### PR TITLE
Fixed "Add new alias" button which was disappearing after adding a new alias. [BO][Shop param][search]

### LINKED ISSUE #21274: [BO][Shop param][search] Add new alias button disappear after adding a new alias
#### Describe the bug

Under Shop param>Search, when I add a new alias, the button "add new alias" disappear.

#### Expected behavior

Same behavior as the "add new tag" button, it should stay.

#### Steps to Reproduce

1. Go to  shop param
2. Click on search
3. Click on add new alias 
4. Add new alias
==>>the alias button has disappeared

**Screenshots**

https://drive.google.com/file/d/1CSmH_ev3mk1QdKjo77wVcZQJP01DteUi/view

Before
Capture d’écran 2020-10-02 à 15 34 56

After
Capture d’écran 2020-10-02 à 15 34 28

#### Additional information

* PrestaShop version: RC1 & 1.7.6.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by roncarino**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | See #21274 by @ngodefroy.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21274.
| How to test?  | See #21274 by @ngodefroy.

The fix is about "add new alias" button in _Shop Parameters > Search_ which wasn't behaving properly, as well explained inside issue PrestaShop#21274 by @ngodefroy.
The commit is just a tiny addition to the if statement in **AdminSearchConfController::initPageHeaderToolbar()**.
On the first click to "Search" `$this->display == null`. When you add a new alias and save instead `$this->display == 'list'`. Despite the fact I would prefer `$this->display` to be equal to `list` at the first side (first click to search); I decided to just allow both situations. This shouldn't impact, in other ways, any other alias process (listing/editing/creation).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21335)

### CODE REVIEW

File: controllers/admin/AdminSearchConfController.php [hunk 1]
```diff
@@ -364,7 +364,7 @@ public function __construct()
 
     public function initPageHeaderToolbar()
     {
-        if (empty($this->display)) {
+        if (empty($this->display) || $this->display == 'list') {
```
Comment (kpodemski) [inline controllers/admin/AdminSearchConfController.php:367]: @roncarino I think we can remove this `if` completely 🤔

Comment (roncarino) [reply controllers/admin/AdminSearchConfController.php:367]: Hi @kpodemski, I wanted to avoid to show the "add new alias" button while we were editing or effectively creating a new alias. 🙂

Comment (kpodemski) [reply controllers/admin/AdminSearchConfController.php:367]: Makes sense 👍

**Review by kpodemski — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @roncarino,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1-D2zkFBdIOB3590xCTcVvEFlZzmJIX_T/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @roncarino & @khouloudbelguith
