### PR TITLE
Remove combination from list

### LINKED ISSUE #24260: [Experimental product page] Add missing 'Remove' feature for combinations listing
### Describe the bug

The QA team explored the experimental product page and reported that 'Remove' feature for combinations listing is missing.

You should be able to click on the remove icon. A confirm modal will ask you if you are sure, if you click on yes the combination is removed and the list is updated.

If you remove the default combination the first one in the list is the new one

#### Additional information

* PrestaShop version: `1.7.8.x`

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Add command to remove combination, along with the endpoint in CombinationController And integrate the click on remove button in the Combination list
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24260
| How to test?      | First enable the experimental product page in `Advanced Parameters > Experimental Features` Then go to edit a product with combinations in experimental page You can click on the remove icon a confirm modal will ask you if you are sure, if you click on yes the combination is removed and the list is updated If you remove the default combination the first one in the list is the new one
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24134)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js [hunk 1]
```diff
@@ -184,6 +189,39 @@ export default class CombinationsManager {
...
+   * @param {HTMLElement} button
+   *
+   * @private
+   */
+  async removeCombination(button) {
+    try {
+      const $deleteButton = $(button);
+      const modal = new ConfirmModal(
+        {
+          id: 'modal-confirm-delete-combination',
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js:202]: Please move selector in map file

**Review by Progi1984 — COMMENTED** [review]
A small comment

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php [hunk 2]
```diff
@@ -171,6 +172,28 @@ public function getListIdsAction(int $productId): JsonResponse
...
+        try {
+            $this->getCommandBus()->handle(new RemoveCombinationCommand($combinationId));
+        } catch (Exception $e) {
+            return $this->json([
+                'error' => $this->getErrorMessageForException($e, $this->getErrorMessages($e)),
+            ], Response::HTTP_BAD_REQUEST);
+        }
+
+        return $this->json([
+            'message' => $this->trans('Successful deletion.', 'Admin.Notifications.Success'),
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php]:
```suggestion
            'message' => $this->trans('Successful deletion', 'Admin.Notifications.Success'),
```

File: admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js (hunk 1 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/edit/combinations-manager.js:202]: It's not really needed because it's never used for selection The id used here is only temporary while we create the confirm modal It's been used this way everywhere else I'm not sure it brings much value 🤔

File: src/Adapter/Product/Combination/Update/CombinationRemover.php [hunk 3]
```diff
@@ -48,16 +52,45 @@ class CombinationRemover
...
     ) {
         $this->productRepository = $productRepository;
         $this->combinationRepository = $combinationRepository;
+        $this->defaultCombinationUpdater = $defaultCombinationUpdater;
+    }
+
+    /**
+     * @param CombinationId $combinationId
+     *
+     * @throws CoreException
```
Comment (matks) [inline src/Adapter/Product/Combination/Update/CombinationRemover.php:78]: I dont know if all the `throws` are needed

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php [hunk 4]
```diff
@@ -171,6 +172,28 @@ public function getListIdsAction(int $productId): JsonResponse
...
+    {
+        try {
+            $this->getCommandBus()->handle(new RemoveCombinationCommand($combinationId));
+        } catch (Exception $e) {
+            return $this->json([
+                'error' => $this->getErrorMessageForException($e, $this->getErrorMessages($e)),
+            ], Response::HTTP_BAD_REQUEST);
+        }
+
+        return $this->json([
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php:192]: Should we return the HTTP code 204 ?

**Review by matks — DISMISSED** [review]
Some suggestions and 1 approval

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php (hunk 4 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php:192]: 204 is for no content, here we return a success message So if we return 204 I can't return the success message and I need to integrate it somewhere else with a data attribute or something

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php [hunk 5]
```diff
@@ -103,7 +103,11 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
             ->add('delete', IconButtonType::class, [
                 'icon' => 'delete',
                 'attr' => [
-                    'class' => 'edit-combination-item tooltip-link',
+                    'class' => 'remove-combination-item tooltip-link',
+                    'data-modal-title' => $this->trans('Warning', 'Admin.Notifications.Warning'),
```
Comment (Julievrz) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php]: IMO we don't need to write 'Warning'. The rest of the message is enough.

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php [hunk 6]
```diff
@@ -103,7 +103,11 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
...
+                    'data-modal-message' => $this->trans('Are you sure you want to delete this item?', 'Admin.Notifications.Warning'),
```
Comment (Julievrz) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php:108]:
```suggestion
                    'data-modal-message' => $this->trans('Are you sure you want to delete this combination?', 'Admin.Catalog.Notification'),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php [hunk 7]
```diff
@@ -103,7 +103,11 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
...
+                    'data-modal-apply' => $this->trans('Yes', 'Admin.Global'),
```
Comment (Julievrz) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php]:
```suggestion
                    'data-modal-apply' => $this->trans('Delete', 'Admin.Actions'),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php [hunk 8]
```diff
@@ -103,7 +103,11 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
...
+                    'data-modal-cancel' => $this->trans('No', 'Admin.Global'),
```
Comment (Julievrz) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Combination/CombinationItemType.php]:
```suggestion
                    'data-modal-cancel' => $this->trans('Cancel', 'Admin.Actions'),
```

**Review by Julievrz — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]
Front LGTM

File: src/Adapter/Product/Combination/Update/CombinationRemover.php (hunk 3 above)
Comment (PierreRambaud) [reply src/Adapter/Product/Combination/Update/CombinationRemover.php:78]: `get` throws exception,
`delete` too, 
`findDefaultCombination` and  ` setDefaultCombination` and `CombinationId` too :sweat_smile: 

This is why phpstorm adds these blocks.
But I'm still convinced that adding throws without explanation or without real throws in methods are useless.
If you change the exception inside methods, does it automatically update phpdocs for everyone? Or phpstan check it too? 

We can't rely on phpstorm configuration

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
@jolelievre One git conflict 😞

**Comment by jolelievre** [comment]
@matks I'm aware much like most of the pending PRs related to the product page But it's useless to fix conflicts for now since they are all blocked by this one https://github.com/PrestaShop/PrestaShop/pull/24168 And will require additional rebase

**Comment by matks** [comment]
> @matks I'm aware much like most of the pending PRs related to the product page But it's useless to fix conflicts for now since they are all blocked by this one #24168 And will require additional rebase

This PR is validated by QA 😄 so in theory if we rebase it we can merge it before #24168. Unless I'm missing a part of the puzzle 🤔 😄 ?

**Comment by jolelievre** [comment]
Oh I didn't see the QA validation, I'm gonna rebase it now then

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @jolelievre & @sarahdib
