### PR TITLE
Fix js error when adding voucher in create order

### LINKED ISSUE #24556: BO - Add new Order page - an error is displayed in the console when adding a voucher
#### Describe the bug

In the BO > Orders > Add new Order page, when we add a voucher => an error is displayed in the console.
BO_order_add_voucher

#### Expected behavior

No error in the console should be displayed

#### Steps to Reproduce

1. Go to BO > Orders > Add new Order page
2. Choose a customer & choose a product
3. Click "Add new voucher" > Set required field > Click save

It was ok with 1774
#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Some JS that is executed a first time when the page load, is executed a second time when the ajax request is performed when adding a cart rule. The JS executed contains variable assignations, some of them were `const` or `let` and so couldn't be re-assigned the second time.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24556
| How to test?      | Please see #24556
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24794)

### CODE REVIEW

File: admin-dev/themes/default/template/controllers/cart_rules/form.js [hunk 1]
```diff
@@ -333,14 +333,14 @@ $('.tab-row.active').removeClass('active');
 $(`#cart_rule_${currentFormTab}`).show();
 $(`#cart_rule_link_${currentFormTab}`).parent().addClass('active');
 
-const date = new Date();
-let hours = date.getHours();
+var date = new Date();
```
Comment (matthieu-rolland) [inline admin-dev/themes/default/template/controllers/cart_rules/form.js]: CI is still running as I write this, but I don't think eslint will tolerate `var`, you could go with `global` or `window` to fix this reassignation issue (same for other places where you used `var` )

```suggestion
window.date = new Date();
```

**Review by matthieu-rolland — COMMENTED** [review]
one feedback 👍

**Review by kpodemski — DISMISSED** [review]
As this is legacy page it LGTM, we'll probably have better quality of JS when this page would be migrated to Symfony :)

File: admin-dev/themes/default/template/controllers/cart_rules/form.js (hunk 1 above)
Comment (matthieu-rolland) [reply admin-dev/themes/default/template/controllers/cart_rules/form.js]: Seems like eslint CI was skipped....  I had to fix something similar, for the same reassignment issue, you can see the conversation here:

https://github.com/PrestaShop/PrestaShop/pull/24356#discussion_r629205063

But since ESlint is skipped, I guess it's up to you 👍

File: classes/controller/AdminController.php [hunk 2]
```diff
@@ -3847,7 +3847,7 @@ protected function copyFromPost(&$object, $table)
     {
         /* Classical fields */
         foreach ($_POST as $key => $value) {
-            if (array_key_exists($key, $object) && $key != 'id_' . $table) {
+            if (property_exists($object, $key) && $key != 'id_' . $table) {
```
Comment (PierreRambaud) [inline classes/controller/AdminController.php]:
```suggestion
            if (array_key_exists($key, get_object_vars($object)) && $key != 'id_' . $table) {
```
Otherwise it will return true for private and protected

File: admin-dev/themes/default/template/controllers/cart_rules/form.js [hunk 3]
```diff
@@ -93,7 +93,7 @@ function updateProductRuleShortDescription(item) {
   else $(`#${id2}_match`).val(length);
 }
 
-const restrictions = new Array('country', 'carrier', 'group', 'cart_rule', 'shop');
+var restrictions = new Array('country', 'carrier', 'group', 'cart_rule', 'shop');
```
Comment (PierreRambaud) [inline admin-dev/themes/default/template/controllers/cart_rules/form.js]: I'm afraid about what will happened if we merge it on 1.7.8.x

I think using `window` object is maybe more appropriate

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !! Thanks @atomiix !!

**Comment by Progi1984** [comment]
Thanks @atomiix & @SD1982
