### PR TITLE
Fix cart rule that can be used more than once per user when it shouldn't

### LINKED ISSUE #25203: FO - 'Total available for each user' in cart rule not considered if the customer is signed in from the checkout page
#### Describe the bug

The 'Total available for each user' in cart rule not considered if the customer is signed in from the checkout page.

#### Steps to Reproduce

1. Create cart rule Check Total available for each User = 1 Set these fields:
1.1. Information:
- Name
- Description
- **Code**

1.2. Conditions:
- Total available = 2
- **Total available for each user =1**

1.3. Actions:
- Discount = 1 euro and click on Save
2. Go to FO > Sign in with john doe > apply the discount > Place the order
3. If you try to apply the cart again impossible
4. Sign out
5. Add a product to cart > In the shopping cart > apply the discount: ok
6. On the checkout page: sign in with john doe: the cart rule should be removed => it is not removed and the order is created with a discount again

178: https://drive.google.com/file/d/1b81nVyBM2bFjXFFbKPYy550uMesG4Tx4/view?usp=sharing
177x: https://drive.google.com/file/d/1FKI9EXBBbqhE6NIJu5H5pTfWZMEy5OKa/view?usp=sharing
1769 => ok: https://drive.google.com/file/d/1eZS5WXun-XeoO_tXoM-kqk15iTNO7yJM/view?usp=sharing

#### Additional information

* PrestaShop version: 177x(PS1776), 178_rc1
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | 
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25203
| How to test?      | See issue #25203
| Possible impacts? | See issues  #19949 and #19960 for possible regressions :/

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25286)

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
WIP, BEHAT TESTS ARE COMING

File: classes/CartRule.php [hunk 1]
```diff
@@ -668,6 +668,17 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+            // also count cart rules that are linked to a cart that is not attached to an order yet
+            if ($alreadyInCart) {
+                $quantityUsedWithoutOrder = Db::getInstance()->getValue('
+                    select count(*)
+                    from ps_cart_cart_rule ccr
+                    LEFT JOIN ps_cart c on c.id_cart = ccr.id_cart
+                    where c.id_customer = ' . $cart->id_customer . '
+                    AND NOT EXISTS (SELECT null FROM ps_orders o where o.id_cart = ccr.id_cart)'
+                );
+                $quantityUsed += $quantityUsedWithoutOrder;
```
Comment (Progi1984) [inline classes/CartRule.php]:
```suggestion
```

File: classes/CartRule.php [hunk 2]
```diff
@@ -668,6 +668,17 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
 			AND ocr.`id_cart_rule` = ' . (int) $this->id . '
 			AND ' . (int) Configuration::get('PS_OS_ERROR') . ' != o.`current_state`
 			');
+            // also count cart rules that are linked to a cart that is not attached to an order yet
+            if ($alreadyInCart) {
+                $quantityUsedWithoutOrder = Db::getInstance()->getValue('
```
Comment (Progi1984) [inline classes/CartRule.php]:
```suggestion
                $quantityUsed += (int) Db::getInstance()->getValue('
```

**Review by Progi1984 — COMMENTED** [review]
Small feedbacks (and behat tests missing)

**Comment by matthieu-rolland** [comment]
> Small feedbacks (and behat tests missing)

yes, as I wrote above behat tests are coming, and this PR is WIP, I opened it quickly to discuss a potential fix with other maintaienrs, so that they could see it. 👍   

This code is not definitive.

File: classes/CartRule.php [hunk 3]
```diff
@@ -668,9 +668,21 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+            if ($alreadyInCart) {
+                // sometimes a cart rule is already in a cart, but the cart is not yet attached to an order (when logging
+                // in for example), these cart rules are not taken into account buy the query above:
+                // so we count cart rules that are already linked to the current cart but not attached to an order yet.
+                $quantityUsed += (int) Db::getInstance()->getValue('
+                    select count(*)
+                    from ps_cart_cart_rule ccr
+                    LEFT JOIN ps_cart c on c.id_cart = ccr.id_cart
+                    where c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . '
+                    AND NOT EXISTS (SELECT null FROM ps_orders o where o.id_cart = ccr.id_cart)'
```
Comment (matks) [inline classes/CartRule.php]:
```
                    SELECT null FROM ps_orders o where o.id_cart = ccr.id_cart'
```
It works ? 😄  "SELECT null" ?

Comment (matthieu-rolland) [reply classes/CartRule.php]: yes :D 
But I'm working on another fix, I realized this fix "works" but not in all cases

Comment (matthieu-rolland) [reply classes/CartRule.php]: I think the fix is good now 👍

File: classes/CartRule.php [hunk 4]
```diff
@@ -668,9 +668,21 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
 			AND ocr.`id_cart_rule` = ' . (int) $this->id . '
 			AND ' . (int) Configuration::get('PS_OS_ERROR') . ' != o.`current_state`
 			');
-            // When checking the cart rules present in that cart the request result is accurate
-            // When we check if using the cart rule one more time is valid then we increment this value
-            if (!$alreadyInCart) {
+
+            if ($alreadyInCart) {
+                // sometimes a cart rule is already in a cart, but the cart is not yet attached to an order (when logging
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
                // Sometimes a cart rule is already in a cart, but the cart is not yet attached to an order (when logging
```

File: classes/CartRule.php [hunk 5]
```diff
@@ -668,9 +668,21 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+                // in for example), these cart rules are not taken into account buy the query above:
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
                // in for example), these cart rules are not taken into account by the query above:
```

File: classes/CartRule.php [hunk 6]
```diff
@@ -668,9 +668,21 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+                // so we count cart rules that are already linked to the current cart but not attached to an order yet.
+                $quantityUsed += (int) Db::getInstance()->getValue('
+                    select count(*)
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
                    SELECT count(*)
```

File: classes/CartRule.php [hunk 7]
```diff
@@ -668,9 +668,21 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+                    from ps_cart_cart_rule ccr
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
                    FROM ps_cart_cart_rule ccr
```

File: classes/CartRule.php [hunk 8]
```diff
@@ -668,9 +668,21 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+                    LEFT JOIN ps_cart c on c.id_cart = ccr.id_cart
+                    where c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . ' AND ccr.id_cart_rule = ' . (int) $this->id . '
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
                    WHERE c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . ' AND ccr.id_cart_rule = ' . (int) $this->id . '
```

File: tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php [hunk 9]
```diff
@@ -479,4 +483,51 @@ public function checkCartRuleContextualValue(TableNode $table)
...
+
+    /**
+     * @When /^I create an order with discount "(.+)" for current cart$/
+     *
+     * @param string $cartRuleName
+     */
+    public function createOrderForCurrentCart(string $cartRuleName)
+    {
+        $cart = $this->getCurrentCart();
+        $order = new Order();
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php]: This creation of Order manually may hide a lot of things we don't expect that could influence the computing later.
It would be better (if not too complicated) to either:
- use the `Dummy_Payment` and call `$paymentModule->validateOrder` on the current cart, a bit like it is done in the handler https://github.com/PrestaShop/PrestaShop/blob/26b6ac8589635729306a506ae1b823f4587479bc/src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php#L102
- or use the command directly, although it mixes two different contexts, and CartContext would become tied to the OrderContext

File: tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/usage_limit_per_user.feature [hunk 10]
```diff
@@ -0,0 +1,29 @@
...
+    Given country "US" is enabled
+    And there is customer "testCustomer" with email "pub@prestashop.com"
+    And customer "testCustomer" has address in "US" country
+
+  Scenario: Cart rule usage limit is detected when the cart rule is created anonymously then assigned to a customer who already used it
+    Given I create an empty cart "dummy_cart" for customer "testCustomer"
+    And shop configuration for "PS_CART_RULE_FEATURE_ACTIVE" is set to 1
+    And there is a cart rule named "limitedCartRule" that applies an amount discount of 1.0 with priority 1, quantity of 2 and quantity per user 1
+    And cart rule "limitedCartRule" has a discount code "foo1"
+    And there is a product in the catalog named "product1" with a price of 19.812 and 1000 items in stock
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/usage_limit_per_user.feature]: I think this part could be in the background In case we need to add other scenarios later

File: tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php (hunk 9 above)
Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php]: done !

**Review by jolelievre — DISMISSED** [review]
Thanks @matthieu-rolland

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

File: classes/CartRule.php [hunk 11]
```diff
@@ -668,9 +668,22 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
...
+                // Sometimes a cart rule is already in a cart, but the cart is not yet attached to an order (when logging
+                // in for example), these cart rules are not taken into account by the query above:
+                // so we count cart rules that are already linked to the current cart but not attached to an order yet.
+
+                $quantityUsed += (int) Db::getInstance()->getValue('
+                    SELECT count(*)
+                    FROM ps_cart_cart_rule ccr
+                    INNER JOIN ps_cart c ON c.id_cart = ccr.id_cart
+                    LEFT JOIN ps_orders o ON o.id_cart = c.id_cart
+                    WHERE c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . ' AND ccr.id_cart_rule = ' . (int) $this->id . ' AND o.id_order IS NULL
```
Comment (matks) [inline classes/CartRule.php:682]:
```suggestion
                    WHERE c.id_customer = ' . $cart->id_customer . ' AND c.id_cart = ' . $cart->id . ' AND ccr.id_cart_rule = ' . (int) $this->id . ' AND o.id_order IS NULL
```
Should we type-hint every ID? There are 3 integers on this line, only one is type-hinted.

**Review by matks — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matthieu-rolland !

With @khouloudbelguith , we checked this PR : The issue is fixed, and the two issues in possible impacts are also still OK. We did some regression tests on cart rules in FO and BO, all is clear !

So it's QA :heavy_check_mark: , thanks !

**Comment by atomiix** [comment]
Thanks everyone!
