### PR TITLE
Integrate new header design for product page

### LINKED ISSUE #15330: Confusing display of VAT in product BO, when VAT disabled
**Scenario**
Merchant is not a VAT payer, so disable VAT in International > VAT.

**What's wrong - product admin**
- It shows inputs for price without tax and with tax.
- It shows a tax selection dropdown.
- It allows you to select VAT, even if it's not applied to the price in the end.

**Solution**
A) Hide the fields that are not required and display only "Price"
B) Keep it, but add a message - VAT disabled, VAT will not take effect.

PS version: 1.7.6.1

______

+ Thumbs up to the dev team for improving the display on FO when VAT is disabled. In first versions of PS 1.7, it was still showing “Total (tax incl.)” and stuff like that. This seems to be fixed now. 👍

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Integrate new header design based on the most recent mockup and add a few new features:<br>- display prices (with tax rate if specified)<br>- display stock (with color code depending on the stock level)<br>- display product references<br>- new component to switch product type, looks like the create product modal
| Type?             | new feature
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #15330
| How to test?      | Check that the value in the header are updated as expected after submit (no automatic js update is handled) You can also test the component to switch product type
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27233)

### New display preview
Capture d’écran 2022-01-06 à 12 47 05

### Specs
https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type

### Breaking Changes

- `LocalizationExtension` now has three more arguments in its constructor (built by DI)
- `ProductFormDataProvider` has many less arguments in its constructor since creation data has been cleaned a lot
- `ProductTypeUpdater` has a new parameter in its constructor `ProductStockUpdater $productStockUpdater`
- `ProductStockUpdater` has a new parameter `MovementReasonRepository $movementReasonRepository`
- `GetProductForEditingHandler` has a new parameter `Configuration` adapter service
- `PricingType` form type has a new parameter `$taxEnabled`

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Seems like it breaks the CI, while front-end modifications looks ok to me

File: src/PrestaShopBundle/Form/Admin/Sell/Product/ProductTypeType.php [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+namespace PrestaShopBundle\Form\Admin\Sell\Product;
+
+use PrestaShop\PrestaShop\Core\Domain\Product\ValueObject\ProductType;
+use PrestaShop\PrestaShop\Core\Form\FormChoiceAttributeProviderInterface;
+use PrestaShop\PrestaShop\Core\Form\FormChoiceProviderInterface;
+use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
+use Symfony\Component\OptionsResolver\OptionsResolver;
+
+class ProductTypeType extends ChoiceType
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/ProductTypeType.php:37]: ProductTypeType ? 😄 
is that intended and if yes, could we find a name less confusing ?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header.html.twig [hunk 2]
```diff
@@ -22,59 +22,87 @@
...
-      <div class="row">
-        <div class="col-md-10 product-header-form">
-          {% block product_header_form %}
-            {% form_theme productForm.header '@PrestaShop/Admin/Sell/Catalog/Product/FormTheme/header.html.twig' %}
-            {{ form_row(productForm.header) }}
-          {% endblock %}
+            {% for group_label, choice in productForm.pricing.tax_rules_group_id.vars.choices %}
+              {% if choice is selectedchoice(productForm.pricing.tax_rules_group_id.vars.value) %}
+                {% set taxRate = choice.attr['data-tax-rate'] %}
+                {% dump(choice) %}
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header.html.twig]: Looks like you forgot some `dump()` 😄

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 3]
```diff
@@ -109,6 +109,112 @@ $product-page-padding-bottom: 80px !default;
...
+    $product-cover-size: 110px;
+
+    .product-header-cover {
+      max-width: $product-cover-size;
+
+      .image_preview-widget {
+        width: $product-cover-size;
+        height: $product-cover-size;
+
+        img {
```
Comment (Hlavtox) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: I would just use .img-fluid on the image, no need for these styles. Set width and height parameters on the image directly to improve CLS in modern browsers.

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 4]
```diff
@@ -109,6 +109,112 @@ $product-page-padding-bottom: 80px !default;
...
+    }
+
+    $product-cover-size: 110px;
+
+    .product-header-cover {
+      max-width: $product-cover-size;
+
+      .image_preview-widget {
+        width: $product-cover-size;
+        height: $product-cover-size;
```
Comment (Hlavtox) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: Avoid using fixed height. If image is bigger for any reason, you will have trouble, just let it flow ;-)

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig [hunk 5]
```diff
@@ -24,7 +24,7 @@
  *#}
 
 <div id="external-combination-tab" class="form-horizontal row justify-content-md-center d-none">
```
Comment (Hlavtox) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig]: You can remove `row justify-content-md-center` and the inside `<div class="col">`

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 4 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: The widget container has a fixed height, but the image inside is floating It has auto-size but max-width and height The purpose is to let it adapt inside a restricted container

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig]: Nice catch, thanks!

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig]: I think you are pleased to see all the useless divs I removed in this PR 😅

File: src/PrestaShopBundle/Form/Admin/Sell/Product/ProductTypeType.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/ProductTypeType.php:37]: I couldn't find better, all form types class names end with Type by convention
And this one is used to edit the "product type" So even though I agree it's not ideal it's the less worse choice 😅

Calling it simply `ProductType` would be confusing because based on the usual convention it would imply a form type for Product

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig (hunk 5 above)
Comment (Hlavtox) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/external_tab.html.twig]: Yes! 😄 You know I am watching 👀

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 3 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: Ok I removed that part, because you're right my image already used the `img-fluid` class However I still need to limit the size of its container But it's the only one that is limited now

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header.html.twig (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header.html.twig]: Nice catch 😅

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 3 above)
Comment (Hlavtox) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: Yes, play with the width of the container, let everything inside adapt. :-)

**Comment by Hlavtox** [comment]
Joe don't forget we need to somehow integrate this. 🤔 Or just merge this and we can play with the footer later. 👍

desktop
mobile

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php [hunk 6]
```diff
@@ -368,7 +367,6 @@ private function renderEditProductForm(FormInterface $productForm, int $productI
             'productForm' => $productForm->createView(),
             'statsLink' => $this->getAdminLink('AdminStats', ['module' => 'statsproduct', 'id_product' => $productId]),
```
Comment (Hlavtox) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]: @jolelievre Can you check this line? I am on develop and the button is displayed even if I uninstalled the related stat modules. Maybe we could check if the module is active. ;-)

**Comment by jolelievre** [comment]
Hi @Hlavtox 

regarding the sales button maybe you're right but it's not the purpose of this PR, is it handled in the legacy page to disable this button when no stat modules are installed?

And I didn't forget about the footer for mobiles don't worry But again it's not the scope of this PR, even the header is not really responsive for now I think we'll have a dedicated PR to handle the responsiveness of this page later

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php (hunk 6 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]: I added a check, the link is only added when module `statsproduct` is installed and enabled

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 7]
```diff
@@ -1275,50 +1271,58 @@ $product-page-padding-bottom: 80px !default;
...
 
-      .product-type-choice {
-        position: relative;
-        width: 100%;
-        max-width: 350px;
-        padding-right: 3rem;
-        margin: 0.25rem 0;
-        text-align: left;
+  select {
+    display: none;
```
Comment (Hlavtox) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss:1289]: ❗

File: src/PrestaShopBundle/Form/Admin/Sell/Product/ProductTypeType.php (hunk 1 above)
Comment (matks) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/ProductTypeType.php:37]: Agreed.

Only idea I have is to use something else for "product type". "Product classification"? "Product specificity"?

File: admin-dev/themes/new-theme/js/pages/product/product-const.ts [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+ */
+
+export default {
+  PRODUCT_TYPE: {
+    STANDARD: 'standard',
+    PACK: 'pack',
+    VIRTUAL: 'virtual',
+    COMBINATIONS: 'combinations',
+  },
+};
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/product/product-const.ts]: product-const.ts looks like it's not a good name, it's redundant because it's already inside the product folder, I would call it `constants` and that's it

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 9]
```diff
@@ -109,6 +109,105 @@ $product-page-padding-bottom: 80px !default;
   }
 
   // Components
+  .product-header-v2 {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss:112]: Do we need to version the header inside a classname? can't we just use product-header?

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 10]
```diff
@@ -109,6 +109,105 @@ $product-page-padding-bottom: 80px !default;
...
+    display: flex;
+    flex-direction: row;
+    gap: 25px;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss]:
```suggestion
    gap: 1.5625rem;
```

I think if we use `rem` on margin and paddings, no reason to not use it on gaps, as we wants it to adapt on font-size change

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 11]
```diff
@@ -109,6 +109,105 @@ $product-page-padding-bottom: 80px !default;
...
+      flex-grow: 1;
+    }
+
+    $product-cover-size: 110px;
+
+    .product-header-cover {
+      width: $product-cover-size;
+      max-width: $product-cover-size;
+      height: $product-cover-size;
+      max-height: $product-cover-size;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: Max width and max-height are useless, the width and height can't change if they are fixed

Why no just use img-fluid? The image should adapt depending on his width but maybe there are some PHP stuff that force the size anyway

File: admin-dev/themes/new-theme/js/pages/product/product-const.ts (hunk 8 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/product-const.ts]: Ok but then it means we should also rename `product-event-map.js` `product-map.js` and so on
I'm fine with it but maybe in a future PR I just renamed the constant file for now

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/product-const.ts]: Well, you're damn right about this, but then another question happens about components name 😆

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 9 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss:112]: Seen the comment after this line, idc!

Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss:112]: Hmm that's weird I had noted some comments for this but they seem to have disappeared
Ah no it's on the `.product-page-v2` class but it's the same principle for this one

For now we have two different pages at the same time but they share the same CSS so sometimes I need to target only the v2 specifically to avoid breaking the legacy one Ideally we should have created a dedicated new scss file but I guess we didn't because it was more convenient this way

Anyway this will be cleaned later when the legacy page is remove, I won't need this extra scope for v2 page

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 10 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: You're right I copied this from the mockup directly I converted the other ones but I forgot this one, my bad

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 11 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: Actually, since I'm in a flex container the max-width and height are the most important Without it the div was too large despite the presence of width/height

Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: As I already explained to @Hlavtox the image is already in `img-fluid` This class doesn't target the image it targets its div container which must be restricted and keep a fixed size (the flex container tries to make it larger if I don't restrict it)

Comment (Hlavtox) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: `flex-grow:0;`

Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss]: Thanks @Hlavtox `flex-grow: 0;` works nicely indeed!

I just left a max-width though because the image I use is still wider than the expected cover. We don't have an image type with 110px size and I don't think it's worth creating a new image type for this.

**Review by matks — DISMISSED** [review]
OK for me.
I'm not good enough to validate the CSS 🤷‍♂️

**Review by NeOMakinG — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
Unfortunately, you have to rebase your PR :D

**Comment by jolelievre** [comment]
@matks @NeOMakinG @PierreRambaud PR has been rebased, it needs re-approval to go back to QA please :)

**Review by matks — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @jolelievre,

I found some issues:
**Issue1**

1. Enable Experimental product page
2. Go to BO > Catalog > Products page
3. Edit any product V2
4. Click on the type of this product => A modal is opened
5. Click on the "Change product type" button without changing the product type
6. See an error 

image

**Second issue**
When using a mobile => the header is NOK, is this the scope of the PR? 
image

**Third issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page
3. Try to add a new product with V2
4. Choose a product with combination / a pack product or product with combinations and add a product
5. See error => the type of product is incorrect

https://user-images.githubusercontent.com/16067358/151415324-5958f4c0-2cb5-4a53-98c0-06599419fd7a.mp4

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith I can do the responsivity after this is merged. 🙂

**Comment by jolelievre** [comment]
Thank you @khouloudbelguith I just fixed the two bugs:
- product creation selected type ignored
- type switching we disable the current type so that it can't be picked

About the mobile display, indeed it's not in the scope of this PR.

@Hlavtox if you are motivated to handle this that's great! Maybe in cooperation with @NeOMakinG Because the whole page is gonna need some responsive love at some point, not just the header (or footer ^^)

**Review by matthieu-rolland — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @jolelievre,

I have some issues:

**First issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products V2
3. Create a standard product or a Pack of products or a Virtual product
4. See an error in the header: 0 in green & in stock label 
image
=> 
It should be `red background` & `out of stock label`
5. In the Stock Tab > Set Low stock level with 2 and save
6. See error in the header 
image
=> 
It should be `red background` & `out of stock label`

**Second issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products V2
3. Create a product with combinations
4. Generate combinations
5. The Stock is not displayed for this type 
image


**Third issue**
It could be related to this issue: https://github.com/PrestaShop/PrestaShop/issues/27054

1. Enable Experimental product page
2. Go to BO > Catalog > Products V2
3. Create a product, in the Pricing Tab > Tax rule = `EU VAT For Virtual Products` & save
4. Refresh the page
5. See an error in the header > the tax rule is changing 

I attached a screen record
https://user-images.githubusercontent.com/16067358/151776764-a893d7af-345a-422e-9964-ad722a18da89.mp4

**Fourth issue**
1. Go BO > International > Localization > Import the Algeria pack
2. Change the employee profile to Arabic
2. Go to BO > Catalog > Products V2
3. Create a product V2 > Choose a type & add new product > See error 
image
4. Edit a product V2 > See error  
image

**Fifth issue**
1. Go to BO >  International > Localization > Languages Tab
2. Create manually a language => in my case, I used this example
image
3. Change the employee language to this new language created
4. Go to BO > Catalog > Products V2
3. Create a product
4. See an error in the header => the currency symbol is not displayed
image

**Sixth issue**

1. In fact when creating a product with a too-long data
2. In the header, the title of the product will be not well displayed as before => I think it could be a problem 
image
 before, it was 
image

**Seventh issue**
1. Go to BO > Shop Parameters > Product Settings > Disable `Enable stock management` 
image
2. Go to BO > Catalog > Products V2
3. Create a product V2 > Choose a type & add new product > See error 
image
4. Edit a product V2 > See error  
image


Thanks!

**Comment by jolelievre** [comment]
Thank @khouloudbelguith 

I fixed a few bugs from what you discovered:

### First issue
Nice catch my condition was wrong to detect the state, but most of all I didn't think about using the custom labels You're right it's better this way We need to confirm this with @MatShir and @TristanLDD though Besides there is no custom label for "low stock" so I always use the default wording

### Second issue
For combinations, I didn't display because each combination has its stock, and the Stock tab is not visible so I assumedthe preview worked the same If we decide to handle this use case différently it's another issue for me @MatShir what do you think?

### Third issue
We will indeed have the same bug as in #27054 because I use the same values and the bug has not been fixed However, what you showed in the video is différent the tax rate changes at each page refresh This one I was not able to reproduce The tax rate may be incorrect depending on the country but it's always the same for me What country did you choose in your Employee settings or in the default country?

### Fourth issue
I fixed as well as I could, the bug was because the value was converted in Arabic display like this for example `١٨٫٠٠٠٠٠٠` which is not usable for the CLDR So instead I used the float value but it's not exactly displayed in Arabic... I was inspired by the front behaviour where latin characters are used in the product previews as well So it makes sense that the preview follows the same principle. However, inputs and stock preview use Arabic characters but I don't know if it's the wanted behaviour? I'd like your opinion (and the one from @MatShir) on this, is this ok to mix both use of characters depending on the need? or should we use one type of character everywhere?

Capture d’écran 2022-02-01 à 00 35 09

Capture d’écran 2022-02-01 à 00 34 44

### Fifth issue
Fixed based on the same fallback used on front.

### Sixth issue
I think the problem is not really about long names in this case, but rather long references. I updated the display a little so that all info is correctly displayed. Though I didn't go into details for all kind of screen sizes so when the width gets smaller and smaller some issues might happen. But this will have to be handled in the PR for responsiveness on this page. For now the quick fix seems enough for me.

### Seventh issue
Fixed

**Comment by MatShir** [comment]
> Hi @jolelievre,
> 
> I have some issues:
> 
> **First issue**
> 1. Enable Experimental product page
> 2. Go to BO > Catalog > Products V2
> 3. Create a standard product or a Pack of products or a Virtual product
> 4. See an error in the header: 0 in green & in stock label 
> image
> => 
> It should be `red background` & `out of stock label`
> 5. In the Stock Tab > Set Low stock level with 2 and save
> 6. See error in the header 
> image
> => 
> It should be `red background` & `out of stock label`

The wording here is not meant to be adaptive to the label.

**Second issue**

> 1. Enable Experimental product page
> 2. Go to BO > Catalog > Products V2
> 3. Create a product with combinations
> 4. Generate combinations
> 5. The Stock is not displayed for this type 
> image
> 

For a product with combination, the stock displayed on the header will be the total amount of the combination. The low stock display won't be available here for this type of product.

**Fourth issue**

> 1. Go BO > International > Localization > Import the Algeria pack
> 2. Change the employee profile to Arabic
> 2. Go to BO > Catalog > Products V2
> 3. Create a product V2 > Choose a type & add new product > See error 
> image
> 4. Edit a product V2 > See error  
> image
> 

All the RTL and Arabic language compliance is not yet supported, we will create a dedicated issue to handle it :)

**Comment by jolelievre** [comment]
Hi @khouloudbelguith and @MatShir 

based on our discussion with Mateus and his decisions I made the following modifications:
- the product with combinations: the stock is displayed it is the sum of all combinations' quantity (still not updated dynamically with JS only on refresh) We don't handle low stock state for combinations
- we always use the same out of stock labels regardless of their customized value
- I wasn't able to reproduce your bug with tax rate that changes at each refresh, but I made a small modif in this component so maybe it will fix the bug on your side @khouloudbelguith

**Review by NeOMakinG — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by jolelievre** [comment]
Hi @matks @matthieu-rolland and @NeOMakinG 

I need your re-approval on this one after rebase to resolve conflicts, nothing changed

**Review by matks — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @jolelievre,

I have some issues:
**First issue**

1. Enable Experimental product page
2. Go to BO > Catalog > Products V2
3. Create a new product
4. See error => the `product-field-label` "tax included" is not displayed & the` tax rule = 0` is displayed

image

**Before**, we have this
image

**Second issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products V2
3. Edit a standard simple product with stock different from 0 
image
4. Change product type to "Product with combinations"
5. In the Combinations Tab > Generate some combinations 
6. Refresh the page
7. See error => the stock in the header is not updated 
image

Is it normal behavior because of this?
`the product with combinations: the stock is displayed it is the sum of all combinations' quantity (still not updated dynamically with JS only on refresh) We don't handle low stock state for combinations`

I checked FO => OK

>Third issue
We will indeed have the same bug as in https://github.com/PrestaShop/PrestaShop/issues/27054 because I use the same values and the bug has not been fixed However, what you showed in the video is différent the tax rate changes at each page refresh This one I was not able to reproduce The tax rate may be incorrect depending on the country but it's always the same for me What country did you choose in your Employee settings or in the default country?


About this issue, I think because if I edit this tax rule => I have different taxes for different countries
image

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Don't forget to check how it behaves with VAT disabled. A lot of new merchants are not VAT payers.

**Comment by khouloudbelguith** [comment]
> @khouloudbelguith Don't forget to check how it behaves with VAT disabled. A lot of new merchants are not VAT payers.

@Hlavtox, thanks a lot :slightly_smiling_face:

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 

I fixed the first two issues, for stock it s now reset when the product is switched to Combinations type This was discussed with @MatShir the spec needs to be updated accordingly. I added a warning in the modal as well with a temporary text:
Capture d’écran 2022-02-16 à 18 00 53

The wording will need to be approved or improved by @Julievrz 

However, regarding the third issue @khouloudbelguith I am still unable to reproduce it. I also have different tax rates based on the country for this tax rule but still, I always get 24%.

Maybe it is related to the shop default country, or the country of the employee. What are the settings for those two configurations? (I use English as my employee's language but France as the shop's default country)

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

>However, regarding the third issue @khouloudbelguith I am still unable to reproduce it. I also have different tax rates based on the country for this tax rule but still, I always get 24%.
Maybe it is related to the shop default country, or the country of the employee. What are the settings for those two configurations? (I use English as my employee's language but France as the shop's default country)


Yes, In my case, I installed this PR with English language & France country.

Thanks!

**Comment by jolelievre** [comment]
@khouloudbelguith ok it's weird same for me...

If it's the only issue blocking at the end maybe we can open a dedicated issue, to see if someone else reproduces it Because right now I can't do much sadly 🤷‍♂️

**Review by PierreRambaud — DISMISSED** [review]

**Comment by matks** [comment]
@jolelievre what do we do for this PR?

**Comment by jolelievre** [comment]
@matks I had to rebase it and fix the stock reset for multishop case in behat tests It's reviewable again now! (@PierreRambaud if you can re-approve it as well please?)

@khouloudbelguith I tried to reproduce the bug about switching tax rate again without success I don't think it should block this PR instead I suggest adding this use case to this issue https://github.com/PrestaShop/PrestaShop/issues/27054 since it's probably related Is it ok for you?

**Review by NeOMakinG — DISMISSED** [review]

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 12]
```diff
@@ -109,6 +109,112 @@ $product-page-padding-bottom: 80px !default;
...
+    > * {
+      flex-grow: 1;
+    }
+
+    $product-cover-size: 110px;
+
+    .product-header-cover {
+      flex-grow: 0;
+      min-width: $product-cover-size;
+      max-width: $product-cover-size;
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss:131]: If you define min & max at the same size, why not define directly the `width` ?

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss [hunk 13]
```diff
@@ -1058,11 +1138,61 @@ $product-page-padding-bottom: 80px !default;
   }
 }
 
+// We use this class to scope the modifications that only target product page v2
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/scss/pages/product/product_page.scss:1149]:
```suggestion
// We use this class to scope modifications that only target product page v2
```

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 12 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss:131]: Because the element is in a flex container so its width adapts automatically to the other elements Basically the `width` attribute is not really taken into account So the way I found to limit the size of this element was with min and max

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 13 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss:1149]: I think both are correct, or at least understandable The PR already has one approval so if it's the only feedback I'm not sure it's worth blocking the PR for this 😅

File: src/PrestaShopBundle/Twig/Extension/LocalizationExtension.php [hunk 14]
```diff
@@ -43,24 +46,72 @@ class LocalizationExtension extends AbstractExtension
...
+     * @param Currency|null $contextCurrency
      */
-    public function __construct(string $contextDateFormatFull, string $contextDateFormatLight)
-    {
+    public function __construct(
+        string $contextDateFormatFull,
+        string $contextDateFormatLight,
+        Repository $localeRepository,
+        $contextLanguage,
+        ?Currency $contextCurrency
```
Comment (Progi1984) [inline src/PrestaShopBundle/Twig/Extension/LocalizationExtension.php:76]: Please define BC Breaks

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig [hunk 15]
```diff
@@ -0,0 +1,106 @@
...
+          {% if choice.data == productData.pricing.tax_rules_group_id %}
+            {% set taxRate = choice.attr['data-tax-rate'] %}
+          {% endif %}
+        {% endfor %}
+
+        {# If tax rate is defined display it in the label #}
+        {% if taxRate %}
+          {{ 'tax incl. (tax rule: %taxRate%%)'|trans({'%taxRate%': taxRate|round(2)}, 'Admin.Catalog.Feature') }}
+        {% else %}
+          {{ 'tax incl.'|trans({'%taxRate%': taxRate|round(2)}, 'Admin.Catalog.Feature') }}
```
Comment (Progi1984) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig]: Shouldn't we use the precision rather than `2` ?

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php [hunk 16]
```diff
@@ -98,30 +73,18 @@ class ProductFormDataProvider implements FormDataProviderInterface
...
      * @param CommandBusInterface $queryBus
-     * @param bool $defaultProductActivation
-     * @param int $mostUsedTaxRulesGroupId
-     * @param int $defaultCategoryId
-     * @param CategoryDataProvider $categoryDataProvider
      * @param int $contextLangId
      * @param int $defaultShopId
      * @param int|null $contextShopId
      */
     public function __construct(
```
Comment (Progi1984) [inline src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php:88]: Could you define the BC Break ?

File: src/Adapter/Product/Update/ProductTypeUpdater.php [hunk 17]
```diff
@@ -60,22 +62,30 @@ class ProductTypeUpdater
...
      * @param VirtualProductUpdater $virtualProductUpdater
+     * @param ProductStockUpdater $productStockUpdater
      */
     public function __construct(
         ProductRepository $productRepository,
         ProductPackUpdater $productPackUpdater,
         CombinationDeleter $combinationDeleter,
-        VirtualProductUpdater $virtualProductUpdater
+        VirtualProductUpdater $virtualProductUpdater,
+        ProductStockUpdater $productStockUpdater
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductTypeUpdater.php:82]: Could you define the BC Break ?

File: src/Adapter/Product/Stock/Update/ProductStockUpdater.php [hunk 18]
```diff
@@ -80,17 +86,20 @@ class ProductStockUpdater
...
      * @param ProductMultiShopRepository $productRepository
      * @param StockAvailableMultiShopRepository $stockAvailableRepository
+     * @param MovementReasonRepository $movementReasonRepository
      * @param Configuration $configuration
      */
     public function __construct(
         StockManager $stockManager,
         ProductMultiShopRepository $productRepository,
         StockAvailableMultiShopRepository $stockAvailableRepository,
+        MovementReasonRepository $movementReasonRepository,
```
Comment (Progi1984) [inline src/Adapter/Product/Stock/Update/ProductStockUpdater.php:97]: Could you define the BC Break ?

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 12 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss:131]: Ok. May be @NeOMakinG has a best solution ?

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

File: admin-dev/themes/new-theme/scss/pages/product/product_page.scss (hunk 12 above)
Comment (Hlavtox) [reply admin-dev/themes/new-theme/scss/pages/product/product_page.scss:131]: Don't lose time with CSS, just make it so it works code wise, we will do the styling and HTML with Valentin if needed. 👍

File: src/Adapter/Product/Stock/Update/ProductStockUpdater.php [hunk 19]
```diff
@@ -118,6 +128,57 @@ public function update(ProductId $productId, ProductStockProperties $properties,
...
+     * @throws CoreException
+     * @throws ProductStockException
+     */
+    public function resetStock(ProductId $productId, ShopConstraint $shopConstraint): void
+    {
+        if ($shopConstraint->forAllShops()) {
+            $shops = $this->productRepository->getAssociatedShopIds($productId);
+        } else {
+            $shops = [$shopConstraint->getShopId()];
+        }
```
Comment (atomiix) [inline src/Adapter/Product/Stock/Update/ProductStockUpdater.php:152]: What about groups? 🤔

Comment (matthieu-rolland) [reply src/Adapter/Product/Stock/Update/ProductStockUpdater.php:152]: I'm not sure either... 

For now this method is always given a "all stop" context, and the product page cannot be accessed in group shop, maybe it's the reason ?

@jolelievre if you could enlighten us ? 🤔

**Review by matthieu-rolland — COMMENTED** [review]
LGTM overall, there's just a clarification is needed about shop context and stock reset

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig (hunk 15 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig]: Nope, it's not a price which is displayed here It's purely informational to remind the value of the tax rate so 2 decimals are more than enough IMHO

File: src/Adapter/Product/Stock/Update/ProductStockUpdater.php (hunk 19 above)
Comment (jolelievre) [reply src/Adapter/Product/Stock/Update/ProductStockUpdater.php:152]: Product entity cannot be edited in the shop group context which is why only single and All shops context are handled
In other parts of the code I added a check though that throws an exception when a group constraint is used, I'll add this safety here as well!

Comment (jolelievre) [reply src/Adapter/Product/Stock/Update/ProductStockUpdater.php:152]: Even if technically for now the method is only called with an All shops constraint, I built in a way that can be potentially used for other use cases I didn't want to explicitly bind it to the All shops context

So it's a lot better to add this extra check indeed!

**Comment by jolelievre** [comment]
@Progi1984 @atomiix @matthieu-rolland I just handled your feedback it should be fine now

If you have other questions don't hesitate to direct message me, I'd like this one to be approved as fast as possible since it brings a lot of value to the page (and many conflicts to be expected on other PRs so it's better to anticipate them)

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by khouloudbelguith — DISMISSED** [review]
Hi @jolelievre,

Could you please check the Conflicting files?

Thanks!

**Comment by jolelievre** [comment]
Thanks @khouloudbelguith 

I just rebased and fixed the conflicts it should be good now If @PierreRambaud @Progi1984 and/or @NeOMakinG can reapprove it it's ready for QA

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig [hunk 20]
```diff
@@ -0,0 +1,106 @@
...
+
+<div class="product-header-details">
+{% block header_summary %}
+  {% set productData = productForm.vars.data %}
+  <div class="product-header-summary">
+    <div class="product-field-preview">
+      <div class="product-field-value">
+        {# It is important to use vars.data and not vars.value because value contains the localized value which may
+         # not be written with numeric characters anymore depending on the language but data is the initial float data.
+         #}
```
Comment (atomiix) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/header-details.html.twig]: Just a suggestion to make the comment closer to the line related
```suggestion
  {# It is important to use vars.data and not vars.value because value contains the localized value which may
   # not be written with numeric characters anymore depending on the language but data is the initial float data.
   #}
  {% set productData = productForm.vars.data %}
  <div class="product-header-summary">
    <div class="product-field-preview">
      <div class="product-field-value">
```

**Review by atomiix — DISMISSED** [review]

**Comment by jolelievre** [comment]
Thanks @atomiix I moved the comment

If you and someone else could approve this PR it would be great, it's been waiting to go back to its final QA for more than a month now 😅

**Review by atomiix — DISMISSED** [review]

**Comment by jolelievre** [comment]
@matks or @NeOMakinG you already approved this one in the past, if you can do it again it would be awesome ^^

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by khouloudbelguith — DISMISSED** [review]
Hi @jolelievre,

I checked this PR with @HanaRebaiQA, we found those issues:

Specs issues:

**First issue**
Spec: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type
>Change product type - Button - Save the new product type, **set the product as offline**, and refresh the page. If the user changes the product type, only the common data between the product type will be saved.

1. Go to BO > Products V2
2. Edit any enabled product
3. Click on the type of the product to change it
4. Select any type and click on "Change product type"
5. See the alert info: Changing the product type will immediately save the product and refresh the page. => OK
6. See error: the product is not disabled as described in the spec


https://user-images.githubusercontent.com/16067358/158423102-a77c8b25-26fc-4253-a487-9f09037368d8.mp4

**Second issue**
Spec: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type

| Changing the Product type form| Impact | warning-alert in the Confirmation modal |
| --- | --- | --- |
| Standard product | No impact, the data is common between the standard product and the others products. | |

1. Go to BO > Products V2
2. Edit a standard product with quantity <> 0 
3. Change the type of product to Product with combinations
4. In the Confirmation Modal => there is a warning 
image

Ping @MatShir, we think we need to update the spec.

**Third issue**
Spec: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type

| Changing the Product type form| Impact | warning-alert in the Confirmation modal |
| --- | --- | --- |
| Standard product | No impact, the data is common between the standard product and the others products. | |
| Product with combination | Deletes the combination and reset the stock to 0. | This will delete all combinations. <br>This will reset the stock of this product. |

1. Go to BO > Catalog > Products V2
2. Edit a product with combinations (quantity <> 0)
3. Change the type of product to another type
4. In the Confirmation Modal => there is only one warning `This will delete all combinations.`

=> the warning `This will reset the stock of this product.` is missing
image

-----------------------------------------------------------------
Other issues

**Fourth issue**
1. Go to BO > International > Taxes page
2. Disable Tax 
image
3. Add a new product V2 > In the pricing tab > Set a Retail price and a tax rule = 20% for example
4. Save
5. See error: in the header: the `tax incl.` is incorrect, it should be the same `tax excl.` 
image

PS: check in the FO 
image

Ping @MatShir what do you think?

**Fifth issue**
1. Go to BO > International > Taxes > Tax rules page
2. Create a new tax rule with the behavior: Combine & One After Another
```
Behavior. Some customers might have an address that matches more than one of your tax rules. In that case, you can choose how this tax rule should behave:
This Tax Only. Will apply only this tax, not any of the other matching taxes.
Combine. Combine taxes. For instance: 100€ + (10% + 5% => 15%) => 115€.
One After Another. Apply taxes one after another. For instance: 100€ + 10% => 110€ + 5% => 115.5€.
```
image
3. Create a product V2 with this tax rule and save
image
4. See an error in the header => 
image

PS: in the FO => OK 
image

**Sixth issue**
1. Go to BO > Shop Parameters > Product Settings > Disable `Enable stock management` 
image
2. Go to BO > Catalog > Products V2
3. Edit a product
4. In the header, the stock is displayed, but in the Stock tab, there is no stock displayed 
image

We think it is a bug, ping @MatShir what do you think?

Thanks!

**Comment by MatShir** [comment]
> Hi @jolelievre,
> 
> I checked this PR with @HanaRebaiQA, we found those issues:
> 
> Specs issues:
> 
> **First issue** Spec: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type
> 
> > Change product type - Button - Save the new product type, **set the product as offline**, and refresh the page. If the user changes the product type, only the common data between the product type will be saved.
> 
> 1. Go to BO > Products V2
> 2. Edit any enabled product
> 3. Click on the type of the product to change it
> 4. Select any type and click on "Change product type"
> 5. See the alert info: Changing the product type will immediately save the product and refresh the page. => OK
> 6. See error: the product is not disabled as described in the spec
> 
>  Products.experimental.PrestaShop.mp4 

This is the expected behavior. I thought the page went offline when you change the product in the legacy. And we agreed with Jo to keep this behavior as it is in the PR. 
I did a PR to update the specs.
→ https://github.com/PrestaShop/prestashop-specs/pull/316

> **Second issue** Spec: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type
> 
> Changing the Product type form	Impact	warning-alert in the Confirmation modal
> Standard product	No impact, the data is common between the standard product and the others products.	
> 1. Go to BO > Products V2
> 2. Edit a standard product with quantity <> 0
> 3. Change the type of product to Product with combinations
> 4. In the Confirmation Modal => there is a warning
>    image
> 
> Ping @MatShir, we think we need to update the spec.

Specs updated :) → → https://github.com/PrestaShop/prestashop-specs/pull/316
Thanks ;)

> **Third issue** Spec: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/catalog/products/add-edit-v2.md#change-of-product-type
> 
> Changing the Product type form	Impact	warning-alert in the Confirmation modal
> Standard product	No impact, the data is common between the standard product and the others products.	
> Product with combination	Deletes the combination and reset the stock to 0.	This will delete all combinations.
> This will reset the stock of this product.
> 1. Go to BO > Catalog > Products V2
> 2. Edit a product with combinations (quantity <> 0)
> 3. Change the type of product to another type
> 4. In the Confirmation Modal => there is only one warning `This will delete all combinations.`
> 
> => the warning `This will reset the stock of this product.` is missing image

@jolelievre will fix it if it is not already fixes and the specs are updated as well :) → https://github.com/PrestaShop/prestashop-specs/pull/316

> Other issues
> 
> **Fourth issue**
> 
> 1. Go to BO > International > Taxes page
> 2. Disable Tax
>    image
> 3. Add a new product V2 > In the pricing tab > Set a Retail price and a tax rule = 20% for example
> 4. Save
> 5. See error: in the header: the `tax incl.` is incorrect, it should be the same `tax excl.`
>    image
> 
> PS: check in the FO image
> 

@jolelievre will fix it if it is not already fixes and the specs are updated as well :) → https://github.com/PrestaShop/prestashop-specs/pull/316> 

> **Fifth issue**
> 
> 1. Go to BO > International > Taxes > Tax rules page
> 2. Create a new tax rule with the behavior: Combine & One After Another
> 
> ```
> Behavior. Some customers might have an address that matches more than one of your tax rules. In that case, you can choose how this tax rule should behave:
> This Tax Only. Will apply only this tax, not any of the other matching taxes.
> Combine. Combine taxes. For instance: 100€ + (10% + 5% => 15%) => 115€.
> One After Another. Apply taxes one after another. For instance: 100€ + 10% => 110€ + 5% => 115.5€.
> ```
> 
> image 3. Create a product V2 with this tax rule and save image 4. See an error in the header => image

This edge case will be handled in this issue https://github.com/PrestaShop/PrestaShop/issues/27054.

> 
> PS: in the FO => OK image
> 
> **Sixth issue**
> 
> 1. Go to BO > Shop Parameters > Product Settings > Disable `Enable stock management`
>    image
> 2. Go to BO > Catalog > Products V2
> 3. Edit a product
> 4. In the header, the stock is displayed, but in the Stock tab, there is no stock displayed
>    image
> 
> We think it is a bug, ping @MatShir what do you think?
> 
> Thanks!

All the quantity field should be hidden. For this PR, the missing part is will be the "Behavior out of the stock".
I'm going to create a dedicated issue for it.

Capture d’écran 2022-03-16 à 16 34 48

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by HanaRebaiQA — DISMISSED** [review]
Hello @jolelievre 

Thanks for the fixed issues.
@khouloudbelguith and me are checked again this PR and here is our feedback :

**First issue :** 
The stock is not updated when editing a product with combinations using a new shop

1. Go to BO > Catalog > Products V2 
2. Create a product `with Combinations`, generate combinations for this product and with `quantity <> 0`
3. Enable multistore and create a new shop
4. Edit the created product with the new shop 
5. Edit quantities for every combinations and Save
6. See error >> The total of stock is NOK 
image

https://user-images.githubusercontent.com/92912932/159305368-9340da9e-df9a-4d8a-b974-e5b9f32d2d1b.mp4


**Second issue :** 
The combinations are not erased (still displayed ) when changing the type of product from `Combinations > Any other type > Changing it again to Combinations` when using a new shop already created


1. Go to BO > Catalog > Products V2 
2. Create a product `with Combinations` and generate combinations for this product 
3. Enable multistore and create a new shop
4. Select the new shop created and edit the last product created with V2
5. Change the type of product to any other type (eg.Standard)
6. Then, change the type again to product `with Combinations`
7. See error >> The generated Combinations of the fist product are not erased (still displayed)

https://user-images.githubusercontent.com/92912932/159316035-95bba019-6670-47a7-9fe7-1d3d17be934d.mp4

**Thrid issue :** 
The tax is updated with every refresh of the page when using theses configuration for the tax rule : 
1. Use different taxes for different Countries 
image
2. Use a One by One Tax 
image

3. Use a tax with Combine 
image

4. Use different taxes for different States as described [here](https://github.com/PrestaShop/prestashop-specs/pull/316/files?diff=split&w=0#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R47)

ping @jolelievre This issue is already reproduced https://github.com/PrestaShop/PrestaShop/pull/27233#issuecomment-1055353950 What do you think ? it should be fixed [here](https://github.com/PrestaShop/PrestaShop/issues/27054)?


https://user-images.githubusercontent.com/92912932/159329718-3a369bba-f618-4337-b62f-6c289e612e6a.mp4


**Fourth issue :** 

The stock is displayed with a green color when the quantity is equal to the low stock level 
But, in specs, the green color must be displayed when the quantity **is strictly superior** to the low stock level
see specifications : 
https://github.com/PrestaShop/prestashop-specs/pull/316/files#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R56-R58
image

1. Go to BO > Catalog > Products V2 
2. Create a standard product equal to low stock level 
3. See error >> The stock is displayed in green color

image

https://user-images.githubusercontent.com/92912932/159326314-658e76c7-89ce-47a7-9ce0-1193e38ca036.mp4

Ping @MatShir what do you think? 

**Fifth issue :** 
The warning message `This will reset the stock of this product` is displayed in case the stock is **disabled** 

1. Go to BO > CONFIGURE > Shop parameters > Product settings
2. Disable the `Enable stock management` parameter
3. Go to BO > Catalog > Products V2
4. Edit a product 
5. Change from any product type to product with combinaitions OR from product with combinations to any other type
6. See error >> The stock warning is displayed but it should'nt
ping @MatShir What do you think ?

https://user-images.githubusercontent.com/92912932/159329471-bd54c477-32f0-4537-95d9-9ea9d9765f84.mp4


image

**Specs issues**

**Sixth issue :** 
https://github.com/PrestaShop/prestashop-specs/pull/316/files#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R96
| Changing the Product type to | Impact | warning-alert in the Confirmation modal |
| --- | --- | --- |
| Product with combination | Deletes the combination and reset the stock to 0. | This will reset the stock of this product. |

The Impact column is NOK, we are changing the type of the product **to** product with combinations, so we don't have yet the combinations to delete them 
ping @MatShir  what do you think?

**Seventh issue :** 
https://github.com/PrestaShop/prestashop-specs/pull/316/files#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R44-R45
>IF the tax rule has not a tax for the shop's country
THEN it displays on the Tax label 0% next to the country ISO code.
image

ping @MatShir What do you think ?

Thanks!

**Comment by jolelievre** [comment]
Hi @HanaRebaiQA and @khouloudbelguith 

thanks for your feedback. Here are my answers for the various issues:

#### First issue and the second issue
The multishop feature development is on pause for now so we can focus on finishing the development of the page in single shop mode. So I think we should create a dedicated issue for those two bugs.

#### Third issue and seventh issue
The problems related to taxes will be handled in this issue indeed https://github.com/PrestaShop/PrestaShop/issues/27054 There has already been an issue added into this one (related to combined taxes) But I think you can add this issue as it seems to be slightly different. This is also the issue where we will add the country code next to the tax.

#### Fourth and the fifth issue
To be fixed in this PR, I'll look into them

#### Sixth issue
To see with @MatShir but it seems like a mistake indeed. Edit: Spec are updated, it was a mistake indeed.

**Review by matks — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by HanaRebaiQA — DISMISSED** [review]
Hello @jolelievre 

I checked again this PR : 
-The issues mentionned above are fixed : OK


I just found new issues related to **specs** : 

**First issue :** 
In this section, this condition is missing 
`If the quantity <= lowStockLevel, the color background is Orange `
image

@MatShir  Could you please check and update the spec in this part https://github.com/PrestaShop/prestashop-specs/pull/316/files#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R56-R64 ?

**Second issue :** 
When the `Enable stock management` parameter is disabled, there is Only one warning when change the product from Combinations to other product type
`This will delete all combinations`
image
@MatShir Could you please update the spec here https://github.com/PrestaShop/prestashop-specs/pull/316/files#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R89-R97 ?

So, this PR will be QA :heavy_check_mark: when the specs are fine.

Thank you!

**Comment by MatShir** [comment]
[Updated](https://github.com/PrestaShop/prestashop-specs/pull/316/commits/562b47b97653475041c59da9d11b2df965211606). Let's merge it ! :)

**Review by matks — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello,

Thank you @MatShir for the fix
@jolelievre It's OK for me after a new check on the PR
So, QA :heavy_check_mark: 

GO for the merge of the PR 
Thanks!

**Comment by Progi1984** [comment]
Thanks @jolelievre & @HanaRebaiQA
