### PR TITLE
No email check in  BO > Advanced Parameters > Logs page

### LINKED ISSUE #24616: BO - Logs - There is no email address check
#### Describe the bug

In the BO > Advanced Parameters > Logs page, in the logs by email section, there is no check of a valid address mail or not

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Logs page
2. In the logs by email section > set the field `Send emails to` to `test`
3. Save
4. See error: no validation (the type of the field should be email and not text)

This field is an improvement in 178x

**Screenshots**

#### Additional informationBO_log
* PrestaShop version: 178x
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In the BO > Advanced Parameters > Logs page, in the logs by email section, there is no check of a valid address mail or not. With this PR we check if the emails given are ok 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24616
| How to test?      | Use incorrect email and see the error, you can add coma to test many email
| Possible impacts? | This may impact the people who decorate this adapter

**:notebook: BC Breaks**
* The class `PrestaShop\PrestaShop\Adapter\Configuration\LogsConfiguration` has two new parameters : 
  * `Symfony\Component\Translation\TranslatorInterface` $translator
  * `PrestaShop\PrestaShop\Adapter\Validate` $validate

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24620)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php [hunk 1]
```diff
@@ -122,7 +122,7 @@ public function saveSettingsAction(Request $request)
                 return $this->redirectToRoute('admin_logs_index');
             }
 
-            $this->flashErrors($saveErrors);
+            $this->addFlash('error', $this->trans('Invalid email address.', 'Admin.Notifications.Error') . ' ( ' . implode(',', $saveErrors) . ' ) ');
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php:125]: shouldn't we check `$saveErrors` is not empty before calling the `addFlash` method?

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php:125]: otherwise lgtm 👍

**Review by matthieu-rolland — DISMISSED** [review]
lgtm 👍

File: src/Adapter/Configuration/LogsConfiguration.php [hunk 2]
```diff
@@ -29,6 +29,7 @@
 use PrestaShop\PrestaShop\Core\Configuration\DataConfigurationInterface;
 use PrestaShop\PrestaShop\Core\ConfigurationInterface;
 use Symfony\Component\OptionsResolver\OptionsResolver;
+use Validate;
```
Comment (PierreRambaud) [inline src/Adapter/Configuration/LogsConfiguration.php]: ping @matks shouldn't we inject the Validate adapter and add the missing `isEmail` method?

File: src/Adapter/Configuration/LogsConfiguration.php [hunk 3]
```diff
@@ -62,6 +63,17 @@ public function getConfiguration()
     public function updateConfiguration(array $configuration)
     {
         if ($this->validateConfiguration($configuration)) {
+            $checkEmails = explode(',', $configuration['logs_email_receivers']);
+            $errors = [];
+            foreach ($checkEmails as $email) {
+                if (!Validate::isEmail($email)) {
+                    $errors[] = $email;
```
Comment (PierreRambaud) [inline src/Adapter/Configuration/LogsConfiguration.php]: The error message has to be built here and not in the controllers.
Otherwise if I extend the symfony service and add a new check, I will have a "Invalid email address' error which will be not related to my change.

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php (hunk 1 above)
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php]:
```suggestion
            $this->flashErrors($saveErrors);
```

File: src/Adapter/Configuration/LogsConfiguration.php (hunk 2 above)
Comment (matks) [reply src/Adapter/Configuration/LogsConfiguration.php]: Yes, like @PululuK did in https://github.com/PrestaShop/PrestaShop/pull/24622/

File: src/Adapter/Configuration/LogsConfiguration.php [hunk 4]
```diff
@@ -62,6 +70,17 @@ public function getConfiguration()
     public function updateConfiguration(array $configuration)
     {
         if ($this->validateConfiguration($configuration)) {
+            $checkEmails = explode(',', $configuration['logs_email_receivers']);
+            $errors = [];
+            foreach ($checkEmails as $email) {
+                if (!Validate::isEmail($email)) {
```
Comment (Progi1984) [inline src/Adapter/Configuration/LogsConfiguration.php]: @okom3pom Could you inject in construct the Validate Adapter ? Thanks

Comment (ghost) [reply src/Adapter/Configuration/LogsConfiguration.php]: @Progi1984 isEmail is missing in the Validate Adapter my PR target 1.7.8 and normaly the code is freeze 

The PR of @PululuK ( https://github.com/PrestaShop/PrestaShop/pull/24622 ) add new fonctionality and he target the dev branch

Comment (ghost) [reply src/Adapter/Configuration/LogsConfiguration.php]: I can close mine and you validate @PululuK PR  in 1.7.8? Because it's a regression ?

Comment (PululuK) [reply src/Adapter/Configuration/LogsConfiguration.php]: Hi @okom3pom, you can copy past this part in my PR ;)

Comment (Progi1984) [reply src/Adapter/Configuration/LogsConfiguration.php]: Good idea @PululuK (and you will rebase your PR after the merge of this one). #modeCoop

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Validate.php [hunk 5]
```diff
@@ -76,6 +76,18 @@ public function isCleanHtml($html, $allowIframe = false)
...
+     * Check for a given email validity.
+     *
+     * @param string $email
+     *
+     * @return bool
+     */
+    public function isEmail($email): bool
+    {
+        return ValidateLegacy::isEmail($email);
+    }
```
Comment (PululuK) [inline src/Adapter/Validate.php]:
```suggestion
    public function isEmail(string $email): bool
    {
        return ValidateLegacy::isEmail($email);
    }
```

**Review by PululuK — DISMISSED** [review]
Thank you !
if you can take part of my tests [here](https://github.com/PrestaShop/PrestaShop/pull/24622/files)  for the new `isEmail` method in adapter, it will be really great !

File: tests/Unit/Adapter/ValidateTest.php [hunk 6]
```diff
@@ -33,6 +33,22 @@
...
 class ValidateTest extends TestCase
 {
+    /**
+     * @var Validate
+     */
+    private $validate;
+
+    /**
+     * @param string $name
+     * @param string $dataName
```
Comment (Progi1984) [inline tests/Unit/Adapter/ValidateTest.php:44]:
```suggestion
     * @param array $data
     * @param string $dataName
```

**Review by Progi1984 — COMMENTED** [review]
A small PHPDoc

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Configuration/LogsConfiguration.php [hunk 7]
```diff
@@ -62,6 +76,17 @@ public function getConfiguration()
     public function updateConfiguration(array $configuration)
     {
         if ($this->validateConfiguration($configuration)) {
+            $checkEmails = explode(',', $configuration['logs_email_receivers']);
+            $errors = [];
+            foreach ($checkEmails as $email) {
+                if (!$this->validate->isEmail($email)) {
+                    $errors[] = $this->translator->trans('Invalid email address.', [], 'Admin.Notifications.Error') . ' ( ' . $email . ' ) ';
```
Comment (PululuK) [inline src/Adapter/Configuration/LogsConfiguration.php]:
```suggestion
                    $errors[] = $this->translator->trans('Invalid email address %email%.' , ['%email%' => $email], 'Admin.Notifications.Error');
```

**Review by PululuK — COMMENTED** [review]
Small feedback, and it is ok for me !

File: src/Adapter/Configuration/LogsConfiguration.php (hunk 7 above)
Comment (Julievrz) [reply src/Adapter/Configuration/LogsConfiguration.php]: @PululuK Why not using the same wording as in https://github.com/PrestaShop/PrestaShop/pull/24622/files ?

line 79, file 92

File: src/Adapter/Configuration/LogsConfiguration.php [hunk 8]
```diff
@@ -40,9 +42,21 @@ class LogsConfiguration implements DataConfigurationInterface
...
+     * @var TranslatorInterface
+     */
+    private $translator;
+
+    /**
+     * @var Validate
+     */
+    private $validate;
+
+    public function __construct(ConfigurationInterface $configuration, TranslatorInterface $translator, Validate $validate)
```
Comment (PierreRambaud) [inline src/Adapter/Configuration/LogsConfiguration.php:55]: Bc breaks

Comment (Progi1984) [reply src/Adapter/Configuration/LogsConfiguration.php:55]: Documented

File: src/Adapter/Configuration/LogsConfiguration.php [hunk 9]
```diff
@@ -62,6 +76,17 @@ public function getConfiguration()
     public function updateConfiguration(array $configuration)
     {
         if ($this->validateConfiguration($configuration)) {
+            $checkEmails = explode(',', $configuration['logs_email_receivers']);
+            $errors = [];
+            foreach ($checkEmails as $email) {
+                if (!$this->validate->isEmail($email)) {
+                    $errors[] = $this->translator->trans('Invalid email address %email%.', ['%email%' => $email], 'Admin.Notifications.Error');
```
Comment (Julievrz) [inline src/Adapter/Configuration/LogsConfiguration.php]: Hi, 

Is it possible that there is more than one invalid email? If yes, we could use transChoice(

Invalid email: %invalid_emails%.|Invalid emails: %invalid_emails%.

Just like we did it here: https://github.com/PrestaShop/PrestaShop/pull/24622

We would also avoid creating 2 different strings to say the same thing.

Comment (ghost) [reply src/Adapter/Configuration/LogsConfiguration.php]: @Julievrz I made the change

**Review by Julievrz — COMMENTED** [review]
The wording is ok. The {1} is optional with "transChoice" if I am not mistaken. @jolelievre can you confirm that il will not duplicate the string, please? (https://github.com/PrestaShop/PrestaShop/pull/24622/files)

**Comment by ghost** [comment]
@Julievrz && @jolelievre  see : https://github.com/PrestaShop/PrestaShop/pull/24622#discussion_r648035502

**Comment by ghost** [comment]
@Progi1984 the best way is i close this PR if @PululuK rebase in 1.7.8 

It's not a problem , i am learning a lot with this PR it's the most important

**Comment by ghost** [comment]
Hey @Julievrz 

@PululuK add the {1} for the transchoice  

https://github.com/PrestaShop/PrestaShop/pull/24622/commits/1cda92a35307c4a6f3e8a60158715c0c8d455e1e 

I think it's the same wording now.

**Comment by Julievrz** [comment]
> Hey @Julievrz
> 
> @PululuK add the {1} for the transchoice
> 
> [1cda92a](https://github.com/PrestaShop/PrestaShop/commit/1cda92a35307c4a6f3e8a60158715c0c8d455e1e)
> 
> I think it's the same wording now.

Hi :) @PululuK added variables but it's not written exactly like in your PR. 

I think the string should be: 'Invalid email: %invalid_emails%.|Invalid emails: %invalid_emails%.' but @PululuK's suggestion is probably right too. I would need the help of a developer here. :-)

**Comment by Julievrz** [comment]
Hi @okom3pom

I talked with @jolelievre and it seems that TransChoice is deprecated in Symphony 4.4, and will no longer work the same way with Symphony 5. So, unfortunately, it's risky to use TransChoice because it might not work in future versions. 

I suggest creating two strings: one singular, one plural, and display the right one depending on the number of emails, if that's possible.

Thank you for your patience as we were discussing the issue.

**Review by Julievrz — DISMISSED** [review]
Wording ✔️ 
Thank you

**Review by PululuK — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by Julievrz — APPROVED** [review]
Wording ✅

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @okom3pom ,

I tested with multiple email addresses, some issues remain :

`test` - Invalid email:test -> **OK**

`test@test` - Successful update. -> **NOK** should be `Invalid email: test@test`

`test@test, test@test.com` - Invalid email: test@test.com -> **error message NOK** should be `Invalid email: test@test`

`test@test.com, test@test` - Invalid email: test@test -> **error message OK**

Could you take a look please ?

**Comment by ghost** [comment]
Hello @florine2623 

test@test is a valid email.
space+email is not a valid email.

**Comment by florine2623** [comment]
Thanks for your answer @kpodemski, noted.

What about the type of the field ?
Should it be `email` as stated by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/issues/24616 ?
Now it is still` type="text"`.

**Comment by ghost** [comment]
I think it's not an email type because :

test@test.com,test@test.fr is not an email type.

See the error when i use email type 

Regards Thomas

Capture d’écran de 2021-07-16 00-22-38

**Comment by florine2623** [comment]
Thanks for the answer @okom3pom !

LGTM

**Comment by Progi1984** [comment]
## WAIT FOR 1780 RELEASE

**Comment by matks** [comment]
@Progi1984 QA has defined the scope of changes they want to embed inside 1.7.8.0 RC1 build 2. This PR is inside the list.

Thank you @okom3pom
