### PR TITLE
Make root category of a shop non editable

### LINKED ISSUE #20463: BO - Categories page - An exception is displayed when updating the Root category
#### Describe the bug

In the BO => Catalog => Categories page, an exception is displayed when updating the **Root** category
image

#### Expected behavior

Root category should be well updated

#### Steps to Reproduce

After enabling **multistore**, you can edit the Root category following these steps:
1. Go to BO => Shop Parameters => General => Enable multistore
2. Create a new shop
3.  BO => Catalog => Categories page
4. Add a new root category
5. Edit the Root category
image

Or simply you can follow this link: `/admin-dev/index.php/sell/catalog/categories/1`
6. Save
7. See error

#### Additional information

* PrestaShop version: 1.7.6.0, 1.7.6.7, 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Root category is the virtual category which is parent of the Home category of a shop. In order to avoid errors due to edition of this category, we avoid his edition
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20463
| How to test?  | You cannot edit the root category of a shop. A flash message must be displayed and you will be redirected to categories list. <br>Inaccessible URLs : <br><ul><li>/admin-dev/index.php/sell/catalog/categories/1</li><li>/admin-dev/index.php/sell/catalog/categories/1/edit</li><li>/admin-dev/index.php/sell/catalog/categories/1/edit-root</li></ul><br><br>In a multishop context, after creating the Home category of the 2nd shop, you won't see any link in front of Root category. See screenshot<br>root_category after

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22438)

### CODE REVIEW

File: src/Adapter/Category/CommandHandler/EditCategoryHandler.php [hunk 1]
```diff
@@ -53,6 +55,11 @@ public function handle(EditCategoryCommand $command)
             throw new CategoryNotFoundException($command->getCategoryId(), sprintf('Category with id "%s" cannot be found.', $command->getCategoryId()->getValue()));
         }
 
+        // Root category means here REAL ROOT category, not the HOME of the shop
```
Comment (kpodemski) [inline src/Adapter/Category/CommandHandler/EditCategoryHandler.php]:
```suggestion
```

IMO useless comment as you did a good job with a method description :) if you think it needs to be even more clear to developers in future I'd suggest putting more details there

File: src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php [hunk 2]
```diff
@@ -53,6 +55,11 @@ public function handle(EditRootCategoryCommand $command)
             throw new CategoryNotFoundException($command->getCategoryId(), sprintf('Category with id "%s" cannot be found.', $command->getCategoryId()->getValue()));
         }
 
+        // Root category means here REAL ROOT category, not the HOME of the shop
```
Comment (kpodemski) [inline src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php]:
```suggestion
```

File: src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php [hunk 3]
```diff
@@ -71,6 +73,11 @@ public function handle(GetCategoryForEditing $query)
             throw new CategoryNotFoundException($query->getCategoryId(), sprintf('Category with id "%s" was not found', $query->getCategoryId()->getValue()));
         }
 
+        // Root category means here REAL ROOT category, not the HOME of the shop
```
Comment (kpodemski) [inline src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php]:
```suggestion
```

**Review by kpodemski — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig [hunk 4]
```diff
@@ -28,25 +28,30 @@
...
           <li class="breadcrumb-item">
-            {% if category.id_parent == 0 and isSingleShopContext %}
+            {% if isRootCategory and isSingleShopContext %}
               {% if category.id_category == currentCategoryView.id %}
                 <span>{{ category.name }}</span>
-                <a href="{{ path('admin_categories_edit', {'categoryId': category.id_category}) }}">
-                  <i style="font-size: 16px;" class="material-icons">edit</i>
-                  {{ 'Edit'|trans({}, 'Admin.Actions') }}
-                </a>
+                  {%  if not isRootCategory %}
```
Comment (Arman-Hosseini) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig]:
```suggestion
                  {% if not isRootCategory %}
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig [hunk 5]
```diff
@@ -28,25 +28,30 @@
...
                   {{ category.name }}
                 </a>
               {% endif %}
             {% elseif category.id_category == currentCategoryView.id %}
               <span>{{ category.name }}</span>
-              <a href="{{ path('admin_categories_edit', {'categoryId': category.id_category}) }}">
-                <i style="font-size: 16px;" class="material-icons">edit</i>
-                {{ 'Edit'|trans({}, 'Admin.Actions') }}
-              </a>
+                {%  if not isRootCategory %}
```
Comment (Arman-Hosseini) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig]:
```suggestion
                {% if not isRootCategory %}
```

File: classes/Category.php [hunk 6]
```diff
@@ -2441,4 +2441,15 @@ public function existsInShop($idShop)
...
 		AND `id_shop` = ' . (int) $idShop, false);
     }
+
+    /**
+     * Indicates whether a category is ROOT for the shop.
+     * The root category is the one with no parent. It's a virtual category.
+     *
+     * @return bool
+     */
+    public function isRootCategory()
```
Comment (Progi1984) [inline classes/Category.php]:
```suggestion
    public function isRootCategory(): bool
```

File: src/Core/Domain/Category/Exception/CannotEditRootCategoryException.php [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace PrestaShop\PrestaShop\Core\Domain\Category\Exception;
```
Comment (Progi1984) [inline src/Core/Domain/Category/Exception/CannotEditRootCategoryException.php]:
```suggestion
 */

declare(strict_types=1);

namespace PrestaShop\PrestaShop\Core\Domain\Category\Exception;
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php [hunk 8]
```diff
@@ -339,6 +340,10 @@ public function editRootAction($categoryId, Request $request)
             if (!$editableCategory->isRootCategory()) {
                 return $this->redirectToRoute('admin_categories_edit', ['categoryId' => $categoryId]);
             }
+        } catch (CannotEditRootCategoryException $e) {
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php]:
```suggestion
        } catch (CannotEditRootCategoryException|CategoryNotFoundException $e) {
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks And TravisCI is broken

File: classes/Category.php [hunk 9]
```diff
@@ -2441,4 +2441,15 @@ public function existsInShop($idShop)
...
+    {
+        return 0 === (int) $this->id_parent || null === $this->id_parent;
```
Comment (PierreRambaud) [inline classes/Category.php]:
```suggestion
        return 0 === (int) $this->id_parent;
```

Comment (Progi1984) [inline classes/Category.php]:
```suggestion
        return 0 === (int) $this->id_parent;
```
null cast in int equals 0

File: src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php [hunk 10]
```diff
@@ -44,6 +45,7 @@ final class EditRootCategoryHandler extends AbstractObjectModelHandler implement
      *
      * @throws CannotEditCategoryException
      * @throws CategoryNotFoundException
+     * @throws CannotEditRootCategoryException
      */
     public function handle(EditRootCategoryCommand $command)
```
Comment (jolelievre) [inline src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php:50]: So the whole handler is now forbidden to be used Maybe then we could throw an exception in the Command constructor itself since it's not supposed to be used any more?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig [hunk 11]
```diff
@@ -28,25 +28,30 @@
     <nav>
       <ol class="breadcrumb">
         {% for category in currentCategoryView.breadcrumb_tree %}
+          {% set isRootCategory = (category.id_parent == 0) %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig:31]: Just a suggestion but is it worth displaying the root category now that it can't be edited anyway Maybe using Home as the first element of the breadcrumb would be more intuitive for the merchant?
@MatShir what do you think?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig [hunk 12]
```diff
@@ -28,25 +28,30 @@
...
           <li class="breadcrumb-item">
-            {% if category.id_parent == 0 and isSingleShopContext %}
+            {% if isRootCategory and isSingleShopContext %}
               {% if category.id_category == currentCategoryView.id %}
                 <span>{{ category.name }}</span>
-                <a href="{{ path('admin_categories_edit', {'categoryId': category.id_category}) }}">
-                  <i style="font-size: 16px;" class="material-icons">edit</i>
-                  {{ 'Edit'|trans({}, 'Admin.Actions') }}
-                </a>
+                  {% if not isRootCategory %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig]: I'm not sure but it seems like this will never happen since we're already in a block where `isRootCategory and isSingleShopContext` The category is necessarily a root category so this link block can be removed I guess.

**Review by Progi1984 — COMMENTED** [review]
Good job. Please add integration tests for this case.

File: src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php (hunk 10 above)
Comment (sowbiba) [reply src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php:50]: That will make me get the Catgory Object in the command. It's not ... usual

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig (hunk 11 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/breadcrumb.html.twig:31]: When we are in a multistore context, we have the page after Shop Home Category creation where we have

Root Category as breadcumb
and the 2 Home categories in the list

File: src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php (hunk 10 above)
Comment (matks) [reply src/Adapter/Category/CommandHandler/EditRootCategoryHandler.php:50]: 👍  indeed I dont see how we can check "is category a root category" without fetching the data from database, and this cannot be done inside a Command 😢

**Comment by matks** [comment]
> Good job. Please add integration tests for this case.

We can test that Root Category is not editable by writing a Behat test attempting to edit the root category and verifying an exception is thrown 👍  .

**Review by matks — COMMENTED** [review]
Code seems good to me, as suggested by @Progi1984 a behat test would be very nice !

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: classes/Category.php [hunk 13]
```diff
@@ -2441,4 +2441,15 @@ public function existsInShop($idShop)
...
+
+    /**
+     * Indicates whether a category is ROOT for the shop.
+     * The root category is the one with no parent. It's a virtual category.
+     *
+     * @return bool
+     */
+    public function isRootCategory(): bool
+    {
+        return 0 === (int) $this->id_parent;
```
Comment (PierreRambaud) [inline classes/Category.php:2453]: `isRootCategoryForAShop` already exists.

Comment (sowbiba) [reply classes/Category.php:2453]: isRootCategoryForAShop returns the home category, not the root

Comment (PierreRambaud) [reply classes/Category.php:2453]: You probably have to change the docstring of `isRootCategoryForAShop` method, it's confusing, description are similar :sweat_smile: 

There are also some call in `BulkDeleteCategoriesHandler` and `DeleteCategoryHandler` that are related to Root category, I'm not sure they thought about it. (Not in this pull request of course)

Comment (sowbiba) [reply classes/Category.php:2453]: Yes there are a lot of confusions between Home category of a Shop and the Root category which is a "virtual category"

File: tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php [hunk 14]
```diff
@@ -0,0 +1,56 @@
...
+    /**
+     * @var int
+     */
+    private $rootCategory;
+    /**
+     * @var \Symfony\Component\DependencyInjection\ContainerInterface|null
+     */
+    private $container;
+
+    protected function setUp()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php]:
```suggestion
    protected function setUp(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php [hunk 15]
```diff
@@ -0,0 +1,56 @@
...
+    {
+        self::bootKernel();
+        $this->container = self::$kernel->getContainer();
+
+        $this->commandBus = $this->container->get('prestashop.core.command_bus');
+        $this->rootCategory = (int) $this->container->get('prestashop.adapter.legacy.configuration')->get('PS_ROOT_CATEGORY');
+    }
+
+    public function testEditRootCategoryDoesntThrowExceptionIfExists()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php]:
```suggestion
    public function testEditRootCategoryDoesntThrowExceptionIfExists(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php [hunk 16]
```diff
@@ -0,0 +1,56 @@
...
+    }
+
+    public function testEditRootCategoryThrowsAnExceptionIfCategoryDoesntExist()
+    {
+        $command = new EditRootCategoryCommand(10000);
+        $this->expectException(CategoryNotFoundException::class);
+        $this->commandBus->handle($command);
+    }
+
+    public function testEditRootCategoryThrowsAnException()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/EditRootCategoryHandlerTest.php]:
```suggestion
    public function testEditRootCategoryThrowsAnException(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 17]
```diff
@@ -0,0 +1,58 @@
...
+    }
+
+    public function testGetRootCategoryForEditingThrowsAnExceptionIfCategoryDoesntExist()
+    {
+        $command = new GetCategoryForEditing(10000);
+        $this->expectException(CategoryNotFoundException::class);
+        $this->commandBus->handle($command);
+    }
+
+    public function testGetRootCategoryForEditingThrowsAnException()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php]:
```suggestion
    public function testGetRootCategoryForEditingThrowsAnException(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 18]
```diff
@@ -0,0 +1,58 @@
...
+    {
+        $categories = $this->container->get('prestashop.adapter.form.choice_provider.category_tree_choice_provider')->getChoices();
+        $existingCategoryId = $categories[0]['id_category'];
+        $command = new GetCategoryForEditing((int) $existingCategoryId);
+
+        $editableCategory = $this->commandBus->handle($command);
+        $this->assertInstanceOf(EditableCategory::class, $editableCategory);
+    }
+
+    public function testGetRootCategoryForEditingThrowsAnExceptionIfCategoryDoesntExist()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php]:
```suggestion
    public function testGetRootCategoryForEditingThrowsAnExceptionIfCategoryDoesntExist(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 19]
```diff
@@ -0,0 +1,58 @@
...
+    protected function setUp()
+    {
+        self::bootKernel();
+        $this->container = self::$kernel->getContainer();
+
+        $this->commandBus = $this->container->get('prestashop.core.command_bus');
+        $this->rootCategory = (int) $this->container->get('prestashop.adapter.legacy.configuration')->get('PS_ROOT_CATEGORY');
+    }
+
+    public function testGetCategoryForEditingReturnsAnEditableCategoryIfExists()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php]:
```suggestion
    public function testGetCategoryForEditingReturnsAnEditableCategoryIfExists(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+    /**
+     * @var int
+     */
+    private $rootCategory;
+    /**
+     * @var \Symfony\Component\DependencyInjection\ContainerInterface|null
+     */
+    private $container;
+
+    protected function setUp()
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php]:
```suggestion
    protected function setUp(): void
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 21]
```diff
@@ -0,0 +1,58 @@
+<?php
+
+namespace Tests\Integration\Adapter\Category\QueryHandler;
+
+use PrestaShop\PrestaShop\Core\Domain\Category\Exception\CannotEditRootCategoryException;
+use PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryNotFoundException;
+use PrestaShop\PrestaShop\Core\Domain\Category\Query\GetCategoryForEditing;
+use PrestaShop\PrestaShop\Core\Domain\Category\QueryResult\EditableCategory;
+use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php:35]:
```suggestion
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\DependencyInjection\ContainerInterface;
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 22]
```diff
@@ -0,0 +1,58 @@
...
+    /**
+     * @var object|\PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter|null
+     */
+    private $commandBus;
+    /**
+     * @var int
+     */
+    private $rootCategory;
+    /**
+     * @var \Symfony\Component\DependencyInjection\ContainerInterface|null
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php]:
```suggestion
     * @var ContainerInterface|null
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 23]
```diff
@@ -0,0 +1,58 @@
+<?php
+
+namespace Tests\Integration\Adapter\Category\QueryHandler;
+
+use PrestaShop\PrestaShop\Core\Domain\Category\Exception\CannotEditRootCategoryException;
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php:31]:
```suggestion
use PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter;
use PrestaShop\PrestaShop\Core\Domain\Category\Exception\CannotEditRootCategoryException;
```

File: tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php [hunk 24]
```diff
@@ -0,0 +1,58 @@
...
+use PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryNotFoundException;
+use PrestaShop\PrestaShop\Core\Domain\Category\Query\GetCategoryForEditing;
+use PrestaShop\PrestaShop\Core\Domain\Category\QueryResult\EditableCategory;
+use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
+
+class GetCategoryForEditingHandlerTest extends KernelTestCase
+{
+    /**
+     * @var object|\PrestaShop\PrestaShop\Core\CommandBus\TacticianCommandBusAdapter|null
```
Comment (Progi1984) [inline tests/Integration/Adapter/Category/QueryHandler/GetCategoryForEditingHandlerTest.php]:
```suggestion
     * @var TacticianCommandBusAdapter|null
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

**Comment by SD1982** [comment]
LGTM !!
The root category is no longer editable now.
If it's ok for wording it's ok for QA
WDYT  @Julievrz ?
Thanks @sowbiba !!

**Review by Progi1984 — APPROVED** [review]

File: classes/Category.php (hunk 13 above)
Comment (PierreRambaud) [reply classes/Category.php:2453]: Could you change the description of the `isRootCategoryForAShop` by setting `Home category` (without changing the method signature of course)?

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @sowbiba

**Comment by coluccini** [comment]
Is there a chance that this PR has broken some upgrades?
I've upgraded from a previous PS version (1.7.6) to the latest and now I can't create new categories. The root category is still showing on the "parent category" field (I think I should now only see the Home category, shouldn't I?), but always is disabled so I can't choose it. If I try to save it either way, I get the following error:

`[PrestaShop\PrestaShop\Core\Domain\Category\Exception\CategoryConstraintException código 6]: Invalid Category parent id 0 supplied`

I've tried to emulated this categories structure from a clean installation:

Screenshot 2021-04-25 at 19 27 23

But the I can't get the Home category to be shown as "root" on the backoffice. I'm still seeing the category marked with `is_root_category = 1` as a subcategory of home:

Screenshot 2021-04-25 at 19 38 15

Screenshot 2021-04-25 at 19 38 38

I've also changed the `PS_HOME_CATEGORY` config to the corresponding ID.
Is there something more I should change?

**Comment by matks** [comment]
@coluccini this PR will be shipped with 1.7.8.0 which has not be released yet so it cannot impact your shop

**Comment by coluccini** [comment]
🤦‍♂️ Sorry, didn't realise about that! 
Do you have ideas why I'm seeing that behaviour after upgrading?
I can't managed to create categories nor products since the upgrade and everything points to an issue on how the root/home categories are structured. According to my previous screenshot: shouldn't I be seeing the category 152 as the root instead the category 1?
