### PR TITLE
Filters : Set Placeholder for Yes/NO & Fix bug when filters are emptied

### LINKED ISSUE #18480: BO - drop-down list filter doesn't work totally as expected
#### Describe the bug

This behavior was observed on all drop-downs of migrated page filters

In the list filters when using the drop-down lists the selection of the empty item brings back to the last selection used

#### Expected behavior

The empty item in the drop-down list should bring up all the items in the list

#### Steps to Reproduce

1. Go to BO on a migrated page that contain a list with drop-down filter
2. On the drop-down list select one one the item and click on search
3. Only the required items are displayed on the list
4. Now on the drop-down select another item and click on search
5. The list is refreshed an the new required items are displayed
6. Now select the blank item in the drop-down list and click on search
7. The list should display all the items but not ( the list display the items from step 5 )

**Screenshots**

**The error in 1.7.7.x (also reproductible in 1.7.6.x) :** 
https://drive.google.com/file/d/1Fds2N2JuKehaQmoul6ep6cPRHffn-d_P/view

#### Additional information

* PrestaShop version: 1.7.7.x and 1.7.6.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Filters : Set Placeholder for Yes/NO & Fix bug when filters are emptied 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Fixes #18480
| How to test?  | 1. Go to BO on a migrated page that contain a list with drop-down filter<br>2. On the drop-down list select one one the item and click on search<br>3. Only the required items are displayed on the list<br>4. Now on the drop-down select another item and click on search<br>5. The list is refreshed an the new required items are displayed<br>6. Now select the "All" item in the drop-down list and click on search<br>7. **BEFORE** : The list display the items from step 5<br>7. **AFTER** : The list display all the items

**:notebook: BC Break**
* The class `PrestaShopBundle\Service\Grid\ResponseBuilder` adds 3 parameters : 
  * `\PrestaShopBundle\Entity\Repository\AdminFilterRepository $adminFilterRepository`
  * `int|null $employeeId`
  * `int $shopId`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21420)

### CODE REVIEW

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 1]
```diff
@@ -99,4 +120,57 @@ public function buildSearchResponse(
...
         return new RedirectResponse($redirectUrl, 302);
     }
+
+    /**
+     * @param array $filtersFormData
+     * @param string $filterId
+     *
+     * @return array
+     */
+    private function checkFiltersFormData(array $filtersFormData, string $filterId): array
```
Comment (jolelievre) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: This method is a bit weird, it has multiple responsibilities:
- check if filters are empty
- clean filter in DB if the filters are empty
- return empty array when filters is considered empty

Either it's not correctly named, or it does too many things, or both 😛

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 2]
```diff
@@ -29,29 +29,47 @@
...
      * @param GridFilterFormFactoryInterface $filterFormFactory
      * @param Router $router
+     * @param AdminFilterRepository $adminFilterRepository
+     * @param int $shopId
      */
     public function __construct(
         GridFilterFormFactoryInterface $filterFormFactory,
-        Router $router
+        Router $router,
+        AdminFilterRepository $adminFilterRepository,
```
Comment (matks) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:65]: Isn't it a BC break to modify constructor ? Can we avoid this will optional args :) ?

Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:65]: Right. I document it.

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: Renamed

Comment (jolelievre) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: I'm not sure you need to transform the input array, since the generator will ignore `null` fields any way
Maybe this function should only check if the array is empty, reset the filter if necessary and return nothing (or void)

And rename this `resetPersistedFilters`, then even the check doesn't need to be in this method, you would just need to do:

```php
if ($filtersForm->isSubmitted()) {
    if ($this->checkIsFormDataEmpty($filtersForm->getData())) {
        $this->resetPersistedFilter($filterId);
    }

    $redirectParams = [
        $filterId => [
            'filters' => $filtersForm->getData(),
        ]
    ];
}
```

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 3]
```diff
@@ -99,4 +120,57 @@ public function buildSearchResponse(
...
+    }
+
+    /**
+     * Return true if array is empty (null values or empty array)
+     *
+     * @param array $formData
+     *
+     * @return bool
+     */
+    private function checkIsFormDataEmpty(array $formData): bool
```
Comment (matks) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:154]: I dont know if it's easy to do because of the mock setup might be complex but such a complex logic with multiple `if` would benefit from some phpunit tests 😉

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: Fixed

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 4]
```diff
@@ -99,4 +121,47 @@ public function buildSearchResponse(
...
+    {
+        if (empty($filterId)) {
+            return;
+        }
+        $adminFilter = $this->adminFilterRepository->findByEmployeeAndFilterId(
+            $this->employeeId,
+            $this->shopId,
+            $filterId
+        );
+        $this->adminFilterRepository->unsetFilters($adminFilter);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:144]: You need to check that `$adminFilter` is not null

Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:144]: Fixed

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 5]
```diff
@@ -99,4 +121,50 @@ public function buildSearchResponse(
...
+    {
+        foreach ($formData as $data) {
+            if (is_null($data)) {
+                continue;
+            }
+            if (is_array($data)) {
+                if ($this->checkIsFormDataEmpty($data)) {
+                    continue;
+                }
+            }
```
Comment (PululuK) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: hum ... why double `if` statement? Use ```&&``` please !

Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: Fixed

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 6]
```diff
@@ -99,4 +121,48 @@ public function buildSearchResponse(
...
+     * Return true if array is empty (null values or empty array)
+     *
+     * @param array $formData
+     *
+     * @return bool
+     */
+    private function checkIsFormDataEmpty(array $formData): bool
+    {
+        foreach ($formData as $data) {
+            if (is_null($data)) {
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]:
```suggestion
            if ($data === null) {
```

Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php]: Fixed

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

IN the BO > International > Localization > Languages, the Placeholder for Yes/NO is not set and the bug when filters is empty not fixed.

image

In the BO > International > Taxes page > the bug when filter = All is not fixed.
I attached a screen record
https://drive.google.com/file/d/1KrAMLcfuhFXlSqGzWGOYQwGxWYn77PcM/view?usp=sharing

In the BO > Advanced Parameters > Employees page the bug when filter = All is not fixed.
I attached a screen record
https://drive.google.com/file/d/1IvrDP0RuIoATgLm_GVTYsfPGU-G_13DL/view?usp=sharing

In the BO > Advanced Parameters > Webservice page, the Placeholder for Yes/NO is not set, and the bug when filters is empty not fixed.
image


Thanks!

**Comment by Progi1984** [comment]
BO > International > Localization > Languages : :ok: 
BO > International > Taxes : :construction: 
BO > Advanced Parameters > Employees : :construction: 
BO > Advanced Parameters > Webservice : :construction:

**Comment by matks** [comment]
@Progi1984 is this PR complete and ready for review 😉  ?

**Comment by Progi1984** [comment]
BO > International > Localization > Languages : :ok: 
BO > International > Taxes : :ok: 
BO > Advanced Parameters > Employees : :ok: 
BO > Advanced Parameters > Webservice : :ok:

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I checked all pages => ok only the page BO > Advanced Parameters > E-mail page following these steps:
1. Try to generate some emails in different languages, for example, create an account when English & French selected
2. Go to BO > Advanced Parameters > E-mail page
3. Try to search by English => ok
4. Try to search by empty language filter
5. See error => the previous result is displayed

I attached a screen record
https://watch.screencastify.com/v/5THJJgr1rfklNszJbsjD

Thanks!

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 7]
```diff
@@ -79,6 +98,10 @@ public function buildSearchResponse(
 
         $redirectParams = [];
         if ($filtersForm->isSubmitted()) {
+            if ($this->checkIsFormDataEmpty($filtersForm->getData())) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:101]: One thing that worries me here When you display the page initially, the form is empty but the grid should be displayed with the filter saved in DB That's the principle of those persisted filters

Is this method able to tell the difference between:
- the filters form has been submitted and has emty values so it is equivalent to reset the filters
- the page has been displayed, no filters data is available but it's not submitted so it's normal I should use the persisted filters

I wonder if somewhere in the check we should assert that the request was submitted? Via POST method checking, or `$form->isSubmitted()` or similar?

Comment (jolelievre) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:101]: Also, since this behaviour is quite tricky, and all this filtering feature is quite complex because it is split into many different components and the rules are quite original (I never persisted filters like this before, personally).

So to avoid regression, and mostly to set the expected behaviour into stone it would deserve some unit tests on this component. Like it was done for all the filters builders:
https://github.com/PrestaShop/PrestaShop/tree/e2c782cd09caddf28cd4cd489428f77bf1b027d6/tests/Unit/Core/Search/Builder

**Review by jolelievre — COMMENTED** [review]
Just a worry about the ResponseBuilder modifications. Besides that everything looks perfect to me.

File: src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php [hunk 8]
```diff
@@ -82,21 +72,15 @@ final class CategoryGridDefinitionFactory extends AbstractFilterableGridDefiniti
...
     /**
      * @param HookDispatcherInterface $hookDispatcher
-     * @param string $resetActionUrl
-     * @param string $redirectActionUrl
      * @param MultistoreContextCheckerInterface $multistoreContextChecker
      * @param AccessibilityCheckerInterface $categoryForViewAccessibilityChecker
      */
     public function __construct(
         HookDispatcherInterface $hookDispatcher,
-        $resetActionUrl,
```
Comment (matks) [inline src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php]: It would be very easy to avoid the BC break by keeping the arguments, even useless. Why force the BC break ? this will only make it harder for module developers to upgrade. We can deprecate these constructor arguments in 8.0.0 and remove them in 9.0.0 .

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
I am against the BC break if we can avoid it. Remember we want to make it smooth to upgrade from 1.7.8 to 8.0.0 and this can happen if we make sure we dont break everything between the two versions. If we can avoid the BC break without adding too much unnecessary code, we should do it. 8.0.0 does not aim to be a big breaking new version.

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php (hunk 3 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:154]: :heavy_check_mark:

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php (hunk 7 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:101]: Tested

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php [hunk 9]
```diff
@@ -64,29 +64,24 @@ public function indexAction(Request $request, EmailLogsFilter $filters)
...
-        $isEmailLogsEnabled = $configuration->get('PS_LOG_EMAILS');
-
-        $presentedEmailLogsGrid = null;
-
-        if ($isEmailLogsEnabled) {
-            $emailLogsGridFactory = $this->get('prestashop.core.grid.factory.email_logs');
-            $emailLogsGrid = $emailLogsGridFactory->getGrid($filters);
-            $presentedEmailLogsGrid = $this->presentGrid($emailLogsGrid);
-        }
+        $emailLogsGrid = $this->get('prestashop.core.grid.factory.email_logs')->getGrid($filters);
```
Comment (kpodemski) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php]: @Progi1984, does it mean that now we will see email logs, even after they had been disabled?

Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php]: Fixed

**Review by jolelievre — DISMISSED** [review]
Thank you @Progi1984

File: src/PrestaShopBundle/Service/Grid/ResponseBuilder.php [hunk 10]
```diff
@@ -99,4 +122,48 @@ public function buildSearchResponse(
...
+    }
+
+    /**
+     * Return true if array is empty (null values or empty array)
+     *
+     * @param array $formData
+     *
+     * @return bool
+     */
+    private function checkIsFormDataEmpty(array $formData): bool
```
Comment (sowbiba) [inline src/PrestaShopBundle/Service/Grid/ResponseBuilder.php:154]:
```
    private function isFormDataEmpty(array $formData): bool
```

**Review by sowbiba — DISMISSED** [review]
Just a method rename suggestion. Nice job

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry, I found a behavior, I don't know if it is a bug or a normal behavior

1. Go to BO > Catalog > Brands page
2. In the Addresses section
3. Filter by country => ok
4. Change the filter to `--` and click on "Search" 
image
5. The list display all the items but the **Reset** button is still displayed 
image

On the Other page, we have the list is reset
https://watch.screencastify.com/v/38YETZxf2CXRh2vQYW8F


Same behavior:
1. Go to BO > Customers > Addresses page
2. Search Country => ok
3.  Change the filter to `--` and click on "Search" 
4. The list display all the items but the **Reset** button is still displayed  
image


Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith Fixed with modification on `src/PrestaShopBundle/Form/Admin/Type/CountryChoiceType.php`

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
All migrated page that contain a list with drop-down filter => ok
https://watch.screencastify.com/v/Oy8huyAK38STqZcXyoTW

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
