### PR TITLE
Fix delivery information for the product

### LINKED ISSUE #9590: [BOOM-5960] Delivery information label is not refresh according to the quantity number
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5960).

- _**Reporter:**_ gadnis
- _**Created at:**_ Thu, 12 Jul 2018 10:49:09 +0200

<p>Hi. Warehouse theme support said that this is prestashop bug, so I write it here. </p>

---
#### Describe the bug

In product page there is an option to show delivery information and product availability labels. Warehouse theme has javascript feature: when user change quantity amount he wants to add to a cart, than product page refresh and show updated information.

#### Expected behavior

Delivery information have to change to "Delivery 2-4 weeks" as defined in BO, because user at least have to know that delivery time will be longer, cause there is 1 product we don't have in stock at the moment.

####  Steps to Reproduce

1. Create a product with quantity 1, choose **allow orders** for **Behavior when out of stock**
2. In FO, product page, you can see that Availability label is "In-Stock", and delivery information is "Delivery 1-3 working days"=> OK
3. Try to change the quantity to 2, as you can see the product section is refreshed => OK
4. After refresh, you can see that Availability label is "Possible to order", and delivery information remain same as before => NOK, cause we have one product available and the second is out of stock, so the delivery info should be **Delivery 2-4 weeks**

**Screenshots**

https://drive.google.com/file/d/15tRFoj3-z8qATuSLjxw_nlTv0rldTAqa/view

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We didn't get a real wanted quantity to determine delivery information + and there's no point in showing delivery times if you can't buy a product. I added proper tests for three scenarios.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Related to #9590.
| Related PRs       | https://github.com/PrestaShop/classic-theme/pull/26
| How to test?      | Instruction below
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

 Edit `product-prices.tpl` in your theme and check `{$product.delivery_information|dump}` before and after this change.

### CODE REVIEW

File: tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php [hunk 1]
```diff
@@ -91,6 +91,7 @@ class ProductLazyArrayTest extends TestCase
         'new' => 0,
         'pack' => 0,
         'out_of_stock' => OutOfStockType::OUT_OF_STOCK_DEFAULT,
+        'customizable' => 0,
```
Comment (matthieu-rolland) [inline tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php:94]: question: does this property have an impact on your test or did you add it for consistency with a real case scenario?

**Review by matthieu-rolland — COMMENTED** [review]
LGTM, just one question about something I'm not sure I understand

File: tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php (hunk 1 above)
Comment (kpodemski) [reply tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php:94]: @matthieu-rolland it was needed for a method which checks for enabling add to cart button

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@PrestaShop/qa-functional Can this PR be tested by developers?

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @kpodemski ,

I have installed and tested this PR with one https://github.com/PrestaShop/classic-theme/pull/26.

I have edited `product-prices.tpl`, added the dump part `{$product.delivery_information|dump}`
I see the dump in the FO like so, only when the Delivery  Time is not configured :
Screenshot 2022-05-16 at 18 09 06
Screenshot 2022-05-16 at 18 08 56
The dump part is always "null" ✔️ 
When I choose another option, it is never displayed ❌ 

I have 2 products with the same delivery config, same quantity, but a different outcome :
This one is OK ✔️ : 

https://user-images.githubusercontent.com/16019289/168641988-90c9a4ec-49df-47a8-9e15-402ba88e4315.mov

-> Delivery time is OK for any quantity

This one is NOK ❌ :

https://user-images.githubusercontent.com/16019289/168642195-8a452705-3026-4844-94ed-6d2901d5dd99.mov

-> For quantity 2, the delivery time is NOK, it should be `3 - 4 days` instead of `5 - 7 days`.

Tested on Product page normal and Product page V2. Same result.

Also, could fix a little thing ^^
When I choose `Delivery Time : Specific delivery time to this product` and leave it empty, I still see the "-", I think it shouldn't be displayed.
Screenshot 2022-05-16 at 18 47 40

Thanks a lot !

**Comment by kpodemski** [comment]
Hello @florine2623 

A few things:

1. this `dump` is not part of any `if`, so you'll always see a `null` or blank value if you don't have "Delivery times" configured in the settings. Remember that this variable works **only** with the configuration from the Preferences, not from the Product page.
2. For the second issue that you have, I'm pretty sure it's because you had this second product in the shopping cart, so the real available quantity was `1`

**Review by florine2623 — APPROVED** [review]
Thanks for the details !

I've tested again this feature ! It works as intended.

It is QA ✅

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623
