### PR TITLE
Instead of testing each hook if it is active, query once and cache.

### LINKED ISSUE #26747: Too many queries to test if hook is active
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Prestashop is repeating this query several dozens of times
```
SELECT active
FROM `ps_hook` h
WHERE (h.name = "**") LIMIT 1
```
The screenshot are from Profiling mode on a product page:

### Expected behavior

Query once the table ps_hook. Then a simple `in_array($hook_name, $active_hooks)` will do it. This can save dozens of queries depending on the page, even more than hundred (/!\) on a category page.

Screenshot on the same product page with proposed PR:
The table ps_hook is queried 7 times instead of 74

### Steps to reproduce

1. Enable Profiling mode
2. Open a FO page, search on the page for PREFIX_hook, you'll see an impressive number
3. Scroll down to table stress: hook is the champion.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Reduce the number of queries on one by page by 50 - 150 (!)
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26747.
| How to test?      | Compare any FO page in Profiling mode before an after fix.
| Possible impacts? | Performance improvement. No other impact is possible, the cange is very constrained.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26748)

### CODE REVIEW

File: classes/Hook.php [hunk 1]
```diff
@@ -1274,11 +1279,14 @@ private static function getMethodName(string $hookName): string
      */
     public static function getHookStatusByName($hook_name): bool
     {
-        $sql = new DbQuery();
-        $sql->select('active');
-        $sql->from('hook', 'h');
-        $sql->where('h.name = "' . pSQL($hook_name) . '"');
+        if (is_null(self::$active_hooks)) {
```
Comment (kpodemski) [inline classes/Hook.php]:
```suggestion
        if (null === static::$active_hooks) {
```

File: classes/Hook.php [hunk 2]
```diff
@@ -1274,11 +1279,14 @@ private static function getMethodName(string $hookName): string
...
+            $sql = new DbQuery();
+            $sql->select('name');
+            $sql->from('hook', 'h');
+            $sql->where('h.active = 1');
+            self::$active_hooks = array_column(Db::getInstance()->executeS($sql), 'name');
```
Comment (kpodemski) [inline classes/Hook.php]:
```suggestion
            static::$active_hooks = array_column(Db::getInstance()->executeS($sql), 'name');
```

File: classes/Hook.php [hunk 3]
```diff
@@ -1274,11 +1279,14 @@ private static function getMethodName(string $hookName): string
...
+        }
 
-        return (bool) Db::getInstance()->getValue($sql);
+        return in_array($hook_name, self::$active_hooks);
```
Comment (kpodemski) [inline classes/Hook.php]:
```suggestion
        return in_array($hook_name, static::$active_hooks);
```

File: classes/Hook.php [hunk 4]
```diff
@@ -63,6 +63,11 @@ class HookCore extends ObjectModel
 
     public static $native_module;
 
+    /**
+     * @var array|null Names of active hooks
+     */
+    protected static $active_hooks = null;
```
Comment (jolelievre) [inline classes/Hook.php]: You should add a line to clear this static field in the `resetStaticCache` method This will offer the possibility to clean it after modifications for example It's also very useful for our test environment where we frequently need to clear the cache

**Review by jolelievre — COMMENTED** [review]
Thanks @lmeyer1 just a suggestion to clear the cache

Also it would be nice to find why this behaviour changed in 178, which modification had this impact to understand the cause of the change

And I wonder if this PR should target 1.7.8.x or develop

File: classes/Hook.php (hunk 2 above)
Comment (jolelievre) [reply classes/Hook.php]: Oh one more suggestion, maybe you should only cache this if the result is not empty In case the method is called too early during installation for example

File: classes/Hook.php [hunk 5]
```diff
@@ -129,10 +129,17 @@ class HookCore extends ObjectModel
...
         Cache::clean('hook_idsbyname');
+        Cache::clean('hook_active');
 
         return parent::add($autodate, $null_values);
     }
 
+    public function clearCache($all = false)
+    {
+        Cache::clean('hook_*');
+        parent::clearCache($all); // TODO: Change the autogenerated stub
```
Comment (jolelievre) [inline classes/Hook.php]: Why the comment, it's perfectly fine to cal the parent function it's even recommended

**Review by jolelievre — DISMISSED** [review]
Except the extra comment it seems good to me
All that's left is to decide if this should target develop or 178x

File: classes/Hook.php (hunk 5 above)
Comment (lmeyer1) [reply classes/Hook.php]: Oh that's PHPStorm that autogenerated the method, and I forgot to change it.

**Comment by lmeyer1** [comment]
> Also it would be nice to find why this behaviour changed in 178, which modification had this impact to understand the cause of the change

The offending method was added with revision 9e490855 Merge branch '1.7.7.x' of github.com:PrestaShop/PrestaShop into merge177xintodevelop-7

I don't have the time to drill down further.

**Comment by marionf** [comment]
Hello @lmeyer1 
As the issue is a regression of the 1.7.8.0, could you rebase your PR on 1.7.8.x ?

File: classes/Address.php [hunk 6]
```diff
@@ -440,14 +440,23 @@ public static function getCountryAndState($id_address)
      *
      * @return bool The address exists
      */
-    public static function addressExists($id_address)
+    public static function addressExists($id_address, $refreshCache = false): bool
```
Comment (Progi1984) [inline classes/Address.php]:
```suggestion
    public static function addressExists($id_address, bool $refreshCache = false)
```

Could you add the PHPDoc ?

**Review by Progi1984 — COMMENTED** [review]
@lmeyer1 Thank you for your contribution. Could you add my suggestion for avoiding BC Break on method signature ? Thanks

**Comment by kpodemski** [comment]
@lmeyer1 I think you pushed an entirely different branch now?

**Comment by lmeyer1** [comment]
@kpodemski 
The only thing I changed is the suggestion of @Progi1984, and now everything fails. I think there is a new bug in CI, again.
And yes, now it is the 1.7.8.x branch, no longer develop.

**Comment by kpodemski** [comment]
@lmeyer1 but these changes are related to the `Address` class and this PR should be about Hooks?

**Comment by lmeyer1** [comment]
@kpodemski Thank you! I mixed up two PR. Now it is fixed.

**Review by tegbessou — DISMISSED** [review]

File: classes/Hook.php [hunk 7]
```diff
@@ -1260,13 +1267,19 @@ private static function getMethodName(string $hookName): string
      *
      * @return bool
      */
-    public static function getHookStatusByName($hook_name): bool
+    public static function getHookStatusByName($hook_name, $refreshCache = false): bool
```
Comment (kpodemski) [inline classes/Hook.php]: We could avoid `BC Break` if we do:

`Hook::resetStaticCache()`
`Hook::getHookStatusByName('someName');`

Comment (kpodemski) [reply classes/Hook.php]: Ok, now I understand why you decided to go with the `clearCache` instead of the `resetStaticCache`, although I'm still not sure if we really need a new argument here, if we target `1.7.8.x` it might be better to keep it simple

Comment (lmeyer1) [reply classes/Hook.php]: @kpodemski What would you like me to do now? And why is this a `BC break`?
- remove parameter `$refreshCache` ? I decided to do it like this, because it was done like this in another class.
- extend `ObjectModel::resetStaticCache` in `Hook::resetStaticCache` ?

The tests fail at `LegacyTests\Unit\Adapter\Module\PrestaTrust\PrestaTrustCheckerTest::testModuleHasPico`, this really looks unrelated.

Comment (kpodemski) [reply classes/Hook.php]: @lmeyer1 

If someone has an override for this method, it won't work anymore after the upgrade (strict error).

I would keep `Hook::clearCache` but remove `$refreshCache`. In the tests, we can rely on the `Hook::clearCache`

Comment (lmeyer1) [reply classes/Hook.php]: @kpodemski Thanks for clarification.

**Review by kpodemski — DISMISSED** [review]

File: classes/Hook.php [hunk 8]
```diff
@@ -126,10 +126,17 @@ class HookCore extends ObjectModel
     public function add($autodate = true, $null_values = false)
     {
         Cache::clean('hook_idsbyname');
+        Cache::clean('hook_active');
 
         return parent::add($autodate, $null_values);
     }
 
+    public function clearCache($all = false)
```
Comment (Progi1984) [inline classes/Hook.php:135]:
```suggestion
    public function clearCache(bool $all = false): void
```

File: classes/Hook.php [hunk 9]
```diff
@@ -1262,11 +1269,17 @@ private static function getMethodName(string $hookName): string
...
+            $sql->from('hook', 'h');
+            $sql->where('h.active = 1');
+            $active_hooks = Db::getInstance()->executeS($sql);
+            if (!empty($active_hooks)) {
+                Cache::store('hook_active', array_column($active_hooks, 'name'));
+            }
+        }
 
-        return (bool) Db::getInstance()->getValue($sql);
+        return in_array($hook_name, Cache::retrieve('hook_active'));
```
Comment (Progi1984) [inline classes/Hook.php]:
```suggestion
        return in_array($hook_name, Cache::retrieve('hook_active'));
```

Please check that `Cache::retrieve('hook_active')` is an array

**Review by Progi1984 — COMMENTED** [review]
@lmeyer1 Thank you for your contribution. I have brought you some comments.

File: classes/Hook.php (hunk 9 above)
Comment (lmeyer1) [reply classes/Hook.php]: Instead of testing on cache read, it is much better to test on cache write. That way, the correct type on cache read is guaranteed.
And we save some processor cycles. This aspect is always important to keep in mind.
Test things once in the right place. Do not test things dozens or hundreds of times.

File: classes/Hook.php (hunk 8 above)
Comment (lmeyer1) [reply classes/Hook.php:135]: Looks like this was on overzealous change:
Tests say:
> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: Declaration of HookCore::clearCache(bool $all = false): bool should be compatible with ObjectModelCore::clearCache($all = false) in /home/runner/work/PrestaShop/PrestaShop/classes/Hook.php:1287

**Review by kpodemski — DISMISSED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
CI is still not happy 😅

**Comment by lmeyer1** [comment]
@matks 
Yes, it is in `LegacyTests\Unit\Adapter\Module\PrestaTrust\PrestaTrustCheckerTest::testModuleHasPico`.
This test creates mock modules, but I don't see why caching a if a Hook is active could break something there.

File: classes/Hook.php (hunk 9 above)
Comment (kpodemski) [reply classes/Hook.php]: @lmeyer1 this is the reason why unit tests are failing, if you do:

```
$active_hooks = Cache::retrieve('hook_active') ?? [];
return in_array($hook_name, $active_hooks);
```

tests are green :-) In unit tests cache is not set

Comment (lmeyer1) [reply classes/Hook.php]: @kpodemski 
Thank you. But this will always return false if cache is disabled... Shouldn't it return true if module is active, even in test context?
Now that I understand what's wrong, I hope to get it right.

File: classes/Hook.php [hunk 10]
```diff
@@ -1262,11 +1269,23 @@ private static function getMethodName(string $hookName): string
...
-        $sql->from('hook', 'h');
-        $sql->where('h.name = "' . pSQL($hook_name) . '"');
+        $hook_names = [];
+        if (Cache::isStored('hook_active')) {
+            $hook_names = Cache::retrieve('hook_active');
+        } else {
+            $sql = new DbQuery();
+            $sql->select('name');
+            $sql->from('hook', 'h');
+            $sql->where('h.active = 1');
```
Comment (PierreRambaud) [inline classes/Hook.php:1282]:
```suggestion
```
Otherwise you don't retrieve any status and the method name is wrong :thinking:

Comment (PierreRambaud) [reply classes/Hook.php:1282]: My bad, seen the in_array after

**Review by PierreRambaud — COMMENTED** [review]
I'm not in favor of using the `Cache` instance, it's not appropriate. Use Db cache instead, which was already done by the second parameter of `getValue` call.
So, to improve perf for this page, maybe selecting all data by key => value ('name' => 'active') should be enough.

**Comment by lmeyer1** [comment]
@PierreRambaud 
> I'm not in favor of using the Cache instance, it's not appropriate. Use Db cache instead, which was already done by the second parameter of getValue call.

The whole point was to reduce the number of queries by several dozens per page. Relying on Db cache for this is not appropriate either. The only thing appropriate is querying once by page.
I don't like to argue on HOW to achieve this (Cache or static property or any other method). What I'm sure of is that querying the database once is 50x faster than querying it 50 times. No matter how well we configured the server for Db cache.

About Db cache: As of version 8.0, mysql does no longer have that feature. Should PS still rely on it?

File: classes/Hook.php [hunk 11]
```diff
@@ -126,10 +126,17 @@ class HookCore extends ObjectModel
...
     {
         Cache::clean('hook_idsbyname');
+        Cache::clean('hook_active');
 
         return parent::add($autodate, $null_values);
     }
 
+    public function clearCache($all = false)
+    {
+        Cache::clean('hook_*');
```
Comment (sowbiba) [inline classes/Hook.php]: isn't it risky to clean using a wilcard ? I think you should clean specifically what you want

And if you change this, you will be able to change the key of the cache entry you added 
from `hook_active`, which make me thing about a boolean to `active_hooks`

Comment (lmeyer1) [reply classes/Hook.php]: @sowbiba 
Shouldn't `clearCache` also clear the two other entries 'hook_idsbyname' and 'hook_idsbyname_withalias' ?

And just found another error : Herre https://github.com/PrestaShop/PrestaShop/pull/26748/files#diff-d5d273eeef7469e6cf4038eb2ee139ee12927a7709ea47f97d66e8b39da60178L128 is missing `Cache::clean('hook_idsbyname_withalias');`

File: classes/Hook.php [hunk 12]
```diff
@@ -126,10 +126,20 @@ class HookCore extends ObjectModel
...
         Cache::clean('hook_idsbyname');
+        Cache::clean('hook_idsbyname_withalias');
+        Cache::clean('active_hooks');
 
         return parent::add($autodate, $null_values);
     }
 
+    public function clearCache($all = false)
+    {
+        Cache::clean('hook_idsbyname');
```
Comment (jolelievre) [inline classes/Hook.php:137]:
```suggestion
        Cache::clean('hook_*');
```

Comment (jolelievre) [reply classes/Hook.php:137]: Just for information, but you can clear multiple cache keys using the wildcard `*` Not mandatory though

File: tests-legacy/Unit/Controller/Admin/AdminTabsControllerTest.php [hunk 13]
```diff
@@ -105,8 +105,9 @@ public function setupDatabaseMock($mock = null)
                 if ($subject instanceof DbQuery) {
                     $builtQuery = $subject->build();
 
-                    // It should select modules
-                    return strpos($builtQuery, 'module') !== false;
+                    // It should select modules and test if hook is active
+                    return strpos($builtQuery, 'module') !== false ||
```
Comment (jolelievre) [inline tests-legacy/Unit/Controller/Admin/AdminTabsControllerTest.php:109]: I'm not sure I understand the reason for this change 🤔

File: classes/Hook.php (hunk 12 above)
Comment (lmeyer1) [reply classes/Hook.php:137]: @jolelievre
That is the change that @sowbiba requested https://github.com/PrestaShop/PrestaShop/pull/26748#discussion_r770592862. He doesn't like the wildcard `*`

File: tests-legacy/Unit/Controller/Admin/AdminTabsControllerTest.php (hunk 13 above)
Comment (lmeyer1) [reply tests-legacy/Unit/Controller/Admin/AdminTabsControllerTest.php:109]: The reason is that somewhere the function I modified is called `getHookStatusByName()`, and I have to whitelist it here so that the test my pass.

**Comment by PierreRambaud** [comment]
> 

You can reduce the number of queries without having to use the cache, you're using a class, you're able to use properties in order to store results instead of querying the cache system.

**Comment by lmeyer1** [comment]
Finally, after @PierreRambaud 's comment, I will implement this without the `Cache` class. Rather I will use a static property on `Hook`. This will reduce the number of db queries by dozens, while not store informations to the Cache that don't belong there.

Edit:
In the meantime, I looked at the code of class `Cache`. The methods I use (`isStored`, `store`, `retrieve` and `clean`) have nothing to do with redis or memcached. This is a per request global variable cache.

Thus, everything is okay now, nothing needs to be changed anymore.
- We are using a per request cache in a global variable
- The is only one mysql request about active hooks instead of dozens.

File: classes/Hook.php (hunk 12 above)
Comment (sowbiba) [reply classes/Hook.php:137]: Don't mind. It's just cache, supposed to be easy to rebuild. You can revert the change

**Comment by PierreRambaud** [comment]
I go further in how the Abstract class CacheCore is working with what @lmeyer1 told me.
Seems the abstract class doesn't rely on any storage, only in a static $local var. I don't understand why they use an abstract class like that :/  
So the fix seems ok ^^

File: classes/Hook.php (hunk 12 above)
Comment (PierreRambaud) [reply classes/Hook.php:137]: If you use the following wording you don't have to implement the clearCache method
```suggestion
        Cache::clean('objectmodel_hook_idsbyname');
```
It will rely only on this object model and it will be easier to clear, it's also more consistent because you've less chance for someone to already use this cache keys

Comment (PierreRambaud) [reply classes/Hook.php:137]: You're also able to use const in order to don't copy & paste strings and make sure the wording is the same everywhere

**Review by kpodemski — APPROVED** [review]
Well done @lmeyer1

**Review by jolelievre — APPROVED** [review]
Thanks @lmeyer1

**Review by matks — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your PR :clap: 
LGTM, QA :heavy_check_mark: 

https://user-images.githubusercontent.com/23308427/148984060-f2518376-1681-4d41-801f-1376741394c3.mp4

Thanks!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
WAIT FOR 1783 RELEASE

**Review by PululuK — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @lmeyer1 & @hibatallahAouadni

File: classes/Hook.php (hunk 12 above)
Comment (Djolhan1) [reply classes/Hook.php:137]: @lmeyer1  Hi, i don't know where to post this (not realy usual with github), but since the update of this file, I have a blog module that ends on a 404. I put back the Hook.php file from version 1.7.8.3 and no more probleme. Have you any idea to fix this issue ?

**Comment by PululuK** [comment]
Thanks you @lmeyer1

File: classes/Hook.php (hunk 12 above)
Comment (lmeyer1) [reply classes/Hook.php:137]: @Djolhan1 Hello, please open a new issue, thank you https://github.com/PrestaShop/PrestaShop/issues

Comment (Djolhan1) [reply classes/Hook.php:137]: > @Djolhan1 Hello, please open a new issue, thank you https://github.com/PrestaShop/PrestaShop/issues

Thank for your answer, Done, hope it help : https://github.com/PrestaShop/PrestaShop/issues/27872

**Comment by matks** [comment]
@prestashop-issue-bot Go and have some rest 😝
