### PR TITLE
Fixed case where the "Place Order" button is disabled when the order is free and "Terms of service" is disabled

### LINKED ISSUE #9927: [BOOM-3601] FO - Checkout - The "Place Order" button is disabled when the order is free and "Terms of service" is disabled
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3601).

- _**Reporter:**_ sakpase16
- _**Created at:**_ Fri, 4 Aug 2017 17:11:41 +0200

<p>If I try to checkout with a completely free order the "Order with obligation to pay" button is disabled unless I turn on the setting "Terms of service" under "Shop Parameters > Order Settings" and require customers to check that box in the checkout process.</p>

<p>I would like to be able to have a completely free order without having to check the terms and conditions box.</p>

How to reproduce the issue ?

- Disable "Terms of service" in Order Settings
- Add a free item to cart
- Start checkout process
- Add shipping method (also free)
- Order is completely free
- Order with obligation to pay button is disabled ergo, I can't complete order.

---

#### Describe the bug
If I try to checkout with a completely free order, the "Place Order" button is disabled unless I turn on the setting "Terms of service" under "Shop Parameters > Order Settings".

#### Expected behavior

The **Place Order** button should be **enabled** and **clickable**

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Shop Parameters** > **Order Settings**
2. Disable **Terms of service** > **Save**

image

3. **BO** > **SELL** > **Catalog** > **Products** 
4. Create a new **free** product (price=0)
5. **FO** > Add the **free** product to the **cart**
6. **Proceed to checkout**, choose an address and click on **Continue**
7. Choose the **free** shipping method, then click on **Continue**
8. In the **Payment** section, the order is totally free, so there's no payment methods => **OK**
9. The **Place Order** button is disabled  => **NOK**
10. _You can click on the button and complete your order =>_ **OK** (**`This step is OK only on develop`**)

image

#### Screen Record

https://drive.google.com/file/d/1fy5KzaOi-iSfUb7C_CfeSU18toSY9Du1/view

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by tswfi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Test case for #9927 (FO - Checkout - The "Place Order" button is disabled when the order is free and "Terms of service" is disabled)
| Type?         | bug fix
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9927.
| How to test?  | ```docker-compose up``` and run ```HEADLESS=false TEST_PATH="regression/checkout/100PercentDiscount_FO.js" URL_FO="http://localhost:8001/" npm run specific-test```

While writing this I think I found few more problems:

* checkout button selector in the test case uses [disabled] but the button is not actually disabled it only has a class disabled (at least in this scenario)
* clicking the confirm button goes to login page (should go to order confirmation page)

This was done as an exercise of howto use your test suite :) so it might not be up to all the testing standards you have, improvement suggestions are welcome :) (like, I guessed that this should probably be a regresssion test ;)

I will probably continue on this branch to add the fix also but wanted to get this out here to get some feedback if this is even the correct way to start fixing things.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22389)

### CODE REVIEW

**Comment by tswfi** [comment]
Now this PR also includes a fix. (will update subject also)

Again suggestions welcome.

**Comment by tswfi** [comment]
Fixed the problem with order confirmation not showing for 0 priced order.

My test case does not check other situattions (like logged in customer etc), I'm counting on other test cases to check those.

**Review by Progi1984 — DISMISSED** [review]

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 1]
```diff
@@ -0,0 +1,408 @@
...
+const addCartRulePage = require("@pages/BO/catalog/discounts/add");
+const orderSettingsPage = require("@pages/BO/shopParameters/orderSettings");
+
+const localizationPage = require("@pages/BO/international/localization");
+const currenciesPage = require("@pages/BO/international/currencies");
+const addCurrencyPage = require("@pages/BO/international/currencies/add");
+const ordersPage = require("@pages/BO/orders");
+const sqlManagerPage = require("@pages/BO/advancedParameters/database/sqlManager");
+const addSqlQueryPage = require("@pages/BO/advancedParameters/database/sqlManager/add");
+const viewSqlQueryPage = require("@pages/BO/advancedParameters/database/sqlManager/view");
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
```

Please unused pages

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 2]
```diff
@@ -0,0 +1,408 @@
...
+
+// FO pages
+const homePage = require("@pages/FO/home");
+const searchResultsPage = require("@pages/FO/searchResults");
+const foLoginPage = require("@pages/FO/login");
+const productPage = require("@pages/FO/product");
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
```

Same here

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 3]
```diff
@@ -0,0 +1,408 @@
...
+const cartPage = require("@pages/FO/cart");
+const checkoutPage = require("@pages/FO/checkout");
+const orderConfirmationPage = require("@pages/FO/checkout/orderConfirmation");
+
+// Import expect from chai
+const { expect } = require("chai");
+
+// Import demo data
+const { PaymentMethods } = require("@data/demo/paymentMethods");
+
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 4]
```diff
@@ -0,0 +1,408 @@
...
+const CustomerFaker = require("@data/faker/customer");
+const AddressFaker = require("@data/faker/address");
+
+const percentCartRule = new CartRuleFaker({
+  name: "discount100",
+  code: "discount100",
+  discountType: "Percent",
+  discountPercent: 100,
+  freeShipping: "on",
+});
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js:38]:
```suggestion
});

```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 5]
```diff
@@ -0,0 +1,408 @@
...
+          baseContext
+        );
+
+        const validationMessage = await addCartRulePage.createEditCartRules(
+          page,
+          percentCartRule
+        );
+        await expect(validationMessage).to.contains(
+          addCartRulePage.successfulCreationMessage
+        );
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
        const validationMessage = await addCartRulePage.createEditCartRules(
          page,
          percentCartRule
        );
        
        await expect(validationMessage).to.contains(
          addCartRulePage.successfulCreationMessage
        );
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 6]
```diff
@@ -0,0 +1,408 @@
...
+          page,
+          dashboardPage.shopParametersParentLink,
+          dashboardPage.orderSettingsLink
+        );
+
+        const pageTitle = await orderSettingsPage.getPageTitle(page);
+        await expect(pageTitle).to.contains(orderSettingsPage.pageTitle);
+      });
+      it("Should change the terms and conditions back to disabled", async () => {
+        const result = await orderSettingsPage.setTermsOfService(page, false);
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      });
      
      it("Should change the terms and conditions back to disabled", async () => {
        await testContext.addContextItem(
          this,
          'testIdentifier',
          'dissableTermAndConditions',
          baseContext,
        );
        
        const result = await orderSettingsPage.setTermsOfService(page, false);
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 7]
```diff
@@ -0,0 +1,408 @@
...
+      );
+
+      await cartPage.addPromoCode(page, percentCartRule.code);
+
+      const grandTotal = await cartPage.getATIPrice(page);
+      await expect(grandTotal, "Order total price is incorrect").to.equal(0);
+    });
+
+    it("should go to checkout process", async function () {
+      await cartPage.clickOnProceedToCheckout(page);
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
    it("should go to checkout process", async function () {
      await testContext.addContextItem(
        this,
        "testIdentifier",
        "proceedToCheckout",
        baseContext
      );
      
      await cartPage.clickOnProceedToCheckout(page);
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 8]
```diff
@@ -0,0 +1,408 @@
...
+        baseContext
+      );
+
+      await homePage.addProductToCartByQuickView(page, 1, "1");
+      await homePage.proceedToCheckout(page);
+      const pageTitle = await cartPage.getPageTitle(page);
+      await expect(pageTitle).to.equal(cartPage.pageTitle);
+    });
+
+    it("should add our discount code and check that the grandtotal is 0", async function () {
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
    it("should add our discount code and check that the total price is 0", async function () {
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 9]
```diff
@@ -0,0 +1,408 @@
...
+        this,
+        "testIdentifier",
+        "setAddressStep",
+        baseContext
+      );
+
+      const isStepAddressComplete = await checkoutPage.setAddress(
+        page,
+        addressData
+      );
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js:256]:
```suggestion
      );
      
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 10]
```diff
@@ -0,0 +1,408 @@
...
+      await expect(isStepAddressComplete, "Step Address is not complete").to.be
+        .true;
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      await expect(isStepAddressComplete, "Step Address is not complete")
        .to.be.true;
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 11]
```diff
@@ -0,0 +1,408 @@
...
+        this,
+        "testIdentifier",
+        "goToLastStep",
+        baseContext
+      );
+
+      // Delivery step - Go to payment step
+      const isStepDeliveryComplete = await checkoutPage.goToPaymentStep(page);
+      await expect(isStepDeliveryComplete, "Step Address is not complete").to.be
+        .true;
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      await expect(isStepDeliveryComplete, "Step Address is not complete")
        .to.be.true;
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 12]
```diff
@@ -0,0 +1,408 @@
...
+        "testIdentifier",
+        "checkNoPaymentNeededText",
+        baseContext
+      );
+
+      const noPaymentNeededText = await checkoutPage.getTextContent(
+        page,
+        checkoutPage.noPaymentNeededElement
+      );
+      await expect(noPaymentNeededText).to.contains(checkoutPage.noPaymentNeededText);
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      const noPaymentNeededText = await checkoutPage.getTextContent(
        page,
        checkoutPage.noPaymentNeededElement
      );
      
      await expect(noPaymentNeededText).to.contains(checkoutPage.noPaymentNeededText);
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 13]
```diff
@@ -0,0 +1,408 @@
...
+        this,
+        "testIdentifier",
+        "checkCompleteIsNotDisabled",
+        baseContext
+      );
+
+      const confirmButtonVisible = await checkoutPage.isPaymentConfirmationButtonVisibleAndEnabled(
+        page
+      );
+      await expect(confirmButtonVisible, "Confirm button visible").to.be.true;
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      const confirmButtonVisible = await checkoutPage.isPaymentConfirmationButtonVisibleAndEnabled(
        page
      );
      
      await expect(confirmButtonVisible, "Confirm button visible").to.be.true;
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 14]
```diff
@@ -0,0 +1,408 @@
...
+        checkoutPage.paymentConfirmationButton
+      );
+
+      // Check that we got to order confirmation (probably not necessary)
+      const cardTitle = await orderConfirmationPage.getOrderConfirmationCardTitle(
+        page
+      );
+      await expect(cardTitle).to.contains(
+        orderConfirmationPage.orderConfirmationCardTitle
+      );
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      const cardTitle = await orderConfirmationPage.getOrderConfirmationCardTitle(
        page
      );
      
      await expect(cardTitle).to.contains(
        orderConfirmationPage.orderConfirmationCardTitle
      );
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 15]
```diff
@@ -0,0 +1,408 @@
...
+      });
+      it("Should change the terms and conditions back to enabled", async () => {
+        const result = await orderSettingsPage.setTermsOfService(
+          page,
+          true,
+          "Terms and conditions of use"
+        );
+        await expect(result).to.contains(
+          orderSettingsPage.successfulUpdateMessage
+        );
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
        const result = await orderSettingsPage.setTermsOfService(
          page,
          true,
          "Terms and conditions of use"
        );
        
        await expect(result).to.contains(
          orderSettingsPage.successfulUpdateMessage
        );
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 16]
```diff
@@ -0,0 +1,408 @@
...
+        this,
+        "testIdentifier",
+        "addPercentDiscount",
+        baseContext
+      );
+
+      await cartPage.addPromoCode(page, percentCartRule.code);
+
+      const grandTotal = await cartPage.getATIPrice(page);
+      await expect(grandTotal, "Order total price is incorrect").to.equal(0);
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      const totalPrice = await cartPage.getATIPrice(page);
      await expect(totalPrice, "Order total price is incorrect").to.equal(0);
```

File: tests/UI/pages/FO/checkout/index.js [hunk 17]
```diff
@@ -113,6 +115,16 @@ class Checkout extends FOBasePage {
     return this.elementVisible(page, this.deliveryOptionLabel(shippingMethod), 2000);
   }
 
+  /**
+   * Is confirm button visible and enabled
+   * @param page
+   * @returns {Promise<boolean>}
+   */
+  isPaymentConfirmationButtonVisibleAndEnabled(page) {
+    // small side effect note, the selector is the one that checks for disabled
```
Comment (boubkerbribri) [inline tests/UI/pages/FO/checkout/index.js:144]: > small side effect note, the selector is the one that checks for disabled

So no need to add selector `this.noPaymentNeededElement` ?

**Review by boubkerbribri — COMMENTED** [review]
Thank you @tswfi , this is very nice.

I just added some comments to increase readability and to delete unnecessary variables.

Could you also run this command in `tests/UI/` folder `npm run lint-fix` , it should delete some spaces, add some comas ...

**Comment by tswfi** [comment]
> I just added some comments to increase readability and to delete unnecessary variables.

Thanks!

> Could you also run this command in `tests/UI/` folder `npm run lint-fix` , it should delete some spaces, add some comas 

Ok, so my vscode has very different idea on the style :D do you happen to have .editorconfig or similar? Or do you know how to tell editors to use your linting rules when doing autoformat for js files?

File: tests/UI/pages/FO/checkout/index.js (hunk 17 above)
Comment (tswfi) [reply tests/UI/pages/FO/checkout/index.js:144]: `this.noPaymentNeededElement` is used in the test case.

What I meant with my comment is that the `this.paymentConfirmationButton` has the `[disabled]` selector. This might be confusing as the one might want to check that the button is there and what its state is. Also it looks like the disabled attribute is not even set in all situations and the styling happens with `disabled` class.

I feel this could probably be improved on. Maybe having something like:
```
this.paymentConfirmationButton = `${this.paymentStepSection} #payment-confirmation button`;
this.paymentConfirmationDisabledButton = `${this.paymentStepSection} #payment-confirmation button:not([disabled])`;
```
I had to double check the source and code a few times before I trusted that `this.paymentConfirmationButton` selector :)


Also if you could give input on the `${this.paymentStepSection} div.content > p` I feel that the `p` should at least have a class (something like "NoPaymentNeededParagraph") for easier styling and even just for this test to have more specific selector for the element.

Comment (boubkerbribri) [reply tests/UI/pages/FO/checkout/index.js:144]: > `this.noPaymentNeededElement` is used in the test case.
> 
> What I meant with my comment is that the `this.paymentConfirmationButton` has the `[disabled]` selector. This might be confusing as the one might want to check that the button is there and what its state is. Also it looks like the disabled attribute is not even set in all situations and the styling happens with `disabled` class.
> 
> I feel this could probably be improved on. Maybe having something like:
> 
> ```
> this.paymentConfirmationButton = `${this.paymentStepSection} #payment-confirmation button`;
> this.paymentConfirmationDisabledButton = `${this.paymentStepSection} #payment-confirmation button:not([disabled])`;
> ```

> I had to double check the source and code a few times before I trusted that `this.paymentConfirmationButton` selector :)

You are absolutely right, your comment is the best way to do it. The main reason why we didn't have 2 selectors, is we didn't have enough use cases to use them both, but with this, I'm sure we can.

> Also if you could give input on the `${this.paymentStepSection} div.content > p` I feel that the `p` should at least have a class (something like "NoPaymentNeededParagraph") for easier styling and even just for this test to have more specific selector for the element.

I'm not sure where to do it. I will try to find and do it later

**Comment by boubkerbribri** [comment]
> > Could you also run this command in `tests/UI/` folder `npm run lint-fix` , it should delete some spaces, add some comas
> 
> Ok, so my vscode has very different idea on the style :D do you happen to have .editorconfig or similar? Or do you know how to tell editors to use your linting rules when doing autoformat for js files?


We have `.estlintrc` for ESLint rules, No rule set in the IDE, and maybe it's become a habits to fellow this rules.

**Review by boubkerbribri — DISMISSED** [review]

File: controllers/front/OrderConfirmationController.php [hunk 18]
```diff
@@ -158,6 +169,12 @@ protected function checkFreeOrder()
             false,
             $cart->secure_key
         );
+
+        // redirect back to us with rest of the data
+        // note the id_module parameter with value -1
+        // it acts as a marker for the module check to use "free_payment"
+        // for the check
+        Tools::redirect('index.php?controller=order-confirmation&id_cart=' . (int) $cart->id . '&id_module=-1&id_order=' . $order->currentOrder . '&key=' . $cart->secure_key);
```
Comment (PierreRambaud) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
        Tools::redirect('index.php?controller=order-confirmation&id_cart=' . (int) $cart->id . '&id_module=-1&id_order=' . (int) $order->currentOrder . '&key=' . $cart->secure_key);
```

File: controllers/front/OrderConfirmationController.php [hunk 19]
```diff
@@ -65,9 +67,18 @@ public function init()
...
+
+        // free order uses -1 as id_module, it has a special check here
+        if ($this->id_module == -1) {
+            if ($order->module != 'free_order') {
+                Tools::redirect($redirectLink);
+            }
+        } else {
+            // and the normal check that module matches
+            $module = Module::getInstanceById((int) ($this->id_module));
+            if ($order->module != $module->name) {
```
Comment (PierreRambaud) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
            if ($order->module !== $module->name) {
```

File: controllers/front/OrderConfirmationController.php [hunk 20]
```diff
@@ -65,9 +67,18 @@ public function init()
         if (!Validate::isLoadedObject($order) || $order->id_customer != $this->context->customer->id || $this->secure_key != $order->secure_key) {
             Tools::redirect($redirectLink);
         }
-        $module = Module::getInstanceById((int) ($this->id_module));
-        if ($order->module != $module->name) {
-            Tools::redirect($redirectLink);
+
+        // free order uses -1 as id_module, it has a special check here
+        if ($this->id_module == -1) {
+            if ($order->module != 'free_order') {
```
Comment (PierreRambaud) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
            if ($order->module !== 'free_order') {
```

File: controllers/front/OrderConfirmationController.php [hunk 21]
```diff
@@ -65,9 +67,18 @@ public function init()
         if (!Validate::isLoadedObject($order) || $order->id_customer != $this->context->customer->id || $this->secure_key != $order->secure_key) {
             Tools::redirect($redirectLink);
         }
-        $module = Module::getInstanceById((int) ($this->id_module));
-        if ($order->module != $module->name) {
-            Tools::redirect($redirectLink);
+
+        // free order uses -1 as id_module, it has a special check here
```
Comment (PierreRambaud) [inline controllers/front/OrderConfirmationController.php:71]: Do you have an idea where the -1 is settled?

Comment (tswfi) [reply controllers/front/OrderConfirmationController.php:71]: checkFreeOrder does a redirect back here. 

The original request has just free_order=1 as a parameter. 
The first check above is to call checkFreeOrder() (which should probably be renamed to handleFreeOrder() ) 
In checkFreeOrder method line 177 (https://github.com/PrestaShop/PrestaShop/pull/22389/files#diff-b8ddf176f2937afab07da250219b256a0a9c06b1fd8f2901797f1f0a2d85b34cR177) does basket => order and redirects back here (just like a real payment method module would) and the process continues as usual.

I don't really like that -1 but it helps with the line 67 check that wants "true" value for module and we cannot use any positive integer as that would try to load some random module..

The real fix should probably be to make a "freePayment" module that cannot be uninstalled and that does a "real" payment process just like all the other payment modules...

Comment (PierreRambaud) [reply controllers/front/OrderConfirmationController.php:71]: I don't think the `id_module` needs to be used here. If you need something special you can add a custom dedicated parameter that will be more evident to use and understand.
It's the same with `$order->module` as `free_order`.
If it's not a module we should bypass checks and should do only what we need.

Comment (tswfi) [reply controllers/front/OrderConfirmationController.php:71]: I have not dug too deep into all this logic so this is also a change that should probably be checked by few people who are well versed on the payment process and all the edge cases (especially from security point of view). 

As far as I know this is safe (the module name check should make sure that basket with "paypal" should not go through with free_order=1 etc), that said I'm not 100% sure (I've been reading prestashop code for just a few days now...)

Comment (PierreRambaud) [reply controllers/front/OrderConfirmationController.php:71]: You're right about security, it should be up to the payment module to provide free order.

Comment (tswfi) [reply controllers/front/OrderConfirmationController.php:71]: @PierreRambaud yup, another flag would work also and will probably be clearer.

Do you know why the orderpresenter is initiated in this init function? If that could be moved to initContent the flag could just return from init which would make this pretty clear and the check on line 63 would not have be touched either.

Comment (tswfi) [reply controllers/front/OrderConfirmationController.php:71]: If I had to guess none of the payment modules handle 0 total orders correctly as it is handled internally with https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentFree.php . At the moment they cannot even test the situation where the order is 0 total (no payments can be selected and the form goes to ?free_order=1 and gets handled very differently).

But if that PaymentFree class could be "raised" to be a real module and payment selection forces that module to be only one available when order has 0 total the process would be the same for all orders and every payment module developer can keep ignoring the 0 price situation.

That raises new question if that new PaymentFree should always be available (aka, no uninstall available for it). Or if it is installed should the payment selector just show a "No payment methods available for 0 priced orders". Or maybe something else completely?

**Comment by SimonGrn** [comment]
Hello @tswfi 

I just wanted to thank you for the huge work you did regarding the UI tests. This is refreshing to see people taking tests seriously and helping the project grow and become more robust.

This is really appreciated.

File: controllers/front/OrderConfirmationController.php (hunk 21 above)
Comment (PierreRambaud) [reply controllers/front/OrderConfirmationController.php:71]: I will try to investigate on Monday :+1:

Comment (PierreRambaud) [reply controllers/front/OrderConfirmationController.php:71]: Still didn't have the time to investigate, sorry :(

Comment (tswfi) [reply controllers/front/OrderConfirmationController.php:71]: @PierreRambaud no worries, aren't we all still just eating christmas leftovers and waiting for 2020 to end :D

Comment (PierreRambaud) [reply controllers/front/OrderConfirmationController.php:71]: @tswfi True story :roll_eyes:

Comment (PierreRambaud) [reply controllers/front/OrderConfirmationController.php:71]: Hey, finally took time to investigate, Tried to change many things to make sure I can't bypass and everything seems ok :+1:

**Review by PierreRambaud — DISMISSED** [review]

File: controllers/front/OrderConfirmationController.php (hunk 21 above)
Comment (tswfi) [reply controllers/front/OrderConfirmationController.php:71]: Thanks :)

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @tswfi,

The UI test is ok :heavy_check_mark: 
[Mochawesome Report.pdf](https://github.com/PrestaShop/PrestaShop/files/5872418/Mochawesome.Report.pdf)
But I have a visual issue.
When the order is free and "Terms of service" is disabled: the button **Place Order** is displayed as disabled
image

It should be like that
image

Thank you!

**Comment by tswfi** [comment]
> But I have a visual issue.
> When the order is free and "Terms of service" is disabled: the button **Place Order** is displayed as disabled

Thanks and sorry for the late response, was out of town for a while.

I'll check the disabled state as soon as I find time for this.

**Comment by tswfi** [comment]
@khouloudbelguith I cannot replicate the button being in disabled state?

image

image

(I did merge develop to this branch before my test as there was a conflict in the pr, but it should not affect this)

This is the part of the pr that handles the button activation on init for this situation: https://github.com/PrestaShop/PrestaShop/pull/22389/files#diff-14bab49f1416e8d1a789646c231ff7add27565267f65a006119c7af22ed7fef9R43-R46

Can you confirm this or give steps how to replicate?

**Comment by PierreRambaud** [comment]
Hey @tswfi you have to avoid merge commits:
image
We really appreciate receiving only rebase :)

**Comment by tswfi** [comment]
@PierreRambaud ah, hmm.. how does one revert merge commit without force-push?

File: tests/UI/pages/FO/checkout/index.js [hunk 22]
```diff
@@ -16,6 +16,8 @@ class Checkout extends FOBasePage {
     this.termsOfServiceModalDiv = '#modal div.js-modal-content';
     this.paymentConfirmationButton = `${this.paymentStepSection} #payment-confirmation button:not([disabled])`;
     this.shippingValueSpan = '#cart-subtotal-shipping span.value';
+    this.noPaymentNeededElement = `${this.paymentStepSection} div.content > p`;
+    this.noPaymentNeededText = 'No payment needed for this order';
```
Comment (PierreRambaud) [inline tests/UI/pages/FO/checkout/index.js]: Just notice these properties are unused :thinking:

Comment (tswfi) [reply tests/UI/pages/FO/checkout/index.js]: here? https://github.com/PrestaShop/PrestaShop/pull/22389/files#diff-0803dd171bfe9089270fb1c54f9fe8270bdf90306391866b9b44b2b3409c4f9cR276-R289

Comment (PierreRambaud) [reply tests/UI/pages/FO/checkout/index.js]: Oh, my bad ^^

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 23]
```diff
@@ -0,0 +1,417 @@
...
+        'testIdentifier',
+        'completeOrder',
+        baseContext,
+      );
+
+      // and click on the confirm button should take us to the confirmationpage
+      await checkoutPage.clickAndWaitForNavigation(
+        page,
+        checkoutPage.paymentConfirmationButton,
+      );
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      await checkoutPage.orderWithoutPaymentMethod(page);
```

We avoid as much to use selectors directly in tests files (as part of the POM architecture). May i suggest to add this function in the checkout page than use it in the test.

PS: using selectors in `goToSubMenu` function is an exception, and we should work on it.

```js
  /**
   * Order when no payment is needed
   * @param page
   * @returns {Promise<void>}
   */
  async orderWithoutPaymentMethod(page) {
    // Click on terms of services checkbox if visible
    if (await this.elementVisible(page, this.conditionToApproveLabel, 500)) {
      await Promise.all([
        this.waitForVisibleSelector(page, this.paymentConfirmationButton),
        page.click(this.conditionToApproveLabel),
      ]);
    }

    // Validate the order
    await this.clickAndWaitForNavigation(page, this.paymentConfirmationButton);
  }
  ```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 24]
```diff
@@ -0,0 +1,417 @@
...
+
+        const pageTitle = await orderSettingsPage.getPageTitle(page);
+        await expect(pageTitle).to.contains(orderSettingsPage.pageTitle);
+      });
+
+      it('Should change the terms and conditions back to disabled', async () => {
+        await testContext.addContextItem(
+          this,
+          'testIdentifier',
+          'dissableTermAndConditions',
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
          'disableTermAndConditions',
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 25]
```diff
@@ -0,0 +1,417 @@
...
+          page,
+          dashboardPage.shopParametersParentLink,
+          dashboardPage.orderSettingsLink,
+        );
+
+        const pageTitle = await orderSettingsPage.getPageTitle(page);
+        await expect(pageTitle).to.contains(orderSettingsPage.pageTitle);
+      });
+
+      it('Should change the terms and conditions back to disabled', async () => {
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      it('should change the terms and conditions back to disabled', async function () {
```

This should fix the error on GA.

File: tests/UI/pages/FO/checkout/index.js [hunk 26]
```diff
@@ -16,6 +16,8 @@ class Checkout extends FOBasePage {
     this.termsOfServiceModalDiv = '#modal div.js-modal-content';
     this.paymentConfirmationButton = `${this.paymentStepSection} #payment-confirmation button:not([disabled])`;
     this.shippingValueSpan = '#cart-subtotal-shipping span.value';
+    this.noPaymentNeededElement = `${this.paymentStepSection} div.content > p`;
```
Comment (boubkerbribri) [inline tests/UI/pages/FO/checkout/index.js]:
```suggestion
    this.noPaymentNeededElement = `${this.paymentStepSection} div.content > p.cart-payment-step-not-needed-info`;
```

I found out where you can add class for that selector to look better, it's in this file `themes/classic/templates/checkout/_partials/steps/payment.tpl`, line 17.

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 27]
```diff
@@ -0,0 +1,417 @@
...
+const CartRuleFaker = require('@data/faker/cartRule');
+const CustomerFaker = require('@data/faker/customer');
+const AddressFaker = require('@data/faker/address');
+
+const percentCartRule = new CartRuleFaker({
+  name: 'discount100',
+  code: 'discount100',
+  discountType: 'Percent',
+  discountPercent: 100,
+  freeShipping: 'on',
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
  freeShipping: true,
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 28]
```diff
@@ -0,0 +1,417 @@
...
+        this,
+        'testIdentifier',
+        'checkNoPaymentNeededText',
+        baseContext,
+      );
+
+      const noPaymentNeededText = await checkoutPage.getTextContent(
+        page,
+        checkoutPage.noPaymentNeededElement,
+      );
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      const noPaymentNeededText = await checkoutPage.getNoPaymentNeededBlockContent(page);
```

Same as first comment

File: tests/UI/pages/FO/checkout/index.js [hunk 29]
```diff
@@ -118,6 +120,16 @@ class Checkout extends FOBasePage {
...
+  /**
+   * Is confirm button visible and enabled
+   * @param page
+   * @returns {Promise<boolean>}
+   */
+  isPaymentConfirmationButtonVisibleAndEnabled(page) {
+    // small side effect note, the selector is the one that checks for disabled
+    return this.elementVisible(page, this.paymentConfirmationButton, 1000);
+  }
+
```
Comment (boubkerbribri) [inline tests/UI/pages/FO/checkout/index.js:147]:
```suggestion

  /**
   * Get No payment needed block content
   * @param page
   * @returns {string}
   */
  getNoPaymentNeededBlockContent(page) {
    return this.getTextContent(page, this.noPaymentNeededElement);
  }
  
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 30]
```diff
@@ -0,0 +1,417 @@
...
+
+      await expect(noPaymentNeededText).to.contains(checkoutPage.noPaymentNeededText);
+    });
+
+    it('complete order button should be enabled', async function () {
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
    it('should check that complete order button is enabled', async function () {
```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 31]
```diff
@@ -0,0 +1,417 @@
...
+
+        await dashboardPage.goToSubMenu(
+          page,
+          dashboardPage.shopParametersParentLink,
+          dashboardPage.orderSettingsLink,
+        );
+
+        const pageTitle = await orderSettingsPage.getPageTitle(page);
+        await expect(pageTitle).to.contains(orderSettingsPage.pageTitle);
+      });
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js:397]:
```suggestion
      });

```

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 32]
```diff
@@ -0,0 +1,417 @@
...
+        const result = await orderSettingsPage.setTermsOfService(
+          page,
+          true,
+          'Terms and conditions of use',
+        );
+
+        await expect(result).to.contains(
+          orderSettingsPage.successfulUpdateMessage,
+        );
+      });
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
      it('should change the terms and conditions back to enabled', async function () {
        await testContext.addContextItem(
          this,
          'testIdentifier',
          'resetTermsAndConditionsValue',
          baseContext,
        );

        const result = await orderSettingsPage.setTermsOfService(
          page,
          true,
          'Terms and conditions of use',
        );

        await expect(result).to.contains(
          orderSettingsPage.successfulUpdateMessage,
        );
      });
```

Step identifier was missing here

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js [hunk 33]
```diff
@@ -0,0 +1,417 @@
...
+    });
+
+    describe('Change terms and conditions setting back to yes', async () => {
+      it("should go to 'Shop Parameters > Order Settings' page", async function () {
+        await testContext.addContextItem(
+          this,
+          'testIdentifier',
+          'goToOrderSettingsPage',
```
Comment (boubkerbribri) [inline tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]:
```suggestion
          'goToOrderSettingsPageToReset',
```

To avoid duplicates

**Comment by tswfi** [comment]
Just a quick note that I have not forgotten this, been a bit busy...

File: tests/UI/pages/FO/checkout/index.js (hunk 26 above)
Comment (Progi1984) [reply tests/UI/pages/FO/checkout/index.js]: Ping @tswfi : a feedback from @boubkerbribri

Comment (tswfi) [reply tests/UI/pages/FO/checkout/index.js]: yup, I'm checking the comments (and trying to get the test run again :)
Already merged the obvious typo fixes etc and rebased this branch.

File: tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js (hunk 23 above)
Comment (tswfi) [reply tests/UI/campaigns/regression/checkout/100PercentDiscount_FO.js]: Yup, makes sense. Done in 39e0147 thanks!

File: tests/UI/pages/FO/checkout/index.js (hunk 26 above)
Comment (tswfi) [reply tests/UI/pages/FO/checkout/index.js]: I did think about adding the class already way back when I made the pull request initially, but decided to try to make minimal changes.
And yes, this is the correct way to get the right element. Added the class and fixed the selector in e0756fb

File: tests/UI/pages/FO/checkout/index.js (hunk 29 above)
Comment (tswfi) [reply tests/UI/pages/FO/checkout/index.js:147]: Took a moment to figure out what you meant with this :)

done in a0712c1

@boubkerbribri thanks alot! and sorry that it took a while for me to get back to this.

**Comment by tswfi** [comment]
test cases have been refactored after great code review from @boubkerbribri 
CI is still chugging away and the failed one was "cannot download language" fail.. (why does that fail btw?)

not sure who to ping and @Progi1984 was the last to ping me so back to you :)

**Comment by Progi1984** [comment]
@tswfi I came back... and I saw your conflicting file. Could you fix it ?

**Comment by tswfi** [comment]
Hehe, this is what happens when pr's go too long to be merged :D

rebased.

**Review by NeOMakinG — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @tswfi,

It is ok :heavy_check_mark: 

**Before**
image

**After**
image

The tests are ok :heavy_check_mark: 
[Mochawesome Report_pr_22389.pdf](https://github.com/PrestaShop/PrestaShop/files/7092972/Mochawesome.Report_pr_22389.pdf)

I checked:

- Terms of service disabled: free order & not a free order
- Terms of service enabled: free order & not a free order
- I checked Free order (product free + shipping free / create a 100% discount + free shipping)
- I checked final summary disabled & enabled

Thanks!

**Comment by Progi1984** [comment]
Thanks @tswfi & @khouloudbelguith
