### PR TITLE
Fallback on language code when locale is empty

### LINKED ISSUE #12673: A problem with a new added language while he was chosen in FO
**Describe the bug**
After entered new language in BO, the user who chose this language displays an error (error 500 without disabled debug mode)

**To Reproduce**
1. Go to Localization > Language 
2. Click on add new language and fill required fields like:
 - Name : Spanish 
 - ISO code: es
 - Language code: es-ES
 - Date format: Y-m-d
 - Date format (full) : Y-m-d H:i:s
And I save form
3. I go to main site in FO
4. I change language to Spanish
5. After change language appears php stacktrace 

**Screenshots**
1. filled form
zaznaczenie_514
2. Result of change language to Spanish
zaznaczenie_515
3. Probable couse of bug - not filled locale column in table ps_lang: 
zaznaczenie_516

**Additionnal information**
PrestaShop version:1.7.6.0
PHP version: 7.1
branch: develop

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When a language is manually created, the CLDR receives an empty locale and fails. This PRs fallbacks on the language code.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | Fixes #12673
| How to test?  | Front office still works even if a home made language is used.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12803)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

File: classes/Tools.php [hunk 1]
```diff
@@ -809,7 +809,10 @@ protected static function getContextLocale(Context $context)
 
         /** @var LocaleRepository $localeRepository */
         $localeRepository = $container->get(self::SERVICE_LOCALE_REPOSITORY);
-        $locale = $localeRepository->getLocale((string) $context->language->locale);
+        $locale = !empty($context->language->locale) ?
+            $context->language->locale :
+            $context->language->language_code;
+        $locale = $localeRepository->getLocale((string) $locale);
```
Comment (PierreRambaud) [inline classes/Tools.php]: Can it be other thing than a string? why not casting in the second patch?

Comment (Quetzacoalt91) [reply classes/Tools.php]: That's a good question, I guess it was for handling a `null` value, but an empty string or `null` both used to trigger an error.

**Review by PierreRambaud — APPROVED** [review]
