### PR TITLE
Validate currency localized names

### LINKED ISSUE #22188: BO - Currencies page - An exception is diplayed when creating a currency  with invalid name
#### Describe the bug

IN the BO > International > Localization > Currencies page, when we try to add a new alternative currency with an invalid name `<>` => an exception is displayed
Try to Go to BO => NOK
Try to go to FO => NOK
The shop is totally broken

#### Steps to Reproduce

1. Go to BO > International > Localization > Currencies page
2. Click on Add new currency 
3. Select "Create an alternative currency"
4. Set an invalid currency name
4.1 for example `<> ` reproduced by me & @Robin-Fischer-PS 
4.2 for example `=test` reproduced by @Robin-Fischer-PS 
5. Click save
6. see => error 
7. Go to BO => NOK
image
8. Go to FO > NOK
https://drive.google.com/file/d/17pFLeaYg66d9XnS8sbVAgcOuU-CuEI2O/view?usp=sharing
Ps: with PS1.7.6.8 => we cannot created an alternative currency
image

**Screenshots**
https://drive.google.com/file/d/17pFLeaYg66d9XnS8sbVAgcOuU-CuEI2O/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Currency localized names validation was not done so the creation process failed midway and broke the whole shop both in BO and FO
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22188
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22191)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php [hunk 1]
```diff
@@ -496,6 +496,13 @@ private function getErrorMessages(Exception $e)
                             sprintf('"%s"', $this->trans('Exchange rate', 'Admin.International.Feature')),
                         ]
                     ),
+                CurrencyConstraintException::INVALID_NAME => $this->trans(
+                    'The %s field is not valid',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php:500]: It would be better to use the following string: "The %s field is invalid." in the same domain (Admin.Notifications.Error) Thanks!

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php:500]: I used the same wording as all other fields in this page If we need to fix this I suggest we do it in a later PR so everything is consistent and we don't delay the stable release
