### PR TITLE
Fix var not displayed in emails when mail address is in uppercase

### LINKED ISSUE #13386: Email address in uppercase
**Describe the bug**
When a customer register his/her email address in uppercase, the confirmation email doesn't work as expected.

**To Reproduce**
1. Create a new account in front office, entering your email address in uppercase (i.e. KHOULOUDBELGHITH@PRESTASHOP.COM)
2. Go to your inbox and see the confirmation email. You will see something like HELLO {FIRSTNAME} {LASTNAME}

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2

### PR DESCRIPTION
**Pull request by marionf**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Fix var not displayed in emails when mail address is in uppercase
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13386
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16550)

### CODE REVIEW

File: classes/Mail.php [hunk 1]
```diff
@@ -553,7 +553,7 @@ function ($carry, $item) {
                 true
             );
             $templateVars = array_merge($templateVars, $extraTemplateVars);
-            $swift->registerPlugin(new \Swift_Plugins_DecoratorPlugin(array($toPlugin => $templateVars)));
+            $swift->registerPlugin(new \Swift_Plugins_DecoratorPlugin(array(self::toPunycode($to) => $templateVars)));
```
Comment (PierreRambaud) [inline classes/Mail.php]:
```suggestion
            $swift->registerPlugin(new \Swift_Plugins_DecoratorPlugin(array(self::toPunycode($toPlugin) => $templateVars)));
```

File: classes/Mail.php [hunk 2]
```diff
@@ -315,10 +315,10 @@ function ($carry, $item) {
                           self::mimeEncode($addrName);
                 $message->addTo(self::toPunycode($addr), $addrName);
             }
-            $toPlugin = $to[0];
+            $toPlugin = self::toPunycode($to[0]);
```
Comment (PierreRambaud) [inline classes/Mail.php]:
```suggestion
            $toPlugin = $to[0];
```

File: classes/Mail.php [hunk 3]
```diff
@@ -315,10 +315,10 @@ function ($carry, $item) {
...
         } else {
             /* Simple recipient, one address */
-            $toPlugin = $to;
+            self::toPunycode($to);
```
Comment (PierreRambaud) [inline classes/Mail.php]:
```suggestion
            $toPlugin = $to;
```

**Comment by marionf** [comment]
@PierreRambaud Changes applied

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is OK with Order confirmation & Awaiting bank wire payment & Welcome & New order emails
image
But, when we enable the "Send confirmation email to your customers" in the contactform module.
The email received by the customer is not ok
image
It should be fixed in the module? or it can be fixed in the Core?

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith I guess it's in the module, could you please create a new issue for this ?

**Comment by khouloudbelguith** [comment]
@marionf, the issue created here: https://github.com/PrestaShop/PrestaShop/issues/16563
Your PR is OK.

Thanks!
