### PR TITLE
Do not allow to put item in cart if available quantity is 0

### LINKED ISSUE #13374: Out of stock product is still added to the cart
**Describe the bug**
Add to cart an out of stock product (order refused) return an error but the product is still added to the cart

**To Reproduce**
1. Go to a product page
2. Change quantity to zero without reloading 
3. Add the product to the cart
4. See errror in the chrome inspector

**Screenshots**
see screenshot
http://creabilis.com/tmp/addtocartbug.jpg

**Additionnal information**
PrestaShop version: 1.7.6 develop branch
PHP version: 7.0

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If available stock quantity is 0, refuse to add cart to product
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/13374
| How to test?  | See ticket, be careful about different "out of stock" behaviors (see screenshot below). Plase check with products, products with combinations and packs.

Different "out of stock" behaviors:

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15623)

### CODE REVIEW

File: classes/Product.php [hunk 1]
```diff
@@ -3695,6 +3723,7 @@ public static function getQuantity(
         Cart $cart = null,
         $idCustomization = null
     ) {
+        // @todo: check whether getAvailableQuantityInStock() can be used
         if (Pack::isPack((int) $idProduct)) {
             return Pack::getQuantity($idProduct, $idProductAttribute, $cacheIsPack, $cart, $idCustomization);
```
Comment (matks) [inline classes/Product.php]: This line is very strange 🤔 . If you check the code below, you see that `Product:: getQuantity()` behavior is
1) get the product available items in stock and 2) remove the items in the cart from it.

So if product X has stock of 10, and in your cart you already added 5 items of product X, then `Product:: getQuantity()` should return 5. Cart items are decreased.

Buuuuut ... according to line 3727, for packs we just skip step 2 😱 . @marionf do you know whether this is intentional ?

### So it seems the following scenario is currently active ⬇️ 

On my shop, I seel 10 units of my beautiful black tshirt !
Customer John Doe comes, and adds 5 units of the black tshirt in its cart => cool.
Oh ? customer John Doe then adds 6 units of the black tshirt in its cart => I tell him he cant do that, he wants to order 11 units but I only have 10.

The day after, I also sell a black hat. I have 10 units of it. So I create a pack "black tshirt + black hat" !
Customer John Doe comes (again ! I love this customer), and adds 5 units of the pack in its cart => cool.
Oh ? customer John Doe then adds 6 units of the pack in its cart => I tell him he can, go ahead man ! 😄

Comment (matks) [reply classes/Product.php]: If we find out this is another bug, then I'll be able to implement `@todo: check whether getAvailableQuantityInStock() can be used`

File: controllers/front/CartController.php [hunk 2]
```diff
@@ -578,16 +584,26 @@ protected function shouldAvailabilityErrorBeRaised($product, $qtyToCheck)
...
+        $productQuantityAvailableAfterCartItemsHaveBeenRemovedFromStock = Product::getQuantity(
             $this->id_product,
             $this->id_product_attribute,
             null,
             $this->context->cart,
             $this->customization_id
         );
 
-        return $productQuantity < 0;
+        return $productQuantityAvailableAfterCartItemsHaveBeenRemovedFromStock < 0;
```
Comment (matthieu-rolland) [inline controllers/front/CartController.php:606]: Is there a reason why you are using `<`and not `<=`here ?
(this method should return false if **$productQuantityAvailableAfterCartItemsHaveBeenRemovedFromStock** = 0 ?)

Comment (matthieu-rolland) [reply controllers/front/CartController.php:606]: answered ! thanks

**Review by matthieu-rolland — DISMISSED** [review]
lgtm !

**Comment by Robin-Fischer-PS** [comment]
@matks : The product is no longer added to cart, but the message still says "Product successfully added to your shopping cart" (you can see the test in video).
https://drive.google.com/file/d/1BfYu_pqv10wDDj69BM1igy3fDxWVvLq0/view

**Comment by matks** [comment]
@Robin-Fischer-PS Hi, you're right, but the good news is that this bug is already fixed.

The bug actually happens because of a bad behavior in module Shopping Cart (https://github.com/PrestaShop/ps_shoppingcart). This has been **fixed but not yet released**.

If you wish to confirm the module indeed fixes the issue, we can do 2 things:
1) release the latest version of the module, however there is 1 mandatory PR waiting https://github.com/PrestaShop/ps_shoppingcart/pull/43 so ideally we would like to wait for this PR to be completed before releasing (else, we'll need 2 releases)
2) you can test with the latest version of the module, see below

## How to test this PR with the `develop` version of module Shopping Cart ?

1) Checkout the PR as you usually do
2) Go in modules folder `cd modules`
3) Remove old shopping cart module `rm -rf ps_shoppingcart`
4) Git clone the repository there `git clone git@github.com:PrestaShop/ps_shoppingcart.git`
5) Go into module folder, and checkout `dev` branch: `cd ps_shoppingcart` then `git checkout dev`

Be careful: this module adds javascript into Product page on FO. This JS will be put in cache by your browser for sure. So you need to make sure your browser cache is cleared and you use the updated version of the cart, not the previous one.

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matks ! I tested the PR with your 2nd proposition (with the latest version of the shopping cart module), it works fine !

Thanks for the detailed walktrough :smile:

**Comment by matks** [comment]
Thank you @Robin-Fischer-PS and reviewers ❤️
