### PR TITLE
Fix TinyMCE max length computing in BO

### LINKED ISSUE #24131: BO - Products page - Summary & Description - the line break is calculated for allowed characters
#### Describe the bug

In the BO > Catalog > Products page > in the summary & the description block the line break is calculated for allowed characters

#### Expected behavior 

The error alert should be displayed with the error message at the bottom of the field. The product can't be saved

Capture d’écran 2021-06-02 à 18 45 29

#### Steps to Reproduce

1. Go to BO -> Products page -> New product page
2. In the Summary & Description  -> set a paragraph with multiple line break 
3. Characters **>** allowed characters (=800)
4. Save => a green alert is displayed => NOK: we should have This value is too long. It should have 800 characters or less. Or The line break should not be calculated as in PS1773

**Screenshots**
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The max length for tinymce was not correctly computed and not synced with the server validator The max length is only about the text itself not the whole HTML content This PR fixes the way the length was computed in tinymce and adds minor improvement on the server side
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #24131
| How to test?      | See issue, but mainly edit description or summary The displayed max length must be consistent with the error returned from the server-side (HTML content and multiple break lines shouldn't be computed)
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25038)

## Breaking Change

`TinyMceMaxLengthValidator` is now a service that needs the translator service as a dependency. Although it should change nothing for end-users or developers since the validator is automatically created by the framework anyway.

### CODE REVIEW

File: src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php [hunk 1]
```diff
@@ -40,8 +44,9 @@ public function validate($value, Constraint $constraint)
             "\n\r",
         ];
         $str = str_replace($replaceArray, [''], strip_tags($value));
+        $length = iconv_strlen($str);
```
Comment (kpodemski) [inline src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php:68]: @jolelievre just curious, why not `mb_strlen`? is `iconv_strlen` works correctly if we decide to use emojis or some special characters?

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php:68]: Could you add Unit tests, please ?

File: src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php [hunk 2]
```diff
@@ -184,6 +184,11 @@ public function __construct(
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
         $is_stock_management = $this->configuration->get('PS_STOCK_MANAGEMENT');
+        $shortDescriptionLimit = (int) $this->configuration->get('PS_PRODUCT_SHORT_DESC_LIMIT');
+        if ($shortDescriptionLimit <= 0) {
+            $shortDescriptionLimit = 800;
```
Comment (sowbiba) [inline src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php]: can we have this value in a constant ?

File: src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php:68]: @kpodemski I have no idea why `iconv_strlen` was used ^^ It was used before I touched this file and I didn't change it 🤷‍♂️

@Progi1984 this validator already existed for a long time and had no unit tests, so this PR's scope shouldn't be to add them (you didn't add some when you modified it for PHPStan right?) But I'm not gonna lose time arguing and will add them to make you happy regardless ^^

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php:68]: I'm sorry @jolelievre. You add new behavior in code. It's why we add tests.

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php:68]: I didn't add any new behaviour but anyway..

**Review by Progi1984 — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]
Thanks @jolelievre

**Review by kpodemski — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

There is an issue following these steps:
1. Got o BO > Catalog > Products page
2. Add a new product
3. In the summary section set this text
```php
testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest

testtesttesttesttesttesttesttesttest
```
image

The number of characters = 792 < 800
4. Click on save
5. See error 
image

Also, the multiple break lines are computed.
I attached a screen record
https://www.awesomescreenshot.com/video/4232553?key=9310336630969a8f2d5ef7c79e3e259f

Thanks to check and feedback.

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php [hunk 3]
```diff
@@ -26,24 +26,50 @@
...
+ */
 class TinyMceMaxLengthValidator extends ConstraintValidator
 {
+    /** @var TranslatorInterface */
+    private $translator;
+
+    /**
+     * @param TranslatorInterface $translator
+     */
+    public function __construct(TranslatorInterface $translator)
```
Comment (Progi1984) [inline src/PrestaShopBundle/Form/Validator/Constraints/TinyMceMaxLengthValidator.php:50]: BC Break :) Could you document the new parameter, please ?

**Review by Progi1984 — COMMENTED** [review]
A last comment and it's ok ;)

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1gOZ23s02ol4ajnACNuWQoY2DzzfrezGD/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
## WAIT FOR 1780 RELEASE

**Comment by matks** [comment]
@Progi1984 QA has defined the scope of changes they want to embed inside 1.7.8.0 RC1 build 2. This PR is inside the list.

Thank you @jolelievre
