### PR TITLE
Fix listing classes when using facetedsearch

### LINKED ISSUE #26820: Category listing is using the wrong template when filtering with facetedsearch on Classic
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you change `col-6 col-xl-4` into `test` for example on line 60 of `template/catalog/listing/product-list.tpl`

At the first load : 
image

This is fine, you removed the columns, but if you filter by clicking on anything (color for example) in facetedsearch, it uses another template: 

image

### Expected behavior

Facetedsearch should use the same classes on product listing, but it can't be fixed by changing the template it uses because facetedsearch is designed to be used on any row/cols so the layout shouldn't break on any way you use it!

As discussed with @PierreRambaud the best solution would be to replace the classes on product element by the previous one in the JS event

### Steps to reproduce

Already described upper

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

facetedsearch

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | We need to keep the same classes as the initial list after updating the product list, currently the facetedsearch module uses another template and it should be agnostic on this point because it can be used differently than on category pages and more
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26820.
| How to test?      | Check issue, same way but without the bug!
| Possible impacts? | Category FO listing

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26823)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

File: themes/classic/_dev/js/listing.js [hunk 1]
```diff
@@ -230,7 +230,16 @@ function updateProductListDOM(data) {
   $(prestashop.themeSelectors.listing.listTop).replaceWith(
     data.rendered_products_top,
   );
-  $(prestashop.themeSelectors.listing.list).replaceWith(data.rendered_products);
+
+  const renderedProducts = $(data.rendered_products);
+  const productSelectors = $(prestashop.themeSelectors.listing.product, renderedProducts);
+
+  if (productSelectors.length > 0) {
+    productSelectors.removeClass().addClass($(prestashop.themeSelectors.listing.product).first().attr('class'));
```
Comment (Progi1984) [inline themes/classic/_dev/js/listing.js:238]:
```suggestion
    productSelectors.removeClass().addClass($(prestashop.themeSelectors.listing.product).first().attr('class'));
```

Why `removeClass` has no parameters ?

**Review by Progi1984 — COMMENTED** [review]
@NeOMakinG has no feedback

File: themes/classic/_dev/js/listing.js (hunk 1 above)
Comment (NeOMakinG) [reply themes/classic/_dev/js/listing.js:238]: Used to remove all class from a jQuery element

**Review by Progi1984 — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @NeOMakinG 

I have tested this PR. The issue is well fixed.
I verified when changing `col-xs-6 col-xl-4 `of `product-class `with different types of grid.
See screen-record below : 
PS178x : 
https://watch.screencastify.com/v/6USEUuuyilggewVkRXnx

When resizing screen : 
https://watch.screencastify.com/v/uoTcYuVbslPiMVlFtg9S

In responsive : 
image
 
LGTM, QA :heavy_check_mark: 

Thanks,
