### PR TITLE
Fix supplier / product v1 association

### LINKED ISSUE #29006: Unable to save a single supplier for a product with combination
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you try to save a single supplier associated for the product with combinations, an error will be displayed.

https://user-images.githubusercontent.com/90208051/177954182-699fbb59-7e92-414a-b6ef-f79da63563bb.mp4

### Expected behavior

It should be saved without errors 

### Steps to reproduce

1. Select product with combinations in BO
2. Open "Options" tab
3. Select all the suppliers and save
4. Unselect all suppliers except the default one
5. Save
6. See error: Enable to update settings.  

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | When removing some supplier associated to a product v1, we encounter an error when saving.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29006
| Related PRs       | #26609
| How to test?      | Cf. #29006
| Possible impacts? | This fix may let some consistency troubles across product v1 and product v2.

> :point_up:  Please notice that this fix assumes the v1 controller is legacy code that should be removed. I simply re-implemented old ObjectModel `ProductSupplier::delete` behavior that as been removed for product v2 purpose.

### CODE REVIEW

**Comment by MeKeyCool** [comment]
@zuk3975 , could you comment this fix please ? I think you understand better than me how it should work ^^'

:pray:

**Comment by zuk3975** [comment]
> @zuk3975 , could you comment this fix please ? I think you understand better than me how it should work ^^'
> 
> pray

hmm let me see

**Comment by zuk3975** [comment]
Actually I found much easier fix. If you debug - the issue comes from Product form (old one) constraint on product_price (actually the price field of combination supplier form).
How it works - when you uncheck one of supplier, then the related combination supplier form row is hidden, but during submit the **hidden field is still sent to the request and its price value is NULL, therefore product_price NotBlank constraint is violated and you get an error**.
The easy fix is to add `default_empty_data' => 0.0` to `src/PrestaShopBundle/Form/Admin/Product/ProductSupplierCombination.php` and it seems to work just fine. (haven't checked any other posible impacts, but I don't think there should be too many of them).
Screenshot from 2022-07-27 18-11-32
Other approach would be to not submit hidden combination supplier rows at all, but that would require digging into old crappy js, so I think the first solution is acceptable :man_shrugging: ) wdyt?

**Comment by MeKeyCool** [comment]
> Actually I found much easier fix. If you debug - the issue comes from Product form (old one) constraint on product_price (actually the price field of combination supplier form). How it works - when you uncheck one of supplier, then the related combination supplier form row is hidden, but during submit the **hidden field is still sent to the request and its price value is NULL, therefore product_price NotBlank constraint is violated and you get an error**. The easy fix is to add `default_empty_data' => 0.0` to `src/PrestaShopBundle/Form/Admin/Product/ProductSupplierCombination.php` and it seems to work just fine. (haven't checked any other posible impacts, but I don't think there should be too many of them). Screenshot from 2022-07-27 18-11-32 Other approach would be to not submit hidden combination supplier rows at all, but that would require digging into old crappy js, so I think the first solution is acceptable man_shrugging ) wdyt?

I think I was absolutely not able to understand that deep this full behavior and your explanations sounds perfectly rights ^^
I'll remove my fix and add yours :D

Thanks for your help ! ^^

**Comment by MeKeyCool** [comment]
Just to be sure, @zuk3975 , it implies that we have "fake" association between product and suppliers that stay in database but are not interpreted. Do you agree this is normal state in Prestashop ? :thinking:

**Comment by zuk3975** [comment]
apparently I was wrong. Even though form error would be fixed, the ProductSuppliers wouldn't have been deleted, so my solution isn't actually fully working.
We discussed in slack with @MeKeyCool and he reminded me the behavior. So His code simply moves the deleted part from ProductSupplier::delete() (it was deleted in #26609) into AdminProductsController::processSuppliers part this way keeping the same behavior for product v1 and not changing anything related to product v2. :heavy_check_mark:

File: controllers/admin/AdminProductsController.php [hunk 1]
```diff
@@ -2446,7 +2446,21 @@ public function processSuppliers($id_product = null)
             foreach ($associated_suppliers as $key => $associated_supplier) {
                 /** @var ProductSupplier $associated_supplier */
                 if (!in_array($associated_supplier->id_supplier, $suppliers_to_associate)) {
-                    $associated_supplier->delete();
+                    // This specific delete is made to ensure product v1/v2 consistency for product / supplier association
+                    // Cf. https://github.com/PrestaShop/PrestaShop/pull/26609
+
+                    $res = $associated_supplier->delete();
+
```
Comment (zuk3975) [inline controllers/admin/AdminProductsController.php:2454]: Add a comment like "This code block was moved from ProductSupplier::delete() to avoid side effects in product page v2 while keeping same behavior in product page v1"

**Review by zuk3975 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @MeKeyCool,

Thank you for this PR.
Tested on 8.0.x branch with PHP 7.3.

Suppliers could be saved on combinations product and always with other product type  too (virtual / standard / pack):


https://user-images.githubusercontent.com/2854834/181791285-073c3ff6-6917-444a-9331-b15a2960db53.mp4



QA approved ✅ 

Thanks

**Comment by matks** [comment]
Thank you @MeKeyCool
