### PR TITLE
Handle case where product location is a boolean

### LINKED ISSUE #22460: Multistore - BO - Add new Order page - Cannot search a product when a shop from different Group is selected
#### Describe the bug

In the BO > Orders > Add new order page > when a shop from a different group is selected, the search for Product is blocked
>I found this issue while testing this PR: https://github.com/PrestaShop/PrestaShop/pull/22020

#### Steps to Reproduce

1. Enable Multistore context
2. Create a new Group `Group2` (all options are enabled)
3. Create a new shop `shop2` associated with this Group
4. Go to BO > Orders > Add new Order page (shop2 is selected
5. Choose a customer
6. Search a product
7. See error in the console

**Screenshots**

177x, 1770: https://drive.google.com/file/d/1ub21MgbjosjH1AYxl2SRdQdrARn5qbye/view?usp=sharing
1769 => ok : https://drive.google.com/file/d/1-O6QaUr1q3SwuCpqbMsoyr8qlgjry5Hc/view

#### Additional information

* PrestaShop version: 177x, 1770
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | In multistore context, prodcut location can return a boolean. That was not handle when searching for a product when creating an order in the BO. This PR fixes it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22460
| How to test?      | See #22460
| Possible impacts? | Nothing more than the original ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22542)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

File: src/Adapter/Product/QueryHandler/SearchProductsHandler.php [hunk 1]
```diff
@@ -197,7 +197,7 @@ private function createFoundProductFromLegacy(
             $this->tools->round($priceTaxExcluded, $computingPrecision),
             $product->getTaxesRate($address),
             Product::getQuantity($product->id),
-            $product->location,
+            $product->location ?: '',
```
Comment (jolelievre) [inline src/Adapter/Product/QueryHandler/SearchProductsHandler.php]: I think this should be fixed in `Product::loadStockData` instead It will fix more use cases

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1IntDdKJd8gJs7jiRJpcKGqVd4W4YZIBz/view?usp=sharing

Thanks!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
## DONT MERGE BEFORE RELEASE 1.7.7.1

**Review by Progi1984 — APPROVED** [review]
