### PR TITLE
Fix not null voucher with free shipping producing php error

### LINKED ISSUE #13543: Cart rule with free shipping AND % or amount reduction not applied in FO
**Describe the bug**
For my case, when I add a new promo code on cart rule (individual or to everyone), in Front-Office adding a correct promo code not working.
Detected by the E2E automation tests.

**To Reproduce**
1. Add a new promo code
2. Don’t forget to activate free shipping (toggle button) before saving it
3. Go to Front-Office and add the promo code
4. Nothing happen, if you reload the page you have an error page (500) 

**Screenshots**
Please refer to the video attached https://drive.google.com/file/d/16dyBqxzC5SDAwNAVa6DAKyK0svf6Rt7j/view

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: 7

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix regression introduced in 1.7.6.x on vouchers: not null (percent or amount) voucher with free shipping was producing php error (maximum nested function)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | fixes #13543 
| How to test?  | On BO create voucher with not null amount AND free shipping. Apply it on FO. It should not result in php error when refreshing page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13617)

### CODE REVIEW

**Comment by tomlev** [comment]
not the best fix, but with a new behat test to  cover this issue...

File: src/Core/Cart/Calculator.php [hunk 1]
```diff
@@ -263,13 +263,15 @@ public function calculateRows()
...
+     * @param bool $withFreeShipping used to calculate free shipping discount (avoid loop on shipping calculation)
      */
-    public function calculateCartRules()
+    public function calculateCartRules($withFreeShipping = true)
     {
         $this->cartRuleCalculator->setCartRules($this->cartRules)
             ->setCartRows($this->cartRows)
             ->setCalculator($this)
-            ->applyCartRules();
+            ->applyCartRules($withFreeShipping);
```
Comment (Quetzacoalt91) [inline src/Core/Cart/Calculator.php]: You say you're not confident in the way you improved this. What about having properties for the free shipping?

```suggestion
            ->setFreeShipping($withFreeShipping);
            ->applyCartRules();
```

Comment (tomlev) [reply src/Core/Cart/Calculator.php]: good idea ;)

File: src/Core/Cart/Calculator.php [hunk 2]
```diff
@@ -289,4 +292,12 @@ public function getCartRulesData()
...
         return $this->cartRuleCalculator->getCartRulesData();
     }
+
+    /**
+     * @return int
+     */
+    public function getCarrierId()
+    {
+        return $this->id_carrier;
+    }
```
Comment (Quetzacoalt91) [inline src/Core/Cart/Calculator.php]: Why is this method used for?

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php [hunk 3]
```diff
@@ -87,6 +87,14 @@ public function thereIsACartRuleWithNameAndPercentDiscountOf50AndPriorityOfAndQu
         $this->createCartRule($cartRuleName, $percent, 0, $priority, $cartRuleQuantity, $cartRuleQuantityPerUser);
     }
 
+    /**
+     * @Given /^there is a cart rule named "(.+)" that applies no discount with priority (\d+), quantity of (.*) and quantity per user (.*)$/
```
Comment (PierreRambaud) [inline tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php]: Quantity is integer no?
```suggestion
     * @Given /^there is a cart rule named "(.+)" that applies no discount with priority (\d+), quantity of (\d+) and quantity per user (\d+)$/
```

File: tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/free_shipping.feature [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+
+  Scenario: One product in cart, one cartRule offering only free shipping
+    Given I have an empty default cart
+    Given shop configuration for "PS_CART_RULE_FEATURE_ACTIVE" is set to 1
+    Given there is a product in the catalog named "product1" with a price of 19.812 and 1000 items in stock
+    Given there is a cart rule named "cartrule4" that applies no discount with priority 4, quantity of 1000 and quantity per user 1000
+    Given cart rule "cartrule4" offers free shipping
+    Given cart rule "cartrule4" has a discount code "foo4"
+    When I add 1 items of product "product1" in my cart
+    When I use the discount "cartrule4"
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/free_shipping.feature:14]: Shouldn't it be `I use the discount code "foo4"`

Comment (tomlev) [reply tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/CartRule/free_shipping.feature:14]: it could be both, here the code doesn't matter, the only thing that matter is that the voucher `has` a code (not applied anytime)

**Comment by jolelievre** [comment]
@Quetzacoalt91 seems better this way to me
Although it's not clean this will have to be refacto in the coming iterations on 
price computing
If you're ok I can approve

**Comment by Quetzacoalt91** [comment]
Yeah I approved the changes 30 minutes ago. Not seeing the freeShipping as a parameter is better.

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @tomlev
