### PR TITLE
Redirect to dashboard when employee default page is unauthorized

### LINKED ISSUE #19075: BO - Bad redirection when trying to access Orders when unauthorized
#### Describe the bug

When an employee cannot access the orders pages, and when his default page is "orders", but try to access it via URL, there is an infinite redirection to orders.

#### Expected behavior

Redirection should target any page this user has access to.

#### Steps to Reproduce

1. With Admin, go to BO > Advanced Parameters > Team > Add new Employee
2. Create the employee, with "Orders" as Default Page, and Logistician as Profile
3. Go to Permissions tab, change permissions of Logistician, remove all permissions in "Orders"
4. Disconnect, and connect with the newly created employee
5. Since his default page is Orders, and his profile has no access to this page, there is an infinite redirection.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Loop redirections when the employee default page is unauthorized for his profile. We check if the default page is authorized first, if not redirect to dashboard.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19075
| How to test?  | 1 - With Admin, go to BO > Advanced Parameters > Team > Add new Employee<br>2 - Create the employee, with "Orders" as Default Page, and Logistician as Profile<br>3 - Go to Permissions tab, change permissions of Logistician, remove all permissions in "Orders"<br>4 - Disconnect, and connect with the newly created employee<br>5 - Since his default page is Orders, and his profile has no access to this page, the employee will be redirected to his dashboard.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19103)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: classes/Dispatcher.php [hunk 1]
```diff
@@ -291,7 +291,10 @@ private function getDefaultController($frontControllerType, Employee $employee =
                 if (null !== $employee) {
                     $tabClassName = $employee->getDefaultTabClassName();
                     if (null !== $tabClassName) {
-                        $defaultController = $tabClassName;
+                        $tabProfileAccess = Profile::getProfileAccess($employee->id_profile, Tab::getIdFromClassName($tabClassName));
+                        if (is_array($tabProfileAccess) && isset($tabProfileAccess['view']) && $tabProfileAccess['view'] == 1) {
```
Comment (eternoendless) [inline classes/Dispatcher.php]: `$tabProfileAccess['view'] == 1`

Consider using strict comparison

Comment (sowbiba) [reply classes/Dispatcher.php]: I used the same comparison as https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L562

And the values are string
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Profile.php#L149

I will use strict comparison with `'1'`

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @sowbiba !

**Comment by Progi1984** [comment]
Thanks @sowbiba
