### PR TITLE
Fixed preview of product in frontoffice

### LINKED ISSUE #25891: FO - Product disabled - an exception is displayed when changing combination or increasing / decreasing a quantity
#### Describe the bug

A product disabled, in the FO when increasing decreasing the quantity => an exception is dislayed
A product with combinations is disabled.
In the FO when we try to change the combinations => an exception is displayed

#### Steps to Reproduce

- [ ] Issue 1
1. Go to BO > Catalog > Products page and edit a product with combinations
2. Disable it
3. Click on Preview
4. FO page opens with a message in the header This product is not visible to your customers.
5. Change a combinations
6. See error 
image

- [ ] Issue 2
1. Go to BO > Catalog > Products page and edit a product (any type of a product)
2. Disable it
3. Click on Preview
4. FO page opens with a message in the header This product is not visible to your customers.
5. Increase / Decrease the quantity
6. See error 
image

In the PS1777 => ok
image
image

#### Additional information

* PrestaShop version: 1780rc1build4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed preview of product in frontoffice
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25891
| How to test?      | Cf. #25891 & #17522

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25903)

### CODE REVIEW

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -197,7 +197,7 @@ public function init()
                 $this->errors[] = $this->trans('You do not have access to this product.', [], 'Shop.Notifications.Error');
                 $this->setTemplate('errors/forbidden');
             } else {
-                if (!$isAssociatedToProduct && $isPreview) {
+                if (!$isAssociatedToProduct && $isPreview && !$this->ajax) {
```
Comment (atomiix) [inline controllers/front/ProductController.php:200]: What if it is ajax then?

Comment (Progi1984) [reply controllers/front/ProductController.php:200]: If it's in ajax, we bypass the error because the `adtoken` for preview is not passed to ajax requests.

**Review by sowbiba — DISMISSED** [review]

File: controllers/front/ProductController.php (hunk 1 above)
Comment (sowbiba) [reply controllers/front/ProductController.php:200]: It would be more understandable for me if you put the check

```
Tools::getValue('adtoken') == Tools::getAdminToken(
                    'AdminProducts'
                    . (int) Tab::getIdFromClassName('AdminProducts')
                    . (int) Tools::getValue('id_employee')
                )
```
in a variable and set it to true if isAjax

`+` a comment to explain

WDYT ?

Comment (Progi1984) [reply controllers/front/ProductController.php:200]: @sowbiba No because `$isAssociatedToProduct` is used in other places of the code with the not same condition.

**Review by PierreRambaud — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I checked a simple product => ok
If I change the quantity:
1. specific prices well applied
2. Label when in stock & out of stock well changed
3. I can add a comment
4. I can view the images

I checked product with combinations
If I change the quantity:
1. specific prices well applied
2. Label when in stock & out of stock well changed
3. I can view images

If I change the combinations:

1. combinations well changed
2. minimum quantity well changed
3. Image well changed
4. Product details well changed

I checked with `Friendly URL` enabled & disabled
I checked with id_employee=1 and id_employee=2

https://watch.screencastify.com/v/TJcQyAEpAauYpDIuAFe1

I checked https://github.com/PrestaShop/PrestaShop/pull/17522 => ok

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
