### PR TITLE
Product combination price edit : Use blur instead of onkeyup to avoid price flip

### LINKED ISSUE #25718: BO combination price editor problem - Number comma formatter
#### Describe the bug

https://user-images.githubusercontent.com/70293774/131098475-aa0a9a48-f8f8-4d3c-ab09-e007d2807b9e.MP4

Hello everyone, I am writing this post to report a problem I had recently following an update of prestashop from version 1.7.7.6 to 1.7.7.7.
In the back office, if I try to edit a product that contains combinations, as soon as I enter the single combination editor, the price entry seems to go crazy. It is useless to try to cancel the price. I can only enter the price through massive actions in the combination summary. The problem seems to arise especially with already existing combinations. I am attaching a video showing the problem.

#### Steps to Reproduce

1. Go to BO > Catalog > Products > Edit a product with combinations
2. In the Combinations Tab > Edit a combination
3. In the field `Impact on the price (tax incl.)` > try to add a decimal with a comma or point for example `1.2`, `1,2`, `1N000`
4. See error => the price is converted

Seems related to this PR: https://github.com/PrestaShop/PrestaShop/pull/24339
Has anyone had the same problem as me? Is there a solution?
Prestashop 1.7.7.7
PHP 7.3

Thanks

### LINKED ISSUE #25753: BO - Product combination price (the impact price -5 is converted)
#### Describe the bug

In the BO > Catalog > Products > Edit a product with combinations
When we try to edit a combination and set the impact price Tax included = -5 it will be converted to `-5.000002`

#### Steps to Reproduce

1. Go to BO > Catalog > Products > Edit a product with combinations
2. In the Combinations Tab > Edit a combination
3. In the field Impact on the price (tax incl.) > try to copy-paste this number `-5` (because of this [bug](https://github.com/PrestaShop/PrestaShop/issues/25718))
4. See error: it will be converted to `-5.000002`
image

In the PS1775 => ok 
image

#### Additional information

* PrestaShop version: 1776, 1777, 177x (with and without this [PR](https://github.com/PrestaShop/PrestaShop/pull/25749)
* PHP version: 7.1, 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Use blur to wait until user ends typing before round the price
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25718 & #25753
| How to test?      | See #25718 & #25753
| Possible impacts? | Test with ecotax

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25749)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @sowbiba 

Seems good to me, I would just like to have the approval from @PierreRambaud since he worked on the number formatted part

**Comment by PierreRambaud** [comment]
I approve but I don't know if this trigger is still needed:
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js#L1969$

**Comment by sowbiba** [comment]
> I approve but I don't know if this trigger is still needed:
> https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js#L1969$

$(document).on('blur', '.combination-form .attribute_priceTI', function() { ==>  TI edit
```
TI edit => Impact on TE
                           => get TI input value
                              compute TE value
                              update TE input
                              Impact on TI
                                  => compute TI value (depending on TE)
                                     update TI input
```                                      
this is weird to me, we assume to (maybe) override the value edited

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 1]
```diff
@@ -1991,7 +1976,7 @@ var priceCalculation = (function() {
       var impactPriceTI = this.getImpactTIInputValue(obj);
       var impactPriceTE = this.computePriceTaxExcluded(impactPriceTI);
 
-      this.updateImpactTEInput(impactPriceTE, obj);
+      this.getImpactTEInput(obj).val(impactPriceTE);
```
Comment (jolelievre) [inline admin-dev/themes/default/js/bundle/product/form.js]: Careful, you are changing the behaviour here, as the removed `updateImpactTEInput` function used to update both fields tax excluded and included (and recompute tax included at the same time)

Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js]: The whole behaviour is quite touchy and prone to many errors To avoid any risk I would have kept the `update*` methods, and you can simply remove the `change` trigger code I guess

Also you need to be careful because not only the combination form is updated, the combination list also needs to be updated and it's not handled in this file. The list update is handled here https://github.com/PrestaShop/PrestaShop/blob/339f1c8fad3f960cf381ed48c72192ea22c67081/admin-dev/themes/default/js/bundle/product/product-combinations.js#L153

It relies on the `change` event so it might break this feature, if you only wanted to remove the `change` trigger for "clean code" the DON'T 😅. Because this whole code is a mess and a slight change can break many unexpected things

As long as your bug is fixed you should try to minimize the modifications as much as possible. This code is bound to be removed once the product page is redone in v8 anyway, so now is not the time to do overkill changes unless you plan on releasing a 1.7.9 next week.. ^^

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @sowbiba

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — COMMENTED** [review]
Thank you @atomiix for fixing my mistakes ^^

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba, @atomiix,

I checked with @Robin-Fischer-PS 
It is ok :heavy_check_mark: 

About the rounding price, we have old issues:
https://github.com/PrestaShop/PrestaShop/issues/9855
https://github.com/PrestaShop/PrestaShop/issues/12078

But before PS1.7.7.5, we need to **refresh** the page to show the error and now the rounding bug is displayed when we click outside because of `blur`  (The event is on `blur`. As soon as you leave the field, the calculation is done)

And about the ecotax issue, we have old issues
https://github.com/PrestaShop/PrestaShop/issues/9972
https://github.com/PrestaShop/PrestaShop/issues/24373

So it seems that the ecotax is not working since before.

Thanks!

**Comment by PierreRambaud** [comment]
Thank you @sowbiba and @atomiix
