### PR TITLE
Handle via javascript that the two fields for impact are synced, mean…

### LINKED ISSUE #33580: Bulk edit of prices not working for product variants
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a product with combinations, 
I would like to bulk-edit prices for a number of the variations.
PrestaShop (8.1.0) tries to perform the desired action,
but nothing actually changes.

See screen-recording for visual explanation:

chrome_KG3MIWmXlP

### Expected behavior

I would expect the functionality in PrestaShop to actually work.

### Steps to reproduce

1: Go to (or create) a product with combinations.
2: Select some of the combinations (i.e. every product with size = S)
3: Make a bulk-edit of the prices.
Note that the prices arent actually changing. See screen-recording above for visual explanation.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Handle via javascript that the two fields for impact are synced, meaning they are both enabled/disabled at the same time
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Try to modify the impact on price on a combination via bulk action, the two inputs for price tax excluded/included should be synced so no more error when only price tax included is provided
| UI Tests          | ~
| Fixed issue or discussion?     | Fixes #33580
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by matks — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/product/combination/bulk/index.ts [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+import ImageSelector from '@pages/product/combination/form/image-selector';
+import QuantityModeSwitcher from '@pages/product/combination/quantity-mode-switcher';
+import CombinationBulkMap from '@pages/product/combination/bulk/combination-bulk-map';
+import FormFieldToggler from '@components/form/form-field-toggler';
+
+// @ts-ignore
```
Comment (M0rgan01) [inline admin-dev/themes/new-theme/js/pages/product/combination/bulk/index.ts]: I wonder if we can take this off. The @types/jquery library gives us the type

**Review by M0rgan01 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @jolelievre 

The issue is well fixed and the bulk edit of prices is well working for product variants.

[Untitled_ Sep 28, 2023 9_03 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/7d7d3aeb-4caf-4be7-a526-54f5a1dcf49e)


Automated tests are OK :heavy_check_mark: 
https://github.com/MhiriFaten/testing_pr/actions/runs/6335953118

Thank you.
