### PR TITLE
Fix `ObjectModel::add()` force_id usage for multilang model

### LINKED ISSUE #25432: force_id not working with lang table in Object Model
#### Describe the bug

In `objectModel`, `force_id` is useful if you wants to set your id, by example if you have a primary as `id_product` in an extra table.
When you call `add()` method, it works well for base table but not for `_lang` table.

#### Expected behavior
The provided id should be used correctly in `_lang` tables

#### Steps to Reproduce

1. Create an object model class : `MyClass`
```
'table' => 'mytable',
'primary' => 'id_product',
'multilang' => true,
```
2. Create the corresponding SQL tables `mytable` and `mytable_lang`.
Make sure `id_product` is NOT an autoincrement.

2. Add a row with the forced id:
```
$myRow = new MyClass(124);
$myRow->id = 124;
$myRow->force_id = true;
$myRow->add();
```

3. Go to database
4. See error : the inserted row in `mytable` has `id_product` set to 0 instead of 124

#### Additional information

* PrestaShop version: all 1.7
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In objectModel, force_id is useful if you wants to set your id, by example if you have a primary as id_product in an extra table. When you call add() method, it works well for base table but not for _lang table.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/25432
| How to test?      | see Issue
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25433)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Comment by jf-viguier** [comment]
Thanks @atomiix

**Review by matks — DISMISSED** [review]
Hello @jf-viguier thank you for the PR.

If we look at the code below, I think there might also be an issue with multishop fields, and this PR maybe also fix it.

It's a bit weird that `Db::getInstance()->Insert_ID();` does not contain the right value 🤔  theoretically it should be the last inserted row ID https://www.php.net/manual/en/pdo.lastinsertid.php

Mmm ...

Ah, the doc mentions a useful statement:

> MySQL:
"With no argument, LAST_INSERT_ID() returns a BIGINT UNSIGNED (64-bit) value representing the first automatically generated value successfully inserted for an AUTO_INCREMENT column as a result of the most recently executed INSERT statement."

So it would actually make sense.

That means that any code in PrestaShop that rely on `Db::getInstance()->Insert_ID();` works correctly as long as the last ID is the last auto-increment ID.

File: classes/ObjectModel.php [hunk 1]
```diff
@@ -579,8 +579,10 @@ public function add($auto_date = true, $null_values = false)
             return false;
         }
 
-        // Get object id in database
-        $this->id = Db::getInstance()->Insert_ID();
+        // Get object id in database if force_id is not true
+        if (!$this->force_id || empty($this->id)) {
```
Comment (ytilotti) [inline classes/ObjectModel.php]:
```suggestion
        if (empty($this->id)) {
```
The `!$this->force_id` is not necessary, it's already _cleaning_ at the start of the method with:
```
if (isset($this->id) && !$this->force_id) {
    unset($this->id);
}
```

**Comment by jf-viguier** [comment]
@matks thanks for the approve.
Yes, it should solve multi shop issues too.
Insert_ID() return 0 if the column is not in autoincrement : in my example, I want the id_product as primary key in an extra table, not in product table.

To add extra columns to product, I often been say that it's a good practice to use a separate table. With this PR it will be ok with multilang or multishop columns.
This bug should be there for long time ago, I've seen some post in the forum but no issue or pr.

File: classes/ObjectModel.php (hunk 1 above)
Comment (jf-viguier) [reply classes/ObjectModel.php]: @ytilotti indeed yes.
@matks @atomiix what do you think ?
!$this->force_id can be more clear to read and usefull if the first if is deleted, Y don't know.

Comment (matks) [reply classes/ObjectModel.php]: > !$this->force_id can be more clear to read and usefull if the first if is deleted, Y don't know.

If we have unit tests that run through this scenario, we dont have to be afraid "what if the first if is deleted?" because the tests would crash in that case 😉

**Comment by jf-viguier** [comment]
Thanks @ytilotti @matks, change done.

**Comment by jf-viguier** [comment]
@matksI guess that tests don't cover force_id = true

**Review by atomiix — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team I think this is a great candidate for `waiting-for-qa-dev`? Let us know

**Comment by jf-viguier** [comment]
thanks @kpodemski

**Comment by sarahdib** [comment]
> @PrestaShop/qa-team I think this is a great candidate for `waiting-for-qa-dev`? Let us know

@kpodemski indeed it can be tested by a dev I add the waiting for dev label :) 
Thank you

**Comment by matks** [comment]
Tested and validated

**Comment by matks** [comment]
Thank you @jf-viguier and @ytilotti
