### PR TITLE
Remove useless and buggy identifier computation

### LINKED ISSUE #15318: Notice when configure some modules
**Describe the bug**

**To Reproduce**
1. Go to module
2. Click on configure ps_emailsubscription
3. See error

**Screenshots**

image

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1

### LINKED ISSUE #15333: Getting issue on module admin controller's render list in Prestashop V1.7.6.1 with existing data
Hello,

Currently I am getting issue on my module's admin controller render list page in Prestashop V1.7.6.1 while my controller's render list has some data.
After research, I found that I am getting this issue because I am not using $this->identifier name similar to $this->table name on module's admin controller page.
For example, my table name is 'product_review' and here I am using primary key as 'id_review' So in this case, I will define $this->identifier = 'id_review' on module admin controller.

In previous prestashop version (below V1.7.6.1), I don't have any issue like this but on current prestashop V1.7.6.1, I am getting a error -
"Notice: Undefined index: id_product_review"

Check this screenshot -  https://prnt.sc/ozmiwc

In Prestashop V1.7.6.1, you are always getting entity like -   'id_' . $table_name
So have you restrict it in current version 1.7.6.1 because you didn't mention anything like this before.

1. Create a table in module i.e. table name 'product_review' and set primary key in this table as 'id_review'
2. Create a module's admin controller and set 
   $this->identifier = 'id_review'
   $this->table = 'product_review'

Now while you will add any data in your table and when you see render list of your admin controller then you will get issue like "Notice: Undefined index: id_product_review"
https://prnt.sc/ozmiwc

Here if I used my primary key as 'id_product_review' then I will get no error. So It looks like It is mandatory to set table primary key same table name.

Screenshots -

error

PrestaShop version: 1.7.6.1

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | The new `LegacyHelperLinkBuilder` (introduced in https://github.com/PrestaShop/PrestaShop/pull/14721) causes an error warning when the expected parameter was not present, besides this computation was useless as it expected the parameter to be present
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15333 and fixes #15318
| How to test?  | You can check the fix by using the product comments module or ps_emailsubscription module (known bugs, but probably other modules had troubles). You also need to check that the quick search is still valid

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15382)

### CODE REVIEW

File: src/Adapter/Routing/AdminLinkBuilder.php [hunk 1]
```diff
@@ -90,12 +90,13 @@ public function getEditLink($entity, array $parameters)
      */
     private function buildActionParameters($action, $entity, array $parameters)
     {
+        unset($parameters['current_index']);
```
Comment (PierreRambaud) [inline src/Adapter/Routing/AdminLinkBuilder.php:93]: always check if key exist before unset.

Comment (PierreRambaud) [reply src/Adapter/Routing/AdminLinkBuilder.php:93]: At least for token

**Comment by MathiasReker** [comment]
Milestone should be 1.7.6.2 instead of 1.7.6.1?

File: src/Adapter/Routing/AdminLinkBuilder.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Routing/AdminLinkBuilder.php:93]: I think `unset` doesn't care if the key is present, if it's not here it simply does nothing
But at least the code is simpler

Comment (PierreRambaud) [reply src/Adapter/Routing/AdminLinkBuilder.php:93]: Oh you're right :+1:

Comment (jolelievre) [reply src/Adapter/Routing/AdminLinkBuilder.php:93]: Well, then is it approved? ^^

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thank you @jolelievre

**Comment by Mohammed1990maroc** [comment]
It's a minor problem of PrestaShop 1.7.6.1, to fix it you need to modify the /src/Adapter/Routing/LegacyHelperLinkBuilder.php file, change the line

[$entityId => $parameters[$entityId], $viewAction => 1]
to
[$entityId => isset($parameters[$entityId])?:null, $viewAction => 1]

**Comment by jolelievre** [comment]
Hi @Mohammed1990maroc 

actually this is not even necessary (see this PR content for the fix). Since anyway this array is merged with `$parameters` there's no need to check for one of its field and merge it back again, this is redundant, useless and cause bugs, ...

This bug fix has been merged in the 1.7.6.2 version which was released yesterday 😉

**Comment by Mohammed1990maroc** [comment]
hit @jolelievre 
prestashop has fix this bug in the 1.7.6.2 ?
This version has not yet been released

**Comment by jolelievre** [comment]
Yes it's included in the 1.7.6.2 version which was released yesterday
https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.2
