### PR TITLE
Check memory_limit during installation

### LINKED ISSUE #16507: Add a check for minimum PHP memory on install
The [System requirements documentation](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/) states that the minimum recommended memory for PHP should be set to 256Mb. To my understanding, this is not enforced by the installer, putting the install process at risk of crashing.

A check on this requirement should be added to the install process.

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | PHP's config memory_limit must be checked during installation process
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16507
| How to test?  | Decrease your memory_limit to 128M to see this message<br>image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16527)

### CODE REVIEW

File: install-dev/controllers/http/process.php [hunk 1]
```diff
@@ -297,60 +297,22 @@ public function processInstallTheme()
...
-            $populate_step['subtasks'] = array();
-            $xml_loader = new XmlLoader();
-            $xml_loader->setTranslator($this->translator);
-
-            foreach ($xml_loader->getSortedEntities() as $entity) {
-                $populate_step['subtasks'][] = array('entity' => $entity);
-            }
-        }
-
-        $this->process_steps[] = $populate_step;
```
Comment (matthieu-rolland) [inline install-dev/controllers/http/process.php:320]: Are all those deletions directly related to the check of php memory limit?

Comment (matthieu-rolland) [reply install-dev/controllers/http/process.php:320]: answered 👍

**Review by matthieu-rolland — DISMISSED** [review]
lgtm !

**Review by matthieu-rolland — APPROVED** [review]
lgtm, thanx @PierreRambaud !

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @PierreRambaud !

There is a way to skip this step : When there is an install cache on the browser, a new install starts at the "Store information" step, so the memory is not verified in this case. I don't know if there is an easy way to prevent users from skipping step "System compatibility" ?

Thanks

**Comment by PierreRambaud** [comment]
@Robin-Fischer-PS If all tests are green, this step seems to be skipped, but in fact, no. If you change your memory limit and restart your apache server or your php-fpm, you can restart the installation and you'll see the warning.

**Comment by Robin-Fischer-PS** [comment]
@PierreRambaud See on this screenrecord, the even if the memory limit is not high enough, I can skip the step (I just go back on step 3 to show the memory is not OK) : 

https://drive.google.com/file/d/1LXxvvqrZBsqpyNJAVR4S1J_bbTtICe7B/view?usp=sharing

**Comment by PierreRambaud** [comment]
> @PierreRambaud See on this screenrecord, the even if the memory limit is not high enough, I can skip the step (I just go back on step 3 to show the memory is not OK) :
> 
> https://drive.google.com/file/d/1LXxvvqrZBsqpyNJAVR4S1J_bbTtICe7B/view?usp=sharing

This is a normal behaviour because of sessions :sweat_smile:

**Comment by Robin-Fischer-PS** [comment]
Thanks, so it's QA approved :P

**Comment by PierreRambaud** [comment]
Thanks me!

**Comment by Robin-Fischer-PS** [comment]
Thanks @PierreRambaud :D
