### PR TITLE
Fixed increment button when adding a product out of stock and with allow order

### LINKED ISSUE #21529: BO - Orders page - increment/decrement button doesn't work when we try to add a product out of stock < 0 (allow order
#### Describe the bug

In the BO => Orders page => New Order page => when we try to add an out of stock product with allowing order, the increment/decrement button doesn't work
In this PR: https://github.com/PrestaShop/PrestaShop/pull/20714 we just fixed when the quantity of product **=** 0
But when the quantity product **<** 0 => NOK

#### Steps to Reproduce

1. Go to BO => Catalog => Products page
2. Add a product with quantity **<** 0 with allow order selected
3. Go to BO => Orders => New Order page
4. Add the last product created
5. check the increment/decrement button
6. see error => we can't increment the product quantity

**Screenshots**

https://drive.google.com/file/d/1WS2cfkW-_EVms0IPYD5FFunCpOnc6_Tz/view?usp=sharing
image

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixed increment button when adding a product out of stock and with allow order
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21529 
| How to test?  | 0. Build assets<br>1. Go to BO => Catalog => Products page<br>2. Add a product with quantity **<** 0 with allow order selected<br>3. Go to BO => Orders => New Order page<br>4. Add the last product created<br>5. check the increment/decrement button<br>6. **BEFORE**see error => we can't increment the product quantity<br>6. **AFTER** We can increment the product quantity

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21555)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have the same issue following these steps:

1. Go to BO => Catalog => Products page
2. Add a product with quantity < 0 with deny orders 
image
3. Go to BO => Orders => New Order page
4. Add the last product created
5. check the increment/decrement button

I attached a screen record
https://drive.google.com/file/d/1wyalWnfGvFeaSB3a8qnRlyrjg6HKwx4f/view?usp=sharing

Thanks!

**Review by sowbiba — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js [hunk 1]
```diff
@@ -157,18 +157,19 @@ export default class ProductRenderer {
   /**
    * Renders available fields related to selected product
    *
-   * @param product
+   * @param {object} product
    */
   renderProductMetadata(product) {
-    this.renderStock(product.stock, product.stock === 0 && product.availableOutOfStock ? true : false);
+    this.renderStock(product.stock, product.availableOutOfStock ? true : (product.stock <= 0));
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]:
```suggestion
    this.renderStock(product.stock, product.availableOutOfStock || product.stock <= 0);
```

**Review by NeOMakinG — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found an issue following these steps:
1. Go to BO => Catalog => Products page
2. Add a product with combinations quantity < 0 or quantity = 0  with allow orders
3. Go to BO => Orders => New Order page
4. Add the last product created
5. check the increment/decrement button

I attached a screen record
https://drive.google.com/file/d/1-SSQprGhL3Bu25F5970OWwcc4MkMdfrn/view?usp=sharing

Thanks!

**Review by jolelievre — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/19FJiWhYyRm3PPxNHo3hpAqOjL7wO9iSE/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
