### PR TITLE
BO - New Order - Warn when product's stock of a pack are empty

### LINKED ISSUE #24553: BO - Add new Order page - Pack - an exception is displayed when we add a pack
#### Describe the bug

In the BO > Orders > Add new Order page, when we add a pack product out of stock; Pack quantities: Decrement both, Decrement products in the pack only.), an exception is displayed.
image

#### Expected behavior

We should have a clear alert:
```php
There are not enough products in stock.
```
image

#### Steps to Reproduce

1. Create two products with quantity = 0 (order not allowed)
2. Create a pack product that contains the two products created with quantity = 1
3. Pack quantities = Decrement both, Decrement products in the pack only. 
image
4. Go to BO > Orders > Add new order > choose a customer
5. Try to add the pack product
6. see error
image

PS1769 => ok
image

#### Additional information

* PrestaShop version: 1.7.8.x, 1774
* PHP version: 7.4, 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | BO - New Order - Warn when product's stock of a pack are empty but the stock of a pack is not empty
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24553
| How to test?      | Cf. #24553

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24657)

### CODE REVIEW

File: src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php [hunk 1]
```diff
@@ -194,6 +195,16 @@ private function assertProductIsInStock(Product $product, UpdateProductQuantityI
             return;
         }
 
+        if (Pack::isPack($product->id)) {
```
Comment (jolelievre) [inline src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php]:
```suggestion
        elseif (Pack::isPack($product->id)) {
```

Suggestion, so we distinguish both behaviour more easily (a product can't be a pack and have combinations)

File: src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php [hunk 2]
```diff
@@ -194,6 +195,16 @@ private function assertProductIsInStock(Product $product, UpdateProductQuantityI
...
+            $isEnoughQuantity = Pack::isInStock($product->id, $command->getNewQuantity());
```
Comment (jolelievre) [inline src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php]:
```suggestion
            $isPackInStock = Pack::isInStock($product->id, $command->getNewQuantity());
```
or
```suggestion
            $hasPackEnoughQuantity = Pack::isInStock($product->id, $command->getNewQuantity());
```

File: src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php [hunk 3]
```diff
@@ -194,6 +195,16 @@ private function assertProductIsInStock(Product $product, UpdateProductQuantityI
...
+
+            if (!$isAvailableWhenOutOfStock && !$isEnoughQuantity) {
+                throw new ProductOutOfStockException(sprintf('Product with id "%s" is out of stock, thus cannot be added to cart', $product->id));
```
Comment (jolelievre) [inline src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php]: Should we introduce a `PackOutOfStockException` (that would extend `ProductOutOfStockException` ) ? This would allow to tell the two behaviours apart and potentially adapt the error message more accurately

File: tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php [hunk 4]
```diff
@@ -384,7 +387,7 @@ public function addProductsCombinationsToCart(
 
     /**
      * @When I select :countryIsoCode address as delivery and invoice address for customer :customerReference in cart :cartReference
-     * @Given cart :cartReference delivery and invoice address country for customer :customeReferenceis is :countryIsoCode
+     * @Given cart :cartReference delivery and invoice address country for customer :customerReference is :countryIsoCode
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php:390]: It did not seem to bother, maybe this statement is never used and could be removed? (just the annotation line)

File: tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php [hunk 5]
```diff
@@ -287,6 +290,48 @@ public function productWithNameIsOutOfStock($productName)
...
+     * @Given /^the product "(.+)" (allows|denies) order if out of stock/
+     *
+     * @param string $productName
+     * @param string $status
+     */
+    public function productWithNameSetStatusOutOfStockOrders(string $productName, string $status): void
+    {
+        $this->checkProductWithNameExists($productName);
+        // Update Product
+        $this->getProductWithName($productName)->out_of_stock = $status == 'allows' ? 1 : 0;
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php]: Maybe you can store it into a local variable?

File: tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    When I update quantity of product "product_pack" in the cart "cart_pack" to 11
+    Then I should get an error that you have the maximum quantity available for this product
+    And cart "cart_pack" should not contain product "product_pack"
+    When I update quantity of product "product_pack" in the cart "cart_pack" to 10
+    Then I should get no error
+    And cart "cart_pack" should contain product "product_pack"
+    When I delete product "product_pack" from cart "cart_pack"
+    And cart "cart_pack" should not contain product "product_pack"
+
+  Scenario: If the pack has availability preferences to deny order
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature]: You should vary the scenario's titles they are all the same
```suggestion
  Scenario: If the pack has availability preferences to deny order and only pack is decremented
```

File: tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+    Given the product "product_pack" denies order if out of stock
+    And the pack "product_pack" decrements products in pack only
+    When I update quantity of product "product_pack" in the cart "cart_pack" to 6
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature:48]: I don't understand this one, I thought the stock was 10 not 5

File: tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+    Then I should get an error that you have the maximum quantity available for this product
+    And cart "cart_pack" should not contain product "product_pack"
+    When I update quantity of product "product_pack" in the cart "cart_pack" to 5
+    Then I should get no error
+    And cart "cart_pack" should contain product "product_pack"
+    When I delete product "product_pack" from cart "cart_pack"
+    And cart "cart_pack" should not contain product "product_pack"
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature:62]: Maybe you could add stock checks after each modif `Then the available stock for product "product_pack" should be 10` Unless it's not possible because the stock remains the same until the cart is actually ordered? Then maybe you could add a new statement to check "virtual" stock (basically you need to provide the cartId so that it's contained quantity is used).
But this is just a suggestion!

**Review by jolelievre — COMMENTED** [review]
A few suggestions, and some questions to answer But almost all good to me

File: tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php (hunk 4 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php:390]: Used in `tests/Integration/Behaviour/Features/Scenario/Order/add_cart_rule_to_order.feature`

File: tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature (hunk 7 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature:48]: Commented ;)

File: tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature (hunk 8 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Cart/Updating/Product/update_pack.feature:62]: I think the stock remains the same until the cart is actually ordered.

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php [hunk 9]
```diff
@@ -178,17 +180,29 @@ private function getProductObject(ProductId $productId)
...
 
             if (!$isAvailableWhenOutOfStock && !$isEnoughQuantity) {
-                throw new ProductOutOfStockException(sprintf('Product with id "%s" is out of stock, thus cannot be added to cart', $product->id));
+                throw new ProductOutOfStockException(
+                    sprintf('Product with id "%s" is out of stock, thus cannot be added to cart', $product->id)
+                );
+            }
+
+            return;
+        } elseif (Pack::isPack($product->id)) {
```
Comment (PierreRambaud) [inline src/Adapter/Cart/CommandHandler/UpdateProductQuantityInCartHandler.php:200]:
```suggestion
        }

        if (Pack::isPack($product->id)) {
```

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

When we try to add a pack out of stock not allowed, I have an issue (with all quantity parameters).
Steps to reproduce the issue:

1. Go to BO > Orders > Add new Order
2. Choose a customer (John Doe)
3. Search the pack product
4. Change the quantity to 1000 and try to add it to the cart
5. See error

image

Another case:

1. Create two products with quantity = 0 (order not allowed)
2. Create a pack product that contains the two products created with quantity = 1
3. Pack quantities = Decrement both or Decrement products in the pack only.
4. Go to BO > Orders > Add new order > choose a customer
5. Try to add the pack product
6. see error

image


Thank you!

**Review by matks — APPROVED** [review]
Thank you, great work 👏

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
I checked all these combinations:

1. Pack out of stock not allowed & allowed:
1.1. Products associated with this pack are all out of stock allowed
1.2. Products associated with this pack are all out of stock not allowed
1.3. Products associated with this pack are in stock
1.4. Products associated with this pack are some in stock and some out of stock
2. All types checked with all availability:
2.1. Decrement both
2.2. Decrement pack only
2.3. Decrement product only

https://drive.google.com/file/d/1C2xebMairQbEqZwHyW6NLGtfB2VYvYl_/view?usp=sharing
Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
