### PR TITLE
Fix error SQL in getRecurseCategory method

### LINKED ISSUE #14366: Error SQL in class CMSCategoryCore in the method getRecurseCategory
Hello,

I found a bug in CMSCategory class for the multisite mode Prestashop in last version 1.6.1.24.
You forgot an `id_shop` in SQL :
`$sql = 'SELECT c.id_cms, cl.meta_title, cl.link_rewrite
				FROM '._DB_PREFIX_.'cms c
				'.Shop::addSqlAssociation('cms', 'c').'
				JOIN '._DB_PREFIX_.'cms_lang cl ON c.id_cms = cl.id_cms
				WHERE id_cms_category = '.(int)$current.'
				AND cl.id_lang = '.(int)$id_lang.($active ? ' AND c.active = 1' : '').'
				GROUP BY c.id_cms
				ORDER BY c.position';`
Correction :  
`$sql = 'SELECT c.id_cms, cl.meta_title, cl.link_rewrite
				FROM '._DB_PREFIX_.'cms c
				'.Shop::addSqlAssociation('cms', 'c').'
				JOIN '._DB_PREFIX_.'cms_lang cl ON (c.id_cms = cl.id_cms AND cl.id_shop = '. (int) Context::getContext()->shop->id .' AND cl.id_lang = '.(int)$id_lang.')
				WHERE id_cms_category = '.(int)$current . ($active ? ' AND c.active = 1' : '').'
				GROUP BY c.id_cms
				ORDER BY c.position';`

Hoping to have been of assistance,

Have a nice day,

### PR DESCRIPTION
**Pull request by marionf**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix error SQL in getRecurseCategory method
| Type?         | bug fix 
| Category?     | BO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14366
| How to test?  | Try to create a CMS category + CMS page with multistore enabled and without. Try to display the sitemap page in FO. Try to generate and display sitemap.xml through Google sitemap module

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15926)

### CODE REVIEW

File: classes/CMSCategory.php [hunk 1]
```diff
@@ -191,14 +191,16 @@ public static function getRecurseCategory($id_lang = null, $current = 1, $active
             $category['children'][] = CMSCategory::getRecurseCategory($id_lang, $row['id_cms_category'], $active, $links);
         }
 
-        $sql = 'SELECT c.`id_cms`, cl.`meta_title`, cl.`link_rewrite`
+		$sql = 'SELECT c.`id_cms`, cl.`meta_title`, cl.`link_rewrite`
```
Comment (PierreRambaud) [inline classes/CMSCategory.php]:
```suggestion
        $sql = 'SELECT c.`id_cms`, cl.`meta_title`, cl.`link_rewrite`
```

**Review by PierreRambaud — DISMISSED** [review]

**Comment by matks** [comment]
@sarahdib what is wrong with this PR ?

**Comment by sarahdib** [comment]
@matks there is no step for testing and we don't know what the PR fix : 
https://github.com/PrestaShop/PrestaShop/issues/14366#issuecomment-542053289

**Comment by marionf** [comment]
@sarahdib 

You can make non-regression tests: try to create a CMS category + CMS page with multistore enabled and without
I don't know if there is an action to do in back-office that allows to call the function getRecurseCategory

**Comment by matks** [comment]
The function `getRecurseCategory()` is used in `SitemapController::getPagesLinks()` so it's used to compute the website sitemap

**Comment by Robin-Fischer-PS** [comment]
Hi @marionf ,

Unfortunately, does not work really well :stuck_out_tongue: 

When trying to access the FO sitemap (without any action on BO), we have a PrestaShopDatabaseException : 
PR15926 crash

**Review by PierreRambaud — APPROVED** [review]

**Comment by marionf** [comment]
@Robin-Fischer-PS it should be fixed now

**Comment by Robin-Fischer-PS** [comment]
@marionf I checked with/without multistore, the CMS creation is OK, and so is the sitemap on FO.

So it's QA Approved :wink:

**Comment by matks** [comment]
Thank you @marionf and @carlead
