### PR TITLE
Change jQuery-ui position before theme.js to avoid overriding bootstrap ones

### LINKED ISSUE #25738: jQuery UI overrides bootstrap tooltip component
#### Describe the bug

When modules adds jQuery UI library (for example ps_searchbar, ps_facetedsearch), it is included in template due to higher priority after theme.js where bootstrap library is included. Bootstrap and jQuery UI uses $.fn.tooltip method for their tooltip components. When jQuery UI is included it overrides bootstrap tooltip method.

#### Expected behavior

JQuery UI should be included before theme.js file. To prevent it from overriding bootstrap tooltip component. 

#### Steps to Reproduce

1. Go to product page.
2. Open `themes/classic/templates/catalog/product.tpl` and place there inside `{block name='page_header_container'}` block. 

```
<span data-toggle="tooltip" title="tooltip content">tooltip hover me</span>
```
3. Open `themes/classic/assets/js/custom.js` and paste this code:
```
$(() => {
  $('[data-toggle="tooltip"]').tooltip();
})
``` 
4. Go back to product page and hover on that span.
Tooltip should appear with white background and box-shadow (it is jQuery UI tooltip).

Zrzut ekranu 2021-08-30 o 14 20 46

5. Go BO and disable ps_searchbar module.
6. Go back to product page and refresh.
7. Hover on span and red tooltip should appear. (it is bootstrap tooltip).
Zrzut ekranu 2021-08-30 o 14 21 16

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Bootstrap tooltips were overridden by JQuery-ui one which make it difficult to style it with Bootstrap variables
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #25738.
| How to test?      | See issue and follow steps
| Possible impacts? | Classic theme tooltips use

# Breaking changes
As this was here from years, theme developers may adapted their stylesheets to change the JQuery-ui ones, now they'll see bootstrap ones and needs to adapt their themes

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25818)

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
@NeOMakinG 1.7.8.1 and BC Break? 🤔

**Comment by NeOMakinG** [comment]
@kpodemski rebased it and seen with PM, let's push this to develop

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

File: classes/controller/FrontController.php [hunk 1]
```diff
@@ -1217,7 +1217,7 @@ public function addJqueryUI($component, $theme = 'base', $check_dependencies = t
 
         $this->registerStylesheet('jquery-ui-theme', $css_theme_path, ['media' => 'all', 'priority' => 95]);
         $this->registerStylesheet('jquery-ui', $css_path, ['media' => 'all', 'priority' => 90]);
-        $this->registerJavascript('jquery-ui', $js_path, ['position' => 'bottom', 'priority' => 90]);
+        $this->registerJavascript('jquery-ui', $js_path, ['position' => 'bottom', 'priority' => 49]);
```
Comment (PierreRambaud) [inline classes/controller/FrontController.php:1227]: What's the reason behind 49? :thinking: 
Why not 50, or 40?

Comment (NeOMakinG) [reply classes/controller/FrontController.php:1227]: Looks like 49 is right before the theme.js, @Progi1984 confirm it

Comment (PierreRambaud) [reply classes/controller/FrontController.php:1227]: Maybe add a comment, not sure we will retrieve this information in the future, it's not obvious =)

**Comment by marwachelly** [comment]
Hi, 
I removed the QA label. This PR should be reviewed first.
Thanks,

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by kpodemski** [comment]
@NeOMakinG 

is it coming for the 1.7.8, or for the develop branch? Milestone is `v8`, branch and labels are related to `1.7.8`?

**Comment by NeOMakinG** [comment]
Rebased to develop, damn that was dumb!

**Review by kpodemski — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by atomiix** [comment]
Closed and re-opened to trigger the CI

**Comment by PierreRambaud** [comment]
> Closed and re-opened to trigger the CI

It seems that integration tests are broken because of this :sweat:

**Comment by marwachelly** [comment]
Hello,
PR is tested and issue is fixed. 
https://watch.screencastify.com/v/Bg4Jj0z9AkLhvXFbNYjh
Thanks,

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @marwachelly
