### PR TITLE
Show free shipping indication only if appropriate

### LINKED ISSUE #10739: Free shipping as visitor
**Describe the bug**
Hello, I've noticed a bug with displaying shipping cost in the cart. As the guest there is always free shipping. As logged member shipping cost is displaying correctly. 

I have only one Carrier (DHL). Shipping costs are calculating by summary package weight and there is no free shipping option.

I've run out of ideas. Can You help me with this issue?

**To Reproduce**
1. Go to ' https://www.febe.store/shop/de/ '
2. Click on ' every product and add it to cart as visitor '
3. See shipping cost at cart

**Screenshots**
In attachment 2 screenshots:
- in first there is item added as visitor - there are no shipping cost
- second - same item as above but while logged in customer account. Shipping cost are calculated correctly

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 5.6.32

member
visitor

### PR DESCRIPTION
**Pull request by hacchus**
The problem is if you are not logged in or need postal codes to determine shipping, you always see shipping as "Free" in your cart, which really means "not calculated yet". It is bad for customer psychology to see "Free" and after they enter more information to get a price.

The result of this change is if there is shipping calculated then it will simply show it. If the system cannot determine shipping yet for any reason then you get "Not Calculated". Finally, if you really have free shipping then you get the indication "Free".

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?       | Instead of showing "Free", show an indication in cart like "Not Calculated" for shipping if shipping cost cannot yet be determined.
| Type?         |  improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10739 #15112

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13517)

### CODE REVIEW

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 1]
```diff
@@ -475,6 +473,41 @@ function ($voucher) {
...
+                }
+            }
+        }
+
+        $shippingDisplayValue = '';
+
+        if ($shippingCost != 0) {
+            $shippingDisplayValue = $this->priceFormatter->format($shippingCost);
+        } else if ($hasFreeCarrierFirst == 0) {
+            $shippingDisplayValue = $this->translator->trans('Not Calculated', array(), 'Shop.Theme.Checkout');
```
Comment (LouiseBonnard) [inline src/Adapter/Presenter/Cart/CartPresenter.php]: Hey, thank you, wouldn't it be easier to remove this line when shipping costs are not determined yet and display it only when free shipping is defined in parameters? If not, I would suggest _Calculated later_ or _Calculated at checkout_. Ping me if you all have a better idea!

Comment (hacchus) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: @LouiseBonnard Yes"Calculated later" seems better. If anyone else has a better idea let's hear it.

Comment (rblaurin) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: I would vote for the first suggestion from @LouiseBonnard, removing this line when not calculated...

**Comment by marionf** [comment]
@hacchus 

> The problem is if you are not logged in or need postal codes to determine shipping, you always see shipping as "Free" in your cart, which really means "not calculated yet". 

The price of the carrier that you see when you are not logged depends of the default carrier and default country.
You see "free" if for your default country and default carrier you have defined no amount
If you choose as default a not free carrier, you will see price even if you are not connected

capture d'écran_1485


I just tried your PR and disable all carriers, I still see "free" shipping

**Comment by hacchus** [comment]
@marionf 

I've tested this on a fresh 1.7.5.2 installation and if I disable all carriers then I get the "Not Calculated" indication as expected. I also have a clean 1.7.5.0 installation with the same results.

dc1

Most of the times I use 3rd party modules to display shipping with complex rules that require zip codes, and therefore it's not possible to calculate shipping until I have zip codes. Up to that point I always get "Free" which is misleading, that's why I came up with this solution. 

I made this modification on two shops (1.7.4.4 and 1.7.5.1), that use a 3rd party shipping module with zip codes and it works as expected.

**Comment by marionf** [comment]
@hacchus 

Thank you for your answer, my bad I was testing your PR on 1.7.6.x branch instead of develop branch
I well see "not calculated" now.
Do you think it's possible to not display this line instead of "not calculated" ?
I am not sure people understand why it's "not calculated"

File: src/Adapter/Presenter/Cart/CartPresenter.php (hunk 1 above)
Comment (hacchus) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: @marionf @rblaurin @LouiseBonnard 

Yes we can hide it. I think we need to change the theme in two places (if more please let me know).

First we send an empty string instead of "Not Calculated".

For modal cart we must change this file:
themes\classic\modules\ps_shoppingcart\modal.tpl on line 60 and surround it with an if statement to check "$cart.subtotals.shipping.value"

For checkout page this file: themes\classic\templates\checkout\_partials\cart-summary.tpl on line 56 we change "if $subtotal" with "if $subtotal.value"

The file themes\classic\templates\checkout\_partials\cart-detailed-totals.tpl is already doing this on line 30 so we don't need to change anything.

I tested this on 1.7.5.2 and works fine. Are there other places we need to change?

**Comment by marionf** [comment]
Thank you @hacchus 
Let's wait for code review now

File: themes/classic/templates/checkout/_partials/cart-summary.tpl [hunk 2]
```diff
@@ -54,7 +54,7 @@
 
     {block name='cart_summary_subtotals'}
       {foreach from=$cart.subtotals item="subtotal"}
-        {if $subtotal && $subtotal.type !== 'tax'}
+        {if $subtotal.value && $subtotal.type !== 'tax'}
```
Comment (matks) [inline themes/classic/templates/checkout/_partials/cart-summary.tpl]: This line might have side-effects. If `$subtotal.value` is 0 (integer), it will hide the line instead of display it. This could create issue if the merchant wants to display some subtotal to the customer for legal compliance matters 🤔 ?

Comment (matks) [reply themes/classic/templates/checkout/_partials/cart-summary.tpl]: I say this because the change will impact every subtotals passed in `$cart.subtotals`, not only the shipping subtotal 😉

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 3]
```diff
@@ -475,6 +473,39 @@ function ($voucher) {
                 '',
         );
     }
+    
+    private function getShippingDisplayValue($cart, $shippingCost)
+    {
+        $hasFreeCarrier = 0;
+        $default_country = null;
```
Comment (matks) [inline src/Adapter/Presenter/Cart/CartPresenter.php]: Can we stick to camelCase variable naming 😉 ? Just above we have `$hasFreeCarrier` that is camelCase then this one `$default_country` that is snake_case

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 4]
```diff
@@ -475,6 +473,39 @@ function ($voucher) {
                 '',
         );
     }
+    
+    private function getShippingDisplayValue($cart, $shippingCost)
```
Comment (matks) [inline src/Adapter/Presenter/Cart/CartPresenter.php:487]: Can we have phpDoc please ?

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 5]
```diff
@@ -475,6 +473,39 @@ function ($voucher) {
...
+    {
+        $hasFreeCarrier = 0;
+        $default_country = null;
+
+        if (isset(Context::getContext()->cookie->id_country)) {
+            $default_country = new Country(Context::getContext()->cookie->id_country);
+        }
+
+        $delivery_option_list = $cart->getDeliveryOptionList($default_country);
```
Comment (matks) [inline src/Adapter/Presenter/Cart/CartPresenter.php]: Same, camelCase for the ❤️

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 6]
```diff
@@ -475,6 +473,39 @@ function ($voucher) {
...
         );
     }
+    
+    private function getShippingDisplayValue($cart, $shippingCost)
+    {
+        $hasFreeCarrier = 0;
+        $default_country = null;
+
+        if (isset(Context::getContext()->cookie->id_country)) {
+            $default_country = new Country(Context::getContext()->cookie->id_country);
```
Comment (matks) [inline src/Adapter/Presenter/Cart/CartPresenter.php]: This could be improved but it's a bit outside of this PR scope. If we cannot find the country of the visitor because he has no cookies but he has landed on the EN version of the website or the GB version of the website, we could still check for the relevant carriers. But this is a bonus, not mandatory.

**Comment by matks** [comment]
Hi @hacchus thanks for the contribution ! I have a few comments, but the important one is https://github.com/PrestaShop/PrestaShop/pull/13517#discussion_r282508618. Other ones are rather for code style.

**Comment by hacchus** [comment]
Hello @matks thanks for your feedback. I did the code style changes and also moved the code that checks carriers inside the if statement, so it doesn't have to run every time, only when shipping cost is 0.

I had to also change the file themes\classic\templates\checkout_partials\cart-detailed-totals.tpl on line 30 to allow 0 values to pass from there as well.

File: themes/classic/templates/checkout/_partials/cart-summary.tpl [hunk 7]
```diff
@@ -54,7 +54,7 @@
 
     {block name='cart_summary_subtotals'}
       {foreach from=$cart.subtotals item="subtotal"}
-        {if $subtotal && $subtotal.type !== 'tax'}
+        {if $subtotal && $subtotal.value|count_characters > 0 && $subtotal.type !== 'tax'}
```
Comment (matks) [inline themes/classic/templates/checkout/_partials/cart-summary.tpl]: Smarty way to handle not-empty values 😄 👏

**Comment by kpodemski** [comment]
ping ping ping, is there any way to rush it to 1.7.6? this is a great contribution

cc @matks

**Comment by jolelievre** [comment]
> ping ping ping, is there any way to rush it to 1.7.6? this is a great contribution
> 
> cc @matks

hello @kpodemski,

sorry but we already froze the 176 version, so we only integrate regression bug fixes, this will have to wait for the 177 version
but thank you @hacchus for this improvement!

**Comment by matks** [comment]
H @hacchus sorry for the late answer, summer got us very busy with 1.7.6 release

I think the PR is good as it is 👍let's move to QA !

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@hacchus Oh, PrettyCI linter is unhappy and there are some git conflicts. Can you handle them ? Else I can do it as you waited for a long time 😄

**Comment by hacchus** [comment]
Hi @matks could you please do it, as I'm very busy at this time? Thanks! :grin:

**Comment by khouloudbelguith** [comment]
Hi @hacchus,

This PR needs to be rebased into develop

Thanks!

**Comment by matks** [comment]
@hacchus PR has been rebased, conflicts solved, codestyle fixed 👍we can now move to the QA stage

**Comment by sarahdib** [comment]
Hello @hacchus 

Thank you for your contribution.

After several test we didn't see any change with the behavior before and after the PR.

Can you explain the exact step to reproduce.

Thank you

**Comment by sarahdib** [comment]
@hacchus Sorry I think it was a cache problem from me.

**Review by matks — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @hacchus
