### PR TITLE
Fix 29341 - Rate impact calculation

### LINKED ISSUE #29341: BO - Product V2 with combinations - The impact on price is not automatically calculated in the bulk edit modal
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-986520326
 The impact on price is not automatically calculated in the bulk edit modal 
image

### Expected behavior
 
 The impact on price tax excl and impact on price tax incl is automatically calculated in the bulk edit modal when on field is edited.

### Steps to reproduce

1. Go to BO > Catalog > Product V2
2. Create a product with combinations > In the combinations list > select all combinations & edit with bulk action
3. Click on Price
4. Set the impact on price tax excluded
5. See error: the impact on price tax included is not automatically changed
image

Same issue if we edit the `the impact on price tax included`, `the impact on price tax excluded` is not automatically calculated
image

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | This PR adds front end calculation for both prices (inc. taxes & ex. taxes) on product v2 page.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29341.

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts [hunk 1]
```diff
@@ -37,4 +37,35 @@ $(() => {
   ]);
   new ImageSelector();
   new QuantityModeSwitcher();
+
+  const priceExcludedTaxId = 'bulk_combination_price_price_tax_excluded';
```
Comment (matthieu-rolland) [inline admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts]: So far we've taken the habit of putting those identifiers in mapping files, see [this file](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts) for example

File: src/Adapter/LegacyContext.php [hunk 2]
```diff
@@ -112,6 +112,11 @@ public function getAdminBaseUrl()
         return __PS_BASE_URI__ . basename(_PS_ADMIN_DIR_) . '/';
     }
 
+    public function getCountryId(): int
+    {
+        return $this->getContext()->country->id;
```
Comment (matthieu-rolland) [inline src/Adapter/LegacyContext.php:117]: :+1:

**Review by matthieu-rolland — COMMENTED** [review]
Just a minor feedback

File: admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts [hunk 3]
```diff
@@ -37,4 +37,35 @@ $(() => {
...
+
+  priceExcludedTaxInput.addEventListener('keyup', () => {
+    let value;
+
+    if (priceExcludedTaxInput.value === '') {
+      value = 0;
+    } else {
+      value = parseFloat(priceExcludedTaxInput.value);
+    }
+    priceIncludedTaxInput.value = (value * rate).toString();
```
Comment (matthieu-rolland) [inline admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts:58]: I wonder if we could use [this](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/order/view/order-prices.ts) here, instead of making the calculation here

Comment (FabienPapet) [reply admin-dev/themes/new-theme/js/pages/product/combination/bulk.ts:58]: Not sure about using this as we don't have precision needed and we can avoid a dependency to OrderPrice here.

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 4]
```diff
@@ -546,4 +546,19 @@ private function loadProduct(Product $product): Product
 
         return $product;
     }
+
+    public function getProductTaxRulesGroupId(ProductId $productId): TaxRulesGroupId
+    {
+        $qb = $this->connection->createQueryBuilder();
```
Comment (nicosomb) [inline src/Adapter/Product/Repository/ProductRepository.php]: No need to create a new variable.

**Review by nicosomb — COMMENTED** [review]
Just a little comment.

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 4 above)
Comment (matks) [reply src/Adapter/Product/Repository/ProductRepository.php]: I have one reason 😝 if you use the debugger, this allows you to check the state of this variable

while
```
$result = ($this->connection->createQueryBuilder())
            ->addSelect('p.id_tax_rules_group')
```
you can't

(sorry I just wanted to say something 😆 )

But I feel like this is more readable though :) some people say "readable code requires one statement by line, no more"

**Review by matks — DISMISSED** [review]
I approve the PR but feel free to apply improvement following @nicosomb

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 4 above)
Comment (FabienPapet) [reply src/Adapter/Product/Repository/ProductRepository.php]: Done

**Comment by FabienPapet** [comment]
@matks @nicosomb I'll need your review again ;)

**Review by matks — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @FabienPapet 

Thank you for your PR !

The issue is solved **OK**

- I run the automated tests **OK**
- Check a V2 product with combinations - The impact on the price is automatically calculated in the bulk edit modal
- Apply the modification to all combinations

See the attached screen shot 

Products • 29846 (1)

Thank you :rocket:

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @sallemiines and @FabienPapet
