### PR TITLE
Wrong address update when changing the shipping adresse of an order

### LINKED ISSUE #17695: When you try to change the shipping address of an order it changes the invoice address instead
**Describe the bug**
When you try to change the shipping address of an order it changes the invoice address instead

**To Reproduce**
1. Go to Orders > Orders > View an order
2. Click on change for the shipping address
3. Select another address than the current one
4. See the invoice address is changed instead of shipping address

**Screenshots**
https://drive.google.com/file/d/11XRbNaOTmbqodv-Mz4UTKtkhFkRE-Yy9/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When changing the shipping address of an order, the invoice address was updated instead of the shipping one. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17695
| How to test?  | 1. Go to Orders > Orders > View an order<br>2. Click on change for the shipping address<br>3. Select another address than the current one<br>4. The shipping address should be updated, not the invoice one

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17700)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/view.js [hunk 1]
```diff
@@ -164,7 +164,7 @@ $(() => {
     const $modal = $(OrderViewPageMap.updateCustomerAddressModal);
 
     $(OrderViewPageMap.openOrderAddressUpdateModalBtn).on('click', (event) => {
-      $modal.find(OrderViewPageMap.updateOrderAddressTypeInput).val($btn.data('address-type'));
+      $modal.find(OrderViewPageMap.updateOrderAddressTypeInput).val($(event.currentTarget).data('address-type'));
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/order/view.js]:
```suggestion
      $modal.find(OrderViewPageMap.updateOrderAddressTypeInput).val($(event.currentTarget).data('addressType'));
```

**Review by Progi1984 — COMMENTED** [review]
Small feedback

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
This PR correctly fix #17695. Thanks @atomiix

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
