### PR TITLE
Fix wrong use of alias when registering new hook

### LINKED ISSUE #18945: Hook missing/misspelt in DB: (actionAuthenticationBefore)
#### Describe the bug

**CustomerLoginForm.php** contains **actionAuthenticationBefore**
But the database hooks table does not contain **actionAuthenticationBefore**, 
instead there is **actionbeforeauthentication** probably misspelled?

#### Expected behavior

Using **hookActionAuthenticationBefore** in code does not fire the hook.
Renaming it in the DB hooks table from actionbeforeauthentication to actionAuthenticationBefore, fixed the issue.

#### Steps to Reproduce

Calling function hookActionAuthenticationBefore ( ) does nothing

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Hooking a module to hook `actionAuthenticationBefore` doesn't work on a clean install.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no... i think
| Deprecations? | no
| Fixed ticket? | Fixes #18945
| How to test?  | Read below

When installing a module that tried to hook to `actionAuthenticationBefore`, it didn't work.

After some investigation, we found out that said module wasn't previously registered in `ps_hooks` on a clean install (which is not an issue in itself because PrestaShop automatically adds them as needed). However, even if it's not registered in `ps_hooks`, it does have an alias in `ps_hook_alias`: `actionBeforeAuthentication`.

Whenever a hook doesn't exist in `ps_hooks`, it is automatically added. But if the hook has an alias, we found that the _lowercased_ alias was being inserted instead. Why? No clue. I think it was a bug. Maybe?

As far as I can tell, the bug goes way back to 2011, probably beyond...

---
**Update on 2020-08-05:** With this change, the alias behavior is now as follows:

**Context:**
- `someNewHook` is a given hook
- `someHook` is an alias for `someNewHook`

**Scenario 1:** Nominal case – a module registers to `someNewHook`, the hook `someNewHook` is dispatched
- table ps_hook contains “someNewHook”
- table ps_hook_module refers to “someNewHook”
- when `someNewHook` is dispatched, the module’s `hooksomeNewHook()` method is called

**Scenario 2:** Old code dispatches a renamed hook – a module registers to `someNewHook`, the hook `someHook` is dispatched
- table ps_hook contains “someNewHook”
- table ps_hook_module refers to “someNewHook”
- when `someHook` is dispatched, the module’s `hooksomeNewHook()` method is called

**Scenario 3:** Modules get backwards compatibility with renamed hooks – a module registers to `someHook`, the hook `someNewHook` is dispatched
- table ps_hook contains “someHook”
- table ps_hook_module contains “someHook”
- when `someNewHook` is dispatched, the module’s `hooksomeHook()` method is called

**Scenario 4:** Old code calls old hook and old module still works – a module registers to `someHook`, the hook `someHook` is dispatched
- table ps_hook contains “someHook”
- table ps_hook_module contains “someHook”
- when `someHook` is dispatched, the module’s `hooksomeHook()` method is called

---
**Update on 2020-08-06:** This change allowed me to realize that the the hook `displayHeader` was used as an alias of `Header` instead of the other way around. This was making `Header` be treated as the canonical hook name instead of an alias, which broke ps_shoppingcart.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12578)

### CODE REVIEW

File: classes/Hook.php [hunk 1]
```diff
@@ -315,34 +314,67 @@ private static function getHookAliasesFor($hookName)
...
+     * @param string $hookName
      *
      * @return bool
      */
     private static function isHookCallableOn($module, $hookName)
     {
-        $aliases = Hook::getHookAliasesFor($hookName);
-        $aliases[] = $hookName;
+        $aliases = array_merge(
+            [$hookName],
```
Comment (kpodemski) [inline classes/Hook.php]: @eternoendless i'm still lost whether we can or not use shorthand arrays :D

**Comment by kpodemski** [comment]
it might be due to the fact that in 1.4 and before we had `hookHeader` etc. in 1.5 this have changed to `hookDisplayHeader` etc.

overall quite nice catch as i've never noticed this problem before 🤔

File: classes/Hook.php (hunk 1 above)
Comment (eternoendless) [reply classes/Hook.php]: We can!

**Comment by eternoendless** [comment]
> it might be due to the fact that in 1.4 and before we had `hookHeader` etc. in 1.5 this have changed to `hookDisplayHeader` etc.

Yeah, that's what aliases are for: you ask for the alias, and the canonical hook is issued/inserted. But I think that inserting the alias instead of the canonical name was a bug, because it would never work!

File: classes/Hook.php (hunk 1 above)
Comment (PierreRambaud) [reply classes/Hook.php]: And we love it!

**Review by mickaelandrieu — DISMISSED** [review]
Looks good but... regarding the importance of the classes impacted, maybe can we create some tests to confirm it works?

**Comment by matks** [comment]
Indeed I think a behat test (behat because database is involved) would be good here. @eternoendless do you want me to add the test ?

**Comment by eternoendless** [comment]
@matks Are you sure that this needs a Behat test? I think it would make more sense to build an _integration_ test much like the ones for the translator (which use a test module)

**Comment by matks** [comment]
> @matks Are you sure that this needs a Behat test? I think it would make more sense to build an _integration_ test much like the ones for the translator (which use a test module)

Indeed I was thinking about an integration test. Behat might not be the best choice indeed.

**Comment by matks** [comment]
🆙

**Comment by Progi1984** [comment]
Hello @eternoendless , thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by psyray** [comment]
Hi @eternoendless 
ping ! :)

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by eternoendless** [comment]
Rebased on top of 1.7.7.x.

I was able to verify this change using the awesome [QA module](https://github.com/PrestaShop/ps_qualityassurance).

1. Register the hook using the module so that a log entry is saved when invoked:

Screenshot 2020-08-04 at 10 40 48

2. Verify that the new hook `actionAuthenticationBefore` has been added and registered instead of the alias `actionBeforeAuthentication` (this was the original bug) ✅ 

Screenshot 2020-08-04 at 11 19 37

3. Try to log in as a customer on FO to trigger the hook (it doesn't matter if the customer exists)

Screenshot 2020-08-04 at 11 21 14

4. Verify that the hook was invoked by checking the logs ✅ 

Screenshot 2020-08-04 at 11 22 42

5. Now let's unregister the former hook and repeat the test using the alias `actionBeforeAuthentication` instead:

Screenshot 2020-08-04 at 11 25 58

6. Verify that the new hook `actionBeforeAuthentication` has been added and registered ✅ 

Screenshot 2020-08-04 at 18 39 52

7. Log in as a customer on FO to trigger the hook, then verify that the hook was invoked by checking the logs ✅ 

Screenshot 2020-08-05 at 11 10 46

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

File: classes/Hook.php [hunk 2]
```diff
@@ -175,44 +181,35 @@ public static function getHooks($position = false, $only_display_hooks = false)
...
-                $hook_ids[strtolower($row['name'])] = $row['id_hook'];
-            }
-            Cache::store($cache_id, $hook_ids);
-        } else {
-            $hook_ids = Cache::retrieve($cache_id);
-        }
+        $hook_ids = self::getAllHookIds($withAliases, $refreshCache);
 
-        return isset($hook_ids[$hook_name]) ? $hook_ids[$hook_name] : false;
+        return isset($hook_ids[$hookName]) ? $hook_ids[$hookName] : false;
```
Comment (PierreRambaud) [inline classes/Hook.php:206]:
```suggestion
        return $hook_ids[$hookName]) ?? false;
```

File: classes/Hook.php [hunk 3]
```diff
@@ -222,6 +219,11 @@ public static function getNameById($hook_id)
 							SELECT `name`
 							FROM `' . _DB_PREFIX_ . 'hook`
 							WHERE `id_hook` = ' . (int) $hook_id);
+
+            if (false === $result) {
+                throw new PrestaShopObjectNotFoundException('The hook id #%s does not exist in database', $hook_id);
```
Comment (PierreRambaud) [inline classes/Hook.php:224]:
```suggestion
                throw new PrestaShopObjectNotFoundException('The hook id #%d does not exist in database', $hook_id);
```

File: classes/Hook.php [hunk 4]
```diff
@@ -231,51 +233,55 @@ public static function getNameById($hook_id)
...
+     *
+     * @param string $hookName Hook name to test
+     *
+     * @return bool TRUE if the hook is an alias, false otherwise
+     *
+     * @throws PrestaShopDatabaseException
+     */
+    public static function isAlias(string $hookName): bool
+    {
+        $aliases = self::getCanonicalHookNames();
```
Comment (PierreRambaud) [inline classes/Hook.php:265]:
```suggestion
        $aliases = static::getCanonicalHookNames();
```

File: classes/Hook.php [hunk 5]
```diff
@@ -288,158 +294,219 @@ private static function getHookAliasesList()
...
      */
-    private static function isHookCallableOn($module, $hookName)
+    public static function isHookCallableOn(Module $module, string $hookName, $strict = false): bool
     {
-        $aliases = Hook::getHookAliasesFor($hookName);
-        $aliases[] = $hookName;
+        $hooksToCheck = (!$strict) ? static::getAllKnownNames($hookName) : [$hookName];
+
+        foreach ($hooksToCheck as $currentHookName) {
+            if (is_callable([$module, self::getMethodName($currentHookName)])) {
```
Comment (PierreRambaud) [inline classes/Hook.php:383]:
```suggestion
            if (is_callable([$module, static::getMethodName($currentHookName)])) {
```

File: classes/Hook.php [hunk 6]
```diff
@@ -288,158 +294,219 @@ private static function getHookAliasesList()
...
+    private static function callHookOn(Module $module, string $hookName, array $hookArgs)
     {
-        if (is_callable([$module, 'hook' . $hookName])) {
-            return Hook::coreCallHook($module, 'hook' . $hookName, $hookArgs);
+        // Note: we need to make sure to call the exact hook name first.
+        // This especially important when the module uses __call() to process the right hook.
+        // Since is_callable() will always return true when __call() is available,
+        // if the module was expecting an aliased hook name to be invoked, but we send
+        // the canonical hook name instead, the hook will never be acknowledged by the module.
+        $methodName = self::getMethodName($hookName);
```
Comment (PierreRambaud) [inline classes/Hook.php:409]:
```suggestion
        $methodName = static::getMethodName($hookName);
```

File: classes/Hook.php [hunk 7]
```diff
@@ -288,158 +294,219 @@ private static function getHookAliasesList()
...
-    public static function getRetroHookName($hook_name)
+    public static function getRetroHookName($hookName)
     {
-        $alias_list = Hook::getHookAliasList();
-        if (isset($alias_list[strtolower($hook_name)])) {
-            return $alias_list[strtolower($hook_name)];
+        $hookNamesByAlias = static::getCanonicalHookNames();
+        if (isset($hookNamesByAlias[strtolower($hookName)])) {
+            // return the canonical name (?)
+            return $hookNamesByAlias[strtolower($hookName)];
```
Comment (PierreRambaud) [inline classes/Hook.php:445]:
```suggestion
        $hookNamesByAlias = static::getCanonicalHookNames();
        $loweredName = strtolower($hookName);
        if (isset($hookNamesByAlias[$loweredName])) {
            // return the canonical name (?)
            return $hookNamesByAlias[$loweredName];
```

File: classes/Hook.php [hunk 8]
```diff
@@ -995,4 +1004,237 @@ private static function getHookRegistry()
...
+     * @throws PrestaShopDatabaseException
+     */
+    private static function getAllHookRegistrations(Context $context, ?string $hookName): array
+    {
+        $shop = $context->shop;
+        $customer = $context->customer;
+
+        $cache_id = self::MODULE_LIST_BY_HOOK_KEY
+            . ($shop instanceof Shop && isset($shop->id) ? '_' . $shop->id : '')
+            . ($customer instanceof Customer ? '_' . $customer->id : '');
```
Comment (PierreRambaud) [inline classes/Hook.php:1035]:
```suggestion
            . (isset($shop->id) ? '_' . $shop->id : '')
            . (isset($customer->id) ? '_' . $customer->id : '');
```
Instanceof checks are useless because of isset

**Comment by matks** [comment]
I have tested and validated the 4 scenarios provided by @eternoendless

**Comment by matks** [comment]
Thank you @eternoendless

**Comment by ProteanCode** [comment]
What is the correct way to make it working with both pre & post 1.7.7.0 instances?
