### PR TITLE
Disable "Features" section in Product Page when Features are disabled

### LINKED ISSUE #21689: Disabling feature in Performance doesnt hide the button in the product page
#### Describe the bug

In, BO, When I set the product feature to disable, the button "add a feature" is still present, I can add a feature, click and save and I have the confirmation message.
However, they are not really saved (if I switch to another tab, the features doesnt appears) 
Moreover, the features are not displayed into BO on the product page

#### Expected behavior

Hide the feature section

#### Steps to Reproduce

1. Go to Advanced param>performance
2. Set product feature to disable
3. Go to Catalog>products
4. Check a product with previously set features
=> they dont appear
=>Try to add a product feature> you can save, have the confirmation message but it isnt saved.

**Screenshots**

https://drive.google.com/file/d/1dDL_nqo4jw9uEL8gGUNlD9rF7Z3CIVfJ/view

#### Additional information

* PrestaShop version: 1.7.6.x, 1.7.7.x, 1.7.7 build 3
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  Disable "Features" section in Product Page when Features are disabled
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21689
| Related PRs       | N/A
| How to test?      | * Go to Advanced parameters > Performance<br>* Disable "Features"<br>* Enable the Product Page v2<br>* Go to Catalog > Products<br>* Go to a product with previously set features (like "Mountain fox notebook")<br>* **BEFORE :** The section "Features" exists<br>* **AFTER :** The section "Features" is removed
| Possible impacts? | Fixed only on Product v2 Page

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/FeaturesType.php [hunk 1]
```diff
@@ -33,9 +33,29 @@
...
+
+    /**
+     * @param TranslatorInterface $translator
+     * @param array $locales
+     * @param bool $isFeatureEnabled
+     */
+    public function __construct(
+        TranslatorInterface $translator,
+        array $locales,
+        bool $isFeatureEnabled
```
Comment (atomiix) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/FeaturesType.php]: I think this is a BC break ;)

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/FeaturesType.php]: @atomiix : I check the ADR : `Since classes whose instantiation is delegated to the Symfony service container are not supposed to be instantiated individually, changing the constructor of those classes is allowed.`

So it should not be a BC Break.

Comment (atomiix) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Specification/FeaturesType.php]: You're right! I forgot we had this rule!

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-maintainers & @PrestaShop/committers for a review

**Review by FabienPapet — DISMISSED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Progi1984 

I have checked your PR. But, i have noticed in the expected behavior of the issue that all the feature section should be hidden (`Hide the feature section`) updated by @MatShir 

But, with PR only the `Add a feature` button is hidden 

https://user-images.githubusercontent.com/92912932/201692445-8a1cbaa8-2e61-4b6a-9e57-d5068c786558.mp4


ping @MatShir What do you think?

Thank You!

**Comment by MatShir** [comment]
The section should be hidden 👍

**Review by matthieu-rolland — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Launched [automated tests](https://github.com/florine2623/testing_pr/actions/runs/3547989271), they are OK.

Check the Feature option in Product page V2 and in Performance in BO, as well as in FO.
It is OK according to the specifications, the whole Feature section is hidden!

https://user-images.githubusercontent.com/16019289/203994918-8d69958e-5211-49c7-a00b-d25d8f9a7fbb.mov

It is QA ✅ !
Thanks!
