### PR TITLE
Fix broken result in webservices

### LINKED ISSUE #30165: Webservice is broken with PS 8.0 and PHP 8.1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The webservice provides invalid XML  :  

image

### Expected behavior

We always should get valid XML : 

image

### Steps to reproduce

Try theses step with : 

- php 7.3 : you won't reproduce this bug
- php 8.1 : you will reproduce this bug

1. Install Prestashop 8.0.0 with demo products
2. Enable webservice
3. Open with your browser this url https://YOURURL/api/combinations/3 (this bug happens with some other url, it's just for example)
image

4. Check XML, you see the bug. XML doesn't allow number as tag, and data are missing

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This bug was "hidden" before php8 but it already existed.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30165 
| Related PRs       | 
| How to test?      | 1/ Activate webservices 2/ test this url: `/api/combinations/3`  (see issue for more complete informations)
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

File: classes/webservice/WebserviceOutputBuilder.php [hunk 1]
```diff
@@ -711,7 +711,7 @@ protected function renderFlatAssociation($object, $depth, $assoc_name, $resource
 
         foreach ($fields_assoc as $field_name => $field) {
             if (!is_array($this->fieldsToDisplay) || in_array($field_name, $this->fieldsToDisplay[$assoc_name])) {
-                if ($field_name == 'id' && !isset($field['sqlId'])) {
+                if (isset($field['id']) && !isset($field['sqlId'])) {
```
Comment (matthieu-rolland) [inline classes/webservice/WebserviceOutputBuilder.php:714]: this would work prior to php8, because the condition `$field_name == 'id'` would evalute to **true** when `$field_name` was equal to zero:

https://www.php.net/releases/8.0/en.php#saner-string-to-number-comparisons

But it should never have worked, here we should evaluate that the field ID exists, if it doesn't exist then we should be in the `else if` case. We are in the case when the id is cotained in the value (which is an array itself), and `$field_name` is a numeric array key.

So the bug was revealed with php8, but the code was always broken.

**Review by mflasquin — APPROVED** [review]
Good job :wink:

**Review by matks — APPROVED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @matthieu-rolland,
Thanks for the PR !
It's LGTM QA :heavy_check_mark: 

**PS : this PR tested with PS 800 + PHP 8.1 + chrome browser** 

image

Thank you :rocket:

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @matthieu-rolland and @sallemiines

**Comment by mamodesign** [comment]
After some testing, the proposed solution wasn't perfect if the value was NULL. i used this instead
if (isset($field['id']) && !isset($field['sqlId'])) {
if (**array_key_exists('id',$field)** && !isset($field['sqlId'])) {
