### PR TITLE
Fix errors when viewing an order in BackOffice when the language of the order no longer exists

### LINKED ISSUE #22611: Errors when viewing a order in BackOffice when the language of the order no long exists
#### Describe the bug

Hi,
If a order has id_lang with a value that do not correspond to an existent language in a shop, I have the same error reported in https://github.com/PrestaShop/PrestaShop/issues/22215. This is an issue if I remove a language, e.g. Even if I do a brand new installation and remove the English language, I can no longer open any of the pre-installed orders in the BackOffice.

#### Expected behavior

The order should assume the default language of the shop if it's language no longer exists.

#### Steps to Reproduce

1. Make a brand new installation
2. Remove English Language
3. Open any of the pre-installed orders

OR

1. Install a new language
2. Create a order with this language
3. Remove the language
4. Open the order in the BackOffice.

**Screenshots**

The same error happen if I click in this new icon of 1.7.7.
image

#### Additional information

* PrestaShop version: 1.7.7

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | When showing invoice/shipping address of a customer, we used the order lang but if we remove that lang from the store, no fallback was used. This PR aims to use the default store language when the order's one is not available.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22611
| How to test?      | Please see #22611
| Possible impacts? | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22677)

### CODE REVIEW

**Review by Progi1984 — COMMENTED** [review]
Could you add a test ?

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
We should add behats / unit tests :)

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php [hunk 1]
```diff
@@ -73,6 +79,7 @@ public function __construct(
     ) {
         $this->localeRepository = $localeRepository;
         $this->locale = $locale;
+        $this->contextLanguageId = Language::getIdByLocale($this->locale);
```
Comment (PierreRambaud) [inline src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php]: What about using dependency injection instead?

File: src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php [hunk 2]
```diff
@@ -63,16 +64,24 @@ final class GetOrderPreviewHandler implements GetOrderPreviewHandlerInterface
...
     /**
      * @param LocaleRepository $localeRepository
      * @param string $locale
+     * @param int|null $contextLanguageId
      */
     public function __construct(
         LocaleRepository $localeRepository,
-        string $locale
+        string $locale,
+        ?int $contextLanguageId
```
Comment (eternoendless) [inline src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php]: If you want to maintain backwards compatibility
```suggestion
        ?int $contextLanguageId = null
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature [hunk 3]
```diff
@@ -698,3 +698,24 @@ Feature: Order from Back Office (BO)
     And the first invoice from order "bo_order1" should have following shipping tax details:
       | total_tax_excl | rate | total_amount |
       | 7              | 6.00 | 0.42         |
+
+  Scenario: View order passed with a now deleted language
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature]:
```suggestion
  Scenario: View order created on a currently deleted language
```

File: src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php [hunk 4]
```diff
@@ -63,16 +64,24 @@ final class GetOrderPreviewHandler implements GetOrderPreviewHandlerInterface
      */
     private $locale;
 
+    /**
+     * @var int
```
Comment (Progi1984) [inline src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php]:
```suggestion
     * @var int|false|null
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks. Thanks :pray:

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
@PierreRambaud seems like your feedback has been dealt with

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I found some issues on the BO > Order details page:

1. Create a cart rule in the BO > Catalog > Discounts 
2. Go to FO > Log in > Add some products to the cart when the Italian language (for example) is selected
3. Continue checkout 
4. Apply discount
5. Place the order
6. Delete the Italian language
7. Go to BO > Orders > Last order created 
8. Try to update the quantity of a product > see the error
9. Try to update the base price of a product > see the error
image
10. Try to delete a product > see the error 
image
11. Try to add a product > see the error 
image
12. Try to add a discount > see the error
13. Try to delete the cart rule > see the error 
image
14. Try to update the carrier > see the error
15. Try to edit the existing address > see the error
16. Try to select another address > see the error 
17. Go to BO > Customer Service > Merchandise Returns > Enable returns
18. Go to BO > Last order > Try to cancel a product => see error
19. Change the order status to shipped > Try to return a product or try to click on partial refund > see the error

Thank you!

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php [hunk 5]
```diff
@@ -39,13 +39,15 @@
 class OrderCartFeatureContext extends AbstractDomainFeatureContext
 {
     /**
-     * @Given order :orderId has customer :customerId
+     * @Given order :orderReference has customer :customerReference
      *
-     * @param int $orderId
-     * @param int $customerId
+     * @param string $orderId
+     * @param string $customerId
```
Comment (sowbiba) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php]:
```suggestion
     * @param string $orderReference
     * @param string $customerReference
```

File: src/Adapter/ContextStateManager.php [hunk 6]
```diff
@@ -136,8 +136,10 @@ public function setCurrency(?Currency $currency): self
      */
     public function setLanguage(?Language $language): self
     {
-        $this->saveContextField('language');
-        $this->context->language = $language;
+        if (null !== $language->id) {
```
Comment (sowbiba) [inline src/Adapter/ContextStateManager.php]: before this modif, If you called setLanguage(null), the context->language was set to null, now this call will have no effect. Isn't it a BC break ?

Comment (atomiix) [reply src/Adapter/ContextStateManager.php]: You're right, I'm not even checking if `$language` is `null` here 🤔
But I can't find any place where we call this method with `null`. Maybe @jolelievre can give us some insights about why we allow `null` here?

File: classes/ObjectModel.php [hunk 7]
```diff
@@ -261,7 +261,7 @@ public function __construct($id = null, $id_lang = null, $id_shop = null, $trans
 
         if ($id) {
             $entity_mapper = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Adapter\\EntityMapper');
-            $entity_mapper->load($id, $id_lang, $this, $this->def, $this->id_shop, self::$cache_objects);
+            $entity_mapper->load($id, $this->id_lang, $this, $this->def, $this->id_shop, self::$cache_objects);
```
Comment (jolelievre) [inline classes/ObjectModel.php:264]: Bald move! 😅

File: src/Adapter/ContextStateManager.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/ContextStateManager.php]: I don't see any use case for now indeed I think it was a safety because we are not always sure if the injected data is really present or not And in some case we might also want to force the context value to be `null` (To force a behaviour to refill it or to avoid using a contextual value..)

I think it would be preferable not to change this, ideally, especially since all the other setters don't have this behaviour Why did you need this modification by the way?

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 8]
```diff
@@ -218,7 +218,7 @@ private function getOrderCustomer(Order $order): ?OrderCustomerForViewing
         $genderName = '';
 
         if (Validate::isLoadedObject($gender)) {
-            $genderName = $gender->name[$order->id_lang];
+            $genderName = $gender->name[$order->id_lang] ?? $gender->name[$this->contextLanguageId];
```
Comment (jolelievre) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: Just curious, shouldn't your modif in ObjectModel prevent this?

Comment (jolelievre) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: Oh no it only checks if `$id_lang` was provided as a parameter

Then maybe we could force the parameter in `$gender = new Gender($customer->id_gender, $order->id_lang)` However I believe when we specify the lang parameter the multilang fields are not arrays any more but converted into simple strings

So you would need to use `genderName = $gender->name` then. Maybe not the best idea 🤷‍♂️

File: src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/Order/QueryHandler/GetOrderPreviewHandler.php]: Indeed or you need to mark it in the PR description if the modification is mandatory

However I'm not even sure you need to do this, since you already inject the locale from the context in your service definition `"@=service('prestashop.adapter.legacy.context').getContext().language.getLocale()"` Then you can simply use `Language::getIdByLocale($this->locale)` all the time (performance cost for the extra object is probably negligible)

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php [hunk 9]
```diff
@@ -39,13 +39,15 @@
...
-     * @Given order :orderId has customer :customerId
+     * @Given order :orderReference has customer :customerReference
      *
-     * @param int $orderId
-     * @param int $customerId
+     * @param string $orderReference
+     * @param string $customerReference
      */
-    public function orderHasCustomer(int $orderId, int $customerId)
+    public function orderHasCustomer(string $orderReference, string $customerReference)
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php:47]: Lucky you it was not used any more ^^

File: tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature [hunk 10]
```diff
@@ -698,3 +698,24 @@ Feature: Order from Back Office (BO)
...
+    And I add 1 product "Mug The best is yet to come" to the cart "dummy_cart-ES"
+    And I add order "bo_order-ES" with the following details:
+      | cart                | dummy_cart-ES               |
+      | message             |                             |
+      | payment module name | dummy_payment               |
+      | status              | Awaiting bank wire payment  |
+    And I change order "bo_order-ES" shipping address to "test-address"
+    Then order "bo_order-ES" shipping address should be "test-address"
+    And order "bo_order-ES" preview shipping address should have the following details:
+      | country | United States |
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature:717]: What I don't understand is that it's actually never displayed in spanish? How can you tell the `en` language is not used all the time?

File: src/Adapter/ContextStateManager.php (hunk 6 above)
Comment (atomiix) [reply src/Adapter/ContextStateManager.php]: @jolelievre I need this modification because when a language has been deleted, you can create the object `Language` with this `id` of the deleted language, you'll get the object (not `null`), but the `id` will be null. Then, when you try to get a `Currency` object (for instance), you'll have an exception because [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/classes/Currency.php#L251-L253) `$idLang` will be null and [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/classes/Currency.php#L265) it will throw an `out of array` exception.

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php (hunk 9 above)
Comment (atomiix) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php:47]: Yeah, I checked before :)

File: classes/ObjectModel.php (hunk 7 above)
Comment (atomiix) [reply classes/ObjectModel.php:264]: Yeah, but in the end, it makes more sense to me

File: tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature (hunk 10 above)
Comment (atomiix) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature:717]: The purpose of this test is to see if you can display an order created with a currently deleted language (and I assure you, it broke before the modifications ^^), maybe a different test should be written (if not already existing) to check that when you change the default language, it is actually used when creating an order?

File: src/Adapter/ContextStateManager.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/ContextStateManager.php]: Then I'd say the responsibility lies in the hand of the service that use the ContextStateManager, if it's an handler for example then it's the handler which should check that:
- the Language associated to order exists
- if it doesn't fallback to default language
- finally set it in the ContextStateManager

File: classes/ObjectModel.php (hunk 7 above)
Comment (jolelievre) [reply classes/ObjectModel.php:264]: yep, totally

**Review by PierreRambaud — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php (hunk 9 above)
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php:47]:
```suggestion
    public function orderHasCustomer(string $orderReference, string $customerReference): void
```

**Review by Progi1984 — DISMISSED** [review]

File: classes/Cart.php [hunk 11]
```diff
@@ -1655,6 +1655,24 @@ public function updateQty(
         return true;
     }
 
+    /**
+     * Returns the language related to the cart or the default one if deleted
```
Comment (PierreRambaud) [inline classes/Cart.php]: Should it be a method in the ObjectModel instead, by checking if id_lang exists? :thinking:

Comment (PierreRambaud) [reply classes/Cart.php]: (In order to avoid duplicate)

**Review by PierreRambaud — COMMENTED** [review]
Just one comment about duplicate code, but LGTM otherwise :)

File: classes/Cart.php (hunk 11 above)
Comment (atomiix) [reply classes/Cart.php]: I'm not sure, it seems weird to me to have a method `getLanguage()` for an object that doesn't have a Language.

Comment (PierreRambaud) [reply classes/Cart.php]: This is something we already do for:
`getHtmlFields`
 `uploadMultiShopTable`
`getAssociatedShops`
`getWebserviceParameters`
...

There are a lot of generic methods like this :sweat_smile:

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php (hunk 9 above)
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php:47]:
```suggestion
    public function orderHasCustomer(string $orderReference, string $customerReference): void
```

**Review by Progi1984 — DISMISSED** [review]
A small thing but it's approved

**Review by Progi1984 — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I found some issues:

**First issue**
Steps to reproduce:
1. Go to BO > International > Localization > Languages Tab
2. Create a language with incorrect data, for example: 
image 
3. Go to FO > select the language created => see error 
image

**Second issue**

1. Add a new language (Italian for example)
2. Create an order with this language
3. In the Shipping Address select "My carrier"
4. Place Order
3. Delete this language
4. Go to BO > Orders > Last order created 
5. Try to add a product (for example the pack product)
6. See error 
image
7. Try to update the tracking number 
8. See error 
image


Thank you!

**Review by Progi1984 — DISMISSED** [review]

**Comment by atomiix** [comment]
@khouloudbelguith I fixed the 2nd issue but for the first one, I don't think it's related to this PR, it look more like a issue with ps_linklist.

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

>but for the first one, I don't think it's related to this PR, it look more like a issue with ps_linklist.

Yes, you are right, it is a regression into the ps_linklist module, I will create a different issue.

Thank you!

File: classes/order/OrderCarrier.php [hunk 12]
```diff
@@ -126,7 +127,7 @@ public function sendInTransitEmail($order)
             $metadata .= "\n" . '</div>';
         }
 
-        $orderLanguage = new Language((int) $order->id_lang);
+        $orderLanguage = new Language((int) $orderLanguageId);
```
Comment (PierreRambaud) [inline classes/order/OrderCarrier.php:130]:
```suggestion
        $orderLanguage = new Language($orderLanguageId);
```

**Review by PierreRambaud — DISMISSED** [review]
Only one comment, but not mandatory, it's about a double cast :sweat_smile: 
Good job :+1:

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]
Well done @atomiix

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I'm sorry, I found a new issue following these steps:

1. Add a new language (Italian for example)
2. Create a cart rule "free gift" no code
3. Go to FO add any product to the cart when the new language selected
4. Sign in with John Doe
5. Go to the cart page > the gift is well added
6. Sign out
7. Delete the language
8. Go to BO > Orders > Shopping carts > View the last shopping cart created
9. Click on `Create an order from this cart.`
10. See error 

image

**Without PR** we don't have an exception but an error
image


Thank you!

**Review by PierreRambaud — APPROVED** [review]

File: classes/ObjectModel.php [hunk 13]
```diff
@@ -363,6 +363,24 @@ public function getFieldsLang()
...
+     * Returns the language related to the object or the default one if it doesn't exists
+     *
+     * @return Language
+     *
+     * @throws PrestaShopDatabaseException
+     * @throws PrestaShopException
+     */
+    public function getAssociatedLanguage(): Language
+    {
+        $language = new Language($this->id_lang);
```
Comment (jolelievre) [inline classes/ObjectModel.php:376]: I wonder if this should be stored in a field to avoid creating a new Object each time the function is called?

Comment (jolelievre) [reply classes/ObjectModel.php:376]: It could be updated in cas id_lang is changed by checking:

```php
if (null === $this->affectedLanguage || (int) $this->affectedLanguage->getId() !== $this->id_lang)
```

Comment (jolelievre) [reply classes/ObjectModel.php:376]: Oh but this check wouldn't work when the language has been removed since it will never match the default lang id

**Review by jolelievre — DISMISSED** [review]
The modif is legit, just a suggestion for possible performance improvement But not mandatory

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an issue following these steps:

1. Add a new language (Italian for example)
2. Create a cart rule "free gift" no code
3. Go to FO add any product to the cart when the new language selected
4. Create a new customer
5. Go to the cart page > the gift is well added
6. Don't process to checkout (don't select an address)
7. Sign out
8. Delete the language
9. Go to BO > Orders > Shopping carts > View the last shopping cart created
10. Click on Create order from this cart => Redirection to Naw order page
11. Search the customer
12. Use the last shopping cart
13. Try to add an address
14. Save
15. See error

image

PS: if we try with John Doe, when we try to add a new address, no error displayed => but we cannot select the new address added

https://drive.google.com/file/d/1JI4DEHqdqy2-BEOPzsNElig3gyjpaV-L/view?usp=sharing

Previously this step is blocked, can't be tested.

Thank you!

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

The last issue is fixed but the creation of the order is blocked
Steps to reproduce the issue:

1. Add a new language (Italian for example)
2. Create a cart rule "free gift" no code
3. Go to FO add any product to the cart when the new language selected
4. Create a new customer
5. Go to the cart page > the gift is well added
6. Don't process to checkout (don't select an address)
7. Sign out
8. Delete the language
9. Go to BO > Orders > Shopping carts > View the last shopping cart created
10. Click on Create order from this cart => Redirection to Naw order page
11. Search the customer
12. Use the last shopping cart
13. Try to add an address
14. Save
15. Select a carrier, order status & Payment method
16. Click on "Create Order"
17. See the error

image

I found another issue with a customized product

1. Add a new language (Italian for example)
2. Go to FO add a customized product to the cart when the new language selected
3. Sign in
4. Don't process to checkout 
5. Sign out
6. Delete the language
7. Go to BO > Orders > Shopping carts > View the last shopping cart created
8. Click on Create order from this cart => Redirection to Naw order page
image

Thank you!

**Comment by atomiix** [comment]
I feel like this one is the good one 😅

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark:
https://drive.google.com/file/d/1P6Vf3QZXDAGemYjyANlDXvGkFI_eIZ04/view?usp=sharing
https://drive.google.com/file/d/1Ge2DckpVK_Rht1L7M7sbHnzqCPmY2T8z/view?usp=sharing

Tests are ok :heavy_check_mark: 
[Orders.pdf](https://github.com/PrestaShop/PrestaShop/files/6170472/Orders.pdf)

Thank you!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
