### PR TITLE
Fixed the wording translation for Enable/Disable Mobile in Modules page

### LINKED ISSUE #28000: BO - Module Manager - The button Disable mobile is not well displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Modules > Module manager > the button Disable mobile is not well displayed
image

### Expected behavior

image

### Steps to reproduce

1. Go to BO > Modules > Module manager
2. Click on the dropdown next to any module
3. See error the button `Disablemobile` not well displayed

### PrestaShop version(s) where the bug happened

8.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed the wording translation for Enable/Disable Mobile in Modules page (Bug inherited from #27527 (ping @PrestaEdit))
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28000
| How to test?      | Cf. #28000

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28023)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Progi1984 ,

Thanks for the PR !

Could you also change the wording in the alert ?
I should have `Disable Mobile` instead of `DisableMobile`

| What I have | What I should have |
|--|--|
| Screenshot 2022-03-24 at 15 05 59Screenshot 2022-03-24 at 15 06 18 | Screenshot 2022-03-24 at 15 06 42Screenshot 2022-03-24 at 15 06 54 |

Thanks!

File: src/Adapter/Module/AdminModuleDataProvider.php [hunk 1]
```diff
@@ -49,21 +49,45 @@ class AdminModuleDataProvider implements ModuleInterface
...
+        Module::ACTION_INSTALL => Module::ACTION_INSTALL,
+        Module::ACTION_UNINSTALL => Module::ACTION_UNINSTALL,
+        Module::ACTION_ENABLE => Module::ACTION_ENABLE,
+        Module::ACTION_DISABLE => Module::ACTION_DISABLE,
+        Module::ACTION_ENABLE_MOBILE => 'Enable mobile',
+        Module::ACTION_DISABLE_MOBILE => 'Disable mobile',
+        Module::ACTION_RESET => Module::ACTION_RESET,
+        Module::ACTION_UPGRADE => Module::ACTION_UPGRADE,
+        'configure' => 'configure',
+    ];
```
Comment (PululuK) [inline src/Adapter/Module/AdminModuleDataProvider.php]: I don't think it is a good idea to use action key name as label. 
If action key name change Ex.: install -> installModule the action label will be automatically wrong

Comment (Progi1984) [reply src/Adapter/Module/AdminModuleDataProvider.php]: Fixed. Thanks @PululuK

File: src/Adapter/Module/AdminModuleDataProvider.php [hunk 2]
```diff
@@ -49,21 +49,45 @@ class AdminModuleDataProvider implements ModuleInterface
...
+        Module::ACTION_DISABLE_MOBILE => 'Admin.Modules.Feature',
+        Module::ACTION_RESET => 'Admin.Actions',
+        Module::ACTION_UPGRADE => 'Admin.Actions',
         'configure' => 'Admin.Actions',
     ];
 
+    /**
+     * @const array giving a translation label for each module action
+     */
+    public const _ACTIONS_TRANSLATION_LABELS_ = [
```
Comment (atomiix) [inline src/Adapter/Module/AdminModuleDataProvider.php]:
```suggestion
    public const ACTIONS_TRANSLATION_LABELS = [
```

Comment (Progi1984) [reply src/Adapter/Module/AdminModuleDataProvider.php]: Fixed

File: src/Adapter/Module/AdminModuleDataProvider.php [hunk 3]
```diff
@@ -49,21 +49,45 @@ class AdminModuleDataProvider implements ModuleInterface
...
+    public const ACTIONS_TRANSLATION_LABELS = [
+        Module::ACTION_INSTALL => 'Install',
+        Module::ACTION_UNINSTALL => 'Uninstall',
+        Module::ACTION_ENABLE => 'Enable',
+        Module::ACTION_DISABLE => 'Disable',
+        Module::ACTION_ENABLE_MOBILE => 'Enable mobile',
+        Module::ACTION_DISABLE_MOBILE => 'Disable mobile',
+        Module::ACTION_RESET => 'Reset',
+        Module::ACTION_UPGRADE => 'Upgrade',
+        'configure' => 'Configure',
```
Comment (jolelievre) [inline src/Adapter/Module/AdminModuleDataProvider.php]: I think it would be really interesting to add a `Module::CONFIGURE` const, this is used for module configurations (it replaces the Update permission basically)

File: src/Adapter/Module/AdminModuleDataProvider.php [hunk 4]
```diff
@@ -49,21 +49,45 @@ class AdminModuleDataProvider implements ModuleInterface
...
-    protected $moduleActions = ['install', 'uninstall', 'enable', 'disable', 'enableMobile', 'disableMobile', 'reset', 'upgrade'];
+    protected $moduleActions = [
+        Module::ACTION_INSTALL,
+        Module::ACTION_UNINSTALL,
+        Module::ACTION_ENABLE,
+        Module::ACTION_DISABLE,
+        Module::ACTION_ENABLE_MOBILE,
+        Module::ACTION_DISABLE_MOBILE,
+        Module::ACTION_RESET,
+        Module::ACTION_UPGRADE,
```
Comment (jolelievre) [inline src/Adapter/Module/AdminModuleDataProvider.php:89]: I'm surprised configure is not among these ones though 🤷‍♂️

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984 

All good for me, although adding the configure const would be a nice extra improvement for this PR

File: src/Adapter/Module/AdminModuleDataProvider.php (hunk 3 above)
Comment (Progi1984) [reply src/Adapter/Module/AdminModuleDataProvider.php]: Fixed

File: src/Adapter/Module/AdminModuleDataProvider.php (hunk 4 above)
Comment (Progi1984) [reply src/Adapter/Module/AdminModuleDataProvider.php:89]: Fixed

**Review by NeOMakinG — APPROVED** [review]
front lgtm

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Tested : Install, Uninstall, Disable, Enable, Reset, Enable Mobile, Disable Mobile on native and non-native modules.
Action works well, error message is correct.

LGTM, QA ✅ !

**Comment by Progi1984** [comment]
Thanks @florine2623
