### PR TITLE
Fix missing id_guest in cookie

### LINKED ISSUE #28336: "Re-display cart at login" feature is not working properly
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

**"Shop Parameters > Customer Settings > Re-display cart at login"** feature is not working properly when enabled

Similar issue to unreproduced #23635, but I checked carefully and the bug is alive and with us in PS 1.7.8.5.

### Expected behavior

An abandoned cart should be recovered and displayed properly when a customer re-logins. 

### Steps to reproduce

1. Enable **_Shop Parameters > Customer Settings > Re-display cart at login_**
2. Login as customer and add a product to the cart
3. Logout
4. Login again and see cart is not recovered / shown.

### PrestaShop version(s) where the bug happened

1.7.8.5

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Seb33300**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When cookie is created, `id_guest` is missing.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28336.
| Related PRs       |
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/28336#issuecomment-1169002509
| Possible impacts? |

### CODE REVIEW

File: classes/Context.php [hunk 1]
```diff
@@ -350,13 +350,15 @@ public function updateCustomer(Customer $customer)
         $customer->logged = 1;
         $this->cookie->email = $customer->email;
         $this->cookie->is_guest = $customer->isGuest();
+        Guest::setNewGuest($this->cookie);
```
Comment (matthieu-rolland) [inline classes/Context.php]: I'm not so familiar with this, could you please explain why this should be done outside of the `else` condition ?

Comment (Seb33300) [reply classes/Context.php]: This `setNewGuest` method is used to save `id_guest` into the cookie.

In the `else`, we assign the `id_guest` to the newly created cart (created when the user was not logged in yet).

In the `if`, we retrieve an existing cart which already have an `id_guest`

Comment (Seb33300) [reply classes/Context.php]: I may need to reassign the `id_guest` from the cart in the `if` and move the `setNewGuest` method call into the `else`.

I will test it tomorrow.

Comment (Seb33300) [reply classes/Context.php]: Fixed

**Comment by kpodemski** [comment]
Hi @Seb33300 

Your fix makes sense. As it is not regression, could you rebase it to `develop` branch?

**Comment by Seb33300** [comment]
Hello @kpodemski 

The ticket I fix with this PR is a regression introduced in 1.7.7 branch

**Comment by kpodemski** [comment]
@Seb33300

We would put it in 1.7.8 if it was 1.7.8 that introduces regression 👍 otherwise we could release a patch version, after patch version, after patch version... :)

**Comment by Seb33300** [comment]
If we merge in develop, this bug will not be fixed until PrestaShop 8.1 will be released (2023/2024) !?

**Comment by matks** [comment]
> If we merge in develop, this bug will not be fixed until PrestaShop 8.1 will be released (2023/2024) !?

The bug is fixed on a shop as soon as the code on the shop server is patched. You do not need to wait for PS 8.1 to be released to apply the bugfix on a shop 😉 .

**Comment by Seb33300** [comment]
Honestly, I don't get the point of delaying the release of **a bugfix**.

I am coming from Symfony ecosystem where all bugfixes without breaking change are merged ASAP.
https://symfony.com/doc/current/contributing/code/pull_requests.html#choose-the-right-branch

Delaying the bugfix to PrestaShop 8.1 will result in a bad customer experience for at least 1 more year for those affected by this bug. People will continue to report it, resulting in more work for your QA team to handle created issues.

Yes, we can patch our shop in the meantime, but for this we need:
- to be a developer (many people using prestashop are not developers)
- have the knowledge to do it properly (using override or module to prevent to lose the patch after a prestashop upgrade)

So, patching PrestaShop is not something trivial and I do it only for blocking issues.
Because I am managing multiple shops for several customers and I cannot take time to patch any single bug in all shops 1 by 1.

Upgrading PrestaShop is something that everyone can do thanks to the upgrade module.
In my case, PrestaShop upgrade are automatically handled by my CI/CD process.

My point is not related to this issue only. This is not the first time I see a PrestaShop bugfix delayed to develop branch. And this always makes me sad.

**Review by zuk3975 — DISMISSED** [review]

**Comment by Seb33300** [comment]
Rebased on develop

**Comment by matks** [comment]
> Honestly, I don't get the point of delaying the release of **a bugfix**.

It is very expensive to build, test and publish a new prestashop version. It requires multiple people working multiple days on it. Any addition (bug fixes included) to a release makes it bigger, and make the releasing work more complex, longer and makes the risk of introducing a blocking bug (a bug that makes it impossible to release so we need to fix it) higher.

So in order to be able to regularly deliver patch versions to the prestashop users, we needed to find a system "what do we add to a patch version, what do we add to the next version" that works with our resources and our team. If we put more stuff into patch releases, this will be too big for the project team to handle and the prestashop users will have _no more_ patch versions.

I am sorry 🤷‍♀️ but it's very expensive to build, test and publish a new prestashop version. So we do what we can.

If you want this to change I think you can support us by sending us money 😄

**Comment by matks** [comment]
I close and re-open the PR to reset the CI.

**Review by kpodemski — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Comment by rozwell** [comment]
Works fine on 1.7.8.7, thank you! 😃

**Review by sLorenzini — APPROVED** [review]
hello @Seb33300,

Thank you for this PR.
Tested on develop & 8.0.x branches and PHP 7.3.

"Re-display cart at login" option works fine. We can add a product to cart, sign in & sign out and keep this product to the cart after re-login:

display-cart-login-BO

[display-cart-login-FO.webm](https://user-images.githubusercontent.com/2854834/197789236-35ccbe2a-22ab-4976-bf5a-115672907ccd.webm)

QA approved ✅ 
Thanks

**Comment by kpodemski** [comment]
Thank you @Seb33300 🎉
