### PR TITLE
Fix A pack set to Decrement products in pack only. cannot be added to cart

### LINKED ISSUE #35366: `available_quantity` coming from `Cart::getProducts()` is 0 for packs
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you create a product pack and set it's stock type to `Decrement products in pack only.` (`PackStockType::STOCK_TYPE_PRODUCTS_ONLY`), it doesn't work in cart.

### Expected behavior

It should provide a value of stock quantity of this pack.
The problem is that it uses available_quantity from the raw query, not a calculated value for the pack.

### Steps to reproduce

0. Open `themes\classic\templates\checkout\_partials\cart-detailed-product-line.tpl` and add `Stock: {$product.quantity_available}` somewhere you can see it.
1. Create pack of two standard products, 1 piece of each.
2. Set stock quantity of these two products to 100 each.
3. Go back to the pack, set quantity of the pack to 1, so you can add it to cart. (...another bug), set `Pack quantities` to `Decrement products in pack only`.
4. Go to FO, add this pack to cart, go to checkout and see that the stock is 1, but it should be 100.

### PrestaShop version(s) where the bug happened

1.7.6 - develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### LINKED ISSUE #35367: A pack set to `Decrement products in pack only.` cannot be added to cart
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you create a product pack and set it's stock type to `Decrement products in pack only.` (`PackStockType::STOCK_TYPE_PRODUCTS_ONLY`) and the quantity of the pack is zero, **it cannot be added to cart**.

### Expected behavior

You MUST be able to add this product to cart even if the quantity is zero.
It worked properly on 1.7.6.

### Steps to reproduce

1. Create pack of two standard products, 1 piece of each.
2. Set stock quantity of these two products to 100 each.
3. Go back to the pack, set quantity of the pack to 0, set `Pack quantities` to `Decrement products in pack only`, disable ordering when not in stock.
4. Go to FO and try to add it to cart.
5. Can't be added to cart and no error message is shown. 🔴 
6. Product page shows quantity 0 or nothing, it should show the quantity. 🔴 

### PrestaShop version(s) where the bug happened

broken on 8.1.3, works properly on 1.7.6

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | When you create a product pack and set it's stock type to Decrement products in pack only. (PackStockType::STOCK_TYPE_PRODUCTS_ONLY) and the quantity of the pack is zero, it cannot be added to cart. The PR also fixes `available_quantity` variable in cart products.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Auto test | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/8038868360
| How to test? | 1. Create pack of two standard products, 1 piece of each. <br>2. Set stock quantity of these two products to 100 each. <br>3. Go back to the pack, set quantity of the pack to 0, set Pack quantities to Decrement products in pack only. <br>4. Go to FO and try to add it to cart.
| Fixed issue or discussion?     | Fixes #35367, Fixes #35366
| Sponsor company   | Codencode snc

### Known issues
When you put both pack and the single products into cart, the ordering is successfully blocked, the error message is not correct and reports the available quantity of the pack. Fixing this will need another batch of thoughts and some BC breaks probably. A workaround would be something like `if available_quantity >= quantityincart`, then error message `"With the current products in your cart, pack is not available in this quantity."`. Saying the true reason would be better, but much more complicated.

Snímek obrazovky 2024-02-25 155450

### CODE REVIEW

**Comment by MatShir** [comment]
I'm adding waiting for PM to the PR, the specs are being reviewed 🤗

**Comment by Codencode** [comment]
Thank you @MatShir!

**Comment by MatShir** [comment]
Do you take the lowest quantity between the products in the pack?

**Comment by Codencode** [comment]
> Do you take the lowest quantity between the products in the pack?

Yes, it is the `Product::getQuantity()` method that does this as it checks if the item is a pack, while `StockAvailable::getQuantityAvailableByProduct()` does not check this.

**Comment by MatShir** [comment]
Perfect thanks for your quick reply and your time 🙏

**Comment by Codencode** [comment]
You're welcome, it's a pleasure to participate in the project, also because I use Prestashop to create e-commerce.

**Review by matthieu-rolland — COMMENTED** [review]
Just to be sure I understand, as I'm not familiar with this:

When a pack is `set to Decrement products in pack only`, (`PackStockType::STOCK_TYPE_PRODUCTS_ONLY`),  it means the quantities that matter are the product quantities, and not the pack quantities ? 

And so if let's say we have many Product A and Product B, but zero pack of A+B, we should still be able to order a pack A+B ?

**Comment by MatShir** [comment]
> And so if let's say we have many Product A and Product B, but zero pack of A+B, we should still be able to order a pack A+B ?

Yes and only Product A and Product B stocks will be decreased

**Comment by matthieu-rolland** [comment]
wait, why are there two PRs mentionning the same bug ? https://github.com/PrestaShop/PrestaShop/pull/35379

**Comment by Codencode** [comment]
> wait, why are there two PRs mentionning the same bug ? #35379

Hi @matthieu-rolland,
PR #35379 is slightly different and fixes a similar bug but is still different.

- #35379 FIXES #35366
- #35372 FIXES #35367

**Comment by Hlavtox** [comment]
@matthieu-rolland @MatShir The second PR is about the same topic, but different place in the code. And it doesnt effect anything on default themes. And its not a regression.

This one is what is important. 👍

I will check it tommorow and compare with some older version. It works properly on 1.7.6…

**Review by jolelievre — COMMENTED** [review]
Hi @Codencode 

thanks for the fix, but something is bothering me in your fix you don't seem to check the type of stock set on the Pack, so I trust that this fixes the use case `Decrement products in pack only.` but isn't it forcing the behaviour for all kinds of pack regardless of their config?

**Comment by kpodemski** [comment]
Also, please take a look at this PR https://github.com/PrestaShop/PrestaShop/pull/15623 from @matks 

There was a change here for a reason. This also explains why packs stopped working after 1.7.7, just as @Hlavtox suggested.

**Comment by Hlavtox** [comment]
~@kpodemski There must be some other issue also, because `$product.quantity` is not correct also on the product page.~

Not true

**Comment by Codencode** [comment]
Could we think of using `Product::getQuantity()` only in case of package?
So do like this:
```
        if (Pack::isPack((int) $this->id_product)) {
            // Check if this pack is out-of-stock
            $availableProductQuantity = Pack::getQuantity(
                $this->id_product,
                $this->id_product_attribute,
                null,
                null,
                $this->customization_id
            );
        } else {
            // Check if this product is out-of-stock
            $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
                $this->id_product,
                $this->id_product_attribute
            );
        }
```

**Comment by kpodemski** [comment]
@Codencode yep, it makes more sense, in my opinion

We need to be very careful with such changes.

But please do not take my word for granted; my suggestion may not be a 100% solution. Eventually, we have to test all the scenarios related to product stocks.

**Comment by Codencode** [comment]
@kpodemski ok,

I made the change locally and tested the following 4 scenarios:

### Scenario 1
- Product 1: 90 qty
- Product 2: 2 qty
- Pack: 2 qty
- Pack: Decrement product in pack only
- Cart: add to cart 1 pack


### Scenario 2
- Product 1: 90 qty
- Product 2: 2 qty
- Pack: 2 qty
- Pack: Decrement product in pack only
- Cart: add to cart 2 pack

### Scenario 3
- Product 1: 90 qty
- Product 2: 2 qty
- Pack: 2 qty
- Pack: Decrement Both
- Cart: add to cart 2 pack

### Scenario 4
- Product 1: 90 qty
- Product 2: 2 qty
- Pack: 2 qty
- Pack: Decrement pack only
- Cart: add to cart 2 pack


### Code
```
        if (Pack::isPack((int) $this->id_product)) {
            // Check if this pack is out-of-stock
            $availableProductQuantity = Pack::getQuantity(
                $this->id_product,
                $this->id_product_attribute,
                null,
                null,
                $this->customization_id
            );
        } else {
            // Check if this product is out-of-stock
            $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
                $this->id_product,
                $this->id_product_attribute
            );
        }
```


And these are the recordings

### Scenario 1
https://github.com/PrestaShop/PrestaShop/assets/2463965/fd2d783e-be63-4ada-981f-25e3242315b7

### Scenario 2
https://github.com/PrestaShop/PrestaShop/assets/2463965/f315380d-0ab0-45aa-999d-9c8080a26e4a

### Scenario 3
https://github.com/PrestaShop/PrestaShop/assets/2463965/e941521a-5e24-4056-bb88-7383052a3051

### Scenario 4
https://github.com/PrestaShop/PrestaShop/assets/2463965/37770b49-dbe2-428e-9acb-d5c4045cc5f4

**Comment by Codencode** [comment]
If anyone can think of anything else to try I can do it.
@Hlavtox, is the change ok for you?

I also edited the comment
`product quantity is the available quantity after decreasing products in cart` => `Check if this pack is out-of-stock`

File: classes/Cart.php [hunk 1]
```diff
@@ -4083,7 +4083,8 @@ public function checkQuantities($returnProductOnFailure = false)
             if (
                 !$product['active'] ||
                 !$product['available_for_order'] ||
-                (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity'])
+                (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity']) &&
```
Comment (Hlavtox) [inline classes/Cart.php]: @Codencode This won't work, we can't just check if the product is a pack. I think that we can just delete this line and keep just `!$product['active'] || !$product['available_for_order']`, because the quantity is checked on the line below. :-)

**Comment by Hlavtox** [comment]
@Codencode I checked the code myself and there are multiple places where `StockAvailable::getQuantityAvailableByProduct` is used.

**I think that we need to use Product::getQuantity here for it to work:**

https://github.com/PrestaShop/PrestaShop/blob/20ef5dbbb70f83968cd3f7ca44d47aae72e366a9/controllers/front/CartController.php#L606 (you did it here)

https://github.com/PrestaShop/PrestaShop/blob/20ef5dbbb70f83968cd3f7ca44d47aae72e366a9/controllers/front/CartController.php#L434

https://github.com/PrestaShop/PrestaShop/blob/20ef5dbbb70f83968cd3f7ca44d47aae72e366a9/controllers/front/CartController.php#L521

File: classes/Cart.php (hunk 1 above)
Comment (Codencode) [reply classes/Cart.php]: @Hlavtox,

just to make sure I understand,
would you do it like this?
```
            if (
                !$product['active'] ||
                !$product['available_for_order']
            ) {
                return $returnProductOnFailure ? $product : false;
            }
```

I did a test and it's actually correct, it works

**Comment by Codencode** [comment]
> @Codencode I checked the code myself and there are multiple places where `StockAvailable::getQuantityAvailableByProduct` is used.
> 
> **I think that we need to use Product::getQuantity here for it to work:**
> 
> https://github.com/PrestaShop/PrestaShop/blob/20ef5dbbb70f83968cd3f7ca44d47aae72e366a9/controllers/front/CartController.php#L606
> 
> (you did it here)
> https://github.com/PrestaShop/PrestaShop/blob/20ef5dbbb70f83968cd3f7ca44d47aae72e366a9/controllers/front/CartController.php#L434
> 
> https://github.com/PrestaShop/PrestaShop/blob/20ef5dbbb70f83968cd3f7ca44d47aae72e366a9/controllers/front/CartController.php#L521

Yes you are right,
but do I insert the check in all three to check if it is a pack?

as I proposed here: https://github.com/PrestaShop/PrestaShop/pull/35372#issuecomment-1953781754


If it goes well I make both changes and upload the commit

**Comment by matthieu-rolland** [comment]
> but do I insert the check in all three to check if it is a pack?

@Codencode shouldn't you check that it's a pack **but also** that it's of type `Decrement products in pack only` ?

File: classes/Cart.php (hunk 1 above)
Comment (Hlavtox) [reply classes/Cart.php]: Yes, because the actual stock is checked few lines below it. ;-)

**Comment by kpodemski** [comment]
@matthieu-rolland these checks are inside `Pack::getQuantity`

File: classes/Cart.php (hunk 1 above)
Comment (Codencode) [reply classes/Cart.php]: Ok done.

What about that other comment? https://github.com/PrestaShop/PrestaShop/pull/35372#issuecomment-1956177017

I can proceed?

**Comment by Hlavtox** [comment]
@Codencode We can use `Product::getQuantity`, it will do everything automatically. :-)

Just make sure to PASS or NOT PASS the `$cart` variable and `$id_customization` properly.

Also, one more scenario, not sure if it's handled:
- I have Product A 100 pcs
- I have Product B 100 pcs
- I make Pack A and Pack B with these products. Both with `Decrement products in pack only`.
- I add both packs to cart 51 pieces, what happens? :D

**Comment by matthieu-rolland** [comment]
@Codencode I think you can go ahead with your solution.

**Comment by Codencode** [comment]
@Codencode We can use `Product::getQuantity`, it will do everything automatically. :-)~
> 
> Just make sure to PASS or NOT PASS the `$cart` variable and `$id_customization` properly.
> 
> Also, one more scenario, not sure if it's handled:
> 
> * I have Product A 100 pcs
> * I have Product B 100 pcs
> * I make Pack A and Pack B with these products. Both with `Decrement products in pack only`.
> * I add both packs to cart 51 pieces, what happens? :D

~In this case the system still lets you add to the (wrong) cart, but on the cart page it shows you the error and doesn't let you continue with the order.
I think the problem is in the `ProductLazyArray::shouldEnableAddToCartButton()` method.~


https://github.com/PrestaShop/PrestaShop/assets/2463965/af83e728-6421-4a66-aca0-1f98fadca916


~Now I'll make the changes I've made so far and then I'll see if I can figure out how to solve this other problem~

Not true

**Comment by Hlavtox** [comment]
@Codencode You rock 🎸 lets go

**Comment by Codencode** [comment]
> @Codencode You rock 🎸 lets go

I made the changes, maybe when you can do some checks?
Greazie.

As soon as possible I'll try to understand how to solve the problem of the scenario you presented.

**Comment by Hlavtox** [comment]
Looks good, but really, you can simplify it. You can just use this everywhere. Inside of that method, it checks if it's a pack and automatically calls Pack::getQuantity. :-) See here - https://github.com/PrestaShop/PrestaShop/blob/8.1.x/classes/Product.php#L4333

```php
Product::getQuantity(
  $this->id_product,
  $this->id_product_attribute,
);
```

**Comment by Codencode** [comment]
> Looks good, but really, you can simplify it. You can just use this everywhere. Inside of that method, it checks if it's a pack and automatically calls Pack::getQuantity. :-) See here - https://github.com/PrestaShop/PrestaShop/blob/8.1.x/classes/Product.php#L4333
> 
> ```
> Product::getQuantity(
>   $this->id_product,
>   $this->id_product_attribute,
> );
> ```
You're right, and initially I did it that way, but in this comment (https://github.com/PrestaShop/PrestaShop/pull/35372#pullrequestreview-1889820512) I understood that it was better to check if it was a pack and so I thought I'd add the check.

Do you think it's better to remove it?

**Comment by Hlavtox** [comment]
@Codencode The comment was misunderstood or about something else I think. `Product::getQuantity` should work and be the easiest way. 👍 I briefly tested it and it worked fine.

**Comment by kpodemski** [comment]
@Hlavtox 

What about this bug that was fixed by Mathieu? https://github.com/PrestaShop/PrestaShop/pull/15623

**Comment by Hlavtox** [comment]
@kpodemski It will still work, `Product::getQuantity` with no `$cart` passed will have the same result.

**Comment by Hlavtox** [comment]
@Codencode Please rebase the PR. ;-)

**Comment by Codencode** [comment]
@Hlavtox,
I made the change by removing unnecessary controls in the CartController.php file and ran the rebase
I hope I did everything right as I'm still not sure how to rebase properly.

**Comment by Codencode** [comment]
> @Codencode We can use `Product::getQuantity`, it will do everything automatically. :-)~
> 
> > Just make sure to PASS or NOT PASS the `$cart` variable and `$id_customization` properly.
> > Also, one more scenario, not sure if it's handled:
> > 
> > * I have Product A 100 pcs
> > * I have Product B 100 pcs
> > * I make Pack A and Pack B with these products. Both with `Decrement products in pack only`.
> > * I add both packs to cart 51 pieces, what happens? :D
> 
> ~In this case the system still lets you add to the (wrong) cart, but on the cart page it shows you the error and doesn't let you continue with the order. I think the problem is in the `ProductLazyArray::shouldEnableAddToCartButton()` method.~
> 
>  2024-02-22-17-56-37_XHswmHyg.mp4 
> ~Now I'll make the changes I've made so far and then I'll see if I can figure out how to solve this other problem~
> 
> Not true

@Hlavtox,
I tested this scenario again and the problem does not occur.
I don't know why it gave me an error, maybe I had done something wrong in the code.
To be safe, I also wrote the text on a new site by applying the patch and this error does not occur.

So for me the patch is ok.

I await your feedback.

File: controllers/front/CartController.php [hunk 2]
```diff
@@ -599,11 +607,15 @@ protected function shouldAvailabilityErrorBeRaised($product, $qtyToCheck)
...
-        // Check if this product is out-of-stock
-        $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+        // Check if this pack is out-of-stock
+        $availableProductQuantity = Pack::getQuantity(
             $this->id_product,
-            $this->id_product_attribute
+            $this->id_product_attribute,
+            null,
+            null,
+            $this->customization_id
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
```

File: controllers/front/CartController.php [hunk 3]
```diff
@@ -599,11 +607,15 @@ protected function shouldAvailabilityErrorBeRaised($product, $qtyToCheck)
             return false;
         }
 
-        // Check if this product is out-of-stock
-        $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+        // Check if this pack is out-of-stock
+        $availableProductQuantity = Pack::getQuantity(
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
        $availableProductQuantity = Product::getQuantity(
```

File: controllers/front/CartController.php [hunk 4]
```diff
@@ -599,11 +607,15 @@ protected function shouldAvailabilityErrorBeRaised($product, $qtyToCheck)
             return false;
         }
 
-        // Check if this product is out-of-stock
-        $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+        // Check if this pack is out-of-stock
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
        // Check if this product is out-of-stock
```

File: controllers/front/CartController.php [hunk 5]
```diff
@@ -521,10 +525,14 @@ protected function processChangeProductInCart()
...
                 );
             } elseif ($this->shouldAvailabilityErrorBeRaised($product, $qty_to_check)) {
-                $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+                $availableProductQuantity = Pack::getQuantity(
                     $this->id_product,
-                    $this->id_product_attribute
+                    $this->id_product_attribute,
+                    null,
+                    null,
+                    $this->customization_id
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
```

File: controllers/front/CartController.php [hunk 6]
```diff
@@ -521,10 +525,14 @@ protected function processChangeProductInCart()
                     'Shop.Notifications.Error'
                 );
             } elseif ($this->shouldAvailabilityErrorBeRaised($product, $qty_to_check)) {
-                $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+                $availableProductQuantity = Pack::getQuantity(
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
                $availableProductQuantity = Product::getQuantity(
```

File: controllers/front/CartController.php [hunk 7]
```diff
@@ -430,10 +430,14 @@ protected function processChangeProductInCart()
...
         // Check product quantity availability
         if ('update' !== $mode && $this->shouldAvailabilityErrorBeRaised($product, $qty_to_check)) {
-            $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+            $availableProductQuantity = Pack::getQuantity(
                 $this->id_product,
-                $this->id_product_attribute
+                $this->id_product_attribute,
+                null,
+                null,
+                $this->customization_id
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
```

File: controllers/front/CartController.php [hunk 8]
```diff
@@ -430,10 +430,14 @@ protected function processChangeProductInCart()
 
         // Check product quantity availability
         if ('update' !== $mode && $this->shouldAvailabilityErrorBeRaised($product, $qty_to_check)) {
-            $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
+            $availableProductQuantity = Pack::getQuantity(
```
Comment (Hlavtox) [inline controllers/front/CartController.php]:
```suggestion
            $availableProductQuantity = Product::getQuantity(
```

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
The PR is rebased and ready. I fixed all scenarios and it works correctly.

Although with a bad error message, it handles also the scenario when there is a combination of packs/products in the cart and prevents ordering it. 👍

Auto tests: https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/8038868360

**Review by ShaiMagal — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @Codencode @Hlavtox - I think this solution should work as expected :)

File: classes/Cart.php [hunk 9]
```diff
@@ -755,6 +755,19 @@ public function getProducts($refresh = false, $id_product = false, $id_country =
...
+                 * in them. The quantity in stock_available then has no meaning and could be always zero.
+                 *
+                 * When calling Pack::getQuantity here, you MUST use null for $cart parameter. Otherwise it
+                 * will subtract the quantity that is already in the cart. Basically resulting in a nonsense,
+                 * half of quantity you have. We need the REAL quantity.
+                 */
+                if (Pack::isPack($product['id_product'])) {
+                    $product['quantity_available'] = Pack::getQuantity((int) $product['id_product'], (int) $product['id_product_attribute']);
+                }
+
```
Comment (Hlavtox) [inline classes/Cart.php:770]: This portion of the code is only used in error message in the default theme. And since we are not passing a cart, the result will be the same.

We could theoretically just use `Product::getQuantity((int) $product['id_product'], (int) $product['id_product_attribute'])` here, but why to fetch it one more time, when it would get us the exact same thing as we have. :-)

File: classes/Cart.php [hunk 10]
```diff
@@ -4088,8 +4101,7 @@ public function checkQuantities($returnProductOnFailure = false)
              */
             if (
                 !$product['active'] ||
-                !$product['available_for_order'] ||
-                (!$product['allow_oosp'] && $product['stock_quantity'] < $product['cart_quantity'])
```
Comment (Hlavtox) [inline classes/Cart.php:4092]: This piece of code is not needed, because it uses only the quantity from stock_available. We need the live one, which is checked few lines below, properly. Because we pass $this (Cart) also, it also checks the amount of products in cart in deep_quantity.

File: controllers/front/CartController.php [hunk 11]
```diff
@@ -434,14 +434,8 @@ protected function processChangeProductInCart()
...
              * No subtracting of quantity in the cart here.
-             *
-             * @todo StockAvailable::getQuantityAvailableByProduct does not work for packs
-             * which depend on quantity of products inside.
              */
-            $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
-                $this->id_product,
-                $this->id_product_attribute
-            );
+            $availableProductQuantity = Product::getQuantity($this->id_product, $this->id_product_attribute);
```
Comment (Hlavtox) [inline controllers/front/CartController.php:438]: This code is just for purposes of getting stock quantity to the error message. Has no functional meaning. We are not passing a cart or customization, so in case of normal products, it will get us the same number as `StockAvailable::getQuantityAvailableByProduct`.

File: controllers/front/CartController.php [hunk 12]
```diff
@@ -533,14 +527,8 @@ protected function processChangeProductInCart()
...
                  * No subtracting of quantity in the cart here.
-                 *
-                 * @todo StockAvailable::getQuantityAvailableByProduct does not work for packs
-                 * which depend on quantity of products inside.
                  */
-                $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
-                    $this->id_product,
-                    $this->id_product_attribute
-                );
+                $availableProductQuantity = Product::getQuantity($this->id_product, $this->id_product_attribute);
```
Comment (Hlavtox) [inline controllers/front/CartController.php:531]: This code is just for purposes of getting stock quantity to the error message. Has no functional meaning. We are not passing a cart or customization, so in case of normal products, it will get us the same number as `StockAvailable::getQuantityAvailableByProduct`.

File: controllers/front/CartController.php [hunk 13]
```diff
@@ -617,14 +606,8 @@ protected function shouldAvailabilityErrorBeRaised($product, $qtyToCheck)
...
          * We check if this product is out-of-stock.
-         *
-         * @todo StockAvailable::getQuantityAvailableByProduct does not work for packs
-         * which depend on quantity of products inside.
          */
-        $availableProductQuantity = StockAvailable::getQuantityAvailableByProduct(
-            $this->id_product,
-            $this->id_product_attribute
-        );
+        $availableProductQuantity = Product::getQuantity($this->id_product, $this->id_product_attribute);
```
Comment (Hlavtox) [inline controllers/front/CartController.php:610]: This is actually the real fix. Product::getQuantity is just a "passthrough" to `StockAvailable::getQuantityAvailableByProduct` for normal products, but will provide a proper pack quantity. 👍

The change is safe, we are not passing a cart or customization.

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Codencode** [comment]
@Hlavtox,
You fixed everything!
Great work and thanks!

**Review by AureRita — APPROVED** [review]
Hi @Codencode 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(115).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/4a490ec1-f2a4-43b0-86b4-200f2e7569e1)


Link to the auto test : https://github.com/AureRita/testing_pr/actions/runs/8051172398

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by Hlavtox** [comment]
Thanks guys! 

@Codencode Next step for us is to improve the error message when there is both pack and normal products, or multiple packs. Something like "You can only buy total of X Product A, adjust the quantity of the product or packs that contain it, to continue."
