### PR TITLE
Fix count query with customer filter

### LINKED ISSUE #18263: BO - Order page - an exception is displayed after filter with a customer
#### Describe the bug

In the BO => Order page => (migrated), an exception is displayed when we filter by a customer 

#### Expected behavior

It should be ok

#### Steps to Reproduce

1. Go to BO => Orders page
2. Filter by a customer
3. See error

**Screenshots**
image
[Orders • 177x.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4368045/Orders.177x.webm.zip)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In the order pages, an error was thrown when filtering by customer. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18263
| How to test?  | 1. Go to BO => Orders page<br>2. Filter by a customer<br>3. No error should be thrown and the number of orders (the title of the section) should match the number of orders in the list

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18305)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

The filter is OK, but the count of orders is still KO : Sometimes it displays the total number of orders (6 in my example below), sometimes it displays 0.

See screenrecord : 
https://drive.google.com/file/d/1szKyRtqu7lBp2B5kRqG37M2uCx1-WT9Z/view?usp=sharing

File: src/Core/Grid/Query/OrderQueryBuilder.php [hunk 1]
```diff
@@ -115,11 +116,13 @@ public function getCountQueryBuilder(SearchCriteriaInterface $searchCriteria)
     {
         $qb = $this->getBaseQueryBuilder($searchCriteria->getFilters());
         if (isset($searchCriteria->getFilters()['new'])) {
-            $qb = $this->addNewCustomerField($qb->addSelect('o.id_order as o_id_order'));
+            $this->addCustomerField($qb);
```
Comment (Progi1984) [inline src/Core/Grid/Query/OrderQueryBuilder.php]: May be could you put this call outside the `if` because it is called in two cases (if/else).

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Thanks @atomiix

**Comment by Progi1984** [comment]
Thanks @atomiix
