### PR TITLE
BO : Fixed anchor target for modules page

### LINKED ISSUE #29453: BO - Page configuration - "See all theme's modules" button doesn't filter the Theme category correctly
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This should be filtered on "Theme modules" instead of "All categories"

https://user-images.githubusercontent.com/16019289/186911847-0abd384d-f914-4f1f-897e-9eb4189bf856.mov

Tested on 1.7.8.7, same bug is present

### Expected behavior

When I click on this button, I should have the list of modules filtered on automatically.

### Steps to reproduce

1. Go to BO > Design > Theme & logo > tab Pages Configuration
2. Click on button See all theme's modules
3. See in modules list that it is not filtered

### PrestaShop version(s) where the bug happened

8.0.0, 1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #35204: BO - Theme & logo - Button See all theme's modules redirects to All modules
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I click on See all theme's module, all the modules are displayed, not only the ones concerning the theme.

https://github.com/PrestaShop/PrestaShop/assets/16019289/44473cad-952d-4ae9-b204-46d7e130284e

### Expected behavior

I should be redirected to the category Theme modules

### Steps to reproduce

1. Go to BO > Design > Theme & Logo 
2. Tab Pages Configuration > Scroll down > Click See all theme's modules
3. You are redirected to Module Manager page
4. The Category should be selected to Themes modules directly :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | BO : Fixed anchor target for modules page
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle: 
| UI Tests          | https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19331758841
| Fixed issue or discussion?     | Fixes #29453
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

### CODE REVIEW

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

**Review by kpodemski — DISMISSED** [review]

**Review by Codencode — DISMISSED** [review]

**Review by Touxten — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 1]
```diff
@@ -1004,6 +1004,28 @@ class AdminModuleController {
...
+        // Change dropdown label to set it to the current category's displayname
+        $(self.categorySelectorLabelSelector).text(jqoCategory.data('category-display-name'));
+        $(self.categoryResetBtnSelector).show();
+        self.updateModuleVisibility();
+      } else {
+        self.updateModuleVisibility();
+      }
+    } else {
+      self.updateModuleVisibility();
+    }
```
Comment (Quetzacoalt91) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: What about

```suggestion
      }
    }
    self.updateModuleVisibility();
```

?

The method will always be called from my understanding.

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Oh my god. Thanks for review.

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Fixed

**Comment by Progi1984** [comment]
Ping @kpodemski @Codencode @Touxten : Fixed feedbacks from @Quetzacoalt91

**Review by Codencode — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Progi1984, 

Thanks for your PR, 

I tested it and it's good for me 

https://github.com/user-attachments/assets/5f718cc4-84e9-4417-85f6-fb26e45ad43c

Thanks

**Review by SiraDIOP — APPROVED** [review]
