### PR TITLE
Handle custom lock file during the cache clear and force module actions one by one

### LINKED ISSUE #28304: An exception is displayed when Installing the blockwishlist module and executing another BO page at the same time
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed when Installing the blockwishlist module and executing another BO page at the same time

### Expected behavior

**Wording:**

- **Case 1**: Upload a module

After pressing the 'upload a module' button, a modal is displayed.

Title: 'Are you sure you want to upload this module?' Admin.Modules.Notification

'First things first: put your store in maintenance mode. And if several people have access to the back office, warn your team that no action should be taken on the store during the process.' Admin.Modules.Notification
Exit buttons:

'Go to maintenance page' Admin.Actions
'Upload anyway' Admin.Actions

- **Case 2**: Upgrade a module

After pressing the 'upgrade a module' button, a modal is displayed.

Title: 'Are you sure you want to upgrade this module?' Admin.Modules.Notification

'First things first: put your store in maintenance mode. And if several people have access to the back office, warn your team that no action should be taken on the store during the process.' Admin.Modules.Notification

Exit buttons:

'Go to maintenance page' Admin.Actions
'Upgrade anyway' Admin.Actions

- **Case 3**: Install a module

After pressing the 'install a module' button, a modal is displayed.

Title: 'Are you sure you want to install this module?' Admin.Modules.Notification

'First things first: put your store in maintenance mode. And if several people have access to the back office, warn your team that no action should be taken on the store during the process.' Admin.Modules.Notification
Exit buttons:

'Go to maintenance page' Admin.Actions
'Install anyway' Admin.Actions

_No response_

### Steps to reproduce

1. Install the develop branch
2. Go to BO > Modules > Module manager page 
3. Uninstall the old version of the module blockwishlist v2.0.1 with removing the folder
4. Install the release and during the install => open another page from BO in another tab
5. An exception is displayed
6. Click on configure of the module => exception
7. All the BO is NOK now

I attached a screen record

https://user-images.githubusercontent.com/16067358/163567496-2c83b052-a5e0-4cc7-b172-708f44d34b15.mp4

I checked develop + v2.0.1 => ok

https://user-images.githubusercontent.com/16067358/163567512-f6654d2f-8f87-4063-b152-f2e84bcc746e.mp4

I checked 178x + v2.1.0 => ok

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

wishlist v2.1.0

### LINKED ISSUE #31562: [Spike] Study cache managment during modules installation
Some issues can occur in the cache management during (at least) the module installation.

A tech study should investigate to know : 
- How and when  lock this cache ( MUST HAVE) 
- How and when invalidate this cache ( MUST HAVE ) 
- How and when use the services ( localisation , menu ...) during the module installation ( NICE TO HAVE) 

Related : https://github.com/PrestaShop/PrestaShop/pull/31419

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Handle custom lock file during the cache clear to make sure other processes have to wait until the new container is ready This is an alternative to the solution proposed in this PR https://github.com/PrestaShop/PrestaShop/pull/31419
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | The lock happens when Symfony cache is clear, mainly during any module operation (enable, disable, install, uninstall, ...) During the cache clearing, any other process (from a different tab) should be blocked until the cache is available again. We need to make sure that the shop doesn't end up in a blocked state for some reason, and we also should probably test that this doesn't impact the auto-upgrade process It could also be interesting to check that the use case related to this PR https://github.com/PrestaShop/PrestaShop/pull/30962 is still valid as it was also a complex use case related to cache clearing<br><br>The module management has also been modified, now the bulk actions are forced one by one and when you try to perform two actions at the same time (by clicking on a button for a module while an action is in progress on another) the action is blocked and a warning message warns you that you need to wait
| Fixed ticket?     | Fixes #31562 and Fixes #28304
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Comment by jolelievre** [comment]
(Edit 20/03 3h30pm) Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4469351523

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php [hunk 1]
```diff
@@ -78,13 +72,18 @@ public function clear()
...
 
             $output = new NullOutput();
             $application->run($input, $output);
 
             Hook::exec('actionClearSf2Cache');
         });
+
+        // Unlock is registered in another seaprate function to make sure it will be called no matter what
+        register_shutdown_function(function () use ($kernel) {
+            $kernel->unlocksCacheClear();
```
Comment (GautierBoudeweel) [inline src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:86]: > If you call [exit()](https://www.php.net/manual/en/function.exit.php) within one registered shutdown function, processing will stop completely and no other registered shutdown functions will be called.
https://www.php.net/manual/en/function.register-shutdown-function.php

What if some code tied to `actionClearSf2Cache` hook executes an exit() call ? Maybe we could have a max_locking_time as a fallback ?

Comment (jolelievre) [reply src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:86]: Do you mean having a timeout after which the file is unlocked? There is no such feature with `flock` as far as I know. 

But anyway even if the file is not unlocked manually it will be automatically unlocked after the process that locked it ends, so if indeed someone calls `exit` in `actionClearSf2Cache` even though they SHOULD NEVER DO IT then the file will be unlocked.

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php [hunk 2]
```diff
@@ -78,13 +72,18 @@ public function clear()
...
+                '--env' => $kernel->getEnvironment(),
             ]);
 
             $output = new NullOutput();
             $application->run($input, $output);
 
             Hook::exec('actionClearSf2Cache');
         });
+
+        // Unlock is registered in another seaprate function to make sure it will be called no matter what
```
Comment (matks) [inline src/Adapter/Cache/Clearer/SymfonyCacheClearer.php]:
```suggestion
        // Unlock is registered in another separate function to make sure it will be called no matter what
```

**Review by matks — COMMENTED** [review]
Pragmatic enough for me for a patch 👍

**Review by zuk3975 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]
LGTM but as I understand we will clear the cache for all actions (if clear cache is finish on previous action) on modules ? Not only the last action ?

**Review by matks — APPROVED** [review]

**Comment by jolelievre** [comment]
@mflasquin indeed the clear cache on the last step was an "optimization" because it cost a lot of time, but in the end, considering all the bugs related to cache clearing and the instability it can occur I don't think the small gain is worth the risk

**Review by djoelleuch — APPROVED** [review]
Hello @jolelievre ,
I have tested your PR and it's well fixed !
The automated tests are OK.
It's QA approved :rocket: 
thank you !

**Comment by nicosomb** [comment]
Thank you @jolelievre :tada: and @djoelleuch !
