### PR TITLE
[BO] Added DataCollector for Legacy Profiling

### LINKED ISSUE #35473: PrestaShop debug profiler doesn't work with Symfony layout
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you enable Symfony layout for the back office in feature flags, the built-in profiler doesn't show up.

### Expected behavior

Profiler should work as before because otherwise, it is impossible to easily debug the performance of queries coming from legacy, etc.

### Steps to reproduce

1. Enable Symfony layout in feature flags.
2. Edit config/defines.inc.php and change `_PS_DEBUG_PROFILING_` to `true`
3. See that the profiler doesn't show with Symfony layout, but it is available if Symfony layout is disabled.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | [BO] Added DataCollector for Legacy Profiling
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | :arrow_down: 
| UI Tests          | https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/18375589383
| Fixed issue or discussion?     | Fixes #35473
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

## How to test ?
* Go to BO
* Enable Debug Mode
* Enable Profiler
* Check in Symfony Bar
* A new block is added named `Legacy`
image

### CODE REVIEW

**Comment by kpodemski** [comment]
I've just tested it and it does the job!

Of course, ideally, we should _merge_ the results from Legacy and Syfmony, but it's a good start!

There's definitely a need to improve the table visually, especially for longer queries, but it can be improved in a separate PR :)

File: src/PrestaShopBundle/DataCollector/LegacyCollector.php [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+namespace PrestaShopBundle\DataCollector;
+
+use Profiler;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+use Symfony\Component\HttpKernel\DataCollector\DataCollector;
+use Throwable;
+
+/**
+ * Collects data about dispatched Commands/Queries during request
```
Comment (kpodemski) [inline src/PrestaShopBundle/DataCollector/LegacyCollector.php]:
```suggestion
 * Collects data from the legacy debug profiling (e.g. queries coming from Db class)
```

File: src/PrestaShopBundle/Resources/views/Admin/WebProfiler/legacy.html.twig [hunk 2]
```diff
@@ -0,0 +1,427 @@
...
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * #}
+{% extends '@WebProfiler/Profiler/layout.html.twig' %}
+
+{% block toolbar %}
+  {% set icon %}
+    {% if collector.isProfilerEnabled %}
```
Comment (kpodemski) [inline src/PrestaShopBundle/Resources/views/Admin/WebProfiler/legacy.html.twig:29]: Isn't it possible to place this if around the whole code in this file except `extends`?

Comment (Progi1984) [reply src/PrestaShopBundle/Resources/views/Admin/WebProfiler/legacy.html.twig:29]: It's not allowed by Twig, sorry.

**Comment by Progi1984** [comment]
> I've just tested it and it does the job!
> 
> Of course, ideally, we should _merge_ the results from Legacy and Syfmony, but it's a good start!
> 
> There's definitely a need to improve the table visually, especially for longer queries, but it can be improved in a separate PR :)

I think it's a good start : the final goal is to remove this collector when PSOS will have full migrated to Symfony.

We wait issues for improvements.

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @Progi1984 , 

Thanks for your pr, i tested it and it's good for me :) , i'm waiting automated tests too approve this pr.

Capture d’écran 2025-10-09 à 14 48 57

**Review by SiraDIOP — APPROVED** [review]

**Comment by Touxten** [comment]
Thank you @Progi1984 && @SiraDIOP

**Comment by Hlavtox** [comment]
Thank you @Progi1984 ❤️
