### PR TITLE
BO - Order Messages - Avoid message with duplicate name

### LINKED ISSUE #24535: BO - Orders - Order message - Order message with the same title is not displayed in the "order_message" list
#### Describe the bug

In the BO > Orders > Order details page > in the messages block, The order messages with the same title is not displayed in the "order_message" list

#### Expected behavior

In the PS1769, they are well displayed
image

#### Steps to Reproduce

1. Go to BO > Customer Service > Order message > Create two message with the same title for example "Test"
image
2. Go to BO > Orders > Orders page
3. View any order
4. In the Message block > Only the last one is displayed in the order_message list
image

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2, 7.4

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | BO - Order Messages - Avoid message with duplicate name
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24535
| How to test?      | Cf. #24535

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24579)

### CODE REVIEW

**Comment by Progi1984** [comment]
@Julievrz Could I have an existing message for avoiding the new string ?

(Ping @MatShir)

**Review by PierreRambaud — DISMISSED** [review]

File: src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php [hunk 1]
```diff
@@ -69,4 +72,22 @@ public function handle(AddOrderMessageCommand $command): OrderMessageId
...
+    private function assertNameIsNotAlreadyUsed(AddOrderMessageCommand $command): void
+    {
+        foreach ($command->getLocalizedName() as $langId => $langName) {
+            $orderMessages = OrderMessage::getOrderMessages($langId);
+            if (!is_array($orderMessages)) {
+                continue;
+            }
+            foreach ($orderMessages as $orderMessage) {
+                if ($orderMessage['name'] === $langName) {
+                    throw new OrderMessageNameAlreadyUsedException(
```
Comment (jolelievre) [inline src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php:85]: One suggestion, you are creating the exception with `$langName` value, even though it is not used in the error message displayed to the merchant, so I think this parameter is a bit useless (in the current state at least)

However, one thing that is missing in the error message - since it is a multi lang field - is which language is invalid (fr, en, ??) So I think the error message should display:
- which language is blocked (ideally we'd need the language locale I guess)
- why not keep the content as you did here but then it should also be inserted in the translated error message

**Review by jolelievre — COMMENTED** [review]
Suggestion for an improvement

File: src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/OrderMessage/CommandHandler/AddOrderMessageHandler.php:85]: I will add to the exception the languageId.

**Review by PierreRambaud — APPROVED** [review]

File: src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php [hunk 2]
```diff
@@ -69,4 +73,26 @@ public function handle(EditOrderMessageCommand $command): void
             throw new OrderMessageException(sprintf('Failed to update order message with id "%s"', $command->getOrderMessageId()->getValue()), 0, $e);
         }
     }
+
+    private function assertNameIsNotAlreadyUsed(EditOrderMessageCommand $command): void
```
Comment (sowbiba) [inline src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php:77]: I dont like the repetition of this method. Can it be in the abstract ?

Comment (Progi1984) [reply src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php:77]: No the `assert` name is logical but the behavior is different inside

**Review by sowbiba — APPROVED** [review]

File: src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php (hunk 2 above)
Comment (sowbiba) [reply src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php:77]: My bad.
So in AddOrderMessage we check that message title doesnt exist at all
In EditOrderMessage that it doesn't exist in some other orderMessage

Comment (Progi1984) [reply src/Adapter/OrderMessage/CommandHandler/EditOrderMessageHandler.php:77]: exactly

File: src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php [hunk 3]
```diff
@@ -244,6 +245,10 @@ private function getErrorMessages(): array
                 'The object cannot be loaded (or found)',
                 'Admin.Notifications.Error'
             ),
+            OrderMessageNameAlreadyUsedException::class => $this->trans(
```
Comment (hibatallahAouadni) [inline src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController.php:248]: After **OrderMessageNameAlreadyUsedException** there's "**::**" IMHO this is NOK, it should be "**:**" :slightly_smiling_face: 
I notice that with your PR, I have **Order Settings** instead of **Orders** and **Customer Settings** instead of **Customers**, I don't know if it's related but this is the only typo that I found :wink:

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @Progi1984 

I think there's a regression within your PR, check my review and the attached screen record below:

https://drive.google.com/file/d/1SkUWwXxIU-9z804s693RklCLQKNIghQL/view

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni I didn't reproduce your bug. Could you check it again, please?

image

**Comment by hibatallahAouadni** [comment]
Hello @Progi1984 

Thanks for your feedback!
What I encountred is this issue #9762 and it's already fixed with 1.7.8.x.
So, LGTM and QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @hibatallahAouadni
