### PR TITLE
No tracking Number for return product tab

### LINKED ISSUE #19200: Return tab on order BO page has no "tracking number" + wrong wording
#### Describe the bug

On the "merchandise return" tab on an order, the label of tracking number is just the "return ID"

It should be : 
* Column label: Return number
* Value: #RE000001 (if prefix is set to RE)

An improvement: have a link to edit the "return" (there is a link from a return to an order but not in the other way)

**Screenshots**

image

#### Describe how it should work

**Specifications**

https://github.com/PrestaShop/prestashop-specs/pull/196/files

#### Additional information

* PrestaShop version: 1.7.6.5 1.7.7.0
* PHP version: N/A

+ "Carrier" in the table is not the good wording. It should be replaced by "Status" (see screenshot below)

BEFORE
image
AFTER
image

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | No tracking Number for return product.
| Type?             | bug fix
| Category?         |  BO
| BC breaks?        |  yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/19200
| How to test?      | Made a return and check that the words are right. DevCore must check for deleted variables
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

**:notebook: BC break** 
* Remove property `$carrierId` in `OrderReturnForViewing.php`
* Remove property `$trackingNumber` in `OrderReturnForViewing.php`
* Remove property `$trackingUrlr` in `OrderReturnForViewing.php`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26056)

### CODE REVIEW

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 1]
```diff
@@ -573,11 +573,15 @@ private function getOrderReturns(Order $order): OrderReturnsForViewing
 
             if (isset($orderReturn['url'], $orderReturn['tracking_number'])) {
                 $trackingUrl = $orderReturn['url'];
-                $trackingNumber = $orderReturn['tracking_number'];
-            } elseif (isset($orderReturn['tracking_number'])) {
-                $trackingNumber = $orderReturn['tracking_number'];
             }
 
+            $conf = $this->configuration->get('PS_RETURN_PREFIX');
+            $trackingNumber = sprintf(
```
Comment (matks) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: Logic seems good in general. But if I understand correctly, actually this is not a tracking number, right ? This is a "merchandise return ID". So we should modify the variable name to make it correct, wdyt ?

Comment (ghost) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: Hi @matks I agree with you but : 

After this PR I want to open another issue.
Which will correct the variable names and clean up this file :

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Order/QueryResult/OrderReturnForViewing.php

There are: $carrierId; $trackingUrl; $trackingNumber ;
I don't think they belong here, but it's possible that people are using them. And if I delete them, it's a  BC break.
This fixed PR https://github.com/PrestaShop/PrestaShop/issues/19200 we need to open another one for the other problem.

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 2]
```diff
@@ -573,11 +573,15 @@ private function getOrderReturns(Order $order): OrderReturnsForViewing
 
             if (isset($orderReturn['url'], $orderReturn['tracking_number'])) {
                 $trackingUrl = $orderReturn['url'];
-                $trackingNumber = $orderReturn['tracking_number'];
-            } elseif (isset($orderReturn['tracking_number'])) {
-                $trackingNumber = $orderReturn['tracking_number'];
             }
 
+            $conf = $this->configuration->get('PS_RETURN_PREFIX');
```
Comment (sowbiba) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: I would replace $conf by $returnPrefixByLang to make it clear

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig [hunk 3]
```diff
@@ -40,11 +40,13 @@
           <td>{{ return.date|date_format_full }}</td>
           <td>{{ return.type }}</td>
           <td>{{ return.stateName }}</td>
-          <td class="text-right">
+          <td>
             {% if return.trackingNumber and return.trackingUrl %}
               <a href="{{ return.trackingUrl }}">{{ return.trackingNumber }}</a>
             {% elseif return.trackingNumber %}
-              {{ return.trackingNumber }}
+              <a class="d-print-none" href="{{ getAdminLink('AdminReturn', true, {'id_order_return': return.idOrderReturn, updateorder_return : '', 'back': app.request.uri}) }}">
```
Comment (sowbiba) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig]:
```suggestion
              <a class="d-print-none" href="{{ getAdminLink('AdminReturn', true, {'id_order_return': return.idOrderReturn, 'updateorder_return': '', 'back': app.request.uri}) }}">
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig [hunk 4]
```diff
@@ -40,11 +40,13 @@
           <td>{{ return.date|date_format_full }}</td>
           <td>{{ return.type }}</td>
           <td>{{ return.stateName }}</td>
-          <td class="text-right">
+          <td>
             {% if return.trackingNumber and return.trackingUrl %}
               <a href="{{ return.trackingUrl }}">{{ return.trackingNumber }}</a>
             {% elseif return.trackingNumber %}
-              {{ return.trackingNumber }}
+              <a class="d-print-none" href="{{ getAdminLink('AdminReturn', true, {'id_order_return': return.idOrderReturn, 'updateorder_return': '', 'back': app.request.uri}) }}">
```
Comment (atomiix) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig]: Why hiding the tracking number in print mode?

Comment (ghost) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig]: Because it's not a tracking number :) i have started [a discussion](https://github.com/PrestaShop/PrestaShop/pull/26056#discussion_r722601948) with @matks  I am waiting for a reply

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: @okom3pom You can change the variable name as the scope remains in the method.

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig (hunk 4 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig]: If it's not a tracking number, it shouldn't be named `trackingNumber` :thinking:

Comment (ghost) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/merchandise_returns.html.twig]: Hello @PierreRambaud i started a discussion with @matks i wait answer.

This fixed PR #19200 we need to open another one for the other problems. ( a lot ) 

https://github.com/PrestaShop/PrestaShop/pull/26056#discussion_r722601948

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: I think it should be done in the same PR. :thinking:

Comment (ghost) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: I would need to know what I am deleting / rename  in[ this file](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Order/QueryResult/OrderReturnForViewing.php)? 

_There are: $carrierId; $trackingUrl; $trackingNumber ;
I don't think they belong here, but it's possible that people are using them. And if I delete them, it's a BC break._


@Progi1984 @PierreRambaud @matks ?

**Comment by atomiix** [comment]
@okom3pom Can you solve the conflict, please? :)

**Comment by ghost** [comment]
Hello @atomiix 

I am waiting for an answer from @matks  and @PierreRambaud 

https://github.com/PrestaShop/PrestaShop/pull/26056#discussion_r745382364

I can rebase and open a new issue

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: For me it should be a new variable as it's not related to the tracking number

Comment (ghost) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: @PierreRambaud i remove also `$carrierId; $trackingUrl; $trackingNumber ; `

**Comment by matks** [comment]
Answer provided by @PierreRambaud  👍  waiting for the new changes

**Comment by ghost** [comment]
Normaly it's good

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I cannot test this PR.
I have an exception in the FO
image
This PR is blocked by this issue: https://github.com/PrestaShop/PrestaShop/issues/26656

Thanks!

**Comment by ghost** [comment]
I am working on https://github.com/PrestaShop/PrestaShop/issues/26656 it's after a bad rebase

**Comment by ghost** [comment]
Hello @khouloudbelguith 

Normaly you can test now

Regards

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

As described in the spec:
` The merchandise return tab lists **the date, the type, the carrier (= return status), and the number (= return reference number)**. When the merchandise return is disabled the tab displayed: "no merchandise returned yet".`

The merchandise return tab is still displayed after disabling it.
Steps to reproduce the issue:
1. Go to BO > Customer Service  > Merchandise Returns page & Enable returns
2. Create an order and change status to shipped
3. Go to FO > account page > Order details page & create a return
4. Go to BO > Customer Service  > Merchandise Returns page & disable returns 
image
5. Go to BO > Orders > View last order Created > Merchandise returns Tab > still displayed 
image


Ping @PrestaShop/product-team I need your confirmation.

Thanks!

**Comment by ghost** [comment]
Hi @khouloudbelguith 

This PR fixes the problems but not the specification, I think it is better to open a new issue for display.

Because it's another problem? 

Regards

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

In fact, the original issue was updated by the product team & this [spec](https://github.com/PrestaShop/prestashop-specs/pull/196) was updated
I need the confirmation of the @PrestaShop/product-team before creating a new issue.

Thank you!

**Review by atomiix — DISMISSED** [review]

**Comment by MatShir** [comment]
We can make another issue, part of the problem is solved.
Thanks @okom3pom

**Comment by khouloudbelguith** [comment]
Hi @okom3pom, 

I checked this PR.
It is ok manually :heavy_check_mark: 
I validate this PR. 
image

But automatic tests should be updated
[Mochawesome Report_marchandise_return.pdf](https://github.com/PrestaShop/PrestaShop/files/7864678/Mochawesome.Report_marchandise_return.pdf)
Ping @PrestaShop/qa-automation 
If we merge this PR, nightly will be NOK.

Thanks!

**Comment by boubkerbribri** [comment]
@nesrineabdmouleh can you check and fix this please ?

**Comment by boubkerbribri** [comment]
Hello @okom3pom, 
To fix tests, we were missing a rebase and we done it wrongly first.
But Now it's FIXED (with a cherry-pick of your commits and the UI tests fix).
I'm very Sorry for the inconvenience but Can you check please that nothing is missing from your PR please ?

**Comment by ghost** [comment]
It"s ok !

**Comment by boubkerbribri** [comment]
Thanks @okom3pom (and sorry again)
We will wait for reviews to add QA :heavy_check_mark: .

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
Validated by @khouloudbelguith previously and UI tests are fixed by @nesrineabdmouleh. So it's QA :heavy_check_mark:

**Comment by Progi1984** [comment]
Thanks @okom3pom @boubkerbribri @nesrineabdmouleh & @khouloudbelguith
