### PR TITLE
Prevent uncheck cast

### LINKED ISSUE #35003: PS 8.1.1 break BC with ObjectModel having translatable bool fields
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Since Prestashop 8.1.1 loading an ObjectModel with a boolean field that is translatable triggers an 'Array to string conversion' error.

### Expected behavior

ObjectModel with translatable boolean must load properly.
If to be deprecated in a near future it should not break in a minor version.

PR #34873 solves the issue

### Steps to reproduce

1. Install the provided module
2. Try to configure the module
[castcrash.zip](https://github.com/PrestaShop/PrestaShop/files/13871512/castcrash.zip)

### PrestaShop version(s) where the bug happened

8.1.1+

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Novius

### PR DESCRIPTION
**Pull request by gross-nvs**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Previous modification in EntityMapper introduced a breaking change when having a boolean field  with `'lang' => true` on an ObjectModel. This is due to an unchecked cast on a value being either a string, an number or an array, and will throw an `Error`: `Warning: Array to string conversion`, therefore introducing a breaking change from previous 8.x versions.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create an ObjectModel having a boolean field with `'lang' => true`, the object should be properly loaded from database without error
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #35003
| Related PRs       | Related to #33048 
| Sponsor company   | Novius

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by florine2623** [comment]
@PrestaShop/committers should this be tested by a dev ?

**Review by boherm — APPROVED** [review]

File: src/Adapter/EntityMapper.php [hunk 1]
```diff
@@ -98,7 +98,12 @@ public function load($id, $id_lang, $entity, $entity_defs, $id_shop, $should_cac
                         if (isset($entity_defs['fields'][$key]['type']) && in_array($entity_defs['fields'][$key]['type'], [
                             \ObjectModel::TYPE_BOOL,
                         ])) {
-                            $entity->{$key} = (string) $value;
+                            if (is_array($value)) {
```
Comment (jolelievre) [inline src/Adapter/EntityMapper.php:101]: Hi @gross-nvs 

I'm not sure to understand the issue here, you try to cast an array for a field that's supposed to be a boolean, how can data for a boolean be an array? Isn't there some inconsistency in the ObjectModel definition here? 🤔

Could you please provide a concrete example of how we can reproduce this error because your PR is not related to any issue, or any reproduced bug and without more context this modification seems doutbful

**Review by jolelievre — CHANGES_REQUESTED** [review]
I prefer to block this one until we get an answer from @gross-nvs

**Comment by gross-nvs** [comment]
I opened an issue with a test module: #35003

You can't assume the value is a boolean before casting because the data is pulled from the database and undergo a first mapping of lang values, therefore you must check if you deal with an array or not.

**Review by Hlavtox — DISMISSED** [review]
Boolean should not be a multilang value, no point of adding code to fix nonsense that should not be there.

**Comment by kpodemski** [comment]
@Hlavtox 

I'm not sure. You could do something like:

"For which languages do you want to display this post?"

And the value could be a multi-lang boolean + if it is a BC Break, it should definitely be fixed.

**Comment by Hlavtox** [comment]
@kpodemski Hm, yeah, you are right.

But please, make sure to check the original issue - https://github.com/PrestaShop/PrestaShop/issues/31958 and the previous PR https://github.com/PrestaShop/PrestaShop/pull/33048.

**Comment by gross-nvs** [comment]
#31958 was checked before posting this PR, out of caution I re-tested it with success just now. :+1:

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Ok @gross-nvs thanks for the details, I was thinking of this kind of use case but that makes more sense now, even though we don't have this kind of usage of multilang boolean (to my knowledge) but there can be use cases where it's needed

**Comment by jolelievre** [comment]
Of course the initial issue should be tested to make sure no regression comes from this modification, but from the looks of the code it seems to respect the initial fix

**Comment by jolelievre** [comment]
But we'll have to make sure that the boolean value is still a string for now, and that the `strval` doesn't change the result compared to simple cast `(string)` To be checked by the develop who will perform the QA

**Comment by gross-nvs** [comment]
@jolelievre `(string)` and `strval` are the same, it's just about code style, I've made a mistake by changing it while doing some testing when I wrote the code.

I can change back to cast code style `(string)` if you prefer and update the pull request.

**Comment by jolelievre** [comment]
@gross-nvs no it should be ok no worries!

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @gross-nvs 

I tested your PR with the module you provided, I also tested a few custom modules I have installed and didn't notice any issues. Thank you :)
