### PR TITLE
Fix php 8.1 Filemanager

### LINKED ISSUE #29543: [PHP8.1] - BO - A warning is displayed in the File manager after resetting the sort and the filter
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > A warning is displayed in the File manager after resetting the sort and the filter 
image

It is ok with 8.0.x + PHP 8.0

### Expected behavior

No warning displayed

### Steps to reproduce

1. Use PHP8.1
2. Go to BO > Catalog > Categories page
3. Edit any category
4. In the description, try to insert some images
5. In the file manager, Try to insert a text in the input of the filter 
6. Click on the sort
7. Then reset it 
image
8. See error

https://user-images.githubusercontent.com/16067358/188629165-33f6f527-c4cb-4619-877f-c2b75df9ae77.mp4

### PrestaShop version(s) where the bug happened

8.0.x, 8.0.0beta

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fixes usort usage that no longer accept boolean return values.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #29543 .
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | See the issue, plus test all sorting options as they have the same issue.

### CODE REVIEW

File: admin-dev/filemanager/dialog.php [hunk 1]
```diff
@@ -424,12 +424,12 @@
 
     function filenameSort($x, $y)
     {
-        return $x['file'] < $y['file'];
+        return ($x['file'] < $y['file']) ? 1 : -1;
```
Comment (atomiix) [inline admin-dev/filemanager/dialog.php]: I like this syntax better for these kind of function but totally optional :) (also, it can return `0` if `$x['file'] === $y['file']`)
```suggestion
        return $x['file'] <=> $y['file'];
```

**Review by matks — DISMISSED** [review]
Ha it expects an int instead of a boolean 😄

**Review by atomiix — DISMISSED** [review]

File: admin-dev/filemanager/dialog.php (hunk 1 above)
Comment (jolelievre) [reply admin-dev/filemanager/dialog.php]: Oh, I didin't know this operator! That's great!

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @FabienPapet 

I have checked this PR. The issue is well fixed.
Here is the checked list : 

- Check the automated tests : OK
- Check with different languages (RTL and no RTL) : OK
- Check Check with different browsers (Chrome & Firefox) : OK
- Check with multistore: OK
- Check on Categories page : OK 
- Check with different Product V1 and Product V2 : OK
- Check with different php versions (7.4 , 8.1) : OK


https://user-images.githubusercontent.com/92912932/189395253-e325f599-85c6-4087-8a3d-32b370172b71.mp4


image

image

image

image

Thank You!

**Comment by matks** [comment]
Thank you @FabienPapet and @HanaRebaiQA
