### PR TITLE
Fix, hide desactivated  categories in breadcrumbs

### LINKED ISSUE #23530: Desactivated category still display in breadcrumbs
#### Describe the bug

On a page of product with a categories path, deactivate one category.
The category still display in breadcrumbs

#### Expected behavior

The category must not appear in breadcrumb

#### Steps to Reproduce

1. Create a path of categories, add thoses to a product.
2. Show the product, with the path of breadcrumbs
3. Deactivate one category in this path
4. Clear all cache
5. The category still display in breadcrumbs of the product page

#### Additional information

* PrestaShop version: 1.7.X
* PHP version: N/A
Fix in pull request
#23528

### PR DESCRIPTION
**Pull request by mkdgs**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  develop 
| Description?      |  The bug: when desactivate a categorie she still showing in breadcrumb. This PR fix it 
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     |  Fixes #23530
| How to test?      |  on a page of product with a categories path, deactivate one category. She must not appear in breadcrumb  
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23528)

### CODE REVIEW

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -1215,7 +1215,7 @@ public function getBreadcrumbLinks()
         $categoryDefault = new Category($this->product->id_category_default, $this->context->language->id);
 
         foreach ($categoryDefault->getAllParents() as $category) {
-            if ($category->id_parent != 0 && !$category->is_root_category) {
+            if ($category->id_parent != 0 && !$category->is_root_category && $category->active) {) {
```
Comment (PululuK) [inline controllers/front/ProductController.php]:
```suggestion
            if ($category->id_parent != 0 && !$category->is_root_category && $category->active) {
```

**Review by PululuK — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
thank you for your contribution @mkdgs  !

**Review by PierreRambaud — DISMISSED** [review]

**Comment by aDamelincourt** [comment]
Hello @mkdgs 
There is a problem with this PR

NOK_23528_Screenshot 2021-03-09_16-10-39-747

I deactivate a sub-categorie but this sub-category still appear in the breadcrumb 
It's the parent category for the product

NOK_23528_Screenshot 2021-03-09_16-09-43-336

The PR correctly fixed the bug, for other categories, different of parent category for product

Thank you.

**Comment by mkdgs** [comment]
@aDamelincourt exact, that was not appear in my use case.
The getCategoryPath() method is very strange:
- unlike the name, it's not return a path
- condition will ignore active category !?  
I have modified the PR, i think getCategoryPath() is useless

**Review by sowbiba — DISMISSED** [review]
LGTM

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -1215,15 +1215,14 @@ public function getBreadcrumbLinks()
...
 
         foreach ($categoryDefault->getAllParents() as $category) {
-            if ($category->id_parent != 0 && !$category->is_root_category) {
-                $breadcrumb['links'][] = $this->getCategoryPath($category);
+            if ($category->id_parent != 0 && !$category->is_root_category && $category->active) {
+                $breadcrumb['links'][] = [
+                    'title' => $category->name,
+                    'url' => $this->context->link->getCategoryLink($category),
+                ];
             }
```
Comment (atomiix) [inline controllers/front/ProductController.php:1223]: I would be in favor of getting rid of the `if` statement here (and everywhere it was made like that), fix the one in the method `getCategoryPath()` and return a `array_filter($breadcrumb)` to remove `null` entries. What do you think?

**Comment by mkdgs** [comment]
@atomiix  It's a deeper change, and i don't know if this method is called elsewhere.
For doing something coherent, i think:
- moving the foreach block to getCategoryPath()
- add the leaf category to the argument like: getCategoryPath($category)
- return an array containing the path of the category

But that's was not the goal of the fix

**Comment by mkdgs** [comment]
It's still marked waiting for author, but I've nothing to add ;)

**Review by PululuK — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by aDamelincourt** [comment]
@mkdgs 
I don't see the parent category of the product
Only the "Home accessories" category is hidden 
image
image
image

**Review by Progi1984 — DISMISSED** [review]

**Comment by mkdgs** [comment]
@aDamelincourt, i see it's fixed !

**Comment by Progi1984** [comment]
@mkdgs Could you apply `./vendor/bin/php-cs-fixer fix` on your code for fixing PHPCSFixer ?

**Comment by mkdgs** [comment]
@Progi1984, now PHPCSFixer seems to be happy :)

**Review by Progi1984 — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Comment by aDamelincourt** [comment]
Thanks @mkdgs 
✔️  Check by QA
Deactivated categories are hidden in breadcrumbs.
image
image
image
image

**Comment by PululuK** [comment]
Thanks @mkdgs ✌🏾
