### PR TITLE
Use inherited layout for categories

### LINKED ISSUE #27946: Category controller should not hardcode a layout tpl
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The front Category controller call 'layouts/layout-full-width.tpl' here:
https://github.com/PrestaShop/PrestaShop/blob/5005657ed11f15e81c2d8cb5e4a855acd19213e1/controllers/front/listing/CategoryController.php#L165

So, if the theme doesn't have this layout this line raise a SmartyException if the category is inactive or unauthorized

### Expected behavior

no exception

### Steps to reproduce

- Delete or rename layouts/layout-full-width.tpl in your theme
- Change the default layout un theme.yml to another layout (layout-left-column by example)
- Remove the full layout in available_layouts section of the theme.yml
- Reset the theme in the bo (in debug mode)
- Back Office : Choose a category
- Front Office : Go to this category page in front
- Back Office : Disable this category 
- Front Office : Reload this category page in front 
image

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed hardcoded layout name from the controller
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27946
| How to test?      | Check that the category page looks the same after the change. The category page that is disabled or you don't have access to.
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27947)

### CODE REVIEW

**Review by saulaski — DISMISSED** [review]

**Comment by jf-viguier** [comment]
merci @saulaski

**Comment by NeOMakinG** [comment]
Isn't it a BC?

**Comment by jf-viguier** [comment]
@NeOMakinG I guess no, getLayout of the parent is called

**Review by matks — DISMISSED** [review]
Sorry for late review

**Comment by jf-viguier** [comment]
merci @matks ready for QA ?

File: controllers/front/listing/CategoryController.php [hunk 1]
```diff
@@ -154,20 +154,6 @@ public function initContent()
         }
     }
 
-    /**
-     * overrides layout if category is not visible.
-     *
-     * @return bool|string
-     */
-    public function getLayout()
```
Comment (jolelievre) [inline controllers/front/listing/CategoryController.php:148]: Hi @jf-viguier 

I don't think the method should be completely removed. As you said the bug occurs for themes that don't have this template but it doesn't mean it's not useful for classic theme Or any other theme that has this file

Comment (jolelievre) [reply controllers/front/listing/CategoryController.php:148]: So instead of completely remove this it should be made more resilient by:
- checking if the template file exists before using it
- or check from the theme layouts

Comment (jolelievre) [reply controllers/front/listing/CategoryController.php:148]:
```php
        $theme = $this->context->shop->theme;
        $layouts = $theme->getAvailableLayouts();
        if (array_key_exists('layout-full-width', $layouts) && !$this->category->checkAccess($this->context->customer->id) || $this->notFound) {
            return 'layouts/layout-full-width.tpl';
        }
```

Comment (jolelievre) [reply controllers/front/listing/CategoryController.php:148]: Maybe we could even add a `hasLayout` method to the Theme class

Comment (jf-viguier) [reply controllers/front/listing/CategoryController.php:148]: @jolelievre I guess that the getLayout() method is not useful anymore. I've checked without it with an nonexistent category and the default layout is used.

Comment (atomiix) [reply controllers/front/listing/CategoryController.php:148]: @jolelievre I think if theme wants to use a different layout, they can use `theme_settings` for that?
Capture d’écran 2022-04-05 à 10 52 47

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @jf-viguier 

I have checked this PR. The issue is not fixed.
An exception is thrown in FO when renaming the `layout-full-width.tpl` file.
image

https://user-images.githubusercontent.com/92912932/163785939-97238623-3cb9-4b55-8fcd-afb008256320.mp4


Could you please check it ?


Thanks!

**Comment by jf-viguier** [comment]
It's not an issue, if this tpl is used in page.tpl it has to be there. The tpl has not to be called.
Page.tpl is the default layout.

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @jf-viguier 

As discussed, I used the same steps to reproduce to can catch the bug. I was able to reproduce it on PS1785 as commented here https://github.com/PrestaShop/PrestaShop/issues/27946#issuecomment-1100067252 

-Rename the file `'layout-full-width.tpl'`
-Check in FO
-See error > An exception is thrown
image


I still have the same exception while testing this PR. 
I also make the `layout-full-width` commented in `theme.yml` to make sure that it's not used.

https://user-images.githubusercontent.com/92912932/163974310-01a1c45e-5269-45df-9081-c39cea95f40b.mp4


Did I miss something ?

Thank You!

**Comment by jf-viguier** [comment]
I've added the step :
Change the default layout un theme.yml to another layout and reset the theme (in debug mode)

Please check.

**Comment by jf-viguier** [comment]
Please remove the Waiting for author: I've updated the how to test, please check @HanaRebaiQA

**Comment by kpodemski** [comment]
@jf-viguier done, sorry it took so long

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @jf-viguier 

I checked again this PR. I could reproduce the issue using the last provided steps.

Here an attached video without PR (For how to reproduce the issue) : 

https://user-images.githubusercontent.com/92912932/174817616-e02da39b-e523-4553-9a37-f4a6cce97e25.mp4


When check the PR, this case seems to be fixed. please see the attached video below : 

https://user-images.githubusercontent.com/92912932/174817550-befb88df-a33a-4ca6-8ef2-630aa77b4af8.mp4



But, i found the same issue with another scenario. Here is the steps : 

1. Rename the `layout-full-width.tpl` under `themes/classic/templates/layouts`
2. Change the default layout (layout-full-width)  in `theme.yml` to `layout-left-column` 
3. BO > IMPROVE > Design > Theme & Logo > Reset to defaults
4. BO > IMPROVE > Design > Theme & Logo > Choose layouts > Change the layout to `Full width, No side columns ... ` for index page (for example)
5. Go to FO > See exception
image


https://user-images.githubusercontent.com/92912932/174817491-ea217452-ae4a-4cae-9e12-5bacdc104f64.mp4

Could you please check it ?


Thank You!

**Comment by jf-viguier** [comment]
@HanaRebaiQA please try to remove the full layout in available_layouts section of the theme.yml
image

Remove the 3 lines, reset the theme in the bo (in debug mode) and try again please.

**Comment by jf-viguier** [comment]
@HanaRebaiQA I've updated the "Steps to reproduce"

**Comment by ghost** [comment]
The steps to reproduce are updated I put it directly in the description of the PR

**Comment by HanaRebaiQA** [comment]
Hello @jf-viguier,
Could you please provide an example of theme so that I can verify the problem exists without your PR, and it's fixed with your PR?
I will also check that it has no impact on classic theme.
Thank You!

**Comment by jf-viguier** [comment]
@HanaRebaiQA I've already answered this question in Mars, please https://github.com/PrestaShop/PrestaShop/issues/27946#issuecomment-1072212025
You can use classic theme and remove the file : layouts/layout-full-width.tpl

**Review by kpodemski — CHANGES_REQUESTED** [review]
We could be more explicit here as this change will introduce a behavior change, right?

What about, instead of having a hardocded layout, using:

`$layout = $this->context->shop->theme->getLayoutRelativePathForPage('error');`

This way, we make sure to display the layout related to error messages, which is expected behavior. Am I right?

**Comment by jf-viguier** [comment]
@kpodemski I don't remember exactly but I guess there is already a default template mecanism: so this PR don't introduce a behavior change.

**Comment by jf-viguier** [comment]
@kpodemski any news on this PR ?

**Comment by kpodemski** [comment]
@jf-viguier sorry, I didn't notice the notification

it will produce a different behavior as the default layout for the category is the one with the left column, with your change, you rely on the `left-column` for the error message. This code is supposed to change the layout to full-width to have errors displayed with it. This is why I suggested improving this PR to get the layout based on the page state.

**Comment by jf-viguier** [comment]
@kpodemski I don't understand what you want.  What do you mean by page state ?

**Comment by kpodemski** [comment]
@jf-viguier 

Test your Pull Request, please. Use your changes, set the layout for the category to the left column, disable access, and open it. You'll see that the error is displayed with the left column layout, which is different than it was.

If you want to keep the previous behavior and disable the hardcoded layout, you need to keep the code but change the hardcoded layout to `$this->context->shop->theme->getLayoutRelativePathForPage('error');`

**Comment by jf-viguier** [comment]
@kpodemski thanks a lot for the help, I've added your improvement.
My bad, I didn't test with a left column, we don't user this layout for years ;-)

**Review by kpodemski — DISMISSED** [review]
I'm accepting it. The tests now should be simple, and the page should look the same as before for categories that don't exist, or we don't have access :)

**Comment by jf-viguier** [comment]
thanks @kpodemski, just a cs fixer new line and we're good

**Review by kpodemski — DISMISSED** [review]

**Comment by jf-viguier** [comment]
@NeOMakinG a little review please ?

**Review by NeOMakinG — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
> @NeOMakinG a little review please ?

And your dreams comes true ser 🍬

**Comment by jf-viguier** [comment]
Thanks @NeOMakinG

**Comment by jf-viguier** [comment]
2023 is coming fast ;-)

**Comment by kpodemski** [comment]
All good from my perspective. I run automated tests [here](https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/3956216349). I'm waiting for them to finish so that I can merge.

Edit: running tests again: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/3956842583

**Comment by kpodemski** [comment]
@jf-viguier could you rebase your PR? I'd like to run automated tests, and rebase is needed.

**Comment by jf-viguier** [comment]
@kpodemski rebase done, thanks

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
Good for me, merging
