### PR TITLE
Check if customized product image exists before trying to delete it

### LINKED ISSUE #15986: Customized product can't be deleted from the cart
**Describe the bug**
It's impossible to delete a customized product from the cart if attached image doesn't exists.

1. Create a customizable product with an image field 
2. Add this customized product to the cart with an image
3. Delete the image in the upload folder
4. Try to delete the product in the cart : the first time, the customization is deleted. Second time : nothing appends

It's a complicated issue, I've simplified the test case because my concern is in a more complicated setup with my module changing customization behaviour. 

PrestaShop version: develop
PHP version: 7.2

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  If customized product image doesn't exists, false is returned and the product cannot be deleted from the cart.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #15986
| How to test?  | Cf my issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15987)

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -1803,7 +1803,7 @@ protected function _deleteCustomization($id_customization, $id_product, $id_prod
                 WHERE `id_customization` = ' . (int) $id_customization);
 
             // Delete customization picture if necessary
-            if (isset($cust_data['type']) && $cust_data['type'] == Product::CUSTOMIZE_FILE) {
+            if (isset($cust_data['type']) && $cust_data['type'] == Product::CUSTOMIZE_FILE && file_exists(_PS_UPLOAD_DIR_ . $cust_data['value'])) {
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
            if (isset($cust_data['type']) && $cust_data['type'] == Product::CUSTOMIZE_FILE) {
               $result &= file_exists(_PS_UPLOAD_DIR_ . $cust_data['value']) ? @unlink(_PS_UPLOAD_DIR_ . $cust_data['value']) : true;
               $result &= file_exists(_PS_UPLOAD_DIR_ . $cust_data['value'] . '_small') ? @unlink(_PS_UPLOAD_DIR_ . $cust_data['value'] . '_small') : true;
           }
```

File: classes/Cart.php [hunk 2]
```diff
@@ -4169,7 +4169,7 @@ public function deleteCustomizationToProduct($id_product, $index)
         );
 
         // Delete customization picture if necessary
-        if ($cust_data['type'] == Product::CUSTOMIZE_FILE) {
+        if ($cust_data['type'] == Product::CUSTOMIZE_FILE && file_exists(_PS_UPLOAD_DIR_ . $cust_data['value'])) {
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
        if (isset($cust_data['type']) && $cust_data['type'] == Product::CUSTOMIZE_FILE) {
            $result &= file_exists(_PS_UPLOAD_DIR_ . $cust_data['value']) ? @unlink(_PS_UPLOAD_DIR_ . $cust_data['value']) : true;
            $result &= file_exists(_PS_UPLOAD_DIR_ . $cust_data['value'] . '_small') ? @unlink(_PS_UPLOAD_DIR_ . $cust_data['value'] . '_small') : true;
        }
```

**Comment by matks** [comment]
Restarting Travis, I think recent docker hub downtime made it fail

**Comment by jf-viguier** [comment]
@matks I don't know what to do.

**Comment by matks** [comment]
> @matks I don't know what to do.

Nothing 😄 CI is failing for reasons unrelated to your contribution. It's our task to fix it, not yours

**Comment by matks** [comment]
@jf-viguier Found it: Travis was right 💪there was a mistake so tiny I did not even notice
Fixed in https://github.com/PrestaShop/PrestaShop/pull/15987/commits/dc43847f4f776269d9360524736a5c2e40085a66

**Comment by jf-viguier** [comment]
ok thanks @matks

**Review by Progi1984 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @jf-viguier

**Comment by jf-viguier** [comment]
Is this pr will be released in 1.7.7 ?

**Comment by PierreRambaud** [comment]
Yes, as you can see on the right of your pull request :)
image

**Comment by jf-viguier** [comment]
@PierreRambaud I've seen that but I don't know if it's a wish or a fact.

**Comment by PierreRambaud** [comment]
@jf-viguier It's a fact, everything merged in a milestone will be in the related release :)
