### PR TITLE
Combination delta quantity fix

### LINKED ISSUE #27313: Product combi delta bugs - Page V2
Hi @zuk3975,

I have some issues:

**First issue**

1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `2000000000000` or `2E12`
4. See error: `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\Stock\Exception\ProductStockConstraintException code 20]: Invalid StockAvailable quantity. Got "2000000000002"`

image

**Second issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `2E5`
4. Save => the final quantity will be 2
5. Edit another combination
6. In the Quantity field > set the same quantity `2E5` and save 
7.  See the difference > the final quantity is `200000`
8. Click outside
9. See error > the quantity of the first combination is converted to `200000`
https://watch.screencastify.com/v/NSTMV9OXU7k0mhrr8KAJ

what is the exact value of 2E5?, if it should be `200000` => in the delta quantity => NOK 

image

**Third issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > set the quantity with the keyboard
4. See error the delta quantity is not displayed only if  click outside
https://watch.screencastify.com/v/TxCcE65kiY8Pp1Icr9Ey

Same issue in the Combination edit page 
image

PS: if you use the arrow to increase or decrease the quantity => well displayed

**Fourth issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `888008848` and save
4. try to set the same quantity field with this value = `4444444444` and save
5. See error 
image

**Fifth issue**
1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to set the quantity field with this value = `2.2`
4. Click on the check button without moving the mouse
5. just an error but the field quantity is not red 
image

But if you click on the check button with moving the mouse 
image

**Sixth issue**

I don't know if it is really a bug

1. Enable Experimental product page
2. Go to BO > Catalog > Products page > Edit a product with combinations V2
3. In the combinations Tab > try to move the mouse on the disabled check button
4. See the behavior 

https://watch.screencastify.com/v/0SYKgdVOLkDKm5xfooIT

**Seventh issue**

1. Add the Finnish language
2. Change employee language to Finnish
3. Go to BO > Edit a product V2 with combinations
4. In the Combinations tab, set quantity with a negative value and save
5. Edit this combination
6. In the quantity field,> try to increase or decrease
7. See error, the delta quantity is NOK

image
 => we have a related issue reported here: https://github.com/PrestaShop/PrestaShop/issues/26502

**Eighth issue**

1. Open Firefox browser
2. Edit product with combination V2
3. In the Tab combinations see the increase/decrease quantity can be clicked only one-time => NOK

https://watch.screencastify.com/v/PbZB4Qd7iDuDWv9DDMyb

=> related to this issue: https://github.com/PrestaShop/PrestaShop/issues/26796

Thanks!

_Originally posted by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/issues/26617#issuecomment-1010159453_

### LINKED ISSUE #29253: StockMovement physical_quantity boundaries are not high enough
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the `stock_mvt` table the comumn `physical_quantity` is defined as an `int(11)` which is slightly higher than the `StockaAvailable::quantity` field which is a `int(10)`. This is logical because stock movement values can be higher than the max boundaries of the stock itself Twice as high actually, since it can vary from the min value `-2147483648` to the max value `2147483647` So it's range should be from `-4294967296` to `4294967296`.

The problem is that in MySQL regardless of the int length value the maximum value for an int column will always be a 4bytes integer meaning `2147483647` max, this results in possible impossible values to be saved in the stock movement table.

### Expected behavior

The database structure should be modified so that `stock_mvt.physical_quantity` should be a BIGINT thus allowing to have appropriate boundaries.

### Steps to reproduce

In the stock page or in the product page v2:

1. Edit the stock of the product to `2147483647` and save the value
2. Edit the stock to a `-2147483648` value
3. The stock should be updated but a MySQL error should happen when trying to create the row of the stock movement
4. Thus the stock movement is never saved

### PrestaShop version(s) where the bug happened

8.0 and probably before

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by margud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  develop
| Description?      | Fixed new product page combination quantity input issues. You can find information about the issues [here](https://github.com/orgs/PrestaShop/projects/7/views/18?filterQuery=scope%3A%22Product+Page+-+PS+8.0%22+product+page)
| Type?             | bug fix 
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes [#27313](https://github.com/PrestaShop/PrestaShop/issues/27313) and Fixes #29253
| How to test?      | All the information how to test it is added [here](https://github.com/orgs/PrestaShop/projects/7/views/18?filterQuery=scope%3A%22Product+Page+-+PS+8.0%22+product+page)

### CODE REVIEW

File: classes/ObjectModel.php [hunk 1]
```diff
@@ -1237,6 +1238,23 @@ public function validateField($field, $value, $id_lang = null, $skip = [], $huma
             }
         }
 
+        // check field range
+        if (!in_array('range', $skip) && isset($data['range']['min'], $data['range']['max'])) {
```
Comment (kpodemski) [inline classes/ObjectModel.php:1252]: Note: worth documenting.

File: admin-dev/themes/new-theme/js/components/components-map.ts [hunk 2]
```diff
@@ -89,6 +89,7 @@ export default {
   },
   deltaQuantityInput: {
     containerSelector: '.delta-quantity',
+    quantityInputSelector: '.delta-quantity-quantity',
```
Comment (kpodemski) [inline admin-dev/themes/new-theme/js/components/components-map.ts:92]: 🥴

Comment (kpodemski) [reply admin-dev/themes/new-theme/js/components/components-map.ts:92]: isn't it `delta-quantity-value`?

File: admin-dev/themes/new-theme/js/components/form/helpers.ts [hunk 3]
```diff
@@ -38,9 +38,17 @@
 export function notifyFormErrors(jsonResponse: any): void {
   Object.keys(jsonResponse.errors).forEach((field: string) => {
     if (Object.prototype.hasOwnProperty.call(jsonResponse.errors, field)) {
-      const fieldErrors: string[] = jsonResponse.errors[field];
-      const errors: string = fieldErrors.join(' ');
-      $.growl.error({message: `${field}: ${errors}`});
+      let fieldErrors: string[];
```
Comment (kpodemski) [inline admin-dev/themes/new-theme/js/components/form/helpers.ts:41]: If you modify global components, I think it would be worth commenting on what happened. It's not only related to your PR, it's a clear way to introduce bugs by fixing other bugs 👍

File: src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php [hunk 4]
```diff
@@ -107,14 +107,14 @@ public function getFormErrorsForJS(FormInterface $form)
         $translator = $this->get('translator');
 
         foreach ($form->getErrors(true) as $error) {
-            if (!$error->getCause()) {
-                $formId = 'bubbling_errors';
-            } else {
+            if ($error->getCause() && method_exists($error->getCause(), 'getPropertyPath')) {
```
Comment (kpodemski) [inline src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php:122]: Same as above. What happened there?

File: admin-dev/themes/new-theme/js/components/form/helpers.ts (hunk 3 above)
Comment (kpodemski) [reply admin-dev/themes/new-theme/js/components/form/helpers.ts:41]: Maybe it's a nitpick. I could use @jolelievre opinion there, but I guess he may know why you've changed that :D

File: admin-dev/themes/new-theme/js/components/components-map.ts (hunk 2 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/components-map.ts:92]: No it's the correct class, the DeltaQuantityType form type is composed of two fields:
- delta
- quantity

So this class name is consistent

File: admin-dev/themes/new-theme/js/components/form/helpers.ts (hunk 3 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/form/helpers.ts:41]: Actually it doesn't change the initial behaviour here, it only improves it, with this modifi `notifyFormErrors` can handle two format of error response:
- when `jsonResponse.errors[field]` is a string
- when `jsonResponse.errors[field]` is an array of string

So it's totally retro compatible

File: classes/ObjectModel.php (hunk 1 above)
Comment (jolelievre) [reply classes/ObjectModel.php:1252]:
```suggestion
        // Range validation allows you to check if the value is between the defined boundaries (min and max options)
        if (!in_array('range', $skip) && isset($data['range']['min'], $data['range']['max'])) {
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ *#}
+
+{% form_theme combinationsForm '@PrestaShop/Admin/Sell/Catalog/Product/FormTheme/combination_listing.html.twig' %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig:26]: It seems like this file is never used it should be removed

File: src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php (hunk 4 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php:122]: This one I don't know either

File: tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature [hunk 6]
```diff
@@ -254,3 +254,33 @@ Feature: Update product stock from Back Office (BO)
...
+    And product "product2" should have following stock information:
+      | quantity | 0 |
+    When I update product "product2" stock with following information:
+      | delta_quantity | -2147483648 |
+    And product "product2" should have following stock information:
+      | quantity | -2147483648 |
+    When I update product "product2" stock with following information:
+      | delta_quantity | 4294967295 |
+    And product "product2" should have following stock information:
+      | quantity | 2147483647 |
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature:273]: You should add changes with the biggest range -4294967295 and 4294967295 and heck the stock movements values like in update_combination_stock.feature

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig (hunk 5 above)
Comment (margud) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig:26]: Hmm about this one, i see that it was deleted by Lelievre some time ago, but the part where it is used was kept, so i added it back. You can find that its used in CombinationController::updateCombinationFromListingAction
`    return $this->json([
                    'errors' => $this->getFormErrorsForJS($combinationsListForm),
                    'formContent' => $this->renderView('@PrestaShop/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig', [
                        'combinationsForm' => $combinationsListForm->createView(),
                    ]),
                ], Response::HTTP_BAD_REQUEST);`

File: src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php (hunk 4 above)
Comment (margud) [reply src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php:122]: Dont remember now how to reproduce it but remember that there was case where $error->cause was not null but it didnt had getPropetyPath and because of that the str_replace would break. It just adds extra check to make sure that function inside can be completed without throwing exception

**Review by zuk3975 — DISMISSED** [review]
waiting Joe confirmation on this https://github.com/PrestaShop/PrestaShop/pull/30592#discussion_r1069049038, but It seems Marius is right

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/combination_list_form.html.twig:26]: Oh you're right!! It's used to render the form with errors, my bad

File: tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature (hunk 6 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature:273]: Sorry my comment wasn't clear enough, w need to check that we can use the maximum delta values here, you already tested with `delta_quantity = 4294967295` you need to add one with `delta_quantity = -4294967295`
And at then end you need to use the stock movement step like:

```
    And product "product2" last stock movements should be:
      | employee   | delta_quantity |
      | Puff Daddy | -4294967295 |
      | Puff Daddy | 4294967295 |
      | Puff Daddy | -2147483648 |
```

Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Product/update_stock.feature:273]: Sorry to be picky about this one, it's to make sure that:
- we can actually use the maximum range
- that it is correctly saved in the stock movement table
- that the DB won't be modified and change our max range without notice

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

Just a last improvement on behat test and it's ok for me

File: vendor/.htaccess [hunk 7]
```diff
@@ -1,10 +0,0 @@
-# Apache 2.2
```
Comment (jolelievre) [inline vendor/.htaccess]: Careful I think you removed this file and commited the change by mistake, you need to revert this change and then it's good forme

**Review by zuk3975 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @margud

**Comment by florine2623** [comment]
Hello @margud @PrestaShop/prestashop-core-developers ,

I have an error when launching automated tests :
https://github.com/florine2623/testing_pr/actions/runs/4024943882/jobs/6917879313

Can i get a rebase please ?

**Comment by jolelievre** [comment]
I think you also need to rebase it considering the tests that are failing

**Review by zuk3975 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by jolelievre** [comment]
Campaign running https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4084727301

**Review by zuk3975 — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @margud @jolelievre ,

#29253 has been tested :x:

**In Stock page** :

`2147483648` :x:
`-2147483648` ✅ 

https://user-images.githubusercontent.com/16019289/216976710-568ed36e-3df6-4ea3-8dbd-6af1ca3913fd.mov

`2147483647` ✅ 
Screenshot 2023-02-06 at 13 55 43

**In Product page** :

`-2147483648` ✅ 
Screenshot 2023-02-06 at 13 59 03

`2147483648` :x:
Screenshot 2023-02-06 at 13 58 49

#27313 has been tested 

**First issue** ✅  no exception displayed, error message explained for each field

https://user-images.githubusercontent.com/16019289/216979956-5581b691-75c3-4ee7-81fa-f28a35eab861.mov

**Second issue** ✅ 
On Standard products and on combination products

https://user-images.githubusercontent.com/16019289/216980878-5d1afd7e-607f-4ff3-be33-26459361db5e.mov

https://user-images.githubusercontent.com/16019289/216981477-ebcc530a-691e-495f-8a81-b94f140afd9a.mov

**Third issue** ✅ 

https://user-images.githubusercontent.com/16019289/216986599-30034e6a-a6ff-4772-a917-3821c61e8c2d.mov

**Fourth issue** ✅  no exception displayed, error message explained for each field

https://user-images.githubusercontent.com/16019289/216982762-87abc21d-5ef1-4bfc-b75b-f6d48f0f8335.mov

**Fifth issue** :x: 
I have an error message when trying to save the quantity -> I close the error message -> It shows me the quantity delta x 2 -> I can Save the quantity delta > Update Successful -> Nothing has been saved.
Can I have your point of view @MatShir ? What should be the expected behavior in this case ?

https://user-images.githubusercontent.com/16019289/216984156-a00d870e-8f99-4d9e-bca2-92096d36f737.mov

**Sixth issue** LGTM ✅ 
I don't have access to the screen record. This is what I understood :

https://user-images.githubusercontent.com/16019289/216985197-e6f128da-8ea8-4207-8219-de04fa3fa3eb.mov

**Seventh issue** ✅ 
Screenshot 2023-02-06 at 14 39 00

**Eighth issue** ✅ 

https://user-images.githubusercontent.com/16019289/216987042-7883fc88-1231-46a2-86e1-53a3968b9cd8.mov

-> In conclusion, only 2 issues are not fixed : #29253 and fifth issue of #27313 💪 

Do not hesitate to reping me !

**Review by jolelievre — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hey @jolelievre ,

Link to automated tests : https://github.com/florine2623/testing_pr/actions/runs/4122431669

The 2 issues from my previous comments are fixed.

**First one :**
https://github.com/PrestaShop/PrestaShop/issues/29253 ✅ 
Screenshot 2023-02-08 at 11 10 01
Tested with quantity `2147483647`, OK

**Second one :**
Fifth issue of https://github.com/PrestaShop/PrestaShop/issues/27313 ✅ 
Number with comma are not saved as expected.

As discussed previously, in https://github.com/PrestaShop/PrestaShop/issues/31110, 2 elements are fixed in this PR : 

- Remove the reset button from combination list

| Before  | After |
| ------------- | ------------- |
| Screenshot 2023-02-08 at 12 14 31  | Screenshot 2023-02-08 at 12 14 23 |

- Enable edition mode when key is pressed (not only on change when losing focus from the input)

https://user-images.githubusercontent.com/16019289/217525425-2e8fa4d1-2487-4872-8fa9-5666ba380987.mov

**New bug found** 

Here are the steps to reproduce :
- Go to BO > Catalog > Products page > Edit a product with combinations V2
- In the combinations Tab > Edit your quantity to 0
- Add quantity 2147483646
- Save > See exception
`0: An unexpected error occurred. [PrestaShop\PrestaShop\Core\Exception\CoreException code 0]: Error occurred when trying to update StockAvailable #47 [The range of property StockAvailable->quantity is currently 2147484546. It must be between -2147483648 and 2147483647.]`
- Add a smaller quantity 12
- Save > See error and can't modifiy the quantity
`0: The "Quantity" field is invalid.`

As it is out-of-scope, an issue has been created
https://github.com/PrestaShop/PrestaShop/issues/31277

This PR is valid and QA ✅ 
Thanks 💪

**Comment by jolelievre** [comment]
Thanks @margud and @florine2623

**Comment by Hlavtox** [comment]
@margud We will need the autoupgrade PR, tests will begin soon.

**Comment by Hlavtox** [comment]
@jolelievre @margud I think we need to also change the install database structure no? https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/db_structure.sql

**Comment by jolelievre** [comment]
@Hlavtox as discussed on slack since the modification is done on one of our rare Doctrine entities, it's not needed to update the db_structure.sql file, as the doctrine command will take care of it (both for install and upgrade). It's an exception compared to all the other entities based on ObjectModel only.
