### PR TITLE
Fix no active payment module displayed in Payment Methods

### LINKED ISSUE #24463: BO - Welcome module - Th pop up onboarding is not displayed in the step3/6 "step1" &  step4/6 "step2"
#### To do 
Fix the issue on the module and release it 

#### Describe the bug

When the `ps_mbo` module is installed, the popup onboarding is not displayed at step 4/6 "Get your shop ready for Payment" step2
on_boarding_no_pop_up
Version ps_mbo =2.0.1.
 the popup onboarding is not displayed at step 3/6 "Give your shop its own identity" step1 when ps_mbo installed and uninstalled

#### Expected behavior

The popup onboarding should be displayed

#### Steps to Reproduce

1. Fresh install 178 with English language & France country
2. Go to BO
3. Follow the welcome instructions
4. See error ate step 3/6 & step4/6

PS 1774 + Welcome v6.0.4 => ok

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2
* Welcome: v6.0.4

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Since #19944, `_PS_TAB_MODULE_LIST_URL_` is defined as an empty string but in `PaymentModulesPresenter::present()`, `tabModuleListProvider->getTabModules()` calls [`Tab::getTabModulesList()`](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/Tab.php#L704) that relies on `_PS_TAB_MODULE_LIST_URL_` which leads to an empty list of modules in Payments > Payment Methods. This PR fixes it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | Fixes partially #24463
| How to test?      | See #24463, second step of step 4/6 should be working
| Possible impacts? | 

## 📓 Deprecation
`\PrestaShop\PrestaShop\Adapter\Module\Presenter\PaymentModulesPresenter`
use `\PrestaShop\PrestaShop\Adapter\Presenter\Module\PaymentModulesPresenter` instead

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24869)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Idea: since we change almost all the code of PaymentModulesPresenter, maybe we could deprecate it entirely and use a new class instead (to avoid the constructor BC break)

File: src/Adapter/Module/Presenter/PaymentModulesPresenter.php [hunk 1]
```diff
@@ -86,23 +68,11 @@ public function __construct(
      */
     public function present()
```
Comment (Progi1984) [inline src/Adapter/Module/Presenter/PaymentModulesPresenter.php]: Could you add unit test, please ?

**Review by Progi1984 — COMMENTED** [review]
A last comment

File: src/Adapter/Module/Presenter/PaymentModulesPresenter.php [hunk 2]
```diff
@@ -31,8 +31,17 @@
...
+        '%s is deprecated since version 1.7.8.0 and will be removed in the next major version.',
+        PaymentModulesPresenter::class
+    ),
+    E_USER_DEPRECATED
+);
+
 /**
- * Class PaymentModulesPresenter is responsible for presenting payment modules.
+ * @deprecated since 1.7.8.0
+ * @see \PrestaShop\PrestaShop\Adapter\Presenter\Module\PaymentModulesPresenter
```
Comment (jolelievre) [inline src/Adapter/Module/Presenter/PaymentModulesPresenter.php:44]: This class was based on `TabModuleListProvider` apparently, which itself relied on the removed file So maybe we also should deprecated the `TabModuleListProvider` class? Along with the `prestashop.adapter.module.data_provider.tab_module_list` service?

File: src/Adapter/Presenter/Module/PaymentModulesPresenter.php [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+    }
+
+    /**
+     * Get presented payment modules.
+     *
+     * @return array
+     */
+    public function present(): array
+    {
+        $installedModules = $this->paymentModuleListProvider->getPaymentModuleList();
```
Comment (jolelievre) [inline src/Adapter/Presenter/Module/PaymentModulesPresenter.php:68]: Seems like this provider only relies on Addons repository calls, no problem for this version But I guess we'll need to be careful when we're gonna merge this into the next version because of the split right?

@PierreRambaud wdyt?

**Review by jolelievre — COMMENTED** [review]
Other than deprecating another service/class it seems all good to me.

File: src/Adapter/Presenter/Module/PaymentModulesPresenter.php [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace PrestaShop\PrestaShop\Adapter\Presenter\Module;
```
Comment (Progi1984) [inline src/Adapter/Presenter/Module/PaymentModulesPresenter.php]:
```suggestion
 */
 
 declare(strict_types=1);

namespace PrestaShop\PrestaShop\Adapter\Presenter\Module;
```

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

File: src/Adapter/Presenter/Module/PaymentModulesPresenter.php (hunk 3 above)
Comment (PierreRambaud) [reply src/Adapter/Presenter/Module/PaymentModulesPresenter.php:68]: Yes exactly

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

I checked with your PR :
- Part 2 of step 4 of the onboarding is displayed : OK
- Rest of the onboarding : OK
- Display of payment modules in Payment > Payment Methods : OK
- Add a new payment method via Payment > Payment Methods page : OK
- Add a new payment method via Module Catalog : OK
- Configure a module added during installation via Payment Methods page : OK
- Configure a module installed on Payment Methods or Module Catalog via Payment Methods page : OK

So it's QA :heavy_check_mark: ! Thanks :)

**Comment by jolelievre** [comment]
Thank you @atomiix
