### PR TITLE
Fix module catalog js & css issues

### LINKED ISSUE #10661: Number of modules displayed isn't ok
**Describe the bug**
If you select a category on the module page, the number of modules displayed isn't good

**To Reproduce**
1. Go to Module Catalog page
2. Select a category
3. Look the number of modules displayed

**Screenshots**

capture d ecran_295

It worked in 1.7.4.2

capture d ecran_296

**Additionnal information**
PrestaShop version: 1.7.5.X
PHP version: N/A

### LINKED ISSUE #10663: Bulk actions on Module manager page doesn't work
**Describe the bug**
Try to make an action in bulk on the module manager page

**To Reproduce**
1. Go to Modules Manager
2. Select 2 modules or more
3. Click on disable/uninstall/enable/install/reset/enable mobile/disable mobile

**Screenshots**
capture d ecran_297

capture d ecran_298

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### LINKED ISSUE #10665: Can't configure a module imported by zip
**Describe the bug**
Can't configure a module imported by zip

**To Reproduce**
1. Go to Modules Manager
2. Click on Install a module
3. Upload your zip
4. Click on Configure
5. The URL isn't the good one

**Screenshots**

capture d ecran_301

capture d ecran_300

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### LINKED ISSUE #10666: Incomplete line on Module catalog page
**Describe the bug**
Line with 2 modules instead of 4 on Module catalog page

**To Reproduce**
1. Go to Module catalog
2. You can see a line with only 1 or 2 modules instead of 4

**Screenshots**
capture d ecran_302

capture d ecran_304

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### LINKED ISSUE #10667: Height of cards on module catalog page
**Describe the bug**
The height of cards on module catalog page isn't the same for all cards

**To Reproduce**
1. Go to Modules catalog
2. Try to resize the window
3. Look at the cards

**Screenshots**
capture d ecran_303

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### LINKED ISSUE #10676: Sort on Module catalog page
**Describe the bug**
Sorts are not working on module catalog page

**To Reproduce**
1. Go to Modules catalog
2. Click on Decreasing price/Increasing price/Name
3. See results are not ok

**Screenshots**
capture d ecran_312

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Js & css issues
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10676<br/>Fixes #10667<br/>Fixes #10666<br/>Fixes #10663<br/>Fixes #10661<br/>Fixes #10665
| How to test?  | Follow issues instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10681)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 1]
```diff
@@ -224,11 +224,19 @@ class AdminModuleController {
...
   }
 
   onModuleDisabled() {
-    this.getModuleItemSelector();
-    // Don't care nothing to do?
+    const self = this;
+    const moduleItemSelector = self.getModuleItemSelector();
+
+    $('.modules-list').each(function scanModulesList() {
+      self.updateTotalResults(
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: Is it me or this method doesn't accept arguments?

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 2]
```diff
@@ -1124,6 +1134,44 @@ class AdminModuleController {
...
+      // If there is no shortlist: the wording directly update from the only module container.
+    } else {
+      const modulesCount = $('.modules-list').find('.module-item').length;
+      updateText($('.module-search-result-wording'), modulesCount);
+
+      if (self.currentDisplay === self.DISPLAY_LIST) {
+        $(this.addonItemListSelector).toggle(modulesCount !== (this.modulesList.length / 2));
+      } else {
+        $(this.addonItemGridSelector).toggle(modulesCount !== (this.modulesList.length / 2));
+      }
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: I think this could be simplified like this:

```js
const selectorToToggle = (self.currentDisplay === self.DISPLAY_LIST)? this.addonItemListSelector : this.addonItemGridSelector;
$(selectorToToggle).toggle(modulesCount !== (this.modulesList.length / 2));
```

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 3]
```diff
@@ -1124,6 +1134,44 @@ class AdminModuleController {
...
+
+      if (modulesCount === 0) {
+        $('.module-addons-search-link').attr(
+          'href',
+          `${this.bsaeAddonsUrl}search.php?search_query=${encodeURIComponent(this.currentTagsList.join(' '))}`
+        );
+      }
+    }
+
+    function updateText(element, value) {
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: Functions must be declared as named function expressions (see [7.1](https://github.com/airbnb/javascript#functions--declarations)).

```js
const updateText = function aMoreDescriptiveAndUniqueName(element, value) { //...
```

To avoid hoisting problems, make sure to declare functions _before_ they are used (see [no-use-before-define](https://eslint.org/docs/rules/no-use-before-define)).

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 1 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: True, it's a function from the old js =)

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 2 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Done. Thanks!

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 3 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Done. Thanks!

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 1 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Done!

File: src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig [hunk 4]
```diff
@@ -39,13 +39,13 @@
       {% include 'PrestaShopBundle:Admin/Module/Includes:menu_top.html.twig' with { 'topMenuData': topMenuData, 'bulkActions': bulkActions } %}
 
       <div id="module-recently-used-list" class="module-short-list">
-        <span id="recently-used_modules" class="module-search-result-wording">{{ 'Recently Used' | trans({}, 'Admin.Modules.Feature') }}</span>
+        <span id="recently-used_modules" class="module-search-result-title">{{ 'Recently Used' | trans({}, 'Admin.Modules.Feature') }}</span>
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig:42]: Please no useless upper case: _Recently used_. Domains are fine otherwise.

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 5]
```diff
@@ -1166,11 +1162,11 @@ class AdminModuleController {
       }
     }
 
-    function updateText(element, value) {
+    const updateText = (element, value) => {
       const explodedText = element.text().split(' ');
       explodedText[0] = value;
       element.text(explodedText.join(' '));
-    }
+    };
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: As I said before, you'll have hoisting problems if you declare a function _after_ it's used. Please declare functions _before_ using them.

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig (hunk 4 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Module/manage.html.twig:42]: Was already defined like that in another PR :/

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 5 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Done, my bad!

**Review by eternoendless — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 6]
```diff
@@ -734,7 +741,7 @@ class AdminModuleController {
     self.animateEndUpload(() => {
       if (result.status === true) {
         if (result.is_configurable === true) {
-          const configureLink = window.moduleURLs.configurationPage.replace('1', result.module_name);
+          const configureLink = window.moduleURLs.configurationPage.replace(/:number:/, result.module_name);
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/module/controller.js:744]: 👍

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 7]
```diff
@@ -1124,6 +1131,43 @@ class AdminModuleController {
...
+    };
+
+    // If there are some shortlist: each shortlist count the modules on the next container.
+    const $shortLists = $('.module-short-list');
+    if ($shortLists.length > 0) {
+      $shortLists.each(function shortLists() {
+        const $this = $(this);
+        updateText(
+          $this.find('.module-search-result-wording'),
+          $this.next('.modules-list').find('.module-item').length
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: Missing semi-colon

File: src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig [hunk 8]
```diff
@@ -1,48 +1,48 @@
...
-                  <option value="price">{{ 'Increasing Price'|trans({}, 'Admin.Modules.Feature') }}</option>
-                  <option value="price-desc">{{ 'Decreasing Price'|trans({}, 'Admin.Modules.Feature') }}</option>
-                  <option value="scoring-desc">{{ 'Popularity'|trans({}, 'Admin.Modules.Feature') }}</option>
-                </select>
-            </div>
-        </div>
+  <div class="row">
+    <div class="col-lg-6">
+      <div class="module-sorting-search-wording">
+        <span id="selected_modules" class="module-search-result-title module-search-result-wording">{{ '%nbModules% modules and services selected for you'|trans({'%nbModules%' : totalModules}, 'Admin.Modules.Feature') }}</span>
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig:29]: Line too long

File: src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig [hunk 9]
```diff
@@ -1,48 +1,48 @@
...
+        <span class="help-box" data-toggle="popover"
+          data-title="{{ "Selection"|trans({}, 'Admin.Modules.Feature') }}"
+          data-content="{{ "Customize your store with this selection of modules recommended for your shop, based on your country, language and version of PrestaShop. It includes the most popular modules from our Addons marketplace, and free partner modules."|trans({}, 'Admin.Modules.Help') }}">
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig:32]: Line too long

File: src/PrestaShopBundle/Resources/views/Admin/Module/catalog-refresh.html.twig [hunk 10]
```diff
@@ -22,6 +22,10 @@
   * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
   * International Registered Trademark & Property of PrestaShop SA
   *#}
-{% for category in categories.subMenu %}
-  {% include 'PrestaShopBundle:Admin/Module/Includes:grid.html.twig' with { 'modules': category.modules, 'display_type': 'grid', 'id': category.refMenu } %}
-{% endfor %}
+<div id="modules-list-container-all" class="row modules-list" style="display: flex;" data-name="all">
+  {% for category in categories.subMenu %}
+    {% for module in category.modules %}
+      {% include 'PrestaShopBundle:Admin/Module/Includes:card_grid.html.twig' with { 'module': module, 'origin': origin|default('none'), 'level' : level, 'category': category.refMenu } %}
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Module/catalog-refresh.html.twig:28]: Line too long

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 11]
```diff
@@ -1124,6 +1131,43 @@ class AdminModuleController {
...
+
+      const selectorToToggle = (self.currentDisplay === self.DISPLAY_LIST) ?
+                               this.addonItemListSelector :
+                               this.addonItemGridSelector;
+      $(selectorToToggle).toggle(modulesCount !== (this.modulesList.length / 2));
+
+      if (modulesCount === 0) {
+        $('.module-addons-search-link').attr(
+          'href',
+          `${this.bsaeAddonsUrl}search.php?search_query=${encodeURIComponent(this.currentTagsList.join(' '))}`
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: `bsaeAddonsUrl` > `baseAddonsUrl`

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 12]
```diff
@@ -1124,6 +1131,43 @@ class AdminModuleController {
...
+
+      // If there is no shortlist: the wording directly update from the only module container.
+    } else {
+      const modulesCount = $('.modules-list').find('.module-item').length;
+      updateText($('.module-search-result-wording'), modulesCount);
+
+      const selectorToToggle = (self.currentDisplay === self.DISPLAY_LIST) ?
+                               this.addonItemListSelector :
+                               this.addonItemGridSelector;
+      $(selectorToToggle).toggle(modulesCount !== (this.modulesList.length / 2));
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/module/controller.js:1161]: I do not understand why we should toggle based on whether the module count is equal to half the module list length ^^. What is the meaning ?

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 13]
```diff
@@ -1124,6 +1131,43 @@ class AdminModuleController {
       self.updateModuleVisibility();
     });
   }
+
+  updateTotalResults() {
+    const updateText = (element, value) => {
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]: Can we find something more accurate that `updateText()` ? It looks like something close to `replaceFirstWordBy()` ?

File: src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig (hunk 8 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig:29]: Was the old file, just fix the indentation and little class changes :/

File: src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig (hunk 9 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig:32]: Was the old file, just fix the indentation and little class changes :/

File: src/PrestaShopBundle/Resources/views/Admin/Module/catalog-refresh.html.twig (hunk 10 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Module/catalog-refresh.html.twig:28]: Was the old file, just fix the indentation and little class changes :/

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 12 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js:1161]: Don't ask me something I don't understand too :D I copy paste this part of code from the old module.js file :trollface:

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 13 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Thanks I will change it :D

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 11 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Thanks I will change it :D

**Review by matks — APPROVED** [review]
