### PR TITLE
Generate product categories breadcrumb accordingly to accessed category

### LINKED ISSUE #30547: Product breadcrumb is not generated accordingly to accessed category.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you assign a category to : 

- `Home / Category A / Category B`
- `Home / Category C / Category D /  Category E`

And assign the default category "Category B".

If you access the product from ` Home / Category C / Category D /  Category E` 
The generated breadcrumb will be `Home / Category A / Category B` because de Product Controller uses by default the product default category.

Fixed by PR #30546

### Expected behavior

If I'm accessing the product from ` Home / Category C / Category D /  Category E` 
I exped the breadcrumb to be ` Home / Category C / Category D /  Category E / My Product` 

### Steps to reproduce

1. Assign a product to two categories  : 

- `Home / Category A / Category B`
- `Home / Category C / Category D /  Category E`

2. Assign default category to `Category B`

3. Access the product from the catalog by using  `Home / Category C / Category D /  Category E` path
4. See that the generaed breadcrumb is `Home / Category A / Category B`

### PrestaShop version(s) where the bug happened

1.7.8.*

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Dreimus**
If the product is accessed from another category than product default category, it will generate the breadcrumb according to current category.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | By default, product breadcrumb is generated by using product default category. With this feature, if a category is stored on the product controller and assigned to the viewed product, the breadcrumb will be generated accordingly. 
| Type?             | improvement 
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?       | Fix https://github.com/PrestaShop/PrestaShop/issues/30547
| UI Test       | https://github.com/florine2623/testing_pr/actions/runs/8247064149
| Related PRs       | [30522](https://github.com/PrestaShop/PrestaShop/pull/30522)
| How to test?      | Assign a product to two categories, and access on both categories to this product. Expect the breadcrumb to be generated accordingly to accessed category.

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
This behavior you are implementing was present in Prestashop 1.6 and got changed to default category in Prestashop 1.7. 

A lot of people (including me) modified it back then to the current behavior, because we always want the default category in breadcrumbs.

Example: https://www.prestashop.com/forums/topic/167513-how-to-show-the-full-breadcrumb-to-the-default-category-on-every-product-page/

If you want to change this, please add a new configuration option to Prestashop settings along with it, so we don't upset anybody. Something like "Category in product breadcrumbs" - "The category product was accessed from" / "Default category of the product (default)".

Ping @kpodemski

**Comment by Dreimus** [comment]
@Hlavtox I've implemented the force default category option in `configure/shop/product-preferences` page.

Waiting for your feedback

**Comment by Hlavtox** [comment]
@Dreimus Nice, what would you say if we changed it to selectbox? I get your idea, but I would keep the current behavior safely default. 

### My proposition for configuration
- Configuration value: PS_PRODUCT_BREADCRUMB_CATEGORY
- Name: Category used in breadcrumbs
- Helper: Select what category you want to display in breadcrumbs on product page. It could be always the default category of the product, or the category the customer came from.
- Options:
  - `default` - Product default category
  - `current` - Category the product was accessed from

### Screenshot
breadcrumbs

Then in front office, just check if PS_PRODUCT_BREADCRUMB_CATEGORY == 'current', else use default category.

Last question - do we need this check? 🤔 `in_array($this->category->id_category, $this->product->getCategories(), true)`, if the user came from that category, the product must be shown there no?

**Comment by Dreimus** [comment]
Hello @Hlavtox,

I wonder if a select is usefull as there is only two choices available. But I can change it if you want, but is it really worth it ?

Moreover, I'm afraid that the mapping between PS_PRODUCT_BREADCRUMB_CATEGORY values and conditions might be lost if we don't have an enum with the available values, what do you think ?

For the category evaluation, I did not tried, but what happen if you are in a specific category, and click on a "featured product" area for example ? The test is preventing this type of cases.

**Comment by Hlavtox** [comment]
@Dreimus Well, firstly, your proposed behavior could be useful for some people, but there was not a single issue opened about this in all those years 1.7 is out. So, I want the current behaviour to be safely default. 👍

I would like to use it instead of a switch because:
A) Better explanation of the options, instead of a YES/NO. It also puts the two options the same "weight".
B) "Force default category use for breadcrumb generation" looks like your behavior should be default and there is a danger of changing people's behavior. If the value is not configured, it should safely default to current behavior.

**Comment by Dreimus** [comment]
@Hlavtox applied your suggestions to the code.

**Review by Hlavtox — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@Dreimus Looks good to me Paul!

Maybe we can simplify this? I changed the validation to validate class, which will check it properly, there could be a faulty object in it maybe. And I don't think we need to check if the category is in there, it will bring additional queries that are not needed.

```
// We can generate breadcrumbs in two possible ways:
// current: Category the product was accessed from
// default: Product default category

if ('current' === Configuration::get('PS_PRODUCT_BREADCRUMB_CATEGORY') && Validate::isLoadedObject($this->category)) {
  $productBreadcrumbCategory = $this->category;
} else {
  $productBreadcrumbCategory = new Category($this->product->id_category_default, $this->context->language->id);
}
```

**Comment by Hlavtox** [comment]
We also need to fix tests, there are two codestyle issues:
https://github.com/PrestaShop/PrestaShop/actions/runs/3677618114/jobs/6234744346

**Comment by Hlavtox** [comment]
@l-delin Hello, can we get a wording check here? :-)

**Comment by Dreimus** [comment]
@Hlavtox I just fixed the cs fixer issues + removed the product category check.

Tell me if you need more infos.

File: src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php [hunk 1]
```diff
@@ -140,6 +140,23 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                    'Admin.Shopparameters.Feature'
+                ),
+                'choices' => [
+                    'Product default category' => 'default',
+                    'Category the product was accessed from' => 'current',
+                ],
+                'choice_translation_domain' => 'Admin.Global',
+                'placeholder' => false,
+                'help' => $this->trans(
+                    'Select what category you want to display in breadcrumbs on product page. It could be always the default category of the product, or the category the customer came from.',
```
Comment (l-delin) [inline src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]:
```suggestion
                    'Select which category to display on the product page breadcrumbs. It can be the default category of the product or the category the customer came from.',
```

**Comment by l-delin** [comment]
> @l-delin Hello, can we get a wording check here? :-)

done! 🎄

**Comment by Dreimus** [comment]
@l-delin translations updated, thanks !

**Review by Hlavtox — DISMISSED** [review]

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -1319,13 +1319,29 @@ protected function getRequiredQuantity($product)
         return $requiredQuantity;
     }
 
-    public function getBreadcrumbLinks()
+    /**
+     * Generates breadcrumb according to product categories and his category subtree.
```
Comment (SharakPL) [inline controllers/front/ProductController.php]:
```suggestion
     * Generates breadcrumb according to product category tree.
```

File: src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php [hunk 3]
```diff
@@ -140,6 +140,23 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                    'Admin.Shopparameters.Feature'
+                ),
+                'choices' => [
+                    'Product default category' => 'default',
+                    'Category the product was accessed from' => 'current',
+                ],
+                'choice_translation_domain' => 'Admin.Global',
+                'placeholder' => false,
+                'help' => $this->trans(
+                    'Select which category to display on the product page breadcrumbs. It can be the default category of the product or the category the customer came from.',
```
Comment (l-delin) [inline src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]:
```suggestion
                    'Select which category to display on the product page breadcrumbs. It can be the product\'s default category or the category the customer came from.',
```

Comment (Hlavtox) [reply src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]: @Dreimus Don't forget to to escape the quote - `product\'s`

Comment (l-delin) [reply src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]: Ahh so that's why it was red 🙌 thank you!

File: controllers/front/ProductController.php [hunk 4]
```diff
@@ -1319,13 +1319,29 @@ protected function getRequiredQuantity($product)
...
+    public function getBreadcrumbLinks(): array
     {
         $breadcrumb = parent::getBreadcrumbLinks();
 
-        $categoryDefault = new Category($this->product->id_category_default, $this->context->language->id);
+        // $productBreadcrumbCategory can have two possible values
+        // - current : Category the product was accessed from
+        // - default : Product default category
+        if (('current' === Configuration::get('PS_PRODUCT_BREADCRUMB_CATEGORY')) &&
+            !is_null($this->category)) {
```
Comment (kpodemski) [inline controllers/front/ProductController.php]:
```suggestion
        if (('current' === Configuration::get('PS_PRODUCT_BREADCRUMB_CATEGORY'))) {
```

Is there any scenario when category could be null? 🤔

File: src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php [hunk 5]
```diff
@@ -140,6 +140,23 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
                 'required' => false,
             ])
+            ->add('product_breadcrumb_category', ChoiceType::class, [
+                'label' => $this->trans(
+                    'Category used in breadcrumbs',
+                    'Admin.Shopparameters.Feature'
+                ),
+                'choices' => [
+                    'Product default category' => 'default',
+                    'Category the product was accessed from' => 'current',
```
Comment (kpodemski) [inline src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]:
```suggestion
                    'Product default category' => 'default',
                    'Category the product was accessed from' => 'current',
```

Those two keys should be translatable phrases

File: controllers/front/ProductController.php (hunk 4 above)
Comment (Hlavtox) [reply controllers/front/ProductController.php]: Product not assigned to any category, or it's category was deleted and it wasn't handled properly.

**Comment by kpodemski** [comment]
Hi @Dreimus 

This PR is very close to being finished. Could you look at our comments and also see a comment from PM on the related Issue?

**Comment by Dreimus** [comment]
Hello @kpodemski , 

I updated the comments, tell me if you need anything more.

File: src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php (hunk 5 above)
Comment (kpodemski) [reply src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]: ping @Dreimus :)

Comment (Dreimus) [reply src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]: @kpodemski, I just added the capability

File: src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php [hunk 6]
```diff
@@ -140,6 +140,23 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
                 'required' => false,
             ])
+            ->add('product_breadcrumb_category', ChoiceType::class, [
+                'label' => $this->trans(
+                    'Category used in breadcrumbs',
+                    'Admin.Shopparameters.Feature'
+                ),
+                'choices' => [
+                    $this->trans('Product default category','Admin.Shopparameters.Feature') => 'default',
+                    $this->trans('Category the product was accessed from','Admin.Shopparameters.Feature') => 'current',
```
Comment (kpodemski) [inline src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/ProductPreferences/GeneralType.php]:
```suggestion
                    $this->trans('Product default category', 'Admin.Shopparameters.Feature') => 'default',
                    $this->trans('Category the product was accessed from', 'Admin.Shopparameters.Feature') => 'current',
```

**Comment by LameuleFR** [comment]
Hi,

Any news regarding to this?

**Comment by kpodemski** [comment]
Hi @Dreimus 

I see two missing things, if I'm not mistaken. There's a https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/configuration.xml, and you should add a default value of the configuration there. This PR will require autoupgrade PR, so it sets the configuration value.

Similar to https://github.com/PrestaShop/autoupgrade/pull/565 but for 9.0.0.sql :)

**Comment by Hlavtox** [comment]
Ping @Dreimus

**Comment by Dreimus** [comment]
@kpodemski i updated the configuration file ( and rebased onto develop ), I'll do the PR in autoupgrade projet now.

**Comment by kpodemski** [comment]
@Dreimus awesome 🎉 thank you

File: controllers/front/ProductController.php [hunk 7]
```diff
@@ -1350,13 +1350,29 @@ protected function getRequiredQuantity(array $product)
         return $requiredQuantity;
     }
 
-    public function getBreadcrumbLinks()
+    /**
+     * Generates breadcrumb according to product category tree.
+     * If the product is accessed from another category than product default category, it will generate the breadcrumb according to current category.
```
Comment (Hlavtox) [inline controllers/front/ProductController.php:1355]: please add "if enabled with PS_PRODUCT_BREADCRUMB_CATEGORY"

File: controllers/front/ProductController.php [hunk 8]
```diff
@@ -1350,13 +1350,29 @@ protected function getRequiredQuantity(array $product)
...
+    public function getBreadcrumbLinks(): array
     {
         $breadcrumb = parent::getBreadcrumbLinks();
 
-        $categoryDefault = new Category($this->product->id_category_default, $this->context->language->id);
+        // $productBreadcrumbCategory can have two possible values
+        // - current : Category the product was accessed from
+        // - default : Product default category
+        if (('current' === Configuration::get('PS_PRODUCT_BREADCRUMB_CATEGORY')) &&
+            !is_null($this->category)) {
```
Comment (Hlavtox) [inline controllers/front/ProductController.php]:
```suggestion
            !empty($this->category)) {
```

**Comment by Hlavtox** [comment]
Minor comments, but we can approve!

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
FYI @MatShir because I don't know if you've seen this PR :)

**Comment by MatShir** [comment]
Oh very nice ! 🚀 
Nice work @Dreimus 💪

**Review by jolelievre — APPROVED** [review]
Thanks @Dreimus 

@Progi1984 I wonder if some UI tests would be interesting for this new feature, to avoid any unwanted regression, not in this PR but it could be a scenario worth being added in your future roadmap?

**Comment by Progi1984** [comment]
@jolelievre It's in discussion with the @PrestaShop/qa-functional team.

[EDIT] : @jolelievre > @paulnoelcholot will contact you.

**Review by florine2623 — APPROVED** [review]
Hello @Dreimus ,

Tested both options :
Screenshot 2024-03-14 at 17 52 10

Breadcrumb from Preview is always Default category ✅ 
Breadcrumb from Categories is Default category is first option is chosen ✅ 
Breadcrumb from Categories is the category you came from if you chose the second option ✅ 

https://github.com/PrestaShop/PrestaShop/assets/16019289/0693e794-7487-4396-96ad-092e6f5245ab

Tested with multiple subcategories.
Tested with disabled categories.
I have found a bug not related to this PR https://github.com/PrestaShop/PrestaShop/issues/35654

This is QA ✅ 
Thanks!
