### PR TITLE
Eco tax fixed for combination price

### LINKED ISSUE #29330: BO - Product V2 - Final price (tax excl.) is not correct when applying ecotax on a combination
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-974372319
BO - Product V2 - Final price (tax excl.) is not correct when applying ecotax on the combination

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > International > Taxes > Enable ecotax without tax rule
2. Go to BO > Catalog > Product V2
3. Create a product with combinations > In the pricing tab: tax rule = 20% Retail price = 0 / ecotax = 0 )
4. Generate a combination & edit it > impact on price tax included = 12 / impact on price tax excluded = 10
5. Add an ecotax = 1 & save
image
6. See error in the combination list > `Final price (tax excl.)` is NOK 
image

Product V1 => OK
image

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by margud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Added logic where eco tax is added to combinations total price image
| Type?             | improvement 
| Category?         |  BO 
| BC breaks?        | no
| Fixed ticket?     | Fixes #29330
| How to test?      | When eco tax is added, it should be added on combination total price in admin product page

### CODE REVIEW

**Review by zuk3975 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts [hunk 1]
```diff
@@ -276,7 +277,15 @@ export default class CombinationsListRenderer {
...
     const $finalPrice = $(CombinationsMap.list.finalPrice, $row);
     const $finalPricePreview = $finalPrice.siblings(CombinationsMap.list.finalPricePreview);
-    const finalPrice = this.productFormModel.displayPrice(productPrice.plus(priceImpactTaxExcluded));
+    let combinationPrice = productPrice.plus(priceImpactTaxExcluded);
+
+    const ecoTax = $(ProductPriceMap.ecoTaxTaxExcluded).val();
+
+    if (ecoTax) {
+      combinationPrice = combinationPrice.plus(new BigNumber(ecoTax.toString()));
+    }
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]: To avoid invalid computing (just in case) maybe the BigNumber value should be stored and we should check if it is not NaN (this happened too many times for me to ignore it 😅) Besides the combination list component already has the `productModel` in its dependencies so you can reuse it (it avoids adding a new form mapping which is already handled by the model itself)

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]:
```suggestion
    const ecoTax = this. productModel.getBigNumber('price.ecotaxTaxExcluded') ?? new BigNumber(0);

    if (!ecoTax.isNaN()) {
      combinationPrice = combinationPrice.plus(ecoTax);
    }
```

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

A suggestion of improvement based on the product model.

**Review by zuk3975 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts [hunk 2]
```diff
@@ -276,7 +276,15 @@ export default class CombinationsListRenderer {
     const productPrice = this.productFormModel.getPriceTaxExcluded();
     const $finalPrice = $(CombinationsMap.list.finalPrice, $row);
     const $finalPricePreview = $finalPrice.siblings(CombinationsMap.list.finalPricePreview);
-    const finalPrice = this.productFormModel.displayPrice(productPrice.plus(priceImpactTaxExcluded));
+    let combinationPrice = productPrice.plus(priceImpactTaxExcluded);
+
+    const ecoTax = this.productFormModel.getBigNumber('price.ecotaxTaxExcluded') ?? new BigNumber(0);
+
+    if (ecoTax) {
```
Comment (zuk3975) [inline admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]: according to Joe comment, this is still missing:
`!ecoTax.isNaN()`

**Review by zuk3975 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts [hunk 3]
```diff
@@ -276,7 +276,15 @@ export default class CombinationsListRenderer {
     const productPrice = this.productFormModel.getPriceTaxExcluded();
     const $finalPrice = $(CombinationsMap.list.finalPrice, $row);
     const $finalPricePreview = $finalPrice.siblings(CombinationsMap.list.finalPricePreview);
-    const finalPrice = this.productFormModel.displayPrice(productPrice.plus(priceImpactTaxExcluded));
+    let combinationPrice = productPrice.plus(priceImpactTaxExcluded);
+
+    const ecoTax = this.productFormModel.getBigNumber('price.ecotaxTaxExcluded') ?? new BigNumber(0);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]: This handles the case where only product has an ecotax. Sadly (😅) the combination can also have its custom ecotax, which overrides the product one (it's not an impact it's a genuine replacement/override).

So we need to integrate for each combination in the list its proper ecotax value via a data attribute I guess. When this value is zero it means it's not overridden and you can use the product ecotax, when it's different from zero you can use it for this combination.

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @margud 

this is looking good, but I forgot that combinations can have their own ecotax value (see comment for more details).

File: admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts (hunk 3 above)
Comment (margud) [reply admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]: Updated it to use custom eco tax. @jolelievre

File: admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts [hunk 4]
```diff
@@ -278,7 +278,17 @@ export default class CombinationsListRenderer {
...
+
+    let ecoTax;
+
+    if (combinationEcoTax !== undefined) {
+      ecoTax = combinationEcoTax > 0
+        ? new BigNumber(combinationEcoTax.toString())
+        : this.productFormModel.getBigNumber('price.ecotaxTaxExcluded') ?? new BigNumber(0);
+    } else {
+      ecoTax = this.productFormModel.getBigNumber('price.ecotaxTaxExcluded') ?? new BigNumber(0);
+    }
```
Comment (zuk3975) [inline admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]: I think this way we get rid of one else statement and its still the same no?
```
if (combinationEcoTax !== undefined && combinationEcoTax > 0 ) {
  ecoTax = new BigNumber(combinationEcoTax.toString());
} else {
  ecoTax = this.productFormModel.getBigNumber('price.ecotaxTaxExcluded') ?? new BigNumber(0);
}

File: src/Core/Domain/Product/Combination/QueryResult/EditableCombinationForListing.php [hunk 5]
```diff
@@ -94,7 +100,8 @@ public function __construct(
         bool $default,
         DecimalNumber $impactOnPrice,
         int $quantity,
-        string $imageUrl
+        string $imageUrl,
+        float $ecoTax
```
Comment (zuk3975) [inline src/Core/Domain/Product/Combination/QueryResult/EditableCombinationForListing.php]: no floats.
Use DecimalNumber

File: admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts (hunk 4 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/components/combination-list/combinations-list-renderer.ts]: Oh nice catch the code is easier to read this way!

File: src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php [hunk 6]
```diff
@@ -188,7 +188,8 @@ private function formatEditableCombinationsForListing(
                 (bool) $combination['default_on'],
                 $impactOnPrice,
                 (int) $this->stockAvailableRepository->getForCombination(new CombinationId($combinationId))->quantity,
-                $imagePath
+                $imagePath,
+                (float) $combination['ecotax']
```
Comment (jolelievre) [inline src/Adapter/Product/Combination/QueryHandler/GetEditableCombinationsListHandler.php]: As suggested by @zuk3975 you'd better use DecimalNumber instead of flat values here

File: src/Core/Domain/Product/Combination/QueryResult/EditableCombinationForListing.php (hunk 5 above)
Comment (jolelievre) [reply src/Core/Domain/Product/Combination/QueryResult/EditableCombinationForListing.php]: Agreed, float lack precision natively so we try and rely on DecimalNumber every time we can Especially on new code, or else we create additional technical debts because the purpose is to rely on DecimalNumber everywhere we have float values

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php [hunk 7]
```diff
@@ -572,6 +572,7 @@ private function formatListForPresentation(CombinationListForEditing $combinatio
                 'quantity' => $combination->getQuantity(),
                 'is_default' => $combination->isDefault(),
                 'image_url' => $combination->getImageUrl() ?: $fallbackImageUrl,
+                'eco_tax' => $combination->getEcoTax(),
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php]:
```suggestion
                'eco_tax' => (string) $combination->getEcoTax(),
```

Once it's been turned into a DecimalNumber

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @margud 

A few suggestion on this one, also you should change the target branch to develop
We won't have time to include this in the 8.0 release anymore.

**Review by kpodemski — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @margud 

Could you please resolve your conflicts :pray: 
Thanks in advance!

**Review by jolelievre — APPROVED** [review]
Thanks @margud

**Review by zuk3975 — APPROVED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @margud 
Thanx for the PR ! it's LGTM ! QA :heavy_check_mark: 

Thank you !

**Comment by zuk3975** [comment]
Thanks @margud :tada:
