### PR TITLE
Prevent page freeze because off multiple add to cart clicks

### LINKED ISSUE #9634: [BOOM-5683] Double click on "Add to cart" on the product page FO freezes the page
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5683).

- _**Reporter:**_ Elitius
- _**Created at:**_ Wed, 6 Jun 2018 01:42:57 +0200

----
#### Describe the bug

If you double click on "add to cart" on a product page in FO, the confimation modal is displayed but cannot be closed if you click on the cross or on "continue shipping", but you can proceed to checkout.

#### Expected behavior

I should be able to close the modal

#### Steps to Reproduce

1. Go on a product page in FO
2. Double click on "add to cart"
3. Try to close the confirmation modal, you can't

**Screenshots**

https://drive.google.com/file/d/1ZMlOxzJDPdXoRdnQEgEGSUm-I_irCj_t/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x and before
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | This PR fixes double click issue and delete useless checking for stock and allow oosp, those checks are not working in quick view and when we don't allow to see stocks on front-office, also it's controller who decide whether we can or not add product to cart, button is no longer blocked after adding to cart thanks to ajax reload
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | yno
| Deprecations? | no
| Fixed ticket? | Fixes #9634 
| How to test?  | Follow scenarios below
| Sponsor company | impSolutions

## Before PR:

- [ ] page should freeze after clicking add to cart multiple times on product page

## After PR:

- [ ] page shouldn't be blocked after clicking add to cart multiple times

## QA
- [ ] we shouldn't be able to add more products than we can to cart
- [ ] add to cart should work as before on quick view and product page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21485)

### CODE REVIEW

File: themes/_core/js/cart.js [hunk 1]
```diff
@@ -79,55 +79,54 @@ $(document).ready(() => {
...
-          $input.parent().find('label').addClass('error');
-        };
-
-        let $quantityInput = $form.find('input[min]' );
-        if (!isQuantityInputValid($quantityInput)) {
-          onInvalidQuantity($quantityInput);
 
-          return;
-        }
+      $('[data-button-action="add-to-cart"]').attr('disabled', 'disabled');
```
Comment (atomiix) [inline themes/_core/js/cart.js]:
```suggestion
      $('[data-button-action="add-to-cart"]').prop('disabled', true);
```

**Comment by Progi1984** [comment]
@kpodemski Hi, Could you rebase your PR to `develop` branch ? Thanks

**Comment by kpodemski** [comment]
@Progi1984 rebased

btw. let me know if I should remove label myself next time 👍

**Comment by atomiix** [comment]
@kpodemski yep, once rebased, you can remove the label yourself ;)

**Review by atomiix — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Is it really inside the 177 scope ? I don't think, and this PR is on develop, we should change the label to 178 wdyt @PrestaShop/product-team ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
> Is it really inside the 177 scope ? I don't think, and this PR is on develop, we should change the label to 178 wdyt @PrestaShop/product-team ?

I update the description and labels.

**Comment by Roomsmaniia** [comment]
LGTM, can't make multiple clicks on the add to cart button on the product page.

Add to cart in quick view still works like before.

**Comment by Progi1984** [comment]
Thanks @kpodemski & @RomainBocheux
