### PR TITLE
Fix arabic numbers displayed

### LINKED ISSUE #33871: PPV2 - Prices in Arabic are not displayed correctly (always show 0.000000)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have problem in Admin panel in prestashop 8 in Products page 
if I change the admin page to arabic and enter to the products all prices will appear as zeroes in the price field 
when I open the consol and see what is the value of the price it shown as arabic or indian number : 
image

if I save the file without change the price it will convert it to zero and that conflect the client that edit some feature without rewrite the price again 

how can I fixed it??

### Expected behavior

I think the number will shown as english number to be right

### Steps to reproduce

1. Add arabic language to your prestashop admin
2. change the admin language from your account profile to arabic
3. go to any product and edit it 
4. go to the price and see the value of it

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix numbers format on some locales: `ar-SA` `bn-BD` and `fa-IR`.<br>In theses locales, we need to fallback to `en`, because admin front not worked at all with persian numbers.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #33871 
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/7084643335
| Fixed issue or discussion?     | Fixes #33871
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by ghadazoubi** [comment]
Hello
sorry I am very new in presta also in github 
how can I fixed the problem in my side??

File: src/PrestaShopBundle/Form/Admin/Type/CustomIntegerType.php [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace PrestaShopBundle\Form\Admin\Type;
```
Comment (mflasquin) [inline src/PrestaShopBundle/Form/Admin/Type/CustomIntegerType.php]:
```suggestion
 */

declare(strict_types=1);

namespace PrestaShopBundle\Form\Admin\Type;
```

File: src/PrestaShopBundle/Form/Admin/Type/CustomNumberType.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace PrestaShopBundle\Form\Admin\Type;
+
```
Comment (mflasquin) [inline src/PrestaShopBundle/Form/Admin/Type/CustomNumberType.php]:
```suggestion
 * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */

declare(strict_types=1);

namespace PrestaShopBundle\Form\Admin\Type;

```

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace PrestaShopBundle\Form\DataTransformer;
```
Comment (mflasquin) [inline src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php]:
```suggestion
 */
 
 declare(strict_types=1);

namespace PrestaShopBundle\Form\DataTransformer;
```

File: src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml [hunk 4]
```diff
@@ -16,6 +16,20 @@ services:
...
+      - '@prestashop.core.localization.locale.context_locale'
+    tags:
+      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\NumberType }
+
+  form.type.extension.integer:
+    class: 'PrestaShopBundle\Form\Admin\Type\CustomIntegerType'
+    arguments:
+      - '@prestashop.core.localization.locale.context_locale'
+    tags:
+      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\IntegerType }
```
Comment (mflasquin) [inline src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml]: According to ADR 19, you should use FQCN https://github.com/PrestaShop/ADR/blob/master/0019-FQCN-Autowiring.md, no ?

```suggestion
  PrestaShopBundle\Form\Admin\Type\CustomNumberType:
    public: false
    arguments:
      - '@prestashop.core.localization.locale.context_locale'
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\NumberType }

  PrestaShopBundle\Form\Admin\Type\CustomIntegerType:
    public: false
    arguments:
      - '@prestashop.core.localization.locale.context_locale'
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\IntegerType }
```

**Review by mflasquin — CHANGES_REQUESTED** [review]

**Comment by boherm** [comment]
Thanks @mflasquin for your review! I've done some fixes 😉

File: src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml [hunk 5]
```diff
@@ -16,6 +16,22 @@ services:
...
+      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\NumberType }
+
+  PrestaShopBundle\Form\Admin\Type\CustomIntegerType:
+    public: false
+    class: 'PrestaShopBundle\Form\Admin\Type\CustomIntegerType'
+    arguments:
+      - '@prestashop.core.localization.locale.context_locale'
+    tags:
+      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\IntegerType }
+
```
Comment (mflasquin) [inline src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml]: I think you can delete 'class' properties because FQCN is the same, no ? Do you think autowire can work (then we can delete 'arguments' properties too ?

File: src/Core/Localization/Locale.php [hunk 6]
```diff
@@ -182,4 +182,18 @@ public function getNumberSpecification()
...
+    /**
+     * Retrieve locale for numbers.
+     * (to avoid use of persian/arabic numbers)
+     *
+     * @return string
+     */
+    public function getLocaleForNumbers()
+    {
+        $locale = substr($this->code, 0, 2);
+        $excludedLocales = ['ar', 'bn', 'fa'];
```
Comment (M0rgan01) [inline src/Core/Localization/Locale.php]: I wonder if it's not better to have a constant to store these values ?

**Review by M0rgan01 — DISMISSED** [review]

**Comment by boherm** [comment]
@M0rgan01, @mflasquin Done guys! 
I've relaunch auto tests, just to be sure: https://github.com/boherm/ga.tests.ui.pr/actions/runs/6589826143

**Review by mflasquin — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

File: src/Core/Localization/LocaleInterface.php [hunk 7]
```diff
@@ -51,4 +51,12 @@ public function formatNumber($number);
...
      */
     public function formatPrice($number, $currencyCode);
+
+    /**
+     * Retrieve locale for numbers.
+     * (to avoid use of persian/arabic numbers)
+     *
+     * @return string
+     */
+    public function getLocaleForNumbers();
```
Comment (jolelievre) [inline src/Core/Localization/LocaleInterface.php]: Adding a method in a public interface is a breaking change, because any object that previously implemented this interface would become invalid...

File: src/PrestaShopBundle/Form/Admin/Type/CustomIntegerType.php [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+
+use PrestaShop\PrestaShop\Core\Localization\LocaleInterface;
+use Symfony\Component\Form\AbstractTypeExtension;
+use Symfony\Component\Form\Extension\Core\DataTransformer\IntegerToLocalizedStringTransformer;
+use Symfony\Component\Form\Extension\Core\Type\IntegerType;
+use Symfony\Component\Form\FormBuilderInterface;
+
+class CustomIntegerType extends AbstractTypeExtension
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Type/CustomIntegerType.php]: The naming of this interface is confusing we don't realize it's a form extension, it looks like a form type instead I guess you based this on the `CustomMoneyType` but it's also wrongly named actually The class name should finish with Extension

The namespace is also not appropriate it should be in `PrestaShopBundle\Form\Extension`

File: src/PrestaShopBundle/Form/Admin/Type/CustomIntegerType.php [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+    {
+        return [IntegerType::class];
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        $builder->resetViewTransformers();
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Type/CustomIntegerType.php]: Are you sure there are not other transformers? When I tested this with you I noticed that the localize transformer was not the only one, if you use reset everything is cleaned but only one is added back So potentially you are removing other relevant transformers

The other transformers should be saved as backup so they can be added again after the reset

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 10]
```diff
@@ -95,6 +97,23 @@ public function configureOptions(OptionsResolver $resolver)
         $resolver->setAllowedTypes('scale', 'int');
     }
 
+    /**
+     * {@inheritdoc}
+     */
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        $builder->resetViewTransformers();
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:118]: Same suggestion as other comment

File: src/PrestaShopBundle/Form/Admin/Type/CustomNumberType.php [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+use PrestaShop\PrestaShop\Core\Localization\LocaleInterface;
+use Symfony\Component\Form\AbstractTypeExtension;
+use Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer;
+use Symfony\Component\Form\Extension\Core\Type\NumberType;
+use Symfony\Component\Form\FormBuilderInterface;
+
+class CustomNumberType extends AbstractTypeExtension
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Type/CustomNumberType.php]: Same suggestions about class name, namespace and potential removed listeners

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 12]
```diff
@@ -0,0 +1,93 @@
...
+
+use Symfony\Component\Form\Exception\TransformationFailedException;
+use Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer;
+
+/**
+ * Transforms between a normalized format and a localized money string.
+ * (Copy from Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php to add $locale in it!)
+ *
+ * @author Bernhard Schussek <bschussek@gmail.com>
+ * @author Florian Eckerstorfer <florian@eckerstorfer.org>
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php]: Are you sure you need to copy the authors as well? 😅

**Review by jolelievre — DISMISSED** [review]

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 13]
```diff
@@ -0,0 +1,90 @@
...
+use Symfony\Component\Form\Exception\TransformationFailedException;
+use Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer;
+
+/**
+ * Transforms between a normalized format and a localized money string.
+ * (Copy from Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php to add $locale in it!)
+ */
+class MoneyToLocalizedStringTransformer extends NumberToLocalizedStringTransformer
+{
+    private $divisor;
```
Comment (tleon) [inline src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php:40]:
```suggestion
    private int $divisor;
```

File: src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php [hunk 14]
```diff
@@ -0,0 +1,84 @@
...
+use Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer;
+use Symfony\Component\Form\Extension\Core\Type\NumberType;
+use Symfony\Component\Form\FormBuilderInterface;
+
+class NumberTypeExtension extends AbstractTypeExtension
+{
+    /**
+     * @var LocaleInterface
+     */
+    private $locale;
```
Comment (tleon) [inline src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php]:
```suggestion
    private LocaleInterface $locale;
```

File: src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php [hunk 15]
```diff
@@ -0,0 +1,84 @@
...
+
+    /**
+     * @param LocaleInterface $locale
+     */
```
Comment (tleon) [inline src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php]:
```suggestion
```

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 16]
```diff
@@ -0,0 +1,90 @@
...
+     * @return int|float|null Normalized number
+     *
+     * @throws TransformationFailedException if the given value is not a string
+     *                                       or if the value can not be transformed
+     */
+    public function reverseTransform($value)
+    {
+        $value = parent::reverseTransform($value);
+        if (null !== $value && 1 !== $this->divisor) {
+            $value = (float) (string) ($value * $this->divisor);
```
Comment (tleon) [inline src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php:85]: I'm not familiar with this why wouldn't you directly cast it to float ?

File: src/PrestaShopBundle/Form/Extension/IntegerTypeExtension.php [hunk 17]
```diff
@@ -0,0 +1,75 @@
...
+use Symfony\Component\Form\Extension\Core\DataTransformer\IntegerToLocalizedStringTransformer;
+use Symfony\Component\Form\Extension\Core\Type\IntegerType;
+use Symfony\Component\Form\FormBuilderInterface;
+
+class IntegerTypeExtension extends AbstractTypeExtension
+{
+    /**
+     * @var LocaleInterface
+     */
+    private $locale;
```
Comment (tleon) [inline src/PrestaShopBundle/Form/Extension/IntegerTypeExtension.php]:
```suggestion
    private LocaleInterface $locale;
```

File: src/PrestaShopBundle/Form/Extension/IntegerTypeExtension.php [hunk 18]
```diff
@@ -0,0 +1,75 @@
...
+
+    /**
+     * @param LocaleInterface $locale
+     */
```
Comment (tleon) [inline src/PrestaShopBundle/Form/Extension/IntegerTypeExtension.php]:
```suggestion
```

**Review by tleon — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php (hunk 14 above)
Comment (boherm) [reply src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php]: Hum, not really sure about it because of the minimal PHP version that we support for 8.1.x 🤔

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php (hunk 16 above)
Comment (boherm) [reply src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php:85]: This file is a copy from `Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php` and I made this only to add $locale in it, and to avoid some construct problem. So I don't really own this piece of code, but it's seems to be worked as is 😅

File: src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php (hunk 14 above)
Comment (tleon) [reply src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php]: Yes apparently 8.1.x still supports php 7.2.x so we can't strong type the properties. My mistake ;)

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php (hunk 16 above)
Comment (tleon) [reply src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php:85]: As discused, it seems that this double cast is mandatory to obtain a correct precision.

**Review by tleon — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php [hunk 19]
```diff
@@ -0,0 +1,84 @@
...
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        // TODO: in 9.0, add getLocaleForNumbers to LocaleInterface and remove this check
+        if (method_exists($this->locale, 'getLocaleForNumbers')) {
+            $viewTransformers = $builder->getViewTransformers();
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Extension/NumberTypeExtension.php]: Nice this way, but it probably deserves a little comment explaining why we do this likt
```suggestion
            // We only want to replace/adapt the NumberToLocalizedStringTransformer so we backup the current transformers so we can add the other ones
            $viewTransformers = $builder->getViewTransformers();
```

File: src/PrestaShopBundle/Form/Extension/IntegerTypeExtension.php [hunk 20]
```diff
@@ -0,0 +1,75 @@
...
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        // TODO: in 9.0, add getLocaleForNumbers to LocaleInterface and remove this check
+        if (method_exists($this->locale, 'getLocaleForNumbers')) {
+            $builder->resetViewTransformers();
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Extension/IntegerTypeExtension.php]: You should do the same here as in NumberTypeExtension, there may be some other transformers that need to be kept

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php (hunk 10 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:118]: You should do the same here as in NumberTypeExtension, there may be some other transformers that need to be kept

File: src/Core/Localization/Locale.php [hunk 21]
```diff
@@ -182,4 +188,17 @@ public function getNumberSpecification()
...
         return $this->numberSpecification;
     }
+
+    /**
+     * Retrieve locale for numbers.
+     * (to avoid use of persian/arabic numbers)
+     *
+     * @return string
+     */
+    public function getLocaleForNumbers()
```
Comment (jolelievre) [inline src/Core/Localization/Locale.php]: I thought about an alternative solution that would avoid having to modify this class Since this notion of transforming the locale is only needed for the number form types and since you created a dedicated `MoneyToLocalizedStringTransformer` to handle this locale correctly why not moving this locale adaptation directly in the transformer?

This would avoid checking in three different form types if this method exists, no need to adapt the interface in 9.0, and at least this quite special code would be placed where it's the most useful (and probably the only place where it ill ever be used), thus avoiding to mess with a structure that's supposed dedicated to the CLDR

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 22]
```diff
@@ -0,0 +1,90 @@
...
+ * Transforms between a normalized format and a localized money string.
+ * (Copy from Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php to add $locale in it!)
+ */
+class MoneyToLocalizedStringTransformer extends NumberToLocalizedStringTransformer
+{
+    private $divisor;
+
+    public function __construct(?int $scale = 2, ?bool $grouping = true, ?int $roundingMode = self::ROUND_HALF_UP, ?int $divisor = 1, string $locale = null)
+    {
+        parent::__construct($scale ?? 2, $grouping ?? true, $roundingMode, $locale);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php:44]: As I suggested in another comment, maybe this is where we should transform the locale? This would centralize the hole transformation process into this class and reduce the complexity and the risk of modifying a core interface

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @boherm 

I had a few ideas that could improve the PR maybe, let me know what you think about it

File: src/Core/Localization/Locale.php (hunk 21 above)
Comment (boherm) [reply src/Core/Localization/Locale.php]: Not sure about your alternative solution. As we have the same problems with others transformers like `IntegerToLocalizedTransformer` for instance that we haven't already extended yet. I understand your logic but I don't really know if this is a great move, and have this logic in Locale class make sense to me. 🤔
Maybe we can talk about this in a voc channel?

**Review by matks — DISMISSED** [review]
Current implementation is good enough for me 👍

**Review by tleon — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Some changed to integrate, seen with @boherm

**Review by matks — DISMISSED** [review]

File: src/Core/Localization/Number/LocaleNumberTransformer.php [hunk 23]
```diff
@@ -0,0 +1,58 @@
...
+
+    /**
+     * Retrieve locale for numbers.
+     * (to avoid use of persian/arabic numbers)
+     *
+     * @return string
+     */
+    public function getLocaleForNumbers()
+    {
+        $locale = substr($this->locale->getCode(), 0, 2);
```
Comment (jolelievre) [inline src/Core/Localization/Number/LocaleNumberTransformer.php:54]: Isn't the code supposed to already be the value with two letters?

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 24]
```diff
@@ -95,6 +107,33 @@ public function configureOptions(OptionsResolver $resolver)
         $resolver->setAllowedTypes('scale', 'int');
     }
 
+    /**
+     * {@inheritdoc}
+     */
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        // We only want to replace/adapt the IntegerToLocalizedStringTransformer, so we save the current transformers
+        // to restore them after replacing the new IntegerToLocalizedStringTransformer.
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php]:
```suggestion
        // We only want to replace/adapt the MoneyToLocalizedStringTransformer, so we save the current transformers
        // to restore them after replacing the new MoneyToLocalizedStringTransformer.
```

File: src/Core/Localization/Number/LocaleNumberTransformer.php [hunk 25]
```diff
@@ -0,0 +1,58 @@
...
+        $this->locale = $locale;
+    }
+
+    /**
+     * Retrieve locale for numbers.
+     * (to avoid use of persian/arabic numbers)
+     *
+     * @return string
+     */
+    public function getLocaleForNumbers()
```
Comment (jolelievre) [inline src/Core/Localization/Number/LocaleNumberTransformer.php]: Since this is specifically used by form inputs I wonder if the method and even the class name should reflect this specific use. I'd go even further since it's specific to symfony form types maybe this should be put into a sub-namespace of PrestaShopBundle instead
```suggestion
    public function getLocaleForNumberInputs()
```

File: src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php [hunk 26]
```diff
@@ -0,0 +1,90 @@
...
+namespace PrestaShopBundle\Form\DataTransformer;
+
+use Symfony\Component\Form\Exception\TransformationFailedException;
+use Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer;
+
+/**
+ * Transforms between a normalized format and a localized money string.
+ * (Copy from Symfony/Component/Form/Extension/Core/DataTransformer/MoneyToLocalizedStringTransformer.php to add $locale in it!)
+ */
+class MoneyToLocalizedStringTransformer extends NumberToLocalizedStringTransformer
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/DataTransformer/MoneyToLocalizedStringTransformer.php:38]: "Funny thing" I checked this on develop (so with Symfony 5.4), the transformer now handles the loale parameter in its constructor So in 9.0 this custom could become obsolete We'll have to pay attention to that when we merge back the fix in develop next week

File: tests/Unit/Core/Localization/Number/LocaleNumberTransformerTest.php [hunk 27]
```diff
@@ -0,0 +1,85 @@
...
+class LocaleNumberTransformerTest extends TestCase
+{
+    /**
+     * Instantiate a LocaleNumberTransformer with custom locale.
+     *
+     * @param string $localeCode
+     *
+     * @return LocaleNumberTransformer
+     */
+    public function createTransformer(string $localeCode): LocaleNumberTransformer
```
Comment (jolelievre) [inline tests/Unit/Core/Localization/Number/LocaleNumberTransformerTest.php]: This probably should be a protected method since it's only used internally
```suggestion
    protected function createTransformer(string $localeCode): LocaleNumberTransformer
```

**Review by jolelievre — COMMENTED** [review]
Just a few suggestions but nothing blocking in itself The proposed solution is perfect, it's only suggestions about naming and namespaces, open to discussion

File: src/Core/Localization/Number/LocaleNumberTransformer.php (hunk 23 above)
Comment (boherm) [reply src/Core/Localization/Number/LocaleNumberTransformer.php:54]: No, it's locale king size like `fr_FR` for instance.

Comment (jolelievre) [reply src/Core/Localization/Number/LocaleNumberTransformer.php:54]: OK so it means the PHPDoc in the Locale class is not accurate, but it's another issue

**Review by M0rgan01 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @boherm

**Review by AureRita — APPROVED** [review]
Hi @boherm 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/b3f58e77-c17a-4361-a8fb-7b26d2b0d390)

I tested with ar-SA, bn-BD, fa-IR, Chinese and Japanese, all of it seems to use the english type for the number displayed. Same with them currency

Link to the auto test : https://github.com/boherm/ga.tests.ui.pr/actions/runs/7084643335

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by nicosomb** [comment]
Well done @boherm !
