### PR TITLE
Hide expiration field when "period never expires" is checked

### LINKED ISSUE #40801: The expiration date must not be displayed when the “Period never expires” option is checked
**Steps to reproduce**
- Create any type of discount
- Check "Period never expires" option

**Expected behavior**
The expiration date is no longer displayed (in the form and in the list).

**Current** 
The expiration date remains displayed (in the form and in the list).

--- 

Image

Image

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Hide expiration date field when the 'period never expires' option is checked
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Steps to reproduce are here https://github.com/PrestaShop/PrestaShop/issues/40801
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/22674629116
| Fixed issue or discussion?     | #40801
| Related PRs       | https://github.com/PrestaShop/ps_apiresources/pull/142 and https://github.com/PrestaShop/autoupgrade/pull/1671
| Sponsor company   | PrestaShop SA

### CODE REVIEW

File: classes/CartRule.php [hunk 1]
```diff
@@ -110,7 +110,7 @@ class CartRuleCore extends ObjectModel
         'fields' => [
             'id_customer' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedId'],
             'date_from' => ['type' => self::TYPE_DATE, 'validate' => 'isDate', 'required' => true],
-            'date_to' => ['type' => self::TYPE_DATE, 'validate' => 'isDate', 'required' => true],
+            'date_to' => ['type' => self::TYPE_DATE, 'validate' => 'isDateOrNull', 'required' => false],
```
Comment (jolelievre) [inline classes/CartRule.php]: I think you should init the `date_to` field to null

File: classes/CartRule.php [hunk 2]
```diff
@@ -429,7 +429,7 @@ public static function getCustomerCartRules(
         $sql .= ')';
 
         // Then, conditions for date, voucher active property and total amount of vouchers in stock
-        $sql .= ' AND NOW() BETWEEN cr.date_from AND cr.date_to
+        $sql .= ' AND (cr.date_to IS NULL OR (NOW() BETWEEN cr.date_from AND cr.date_to))
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
        $sql .= ' AND ((cr.date_from <= NOW() AND cr.date_to IS NULL) OR (NOW() BETWEEN cr.date_from AND cr.date_to))
```

File: classes/CartRule.php [hunk 3]
```diff
@@ -786,7 +786,7 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
             if (strtotime($this->date_from) > time()) {
                 return (!$display_error) ? false : $this->trans('This voucher is not valid yet', [], 'Shop.Notifications.Error');
             }
-            if (strtotime($this->date_to) < time()) {
+            if ($this->date_to !== null && $this->date_to !== '' && strtotime($this->date_to) < time()) {
```
Comment (jolelievre) [inline classes/CartRule.php]: `date_to` should never be equal to `''` no? Is it useful to test it?

File: classes/CartRule.php [hunk 4]
```diff
@@ -1992,7 +1992,7 @@ public static function autoAddToCart(?Context $context = null, bool $useOrderPri
 		WHERE cr.active = 1
 		AND cr.code = ""
 		AND (cr.quantity > 0 OR cr.quantity is null)
-		AND NOW() BETWEEN cr.date_from AND cr.date_to
+		AND (cr.date_to IS NULL OR (NOW() BETWEEN cr.date_from AND cr.date_to))
```
Comment (jolelievre) [inline classes/CartRule.php]:
```suggestion
		AND ((cd.date_from <= NOW && cr.date_to IS NULL) OR (NOW() BETWEEN cr.date_from AND cr.date_to))
```

File: admin-dev/themes/new-theme/js/pages/discount/form/index.ts [hunk 5]
```diff
@@ -75,6 +75,18 @@ $(() => {
     $(DiscountMap.quantityPerCustomerInput).parents('.form-group').show();
   }
 
+  const toggleExpiryDateVisibility = () => {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/discount/form/index.ts]: I just remembered we have a component to handle this kind of use `FormFieldToggler`

File: src/Adapter/Discount/Update/DiscountBuilder.php [hunk 6]
```diff
@@ -36,7 +36,7 @@ public function build(AddDiscountCommand $command): CartRule
         $cartRule->active = $command->isActive();
         $cartRule->id_customer = $command->getCustomerId()?->getValue();
         $cartRule->date_from = $validFrom->format(DateTimeUtil::DEFAULT_DATETIME_FORMAT);
-        $cartRule->date_to = $validTo->format(DateTimeUtil::DEFAULT_DATETIME_FORMAT);
+        $cartRule->date_to = $command->isPeriodNeverExpires() ? null : $validTo->format(DateTimeUtil::DEFAULT_DATETIME_FORMAT);
```
Comment (jolelievre) [inline src/Adapter/Discount/Update/DiscountBuilder.php]: We don't need an extra getter/setter for this, forcing the value of dateTo to null implies that it will never expire via `$command->setValidaTo(null)` Thanks to the `isDirty` trait we are able to understand this was intentional, not a default unset value

File: src/Core/Domain/Discount/Command/AddDiscountCommand.php [hunk 7]
```diff
@@ -124,15 +125,29 @@ public function getValidTo(): ?DateTimeImmutable
...
+        $this->periodNeverExpires = $periodNeverExpires;
+
+        return $this;
+    }
+
+    public function isPeriodNeverExpires(): bool
+    {
+        return $this->periodNeverExpires;
+    }
+
```
Comment (jolelievre) [inline src/Core/Domain/Discount/Command/AddDiscountCommand.php]: As explained above, you don't need these extra getters/setter

File: src/Core/Domain/Discount/Command/UpdateDiscountCommand.php [hunk 8]
```diff
@@ -161,6 +162,18 @@ public function setValidityDateRange(DateTimeImmutable $from, DateTimeImmutable
...
+        $this->periodNeverExpires = $periodNeverExpires;
+
+        return $this;
+    }
+
+    public function isPeriodNeverExpires(): bool
+    {
+        return $this->periodNeverExpires;
+    }
+
```
Comment (jolelievre) [inline src/Core/Domain/Discount/Command/UpdateDiscountCommand.php]:
```suggestion
```

File: src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php [hunk 9]
```diff
@@ -128,14 +128,16 @@ private function fillCommandFromData(AddDiscountCommand|UpdateDiscountCommand $c
...
             } else {
                 $validTo = $this->parseDateWithDefaultTime($dateRange['to'] ?? null, '23:59');
             }
 
-            if ($validFrom && $validTo) {
+            if ($validFrom) {
                 $command->setValidityDateRange($validFrom, $validTo);
+                if ($neverExpires) {
+                    $command->setPeriodNeverExpires(true);
+                }
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/DataHandler/DiscountFormDataHandler.php]:
```suggestion
```
Just setting null on validTo should be enough

File: src/Core/Form/IdentifiableObject/DataProvider/DiscountFormDataProvider.php [hunk 10]
```diff
@@ -207,7 +207,7 @@ public function getData($id)
                     'from' => $discountForEditing->getValidFrom() ? $discountForEditing->getValidFrom()->format(DateTimeUtil::DEFAULT_DATETIME_FORMAT) : null,
                     'to' => $discountForEditing->getValidTo() ? $discountForEditing->getValidTo()->format(DateTimeUtil::DEFAULT_DATETIME_FORMAT) : null,
                 ],
-                'period_never_expires' => $this->isPeriodNeverExpires($discountForEditing->getValidFrom(), $discountForEditing->getValidTo()),
+                'period_never_expires' => $this->isPeriodNeverExpires($discountForEditing->getValidTo()),
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/DataProvider/DiscountFormDataProvider.php]:
```suggestion
                'period_never_expires' => null === $discountForEditing->getValidTo(),
```
You can simplify this

**Review by boherm — DISMISSED** [review]

File: src/Core/Grid/Data/Factory/DiscountGridDataFactoryDecorator.php [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+use PrestaShop\PrestaShop\Core\Grid\Data\GridData;
+use PrestaShop\PrestaShop\Core\Grid\Data\GridDataInterface;
+use PrestaShop\PrestaShop\Core\Grid\Record\RecordCollection;
+use PrestaShop\PrestaShop\Core\Grid\Search\SearchCriteriaInterface;
+use PrestaShop\PrestaShop\Core\Util\DateTime\DateTime as DateTimeUtil;
+
+/**
+ * Decorates discount grid data to display a fallback when expiration date is null
+ */
+final class DiscountGridDataFactoryDecorator implements GridDataFactoryInterface
```
Comment (jolelievre) [inline src/Core/Grid/Data/Factory/DiscountGridDataFactoryDecorator.php:21]: Nice! Just out of curiosity did you try this with grid template override? https://devdocs.prestashop-project.org/9/development/components/grid/tutorials/customize-templates/

I need to test it for the total quantity in my PR

File: tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php [hunk 12]
```diff
@@ -202,11 +201,8 @@ public function createDiscount(string $discountReference, string $discountType,
         if (isset($data['valid_from'])) {
             $validFrom = new DateTimeImmutable($data['valid_from']);
 
-            // Check if "never expires" is set
             if (isset($data['period_never_expires']) && PrimitiveUtils::castStringBooleanIntoBoolean($data['period_never_expires'])) {
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php:203]: I wonder if we should keep this `period_never_expires` or use the `null` value explicitly 🤔

Both are fine, using null is more technical/developer oriented, whereas `period_never_expires` is more user oriented (which is originally the purpose of behat)

File: tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php [hunk 13]
```diff
@@ -215,6 +211,9 @@ public function createDiscount(string $discountReference, string $discountType,
 
             try {
                 $command->setValidityDateRange($validFrom, $validTo);
+                if ($validTo === null) {
+                    $command->setPeriodNeverExpires(true);
+                }
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php]:
```suggestion
```

File: tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php [hunk 14]
```diff
@@ -380,17 +379,15 @@ public function editDiscount(string $discountReference, TableNode $node): void
...
             } else {
                 $validFrom = new DateTimeImmutable();
             }
-            $validTo = (new DateTime())->modify('+100 years')->setTime(23, 59, 59);
-            $validTo = DateTimeImmutable::createFromMutable($validTo);
 
             try {
-                $command->setValidityDateRange($validFrom, $validTo);
+                $command->setValidityDateRange($validFrom, null);
+                $command->setPeriodNeverExpires(true);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php]:
```suggestion
```

File: tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php [hunk 15]
```diff
@@ -721,40 +718,23 @@ protected function assertDiscountProperties(DiscountForEditing $discountForEditi
...
-            sprintf('Expiration date should be more than %d years in the future', $years)
+        Assert::assertNull(
+            $discountForEditing->getValidTo(),
+            'Discount should have no expiration date (period never expires)'
         );
     }
 
     /**
-     * Check if the discount period is set to "never expires" (100 years in the future).
+     * Check if the discount period is set to "never expires" (null expiration date).
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/Discount/DiscountFeatureContext.php]: I think this method can be removed as well no? Simply checking that validTo === null should be enough

File: tests/Integration/Behaviour/Features/Scenario/Discount/BO/update_discount_validity_dates.feature [hunk 16]
```diff
@@ -200,13 +200,13 @@ Feature: Update discount validity dates
       | period_never_expires | false               |
       | reduction_percent    | 15.0                |
 
-  Scenario: Verify never-expiring discount has expiration far in the future
+  Scenario: Verify never-expiring discount has no expiration date
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Discount/BO/update_discount_validity_dates.feature:203]: Nice, I just realized that the date conditions don't seem to be tested in the FO tests to assert validaty check works as expected We have `discount-priority-creation-date` but it's to check the impact of the creation on priorisation

Can you please add a new feature file where we vary the validTo and validFrom to cehck the current date is indeed within the range? With one scenario based on explicit validTo and one based on validTo === null (like at first it's not valid because validTo is <= NOW but when it's set to null the discount becomes valid)

**Review by jolelievre — COMMENTED** [review]
Thanks @nicosomb

**Review by tleon — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/components/form/form-field-toggler.ts [hunk 17]
```diff
@@ -127,7 +127,7 @@ export default class FormFieldToggler {
         return checkedValue;
       }
       case 'checkbox':
-        return inputElement.checked ? inputElement.value : undefined;
+        return inputElement.checked ? (inputElement.value || '1') : '0';
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/form/form-field-toggler.ts]: Hmm, we'll have to check the other places where this was used to make sure it doesn't have side effects Why didn't it work with the current code?

File: classes/CartRule.php [hunk 18]
```diff
@@ -369,13 +370,13 @@ public static function haveCartRuleToday($idCustomer)
             $start_date = date('Y-m-d 00:00:00');
             $end_date = date('Y-m-d 23:59:59');
             $sql = 'SELECT 1 FROM `' . _DB_PREFIX_ . 'cart_rule` ' .
-                'WHERE ((date_to >= "' . $start_date .
+                'WHERE (((date_to >= "' . $start_date .
```
Comment (jolelievre) [inline classes/CartRule.php]: I do'nt think you need to open a new extra `()` There is already one englobing all the dates conditions

File: classes/CartRule.php [hunk 19]
```diff
@@ -369,13 +370,13 @@ public static function haveCartRuleToday($idCustomer)
...
                 '" AND date_to <= "' . $end_date .
                 '") OR (date_from >= "' . $start_date .
                 '" AND date_from <= "' . $end_date .
                 '") OR (date_from < "' . $start_date .
                 '" AND date_to > "' . $end_date .
-                '")) AND `id_customer` IN (0,' . (int) $idCustomer . ')';
+                '") OR (date_to IS NULL AND date_from <= "' . $end_date . '"))) AND `id_customer` IN (0,' . (int) $idCustomer . ')';
```
Comment (jolelievre) [inline classes/CartRule.php]: You should only need to add one more condition here, something like

```suggestion
                '") OR (date_from < "' . $start_date .
                '" AND date_to IS NULL " .
                '")) AND `id_customer` IN (0,' . (int) $idCustomer . ')';
```

File: classes/CartRule.php [hunk 20]
```diff
@@ -786,7 +787,7 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
             if (strtotime($this->date_from) > time()) {
                 return (!$display_error) ? false : $this->trans('This voucher is not valid yet', [], 'Shop.Notifications.Error');
             }
-            if (strtotime($this->date_to) < time()) {
+            if (!DateTimeUtil::isNull($this->date_to ?? null) && strtotime($this->date_to) < time()) {
```
Comment (jolelievre) [inline classes/CartRule.php:794]: Ah nice, I forgot about this one!!

File: src/PrestaShopBundle/ApiPlatform/Normalizer/DateTimeImmutableNormalizer.php [hunk 21]
```diff
@@ -23,6 +23,10 @@ class DateTimeImmutableNormalizer implements DenormalizerInterface, NormalizerIn
 {
     public function denormalize($data, string $type, ?string $format = null, array $context = [])
     {
+        if (DateTimeUtil::isNull($data)) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/Normalizer/DateTimeImmutableNormalizer.php:26]: Nice catch

**Review by jolelievre — COMMENTED** [review]
Almost good, just this DB query that maybe could be rewritten following the same coding style as the other conditions

File: admin-dev/themes/new-theme/js/components/form/form-field-toggler.ts (hunk 17 above)
Comment (nicosomb) [reply admin-dev/themes/new-theme/js/components/form/form-field-toggler.ts]: without that, the 2 fields (date from and date to) were hidden by ticking the checkbox

**Review by Hlavtox — COMMENTED** [review]
@ibahloul-ps Any specific reason why only end date is optional? It's a bit inconsistent.

@nicosomb I am pretty sure we already have a component with a no limit checkbox, used for specific prices. :-)

File: admin-dev/themes/new-theme/js/components/form/form-field-toggler.ts (hunk 17 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/form/form-field-toggler.ts]: Hmm, then it means the selector is maybe too wide no? Maybe you just need to have a more precise selector for the field that needs to be hidden and it would prevent modifying this generic and shared component?

**Comment by jolelievre** [comment]
@Hlavtox the component you mentioned is related to the `disabling_switch` form option right?
It's not exactly the same because here we want to hide the element not disable it. We don't have a global option to handle this, but we do have a common component in JS at least.

Regarding applying the same principle to `date_to` I shared your idea to Ilies who will think about it.

Anyway, for both questions I don't think it's worth blocking or delaying the PR, but it's worth thinking about improvement in another PR

**Comment by Hlavtox** [comment]
@jolelievre Yeah, but wouldn't just disabling it work just fine? 

Why implement different components just for this page.

The backoffice would be consistent. You would not have to create and manage yet another component.

**Comment by ibahloul-ps** [comment]
> @ibahloul-ps Any specific reason why only end date is optional? It's a bit inconsistent.

Because it seemed more obvious to us to have a discount that doesn't expire, rather than a discount that doesn't start :p

That said, we could review the design to have an optional period, it seems like a good idea!

**Comment by Hlavtox** [comment]
@ibahloul-ps Well, do you know that also discounts that have no time limit exist? Like most of them? 😁

**Comment by ibahloul-ps** [comment]
> @ibahloul-ps Well, do you know that also discounts that have no time limit exist? Like most of them? 😁

Yes, that's why we added a way to set no limit rather than saying that a discount expires in 100 years. It's just that a discount always has a start date (at least the creation date), which is why there is no option to make it nullable.

But you're right, the period (with a start date/end date) could be optional 👍

**Review by jolelievre — DISMISSED** [review]
Thanks @nicosomb

**Review by boherm — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by paulnoelcholot — COMMENTED** [review]
Hello @nicosomb 

I tested your PR but I don't have the same expected behavior as on the models.

Did I miss something? :/

https://github.com/user-attachments/assets/2d54a77a-8c4b-4527-9483-66f6ff3727c9

**Review by jolelievre — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @nicosomb,

I tested your PR and it's good for me! :tada: 

Thanks!


https://github.com/user-attachments/assets/3e2e3ee8-6481-4a08-9a96-1b7d072b0838

**Review by paulnoelcholot — APPROVED** [review]
