### PR TITLE
Check variable before using it

### LINKED ISSUE #25483: FO - An exception is displayed when we click on sign out two times
#### Describe the bug

In the FO > When a customer tries to logout with clicking multiple times on "Sign out" => an exception is displayed
image

#### Steps to Reproduce

1- Enable debug mode
2- Go to FO and sign in
3- Click on Sign out 2 times ( URL: shop.com/en/?mylogout=)
4- See error: exception: https://drive.google.com/file/d/1D9TwKgFv2ENsiuPwuvPwUToEYCLhJzuI/view?usp=sharing

I tried with PS1769 => ok (no exception displayed)
https://drive.google.com/file/d/1nOWxP5xcqtCp0P3NS-iipbFIxYNRGOEH/view?usp=sharing

#### Additional information

* PrestaShop version: 1776build1, 1775
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Check variable before using it
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25483
| How to test?      | Cf. #25483

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25495)

### CODE REVIEW

File: classes/Cookie.php [hunk 1]
```diff
@@ -545,7 +545,7 @@ public function getSession($sessionId)
             $session = new CustomerSession($sessionId);
         }
 
-        if (!empty($session->getId())) {
+        if (isset($session) && !empty($session->getId())) {
```
Comment (eternoendless) [inline classes/Cookie.php:548]:
```suggestion
        if (is_object($session) && !empty($session->getId())) {
```

**Review by eternoendless — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sarahdib
