### PR TITLE
Reintroduce email unicity validation

### LINKED ISSUE #39587: Email unicity not checked anymore on version 9.0
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a customer change his email on front office, he can set an email that already exists in database for another customer

### Expected behavior

The validation of the unicity of the email address must be reinstated. This validation was in place in [version 8.2](https://github.com/PrestaShop/PrestaShop/blob/8.2.x/classes/form/CustomerForm.php#L129) but is not present in the [version 9.0](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/form/CustomerForm.php#L124)

```php
        // this part is missing from version 9.0
        $emailField = $this->getField('email');
        $id_customer = Customer::customerExists($emailField->getValue(), true, true);
        $customer = $this->getCustomer();
        if ($id_customer && $id_customer != $customer->id) {
            $emailField->addError($this->translator->trans(
                'The email is already used, please choose another one or sign in',
                [],
                'Shop.Notifications.Error'
            ));
        }
```

### Steps to reproduce

1. Go to customer identity page
2. Change the email and set an email already used by another customer
3. No error message is displayed

### PrestaShop version(s) where the bug happened

9.0.0

### How you installed PrestaShop

docker

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by bibips**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | The validation of the unicity of the email address is reinstated. This validation was in place in [version 8.2](https://github.com/PrestaShop/PrestaShop/blob/8.2.x/classes/form/CustomerForm.php#L129) but is not present in the [version 9.0](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/form/CustomerForm.php#L124)
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Go to customer identity page<br>2. Change the email and set an email already used by another customer<br>3. An error message is displayed
| UI Tests          | https://github.com/bibips/ga.tests.ui.pr/actions/runs/17938704488
| Fixed issue or discussion?     | Fixes #39587

### CODE REVIEW

**Comment by Codencode** [comment]
@Hlavtox @kpodemski Let's wait for others' opinions to understand how to proceed, or should we approve the PR?

File: classes/form/CustomerForm.php [hunk 1]
```diff
@@ -123,6 +123,17 @@ public function getCustomer()
...
+        if (!$this->context->customer->is_guest) {
+            $emailField = $this->getField('email');
+            if (Customer::customerExists($emailField->getValue())) {
+                $emailField->addError($this->translator->trans(
+                    'The email is already used, please choose another one or sign in',
+                    [],
+                    'Shop.Notifications.Error'
+                ));
+            }
+        }
```
Comment (Hlavtox) [inline classes/form/CustomerForm.php:138]:
```suggestion
        // If email is being changed, check if it's free to use and doesn't belong to another customer
        if (!$this->context->customer->is_guest) {
            $emailField = $this->getField('email');
            if (Customer::customerExists($emailField->getValue())) {
                $emailField->addError($this->translator->trans(
                    'The email is already used, please choose another one',
                    [],
                    'Shop.Notifications.Error'
                ));
            }
        }
```

**Review by Hlavtox — COMMENTED** [review]
Minor suggestion, otherwise I think it's good. Getting customer through context is legit, the class already does this.

**Review by Codencode — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @bibips 
Thank you for the pr. Could you restart the automated tests please?

Thanks

**Comment by AureRita** [comment]
Hi @bibips 

Thank you for your PR, I tested it and I currently can't any things from a user as you can see on this video : 

https://github.com/user-attachments/assets/6a5e73ab-74b4-40a2-a45e-5dd8e48343c8

Can you check it for some changes ? 

Waiting for feedbacks

**Review by ShaiMagal — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@AureRita Try it now again, the code was broken

**Review by Hlavtox — APPROVED** [review]

**Review by Touxten — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

File: classes/form/CustomerForm.php [hunk 2]
```diff
@@ -123,6 +123,20 @@ public function getCustomer()
 
     public function validate()
     {
+        // If email is being changed, check if it's free to use and doesn't belong to another customer
+        if (!$this->context->customer->is_guest) {
```
Comment (jolelievre) [inline classes/form/CustomerForm.php:127]: Be careful if you put this check here it means it will only be used in the FO form, so not in BO, not in webservice and not in Admin API

Maybe this check should be placed in a protected method in `Customer::validateEmailUnicity` instead, and this method should be called in add/update/save methods automatically

Or alternatively we could create a new dedicated validation rule for legacy fields and configure it on this email field but I'm not sure if it's possible this way

Comment (Codencode) [reply classes/form/CustomerForm.php:127]: Hello @jolelievre, if I'm not mistaken and if I understood correctly, these checks should have already been included by this separate PR: https://github.com/PrestaShop/PrestaShop/pull/39591

**Review by AureRita — APPROVED** [review]
Hi @bibips 

Thank you for your PR, I tested it and it seems to works as you can see : 

https://github.com/user-attachments/assets/36fcd4df-421e-4f1e-8018-31a37a9d21ee

link of automated test : https://github.com/AureRita/testing_pr/actions/runs/17947279191

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

File: classes/form/CustomerForm.php (hunk 2 above)
Comment (Hlavtox) [reply classes/form/CustomerForm.php:127]: @jolelievre It's already implemented in other places, we didn't realize / test this use case only.

Comment (jolelievre) [reply classes/form/CustomerForm.php:127]: Hmm, but I don't understand if the tests are already done on the Customer level why is it needed to do them on the corm level as well? The Customer should trigger an invalid data no?

Comment (Hlavtox) [reply classes/form/CustomerForm.php:127]: @jolelievre It (the PR for Customer class) would also catch it, as a second safeguard, but it would just throw a generic error on the top of the page.

This PR (we are currently discussing) will throw a precise error under the email field.

Comment (jolelievre) [reply classes/form/CustomerForm.php:127]: Ok got it, thanks
