### PR TITLE
Orders > Product : Display "Stock Location" column only if it is not empty

### LINKED ISSUE #16391: Missing columns on new order page
**Describe the bug**
Missing columns on the new order page

**To Reproduce**
Steps to reproduce the behaviour:
1. Edit a product and fill the field stock location
2. Order this product in FO
3. See the order in BO
4. Stock location and Available quantity are missing

**Screenshots**
capture d'écran_2142

Legacy

capture d'écran_2141

**Solution**
The stock location column is hidden only when none of the products has a stock location only on the website. The column is only displayed at the corresponding pagination. If only a product on page 2 of the list has a stock location then the stock location column appears on page 2 and hidden in the other pages.
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Orders > Product : Display "Stock Location" column only if it is not empty
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16391
| How to test?  | * Build assets<br>* In BO, in an order, if stock location is defined, the stock location column is displayed else not<br>* Column is displayed in add form <br>* Works well

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17135)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js [hunk 1]
```diff
@@ -190,4 +196,18 @@ export default class OrderProductRenderer {
       $(OrderViewPageMap.productAddNewInvoiceInfo).addClass('d-none');
     }
   }
+
+  toggleColumnLocation(forceDisplay = null) {
+    let isColumnLocationDisplayed = false;
+    if (forceDisplay === null) {
+      $(OrderViewPageMap.productsCellLocation).filter('td').each(function() {
+        if ($(this).html() !== '') {
+          isColumnLocationDisplayed = true;
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js:205]: No need to continue
```suggestion
          isColumnLocationDisplayed = true;
          return false;
```

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js:205]: :heavy_check_mark: Thanks

File: admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js [hunk 2]
```diff
@@ -71,6 +71,7 @@ export default {
   productsTablePaginationTemplate: '#orderProductsTablePagination .page-item.d-none',
   productsTableRow: productId => `#orderProduct_${productId}`,
   productsTableRowEdited: productId => `#editOrderProduct_${productId}`,
+  productsCellLocation: '.cellProductLocation',
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]:
```suggestion
  productsCellLocation: '.cell-product-location',
```

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]: Note : https://codeguide.co/#css-classes

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

Two issues on this PR : 

- When adding a product with combination, the stock location is not displayed in the add form. It is however well displayed once added.
- When there is a pagination, according to the main issue, the stock location column should not be displayed if on this page, there is no stock location.

Thanks :)

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js [hunk 3]
```diff
@@ -135,9 +136,10 @@ export default class OrderProductAdd {
   setCombinations(combinations) {
     this.combinationsSelect.empty();
     Object.values(combinations).forEach((val) => {
-      this.combinationsSelect.append(`<option value="${val.attributeCombinationId}" data-price-tax-excluded="${val.priceTaxExcluded}" data-price-tax-included="${val.priceTaxIncluded}" data-stock="${val.stock}">${val.attribute}</option>`);
+      this.combinationsSelect.append(`<option value="${val.attributeCombinationId}" data-price-tax-excluded="${val.priceTaxExcluded}" data-price-tax-included="${val.priceTaxIncluded}" data-stock="${val.stock}" data-location="${val.location}" >${val.attribute}</option>`);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: Remove extra space after data-location

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig [hunk 4]
```diff
@@ -22,7 +22,9 @@
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  * International Registered Trademark & Property of PrestaShop SA
  *#}
-
+{% if isColumnLocationDisplayed is not defined %}
+  {% set isColumnLocationDisplayed=(product.availableQuantity is empty) %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: So the column is displayed when there is no stock? Shouldn't it be the opposite?

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: In products.html.twig you check `product.location is not empty` which seems more logical

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: I guess you add the `isColumnLocationDisplayed ` here because when adding a product the variable is not defined like it is in the products loop
The it would be cleaner to define this variable in the addProduct controller

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js (hunk 3 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: :heavy_check_mark:

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig (hunk 4 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: The variable `product` is added in  `src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php` at l.542

Comment (Progi1984) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: Fixed for the bad variable used

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig [hunk 5]
```diff
@@ -22,7 +22,9 @@
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  * International Registered Trademark & Property of PrestaShop SA
  *#}
-
+{% if isColumnLocationDisplayed is not defined %}
+  {% set isColumnLocationDisplayed=(product.location is empty) %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]:
```suggestion
  {% set isColumnLocationDisplayed=(product.location is not empty) %}
```

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: But again it's cleaner to do this in the controller (if it's related to the add product feature html return)

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig (hunk 5 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig]: Fixed ;)

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 6]
```diff
@@ -199,6 +199,7 @@ export default class OrderViewPage {
 
     EventEmitter.on(OrderViewEventMap.productListPaginated, (event) => {
       this.orderProductRenderer.paginate(event.numPage);
+      this.orderProductRenderer.toggleColumnLocation();
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: This would be more logical to do this in the `orderProductRenderer.paginate` function

**Review by jolelievre — CHANGES_REQUESTED** [review]
last change ;)

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 6 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: Fixed

**Review by jolelievre — DISMISSED** [review]
Thank @Progi1984

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

The display of stock location seems to be OK, but when I install your PR, the display price and quantity of "basic" product when adding is broken ("NaN") : 
pr17135 NaN

I do not have this problem with combination product (I did not try any other type, no time unfortunately).

**Review by jolelievre — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 

Still one small bug, when I add a new product, if no product already in the order has a stock location, and if there is more than 8 product (with pagination), the display of the product of the second page is shifted on the left (the "stock location" column is not taken into account for this page).
See screenshot, the two last product are the products on page 2 : 
pr17135 pagination decale

**Review by matks — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js [hunk 7]
```diff
@@ -200,15 +200,15 @@ export default class OrderProductRenderer {
...
+      $(OrderViewPageMap.productsCellLocationDisplayed).filter('td').each(function() {
         if ($(this).html() !== '') {
           isColumnLocationDisplayed = true;
           return false;
         }
       });
+      $(OrderViewPageMap.productsCellLocationDisplayed).toggleClass('d-none', !isColumnLocationDisplayed);
     } else {
-      isColumnLocationDisplayed = forceDisplay;
+      $(OrderViewPageMap.productsCellLocation).toggleClass('d-none', !forceDisplay);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js]: I'd say you're gonna have the same problem here than with the previous bug, you must only toggle `productsCellLocationDisplayed`

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Review by jolelievre — DISMISSED** [review]
Nice job @Progi1984

**Review by PierreRambaud — DISMISSED** [review]
Don't forget to build assets please :)

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 ! Could you resolve the conflicts on the two files ? Thx !

**Comment by Progi1984** [comment]
@Robin-Fischer-PS Fixed

**Review by jolelievre — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
