### PR TITLE
Fix subcategories for multishop

### LINKED ISSUE #29159: Multistore. Product page in BO, can't select subcategory for product if was selected "Color" for shop in Multistore settings
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In multistore I can't select subcategory for new product or for existing products if I selected color for each shop in Multistore settings, 
scrnli_7_25_2022_4-49-31 PM

scrnli_7_25_2022_4-13-11 PM

see video: 

https://user-images.githubusercontent.com/90208051/180806211-2a9b3dee-c855-446f-bfbb-f6ec291e8da1.mp4

Also issue reproduced on PS 1.7.8.6

### Expected behavior

Subcategory can be selected

### Steps to reproduce

1. Enable multistore in BO 
2. Select some color for each shop 
3. Go to some product page in BO
4. Try to select subcategory for the product 

### PrestaShop version(s) where the bug happened

1.7.8.6 / 8.0.0 

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In shop configuration for multishop, categories tree was broken which induced some weird behavior when creating / editing a shop.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Closes #29159
| Related PRs       | Na.
| How to test?      | Cf. #29159 :point_up: Please notice that "color" edition isn't important. The problem is that subcategories are not properly checked in creation/edition form. 
| Possible impacts? | Shop creation/edition for multishop.

### CODE REVIEW

File: controllers/admin/AdminShopController.php [hunk 1]
```diff
@@ -217,14 +217,30 @@ public function renderList()
...
-            foreach ($children as $child) {
-                $selected_cat[] = $child['id_category'];
-            }
+            // Array responsible of selected categories storage.
+            // To make this array construction easier, we use [ (int) 'category_id' => (int) 'category_id'] format.
+            $selected_categories = [];
+
+            // This recursive anonymous function is in charge of building categories tree.
+            $add_children_categories = function (int $category_id) use (&$selected_categories, &$add_children_categories): void {
+                $children = Category::getChildren($category_id, $this->context->language->id);
```
Comment (matks) [inline controllers/admin/AdminShopController.php]: When I this behavior I tell myself... mmm maybe we can put this code in a dedicated class and unit test it? 😄

Comment (MeKeyCool) [reply controllers/admin/AdminShopController.php]: :thinking: Interesting idea.
Should I create some `PrestaShopBundle\Utils\Tree` class ? Maybe some class exists already ?

Comment (matks) [reply controllers/admin/AdminShopController.php]: Yes for a `Tree` class 👍 it works for me

**Comment by FabienPapet** [comment]
@matks friendmy ping for review please before you go

**Comment by matks** [comment]
> @matks friendmy ping for review please before you go

The sea is calling me ⛵ ...

I can't ... review ... 🌴 🍸

**Review by matks — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @MeKeyCool ,

PR is tested and issue is well fixed.

[Untitled_ Sep 27, 2022 9_35 AM.webm](https://user-images.githubusercontent.com/111756615/192534809-841a8291-31a9-466c-8f80-e4430c1dadd9.webm)

The automated tests and PR are QA validated :heavy_check_mark: 

Thank you,
