### PR TITLE
Multi-carrier - handle product customization

### LINKED ISSUE #40288: [Multicarrier] Customizable product - number products are multiplied by number of products in the cart (not number of items) : impacts on order confirmation page, order detail page, order page (BO)
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

1. First product added into cart in 2 quantities (= 2 items)
2. Second product added into cart in 3 quantities (= 3 items)
3. Checkout complete, order confirmation page is displayed 
4. On the order confirmation page, first product in 2 quantities is displayed TWICE (= 4 items) and the second product in 3 quantities in displayed TWICE (= 6 items) ((in total 10 ITEMS))
5. On the order detail page :
with classic theme : first product in 2 quantities is displayed TWICE (= 4 items) and the second product in 3 quantities in displayed TWICE (= 6 items) ((in total 10 ITEMS))
with hummingbird theme : first product is displayed twice with zero quantity ( zero quantity bug is already opened https://github.com/PrestaShop/PrestaShop/issues/40276) and the second product is displayed twice in zero quantity.
6. Order is displayed (BO)
7. The shipment tab indicates 10 items

https://github.com/user-attachments/assets/83a43074-68bc-490a-bf20-ca90aa3e438a

https://github.com/user-attachments/assets/96a487df-1013-4521-bd8f-b3cd3226a19f

### Expected behavior

1. First product added into cart in 2 quantities (= 2 items)
2. Second product added into cart in 3 quantities (= 3 items)
3. Checkout complete, order confirmation page is displayed 
4. On the order confirmation page, first product is in 2 quantities and the second product in 3 quantities (5 items in total)
5. On the order detail page, first product is in 2 quantities and the second product in 3 quantities (5 items in total)
6. Order is displayed (BO)
7. The shipment tab indicates 5 items

### Steps to reproduce

**Pré cond** 
- Fresh new shop 
- "Improve shipment" feature flag activated
- Hummingbird theme or Classic theme (both themes are concerned by this issue)

1. Add to basket 1 customizable product in 2 quantities
2. Add to basket another customizable product in 3 quantities
3. Proceed to checkout 
4. Check numbers of products on the order confirmation page
5. Check this order detail page
6. On the BO, go on the order
7. Check the shipment tab

### PrestaShop version(s) where the bug happened

develop branch

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

improve shipment feature flag

### Your company or customer's name goes here (if applicable).

PS

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Added customizable product management during shipment creation.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/40288
| UI Tests          | -
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/40288
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by Poulinhoo — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by ga-devfront — DISMISSED** [review]

**Review by ingridusta — COMMENTED** [review]
Hi @M0rgan01, 

Unfortunately I still have a bug, on the order detail page. Can you confirm it's still linked to your pr, or tell me if I should open a new issue on the Detail Order Page, specifically ? 

With both themes, no bug found on the final summary and order confirmation page. 

But on the order detail page, when the merchant splits the order, products with their quantity are multiplied by the number of products (not items) in the cart. Here is a video of the test (on classic theme) > you can skip to 1'24" for the interesting moment : 

https://github.com/user-attachments/assets/905dfb04-197a-4ead-967a-2842b1caf77f

On Hummingbird theme (0 quantity is displayed for each product, (which is an issue already opened : https://github.com/PrestaShop/PrestaShop/issues/40276), but each row of product are also multiplied by two : 

Capture d’écran 2025-12-11 à 23 10 30

File: src/Adapter/Shipment/OrderShipmentCreator.php [hunk 1]
```diff
@@ -77,17 +77,43 @@ public function addShipmentOrder(Order $order, array $productsHandledByCarrier):
...
+     *     id_order_detail: int,
+     *     product_id: int,
+     *     product_quantity: int
+     * } $orderDetailProduct
+     *
+     * @return bool
+     */
+    private function needShipmentProductCreation(array $product, array $orderDetailProduct): bool
+    {
+        if (!empty($product['id_customization'])) {
```
Comment (Hlavtox) [inline src/Adapter/Shipment/OrderShipmentCreator.php:114]: I think that you should be matching by both id_product, id_product_attribute and id_customization.

But it's still a code smell and a potential point of failure. It should be refactored before going into production imho.

**Review by ingridusta — DISMISSED** [review]
Hi @M0rgan01, 

As you explained me, the issue I wrote about in my previous comment is the one already opened on which I will add the price impact. 

I also tested the case you told me : 
Customizable product with combination.

https://github.com/user-attachments/assets/166b55a3-3f91-40c4-aa53-d81e3a9f2344

It's QA approved ✅ thank you !

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@M0rgan01 @ingridusta 

Can you please check if it works with combinations? I have a feeling that it won't, maybe I am wrong.

What if you order two products with different combinations? The ID of product will be the same, how will you match it?

Dismiss the review if it works fine. :-)

**Comment by ingridusta** [comment]
Hi @Hlavtox, going to test it and keep you in touch.

**Comment by ingridusta** [comment]
Hi @Hlavtox, 

Thanks for your request, you are right, we still have an issue using combination products : 

https://github.com/user-attachments/assets/d3b9e61e-7477-4a48-b01d-db6da28ad9da

**Comment by M0rgan01** [comment]
@Hlavtox good catch

**Review by ga-devfront — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
Thanks guys, it should work now. :-)

_If it was me, I would still try to find time to try to make the data coming from one, already presented source of truth, so we don't have to call `OrderDetail::getList($order->id)`. Maybe you could pass OrderLazyArray instead of Order, it could have more data._

**Review by ingridusta — APPROVED** [review]
Hi @M0rgan01, 

Thanks for ur fix, now customizable products works too. And no regression detected on virtual product and physical product. On each theme : classic and hummingbird ! 

https://github.com/user-attachments/assets/c172b6ba-d4fe-48f6-8957-d3c2cbf1c9a9


https://github.com/user-attachments/assets/48c0a30a-17fc-415d-94aa-e0d768e4f07e

GG !! It's QA approved ✅

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
UI tests in progress, please wait before merging this PR https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/20188743225 ✅

**Comment by nicosomb** [comment]
Thank you @M0rgan01 and @ingridusta !
