### PR TITLE
Change product status in the BO search results

### LINKED ISSUE #19105: Change product status in the BO search results
#### Describe the bug

You cannot change the product status in the BO search results when you click on enable / disable.

#### Steps to Reproduce

1 - Go to BO
2 - Search for a product in the search bar
3 - In the results table, click on the enable (✔️) or disable (❌) icon
4 - You are redirected to the product page, but the product status is always the same

**Screenshots**

See Screenshot : https://drive.google.com/file/d/1cpuYBronnQlCnZJXWRGngaigbuAUIb8v/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | You cannot change the product status in the BO search results when you click on enable / disable.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19105
| How to test?  | See description below: 

 Capture du 2020-05-11 20-44-40

### Before fix : 

1 - Go to BO
2 - Search for a product in the search bar
3 - In the results table, click on the enable (✔️) or disable (❌) icon
4 - You are redirected to the product page, but the product status is always the same

See Screenshot : https://drive.google.com/file/d/1cpuYBronnQlCnZJXWRGngaigbuAUIb8v/view

### After fix (and improvements)

1 - Go to BO
2 - Search for a product in the search bar
3 - In the results table, click on the enable (✔️) or disable (❌) icon
4 - The status is updated or not and a confirmation or error message is displayed (This is an improvement, because the user does not necessarily want to go to the product page afterwards, for that he must click on the modify button)

See Screenshot :  https://drive.google.com/file/d/1avU7vyRhrDnlZ80adhanuuvQIujGMWCY/view

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19080)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: controllers/admin/AdminSearchController.php [hunk 1]
```diff
@@ -67,8 +67,17 @@ public function postProcess()
         $action = Tools::getValue('action');
         if ($action == 'redirectToProduct') {
             $id_product = (int) Tools::getValue('id_product');
-            $link = $this->context->link->getAdminLink('AdminProducts', false, ['id_product' => $id_product]);
-            Tools::redirectAdmin($link);
+            $product = new Product($id_product);
+            if (Validate::isLoadedObject($product) && Tools::getIsset('statusproduct')) {
+                if ($product->toggleStatus()) {
+                    $this->confirmations[] = $this->trans('The status has been updated successfully', [], 'Admin.Notifications.Success');
```
Comment (LouiseBonnard) [inline controllers/admin/AdminSearchController.php]:
```suggestion
                    $this->confirmations[] = $this->trans('The status has been updated successfully.', [], 'Admin.Notifications.Success');
```

Comment (LouiseBonnard) [reply controllers/admin/AdminSearchController.php]: Hi @PululuK, I would recommend the version with a dot at the end so that both notifications (error and success) stay consistent. :-)

Comment (PululuK) [reply controllers/admin/AdminSearchController.php]: Thank you @LouiseBonnard  !

**Review by LouiseBonnard — DISMISSED** [review]

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-product-team for validating the behavior.

**Comment by LouiseBonnard** [comment]
I agree with the behavior but couldn't put my finger on the related issue mentioned by @PululuK in the pull request description. :-(

**Comment by Progi1984** [comment]
@PululuK Could you finally open an issue ? And fix Travis CI ? Thanks ;)

**Comment by PululuK** [comment]
> And fix Travis CI ?

@Progi1984  Why travis is broken then ?  🤔

**Comment by PululuK** [comment]
#19105

**Comment by boubkerbribri** [comment]
> > And fix Travis CI ?
> 
> @Progi1984 Why travis is broken then ? thinking

It was just a false flag, i restarted it.

**Review by Progi1984 — DISMISSED** [review]

File: controllers/admin/AdminSearchController.php [hunk 2]
```diff
@@ -67,8 +67,17 @@ public function postProcess()
...
+            if (Validate::isLoadedObject($product) && Tools::getIsset('statusproduct')) {
+                if ($product->toggleStatus()) {
+                    $this->confirmations[] = $this->trans('The status has been updated successfully.', [], 'Admin.Notifications.Success');
+                } else {
+                    $this->errors[] = $this->trans('An error occurred while updating the status.', [], 'Admin.Notifications.Error');
+                }
+            } else {
+                $link = $this->context->link->getAdminLink('AdminProducts', false, ['id_product' => $id_product]);
+                Tools::redirectAdmin($link);
+            }
```
Comment (PierreRambaud) [inline controllers/admin/AdminSearchController.php]:
```suggestion
            if (Tools::getIsset('statusproduct')) {
                $product = new Product($id_product);
            }

            if (isset($product) && Validate::isLoadedObject($product)) {
                if ($product->toggleStatus()) {
                    $this->confirmations[] = $this->trans('The status has been updated successfully.', [], 'Admin.Notifications.Success');
                } else {
                    $this->errors[] = $this->trans('An error occurred while updating the status.', [], 'Admin.Notifications.Error');
                }
            } else {
                $link = $this->context->link->getAdminLink('AdminProducts', false, ['id_product' => $id_product]);
                Tools::redirectAdmin($link);
            }
```

Do not load the Product object if it's not needed.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
See comments

**Review by Progi1984 — APPROVED** [review]

**Review by LouiseBonnard — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
@PululuK It seems like you have SCSS styleint issues, last thing to fix this PR should be good ;)

**Comment by PululuK** [comment]
> @PululuK It seems like you have SCSS styleint issues, last thing to fix this PR should be good ;)

Thank you @matthieu-rolland  !
Ok SCSS is broken ... but why ?

**Comment by NeOMakinG** [comment]
@PululuK trying to run it again, because it looks not linked to Stylelint 👀

**Comment by NeOMakinG** [comment]
@PululuK It's fine now, it was probably a problem with github when the action ran, nothing related to your work or our linters!

Thanks for your contribution

**Comment by Robin-Fischer-PS** [comment]
It's QA approved :heavy_check_mark: , thanks @PululuK ! :smile:

**Comment by PierreRambaud** [comment]
Thanks @PululuK
