### PR TITLE
Creation of a LegacyController for display a legacy page in a symfony layout

### LINKED ISSUE #32980: Create generic Symfony controller able to display a legacy page && handle its display via the Symfony controller automatically
## Description 

The legacy pages are rendered thanks to the Dispatcher from the index.php For now, the idea is to reverse what the legacy layout was. We need a `LegacyController::legacyPageAction` that would be used as a wrapper around the legacy controllers. In this controller the layout is rendered by Symfony and only the content at the center would be rendered by the legacy controller wrapped. The first step is to have this controller usable via a forced URL with the legacy controller passed as a parameter.

Like the generical Symfony layout is based on a Twig component, this legacy display should also be handled via a Twig component that will look like the generic one a lot except for a few exceptions that we need to anticipate (non-exhaustive list):
- the theme used should be the default one not the new-theme
- the loaded assets should match with the ones originally set via `AdminController::setMedia(false)`
- we need to handle correctly the backward compatibility, although it should already have been handled by #33191
- ... there may be some other things to consider / think about

Once the generic controller is done and the controller is available we can then remove the principle based on `RouteNotFoundException` in the `index.php` file, any URL even the legacy ones would be handled via Symfony

Some generic route mapping will need to be found to catch the legacy URLs, the URL should not change to avoid breaking changes, it's just that the layout would now be handled by Symfony. This will simplify the work about authentication by Symfony a lot since after this ALL the pages (including the legacy ones) would be handled by the framework.

Example:
```yaml
legacy_controller_route:
  path: /controller={controllerName}
  defaults:
    _controller: LegacyLayoutController::legacyPageAction
```

## Acceptance test 

1. This controller should be able to display a legacy page ( TBD ) 
Could be test manually by forcing the URL  

2. Handle legacy page display via the Symfony controller automatically and systematically

3. UI tests work fine with Symfony layout enabled, and on legacy pages

4. Test multistore shop list 

5. Test the productcomment in the BO. It should work as ISO

### LINKED ISSUE #33804: Handle legacy modals for legacy pages rendered with Symfony layout
### Presentation

In legacy pages there is a feature to render modals easily, it is based on a `modal.tpl` smarty template
The modal are then rendered by this method:
https://github.com/PrestaShop/PrestaShop/blob/bea5f35b76d6178311d0130fc9cc9513c09d2fb6/classes/controller/AdminController.php#L2336-L2346

Which is itself called in the initFooter (modals are probably also inserted in the footer of the page)
https://github.com/PrestaShop/PrestaShop/blob/bea5f35b76d6178311d0130fc9cc9513c09d2fb6/classes/controller/AdminController.php#L2312

This is a sub-task of what we'll have to handle for backward compatibility in https://github.com/PrestaShop/PrestaShop/issues/33191

classes/controller/AdminController.php
controllers/admin/AdminImportController.php : progress bar
controllers/admin/AdminModulesController.php : confirm how to remove 

### Expected result

This feature is a legacy one and we shouldn't incite to use it more on migrated pages, so this shouldn't be handled by the Symfony layout. Also, no need to display this modal via twig so it should only be handled by the bridge for legacy pages and when admin controller will be fully removed in the future this feature will also disappear.

### Acceptance tests 

ISO

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR is the end of the road for the Symfony layout feature, the migrated pages were already handled thanks to Twig components that are all based on the new-theme BO theme For legacy pages they are all based on the default BO theme, so first all the global layout HTML code and the Twig components templates had to be adapted to render the default theme The a generic Symfony controller `LegacyController` was added as a wrapper around the legacy controller, it serves the role the legacy `Dispatcher` had to detect the appropriate controller class and execute its workflow in the correct order But it only renders the central page of the page, the surrounding layout is handled by the Symfony components<br>Also to make legacy and migrated pages fully compatible the query token was changed so that all pages now rely on a Symfony CSRF token
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | ~
| UI Tests          | Symfony: https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7656417184 Legacy: https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7656804352
| Fixed issue or discussion?     | Fixes #32980 and Fixes #33804
| Related PRs       | -
| Sponsor company   | -

### Breaking change

Once the feature is removed and the symfony layout becomes the default/only behavior
The main change from this pr, besides rendering everything via symfony layout, is that the query token in the back office are now **always** symfony CSRF tokens even in legacy pages This means the way to check if a legacy token is valid and also the generation of such tokens don't work any more, the legacy values will be considered as invalid

But this breaking change impact is reduced because it only applies in cases where the token are generated manually (using Hashing methods directly), for all the usual use cases as long as the `Tools::getAdminToken` method is used the proper CSRF token will be generated and used thanks to the `UserTokenManager::getSymfonyToken` that is forcefully used in it regardless of the parameter used

However validation is now different, you can't generate the expected token and compare it to the value in the URL any more, because each CSRF token is unique for each request and must be validated based on stored data. But to ease this process two methods are possible:
- using `UserTokenManager::isTokenValid` this method handles everything internally from fetching the token request value different possibilities to using the token manager to check its validity It can also check for legacy tokens validity and automatically switches its check depending on the value of the feature flag
- using `LegacyAdminTokenValidator::isTokenValid` method, this method is also able to fetch the proper parameters from the request (both legacy token and CSRF tokens), but you can specify the parameters (optional) in case you need more specific control This service is "legacy-compliant" meaning it relies on services accessible and usable in legacy environment like the FrontEnd, that's why it's part of the front dedicated service, it's not available in the back office but there's no reason why it should be so far

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/CustomLegacyController.php [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+use Dispatcher;
+use DOMDocument;
+use DOMXPath;
+use PrestaShop\PrestaShop\Adapter\LegacyContext;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+use Tools;
+
+class CustomLegacyController extends PrestaShopAdminController
```
Comment (mickaelandrieu) [inline src/PrestaShopBundle/Controller/Admin/CustomLegacyController.php]: This is smart, but I'd inject something like a ``ToolsManager`` so you remove every mention of legacy classes and ease the migration the day you will migrate these classes.
Also ToolsManager may be reused, and transformer accordingly at every occasion where we can safely remove a direct call to ``Tools`` class.

Here, you can probably set the controller key into the $_POST/ Request Symfony query (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#L464)

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/CustomLegacyController.php]: This was still a draft but we actually don't need `Tools` here anymore, so no more problem

File: tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts [hunk 2]
```diff
@@ -263,10 +263,7 @@ describe('BO - Customer Service - Merchandise Returns : Delete product', async (
   });
 
   describe('BO : Delete products from merchandise return', async () => {
-    [
-      {args: {understandTheRisk: false, button: 'Take me out of here!'}},
-      {args: {understandTheRisk: true, button: 'I understand the risks and I really want to display this page'}},
-    ].forEach((test, index: number) => {
+    [1, 2].forEach((index: number) => {
```
Comment (Progi1984) [inline tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts:266]: I think you can remove the `forEach` loop.

**Review by Progi1984 — COMMENTED** [review]
A small feedback

File: tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts [hunk 3]
```diff
@@ -289,28 +286,17 @@ describe('BO - Customer Service - Merchandise Returns : Delete product', async (
         expect(pageTitle).to.contains(editMerchandiseReturnsPage.pageTitle);
       });
 
-      it(`should delete the first returned product and click on '${test.args.button}'`, async function () {
+      it('should delete the first returned product', async function () {
```
Comment (Progi1984) [inline tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts:289]: Here you can remove the second returned product and after the first one... (no need to loop)

File: controllers/front/CmsController.php [hunk 4]
```diff
@@ -77,10 +79,16 @@ public function init()
...
+            if (!$this->cms->isAssociatedToShop()) {
                 $this->redirect_after = '404';
                 $this->redirect();
+            } elseif (!$this->cms->active) {
+                $adminTokenValidator = $this->getContainer()->get(LegacyAdminTokenValidator::class);
+                $isAdminTokenValid = $adminTokenValidator->isTokenValid('AdminCmsContent', (int) Tools::getValue('id_employee'), Tools::getValue('adtoken'));
+                if (!$isAdminTokenValid) {
+                    $this->redirect_after = '404';
+                    $this->redirect();
+                }
```
Comment (M0rgan01) [inline controllers/front/CmsController.php:91]: for an invalid token, I would rather use error code 401, or 403 if it is a role problem

File: src/Core/FeatureFlag/FeatureFlagManager.php [hunk 5]
```diff
@@ -108,4 +114,26 @@ public function disable(string $featureFlagName): void
...
+     * @return bool
+     */
+    private function getFeatureFlagState(string $featureFlagName): bool
+    {
+        if (!isset($this->featureFlagStates[$featureFlagName])) {
+            $this->featureFlagStates[$featureFlagName] = $this->getLayer($featureFlagName)->isEnabled($featureFlagName);
+        }
+
+        return $this->featureFlagStates[$featureFlagName];
+    }
```
Comment (M0rgan01) [inline src/Core/FeatureFlag/FeatureFlagManager.php:138]: Nice

File: src/PrestaShopBundle/Controller/Admin/LegacyController.php [hunk 6]
```diff
@@ -0,0 +1,253 @@
...
+            foreach ($templateDirectories as $templateDirectory) {
+                if (file_exists($templateDirectory . DIRECTORY_SEPARATOR . $actionTemplate) && $controllerDisplay != 'view' && $controllerDisplay != 'options') {
+                    if (method_exists($this, $controllerDisplay . u($adminController->className)->camel())) {
+                        $this->{$controllerDisplay . u($adminController->className)->camel()}();
+                    }
+                    $smarty->assign('content', $smarty->fetch($actionTemplate));
+
+                    break;
+                }
+            }
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Controller/Admin/LegacyController.php]: I had to go over it several times to try to understand the code. Maybe a few comments would help with readability.

File: src/PrestaShopBundle/Controller/Admin/PrestaShopAdminController.php [hunk 7]
```diff
@@ -50,4 +52,9 @@ protected function dispatchCommand(mixed $command): void
     {
         $this->container->get(CommandBusInterface::class)->handle($command);
     }
+
+    protected function dispatchHookWithParameters(string $hookName, array $parameters = []): void
+    {
+        $this->container->get(HookDispatcherInterface::class)->dispatchWithParameters($hookName, $parameters);
+    }
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Controller/Admin/PrestaShopAdminController.php:59]: Indeed it has its place in subscribed Services

File: src/PrestaShopBundle/DependencyInjection/Compiler/TestEnvironmentPass.php [hunk 8]
```diff
@@ -41,10 +41,18 @@ public function process(ContainerBuilder $container)
...
+
+        // see https://symfony.com/doc/current/testing.html#multiple-requests-in-one-test
+        $container->getDefinition('security.token_storage')->clearTag('kernel.reset');
+        $container->getDefinition('doctrine')->clearTag('kernel.reset');
+
+        // Force some aliases to be public because they are needed in the integration test case classes
+        // see https://symfony.com/doc/6.4/testing.html#retrieving-services-in-the-test
+        $container->getDefinition('form.factory')->setPublic(true);
+        $container->getDefinition('security.csrf.token_manager')->setPublic(true);
+        $container->getDefinition('serializer')->setPublic(true);
```
Comment (M0rgan01) [inline src/PrestaShopBundle/DependencyInjection/Compiler/TestEnvironmentPass.php]: I think we can avoid doing that. We use the wrong getContainer method in testing. See https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L80-L101. 

For exemple, for form.factory we must do that

   ```
protected function getFormFactory(): FormFactoryInterface
    {
        - return self::$kernel->getContainer()->get('form.factory');
        + return self::getContainer()->get('form.factory');
    }
```

File: src/PrestaShopBundle/Resources/config/services/bundle/common.yml [hunk 9]
```diff
@@ -0,0 +1,17 @@
...
+    arguments:
+      - PrestaShopBundle\Entity\FeatureFlag
+    lazy: true
+
+  PrestaShopBundle\Entity\Repository\TabRepository:
+    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
+    public: false
+    arguments:
+      - PrestaShopBundle\Entity\Tab
+    lazy: true
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Resources/config/services/bundle/common.yml]:
```suggestion
services:
  _defaults:

  PrestaShopBundle\Entity\Repository\FeatureFlagRepository:
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    public: true
    arguments:
      - PrestaShopBundle\Entity\FeatureFlag
    lazy: true

  PrestaShopBundle\Entity\Repository\TabRepository:
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - PrestaShopBundle\Entity\Tab
    lazy: true
```

Comment (M0rgan01) [reply src/PrestaShopBundle/Resources/config/services/bundle/common.yml]: (is the public necessary?)

File: src/PrestaShopBundle/Resources/config/services/bundle/services.yml [hunk 10]
```diff
@@ -116,6 +115,12 @@ services:
       $storage: "@security.csrf.token_storage"
     autowire: true
 
+  PrestaShopBundle\Security\Admin\UserTokenManager:
+    public: true
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Resources/config/services/bundle/services.yml]: not obligatory thanks to default

File: src/PrestaShopBundle/Resources/config/services/core/quick_access.yml [hunk 11]
```diff
@@ -0,0 +1,10 @@
+services:
+  _defaults:
+    public: false
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Resources/config/services/core/quick_access.yml]: This is already the default value it seems to me

File: src/PrestaShopBundle/Resources/views/Admin/Layout/legacy_layout.html.twig [hunk 12]
```diff
@@ -0,0 +1,155 @@
...
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * #}
+<!DOCTYPE html>
+<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7 lt-ie6"> <![endif]-->
+<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8 ie7"> <![endif]-->
+<!--[if IE 8]>    <html class="no-js lt-ie9 ie8"> <![endif]-->
+<!--[if gt IE 8]> <html class="no-js ie9"> <![endif]-->
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Resources/views/Admin/Layout/legacy_layout.html.twig:29]: we hadn't put this piece of code in the symfony layout, is it important?

File: controllers/front/CmsController.php (hunk 4 above)
Comment (jolelievre) [reply controllers/front/CmsController.php:91]: This an existing feature that allows previewing content when they are offline, but only when you are registered as employee When you are not logged in the BO then the usual FO behaviour is occurring, which is to display a not found page for a disabled content in this case

File: src/PrestaShopBundle/Controller/Admin/LegacyController.php (hunk 6 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/LegacyController.php]: It's just copy/paste from legacy AdminController code, but I can comment it a bit for the general idea

File: src/PrestaShopBundle/DependencyInjection/Compiler/TestEnvironmentPass.php (hunk 8 above)
Comment (jolelievre) [reply src/PrestaShopBundle/DependencyInjection/Compiler/TestEnvironmentPass.php]: Ok I'll try that

File: src/PrestaShopBundle/Resources/config/services/bundle/common.yml (hunk 9 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/services/bundle/common.yml]: Good question, I'll check but maybe a wrong copy/paster indeed

File: src/PrestaShopBundle/Resources/views/Admin/Layout/legacy_layout.html.twig (hunk 12 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Layout/legacy_layout.html.twig:29]: I don't know it's from the layout in default theme, the new-theme is different indeed, I didn't think about the relevance of the layout I just tried to reproduce it as accurately as possible I think it's better to keep it this way, there are some really weird stuff the legacy pages are relying on, like disabling cache control on all the pages so I prefer not to mess with this

File: tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts (hunk 2 above)
Comment (jolelievre) [reply tests/UI/campaigns/functional/BO/05_customerService/03_merchandiseReturns/02_deleteProduct.ts:266]: I'm not sure I need to delete the first two products successfully, and the third one is blocked by a constraint

**Review by Progi1984 — DISMISSED** [review]
OK for UI Tests

File: src/PrestaShopBundle/Controller/Admin/LegacyController.php (hunk 6 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/LegacyController.php]: And I just realized the code was wrong I'm searching for method on the Symfony controller via `$this` instead of the methods from `$adminController`

File: src/PrestaShopBundle/DependencyInjection/Compiler/TestEnvironmentPass.php (hunk 8 above)
Comment (jolelievre) [reply src/PrestaShopBundle/DependencyInjection/Compiler/TestEnvironmentPass.php]: I'll wait for your PR on SF 6.4 to rebase this branch since you already fixed all this

File: src/PrestaShopBundle/Resources/config/services/bundle/common.yml (hunk 9 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/services/bundle/common.yml]: Seems like they can, and should, be private

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/services/bundle/common.yml]: They are private now

**Review by jolelievre — APPROVED** [review]

**Review by boherm — APPROVED** [review]
LGTM! Nice ;)

**Review by Progi1984 — APPROVED** [review]
OK for UI Tests

**Comment by Progi1984** [comment]
@jolelievre No need QA as it is behind a feature flag.
