### PR TITLE
fix(Cart): fix notice saving customization when customer field is empty and not required

### LINKED ISSUE #30464: save customization when customer fied is empty and not required
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

From the FO, if I save the customization of a product while one of text field is empty and not required, an error appears.

image

image

### Expected behavior

the error should not appear

### Steps to reproduce

On BO :
1. Catalog > Products > Choose a product
2. Option > Add customization field, Type Text, and not Required
3. Save

On FO : 
4. Open the product on FO
5. do not fill in empty customization text fields
6. Save customization
7. See error

### PrestaShop version(s) where the bug happened

develop - 8.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0
| Description?      | I check that the query returns the customization.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30464.
| Related PRs       | no
| How to test?      | Follow issue video steps no notices are shown.
| Possible impacts? | no

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -4323,8 +4323,12 @@ public function deleteCustomizationToProduct($id_product, $index)
             AND `in_cart` = 0'
         );
 
+        if (!$cust_data) {
```
Comment (nicosomb) [inline classes/Cart.php:4321]: Just to be sure and to understand this code: if the previous query fails (then `$cust_data` is empty), do we need to return `true` (the current value for `$result`) or `false` ?

Comment (davidglezz) [reply classes/Cart.php:4321]: If the query returns 0 rows `$cust_data === false`.

I return `$result` (`true`), because its ok, no error deleting customization, there was simply nothing to delete.

Comment (davidglezz) [reply classes/Cart.php:4321]: I confirm that the query is correct.

**Comment by MatShir** [comment]
The bug is flagged as a regression, you can target the 8.0.x branch :)

**Comment by davidglezz** [comment]
@MatShir done

File: classes/Cart.php [hunk 2]
```diff
@@ -4320,8 +4320,12 @@ public function deleteCustomizationToProduct($id_product, $index)
...
+            return $result;
```
Comment (zuk3975) [inline classes/Cart.php]: minor suggestion (not blocking)
```suggestion
            return true;
```
and move the variable $result from line 4311 to somewhere after the if statement (line ~4326)
It is practically the same, except we don't init useless variable in case the $cust_data is falsy.

**Review by zuk3975 — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

File: classes/Cart.php (hunk 2 above)
Comment (davidglezz) [reply classes/Cart.php]: done

**Review by nicosomb — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @davidglezz ,

I checked your PR and here is my checked list :

1. multilanguage: OK :heavy_check_mark: 
2. different browsers: OK :heavy_check_mark: 
3. multistore: OK :heavy_check_mark: 
4. automated tests: OK :heavy_check_mark:  

Thank you !

**Comment by MatShir** [comment]
🚀 let's merge it !!!!

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @davidglezz 👍
