### PR TITLE
Fixed API inconsistent return format of JSON

### LINKED ISSUE #22760: API /orders endpoint inconsistent return format of JSON
#### Describe the bug

Endpoint /orders have 2 different formats of json returned based on quantity of orders which will be fetched.

#### Expected behavior

I expect it to returns orders in same format, or different HTTP status code for empty list. The first one is a preffered

#### Steps to Reproduce

1. Call api /orders?output_format=JSON&display=full
2. It will be in format
`{
    "orders": [
        {
        ...
}
]}`
3. Call api /orders?output_format=JSON&display=full&limit=100000,20 (or other limit number which will return empty list)
4. Response will be in format
`[]`

That format is wrong, if you look at xml response you can see that it always returns format
```
<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
    <orders></orders>
</prestashop>
```

Preffered format of json for empty list of orders should be like this:
```
{
    "orders": []
}
```
Now you clearly see that base object is an Object not a List/Array of objects and that orders are empty

**Screenshots**
image
image

XML screenshots
image
image

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.2.33

### PR DESCRIPTION
**Pull request by Kyaary**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | API returns a different format of JSON when it returns an empty list.
| Type?             | bug fix
| Category?         |  WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22760 
| How to test?      | Call api /orders?output_format=JSON&display=full&limit=100000,20 (or other limit number which will return empty list)

**How it looks ?**
See [#22760 comment](https://github.com/PrestaShop/PrestaShop/issues/22760#issuecomment-766392118)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22969)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @Kyaary 
With your PR applied and without applying limits I have nothing left when I call the api on other pages which should normally contain something
**Without your PR**
I call => "/api/products?output_format=JSON&display=full"
I have this return
image

**With your PR applied**
Same api call => "/api/products?output_format=JSON&display=full"
I have this result
image

**Comment by yannicka** [comment]
Doesn't this break backwards compatibility, since the value returned by the API, when the data array is empty, is different between before and after this PR?

File: classes/webservice/WebserviceOutputJSON.php [hunk 1]
```diff
@@ -163,6 +163,11 @@ public function renderNodeFooter($node_name, $params)
 
     public function overrideContent($content)
     {
+        array_walk_recursive($this->content, function (&$item) {
+            if (is_null($item)) {
```
Comment (PierreRambaud) [inline classes/webservice/WebserviceOutputJSON.php:167]:
```suggestion
            if ($item !== null) {
```

Never use is_null function, it's slow :)

File: classes/webservice/WebserviceOutputJSON.php [hunk 2]
```diff
@@ -163,6 +163,11 @@ public function renderNodeFooter($node_name, $params)
...
+                $this->content[key($this->content)] = [];
+            }
+        });
```
Comment (PierreRambaud) [inline classes/webservice/WebserviceOutputJSON.php]:
```suggestion
        array_walk_recursive($this->content, function (&$item) {
            if ($item === null) {
                $item = [];
            }
        });
```

Never use is_null method, it's slow.
I think you want to add empty array on $item, not everywhere :)

**Review by PierreRambaud — DISMISSED** [review]
Few comments

File: classes/webservice/WebserviceOutputJSON.php (hunk 2 above)
Comment (Kyaary) [reply classes/webservice/WebserviceOutputJSON.php]: With your solution, I get the following result :
image

I tried this, and I think I got the expected result :
```suggestion
       if(count($this->content[key($this->content)])==1){
            array_walk_recursive($this->content, function (&$item) {
                if ($item === null) {
                    $this->content[key($this->content)] = [];
                }
            });
        }
```
image
image


Otherwise, as mentionned in [this comment](https://github.com/PrestaShop/PrestaShop/issues/22760#issuecomment-767403666), wouldn't it be easier and more relevant to just return "{}" when the query returns no results ?

Comment (PierreRambaud) [reply classes/webservice/WebserviceOutputJSON.php]: I'm not sure it's the right solution. If there is only one element, why doing an array_walk_recursive :thinking:

**Comment by PierreRambaud** [comment]
It should be better right now.

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
LGTM, waiting for @PierreRambaud 's aproval before sending in QA

**Comment by SD1982** [comment]
LGTM thanks @Kyaary and @PierreRambaud !!

**Comment by atomiix** [comment]
Thanks @Kyaary & @SD1982 !
