### PR TITLE
Handle multishop for packed products in product page V2

### LINKED ISSUE #29343: BO - A duplication of combinations products when adding them in a pack product when multistore is enabled with product V2
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A duplication of combinations when adding them in a pack product when multistore is enabled 
This bug is introduced when enabling multistore at least once and even when it's disable it, the issue still present.

**8.0.x : NOK** :x: 
image

https://user-images.githubusercontent.com/92912932/184661672-f60f11b2-f0af-47da-b2d7-1005393aa75d.mp4

### Expected behavior

_No response_

### Steps to reproduce

1. BO > Add a product V2 (any type)
2. Add a packed product
3. Add the created products for the packed one ==> OK not duplication!
4. Enable multistore
5. Edit the packed product
6. Make some changes and Save
7. See error > The related products are duplicated in the pack tab ==> NOK because multistore is enabled
8. Disable multistore
9. Add a new products and a new packed product
10. Add the newest products to the packed one
11. See error > The duplication is always present ==> NOK even the multistore is disabled

### PrestaShop version(s) where the bug happened

7.3

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add shop id context when loading pack products to avoid a duplication of products when multishop and product page v2 are enabled
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29343 
| Related PRs       | 
| How to test?      | See #29343 
| Possible impacts? |

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
PHPUnit is angry 😄 you need to fix CI

**Comment by mflasquin** [comment]
> PHPUnit is angry smile you need to fix CI

Yes sure :D , about tests, @jolelievre can we discuss how we have to test product page V2 with multi-shop ?

File: src/Adapter/Product/Pack/Repository/ProductPackRepository.php [hunk 1]
```diff
@@ -74,7 +76,7 @@ public function __construct(
      *
      * @throws CoreException
      */
-    public function getPackedProducts(PackId $productId, LanguageId $languageId): array
+    public function getPackedProducts(PackId $productId, LanguageId $languageId, ShopId $shopId): array
```
Comment (atomiix) [inline src/Adapter/Product/Pack/Repository/ProductPackRepository.php]: I think this is a BC Break, you should specify it in the PR description table ;)

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php [hunk 2]
```diff
@@ -71,7 +71,7 @@ class ProductFormDataProvider implements FormDataProviderInterface
     private $defaultShopId;
 
     /**
-     * @var int
+     * @var int|null
```
Comment (Amoifr) [inline src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: not sure that lower php version will support this

**Review by Amoifr — COMMENTED** [review]
Hello from outside ;-)

File: src/Core/Domain/Product/Pack/Query/GetPackedProducts.php [hunk 3]
```diff
@@ -46,14 +47,21 @@ class GetPackedProducts
...
+     */
+    private $shopId;
+
     /**
      * @param int $packId
      * @param int $languageId
+     * @param int $shopId
      */
-    public function __construct(int $packId, int $languageId)
+    public function __construct(int $packId, int $languageId, int $shopId)
```
Comment (jolelievre) [inline src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]:
```suggestion
    public function __construct(int $packId, int $languageId, ShopConstraint $shopConstraint)
```

Comment (jolelievre) [reply src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]: For now you only need to handle a single shop ID, and it's enough for this PR

But in the near future we're gonna need to handle multishop feature so a `ShopConstraint` is more adapted in this case, you only need to handle the use case where it handle a single shop for now but we already anticipate that this query will rely on a `ShopConstraint` object

**Review by jolelievre — COMMENTED** [review]
Thank you @mflasquin 

Almost all good, the query only handles single shop use cases for now, but it's enough for now. 
We'll handle other use cases in a more detailed PR that will also update the related CQRS command.

Only thing that could be anticipated is the usage of `ShopConstraint` in the query constructor as I suggested in my comment

**Comment by matks** [comment]
@mflasquin friendly reminder 😄 don't forget this PR

File: src/Core/Domain/Product/Pack/Query/GetPackedProducts.php (hunk 3 above)
Comment (mflasquin) [reply src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]: Is it better @jolelievre  ?

File: src/Adapter/Product/Pack/Repository/ProductPackRepository.php [hunk 4]
```diff
@@ -88,9 +90,11 @@ public function getPackedProducts(PackId $productId, LanguageId $languageId): ar
                 ->leftJoin('pack', $this->dbPrefix . 'product_lang', 'language', 'pack.id_product_item = language.id_product')
                 ->where('pack.id_product_pack = :idProduct')
                 ->andWhere('language.id_lang = :idLanguage')
+                ->andWhere('language.id_shop = :idShop')
                 ->orderBy('pack.id_product_item', 'ASC')
                 ->setParameter('idProduct', $productId->getValue())
-                ->setParameter('idLanguage', $languageId->getValue());
+                ->setParameter('idLanguage', $languageId->getValue())
+                ->setParameter('idShop', $singleShopConstraint->getShopId());
```
Comment (jolelievre) [inline src/Adapter/Product/Pack/Repository/ProductPackRepository.php]: It's good but you should add a check at the beginning of the method if shopConstraint is allShops or shopGroupId you should trigger an exception explaining that this is not handled (you can use `InvalidShopConstraintException`)

File: src/Core/Domain/Product/Pack/Query/GetPackedProducts.php [hunk 5]
```diff
@@ -71,4 +79,12 @@ public function getLanguageId(): LanguageId
     {
         return $this->languageId;
     }
+
+    /**
+     * @return ShopConstraint
+     */
+    public function getSingleShopConstraint(): ShopConstraint
```
Comment (jolelievre) [inline src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]:
```suggestion
    public function getShopConstraint(): ShopConstraint
```

File: src/Core/Domain/Product/Pack/Query/GetPackedProducts.php [hunk 6]
```diff
@@ -46,14 +47,21 @@ class GetPackedProducts
      */
     protected $languageId;
 
+    /**
+     * @var ShopConstraint
+     */
+    private $singleShopConstraint;
```
Comment (jolelievre) [inline src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]:
```suggestion
    private $shopConstraint;
```

File: src/Core/Domain/Product/Pack/Query/GetPackedProducts.php [hunk 7]
```diff
@@ -46,14 +47,21 @@ class GetPackedProducts
...
+
     /**
      * @param int $packId
      * @param int $languageId
+     * @param ShopConstraint $singleShopConstraint
      */
-    public function __construct(int $packId, int $languageId)
+    public function __construct(int $packId, int $languageId, ShopConstraint $singleShopConstraint)
```
Comment (jolelievre) [inline src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]:
```suggestion
    public function __construct(int $packId, int $languageId, ShopConstraint $shopConstraint)
```

File: src/Core/Domain/Product/Pack/Query/GetPackedProducts.php (hunk 6 above)
Comment (jolelievre) [reply src/Core/Domain/Product/Pack/Query/GetPackedProducts.php]: This should be enough, even if for now only single shop is handled it could evolve in the future so we should keep a generic naming here

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php [hunk 8]
```diff
@@ -211,12 +211,15 @@ private function extractRelatedProducts(int $productId): array
      */
     protected function extractPackedProducts(int $productId): array
     {
+        $singleShopConstraint = $this->contextShopId ? ShopConstraint::shop($this->contextShopId) : ShopConstraint::shop($this->defaultShopId);
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]:
```suggestion
```

Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: The shop constraint is already created at the beginning of the `getData` so you should pass it as a parameter to this method, this way if we change this someday we only need to change the initial creation

**Review by jolelievre — COMMENTED** [review]
Thanks @mflasquin 

Almost good, although I don't know why but the behat tests are failing for now, you need to investigate it.

Also it would be nice if you can add some tests in multishop environment, the idea is to:
- create a pack product associated to multiple shops
- create a product with combinations associated to multiple shops
- associate the product with combinations to the pack
- assert the pack's content to make sure it doesn't contain duplicate ones, you need to test this on all the associated shops they should all have the same content since the pack associations are common to all the shops

If you need help to add those behat tests or example don't hesitate to ask.

**Comment by jolelievre** [comment]
Here's an example of a PR that added multishop management on a particular command https://github.com/PrestaShop/PrestaShop/pull/27783

You can see that the behat tests are modified a bit:
- we force the shop constraint everywhere in the command
- previous scenarios use `getDefaultShopId` as a fallback default value
- we add two new steps in update endpoints and assertion endpoint:
  - one for specific shopReferences (it can be a list that we check in a loop shop by shop)
  - one for all shops
- in your case since the command is not multishop you only need to add the new multishop endpoints for assertions I think

File: src/Adapter/Product/Pack/Repository/ProductPackRepository.php (hunk 4 above)
Comment (mflasquin) [reply src/Adapter/Product/Pack/Repository/ProductPackRepository.php]: @jolelievre what do you think about the exception I just add ?

Comment (jolelievre) [reply src/Adapter/Product/Pack/Repository/ProductPackRepository.php]: Yep, the exception makes sense

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php [hunk 9]
```diff
@@ -108,15 +114,71 @@ public function assertPackEmpty(string $packReference): void
...
+    /**
+     * @Then pack :packReference should contain products with following details for shop(s) :shopReferences:
+     *
+     * @param string $packReference
+     * @param TableNode $table
+     * @param string $shopReferences
+     */
+    public function assertPackContentsForShops(string $packReference, TableNode $table, string $shopReferences): void
+    {
+        foreach (explode(',', $shopReferences) as $shopReference) {
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php:131]: We should start reusing this. Method in some abstract context should be enough. Or if we want to go even further maybe we could think of some reusable transformation. Anyway, just a note, I think such refacto could be done in separate pr for multiple contexts at a time.

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php [hunk 10]
```diff
@@ -108,15 +114,71 @@ public function assertPackEmpty(string $packReference): void
...
+            $this->assertPackContents($packReference, $table, ShopConstraint::shop((int) $this->getSharedStorage()->get($shopReference)));
+        }
+    }
+
+    /**
+     * @Then I should get error that product for packing quantity is invalid
+     */
+    public function assertPackProductQuantityError()
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php]:
```suggestion
    public function assertPackProductQuantityError(): void
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php [hunk 11]
```diff
@@ -108,15 +114,71 @@ public function assertPackEmpty(string $packReference): void
...
+        $this->assertLastErrorIs(
+            ProductPackConstraintException::class,
+            ProductPackConstraintException::INVALID_QUANTITY
+        );
+    }
+
+    /**
+     * @Then I should get error that I cannot add pack into a pack
+     */
+    public function assertAddingPackToPackError()
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php]:
```suggestion
    public function assertAddingPackToPackError(): void
```

**Review by zuk3975 — DISMISSED** [review]
some minor suggestions

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php (hunk 9 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePackFeatureContext.php:131]: Yeah I though about it as well, but I agree it should be done separately

File: classes/ObjectModel.php [hunk 12]
```diff
@@ -2305,4 +2305,18 @@ public function getHtmlFields()
 
         return self::$htmlFields[$this->def['table']];
     }
+
+    /**
+     * @return int[]
+     */
+    protected function getShopIdsList(): array
```
Comment (zuk3975) [inline classes/ObjectModel.php:2312]: :+1:

File: tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php [hunk 13]
```diff
@@ -365,4 +363,26 @@ private function assertIndexation(string $productReference, bool $expectedIsInde
...
+                'Product type is not as expected. Expected %s but got %s instead',
+                $productTypeName,
+                $editableProduct->getType()
+            )
+        );
+        $productId = $this->getSharedStorage()->get($productReference);
+        $product = new Product($productId);
+        Assert::assertEquals($productTypeName === ProductType::TYPE_VIRTUAL, (bool) $product->is_virtual);
+        // cache_is_pack is automatically updated by legacy code when removing all pack items so it's not worth testing it for now
+        // Assert::assertEquals($productTypeName === ProductType::TYPE_PACK, (bool) $product->cache_is_pack);
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php]: does it produce any error or what?
I don't understand why you say its not worth it?

File: tests/Resources/DatabaseDump.php [hunk 14]
```diff
@@ -158,9 +159,40 @@ public function restoreTable(string $table): void
...
+        $staticMethodCall = sprintf('%s::resetStaticCache', $className);
+        if (is_callable($staticMethodCall)) {
+            call_user_func($staticMethodCall);
+        }
+    }
+
+    private function getClassName(string $table): string
+    {
+        if ($table === 'lang') {
+            return 'Language';
```
Comment (zuk3975) [inline tests/Resources/DatabaseDump.php]: Would it be any better using ::class? (would get rid of "magic" strings at least) :thinking: 
```suggestion
            return Language::class;
```

**Review by zuk3975 — DISMISSED** [review]
just couple questions/suggestions

File: tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php (hunk 13 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php]: I didn't say anything I just moved some code 😅
I'll try if it works if I uncomment this line

Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php]: But I think it means we can't be sure that cache_is_ack will remain true as long as the product_type is Pack, because it is modified on product deletion and can be inconsistent sometimes, but I'm not sure fixing this is the PR's scope

Comment (zuk3975) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php]: could you clarify the comment once you check the behavior? :pray:

File: tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php [hunk 15]
```diff
@@ -379,8 +379,7 @@ private function assertProductType(string $productReference, string $productType
         $productId = $this->getSharedStorage()->get($productReference);
         $product = new Product($productId);
         Assert::assertEquals($productTypeName === ProductType::TYPE_VIRTUAL, (bool) $product->is_virtual);
-        // cache_is_pack is automatically updated by legacy code when removing all pack items so it's not worth testing it for now
-        // Assert::assertEquals($productTypeName === ProductType::TYPE_PACK, (bool) $product->cache_is_pack);
+        Assert::assertEquals($productTypeName === ProductType::TYPE_PACK, (bool) $product->cache_is_pack);
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php:382]: :+1:

**Review by zuk3975 — APPROVED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php (hunk 15 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/CommonProductFeatureContext.php:382]: Yeah it didn't work so I actually fixed it ^^

**Review by matks — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @mflasquin 

Thank you for your PR, I tested it and it works, as we can see here :

[Untitled_ Nov 30, 2022 12_02 PM (1).webm](https://user-images.githubusercontent.com/100699445/204780404-bc63c535-6742-4a96-a4a8-697e0a2c02b9.webm)

Even when we go in single shop the error still corrected ( about the issue on the image it's not because of your PR ) 

Thank you !

**Review by AureRita — APPROVED** [review]

**Comment by marsaldev** [comment]
thanks @mflasquin 💪!
