### PR TITLE
Order return states grid - Remove unnecessary filters merge

### LINKED ISSUE #20372: [BO LinkWidget Page] - Error displayed in page
#### Describe the bug
An error is displayed after opening page link widget
#### Expected behavior

Page correctly displayed

#### Steps to Reproduce

1. Go to 'BO > design > linkwidget'
2. See error

**Screenshots**
image

#### Additional information

* PrestaShop version: branch develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | No need to merge filters with request filters (removing the method fix visibility issue)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20372 
| How to test?  | /admin-dev/index.php/configure/shop/order-states/ <br>Check that filters work well in the 2 grids individually and combined

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20381)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php [hunk 1]
```diff
@@ -528,22 +528,4 @@ protected function getErrorMessageForException(Exception $e, array $messages)
             $e->getMessage()
         );
     }
-
-    /**
-     * @param Request $request
-     *
-     * @return Filters
-     */
-    protected function buildFiltersParamsByRequest(Request $request, Filters $filters)
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php:537]: BC break 🔴  😱 

Even if it's now useless, we cannot remove it as there might be modules who have controllers extending FrameworkBundleAdminController and using this.

However we can deprecate it if it's usless now

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1LYAHQV9yOrxeMsManjfRzWKsGenHTWXI/view?usp=sharing

Thanks!

**Comment by eternoendless** [comment]
Thank you @sowbiba
