### PR TITLE
Fix js error in console in multistore mode

### LINKED ISSUE #24057: JavaScript error in console using multistore
#### Describe the bug

Js error in console using multistore

#### Steps to Reproduce

1. Go to BO
2. Activate Multistore
3. Add a store
4. Configure new store
5. Open console browser
6. See error

**Screenshots**

Capture d’écran 2021-04-14 à 22 38 44

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  1.7.8.x
| Description?      | Keep perfect scrollbar from throwing an error when there is no element to add a scrollbar on it
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24057
| How to test?      | See issue #24057
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24456)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/components/multistore-dropdown.js [hunk 1]
```diff
@@ -40,7 +40,13 @@ const initMultistoreDropdown = () => {
     searchTerm: '__QUERY__',
   });
 
-  new PerfectScrollbar(MultistoreDropdownMap.scrollbar);
+  try {
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/components/multistore-dropdown.js]:
```suggestion
  if (MultistoreDropdownMap.scrollbar.length > 0) {
```

File: admin-dev/themes/new-theme/js/components/multistore-dropdown.js [hunk 2]
```diff
@@ -40,7 +40,13 @@ const initMultistoreDropdown = () => {
...
+    new PerfectScrollbar(MultistoreDropdownMap.scrollbar);
+  } catch (error) {
+    // there is no dropdown on which to add a scrollbar, stop silently
+    return;
+  }
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/components/multistore-dropdown.js]:
```suggestion
  }
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sarahdib & @matthieu-rolland
