### PR TITLE
Fix email not translated when installing a new language

### LINKED ISSUE #16273: When I install a new language, the generated emails are not translated on first generation
**Describe the bug**
When I install a new language, the generated emails are not translated on first generation

**To Reproduce**
1. Go to International > Translations
2. Install new language "Polish"
3. The mails are generated in `mails/pl` but they are in englisg
4. If you regenerate them manually after it works fine

**Solution**
Check the update package part of the code, seems like the translations are not available
Maybe the translations are cached on the start of the request, so when mails are generated the new one is not available, maybe we should clean the cache right after the new language is installed

**Additional information**
PrestaShop version: 1.7.6
PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | This fixes emails not being translated when installing a new language
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16273
| How to test?  | See #16273 ⚠ As it modifies quite a lot the language management, we should also test if mails are correctly generated during a fresh install (using something else than english) from web, and with CLI And check that the manual generation from the form also still works  ⚠

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16294)

### CODE REVIEW

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php [hunk 1]
```diff
@@ -108,25 +108,20 @@ public function handle(GenerateThemeMailTemplatesCommand $command)
...
     /**
-     * When installing a new Language, if it's a new one the Translator component can't manage it because its cache is
-     * already filled with the default one as fallback. We force the component to update its cache by adding a fake
-     * resource for this locale (this is the only way clean its local cache)
+     * When installing a new language, we must add the lang pack to the translator
      *
      * @param string $locale
      */
-    private function cleanTranslatorLocaleCache($locale)
+    private function addLanguageToTranslator(string $locale)
```
Comment (PierreRambaud) [inline src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php]: 5.6compatible, you can't do that :)
```suggestion
    private function addLanguageToTranslator($locale)
```

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php [hunk 2]
```diff
@@ -108,25 +108,20 @@ public function handle(GenerateThemeMailTemplatesCommand $command)
...
-        ) {
-            return;
+        $finder = Finder::create()
+            ->files()
+            ->name('*.' . $locale . '.xlf')
+            ->in(_PS_ROOT_DIR_ . '/app/Resources/translations/' . $locale);
+
+        foreach ($finder as $file) {
+            list($domain, $locale, $format) = explode('.', $file->getBasename(), 3);
+            $this->translator->addResource($format, $file, $locale, $domain);
```
Comment (eternoendless) [inline src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php]: You'll have to add this part as well in order to include translations from DB:

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Context.php#L451-L453

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php [hunk 3]
```diff
@@ -108,25 +108,21 @@ public function handle(GenerateThemeMailTemplatesCommand $command)
...
-     * resource for this locale (this is the only way clean its local cache)
+     * When installing a new language, we must add the lang pack to the translator
      *
-     * @param string $locale
+     * @param $locale
      */
-    private function cleanTranslatorLocaleCache($locale)
+    private function addLanguageToTranslator($locale)
     {
-        if (!method_exists($this->translator, 'addLoader')
```
Comment (jolelievre) [inline src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php:119]: Be careful, I remember this check was here for a reason because sometimes the injected translator was not `PrestaShopBundle\Translation\Translator` but `PrestaShopBundle\Translation\DataCollectorTranslator` which doesn't have the method `addRessource` nor `addLoader`
Although since there have been modifications on the translator (we had 2 different components) by @matthieu-rolland maybe this fixed the issue

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php [hunk 4]
```diff
@@ -108,25 +108,21 @@ public function handle(GenerateThemeMailTemplatesCommand $command)
     }
 
     /**
-     * When installing a new Language, if it's a new one the Translator component can't manage it because its cache is
-     * already filled with the default one as fallback. We force the component to update its cache by adding a fake
-     * resource for this locale (this is the only way clean its local cache)
+     * When installing a new language, we must add the lang pack to the translator
      *
-     * @param string $locale
+     * @param $locale
```
Comment (eternoendless) [inline src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php]: Don't remove the parameter signature here!
```suggestion
     * @param string $locale
```

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php [hunk 5]
```diff
@@ -108,25 +108,21 @@ public function handle(GenerateThemeMailTemplatesCommand $command)
...
      */
-    private function cleanTranslatorLocaleCache($locale)
+    private function addLanguageToTranslator($locale)
     {
-        if (!method_exists($this->translator, 'addLoader')
-            || !method_exists($this->translator, 'addResource')
-        ) {
-            return;
+        $finder = Finder::create()
```
Comment (eternoendless) [inline src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php]: You can avoid re-populating the translator if it's already done
```suggestion
		if (0 < count($this->translator->getCatalogue($locale)->all()) {
		    // avoid re-populating the translator
		    return;
		}

        $finder = Finder::create()
```

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php (hunk 3 above)
Comment (eternoendless) [reply src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php:119]: I think it's fixed but it should be tested.

FYI you get DataCollectorTranslator when you're in dev mode (it tracks translation hits for the Symfony profiler)

Comment (atomiix) [reply src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php:119]: Yeah, actually if I check if those methods exists it will return false because I got a `DataCollectorTranslator` **but** as `DataCollectorTranslator` is wrapping the `Translator` class, those methods are still available via the magic function `__call` that call the translator functions and make it works.

File: src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php (hunk 5 above)
Comment (atomiix) [reply src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php]: What if we're updating the lang pack? Don't we need to update the translator with the latest translations?

Comment (eternoendless) [reply src/Core/Domain/MailTemplate/CommandHandler/GenerateThemeMailTemplatesCommandHandler.php]: I see what you mean. But in case of the current language being updated, the resources have already been added to the translator. What happens to the translator if you add the same resource twice?

I have the feeling that we need to factorize this translator refresh functionality out of this class and have it shared with the one in Context.

File: classes/Context.php [hunk 6]
```diff
@@ -391,6 +392,16 @@ public function getTranslator($isInstaller = false)
         return $this->translator;
     }
 
+    /**
+     * @param string $locale
+     * @param string $notName
+     */
+    public function addLanguageToTranslator($locale, $notName = null)
```
Comment (jolelievre) [inline classes/Context.php]: It seems `$notName` is not really useful here (you don't use it in the `Language` class)

File: classes/Context.php [hunk 7]
```diff
@@ -433,22 +444,29 @@ public function getTranslatorFromLocale($locale)
         $translator->addLoader('db', $sqlTranslationLoader);
         $notName = $adminContext ? '^Shop*' : '^Admin*';
 
+        $this->doAddLanguageToTranslator($translator, $locale, $notName);
```
Comment (atomiix) [inline classes/Context.php]: @jolelievre I'm using `$notName` there ;)

File: classes/Context.php [hunk 8]
```diff
@@ -391,6 +392,15 @@ public function getTranslator($isInstaller = false)
         return $this->translator;
     }
 
+    /**
+     * @param string $locale
+     */
+    public function addLanguageToTranslator($locale)
```
Comment (eternoendless) [inline classes/Context.php]: You're adding responsibilities to Context that aren't theirs.

I think that you should extract a class `TranslationLanguageLoader` that would basically take over the responsibility for loading a language into an already instantiated translator.

It would work like this:

```
$isAdminContext = defined('_PS_ADMIN_DIR_');
$translator = Context::getContext()->getTranslator();
(new TranslatorLanguageLoader($isAdminContext))->loadLanguage($translator, $localeCode); // this returns void
```

This way, I don't think that you'd need to change the `getTranslator()` signature anymore.

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: classes/lang/DataLang.php [hunk 9]
```diff
@@ -46,22 +48,13 @@ public function __construct($locale)
...
-        if ($legacyLocale === $this->locale) {
-            $this->translator = $legacyTranslator;
-        } else {
-            $this->translator = new Translator(
-                $this->locale,
-                null,
-                _PS_CACHE_DIR_ . '/translations/' . $this->locale,
-                false
-            );
+        if ($translatorLocale !== $this->locale) {
```
Comment (jolelievre) [inline classes/lang/DataLang.php]: Waow! So fixing "only" this allows to manage the new language correctly?!

Comment (atomiix) [reply classes/lang/DataLang.php]: Yes... Took time to find it though 😅
I just nedd to follow @eternoendless's recommandation by adding a new `TranslatorLanguageLoader` and we should be good with that PR

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+
+    /**
+     * @param TranslatorInterface $translator
+     * @param string $locale
+     * @param Theme|null $theme
+     */
+    public function loadLanguage(TranslatorInterface $translator, $locale, Theme $theme = null)
+    {
+        if ($translator->getLocale() !== $locale) {
+            $translator->addLoader('xlf', new XliffFileLoader());
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php:65]: Maybe you check if the loader are already present? If this method is called several times you will have multiple instances of the same loader

Comment (atomiix) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php:65]: From what I saw, `addLoader()` is doing `$this->loaders[$format] = $loader;` and there was no public method to get the loaders. But if you think it's better to check I can do it :)
Wdyt?

File: classes/lang/DataLang.php [hunk 11]
```diff
@@ -46,31 +47,10 @@ public function __construct($locale)
...
-                ->files()
-                ->name('*.' . $this->locale . '.xlf')
-                ->in((_PS_ROOT_DIR_ . '/app/Resources/translations'));
-
-            foreach ($finder as $file) {
-                list($domain, $locale, $format) = explode('.', $file->getBasename(), 3);
-                $this->translator->addResource($format, $file, $locale, $domain);
-            }
-        }
+        (new TranslatorLanguageLoader($isAdminContext))->loadLanguage($this->translator, $this->locale);
```
Comment (eternoendless) [inline classes/lang/DataLang.php]: As discussed, the problem with this is that the contextual translator is set to the current user's language. Doing this will take over the user's language in unexpected ways.

For example, let's say the user is in French and he installs Polish. Doing this will switch the user's translator to Polish until the next page reload.

This means that whenever a translation operation needs to be performed in a locale that's different from the user's current one, a new translator must be instantiated in that language and passed along as a parameter.

So you just need to call `Context::getContext()->getTranslatorFromLocale($this->locale)`

File: classes/Context.php [hunk 12]
```diff
@@ -423,30 +422,8 @@ public function getTranslatorFromLocale($locale)
...
-        foreach ($finder as $file) {
-            list($domain, $locale, $format) = explode('.', $file->getBasename(), 3);
-
-            $translator->addResource($format, $file, $locale, $domain);
-            if (!$this->language instanceof PrestashopBundle\Install\Language) {
-                $translator->addResource('db', $domain . '.' . $locale . '.db', $locale, $domain);
-            }
-        }
+        $theme = $this->shop !== null ? $this->shop->theme : null;
+        (new TranslatorLanguageLoader($adminContext))->loadLanguage($translator, $locale, $theme);
```
Comment (eternoendless) [inline classes/Context.php]: Following my comment on DataLang, you may extract further logic from this method and create a static factory which would replace `TranslatorLanguageLoader` which would no longer be a necessary as a separate feature:

```php
$options = (new TranslationFactoryOptions())
  ->setIsBackoffice(true)
  ->setThemeName(null) // not needed when setIsBackoffice is true
  ->setCleanCache(true);
$newTranslator = TranslationFactory::buildTranslator($locale, $options);
```

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: classes/lang/DataLang.php (hunk 11 above)
Comment (eternoendless) [reply classes/lang/DataLang.php]: Nevermind, this is not necessary.

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php (hunk 10 above)
Comment (eternoendless) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php:65]: You can also only add loaders if the catalogue is empty for that locale.

File: classes/Context.php (hunk 12 above)
Comment (eternoendless) [reply classes/Context.php]: Nevermind, not necessary

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php [hunk 13]
```diff
@@ -0,0 +1,82 @@
...
+
+            $sqlTranslationLoader = new SqlTranslationLoader();
+            if (null !== $theme) {
+                $sqlTranslationLoader->setTheme($theme);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: I'm wondering since the loader depends on the theme, shouldn't the loader be also depends on it Something like:
```
$translator->addLoader('db-'.$theme, $sqlTranslationLoader);
```
Or are we sure that the theme stays unmodified during the whole process (for each calls)

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorInterface.php [hunk 14]
```diff
@@ -0,0 +1,42 @@
...
+
+use Symfony\Component\Translation\TranslatorInterface;
+
+/**
+ * Interface PrestaShopTranslatorInterface used by PrestaShop translators
+ */
+interface PrestaShopTranslatorInterface extends TranslatorInterface
+{
+    /**
+     * @param $locale
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorInterface.php]:
```suggestion
     * @param string $locale
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 15]
```diff
@@ -130,6 +130,16 @@ public function transChoice($id, $number, array $parameters = array(), $domain =
         return vsprintf(parent::transChoice($id, $number, array(), $domain, $locale), $parameters);
     }
 
+    /**
+     * @param $locale
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
     * @param string $locale
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 16]
```diff
@@ -130,6 +130,16 @@ public function transChoice($id, $number, array $parameters = array(), $domain =
...
+     *
+     * @return bool
+     */
+    public function isCatalogLoaded($locale)
+    {
+        return isset($this->catalogues[$locale]);
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Shouldn't it be better to check for emptyness?
```suggestion
        return !empty($this->catalogues[$locale]);
```

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php (hunk 13 above)
Comment (eternoendless) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: I don't think the theme is ever modified during runtime

**Review by eternoendless — COMMENTED** [review]
Just a couple comments!

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
Looks good to me, I'd like an approval from @jolelievre as well

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php (hunk 13 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: true!

**Review by jolelievre — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi,

Change of language on the install is KO with this PR.

Thanks ;)

**Comment by jolelievre** [comment]
> Hi,
> 
> Change of language on the install is KO with this PR.
> 
> Thanks ;)

Woow that's a problem :P What do you mean by "change of language" Is it in the back office or the front office. Can you provide more detailed actions to test it and maybe a screenshot or stacktrace of the thrown exception (if any)

File: classes/Context.php [hunk 17]
```diff
@@ -422,49 +422,15 @@ public function getTranslatorFromLocale($locale)
...
-        $translator->addLoader('db', $sqlTranslationLoader);
-        $notName = $adminContext ? '^Shop*' : '^Admin*';
-
-        $finder = Finder::create()
-            ->files()
-            ->name('*.' . $locale . '.xlf')
-            ->notName($notName)
-            ->in($this->getTranslationResourcesDirectories());
+        // only way to reset the catalogue
+        $translator->addLoader('Array', new ArrayLoader());
```
Comment (jolelievre) [inline classes/Context.php]: Maybe you should put this in the `TranslatorLanguageLoader::loadLanguage` method?

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php [hunk 18]
```diff
@@ -0,0 +1,105 @@
...
+     */
+    public function __construct($isAdminContext)
+    {
+        $this->isAdminContext = $isAdminContext;
+    }
+
+    /**
+     * @param PrestaShopTranslatorInterface $translator
+     * @param string $locale
+     * @param Theme|null $theme
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: The PHPDoc is not in the right order (or the function's parameters)

File: classes/Context.php [hunk 19]
```diff
@@ -422,49 +422,15 @@ public function getTranslatorFromLocale($locale)
...
-        foreach ($finder as $file) {
-            list($domain, $locale, $format) = explode('.', $file->getBasename(), 3);
-
-            $translator->addResource($format, $file, $locale, $domain);
-            if (!$this->language instanceof PrestashopBundle\Install\Language) {
-                $translator->addResource('db', $domain . '.' . $locale . '.db', $locale, $domain);
-            }
-        }
+        $adminContext = defined('_PS_ADMIN_DIR_');
+        $withDB = !$this->language instanceof PrestashopBundle\Install\Language;
```
Comment (jolelievre) [inline classes/Context.php:427]: I don't understand this check? In which case don't you want the database to be loaded? Maybe it's worth a comment here

Besides what other type can `$this->language` be? `\Language`? So it means you only disable the db loading during install process? Why?

File: classes/Context.php [hunk 20]
```diff
@@ -422,49 +422,15 @@ public function getTranslatorFromLocale($locale)
...
-        $notName = $adminContext ? '^Shop*' : '^Admin*';
-
-        $finder = Finder::create()
-            ->files()
-            ->name('*.' . $locale . '.xlf')
-            ->notName($notName)
-            ->in($this->getTranslationResourcesDirectories());
+        // only way to reset the catalogue
+        $translator->addLoader('Array', new ArrayLoader());
+        $translator->addResource('Array', [], $locale);
```
Comment (eternoendless) [inline classes/Context.php]: This could be better managed inside the translator itself:

```php
public function resetCatalogue($locale)
{
    unset($this->catalogues[$locale]);
}
```

Just add this in the Translator trait and in the PrestaShopTranslatorInterface

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php [hunk 21]
```diff
@@ -0,0 +1,105 @@
...
+     * @param bool $withDB
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: Arguments are not in the right order

Comment (eternoendless) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: Consider writing descriptions for public functions and arguments.

For example

```php
/**
 * Loads a language into a translator
 *
 * @param PrestaShopTranslatorInterface $translator Translator to modifiy
 * @param string $locale Locale code for the language to load
 * @param bool $withDB [default=true] Whether to load translations from the database or not
 * @param Theme|null $theme [default=false] Currently active theme (Front office only)
 */

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorInterface.php [hunk 22]
```diff
@@ -0,0 +1,47 @@
...
+{
+    /**
+     * @param string $locale
+     *
+     * @return bool
+     */
+    public function isCatalogLoaded($locale);
+
+    /**
+     * @param $locale
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorInterface.php]:
```suggestion
     * @param string $locale
```

File: classes/Context.php (hunk 19 above)
Comment (atomiix) [reply classes/Context.php:427]: We don't need to load DB translations when `$this->language` in an instance of `PrestashopBundle\Install\Language` because that's only translations for the web installer and when we load the installer language we didn't configured the DB yet...

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 23]
```diff
@@ -130,6 +130,24 @@ public function transChoice($id, $number, array $parameters = array(), $domain =
...
+     *
+     * @return bool
+     */
+    public function isCatalogLoaded($locale)
+    {
+        return !empty($this->catalogues[$locale]);
+    }
+
+    /**
+     * @param $locale
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
     * @param string $locale
```

**Review by matks — APPROVED** [review]

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php [hunk 24]
```diff
@@ -0,0 +1,107 @@
...
+    }
+
+    /**
+     * @param Theme|null $theme
+     *
+     * @return array
+     */
+    protected function getTranslationResourcesDirectories(Theme $theme = null)
+    {
+        $locations = [_PS_ROOT_DIR_ . '/app/Resources/translations'];
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php]: This one can be a const (I mean `_PS_ROOT_DIR_ . '/app/Resources/translations'`)

File: classes/Context.php (hunk 19 above)
Comment (jolelievre) [reply classes/Context.php:427]: oooookay, this makes sense but maybe you can add a comment explaining that, because it's not that intuitive at first ^^

**Comment by Robin-Fischer-PS** [comment]
Hi,

I've a new bug : 

When I import a localization pack of a country with several official languages (for example, Belgium), only one language has the generated emails in the correct language. The other languages are in English.

**After manual regeneration (in Design > Email), the emails are still in English.**

Some details for my Belgium example : 

If only English is installed, French will be OK, German and Dutch will be NOK.
If English and French are already installed (and OK), German will also be OK, only Dutch will be NOK.

In 1752, it's OK.

**Comment by matks** [comment]
> Hi,
> 
> I've a new bug :
> 
> When I import a localization pack of a country with several official languages (for example, Belgium), only one language has the generated emails in the correct language. The other languages are in English.
> 
> **After manual regeneration (in Design > Email), the emails are still in English.**
> 
> Some details for my Belgium example :
> 
> If only English is installed, French will be OK, German and Dutch will be NOK.
> If English and French are already installed (and OK), German will also be OK, only Dutch will be NOK.
> 
> In 1752, it's OK.

So, if I understand correctly, we have 2 reproductable failing scenarios (at least):

## Scenario 1

1. I install a shop in English. I download a localization pack for Belgium. This pack contains French, Dutch, and German.
2. I generate the mails for languages French, Dutch, German.
3. French, Dutch, German mails mails are generated but are not translated. They are in English.

## Scenario 2

1. I install a shop in French. This means 2 languages are available on my shop: French and English. I make sure both are activated.
2. I download a localization pack for Belgium. This pack contains French, Dutch, and German.
3. I generate the mails for languages French, Dutch, German.
4. French, and German mails are generated and translated. But Dutch mails are in English.

Is that correct @Robin-Fischer-PS ?

**Comment by Robin-Fischer-PS** [comment]
Not exactly @matks 

Scenario 2 is OK. For Scenario 1, step 3 is : 
French mails are generated and translated. Dutch, German mails mails are generated too but are not translated. They are in English.

**Comment by Robin-Fischer-PS** [comment]
Hi,

New bug. When I do a fresh install with a country with 3 or more official languages (Belgium, Switzerland), it is KO.

pr16294 fail install

**Comment by PierreRambaud** [comment]
@Robin-Fischer-PS as defined in the documentation https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/
The minimum memory_limit is 256M. Could you please increase the value and retry?

**Comment by Robin-Fischer-PS** [comment]
With memory_limit = 256M, it's OK :wink:

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@atomiix Since this PR has been unscoped and we have a few more time to fix it, could you handle Pierre's feedback https://github.com/PrestaShop/PrestaShop/pull/16294#discussion_r349204994 ? 😉

File: classes/Context.php (hunk 19 above)
Comment (matks) [reply classes/Context.php:427]: 🆙

File: composer.json [hunk 25]
```diff
@@ -182,7 +182,7 @@
         ],
         "phpunit-admin": [
             "@composer create-test-db",
-            "@php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit-admin.xml"
+            "php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit-admin.xml"
```
Comment (matks) [inline composer.json]: 👍

**Review by matks — DISMISSED** [review]

File: composer.json (hunk 25 above)
Comment (PierreRambaud) [reply composer.json]: NOPE NOPE AND NOPE :scream:

Comment (PierreRambaud) [inline composer.json]: NOPE NOPE AND NOPE !!!! :scream:

**Review by PierreRambaud — DISMISSED** [review]
Change composer.json

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

It gives me an immense joy and great satisfaction to announce you that this PR is QA Approved :heavy_check_mark: !

Congrats, now you can relax and enjoy the simple pleasures of life, like working on cart rules :trollface: 

(FYI : I tested with a 128MB configuration : It works fine on install with 3 languages)

Thanks !
