### PR TITLE
Fix default value for Jquery colorpicker

### LINKED ISSUE #27249: BO - The color picker by default is black
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The color picker by default is black 
image

In the PS1782 => ok
image

Related to this PR: https://github.com/PrestaShop/PrestaShop/pull/27114

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > Catalog > Attributes & Features 
2. Click on "Add new value" to the Color "Attribute group"
3. See the color field by default is black

image

1. Enable Multistore context
2. Create a new shop
3. See the color field by default is black

 image

### PrestaShop version(s) where the bug happened

1.7.8.3build1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | 2 fixes done : <ul><li>Use element in forEach callback instead of `this` (which refer to parent component)</li><li>Use `$t.is('input')` instead of `$t[0].nodeName` to test HTML element type</li></ul>
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27249
| How to test?      | Look at issue description
| Possible impacts? | Check colorpickers inside BO, including when multistore is enabled<br>Regression was previously introduced by https://github.com/PrestaShop/PrestaShop/pull/27114 : please test that issue expected behaviour too

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27330)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
I'm not sure it's a good idea to modify code that was copied as external dependency Especially since you use ES6 code (let, const, ...) in a ES5 script that is not rebuilt by esbuild

But I may be wrong, maybe @NeOMakinG should confirm this?

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Please revert every `var` changed, just add the fix for the issue

I really think that except if you're using a preprocessor, don't use ES6+ features

Even if it's pretty supported now, we never know, and it's not transpiled to syntax < ES5 syntax

Also, keep in mind that this is a dependency, try to add less differences as possible, the fix will be enough

**Review by NeOMakinG — DISMISSED** [review]

File: js/jquery/plugins/jquery.colorpicker.js [hunk 1]
```diff
@@ -53,8 +53,8 @@
 
     // update the colors of the newly created inputs
     $(document).ready(function() {
-      inputs.forEach(function() {
-        $.fn.mColorPicker.setTextColor($(this));
+      inputs.forEach(function(input) {
+        $.fn.mColorPicker.setTextColor(input);
```
Comment (saulaski) [inline js/jquery/plugins/jquery.colorpicker.js:57]: Warning: argument passed to `setTextColor(element)` method is treated as a jQuery object.
Here the input argument should be wrapped first : 
```suggestion
        $.fn.mColorPicker.setTextColor($(input));
```
Or even better, just wrap the argument of any type in `setTextColor(element)` method : 
```
        $.fn.mColorPicker.setTextColor = function(element) {
          element = $(element);
          // ...
```

File: js/jquery/plugins/jquery.colorpicker.js [hunk 2]
```diff
@@ -118,8 +118,7 @@
   };
 
   $.fn.mColorPicker.drawPickerTriggers = function ($t) {
-
-    if ($t[0].nodeName.toLowerCase() != 'input') return false;
+    if ($t.prop('tagName').toLowerCase() != 'input') return false;
```
Comment (saulaski) [inline js/jquery/plugins/jquery.colorpicker.js]:
```suggestion
    if (!$t.is('input')) return false;
```

File: js/jquery/plugins/jquery.colorpicker.js (hunk 1 above)
Comment (saulaski) [reply js/jquery/plugins/jquery.colorpicker.js:57]: Forget my warning please : items in `inputs` array are jQuery objects already.

**Review by NeOMakinG — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @sowbiba,

It is ok :heavy_check_mark: 
image
image

https://user-images.githubusercontent.com/16067358/150347344-50d28ede-c873-45ab-9096-7eec8e48b31a.mp4

Thanks!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
WAIT FOR 1783 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sowbiba & @khouloudbelguith
