### PR TITLE
Fix config values not properly fetched in multistore context

### LINKED ISSUE #25680: BO - SEO and Webservice Parameters pages not saved in Multistore
#### Describe the bug

When in Multistore, in shop or group of shops context, the parameters are not saved on both SEO & URLS and Webservice pages.

#### Expected behavior

Parameters should be saved in every context in Multistore on these pages.

#### Steps to Reproduce

1. Go to Shop Parameters > Traffic & SEO > SEO & URLs or to Advanced Parameters > Webservice pages
2. Change any parameter (for example : "Accented URL" or "Route to products" / "Enable PrestaShop's webservice"), save
3. Click on the menu to to reload the page (without hitting F5 key)
4. Check the modified parameters : The changes were not saved.

**Screenshots**

https://drive.google.com/file/d/1seW68XZPCbuBoc9gnexE9SKOlwlAHvj2/view

#### Additional information

* PrestaShop version: 1.7.8.0 RC1 B3
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | When there no ShopConstraint is specified in the `get` method, we rely on current context values.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | yes
| Fixed ticket?     | Fixes #25680
| How to test?      | see issue #25680
| Possible impacts? | All config forms in multistore context, but side effects should be the same everywhere, not on a form in particular. 

### BC break

- The constructor of `ShopConstraint` class is made protected in this PR, you must use the public static method to build `ShopConstraint` objects.

### Deprecations: 

- Not specifying a `ShopConstraint` in the `get` method of `PrestaShop\PrestaShop\Adapter\Configuration` triggers a depreciation notice.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25690)

### CODE REVIEW

**Comment by eternoendless** [comment]
This needs to be rebased into `1.7.8.0-build`

**Review by eternoendless — COMMENTED** [review]
You need to add the deprecation message in ::set() as well

```php
        if ($this->shop instanceof Shop && null === $shopConstraint) {
            $shopGroupId = $this->shop->id_shop_group;
            $shopId = $this->shop->id;
        } else {
			// * <-------------- deprecation goes here
            $shopId = $this->getShopId($shopConstraint);
            $shopGroupId = $this->getShopGroupId($shopConstraint);
        }
```

**Comment by eternoendless** [comment]
And in `has()` as well

**Comment by matthieu-rolland** [comment]
> And in `has()` as well

yes, with @PierreRambaud we decided to add a private method that builds a `ShopConstraint` if needed and do the trigger in it. The PR is updated in this regard.

**Review by PierreRambaud — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

File: src/Adapter/Configuration.php [hunk 1]
```diff
@@ -151,14 +155,11 @@ public function get($key, $default = null, ShopConstraint $shopConstraint = null
...
     {
-        // By default, set a piece of configuration for all available shops and shop groups
-        $shopGroupId = null;
-        $shopId = null;
-
         if ($this->shop instanceof Shop && null === $shopConstraint) {
             $shopGroupId = $this->shop->id_shop_group;
             $shopId = $this->shop->id;
         } else {
+            $shopConstraint = null === $shopConstraint ? $this->buildShopConstraintFromContext() : $shopConstraint;
```
Comment (eternoendless) [inline src/Adapter/Configuration.php:162]:
```suggestion
            $shopConstraint = $shopConstraint ?: $this->buildShopConstraintFromContext();
```

Comment (eternoendless) [inline src/Adapter/Configuration.php]:
```suggestion
            $shopConstraint = $shopConstraint ?: $this->buildShopConstraintFromContext();
```

File: tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php [hunk 2]
```diff
@@ -32,9 +32,11 @@
 use Language;
 use PrestaShopBundle\Install\DatabaseDump;
 use PrestaShopBundle\Install\Install;
+use Shop;
 use Tests\Resources\ResourceResetter;
 use Tab;
 
+
```
Comment (eternoendless) [inline tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php]:
```suggestion
```

File: src/Adapter/Configuration.php [hunk 3]
```diff
@@ -395,4 +400,20 @@ public function deleteFromContext(string $key, ShopConstraint $shopConstraint):
...
         );
     }
+
+    /**
+     * @return ShopConstraint
+     */
+    private function buildShopConstraintFromContext(): ShopConstraint
+    {
+        @trigger_error(
+            'Not specifying the optional ShopConstraint parameter is deprecated since version 1.7.8.0',
```
Comment (jolelievre) [inline src/Adapter/Configuration.php:417]: That's the only thing I am troubled with in this PR @eternoendless 

We discussed that in the next 8.0 version we would probably got rid of this extra parameter and instead the `Configuration` would become stateful (one configuration is fetched for a specific ShopConstraint), so this future idea seems more stable (for once having a stateful shop context, but specific to one service seems like the cleaner approach)

However this deprecation message goes against this idea since it implies that every future calls of `Configuration::get` will have to provide this extra parameter, meaning we also have to provide a default value everywhere...

TLDR: I'm not against this deprecation message but IMHO it should rather be a message stating that this parameter is gonna be removed in the next version, not become mandatory

File: tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php [hunk 4]
```diff
@@ -49,6 +51,7 @@ public static function createTestDB()
         require_once __DIR__ . '/../../../install-dev/init.php';
 
         $install = new Install();
+        Shop::setContext(Shop::CONTEXT_SHOP, 1);
```
Comment (jolelievre) [inline tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php]: This doesn't seem to be enough the integration tests are still failing

Comment (matthieu-rolland) [reply tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php]: and phpunit as well it seems

File: src/Adapter/Configuration.php (hunk 3 above)
Comment (eternoendless) [reply src/Adapter/Configuration.php:417]: The new Configuration will belong to the Core namespace, this `Adapter\Configuration` will most likely delegate to `Core\ConfigurationRepository` to get the appropriate `Core\Configuration`

File: src/Adapter/Configuration.php [hunk 5]
```diff
@@ -395,4 +400,20 @@ public function deleteFromContext(string $key, ShopConstraint $shopConstraint):
...
+            E_USER_DEPRECATED
+        );
+
+        return new ShopConstraint(
+            Shop::getContextShopID(),
+            Shop::getContextShopGroupID()
```
Comment (PierreRambaud) [inline src/Adapter/Configuration.php]:
```suggestion
            Shop::getContextShopID() ?: null,
            Shop::getContextShopGroupID() ?: null
```

Should fix tests

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php [hunk 6]
```diff
@@ -96,8 +96,8 @@ public static function allShops(): self
      */
     public function __construct(?int $shopId, ?int $shopGroupId, bool $strict = false)
     {
-        $this->shopId = null !== $shopId ? new ShopId($shopId) : null;
-        $this->shopGroupId = null !== $shopGroupId ? new ShopGroupId($shopGroupId) : null;
+        $this->shopId = !empty($shopId)  ? new ShopId($shopId) : null;
+        $this->shopGroupId = !empty($shopGroupId)  ? new ShopGroupId($shopGroupId) : null;
```
Comment (matthieu-rolland) [inline src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: Here I use `!empty()` because `$shopId` and `$shopGroupId` are either null or integer, and it is considered empty if value is null or not greater than zero.

Comment (matthieu-rolland) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: I will revert this and refactor usages of ShopConstraint and the configuration class instead

Comment (PierreRambaud) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: https://github.com/PrestaShop/PrestaShop/pull/25690#discussion_r695604349 
It should do the trick without having the use empty here :)

Comment (PierreRambaud) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: (You shouldn't have to check if data is empty, but only if it higher than 0), the parameter is null or an integer

Comment (matthieu-rolland) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: we decided not to allow the zero value, so that it breaks in `ShopId` or `ShopGroupId`

File: src/Adapter/Configuration.php [hunk 7]
```diff
@@ -100,6 +100,10 @@ public function add(array $parameters = [])
      */
     public function get($key, $default = null, ShopConstraint $shopConstraint = null)
     {
+        if (null === $shopConstraint) {
```
Comment (eternoendless) [inline src/Adapter/Configuration.php:105]: Perhaps a little comment in the Phpdoc above wouldn't be out of place

File: src/Adapter/Configuration.php [hunk 8]
```diff
@@ -151,14 +156,11 @@ public function get($key, $default = null, ShopConstraint $shopConstraint = null
...
     {
-        // By default, set a piece of configuration for all available shops and shop groups
-        $shopGroupId = null;
-        $shopId = null;
-
         if ($this->shop instanceof Shop && null === $shopConstraint) {
             $shopGroupId = $this->shop->id_shop_group;
             $shopId = $this->shop->id;
         } else {
+            $shopConstraint = $shopConstraint ?: $this->buildShopConstraintFromContext();
```
Comment (eternoendless) [inline src/Adapter/Configuration.php:165]: Again, a little note on the parameter to help people understand

File: src/Adapter/Configuration.php [hunk 9]
```diff
@@ -188,6 +190,10 @@ public function set($key, $value, ShopConstraint $shopConstraint = null, array $
      */
     public function has($key, ShopConstraint $shopConstraint = null)
     {
+        if (null === $shopConstraint) {
```
Comment (eternoendless) [inline src/Adapter/Configuration.php:196]: Same comment about the note on the parameter

File: tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php [hunk 10]
```diff
@@ -32,6 +32,7 @@
 use Language;
 use PrestaShopBundle\Install\DatabaseDump;
 use PrestaShopBundle\Install\Install;
+use Shop;
```
Comment (eternoendless) [inline tests-legacy/PrestaShopBundle/Utils/DatabaseCreator.php]: It looks like this is not used

File: src/Adapter/Configuration.php [hunk 11]
```diff
@@ -118,19 +123,20 @@ public function get($key, $default = null, ShopConstraint $shopConstraint = null
             return $this->getLocalized($key, $shopId, $shopGroupId);
         }
 
+        if ($isStrict) {
```
Comment (eternoendless) [inline src/Adapter/Configuration.php]: Now that $shopConstraint is never null, we don't need the `$this->isStrict()` method anymore

File: src/Adapter/Configuration.php [hunk 12]
```diff
@@ -118,19 +123,20 @@ public function get($key, $default = null, ShopConstraint $shopConstraint = null
...
-        $hasKey = ConfigurationLegacy::hasKey($key, null, null, $shopId);
-        if ($hasKey || $isStrict) {
-            return $hasKey ? ConfigurationLegacy::get($key, null, null, $shopId) : null;
+        if (ConfigurationLegacy::hasKey($key, null, null, $shopId)) {
+            return ConfigurationLegacy::get($key, null, null, $shopId);
         }
 
-        $hasKey = ConfigurationLegacy::hasKey($key, null, $shopGroupId);
-        if ($hasKey) {
+        if (ConfigurationLegacy::hasKey($key, null, $shopGroupId)) {
```
Comment (eternoendless) [inline src/Adapter/Configuration.php]: You can delay the call to `$this->getShopGroupId()` in line 113 to here. That said, it makes no sense calling `::get()` unless `$shopGroupId` is different from null.

File: src/Adapter/Configuration.php [hunk 13]
```diff
@@ -118,19 +123,20 @@ public function get($key, $default = null, ShopConstraint $shopConstraint = null
...
 
+        if ($isStrict) {
+            return $this->getStrictValue($key, $shopConstraint);
+        }
+
         // Since hasKey doesn't check manage the fallback shop > shop group > global, we handle it manually
-        $hasKey = ConfigurationLegacy::hasKey($key, null, null, $shopId);
-        if ($hasKey || $isStrict) {
-            return $hasKey ? ConfigurationLegacy::get($key, null, null, $shopId) : null;
+        if (ConfigurationLegacy::hasKey($key, null, null, $shopId)) {
```
Comment (eternoendless) [inline src/Adapter/Configuration.php]: It makes no sense calling this with a null `$shopId` right? (eg. shopgroup or allshops context)

File: classes/shop/Shop.php [hunk 14]
```diff
@@ -976,7 +976,7 @@ public static function setContext($type, $id = null)
                 break;
             case self::CONTEXT_GROUP:
                 self::$context_id_shop = null;
-                self::$context_id_shop_group = (int) $id;
+                self::$context_id_shop_group = $id;
```
Comment (eternoendless) [inline classes/shop/Shop.php]: Not a good idea, this is an error

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php [hunk 15]
```diff
@@ -53,38 +53,40 @@ class ShopConstraint
...
-    public static function shopGroup(int $shopGroupId): self
+    public static function shopGroup(int $shopGroupId, bool $isStrict = false): self
     {
-        return new static(null, $shopGroupId, false);
+        return new static(null, $shopGroupId, $isStrict);
     }
 
     /**
-     * Constraint to get configuration for all shops (the global value)
+     * @param bool $isStrict
```
Comment (eternoendless) [inline src/Core/Domain/Shop/ValueObject/ShopConstraint.php:85]: Reintroduce the missing comment
```suggestion
     * Constraint to get configuration for all shops (the global value)
     *
     * @param bool $isStrict
```

File: src/Adapter/Configuration.php [hunk 16]
```diff
@@ -395,4 +395,51 @@ public function deleteFromContext(string $key, ShopConstraint $shopConstraint):
...
+            return ShopConstraint::shopGroup(Shop::getContextShopGroupID());
+        }
+
+        return ShopConstraint::allShops();
+    }
+
+    /**
+     * @param string $key
+     * @param ShopConstraint $shopConstraint
+     * @param $default
```
Comment (eternoendless) [inline src/Adapter/Configuration.php]:
```suggestion
```

File: src/Adapter/Configuration.php [hunk 17]
```diff
@@ -345,39 +352,32 @@ private function getLocalized($key, ?int $shopId = null, ?int $shopGroupId = nul
...
     {
-        return null !== $shopConstraint && null !== $shopConstraint->getShopGroupId()
-            ? $shopConstraint->getShopGroupId()->getValue()
-            : null
-        ;
-    }
+        if (null !== $shopConstraint->getShopGroupId()) {
+            return $shopConstraint->getShopGroupId()->getValue();
+        } elseif (null !== $shopConstraint->getShopId()) {
+            return (int) Shop::getGroupFromShop((int) $shopConstraint->getShopId()->getValue(), true);
```
Comment (eternoendless) [inline src/Adapter/Configuration.php]: This function can return `false` if the shopGroup is not found. Shouldn't this throw an exception in that case instead of casting it to 0? Because there is no group 0 (the default is 1).

**Comment by Progi1984** [comment]
@matthieu-rolland Is this PR fixing issue #25674 ?

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland Is this PR fixing issue #25674 ?

nope

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php [hunk 18]
```diff
@@ -94,7 +98,7 @@ public static function allShops(): self
      *
      * @throws ShopException
      */
-    public function __construct(?int $shopId, ?int $shopGroupId, bool $strict = false)
+    private function __construct(?int $shopId, ?int $shopGroupId, bool $strict = false)
```
Comment (atomiix) [inline src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: I think this is a BC Break

Comment (matthieu-rolland) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: yes, I add it in the PR description 👍

File: src/Adapter/Configuration.php [hunk 19]
```diff
@@ -182,22 +186,26 @@ public function set($key, $value, ShopConstraint $shopConstraint = null, array $
...
-        $isStrict = $this->isStrict($shopConstraint);
 
         if (ConfigurationLegacy::isLangKey($key)) {
-            return $this->hasMultilang($key, $shopId, $shopGroupId, $isStrict);
+            return $this->hasMultilang($key, $shopId, $shopGroupId, $shopConstraint->isStrict());
         }
 
         $hasKey = ConfigurationLegacy::hasKey($key, null, $shopGroupId, $shopId);
-        if ($hasKey || $isStrict) {
+        if ($hasKey || $shopConstraint->isStrict()) {
```
Comment (jolelievre) [inline src/Adapter/Configuration.php]: I believe the strict check is not correctly handled here, you need to check `null !== $shopId` and `null !== $shopGroupId` like you did in `getStrictValue`

The fact that `isStrict` is not checked in the second check for group is a hint that something is missing here

Comment (jolelievre) [reply src/Adapter/Configuration.php]: Example:
- config is set for Group
- config is not set for Shop
- `has` function is called with specific groupId and isStrict true
- $hasKey == false, but $isStrict is true so false is returned
- the method returns that group has no value, whereas it's the shop which has none

File: src/Adapter/Configuration.php [hunk 20]
```diff
@@ -345,39 +353,43 @@ private function getLocalized($key, ?int $shopId = null, ?int $shopGroupId = nul
...
-        return null !== $shopConstraint && null !== $shopConstraint->getShopGroupId()
-            ? $shopConstraint->getShopGroupId()->getValue()
-            : null
-        ;
-    }
+        if (null !== $shopConstraint->getShopGroupId()) {
+            return $shopConstraint->getShopGroupId()->getValue();
+        } elseif (null !== $shopConstraint->getShopId()) {
+            $shopGroupId = Shop::getGroupFromShop((int) $shopConstraint->getShopId()->getValue(), true);
+            // $shopGroupId can must not be false, it would mean that the shop group was not found for the given shop
```
Comment (jolelievre) [inline src/Adapter/Configuration.php]:
```suggestion
            // $shopGroupId can not be false, it would mean that the shop group was not found for the given shop
```

File: src/Adapter/Configuration.php [hunk 21]
```diff
@@ -345,39 +353,43 @@ private function getLocalized($key, ?int $shopId = null, ?int $shopGroupId = nul
...
+            if ($shopGroupId === false) {
+                throw new ShopException(
+                    sprintf(
+                        'Shop group with id %s was not found.',
+                        $shopGroupId
```
Comment (jolelievre) [inline src/Adapter/Configuration.php]: `$shopGroupId` is always false in this case, so the exception message won't bring much info
```suggestion
                        'Shop group was not found for the shop with id %d.',
                        $shopConstraint->getShopId()->getValue()
```

File: src/Adapter/Configuration.php [hunk 22]
```diff
@@ -395,4 +407,50 @@ public function deleteFromContext(string $key, ShopConstraint $shopConstraint):
             !empty($shopId) ? $shopId->getValue() : null
         );
     }
+
+    /**
+     * @return ShopConstraint
+     */
+    private function buildShopConstraintFromContext(): ShopConstraint
+    {
+        @trigger_error(
```
Comment (jolelievre) [inline src/Adapter/Configuration.php:416]: I still think this deprecate notice makes no sense because:
- almost nowhere in the Core code do we respect this message and provide a shopConstraint parameter, thus lots of deprecation messages will be triggered by our own code... (especially when the service is used in the service definitions)
- in future version we plan on simplifying this interface by removing this extra parameter, instead the Configuration would be stateful and depend on the context it was created for (single shop, global, group shop), although we are still not sure exactly how we will do this

So neither the present nor the future actually match this notice... But since this was suggested by Pablo I'm guessing we will leave it regardless because we can't wait for his return to merge this..

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 23]
```diff
@@ -0,0 +1,230 @@
...
+    }
+
+    public function cleanDb(): void
+    {
+        //remove newly created shop
+        $shop = $this->entityManager->getRepository(Shop::class)->findOneBy(['name' => 'test_shop_2']);
+        $this->entityManager->remove($shop);
+        $this->entityManager->flush();
+        // remove multistore feature enabling configuration
+        $this->configuration->remove('PS_MULTISHOP_FEATURE_ACTIVE');
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
        $this->configuration->set('PS_MULTISHOP_FEATURE_ACTIVE', 0);
```

The configuration must not be removed, just reset to 0

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 24]
```diff
@@ -0,0 +1,230 @@
...
+    public function testGet(array $setParams, array $getParams, $expectedResult, bool $isLastTest): void
+    {
+        foreach ($setParams as $values) {
+            $this->configuration->set($values['key'], $values['value'], $values['shopConstraint']);
+        }
+        $result = $this->configuration->get($getParams['key'], $getParams['default'], $getParams['shopConstraint']);
+
+        $this->assertEquals($expectedResult, $result);
+
+        if ($isLastTest) {
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]: This complexifies your test method You shouldn't provide this boolean in your test data, it makes the maintenance of this test class more complicated (if someone wants to add another data he might wrongly copy the `true` parameter at the end)

Indeed you should rely on native methods from PHPUnit to handle this, like `tearDown` if you want to clean the DB after each test (but then, you will also have to init it before each test)

Or alternatively, if you want to clean only once after all the tests are done you can use `tearDownAfterClass` but since it's a static class you can't rely on `$this` so you will have to call `self::$kernel->getContainer()->get` to get the necessary services

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 25]
```diff
@@ -0,0 +1,230 @@
...
+                    'shopConstraint' => ShopConstraint::allShops(),
+                ],
+                'value_test_1',
+                false,
+            ],
+            // set and get a value for shop 2
+            [
+                [
+                    [
+                        'key' => 'key_test_1',
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]: Be careful you are using the same key as in the first test here, meaning both tests are colliding with each other and/or dependent with each other

Unless this is on purpose to make sure the previously set variable in global context has now been overridden, but then you should allow multiple "get check" per test so that:
- in first test you check value for all shops, single shop, group shop they are all identical
- in second test you check the three values again but they are not equal any more

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 26]
```diff
@@ -0,0 +1,230 @@
...
+                ],
+                [
+                    'key' => 'key_test_1',
+                    'default' => false,
+                    'shopConstraint' => ShopConstraint::shop(2),
+                ],
+                'value_test_1',
+                false,
+            ],
+            // try to get a non existing value for shop 2, get default value instead
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]: You should have the same test for allShops as well

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 27]
```diff
@@ -0,0 +1,230 @@
...
+                ],
+                [
+                    'key' => 'parent_group_key_2',
+                    'default' => false,
+                    'shopConstraint' => ShopConstraint::shop(2),
+                ],
+                'parent_group_value',
+                false,
+            ],
+            // try getting a non existing value for shop 2, with is strict = true => should not inherit from parent group
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]: You also need to test getting a group value with strict
And you should set the value in the global context or the strict value has less interest

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 28]
```diff
@@ -0,0 +1,230 @@
...
+
+    /**
+     * @param array $setParams
+     * @param array $getParams
+     * @param $expectedResult
+     * @param bool $isLastTest
+     *
+     * @dataProvider getProvider
+     */
+    public function testGet(array $setParams, array $getParams, $expectedResult, bool $isLastTest): void
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]: You also need to test the `has` method (in a different test)

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 29]
```diff
@@ -0,0 +1,230 @@
...
+
+        if ($isLastTest) {
+            $this->cleanDb();
+        }
+    }
+
+    /**
+     * @return array[]
+     */
+    public function getProvider(): array
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]: The way the provider and the test data are built is a bit confusing and hard to understand
Maybe using some `yield` to separate each test clearly would make it more readable

And you could split the tests with `isStrict` in a dedicated test function (with its dedicated provider as well)

File: tests/TestCase/ContextStateTestCase.php [hunk 30]
```diff
@@ -0,0 +1,71 @@
...
+abstract class ContextStateTestCase extends TestCase
+{
+    /**
+     * @param array $contextFields
+     *
+     * @return MockObject|Context
+     */
+    protected function createContextMock(array $contextFields)
+    {
+        $contextMock = $this->getMockBuilder(\Context::class)
```
Comment (jolelievre) [inline tests/TestCase/ContextStateTestCase.php]: Can you add a `use` statement for `Context` please?

File: tests/Integration/Adapter/ConfigurationTest.php (hunk 24 above)
Comment (matthieu-rolland) [reply tests/Integration/Adapter/ConfigurationTest.php]: I tried using `tearDownAfterClass` but I  have two issues:

1/ Strangely it seems like the function is executed more than once for this test file (I debugged it)
2/ `self::$kernel->getContainer()` doesn't give me the container, or at least not each time

For now I just removed the `cleanDb` method, it doesn't break the test suite, but it's annoying

File: src/Adapter/Shop/Context.php [hunk 31]
```diff
@@ -228,4 +229,20 @@ public function getShopName()
...
+
+    /**
+     * @param bool $strict
+     *
+     * @return ShopConstraint
+     */
+    public function getShopConstraint(bool $strict = false): ShopConstraint
+    {
+        if ($this->isShopContext()) {
+            return ShopConstraint::shop($this->getContextShopID(), $strict);
```
Comment (jolelievre) [inline src/Adapter/Shop/Context.php]: Just a comment, but maybe it would be less risky to type to `int` here I'm not sure the shop context is always correctly filled with a strict int, and it doesn't handle the casting internally either, it just returns the value from legacy Shop class
And legacy code is rarely very strict ^^

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 32]
```diff
@@ -0,0 +1,415 @@
...
+    }
+
+    /**
+     * @param array $setParams
+     * @param array $getParams
+     * @param $expectedResult
+     *
+     * @dataProvider getWithStrictParameterProvider
+     */
+    public function testGetWithSrictParameter(array $setParams, array $getParams, $expectedResult)
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
    public function testGetWithSrictParameter(array $setParams, array $getParams, $expectedResult): void
```
Not mandatory

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 33]
```diff
@@ -0,0 +1,415 @@
...
+    {
+        if (!empty($setParams)) {
+            $this->configuration->set($setParams['key'], $setParams['value'], $setParams['shopConstraint']);
+        }
+        $result = $this->configuration->has($getParams['key'], $getParams['shopConstraint']);
+
+        $this->assertEquals($expectedResult, $result);
+    }
+
+    public function hasProvider(): Generator
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
    public function hasProvider(): iterable
```

Just a small trick I got from @Progi1984 you can use `iterable` for providers relying on `yield` It's quite handy since you don't need a `use` statement unlike with `Generator`

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 34]
```diff
@@ -0,0 +1,415 @@
...
+        // test in single shop context with $isStrict = true, when value is set for parent group
+        yield [
+            [
+                'key' => 'has_key_test_7',
+                'value' => 'has_value_test_7',
+                'shopConstraint' => ShopConstraint::shopGroup(1),
+            ],
+            [
+                'key' => 'has_key_test_7',
+                'shopConstraint' => ShopConstraint::shopGroup(2, true),
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
                'shopConstraint' => ShopConstraint::shop(2, true),
```

I think there's a small typo here, since you say in the comment you wat to test single shop context from group value

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 35]
```diff
@@ -0,0 +1,415 @@
...
+                'shopConstraint' => ShopConstraint::allShops(),
+            ],
+            [
+                'key' => 'all_shop_key_1',
+                'default' => false,
+                'shopConstraint' => ShopConstraint::shopGroup(1),
+            ],
+            'all_shop_value_1',
+        ];
+        // get value for shop 2, inherited from parent group shop
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php:317]: I believe there is one case missing (but I might have missed it)
`// get value for shop 2, inherited from parent group shop` inherited from all shop

And maybe also
`// get value for shop 2, inherited from parent group shop even though there is a value from all shops` (<- group has priority over all shops)

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 36]
```diff
@@ -0,0 +1,415 @@
...
+                'shopConstraint' => ShopConstraint::allShops(),
+            ],
+            [
+                'key' => 'all_shop_key_1',
+                'default' => false,
+                'shopConstraint' => ShopConstraint::shopGroup(1, true),
+            ],
+            null,
+        ];
+        // try getting a non existing value for all shop, with is strict = true => should return null
```
Comment (jolelievre) [inline tests/Integration/Adapter/ConfigurationTest.php:402]: You should maybe also test cases where it works ^^ Just to make sure it doesn't always return null 😛

**Review by jolelievre — COMMENTED** [review]
Great, almost perfect!! Just small comments here and there (not mandatory), and some last improvements in the test class

File: classes/shop/Shop.php [hunk 37]
```diff
@@ -884,7 +884,7 @@ public static function getTotalShops($active = true, $id_shop_group = null)
      * @param int $shop_id Shop ID
      * @param bool $as_id
      *
-     * @return int|array Group ID
+     * @return int|array|false Group ID
```
Comment (Progi1984) [inline classes/shop/Shop.php]:
```suggestion
     * @return int|array|bool Group ID
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 38]
```diff
@@ -0,0 +1,485 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace Tests\Integration\Adapter;
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
 */

declare(strict_types=1);

namespace Tests\Integration\Adapter;
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 39]
```diff
@@ -0,0 +1,485 @@
...
+     */
+    public function testGetWithSrictParameter(array $setParams, array $getParams, $expectedResult): void
+    {
+        $this->setAndGetValuesForTesting($setParams, $getParams, $expectedResult);
+    }
+
+    /**
+     * @param array $setParams
+     * @param array $getParams
+     * @param string $expectedResult
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
     * @param bool $expectedResult
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 40]
```diff
@@ -0,0 +1,485 @@
...
+     * @dataProvider hasProvider
+     */
+    public function testHas(array $setParams, array $getParams, string $expectedResult): void
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
    public function testHas(array $setParams, array $getParams, bool $expectedResult): void
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 41]
```diff
@@ -0,0 +1,485 @@
...
+    }
+
+    /**
+     * @param array $setParams
+     * @param array $getParams
+     * @param $expectedResult
+     *
+     * @dataProvider getProvider
+     */
+    public function testGet(array $setParams, array $getParams, $expectedResult): void
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
     * @param string $expectedResult
     *
     * @dataProvider getProvider
     */
    public function testGet(array $setParams, array $getParams, string $expectedResult): void
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 42]
```diff
@@ -0,0 +1,485 @@
...
+    }
+
+    /**
+     * @param array $setParams
+     * @param array $getParams
+     * @param $expectedResult
+     *
+     * @dataProvider getWithStrictParameterProvider
+     */
+    public function testGetWithSrictParameter(array $setParams, array $getParams, $expectedResult): void
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
     * @param string|null $expectedResult
     *
     * @dataProvider getWithStrictParameterProvider
     */
    public function testGetWithSrictParameter(array $setParams, array $getParams, ?string $expectedResult): void
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 43]
```diff
@@ -0,0 +1,485 @@
...
+                'shopConstraint' => ShopConstraint::shop(2, true),
+            ],
+            'shop_value_1',
+        ];
+    }
+
+    /**
+     * @param array $setParams
+     * @param array $getParams
+     * @param $expectedResult
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
     * @param string|null $expectedResult
```

File: tests/Integration/Adapter/ConfigurationTest.php [hunk 44]
```diff
@@ -0,0 +1,485 @@
...
+     */
+    private function setAndGetValuesForTesting(array $setParams, array $getParams, $expectedResult): void
```
Comment (Progi1984) [inline tests/Integration/Adapter/ConfigurationTest.php]:
```suggestion
    private function setAndGetValuesForTesting(array $setParams, array $getParams, ?string $expectedResult): void
```

File: tests/TestCase/ContextStateTestCase.php [hunk 45]
```diff
@@ -0,0 +1,72 @@
...
+use Shop;
+
+abstract class ContextStateTestCase extends TestCase
+{
+    /**
+     * @param array $contextFields
+     *
+     * @return MockObject|Context
+     */
+    protected function createContextMock(array $contextFields)
```
Comment (Progi1984) [inline tests/TestCase/ContextStateTestCase.php]:
```suggestion
    protected function createContextMock(array $contextFields): Context
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks adressed

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php (hunk 18 above)
Comment (jolelievre) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: @matthieu-rolland I just thought that this constructor should be `protected` instead of `private` This will still prevent the object from being built without the static function However it would allow creating sub types of `ShopConstraint`

For example in product page I'd like to create a `ProductShopConstraint` that would throw an exception in case you try to create it with shopGroupId (which is not handled by the product). In order to do that I need the constructor to be protected so that I can override it

**Review by jolelievre — COMMENTED** [review]
The PR is testable, but it would require a small change in the ShopCOnstraint constructor (no impact or QA before or after the modification)

**Comment by jolelievre** [comment]
@matthieu-rolland the fields in ShopCOnstraint should also be `protected`

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

I discussed with @Robin-Fischer-PS
 It is ok :heavy_check_mark: 

PS: about the  Merchandise Returns page migrated to Symfony is not working at first as reported here: https://github.com/PrestaShop/PrestaShop/issues/23606

Thanks!

**Comment by atomiix** [comment]
Thanks @matthieu-rolland & @khouloudbelguith !

**Comment by MatShir** [comment]
😱 this PR needs to be merged also into 1.7.8.0-build. @matthieu-rolland could you take a look please ? 🙏

File: src/Adapter/Configuration.php (hunk 3 above)
Comment (SharakPL) [reply src/Adapter/Configuration.php:417]: This depreciation fills the dev log very quickly. Can we get rid of it?
obraz
