### PR TITLE
Fix: BO - Product Page - Redirection type - Category without image generate 404 call

### LINKED ISSUE #37875: BO - Product Page - Redirection type - Category without image generate 404 call
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you choose a category as the redirection type when the product is disabled, the category listing also displays an image even if it's not administered, and this generates a 404.

Image

### Expected behavior

Display no image if category has no image or no image at all at this location

### Steps to reproduce

1. Go to category A and delete default image
2. Go to product page
2. Select a category redirection type when the product is deactivated
3. Search category A and see the category A with broken image before

### PrestaShop version(s) where the bug happened

FROM 1.7 TO 8.1 minimum

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | When you choose a category as the redirection type when the product is disabled, the category listing also displays an image even if it's not administered, and this generates a 404.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/37875
| UI Tests          | https://github.com/paulnoelcholot/testing_pr/actions/runs/13410487942
| Fixed issue or discussion?     | Fixes #37875
| Related PRs       | 
| Sponsor company   | @Codencode

### CODE REVIEW

**Review by boherm — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @Codencode

**Comment by alexandrebru83** [comment]
@Codencode Once the category has been selected, the image is also broken.
Maybe it's for another PR :)
Capture d’écran 2025-01-27 à 11 42 08

**Comment by Codencode** [comment]
> @Codencode Once the category has been selected, the image is also broken. Maybe it's for another PR :) Capture d’écran 2025-01-27 à 11 42 08

@alexandrebrubeyonds, this PR also resolves this case, so there's nothing else to do.

Thank you.

**Comment by alexandrebru83** [comment]
> > @Codencode Once the category has been selected, the image is also broken. Maybe it's for another PR :) Capture d’écran 2025-01-27 à 11 42 08
> 
> @alexandrebrubeyonds, this PR also resolves this case, so there's nothing else to do.
> 
> Thank you.

No I test your fix and when you save and refresh the page, image is still broken

**Comment by Codencode** [comment]
@alexandrebrubeyonds,
I tested the PR myself as well, and it works.
Which version of PS are you testing it with?
I’m using 8.2.0.
Screenshot 2025-01-27 at 12-38-32 Products • Codencode

Thanks!

**Comment by alexandrebru83** [comment]
8.1.6 : https://www.awesomescreenshot.com/video/35947029?key=c18d4378741d20be311f403e4e834eb6

Do you save and refresh the page ?

**Comment by Codencode** [comment]
> 8.1.6 : https://www.awesomescreenshot.com/video/35947029?key=c18d4378741d20be311f403e4e834eb6
> 
> Do you save and refresh the page ?


Ah, I see, the problem is the reopening of the page. I’ll check if I can fix it.
Thanks for the feedback!

**Comment by Hlavtox** [comment]
I think it gets the link from `public function getCategory(` on page load. :-)

**Comment by SiraDIOP** [comment]
Hello @Codencode ,

I tested your PR and it's good for me! 🎉
Thanks!
Capture d’écran 2025-01-27 à 14 46 14

**Review by SiraDIOP — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Not sure whats happening, but no changes in code were made since the failure report

**Comment by Codencode** [comment]
> I think it gets the link from `public function getCategory(` on page load. :-)

@Hlavtox, the system retrieves the image here:
https://github.com/PrestaShop/PrestaShop/blob/3071db5e2834885c9456ee3b880f404f480bb71d/src/Adapter/Category/Repository/CategoryPreviewRepository.php#L85-L85

I was thinking of replacing that code with:
```php
        if (file_exists(_PS_CAT_IMG_DIR_ . $categoryId->getValue() . '.jpg')) {
            $imagePath = $this->categoryImagePathFactory->getPath($categoryId->getValue());
        } else {
            $imagePath = $this->categoryImagePathFactory->getNotAvailableImagePath(Language::getIsoById($languageId->getValue()) . '-default-category_default');
        }
```

And adding the new method to the ImagePathFactory class (https://github.com/PrestaShop/PrestaShop/blob/8.2.x/src/Adapter/Image/ImagePathFactory.php):

```php
    /**
     * @param string $name
     *
     * @return string
     */
    public function getNotAvailableImagePath(string $name) : string
    {
        return sprintf('%s/%s.jpg', $this->pathToBaseDir, $name);
    }
```
Alternatively, I could pass the language's iso_code as a parameter to the getPreview function here:
https://github.com/PrestaShop/PrestaShop/blob/3071db5e2834885c9456ee3b880f404f480bb71d/src/Adapter/Product/Options/RedirectTargetProvider.php#L139-L142
This way, we avoid having to retrieve the iso_code from the ID.

I've created 2 temporary PRs with the 2 solutions:

Solution 1: https://github.com/Codencode/PrestaShop/commit/e07afa5f697470ae236ccc00a6535f836101d572

Solution 2: https://github.com/Codencode/PrestaShop/commit/520dd00c52638b7d041a07e849b6c688f49562f0

What do you think?

Of course, once the best solution is found, I will make the changes to this PR.

Thanks.

**Comment by Codencode** [comment]
> Hello @Codencode ,
> 
> I tested your PR and it's good for me! 🎉 Thanks! Capture d’écran 2025-01-27 à 14 46 14

Hello @SiraDIOP,
sorry, but I'm trying to solve a second small issue (related to the PR) that came up after the creation of this PR.

**Comment by Hlavtox** [comment]
@Codencode Or you could change `public function getPath(int $entityId):` to `public function getPath(int|string0 $imageName):` and reuse that method. There is already so much duplicate code for primitive logic. :-)

**Comment by Codencode** [comment]
> @Codencode Or you could change `public function getPath(int $entityId):` to `public function getPath(int|string0 $imageName):` and reuse that method. There is already so much duplicate code for primitive logic. :-)

@Hlavtox, great idea!
Would you retrieve the `iso_code` directly within the` CategoryPreviewRepository::getPreview()` method, or would you pass it as a parameter?

**Comment by Codencode** [comment]
I have added fallback image management for categories without an image to resolve the issue reported by @alexandrebrubeyonds .

I opted to retrieve the iso_code directly in the `CategoryPreviewRepository::getPreview()` method.

File: src/Adapter/Image/ImagePathFactory.php [hunk 1]
```diff
@@ -45,12 +45,12 @@ public function __construct(
     }
 
     /**
-     * @param int $entityId
+     * @param int|string $imageName
      *
      * @return string
      */
-    public function getPath(int $entityId): string
+    public function getPath(int|string $imageName): string
```
Comment (Hlavtox) [inline src/Adapter/Image/ImagePathFactory.php]: @Codencode I would remove the `int|string` here and it will work

Comment (Codencode) [reply src/Adapter/Image/ImagePathFactory.php]: Yes, I was looking into the issue.
Ok, I'll remove it.
Thanks!

**Review by Hlavtox — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Codencode,

I tested your PR and it's good for me! :tada: 

Thanks!

image
Automated test : https://github.com/paulnoelcholot/testing_pr/actions/runs/13410487942

**Comment by Codencode** [comment]
Hello @paulnoelcholot, Thanks!
