### PR TITLE
BO - Product : Fixed feature display in multishop

### LINKED ISSUE #15383: Multistore Product feature saving bug
### Describe the bug
In a multistore installation, all of the features are always loaded in the backoffice despite being disabled for a specific shop. The featurevalues will multiply on every save.

### Steps To Reproduce
1. Turn on multistore
2. Create a feature, but only allow it for one shop.
3. Add the feature whilst selecting the shop it's allowed for
4. Change shop, you'll see the featurename is empty.
5. Save the product
6. the features are incorrectly persisted to the database 

**Screenshots**
Feature:
image
Product, in the correct shop:
image
Product after save of previous screenshot, but in the other shop:
image

Before saving in the incorrect shop (id-product 19):
image
Then, after saving it with the empty featurename (will create the id_feature: 0 row):
image

### Additional information

- PrestaShop version: 1.7.8.7
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | BO - Product : Fixed feature display in multishop
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | :arrow_down:  
| UI Tests          | https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19478232645
| Fixed issue or discussion?     | Fixes #15383
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

## How to test ?
* Go to BO
* Enable Multistore
* Create a Shop named "Shop2"
* Create a feature "My Super Feature", only for the first shop, and some feature values
* Go to Catalog Products
* Select the first shop  (in the multistore header bar)
* Create a standard product
* Save it
* "Select Stores" for all stores (in the multistore header bar)
* Add a feature (The feature  "My Super Feature" is available) and choose a value
* Add a feature (The feature  "My Super Feature" is available) and choose a personalized value
* Save it
* Change to the "Shop 2"
* **BEFORE**
  *  Add a feature (The feature  "My Super Feature" was available) 
  * Features previously created were visible
* **AFTER**
  * Add a feature (The feature  "My Super Feature" is not available => because it is not allowed to this store) 
  * Features previously created are not visible

### CODE REVIEW

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

File: src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php [hunk 1]
```diff
@@ -45,7 +45,8 @@ class FeaturesChoiceProvider implements FormChoiceProviderInterface
     public function __construct(
         protected readonly FeatureRepository $featureRepository,
         protected readonly LegacyContext $legacyContext,
-        protected readonly ConfigurationInterface $configuration
+        protected readonly ConfigurationInterface $configuration,
+        protected readonly int $contextShopId
```
Comment (Codencode) [inline src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php]: Hi @Progi1984 
do we need to pass $contextShopId as a parameter? Couldn't you retrieve it from $legacyContext?

Comment (Progi1984) [reply src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php]: Fixed. Thanks for the tip.

**Review by Codencode — APPROVED** [review]

**Review by nicohery — APPROVED** [review]

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

Ping @kpodemski :pray:

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@Progi1984 UI + CI is green, can we merge?

BTW, Franck, if nobody approves your PRs, just ping me or @Codencode more often, so we can get it merged fast. :-)

**Comment by Progi1984** [comment]
@Hlavtox I let @PrestaShop/qa-functional decide.

Thanks for reviewing my personal PRs (not linked to PSCorp).

**Comment by Codencode** [comment]
@Progi1984  @Progi1984 
I remember I already approved this PR (because I tested it) and I see my approval is already there. Do I need to do anything else?

**Comment by Progi1984** [comment]
> @Progi1984  @Progi1984 
> I remember I already approved this PR (because I tested it) and I see my approval is already there. Do I need to do anything else?

No Thanks

**Review by SharakPL — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Progi1984, 

Thanks for your PR, 
 i tested it and it's good for me :) 
Capture d’écran 2026-01-14 à 19 28 10
Capture d’écran 2026-01-14 à 19 32 33
Capture d’écran 2026-01-14 à 19 33 10

Thanks

**Review by SiraDIOP — APPROVED** [review]

**Comment by nicosomb** [comment]
thank you @Progi1984 and @SiraDIOP !
