### PR TITLE
Fix customer isLogged property in FO

### LINKED ISSUE #30991: is_logged property in FO is true even for guests
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Something is broken on 8.0 and develop - guest customers haves `is_logged = true` for some reason.

This results in wrong behavior of modules that use it. For example, ps_customersignin returns a logged in customer with no name and a list of non-functional links. The same for customer account links in footer.

Snímek obrazovky 2023-01-22 162928

**Does not happen on previous versions.**

### Expected behavior

`$customer` object in front office should NOT return `is_logged` `true` in case of guests.

I traced the behavior to `$customer->isLogged` function, there is a difference, when 8+ returns true for `Context::getContext()->cookie->isSessionAlive()` call. This change is probably correct.

What is not correct is the call. `$cust['is_logged'] = $this->context->customer->isLogged(true);`. Changing it to `$cust['is_logged'] = $this->context->customer->isLogged();` fixes the issue.

### Steps to reproduce

1. Use hummingbird or classic theme. To better see the issue, add `{dump($customer)}` to `templates\_partials\header.tpl`.
2. Now add something to cart, go to checkout, fill out the first step WITHOUT a password, just as a guest - name and email only. Go to step 2.
3. On hummingbird, you will see it right away, on classic, go somewhere where you can see footer. See that there are links indended for loggd in customer, with "sign out" button. And when you click them, it redirects you to login page. Also if you check the dumped data on the top, see that the customer has `logged_in` true or 1.

### PrestaShop version(s) where the bug happened

8.0, develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | See below
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | See below
| Fixed ticket?     | Fixes #30991
| Related PRs       | 
| Sponsor company   | 

### Changes explained
- I removed the usage of `withGuest` parameter of isLogged function that causes it to return true even if the customer is guest.
- A) In FO, we always need the real value, that's why the change in `$cust['is_logged'] = $this->context->customer->isLogged();`.
- B) Then there is the line that redirects to login controller if `$auth` is `true` and `isLogged` is `false`. It's passing an attribute called `guestAllowed`, which is always `false` and not used at all in whole core or modules.
- C) And last usage of this parameter was in `Hook` class. I simply used `isGuest` check instead of this.
- Keeping it now to not introduce BC, but I will remove this parameter completely in v9. IsLogged should be what it is, and not magically return true even for guests.

### What to test
- To test A), check scenario I described in the issue. Finish step 1 in checkout without entering a password (guest order), go to homepage, see that the dumped data and links in footer are correct.
- To test B), check that if you are logged out and you try to go to `/addresses` (or some other page that requires login) for example, it will still redirect you to login screen and there will be no change in behaviour.
- To test C)
  - Register yourself through register page. (not checkout, there is a group assignment bug fixed on develop only I think)
  - Go to `Customer groups`, edit Guest group (2) and uncheck search bar module for example.
  - Now go to `Customers`, edit your customer and try changing his user groups. 
    - Assign him to group 1, default group 1 - search module is visible in FO. 
    - Assign him to group 2, default group 2, module disappears in FO. 
    - Assign him to group 3, module reappears again.

### CODE REVIEW

**Comment by Hlavtox** [comment]
I would like @kpodemski to do the QA 🙏

**Review by FabienPapet — APPROVED** [review]

File: classes/controller/FrontController.php [hunk 1]
```diff
@@ -80,6 +80,7 @@ class FrontControllerCore extends Controller
     /**
      * If set to true, user can be logged in as guest when checking if logged in.
      *
+     * @deprecated Since 8.0 and will be removed in the next major.
```
Comment (FabienPapet) [inline classes/controller/FrontController.php:83]:
```suggestion
     * @deprecated Since 8.1 and will be removed in the next major.
```

**Review by lartist — APPROVED** [review]

File: classes/controller/FrontController.php (hunk 1 above)
Comment (Hlavtox) [reply classes/controller/FrontController.php:83]: The version is correct, I am targeting 8.0 branch

Comment (FabienPapet) [reply classes/controller/FrontController.php:83]: Deprecating something in a patch version should not be allowed IMO :/ I did not check the targeted branch.

Comment (Hlavtox) [reply classes/controller/FrontController.php:83]: I can remove the deprecation notice and add it in 8.1, but it will have the same effect. Worse, because people will find out later.

Anyway, this should be merged ASAP to 8.0.2

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
1. check scenario I described in the issue. Finish step 1 in checkout without entering a password (guest order), go to homepage, see that the dumped data and links in footer are correct => QA :heavy_check_mark: 
2. check that if you are logged out and you try to go to /addresses (or some other page that requires login) for example, it will still redirect you to login screen and there will be no change in behaviour => QA :heavy_check_mark: 
3. Register yourself through register page. Go to Customer groups, edit Guest group (2) and uncheck search bar module for example. Now go to Customers, edit your customer and try changing his user groups:

- Assign him to group 1, default group 1 - search module is visible in FO => QA :heavy_check_mark: 
- Assign him to group 2, default group 2, module disappears in FO => QA :heavy_check_mark: 
- Assign him to group 3, module reappears again => QA :heavy_check_mark: 

Thanks!

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
Thanks myself and the team 💘
