### PR TITLE
Fix wrong product quantity after adding a product triggering a free gift 

### LINKED ISSUE #21506: BO - Order page - Updating a product with a specific discount (gift)
Related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/21447)

#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Create a cart rule 
1.1 Informations: without code
1.2 Conditions: Product selection demo_6
1.3 Actions: Free shipping + discount amount = 1euro tax included + Free gift (demo_11)
2. Add a product demo_11 to the cart 
4. Continue checkout
5. Go to the BO > Order detail page
6. Try to add demo_6 to the order 
In this case, we have two behaviors

If the quantity of demo_11 = 1
=> the discount is well applied but quantity of demo_11 = 1 (not updated)
image

If the quantity of demo_11 > 1 (=2)
=> the discount is well applied and quantity of demo_11 = 2 (well updated)
image

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix wrong product quantity in order when adding a product triggers a free gift cart rule and there's only the same kind of product in the order, and only one remaining in stock.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21506
| How to test?  | See steps in the issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21795)

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -1428,7 +1428,7 @@ public function updateQty(
 
             if ($operator == 'up') {
                 $updateQuantity = '+ ' . $quantity;
-                $newProductQuantity = $productQuantity - $quantity;
+                $newProductQuantity = ($productQuantity + $cartProductQuantity['quantity']) - $quantity;
```
Comment (matthieu-rolland) [inline classes/Cart.php]: We get the product quantity from `Product::getQuantity()`, but for some reason this method subtracts the number of product of the same kind in the cart from the total quantity in stock, so we need to add it here before we do our comparison otherwise substracting the quantity we are setting below can sometimes give a negative value even though it shouldn't  

I was thinking about replacing the use of `Product::getQuantity()` for something else, but I'm not sure about the possible consequences. This modification fixes the bug and doesn't break any test.

**Review by atomiix — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature [hunk 2]
```diff
@@ -930,3 +930,34 @@ Feature: Order from Back Office (BO)
...
+      | price         | 12.0                     |
+    Then order "bo_order1" should have 5 products in total
+    And the available stock for product "gifted product" should be 0
+    And product "gifted product" in order "bo_order1" has following details:
+      | product_quantity            | 2     |
+      | product_price               | 15.00 |
+      | unit_price_tax_incl         | 15.90 |
+      | unit_price_tax_excl         | 15.00 |
+      | total_price_tax_incl        | 31.80 |
+      | total_price_tax_excl        | 30.00 |
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1060]: You should add tests about all the order total prices as well (especially discounts in this case)
Ideally even also add them right before the product is added to the order

File: classes/Cart.php (hunk 1 above)
Comment (jolelievre) [reply classes/Cart.php]: This is wanted, when the cart is provided as a parameter to `Product::getQuantity` it is meant to substract the cart's quantity from the stock Because as long as a cart is not finalized the stock is not decreased

The real stock is only substracted when the order is created (because a pending cart is not considered to be finished so it doesn't affect the stock yet)

That's why it MUST performs this computation, here's a example because it's not an easy topic:
- Product A has 5 quantities of stock
- Cart has 3 product A
- So "virtually" there is only 2 left Product A in stock
- I update the cart and add 3 more Product A (so 6 in total which is not possible)
- The action in the cart will "up" of 3 products
- So Product::getQuantity returns 5 (real stock) - 3 (products present in cart) = 2 virtually available products
- Then the action must fail because it's too high

So your modif will break this behaviour The biggest problem is we have ZERO test to ensure we don't break this.. 

Now in your case it's different because you are modifying a cart which has already been ordered, so the stock has already been updated and is accurante regardles of the cart quantity, so you can't rely on the same rules (but it doesn't mean you can modify them or it will break the FO behaviour)

We already encountered this kind of issues in other Order handlers, usually the solution is to perform all the stock checks beorehand to make sure they are valid and disbale this check using the last parameter of `Cart::updateQuantity` => `$skipAvailabilityCheckOutOfStock = true`

Like here:
https://github.com/PrestaShop/PrestaShop/blob/611916bdb01be94bbb094e000f3b6e2a99590330/src/Adapter/Order/OrderProductQuantityUpdater.php#L251

Comment (jolelievre) [reply classes/Cart.php]: The problem here is that the gift present is automatically added via:

https://github.com/PrestaShop/PrestaShop/blob/611916bdb01be94bbb094e000f3b6e2a99590330/classes/Cart.php#L1216

So it's hard coded to check the stock based on the cart quantity And you can't even add a new parameter in `addCartRule` that would ignore this when called from an Order handler, because it's NOT called from a handler It is automatically called when the product is added and `CartRule::autoAddToCart` is called

So that's a tricky one ^^ But I don't have the solution right now

**Review by jolelievre — DISMISSED** [review]
No can do ^^

File: classes/Cart.php (hunk 1 above)
Comment (jolelievre) [reply classes/Cart.php]: The whole problem is about the fact that Cart is actually ordered but we have no way to know that with the cart's data alone.. One solution could be to add an `id_order` column in the Cart that is automatically filled when the order is created

This way we could easily detect that a cart is an order cart (and it would probably allow other things later, or for some refacto) But I'm not even sure it would be enough, because I'm not sure it's safe to simply disable some checks because a cart is ordered

That said.. maybe it would allow us to update `Product::getQuantity` and it wouldn't substract the cart quantity if the cart has an order (meaning stock is already udpated) That's a lead.. But it would be safer to add behat tests on the cart to avoid too many regressions

Comment (matthieu-rolland) [reply classes/Cart.php]: thank you for those very useful informations! I'll modify `Product::getQuantity` so that it subtracts the cart quantity only if the cart has no related order. And add tests for the case you described above. That will take the addition of a new column in ps_cart.

File: classes/Cart.php [hunk 3]
```diff
@@ -137,6 +140,7 @@ class CartCore extends ObjectModel
             'allow_seperated_package' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
             'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
             'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
+            'id_order' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedId'],
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
            'id_order' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'allow_null' => true],
```

File: classes/Cart.php [hunk 4]
```diff
@@ -84,6 +84,9 @@ class CartCore extends ObjectModel
     /** @var string Object last modification date */
     public $date_upd;
 
+    /** @var int Order ID */
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
    /** @var int|null Order ID */
```

File: install-dev/upgrade/sql/1.7.7.0.sql [hunk 5]
```diff
@@ -887,3 +887,8 @@ DELETE FROM `PREFIX_hook` WHERE name = 'actionFrontControllerAfterInit';
 
 /* Update wrong hook alias */
 UPDATE `PREFIX_hook_alias` SET name = 'displayHeader', alias = 'Header' WHERE name = 'Header' AND alias = 'displayHeader';
+
+/* add id_order in cart */
+ALTER TABLE `PREFIX_cart`
+    ADD `id_order` INT(10) UNSIGNED,
```
Comment (Progi1984) [inline install-dev/upgrade/sql/1.7.7.0.sql]:
```suggestion
    ADD `id_order` INT(10) UNSIGNED NULL DEFAULT NULL,
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature [hunk 6]
```diff
@@ -930,3 +930,34 @@ Feature: Order from Back Office (BO)
...
+    And cart rule "GiftAutoCartRule" is restricted to product "product triggering gift"
+    And cart rule "GiftAutoCartRule" offers free shipping
+    And cart rule "GiftAutoCartRule" offers a gift product "gifted product"
+    And I add 1 products "gifted product" to the cart "dummy_cart"
+    Given I add order "bo_order1" with the following details:
+      | cart                | dummy_cart                 |
+      | message             | test                       |
+      | payment module name | dummy_payment              |
+      | status              | Awaiting bank wire payment |
+    Then order "bo_order1" should have 3 products in total
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1034]: Why 3 ?

**Review by Progi1984 — COMMENTED** [review]
Some comments

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature (hunk 6 above)
Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1034]: Because there are already two products in the cart, due to the background actions from which all scenarios in this file inherit:

https://github.com/PrestaShop/PrestaShop/blob/953205dbd8d29db3368638d7494ad86430806e5a/tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature#L23

File: classes/Cart.php (hunk 1 above)
Comment (matthieu-rolland) [reply classes/Cart.php]: I tried the scenario you wrote above, it didn't seem to be broken even with my former fix...  I still made the fix we talked about. 

I think the kind of scenario you're worried about is throughly tested here: `tests/Integration/Behaviour/Features/Scenario/Order/order_out_of_stock.feature`

**Comment by Progi1984** [comment]
@matthieu-rolland Conflicts detected : need to rebase :)

File: install-dev/upgrade/sql/1.7.7.0.sql [hunk 7]
```diff
@@ -676,3 +676,8 @@ DELETE FROM `PREFIX_hook` WHERE name = 'actionFrontControllerAfterInit';
 
 /* Update wrong hook alias */
 UPDATE `PREFIX_hook_alias` SET name = 'displayHeader', alias = 'Header' WHERE name = 'Header' AND alias = 'displayHeader';
+
+/* add id_order in cart */
+ALTER TABLE `PREFIX_cart`
```
Comment (Progi1984) [inline install-dev/upgrade/sql/1.7.7.0.sql]: Must be move in `1.7.7.1.sql`.

**Review by Progi1984 — DISMISSED** [review]
:warning: The fix SQL must be in a new file

File: install-dev/upgrade/sql/1.7.7.0.sql (hunk 7 above)
Comment (matthieu-rolland) [reply install-dev/upgrade/sql/1.7.7.0.sql]: nice catch ! 

it was not supposed to be 1.7.7.1 when I started this issue...  (done !)

File: install-dev/upgrade/sql/1.7.7.1.sql [hunk 8]
```diff
@@ -1 +1,9 @@
 /* PHP:ps_1771_update_customer_note(); */;
+
+SET SESSION sql_mode='';
+SET NAMES 'utf8';
+
+/* add id_order in cart */
+ALTER TABLE `PREFIX_cart`
+    ADD `id_order` INT(10) UNSIGNED NULL DEFAULT NULL,
+    ADD INDEX (id_order);
```
Comment (atomiix) [inline install-dev/upgrade/sql/1.7.7.1.sql]: No need to update the existing cart to add the id_order?

**Comment by Matt75** [comment]
Hi

I'm worried about cart with multiple orders and this changes.

Currently in PaymentModule::validateOrder() PrestaShop can split a Cart in multiple Orders in some cases described in https://github.com/PrestaShop/prestashop-specs/issues/111

With your changes you assign an id_order to a Cart but in case of a Cart with multiple Orders, how this will works ?

This weird behavior of PrestaShop cause many issues with payment modules since years 😅 and no one know how handle it...

**Review by Progi1984 — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
> Hi
> 
> I'm worried about cart with multiple orders and this changes.
> 
> Currently in PaymentModule::validateOrder() PrestaShop can split a Cart in multiple Orders in some cases described in [PrestaShop/prestashop-specs#111](https://github.com/PrestaShop/prestashop-specs/issues/111)
> 
> With your changes you assign an id_order to a Cart but in case of a Cart with multiple Orders, how this will works ?
> 
> This weird behavior of PrestaShop cause many issues with payment modules since years 😅 and no one know how handle it...

thanks for the precious insight @Matt75  !   I guess this PR will remain in standby until something is officially specified for the order splitting mechanism ? 

In all cases, we have to find another way to fix the issue this PR was meant to fix...

File: install-dev/upgrade/sql/1.7.7.1.sql (hunk 8 above)
Comment (jolelievre) [reply install-dev/upgrade/sql/1.7.7.1.sql]: Indeed we need a script to update this, or a super doped SQL query if someone knows how to ^^

**Review by jolelievre — COMMENTED** [review]
Some additional upgrade scripts required but it seems good
And I need this soon for another fix ^^

File: classes/Product.php [hunk 9]
```diff
@@ -3752,7 +3752,9 @@ public static function getQuantity(
         $availableQuantity = StockAvailable::getQuantityAvailableByProduct($idProduct, $idProductAttribute);
         $nbProductInCart = 0;
 
-        if (!empty($cart)) {
+        // we don't substract products in cart if the cart is already attached to an order, since stock quantity
+        // has already been updated, this is only useful when the order has not yet been created
+        if (!empty($cart) && (int) $cart->id_order <= 0) {
```
Comment (jolelievre) [inline classes/Product.php]: @matthieu-rolland as discussed based on the comment from @Matt75 https://github.com/PrestaShop/PrestaShop/pull/21795#issuecomment-739249918

It might not be a good idea to store the orderId in the cart table because it maybe be associated to multiple orders, even though in this case it wouldn't have much impact because we just need to know if the Cart is order, no matter how many orders a linked to it. So we have two solutions here I guess:
- never store the relation and rely on `Order::getIdByCartId` this will make an extra SQL query but at least we are sure to have up to date data and nothin in the cart table is confusing
- we store the Order `reference` instead of its ID, since all split orders have the same reference we can still correctly get the whole list thanks to this column

File: classes/PaymentModule.php [hunk 10]
```diff
@@ -1060,6 +1060,10 @@ protected function createOrderFromCart(
             throw new PrestaShopException('Can\'t save Order');
         }
 
+        // update cart's order id
+        $cart->id_order = $order->id;
```
Comment (jolelievre) [inline classes/PaymentModule.php]: If we want to be safer and not only rely on this module and expect every Order creation to be made here, we should do this in `Order::add` and/or `Order::update` so that any modif saved via the ObjectModel ensure that the cart is always correctly updated (even if it's not created via a PaymentModule)

File: classes/Product.php (hunk 9 above)
Comment (matthieu-rolland) [reply classes/Product.php]: So I opted for solution number 2

File: classes/Cart.php [hunk 11]
```diff
@@ -138,6 +141,7 @@ class CartCore extends ObjectModel
             'allow_seperated_package' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
             'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
             'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
+            'reference_order' => ['type' => self::TYPE_STRING, 'allow_null' => true],
```
Comment (Progi1984) [inline classes/Cart.php]: :warning: self::TYPE_STRING but the PHPDoc is `int`.

Comment (Progi1984) [reply classes/Cart.php]: If it's a string, define the size

File: classes/order/Order.php [hunk 12]
```diff
@@ -311,6 +311,10 @@ public function getFields()
     public function add($autodate = true, $null_values = true)
     {
         if (parent::add($autodate, $null_values)) {
+            $cart = new Cart((int) $this->id_cart);
```
Comment (jolelievre) [inline classes/order/Order.php]: I'm not sure exactly when the Order reference is created and saved Maybe it would be safer to perform this in the update method as well?

File: classes/Cart.php (hunk 11 above)
Comment (jolelievre) [reply classes/Cart.php]: After all the discussion with @kpodemski I'm still not 100% sure about using this reference

Split order shouldn't be a problem since they share the same reference anyway, and for this use case we actually don't care about the order reference since we don't use it It is only used to know if the cart is ordered or not

But once this field is introduce some other devs may start using it so if it is not consistent it might lead to some unexpected behaviour so we need to be careful about it

So I'm thinking maybe a simple boolean would be enough for us here, and less confusing Like just a `ordered` boolean to avoid calling `Order::getIdByCartId` for performance issue

Comment (kpodemski) [reply classes/Cart.php]: @jolelievre `ordered` flag is ok, also it's a handy way to get all non ordered carts from for example 2 years ago and just throw them into space :) one suggestion would be to have some helper methods like `static::isCartOrdered` `$cart->markAsOrdered()`

Comment (jolelievre) [reply classes/Cart.php]: I'm not sure but I believe such detection of abandoned carts already exist in `AdminStatsController::getAbandonedCarts` or in `Cart::lastNoneOrderedCart` (there might be other similar features)

It's already doable easily with a leftJoin on order table

Comment (matthieu-rolland) [reply classes/Cart.php]: I won't touch the db structure (as discussed on slack, it's not worth it for now)

**Review by jolelievre — APPROVED** [review]
So much smaller now indeed 😅

**Review by PierreRambaud — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]
All good 👍 let's wait for Travis tho

Edit: Travis is happy, time for QA

**Comment by SD1982** [comment]
LGTM thanks @matthieu-rolland !!

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @SD1982
