### PR TITLE
Fix ps_facetedsearch - bad display after clearing a filter of no result

### LINKED ISSUE #28966: FO - ps_facetedsearch - A bad display afer clearing a filter of no result
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > When we create a filter with no result, then we clear it, the products are not displayed

PS1778 + ps_facetedsearch v3.7.1 => ok  / PS1778 + ps_facetedsearch 3.8.0 => OK
PS1786 + ps_facetedsearch 3.8.0 => NOK / PS1786 + ps_facetedsearch 3.7.1 => NOK / 8.0.x + ps_facetedsearch 3.8.0 => NOK

### Expected behavior

_No response_

### Steps to reproduce

1. Go to FO > Click on the `All products` link
2. Try to filter by price 41€ ~ 42€ & size = S => no result
3. Click on clear all or remove any active filter
4. See error: the products are not well displayed: there is no space between products 

image
Refresh the page => OK 
image

### PrestaShop version(s) where the bug happened

1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by leemyongpakvn**
Seperate `renderedProducts` and `productSelectors`, then we are safe in case `$(prestashop.themeSelectors.listing.product)` is `Undefined` after a previous filter with _No product_

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Backport of https://github.com/PrestaShop/classic-theme/pull/43.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28966.
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | See issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

File: themes/classic/_dev/js/listing.js [hunk 1]
```diff
@@ -229,11 +229,13 @@ function updateProductListDOM(data) {
...
-  const productSelectors = $(prestashop.themeSelectors.listing.product, renderedProducts);
+  const productSelectors = $(prestashop.themeSelectors.listing.product);
 
   if (productSelectors.length > 0) {
-    productSelectors.removeClass().addClass($(prestashop.themeSelectors.listing.product).first().attr('class'));
-  }
+    productSelectors.removeClass().addClass(productSelectors.first().attr('class'));
+  } else {
+    productSelectors.removeClass().addClass(renderedProducts.first().attr('class'));
+  }
```
Comment (NeOMakinG) [inline themes/classic/_dev/js/listing.js]: I guess the `if/else` is useless then?

Edit: I'm dumb.

**Review by NeOMakinG — CHANGES_REQUESTED** [review]

**Review by NeOMakinG — DISMISSED** [review]
🍬

**Review by kpodemski — DISMISSED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by leemyongpakvn** [comment]
@kpodemski In need of your approval after a small lint-fix

**Review by kpodemski — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @leemyongpakvn,

Thank you for this PR.
Tested on 1.7.8.x branch with PHP 7.3.

All products are well displayed after clearing the filter:

https://user-images.githubusercontent.com/2854834/189152641-40970163-3525-4910-a55a-5fd007756c1c.mp4

QA approved ✅ 

Thanks

**Comment by matks** [comment]
Thank you @leemyongpakvn
