### PR TITLE
Fix WS error: add product with empty unit-price

### LINKED ISSUE #29315: Webservice error onto product add method
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

A php error occur when i try to add a product with webservice.
Error is:
```

Fatal error: Uncaught InvalidArgumentException: "" cannot be interpreted as a number in /var/www/prestashop/vendor/prestashop/decimal/src/Builder.php:36
Stack trace:
#0 /var/www/prestashop/vendor/prestashop/decimal/src/DecimalNumber.php(73): PrestaShop\Decimal\Builder::parseNumber('')
#1 /var/www/prestashop/classes/Product.php(883): PrestaShop\Decimal\DecimalNumber->__construct('')
#2 /var/www/prestashop/classes/Product.php(849): ProductCore->fillUnitRatio(false)
#3 /var/www/prestashop/classes/Product.php(801): ProductCore->updateUnitRatio()
#4 /var/www/prestashop/classes/Product.php(7542): ProductCore->add(true, false)
#5 /var/www/prestashop/classes/webservice/WebserviceRequest.php(1668): ProductCore->addWs()
#6 /var/www/prestashop/classes/webservice/WebserviceRequest.php(1443): WebserviceRequestCore->saveEntityFromXml(201)
#7 /var/www/prestashop/classes/webservice/WebserviceRequest.php(578): WebserviceRequestCore->executeEntityPost()
#8 /var/www/prestashop/webservice/dispatcher.php(90): WebserviceRequestCore->fetch('H2S in /var/www/prestashop/vendor/prestashop/decimal/src/Builder.php on line 36

```
### Expected behavior

I must have an XML output instead of this php error, even invalid data are send.

### Steps to reproduce

1. Enable webservice and debug mode
2. Send a request like this one:

```

<?php
    error_reporting(-1);
    ini_set('display_errors', true);
    $ch = curl_init();
    curl_setopt($ch, 10002, 'http://vps-c364ee61.vps.ovh.net/api/products&ws_key=KEY');
    curl_setopt($ch, 42, '1');
    curl_setopt($ch, 19913, '1');
    curl_setopt($ch, 2, '1');
    curl_setopt($ch, 10018, 'browser');
    curl_setopt($ch, 107, '1');
    curl_setopt($ch, 10005, 'KEY:');
    curl_setopt($ch, 13, '300');
    curl_setopt($ch, 10023, unserialize('a:1:{i:0;s:7:"Expect:";}'));
    curl_setopt($ch, 10036, 'POST');
    curl_setopt($ch, 10015, 'xml=<?xml version="1.0" encoding="UTF-8"?>
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<product>
	<id><![CDATA[]]></id>
	<id_manufacturer><![CDATA[]]></id_manufacturer>
	<id_supplier><![CDATA[]]></id_supplier>
	<id_category_default>2</id_category_default>
	<new><![CDATA[]]></new>
	<cache_default_attribute><![CDATA[]]></cache_default_attribute>
	<id_default_image><![CDATA[]]></id_default_image>
	<id_default_combination><![CDATA[]]></id_default_combination>
	<id_tax_rules_group><![CDATA[]]></id_tax_rules_group>
	
	
	<id_shop_default><![CDATA[]]></id_shop_default>
	<reference>REF459</reference>
	<supplier_reference><![CDATA[]]></supplier_reference>
	<location><![CDATA[]]></location>
	<width>5</width>
	<height>6</height>
	<depth>7</depth>
	<weight>5</weight>
	<quantity_discount><![CDATA[]]></quantity_discount>
	<ean13><![CDATA[]]></ean13>
	<isbn><![CDATA[]]></isbn>
	<upc><![CDATA[]]></upc>
	<mpn><![CDATA[]]></mpn>
	<cache_is_pack><![CDATA[]]></cache_is_pack>
	<cache_has_attachments><![CDATA[]]></cache_has_attachments>
	<is_virtual><![CDATA[]]></is_virtual>
	<state>1</state>
	<additional_delivery_times><![CDATA[]]></additional_delivery_times>
	<delivery_in_stock><language id="1"><![CDATA[]]></language></delivery_in_stock>
	<delivery_out_stock><language id="1"><![CDATA[]]></language></delivery_out_stock>
	<product_type><![CDATA[]]></product_type>
	<on_sale><![CDATA[]]></on_sale>
	<online_only><![CDATA[]]></online_only>
	<ecotax>10</ecotax>
	<minimal_quantity>1</minimal_quantity>
	<low_stock_threshold><![CDATA[]]></low_stock_threshold>
	<low_stock_alert><![CDATA[]]></low_stock_alert>
	<price>20.833333</price>
	<wholesale_price><![CDATA[]]></wholesale_price>
	<unity><![CDATA[]]></unity>
	<unit_price><![CDATA[]]></unit_price>
	<unit_price_ratio><![CDATA[]]></unit_price_ratio>
	<additional_shipping_cost><![CDATA[]]></additional_shipping_cost>
	<customizable><![CDATA[]]></customizable>
	<text_fields><![CDATA[]]></text_fields>
	<uploadable_files><![CDATA[]]></uploadable_files>
	<active>1</active>
	<redirect_type><![CDATA[]]></redirect_type>
	<id_type_redirected><![CDATA[]]></id_type_redirected>
	<available_for_order>1</available_for_order>
	<available_date><![CDATA[]]></available_date>
	<show_condition><![CDATA[]]></show_condition>
	<condition>new</condition>
	<show_price>1</show_price>
	<indexed><![CDATA[]]></indexed>
	<visibility><![CDATA[]]></visibility>
	<advanced_stock_management><![CDATA[]]></advanced_stock_management>
	<date_add><![CDATA[]]></date_add>
	<date_upd><![CDATA[]]></date_upd>
	<pack_stock_type><![CDATA[]]></pack_stock_type>
	<meta_description><language id="1"><![CDATA[]]><![CDATA[Livraison rapide. Le TESLA est un mod électronique simple d'utilisation à Volt et Watt variable.]]></language></meta_description>
	<meta_keywords><language id="1"><![CDATA[]]><![CDATA[]]></language></meta_keywords>
	<meta_title><language id="1"><![CDATA[]]><![CDATA[Tesla - Chrome : Mod électronique]]></language></meta_title>
	<link_rewrite><language id="1"><![CDATA[]]></language></link_rewrite>
	<name><language id="1"><![CDATA[]]><![CDATA[After 8 0 é U %toto ² machine]]></language></name>
	<description><language id="1"><![CDATA[]]><![CDATA[<div class="row-fluid">desc longue</div>]]></language></description>
	<description_short><language id="1"><![CDATA[]]><![CDATA[desc courte]]></language></description_short>
	<available_now><language id="1"><![CDATA[]]></language></available_now>
	<available_later><language id="1"><![CDATA[]]></language></available_later>
<associations>
<categories>
	<category>
	<id><![CDATA[]]></id>
	</category>
</categories>
<images>
	<image>
	<id><![CDATA[]]></id>
	</image>
</images>

<product_option_values>
	<product_option_value>
	<id><![CDATA[]]></id>
	</product_option_value>
</product_option_values>
<product_features>
	<product_feature>
	<id><![CDATA[]]></id>
	<id_feature_value><![CDATA[]]></id_feature_value>
	</product_feature>
</product_features>
<tags>
	<tag>
	<id><![CDATA[]]></id>
	</tag>
</tags>
<stock_availables>
	<stock_available>
	<id><![CDATA[]]></id>
	<id_product_attribute><![CDATA[]]></id_product_attribute>
	</stock_available>
</stock_availables>
<attachments>
	<attachment>
	<id><![CDATA[]]></id>
	</attachment>
</attachments>
<accessories>
	<product>
	<id><![CDATA[]]></id>
	</product>
</accessories>
<product_bundle>
	<product>
	<id><![CDATA[]]></id>
	<id_product_attribute><![CDATA[]]></id_product_attribute>
	<quantity><![CDATA[]]></quantity>
	</product>
</product_bundle>
</associations>
<out_of_stock>1</out_of_stock></product>
</prestashop>
');
    echo curl_exec($ch);
    curl_close($ch);
```

### PrestaShop version(s) where the bug happened

8.0.0 beta1

### PHP version(s) where the bug happened

7.2.34

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | If we add a new product with WS and set unit-price tag with no value on it, we throw an exception for empty string in a `new DecimalNumber()`. This PR fix simply this error.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #29315
| Fixed ticket?     | Fixes #29315 
| Related PRs       |
| Sponsor company   |

FYI, with `?:` instead of `??` and for each PHP version supported by PrestaShop: 
```php
<?php
var_export (false ?? 'value2');   // false
var_export (true  ?? 'value2');   // true
var_export (null  ?? 'value2');   // value2
var_export (''    ?? 'value2');   // ""
var_export (0     ?? 'value2');   // 0

var_export (false ?: 'value2');   // value2
var_export (true  ?: 'value2');   // true
var_export (null  ?: 'value2');   // value2
var_export (''    ?: 'value2');   // value2
var_export (0     ?: 'value2');   // value2
```

### CODE REVIEW

File: classes/Product.php [hunk 1]
```diff
@@ -884,7 +884,7 @@ protected function updateUnitRatio(): void
     protected function fillUnitRatio(bool $ecotaxEnabled): void
     {
         // Update instance field
-        $unitPrice = new DecimalNumber((string) ($this->unit_price ?? 0));
+        $unitPrice = new DecimalNumber((string) ($this->unit_price ?: 0));
         $price = new DecimalNumber((string) ($this->price ?? 0));
         if ($ecotaxEnabled) {
             $price = $price->plus(new DecimalNumber((string) ($this->ecotax ?? 0)));
```
Comment (mflasquin) [inline classes/Product.php]:
```suggestion
        $price = new DecimalNumber((string) ($this->price ?: 0));
        if ($ecotaxEnabled) {
            $price = $price->plus(new DecimalNumber((string) ($this->ecotax ?: 0)));
```

**Review by mflasquin — CHANGES_REQUESTED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @boherm 

Thank you for your PR, I tested you PR and when you set an empty unit-price, It's works ! 
But when I set an empty price ( as you change it on the code ), that's return me an error. 

as you can see : 

[Untitled_ Apr 6, 2023 4_25 PM.webm](https://user-images.githubusercontent.com/100699445/230417482-efff0a55-d187-413b-9c15-f03ad6dfd46e.webm)

Thank you

**Comment by boherm** [comment]
Thanks for your review @AureRita!

We have a rule in WS to avoid to add a new product if `price` is empty, but it wasn't the case for `unit_price`.
This error showed in your video, isn't a PHP Exception but a WS error, so I think that is ok for price!

**Review by florine2623 — APPROVED** [review]
Hello @boherm ,

Thanks for the PR !

It is indeed fixed. With or without unit_price, the POST method for products works as expected 👍 


https://user-images.githubusercontent.com/16019289/230604582-5c1a90c1-cd0e-40b8-9b1b-bac3229f86d4.mov



It is QA ✅

**Comment by nicosomb** [comment]
Thank you @boherm !
