### PR TITLE
Take shop id into account when getting a language list for an order

### LINKED ISSUE #21817: Multistore - BO - Order page - All languages are available in the dropdown for Language in the Add new Order page
#### Describe the bug

Multistore is enabled.
We have 2 shops, for each shop, we have 1 different currency and 1 different language
In the BO > Add new Order page > All languages are available in the dropdown for Language

#### Steps to Reproduce

1. You must have 2 languages (English, French)
2. Enable Multistore context 
3. Create a new shop shop2
4. Edit languages (English is associated with the shop1 only) / (French is associated with shop2 only)
image
5. Go to BO > Order page > select shop2
6. Click add new Order
7. Choose a customer
8. In the cart section => see error (All languages are available in dropdown for Language)
image

PS: 1768 => ok
#### Additional information

* PrestaShop version: 1770rc1build4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | Current shop was not taken into account when getting the list of available languages
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21817
| How to test?  | See issue #21817 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22020)

**BC BREAK:**

`LanguageByIdChoiceProvider` 's interface was changed from `FormChoiceProviderInterface` to `ConfigurableFormChoiceProviderInterface`, as a consequence its `getOptions` method now takes an array of options as a parameter (default: empty array).

### CODE REVIEW

File: src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php [hunk 1]
```diff
@@ -40,11 +40,20 @@ final class LanguageByIdChoiceProvider implements FormChoiceProviderInterface
...
+    private $shopId;
+
+    /**
+     * LanguageByIdChoiceProvider constructor.
+     *
      * @param LanguageDataProvider $languageDataProvider
+     * @param int $shopId
      */
-    public function __construct(LanguageDataProvider $languageDataProvider)
+    public function __construct(LanguageDataProvider $languageDataProvider, int $shopId)
```
Comment (jolelievre) [inline src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: It's a BC break! Not only does it change the constructor of an existing class It completely changes its behavior because it will only return the language for a specific shop

In your use case you want to filter for one shop but it doesn't mean it's always used for a single shop

I see two alternatives you can change the interface `ConfigurableFormChoiceProviderInterface` so you can use an `$options` containing the shop_id (optional)
Or create a new provider altogether

**Review by jolelievre — DISMISSED** [review]

File: src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: I'm more in favor of using the ConfigurableFormChoiceProviderInterface to be consistent with other classes :)

Comment (matthieu-rolland) [reply src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: I'll do that ! I totally didn't think about the bc break...

**Comment by Progi1984** [comment]
@matthieu-rolland Unit tests are broken : https://travis-ci.com/github/PrestaShop/PrestaShop/obs/444245142#L651

File: src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php [hunk 2]
```diff
@@ -52,11 +54,12 @@ public function __construct(LanguageDataProvider $languageDataProvider)
      *
      * @return array
      */
-    public function getChoices()
+    public function getChoices(array $options = [])
     {
         $choices = [];
+        $shopId = !empty($options['shop_id']) ? $options['shop_id'] : false;
```
Comment (Progi1984) [inline src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]:
```suggestion
        $shopId = $options['shop_id'] ?? false;
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

File: src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php (hunk 2 above)
Comment (matthieu-rolland) [reply src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: `??` is like doing an `'isset'`, if for some reason `$options['shop_id']` is set with let's say an empty string, it would be set as such, I prefer setting false as a value in all the cases where `empty` is true.  (I did update this part though)

Comment (matthieu-rolland) [inline src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: I should have done this actually:

```suggestion
        $shopId = !empty((int) $options['shop_id']) ? $options['shop_id'] : false;
```

Comment (Progi1984) [reply src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: Wrong : it checks that the value is not `false`

https://www.designcise.com/web/tutorial/whats-the-difference-between-null-coalescing-operator-and-ternary-operator-in-php

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

File: src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php (hunk 2 above)
Comment (matthieu-rolland) [reply src/Core/Form/ChoiceProvider/LanguageByIdChoiceProvider.php]: `$shopId = $options['shop_id'] ?? false;` 

is equivalent to:

`$shopId = isset($options['shop_id']) ? $options['shop_id'] : false;`

It's actually written in your article :D

`expr1 ?? expr2;` is actually the same as the following:
`return (isset($x) ? $x : $y);`

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

I have an exception following these steps:

1. Go to BO > International > localization > See error

image


Thanks!

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
@matthieu-rolland All good, however since we change the interface and the prototype of the function it should be documented as a BC break (even if it's a small and acceptable one)
You just need to update the PR description for documentation

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1EuPWz3uMmSCm2yvWIlGhaEcT9gd1zH_J/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @khouloudbelguith
