### PR TITLE
Fix ID replacement in urls generated by symfony

### LINKED ISSUE #11621: Features - In the Product page, the Pre-defined value is not enabled - The Project folder name begin with numbers
**Describe the bug**
This issue occurs only when the Project folder **begin** with numbers for example 1750rc1.
In the other case, there are no errors.

**To Reproduce**
1. Extract the file zip of prestashop_1.7.5.0-rc.1+build.1.zip
2. Rename it to 1750rc1
3. Install the shop => OK => Installation done successfully
4. Create a product
5. In the product page, Click on Add a feature
6. Choose a color feature
7. the Pre-defined value is not enabled / error in the console 

**Screenshots**
image
image

In the 1.7.4.4 => OK.

**Additionnal information**
PrestaShop version: 1.7.5.0RC1
PHP version: 7.1

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | When PrestaShop was installed in a folder starting with numbers (ex: `1750rc1`) The url replacement used to add feature did not work correctly this resulting in a 404.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11621
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11644)

### CODE REVIEW

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 1]
```diff
@@ -400,7 +400,7 @@ var featuresCollection = (function() {
 
         if('' !== $(this).val()) {
           $.ajax({
-            url: $(this).attr('data-action').replace(/\/\d+((?=\?.*))?/, '/' + $(this).val()),
+            url: $(this).attr('data-action').replace(/\/\d+(?!.*\/\d+)((?=\?.*))?/, '/' + $(this).val()),
```
Comment (eternoendless) [inline admin-dev/themes/default/js/bundle/product/form.js]: Maybe this part could be factored into a method with a more semantic meaning?

```js
doSomethingThatShouldBeExplainedHere = function(foo, bar) {
  return foo.replace(/\/\d+(?!.*\/\d+)((?=\?.*))?/, '/' + bar)
}
```

Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js]: alright

**Review by PierreRambaud — APPROVED** [review]
It's a duplicate in the same file, but this file will be refactor later because of its complexity, and because it's not in es6 :)

**Comment by mickaelandrieu** [comment]
LGTM, good job everyone!
