### PR TITLE
Fix labels display computing

### LINKED ISSUE #9959: [BOOM-3364] Bandeau exclusivité web
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3364).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Thu, 29 Jun 2017 17:58:43 +0200

<p>Le bandeau exclusivité web masque les déclinaisons</p>
        
* How to reproduce the issue ?

Create or update a product and check &quot;Web Only&quot; in Product Option. See FO.

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix miniature's label display (bad offset computing)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9959
| How to test?  | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13407)

### CODE REVIEW

File: themes/classic/_dev/js/components/product-miniature.js [hunk 1]
```diff
@@ -28,24 +28,34 @@ export default class ProductMinitature {
...
+      //Flags other than on-sale, discount and online-only (which have all their way to display)
+      const flagElems = $(element).find('.product-flag:not(.on-sale):not(.discount):not(.online-only)');
 
-        if ($(element).find('.pack').length) {
-          $(element).find('.pack').css('top', discountElems.height() * 3 + FLAG_MARGIN);
-        }
+      var flagsTop = FLAG_MARGIN;
+      var discountTop = FLAG_MARGIN;
+      if (onSaleElems.length) {
+        discountTop = parseFloat(onSaleElems.outerHeight()) + FLAG_MARGIN;
```
Comment (PierreRambaud) [inline themes/classic/_dev/js/components/product-miniature.js]: We're playing with pixel, better to 
```suggestion
        discountTop = parseInt(onSaleElems.outerHeight(), 10) + FLAG_MARGIN;
```

Comment (jolelievre) [reply themes/classic/_dev/js/components/product-miniature.js]: Actually it's a rest of former code, I think we can safely remove the `parse*` part

File: themes/classic/_dev/js/components/product-miniature.js [hunk 2]
```diff
@@ -28,24 +28,34 @@ export default class ProductMinitature {
...
+      if (discountElems.length) {
+        flagsTop = discountTop + discountElems.outerHeight() + FLAG_MARGIN;
+        //Discount flag is actually in product-description div so it needs a negative top value
+        discountElems.css('top', discountTop + -$(element).find('.thumbnail-container').outerHeight() + $(element).find('.product-description').outerHeight());
       }
 
+      //Now display flags one above the other
+      flagElems.each((index, flag) => {
+        $(flag).css('top', flagsTop);
+        $(flag).css('margin-top', 0);
```
Comment (Quetzacoalt91) [inline themes/classic/_dev/js/components/product-miniature.js]: Should we define this rule in a CSS file instead?

Comment (jolelievre) [reply themes/classic/_dev/js/components/product-miniature.js]: Actually there is already a non 0 rule in the css, but I didn't want to modify it This way if javascript has problems or in pages where this code doesn't run the css rule is still there as a fallback
Maybe I should add a comment however here?

Comment (Quetzacoalt91) [reply themes/classic/_dev/js/components/product-miniature.js]: Well, if it is already in the css file, I see no reason to redefine it here again.

This could have unexpected consequences for child themes, who may prefer to set their label on another place of the website. If your changes work even without this line, I would rather remove it.

Comment (jolelievre) [reply themes/classic/_dev/js/components/product-miniature.js]: That's the thing it doesn't work correctly without this line, because the margin from the css offsets the elements. Since the `top` value is computed by the js the `margin-top` is not really useful any more.
I can remove the line from the css but it could also have consequences on a child theme no? Honestly I don't even understand why this is performed through javascript, a full css method would probably be better but I only fixed the existing one. Maybe dropping this js computing with a css layout would be better.

Comment (eternoendless) [reply themes/classic/_dev/js/components/product-miniature.js]: It's best just to add a class and avoid setting styles as much as possible

Comment (jolelievre) [reply themes/classic/_dev/js/components/product-miniature.js]: I agree, I'll rework this feature to be full css then and drop the javascript as much as possible.
But as special product flags may have very different looks some js might still be necessary

Comment (jolelievre) [reply themes/classic/_dev/js/components/product-miniature.js]: Alright! no more js positioning And I also cleaned CSS a little as the product-flag were defined in two places without valid reason (for product page and product list page)

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
@jolelievre you should probably rebase you're PR before the QA team reviews it.

**Comment by jolelievre** [comment]
> @jolelievre you should probably rebase you're PR before the QA team reviews it.

@Quetzacoalt91 Thanks, it's done!

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by matks** [comment]
Thank you @jolelievre
