### PR TITLE
Optimizing queries for checking address existence

### LINKED ISSUE #26754: Too many queries to test if address_id exists
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When there is a product in the cart and I'm not logged in, Prestashop is repeating this query 30 times

    SELECT SQL_NO_CACHE `id_address`  FROM ps_address a  WHERE a.`id_address` = 0 LIMIT 1

Additionally the logic is suspect, because the query does not check if the address is marked as deleted or if it is active. This would be necessary, since the addresses are soft-deleted in the address table.

The screenshot are from Profiling mode on a product page. Checking the individual queries in Stopwatch SQL shows that all queries are exactly the same.

### Expected behavior

Never check if address with `id_address = 0` exists. It must never exist.
Check only once if an address exists, remember the answer.
Even better: good execution logic would test only once for the existence of the address saved in the cart.

To-do:

- [x] #28321

- [ ]  Investigate the core of the issue to understand: why we are doing so much queries (related to how we store the adress in the cache of the cart) ?

### Steps to reproduce

1. Enable Profiling mode
3. Add a product to your cart
4. Scroll down to query doubles, you'll notice that there is 30x the same query on the table `address`.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #28321: Improvement the number of queries with quickwins !
(For the non logged mode) Check if the PR of @eternoendless #27406 is always valid.<br /><br/>(For the logged mode) <br/>* Enable Profiling mode<br/>* Connect as a user<br/>* Add a product to your cart<br/>* Scroll down to query doubles, you'll notice that there is 30x the same query on the table address (and not with this PR)<br><br>**BEFORE**<br>image<br><br>**AFTER**<br>image

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Optimizing queries for checking address existence
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#28321](https://github.com/PrestaShop/PrestaShop/issues/28321)
| How to test?      | (For the non logged mode) Check if the PR of @eternoendless #27406 is always valid.<br /><br/>(For the logged mode) <br/>* Enable Profiling mode<br/>* Connect as a user<br/>* Add a product to your cart<br/>* Scroll down to query doubles, you'll notice that there is less the same query on the table address than before this PR<br><br>**BEFORE**<br>image<br><br>**AFTER**<br>image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28232)

### CODE REVIEW

**Comment by Hlavtox** [comment]
25 queries after? That's still insane, it must be one query bro. Nothing like this is happening on 1.7.6.

**Comment by Progi1984** [comment]
@Hlavtox We can't optimize without breaking a lot of things and it's not possible in a patch version.

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/Address.php [hunk 1]
```diff
@@ -232,6 +236,11 @@ public function delete()
         if (!$this->isUsed()) {
             $this->deleteCartAddress();
 
+            // Update the cache
+            if (isset(self::$addressExists[$this->id])) {
+                self::$addressExists[$this->id] = false;
+            }
```
Comment (PierreRambaud) [inline classes/Address.php]:
```suggestion
            if (isset(static::$addressExists[$this->id])) {
                static::$addressExists[$this->id] = false;
            }
```

Avoid the usage of `self` since this class can be extended and the atribute is protected

File: classes/Address.php [hunk 2]
```diff
@@ -437,21 +446,28 @@ public static function getCountryAndState($id_address)
...
-    public static function addressExists($id_address)
+    public static function addressExists($id_address, bool $useCache = false)
     {
         if ($id_address <= 0) {
             return false;
         }
 
-        return (bool) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
+        if ($useCache && isset(self::$addressExists[$id_address])) {
+            return self::$addressExists[$id_address];
```
Comment (PierreRambaud) [inline classes/Address.php]:
```suggestion
        if ($useCache && isset(static::$addressExists[$id_address])) {
            return static::$addressExists[$id_address];
```

same as preivous

File: classes/Address.php [hunk 3]
```diff
@@ -437,21 +446,28 @@ public static function getCountryAndState($id_address)
...
+        }
+
+        self::$addressExists[$id_address] = (bool) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
```
Comment (PierreRambaud) [inline classes/Address.php]:
```suggestion
        static::$addressExists[$id_address] = (bool) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
```

File: classes/Address.php [hunk 4]
```diff
@@ -437,21 +446,28 @@ public static function getCountryAndState($id_address)
...
      *
      * @param int $id_address Address id
+     * @param bool $useCache Use Cache for optimizing queries
      *
      * @return bool The address exists
      */
-    public static function addressExists($id_address)
+    public static function addressExists($id_address, bool $useCache = false)
     {
         if ($id_address <= 0) {
```
Comment (PierreRambaud) [inline classes/Address.php]:
```suggestion
        if ((int) $id_address <= 0) {
```

Out of the scope but can be cool to have a better chjeck

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
A little comment about the usage of self

File: classes/Address.php (hunk 3 above)
Comment (Progi1984) [reply classes/Address.php]: Fixed

File: classes/Address.php (hunk 2 above)
Comment (Progi1984) [reply classes/Address.php]: Fixed

File: classes/Address.php (hunk 4 above)
Comment (Progi1984) [reply classes/Address.php]: Fixed

File: classes/Address.php (hunk 1 above)
Comment (Progi1984) [reply classes/Address.php]: Fixed

**Comment by Progi1984** [comment]
@PierreRambaud & @matthieu-rolland Feedbacks adressed. :smile:

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Progi1984 

I have checked this PR. The issue is not fixed using the same steps described in the issue.

1. Enable Profiling mode
2. Add a product to your cart
3. See error >> Scroll down to query doubles ==> There is **30x** the same query on the table address.

image

https://user-images.githubusercontent.com/92912932/163819720-d6bff6db-9fde-4ae2-b683-640bb1742223.mp4



Could you please check it ?

Thanks !

**Comment by Progi1984** [comment]
@HanaRebaiQA As you can see it's an optimization. We can't remove all doubles without refactoring all the front and in a patch version, it's not possible.

**Comment by Hlavtox** [comment]
It shouldn't have slipped in the core the first time, we are making prestashop slower and slower with each version

**Comment by matks** [comment]
> It shouldn't have slipped in the core the first time

On average, sixty to eighty Pull Requests are merged in the project each week. We try to check everything, we try to verify everything and make sure that each addition to the project will bring only benefits no drawbacks but we'll never reach 100% issues-busting. We have to accept that bugs, performance issues, problems will slip by. Some will be catched when we do a beta release, either by the project QA team or by contributors tests. Some will not be catched and will be reported from live shops. We try to reduce this number as much as possible, within our capabilities because we are not a big team.

I know QA team is looking to expand its capabilities to performance monitoring :) it's a topic for 2022 / 2023 I believe. But the software is so big, anything started now will only show benefits in some months. The current QA campaign running every night for example has been started 1 or 2 years ago and is now a great benefit to us, but it had to start at some point. The best is in front of us, not behind.

> we are making prestashop slower and slower with each version

Some say that the only way to keep a software fast is not to modify it anymore 😄 I think I quoted it before: [software has bugs, it's normal](https://m.signalvnoise.com/software-has-bugs-this-is-normal/). "The only reliable, widely used way to ensure impeccable software quality is to write less software that does less stuff, and then spend eons honing that tiny lot." Unfortunately PrestaShop is growing so it means more bugs, more issues coming. Because it lives. Although the code you, me, any contributor will bring to the software might bring issues, it also bring values it's a good thing if at the end of the day we created more software value than we removed. "Useful software can be ridden with bugs, yet remain highly valuable."

> 25 queries after? That's still insane, it must be one query bro. Nothing like this is happening on 1.7.6.

Just like Progi said we are very careful about what we add in patch versions. In the past, we used to deliver more items inside patch versions, bigger items. What happened is we also delivered bigger bugs! So frustrated users reported that, when they upgrade from one 1.7 version to another version although it was a patch version, their shop was in a worse state than before.

In order to avoid that we decided to reduce strictly the scope of code delivered through patch versions, so that we only deliver surgical bugfixes, built specifically to be as safe as possible. We keep higher risk improvements for minor or major versions where the quality assurance is bigger with beta releases and large test campaign.

We are trying to balance how much value we deliver with how much risk we take, because each addition to the PrestaShop project can bring a critical regression, even though we have a strict quality procedure as you know. It's sometimes frustrating 😬 we undergo such a burden to go through code review and QA testing (you know sometimes it's hard to handle) and yet bugs slip by... but this is the equilibrium we have found so far and it seems to reach the goal we had: patch releases as safe as possible, that users can upgrade to confidently.

We wish we could do so better 😄 but this is the best we have been able to do, collectively, as of today. Maybe in 2022 or 2023 we'll find a better equilibrium.

File: classes/Address.php [hunk 5]
```diff
@@ -104,9 +104,13 @@ class AddressCore extends ObjectModel
 
     /** @var array Zone IDs cache */
     protected static $_idZones = [];
+
     /** @var array Country IDs cache */
     protected static $_idCountries = [];
 
+    /** @var array<int, bool> Store if an adress ID exists */
+    protected static $addressExists = [];
```
Comment (jolelievre) [inline classes/Address.php:112]: You need to clean this in the `resetStaticCache` method or it will potentially mess with the tests

File: classes/Address.php [hunk 6]
```diff
@@ -232,6 +236,11 @@ public function delete()
         if (!$this->isUsed()) {
             $this->deleteCartAddress();
 
+            // Update the cache
+            if (isset(static::$addressExists[$this->id])) {
```
Comment (jolelievre) [inline classes/Address.php:247]: You could also update this in the `add` and `update` methods if you want to optimize a little bit more

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @Progi1984 

Just a suggestion, and the `resetStaticCache` method MUST be updated to clean this new cache

File: classes/Address.php (hunk 5 above)
Comment (Progi1984) [reply classes/Address.php:112]: Correct. Thanks

File: classes/Address.php (hunk 6 above)
Comment (Progi1984) [reply classes/Address.php:247]: Done

**Comment by Progi1984** [comment]
@jolelievre & @matks It's fixed

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by atomiix — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Progi1984 

I have checked again this PR. The issue seems to not be fixed.

**In the non logged mode :** The query is not exists

This is the query : 

```
SELECT SQL_NO_CACHE `id_address`
FROM hana_address a
WHERE a.`id_address` = 7 LIMIT 1
```

**In the logged mode :** The query still exists : 

- Before Add the product in cart (0 times) 
**- In Add the product (only one product) in cart process (37 doubles)** :x: 
image

**- In Order the product process (34 doubles)** :x: 
image

- In Order confirmation page (19 times)


https://user-images.githubusercontent.com/92912932/170472878-2782a6d9-d9b6-41f5-87fd-bc0023158c73.mp4




Could you please check again ?

Thank you!

**Comment by kpodemski** [comment]
Hi @Progi1984 

It's a static cache why don't we set `true` by default? that should help

**Comment by Progi1984** [comment]
@kpodemski I don't change to `true` for avoiding a lot of behavior changes in code. It can't be defined to `true` in develop branch.

@HanaRebaiQA I know it remains a lot of calls and I can't remove all of it. I just optimize a little all these calls. I can't remove all doubles without refactoring all the front and in a patch version, it's not possible.

**Review by HanaRebaiQA — APPROVED** [review]
Hello @Progi1984 

Thanks for your feedback. Yes! when i checked the behavior **without PR on 178x** when profiling mode is enabled. There is an optimization of the number of queries with this PR compared to without PR

**Number of queries Without PR** : 

_In the non logged mode :_ The query is not exists

This is the query : 

```
SELECT SQL_NO_CACHE `id_address`
FROM hana_address a
WHERE a.`id_address` = 7 LIMIT 1
```


_In the logged mode :_

- Before Add the product in cart (**32 times**) :x:
- In Add the product (only one product) in cart process (**50 doubles**) :x:
- When add the product in cart ans search in all FO : (**32 doubles**) :x:
image

- In Order the product process (**47 doubles**) :x:
- In Order confirmation page (**24 times**) :x:

Here is a screen-record which details the number of queries without PR in each action : 


https://user-images.githubusercontent.com/92912932/173097154-4714fa0a-f068-49db-b2b9-ff5308c66c69.mp4

**Number of queries With PR** : 

_In the non logged mode :_ The query is not exists :heavy_check_mark: 

_In the logged mode :_

- Before Add the product in cart (**0 times**) :heavy_check_mark: 
- In Add the product (only one product) in cart process (**37 doubles**) :heavy_check_mark: 
- When add the product in cart ans search in all FO : (**25 doubles**) :heavy_check_mark: 
image

- In Order the product process (**34 doubles**) :heavy_check_mark: 
- In Order confirmation page (**19 times**) :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/170472878-2782a6d9-d9b6-41f5-87fd-bc0023158c73.mp4


I have checked also :  

- With different languages : OK 
- With multistore : OK 
- Automated tests : OK 

So, it's QA :heavy_check_mark: 

Thank you!

**Comment by Progi1984** [comment]
Thanks @HanaRebaiQA for all discussions on this issue/PR and for the QA (of course :rofl:).

**Comment by HanaRebaiQA** [comment]
You are welcome @Progi1984 and thanks for you and for your patience:smile:

**Comment by ProteanCode** [comment]
I will ask for a workaround there, or debate if this has quite heavy impact

If MySQL will be queried for a result of that query ie. 10 times during the request, won't cached results be returned by default?

I think that sequential calls to a specific MySQL query are cached by default. The TTL of the cache is unknown to me, but iirc it just exists
