### PR TITLE
Do not clear system cache on bulk install,remove,upgrade module

### LINKED ISSUE #29121: Cache is cleared for every module when you bulk remove modules instead of only once
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] #29179

### Describe the bug and add screenshots

In the module manager, when you remove multiple modules through bulk action, the cache is cleared for each modules instead of being clearing only once at the end of the process.

### Expected behavior

The cache should be cleared only once at the end of the process.

### Steps to reproduce

As this bug is technical, I think only a dev can validate it:

1. Set a break point to [the clear cache method](https://github.com/PrestaShop/PrestaShop/blob/4a34c76eb9413ac760f37c75ba0dbe6213fd9824/src/Core/Module/EventSubscriber.php#L79)
2. Go to module manager
3. Select multiple modules
4. Click on the bulk action "uninstall"
5. See that the breakpoint is called multiple times

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | In the module manager, when you install,remove or upgrade multiple modules through bulk action, the cache is cleared for each modules instead of being clearing only once at the end of the process.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29121
| Related PRs       | 
| How to test?      | See #29121
| Possible impacts? |

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php [hunk 1]
```diff
@@ -209,10 +209,17 @@ public function moduleAction(Request $request)
 
         try {
             $args = [$module];
-            if ($action === 'uninstall') {
+            if ($action === ModuleAdapter::ACTION_UNINSTALL) {
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:212]: 👍 much better bravo

File: src/PrestaShopBundle/Event/ModuleManagementEvent.php [hunk 2]
```diff
@@ -43,13 +43,21 @@ class ModuleManagementEvent extends Event
...
     }
 
     public function getModule()
     {
         return $this->module;
     }
+
+    public function getSystemClearCache()
+    {
+        return $this->systemClearCache;
```
Comment (matks) [inline src/PrestaShopBundle/Event/ModuleManagementEvent.php:63]: Is this something we could unit test 😄 ?

File: src/Core/Module/ModuleManager.php [hunk 3]
```diff
@@ -65,6 +65,9 @@ class ModuleManager implements ModuleManagerInterface
     /** @var Filesystem */
     private $filesystem;
 
+    /** @var bool */
+    private $systemClearCache;
```
Comment (kpodemski) [inline src/Core/Module/ModuleManager.php]:
```suggestion
    private $systemClearCache = true;
```

File: src/Core/Module/ModuleManager.php [hunk 4]
```diff
@@ -82,6 +85,7 @@ public function __construct(
         $this->translator = $translator;
         $this->eventDispatcher = $eventDispatcher;
         $this->hookManager = $hookManager;
+        $this->systemClearCache = true;
```
Comment (kpodemski) [inline src/Core/Module/ModuleManager.php]:
```suggestion
```

File: src/Core/Module/ModuleManager.php [hunk 5]
```diff
@@ -369,6 +373,11 @@ private function assertIsInstalled(string $name): void
 
     private function dispatch(string $event, ModuleInterface $module): void
     {
-        $this->eventDispatcher->dispatch(new ModuleManagementEvent($module), $event);
+        $this->eventDispatcher->dispatch(new ModuleManagementEvent($module, $this->systemClearCache), $event);
+    }
+
+    public function disableSystemClearCache()
```
Comment (kpodemski) [inline src/Core/Module/ModuleManager.php]:
```suggestion
    public function disableSystemClearCache(): void
```

File: src/PrestaShopBundle/Event/ModuleManagementEvent.php [hunk 6]
```diff
@@ -43,13 +43,21 @@ class ModuleManagementEvent extends Event
...
         $this->module = $module;
+        $this->systemClearCache = $systemClearCache;
     }
 
     public function getModule()
     {
         return $this->module;
     }
+
+    public function getSystemClearCache()
```
Comment (kpodemski) [inline src/PrestaShopBundle/Event/ModuleManagementEvent.php]:
```suggestion
    public function getSystemClearCache(): bool
```

File: src/PrestaShopBundle/Event/ModuleManagementEvent.php [hunk 7]
```diff
@@ -43,13 +43,21 @@ class ModuleManagementEvent extends Event
 
     private $module;
 
-    public function __construct(ModuleInterface $module)
+    private $systemClearCache;
```
Comment (kpodemski) [inline src/PrestaShopBundle/Event/ModuleManagementEvent.php:48]:
```suggestion
    /** @var bool */
    private $systemClearCache;
```

File: src/PrestaShopBundle/Event/ModuleManagementEvent.php (hunk 2 above)
Comment (mflasquin) [reply src/PrestaShopBundle/Event/ModuleManagementEvent.php:63]: I will check :)

Comment (mflasquin) [reply src/PrestaShopBundle/Event/ModuleManagementEvent.php:63]: I think we don't have to uni test this class because it's like a dto

**Review by matks — COMMENTED** [review]
I still want tests 😄

File: src/PrestaShopBundle/Event/ModuleManagementEvent.php (hunk 2 above)
Comment (matks) [reply src/PrestaShopBundle/Event/ModuleManagementEvent.php:63]: My bad you're right 👍

**Review by matks — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by matks** [comment]
I test this

**Review by matks — CHANGES_REQUESTED** [review]
Hello @mflasquin I tested the Pull Request. It does not seem to work 🤔 when I uninstall multiple modules using bulk uninstall (see screenshot), I can see the cache is clear multiple times, once for every module.

I analysed the code, it seems
```
$systemCacheClearEnabled = filter_var(
    $request->request->get('actionParams', [])['cacheClearEnabled'] ?? true,
    FILTER_VALIDATE_BOOLEAN
);
```
always return true, so your disabling logic is not executed.

I then looked at the ajax requests sent by the 'Module Manager' page: they only contain one POST param, it is the _token.

When I read again the Pull Request, I feel like it is missing something; you added some logic so that cache is not _always_ cleared but I think you also need to modify the frontend logic, to make sure that there is one ajax request (the last) that clears the cache, but the previous ajax requests do not clear the cache. Is this relevant?

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Well, we tested together with @mflasquin and ... this time it works. I think maybe my assets were outdated.
