### PR TITLE
Fix multiple cart rules calculation

### LINKED ISSUE #16673: The total is not well calculated with free gift
**Describe the bug**
After fixing this issue: https://github.com/PrestaShop/PrestaShop/issues/11722 in the develop branch.
2 uses cases are not ok in the develop branch as reported here: https://github.com/PrestaShop/PrestaShop/issues/11722#issuecomment-561220896
Issue 1:
Create the following rules:

- Rule 1
Amount discount:
image

- Rule 2
image

- Rule 3
Free gift
image

Cart:
image

Issue 2:
- Change the first rule:
image

- Discount is higher than the amount
image

In the PS1.7.6.2, the total is well calculated

**Additional information**
PrestaShop version: develop
PHP version: 7.1

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This fix discounts calculation with multiple cart rules
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16673
| How to test?  | See #16673

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16724)

### CODE REVIEW

File: src/Core/Cart/Calculator.php [hunk 1]
```diff
@@ -192,6 +208,19 @@ public function getDiscountTotal()
             $amount = $amount->add($cartRule->getDiscountApplied());
         }
 
+        $totalWithoutDiscount = $this->getRowTotalWithoutDiscount();
+        $initialShipping = $this->getFees()->getInitialShippingFees();
+        $finalShipping = $this->getFees()->getFinalShippingFees();
+
+        if (null !== $initialShipping && null !== $finalShipping) {
```
Comment (jolelievre) [inline src/Core/Cart/Calculator.php]: I'm not sure I get this part Part of the shipping is added, the other one is subsided.. Which one is what? Maybe this justifies a comment

Comment (jolelievre) [reply src/Core/Cart/Calculator.php]: Since you compute the whole discount separately, is it still useful to `applyFlatDiscount` on rows during the computation process?

**Review by jolelievre — COMMENTED** [review]
Is the issue https://github.com/PrestaShop/PrestaShop/issues/11722 still fixed with your modification? Is there a behat test dedicated to this previous issue?

File: src/Core/Cart/Calculator.php (hunk 1 above)
Comment (atomiix) [reply src/Core/Cart/Calculator.php]: > I'm not sure I get this part Part of the shipping is added, the other one is subsided.. Which one is what? Maybe this justifies a comment

You're right, I'll add a comment explaining this part!

>Since you compute the whole discount separately, is it still useful to `applyFlatDiscount` on rows during the computation process?

I think it's not useful but I'm pretty sure that getting rid of it will introduce a BC break?

Edit: Actually, it's needed because otherwise you can't keep track of an already applied discount. Imagine 2 discounts of 50% each with 2 different priorities. If we do not keep track of the already applied discount the cart total will be 0€ instead of 50% of 50% of the amount.

**Comment by atomiix** [comment]
> Is the issue #11722 still fixed with your modification? Is there a behat test dedicated to this previous issue?

Yes the issue is still fixed with my modifications. The behat tests I added handle that case too.

File: src/Core/Cart/Calculator.php (hunk 1 above)
Comment (jolelievre) [reply src/Core/Cart/Calculator.php]: Ok for `applyFlatDiscount`

For the shipping part I didn't get it at first but with your comment it seems logical, but I think we could simplify this an remove the comment with this:
```php
if (null !== $initialShipping && null !== $finalShipping) {
    $shippingDiscount = (new AmountImmutable())->add($initialShipping)->sub($finalShipping);
    $totalWithoutDiscount = $totalWithoutDiscount->sub($shippingDiscount);
}
```
or to avoid the intermediate variables:
```php
if (null !== $this->getFees()->getInitialShippingFees() && null !== $this->getFees()->getFinalShippingFees()) {
    $shippingDiscount = (new AmountImmutable())
                         ->add($this->getFees()->getInitialShippingFees())
                         ->sub($this->getFees()->getFinalShippingFees())
    ;
    $totalWithoutDiscount = $totalWithoutDiscount->sub($shippingDiscount);
}
```
What do you think?

Comment (atomiix) [reply src/Core/Cart/Calculator.php]: Just updated the code 😉

File: src/Core/Cart/Calculator.php [hunk 2]
```diff
@@ -192,6 +208,20 @@ public function getDiscountTotal()
...
         }
 
+        $totalWithoutDiscount = $this->getRowTotalWithoutDiscount();
+
+        if (null !== $this->getFees()->getInitialShippingFees() && null !== $this->getFees()->getFinalShippingFees()) {
+            $shippingDiscount = (new AmountImmutable())
+                ->add($this->getFees()->getInitialShippingFees())
+                ->sub($this->getFees()->getFinalShippingFees())
+            ;
+            $totalWithoutDiscount = $totalWithoutDiscount->add($shippingDiscount);
```
Comment (jolelievre) [inline src/Core/Cart/Calculator.php]: Shouldn't it be a substraction here since it's a discount?

Comment (jolelievre) [reply src/Core/Cart/Calculator.php]: Or maybe it should be added to `$amount` ? To have the addition of product discount plus shipping discount?
By the way does `$totalWithoutDiscount` already contains shipping fees?

Comment (atomiix) [reply src/Core/Cart/Calculator.php]: Actually it's the rest of the shipping discount so it should be added. Maybe I should rename the `$shippingDiscount`to better reflect what this variable is?

Comment (atomiix) [reply src/Core/Cart/Calculator.php]: As seen with you on Slack, I changed the variable name to better understand that part

File: src/Core/Cart/Calculator.php [hunk 3]
```diff
@@ -150,10 +150,11 @@ public function getTotal($ignoreProcessedFlag = false)
 
         $amount = new AmountImmutable();
         foreach ($this->cartRows as $cartRow) {
-            $rowPrice = $cartRow->getFinalTotalPrice();
+            $rowPrice = $cartRow->getInitialTotalPrice();
```
Comment (jolelievre) [inline src/Core/Cart/Calculator.php]: I think you can use `getRowTotalWithoutDiscount` here instead of the loop

File: src/Core/Cart/Calculator.php [hunk 4]
```diff
@@ -150,10 +150,11 @@ public function getTotal($ignoreProcessedFlag = false)
...
             $amount = $amount->add($rowPrice);
         }
-        $shippingFees = $this->fees->getFinalShippingFees();
+        $amount = $amount->sub($this->getDiscountTotal());
+        $shippingFees = $this->fees->getInitialShippingFees();
```
Comment (jolelievre) [inline src/Core/Cart/Calculator.php:153]: So if you add `getInitialShippingFees` when is the shipping discount applied? Also I don't know what wrapping fees are but should it be considered when computing the max authorized discount?

Comment (jolelievre) [reply src/Core/Cart/Calculator.php:153]: mmm, my bad it should already be inside the total discount! forget this comment

**Review by jolelievre — APPROVED** [review]
Nice job @atomiix

File: src/Core/Cart/Calculator.php [hunk 5]
```diff
@@ -148,12 +148,9 @@ public function getTotal($ignoreProcessedFlag = false)
...
 
-        $amount = new AmountImmutable();
-        foreach ($this->cartRows as $cartRow) {
-            $rowPrice = $cartRow->getFinalTotalPrice();
-            $amount = $amount->add($rowPrice);
-        }
-        $shippingFees = $this->fees->getFinalShippingFees();
+        $amount = $this->getRowTotalWithoutDiscount();
+        $amount = $amount->sub($this->getDiscountTotal());
+        $shippingFees = $this->fees->getInitialShippingFees();
```
Comment (arouiadib) [inline src/Core/Cart/Calculator.php:153]: Hi Thomas, could you please explain  why using `getInitialShippingFees()` here instead of `getFinalShippingFees`? using  `getFinalShippingFees` makes avoiding [#9586 ](https://github.com/PrestaShop/PrestaShop/issues/9586)(at least).

**Comment by khouloudbelguith** [comment]
Hi,

We have issues could be fixed with this PR:
-https://github.com/PrestaShop/PrestaShop/issues/16673#issuecomment-570246339
-https://github.com/PrestaShop/PrestaShop/issues/9586#issuecomment-571114824 (regression compared to PS1.7.6.2)

Thanks!

**Comment by Progi1984** [comment]
Thanks @atomiix
