### PR TITLE
Taking into account legacy public actions in Symfony layout

### LINKED ISSUE #35359: AdminSearch external index cron URL is no longer reachable when unlogged
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the back office go to Shop Parameters > Search
Here you'll see information explaining how to setup an cron based on a callable URL:
Capture d’écran 2024-02-14 à 16 17 41

This URL should therefore be callable even when you are not logged in to your back office, it can be tested by using a browser with private navigation as well.

With the Symfony layout enabled this URL is no longer callable and is redirected to the login page.

https://github.com/PrestaShop/PrestaShop/assets/16019289/1188f503-56f5-4056-8ed4-6fe266d8447b

### Expected behavior

I should be able to call the search indexation URL even if I'm not logged in (it works with legacy layout but not with Symfony layout). We need to find either a solution to make it work as is with Symfony layout or at least to find how the controller could be adapted to skip the global token validation and handle its own internal validation separately.

- [ ] Investigate to find a clean fix and without impacting the modules ecosystem

### Steps to reproduce

1. Make sure the Symfony layout is enabled in feature flags
2. Go to Shop Parameters > Search
3. Copy the search indexation URL and call it in a browser with private navigation (or any other way to call it without being logged in to the back office)
4. The URL should be callable, no redirection to the login page, a white content should appear since the controller returns no content but the call should be a success 200

### PrestaShop version(s) where the bug happened

9.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We need to add a check in the Symfony listeners for anonymous requests from legacy controllers. I also removed the part recovering the content of the content variable of the legacy controllers, which added an unwanted rendering. To make this possible, we initialize the legacy controller in the LegacyRouterChecker Class, which is responsible for creating attributes that will later be useful in the listener Contexts and the LegacyController. This had side effects on the initialization of contexts, which were improperly initialized in the listeners and then overridden during initialization in the LegacyController. Therefore, we had to adapt the listeners and their priorities by duplicating them (listeners for the Symfony layout and listeners for the legacy layout).
| Type?             | bug fix
| Category?         | BO 
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | See  #35359
| UI Tests          | Symfony: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/8802453146 / Legacy: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/8802455158
| Fixed issue or discussion?     | Fixes #35359
| Related PRs       | -
| Sponsor company   | -

**BC breaks**
Method `AdminController->isAnonymousAllowed` is now `public`

### CODE REVIEW

**Review by boherm — DISMISSED** [review]

File: src/Core/Context/LegacyControllerContextBuilder.php [hunk 1]
```diff
@@ -88,6 +88,10 @@ public function build(): LegacyControllerContext
 
     public function buildLegacyContext(): void
     {
+        if ($this->contextStateManager->getContext()->controller) {
```
Comment (jolelievre) [inline src/Core/Context/LegacyControllerContextBuilder.php:93]:
```suggestion
        // In legacy pages the AdminController class already sets the context's controller, which is a more accurate
        // candidate than our facade meant for backward compatibility, so we leave it untouched
        if ($this->contextStateManager->getContext()->controller) {
```

File: src/PrestaShopBundle/EventListener/Admin/Context/ShopContextListener.php [hunk 2]
```diff
@@ -92,9 +94,15 @@ private function getConfiguredDefaultShopId(): int
         return (int) $this->configuration->get('PS_SHOP_DEFAULT', null, ShopConstraint::allShops());
     }
 
-    private function getMultiShopConstraint(): ShopConstraint
+    private function getMultiShopConstraint(Request $request): ShopConstraint
     {
         $shopConstraint = ShopConstraint::allShops();
+        $isAllShopContext = $request->attributes->get(LegacyRouterChecker::LEGACY_CONTROLLER_IS_ALL_SHOP_CONTEXT);
```
Comment (jolelievre) [inline src/PrestaShopBundle/EventListener/Admin/Context/ShopContextListener.php]:
```suggestion
        // Check if the displayed legacy controller forces All shops mode (check already performed by LegacyRouterChecker)
        $isAllShopContext = $request->attributes->get(LegacyRouterChecker::LEGACY_CONTROLLER_IS_ALL_SHOP_CONTEXT);
```

File: src/PrestaShopBundle/Routing/LegacyRouterChecker.php [hunk 3]
```diff
@@ -45,7 +46,10 @@
 class LegacyRouterChecker
 {
     public const LEGACY_CONTROLLER_CLASS_ATTRIBUTE = '_legacy_controller_class';
+    public const LEGACY_CONTROLLER_INSTANCE_ATTRIBUTE = '_legacy_controller_instance_class';
+    public const LEGACY_CONTROLLER_ANONYMOUS_ATTRIBUTE = '_legacy_controller_anonymous_class';
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/LegacyRouterChecker.php]:
```suggestion
    public const LEGACY_CONTROLLER_INSTANCE_ATTRIBUTE = '_legacy_controller_instance';
    public const LEGACY_CONTROLLER_ANONYMOUS_ATTRIBUTE = '_legacy_controller_anonymous';
```

File: src/PrestaShopBundle/Routing/LegacyRouterChecker.php [hunk 4]
```diff
@@ -116,6 +120,13 @@ public function check(Request $request): bool
 
             $controllerClass = $controllers[strtolower($queryController)];
         }
+        // Loading controller
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/LegacyRouterChecker.php]:
```suggestion
        // We load the controller early in the process (during router matching actually), because the controller
        // configuration has many impacts on the contexts, the security listeners, ... And the relevant data can
        // only be retrieved once the legacy class is instantiated to access its public configuration
        // But for performance issues we only instantiate (and init) the controller here once and then store it (along
        // with other related attributes) in the request attributes so they can be retrieved easily by the code depending on them
```

File: src/PrestaShopBundle/Routing/LegacyRouterChecker.php [hunk 5]
```diff
@@ -116,6 +120,13 @@ public function check(Request $request): bool
...
+        $adminController = new $controllerClass();
+        $adminController->init();
+
+        $request->attributes->set(self::LEGACY_CONTROLLER_INSTANCE_ATTRIBUTE, $adminController);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/LegacyRouterChecker.php]: I'm hesitating here, should we have multiple attributes on the root level? Or one `_legacy_controller` array attribute with sub fields?

Not that it changes much things anyway, just a thought (maybe not the best one 😅)

**Review by jolelievre — COMMENTED** [review]
Thanks @M0rgan01 

Some minor thoughts, mostly some comments to clearly explain what we do here, which will turn out complex for future developers reading this code I'm sure 😅

File: src/PrestaShopBundle/Routing/LegacyRouterChecker.php (hunk 5 above)
Comment (M0rgan01) [reply src/PrestaShopBundle/Routing/LegacyRouterChecker.php]: I see what you mean... I added a specific class for these constants.

File: src/PrestaShopBundle/Routing/LegacyControllerConstants.php [hunk 6]
```diff
@@ -0,0 +1,14 @@
...
+
+namespace PrestaShopBundle\Routing;
+
+class LegacyControllerConstants
+{
+    public const CLASS_ATTRIBUTE = '_controller_class';
+    public const INSTANCE_ATTRIBUTE = '_controller_instance';
+    public const ANONYMOUS_ATTRIBUTE = '_controller_anonymous';
+    public const IS_MODULE_ATTRIBUTE = '_controller_is_module';
+    public const IS_ALL_SHOP_CONTEXT = '_controller_is_all_shop_context';
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/LegacyControllerConstants.php]:
```suggestion
    public const IS_ALL_SHOP_CONTEXT_ATTRIBUTE = '_controller_is_all_shop_context';
```
Maybe? It's the only one missing the suffix

File: src/PrestaShopBundle/Routing/LegacyControllerConstants.php [hunk 7]
```diff
@@ -0,0 +1,14 @@
+<?php
+
+declare(strict_types=1);
+
+namespace PrestaShopBundle\Routing;
+
+class LegacyControllerConstants
+{
+    public const CLASS_ATTRIBUTE = '_controller_class';
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/LegacyControllerConstants.php]:
```suggestion
    public const CLASS_ATTRIBUTE = '_legacy_controller_class';
```
I think we didn't understand each other with my last comment, using `legacy` as prefix everywhere seems appropriate, to avoid confusing ith Symfony attributes

**Review by jolelievre — DISMISSED** [review]
Thanks @M0rgan01

**Review by nicosomb — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @M0rgan01 ,

LGTM ✅ 

The expected behavior is the same as described in the issue.

Tested with Symfony layout enabled/disabled. Tested with/without incognito mode.
Redirected to a white page with code 200.
Screenshot 2024-04-15 at 14 56 05

But before merging, the auto tests are broken. Could you check : https://github.com/florine2623/testing_pr/actions/runs/8689082728/job/23826239697

Thanks !

File: app/config/admin/services.yml [hunk 8]
```diff
@@ -1,10 +1,15 @@
 # Dedicated services for Admin app
 parameters:
+  # We set priorities lower than the RouterListener (32) so that the LegacyRouterChecker class is called first.
+  # The correct functioning of Context Listeners on legacy routes depends on LegacyRouterChecker.
+  employee_listener_priority: 31
+  language_listener_priority: 30
+  default_listener_priority: 29
   # All admin context listeners should be executed before the router listener, this way even if no symfony route is found they context are initialized
```
Comment (jolelievre) [inline app/config/admin/services.yml]:
```suggestion
  # All admin context listeners should be executed before the router listener, this way even if no symfony route is found the contexts are initialized correctly
```

File: app/config/admin/services.yml [hunk 9]
```diff
@@ -1,10 +1,15 @@
 # Dedicated services for Admin app
 parameters:
+  # We set priorities lower than the RouterListener (32) so that the LegacyRouterChecker class is called first.
+  # The correct functioning of Context Listeners on legacy routes depends on LegacyRouterChecker.
```
Comment (jolelievre) [inline app/config/admin/services.yml]:
```suggestion
  # The correct behaviour of Context Listeners on legacy routes depends on LegacyRouterChecker.
```

**Review by jolelievre — DISMISSED** [review]
Thanks @M0rgan01 

Only comments about typos, completely optional 😅

**Review by boherm — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Nice @M0rgan01 !!

File: src/PrestaShopBundle/Routing/LegacyRouterChecker.php [hunk 10]
```diff
@@ -111,13 +114,29 @@ public function check(Request $request): bool
             // It's clearer to actually return a not found exception, for now the dispatcher is still used as fallback in index.php
             // but when it's cleared and only Symfony handles the whole routing then we can display a proper not found Symfony page
             if (!isset($controllers[strtolower($queryController)])) {
-                throw new NotFoundHttpException(sprintf('Unknown controller %s', $queryController));
+                // We need to define the languageId for context initialization in the legacy layout, because it will not be built
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/LegacyRouterChecker.php]:
```suggestion
                // We need to initialize the LanguageContext because it's used by components in the Symfony layout that will be displayed in the Not Found legacy page
```

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by boherm — APPROVED** [review]
