### PR TITLE
Fix error when loading theme that includes a translations directory but no translations

### LINKED ISSUE #14960: Importing a theme that has a translations folder but no files in it will throw an exception
**Describe the bug**
When loading a theme, ThemeManager will try to load its translations if the translations directory is present. But if it's present AND empty it would throw an exception.

**To Reproduce**
1. Create a theme that is not named classic, make sure there's a translations directory in it with nothing inside.
2. Zip it
3. Try to import it into PS.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.1

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | When loading a theme, ThemeManager will try to load its translations if the `translations` directory is present. But if it's present AND empty it would throw an exception.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | Yes, `TranslationFinderTrait` has been extracted into a class of its own, `TranslationFinder`.
| Fixed ticket? | Fixes #14960
| How to test?  | Create a theme that is not named `classic`, make sure there's a `translations` directory in it with nothing inside. Zip it and try to import it into PS.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14938)

### CODE REVIEW

File: src/PrestaShopBundle/Translation/Provider/TranslationFinder.php [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+        }
+
+        /** @var SplFileInfo $file */
+        foreach ($translationFiles as $file) {
+            if ('xlf' === $file->getExtension()) {
+                if (strpos($file->getBasename('.xlf'), $locale) !== false) {
+                    $domain = $file->getBasename('.xlf');
+                } else {
+                    $domain = $file->getBasename('.xlf') . '.' . $locale;
+                }
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Translation/Provider/TranslationFinder.php]: you could probably avoid the **else** here:

```php
$domain = $file->getBasename('.xlf');

if (strpos($file->getBasename('.xlf'), $locale) === false) {
  $domain .= '.' . $locale;
}
```

File: src/PrestaShopBundle/Translation/Provider/TranslationFinder.php [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+     * @param string|array $paths a list of paths when we can look for translations
+     * @param string $locale the Symfony (not the PrestaShop one) locale
+     * @param string|null $pattern a regular expression
+     *
+     * @return MessageCatalogue
+     *
+     * @throws FileNotFoundException
+     */
+    public function getCatalogueFromPaths($paths, $locale, $pattern = null)
+    {
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Translation/Provider/TranslationFinder.php:55]: Maybe some parts of this method could have been extracted in two different methods, that would be called in it ?

**getTranslationFilesFromPaths**() and a method **getFileCatalogueFromTranslationFile**() that would be called inside the foreach;

It could make this method easier to read, but this is not mandatory, maybe my suggestion is overkill... your call.

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Translation/Provider/TranslationFinder.php:55]: example:

```php

private function getTranslationFilesFromPaths($paths)
    {
        try {
            $translationFiles = $finder->files()->notName('index.php')->in($paths);
        } catch (\InvalidArgumentException $e) {
            throw new FileNotFoundException(
                sprintf(
                    'Could not crawl for translation files: %s',
                    $e->getMessage()
                ),
                self::ERR_DIRECTORY_NOT_FOUND,
                $e
            );
        }
        if (count($translationFiles) === 0) {
            throw new FileNotFoundException('There are no translation file available.', self::ERR_NO_FILES_IN_DIRECTORY);
        }
        
        return $translationFiles;
    }

```

**Comment by eternoendless** [comment]
Done!

**Review by matthieu-rolland — APPROVED** [review]
LGTM !

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

It is OK.
checked with this theme
[childtheme-example.zip](https://github.com/PrestaShop/PrestaShop/files/3472534/childtheme-example.zip)

Thanks!

**Comment by eternoendless** [comment]
Thanks everyone!
