### PR TITLE
Fix SQL query in OrderQueryBuilder

### LINKED ISSUE #24911: BO - Orders - impossible to extend order grid query from module
#### Describe the bug

When you try to modify Orders list query from a module using actionOrderGridQueryBuilderModifier hook, always gets an error by using the "New client" filter.

#### Expected behavior

A module could extend orders list query using actionOrderGridQueryBuilderModifier hook with no errors.

#### Steps to Reproduce

1. Develop a module to add a new column on backoffice Orders grid using actionOrderGridQueryBuilderModifier hook.
2. Add a new data column to Orders grid (similar to example for Customers grid from official doc: https://devdocs.prestashop.com/1.7/modules/sample-modules/grid-and-identifiable-object-form-hooks-usage/#extending-grid-query-builder)
2. Click on backoffice Orders menu
3. Use "New client" filter with any value (Yes or No) and click on Search button
4. An error 500 is shown due to and incorrect table alias

**Screenshots**

- Module hooks code:

hookActionOrderGridDefinitionModifier code:
```
public function hookActionOrderGridDefinitionModifier(array $params)
{
    $definition = $params['definition'];

    $definition->getColumns()->addAfter(
        'date_add',
        (new BooleanColumn('from_app'))
            ->setName($this->l('App order'))
            ->setOptions([
                'field' => 'from_app',
                'true_name' => $this->trans('Yes', [], 'Admin.Global'),
                'false_name' => $this->trans('No', [], 'Admin.Global'),
                'clickable' => true,
            ])
    );

    $definition->getFilters()->add(
        (new Filter('from_app', YesAndNoChoiceType::class))
        ->setTypeOptions([
            'required' => false,
        ])    
        ->setAssociatedColumn('from_app')
    );
}

public function hookActionOrderGridQueryBuilderModifier(array $params)
{
    $searchQueryBuilder = $params['search_query_builder'];

    $searchCriteria = $params['search_criteria'];

    $searchQueryBuilder->addSelect(
        'app.`id_order` IS NOT NULL AS `from_app`'
    );

    $searchQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );

    if ('from_app' === $searchCriteria->getOrderBy()) {
        $searchQueryBuilder->orderBy('app.`id_order`', $searchCriteria->getOrderWay());
    }

    foreach ($searchCriteria->getFilters() as $filterName => $filterValue) {
        if ('from_app' === $filterName) {
            $searchQueryBuilder->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
        }
    }
}
```
- Error details:

#### Additional information

A further investigation show that error came from leftJoin alias used on $searchQueryBuilder modification. The problem is that standard "o" alias completly change on query builder when a "New client" filter is used. This is caused by an incorrect subquery that do not use standard "o" alias (in fact do not use any alias at all) on https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Query/OrderQueryBuilder.php#L275. This makes impossible to extend orders query using a join stament unless you remove "New client" filter and column from grid.

* PrestaShop version: develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Because of the way the SQL query was made in OrderQueryBuilder, it threw an exception when trying to extend the form. This PR solves the issue by changing the way the SQL query is made.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24911
| How to test?      | See Below
| Possible impacts? | 

### How to test

Create new table `app_order_table` with `id_order`
image

Install the module [ps_qualityassurance](https://github.com/PrestaShop/ps_qualityassurance), add two hooks:

`actionOrderGridQueryBuilderModifier` with this content:
```php
$searchQueryBuilder = $params['search_query_builder'];
$countQueryBuilder = $params['count_query_builder'];

    $searchCriteria = $params['search_criteria'];

    $searchQueryBuilder->addSelect(
        'app.`id_order` IS NOT NULL AS `from_app`'
    );

    $searchQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );
	$countQueryBuilder->leftJoin(
        'o',
        '`app_order_table`',
        'app',
        'app.`id_order` = o.`id_order`'
    );

    if ('from_app' === $searchCriteria->getOrderBy()) {
        $searchQueryBuilder->orderBy('app.`id_order`', $searchCriteria->getOrderWay());
    }

    foreach ($searchCriteria->getFilters() as $filterName => $filterValue) {
        if ('from_app' === $filterName) {
            $searchQueryBuilder
              ->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
          $countQueryBuilder
              ->andWhere('app.`id_order` IS ' . ($filterValue ? 'NOT' : '') . ' NULL');
        }
    }
```

and `actionOrderGridDefinitionModifier` with this content:
```php
$definition = $params['definition'];

    $definition->getColumns()->addAfter(
        'date_add',
        (new PrestaShop\PrestaShop\Core\Grid\Column\Type\BooleanColumn('from_app'))
            ->setName($this->l('App order'))
            ->setOptions([
                'field' => 'from_app',
                'true_name' => $this->trans('Yes', [], 'Admin.Global'),
                'false_name' => $this->trans('No', [], 'Admin.Global'),
                'clickable' => true,
            ])
    );

    $definition->getFilters()->add(
        (new PrestaShop\PrestaShop\Core\Grid\Filter\Filter('from_app', PrestaShopBundle\Form\Admin\Type\YesAndNoChoiceType::class))
        ->setTypeOptions([
            'required' => false,
        ])    
        ->setAssociatedColumn('from_app')
    );
```

Now, go on the page Order and try to change the filter `new client`. An exception should happen without this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26221)

### CODE REVIEW

File: src/Core/Grid/Query/OrderQueryBuilder.php [hunk 1]
```diff
@@ -117,12 +117,9 @@ public function getCountQueryBuilder(SearchCriteriaInterface $searchCriteria)
     {
         $qb = $this->getBaseQueryBuilder($searchCriteria->getFilters());
         if (isset($searchCriteria->getFilters()['new'])) {
```
Comment (jolelievre) [inline src/Core/Grid/Query/OrderQueryBuilder.php]: Since the filters checking is already performed in `applyNewCustomerFilter` I think you can remove this if statement

In the search function that's how it's done, `applyNewCustomerFilter` is always called because it can handle itself

**Review by jolelievre — COMMENTED** [review]
Just a small comment ;)

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — COMMENTED** [review]
@atomiix I tried to understand what's going on with the query but it's really hard 😅  and when I print the SQL being executed with your PR and the 'New customer' filter I get 3 times the ps_orders table with twice alias `o` and once alias `o`.

Could you help me understand the fix? 😉

File: src/Core/Grid/Query/OrderQueryBuilder.php [hunk 2]
```diff
@@ -233,20 +228,27 @@ private function getBaseQueryBuilder(array $filters)
...
             ->setMaxResults(1)
+            ->getSQL()
         ;
+    }
 
-        $qb->addSelect('IF ((' . $newCustomerSubSelect->getSQL() . ') > 0, 0, 1) AS new');
+    /**
+     * @param QueryBuilder $qb
+     */
+    private function addNewCustomerField(QueryBuilder $qb)
```
Comment (Progi1984) [inline src/Core/Grid/Query/OrderQueryBuilder.php]:
```suggestion
    private function addNewCustomerField(QueryBuilder $qb): void
```

File: src/Core/Grid/Query/OrderQueryBuilder.php [hunk 3]
```diff
@@ -233,20 +228,27 @@ private function getBaseQueryBuilder(array $filters)
     }
 
     /**
-     * @param QueryBuilder $qb
+     * return the subquery defining if a customer is new or not
```
Comment (Progi1984) [inline src/Core/Grid/Query/OrderQueryBuilder.php]:
```suggestion
     * Returns the subquery defining if a customer is new or not
```

**Review by Progi1984 — COMMENTED** [review]
@atomiix Thank you for your contribution. I have brought you some comments.

**Review by Progi1984 — APPROVED** [review]

**Comment by atomiix** [comment]
@matks the main issue was that the whole request was used as a subquery in the function `applyNewCustomerFilter` preventing it to be extended.
This PR change the way of getting the `new` value without using the main query as a subquery.
There is 1 select from `ps_order` with the alias `o` which is the main query and 2 selects from `ps_order` with the alias `so` whiches are 2 subqueries.

**Comment by matks** [comment]
> There is 1 select from `ps_order` with the alias `o` which is the main query and 2 selects from `ps_order` with the alias `so` whiches are 2 subqueries.

Would'nt it be a little safer to have the 2 subqueries use different aliases?

**Comment by atomiix** [comment]
@matks actually, these 2 subqueries come from the method `getNewCustomerSubSelect()`, the first is to get the actual value `new` and the second is to filter the request depending on `new`. This is done like so to prevent the use of `having` that is not usable to get the total number of orders.
That's why they use the same alias but I don't think that it's a problem.

**Review by matks — APPROVED** [review]
Thank you @atomiix for the answers, I approve this PR.

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
**Without PR**
image
**With PR**
image

https://watch.screencastify.com/v/QEpLlSMV8vOEnYHVV686

Thanks!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith

**Comment by ocio87** [comment]
Hello,

It is reported that the slowness has not yet been fixed in version 8.1.

The fix that they propose in https://github.com/PrestaShop/PrestaShop/issues/27232 has not been implemented yet.

The change is made manually in my version 8.1.0 and it improves the loading of the page.

Behavior without changes

https://drive.google.com/file/d/1pn8W0WxQnc3_Xbk2d0NqWfIaGJkSLOWn/view?usp=sharing

Behavior with changes:

https://drive.google.com/file/d/1pqyznTp1ie2P-6UxxvQMPvirAlLNDJpq/view?usp=sharing

Change made suggested by @Hlavtox :

\src\Core\Grid\Query\OrderQueryBuilder.php and put it back to what it was.
Find $qb->addSelect('(' . $this->getNewCustomerSubSelect() . ') AS new'); and change it to $qb->addSelect('IF((SELECT so.id_order FROM ps_orders so WHERE (so.id_customer = o.id_customer) AND (so.id_order < o.id_order) LIMIT 1) IS NOT NULL, 0, 1) AS new'); 

image

**Comment by bpodwinski** [comment]
I just noticed that the PR checks if a customer is new using the SQL COUNT method, This causes a very big performance problem:

With 18,000 orders, it took 43 seconds to load the page on the latest version of Prestashop 8.2.

I modified the getNewCustomerSubSelect function:

**Before: use SQL COUNT method, COUNT iterates through all rows, result 43s env**

    /**
     * Returns the subquery defining if a customer is new or not
     */
    private function getNewCustomerSubSelect(): string
    {
        return $this->connection
            ->createQueryBuilder()
            ->select('IF(count(so.id_order) > 0, 0, 1)')
            ->from($this->dbPrefix . 'orders', 'so')
            ->where('so.id_customer = o.id_customer')
            ->andWhere('so.id_order < o.id_order')
            ->setMaxResults(1)
            ->getSQL()
        ;
    } 

Fix by @Hlavtox [https://github.com/PrestaShop/PrestaShop/issues/27232#issuecomment-1006692117](https://github.com/PrestaShop/PrestaShop/issues/27232#issuecomment-1006692117)
**After: with if condition and limit 1, result 4.4s env**

    /**
     * Returns the subquery defining if a customer is new or not
     */
     private function getNewCustomerSubSelect(): string
    {
        return $this->connection
            ->createQueryBuilder()
            ->select('IF((' . 
                $this->connection->createQueryBuilder()
                    ->select('so.id_order')
                    ->from($this->dbPrefix . 'orders', 'so')
                    ->where('so.id_customer = o.id_customer')
                    ->andWhere('so.id_order < o.id_order')
                    ->setMaxResults(1)
                    ->getSQL() . 
                ') IS NOT NULL, 0, 1)')
            ->getSQL();
    } 

**Another solution with EXISTS, result 4.7s**

    /**
     * Returns the subquery defining if a customer is new or not
     */
    private function getNewCustomerSubSelect(): string
    {
        return $this->connection
            ->createQueryBuilder()
            ->select('IF(EXISTS(' . 
                $this->connection->createQueryBuilder()
                    ->select('1')
                    ->from($this->dbPrefix . 'orders', 'so')
                    ->where('so.id_customer = o.id_customer')
                    ->andWhere('so.id_order < o.id_order')
                    ->setMaxResults(1)
                    ->getSQL() . 
                '), 0, 1) AS new')
            ->getSQL();
    }

My Prestashop, which is causing issues, is the result of a migration from PS 1.7.7 to 8.2. I’m not sure if the problem is due to the migration itself or because the migration script may have missed adding some SQL indexes.

Anyway, COUNT is not suitable for checking if a customer has already placed an order because it scans all matching rows without stopping, even if it finds one. This creates unnecessary load, especially when only the existence of an order is needed, not the total count.

It's so slow COUNT that displaying 10 or 100 orders, the page takes 43s in all cases!

**Comment by ocio87** [comment]
I have prestashop 8.1.1 with 107000 orders. With mysql 5.7 it loads in 2 seconds.

I am migrating to an Almalinux 9 server with Mysql 8.0 and it loads in 6 seconds.

Is there something that can be changed in the configuration so that the load is not so affected with Mysql 8.0?
