### PR TITLE
Show new invoice information when adding product with new invoice in BO Order

### LINKED ISSUE #18020: New invoice information block is missing in Order view page
#### Describe the bug

In Order view page when I try to add a product with new invoice, I should see the checkobox "free shipping" according to legacy behavior.
Screenshot from 2020-03-06 15-07-11

#### Expected behavior

The checkbox with "free shipping" checkbox should appear when "create new invoice" is selected.

#### Steps to Reproduce

1. Go to `admin-dev/sell/orders/orders/{orderId}/view
2. Make sure order status is not "delivered" and you can add products.
3. Make sure your order has invoice. (to generate one, click `generate invoice` in Documents tab
4. Click `Add product`, search and select the product.
5. In right side of the screen you should see select box with invoices, select option `create new invoice`
6. The new block 'new invoice information' should appear which should contain a checkbox of "free shipping"

#### Additional information

* PrestaShop version: 1.7.7x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Free shipping checkbox was missing due to wrong comparson and some selectors in js. It should occur in BO order view page when adding new product with "create new invoice" option.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #18020 
| How to test?  | The block was missing before and should be visible now. It should occur once you select "create new invoice" option when adding product in BO. Before - Screenshot from 2020-04-09 13-00-34 After - Screenshot from 2020-04-09 12-59-58

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18544)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Code is :ok_hand: but TravisCI is :red_circle:

**Comment by zuk3975** [comment]
> Code is  but TravisCI is

seems to be random failures :crying_cat_face:

**Comment by Progi1984** [comment]
@zuk3975 I fix TravisCI ;)

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

There are somme diffrence between the legacy Order page and the Migrated Order page
- In the Migrated order page when we select `Create a new invoice` and click "Add" => There is no alert displayed
image

- In the Migrated order page following these steps:
1. Order status is payment accepted
2. Add a new product with creating a new invoice
3. Without refresh the page => Add another product 
4. When we click `Add a product` button
=> the option selected is always "`Create a new invoice`", it is not the option by default "#Invoice1", so the "new invoice information" is always displayed => it shouldn't, it is not the same behavior with the legacy page.
If we selected free shipping in the Step2 => in the Step4 the free shipping is selected too.

177x => https://drive.google.com/file/d/1wgNRLJ-U2Qsgo7uZ1_kLubwj2-EonCQ1/view?usp=sharing

1764 => https://drive.google.com/file/d/1AiCdg6w5_cMJ5KYJK6URbf4etwaqtAvl/view?usp=sharing

Thanks!

**Comment by zuk3975** [comment]
Hi @khouloudbelguith ,
> In the Migrated order page when we select `Create a new invoice` and click "Add" => There is no alert displayed

First one seems to be unrelated with pr, because "create new invoice" feature was already there, But i guess I can try to implement it here it should be just couple lines.

> ..."new invoice information" is always displayed => it shouldn't...

This one is related, Ill try to fix it.

Thanks.

**Comment by matks** [comment]
> First one seems to be unrelated with pr, because "create new invoice" feature was already there, But i guess I can try to implement it here it should be just couple lines.

No this is out of scope. We need another issue and another PR

**Comment by matks** [comment]
This PR fixes this ticket AND ONLY THIS TICKET
https://github.com/PrestaShop/PrestaShop/issues/18020

**Comment by khouloudbelguith** [comment]
Hi @zuk3975, @matks,

Issue created https://github.com/PrestaShop/PrestaShop/issues/18573

Thanks!

**Comment by zuk3975** [comment]
Fixed the second bug.
As @matks mentioned, the first one should be done in separate pr after creating separate issue.

File: admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js [hunk 1]
```diff
@@ -55,6 +55,8 @@ export default class OrderInvoicesRefresher {
           $paymentInvoiceSelect.append(`<option value="${invoiceId}">${invoiceName}</option>`);
           $productEditInvoiceSelect.append(`<option value="${invoiceId}">${invoiceName}</option>`);
         });
+
+        document.querySelector(OrderViewPageMap.productAddInvoiceSelect).selectedIndex = 0;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js:59]: Quick question, is the first index the last created invoice? Because selecting the first one when new ones have been created wouldn't make sense

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js [hunk 2]
```diff
@@ -118,6 +119,7 @@ export default class OrderProductAdd {
       );
     });
     this.productAddActionBtn.on('click', event => this.addProduct($(event.currentTarget).data('orderId')));
+    this.productAddMenuBtn.on('click', () => this.orderProductRenderer.toggleProductAddNewInvoiceInfo());
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: Is this necessary? Since it's already done in `OrderViewPage::listenForProductAdd`?
Isn't the fix in `toggleProductAddNewInvoiceInfo` enough?

File: admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js (hunk 1 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js:59]: sadly no, its the first one... But legacy works like that so be it :)
The "create new invoice" option is last and invoices are ordered from oldest to newest , so we would want to change that, but i guess its not the purpose of the pr.

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js (hunk 2 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: Yes you are right.

File: admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js [hunk 3]
```diff
@@ -71,8 +71,8 @@ export default {
   productsTablePaginationLink: '.page-item:not(.d-none):not(#orderProductsTablePaginationNext):not(#orderProductsTablePaginationPrev) .page-link',
   productsTablePaginationActive: '#orderProductsTablePagination .page-item.active span',
   productsTablePaginationTemplate: '#orderProductsTablePagination .page-item.d-none',
-  productsTableRow: (productId) => `#orderProduct_${productId}`,
-  productsTableRowEdited: (productId) => `#editOrderProduct_${productId}`,
+  productsTableRow: productId => `#orderProduct_${productId}`,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]: I believe eslint requires those `()` and removing them will conflict with the rules on develop
@NeOMakinG what do you think?

File: admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js (hunk 1 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js:59]: You're right it's not the purpose but it doesn't explode the scope either Maybe just need to change the order of returned orders, if you've got time and as long as it doesn't block the PR this could be added If decision or implementation takes too long it should be in another PR

Anyway this needs to be decided by @MatShir : should the default selected invoice be the most recent or the oldest one?

File: admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js (hunk 3 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]: I think I've deleted it because the eslinter underlined those two lines.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]: Ok it's weird because in function callbacks the `()` are required :P Maybe it depends on the eslint config? Is it the same as the one in develop?
But anyway if eslint is fine with it no problem for me

File: admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js (hunk 1 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-invoices-refresher.js:59]: Screenshot from 2020-04-15 14-20-39

File: admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js (hunk 3 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]: They're required on develop, it will generate conflict on the merge of 1.7.7.x into develop.

I think your IDE use a basic configuration (like eslint:recommended) or airbnb, because he can't find a configuration on the project (of course it's not existing on 1.7.7.x), maybe you should configure you'r IDE to use our configurastion even if there are no .eslintrc files

Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/OrderViewPageMap.js]: rolled back

**Review by jolelievre — DISMISSED** [review]
Thank @zuk3975

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

We have a different issue comparing 1.7.6 and this PR following these steps:
1. Create order from the FO with a carrier not free, for example in the FO => checkout page =>  Step3 => select My carrier as a shipping method
3. In the BO => Orders Views page => Order status is payment accepted
4. Add a new product with creating a new invoice with selecting `Free shipping`
5. a new discount is created => ok
6. if you check the first invoice created by changing the order status, the Shipping Costs became "Free shipping" => OK, but there is a block is missing, the `Discounts block` is missing in the first invoice.

**1.7.7.x => with this PR:**
image

**1.7.6.4 =>**
image

Thanks!

**Comment by zuk3975** [comment]
> Hi @zuk3975,
> 
> We have a different issue comparing 1.7.6 and this PR following these steps:
> 
> 1. Create order from the FO with a carrier not free, for example in the FO => checkout page =>  Step3 => select My carrier as a shipping method
> 2. In the BO => Orders Views page => Order status is payment accepted
> 3. Add a new product with creating a new invoice with selecting `Free shipping`
> 4. a new discount is created => ok
> 5. if you check the first invoice created by changing the order status, the Shipping Costs became "Free shipping" => OK, but there is a block is missing, the `Discounts block` is missing in the first invoice.
> ...
> Thanks!

Hi, thanks, but
this pr is only responsible for showing the hidden template whereas the issue seems to be associated with cart rule calculations in invoice.
Separate issue should be created for that, thanks.

**Comment by khouloudbelguith** [comment]
@zuk3975, thanks!
Issue created here: https://github.com/PrestaShop/PrestaShop/issues/18712

Thanks!

**Review by jolelievre — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

This PR is ready for QA? or you need to resolve conflicts before?

Thanks!

**Comment by zuk3975** [comment]
> Hi @zuk3975,
> 
> This PR is ready for QA? or you need to resolve conflicts before?
> 
> Thanks!

I've rebased it, it was only assets conflicting, it is ready for testing.

**Comment by khouloudbelguith** [comment]
@zuk3975, thanks!
Waiting to be reviewed again :wink: 

Thanks!

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

It is ok :heavy_check_mark: 
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @zuk3975
