### PR TITLE
HelperForm field label not work in switch type 

### LINKED ISSUE #20652: HelperForm field label not work in switch type
## Describe the bug

HelperForm field label not work in switch type. Labels are always **YES** or **NO**, even when we define another one.

image

## Expected behavior

image

#### 1 - Module config form

```php
protected function getConfigForm()
    {
        return array(
            'form' => array(
                'legend' => array(
                'title' => $this->l('Settings'),
                'icon' => 'icon-cogs',
                ),
                'input' => array(
                    array(
                        'type' => 'switch',
                        'label' => $this->l('Mater Mode'),
                        'name' => 'CMS_SYNCRONIZATION_MASTER_MODE',
                        'is_bool' => true,
                        'desc' => $this->l('Use this module in master or client mode'),
                        'values' => array(
                            array(
                                'id' => 'active_on',
                                'value' => true,
                                'label' => $this->l('MASTER') // Label if ON
                            ),
                            array(
                                'id' => 'active_off',
                                'value' => false,
                                'label' => $this->l('CLIENT') // Label if OFF
                            )
                        ),
                    ),
                ),
                'submit' => array(
                    'title' => $this->l('Save'),
                ),
            ),
        );
    }
```
#### 2 - See error in Backoffice module config page

You have **YES** and **NO**  instead of **MASTER** and **CLIENT**

image

## How to test

1 - Install [pululuk_issue_20653.zip](https://github.com/PrestaShop/PrestaShop/files/5102309/pululuk_issue_20653.zip)

2 - Go to module configuration page and make sure you have **MY ON**  and **MY OFF** instead of **YES** and **NO**

3 - Edit module code source  remove form input switch labels look : 

```php
protected function getConfigForm()
    {
        return array(
            'form' => array(
                'legend' => array(
                'title' => $this->l('Settings'),
                'icon' => 'icon-cogs',
                ),
                'input' => array(
                    array(
                        'type' => 'switch',
                        'label' => $this->l('Live mode'),
                        'name' => 'PULULUK_ISSUE_20653_LIVE_MODE',
                        'is_bool' => true,
                        'desc' => $this->l('Use this module in live mode'),
                        'values' => array(
                            array(
                                'id' => 'active_on',
                                'value' => true,
                            ),
                            array(
                                'id' => 'active_off',
                                'value' => false,
                            )
                        ),
                    )
                ),
                'submit' => array(
                    'title' => $this->l('Save'),
                ),
            ),
        );
    }
```
2 - Go to module configuration page and make sure you have default labels now **YES** and **NO**

### Additional information

* PrestaShop version: N/A
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | HelperForm field label not work in switch type 
| Type?     | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20652
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/20652 **How to test section** 

@khouloudbelguith  check this controllers : 

- controllers/admin/AdminCarrierWizardController.php
- controllers/admin/AdminPatternsController.php
- controllers/admin/AdminCarriersController.php
- controllers/admin/AdminStatesController.php
- controllers/admin/AdminTaxRulesGroupController.php
- controllers/admin/AdminStoresController.php
- controllers/admin/AdminSuppliersController.php
- controllers/admin/AdminCountriesController.php
- controllers/admin/AdminZonesController.php
- controllers/admin/AdminQuickAccessesController.php
- controllers/admin/AdminShopGroupController.php
- controllers/admin/AdminGroupsController.php
- controllers/admin/AdminTabsController.php
- controllers/admin/AdminShopUrlController.php
- controllers/admin/AdminImagesController.php
- controllers/admin/AdminShopController.php

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20653)

### CODE REVIEW

File: classes/helper/HelperForm.php [hunk 1]
```diff
@@ -92,6 +94,23 @@ public function generate()
                         unset($this->fields_form[$fieldset_key]['form']['input'][$key]);
                     }
                     switch ($params['type']) {
+                        case 'switch':
+                            $switch_values = $params['values'];
+                            if (isset($switch_values) && !empty($switch_values)) {
```
Comment (PierreRambaud) [inline classes/helper/HelperForm.php]:
```suggestion
                            if (!empty($params['values'])) {
```
So if `$switch_values` is empty, nothing occurs, it's not going to the default part? :thinking: 

Then assign the `$params['values']` to `$switchValues`, otherwise it will failing on modern PHP instances. (Undefined index 'values' blablabla).

File: classes/helper/HelperForm.php [hunk 2]
```diff
@@ -92,6 +94,23 @@ public function generate()
...
+                                $default_switch_labels = [
```
Comment (PierreRambaud) [inline classes/helper/HelperForm.php]: This kind of values must be outside the loop, no need to generate it each time

File: classes/helper/HelperForm.php [hunk 3]
```diff
@@ -92,6 +94,23 @@ public function generate()
...
+                                    'active_on' => $translator->trans('Yes', [], 'Admin.Global'),
+                                    'active_off' => $translator->trans('No', [], 'Admin.Global'),
+                                ];
+
+                                foreach ($switch_values as $k => $value) {
+                                    if (!isset($value['label'])) {
+                                        $defautl_label = (array_key_exists($value['id'], $default_switch_labels)) ? $default_switch_labels[$value['id']] : '';
```
Comment (PierreRambaud) [inline classes/helper/HelperForm.php]:
```suggestion
                                        $defautl_label = $default_switch_labels[$value['id']] ?? '';
```

**Review by PierreRambaud — COMMENTED** [review]
I love the idea, just few comments :)

**Review by Progi1984 — DISMISSED** [review]

File: classes/helper/HelperForm.php (hunk 1 above)
Comment (PululuK) [reply classes/helper/HelperForm.php]: > So if $switch_values is empty, nothing occurs, it's not going to the default part? thinking


This means that the developer did not understand the documentation 😅
What should be the behavior in this case ? Maybe we should ask the PM team ? 🤔
Nice @PierreRambaud  !!


**EDIT** : 

For this case the current behavior is : 
image

Comment (PierreRambaud) [reply classes/helper/HelperForm.php]: ping @PrestaShop/prestashop-product-team :)

Comment (LouiseBonnard) [reply classes/helper/HelperForm.php]: Hi there! Ideally, `$switch_values` should not be empty but in case no values are defined, I think it makes more sense to have _Yes_ and _No_ as default values. :-)

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

I found an issue.
If you navigate to BO > Shipping > Carriers > Edit any carrier
In the Second Step, see the error
**After**
image
**Before**
image

Thanks to check and feedback.

**Comment by PululuK** [comment]
Sorry @khouloudbelguith, but I don't understand you. This PR is in progress ... See https://github.com/PrestaShop/PrestaShop/pull/20653#discussion_r485562156

**Comment by khouloudbelguith** [comment]
@PululuK, are you still working in this PR? not ready yet for QA?

**Comment by PululuK** [comment]
> @PululuK, are you still working in this PR? not ready yet for QA?

Yes !
I discussed with the @PierreRambaud  @LouiseBonnard  here :  #20653 (comment).
I have some improvements to do

**Comment by khouloudbelguith** [comment]
@PululuK, ok thank!
The label Waiting for QA was added, that's why I made some tests.

**Comment by atomiix** [comment]
@PululuK @khouloudbelguith my bad, I thought the changes requested were made 😄

**Comment by PululuK** [comment]
> @PululuK, ok thank!
> The label Waiting for QA was added, that's why I made some tests.

Yes @khouloudbelguith you did your job.
I understand you perfectly ... Thank you !

File: classes/helper/HelperForm.php (hunk 1 above)
Comment (PululuK) [reply classes/helper/HelperForm.php]: Done !

**Comment by PululuK** [comment]
@Progi1984  @atomiix @PierreRambaud  ready for review  🤗

File: controllers/admin/AdminCarrierWizardController.php [hunk 4]
```diff
@@ -266,12 +266,12 @@ public function renderStepThree($carrier)
                             [
                                 'id' => 'shipping_handling_on',
                                 'value' => 1,
-                                'label' => $this->trans('Enabled', [], 'Admin.Global'),
+                                'label' => $this->trans('Yes', [], 'Admin.Global'),
```
Comment (PierreRambaud) [inline controllers/admin/AdminCarrierWizardController.php:269]: Why changing these translations? :thinking:

Comment (PululuK) [reply controllers/admin/AdminCarrierWizardController.php:269]: @PierreRambaud To make this consistent with the other pages and avoid : 

image

Comment (PululuK) [reply controllers/admin/AdminCarrierWizardController.php:269]: @LouiseBonnard @Junebyun could you help us ?
I think we need to harmonize the labels for switch inputs. Either we use "Yes" and "No" or "Enabled" and "Disabled".
WYDF ?

@PierreRambaud  FYI, The current behavior is "Yes" or "No" in all cases. Currently Labels in forms are not taken into account.
See https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/helpers/form/form.tpl#L423
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/helpers/form/form.tpl#L425

Comment (LouiseBonnard) [reply controllers/admin/AdminCarrierWizardController.php:269]: Hi @PululuK, that's an interesting question for @Julievrz, our new Product Content Manager! And once the decision made, it might be great to relate it to https://github.com/PrestaShop/PrestaShop/issues/19142. :-)

**Review by Progi1984 — DISMISSED** [review]

File: controllers/admin/AdminCarrierWizardController.php (hunk 4 above)
Comment (PululuK) [reply controllers/admin/AdminCarrierWizardController.php:269]: @LouiseBonnard  @PierreRambaud  news ?

Comment (PierreRambaud) [reply controllers/admin/AdminCarrierWizardController.php:269]: @PululuK I'm not the one who decides about wordings :(

Comment (PululuK) [reply controllers/admin/AdminCarrierWizardController.php:269]: @LouiseBonnard @PierreRambaud But I don't understand why this PR is waiting for wording ? The current behavior is "Yes" or "No".

See https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/helpers/form/form.tpl#L423 and https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/template/helpers/form/form.tpl#L425

If you want to modify wordings this is not in the scope of my PR. 

See https://github.com/PrestaShop/PrestaShop/pull/20653#discussion_r487705269

Comment (Julievrz) [reply controllers/admin/AdminCarrierWizardController.php:269]: Yes/No is ok for me. @PululuK @PierreRambaud

Comment (PululuK) [reply controllers/admin/AdminCarrierWizardController.php:269]: Thank you @Julievrz  !

**Comment by PululuK** [comment]
ping @PierreRambaud @atomiix

**Review by PierreRambaud — DISMISSED** [review]

File: controllers/admin/AdminCarrierWizardController.php (hunk 4 above)
Comment (Progi1984) [reply controllers/admin/AdminCarrierWizardController.php:269]: @Julievrz / @LouiseBonnard If the wording is OK : can you put the label "Wording :heavy_check_mark:" ?

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

I found this issue in the carrier page
image

It should be
image


Thanks!

**Comment by PululuK** [comment]
> Hi @PululuK,
> 
> I found this issue in the carrier page
> Thanks!


Thanks @khouloudbelguith 
Done ! FYI it is a old Prestashop issue they used 1 for "No" and 0 for "Yes".
. See https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCarriersController.php#L261 and https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCarriersController.php#L256 
Ping @PierreRambaud  @Progi1984  @atomiix

**Comment by PierreRambaud** [comment]
> > Hi @PululuK,
> > I found this issue in the carrier page
> > Thanks!
> 
> Thanks @khouloudbelguith
> Done ! FYI it is a old Prestashop issue they used 1 for "No" and 0 for "Yes".
> . See https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCarriersController.php#L261 and https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCarriersController.php#L256
> Ping @PierreRambaud @Progi1984 @atomiix

Nice catch! Your solution here: 2c615147beaed1e0728dfa64eb10d07682611616 is the best one I think.
If we change the wording, people will be disrupted, and changing the value will be break everything :sweat_smile:

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

I found some issues:
1. controllers/admin/AdminPatternsController.php
image
2. controllers/admin/AdminShopUrlController.php
image
3. controllers/admin/AdminShopGroupController.php
image

Thanks to check and feedback.

**Comment by PululuK** [comment]
@khouloudbelguith  Done ! I thank you for your patience 🙌🏾

@Progi1984  @PierreRambaud  https://github.com/PrestaShop/PrestaShop/pull/20653/commits/7faa70c11d354faf7402864f2c54b149cfcc2b4f

Default switch Id's is `active_off` and `active_on`,  in case the developer use a custom id for exemple [type_switch_disabled_on](https://github.com/PululuK/PrestaShop/blob/patch-14/controllers/admin/AdminPatternsController.php#L328) and [type_switch_disabled_off](https://github.com/PululuK/PrestaShop/blob/patch-14/controllers/admin/AdminPatternsController.php#L332) the label will be based on the value :   `1 => 'Yes' ` and `0 => 'No'` (the switch type is boolean 😉)

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

There are some changes in the Module's Configuration pages
1. statsdata
2. ps_shoppingcart
3. contactform
4. ps_imageslider
5. ps_mainmenu
6. productcomments (`CONFIGURATION` section, `ADD NEW CRITERION` section)
7. ps_crossselling
8. ps_wirepayment
9. ps_sharebuttons

For example
image

Thanks to check and feedback.

**Comment by PululuK** [comment]
Hi @khouloudbelguith 

Yes this is expected behavior ! See https://github.com/PrestaShop/ps_crossselling/blob/dev/ps_crossselling.php#L134 And https://github.com/PrestaShop/ps_crossselling/blob/dev/ps_crossselling.php#L139

They have never been displayed because the labels do not currently work !

**Comment by khouloudbelguith** [comment]
@PululuK, thanks for your feedback.
In this case, I need a confirmation from our Product team to validate this PR.
Ping @PrestaShop/product-team what do you think?
After this PR, there are some changes in some modules as commented here: https://github.com/PrestaShop/PrestaShop/pull/20653#issuecomment-704790576
As @PululuK said, this an expected behavior.
For example
https://github.com/PrestaShop/contactform/blob/dev/contactform.php#L214
https://github.com/PrestaShop/ps_crossselling/blob/dev/ps_crossselling.php#L134
What do you think?

Thanks!

**Comment by PululuK** [comment]
@khouloudbelguith 

In your example

image

This is because :  

- https://github.com/PrestaShop/statsdata/blob/master/statsdata.php#L194
- https://github.com/PrestaShop/statsdata/blob/master/statsdata.php#L199
- https://github.com/PrestaShop/statsdata/blob/master/statsdata.php#L212
- https://github.com/PrestaShop/statsdata/blob/master/statsdata.php#L217
- https://github.com/PrestaShop/statsdata/blob/master/statsdata.php#L230
- https://github.com/PrestaShop/statsdata/blob/master/statsdata.php#L235


This also impacts all modules using switch type fields with labels.
They have never been displayed because the labels do not currently work !

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith, @PululuK, the wording is less consistent with the rest of the software pages but if it allows us to fix this issue, well, I'm all for it, thank you very much! I think we can discuss the UX of the buttons later and possibly create a new issue to improve it.

@TristanLDD, @prestascott, FYI

**Comment by PululuK** [comment]
> Hi @khouloudbelguith, @PululuK, the wording is less consistent with the rest of the software pages but if it allows us to fix this issue, well, I'm all for it, thank you very much! I think we can discuss the UX of the buttons later and possibly create a new issue to improve it.
> 
> @TristanLDD, @prestascott, FYI

Hello @LouiseBonnard  @khouloudbelguith 

I just want to clarify a few things:
This fix consists in allowing to use a custom label in the switch type field. For example instead of **Yes** and **No** (current behavior) developers can use **Ok** and **Nok**, or **Auto** and **Manual** ... etc etc

In Core, I agree that the labels for these fields must be consistent ... but in the modules the developers put what they want, it is the objective of this PR 😉

If you want to keep the consistency on the native modules do not hesitate to ask me, I can provide PRs for the modules mentioned by @khouloudbelguith here https://github.com/PrestaShop/PrestaShop/pull/20653#issuecomment-704790576

**Comment by khouloudbelguith** [comment]
Thanks @LouiseBonnard,@PululuK,

It is ok :heavy_check_mark: 
Issue reported here: https://github.com/PrestaShop/PrestaShop/issues/21361

Thanks!

**Comment by PululuK** [comment]
> Thanks @LouiseBonnard,@PululuK,
> 
> It is ok heavy_check_mark
> Issue reported here: #21361
> 
> Thanks!

I thank you for your patience @khouloudbelguith !
Could you assign it to me please #21361

**Comment by Progi1984** [comment]
Thanks @PululuK & @khouloudbelguith
