### PR TITLE
Prevent adding or editing an invalid product quantity on order

### LINKED ISSUE #17963: I shouldn't be able to add a product with 0 quantity to the order 1/2
#### Describe the bug

I can add a product with 0 quantity to the order & another product is added

#### Expected behavior

I shouldn't be able to add a product with 0 quantity to the order

#### Steps to Reproduce

1. Go to BO > orders > orders > View an order
2. Click on Add a product
3. Select a product and change the quantity for 0
4. Another product is added to the order with quantity 1
5. If I refresh the page, it disappears

**Screenshots**

https://drive.google.com/file/d/117N5MEnHc9KbgicqnSJ0QtSOZVY9mI1D/view?usp=sharing

Legacy behavior: 

capture d'écran_2433

Dependant of #17967
Can edit product with 0 quantity in the Order page 2/2 

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### LINKED ISSUE #17967: Can edit product with 0 quantity in the Order page 2/2
### Expected Behavior 

I shouldn't be allowed to save if I edit a quantity to 0.

### Actual Behavior

I can save a product modification if I edit a quantity to 0.

### Steps to reproduce it

**Edit behavior** as the same issue
1. Go to BO > orders > orders > View an order
2. Click on Edit a product
3. Select a product and change the quantity for 0
4. The product list displays the product with the quantity for 0 and a Total of 0

image

Dependant of #17963
I shouldn't be able to add a product with 0 quantity to the order 1/2 

_Originally posted by @MatShir in https://github.com/PrestaShop/PrestaShop/issues/17963#issuecomment-594462417_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Commands that manage edit and add product to order had no validation regarding the input quantity So from now on an exception is thrown when trying to set a negative or zero value The controller and front js already handled the display of an error correctly (through a json response)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17963 and #17967
| How to test?  | See the issues or more details but basically try to add or edit a product with an invalid quantity (<= 0) the action should not be allowed and an error is displayed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18168)

### CODE REVIEW

File: classes/PrestaShopCollection.php [hunk 1]
```diff
@@ -401,6 +401,21 @@ public function getFirst()
...
+     * @return ObjectModel|false
+     */
+    public function getLast()
+    {
+        $this->getAll();
+        if (!count($this)) {
+            return false;
+        }
+
+        return $this[count($this) - 1];
```
Comment (Progi1984) [inline classes/PrestaShopCollection.php:416]:
```suggestion
        return end($this);
```

File: src/Core/Domain/Order/Exception/InvalidProductQuantityException.php [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+ *
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
```
Comment (Progi1984) [inline src/Core/Domain/Order/Exception/InvalidProductQuantityException.php:25]: `declare(strict_types=1);`

File: tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature [hunk 3]
```diff
@@ -67,47 +71,145 @@ Feature: Order from Back Office (BO)
...
+    When I add products to order "bo_order1" with new invoice and the following products details:
+      | name          | Mug Today is a good day |
+      | amount        | 1                       |
+      | price         | 16                      |
+      | free_shipping | true                    |
+    Then order "bo_order1" should contain 3 products "Mug Today is a good day"
+    Then order "bo_order1" should have 0 invoices
+
+  @order-from-bo
+  Scenario: Add product to an existing Order WITH invoice with free shipping to NEW invoice
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature]:
```suggestion
  Scenario: Add product to an existing Order with invoice with free shipping to new invoice
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature [hunk 4]
```diff
@@ -67,47 +71,145 @@ Feature: Order from Back Office (BO)
...
+    When I add products to order "bo_order1" with new invoice and the following products details:
+      | name          | Mug Today is a good day |
+      | amount        | 2                       |
+      | price         | 16                      |
+      | free_shipping | true                    |
+    Then order "bo_order1" should contain 2 products "Mug Today is a good day"
+    Then order "bo_order1" should have 2 invoices
+
+  @order-from-bo
+  Scenario: Add product to an existing Order WITH invoice with free shipping to last invoice
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_from_bo.feature]:
```suggestion
  Scenario: Add product to an existing Order with invoice with free shipping to last invoice
```

File: classes/PrestaShopCollection.php (hunk 1 above)
Comment (jolelievre) [reply classes/PrestaShopCollection.php:416]: MM, I'm not sure 
I don't want to move the array cursor

File: classes/PrestaShopCollection.php [hunk 5]
```diff
@@ -401,6 +401,21 @@ public function getFirst()
         return $this[0];
     }
 
+    /**
+     * Retrieve the last result.
+     *
+     * @return ObjectModel|false
+     */
+    public function getLast()
```
Comment (matks) [inline classes/PrestaShopCollection.php:409]: Improvement suggestion: add a unit test

**Review by matks — APPROVED** [review]

File: classes/PrestaShopCollection.php (hunk 1 above)
Comment (Progi1984) [reply classes/PrestaShopCollection.php:416]: But how can you be sure that the key of the array is well `count($this) - 1` ?

Comment (jolelievre) [reply classes/PrestaShopCollection.php:416]: Because that's how this class is supposed to behave, it stores db results in `$this->results` which is a regular array (I mean not associative). Besides if you look at the `getFirst` function it uses `return $this[0];` and all the `getOffset` `setOffset` also use an index to access the results

Comment (Progi1984) [reply classes/PrestaShopCollection.php:416]: :ok_hand:

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
This PR correctly fix #17963 and #17967. Thanks @jolelievre
