### PR TITLE
Force refresh of tinymce editors in product page step 1

### LINKED ISSUE #12053: Product summary and description are not always displayed
**Describe the bug**
Product summary and description are not always displayed when you switch language

**To Reproduce**
1. Make sure you have many languages installed
2. Go to Catalog > Product > Edit a product
3. Change language and click on summary and description
4. You don't see always the content

**Screenshots**

capture d ecran_875

https://drive.google.com/file/d/1uxfI5Ezq4nu0V8AqxW9eLEL9PBbuiH6n/view?usp=sharing

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | When switching language on the product page (step 1), the summary and description editors sometimes appear empty, whereas they should not be. Probably TinyMCE does not like to be initialized while invisible so we force the refresh when showing it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12053 
| How to test?  | Be sure to have 5 to 6 languages installed, go to a product edition page and switch the language thanks to the top select box. The summary/description editor should switch correctly without hiding their content.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12234)

### CODE REVIEW

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 1]
```diff
@@ -746,6 +746,14 @@ var form = (function() {
   function switchLanguage(iso_code) {
     $('div.translations.tabbable > div > div.translation-field:not(.translation-label-' + iso_code + ')').removeClass('show active');
     $('div.translations.tabbable > div > div.translation-field.translation-label-' + iso_code).addClass('show active');
+    //Force refresh tinymce editors
+    $('div.translations.tabbable > div > div.translation-field.translation-label-' + iso_code + ' textarea.autoload_rte').each(function(index, textarea) {
```
Comment (matks) [inline admin-dev/themes/default/js/bundle/product/form.js]: I see this string `'div.translations.tabbable > div > div.translation-field.translation-label-'` twice on my screen 😛 dont you want to reuse it to avoid duplicated content ?

Also this way you'll escape the "Line too long" of @PierreRambaud 😄

Comment (PierreRambaud) [reply admin-dev/themes/default/js/bundle/product/form.js]: Do you mean @matks ? :trollface:

**Comment by Quetzacoalt91** [comment]
As far as I know this issue already existing before 1.7.5.0. Shall we target the `develop` branch instead?

**Comment by PierreRambaud** [comment]
@Quetzacoalt91 It has been added by @marionf. WDYT @eternoendless ?

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 1 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js]: OK ^^ fixed

**Comment by jolelievre** [comment]
There are high chances indeed that this bug occurs on the develop branch and is not a regression from 1.7.5

**Review by PierreRambaud — DISMISSED** [review]

**Comment by marionf** [comment]
@jolelievre 

If I change language and click on the tab not selected (summary or description), the content is still hidden

https://drive.google.com/file/d/1c1INUOHCdUkxKDWvpChPLKGOxXtsUHqJ/view?usp=sharing

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 2]
```diff
@@ -745,7 +761,10 @@ var form = (function() {
 
   function switchLanguage(iso_code) {
     $('div.translations.tabbable > div > div.translation-field:not(.translation-label-' + iso_code + ')').removeClass('show active');
-    $('div.translations.tabbable > div > div.translation-field.translation-label-' + iso_code).addClass('show active');
+
+    const langueTabSelector = 'div.translations.tabbable > div > div.translation-field.translation-label-' + iso_code;
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/bundle/product/form.js:765]:
```suggestion
    const langueTabSelector = `div.translations.tabbable > div > div.translation-field.translation-label-${iso_code}`;
```

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 3]
```diff
@@ -74,8 +74,24 @@ $(document).ready(function() {
...
   });
+
+  $('.summary-description-container a[data-toggle="tab"]').on('shown.bs.tab', resetEditor);
 });
 
+/**
+ * Reset active tinyMce editor (triggered when switch language, or switching tabs)
+ */
+function resetEditor() {
+  const languageEditorsSelector = '.summary-description-container .panel.active div.translations.tabbable > div > div.translation-field.active textarea.autoload_rte';
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/bundle/product/form.js]: why not:
```suggestion
  const languageEditorsSelector = '.summary-description-container .panel.active div.translation-field.active textarea.autoload_rte';
```

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 4]
```diff
@@ -74,8 +74,24 @@ $(document).ready(function() {
...
+  $(languageEditorsSelector).each(function(index, textarea) {
+    var editor = tinyMCE.get(textarea.id);
+    if (editor) {
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/bundle/product/form.js:88]: did you try https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#nodechanged ?

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 2 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js:765]: I wish I could but this is an ES6 feature right? this file is from the default name which is not transpiled, so I'm worried about the compatibility with old browsers

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 3 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js]: you're right it's shorter and cleaner!

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 4 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js:88]: I didn't know it, I just tried but it doesn't work unfortunately

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 2 above)
Comment (PierreRambaud) [reply admin-dev/themes/default/js/bundle/product/form.js:765]: Oh, you're right, it is the old theme:(

**Review by PierreRambaud — APPROVED** [review]
