### PR TITLE
Forbid URLS to be added in customer names

### LINKED ISSUE #13524: Problem with customer account creation
**Describe the bug**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Only forbid for customer name and not everywhere
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13524 
| How to test?  | Attempt, from front-office, to create a customer with an URL as first name or last name. Now it is not possible anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13599)

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
Ping @doekia @okom3pom what do you think?

**Comment by doekia** [comment]
> Ping @doekia @okom3pom what do you think?

Sound good to me except I will have also filtered out square brackets [ ], I have no use case how,where,will it allows abuse but better safe than sorry

**Comment by eternoendless** [comment]
Great!

@PierreRambaud Do you want to add them to the regex for good measure?

**Comment by PierreRambaud** [comment]
yes-sir

**Review by doekia — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]

File: js/validate.js [hunk 1]
```diff
@@ -99,9 +99,15 @@ var unicode_hack = (function() {
...
+function validate_isCustomerName(s)
+{
+	var reg = /^(?:[^0-9!<>,;?=+()\/\\@#"°*`\{\}_^$%:¤\[\]|\.。]|[\.。](?:\s|$))*$/;
+	return reg.test(s);
+}
+
 function validate_isName(s)
 {
-	var reg = /^[^0-9!<>,;?=+()@#"°{}_$%:]+$/;
+	var reg = /^[^0-9!<>,;?=+()@#"°\{\}_$%:]+$/;
```
Comment (matks) [inline js/validate.js:110]: Nice fix ! 😉

**Comment by Quetzacoalt91** [comment]
Looks like it's ready for merge @eternoendless

File: classes/Validate.php [hunk 2]
```diff
@@ -156,6 +156,22 @@ public static function isImageSize($size)
...
+     * Check whether given customer name is valid
+     *
+     * @param string $name Name to validate
+     *
+     * @return int 1 if given input is a name, 0 else
+     */
+    public static function isCustomerName($name)
+    {
+        $validityPattern = Tools::cleanNonUnicodeSupport(
+            '/^(?:[^0-9!<>,;?=+()\/\\@#"°*`{}_^$%:¤\[\]|\.。]|[\.。](?:\s|$))*$/u'
```
Comment (123monsite-regis) [inline classes/Validate.php:169]: hi,
i take a look at our real customers databases, and it appears that some customers use the dot as separator like "jean.marc" or "J.R." ,
if there is no sql upgrade , we will have some customers blocked during some objects loads or saving.

regards

Comment (doekia) [reply classes/Validate.php:169]: I did mentionned this case and the fact it should be inserted in an upgrade task on the other thread 
https://github.com/PrestaShop/PrestaShop/pull/13559#issuecomment-487051723
`update ps_customer set firstname = replace(replace(firstname,'.','. '),' ',' ');`
`update ps_customer set lastname = replace(replace(lastname,'.','. '),' ',' ');`

Comment (matks) [reply classes/Validate.php:169]: I dont think a database upgrade is the right thing to do. Imagine this: you update to the latest patch version of Prestashop that states "Protects you against spam" (so you expects this patch to change *nothing*  in your regular shop behavior*) and you find out that this patch modified your database behind your back ?

What about the people that use the lastname as an identifier (because they have nothing better) for a synchronizing system between their shop and their ERP ?

Not to forget the cost of this query on very large databases, might trigger timeouts or deadlocks.

That's why the sql upgrade task does not look a suitable solution for me.

*Which should always be the case for patch versions, but sometimes it cant be avoided. But not here.

Comment (doekia) [reply classes/Validate.php:169]: cost of the query? Just applied those 2 queries on 272455 customer in a breeze, less than 800ms

Comment (eternoendless) [reply classes/Validate.php:169]: I agree with @matks in that it's risky to change existing data without warning, not to mention that the process could potentially be too long to perform during the autoupgrade.

I propose adding a release note explaining the potential problem and suggesting to run similar queries manually when upgrading -- and I insist on the "similar" because `replace('John B. B.', '.', '. ')` returns:
```
"John B.  B. "
```

... and `regexp_replace` is only available on MySql 8+

**Comment by eternoendless** [comment]
Thank you @PierreRambaud
