### PR TITLE
Check quantities at any point of checkout process

### LINKED ISSUE #10762: Stock quantity are not verified at the last step of the checkout
**Describe the bug**

As the remaining quantity in stock is not checked at the last step of the checkout, you are able to arrive in the payment process and to pay a product that is out of stock even if it's not allowed.

**To Reproduce**

1. Set a product quantity to 2 in the BO
2. Add this product to cart, 2 units
3. Go to the last step of the checkout (payment), just before you click "Confirm with an obligation to pay"
4. Now, change quantity of the product to 1 in back-office
5. Click "Confirm with an obligation to pay" on last step of the checkout (payment)
6. You are now able to pay while you shouldn't

**Wanted behavior**
We should check the stock quantity at the last step of the checkout while clicking on "Order with obligation to pay".
If the product is out of stock and if order of out of stock product isn't allowed, then we should bring the user at the cart, display the following error message "The item _product name_ is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted." and disabled the "proceed to checkout" button like below:

capture d'écran_3016

Please note that this "stock quantity check" and this behavior is already present at the previous checkout steps (personal informations, addresses, shipping method) when you click on "Continue"

**Additionnal information**
PrestaShop version: 1.7.0.0 to 1.7.5.0
PHP version: N/A

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Quantity was not checked on last step of checkout and the code to do checks was spread on multiple places. This allowed multiple people (=angry customers) to order same product if they had the checkout funnel already opened for a longer time.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #10762
| How to test?      | See video - https://drive.google.com/file/d/1Dj67yJUux9zub9ZhuFA2024ekvIHMbYt/view?usp=sharing
| Possible impacts? | Shouldn't be

**Notes**
- I removed the checks from PaymentStep. Now everything is checked in OrderController, so it's centralized.
- The final step is a bit different. It submits a payment module form via javascript, so it does not go through orderControoler anymore. I make an ajaxrequest before handing the work to payment module and check if everything is still good. If it's not, I send cart url along and redirect to it.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26048)

### CODE REVIEW

File: themes/_core/js/checkout-payment.js [hunk 1]
```diff
@@ -146,6 +146,19 @@ class Payment {
       return;
     }
 
+    const url = window.location.href;
+    $.post(url, {
+      ajax: 1,
+      action: 'checkProductsStillOrderable',
+    })
+      .then((resp) => {
+        console.log(resp);
```
Comment (NeOMakinG) [inline themes/_core/js/checkout-payment.js]:
```suggestion
```

Comment (Hlavtox) [reply themes/_core/js/checkout-payment.js]: @NeOMakinG 😂😂

**Review by NeOMakinG — DISMISSED** [review]
Can't find something wrong with the JS, did you test the history ? If you go backward/front, does it react properly?

File: controllers/front/OrderController.php [hunk 2]
```diff
@@ -237,6 +237,25 @@ public function displayAjaxselectDeliveryOption()
         ]));
     }
 
+    public function displayAjaxcheckProductsStillOrderable(): void
```
Comment (kpodemski) [inline controllers/front/OrderController.php]:
```suggestion
    public function displayAjaxCheckProductsStillOrderable(): void
```

File: controllers/front/OrderController.php [hunk 3]
```diff
@@ -237,6 +237,25 @@ public function displayAjaxselectDeliveryOption()
...
+    {
+        $responseData = [
+            'allGood' => true,
```
Comment (kpodemski) [inline controllers/front/OrderController.php]:
```suggestion
            'errors' => false,
```

File: controllers/front/OrderController.php [hunk 4]
```diff
@@ -237,6 +237,25 @@ public function displayAjaxselectDeliveryOption()
...
+            'cartUrl' => '',
+        ];
+
+        if ($this->context->cart->isAllProductsInStock() !== true ||
```
Comment (kpodemski) [inline controllers/front/OrderController.php:249]: Maybe it would be good to have these checks in a dedicated method?

File: controllers/front/OrderController.php [hunk 5]
```diff
@@ -237,6 +237,25 @@ public function displayAjaxselectDeliveryOption()
...
+            $this->context->cart->checkAllProductsAreStillAvailableInThisState() !== true ||
+            $this->context->cart->checkAllProductsHaveMinimalQuantities() !== true) {
+            $responseData['allGood'] = false;
```
Comment (kpodemski) [inline controllers/front/OrderController.php]:
```suggestion
            $responseData['errors'] = true;
```

File: controllers/front/OrderController.php [hunk 6]
```diff
@@ -250,15 +269,23 @@ public function initContent()
...
+        if ($this->context->cart->isAllProductsInStock() !== true ||
+            $this->context->cart->checkAllProductsAreStillAvailableInThisState() !== true ||
+            $this->context->cart->checkAllProductsHaveMinimalQuantities() !== true) {
+            $shouldRedirectToCart = true;
         }
 
-        $product = $this->context->cart->checkQuantities(true);
-        if (is_array($product)) {
-            // if there is an issue with product quantities, redirect to cart page
+        // If there was a problem, we redirect the user to cart, cartController deals with the detailed errors
```
Comment (kpodemski) [inline controllers/front/OrderController.php]:
```suggestion
        // If there was a problem, we redirect the user to cart, CartController deals with the detailed errors
```

File: themes/_core/js/checkout-payment.js [hunk 7]
```diff
@@ -146,6 +146,16 @@ class Payment {
       return;
     }
 
+    $.post(window.location.href, {
+      ajax: 1,
+      action: 'checkProductsStillOrderable',
+    })
+      .then((resp) => {
+        if (resp.allGood === false && resp.cartUrl !== '') {
```
Comment (kpodemski) [inline themes/_core/js/checkout-payment.js]:
```suggestion
        if (resp.errors === true && resp.cartUrl !== '') {
```

File: themes/_core/js/checkout-payment.js [hunk 8]
```diff
@@ -146,6 +146,16 @@ class Payment {
...
+          location.href = resp.cartUrl;
```
Comment (kpodemski) [inline themes/_core/js/checkout-payment.js]:
```suggestion
          location.href = resp.cartUrl;
```

I'm not sure about this, I think we should have an event here, and by default, we could redirect, but the developers should have a possibility to override it.

I would go with the
`prestashop.emit('orderConfirmationErrors', function () { // as much usable info as possible, selected carrier? payment method? }`

cc @NeOMakinG @Oksydan what do you think guys?

Comment (NeOMakinG) [reply themes/_core/js/checkout-payment.js]: Looks better yes, so it's overridable!

Comment (Hlavtox) [reply themes/_core/js/checkout-payment.js]: @NeOMakinG Can you implement it into the PR for me? ;-)

Comment (NeOMakinG) [reply themes/_core/js/checkout-payment.js]: Ok, hope to have some time asap

File: classes/checkout/CheckoutPaymentStep.php [hunk 9]
```diff
@@ -53,26 +53,6 @@ public function __construct(
 
     public function handleRequest(array $requestParams = [])
     {
-        $cart = $this->getCheckoutSession()->getCart();
```
Comment (sowbiba) [inline classes/checkout/CheckoutPaymentStep.php:56]: I understand that changes in OrderController::initContent makes "orderability" checked in every step of the order
But why remove the check just before payment ?
Is payment handled by orderController ?

Comment (Hlavtox) [reply classes/checkout/CheckoutPaymentStep.php:56]: @sowbiba Orderability is checked by OrderController on every page load or step change.

Only exception is the last step - confirming the order. It does not go through OrderController at all. Each payment module display is actually a `<form>` that is submitted by JS. I intercept this with an ajax call to OrderController to make sure we can still order it.

Comment (Hlavtox) [reply classes/checkout/CheckoutPaymentStep.php:56]: The check in payment step was unnecessary. :-)

**Review by sowbiba — DISMISSED** [review]
LGTM

File: controllers/front/OrderController.php (hunk 4 above)
Comment (Hlavtox) [reply controllers/front/OrderController.php:249]: @kpodemski Can we do it in another PR and think it through more deeply, not to make scope of this PR bigger?

Because, in order controller, it was checking the "orderability" by `$cart->checkQuantities()`, and in payment step it does it by `$cart->isAllProductsInStock() + $cart->checkAllProductsAreStillAvailableInThisState() + $cart->checkAllProductsHaveMinimalQuantities()`.

I could put those three to dedicated method, but it would be good to rewrite it in a single method, because its not very efficient to load and loop through all cart product three times. So we can make another PR/topic where we can discover what is old, what is new, what is used where in prestashop and possibly make one new nice function. Agree? :-)

Comment (kpodemski) [reply controllers/front/OrderController.php:249]: All right @Hlavtox 👍

**Comment by kpodemski** [comment]
LGTM but I would love to see the feedback from @Matt75 about this one.

**Comment by Matt75** [comment]
It will only works for PaymentModule that use standard confirmation button.

Modern Payment components use Javascript to avoid redirection and Cookie Same-Site directive trouble on returns to the shop.
So for this kind of module, we need to communicate with developers to informs them, they have to make an ajax request to check if Cart is still valid before proceed furthermore.

For example with PayPal Checkout, payment buttons are managed by PayPal SDK and we subscribe to callbacks and events : https://developer.paypal.com/docs/business/checkout/set-up-standard-payments/integrate/
Modern payment gateways proceed like this too, so we need to communicate with developers that integrate this to add this new ajax call before proceed to payment.

This change is not blocking so even if a developer doesn't perform this check, it will works. So it's seems good to me, but the devdocs needs to be amended.

**Comment by kpodemski** [comment]
Thank you for your input @Matt75 :)

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
I've added the Documentation label to keep in mind that we need to have it documented.

**Comment by tswfi** [comment]
@Hlavtox one question. does this also validate cart rules and discounts? I've seen some orders that have "expired" coupon codes and I'm guessing the coupon is validated only when it is added which means that if the coupon expires tomorrow but I add it today and make the order next week it will still have the coupon active.

**Comment by Hlavtox** [comment]
@tswfi No I think it does not, but we can add it (later?). I renamed the function to **checkCartStillOrderable**. We can modify inner workings any time.

**Comment by tswfi** [comment]
@Hlavtox great :+1: After this gets merged I will try to test the coupon and cart rule stuff and if I can find a problem in it I will write a new issue and probably the pr also.

File: controllers/front/OrderController.php [hunk 10]
```diff
@@ -237,6 +237,26 @@ public function displayAjaxselectDeliveryOption()
...
+
+        // TODO - move to separate single function in Cart and also check if discounts and rules are valid
+        if ($this->context->cart->isAllProductsInStock() !== true ||
+            $this->context->cart->checkAllProductsAreStillAvailableInThisState() !== true ||
+            $this->context->cart->checkAllProductsHaveMinimalQuantities() !== true) {
+            $responseData['errors'] = true;
+            $responseData['cartUrl'] = $this->context->link->getPageLink('cart', null, null, ['action' => 'show']);
+        }
+
+        ob_end_clean();
```
Comment (atomiix) [inline controllers/front/OrderController.php]: I think you should remove this ;)
```suggestion
```

Comment (Matt75) [reply controllers/front/OrderController.php]: This line is added before each ajax returns to avoid notice and warning that can broke json response.

I think we should keep it in order to avoid broken checkout tunnel in case of a notice or a warning is printed before json, because we are on the payment step and this is critical to have a response can be parsed by current javascript implementation.

The `ob_start` is on FrontControllerCore : https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/classes/controller/FrontController.php#L329

And many controllers have this line before returns json, for example :
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/AddressController.php#L178
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/AttachmentController.php#L38
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/CartController.php#L174
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/CartController.php#L225
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/GetFileController.php#L300
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/OrderController.php#L230
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/OrderController.php#L320
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/ProductController.php#L423
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0/controllers/front/ProductController.php#L450

Comment (Hlavtox) [reply controllers/front/OrderController.php]: The same goes for https://github.com/PrestaShop/PrestaShop/pull/25353.

@PierreRambaud @atomiix @Matt75 Guys pls agree on one thing and tell me the result 😄

Comment (atomiix) [reply controllers/front/OrderController.php]: I kinda agree with @PierreRambaud, we shouldn't be hiding errors like that. If you don't want warning or notice, ou should configure your php.ini IMO

**Comment by Hlavtox** [comment]
@eternoendless Pls don't block QA, I think that the decision to remove ob_end_clean(); could be made during QA...

**Comment by Matt75** [comment]
@Hlavtox I cannot accept customer can be blocked at latest checkout step because if ajax request fail there are no error message displayed and customer is blocked without any information.

Many modules thanks to hooks or overrides can do things that can broke the ajax returns for example with a notice or warning printed before json.

Error management this not good in this case, what's happens if ajax request fail or cannot be parsed ?

This case should be handled to avoid PaymentModule developers be spammed with unrelated support issues with their code.

You can try with a module hooked on hooks :
- `actionAjaxDieBefore`
- `actionBeforeAjaxDieCartControllerdisplayAjaxUpdate`
- `actionAjaxDieCartControllerdisplayAjaxUpdateBefore`
- Others hooks can be used, but you needs to dive in Cart classes and dependencies to find them 🤯

Try to create a notice or warning with a server configured in dev or try to add unwanted content with a dump() for example.

You can improve ajax error management for example, in order to display a message that's inform you're blocked by an unexpected response.

File: controllers/front/OrderController.php [hunk 11]
```diff
@@ -237,6 +237,25 @@ public function displayAjaxselectDeliveryOption()
...
     }
 
+    public function displayAjaxCheckCartStillOrderable(): void
+    {
+        $responseData = [
+            'errors' => false,
+            'cartUrl' => '',
+        ];
+
+        // TODO - move to separate single function in Cart and also check if discounts and rules are valid
```
Comment (PierreRambaud) [inline controllers/front/OrderController.php]: We can't keep a PR with a TODO like that, I'm sure in 10 years, there will always be this todo ^^

File: controllers/front/OrderController.php [hunk 12]
```diff
@@ -250,15 +269,24 @@ public function initContent()
...
+        // Check the customer meets minimal order amount treshold
         if (count($presentedCart['products']) <= 0 || $presentedCart['minimalPurchaseRequired']) {
-            // if there is no product in current cart, redirect to cart page
-            $cartLink = $this->context->link->getPageLink('cart');
-            Tools::redirect($cartLink);
+            $shouldRedirectToCart = true;
+        }
+
+        // Check that products are still orderable, at any point in checkout
+        // TODO - move to separate single function in Cart and also check if discounts and rules are valid
```
Comment (PierreRambaud) [inline controllers/front/OrderController.php]: Same as previous about todo

File: themes/_core/js/checkout-payment.js [hunk 13]
```diff
@@ -146,6 +155,14 @@ class Payment {
       return;
     }
 
+    $.post(window.location.href, {
```
Comment (PierreRambaud) [inline themes/_core/js/checkout-payment.js]: We shouldn't rerun the `window.location.href`, more if it concerns the legacy page.
Legacy pages are handle depending on `_GET` parameters, meaning if you have a module injecting his own parameters, you will maybe execute code that couldn't be execute.
Please use routes instead.

File: controllers/front/OrderController.php (hunk 11 above)
Comment (Hlavtox) [reply controllers/front/OrderController.php]: @PierreRambaud So what should I do if I don't want to dive into it right now, but don't want it to be forgotten?

File: themes/_core/js/checkout-payment.js (hunk 13 above)
Comment (Hlavtox) [reply themes/_core/js/checkout-payment.js]: ping @NeOMakinG help pls

Comment (Matt75) [reply themes/_core/js/checkout-payment.js]: `window.prestashop.urls.pages.order`

Comment (matks) [reply themes/_core/js/checkout-payment.js]: I believe @Matt75 provided a nice tip to be used ;)

File: controllers/front/OrderController.php (hunk 11 above)
Comment (Hlavtox) [reply controllers/front/OrderController.php]: I made an issue for this: https://github.com/PrestaShop/PrestaShop/issues/27023

**Comment by Hlavtox** [comment]
@PierreRambaud @matks @Matt75 Hi guys, I applied all suggestions. What now?

Either put it to QA or tell me if I should put ob_end_clean(); back, pls

File: themes/_core/js/checkout-payment.js [hunk 14]
```diff
@@ -25,6 +25,15 @@
 import $ from 'jquery';
 import prestashop from 'prestashop';
 
+prestashop.checkout = prestashop.checkout || {};
+
+// eslint-disable-next-line no-unused-vars
+prestashop.checkout.onCheckOrderableCartError = (resp, paymentObject) => {
```
Comment (PierreRambaud) [inline themes/_core/js/checkout-payment.js]:
```suggestion
prestashop.checkout.onCheckOrderableCartError = (resp) => {
```
What's the reason to keep the paymentObject var?

File: controllers/front/OrderController.php (hunk 4 above)
Comment (Hlavtox) [reply controllers/front/OrderController.php:249]: @kpodemski Made an issue for this so we don't forget ;-) https://github.com/PrestaShop/PrestaShop/issues/27023

File: themes/_core/js/checkout-payment.js (hunk 14 above)
Comment (Hlavtox) [reply themes/_core/js/checkout-payment.js]: I think @NeOMakinG added it so payment modules can intercept this depending on payment method selected?

**Review by kpodemski — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Following these steps mentioned in the issue, I still manage to reproduce the issue with your PR:

1. Set a product quantity to 2 in the BO
2. Add this product to cart, 2 units
3. Go to the last step of the checkout (payment), just before you click "Confirm with an obligation to pay"
4. Now, change quantity of the product to 1 in back-office
5. Click "Confirm with an obligation to pay" on last step of the checkout (payment)
6. See error > **You are now able to pay while you shouldn't**

https://www.awesomescreenshot.com/video/6622412?key=0f74e7ded6f8fd51f4428fdbf7cb8a85

Please check and feedback.
Thanks!

**Comment by kpodemski** [comment]
@Hlavtox you probably need to check the quantities after clicking the "I order with an obligation to pay" button, but some of the modules don't use this button from what I remember 🤔

**Comment by Matt75** [comment]
> @Hlavtox you probably need to check the quantities after clicking the "I order with an obligation to pay" button, but some of the modules don't use this button from what I remember 🤔

Yes, but native modules use default button `I order with an obligation to pay` : 
1. https://github.com/PrestaShop/ps_wirepayment
2. https://github.com/PrestaShop/ps_checkpayment
3. https://github.com/PrestaShop/ps_cashondelivery

Modules that replace native button use the hook `displayPaymentByBinaries` likes `ps_checkout`, `atos`and some others

**Comment by PierreRambaud** [comment]
Hi @Hlavtox ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Comment by Hlavtox** [comment]
@kpodemski It worked before, I don't know why it didn't work for Hiba, I will check and reopen.

**Comment by PierreRambaud** [comment]
> @kpodemski It worked before, I don't know why it didn't work for Hiba, I will check and reopen.

I reopen it for you ;)

**Comment by Hlavtox** [comment]
Rebased, will check and fix the remaining issues today. 👍

**Review by NeOMakinG — DISMISSED** [review]
JS is fine for me now 

- Modules are able to override prestashop.checkout methods if they wants
- Modules are able to register to the error event and modify the behavior if they waants
- The feature is working as expected, it will verify stocks before submitting

**Comment by Hlavtox** [comment]
@hibatallahAouadni Can you please retest? We improved it with Valentin. Should work fine!

**Review by atomiix — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I tested the PR with different type of products:
### Simple products: 
It redirects me to the shopping cart page with alert message :heavy_check_mark: 
image
redirect with an error message (same result as Simple Product) :heavy_check_mark: 
### Product with combination: 
redirect with an error message (same result as Simple Product) :heavy_check_mark: 
### Pack of Products:
It depends on the Pack quantities choice:

1. Decrement Pack only: redirect with an error message :heavy_check_mark: 
2. Decrement products in pack only: 

- if we change the quantity of simple product: redirect with an error message :heavy_check_mark: 
- if we change the quantity of product with combination: the order will be submitted and the qty of the product with combinations will be -1 :x: (check the screen record below): 

https://user-images.githubusercontent.com/23308427/156162842-dd8bf2e0-87ce-426e-8b82-2688510b3ef8.mp4

3. Decrement both: same behavior as Decrement product in pack only, the error only occurs with product with combinations

Waiting for your feedback.
Thanks!

**Comment by Hlavtox** [comment]
@hibatallahAouadni That case seems not to be cached by the original functions.

```
$cart->isAllProductsInStock();
$cart->checkAllProductsAreStillAvailableInThisState();
$cart->checkAllProductsHaveMinimalQuantities();
```

Can you please check the same behavior on develop? If you decrement the pack - `if we change the quantity of product with combination`, then go back to checkout and refresh page.

We can fix this in another PR, but I want this already merged, this PR is 18 days with correct code and still not merged.

**Review by PierreRambaud — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Indeed I encounter the same issue on develop, it seems you fixed all cases but this one #27871
Combinations quantity in Pack are not verified at the last step of the checkout
So, LGTM QA :heavy_check_mark: and I created a new issue for the remaining issue.
Hope you can fix it too ASAP :rocket: 

Thanks!

**Comment by NeOMakinG** [comment]
Thanks @Hlavtox , @hibatallahAouadni and every reviewers

**Comment by nsorosac** [comment]
Congrats on this one @Hlavtox and reviewers :clap::clap::clap:

**Comment by NeOMakinG** [comment]
> QA OK without required approvals !? :trollface:

Issuebot, you're so weird
