### PR TITLE
Fix validate medium pass

### LINKED ISSUE #40380: It is possible to validate an average admin password
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the installation page, I can add a average password like : "prestashop" or "Correct Horse Battery Staple"

https://github.com/user-attachments/assets/d60f2e4a-9c7b-4ec7-abbc-8b4a0a512870

### Expected behavior

This should not be possible

### Steps to reproduce

1. On the installation page
2. Fill a password like "prestashop"
3. Next

### PrestaShop version(s) where the bug happened

9.1.0

### How you installed PrestaShop

docker

### PHP version(s) where the bug happened

8.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.1.x
| Description?      |Prevent medium strengh password to be submited 
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        |no
| Deprecations?     |  no
| How to test?      | see #40380 
| UI Tests          |https://github.com/tleon/ga.tests.ui.pr/actions/runs/23531793264
| Fixed issue or discussion?     | Fixes #40380 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

File: admin-dev/themes/new-theme/js/components/form/change-password-control.ts [hunk 1]
```diff
@@ -2,6 +2,10 @@
  * For the full copyright and license information, please view the
  * docs/licenses/LICENSE.txt file that was distributed with this source code.
  */
+/**
```
Comment (nicosomb) [inline admin-dev/themes/new-theme/js/components/form/change-password-control.ts]: license block is duplicated

**Review by nicosomb — CHANGES_REQUESTED** [review]

File: themes/_core/js/theme.js [hunk 2]
```diff
@@ -18,6 +16,8 @@ import './address';
 import {psShowHide} from './common';
 import initEmailFields from './email-idn';
 
+__webpack_public_path__ = window.prestashop.core_js_public_path;
```
Comment (jolelievre) [inline themes/_core/js/theme.js:22]: Why did you need to move this line?
If its position is important for something to work you should add a comment to explain why so a future developer doesn't modify it blindly

File: install-dev/theme/js/configure.js [hunk 3]
```diff
@@ -31,6 +31,34 @@ $(function() {
   });
 
   watchPasswordStrength($('#infosPassword'));
+
+  // Prevent form submit when password does not meet minimum strength (score) or length
+  $('#mainForm').on('submit', function(e) {
```
Comment (jolelievre) [inline install-dev/theme/js/configure.js:37]: `zxcvbn` is used in two places here (I don't know if this could/should be mutualized to have common validation)

Does it mean the other part that handles the `displayFeedback` could display some errors but the form was still submittable? Should these two extra error messages be handled by the `watchPasswordStrength` which could also enabled/disable the submit button as well as displaying these extra errors?

File: admin-dev/themes/new-theme/js/pages/employee/EmployeeForm.ts [hunk 4]
```diff
@@ -51,10 +51,36 @@ export default class EmployeeForm {
...
     this.toggleShopTree();
   }
 
+  /**
+   * Prevent form submit when initial password field has value but does not meet strength requirement.
+   *
+   * @param passwordHandler
+   * @private
+   */
+  private preventSubmitWhenPasswordWeak(passwordHandler: ChangePasswordHandler): void {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/employee/EmployeeForm.ts]: Similar idea to the comment below (sorry I reviewed from the bottom 😅)
Should the `watchPasswordStrength` method block the submit button by enabling/disabling it? (which doesn't mean the submit event doesn't need to be protected because you can also submit by pressing enter in an input)

File: admin-dev/themes/new-theme/js/pages/customer/CustomerForm.ts [hunk 5]
```diff
@@ -17,6 +17,8 @@ export default class CustomerForm {
     );
     passwordHandler.watchPasswordStrength($(customerFormMap.passwordInput));
 
+    this.preventSubmitWhenPasswordWeak(passwordHandler);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/customer/CustomerForm.ts]: See comments below (the order is inversed sorry)

File: admin-dev/themes/new-theme/js/components/form/change-password-control.ts [hunk 6]
```diff
@@ -150,20 +150,40 @@ export default class ChangePasswordControl {
     // Prevent submitting the form if new password is not valid
     $(document).on(
       'submit',
-      $(this.oldPasswordInputSelector).closest('form'),
+      'form',
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/form/change-password-control.ts]: Hmm doesn't it mean you are watching all the forms on the page? For a component that, in essence, will be shared in context we can't anticipate it seems dangerous to check all the forms no?

What guarantees this won't block another form? If the safeguard for this is the early return under then why do it this way instead of watching only the appropriate form?

File: admin-dev/themes/new-theme/js/pages/employee/EmployeeForm.ts [hunk 7]
```diff
@@ -64,6 +67,23 @@ export default class EmployeeForm {
...
 
+    const $passwordInput = $(employeeFormMap.passwordInput);
+    const $form = $passwordInput.closest('form');
+
+    if ($form.length) {
+      $form.on('submit', (e) => {
+        const passwordValue = $passwordInput.val() as string;
+
+        if (passwordValue && passwordValue.length > 0) {
+          $passwordInput.trigger('keyup');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/employee/EmployeeForm.ts]: Why do you need to trigger a change here?

File: install-dev/theme/js/configure.js (hunk 3 above)
Comment (jolelievre) [reply install-dev/theme/js/configure.js:37]: Still the same question, the `watchPasswordStrength` contains the same code? Isn't it possible to move this in a common function used by both the `watchPasswordStrength` function AND this form submit watcher?

File: src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php [hunk 8]
```diff
@@ -175,10 +176,20 @@ public function update($id, array $data)
                     $id
                 );
 
-                $command->setPlainPassword($data['change_password']['new_password'], $this->minLength, $this->maxLength, $this->minScore);
+                $command->setPlainPassword(
+                    $data['change_password']['new_password'],
+                    $this->minLength,
+                    $this->maxLength,
+                    max(PasswordPolicyConfiguration::PASSWORD_SAFELY_UNGUESSABLE, $this->minScore)
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php]: So we can never use a score lower than 3 in the end? Even if it was configured as such in the BO?
If so, we should remove the possibility to use lower values completely or it will be confusing

File: src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php [hunk 9]
```diff
@@ -105,6 +105,9 @@ public function buildForm(FormBuilderInterface $builder, array $options)
         $maxLength = $this->configuration->get(PasswordPolicyConfiguration::CONFIGURATION_MAXIMUM_LENGTH);
         $minLength = $this->configuration->get(PasswordPolicyConfiguration::CONFIGURATION_MINIMUM_LENGTH);
 
+        // Employee passwords must be at least "strong" (score 3)
+        $employeeMinScore = max(PasswordPolicyConfiguration::PASSWORD_SAFELY_UNGUESSABLE, $minScore);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeType.php]: I'm not sure about this one? Was it part of the initial issue?

The merchant can choose to change this value even if we recommend at least 3, but you are removing this possibility with this PR no?

File: themes/_core/js/theme.js (hunk 2 above)
Comment (jolelievre) [reply themes/_core/js/theme.js:22]: Still waiting for an answer to that question

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @tleon

**Review by boherm — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @tleon, 

Thank for your PR, i tested it and it's good for me 

https://github.com/user-attachments/assets/6491ad20-8cbe-4e48-93eb-37671ac9e9ca

https://github.com/user-attachments/assets/4d5b3030-d5fc-4d37-a52f-c303c87c0063

I'm waiting automated tests to approve this PR

Thanks

**Comment by Progi1984** [comment]
@tleon I launched E2E Tests today : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/24124096311

No problem on my side.

**Review by Progi1984 — APPROVED** [review]
