### PR TITLE
Show confirm modal when adding product with new invoice

### LINKED ISSUE #18573: BO - Order page - Missing modal to confirm or cancel the creation of the new invoice
#### Describe the bug

- In the Migrated order page when we select `Create a new invoice` and click "Add" => There is no alert displayed
image

#### Expected behavior

We should have a modal to confirm or cancel the creation of the new invoice

#### Steps to Reproduce

1. Go to `admin-dev/sell/orders/orders/{orderId}/view
2. Make sure order status is not "delivered" and you can add products.
3. Make sure your order has invoice. (to generate one, click `generate invoice` in Documents tab
4. Click `Add product`, search and select the product.
5. In right side of the screen you should see select box with invoices, select option `create new invoice`
6. Click Add 
7. see error => there is no modal to confirm or cancel the creation of the new invoice

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | shows modal to confirm that you want create a new invoice. more #18573
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18573
| How to test?  |Screenshot from 2020-04-15 14-32-35 more here #18573

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18635)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js [hunk 1]
```diff
@@ -180,4 +182,29 @@ export default class OrderProductAdd {
...
+        id: 'modal-test',
+        confirmTitle: modalTranslations['modal.title'],
+        confirmMessage: modalTranslations['modal.body'],
+        confirmButtonLabel: modalTranslations['modal.apply'],
+        closeButtonLabel: modalTranslations['modal.cancel'],
+      }, () => this.onAddProductWithNewInvoiceClick(orderId));
+
+      modal.show();
+    } else {
+      this.addProduct(orderId)
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]:
```suggestion
      this.addProduct(orderId);
```

**Review by Progi1984 — COMMENTED** [review]
Small feedback

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js [hunk 2]
```diff
@@ -180,4 +182,29 @@ export default class OrderProductAdd {
...
+
+  handleAddProductWithConfirmationModal(event) {
+    const invoiceId = parseInt(this.invoiceSelect.val(), 10);
+    const orderId = $(event.currentTarget).data('orderId');
+
+    if (invoiceId === 0) {
+      const modalTranslations = this.confirmNewInvoiceModalTranslations.data('translations');
+
+      const modal = new ConfirmModal({
+        id: 'modal-test',
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: Maybe you should use an id more related to this context like `confirm_new_invoice_modal` ?
@NeOMakinG I never remember if it's better to use `-` or `_` in ids/classes?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig [hunk 3]
```diff
@@ -94,6 +94,18 @@
     {% include '@PrestaShop/Admin/Sell/Order/Order/Blocks/View/Modal/view_all_messages_modal.html.twig' %}
     {% include '@PrestaShop/Admin/Sell/Order/Order/Blocks/View/Modal/view_product_pack_modal.html.twig' %}
   </div>
+
+  <script type="text/html" id="modalTranslationsAddProductWithNewInvoice"
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: It bothers me to create a script tag just to store these translations 🤔
Maybe it could be added on the select field instead? since it's related to the modal

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js (hunk 2 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: this one was indeed forgotten to modify :smile:

Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: I think we've decided to use `-` in classs and id. It can bee seen done well in order create page map.

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig (hunk 3 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: moved to selectbox

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig [hunk 4]
```diff
@@ -59,7 +59,17 @@
...
     <td class="addProductInvoice pr-2">
-      {{ form_row(addProductRowForm.invoice) }}
+      {{ form_row(addProductRowForm.invoice, {
+        'attr': {
+          'data-modal-translations':        {
+            'modal.title': 'Create a new invoice'|trans({}, 'Admin.Actions'),
+            'modal.apply': 'Create'|trans({}, 'Admin.Actions'),
+            'modal.cancel': 'Cancel'|trans({}, 'Admin.Actions'),
+            'modal.close': 'Close'|trans({}, 'Admin.Actions'),
+            'modal.body': 'Are you sure you want to create a new invoice?'|trans({}, 'Admin.Actions')
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]:
```suggestion
            'modal.body': 'Are you sure you want to create a new invoice?'|trans({}, 'Admin.Orderscustomers.Notification')
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig [hunk 5]
```diff
@@ -59,7 +59,17 @@
   <td id="addProductTotalPrice"></td>
   {% if orderForViewing.hasInvoice() %}
     <td class="addProductInvoice pr-2">
-      {{ form_row(addProductRowForm.invoice) }}
+      {{ form_row(addProductRowForm.invoice, {
+        'attr': {
+          'data-modal-translations':        {
+            'modal.title': 'Create a new invoice'|trans({}, 'Admin.Actions'),
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]:
```suggestion
            'modal.title': 'Create a new invoice'|trans({}, 'Admin.Orderscustomers.Feature'),
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig [hunk 6]
```diff
@@ -59,7 +59,17 @@
...
+            'modal.apply': 'Create'|trans({}, 'Admin.Actions'),
+            'modal.cancel': 'Cancel'|trans({}, 'Admin.Actions'),
+            'modal.close': 'Close'|trans({}, 'Admin.Actions'),
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: Does this modal contain both _Cancel_ and _Close_ buttons?
🤔

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js (hunk 2 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: never use underscores, we follow bootstrap rules on selectors, prefer using dash :)

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig (hunk 6 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: uh no, my bad. Which one should I leave?

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: No worries! When there are action verbs at stake, it makes more sense to use the _Cancel_ button. :-)

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js [hunk 7]
```diff
@@ -180,4 +182,28 @@ export default class OrderProductAdd {
...
+        closeButtonLabel: modalTranslations['modal.cancel'],
+      }, () => this.onAddProductWithNewInvoiceClick(orderId));
+
+      modal.show();
+    } else {
+      this.addProduct(orderId);
+    }
+  }
+
+  async onAddProductWithNewInvoiceClick(orderId) {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: Out of curiosity, why do you need async/await here, but not on `handleAddProductWithConfirmationModal` when you call the same `addProduct` method?

Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js]: Indeed its useless. Modified :heavy_check_mark:

**Comment by zuk3975** [comment]
Applied wording modifiactions and last feedback fixes. :heavy_check_mark:

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig [hunk 8]
```diff
@@ -59,7 +59,16 @@
   <td id="addProductTotalPrice"></td>
   {% if orderForViewing.hasInvoice() %}
     <td class="addProductInvoice pr-2">
-      {{ form_row(addProductRowForm.invoice) }}
+      {{ form_row(addProductRowForm.invoice, {
+        'attr': {
+          'data-modal-translations':        {
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]:
```suggestion
          'data-modal-translations': {
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig [hunk 9]
```diff
@@ -59,7 +59,16 @@
...
+            'modal.title': 'Create a new invoice'|trans({}, 'Admin.Orderscustomers.Feature'),
+            'modal.apply': 'Create'|trans({}, 'Admin.Actions'),
+            'modal.cancel': 'Cancel'|trans({}, 'Admin.Actions'),
+            'modal.body': 'Are you sure you want to create a new invoice?'|trans({}, 'Admin.Orderscustomers.Notification')
+          }|json_encode|replace("'", "&#39;")|raw|trim
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: Not a good idea to use json encode here.
Use as many data attributes as there are.
This, plus the raw isn't a good idea.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Json_encode is not a good idea in the template

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig (hunk 9 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: @zuk3975 so as modified in this PR https://github.com/PrestaShop/PrestaShop/pull/18690
Seems like the `|replace("'", "&#39;")|raw` is useless and potentially introduce security breach So you should be able to remove it

Comment (zuk3975) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: okay

**Comment by zuk3975** [comment]
> Json_encode is not a good idea in the template

Implemented separate data attributes instead. :heavy_check_mark:

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hello @zuk3975, thanks for your contribution, would you mind to rebase your pull request and rebuild assets before merging ? Thanks

**Comment by zuk3975** [comment]
@Progi1984 :heavy_check_mark:

**Comment by matks** [comment]
Thank you @zuk3975

**Comment by matks** [comment]
Closing and re-opening to reset Travis

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]
