### PR TITLE
Do not use cache while checking if an order exists

### LINKED ISSUE #11115: Duplicate order reference for different order 2/2
For the second time we have a duplicate reference for two different orders, the first time both orders were created at the very same time, the second time the orders were created with 1 second difference.

**Describe the bug**

So far it happened twice within a month or so, with hundreds of orders created just fine. We are unable to find out why so there are no steps to reproduce this at the moment, sorry.

Different order, same reference, different customer, different cart, same (or very close) date_add:

"id_order";"reference";"id_customer";"id_cart";"invoice_date";"date_add"
"1125";"C18101001125";"143131";"6367";"2018-10-10 22:06:36";"2018-10-10 22:06:36"
"1126";"C18101001125";"143130";"6372";"2018-10-10 22:06:36";"2018-10-10 22:06:36"
"2745";"C18102102744";"94587";"15912";"2018-10-21 21:01:59";"2018-10-21 21:01:59"
"2746";"C18102102744";"62536";"15904";"2018-10-21 21:02:00";"2018-10-21 21:02:00"

**Additionnal information**
PrestaShop version: 1.7.4.0
PHP version: 7.0

---
> Originally posted by @matks 

@MatShir I confirm that this issue is a global mess 😅 

I think many people observe the same issue (= duplicate order references) but there are actually multiple usecases, some which are faulty, some which are not.

I have noticed:

## Duplicate order references when there is an order split

This usecase is not a bug ✅  . When a cart contains multiple products that cannot be shipped by a single carrier, then the order will be split into sub-orders. Each sub-order is being shipped by a different carrier **but they all share the same order reference**.

## Duplicate order with different shipping adresses

> In my last investigations, it can be related to addresses: sometimes 2 shipping addresses ID are sended in customer cart on PS1.7 but one of this address is deleted=1 in database, so that can create some problems like wrong shipping amount or wrong discounts.

It seems there might be a issue related to customer using a deleted address but this seems to be random so it cannot be reproduced easily.

➡️  possibly a bug but as we dont have a step-by-step 100% reproductible scenario there is nothing we can do

## Duplicate order references with advanced warehouse management

> We had this problem on a mono-shop with advanced stock management activated and it disappeared when advanced stock management has been unabled.

It seems there might be a issue related to using advanced stock management but AFAIK this comes from a module, not the Core then ? 🤔 

## Wrong invoice number assignment

Contributor @Alexandre17220 mentioned some wrong code in the logic of invoice number generation that is prone to race conditions issues.

# Summary

As I said, I think many people observe the same issue (= duplicate order references) but there are actually multiple usecases, some which are faulty, some which are not. This GitHub issue is mixing all of these which is making the situation more ambiguous rather than helping. I suggest closing and locking this issue and opening new issues, one per _reproductible_ usecase to sort it out. Nothing will come out of this issue in its current state, there is too much informations that we cannot act on.

---
https://github.com/PrestaShop/PrestaShop/issues/11115#issuecomment-466052440

the source code is very simple for understand the problem   : 

```
public static function setLastInvoiceNumber($order_invoice_id, $id_shop)
    {
        if (!$order_invoice_id) {
            return false;
        }

        $number = Configuration::get('PS_INVOICE_START_NUMBER', null, null, $id_shop);
        // If invoice start number has been set, you clean the value of this configuration
        if ($number) {
            Configuration::updateValue('PS_INVOICE_START_NUMBER', false, false, null, $id_shop);
        }

        $sql = 'UPDATE `'._DB_PREFIX_.'order_invoice` SET number =';

        if ($number) {
            $sql .= (int)$number;
        } else {
            $getNumberSql = '(SELECT new_number FROM (SELECT (MAX(`number`) + 1) AS new_number
                FROM `'._DB_PREFIX_.'order_invoice`'.(Configuration::get('PS_INVOICE_RESET') ?
                ' WHERE DATE_FORMAT(`date_add`, "%Y") = '.(int)date('Y') : '').') AS result)';
            $getNumberSqlRow = Db::getInstance()->getRow($getNumberSql);
            $newInvoiceNumber = $getNumberSqlRow['new_number'];
            $sql .= $newInvoiceNumber;
        }

        $sql .= ' WHERE `id_order_invoice` = '.(int)$order_invoice_id;

        return Db::getInstance()->execute($sql);
    }
```

**SELECT (MAX(`number`) + 1)**

---

https://github.com/PrestaShop/PrestaShop/issues/11115#issuecomment-466335070

```
SELECT (MAX(`number`) + 1)
```

I see, so this is a race condition where two orders may get the same id. Nice find!

### LINKED ISSUE #17266: Duplicated orders from the same cart
We have found a bug which allows to create duplicated orders from the same cart. In order to check if the shop has this kind of problem, you can execute the following MySQL query:

SELECT 
	id_order,
	GROUP_CONCAT(id_order), 
	count(id_cart), 
	GROUP_CONCAT(reference),
	date_add
FROM ps_orders
GROUP BY id_cart
HAVING COUNT(id_cart) > 1
ORDER BY `ps_orders`.`id_order` DESC

In the following screenshoot you can see that two identical orders have been created at the same time:
http://soy.es/screenshots/issues_17266_01.jpg

If we look at the carts, we see that two different orders were created from the same cart:
http://soy.es/screenshots/issues_17266_02.jpg

When we revise the code, in order to find the error, we see that in the Cart.php class there is a function which checks if there is already an order for that cart. This function, orderExists(), has a cache:
http://soy.es/screenshots/issues_17266_03.jpg

It is quite likely that the bug comes from this cache. We belive that each time the shop checks if an order exists from a cart may be verified with the data base directly, not with a cache:
http://soy.es/screenshots/issues_17266_04.jpg

This function is called before creating an order in the validateOrder() function from the PaymentModule class:
http://soy.es/screenshots/issues_17266_05.jpg

### LINKED ISSUE #20641: Duplicate order reference for different order 1/2
#### Describe the bug

The function orderExists() from Cart.php has been modified in order to use only the cache when the order exists, avoiding the issue with duplicated orders.
**Screenshots**

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x 
| Description?  | The function orderExists() from Cart.php has been modified in order to use only the cache when the order exists, avoiding the issue with duplicated orders.<br>Original pull request #17302
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20641 
| How to test?  | See #20641 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19139)

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -1628,15 +1628,9 @@ public function _addCustomization($id_product, $id_product_attribute, $index, $t
...
-            $result = (bool) Db::getInstance()->getValue('SELECT count(*) FROM `' . _DB_PREFIX_ . 'orders` WHERE `id_cart` = ' . (int) $this->id);
-            Cache::store($cache_id, $result);
+        $result = (bool) Db::getInstance()->getValue('SELECT count(*) FROM `' . _DB_PREFIX_ . 'orders` WHERE `id_cart` = ' . (int) $this->id);
 
-            return $result;
-        }
-
-        return Cache::retrieve($cache_id);
+        return $result;
     }
```
Comment (matthieu-rolland) [inline classes/Cart.php:1635]: > The function orderExists() from Cart.php has been modified **in order to use only the cache when the order exists**

Here it seems like the cache is never used in the **orderExists** function, is it on purpose?

Comment (eternoendless) [reply classes/Cart.php:1635]: The cache only makes sense if it's invalidated properly. If an order is checked, then deleted, then checked again it would seem as if it wasn't deleted. So yeah, I think it's correct. However I'm interested in knowing why it was added in the first place.

Comment (PierreRambaud) [reply classes/Cart.php:1635]: The ugly reason: https://github.com/PrestaShop/PrestaShop/commit/a7869a1f06c32978def39d4ab9ff9b2eebe14344

**Comment by PierreRambaud** [comment]
PR rebased to fix CS

**Review by Progi1984 — DISMISSED** [review]

File: classes/Cart.php (hunk 1 above)
Comment (matthieu-rolland) [reply classes/Cart.php:1635]: 👍

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by prestamodule** [comment]
@PierreRambaud does this PR intent that you should use `getValue(<query>, false)` too ? WDYT ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud does this PR intent that you should use `getValue(<query>, false)` too ? WDYT ?

Nice catch, didn't know about this (ugly) SQL "cache" :sweat_smile:

**Review by Progi1984 — APPROVED** [review]

**Comment by colinegin** [comment]
Hello guys,

is this PR targeting the develop branch or the 1.7.7.x branch ? 
The milestone indicated is 1770 while the branch seems to be develop.

Thanks !

**Comment by PierreRambaud** [comment]
> Hello guys,
> 
> is this PR targeting the develop branch or the 1.7.7.x branch ?
> The milestone indicated is 1770 while the branch seems to be develop.
> 
> Thanks !

Forget to change the Pull request description, my bad

**Comment by Robin-Fischer-PS** [comment]
Review needed for QA, thanks !

Also, if there is an actual scenario to test, we would really appreciate it, since in the original issue, the bug seems to be "random", and has never been reproduced.

If there is no scenario, would a regression test be sufficient ?

**Comment by PierreRambaud** [comment]
> Review needed for QA, thanks !
> 
> Also, if there is an actual scenario to test, we would really appreciate it, since in the original issue, the bug seems to be "random", and has never been reproduced.
> 
> If there is no scenario, would a regression test be sufficient ?

Yes, only a non-regression test is needed ;)

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Regression tests done on order and cart, OK for me, thanks !

**Comment by Progi1984** [comment]
Thanks @PierreRambaud

File: classes/PaymentModule.php [hunk 2]
```diff
@@ -377,7 +377,7 @@ public function validateOrder(
                     $transaction_id = null;
                 }
 
-                if (!$order->addOrderPayment($amount_paid, null, $transaction_id)) {
+                if (!isset($order) || !$order->addOrderPayment($amount_paid, null, $transaction_id)) {
```
Comment (jf-viguier) [inline classes/PaymentModule.php:380]: Is there a relation between this isset and the duplicate order issue ?

Comment (kpodemski) [reply classes/PaymentModule.php:380]: I don't think so, for the $order to be not defined `$package_list` must not exists which is hardly possible but I guess @PierreRambaud just wanted to make sure ;)
