### PR TITLE
Clear Module::getModuleIdByName_ when installing a module

### LINKED ISSUE #21825: Configuration button no longer appears after installation
#### Describe the bug

configuration button no longer appears after installation in catalog module.

#### Expected behavior

Button should be appear.

#### Steps to Reproduce

1. Go to BO -> Modules -> Catalog module
2. Click on "Install"
3. See error

**Screenshots**
Capture d’écran 2020-11-10 à 09 25 22

https://drive.google.com/file/d/1yCwvE2ja8srE3BhP6Z-wT9meFsVCJJOL/view

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Because of a cache key not cleared when installing a module, the module couldn't be found when checking if the employee can perform actions on it
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21825
| How to test?      | Please see #21825
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24286)

### CODE REVIEW

File: classes/module/Module.php [hunk 1]
```diff
@@ -425,6 +425,7 @@ public function install()
         $this->id = Db::getInstance()->Insert_ID();
 
         Cache::clean('Module::isInstalled' . $this->name);
+        Cache::clean('Module::getModuleIdByName_' . pSQL($this->name));
```
Comment (matks) [inline classes/module/Module.php:428]: @atomiix Can you explain how the cache becomes wrong?

Here is how the cache is being used
```
public static function getModuleIdByName($name)
    {
        $cache_id = 'Module::getModuleIdByName_' . pSQL($name);
        if (!Cache::isStored($cache_id)) {
            $result = (int) Db::getInstance()->getValue('SELECT `id_module` FROM `' . _DB_PREFIX_ . 'module` WHERE `name` = "' . pSQL($name) . '"');
            Cache::store($cache_id, $result);

            return $result;
        }

        return Cache::retrieve($cache_id);
    }
```

Why do we need to clear the cache when we install a module? I understand we might need to clear it when we upgrade or uninstall a module, but I would say "before a module is installed there is no cache entry"?

Comment (atomiix) [reply classes/module/Module.php:428]: @matks as soon as you call `getModuleIdByName()` you'll have a cache entry, also, when calling `isInstalled()` it will also call `getModuleIdByName()`...

Comment (matks) [reply classes/module/Module.php:428]: I see. I approve the PR.

Suggestion but it's out of scope: improve `getModuleIdByName()` so that it only registers cache entries for valid data 😆

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
I tried these steps:
1. Install a module that contains a configuration page or not via the module catalog page 
2. Disable a module / uninstall / reset / enable
3. Install a module via the "upload module button"
4. Try to click to configure a module after installing it

https://drive.google.com/file/d/1sWzcuVi3QyrKJb0URT6Al9SKGTEWGd8G/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
