### PR TITLE
Fix upgrade from 1.6.1.24 to 1.7.8.x

### LINKED ISSUE #24631: Upgrade issue 1.6.24 to 1.7.8.x
**Upgrade issues** 

There were a few changes that prevented the upgrade to complete: <ul><li>`Language::getCountry()` required a string but null could be passed. Using `Language->getLocale()` instead of `Language->locale` solve this issue</li><li>The `Tab` structure changed and 2 new fields (`wording` & `wording_domain`) have been added but are not present yet when migrating the tab in the 1.7.0.0.sql script file. Unsetting those 2 keys from the data array solve this issue</li><li>`$this->translator->getSourceString()` could return an `int` in some cases, breaking the return type and leading to an exception. Casting the returned value to `string` solve the issue</li></ul>

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | There were a few changes that prevented the upgrade to complete: <ul><li>`Language::getCountry()` required a string but null could be passed. Using `Language->getLocale()` instead of `Language->locale` solve this issue</li><li>The `Tab` structure changed and 2 new fields (`wording` & `wording_domain`) have been added but are not present yet when migrating the tab in the 1.7.0.0.sql script file. Unsetting those 2 keys from the data array solve this issue</li><li>`$this->translator->getSourceString()` could return an `int` in some cases, breaking the return type and leading to an exception. Casting the returned value to `string` solve the issue</li></ul>
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | Try to migrate from 1.6.1.24 to a build of 1.7.8.x, it should work
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24242)

### CODE REVIEW

**Review by sowbiba — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

During upgrade, I have the following SQL error. The upgrade is however completed, the error does not seem to block totally the upgrade. 

`SQL 1.7.8.0 1064 in INSERT IGNORE INTO `ps_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES (NULL, 'actionPresentCart', 'Cart Presenter', 'This hook is called before a cart is presented', '1'), (NULL, 'actionPresentOrder', 'Order footer', 'This hook is called before an order is presented', '1'), (NULL, 'actionPresentOrderReturn', 'Order Return Presenter', 'This hook is called before an order return is presented', '1'), (NULL, 'actionPresentProduct', 'Product Presenter', 'This hook is called before a product is presented', '1'), (NULL, 'displayBanner', 'Display Banner', 'Use this hook for banners on top of every pages', '1'), (NULL, 'actionModuleUninstallBefore', 'Module uninstall before', 'This hook is called before module uninstall process', '1'), (NULL, 'actionModuleUninstallAfter', 'Module uninstall after', 'This hook is called at the end of module uninstall process', '1'), (NULL, 'displayCartModalContent', 'Cart Presenter', 'This hook displays content in the middle of the window that appears after adding product to cart', '1'), (NULL, 'displayCartModalFooter', 'Cart Presenter', 'This hook displays content in the bottom of window that appears after adding product to cart', '1'), (NULL, 'displayHeaderCategory', 'Category header', 'This hook adds new blocks above the products listing in a category/search', '1'), (NULL, 'actionCheckoutRender', 'Checkout process render', 'This hook is called when checkout process is constructed', '1'), (NULL, 'actionPresentProductListing', 'Product Listing Presenter', 'This hook is called before a product listing is presented', '1'), (NULL, 'actionGetProductPropertiesAfterUnitPrice', 'Product Properties', 'This hook is called after defining the properties of a product', '1'), (NULL, 'actionProductSearchProviderRunQueryBefore', 'Runs an action before ProductSearchProviderInterface::RunQuery()', 'Required to modify an SQL query before executing it', '1'), (NULL, 'actionProductSearchProviderRunQueryAfter', 'Runs an action after ProductSearchProviderInterface::RunQuery()', 'Required to return a previous state of an SQL query or/and to change a result of the SQL query after executing it', '1'), (NULL, 'actionOverrideEmployeeImage', 'Override Employee Image', 'This hook is used to override the employee image', '1'), (NULL, 'actionFrontControllerSetVariables', 'Add variables in JavaScript object and Smarty templates', 'Add variables to javascript object that is available in Front Office. These are also available in smarty templates in modules.your_module_name.', '1'), (NULL, 'displayAdminGridTableBefore', 'Display before Grid table', 'This hook adds new blocks before Grid component table.', '1'), (NULL, 'displayAdminGridTableAfter', 'Display after Grid table', 'This hook adds new blocks after Grid component table.', '1'), (NULL, 'displayAdminOrderCreateExtraButtons', 'Add buttons on the create order page dropdown', 'Add buttons on the create order page dropdown', '1') (NULL, 'actionProductFormBuilderModifier', 'Modify product identifiable object form', 'This hook allows to modify product identifiable object form content by modifying form builder data or FormBuilder itself', '1') (NULL, 'actionBeforeUpdateProductFormHandler', 'Modify product identifiable object data before updating it', 'This hook allows to modify product identifiable object form data before it was updated', '1') (NULL, 'actionAfterUpdateProductFormHandler', 'Modify product identifiable object data after updating it', 'This hook allows to modify product identifiable object form data before it was updated', '1') (NULL, 'actionBeforeCreateProductFormHandler', 'Modify product identifiable object data before creating it', 'This hook allows to modify product identifiable object form data before it was created', '1') (NULL, 'actionAfterCreateProductFormHandler', 'Modify product identifiable object data after creating it', 'This hook allows to modify product identifiable object form data after it was created', '1'): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(NULL, 'actionProductFormBuilderModifier', 'Modify product identifiable object f' at line 22`


Can you check it ? Thanks !

File: install-dev/upgrade/php/migrate_tabs_17.php [hunk 1]
```diff
@@ -104,6 +104,12 @@ public function createEntityTab($identifier, array $data, array $data_lang): voi
         if (isset($data['enabled'])) {
             unset($data['enabled']);
         }
+        if (isset($data['wording'])) {
```
Comment (jolelievre) [inline install-dev/upgrade/php/migrate_tabs_17.php:107]: This would be worth a comment at least
Also I understand that you need to remove this to upgrade from 1.6 to 1.7

But doesn't that also mean that it won't work for more advanced versions that are updated? unless the `XmlLoader1700` class is only used during a step between 1.6 and 1.7.0.0? So the data should be correctly integrated/updated in a later step?

**Review by Progi1984 — APPROVED** [review]

File: install-dev/upgrade/php/migrate_tabs_17.php (hunk 1 above)
Comment (PierreRambaud) [reply install-dev/upgrade/php/migrate_tabs_17.php:107]: Data will be correctly upgraded from 1.6 to 1.7.0.0, the problem occurs only with the latest 1.7.8.0 because both keys have been added recently

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

I checked the upgrade from 1.6.1.24 and from 1.7.7.2 to 1.7.8.0 with your PR : 

- No error during upgrade
- After upgrade, BO and FO looks fine
- Tested some actions on BO (install module, edit order, add discount, edit payment method...)
- Tested some actions on FO (log in, log out, make an order, add a discount...)

And...

all-good-its-all-good

QA :heavy_check_mark: !

**Comment by atomiix** [comment]
Thanks @Robin-Fischer-PS !
