### PR TITLE
Fix bugs occuring when an order state is deleted but still assigned to orders

### LINKED ISSUE #19098: Undefined index Notice error in debug mode when deleting a custom order status
#### Describe the bug

This is issue #16657, which has already been raised, and closed, though I think there is an issue here.
The problem comes if an order status has been removed (or as in the original bug report the mapping between order status has not been completed correctly).

I think you can also recreate this by creating an order using paypal for example, and then uninstalling the paypal module.  The order remains, but the status does not, this then causes the error.

As explained in the original bug report, in these circumstances, $val['id_order_state'] below is not guaranteed to have a value, can be null, and then this code generates the Notice error in debug mode, and it's not possible to load the page even to cancel the order.

`
foreach ($res as $key => $val) {
    $res[$key]['order_state'] = 
    $indexedOrderStates[$val['id_order_state']]['name'];            
    $res[$key]['invoice'] = $indexedOrderStates[$val['id_order_state']]['invoice'];
     $res[$key]['order_state_color'] = $indexedOrderStates[$val['id_order_state']]['color'];
}
`
#### Expected behavior

Customer page should open without error.

#### Steps to Reproduce

1. Enable debug mode
2. Create a new order status
3. Raise a new order, and assign the order the status you created.
4. Delete the order status
5. Try to load the customer screen - Error
6. Assign the order a different order status
7. Load the customer screen again - Now it loads.

**Screenshots**
image

If applicable, add screenshots or screen recordings to help explain your problem.
image

image

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Some pages would throw exceptions when a deleted order state was still assigned to an order. This pr transforms the order state hard delete into a soft delete, also it keeps order state selectors from displaying deleted states, except if the current state is deleted. 
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19098
| How to test?  | **1-** In FO, create an order<br>**2-** In BO, create a new order state<br>**3-** In BO, assign this state to the order previously created<br>**4-** In BO, delete the order state previously created<br>**5-** In BO, go to the order list page => the order state of the last created order should still be displayed (with the mention "(deleted)".<br>**6-** In BO, go the detail order page of this order, the status should be selected with the mention "(selected)"<br>**7-** In BO, still in the order detail page, if you click on customer detail, the page should display (no exception)<br>**8-** In FO, in the order history page, the status should display correctly (without any mention)<br>**9-** In BO, both in order list page and in order detail page, if you select another state, the old state should disappear from the selector. <br>**10-** All deleted states should not appear in selectors, except if they are currently selected

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19581)

### CODE REVIEW

File: src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php [hunk 1]
```diff
@@ -51,31 +53,46 @@ final class OrderStateByIdChoiceProvider implements FormChoiceProviderInterface,
...
     {
         $orderStates = $this->orderStateDataProvider->getOrderStates($this->languageId);
         $choices = [];
 
         foreach ($orderStates as $orderState) {
+            if ($orderState['deleted'] == 1 && (empty($options['current_state']) || $options['current_state'] != $orderState['id_order_state'])) {
+                continue;
+            }
+            $orderState['name'] .= $orderState['deleted'] == 1 ? ' ' . $this->translator->trans('(deleted)', [], '') : '';
             $choices[$orderState['name']] = $orderState['id_order_state'];
```
Comment (matthieu-rolland) [inline src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php:96]: @LouiseBonnard here we will display the mention `(deleted)` with parenthesis, following the order status name, if the status has been deleted. Do you have any idea about what domain we should use ?

Comment (LouiseBonnard) [reply src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php:96]: @Junebyun is to one to help you get the proper domain. ;-)

Comment (Junebyun) [reply src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php:96]: @matthieu-rolland Hi! If I got it right the _(deleted)_ message would appear in the BO, correct?

Comment (matthieu-rolland) [reply src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php:96]: yes 👍 we have a selector with a list of order statuses (ex: "waiting for payment"), and we will add `(deleted)` when the currently selected status is deleted so that the user knows that once he selects another order status this one will disappear.

Comment (Junebyun) [reply src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php:96]: @matthieu-rolland Hi! You can put it in the _Admin.Global_ domain :)

File: classes/order/OrderState.php [hunk 2]
```diff
@@ -114,19 +114,20 @@ class OrderStateCore extends ObjectModel
      * Get all available order statuses.
      *
      * @param int $id_lang Language id for status name
+     * @param bool $getDeletedStates
      *
      * @return array Order statuses
      */
-    public static function getOrderStates($id_lang)
+    public static function getOrderStates($id_lang, $getDeletedStates = false)
```
Comment (jolelievre) [inline classes/order/OrderState.php]: The parameter seems a bit confusing (double negative) Maybe use `$filterDeleted = true` instead?

File: src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php (hunk 1 above)
Comment (matthieu-rolland) [reply src/Core/Form/ChoiceProvider/OrderStateByIdChoiceProvider.php:96]: @Junebyun thanx 👍 done

File: controllers/admin/AdminStatusesController.php [hunk 3]
```diff
@@ -622,7 +622,10 @@ public function postProcess()
             if (!$order_state->isRemovable()) {
                 $this->errors[] = $this->trans('For security reasons, you cannot delete default order statuses.', [], 'Admin.Shopparameters.Notification');
             } else {
-                return parent::postProcess();
+                $order_state->deleted = 1;
```
Comment (jolelievre) [inline controllers/admin/AdminStatusesController.php]: So it's always a soft delete even if the state has never been used?

Comment (matthieu-rolland) [reply controllers/admin/AdminStatusesController.php]: Yes

Not that it would be difficult to implement, but I thought it would add overall complexity to have sometimes a soft delete and sometimes a hard delete, do you think it's worth it?

Comment (jolelievre) [reply controllers/admin/AdminStatusesController.php]: It's not mandatory for sure, but once we validate and release this behaviour we won't be able to change it back without a BC Maybe this should be discussed with @PrestaShop/prestashop-product-team

Comment (matthieu-rolland) [reply controllers/admin/AdminStatusesController.php]: @colinegin @MatShir hello guys, do you see a possible use case where doing a hard delete would be better than doing a soft delete?

**Comment by matks** [comment]
Re-running Travis

File: controllers/admin/AdminStatusesController.php (hunk 3 above)
Comment (colinegin) [reply controllers/admin/AdminStatusesController.php]: i see 2 potential problems/risks : 
- can it cause a performance problem if there are thousands / hundreds of thousands order statuses in the database with soft delete status ?
- what happens if i try to create an order status that i had decided to delete in the past ? Will i get an error or is it possible to "undelete" an order that was soft deleted ?

**Comment by jolelievre** [comment]
@matthieu-rolland travis sanity tests kept failing so I just rebase the branch ;)

File: controllers/admin/AdminStatusesController.php (hunk 3 above)
Comment (jolelievre) [reply controllers/admin/AdminStatusesController.php]: 1- I think there can only be drawbacks in BO as in any other parts the soft deleted states are ignored
2- if you deleted one and recreate it this will be a new record

Comment (jolelievre) [reply controllers/admin/AdminStatusesController.php]: So if we always soft delete them regardless of their use they will keep piling up But then maybe this should be check directly in `OrderState::delete` method, so the behaviour will remain the same no matter where it's called (a module, the legacy controller, the migrated page)

File: classes/order/OrderState.php [hunk 4]
```diff
@@ -114,19 +114,22 @@ class OrderStateCore extends ObjectModel
...
      *
      * @param int $id_lang Language id for status name
+     * @param bool $getDeletedStates
      *
      * @return array Order statuses
      */
-    public static function getOrderStates($id_lang)
+    public static function getOrderStates($id_lang, $filterDeleted = true)
     {
+        $deletedStates = $filterDeleted ? 'WHERE deleted = 0' : '';
```
Comment (jolelievre) [inline classes/order/OrderState.php]:
```suggestion
        $deletedStates = $filterDeleted ? ' WHERE deleted = 0' : '';
```

File: controllers/admin/AdminStatusesController.php (hunk 3 above)
Comment (kpodemski) [reply controllers/admin/AdminStatusesController.php]: @jolelievre @colinegin 

order states are so rarely deleted that it shouldn't be an issue here, if we have `softDelete` method available from 1.7.7 we can - as a developers - think about proper indexes if we need more performance :) but it's not something what should be done in core IMO

File: classes/order/OrderState.php (hunk 4 above)
Comment (matthieu-rolland) [reply classes/order/OrderState.php]: @jolelievre done ! thanx

File: classes/ObjectModel.php [hunk 5]
```diff
@@ -887,6 +887,29 @@ public function deleteSelection($ids)
...
+     * @throws PrestaShopException
+     */
+    public function softDelete()
+    {
+        $definitions = ObjectModel::getDefinition($this);
+
+        if (empty($definitions['fields']['deleted'])) {
+            throw new PrestaShopException('Field "deleted" is missing from definition in object model ' . get_class($this));
+        }
+        if (!array_key_exists('deleted', $this)) {
```
Comment (PierreRambaud) [inline classes/ObjectModel.php]: Please don't test with array_key_exists for object :) It's not compatible with PHP7.4

Comment (PierreRambaud) [inline classes/ObjectModel.php]:
```suggestion
        if (!array_key_exists('deleted', get_object_vars($this))) {
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Just a little comment about PHP 7.4 compatibility

File: classes/ObjectModel.php (hunk 5 above)
Comment (jolelievre) [reply classes/ObjectModel.php]: What about this? Does it still work in 7.4?

```suggestion
        if (!property_exists($this, 'deleted')) {
```

Comment (matthieu-rolland) [reply classes/ObjectModel.php]: thanx ! done (yes it should work in 7.4)

Comment (matthieu-rolland) [reply classes/ObjectModel.php]: thanx, done!

File: controllers/admin/AdminStatusesController.php (hunk 3 above)
Comment (matthieu-rolland) [reply controllers/admin/AdminStatusesController.php]: thank you for your input @kpodemski ! you're right, and it has been decided that it will be soft delete only.

**Review by jolelievre — DISMISSED** [review]

File: classes/ObjectModel.php (hunk 5 above)
Comment (PierreRambaud) [reply classes/ObjectModel.php]: Nope nope nope, the `property_exists` is also checking for private and protected property :scream:

Comment (PierreRambaud) [reply classes/ObjectModel.php]: Since it's related to ObjectModel, maybe people are using `private $deleted;` :sweat_smile:

Comment (PierreRambaud) [reply classes/ObjectModel.php]: image

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

File: classes/ObjectModel.php (hunk 5 above)
Comment (jolelievre) [reply classes/ObjectModel.php]: Ok, good to know indeed!

**Review by Junebyun — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @matthieu-rolland !!

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland

**Comment by matks** [comment]
I mark this PR as key feature, it needs to be quoted into the Release Note (or the devdocs)
