### PR TITLE
Refacto SearchParameters and SearchParametersResolver for pagination

### LINKED ISSUE #12338: Filtering on messages in Logs does not return correct result
**Describe the bug**
On PS 1.7.5.0, filtering on messages under "Logs" does return the correct result, but keeps showing other pages within the result. These other pages do not contain the filtered messages. Selecting another number of results per page do not work either.

**To Reproduce**
1. Go To Advanced Parameters, Logs
2. Filter on Message. Click "Search".
3. The first page returns the correct result, but clicking on next page shows wrong results (not filtered results).

**Additionnal information**
PrestaShop version: 1.7.5.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | There was a bug on pagination for logs, this bug was actually larger than that and concerned all Grids. The `SearchParametersResolver` did not manage overriding rules properly, so when a request had parameters for pagination the former request with filters was ignored. Now the override rules are as follow: Default -> Saved -> Request
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12338
| How to test?  | Go to Advanced Parameters -> Logs, if you dont have enough stored logs you can perform Product modifications to create more or remove a product (for example). The pagination is supposed to work even when you perform a search or if you changer the order field.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12361)

### CODE REVIEW

File: src/Core/Search/SearchParameters.php [hunk 1]
```diff
@@ -58,10 +50,13 @@ public function __construct(AdminFilterRepository $adminFilterRepository)
     public function getFiltersFromRequest(Request $request, $filterClass)
     {
         $filters = [];
-        $defaultValues = $filterClass::getDefaults();
 
-        foreach (self::FILTER_TYPES as $type) {
-            $filters[$type] = $request->get($type, $defaultValues[$type]);
+        foreach (SearchParametersInterface::FILTER_TYPES as $type) {
```
Comment (Quetzacoalt91) [inline src/Core/Search/SearchParameters.php]: As this class implements the interface, isn't `self::FILTER_TYPES` still working?

Comment (jolelievre) [reply src/Core/Search/SearchParameters.php]: good question! I will try, that would be nice :P

Comment (jolelievre) [reply src/Core/Search/SearchParameters.php]: it works! thanks

File: src/Core/Search/SearchParameters.php [hunk 2]
```diff
@@ -58,10 +50,13 @@ public function __construct(AdminFilterRepository $adminFilterRepository)
     public function getFiltersFromRequest(Request $request, $filterClass)
     {
         $filters = [];
-        $defaultValues = $filterClass::getDefaults();
 
-        foreach (self::FILTER_TYPES as $type) {
-            $filters[$type] = $request->get($type, $defaultValues[$type]);
+        foreach (static::FILTER_TYPES as $type) {
```
Comment (PierreRambaud) [inline src/Core/Search/SearchParameters.php]: Can you keep the `self` other someone won't be able to implement and add a type in FILTER_TYPES

**Review by mickaelandrieu — DISMISSED** [review]

File: src/Core/Search/SearchParameters.php (hunk 2 above)
Comment (mickaelandrieu) [reply src/Core/Search/SearchParameters.php]: FILTER_TYPES is a constant

**Comment by mickaelandrieu** [comment]
well spotted @jolelievre :)

I remember I wanted to add tests for this one so I'm happy to see you have done them!

File: src/Core/Search/SearchParameters.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Search/SearchParameters.php]: ok I switched with `self` and squashed the branche, if it's ok for you it can go to QA

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by go-sudo** [comment]
Hello
I update my ps to the latest version 1.7.5.1 but still smae error with paginagion 
I get this error **Failed to load resource: the server responded with a status of 500 ()**
https://playstore.ma/index.php?id_category=100&controller=category

any idea please 
 Informations sur votre serveur
Informations sur votre serveur Linux #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

Version du logiciel serveur : Apache

Version de PHP : 7.2.15

Limite de mémoire : 6056M

Temps maximal d'exécution : 3000

Taille max. pour envoi de fichiers : 70M

Informations
Version de PrestaShop : 1.7.5.1

best regards

**Comment by PierreRambaud** [comment]
Hi @go-sudo 
If you have a problem, please create an issue ;)
Kind regards

**Comment by jolelievre** [comment]
Hello @go-sudo,

besides I think your bug is completely unrelated to this PR, as it didn't fix a 500 error but a loss of filters parameters when the page was changed. And you seem to have an error on your front office whereas this PR fixed a bug on the back office.

As @PierreRambaud suggested you should create another issue and give more info, a 500 error doesn't give enough information you need to look at the error in your logs or use the debug mode to have the stack trace and exception message.

Best regards
