### PR TITLE
Do not return customization values if cart is not set

### LINKED ISSUE #29259: Customizations are shared if no cookie are sent
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the browser doesn't send cookies and you save a customization, if another browser that doesn't send cookie open the product detail page, it will see the customization.

https://user-images.githubusercontent.com/2168836/183050931-28a7ed7b-179a-49e3-8dde-13d237eb4635.mov

### Expected behavior

Customizations shouldn't be saved if the server doesn't receive the cookie

### Steps to reproduce

1. Disable the cookie in the settings of your browser (see on the screen record to know how to do it)
2. As a guest, save a customization for the customizable mug for instance
3. In a private session or another browser that have cookie disabled, visit the customizable mug detail page
4. See that the customization is here

### PrestaShop version(s) where the bug happened

1.7.8.x

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fix for issue 29259 where customization values are shared between customers with disabled cookies.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29259. 
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Follow instructions in issue.
| Possible impacts? | ront office with storing values for customizations on products.

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -4362,6 +4362,10 @@ public function getProductCustomization($id_product, $type = null, $not_in_cart
             return [];
         }
 
+        if (0 === (int) $this->id) {
```
Comment (Hlavtox) [inline classes/Cart.php:4366]: Personally, I would comment it 😄Something like:
```
// Do not return anything, if there is no cart. Otherwise, all customers with disabled cookies would get the same customization.
```

**Review by kpodemski — APPROVED** [review]

File: classes/Cart.php (hunk 1 above)
Comment (kpodemski) [reply classes/Cart.php:4366]: @Prestaworks I see that you added a comment, but other Daniel's one is a bit clearer to me, as this issue is strictly related to the cookies. Right?

Comment (Prestaworks) [reply classes/Cart.php:4366]: I guess that even if you accept cookies, if there is no cart set you could get other users data also. id_cart = 0 in the sql query.

**Review by yanmakouf — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]
Well done

**Review by zuk3975 — APPROVED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @Prestaworks 

LGTM ! QA :heavy_check_mark:  
You can see the attached screen record 

[Untitled_ Nov 11, 2022 10_47 AM.webm](https://user-images.githubusercontent.com/31663369/201314528-563b823d-4675-4cd5-8de3-2b14eea9ccca.webm)


Thank you !

**Comment by kpodemski** [comment]
Thanks @Prestaworks !
