### PR TITLE
Fix carrier display in order confirmation email

### LINKED ISSUE #14293: Carrier is not correct displayed in the Order confirmation email
### 1761beta and develop is NOK
data
data2

### 1751 is OK:

Tested on 100% clean install.

**Describe the bug**
Check the screenshot.

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: 7.2

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix carrier display in order confirmation email
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14293
| How to test?  | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14296)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by MathiasReker** [comment]
Thanks :)

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

It is OK for me:
1. Address issue with Windows
image

2. carrier email issue

image

Thanks!

File: classes/AddressFormat.php [hunk 1]
```diff
@@ -515,7 +515,7 @@ class_exists($nameObject)) {
     public static function getOrderedAddressFields($idCountry = 0, $splitAll = false, $cleaned = false)
     {
         $out = array();
-        $fieldSet = explode(PHP_EOL, AddressFormat::getAddressCountryFormat($idCountry));
+        $fieldSet = explode("\n", AddressFormat::getAddressCountryFormat($idCountry));
```
Comment (PierreRambaud) [inline classes/AddressFormat.php]: Because, I just learn this format value is stored in database
```suggestion
        $fieldSet = explode(AddressFormat::FORMAT_NEW_LINE, AddressFormat::getAddressCountryFormat($idCountry));
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Rename "\n" into const

File: classes/AddressFormat.php (hunk 1 above)
Comment (jolelievre) [reply classes/AddressFormat.php]: That's what I warned you about in the previous PR about dni, I wasn't sure either

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
@jolelievre, @PierreRambaud, it is ok now
image

Thanks!
