### PR TITLE
Remove product image dropzone flex that was adding space

### LINKED ISSUE #27640: Product V2 - Images are not well displayed when we have more than 7 imags
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Catalog > Products > Edit Product V2, when we try to add a lot of images, they are not well displayed
image

### Expected behavior

_No response_

### Steps to reproduce

1. Enable Experimental product page
2. Go to Catalog > Products > Edit Product V2
3. Add a lot of images (8 images)
image
5. Try to resize the window
6. See error
image

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by margud**
… spaced between images

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?      | Removed display:flex from product images dropzone that was creating not needed spaces between images.
| Type?             |  improvement 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #27640
| How to test?      | Add more then 7-8 images and without the change there should be big empty spaces between images.
| Possible impacts? | Maybe the flex was used for something else but while testing couldn't find anything that would have been impected.

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue [hunk 1]
```diff
@@ -711,7 +711,6 @@
   }
 
   #product-images-dropzone.dropzone {
-    display: flex;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:714]: I'm not sure if this one was needed, @NeOMakinG I think you're the one who integrated this component right? Do you remember?

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Proper solution is to remove `justify-content: space-between;` to align items to the left side as by default.

**Comment by Hlavtox** [comment]
@NeOMakinG @jolelievre @margud The BEST BEST solution is to use a CSS grid which would allow to evenly space the images AND keep it aligned to the left. This is impossible with display: flex;

https://codepen.io/hlavtox/pen/OJZMPOQ

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue (hunk 1 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:714]: If you remove the flex, you have to remove every flex property above

If it works without it, then we don't need it! My guess is that it's also used for the image-selected window, isn't it? It might generate an issue there

**Comment by NeOMakinG** [comment]
> @NeOMakinG @jolelievre @margud The BEST BEST solution is to use a CSS grid which would allow to evenly space the images AND keep it aligned to the left. This is impossible with display: flex;
> 
> https://codepen.io/hlavtox/pen/OJZMPOQ

If it works without flex and grid, let's not using any of them

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue (hunk 1 above)
Comment (margud) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:714]: hmm this is how it looks and i don't see what could be the issue. Tried to add other changes that where suggested but I think just removing flex looks the best.
image

**Comment by Hlavtox** [comment]
@NeOMakinG It works, but creates some space on the right of the images. Flex was there to make spacing even.

If we want to remove flex, remove all flex related properties. 👍
```
flex-wrap: wrap;
justify-content: space-around;
```

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue [hunk 2]
```diff
@@ -711,12 +711,6 @@
...
-    align-items: flex-start;
-    justify-content: space-between;
-    border-radius: 4px;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: I guess the border-radius removal is a miss

Comment (margud) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: i can return it, but i m testing it and it doesn't change anything on the display, its added on parent div that hold all the images, so i don't really understand why we need it.

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: Isn't it the global border of the dropzone component that we can see there? 
image

Comment (margud) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: its this one, maybe it just not done correctly but no it has no impact.
image

Comment (margud) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: but if we move it to one div above, to the .product-images-container then yes it would make sane and would add border radius on the line that surrounds all the images. So now we can remove it or move it to .product-images-container but it never added the border before.

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: Alright, @margud thanks for the investigation!

I would suggest to move it to the div upper then, it would make sense from a design point of view :)

Then it's a 🍬 from me!

Comment (margud) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: Sure i can do that but all the fields bellow like summary and description doesn't have the border radius, so is it really good idea to have this specific radius just for image div? I think that looks strange. @NeOMakinG 
image

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:717]: > Sure i can do that but all the fields bellow like summary and description doesn't have the border radius, so is it really good idea to have this specific radius just for image div? I think that looks strange. @NeOMakinG image

Meh, I was thinking they had, in that case, let's go 👍 

Thanks for the explaining

**Review by NeOMakinG — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @margud 

I have checked this PR. the issue is well fixed.

Here is my checked list : 
-Check the automated tests : OK
-Check with different images format (.jpeg, jpe. png, .webp, .gif) : OK
-Check with product V1 : OK
-Check with product V2 : OK
- Check with multistore : OK
- Check with multi languages : OK
- Check with different browsers : OK

image

image

So, it's QA :heavy_check_mark: 

Thank You!

**Comment by matks** [comment]
Thank you @margud
