### PR TITLE
Fix duplicate / wrongly pluralized error message on field length in BO

### LINKED ISSUE #28877: BO - Products V1- The alert is duplicated when we create a product is a too long/too short name
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we create a product with a too-long/too short name, the alert is duplicated
image
image

### Expected behavior

image

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Add a product with a long name (more than 128 characters)
3. Save
4. See error: the alert is duplicated

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by yanmakouf**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?           |  An issue was reported about an error message being duplicated. After investigation, it turned out that the message was wrongly pluralized, displaying both singular and plural versions of an error message. Symfony 4.4 is supposed to handle those messages. The problem that was found was that the PrestashopTranslatorTrait ( which is a custom Prestashop layer on top of Symfony's translation system) had some issues, mainly the fact that it would not pass the `$parameters`parameter to the parent function trans(), preventing it to get the `%count%` index in the array parameters, preventing symfony from choosing between singular and plural versions.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28877
| Related PRs       | (https://github.com/PrestaShop/PrestaShop/pull/29040 https://github.com/PrestaShop/PrestaShop/pull/29396).
| How to test?      | Go to BO > Catalog > Products V1 > Add Product > Fill the "Name" field with less than 3 or more than 128 characters > Click Save button > See error : 'This value is too long. It should have {{ limit }} character or less.' OR 'This value is too long. It should have {{ limit }} characters or less.' with good pluralization according to context.
| Possible impacts? | All form fields with a length constraint.

Note : I've had to make another PR cause i made a mess when rebasing the previous one and it was quicker than trying to go up the gitflow tree but there was interesting discussions please check https://github.com/PrestaShop/PrestaShop/pull/29040 AND https://github.com/PrestaShop/PrestaShop/pull/29396

### CODE REVIEW

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 1]
```diff
@@ -53,27 +53,38 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
             $legacy = $parameters['legacy'];
             unset($parameters['legacy']);
         }
+        $emptyParams = empty($parameters);
+        $isSprintf = $this->isSprintfString($id);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
        $isSprintf = !emptyParams && $this->isSprintfString($id);
```

I believe the optimization that @eternoendless suggested is that it's useless to call `isSprintfString` when there are no parameters since the purpose of sprintf is to replace parameters.

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 2]
```diff
@@ -53,27 +53,38 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
+                $locale
+            );
+        } else {
+            $translated = parent::trans(
+                $id,
+                $parameters,
+                $this->normalizeDomain($domain),
+                $locale
+            );
+        }
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
        $translated = parent::trans($id, $isSprintf ? [] : $parameters, $this->normalizeDomain($domain), $locale);
```

Comment (jolelievre) [reply src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: This is equivalent and much smaller. However, I'm still not very confident about simply removing the parameters from the Symfony call, because as we discovered parameters are also required to be able to handle the plural wordings correctly.

This can be acceptable if and only if the messages using the sprintf format are guaranteed to be legacy Core wordings only.

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 3]
```diff
@@ -209,4 +220,15 @@ private function normalizeDomain($domain)
 
         return $normalizedDomain;
     }
+
+    private function replaceHtmlSpecialChars(string $message, $functionName)
+    {
+        if ('htmlspecialchars' === $functionName) {
+            $translated = call_user_func($functionName, $message, ENT_NOQUOTES);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
            $translated = htmlspecialchars($message, ENT_NOQUOTES);
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 4]
```diff
@@ -209,4 +220,15 @@ private function normalizeDomain($domain)
 
         return $normalizedDomain;
     }
+
+    private function replaceHtmlSpecialChars(string $message, $functionName)
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
    private function replaceHtmlSpecialChars(string $message, string $functionName)
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 5]
```diff
@@ -53,27 +53,38 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
-        if (isset($legacy) && 'htmlspecialchars' === $legacy) {
-            $translated = call_user_func($legacy, $translated, ENT_NOQUOTES);
-        } elseif (isset($legacy)) {
-            $translated = call_user_func($legacy, $translated);
-        }
-
-        if (!empty($parameters) && $this->isSprintfString($id)) {
+        $translated = isset($legacy) ? $this->replaceHtmlSpecialChars($translated, $legacy) : $translated;
+        
+        if (!$emptyParams && $isSprintf) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
        if ($isSprintf) {
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 6]
```diff
@@ -53,27 +53,38 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
             $translated = vsprintf($translated, $parameters);
-        } elseif (!empty($parameters)) {
+        } elseif (!$emptyParams) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: This elseif could be removed, because the `trans` method already perform an `strtr` internally

File: tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+        self::assertEquals('A new order has been placed on your shop', $this->translator->trans('A new order has been placed on your shop', [], 'Admin.Navigation.Header', null));
+        self::assertEquals(
+            'This value is too short. It should have {{ 3 }} characters or more.',
+            $this->translator->trans(
+                'This value is too short. It should have {{ limit }} characters or more.',
+                ['limit' => 3],
+                '',
+                null
+            )
+        );
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php]: You should add an example of a pluralized message (that's the initial point of this PR after all 😅)
- `This value is too long. It should have {{ limit }} character or less.|This value is too long. It should have {{ limit }} characters or less.` (domain `validators`)

And also an example related to this weird `sprintf` special use case:
- `Image is too large (%1$d kB). Maximum allowed: %2$d kB` (domain `AdminNavigationSearch`)
- `%d results match your query "%s".` (domain `AdminNavigationSearch`)

File: tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+    {
+        self::assertEquals('Succesful deletion', $this->translator->trans('Succesful deletion', ['legacy' => 'htmlspecialchars'], 'Admin.Notifications.Success', null));
+        self::assertEquals('The root category of the shop myshop', $this->translator->trans('The root category of the shop %shop%', ['%shop%' => 'myshop'], 'AdminCatalogNotification', null));
+        self::assertEquals('A new order has been placed on your shop', $this->translator->trans('A new order has been placed on your shop', [], 'Admin.Navigation.Header', null));
+        self::assertEquals(
+            'This value is too short. It should have {{ 3 }} characters or more.',
+            $this->translator->trans(
+                'This value is too short. It should have {{ limit }} characters or more.',
+                ['limit' => 3],
+                '',
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php]: Why no domain is used here?

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 9]
```diff
@@ -53,27 +53,38 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
-        $translated = parent::trans($id, [], $this->normalizeDomain($domain), $locale);
+        if (!$emptyParams && $isSprintf) {
+            $translated = parent::trans(
+                $id,
+                 [],
+                $this->normalizeDomain($domain),
+                $locale
+            );
+        } else {
+            $translated = parent::trans(
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: This breaks legacy fallback which should also work without parameters.

I understand the subject is quite tricky. Let me try to clarify.

The translator contais all the base translations + all the ones customized by the user using the BO interface, but it doesn't contain the translations being loaded from legacy dictionaries (which cannot be loaded inside the translator because they are incompatibile).  

When the translation exists in the translator, the message is translated and that's the end of it. But when the translation doesn't exist in the translator, then we try and perform it using the legacy module dictionaries. As you can see in `shouldFallbackToLegacyModuleTranslation()`, we use `$message === $translated` to test if the translation using the `trans()` was unsuccessful. 

However, we can't use that test if you send parameters to `trans()` because the translator will replace the parameters in the output even if it fails to find a translation. Eg: `trans("message %test%", ['%test%' => "toto"])` will yield `"message toto"`, which is different from the original "message %test%".

You'll probably say that comparing the original message to the output to infer behavior is hacky, and I would agree. The only way to know for sure would be to look inside its catalogues for a match.

I'm pretty sure `has()` will return false when the translation is not found (but you should check to make sure). This is pretty obvious, so I'm suspicious of why we didn't do this before, perhaps I'm missing something.

If all goes well, you should end up with a code that looks like this

```php
$normalizedDomain = $this->normalizeDomain($domain);
$translationExists = $this->getCatalogue($locale)->has($id, $normalizedDomain);

if ($this->shouldFallbackToLegacyModuleTranslation($id, $domain)) {
    return $this->translateUsingLegacySystem($id, $parameters, $domain, $locale);
}

if (!empty($parameters) && !$this->isSprintfString($id)) {
    // translate with parameters
    $translated = parent::trans(
        $id,
        $parameters,
        $normalizedDomain,
        $locale
    );
} else {
    // translate without parameters, 
    $translated = parent::trans(
        $id,
        [],
        $normalizedDomain,
        $locale
    );

    if (!empty($parameters)) {
        $translated = vsprintf($translated, $parameters);
    }
}

if (isset($legacy) && is_callable($legacy)) {
    if ('htmlspecialchars' === $legacy) {
        $translated = call_user_func($legacy, $translated, ENT_NOQUOTES);
    } else {
        $translated = call_user_func($legacy, $translated);
    }
}

return $translated;

// [ ... ]

private function shouldFallbackToLegacyModuleTranslation($message, $domain)
{
    return 
        'Modules.' === substr($domain ?? '', 0, 8);
        && (
            !method_exists($this, 'getCatalogue')
            || !$this->getCatalogue()->has($message, $this->normalizeDomain($domain))
        )
        ;
}
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 10]
```diff
@@ -209,4 +204,15 @@ private function normalizeDomain($domain)
 
         return $normalizedDomain;
     }
+
+    private function replaceHtmlSpecialChars(string $message, string $functionName)
+    {
+        if ('htmlspecialchars' === $functionName) {
+            $translated = htmlspecialchars($functionName, $message, ENT_NOQUOTES);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
            $translated = htmlspecialchars($message, ENT_NOQUOTES);
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php (hunk 9 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Hi @eternoendless your comment was probably made on the previous commit, the latest state has greatly simplified the previous code and it meets nearly all what you suggested in a smaller way except for a few things.

`shouldFallbackToLegacyModuleTranslation` is based on the translated message it checks that the initial message hasn't changed, what you suggest is to use legacy method early but I'm not sure about this one Because if the message is absent in module's legacy translations then the parameters could never be replaced, although your idea to accurately detect if the legacy translation exists makes sense, but we'd need a `LegacyTranslator::has` method as well, from what I could grasp the existence is checked in this code:

https://github.com/PrestaShop/PrestaShop/blob/d0f9edeb15b7c1b249d8b7fdb692987d3270f6f2/classes/Translate.php#L187-L197

If we can extract this in a `has` method then we can really check if the message is handled via legacy (also we should check that it's NOT handled by the catalogue since it should have the priority) and when we have this then I think it's the most optimal fallback we can have.

Also in your suggestion the `$translationExists` is never used, but it should be handled in the `shouldFallbackToLegacyModuleTranslation` method I guess (seems like it already is)

**Comment by matks** [comment]
@yanmakouf ready for review or is there still some work to do 😄 ?

**Comment by yanmakouf** [comment]
> @yanmakouf ready for review or is there still some work to do 😄 ?

Well I still have to fix the issue of the static analysis failing. Not sure my test is alright. @jolelievre what do you think ?

File: tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+    public function testTranslator()
+    {
+        self::assertEquals('Succesful deletion', $this->translator->trans('Succesful deletion', ['legacy' => 'htmlspecialchars'], 'Admin.Notifications.Success', null));
+        self::assertEquals('The root category of the shop myshop', $this->translator->trans('The root category of the shop %shop%', ['%shop%' => 'myshop'], 'AdminCatalogNotification', null));
+        self::assertEquals('A new order has been placed on your shop', $this->translator->trans('A new order has been placed on your shop', [], 'Admin.Navigation.Header', null));
+        self::assertEquals('Image is too large (10 kB). Maximum allowed: 5 kB', $this->translator->trans('Image is too large (%1$d kB). Maximum allowed: %2$d kB', [10, 5], 'AdminNavigationSearch', null));
+        self::assertEquals('10 results match your query "stringTest".', $this->translator->trans('%d results match your query "%s".', [10, 'stringTest'], 'Admin.Navigation.Header', null));
+        self::assertEquals(
+            'This value is too short. It should have 3 characters or more.',
+            $this->translator->transChoice(
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php]: This is ignoring the initial problem of `trans` ^^

This test class can indeed test both methods `trans` and `transChoice` but the main problem was that `trans` didn't handle plural messages correctly because of PrestaShop modifications in the trait, so you are still missing one use case here

Comment (jolelievre) [reply tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php]: I'll try and fetch your branch in the afternoon to understand what was failing when you showed me

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @yanmakouf

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php (hunk 9 above)
Comment (eternoendless) [reply src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: > Also in your suggestion the $translationExists is never used

Yeah you're right, here it is fixed:

```php
if ($this->shouldFallbackToLegacyModuleTranslation($id, $domain)) {
    return $this->translateUsingLegacySystem($id, $parameters, $domain, $locale);
}

if (!empty($parameters) && !$this->isSprintfString($id)) {
    // translate with parameters
    $translated = parent::trans(
        $id,
        $parameters,
        $this->normalizeDomain($domain),
        $locale
    );
} else {
    // translate without parameters, 
    $translated = parent::trans(
        $id,
        [],
        $this->normalizeDomain($domain),
        $locale
    );

    if (!empty($parameters)) {
        $translated = vsprintf($translated, $parameters);
    }
}

if (isset($legacy) && is_callable($legacy)) {
    if ('htmlspecialchars' === $legacy) {
        $translated = call_user_func($legacy, $translated, ENT_NOQUOTES);
    } else {
        $translated = call_user_func($legacy, $translated);
    }
}

return $translated;

// [ ... ]

private function shouldFallbackToLegacyModuleTranslation($message, $domain)
{
    return 
        'Modules.' === substr($domain ?? '', 0, 8);
        && (
            !method_exists($this, 'getCatalogue')
            || !$this->getCatalogue()->has($message, $this->normalizeDomain($domain))
        )
        ;
}
```

> if the message is absent in module's legacy translations then the parameters could never be replaced

Yes they will. The legacy translator has its own way of replacing params, so no need to add more logic for that: https://github.com/PrestaShop/PrestaShop/blob/434137b764ab0faa9de420a0a8ec54a039165dd0/classes/Translate.php#L199-L205

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 12]
```diff
@@ -53,28 +53,23 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
             unset($parameters['legacy']);
         }
+        $emptyParams = empty($parameters);
+        $isSprintf = !$emptyParams && $this->isSprintfString($id);
 
         if (empty($locale)) {
             $locale = null;
         }
 
-        $translated = parent::trans($id, [], $this->normalizeDomain($domain), $locale);
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php:61]: This is still breaking legacy fallback when using placeholders.

eg. when calling `trans("This is a %message%", ['%message%' => 'bad idea'], 'Modules.Mymodule.Foobar')`

Assume the translation is not in the catalog (which should call for legacy fallback). When the translation is not found, `trans` returns the original wording without translating it. 

However, on this line, `$translated` will be "This is a bad idea" instead of "This is a %message%", because you sent the parameters and when you do, they are replaced regardless of whether the wording was translated or not.

So when we call `$this->shouldFallbackToLegacyModuleTranslation()`, it will return false instead of true, because `$id` and `$translated` should have been equal, based on the original premise stating that one of the requisites to qualify for legacy fallback is that the wording is not found on the translation catalogue, and that we can tell that because the original wording and their translations are equal. 

Therefore, my [previous comment](https://github.com/PrestaShop/PrestaShop/pull/29584#discussion_r966209517) remains true.

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 13]
```diff
@@ -209,4 +204,15 @@ private function normalizeDomain($domain)
 
         return $normalizedDomain;
     }
+
+    private function replaceHtmlSpecialChars(string $message, string $functionName)
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Missing return type and phpdoc: https://www.pabloborowicz.com/why-you-should-be-commenting-your-code/#describing-class-members
```suggestion
    private function replaceHtmlSpecialChars(string $message, string $functionName): string
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 14]
```diff
@@ -53,28 +53,24 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
         }
 
-        if (isset($legacy) && 'htmlspecialchars' === $legacy) {
-            $translated = call_user_func($legacy, $translated, ENT_NOQUOTES);
-        } elseif (isset($legacy)) {
-            $translated = call_user_func($legacy, $translated);
-        }
+        $translated = parent::trans($id, $isSprintf ? [] : $parameters, $this->normalizeDomain($domain), $locale);
+
+
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Remove extra empty line
```suggestion

```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 15]
```diff
@@ -53,28 +53,24 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
             $legacy = $parameters['legacy'];
             unset($parameters['legacy']);
         }
+        $emptyParams = empty($parameters);
+        $isSprintf = !$emptyParams && $this->isSprintfString($id);
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: I think this can be simplified like this:
```suggestion
        $isSprintf = !empty($parameters) && $this->isSprintfString($id);
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 16]
```diff
@@ -209,4 +203,23 @@ private function normalizeDomain($domain)
 
         return $normalizedDomain;
     }
+
+    /**
+     * Returns the message
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
     * Replaces special characters on the message
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 17]
```diff
@@ -209,4 +203,23 @@ private function normalizeDomain($domain)
...
+     *
+     * @param string $message the message
+     * @param string $functionName Name of function to be called
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
     * @param string|callable $functionName Name of function to be called
```

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 18]
```diff
@@ -209,4 +203,23 @@ private function normalizeDomain($domain)
...
+     *
+     * @return string|null
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]:
```suggestion
     * @return string
```

**Review by eternoendless — COMMENTED** [review]
Final cosmetic changes, other than that it looks good!

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php (hunk 17 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Only this one to fix and we should be good

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 19]
```diff
@@ -209,4 +201,23 @@ private function normalizeDomain($domain)
...
+
+    /**
+     * Replaces special characters on the message
+     *
+     * @param string $message the message
+     * @param callable|string $functionName Name of function to be called
+     *
+     * @return string
+     */
+    private function replaceSpecialCharsWithLegacyFunctions(string $message, string|callable $functionName): string
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Union types is a PHP 8 feature, we can't use it yet if we want to be compatible with 7.2+
```suggestion
    private function replaceSpecialCharsWithLegacyFunctions(string $message, string $functionName): string
```

**Review by jolelievre — DISMISSED** [review]
Thanks @yanmakouf

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php [hunk 20]
```diff
@@ -53,28 +53,22 @@ public function trans($id, array $parameters = [], $domain = null, $locale = nul
...
 
-        if (isset($legacy) && 'htmlspecialchars' === $legacy) {
-            $translated = call_user_func($legacy, $translated, ENT_NOQUOTES);
-        } elseif (isset($legacy)) {
-            $translated = call_user_func($legacy, $translated);
-        }
+        $translated = parent::trans($id, $isSprintf ? [] : $parameters, $this->normalizeDomain($domain), $locale);
 
-        if (!empty($parameters) && $this->isSprintfString($id)) {
+        $translated = isset($legacy) ? $this->replaceSpecialCharsWithLegacyFunctions($translated, $legacy) : $translated;
```
Comment (eternoendless) [inline src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Wouldn't it make more sense to replace the special characters after the tokens have been replaced instead of doing it before?

**Review by eternoendless — DISMISSED** [review]

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php (hunk 20 above)
Comment (yanmakouf) [reply src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Not sure what difference does it make technically. But I can see how more "natural" flow it is.  :)

**Comment by l-delin** [comment]
I'm removing the **waiting for wording** label because there's no wording. Ping me if need be!

**Comment by yanmakouf** [comment]
> I'm removing the **waiting for wording** label because there's no wording. Ping me if need be!

Thanks. Yeah it adds it every time I push. Not exactly sure why.

File: src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php (hunk 20 above)
Comment (eternoendless) [reply src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php]: Here's why.

Imagine this scenario:

```php
trans("Some <b>%s</b>", ["<i>injection</i>", 'legacy' => 'htmlspecialchars'], 'foo');
```

If you do the replacement before, you get:

```
Some &lt;<i>injection</i>&gt;
```

If you the replacement after, you get:

```
Some &lt;&lt;i&gt;injection&lt;/i&gt;&gt;
```

**Review by eternoendless — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php [hunk 21]
```diff
@@ -0,0 +1,114 @@
...
+            '%d results match your query "%s".',
+            'Admin.Navigation.Header',
+            [10, 'stringTest'],
+        ];
+        yield 'translation with plural format' => [
+            'This value is too short. It should have 3 characters or more.',
+            'This value is too short. It should have {{ limit }} character or more.|This value is too short. It should have {{ limit }} characters or more.',
+            'validators',
+            // transChoice has been deprecated trans should be used instead with a %count% parameter
+            ['{{ limit }}' => 3, '%count%' => 3],
```
Comment (atomiix) [inline tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php:75]: Maybe add the same test but for `{{ limit }} = 1` so we can be sure the right sentence is chosen according to `{{ limit }}`?

Comment (yanmakouf) [reply tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php:75]: Yeah why not. Tho having 3 as a limit should be ok. If it did not work it would return either  'This value is too short. It should have {{ limit }} character or more.|This value is too short. It should have {{ limit }} characters or more' or 'This value is too short. It should have {{ limit }} character or more.' Anyway i'll add a test for clarity :) But  @jolelievre and @eternoendless will maybe get tired of review/approve ^^

**Review by atomiix — DISMISSED** [review]

File: tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php [hunk 22]
```diff
@@ -0,0 +1,127 @@
...
+            'This is a bad idea',
+            'This is a %message%',
+            'Modules.Mymodule.Foobar',
+            ['%message%' => 'bad idea'],
+        ];
+        yield 'translation with htmlspecialchars and sprintf' => [
+            '&lt;a href="test"&gt;10 Succesful deletion "stringTest"&lt;/a&gt;',
+            '<a href="test">%d Succesful deletion "%s"</a>',
+            'Admin.Notifications.Success',
+            ['legacy' => 'htmlspecialchars', 10, 'stringTest'],
```
Comment (eternoendless) [inline tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php]:
```suggestion
            '&lt;a href="test"&gt;10 Succesful deletion "&lt;b&gt;stringTest&lt;b&gt;"&lt;/a&gt;',
            '<a href="test">%d Succesful deletion "%s"</a>',
            'Admin.Notifications.Success',
            ['legacy' => 'htmlspecialchars', 10, '<b>stringTest</b>'],
```

Comment (eternoendless) [reply tests/Integration/PrestaShopBundle/TranslationIntegrationTest.php]: This is what's missing to test htmlspecialchars after replacing the arguments

**Review by eternoendless — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @yanmakouf  !
The issue is solved :+1:
I checked those steps:

- Run the automated tests > **OK**
- I check the other input fields : Reference / Summary / Summary /Stock location/Meta title/Meta description  > **OK**
- I check it with the 3 types of products : standard product / Virtual product / Pack of products
- I check it also with product V2 > **OK**

https://user-images.githubusercontent.com/31663369/192811073-ae9bd8db-71d1-496f-85e9-a4b524346b5c.mp4

Thank you ! :rocket:
