### PR TITLE
Fix broken page when requesting a duplicate _legacy_link

### LINKED ISSUE #13128: Legacy pages are not correctly redirected when updating categories
**Describe the bug**
Legacy pages are not correctly redirected when updating categories.
Ping @matks 

**To Reproduce**
Go to an old legacy update page
http://ps-develop.localhost/admin-dev/index.php?controller=AdminCategories&id_category=9&updatecategory

**Screenshots**
image

**Additionnal information**
PrestaShop version: latest develop branch
PHP version: 7.2

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | We must be able to have many routes with the same legacy_link, but in case someone creates a module and want to use say "Hey use my controller for this legacy link", so use the last element in the stack.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13128
| How to test?  | Follow ticket instruction

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13208)

### CODE REVIEW

File: src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php [hunk 1]
```diff
@@ -90,10 +90,28 @@ public function getLegacyRouteByAction($controller, $action)
...
+     * @param string $action
+     *
+     * @return string
+     */
+    private function getRouteName(array $controllerActions, $action)
+    {
         $routeName = $controllerActions[$action];
-        $legacyRoutes = $this->getLegacyRoutes();
+        if (is_array($routeName)) {
+            return end($routeName);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php]: I'm wondering why return the last one, why not the first matching one. In Symfony routing the first matching route is used:
https://symfony.com/doc/3.4/routing.html#adding-wildcard-requirements

Which "forces" (but also allows) you to define the order of your routes in a specific order sometimes, we should use the same priority or it will be confusing, whay do you think?

File: tests-legacy/PrestaShopBundle/Routing/Converter/RouterProviderTest.php [hunk 2]
```diff
@@ -169,6 +169,22 @@ public function testGetLegacyRouteByAction()
                     'AdminCategories:create',
                 ],
             ],
+            [
```
Comment (jolelievre) [inline tests-legacy/PrestaShopBundle/Routing/Converter/RouterProviderTest.php:172]: Good thing that you added a test, I think you should add one for `CacheProvider` as well since it extends the same abstract class

**Review by jolelievre — CHANGES_REQUESTED** [review]
Nice job @PierreRambaud 
I'm wondering since you're the first one to modify this part of the code, did you find it clear or messy?

File: src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php (hunk 1 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Routing/Converter/AbstractLegacyRouteProvider.php]: `_legacy_link` aren't stacked as Symfony routes are. 
If a module creates a route and the developer want to change all `AdminCategories` links with his own route, he'll use `_legacy_link: AdminCategories` too.
It becomes helpful to get the last one instead of Core behavior.

**Comment by PierreRambaud** [comment]
> Nice job @PierreRambaud
> I'm wondering since you're the first one to modify this part of the code, did you find it clear or messy?

It was clear!

**Comment by PierreRambaud** [comment]
@jolelievre All changes applied!

**Review by jolelievre — APPROVED** [review]
Thanks @PierreRambaud

**Comment by matks** [comment]
Thank you @PierreRambaud
