### PR TITLE
Handle profile name above 32 chars exception

### LINKED ISSUE #16725: Error - Unclear alert when adding a profile's name more than 32 chars
**Describe the bug**
 Unclear alert when adding a profile's name more than 32 chars

**To Reproduce**
1. Go to BO => Advanced Parameters => Team => Profiles
2. Create a profile with a name more than 32 chars
3. Save

With PS1.7.5.2, it was very clear
image

**Screenshots**
image

**Additional information**
PrestaShop version: 1.7.6.2, 1.7.6.0
PHP version: 7.1

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | This handles exception when saving a profile name that is longer that 32 chars
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16725
| How to test?  | In _Advanced Parameters -> Team -> Profiles_ try adding a new profile with a name longer that 32 chars. Same thing when editing a profile name.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16906)

### CODE REVIEW

File: src/Core/Domain/Profile/Exception/ProfileConstraintException.php [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+/**
+ * Is thrown when some constraint is violated in Profile subdomain
+ */
+class ProfileConstraintException extends ProfileException
+{
+    /**
+     * Profile name max length as defined in the ObjectModel
+     */
+    const NAME_MAX_LENGTH = 32;
```
Comment (eternoendless) [inline src/Core/Domain/Profile/Exception/ProfileConstraintException.php]: I think it would make more sense to put this in AddProfileCommand

Comment (atomiix) [reply src/Core/Domain/Profile/Exception/ProfileConstraintException.php]: Yes, I thought about it but since we need to check the length in `EditProfileCommand` too, I thought the common place would have been the Exception linked to that check.
So should I use `AddProfileCommand::MAX_LENGTH` in `EditProfileCommand` or should I add a second constante in `EditProfileCommand`?

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php [hunk 2]
```diff
@@ -264,6 +265,13 @@ public function bulkDeleteAction(Request $request)
     protected function getErrorMessages()
     {
         return [
+            ProfileConstraintException::class => [
+                ProfileConstraintException::INVALID_NAME => $this->trans(
+                    'Your entry in field name exceeds max length %d chars (incl. HTML tags)',
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php]: It works for both first and last name fields, right? In this case, I would write _Your entry in the %s field cannot be longer than %limit% characters (incl. HTML tags)_, localized in the same domain.

Comment (atomiix) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php]: It's not a person name, it's a name we give to a profile, like `SuperAdmin`, `Logistician`, `Salesman`, etc... But if you still think I should change it I'll do it! Wdyt?

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController.php]: My bad, I was on the employee tab... What about _This field cannot be longer than %limit% characters (incl. HTML tags)_ in Admin.Notifications.Error?

File: src/Core/Domain/Profile/Exception/ProfileConstraintException.php (hunk 1 above)
Comment (matks) [reply src/Core/Domain/Profile/Exception/ProfileConstraintException.php]: For this kind of constants, we have also been using "Settings" class
See https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Category/SeoSettings.php

File: src/Core/Domain/Profile/Command/AddProfileCommand.php [hunk 3]
```diff
@@ -51,4 +58,21 @@ public function getLocalizedNames()
     {
         return $this->localizedNames;
     }
+
+    /**
+     * @param string $name
+     */
+    private function assertNameIsStringAndRequiredLength($name)
+    {
+        if (!is_string($name) || strlen($name) !== ProfileConstraintException::NAME_MAX_LENGTH) {
```
Comment (jolelievre) [inline src/Core/Domain/Profile/Command/AddProfileCommand.php]:
```suggestion
        if (!is_string($name) || strlen($name) > ProfileConstraintException::NAME_MAX_LENGTH) {
```

File: src/Core/Domain/Profile/Command/EditProfileCommand.php [hunk 4]
```diff
@@ -75,4 +80,21 @@ public function getLocalizedNames()
     {
         return $this->localizedNames;
     }
+
+    /**
+     * @param string $name
+     */
+    private function assertNameIsStringAndRequiredLength($name)
+    {
+        if (!is_string($name) || strlen($name) !== ProfileConstraintException::NAME_MAX_LENGTH) {
```
Comment (jolelievre) [inline src/Core/Domain/Profile/Command/EditProfileCommand.php]:
```suggestion
        if (!is_string($name) || strlen($name) > ProfileConstraintException::NAME_MAX_LENGTH) {
```

File: src/Core/Domain/Profile/Exception/ProfileConstraintException.php (hunk 1 above)
Comment (jolelievre) [reply src/Core/Domain/Profile/Exception/ProfileConstraintException.php]: Agreed! This kind of domain specification should not be stored in the exception

**Review by jolelievre — CHANGES_REQUESTED** [review]
Careful your condition is a strict equality It should check the string max length instead

File: src/Core/Domain/Profile/Command/AddProfileCommand.php [hunk 5]
```diff
@@ -51,4 +59,21 @@ public function getLocalizedNames()
     {
         return $this->localizedNames;
     }
+
+    /**
+     * @param string $name
+     */
+    private function assertNameIsStringAndRequiredLength($name)
+    {
+        if (null !== $name && !is_string($name) || strlen($name) > ProfileSettings::NAME_MAX_LENGTH) {
```
Comment (PierreRambaud) [inline src/Core/Domain/Profile/Command/AddProfileCommand.php]:
```suggestion
        if (!is_string($name) || strlen($name) > ProfileSettings::NAME_MAX_LENGTH) {
```
No need to check for null if you check for is_string & strlen :)

File: src/Core/Domain/Profile/Command/EditProfileCommand.php [hunk 6]
```diff
@@ -75,4 +81,21 @@ public function getLocalizedNames()
     {
         return $this->localizedNames;
     }
+
+    /**
+     * @param string $name
+     */
+    private function assertNameIsStringAndRequiredLength($name)
```
Comment (PierreRambaud) [inline src/Core/Domain/Profile/Command/EditProfileCommand.php]: Duplicate code, should we provide an abstract method?

File: src/Core/Domain/Profile/Command/AddProfileCommand.php (hunk 5 above)
Comment (atomiix) [reply src/Core/Domain/Profile/Command/AddProfileCommand.php]: For TranslatableField type, empty strings are sent as null so I think we need this test

Comment (PierreRambaud) [reply src/Core/Domain/Profile/Command/AddProfileCommand.php]: Not needed `is_string(null) => false`

Comment (atomiix) [reply src/Core/Domain/Profile/Command/AddProfileCommand.php]: Yes, that's the problem, we should allow the value null

Comment (PierreRambaud) [reply src/Core/Domain/Profile/Command/AddProfileCommand.php]: Ooooooooooohhhhhhhhhhhhhhhhhhh :sweat_smile:

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thank you @atomiix and thank you everybody for validation
