### PR TITLE
Fix deleted products not being displayed in orders

### LINKED ISSUE #16841: Products in orders disappear when catalog product is deleted
Latest PS version and bellow: Products in orders disappear when catalog product is deleted. Product array in client order details is empty. File Orders.php > getCartProducts() $product['product_id'] comparision with $product['id_product'] which no longer exists.. comparision failing to empty array.

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix deleted products not being displayed in orders history and fix the migrated page throwing an error
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16841
| How to test?  | In the FO, place an order. Then, in catalog on the BO, delete the product you just ordered. The migrated order view page should not throw an error and in your customer account, when you look at your order history, the deleted product should still be there.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17254)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
LGTM

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]
lgtm

File: src/Adapter/Presenter/Order/OrderLazyArray.php [hunk 1]
```diff
@@ -165,14 +165,16 @@ public function getProducts()
...
-        $orderProducts = $order->getCartProducts();
+        $orderProducts = $order->getProducts();
         $cartProducts = $this->cartPresenter->present($cart);
         $orderPaid = $order->getCurrentOrderState() && $order->getCurrentOrderState()->paid;
 
         $includeTaxes = $this->includeTaxes();
         foreach ($orderProducts as &$orderProduct) {
             $orderProduct['name'] = $orderProduct['product_name'];
             $orderProduct['quantity'] = $orderProduct['product_quantity'];
+            $orderProduct['id_product'] = $orderProduct['product_id'];
```
Comment (jolelievre) [inline src/Adapter/Presenter/Order/OrderLazyArray.php:177]: Could you add a comment here please? Explaining that the replaced data actually comes from the OrderDetail object/table, in case the product row has been removed (hence the difference in array field names)

**Review by jolelievre — CHANGES_REQUESTED** [review]
Just some comments to understand where the data comes from

**Review by jolelievre — APPROVED** [review]
Thanks @atomiix

**Comment by Robin-Fischer-PS** [comment]
Hi ! I tested the PR on FO and on BO, it's QA :heavy_check_mark: :)
