### PR TITLE
Fix delete order state confirmation

### LINKED ISSUE #21269: BO - Order statuses - an alert is not displayed when deleting an order status
#### Describe the bug

In the BO > Order Settings > Statuses page, When we try to delete an order status, there is no alert displayed.

It was ok with PS1768

#### Expected behavior

image
.

#### Steps to Reproduce

1. Go to BO > Order Settings > Statuses page
2. Try to delete an order status
4. See error "No alert"

#### Additional information

* PrestaShop version: 1770rc1
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Redirect after order state deletion to display success alert
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21269
| How to test?  | Go to BO > Order Settings > Statuses page<br>Delete an order status<br>You are redirected to the order statuses list and a green alert confirms Successful deletion

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21310)

### CODE REVIEW

File: controllers/admin/AdminStatusesController.php [hunk 1]
```diff
@@ -629,7 +629,9 @@ public function postProcess()
             if (!$order_state->isRemovable()) {
                 $this->errors[] = $this->trans('For security reasons, you cannot delete default order statuses.', [], 'Admin.Shopparameters.Notification');
             } else {
-                return $order_state->softDelete();
+                $order_state->softDelete();
```
Comment (Progi1984) [inline controllers/admin/AdminStatusesController.php]: if return false, maybe return an error.

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1oQZlFS7cAz_hUUwfv-TMSOjlwSxyDRj2/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @sowbiba & @khouloudbelguith
