### PR TITLE
Setup generic provider for oauth API

### LINKED ISSUE #32338: Spike : CQRS2endpoint
For now, we have endpoint like this :

```
resources:
  PrestaShopBundle\Api\Resource\HookStatus:
    operations:
      ApiPlatform\Metadata\Get:
        provider: PrestaShopBundle\Api\StateProvider\HookStatusProvider
        uriTemplate: '/hook-status/{id}'
        requirements:
          id: '\d+'
        exceptionToStatus:
          PrestaShop\PrestaShop\Core\Domain\Hook\Exception\HookNotFoundException: 404
```

The idea is to replace API DTO with QueryResult already exist and create a generic provider. Finally we will be able to create API endpoints match to CQRS with only yml code and integration tests.

Some key points :

- When using command endpoint, maybe we have to send the query result associated
- Replace all value object in query result by scalar values

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Setup generic provider for oauth API using CQRS
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI must be green
| Fixed ticket?     | Fixes #32338 
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

File: tests/Unit/PrestaShopBundle/Api/StateProvider/HookStatusProviderTest.php [hunk 1]
```diff
@@ -56,24 +58,27 @@ public function setUp(): void
...
+            return new HookStatus($query->getHookId()->getValue(), false);
         }
 
         if ($query->getHookId()->getValue() === 2) {
-            return true;
+            return new HookStatus($query->getHookId()->getValue(), true);
         }
 
-        return true;
+        throw new RuntimeException(sprintf('Hook "%s" was not expected in query bus mock', $query->getHookId()->getValue()));
```
Comment (tleon) [inline tests/Unit/PrestaShopBundle/Api/StateProvider/HookStatusProviderTest.php:71]: Maybe in this case we could use a switch case default instead of multiples if and an implied default behavior

**Comment by tleon** [comment]
You also need to run the fixer.

File: app/config/config.yml [hunk 2]
```diff
@@ -105,6 +105,6 @@ api_platform:
   enable_entrypoint: false
   mapping:
     paths:
-      - '%kernel.project_dir%/app/config/api_platform'
+      - '%kernel.root_dir%/../src/PrestaShopBundle/Api/Resources'
```
Comment (jolelievre) [inline app/config/config.yml]:
```suggestion
      - '%kernel.project_dir%/src/PrestaShopBundle/Api/Resources'
```

File: src/PrestaShopBundle/Api/Processor/CommandProcessor.php [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+    {
+        $command = $operation->getExtraProperties()['command'];
+        $reflectionMethod = new \ReflectionMethod($command, '__construct');
+        $constructParameters = $reflectionMethod->getParameters();
+        $parameters = [];
+        foreach ($constructParameters as $parameter) {
+            $parameters[] = $data->{$parameter->name};
+        }
+
+        $this->commandBus->handle(new $command(...array_values($parameters)));
```
Comment (jolelievre) [inline src/PrestaShopBundle/Api/Processor/CommandProcessor.php]: First POC is enough but we'll have to improve this to handle setters as well Many commands use setters and don't have all the parameters in the constructor

File: src/PrestaShopBundle/Api/Resources/Hook.php [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+declare(strict_types=1);
+
+namespace PrestaShopBundle\Api\Resources;
```
Comment (jolelievre) [inline src/PrestaShopBundle/Api/Resources/Hook.php]:
```suggestion
namespace PrestaShopBundle\ApiPlatform\Resources;
```

File: src/PrestaShopBundle/Resources/config/services/bundle/services.yml [hunk 5]
```diff
@@ -96,13 +96,20 @@ services:
     public: false
     tags: [ 'container.env_var_processor' ]
 
-  PrestaShopBundle\Api\StateProvider\HookStatusProvider:
+  PrestaShopBundle\Api\Provider\QueryProvider:
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/config/services/bundle/services.yml]: All the providers/services associated with ApiPlatform should also me moved in the appropriate namespace

File: tests/Unit/PrestaShopBundle/Api/StateProvider/HookStatusProviderTest.php (hunk 1 above)
Comment (jolelievre) [reply tests/Unit/PrestaShopBundle/Api/StateProvider/HookStatusProviderTest.php:71]: I think it's enough as it meets all the use cases of the current test, it's even almost overkill

Comment (mflasquin) [reply tests/Unit/PrestaShopBundle/Api/StateProvider/HookStatusProviderTest.php:71]: More is better than less ^^

File: src/PrestaShopBundle/ApiPlatform/Resources/Hook.php [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+use PrestaShopBundle\ApiPlatform\Processor\CommandProcessor;
+use PrestaShopBundle\ApiPlatform\Provider\QueryProvider;
+
+#[ApiResource(
+    operations: [
+        new Get(
+            uriTemplate: '/hook-status/{id}',
+            requirements: ['id' => '\d+'],
+            exceptionToStatus: [HookNotFoundException::class => 404],
+            output: HookStatus::class,
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/Resources/Hook.php]: That's the last thing I'm not 100% sure about I'd like to test if e can use the resource DTO as output and if ApiPlatform is able to automatically fill it with only available fields present To check this maybe you can add the `name` field in this DTO

The API should not return it since the query result object only contains partial fields

File: src/PrestaShopBundle/ApiPlatform/Resources/Hook.php [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+            extraProperties: ['command' => UpdateHookStatusCommand::class]
+        ),
+    ]
+)]
+class Hook
+{
+    /**
+     * @var int
+     */
+    public int $id = 0;
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/Resources/Hook.php]: Do we really need this field since we already have `$hookId` Is this needed only to match the API placeholder `{id}` If so I wonder if there's a possibility to use `{id}` in the URI but indicate some mapping to make it match with `hookId` ?

If not then maybe we should simply use `hookId` as the placeholder, but globally I'd prefer we don't add addition/duplicate fields like this one

**Review by jolelievre — COMMENTED** [review]
Thanks @mflasquin 

Last comments about the DTO, and also maybe we should add some integration tests for this API? That will serve as an example for future implementation since no API should be added without a related test

File: app/config/config.yml [hunk 8]
```diff
@@ -105,6 +105,6 @@ api_platform:
   enable_entrypoint: false
   mapping:
     paths:
-      - '%kernel.project_dir%/app/config/api_platform'
+      - '%kernel.project_dir%/src/PrestaShopBundle/Api/Resources'
```
Comment (jolelievre) [inline app/config/config.yml]:
```suggestion
      - '%kernel.project_dir%/src/PrestaShopBundle/ApiPlatform/Resources'
```

**Review by 0x346e3730 — DISMISSED** [review]
LGTM 👍

File: src/PrestaShopBundle/ApiPlatform/Resources/Hook.php (hunk 6 above)
Comment (jolelievre) [reply src/PrestaShopBundle/ApiPlatform/Resources/Hook.php]: On second thought, we can decide about this output necessity later, we should have another PR that adds another endpoint that returns the whole hook (a new query will probably be needed) Then we'll be able to test if ApiPlatform is able to automatically fill and filter absent fields (with value null)

So ok for this first POC PR 👍 It will unlock several other topics

File: tests/Integration/Api/GetHookStatusTest.php [hunk 9]
```diff
@@ -45,18 +45,18 @@ public function testGetHookStatus(): void
         $activeHook->add();
 
         $bearerToken = $this->getBearerToken();
-        $response = static::createClient()->request('GET', '/new-api/hook-status/' . $inactiveHook->id, ['auth_bearer' => $bearerToken]);
+        $response = static::createClient()->request('GET', '/admin-dev/new-api/hook-status/' . (int) $inactiveHook->id, ['auth_bearer' => $bearerToken]);
```
Comment (jolelievre) [inline tests/Integration/Api/GetHookStatusTest.php]: Ah I didn't realize integration tests were already present However the namespace should be changed to `ApiPlatform` as well

**Review by jolelievre — COMMENTED** [review]
Thanks @mflasquin 

Just one namespace to adapt and it's all good. Also an integration test is failing in the CI but it doesn't seem to be related to your PR so maybe you should just rebase it and it will fix it all

File: tests/Integration/Api/GetHookStatusTest.php (hunk 9 above)
Comment (jolelievre) [reply tests/Integration/Api/GetHookStatusTest.php]: I think we should add a custom TestCase that will offer some helper methods to test the APIs more easily, but it should be done in another PR as well

Comment (FabienPapet) [reply tests/Integration/Api/GetHookStatusTest.php]: There's an api test case for api platform ;)

Comment (jolelievre) [reply tests/Integration/Api/GetHookStatusTest.php]: Ah but it's already used!

**Comment by jolelievre** [comment]
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5114446564

**Review by 0x346e3730 — DISMISSED** [review]

**Review by tleon — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by tleon — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by mflasquin** [comment]
Tests UI : https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5175987799

**Review by 0x346e3730 — DISMISSED** [review]

File: tests/Integration/ApiPlatform/GetHookStatusTest.php [hunk 10]
```diff
@@ -63,6 +70,44 @@ public function testGetHookStatus(): void
...
+    {
+        $hook = new \Hook();
+        $hook->name = 'disableHook';
+        $hook->active = true;
+        $hook->add();
+
+        $bearerToken = $this->getBearerToken();
+        static::createClient()->request('PUT', '/new-api/hook-status', [
+            'auth_bearer' => $bearerToken,
+            'json' => ['hookId' => (int) $hook->id, 'status' => (bool) !$hook->active],
```
Comment (jolelievre) [inline tests/Integration/ApiPlatform/GetHookStatusTest.php]:
```suggestion
            'json' => ['hookId' => (int) $hook->id, 'status' => false],
```

File: tests/Integration/ApiPlatform/GetHookStatusTest.php [hunk 11]
```diff
@@ -63,6 +70,44 @@ public function testGetHookStatus(): void
...
+        ]);
+        self::assertResponseStatusCodeSame(200);
+
+        $response = static::createClient()->request('GET', '/new-api/hook-status/' . (int) $hook->id, ['auth_bearer' => $bearerToken]);
+        self::assertEquals(json_decode($response->getContent())->active, !$hook->active);
```
Comment (jolelievre) [inline tests/Integration/ApiPlatform/GetHookStatusTest.php]:
```suggestion
        self::assertEquals(json_decode($response->getContent())->active, false);
```

File: tests/Integration/ApiPlatform/GetHookStatusTest.php [hunk 12]
```diff
@@ -63,6 +70,44 @@ public function testGetHookStatus(): void
...
+    {
+        $hook = new \Hook();
+        $hook->name = 'enableHook';
+        $hook->active = false;
+        $hook->add();
+
+        $bearerToken = $this->getBearerToken();
+        static::createClient()->request('PUT', '/new-api/hook-status', [
+            'auth_bearer' => $bearerToken,
+            'json' => ['hookId' => (int) $hook->id, 'status' => (bool) !$hook->active],
```
Comment (jolelievre) [inline tests/Integration/ApiPlatform/GetHookStatusTest.php]:
```suggestion
            'json' => ['hookId' => (int) $hook->id, 'status' => true],
```

File: tests/Integration/ApiPlatform/GetHookStatusTest.php [hunk 13]
```diff
@@ -63,6 +70,44 @@ public function testGetHookStatus(): void
...
+        ]);
+        self::assertResponseStatusCodeSame(200);
+
+        $response = static::createClient()->request('GET', '/new-api/hook-status/' . (int) $hook->id, ['auth_bearer' => $bearerToken]);
+        self::assertEquals(json_decode($response->getContent())->active, !$hook->active);
```
Comment (jolelievre) [inline tests/Integration/ApiPlatform/GetHookStatusTest.php]:
```suggestion
        self::assertEquals(json_decode($response->getContent())->active, true);
```

**Review by 0x346e3730 — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
LGTM UI tests

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @mflasquin
