### PR TITLE
Select new invoice address automatically

### LINKED ISSUE #29289: Delivery address force as invoice address when use "use different addresses for invoice"
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hi,

Firstly, this issue is similar to this [one](https://github.com/PrestaShop/PrestaShop/issues/28511).

When a new customer chooses to use two different addresses for shipping and billing, PrestaShop forces the billing address with the shipping address previously created.

https://user-images.githubusercontent.com/8830801/183665685-a0ec1569-282e-4637-8e23-f01a1b205120.mov

That the payload post by the billing address form :
image

If you check the code [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutAddressesStep.php#L161-L202), I think it cause by this condition `if (isset($requestParams['id_address_delivery'])) {` beeing valid. So these [lines (L168 to L176)](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutAddressesStep.php#L168-L176)  are executed BUT, at this time, the `$this->use_same_address` is set to `true` (dont know why), that means the billing address is override by the delivery address get from the `id_address_delivery` field from the payload (L163).

### Expected behavior

Set billing address with the last created address (step 3 in **Steps to reproduce**)

### Steps to reproduce

Add product to your cart and go to the checkout
Next :
1. Create new customer
2. Create new delivery address and uncheck "use different addresses for invoice" 
3. Create new billing address
4. You will be redirected to step 3 but return to step 2 and see billing address set with delivery address

### PrestaShop version(s) where the bug happened

1.7.8.7 - 8.0.0 - develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fix when we select "use a different address" for the invoice address. Now the new address added as invoice address is indeed assignee as invoice address to the order.
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #29289
| Related PRs       | 
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/29289
| Possible impacts? | Try the whole process of a command to see if everything work well.

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

File: controllers/front/OrderController.php [hunk 1]
```diff
@@ -146,24 +146,9 @@ protected function bootstrap()
...
-            $invalidAddressIds = $addressValidator->validateCartAddresses($cart);
-            if (empty($invalidAddressIds)) {
-                $shouldGenerateChecksum = true;
-            }
-        }
-
-        $data['checksum'] = $shouldGenerateChecksum
-            ? $this->cartChecksum->generateChecksum($cart)
-            : null;
+        $data['checksum'] = $this->cartChecksum->generateChecksum($cart);
```
Comment (jolelievre) [inline controllers/front/OrderController.php:151]: Hi @lartist 

just a question regarding your modification, previously the Address was being checked to be sure it is valid before updating the cart checksum. With your modification it's not done anymore so although it means we're sure the checksum is updated more often, doesn't it also mean that it can be updated with an invalid address?

**Review by jolelievre — COMMENTED** [review]
Hi @lartist 

I know the change has already been approved, but it feels weird not to check addresses anymore no? Maybe we should check why the address was invalid instead and prevented from updating the checksum?

**Review by hibatallahAouadni — APPROVED** [review]
Hello @lartist 

Thanks for your PR :rocket: 
LGTM, QA :heavy_check_mark: 

https://user-images.githubusercontent.com/23308427/191726187-528529a6-50c2-4b5f-9893-0ab8a4d4e131.mp4

@jolelievre I see your comment here:
> With your modification it's not done anymore so although it means we're sure the checksum is updated more often, doesn't it also mean that it can be updated with an invalid address?

So, I checked if the address is checked or no, and it seems everything ok :heavy_check_mark: 
Please check the attached screen record below:

https://user-images.githubusercontent.com/23308427/191742254-37030f32-e314-4c89-81c9-9498cb949f39.mp4

Thanks!

**Comment by matks** [comment]
Thank you @lartist
