### PR TITLE
Replace a die() by PrestaShopException

### LINKED ISSUE #27115: Annoying Die() on changeOrderState on History class
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If you create a module using the method OrderHistory::changeIdOrderState and if the first parameter which is an id of OrderState doesn't exist (or doesn't exist anymore) for some wierd (or bad) reason, your code found on an annoying Die.

After that, you cannot catch, log, or do something to highlight the bug.

### Expected behavior

Throw a PrestaShopException instead of a Die.

### Steps to reproduce

1. Install a new Prestashop
2. Install the sample module [sample module issueorderhistory.zip](https://github.com/PrestaShop/PrestaShop/files/7784867/issueorderhistory.zip)
3. Go to configuration page of this module (it try to change state of order ID 5 in an unexistant state ID 125)
4. See an error "Invalid new order status" without the body of the page or standard error 500 page (status error is OK). 
 

### PrestaShop version(s) where the bug happened

all

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by clotairer**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | If you create a module using the method OrderHistory::changeIdOrderState and if the first parameter which is an id of OrderState doesn't exist (or doesn't exist anymore) for some wierd (or bad) reason, your code found on an annoying Die. After that, you cannot catch, log, or do something to highlight the bug.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27115
| How to test?      | See sample module. Instead of returning an error with a Die, the error is catch by the module at step 4.
| Possible impacts? | Change an order status

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27116)

### CODE REVIEW

File: classes/order/OrderHistory.php [hunk 1]
```diff
@@ -356,7 +356,7 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
 
         // changes invoice number of order ?
         if (!Validate::isLoadedObject($new_os) || !Validate::isLoadedObject($order)) {
-            die(Tools::displayError($this->trans('Invalid new order status', [], 'Admin.Orderscustomers.Notification')));
+            throw new \PrestaShopException($this->trans('Invalid new order status', [], 'Admin.Orderscustomers.Notification'));
```
Comment (PierreRambaud) [inline classes/order/OrderHistory.php]:
```suggestion
            throw new PrestaShopException($this->trans('Invalid new order status', [], 'Admin.Orderscustomers.Notification'));
```

**Review by PierreRambaud — COMMENTED** [review]
Just a little comment about the usage of namespace

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm :)

waiting for wording..

**Comment by PierreRambaud** [comment]
> lgtm :)
> 
> waiting for wording..

The wording didn't change, we can remove the label

**Comment by PierreRambaud** [comment]
Thank you @clotairer
