### PR TITLE
Remove i18n access restrictions

### LINKED ISSUE #19713: Cannot access Stock BO page for user which is not super-admin on 1.7.6.5 (or translation admin)
#### Describe the bug

On 1.7.6.5, a user who is not super-admin cannot access "Stock" page EVEN if I give him the necessary rights.

Bug reported by Mads Oliver Jenssen on open source slack

#### Expected behavior

People who have the right access should be able to access the page 😄 

#### Steps to Reproduce

1. Install 1.7.6.5
2. Modify "Logistician' employee profile, give him all accesses to "Stock" page
3. Create new employee, assign him the "Logistician" profile
4. Login as new employee, try to access 'Stock page'
- on first attempt: blank page
- if you refresh, you see a hundred of "access denied" messages

**Screenshots**

Capture d’écran 2020-06-11 à 15 32 42

#### Additional information

In "Network" tab in developer tools I see hundred of ajax calls to URL `http://localhost/admin/index.php/api/i18n/admin_domain` with HTTP response 302

Capture d’écran 2020-06-11 à 15 33 41

* PrestaShop version: 1.7.6.5
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | This controller action is needed for some VueJs pages. We can remove the access restrictions.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19713 
| How to test?  | - Install 1.7.6.5<br>- Modify "Logistician' employee profile, give him all accesses to "Stock" page<br>- Create new employee, assign him the "Logistician" profile<br>- Login as new employee, try to access 'Stock page'<br>- on first attempt: blank page<br>- if you refresh, you see a hundred of "access denied" messages
.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19716)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Api/I18nController.php [hunk 1]
```diff
@@ -37,7 +36,7 @@ class I18nController extends ApiController
     /**
      * Show translation for page-app build with vue-js.
      *
-     * @AdminSecurity("is_granted('read', request.get('_legacy_controller'))")
+     * No access restrictions because it is require for VueJs translations
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Api/I18nController.php]:
```suggestion
     * No access restrictions because it is required for VueJs translations
```

**Review by matks — DISMISSED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
This must be fixed in 1.7.6.x as well

**Comment by PierreRambaud** [comment]
> This must be fixed in 1.7.6.x as well

Ready #19718

**Review by matks — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @PierreRambaud
