### PR TITLE
CustomerAddressForm : Set a minimum length in HTML5

### LINKED ISSUE #37303: Postcode - set the minimum length for html5 forms
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Our postcode input looks like:
`<input id="field-postcode" class="form-control" name="postcode" type="text" value="12345" maxlength="12" required="">`
So, we use maxlength to tell browser 12 is max length, but we don't use minlength.
We should use this, because if customer wrote short postcode, he will be stopped by browser and we prevent unnecessary reload
If postcode format should be NNNNN, we must set minlength="5".
If postcode format should be NNNN, we must set minlength="4".
etc...
Example:
`<input id="field-postcode" class="form-control" name="postcode" type="text" value="12345" minlength="5" maxlength="12" required="">`

### Expected behavior

Use minlength

### Steps to reproduce

1. login to user account
2. go to section address
3. edit any adress
4. fill there "1234" to postcode (where is format for example NNNNN)
5. click on submit
6. you will see error about postcode, but AFTER reload (sub,ot). If we use minlength, customer will see error earlier and submit will not be processed before the customer fixes it

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | CustomerAddressForm : Set a minimum length in HTML5
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | 1. Login to user account on FO<br>2. Go to section address<br>3. Edit any adress<br>4. Fill there "1234" to postcode (where is format for example NNNNN)<br>5. Click on submit<br>6. You will see HTML5 Error about postcode.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #37303
| Related PRs       | PrestaShop/classic-theme/pull/172<br />PrestaShop/hummingbird/pull/712
| Sponsor company   | lefevre.dev

### CODE REVIEW

**Comment by Progi1984** [comment]
@ShaiMagal Interested by your feedback :)

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Shop.Notifications.Error`
    - [ ] `The %1$s field is too short (%2$d chars min).`

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva

File: classes/form/AbstractForm.php [hunk 1]
```diff
@@ -158,26 +158,42 @@ public function validate()
...
                         $this->translator->trans(
                             'The %1$s field is too long (%2$d chars max).',
                             [$field->getLabel(), $field->getMaxLength()],
                             'Shop.Notifications.Error'
                         )
                     );
+                } elseif (!$this->checkFieldMinLength($field)) {
+                    $field->addError(
+                        $this->translator->trans(
+                            'The %1$s field is too short (%2$d chars max).',
```
Comment (SharakPL) [inline classes/form/AbstractForm.php]:
```suggestion
                            'The %1$s field is too short (min %2$d chars).',
```

File: classes/form/AbstractForm.php [hunk 2]
```diff
@@ -158,26 +158,42 @@ public function validate()
...
```
Comment (SharakPL) [inline classes/form/AbstractForm.php]:
```suggestion
                            'The %1$s field is too short (min %2$d chars).',
```

**Comment by Progi1984** [comment]
@SharakPL Fixed :)

**Review by Codencode — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Comment by Progi1984** [comment]
@SharakPL & @Codencode Need 2 approvals there, too : PrestaShop/classic-theme/pull/172 & PrestaShop/hummingbird/pull/712

**Review by paulnoelcholot — APPROVED** [review]

**Comment by Progi1984** [comment]
Ping @PrestaShop/committers for merge

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.
