### PR TITLE
In BO > Orders: Fix disabled add voucher button

### LINKED ISSUE #25627: BO - Orders page - Cannot add a voucher - the Add button is disabled
#### Describe the bug

In the BO > Orders > Order details page, when we try to Add a discount, the Add button is disabled
image

#### Steps to Reproduce

1. Go to BO > Orders > Orders page
2. Open an order
3. Click Add discount
4. If it is Free shipping Fill the fields
5. See error: the Add button is always disabled
6. If It is a Percent Type or an Amount Type
7. See error: the Value Field is disabled 
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.4, 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In BO >Orders: Fix disabled add voucher button
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25627
| How to test?      | Cf. #25627
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25692)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/view.ts [hunk 1]
```diff
@@ -161,7 +161,12 @@ $(() => {
 
     $form.find(OrderViewPageMap.addCartRuleNameInput).on('keyup', (event) => {
       const cartRuleName = <string>$(event.currentTarget).val();
-      $(OrderViewPageMap.addCartRuleSubmit).attr('disabled', cartRuleName.trim().length === 0 ? 'true' : 'false');
+
+      if (cartRuleName.trim().length === 0) {
+        $(OrderViewPageMap.addCartRuleSubmit).attr('disabled', 'disabled');
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/view.ts:166]:
```suggestion
        $(OrderViewPageMap.addCartRuleSubmit).prop('disabled', true);
```

File: admin-dev/themes/new-theme/js/pages/order/view.ts [hunk 2]
```diff
@@ -161,7 +161,12 @@ $(() => {
...
+      } else {
+        $(OrderViewPageMap.addCartRuleSubmit).removeAttr('disabled');
+      }
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/view.ts]:
```suggestion
      $(OrderViewPageMap.addCartRuleSubmit).prop('disabled', cartRuleName.trim().length === 0);
```

What about this?

**Review by PierreRambaud — DISMISSED** [review]
Simple question, should be easier to understand

File: admin-dev/themes/new-theme/js/pages/order/view.ts (hunk 2 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/view.ts]: Better. Thanks.

**Review by NeOMakinG — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Go to BO > Orders > Orders > Edit Order
2. Try to add a discount with type Amount
3. See error the Value is disabled 
image

Thanks!

**Comment by PierreRambaud** [comment]
> Hi @Progi1984,
> 
> I have an issue following these steps:
> 
> 1. Go to BO > Orders > Orders > Edit Order
> 2. Try to add a discount with type Amount
> 3. See error the Value is disabled
>    image
> 
> Thanks!

@Progi1984 You also have to change this part of code:
```js
    $modal.on('shown.bs.modal', () => {
      $(OrderViewPageMap.addCartRuleSubmit).attr('disabled', 'true');
    });
```
into

```js
    $modal.on('shown.bs.modal', () => {
      $(OrderViewPageMap.addCartRuleSubmit).prop('disabled', true);
    });
```

**Review by sowbiba — DISMISSED** [review]

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,
I checked with @khouloudbelguith , The PR is OK :heavy_check_mark: 
Thanks,

**Comment by Progi1984** [comment]
Thanks @marwachelly & @khouloudbelguith
