### PR TITLE
ScrollIntoView if field is invalid

### LINKED ISSUE #13040: Problem with tooltips on migrated pages
**Describe the bug**
The problem is that when the page is scrolled down and the input is hidden under the page header, the tooltip still appears next to the input.

**To Reproduce**
1. Go to admin-dev/index.php/configure/advanced/employees/1/edit
2. Remove the name
3. Scroll down
4. Click on Save
5. See the tooltip

**Screenshots**
54812254-fa4c1a00-4c8a-11e9-9ea0-48c7aba45be3

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | ScrollIntoView if field is invalid
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13040 
| How to test?  | All fields with this kind of behavior must be visible if invalid.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13219)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/app/utils/fields.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
+const $ = global.$;
+
+/**
+ * Enable all datepickers.
+ */
+const initInvalidFields = () => {
+  $('input,select,textarea').each(function findElements() {
```
Comment (Quetzacoalt91) [inline admin-dev/themes/new-theme/js/app/utils/fields.js]: Does it work for elements added after the page load?

Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/app/utils/fields.js]: Nope, should it? I can change it!

Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/app/utils/fields.js]: I tried to add an invalid element in document/window peut nothing work. Look like it's not working with this event :disappointed:

File: admin-dev/themes/new-theme/js/app/utils/fields.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    $(this).on('invalid', function scroll() {
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/app/utils/fields.js]: You should use a [delegated event](https://learn.jquery.com/events/event-delegation/) instead of adding one event handler for each element.

**Review by eternoendless — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/app/utils/fields.js (hunk 2 above)
Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/app/utils/fields.js]: I tried, but it's not working with `invalid` event.
Tests with `window` and `document` but it's not working.
https://github.com/PrestaShop/PrestaShop/pull/13219#discussion_r272651959

Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/app/utils/fields.js]: But I refactor my code :)

**Comment by PierreRambaud** [comment]
Rebased!

**Comment by PierreRambaud** [comment]
Rebased again!

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PierreRambaud
