### PR TITLE
Fix javascript error in console in multistore `create shop` page

### LINKED ISSUE #24276: JS error thrown when create a new store
#### Describe the bug

Enable the multistore context, when you try to create a new store, a JS error will be displayed in the console:

```
VM1132:1 Uncaught SyntaxError: Identifier 'Tree' has already been declared
    at b (jquery-3.5.1.min.js:2)
    at Function.globalEval (jquery-3.5.1.min.js:2)
    at Object.dataFilter (jquery-3.5.1.min.js:2)
    at jquery-3.5.1.min.js:2
    at l (jquery-3.5.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:2)
    at Object.send (jquery-3.5.1.min.js:2)
    at Function.ajax (jquery-3.5.1.min.js:2)
    at Function.s.ajax (jquery-migrate-3.1.0.min.js:2)
    at Function.S._evalUrl (jquery-3.5.1.min.js:2)
```
PS: I didn't manage to reproduce the issue PS1.7.7.3, so it's a regression!

#### Expected behavior

No JS error displayed

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Shop Parameters** > **General**
2. Enable the option **Enable Multistore** > **Save**
3. **BO** > **CONFIGURE** > **Advanced Parameters** > **Multistore**
4. Click on **Add a new shop**
5. See error in console

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixes an error popping in the console 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24276
| How to test?      | Reproduction steps are detailed in the issue #24276
| Possible impacts? | 

# READ THIS BEFORE REVIEW

The initial bug was that after running autofix on js files, in many places `var` was replaced by `const`, which is normally a good thing. 

The problem with `Tree.js` is the file is loaded at least twice, once with the page, and once in ajax (Tree actually calls himself in ajax, weird I know...). So the variable `Tree` would be declared twice as a const, which would trigger an error.

I talked about it with other core-maintainers and we decided that this temporary patch was sufficient for the 1.7.8, because:

1 / It's not a regression, this weird behavior is only made noticeable now thanx to the autofix that was run on it 
2/ We don't really care about refactoring this code during feature freeze: this page will be migrated, and if we want to refactor this before this page's migration, then it should be done on develop

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24356)

### CODE REVIEW

File: admin-dev/themes/default/js/tree.js [hunk 1]
```diff
@@ -200,7 +200,7 @@ Tree.prototype = {
         },
       );
     } else {
-      $(this).$element.find('label.tree-toggler').each(
+      this.$element.find('label.tree-toggler').each(
```
Comment (matthieu-rolland) [inline admin-dev/themes/default/js/tree.js:204]: Here `$(this)` would trigger another error

File: admin-dev/themes/default/js/tree.js [hunk 2]
```diff
@@ -22,7 +22,7 @@
  * @copyright Since 2007 PrestaShop SA and Contributors
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  */
-const Tree = function (element, options) {
+var Tree = function (element, options) {
```
Comment (Progi1984) [inline admin-dev/themes/default/js/tree.js]:
```suggestion
const Tree = function (element, options) {
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback for fixing eslint

File: admin-dev/themes/default/js/tree.js (hunk 2 above)
Comment (matthieu-rolland) [reply admin-dev/themes/default/js/tree.js]: that's the fix :D. (I explained in the PR description, I'll make a comment so that the eslint doesn't complain)

Comment (Progi1984) [reply admin-dev/themes/default/js/tree.js]: In this case, use `let`. And remove the comment

Comment (matthieu-rolland) [reply admin-dev/themes/default/js/tree.js]: `let` triggers the same error, it doesn't allow declaring the same variable twice (you can change the value of the variable, but not declare it again)

**Review by matks — DISMISSED** [review]
I approving restoring the code to the initial state because the modification (var to const) introduced unwanted side-effects.

This PR restores the code to initial state, removing side-effects. Later on, a long-term suitable solution could be found that would allow us to follow eslint help without unwanted side-effects.

File: admin-dev/themes/default/js/tree.js (hunk 2 above)
Comment (Progi1984) [reply admin-dev/themes/default/js/tree.js]: Ok. In this case, may be @NeOMakinG can help you fixing correctly this bug ?

Comment (matthieu-rolland) [reply admin-dev/themes/default/js/tree.js]: well we can do it in 1.7.9 if we want to, I'll create an issue based on this one.  This behavior is not a 1.7.8 regression
(the issue is probably to be fixed on the PHP side), so it's not to be refactored during feature freeze, and not on 1.7.8.x

Comment (NeOMakinG) [reply admin-dev/themes/default/js/tree.js]: Did you test with global? or event window ?

`global.Tree` or event `window.Tree`? 

I think, when you declare a var outside of a function scope, it declare it as global, so maybe just using global.Tree will do the job :)

Comment (matthieu-rolland) [reply admin-dev/themes/default/js/tree.js]: I'll try this 👍  I didn't know the global `window.Tree` would be considered better than `var` by the linter

Comment (NeOMakinG) [reply admin-dev/themes/default/js/tree.js]: I've a doubt about window for this, but global may do the job way better

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matthieu-rolland !

After clearing browser cache :

The Multistore tree is now functional too (it was KO in 1.7.8, without the PR, but not reported in any issue AFAIK) in the different multistore pages.
In Add new Shop, Edit a shop, I no longer have the JS error. Also, the associated categories tree works fine (except the historical bug on collapse all/expande all buttons).

So it's QA :heavy_check_mark: , thanks !

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @Robin-Fischer-PS
