### PR TITLE
Fix combination supplier changes not taking effect

### LINKED ISSUE #26610: Combination supplier selection error
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

when selecting a supplier - table with supplier list should appear, but instead it throws console error.
Screenshot from 2021-11-15 15-17-29
### Expected behavior

table with supplier list should appear which allows modifying couple supplier fields before saving

### Steps to reproduce

1. Turn on experimental product page feature
2. Make sure you have suppliers created and enabled in sell -> catalog > brands & suppliers
3. Go to any experimental combinational product page and open combination edition form (by clicking the pencil icon on the left of combination list row).
4. Try to select any supplier while developer console is open. See the error.

------------------------------------------------------------

Enable Experimental Features

1. Go to Products list
2. Edit a product with combination using Experimental Features option that has already a supplier selected (demo product)
3. Go to Combinations tab > Edit one combination
4. Select a supplier > Save > Error : NOK
5. Refresh the page > Try to re-edit the same combination
6. Default supplier column disappeared : NOK

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Experimental product page combinations. Fix following: when selecting a supplier - table with supplier list should appear, but instead it throws console error. It seems that argument `productFormModel (which is used to fill supplier wholesale price` is null in product-supplier-manager.js. Screenshot from 2021-11-15 15-17-29
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/26610
| How to test?      | Make sure that selecting suppliers in `experimental product page combination edit` works as expected
| Possible impacts? | see bellow

Possible impacts:
* Sell -> Catalog -> Suppliers -> view page might be affected, as it needed additional touch to work after these changes (should work as before).
* Also removed method ProductSupplier::delete() which used to additionally remove all the product suppliers, so there might be possible impacts, but i couldn't find any direct usages.
* Removed product_supplier fixtures where product was combinational but product_supplier id_product_attribute was 0. (may affect tests)

BC breaks:
- ProductSupplier::delete() method removed. (it used to additionally remove all the product suppliers which was a strange side-effect causing troubles). 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26609)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
OK for this fix, however I'm not sure it fixes the whole bug especially the one mentioned here:
https://github.com/PrestaShop/PrestaShop/issues/26610#issuecomment-968936274

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

I have an issue following these steps:
1. Fresh install of this PR
2. Enable Experimental product page
3. Go to BO > Catalog > Products page
4. Edit a **demo** product with combinations V2 (for example id_product=1)
5. Edit any combination
6. Select another supplier and change the Default supplier
image
7. Save
8. See error 
image

I attached a screen record
https://watch.screencastify.com/v/c8Bkee6dg2XcxateH71Z

Thanks!

**Comment by zuk3975** [comment]
Ok, I've finally reproduced the bug and found the cause.
Adding WIP until this fixed.
Reminder to myself:
Starting at ProductSupplierUpdater:122 we are deleting "nonCombinationalSuppliers" that should just be some unused leftovers from legacy. 
**BUT** ProductSupplier object model delete() method has a side effect and it causes deletion of all the product suppliers on the first edition of combination.

Possible solution (it will introduce BC break, so need to double check what/if it really had a purpose).
* Remove the override of delete() in ProductSupplier;
* Adjust GetSupplierForViewingHandler, because it seem to be used there for some reason
* Remove ProductSupplier fixtures from combinational product where id_product_attribute = 0.


**EDITED**  :heavy_check_mark:  Done.

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php [hunk 1]
```diff
@@ -162,11 +165,10 @@ private function getSupplierProducts(Supplier $supplier, LanguageId $languageId)
                     $combinations[$attributeId]['attributes'] = $attribute;
                 }
 
-                $productInfo = Supplier::getProductInformationsBySupplier(
-                    $supplier->id,
-                    $product->id,
-                    0
-                );
+                $productInfo = Supplier::getProductInformationsBySupplier($supplier->id, $product->id);
```
Comment (jolelievre) [inline src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php]: I'm not sure but it seems like here you are ignoring every product which don't have a product_supplier with `id_product_atrribute == 0` It's fine for regular products, but I'm afraid this will cause all products with combinations to be ignored
So the page doesn't have a 500 error anymore, but it doesn't display everything it's supposed to either

Comment (zuk3975) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php]: yep you are right. I think now I've fixed it. Though I wonder, should I clean up this query?
Its a bit outdated and it returns different array depending if its combinational product or not. Or just leave it?

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]
I approve but I have a case of conscience : you modify the QueryHandler... but I don't see any changes in behat tests... 

Ping @zuk3975

File: admin-dev/themes/new-theme/js/pages/product/combination/edit.js [hunk 2]
```diff
@@ -38,6 +39,11 @@ $(() => {
     'TextWithLengthCounter',
   ]);
 
-  new ProductSuppliersManager(ProductMap.suppliers.combinationSuppliers, false);
+  const $productForm = $(window.parent.document.querySelector(ProductMap.productForm));
+  const {eventEmitter} = window.prestashop.instance;
+  // Init product model along with input watching and syncing
+  const productFormModel = new ProductFormModel($productForm, eventEmitter);
+
+  new ProductSuppliersManager(ProductMap.suppliers.combinationSuppliers, false, productFormModel);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/combination/edit.js:47]: You don't need to inject `productFormModel` here because it's only relevant for product form This needs to be refacto I'll create an issue for this
For now you can revert this modification (along with the one in suppliers manager)

File: admin-dev/themes/new-theme/js/pages/product/edit/product-suppliers-manager.js [hunk 3]
```diff
@@ -32,11 +32,11 @@ export default class ProductSuppliersManager {
    *
    * @param {string} suppliersFormId
    * @param {boolean} forceUpdateDefault
-   * @param {ProductFormModel|null} productFormModel
+   * @param {ProductFormModel} productFormModel
    *
    * @returns {{}}
    */
-  constructor(suppliersFormId, forceUpdateDefault, productFormModel = null) {
+  constructor(suppliersFormId, forceUpdateDefault, productFormModel) {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-suppliers-manager.js:43]: To be reverted as well

**Review by jolelievre — COMMENTED** [review]
Somme code needs to be reverted

Also it would be great if you can add some behat test for this CQRS query, you don't need to test the creation/editing Just the query itself, with all the data in the fixtures you should have enough to test he two use cases (combinations or not)

File: admin-dev/themes/new-theme/js/pages/product/combination/edit.js (hunk 2 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/combination/edit.js:47]: Sorry I misunderstood that this was needed to fix some js errors because I poorly handled this part ^^

I created a dedicated issue for this matter https://github.com/PrestaShop/PrestaShop/issues/26906 so it will be refactored and improved in another PR, for now, the most important is to fix the initial issue

Wer just need to add a `@todo` comment to explain it's a temporary fix and point at to the created issue

File: tests/Integration/Behaviour/Features/Context/Domain/SupplierFeatureContext.php [hunk 4]
```diff
@@ -33,13 +33,74 @@
...
 
 class SupplierFeatureContext extends AbstractDomainFeatureContext
 {
+    /**
+     * @Given /^supplier "(.+)" with name "(.+)" exists$/
+     *
+     * @param string $reference
+     * @param string $supplierName
+     */
+    public function existsByName(string $reference, string $supplierName): void
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/SupplierFeatureContext.php]: Please move it out of this Domain class, because this method doesn't use CQRS calls.

**Review by Progi1984 — COMMENTED** [review]
@zuk3975 A small feedback, please

File: tests/Integration/Behaviour/Features/Context/Domain/SupplierFeatureContext.php (hunk 4 above)
Comment (zuk3975) [reply tests/Integration/Behaviour/Features/Context/Domain/SupplierFeatureContext.php]: wasn't sure such convention exists, I always though we have just outdated architecture.

**Review by jolelievre — DISMISSED** [review]
Thank you @zuk3975

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

**First issue**
1. Go to BO > Catalog > Products V2 and create a product with two combinations for example
2. Edit the first combination and check a supplier "Fashion supplier" and save 
image
3. Go to the next combination and select another supplier 
image
4. Go back to the first combination
5. See error: the default supplier is changed but the second supplier is not checked 
image
6. now uncheck all suppliers for this combination and save 
image
7. Go to the second combination
8. See error => no default supplier checked 
image

I attached a screen record
https://watch.screencastify.com/v/zHp7WbS9DGpMmEv01L7i

**Second issue**
1. Create a supplier 1
2. Go to BO > Shop Parameters > General page and enable `Display suppliers`
image
3. Go to BO > Catalog > Edit a product with combinations V2
4. For each combination > Choose the supplier created and select it as a default supplier 
image
5. Save 
6. Go to FO > Sitemap > Suppliers > The list of the supplier created
7. See error: the product is not displayed 
image

I attached a screen record
https://watch.screencastify.com/v/awPnRcbY2lcHK1disACU

Thank you!

**Comment by jolelievre** [comment]
By the way @zuk3975 We discussed about how to handle suppliers for combinations I'll explain to you Monday 😉

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 

we discussed the bugs you found with @MatShir and we thought the edition of supplier deserves to be refactorized. I created a dedicated issue for this, however, I think it's worth merging this PR as is since it fixed the initial issue.

See the new issue that would be handled in a separate PR once this one has been merged https://github.com/PrestaShop/PrestaShop/issues/27034

**Comment by matks** [comment]
@jolelievre so if QA validates the PR, we merge without changes?

**Comment by jolelievre** [comment]
@matks The first issue will be fixed with the new design, so it's definitely out of this PR's scope indeed

For the second one it needs to be discussed and approved with Mateus and Khouloud, should it be fixed in this PR or can it wait for the next one?

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 

so after discussion with @MatShir  the second issue (in front) has to be fixed in this PR, I just pushed the fix so it should be good for this PR.

The first one, however, as I mentioned in my earlier comment, will be fixed by another issue that improves the UX of this part for combinations (see issue https://github.com/PrestaShop/PrestaShop/issues/27034) so it is not in this PR's scope.

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Thanks @jolelievre!

File: classes/Supplier.php [hunk 5]
```diff
@@ -154,9 +154,8 @@ public static function getSuppliers($getNbProducts = false, $idLang = 0, $active
 					JOIN `' . _DB_PREFIX_ . 'product` p ON (ps.`id_product`= p.`id_product`)
 					' . Shop::addSqlAssociation('product', 'p') . '
 					LEFT JOIN `' . _DB_PREFIX_ . 'supplier` as m ON (m.`id_supplier`= p.`id_supplier`)
-					WHERE ps.id_product_attribute = 0' .
+					WHERE product_shop.`visibility` NOT IN ("none")' .
```
Comment (sowbiba) [inline classes/Supplier.php:157]: Do we really need to use NOT IN? why not `<>` ?

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php [hunk 6]
```diff
@@ -118,77 +117,116 @@ private function getSupplierProducts(Supplier $supplier, LanguageId $languageId)
...
-
-                    if (!empty($combinations[$attributeId]['attributes'])) {
-                        $attribute = sprintf(', %s', $attribute);
-                    }
-
-                    $combinations[$attributeId]['attributes'] = $attribute;
-                }
+        foreach ($supplierProducts as $productData) {
+            $product = new Product($productData['id_product'], false, $languageId->getValue());
+            $product->loadStockData();
```
Comment (sowbiba) [inline src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php:122]: I saw in another PR this method being deleted

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php [hunk 7]
```diff
@@ -118,77 +117,116 @@ private function getSupplierProducts(Supplier $supplier, LanguageId $languageId)
...
+            $combinations = $this->findProductSupplierCombinations($product, $supplier, $languageId);
+
+            if (empty($combinations)) {
+                $products[] = $this->buildNonCombinationSupplierProduct($product, $supplier);
+                continue;
+            }
+
+            $products[] = [
```
Comment (sowbiba) [inline src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php:130]: the `$products` array entries does not have the same keys. it's disturbing for me :D

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php [hunk 8]
```diff
@@ -118,77 +117,116 @@ private function getSupplierProducts(Supplier $supplier, LanguageId $languageId)
...
+     * @param LanguageId $languageId
+     *
+     * @return array<int, array<string, mixed>>
+     *
+     * @throws LocalizationException
+     */
+    private function findProductSupplierCombinations(Product $product, Supplier $supplier, LanguageId $languageId): array
+    {
+        $productCombinations = $product->getAttributeCombinations($languageId->getValue());
+        if (!$productCombinations) {
```
Comment (sowbiba) [inline src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php]: Product::getAttributeCombinations is supposed to always return an array

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php (hunk 7 above)
Comment (sowbiba) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php:130]: Ow I see. It's the combinations which have the extra keys like ean13 or quantity

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php (hunk 6 above)
Comment (sowbiba) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php:122]: My bad, it was deleting this method for combinations
https://github.com/PrestaShop/PrestaShop/pull/26682/files#diff-a1cf5fd4d60c26d43efc6ffdad5f2606c95ca4bc50512ca4d92285ebcd687f0fL146

File: classes/Supplier.php (hunk 5 above)
Comment (jolelievre) [reply classes/Supplier.php:157]: It's the same you're right I just copied the existing query condition, I want to limit the modifications on legacy code

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php:122]: Yes this part was not removed yet in Product

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php (hunk 7 above)
Comment (jolelievre) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php:130]: Yes every products are in the same array, standard product have all the details But for products with combinations the details are only provided for each combinations
This code could be improved later with objects instead of flat array but it's not the purpose of this PR

File: src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php]: That's what the PHPDoc says but when no combinations exist the SQL query can return false

Comment (jolelievre) [reply src/Adapter/Supplier/QueryHandler/GetSupplierForViewingHandler.php]: Seems like when there is no combinations an empty array is returned actually, so I replaced this check with `empty($productCombinations)`

**Review by jolelievre — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]
👍🏾

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @zuk3975,

It is ok :heavy_check_mark: 
I checked
1. New product with combinations => ok https://watch.screencastify.com/v/rnDHBq2quuPFCJaqhtSq
2. Edit a product with combinations => ok https://watch.screencastify.com/v/H5jLlkWK8vxeXXjPdUo7
3. Create an order with those products
4. In the FO > Suppliers page > Products well displayed
5. Delete/Edit a supplier and check it again in the Product > Combinations Tab
6. Import suppliers & then create products associated with this supplier

Thanks!

**Comment by Progi1984** [comment]
Thanks @zuk3975 & @khouloudbelguith
