### PR TITLE
Fix 404 layout for wrong category

### LINKED ISSUE #24370: FO - confusing error message when we access to disabled category or a category page that does not exist
_Originally posted [here](https://github.com/PrestaShop/PrestaShop/pull/24270#issuecomment-830483500)_

#### Describe the bug

In FO, if you try to access a disabled category or a category page that does not exist, a wrong error will be displayed (see the attached screenshot n°1)

#### Expected behavior

It should display this page is not found (see the attached screenshot n°2)

#### Steps to Reproduce

1. Go to FO
2. Try to access a category that does not exist URL (for example : [URL]/fr/18-test)
3. See error > it display the wrong error message **No products available**
4. Create a category 
5. Disable the category
6. In FO, try to access the disabled category by URL
7. See error > it display the wrong error message **No products available**

**Screenshots**

https://drive.google.com/file/d/1FXBS2yphcE1OkdgLo0nnk-A2y_JyZ8OC/view

- Screenshot n°1

image

- Screenshot n°2

image

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

---
_PS: on develop, we still have these issues #24145 & #24143_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Since #21258, when trying to access a disabled or unexisting category, there is no redirection anymore. We display the 404 template directly. This needed some adjustments to have a matching 404 page everywhere.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24370
| How to test?      | Please see #24370
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24852)

### CODE REVIEW

File: controllers/front/listing/CategoryController.php [hunk 1]
```diff
@@ -155,7 +158,7 @@ public function initContent()
      */
     public function getLayout()
     {
-        if (!$this->category->checkAccess($this->context->customer->id)) {
+        if (!$this->category->checkAccess($this->context->customer->id) || $this->notFound) {
```
Comment (kpodemski) [inline controllers/front/listing/CategoryController.php:161]: hmm, why not redirect to the 404 page instead?

Comment (atomiix) [reply controllers/front/listing/CategoryController.php:161]: I guess it's bad for SEO: #21258

Comment (kpodemski) [reply controllers/front/listing/CategoryController.php:161]: Yeah, SEO, 3 devs, 3 opinions, probably 302 to 404 page would be enough, the best solution would be to have the option to select what to do in this kind of situation, same as on product page, maybe I'll create an issue about it for the future

**Review by kpodemski — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

File: controllers/front/listing/CategoryController.php (hunk 1 above)
Comment (PierreRambaud) [reply controllers/front/listing/CategoryController.php:161]: You shouldn't redirect to a 404 but the page itself has to return the HTTP 404 Not found Otherwise this means.
- Trying to reach /blabla
- Page found, goes to 302 with a redirection
- Woot it's a 404.

The /blabla is still found.

But maybe the right solution to add a custom `renderNotFound` in the FrontController.php, it will helps for rendering 404 page outside the CategoryController?

Comment (matks) [reply controllers/front/listing/CategoryController.php:161]: @kpodemski I have zero knowledge of SEO 😄  but I think the 404 makes sense.

If I search for category "Kid clothes"
- if it exists, server tells me a HTTP 200 => it exists!
- if it does not exists, server tells me a HTTP 404 => nope, there is no such thing
- if it existed but it was moved I expect a 301 or 302

So I find it logical, following HTTP response codes logic, to return the 404. For SEO I have no idea 😅

**Review by matks — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @atomiix !

**Comment by Progi1984** [comment]
As discussed with @PierreRambaud & @atomiix : ok but need a refactoring.
