### PR TITLE
Fix classic them subcategories in menu displayed hover menu by improving JS selector

### LINKED ISSUE #17794: Sometimes subcategories go over the menu and prevent clicking on it
**Describe the bug**
Sometimes on categories pages, subcategories go over the menu and prevent clicking on it

**To Reproduce**
1. Go to the front-office and click on Accessories
2. Try to click on Art
3. You can't because the subcategories go over
4. See error in the console

**Screenshots**

capture d'écran_2391

capture d'écran_2392

https://drive.google.com/open?id=1stnlle9F4Zwg4MV0oyfS-_bc9jPNOt3a

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Sometimes on category page, the submenu was over the menu and make the click on menu impossible
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes #17794 .
| How to test?  | Go on category page in FO, and try to over every categories, that should works fine :)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17843)

### CODE REVIEW

File: themes/classic/_dev/js/components/top-menu.js [hunk 1]
```diff
@@ -28,38 +28,39 @@ import DropDown from './drop-down';
...
-        
+        const classesSelected = Array.prototype.slice.call(e.currentTarget.classList).map(e => (typeof e === 'string' ? `.${e}` : false));
+
+        elmtClass = classesSelected.join('');
+
         if (elmtClass && $(e.target).data('depth') === 0) {
-          $(`.${elmtClass} .js-sub-menu`).css({
-            top: $(`.${elmtClass}`).height() + $(`.${elmtClass}`).position().top
+          $(`${elmtClass} .js-sub-menu`).css({
+            top: $(`${elmtClass}`).height() + $(`${elmtClass}`).position().top
```
Comment (NeOMakinG) [inline themes/classic/_dev/js/components/top-menu.js:44]: Here is the modification, with classesSelected too, others are linting... Definitly I wont think about committing lint before modifications!

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG
