### PR TITLE
Remove module list item when force deletion

### LINKED ISSUE #30952: Module does not disappear from module list after uninstalling and deleting it
### Describe the bug and add attachments

Discovered when working on https://github.com/PrestaShop/PrestaShop/pull/30863.

When you uninstall a module and check the "delete" checkbox in the modal, the module does not disappear from the list.

### Expected behavior

It should disappear, like in previous versions. 

➡️ Watch out for compatibility with ps_distribution api, when this module is available from a distribution module, it should not disappear from the list.

### Steps to reproduce

1. Get some develop branch ready, uninstall ps_distributionapi to be sure, clear cache.
2. Go to module manager.
3. Uninstall any module and check "delete module after uninstalling".
4. Module stays in the list.
5. (optional) Attempts to install it end up with red toast `Cannot Install module xxx. The module is invalid and cannot be loaded.` But that's normal, the module is not on the disk anymore.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When deleting a module, we can dynamically remove the module from the list, or force the reload of the page. I chose to do it dynamically in JS for user experience. <br/> We do not remove the module from the list if it has a download url, to be able to re-download it if necessary <br/> I also modified the behavior of the dropdowns for the buttons after uninstallation, in fact it was possible to delete a module that was already deleted
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see #30952
| Fixed ticket?     | Fixes #30952
| Related PRs       | -
| Sponsor company   | -

Attention, for the modifications to work correctly, the url of the distribution API must be modified for the purposes of the tests. Indeed the recovery of the list of modules for 8.1.x is not yet possible. See https://api.prestashop-project.org/prestashop for versions and  modify the PrestaShop/modules/ps_distributionapiclient/src/DistributionApi.php file
image

### CODE REVIEW

File: admin-dev/themes/new-theme/js/components/module-card.ts [hunk 1]
```diff
@@ -423,6 +423,10 @@ export default class ModuleCard {
           mainElement.attr('data-installed', '0');
           mainElement.attr('data-active', '0');
 
+          if (forceDeletion === 'true' || forceDeletion === true && moduleTechName !== 'ps_distributionapiclient') {
+            mainElement.hide();
```
Comment (boherm) [inline admin-dev/themes/new-theme/js/components/module-card.ts]: I'm not blocking for this, but why not use `.remove()` instead?

**Review by boherm — COMMENTED** [review]
LGTM, after ESLint fix!
Just one question for `.hide()` instead of `.remove()`. 😄

**Review by Hlavtox — DISMISSED** [review]
We should not be hardcoding a module name in the core, other distributions can have a different marketplace.

Also, we should check if this module is available from an API before removing it from the list, because it will reappear after refresh. 👍

**Review by tleon — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/components/module-card.ts (hunk 1 above)
Comment (M0rgan01) [reply admin-dev/themes/new-theme/js/components/module-card.ts]: I agree, remove is better

**Review by boherm — DISMISSED** [review]

**Review by 0x346e3730 — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by AchrafKchaou1991 — COMMENTED** [review]
Hello @M0rgan01 
It seems the issue still persist, see the attached screen record below:

[Pr32662.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/5e9b4b05-79a8-46f1-af51-71129992dfd4)

Waiting for your feedback.
Thanks!

File: admin-dev/themes/new-theme/js/components/module-card.ts (hunk 1 above)
Comment (M0rgan01) [reply admin-dev/themes/new-theme/js/components/module-card.ts]: The transition from hide to remove required a small additional tweak. You have to send the event before removing.
(` this.eventEmitter.emit('Module Uninstalled', mainElement);`)

Now it is good :smile:

**Review by boherm — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by aniszr** [comment]
Hello @M0rgan01

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @M0rgan01 

Thanks for your PR 🚀 
So, here's my test cases:

- Module non-native: uninstall ✅ Module dispeared ✅ can't find in the list ✅ 
- Module native: Uninstall ✅ Module dispeared ✅ can not found in the list ❌ even when we reset the distributionapi, the module still not found ❌ 

Please check the attached screen record below and feedback:

[pr-32662.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/0d923939-4138-4f1b-94f0-8754b0708d78)

Thanks!

**Comment by matks** [comment]
@hibatallahAouadni It is important to be aware that _the behavior for a development branch and the behavior for a live version are not the same_.

## If you are on a live version, let's say you use 8.0.4

If you uninstall the module pagenotfound and you choose to _delete the files from the disk_ then the module is not available anymore in your `modules/` folder. However PrestaShop is able to poll the API endpoint https://api.prestashop-project.org/modules/8.0.4 and to find it. Then PrestaShop is able to display a "Install" button, because it is capable of retrieving the module from the API.

## If you are on a live version, let's say you use `develop` branch -> it means version is 9.0.0

There is no endpoint https://api.prestashop-project.org/modules/9.0.0

If you uninstall the module pagenotfound and you choose to _delete the files from the disk_ then the module is not available anymore in your `modules/` folder. And PrestaShop is NOT able to poll the API endpoint https://api.prestashop-project.org/modules/9.0.0 to find it. Then PrestaShop is NOT able to display a "Install" button for pagenotfound module, because it is not capable of retrieving the module from the API. So the pagenotfound module is not shown in the modules list, and it is the expected behavior

**Comment by M0rgan01** [comment]
@Hlavtox I propose a new version of my PR :)

**Review by tleon — COMMENTED** [review]
LGTM, I'm not the best at js / ts would be great if others could have a look.

**Review by matthieu-rolland — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @M0rgan01 

Thanks for your PR,the module display issue is solved.LGTM :heavy_check_mark: 

See attached screenvideo:

https://github.com/PrestaShop/PrestaShop/assets/92626242/7b220c13-40f5-4f2f-9a36-96b8d40611e9

Thanks!

**Comment by kpodemski** [comment]
thank you @M0rgan01
