### PR TITLE
Fix: [BO] Admin Countries page redirect issue with multishop after changing shop

### LINKED ISSUE #40059: [BO] Admin Countries page redirect issue with multishop after changing shop
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

With multishop enabled and the site installed in a subfolder, when navigating to International > Locations > Countries and switching shops, any subsequent action on the page - such as enabling/disabling, editing, or saving Country options - leads to a 404 error.
However, if after changing shops you click on the "Countries" tab again, everything works correctly.

https://github.com/user-attachments/assets/7c587476-3d49-4fd8-89c9-a2ea1a61000c

### Expected behavior

_No response_

### Steps to reproduce

1. Enable multishop and create a second store
2. Go to International > Locations > Countries
3. Enable/disable a country
4. Switch store
5. Try to enable/disable the country and you will see the error

Note: If the problem doesn't occur, try switching stores multiple times and then performing an operation on the page

### PrestaShop version(s) where the bug happened

9.0.x

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Codencode snc

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | I updated the redirect logic after changing the shop context to no longer rely on `Request::getUri()`, but instead rebuild the URL using the components of the `Request` (`getSchemeAndHttpHost()`, `getBasePath()`, `getPathInfo()`, `getQueryString()`).
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Enable multishop and create a second store<br> 2. Go to International > Locations > Countries<br> 3. Enable/disable a country<br> 4. Switch store<br> 5. Now you should be able to enable/disable/edit a country without getting a 404 error.
| UI Tests          | 🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/19567664393
| Fixed issue or discussion?     | Fixes #40059
| Related PRs       | 
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by Codencode** [comment]
An alternative solution, suggested by @tylerward99, is to uncomment these 2 lines in the admin's **.htaccess** file:
https://github.com/PrestaShop/PrestaShop/blob/6a165828ba4c90e300ceb8590998cefe67cc7ee3/admin-dev/.htaccess#L51-L52

@PrestaShop/committers Could you give me some feedback about this?

**Comment by Codencode** [comment]
@Hlavtox @kpodemski could you give me some feedback on this PR?
Thanks

**Review by Hlavtox — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

File: src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php [hunk 1]
```diff
@@ -324,9 +324,18 @@ private function createShopContextUpdateRedirectResponse(ShopConstraint $updated
         }
         $legacyCookie->write();
 
+        // Rebuild the current URI from the Request components to avoid relying on /index.php in the raw URL
+        $request = $requestEvent->getRequest();
+
+        $uri = $request->getSchemeAndHttpHost() . $request->getBasePath() . $request->getPathInfo();
```
Comment (jolelievre) [inline src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php:330]: Seems like the difference here is only that you use `getBasePath` instead of `getBaseUrl` right?

Are you sure it's a good ifea? This won't work for configurations that don't have url rewriting enabled, and it reaaly ssems overkill if the purpose is only to remove the `index.php` part no?

Comment (Codencode) [reply src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php:330]: Hi Jonathan,
yes, the goal is to remove index.php. I didn’t quite understand in which situation it doesn’t work.
What do you suggest to remove index.php?

**Comment by SiraDIOP** [comment]
Hello @Codencode, 

Thanks for your PR, i tested it and it's good for me ^^


https://github.com/user-attachments/assets/f10f6798-bca4-4955-9d8e-859228510918

Thanks

**Review by SiraDIOP — APPROVED** [review]

**Comment by Codencode** [comment]
@jolelievre, can we merge or do you have any suggestions?

File: src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/EventListener/Admin/Context/ShopContextSubscriber.php:330]: Nevermind, I'm scared of side effects but it will popup eventually it there are any
