### PR TITLE
Dynamic pack quantity

### LINKED ISSUE #36825: Use Quantity of Products in Pack does not show quantity in 8.1.7
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a pack of products, pack stock behavior is set to "Use quantity of products in the pack". There are 2 pack items with a quantity of 300 each, so the pack should also show 300. However, it says the quantity is 0 on the product and products page.

{D22CCD56-CF18-4AB4-A524-2FD5F5DA3CC2}

{8220A48D-2D19-438B-B182-D184B708350E}

### Expected behavior

The Product and Products pages should show the quantity of the products in the pack.

### Steps to reproduce

1. Create a pack of products
2. Add 2+ products that are in stock
3. Set Pack stock behavior to "Use quantity of products in the pack"
4. Save and look at quantity on product or products pages

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Compute pack quantity dynamically absed on its config and contained products' stocks in CQRS, integrate this dynamic quantity in the form header and in the product grid
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green UI tests green, see issue
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/21220936427
| Fixed issue or discussion?     | Fixes #36825
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

File: src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php [hunk 1]
```diff
@@ -239,6 +242,23 @@ private function applyModification(array $products, ShopSearchCriteriaInterface
                 (string) $priceTaxIncluded,
                 $currency->iso_code
             );
+
+            $productType = $products[$i]['product_type'] ?? null;
+            // For pack products we dynamically update the quantity in the column so that it reflects its quantity based on
+            // its configuration and the quantity of its products. Since it's done in the decorator the dynamic quantity is not
+            // consistent with sorting and filtering Including this complexity in the query builder would cost too much in performance
+            // and would be too complex so it's a compromise
+            if ($productType === ProductType::TYPE_PACK) {
```
Comment (Hlavtox) [inline src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: The type could be the default one, if the product was not modified using the new product page, you have to account for this. 😎

**Review by Hlavtox — DISMISSED** [review]
Some comment, otherwise great job as always!

File: src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: After upgrade to v8 this column should be updated already If the column is not updated then I think we can just ignore it, you will get the quantity of the pack itself and it's not that bad This additional feature is already compromising enough IMHO

Comment (Hlavtox) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: Yes, but it was still allowed to create products without type. Legacy page, modules, imports.

You have to support `producttype::TYPE_UNDEFINED`. There are methods in Product for this specific reason - check out getProductType and getDynamicProductType. 🙏

Comment (jolelievre) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: I don't understand your point if the type is undefined it's not a pack so why would I care about getting a pack quantity The legacy page is long gone, the data should have been migrated since v8 if the shop still has products without types when it reaches the v9 it means it's not following the recent core modifications, so too bad it won't get this super fancy pack quantity (which is accessory IMHO)

Unless you can show me where in the legacy page this was handled?

Comment (jolelievre) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: I already didn't want to do something in the list because this breaks the consistency with filtering and sorting, so I can remove it completely, but I won't do more than this

Comment (Hlavtox) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: If it's undefined, it was created using the legacy code, it can still be a pack. That's why getDynamicProductType was introduced.

Comment (Hlavtox) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: @kpodemski please help

Comment (kpodemski) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:251]: `|| $product['cache_is_pack']`?

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Putting block back as the PR doesn't include all product types possible in the database.

A new Product is created as UNDEFINED by default even in 9.0.

```
'product_type' => [
                'type' => self::TYPE_STRING,
                'validate' => 'isGenericName',
                // For now undefined value is still allowed, in 179 we should use ProductType::AVAILABLE_TYPES here
                'values' => [
                    ProductType::TYPE_STANDARD,
                    ProductType::TYPE_PACK,
                    ProductType::TYPE_VIRTUAL,
                    ProductType::TYPE_COMBINATIONS,
                    ProductType::TYPE_UNDEFINED,
                ],
                // This default value should be replaced with ProductType::TYPE_STANDARD in 179 when the v2 page is fully migrated
                'default' => ProductType::TYPE_UNDEFINED,
            ],
```

and there is no adjustment in add or update methods.

**Comment by kpodemski** [comment]
The fallback could work on `cache_is_pack`, but I think we should stick to the changes introduced by a new product page and force third-party tools to set proper `product_type` :)

**Review by Hlavtox — DISMISSED** [review]
We discussed this with Krystian and came up with a solution.

Rerun this in 9.1.0.sql

UPDATE `PREFIX_product` SET `product_type` = “standard”;
UPDATE `PREFIX_product` SET `product_type` = “combinations” WHERE `cache_default_attribute` != 0;
UPDATE `PREFIX_product` SET `product_type` = “pack” WHERE `cache_is_pack` = 1;
UPDATE `PREFIX_product` SET `product_type` = “virtual” WHERE `is_virtual` = 1;

and we remove the UNDEFINED type as default for 9.1.0

With a clear error message if someone tries to create it.

**Review by kpodemski — DISMISSED** [review]

**Comment by jolelievre** [comment]
@Hlavtox @kpodemski yep my bad I was sure we already handled this in 8.something upgrade
But it was older and was done in 1.7.8 https://github.com/PrestaShop/autoupgrade/blob/4fa7eddc34c2dc6f225e9e8459a00040982fe4ff/upgrade/sql/1.7.8.0.sql#L209

So indeed many products can have been created since then that are not up-to-date
The improvement in 9.1.0.sql makes sense

**Review by SiraDIOP — COMMENTED** [review]
Hello @jolelievre, 

Thanks for your PR, could you please restart the automated tests?
Thanks

**Review by tleon — DISMISSED** [review]

**Comment by jolelievre** [comment]
@SiraDIOP, there is a UI test that is failing (not a random fail), I'm working on adapting it

**Comment by jolelievre** [comment]
@SiraDIOP tests should be green now (currently running, but the part that failed already has succeeded)

**Comment by Hlavtox** [comment]
@kpodemski @jolelievre We should check for performance, I hope the page is still usable when 1000 products displayed for example. Just to be sure.

**Review by Progi1984 — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by mattgoud — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @jolelievre, 

Thanks for your PR, i tested it and it's good for me ^^

https://github.com/user-attachments/assets/52bc525b-03eb-4c76-b00d-58cdb2e2591d

**Review by SiraDIOP — APPROVED** [review]

**Comment by Hlavtox** [comment]
@SiraDIOP @jolelievre It would be good to mention that it doesn't work in filters and sorting.
