### PR TITLE
Order zero ratio for order detail tax

### LINKED ISSUE #22008: BO - Order page - Adding a product on empty order : Invoice NOK
#### Describe the bug

When I add a product on an empty order (for example, an order with one product, the product is deleted, and a new product is added), the tax block in the generated invoice is NOK : It only contains the Shipping tax and not the Product tax 

#### Expected behavior

Tax block should also contain the product tax.

#### Steps to Reproduce

1. Create order from the FO with only one product
2. Delete the product and refresh : The order is empty, status changed to "canceled"
3. Add a product to the order and refresh
4. Generate the invoice or change status of the order to Payment accepted
5. Download the invoice : The taxes block is NOK : Only the Shipping tax in displayed but not the product tax. Rest of the invoice is OK.

**Screenshots**

no tax on product

https://drive.google.com/file/d/1jVBtdnBrcsIagBDg6ARgKS1WjzXTnchy/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x, 177RC1Build4
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Handle zero ratio for order detail tax. See details below
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/22008
| How to test?  | See ticket

## Details

When an order is empty, property `$order->total_products` is zero.

When adding a product to empty order, we arrive there: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/OrderDetail.php#L396
```
        if ($order->total_products <= 0) {
            return true;
        }
        ...

        $ratio = $this->unit_price_tax_excl / $order->total_products;
```

Unfortunately at this moment `order->total_products` is not yet updated so the code exists early, which prevents correct creation of `order_detail_tax`.

After thorough exploration of the logic with @jolelievre we think that this property is only used to compute the ratio below. Since the only usecase where `$order->total_products` is zero is "when we add a product to an empty order", it means the ratio in this case is 1 so in the PR I force the value to 1.

````
$ratio = ($order->total_products > 0) ? ($this->unit_price_tax_excl / $order->total_products) : 1;
```

**I also added a Behat test that, if run on `1.7.7.x` fails so the test validates that the bug is fixed**. QA exploratory tests should complete the validation of this Pull Request.

<!-- Click the form's "Preview" button to make sure the table is functional in GitHub. Thank you! -->

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prestashop/prestashop/22018)
<!-- Reviewable:end -->

### CODE REVIEW

**Comment by matks** [comment]
Tests are coming

**Review by eternoendless — COMMENTED** [review]
What about this?
https://github.com/matks/PrestaShop/blob/c7f4de5ec40f76f371befd3e811b0d02ad639df7/classes/order/OrderDetail.php#L375-L380

**Comment by jolelievre** [comment]
> What about this?
> https://github.com/matks/PrestaShop/blob/c7f4de5ec40f76f371befd3e811b0d02ad639df7/classes/order/OrderDetail.php#L375-L380

Thats a comment I added a while back when I realized this method is still very much needed Mainly because `Order::updateOrderDetailTax` is still buggy I tried to fix it with minimum impact but it soon became a HUGE refacto which was way out of the initial scope of my fix

So since we were kind of in the rush for releasing a version, and still are, I preferred to limit the impact of my modification, but it would be worth fixing this

**Review by jolelievre — COMMENTED** [review]
I'm waiting for the behat tests for this scenario but I'm ok with this 😉

**Review by jolelievre — APPROVED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 1]
```diff
@@ -380,6 +380,49 @@ public function checkInvoiceShippingTaxDetails(string $invoicePosition, string $
...
+     * @param string $invoicePosition
+     * @param string $orderReference
+     * @param TableNode $table
+     */
+    public function checkInvoiceProductTaxDetails(string $invoicePosition, string $orderReference, TableNode $table)
+    {
+        $orderId = SharedStorage::getStorage()->get($orderReference);
+        $invoiceProductData = $table->getColumnsHash();
+
+        $order = new Order($orderId);
```
Comment (sowbiba) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:395]: no need to cast ?

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 1 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:395]: answer myself :D :D https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php#L129

**Comment by khouloudbelguith** [comment]
Hi @matks,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1Pf5cBf3T-sGKJ68Jz8jOvoF9byYp0T9I/view?usp=sharing

PS: during the test of this PR, I found this issue: https://github.com/PrestaShop/PrestaShop/issues/22029

Thanks!

**Comment by Progi1984** [comment]
Thanks @matks & @khouloudbelguith
