### PR TITLE
Incorrect email subject and template variable {shop_name}

### LINKED ISSUE #16499: Incorrect email subject and template variable {shop_name}
In PS 1.7.6.1 the email subject and template variable {shop_name} display the internal BO name from the "Multishop" settings. It should display the external name from "Contact" settings.

I patched /classes/Mail.php as follows:

```
//BEGIN PATCH
//            $subject = '[' . $shop->name . '] ' . $subject;
            $subject = '[' . Tools::safeOutput(Configuration::get('PS_SHOP_NAME', null, null, $id_shop)) . '] ' . $subject;
//END PATCH
```
and
```
//BEGIN PATCH
//            $templateVars['{shop_name}'] = Tools::safeOutput($shop->name);
            $templateVars['{shop_name}'] = Tools::safeOutput(Configuration::get('PS_SHOP_NAME', null, null, $id_shop));
//END PATCH
```

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | The `shop_name` must be retrieve from the shop configuration and not from `shop->name`
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16499 
| How to test?  | Follow ticket instruction

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16500)

### CODE REVIEW

File: classes/Mail.php [hunk 1]
```diff
@@ -505,7 +505,7 @@ function ($carry, $item) {
                 Context::getContext()->link = new Link();
             }
 
-            $templateVars['{shop_name}'] = Tools::safeOutput($shop->name);
```
Comment (Progi1984) [inline classes/Mail.php:508]: @PierreRambaud Couldn't store it in a variable for avoiding two call to `Configuration::get` ?

**Review by Progi1984 — APPROVED** [review]

File: classes/Mail.php (hunk 1 above)
Comment (PierreRambaud) [reply classes/Mail.php:508]: Thanks, didn't notice we have the `Configuration::getMultiple` :)

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

It is OK.
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @PierreRambaud

**Comment by LucaMozzo** [comment]
@khouloudbelguith hi, how did you do QA? I had this problem, changed the code according to this PR, cleaned the cache and regenerated the email templates (override existing enabled), and still getting the old name, did I miss a step?

**Comment by khouloudbelguith** [comment]
Hi @LucaMozzo,

It is well working with PS1.7.6.2
https://drive.google.com/file/d/1dgTDalZF2VnkySdpHkQNJpw7holMgSt6/view
Only this issue: https://github.com/PrestaShop/PrestaShop/issues/16847
Thanks!

**Comment by micka-fdz** [comment]
Encoding issues fixed here : #17073
