### PR TITLE
Disable shop context switching from the multistore header if the shop has no URL

### LINKED ISSUE #23785: Multistore - Issues when a shop without URL is selected as context
#### Describe the bug

Following [the comment](https://github.com/PrestaShop/PrestaShop/pull/23292#issuecomment-808203554) of @Robin-Fischer-PS 

When a store without URL is selected as context the following issues appears:

1) On migrated pages, in the new multistore header, the "Configure URL" link redirects to the listing page with all the shops' URLs instead of redirecting to the shop URL edit page

2) On migrated & legacy pages, the icon of the Gamification module is broken
pr 23292 broken display no url

3) On legacy pages, the multistore dropdown (allowing to select the context) is no longer displayed 

#### Expected behavior

As a merchant I should not be able to select as context a shop without URL defined

**Screenshots**

https://drive.google.com/file/d/1ALc8s3duL-vMPPsIPKzjo6fiNC6pmAiA/view?usp=sharing

#### Specs

https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR disable shop context URL in the multistore header if the shop has no URL defined. The link is not clickable and the autocomplete search bar doesn't return the shop. Behat tests have been updated accordingly.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23785
| How to test?      | In multistore context, create a shop without defining its URL. Then go on a migrated page, you should not be able to switch context on this shop, and the shop should not be returned in the autocomplete search bar.
| Possible impacts? | 

Eventually, people should be able to configure their shop even if it has no URL specified yet. In legacy it is not possible, by making it possible we noticed some strange behaviors that need to be fixed. For now we disable it, just like in legacy, once we have fixed those issues we will enable it again.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23840)

### CODE REVIEW

File: src/Adapter/Shop/QueryHandler/SearchShopsHandler.php [hunk 1]
```diff
@@ -83,14 +83,16 @@ public function handle(SearchShops $query): array
...
+            if ($shop->hasMainUrl()) {
+                $result[] = new FoundShop(
+                    $shop->getId(),
+                    $shop->getColor() ?? '',
+                    $shop->getName(),
+                    $shop->getShopGroup()->getId(),
+                    $shop->getShopGroup()->getName(),
+                    $shop->getShopGroup()->getColor()
+                );
+            }
```
Comment (Progi1984) [inline src/Adapter/Shop/QueryHandler/SearchShopsHandler.php]:
```suggestion
            if (!$shop->hasMainUrl()) {
                continue;
            }
            
            $result[] = new FoundShop(
                $shop->getId(),
                $shop->getColor() ?? '',
                $shop->getName(),
                $shop->getShopGroup()->getId(),
                $shop->getShopGroup()->getName(),
                $shop->getShopGroup()->getColor()
            );
```

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php [hunk 2]
```diff
@@ -131,6 +132,30 @@ public function addShop(string $reference, string $shopName, string $color, stri
         SharedStorage::getStorage()->set($reference, $shop);
     }
 
+    /**
+     * @Given I add a shop url :reference to shop :shopReference
+     *
+     * @param string $reference
+     * @param string $shopReference
+     */
+    public function addShopUrl(string $reference, string $shopReference)
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php]:
```suggestion
    public function addShopUrl(string $reference, string $shopReference): void
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig [hunk 3]
```diff
@@ -53,11 +53,7 @@
 
     {% if isShopContext %}
       <div class="header-multishop-right">
-        {% if currentContext.hasMainUrl() %}
-          <a class="header-multishop-view-action" href="{{ link.getBaseLink(currentContext.id) }}" target="_blank" rel="nofollow">{{ "View my shop"|trans({}, 'Admin.Navigation.Header') }} <i class="material-icons">visibility</i></a>
-        {% else %}
-          <a class="header-multishop-view-action" href="{{ getAdminLink('AdminShop', true, {'shop_id' : currentContext.id}) }}" rel="nofollow">{{ "Configure URL"|trans({}, 'Admin.Actions') }} <i class="material-icons">visibility</i></a>
-        {% endif %}
+        <a class="header-multishop-view-action" href="{{ link.getBaseLink(currentContext.id) }}" target="_blank" rel="nofollow">{{ "View my shop"|trans({}, 'Admin.Navigation.Header') }} <i class="material-icons">visibility</i></a>
```
Comment (Progi1984) [inline src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig:56]: So it's not possible anymore to configure URL @matthieu-rolland  ?

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig:56]: yes, it's still possible, why?

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig:56]: This PR disables the context switching link if the shop has no URL, but there is still the link to configure the URL.

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Resources/views/Admin/Multistore/header.html.twig:56]: Ah I understand why you ask this: The link I remove here is the configure URL link at the top right of the header, for the current context. But since we can't switch context on a shop not having a URL specified, the configure URL will never appear at the top right of the header.

But it will still appear inside the header dropdown (see line 103)

**Review by NeOMakinG — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@matthieu-rolland CodeStyle CI not happy 😓

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland CodeStyle CI not happy 😓

ah yes, that's the risk of commits through Github's interface :D

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Thanks @matthieu-rolland , it works fine both on Legacy and migrated pages (and also without multistore enabled).

Note that the bug can still be reproduced by going to a shop context, then delete the URL of the shop, but this is not a regression, it was already there at least in 1.7.5 (and probably since the multistore exist).

QA :heavy_check_mark:

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @Robin-Fischer-PS
