### PR TITLE
Check Select Privilege in the Install Process

### LINKED ISSUE #13442: Installation failing with wrong error message when does not have SELECT priviliege on database
**Describe the bug**
When using the installer, if the mysql user has admin and write privileges, but not reading one, the installation is failing, but with a useless error message. We wasted hours before figuring out the actual issue.

**To Reproduce**
1. Get a mysql database with a user with all the permission, but SELECT
1. Go through the installation wizard

Current:
- Failing at 23%
- Error message `1: Cannot install language "English (English)"`
- There is a single line in the log file `prod_20190415_installation.log`

> *ERROR*     v1.7.5.1    2019/04/15 - 20:00:52: Cannot install language "English (English)"

Expected:
- Get a useful error message like `The mysql user cannot read the database`

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.15

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check Select Privilege in the Install Process
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13442
| How to test?  | * Create a user with SELECT privilege<br>* Install PrestaShop<br>* The installation is going well<br>* Create a user without SELECT privilege<br>* Install PrestaShop<br>* At Database process, click on "Test" and you should have this message<br>image<br><br>SQL Request for creating a user without no SELECT privilege<br>`CREATE USER 'usernoselect'@'localhost';`<br>`ALTER USER 'usernoselect'@'localhost' IDENTIFIED BY 'usernoselect' ;`<br>`GRANT ALL PRIVILEGES ON *.* TO 'usernoselect'@'localhost';`<br>`FLUSH PRIVILEGES;`<br>`REVOKE Select ON *.* FROM 'usernoselect'@'localhost';`<br>`FLUSH PRIVILEGES;`
  

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19856)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Install/Database.php [hunk 1]
```diff
@@ -104,6 +104,15 @@ public function testDatabaseSettings($server, $database, $login, $password, $pre
             }
         }
 
+        if (!$errors) {
+            if (($select_error = Db::checkSelectPrivilege($server, $login, $password, $database, $prefix)) !== true) {
+                $errors[] = $this->translator->trans('Your database login does not have the privileges to select data in table on the database "%s". Ask your hosting provider.', ['%database%' => $database], 'Install');
```
Comment (Junebyun) [inline src/PrestaShopBundle/Install/Database.php]:
```suggestion
                $errors[] = $this->translator->trans('Your database login does not have the privileges to select data in table from the database "%s". Ask your hosting provider.', ['%database%' => $database], 'Install');
```

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Install/Database.php [hunk 2]
```diff
@@ -104,6 +104,15 @@ public function testDatabaseSettings($server, $database, $login, $password, $pre
             }
         }
 
+        if (!$errors) {
+            if (($select_error = Db::checkSelectPrivilege($server, $login, $password, $database, $prefix)) !== true) {
+                $errors[] = $this->translator->trans('Your database login does not have the privileges to select data in table from the database "%s". Ask your hosting provider.', ['%database%' => $database], 'Install');
```
Comment (Junebyun) [inline src/PrestaShopBundle/Install/Database.php]:
```suggestion
                $errors[] = $this->translator->trans('Your database login does not have the privileges to select data in table from the database "%s". Please ask your hosting provider to have them.', ['%database%' => $database], 'Install');
```

Comment (Progi1984) [reply src/PrestaShopBundle/Install/Database.php]: Thanks @Junebyun

**Review by Junebyun — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Install/Database.php [hunk 3]
```diff
@@ -104,6 +104,15 @@ public function testDatabaseSettings($server, $database, $login, $password, $pre
             }
         }
 
+        if (!$errors) {
+            if (($select_error = Db::checkSelectPrivilege($server, $login, $password, $database, $prefix)) !== true) {
+                $errors[] = $this->translator->trans('Your database login does not have the privileges to select data in table from the database "%s". Please ask your hosting provider to have them.', ['%database%' => $database], 'Install');
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Install/Database.php]: Hi there, I've searched about this privilege because I did not know what it was and it looks like the right terminology about this action is _grant CREATE/DROP/etc. privilege_ ([read](https://mediatemple.net/community/products/dv/204404494/how-do-i-grant-privileges-in-mysql)), therefore I suggest the following wordings: 

- _You must be granted the privilege to select data in the tables of database "%s". Ask your hosting provider to enable it._ which should be easier for merchants to understand the issue

- _Your current login must be granted the SELECT privilege for database "%s". Ask your hosting provider to enable it._ which should fit the technical terminology

@Junebyun, what do you think?

Comment (Junebyun) [reply src/PrestaShopBundle/Install/Database.php]: Hi @LouiseBonnard, thank you for your suggestions! I will go with the first option. :)

Comment (Junebyun) [inline src/PrestaShopBundle/Install/Database.php]:
```suggestion
                $errors[] = $this->translator->trans('You must be granted the privilege to select data in the tables of database "%s". Ask your hosting provider to enable it.', ['%database%' => $database], 'Install');
```

Comment (Progi1984) [reply src/PrestaShopBundle/Install/Database.php]: :heavy_check_mark:

**Review by LouiseBonnard — DISMISSED** [review]

**Review by Junebyun — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Install/Database.php [hunk 4]
```diff
@@ -104,6 +104,15 @@ public function testDatabaseSettings($server, $database, $login, $password, $pre
             }
         }
 
+        if (!$errors) {
+            if (($select_error = Db::checkSelectPrivilege($server, $login, $password, $database, $prefix)) !== true) {
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Install/Database.php]: Is it possible to merge those two consecutive conditions into a single one?

File: src/PrestaShopBundle/Install/Database.php [hunk 5]
```diff
@@ -104,6 +104,15 @@ public function testDatabaseSettings($server, $database, $login, $password, $pre
...
+                $errors[] = $this->translator->trans('You must be granted the privilege to select data in the tables of database "%s". Ask your hosting provider to enable it.', ['%database%' => $database], 'Install');
+                if ($select_error != false) {
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Install/Database.php]: I think you can check `$select_error` with `!==` here, since `Db::checkSelectPrivilege` returns a boolean or a string.
```suggestion
                if ($select_error !== false) {
```

**Review by matthieu-rolland — COMMENTED** [review]
Looks good to me, two small feedbacks 👍   (I don't block the PR though)

File: src/PrestaShopBundle/Install/Database.php (hunk 4 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Install/Database.php]: :heavy_check_mark:

File: src/PrestaShopBundle/Install/Database.php (hunk 5 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Install/Database.php]: :heavy_check_mark:

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm !

**Review by Junebyun — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

It works, with your PR the check is made before installation : 

pr19856

QA :heavy_check_mark:

**Comment by Progi1984** [comment]
Thanks @Robin-Fischer-PS
