### PR TITLE
An exception is displayed when we create a new store

### LINKED ISSUE #33385: An exception is displayed when we create a new store
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In 'Shop parameters > contact > stores' page, when we create a new store an exception is displayed

-> Mode debug on
Capture d’écran de 2023-07-26 10-04-24

-> Mode debug off
Capture d’écran de 2023-07-26 10-29-40

### Expected behavior

A validation message should be displayed when we create a new store

### Steps to reproduce

1- Go to 'Shop parameters > contact > stores' page
2- Fill all the inputs
3- Save and see the error

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | A remnant of a deprecated alias that was removed
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see #33385
| Fixed ticket?     | Fixes #33385
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Comment by M0rgan01** [comment]
Tests: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5666749663

**Review by kpodemski — DISMISSED** [review]

File: controllers/admin/AdminStoresController.php [hunk 1]
```diff
@@ -425,7 +426,7 @@ protected function postImage($id)
         * In case of .jpg images, the actual format inside is decided by ImageManager.
         */
         $sfContainer = SymfonyContainer::getInstance();
-        if ($sfContainer->get('prestashop.core.admin.feature_flag.repository')->isEnabled(FeatureFlagSettings::FEATURE_FLAG_MULTIPLE_IMAGE_FORMAT)) {
+        if ($sfContainer->get(FeatureFlagRepository::class)->isEnabled(FeatureFlagSettings::FEATURE_FLAG_MULTIPLE_IMAGE_FORMAT)) {
```
Comment (boherm) [inline controllers/admin/AdminStoresController.php]: You must use `FeatureFlagStateCheckerInterface` instead of the repository.
```suggestion
        if ($sfContainer->get(FeatureFlagStateCheckerInterface::class)->isEnabled(FeatureFlagSettings::FEATURE_FLAG_MULTIPLE_IMAGE_FORMAT)) {
```

**Review by boherm — CHANGES_REQUESTED** [review]

File: controllers/admin/AdminStoresController.php (hunk 1 above)
Comment (M0rgan01) [reply controllers/admin/AdminStoresController.php]: thanks @boherm :)

**Review by boherm — APPROVED** [review]
LGTM, thanks @M0rgan01!

**Review by kpodemski — APPROVED** [review]

**Review by sallemiines — APPROVED** [review]
Hello @M0rgan01 
Thanx for the PR 
[Automated tests](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5679348036) : OK 

LGTM QA :heavy_check_mark: 

https://github.com/PrestaShop/PrestaShop/assets/31663369/6a172e39-7df3-4c19-864c-a909a1bbb105



Thank you ! :rocket:

**Comment by nicosomb** [comment]
Thank you @M0rgan01 !
