### PR TITLE
Fix: Multishop: Deleting and recreating a combination removes the shared reference (new Product Page V2)

### LINKED ISSUE #37840: Multishop: Deleting and recreating a combination removes the shared reference (new Product Page V2)
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In a multishop setup with two shops (e.g., **B2C** and **B2B**), using the new product page (Product Page v2), if a product has an active combination for both shops, the following behavior occurs:

The product has an active combination with:
**Size**: S
**Reference**: REFERENCE

If I delete this combination from the **B2B** shop and then recreate it, the system reassigns the same combination (keeping the same ID). This behavior is correct and useful.

Issue: During this process, the system removes the value of the **Reference** (reference) field of the combination. Since the **Reference** field is unique across all shops, it should remain unchanged even after deleting and recreating the combination.

In my opinion, the system should preserve the reference value to avoid data loss and ensure proper management of combinations in a multishop context.

https://github.com/user-attachments/assets/fa953118-81a5-4c49-b6b3-38bbe4b77241

### Expected behavior

The system should retain the value of the **Reference** (REFERENCE) field.

### Steps to reproduce

1. Set up a multishop configuration with at least two shops (e.g., B2C and B2B).
2. Create a product with an active combination shared across both shops:
**Size**: S
**Reference**: REFERENCE
3. Delete the combination from the B2B shop.
4. Recreate the same combination in the B2B shop.

### PrestaShop version(s) where the bug happened

8.2.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@codencode

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | see: https://github.com/PrestaShop/PrestaShop/issues/37840 - Note: The issue also occurs on the 9.0.x branch, so I performed the rebase by moving the PR to 9.0.x because PRs are no longer being merged on version 8.2.x.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |1. Set up a multishop configuration with at least two shops (e.g., B2C and B2B).<br/>2. Create a product with an active combination shared across both shops:<br/>Size: S<br/>Reference: REFERENCE<br/>3. Delete the combination from the B2B shop.<br/>4. Recreate the same combination in the B2B shop. 5. Check that the combination has **REFERENCE** as its reference.<br/> For more info see: https://github.com/PrestaShop/PrestaShop/issues/37840
| UI Tests          | 🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/18774894264
| Fixed issue or discussion?     | Fixes #37840
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by Codencode** [comment]
Perhaps we could consider retrieving `$productId` and `$combinationReference` with a single method to execute only one query instead of two?

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php [hunk 1]
```diff
@@ -234,6 +234,31 @@ public function getProductId(CombinationId $combinationId): ProductId
...
+        ;
+
+        $result = $qb->execute()->fetchAssociative();
+        $reference = '';
+
+        if (!empty($result['reference'])) {
+            $reference = $result['reference'];
+        }
+
+        return $reference;
```
Comment (kpodemski) [inline src/Adapter/Product/Combination/Repository/CombinationRepository.php]:
```suggestion
        $result = $qb->execute()->fetchAssociative();

        return $result['reference'] ?? '';
```

I think this will be enough :)

**Comment by Codencode** [comment]
ping @PrestaShop/committers

**Comment by Codencode** [comment]
I performed the rebase onto the 9.0.x branch.

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by Codencode** [comment]
ping @PrestaShop/qa-functional

**Comment by Robin-Fischer-PS** [comment]
Hi @Codencode :)

Thanks for the ping! It should be tested soon (we currently have a lot of PR in QA, so there is a bit of delay). But it will be done for the 9.0.2 no matter what 😄

**Comment by Codencode** [comment]
Hi @Robin-Fischer-PS 
Perfect and thank you very much for the feedback!

**Comment by paulnoelcholot** [comment]
Hello @Codencode,

I tested your PR and it's good for me! :tada: 

Thanks!

https://github.com/user-attachments/assets/b1f7f811-2ec3-4ca4-aebb-58d0d95d78e1

**Review by paulnoelcholot — APPROVED** [review]
