### PR TITLE
Set cover on table image when add image on product

### LINKED ISSUE #31478: PPV2 - The images of products V2 are not displayed in stocks page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 The images of products P2 are not displayed in stocks page 

**8.1.0_beta : NOK With Product V2** :x: 

image

image

develop : NOK :x: 

image

**8.1.0_beta : OK With Product V1** :heavy_check_mark: 

image

**8.0.1 : OK** :heavy_check_mark: 

image

Indeed, it's a regression on 8.0.1_beta!

### Expected behavior

The images are well displayed on stock page

### Steps to reproduce

1. Use 8.1.0_beta
2. Go to 
3. Go to BO > CONFIGURE > Advanced parameters > New & Experimental Features > Enable `New product page`
4. Go to BO > SELL > Catalog > Products > Create any product type (eg:With combinations) with **Product V2**
5. In the Description field > Add an image 
6. Click on Save
7. Go to BO > SELL > Catalog > Stock 
8. See error > the images related to product type V2 are not displayed

### PrestaShop version(s) where the bug happened

8.1.0_beta

### PHP version(s) where the bug happened

7.3, 8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Set cover on table image when add image on product
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31478 
| Fixed ticket?     | Fixes #31478 
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

File: src/Adapter/Product/Image/Repository/ProductImageRepository.php [hunk 1]
```diff
@@ -589,6 +589,15 @@ public function updateMissingCovers(ProductId $productId): void
                 ->setParameter('shopId', (int) $image['id_shop'])
                 ->execute()
             ;
+
+            $this->connection->createQueryBuilder()
+                ->update($this->dbPrefix . 'image')
+                ->set($this->dbPrefix . 'image' . '.cover', ':cover')
```
Comment (zuk3975) [inline src/Adapter/Product/Image/Repository/ProductImageRepository.php]:
```suggestion
                ->set($this->dbPrefix . 'image.cover', ':cover')
```
can you aslo fix it above in line 584 and 588?

File: src/Adapter/Product/Image/Repository/ProductImageRepository.php [hunk 2]
```diff
@@ -589,6 +589,15 @@ public function updateMissingCovers(ProductId $productId): void
...
+                ->setParameter('cover', $newValue)
+                ->andWhere($this->dbPrefix . 'image' . '.id_image = :imageId')
```
Comment (zuk3975) [inline src/Adapter/Product/Image/Repository/ProductImageRepository.php]: same here

File: src/Adapter/Product/Image/Repository/ProductImageRepository.php (hunk 1 above)
Comment (zuk3975) [reply src/Adapter/Product/Image/Repository/ProductImageRepository.php]: It should probably even work like this
```suggestion
                ->set('cover', ':cover')
```
because there ain't no alias and no table joins. Could you check and implement it if it works?

**Review by Hlavtox — DISMISSED** [review]

**Review by 0x346e3730 — DISMISSED** [review]

**Review by boherm — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @mflasquin ,
I have checked your PR the issue is  well fixed ,
Automated tests --> OK

[Untitled_ Apr 20, 2023 2_44 PM.webm](https://user-images.githubusercontent.com/115152460/233379499-750b4c4a-f4d5-4b05-b4c7-12a4d756970b.webm)


It's QA approved :heavy_check_mark:
Thank you for you PR :rocket:

**Comment by nicosomb** [comment]
Thank you @mflasquin !
