### PR TITLE
Save address choice on click

### LINKED ISSUE #36062: Loss of delivery address selection when choosing billing address
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the purchase funnel, if there is more than one address and the customer chooses the address that is not selected by default, the choice is lost if the customer clicks on the link to enter a different address for the billing process.

Example on a default PrestaShop environment :
1. The client has two delivery addresses and one is selected by default:
image

2. The client chooses the other delivery address (and not the one by default):
image

3. The client then clicks on the linK to add another address ('L'adresse de facturation ') for the billing process:
Then the address by default is once again selected and not the one chosen in the previous step.
image

### Expected behavior

The delivery address chosen by the client must be still selected when he wants to enter a different billing address

### Steps to reproduce

    • Enter two delivery addresses or more
    • Put an item in the cart and begin the order process
    • Go to the address part of the purchase funnel
    • Selected another delivery address than the one selected by default
    • Click on the link to enter a different address for the billing process
You’ll see that the delivery address is not the one previously selected.

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@202ecommerce

### PR DESCRIPTION
**Pull request by Matt75**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x 
| Description?      | Loss of delivery address selection when choosing billing address #36062
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See issue
| UI Tests          | https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/16725765788
| Fixed issue or discussion?     | Fixes #36062
| Related PRs       | No
| Sponsor company   | PrestaShop

### CODE REVIEW

File: themes/_core/js/checkout-address.js [hunk 1]
```diff
@@ -26,9 +26,25 @@ import $ from 'jquery';
 import prestashop from 'prestashop';
 import {psGetRequestParameter} from './common';
 
+const {addressForm} = prestashop.selectors.checkout;
 const editAddress = psGetRequestParameter('editAddress');
 const useSameAddress = psGetRequestParameter('use_same_address');
 
+export function updateAddressForm() {
```
Comment (gaelreyrol) [inline themes/_core/js/checkout-address.js]:
```suggestion
function updateAddressForm() {
```

File: themes/_core/js/checkout-address.js [hunk 2]
```diff
@@ -26,9 +26,25 @@ import $ from 'jquery';
...
+  const $addressForm = $(`${addressForm} form`);
```
Comment (gaelreyrol) [inline themes/_core/js/checkout-address.js:34]: We should have a clear and explicit identifier to prevent regressions.

**Review by matks — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @Matt75,

Thanks for your PR, i tested it and it's OK for me 
I'm waiting ui tests to approve the PR
Capture d’écran 2025-08-04 à 16 34 43

Thanks ^^

**Review by SiraDIOP — APPROVED** [review]
