### PR TITLE
BO - Multistore : Fixed link "Add new group"

### LINKED ISSUE #37690: Multistore - Exception thrown when creating a group in specific shop
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Exception is thrown when I try to create a customer group in a specific store.

Image

### Expected behavior

No exception

### Steps to reproduce

1. Go to Shop parameters > General > Enable Multistore
2. Go to Advanced parameters > Multistore > Create a second store
3. In shop 1 context > Go to Shop Parameters > Customer > Group tab > Create a new customer group ✅ 
4. In shop 2 context > Create a new customer group :x: Exception thrown

### PrestaShop version(s) where the bug happened

9.0.0 (not reproduced in 8.2.0)

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | BO - Multistore : Fixed link "Add new group"
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | :arrow_down: 
| UI Tests          |  https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19537543912
| Fixed issue or discussion?     | Fixes #37690
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

## How to test?
1. Go to Shop parameters > General > Enable Multistore
2. Go to Advanced parameters > Multistore > Create a second store
3. Set the context to "Shop 1"
4. Go to Shop Parameters > Customer > Group tab > Create a new customer group ✅
5. On the same page, change the context to "Shop 2"
6. Click on the button "Add new group" on the header button list
7. **BEFORE** : Create a new customer group :x: Exception thrown
8. **AFTER** : The form is well opened

### CODE REVIEW

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

**Comment by Codencode** [comment]
Hello @Progi1984,

I've tested this PR, and it works. However, the issue also occurs with other operations, such as edit/delete and saving the "Default groups options" form.

From what I understand, this problem generally affects all pages that haven't been fully migrated to Symfony controllers yet. In fact, yesterday I reported this issue: https://github.com/PrestaShop/PrestaShop/issues/40059, which is the same but relates to the International > Locations > Countries page.

For this problem, I created this PR: https://github.com/PrestaShop/PrestaShop/pull/40066, which should fix the issue in a general way, and therefore also address the problem present here.

Of course, given your experience, I'd like to hear your opinion on this.

Thank you very much!

File: controllers/admin/AdminGroupsController.php [hunk 1]
```diff
@@ -163,7 +163,7 @@ public function initPageHeaderToolbar()
     {
         if (Group::isFeatureActive() && empty($this->display)) {
             $this->page_header_toolbar_btn['new_group'] = [
-                'href' => self::$currentIndex . '&addgroup&token=' . $this->token,
+                'href' => $this->context->link->getAdminLink('AdminGroups') . '&addgroup&token=' . $this->token,
```
Comment (Hlavtox) [inline controllers/admin/AdminGroupsController.php]:
```suggestion
                'href' => $this->context->link->getAdminLink('AdminGroups', true, [], ['addgroup' => 1]),
```

It's better to use parameters, cleaner and allows us to properly migrate that link to a symfony one, automatically, if that page is migrated.

**Comment by Hlavtox** [comment]
@Progi1984 Small comment, I will approve right away. :-)

File: controllers/admin/AdminGroupsController.php (hunk 1 above)
Comment (Progi1984) [reply controllers/admin/AdminGroupsController.php]: Fixed @Hlavtox :)

**Comment by Progi1984** [comment]
@Codencode Hi, I see your PR #40066. I prefer mine. Why ?

Because the fix is due to legacy code. I prefer having a fix in legacy code, because when we remove it, legacy code will be removed. And I prefer don't add a patch code in Symfony side due to legacy code. 

It's my idea :)

**Review by Hlavtox — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

**Comment by Codencode** [comment]
@Progi1984 Hi, you are absolutely right, your idea makes sense!
However, I believe the other issues, namely editing/deleting and saving the "Default groups" form, remain.
Do you have any ideas about that?
And regarding my PR (https://github.com/PrestaShop/PrestaShop/pull/40066), do you think it doesn't make sense?
Do you have any suggestions?
Thank you very much for your feedback!

**Review by nicohery — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Progi1984,

I tested your PR and it's good for me! :tada: 

Thanks!

https://github.com/user-attachments/assets/bd1cdb9e-b9ee-48b4-8852-40f1b92b20c9

**Review by paulnoelcholot — APPROVED** [review]

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by Touxten** [comment]
Thank you you @Progi1984 && @paulnoelcholot

**Comment by Hlavtox** [comment]
@Codencode I think we should fix both.

A) Make all links properly like @Progi1984 did here.
B) But also make sure that links with currentIndex work.

**Comment by Codencode** [comment]
> @Codencode I think we should fix both.
> 
> A) Make all links properly like @Progi1984 did here. B) But also make sure that links with currentIndex work.

@Hlavtox 
Yes, of course. However, in my opinion, to solve the problem, it's not enough to act on the "creation" of the links; something like this PR of mine is needed: https://github.com/PrestaShop/PrestaShop/pull/40066
Then again, I could be wrong; maybe I'm missing something. That's precisely why I'm asking you more experienced folks :-)
