### PR TITLE
Get specific prices: let mysql optimize the query.

### LINKED ISSUE #26772: Get specific prices: let mysql optimize the query.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This is not really a bug. It's a performance enhancement. It is a valuable improvement in my environment, and I think it would improve on most other installations too, but to prove it would bee quite difficult...

Of all queries involving the table ps_specific_price, 
```
SELECT SQL_NO_CACHE COUNT(*) FROM (SELECT DISTINCT `id_product` FROM `ps_specific_price` WHERE `id_product` != 0 GROUP BY id_product ) AS counted LIMIT 1
```
in /classes/SpecificPrice.php:287 is consistently the one that is the slowest, between 100ms and more than a second.

The bug consists in the fact that this query is used to optimize a query that consistently takes less than 1ms. That is : spend 100 ms to get an improvement below the 1 ms level.

### Expected behavior

Do not try to optimize the query that already is faster than 1ms. It is useless to fine tune a query code for optimization. The datebase engine must do this work: based on the information about index statistics choose the best index available and optimize the query plan.

### Steps to reproduce

Prerequisites: 
use an environment with many specific prices. My setup:
- 25 shops
- 50k products
- 4M specific prices

1. Enable Profiling mode (https://doc.prestashop.com/pages/viewpage.action?pageId=51184700)
    - On your server, open the /config/defines.inc.php file.
    - Find this line (around line 43): define('PS_DEBUG_PROFILING', false);
    - In this line, change "false" to "true".
2. Display a product page
3. In the profiling output examine all the queries containing the specific_price table
   - Most queries are fast
   - The query cited above is manyfold slower.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
Optimizing a sub-millisecond query in PHP using several additional queries (that take longer) is inefficient.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove inefficient optimization (it actually multiplies the query time of the affected queries by about 100 x)
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26772
| How to test?      | Analyze and compare output in profiling mode before and after the change
| Possible impacts? | The change is self contained and should not have any side effect.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26773)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Ohlala @lmeyer1 you submitted a PR very hard to review 😭 

Honestly: the stuff written in this class by developers long gone is undocumented, untested, quite unreadable and we have no information what the expected behavior was. Also this could be linked to other parts of code, same we have no idea.

How could we know for sure your change breaks nothing in this part of the code so fragile and so vulnerable?

**Comment by lmeyer1** [comment]
@matks
The tests didn't pass, so visibly something broke. I didn't yet look into it to know what the reason is.
I analysed the code a bit, so I will add explanations.
It looks as if I had to work on another project next week though...
@jocel1 wrote this code in 2015... Isn't he still there? But of course, it's too long ago to remember...

**Comment by jocel1** [comment]
Hi!

Well the 
```SELECT COUNT(*) FROM (SELECT DISTINCT `id_product` FROM `ps_specific_price` WHERE `id_product` != 0 GROUP BY id_product ) AS counted LIMIT 1```
query is definitely not part of my original code, and is a really bad idea...
What I recommend now is the following code:
```
        if (!array_key_exists($key_cache, self::$_filterOutCache)) {
            $query = 'SELECT 1 FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
            $has_product_specific_price = Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue($query);
            if ($has_product_specific_price == 0) {
                self::$_no_specific_values[$field_name] = true;

                return $query_extra;
            }
            $query_count = 'EXPLAIN SELECT COUNT(DISTINCT `' . $name . '`) FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
            $specific_count_result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow($query_count);
            $specific_count = $specific_count_result['rows'];

            if ($specific_count < $threshold) {
                $query = 'SELECT DISTINCT `' . $name . '` FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
                $tmp_specific_list = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($query);
                foreach ($tmp_specific_list as $key => $value) {
                    $specific_list[] = $value[$field_name];
                }
            }
            self::$_filterOutCache[$key_cache] = $specific_list;
        } else {
            $specific_list = self::$_filterOutCache[$key_cache];
        }
```

Note the whole purpose of the original modification is to make the query easily cacheable by the query cache, or something like ProxySQL, because in the case of high concurrency workload, it changes everything!

BR,

**Comment by lmeyer1** [comment]
Thanks @jocel1 !
I adopted your recommendation. This will be easy to review. 
And yes, my change also deoptimized cache, I didn't think about that point.

File: classes/SpecificPrice.php [hunk 1]
```diff
@@ -283,17 +283,21 @@ protected static function filterOutField($field_name, $field_value, $threshold =
         $key_cache = __FUNCTION__ . '-' . $field_name . '-' . $threshold;
         $specific_list = [];
         if (!array_key_exists($key_cache, self::$_filterOutCache)) {
-            $query_count = 'SELECT COUNT(*) FROM (SELECT DISTINCT `' . $name . '` FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0 GROUP BY id_product ) AS counted';
-            $specific_count = Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue($query_count);
-            if ($specific_count == 0) {
+            $query = 'SELECT 1 FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
```
Comment (Progi1984) [inline classes/SpecificPrice.php:287]:
```suggestion
            // Check if a specific price with this key exists
            $query = 'SELECT 1 FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
```

File: classes/SpecificPrice.php [hunk 2]
```diff
@@ -283,17 +283,21 @@ protected static function filterOutField($field_name, $field_value, $threshold =
...
+            $has_product_specific_price = Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue($query);
+            if ($has_product_specific_price == 0) {
                 self::$_no_specific_values[$field_name] = true;
 
                 return $query_extra;
             }
+            $query_count = 'EXPLAIN SELECT COUNT(DISTINCT `' . $name . '`) FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
```
Comment (Progi1984) [inline classes/SpecificPrice.php:295]:
```suggestion
            // Fetch the count of specific price
            $query_count = 'EXPLAIN SELECT COUNT(DISTINCT `' . $name . '`) FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
```

Why use en `EXPLAIN` ?

**Review by Progi1984 — COMMENTED** [review]
@lmeyer1 Thank you for your contribution. I have brought you two comments to your PR.

File: classes/SpecificPrice.php (hunk 2 above)
Comment (lmeyer1) [reply classes/SpecificPrice.php:295]: Because explain can be 100x faster than count(*). It's only approximative, but we don't care about the exact number.
The difference in time is very noticeable when we have millions of specific prices.

File: classes/SpecificPrice.php [hunk 3]
```diff
@@ -283,17 +283,23 @@ protected static function filterOutField($field_name, $field_value, $threshold =
...
+            // Fetch the approximate count of specific price. explain can be 100x faster than count.
+            $query_count = 'EXPLAIN SELECT COUNT(DISTINCT `' . $name . '`) FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
+            $specific_count_result = Db::getInstance(_PS_USE_SQL_SLAVE_)->getRow($query_count);
+            $specific_count = $specific_count_result['rows'];
+
             if ($specific_count < $threshold) {
                 $query = 'SELECT DISTINCT `' . $name . '` FROM `' . _DB_PREFIX_ . 'specific_price` WHERE `' . $name . '` != 0';
                 $tmp_specific_list = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($query);
-                foreach ($tmp_specific_list as $value) {
+                foreach ($tmp_specific_list as $key => $value) {
```
Comment (atomiix) [inline classes/SpecificPrice.php]: I guess this change is useless?
```suggestion
                foreach ($tmp_specific_list as $value) {
```

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by atomiix** [comment]
@PrestaShop/qa-team I guess this one can be validated by a dev?

**Comment by khouloudbelguith** [comment]
> @PrestaShop/qa-team I guess this one can be validated by a dev?

Hi @atomiix,

As discussed with @sarahdib & @Robin-Fischer-PS, this PR should be tested by @PrestaShop/qa-team at first to be sure there are no regressions and then a dev will validate it also.

Thank you!

**Comment by marwachelly** [comment]
Hello,

I tested the PR and I didn't detect any related regression. 
@atomiix Could you please check the perfermance section.

Many thanks,

**Comment by saulaski** [comment]
@marwachelly I take in charge the optimization validation.

**Comment by marwachelly** [comment]
> @marwachelly I take in charge the optimization validation.

Many thanks @saulaski

**Comment by saulaski** [comment]
@lmeyer1 @jocel1 Thank you both for this successful optimization.

The original slow query has been reproduced on my local environment: 
- 4 millions specific prices
- execution time around 1 minute

**PR optimization speeds up to 1 millisecond only, a great performance boost.**

Please note that this optimization executes 2 queries instead of 1, then it is less beneficial to very few specific prices in database. Thankfully this performance degredation is neglectable: 0.3 ms tested with 2 prices.

Here the details of the performance testing:
https://docs.google.com/spreadsheets/d/1u_KZV7kvGcs4Ow4FKuVmBrDhVVJnZP6Zm15qgp5Kc9Q/edit?usp=sharing

**Review by saulaski — APPROVED** [review]

**Comment by matks** [comment]
Thank you @saulaski and @marwachelly for the QA validation and thank you @lmeyer1 for the contribution

**Review by matks — APPROVED** [review]

**Comment by sebweb-agency** [comment]
I adopted your recommendation. Thanks ;-)
