### PR TITLE
Move notifications divs to the vuejs app

### LINKED ISSUE #27840: BO- Stock- Wrong position of information message in multistore context
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

 Wrong position of information messages in multistore context 
image

### Expected behavior

 The information message is in the header but it should be below the tabs
image

### Steps to reproduce

1. Activate multistore
2. Create a new shop group, do not set a color
3. Create a new shop, do not set a color
4. Configure new shop url
5. Go to Catalog> stock
6. the information message is in the header but it should be below the tabs

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | As the stock page is a vuejs page, the contextual notification was displayed outside of the vuejs page. This PR aims to fix that by dynamically moving the element into the vuejs page.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27840
| How to test?      | Please see #27840 after compiling assets
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27850)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue [hunk 1]
```diff
@@ -60,6 +65,9 @@
       const toolbarButtons = getOldHeaderToolbarButtons();
       toolbarButtons.insertAfter($(this.$el).find('.title-row > .title'));
 
+      const notifications = getNotificationsElements();
+      notifications.insertAfter($(this.$el));
```
Comment (saulaski) [inline admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue]: Wrapping the HTML element `this.$el` in jQuery object wasn't required here

**Review by saulaski — APPROVED** [review]

File: admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue [hunk 2]
```diff
@@ -50,6 +51,10 @@
       .find('.toolbar-icons');
   }
 
+  function getNotificationsElements() {
+    return $(`#ajax_confirmation, #${ComponentsMap.contextualNotification.messageBoxId}`);
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue]: Moove the `#ajax_confirmation` selector to `ComponentsMap`, at the root!

File: admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue (hunk 1 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue]: If it's right and if this is possible, take care of the line 66, maybe it's not required too, I know it's not the PR scope, but if we can improve it... 

It's not the case, then just ignore my comment :)

Comment (saulaski) [reply admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue]: @NeOMakinG I'm affraid jQuery wrapper is required at line 66, since child elements are returned.
Alternative: declare a variable to optimize duplicated processing
```
      const $vueElement = $(this.$el);
      const toolbarButtons = getOldHeaderToolbarButtons();
      toolbarButtons.insertAfter($vueElement.find('.title-row > .title'));
      const notifications = getNotificationsElements();
      notifications.insertAfter($vueElement);
```

**Review by saulaski — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue (hunk 1 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/app/pages/stock/components/header/stock-header.vue]: I had a doubt too, this is why I said `If this is possible`

Your implementation could be the solution yeah

**Review by saulaski — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/components/components-map.ts [hunk 3]
```diff
@@ -102,4 +102,5 @@ export default {
     messageBoxId: 'content-message-box',
     notificationClass: 'contextual-notification',
   },
+  ajaxConfirmation: '#ajax_confirmation',
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/components-map.ts:105]: Warning, this makes me think about a PR from @Progi1984 which redefined a more "identified" zone for notifications (in a better way IMHO because ajax_confirmation div seemed a bit lost from legacy code)

See this PR and discuss with @Progi1984 maybe https://github.com/PrestaShop/PrestaShop/pull/27347

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/components/components-map.ts:105]: Seen with @atomiix & @NeOMakinG : it's good.

**Review by Progi1984 — DISMISSED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello,

The information message is displayed in the wrong position first. It is displayed in the header then it moves below the tabs. 
https://watch.screencastify.com/v/52lUtw7ALQqRnKc55AIT

Could you please check?

Thanks,

**Review by saulaski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by marwachelly — APPROVED** [review]
Hello,
Issue is fixed. PR is QA approved.
https://watch.screencastify.com/v/2GZXscOGVrPy4LUPGSaR

Thanks,

**Comment by atomiix** [comment]
Thanks @marwachelly
