### PR TITLE
Fix tag relation with product in Tag form

### LINKED ISSUE #28295: BO - An exception is displayed when editing a tag in the page product V2
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed when editing a tag in the page product V2

https://user-images.githubusercontent.com/89604350/164192885-ccb86aa3-138c-4885-8ed2-9a4b5fca10f0.mp4

Thanks to @HanaRebaiQA for finding the bug.

### Expected behavior

_No response_

### Steps to reproduce

1. Create a product V2
2. In the SEO tab > add a new tag with a specified language (eg:english)
3. Enable this product and save
4. Go to BO > Shop parameters > Search > Tags page
5. Edit the last tag created
6. Change in another languages (eg: Frensh) and Save
7. Come back to the product
8. Click on Save
9. See error >>
 **If PHP is 7.4**
image
**If PHP 8.0**
image

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4/8.0

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #28296: Tags - The tag is not displayed after being updated when the product is disabled
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The tag is not diplayed after being updated when the product is disabled

https://user-images.githubusercontent.com/89604350/164194691-8e0d9d9c-763a-4ea6-9b85-5d4aa8823c6c.mp4

Thanks to @HanaRebaiQA.

### Expected behavior

_No response_

### Steps to reproduce

1. Create a product V2
2. In the SEO tab > add a new tag with a specified language (eg: English)
3. Disable this product and save
4. Go to BO > Shop parameters > Search > Tags page
5. Edit the last tag created
6. Change in another languages (eg: Frensh) and Save
7. Come back to the product
8. Check the tag with the updated language
9. See error >> the tag is not displayed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | refer to https://github.com/PrestaShop/PrestaShop/issues/28296 And #28295.It used to collect only active products for shop in Tags form, so if product was disabled and had a tag, then after saving tag form the relation was gone. Now the product is shown in form even if its disabled, that way the form works as expected and relation is not deleted during edit.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Resolves https://github.com/PrestaShop/PrestaShop/issues/28296 Resolves #28295
| Related PRs       | 
| How to test?      | refer to https://github.com/PrestaShop/PrestaShop/issues/28296 and #28295
| Possible impacts? |  Im not 100% sure what was the intention to not show disabled products, but I still left the same logic for the left side of the product-tag relation table in Tag edit form, just changed some logic for the right side. So if the product is disabled, but its not related to the editable tag, then it still shouldn't be shown in right table side as before, however if it is related and disabled, it now should be shown in the right side of the relation table (previously it wasn't shown).

### CODE REVIEW

File: classes/Tag.php [hunk 1]
```diff
@@ -345,8 +348,8 @@ private static function deleteProductTags($idProduct, int $langId = null)
             WHERE id_product=' . (int) $idProduct
         ;
         if ($langId) {
-            $removeWhere .= ' AND id_lang =' . (int) $langId;
-            $selectTagsToRemove .= ' AND id_lang =' . (int) $langId;
+            $removeWhere .= ' AND id_lang =' . $langId;
+            $selectTagsToRemove .= ' AND id_lang =' . $langId;
```
Comment (matks) [inline classes/Tag.php:352]: Why remove the type casting? It is a protection against SQL injection

**Review by yanmakouf — APPROVED** [review]

File: classes/Tag.php (hunk 1 above)
Comment (PululuK) [reply classes/Tag.php:352]: Hi @matks, see the `$langId` declaration type in function signature (`int`|`null`).

Comment (zuk3975) [reply classes/Tag.php:352]: Yep it is already typed.
Screenshot from 2022-09-05 10-46-12

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

**Review by matks — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @zuk3975 

- Issue solved
- Test automatics are **OK**
See the attached screen record



https://user-images.githubusercontent.com/31663369/195557270-1dc8e2ac-b972-4860-97bf-def4ededb3be.mp4

THank you ! :rocket:

**Comment by kpodemski** [comment]
Thank you @zuk3975
