### PR TITLE
Footer from next invoice shown on invoice when exporting multiple invoices (i.e. invoices by date range)

### LINKED ISSUE #26067: Footer from next invoice shown on invoice when exporting multiple invoices (i.e. invoices by date range)
#### Describe the bug

When exporting multiple invoices (i.e. invoices by date range), the footer of the following invoice is shown on the current invoice erroneously. This meant that in a multi-store environment, the wrong store details could be output on the invoice footer, which can create a compliance issue, especially if different tax information should be displayed. The issue resolves around the use of TCPDF, where the footer needs to be output after AddPage, otherwise the last page of a page group will end up having the footer of the next page group.

#### Expected behaviour

The footer should be output using the correct store details.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. In a multi-store environment -- set up multiple stores with different data, such that the footers on invoices would differ depending on which store items were ordered from
2. Place and invoice a mixture of orders - switch between stores when placing orders
3. Export orders using the invoices by date range functionality
4. Where invoices switch between stores, the footer belonging to the store of the next invoice will be shown on the current invoice

I will submit a pull request with a fix.

#### Additional information

* PrestaShop version: 1.7.7.8 (although also in previous versions)
* PHP version: 7.3.29

### PR DESCRIPTION
**Pull request by AshleyButcher**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When exporting multiple invoices (i.e. invoices by date range), the footer of the following invoice is shown on the current invoice erroneously. This meant that in a multi-store environment, the wrong store details could be output on the invoice footer, which can create a compliance issue, especially if different tax information should be displayed. The issue resolves around the use of TCPDF, where the footer needs to be output after AddPage, otherwise the last page of a page group will end up having the footer of the next page group.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26067
| How to test?      | 1. In a multi-store environment -- set up multiple stores with different data, such that the footers on invoices would differ depending on which store items were ordered from 2. Place and invoice a mixture of orders - switch between stores when placing orders 3. Export orders using the invoices by date range functionality 4. Where invoices switch between stores, the footer should always be relative to the store the invoice is from
| Possible impacts? | Individual invoicing (no issues seen in testing so far though), any other PDF generation

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26068)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Woah 😄  this looks crazy. I'm diving in... looks like it's a weird TCPDF situation (or are we using TCPDF in a strange way)

**Review by matks — DISMISSED** [review]
I verified, the change is valid although it seems counter-intuitive

File: classes/pdf/PDF.php [hunk 1]
```diff
@@ -147,10 +147,13 @@ public function render($display = true)
             $template->assignHookData($object);
 
             $this->pdf_renderer->createHeader($template->getHeader());
-            $this->pdf_renderer->createFooter($template->getFooter());
             $this->pdf_renderer->createPagination($template->getPagination());
             $this->pdf_renderer->createContent($template->getContent());
             $this->pdf_renderer->writePage();
+	    // The footer must be added after adding the page, or TCPDF will
+	    // add the footer for the next page from on the last page of this
+	    // page group, which could mean the wrong store info is rendered.
```
Comment (Progi1984) [inline classes/pdf/PDF.php]:
```suggestion
            // The footer must be added after adding the page, or TCPDF will
            // add the footer for the next page from on the last page of this
            // page group, which could mean the wrong store info is rendered.
```

**Review by Progi1984 — COMMENTED** [review]
@Ashley-Butcher Thank you for your contribution. I added a comment for fixing PHPCSFixer. Please fix it and I will approve your PR.

**Comment by AshleyButcher** [comment]
Is there a problem with the automated unit tests / sanity checks? I see them all as canceled. :(

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Closed & Reopened the PR for restarting the CI.

**Review by tegbessou — APPROVED** [review]
Thank you for your PR! IMO is good

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Ashley-Butcher,

It is ok :heavy_check_mark: 
https://watch.screencastify.com/v/2oPR25eZiYKNdYqXSesX

Thanks!

**Comment by Progi1984** [comment]
Thanks @Ashley-Butcher & @khouloudbelguith
