### PR TITLE
Get proper cover for product in cart and cart modal

### LINKED ISSUE #21775: FO - Product with combinations - Incorrect image displayed
#### Describe the bug

In the FO, when we add a product with combinations to the cart, the cover image is displayed instead of the Product's image selected.
image
This issue occurs in 

- ~~Product successfully added to your shopping cart Pop up~~ => Fixed
- ~~Shopping cart page~~ => Fixed https://github.com/PrestaShop/PrestaShop/pull/24248
- Checkout page ( cart summary details)
- Order final summary
- Order confirmation page

#### Steps to Reproduce

1. Go to FO
2. Select first product "Hummingbird Printed T-Shirt"
3. Add the Combination  Size-S, Color-Wite
4. Go to cart (or cart summary in checkout page, order final summary or order confirmation page)
5. See an error

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Get proper cover for product with variant
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21775 
| How to test?  | Add variants with different images to cart, check for proper covers in display and in cart
| Sponsor company | impSolutions

I don't like this fix tbh, this will create n+1 query for products with cart, the problem is that with changes to covers introduced some time ago I don't see any other way to split getting products with **real** cover based on attribute selection, with those where we need to get products on listings and force **selected cover from BO**

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21782)

### CODE REVIEW

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 1]
```diff
@@ -678,4 +688,19 @@ protected function getAttributesArrayFromString($attributes)
...
     }
+
+    /**
+     * Gets proper cover for a specific variant of product
+     *
+     * @param int $idProductAttribute
+     *
+     * @return int Cover image id
+     */
+    private function getCoverImageForCombination($idProductAttribute)
```
Comment (Progi1984) [inline src/Adapter/Presenter/Cart/CartPresenter.php]:
```suggestion
    private function getCoverImageForCombination(int $idProductAttribute): int
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback

**Comment by kpodemski** [comment]
Thanks @Progi1984 

I'll wait for @matks and @jolelievre , I think that we need to discuss this topic related to covers further and produce some valid solution once for all

**Comment by matks** [comment]
Hi everybody, as I said in Slack I think one reason why we keep reworking this topic is that it's not clear what should be done and it's even not clear what exists now.

Would it be possible first to find names to accurately describe the different kind of images we can upload/assign to a product, then describe the different kind of images we can display on FO ; and highlight the possible differences of behavior between a simple product, a product with combinations and a product pack ?

Once we have this mapping of the topic we should complete this document https://github.com/PrestaShop/prestashop-specs/pull/122 and then (I hope) we'll be able to work out a reliable solution with everybody having the same understanding of the topic 😄 .

**Comment by kpodemski** [comment]
Hey @matks 

We have few possibilities when it comes to product images:

- you can select any image added to product as *cover*
- you can select which images are related to which combinations

The problem:
If you have product, for example T-shirt in various colors, you might want to setup it in a way where you assign images of white T-shirt to combination "Color: white", and images of black T-shirt to combination "Color: black", but what about *cover* then? Well, cover will still display 1 image selected from *all product images*, so when user is adding "Color: white" to shopping cart, he will see image of black t-shirt instead of white one.

Right now entire PrestaShop front-office depends on *cover* selected from first tab of product edition, and in my opinion it's not a good idea.

I'd say that we need two options:

- *cover* for simple products without combinations: cover comes from user selection
- *cover* for product with combinations where we select first related image instead of user selection: cover comes from combination images, not user selection

Now... when it comes to "naming", I really don't know how to handle this as in both scenarios we need to get cover, but one cover should depend on user selection of it, and one on image selection for combinations, so... maybe:

Simple product cover
Combination product cover

?

Pack products are treated as simple ones from what I know :) And if you have few products in it, it should indeed display image selected by user as a cover.

**Comment by jolelievre** [comment]
Hi @kpodemski 

I actually found something while fixing https://github.com/PrestaShop/PrestaShop/pull/22103
We can use `$product.default_image` which matches the combination cover image (or first combination image by default) This might be solution to all our problems I guess in cart, modal and stuff we should use this default image instead of cover

And the cover image should be limited to the products lists where you display a generic image (let aside special use case for search where modules can override the cover image to map the search)

**Comment by kpodemski** [comment]
@jolelievre nice! I just changed this PR to match your code from issue with packs 👍

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @kpodemski

**Comment by Roomsmaniia** [comment]
LGTM,
image

Thanks @kpodemski

**Comment by matks** [comment]
Thank you @kpodemski
