### PR TITLE
Fix shipments tab

### LINKED ISSUE #39301: Improve shipment - Tab "Shipment (x)" : display bugs
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

1. Detailed order page displayed
2. A double frame is displayed that is not expected 
    Sorting the column is not possible
    The title "Price" is not the good one (it should be "Shipping cost")
    The data in the columns are not aligned as in the mocks up

Image

### Expected behavior

1. Detailed order page displayed 
2. Image

### Steps to reproduce

Pre conds : 
- "Improve shipments" experimental feature activated 
- Order placed on the BO that can be merged

1. Go on the detailed order page
2. Check the tab "Shipments (x)

### PrestaShop version(s) where the bug happened

9

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

8.1.33

### If your bug is related to a module, specify its name and its version

Experimental feature Improve shipment

### Your company or customer's name goes here (if applicable).

ps

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | some fixes for shipments tab
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/39301
| UI Tests          | -
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/39301
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

File: src/Core/Grid/Data/Factory/ShipmentGridDataFactory.php [hunk 1]
```diff
@@ -63,7 +63,7 @@ private function applyModifications(RecordCollectionInterface $records): RecordC
         $updated = [];
 
         foreach ($records as $record) {
-            $record['price'] = $this->locale->formatPrice((float) $record['price'], $this->currencyContext->getIsoCode());
```
Comment (Quetzacoalt91) [inline src/Core/Grid/Data/Factory/ShipmentGridDataFactory.php:66]: No need to run it on the price anymore?

Comment (M0rgan01) [reply src/Core/Grid/Data/Factory/ShipmentGridDataFactory.php:66]: it's just a rename (`$record['shipping_cost'] = $this->locale->formatPrice((float) $record['shipping_cost'], $this->currencyContext->getIsoCode());`)

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by ga-devfront — DISMISSED** [review]

**Review by ga-devfront — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by ingridusta — APPROVED** [review]
Hello, 
Thanks for all the corrections ! 
Capture d’écran 2025-08-05 à 16 15 59
(The sorting has been deleted)

**Review by tblivet — APPROVED** [review]

**Review by ga-devfront — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]
