### PR TITLE
Don't recalculate total when PS_ORDER_RECALCULATE_SHIPPING is 0 and editing a carrier

### LINKED ISSUE #25418: issue on total when change courier on admin
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

when I change courier on active order, even if this flag is off (see this https://nimb.ws/JrHXi4 )  the total of the order (only the total) changes

image

#### Steps to Reproduce

1. Go to 'admin-->shop parameters-->order setting-->Recalculate shipping costs after editing the order-->OFF'
2. change carrier into an active orde
4. order total changes

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.5
* PHP version: 7.4.16

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Don't recalculate total when PS_ORDER_RECALCULATE_SHIPPING is 0 and editing a carrier
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25418
| How to test?      | Cf  #25418

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25428)

### CODE REVIEW

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 1]
```diff
@@ -315,17 +315,15 @@ private function updateOrderTotals(Order $order, Cart $cart, int $computingPreci
                 $order->total_discounts = $order->total_discounts - $order->total_shipping_tax_incl + $totalShippingTaxIncluded;
                 $order->total_discounts_tax_excl = $order->total_discounts_tax_excl - $order->total_shipping_tax_excl + $totalShippingTaxExcluded;
                 $order->total_discounts_tax_incl = $order->total_discounts_tax_incl - $order->total_shipping_tax_incl + $totalShippingTaxIncluded;
+            } else {
+                $order->total_paid -= ($order->total_shipping_tax_incl - $totalShippingTaxIncluded);
```
Comment (sowbiba) [inline src/Adapter/Order/OrderAmountUpdater.php:319]: this operation is weird for me
Whatever the shipping value is, this will result in 

$order->total_paid -= 0
$order->total_paid_tax_incl -= 0
$order->total_paid_tax_excl -= 0

Comment (sowbiba) [reply src/Adapter/Order/OrderAmountUpdater.php:319]: why not test that case earlier and Do nothing ?

**Review by jolelievre — APPROVED** [review]

File: src/Adapter/Order/OrderAmountUpdater.php (hunk 1 above)
Comment (sowbiba) [reply src/Adapter/Order/OrderAmountUpdater.php:319]: why doing 

$order->total_shipping = $cart->getOrderTotal(true, **Cart::ONLY_SHIPPING**, $orderProducts, $carrierId, false, $this->keepOrderPrices);
        $order->total_shipping_tax_excl = $cart->getOrderTotal(false, **Cart::ONLY_SHIPPING**, $orderProducts, $carrierId, false, $this->keepOrderPrices);
        $order->total_shipping_tax_incl = $cart->getOrderTotal(true, **Cart::ONLY_SHIPPING**, $orderProducts, $carrierId, false, $this->keepOrderPrices);

if the shipping price doesn't have to be updated ?

**Review by sowbiba — APPROVED** [review]

File: src/Adapter/Order/OrderAmountUpdater.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Order/OrderAmountUpdater.php:319]: Because `$cart->getOrderTotal(true, CART::ONLY_BOTH...) calculate with shipping... So if we change carrier, `$cart->getOrderTotal(true, CART::ONLY_BOTH...)` take the shipping for the new carrier, we need to substract it and add the old one.

**Review by matks — APPROVED** [review]

File: src/Adapter/Order/OrderAmountUpdater.php (hunk 1 above)
Comment (sowbiba) [reply src/Adapter/Order/OrderAmountUpdater.php:319]: oh, ok I get it, it's because total_paid is recalculated l284, so with the new shipping price. This operation is only for resetting the former shipping price. Sorry for bothering you with that. thanks

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 

I check these tests:
Recalculate shipping costs option enabled:

- Update quantity product
- Change Address / Edit address
- Change carrier
- Add/Remove product
- Change Currency
- Remove cart rule free shipping
- Add new Order from the BO

Recalculate shipping costs option disabled:

- Update quantity product
- Change Address /Edit Adress
- Change carrier
- Add/Remove product
- Change currency
- Remove cart rule free shipping
- Add new Order from the BO

https://drive.google.com/file/d/1A6rs5FjAIVM8CaFE2ZTyMP5_ph2PBay-/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
