### PR TITLE
PR - Fix order detail price re-calculation

### LINKED ISSUE #36373: Bad price re-calculation on order update from BO
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When editing an order delivery address in the BO, tthe product prices of that order are recalculated (to adjust the tax for the country). The code is incorrect and DOUBLES the orderDetail->total_price_tax_incl due to a typo.

lease note that this has not been detected earlier because a SECOND update of this order is done later, in the same PHP process, when PrestaShop recalculates all the prices from the products found in the cart, in `OrderAmountUpdater::updateOrderDetails()`

```
ChangeOrderDeliveryAddressHandler::handle()
  `-- OrderDetailUpdater::updateOrderDetailsTaxes()  // first (incorrect) update
  `-- OrderAmountUpdater::update()
        `-- OrderAmountUpdater::updateOrderDetails()  // second update (based on cart product prices)
```

### Expected behavior

Having the good data saved in DB

### Steps to reproduce

0. BEFORE:
have a way to log each SQL request made.
UNRECOMMENDED METHOD: For example, in your ENV environment:
/classes/db/DbPDO.php
```php
   protected function _query($sql)
    {
        try {
            file_put_contents(_PS_ROOT_DIR_.'/pr-fix-order-detail-updater.log', date('[Y-m-d H:i:s] ').print_r($sql, true).PHP_EOL, FILE_APPEND);
            return $this->link->query($sql);
        } catch (PDOException $exception) {
            throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception);
        }
    }
```

Steps to reproduce:

1. Have a cart with 2 products, each with an associated VAT tax for your country.
2. Place an order with that cart.
3. in BO, edit the order's delivery address.
4. For example, change the last digit of the phone number.
5. save

You will see in the SQL requests that a first batch of updates is done in `order_detail` with incorrect data, followed by a second batch later on with the correct data

### PrestaShop version(s) where the bug happened

9.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

KIWIK (kiwik.com)

### PR DESCRIPTION
**Pull request by Jeremie-Kiwik**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When editing an order delivery address in the BO, the product prices of that order are recalculated (to adjust the tax for the country). The code is incorrect and set a bad tax incl. price (`orderDetail->total_price_tax_incl`) due to a typo.<br>Please note that this has not been detected earlier because a SECOND update of this order is done later, in the same PHP process, when PrestaShop recalculates all the prices from the products found in the cart, in `OrderAmountUpdater::updateOrderDetails()`
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See below
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #36373
| Related PRs       |
| Sponsor company   | KIWIK (kiwik.com)

*Steps to reproduce*

0. BEFORE:
Have a way to log each SQL request made.
UNRECOMMENDED METHOD: For example, in your ENV environment:
```php
/classes/db/DbPDO.php
   protected function _query($sql)
    {
        try {
            file_put_contents(_PS_ROOT_DIR_.'/(pr-fix-order-detail-updater.log', \date('[Y-m-d H:i:s] ').print_r($sql, true).PHP_EOL, FILE_APPEND);
            return $this->link->query($sql);
        } catch (PDOException $exception) {
            throw new PrestaShopException($exception->getMessage(), (int) $exception->getCode(), $exception);
        }
    }
```

1. Have a cart with 2 products, each with an associated VAT tax for your country.
2. Place an order with that cart.
3. in BO, edit the order's delivery address.
4. For example, change the last digit of the phone number.
5. save
6. You will see in the SQL requests that a first batch of updates is done in `order_detail` with incorrect data, followed by a second batch later on with the correct data

Example of SQL requests (I only kept some fields for a better understanding)
```sql
-- WITHOUT PR
-- 1st update
UPDATE `ps_order_detail` SET `id_order_detail` = '8', ... `total_price_tax_incl` = '57.44' ... WHERE `id_order_detail` = 8;
UPDATE `ps_order_detail` SET `id_order_detail` = '9', ... `total_price_tax_incl` = '14.4'  ... WHERE `id_order_detail` = 9;
-- 2nd update
UPDATE `ps_order_detail` SET `id_order_detail` = '8', ... `total_price_tax_incl` = '43.08' ... WHERE `id_order_detail` = 8;
UPDATE `ps_order_detail` SET `id_order_detail` = '9', ... `total_price_tax_incl` = '10.8'  ... WHERE `id_order_detail` = 9;


-- WITH PR
-- 1st update
UPDATE `ps_order_detail` SET `id_order_detail` = '8', ... `total_price_tax_incl` = '43.08' ... WHERE `id_order_detail` = 8;
UPDATE `ps_order_detail` SET `id_order_detail` = '9', ... `total_price_tax_incl` = '10.8'  ... WHERE `id_order_detail` = 9;
-- 2nd update
UPDATE `ps_order_detail` SET `id_order_detail` = '8', ... `total_price_tax_incl` = '43.08' ... WHERE `id_order_detail` = 8;
UPDATE `ps_order_detail` SET `id_order_detail` = '9', ... `total_price_tax_incl` = '10.8' ...  WHERE `id_order_detail` = 9;
```

The changes occurs in:
```php
ChangeOrderDeliveryAddressHandler::handle()
  `-- OrderDetailUpdater::updateOrderDetailsTaxes()  // first (incorrect) update
  `-- OrderAmountUpdater::update()
        `-- OrderAmountUpdater::updateOrderDetails()  // second update (based on cart product prices)
```

### CODE REVIEW

File: src/Adapter/Order/OrderDetailUpdater.php [hunk 1]
```diff
@@ -199,15 +199,15 @@ public function updateOrderDetailsTaxes(Order $order): void
...
+                        $orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_excl + $totalAmount;
                     }
 
                     Db::getInstance()->insert('order_detail_tax', $orderDetailTaxes, false);
                 }
 
                 // Update OrderDetail values
                 $orderDetail->unit_price_tax_incl = (float) $orderDetail->unit_price_tax_excl + $unitAmount;
-                $orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_incl + $totalAmount;
+                $orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_excl + $totalAmount;
```
Comment (kpodemski) [inline src/Adapter/Order/OrderDetailUpdater.php]: This is so counterintuitive. Tax included total price = total price tax excluded + something. Is `$orderDetail->total_price_tax_excl` 0 at this point?

Even if it fixes the issue, I think we should make sure this code is readable because, for me, it is definitely not readable unless I am missing something.

Comment (Hlavtox) [reply src/Adapter/Order/OrderDetailUpdater.php]: @kpodemski I think it makes sense `total_price_tax_incl` is `total_price_tax_excl` + `$totalAmount` of taxes.

However, why there are the same lines twice?

```
$orderDetail->unit_price_tax_incl = (float) $orderDetail->unit_price_tax_excl + $unitAmount;
$orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_excl + $totalAmount;
```

Comment (Jeremie-Kiwik) [reply src/Adapter/Order/OrderDetailUpdater.php]: `$orderDetail->total_price_tax_excl` isn't 0. It has the good tax excl value. So it is ok to say that tax included total price = tax excluded total price + total tax amount.

But you're right, it is mostly unreadable, and I think there is another problem on products with multiples taxesAmount. Their `$orderDetail->unit_price_tax_incl ` will store the amount of the LAST taxeAmount, and not a sum of every taxeAmount.

Perhaphs the update can be done like this:
- parse all taxesAmount, to populate `order_detail_tax` table
- at the end, update `order_detail_tax` with the new calculated taxes (or `0` if there was no tax)

Here is a try:

```php
// FIX: new variable to store the sum of "unit amount" taxes
//$unitAmount = $totalAmount = 0;
$unitAmount = $totalUnitAmount = $totalAmount = 0;
// END
if (!empty($taxesAmount)) {
    $orderDetailTaxes = [];
    foreach ($taxesAmount as $taxId => $amount) {
        switch ($roundType) {
            case Order::ROUND_ITEM:
                $unitAmount = (float) Tools::ps_round($amount, $computingPrecision);
                $totalAmount = $unitAmount * $orderDetail->product_quantity;

                break;
            case Order::ROUND_LINE:
                $unitAmount = $amount;
                $totalAmount = Tools::ps_round($unitAmount * $orderDetail->product_quantity, $computingPrecision);

                break;
            case Order::ROUND_TOTAL:
                $unitAmount = $amount;
                $totalAmount = $unitAmount * $orderDetail->product_quantity;

                break;
        }
        $orderDetailTaxes[] = [
            'id_order_detail' => $orderDetail->id,
            'id_tax' => $taxId,
            'unit_amount' => (float) $unitAmount,
            'total_amount' => (float) $totalAmount,
        ];
        // FIX: store the current unit amount, and do not alter orderDetail for now
        $totalUnitAmount += $unitAmount;
        //$orderDetail->unit_price_tax_incl = (float) $orderDetail->unit_price_tax_excl + $unitAmount;
        //orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_excl + $totalAmount;
        // END
    }

    Db::getInstance()->insert('order_detail_tax', $orderDetailTaxes, false);
}

// Update OrderDetail values
// FIX: store the sum of each taxeAmount
//$orderDetail->unit_price_tax_incl = (float) $orderDetail->unit_price_tax_excl + $unitAmount;
$orderDetail->unit_price_tax_incl = (float) $orderDetail->unit_price_tax_excl + $totalUnitAmount;
// END
$orderDetail->total_price_tax_incl = (float) $orderDetail->total_price_tax_excl + $totalAmount;
if (!$orderDetail->update()) {
    throw new OrderException('An error occurred while editing the product line.');
}
```

Comment (kpodemski) [reply src/Adapter/Order/OrderDetailUpdater.php]: @Jeremie-Kiwik The name of the variable confused me. I would expect `totalTaxAmount`, but on the other hand method is named `updateOrderDetailTaxes`, so maybe I'm nitpicking

> and I think there is another problem on products with multiples taxesAmount. Their $orderDetail->unit_price_tax_incl  will store the amount of the LAST taxeAmount, and not a sum of every taxeAmount.

If I recall correctly, we have scenarios for this in behat tests, I'll ping @jolelievre and @amine-O because I believe that this error is a major one, the one that you reported. The one with the last tax rate being applicable is also not something good to have, of course

Comment (Jeremie-Kiwik) [reply src/Adapter/Order/OrderDetailUpdater.php]: So, here is a try with readable names + will store in `order_detail` the sum of every taxeAmount. Which is a breaking change :-/

**Review by boherm — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Jeremie-Kiwik

**Comment by nicosomb** [comment]
Here are my logs

## Without your pull request 

```
--- 1st update

[2025-03-03 16:26:59] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '46.4',`total_price_tax_excl` = '29',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '29',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 12
[2025-03-03 16:26:59] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '19.04',`total_price_tax_excl` = '11.9',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '11.9',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 13

--- 2nd update

[2025-03-03 16:26:59] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '34.8',`total_price_tax_excl` = '29',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '29',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 12
[2025-03-03 16:26:59] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '14.28',`total_price_tax_excl` = '11.9',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '11.9',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 13
```


## With your pull request 


```
--- 1st update

[2025-03-03 16:23:48] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '34.8',`total_price_tax_excl` = '29',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '29',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 12
[2025-03-03 16:23:48] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '14.28',`total_price_tax_excl` = '11.9',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '11.9',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 13

--- 2nd update 

[2025-03-03 16:24:52] UPDATE `ps_order_detail` SET (...) `total_price_tax_incl` = '34.8',`total_price_tax_excl` = '29',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '29',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 12
[2025-03-03 16:24:52] UPDATE `ps_order_detail` SET `total_price_tax_incl` = '14.28',`total_price_tax_excl` = '11.9',`total_shipping_price_tax_excl` = '0',`total_shipping_price_tax_incl` = '0',`purchase_supplier_price` = '5.49',`original_product_price` = '11.9',`original_wholesale_price` = '5.49',`total_refunded_tax_excl` = '0',`total_refunded_tax_incl` = '0' WHERE `id_order_detail` = 13

```

## Conclusion 

It's OK for me ✅

**Comment by nicosomb** [comment]
UI tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/13634544728

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.
