### PR TITLE
Delete supplier's address only if no other shops use it

### LINKED ISSUE #14762: Issue when we delete a supplier in multistore
**Describe the bug**
If a supplier is available for all shops and I delete the supplier for Shop A when I try to edit in Shop B an error page appear

**To Reproduce**
1. Create two shops 
2. Go to Brands & Supplier
3. Create a supplier for all shops
4. Then delete this supplier for shop A
5. Edit the supplier in shop B 
6. See the error 

**Screenshots**
https://drive.google.com/file/d/1lsyNnpeGF0adJeC2liNBtSLZBUTnI0pX/view

**Additional information**
PrestaShop version: 1.7.7
PHP version: 7.1

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Do not delete supplier's address if it's used for another shop
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14762
| How to test?  | 1. Create two shops<br>2. Go to Brands & Supplier<br>3. Create a supplier for all shops<br>4. Then delete this supplier for shop A<br>5. Edit the supplier in shop B

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16123)

### CODE REVIEW

File: src/Adapter/Supplier/CommandHandler/AbstractDeleteSupplierHandler.php [hunk 1]
```diff
@@ -117,13 +117,15 @@ protected function removeSupplier(SupplierId $supplierId)
...
 
-            if (false === $this->deleteSupplierAddress($supplierId)) {
-                throw new CannotDeleteSupplierAddressException(
-                    sprintf(
-                        'Unable to set deleted flag for supplier with id "%s" address',
-                        $supplierId->getValue()
-                    )
-                );
+            if (1 >= count($entity->getAssociatedShops())) {
+                if (false === $this->deleteSupplierAddress($supplierId)) {
```
Comment (PierreRambaud) [inline src/Adapter/Supplier/CommandHandler/AbstractDeleteSupplierHandler.php]:
```suggestion
                if (1 >= count($entity->getAssociatedShops()) && false === $this->deleteSupplierAddress($supplierId)) {
```
Only one if is needed :sweat_smile: Sorry

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thank you @atomiix
