### PR TITLE
Fix warning on the Customer Threads page

### LINKED ISSUE #23837: Warning on line 1021 in file /prestashop/controllers/admin/AdminCustomerThreadsController.php [2] count(): Parameter must be an array or an object that implements Countable
#### Description

When saving the imap settings on the backend customer service page the following error is shown.

`Warning on line 1021 in file /prestashop/controllers/admin/AdminCustomerThreadsController.php [2] count(): Parameter must be an array or an object that implements Countable`

LINE 1014 = `$errors = imap_errors()` 
this returns a boolean when there are no errors.

LINE 1021 = `if (count($errors) && is_array($errors) {` _[current code]_
This is because the IF-statement which checks the $errors array is in the wrong order.
If nothing is returned from imap_errors() then $errors becomes a boolean which isn't countable

Changing LINE 1021 fixes the issue 
`if (is_array($errors) && count($errors))  {` _[fix code]_
 -> switching the 2 options of the IF-statement

#### Steps to Reproduce

1. Go to 'Customer Service' in the backend
2. Setup IMAP settings & Save
3. Revisit the 'Customer Service' page

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | wrong check for the errors
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23837
| How to test?      | All details in the issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

IMPORTANT: You need to have properly configured IMAP first 🔴 🔴 🔴 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25858)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: controllers/admin/AdminCustomerThreadsController.php [hunk 1]
```diff
@@ -1017,7 +1017,7 @@ public function syncImap()
         $str_errors = '';
         $str_error_delete = '';
 
-        if (count($errors) && is_array($errors)) {
+        if (!empty($errors)) {
```
Comment (PierreRambaud) [inline controllers/admin/AdminCustomerThreadsController.php]:
```suggestion
        if (is_array($errors) && count($errors)) {
```

Should do the job. With your change, you don't check if $errors is an array and is iterable.

**Review by PierreRambaud — DISMISSED** [review]
Inverse the condition order, it's the real trick :)

File: controllers/admin/AdminCustomerThreadsController.php (hunk 1 above)
Comment (kpodemski) [reply controllers/admin/AdminCustomerThreadsController.php]: I don't think it's that needed for a `imap_errors(): array|false`, but I'll follow your advice.

**Review by matks — APPROVED** [review]

File: controllers/admin/AdminCustomerThreadsController.php (hunk 1 above)
Comment (NeOMakinG) [reply controllers/admin/AdminCustomerThreadsController.php]: @PierreRambaud Are you really sure about this? I think that the `$errors` variable type is forced to be an array OR false as it's an `imap_errors`, so empty is the perfect case, if $errors is false, empty is false, if it's an array but empty it will return false, looks like `is_array($errors) && count($errors)` is overkill (except if it has better performances than using empty)

ping @Progi1984 looks like the thing we seen together last week

Comment (PierreRambaud) [reply controllers/admin/AdminCustomerThreadsController.php]: The first `is_array` check will be faster than `empty` meaning it will fail fast
I didn't check it came from the `imap_errors`, so both are valid ^^

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @kpodemski
