### PR TITLE
Fix wrong number of orders when filter 'New client' on

### LINKED ISSUE #18248: [Orders Page] - Wrong number of orders displayed with filter 'New Client'
#### Describe the bug

When filtering by column 'New Client' in orders page, the number of orders displayed in `h3.card-header-title` is wrong (it displays the total number of orders)

#### Expected behavior

The correct number of orders displayed

#### Steps to Reproduce

1. Go to 'BO > Orders' page
2. Filter by column 'New client' Value 'Yes'
Expected number of orders displayed : 1
Actual Number of orders displayed : 5
image

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | When filter by 'new client' in the page order, the number of orders (in the header) was wrong. This PR fixes it
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18248
| How to test?  | 1. Go to 'BO > Orders' page<br>2. Filter by column 'New client' Value 'Yes'<br>3. See that the number of orders in the header of the table should be equal to the number of order in the table. (see below)

Capture d’écran 2020-03-24 à 14 24 12

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18288)

### CODE REVIEW

**Review by matks — APPROVED** [review]

File: src/Core/Grid/Query/OrderQueryBuilder.php [hunk 1]
```diff
@@ -231,6 +230,25 @@ private function getBaseQueryBuilder(array $filters)
...
+        $newCustomerSubSelect = $this->connection
+            ->createQueryBuilder()
+            ->select('so.id_order')
+            ->from($this->dbPrefix . 'orders', 'so')
+            ->where('so.id_customer = o.id_customer')
+            ->andWhere('so.id_order < o.id_order')
+            ->setMaxResults(1)
+        ;
+
+        return $qb->addSelect('IF ((' . $newCustomerSubSelect->getSQL() . ') > 0, 0, 1) AS new');
```
Comment (jolelievre) [inline src/Core/Grid/Query/OrderQueryBuilder.php:249]: I don't think you need to return the query builder? Since it is passed as argument and already modified

File: src/Core/Grid/Query/OrderQueryBuilder.php [hunk 2]
```diff
@@ -122,8 +113,16 @@ public function getSearchQueryBuilder(SearchCriteriaInterface $searchCriteria)
      */
     public function getCountQueryBuilder(SearchCriteriaInterface $searchCriteria)
     {
-        return $this->getBaseQueryBuilder($searchCriteria->getFilters())
-            ->select('COUNT(o.id_order)');
+        $qb = $this->getBaseQueryBuilder($searchCriteria->getFilters());
+        if (isset($searchCriteria->getFilters()['new'])) {
+            $qb = $this->addNewCustomerField($qb->addSelect('o.id_order as o_id_order'));
+            $qb = $this->applyNewCustomerFilter($qb, $searchCriteria->getFilters());
+            $qb->select('count(o_id_order)');
```
Comment (jolelievre) [inline src/Core/Grid/Query/OrderQueryBuilder.php:120]: `$qb->select('count(o_id_order)');` can always be performed after the `if` statement, and the `else` statement can then be removed

Comment (atomiix) [reply src/Core/Grid/Query/OrderQueryBuilder.php:120]: @jolelievre It's not exactly the same line, one is `o_id_order` the other one is `o.id_order` 😄

Comment (jolelievre) [reply src/Core/Grid/Query/OrderQueryBuilder.php:120]: Ooohhh, my bad! 😅

**Review by jolelievre — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @atomiix
