### PR TITLE
Hide suppliers if there are no suppliers on product v2

### LINKED ISSUE #29348: BO - Product V2 - When we delete all suppliers, the supplier block is still displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reported previously here: https://github.com/PrestaShop/PrestaShop/pull/27353#pullrequestreview-968285262
when we delete all suppliers, the supplier block is still displayed => in the spec `This part is displayed only if you have created at least one supplier.`

### Expected behavior

when we delete all suppliers, the supplier block is still displayed => in the spec `This part is displayed only if you have created at least one supplier.`

### Steps to reproduce

1. Go to BO > Catalog > Suppliers & delete all suppliers 
2. Go to BO > Catalog > Product V2 > Edit a product 
3. In the Options tab > check that the supplier block is still displayed

image

Reproduced with 1787 product V2 / 80x product V2

In the product V1 => OK

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.x

### PHP version(s) where the bug happened

7.2, 8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Suppliers shouldn't be displayed if there are no suppliers in the shop
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29348.
| How to test?      | See issue
| Possible impacts? | Product v2 suppliers

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php [hunk 1]
```diff
@@ -83,12 +83,28 @@ public function adaptProductForm(FormEvent $event): void
...
+
+        // As this is also executed on pre-submit, we need to verify that suppliers exist before removing it
+        if ($optionsField->has('suppliers')) {
+            $suppliers = $optionsField->get('suppliers')->get('supplier_ids')->getConfig()->getOptions()['choices'];
+
+            // Don't display the suppliers part if there are no suppliers
+            if (count($suppliers) <= 0) {
+                $this->removeSuppliers($form);
+
+                if ($optionsField->has('product_suppliers')) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php]: Maybe this should be placed in the `removeProductSuppliers` instead, I don't know if calling remove on a non-existent field triggers an error

**Review by jolelievre — DISMISSED** [review]
Thanks @NeOMakinG

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
Thanks @NeOMakinG 
I tested the cases and it's all good (Simple Product, product with combinations)
Product V1 : 
- No Supplier => Block is not displayed :heavy_check_mark: 
- Disabled supplier => Block is not displayed :x: ([known Bug](https://github.com/PrestaShop/PrestaShop/pull/27353#issuecomment-1113482543))
Product V2 : 
- No Supplier => Block is not displayed :heavy_check_mark: 
- Disabled supplier => Block is displayed :heavy_check_mark: (Bug resolved)
