### PR TITLE
Replace usages of jQuery.live usages and add polyfill

### LINKED ISSUE #15882: legacy order create page not working well after jquery migration
@matthieu-rolland, @matks  - after this pr legacy order create page is not working well.

- Cannot choose customer;
- Carts/orders are shown before even choosing customer. 

Screenshot from 2019-10-09 14-18-47
Checked locally, that undoing this pr changes brings back the expected behavior.

_Originally posted by @zuk3975 in https://github.com/PrestaShop/PrestaShop/pull/15245#issuecomment-539958808_

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Replace usage of jQuery.live with jQuery.on, and add a jQuery.live polyfill.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15882
| How to test?  | Check that order page in BO works fine again.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15900)

### CODE REVIEW

File: classes/controller/AdminController.php [hunk 1]
```diff
@@ -2705,8 +2705,9 @@ public function setMedia($isNewTheme = false)
             // add Jquery 3 and its migration script
             $this->addJs(_PS_JS_DIR_ . 'jquery/jquery-3.4.1.min.js');
             $this->addJs(_PS_JS_DIR_ . 'jquery/jquery-migrate-3.1.0.min.js');
-            // implement $.browser object, that has been removed since jquery 1.9
+            // implement $.browser object and live method, that has been removed since jquery 1.9
             $this->addJs(_PS_JS_DIR_ . 'jquery/jquery.browser-0.1.0.min.js');
+            $this->addJs(_PS_JS_DIR_ . 'jquery/jquery.live.js');
```
Comment (Progi1984) [inline classes/controller/AdminController.php]: @matthieu-rolland : Could you define in filename the version of the jquery.live ?

**Review by Progi1984 — DISMISSED** [review]

File: classes/controller/AdminController.php (hunk 1 above)
Comment (matthieu-rolland) [reply classes/controller/AdminController.php]: ah yes, good point !
This PR is in wip so far because it's not finished, and the jquery.live file will be replaced by the one I pushed on a dedicated repo.

But thanx for the comment idea, totally forgot about that. 👍

Comment (Progi1984) [reply classes/controller/AdminController.php]: Sorry for the WIP :stuck_out_tongue:

Comment (matthieu-rolland) [reply classes/controller/AdminController.php]: @Progi1984  It's fine, and your comment is helpful ;)

File: admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl [hunk 2]
```diff
@@ -64,10 +64,10 @@
 		$('#move_to_left').click(function(){
 			return !$('#select_right option:selected').remove().appendTo('#select_left');
 		});
-		$('#select_left option').live('dblclick', function(){
+		$('#select_left').on('dblclick', 'option', function(e) {
```
Comment (PierreRambaud) [inline admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl]: Prefer this, because if you have a js which change #select_left, the event will not be triggered again.
```suggestion
		$(document).on('dblclick', '#select_left option', function(e) {
```

Comment (matthieu-rolland) [reply admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl]: done !

File: classes/controller/AdminController.php (hunk 1 above)
Comment (matthieu-rolland) [reply classes/controller/AdminController.php]: In the end I implementend your suggestion @Progi1984 :D . This js file is not to be fetched via npm in the legacy backoffice.

**Review by jolelievre — DISMISSED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15900)* status: 6 of 16 files reviewed, 4 unresolved discussions (waiting on @matthieu-rolland and @Progi1984)

___
*[admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl, line 52 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdALN2dRnYljj0DUj:-LrDdALN2dRnYljj0DUk:bcsg7xm) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl#L52)):*
> ```Smarty
> 		{else}
> 			<script type="text/javascript">
> 			$('body').on('blur', 'input[name=email]', function(e)
> ```

Always prefer to attach event on document , attaching event to 'body' is the slowest method ^^'
___
*[admin-dev/themes/default/template/controllers/carriers/helpers/form/form.tpl, line 31 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdepFAnjx_PEkoymp:-LrDdepFAnjx_PEkoymq:b-2guby3) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/carriers/helpers/form/form.tpl#L31)):*
> ```Smarty
> 	($("input[name='is_free']:checked").val() == 0) ? $('#shipping_costs_div').show('toggle'): $('#shipping_costs_div').hide();
> 
> 	$('body').on('change', "input[name='is_free']", function() {ldelim}
> ```

same here
___
*[admin-dev/themes/default/template/controllers/orders/form.tpl, line 128 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdfyFD9U9eUuBWWUd:-LrDdfyFD9U9eUuBWWUe:b-reqdj3) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/orders/form.tpl#L128)):*
> ```Smarty
> 			useCart('{$cart->id|intval}');
> 		{/if}
> 		$('body').on('click', '.delete_product', function(e) {
> ```

same everywhere
___
*[admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl, line 67 at r1](https://reviewable.io/reviews/prestashop/prestashop/15900#-LqpkRQoYWU07FBwtLFq-r1-67:-LrDdmsM-g4CfhvfGVcX:b-vn3jdn) ([raw file](https://github.com/prestashop/prestashop/blob/a0b96d18df8f5a87135256dc9e4080c5c511dd78/admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl#L67)):*
<details><summary><i>Previously, matthieu-rolland (Matthieu Rolland) wrote…</i></summary><blockquote>

done ! 
</blockquote></details>

I don't see any differences.

**Comment by matthieu-rolland** [comment]
@PierreRambaud As requested, I replaced the 'body' string by a document object in jquery selectors regarding the use of jQuery.on().   👍

**Review by PierreRambaud — APPROVED** [review]
> Reviewed 7 of 7 files at r2, 1 of 3 files at r3, 4 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15900)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @matthieu-rolland, @PierreRambaud, and @Progi1984)

**Review by matthieu-rolland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15900)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @PierreRambaud and @Progi1984)

___
*[admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl, line 52 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdALN2dRnYljj0DUj:-LrIoxeSEiRhVshBf9nI:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/addresses/helpers/form/form.tpl#L52)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

Always prefer to attach event on document , attaching event to 'body' is the slowest method ^^'
</blockquote></details>

Done.
___
*[admin-dev/themes/default/template/controllers/carriers/helpers/form/form.tpl, line 31 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdepFAnjx_PEkoymp:-LrIowEs2QKXXsuA5GdP:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/carriers/helpers/form/form.tpl#L31)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[admin-dev/themes/default/template/controllers/orders/form.tpl, line 128 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdfyFD9U9eUuBWWUd:-LrIopEm8cFa-Q9A077H:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/orders/form.tpl#L128)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

same everywhere
</blockquote></details>

Done.
___
*[classes/controller/AdminController.php, line 2710 at r1](https://reviewable.io/reviews/prestashop/prestashop/15900#-LqpkRQoYWU07FBwtLFs-r1-2710:-LrIoslQ4pI8h4571IHo:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/a0b96d18df8f5a87135256dc9e4080c5c511dd78/classes/controller/AdminController.php#L2710)):*
<details><summary><i>Previously, matthieu-rolland (Matthieu Rolland) wrote…</i></summary><blockquote>

In the end I implementend your suggestion @Progi1984 :D . This js file is not to be fetched via npm in the legacy backoffice.
</blockquote></details>

Done.

**Review by matthieu-rolland — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15900)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @PierreRambaud, @Progi1984, and @Robin-Fischer-PS)

___
*[admin-dev/themes/default/template/controllers/orders/form.tpl, line 128 at r3](https://reviewable.io/reviews/prestashop/prestashop/15900#-LrDdfyFD9U9eUuBWWUd:-LrJ0yyS87piFDOKiTpG:b-dobog6) ([raw file](https://github.com/prestashop/prestashop/blob/b7d426b435ace6f796c700c7da59fbd63b16bcd2/admin-dev/themes/default/template/controllers/orders/form.tpl#L128)):*
> Done.        PierreRambaud (GoT) is:   No elements found. Consider changing the search query. Blocking:
<details><summary><i alt="summary">Quoted 77 lines of code…</i></summary>

>         opposed to resolving the discussion while waiting on somebody else.
>         Dismiss from
>       this discussion
>       •
>       unresolved discussions.
>             
>             This is advanced stuff, you don't need it to get started.You are:  Discussing:
>             contributing to the discussion but neutral on resolving.
>              Satisfied: in favor of resolving and ending the discussion.
>              Blocking:
>             opposed to resolving the discussion while waiting on somebody else.
>            Working:
>             holding the discussion unresolved while working on something related.
>             No elements found. Consider changing the search query. List is empty. 
>                     
>                   
>   
>   
>   
>     
>       $(document).on('click', '.delete_product', function(e) {
>     
>     
>     
>   
> 
> 
>   
>     
>       e.preventDefault();
>     
>     
>     
>   
>   
>   
>     
>       e.preventDefault();
>     
>     
>     
>   
> 
> 
>   
>     
>       var to_delete = $(this).attr('rel').split('_');
>     
>     
>     
>   
>   
>   
>     
>       var to_delete = $(this).attr('rel').split('_');
>     
>     
>     
>   
> 
> 
>   
>     
>       deleteProduct(to_delete[1], to_delete[2], to_delete[3]);
>     
>     
>     
>   
>   
>   
>     
>       deleteProduct(to_delete[1], to_delete[2], to_delete[3]);
>     
>     
>     
>   
> 
</details>
> EXPANDEXPAND
<details><summary><i alt="summary">Quoted 36 lines of code…</i></summary>

>                 Collapsed:
>               1461 lines
>             with
>             
>               no changes
>             
> 
> 
>             
>           
>         
>           
>           
>             
>       single
>     
>       auto
>     130…admin-dev/themes/default/template/controllers/specific_price_rule/…helpers/form/form.tpl⊥r2r3r4
> 
> 
>   
>     
>        
>     
>     
>     
>   
>   
>   
>     
>        
>     
>     
>     
>   
> 
</details>
> EXPANDEXPAND
<details><summary><i alt="summary">Quoted 39 lines of code…</i></summary>

>                 Collapsed:
>               318 lines
>             with
>             
>               no changes
>             
> 
> 
>             
>           
>         
>           
>             
>               
>                 Files hidden because they have no changes or open comments:
>               
>               
>                 (show all)
>               
>             
>             admin-dev/themes/default/template/controllers/tags/helpers/form/form.tpl
>             
>           
>           
>         
>           
>             
>             admin-dev/themes/default/template/helpers/form/assoshop.tpl
>             
>           
>           
>         
>           
>           
>             
>       single
>     
>       auto
>     130…</details>

**Review by matks — APPROVED** [review]
> Reviewed 7 of 7 files at r2, 2 of 3 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15900)* status: all files reviewed, 4 unresolved discussions (waiting on @PierreRambaud, @Progi1984, and @Robin-Fischer-PS)
