### PR TITLE
Fix BO menu scrollbar size on small screens

### LINKED ISSUE #9588: [BOOM-5964] Scroll bar in back-office menu is too big on small screens
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5964).

- _**Reporter:**_ coline.ginestet
- _**Created at:**_ Thu, 12 Jul 2018 16:09:31 +0200

Current scroll bar in 1.7.4.0 is to be changed with this one: https://github.com/mdbootstrap/perfect-scrollbar

image-2018-07-12-16-09-25-564

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Integrate perfectscrollbar.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Ticket? | Fixes #9588
| How to test?  | Follow ticket instruction.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14689)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/nav_bar.js [hunk 1]
```diff
@@ -22,158 +22,187 @@
...
     });
   }
 
   mobileNav() {
-    let $logout = $('#header_logout').addClass('link').removeClass('m-t-1').prop('outerHTML');
-    let $employee = $('.employee_avatar').prop('outerHTML');
-    let profileLink = $('.profile-link').attr('href');
+    const $logout = $('#header_logout').addClass('link').removeClass('m-t-1').prop('outerHTML');
+    const $employee = $('.employee_avatar').prop('outerHTML');
+    const profileLink = $('.profile-link').attr('href');
```
Comment (matthieu-rolland) [inline admin-dev/themes/new-theme/js/nav_bar.js:156]: Question: what is the meaning of adding a '$' at the beginning of a variable, does it mean that **.prop('outerHTML')** returns a jquery object?

Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/nav_bar.js:156]: I don't know :D as I know it's not returning an HTML object.

Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/nav_bar.js:156]: This is what happened when there are no rules :trollface:

Comment (matthieu-rolland) [reply admin-dev/themes/new-theme/js/nav_bar.js:156]: haha yes indeed, it's not meaningless if the goal is to give a cue about the type of the variable (a jquery object), but here I'm not sure. No big deal since those variables were already there and used...

**Review by matthieu-rolland — DISMISSED** [review]
LGTM

**Comment by sarahdib** [comment]
@PierreRambaud there is some conflicting files can you resolve it ?

**Comment by PierreRambaud** [comment]
@sarahdib Done

**Review by matks — APPROVED** [review]
