### PR TITLE
Split integration workflows into two, get rid of processIsolation

### LINKED ISSUE #27062: CI is failing on develop for multiple reasons
We've had multiple CI failing issues today:

## Behat CI failing

Following merge of PRs and the Behat tests were failing

Fixed by https://github.com/PrestaShop/PrestaShop/pull/27046 ✅ 

## PHPUnit CI failing

Running phpunit using Composer binary is failing since composer/composer 2.2 https://github.com/composer/composer/issues/10387
```
1) Tests\Integration\Adapter\Cart\CartPresenterTest::testProductAttributesAreProperlyConverted with data set #0 ('Taille : S- Couleur : Noir', array('S', 'Noir'))
PHPUnit\Framework\Exception: PHP Fatal error:  strict_types declaration must be the very first statement in the script in /home/runner/work/PrestaShop/PrestaShop/vendor/phpunit/phpunit/phpunit on line 2
Fatal error: strict_types declaration must be the very first statement in the script in /home/runner/work/PrestaShop/PrestaShop/vendor/phpunit/phpunit/phpunit on line 2

/home/runner/work/PrestaShop/PrestaShop/vendor/phpunit/phpunit/phpunit:60
```

Fixed by https://github.com/PrestaShop/PrestaShop/pull/27067 but long-term fix needed probably in a future Composer version ✅

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Split integration workflows into two to see if it makes us win some execution time overall<br>Also got rid of `processIsolation` in almost all the integration tests, only a few ones really need to be isolated (mainly because they reboot the kernel) so a dedicated PHPUnit config has been added for them and they use a specific group to match the proper config:<br><br>`@group isolatedProcess`<br><br>Also we only build classic theme assets now because only those are necessary to successfully install the shop and test DB<br><br>Little benchmark; before this PR integration tests took 15m now it's 3m26s<br>Also the assets building went from 3m24s to 33s<br>So overall for integration tests **the gain should be minimum 15min**<br><br>So for now the CI duration is determined by our current. longer job which is Behaviour tests for PHP 7.2 and takes around 20min
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | CI green
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27055)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Seems the Symfony XmlLoader is using a deprecated function :thinking:

**Comment by jolelievre** [comment]
Yep it's a bit weird I don't understand when it's triggered exactly, but I reverted my changes on the failing test because it does need to be isolated Seems like everything is fine now Finally ^^

File: tests/Integration/Behaviour/Features/Context/LanguageFeatureContext.php [hunk 1]
```diff
@@ -52,23 +51,10 @@ public static function restoreLanguagesTablesAfterFeature(): void
...
-            $lang = new Language($langId['id_lang']);
-            $lang->delete();
-        }
-
-        // We still restore lang table to reset increment ID
-        DatabaseDump::restoreTables(['lang', 'lang_shop']);
+        LanguageResetter::resetLanguages();
 
         // Reset default language
         Configuration::updateValue('PS_LANG_DEFAULT', 1);
```
Comment (matthieu-rolland) [inline tests/Integration/Behaviour/Features/Context/LanguageFeatureContext.php]: is there a reason for not putting this part into `LanguageResetter::resetLanguages` ?

I would have think that setting `PS_LANG_DEFAULT` to 1 in the table `ps_lang` would be part of the reset

Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/LanguageFeatureContext.php]: Most of the time we don't change the default language so it was not necessary in our use cases But I guess it could be part of it indeed

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Core/Addon/Module/ModuleRepository.php [hunk 2]
```diff
@@ -205,32 +205,30 @@ public function getFilteredList(AddonListFilter $filter, $skip_main_class_attrib
...
                     unset($modules[$key]);
 
                     continue;
                 }
 
                 if ($module->database->get('installed') == 0
-                    && (!$filter->hasStatus(AddonListFilterStatus::UNINSTALLED)
-                        || $filter->hasStatus(AddonListFilterStatus::INSTALLED))) {
+                    && !$filter->hasStatus(AddonListFilterStatus::UNINSTALLED)
+                    && $filter->hasStatus(AddonListFilterStatus::INSTALLED)) {
```
Comment (matks) [inline src/Core/Addon/Module/ModuleRepository.php]: What is the relationship between this change and the PR scope?

File: app/AppKernel.php [hunk 3]
```diff
@@ -81,15 +81,34 @@ public function registerBundles()
     /**
      * {@inheritdoc}
      */
-    public function reboot($warmupDir)
+    public function boot()
```
Comment (matks) [inline app/AppKernel.php:82]: What is the relationship between this change and the PR scope?

File: tests-legacy/Endpoints/AbstractEndpointAdminTest.php [hunk 4]
```diff
@@ -88,13 +86,13 @@ protected function employeeLogin()
...
-
-        $reflectedClass = new ReflectionClass(SymfonyContainer::class);
-        $instanceProperty = $reflectedClass->getProperty('instance');
-        $instanceProperty->setAccessible(true);
-        $instanceProperty->setValue($kernel->getContainer());
-        $instanceProperty->setAccessible(false);
+        $newKernel = new AppKernel('test', true);
+        $newKernel->boot();
+
+        // Make kernel accessible for SymfonyContainer
```
Comment (matks) [inline tests-legacy/Endpoints/AbstractEndpointAdminTest.php]: 🤔

File: app/AppKernel.php (hunk 3 above)
Comment (jolelievre) [reply app/AppKernel.php:82]: Now that integration tests run without the process isolation they all run in the same process But when you use a `KernelTestCase` it actually boots and shutdown a kernel in `setUp` and `tearDown` classes

But since we store references of the kernel in some places they needed to be cleared or else the kernel from the previous test was used which resulted in weird unexpected bugs

I tried to explain this in the comment of `cleanKernelReferences` but maybe it's not clear enough?

File: src/Core/Addon/Module/ModuleRepository.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Addon/Module/ModuleRepository.php]: I had trouble making the test for this one work in process isolation And I went too deep, and the tests themselves didn't make sense 😅 And the code itself didn't make sense either!! I got lost somewhere in the middle of my own insanity...

It's a bit out of scope though, I can try and revert this to see if it goes fine now that the rest is cleaner and more stable if you want?

File: tests-legacy/Endpoints/AbstractEndpointAdminTest.php (hunk 4 above)
Comment (jolelievre) [reply tests-legacy/Endpoints/AbstractEndpointAdminTest.php]: Yes, `SymfonyContainer` is a bit weirdly done but it expects a global $kernel variable or it can't access to it So in test environment we need to update this global variable each time a kernel is booted

And I know it shouldn't be related with integration tests, but at some point this was failing so I had no choice but to fix it

Comment (jolelievre) [reply tests-legacy/Endpoints/AbstractEndpointAdminTest.php]: It might be because the kernel now clears its references, but it's cleaner to do it and it was necessary for many other use cases So just this one side effect is acceptable besides it's clear to do it this way instead of cheating with reflection to set a private field

File: src/Core/Addon/Module/ModuleRepository.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Addon/Module/ModuleRepository.php]: Actually the previous tests mostly did nothing, half of them didn't perform any assertions because the filtered list didn't return anything Now there's only one left which does no assertions because it filters modules from addons and I couldn't find a way to mock this one since we are getting rid of Addon anyway

Comment (PierreRambaud) [reply src/Core/Addon/Module/ModuleRepository.php]: Not sure it's a good idea to touch this part of code as it concerns module's bitwise :p 
I already experiment issues by editing it :eyes:

**Review by matks — COMMENTED** [review]
@jolelievre can we discuss this PR live, maybe with another maintainer? it raises lot of questions and I'm a bit worried we're modifying deep parts of the code although the PR is an improvement and does not fix something 😞

**Comment by matks** [comment]
@jolelievre looks like we did not talk about this one 😭

**Comment by Progi1984** [comment]
Hi @jolelievre,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

**Comment by jolelievre** [comment]
@Progi1984 we need to discuss this with the team on several points, and one of your PR already deals with the module manager so I was waiting for it to be merged before I rebase and clean this one

So I will reopen it, because it seemed to be a bit faster with this new solution

**Review by matthieu-rolland — COMMENTED** [review]
LGTM for me, will need to be rebased once @Progi1984 's PR will be merged

**Review by Progi1984 — DISMISSED** [review]
Hello @jolelievre, thanks for your contribution, would you mind to rebase your pull request? Thanks

Reference : https://anavarre.net/how-to-rebase-a-github-pull-request/

File: .github/workflows/behaviour.yml [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+          mysql root password: 'password'
+      - name: Setup Node
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
+
+      - uses: actions/checkout@v2
+
+      - name: PrestaShop Configuration
+        run: cp .github/workflows/phpunit/parameters.yml app/config/parameters.yml
```
Comment (atomiix) [inline .github/workflows/behaviour.yml]:
```suggestion
        run: |
            cp .github/workflows/phpunit/parameters.yml app/config/parameters.yml
            cp .github/workflows/phpunit/parameters.php app/config/parameters.php
```

File: .github/workflows/behaviour.yml [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+
+      - name: Build theme assets
+        run: make front-classic
+
+      - name: Change MySQL authentication method
+        run: mysql -h127.0.0.1 -uroot -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"
+
+      - name: Prepare PrestaShop parameters
+        run: cp .github/workflows/phpunit/parameters.php app/config/parameters.php
+
```
Comment (atomiix) [inline .github/workflows/behaviour.yml]:
```suggestion
```

File: tests/Integration/Classes/module/ModuleTest.php [hunk 7]
```diff
@@ -30,9 +30,30 @@
...
+ */
 class ModuleTest extends TestCase
 {
+    use ContextMockerTrait;
+
+    public static function setUpBeforeClass(): void
+    {
+        parent::setUpBeforeClass();
+        static::mockContext();
+        Module::resetStaticCache();
```
Comment (atomiix) [inline tests/Integration/Classes/module/ModuleTest.php]: Even if the tests are isolated you need to reset the static cache?

File: classes/module/Module.php [hunk 8]
```diff
@@ -234,6 +234,11 @@ abstract class ModuleCore implements ModuleInterface
 
     public static $hosted_modules_blacklist = ['autoupgrade'];
 
+    public static function resetStaticCache()
+    {
+        static::$_INSTANCE = [];
+    }
+
```
Comment (atomiix) [inline classes/module/Module.php]: I have a doubt about this function 🤔 If we use it for something else than the tests, the only reason I see why we would use it is to get a more recent version of a module (after an upgrade for instance) but as we use `include_once` on the module, we won't get the new version.

File: .github/workflows/behaviour.yml (hunk 6 above)
Comment (jolelievre) [reply .github/workflows/behaviour.yml]: Thanks, I'll do the same for the integration.yml config

File: tests/Integration/Classes/module/ModuleTest.php (hunk 7 above)
Comment (jolelievre) [reply tests/Integration/Classes/module/ModuleTest.php]: Actually, the tests are not isolated any more for the most part, there only a few ones I couldn't handle without isolationProcess

This is why there are two PHPUnit configs now, one with isolation and one without The tests classes use one or the other based on an `isolatedProcess` group that can be set easily on any class

Comment (jolelievre) [reply tests/Integration/Classes/module/ModuleTest.php]: Oh but I understand your comment now ^^ Since this specific class is still isolated it might be useless indeed I will test it out! Thanks

File: classes/module/Module.php (hunk 8 above)
Comment (jolelievre) [reply classes/module/Module.php]: Except in test environment I don't think this is useful indeed You're right that the `include_once` prevents loading a new class in the same process Maybe this will be needed someday But this is still useful for tests especially since all the module classes have a copied reference of the context

But so far only one test class uses this and as you said it's isolated so I'm gonna check if this is still useful, if not I'll clean it

**Comment by jolelievre** [comment]
Thanks @atomiix for the pertinent feedback!

I cleaned the code that was left from my previous attempt to switch all to "not isolated"
I still need to mock the context though, I'm not sure what it is needed now in ModuleTest but my guess is somehow other tests were impacting and initializing the context (even if they are supposed to be isolated 🤷‍♂️ )

**Review by atomiix — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: .github/workflows/behaviour.yml [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+        run: composer install --ansi --prefer-dist --no-interaction --no-progress
+
+      - name: Build theme assets
+        run: make front-classic
+
+      - name: Change MySQL authentication method
+        run: mysql -h127.0.0.1 -uroot -ppassword -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"
+
+      - name: Run integration-behaviour-tests
+        run: composer run-script integration-behaviour-tests --timeout=0
```
Comment (MeKeyCool) [inline .github/workflows/behaviour.yml:68]: idem

File: .github/workflows/behaviour.yml [hunk 10]
```diff
@@ -0,0 +1,70 @@
...
+        with:
+          path: ${{ steps.composer-cache.outputs.dir }}
+          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+          restore-keys: ${{ runner.os }}-composer-
+
+      - name: Composer Install
+        run: composer install --ansi --prefer-dist --no-interaction --no-progress
+
+      - name: Build theme assets
+        run: make front-classic
```
Comment (MeKeyCool) [inline .github/workflows/behaviour.yml:62]: I am not completely aware about github actions and good practices but, isn't this make command inside the run a security issue ?

For example, if the attacker replace his branch `make front-classic` command to print `GITHUB_TOKEN` wouldn't it be a problem ?

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

File: .gitignore [hunk 11]
```diff
@@ -87,6 +86,8 @@ tests/Resources/img/tmp/.gitkeep
 tests/Resources/download/*
 tests/Unit/.phpunit.result.cache
 .phpunit.result.cache
+tests/Integration/.phpunit.result.cache
+tests-legacy/.phpunit.result.cache
```
Comment (MeKeyCool) [inline .gitignore:90]: doesn't `**/.phpunit.result.cache` or `*.phpunit.result.cache` work for those four lines ?

File: Makefile [hunk 12]
```diff
@@ -5,3 +5,19 @@ composer:
...
+
+admin-default:
+	./tools/assets/build.sh admin-default
+
+admin-new-theme:
+	./tools/assets/build.sh admin-new-theme
+
+admin: admin-default admin-new-theme
+
+front: front-core front-classic
```
Comment (MeKeyCool) [inline Makefile:23]: If you are looking some polymorphism in your Makefile, i would recommend to use some simple "rule argument" solution and to enhance the script (adding admin and front arguments for examples) :

 ```Makefile
ARGS = `arg="$(filter-out $@,$(MAKECMDGOALS))" && echo $${arg:-${1}}`
# ARGS ?= assets # Add default value if it helps
build:
	@echo "build argument $(ARGS)"
	./tools/assets/build.sh $(ARGS)
	
# This rule is made to silence invalid rule call due to "rule argument hack"
%:
	@:
	# @echo "DEBUG : \`$@\` rule called." 
 ```
 Or add a question to the script to ask what subpart you want to build.

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php [hunk 13]
```diff
@@ -55,6 +57,11 @@ public function clear()
             return;
         }
 
+        if ($this->shutdownRegistered) {
+            return;
+        }
+
+        $this->shutdownRegistered = true;
```
Comment (MeKeyCool) [inline src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:64]: I don't like this boolean but I think i didn't understand well the whole context ^^'
Can't we use state or context instead of creating a new implicit state in this class ? (with all the side effects we could expect)

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 14]
```diff
@@ -1894,7 +1894,14 @@ private function getErrorMessages(Exception $e)
         }
 
         return [
-            CannotEditDeliveredOrderProductException::class => $this->trans('You cannot edit the cart once the order delivered.', 'Admin.Orderscustomers.Notification'),
+            ProductSearchEmptyPhraseException::class => $this->trans(
+                'Product search phrase must be a not empty string.',
```
Comment (MeKeyCool) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
                'Product search sentence must not be an empty string.',
```

File: .github/workflows/behaviour.yml (hunk 10 above)
Comment (atomiix) [reply .github/workflows/behaviour.yml:62]: Secrets are hidden when running a github action, no risk here AFAIK

File: Makefile (hunk 12 above)
Comment (atomiix) [reply Makefile:23]: Way less lisible IMO

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 14 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Indeed

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php (hunk 13 above)
Comment (jolelievre) [reply src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:64]: This indeed makes the class stateful, but I don't know if you noticed most of this class purpose is to register a shutdown function via `register_shutdown_function`

So regardless of how many times this cache method is called, the process can only stop once. However, without this check the shutdown callback could be executed several times which has absolutely no use. So this modification simply ensure that the callback is registered and executed only once

File: Makefile (hunk 12 above)
Comment (jolelievre) [reply Makefile:23]: I agree with @atomiix

File: .github/workflows/behaviour.yml (hunk 9 above)
Comment (jolelievre) [reply .github/workflows/behaviour.yml:68]: idem what? ^^

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

File: .github/workflows/behaviour.yml (hunk 9 above)
Comment (MeKeyCool) [reply .github/workflows/behaviour.yml:68]: Lol ! It looks it doesn't appear in same order than my review ^^'

Sorry for this, it was about my questions with security and github actions ^^'

File: .github/workflows/behaviour.yml (hunk 10 above)
Comment (MeKeyCool) [reply .github/workflows/behaviour.yml:62]: After discussing with @matks , it sounds obvious anybody can make anything in github actions to get it back (calling an api, writing some files, etc.) So the only way to secure it is to ensure that github_token won't give an admin access to the repository ^^'

File: Makefile (hunk 12 above)
Comment (MeKeyCool) [reply Makefile:23]: I think it is not a problem while your Makefile is few lines but this copy/past strategy won't scale ^^'

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php (hunk 13 above)
Comment (MeKeyCool) [reply src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:64]: :thinking: So if i understand well, you created a kind of singleton to give an anonymous static function to `register_shutdown_function`.

I didn't know `register_shutdown_function` function and with few researches it seems it is not that easy to get functions you already registered ^^'

But is your solution really satisfying ?

I mean if i call `new SymfonyCacheClearer()->clear()` won't it happen another function ?

If I understand well your subject, i think you may assume your singleton to not allowing bypassing state by cloning or constructing or anything else.

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php [hunk 15]
```diff
@@ -55,6 +57,11 @@ public function clear()
...
         register_shutdown_function(function () use ($kernel) {
             // The cache may have been removed by Tools::clearSf2Cache, it happens during install
```
Comment (MeKeyCool) [inline src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:66]: I just realised it thinking to this class implementation but why do we use an anonymous function here ?
To forbid any external access ?
Is it a technical debt ? A recommended implementation in Prestashop ?

This is typically the kind of domain behavior I would like to test so extracting it should be interesting ^^'

Comment (jolelievre) [reply src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:66]: `SymfonyCacheClearer ` is not supposed to be instanciated manually, it is only used in the core via its service definition so yes I assume it will not be instanciated by a module Even if it did we can't anticipate any unexpected thing a module is able to do, the list is just limitless

Regarding the anonymous function it's just that `register_shutdown_function` requires a callback method, so using an anonymous function is as good as a private function anyway so it's not worth blocking this and it's not even the purpose of the PR or the modification of this class

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @jolelievre
