### PR TITLE
BO - Customer View page - Added Green alert when editing a voucher

### LINKED ISSUE #18842: BO - Customer View page - there is no green alert after editing a voucher
#### Describe the bug

In the BO => Customers => Customer view page, when we try to edit a voucher, there is no alert
:heavy_check_mark: `Successful update.` displayed

#### Expected behavior

The green alert should be displayed like in the legacy page
image

#### Steps to Reproduce

1. Go to BO => Catalog => Discounts page
2. Add new cart rule for the "John DOE" customer
3. Go to BO => Customers => Customer view page "John DOE"
4. Try to edit a voucher
5. Click save
6. No alert displayed

#### Additional information

* PrestaShop version: 1.7.6.0, 1.7.6.5
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | BO - Customer View page - Added Green alert when editing a voucher.
| Type?         |  bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18842
| How to test?  | 1. Go to BO => Catalog => Discounts page<br>2. Add new cart rule for the "John DOE" customer<br>3. Go to BO => Customers => Customer view page "John DOE"<br>4. Try to edit a voucher<br>5. Click save<br>6. No alert displayed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18975)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 1]
```diff
@@ -840,4 +842,28 @@ private function getErrorMessages(Exception $e)
             ),
         ];
     }
+
+    /**
+     * Manage legacy flashes, this code must be removed
+     * when legacy edit will be migrated.
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Add a `@todo` maybe?

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 2]
```diff
@@ -266,6 +266,8 @@ public function viewAction($customerId, Request $request)
             'note' => $customerInformation->getGeneralInformation()->getPrivateNote(),
         ]);
 
+        $this->manageLegacyFlashes($request->query->get('conf'));
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
        if ($request->query->has('conf')) {
            $this->manageLegacyFlashes($request->query->get('conf'));
        }
```

And you can remove the empty check in `manageLegacyFlashes`.
Do not trigger unwanted calls.
Plus, since there is a check for `$messages[$messageId]` the `empty($messageId)` is not needed again

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Fixed ;)

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 2 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Fixed

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
