### PR TITLE
Fix: Front container lazy service declaration

### LINKED ISSUE #39555: Front container lazy service declaration
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There is an issue when you declare a service with lazy loading. If there is no service cache generated, the front page is loaded without any problem, but when you load the same page the second time, the container is already generatedm but module autoload file is not launched yet and we receive the exception, that class is not found:
```
Fatal error: Class "Testservice\Handler\OneHandler" not found in /site/var/cache/dev/FrontContainer.php line 1743
Stack trace:
#0 /site/src/Adapter/ContainerBuilder.php(160): require_once()
#1 /site/src/Adapter/ContainerBuilder.php(139): Adapter\ContainerBuilder->loadDumpedContainer()
#2 /site/src/Adapter/ContainerBuilder.php(107): Adapter\ContainerBuilder->buildContainer()
#3 /site/classes/Hook.php(1291): Adapter\ContainerBuilder::getContainer()
#4 /site/classes/Hook.php(853): HookCore::getHookModuleFilter()
#5 /site/classes/Hook.php(952): HookCore::getHookModuleExecList()
#6 /site/classes/Dispatcher.php(584): HookCore::exec()
#7 /site/classes/Dispatcher.php(235): DispatcherCore->loadRoutes()
#8 /site/classes/Dispatcher.php(193): DispatcherCore->__construct()
#9 /site/index.php(78): DispatcherCore::getInstance()
#10 {main}
Thrown in /site/var/cache/dev/FrontContainer.php line 1743
```

The lazy class is generated like that in FrontContaier:
```
class OneHandlerGhost37006b2 extends \Testservice\Handler\OneHandler implements \Symfony\Component\VarExporter\LazyObjectInterface
{
    use \Symfony\Component\VarExporter\LazyGhostTrait;

    private const LAZY_OBJECT_PROPERTY_SCOPES = [];
}

```
As you can see, the ghost class extends my lazy class, that should be loaded (autoload) while this container file is readed.
If I use experimental feature PS_FF_FRONT_CONTAINER_V2=true everything is fine, services a loaded correctly.

### Expected behavior

The exception should not be trown, we should load module autoload files earlier somehow to not generate the exception.

### Steps to reproduce

1. Create a new module
2. Declare a new lazy service in common.yml
3. Include this common.yml in front services.
4. Use this service in hook, for exemple in displayHeader.
5. Open the home page, container will be generated for the first time, everthing is OK.
6. Reload the page, you will see the exception that i added earlier.

You can test it. I created a simple module for test.
[testservice.zip](https://github.com/user-attachments/files/22299629/testservice.zip)

### PrestaShop version(s) where the bug happened

9.0.0

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

202 ecommerce

### PR DESCRIPTION
**Pull request by Codencode**
[Core] Fix lazy services: register module autoloaders before FrontContainer

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | There is an issue when you declare a service with lazy loading. If there is no service cache generated, the front page is loaded without any problem, but when you load the same page the second time, the container is already generatedm but module autoload file is not launched yet and we receive the exception, that class is not found
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install the module: [pr39572.zip](https://github.com/user-attachments/files/22363506/pr39572.zip) - 2. display the site homepage - 3. verify that there are no errors and that the message **Value of lazy service** is present
| UI Tests          | 🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/18281837331
| Fixed issue or discussion?     | Fixes #39555
| Related PRs       | 
| Sponsor company   | @Codencode 

The problem occurs because, when the container is already built, it is included before the module autoloaders are registered.
If a service is declared with `lazy: true`, the container generates a Ghost class that extends the service class. At this point PHP throws an error because the parent class has not yet been imported.
Note: this issue does not occur when enabling the experimental New front container feature.
The adopted solution is to register the module autoloaders before including the FrontContainer.
To achieve this, the method `ContainerBuilder::loadModulesAutoloader()` was modified so that it receives the list of installed modules without retrieving it from the container (which is only available after the container has been included).

This may not be the definitive solution, but it highlights the root cause of the issue and could help move towards a proper fix.

### CODE REVIEW

File: src/Adapter/ContainerBuilder.php [hunk 1]
```diff
@@ -136,11 +137,12 @@ public function buildContainer($containerName)
         // them at each container creation, this can't be compiled.
         $this->loadDoctrineAnnotationMetadata();
 
+        $moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+        $this->loadModulesAutoloader($moduleRepository->getInstalledModules());
```
Comment (jolelievre) [inline src/Adapter/ContainerBuilder.php:148]: Creating the `ModuleRepository` and fetching installed modules can have an impact on performance if we do it on each request Isn't it possible to first check if `'prestashop.installed_modules'` parameter is present?

Ah no because the container is not created yet.. So we're forced to fetch this list on each container creation then? That's too bad, I wonder how we could cache this differently somehow

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:148]: Besides that, the approach is fine, I just wonder how we could improve it a bit more

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: Unfortunately, yes. We are forced to retrieve the list of installed modules with every request.

As you yourself pointed out, we cannot retrieve the list from the container because when we need it, the container is not yet available.

The only solution I can think of is to manually store the list in a cache file.

Do you have any other ideas?

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: @jolelievre even in the `PS_FF_FRONT_CONTAINER_V2` mode, the list of installed modules is loaded with every request, which is why it doesn't throw an error!

The loading happens here:
https://github.com/PrestaShop/PrestaShop/blob/1a12f6ba8085258f0c884f89680ab936e626b1e6/app/AppKernel.php#L80-L86

So the "issue" of loading with every request would also exist in this mode

Comment (ChillCode) [reply src/Adapter/ContainerBuilder.php:148]: Since you're working on this part, what about using get active/enabled modules instead of installed?

Per [documentation](https://docs.prestashop-project.org/v.8-documentation/user-guide/improving-shop/managing-modules/modules-and-services/installed-modules) they shouldn't be loaded when the module is disabled but we are autoloading it's classes.

I had to this by my own since when testing modules that are almost the same but for two different customers so different module name a faced very strange behaviors until I completely  uninstalled one of them.

[EDIT]

After applied your patch to my dev install this has more sense:

```
        $moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
        $activeModules = $moduleRepository->getActiveModules();

        $this->loadModulesAutoloader($activeModules);
```

And removed the call inside the compileContainer.

Sorry if't out of context.

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: It could be an idea, but I don't know what impact it might have if we don't include the autoloaders of installed but inactive modules.

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: @jolelievre here: https://github.com/PrestaShop/PrestaShop/commit/d28f6b1f87a0295bbf1c5a056c64416184759b75 I implemented a "rudimentary" cache management to save the list of installed modules in the installed_modules.php file.
The entire part about deletion in case of cache clearance is missing.
What do you think?
Perhaps an improvement could be to apply the Singleton pattern to the InstalledModulesCacheManager class to centralize its usage.
If you think this approach is correct, I'll apply the commit to this PR. Also, which class should handle the deletion of the cache file?

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:148]: Hi @Codencode if you use a filesystem cache placed in the legacy cache folder (so using `prestashop.legacy_cache_dir` parameter or `_PS_CACHE_DIR_` legacy const), then you won't need to worry about the clearing of this cache since `LegacyCacheClearer` already removes all the files from this folder

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:148]: @Codencode yes it seems even in Symfony environments we always perform this query anyway, then maybe adding a cache right now is out of scope and overkill compared to the initial fix

We could add a class field cache to ensure the SQL query is done only once at least, but since `ModuleRepository` is created multiple times it wouldn't help in the end. And the last solution could be to use a static class field cache, but I'm not a big fan of this practice, that caused many drawbacks in the past

Ideally, we should have a `CacheModuleRepository` service/class that decorates the `ModuleRepository` and handles the caching, but it's an improvement in itself that probably extends the scope of this PR a bit too much

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: Hi @jolelievre 
>Hi @Codencode if you use a filesystem cache placed in the legacy cache folder (so using prestashop.legacy_cache_dir parameter or _PS_CACHE_DIR_ legacy const), then you won't need to worry about the clearing of this cache since LegacyCacheClearer already removes all the files from this folder

You're right, the cache would actually clear itself automatically!
>Ideally, we should have a CacheModuleRepository service/class that decorates the ModuleRepository and handles the caching, but it's an improvement in itself that probably extends the scope of this PR a bit too much

I'm not sure we can create a service because we need it before the container is created. We wouldn't be able to retrieve it without creating the container first.

I think this should be handled with a class that needs to be instantiated manually, like this solution: https://github.com/PrestaShop/PrestaShop/commit/d28f6b1f87a0295bbf1c5a056c64416184759b75
I would obviously need to rename the class.

What do you think?

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:148]: If you're going with the cache overlay system then ideally:
- we need an interface for ModuleRepositoryInterface, the current ModuleRepository would implement this class
- then we'd have a CachedModuleRepository that implements the same interface and decorates the ModuleRepository, meaning you pass the initial ModuleRepository in the constructor, on each interface methods call it checks if there is some cache available, if not it uses the decorated object that trully implements the logic behind (by calling the DB)
- you can define both as Symfony services so that they are easily usable in Symfony code
- you're not limited to Symfony services, you can use these classes even in legacy code, or in kernel code where the container is not available yet, it's just that you need to instanciate them manually in those cases

Ultimately, it would look like:

```php
$moduleRepository = new CachedModuleRepository(
    new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
    PS_CACHE_DIR
);
```

or if you want the cache decorator not to be aware of the caching strategy you can inject a Cache adapter instead:

```php
$cache = new AnyCacheAdapterForExampleFilesystem(PS_CACHE_DIR);
$moduleRepository = new CachedModuleRepository(
    new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
    $cache
);
```

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: >`$moduleRepository = new CachedModuleRepository(
    new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
    PS_CACHE_DIR
);

I'm missing something. Here, ModuleRepository, which should be this one: https://github.com/PrestaShop/PrestaShop/blob/9.0.x/src/Adapter/Module/Repository/ModuleRepository.php, does not implement the `ModuleRepositoryInterface` (https://github.com/PrestaShop/PrestaShop/blob/9.0.x/src/Core/Module/ModuleRepositoryInterface.php). Therefore, we cannot have `CachedModuleRepository `implementing this interface.

Perhaps instead of `src/Adapter/Module/Repository/ModuleRepository.php`, we should have `PrestaShop\PrestaShop\Core\Module\ModuleRepository` (https://github.com/PrestaShop/PrestaShop/blob/9.0.x/src/Core/Module/ModuleRepository.php) that implements the `ModuleRepositoryInterface`?
However, can we retrieve `PrestaShop\PrestaShop\Core\Module\ModuleRepository` without the container having already been compiled?

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: I implemented something that "approaches" your first solution, but it doesn't use the `ModuleRepositoryInterface` for the reasons I mentioned earlier.
You can find it here: https://github.com/PrestaShop/PrestaShop/commit/2d7ee10b359edc954a64f84232956b827f481cbb

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:148]: Oh I didn't know/remember there was already an existing `ModuleRepositoryInterface` that's interesting And it seems like there may have been a misuse of the `PrestaShop\PrestaShop\Adapter\Module\Repository\ModuleRepository` class, we probably should use the `PrestaShop\PrestaShop\Core\Module\ModuleRepository` class/service instead but maybe it's more complicated to use it for simple tasks like this in early kernel booting (manual instanciation may be troublesome when we simply need a list of installed modules)

But we can create another interface if needed for this specific use case, anyway the modifications in your commit seem interesting But can you please update this PR with this approach so that I can see the whole picture? and propose an alternative interface name that would fit our need

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:148]: @jolelievre, I have made the changes by introducing the new class PrestaShop\PrestaShop\Core\Module\CachedModuleRepository.
I await your feedback on the structure and the names.

Thanks

File: app/AppKernel.php [hunk 2]
```diff
@@ -77,7 +78,11 @@ public function registerBundles(): iterable
         }
 
         /* Will not work until PrestaShop is installed */
-        $installedModules = $this->getModuleRepository()->getInstalledModules();
+        $cachedRepository = new CachedModuleRepository(
```
Comment (jolelievre) [inline app/AppKernel.php]: You should move this into the `getModuleRepository` method

File: src/Adapter/Container/ContainerParametersExtension.php [hunk 3]
```diff
@@ -82,11 +83,15 @@ public function build(ContainerBuilder $container)
 
         // Init the active modules
         $moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+        $cachedRepository = new CachedModuleRepository(
```
Comment (jolelievre) [inline src/Adapter/Container/ContainerParametersExtension.php]: You can simplify this with a single variable:
```php
    $moduleRepository = new CachedModuleRepository(
        new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
        _PS_CACHE_DIR_
    );
```

File: src/Adapter/ContainerBuilder.php [hunk 4]
```diff
@@ -136,11 +138,15 @@ public function buildContainer($containerName)
         // them at each container creation, this can't be compiled.
         $this->loadDoctrineAnnotationMetadata();
 
+        $cachedRepository = new CachedModuleRepository(
```
Comment (jolelievre) [inline src/Adapter/ContainerBuilder.php]:
```suggestion
        $moduleRepository = new CachedModuleRepository(
```

File: src/Adapter/Module/Repository/CachedModuleRepository.php [hunk 5]
```diff
@@ -24,36 +24,41 @@
...
-use PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Attribute\ValueObject\AttributeId;
+namespace PrestaShop\PrestaShop\Core\Module;
 
-/**
- * Deletes attribute group by provided id
- */
-final class DeleteAttributeTextureImageCommand
+use PrestaShop\PrestaShop\Adapter\Module\Repository\ModuleRepository;
+
+class CachedModuleRepository
```
Comment (jolelievre) [inline src/Adapter/Module/Repository/CachedModuleRepository.php:33]: The principle is there, you have a cache class that wraps your `ModuleRepository` but I don't think you should implement the caching manually 

There are Symfony components that already handle this better than we do https://symfony.com/doc/current/components/cache.html So, instead, you should inject a `CacheInterface` in this constructor, this way your class doesn't know how we handle the cache, and it doesn't need to

When you use Symfony DI you just need to pass the `@cache.app` (or any sub adapters like `cache.adapter.filesystem`, `cache.adapter.memcached`, ...) in your service definition.

In your case since you don't have DI available in all cases, you'll need to create the classes manually, you can use `Symfony\Component\Cache\Adapter\FilesystemAdapter` adapter. For the FO container, you'll need to pass the legacy cache folder in its constructor for the FO.

For the `AppKernel` I'm not sure, either you can get the service from the container if it's available, if not you can also manually create a file cache adapter and use `$this->getCacheDir()` in the constructor.

File: src/Core/Module/CachedModuleRepository.php [hunk 6]
```diff
@@ -24,36 +24,41 @@
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  */
 
-namespace PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Command;
+declare(strict_types=1);
 
-use PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Attribute\Exception\AttributeConstraintException;
-use PrestaShop\PrestaShop\Core\Domain\AttributeGroup\Attribute\ValueObject\AttributeId;
+namespace PrestaShop\PrestaShop\Core\Module;
```
Comment (jolelievre) [inline src/Core/Module/CachedModuleRepository.php]: I'm not even sure it should be in the Core namespace, because it doesn't implement a core interface and it's not a pure decorator since it doesn't implement all the methods from the decorated repository

Besides it's a wrapper of an adapter service that is a mix between Doctrine connection and ObjectModel and is bound to disappear someday, so all these things combined mean it's not really a candidate for clean code in the core

You should probably move this class in the adapter namespace in `PrestaShop\PrestaShop\Adapter\Module\Repository`

Comment (Codencode) [reply src/Core/Module/CachedModuleRepository.php]: @jolelievre 
I made the changes, I hope I didn't forget anything:
I changed the namespace of the `CachedModuleRepository` class to `PrestaShop\PrestaShop\Adapter\Module\Repository` as you suggested - it really didn't make sense to have it in `Core`.
I modified the cache handling like this (I'm not entirely sure about my implementation):
```php
new CachedModuleRepository(
    new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
    new Psr16Cache(
        new FilesystemAdapter('modules', 0, _PS_CACHE_DIR_)
    )
)
```

I'm not clear about this part:
> For the AppKernel I'm not sure, either you can get the service from the container if it's available, if not you can also manually create a file cache adapter and use $this->getCacheDir() in the constructor.

Thanks!

Comment (ChillCode) [reply src/Core/Module/CachedModuleRepository.php]: Hi @Codencode 

This is how I implemented a cache temporally when applied your patch, it's just for dev purposes and to check if a cache is faster than 0.0040s it took reading from DB on my setup, and is not faster but in prod it might be, but initializing  `FilesystemAdapter` was even slower than `ModuleRepository`, but again this is just my setup.

```
        $cache = new FilesystemAdapter('ps_active_modules', 0, $this->environment->getCacheDir());

        $activeModules = $cache->get('active_modules', function ($item) {
            $moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
            return $moduleRepository->getActiveModules();
        });
```

I used active modules but this snippet is just to show that `FilesystemAdapter` has all needed interfaces already implemented.

Great job!

File: src/Adapter/Module/Repository/CachedModuleRepository.php [hunk 7]
```diff
@@ -0,0 +1,79 @@
...
+namespace PrestaShop\PrestaShop\Adapter\Module\Repository;
+
+use Psr\SimpleCache\CacheInterface;
+
+class CachedModuleRepository
+{
+    private $decorated;
+    private $cache;
+
+    public function __construct(ModuleRepository $decorated, CacheInterface $cache)
```
Comment (jolelievre) [inline src/Adapter/Module/Repository/CachedModuleRepository.php:38]: I think you can use `Symfony\Contracts\Cache\CacheInterface` insted here, this way you won't need the extra layer of `Psr16Cache`

File: src/Adapter/Module/Repository/CachedModuleRepository.php [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+
+        if (!$values) {
+            $values = $this->decorated->getInstalledModules();
+            $this->cache->set('installed_modules', $values);
+        }
+
+        return $values;
+    }
+
+    public function getPresentModules(): array
```
Comment (jolelievre) [inline src/Adapter/Module/Repository/CachedModuleRepository.php:51]: Wah nice! This way, even the cache instance can be used in other use cases in the future

File: src/Adapter/Module/Repository/CachedModuleRepository.php [hunk 9]
```diff
@@ -0,0 +1,79 @@
...
+    {
+        $values = $this->cache->get('present_modules');
+
+        if (!$values) {
+            $values = $this->decorated->getInstalledModules();
```
Comment (jolelievre) [inline src/Adapter/Module/Repository/CachedModuleRepository.php]:
```suggestion
            $values = $this->decorated->getPresentModules();
```

File: src/Adapter/Module/Repository/CachedModuleRepository.php [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+
+        return $values;
+    }
+
+    public function getActiveModules(): array
+    {
+        $values = $this->cache->get('active_modules');
+
+        if (!$values) {
+            $values = $this->decorated->getInstalledModules();
```
Comment (jolelievre) [inline src/Adapter/Module/Repository/CachedModuleRepository.php]:
```suggestion
            $values = $this->decorated->getActiveModules();
```

File: src/Core/Module/CachedModuleRepository.php (hunk 6 above)
Comment (jolelievre) [reply src/Core/Module/CachedModuleRepository.php]: What I meant was instead of manually creating the Cache instance in the kernel maybe you could do something like:
```php
new CachedModuleRepository(
    new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
    $container->get('cache.adapter.filesystem'),
)
```

But after checking, I think we're in the same situation as in the FO ContainerBuilder and the container is not available yet when we get the list of modules, so forget about it 😉

**Review by jolelievre — COMMENTED** [review]
Thanks @Codencode 

Only one last simplification to drop the `Psr16Cache` and I think it should be good.

Out of curiosity (and safety) can you check that the cache is correctly created for Symfony and for FO (logically intehir respective cache folder), and that it is correctly cleaned when we clear symfony cache as well (from the BO and from the CLI)?

File: src/Core/Module/CachedModuleRepository.php (hunk 6 above)
Comment (Codencode) [reply src/Core/Module/CachedModuleRepository.php]: Yes, we still need the container, which is not yet available, so as you said, let's forget about it 😄

File: src/Adapter/Module/Repository/CachedModuleRepository.php (hunk 9 above)
Comment (Codencode) [reply src/Adapter/Module/Repository/CachedModuleRepository.php]: Yes, here I did a bit of copy and pasting and didn't update the method name!

File: src/Adapter/Module/Repository/CachedModuleRepository.php (hunk 8 above)
Comment (Codencode) [reply src/Adapter/Module/Repository/CachedModuleRepository.php:51]: Yes, and then I was forced to do it because in `AppKernel `the methods `getPresentModules()` and `getActiveModules()` are already called, and if I hadn't implemented them, it would have thrown an error.

File: src/Adapter/Module/Repository/CachedModuleRepository.php (hunk 10 above)
Comment (Codencode) [reply src/Adapter/Module/Repository/CachedModuleRepository.php]: @jolelievre I've changed the interface as you suggested. I admit I was too hasty when making the previous change and didn't think it through properly - fortunately you gave me an excellent suggestion!

I've done some tests which I'm attaching:

### Clearing cache from the admin panel

[clear-cache-from-admin.webm](https://github.com/user-attachments/assets/a7e81f19-c166-47a3-866f-29cb364edbb4)

---
### Clearing cache from the console
[clear-cache-from-console.webm](https://github.com/user-attachments/assets/a81f6479-439e-46c7-a2f5-0264d500e74e)

---
### Switching from "debug" mode to production mode to show that the file is created in the correct folder

[switch-debug-mode.webm](https://github.com/user-attachments/assets/75ea14a1-0796-4956-b7e8-96c97a95146b)

---
Looking forward to your feedback.

Thanks again!

File: config/defines.inc.php [hunk 11]
```diff
@@ -33,7 +33,7 @@
  * The code below can be also managed by settings in backoffice. The interface hardcodes the value into this file.
  */
 if (!defined('_PS_MODE_DEV_')) {
-    define('_PS_MODE_DEV_', true);
+    define('_PS_MODE_DEV_', false);
```
Comment (jolelievre) [inline config/defines.inc.php]: Probably a dev modification that you pushed by mistake

File: app/AppKernel.php [hunk 12]
```diff
@@ -300,10 +302,13 @@ public function getProjectDir(): string
...
     }
 
-    protected function getModuleRepository(): ModuleRepository
+    protected function getModuleRepository(): CachedModuleRepository
     {
         if ($this->moduleRepository === null) {
-            $this->moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+            $this->moduleRepository = new CachedModuleRepository(
+                new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_),
+                new FilesystemAdapter('modules', 0, _PS_CACHE_DIR_)
```
Comment (jolelievre) [inline app/AppKernel.php]:
```suggestion
                new FilesystemAdapter('modules', 0, $this->getCacheDir())
```

Comment (jolelievre) [reply app/AppKernel.php]: The tests are failing, probably because of the cache system now in place Since the tests modify the installed modules the values are not updated anymore

To overcome this issue you need to change the cache adapter in test environment:

```php
if ($this->environment === 'test') {
    // This cache is equivalent to no cache, in test environment we don't want the value to be cached
    $cache = new NullAdapter();
} else {
    $cache = new FilesystemAdapter(...);
}
```

That's where we see that relying on the `CacheInterface` is already relevant to adapt our use cases, and you probably need to implement something similar in the FO ContainerBuilder.

Let's hope that with this modification the tests will be green again

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/Adapter/Module/Repository/CachedModuleRepository.php (hunk 10 above)
Comment (jolelievre) [reply src/Adapter/Module/Repository/CachedModuleRepository.php]: Thanks, seems good!

File: app/AppKernel.php (hunk 12 above)
Comment (Codencode) [reply app/AppKernel.php]: @jolelievre I've made the changes, I hope I understood correctly.
We're waiting for the tests!

File: app/AppKernel.php [hunk 13]
```diff
@@ -300,10 +303,18 @@ public function getProjectDir(): string
         return realpath(__DIR__ . '/..');
     }
 
-    protected function getModuleRepository(): ModuleRepository
+    protected function getModuleRepository(): CachedModuleRepository
     {
-        if ($this->moduleRepository === null) {
-            $this->moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+        if ($this->moduleRepository === null) {//TODO <cnc-notice> DA TESTARE - OK
+            if ($this->environment === 'test') {
```
Comment (jolelievre) [inline app/AppKernel.php]:
```suggestion
            if ($this->getEnvironment() === 'test') {
```
Actually this would probably be cleaner here

File: src/Adapter/Container/ContainerParametersExtension.php [hunk 14]
```diff
@@ -81,7 +84,15 @@ public function build(ContainerBuilder $container)
         $container->setParameter('kernel.cache_dir', $this->environment->getCacheDir());
 
         // Init the active modules
-        $moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+        if ($this->environment === 'test') {//TODO <cnc-notice> DA TESTARE - OK
```
Comment (jolelievre) [inline src/Adapter/Container/ContainerParametersExtension.php]:
```suggestion
        if ($this->environment->getName() === 'test') {//TODO <cnc-notice> DA TESTARE - OK
```

File: src/Adapter/ContainerBuilder.php [hunk 15]
```diff
@@ -136,11 +140,20 @@ public function buildContainer($containerName)
         // them at each container creation, this can't be compiled.
         $this->loadDoctrineAnnotationMetadata();
 
+        if ($this->environment === 'test') {//TODO <cnc-notice> DA TESTARE - OK
```
Comment (jolelievre) [inline src/Adapter/ContainerBuilder.php]:
```suggestion
        if ($this->environment->getName() === 'test') {//TODO <cnc-notice> DA TESTARE - OK
```

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php]: Also, I noticed there is a `@deprecated` on the top of this class, I think you can remove it because we are from having Symfony on the FO so this class shouldn't be removed anytime soon

**Review by jolelievre — COMMENTED** [review]
Thanks @Codencode yep you understood it correctly

Just some last small things to fix, because `$this->environment` is not always a string in all the modified classes (I'm surprised PHPstan said nothing about it). And a little CS fix to apply and we should be good, the CI seems to be green again

Once you fixed these last things, I think you can relaunch the UI tests completely but it smells good.

Thanks for the extensive work, it was not an easy bugfix, and my instructions were quite strict 😅 But in the end, I think you reached the optimal solution

File: src/Adapter/Container/ContainerParametersExtension.php (hunk 14 above)
Comment (Codencode) [reply src/Adapter/Container/ContainerParametersExtension.php]: @jolelievre,
I've made the changes. Yes, I had imagined that the tests would need to be restarted. Thanks for pointing that out.

Your instructions are correct, and I compliment you because nothing escapes your attention, and you are very precise in giving the right instructions. So, don't worry, no problem at all.

The real issue is that I've been a bit careless these days. I'm working on this PR alongside my job, and I often overlook things, like leaving comments in the code 😅. I hope you'll forgive me 😄.

Also, in the end, I think it would be better to squash all the commits into one to keep things a bit more organized.

File: app/AppKernel.php [hunk 16]
```diff
@@ -300,10 +303,18 @@ public function getProjectDir(): string
...
     }
 
-    protected function getModuleRepository(): ModuleRepository
+    protected function getModuleRepository(): CachedModuleRepository
     {
         if ($this->moduleRepository === null) {
-            $this->moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+            if ($this->getEnvironment() === 'test') {
+                $cache = new NullAdapter();
+            } else{
```
Comment (jolelievre) [inline app/AppKernel.php]:
```suggestion
            } else {
```

File: src/Adapter/Container/ContainerParametersExtension.php [hunk 17]
```diff
@@ -81,7 +84,15 @@ public function build(ContainerBuilder $container)
         $container->setParameter('kernel.cache_dir', $this->environment->getCacheDir());
 
         // Init the active modules
-        $moduleRepository = new ModuleRepository(_PS_ROOT_DIR_, _PS_MODULE_DIR_);
+        if ($this->environment->getName() === 'test') {
+            $cache = new NullAdapter();
+        } else{
```
Comment (jolelievre) [inline src/Adapter/Container/ContainerParametersExtension.php]:
```suggestion
        } else {
```

File: src/Adapter/ContainerBuilder.php [hunk 18]
```diff
@@ -136,11 +135,20 @@ public function buildContainer($containerName)
         // them at each container creation, this can't be compiled.
         $this->loadDoctrineAnnotationMetadata();
 
+        if ($this->environment->getName() === 'test') {
+            $cache = new NullAdapter();
+        } else{
```
Comment (jolelievre) [inline src/Adapter/ContainerBuilder.php]:
```suggestion
        } else {
```

File: src/Adapter/Container/ContainerParametersExtension.php (hunk 14 above)
Comment (jolelievre) [reply src/Adapter/Container/ContainerParametersExtension.php]: Haha, nothing to feel sorry about
You already take some of your personal time to improve the project, so thank you 😉

**Review by jolelievre — COMMENTED** [review]
Just a few lint errors to fix for CS fixer
Or you can run `composer run php-cs-fixer` to let it fix them for you

And if you can squash the commits after you're done with cs fixer then it will be perfect 😉

**Review by jolelievre — DISMISSED** [review]
Thanks @Codencode

**Comment by Codencode** [comment]
@jolelievre I also recreated the UI Tests: https://github.com/Codencode/ga.tests.ui.pr/actions/runs/18281837331

**Comment by Codencode** [comment]
UI Tests are green 🟢

**Comment by Codencode** [comment]
Ping @PrestaShop/committers

**Comment by jolelievre** [comment]
@Codencode you need to rebase and fix the conflicts ;)

**Comment by Codencode** [comment]
@jolelievre rebase completed.

Thank you!

**Review by jolelievre — APPROVED** [review]
Thanks @Codencode

**Comment by jolelievre** [comment]
@boherm @nicosomb @tleon @tyloo could one of you please review this one?

File: src/Adapter/ContainerBuilder.php [hunk 19]
```diff
@@ -49,11 +53,6 @@
 use Symfony\Component\DependencyInjection\Dumper\PhpDumper;
 use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
 
-/**
- * Build the Container for PrestaShop Legacy.
- *
- * @deprecated since 9.0. Please use SymfonyContainer instead.
- */
```
Comment (kpodemski) [inline src/Adapter/ContainerBuilder.php:56]: @Codencode did I miss something? Why was this deprecation removed?

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:56]: I asked to remove it because it doesn't make sense to deprecate this, it's still fully used in the FO and it will be until the FO is migrated, so not any time soon

Comment (Codencode) [reply src/Adapter/ContainerBuilder.php:56]: @kpodemski As @jolelievre already informed you, he was the one who asked me to do it :)

Comment (jolelievre) [reply src/Adapter/ContainerBuilder.php:56]: @kpodemski if it's ok with you don't hesitate to approve the PR so it can go to QA 😉

**Review by kpodemski — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Codencode, 

Thanks for your PR, i tested it and it's good for me :) 
Capture d’écran 2025-11-12 à 19 05 31

Thanks

**Review by SiraDIOP — APPROVED** [review]
