### PR TITLE
Try to use the real command to clear the cache when the kernel is available

### LINKED ISSUE #11105: In BO page Advanced Parameters / Performance, if we click twice on the Clear cache, user sees a 500 error page
**Describe the bug**
In the Advanced Parameters / Performance, if we click twice on the Clear cache button => Error 500

**To Reproduce**
1. Go to BO =>  Advanced Parameters / Performance 
2. Click on "Clear Cache" button 2 times
3. See error : Actual: Error 500

**Screenshots**
https://drive.google.com/file/d/1cJrW2c5kEbaDvKEbuZA7m74egEzV5UET/view

66586071-4eb3da00-eb88-11e9-9b4c-94159bc15522

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

---
Update 2020-08-04 This is clearly a race condition when two processes are cleaning/rebuilding the cache at the same time.

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Use Symfony command `cache:clear` instead of an hard `rm -rf` against the `var/cache` directory. It's maybe not the best way to do it.
| Type?         | bug fix
| Category?     | CO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11105
| How to test?  | Follow ticket instruction.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20689)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php [hunk 1]
```diff
@@ -41,6 +45,23 @@ final class SymfonyCacheClearer implements CacheClearerInterface
      */
     public function clear()
     {
-        Tools::clearSf2Cache();
+        /*  @var KernelInterface */
+        global $kernel;
+
+        if (empty($kernel)) {
```
Comment (eternoendless) [inline src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:52]: There's a hook in `Tools::clearSf2Cache()` that will never be called.

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @PierreRambaud 

Found an issue testing this PR: 
Go to BO => Advanced Parameters / Performance
Click on "Clear Cache" button 2 times
See error : Actual: Error 500

I get this error: https://drive.google.com/file/d/1PXFJBjp6tXYlg_q8480_7K7pmhDqDgK5/view
Capture d’écran 2020-09-02 à 15 06 32

**Comment by PierreRambaud** [comment]
> Hello @PierreRambaud
> 
> Found an issue testing this PR:
> Go to BO => Advanced Parameters / Performance
> Click on "Clear Cache" button 2 times
> See error : Actual: Error 500
> 
> I get this error: https://drive.google.com/file/d/1PXFJBjp6tXYlg_q8480_7K7pmhDqDgK5/view
> Capture d’écran 2020-09-02 à 15 06 32

Is it occurred everytime you double click on the button? :thinking: This problem also happened for me when I clicked too fast others links :sweat_smile:

**Comment by ngodefroy** [comment]
> > Hello @PierreRambaud
> > Found an issue testing this PR:
> > Go to BO => Advanced Parameters / Performance
> > Click on "Clear Cache" button 2 times
> > See error : Actual: Error 500
> > I get this error: https://drive.google.com/file/d/1PXFJBjp6tXYlg_q8480_7K7pmhDqDgK5/view
> > Capture d’écran 2020-09-02 à 15 06 32
> 
> Is it occurred everytime you double click on the button? 🤔 This problem also happened for me when I clicked too fast others links 😅

Yes.. Asked @khouloudbelguith  to double check and same for her, see video:
https://drive.google.com/file/d/1jwF55Rm-CK17wSVzXkpy8pk15WivL1hw/view?usp=sharing

**Comment by PierreRambaud** [comment]
> > > Hello @PierreRambaud
> > > Found an issue testing this PR:
> > > Go to BO => Advanced Parameters / Performance
> > > Click on "Clear Cache" button 2 times
> > > See error : Actual: Error 500
> > > I get this error: https://drive.google.com/file/d/1PXFJBjp6tXYlg_q8480_7K7pmhDqDgK5/view
> > > Capture d’écran 2020-09-02 à 15 06 32
> > 
> > 
> > Is it occurred everytime you double click on the button? thinking This problem also happened for me when I clicked too fast others links sweat_smile
> 
> Yes.. Asked @khouloudbelguith to double check and same for her, see video:
> https://drive.google.com/file/d/1jwF55Rm-CK17wSVzXkpy8pk15WivL1hw/view?usp=sharing

I don't manage to reproduce your issue. Are you using docker? :thinking:

**Comment by ngodefroy** [comment]
@PierreRambaud 
I am not on Docker so is Khouloud.. I tried to test on another navigator to double check: same behavior, I get a 404 error.

@khouloudbelguith doesnt reproduce.. how do we do ?^^

**Comment by PierreRambaud** [comment]
> @PierreRambaud
> Je ne suis pas sur Docker (khouloud non plus), j'ai réessayé de tester sur un autre navigateur pour confirmer, toujours le meme pb, j'ai une 404.
> @khouloudbelguith ne reproduit pas... on fait comment ?^^

I don't know what we should do. If you have a problem, someone can also have the same.
What is your server configuration? Apache / Nginx? PHP fpm?

**Comment by ngodefroy** [comment]
> > @PierreRambaud
> > Je ne suis pas sur Docker (khouloud non plus), j'ai réessayé de tester sur un autre navigateur pour confirmer, toujours le meme pb, j'ai une 404.
> > @khouloudbelguith ne reproduit pas... on fait comment ?^^
> 
> I don't know what we should do. If you have a problem, someone can also have the same.
> What is your server configuration? Apache / Nginx? PHP fpm?

Apache, let me modify the memory limit and max execution time to see if that helps..

**Comment by ngodefroy** [comment]
@PierreRambaud  Thanks to the advice of @khouloudbelguith, I modified memory limit to 10000M (instead of 128) & max execution time to 60 (instead of 30) and it worked just fine ! 
Capture d’écran 2020-09-02 à 18 35 03
You can close the issue :)

**Comment by Progi1984** [comment]
Thanks @PierreRambaud & @ngodefroy

**Comment by ghost** [comment]
An error 500 on a double click on a clear cache still present on a demo site https://demo.prestashop.com/#/en/back (PS 1.7.7.0). So whether the problem fixed or not? Setting 10Gb memory limit as advised above on a 2 Gb webserver doesn't look like a solution for me.
