### PR TITLE
AppKernel is now able to detect the admin folder

### LINKED ISSUE #35354: Hardcoded path in config: The "/var/www/html/admin-dev/themes/new-theme" directory does not exist
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello there,

Modifying the admin folder on the nightly build makes the BO fail. This seems to be caused by a hardcoded path in the config files with `admin-dev` I found in this [commit](https://github.com/PrestaShop/PrestaShop/commit/1b70d5a7637fa11fa12a03dbf5b18a625c1353ea#diff-58ea7cc56899a1bcf3bdb6fc0d9cee247056d8e8ffc845a8ee8648f24ed7c3e8R89).

image

### Expected behavior

I expect the Back-office to work even if I rename my `admin-dev` folder.

### Steps to reproduce

1. Install the nightly with a folder `admin-dev` present (if you rename it prior installation, it will fail)
2. Access your back office. It should load
3. Rename `admin-dev` as anything you want
4. Access your back ffice. It should load

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | AppKernel is now able to detect the admin folder in case the PS_ADMIN_DIR is not defined, the admin dir path is now set in the `prestashop.admin_dir` parameter that must be favored from now on in DI
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and UI tests green, see description below for manual checks
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7962314884
| Fixed issue or discussion?     | Fixes #35354
| Related PRs       | ~
| Sponsor company   | ~

### Steps to reproduce
1. Install the nightly with a folder admin-dev present (if you rename it prior installation, it will fail)
2. Access your back office. It should load
3. Rename admin-dev as anything you want
4. Access your back ffice. It should load

### Alternative:
You can use `./bin/console debug:container --parameters` and check that `prestashop.admin_dir` and `prestashop.admin_folder_name` are correctly updated when the admin folder is renamed In dev environment it should be automatic thanks to the resource checking, but in prod you probably have to clean the cache after every modification

### CODE REVIEW

File: app/AppKernel.php [hunk 1]
```diff
@@ -222,12 +223,53 @@ public function registerContainerConfiguration(LoaderInterface $loader)
...
+                        }
+
+                        return strcmp($a->getRealPath(), $b->getRealPath());
+                    })
+                    ->in($this->getProjectDir())
+                ;
+                foreach ($finder as $adminIndexFile) {
+                    $adminDir = $adminIndexFile->getPath();
+                    // Container freshness depends on this file existence
+                    $container->addResource(new FileExistenceResource($adminIndexFile->getRealPath()));
```
Comment (matthieu-rolland) [inline app/AppKernel.php:261]: nice, I didn't know about this `FileExistenceResource` feature

**Review by matthieu-rolland — APPROVED** [review]

File: app/AppKernel.php (hunk 1 above)
Comment (jolelievre) [reply app/AppKernel.php:261]: Yep me neither, just found out about it!

**Review by FabienPapet — APPROVED** [review]

**Comment by FabienPapet** [comment]
Less coupling to legacy constants, nice !

**Comment by matthieu-rolland** [comment]
@jolelievre I guess this can be merged as long as CI and ui tests are fine ?

there's only one UI test failing, but it doesn't look like it's related to your PR

**Comment by jolelievre** [comment]
@FabienPapet yep, step by step 😅
I'll propose a refacto PR after this one is merged to clean the modern code

File: app/AppKernel.php (hunk 1 above)
Comment (PululuK) [inline app/AppKernel.php:261]: Nice @jolelievre, thanks :) 
I think we should put this in a dedicated function or class

**Review by PululuK — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @jolelievre 

Thank you for your PR, I tested it and it seems to works as you can see : 

image

image


Link to the auto test : https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7962314884

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

File: app/AppKernel.php (hunk 1 above)
Comment (jolelievre) [reply app/AppKernel.php:261]: There's room for a small refacto indeed, I guess it will have to be done in a dedicated PR then
