### PR TITLE
Optimize product page

### LINKED ISSUE #34455: Very slow loading of admin product page due to product features
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/31782

<div type='discussions-op-text'>

<sup>Originally posted by **ioweb-gr** March 11, 2023</sup>
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

We have a website with fairly large products with combinations packed with features. Most of our products have over 60 features active (with more than 20 possible values  per feature)  and some have combinations of over 40 colors and 10 sizes and there are more than 40 images as well per product. 

### Expected behavior

Improvement of the performance by reducing the number of queries

### Steps to reproduce

1. Create a product with combinations of 40 colors and 10 sizes
2. Add 40+ images to the product
3. Add two languages
4. Create 60+ features with at least 20 feature values per feature
5. Set values to the product for all features 
6. Try to edit the product in the backend in any browser and watch it freeze. 

### Appendix 

When trying to edit the product in the backend we face extreme slowdown and browser freezing. 
It can take more than 5 minutes to give control to the user, until the interface becomes responsive and fully loaded. 

Microsoft edge profiler, reports loops of rendering layout which takes more than 2-3 seconds I'm assuming for each new feature it causes layout shift and re-render. 

Moreover, we profiled prestashop and noticed there are fairly large execution times just to load the form, apart from rendering it in the browser. 

e.g. a request like this 

image

is repeated 3 times with total execution of over 10 seconds to fetch the combinations with the timeline like this

image

Also the actual request to fetch the product in admin is taking more than 34 seconds

image

With the timeline showing some very specific delays in evaluating twig templates for display

image
image

The server is a 12core dedicated server with 64G RAM and Nvme disk and the load is very low so we can exclude server performance 
image

### PrestaShop version(s) where the bug happened

1.7.5.2

### PHP version(s) where the bug happened

7.2/7.3

### If your bug is related to a module, specify its name and its version

Prestashop Features</div>

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Optimize the feature values fetching in product page to reduce the number of requests and the memory usage
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7084101479
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | ~

## Condition of tests

I used this module to generate the data in which to improvements have been added:
https://github.com/PrestaShop/PsFixturesCreator/pull/4
https://github.com/PrestaShop/PsFixturesCreator/pull/5

Then used the command from the module to generate a product with a lot of features:
```bash
./bin/console prestashop:product-creator --productsWithCombinations=1 --features=12 --featureValues=12
./bin/console prestashop:product-creator --productsWithCombinations=1 --features=65 --featureValues=25
```

Then the product page in BO was tested (only the new product page from 8.1, not the legacy one) and Blackfire was used to extract some metrics displayed in the following tables.

### Tests in prod mode
| Metric | Number of feature values | Without optimization | With optimization |
| ------ | -------------------------- | --------------------- | ----------------- |
| Time | 12x12 | 6.51s | 5.91s |
| Memory peak usage |   | 73.6Mb | 67.1Mb |
| SQL Queries |   | 497 ms / 2 354 rq | 322 ms / 207 rq |
| Time | 2 but feature has 1000 values | 2.4s | 1.88s |
| Memory peak usage |   | 35.4Mb | 30.7Mb |
| SQL Queries |   | 630 ms / 2 201 rq | 67.7 ms / 197 rq |
| Time | 65x25 | 1m15s | 48.7s |
| Memory peak usage |   | 594Mb | 466Mb |
| SQL Queries |   | 11.9 s / 45 694 rq | 337 ms / 325 rq |

### Tests in dev mode
In dev mode the metrics explode (especially the memory usage) because many things are profiles by Symfony for debug toolbar probably and it prevents using Blackfire for monitoring

| Metric | Number of feature values | Without optimization | With optimization |
| ------ | -------------------------- | --------------------- | ----------------- |
| Time | 12x12 | 26.3s | 20.2s |
| Memory peak usage |   | 306Mb | 281Mb |
| SQL Queries |   | 3.18 s / 2 354 rq | 378 ms / 219 rq |
| Time | 65x25 | No blackfire | No blackfire |
| Memory peak usage |   | No blackfire | No blackfire |
| SQL Queries |   | No blackfire | No blackfire |

## Conclusion

Even though these optimizations improve the performance a bit they are far from enough to handle a product with hundreds o even thousands of features The number of queries and memory related to all this data is one thing, but it seems most of the memory usage comes from having hundreds/thousands of small form types and also the twig rendering all those form types

I advise reworking this feature with an ajax component instead, similar to what as done for combinations, I don't know if pagination would be relevant or not though Maybe the list of features could still be fetched along with the form just for display, maybe not a good idea maybe even the display should be fetched by ajax But the edition itself anyway MUST be handled by ajax so we don't have thousands of inputs in the page, because regardless of the tremendous cost on server side there's even a huge cost for the browser on the client side

### CODE REVIEW

**Comment by Hlavtox** [comment]
@jolelievre Features and feature values must be ordered by name, like on the old page. 👍

File: src/Adapter/Form/ChoiceProvider/FeatureValuesChoiceProvider.php [hunk 1]
```diff
@@ -74,6 +74,7 @@ public function getChoices(array $options)
         if (isset($options['custom'])) {
             $filters['custom'] = $options['custom'];
         }
+        $filters['id_lang'] = $options['id_lang'] ?? $this->contextLanguageId;
```
Comment (Hlavtox) [inline src/Adapter/Form/ChoiceProvider/FeatureValuesChoiceProvider.php]: Fetching it only in one language will prevent the conditions below from working, there are some fallbacks if the entry doesn't exist in that language.

However, I think that there should ALWAYS be a language entry.

**Comment by jolelievre** [comment]
> @jolelievre Features and feature values must be ordered by name, like on the old page. 👍

In the new product page the features and feature values are ordered by position, this was added on purpose If we want to change this functional behaviour I let you talk about it with @PrestaShop/product-council but that's not the purpose of this issue/PR so I prefer to focus on optimization for now

File: src/Adapter/Feature/Repository/FeatureValueRepository.php [hunk 2]
```diff
@@ -205,26 +212,27 @@ public function getFeatureValuesCount(?array $filters = []): int
...
      */
-    private function getFeatureValueLocalizedValues(int $featureValueId): array
+    private function getFeatureValueLocalizedValues(array $featureValuesIds, ?int $langId): array
     {
         $qb = $this->connection->createQueryBuilder();
         $qb->from($this->dbPrefix . 'feature_value_lang', 'fvl')
             ->select('fvl.*')
-            ->where('fvl.id_feature_value= :featureValueId')
-            ->setParameter('featureValueId', $featureValueId)
+            ->where('fvl.id_feature_value IN(:featureValueIds)')
```
Comment (Hlavtox) [inline src/Adapter/Feature/Repository/FeatureValueRepository.php:273]: This is not very good, merchant will have 1000 feature values and we will be passing the whole list in the query?

The whole list can be fetched by one fast query like I did here https://github.com/PrestaShop/PrestaShop/issues/34455#issuecomment-1792211164 👍

**Comment by Hlavtox** [comment]
@jolelievre Feature values don't have a position, they must be sorted alphabetically. 
`>orderBy('f.position, fv.id_feature_value', 'ASC')` this basically sorts them by ID, because the position of the parent feature is still the same.

File: src/Adapter/Form/ChoiceProvider/FeatureValuesChoiceProvider.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/FeatureValuesChoiceProvider.php]: Yep right, I modified it a bit to fetch potential multiple languages but maximum two

File: src/Adapter/Feature/Repository/FeatureValueRepository.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/Feature/Repository/FeatureValueRepository.php:273]: I think the query has been split because the initial query handles pagination and adding multiple joins in the query would completely mess with the pagination count and offsets

**Comment by jolelievre** [comment]
> @jolelievre Feature values don't have a position, they must be sorted alphabetically. `>orderBy('f.position, fv.id_feature_value', 'ASC')` this basically sorts them by ID, because the position of the parent feature is still the same.

I believe this is mostly to "group" the returned values by feature parent and keep a consistent return for expected tests results, but I'll try to add a sort in the choice provider instead

File: src/Adapter/Feature/Repository/FeatureValueRepository.php (hunk 2 above)
Comment (Hlavtox) [reply src/Adapter/Feature/Repository/FeatureValueRepository.php:273]: Can we just make a separate method to fetch it in a fast way? Do we need all of this code to run this query? :-)

```
SELECT fvl.* FROM ps_feature_value_lang fvl
LEFT JOIN ps_feature_value fv ON fv.id_feature_value = fvl.id_feature_value
WHERE fv.id_feature = X AND fvl.id_lang = X
ORDER BY fvl.value;
```

**Comment by Hlavtox** [comment]
Remember there can be thousands of feature values returned, why not just add `ORDER BY fvl.value`?

**Comment by MatShir** [comment]
Regarding the sort, I’m going back to my statement for the order by position in the search input. I agree, it can be very inconvenient to look for data since the feature can be a very long list, with feature of different for different product type. So the features mix feature for example for TV and T-shirt, so the position sorting making it not really relevant.

To conclude, ideally feature and feature values should be sort by alphabetic order, but I don’t know if it fits the PR scope. It  would be a nice to have

**Comment by MatShir** [comment]
The sorting by position could be more interesting to order the features after the save. So the merchant would have a preview of how the list would be in the FO but keep the alpha order when looking for feature and feature value for an easy search. Just an improv idea

**Review by Hlavtox — DISMISSED** [review]
Hi @jolelievre, some tweaks that should be done, so it's done correctly... :-)

1. Feature values must be fetched with one query. Now you are passing a list of IDs to get language values. It can be big, it can be slow, it's just one unnecessary round trip and complication.
```
SELECT fvl.* FROM ps_feature_value_lang fvl
LEFT JOIN ps_feature_value fv ON fv.id_feature_value = fvl.id_feature_value
WHERE fv.id_feature = X AND fvl.id_lang = X
ORDER BY fvl.value;
```

2. We can fetch the data just in one language, there will always be a language value for the feature.

3. Data in selectboxes must be ordered by `fl.name`, values by `fvl.value`. It will be faster then doing a PHP sort on the fetched data.

**Comment by Hlavtox** [comment]
@jolelievre Works perfectly! Last thing we should optimize is this - fetch the lang values directly.

Snímek obrazovky 2023-11-21 115714

**Comment by jolelievre** [comment]
@Hlavtox this one is trickier because it NEED the multi lang values, so the pagination can't work But I'll try and see if I can create yet another method (or modify the actual one) that doesn't use pagination and thus would allow doing a single request

**Review by tleon — DISMISSED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @jolelievre,

I tested your PR and it's GOOD for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by mflasquin** [comment]
thanks @jolelievre 😉
