### PR TITLE
FO: Display 'free' as shipping cost in the cart when a cart rule grants free shipping

### LINKED ISSUE #18533: FO - checkout - The Shipping cost is incorrect in the cart detail when using a cart rule "Free shipping"
#### Describe the bug
When there is a free shipping voucher, in the checkout page => cart details, the shipping line is incorrect, the shipping cost is displayed instead of FREE.

#### Expected behavior

What should be done is to display FREE on the shipping line instead of the initial pricen when there is a free shipping voucher

#### Steps to Reproduce

Steps to reproduce the **fixed** issue in the branch 177x
In the **BO**:
1. Add cart rule free shipping from € 35,-
2. Add cart rule free gift to the value of € 3,95,- with every order
3. Add cart rule free gift to the value of € 17,95,- for orders from € 75, -
4. All carriers should **not be free**

In the **FO**:
1. Add a product to the shopping cart with a value of less than 35 euros to see the shipping costs.
2. Add a product to the shopping cart with a value over 35 euros to see the free shipping label.

at this step, in the cart details, the shipping cost is always displayed with 177x branch, in the PS1.7.6.4, it is free

**Screenshots**
**177x branch**
image

**1764**
image

#### Additional information

* PrestaShop version:  1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In the cart (FO), in the right column, the value of the shipping cost should be 'free' when there is a cart rule offering free shipping. This PR takes count of cart rules when defining the display value of shipping cost. (see issue for screen captures)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18533
| How to test?  | See issue #18533

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18884)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 1]
```diff
@@ -495,6 +495,13 @@ private function getShippingDisplayValue($cart, $shippingCost)
     {
         $shippingDisplayValue = '';
 
+        // if one of the applied cart rules have free shipping, then the shipping display value is 'Free'
+        foreach ($cart->getCartRules() as $rule) {
```
Comment (arouiadib) [inline src/Adapter/Presenter/Cart/CartPresenter.php:499]: Thank you for addressing this issue. I am just a bit confused in front of the the `else` statement in line 507. Doesn't it contain part/or whole of the logic you added? Again thanks for your time

Comment (Progi1984) [reply src/Adapter/Presenter/Cart/CartPresenter.php:499]: Ping @matthieu-rolland

**Comment by SD1982** [comment]
LGTM thanks @matthieu-rolland !

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland
