### PR TITLE
Fixed missing APE/SIRET Code in BackOffice Order View

### LINKED ISSUE #22983: Missing B2B info in Orders Details > Customer Block
#### Describe the bug

In 1.7.7.0 and 1.7.7.1 versions, when the shop is in B2B mode, some infos are missing in BO > Orders details > Customer Block : 
- Company name before the name of the customer
- SIRET and APE numbers in Customer Summary

In Orders List, the Company Name is displayed in 177 :heavy_check_mark: 

 
#### Expected behavior

The B2B info should also be displayed in 1.7.7 Order Details Page.

#### Steps to Reproduce

1. Go to Shop Parameters > Customer Settings > Enable B2B Mode
2. Go to Customers > Customers > Edit any customer (John DOE for example)
3. Add the B2B Info (Company, SIRET, APE...)
4. Go to an order of this customer, check the detail

**Screenshots**

Customer B2B Info added : 
177 regression SIRET APE missing customer

Display in 176 : 
177 regression SIRET APE missing in 176

Display in 177 : 
177 regression SIRET APE missing in 177

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fixed missing APE/SIRET Code in BackOffice Order View
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #22983
| How to test?      | Cf. #22983

**:notebook: BC Break :**
* The constructor of the file `src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php` has a new parameter (the 7th) : `\PrestaShop\PrestaShop\Adapter\Configuration $configuration`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23078)

### CODE REVIEW

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 1]
```diff
@@ -224,6 +224,8 @@ private function getOrderCustomer(Order $order): ?OrderCustomerForViewing
         $customerStats = $customer->getStats();
         $totalSpentSinceRegistration = Tools::convertPrice($customerStats['total_orders'], $order->id_currency);
 
+        $isB2BEnabled = (bool) Configuration::get('PS_B2B_ENABLE');
```
Comment (kpodemski) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: hmm why we didn't use `ConfigurationAdapter` in this class? 🤔

Comment (Progi1984) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: Correct. I make the change.

File: src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php [hunk 2]
```diff
@@ -114,6 +128,8 @@ public function __construct(
         $this->validOrdersPlaced = $validOrdersPlaced;
         $this->privateNote = $privateNote;
         $this->isGuest = $isGuest;
+        $this->ape = $ape;
+        $this->siret = $siret;
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php:132]: Consider casting these to string so that you can avoid mixed return types

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php]: Done

File: src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php (hunk 2 above)
Comment (Progi1984) [reply src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php:132]: Fixed.

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 3]
```diff
@@ -138,7 +144,8 @@ public function __construct(
         Locale $locale,
         Context $context,
         CustomerDataProvider $customerDataProvider,
-        GetOrderProductsForViewingHandlerInterface $getOrderProductsForViewingHandler
+        GetOrderProductsForViewingHandlerInterface $getOrderProductsForViewingHandler,
+        Configuration $configuration
```
Comment (eternoendless) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:148]: I'm personally not a fan of including the whole configuration as it makes it harder to test. But it's not worse than using the static version...

**Review by eternoendless — COMMENTED** [review]
I'm sad to see APE Code and SIRET which are French embedded in Core code which should be country agnostic...

**Review by eternoendless — DISMISSED** [review]
Code looks good

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php (hunk 3 above)
Comment (kpodemski) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:148]: Would you rather provide an array of specific configuration keys and its values? Something like we used to do in `Configuration::getMultiple`? I'm just curious.

I can imagine some scenarios where tests could fail if not executed in proper order but from what I know we're resetting configuration before tests so... it shouldn't be an issue right?

**Review by kpodemski — DISMISSED** [review]

**Review by Julievrz — DISMISSED** [review]
The wording looks good, thank you.

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found an exception following these steps:

1. Go to BO > Shop Parameters > Customer Settings page
2. Enable B2B
3. Go to FO 
4. Sign in with `John Doe` 
5. Go to Home > Your account > Your personal information page (To **edit** information)
6. Set `Company` and  `Identification number`
7. Save
8. Add any product to the cart
9. Continue checkout
10. Go to BO > Orders page
11. Open the last order created
12. See the error

image

This issue is reproduced with an old customer or a new customer or a guest only after editing information as described in step5 and step6.

Thank you!

**Review by atomiix — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found only one trivial issue:
As commented here: https://github.com/PrestaShop/PrestaShop/issues/22983#issuecomment-769716776
>In mobile display, SIRET and APE should both appear between "Account registered" and "Valid orders placed" infos in order to facilitate reading.

The APE => OK, but the Siret is NOK
image

Thank you!

**Review by PululuK — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
image
image

**Mobile**
image
image

Thank you!

**Comment by Progi1984** [comment]
Thanks me and @khouloudbelguith
