### PR TITLE
Multistore : Display countries only those covered by active carriers

### LINKED ISSUE #12732: When multistore is enabled, all countries are displayed in address instead of only those covered by active carriers
**Describe the bug**
You are in multistore and have zones, countries enabled for all shops 
Carriers are limited to a specific zone
You set _Restrict country selections in front office to those covered by active carriers_ to yes 
In front office of both shop while creating a customer address, you will see all countries instead of only ones covered by carriers of the shop.

**To Reproduce**
1. Enable multistore in shop parameters > General
2. Create a second store in advanced parameters > Multistore with default parameters
3. Go in International > Locations > Zones
4. Enable Europe & North America for both shops
5. Go in International >Locations > Countries
6. Enable France & United states for both shops
7. Set _Restrict country selections in front office to those covered by active carriers_ to _Yes_ for both shops 
8. Create a carrier 1 for shop 1 that only delivers Europe zone
9. Create a carrier 2 for shop 2 that only delivers North America zone
10. Go to shop1 FO and create a customer address, you will see in country list France & US instead of only France
11. Go to shop2 FO and create a customer address, you will see in country list France & US instead of only US

**Suggested fix**
The listed countiers should only be what is applicable to the current shop? Proposed change:

line 143 of:

/classes/Carrier.php

to:

`        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
			SELECT cl.*,c.*, cl.`name` AS country, zz.`name` AS zone, cs.`id_shop`
			FROM `'._DB_PREFIX_.'country` c'.
            Shop::addSqlAssociation('country', 'c').'
			LEFT JOIN `'._DB_PREFIX_.'country_lang` cl ON (c.`id_country` = cl.`id_country` AND cl.`id_lang` = '.(int) $id_lang.')
			INNER JOIN (`'._DB_PREFIX_.'carrier_zone` cz INNER JOIN `'._DB_PREFIX_.'carrier` cr ON ( cr.id_carrier = cz.id_carrier AND cr.deleted = 0 '.
            ($active_carriers ? 'AND cr.active = 1) ' : ') ').'     
			LEFT JOIN `'._DB_PREFIX_.'zone` zz ON cz.id_zone = zz.id_zone) ON zz.`id_zone` = c.`id_zone`
			LEFT JOIN `'._DB_PREFIX_.'carrier_shop` cs ON cr.id_carrier = cs.id_carrier
			WHERE 1
			AND cs.`id_shop` = ' . $id_shop . '
			'.($active_countries ? 'AND c.active = 1' : '').'
			'.(!is_null($contain_states) ? 'AND c.`contains_states` = '.(int) $contain_states : '').'
			ORDER BY cl.name ASC');`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Multistore : Display countries only those covered by active carriers (and a small optimization)
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | :arrow_down: 
| UI Tests          | https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19499555970
| Fixed issue or discussion?     | Fixes #12732
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

## How to test?
1. Enable multistore in shop parameters > General
2. Create a second store in advanced parameters > Multistore with default parameters
3. Go in International > Locations > Zones
4. Disable all zones
5. Enable Europe & North America for both shops
6. Go in International >Locations > Countries
7. Disable all countires
8. Enable France & United states for both shops
9. Set _Restrict country selections in front office to those covered by active carriers_ to _Yes_ for both shops 
10. Disable all carriers
11. Create a carrier 1 for shop 1 that only delivers Europe zone
12. Create a carrier 2 for shop 2 that only delivers North America zone
13. **BEFORE**
    * Go to shop1 FO and create a customer address, you will see in country list France & US 
    * Go to shop2 FO and create a customer address, you will see in country list France & US 
14. **AFTER**
    * Go to shop1 FO and create a customer address, you will see in country list only France
    * Go to shop2 FO and create a customer address, you will see in country list only US

### CODE REVIEW

**Review by Codencode — DISMISSED** [review]

**Review by Touxten — DISMISSED** [review]

File: classes/Carrier.php [hunk 1]
```diff
@@ -636,37 +636,45 @@ public static function getIdTaxRulesGroupMostUsed()
...
-            FROM `' . _DB_PREFIX_ . 'state` s
-            ORDER BY s.`name` ASC');
+        $result = [];
 
-        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
-            SELECT cl.*,c.*, cl.`name` AS country, zz.`name` AS zone
-            FROM `' . _DB_PREFIX_ . 'country` c' .
-            Shop::addSqlAssociation('country', 'c') . '
+        $countries = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS(
+            'SELECT cl.*,c.*, cl.`name` AS country, zz.`name` AS zone
```
Comment (Hlavtox) [inline classes/Carrier.php]:
```suggestion
            'SELECT cl.*, c.*, cl.`name` AS country, zz.`name` AS zone
```

Comment (Touxten) [reply classes/Carrier.php]: Nice catch  I didn't see that 💪eagle eye

Comment (Codencode) [reply classes/Carrier.php]: I focused on testing the query, but I didn't notice the lack of spaces!

Comment (Hlavtox) [reply classes/Carrier.php]: Nah it's just my obsession with having a system in everything :D

**Comment by Hlavtox** [comment]
I think it can also be done without the inner query, but as you wish @Progi1984, won't block it, just a suggestion.

```php
        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
            SELECT cl.*, c.*, cl.`name` AS country, zz.`name` AS zone
            FROM `' . _DB_PREFIX_ . 'country` c' .
            Shop::addSqlAssociation('country', 'c') . '
            LEFT JOIN `' . _DB_PREFIX_ . 'country_lang` cl ON c.`id_country` = cl.`id_country` AND cl.`id_lang` = ' . (int) $id_lang . '
            INNER JOIN `' . _DB_PREFIX_ . 'carrier_zone` cz ON cz.id_zone = c.id_zone
            LEFT JOIN `' . _DB_PREFIX_ . 'zone` zz ON zz.id_zone = c.id_zone
            INNER JOIN `' . _DB_PREFIX_ . 'carrier` cr ON cr.id_carrier = cz.id_carrier ' . ($active_carriers ? 'AND cr.active = 1 ' : '') . ' AND cr.deleted = 0
            INNER JOIN `' . _DB_PREFIX_ . 'carrier_shop` cs ON cr.id_carrier = cs.id_carrier AND cs.id_shop = ' . (int) Shop::getContextShopID() . '
            WHERE 1
            ' . ($active_countries ? 'AND c.active = 1' : '') . '
            ' . (null !== $contain_states ? 'AND c.`contains_states` = ' . (int) $contain_states : '') . '
            ORDER BY cl.name ASC
        ');
```

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

**Review by Touxten — APPROVED** [review]

**Comment by Codencode** [comment]
Hi @Progi1984, I'll take this opportunity to clear up a doubt.

Instead of this code:

```php
        $countries = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS(
            'SELECT cl.*,c.*, cl.`name` AS country, zz.`name` AS zone
            FROM `' . _DB_PREFIX_ . 'country` c
                ' . Shop::addSqlAssociation('country', 'c') . '
            LEFT JOIN `' . _DB_PREFIX_ . 'country_lang` cl ON (c.`id_country` = cl.`id_country` AND cl.`id_lang` = ' . (int) $id_lang . ')
            INNER JOIN (
                `' . _DB_PREFIX_ . 'carrier_zone` cz 
                    INNER JOIN `' . _DB_PREFIX_ . 'carrier` cr ON (cr.id_carrier = cz.id_carrier AND cr.deleted = 0 ' . ($active_carriers ? 'AND cr.active = 1) ' : ') ') . '
                    INNER JOIN `' . _DB_PREFIX_ . 'carrier_shop` cs ON cr.id_carrier = cs.id_carrier AND cs.id_shop = ' . (int) Shop::getContextShopID() . ' 
                    LEFT JOIN `' . _DB_PREFIX_ . 'zone` zz ON cz.id_zone = zz.id_zone
            ) ON zz.`id_zone` = c.`id_zone`
            WHERE 1
            ' . ($active_countries ? 'AND c.active = 1' : '') . '
            ' . (null !== $contain_states ? 'AND c.`contains_states` = ' . (int) $contain_states : '') . '
            GROUP BY c.`id_country`
            ORDER BY cl.name ASC'
        );
        foreach ($countries as $country) {
            $result[$country['id_country']] = $country;
        }
```

couldn't we use this:

```php
        $db = Db::getInstance(_PS_USE_SQL_SLAVE_);
        $countries = $db->executeS(
            'SELECT cl.*,c.*, cl.`name` AS country, zz.`name` AS zone
            FROM `' . _DB_PREFIX_ . 'country` c
                ' . Shop::addSqlAssociation('country', 'c') . '
            LEFT JOIN `' . _DB_PREFIX_ . 'country_lang` cl ON (c.`id_country` = cl.`id_country` AND cl.`id_lang` = ' . (int) $id_lang . ')
            INNER JOIN (
                `' . _DB_PREFIX_ . 'carrier_zone` cz 
                    INNER JOIN `' . _DB_PREFIX_ . 'carrier` cr ON (cr.id_carrier = cz.id_carrier AND cr.deleted = 0 ' . ($active_carriers ? 'AND cr.active = 1) ' : ') ') . '
                    INNER JOIN `' . _DB_PREFIX_ . 'carrier_shop` cs ON cr.id_carrier = cs.id_carrier AND cs.id_shop = ' . (int) Shop::getContextShopID() . ' 
                    LEFT JOIN `' . _DB_PREFIX_ . 'zone` zz ON cz.id_zone = zz.id_zone
            ) ON zz.`id_zone` = c.`id_zone`
            WHERE 1
            ' . ($active_countries ? 'AND c.active = 1' : '') . '
            ' . (null !== $contain_states ? 'AND c.`contains_states` = ' . (int) $contain_states : '') . '
            GROUP BY c.`id_country`
            ORDER BY cl.name ASC',
            false
        );
        while ($country = $db->nextRow($countries)) {
            $result[$country['id_country']] = $country;
        }
        return $result;
  ```      

So instead of passing `true` as the second parameter (which requests an array that we then need to iterate through), we should pass `false` and request the "statement" to iterate through instead? Basically, when we request an array, does the system already perform an iteration to create it?

I'm sure you'll have a valid explanation to clear up my doubt :-)


However, I approve of the solution.

**Review by Codencode — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
Thanks Franck, thanks for fixing all of these

**Comment by SiraDIOP** [comment]
Hello @Progi1984, 

Thanks for your PR, i tested it and it's good for me 
Capture d’écran 2025-11-28 à 10 17 40
Capture d’écran 2025-11-28 à 10 18 37

Thanks

**Review by SiraDIOP — APPROVED** [review]
