### PR TITLE
Define when a voucher should be displayed in 'Your vouchers'

### LINKED ISSUE #22397: Customer Group Discounts are not showned since migration to 1.7.7.0
#### Describe the bug

Special discounts are sets for each group of customer. Since the migration to 1.7.7.0, the discounts are not anymore showned on the frontend account page of each customer (it works if the discount is espacially done for the customer).

#### Expected behavior

Discounts have to be showned in each customer's "My discounts" page if he/she is a member of the group that can have the discount

#### Steps to Reproduce

1. **BO** > **SELL** > **Catalog** > **Discounts** > **Add a new cart rule**
2. In the **Conditions** tab, check the **Customer group selection** in the **Restrictions** section
3. Choose **Customer** as **Selected groups** and (for exemple) choose **Free shipping** in the **Actions** tab, then **Save**
4. Go to **FO** and access with the credentials of a customer that is a member the "Customer" group. 
5. Go to account page **Vouchers**
6. See that the discount is not shown there

#### Screenshots & screen records

**PS1.7.6.9:**
https://drive.google.com/file/d/1pNO0hS7UPnjgR-q7EdLjTmL13T0ekJ7A/view

**PS1.7.7.0:**
https://drive.google.com/file/d/18PBGO4_AEJCYGMXO1UCSka72L0-EpeQW/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Conditions for showing vouchers in *You vouchers* were unclear, this PR aims to implements specs defined [here](https://github.com/PrestaShop/prestashop-specs/pull/189/files?short_path=48191b5#diff-48191b557b76f88e81e5ba06072d3f90a953d5f658238f66ef043a330c39582f).
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22397
| How to test?      | Following [these specs](https://github.com/PrestaShop/prestashop-specs/pull/189/files?short_path=48191b5#diff-48191b557b76f88e81e5ba06072d3f90a953d5f658238f66ef043a330c39582f), you can try different combinations on a cart rule and see if it is showing or not in the FO page *Your vouchers*
| Possible impacts? | That should also impact the Customer detail page, on the *Vouchers* part

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22518)

### CODE REVIEW

File: js/admin.js [hunk 1]
```diff
@@ -364,6 +364,7 @@ function gencode(size)
   var chars = "123456789ABCDEFGHIJKLMNPQRSTUVWXYZ";
   for (var i = 1; i <= size; ++i)
     getE('code').value += chars.charAt(Math.floor(Math.random() * chars.length));
+  getE('cart-rules-highlight').style.display = '';
```
Comment (PierreRambaud) [inline js/admin.js]:
```suggestion
  for (var i = 1; i <= size; ++i) {
    getE('code').value += chars.charAt(Math.floor(Math.random() * chars.length));
  }

  getE('cart-rules-highlight').style.display = '';
```
Just because I thought it was a bug :sweat:

File: classes/CartRule.php [hunk 2]
```diff
@@ -392,7 +392,9 @@ public static function getCustomerCartRules(
             $sql_part2 .= ' AND highlight = 1 AND code NOT LIKE "' . pSQL(CartRule::BO_ORDER_CODE_PREFIX) . '%"';
         }
 
-        $sql = '(SELECT SQL_NO_CACHE ' . $sql_part1 . ' WHERE cr.`id_customer` = ' . (int) $id_customer . ' ' . $sql_part2 . ')';
+        $sql = '(SELECT SQL_NO_CACHE ' . $sql_part1 . '
+            WHERE cr.`id_customer` = ' . (int) $id_customer . ' OR cr.`highlight` = 1 OR cr.`code` = ""
```
Comment (PierreRambaud) [inline classes/CartRule.php]: Watch out with the `OR` chained with all `AND` in `$sql_part2`

**Review by PierreRambaud — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have a difference In the BO > Catalog > Discounts page > Add new cart rule page
**Without PR** and PS1769
image
**With PR**
image
It will be displayed only if we generate a code

Is this a wanted behavior?

Thank you!

**Comment by atomiix** [comment]
Hi @khouloudbelguith

Yes, it's a new behavior that @MatShir wanted so we can better understand that `Highlight` won't be used when there is no code.

**Comment by MatShir** [comment]
**Magic** 🧙 

The specification is coming very soon. 🤞

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an issue in the BO.

1. Go to BO > Catalog > Discounts > Add new cart rule for a User restriction (for example `pub@prestashop.com`) with no code.
2. Create a new customer from the BO or FO
3. Go to BO > Customers > New Customer View page
4. I the Voucher section, the cart rule is displayed => NOK

PS: in the FO => OK

I attached a screen record
https://drive.google.com/file/d/1-zPNxswj59R8bK7DDNeVMHCDfgQXo8oo/view?usp=sharing

Thanks!

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

All cases are ok :heavy_check_mark: 
I found an issue not related to this PR (reproduced with PS1769):

1. Create a cart rule:
1.1. Information: with Code + Highlight enabled
1.2. Total available = 1 & Total available for each user = 1
1.3. Actions: any discount
2. Go to FO (sign in with John DOE) > apply the voucher > checkout 
3. Sign in with a different customer 
4. Go to FO > Your account > Your vouchers page
5. see the error: the quantity =1  => NOK
image
image
6. In the BO > Customers > Customer details page => ok
image

PS1769 NOK => https://drive.google.com/file/d/1-LfZnNngHTlMliDNBdrEpY0RLJ7O8UWY/view?usp=sharing

It should be fixed here or I need to create an issue?

Thank you!

**Comment by atomiix** [comment]
Thanks @khouloudbelguith, I think we can open a new issue for this bug!

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

Ok :heavy_check_mark: 

Thank you!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
WAITING FOR THE 1771 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith & @atomiix
