### PR TITLE
Fix missing canonicals

### LINKED ISSUE #9503: [BOOM-6269] Missing url canonical in a lot of pages
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-6269).

- _**Reporter:**_ maofree
- _**Created at:**_ Fri, 17 Aug 2018 13:42:02 +0200

### Describe the bug
Missing url canonical from manufacturer page probably from other pages like this
look from its source view, the `hreflang` url are present but not the canonical url `rel`

PS: The rel = canonical link tag is an HTML tag that allows search engines to find the canonical URL on a given page.

### Expected behavior

image

### Steps to reproduce 

1. FO> Brands
2. inspect the source code
3. See error > no `rel = canonical` link tag

image

### Additional infos
- PS version: 1.7.8.2
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by Prestaworks**
Add of canonical links for bestsales, manufacturer, newproducts, pricesdrop, search and supplier.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Added canonical url to various listing pages to solve issue 9503
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9503.
| How to test?      | See issue for details, but checking source code of affected controllers should be enough.
| Possible impacts? | Frontend template, header information regarding canonical url

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26774)

### CODE REVIEW

**Comment by Hlavtox** [comment]
Maybe we could automatically generate it for all pages here?
https://github.com/PrestaShop/PrestaShop/blob/190d2aa713d2a737bdf2852b827a008b31f0fba3/classes/controller/FrontController.php#L1785

And then only alter it in special pages - specific manufacturer, product, category etc.?

**Comment by Prestaworks** [comment]
> Maybe we could automatically generate it for all pages here?
> 
> https://github.com/PrestaShop/PrestaShop/blob/190d2aa713d2a737bdf2852b827a008b31f0fba3/classes/controller/FrontController.php#L1785
> 
> And then only alter it in special pages - specific manufacturer, product, category etc.?

It would be a bit complex as we would have to identify the controller and get links in a few different ways. Also, it's not really needed as canonical links is mainly used to avoid duplicate content from listing pages. So for instance, the contact-us page only have one version for each language and do not need a canonical link.

File: controllers/front/listing/BestSalesController.php [hunk 1]
```diff
@@ -31,6 +31,13 @@ class BestSalesControllerCore extends ProductListingFrontController
 {
     public $php_self = 'best-sales';
 
+    public function getCanonicalURL()
```
Comment (Progi1984) [inline controllers/front/listing/BestSalesController.php]:
```suggestion
    public function getCanonicalURL(): string
```

File: controllers/front/listing/BestSalesController.php [hunk 2]
```diff
@@ -31,6 +31,13 @@ class BestSalesControllerCore extends ProductListingFrontController
...
+    {
+        $canonicalUrl = $this->context->link->getPageLink('best-sales');
+
+        return $canonicalUrl;
```
Comment (Progi1984) [inline controllers/front/listing/BestSalesController.php]:
```suggestion
        return $this->context->link->getPageLink('best-sales');
```

File: controllers/front/listing/ManufacturerController.php [hunk 3]
```diff
@@ -43,6 +43,17 @@ public function canonicalRedirection($canonicalURL = '')
         }
     }
 
+    public function getCanonicalURL()
```
Comment (Progi1984) [inline controllers/front/listing/ManufacturerController.php]:
```suggestion
    public function getCanonicalURL(): string
```

File: controllers/front/listing/ManufacturerController.php [hunk 4]
```diff
@@ -43,6 +43,17 @@ public function canonicalRedirection($canonicalURL = '')
...
+    {
+        if (Validate::isLoadedObject($this->manufacturer)) {
+            $canonicalUrl = $this->context->link->getManufacturerLink($this->manufacturer);
+        } else {
+            $canonicalUrl = $this->context->link->getPageLink('manufacturer');
+        }
+
+        return $canonicalUrl;
```
Comment (Progi1984) [inline controllers/front/listing/ManufacturerController.php]:
```suggestion
        if (Validate::isLoadedObject($this->manufacturer)) {
            return $this->context->link->getManufacturerLink($this->manufacturer);
        }
        
        return $this->context->link->getPageLink('manufacturer');
```

File: controllers/front/listing/NewProductsController.php [hunk 5]
```diff
@@ -31,6 +31,13 @@ class NewProductsControllerCore extends ProductListingFrontController
 {
     public $php_self = 'new-products';
 
+    public function getCanonicalURL()
+    {
+        $canonicalUrl = $this->context->link->getPageLink('new-products');
+
+        return $canonicalUrl;
+    }
```
Comment (Progi1984) [inline controllers/front/listing/NewProductsController.php]:
```suggestion
    public function getCanonicalURL(): string
    {
        return $this->context->link->getPageLink('new-products');
    }
```

File: controllers/front/listing/PricesDropController.php [hunk 6]
```diff
@@ -31,6 +31,13 @@ class PricesDropControllerCore extends ProductListingFrontController
 {
     public $php_self = 'prices-drop';
 
+    public function getCanonicalURL()
+    {
+        $canonicalUrl = $this->context->link->getPageLink('prices-drop');
+
+        return $canonicalUrl;
+    }
```
Comment (Progi1984) [inline controllers/front/listing/PricesDropController.php]:
```suggestion
    public function getCanonicalURL(): string
    {
        return $this->context->link->getPageLink('prices-drop');
    }
```

File: controllers/front/listing/SearchController.php [hunk 7]
```diff
@@ -61,6 +61,13 @@ public function init()
         );
     }
 
+    public function getCanonicalURL()
```
Comment (Progi1984) [inline controllers/front/listing/SearchController.php]:
```suggestion
    public function getCanonicalURL(): string
```

File: controllers/front/listing/SearchController.php [hunk 8]
```diff
@@ -61,6 +61,13 @@ public function init()
...
+    {
+        $canonicalUrl = $this->context->link->getPageLink('search', null, null, ['s' => $this->search_string]);
+
+        return $canonicalUrl;
```
Comment (Progi1984) [inline controllers/front/listing/SearchController.php]:
```suggestion
        return $this->context->link->getPageLink('search', null, null, ['s' => $this->search_string]);
```

File: controllers/front/listing/SupplierController.php [hunk 9]
```diff
@@ -44,6 +44,17 @@ public function canonicalRedirection($canonicalURL = '')
         }
     }
 
+    public function getCanonicalURL()
```
Comment (Progi1984) [inline controllers/front/listing/SupplierController.php]:
```suggestion
    public function getCanonicalURL(): string
```

File: controllers/front/listing/SupplierController.php [hunk 10]
```diff
@@ -44,6 +44,17 @@ public function canonicalRedirection($canonicalURL = '')
...
+    {
+        if (Validate::isLoadedObject($this->supplier)) {
+            $canonicalUrl = $this->context->link->getSupplierLink($this->supplier);
```
Comment (Progi1984) [inline controllers/front/listing/SupplierController.php]:
```suggestion
            return $this->context->link->getSupplierLink($this->supplier);
```

File: controllers/front/listing/SupplierController.php [hunk 11]
```diff
@@ -44,6 +44,17 @@ public function canonicalRedirection($canonicalURL = '')
...
+        } else {
+            $canonicalUrl = $this->context->link->getPageLink('supplier');
+        }
+
+        return $canonicalUrl;
```
Comment (Progi1984) [inline controllers/front/listing/SupplierController.php]:
```suggestion
        }

        return $this->context->link->getPageLink('supplier');
```

**Review by Progi1984 — COMMENTED** [review]
@Prestaworks Thank you for your contribution. I have brought some suggestions for improving the typehinting and reducing some unuseful code.

**Review by matks — COMMENTED** [review]
I'll be honest 🤷‍♂️  : I'm completely lost when it comes to SEO.

So code seems legit but I need someone more skilled that me at SEO to validate the goal

**Comment by Prestaworks** [comment]
> I'll be honest 🤷‍♂️ : I'm completely lost when it comes to SEO.
> 
> So code seems legit but I need someone more skilled that me at SEO to validate the goal

Do you have someone you can ask about these things?

**Comment by matks** [comment]
For "regular" SEO stuff, the other maintainers are skilled enough.

For deep SEO stuff, we usually request a web agency that are SEO experts. Nothing better than people who do it all day.

**Comment by Prestaworks** [comment]
> For "regular" SEO stuff, the other maintainers are skilled enough.
> 
> For deep SEO stuff, we usually request a web agency that are SEO experts. Nothing better than people who do it all day.

I agree, all I got here is the information I got about canonicals, that page2 3 and so on need a canonical to avoid duplicate content and that there is no problem with a canonical pointing to itself. This is however based on information from merchants, their seo experts and articles on the internet and not from me being any kind of expert on the matter :) 

can you ask a SEO expert that you trust about this so we can close the issue (or move forward with a better solution)?

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I had the same feedback some time ago about the canonicals in PrestaShop from the SEO agency. These pages should have them, which is why it's a ✅ from me

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

As commented here: https://github.com/PrestaShop/PrestaShop/issues/9503#issuecomment-415010976
There are some pages are missing
1. index 
image

2. contact 
image

3. sitemap 
image

4. stores 
image


Thank you!

**Comment by Prestaworks** [comment]
> Hi @Prestaworks,
> 
> As commented here: [#9503 (comment)](https://github.com/PrestaShop/PrestaShop/issues/9503#issuecomment-415010976) There are some pages are missing
> 
>     1. index
>        image
> 
>     2. contact
>        image
> 
>     3. sitemap
>        image
> 
>     4. stores
>        image
> 
> 
> Thank you!

You only need canonicals on pages with pagination (page2, page3 and so on) so there are no reason to have a canonical on contact-form or the index page for instance.

**Comment by khouloudbelguith** [comment]
Hello :slightly_smiling_face: 

Ping @PrestaShop/product-team can you please confirm me that https://github.com/PrestaShop/PrestaShop/pull/26774#issuecomment-994721696

Thank you!

**Review by jolelievre — DISMISSED** [review]
Thanks @Prestaworks

File: controllers/front/listing/BestSalesController.php [hunk 12]
```diff
@@ -31,6 +31,11 @@ class BestSalesControllerCore extends ProductListingFrontController
 {
     public $php_self = 'best-sales';
 
+    public function getCanonicalURL(): string
+    {
+        return $this->context->link->getPageLink('best-sales');
```
Comment (Hlavtox) [inline controllers/front/listing/BestSalesController.php]: Pagination should be implemented here.

File: controllers/front/listing/ManufacturerController.php [hunk 13]
```diff
@@ -43,6 +43,15 @@ public function canonicalRedirection($canonicalURL = '')
         }
     }
 
+    public function getCanonicalURL(): string
+    {
+        if (Validate::isLoadedObject($this->manufacturer)) {
+            return $this->context->link->getManufacturerLink($this->manufacturer);
```
Comment (Hlavtox) [inline controllers/front/listing/ManufacturerController.php]: Pagination should be implemented here

File: controllers/front/listing/NewProductsController.php [hunk 14]
```diff
@@ -31,6 +31,11 @@ class NewProductsControllerCore extends ProductListingFrontController
 {
     public $php_self = 'new-products';
 
+    public function getCanonicalURL(): string
+    {
+        return $this->context->link->getPageLink('new-products');
```
Comment (Hlavtox) [inline controllers/front/listing/NewProductsController.php]: Pagination should be implemented here

File: controllers/front/listing/PricesDropController.php [hunk 15]
```diff
@@ -31,6 +31,11 @@ class PricesDropControllerCore extends ProductListingFrontController
 {
     public $php_self = 'prices-drop';
 
+    public function getCanonicalURL(): string
+    {
+        return $this->context->link->getPageLink('prices-drop');
```
Comment (Hlavtox) [inline controllers/front/listing/PricesDropController.php]: Pagination should be implemented here

File: controllers/front/listing/SearchController.php [hunk 16]
```diff
@@ -61,6 +61,11 @@ public function init()
         );
     }
 
+    public function getCanonicalURL(): string
+    {
+        return $this->context->link->getPageLink('search', null, null, ['s' => $this->search_string]);
```
Comment (Hlavtox) [inline controllers/front/listing/SearchController.php]: Pagination should be implemented here

File: controllers/front/listing/SupplierController.php [hunk 17]
```diff
@@ -44,6 +44,15 @@ public function canonicalRedirection($canonicalURL = '')
         }
     }
 
+    public function getCanonicalURL(): string
+    {
+        if (Validate::isLoadedObject($this->supplier)) {
+            return $this->context->link->getSupplierLink($this->supplier);
```
Comment (Hlavtox) [inline controllers/front/listing/SupplierController.php]: Pagination should be implemented here

**Comment by Hlavtox** [comment]
Hi @Prestaworks, you are missing pagination in nearly all canoncials. Each page of the listing has unique content, so it must have unique canoncial.

See category controller for help with implementation:
https://github.com/PrestaShop/PrestaShop/blob/bcf63947b4820e86a0dad1fd1219be259b76cf9e/controllers/front/listing/CategoryController.php#L57

**Comment by kpodemski** [comment]
@Hlavtox is right, 

> A common mistake is to point the rel=”canonical” from all paginated results to the root page of the series.
> Some ill-informed SEO people suggest this as a way to consolidate authority across the set of pages to the root page, but this is misinformed.
> 
> Incorrect canonicalization to the root page runs the risk of misdirecting search engines into thinking you have only a single page of results.
> 
> Googlebot then won’t index pages that appear further along the chain, nor acknowledge the signals to the content linked from those pages.
> 
> You don’t want your detailed content pages dropping out of the index because of poor pagination handling.
> 
> Each page within a paginated series should have a self-referencing canonical, unless you use a View All page.
> 
> Use the rel=canonical incorrectly and chances are Googlebot will just ignore your signal.

Source: https://www.searchenginejournal.com/technical-seo/pagination/

More:
https://blogs.perficient.com/2017/11/14/pagination-canonicalization-seo-your-technical-guide/

> Here’s how your canonical tags should look:
> Root paginated page (the first page in your paginated series)
> <link rel=”canonical” href=”https://www.domain.com/category“/>
> Second page in the series (first after the root)
> <link rel=”canonical” href=” https://www.domain.com/category?page=2″/>

Another source:
https://ahrefs.com/blog/rel-prev-next-pagination/

File: controllers/front/listing/SearchController.php (hunk 16 above)
Comment (kpodemski) [reply controllers/front/listing/SearchController.php]: Is it needed for the search page tho?

**Review by kpodemski — DISMISSED** [review]
I agree with Daniel's suggestion about paginated results

**Comment by jolelievre** [comment]
Ok then we should add a tool that helps to build the canonical URL with pagination more easily to avoid duplicating the code everywhere

**Comment by Prestaworks** [comment]
> Ok then we should add a tool that helps to build the canonical URL with pagination more easily to avoid duplicating the code everywhere

We could take the page handing code and put in a function like this, maybe in the ProductListingFrontControllerCore ? Then just pass the different urls to this function to fix the page part? 
```

public function nameoffunction($canonicalUrl)
    {
        $parsedUrl = parse_url($canonicalUrl);
        if (isset($parsedUrl['query'])) {
            parse_str($parsedUrl['query'], $params);
        } else {
            $params = [];
        }
        $page = (int) Tools::getValue('page');
        if ($page > 1) {
            $params['page'] = $page;
        } else {
            unset($params['page']);
        }
        $canonicalUrl = http_build_url($parsedUrl, ['query' => http_build_query($params)]);
        return $canonicalUrl;
    }
```


Then in the controllers it would be

```
public function getCanonicalURL()
    {
        if (!Validate::isLoadedObject($this->category)) {
            return '';
        }
        $canonicalUrl = $this->context->link->getCategoryLink($this->category);
        $canonicalUrl = $this->nameoffunction($canonicalUrl);

        return $canonicalUrl;
    }
```

**Comment by jolelievre** [comment]
Seems like a good choice @Prestaworks 
For the function name I suggest `buildPaginatedUrl`

File: controllers/front/listing/BestSalesController.php [hunk 18]
```diff
@@ -31,6 +31,11 @@ class BestSalesControllerCore extends ProductListingFrontController
 {
     public $php_self = 'best-sales';
 
+    public function getCanonicalURL(): string
+    {
+        return parent::buildPaginatedUrl($this->context->link->getPageLink('best-sales'));
```
Comment (sowbiba) [inline controllers/front/listing/BestSalesController.php]:
```suggestion
        return $this->buildPaginatedUrl($this->context->link->getPageLink('best-sales'));
```

File: controllers/front/listing/CategoryController.php [hunk 19]
```diff
@@ -59,22 +59,8 @@ public function getCanonicalURL()
...
-        }
-
-        if ($page > 1) {
-            $params['page'] = $page;
-        } else {
-            unset($params['page']);
-        }
-
-        return http_build_url($parsedUrl, ['query' => http_build_query($params)]);
+        return parent::buildPaginatedUrl($this->context->link->getCategoryLink($this->category));
```
Comment (sowbiba) [inline controllers/front/listing/CategoryController.php]:
```suggestion
        return $this->buildPaginatedUrl($this->context->link->getCategoryLink($this->category));
```

File: controllers/front/listing/ManufacturerController.php [hunk 20]
```diff
@@ -43,6 +43,15 @@ public function canonicalRedirection($canonicalURL = '')
         }
     }
 
+    public function getCanonicalURL(): string
+    {
+        if (Validate::isLoadedObject($this->manufacturer)) {
+            return parent::buildPaginatedUrl($this->context->link->getManufacturerLink($this->manufacturer));
```
Comment (sowbiba) [inline controllers/front/listing/ManufacturerController.php]:
```suggestion
            return $this->buildPaginatedUrl($this->context->link->getManufacturerLink($this->manufacturer));
```

File: controllers/front/listing/NewProductsController.php [hunk 21]
```diff
@@ -31,6 +31,11 @@ class NewProductsControllerCore extends ProductListingFrontController
 {
     public $php_self = 'new-products';
 
+    public function getCanonicalURL(): string
+    {
+        return parent::buildPaginatedUrl($this->context->link->getPageLink('new-products'));
```
Comment (sowbiba) [inline controllers/front/listing/NewProductsController.php]:
```suggestion
        return $this->buildPaginatedUrl($this->context->link->getPageLink('new-products'));
```

File: controllers/front/listing/PricesDropController.php [hunk 22]
```diff
@@ -31,6 +31,11 @@ class PricesDropControllerCore extends ProductListingFrontController
 {
     public $php_self = 'prices-drop';
 
+    public function getCanonicalURL(): string
+    {
+        return parent::buildPaginatedUrl($this->context->link->getPageLink('prices-drop'));
```
Comment (sowbiba) [inline controllers/front/listing/PricesDropController.php]:
```suggestion
        return $this->buildPaginatedUrl($this->context->link->getPageLink('prices-drop'));
```

File: controllers/front/listing/SearchController.php [hunk 23]
```diff
@@ -61,6 +61,11 @@ public function init()
         );
     }
 
+    public function getCanonicalURL(): string
+    {
+        return parent::buildPaginatedUrl($this->context->link->getPageLink('search', null, null, ['s' => $this->search_string]));
```
Comment (sowbiba) [inline controllers/front/listing/SearchController.php]:
```suggestion
        return $this->buildPaginatedUrl($this->context->link->getPageLink('search', null, null, ['s' => $this->search_string]));
```

File: controllers/front/listing/SupplierController.php [hunk 24]
```diff
@@ -44,6 +44,15 @@ public function canonicalRedirection($canonicalURL = '')
         }
     }
 
+    public function getCanonicalURL(): string
+    {
+        if (Validate::isLoadedObject($this->supplier)) {
+            return parent::buildPaginatedUrl($this->context->link->getSupplierLink($this->supplier));
```
Comment (sowbiba) [inline controllers/front/listing/SupplierController.php]:
```suggestion
            return $this->buildPaginatedUrl($this->context->link->getSupplierLink($this->supplier));
```

File: classes/controller/ProductListingFrontController.php [hunk 25]
```diff
@@ -39,6 +39,33 @@
...
+        }
+        $page = (int) Tools::getValue('page');
+        if ($page > 1) {
+            $params['page'] = $page;
+        } else {
+            unset($params['page']);
+        }
+        $canonicalUrl = http_build_url($parsedUrl, ['query' => http_build_query($params)]);
+
+        return $canonicalUrl;
```
Comment (sowbiba) [inline classes/controller/ProductListingFrontController.php]:
```suggestion
        return http_build_url($parsedUrl, ['query' => http_build_query($params)]);
```

**Review by sowbiba — COMMENTED** [review]
Some feedbacks

File: controllers/front/listing/SupplierController.php (hunk 24 above)
Comment (Prestaworks) [reply controllers/front/listing/SupplierController.php]: Any specific reason for "this" instead of "parent"?

**Comment by Progi1984** [comment]
Hi @Prestaworks,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

**Comment by Prestaworks** [comment]
> Hi @Prestaworks, Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant. Thanks!

What are you waiting on me for?

**Comment by Progi1984** [comment]
@Prestaworks Sorry but I didn't see any answers to @sowbiba feedbacks.

**Comment by Prestaworks** [comment]
> @Prestaworks Sorry but I didn't see any answers to @sowbiba feedbacks.

There was :)
bild

File: classes/controller/ProductListingFrontController.php [hunk 26]
```diff
@@ -39,6 +39,32 @@
...
 {
+    /**
+     * Generates an URL to a product listing controller
+     * with only the essential query params and page remaining.
+     *
+     * @param string $canonicalUrl an url to a listing controller page
+     *
+     * @return string a canonical URL for the current page in the list
+     */
+    public function buildPaginatedUrl($canonicalUrl)
```
Comment (Progi1984) [inline classes/controller/ProductListingFrontController.php]:
```suggestion
    public function buildPaginatedUrl(string $canonicalUrl): string
```

File: controllers/front/listing/BestSalesController.php (hunk 18 above)
Comment (Progi1984) [reply controllers/front/listing/BestSalesController.php]: Ping @Prestaworks

**Comment by Prestaworks** [comment]
> Some feedbacks

Is this due to override reasons?

File: controllers/front/listing/CategoryController.php (hunk 19 above)
Comment (Progi1984) [reply controllers/front/listing/CategoryController.php]: Ping @Prestaworks

File: controllers/front/listing/ManufacturerController.php (hunk 20 above)
Comment (Progi1984) [reply controllers/front/listing/ManufacturerController.php]: Ping @Prestaworks

File: controllers/front/listing/NewProductsController.php (hunk 21 above)
Comment (Progi1984) [reply controllers/front/listing/NewProductsController.php]: Ping @Prestaworks

File: controllers/front/listing/PricesDropController.php (hunk 22 above)
Comment (Progi1984) [reply controllers/front/listing/PricesDropController.php]: Ping @Prestaworks

File: controllers/front/listing/SearchController.php (hunk 23 above)
Comment (Progi1984) [reply controllers/front/listing/SearchController.php]: Ping @Prestaworks

File: controllers/front/listing/SupplierController.php (hunk 24 above)
Comment (Progi1984) [reply controllers/front/listing/SupplierController.php]: Yes. If a controller wants to override the method, it's a direct method.

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

**Comment by Prestaworks** [comment]
> Some feedbacks

There is also some talk about pagination, I believe there was some SEO discoussion regarding this in another thread. So if there is a decision made on that maybe we can fix that now also?

**Comment by sowbiba** [comment]
> > Some feedbacks
> 
> Is this due to override reasons?

Sorry for the delay of the answer. Yeah, you created an abstract extending another abstract. If you use parent::XXX, you avoid children classes to override the buildPaginatedUrl method or at least use it where it is expected

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — COMMENTED** [review]
Is it possible to squash your commits? :)

**Comment by Prestaworks** [comment]
> Is it possible to squash your commits? :)

I don't think it's recommended to squash commits that are already pushed to remote?
(I also think that last time we tried to squash, it created a "merge commit" and that made the PR broken and we had to make a new one)

**Comment by Hlavtox** [comment]
It works fine, I do it in Tortoisegit.
- Show log
- Select all commits of this PR
- Right click, combine into one commit
- Set new message
- Push -force

**Comment by Prestaworks** [comment]
> It works fine, I do it in Tortoisegit.
> 
>     * Show log
> 
>     * Select all commits of this PR
> 
>     * Right click, combine into one commit
> 
>     * Set new message
> 
>     * Push -force

so you have a special software that does that for you? great4U :)

**Comment by Hlavtox** [comment]
> so you have a special software that does that for you? great4U :)

Just saying that every time that I tried to squash or rebase in CLI, I screwed up my branch completely. 😄😄

**Comment by Prestaworks** [comment]
> > so you have a special software that does that for you? great4U :)
> 
> Just saying that every time that I tried to squash or rebase in CLI, I screwed up my branch completely. 😄😄

yes me2 :) but now I saw that Github desktop added the same feature :) so it just got easy :)

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @Prestaworks,

It is ok :heavy_check_mark: 
- Category list
image
- Category list page 2
image
- Prices drop  list
image
- Prices drop  list page 2
image
- New products list
image
- New products list page2 
image
- Best sales list & page2
image
- Search list & page2
image

- Brand list page
- Suplier list page
- Specific brand list & page2
- Specific supplier list & page2
- I checked Friendly URL enabled / disabled + different languages
- I checked shop2 created with multistore
- I checked category list page + filter + sort

Thanks!

**Comment by Progi1984** [comment]
Thanks @Prestaworks & @khouloudbelguith

**Comment by Hlavtox** [comment]
Good job @Prestaworks !!!

**Comment by justeen35** [comment]
Thank you @Prestaworks
