### PR TITLE
Fixed the reset of the unit_price_ratio when the product is activated / deactivated from the product listing page

### LINKED ISSUE #10792: Unit price reset to 0 if you activate/deactivate or duplicate products in bo product list
**Describe the bug**
The Unit price and cost price are reset to 0 if you activate/deactivate/duplicate products from the product list.

**To Reproduce**
You have a product with unit price & cost price value.
From the product list you deactivate the product (both with single action or via mass action).
You open the product form and you can see that the unit price & cost price are set to 0.

NB
If you activate/deactivate the product from the product form the unit price works well.

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1.22

### LINKED ISSUE #20679: Activating / Deactivating Product from product listing resets unit_price_ratio to 0
#### Describe the bug

When the product is activated / deactivated from the product listing page, the `unit_price_ratio` is reset to 0

#### Expected behavior

The `unit_price_ratio` would be kept

#### Steps to Reproduce

1. Set unit price for a product to 10
2. Go to product listing page
2. Click on check / cross icon to activate / deactivate product
3. Navigate to product detail page Prices tab
4. The Unit price value is 0

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.3.14

### PR DESCRIPTION
**Pull request by artaban**
Fixes #20679

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When the product is activated / deactivated from the product listing page, the unit_price_ratio is reset to 0, this PR fixes this
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | yes / no
| Deprecations? | yes / no
| Fixed ticket? | Fixes #10792, #20679
| How to test?  | See issue description..

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20680)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
Hi @artaban , thanks for your contribution ! 

I aprove your modification, but this PR should not been sent to the QA team until the issue you created is reproduced by one of our testers. So wait and see ;)

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Hi and thanks for your contribution. This pull request must target the develop branch instead, could you please rebase it?

**Comment by artaban** [comment]
I've tried my best ;)
Guess it is alway good idea to create branch for the PR.. The rebasing is much cleaned then (I've pushed my changes directly to the 1.7.6.x branch)

File: classes/Product.php [hunk 1]
```diff
@@ -697,7 +697,9 @@ public function getFieldsShop()
     {
         $fields = parent::getFieldsShop();
         if (null === $this->update_fields || (!empty($this->update_fields['price']) && !empty($this->update_fields['unit_price']))) {
-            $fields['unit_price_ratio'] = (float) $this->unit_price > 0 ? $this->price / $this->unit_price : 0;
+            if ($this->unit_price != null) {
```
Comment (PierreRambaud) [inline classes/Product.php]:
```suggestion
            if ($this->unit_price !== null) {
```
Should it be this?

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @artaban,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1CdrBepowiwH0azrYpeTG3sJ1qkdVKSh-/view?usp=sharing

Thanks!

PS: about the issue of changing price => it is ab old issue reported here: https://github.com/PrestaShop/PrestaShop/issues/12078

**Comment by PierreRambaud** [comment]
Thanks @artaban
