### PR TITLE
Fix: Features with the same name are shown only once when creating values and assigning to products

### LINKED ISSUE #40703: Features with the same name are shown only once when creating values and assigning to products
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When two features with the same name are created, the system does not handle them correctly in some parts of the back office.

### Feature value creation
When creating a feature value, the system displays only one of the two features, making it impossible to select the other one.

### Feature assignment to a product
When assigning features to a product, the system displays only one of the features with a duplicated name, preventing them from being distinguished.

# Attached video:

- feature creation

https://github.com/user-attachments/assets/7a2ac1e8-ed55-4e0e-9286-c3b8cb372a1c

- product editing

https://github.com/user-attachments/assets/eec611e2-f958-4bf4-b599-d60e59c70a23

### Expected behavior

_No response_

### Steps to reproduce

1. Create a feature with name X
2. Create a second feature with the same name X
3. Try to:
   - create a feature value
   - assign the feature to a product

### PrestaShop version(s) where the bug happened

9.0.0

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### Your company or customer's name goes here (if applicable).

Codencode snc

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  9.0.x
| Description?      | Fixes an ambiguity issue when multiple features share the same name by displaying the feature ID alongside the name in the feature value creation form.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Create a feature with name X<br/>2. Create a second feature with the same name X <br/>3. create assign the feature to a product<br/> 4. Create a feature value for both created features <br/>5. Open a product in edit mode<br/> 6. Add the two created feature values<br/><br/>
| UI Tests          | 🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/22104649874 
| Fixed issue or discussion?     | Fixes #40703
| Related PRs       | 
| Sponsor company   | Codencode snc

---
### Note
This is a backport of https://github.com/PrestaShop/PrestaShop/pull/37882

---
 ### Attached videos:
 **feature creation** 
 
  [creazione.webm](https://github.com/user-attachments/assets/ec33f616-fdc2-4653-8daa-623dfcd330bb)
  
 **product edit** 
 
[modifica product.webm](https://github.com/user-attachments/assets/6645c6a4-abeb-444c-a528-11b0d460d438)

### CODE REVIEW

File: src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php [hunk 1]
```diff
@@ -66,7 +66,8 @@ public function getChoices()
         );
         $this->cacheFeatureChoices = [];
         foreach ($features as $feature) {
-            $this->cacheFeatureChoices[$feature['localized_names'][$contextLangId]] = $feature['id_feature'];
+            $featureName = sprintf('%s (#%d)', $feature['localized_names'][$contextLangId], $feature['id_feature']);
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php]: @Hlavtox has developed a generic tool for this kind of use cases `FormChoiceFormatter::formatFormChoices` It checks if there are duplicates and prepends the ID automatically only when it's needed

I think it should fit your use case nicely

Comment (Codencode) [reply src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php]: @jolelievre 

Yes @Hlavtox, you had pointed it out to me on Slack, but since this issue has been resolved in version 9.1.x and given that version 9.0.4 likely won't be released, I didn’t update it further.
Actually, it’s better if I update it.
Thank you!

Comment (Codencode) [reply src/Adapter/Form/ChoiceProvider/FeaturesChoiceProvider.php]: @jolelievre done!

**Review by jolelievre — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @Codencode, 

Thanks for your PR, i tested it and it's good for me 


https://github.com/user-attachments/assets/a056b38b-8d77-4345-b255-f4ffbd44d3b2



I'm waiting automated tests to approve the PR.

Thanks

**Comment by Codencode** [comment]
~~@SiraDIOP can you restart the UI tests?
Thanks~~

**Comment by Codencode** [comment]
@SiraDIOP your UI tests weren't finalized, so I recreated them and they're all green now.

**Comment by Hlavtox** [comment]
Thank you @Codencode & @SiraDIOP :-)))
