### PR TITLE
Fix generation of nightlies on develop branch

### LINKED ISSUE #30285: Generation of nightlies is broken on `develop` branch
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Docker image `prestashop/prestashop:nightly` cannot start properly at the moment, because there is no nightly release to download and install.

It seems the workflow generating these images is broken for 17 days, and the bucket storing the artifacts has an automatic cleaning process that removes files older than 15(?) days.

### Expected behavior

_No response_

### Steps to reproduce

* Run `php tools/build/CreateRelease.php --destination-dir=/tmp/ps-release` from the root folder of PrestaShop
* The version won't be found and the generation will fail.

### PrestaShop version(s) where the bug happened

8.0.0 (Nightly)

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Nightlies generation [appears to be broken](https://github.com/PrestaShop/PrestaShop/actions/workflows/cron_nightly_build.yml) since [Version class has been introduced](https://github.com/PrestaShop/PrestaShop/commit/8632cf0469e0c3056ab3b23d1a0e3c0abc2479e7). This PR changes the source file when it retrieves the Version constant.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30285
| Related PRs       | /
| How to test?      | Running `php tools/build/CreateRelease.php --destination-dir=/tmp/ps-release` must now succeed.
| Possible impacts? | /

### CODE REVIEW

**Review by sowbiba — DISMISSED** [review]
Perfect. Thanks @Quetzacoalt91

File: tools/build/Library/ReleaseCreator.php [hunk 1]
```diff
@@ -370,7 +370,7 @@ protected function setConfigDefinesConstants()
      */
     protected function getCurrentVersion()
     {
-        $kernelFile = $this->projectPath.'/app/AppKernel.php';
+        $kernelFile = $this->projectPath.'/src/Core/Version.php';
         $matches = [];
```
Comment (FabienPapet) [inline tools/build/Library/ReleaseCreator.php]: Maybe we can require the file and load the constant value instead of parsing the file ?

File: tools/build/Library/ReleaseCreator.php [hunk 2]
```diff
@@ -370,7 +370,7 @@ protected function setConfigDefinesConstants()
      */
     protected function getCurrentVersion()
     {
-        $kernelFile = $this->projectPath.'/app/AppKernel.php';
+        $kernelFile = $this->projectPath.'/src/Core/Version.php';
```
Comment (sowbiba) [inline tools/build/Library/ReleaseCreator.php:373]: Nice idea from @amaury-hanser 
Maybe, to not disturb generation of nightlies for the previous versions we can search in class Version and if $matches is empty, search in AppKernel

File: tools/build/Library/ReleaseCreator.php (hunk 1 above)
Comment (Quetzacoalt91) [reply tools/build/Library/ReleaseCreator.php]: Well, I would not make too many changes in this PR as I want to fix an issue for people relying on the nightly first.

Plus, we try to generate a release here from the source file **only**. Composer is not supposed to be run yet, so the autoloader cannot work to load other files such as the Version class. That why this "dirty" solution was chosen in the first place.

Comment (FabienPapet) [reply tools/build/Library/ReleaseCreator.php]: There is no need for composer here

```
require_once $this->projectPath.'/src/Core/Version.php';
return \PrestaShop\PrestaShop\Core\Version::VERSION;
```

Comment (Quetzacoalt91) [reply tools/build/Library/ReleaseCreator.php]: Very well, here you go

**Review by FabienPapet — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by yanmakouf — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @Quetzacoalt91,

It is ok :heavy_check_mark: 

image

I tried to install the zip created => OK
image

I tried to make an upgrade from PS1787 to the new zip created & .XML => OK

Thanks!

**Comment by matks** [comment]
Thank you @Quetzacoalt91
