### PR TITLE
Do not reject cart creation if no cookie, only exclude bots

### LINKED ISSUE #15878: Bug add to cart without cookie session
#### Describe the bug
When my cookie session is not generate, i can not add product to the cart at first time. 
The popin add to cart is empty. 

#### Steps to reproduce 
1- Go to http://demo.prestashop.com/#/en/front on a product page
2- flush your cookies
3- add the product to the cart 
You'll see the confirmation popin empty.

**Screenshots**

https://drive.google.com/file/d/1t8EbiJ3S5KvcSGotq9Lxr_gJbUKPBmCW/view

cookie
cart

#### Additional infos:

- Prestashop version: 1.7.7.2
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by psyray**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix #15878 - Cart not updated if a customer doesn't have cookie.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #15878.
| How to test?      | See @khouloudbelguith [screencast](https://drive.google.com/file/d/1t8EbiJ3S5KvcSGotq9Lxr_gJbUKPBmCW/view) on #15878, problem is not present anymore.
| Possible impacts? | Maybe ghost cart could be created by bots not listed in the filter, so filter update is required regularily.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25972)

### CODE REVIEW

File: controllers/front/CartController.php [hunk 1]
```diff
@@ -238,7 +238,7 @@ public function postProcess()
     protected function updateCart()
     {
         // Update the cart ONLY if $this->cookies are available, in order to avoid ghost carts created by bots
```
Comment (matks) [inline controllers/front/CartController.php]: As you modify the code below, we should remove this comment because it is not accurate anymore.

**Review by matks — COMMENTED** [review]
Thank you for the PR I see you removed the check on cookie existence and replaced it by "is it a bot" check. It makes sense, when reading issue content https://github.com/PrestaShop/PrestaShop/issues/15878 .

PR is good for me 👍  but there is a little comment we should update because it becomes inaccurate when we apply your changes. Can you please remove the comment 😉  and then I approve the PR.

File: controllers/front/CartController.php (hunk 1 above)
Comment (psyray) [reply controllers/front/CartController.php]: Maybe we should just change, like this, to comment why this check was there, instead of remove it ?
Tell me
```
// Update the cart ONLY if it's not a bot, in order to avoid ghost carts
```

**Comment by psyray** [comment]
> Thank you for the PR I see you removed the check on cookie existence and replaced it by "is it a bot" check. It makes sense, when reading issue content #15878 .

FYI, the method `Cookie::exists()` is now orphan, so I let you check and decide if you want to keep it

File: controllers/front/CartController.php (hunk 1 above)
Comment (psyray) [reply controllers/front/CartController.php]: @matks ping !

Comment (psyray) [reply controllers/front/CartController.php]: I have updated comment

**Comment by matks** [comment]
> > Thank you for the PR I see you removed the check on cookie existence and replaced it by "is it a bot" check. It makes sense, when reading issue content #15878 .
> 
> FYI, the method `Cookie::exists()` is now orphan, so I let you check and decide if you want to keep it

It has to stay. Else it's a Breaking Change. A module might rely on it.

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
let's wait for CI before sending this PR in QA 👍

File: classes/Connection.php [hunk 2]
```diff
@@ -138,9 +150,8 @@ public static function setPageConnection($cookie, $full = true)
...
-            // This is a bot : don't log connection
+        // This is a bot : don't log connection
+        if(self::isBot()) {
```
Comment (kpodemski) [inline classes/Connection.php]:
```suggestion
        if (static::isBot()) {
```

Comment (psyray) [reply classes/Connection.php]: Corrected

File: classes/Connection.php [hunk 3]
```diff
@@ -130,6 +130,18 @@ public static function setPageConnection($cookie, $full = true)
         ];
     }
 
+    /**
+     * Check if the current visitor is a bot
+     * 
+     * @return boolean
+     */
+    public static function isBot() {
```
Comment (kpodemski) [inline classes/Connection.php]:
```suggestion
    public static function isBot(): bool
    {
```

File: classes/Connection.php [hunk 4]
```diff
@@ -130,6 +130,18 @@ public static function setPageConnection($cookie, $full = true)
         ];
     }
 
+    /**
+     * Check if the current visitor is a bot
+     * 
+     * @return boolean
```
Comment (kpodemski) [inline classes/Connection.php]:
```suggestion
     * @return bool
```

File: classes/Connection.php [hunk 5]
```diff
@@ -130,6 +130,18 @@ public static function setPageConnection($cookie, $full = true)
...
+     */
+    public static function isBot() {
+            if (isset($_SERVER['HTTP_USER_AGENT'])
```
Comment (kpodemski) [inline classes/Connection.php]:
```suggestion
        if (isset($_SERVER['HTTP_USER_AGENT'])
```

**Comment by kpodemski** [comment]
You have some errors coming from the cs-fixer.

**Comment by psyray** [comment]
Errors fixed

**Comment by PierreRambaud** [comment]
> Errors fixed

Could you run the php-cs-fixer command, seems there are still some errors ^^

**Comment by psyray** [comment]
@PierreRambaud
It's good now, all checks passed ;)

**Review by kpodemski — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by psyray** [comment]
@PierreRambaud @kpodemski 
Ping !
Merge ?

**Comment by matks** [comment]
@psyray this PR needs to be tested by QA team first 😉  so the 'waiting for QA' label has been applied

**Comment by marwachelly** [comment]
Hello,
The behavior is as expected now:
https://www.awesomescreenshot.com/video/5814750?key=203e0ea772563ea46721d0c9ae9fd483
Thanks,

**Comment by Progi1984** [comment]
Thanks @psyray & @marwachelly

**Comment by davidcylke** [comment]
I tried to implement this, but ghost carts are still created. Anything else I should do when used in multistore?

**Comment by psyray** [comment]
Please open an issue with full details
Or try to update to latest PS version.
I've personally implement my changes and it's working fine
