### PR TITLE
Color picker doesn't recognize html color name on page load, in BO

### LINKED ISSUE #20108: [BO] Color picker doesn't recognize html color name on page load
#### Describe the bug

In BO, the color picker allows to pick a color, but also to write an HTML color name, like "blue" or "red" for example. When we type "red", the color automatically switches to red, this is working, and the value"red" is properly saved when we push the form.

But if you go back, in edit mode, the field will have the value "red", which is correct, but the color will remain black, it seems like the colorpicker doesn't update the color on page load when it is an HTML color name, it works fine with hexa codes.

#### Expected behavior

On page load, when the colorpicker's value is a color HTML name, like "red", the color picker should be red.

#### Steps to Reproduce

Let's take the order state creation page as an example

1. Go to order state creation page (BO > Shop Parameters > Orders > Order State tab > Create a new order state)
2. Write "red" in the color picker field, it will be instantly recognized, and the color will switch to red 
3. Save the order state
4. In the BO order state list page (BO > Shop Parameters > Orders > Order State tab), edit the newly created order state
5. There is "red" written in the colorpicker field, the value was properly saved, but the color picker didn't change its color on pageload.

**Screenshots**

When writing the HTML color name, like "red", the color is updated instantly:
Capture d’écran 2020-07-08 à 17 27 23

When loading the page, the value is saved, but the color remains black:
Capture d’écran 2020-07-08 à 17 27 40

#### Additional information

* PrestaShop version: 1.7.6.x, 1.7.7.x, develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | In BO, the color picker allows to pick a color, but also to write an HTML color name, like "blue" or "red" for example. When we type "red", the color automatically switches to red, this is working, and the value"red" is properly saved when we push the form. But if you go back, in edit mode, the field will have the value "red", which is correct, but the color will remain black, it seems like the colorpicker doesn't update the color on page load when it is an HTML color name, it works fine with hexa codes. by @matthieu-rolland 
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20108
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/20108 by @matthieu-rolland .

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20148)

### CODE REVIEW

**Comment by PululuK** [comment]
ping @NeOMakinG

**Comment by arouiadib** [comment]
+1 for the quality of the description of the PR.
Just a question I always ask myself but never found opportunity to ask someone else.

Is it allowed to modify such file in the context of PS project? 
I see in the beginning:

```
/*
  mColorPicker
  Version: 1.0 r34
  Copyright (c) 2010 Meta100 LLC.
  http://www.meta100.com/
  Licensed under the MIT license
  http://www.opensource.org/licenses/mit-license.php
*/

```

Thanks in advance for information

**Comment by PululuK** [comment]
> +1 for the quality of the description of the PR.
> Just a question I always ask myself but never found opportunity to ask someone else.
> 
> Is it allowed to modify such file in the context of PS project?
> I see in the beginning:
> 
> ```
> /*
>   mColorPicker
>   Version: 1.0 r34
>   Copyright (c) 2010 Meta100 LLC.
>   http://www.meta100.com/
>   Licensed under the MIT license
>   http://www.opensource.org/licenses/mit-license.php
> */
> ```
> 
> Thanks in advance for information

Hi @arouiadib,
I think it's legitimate
See please : https://opensource.org/licenses/MIT
@matks @ttoine do you want to add something ?
Thanks

**Review by NeOMakinG — DISMISSED** [review]
Looks fine for me @PululuK, does the fact that you update it on keyup doesn't cause any errors when the color isn't completely written ?

File: js/jquery/plugins/jquery.colorpicker.js [hunk 1]
```diff
@@ -63,6 +59,16 @@
     return this;
   };
 
+ $.fn.mColorPicker.setTextColor = function(element) {
```
Comment (PierreRambaud) [inline js/jquery/plugins/jquery.colorpicker.js]:
```suggestion
  $.fn.mColorPicker.setTextColor = function(element) {
```

File: js/jquery/plugins/jquery.colorpicker.js [hunk 2]
```diff
@@ -63,6 +59,16 @@
...
+    try {
+      element.css({
+      'background-color': element.val()
+    }).css({
+      'color': $.fn.mColorPicker.textColor(element.css('background-color'))
+      }).trigger('change');
+    } catch (r) {}
+  };
```
Comment (PierreRambaud) [inline js/jquery/plugins/jquery.colorpicker.js]:
```suggestion
    try {
      element.css({
        'background-color': element.val()
      }).css({
        'color': $.fn.mColorPicker.textColor(element.css('background-color'))
      }).trigger('change');
    } catch (r) {}
    };
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Nice catch, but sorry indentation is broken :sweat_smile:

File: js/jquery/plugins/jquery.colorpicker.js [hunk 3]
```diff
@@ -63,6 +59,16 @@
...
 
+  $.fn.mColorPicker.setTextColor = function(element) {
+    try {
+      element.css({
+        'background-color': element.val()
+      }).css({
+        'color': $.fn.mColorPicker.textColor(element.css('background-color'))
+      }).trigger('change');
+    } catch (r) {}
+    };
```
Comment (PierreRambaud) [inline js/jquery/plugins/jquery.colorpicker.js]:
```suggestion
  };
```
Oups adding unneeded spaces, my bad ^^

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Simple question @PululuK, is it possible to set the color on ready but outside the source file ? I think yes, but not sure

**Comment by eternoendless** [comment]
This lib has been updated since r34 as well https://github.com/meta100/mColorPicker/blob/master/javascripts/mColorPicker.js

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

It is ok :heavy_check_mark: https://drive.google.com/file/d/1Ti5_tSWlT9A9ItNTniQsJYqewLUbqqxh/view?usp=sharing
Thanks!

**Comment by PululuK** [comment]
> Simple question @PululuK, is it possible to set the color on ready but outside the source file ? I think yes, but not sure


Hi @NeOMakinG ,

Yes I think it's possible, maybe here :
```
admin-dev/themes/default/template/helpers/form/form.tpl
admin-dev/themes/default/template/helpers/options/options.tpl
```

@eternoendless @NeOMakinG
But this file has already been modified by the Prestashop team
https://github.com/PrestaShop/PrestaShop/blob/develop/js/jquery/plugins/jquery.colorpicker.js

**Comment by matthieu-rolland** [comment]
thanks @PululuK !

**Comment by PululuK** [comment]
@matthieu-rolland  @eternoendless  @NeOMakinG 
If you want to update this library I can open a new PR for this, but I think it could be BC for some modules for example.
WDYF ?
