### PR TITLE
Automatically add dni field in Address format for countries which need it

### LINKED ISSUE #13487: PrestaShopException when we add DNI option
**Describe the bug**
When the DNI option is activated there is an error in front office when you try to add an address. In 1.7.5.1 there is no error.

**To Reproduce**
1. Go to International -> Zone 
2. Create a country with DNI required 
3. Go to front add a product to the cart and start the order process 
4. When you add the adresse and validate see error

**Screenshots**
Capture d’écran 2019-04-19 à 10 54 56

**Additionnal information**
PrestaShop version: 1.7.6.X
PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Automatically add dni field in Address format for countries which need it
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13487
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13578)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
It looks like a hack, isn't it? Shouldn't we find the `dni` in the `PREFIX_address_format` for the related country instead?

File: classes/AddressFormat.php [hunk 1]
```diff
@@ -590,6 +590,9 @@ public function getFormat($idCountry)
         if (empty($out)) {
             $out = $this->getFormatDB(Configuration::get('PS_COUNTRY_DEFAULT'));
         }
+        if (Country::isNeedDniByCountryId($idCountry) && false === strpos($out, 'dni')) {
+            $out .= "\ndni";
```
Comment (PierreRambaud) [inline classes/AddressFormat.php]:
```suggestion
            $out .= PHP_EOL . 'dni';
```

Comment (jolelievre) [reply classes/AddressFormat.php]: I actually wanted to use it but since the "\n" is used in `AddressFormat::getOrderedAddressFields`
 I prefered to stick with the explicit `\n` Are we sure PHP_EOL always === "\n" on any platform?

https://github.com/PrestaShop/PrestaShop/blob/0125a82acee6942c9dc522743dee2ce0dff32e64/classes/AddressFormat.php#L518

Comment (jolelievre) [reply classes/AddressFormat.php]: I'm not sure but on Windows it might be `\r\n`

Comment (PierreRambaud) [reply classes/AddressFormat.php]: we need to change the \n everywhere we can :/ it's not cross platform

Comment (jolelievre) [reply classes/AddressFormat.php]: It depends on how the field is generated and stored as well, especially on creation (the value in database seems to be `\n`)

Comment (jolelievre) [reply classes/AddressFormat.php]: Ok done!

File: controllers/admin/AdminCountriesController.php [hunk 2]
```diff
@@ -180,7 +180,7 @@ public function renderForm()
         ];
 
         foreach ($default_layout_tab as $line) {
-            $default_layout .= implode(' ', $line) . "\r\n";
+            $default_layout .= implode(' ', $line) . PHP_EOL;
```
Comment (PierreRambaud) [inline controllers/admin/AdminCountriesController.php:183]: :+1:

Comment (jolelievre) [reply controllers/admin/AdminCountriesController.php:183]: Approved? ^^

**Review by PierreRambaud — APPROVED** [review]
