### PR TITLE
Twig extension for multistore shop context URLs

### LINKED ISSUE #24818: Bad redirection on shop context links in BO
#### Describe the bug

In BO, when the shop is configured not to use url tokens, clicking on a shop context link will redirects to the BO's home page.

#### Expected behavior

It should switch context and redirect to the same page.

#### Steps to Reproduce

- Disable URL tokens, by writing `SetEnv _TOKEN_ disabled` in your `.htaccess` file, at the root of your prestashop project
- Activate multistore
- Add at least one shop
- Go on a page where the multistore header will appear, ex: maintenance configuration page
- In the multistore header dropdown, click on a shop's link to switch context, you will be redirected to BO's home page

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Create twig extension to be sure URLs are properly created when using the `setShopContext` parameter in URLS. The problem exists when there is nothing in the URL, we are not able to do `&setShopContext` without `?`. Same with javascript behaviour, centralized it into one function instead of custom concatenations.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24818
| How to test?      | Follow ticket instruction.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24851)

### CODE REVIEW

File: src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+            new SimpleFunction('multistore_url', [$this, 'generateUrl']),
+            new SimpleFunction('multistore_group_url', [$this, 'generateGroupUrl']),
+            new SimpleFunction('multistore_shop_url', [$this, 'generateShopUrl']),
+        ];
+    }
+
+    /**
+     * Generate URL from current request for a specific shop group.
+     *
+     * @param ?ShopGroup $group
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php]:
```suggestion
     * @param ?int $id
```

**Comment by matthieu-rolland** [comment]
One small feedback to make phpstan happy, otherwise LGTM 👍

File: src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php]:
```suggestion
     * @param int|null $group
```

File: src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+     * @param ?string $prefix
```
Comment (Progi1984) [inline src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php]:
```suggestion
     * @param string|null $prefix
     * @return string
```

File: src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+        return $currentRequest->getBaseUrl()
+            . $currentRequest->getPathInfo()
+            . '?'
+            . http_build_query($currentRequest->query->all());
+    }
+
+    /**
+     * Generate URL from current request for a specific shop group.
+     *
+     * @param ?ShopGroup $group
```
Comment (Progi1984) [inline src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php]:
```suggestion
     * @param ShopGroup|null $group
```

File: src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+     */
+    public function generateGroupUrl(?ShopGroup $group = null): string
+    {
+        return $this->generateUrl($group->getId(), 'g-');
+    }
+
+    /**
+     * Generate URL from current request for a specific shop.
+     *
+     * @param ?Shop $shop
```
Comment (Progi1984) [inline src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php]:
```suggestion
     * @param Shop|null $shop
```

File: src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+use PrestaShopBundle\Entity\Shop;
+use PrestaShopBundle\Entity\ShopGroup;
+use Symfony\Component\HttpFoundation\RequestStack;
+use Twig\Extension\AbstractExtension;
+use Twig_SimpleFunction as SimpleFunction;
+
+/**
+ * Class MultiStoreUrlExtension is responsible for providing a way to generate url with setShopContext parameter.
+ */
+class MultistoreUrlExtension extends AbstractExtension
```
Comment (Progi1984) [inline src/PrestaShopBundle/Twig/Extension/MultistoreUrlExtension.php:40]: Could you add unit tests ?

**Review by Progi1984 — COMMENTED** [review]
An unit test missing and it's ok

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @PierreRambaud !

Your fix works fine now, all links are OK : 

* Link to shop in header : OK
* Link to shop in header dropdown : OK
* Link to context (shop) in header : OK
* Link to context (shop) in search in header : OK
* Link to context (shop) in dropdown : OK
* Link to context (shop) in search in dropdown : OK
* Link to context (group) in header : OK
* Link to context (group) in search in header : OK
* Link to context (group) in dropdown : OK
* Link to context (group) in search in dropdown : OK
* Link to context (all shops) in header : OK
* Link to context (all shops) in dropdown : OK

So it's QA :heavy_check_mark: !

(And I now @prestonBot , "QA OK without required approvals" :P )

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @PierreRambaud and @Robin-Fischer-PS !
