### PR TITLE
Test id_manufacturer index before accessing it

### LINKED ISSUE #30272: Error in cart - removing products in debug mode and specific language doesn't work
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This issue occurs since Prestashop 8, in Classic theme. If you delete product(s) from cart on cart page, nothing happens after clicking the remove button. Only after manually refreshing the page, the products will disappear. The problem is visible only in debug mode (works ok in production mode) and only if you choose language other then English (try with French).

See this video: https://www.dropbox.com/s/kr09za0c3qcf6k0/Test%20-%20Google%20Chrome%202022-11-11%2021-07-01.mp4?dl=0

### Expected behavior

Cart should be reloaded after deleting product on cart page. 

### Steps to reproduce

1. Setup Debug mode ON
2. Clear smarty cache
3. Choose language other then English.
4. Add products to cart, go to cart page
5. Try to remove product from cart, nothing happens (unless you refresh the page manually)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.9

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Problem reported in this issue https://github.com/PrestaShop/PrestaShop/pull/30194 was a regression on develop and 8.0.x that was not caught. It fixed it on develop but the problem remained in 8.0.x. This PR is a backport of this change. Simple change and already tested, doesn't need QA.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30272
| Related PRs       | -
| How to test?      | See reproducible scenario on the issue.
| Possible impacts? | no

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Comment by Hlavtox** [comment]
@PrestaShop/qa-team Hello! :-) Can this be tested only by automatic tests? It's the same code as in the related PR and a tiny change.

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

I have checked your PR. I have failed jobs when I have launched the automated tests here 
https://github.com/HanaRebaiQA/testing_pr/actions/runs/3462695107/jobs/5781926414 

In 8.0.x without PR, there is no failure in all tests
ping @PrestaShop/qa-automation Could you please check it ?

Thank You!

**Comment by Hlavtox** [comment]
@HanaRebaiQA I think that a code that checks for empty manufacturer can't cause failed tests...

**Review by yanmakouf — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Hlavtox 

I have checked your PR. I have failed jobs when I have launched the automated tests here 
https://github.com/HanaRebaiQA/testing_pr/actions/runs/3462695107/jobs/5781926414 

In 8.0.x without PR, there is no failure in all tests
ping @PrestaShop/qa-automation Could you please check it ?

Thank You!

**Comment by kpodemski** [comment]
@Hlavtox maybe rebase PR?

**Comment by Hlavtox** [comment]
@kpodemski Cannot we just merge it when it's one empty check that works in a different branch??

File: classes/Product.php [hunk 1]
```diff
@@ -5516,7 +5516,7 @@ public static function getProductProperties($id_lang, $row, Context $context = n
         $row['category'] = Category::getLinkRewrite((int) $row['id_category_default'], (int) $id_lang);
         $row['category_name'] = Db::getInstance()->getValue('SELECT name FROM ' . _DB_PREFIX_ . 'category_lang WHERE id_shop = ' . (int) $context->shop->id . ' AND id_lang = ' . (int) $id_lang . ' AND id_category = ' . (int) $row['id_category_default']);
         $row['link'] = $context->link->getProductLink((int) $row['id_product'], $row['link_rewrite'], $row['category'], $row['ean13']);
-        $row['manufacturer_name'] = (int) $row['id_manufacturer'] > 0 ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;
+        $row['manufacturer_name'] = !empty($row['id_manufacturer']) ? Manufacturer::getNameById((int) $row['id_manufacturer']) : null;
```
Comment (FabienPapet) [inline classes/Product.php:5519]: I'm not sure about what you are fixing here

```
(int) '' === 0
(int) false === 0
(int) null === 0
``` 

So if I'm not wrong `(!empty($row['id_manufacturer']))` and `(int) $row['id_manufacturer'] > 0` are the same :/ (if `$row['id_manufacturer']` exists)

Unless i'm missing something

Comment (Hlavtox) [reply classes/Product.php:5519]: The problem is that this key doesn't exist in cart context. `id_manufacturer` must be present in the array for casting to work.

Comment (FabienPapet) [reply classes/Product.php:5519]: That is a `empty` behaviour i was not aware of (and it confirms for me that `empty` is 🤢).
 Fix is good for me

Comment (Hlavtox) [reply classes/Product.php:5519]: `empty` is amazing! :D Oneline check for everything, in most scenarios.

**Comment by Progi1984** [comment]
@HanaRebaiQA It's an approval for me. I detect an error in `8.0.x` : #30358 but it's not relative to this PR.

**Review by Progi1984 — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @Hlavtox @Progi1984
