### PR TITLE
Remove inline-style from form_row of the UIKit and adapt js

### LINKED ISSUE #24376: Invalid inline style in PrestaShop UI Kit symfony form theme
#### Describe the bug

In the prestashop UI kit form theme some inline code has been added in. the `form_row` block:

```twig
    <div class="{{ block('form_row_class') }}{{ block('widget_type_class') }}{% if (not compound or force_error|default(false)) and not valid %} has-error{% endif %}"{% if (attr.visible is defined and not attr.visible) %} style="display: none;"{% endif %}>
```

This part in particular `{% if (attr.visible is defined and not attr.visible) %} style="display: none;"{% endif %}` we should use a class instead (like `d-none`) This option seems to be only used in `PrestaShopBundle\Form\Admin\Sell\Address\CustomerAddressType` (strangely not in the other address types).

This should be fixed in the theme, but maybe also in the js of the customer address (if we use a class the js might just use `.show()/.hide()` and it won't work any more).

#### Expected behavior

Same behaviour but with clean theme without hard coded inline style.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | We're using inline-style in form_row of the UIKit, this should be removed to use a bootstrap class
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24376.
| How to test?      | Go on create customer address page, select united state, state field should appear, if you select France, it should disappear
| Possible impacts? | Customer address creation form

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24541)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @NeOMakinG

File: admin-dev/themes/new-theme/js/components/country-state-selection-toggler.js [hunk 1]
```diff
@@ -74,27 +74,32 @@ export default class CountryStateSelectionToggler {
...
+      });
   }
 
   toggle() {
     if (this.$countryStateSelector.find('option').length > 0) {
-      this.$stateSelectionBlock.fadeIn();
       this.$stateSelectionBlock.removeClass('d-none');
     } else {
-      this.$stateSelectionBlock.fadeOut();
+      this.$stateSelectionBlock.addClass('d-none');
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/components/country-state-selection-toggler.js]: Please change that with a `toggle`

**Review by Progi1984 — COMMENTED** [review]
A small test

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !!
Thanks @NeOMakinG !!

**Comment by PululuK** [comment]
Thanks @NeOMakinG @SD1982
