### PR TITLE
Bug fix for number of decimals in product price

### LINKED ISSUE #23868: X number of decimals are only displayed if the product price has X decimals
#### Decimals for currencies not working on PresstaShop 1.7.7.3

I've set the Decimals for Omani Rial to **3**:

Screen Shot 2021-04-01 at 4 01 29 PM

But it's not working:

Screen Shot 2021-04-01 at 4 04 32 PM

I've also cleared the cache (removing **_var/cache/prod - dev_**), but the problem persists.

### PR DESCRIPTION
**Pull request by samberrry**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Decimals feature does not work.By default it's set to two, and it's stuck to 2 and it does not change according to the configuration in backoffice International->Localization->Currencies->edit for a currency->Decimals. So, this pull request fixes this issue. Actually the problem has two parts. One which is fixed in Product.php is that the number of Decimals is fixed to two, and another issue is that the extra 0 won't be added to match the number of decimals chosen in configuration which is fixed in Factory.php file.
| Type?             | bug fix 
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23868
| How to test?      | Change decimals in backoffice and check the product price in front office
| Possible impacts? | I really got the root cause, exactly the points where the problem comes from

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24320)

### CODE REVIEW

**Comment by samberrry** [comment]
@sowbiba new PR created on 1.7.7.x branch, and closed: https://github.com/PrestaShop/PrestaShop/pull/23912

**Review by sowbiba — DISMISSED** [review]

**Comment by sowbiba** [comment]
Great !!! Thanks @samberrry

File: tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php [hunk 1]
```diff
@@ -214,6 +214,90 @@ public function testBuildPriceSpecificationWithMax($data, $expected)
...
+    /**
+     * Given a valid CLDR locale
+     * Given a Max Fractions digits to display in a number's decimal
+     * Given a boolean to define if we should group digits in a number's integer part
+     * Given an integer to specify max fraction digits
+     * Then calling buildPriceSpecification() should return an NumberSpecification
+     *
+     * @dataProvider getPriceData
+     */
+    public function testBuildPriceSpecificationWithPrecisionFallback($data, $expected)
```
Comment (Progi1984) [inline tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]:
```suggestion
    public function testBuildPriceSpecificationWithPrecisionFallback(array $data, array $expected): void
```

File: tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php [hunk 2]
```diff
@@ -214,6 +214,90 @@ public function testBuildPriceSpecificationWithMax($data, $expected)
...
+                        $data[0] => 'Euro',
+                    ]
+                ),
+                3,
+                true,
+                $maxFractionDigits
+            );
+            $expected['maxFractionDigits'] = $maxFractionDigits;
+            $expected['minFractionDigits'] = $expectedMinFractionDigits;
+            $this->assertEquals(
```
Comment (Progi1984) [inline tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]:
```suggestion
            self::assertEquals(
```

File: tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php [hunk 3]
```diff
@@ -214,6 +214,90 @@ public function testBuildPriceSpecificationWithMax($data, $expected)
...
+                $expected,
+                $specification->toArray()
+            );
+            $this->assertEquals($specification->getMaxFractionDigits(), $maxFractionDigits);
```
Comment (Progi1984) [inline tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]:
```suggestion
            self::assertEquals($specification->getMaxFractionDigits(), $maxFractionDigits);
```

**Review by Progi1984 — COMMENTED** [review]
Small improvements

**Comment by samberrry** [comment]
@sowbiba welcome ;)

**Review by matthieu-rolland — DISMISSED** [review]
thank you @samberrry for this quality PR 👍

**Comment by samberrry** [comment]
@matthieu-rolland welcome ;)

**Comment by khouloudbelguith** [comment]
Hi @samberrry,

>and another issue is that the extra 0 won't be added to match the number of decimals chosen in configuration which is fixed in Factory.php file.

I have the same issue after a fresh install of this PR with English language & France country, here are the steps to reproduce the issue:
Fresh install with English language & France country

1. Go to BO > International > Localization > currencies page
2. Edit the Euro currency
3. Change Decimals to 3 and save
image
4. Go to FO & Euro selected as a currency
5. See the error, products with price `xx.xx` are still displayed `xx.xx` instead of `xx.xx0`
image

Also, if a product has a specific price, the base price has only 2 decimals, for example, the first product `Hummingbird printed t-shirt`
It is displayed `22.68` instead of `22.680`
image

The same issue with the discount amount flag:
Steps to reproduce the issue:
1. Create a new product 
2. In the Pricing tab, add a new specific price with discount = 1 euro 
image
3. Go to FO and check the product: the flag is NOK in the product details page, category list page, search list page,..
image

The same issue in the checkout process & the Shipping amount also
Steps to reproduce the issue:
1. Create a product with price tax included = 1.555 euro
2. Go to FO & Add the product to the cart with quantity = 2
3. Modal `Product successfully added` => NOK 
image
4. Click Proceed to checkout => see error
image
5. Click proceed to checkout 
image
6. Place Order => See error
image
7. Go to `Your account > Order history page`
image
8. Click on details
image


Thank you!

**Comment by samberrry** [comment]
@khouloudbelguith thanks. I will check

**Comment by samberrry** [comment]
@khouloudbelguith please check it again. The issue is fixed.

**Comment by Progi1984** [comment]
@samberry It seems that the CI is broken. Could you fix it ?

**Comment by Progi1984** [comment]
@samberry It seems that the CI is broken. Could you fix it ?

**Comment by samberrry** [comment]
@Progi1984 I have no idea about it. I would be thankful if you check it.

**Comment by samberrry** [comment]
@Progi1984 in this [commit](https://github.com/PrestaShop/PrestaShop/pull/24320/commits/6ccc8f146a22ccb6f18bfdf7fc8327a59ffaaccb) I've just committed the line which previously I changed and in the previous [commit](https://github.com/PrestaShop/PrestaShop/pull/24320/commits/535b624d9ef522f4b5d3fc1c306e4ecb6a883236) (in Factory.php) the CI did not fail, I don know why a test and job is failing..

**Comment by Progi1984** [comment]
@samberrry I think the `intval` is a problem. It transforms the value of  `$currency->getDecimalPrecision()` in `int`.

**Comment by samberrry** [comment]
@Progi1984 as we need to cast it to ``int`` because ``$minFractionDigits`` is an integer. Let me cast it with ``(int)`` instead of ``intval``.

File: src/Core/Localization/Specification/Factory.php [hunk 4]
```diff
@@ -113,7 +113,7 @@ public function buildPriceSpecification(
             $this->getNegativePattern($currencyPattern),
             $this->computeNumberSymbolLists($numbersSymbols),
             $maxFractionDigits ?? $this->getMaxFractionDigits($positivePattern),
-            $this->getMinFractionDigits($positivePattern),
+            is_int((int)$currency->getDecimalPrecision()) ? (int)$currency->getDecimalPrecision(): $this->getMinFractionDigits($positivePattern),
```
Comment (PierreRambaud) [inline src/Core/Localization/Specification/Factory.php]:
```suggestion
            is_int($currency->getDecimalPrecision()) ? (int) $currency->getDecimalPrecision(): $this->getMinFractionDigits($positivePattern),
```

Comment (samberrry) [reply src/Core/Localization/Specification/Factory.php]: this is the first version of the code and does not work, this will result the screenshots that @khouloudbelguith has sent above. We need this `int` cast to run `(int)$currency->getDecimalPrecision()` and fix the issue.
Thanks

Comment (PierreRambaud) [reply src/Core/Localization/Specification/Factory.php]: So the check is useless as casting something in int will always return an int oO

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
The condition is malformed, casting anything into int, will always return an int.
So,
`is_int((int) 'blablal')` will always be the.

I think there is something wrong in your PR

File: src/Core/Localization/Specification/Factory.php (hunk 4 above)
Comment (samberrry) [reply src/Core/Localization/Specification/Factory.php]: In the previous [PR](https://github.com/PrestaShop/PrestaShop/pull/23912) @sowbiba changed this line.

**Comment by samberrry** [comment]
@PierreRambaud you are right, let me change it a little.

**Comment by samberrry** [comment]
Still it does not work..

**Comment by samberrry** [comment]
even after removing intval and useless check for int

File: src/Core/Localization/Specification/Factory.php (hunk 4 above)
Comment (sowbiba) [reply src/Core/Localization/Specification/Factory.php]: I think the check has to be

is_int(toto) ? toto : somethingElse
No need to cast toto

Doing this, precision === '4' will result with *somethingElse*

If you want to allow strings that "look like integer" you can do
is_numeric(toto) ? (int) toto : somethingElse

Comment (sowbiba) [reply src/Core/Localization/Specification/Factory.php]:
```
var_dump(is_int(42)); //true
var_dump(is_int('42')); //false
var_dump(is_int('42.5')); //false
var_dump(is_int('42,5')); //false

var_dump(is_numeric(42)); //true
var_dump(is_numeric('42')); //true
var_dump(is_numeric('42.5')); //true
var_dump(is_numeric('42,5')); //false

var_dump(ctype_digit(42)); //false
var_dump(ctype_digit('42')); //true
var_dump(ctype_digit('42.5')); //false
var_dump(ctype_digit('42,5')); //false

**Comment by PierreRambaud** [comment]
> even after removing intval and useless check for int

The problem seems to come elsewhere

File: src/Core/Localization/Specification/Factory.php (hunk 4 above)
Comment (samberrry) [reply src/Core/Localization/Specification/Factory.php]: @sowbiba thanks, I will check the other forms to check the int val..

**Comment by samberrry** [comment]
> > even after removing intval and useless check for int
> 
> The problem seems to come elsewhere

yeah, I don know where. no idea

**Comment by samberrry** [comment]
@sowbiba thanks for your suggestions.. I tried them but not worked. I have no idea about this.

**Comment by sowbiba** [comment]
After research and tries, the display of trailing zeros is avoided by 2 implementations

1 - https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#L1973 : When we use `round`, the trailing zeros are automatically cleaned. We can fix that by doing ``` number_format(round($value, $places, $mode - 1), $places) ``` but it will change the return type :/

2 - When presenting the price, we use a Formatter that transforms the price to a Decimal object
https://github.com/PrestaShop/decimal/blob/master/src/DecimalNumber.php#L551 => trailing zeros are cleaned here too

**Comment by samberrry** [comment]
@sowbiba as I see there are still some prices with wrong trailing zeros, I mean that it seems that I've not corrected all prices. yeah?

**Comment by sowbiba** [comment]
> After research and tries, the display of trailing zeros is avoided by 2 implementations
> 
> 1 - https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#L1973 : When we use `round`, the trailing zeros are automatically cleaned. We can fix that by doing `number_format(round($value, $places, $mode - 1), $places)` but it will change the return type :/
> 
> 2 - When presenting the price, we use a Formatter that transforms the price to a Decimal object
> https://github.com/PrestaShop/decimal/blob/master/src/DecimalNumber.php#L551 => trailing zeros are cleaned here too

I was going the wrong way. We don't need to change the way prices are computed for calculations but the way it is presented. Your fix seems to work well

Capture d’écran de 2021-05-26 11-48-52

**Comment by samberrry** [comment]
> > After research and tries, the display of trailing zeros is avoided by 2 implementations
> > 1 - https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#L1973 : When we use `round`, the trailing zeros are automatically cleaned. We can fix that by doing `number_format(round($value, $places, $mode - 1), $places)` but it will change the return type :/
> > 2 - When presenting the price, we use a Formatter that transforms the price to a Decimal object
> > https://github.com/PrestaShop/decimal/blob/master/src/DecimalNumber.php#L551 => trailing zeros are cleaned here too
> 
> I was going the wrong way. We don't need to change the way prices are computed for calculations but the way it is presented. Your fix seems to work well
> 
> Capture d’écran de 2021-05-26 11-48-52

thanks @sowbiba yes the price presentation is ok. But I'm confused about why the CI is failing..

**Comment by sowbiba** [comment]
> > > After research and tries, the display of trailing zeros is avoided by 2 implementations
> > > 1 - https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Tools.php#L1973 : When we use `round`, the trailing zeros are automatically cleaned. We can fix that by doing `number_format(round($value, $places, $mode - 1), $places)` but it will change the return type :/
> > > 2 - When presenting the price, we use a Formatter that transforms the price to a Decimal object
> > > https://github.com/PrestaShop/decimal/blob/master/src/DecimalNumber.php#L551 => trailing zeros are cleaned here too
> > 
> > 
> > I was going the wrong way. We don't need to change the way prices are computed for calculations but the way it is presented. Your fix seems to work well
> > Capture d’écran de 2021-05-26 11-48-52
> 
> thanks @sowbiba yes the price presentation is ok. But I'm confused about why the CI is failing..

the previous test was is_int so '4' was evaluated to false. Now it's 'is_numeric'
That's why the CI failed. Fixed

**Comment by samberrry** [comment]
@sowbiba great. Thanks my friend.

**Review by jolelievre — DISMISSED** [review]

File: tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php [hunk 5]
```diff
@@ -214,6 +214,90 @@ public function testBuildPriceSpecificationWithMax($data, $expected)
...
+     * Then calling buildPriceSpecification() should return an NumberSpecification
+     *
+     * @dataProvider getPriceData
+     */
+    public function testBuildPriceSpecificationWithPrecisionFallback(array $data, array $expected): void
+    {
+        // if maxFractionDigits < minFractionDigits, minFractionDigits = maxFractionDigits
+        // see PrestaShop\PrestaShop\Core\Localization\Specification\Number
+        // The dataProvider provides minFractionDigits === 2
+        $precisions = [
```
Comment (PierreRambaud) [inline tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]: Why not using a dataProvider instead https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html?highlight=dataprovider#data-providers

Comment (Progi1984) [reply tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]: @samberrry Could you do it ? We can send your PR after this.

Comment (samberrry) [reply tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]: @Progi1984 let me check that.

Comment (samberrry) [reply tests-legacy/Unit/Core/Localization/Specification/FactoryTest.php]: done

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @samberrry,

I tried with a currency with:
decimals = 0
decimals = 2
decimals = 4
https://drive.google.com/file/d/1Q-SLnOeFcb5efumEK5YyTGwn5XS2UkSg/view?usp=sharing
=> ok

But when I tried with decimals = 1 => NOK

https://drive.google.com/file/d/1ynS5uLb2u3tIGypVJ6szChZ-HWgFBCU6/view?usp=sharing

Thanks to check and feedback.

**Comment by samberrry** [comment]
hi @khouloudbelguith thanks
I will check it.

**Comment by samberrry** [comment]
I confirm that there is issue with decimal = 1, I reproduced it.

**Comment by samberrry** [comment]
the above mentioned issue is fixed in the last commit.

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @samberrry,

It is ok :heavy_check_mark: 
I checked a currency with:

- decimals = 0
- decimals = 1
- decimals = 2
- decimals = 3
- decimals = 4
- decimals = 5
- decimals = 6

In the BO:

- Create an official currency
- Create an unofficial currency
- Import a pack

=> 
- Create orders with those currencies
- Check email

In the FO, I checked:

- Product details page
- Search page 
- Catalog page
- Modal shopping cart
- Shopping cart page
- Checkout page
- Final summary
- Order confirmation page
- Order history 

https://drive.google.com/file/d/13gGF5dj_BN9i7C9RDrgyRRVA4-7O-UpQ/view?usp=sharing
Thank you!

**Comment by Progi1984** [comment]
Thanks @samberrry & @khouloudbelguith

**Comment by samberrry** [comment]
Thanks @Progi1984 @khouloudbelguith and team.
