### PR TITLE
Fix old deleted customization fields copied after duplicating a product

### LINKED ISSUE #18086: An old deleted customization field is copied after duplicating a product
#### Describe the bug

After duplicating a product, an old deleted customization field is copied to the new product.

#### Expected behavior

The deleted customization field should not be copied to the new product

#### Steps to Reproduce

1. Go to BO => Products
2. Create a new product
3. In the options Tab => add a Customization (all type and could be required or not)
4. Go to the FO => Product details page => add the customization to the product
5. Go back to the BO => Last product created => delete the customization
6. Save
7. Duplicate this product
8. Check the copy of the product => the deleted customization field is copied to the new product

**Screenshots**

https://drive.google.com/file/d/11VFXdx2VUew_SWDYRi0WDj8FvtERf_Sd/view

#### Additional information

* PrestaShop version: 1.7.5.2, 1.7.6.4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Matt75**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | After duplicating a product, an old deleted customization field is copied to the new product.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/18086
| How to test?      | Follow scenario described in the issue
| Possible impacts? | --

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26415)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/Product.php [hunk 1]
```diff
@@ -5322,7 +5322,7 @@ protected static function _getCustomizationFieldsNLabels($product_id, $id_shop =
 
         $customizations = [];
         if (($customizations['fields'] = Db::getInstance()->executeS('
-            SELECT `id_customization_field`, `type`, `required`
+            SELECT `id_customization_field`, `type`, `required`, `is_deleted`
             FROM `' . _DB_PREFIX_ . 'customization_field`
             WHERE `id_product` = ' . (int) $product_id . '
             ORDER BY `id_customization_field`')) === false) {
```
Comment (Progi1984) [inline classes/Product.php:5331]: Why not select only not deleted customization fields ? 

That avoids to have all customization fields

**Review by Progi1984 — COMMENTED** [review]
@Matt75 I think you should improve the SQL query

File: classes/Product.php (hunk 1 above)
Comment (Matt75) [reply classes/Product.php:5331]: As it's a protected method, I think we can change results of this method. 🤔  So yes

**Comment by Matt75** [comment]
Initially I do like this to preserve retrocompatibility in case of a module or an override, that's why I use an empty for example to be sure this column exist in case of Product::_getCustomizationFieldsNLabels() is overrided.

Do you prefer to only add a condition a the query ? It's a protected method and only used in duplicateCustomizationFields so I think it's doable

File: classes/Product.php (hunk 1 above)
Comment (Matt75) [reply classes/Product.php:5331]: @Progi1984 Done

**Review by matthieu-rolland — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Matt75 ,

Thanks for the PR, it looks good to me !

**Comment by atomiix** [comment]
Thanks @Matt75!
