### PR TITLE
Fixed `displayPackPrice` not defined to true due to a type comparision

### LINKED ISSUE #21034: Block "instead of" in DisplayPackPrice is missing
#### Describe the bug

The displayPackPack in controllers/front/ProductController.php is not assigned well. Let's see the line code:

$this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < $this->product->getNoPackPrice()) ? true : false);

In that line, $productPrice is float, but $this->product->getNoPackPrice() is formattted price, so in that comparation, it can be false even the noPackPrice is greater than pack price

#### Expected behavior

The block "Instead of" should be displayed allways a pack price is lower than no price pack. 

#### Steps to Reproduce

1. Create a product with a price of 7.99€, tax included
2. Create a pack that includes the previous product, with a pack price of 23€, tax included
3. Go to pack product page. The block "Instead of" is missing

**Screenshots**
pack-ok

pack-error

#### Additional information

* PrestaShop version: 1.7.6.1 (failure still happens)
* PHP version: 7.1

### LINKED ISSUE #21828: Fix bug with condition display packaging price
#### Describe the bug

The "Product::getNoPackPrice" method returns an incorrect value for comparison; a string of the form "$ 10.99" is returned, which leads to an incorrect comparison

#### Steps to Reproduce

Create pack product, go on front page and see

#### Additional information

* PrestaShop version: 1.7.4
* PHP version: 7.2

---

## Steps to reproduce on PS1770 & develop:
1. BO > Catalog > Products > Create pack contains 2 or 3 products
2. set its price less than the really sum of all products prices (ex: P1: 19.12 + P2: 18.90 + P3: 12.90 = 50.92 > Pack_price: 40)
3. FO > Pack page: we only see the price of the pack we don't see the text "Instead of 50.92"

image

4. BO > International > Localization > Currencies > edit the current currency (ex: euro)
5. Click on edit button (see screenshot below)

image

6. A pop up is open, we need to change the displayed position of the currency
7. Choose the option in the green square (see screen shot below)

image

8. Click on Apply, the popup is closed
9. Click on Save
10. FO > Pack page > now we see the pack's price and the text "Instead of 50.92" below

image

## Steps to reproduce on 1.7.6.8 and 1.7.4.1:
1. BO > Catalog > Products > Create pack contains 2 or 3 products
2. set its price less than the really sum of all products prices (ex: P1: 19.12 + P2: 18.90 + P3: 12.90 = 50.92 > Pack_price: 40)
3. FO > Pack page: we only see the price of the pack we don't see the text "Instead of 50.92"
4. Change the language to French, cause in the French language currency change its position
5. The text "Instead of 50.92" will be displayed (of course with the french language)

## ScreenRecord:
PS1.7.4.1: https://drive.google.com/file/d/18Bk-l-4zWjuAb9__Ts-UWHemh6LlP4d8/view
PS1.7.7.0:  https://drive.google.com/file/d/11Vqwi0fIaqkadj5d4Re62KVlWwxCH9T8/view

### PR DESCRIPTION
**Pull request by Prestaworks**
Fix for issue
https://github.com/PrestaShop/PrestaShop/issues/21034

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR will fix the issue with the displayPackPrice is not set to true due to issue with type comparisions.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes #21034 and #21828
| How to test?  | See instructions in ticket for how to test.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21732)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
Hi @Prestaworks I have one question.

So we have 3 prices, right ?
- `$productPrice`
- `$product->getNoPackPrice()` which is the _formatted_ pack price
- `$Pack::noPackPrice($product->id))` which is the not formatted pack price

I am afraid of 1 usecase: if
- `$productPrice` is 23,002
- `$product->getNoPackPrice()` is 23,00
- `$Pack::noPackPrice($product->id))` is 23,003

In this situation, with your PR, I'm thinking we might display "23€ instead of 23€" which is not good 😅  it sounds not logical. Because the 3rd digit is removed after formatting the price for 2 decimals.

This did not happen with previous implementation.

Maybe we should check that `$productPrice` is below the 2 prices (the formatted AND the not formatted) ?

**Comment by Prestaworks** [comment]
@matks you can't use $product->getNoPackPrice() it returns a string like 23,00 € so any compare with the decimal values just don't work (depending on what chars are used for decimal marker I guess) :(

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -339,7 +339,7 @@ public function initContent()
 
             $this->context->smarty->assign('packItems', $presentedPackItems);
             $this->context->smarty->assign('noPackPrice', $this->product->getNoPackPrice());
-            $this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < $this->product->getNoPackPrice()) ? true : false);
+            $this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < Pack::noPackPrice((int) $this->product->id)) ? true : false);
```
Comment (atomiix) [inline controllers/front/ProductController.php]:
```suggestion
            $this->context->smarty->assign('displayPackPrice', ($pack_items && $productPrice < Pack::noPackPrice((int) $this->product->id)));
```

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Roomsmaniia** [comment]
LGTM,

Thanks @Prestaworks

**Comment by PululuK** [comment]
Thanks @Prestaworks
