### PR TITLE
Fix WebserviceOutputBuilder - handle api categories blank schema

### LINKED ISSUE #28543: 'Trying to access array offset on value of type null' calling WS api categories blank schema
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Call a blank schema of Categories in a shop with Categories tree level depth > 1

image

### Expected behavior

Blank schema of a category as response

1. Have a fresh install of Prestashop 1.7.8.4
2. Be on php 7.4
3. Create a Main categories ( under the Home ) ( I called it Pants )
4. Create two subcategories of this one ( I named there Coton / Jean )
5. Go on Advenced Parameters > Webservice 
6. on Configuration, check "Enable PrestaShop's webservice" and save 
7. Clic on " Add new webservice key " 
8. On the key, clic on "Generate" and copy the key 
9. On permission tab, enable "View (GET)", "Modify (PUT)", "Add (POST)", "Delete (DELETE)", "Fast view (HEAD)"
10. Save it 
11. go on "(link of your shop)/api/categories?schema=blank" 
12. Put the key on the login and nothing in password 
13. You should see the same issue  

---
1. Create a categories tree with level depth > 1
2. Attempt to send HTTP request `[GET] /api/categories?schema=blank`
3. Error received: 'Trying to access array offset on value of type null'

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4.29

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by angelo983**
Validation of category association id

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Resolve 'Trying to access array offset on value of type null' in calling api categories blank schema
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28543
| How to test?      | Follow above ticket steps. Call a blank schema of Categories in a shop with Categories tree level depth > 1
| Possible impacts? | Categories API

### CODE REVIEW

**Comment by angelo983** [comment]
Fixes #28543

**Review by matks — DISMISSED** [review]
Dear @angelo983 thank you for the PR!

Code seems OK, just need to wait for confirmation of bug https://github.com/PrestaShop/PrestaShop/issues/28543

**Comment by angelo983** [comment]
Hello @matks, you are welcome!
I pushed another commit covering more cases.

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: classes/webservice/WebserviceOutputBuilder.php [hunk 1]
```diff
@@ -660,12 +660,14 @@ protected function renderAssociations($object, $depth, $associations, $ws_params
...
-                            $value = $object_assoc;
+                        if (empty($object_assoc)) {
+                            continue;
                         }
+                        $value = $object_assoc;
                         if (empty($fields_assoc)) {
-                            $fields_assoc = [['id' => $value['id']]];
+                            if (!empty($value['id'])) {
+                                $fields_assoc = [['id' => $value['id']]];
+                            }
```
Comment (PululuK) [inline classes/webservice/WebserviceOutputBuilder.php]: Can you please use `AND` operator instead a new `IF` statement ? (see the line just bellow)

**Comment by angelo983** [comment]
@PululuK I did what you asked for

**Comment by AureRita** [comment]
Hi @angelo983 

Thank you for your PR but, currently, the issue that you want to correct didn't exist on develop and 178x, so they're already corrected, as you can see : 

on 1.7.8.x : 
image

on old develop ( 3 month ago I think ) :
image

on new develop ( with an other PR ) : 
image

If you take the files from the 1.7.8.4 version, I test it and yes, it correct the issue !

**Comment by angelo983** [comment]
@AureRita you replicated yourself the issue #28543.
Do you want to tell me that in version 1.7.8.6 the problem does not arise?
What number is the other PR you mentioned?

**Comment by AureRita** [comment]
Hi @angelo983 ,

Yes, that's it, the problem does not arise in version 1.7.8.6

I mentioned a PR that I tested near this one, if you want more information it was pr-27755

**Comment by angelo983** [comment]
@AureRita in 1.7.8.6 the bug is still present, in my develop branch not because my patch is present.
error

**Comment by AureRita** [comment]
Hi @angelo983, 

I do a video for you on develop without your pr : 

https://user-images.githubusercontent.com/100699445/170718820-414932b4-07e1-413b-b60d-89d0c774b6cc.mp4

And another on version 1.7.8.6 : 

https://user-images.githubusercontent.com/100699445/170720165-05b9c3eb-bf69-4a15-a5c3-78cb0b1c651e.mp4

Can you do a video or anything else to see this problem on 1.7.8.6, it's maybe a problem with some restriction on your computer ? 

Why do your webservice get blue character ?

**Comment by MatShir** [comment]
Hey @angelo983, 
We are planning a patch release for September, it would be nice to have your fix 🚀  Could you please check last @AureRita message ?

**Comment by atomiix** [comment]
@angelo983 friendly reminder :)

**Comment by angelo983** [comment]
Hello,
I have reproduced the problem also in 1.7.8.6 following what I wrote in #28543 issue.

I have done my part, if someone wants to go deeper could check why and how an empty value can arrive to objectAssoc when renderAssociations function is called.

**Review by matks — COMMENTED** [review]
Hi everyone I'm lost 😅 what's happening with this pull request?

**Comment by kpodemski** [comment]
Hello @AureRita 

You reproduced the issue before, but later you couldn't, could you please double-check if the issue is not there anymore? We have information from @angelo983 that the bug is still there.

**Review by AureRita — APPROVED** [review]
Hi @angelo983 ! 

Sorry for that long long time, after many research I see where is the differents to repeat the issue ( we need to disabled the debug mode ). After checking this, I try your PR and it's seems to works ! 

we can see this without your pr : 

[Untitled_ Oct 31, 2022 2_42 PM.webm](https://user-images.githubusercontent.com/100699445/199021903-1e97b828-b042-495b-b893-ff3dbffc00de.webm)

And with your PR : 

[Untitled_ Oct 31, 2022 2_43 PM.webm](https://user-images.githubusercontent.com/100699445/199022225-9496be4d-c347-487f-83ab-d968e604d209.webm)

Thank you for your Patience and your PR !

**Review by jolelievre — APPROVED** [review]
Thanks @angelo983

**Comment by jolelievre** [comment]
The PR was tested and approved by QA, but it's missing one review approval (previous approvals were removed after handling a suggestion) Just waiting for the second approval to merge this one

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @angelo983 :)

**Comment by matteolavaggi** [comment]
Why this bug is not fixed in PS 1.7.8.8 ?
