### PR TITLE
Fix RouteValidator by checking unknown keywords in schema URL

### LINKED ISSUE #36392: BO - Traffic & SEO > You can add any keyword to a Schema of URLs, when you go to the FO, you will find a 404
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I edit my Schema of URL with non-existing keyword, I will find an 404 page.

https://github.com/PrestaShop/PrestaShop/assets/16019289/a9e0ce9e-8f1c-4e30-ac15-4478f33d8bad

### Expected behavior

I should not be able to Save the form if I add an keyword that does not exist in the given list. 

### Steps to reproduce

1. Go to BO > Shop Parameters > Traffic & SEO
2. Go to block Schema of URLs
3. Edit Route to category to `{id}-{rewrite}{hello}{bonjour}` > Save
4. Go to FO > Open any category page
5. See 404 error The page you are looking for was not found. :x:

### PrestaShop version(s) where the bug happened

8.0.x, 8.1.7, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by cnavarro-prestashop**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x 
| Description?      | Validate routes by checking unknown keywords in schema URL. This fix will solve issue [404 page if you add unknown keyword in schema URL](https://github.com/PrestaShop/PrestaShop/issues/36392)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | Login in BO. Go to Shop parameters > Traffic & SEO> SEO & URLs. Add unknown keyword (eg. foo) in Schema of URLs fields. Save and see error "Keyword "{foo}" doesn't exist for route..."
| UI Tests          | https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/16521605267
| Fixed issue or discussion?     | Fixes #36392
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @cnavarro-prestashop!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by cnavarro-prestashop** [comment]
Capture d’écran 2025-07-08 à 00 17 29

**Comment by cnavarro-prestashop** [comment]
Capture d’écran 2025-07-08 à 00 12 52

File: src/Adapter/Routes/RouteValidator.php [hunk 1]
```diff
@@ -48,20 +49,28 @@ public function isRoutePattern($pattern)
...
      * @param string $routeId
      * @param string $rule Rule to verify
      *
-     * @return array - returns list of missing keywords
+     * @return array - returns list of missing or unknown keywords
      *
      * @throws PrestaShopException
      */
-    public function doesRouteContainsRequiredKeywords($routeId, $rule)
+    public function isRouteValid($routeId, $rule)
```
Comment (Progi1984) [inline src/Adapter/Routes/RouteValidator.php]:
```suggestion
    public function isRouteValid(string $routeId, string $rule): array
```

**Review by Hlavtox — CHANGES_REQUESTED** [review]
You cannot rename a method in patch or minor version.

**Comment by cnavarro-prestashop** [comment]
Hi @Hlavtox, Thanks for your quick review ! Actually I didn't rename method, I've set ``doesRouteContainsRequiredKeywords`` as deprecated and create another method ``isRouteValid`` to avoid breaking changes.

**Comment by Hlavtox** [comment]
@cnavarro-prestashop Aahhh, sorry. Github is displaying it in a weirdd way somehow…

IMG_6931

File: src/Adapter/Routes/RouteValidator.php (hunk 1 above)
Comment (cnavarro-prestashop) [reply src/Adapter/Routes/RouteValidator.php]: https://github.com/PrestaShop/PrestaShop/pull/39168/commits/80bd55930ec408b3dd4357e0fdb751944a82b979

File: src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig [hunk 2]
```diff
@@ -55,6 +55,9 @@
               </li>
               <li>
                 {{ 'All mandatory keywords (*) must be included in the route'|trans({}, 'Admin.Shopparameters.Notification') }}
+              </li>
+                            <li>
```
Comment (Touxten) [inline src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig]: Lot of space

Comment (cnavarro-prestashop) [reply src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig]: https://github.com/PrestaShop/PrestaShop/pull/39168/commits/284fdfa6fd858405e13a7a9a02dbf61a3afc8a6a

**Review by Touxten — APPROVED** [review]

**Review by matks — DISMISSED** [review]

**Review by nicosomb — CHANGES_REQUESTED** [review]
Some changes are useless (new blank lines), right?

File: src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig [hunk 3]
```diff
@@ -56,6 +56,9 @@
               <li>
                 {{ 'All mandatory keywords (*) must be included in the route'|trans({}, 'Admin.Shopparameters.Notification') }}
               </li>
+              <li>
+                {{ 'All keywords must be defined in the route rules'|trans({}, 'Admin.Shopparameters.Notification') }}
```
Comment (Hlavtox) [inline src/PrestaShopBundle/Resources/views/Admin/Configure/ShopParameters/TrafficSeo/Meta/Blocks/url_schema_configuration.html.twig]:
```suggestion
                {{ 'Only available keywords for a given route can be used'|trans({}, 'Admin.Shopparameters.Notification') }}
```

Wdyt

**Comment by Hlavtox** [comment]
@cnavarro-prestashop Some extra blank lines, minor wording suggestion, otherwise ready to go. :-)

**Review by nicosomb — DISMISSED** [review]

**Comment by cnavarro-prestashop** [comment]
Hi @Hlavtox and @nicosomb, I disabled auto-format in my IDE therefor blank lines and indentation have been removed.

**Review by Hlavtox — DISMISSED** [review]
Nice work boss 🚀

**Comment by Hlavtox** [comment]
@cnavarro-prestashop One extra space to remove - https://github.com/PrestaShop/PrestaShop/actions/runs/16491718729/job/46627770478?pr=39168

**Comment by cnavarro-prestashop** [comment]
Yep sorry, PHPCS Fixer ran : https://github.com/PrestaShop/PrestaShop/commit/077e6fb3d94bfe95d6a2f9459b50748645812e75

**Review by Hlavtox — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by ShaiMagal — DISMISSED** [review]
There is a BC break in this PR.

Before, it returned only an array with keywords.

Now, it returns an array 
```
[
  'missing' => [...],
  'unknown' => [...]
]
```

A fix would be to modify the method like this:

```
public function doesRouteContainsRequiredKeywords($routeId, $rule)
{
    $errors = $this->isRouteValid($routeId, $rule);

    return $errors['missing'] ?? [];
}
```

**Comment by cnavarro-prestashop** [comment]
Nice suggestion @ShaiMagal, thanks ! https://github.com/PrestaShop/PrestaShop/commit/19b7b97a9a98aa7d74a65efa7033b1c66a0aa8cc

**Review by nicosomb — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @cnavarro-prestashop,

Thank you for your PR 
I tested it and it's Good for me ^^
I'm waiting for the automated tests to validate the PR

Uploading Enregistrement de l’écran 2025-07-25 à 14.26.40.mov…


Thanks

**Comment by kpodemski** [comment]
thank you @cnavarro-prestashop - good to see you there :D
