### PR TITLE
Construct category tree using JS on product page v2

### LINKED ISSUE #24263: [Experimental product page] Load Categories tree in JS to handle large number of categories
### Describe the bug

On the experimental product page ; the categories tree must be generated in JS to handle large number of categories

#### Additional information

* PrestaShop version: `1.7.8.x`

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Category trees on product page v2 needs to be constructed using JS as it needs to be async, in order to make the product page lighter to load
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24263
| How to test?      | Go on product page and try to select a category, expand and hide, use typehead by searching a category in the search input. The merchant can't unselect the default category. The checkbox is disabled. The default category in the associated category list can't be removed (the suppression cross is hidden). To unselect a default category on the category tree, the merchant has to select another category as main category then unselect the previous default category.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

# How does it looks ?
image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23900)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/product/components/categories/index.js [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+      }
+    });
+
+    this.expanded = !this.expanded;
+  }
+
+  /**
+   * Typehead datas require to have only one array level
+   */
+  initTypeheadDatas(datas) {
```
Comment (zuk3975) [inline admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]: If Im not mistaken and this "typehead" is related to a search, then should be "Type**a**head" everywhere, shoudn't it?

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]: Oh damn, my bad

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]: Fixed it

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/categories.html.twig [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+        <div id="form_step1_categories" class="category-tree-overflow js-category-tree-overflow"></div>
+      </div>
+    </fieldset>
+
+    <div class="categories-tree-loader">
+      <div class="spinner m-auto d-block"></div>
+    </div>
+  </div>
+</div>
```
Comment (NeOMakinG) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Blocks/categories.html.twig]: Don't review this for the moment, it will change (ps_categoryTree will be kicked and translations will be added)

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Some data are always hardcoded

**Comment by NeOMakinG** [comment]
@Progi1984 it's a draft 😆

**Comment by Progi1984** [comment]
@NeOMakinG It's a published PR so it's opened to review.

**Comment by NeOMakinG** [comment]
@Progi1984 of course and I asked for review too

File: admin-dev/themes/new-theme/js/pages/product/components/categories/index.js [hunk 3]
```diff
@@ -0,0 +1,271 @@
...
+    regexpString = regexpString.replace('__REGEXP__', '([0-9]+)');
+    const categoryIdRegexp = new RegExp(regexpString);
+
+    this.categoryTree.querySelectorAll(ProductCategoryMap.categoryTreeElement).forEach((treeElement) => {
+      const checkboxInput = treeElement.querySelector(ProductCategoryMap.checkboxInput);
+      const matches = checkboxInput.name.match(categoryIdRegexp);
+      const categoryId = Number(matches[1]);
+      initialElements[categoryId] = treeElement;
+    });
+    console.log('initialElements', initialElements);
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]:
```suggestion
```

File: admin-dev/themes/new-theme/js/pages/product/components/categories/index.js [hunk 4]
```diff
@@ -0,0 +1,271 @@
...
+        ) {
+          childrenList.classList.toggle('d-none');
+
+          if (childrenList.classList.contains('d-none')) {
+            inputsContainer.parentElement.classList.remove('less');
+            inputsContainer.parentElement.classList.add('more');
+          } else {
+            inputsContainer.parentElement.classList.remove('more');
+            inputsContainer.parentElement.classList.add('less');
+          }
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]:
```suggestion
          inputsContainer.parentElement.classList.toggle('less', !childrenList.classList.contains('d-none'));
          inputsContainer.parentElement.classList.toggle('more', childrenList.classList.contains('d-none'));
```

File: admin-dev/themes/new-theme/js/pages/product/components/categories/index.js [hunk 5]
```diff
@@ -0,0 +1,271 @@
...
+    currentAction.style.display = 'none';
+
+    this.categoriesContainer
+      .querySelectorAll(ProductCategoryMap.childrenList)
+      .forEach((e) => {
+        if (this.expanded && !force) {
+          e.classList.add('d-none');
+        } else {
+          e.classList.remove('d-none');
+        }
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]:
```suggestion
        e.classList.toggle('d-none', this.expanded && !force);
```

File: admin-dev/themes/new-theme/js/pages/product/components/categories/index.js [hunk 6]
```diff
@@ -0,0 +1,271 @@
...
+    this.categoriesContainer
+      .querySelectorAll(ProductCategoryMap.everyItems)
+      .forEach((e) => {
+        if (this.expanded && !force) {
+          e.classList.add('more');
+          e.classList.remove('less');
+        } else {
+          e.classList.add('less');
+          e.classList.remove('more');
+        }
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/product/components/categories/index.js]:
```suggestion
        e.classList.toggle('more', this.expanded && !force);
        e.classList.toggle('less', !(this.expanded && !force));
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/basic.html.twig [hunk 7]
```diff
@@ -42,6 +43,9 @@
     </div>
     <div class="col-md-3 right-column">
       {{ form_row(productForm.shortcuts) }}
+      {{ form_row(productForm.categories) }}
+
+{#      {{ include('@PrestaShop/Admin/Sell/Catalog/Product/Blocks/categories.html.twig') }}#}
```
Comment (Progi1984) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Tabs/basic.html.twig]:
```suggestion
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG categories is not displayed on edit and create a new product in page prodcut v2
https://drive.google.com/file/d/1CKvZNjujkaVurk7SGthi0o0k18p5pWqS/view

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I have some issues:
1. Edit a demo product on the experimental page
2. In the Categories section
3. Click on Expand All
4.  We can't uncheck the default category 
image
5. Also try to remove the default category from the `Associated categories` with the cross 
image
6. The radio button is not changed to the parent category 
https://drive.google.com/file/d/1yRaIyePdkBC_abXNwNaz6sd4sWnfllwk/view?usp=sharing
**Product V1** => https://drive.google.com/file/d/1squjWOv2WSPUoPo_Uvs2Zpt2Zga6KSgm/view?usp=sharing
7. In the `Search categories` section, search a category and choose it 
image
8. The selected category is not displayed in the Associated categories 
image
**Product V1** => https://drive.google.com/file/d/10mnk1XVFF3fr32dRfH_oBDzC4gA-cr00/view?usp=sharing
9. Also Try to search for the `Men` category
10. The searched list has only `Men` 
image
**Product V1**, I have `Men` & `Women`  => 
image
11. With the radio button => select an unchecked category => The category is not displayed in the `associated categories` page
image
**Product V1** => ok
image


When I add a product, the Home page should be selected an associated category + default category
image
**Product V1** => 
image


Thank you!

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@jolelievre PHPUnit is broken.

**Review by Progi1984 — DISMISSED** [review]

**Comment by jolelievre** [comment]
This one is waiting for @MatShir feedback regarding how we deal with the default category Not ready for QA yet

**Comment by Progi1984** [comment]
@jolelievre Added "Waiting for PM"

**Comment by MatShir** [comment]
**The new behavior:**
The merchant can't unselect the default category. The checkbox is disabled.
The default category in the associated category list can't be removed (the suppression cross is hidden). 

To unselect a default category on the category tree, the merchant has to select another category as main category then unselect the previous default category.

_New specs incoming_

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

1. Adding a new product
=> ok :heavy_check_mark: the Home is selected as a default category
2. Selecting another category => ok 
3. Expand All => ok / Expand one by one => ok
4. Collapse All => ok / Collapse one by one => ok
5. The merchant can't unselect the default category => ok
6. The checkbox is disabled => ok
7. The default category in the associated category list can't be removed (the suppression cross is hidden) => ok
8. To unselect a default category on the category tree, the merchant has to select another category as the main category then unselect the previous default category. => ok
9. In the Search categories section, search a category and choose it: the selected category is displayed in the Associated categories => ok
10. Search a category and select it => ok
11. Unselect category, it will be removed from the Associated categories => ok
12. Click on the Cross => category will be unselected

https://drive.google.com/file/d/1hUPZE68T71ZFx8hU-J3lort0cXBX2KTf/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Great news @NeOMakinG & @khouloudbelguith
