### PR TITLE
Origin/m/international/locations/countries edit rebased

### LINKED ISSUE #10604: Migrate "International > Locations > Countries" page
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate listing 
- [ ] Form todo
Capture d’écran 2023-07-06 à 15 52 23

- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] #19372 - Checkboxes for multistore
- [ ] #19324 - Specific settings dropdown for multistore

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### PR DESCRIPTION
**Pull request by margud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Edit action of Countries form 
| Type?             | refacto
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#10604](https://github.com/PrestaShop/PrestaShop/issues/10604)
| How to test?      |  You can now edit country with new symfony controller.

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 1]
```diff
@@ -106,18 +108,44 @@ public function createAction(Request $request): Response
...
+            $countryFormHandler = $this->get(
+                'prestashop.core.form.identifiable_object.handler.country_form_handler'
+            );
+
+            $countryForm = $countryFormBuilder->getFormFor($countryId);
+            $countryForm->handleRequest($request);
+            $result = $countryFormHandler->handleFor($countryId, $countryForm);
+
+            if ($result->isSubmitted() && $result->isValid()) {
+                $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]:
```suggestion
                $this->addFlash('success', $this->trans('Successful update', 'Admin.Notifications.Success'));
```

File: src/Adapter/Country/AbstractCountryHandler.php [hunk 2]
```diff
@@ -49,4 +51,26 @@ protected function validateCountryFields(Country $country): void
...
+     * @return Country
+     *
+     * @throws CountryNotFoundException
+     */
+    protected function getCountry(CountryId $countryId): Country
+    {
+        $countryIdValue = $countryId->getValue();
+
+        try {
+            $country = new Country($countryIdValue);
```
Comment (jolelievre) [inline src/Adapter/Country/AbstractCountryHandler.php]: Fetching an ObjectModel by specifying an ID doesn't ensure that it will exist or has been found
You can see in our `AbstractObjectModelRepository` that we check that the `object->id` is indeed the right value, this ensure that a row has been found in the database:

https://github.com/PrestaShop/PrestaShop/blob/c771bd3630fa4fe7d54e09d4c46be90b1dcea0bf/src/Core/Repository/AbstractObjectModelRepository.php#L281-L284

Comment (jolelievre) [reply src/Adapter/Country/AbstractCountryHandler.php]: I suggest two possibilities:
- modify your method to mimic this behaviour
- you can create, as I suggested in another PR, a dedicated `CountryRepository` service that extends `AbstractObjectModelRepository` it will give you better tools to build such methods

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+     * {@inheritdoc}
+     *
+     * @throws CannotAddCountryException
+     * @throws CountryConstraintException
+     * @throws CountryException
+     */
+    public function handle(EditCountryCommand $command): void
+    {
+        try {
+            $country = new Country($command->getCountryId()->getValue());
```
Comment (jolelievre) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]: Here you should use your method from the abstract class `getCountry` which has better handling of exceptions and error cases. Or if you decide to create the repository you'll be able to inject it into this handler and use the `CategoryRepositiry::get` method

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+            }
+
+            if (null !== $command->getZoneId()) {
+                $country->id_zone = $command->getZoneId();
+            }
+
+            $this->validateCountryFields($country);
+
+            if (false === $country->update()) {
+                throw new CannotAddCountryException('Failed to update country');
```
Comment (jolelievre) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]:
```suggestion
                throw new CannotUpdateCountryException('Failed to update country');
```

Comment (jolelievre) [reply src/Adapter/Country/CommandHandler/EditCountryHandler.php]: Same suggestion here, all this exception handling that you do could be taken care of in the repository, When I first suggested it you said you could do it in a future refacto, maybe it's a good occasion to implement it It will save you time and clean your code

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+{
+    /**
+     * {@inheritdoc}
+     */
+    public function handle(GetCountryForEditing $command): EditableCountry
+    {
+        $countryId = $command->getCountryId();
+        $country = $this->getCountry($countryId);
+
+        $format = AddressFormat::getAddressCountryFormat($countryId->getValue());
```
Comment (jolelievre) [inline src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]: The focus of this PR is not the format, so for now this implementation is enough but it will need to be refacto in the next PR about AddressFormat, can you please add a `@todo` comment to explain that this should be replaced by:
- a dedicated service to fetch the country address format, it should implement a dedicated interface
- for now the string format is enough, but maybe we should introduce some kind of DTO or maybe even a smarter Domain object that stores this address format

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+        return new EditableCountry(
+            $command->getCountryId(),
+            $country->name,
+            (string) $country->iso_code,
+            (int) $country->call_prefix,
+            (int) $country->id_currency,
+            (int) $country->id_zone,
+            (bool) $country->need_zip_code,
+            (string) $country->zip_code_format,
+            (string) $format,
```
Comment (jolelievre) [inline src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]:
```suggestion
            (string) $country->format,
```

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php (hunk 5 above)
Comment (jolelievre) [reply src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]: But I'm not sure we should use this `AddressFormat::getAddressCountryFormat` for two reasons:
- it will always perform an additional request to get the coutrny's format even though you can already have via `$country->format`
- it includes an automatic fallback and gets the default country's format, this fallback is interesting in the FO context to make sure you always have an address format available but no in the BO context where each Country must be edited independently

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]: You can simply use the actual value saved in DB four this country.

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php (hunk 5 above)
Comment (jolelievre) [reply src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]: This raises a question about the constraint related to this format field (although it won't be done in this PR) but if we expect each country to have a proper format it means we'll probably have to make this field required and thoroughly validated to be a correct format

File: src/Core/Domain/Country/Command/EditCountryCommand.php [hunk 7]
```diff
@@ -0,0 +1,303 @@
...
+    {
+        return $this->countryId;
+    }
+
+    public function setCountryId(int $countryId): EditCountryCommand
+    {
+        $this->countryId = new CountryId($countryId);
+
+        return $this;
+    }
```
Comment (jolelievre) [inline src/Core/Domain/Country/Command/EditCountryCommand.php]: I don't think the countryId should have a setter, this one should remain immutable and only provided via the constructor

File: src/Core/Domain/Country/Command/EditCountryCommand.php [hunk 8]
```diff
@@ -0,0 +1,303 @@
...
+{
+    /**
+     * @var CountryId
+     */
+    private $countryId;
+
+    /**
+     * @var string[]
+     */
+    protected $localizedNames;
```
Comment (jolelievre) [inline src/Core/Domain/Country/Command/EditCountryCommand.php]:
```suggestion
    private $localizedNames;
```

Comment (jolelievre) [reply src/Core/Domain/Country/Command/EditCountryCommand.php]: Since the command class are not meant to be extended you don't need to make their properties protected, you can use private everywhere here

File: src/Core/Domain/Country/CommandHandler/AddCountryHandlerInterface.php [hunk 9]
```diff
@@ -34,10 +34,5 @@
  */
 interface AddCountryHandlerInterface
 {
-    /**
```
Comment (jolelievre) [inline src/Core/Domain/Country/CommandHandler/AddCountryHandlerInterface.php:37]: No reason to remove this PHPDoc, but no reason to keep it either since everything is strong typed 😅
So whatever 🤷‍♂️

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 10]
```diff
@@ -106,18 +108,44 @@ public function createAction(Request $request): Response
...
-            )
-        );
+        try {
+            /** @var EditableCountry $editableCountry */
+            $editableCountry = $this->getQueryBus()->handle(new GetCountryForEditing($countryId));
+        } catch (CountryException $e) {
+            $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
+
+            return $this->redirectToRoute('admin_countries_index');
+        }
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]: You don't need to handle this exception separately, because the `country_form_builder` already performs this query internally So you are duplicating this call, instead you should move this catch block at the end of the following (L137)

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php [hunk 11]
```diff
@@ -97,36 +103,120 @@ public function createCountry(string $countryReference, TableNode $table): void
...
      * @param string $countryReference
-     * @param string $name
+     * @param TableNode $table
      */
-    public function assertCountryName(string $countryReference, string $name): void
+    public function editCountry(string $countryReference, TableNode $table): void
     {
+        $data = $this->localizeByRows($table);
+
+        /** @var Country $country */
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php]: You don't need to fetch the `Country` legacy object anymore, you can now only rely on CQRS commands, and you can already have the country ID via the shared storage.

So you should do something like:

```php
$command = new EditCountryCommand(SharedStorage::getStorage()->get($countryReference));
```

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php [hunk 12]
```diff
@@ -97,36 +103,120 @@ public function createCountry(string $countryReference, TableNode $table): void
...
+            $command->setNeedIdNumber(PrimitiveUtils::castStringBooleanIntoBoolean($data['need_identification_number']));
+        }
+
+        if (isset($data['display_tax_label'])) {
+            $command->setDisplayTaxLabel(PrimitiveUtils::castStringBooleanIntoBoolean($data['display_tax_label']));
+        }
+
+        $this->getCommandBus()->handle($command);
+
+        SharedStorage::getStorage()->set($countryReference, $countryId);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php]:
```suggestion
```

You don't need to update the storage since the ID is not gonna be changed during its edition

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php [hunk 13]
```diff
@@ -97,36 +103,120 @@ public function createCountry(string $countryReference, TableNode $table): void
...
     }
 
     /**
-     * @Given /^country "(.*)" is (enabled|disabled)?$/
-     * @Then /^country "(.*)" should be (enabled|disabled)?$/
-     *
-     * @param string $countryReference
-     * @param string $expectedStatus
+     * @When /^I query country "(.+)" I should get a Country with properties:$/
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php]:
```suggestion
     * @Then /^the country "(.+)" should have the following properties:$/
```

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php [hunk 14]
```diff
@@ -97,36 +103,120 @@ public function createCountry(string $countryReference, TableNode $table): void
...
-        $isEnabled = 'enabled' === $expectedStatus;
-        $actualStatus = (bool) $country->active;
+        $queryBus = $this->getQueryBus();
+        /** @var EditableCountry $result */
+        $result = $queryBus->handle(new GetCountryForEditing($countryId));
 
-        if ($actualStatus !== $isEnabled) {
-            throw new RuntimeException(sprintf('Country "%s" is %s, but it was expected to be %s', $countryReference, $actualStatus ? 'enabled' : 'disabled', $expectedStatus));
+        $serializer = CommonFeatureContext::getContainer()->get('serializer');
+        $realData = $serializer->normalize($result);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php]: I prefer you not to rely on a serializer because it means you don't test the QueryResult object directly (and its getters). So you hide a part of the test behind this serializer which could result in unexpected hidden faulty behavior

So please compare the values based on the object getter instead

File: tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php [hunk 15]
```diff
@@ -72,6 +87,14 @@ public function testCreate(int $initialEntityCount): int
         $this->assertCount($initialEntityCount + 1, $newCountry);
         $this->assertCollectionContainsEntity($newCountry, $countryId);
 
+        $country = new Country($countryId);
+        $this->assertEquals($isoCode, $country->iso_code);
+        $this->assertEquals($zipCodeFormat, $country->zip_code_format);
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php]: It's a good idea to test that the data has correctly been set, but since this test is about testing the controllers it would be even more efficient to test that the data is correct in the form after the creation.

To do that you have some helper functions that allows fetching the data from the edition form like here:
https://github.com/PrestaShop/PrestaShop/blob/ed1e79d6201e98f6f810ee10da850db0589c7a8a/tests/Integration/PrestaShopBundle/Controller/Sell/Catalog/ProductControllerTest.php#L113-L120

It's going a step further in testing the whole workflow of the controller

File: tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php [hunk 16]
```diff
@@ -80,23 +103,72 @@ public function testCreate(int $initialEntityCount): int
...
+            'country[address_format]' => $addressFormat,
+            'country[is_enabled]' => 1,
+            'country[contains_states]' => 0,
+            'country[need_identification_number]' => 0,
+            'country[display_tax_label]' => 1,
+        ];
+        $this->editEntityFromPage(['countryId' => $countryId], $formData);
+
+        // need to clear cache because prestashop caches address format and without clear it sees the one before update
+        Cache::clear();
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php]: Then it probably means that your command hanlder should clear this cache after edition, you can target a specific cache key with a wildcard to only clear the appropriate cache

You should do it now because anyway it will probably cause you some problem later when you'll test the address format in behat

File: tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php [hunk 17]
```diff
@@ -80,23 +103,72 @@ public function testCreate(int $initialEntityCount): int
...
+
+        // Then check that it was correctly updated
+        $this->assertFormValuesFromPage(
+            ['countryId' => $countryId],
+            $formData
+        );
+
+        $country = new Country($countryId);
+        $this->assertEquals($isoCode, $country->iso_code);
+        $this->assertEquals($zipCodeFormat, $country->zip_code_format);
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php]: This one is overkill since it seems you already checked the form content via `assertFormValuesFromPage` before on L140

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

A few feedback to fix but it's looking good

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php (hunk 5 above)
Comment (margud) [reply src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]: added todo, but $country doesn't have format like $country->format, it only had zip_code_format but not address format so not sure about this part. 
So for now added todo and link to this comment, so when i start working on format i will be able to tell more.

File: src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php (hunk 6 above)
Comment (margud) [reply src/Adapter/Country/QueryHandler/GetCountryForEditingHandler.php]: as before, there is no format in country object

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 18]
```diff
@@ -144,6 +175,25 @@ protected function getCountryToolbarButtons(): array
     protected function getErrorMessages(Exception $e): array
     {
         //todo add error messages
-        return [];
+        return [
+            CountryNotFoundException::class => $this->trans(
+                'This country does not exists',
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]:
```suggestion
                'This country does not exist',
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 19]
```diff
@@ -144,6 +175,25 @@ protected function getCountryToolbarButtons(): array
...
+                'Admin.International.Feature'
+            ),
+            CannotEditCountryException::class => [
+                CannotEditCountryException::FAILED_TO_UPDATE_COUNTRY => $this->trans(
+                    'Failed to update country',
+                    'Admin.International.Feature'
+                ),
+                CannotEditCountryException::UNKNOWN_EXCEPTION => $this->trans(
+                    'Failed to update country. Got unexpected error',
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]:
```suggestion
                    'Failed to update country. An unexpected error occurred.',
```

**Review by l-delin — COMMENTED** [review]
The wording needs some editing done :)

File: src/Adapter/Country/AbstractCountryHandler.php [hunk 20]
```diff
@@ -49,4 +64,101 @@ protected function validateCountryFields(Country $country): void
...
+    /**
+     * Get legacy country
+     *
+     * @param CountryId $countryId
+     *
+     * @return Country
+     *
+     * @throws CountryNotFoundException
+     */
+    protected function getCountry(CountryId $countryId): Country
```
Comment (zuk3975) [inline src/Adapter/Country/AbstractCountryHandler.php]: Is this method necessary? the CountryRepository->get() already does the same, no? :thinking:

File: src/Adapter/Country/AbstractCountryHandler.php [hunk 21]
```diff
@@ -49,4 +64,101 @@ protected function validateCountryFields(Country $country): void
...
+
+    /**
+     * @param EditCountryCommand $command
+     *
+     * @throws CannotEditCountryException
+     * @throws CountryConstraintException
+     * @throws CountryNotFoundException
+     * @throws PrestaShopException
+     */
+    protected function updateCountry(EditCountryCommand $command): void
```
Comment (zuk3975) [inline src/Adapter/Country/AbstractCountryHandler.php]: move this method to EditCountryHandler.
There is no point having it here, especially when it depends on EditCountryCommand (it cannot be used anywhere except the EditCountryHandler)

File: src/Adapter/Country/AbstractCountryHandler.php [hunk 22]
```diff
@@ -29,14 +29,29 @@
...
+use PrestaShop\PrestaShop\Core\Domain\Country\Exception\CannotEditCountryException;
 use PrestaShop\PrestaShop\Core\Domain\Country\Exception\CountryConstraintException;
+use PrestaShop\PrestaShop\Core\Domain\Country\Exception\CountryNotFoundException;
+use PrestaShop\PrestaShop\Core\Domain\Country\ValueObject\CountryId;
 use PrestaShopException;
 
 /**
  * Abstract country handler
  */
 class AbstractCountryHandler
```
Comment (zuk3975) [inline src/Adapter/Country/AbstractCountryHandler.php]: I know its not you that created this, but have in mind that having abstract handlers for cases like this is not the best practice. 
It only has the validation, so instead there should be some dedicated validator that could be used anywhere (not only in the handlers).

Anyway, as there is already the validateFields method, I think you can reuse it as it is now :man_shrugging:

File: src/Core/Domain/Country/QueryResult/EditableCountry.php [hunk 23]
```diff
@@ -0,0 +1,266 @@
...
+
+namespace PrestaShop\PrestaShop\Core\Domain\Country\QueryResult;
+
+use PrestaShop\PrestaShop\Core\Domain\Country\ValueObject\CountryId;
+use PrestaShop\PrestaShop\Core\Domain\Country\ValueObject\CountryZipCodeFormat;
+
+/**
+ * Stores editable country data
+ */
+class EditableCountry
```
Comment (zuk3975) [inline src/Core/Domain/Country/QueryResult/EditableCountry.php]:
```suggestion
class CountryForEditing
```
just a suggestion to follow latest practices. Altough I cannot require this change because there are many uses of both "..ForEditing.." and "..Editable.." and the preferred way is not documented anywhere :smile:

File: src/Core/Domain/Country/QueryResult/EditableCountry.php [hunk 24]
```diff
@@ -0,0 +1,266 @@
...
+{
+    /**
+     * @var CountryId
+     */
+    private $countryId;
+
+    /**
+     * @var string[]
+     */
+    private $localisedNames;
```
Comment (zuk3975) [inline src/Core/Domain/Country/QueryResult/EditableCountry.php]:
```suggestion
    private $localizedNames;
```

File: src/Core/Domain/Country/QueryResult/EditableCountry.php [hunk 25]
```diff
@@ -0,0 +1,266 @@
...
+     */
+    public function getCountryId(): CountryId
+    {
+        return $this->countryId;
+    }
+
+    /**
+     * @return string[]
+     */
+    public function getLocalisedNames(): array
```
Comment (zuk3975) [inline src/Core/Domain/Country/QueryResult/EditableCountry.php]:
```suggestion
    public function getLocalizedNames(): array
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 26]
```diff
@@ -106,18 +111,44 @@ public function createAction(Request $request): Response
 
     public function editAction(int $countryId, Request $request): Response
```
Comment (zuk3975) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php:125]: missing security annotation :thinking:

File: src/PrestaShopBundle/Resources/config/services/adapter/country.yml [hunk 27]
```diff
@@ -27,5 +27,23 @@ services:
...
+
+  prestashop.adapter.country.command_handler.edit_country_handler:
+    public: true
+    class: 'PrestaShop\PrestaShop\Adapter\Country\CommandHandler\EditCountryHandler'
+    arguments:
+      - '@prestashop.adapter.country.repository.country_repository'
+    tags:
+      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Country\Command\EditCountryCommand' }
+
+  prestashop.adapter.country.query_handler.get_editable_country:
```
Comment (zuk3975) [inline src/PrestaShopBundle/Resources/config/services/adapter/country.yml]: follow classs name
```suggestion
  prestashop.adapter.country.query_handler.get_country_for_editing_handler:
```

File: tests/Integration/Behaviour/Features/Scenario/Country/country_management.feature [hunk 28]
```diff
@@ -19,5 +21,50 @@ Feature: country management
       | need_identification_number | false           |
       | display_tax_label          | true            |
       | shop_association           | 1               |
-    Then country "test" name should be "testName"
-    And country "test" should be enabled
+    Then the country "test" should have the following properties:
+      | localisedNames[en-US] | testName |
+      | localisedNames[fr-FR] | testName |
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Scenario/Country/country_management.feature]:
```suggestion
      | localizedNames[fr-FR] | testName |
```
check other places too

File: tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php [hunk 29]
```diff
@@ -80,23 +100,65 @@ public function testCreate(int $initialEntityCount): int
      *
      * @param int $countryId
      */
-    public function testEdit(int $countryId): void
+    public function testEdit(int $countryId): int
     {
-        $this->markTestSkipped('Not implemented');
-        // TODO: Implement when edit action is created
+        // this is the default format that is taken when opening country form, if you try to add spaces the test will fail.
```
Comment (zuk3975) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Improve/International/CountryControllerTest.php:105]: good comment :+1: , wanted to ask wtf is this already :smile:

File: src/Core/Domain/Country/QueryResult/EditableCountry.php [hunk 30]
```diff
@@ -0,0 +1,266 @@
...
+    private $displayTaxLabel;
+
+    /**
+     * @var int[]
+     */
+    private $shopAssociation;
+
+    /**
+     * @param CountryId $countryId
+     * @param string[] $localisedNames
```
Comment (l-delin) [inline src/Core/Domain/Country/QueryResult/EditableCountry.php]:
```suggestion
     * @param string[] $localizedNames
```

File: src/Core/Domain/Country/QueryResult/EditableCountry.php [hunk 31]
```diff
@@ -0,0 +1,266 @@
...
+     * @param string $addressFormat
+     * @param bool $enabled
+     * @param bool $containsStates
+     * @param bool $needIdNumber
+     * @param bool $displayTaxLabel
+     * @param int[] $shopAssociation
+     */
+    public function __construct(
+        CountryId $countryId,
+        array $localisedNames,
```
Comment (l-delin) [inline src/Core/Domain/Country/QueryResult/EditableCountry.php]:
```suggestion
        array $localizedNames,
```

File: src/Core/Domain/Country/QueryResult/EditableCountry.php [hunk 32]
```diff
@@ -0,0 +1,266 @@
...
+        ?string $zipCodeFormat,
+        string $addressFormat,
+        bool $enabled,
+        bool $containsStates,
+        bool $needIdNumber,
+        bool $displayTaxLabel,
+        array $shopAssociation
+    ) {
+        $this->countryId = $countryId;
+        $this->localisedNames = $localisedNames;
```
Comment (l-delin) [inline src/Core/Domain/Country/QueryResult/EditableCountry.php]:
```suggestion
        $this->localizedNames = $localizedNames;
```

**Review by l-delin — COMMENTED** [review]
Following @zuk3975 's review

File: src/Adapter/Country/AbstractCountryHandler.php (hunk 22 above)
Comment (margud) [reply src/Adapter/Country/AbstractCountryHandler.php]: hmm i added this but i m trying to keep same logic as in other cases. I see that most of the other cases has validate function like this in abstract. I guess i can move it to validator but having different logic then in other cases is confusing no?

Comment (zuk3975) [reply src/Adapter/Country/AbstractCountryHandler.php]: Yeah, it was previous practice that we used, but it wasn't the best and we have a new one starting from product page.
So if it was you that introduced this abstract handler and its not yet in production, then I think you can inspire from product and combination validators and do the same for country :thinking: (especially considering the fact you are out of tasks for now :smile:)

**Comment by zuk3975** [comment]
should rebase instead of merge to avoid having the develop changes as your own and so the PR validator won't block your PR for merge commits

File: src/PrestaShopBundle/Resources/config/routing/admin/improve/international/country.yml [hunk 33]
```diff
@@ -30,7 +30,7 @@ admin_countries_edit:
   methods: [ GET, POST ]
   defaults:
     _controller: 'PrestaShopBundle\Controller\Admin\Improve\International\CountryController::editAction'
-    _legacy_controller: AdminCountry
+    _legacy_controller: AdminCountries
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/config/routing/admin/improve/international/country.yml:36]: Nice catch, the legacy link should also be fixed `_legacy_link: AdminCountries:updateCountry`

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

Seems all good to me, except the legacy_link that also needs fixing

File: src/PrestaShopBundle/Resources/config/routing/admin/improve/international/country.yml (hunk 33 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Resources/config/routing/admin/improve/international/country.yml:36]: done https://github.com/PrestaShop/PrestaShop/pull/29591/commits/7f4169411a305a4073f11720eee80287acb2fc65 . @margud I've pushed to your branch, so don't forget to pull it before you work on it again (if it won't get merged until you work)

**Review by zuk3975 — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
Hi @margud 

this PR needs to be rebased because it has conflicts. Then it should be mergeable.

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 34]
```diff
@@ -0,0 +1,137 @@
...
+        $this->countryRepository = $countryRepository;
+    }
+
+    /**
+     * {@inheritdoc}
+     *
+     * @throws CannotEditCountryException
+     * @throws CountryConstraintException
+     * @throws CountryNotFoundException
+     * @throws PrestaShopException
```
Comment (FabienPapet) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]: Wrong throw here I think

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 35]
```diff
@@ -0,0 +1,137 @@
...
+        $this->updateCountry($command);
+    }
+
+    /**
+     * @param EditCountryCommand $command
+     *
+     * @throws CannotEditCountryException
+     * @throws CountryConstraintException
+     * @throws CountryNotFoundException
+     * @throws PrestaShopException
```
Comment (FabienPapet) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]: Wrong throw here I think

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 36]
```diff
@@ -0,0 +1,137 @@
...
+namespace PrestaShop\PrestaShop\Adapter\Country\CommandHandler;
+
+use PrestaShop\PrestaShop\Adapter\Country\Repository\CountryRepository;
+use PrestaShop\PrestaShop\Core\Domain\Country\Command\EditCountryCommand;
+use PrestaShop\PrestaShop\Core\Domain\Country\CommandHandler\EditCountryHandlerInterface;
+use PrestaShop\PrestaShop\Core\Domain\Country\Exception\CannotEditCountryException;
+use PrestaShop\PrestaShop\Core\Domain\Country\Exception\CountryConstraintException;
+use PrestaShop\PrestaShop\Core\Domain\Country\Exception\CountryNotFoundException;
+use PrestaShop\PrestaShop\Core\Exception\CoreException;
+use PrestaShopException;
```
Comment (FabienPapet) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]:
```suggestion
```

File: src/Adapter/Country/CommandHandler/AddCountryHandler.php [hunk 37]
```diff
@@ -77,12 +87,8 @@ public function handle(AddCountryCommand $command): CountryId
...
             }
 
-            $this->validateCountryFields($country);
-
-            if (false === $country->add()) {
-                throw new CannotAddCountryException('Failed to add country');
-            }
-        } catch (PrestaShopException $e) {
+            $this->countryRepository->add($country);
+        } catch (CoreException $e) {
```
Comment (zuk3975) [inline src/Adapter/Country/CommandHandler/AddCountryHandler.php]: I don't think you need to catch this. If something goes wrong related to country, it will throw CannotAddCountry exception already. If it throws core exception then its something fatal, not related to country anymore (but rather smth with db connection etc...)

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 38]
```diff
@@ -0,0 +1,128 @@
...
+    {
+        $this->countryRepository = $countryRepository;
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function handle(EditCountryCommand $command): void
+    {
+        $this->updateCountry($command);
```
Comment (zuk3975) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]: redundant private method. You don't do anything else, so why not just leaving whole code here in handle() method?

File: src/Adapter/Country/CommandHandler/EditCountryHandler.php [hunk 39]
```diff
@@ -0,0 +1,128 @@
...
+        if (null !== $command->getZoneId()) {
+            $country->id_zone = $command->getZoneId();
+        }
+
+        try {
+            $this->countryRepository->update($country);
+        } catch (CoreException $e) {
+            throw new CannotEditCountryException(
+                'An unexpected error occurred when updating country',
+                CannotEditCountryException::UNKNOWN_EXCEPTION,
```
Comment (zuk3975) [inline src/Adapter/Country/CommandHandler/EditCountryHandler.php]: again, I don't think you need to catch core exception here, also then you wouldn't need to have that strange UNKNOWN_EXCPETION code

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 40]
```diff
@@ -144,6 +182,25 @@ protected function getCountryToolbarButtons(): array
     protected function getErrorMessages(Exception $e): array
     {
         //todo add error messages
```
Comment (zuk3975) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]: todo can be removed?

File: src/Core/Domain/Country/CommandHandler/AddCountryHandlerInterface.php (hunk 9 above)
Comment (FabienPapet) [reply src/Core/Domain/Country/CommandHandler/AddCountryHandlerInterface.php:37]: thats less code to download, good for 🌍 😂

**Review by FabienPapet — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @margud ,

I have tested your PR and we can edit country with new symfony controller.
Automated tests are OK.

QA :heavy_check_mark: 

Thank you!

**Comment by nicosomb** [comment]
Thank you @margud and @MhiriFaten !
