### PR TITLE
Avoid displaying the addon modal twice, change form names/IDs to avoid collision

### LINKED ISSUE #10469: Back-Office several controller "[DOM] Found 2 elements with non-unique id" error on Devtool console
**Describe the bug**
By navigating on each page of the Back-Office with your DevTool panel open (F12), you can notice that many controllers contain non-unique id, and it raised as an error by the console.

**To Reproduce**
1. Just open devtool panel (F12)
2. go to 'dashboard'
3. You can see errors like "[DOM] Found 2 elements with non-unique id #addons_login_button"
4. Same casefor each pages listed below

Pages concerned:

- dashboard
- invoices
- credit slips
- delivery slips
- products
- stats
- module catalog
- module manager
- theme catalog
- positions
- preferences
- payment method
- preferences
- localization
- translations
- general
- order settings
- product settings
- customer settings
- information
- performance
- administration
- E-mail
- import
- database
- logs

**Screenshots**
image

**Additionnal information**
PrestaShop version: 1.7.5.0 Develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | The javascript console displays error due to form elements having equal ids, this happens for three reasons. First addon modal is displayed twice in Symfony pages Second on pages with several forms a _token input is added for each form with the same form__token id Thus in the FormHandler class we allow to change the form_name so you can (manually) change the form name in its config Third in legacy form template the smarty countdown of forms did not work thus two forms with the same ids could occur
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10469
| How to test?  | Go to a migrated page, you shouldn't have errors about id duplication any more

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10684)

### CODE REVIEW

File: classes/controller/AdminController.php [hunk 1]
```diff
@@ -1826,11 +1826,19 @@ public function display()
             $this->context->smarty->assign(
                 array(
                     'page_header_toolbar' => $this->context->smarty->fetch($page_header_toolbar),
-                    'modal_module_list' => $this->context->smarty->fetch($modal_module_list),
                 )
             );
+            if (!empty($modal_module_list)) {
```
Comment (PierreRambaud) [inline classes/controller/AdminController.php:1831]: With the ternary condition, $modal_module_list is never empty

Comment (jolelievre) [reply classes/controller/AdminController.php:1831]: yes an empty string returns true, that's the point of the test

Comment (PierreRambaud) [reply classes/controller/AdminController.php:1831]: Oh my bad, miss reading the diff and thinking the ternary was:
```php
file_exists($module_list_dir . 'modal.tpl') ? $module_list_dir . 'modal.tpl' : 'modal.tpl';
```

**Review by PierreRambaud — DISMISSED** [review]

File: classes/controller/AdminController.php (hunk 1 above)
Comment (jolelievre) [reply classes/controller/AdminController.php:1831]: yes that was the previous ternary, but with the new template it no longer has the wanted behavior and instead of adding a modal for available modules (which does not exist in the new theme) it resulted in including the addon login modal in two different locations

**Comment by marionf** [comment]
@jolelievre 

I still have the error with your PR

capture d ecran_324

File: admin-dev/themes/default/template/helpers/form/form.tpl [hunk 2]
```diff
@@ -34,7 +34,7 @@
 {if isset($identifier_bk) && $identifier_bk == $identifier}{capture name='identifier_count'}{counter name='identifier_count'}{/capture}{/if}
 {assign var='identifier_bk' value=$identifier scope='parent'}
 {if isset($table_bk) && $table_bk == $table}{capture name='table_count'}{counter name='table_count'}{/capture}{/if}
-{assign var='table_bk' value=$table scope='parent'}
+{assign var='table_bk' value=$table scope='root'}
```
Comment (Quetzacoalt91) [inline admin-dev/themes/default/template/helpers/form/form.tpl:37]: Reducing the visibility of this variable may break some compatibility.

Comment (jolelievre) [reply admin-dev/themes/default/template/helpers/form/form.tpl:37]: well it actually enhance it since it is visible by root and not only parent
without this the couting can't work because the two forms don't have the same immediate parent

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
One CS fixer to run and we should be good to go for QA review.

**Comment by jolelievre** [comment]
@Quetzacoalt91 ok rebase and cs fixer done, just waiting for the travis build, then if you can approve it again please?

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @jolelievre
