### PR TITLE
Product multishop list and shared group stock

### LINKED ISSUE #26738: Product stock fails when stock is shared in the group on product page v2
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On product page v2
- in a multishop scenario
- where you have a Shop group that shares its stock amongst the group (let's call it "Sharing group")
- the product page fails to load when trying to access it with a shop belonging to "Sharing Group"

Capture d’écran 2021-11-24 à 19 00 39

### Analysis

The query condition to get the StockAvailable are automatically filled with context values for now
The product has no StockAvailable associated for its shop group so no StockAvailable ID can be found and an exception is thrown

### Expected behavior

The problem comes from missing data for group stock, there should be a StockAvailable bound by its groupId

There are two approaches for this bug:

### Correct filling of data

During the shop creation when products are copied the stock available is not copied when the group is the one responsible for stock. See this line:

https://github.com/PrestaShop/PrestaShop/blob/ea657db565709475c488f1a9859f71802c86fd22/classes/shop/Shop.php#L1214-L1219

That's where the missing data comes from. First solution is to handle the creation of this missing data on product creation or when they are copied to another shop via the `CopyProductToShop` command.

This would ensure us the consistency of our data, however we can't be sure that upgrading shop will have this consistency so the bug would remain.

### Be more resilient about StockAvailable

The problem had already risen about this missing StockAvailable even in single shop context, so an alternative solution would be to be more resilient. When the StockAvailable is not detected (regardless of the context) a StockAvailable should be created. Naturally, its quantity would be 0. We will have to handle two cases though:

- the selected shop handles its own stock -> create a StockAvailable associated by shopId
- the selected shop belongs to a group that handles its shared stock -> create a StockAvailable associated by shopGroupId

### Suggested solution

The solution I suggest is a mix:
- the getter should be more resilient to missing data, this can be done by two ways:
  - ignore the missing StockAvailable and use 0 as a fallback quantity
  - detect the missing StockAvailable and create the appropriate one
- the CopyProductToShop command should handle the creation appropriately
- we can't fix all the legacy code especially not the shop creation right now but we can improve the new product code to be more resilient and self-fixing so that it fixes current bugs and avoid inconsistencies from an upgraded shop

### Steps to reproduce

- in the default group (that doesn't share stock quantity) create a new shop and copy all data
- create a shop group that shares stock quantity
- create two shops and copy all data
- select shop context Single shop from first group
- the page is correctly displayed
- switch to a shop from the first group
- the page is correctly displayed
- switch to a shop from the second group
- an exception is thrown (see screencast)

### Screencast

https://watch.screencastify.com/v/msTVVCMW8NfxTnUhJeRf

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR starts the multishop modification in product list V2, but before that it also needs to fix bugs related with Shared group stock which was identified in #26738<br>To handle the product list in multishop this PR introduces the `ShopSearchCriteriaInterface` which is automatically built when the filters class extends `ShopFilters`
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26738
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

File: src/Core/Grid/Search/ShopSearchCriteriaInterface.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+
+namespace PrestaShop\PrestaShop\Core\Grid\Search;
+
+use PrestaShop\PrestaShop\Core\Domain\Shop\ValueObject\ShopConstraint;
+
+/**
+ * This extended interface of the SearchCriteriaInterface integrates a mandatory ShopConstraint
+ * which is used for multishop feature.
+ */
+interface ShopSearchCriteriaInterface extends SearchCriteriaInterface
```
Comment (zuk3975) [inline src/Core/Grid/Search/ShopSearchCriteriaInterface.php:37]: Oh this is probably the answer to my question here https://github.com/PrestaShop/PrestaShop/pull/30585#discussion_r1049649628 :+1:

File: src/Core/Search/ShopFilters.php [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+abstract class ShopFilters extends Filters implements ShopSearchCriteriaInterface
+{
+    /**
+     * @var ShopConstraint
+     */
+    private $shopConstraint;
+
+    /**
+     * @param ShopConstraint $shopConstraint
+     * @param array $filters
```
Comment (zuk3975) [inline src/Core/Search/ShopFilters.php]: could define filters array structure? I think it could at least show that array is associative no? (array<string, mixed>). Not sure if there are/ever wiil be filters with integers as keys :thinking:

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/shop_list.html.twig [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+ *#}
+
+{# The first shop is always displayed entirely and in bold #}
+{% set shops = record[column.options.field] %}
+{% set allShops = shops|join(', ') %}
+<span class="product-shop-list" title="{{ allShops }}">
+  {% set firstShop = shops[0] %}
+  <strong>{{ firstShop }}</strong>
+  {%- if shops|length > 1 -%}
+    ,
```
Comment (zuk3975) [inline src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/shop_list.html.twig:33]: is this comma supposed to be here? just a heads up to make sure its not some typo (looks suspicious :smile:)

File: tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php [hunk 4]
```diff
@@ -263,20 +267,27 @@ public function assertInvalidOutOfStockType(): void
...
+        ));
         $index = 0;
         foreach ($movementsData as $movementDatum) {
             $stockMovement = $stockMovements[$index];
             Assert::assertEquals(
                 $movementDatum['employee'],
                 $stockMovement->getEmployeeName(),
                 sprintf(
-                    'Invalid employee name of stock movement event, expected "%s" instead of "%s"',
+                    'Invalid employee name of stock movement event for shop%d, expected "%s" instead of "%s"',
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php]:
```suggestion
                    'Invalid employee name of stock movement event for shop %d, expected "%s" instead of "%s"',
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php [hunk 5]
```diff
@@ -285,7 +296,8 @@ private function assertStockMovementHistories(array $stockMovements, TableNode $
                 (int) $movementDatum['delta_quantity'],
                 $stockMovement->getDeltaQuantity(),
                 sprintf(
-                    'Invalid delta quantity of stock movement event, expected "%d" instead of "%d"',
+                    'Invalid delta quantity of stock movement event for shop%d, expected "%d" instead of "%d"',
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php:299]:
```suggestion
                    'Invalid delta quantity of stock movement event for shop %d, expected "%d" instead of "%d"',
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php (hunk 4 above)
Comment (zuk3975) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php]: unless you made this intentionally? But it might be confusing with the shop reference this way. Because we use lots of shops references called "shop1", "shop2".
Check other parts, this one is repeated in some places bellow :arrow_down:

File: tests/Integration/PrestaShopBundle/Controller/GridControllerTestCase.php [hunk 6]
```diff
@@ -128,12 +128,18 @@ protected function parseEntitiesFromGridTable(Crawler $crawler): TestEntityDTOCo
             }
         }
 
+        // Get total number
+        $gridTitleHeader = trim($crawler->filter('.card-header-title')->first()->text());
+        preg_match('/\(([0-9]+)\)/', $gridTitleHeader, $titleMatches);
+        $totalCount = (int) ($titleMatches[1] ?? 0);
```
Comment (zuk3975) [inline tests/Integration/PrestaShopBundle/Controller/GridControllerTestCase.php]: it all seems so complicated and unreliable. But I guess it is how those tests must be written? :smile: Have no experience in this area :(

File: tests/Integration/PrestaShopBundle/Controller/TestEntityDTO.php [hunk 7]
```diff
@@ -69,12 +69,24 @@ public function getId(): ?int
...
-    public function __get(string $variableName)
+    public function getVariable(string $variableName)
     {
         if (!isset($this->variables[$variableName])) {
             throw new VariableNotFoundException(sprintf('Variable %s not found in entity', $variableName));
         }
 
         return $this->variables[$variableName];
     }
+
```
Comment (zuk3975) [inline tests/Integration/PrestaShopBundle/Controller/TestEntityDTO.php:80]: didn't notice this TestEntityDTO class before. Naming is so strange. It should either be Entity or a DTO, but not both (or is it like a DTO for Testing the entity? :smile: Anyway just TestEntity would be enough I guess..)

**Review by zuk3975 — DISMISSED** [review]
some optional notes

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/shop_list.html.twig (hunk 3 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Columns/Content/shop_list.html.twig:33]: Yes the list of shops is separated by commas so it's on purpose this one is added if there is more than one shop The other ones via the `join` And to make sure there is no extra space I use the `{%- -%}` twig notation (with extra `-`) so that the spaces are trimmed (I'll add a screenshot to display how it looks like)

File: tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php (hunk 4 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php]: No it was a typo, thanks

File: tests/Integration/PrestaShopBundle/Controller/GridControllerTestCase.php (hunk 6 above)
Comment (jolelievre) [reply tests/Integration/PrestaShopBundle/Controller/GridControllerTestCase.php]: Well I didn't find any proper data attributes to fetch this data 😅 So I had to parse the title, but you're right it's not ideal I'm gonna add a proper data attribute in the template, it could be useful for JS as well someday

File: tests/Integration/PrestaShopBundle/Controller/TestEntityDTO.php (hunk 7 above)
Comment (jolelievre) [reply tests/Integration/PrestaShopBundle/Controller/TestEntityDTO.php:80]: Actually, that's what you said it's a generic DTO used to test any entity 😅 So the naming isn't that bad, I don't mind it but if you want me to change it I don't mind either But TestEntity makes it sound like it's a specific Entity that would have been implemented as a specific use case for test, whereas this is a generic structure that can be used to test any entity

File: src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php [hunk 8]
```diff
@@ -125,16 +151,21 @@ public function __construct(
...
+        $this->productMultiShopRepository = $productMultiShopRepository;
     }
 
     /**
      * {@inheritdoc}
      */
     public function getData(SearchCriteriaInterface $searchCriteria): GridData
     {
-        $productData = $this->productGridDataFactory->getData($searchCriteria);
+        if (!$searchCriteria instanceof ShopSearchCriteriaInterface) {
```
Comment (lartist) [inline src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:163]: Why not changing the parameter type instead?

File: src/Adapter/Product/Stock/Update/ProductStockUpdater.php [hunk 9]
```diff
@@ -305,23 +322,34 @@ private function updateStockAvailable(StockAvailable $stockAvailable, ProductSto
         $this->stockAvailableRepository->update($stockAvailable);
 
         if ($properties->getStockModification()) {
+            if ($stockAvailable->getShopId()) {
+                $shopId = $stockAvailable->getShopId();
+            } else {
+                // We can use any shop from the shop group, the stock movement will correctly associate the proper StockAvailable based on the shopId only
+                $shopsFromGroup = $this->shopGroupRepository->getShopsFromGroup(new ShopGroupId((int) $stockAvailable->id_shop_group));
+                $shopId = $shopsFromGroup[0]->getValue();
```
Comment (lartist) [inline src/Adapter/Product/Stock/Update/ProductStockUpdater.php]: If you want to fetch the first item I think you should use reset() instead since we don't have the control on the index type

File: src/Adapter/Shop/Repository/ShopGroupRepository.php [hunk 10]
```diff
@@ -49,4 +128,24 @@ public function assertShopGroupExists(ShopGroupId $shopGroupId): void
...
     }
+
+    /**
+     * @param ShopGroupId $shopGroupId
+     *
+     * @return ShopId[]
+     */
+    public function getShopsFromGroup(ShopGroupId $shopGroupId): array
+    {
+        $qb = $this->connection->createQueryBuilder();
```
Comment (lartist) [inline src/Adapter/Shop/Repository/ShopGroupRepository.php]: Not a big deal but why building query in two times instead of one et pass the result directly to the array map? :)

File: tests/Integration/Behaviour/Features/Context/Domain/Product/AbstractProductFeatureContext.php [hunk 11]
```diff
@@ -390,4 +390,19 @@ protected function getManufacturerId(string $manufacturerReference): int
...
     }
+
+    /**
+     * @param string $shopReferences
+     *
+     * @return int[]
+     */
+    protected function getShopIdsFromReferences(string $shopReferences): array
+    {
+        $shopIds = [];
```
Comment (lartist) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/AbstractProductFeatureContext.php]: Not a big deal but array_map is clearly more elegant !

File: tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php (hunk 5 above)
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/StockAssertionFeatureContext.php]: Missed one
```suggestion
                    'Invalid delta quantity of stock movement event for shop %d, expected "%d" instead of "%d"',
```

File: src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/Product/Grid/Data/Factory/ProductGridDataFactoryDecorator.php:163]: I can't because of the interface it implements, if I change the type it's no longer compatible..

File: src/Adapter/Product/Stock/Update/ProductStockUpdater.php (hunk 9 above)
Comment (jolelievre) [reply src/Adapter/Product/Stock/Update/ProductStockUpdater.php]: Hmm, but we dot know how the DB result is returned though 🤔 It's always a 0-indexed array

**Review by zuk3975 — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Comment by jolelievre** [comment]
This only a partial PR so it is merged early the QA will be done when the whole feature is finished
