### PR TITLE
Fix sorting issue in the SQL Manager page

### LINKED ISSUE #10990: SQL Manager - Sorting by SQL query causes an exception
**Describe the bug**

In the BO => Database / SQL Manager page, when we try to filter by SQL query => an exception occured

**To Reproduce**
1. Go to BO => Database / SQL Manager page
2. Create at least 2 SQL Query
3. After that, try to apply a sort on SQL Query with icon
image

**Screenshots**
image
https://drive.google.com/file/d/1dSqKBISsiUZCFcwGS7bSE5FvlTvg4xNx/view

**Additionnal information**
PrestaShop version: 1.7.4.3 / 1.7.5.x
PHP version: 7.1

### PR DESCRIPTION
**Pull request by khouloudbelguith**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | It is impossible to sort by SQL query in the SQL Manager page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10990
| How to test?  | Go to BO => Database / SQL Manager page => Create at least 2 SQL Query => After that, try to apply a sort on SQL Query with the icon

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10991)

### CODE REVIEW

**Comment by marionf** [comment]
@khouloudbelguith 
This is not a regression of 1.7.5.0, can you do it on develop branch please ?

**Comment by Quetzacoalt91** [comment]
Hmm, I'm not sure this fix is the best we could find.

This is not the first I see about the SQL columns in a table filtering, and instead of modifying all the occurrences which could trigger errors, I would rather make a global change.

In your case:

```sql
SELECT SQL_CALC_FOUND_ROWS  a.*  FROM `ps_request_sql` a     WHERE 1    ORDER BY sql DESC  LIMIT 0, 50;
```

Doesn't work. But

```sql
SELECT SQL_CALC_FOUND_ROWS  a.*  FROM `ps_request_sql` a     WHERE 1    ORDER BY a.sql DESC  LIMIT 0, 50;
```

does, thanks to your change, and

```sql
SELECT SQL_CALC_FOUND_ROWS  a.*  FROM `ps_request_sql` a     WHERE 1    ORDER BY `sql` DESC  LIMIT 0, 50;
```

works as well. It seems that applying quotes around the column names would make the SQL requests working in all case, without modifying the controller.

**Review by jolelievre — DISMISSED** [review]
nice job! @khouloudbelguith

**Review by Quetzacoalt91 — CHANGES_REQUESTED** [review]
Sorry my last message was unclear but I requested changes.

**Comment by jolelievre** [comment]
@Quetzacoalt91 I see your point, so I am not a pro of AdminController but it seems the change should be made here in this case:

https://github.com/PrestaShop/PrestaShop/blob/d0313c0881f957f9fab42bf2bb1a4e15df7081f0/classes/controller/AdminController.php#L3378

```php
        if (preg_match('/[.!]/', $orderBy)) {
            $orderBySplit = preg_split('/[.!]/', $orderBy);
            $orderBy = bqSQL($orderBySplit[0]) . '.`' . bqSQL($orderBySplit[1]) . '`';
        } elseif ($orderBy) {
            $orderBy = bqSQL($orderBy);
        }
```
becomes:
```php
        if (preg_match('/[.!]/', $orderBy)) {
            $orderBySplit = preg_split('/[.!]/', $orderBy);
            $orderBy = bqSQL($orderBySplit[0]) . '.`' . bqSQL($orderBySplit[1]) . '`';
        } elseif ($orderBy) {
            $orderBy = bqSQL('`' . $orderBy . '`');
        }
```

**Comment by Quetzacoalt91** [comment]
Almost, by looking at the existing code, a better solution would be

```php
            $orderBy = '`' . bqSQL($orderBy) . '`';
```

**Comment by jolelievre** [comment]
that's what I thought initially, but in the previous condition the quote are integrated inside the bqSQL call:

```php
$orderBy = bqSQL($orderBySplit[0]) . '.`' . bqSQL($orderBySplit[1]) . '`';
```

weird?

**Comment by khouloudbelguith** [comment]
Hi @Quetzacoalt91, @jolelievre, thanks for your review.
@Quetzacoalt91 Done, I made new changes & it works perfectly.

File: controllers/admin/AdminRequestSqlController.php [hunk 1]
```diff
@@ -50,10 +50,7 @@ public function __construct()
         $this->fields_list = array(
             'id_request_sql' => array('title' => $this->trans('ID', array(), 'Admin.Global'), 'class' => 'fixed-width-xs'),
             'name' => array('title' => $this->trans('SQL query Name', array(), 'Admin.Advparameters.Feature')),
-            'sql' => array(
-                'title' => $this->trans('SQL query', array(), 'Admin.Advparameters.Feature'),
-                'filter_key' => 'a!sql',
-            ),
+            'sql' => array('title' => $this->trans('SQL query', array(), 'Admin.Advparameters.Feature')),
```
Comment (jolelievre) [inline controllers/admin/AdminRequestSqlController.php]: I think that with the other modification in AdminController, this one is no longer useful

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by jolelievre** [comment]
great! thank you @khouloudbelguith ^^

**Review by jolelievre — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @khouloudbelguith
