### PR TITLE
Finish migration "Catalog > Monitoring" page

### LINKED ISSUE #10552: Migrate "Catalog > Monitoring" page
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate all grids of the page https://github.com/PrestaShop/PrestaShop/pull/13529
- [x] Implement product actions usable in grid (see `@todo` in https://github.com/PrestaShop/PrestaShop/pull/13529/files) https://github.com/PrestaShop/PrestaShop/pull/16267
- [x] Fix monitoring grids id configuration https://github.com/PrestaShop/PrestaShop/pull/15757
- [x] Add Helper card (see below) https://github.com/PrestaShop/PrestaShop/pull/16267
- [x] Fix old issue (see below): remove a button
- [x] Unhide page https://github.com/PrestaShop/PrestaShop/pull/16588

Old issue: https://github.com/PrestaShop/PrestaShop/issues/11482

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This ends the migration of the page Catalog > Monitoring
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10552 #14923
| How to test?  | use `/admin-dev/index.php/sell/catalog/monitoring` url to see the migrated page. Everything should be working like legacy

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16267)

### CODE REVIEW

**Comment by matks** [comment]
🎉

File: admin-dev/themes/new-theme/js/pages/monitoring/index.js [hunk 1]
```diff
@@ -69,12 +67,12 @@ $(() => {
 
     grid.addExtension(new ExportToSqlManagerExtension());
     grid.addExtension(new ReloadListActionExtension());
-    grid.addExtension(new SortingExtension());
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/monitoring/index.js:72]: It seems logical to remove them as they are not needed 🤔 did you check @atomiix or do you want us to check that they are not needed for sure ?

File: src/Adapter/Product/CommandHandler/SetProductIsEnabledHandler.php [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+        $product = new Product($productId);
+
+        if ($product->id !== $productId) {
+            throw new ProductNotFoundException(sprintf(
+                'Product with id "%s" was not found',
+                $productId
+            ));
+        }
+
+        if (!$product->toggleStatus()) {
```
Comment (matks) [inline src/Adapter/Product/CommandHandler/SetProductIsEnabledHandler.php]: Warning : this is not a `ToggleProductStatusCommand` but rather a `SetProductIsEnabledCommand` with a  `$isEnabled` property.

If your code is run, it ignores the `$isEnabled` property and toggles the status no matter what.

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php [hunk 3]
```diff
@@ -247,4 +261,51 @@ private function getProductWithoutPriceGrid(ProductWithoutPriceFilters $filters)
...
+     * @AdminSecurity(
+     *     "is_granted(['update'], request.get('_legacy_controller'))",
+     *     message="You do not have permission to update this."
+     * )
+     *
+     * @param $productId
+     *
+     * @return JsonResponse
+     */
+    public function toggleStatusAction($productId)
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php]: Shall we put this action in MonitoringController ... or in ProductController 🤔 ?

I think ProductController is maybe better ? For example is in the products listing we have a toggle action too, we will want to reuse this action and it would be strange that a Products Listing calls an ajax route in MonitoringController.

File: src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml [hunk 4]
```diff
@@ -53,3 +53,9 @@ services:
           'es': 'http://doc.prestashop.com/display/PS17/Gestionar+Atributos+del+Producto'
           'it': 'http://doc.prestashop.com/display/PS17/Gestire+gli+Attributi+dei+Prodotti'
           '_fallback': 'http://doc.prestashop.com/display/PS17/Managing+Product+Attributes'
+        'monitoring':
+          'en': 'http://doc.prestashop.com/display/PS17/Monitoring+your+Catalog'
```
Comment (matks) [inline src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml]: Let's use https instead. I see previous links were using http but this is a mistake, I'll fix it.

Security matters 🍾

File: src/Adapter/Product/QueryHandler/GetProductIsEnabledHandler.php [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+
+use PrestaShop\PrestaShop\Adapter\Entity\Product;
+use PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductNotFoundException;
+use PrestaShop\PrestaShop\Core\Domain\Product\Query\GetProductIsEnabled;
+use PrestaShop\PrestaShop\Core\Domain\Product\QueryHandler\GetProductIsEnabledHandlerInterface;
+
+/**
+ * @internal
+ */
+final class GetProductIsEnabledHandler implements GetProductIsEnabledHandlerInterface
```
Comment (matks) [inline src/Adapter/Product/QueryHandler/GetProductIsEnabledHandler.php:37]: 👍

File: src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/monitoring.yml [hunk 6]
```diff
@@ -11,3 +11,13 @@ admin_monitoring_search:
   defaults:
     _controller: 'PrestaShopBundle:Admin/Sell/Catalog/Monitoring:search'
     _legacy_controller: AdminTracking
+
+admin_monitoring_toggle_status:
```
Comment (matks) [inline src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/monitoring.yml]: Should become a product route, not a monitoring route
as stated before

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Monitoring/Blocks/showcase_card.html.twig [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2019 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ *#}
+
+{% if not isShowcaseCardClosed %}
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Monitoring/Blocks/showcase_card.html.twig:26]: 👍

File: admin-dev/themes/new-theme/js/pages/monitoring/index.js (hunk 1 above)
Comment (atomiix) [reply admin-dev/themes/new-theme/js/pages/monitoring/index.js:72]: Yes I checked but I'm not against a double check :)

File: src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml (hunk 4 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml]: We may have to change the documentation too then? https://docs.google.com/document/d/1xeiEwT02OpBxePesgdd68HxKD6XZe6PqYAT3KD76ol4

Comment (matks) [reply src/PrestaShopBundle/Resources/config/services/core/util/helper_card.yml]: Yes indeed

File: src/Adapter/Product/CommandHandler/SetProductIsEnabledHandler.php [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+use PrestaShop\PrestaShop\Adapter\Entity\Product;
+use PrestaShop\PrestaShop\Core\Domain\Product\Command\SetProductIsEnabledCommand;
+use PrestaShop\PrestaShop\Core\Domain\Product\CommandHandler\SetProductIsEnabledCommandHandlerInterface;
+use PrestaShop\PrestaShop\Core\Domain\Product\Exception\CannotUpdateProductException;
+use PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductNotFoundException;
+
+/**
+ * @internal
+ */
+class SetProductIsEnabledHandler implements SetProductIsEnabledCommandHandlerInterface
```
Comment (Progi1984) [inline src/Adapter/Product/CommandHandler/SetProductIsEnabledHandler.php]: @atomiix The name of the class is not what the class do. Why not `ToggleProductStatusHandler` or `UpdateProductStatusHandler` like `Order` with `UpdateOrderStatusHandler` ?

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php [hunk 9]
```diff
@@ -90,6 +92,10 @@ public function indexAction(
         $productWithoutDescriptionGrid = $this->getProductWithoutDescriptionGrid($productWithoutDescriptionFilters);
         $productWithoutPriceGrid = $this->getProductWithoutPriceGrid($productWithoutPriceFilters);
 
+        $showcaseCardIsClosed = $this->getQueryBus()->handle(
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php]:
```suggestion
        $isShowcaseCardClosed = $this->getQueryBus()->handle(
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php [hunk 10]
```diff
@@ -101,6 +107,8 @@ public function indexAction(
             'productWithoutImageGrid' => $this->presentGrid($productWithoutImageGrid),
             'productWithoutDescriptionGrid' => $this->presentGrid($productWithoutDescriptionGrid),
             'productWithoutPriceGrid' => $this->presentGrid($productWithoutPriceGrid),
+            'showcaseCardName' => ShowcaseCard::MONITORING_CARD,
+            'isShowcaseCardClosed' => $showcaseCardIsClosed,
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController.php]:
```suggestion
            'isShowcaseCardClosed' => $isShowcaseCardClosed,
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

File: src/Adapter/Product/CommandHandler/SetProductIsEnabledHandler.php (hunk 8 above)
Comment (PierreRambaud) [reply src/Adapter/Product/CommandHandler/SetProductIsEnabledHandler.php]: `SetOrderStatusHandler`?

File: src/Adapter/Product/QueryHandler/GetProductIsEnabledHandler.php [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+        $productId = $query->getProductId()->getValue();
+        $product = new Product($productId);
+
+        if ($product->id !== $productId) {
+            throw new ProductNotFoundException(
+                sprintf('Product with id "%s" was not found.', $productId)
+            );
+        }
+
+        return $product->active;
```
Comment (PierreRambaud) [inline src/Adapter/Product/QueryHandler/GetProductIsEnabledHandler.php]:
```suggestion
        return (bool) $product->active;
```
AFAIK it's currently a integer :nauseated_face:

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @atomiix
