### PR TITLE
Do not try to install an unsupported language

### LINKED ISSUE #12178: Can't import tanzania pack
**Describe the bug**
When you try to import Tanzania pack, you have an exception (develop branch) instead of an error message (1.7.5.1)

**To Reproduce**
1. Go to International > Localization
2. Select Tanzania
3. Click on Import

**Screenshots**

capture d ecran_935

It's working in 1.7.5.1
capture d ecran_936

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If a localization have a language we don't support, we must display an error message instead of an exception.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12178 .
| How to test?  | Follow ticket instruction

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13222)

### CODE REVIEW

File: classes/Language.php [hunk 1]
```diff
@@ -1072,15 +1072,15 @@ public static function downloadAndInstallLanguagePack($iso, $version = _PS_VERSI
...
-        } else {
-            $lang_pack = self::getLangDetails($iso);
-            self::installSfLanguagePack($lang_pack['locale'], $errors);
-            self::generateEmailsLanguagePack($lang_pack, $errors);
+        if (Language::downloadLanguagePack($iso, $version, $errors)) {
+            if ($install) {
+                Language::installLanguagePack($iso, $params, $errors);
+                Language::updateMultilangTable($iso);
+            } else {
+                $lang_pack = self::getLangDetails($iso);
```
Comment (Quetzacoalt91) [inline classes/Language.php:1080]: Should we add a test when `$lang_pack` is false?

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by tomlev — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13222)* status: all files reviewed, 1 unresolved discussion (waiting on @PierreRambaud)
