### PR TITLE
Fixed sort for naming in Admin > Carriers list

### LINKED ISSUE #21640: BO - Carriers page - The sort by Name is not working correctly
#### Describe the bug

In the BO > Shipping > Carriers page > the sort by name is not working correctly.
In fact, sorting by Name is reversed comparing the sort by ID (for example)

#### Expected behavior

image

#### Steps to Reproduce

1. Go to BO > Shipping > Carriers page
2. sort by name
4. See the error

#### Additional information

* PrestaShop version: Develop (178)
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed sort for naming in Admin > Carriers list : Replace "0" by the name of the shop directly in SQL query (allowing sort without errors)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21640
| How to test?      |  Cf. #21640

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25302)

### CODE REVIEW

File: controllers/admin/AdminCarriersController.php [hunk 1]
```diff
@@ -649,6 +649,23 @@ public function getList($id_lang, $order_by = null, $order_way = null, $start =
...
+                $bName = strtolower($b['name']);
+                if ($aName == $bName) {
+                    return 0;
+                }
+                if ($orderWay == 'ASC') {
+                    return ($aName < $bName) ? -1 : 1;
+                } else {
+                    return ($aName > $bName) ? -1 : 1;
+                }
+            });
```
Comment (PierreRambaud) [inline controllers/admin/AdminCarriersController.php]: Could you please externalise the method instead of using anonymous one.
It also need a little refactoring like testing the key 'name' exists, and remove useless else at the end :)

Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Fixed

File: controllers/admin/AdminCarriersController.php [hunk 2]
```diff
@@ -649,6 +649,31 @@ public function getList($id_lang, $order_by = null, $order_way = null, $start =
...
+            usort($this->_list, [$this, 'sortListByName']);
+        }
+    }
+
+    /**
+     * @param array $a
+     * @param array $b
+     *
+     * @return int
+     */
```
Comment (PierreRambaud) [inline controllers/admin/AdminCarriersController.php]:
```suggestion
    /**
     * Sort arrays based on the name
      *
     * @param array $a The first array to compare
     * @param array $b The second array to compare 
     *
     * @return int 0 if they are equal. If the order way is ASC, -1 for lower and 1 for greater, otherwise, it's the opposite
     */
```

Could be more explicit ^^

File: controllers/admin/AdminCarriersController.php [hunk 3]
```diff
@@ -649,6 +649,31 @@ public function getList($id_lang, $order_by = null, $order_way = null, $start =
...
+    private function sortListByName(array $a, array $b): int
+    {
+        $aName = strtolower($a['name'] ?? '');
+        $bName = strtolower($b['name'] ?? '');
```
Comment (PierreRambaud) [inline controllers/admin/AdminCarriersController.php]:
```suggestion
        $aName = isset($a['name']) ? strtolower($a['name']) : '';
        $bName = isset($b['name']) ? strtolower($b['name']) : '';
```

File: controllers/admin/AdminCarriersController.php (hunk 2 above)
Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Fixed

File: controllers/admin/AdminCarriersController.php (hunk 3 above)
Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Fixed

File: controllers/admin/AdminCarriersController.php [hunk 4]
```diff
@@ -649,6 +649,33 @@ public function getList($id_lang, $order_by = null, $order_way = null, $start =
...
+     */
+    private function sortListByCarrierName(array $a, array $b): int
+    {
+        $aName = isset($a['name']) ? strtolower($a['name']) : '';
+        $bName = isset($b['name']) ? strtolower($b['name']) : '';
+        if ($aName == $bName) {
+            return 0;
+        }
+        if ($this->_orderWay == 'ASC') {
+            return ($aName < $bName) ? -1 : 1;
```
Comment (eternoendless) [inline controllers/admin/AdminCarriersController.php]:
```suggestion
            return $aName <=> $bName;
```

Seee https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.spaceship-op

File: controllers/admin/AdminCarriersController.php [hunk 5]
```diff
@@ -649,6 +649,33 @@ public function getList($id_lang, $order_by = null, $order_way = null, $start =
...
+        }
+
+        return ($aName > $bName) ? -1 : 1;
```
Comment (eternoendless) [inline controllers/admin/AdminCarriersController.php]:
```suggestion
        return $bName <=> $aName;
```

File: controllers/admin/AdminCarriersController.php (hunk 4 above)
Comment (eternoendless) [reply controllers/admin/AdminCarriersController.php]: Alternatively, remove the strtolower above and
```suggestion
            return strnatcasecmp($a['name'] ?? '', $b['name'] ?? '');
```

File: controllers/admin/AdminCarriersController.php (hunk 5 above)
Comment (eternoendless) [reply controllers/admin/AdminCarriersController.php]: Alternatively, remove the strtolower above and
```suggestion
        return strnatcasecmp($b['name'] ?? '', $a['name'] ?? '');
```

File: controllers/admin/AdminCarriersController.php (hunk 4 above)
Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Wow. I completly forgot that. I love it.

File: controllers/admin/AdminCarriersController.php (hunk 5 above)
Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Fixed

File: controllers/admin/AdminCarriersController.php [hunk 6]
```diff
@@ -649,6 +649,27 @@ public function getList($id_lang, $order_by = null, $order_way = null, $start =
...
+     * @param array $b The second array to compare
+     *
+     * @return int 0 if they are equal. If the order way is ASC, -1 for lower and 1 for greater, otherwise, it's the opposite
+     */
+    private function sortListByCarrierName(array $a, array $b): int
+    {
+        $aName = isset($a['name']) ? strtolower($a['name']) : '';
+        $bName = isset($b['name']) ? strtolower($b['name']) : '';
+
+        return $this->_orderWay == 'ASC' ? $aName <=> $bName : $bName <=> $aName;
```
Comment (eternoendless) [inline controllers/admin/AdminCarriersController.php]: Sorry, I should have known better. You can replace all this by the proper way to do sort by column. Here it is, for what it's worth:
```suggestion
            $names = array_column($this->_list, 'name');
            $sortOrder = $this->_orderWay == 'ASC' ? SORT_ASC : SORT_DESC;
            array_multistort($this->_list, $names, $sortOrder, SORT_NATURAL);
```

The real problem I'm seeing right now with your solution is that the sort is only performed on the current paginated result, not on the whole list.

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: controllers/admin/AdminCarriersController.php (hunk 6 above)
Comment (PierreRambaud) [reply controllers/admin/AdminCarriersController.php]: `usort` is really faster than `array_multisort` which is designed to compare elements from different arrays (or sub-arrays) at the same time. The `usort` is called on the `$this->_list` which is the same as you :thinking:

Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: I close this conversation, because I fix with a better solution.

**Comment by Progi1984** [comment]
@eternoendless & @PierreRambaud I close your conversation as I found a better (and cleaner, I find) solution for fixing naming sort. Please review when you have some availability. Thanks.

**Review by PierreRambaud — DISMISSED** [review]

File: controllers/admin/AdminCarriersController.php [hunk 7]
```diff
@@ -642,13 +642,13 @@ public function changeZones($id)
      */
     public function getList($id_lang, $order_by = null, $order_way = null, $start = 0, $limit = null, $id_lang_shop = false)
     {
-        parent::getList($id_lang, $order_by, $order_way, $start, $limit, $id_lang_shop);
+        // Replace "0" by the name of the shop directly in SQL query (allowing sort without errors)
+        $this->_select = 'CASE WHEN name = "0" '
+            . 'THEN "' . Carrier::getCarrierNameFromShopName() . '" '
```
Comment (matks) [inline controllers/admin/AdminCarriersController.php]: @PierreRambaud could this be an item that becomes a SQLi?

Comment (PierreRambaud) [reply controllers/admin/AdminCarriersController.php]: Oh yes
```suggestion
            . 'THEN "' . pSQL(Carrier::getCarrierNameFromShopName()) . '" '
```

**Review by PierreRambaud — DISMISSED** [review]

File: controllers/admin/AdminCarriersController.php [hunk 8]
```diff
@@ -642,13 +642,13 @@ public function changeZones($id)
      */
     public function getList($id_lang, $order_by = null, $order_way = null, $start = 0, $limit = null, $id_lang_shop = false)
     {
-        parent::getList($id_lang, $order_by, $order_way, $start, $limit, $id_lang_shop);
+        // Replace "0" by the name of the shop directly in SQL query (allowing sort without errors)
+        $this->_select = 'CASE WHEN name = "0" '
```
Comment (eternoendless) [inline controllers/admin/AdminCarriersController.php]: I think you need to do this:
```suggestion
        $this->_select .= ', CASE WHEN name = "0" '
```

... otherwise, you're replacing this: https://github.com/PrestaShop/PrestaShop/blob/30f668874fdc21d55eecb5a8fda6a48af317fe28/controllers/admin/AdminCarriersController.php#L138

File: controllers/admin/AdminCarriersController.php [hunk 9]
```diff
@@ -642,13 +642,13 @@ public function changeZones($id)
...
+            . 'THEN "' . pSQL(Carrier::getCarrierNameFromShopName()) . '" '
+            . 'ELSE name '
+            . 'END AS name';
```
Comment (eternoendless) [inline controllers/admin/AdminCarriersController.php]: Why not use if?
```suggestion
        $this->_select .= sprintf(
            ', IF(name = "0", "%s", name) AS name',
            pSQL(Carrier::getCarrierNameFromShopName())
        );
```

Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Thanks for the review. (And if have forgot the  `IF`).

**Comment by Progi1984** [comment]
@eternoendless I have applied your feedback. Thanks.

**Review by eternoendless — DISMISSED** [review]

File: controllers/admin/AdminCarriersController.php [hunk 10]
```diff
@@ -642,13 +642,13 @@ public function changeZones($id)
      */
     public function getList($id_lang, $order_by = null, $order_way = null, $start = 0, $limit = null, $id_lang_shop = false)
     {
-        parent::getList($id_lang, $order_by, $order_way, $start, $limit, $id_lang_shop);
+        // Replace "0" by the name of the shop directly in SQL query (allowing sort without errors)
+        $this->_select .= sprintf(
+            ', IF(name = "0", "%s", name) AS name',
```
Comment (sowbiba) [inline controllers/admin/AdminCarriersController.php]: why the comma before the IF ?
This method is public and _select is empty by default

Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: Because it's not empty as @eternoendless said

https://github.com/PrestaShop/PrestaShop/blob/30f668874fdc21d55eecb5a8fda6a48af317fe28/controllers/admin/AdminCarriersController.php#L138

Comment (PierreRambaud) [reply controllers/admin/AdminCarriersController.php]: But this line is also in a public method, not inside the constructor :thinking:

Comment (sowbiba) [reply controllers/admin/AdminCarriersController.php]: 👍🏾  you can call getList without renderList

Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: FYI (and after some searchs) :
* `renderList` is called and implement `$this->_select`
* After that, it calls `parent::renderList` (`classes/controller/AdminController.php`)
* This one calls `$this->getList($this->context->language->id);`
* So it's not empty

Comment (Progi1984) [reply controllers/admin/AdminCarriersController.php]: But I have improved the resiliency.

File: controllers/admin/AdminCarriersController.php [hunk 11]
```diff
@@ -642,13 +642,14 @@ public function changeZones($id)
      */
     public function getList($id_lang, $order_by = null, $order_way = null, $start = 0, $limit = null, $id_lang_shop = false)
     {
-        parent::getList($id_lang, $order_by, $order_way, $start, $limit, $id_lang_shop);
+        // Replace "0" by the name of the shop directly in SQL query (allowing sort without errors)
+        $this->_select = empty($this->_select) ? '' : ', ';
```
Comment (eternoendless) [inline controllers/admin/AdminCarriersController.php]: You're replacing `$this->_select` with `', '`, this is way is clearer.
```suggestion
        if (!empty($this->_select)) {
            $this->_select .= ', ';
        }
```

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

Thanks for the PR, looks good to me :)

**Comment by Progi1984** [comment]
Thanks @florine2623

**Comment by Progi1984** [comment]
Thanks @florine2623
