### PR TITLE
Fix body classes for manufacturer and supplier listings

### LINKED ISSUE #31320: FO manufacturer list page throws warning
### Describe the bug and add attachments

When visiting /brands and /suppliers page in front office on 8.1.x, you can see two warnings, because it's trying to access `$this->manufacturer` in `getTemplateVarPage` when there is no specific manufacturer set.

Caused by https://github.com/PrestaShop/PrestaShop/pull/29264
Fixed by https://github.com/PrestaShop/PrestaShop/pull/31319

### Expected behavior

No warnings.

### Steps to reproduce

1. FO > Brands or Suppliers page
2. See warnings

### PrestaShop version(s) where the bug happened

8.1.x

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | In https://github.com/PrestaShop/PrestaShop/pull/29264, I did not realize there is also a case when there is no specific manufacturer = their listing. It was missed during QA. It throws `Warning: Attempt to read property "id" on null in controllers\front\listing\ManufacturerController.php on line 242` and `Warning: Attempt to read property "name" on null in controllers\front\listing\ManufacturerController.php on line 243`.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Visit `/brands` and see that the warnings are gone. Visit `/brand/2-graphic-corner` and see that body classes are still there.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/31320
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

File: controllers/front/listing/ManufacturerController.php [hunk 1]
```diff
@@ -239,8 +239,10 @@ public function getTemplateVarPage()
     {
         $page = parent::getTemplateVarPage();
 
-        $page['body_classes']['manufacturer-id-' . $this->manufacturer->id] = true;
-        $page['body_classes']['manufacturer-' . $this->manufacturer->name] = true;
+        if (Validate::isLoadedObject($this->manufacturer) && $this->manufacturer->active && $this->manufacturer->isAssociatedToShop()) {
+            $page['body_classes']['manufacturer-id-' . $this->manufacturer->id] = true;
+            $page['body_classes']['manufacturer-' . $this->manufacturer->name] = true;
+        }
```
Comment (PululuK) [inline controllers/front/listing/ManufacturerController.php]: Hi @Hlavtox, thanks for your contribution :)
It's already checked during the initialization (see `init` and `initContent`). 
The real issue here, is that you are calling the parent initialization before the check (see `ManufacturerController::initContent`) the `parent::initContent` must be called after the check. 
So I suggest to solve this problem at lowest level.

**Review by PululuK — DISMISSED** [review]

File: controllers/front/listing/ManufacturerController.php (hunk 1 above)
Comment (Hlavtox) [reply controllers/front/listing/ManufacturerController.php]: Not sure it will solve anything. I am solving manufacturers listing, there will never be a single manufacturer assigned. 🤷‍♂️

**Review by 0x346e3730 — DISMISSED** [review]

File: controllers/front/listing/ManufacturerController.php [hunk 2]
```diff
@@ -239,8 +239,10 @@ public function getTemplateVarPage()
     {
         $page = parent::getTemplateVarPage();
 
-        $page['body_classes']['manufacturer-id-' . $this->manufacturer->id] = true;
-        $page['body_classes']['manufacturer-' . $this->manufacturer->name] = true;
+        if (Validate::isLoadedObject($this->manufacturer) && $this->manufacturer->active && $this->manufacturer->isAssociatedToShop()) {
```
Comment (kpodemski) [inline controllers/front/listing/ManufacturerController.php]:
```suggestion
        if (!empty($this->manufacturer->id)) {
```

I agree with @PululuK. There's a check for that on the `init` method, so you only need to check whether you're on the manufacturer page or the listing, and you can do that by checking the object. No need for checking association, etc., because it is checked already at this point.

File: controllers/front/listing/SupplierController.php [hunk 3]
```diff
@@ -242,8 +242,10 @@ public function getTemplateVarPage()
     {
         $page = parent::getTemplateVarPage();
 
-        $page['body_classes']['supplier-id-' . $this->supplier->id] = true;
-        $page['body_classes']['supplier-' . $this->supplier->name] = true;
+        if (Validate::isLoadedObject($this->supplier) && $this->supplier->active && $this->supplier->isAssociatedToShop()) {
```
Comment (kpodemski) [inline controllers/front/listing/SupplierController.php]:
```suggestion
        if (!empty($this->supplier->id)) {
```

**Review by kpodemski — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Automated tests : https://github.com/florine2623/testing_pr/actions/runs/4202318255

LGTM ! It is QA ✅ 
Thanks!
