### PR TITLE
Missing log datas in some controllers and classes

### LINKED ISSUE #18517: Missing log datas in some controllers and classes
#### Describe the bug

Missing log datas in some controllers and classes

#### Expected behavior

When writing the logs, the `object_type` and `object_id` fields must be filled in (if necessary ...)

See https://github.com/PululuK/PrestaShop/blob/patch-2/src/Adapter/LegacyLogger.php#L168

#### Steps to Reproduce

1. Go to Product controller in BO
2. Delete or Update a product
3. Go to log controller in BO
4. See is missing Object type, Object id ...

**Screenshots**

https://drive.google.com/file/d/1bwJd1tKvuJYbhWiudIwFPdpo336lDnW1/view
#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

Hi @khouloudbelguith @marionf can you assign it to me please ?

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Missing log datas in some controllers and classes. When writing the logs, the **object_type** and **object_id** fields must be filled in (if necessary ...)
| Type?         | bug fix 
| Category?     | CO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/18517
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/18517

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18519)

### CODE REVIEW

**Comment by PululuK** [comment]
Needed for https://github.com/PrestaShop/PrestaShop/pull/16425

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 1]
```diff
@@ -1332,4 +1332,17 @@ private function getErrorMessages(): array
             CannotUpdateProductException::class => $this->trans('An error occurred while updating the status for an object.', 'Admin.Notifications.Error'),
         ];
     }
+
+    /**
+     * @return array
+     */
+    private static function getLogDataContext($id_product = null, $error_code = null, $allow_duplicate = null): array
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php]: @PululuK Why using a static ?

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]: @Progi1984 because I find it sexy (ᵢ'ₘ ₖᵢddᵢₙg ₒ𝆑 𝄴ₒᵤᵣₛₑ 😁)!
Very good question ... I will correct that ! Thanks man

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Module/ModuleDataProvider.php [hunk 2]
```diff
@@ -219,6 +219,10 @@ public function isModuleMainClassValid($name)
         }
 
         $parser = (new PhpParser\ParserFactory())->create(PhpParser\ParserFactory::PREFER_PHP7);
+        $log_context_data = [
+            'object_type' => 'Module',
+            'object_id' => LegacyModule::getModuleIdByName($name),
+         ];
 
         try {
```
Comment (PierreRambaud) [inline src/Adapter/Module/ModuleDataProvider.php]:
```suggestion
        $log_context_data = [
            'object_type' => 'Module',
            'object_id' => LegacyModule::getModuleIdByName($name),
        ];

        try {
```

Weird that php-cs-fixer is not crying oO

File: src/Adapter/Module/ModuleDataProvider.php [hunk 3]
```diff
@@ -231,7 +235,7 @@ public function isModuleMainClassValid($name)
                         '%parse_error%' => $exception->getMessage(),
                     ],
                     'Admin.Modules.Notification'
-                )
+                ), $log_context_data
```
Comment (PierreRambaud) [inline src/Adapter/Module/ModuleDataProvider.php:238]:
```suggestion
                ), 
                $log_context_data
```

File: src/Adapter/Module/ModuleDataProvider.php [hunk 4]
```diff
@@ -254,7 +258,7 @@ public function isModuleMainClassValid($name)
                             '%module%' => $name,
                             '%error_message%' => $e->getMessage(), ],
                         'Admin.Modules.Notification'
-                    )
+                    ), $log_context_data
```
Comment (PierreRambaud) [inline src/Adapter/Module/ModuleDataProvider.php:261]:
```suggestion
                    ), 
                    $log_context_data
```

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 5]
```diff
@@ -1332,4 +1332,17 @@ private function getErrorMessages(): array
...
+     * @return array
+     */
+    private function getLogDataContext($id_product = null, $error_code = null, $allow_duplicate = null): array
+    {
+        return [
+                'object_type' => 'Product',
+                'object_id' => $id_product,
+                'error_code' => $error_code,
+                'allow_duplicate' => $allow_duplicate,
+            ];
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php]: Something is broken with php-cs-fixer...

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]: Sorry @PierreRambaud , but ... who should i trust, you or `php-cs-fixer` 😅 ?

**Comment by PierreRambaud** [comment]
Could you rebase your pull request please, we update our cs-fixer configuration :)

**Comment by PululuK** [comment]
> Could you rebase your pull request please, we update our cs-fixer configuration :)

It's not the right branch ?

**Comment by PierreRambaud** [comment]
> > Could you rebase your pull request please, we update our cs-fixer configuration :)
> 
> It's not the right branch ?

Yes it is, but we update our cs fixer configuration and tests where not ran with the latest changes.

**Comment by PululuK** [comment]
> Yes it is, but we update our cs fixer configuration and tests where not ran with the latest changes.

Why rebase then? A simple git pull from remote branch should be enough, right?
If you can help me do it please ... I'm getting old for this stuff!

**Comment by PululuK** [comment]
@Progi1984  @PierreRambaud

**Comment by PierreRambaud** [comment]
Instead of using a merge commit, rebasing re-writes the project history by creating brand new commits for each commit in the original branch. It prevents having merge commits in the history.

**Comment by PululuK** [comment]
> Instead of using a merge commit, rebasing re-writes the project history by creating brand new commits for each commit in the original branch. It prevents having merge commits in the history.

Can you rebase please ?

**Comment by PierreRambaud** [comment]
@PululuK Of course, I'll do it for you :heart:

**Comment by Progi1984** [comment]
@PierreRambaud

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
The object type and the object ID are correctly added in the logs 
capture d'écran_19

Thanks @PululuK !

**Comment by Progi1984** [comment]
Thanks @PululuK
