### PR TITLE
Display customer groups in order detail

### LINKED ISSUE #23116: Customer's group is not displayed anywhere
#### Describe the bug

Merchant is unable to determine customer's group, unless he edits that customer.
It's very important for determining prices, discounts and communication with the customer.

#### Expected behavior

Customer group should be displayed on order screen and on customer's detail.
On order page, we can display it the same as we display "Guest" under customers name.
On customer detail page, it can be simply displayed in the information table.

**Screenshots**
How it can be done
customer

How guest is displayed
guest

Where it can be displayed on customer page
customer screen

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR displays the customer groups on order page. In the same spot as "Guest" was displayed, under customer's name.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23116
| How to test?      | Make an order with registered customer and see order page in backoffice, with and without a PR.
| Possible impacts? | no

**Screenshot**
customer groups

**Design spec**
Default group suffixed by (default), no group IDs.
https://github.com/PrestaShop/PrestaShop/issues/23116#issuecomment-883444007

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25080)

### CODE REVIEW

File: src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php [hunk 1]
```diff
@@ -116,7 +128,9 @@ public function __construct(
         ?string $privateNote,
         bool $isGuest,
         string $ape = '',
-        string $siret = ''
+        string $siret = '',
+        int $idDefaultGroup,
+        string $defaultGroupName
```
Comment (Progi1984) [inline src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php]: You can't add parameters without default value, after parameter with default value.

Comment (Progi1984) [reply src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php]: It's a BC Break as you change the signature.

Comment (Hlavtox) [reply src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php]: @Progi1984 Should I just add empty default values and it will be fine?

Comment (atomiix) [reply src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php]: Also, keep in mind that adding non-optional parameters after optional parameters is deprecated since PHP 8 ;)

Comment (Hlavtox) [reply src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php]: @atomiix @Progi1984 Can you help me with completing this PR? What should I do? :-)

Comment (matks) [reply src/Core/Domain/Order/QueryResult/OrderCustomerForViewing.php]: @Hlavtox I think what should be done is
```
public function __construct(
        int $id,
        string $firstName,
        string $lastName,
        string $gender,
        string $email,
        DateTimeImmutable $accountRegistrationDate,
        string $totalSpentSinceRegistration,
        int $validOrdersPlaced,
        ?string $privateNote,
        bool $isGuest,
        string $ape = '',
        string $siret = '',
        int $idDefaultGroup = null,
        string $defaultGroupName = null
    )
```

Then in your code, you must handle the case `if (null === $idDefaultGroup)`, what should happen in this case 😉

**Comment by prestascott** [comment]
Hello everyone,

Thanks @Hlavtox for this PR.

[Here is my comment on your design](https://github.com/PrestaShop/PrestaShop/issues/23116#issuecomment-883444007)

Let me know what do you think! ^^

**Comment by matks** [comment]
Hi @Hlavtox are you still invested in this PR or should we close it? It's been a while, did you move to another better subject?

**Comment by Hlavtox** [comment]
@matks Will do it, there wasn't much time. :-)

**Comment by Hlavtox** [comment]
@matks Didnt forget, will do it 😄

**Comment by matks** [comment]
Hi @Hlavtox you have many PRs open and there is only 24 hours in the day 😛  maybe we can close this PR to put it "on hold" and reopen later?

**Comment by Hlavtox** [comment]
@matks Tommorow!!!

**Comment by Hlavtox** [comment]
@matks @atomiix @Progi1984 Hi guys, I remade the PR so it displays all groups as designed.
BC break should be resolved, in case the last parameter is not provided, empty array is used and no groups displayed.

@prestascott Please check if it's to your design specs, I added a small shadow so it's better visible. :-)

customer groups

**Comment by prestascott** [comment]
@Hlavtox Thank you for your PR. Are the tags clickable? Because the shadows you added make them look like they are. The shadows increase the affordance of the tags and we don't want that. We just want users to identify the customer's groups and the white background is already doing its job well.

Can you please remove the shadows? :)

**Comment by Hlavtox** [comment]
@prestascott Removed

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig [hunk 2]
```diff
@@ -44,9 +44,7 @@
 
               <strong class="text-muted ml-2">#{{ orderForViewing.customer.id }}</strong>
             </h2>
-            {% if orderForViewing.customer.isGuest %}
-              <strong class="text-muted">Guest</strong>
-            {% endif %}
```
Comment (atomiix) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:49]: I think we should keep this, if a customer is in multiple groups, the information about him being a guest is easier to get here.

Comment (Hlavtox) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:49]: @atomiix It's gonna look the same. If you do not show groups for guests, you loose possible information, if some merchant assigns other groups to guests. And if you display both, it's weird.

Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:49]: Why would it be weird to display both? In one case, "Guest" is a group the customer is in, in the 2nd case, it's more of a "status". And as you can define other groups as guest, it may be important to remind that a customer is considered a guest by PrestaShop even though he's not in any group named "Guest".

Comment (Hlavtox) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:49]: It's gonna look like this. 
Výstřižek

The design was already validated and specified by Scott, please don't change it...

**Comment by Hlavtox** [comment]
@atomiix @matks Guys, can you remove Waiting for author and add QA pls?

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

Thanks for our PR. The feature is well added.

So, QA :heavy_check_mark: 

Here the tested cases : 
-Check with different and all combinations of customers (Guest, Visitor, Customer)  
image
image
image

-Check with default and multistore shops
-Check with mobile
image

Thanks!

**Review by kpodemski — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
@atomiix  : I just noticed that there is no reviewrs for this PR + the merging is blocked and you added the label waiting for QA yesterday!
Could you please check again? and i will add the QA approved label when everything is OK.

Thanks!

**Review by atomiix — APPROVED** [review]

**Comment by atomiix** [comment]
Thanks @Hlavtox @HanaRebaiQA

**Comment by prestascott** [comment]
The design from the PR seems different from my mockups, is it normal?

**Comment by Hlavtox** [comment]
@prestascott It's the same no worries Scott, Hana didn't build her assets it seems.

**Comment by Hlavtox** [comment]
It looks the same as on screenshot, but without shadows.

**Comment by prestascott** [comment]
Ok perfect thanks!
