### PR TITLE
Fix CLI install

### LINKED ISSUE #25959: Install of PrestaShop 1.7.8-rc.1 is not possible in CLI mode
#### Describe the bug

Install of PrestaShop 1.7.8-rc.1 is not possible in CLI mode.
I used this command
`php index_cli.php --language=fr --country=fr --domain=prestashop.com --base_uri=rc1780 --db_server=10.1.32.2 --db_user=root --db_name=1780cli --db_password=xxx --firstname=Demo --lastname=Prestashop --email=demo@prestashop.com --password=prestashop_demo --db_create=1 --newsletter=0 --send_email=0 --enable_ssl=1`

#### Expected behavior

Install in CLI mode work as before.

#### Steps to Reproduce

Make a composer create-project prestashop/prestashop:1.7.8-rc.1 and try to use the index_cli in order to install PrestaShop.

You will see this logs:

```
TypeError: Argument 1 passed to PrestaShop\PrestaShop\Core\Domain\Shop\ValueObject\ShopConstraint::shop() must be of the type int, null given, called in /src/Adapter/Configuration.php on line 422 and defined in /src/Core/Domain/Shop/ValueObject/ShopConstraint.php:62
Stack trace:
 
0 /src/Adapter/Configuration.php(422): PrestaShop\PrestaShop\Core\Domain\Shop\ValueObject\ShopConstraint::shop()
1 /src/Adapter/Configuration.php(106): PrestaShop\PrestaShop\Adapter\Configuration->buildShopConstraintFromContext()
2 /src/Core/Addon/Theme/ThemeRepository.php(74): PrestaShop\PrestaShop\Adapter\Configuration->get()
3 /classes/shop/Shop.php(495): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeRepository->getInstanceByName()
4 /classes/shop/Shop.php(137): ShopCore->setTheme()
5 /install-dev/controllers/console/process.php(71): ShopCore->__construct()
6 /install-dev/controllers/console/process.php(227): InstallControllerConsoleProcess->initializeContext()
7 /install-dev/controllers/console/process.php(138): InstallControllerConsoleProcess->processPopulateDatabase()
8 /install-dev/classes/controllerConsole.php(117): InstallControllerConsoleProcess->process()
9 /install-dev/index_cli.php(64): InstallControllerConsole::execute()
```

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8-rc.1
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | When installing PrestaShop in CLI in a subfolder (`--base_uri=/subfolder`), the installer throw an exception. This PR aims to fix this.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25959
| How to test?      | Try to install PrestaShop in CLI with the `--base_uri` option:`php install-dev/index_cli.php --base_uri=/subfolder`, no exception should be thrown
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25982)

### CODE REVIEW

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php [hunk 1]
```diff
@@ -52,29 +52,29 @@ class ShopConstraint
...
-     * @param int $shopId
+     * @param int|null $shopId
      * @param bool $isStrict
      *
      * @return static
      *
      * @throws ShopException
      */
-    public static function shop(int $shopId, bool $isStrict = false): self
+    public static function shop(?int $shopId, bool $isStrict = false): self
```
Comment (eternoendless) [inline src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: It makes no sense to set up a shop context without shopId

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php [hunk 2]
```diff
@@ -52,29 +52,29 @@ class ShopConstraint
...
-     * @param int $shopGroupId
+     * @param int|null $shopGroupId
      * @param bool $isStrict
      *
      * @return static
      *
      * @throws ShopException
      */
-    public static function shopGroup(int $shopGroupId, bool $isStrict = false): self
+    public static function shopGroup(?int $shopGroupId, bool $isStrict = false): self
```
Comment (eternoendless) [inline src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: Same here, you shouldn't be able to set a shop group constraint without shopGroupId

Comment (matthieu-rolland) [inline src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: what is the reason of this. modification ? it's supposed to be impossible to have a shopGroup or shop context without a related ID

**Review by matks — COMMENTED** [review]
I'll say exactly what my peers said 😄  this PR either contains a design issue or there is a very weird situation that obliges you to deal with it like this and then we need to understand the situation (the context of the bug) to understand the submitted changes.

**Comment by matks** [comment]
Also I'll be happy to help to setup a test case that fails today and will pass thanks to this PR

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: I agree this is breaking the interfaces we specifically built to be more strict
Sorry but the problem needs to be fixed at the source, not at the end of the problem I realize it's more complicated 😅

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/Core/Domain/Shop/ValueObject/ShopConstraint.php (hunk 2 above)
Comment (matks) [reply src/Core/Domain/Shop/ValueObject/ShopConstraint.php]: Or we need to understand why we have to do that. Legacy code could oblige us to do this dirty fix, but let's be fully aware of the how and why.

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PrestaEdit** [comment]
You can associate this issue into this PR: https://github.com/PrestaShop/PrestaShop/issues/25959

**Review by PrestaEdit — APPROVED** [review]
On user side, this fix the installation on CLI mode.

**Comment by PierreRambaud** [comment]
Thank you @atomiix
