### PR TITLE
Fix bad selector to fix checkbox issues on RMA

### LINKED ISSUE #28963: FO - merchandise return table: if we click on the checkbox in the header, checkboxes in the table are no more clickable
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the order details page when we want to return product, if we click on the checkbox in the header (encircled in red), checkboxes inside the table are no more clickable (encircled in orange) :
image
I reproduce the bug with the **Classic Theme** on FF/Chrome but not with the "Prestarocket Theme"

### Expected behavior

_No response_

### Steps to reproduce

1. Go to Your Account -> My order history and details
2. Select an order to return
3. Scroll down to the list of products
4. Click on the checkbox in the header
5. The checkboxes inside the table are no more clickable

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The current selector select too many elements in customer.js (form + checkbox) because of the comma. Without the comma, it select only the checkbox as expected
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28963
| Related PRs       | 
| How to test?      | See issue #28963
| Possible impacts? |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

File: themes/classic/_dev/js/selectors.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ prestashop.themeSelectors = {
     searchLink: '.js-search-link',
   },
   order: {
-    returnForm: '#order-return-form, .js-order-return-form',
+    returnForm: '#order-return-form.js-order-return-form',
```
Comment (kpodemski) [inline themes/classic/_dev/js/selectors.js]:
```suggestion
    returnForm: '#order-return-form.js-order-return-form',
```

are you sure? if you want to get one element you only need `#order-return-form`, maybe you forgot to put a space between ID and class selector?

Comment (mflasquin) [reply themes/classic/_dev/js/selectors.js]: I just let the selector with the class .js-order-return-form because maybe it was important. But indeed it would work with only with the #order-return-form

**Review by kpodemski — DISMISSED** [review]

File: themes/classic/_dev/js/selectors.js [hunk 2]
```diff
@@ -54,7 +54,7 @@ prestashop.themeSelectors = {
     searchLink: '.js-search-link',
   },
   order: {
-    returnForm: '#order-return-form, .js-order-return-form',
+    returnForm: '#order-return-form',
```
Comment (NeOMakinG) [inline themes/classic/_dev/js/selectors.js]: This will lead to a BC break and themes only using the prefixed `js-` class won't work anymore

These `js-` classes are the only thing we need but we kept old classes for retrocompatibility

```suggestion
    returnFormHeadCheckboxes: '#order-return-form table thead input[type=checkbox], .js-order-return-form table thead input[type=checkbox]',
    returnFormContentCheckboxes: '#order-return-form table thead input[type=checkbox], .js-order-return-form table thead input[type=checkbox]',
```

And then update `customer.js` accordingly like

```js
  $(`${prestashop.themeSelectors.order.returnFormHeadCheckboxes}`).on('click', function () {
    const checked = $(this).prop('checked');
    $(`${prestashop.themeSelectors.order.returnFormContentCheckboxes}`).each((_, checkbox) => {
      $(checkbox).prop('checked', checked);
    });
  });
```

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Thanks for the contrib @mflasquin but we can't accept it as it is, it will lead to some themes compatibility issues if we keep it like it is

**Review by matks — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

File: themes/classic/_dev/js/customer.js [hunk 3]
```diff
@@ -26,9 +26,9 @@ import $ from 'jquery';
 import prestashop from 'prestashop';
 
 function initRmaItemSelector() {
-  $(`${prestashop.themeSelectors.order.returnForm} table thead input[type=checkbox]`).on('click', function () {
+  $(`${prestashop.themeSelectors.order.returnFormHeadCheckboxes}`).on('click', function () {
```
Comment (NeOMakinG) [inline themes/classic/_dev/js/customer.js]:
```suggestion
  $(prestashop.themeSelectors.order.returnFormHeadCheckboxes).on('click', function () {
```

File: themes/classic/_dev/js/customer.js [hunk 4]
```diff
@@ -26,9 +26,9 @@ import $ from 'jquery';
 import prestashop from 'prestashop';
 
 function initRmaItemSelector() {
-  $(`${prestashop.themeSelectors.order.returnForm} table thead input[type=checkbox]`).on('click', function () {
+  $(prestashop.themeSelectors.order.returnFormHeadCheckboxes).on('click', function () {
     const checked = $(this).prop('checked');
-    $(`${prestashop.themeSelectors.order.returnForm} table tbody input[type=checkbox]`).each((_, checkbox) => {
+    $(`${prestashop.themeSelectors.order.returnFormContentCheckboxes}`).each((_, checkbox) => {
```
Comment (NeOMakinG) [inline themes/classic/_dev/js/customer.js]:
```suggestion
    $(prestashop.themeSelectors.order.returnFormContentCheckboxes).each((_, checkbox) => {
```

**Review by NeOMakinG — APPROVED** [review]
🍬

**Review by atomiix — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @mflasquin ,

Thanks for your PR. The issue is well fixed. Here is my checked list :

-Check with different languages: OK
-Check with different browsers: OK
-Check the automated tests: OK

[Untitled_ Sep 26, 2022 2_43 PM.webm](https://user-images.githubusercontent.com/111756615/192294864-7240b20a-4700-44bd-896c-502c226d0f31.webm)
