### PR TITLE
Dont show root category on category grid search results

### LINKED ISSUE #20067: [BO] - Category root displayed after filter
#### Describe the bug

When you filter categories by `name=root` or `displayed=Yes`, category root is displayed (unwanted behavior after the fix in #17399 )

#### Expected behavior

Category root not displayed

#### Steps to Reproduce

1. Go to 'BO -> categories page'
2. Filter by displayed = Yes
3. See result
image

#### Additional information

* PrestaShop version: branch 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | This PR excludes "root category" from "category grid search" in BO. This PR is the last milestone to obtain a fully green build on https://nightly.prestashop.com/ for PS 1.7.7
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20067
| How to test?  | See ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20433)

### CODE REVIEW

File: src/Core/Grid/Query/CategoryQueryBuilder.php [hunk 1]
```diff
@@ -70,6 +77,7 @@ final class CategoryQueryBuilder extends AbstractDoctrineQueryBuilder
      * @param int $contextShopId
      * @param MultistoreContextCheckerInterface $multistoreContextChecker
      * @param FeatureInterface $multistoreFeature
+     * @param int|null $contextShopId
```
Comment (Progi1984) [inline src/Core/Grid/Query/CategoryQueryBuilder.php]:
```suggestion
     * @param int|null $rootCategoryId
```

File: src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml [hunk 2]
```diff
@@ -136,6 +136,7 @@ services:
             - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
             - '@prestashop.adapter.shop.context'
             - '@prestashop.adapter.feature.multistore'
+            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
```
Comment (Progi1984) [inline src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml]: language.id ?

**Review by Progi1984 — COMMENTED** [review]
Some comment ?

File: src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml (hunk 2 above)
Comment (matks) [reply src/PrestaShopBundle/Resources/config/services/core/grid/doctrine_query_builder.yml]: Ooooh I totally messed up this PR 😨 

My initial code was good but it seems at the time to `git add` and `git commit` I mixed the PR with some other code changes

My bad. A total failure 😞

**Comment by matks** [comment]
@Progi1984 issues have been fixed ✅

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
HI @matks,

It is ok :heavy_check_mark: 
image

Ping @PrestaShop/qa-automation Tests should be updated!

Thanks!

**Comment by Progi1984** [comment]
Thanks @matks & @khouloudbelguith

**Comment by boubkerbribri** [comment]
> Ping @PrestaShop/qa-automation Tests should be updated!

Done with #20460

**Comment by matks** [comment]
Capture d’écran 2020-08-06 à 09 06 53

YOUHOUUUUUUUU 🎉
