### PR TITLE
Make customer note TYPE_STRING instead of TYPE_HTML

### LINKED ISSUE #21829: BO - Order page - Private note containing problematic characters
#### Describe the bug

In the BO > Orders > Order page > the private not working correctly with problematic characters: "toto & tata"
image

#### Expected behavior

It should be well displayed

#### Steps to Reproduce

1. Go to BO > Orders page
2. Open an order
3. In the Private note set this expression "toto & tata"
4. Save

image

PS: 1768 => ok
image

#### Additional information

* PrestaShop version: 1.7.7.0rc1build4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
## Please don't merge before release 1.7.7.0

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | With the new Order detail page, the customer private note is showing encoded html entities instead of the real character. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21829
| How to test?  | You should be able to save customer's note both from order detail page & customer detail page containing the character `&` and it should not be transformed to `&amp;`.<br><br>You should also check that the upgrade process is working following those steps:<br>1. Add a customer's private note containing the char `&` and see that it's changed to `&amp;`<br>2. Checkout this PR<br>3. Update `_PS_INSTALL_VERSION_` constant in `install-dev/install_version.php` with `'1.7.7.1'`<br>4. Run `php install-dev/upgrade/upgrade.php`<br>5. Check that the private note is now display correctly

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21992)

### CODE REVIEW

File: install-dev/upgrade/php/ps_1771_update_customer_note.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+            'UPDATE ' . _DB_PREFIX_ . 'customer
+            SET note = "' . html_entity_decode($note['note']) . '"
+            WHERE id_customer = ' . $note['id_customer']
+        );
+        if (false === $result) {
+            return false;
+        }
+    }
+
+    return true;
```
Comment (kpodemski) [inline install-dev/upgrade/php/ps_1771_update_customer_note.php]:
```suggestion
    $result = true;
    foreach ($notes as $note) {
        $result &= Db::getInstance()->execute(
            'UPDATE ' . _DB_PREFIX_ . 'customer
            SET note = "' . html_entity_decode($note['note']) . '"
            WHERE id_customer = ' . $note['id_customer']
        );
    }

    return $result;
```

**Review by kpodemski — DISMISSED** [review]
Little suggestion but not important

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/Customer.php [hunk 2]
```diff
@@ -194,7 +194,7 @@ class CustomerCore extends ObjectModel
             'max_payment_days' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'copy_post' => false],
             'active' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool', 'copy_post' => false],
             'deleted' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool', 'copy_post' => false],
-            'note' => ['type' => self::TYPE_HTML, 'validate' => 'isCleanHtml', 'size' => 65000, 'copy_post' => false],
+            'note' => ['type' => self::TYPE_STRING, 'validate' => 'isCleanHtml', 'size' => 65000, 'copy_post' => false],
```
Comment (Progi1984) [inline classes/Customer.php]:
```suggestion
            'note' => ['type' => self::TYPE_STRING, 'size' => 65000, 'copy_post' => false],
```

File: install-dev/upgrade/php/ps_1771_update_customer_note.php (hunk 1 above)
Comment (Progi1984) [reply install-dev/upgrade/php/ps_1771_update_customer_note.php]:
```suggestion
    $result = true;
    foreach ($notes as $note) {
        $result &= Db::getInstance()->execute(
            'UPDATE ' . _DB_PREFIX_ . 'customer
            SET note = "' . html_entity_decode($note['note']) . '"
            WHERE id_customer = ' . $note['id_customer']
        );
    }

    return (bool) $result;
```

File: install-dev/upgrade/php/ps_1771_update_customer_note.php [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+
+/*
+ * Since note is now TYPE_STRING instead of TYPE_HTML it needs to be decoded
+ */
+function ps_1771_update_customer_note()
+{
+    $notes = Db::getInstance()->executeS(
+        'SELECT id_customer, note FROM ' . _DB_PREFIX_ . 'customer
+        WHERE note IS NOT NULL AND note != ""'
+    );
```
Comment (matthieu-rolland) [inline install-dev/upgrade/php/ps_1771_update_customer_note.php:35]: my only concern here is the case where a shop has a lot of customers with notes, or even a lot of customers with notes on all of them. In the foreach below, it will make an update query foreach customer (potentially dozen of thousands on big shops...)

Not sure if having a batch mechanism here would be overkill or not (like making one update query per 50 items...)

**Review by matthieu-rolland — COMMENTED** [review]
a small feedback...

File: install-dev/upgrade/php/ps_1771_update_customer_note.php (hunk 3 above)
Comment (PierreRambaud) [reply install-dev/upgrade/php/ps_1771_update_customer_note.php:35]: Since we don't support MyISAM we can't prepare SQL requests then execute like a batch.
Also, note values are different for each customer, let make requests easier to read, easier to manipulate, because during the upgrade we don't want to crash the system :sweat_smile:

**Review by Progi1984 — DISMISSED** [review]

File: install-dev/upgrade/php/ps_1771_update_customer_note.php (hunk 3 above)
Comment (matthieu-rolland) [reply install-dev/upgrade/php/ps_1771_update_customer_note.php:35]: Well it's quite doable in php, but alright, it's probably overkill, and the query would be too complex, that's true, didn't think about how the query would look like  👍   

I'm always a bit scared of update queries inside a foreach when we don't know in advance the number of iterations... but I guess it's not a big deal

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an issue following these steps:

1. Go to BO > Orders >
2. Open an Order
3. In the Private note set this expression `<<`
image
4. Save
5. see error
image

I attached a screen record
https://drive.google.com/file/d/1_Vz96iYCzvl_uacmXrVfc60tH7kRV3Kr/view?usp=sharing

Thanks!

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1dgUmv8uBLiq_16tEuTaiWrvfVCZWM0tu/view?usp=sharing

Thank!

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
The upgrade log `*INFO* 	v1.7.7.0	2020/11/26 - 13:04:33: [OK] PHP 1.7.7.1 : /* PHP:ps_1771_update_customer_note(); */`
https://drive.google.com/file/d/1dgUmv8uBLiq_16tEuTaiWrvfVCZWM0tu/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
## Please don't merge before release 1.7.7.0

**Review by PierreRambaud — DISMISSED** [review]
Wait for 1.7.7.0 final

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
