### PR TITLE
Fallback to first found combination when fetching combination by all shops constraint

### LINKED ISSUE #31170: Shop association between combination and shop not found when updating product
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Product page v2.
Error happens when we try to load combination by shop constraint (CombinationRepository->getByShopConstraint) using All shops constraint. For All shops code tries to load combination for default shop, but in case it doesn't exist it will throw exeception.
For example doing product with combinations update, code will try update all default suppliers and for that it will search for combinations in all shops (because suppliers are not related specifically to any shop) and it will throw
Screenshot 2023-02-02 at 18 19 06
 CombinationShopAssociationNotFoundException. 

### Expected behavior

Its valid case that combination might not exist in some shop, but we still need to get combination info, so instead of error we should fallback to any another combination that is associated to shop.

### Steps to reproduce

1. Have multishop enabled and at least 2 shops.
2. Go to product v2 combination tab
3. Generate any different combinations in those 2 shops (its important that combinations between shops differs, else doesn't matter)
4. try to update any product field, lets say "label when in stock" with some random valid value
5. Save & see error `An unexpected error occurred. [PrestaShop\PrestaShop\Core\Domain\Product\Combination\Exception\CombinationShopAssociationNotFoundException code 0]: Could not find association between Combination {someId} and Shop {some shop id}`

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | refer to #31170 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | refer to #31170 
| Fixed ticket?     | #31170 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

File: src/Adapter/Product/Repository/ProductSupplierRepository.php [hunk 1]
```diff
@@ -111,7 +111,7 @@ public function get(ProductSupplierId $productSupplierId): ProductSupplier
      *
      * @throws InvalidProductSupplierAssociationException
      */
-    public function getIdByAssociation(SupplierAssociationInterface $association): ?ProductSupplierId
+    public function findIdByAssociation(SupplierAssociationInterface $association): ?ProductSupplierId
```
Comment (zuk3975) [inline src/Adapter/Product/Repository/ProductSupplierRepository.php:114]: not necessary change, but I think its better to use find instead of get when method can return null

**Comment by zuk3975** [comment]
I prefer to wait for this PR to be merged https://github.com/PrestaShop/PrestaShop/pull/30985
then I can add some behat tests I think, so lets wait for it before adding for QA.

**EDIT** Added test. Ready for review :heavy_check_mark:

File: src/Adapter/Product/Repository/ProductSupplierRepository.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductSupplierRepository.php:114]: Ok why not

File: tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_suppliers.feature [hunk 2]
```diff
@@ -684,3 +684,48 @@ Feature: Update product combination suppliers in Back Office (BO)
     Then product product7 should not exist anymore
     And supplier "supplier4" should have 0 products associated
     And supplier "supplier5" should have 0 products associated
+
+  Scenario: Product suppliers can be updated when some combinations doesn't exist in default shop
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_suppliers.feature]: This should be into a feature dedicated to multishop, I prefer we keep a clean separation of multishop features, so that the background that creates/enables shops is unique and always at the top of the file And to make sure we clean the data correctly The `@restore-shops-after-feature` is not in this file, so it will likely impact the other tests sooner or later

So this should be moved into the shop features, and since we don't have features for suppliers in multishop yet you'll likely have to add one in `tests/Integration/Behaviour/Features/Scenario/Product/Combination/Shop/update_multishop_combination_suppliers.feature`

**Review by jolelievre — COMMENTED** [review]
OK for me except the behat tests should be moved in another feature file with appropriate shop cleaning tags

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Review by jolelievre — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @zuk3975 ,

I have checked your PR and the issue is well fixed.
The automated tests are OK ! 

So it's QA approved :heavy_check_mark: 

Thank you!
