### PR TITLE
Do not check for multiple image formats feature, add fallback

### LINKED ISSUE #32897: Deleting product image doesn't work via API/webservice
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

As title says, image isn't deleted.
Error says
```
Fatal error: Uncaught Error: Call to a member function get() on null in /var/www/html/classes/Image.php:640
Stack trace:
#0 /var/www/html/classes/Image.php(210): ImageCore->deleteImage()
#1 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(822): ImageCore->delete()
#2 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(625): WebserviceSpecificManagementImagesCore->manageDeclinatedImagesCRUD(true, '/var/www/html/i...', Array, '/var/www/html/i...')
#3 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(650): WebserviceSpecificManagementImagesCore->manageEntityDeclinatedImages('/var/www/html/i...', Array)
#4 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(656): WebserviceSpecificManagementImagesCore->manageDeclinatedImages('/var/www/html/i...')
#5 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(315): WebserviceSpecificManagementImagesCore->manageProductImages()
#6 /var/www/html/classes/webservice/WebserviceSpecificManagementImages.php(184): WebserviceSpecificManagementImagesCore->manageImages()
#7 /var/www/html/classes/webservice/WebserviceRequest.php(619): WebserviceSpecificManagementImagesCore->manage()
#8 /var/www/html/webservice/dispatcher.php(94): WebserviceRequestCore->fetch('8A7LBRETHEZ9PUS...', 'DELETE', 'images/products...', Array, false, NULL)
#9 {main}
  thrown in /var/www/html/classes/Image.php on line 640
```

https://github.com/PrestaShop/PrestaShop/assets/23308427/8dacd8c2-d869-4f7f-aabc-dcdf3c10916a

### Expected behavior

Image is deleted.

### Steps to reproduce

1. Generate API key
2. Obtain product image ID 
3. Call /api/images/products/PRODUCT_ID/IMAGE_ID with DELETE method.

### PrestaShop version(s) where the bug happened

dev/master

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | See below
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6170813634 The images should be visible with and w/o new image formats
| Fixed ticket?     | Fixes #32897
| Related PRs       | 
| Sponsor company   |

### Description of changes
- I unified the place where image formats are retrieved to getGenerationFormats method.
- No need to have duplicate conditions for this, because it will behave the same.
- It was producing an extra query for a feature flag each time an image was processed, now it's only one query and formats are saved in cache and processed only once.
- If the feature flag is disabled or the config is corrupted/not present, JPG is always provided.
- When prepraing the formats, it checks if the configuration value is between SUPPORTED_FORMATS.
- It also fixes unavailable container in webservice context, because it uses a legacy class to fetch the status of the feature flag.

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
I understand your idea, but this is different from how you work with feature flags.

Feature flags aim to use the code behind them only if enabled. Right now, you're using the code that is supposed to always work behind the feature flag.

Also, I'm afraid that if you set formats to JPG, WebP, and Avif and turn off the feature flag, you will still produce the same output as the feature flag was enabled.

**Comment by Hlavtox** [comment]
@kpodemski @matks Guys, can we merge it like this and remove the feature flag check for v9?

**Comment by matks** [comment]
> I understand your idea, but this is different from how you work with feature flags.

I don't understand the idea 😄 why this change in 8.1.x branch? It's not a bugfix, it has nothing to do with patch version 8.1.2

**Comment by Hlavtox** [comment]
@matks It is a bugfix, it fixes https://github.com/PrestaShop/PrestaShop/issues/32897 and fixes duplicate queries on each image that gets presented on front office.

**Review by kpodemski — DISMISSED** [review]

File: src/Core/Image/ImageFormatConfiguration.php [hunk 1]
```diff
@@ -51,7 +57,30 @@ public function __construct(ConfigurationInterface $configuration)
 
     public function getGenerationFormats(): array
     {
-        return explode(self::SEPARATOR, $this->configuration->get(self::IMAGE_FORMAT_CONFIGURATION_KEY));
+        // Return formats from cache
+        if (!empty(self::$formatsToGenerate)) {
```
Comment (jolelievre) [inline src/Core/Image/ImageFormatConfiguration.php]: Can you please not use static cache, except very specific use cases they are usually a bad practice as they are a pain in the ass to clear and mess with test environments
Since this class is a service using a field cache should have the same behaviour as only one instance of the service will be instanciated in the request process

File: src/Core/Image/ImageFormatConfiguration.php [hunk 2]
```diff
@@ -83,4 +112,12 @@ public function isGenerationFormatSet(string $format): bool
     {
         return in_array($format, $this->getGenerationFormats());
     }
+
+    /**
+     * reset static cache (eg unit testing purpose).
+     */
+    public static function resetStaticCache()
```
Comment (jolelievre) [inline src/Core/Image/ImageFormatConfiguration.php]: Ah you probably already noticed this cache issue in the tests 😅
I'm not sure it will do exactly what you intend to but it seems to me a regular class field would have the same effect for your optimization without the drawbacks of static cache and this method would not be needed any more

**Review by jolelievre — DISMISSED** [review]
Thanks @Hlavtox

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
@MatShir @PrestaShop/qa-functional 

let's try to put it to 8.1.2 :) test is straightforward, images should be visible with and w/o new image formats

**Comment by MatShir** [comment]
Let's go ! I have edited the how to test with your comment. Don't hesitate to add more info :)

**Comment by MatShir** [comment]
https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6170813634 🔴

**Comment by Hlavtox** [comment]
@MatShir Restarting, probably random fails

**Comment by MatShir** [comment]
https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6170813634 🟢
 🥳 
 @AureRita go go ;)

**Review by boherm — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@boherm @kpodemski @jolelievre Can you reapprove guys? I also fixed the remaining things and webservice. No BC break, no behavior change.

**Review by kpodemski — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Here's the result :

https://github.com/PrestaShop/PrestaShop/assets/16019289/3cf5ad2d-320a-4f64-b8b2-5ba894be416f

The image is well deleted, but the error message is not correct. I have the same behavior without PR too.

Here's what I have :
`Fatal error: Uncaught Error: Call to a member function get() on null in
/Users/fHea/Desktop/pr-ps810/classes/Image.php:949
Stack trace:
#0 /Users/fHea/Desktop/pr-ps810/classes/Image.php(648): ImageCore->deleteAutoGeneratedImage(Array, 'jpg', Array)
#1 /Users/fHea/Desktop/pr-ps810/classes/Image.php(210): ImageCore->deleteImage()
#2 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceSpecificManagementImages.php(822): ImageCore->delete()
#3 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceSpecificManagementImages.php(625):
WebserviceSpecificManagementImagesCore->manageDeclinatedImagesCRUD(true, '/Users/fHea/Des...', Array,
'/Users/fHea/Des...')
#4 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceSpecificManagementImages.php(650):
WebserviceSpecificManagementImagesCore->manageEntityDeclinatedImages('/Users/fHea/Des...', Array)
#5 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceSpecificManagementImages.php(656):
WebserviceSpecificManagementImagesCore->manageDeclinatedImages('/Users/fHea/Des...')
#6 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceSpecificManagementImages.php(315):
WebserviceSpecificManagementImagesCore->manageProductImages()
#7 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceSpecificManagementImages.php(184):
WebserviceSpecificManagementImagesCore->manageImages()
#8 /Users/fHea/Desktop/pr-ps810/classes/webservice/WebserviceRequest.php(622):
WebserviceSpecificManagementImagesCore->manage()
#9 /Users/fHea/Desktop/pr-ps810/webservice/dispatcher.php(94): WebserviceRequestCore->fetch('WPJJGJQRSN1KDPX...',
'DELETE', 'images/products...', Array, false, NULL)
#10 {main}
thrown in /Users/fHea/Desktop/pr-ps810/classes/Image.php on line 949`

Could you check ? ^^
Thanks!

**Comment by Hlavtox** [comment]
EDIT: No, for some reason.

Context::getContext()->container and only this is a webservice container - it's null everywhere else.
SymfonyContainer::getInstance() is a backoffice container and null everywhere else.

So, easiest way to solve this is just to use a legacy class for getting the config value, it will work everywhere.
_________

**Fixed by changing this.**
`$configuration = SymfonyContainer::getInstance()->get('prestashop.adapter.legacy.configuration');`
to
`$configuration = Context::getContext()->container->get('prestashop.adapter.legacy.configuration');`

**This is the same way it's done in Currency class.**
```
public function setIsoCodeForWebService()
    {
        $container = Context::getContext()->container;
```

**Comment by Hlavtox** [comment]
Can you reapprove guys? @PrestaShop/committers

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
It is fixed indeed !

https://github.com/PrestaShop/PrestaShop/assets/16019289/6303552c-e6f8-4a0a-9200-9c271a56a116

It is QA ✅
