### PR TITLE
Can't export data more than filters limits

### LINKED ISSUE #16328: Customers export from the BO - Wrong 50 limit
Hello,

When you use the "export" button of the customer grid from the Backoffice:
image

The file is limited to 50 entries. It should extract all the Customers.

In the PrestaShopBundle\Controller\Admin\Sell\Customer\CustomerController::exportAction(CustomerFilters $filters)
There is no filter setting. So the default values of the Filter are the following:

    public static function getDefaults()
    {
        return [
            'limit' => 50,
            'offset' => 0,
            'orderBy' => 'date_add',
            'sortOrder' => 'DESC',
            'filters' => [],
        ];
    }

The issue can be handled adding: `$filters->set('limit', null);` at the top of the controller.

Best regards.

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Customers, manufacturers and Categories can't be export over the default limit.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16328 
| How to test?  | Follow ticket instruction, and repeat with Categories, manufacturers and customers.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16742)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php [hunk 1]
```diff
@@ -664,12 +664,11 @@ public function deleteAction(Request $request)
...
      * @DemoRestricted(redirectRoute="admin_categories_index")
      *
-     * @param CategoryFilters $filters
-     *
      * @return Response
      */
-    public function exportAction(CategoryFilters $filters)
+    public function exportAction()
     {
+        $filters = new CategoryFilters(['limit' => null] + CategoryFilters::getDefaults());
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php]: By doing that you ignore all previously set filters in the grid, so the export action will simply return all the categories all the time (regardless of your current filtering) I'd recommend rebuild an object filter based on the provided values:
```php
$filters = new CategoryFilters($filters->all() + ['limit' => null], $filters->getFilterId());
```

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by sarahdib** [comment]
@jolelievre it's ok for you ?

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
@sarahdib yep all good

**Comment by sarahdib** [comment]
@PierreRambaud It's fixed for all except for supplier

**Comment by PierreRambaud** [comment]
@sarahdib The supplier has not been migrated yet :sweat_smile: This is why it's not working yet

**Comment by Progi1984** [comment]
Thanks @PierreRambaud
