### PR TITLE
Fix price formatting in MoneyType

### LINKED ISSUE #28430: BO - Product page V2 & V1 - The alternative currency symbol is not displayed in the product V2 & V1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we create an alternative currency, the symbol of this currency is not displayed on the Product page V2
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > International > Localization > Currencies page
2. Add an alternative currency and enable it
image
3. Go to BO > International > Localization page
4. Se the new currency created as a default currency and save 
image
5. Go to BO > Catalog > Products > Edit a product V2
6. In the pricing tab > the currency symbol is empty
6.1 Retail price (tax excl.) & (tax incl.)
6.2 Retail price per unit (tax excl.) & (tax incl.)
6.3 Cost price (tax excl.)
6.4 When adding a specific price: `Set specific price (tax excl.)` filed & `Reduction amount` field
6.5 Combinations tab > `Cost price (tax excl.)` & `Impact on price (tax excl.)` & `Impact on price (tax incl.)` & `Impact on price per unit (tax excl.)` & the `Cost price (tax excl.)` of a supplier
6.6 In the Options tab: the  `Cost price (tax excl.)` of a supplier

image

I tried with PS1785 & PS1778 => Same issue

image

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

1778, 1785, 8.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | refer to #28430. Symfony MoneyType form never considered prestashop Locale configurations. This Pr fixes it through adjusting CustomMoneyType form extension
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | #28430
| Related PRs       | 
| How to test?      | refer to #28430
| Possible impacts? | All inputs where Money type was used will be affected

Screenshot from 2022-08-17 14-58-08
Screenshot from 2022-08-17 14-53-14

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 1]
```diff
@@ -26,14 +26,43 @@
...
 use Symfony\Component\Form\Extension\Core\Type\MoneyType;
+use Symfony\Component\Form\FormInterface;
+use Symfony\Component\Form\FormView;
 use Symfony\Component\OptionsResolver\OptionsResolver;
 
 class CustomMoneyType extends AbstractTypeExtension
 {
     public const PRESTASHOP_DECIMALS = 6;
 
+    protected const PATTERN_MAP = [
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php]: for this I would like to somehow reuse PatternTransformer class :thinking:
Maybe it would require to expose some additional constants which has the patterns defined, then i can assign symfony money patterns to them :thinking:

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 2]
```diff
@@ -55,4 +84,31 @@ public function configureOptions(OptionsResolver $resolver)
 
         $resolver->setAllowedTypes('scale', 'int');
     }
+
+    /**
+     * {@inheritDoc}
+     */
+    public function buildView(FormView $view, FormInterface $form, array $options)
+    {
+        parent::buildView($view, $form, $options);
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:103]: trust symfony to collect and build the pattern with correct currency symbol.

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 3]
```diff
@@ -55,4 +84,31 @@ public function configureOptions(OptionsResolver $resolver)
...
+
+        if (!empty($matches[1])) {
+            $symbol = trim($matches[1]);
+        }
+
+        if (!isset($this::PATTERN_MAP[$pricePattern])) {
+            return;
+        }
+
+        $view->vars['money_pattern'] = str_replace('¤', $symbol ?? $currency, $this::PATTERN_MAP[$pricePattern]);
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php]: reassign money_pattern understandable for symfony component depending on prestashop price specification

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 4]
```diff
@@ -55,4 +84,31 @@ public function configureOptions(OptionsResolver $resolver)
...
+        parent::buildView($view, $form, $options);
+        $currency = $options['currency'];
+        $moneyPattern = $view->vars['money_pattern'];
+
+        $priceSpecification = $this->locale->getPriceSpecification($currency);
+        $value = new DecimalNumber((string) (float) $view->vars['value']);
+        $pricePattern = $value->isPositive() ? $priceSpecification->getPositivePattern() : $priceSpecification->getNegativePattern();
+
+        // inspired by symfony MoneyType
+        preg_match('/^([^\s\xc2\xa0]*)[\s\xc2\xa0]*{{ widget }}(?:[,.]0+)?[\s\xc2\xa0]*([^\s\xc2\xa0]*)$/u', $moneyPattern, $matches);
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php]: find currency symbol in string (find all except `{{ widget }}` which is the way how symfony MoneyType formats it). preg_match taken from MoneyType ($matches[1] should contain symbol if it exists)

**Comment by zuk3975** [comment]
@PrestaShop/committers feedback appreciated. Not sure its the best way, couldn't find better one :thinking: Btw should somehow be improvable by using pattern transformer constants :thinking:

**Comment by zuk3975** [comment]
Improved a little to reuse PatternTransformer as much as possible. Seems to work well.

File: src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php [hunk 5]
```diff
@@ -68,19 +68,27 @@ abstract class AbstractCurrencyHandler extends AbstractObjectModelHandler
...
 
+    /**
+     * @var PatternTransformer
+     */
+    protected $patternTransformer;
+
     /**
      * @param LocaleRepository $localeRepoCLDR
-     * @param LanguageInterface[] $languages
+     * @param array $languages
```
Comment (jolelievre) [inline src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php]:
```suggestion
     * @param LanguageInterface[] $languages
```

The initial PHPDoc is more accurate and matches the class field

File: src/Core/Localization/Currency/PatternTransformer.php [hunk 6]
```diff
@@ -88,6 +105,55 @@ public function transform(string $currencyPattern, string $transformationType):
...
+        ];
+
+        if (empty($positivePatternMap[$patternType])) {
+            return null;
+        }
+
+        return str_replace(
+            self::CURRENCY_SYMBOL,
+            $priceSpecification->getCurrencySymbol(),
+            $isPatternPositive ? $positivePatternMap[$patternType] : sprintf('-%s', $positivePatternMap[$patternType])
```
Comment (jolelievre) [inline src/Core/Localization/Currency/PatternTransformer.php]: If we really want to use the whole CLDR feature I'm not sure we should construct the negative form this way. In most western languages this is how it would be built (although some would have a space) but it's not the case for all languages (including RTL languages) so iI'm not sure we should use this but instead `getNegativePattern()`

And actually I'm thinking even the way you build the pattern may already be breaking the format for some languages. Ideally we should use the returned pattern from the specification and replace the part that we need with `{{ widget }}`

I think you can simply replace `#,##0.00` because it's the common pattern used in every language for the CLDR norm and parser. Maybe it will make this a bit harder to unit test, but it's not that much a problem because it would be more valuable to test this in integration tests, this way it's really based on the CLDR fixtures (if you can keep the unit tests though it's still a good thing).

**Review by jolelievre — COMMENTED** [review]
Thanks @zuk3975,

That's a very interesting new feature, I just thought of an alternative way to build the pattern which should be compatible with more use cases.

File: src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php (hunk 5 above)
Comment (zuk3975) [reply src/Adapter/Currency/CommandHandler/AbstractCurrencyHandler.php]: Idk how I changed it, probably some automatic stuff in phpstorm when i added argument

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 7]
```diff
@@ -55,4 +76,53 @@ public function configureOptions(OptionsResolver $resolver)
...
+     */
+    public function buildView(FormView $view, FormInterface $form, array $options)
+    {
+        parent::buildView($view, $form, $options);
+
+        $frameworkPattern = $this->getFrameworkPattern($options['currency']);
+
+        if (!$frameworkPattern) {
+            return;
+        }
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php]: Not sure this is needed since the method always returns a string

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975 

Just a suggestion but not blocking.

**Review by matks — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Comment by AureRita** [comment]
Hi @zuk3975 

Thank you for your PR, I tested it and it correct many things that are reported, as we can see here :

[Untitled_ Oct 31, 2022 5_36 PM.webm](https://user-images.githubusercontent.com/100699445/199062113-91ed7bd0-6035-483b-b8e2-18e1a2a9e5a7.webm)

but, strangely, the currency symbol is not well displayed in product v1 > In the Options tab: the Cost price (tax excl.) of a supplier, as you can see : 
 
[Untitled_ Oct 31, 2022 5_39 PM.webm](https://user-images.githubusercontent.com/100699445/199062694-19727b9d-7d32-426b-afba-9df4887c6899.webm)

It let the previous symbol (Euro - €) 

Waiting for your correction, thanks

**Comment by zuk3975** [comment]
Also found another issue. Eur currency was hardcoded as default iso in the CustomMoneyType, so if you have no EUR currency added into back office you would have got error `unable to find price specification for "eur"`. Fixed so default configuration is taken from the database PS_CURRENCY_DEFAULT instead. 
As old product page uses default currency in suppliers list, it is now also fixed there.

**Review by kpodemski — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 8]
```diff
@@ -44,15 +74,60 @@ public static function getExtendedTypes(): iterable
      */
     public function configureOptions(OptionsResolver $resolver)
     {
+        $defaultCurrencyIso = Currency::getIsoCodeById($this->defaultCurrencyId);
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php]: It is weird to inject an id and fetch with a legacy method IMO.

Maybe put this logic into a separate service that will provide the legacyIsoCode if not set into form options.

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

File: src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php [hunk 9]
```diff
@@ -44,15 +74,60 @@ public static function getExtendedTypes(): iterable
...
+     * Provides currency pattern understandable to symfony, but uses prestashop Locale.
+     *
+     * @param string $currencyCode e.g. EUR, USD
+     *
+     * @return string
+     *
+     * @throws InvalidArgumentException
+     * @throws LocalizationException
+     */
+    private function getFrameworkPattern(string $currencyCode): string
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:118]: can this logic be in a separate tested service ?

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:118]: Actually, the first implementation was separated, but it ended up being quite overkill since it was not useful anywhere but here However it complexified some existing interfaces and services for no additional value and induced some breaking change

At least the change here is located to the form type only (which is the only place where it's needed) and it's still unit tested, only it's the form type that is tested directly which is acceptable IMHO

Comment (FabienPapet) [reply src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:118]: I agree that we can keep it as it is, but we need to get rid of the legacy classes (Locale, Price) on the new code.

**Review by jolelievre — DISMISSED** [review]

File: src/Adapter/Currency/QueryHandler/GetCurrencyForEditingHandler.php [hunk 10]
```diff
@@ -45,12 +45,20 @@ final class GetCurrencyForEditingHandler implements GetCurrencyForEditingHandler
...
+     */
+    private $patternTransformer;
+
     /**
      * @param int $contextShopId
      */
-    public function __construct($contextShopId)
-    {
+    public function __construct(
+        $contextShopId,
```
Comment (FabienPapet) [inline src/Adapter/Currency/QueryHandler/GetCurrencyForEditingHandler.php]:
```suggestion
        int $contextShopId,
```

File: src/Adapter/Currency/Repository/CurrencyRepository.php [hunk 11]
```diff
@@ -69,4 +70,31 @@ public function get(CurrencyId $currencyId): Currency
...
+                $e
+            );
+        }
+
+        if (empty($isoCode)) {
+            return null;
+        }
+
+        return $isoCode;
+    }
```
Comment (FabienPapet) [inline src/Adapter/Currency/Repository/CurrencyRepository.php]:
```suggestion
    public function findIsoCode(CurrencyId $currencyId): ?string
    {
        try {
            $currency = $this->get($currencyId);
            return $currency->iso_code;
        } catch (CurrencyNotFoundException $notFoundException) {
            return null;
        }
    }
```

**Review by FabienPapet — DISMISSED** [review]

File: src/Adapter/Currency/Repository/CurrencyRepository.php [hunk 12]
```diff
@@ -69,4 +69,14 @@ public function get(CurrencyId $currencyId): Currency
...
     }
+
+    /**
+     * @param CurrencyId $currencyId
+     *
+     * @return string
+     */
+    public function getIsoCode(CurrencyId $currencyId): string
+    {
+        return $this->get($currencyId)->iso_code;
```
Comment (jolelievre) [inline src/Adapter/Currency/Repository/CurrencyRepository.php:80]: If it's just to get the iso code, maybe a custom query via doctrine connection would be more efficient than fetching a whole ObjectModel?

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975 

Just an optimization suggestion, but except that all good to me.

**Review by kpodemski — APPROVED** [review]
Well done @zuk3975

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @zuk3975 

I have checked your PR, but I found this issue : 

-The new currency symbol is not correct in the supplier section when editing a product with combinations with a demo product (It's always displayed as the old one)


1. Go to BO > International > Localization > Currencies page
2. Add an alternative currency and enable it
3. Go to BO > International > Localization page
4. Se the new currency created as a default currency and save
5. Go to BO > Catalog > Products > Edit a product demo with combinations with V2
6. In combinations tab > edit any combination 
7. See the Supplier section > The symbol is not correct!

image
image


https://user-images.githubusercontent.com/92912932/212348270-b9a0bf2d-df29-440c-9a33-b940be2fc26e.mp4



Could you please check it?

Thank You!

**Comment by jolelievre** [comment]
Hi @HanaRebaiQA 

actually, this is the expected behaviour, the specific price has a custom currency that you can edit, so the associated price input uses the same currency (and symbol) as the one specified for that supplier, it doesn't rely on the global default one so all the forms in your video follow the expected behaviour. If there's nothing else that was detected I guess this validates this PR and we can merge it.

**Comment by HanaRebaiQA** [comment]
Hello @jolelievre 

Thanks for your feedback. 
ping @MatShir What do you think?

**Comment by MatShir** [comment]
Nice catch but as @jolelievre we can move forward on this PR :)
Is QA done then ? @HanaRebaiQA

**Review by HanaRebaiQA — APPROVED** [review]
Hello @MatShir 

As discussed, it's QA :heavy_check_mark: 

Thank You!

**Comment by kpodemski** [comment]
Thanks @zuk3975
