### PR TITLE
Fix experimental product page creation link

### LINKED ISSUE #24068: Wrong button name for Experimental Product page button on Standard Add page
#### Describe the bug

When on the "Add a product" page (standard), the button redirecting to the experimental product page wording is "Edit on experimental page". It should be "New product on experimental page" (Admin.Catalog.Feature)
#### Expected behavior

Hi, this suggestion looks good to me. However, we have to make sure this will apply only if creating a new product.

This should not modify the edit buttons in the listing and on an existing product page (V1) that should remain 'Edit on experimental page'.
@Julievrz 

#### Steps to Reproduce

1. Go to Advanced Parameters > Experimental Features
2. Enable the "Experimental product page"
3. Go to Catalog > Products > Click on "+ New product"
4. See button on bottom right : "Edit on experimental page"

**Screenshots**

edit experimal page

#### Additional information

* PrestaShop version: develop (1.7.8)
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | On product creation page V1, the link toward v2 product page was a link toward edition mode instead of creation.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24068
| How to test?      | See steps described in the issue, but also test that the link is good (it should be "create" in the URL, and not "edit"...
| Possible impacts? | it's ok

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24892)

### CODE REVIEW

**Review by matks — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 1]
```diff
@@ -665,6 +665,7 @@ public function formAction($id, Request $request)
             'drawerModules' => $drawerModules,
             'layoutTitle' => $this->trans('Product', 'Admin.Global'),
             'isProductPageV2Enabled' => ($this->isProductPageV2Enabled()),
+            'isCreationMode' => (int) $product->state === Product::STATE_TEMP,
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php:668]:
```suggestion
            'isCreationMode' => $product->state === Product::STATE_TEMP,
```

I see no reason to use int when having `isSomething` as name

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig [hunk 2]
```diff
@@ -106,7 +106,15 @@
       >
         {{ 'Add new product'|trans({}, 'Admin.Catalog.Feature')|raw }}
       </button>
-      {% if isProductPageV2Enabled == true %}
+      {% if isProductPageV2Enabled == true and isCreationMode is same as(true) %}
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig:109]:
```suggestion
      {% if isProductPageV2Enabled == true and isCreationMode == true %}
```

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig [hunk 3]
```diff
@@ -106,7 +106,15 @@
...
+        <a
+          class="btn btn-outline-primary ml-3"
+          href="{{ path('admin_products_v2_create') }}"
+        >
+          {{ 'New product on experimental page'|trans({}, 'Admin.Catalog.Feature')|raw }}
+        </a>
+      {% endif %}
+      {% if isProductPageV2Enabled == true and isCreationMode is same as(false) %}
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig:117]:
```suggestion
      {% if isProductPageV2Enabled == true and isCreationMode == true %}
```

Comment (Progi1984) [reply src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig:117]: @PierreRambaud Shouldn't be `== false` ?

**Review by Progi1984 — COMMENTED** [review]
Agree with @PierreRambaud

**Review by Julievrz — APPROVED** [review]
Wording ✔️ Thank you

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 1 above)
Comment (matthieu-rolland) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:668]: I was afraid this condition might fail if `$product->state` happened to be a string `'0'` , while `Product::STATE_TEMP` is an integer `0` 

In the end the value of `isCreationMode` is a boolean 🤔

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig (hunk 2 above)
Comment (matthieu-rolland) [reply src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig:109]: Isn't it better to enforce strict equality? (`===`)

That's what `is same as` does in Twig syntax

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 1 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:668]: oh my bad, I miss read because of parenthesis :sweat_smile: 
I read `(int) ($product->state === Product::STATE_TEMP)`

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig (hunk 2 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Blocks/footer.html.twig:109]: You're right, it's quite better to use `is same as` I was thinking `==` is enough but no :sweat: 
But, keep in mind, when using `is same as`, null value will not return false :)

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

I have an issue following these steps:

1. Go to Advanced Parameters > Experimental Features
2. Enable the "Experimental product page"
3. Go to Catalog > Products > Click on "+ New product" => check the ID of the product that will be created 
image
5. Click "New product on experimental page"
6. Set required fields
7. Save
8. The page is reloaded => Check the ID in the URL => 
image

This is normal behavior or a bug? 

Thanks!

**Comment by matks** [comment]
Hello @khouloudbelguith this is unfortunately expected

The current product page does a nasty trick when you open "create a new product": it already creates it BEFORE you submit the form. This is why you have the ID 42 already used. This is the issue mentioned in https://github.com/PrestaShop/PrestaShop/issues/9945

So it is not related to this PR

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland, @matks,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1QgQWNq3cPO-NXsImSFqxh1sUnk7yBlev/view?usp=sharing

Thank you!

**Comment by matks** [comment]
Thank you @khouloudbelguith and @matthieu-rolland
