### PR TITLE
Correctly display percentage in cart

### LINKED ISSUE #9892: [BOOM-3843] Probleme affichage remise dans panier
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3843).

- _**Reporter:**_ c-yammine@nepenthes.net
- _**Created at:**_ Thu, 14 Sep 2017 18:09:36 +0200

<p>Il y a un bug dans l'affichage de la remise dans le PANIER lorsque cette remise est paramétrée dans les REGLES DE PRIX CATALOGUE.</p>

<p>Dans mon cas, le produit est paramétré pour une remise unitaire de 18%, et pour plus de 48 unités, la remise passe à 25%.</p>

<p>Comme vous pouvez le voir sur la capture, la remise pour 60 unités reste à 18% dans le PANIER, pourtant l'affichage de la remise à 25% se fait bien dans la fiche produit. le bug d'affichage se fait au niveau du PANIER.<br/>
Merci de me tenir au courant.</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update Product::getProductProperties so that the cart displays the appropriate discount
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9892
| How to test?  | Set different rules of price on a product depending on the quantity Add it to your cart In the cart view when updating the quantity the price AND the discount percentage are updated

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11656)

### CODE REVIEW

File: classes/Product.php [hunk 1]
```diff
@@ -4742,6 +4742,8 @@ public static function getProductProperties($id_lang, $row, Context $context = n
         if (isset($row['quantity_wanted'])) {
             // 'quantity_wanted' may very well be zero even if set
             $quantity = max((int) $row['minimal_quantity'], (int) $row['quantity_wanted']);
+        } elseif (isset($row['cart_quantity'])) {
+            $quantity = max((int) $row['minimal_quantity'], (int) $row['cart_quantity']);
         } else {
             $quantity = (int) $row['minimal_quantity'];
```
Comment (PierreRambaud) [inline classes/Product.php:4748]: Could it be simpler to have
```
$quantity = max(
  (int) $row['minimal_quantity'],
  isset($row['quantity_wanted']) ? (int) $row['quantity_wanted'] : 0,
  isset($row['cart_quantity']) ? (int) $row['cart_quantity'] : 0,
);
```

Comment (PierreRambaud) [reply classes/Product.php:4748]: Or is there an importance about order. quantity_wanted before cart_quantity ?

Comment (jolelievre) [reply classes/Product.php:4748]: I'm actually not sure, since `cart_quantity` was not managed I think leaving `quantity_approved` the priority reduces the risk of side effects bug
Although I don't think they are used in the same use cases it is safer

**Review by PierreRambaud — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @jolelievre
