### PR TITLE
Attribute group list is sorted by position

### LINKED ISSUE #36012: related #35591 - bug 10 : Attribute group list is not by default sorted by position
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Regression on the migrated Attributes pages

see #35591 B10

For some reason, when I open a list of attribute values, it automatically opens "rearrange" mode. It doesn't happen in attribute list.
Need to adapt the attribut group list

### Expected behavior

_No response_

### Steps to reproduce

Go to Attributes lists

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mattgoud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  related #35591 - fix bug 10 : Attribute group list is not by default sorted by position
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/8878375809
| Fixed issue or discussion?     | Fixes #36012
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by paulnoelcholot — DISMISSED** [review]

**Comment by paulnoelcholot** [comment]
Hello @mattgoud,

I tested your PR and it's good! :tada: 

Thanks !

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Just to confirm - what does this fix?

Bug 10 in the issue is `"For some reason, when I open a list of attribute values, it automatically opens "rearrange" mode. It doesn't happen in attribute list."`

This PR is called `Attribute group list is sorted by position`

And in the code it changes desc to asc?

Maybe it does what it should do, but having no PR description and no screenshots of QA is very confusing.

**Comment by paulnoelcholot** [comment]
Hello @mattgoud,

I tested your PR and I found a problem. The list is still in rearrange mode :

image

File: src/Core/Search/Filters/AttributeGroupFilters.php [hunk 1]
```diff
@@ -37,6 +37,8 @@ final class AttributeGroupFilters extends Filters
     /** @var string */
     protected $filterId = AttributeGroupGridDefinitionFactory::GRID_ID;
 
+    protected $needsToBePersisted = false;
```
Comment (jolelievre) [inline src/Core/Search/Filters/AttributeGroupFilters.php]: There is no reason not to persist this filter, you are simply ignoring the "bug" by adding this Which is not a bug this is the same behavior we have in the hole BO

File: src/Core/Search/Filters/AttributeGroupFilters.php [hunk 2]
```diff
@@ -46,7 +48,7 @@ public static function getDefaults()
             'limit' => 50,
             'offset' => 0,
             'orderBy' => 'position',
```
Comment (jolelievre) [inline src/Core/Search/Filters/AttributeGroupFilters.php:48]: Regarding the "bug" mentioned that the rearrange mode is enabled by default on first access, it is simply because the default column used here is position It should be `id`

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/Core/Search/Filters/AttributeGroupFilters.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Search/Filters/AttributeGroupFilters.php:48]: Unless it's ordered by position on purpose to have a preview of the order in FO, but that's up to @PrestaShop/product-council to tell us that

Comment (Hlavtox) [reply src/Core/Search/Filters/AttributeGroupFilters.php:48]: @jolelievre The default order should be just ID, like everywhere else.

File: src/Core/Search/Filters/AttributeGroupFilters.php (hunk 1 above)
Comment (mattgoud) [reply src/Core/Search/Filters/AttributeGroupFilters.php]: ok @jolelievre, this filter is persisted

File: src/Core/Search/Filters/AttributeGroupFilters.php (hunk 2 above)
Comment (mattgoud) [reply src/Core/Search/Filters/AttributeGroupFilters.php:48]: @Hlavtox @jolelievre, ok done (default order is setting by ID asc)

**Review by Hlavtox — APPROVED** [review]

File: src/Core/Search/Filters/AttributeGroupFilters.php [hunk 3]
```diff
@@ -45,8 +45,8 @@ public static function getDefaults()
         return [
             'limit' => 50,
             'offset' => 0,
-            'orderBy' => 'position',
-            'sortOrder' => 'desc',
+            'orderBy' => 'id',
```
Comment (jolelievre) [inline src/Core/Search/Filters/AttributeGroupFilters.php]: Sorry @mattgoud after discussion with product team (and @paulnoelcholot) it as decided to keep the order by position, but we still need to update this to have the `asc` order by default

The confusion `Done` button will likely be removed in another PR (that will impact all pages relying on this position component)

**Review by Hlavtox — DISMISSED** [review]
Blocking because of default order

@MatShir @kpodemski Why sort the attributes by position as default?

- First, where was this discussed in the council? Nothing on Slack, is there some other channel?
- This is against consistency with other backoffice pages. Other pages are using ID as default.
- As a merchant, I don't care what is the order in FO when I want to manage attributes. When you go to Attribute pages and you want to change something on an attribute or add a value, you will IF SOMETHING look for it by it's name. So if you want to go against the standard, attribute would be something to choose.

File: src/Core/Search/Filters/AttributeGroupFilters.php (hunk 3 above)
Comment (mattgoud) [reply src/Core/Search/Filters/AttributeGroupFilters.php]: @jolelievre  I removed the rearrange/done button for the attributes/attributes groups pages + put back the filter by position as seen with Amine

File: src/Core/Search/Filters/AttributeGroupFilters.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Search/Filters/AttributeGroupFilters.php:48]: @Hlavtox not all grid handle repositioning, so in regular grids without position it makes sense that the default order is by ID However in entities that can be positioned I think it's better to use the position by default, it reflects right away the state and order of things in the FO
Besides even in legacy page the attributes were already order by position, so I don't understand why you're so fixated on this topic

**Comment by mattgoud** [comment]
> Blocking because of default order
> 
> @MatShir @kpodemski Why sort the attributes by position as default?
> 
> * First, where was this discussed in the council? Nothing on Slack, is there some other channel?
> * This is against consistency with other backoffice pages. Other pages are using ID as default.
> * As a merchant, I don't care what is the order in FO when I want to manage attributes. When you go to Attribute pages and you want to change something on an attribute or add a value, you will IF SOMETHING look for it by it's name. So if you want to go against the standard, attribute would be something to choose.

Hello @Hlavtox, finally after discussion with the PM it was agreed to sort by position + remove the Done button

File: src/Core/Search/Filters/AttributeGroupFilters.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Search/Filters/AttributeGroupFilters.php:48]: @mattgoud you shouldn't remove this button in the Grid definitions, it will remove both the Done and Rearange button, we only want to remove the Done button

It seems like this is handled by JS here https://github.com/PrestaShop/PrestaShop/blob/4125e4795ff6acfe01bd8c38460941ab6eb349bc/admin-dev/themes/new-theme/js/components/grid/extension/position-extension.ts#L294 For now the extension switched the label of the button, but the idea would be to hide the button when `this.isPositionsReorderActive()` is true

Comment (mattgoud) [reply src/Core/Search/Filters/AttributeGroupFilters.php:48]: > @mattgoud you shouldn't remove this button in the Grid definitions, it will remove both the Done and Rearange button, we only want to remove the Done button
> 
> It seems like this is handled by JS here
> 
> https://github.com/PrestaShop/PrestaShop/blob/4125e4795ff6acfe01bd8c38460941ab6eb349bc/admin-dev/themes/new-theme/js/components/grid/extension/position-extension.ts#L294
> 
> For now the extension switched the label of the button, but the idea would be to hide the button when `this.isPositionsReorderActive()` is true

ok @jolelievre done

File: src/Core/Grid/Definition/Factory/AttributeGroupGridDefinitionFactory.php [hunk 4]
```diff
@@ -200,7 +200,7 @@ protected function getFilters()
             )
             ->add((new Filter('position', ReorderPositionsButtonType::class))
                 ->setAssociatedColumn('position')
-            )
+            )
```
Comment (jolelievre) [inline src/Core/Grid/Definition/Factory/AttributeGroupGridDefinitionFactory.php]: @mattgoud you just need to remove these extra spaces and it should be good
Maybe you can squash your commits also

**Review by jolelievre — DISMISSED** [review]
Thanks @mattgoud

**Review by boherm — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @mattgoud ,

The button "Rearrange" is displayed just a few milli seconds 😅 

https://github.com/PrestaShop/PrestaShop/assets/16019289/ca51463c-e195-4991-bc65-32d8c0af47ea

Could you check ? ^^

**Review by boherm — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
cc @Hlavtox - I dismissed your review following our conversation, not to block this PR since it's the same behavior as on the old page. Let's create an Issue if this change you wanted is something you'd like to discuss further.

**Review by florine2623 — COMMENTED** [review]
Hello @mattgoud ,

I still have some issues with this PR 😭 

https://github.com/PrestaShop/PrestaShop/assets/16019289/2c82041d-dce5-4075-b269-27399e1be6d4

The button Rearrange flashes, I can't click on it.

Could you check please ? :)
Thanks!

**Review by florine2623 — APPROVED** [review]
As checked with @mattgoud ,

All the components are loaded when the page is refreshed, so it is normal that some of the components are displayed before being hidden.

Tested Rearranging from ID and Name, it works as expected. The update will be done automatically without clicking on any other button.
When sorting by Position, you can't Rearrange.

It is QA ✅ 
Thanks!

**Review by jolelievre — APPROVED** [review]
