### PR TITLE
Simplify 'Add a theme' form

### LINKED ISSUE #23344: Error on translation when adding a new theme
This issue is related to the [Refactoring of Translation storage component](https://github.com/PrestaShop/PrestaShop/issues/19242) project

You can read about the project [here](https://github.com/PrestaShop/PrestaShop/issues/19242).

#### Describe the bug

After uploading a new theme and click on save there is an error 

#### Steps to Reproduce

1. Go to Bo -> Theme & logo
2. Click on add a new theme
3. Upload new theme and save

**Screenshots**

Capture d’écran 2021-02-22 à 12 18 15

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Simplifies add a theme forms
| Type?         | refacto
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Part of #16482 and https://github.com/PrestaShop/PrestaShop/issues/23344
| How to test?  |  Theme & Logo > Theme. Everything should work exactly the same

:notebook: **BC Break**
Backwards compatibility break introduced due to extension of TranslationAwareType by ImportThemeType. This means if any module extends any of this type they will get an exception upon upgrading to PS version containing changes in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21243)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php [hunk 1]
```diff
@@ -494,6 +500,20 @@ private function handleImportThemeException(Exception $e)
...
+                ThemeConstraintException::MISSING_CONFIGURATION_FILE => $couldntToUploadTheme . ': ' . $this->trans(
+                        'Missing configuration file', 'Admin.Notifications.Error'
+                    ),
+                ThemeConstraintException::INVALID_CONFIGURATION => $couldntToUploadTheme . ': ' . $this->trans(
+                        'Invalid configuration', 'Admin.Notifications.Error'
+                    ),
+                ThemeConstraintException::INVALID_DATA => $couldntToUploadTheme . ': ' . $this->trans(
+                        'Invalid data', 'Admin.Notifications.Error'
+                    ),
+            ],
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php]: Better to use `sprintf`

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks. Thanks :pray:

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php (hunk 1 above)
Comment (JevgenijVisockij) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php]: Hey removed first part of message in general so sprintf is no longer needed.

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php [hunk 2]
```diff
@@ -494,6 +494,20 @@ private function handleImportThemeException(Exception $e)
                     '%theme_name%' => $e instanceof ImportedThemeAlreadyExistsException ? $e->getThemeName()->getValue() : '',
                 ]
             ),
+            ThemeConstraintException::class => [
+                ThemeConstraintException::RESTRICTED_ONLY_FOR_SINGLE_SHOP => $this->trans(
+                        'Themes can be changed only in single shop context', 'Admin.Notifications.Error'
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php]:
```suggestion
                        'Themes can only be changed in single store context.', 'Admin.Notifications.Error'
```

File: src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/ImportThemeType.php [hunk 3]
```diff
@@ -62,16 +66,31 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                'label' => $this->trans('Zip file', 'Admin.Design.Feature'),
+                'help' => $this->trans(
+                    'Browse your computer files and select the Zip file for your new theme.',
+                    'Admin.Design.Help'
+                ),
                 'required' => false,
                 'constraints' => new File([
                     'mimeTypes' => 'application/zip',
-                    'mimeTypesMessage' => $this->trans('Invalid file format.', [], 'Admin.Design.Notification'),
+                    'mimeTypesMessage' => $this->trans('Invalid file format.', 'Admin.Design.Notification'),
```
Comment (Julievrz) [inline src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/ImportThemeType.php:77]: What are the valid file formats?

Comment (JevgenijVisockij) [reply src/PrestaShopBundle/Form/Admin/Improve/Design/Theme/ImportThemeType.php:77]: I believe it's zip only

File: admin-dev/themes/new-theme/js/components/form/form-error.js [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ /
+
+const {$} = window;
+
```
Comment (JevgenijVisockij) [inline admin-dev/themes/new-theme/js/components/form/form-error.js:27]: There are cases when form error will be thrown at the top of the form and then current design doesn't fit. So I solved it with additional js component, I am not sure if it's the best way. 

I tried pure CSS approach, but it was messy and meant copying parts of UI kit, when all I need is to add already existing classes.

**Review by matks — DISMISSED** [review]
Great work !

**Review by NeOMakinG — DISMISSED** [review]
LGTM 👍

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

I think this PR is blocked by this issue: https://github.com/PrestaShop/PrestaShop/issues/23344
What do you think?

Thanks!

**Review by PierreRambaud — DISMISSED** [review]

**Comment by JevgenijVisockij** [comment]
> Hi @JevgenijVisockij,
> 
> I think this PR is blocked by this issue: #23344
> What do you think?
> 
> Thanks!

Indeeed it was blocked by. I added fix to that issue so this can be reviewed.

File: src/Core/Translation/Finder/TranslationFinder.php [hunk 5]
```diff
@@ -90,7 +90,7 @@ private function removeTrailingLocaleFromDomains(MessageCatalogueInterface $cata
      *
      * @throws FileNotFoundException
      */
-    private function getTranslationFilesFromPath(array $paths, string $pattern): Finder
+    private function getTranslationFilesFromPath(array $paths, ?string $pattern): Finder
     {
```
Comment (JevgenijVisockij) [inline src/Core/Translation/Finder/TranslationFinder.php:94]: Fixes
https://github.com/PrestaShop/PrestaShop/issues/23344

I am assuming it was simply mistake when adding typehints, because  couple lines after this we have
```
     if (null !== $pattern) {
            $finder->name($pattern);
        }

```

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1QBeCBsA-BNA1F4Pn3KVSgU4H89H1SXkt/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @JevgenijVisockij & @khouloudbelguith
