### PR TITLE
Fixed Exception for not defined variables when editing a product quantity in an order

### LINKED ISSUE #17618: Error variable doesn't exist when editing a product quantity for an order
**Describe the bug**
Error when editing a product quantity for an order

**To Reproduce**
1. Go to the migrated order listing
2. View an order in "awaiting payment"
3. Edit the product quantity
4. Click on Save
5. See 500 error in the console

**Screenshots**
capture d'écran_2315

capture d'écran_2314

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixed Exception for not defined variables when editing a product quantity in an order
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17618
| How to test?  | Steps to reproduce the behavior:<br>1. Go to the migrated order listing<br>2. View an order in "awaiting payment"<br>3. Edit the product quantity<br>4. Click on Save<br>5. **Before:** See 500 error in the Synfony console<br>5. **After:** No more error

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17641)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
LGTM 👍 
I restarted the sanity test that failed, if it fails again we'll have to investigate...

(there's also a pretty CI issue)

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Waiting for PrettyCi fixes

**Review by atomiix — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php [hunk 1]
```diff
@@ -35,8 +35,8 @@
 use PrestaShop\PrestaShop\Core\Domain\Order\Command\IssuePartialRefundCommand;
 use PrestaShop\PrestaShop\Core\Domain\Order\Command\IssueReturnProductCommand;
 use PrestaShop\PrestaShop\Core\Domain\Order\Command\IssueStandardRefundCommand;
-use PrestaShop\PrestaShop\Core\Domain\Order\Exception\InvalidOrderStateException;
 use PrestaShop\PrestaShop\Core\Domain\Order\Exception\InvalidCancelProductException;
+use PrestaShop\PrestaShop\Core\Domain\Order\Exception\InvalidOrderStateException;
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderRefundFeatureContext.php]: Already fixed by https://github.com/PrestaShop/PrestaShop/pull/17643 You should rebase

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
Ping @marionf  I tried to reproduce the bug described in [# 17618](https://github.com/PrestaShop/PrestaShop/issues/17618) before applying the pull request but I was not able to do it. 

See here : https://drive.google.com/file/d/1BVbuYv5hlRVnbimMQCbUgKfnW_wp_eOr/view?usp=sharing

Can you verify that the bug is still present for you ?

**Comment by Progi1984** [comment]
@SD1982 You have the error in your video. Check the symfony Console 

image

**Comment by marionf** [comment]
@SD1982 

Sorry I can't try to reproduce the issue #17618 because I have another error before, when I click to view an order

capture d'écran_2348

**Comment by SD1982** [comment]
Sorry my bad !! I did not expect the error to only appear in the debug bar of symfony.
So I was finally able to reproduce the bug and I also confirm that the pull request correctly fix the bug. Thanks @Progi1984

**Comment by matks** [comment]
Thank you @Progi1984
