### PR TITLE
Set numeric_iso_code & precision in currency from CLDR when upgrading

### LINKED ISSUE #22177: Upgrade to 1.7.7.0 stable build from 1.7.5.x and previous versions : Currency precision is set to 6 by default
#### Describe the bug

When making an upgrade from 1.7.5.x and previous version to 1.7.7.0 build stable, the precision of each currency installed is set to 6, leading to unwanted display on FO, and invoices.

#### Expected behavior

After upgrade, the precision of the currency should be the one set by default (2 decimals for example for Euro) instead of 6.

#### Steps to Reproduce

1. Install 1.7.5.x version with Euro installed and autoupgrade module
2. Make an upgrade to 1.7.7.0 stable build
3. Go to International > Localization > Currencies and open Euro parameters : Decimals is set to 6 instead of 2
4. Go to FO > Clothes : Demo Product prices are displayed on 3 digits
5. Make an order with these products, confirm the order and generate invoice in BO : Invoices has 3 digits.

**Screenshots**

Currency Euro in BO : decimals set to 6 after upgrade : 

decimel set to 6 1

Display on FO with 3 digits (with demo product) : 

decimel set to 6 2

Invoice with 3 digits in Euro : 

decimel set to 6 3

#### Additional information

* PrestaShop version: 1770 stable build 5
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | See #22177
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22177
| How to test?  | Upgrade from PS <= 1.7.5 to 1.7.7.0, currencies' precision and numeric_iso_code should be the ones from CLDR

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22178)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php [hunk 1]
```diff
@@ -62,6 +62,17 @@ function ps_1760_copy_data_from_currency_to_currency_lang()
 
 function refreshLocalizedCurrencyData(Currency $currency, array $languages, LocaleRepository $localeRepoCLDR)
 {
+    $cldrLocale = $localeRepoCLDR->getLocale(Context::getContext()->language->locale);
```
Comment (jolelievre) [inline install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php]: I think we should avoir relying on the context in upgrade Since we already have the list of languages and this data isn't related to a specific Language anyway you could use the first one from the array

```suggestion
    $language = new Language($languages[0]['id_lang']);
    $cldrLocale = $localeRepoCLDR->getLocale($language->locale);
```

Comment (eternoendless) [reply install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php]: Nice catch!

**Review by jolelievre — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix ,

After testing an upgrade from 1751 to 1770 with your PR, and some data added (multistore, products, discounts, customers, orders, and two localization pack) : 

The bug seems to be fixed : 

On BO : 



On FO : 



Also tested the upgrade from 1744 and 1765 (on fresh install for these versions) : Display OK too.

QA :heavy_check_mark:
