### PR TITLE
Prevent deleting address being used in the cart

### LINKED ISSUE #20365: Prevent deleting address being used in the cart
#### Describe the bug

Bug when delete address when use in shopping cart

#### Expected behavior

You can delete the address you are using in the basket. What is wrong, after that the client will not be able to place an order

#### Steps to Reproduce

1. Create customer
2. Create address
3. Use in shopping cart
4. Delete address by link site.ru/address?id_address=ID&delete=1&token=TOKEN

#### Additional information

* PrestaShop version: 1.7.4
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by fest73**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | You can delete the address you are using in the basket. What is wrong, after that the client will not be able to place an order
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20365.
| How to test?  | Create customer. Create address. Use in shopping cart. Delete address by link site.ru/address?id_address=ID&delete=1&token=TOKEN

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20366)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: controllers/front/AddressController.php [hunk 1]
```diff
@@ -84,6 +84,20 @@ public function postProcess()
         }
 
         if (Tools::getValue('delete')) {
+            if ($this->context->cart) {
```
Comment (PululuK) [inline controllers/front/AddressController.php]: Check if it is a loaded object is more appropriate I think

File: controllers/front/AddressController.php [hunk 2]
```diff
@@ -84,6 +84,20 @@ public function postProcess()
...
+                if (
+                    $this->context->cart->id_address_invoice == $id_address
+                    || $this->context->cart->id_address_delivery == $id_address
+                ) {
```
Comment (PululuK) [inline controllers/front/AddressController.php]: Use a single `if statement`, something like : 

```php
if ( Validate::isLoadedObject($this->context->cart)  &&  ( 
      $this->context->cart->id_address_invoice == $id_address
      || $this->context->cart->id_address_delivery == $id_address
)) {
       // Return error message here ...
}
```

Comment (fest73) [reply controllers/front/AddressController.php]: ok

Comment (PululuK) [reply controllers/front/AddressController.php]: Thanks @dariusakafest, but you forgot something I think.  
`IF(IS_LOADED_OBJECT && ( IS_INVOICE_ADRESSE || IS_DELIVERY_ADRESSE )){ //Return error message here }`

Comment (fest73) [reply controllers/front/AddressController.php]: ok

**Review by PululuK — DISMISSED** [review]

File: controllers/front/AddressController.php [hunk 3]
```diff
@@ -84,6 +84,20 @@ public function postProcess()
         }
 
         if (Tools::getValue('delete')) {
+            if (
+                Validate::isLoadedObject($this->context->cart)
+                && ($this->context->cart->id_address_invoice == $id_address
+                || $this->context->cart->id_address_delivery == $id_address)
+            ) {
+                $this->errors[] = $this->trans(
+                    'Could not delete address. You use it in the shopping cart',
```
Comment (LouiseBonnard) [inline controllers/front/AddressController.php]:
```suggestion
                    'Could not delete the address since it is used in the shopping cart.',
```

**Review by LouiseBonnard — APPROVED** [review]

**Review by matks — APPROVED** [review]
Nice idea, nice PR 👍

**Review by PululuK — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @dariusakafest :) 

Your PR is QA :heavy_check_mark: , I now have the error when trying to delete an address used in shopping cart.

Thanks !

pr20366

**Comment by matks** [comment]
Thank you @dariusakafest
