### PR TITLE
Remove available_date from presented product if in the past

### LINKED ISSUE #20659: Product availability date is displayed even if it's in the past
#### Describe the bug

Product availability date is useful to tell customers when a given product will be available. But it's displayed even if it's in the past.

#### Expected behavior

If product availability date is in the past, hide it. I will submit a Pull Request.

#### Steps to Reproduce

1. Go to a product page in BO
2. Add a product availability date, select past date
3. Look on FO at product page, click on "details" you see the date, it should be hidden

#### Additional information

* PrestaShop version: develop
* PHP version: php7.2

### PR DESCRIPTION
**Pull request by awitkutarahil**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove available_date from presented product if in the past
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20659
| How to test?  | Check out the issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20660)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
Looks fine to me

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — APPROVED** [review]

File: src/Adapter/Presenter/Product/ProductLazyArray.php [hunk 1]
```diff
@@ -814,8 +814,15 @@ public function addQuantityInformation(
         $this->product['show_availability'] = $show_availability;
         $product['quantity_wanted'] = $this->getQuantityWanted();
 
-        if (isset($product['available_date']) && '0000-00-00' == $product['available_date']) {
-            $product['available_date'] = null;
+        if (isset($product['available_date'])) {
+            if ('0000-00-00' == $product['available_date']) {
+                $product['available_date'] = null;
+            }
```
Comment (matthieu-rolland) [inline src/Adapter/Presenter/Product/ProductLazyArray.php]: hello @awitkutarahil, thank you for your contribution :)

  Here it seems that if `'0000-00-00' == $product['available_date']` then `$product['available_date']` will be set to null anyway in the second condition (since it will be inferior to current date), therefore this first condition seems unnecessary, what do you think ?

**Review by matthieu-rolland — CHANGES_REQUESTED** [review]

File: src/Adapter/Presenter/Product/ProductLazyArray.php (hunk 1 above)
Comment (NeOMakinG) [reply src/Adapter/Presenter/Product/ProductLazyArray.php]: Nice catch, you should be right

Comment (awitkutarahil) [reply src/Adapter/Presenter/Product/ProductLazyArray.php]: @matthieu-rolland Clever indeed. I have removed the unnecessary condition.

**Review by NeOMakinG — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Presenter/Product/ProductLazyArray.php [hunk 2]
```diff
@@ -814,8 +814,11 @@ public function addQuantityInformation(
         $this->product['show_availability'] = $show_availability;
         $product['quantity_wanted'] = $this->getQuantityWanted();
 
-        if (isset($product['available_date']) && '0000-00-00' == $product['available_date']) {
-            $product['available_date'] = null;
+        if (isset($product['available_date'])) {
+            $date = new \DateTime($product['available_date']);
+            if ($date < new \DateTime()) {
```
Comment (PierreRambaud) [inline src/Adapter/Presenter/Product/ProductLazyArray.php]:
```suggestion
            $date = new DateTime($product['available_date']);
            if ($date < new DateTime()) {
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please use namespace instead :)

**Comment by awitkutarahil** [comment]
> Could you please use namespace instead :)

This is done 😉

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @awitkutarahil,

It is ok :heavy_check_mark: 
https://www.awesomescreenshot.com/video/825094?key=575dba2a7b15f56180ca217c96786c98

Thanks!

**Comment by AldeaG** [comment]
How can I implement this in a Prestashop 1.7.7.0 without update the whole Prestashop?
