### PR TITLE
BO Modules : Display only modules if you have the permission

### LINKED ISSUE #9874: [BOOM-3974] View permission doesn't work for modules
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3974).

- _**Reporter:**_ @marionf 
- _**Created at:**_ Mon, 9 Oct 2017 17:49:05 +0200

**Describe the issue**
I can see some modules in BO even if I don't have the "View" right for this module in permissions.

**Steps to reproduce**
1. Go in Advanced parameters > Team > Permissions > Logistician
2. Check View, Add, Edit & Delete for the lines Modules, Modules Manager & Modules
3. In the Modules block, don't check view for any modules
4. Go in Advanced parameters > Team > Employees and create a new Logistician profile
5. Login with this profile
6. Go in Modules > Modules Manager > Modules
7. You can view all the modules while you don't have the right to view them

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | BO Modules : Display only modules if you have the permission
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | :arrow_down: 
| UI Tests          | https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/18784773889
| Fixed issue or discussion?     | Fixes #9874 
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

### CODE REVIEW

**Review by Codencode — APPROVED** [review]

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

File: src/Core/Module/ModuleRepository.php [hunk 1]
```diff
@@ -378,4 +381,24 @@ protected function enrichModuleAttributesFromHook(Module $module): ModuleInterfa
 
         return $module;
     }
+
+    /**
+     * Filter modules if the current employee has the right to see it
+     */
+    protected function filterModulesFromPermissions(ModuleCollection $modules): ModuleCollection
```
Comment (SharakPL) [inline src/Core/Module/ModuleRepository.php]:
```suggestion
    protected function filterModulesByPermissions(ModuleCollection $modules): ModuleCollection
```
Isn't this more logical name?

File: src/Core/Module/ModuleRepository.php [hunk 2]
```diff
@@ -378,4 +381,24 @@ protected function enrichModuleAttributesFromHook(Module $module): ModuleInterfa
...
+        foreach ($modules as $key => $module) {
+            $moduleName = $module->getAttributes()->get('name');
+            if ($this->moduleDataProvider->isInstalled($moduleName)) {
+                if (!$this->moduleDataProvider->can(
+                    ModulePermission::VIEW,
+                    $moduleName
+                )) {
+                    unset($modules[$key]);
+                }
+            }
```
Comment (SharakPL) [inline src/Core/Module/ModuleRepository.php]:
```suggestion
            if ($this->moduleDataProvider->isInstalled($moduleName) && !$this->moduleDataProvider->can(
                ModulePermission::VIEW,
                $moduleName
            )) {
                unset($modules[$key]);
            }
```
No need for nesting. Right?

**Review by Codencode — DISMISSED** [review]

File: src/Core/Module/ModuleRepository.php (hunk 1 above)
Comment (Progi1984) [reply src/Core/Module/ModuleRepository.php]: Fixed.

File: src/Core/Module/ModuleRepository.php (hunk 2 above)
Comment (Progi1984) [reply src/Core/Module/ModuleRepository.php]: Fixed.

**Comment by Progi1984** [comment]
@SharakPL & @Codencode Fixed feedbacks from @SharakPL :muscle:

**Review by kpodemski — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Progi1984, 

Thanks for your PR, I tested it and it's good for me :) 

Capture d’écran 2025-11-14 à 15 32 39


Capture d’écran 2025-11-14 à 15 29 20
3b15232807" />

Capture d’écran 2025-11-14 à 15 31 22

**Review by SiraDIOP — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @SiraDIOP and @Progi1984 !
