### PR TITLE
Impossible to change position of products

### LINKED ISSUE #11152: It is impossible to change position of products into a category in the catalog > product page
**Describe the bug**
It is impossible to change the position of products into the catalog => product page.
After Drag & drop => Click on "Save & Refresh" button => The green alert "Products successfully sorted." is not displayed.
The new positions of products are not saved.

**To Reproduce**

1. Go to Catalog > Products
2. Click on Filter by categories and select a category ( Art category)
3. Click on Reorder button
4. Drag & drop some products
5. Click on "Save & Refresh" button
6. "Products successfully sorted." is not displayed & The new positions of products are not saved.
image

PS: 1.7.5.0 beta1 build1 => OK.
**Screenshots**
https://drive.google.com/file/d/1lDPMf28BqLEVKG_evNMmQWvEuZAhTDTT/view

**Additionnal information**
PrestaShop version: 1.7.5.0 beta1 build2
PHP version: 7.1

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Unable to change position when position start at 0. Reorder button appears with strange condition.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11152.
| How to test?  | Create new category, two products and try to reorder. Or just reorder after a fresh install.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11475)

### CODE REVIEW

File: src/Adapter/Product/ListParametersUpdater.php [hunk 1]
```diff
@@ -70,12 +70,42 @@ public function buildListParameters(
...
+                $persistedFilterParameters,
+                $defaultFilterParameters
+            ),
         ];
+
+        /*
+         * We need to force the sort order when the order by
+         * is set to position_ordering
+         */
+        if ('position_ordering' === $filters['orderBy']) {
```
Comment (jolelievre) [inline src/Adapter/Product/ListParametersUpdater.php:104]: ok but I think it should be done in `cleanFiltersForPositionOrdering`

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 2]
```diff
@@ -167,23 +173,26 @@ public function catalogAction(
...
-                $categoriesForm->setData(
-                    [
-                        'categories' => [
-                            'tree' => [0 => $combinedFilterParameters['filter_category']],
-                        ],
-                    ]
-                );
-            }
+        }
+        // Pagination
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php:178]: can you add a blank line please? for clarity

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 3]
```diff
@@ -320,11 +333,17 @@ public function listAction(
...
+                    [
+                        'limit' => $limit,
+                        'offset' => $offset,
+                        'total' => $totalCount,
+                    ]
+                )
+            );
         }
 
         return $vars;
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php:350]: this is not clear at all, sometimes we return a response, sometime it's an array..
we should always return the same thing, the convention chosen for new migrated controllers is to always explicitly return a Response via render
could you please remove the `@Template` association and use render instead?
it may not be necessary on all actions (although it would be nice), but this one especially is really messy

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 4]
```diff
@@ -860,21 +896,26 @@ public function massEditAction(Request $request, $action)
             return $this->redirectToRoute('admin_product_catalog');
         }
 
-        /** @var ProductInterfaceProvider $productProvider */
+        /* @var $productProvider ProductInterfaceProvider */
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php]: I changed these annotations volontarily in my last PR
why do you want to use this reverse annotation?
It's not very readable, it is inconsistent with the class or controller fields annotations
And I'm not even sure PHPStorm (or other IDEs) understand it

**Review by jolelievre — COMMENTED** [review]
nice catch @PierreRambaud

File: src/Adapter/Product/ListParametersUpdater.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Adapter/Product/ListParametersUpdater.php:104]: I tought about it but this function is called after the first usage of `$orderBy`.
ProductController::150 => getCatalogPorduct
and the clean is at 191 :(

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 3 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:350]: I just add line break here :P It's from my cleanup commit.

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 4 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]: Problem while rebase :) My bad

File: src/Adapter/Product/ListParametersUpdater.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Product/ListParametersUpdater.php:104]: you're right, this controller is a nightmare..
I'm thinking of better ways to manage this, but none seems acceptable..

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 3 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:350]: I know you didn't implement it, I was just thinking it could be the occasion to improve it
But it can be done later

**Review by jolelievre — APPROVED** [review]
unless you're motivated to change the `listAction` method (but I would understand if you're not ^^) it's fine for me

File: src/Adapter/Product/ListParametersUpdater.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Adapter/Product/ListParametersUpdater.php:104]: We will have to change everything in the future, we need to refactor how the old migrated controllers have been done :/

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 3 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:350]: Too risky to change something and or refactor everything before the release :(

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:350]: But I thought about it ^^

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:350]: you're right!

File: src/Adapter/Product/ListParametersUpdater.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Product/ListParametersUpdater.php:104]: yep @mickaelandrieu has prepared an issue about this, to plan how we will attack this controller!

**Comment by Quetzacoalt91** [comment]
Thank you @PierreRambaud
