### PR TITLE
Fix: Cart.php class method _deleteCustomization not deleting all image files from same customization but only first

### LINKED ISSUE #36904: Cart.php class method _deleteCustomization not deleting all image files from same customization but only first
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I have a product with multiple customization fields: 11 text fields, and 3 file fields.
Saving customization fields to product works well.
But when I remove a product from Cart, customization data is deleted from Database correctly, but attached image files stored at /upload/ folder are not fully deleted. It deletes only first image file, and other image files like 2nd and 3rd remains there

Place where bug is i think: Cart.php class method _deleteCustomization

### Expected behavior

When I delete a Product from Cart with multiple customization fields, I expect all physically image files from customization fields type 'FILE' are deleted from /upload/ folder and not only first.

### Steps to reproduce

1. in admin create a Product with more customization fields e.g. 5 text fields, and 3 file fields
2. in frontend fill all customization fields (into file fields upload 3 JPG images)
3. add this product to Cart, and for now all is fine
4. now in Cart remove this product from Cart
5. check the folder /upload/ and you will see that 1st image file was deleted, and 2nd and 3rd image file were not deleted

### PrestaShop version(s) where the bug happened

8.1.4

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | I have a product with multiple customization fields: 11 text fields, and 3 file fields. Saving customization fields to product works well. But when I remove a product from Cart, customization data is deleted from Database correctly, but attached image files stored at /upload/ folder are not fully deleted. It deletes only first image file, and other image files like 2nd and 3rd remains there.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | in admin create a Product with more customization fields e.g. 5 text fields, and 3 file fields. In frontend fill all customization fields (into file fields upload 3 JPG images). Add this product to Cart, and for now all is fine. Now in Cart remove this product from Cart.Check the /upload/ folder and verify that all files for this customization have been deleted
| UI Tests | https://github.com/florine2623/testing_pr/actions/runs/10903699993
| Fixed issue or discussion?     | Fixes #36904
| Sponsor company   | @Codencode

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -2002,14 +2002,18 @@ protected function _deleteCustomization($id_customization, $id_product, $id_prod
             WHERE `id_customization` = ' . (int) $id_customization);
 
         if ($customization) {
-            $cust_data = Db::getInstance()->getRow('SELECT *
+            $cust_datas = Db::getInstance()->executeS('SELECT *
```
Comment (Hlavtox) [inline classes/Cart.php:2009]:
```suggestion
            /*
             * Now we will select all customized files that could be connected to this customization.
             * One customization can have multiple fields for files, we need to delete all of them.
             */
            $cust_datas = Db::getInstance()->executeS('SELECT *
```

Just some comments 🙏

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@Codencode Good job dude! :-)

**Comment by Codencode** [comment]
> @Codencode Good job dude! :-)

Thank you!

**Review by tleon — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Codencode ,

Works as expected :

https://github.com/user-attachments/assets/16663a29-24a5-4e8c-b27c-56b0617f00e4

It is QA ✅

**Comment by Hlavtox** [comment]
Thanks @Codencode & @florine2623, good job
