### PR TITLE
Fix availability structured data

### LINKED ISSUE #23199: schema.org error in products out of stock when stock management is disabled
#### Describe the bug

schema.org error in products out of stock when stock management is disabled.

When you deactivate the stock management and a product is in negative stock, instead of showing this
```
itemprop="offers" itemscope itemtype="https://schema.org/Offer">
<link itemprop="availability" href="https://schema.org/InStock" />
```

this other wrong code is shown
```
itemprop="offers" itemscope itemtype="https://schema.org/Offer">
<link itemprop="availability" href="https://schema.org/PreOrder" />
```

#### Expected behavior

I think the product should be shown in stock

#### Steps to Reproduce

1. Go to disable stock management
2. Increase stock on a product
3. See good on source code

4. Reduce the stock of the same product to 0
5. See error on source code

**Screenshots**

https://youtu.be/ogvmNO3m7SY

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.7.1, develop (1.7.8.0)
* PHP version: 7.2, 7.3

### LINKED ISSUE #23534: Wrong definition of Schema.org availability for out-of-stock products.
#### Describe the bug

Structured data availability (used by search engines to display rich snippets in results) is defined in ProductLazyArray.

```
if ($this->product['quantity'] > 0) {
    $seoAvailability .= 'InStock';
} elseif ($this->product['quantity'] <= 0 && $this->product['allow_oosp']) {
    $seoAvailability .= 'PreOrder';
} else {
    $seoAvailability .= 'OutOfStock';
}
```

Preorder should not be there, OutOfStock should be used instead.

> Note: The preorder value should only be used for new products and shouldn't be used for existing products that are out of stock and will be back in stock at a later date.​

Source: https://support.google.com/merchants/answer/6324448?hl=en

#### Expected behavior

```
if ($this->product['quantity'] > 0) {
    $seoAvailability .= 'InStock';
} else {
    $seoAvailability .= 'OutOfStock';
}
```

#### Steps to Reproduce

1. FO, in the product page template, put {$product.seo_availability} anywhere
2. Check it out for products with available quantity
3. Then with 0 quantity and OOSP enabled
4. And with 0 quantity and OOSP disabled

#### Additional information
* PrestaShop version: 1.7

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Resolves #23534, resolves #23199
| Related PRs       | -
| How to test?      | See below
| Possible impacts? | -
| Sponsor company   | [TRENDO s.r.o.](https://www.trendo.cz)

#### Description
- Fixes availability structured data.
- Structured data needed some tweaks, more info below. Everything is PM validated. BETTER SEO.
- Products out of stock should not have **Preorder** availability. Per google documentation: `Note: The preorder value should only be used for new products and shouldn't be used for existing products that are out of stock and will be back in stock at a later date.​`
  - Google doc: https://support.google.com/merchants/answer/6324448?hl=en
  - Discussion: https://github.com/PrestaShop/PrestaShop/issues/23534#issuecomment-796258724
- If stock management is disabled = we have everything, we should always return **In Stock**.
  - Discussion: https://github.com/PrestaShop/PrestaShop/pull/23248#issuecomment-813998975
  - Google doc: https://support.google.com/merchants/answer/6324448

#### How to test
- You will see result of this PR in the source code of product page.
- Test with stock management disabled and see that it always returns in stock.
- Test with out of stock, not available for order product.
- Test wth out of stock, orderable product.
- Test with in stock product.

availability

### CODE REVIEW

File: src/Adapter/Presenter/Product/ProductLazyArray.php [hunk 1]
```diff
@@ -382,22 +382,25 @@ public function getGroupedFeatures()
...
     {
-        $seoAvailability = 'https://schema.org/';
-        if ($this->product['quantity'] > 0) {
-            $seoAvailability .= 'InStock';
-        } elseif ($this->product['quantity'] <= 0 && $this->product['allow_oosp']) {
-            $seoAvailability .= 'PreOrder';
+        // This case doesn't show by default, if one wants to keep inactive products
+        // displayed as discontinued, he will have proper structured data
+        if ($this->product['active'] === 0) {
+            return 'https://schema.org/Discontinued';
```
Comment (kpodemski) [inline src/Adapter/Presenter/Product/ProductLazyArray.php:394]: Do we really need it? The inactive product should not be visible in the front office, right? Am I missing something?

Comment (Hlavtox) [reply src/Adapter/Presenter/Product/ProductLazyArray.php:394]: Yes, they are not visible now, but I want to add this possibility in the future. More details here - https://github.com/PrestaShop/PrestaShop/issues/23533

Comment (kpodemski) [reply src/Adapter/Presenter/Product/ProductLazyArray.php:394]: Isn't `410 Gone status code` a feature that will help with that? It is precisely for that reason to avoid indexing addresses that are no longer relevant in the store.

Comment (Hlavtox) [reply src/Adapter/Presenter/Product/ProductLazyArray.php:394]: Yes, it will, I want to implement an option to send 200/404/410 along with "DISCONTINUED" text. This is just a bonus. :-)

Comment (Hlavtox) [reply src/Adapter/Presenter/Product/ProductLazyArray.php:394]: @kpodemski WIP - https://github.com/PrestaShop/PrestaShop/pull/29720

Comment (Hlavtox) [reply src/Adapter/Presenter/Product/ProductLazyArray.php:394]: @kpodemski Removed from this PR

**Comment by Hlavtox** [comment]
Ready to review

**Review by matks — DISMISSED** [review]
Thank you for providing all the sources from Google, I believe this implementation is good and follows Google recommendations

Great work 👍 

Nice-to-have (for a future PR maybe): SEO logic rules should not be written inside ProductLazyArray.php . I guess we could create something like SEOStrategy.php where we write up-to-date SEO rules (they need to be regularly updated), rules could be overriden by a hook so that people who think this is not the best SEO solution could customize it 😋 and ProductLazyArray.php would simply fetch the SEO rules and apply whatever they are

**Review by marsaldev — DISMISSED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hello @Hlavtox,

I found an issue following these steps:

1. Go to BO > Shop Parameters > Product Settings page
2. Enable "Enable stock management" and Enable "Allow ordering of out-of-stock products"
3. Create a product out of stock with "allowed order" & "Availability date"
image
4. Preview the product in the FO
5. FO, in the product page template, put `{$product.seo_availability}` anywhere
6. See error `seo_availability === https://schema.org/OutOfStock`, it should be **Backorder** 
image


As I checked here https://support.google.com/merchants/answer/6324448
```
Backorder [backorder]
The product is not available at the moment, but you’re accepting orders and it'll be shipped as soon as it becomes available again. You're required to provide the availability date
```

Thanks!

**Comment by Hlavtox** [comment]
Hi @khouloudbelguith, the PR was done per last year's specs. BackOrder value was not supported, I have added it now.

For approvals and QA let's wait until https://github.com/PrestaShop/PrestaShop/pull/29720 is merged because there will be a conflict. 👍

**Review by kpodemski — COMMENTED** [review]
Hi @Hlavtox 

Only a few weeks to get it to 8.1 if you have time to finish it :D

**Comment by Hlavtox** [comment]
@hibatallahAouadni Please start testing, I will get reviews in the meantime :D

**Review by zuk3975 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox, 

Thank you for your PR, 

I tried to reproduce the issue of Khouloud and it's seems to be corrected, as you can see  : 
image

I also tried the differente scénario you asked. : 
"Test with stock management disabled and see that it always returns in stock.
Test with out of stock, not available for order product.
Test wth out of stock, orderable product.
Test with in stock product."

Even the automated test seems ok 

So it's QA Approved :heavy_check_mark: 

Thank you !

**Comment by Hlavtox** [comment]
Perfect, thanks guys!
