### PR TITLE
Trigger a deprecated when using a hook alias and correctly handle errors

### LINKED ISSUE #26411: Errors are not correctly handle in FO and BO contexts
#### Describe the bug

First, we should run a deprecated notice when we use hook aliases.
Aliases are here for retro compatibility and should be removed in the future, this was originally designed for this reason.

Then, with the Symfony migration, all migrated controllers are based on AdminLegacyController, which result a catch of all errors/warning/deprecated/etc, when the controller is initialized, so a lot of data are not properly caught by the Symfony Profiler.

Last but not least, the Symfony debug must not be triggered in Front Office, it set the `display_errors` to false and a lot of errors are hidden.

#### Expected behavior

- Mark usage of hook aliases as deprecated, it tells people to use the new hook
- Remove Symfony debugger in FO, it will be automatically restored when we will migrate the FO
- Only run "myErrorHandler" (seems a pretty copy & paste from Stackoverflow :trollface: ) when it's not inside `AdminLegacyController`

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Also, remove init debug in front as we don't have Symfony profiler, it hides a lot of possible errors. Plus, only use php_errors when using a controller that's not AdminLegacylayoutControllerCore.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| Fixed ticket?   | Fixes #26411
| How to test?      | No need QA
| Possible impacts? | The front and the back are now correctly handle "trigger_error" calls, a lot of changes will have to be made :sweat_smile: 

### BC breaks

- `Hook::getHookAliasList` is no longer available
- `Hook::getRetroHookName` is no longer available

### Deprecated

- The usage of hook aliases now trigger a deprecated message 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26267)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
A lot of deprecations have to be fixed in our modules :sweat_smile:

**Comment by tegbessou** [comment]
PR is valid IMO

**Review by matthieu-rolland — COMMENTED** [review]
Seems like adding new triggers is breaking some integration tests, you'll have to update them, at least in `EditRootCategoryHandlerTest` but probably in other places too

**Review by sowbiba — DISMISSED** [review]

**Review by Progi1984 — COMMENTED** [review]
@PierreRambaud Could you document BC Break, please ? :pray:

File: classes/module/Module.php [hunk 1]
```diff
@@ -2710,9 +2710,7 @@ public function isHookableOn($hook_name)
             return Hook::isDisplayHookName($hook_name);
         }
 
-        $retro_hook_name = Hook::getRetroHookName($hook_name);
```
Comment (jolelievre) [inline classes/module/Module.php:2439]: Does it mean alias or retro hook cannot be used anymore? Or it only prevents positioning a module on an alias hook?

File: tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php [hunk 2]
```diff
@@ -66,7 +66,7 @@ public function handleFor($id, FormInterface $form)
         return $this->formHandler->handleFor($form, $id);
     }
 
-    public function getLastCreatedId(): int
+    public function getLastCreatedId(): ?int
```
Comment (jolelievre) [inline tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php]: That's not supposed to happen actually 😅

This is only hiding the problem, but I'm not sure it will prevent the ProductControllerTest from failing

**Review by jolelievre — COMMENTED** [review]
Just a two questions, but i'm not sure the modif to fix the tests is the right approach

Also, just to be clear, this PR triggers deprecation notices when an alias is used, but the feature itself still works right?

File: classes/module/Module.php (hunk 1 above)
Comment (PierreRambaud) [reply classes/module/Module.php:2439]: We shouldn't transplant an alias, an alias is here to retrieve the new hook and call it if needed.
I'll do more test to be sure everything is ok everywhere

File: tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php (hunk 2 above)
Comment (PierreRambaud) [reply tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php]: That's not supposed to happen but if you check the class, you can create it without having the lastCreatedId set. 
```php
$a = new FormhandlerChecker(..., ...);
$a->getLastCreatedId() === null; // Means nothing as been handled yet.
$a->handleFor($id, $form);
$a->getLastCreatedId() === null; // Is null again.
```

I don't understand the class behavior, it's quite weird :sweat_smile: if the lastCreatedId is mandatory, so the handle have to be executed in the constructor.

Comment (PierreRambaud) [reply tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php]: And if the test still pass if the value is null and it should be set, it means the test is malformed :sweat_smile:

Comment (jolelievre) [reply tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php]: Nope, actually this class is used on top of the `FormHandlerInterface` because it's part of our form processing workflow, it creates an entity and returns the ID to the controller which can then redirect to the edit page

But during test workflow we need to know which ID has been created, and parsing the redirection URL is not the ideal way to do this since it's not generic, URL format can change and so on So the idea is to wrap the usual handler in this decorator, and save the created ID before it is returned to the controller

So that after the create controller has been called, we can get the generated ID. Now in all our tests we expect this ID to be present, if it's not it means the creation process failed so allowing null would only hide the problem

Comment (jolelievre) [reply tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php]: That said, it might not be the checker responsibility to ensure the presence of this ID, and even if it did it's not via a forced type So nevermind, you can change this to nullable type Because we can also imagine some test use cases where we check that the creation failed

Anyway it's up to the test to assert the ID value (null or not), not the checker so ok for your modification But I'm still not sure this will resolve your CI issue ^^

Comment (jolelievre) [reply tests/Integration/Core/Form/IdentifiableObject/Handler/FormHandlerChecker.php]: @PierreRambaud I extracted the refacto of those test controllers in this PR https://github.com/PrestaShop/PrestaShop/pull/26437 Feel free to review it 😉

**Review by matks — DISMISSED** [review]
OK for me. @jolelievre raised the only thing I'm afraid of and issue is settled

**Comment by matks** [comment]
Please rebase @PierreRambaud 😭  sorry

**Comment by PierreRambaud** [comment]
> Please rebase @PierreRambaud sob sorry

I'm waiting for modules to be released

**Comment by matks** [comment]
Re-running CI

**Comment by matks** [comment]
Apologies for late answer @PierreRambaud .

Code is good for me but PR needs a rebase and CI fails. Can you fix these and ping me ASAP? I'll add the approval quick.

**Comment by PierreRambaud** [comment]
> Apologies for late answer @PierreRambaud .
> 
> Code is good for me but PR needs a rebase and CI fails. Can you fix these and ping me ASAP? I'll add the approval quick.

I'm still waiting for release in some modules :p

**Comment by matks** [comment]
> > Apologies for late answer @PierreRambaud .
> > Code is good for me but PR needs a rebase and CI fails. Can you fix these and ping me ASAP? I'll add the approval quick.
> 
> I'm still waiting for release in some modules :p

Which one ? Can I help to speed up the process ?

**Comment by PierreRambaud** [comment]
> > > Apologies for late answer @PierreRambaud .
> > > Code is good for me but PR needs a rebase and CI fails. Can you fix these and ping me ASAP? I'll add the approval quick.
> > 
> > 
> > I'm still waiting for release in some modules :p
> 
> Which one ? Can I help to speed up the process ?

For now, it's `ps_mainmenu`

**Comment by matks** [comment]
@PierreRambaud So, if I checkout this branch, I should have issues with ps_mainmenu right?

**Comment by PierreRambaud** [comment]
And now it's about the `ps_featuredproducts` module ^^

**Comment by PierreRambaud** [comment]
New PR for ps_featuredproducts https://github.com/PrestaShop/ps_featuredproducts/pull/43

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
As in the column **how to test** there's **no QA needed** so I will add the label **waiting for dev**.

**Comment by atomiix** [comment]
With this PR in debug mode on:
Capture d’écran 2021-12-27 à 15 30 23

Without this PR or in debug mode off:
Capture d’écran 2021-12-27 à 15 31 05

This PR is QA ✔️

**Comment by atomiix** [comment]
Thanks @PierreRambaud
