### PR TITLE
Fix filters reset in BO stock movements

### LINKED ISSUE #18000: Filter in movements and stock does not reset
#### Describe the bug

When filters are activated on Movements (or Stock) page, if you change tab to "Stock" (or Movement, you got the idea...), and then go back to "Movements", the filters appears to be reset (at "None", all checkboxes unchecked), but if you add a new filter, it will combine with the older filters.

#### Expected behavior

Filters should either be really reset, or filters should stay displayed.

#### Steps to Reproduce

1. Go to BO > Catalog > Stocks > Movements : All movements are displayed
2. Add Filter, for example "Movement type" set to "Product return" : Data are filtered
3. Go to "Stock" tab, then go back to "Movements" : All movements are displayed, and filters appears to be reset.
4. Add another filter (for example, check "Accessories" category) : Only data with "Accessories" category AND movement type "Product return" are displayed, even if there is no shown filter on movement type.

**Screenshots**

https://drive.google.com/file/d/1Q6UXU9rspcWKQPgaEKEzgZGBJkzwNvam/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7 and 1.7.6.2 at least
* PHP version: N/A

### PR DESCRIPTION
**Pull request by saulaski**
Now on filter reset event, root app resets child filter components

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In BO/Catalog/Stock, filters didn't reset correctly because previous selection was kept stored in child components. Only the root app did reset its own filters on reset event.<br/>Now the root app resets itself plus its child filter components.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #18000.
| How to test?      | <ol><li>Go to BO > Catalog > Stocks > Movements : All movements are displayed</li><li>Add Filter, for example "Movement type" set to "Product return" : Data are filtered</li><li>Go to "Stock" tab, then go back to "Movements" : All movements are displayed, and filters appears to be reset.</li><li>Add another filter (for example, check "Accessories" category) : Only data with "Accessories" category AND movement type "Product return" are displayed, even if there is no shown filter on movement type.</li></ol>
| Possible impacts? | Only BO/Catalog/Stock filters

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27329)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue [hunk 1]
```diff
@@ -153,7 +155,7 @@
   import PSSelect from '@app/widgets/ps-select.vue';
   import PSDatePicker from '@app/widgets/ps-datepicker.vue';
   import PSRadio from '@app/widgets/ps-radio.vue';
-  import FilterComponent from './filters/filter-component.vue';
+  import FilterComponent, {FilterComponentInstanceType} from './filters/filter-component.vue';
```
Comment (sowbiba) [inline admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue:158]:
```suggestion
  import {FilterComponent, FilterComponentInstanceType} from './filters/filter-component.vue';
```

File: admin-dev/themes/new-theme/js/app/pages/stock/components/app.vue [hunk 2]
```diff
@@ -57,12 +58,14 @@
   import Vue from 'vue';
   import PSPagination from '@app/widgets/ps-pagination.vue';
   import StockHeader from './header/stock-header.vue';
-  import Search from './header/search.vue';
+  import Search, {SearchInstanceType} from './header/search.vue';
```
Comment (sowbiba) [inline admin-dev/themes/new-theme/js/app/pages/stock/components/app.vue:61]:
```suggestion
  import {Search, SearchInstanceType} from './header/search.vue';
```

**Comment by sowbiba** [comment]
Not sure if you have to target develop or 1.7.8.x

Ping @PrestaShop/product-team

File: admin-dev/themes/new-theme/js/app/pages/stock/components/app.vue (hunk 2 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/app/pages/stock/components/app.vue:61]: Both are valid, I prefer the one @saulaski used because Search is the default export

File: admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue (hunk 1 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue:158]: same here, not needed, FilterComponent is the default export

**Review by NeOMakinG — APPROVED** [review]
We seen most of this together, looks fine to me even if it's not really respecting good practices, you won't refactor the whole system.

**Comment by saulaski** [comment]
> We seen most of this together, looks fine to me even if it's not really respecting good practices, you won't refactor the whole system.

This fix is indeed a dirty workaround to clean up duplicated data in child components, in order to properly reset the filters.

**Review by sowbiba — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,

I tested the PR the issue is fixed. 
https://watch.screencastify.com/v/2FxFeVa9rsxzRFKJ9Z39

Thanks,

**Comment by matks** [comment]
Thank you @saulaski
