### PR TITLE
Do not overwrite legend by empty value

### LINKED ISSUE #21806: Image titles are empty, if image legend is empty - FO
#### Describe the bug

HTML image TITLE is empty, if image legend is empty.

#### Expected behavior

HTML image TITLE should not be empty, if image legend is empty.
It should be filled with product name.

#### Steps to Reproduce

1. Go to product listing (for example) and view page source.
2. Check the product image with empty image legend.
3. You can see, that only ALT attribute is filled.
4. If you check product image with legend instead - you can see that both  ALT and TITLE attributes are filled

### Additional infos
* PrestaShop version: 1.7.6.5
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixes empty image legends/titles. There is a fallback to object name implemented in `getImage`, but it got overwritten back to empty legend in `getAllProductImages`.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Delete image description from a product in BO. Visit that product in FO, inspect the main image and check that there is a product name in the `title` and `alt` tags. Some themes may have a fallback in them built in, test it with latest version of hummingbird.
| Fixed ticket?     | Fixes #21806
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

File: src/Adapter/Image/ImageRetriever.php [hunk 1]
```diff
@@ -96,11 +99,14 @@ public function getAllProductImages(array $product, Language $language)
             $productInstance,
             $imageToCombinations
         ) {
-            $image = array_merge($this->getImage(
-                $productInstance,
-                $image['id_image']
-            ), $image);
+            // Now let's fetch extra information about thumbnail sizes etc. and add this information.
+            // getImage also resolves a proper image legend, if it was missing in $image originally.
+            $image = array_merge(
```
Comment (kpodemski) [inline src/Adapter/Image/ImageRetriever.php]:
```suggestion
            $image = array_merge(
```

Comment (kpodemski) [reply src/Adapter/Image/ImageRetriever.php]: cs fixer

Comment (Hlavtox) [reply src/Adapter/Image/ImageRetriever.php]: Fixed ✅

**Review by kpodemski — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Auto test are failing here : https://github.com/florine2623/testing_pr/actions/runs/5691959862/job/15430408174
Could you check ? The error does not exist on the nightly.

What do you think @PrestaShop/qa-automation ? it is related to the PR ?

Tested the PR with hummingbird.
LGTM ✅

**Comment by kpodemski** [comment]
Failing tests are not related to the PR.

**Comment by Progi1984** [comment]
@florine2623 It's ok. The error is caused by #33295.

**Comment by diseneopl** [comment]
Doesn't work correctly when images are assigned to an attribute and set image legend for example last image (display product name for all)

**Comment by Hlavtox** [comment]
@diseneopl Can you provide more information? Screenshots and what is wrong, and how it should be?

**Comment by diseneopl** [comment]
In backend I set legend only for last image. In frontend legend of all images is the same, product name.

**Comment by Hlavtox** [comment]
@diseneopl Yes you are right, the legends don't work at all. :-)))
