### PR TITLE
Fix: Doctrine auto-mapping in modules: only the first subfolder inside src/Entity is recognized

### LINKED ISSUE #39725: Doctrine auto-mapping in modules: only the first subfolder inside src/Entity is recognized
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Currently, Doctrine auto-mapping in PrestaShop modules correctly recognizes:

- entities placed directly inside the src/Entity directory
- or all entities contained within a single subfolder

However, if multiple subfolders are present, Doctrine maps only the first one it finds, ignoring the others.

**Example**

If the module has the following structure:

- src/Entity/Category/Category.php  
- src/Entity/Feature/Feature.php  
- src/Entity/Product.php

the system will throw the following error:

```php
The class 'Cnc\EntitiesMoreFolders\Entity\Product' was not found in the chain configured namespaces
```

@jolelievre, this seems to be another issue related to Doctrine and ORM, not connected to cache and therefore not related to this PR: https://github.com/PrestaShop/PrestaShop/pull/39525

The problem is I couldn't figure out what might be causing it.
The only thing I noticed is that in the container, specifically in the file v`ar/cache/dev/admin/ContainerXXXX/AdminKernelDevDebugContainer.php` in the method `getDoctrine_Orm_DefaultConfigurationService()` there's:

```php
$a->addDriver(new \Doctrine\ORM\Mapping\Driver\AnnotationDriver($b, [(\dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'entities_more_folders'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity')]), 'Cnc\\EntitiesMoreFolders\\Entity\\Category');
```

and not:
```php
$a->addDriver(new \Doctrine\ORM\Mapping\Driver\AnnotationDriver($b, [(\dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'modules'.\DIRECTORY_SEPARATOR.'entities_more_folders'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Entity')]), 'Cnc\\EntitiesMoreFolders\\Entity');
```

If I manually update the container, the system no longer throws the error.

### Expected behavior

_No response_

### Steps to reproduce

1. Install the module [entities_more_folders.zip](https://github.com/user-attachments/files/23047977/entities_more_folders.zip).
2. Go to the module configuration page in the back office.
3. The following error will be displayed:

### PrestaShop version(s) where the bug happened

8 - 9

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Codencode snc

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.1.x
| Description?      | This PR modifies the `getModuleNamespace()` method used for registering Doctrine entity mappings for modules.<br/>Instead of returning the full namespace of the first class found, the method now truncates the namespace up to the `\Entity` root, in order to obtain a namespace that is valid for all module entities (including those in subfolders).<br/><br/>_This PR allows organizing a module's Entities into multiple subfolders within `src/Entity`, while keeping the Doctrine mapping functional and improving the module's overall structure._
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Install the module [entities_more_folders.zip](https://github.com/user-attachments/files/23047977/entities_more_folders.zip).<br/> 2. Go to the module configuration page in the back office.<br/> 3. You must display the page without errors as follows: Screenshot 2025-11-24 at 18-04-03 Module Manager • Codencode
| UI Tests          | 🟢  https://github.com/Codencode/ga.tests.ui.pr/actions/runs/21839303816
| Fixed issue or discussion?     | Fixes #39725
| Related PRs       | 
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by Codencode** [comment]
@kpodemski @Hlavtox @jolelievre
I'm getting an error in this **test (functional:BO:orders:03-05, 9.0.x)** (UI test): https://github.com/Codencode/ga.tests.ui.pr/actions/runs/19642981377/job/56310285909

It appears the system expects **Credit slip** but gets **Delivery slip** instead.
Perhaps something changed in the tests?
Could you help me with this?
Thank you!

**Comment by Hlavtox** [comment]
Something wrong with automatic tests, ping @PrestaShop/qa-automation.

@Codencode Not relevant to your PR, accepting it and the tests should be fixed later.

**Review by Hlavtox — DISMISSED** [review]

**Comment by Codencode** [comment]
@Hlavtox 
Of course, I understood it wasn't related, but I thought it was worth investigating further.
Thanks!

**Comment by Progi1984** [comment]
@Codencode UI Tests are :green_circle:  : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19696223678/job/56425358771

**Comment by Codencode** [comment]
> @Codencode UI Tests are 🟢 : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19696223678/job/56425358771

@Progi1984 Awesome, thank you!

**Review by Hlavtox — DISMISSED** [review]

**Review by ShaiMagal — DISMISSED** [review]

File: src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php [hunk 1]
```diff
@@ -120,11 +120,19 @@ private function createAnnotationMappingDriver($moduleNamespace, $moduleEntityDi
     private function getModuleNamespace(SplFileInfo $moduleFolder)
     {
         $finder = new Finder();
-        $finder->files()->in($moduleFolder->getRealPath() . '/src/Entity')->name('*.php');
+        $finder->files()->in($moduleFolder)->name('*.php');
```
Comment (jolelievre) [inline src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php]: So the entities can now be in any folder? Not necessarily `src\Entity`, as long as the namesapce in the file ends with `\Entity` ? or contains `\Entity` ?

File: src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php [hunk 2]
```diff
@@ -120,11 +120,19 @@ private function createAnnotationMappingDriver($moduleNamespace, $moduleEntityDi
...
-            $phpContent = file_get_contents($phpFile->getRealPath());
-            if (preg_match('~namespace[ \t]+(.+)[ \t]*;~Um', $phpContent, $matches)) {
-                return $matches[1];
+            if (preg_match('~namespace[ \t]+(.*)[ \t]*;~Um', $phpFile->getContents(), $matches)) {
+                if (($namespace = trim($matches[1])) === '') {
+                    continue;
+                }
+
+                if (($pos = strpos($namespace, '\\Entity')) !== false) {
+                    return substr($namespace, 0, $pos + strlen('\\Entity'));
```
Comment (jolelievre) [inline src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: Hmm so you remove a part of the namesapce? I'm not sure to understand it all, because then this namespace is given to doctrine mapping but it's still expecting the folder to be `$moduleFolder . '/src/Entity'` So isn't there a risk that we end up with a namespace that actually doesn't match with this folder?

**Review by jolelievre — CHANGES_REQUESTED** [review]
I'm not blocking for the changes it self, although I have some questions.

But because this should target 9.1 IMHO, this is quite a potentially risky modification, and we're at the boundary between bugfix and feature So 9.1 would probably be safer because we're gonna have a stabilisation period after the beta (which is not so far btw, we're probably gonna create the 9.1.x branch tomorrow, so if it's availablewhen you read this message  target it instead of the develop branch 😉)

File: src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php (hunk 2 above)
Comment (Hlavtox) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: > So isn't there a risk that we end up with a namespace that actually doesn't match with this folder?

I think that would throw an error by itself, it's required by PSR-4 for path and namespace to match no?

Comment (ChillCode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php]: Hi, I think I confused a bit codencode with a POC I shared, sorry, this is my fullcode.

```

    /**
     * Returns a list of DoctrineOrmMappingsPass indexed with their associated src/Entity directory resource.
     *
     * @param array $installedModules
     *
     * @return array<DoctrineOrmMappingsPass>
     */
    private static function getCompilerPassList(array $installedModules, string $modulesDir): array
    {
        $mappingsPassList = [];

        /*
         * Get a list of all directories from installed modules which have src/Entity folder.
         */
        $modulesFoldersWithEntities = Finder::create()->directories()->in($modulesDir)->depth(0)->filter(
            fn (SplFileInfo $moduleFolderWithEntity): bool => in_array($moduleFolderWithEntity->getFilename(), $installedModules) && is_dir($moduleFolderWithEntity->getRealPath() . '/src/Entity')
        );

        foreach ($modulesFoldersWithEntities as $moduleFolderWithEntity) {
            $moduleEntityDirectory = $moduleFolderWithEntity->getRealPath() . '/src/Entity';

            self::removeIndexFiles($moduleEntityDirectory);

            $moduleNamespace = self::getModuleNamespace($moduleEntityDirectory);

            /*
             * User Deprecated: The annotation mapping driver is deprecated and will be removed in Doctrine ORM 3.0,
             * please migrate to the attribute or XML driver.
             *
             * In ORM 3.0, the AttributeDriver will report fields for the classes where they are declared. This may uncover invalid mapping configurations.
             * To opt into the new mode also with the AnnotationDriver today, set the "reportFieldsWhereDeclared" constructor parameter to true.
             */
            $mappingsPassList[$moduleEntityDirectory] = DoctrineOrmMappingsPass::createAnnotationMappingDriver([$moduleNamespace], [$moduleEntityDirectory], [], false, [], false);
        }

        return $mappingsPassList;
    }

    /**
     * This methods aims to get the top namespace of modules entities even if they are not PSR-4 valid.
     *
     * PSR-4 valid module entities can be autoloaded returning an empty string '';
     *
     * This method is required till PrestaShop enforces other mapping methods like PHP or Attributes.
     *
     * Cnc\EntitiesMoreFolders\Entity\Feature\Entity\SubFeature becomes Cnc\EntitiesMoreFolders\Entity
     *
     * @todo Use rector to convert all Annotations to Attributes
     *
     * @param string $moduleEntityDirectory Modules src/Entity path
     *
     * @return string
     */
    private static function getModuleNamespace(string $moduleEntityDirectory): string
    {
        $finder = Finder::create()->files()->in($moduleEntityDirectory)->name('*.php');

        foreach ($finder as $phpFile) {
            if (preg_match('~namespace[ \t]+(.*)[ \t]*;~Um', $phpFile->getContents(), $matches)) {
                if ('' === ($namespace = trim($matches[1]))) {
                    continue;
                }

                if (false !== ($pos = strpos($namespace, '\\Entity'))) {
                    return substr($namespace, 0, $pos + strlen('\\Entity'));
                }

                // Fallback: if for some reason there's no '\Entity', I'll use what was found anyway
                return $namespace;
            }
        }

        return '';
    }
```

This core entity uses subfolders:

/src/PrestaShopBundle/Entity/Employee/Employee.php

So Modules should also allow that, the use of organized entitites, and @Codencode module is PSR-4 compilant, demodoctrine and productcomments are not, and does not matter since we are passing Namespace and Directory to the mapping:

On my code:

`DoctrineOrmMappingsPass::createAnnotationMappingDriver([$moduleNamespace], [$moduleEntityDirectory], [], false, [], false);`

The current code were folder and namespace is mapped togetther:
```

    private function createAnnotationMappingDriver($moduleNamespace, $moduleEntityDirectory)
    {
        $reader = new Reference('annotation_reader');
        $driverDefinition = new Definition('Doctrine\ORM\Mapping\Driver\AnnotationDriver', [$reader, [$moduleEntityDirectory]]);
        $indexFile = $moduleEntityDirectory . '/index.php';
        if (file_exists($indexFile)) {
            $driverDefinition->addMethodCall('addExcludePaths', [[$indexFile]]);
        }

        return new DoctrineOrmMappingsPass($driverDefinition, [$moduleNamespace], [], false, []);
    }
```

Doctrine knows what to map and were to map at this point.

And @Codencode module works without passing namespace, just an empty string, because is PSR-4, demodoctrine and productcomments doing so are not mapped, but no expception is thrown, simply we cannot see them mapped from console.

`DoctrineOrmMappingsPass::createAnnotationMappingDriver([''], [$moduleEntityDirectory], [], false, [], false);`

**Comment by ChillCode** [comment]
Thanks for the PR @Codencode

File: src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: Hmm, so if I understand when the hierarchy respects PSR-4 the configuration is smaller? But when it doesn't we need to specify the folder with the mapping namespace, and we need to do that for all the subfolders?

One thing I don't understand as well is why `productcomments` doesn't respect PSR-4? 🤔
The namesapce is defined on the src folder:
```
"PrestaShop\\Module\\ProductComment\\": "src/"
```
so `PrestaShop\Module\ProductComment\Entity` for the entity folder should be PSR-4 compliant, what am I missing?

Comment (ChillCode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php]: Sorry, I meant is not ORM compilant, check inside the entities and compare with @Codencode module.

Comment (Codencode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: Hi Jonathan, I was waiting for your feedback 😄 
The idea was to retrieve the namespace of the "module", so from the first namespace that the system retrieves for the module, we take the first part and use that. This way, Doctrine will map the entire "Entity" folder of the module.
This, of course, assumes that the module folder containing the entities is named "Entity".

Let me give an example with my module.
The system takes the first available namespace (at least on my Windows PC) as `Cnc\EntitiesMoreFolders\Entity\Category`, so by performing a substring operation, we get `Cnc\EntitiesMoreFolders\Entity`, which is exactly the root namespace. This way, Doctrine will map all the entities in the folder/namespace Cnc\EntitiesMoreFolders\Entity.

My first version of the PR was slightly different. In fact, I created a commit with the code suggested by @ChillCode, who can correct me if I missed something 😄 .

Comment (Codencode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: > Hi, I think I confused a bit codencode with a POC I shared, sorry, this is my fullcode.
> 
> ```
> 
>     /**
>      * Returns a list of DoctrineOrmMappingsPass indexed with their associated src/Entity directory resource.
>      *
>      * @param array $installedModules
>      *
>      * @return array<DoctrineOrmMappingsPass>
>      */
>     private static function getCompilerPassList(array $installedModules, string $modulesDir): array
>     {
>         $mappingsPassList = [];
> 
>         /*
>          * Get a list of all directories from installed modules which have src/Entity folder.
>          */
>         $modulesFoldersWithEntities = Finder::create()->directories()->in($modulesDir)->depth(0)->filter(
>             fn (SplFileInfo $moduleFolderWithEntity): bool => in_array($moduleFolderWithEntity->getFilename(), $installedModules) && is_dir($moduleFolderWithEntity->getRealPath() . '/src/Entity')
>         );
> 
>         foreach ($modulesFoldersWithEntities as $moduleFolderWithEntity) {
>             $moduleEntityDirectory = $moduleFolderWithEntity->getRealPath() . '/src/Entity';
> 
>             self::removeIndexFiles($moduleEntityDirectory);
> 
>             $moduleNamespace = self::getModuleNamespace($moduleEntityDirectory);
> 
>             /*
>              * User Deprecated: The annotation mapping driver is deprecated and will be removed in Doctrine ORM 3.0,
>              * please migrate to the attribute or XML driver.
>              *
>              * In ORM 3.0, the AttributeDriver will report fields for the classes where they are declared. This may uncover invalid mapping configurations.
>              * To opt into the new mode also with the AnnotationDriver today, set the "reportFieldsWhereDeclared" constructor parameter to true.
>              */
>             $mappingsPassList[$moduleEntityDirectory] = DoctrineOrmMappingsPass::createAnnotationMappingDriver([$moduleNamespace], [$moduleEntityDirectory], [], false, [], false);
>         }
> 
>         return $mappingsPassList;
>     }
> 
>     /**
>      * This methods aims to get the top namespace of modules entities even if they are not PSR-4 valid.
>      *
>      * PSR-4 valid module entities can be autoloaded returning an empty string '';
>      *
>      * This method is required till PrestaShop enforces other mapping methods like PHP or Attributes.
>      *
>      * Cnc\EntitiesMoreFolders\Entity\Feature\Entity\SubFeature becomes Cnc\EntitiesMoreFolders\Entity
>      *
>      * @todo Use rector to convert all Annotations to Attributes
>      *
>      * @param string $moduleEntityDirectory Modules src/Entity path
>      *
>      * @return string
>      */
>     private static function getModuleNamespace(string $moduleEntityDirectory): string
>     {
>         $finder = Finder::create()->files()->in($moduleEntityDirectory)->name('*.php');
> 
>         foreach ($finder as $phpFile) {
>             if (preg_match('~namespace[ \t]+(.*)[ \t]*;~Um', $phpFile->getContents(), $matches)) {
>                 if ('' === ($namespace = trim($matches[1]))) {
>                     continue;
>                 }
> 
>                 if (false !== ($pos = strpos($namespace, '\\Entity'))) {
>                     return substr($namespace, 0, $pos + strlen('\\Entity'));
>                 }
> 
>                 // Fallback: if for some reason there's no '\Entity', I'll use what was found anyway
>                 return $namespace;
>             }
>         }
> 
>         return '';
>     }
> ```
> 
> This core entity uses subfolders:
> 
> /src/PrestaShopBundle/Entity/Employee/Employee.php
> 
> So Modules should also allow that, the use of organized entitites, and @Codencode module is PSR-4 compilant, demodoctrine and productcomments are not, and does not matter since we are passing Namespace and Directory to the mapping:
> 
> On my code:
> 
> `DoctrineOrmMappingsPass::createAnnotationMappingDriver([$moduleNamespace], [$moduleEntityDirectory], [], false, [], false);`
> 
> The current code were folder and namespace is mapped togetther:
> 
> ```
> 
>     private function createAnnotationMappingDriver($moduleNamespace, $moduleEntityDirectory)
>     {
>         $reader = new Reference('annotation_reader');
>         $driverDefinition = new Definition('Doctrine\ORM\Mapping\Driver\AnnotationDriver', [$reader, [$moduleEntityDirectory]]);
>         $indexFile = $moduleEntityDirectory . '/index.php';
>         if (file_exists($indexFile)) {
>             $driverDefinition->addMethodCall('addExcludePaths', [[$indexFile]]);
>         }
> 
>         return new DoctrineOrmMappingsPass($driverDefinition, [$moduleNamespace], [], false, []);
>     }
> ```
> 
> Doctrine knows what to map and were to map at this point.
> 
> And @Codencode module works without passing namespace, just an empty string, because is PSR-4, demodoctrine and productcomments doing so are not mapped, but no exception is thrown, simply we cannot see them mapped from console.
> 
> `DoctrineOrmMappingsPass::createAnnotationMappingDriver([''], [$moduleEntityDirectory], [], false, [], false);`

@ChillCode, sorry, I didn't understand what you meant with this comment. Are you suggesting a change?
Sorry, but my English isn't the best 😅.

Comment (ChillCode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: Hi @Codencode 

Your entities are fully ORM-compliant. They only need to be located in the correct directory for Doctrine to pick them up. Once you apply that small change, the site continues to work normally. However, when you debug Doctrine using the doctrine:mapping:info console command, you will see that your entities are mapped correctly, while productcomments and demodoctrine are not. The reason is that those classes are missing the required ORM attributes.

This is exactly how I discovered the issue. My own entities were not ORM-compliant either, so I started investigating. Eventually, I refactored the class because the PrestaShopExtension performs several preprocessing steps: it registers the entities as resources, removes the index.php files, and so on. I observed this while debugging the container, focusing first on the Doctrine portion. That is also where I noticed a duplicated resource. The final outcome is reflected in my code:

https://gist.github.com/ChillCode/b43f72485fdc1fbc3cd1637456d1509d

I passed the text to AI so is more clear.

What I wanted to try but did not, is to map everything with it's full Namespace and Directory instead of the return.

Comment (ChillCode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php]: That's one of the reasons of starting the refactor of module entities mapping:

https://github.com/PrestaShop/PrestaShop/blob/1e10168a359c09bbf148f166f2b2ac82e20915b7/src/PrestaShopBundle/DependencyInjection/PrestaShopExtension.php#L128-L166

Duplicate logic, this extension removes and add resources, then module doctrine pass , tries to ignore index.php with a method implemented for this reason and adds the resoruces again.

I also tried using reflection, but was not better than a regex, so my last take was to convert all to Attributes and don't lose time because sure you're gonna solve this and take the big picture.

As you see I only add resources if they don't exists since I found the disparity of loading installed in one side and active in the api side, too many things to remember.

Comment (Codencode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: @ChillCode I also tried with the CLI and the `doctrine:mapping:info` command; it correctly returns the entities from the **productcomment** module for me. However, I noticed that it's not mapping entities from another module (basically what's happening to you with productcomment)!

I looked into it more deeply and realized that in this module where entities are not being mapped, the problem is that within `src` there are both a `Controller` and an `Entity` folder, so we have:
- src/Controller
- src/Entity

Therefore, when the system creates the entity mapping, in this case it retrieves the namespace from the `src/Controller` folder, which throws everything off.

In light of all this, I believe the issue is not related to missing ORM attributes (i.e., not being ORM compliant), but rather a problem with the order of filesystem paths in the OS. I am actually working on Windows.

To test this, I made a modification, specifically to the `getModuleNamespace()` method:
```php
    private function getModuleNamespace(SplFileInfo $moduleFolder)
    {
        // I force the check in the src/Entity folder of the module.
        $entityDir = $moduleFolder->getPathname() . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'Entity';

        $finder = new Finder();
        $finder->files()->in($entityDir)->name('*.php');

        foreach ($finder as $phpFile) {
            if (preg_match('~namespace[ \t]+(.*)[ \t]*;~Um', $phpFile->getContents(), $matches)) {
                if (($namespace = trim($matches[1])) === '') {
                    continue;
                }

                if (($pos = strpos($namespace, '\\Entity')) !== false) {
                    return substr($namespace, 0, $pos + strlen('\\Entity'));
                }

                // Fallback: if for some reason there's no '\Entity', I'll use what was found anyway
                return $namespace;
            }
        }

        return '';
    }
```
Essentially, I force the scan of the src\Entity folder of the module because that's where the entities should be.

Can you also try a test with this modified code and verify what the `doctrine:mapping:info` command returns?

I hope I have been clear in my explanation.

Thanks

Comment (ChillCode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php]: The conclusion that is ORM compilant I got when I followed the code till this is ignored, but meaby I'm wrong, also not an expert and forget many things the next day, so at the end only the code and comments are left.

And really feel bad for my distraction, your inital PR solved the issue as it should, but always I like to clean the code and remove unnecesary walks etc...

Comment (Codencode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: @ChillCode I tried with the initial PR, specifically this commit: https://github.com/PrestaShop/PrestaShop/pull/40094/changes/144d8c376d25c3895f3633ea248251fe73dc2b0b

I made the same modification to the `createAnnotationMappingDriver()` method as you did. However, in this case, the `doctrine:mapping:info` command did not map my entities at all. Maybe I missed something?

But you conducted this test: https://github.com/PrestaShop/PrestaShop/pull/40094#discussion_r2613821289
What result did you get?

However, I will now apply the modification to this PR, because indeed, for this PR, it is necessary.

Comment (Codencode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:137]: @ChillCode @jolelievre
I've created a new commit (this way we have a trace of the previous changes).

As you can see, I've directly passed the path as a string to the method, instead of using SplFileInfo. This is to avoid doing concatenations twice, because in my opinion, we should specifically look in the `src/Entity` folder.

Furthermore, in the `getCompilerPassList()` method, there was a variable `$modulePrefix` that wasn't being used, so I removed it.

Yes, I changed the parameter type, but this shouldn't cause any backward compatibility issues since the method is private and only used within this class. Also, it's worth mentioning that this PR will need to be moved to a different branch. So @jolelievre, I haven't performed the rebase to change branches yet, but I will.

What are your thoughts?

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop`, `9.0.x` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Codencode** [comment]
@jolelievre I performed the rebase, so now the PR points to the 9.1.x branch, as you suggested.
I await your feedback.

Thank you.

**Review by SiraDIOP — COMMENTED** [review]
Hello @Codencode, 

Thanks for your PR, but i have a question : Is it normal that the PR is not reviewed even though it is waiting for QA? Is there a problem with the PR?

Thanks

**Comment by Codencode** [comment]
Hello @SiraDIOP, I believe the issue arose because it had been approved, but subsequently @jolelievre asked me to rebase it to target the 9.1.x branch.
I think Jonathan will let us know when he has a moment.
For now, I have removed the "Waiting for QA" label.

Thank you!

File: src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php [hunk 3]
```diff
@@ -113,18 +114,27 @@ private function createAnnotationMappingDriver($moduleNamespace, $moduleEntityDi
...
         foreach ($finder as $phpFile) {
-            $phpContent = file_get_contents($phpFile->getRealPath());
-            if (preg_match('~namespace[ \t]+(.+)[ \t]*;~Um', $phpContent, $matches)) {
-                return $matches[1];
+            if (preg_match('~namespace[ \t]+(.*)[ \t]*;~Um', $phpFile->getContents(), $matches)) {
+                if (($namespace = trim($matches[1])) === '') {
+                    continue;
+                }
+
+                if (($pos = strpos($namespace, '\\Entity')) !== false) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:136]: The logic seems good, you should add a comment here to explain what you do like
```suggestion
                // We strip the last part of the namespace to get the namespace matching with the entity folder
                // This is required in case you have sub-folders like src/Entity/Category/Category.php
                // The first matching PHP file would be in a sub namespace and be returned, thus the Entity
                // namespace would not be parsed completely
                if (($pos = strpos($namespace, '\\Entity')) !== false) {
```

**Review by jolelievre — COMMENTED** [review]
@Codencode just one comment

Regarding the branch I'm not sure, adding this to 9.0.x could be nice but we're about to release the (probably) last patch of the 9.0 soon and this fix will likely not have time to be included in it

So keeping 9.1.x is probably fine, this way the modification will only impact the 9.1 in case we find a bug and it has a bit more time to be fixed with the stabilisation phase

File: src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php (hunk 3 above)
Comment (Codencode) [reply src/PrestaShopBundle/DependencyInjection/Compiler/ModulesDoctrineCompilerPass.php:136]: @jolelievre done

**Comment by Codencode** [comment]
> @Codencode just one comment
> 
> Regarding the branch I'm not sure, adding this to 9.0.x could be nice but we're about to release the (probably) last patch of the 9.0 soon and this fix will likely not have time to be included in it
> 
> So keeping 9.1.x is probably fine, this way the modification will only impact the 9.1 in case we find a bug and it has a bit more time to be fixed with the stabilisation phase

@jolelievre initially I had targeted the 9.0.x branch, but you had suggested targeting the 9.1.x branch instead, so I did.
In my opinion, the 9.1.x branch is more appropriate precisely for the reasons you mentioned.
I also added the comment in the code.

So whenever you want, and if you think it's appropriate, you can "unblock" the PR.

As always, thanks for your feedback

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@jolelievre 

> last patch of the 9.0 soon

9.0 is maybe finally ready for production with 9.0.3 and it's already a last patch? You can't be serious…

So, you release 9.1, probably full of issues (that's normal), and we will have to wait again to have something ready?

cc @cnavarro-prestashop

**Comment by kpodemski** [comment]
@Hlavtox 

`9.1.x` includes all bug fixes from `9.0.x` and follows the regular release cycle we've been following for some time. I don't see a reason to change that. We release `9.1.0`, and we stop supporting `9.0.x`. It was the same with PrestaShop 8.1: there were 7 patch versions for `8.1`, but the pace of releasing another minor version was a bit different.

Considering the main additions to 9.1 are isolated, it should be all good.

Of course, there are some subjects we've already discussed, like data migration between what's old (cart rules, carriers) and what's new (discounts, multi-shipment). That has to be addressed, and there's still some time to do so.

Let's also remember that patch versions will be more regular now, around every 6 weeks.

**Comment by Hlavtox** [comment]
@kpodemski I know how it works, but try to look at it from a human level. :-)

I am now running dozens of stores on 8.2.3, old version, old symfony, old PHP. I invested a lot of time into 9.0 to make it awesome. It has still some crucial issues that need to be addressed, like the availability thing now, before it can be ready.

And I impatiently waiting for the moment I can finally upgrade and modernize the shops by X years.

And if the patches for 9.0 stop suddenly, with the software not ready for production, it starts again, and nothing gets upgraded.

**Comment by Codencode** [comment]
Ping @jolelievre

**Comment by jolelievre** [comment]
@Hlavtox, regardless of your frustration, which I can partially understand, there's a reality you have to accept We can't maintain three versions in parallel. So when a new minor is released, it automatically means the end of the previous version's maintenance

It's not really something new, besides as @kpodemski explained, all the fixes and improvements of the 9.0 are by definition included in the 9.1, so your efforts are not wasted since 9.1 is at least as good as the 9.0

**Review by jolelievre — APPROVED** [review]
Thanks @Codencode

**Review by SiraDIOP — COMMENTED** [review]
Hello @Codencode, 

Thanks for your PR, i tested it and it's good for me :) 

Image

I'm waiting automated tests to approve the PR.
Thanks

**Comment by Codencode** [comment]
Hello @SiraDIOP, I noticed that all your UI tests were stuck, so I started them myself.
Let's wait for the outcome.
Thank you!

**Comment by Codencode** [comment]
@SiraDIOP UI test are 🟢

**Review by SiraDIOP — APPROVED** [review]
