### PR TITLE
In dev mode, hooks must not swallow exceptions

### LINKED ISSUE #24984: In dev mode, an Exception in a hook must not be ignored silently
#### Describe the bug

While developing a module, I noticed, that Exceptions thrown in certain hooks are completely ignored. In this cas the hook configuration just has no effect. `displayProductExtraContent` is one of the hooks that swallows exceptions.

#### Expected behavior

I expect in dev mode to be notified when Exceptions occur. Otherwise, debugging is very difficult.
In production mode, exceptions in hook must be swallowed though to keep backwards compatibility, because we can expect existing modules with bugs in hook, that were hidden due to hook swallowing exceptions.

#### Steps to Reproduce

1. Add `throw new Exception('Test');` in the `displayProductExtraContent` hook of a module.
2. Notice, that this Exception has no effect in dev mode when displaying a product page.

#### Additional information

I discussed this issue on slack with @tswfi and @jolelievre.

* PrestaShop version: 1.7.7.x, 1.7.8.x
* PHP version: any

### LINKED ISSUE #25002: Improper use of `defined` to check for a constant
#### Describe the bug

`defined(_CONSTANT_)` is wrong. Quotes are not optional.

    var_dump(defined('_CONSTANT_'));  // false
    var_dump(defined(_CONSTANT_));  // false
    define('_CONSTANT_', true);
    var_dump(defined('_CONSTANT_'));  // true
    var_dump(defined(_CONSTANT_));  // false (INCORRECT)
    // Warning:  Use of undefined constant _CONSTANT_ - assumed '_CONSTANT_' (this will throw an Error in a future version of PHP)

#### Expected behavior

The PHP function `defined()` should always be used with quotes when testing for a literal constant.

#### Additional information

This error occurs 6 times in `Prestashop/Prestashop`, and once in `Prestashop/pagesnotfound`.
Two occurrences in `Prestashop/Prestashop` fixed in #24985
Four occurrences in `Prestashop/Prestashop` fixed in #25003 
Occurrence in `Prestashop/pagesnotfound` fixed in https://github.com/PrestaShop/pagesnotfound/pull/15#issue-672656650

* PrestaShop version: develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In dev mode, exceptions that are thrown in hooks should be displayed. In production mode, they should be silently swalowed. Displaying exceptions instead of swallowing enhances development experience. 
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no. In production mode, we continue to swallow exceptions. We expect that existing modules rely on the fact that exceptions are swallowed. Changing this would break BC.
| Deprecations?     | no
| Fixed ticket?     | Fixes #24984., partially fixes #25002
| How to test?      | In a module implementing the hook `displayProductExtraContent` throw an exception. Navigate to a product page. In dev environment, the exception must display. In production environment, the page must display normally.
| Possible impacts? | None.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24985)

### How to test

Using the `ps_qualityassurance` module, register on the `displayProductExtraContent` hook and in the code throw an exception with this code: `throw new \Exception('blocking error');`

Then go to the product page to test it:
- without the PR the exception is never seen whether you are in dev mode or not
- with this PR in prod mode nothing happens, in dev mode, you should have an error page

### CODE REVIEW

File: src/Adapter/HookManager.php [hunk 1]
```diff
@@ -45,9 +46,15 @@ class HookManager
      * @param bool $use_push Force change to be refreshed on Dashboard widgets
      * @param int $id_shop If specified, hook will be execute the shop with this ID
      *
+<<<<<<< HEAD
```
Comment (PierreRambaud) [inline src/Adapter/HookManager.php]: Wrong merge I think :sweat:

Comment (lmeyer1) [reply src/Adapter/HookManager.php]: Sorry, I saw it instantly, but too late.

**Comment by lmeyer1** [comment]
@jolelievre
PHPstan thinks `if (_PS_MODE_DEV_) {` is always true.
Should I test for dev mode differently, or should I add `// @phpstan-ignore-line` (see https://phpstan.org/user-guide/ignoring-errors)?

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @lmeyer1

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please use `prestashop.adapter.environment` service instead the const.

**Comment by lmeyer1** [comment]
@PierreRambaud 
While using `(new Environment())->isDebug()` I found a bug in the `Environment` class. I fixed it at the same time.
Shouldn't an obvious error like `defined(_PS_MODE_DEV_)` instead of `defined('_PS_MODE_DEV_')` (missing quotes) throw an error in phpstan?

**Review by PierreRambaud — DISMISSED** [review]

File: src/Adapter/HookManager.php [hunk 2]
```diff
@@ -80,6 +81,9 @@ public function exec(
             } catch (\Exception $e) {
                 $logger = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Adapter\\LegacyLogger');
                 $logger->error(sprintf('Exception on hook %s for module %s. %s', $hook_name, $id_module, $e->getMessage()), ['object_type' => 'Module', 'object_id' => $id_module, 'allow_duplicate' => true]);
+                if ((new Environment())->isDebug()) {
```
Comment (Progi1984) [inline src/Adapter/HookManager.php]: Isn't it possible to pass it to constructor ?

Like here : https://github.com/PrestaShop/PrestaShop/blob/ad181f7fb89dea67dfebba779a6440854baa6d5b/src/PrestaShopBundle/Resources/config/services/adapter/data_configuration.yml#L82

**Review by Progi1984 — COMMENTED** [review]
A last feedback

File: src/Adapter/HookManager.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/HookManager.php]: There are two possibilities actually, either inject the `prestashop.adapter.environment` service into the HookManager or the boolean directly Both are valid choices

Comment (jolelievre) [reply src/Adapter/HookManager.php]: By the way @lmeyer1 if you're not used to Symfony services or dependency injection here's a link to the Symfony documentation that might help you https://symfony.com/doc/3.4/service_container.html#explicitly-configuring-services-and-arguments

Comment (PierreRambaud) [reply src/Adapter/HookManager.php]: You can't use HookManager as a service, it's instantiate manually. But you're right, since Symfony Container is used in this file, you can reach the `prestashop.adapter.environment` service instead of creating a new instance of Environement :+1:

Comment (lmeyer1) [reply src/Adapter/HookManager.php]: @PierreRambaud 
Do you mean using `ServiceLocator` ? Like

    $env = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Adapter\\Environment');

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/HookManager.php [hunk 3]
```diff
@@ -79,7 +80,11 @@ public function exec(
                 return Hook::exec($hook_name, $hook_args, $id_module, $array_return, $check_exceptions, $use_push, $id_shop);
             } catch (\Exception $e) {
                 $logger = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Adapter\\LegacyLogger');
+                $environment = ServiceLocator::get('\\PrestaShop\\PrestaShop\\Adapter\\Environment');
```
Comment (jolelievre) [inline src/Adapter/HookManager.php:83]: Oh right this is the old system of DI that was implemented in the early 1.7 versions ^^
We'll need to replace this with Symfony DI in the next major version, but it's not your job here 😉

**Review by jolelievre — DISMISSED** [review]
Nice job @lmeyer1

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
@lmeyer1 I tested your PR and I realized that performing this check in `HookManager` alone was not enough, because it's not used everywhere Particularly for display hooks

So I added the same principle further in the legacy `Hook` class so that it's the same everywhere, this seems to work fine

I'll wait for a re-approval of other maintainers though before we merge this one.

File: classes/Hook.php [hunk 4]
```diff
@@ -1004,7 +1014,16 @@ public static function coreRenderWidget($module, $hook_name, $params)
             return null;
         }
 
-        return $module->renderWidget($hook_name, $params);
+        try {
+            return $module->renderWidget($hook_name, $params);
+        } catch (\Exception $e) {
```
Comment (kpodemski) [inline classes/Hook.php]:
```suggestion
        } catch (Exception $e) {
```

there's no need to use `\` right?

Comment (Progi1984) [reply classes/Hook.php]: @lmeyer1 A small fix and we merge.

**Review by Progi1984 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @lmeyer1 & @jolelievre
