### PR TITLE
Fix FO address forms reload when switching address's country

### LINKED ISSUE #28781: [FO] - States field is not displayed anymore
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In FO, during checkout process I can't choose the State.

In PS 1.7.8.x ✅ 
Screenshot 2022-06-17 at 14 45 23

In 8.0.x ❌ 
Screenshot 2022-06-17 at 14 46 31

In the address, the configuration is correct : 
Screenshot 2022-06-17 at 15 46 07

### Expected behavior

I should be able to choose the State of my address

### Steps to reproduce

- Go to BO > International > Location > Countries > Enable United States
- Check in States if Unites States are all enabled
- Go to FO > Checkout > On Addresses Step > Choose Country : United States
- No State field. You should be able to choose your state

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #29012: FO - An exception is displayed when creating an address with italian country
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Could be related to https://github.com/PrestaShop/PrestaShop/issues/28781
In the FO > When we try to create an address with an Italian country, an exception is displayed
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > International > Localization page & Import the italian pack
2. Go to BO > International > Locations > Countries tab & edit the Italian country
3. Enable `Do you need a tax identification number?` and save
4. Go to BO > Addresses page
5. Select dni as a required field
6. Go to FO > Create an address with the Italian country
7. See error 
8. Go to FO > Add a product to the cart and proceed to checkout
9. In the Addresses tab, create an address with the Italian country
10. See error

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2, 7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by yanmakouf**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fixes the address form reload after switching country of the adrdress, updates properly the form fields.
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Resolves #29012, resolves #28781
| Related PRs       | N/A
| How to test?      | 1)Go to BO > International > Localization page & Import the italian pack 2) Go to BO > International > Locations > Countries tab & edit the Italian country 3) Enable "Do you need a tax identification number?" and save 4) Go to BO > Addresses page 5) Select dni as a required field 6) Go to FO > Create an address with the Italian country 7) See NO error 8) Go to FO > Add a product to the cart and proceed to checkout 9) In the Addresses tab, create an address with the Italian country 10) See NO error
| Possible impacts? | Check that #18008 still working

### CODE REVIEW

**Review by Amoifr — COMMENTED** [review]
As we discuss, I introduce this dimension in a previous PR but may be the order of the conditions is wrong.
So ping someone the product to get priorities between the 2 sources, and I also will be good to have a test that translate the product expectation. (It seems that I didn't apply it to myself in the past)

**Comment by yanmakouf** [comment]
> As we discuss, I introduce this dimension in a previous PR but may be the order of the conditions is wrong. So ping someone the product to get priorities between the 2 sources, and I also will be good to have a test that translate the product expectation. (It seems that I didn't apply it to myself in the past)

Discussed it with @eshraw. We agreed that there's two cases. 1) It is the first address add.. 2) User already registered an address.

Case 1) 
- Check browser language, if browser language matches an enabled pack (set in BO) use this as the default select country field value
- if not matches or no language set in browser, use BO defined default country value.
- If user changes values of the select country field => reload form with this country's adresse format (cf #28781 )

Case 2) 
- Use this country as the default value of select country field
- If user changes values of the select country field => reload form with this country's adresse format

@eshraw right ? ^^

File: classes/form/CustomerAddressForm.php [hunk 1]
```diff
@@ -92,23 +92,27 @@ public function loadAddressById($id_address)
...
+        // Country preselection priority order :
+        // 1) Update the format if a new id_country was set.
+        // 2) Detect country from browser language settings and matches BO enabled countries
+        // 3) Default country set in BO
+        if (isset($params['id_country']) && $params['id_country'] != $this->formatter->getCountry()->id) {
+            $this->formatter->setCountry(
+                new Country($params['id_country'], $this->language->id)
+            );
+        } elseif (Tools::isCountryFromBrowserAvailable() && Country::getByIso(Tools::getCountryIsoCodeFromHeader(), true)) {
             $languageAvailable = Tools::getCountryIsoCodeFromHeader();
```
Comment (zuk3975) [inline classes/form/CustomerAddressForm.php]: could we use this occasion to rename this variable?
I would say `$countryIsoCode` would reflect the value much better.

Comment (yanmakouf) [reply classes/form/CustomerAddressForm.php]: Agreed

File: classes/form/CustomerAddressForm.php [hunk 2]
```diff
@@ -92,23 +92,29 @@ public function loadAddressById($id_address)
...
-                (int) Country::getByIso($languageAvailable, true),
-                Language::getIdByIso($languageAvailable)
-            ));
-        } elseif (isset($params['id_country'])
-            && $params['id_country'] != $this->formatter->getCountry()->id
+        // This form is tricky: fields may change depending on which country is being selected!
+        // Country preselection priority order :
+        // 1) Update the format if a new id_country was set.
+        // 2) Detect country from browser language settings and matches BO enabled countries
+        // 3) Default country set in BO
```
Comment (MeKeyCool) [inline classes/form/CustomerAddressForm.php:99]: I like this kind of enhancement of comments ^^

File: classes/form/CustomerAddressForm.php [hunk 3]
```diff
@@ -92,23 +92,29 @@ public function loadAddressById($id_address)
...
+        if (isset($params['id_country']) && $params['id_country'] != $this->formatter->getCountry()->id) {
+            $this->formatter->setCountry(
+                new Country($params['id_country'], $this->language->id)
+            );
+        } elseif (
+            Tools::isCountryFromBrowserAvailable() &&
+            Country::getByIso($countryIsoCode = Tools::getCountryIsoCodeFromHeader(), true)
```
Comment (MeKeyCool) [inline classes/form/CustomerAddressForm.php:105]: I think it is confusing to add variable declaration inside a function call inside a elseif test ^^'

**Review by MeKeyCool — DISMISSED** [review]

File: classes/form/CustomerAddressForm.php (hunk 3 above)
Comment (yanmakouf) [reply classes/form/CustomerAddressForm.php:105]: I understand how it can be confusing. Still to me it is a valid syntax. And in this case we don't need to initiate a variable if the condition is not met. Vote ? 😇

Comment (MeKeyCool) [reply classes/form/CustomerAddressForm.php:105]: I made a free comment, feel free to change or not ;)

File: classes/form/CustomerAddressForm.php [hunk 4]
```diff
@@ -92,23 +92,29 @@ public function loadAddressById($id_address)
...
-                Language::getIdByIso($languageAvailable)
-            ));
-        } elseif (isset($params['id_country'])
-            && $params['id_country'] != $this->formatter->getCountry()->id
+        // This form is tricky: fields may change depending on which country is being selected!
+        // Country preselection priority order :
+        // 1) Update the format if a new id_country was set.
+        // 2) Detect country from browser language settings and matches BO enabled countries
+        // 3) Default country set in BO
+        if (isset($params['id_country']) && $params['id_country'] != $this->formatter->getCountry()->id) {
```
Comment (zuk3975) [inline classes/form/CustomerAddressForm.php]: I think we should use strict comparisons everywhere :thinking: 
```suggestion
        if (isset($params['id_country']) && (int) $params['id_country'] !== (int) $this->formatter->getCountry()->id) {
```

Comment (yanmakouf) [reply classes/form/CustomerAddressForm.php]: I agree. This is a mistake on my side thanks for pointing it out !

**Review by MeKeyCool — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by matks — APPROVED** [review]

File: classes/form/CustomerAddressForm.php [hunk 5]
```diff
@@ -92,25 +92,25 @@ public function loadAddressById($id_address)
...
+        // Country preselection priority order :
+        // 1) Update the format if a new id_country was set.
+        // 2) Detect country from browser language settings and matches BO enabled countries
+        // 3) Default country set in BO
+
+        if (isset($params['id_country']) && (int) $params['id_country'] !== (int) $this->formatter->getCountry()->id) {
+            $country = new Country($params['id_country'], $this->language->id);
+        } elseif (
+            Tools::isCountryFromBrowserAvailable() &&
+            Country::getByIso($countryIsoCode = Tools::getCountryIsoCodeFromHeader(), true)
```
Comment (jolelievre) [inline classes/form/CustomerAddressForm.php:105]: I won't block the PR since it's already been approved and is waiting for QA but the assignment of `$countryIsoCode` is not really a good practice IMHO

It hides the affectation and makes the code less human readable, thus harder to maintain, this should be "split" inside an `else` statement where we assign $countryIsoCode explicitly and then perform the check The logic is good it's just the way code is written which is confusing to me

Comment (yanmakouf) [reply classes/form/CustomerAddressForm.php:105]: I think @MeKeyCool made the same comment.I get how it can be confusing and as you said maybe less human firendly :P I'll keep it in my mind for future developments

**Review by sLorenzini — APPROVED** [review]
hello @yanmakouf,

Thank you for this PR.

Tested on 8.0.x branch with PHP 7.3 version.
Tested with 2 countries. The state field is well displayed on:
- customer account, addresses tab by adding a new one
- checkout in step addresses by adding a new one

See screenrecord:

https://user-images.githubusercontent.com/2854834/187653877-8bc3bb29-3cdc-4b32-bd24-86808c5726e2.mp4

QA approved ✅ 

Thank you

**Comment by jolelievre** [comment]
Thanks @sLorenzini and @yanmakouf
