### PR TITLE
Replace exception message by custom message on invalid avatar on employee page

### LINKED ISSUE #28985: BO - Employees page - an exception is displayed when we try to add an invalid avatar
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related to https://github.com/PrestaShop/PrestaShop/issues/28253, https://github.com/PrestaShop/PrestaShop/issues/28484
In the BO > Team > Employees page, an exception is displayed when we add an invalid avatar (SVG, mp4,...)
image

### Expected behavior

When user hits "save" an error should be displayed to tell user that only some image files (list to be defined) are accepted as avatar. Trying to submit files such as SVG or MP4 should trigger a form invalidation error.

Error message should be something

### Steps to reproduce

1. Go to BO > Team > Employees page
2. Add/Edit an employee
3. Add an invalid avatar (SVG, ...)
4. Save
5. See an error

### PrestaShop version(s) where the bug happened

1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  1.7.8.x
| Description?      | Add custom message instead of exception message when uploading avatar with invalid extension
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes #28985
| Related PRs       | 
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/28985
| Possible impacts? |

### CODE REVIEW

**Review by matks — DISMISSED** [review]
OK for me. @Julievrz will tell us if the wording is good 👍

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 1]
```diff
@@ -478,6 +479,10 @@ protected function getEmployeeFormHandler()
     protected function getErrorMessages(Exception $e)
     {
         return [
+            UploadedImageConstraintException::class => $this->trans(
+                'The file extension for the avatar is not supported. Valid ones are: gif, jpg, jpeg, jpe, png, webp.',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: We could use the existing string: 'Image format not recognized, allowed formats are: %s'
in Admin.Notifications.Error

Comment (lartist) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: Ok

**Review by matthieu-rolland — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 2]
```diff
@@ -478,6 +479,10 @@ protected function getEmployeeFormHandler()
     protected function getErrorMessages(Exception $e)
     {
         return [
+            UploadedImageConstraintException::class => $this->trans(
+                'Image format not recognized, allowed formats are: %s',
+                'Admin.Notifications.Error'
```
Comment (atomiix) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: You have to pass the string that will replace the `%s` as third argument in an array ;)
```suggestion
                'Admin.Notifications.Error',
                ['gif, jpg, jpeg, jpe, png, webp.']
```

**Review by atomiix — CHANGES_REQUESTED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @lartist

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 3]
```diff
@@ -478,6 +480,13 @@ protected function getEmployeeFormHandler()
     protected function getErrorMessages(Exception $e)
     {
         return [
+            UploadedImageConstraintException::class => $this->trans(
+                'Image format not recognized, allowed formats are: %s',
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php:484]:
```suggestion
                'Image format not recognized, allowed format(s) is(are): .%s',
```

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php:484]: Actually I just checked, this is the wording that is in the catalog, the one suggested before doesn't exist

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php (hunk 3 above)
Comment (Julievrz) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php:484]: image

Comment (Julievrz) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php:484]: @jolelievre Are you sure?

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php:484]: You're right @Julievrz I found `Image format not recognized, allowed formats are: %s` now I guess my catalog were not up-to-date when I searched it, sorry!

**Review by jolelievre — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 4]
```diff
@@ -481,7 +481,7 @@ protected function getErrorMessages(Exception $e)
     {
         return [
             UploadedImageConstraintException::class => $this->trans(
-                'Image format not recognized, allowed formats are: %s',
+                'Image format not recognized, allowed format(s) is(are): .%s',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: Image format not recognized, allowed formats are: %s

@l-delin I'll let you follow up on this one. :) Thanks

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 5]
```diff
@@ -478,6 +480,13 @@ protected function getEmployeeFormHandler()
     protected function getErrorMessages(Exception $e)
     {
         return [
+            UploadedImageConstraintException::class => $this->trans(
+                'Image format not recognized, allowed format(s) is(are): .%s',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]:
```suggestion
                'Image format not recognized, allowed formats are: %s',
```

**Review by matks — COMMENTED** [review]
@lartist you got some feedback from wording managers :) we can improve the wordings some more

**Review by jolelievre — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 6]
```diff
@@ -478,6 +480,13 @@ protected function getEmployeeFormHandler()
     protected function getErrorMessages(Exception $e)
     {
         return [
+            UploadedImageConstraintException::class => $this->trans(
+                'Image format not recognized, allowed formats are: %s',
+                'Admin.Notifications.Error',
+                [
+                    implode(', ', ImageManagerCore::MIME_TYPE_SUPPORTED),
```
Comment (atomiix) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: I think it might be better to use the class `ImageManager` instead of `ImageManagerCore` so if there's a `ImageManager` override that adds/removes a mime type, this wording could be updated as well
```suggestion
                    implode(', ', ImageManager::MIME_TYPE_SUPPORTED),
```

Comment (lartist) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: Seems like a good idea @atomiix. I'll take care of it

Comment (lartist) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: I squash commits because 7 commits just to a an error message sound's a little bit too much :)

**Review by atomiix — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @lartist ,

I tested your PR and the error message is well fixed :tada: 

Here is my checked list :

- Check with different languages: OK
- Check with different format : 
      1.  CSV
      2. SVG
      3. MP4
      4. MP3
      5. WEBM
      6. PDF
- Check with different browsers: OK
- Check the automated tests: OK

image (6)

Many thanks :smile:

**Comment by atomiix** [comment]
Thanks @lartist !
