### PR TITLE
Fix html being displayed in download virtual product text mail

### LINKED ISSUE #10915: Display issue in virtual product email
**Describe the bug**
Some html tags are displayed in email when you order virutal product

**To Reproduce**
1. Go to advanced parameters > Email and choose Send email in text format
2. Make sure you receive email (test it)
3. Go to Catalog > Product
4. Create a new virual product with a file
4. Order this product
5. Put the order in "payment accepted" status
6. See the txt email sent 

**Screenshots**

46542475-cb99dd00-c8be-11e8-932e-13fb208dacc0

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | uses partial mail to render text/html list of downloadable virtual products in the download product mail
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10915
| How to test?  | Order a virtual product with a file and see the text mail sent

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16014)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

File: classes/order/OrderHistory.php [hunk 1]
```diff
@@ -615,4 +627,47 @@ public function addWs()
...
+        }
+
+        if (!isset($this->context)) {
+            $this->context = Context::getContext();
+        }
+
+        $content = $this->getPartialRenderer()->render($template_name, $this->context->language, $var);
+        if ($mail_type == Mail::TYPE_TEXT) {
+            // delete html comments in text mode so it's not visible in the mail
+            $content = preg_replace('/\n?<!--.*-->\n?/i', '', $content);
```
Comment (PierreRambaud) [inline classes/order/OrderHistory.php]: Maybe any spaces types? Don't know if all templates contains only `\n` notations, or if a developer add an email created on Mac / Windows.
Add global and dot can match new lines with ungreedy notation
for this kind of comments:
```html
<!-- blyat -->
<p>Htmlcontent</p>
<!-- 
test 
-->
```

```suggestion
            $content = preg_replace('/\s?<!--.*?-->\s?/gs', '', $content);
```

File: mails/themes/classic/core/download_product.html.twig [hunk 2]
```diff
@@ -24,11 +24,16 @@
...
-            
+
 {% endif %}
             <span>
               {{ 'You have [1]{nbProducts}[/1] product(s) now available for download using the following link(s):'|trans({'[1]': '<span><strong>', '[/1]': '</strong></span>'}, 'Emails.Body', locale)|raw }}<br/><br/>
-              {virtualProducts}
+              {% if templateType == 'html' %}
+                {virtualProducts}
+              {% endif %}
+              {% if templateType == 'txt' %}
```
Comment (PierreRambaud) [inline mails/themes/classic/core/download_product.html.twig:34]: elseif instead

File: mails/themes/modern/core/download_product.html.twig [hunk 3]
```diff
@@ -259,7 +259,14 @@
                                     </tr>
                                     <tr>
                                       <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
-                                        <div style="font-family:Open sans, arial, sans-serif;font-size:14px;line-height:25px;text-align:left;color:#363A41;"> {virtualProducts} </div>
+                                        <div style="font-family:Open sans, arial, sans-serif;font-size:14px;line-height:25px;text-align:left;color:#363A41;">
+                                          {% if templateType == 'html' %}
+{virtualProducts}
+{% endif %}
+                                          {% if templateType == 'txt' %}
```
Comment (PierreRambaud) [inline mails/themes/modern/core/download_product.html.twig:266]: same here

File: mails/themes/classic/core/download_product.html.twig (hunk 2 above)
Comment (PierreRambaud) [reply mails/themes/classic/core/download_product.html.twig:34]: Oh, just noticed these files are generated -_-

File: mails/themes/modern/core/download_product.html.twig (hunk 3 above)
Comment (PierreRambaud) [reply mails/themes/modern/core/download_product.html.twig:266]: Oh, just noticed these files are generated -_-

File: classes/order/OrderHistory.php (hunk 1 above)
Comment (atomiix) [reply classes/order/OrderHistory.php]: I did that mainly because the partial renderer add the partial file being rendered in html comment like that : 
```
return "\n<!-- begin $tpl -->\n"
            . parent::fetch($template, $cache_id, $compile_id, $parent, $display, $merge_tpl_vars, $no_output_filter)
            . "\n<!-- end $tpl -->\n";
```

Comment (PierreRambaud) [reply classes/order/OrderHistory.php]: Oh, I was more thinking about comments in custom html template ^^'

File: mails/themes/modern/core/download_product.html.twig (hunk 3 above)
Comment (atomiix) [reply mails/themes/modern/core/download_product.html.twig:266]: This one is generated by the [mjml-theme-converter](https://github.com/PrestaShop/mjml-theme-converter), I can't change it

File: classes/order/OrderHistory.php (hunk 1 above)
Comment (jolelievre) [reply classes/order/OrderHistory.php]: I don't understand the need to remove html comment tags, when I look at your txt template `download_product_virtual_products.txt` there is no html content, so why do you need to remove it?

File: classes/order/OrderHistory.php [hunk 4]
```diff
@@ -615,4 +627,47 @@ public function addWs()
...
+     * current_theme/mails/current_iso_lang/ if found, otherwise in
+     * mails/current_iso_lang.
+     *
+     * @param string $template_name template name with extension
+     * @param int $mail_type Mail::TYPE_HTML or Mail::TYPE_TEXT
+     * @param array $var sent to smarty as 'list'
+     *
+     * @return string
+     */
+    protected function getEmailTemplateContent($template_name, $mail_type, $var)
```
Comment (jolelievre) [inline classes/order/OrderHistory.php]: As I told you I don't think this extra function is useful, it was already present in PaymentModule so I just modified the last part about partiel rendering. But anyway in the Mail::send function we already check the PS_MAIL_TYPE configuration and this is where the appropriate content is selected (or not) inside the mail body.

So I think you could simply (even drop completely) this method and simply call `$this->getPartialRenderer()->render($template_name, $this->context->language, $var)` to create you two variables
Sure in cas the mail config is not for BOTH you will have generated one for nothin but I the performance cost is really minimal compared to the complexity of the code

Comment (jolelievre) [reply classes/order/OrderHistory.php]: Actually it's probably useless in PaymentModule as well, but I wanted to make the minimum changes possible I guess

File: classes/order/OrderHistory.php (hunk 1 above)
Comment (atomiix) [reply classes/order/OrderHistory.php]: That's because when  the `download_product_virtual_products.txt` template is rendered, the renderer adds comments. Here is what I get in my mailbox when I don't remove html comments : 
```
http://localhost/prestashop/index.php

Hi thomas baccelli,

Thank you for your order with the reference JRNKCBIHJ from PrestaShop

Product(s) to download

You have 1 product(s) now available for download using the following link(s):


<!-- begin /Users/tBaccelli/Sites/prestashop/mails/_partials/download_product_virtual_products.txt -->
  [Capture d&rsquo;écran 2019-10-15 à 17.40.05.png](http://localhost/prestashop/index.php?controller=get-file&key=756cddd141c35f16ab816bb301b14b79de34182f-6d13e7f3990af715aeb737adb923a46b5ee456fa&id_order=1932&secure_key=24926c1a734a9822e6ad4f535668f657)

<!-- end /Users/tBaccelli/Sites/prestashop/mails/_partials/download_product_virtual_products.txt -->


Follow your order and download your invoice on our shop, go to the [Order history and details](http://localhost/prestashop/index.php?controller=history) section of your customer account.

If you have a guest account, you can follow your order via the [Guest Tracking](http://localhost/prestashop/index.php?controller=guest-tracking) section on our shop.

[PrestaShop](http://localhost/prestashop/index.php)

Powered by [PrestaShop](https://www.prestashop.com/?utm_source=marchandprestashop&utm_medium=e-mail=utm_campaign=footer_1-7)

```

Comment (jolelievre) [reply classes/order/OrderHistory.php]: Oh damn, seems like it's coming from our own over layer on Smarty (probably SmartyDev in this case) https://github.com/PrestaShop/PrestaShop/blob/4ec595f06d52c5aa93b8dd930699f8f6d21cca58/classes/Smarty/SmartyDev.php#L39

This is completely not needed in this case, so we shouldn't use the context Smarty instance but a normal one instead.. but the thing is smarty is configured in https://github.com/PrestaShop/PrestaShop/blob/develop/config/smarty.config.inc.php

Then maybe we should add a `cleanComments` parameter to the `MailPartialTemplateRenderer::render` method

**Review by jolelievre — APPROVED** [review]
Nice job @atomiix

**Comment by matks** [comment]
@Robin-Fischer-PS My bad, I told @atomiix to merge this because it was approved, I forgot to mention the QA

**Comment by Robin-Fischer-PS** [comment]
Hi @matks :)

One small defect : The link on the mail includes number of DL and expiration date. The link still works.

pr16014 link

**Comment by marionf** [comment]
@atomiix @matks 

I still have the issue with txt email

capture d'écran_2089

**Comment by marionf** [comment]
My bad, I wasn't on the good store 
It's ok

capture d'écran_2090
