### PR TITLE
Fix symlink issues on install

### LINKED ISSUE #39104: The symbolic link of PrestaShop v9 is not created by the self-unzipper
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you use the self-unzipper of a PrestaShop v9 release, it appears the only symbolic link present (`admin/bundles/apiplatform`) is not created on the filesystem, even though the process completed.

https://github.com/user-attachments/assets/c52a9510-900c-461f-9235-1242a966d62d

The result of `admin/bundles` is:

```
root@85de681246cf:/var/www/html/admin/bundles# ls -l
total 4
-rw-r--r-- 1 www-data www-data 67 Jun 10 11:38 apiplatform
```

> [!CAUTION]
> Oh no, `apiplatform` is just a regular file containing the destination path of the link that was supposed to be created, not a symbolic link.

I've tested this feature following a discussion on https://github.com/PrestaShop/PrestaShop/issues/38960

### Expected behavior

This is what the filesystem should look like:

```
root@85de681246cf:/var/www/html/admin/bundles# ls -l
total 4
lrwxrwxrwx 1 root root 67 Jul 10 15:02 apiplatform -> ../../vendor/api-platform/core/src/Symfony/Bundle/Resources/public/
```

### Steps to reproduce

1. From scratch, retrieve any release of PrestaShop v9.0.0
2. Unzip the archive you downloaded and extract the files in it to your web server directory: `index.php` and `prestashop.zip`
3. Open the directory in your browser, you should see the extraction of PrestaShop, then a redirection the installation page
4. Check the state of `admin/bundles/apiplatform`

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1.31

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | With this PR, we create symlink (or hard copy if the hosting env doesn't have symlink enabled) on the "finalize" installation step.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Install this PR, and verify the folder `admin-dev/bundles` are empty or not present.<br>2. Install PrestaShop with cli or web installer.<br>3. After installation, `admin-dev/bundles` must have `apiplateform` folder!
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/16806935930
| Fixed issue or discussion?     | Fixes #39104, and maybe #38960 too (after some work on autoupgrade module too! cc @Quetzacoalt91)
| Related PRs       | ~
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Nice job @boherm

File: src/PrestaShopBundle/Install/Install.php [hunk 1]
```diff
@@ -1228,9 +1231,18 @@ public function finalize(?string $randomizedAdminFolderName = null): bool
                 return false;
             }
         }
+
+        // We need also to run "assets:install" to install some bundles assets via symlink
+        // or hard copy if symlink aren't possible in this environment.
+        SymfonyContainer::getInstance()
+            ->get(AssetsInstaller::class)
+            ->installAssets($adminFolder);
```
Comment (Quetzacoalt91) [inline src/PrestaShopBundle/Install/Install.php:1239]: @PrestaShop/squad-seamless-upgrade We can reuse this code to run the same action during an update.

File: src/Adapter/Bundle/AssetsInstaller.php [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        // We need to use the PrestaShopApplication to run the command
+        $application = new PrestaShopApplication($kernel);
+        $application->setAutoExit(false);
+
+        // Run the command to install bundles assets
+        // (for now! maybe we should use another way to install assets in the future)
+        $application->run(new ArrayInput([
+            'command' => 'assets:install',
+            'target' => $adminFolder,
+        ]), new NullOutput());
```
Comment (Quetzacoalt91) [inline src/Adapter/Bundle/AssetsInstaller.php]: Does the NullOutput means we won't know what happened if the command fails?

File: src/Adapter/Bundle/AssetsInstaller.php [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+ * @internal
+ */
+final class AssetsInstaller
+{
+    public function installAssets(string $adminFolder): void
+    {
+        // We retrieve the kernel from the global scope
+        global $kernel;
+        if (!$kernel instanceof KernelInterface) {
+            throw new \RuntimeException('Kernel is not initialized. Cannot install assets.');
```
Comment (jolelievre) [inline src/Adapter/Bundle/AssetsInstaller.php]: Please add a `use` statement for this exception

File: src/Adapter/Bundle/AssetsInstaller.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/Bundle/AssetsInstaller.php]: Yep, if we want some log we could add a different output, for example if we use a `BufferedOutput` then we can get all the output via `BufferOutput::fetch` and throw an exception accordingly when the run method returns an error code (!= 0)

File: src/Adapter/Bundle/AssetsInstaller.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/Bundle/AssetsInstaller.php]: Ah cs fixer thinks like me 😅

**Review by tleon — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]

File: src/Adapter/Bundle/AssetsInstaller.php [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+ * @internal
+ */
+final class AssetsInstaller
+{
+    public function installAssets(string $adminFolder): void
+    {
+        // We retrieve the kernel from the global scope
+        global $kernel;
+        if (!$kernel instanceof KernelInterface) {
+            throw new PrestaShopExceptionCore('Kernel is not initialized. Cannot install assets.');
```
Comment (jolelievre) [inline src/Adapter/Bundle/AssetsInstaller.php]:
```suggestion
            throw new PrestaShopException('Kernel is not initialized. Cannot install assets.');
```
We never use the `*Core` classes directly, they are meant as bases for the override system but should not be used directly

Comment (jolelievre) [reply src/Adapter/Bundle/AssetsInstaller.php]: This makes me think maybe we should add a rule in PHPStan to enforce this

Comment (boherm) [reply src/Adapter/Bundle/AssetsInstaller.php]: You're totally right!

**Review by jolelievre — DISMISSED** [review]
Thanks @boherm

**Review by tleon — DISMISSED** [review]

**Comment by boherm** [comment]
Rebased to resolve conflicts with 9.0.x branch.
Ready for review (again!)

**Review by kpodemski — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by tleon — APPROVED** [review]
QA ok for me

**Review by paulnoelcholot — APPROVED** [review]
