### PR TITLE
Fix product features

### LINKED ISSUE #10757: Multiple features with same value are causing not described errors
**Describe the bug**
Title says it all.

**To Reproduce**
1. Go to 'Catalog > Product -> Edit'
2. Add feature, Color: White, and below again, Color: white
3. Click the "Save" button
4. See error, it says that settings cannot be saved but there's literally no information at all about what went wrong, of course it's obvious mistake to have 2 features with same value but if someone have 20+ features it's easy to overlook it

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Can't get feature data if you don't have token in url & Can't save duplicate feature data.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10757 
| How to test?  | Follow ticket instructions, but can you test all the Product page ?

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10956)

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php [hunk 1]
```diff
@@ -296,6 +297,20 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 $event->setData($data);
             }
 
+            if (isset($data['features'])) {
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:303]: I understand that you are making sure there is no duplicates in `$data['features']` however I fail to understand the goal behind it. Maybe an helpful comment would help here ? 😄

**Review by matks — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php (hunk 1 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:303]: Done

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 2]
```diff
@@ -466,6 +466,7 @@ public function formAction($id, Request $request)
                 if ($form->isValid()) {
                     //define POST values for keeping legacy adminController skills
                     $_POST = $modelMapper->getModelData($formData, $isMultiShopContext) + $_POST;
+                    $_POST['form'] = $formData;
```
Comment (kpodemski) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php:469]: This is very interesting line, is it related to all the problems with not working product saving in some scenarios? How did you catch it?

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:469]: It's maybe related to some scenarios, but not all of them :smile: 
By editing the ProductInformation Form, I found that my changes were not catch in the legacy controller (don't understand why they not fully migrate this page :/) and step by step I realized that the `$_POST` needs to be filled.

**Review by eternoendless — DISMISSED** [review]
LGTM

**Comment by marionf** [comment]
@PierreRambaud 

1) Whathever the feature I choose, I have always the same predefined values in the drop down

capture d ecran_465

capture d ecran_466

2) If I try to save a feature with a predefined value that is not corresponding to this feature, I have this error

capture d ecran_467

3) 
I add 3 values to the same feature:
Frame Size: Coton (predefined)
Frame size: test (custom)
Frame size: Elasthanne (predefined)
The 3 values are displayed in FO: OK

I delete Frame size: Elasthanne and save
The 2 values (Frame Size: coton  & Frame size: test)  are displayed in FO: OK

I add again Frame size: Elasthanne and save
Only 2 values are displayed in FO: Frame size coton & frame size Elasthanne), the custom value "test" has disappeared

4) 
I add some Feature & values:
Frame size: coton (predefined)
Frame size: elasthanne (predefined)
Color: test (custom)
Size: test2 (custom)

The 4 features & values are displayed in FO: OK

I change the tax rule of the product & save

In FO I have well the 4 features but only 2 values:
Frame size: coton 
Frame size: elasthanne 
Color: 
Size: 
The 2 custom values have disappeared

I think scenario 3 and 4 are the same issue: if I change something on the product page and save, custom values are removed

**Comment by PierreRambaud** [comment]
@marionf Should be ok now :)

**Comment by marionf** [comment]
@PierreRambaud 
I still have custom values that disappeared
I add:
Frame size: Coton
Frame size: test
Paper type: Quadrillé
Save -> OK
Change Paper type for "Ligné" and custom value "test" disappear

**Comment by marionf** [comment]
Still have custom values that disappear

https://drive.google.com/open?id=1KwunRy_Gj8mnO8Gs3gSOth7lRJP7qomE

**Comment by marionf** [comment]
Still have custom values that disappear

https://drive.google.com/open?id=1KwunRy_Gj8mnO8Gs3gSOth7lRJP7qomE

**Comment by Quetzacoalt91** [comment]
This seems to be caused by the count of existing features when adding a new line. If you previously removed a feature (not the last one), adding another feature will get exactly the same name as an existing line.

**Comment by PierreRambaud** [comment]
@marionf @Quetzacoalt91 Yeah, you found a new bug :+1: (on custom fields too)
Everything should be ok now (I hope), don't forget to clear your cache.

File: src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php [hunk 3]
```diff
@@ -296,6 +297,27 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                $ids = [];
+                foreach ($data['features'] as $idx => $feature) {
+                    if (empty($feature['value'])) {
+                        continue;
+                    }
+
+                    $id = sprintf('%d-%d', $feature['feature'], $feature['value']);
+                    if (in_array($id, $ids)) {
+                        unset($data['features'][$idx]);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:312]: isn't it dangerous to unset an element of the array while going through it?
you should either copy the array and go though the copy, or instantiate a new array and populate it while going through the initial one

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php (hunk 3 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:312]: Nope it's not dangerous and because it's a data we really want to remove in this array :)
If I copy the array into another, the $_POST and other will not be changed and the legacy code will still using the wrong data.

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:312]: alright, I understand that you need to unset this array specificly
but you are sur there's not a chance you miss an index if you unset one during the loop? does php stores/saves each index? or the Iterator interface is able not to get lost?

Comment (PierreRambaud) [reply src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:312]: It always clean the current index and not the one after.
Nothing can be lost :)

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:312]: alright, good to know!! :)
all good then

**Review by jolelievre — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PierreRambaud
