### PR TITLE
Prevent setting duplicate order status names

### LINKED ISSUE #22870: Having two order states with the same name makes status name disappear in order list after order validation
#### Describe the bug

Having two order states with the same name makes order status disappear in order list after order validation.

#### Steps to Reproduce

1 - Use the same name for two order statuses for the same id_lang 

(this is already happening in some existsings translations like IT where "On backorder (paid)" and "On backorder (unpaid)" are both translated in "In attesa di rifornimento". )

2 - Put a product to 0 quantity with "Allow orders when out of stock

3 - Make an order of that product and check order list afterwards :

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Check if an order status has the same name in Add/Edit
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22870
| How to test?      | Add or Edit an order status and try to set the label identical to an existing one (like @hibatallahAouadni did in https://github.com/PrestaShop/PrestaShop/issues/22870#issuecomment-769142051)<br>Specs from @MatShir : https://github.com/PrestaShop/PrestaShop/issues/22870#issuecomment-772563200

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23142)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

File: controllers/admin/AdminStatusesController.php [hunk 1]
```diff
@@ -602,6 +602,19 @@ public function postProcess()
             if (!$this->access('add')) {
                 return;
             }
+            $langIds = Language::getIDs(false);
+
+            foreach ($langIds as $id_lang) {
+                $count = (int) DB::getInstance()->getValue(
+                    'SELECT COUNT(*) AS count FROM ' . _DB_PREFIX_ . 'order_state_lang' .
+                    ' WHERE id_lang = ' . (int) $id_lang .
+                    ' AND name = "' . (string) $_POST['name_' . $id_lang] . '"' .
```
Comment (eternoendless) [inline controllers/admin/AdminStatusesController.php]: This should definitely not be done at the controller level, but in ObjectModel

**Review by eternoendless — DISMISSED** [review]
Please avoid adding more SQL in controllers

File: controllers/admin/AdminStatusesController.php [hunk 2]
```diff
@@ -602,6 +602,19 @@ public function postProcess()
...
+                    (isset($_POST['id_order_state']) ? ' AND id_order_state != ' . (int) $_POST['id_order_state'] : '')
+                );
+                if ($count) {
+                    $this->errors[] = $this->trans('This name already exists.', [], 'Admin.Design.Notification');
```
Comment (PierreRambaud) [inline controllers/admin/AdminStatusesController.php:620]: We also don't need to continue if there is an error :thinking:

**Review by PierreRambaud — DISMISSED** [review]
As Pablo's says, you have to put logic inside ObjectModel

File: classes/order/OrderState.php [hunk 3]
```diff
@@ -162,4 +162,21 @@ public function isRemovable()
...
+     * @param int|null $idOrderState
+     *
+     * @return int
+     */
+    public static function countByLocalizedName(string $name, int $idLang, ?int $idOrderState): int
+    {
+        return (int) DB::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
+            'SELECT COUNT(*) AS count FROM ' . _DB_PREFIX_ . 'order_state_lang' .
+            ' WHERE id_lang = ' . $idLang .
+            ' AND name = "' . $name . '"' .
```
Comment (matks) [inline classes/order/OrderState.php]:
```suggestion
            ' AND name = \'' . pSQL($name) . '\'' .
```
I think we need to escape this string 🤔  ?

File: controllers/admin/AdminStatusesController.php [hunk 4]
```diff
@@ -602,6 +602,19 @@ public function postProcess()
             if (!$this->access('add')) {
                 return;
             }
+            $langIds = Language::getIDs(false);
+
+            foreach ($langIds as $id_lang) {
+                $count = OrderState::countByLocalizedName(
+                    (string) $_POST['name_' . $id_lang],
```
Comment (matks) [inline controllers/admin/AdminStatusesController.php]: I think we're supposed to use `Tools::getValue()` but I'm no legacy expert 😅

File: classes/order/OrderState.php (hunk 3 above)
Comment (Progi1984) [reply classes/order/OrderState.php]: Good idea

File: controllers/admin/AdminStatusesController.php (hunk 4 above)
Comment (Progi1984) [reply controllers/admin/AdminStatusesController.php]: Fixed

File: classes/order/OrderState.php [hunk 5]
```diff
@@ -162,4 +162,21 @@ public function isRemovable()
...
     }
+
+    /**
+     * @param string $name
+     * @param int $idLang
+     * @param int|null $idOrderState
+     *
+     * @return int
+     */
+    public static function countByLocalizedName(string $name, int $idLang, ?int $idOrderState): int
```
Comment (matks) [inline classes/order/OrderState.php]:
```suggestion
    public static function countByLocalizedName(string $name, int $idLang, ?int $excludeIdOrderState): int
```
Suggestion (not blocking): change the variable name to highlight its meaning, this identifier is used to _exclude_ results not to include (and explain this in phpDoc)

**Review by matks — DISMISSED** [review]
Code is good enough for me so I approve the PR. I add a suggestion 😉  feel free to choose whether to apply it or not.

File: classes/order/OrderState.php (hunk 5 above)
Comment (jolelievre) [reply classes/order/OrderState.php]: Agreed, either that or you could remove this condition and check that `$count == 0` in your validator And maybe this method would have more use cases without this extra condition

**Review by sowbiba — DISMISSED** [review]

File: classes/order/OrderState.php (hunk 5 above)
Comment (Progi1984) [reply classes/order/OrderState.php]: Done @matks

**Review by matks — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984, @MatShir,

I have only one question when we delete an order status, then we try to re-create it with the same name => this is not possible.
Steps to reproduce the behavior
1. Go to BO > Shop Parameters > Order Settings > Statuses Tab
2. Create an Order status `test`
3. Delete it 
image
4. Try to create a new order status with `test` name
5. See an error 
image
 In the BO > Orders > Order page > the deleted status well displayed
image

What do you think? can we accept this behavior, in the PS1771 => we can re-create it.

Thank you!

**Review by jolelievre — DISMISSED** [review]

**Comment by MatShir** [comment]
It should not take into account the deleted order status

**Review by sowbiba — DISMISSED** [review]

File: classes/order/OrderState.php [hunk 6]
```diff
@@ -162,4 +162,24 @@ public function isRemovable()
...
     }
+
+    /**
+     * @param string $name
+     * @param int $idLang
+     * @param int|null $excludeIdOrderState ID of the order state excluded for the search
+     *
+     * @return int
+     */
+    public static function countByLocalizedName(string $name, int $idLang, ?int $excludeIdOrderState): int
```
Comment (eternoendless) [inline classes/order/OrderState.php]: Does it make sense to use count when normally this can only return 0 or 1?

This looks like an "exists" assertion.

Also, I'm worried about executing as many requests as languages you have installed.

File: classes/order/OrderState.php [hunk 7]
```diff
@@ -162,4 +162,24 @@ public function isRemovable()
     {
         return !($this->unremovable);
     }
+
+    /**
```
Comment (eternoendless) [inline classes/order/OrderState.php:166]: Don't forget to describe your method and the parameters. Describing helps other people understand the intent (what the method is for, what is expected in all parameters). In addition, you'll be surprised about how often you will find out naming or design issues just by taking the time to describe stuff.

File: classes/order/OrderState.php (hunk 6 above)
Comment (Progi1984) [reply classes/order/OrderState.php]: Fixed the naming. Executing is stopped when a localized name exist.

**Review by matks — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by sowbiba** [comment]
waiting for checks to label it *waiting for QA*

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Install shop with the English language & France country
2. Go to BO > Shop Parameters > Order Settings > Statuses Tab
3. Add new statuses with this name `En attente du paiement par chèque` 
image
4. Save
5. Go to Your profile > change the language of the super admin to French
6. Go to BO > Orders > Order list page
7. See error 
image
8. Go to BO > Shop Parameters > Order Settings > Statuses Tab: you have two statuses with the same name 
image
9. Try to delete the last status created
10. See error 
image


PS: this issue is reproduced only after the last fix, previously it was ok
Thank you!

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/106x8N8ya1qALb4c0NhDtUUFUXn5iy4NC/view?usp=sharing

I just found new trivial regression but not related to this PR: https://github.com/PrestaShop/PrestaShop/issues/23379

Thank you!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
