### PR TITLE
27054: fixed taxes for wrong countries

### LINKED ISSUE #27054: BO - Tax Rule is applied on product page V2 - It shouldn't because the default country is different from the country where the tax rule is applied
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

BO - Tax Rule is applied on product page V2 - It shouldn't because the default country is different from the country where the tax rule is applied

Specs: https://build.prestashop.com/prestashop-specs/1.7/back-office/catalog/products/add-edit-v2.html#retail-price
### Expected behavior

It will display the shop's country and its related tax rate. If there is none configured for this specific country, we will display 0%

Capture d’écran 2022-01-24 à 18 09 32

### Steps to reproduce

1. Go to BO > International > Localization & check that the `Default country = France` 
image
2. Go to BO > International > Taxes > Tax rules page & Create a Tax rule for Algeria  
image
3. Go to BO > Catalog > Products V2 > Princing tab and change the tax rule to the last one created
4. See error => Tax rule is applied, it shouldn't 
image
5. If this PR https://github.com/PrestaShop/PrestaShop/pull/26762 is merged => same issue on the `Retail price per unit` 
image

In the Product V1 => ok 
image

> Edited by Khouloud

### Other Steps to reproduce a similar issue: 

reported previously here: https://github.com/PrestaShop/PrestaShop/pull/27233#pullrequestreview-916147184 and here: https://github.com/PrestaShop/PrestaShop/pull/27233#pullrequestreview-867695501 "Third issue"

The tax is updated with every refresh of the page when using theses configuration for the tax rule : 
1. Create a tax rule that uses different taxes for different Countries 
image
2. Create a tax rule that uses a One by One Tax 
image

3. Create a tax rule that uses a tax with Combine 
image

4. Create a tax rule that uses different taxes for different States as described [here](https://github.com/PrestaShop/prestashop-specs/pull/316/files?diff=split&w=0#diff-69aed766389514c34c80d6bac9113d027cc8640ae5e27ab4f7e6c478c0123a33R47)
5. Create for each tax rule product with different tax rules
6. Save
7. Refresh
8. See error => the tax rule is changed 

https://user-images.githubusercontent.com/92912932/159329718-3a369bba-f618-4337-b62f-6c289e612e6a.mp4
### PrestaShop version(s) where the bug happened

> Edited by Khouloud

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-986520326

1. Go to BO > Taxes > Taxes rule & create a tax rule with combine 10% + 20% = 30%
2. In the BO > Taxes > Enable ecotax with tax rule = combine de tax
3. Go to BO > Create a product V2 > In the pricing tab
4. The ecotax rate displayed = 20% => NOK / it should be 30%
5. also, if I add ecotax = 1 tax excluded => it is displayed 1.2 tax included  / it should be 1.3 tax included

https://user-images.githubusercontent.com/16067358/170534006-1a35ae67-a97a-4be6-a3b2-e8291217cd71.mp4

1.7.8.1, develop

### PHP version(s) where the bug happened

10.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by margud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?      | Fixed issue where on new product page it would show wrong tax %. More information on first issue [here](https://github.com/orgs/PrestaShop/projects/7/views/18)
| Type?             | bug fix 
| Category?         |  BO 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#27054](https://github.com/PrestaShop/PrestaShop/issues/27054).
| How to test?      | In product bo page when choosing tax it should show the tax of the default country. More information [here](https://github.com/orgs/PrestaShop/projects/7/views/18)

### CODE REVIEW

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 1]
```diff
@@ -53,19 +56,33 @@ public function getChoices()
...
     public function getChoicesAttributes(): array
     {
-        $attrs = [];
-        foreach ($this->getRules() as $rule) {
-            // Keep first one found
-            if (!empty($attrs[$rule['name']]['data-tax-rate'])) {
-                continue;
-            }
+        $address = new Address();
+        $address->id_country = (int) Context::getContext()->country->id;
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: We try to avoid using `Context::getContext` directly in recent code, This should be injected in the provider instead, you can inject the `LegacyContext` in this service, or (maybe better) simply inject the country ID this way the service is not bound to any context service but only the data that is relevant for its use (which will simplify future refacto, since only the service definition ill need to be updated).


In the service you can inject something like `- "@=service("prestashop.adapter.legacy.context").getContext().country.id"`

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 2]
```diff
@@ -53,19 +56,33 @@ public function getChoices()
...
-                'data-tax-rate' => !empty($rule['rate']) ? $rule['rate'] : 0,
+        $tax_rates = [];
+        foreach ($this->getRules() as $rule) {
+            $id_tax_rules_group = (int) $rule['id_tax_rules_group'];
+            $tax_calculator = TaxManagerFactory::getManager($address, $id_tax_rules_group)->getTaxCalculator();
+            $tax_rates[$id_tax_rules_group] = [
+                'id_tax_rules_group' => $id_tax_rules_group,
+                'rates' => [],
+                'computation_method' => (int) $tax_calculator->computation_method,
             ];
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Are you sure these data are relevant in the choices attributes? Besides I don't think they are correctly indexed because the array index should map the one used in `getChoices` so it should rather be `$tax_rates[$rule['name']]` (like you did in L75

This data will, at best, be ignored and at worst add some unexpected extra fields in the selector. If these fields are not used in the page after (unlike the `data-tax-rate` data attribute) then they shouldn't be part of the returned attributes. If they are not relevant and since they are not used in the following code maybe this should simply be removed.

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
```

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 3]
```diff
@@ -53,19 +56,33 @@ public function getChoices()
...
-                continue;
-            }
+        $address = new Address();
+        $address->id_country = (int) Context::getContext()->country->id;
 
-            $attrs[$rule['name']] = [
-                'data-tax-rate' => !empty($rule['rate']) ? $rule['rate'] : 0,
+        $tax_rates = [];
+        foreach ($this->getRules() as $rule) {
+            $id_tax_rules_group = (int) $rule['id_tax_rules_group'];
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: You maybe copied this code from a legacy code, but please prefer the camel case notation for all the variable in this class

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
            $taxRulesGroupId = (int) $rule['id_tax_rules_group'];
```

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 4]
```diff
@@ -53,19 +56,33 @@ public function getChoices()
...
+                foreach ($tax_calculator->taxes as $tax) {
+                    $tax_rates[$rule['name']] = [
+                        'data-tax-rate' => (float) $tax->rate,
+                    ];
+                }
+            } else {
+                $tax_rates[$rule['name']] = [
+                    'data-tax-rate' => 0,
+                ];
+            }
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Be careful you are looping through multiple tax values, so the last one will be kept in the end. In the previous implementation only the first one was kept, I don't know enough about the tax rate behaviour to be sure what we actually expect to know which one should be the better.

But I believe some taxes can be defined as "compound" taxes and their value is added one above the other or something like that, I believe it depends on the tax configuration itself which seems to be define in `TaxRule::behavior`.

This behaviour seems to be injected in the TaxCalculator already:
https://github.com/PrestaShop/PrestaShop/blob/db4bab3d59bca55c0f3ffe97391b3caa023f5db5/classes/tax/TaxRulesTaxManager.php#L130

But to benefit from its computing intelligence I think you should use `$tax_calculator->getTotalRate()` instead which performs this loop among the taxes and applies the appropriate method

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
            $tax_rates[$rule['name']] = [
                'data-tax-rate' => $tax_calculator->getTotalRate(),
            ];
```

File: src/Adapter/Tax/TaxComputer.php [hunk 5]
```diff
@@ -100,15 +87,11 @@ public function computePriceWithoutTaxes(
...
-            $countryTaxRate = $taxRulesGroup['rates'][$countryId->getValue()] ?? reset($taxRulesGroup['rates']);
-        } else {
-            $countryTaxRate = 0;
-        }
+        $address = new Address();
+        $address->id_country = $countryId->getValue();
+        $taxCalculator = TaxManagerFactory::getManager($address, $taxRulesGroupId->getValue())->getTaxCalculator();
 
-        return new DecimalNumber((string) $countryTaxRate);
+        return new DecimalNumber((string) $taxCalculator->getTotalRate());
```
Comment (margud) [inline src/Adapter/Tax/TaxComputer.php:135]: Old logic would just add last tax, now it calculates correct tax rates.
But because we are using TaxManagerFactory to do so i had to remove unit test because i couldn't mock sql that its inside getTaxCalulator() function. 
Open to suggestions on how to return and modify unit test to make it work. Putting calculator in constructor feels like the function doesn't make sense anymore.

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 6]
```diff
@@ -26,15 +26,28 @@
...
 use TaxRulesGroup;
 
 /**
  * Provides tax rule group choices with tax rule name as key and id as value
  */
 final class TaxRuleGroupChoiceProvider implements FormChoiceProviderInterface, FormChoiceAttributeProviderInterface
 {
+    /** @var int */
+    private $countryId;
+    /** @var int */
```
Comment (zuk3975) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: shouldn't cs fixer fail due to this? we usually use like this everywhere:
```suggestion
    
    /**
     * @var int
     */
```

File: src/Adapter/Tax/TaxComputer.php [hunk 7]
```diff
@@ -100,15 +101,19 @@ public function computePriceWithoutTaxes(
      */
     public function getTaxRate(TaxRulesGroupId $taxRulesGroupId, CountryId $countryId): DecimalNumber
     {
-        $taxRulesGroup = $this->taxRulesGroupRepository->getTaxRulesGroupDetails($taxRulesGroupId);
-        if (!empty($taxRulesGroup['rates'])) {
-            // Use the tax rate associated to context country, or the first one as fallback
-            $countryTaxRate = $taxRulesGroup['rates'][$countryId->getValue()] ?? reset($taxRulesGroup['rates']);
-        } else {
-            $countryTaxRate = 0;
+        $country = new \Country($countryId->getValue());
```
Comment (zuk3975) [inline src/Adapter/Tax/TaxComputer.php]: Inject [CountryRepository](https://github.com/PrestaShop/PrestaShop/blob/8.0.x/src/Adapter/Country/Repository/CountryRepository.php) into constructor and use $this->countryRepository->get($countryId) instead. 
Though this method doesn't exist yet so you'll need to implement it. (its pretty easy, just check other example classes that extends AbstractObjectModelRepository)

File: src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php [hunk 8]
```diff
@@ -40,64 +39,6 @@
...
-        $this->connection = $connection;
-        $this->dbPrefix = $dbPrefix;
-    }
-
-    /**
-     * @param TaxRulesGroupId $taxRulesGroupId
-     *
-     * @return array
-     */
-    public function getTaxRulesGroupDetails(TaxRulesGroupId $taxRulesGroupId): array
```
Comment (zuk3975) [inline src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php:70]: if Im not mistaken this class was introduced in 1.7.8 with first beta of product page. So its all ok to remove those public methods, as for beta its not considered BC break, right @jolelievre ?

File: src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php [hunk 9]
```diff
@@ -90,7 +90,10 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'virtual_product_file_id' => $options['virtual_product_file_id'],
             ])
             ->add('shipping', ShippingType::class)
-            ->add('pricing', PricingType::class)
+            ->add('pricing', PricingType::class,
+            [
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/EditProductFormType.php]: cs fixer should care about this, probably its missing some configs :thinking: 
```suggestion
            ->add('pricing', PricingType::class, [
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php [hunk 10]
```diff
@@ -65,7 +65,11 @@ public function __construct(
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
         $builder
-            ->add('retail_price', RetailPriceType::class)
+            ->add('retail_price', RetailPriceType::class,
+                [
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php]: same here

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 11]
```diff
@@ -93,6 +95,8 @@ class RetailPriceType extends TranslatorAwareType
      * @var int
      */
     protected $contextCountryId;
+    /** @var int */
```
Comment (zuk3975) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: same about cs mentioned at the top

File: tests/Unit/Adapter/Tax/TaxComputerTest.php [hunk 12]
```diff
@@ -1,151 +0,0 @@
...
-use Generator;
-use PHPUnit\Framework\MockObject\MockObject;
-use PHPUnit\Framework\TestCase;
-use PrestaShop\Decimal\DecimalNumber;
-use PrestaShop\PrestaShop\Adapter\Tax\TaxComputer;
-use PrestaShop\PrestaShop\Adapter\TaxRulesGroup\Repository\TaxRulesGroupRepository;
-use PrestaShop\PrestaShop\Core\Domain\Country\ValueObject\CountryId;
-use PrestaShop\PrestaShop\Core\Domain\TaxRulesGroup\ValueObject\TaxRulesGroupId;
-
-class TaxComputerTest extends TestCase
```
Comment (zuk3975) [inline tests/Unit/Adapter/Tax/TaxComputerTest.php:40]: Why removed whole test? The class still exists, couldn't it be adjusted?

File: src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php (hunk 8 above)
Comment (margud) [reply src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php:70]: well i removed it because its never used after i deleted and changed the part that was using it.

File: tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature [hunk 13]
```diff
@@ -0,0 +1,280 @@
...
+@clear-cache-before-feature
+@update-product-prices
+@update-prices-without-states
+@reboot-kernel-after-feature
+@clear-cache-after-feature
+Feature: Update product price fields from Back Office (BO).
+  As a BO user I want to be able to update product fields associated with price.
+
+  Background:
+    Given shop configuration for default shop fr
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature]: sounds broken. Did you mean at least smth like?

```suggestion
    Given shop configuration for default shop is set to fr
```

Comment (zuk3975) [reply tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature]: And i think this is the main and only difference compared the scenarios in `update_prices.feature` - the different country. As far as I remember you just expect to check different tax rate depending if BO country has state or not. So to reflect the actual scenario/usecase (and save some tests running time) it was probably enough just to add a single scenario into existing `update_prices.feature` ? smth like `Scenario: I update product prices when default country has no states`. Most of the times more tests = better, but in this case I think it actually hides the usecase and wastes the tests time, though I may be wrong :man_shrugging:  wdyt @jolelievre ?

File: tests/Unit/Adapter/Tax/TaxComputerTest.php (hunk 12 above)
Comment (margud) [reply tests/Unit/Adapter/Tax/TaxComputerTest.php:40]: because unit test doesn't have database and the tax calculator has sql inside it we can't test it with unit test. To make it testable it would require lot of refactoring. If we want to do it i would prefer new PR for that.

File: src/Adapter/Country/Repository/CountryRepository.php [hunk 14]
```diff
@@ -49,4 +50,23 @@ public function assertCountryExists(CountryId $countryId): void
...
+    public function get(CountryId $countryId): Country
+    {
+        /** @var Country $country */
+        $country = $this->getObjectModel(
+            $countryId->getValue(),
+            Country::class,
+            CountryNotFoundException::class
+        );
+
+        return $country;
```
Comment (Amoifr) [inline src/Adapter/Country/Repository/CountryRepository.php]: may be you can return the previous expression instead using a local variable

File: src/Adapter/Country/Repository/CountryRepository.php [hunk 15]
```diff
@@ -49,4 +50,23 @@ public function assertCountryExists(CountryId $countryId): void
...
     }
+
+    /**
+     * @param CountryId $countryId
+     *
+     * @return Country
+     *
+     * @throws CountryNotFoundException
+     */
+    public function get(CountryId $countryId): Country
```
Comment (Amoifr) [inline src/Adapter/Country/Repository/CountryRepository.php]: Is getByCountryId is already defined ?

File: src/PrestaShopBundle/Resources/config/services/adapter/tax.yml [hunk 16]
```diff
@@ -8,7 +8,8 @@ services:
   prestashop.adapter.tax.tax_computer:
     class: 'PrestaShop\PrestaShop\Adapter\Tax\TaxComputer'
     arguments:
-      - '@prestashop.adapter.tax_rules_group.repository.tax_rules_group_repository'
+      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
+      - '@prestashop.adapter.country.repository.country_repository'
```
Comment (Amoifr) [inline src/PrestaShopBundle/Resources/config/services/adapter/tax.yml]: is this change introduce a BC break ?

**Review by Amoifr — COMMENTED** [review]
Tks for this PR, I've just mention some detail

File: src/PrestaShopBundle/Resources/config/services/adapter/tax.yml (hunk 16 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Resources/config/services/adapter/tax.yml]: according to recent ADR https://github.com/PrestaShop/ADR/blob/master/0017-backward-compatibility-promise.md
Screenshot from 2022-08-04 11-32-38

As long as class instantiation is delegated to container, it is not a BC break. And thats the case (tax computer is a service defined in container services configuration and is not designed to be instantiated manually). So no BC break here as far as I understand.

File: src/Adapter/Country/Repository/CountryRepository.php (hunk 15 above)
Comment (zuk3975) [reply src/Adapter/Country/Repository/CountryRepository.php]: When reviewing, please try to be more specific about your suggestion. Its not always so intuitive to "guess" whats your point of some questions :stuck_out_tongue: 

If I got your intentions right, - see other repositories they all use get() method, its quite common practice to not be too specific for these main common methods). Idea is that its already a repository dedicated for country and the typehint also suggests already that we search by countryId, so its not worth adding that "byCountryId" suffix

File: src/Adapter/Country/Repository/CountryRepository.php (hunk 14 above)
Comment (margud) [reply src/Adapter/Country/Repository/CountryRepository.php]: the issue with inline return is that phpstan thinks we are returning ObjectModel and not Country. So we need to tell its Country by adding this typehint:
        /** @var Country $country */
Thats why in most cases its not inline return.

File: tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature (hunk 13 above)
Comment (margud) [reply tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature]: I can remove some test but i think because of cache its better to have it in different file. It fails in the same file and i think it would be difficult to clear all cache in middle of file. To avoid not needed difficulties i prefer to have it in new file but yeah maybe not all test are needed. What do you think @jolelievre @zuk3975

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 17]
```diff
@@ -166,15 +187,26 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
                 'label' => $this->trans('Tax rule', 'Admin.Catalog.Feature'),
-                'help' => !$this->isTaxEnabled ? $this->trans('Tax feature is disabled, it will not affect price tax included.', 'Admin.Catalog.Feature') : '',
+                'help' => !$this->isTaxEnabled ?
+                    $this->trans('Tax feature is disabled, it will not affect price tax included.', 'Admin.Catalog.Feature')
+                    : $this->trans(
+                        $taxGroupHelpText,
+                        'Admin.Catalog.Feature',
+                        ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => $selectedTaxRate, '%3s$s' => $stateIsoCode]
+                    ),
+                'help_attr' => ['class' => 'js-tax-rule-help',
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
                'help_attr' => [
                    'class' => 'js-tax-rule-help',
```

File: admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts [hunk 18]
```diff
@@ -221,6 +226,12 @@ export default class ProductFormModel {
           'price.priceTaxIncluded',
           priceTaxExcluded.times(taxRatio).plus(ecotaxTaxIncluded).toFixed(this.precision),
         );
+        const placeHolder = $('.js-tax-rule-help').data('place-holder');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]:
```suggestion
        const placeHolder = this.$taxRuleGroupHelpLabel.data('place-holder');
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 19]
```diff
@@ -130,6 +139,18 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+        $selectedTaxRate = $this->taxComputer->getTaxRate(new TaxRulesGroupId($options['tax_rules_group_id']), new CountryId($this->contextCountryId));
+        $country = new Country($this->contextCountryId);
+        $taxGroupHelpText = 'Tax %1$s : %2$s%%';
+        $stateIsoCode = '';
+        if ($country->contains_states) {
+            $taxRules = \TaxRule::getTaxRulesByGroupId($this->contextLangId, $options['tax_rules_group_id']);
+            $firstTaxRule = reset($taxRules);
+            $state = new State($firstTaxRule['id_state']);
+            $stateIsoCode = $state->iso_code;
+            $taxGroupHelpText = 'Tax %1$s-%3$s: %2$s%%';
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: Iy you use a dynamic wording stored in a variable our TranslationTool won't be able to extract these new wordings So instead you should handle both use case and call trans in each one of them

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
            $taxRateHelpPlaceholder = $this->trans(
                'Tax %1$s-%3$s: %2$s%%',
                'Admin.Catalog.Feature',
                [
                    '%1$s' => Country::getIsoById($this->contextCountryId),
                    '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_',
                    '%3s$s' => $stateIsoCode
                ]
            );
        else {
            $taxRateHelpPlaceholder = $this->trans(
                'Tax %1$s : %2$s%%',
                'Admin.Catalog.Feature',
                [
                    '%1$s' => Country::getIsoById($this->contextCountryId),
                    '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_',
                ]
            );
```

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: Similar thing for the actual help text since you need to inject actual values

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 20]
```diff
@@ -251,12 +282,15 @@ public function configureOptions(OptionsResolver $resolver)
         $resolver->setDefaults([
             'label' => $this->trans('Retail price', 'Admin.Catalog.Feature'),
             'label_tag_name' => 'h3',
-            'required' => false,
+            'required' => ['tax_rules_group_id'],
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
            'required' => false,
```

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: I think you're confusing the `tax_rules_group_id` which is now a required option and the `required` option which is here to avoid a required asterix next to the field

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 21]
```diff
@@ -53,26 +70,38 @@ public function getChoices()
...
+
+        $taxRates = [];
         foreach ($this->getRules() as $rule) {
-            // Keep first one found
-            if (!empty($attrs[$rule['name']]['data-tax-rate'])) {
-                continue;
+            if ($country->contains_states) {
+                $taxRules = \TaxRule::getTaxRulesByGroupId($this->langId, $rule['id_tax_rules_group']);
+                $firstTaxRule = reset($taxRules);
+                $address->id_state = $firstTaxRule['id_state'] ?? null;
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: You are implementing this same thing in several places
I think this could be simplified if it's integrated into the `TaxManagerFactory::getManager` this can be performed when the provided address has a country that contains states but no explicit state defined This should simplify all these classes:
- TaxRuleGroupChoiceProvider
- TaxComputer
- RetailPriceType

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Especially in this service, you perform it outside the loop and inside the loop so it's not optimized, the initial one outside the loop is probably overkill

File: package-lock.json [hunk 22]
```diff
@@ -0,0 +1,6 @@
+{
+  "name": "prestashopCore8",
```
Comment (jolelievre) [inline package-lock.json]: I don't think we need this file in the project's root

File: src/Adapter/Country/Repository/CountryRepository.php (hunk 14 above)
Comment (jolelievre) [reply src/Adapter/Country/Repository/CountryRepository.php]: Damn PHPStan 😅

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 23]
```diff
@@ -53,26 +70,38 @@ public function getChoices()
      */
     public function getChoicesAttributes(): array
     {
-        $attrs = [];
+        $address = new Address();
+        $address->id_country = $this->countryId;
+        $country = new \Country($this->countryId);
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Please add use statements for Country and State and TaxRule

File: src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/TaxRulesGroup/Repository/TaxRulesGroupRepository.php:70]: If it's not used anymore it's fine to clean it since the code is still experimental

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php [hunk 24]
```diff
@@ -65,7 +65,10 @@ public function __construct(
     public function buildForm(FormBuilderInterface $builder, array $options)
     {
         $builder
-            ->add('retail_price', RetailPriceType::class)
+            ->add('retail_price', RetailPriceType::class, [
+                'tax_rules_group_id' => $options['tax_rules_group_id'],
+            ]
+            )
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/PricingType.php]:
```suggestion
            ])
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 25]
```diff
@@ -130,6 +139,18 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             $ecotaxRate = new DecimalNumber('0');
         }
 
+        $selectedTaxRate = $this->taxComputer->getTaxRate(new TaxRulesGroupId($options['tax_rules_group_id']), new CountryId($this->contextCountryId));
+        $country = new Country($this->contextCountryId);
+        $taxGroupHelpText = 'Tax %1$s : %2$s%%';
+        $stateIsoCode = '';
+        if ($country->contains_states) {
+            $taxRules = \TaxRule::getTaxRulesByGroupId($this->contextLangId, $options['tax_rules_group_id']);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: We never use the localized values from this method so I don't think this function is adapted because:
- it returns much more data than we need
- it forces us to provide a languegId thus complexifying the form type for a useless info

Maybe there is another method which returns similar info (the purpose is to get the first state associated to a tax rule), and if there is none we can create a new method dedicated for this use, in which case it could even return the first one automatically and return type would be `int` which would simplify all the related codes even more

Or maybe it could be done in the more recent `TaxRulesGroupRepository` (see other comments about this service)

File: src/Adapter/Tax/TaxComputer.php [hunk 26]
```diff
@@ -43,17 +45,25 @@ class TaxComputer
     protected const DIVISION_PRECISION = Division::DEFAULT_PRECISION + 2;
 
     /**
-     * @var TaxRulesGroupRepository
```
Comment (jolelievre) [inline src/Adapter/Tax/TaxComputer.php]: You removed the repository here to replace everything with legacy code which was the exact opposite idea of this service initially 😅 I don't mind if the previous `getTaxRulesGroupDetails` function is not adapted anymore and needs to be replaced

But at least the new code should follow the same spirit to replace legacy code, so you can probably add a new method or maybe modify the existing `getTaxRulesGroupDetails` to meet your needs

And as I already suggested in other comments for a refacto to avoid duplicating all the logic related with the first state, I think this class and method would actually be good candidates And as I said in another comment, the language has nothing to do here since we don't need localized values It's only here because it's used `getTaxRulesByGroupId` but most of the returned data has no interest here so instead you can implement a new request in the `TaxRulesGroupRepository` Either it returns all the states and you pick the first here, or it returns the first one automatically like `getCountryDefaultState` which you might need in the form type as well to adapt the wording

File: src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php [hunk 27]
```diff
@@ -46,6 +46,7 @@ public function getOptions(int $id, array $data): array
             'product_type' => $data['header']['type'] ?? ProductType::TYPE_STANDARD,
             'virtual_product_file_id' => $data['stock']['virtual_product_file']['virtual_product_file_id'] ?? null,
             'active' => $data['header']['active'] ?? false,
+            'tax_rules_group_id' => $data['pricing']['retail_price']['tax_rules_group_id'] ?? null,
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php:49]: Just to be sure did you check a use case where you change the tax rules and then submit the form with invalid values somewhere else? Just to make sure that on submit the help message is correctly adapted with the new value and not the initial one?

File: src/Adapter/Tax/TaxComputer.php (hunk 26 above)
Comment (jolelievre) [reply src/Adapter/Tax/TaxComputer.php]: Or alternatively maybe the `getTaxRulesGroupDetails` could return tax rate values for each states the country contains also, or it could have an optional stateId parameter to specify the targetted state

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php (hunk 17 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: Also, I'm quite surprised that you can add a `help_attr` so easily without handling it in a form extension because the `help` option was added by us here  https://github.com/PrestaShop/PrestaShop/blob/ff96226eae149d58b34ca6c5228b846595d05914/src/PrestaShopBundle/Form/Admin/Extension/HelpTextExtension.php#L47

Does it mean Symfony already handles a native `help_attr` option? 🤔

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: Oh, actually it does!! https://github.com/symfony/form/blob/4.4/Extension/Core/Type/FormType.php#L198

It also handles the `help` option which means our extension is probably completely overkilled 😅

File: src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig [hunk 28]
```diff
@@ -1161,7 +1161,7 @@
 
 {% block form_help %}
   {% if help is not null %}
-    <small class="form-text">{{ help|raw }}</small>
+    <small class="form-text {% if help_attr.class is defined %}{{ help_attr.class }}{% endif %}" {% if help_attr.placeholder is defined %} data-place-holder="{{ help_attr.placeholder }}" {% endif%}>{{ help|raw }}</small>
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig]: You can probably use similar code to the original Symfony form theme for this params:

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Twig/Resources/views/Form/form_div_layout.html.twig#L305-L306

Except we don't need the default class maybe, oh actually we do have one!! `form-text`

File: tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php [hunk 29]
```diff
@@ -66,9 +66,12 @@ public function __construct()
      */
     public function createTax(string $taxReference, TableNode $table): void
     {
-        $data = $table->getRowsHash();
+        // we don't want to duplicate taxes if they already exist
+        if (SharedStorage::getStorage()->exists($taxReference)) {
+            return;
+        }
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php]:
```suggestion
```

I disagree there are many use cases in our behat tests where we use the same reference several times, it's probably not the best idea but regardless if a reference is used multiple times to create an entity the it should be created regardless and replaced

File: tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php [hunk 30]
```diff
@@ -264,6 +267,11 @@ private function createTaxUsingCommand(string $taxReference, array $data): void
      */
     public function addTaxRuleGroupToTax(string $taxGroupReference, string $taxReference, TableNode $table)
     {
+        // we don't want to duplicate taxes if they already exist
+        if (SharedStorage::getStorage()->exists($taxGroupReference)) {
+            return;
+        }
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php]:
```suggestion
```
Same comment here

File: tests/Integration/Behaviour/Features/Scenario/Product/update_product_type.feature [hunk 31]
```diff
@@ -1,4 +1,7 @@
 # ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s product --tags update-product-type
+@restore-all-tables-before-feature
+@reboot-kernel-before-feature
+@clear-cache-before-feature
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/update_product_type.feature]:
```suggestion
```
This behat scenario already has a restore policy based on `@restore-products-before-feature` so restoring the tables twice will only make the test longer for no reason

As for the clear cache and kernel reboot before it shouldn't be its responsibility, it didn't need it previously so if something has been messed in the cache and kernel services it means it's an impact from another feature executed before So I guess it comes from `update_prices_without_states.feature` so it's the responsibility of the previous feature to clean correctly after its execution

If we leave the cleaning to the following one it means the next time we add another feature in between (because of alphabetical order) then it will be this new feature which will need to clean And on some environment the alphabetical order is not strictly the same so it becomes even more a nightmare All the more reason to leave the cleaning to the one responsible for it

File: tests/Unit/Adapter/Tax/TaxComputerTest.php (hunk 12 above)
Comment (jolelievre) [reply tests/Unit/Adapter/Tax/TaxComputerTest.php:40]: I disagree the class was previously unit testable because we mocked the query results If it's not possible anymore it probably means the architecture has been improperly modified (but I already commented on this part earlier ^^)

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @margud 

The generic principle seems fine, but there are many modifications in the architecture which reduce the code quality and are not acceptable

File: tests/Unit/Adapter/Tax/TaxComputerTest.php (hunk 12 above)
Comment (margud) [reply tests/Unit/Adapter/Tax/TaxComputerTest.php:40]: We mocked it because we used custom repository to get basic tax group without any calculations. Now we use TaxManagerFactory that has to be called static for each tax group and it has sql inside it. So there is no way to mock it. Atleast i don't know how to mock it without being able to inject it into constructor.

File: src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php (hunk 27 above)
Comment (margud) [reply src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php:49]: Don't really get it what to check here. By invalid values somewhere you mean invalid values in product form?

File: admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts [hunk 32]
```diff
@@ -125,6 +130,19 @@ export default class ProductFormModel {
...
+    const $taxRulesGroupIdInput: JQuery<HTMLElement> | undefined = this.mapper.getInputsFor('price.taxRulesGroupId');
+
+    if (!$taxRulesGroupIdInput) {
+      console.error('Could not find tax rules input');
+      return '';
+    }
+
+    const $selectedTaxOption = $(':selected', $taxRulesGroupIdInput);
+
+    return $selectedTaxOption.data('stateIsoCode');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]:
```suggestion
    return $selectedTaxOption.data('stateIsoCode') ?? '';
```

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]: This should guaranty that a string is always returned even if data attribute is absent

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 33]
```diff
@@ -130,6 +140,40 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
 
+        $selectedTaxRate = $this->taxComputer->getTaxRate(new TaxRulesGroupId($options['tax_rules_group_id']), new CountryId($this->contextCountryId));
+        $country = new Country($this->contextCountryId);
+
+        $taxRatePlaceHolder = $this->trans(
+            'Tax %1$s : %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => $selectedTaxRate]
+        );
+        $taxRateHelpPlaceholderWithoutTax = $this->trans(
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
        $taxRateHelpPlaceholderWithoutState = $this->trans(
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 34]
```diff
@@ -130,6 +140,40 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+            'Tax %1$s : %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_']
+        );
+        $taxRateHelpPlaceholderWithTax = $this->trans(
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
        $taxRateHelpPlaceholderWithState = $this->trans(
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 35]
```diff
@@ -166,15 +210,23 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
                 'label' => $this->trans('Tax rule', 'Admin.Catalog.Feature'),
-                'help' => !$this->isTaxEnabled ? $this->trans('Tax feature is disabled, it will not affect price tax included.', 'Admin.Catalog.Feature') : '',
+                'help' => !$this->isTaxEnabled ?
+                    $this->trans('Tax feature is disabled, it will not affect price tax included.', 'Admin.Catalog.Feature')
+                    : $taxRatePlaceHolder,
+                'help_attr' => [
+                    'class' => 'js-tax-rule-help',
+                    'data' => [
+                        'place-holder-without-tax' => $taxRateHelpPlaceholderWithoutTax,
+                        'place-holder-with-tax' => $taxRateHelpPlaceholderWithTax,
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
                        'place-holder-without-state' => $taxRateHelpPlaceholderWithoutState,
                        'place-holder-with-state' => $taxRateHelpPlaceholderWithState,
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 36]
```diff
@@ -130,6 +140,40 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+
+        $taxRatePlaceHolder = $this->trans(
+            'Tax %1$s : %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => $selectedTaxRate]
+        );
+        $taxRateHelpPlaceholderWithoutTax = $this->trans(
+            'Tax %1$s : %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_']
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
            ['%1$s' => $country->iso_code, '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_']
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 37]
```diff
@@ -130,6 +140,40 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             $ecotaxRate = new DecimalNumber('0');
         }
 
+        $selectedTaxRate = $this->taxComputer->getTaxRate(new TaxRulesGroupId($options['tax_rules_group_id']), new CountryId($this->contextCountryId));
+        $country = new Country($this->contextCountryId);
+
+        $taxRatePlaceHolder = $this->trans(
+            'Tax %1$s : %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => $selectedTaxRate]
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
            ['%1$s' => $country->iso_code, '%2$s' => $selectedTaxRate]
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 38]
```diff
@@ -130,6 +140,40 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+        );
+        $taxRateHelpPlaceholderWithoutTax = $this->trans(
+            'Tax %1$s : %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_']
+        );
+        $taxRateHelpPlaceholderWithTax = $this->trans(
+            'Tax %1$s-%3$s: %2$s%%',
+            'Admin.Catalog.Feature',
+            ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_', '%3s$s' => '_STATE_ISO_CODE_HELP_PLACEHOLDER_']
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
            ['%1$s' => $country->iso_code, '%2$s' => '_TAX_RATE_HELP_PLACEHOLDER_', '%3s$s' => '_STATE_ISO_CODE_HELP_PLACEHOLDER_']
```

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 39]
```diff
@@ -130,6 +140,40 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+            $stateId = $this->taxRulesGroupRepository->getTaxRulesGroupDefaultStateId(
+                new TaxRulesGroupId($options['tax_rules_group_id']),
+                new CountryId($this->contextCountryId)
+            );
+            if ($stateId) {
+                $state = new State($stateId);
+                $taxRatePlaceHolder = $this->trans(
+                    'Tax %1$s-%3$s: %2$s%%',
+                    'Admin.Catalog.Feature',
+                    ['%1$s' => Country::getIsoById($this->contextCountryId), '%2$s' => $selectedTaxRate, '%3s$s' => $state->iso_code]
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]:
```suggestion
                    ['%1$s' => $country->iso_code, '%2$s' => $selectedTaxRate, '%3s$s' => $state->iso_code]
```

File: src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig [hunk 40]
```diff
@@ -1161,7 +1161,11 @@
 
 {% block form_help %}
   {% if help is not null %}
-    <small class="form-text">{{ help|raw }}</small>
+    <small class="form-text {% if help_attr.class is defined %}{{ help_attr.class }}{% endif %}"
+        {% if help_attr.data is defined %}
+          {% for data, value in help_attr.data %} data-{{ data }}="{{ value }}" {% endfor%}
+        {% endif%}>
+      {{ help|raw }}</small>
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig]:
```suggestion
        {%- set help_attr = help_attr|merge({class: (help_attr.class|default('') ~ ' form-text')|trim}) -%}
        <small id="{{ id }}_help"{% with { attr: help_attr } %}{{ block('attributes') }}{% endwith %}>{{ help|raw }}</small>
```

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig]: I already suggested it in a previous comment but you should use this code from the Symfony form theme, it is more adaptable and will serve more use cases.

File: admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts [hunk 41]
```diff
@@ -221,6 +240,28 @@ export default class ProductFormModel {
           'price.priceTaxIncluded',
           priceTaxExcluded.times(taxRatio).plus(ecotaxTaxIncluded).toFixed(this.precision),
         );
+        const placeHolderWithoutTax = this.$taxRuleGroupHelpLabel.data('place-holder-without-tax');
+        const placeHolderWithTax = this.$taxRuleGroupHelpLabel.data('place-holder-with-tax');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]:
```suggestion
        const placeHolderWithoutState = this.$taxRuleGroupHelpLabel.data('place-holder-without-state');
        const placeHolderWithState = this.$taxRuleGroupHelpLabel.data('place-holder-with-state');
```

File: admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts [hunk 42]
```diff
@@ -221,6 +240,28 @@ export default class ProductFormModel {
...
+
+        let newString;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]:
```suggestion
        let helpLabel;
```

File: classes/tax/TaxManagerInterface.php [hunk 43]
```diff
@@ -44,4 +44,6 @@ public static function isAvailableForThisAddress(Address $address);
      * @return TaxCalculator
      */
     public function getTaxCalculator();
+
+    public function getAddress(): Address;
```
Comment (jolelievre) [inline classes/tax/TaxManagerInterface.php]: You don't need this extra function in the interface nor in the TaxRulesTaxManager (see the comment in TaxRuleGroupChoiceProvider)

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 44]
```diff
@@ -53,26 +75,32 @@ public function getChoices()
...
-            }
+            $taxRulesGroupId = new TaxRulesGroupId((int) $rule['id_tax_rules_group']);
+            $stateId = $this->taxRulesGroupRepository->getTaxRulesGroupDefaultStateId($taxRulesGroupId, new CountryId($this->countryId));
+            $address->id_state = $stateId;
 
-            $attrs[$rule['name']] = [
-                'data-tax-rate' => !empty($rule['rate']) ? $rule['rate'] : 0,
+            $taxManagerFactory = TaxManagerFactory::getManager($address, $taxRulesGroupId->getValue());
+            $taxRate = $taxManagerFactory->getTaxCalculator()->getTotalRate();
+            $state = new State($taxManagerFactory->getAddress()->id_state);
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
            $state = new State($stateId);
```

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
            $state = new State($address->id_state);
```

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: You have two other possibilities to get this data so no need to add a function on the tax manager interface which is not useful and out of the initial scope of the interface

File: src/Adapter/Tax/TaxComputer.php [hunk 45]
```diff
@@ -100,15 +102,14 @@ public function computePriceWithoutTaxes(
...
     public function getTaxRate(TaxRulesGroupId $taxRulesGroupId, CountryId $countryId): DecimalNumber
     {
-        $taxRulesGroup = $this->taxRulesGroupRepository->getTaxRulesGroupDetails($taxRulesGroupId);
-        if (!empty($taxRulesGroup['rates'])) {
-            // Use the tax rate associated to context country, or the first one as fallback
-            $countryTaxRate = $taxRulesGroup['rates'][$countryId->getValue()] ?? reset($taxRulesGroup['rates']);
-        } else {
-            $countryTaxRate = 0;
-        }
+        $address = new Address();
```
Comment (jolelievre) [inline src/Adapter/Tax/TaxComputer.php:111]: I think you should create another method `public function getTaxRateByState(TaxRulesGroupId $taxRulesGroupId, CountryId $countryId, StateId $stateId): DecimalNumber`

It would be used in this method when a default state has been found, and it could also be used in `TaxRuleGroupChoiceProvider` when you loop through all the tax rules. This way the choice provider doesn't need to compute the tax rate itself (and duplicate some code at the same time). The responsibility of tax computing is all centered in this service, meaning less duplicated code and a single place to modify if one day we need to fix this.

But it also allows you to get the stateId in advance in the provider (since you need it to get the ISO code) without performing duplicate requests for nothing.

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php (hunk 44 above)
Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Besides you should only fetch the state when `$stateId` is different from 0 this will avoid many useless queries (as most countries don't have states).

```suggestion
            $stateIsoCode = '';
            if ($stateId > 0) {
                $state = new State($stateId);
                $stateIsoCode = $state->iso_code;
            }
```

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 46]
```diff
@@ -53,26 +75,32 @@ public function getChoices()
...
+        return $taxRates;
     }
 
     /**
      * @return array
      */
     private function getRules(): array
     {
-        return TaxRulesGroup::getTaxRulesGroupsForOptions();
+        return TaxRulesGroup::getTaxRulesGroups();
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Be careful since you replaced `getTaxRulesGroupsForOptions` by `getTaxRulesGroups` it means you don't have the `No tax` option anymore which was initially added by the legacy code here:

https://github.com/PrestaShop/PrestaShop/blob/d0f9edeb15b7c1b249d8b7fdb692987d3270f6f2/classes/tax/TaxRulesGroup.php#L159-L162

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: Why did you change this? If the idea is to optimize the initial query because you don't get the rate the same way why not, but then you have to add the `No tax` option manually here.

If it's another reason I'm curious to understand why?

File: src/Adapter/Country/Repository/CountryRepository.php (hunk 15 above)
Comment (jolelievre) [inline src/Adapter/Country/Repository/CountryRepository.php]: This method is not used anymore with the latest implementation. You could either inject this service to use it in the providers or TaxManager services to make it useful, although it's a suggestion, not a mandatory change.

If you don't you can remove the method since it's used nowhere, or you can leave it since we'll probably need it in the future as the repositories become more and more used. It's up to you, I don't have a closed opinion on this one.

File: tests/Unit/Adapter/Tax/TaxComputerTest.php (hunk 12 above)
Comment (jolelievre) [reply tests/Unit/Adapter/Tax/TaxComputerTest.php:40]: You're right with the latest changes it's not mockable anymore. Then we should move this test into integration tests, so that we have access to the database and taxes installed with the default features. This will allow us to perform a few tests based on the data from fixtures.

File: src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php (hunk 27 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php:49]: Yes, the idea is to force an invalid constraint in the form, for example use `<` in the reference input, this will be considered invalid, and the form is submitted and displayed again with inline errors. All the submitted values (including the reference) should be populated inside the form.

At this moment the previously selected tax rules should still be the one selected in the select input, and its help message should match the one you selected (country, potential state, tax rate, ...)

File: tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature [hunk 47]
```diff
@@ -0,0 +1,280 @@
+# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s product --tags update-prices-without-states
+@restore-all-tables-before-feature
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature]: Regarding the database strategy for clearing I think the most effective would be to use `@restore-products-before-feature` here, at the beginning of the scenario it should be enough

However since you also create taxes and taxe rules it's not enough to clear after the scenario so you could introduce a new tag in CommonFeatureContext:

```php
    /**
     * This hook can be used to flag a feature for database hard reset
     *
     * @BeforeFeature @restore-all-tables-after-feature
     */
    public static function restoreAllTablesAfterFeature()
    {
        DatabaseDump::restoreAllTables();
        require_once _PS_ROOT_DIR_ . '/config/config.inc.php';
    }
```

This way you can use `@restore-all-tables-after-feature` in this scenario to make sure the DB is correctly reset at the end of the feature. And it shouldn't have that much impact on the following feature even if it uses `@restore-products-before-feature` since the tables will already have been reset (the reset checks if any modification is in the DB)

File: tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature [hunk 48]
```diff
@@ -0,0 +1,280 @@
...
+@reboot-kernel-before-feature
+@clear-cache-before-feature
+@update-product-prices
+@update-prices-without-states
+@reboot-kernel-after-feature
+@clear-cache-after-feature
+Feature: Update product price fields from Back Office (BO).
+  As a BO user I want to be able to update product fields associated with price.
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature]: The description of the feature should explain the purpose of those tests Because honestly, I wonder what is the purpose here since all the scenarios look very much like the ones from `update_prices.feature` except for the tax rule related to France but does it really change so much?

Not that having too many behat tests is really an issue anyway 😅

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

Sorry a lot of comments again 😅 This is really a complex topic, but we're getting close 😉

File: tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_prices.feature [hunk 49]
```diff
@@ -2,7 +2,6 @@
 @restore-products-before-feature
 @clear-cache-before-feature
 @product-combination
-@update-product-prices
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/Combination/update_combination_prices.feature]: This tag was actually added to easily launch all the features related to prices, whether it's from a combination or regular product
It's convenient during the development phase and debugging to check everything is fine since all those features may be related without realizing it So I think it should stay here and you should add it to `update-prices-without-states.feature` as well

File: tests/Integration/Behaviour/behat.yml [hunk 50]
```diff
@@ -348,6 +348,7 @@ default:
                 - Tests\Integration\Behaviour\Features\Transform\LocalizedArrayTransformContext
                 - Tests\Integration\Behaviour\Features\Transform\StringToArrayTransformContext
                 - Tests\Integration\Behaviour\Features\Transform\StringToBoolTransformContext
+                - Tests\Integration\Behaviour\Features\Context\Domain\TaxFeatureContext
```
Comment (jolelievre) [inline tests/Integration/Behaviour/behat.yml]: Please try to keep the alphabetical order in the context list, it reduces risks of collision from multiple PRs and it allows finding contexts more easily by search when needed This one should be a few lines above after `Tests\Integration\Behaviour\Features\Context\Domain\SupplierFeatureContext`

File: tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature [hunk 51]
```diff
@@ -0,0 +1,278 @@
+# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s product --tags update-prices-without-states
+@restore-products-before-feature
+@reboot-kernel-before-feature
+@update-prices-without-states
+@reboot-kernel-after-feature
+@restore-all-tables-after-feature
+Feature: Update product price fields from Back Office (BO) when default country has no states.
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/update_prices_without_states.feature:9]: Testing a country with states makes sense, however we don't really test the use case that interests us here When a country has multiple states then the default one is the first one To test this it's worth having a new feature where you create/edit a country with states and remove the first one to ensure the default tax rate is then updated

File: tests/Integration/Adapter/Tax/TaxComputerTest.php [hunk 52]
```diff
@@ -0,0 +1,136 @@
...
+    {
+        self::bootKernel();
+        $container = self::$kernel->getContainer();
+        $this->taxComputer = $container->get('prestashop.adapter.tax.tax_computer');
+    }
+
+    /**
+     * @dataProvider getComputePriceData
+     */
+    public function testComputePriceWithTaxes(float $taxRate, int $countryId, int $stateId, string $priceWithoutTaxes, string $priceWithTaxes): void
```
Comment (jolelievre) [inline tests/Integration/Adapter/Tax/TaxComputerTest.php]: Those new tests are really nice, thanks!
Now that the basic tests are here you should add some to test `getTaxRate`, especially for special use cases where we need to choose the default state

File: classes/tax/TaxManagerInterface.php (hunk 43 above)
Comment (jolelievre) [reply classes/tax/TaxManagerInterface.php]: This method is still not really needed, I already commented in other places how it could be removed with a bit of refacto on your modifications

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 53]
```diff
@@ -53,26 +75,32 @@ public function getChoices()
...
-                continue;
-            }
+            $taxRulesGroupId = new TaxRulesGroupId((int) $rule['id_tax_rules_group']);
+            $stateId = $this->taxRulesGroupRepository->getTaxRulesGroupDefaultStateId($taxRulesGroupId, new CountryId($this->countryId));
+            $address->id_state = $stateId;
 
-            $attrs[$rule['name']] = [
-                'data-tax-rate' => !empty($rule['rate']) ? $rule['rate'] : 0,
+            $taxManagerFactory = TaxManagerFactory::getManager($address, $taxRulesGroupId->getValue());
+            $taxRate = $taxManagerFactory->getTaxCalculator()->getTotalRate();
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
            $taxRate = $this->taxComputer->getTaxRateByState($taxRulesGroupId, new CountryId($this->countryId), new State($stateId));
```

Comment (jolelievre) [reply src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]: I you implement the `getTaxRateByState` as I suggested in TaxComputer comments, the this service doesn't need to reimplement this logic it is all handled in TaxComputer

File: tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php [hunk 54]
```diff
@@ -277,9 +275,36 @@ public function addTaxRuleGroupToTax(string $taxGroupReference, string $taxRefer
         $taxRule = new TaxRule();
         $taxRule->id_tax = $tax->id;
         $taxRule->id_tax_rules_group = $taxRulesGroup->id;
-        $taxRule->behavior = 1;
+        $taxRule->behavior = 0;
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php]: This changes the initial behaviour, although I'm not sure if the value 0 is correctly handled when I look into the code of TaxCalculator, seems like it can only handle `TaxCalculator::COMBINE_METHOD` (1) or `TaxCalculator::ONE_AFTER_ANOTHER_METHOD` (2) but doesn't really handle the 0 value which is "this tax only"

File: tests/Integration/Adapter/Tax/TaxComputerTest.php [hunk 55]
```diff
@@ -0,0 +1,166 @@
...
+        yield [21.3, $country->id, [$stateId], '10.00', '12.13', 0];
+        yield [14.7, $country->id, [$stateId], '8.00', '9.176', 0];
+        // tax rate is rounded to 3.148
+        yield [3.14769, $country->id, [$stateId], '8.666', '8.93880568', 0];
+
+        $secondState = $states[1];
+        $secondStateId = (int) $secondState['id_state'];
+
+        /* taxes for countries with states and tax has multiple states and only first one should be taken */
+        yield [20.0, $country->id, [$stateId, $secondStateId],  '10.00', '12.00', 1];
```
Comment (jolelievre) [inline tests/Integration/Adapter/Tax/TaxComputerTest.php]:
```suggestion
        yield [20.0, $country->id, [$stateId, $secondStateId],  '10.00', '12.00', TaxCalculator::COMBINE_METHOD];
```

Comment (jolelievre) [reply tests/Integration/Adapter/Tax/TaxComputerTest.php]: We should use the existing const to understand the code here better, and I think one const is missing in TaCalculator we should add `public const ONE_TAX_ONLY_METHOD = 0;`

File: src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php (hunk 27 above)
Comment (margud) [reply src/Core/Form/IdentifiableObject/OptionProvider/ProductFormOptionsProvider.php:49]: yeah there was issue when some inputs are invalid but now its fixed.

File: tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php (hunk 54 above)
Comment (margud) [reply tests/Integration/Behaviour/Features/Context/Domain/TaxFeatureContext.php]: I looked into it and all the test where using one tax only, so it didn't matter what behavior is used, but i think by default it makes more sense to test the default logic that is 0- one tax only and for 1-tax combined use specific tests.

File: admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts [hunk 56]
```diff
@@ -241,4 +253,44 @@ export default class ProductFormModel {
...
+    }
+    const stateIsoCode = this.getStateIsoCode();
+    const priceTaxExcluded = this.mapper.getBigNumber('price.priceTaxExcluded') ?? new BigNumber(0);
+    const ecotaxTaxIncluded = this.mapper.getBigNumber('price.ecotaxTaxIncluded') ?? new BigNumber(0);
+    this.mapper.set(
+      'price.priceTaxIncluded',
+      priceTaxExcluded.times(taxRatio).plus(ecotaxTaxIncluded).toFixed(this.precision),
+    );
+    const placeHolderWithoutTax = this.$taxRuleGroupHelpLabel.data('place-holder-without-state');
+    const placeHolderWithTax = this.$taxRuleGroupHelpLabel.data('place-holder-with-state');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]:
```suggestion
    const placeHolderWithoutState = this.$taxRuleGroupHelpLabel.data('place-holder-without-state');
    const placeHolderWithState = this.$taxRuleGroupHelpLabel.data('place-holder-with-state');
```

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/edit/product-form-model.ts]: But you could actually only use one const here:

```js
    const taxPlaceholder = this.$taxRuleGroupHelpLabel.data(stateIsoCode ? 'placeholder-with-state' : 'placeholder-without-state');
    this.$taxRuleGroupHelpLabel.html(
      taxPlaceholder
        .replace(
          new RegExp('_TAX_RATE_HELP_PLACEHOLDER_', 'g'),
          taxRatio.minus(1).times(100).toPrecision(),
        )
        .replace(
          new RegExp('_STATE_ISO_CODE_HELP_PLACEHOLDER_', 'g'),
          stateIsoCode,
        )
    );
```

You replace even if the `_STATE_ISO_CODE_HELP_PLACEHOLDER_` is not in the string you don't care it ill simply do nothing, but at least the code is much smaller and a bit easier to read.

File: src/Adapter/Country/Repository/CountryRepository.php [hunk 57]
```diff
@@ -27,6 +27,7 @@
 
 namespace PrestaShop\PrestaShop\Adapter\Country\Repository;
 
+use Country;
```
Comment (jolelievre) [inline src/Adapter/Country/Repository/CountryRepository.php]: You can remove this one since you dropped the `get` method

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 58]
```diff
@@ -53,19 +82,26 @@ public function getChoices()
      */
     public function getChoicesAttributes(): array
     {
-        $attrs = [];
+        $address = new Address();
+        $address->id_country = $this->countryId;
+
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
```

You don't need an address object here anymore

File: src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php [hunk 59]
```diff
@@ -53,19 +82,26 @@ public function getChoices()
...
         foreach ($this->getRules() as $rule) {
-            // Keep first one found
-            if (!empty($attrs[$rule['name']]['data-tax-rate'])) {
-                continue;
+            $taxRulesGroupId = new TaxRulesGroupId((int) $rule['id_tax_rules_group']);
+            $stateId = $this->taxRulesGroupRepository->getTaxRulesGroupDefaultStateId($taxRulesGroupId, new CountryId($this->countryId));
+            if (!$stateId) {
+                $taxRate = $this->taxComputer->getTaxRate($taxRulesGroupId, new CountryId($this->countryId));
+            } else {
+                $taxRate = $this->taxComputer->getTaxRateByState($taxRulesGroupId, new CountryId($this->countryId), new StateId($stateId));
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/TaxRuleGroupChoiceProvider.php]:
```suggestion
            if (!$stateId) {
                $taxRate = $this->taxComputer->getTaxRate($taxRulesGroupId, new CountryId($this->countryId));
                $stateIsoCode = '';
            } else {
                $taxRate = $this->taxComputer->getTaxRateByState($taxRulesGroupId, new CountryId($this->countryId), new StateId($stateId));
                $state = new State($stateId);
                $stateIsoCode = $state->iso_code;
```

This will prevent instantiating a State all the time even when state ID is zero (which is most of the time)

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

Last suggestions and we're good, promise 😉

**Review by jolelievre — APPROVED** [review]
Thank you @margud

**Review by zuk3975 — APPROVED** [review]

**Review by davidPrestashop — APPROVED** [review]
Products v2
Create, update, delete tax rule
Screenshot from 2022-10-28 10-33-02

Screenshot from 2022-10-28 10-32-04

Screenshot from 2022-10-28 10-31-55

Screenshot from 2022-10-28 10-31-44

**Comment by jolelievre** [comment]
Thanks @boubkerbribri and @margud
