### PR TITLE
Simplify cart rule minimal value by avoiding subtracting values

### LINKED ISSUE #40409: $cart->getProductsGifts returns wrong data if multiple same gifts are in the cart
### Describe the bug and add attachments

`$cart->getProductsGifts` returns wrong data when there is the same product gifted multiple times.

### Steps to reproduce

Create two cart rules that give the same gift, so you have a following situation. 3 products of this type, 2 gifted, 1 normal.

Image

Now, if you delete the normally added one, `$cart->deleteProduct` gets called.

In `$cart->deleteProduct`, the cart asks itself _if the product being deleted is also gifted_.

If yes, it doesn't delete it, but only change the quantity to the gifts remaining.

However, if you look on this method and dump the data, it returns **only the number of product lines, not the quantity.** Which is wrong. Then, even the update query is wrong. The correct number should be 2 in this case, not 1.

```php
    protected function getProductsGifts($id_product, $id_product_attribute)
    {
        // GETS ALL GIFTS
        $gifts = array_filter($this->getProductsWithSeparatedGifts(), function ($product) {
            return array_key_exists('is_gift', $product) && $product['is_gift'];
        });

        $preservedGifts = [$id_product . '-' . $id_product_attribute => 0];

        // FOR EACH LINE
        foreach ($gifts as $gift) {
            if (
                (int) $gift['id_product_attribute'] === $id_product_attribute
                && (int) $gift['id_product'] === $id_product
            ) {
                 // JUST ADDS 1, BUT SHOULD ADD THE QUANTITY
                ++$preservedGifts[$id_product . '-' . $id_product_attribute];
            }
        }

        return $preservedGifts;
    }
```

Image

It has no effect on what you see on FO, because the quantity is probably fixed back somewhere later in autoAddToCart or cart rule verifications, but this should not happen. It can do some weird side effects somewhere.

### PrestaShop version(s) where the bug happened

9.0.2, but goes back probably all the way to 1.7.x

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | This PR allows `CartRule::checkValidity` to ask for cart total directly with gifts excluded. Without needing to do some subtracting magic, which can result in rounding errors and eats performance.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Run UI test.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/20525751567 🟢 
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/40409
| Related PRs       | 
| Sponsor company   | TRENDO s.r.o.

### Description
- `CartRule::checkValidity` when checking the minimal amount of order, first asked for cart products total, then subtracted all the gifts to get the real value. We now call it directly in one step, by using new cart calculation type `Cart::ONLY_PRODUCTS_WITHOUT_GIFTS`. So, I could then simplify the `CartRule::checkValidity` a lot and just remove the whole block of code.

### Benefits
- No need to call `$products = $cart->getProducts();`
- No need to call `$cart_rules = $cart->getCartRules(CartRule::FILTER_ACTION_ALL, false);`
- No possible rounding errors.
- Much cleaner, whole code of block removed.
- No BC break

### Other notes
- You may be confused a bit on the code - although `ONLY_PRODUCTS` should have returned the totals without gifts, it doesn't do so, because `is_gift` is never returned, at least the whole lifetime of 1.7. This dead code is removed and added a new constant `ONLY_PRODUCTS_WITHOUT_GIFTS`, which does this and asks for proper data, with gifts separated.
- I accidentaly discovered a possible race condition from my previous PRs, that wasn't a problem before. `getProductsGifts` returned is_gift even for a product that wasn't a gift anymore, because it was cached. `$this->_products = null;` and `$this->_products_with_separated_gifts = null;` should be wiped also with other static caches.
- The change inside `getProductsGifts` is a tiny refacto, so the method is simplier + a bug fix, which I found during testing of this.

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -1847,31 +1853,25 @@ public function deleteProduct(
...
-
-        $preservedGifts = [$id_product . '-' . $id_product_attribute => 0];
-
-        foreach ($gifts as $gift) {
-            if (
-                (int) $gift['id_product_attribute'] === $id_product_attribute
-                && (int) $gift['id_product'] === $id_product
-            ) {
-                ++$preservedGifts[$id_product . '-' . $id_product_attribute];
+        $giftCount = 0;
```
Comment (Hlavtox) [inline classes/Cart.php:1865]: This is just a tiny refacto of this method, no need for it to be complicated and loop it twice.
Plus a bug fix of a tiny issue I found. We need to use `$product['quantity']`.

File: classes/Cart.php [hunk 2]
```diff
@@ -262,6 +263,8 @@ public function resetProductRelatedStaticCache()
         if (isset(self::$_totalWeight[$this->id])) {
             unset(self::$_totalWeight[$this->id]);
         }
+        $this->_products = null;
```
Comment (Hlavtox) [inline classes/Cart.php:266]: This is moved because it must be wiped with `self::$_nbProducts`.

File: classes/Cart.php [hunk 3]
```diff
@@ -2044,7 +2047,16 @@ public function getOrderTotal(
         // If no specific products list is provided, we get the full list of products in cart
         // In most cases, we calculate the total for all products in cart
         if (null === $products) {
-            $products = $this->getProducts(false, false, null, true, $keepOrderPrices);
+            if ($type == Cart::ONLY_PRODUCTS_WITHOUT_GIFTS) {
```
Comment (Hlavtox) [inline classes/Cart.php:2050]: This is the main change in the PR. If we want a total without gifts, let's return it immediately. Not subtract the gifts from all products. :-)

**Review by ShaiMagal — DISMISSED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

**Comment by ShaiMagal** [comment]
Hello @Hlavtox, testing this:

## Before change

The breakpoint for cart rule works correctly, taking gifts in account, having following performance.

before_performance
before_not
before_with

## After change

The breakpoint for cart rule works perfectly still, taking gifts in account, having simmilar performance, but a less memory overhead. We already have good caching there so the db query count stay same. The effect will be greater with more products in cart and more cart rules on the shop.

after_performance
after_not
after_with

Tests green both CI and UI.

**Comment by Hlavtox** [comment]
@ShaiMagal Thanks bro!!

**Comment by kpodemski** [comment]
@Hlavtox @ShaiMagal 

guys, if not agreed with QA, committers should only test what's under the "Waiting for dev" label

this is the second time i'm seeing QA performed not by a QA member 🤔

**Comment by Hlavtox** [comment]
@kpodemski 

> guys, if not agreed with QA, committers should only test what's under the "Waiting for dev" label

It should be the developer who decides what to test or not.

> this is the second time i'm seeing QA performed not by a QA member 🤔

I asked him to test it, I think we can agree that @ShaiMagal is enough skilled to test a PR. :-)))

**Comment by Progi1984** [comment]
Ping @PrestaShop/qa-functional and @Robin-Fischer-PS : Rules about test are not applied

**Comment by Hlavtox** [comment]
To prevent further misunderstandings - https://github.com/PrestaShop/open-source/pull/302

**Comment by Hlavtox** [comment]
@Progi1984 I would like you to answer on a PR that is being stuck for a month because of automatic tests instead.

Also, please send a specific reference to rule stating that we must consult testing with the QA team.

**Comment by Progi1984** [comment]
@Hlavtox You are open to fix your PR. I'm not at the community's disposal. Sorry.

**Comment by Hlavtox** [comment]
@Progi1984 Ok, I will merge it next week, you can fix your test later

**Comment by Hlavtox** [comment]
@Progi1984 And Franck, I am just respecting the maintainer guide. 

As per guidelines for developer QA specified in https://www.prestashop-project.org/maintainers-guide/processes/reviewing-pull-requests/, there is no rule nowhere that I MUST consult doing a developer QA with QA team.

> Some other PRs may require QA by a developer, for example if the PR is very technical and does not change the behavior of the software. In that case, you can add Waiting for QA and Waiting for dev label. This should be discussed with QA functional team.

So, for the millionth time please, stop bothering us with your rules and let me live. :-)
