### PR TITLE
Fix: in the customer form from admin side, it is missing the newsletter option as Partner Offers

### LINKED ISSUE #40856: in the customer form from admin side, it is missing the newsletter option as Partner Offers
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue%20type%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've seen that in the customer edit page, from admin side, it is missing the newsletter option.
It should be present as the one for partner offers

Image

### Steps to reproduce

1. go in the admin panel
2. go in the customers list
3. push on the pen icon

### Expected behavior

near the checkbox for partner offers there should also be a checkbox for newsletters

### Actual Result

At the moment it is possible to activate and deactivate the newsletter option only from the customer list

### PrestaShop version where the bug happens

9.0.3

### How have you installed PrestaShop

git clone

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.1.x
| Description?      | This PR adds handling for the newsletter field in the admin Customer form.
| Type?             | improvement
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | 1. go to Customers > Customers<br>2. edit a customer<br>3. change the **Newsletter** field<br>4. verify that the field has been updated correctly
| UI Tests          | 🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/22297904886
| Fixed issue or discussion?     | Fixes #40856
| Related PRs       |
| Sponsor company   | Codencode snc

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 1]
```diff
@@ -260,6 +260,12 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 ),
                 'required' => false,
             ])
+            ->add('is_newsletter_subscribed', SwitchType::class, [
+                'label' => $this->trans('Newsletter', 'Admin.Orderscustomers.Feature'),
+                'help' => '',
+                'required' => false,
+                'disabled' => !$this->isPartnerOffersEnabled,
```
Comment (Touxten) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: I don't think it's appropriate here because these are partner offers and not newsletters.

Comment (Touxten) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: This only : `disabled' => !$this->isPartnerOffersEnabled,`

Comment (Codencode) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: You're right, I'll correct it immediately!
Thanks!

Comment (Codencode) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: @Touxten done

**Review by Touxten — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by Progi1984** [comment]
@Codencode There is two bugs : one for translation (fixed today by @jolelievre / updated in the next night), second on my side (will be fixed in the week).

**Comment by Codencode** [comment]
@Progi1984 
Ok, thanks!
Maybe ping me when you update it so I can restart the tests!
Thanks again!

**Comment by Codencode** [comment]
@Progi1984 @jolelievre the UI test changes you made work 💯!
Thanks!

**Review by paulnoelcholot — APPROVED** [review]
Hello @Codencode,

I tested your PR and it's good for me! 🎉 

Thanks!

Image

**Comment by Touxten** [comment]
Thanks you @paulnoelcholot && @Codencode
