### PR TITLE
Fixed combination with an hyphen in Stock Manager

### LINKED ISSUE #16706: Stock manager will not show combinations with "-" in name
When I create an attribute group named like this: "Example-name", the stock manager combination GUI is broken, where only the portion behind the "-" is shown. See screenshot.

Screenshot 2019-12-05 15 25 58
Screenshot 2019-12-05 15 27 17

PS 1.7.6.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed combination with an hyphen in Stock Manager
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16706
| How to test?  | * Build assets<br>* Create an attribute group named like this: "Example-name"<br>* Create values for this attribute group<br>* Create a product with combination with this attribute<br>* Go to Stock Manager<br>* **BEFORE**<br>image<br>* **AFTER**<br>image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20330)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 :) 

It's OK without space around the hyphen, but now if I write "attribut - test", I have the bug. See screenshot : 

pr20330 1

pr 20330 2

Thanks !

**Comment by NeOMakinG** [comment]
> Hi @Progi1984 :)
> 
> It's OK without space around the hyphen, but now if I write "attribut - test", I have the bug. See screenshot :
> 
> pr20330 1
> 
> pr 20330 2
> 
> Thanks !

I think the same thing happen on FO too, inside cart/checkout

File: admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ export default {
       const arr = this.product.combination_name.split(',');
       let attr = '';
       arr.forEach((attribute) => {
-        const value = attribute.split('-');
+        const value = attribute.split(' - ');
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js]: Because it depends on the `getAttributesResume` (if I'm right), why not getting this value from the BO?
Same for line 39, I think it can have the same problem :p

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js]: I improved.

**Review by PierreRambaud — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js [hunk 2]
```diff
@@ -36,11 +36,13 @@ export default {
       return null;
     },
     combinationName() {
-      const arr = this.product.combination_name.split(',');
+      const combinations = this.product.combination_name.split(',');
+      const attributes = this.product.attribute_name.split(',');
```
Comment (sowbiba) [inline admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js:40]: the attributes are in the format `toto, tata, titi`
So if you split by ",", the white space remains, right ?

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js:40]: Fixed ;)

File: admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js [hunk 3]
```diff
@@ -36,11 +36,13 @@ export default {
       return null;
     },
     combinationName() {
-      const arr = this.product.combination_name.split(',');
+      const combinations = this.product.combination_name.split(', ');
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js]: why not split and trim? :thinking:

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js]: Fixed

File: admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js [hunk 4]
```diff
@@ -36,11 +36,13 @@ export default {
...
+      const combinations = this.product.combination_name.split(',');
+      const attributes = this.product.attribute_name.split(',');
+      const separator = ' - ';
       let attr = '';
-      arr.forEach((attribute) => {
-        const value = attribute.split('-');
-        attr += attr.length ? ` - ${value[1]}` : value[1];
+      combinations.forEach((attribute, index) => {
+        const value = attribute.trim().slice(attributes[index].trim().length + separator.length);
+        attr += attr.length ? ` - ${value}` : value;
```
Comment (sowbiba) [inline admin-dev/themes/new-theme/js/app/pages/stock/mixins/product-desc.js:45]:
```suggestion
      combinations.forEach((combination, index) => {
        const value = combination.trim().slice(attributes[index].trim().length + separator.length);
        attr += attr.length ? ` - ${value}` : value;
```

**Review by atomiix — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

Now it's OK with hyphen with or without space, BUT in the Stocks > Movement page, the product with combination are no longer displayed : 
In this screenshot, I added +5 quantity on several products, some with combination, some "standard". In movement page : Only the standard product are displayed, the combination ones are not displayed (funny thing : The pagination is however OK)

pr20330 movement page

See screenrecord here : 
https://drive.google.com/file/d/1Piw9R0bTL1Y_PdybM6TdCS26oX9X9C7U/view?usp=sharing

**Review by sowbiba — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
This is good to me However it is related to a discussion we had recently with @MatShir about using the configurable separator in the BO as well
So either we manage this configurable separator in a different PR (but we must not forget it) or we can include it right now to be sure it's not forgotten

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

Tested How to test : OK
Tested with space and separator : OK
Tested with other separator than "-" : OK
Tested display on FO (on product page, order confirmation) : OK
Tested display on BO : In details orders, order preview, create order, invoice : OK
Tested display on BO > Stocks > Movements : All products are displayed : OK

Display on Stock page : 

pr 20330 Stocks OK

So it's QA :heavy_check_mark: , thanks :)

**Comment by Progi1984** [comment]
Thanks @Robin-Fischer-PS
