### PR TITLE
Make sure `checkSelectPrivilege` check privileges for both InnoDB and MyISAM

### LINKED ISSUE #12675: MyISAM is still default engine for DB connection test --> Azure MySQL connection fails
**Describe the bug**
When deploying Prestashop 1.7.5.1 (docker image) as a Web App in Microsoft Azure and using Azure Database for MySQL, the connection test at the installation setup will fail, because MyISAM is still used and not supported by Azure MySQL (or Google Cloud SQL).

"Got error 1 from storage engine" is returned as an error, which usually means, that MyISAM is used instead of InnoDB.

1. Deploy Prestashop as a container using the latest docker image from image hub
2. Use Azure Database for MySQL and try to connect at step 5 of the setup

**Additionnal information**
https://github.com/PrestaShop/PrestaShop/blob/master/classes/db/DbPDO.php Line 317
The engine should be InnoDB

### PR DESCRIPTION
**Pull request by onlime**
This PR completes #14402 (reported in #12675 and #20676) for `checkSelectPrivilege()`.

The previous implementation only checks MyISAM when no engine was specified.
The new implementation checks InnoDB and MyISAM if no engine is specified.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | During the database check the installation process tries to run a `SELECT` statement on a test table under the specified database. The engine fallbacks to default one which in this case was MyISAM which on some hosting environments is not supported. This PR enables check also for InnoDB engine.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #12675
| How to test?      | To test it easily you can try to install PrestaShop using MySQL engine with disabled MyISAM support.

NOTE: As a quickfix, if you need to get the installer runing on InnoDB, you could also just replace the following:

```diff
--- classes/db/DbPDO.ORIG.php	2021-10-04 18:11:53.000000000 +0200
+++ classes/db/DbPDO.php	2021-11-12 12:35:11.840528301 +0100
@@ -411,7 +411,7 @@
        }

        if ($engine === null) {
-            $engine = 'MyISAM';
+            $engine = 'InnoDB';
        }

        // Create a table

--- classes/db/DbMySQLi.ORIG.php	2021-10-04 18:11:53.000000000 +0200
+++ classes/db/DbMySQLi.php	2021-11-12 12:34:54.823606056 +0100
@@ -449,7 +449,7 @@
        }

        if ($engine === null) {
-            $engine = 'MyISAM';
+            $engine = 'InnoDB';
        }

        // Create a table
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26588)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Hello @onlime . Please tell me if I understand correctly the issue:

Say we are on a hosted env using InnoDB, MyISAM is not available. PrestaShop install process starts. PS install attempts to run function `checkSelectPrivilege` with empty `$engine` and consequently returns an issue - because MyISAM is not available and the code does not check for InnoDB in this usecase.

Is this correct?

**Comment by onlime** [comment]
> Hello @onlime . Please tell me if I understand correctly the issue:
> 
> Say we are on a hosted env using InnoDB, MyISAM is not available. PrestaShop install process starts. PS install attempts to run function `checkSelectPrivilege` with empty `$engine` and consequently returns an issue - because MyISAM is not available and the code does not check for InnoDB in this usecase.
> 
> Is this correct?

Exactly! There is no way to complete the install wizard, neither DB connection test works nor clicking on the "next" button. And the user would have no clue what's going on as the error message is misleading:

PrestaShop-install-db

This happens on a decent hosting provider that has disabled `MyISAM` for good, e.g. my [own company](https://www.onlime.ch) that uses the following configuration on all Percona/MySQL 8.0 based webservers:

```ini
disabled_storage_engines = "MyISAM,MERGE"
```

The whole thing was supposed to be fixed already in #14402, but just partially. So I used the same implementation as in that PR, for consistency.

**Review by tegbessou — DISMISSED** [review]
Thank you for your PR!!

**Review by Progi1984 — DISMISSED** [review]

File: classes/db/DbPDO.php [hunk 1]
```diff
@@ -392,29 +392,29 @@ public static function checkSelectPrivilege($server, $user, $pwd, $db, $prefix,
...
+            ) ENGINE=' . $engineToTest);
 
-        // Drop the table
-        $link->query('DROP TABLE `' . $prefix . 'test`');
+            $result = $link->query('SELECT * FROM `' . $prefix . 'test`');
 
-        if (!$result) {
-            $error = $link->errorInfo();
+            if ($result) {
+                $link->query('DROP TABLE `' . $prefix . 'test`');
```
Comment (PierreRambaud) [inline classes/db/DbPDO.php]: It should be dropped even if the `$result` failed.
What if you have the right to create but not to select.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
One comment about the deletion of the test table.
Regarding MySQL permissions, you can create and be enable to select or drop, so the drop need to be tested too, and only when it success

File: classes/db/DbPDO.php (hunk 1 above)
Comment (matks) [reply classes/db/DbPDO.php]: Nice catch 👍

Comment (onlime) [reply classes/db/DbPDO.php]: right, fixed in 676b9d3

File: classes/db/DbMySQLi.php [hunk 2]
```diff
@@ -448,27 +448,27 @@ public static function checkSelectPrivilege($server, $user, $pwd, $db, $prefix,
...
+            $enginesToTest = [$engine];
         }
 
-        // Create a table
-        $link->query('
-		CREATE TABLE `' . $prefix . 'test` (
-			`test` tinyint(1) unsigned NOT NULL
-		) ENGINE=' . $engine);
+        foreach ($enginesToTest as $engineToTest) {
+            $link->query('
```
Comment (PierreRambaud) [inline classes/db/DbMySQLi.php]: I'm sorry I wasn't very clear, you should test all result when using $link->query, not only the select request.

Comment (onlime) [reply classes/db/DbMySQLi.php]: ok, but it makes me think if we really should waste any more time on this. That is quite ugly low level code and I don't get it why in 2021 any kind of MySQL based application should still support MyISAM. We're talking about the installer here, and you guys could easily remove MyISAM support for the installer, without breaking any existing installations that are still stuck on MyISAM tables.
Are you aware how bad MyISAM performs in MySQL 8.0?

Comment (onlime) [reply classes/db/DbMySQLi.php]: I would leave it as is, because the method is called `checkSelectPrivilege()`, only checking `SELECT` priv. If `CREATE` fails, the `SELECT` would also fail, and if `CREATE` and `SELECT` works, but `DROP` fails, the user is left with a `test` table lying around which will not do any harm.
You really should try to support any kind of crippled permission setups, but rather clearly document how to set up a MySQL user for PrestaShop. Usually installers don't test every single permission and this should be the user's responsibility to set it up correctly.

Comment (PierreRambaud) [reply classes/db/DbMySQLi.php]: > Are you aware how bad MyISAM performs in MySQL 8.0?

Yes, but not everyone is running it on MySQL.
And not everyone has a new server for all instances. Unfortunately, MyISAM is still supported :( 

> I would leave it as is, because the method is called checkSelectPrivilege(), only checking SELECT priv

You're completely right :p

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

File: classes/db/DbPDO.php [hunk 3]
```diff
@@ -392,29 +392,29 @@ public static function checkSelectPrivilege($server, $user, $pwd, $db, $prefix,
...
         }
 
-        // Create a table
-        $link->query('
-		CREATE TABLE `' . $prefix . 'test` (
-			`test` tinyint(1) unsigned NOT NULL
-		) ENGINE=' . $engine);
+        foreach ($enginesToTest as $engineToTest) {
+            $link->query('
+            CREATE TABLE `' . $prefix . 'test` (
```
Comment (Progi1984) [inline classes/db/DbPDO.php]:
```suggestion
            $link->query('CREATE TABLE `' . $prefix . 'test` (
```

File: classes/db/DbMySQLi.php [hunk 4]
```diff
@@ -448,27 +448,27 @@ public static function checkSelectPrivilege($server, $user, $pwd, $db, $prefix,
...
+            CREATE TABLE `' . $prefix . 'test` (
```
Comment (Progi1984) [inline classes/db/DbMySQLi.php]:
```suggestion
            $link->query('CREATE TABLE `' . $prefix . 'test` (
```

**Review by Progi1984 — COMMENTED** [review]
@onlime  A small style fix and it's ok for me.

**Review by matks — APPROVED** [review]
Approved. I agree with this solution, as you discussed with @PierreRambaud it's a good compromise between the scope of this function and how interesting it is... in 2021.

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi,

I tried to configure my environment in docker(mysql 5.7) & Local (mysql8.0) but I have a problem when adding this line  `disabled_storage_engines="MyISAM,BLACKHOLE,FEDERATED,ARCHIVE" ` or this line `disabled_storage_engines = "MyISAM"` to `my file /etc/mysql/my.cnf`
I checked with @PierreRambaud, this PR could be tested by a dev.

Thank you!

**Comment by saulaski** [comment]
Hello, I take in charge the testing.

**Comment by saulaski** [comment]
@khouloudbelguith Issue reproduced with MyISAM engine disabled in both MySQL versions 5.7 and 8.0.
PR fixed the issue.

**Comment by matks** [comment]
@saulaski Can we trust Douglas Powers?

**Comment by matks** [comment]
Thank you @onlime and @saulaski
