### PR TITLE
Order Page: Fix private note that cannot be emptied

### LINKED ISSUE #17726: Private note in order page migrated cannot be emptied
**Describe the bug**
In migrated order view page, the private note of a customer cannot be emptied, since the "Save" button is deactivated when the field is empty.

**To Reproduce**
1. Go to order view page (migrated)
2. Click on "Private note". If the private note is empty, write something in it, save, and refresh
3. Empty the "private note" field
4. The "Save" button becomes grey, and cannot be clicked, it is not possible to empty the field.

**Screenshots**
https://drive.google.com/file/d/1a6Af_Ra9RTgeZeJG6YgvdKiMABTaGkXy/view?usp=sharing

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | the private note of a customer cannot be emptied, since the "Save" button is deactivated when the field is empty.
| Type?         | bug fix
| Category?     | BO 
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | Fixes #17726
| How to test?  | - Go on a migrated order page<br>-  Write something in the private note field and save<br>- Empty the private field, then you should be able to click on save

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17799)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

File: admin-dev/themes/new-theme/js/pages/order/view.js [hunk 1]
```diff
@@ -112,9 +112,8 @@ $(() => {
   function handlePrivateNoteChange() {
     const $submitBtn = $(OrderViewPageMap.privateNoteSubmitBtn);
 
-    $(OrderViewPageMap.privateNoteInput).on('input', (event) => {
-      const note = $(event.currentTarget).val();
-      $submitBtn.prop('disabled', !note);
+    $(OrderViewPageMap.privateNoteInput).on('input', () => {
+      $submitBtn.prop('disabled', false);
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/order/view.js:116]: So, if you remove the text and CTRL - Z you'r able to save it again ? Is that behavior wanted? We could add the content to a data-attr and compare the content on input but it's maybe too overkill, I don't know !

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland
