### PR TITLE
Use index for connections.date_add

### LINKED ISSUE #31727: Incorrect condition disallows use of index `date_add` on table `ps_connections`
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The display of the Carts page in the BO takes a lot of time (often it delays after the timeout of 300 s). The query used is 

```
SELECT a.`id_cart`, a.`date_add` AS `date_add` , CONCAT(LEFT(c.`firstname`, 1), '. ', c.`lastname`) `customer`, a.id_cart total, ca.name carrier, o.id_order, IF ( IFNULL(o.id_order, 'Non commandé') = 'Non commandé', IF(TIME_TO_SEC(TIMEDIFF('2023-03-03 09:08:00', a.`date_add`)) > 86400, 'Panier abandonné', 'Non commandé'), o.id_order ) AS status, IF(o.id_order, 1, 0) badge_success, IF(o.id_order, 0, 1) badge_danger, IF(co.id_guest, 1, 0) id_guest, shop.name as shop_name 
FROM `ps_cart` a 
LEFT JOIN ps_customer c ON (c.id_customer = a.id_customer) 
LEFT JOIN ps_currency cu ON (cu.id_currency = a.id_currency) 
LEFT JOIN ps_carrier ca ON (ca.id_carrier = a.id_carrier) 
LEFT JOIN ps_orders o ON (o.id_cart = a.id_cart) 
LEFT JOIN ( SELECT DISTINCT `id_guest` FROM `ps_connections` 
WHERE TIME_TO_SEC(TIMEDIFF('2023-03-03 09:08:00', `date_add`)) < 1800 ) AS co ON co.`id_guest` = a.`id_guest` 
LEFT JOIN `ps_shop` shop ON a.`id_shop` = shop.`id_shop` 
WHERE 1 AND a.id_shop IN (20) ORDER BY a.id_cart DESC LIMIT 0, 50;
```
Notice the inner select `SELECT DISTINCT id_guest FROM ps_connections WHERE TIME_TO_SEC(TIMEDIFF('2023-03-03 09:08:00', date_add)) < 1800`. The table ps_connections does have an index on the field `date_add`, but with this condition it cannot be used. In fact the calculation must be executed for each of the lines in ps_connections (these can be tens or hundreds of thousnad).

### Expected behavior

The condition in the query should be turned around in a way that the calculation is only done once. For instance: 
```
`date_add` > date_add(now(), interval -30 minute))
```
That way the index `date_add` on the table `ps_connections` can be used and the query time drops into fractions of a second.

### Steps to reproduce

1. In the BO, navigate to `Orders - Carts`
2. Notice that the page takes a long time to load.

Note: my `ps_connections` table has 2M+ rows

### PrestaShop version(s) where the bug happened

8.0.1 and develop

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes an inefficient query. Use index instead of full table scan, 1 math operation per query instead of 1 per row.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Displaying the list of Carts in the BO still works the same, but MUCH faster (0.5s instead of minutes)
| Fixed ticket?     | Fixes #31727
| Related PRs       | None
| Sponsor company   | Société Biblique de Genève

### CODE REVIEW

File: controllers/admin/AdminCartsController.php [hunk 1]
```diff
@@ -67,8 +67,7 @@ public function __construct()
 		LEFT JOIN (
             SELECT DISTINCT `id_guest`
             FROM `' . _DB_PREFIX_ . 'connections`
-            WHERE
-                TIME_TO_SEC(TIMEDIFF(\'' . pSQL(date('Y-m-d H:i:00', time())) . '\', `date_add`)) < 1800
```
Comment (lmeyer1) [inline controllers/admin/AdminCartsController.php:71]: Is there a reason, why we are using `pSQL(date('Y-m-d H:i:00', time()))` here instead of `now()` ? 
I would have simplified further to `WHERE `date_add` > date_add(now() , interval -30 minute)`

Comment (matthieu-rolland) [reply controllers/admin/AdminCartsController.php:71]: hello @lmeyer1 , here is the reason, usage of `now()` should be avoided:

https://github.com/PrestaShop/PrestaShop/issues/30828

Comment (Hlavtox) [reply controllers/admin/AdminCartsController.php:71]: @matthieu-rolland That issue is closed and NOW works absolutely correctly :D (I think)

Comment (matthieu-rolland) [reply controllers/admin/AdminCartsController.php:71]: nobody said that now doesn't work, but it uses the mysql timezone which in some cases can be different from the timezone of the shop (I know that some people in the prestashop company were confronted with this issue and were able to fix it by not using `NOW()`)

Comment (lmeyer1) [reply controllers/admin/AdminCartsController.php:71]: @matthieu-rolland Thanks. I didn't use `now()`, so everything is OK.

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
The related issue still has the `TBR` label.

Can a dev check the issue and share the steps to reproduce the issue in order for QA to test it ?
Or maybe it can be tested by a dev.

@PrestaShop/prestashop-core-developers what do you think ?

**Comment by Hlavtox** [comment]
@florine2623 Do the QA please and don't question it, it's a performance improvement

**Comment by HanaRebaiQA** [comment]
Hello everyone,

This PR should be tested by a dev since the issue is too technical!

Thanks @florine2623 for your ping
@PrestaShop/prestashop-core-developers We are still waiting for your feedback 

Thanks!

**Comment by Hlavtox** [comment]
@HanaRebaiQA So it's not enough when I tell you? What prestashop company developers have extra, some extra permissions?

You can see how to test it if you read the PR description, `How to test` section - `Displaying the list of Carts in the BO still works the same, but MUCH faster (0.5s instead of minutes)`

**Comment by FabienPapet** [comment]
@PrestaShop/qa-team You can test that the page is displayed the same way with and without the modification, as mentioned in the description. Automation tests and 🟢 CI is ok for the technical part, as it is only a performance improvement.

Nothing to test by dev IMO.

**Review by florine2623 — APPROVED** [review]
Hello @lmeyer1 ,

Thanks for the PR !

Tested the Displaying the list of Carts in the BO it still works the same.

Tested with multiples cart more or less filled with products.

It is QA ✅ 
Thanks!

**Comment by 0x346e3730** [comment]
Thank you for your contribution @lmeyer1

**Comment by tonyyb** [comment]
Please can you apply this hotfix patch on 8.1 and 8.2 branches  ? @0x346e3730 @kpodemski  

This is an huge problem for website with a lot of connexions : AdminCartsController take a lot of time for render. 

**Server with standard timeout configurations (max_execution_time for example) are totally impacted.**

**Comment by kpodemski** [comment]
@tonyyb feel free to backport this pull request to `8.2.x` branch, if you do that, I'll make sure we merge it 😎
