### PR TITLE
Make customization image downloadable in BO order page

### LINKED ISSUE #19974: [1.7.7] Image customization cannot be zoomed or viewed from order admin
#### Steps to Reproduce

1. Add a customization field to product, file type, optional.
2. Go to FO, customize the product by uploading an image. Add it to cart. Order it.
3. Go to BO > Orders > Your order
4. Attached image to product cannot be zoomed, does not link anywhere. 

#### How we can solve this
1. Add `private $link;` and `$this->link= _THEME_PROD_PIC_DIR_ . $this->value;`
to `/src/Core/Domain/Order/QueryResult/OrderProductCustomizationForViewing.php`

2. Change `{{ customization.name }}` to `<a href="{{ customization.link }}" target="_blank">{{ customization.name }}</a>` in `/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product.html.twig` or open it in a modal.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | This PR makes customization images downloadable in BO order page, this feature was missing in the migrated order page.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19974
| How to test?  | 1- Add an image customization field to a product, in BO<br> 2- In FO, upload an image on this product and complete the order<br> 3- In BO, go to the order you just made and click on the customization image, it should download the image in full size.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20039)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 1]
```diff
@@ -1460,6 +1464,40 @@ public function configureProductPaginationAction(Request $request): JsonResponse
...
+     *
+     * @param int $type
+     * @param string $name
+     * @param string $value
+     *
+     * @return BinaryFileResponse
+     */
+    public function displayCustomizationImageAction(int $type, string $name, string $value)
+    {
+        $uploadDir = $this->get('prestashop.adapter.legacy.context')->getUploadDirectory();
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:1480]: I'm not sure how to deal with exceptions in this action, since it's a download feature (there's no place to display any error message)

**Comment by matthieu-rolland** [comment]
@PrestaShop/prestashop-product-team Hello, I made the customization image downloadable, like it was in the legacy order page, but I could also just display it in another tab instead..  Do you guys have a preference ?

**Comment by MatShir** [comment]
IMO, the user will proceed with the image on another software, so I don't see why he needs to see it on another tab.
@Hlavtox wdyt  ?

**Comment by Hlavtox** [comment]
@MatShir @matthieu-rolland Well, depends.
- If you make it downloadable, you upset people who just want to view it.
- If you make it just open in target="blank", you upset people who want to download it. 

:D :D

**Comment by MatShir** [comment]
Let's go for the download-only them! @matthieu-rolland

File: src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml [hunk 2]
```diff
@@ -340,3 +340,16 @@ admin_orders_configure_product_pagination:
...
+  methods: [GET]
+  defaults:
+    _controller: PrestaShopBundle:Admin/Sell/Order/Order:displayCustomizationImage
+    _legacy_controller: AdminOrders
+  requirements:
+    type: \d+
+    name: \w+
+    value: \w+
+  options:
+    expose: true
```
Comment (Progi1984) [inline src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml]: Why do `expose` it ? It won't be used in JS.

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Resources/config/routing/admin/sell/orders/orders.yml]: you're right ! fixed

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 3]
```diff
@@ -1460,6 +1464,40 @@ public function configureProductPaginationAction(Request $request): JsonResponse
...
+        $file = $uploadDir . $customizationForViewing->getValue();
+        $mimeTypeGuesser = new FileinfoMimeTypeGuesser();
+
+        $response = new BinaryFileResponse($file);
+
+        if ($mimeTypeGuesser->isSupported()) {
+            $response->headers->set('Content-Type', $mimeTypeGuesser->guess($file));
+        } else {
+            $response->headers->set('Content-Type', 'image/jpeg');
+        }
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
        $response->headers->set(
            'Content-Type', 
            $mimeTypeGuesser->isSupported() ? $mimeTypeGuesser->guess($file) : 'image/jpeg'
        );
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 4]
```diff
@@ -1460,6 +1464,40 @@ public function configureProductPaginationAction(Request $request): JsonResponse
...
+     * @param string $name
+     * @param string $value
+     *
+     * @return BinaryFileResponse
+     */
+    public function displayCustomizationImageAction(int $type, string $name, string $value)
+    {
+        $uploadDir = $this->get('prestashop.adapter.legacy.context')->getUploadDirectory();
+        $customizationForViewing = new OrderProductCustomizationForViewing($type, $name, $value);
+        $file = $uploadDir . $customizationForViewing->getValue();
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Make sure the file exists and is in the scope of the `$uploadDir`?

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 5]
```diff
@@ -1460,6 +1465,56 @@ public function configureProductPaginationAction(Request $request): JsonResponse
...
+                'Content-Type',
+                $mimeTypeGuesser->isSupported() ? $mimeTypeGuesser->guess($file) : 'image/jpeg'
+            );
+
+            $response->setContentDisposition(
+                ResponseHeaderBag::DISPOSITION_ATTACHMENT,
+                $customizationForViewing->getValue()
+            );
+
+            return $response;
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Why not using `$this->file` instead? https://symfony.com/blog/new-in-symfony-3-2-file-controller-helper
Let Symfony do the job :wink:

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 6]
```diff
@@ -1460,6 +1465,56 @@ public function configureProductPaginationAction(Request $request): JsonResponse
...
+    {
+        $uploadDir = $this->get('prestashop.adapter.legacy.context')->getUploadDirectory();
+        $customizationForViewing = new OrderProductCustomizationForViewing($type, $name, $value);
+        $file = $uploadDir . $customizationForViewing->getValue();
+        $mimeTypeGuesser = new FileinfoMimeTypeGuesser();
+        $filesystem = new Filesystem();
+
+        try {
+            if (!$filesystem->exists($file)) {
+                $this->addFlash('error', $this->trans('The product customization image file was not found.', 'Admin.Notifications.Error'));
```
Comment (Junebyun) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
                $this->addFlash('error', $this->trans('The product customization picture could not be found.', 'Admin.Notifications.Error'));
```

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: @Junebyun thanx !

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 5 above)
Comment (matthieu-rolland) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Didn't know about this, it's much cleaner indeed 👍

**Comment by matthieu-rolland** [comment]
> Wouldn't it be good to add download attribute to the link? Otherwise it will open the jpg in the browser, in the same window.

Actually it does download the file, even without the download HTML attribute, because the correct response headers are set server side after you click on the link. But still, thank you for the tip 👍 , I added it for html5 semantic purpose.

**Comment by Hlavtox** [comment]
@matthieu-rolland Didn't know it can be also set by a header. Always learning. 🍺 🙂

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

The file now is downloadable.
But the name of the downloaded file is not correct comparing 176.
**PS176**
The file's name is `ID_order-file.jpg`

**PS177 with this PR**
The file's name is random for example: `d2fecafe3c5c0f6bb9e111a16c4bf339`

Thanks!

**Comment by matthieu-rolland** [comment]
> Hi @matthieu-rolland,
> 
> The file now is downloadable.
> But the name of the downloaded file is not correct comparing 176.
> **PS176**
> The file's name is `ID_order-file.jpg`
> 
> **PS177 with this PR**
> The file's name is random for example: `d2fecafe3c5c0f6bb9e111a16c4bf339`
> 
> Thanks!

thank you for your feedback @khouloudbelguith !

I fixed this, I slightly changed the name, before it was `ID_order-file*number*.jpg` (for example: `6-file1.jpg`), the number was not really relevant, depending on the number of customization images. 

Now it's *`ID_order*-customization-*customization-name*`, for example, let's say the order ID is 6, and the customization name is "product-logo", then the name will be: `6-customization-product-logo.jpg`.

This modification is still to be reviewed.

**Comment by Hlavtox** [comment]
@matthieu-rolland @khouloudbelguith I think it does not matter much guys. If you want the name to be unique, it must be the random string the image is saved as OR you must put id of customization to the file name. Because you can customize the same product multiple times in the same order.

**Review by Progi1984 — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland @khouloudbelguith I think it does not matter much guys. If you want the name to be unique, it must be the random string the image is saved as OR you must put id of customization to the file name. Because you can customize the same product multiple times in the same order.

I agree, it's not so much about uniqueness (your browser will add numbers in the file's name if there are duplicates anyway), it's more about giving the file a proper name, with meaning.

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matthieu-rolland,

It is ok :heavy_check_mark: 

Thanks!
