### PR TITLE
Fix multiple bugs in order view page

### LINKED ISSUE #17089: Migration - Product block on order page bugs
**Describe the bug**
 Following the merge of https://github.com/PrestaShop/PrestaShop/pull/16150, here is the list of the remaining bugs on this page :

Adding several "small" discount with a total greater than the order total will raise another Symfony Exception, with a small difference : The last discount will still be added even if it raise an exception, but it will raise another exception when trying to delete it
* **Bug** :negative_squared_cross_mark: : I still have the exception when adding free shipping discount (it's now OK when adding only "amount" discounts) => This bug also exist in Legacy

* **New bug** :negative_squared_cross_mark: When there is a product which is out of stock, it is impossible to delete it from the order (this also happens in Legacy)
* **New bug** :negative_squared_cross_mark: When editing a product, if the quantity is set higher than available quantity, the field "available" should becomes red. Can you confirm @TristanLDD ? 
* **New bug** :negative_squared_cross_mark: It is not possible to edit a virtual product : https://drive.google.com/file/d/1QtMeLer98qEFD5jXEEO0kBUHswnr4Wcn/view?usp=sharing (this also happens in Legacy)
 * When adding a discount on an order on which at least one invoice has already been created, the user can choose the invoice on which the discount must apply. In the dropdown, in Legacy, each line is "[Invoice Number] - [Invoice Amount]. In migrated page, Invoice Amount is missing.
* A typo (in Legacy and migrated page) bug, on adding a discount popin, under "Apply to all invoices", in the help text :
"If you chooses to create this discount for all invoices, only one discount will be created per order invoice." should be "If you choose to create this discount for all invoices, only one discount will be created per order invoice." => This bug also exist in Legacy,.
* New bug : On pagination, when I have 8 product, if I add a 9th product, it will be added on the bottom of page 1, AND on page 2 (the sum below the product block is still OK). See screenshots : 
pr16150 pagination 9e element
pr16150 pagination 9e element 2
* When adding a product, if a new invoice is created, the "shipping block" displayed is not deleted after creating the invoice

Please note that there might still be some bugs out there...

**Additional information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | last product of pagination were shown on both pages. Fixed
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes all bugs of #17089
| How to test?  | https://github.com/PrestaShop/PrestaShop/issues/17089

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17220)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
All bugs fixed in https://github.com/PrestaShop/PrestaShop/pull/17206

**Review by atomiix — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @zuk3975 ! Could you fix the conflict on the "UpdateProductInOrderHandler.php" file ? Thanks !

**Comment by matks** [comment]
Needs rebase

**Comment by zuk3975** [comment]
@Robin-Fischer-PS rebased.
Conflicts were related to this pr https://github.com/PrestaShop/PrestaShop/pull/16722 so it would be nice to check if I didn't break anything. (I've checked standard case, seems to be ok)

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js [hunk 1]
```diff
@@ -127,7 +134,6 @@ export default class OrderProductEdit {
 
     // Init editor data
     this.taxRate = product.tax_rate;
-    this.totalQuantity = product.availableQuantity + product.quantity;
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js:130]: @zuk3975 Expected ? No rebase mistake ?

**Review by matks — APPROVED** [review]

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 2]
```diff
@@ -240,5 +246,14 @@ private function assertProductCanBeUpdated(
 //                }
 //            }
 //        }
+
+        //check if product is available in stock
+        if (!\Product::isAvailableWhenOutOfStock(StockAvailable::outOfStock($orderDetail->product_id))) {
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php:251]:
```suggestion
        if (!Product::isAvailableWhenOutOfStock(StockAvailable::outOfStock($orderDetail->product_id))) {
```

**Review by Progi1984 — COMMENTED** [review]
A feedback and the same question as @matks

**Review by NeOMakinG — DISMISSED** [review]
Except the @matks question, front-end part LGTM

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js (hunk 1 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js:130]: It was intentional. Check lines (-47) and 49. As I remember it had something to do with dynamic stock value checking instead of product.availableQuantity (or something like that, i don't remember)

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
Confirmed by @zuk3975 👍

**Comment by Robin-Fischer-PS** [comment]
I tested this PR, no major bug appeared, so once the conflict is solved, merge will be possible : 
Even if we might still have some bugs out there, I will create one issue per bug, in order to have a clearer backlog, and a better view on what's left to do in the version.

Thanks !

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
