### PR TITLE
Fix `dashtrends` module position during install

### LINKED ISSUE #24271: Module `dashtrends` position during install
#### Describe the bug

The `dashtrends` module is displayed last in the home page on the backoffice.

#### Expected behavior

The `dashtrends` module must be displayed first

image

#### Steps to Reproduce

1. Go to Admin dashboard controller
2. See error

**Screenshots**

image

#### Additional information

* PrestaShop version: `>= 1.7.7.x`
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x 
| Description?      | The `dashtrends` module is displayed last in the home page on the backoffice.
| Type?             | improvement 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24271
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/24271
| Possible impacts? | This PR modifies the list of modules being installed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24272)

### CODE REVIEW

File: src/PrestaShopBundle/Install/Install.php [hunk 1]
```diff
@@ -898,9 +898,9 @@ public function getModulesList()
             'blockwishlist',
             'contactform',
             'dashactivity',
+            'dashtrends',
```
Comment (matks) [inline src/PrestaShopBundle/Install/Install.php:901]: Waoh 😮  so this list indirectly controls what modules is hooked first or last, which impacts the display of the BO ?!

**Review by matks — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @PululuK 

It works like a charm! dashtrends are displayed first as before :heavy_check_mark: 

PS: @PrestaShop/product-team IMHO I think we need to improve the metrics block :sweat_smile: (and yes I made a screen record :grin: )
https://drive.google.com/file/d/17q_Q0-TpsEErGPvnM0F8QWbSHiwXu6E8/view

Thanks!

**Comment by Progi1984** [comment]
Thanks @PululuK & @hibatallahAouadni
