### PR TITLE
Fixes Search that would return no result if semicolon is used

### LINKED ISSUE #25394: Search with semicolon gives no result. Search differs from earlier versions of find()(1.7.6.x vs 1.7.7.x)
In Prestashop 1.7.6.X you could search for multiple products based on (e.g.) tags. You could split them with a semicolon.
So if i searched for  testproduct1; testproduct5; testproduct8 it would find all 3 products.

Now, we've found out on Prestashop 1.7.7.5 ( this is the version where we noticed the problems so it could be earlier , we upgraded from 1.7.6.8 to 1.7.7.5 ). 
If we search for testproduct1 we get 1 result as expected. 
If we search for testproduct1; testproduct2 the result is 'NO PRODUCTS FOUND'  but it SHOULD  give us the 2 products
If we search for testproduct1; testproduct2; testproduct3 the result is 'NO PRODUCTS FOUND'  but it SHOULD  give us the 3 products

If i replace the find() function on Prestashop 1.7.7.5 with the one from 1.7.6.8 it all works as expected and fine

* PrestaShop version: 1.7.7.5 
* PHP version: PHP 7.3

NOTE : we also found a shop with 1.7.7.2 . Same problem

### PR DESCRIPTION
**Pull request by venditdevs**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Fixes searching multiple products seperated by semicolon. Also changed default of $eligibleProducts2 to array so an unnecessary if/else could be removed.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25394.
| How to test?      | Try to search multiple products separated by a semicolon based on tags. Example of searchs<br/>- "red shirt"<br/>- "red"<br/>- "red shirt ; blue shirt"<br/>- "red ; blue"<br/>The Search system will return the results for "red" and for "blue" rather than trying to find results that match simultaneously "red" and "blue".
| Possible impacts? | Search engine, more information in the issue #25394

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25396)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@venditdevs Hi Could you fix PHPCSFixer Check ?

File: classes/Search.php [hunk 1]
```diff
@@ -319,21 +319,18 @@ public static function find(
...
             }
 
             $productIds = array_column($result, 'id_product');
-            if ($eligibleProducts2 === null) {
-                $eligibleProducts2 = $productIds;
-            } else {
-                $eligibleProducts2 = array_intersect($eligibleProducts2, $productIds);
-            }
-
+            $eligibleProducts2 = array_merge($eligibleProducts2, $productIds);
```
Comment (matks) [inline classes/Search.php]: This is a big change of behavior.
Previously we would look at the intersection of `$eligibleProducts2` and `$productIds` now we merge them. I expect that this will make the search less accurate, it will present way much results than before.

I am not sure this is the right way to fix the issue

> It's this line: $eligibleProducts2 = array_intersect($eligibleProducts2, $productIds);
This will return the differences between the two arrays which is none when you use 2 or more search words and so the result is empty.

Can you tell us
- what is inside `$eligibleProducts2` when a single search word is used
- what is inside `$eligibleProducts2` when two search words are used

I think the root issue might be there.

Comment (venditdevs) [reply classes/Search.php]: @matks : If the two arrays don't match.....the array $eligibleProducts2 is empty. So if word 1 result is (e.g.) id_product 5 and word 2 result is id_product 6. You have NO results because they don't match. That's wrong in every way you look at it.

Data:
testproduct1 = id_product 1
testproduct2 = id_product 2
testproduct3 = id_product 3

What is inside $eligibleProducts2 when a single search word is used:
Example: Search for testproduct1; the contents of $eligibleProducts2 = array([0]=>1)

What is inside $eligibleProducts2 when two search words are used:
Example: Search for testproduct1;testproduct2; the contents of $eligibleProducts2 = array()
Reason: The 2 arrays don't match and so array_intersect returns an empty array. But it really should return array([0]=>1,[1]=>2)

What is inside $eligibleProducts2 when three search words are used:
Example: Search for testproduct1;testproduct2;testproduct3; the contents of $eligibleProducts2 = array()
Reason: The 2 arrays don't match and so array_intersect returns an empty array. But it really should return array([0]=>1,[1]=>2,[2]=>3)

Comment (matks) [reply classes/Search.php]: Aaaah I got it now.

I think that the goal of `$eligibleProducts2 = array_intersect($eligibleProducts2, $productIds);` was to make search more accurate.

Exemple: I search "red shirt".
First loop on "red" will give me 4 red products
Second loop on "shirt" will give me 5 shirt products
Then intersection will give me the red shirt products

If we remove the `array_intersect()` we will get every red product and every shirt product. We don't want that to happen.

But if you search, like you do, the words "shirt ; trousers" you want to find both shirts and trousers
but the above logic will find all products that are shirts AND trousers and this is not possible.

So the main issue is that the current logic attempts to find "products that match all input words" while in your usecase you want "products that match any input word".

So I cannot approve your change. We need to find a way that preserve both behavior, if that's possible.

Comment (venditdevs) [reply classes/Search.php]: Maybe with a strpos check on ; set a flag automatically to search for all words. So if ; is present in $expr search for all words.
Would that be a fast and easy fix?

Comment (matks) [reply classes/Search.php]: > Maybe with a strpos check on ; set a flag automatically to search for all words. So if ; is present in $expr search for all words.

That could work for your usecase, but what about "red shirt ; blue trousers ; black shoes" 😅 

I guess the very best would be
1. When we detect there are terms separated by `;`
2. We select each part separated by `;`
3. For each of these parts, we perform the regular intersect search : that means we look for red shirts, then we look for blue trousers, then we look for black shoes
4. Finally we merge all results together, so we return results that are red shirts OR blue trousers OR black shoes

It's a more complex though. Also such a complex behavior cannot be guessed, we will need
- to test it
- to document it

Comment (matks) [reply classes/Search.php]: At this point it's probably a good idea to ask @PrestaShop/prestashop-core-developers for their opinion

Comment (venditdevs) [reply classes/Search.php]: "That could work for your usecase, but what about "red shirt ; blue trousers ; black shoes""
I think this can be fixed quite easy ..if we do an explode on ';' in $expr build a foreach. 
At the end tie everything together.

This would fix everything imho.

I'm going to test it

Comment (venditdevs) [reply classes/Search.php]: @matks  . I tested it. If we explode the expressions on semicolon. Loop it in a for each it will give the expected result. In all ways

Comment (venditdevs) [reply classes/Search.php]: Tested it with code the find() function of Prestashop 1.7.7.5. However it won't work with the code in 'Develop' branche. It will mess up the result later on in the code. Working on that. The current outcome: $eligibleProducts2Full (new var) has 2 product id's however only 1 product is returned as final result.

Comment (venditdevs) [reply classes/Search.php]: PR updated!

**Comment by venditdevs** [comment]
> @venditdevs Hi Could you fix PHPCSFixer Check ?

I'm sorry. I really have no idea what the problem in PHPCSFixer is and how to fix.

**Comment by matks** [comment]
> > @venditdevs Hi Could you fix PHPCSFixer Check ?
> 
> I'm sorry. I really have no idea what the problem in PHPCSFixer is and how to fix.

You can run it locally
```
php /vendor/bin/php-cs-fixer fix
```

**Comment by venditdevs** [comment]
> > > @venditdevs Hi Could you fix PHPCSFixer Check ?
> > 
> > 
> > I'm sorry. I really have no idea what the problem in PHPCSFixer is and how to fix.
> 
> You can run it locally
> 
> ```
> php /vendor/bin/php-cs-fixer fix
> ```

OK thx! 
Pulled the Git Repo and ran cs-fixer. Edited PR ...checks are all queued...guess we'll have to wait if it's fixed now.

**Comment by venditdevs** [comment]
@matks ...All unit tests are failing on setup :S That's nothing i can fix right?

**Comment by matks** [comment]
> @matks ...All unit tests are failing on setup :S That's nothing i can fix right?

Indeed looks like we have a bigger issue 😆  stand by

**Comment by venditdevs** [comment]
> > @matks ...All unit tests are failing on setup :S That's nothing i can fix right?
> 
> Indeed looks like we have a bigger issue  stand by

Well at least cs-fixer is ok now :)

**Comment by venditdevs** [comment]
@matks . I'm testing further and there is much more broken then we thought in the routine. If you search for this:
testproduct1;testproduct2;test it won't return the first 2 product but the whole search is empty again.

It's really starting to annoy me....

**Comment by matks** [comment]
> @matks . I'm testing further and there is much more broken then we thought in the routine. If you search for this:
> testproduct1;testproduct2;test it won't return the first 2 product but the whole search is empty again.

Search logic has always been a complex topic. This is why there are companies that have search as a core business like Algolia

I don't think we should aim to cover all possible searches in PrestaShop. PrestaShop relies on SQL and SQL is not a good engine for search. If someone really wants nice search results, I think that there are some nice modules (like Algolia, but also others) that will do a lot better than what we can achieve with SQL. Product search is not the main focus on PrestaShop, main focus is to sell. Let's implement something nice, simple, and that covers basic usecase :) that will already be quite good, what do you think?

**Comment by venditdevs** [comment]
> that will already be quite good, what do you think?

@matks Well, the results are better than it used to be, that's for sure;)

I fixed the last problem in the current PR. So everything now works as it used to be in PS 1.6.6.X AND uses the new routine from 1.7.7.X that gives better search results. So: Black shoes;red shirts;green trousers will work now as expected.

**Comment by matks** [comment]
> I fixed the last problem in the current PR. So everything now works as it used to be in PS 1.6.6.X AND uses the new routine from 1.7.7.X that gives better search results. So: Black shoes;red shirts;green trousers will work now as expected.

I think this is a nice improvement 😄  no need to go further.

**Review by matks — APPROVED** [review]
Code looks good to me. I approve the PR.

I add 2 things that could be great, if you are willing to go further:
- document this "loop on the items separated by a semi-colon" behavior in the function PHPDoc, to help future readers to understand what this part of the code does
- write automated tests to validate this behavior

**Comment by Hlavtox** [comment]
@matks @venditdevs Guys, there were big argues about the search. Exactly by this. You searched "red car" and it returned everything red and every car. Completely unusable. 

Now it works, **PLEASE** don't screw it up.

**Comment by matks** [comment]
> @matks @venditdevs Guys, there were big argues about the search. Exactly by this. You searched "red car" and it returned everything red and every car. Completely unusable.
> 
> Now it works, **PLEASE** don't screw it up.

We can't let https://github.com/PrestaShop/PrestaShop/issues/25394 unsolved. There's even a placeholder to suggest using the semicolon.

If you wan't to be sure these changes are fine, the best is to check them out and verify them 😄

**Comment by matks** [comment]
Just found this 😛  https://github.blog/changelog/2021-08-02-search-issues-by-label-using-logical-or/ : as we can, it's standard to use comma or semicolon and expect a OR search being performed

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @venditdevs,

It is ok :heavy_check_mark: 

**Before** 
image
**After**
image

**With PR**
image
image

>https://github.com/PrestaShop/PrestaShop/pull/25396#issuecomment-889745908

**Without PR**
image

**With PR**
image

Thanks!

**Comment by atomiix** [comment]
Thanks everyone! :)

**Comment by matks** [comment]
> @matks @venditdevs Guys, there were big argues about the search. Exactly by this. You searched "red car" and it returned everything red and every car. Completely unusable.
> 
> Now it works, **PLEASE** don't screw it up.

@Hlavtox the current changes only handle the semicolon separator as a OR

Can you have a look and tell is result looks fine ? 😉  from my opinion it looks good
