### PR TITLE
Fix label_attr check in form_rest macro

### LINKED ISSUE #26786: Error with dynamical form rendering in 1.7.8.1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When i wan't to use a form, where my entity is dynamical from the database, with a form structure like this:
```twig
{{form_start(form)}}
{# form content #}
{{form_end(form)}}
```
I get this error message. 
image

If i use {{form(form)}} it actually works, but thats not good for me, cause i want to customize the template.

### Expected behavior

Expected behavior is to successfully display my form, instead of getting an error message

### Steps to reproduce

I made an example module, which can reproduce this bug.
https://github.com/krekken/formbugreproduce

if you install it on a 1.7.7.8 prestashop it will work, but it won't work if you install it on a 1.7.8.1 container. 

image
the Form Bug Reproduce tab is the one, which contains the bugged form

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.4.25

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Because of a wrong `if` statement in twig, an undefined variable was accessed, leading to an exception. This PR aims to fix it by fixing the `if` statement.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26786
| How to test?      | Please see #26786
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26987)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @atomiix

File: tests/UI/campaigns/sanity/01_installShop/01_installShop.js [hunk 1]
```diff
@@ -167,7 +167,7 @@ describe('Install Prestashop', async () => {
         {
           step: {
             name: 'Install addons modules',
-            timeout: 60000,
+            timeout: 120000,
```
Comment (PierreRambaud) [inline tests/UI/campaigns/sanity/01_installShop/01_installShop.js:170]: It's not needed, the problem from addons is related to back-office timeout ^^

**Comment by matks** [comment]
@atomiix Hi ! I'm sorry but it seems you and @JevgenijVisockij submitted a bugfix almost at the same time... but @JevgenijVisockij was a little earlier (because he has PR ID 26986 and you have PR ID 26987). I think we can close yours as the content is quite similar.

=> duplicate of https://github.com/PrestaShop/PrestaShop/pull/26986

File: tests/UI/campaigns/sanity/01_installShop/01_installShop.js (hunk 1 above)
Comment (atomiix) [reply tests/UI/campaigns/sanity/01_installShop/01_installShop.js:170]: Nope it is not, this fix worked

**Comment by atomiix** [comment]
@matks he must rebase his branch then, it's a regression, it must be fixed on 1.7.8.x, not on develop

**Comment by jolelievre** [comment]
I also saw it but to me, this PR was more urgent as it targets 178x and it includes a fix for the CI

Since @JevgenijVisockij can't reproduce the timeout issue on the develop CI it'd be wiser to merge this one first (which will be merged in develop later) even if indeed Jevgenij's PR was here earlier

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @atomiix

**Review by matks — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,

PR is tested and issue is fixed.
https://watch.screencastify.com/v/SnV9uv6DO0LTBcoCZrU3

Thanks,

**Comment by matks** [comment]
Thank you @atomiix
