### PR TITLE
Deprecate URL generation on category with id 0 and remove preview in category creation

### LINKED ISSUE #25871: BO - Categories page - Invalid category vars - An exception is displayed when Adding a category
#### Describe the bug

If we change the `Route to category` in the BO > Shop Parameters page from `{id}-{rewrite}` to `{id}-{rewrite}-{meta_title}`, we cannot add new category => an exception is displayed

#### Steps to Reproduce

1. Go to BO > Shop Parameters > SEO & URLs page
2. Enable `Friendly URL`
3. Change the `Route to category` from `{id}-{rewrite}` to `{id}-{rewrite}-{meta_title}`
4. Go to BO > Catalog > Categories page
5. Click button 'Add new category'
6. See error 
image

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.7, 1.7.8.x
* PHP version: 7.1, 7.2

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This fixes 25871 by removing url preview while creating a category. 
| Type?             | bug fix 
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | Fixes #25871 
| How to test?      | Explained in #25871

### CODE REVIEW

File: classes/Link.php [hunk 1]
```diff
@@ -428,6 +428,10 @@ public function getCategoryLink(
         $idShop = null,
         $relativeProtocol = false
     ) {
+        if ($category === 0) {
```
Comment (jolelievre) [inline classes/Link.php]:
```suggestion
        if ((int) $category === 0) {
```

Comment (jolelievre) [reply classes/Link.php]: In most of the legacy code the variable are not strictly typed, so there are a lot of changes that you get and ID as string `'0'` so to perform your equality test correctly you'd better cast it before using the strict equality `===` (even though the PHPdoc seems to indicate that a string is never used in legacy code we're never sure of it ^^)

Comment (jolelievre) [reply classes/Link.php]: But you could probably do even better than this, because as you can see a few line below the `$category` can actually be an Object an array or an int

So you probably should add your deprecation notice on L453 by checking the `$params['id']` value as well Same suggestion if you do that, you'd better cast it as an int if you use the strict equality because even in legacy objects the field are not always correctly typed (event the ID)

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig [hunk 2]
```diff
@@ -136,17 +136,20 @@
...
-            <small class="form-text">
-              {{ 'Here is a preview of how your page will appear in search engine results.'|trans({}, 'Admin.Global') }}
-            </small>
+      {# Do not display category preview while creating a category #}
+      {% if categoryUrl is not null %}
+        {% block category_tool_serp %}
+          <div class="form-group row">
+            <label class="form-control-label">{{ 'SEO preview'|trans({}, 'Admin.Global') }}</label>
+            <div class="col-sm">
+              <div id="serp-app" data-category-url="{{ categoryUrl }}"></div>
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig:145]: I don't know if you checked but be careful since you remove the `#serp-app` you may have a JS error, because the Serp component expects this div to be present and I'm not sure if it handles its absence correctly (it should fail silently in this case)

**Review by jolelievre — COMMENTED** [review]
Thanks @FabienPapet 

Nice first PR, welcome to the PrestaCrew 😉

File: classes/Link.php (hunk 1 above)
Comment (matks) [reply classes/Link.php]: Also as discussed live: maybe we can test this behavior.

Unfortunately `classes/Link.php` is a legacy class strongly coupled to multiple other legacy classes so unit tests cannot be done. But we have an integration test with some mocking stuff here https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Classes/LinkTest.php maybe we can expand this Test to be able to test your new case

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig (hunk 2 above)
Comment (FabienPapet) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig:145]: I did not check, but this code inside serp app check if the html node exists before running anything. 

```js
    if ($(selectors.container).length === 0) {
      return;
    }
```

Should I test the existence of the node before calling it or can we rely on it ?

File: classes/Link.php (hunk 1 above)
Comment (FabienPapet) [reply classes/Link.php]: I'm gonna need help to add that test case 😄. I've moved the code

Comment (matks) [reply classes/Link.php]: I checked Link class, there is so much coupling to singletons 😭 let's forget about it

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig (hunk 2 above)
Comment (NeOMakinG) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig:145]: I guess the component does it by itself so it should be enough?

**Review by matks — APPROVED** [review]
Good enough for me 👍

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Categories/Blocks/form.html.twig:145]: No this is enough I just wanted to be sure If no errors pop out in the console it's already a good sign

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

**Review by marwachelly — APPROVED** [review]
Hello @FabienPapet,

PR is tested and issue is well fixed.

https://user-images.githubusercontent.com/89604350/179206409-2e7cd96a-1ca9-4973-9224-35091bae5961.mp4


PR is QA validated.

Thank you,
