### PR TITLE
Fixed Ecotax when editing an Order ((Add/Update)ProductToOrder)

### LINKED ISSUE #22029: BO - Order page - when adding a product which has an ecotax to an old order, the base price is NOK
#### Describe the bug

The ecotax is enabled, In the BO > Orders > old order details page > when we try to add a product which has an ecotax, the base is NOK, so the total is NOK, the invoice is NOK

The Edit of a product with Ecotax is NOK too.

#### Steps to Reproduce

0. Go to BO > International > Taxes > Enable "Use ecotax"
image
1. Create an order from the FO with any product
2. Go to BO > Catalog > Products page > Create a new product
2.1 Tax included = 12€
2.2 Tax rule = 20%
2.3 Ecotax (tax incl.) = 5€ 
image
3. Go to BO > Orders > last order created
4. Add a product
5. Search the last product created
image
6. Click add
7. see the error
image
8. change the status to payment accepted
9. Download invoice
10. see error
image

PS1768 => ok: https://drive.google.com/file/d/12s52BuZBTIUykgD6j4mRTv-5RhD_xtPA/view?usp=sharing
177x => NOK: https://drive.google.com/file/d/1X1F-PonwH9O1CBsm_WfCsUsW8NsXyLux/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

-----
## Expected behavior

As the ecotax is included in the price filled by the merchant, the unit prices should be displayed ecotax included
Specs: https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/ecotax.md
Note: For the ecotax VAT rate, take into account the one defined in International > Taxes

## Technical viewpoint (@jolelievre)

This comment should help you regarding the technical solution that needs to be implemented https://github.com/PrestaShop/PrestaShop/issues/22029#issuecomment-767658294 If you have any question don't hesitate to ask me

## Status

Waiting for https://github.com/PrestaShop/PrestaShop/pull/22228 to be merged

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fixed Ecotax when editing an Order ((Add/Update)ProductToOrder) : The price in OrderDetail includes Ecotax, so we need to exclude in some parts of code when we work on taxes
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22029
| How to test?      | Cf https://github.com/PrestaShop/PrestaShop/issues/22029#issue-747429613
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23492)

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -2211,7 +2214,7 @@ public function newCalculator($products, $cartRules, $id_carrier, $computePrecis
         $priceCalculator = ServiceLocator::get(PriceCalculator::class);
 
         // set cart rows (products)
-        $useEcotax = $this->configuration->get('PS_USE_ECOTAX');
+        $useEcotax = is_null($withEcoTax) ? $this->configuration->get('PS_USE_ECOTAX') : $withEcoTax;
```
Comment (matthieu-rolland) [inline classes/Cart.php]:
```suggestion
        $useEcotax = $withEcoTax ?? $this->configuration->get('PS_USE_ECOTAX');
```

File: classes/Cart.php [hunk 2]
```diff
@@ -871,7 +873,7 @@ public function getProducts($refresh = false, $id_product = false, $id_country =
      *
      * @return mixed
      */
-    protected function applyProductCalculations($row, $shopContext, $productQuantity = null, bool $keepOrderPrices = false)
+    protected function applyProductCalculations($row, $shopContext, $productQuantity = null, bool $keepOrderPrices = false, bool $withEcotax = true)
```
Comment (sowbiba) [inline classes/Cart.php]: missing $withEcotax in phpDoc

File: classes/Cart.php [hunk 3]
```diff
@@ -1120,7 +1122,8 @@ private function getOrderPrices(
         int $productQuantity,
         ?int $addressId,
         Context $shopContext,
-        &$specificPriceOutput
+        &$specificPriceOutput,
+        bool $withEcotax = true
```
Comment (sowbiba) [inline classes/Cart.php]: missing $withEcotax in phpDoc

File: classes/Cart.php [hunk 4]
```diff
@@ -2065,7 +2068,8 @@ public function getOrderTotal(
         $products = null,
         $id_carrier = null,
         $use_cache = false,
-        bool $keepOrderPrices = false
+        bool $keepOrderPrices = false,
+        bool $withEcoTax = null
```
Comment (sowbiba) [inline classes/Cart.php]: missing $withEcotax in phpDoc

**Review by sowbiba — DISMISSED** [review]
Just some suggestions

I had some questions but found the answers myself :D
(like can product->ecotax and orderDetail->ecotax be null ? => it's initialized with 0 in the Model so we can expect that the answer is No)

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please add a better description and how to test part :trollface:

File: classes/order/OrderDetail.php [hunk 5]
```diff
@@ -64,22 +64,22 @@ class OrderDetailCore extends ObjectModel
...
 
     /** @var float */
     public $original_product_price;
 
-    /** @var float */
+    /** @var float Without taxes, includes ecotax */
     public $unit_price_tax_incl;
 
-    /** @var float */
+    /** @var float With VAT, includes ecotax */
```
Comment (PierreRambaud) [inline classes/order/OrderDetail.php]:
```suggestion
    /** @var float With taxes, includes ecotax */
```

Comment (jolelievre) [inline classes/order/OrderDetail.php]:
```suggestion
    /** @var float With taxes, includes ecotax */
```

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 6]
```diff
@@ -34,6 +34,7 @@
 use Order;
 use OrderDetail;
 use OrderInvoice;
+use PrestaShop\Decimal\Number;
```
Comment (PierreRambaud) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]:
```suggestion
use PrestaShop\Decimal\DecimalNumber;
```

Prefer DecimalNumber for PHP8

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 7]
```diff
@@ -39,6 +39,7 @@
 use OrderInvoice;
 use OrderState;
 use PHPUnit\Framework\Assert as Assert;
+use PrestaShop\Decimal\Number;
```
Comment (PierreRambaud) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
use PrestaShop\Decimal\DecimalNumber;
```

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 6 above)
Comment (PierreRambaud) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: How, it's maybe only working on the develop branch :D

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 7 above)
Comment (PierreRambaud) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: How, it's maybe only working on the develop branch :D

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Not handled in 177, the new library is only available in 178

File: classes/Cart.php [hunk 8]
```diff
@@ -1120,7 +1124,8 @@ private function getOrderPrices(
         int $productQuantity,
         ?int $addressId,
         Context $shopContext,
-        &$specificPriceOutput
+        &$specificPriceOutput,
+        bool $withEcotax = true
```
Comment (jolelievre) [inline classes/Cart.php]: I wonder if you need this `$withEcotax` argument here, let me explain why:
- `getOrderPrices` is only called when the cart has an order associated
- so it should only be used in Order handlers when we call `$cart->getProducts`
- in `OrderMountUpdater:updateOrderDetails` you use `$cart->getProducts` but always with ecotax false
- so in the end maybe you can simply call `Product::getPriceFromOrder` with ecotax argument hard coded as `false` all the time?

File: classes/Cart.php [hunk 9]
```diff
@@ -2065,7 +2071,8 @@ public function getOrderTotal(
         $products = null,
         $id_carrier = null,
         $use_cache = false,
-        bool $keepOrderPrices = false
+        bool $keepOrderPrices = false,
+        bool $withEcoTax = null
```
Comment (jolelievre) [inline classes/Cart.php]: For the same reasons as above if ecotax is always false when you get order prices, then maybe you don't need it here either

File: classes/Cart.php (hunk 8 above)
Comment (jolelievre) [reply classes/Cart.php]: This assumption is based on the principle that we never call `$cart->getProducts` with default ecotax true in other handlers so I might be wrong But it's not the case and we can avoid this extra parameter it might be worth trying to hard code it to false here and see if the tests succeed

In which case it implies the parameter can be removed

File: src/Adapter/Order/OrderDetailUpdater.php [hunk 10]
```diff
@@ -80,21 +80,29 @@ public function __construct(
...
      *
      * @throws OrderException
      */
     public function updateOrderDetail(
         OrderDetail $orderDetail,
         Order $order,
         Number $priceTaxExcluded,
-        Number $priceTaxIncluded
+        Number $priceTaxIncluded,
+        Number $ecotax
```
Comment (jolelievre) [inline src/Adapter/Order/OrderDetailUpdater.php]: Can you not retrieve the ecotax from `$orderDetail->ecotax` instead of addin an extra parameter? It should have been filled when the OrderDetail is created, and it would be safer because it saves the ecotax applied at the time of the command

With your current implementation if the ecotax is edited after the Order has been created, and then you edit the Order it will use the new one instead of the one that applied at the moment of the order (and we don't want that, just like the product prices update shouldn't affect the ordered product prices)

File: src/Adapter/Order/OrderDetailUpdater.php [hunk 11]
```diff
@@ -80,21 +80,29 @@ public function __construct(
...
     ): void {
         list($roundType, $computingPrecision, $taxAddress) = $this->prepareOrderContext($order);
 
         try {
+            $priceTaxExcluded = $priceTaxExcluded->minus($ecotax);
```
Comment (jolelievre) [inline src/Adapter/Order/OrderDetailUpdater.php:102]: This is definitely worth some extra comments to explain that (for some very weird reasons) Ecotax is added in both prices in OrderDetail (tax excluded and tax inxluded) although we don't understand why and it seems a very weird behaviour

And while we're talking about this weird behaviour I'd like some feedback about this from @PrestaShop/product-team and some clear specification (wether we keep this behaviour or not) because it makes no sense to me Mayt it's a very old bug that we are just forcibly re developing just to match the legacy behaviour... (this kind of strategy has proven to be wrong in many many cases 😅 )

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 12]
```diff
@@ -183,17 +184,21 @@ public function addProductsToOrderWithNewInvoiceAndTheFollowingDetails(string $o
...
-        }
+        $productCore = new Product((int) $productId);
+        $ecotax = new Number($productCore->ecotax);
+
+        $combinationId = isset($data['combination']) ? $this->getProductCombinationId($product, $data['combination']) : 0;
 
         if (empty($data['price_tax_incl'])) {
-            $taxCalculator = $this->getProductTaxCalculator((int) $orderId, (int) $productId);
-            $data['price_tax_incl'] = !empty($taxCalculator) ? (string) $taxCalculator->addTaxes($data['price']) : $data['price'];
+            $taxCalculator = $this->getProductTaxCalculator((int) $orderId, $productId);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:191]: I'm not sure I understand this.. you perform the same computing as in the handler, basically, so of course it will match And it's a very suspicious computing as I commented earlier 😅

Don't get me wrong I understand why you needed to add this, but it feels so illogical that I feel the need to ask for blocking specifications here.. It feels like we are forcing a square in a circle just to please the legacy behaviour

**Review by jolelievre — DISMISSED** [review]
Some comments for you @Progi1984 about some possible simplifications, although I'm not sure maybe we can handle this without the extra parameter `withEcoTax` (at least in the order products part)

However the reason I "block" the PR is different, it's about getting feedback, a big reflexion and some extra carefully written specifications for this, because the current behaviour seems illogical and it feels like we are forcing new implementation to match legacy buggy one

Most important question: why would OrderDetail::price_tax_excluded include the ecotax? I can understand its present in tax_included but not in the excluded part

When you look at how it works in the Product page form, you have three inputs:
- price_tax_excluded
- price_tax_included
- ecotax (tax included)

And in this page `price_tax_included = (price_tax_excluded * taxRate) + ecotax` This might be a debatable way of handling this but at least there is some kind of logic Which is not reflected at all in the OrderDetails where the unit_price_tax_excluded contains the ecotax (with tax removed)

Oh right because we din't even start talking about the tax rate which can be applied on the ecotax itself 😅  (I'm not sure you noticed this one @Progi1984 )

**Comment by eternoendless** [comment]
ping @Progi1984

File: src/Adapter/Order/OrderDetailUpdater.php (hunk 11 above)
Comment (Progi1984) [reply src/Adapter/Order/OrderDetailUpdater.php:102]: I currently add comments.

For explanation : Prices coming from the backoffice : they are displayed with ecotax so we need to remove ecotax before having precise price

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 12 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:191]: Fixed

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Order/OrderDetailUpdater.php [hunk 13]
```diff
@@ -467,4 +498,18 @@ private function getTaxCalculatorByAddress(Address $address, OrderDetail $orderD
...
+    /**
+     * Get a TaxCalculator adapted for Ecotax
+     *
+     * @param Address $address
+     *
+     * @return TaxCalculator
+     */
+    private function getTaxCalculatorForEcotax(Address $address): TaxCalculator
+    {
+        $tax_manager = TaxManagerFactory::getManager($address, (int) \Configuration::get('PS_ECOTAX_TAX_RULES_GROUP_ID'));
```
Comment (sowbiba) [inline src/Adapter/Order/OrderDetailUpdater.php]: you can import Configuration

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 14]
```diff
@@ -1755,13 +1751,14 @@ public function assertLastErrorIsRefundQuantityTooHigh()
 
     /**
      * @param int $orderId
+     * @param int $productId
      *
      * @return TaxCalculator|null
```
Comment (sowbiba) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: it cant return null. does it ?

Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Right ;)

File: src/Adapter/Order/OrderDetailUpdater.php (hunk 13 above)
Comment (Progi1984) [reply src/Adapter/Order/OrderDetailUpdater.php]: Done

**Review by sowbiba — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found an issue when adding a product with ecotax to an order that has already an invoice.
Steps to reproduce the issue:
1. Go to BO > International > Taxes > Enable "Use ecotax"
2. Create a product without ecotax and Price tax included = 10 Euro (an example)
3. Create order from the FO/BO with the last product created
4. Go to BO > Orders > Order list page > change the status of the last order to "payment accepted"
5. Go to BO > Catalog > Products page > Create a new product
5.1 Tax included = 12€
5.2 Tax rule = 20%
5.3 Ecotax (tax incl.) = 5€ 
image
6. Go to BO > Orders > last order created
7. Add a product
8. Search the last product created & Click Add
9. Click on the Documents Tab
10. See error: the **Amount** is NOK = `€27.00 (€17.00 not paid)`, it should be `€22.00 (€12.00 not paid)` 
image
11. Download the invoice => see error
image

I will complete my test to check if it is ok in other cases.

Thank you!

File: classes/order/OrderDetail.php [hunk 15]
```diff
@@ -64,22 +64,22 @@ class OrderDetailCore extends ObjectModel
...
 
-    /** @var float */
+    /** @var float Without taxes, includes ecotax */
     public $product_price;
 
     /** @var float */
     public $original_product_price;
 
-    /** @var float */
+    /** @var float Without taxes, includes ecotax */
```
Comment (jolelievre) [inline classes/order/OrderDetail.php]: I think the comments are inversed here with/without

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 16]
```diff
@@ -180,22 +180,25 @@ private function updateOrderTotals(Order $order, Cart $cart, int $computingPreci
         $order->total_discounts_tax_excl = (float) abs($cart->getOrderTotal(false, Cart::ONLY_DISCOUNTS, $orderProducts, $carrierId, false, $this->keepOrderPrices));
         $order->total_discounts_tax_incl = (float) abs($cart->getOrderTotal(true, Cart::ONLY_DISCOUNTS, $orderProducts, $carrierId, false, $this->keepOrderPrices));
 
+        // We set $useEcotax to false because
+        //    $cart->getOrderTotal will fetch from order details which have already ecotax in their prices
+        $useEcotax = false;
```
Comment (jolelievre) [inline src/Adapter/Order/OrderAmountUpdater.php]: So it means regardless of `$useEcotax` since it gets the prices from OrderDetail it will always contain the ecotax? What's the point of this variable/parameter then? Wouldn't it work the same way without it?

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 17]
```diff
@@ -262,8 +265,10 @@ private function updateOrderCarrier(Order $order, Cart $cart): void
      */
     private function updateOrderDetails(Order $order, Cart $cart): void
     {
+        // We set $useEcotax to false else $cart->getProducts apply a second time ecotax on price
+        $useEcotax = false;
```
Comment (jolelievre) [inline src/Adapter/Order/OrderAmountUpdater.php]: Ok I understand better with this comment, the only thing bugging me is that this parameter is not correct in its naming, or even behaviour What I mean is if I use `getProducts` with `$useEcotax = false` I would expect to get the prices **without** the eco tax. And that's actually the behaviour this method has when the cart is not assigned to an order right?

So it means it doesn't have the same behaviour when the order exists which seems problematic. So the `$useEcotax` parameter here is not used to "toggle" the ecotax but only used as a workaround to prevent having it twice... Wouldn't it make more sense if when `$useEcotax` is false we would subtract the ecotax from the value returned in OrderDetails?

Comment (jolelievre) [reply src/Adapter/Order/OrderAmountUpdater.php]: So maybe the error is actually in `Product::getPriceFromOrder` Since `original_product_price` seems to already contain the ecotax we need to subtract it here:

https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/classes/Product.php#L3600-L3604

```php
        $ecoTaxValue = $withTaxes ? $orderDetail['ecotax'] * (1 + $orderDetail['ecotax_tax_rate']) : $orderDetail['ecotax'];
        if (!$withEcoTax) {
            $price -= $ecoTaxValue;
        }
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature [hunk 18]
```diff
@@ -0,0 +1,253 @@
+# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags order-ecotax
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature]:
```suggestion
# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags odd-order-ecotax
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature [hunk 19]
```diff
@@ -0,0 +1,253 @@
...
+@reset-database-before-feature
+@reboot-kernel-before-feature
+@clear-cache-before-feature
+@order-ecotax
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature:5]:
```suggestion
@order-ecotax
@odd-order-ecotax
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_with_tax.feature [hunk 20]
```diff
@@ -0,0 +1,266 @@
+# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags order-ecotax
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_with_tax.feature]:
```suggestion
# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags order-ecotax-with-tax
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature [hunk 21]
```diff
@@ -0,0 +1,253 @@
+# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags order-ecotax
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature]:
```suggestion
# ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags basic-order-ecotax
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature [hunk 22]
```diff
@@ -0,0 +1,253 @@
...
+@reset-database-before-feature
+@reboot-kernel-before-feature
+@clear-cache-before-feature
+@order-ecotax
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature:5]:
```suggestion
@basic-order-ecotax
@order-ecotax
```

**Review by jolelievre — COMMENTED** [review]
@Progi1984 amazing wor on the behat tests!! Every single possible case is tested really nice

I don't want to block this one since it's already been approved twice, but I shared a concern I have about the way ecotax is handled in `Product::getPriceFromOrder` (see the comments in review)

I also had a question, did you check if `SearchProductsHandler` correctly handles advanced ecotax use cases? Especially when the ecotax tax rate doesn't match the one from the Product. Because it's used in the product page when we are searching for products and it prefills the prices so if this one is also buggy it will reduce all your hard work to nothing ^^

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 23]
```diff
@@ -180,22 +180,25 @@ private function updateOrderTotals(Order $order, Cart $cart, int $computingPreci
         $order->total_discounts_tax_excl = (float) abs($cart->getOrderTotal(false, Cart::ONLY_DISCOUNTS, $orderProducts, $carrierId, false, $this->keepOrderPrices));
         $order->total_discounts_tax_incl = (float) abs($cart->getOrderTotal(true, Cart::ONLY_DISCOUNTS, $orderProducts, $carrierId, false, $this->keepOrderPrices));
 
+        // We set $useEcotax to false because
+        //    $cart->getOrderTotal will fetch from order details which have already ecotax in their prices
+        $useEcotax = false;
         // We should always use Cart::BOTH for the order total since it contains all products, shipping fees and cart rules
         $order->total_paid = Tools::ps_round(
-            (float) $cart->getOrderTotal(true, Cart::BOTH, $orderProducts, $carrierId, false, $this->keepOrderPrices),
+            (float) $cart->getOrderTotal(true, Cart::BOTH, $orderProducts, $carrierId, false, $this->keepOrderPrices, $useEcotax),
```
Comment (jolelievre) [inline src/Adapter/Order/OrderAmountUpdater.php]: About the bug that @khouloudbelguith found, I guess you need to perform the same modifications in `updateOrderInvoices` And you'll probably need to add behat tests to check the invoice values as well

File: classes/order/OrderDetail.php (hunk 15 above)
Comment (Progi1984) [reply classes/order/OrderDetail.php]: Right. Fixed.

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature (hunk 18 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature (hunk 19 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_odd_tax.feature:5]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_with_tax.feature (hunk 20 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax_with_tax.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature (hunk 21 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature (hunk 22 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_ecotax.feature:5]: Fixed

File: src/Adapter/Order/OrderAmountUpdater.php (hunk 23 above)
Comment (Progi1984) [reply src/Adapter/Order/OrderAmountUpdater.php]: That works. And behat tests added ofc.

**Review by jolelievre — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have issues when Tax excluded is selected as `Price display method` in the Customer Group Setting.

1. Go to BO > Shop Parameters > Customer Settings > Groups page
2. Edit Customer Group
3. Set "Price display method" to tax excluded

**First issue**
1. Create a product with Tax included = 12 euro / Tax =20% / Ecotax =5 (price without tax 5 +5.833=10.8333)
2. Create an order with this product
2. Go to the last order created 
3. Edit the base price tax excluded to 20 
image
4. Save
5. The base price displayed is **20.83** 

=> there is difference between the price edited and the final price

**Second issue**
A product with combinations
There is difference between BO & FO
1. Create a product with combinations
2. Try to edit the first combination => impact Ecotax = 5
3. Try to edit the second combination => impact ecotax = 10
4. The price of the final product = 12 tax included without Ecotax 
image
5. Go to FO > Create an order with those combinations 
image
6. Go to BO > View last Order 
image
7. Go to old Order > Try to add those combinations 
image
8. Click Add
9. See the difference 
image


Thank you!

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I tried with PS1767.
**The first issue** => strange behavior.

1. Create a product with Tax included = 12 euro / Tax =20% / Ecotax =5 (price without tax 5 +5.833=10.8333)
2. Create an order with this product
3. Go to the last order created
4. See the base price tax excluded = €15.83 instead of €10.83
image

If `Price display method` = Tax included => ok we have €12
image

If we change the base price tax excluded to €20 and save
image
It will be €25.
image


**The second issue** with PS1767
I have the same price in the FO & BO 
image
image

Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith I fixed the second issue. But not the first one, could you create an issue for this one (not related to the scope of the PR), please ?

**Review by jolelievre — DISMISSED** [review]

File: classes/order/Order.php [hunk 24]
```diff
@@ -570,12 +570,15 @@ public static function cleanHistoryCache()
...
-        SELECT *
-        FROM `' . _DB_PREFIX_ . 'order_detail` od
-        LEFT JOIN `' . _DB_PREFIX_ . 'product` p ON (p.id_product = od.product_id)
-        LEFT JOIN `' . _DB_PREFIX_ . 'product_shop` ps ON (ps.id_product = p.id_product AND ps.id_shop = od.id_shop)
-        WHERE od.`id_order` = ' . (int) $this->id);
+        // The `od.ecotax` is a newly added at end as ecotax is used in multiples columns but it's the ecotax value we need
+        $sql = 'SELECT p.*, ps.*, od.*';
+        $sql .= ' FROM `%sorder_detail` od';
+        $sql .= ' LEFT JOIN `%sproduct` p ON (p.id_product = od.product_id)';
+        $sql .= ' LEFT JOIN `%sproduct_shop` ps ON (ps.id_product = p.id_product AND ps.id_shop = od.id_shop)';
```
Comment (PierreRambaud) [inline classes/order/Order.php:577]:
```suggestion
        $sql .= ' INNER JOIN `%sproduct` p ON (p.id_product = od.product_id)';
        $sql .= ' INNER JOIN `%sproduct_shop` ps ON (ps.id_product = p.id_product AND ps.id_shop = od.id_shop)';
```

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry but the last issue (combinations + Price display method = Tax excluded)is still reproduced.
Steps to reproduce the issue:
1. Go to BO > International > Tax > Enable Ecotax
2. Go to BO > Shop Parameters > Customer Settings > Group
3. Edit Customer group 
4. Change `Price display method` to Tax excluded
5. Create a new Product with two combinations
6. Tax included = 12 euro / Tax rule = 20 % / without Ecotax
image
7. Generate two combinations
7.1 First combinations has Ecotax = 5 euro tax included as a price and impact 
image
7.2 Second combination has Ecotax =10 euro tax included as a price and impact
image
8. Go to BO > Orders > Edit old order > Add the combinations
image

Here's an order created from the FO
image

I make a fresh install and checked commits => ok
image

Thank you!

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

About the first issue created here: https://github.com/PrestaShop/PrestaShop/issues/24340
Thank you!

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
:notebook: The bug is there only install in language :gb: with country :fr: not in language :fr: with country :fr:

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I checked these tests:
Edit old orders:
**Without Ecotax**
1. Add simple standard product
2. Add a similar product 
3. Add product with combinations (minimal quantity different + impact on price different)
4. Add virtual product
5. Add pack products
6. Add customized product
7. Add Out of stock product (Allowed & Not allowed)
8. Add a product with a specific price (quantity =1 )

The `Add action` is verified without updating the price & with updating the price
 => Invoice: ok :heavy_check_mark: 

**With Ecotax**
1. Add a product with a specific price (quantity = 1) => ok
2. Product with ecotax with combinations (has only impact on the price, not ecotax) => ok
3. Standard simple product => ok
4. When method price =  tax included: product without ecotax + with combinations (have an impact on ecotax) => ok
5. When method price =  tax included: Product with ecotax + combinations + impact ecotax + impact price => ok
6. Add those products with muti-invoice => ok
7. Edit the price of those products tax included => ok
8. Add those products with updating the base price ( When method price =  tax included)

The invoices => ok :heavy_check_mark: 

About this issue: https://github.com/PrestaShop/PrestaShop/pull/23492#issuecomment-832663349 as we discussed, I will create a new issue.
=> Issue created here: https://github.com/PrestaShop/PrestaShop/issues/24373

 **When method price =  tax excluded + Ecotax**
1. Add simple standard product => ok
2. Add simple standard product with editing the price => ok
3. Edit the base price => ok
4. Add a product with combinations (has no impact on ecotax) => ok
5. Add a product with a specific price => ok

Thank you!
