### PR TITLE
Multistore - Product on category page display out of stock flag instead of availlable on order

### LINKED ISSUE #27604: [Multistore] - Product on category page display out of stock flag instead of availlable on order
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

>Edited by Khouloud

Steps to reproduce the issue:
1. Enable Multistore & Create new Group shop with Share quantity = enabled
2. Create a shop assiciated to this Group shop
3. Create a product with quantity = 0 & allowed for order
4. Go to FO of the shop2 > Category list
5. See error > The product is displayed with out-of-stock flag
image

Hello, i'm back with my bug and i found the cause:

On catagory page i have product display as out of stock even if the product is availlable for order. But if I access to the product page, status is ok and product can be added on cart. More, when I add the product to cart, the status on category page change for the good status until the product are removed from the cart.

Not all product are affected. I searched in code and the problem come from the out_of_sotck parameter to define if you can order product out of stock. For some product the value of out_of_stock is empty on category page instead of 0,1 or 2. In this case it should be 1.

**Product.php line 5579:**

     ` $row['allow_oosp'] = Product::isAvailableWhenOutOfStock($row['out_of_stock']);`

Problem is only on category page.
Home page, product page, search page are ok.
To avoid loosing customer i disable message on category page

123515636-7b7b8e00-d698-11eb-853f-76c3ce5b1a0c

128632685-d1507f7f-9bf3-4c52-8459-34b62a81d6ac

128632731-46a0e0c9-5313-4dec-85c8-4040db14b05a

128632843-5d73b17b-3530-48b5-939e-0583711376be

I try to come back on the classic theme to identify if the problem occurs too. At first glance, no message is displaying and it seems to be normal. But classic theme doesn't display out of stock or allows order by default. If stock equal 0, no message is displayed. I try with not allow and allow order:

**themes/classic/templates/catalog/_partials/product-flags.tpl**

```
{block name='product_flags'}
    <ul class="product-flags">
        {foreach from=$product.flags item=flag}
            <li class="product-flag {$flag.type}">{$flag.label}</li>
        {/foreach}
    </ul>
{/block}
```
But if i add the check on allow on order (product.allow_oosp) and display message, we can see that property is not initialize with correct value on catalog part and availability message is wrong :

**themes/classic/templates/catalog/_partials/product-flags.tpl**

```
{block name='product_flags'}
    <ul class="product-flags">
        {if $product.quantity > 0}
            {foreach from=$product.flags item=flag}
                <li class="product-flag {$flag.type}">{$flag.label}</li>
            {/foreach}
        {else}
            {if !$product.allow_oosp}
                <li class="product-flag out-of-stock">{$product.availability_message}</li>
            {/if}
        {/if}
    </ul>
{/block}
```

**Root cause :** 
After a long investigation, i found that : On class ProductAssemblerCore (ProductAssembler.php in classes foler), there is a SQL request that seach information for product. 
This request seach stock information by product shop and don't take account that stock is configurated to share stock 👍 

```
LEFT JOIN {$prefix}stock_available sa
			        ON sa.id_product = p.id_product
			        AND sa.id_shop = $idShop
```

image

So on category page for shared stock management between  shop, information about stock are wrong

### Expected behavior

When a product is availlable for order even if its qty equal 0, display on demand on category page.

### Steps to reproduce

**You need to have multishop with shared product stock** 

1. Define product witch capability to be order even if stock are equal to 0
2. Define stock to 0
3. Show product on category page
4. Flag is out of stock instead of On-demand

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Rizzen59**
Adding shop group id on ProductSearchContext and update sql query on  ProductAssembler.php

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Take account of the sharing stock in product assembler. Adding Shop Group Id and flag in SearchContext
| Type?             | bug fix
| Category?         | FO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #27604
| How to test?      | As indicated in ticket, in multistore with stock sharing enable, adding product with allow order, the flag is correctly displayed
| Possible impacts? | Few impact. two proprerties in Search Context only used in productAssembler.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27841)

This PR could fix this issue: https://github.com/PrestaShop/PrestaShop/issues/28097

### CODE REVIEW

File: src/Core/Product/Search/ProductSearchContext.php [hunk 1]
```diff
@@ -139,4 +153,36 @@ public function getIdCustomer()
...
+    {
+        return $this->idShopGroup;
+    }
+
+    /**
+     * @param int $idShopGroup
+     */
+    public function setIdShopGroup(int $idShopGroup): void
+    {
+        $this->idShopGroup = $idShopGroup;
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setIdShopGroup(int $idShopGroup): self
    {
        $this->idShopGroup = $idShopGroup;
        
        return $this;
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 2]
```diff
@@ -139,4 +153,36 @@ public function getIdCustomer()
...
+    {
+        return $this->stockSharingBetweenShopGroupEnabled;
+    }
+
+    /**
+     * @param bool $stockSharingBetweenShopGroupEnabled
+     */
+    public function setStockSharingBetweenShopGroupEnabled(bool $stockSharingBetweenShopGroupEnabled): void
+    {
+        $this->stockSharingBetweenShopGroupEnabled = $stockSharingBetweenShopGroupEnabled;
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setStockSharingBetweenShopGroupEnabled(bool $stockSharingBetweenShopGroupEnabled): self
    {
        $this->stockSharingBetweenShopGroupEnabled = $stockSharingBetweenShopGroupEnabled;
        
        return $this;
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 3]
```diff
@@ -139,4 +153,36 @@ public function getIdCustomer()
...
+    /**
+     * @return bool
+     */
+    public function isStockSharingBetweenShopGroupEnabled(): bool
+    {
+        return $this->stockSharingBetweenShopGroupEnabled;
+    }
+
+    /**
+     * @param bool $stockSharingBetweenShopGroupEnabled
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php:186]:
```suggestion
     * @param bool $stockSharingBetweenShopGroupEnabled
     *
     * @return self
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 4]
```diff
@@ -139,4 +153,36 @@ public function getIdCustomer()
...
+    /**
+     * @return int
+     */
+    public function getIdShopGroup(): int
+    {
+        return $this->idShopGroup;
+    }
+
+    /**
+     * @param int $idShopGroup
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php:166]:
```suggestion
     * @param int $idShopGroup
     *
     * @return self
```

File: classes/ProductAssembler.php [hunk 5]
```diff
@@ -53,12 +54,14 @@ public function __construct(Context $context)
...
     private function addMissingProductFields(array $rawProduct)
     {
-        $idShop = (int) $this->searchContext->getIdShop();
-        $idLang = (int) $this->searchContext->getIdLang();
-        $idProduct = (int) $rawProduct['id_product'];
+        $idShop = (int)$this->searchContext->getIdShop();
+        $idShopGroup = (int)$this->searchContext->getIdShopGroup();
+        $isStockSharingBetweenShopGroupEnabled = (int)$this->searchContext->isStockSharingBetweenShopGroupEnabled();
+        $idLang = (int)$this->searchContext->getIdLang();
+        $idProduct = (int)$rawProduct['id_product'];
```
Comment (Progi1984) [inline classes/ProductAssembler.php]:
```suggestion
        $idShop = (int)$this->searchContext->getIdShop();
        $idShopGroup = $this->searchContext->getIdShopGroup();
        $isStockSharingBetweenShopGroupEnabled = $this->searchContext->isStockSharingBetweenShopGroupEnabled();
        $idLang = (int) $this->searchContext->getIdLang();
        $idProduct = (int) $rawProduct['id_product'];
```

File: classes/ProductAssembler.php [hunk 6]
```diff
@@ -53,12 +54,14 @@ public function __construct(Context $context)
...
         $prefix = _DB_PREFIX_;
 
-        $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
+        $nbDaysNewProduct = (int)Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
```
Comment (Progi1984) [inline classes/ProductAssembler.php]:
```suggestion
        $nbDaysNewProduct = (int) Configuration::get('PS_NB_DAYS_NEW_PRODUCT');
```

**Review by Progi1984 — COMMENTED** [review]
@Rizzen59 Thank you for your contribution. I have brought you some comments but the bugfix logic is good.

File: src/Core/Product/Search/ProductSearchContext.php (hunk 2 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done !

File: src/Core/Product/Search/ProductSearchContext.php (hunk 3 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php:186]: Done !

File: src/Core/Product/Search/ProductSearchContext.php (hunk 4 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php:166]: Done

**Comment by Rizzen59** [comment]
> @Rizzen59 Thank you for your contribution. I have brought you some comments but the bugfix logic is good.

Thanks. I commit the suggestion.
I use phpStorm. Is there a specific formatter config ?

**Review by matthieu-rolland — COMMENTED** [review]
you have some linting issues but lgtm otherwise 👍

**Comment by Rizzen59** [comment]
> you have some linting issues but lgtm otherwise 👍

wich linter do you use ?

**Review by Progi1984 — COMMENTED** [review]
@Rizzen59 I think you don't push your last modifications. Could you check my comments ?

**Comment by Rizzen59** [comment]
I done a new pass. 

- I check all warning from phpstorm linter (I added type for all parameters and return values)
- i reintroduced space between type cast and parameters removed by phpstorm formatter

Just one point : all originals setters return "$this" so as to chain call. I don't understand why returning slef instead of $this on new setters. For me self is for static context.

Thank you for your time and advice. 
Please, let me know if there are specifics linters or formatters configuration to improve my contribution.

**Comment by NeOMakinG** [comment]
Seems like it brokes something in the UI tests, except if it's not related

File: classes/ProductAssembler.php [hunk 7]
```diff
@@ -82,11 +85,18 @@ private function addMissingProductFields(array $rawProduct)
...
                     ON pl.id_product = p.id_product
                     AND pl.id_shop = $idShop
-                    AND pl.id_lang = $idLang
-                LEFT JOIN {$prefix}stock_available sa
-			        ON sa.id_product = p.id_product
-			        AND sa.id_shop = $idShop
-                LEFT JOIN {$prefix}product_shop ps
+                    AND pl.id_lang = $idLang ";
+
+        $sql .= "LEFT JOIN {$prefix}stock_available sa ";
```
Comment (Progi1984) [inline classes/ProductAssembler.php]:
```suggestion
                    AND pl.id_lang = $idLang ";

        $sql .= "LEFT JOIN {$prefix}stock_available sa ";
```
```suggestion
                    AND pl.id_lang = $idLang
                LEFT JOIN {$prefix}stock_available sa ";
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 8]
```diff
@@ -65,7 +79,7 @@ public function __construct(Context $context = null)
      *
      * @return $this
      */
-    public function setIdShop($idShop)
+    public function setIdShop(int $idShop): ProductSearchContext
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setIdShop($idShop)
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 9]
```diff
@@ -75,7 +89,7 @@ public function setIdShop($idShop)
     /**
      * @return int the Product Search Shop id
      */
-    public function getIdShop()
+    public function getIdShop(): int
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function getIdShop()
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 10]
```diff
@@ -95,7 +109,7 @@ public function setIdLang($idLang)
     /**
      * @return int the Product Search Language id
      */
-    public function getIdLang()
+    public function getIdLang(): int
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function getIdLang()
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 11]
```diff
@@ -85,7 +99,7 @@ public function getIdShop()
      *
      * @return $this
      */
-    public function setIdLang($idLang)
+    public function setIdLang(int $idLang): ProductSearchContext
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setIdLang($idLang)
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 12]
```diff
@@ -105,7 +119,7 @@ public function getIdLang()
      *
      * @return $this
      */
-    public function setIdCurrency($idCurrency)
+    public function setIdCurrency(int $idCurrency): ProductSearchContext
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setIdCurrency($idCurrency)
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 13]
```diff
@@ -115,7 +129,7 @@ public function setIdCurrency($idCurrency)
     /**
      * @return int the Product Search Currency id
      */
-    public function getIdCurrency()
+    public function getIdCurrency(): int
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function getIdCurrency()
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 14]
```diff
@@ -125,7 +139,7 @@ public function getIdCurrency()
      *
      * @return $this
      */
-    public function setIdCustomer($idCustomer)
+    public function setIdCustomer(int $idCustomer): ProductSearchContext
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setIdCustomer($idCustomer)
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 15]
```diff
@@ -135,8 +149,46 @@ public function setIdCustomer($idCustomer)
     /**
      * @return int the Product Search Customer id
      */
-    public function getIdCustomer()
+    public function getIdCustomer(): int
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function getIdCustomer()
```

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Please remove all new type hint. It's BC so we can't embed that in patch version.

File: classes/ProductAssembler.php (hunk 7 above)
Comment (Rizzen59) [reply classes/ProductAssembler.php]: applied

File: src/Core/Product/Search/ProductSearchContext.php (hunk 8 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 9 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 11 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 10 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 12 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 13 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 14 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

File: src/Core/Product/Search/ProductSearchContext.php (hunk 15 above)
Comment (Rizzen59) [reply src/Core/Product/Search/ProductSearchContext.php]: Done

**Comment by Rizzen59** [comment]
I updated code with you advice in review

File: src/Core/Product/Search/ProductSearchContext.php [hunk 16]
```diff
@@ -139,4 +153,44 @@ public function getIdCustomer()
     {
         return $this->idCustomer;
     }
+
+    /**
+     * @return int the Shop Group Iid
+     */
+    public function getIdShopGroup()
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function getIdShopGroup(): int
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 17]
```diff
@@ -139,4 +153,44 @@ public function getIdCustomer()
...
+    {
+        return $this->idShopGroup;
+    }
+
+    /**
+     * @param int $idShopGroup
+     *
+     * @return self
+     */
+    public function setIdShopGroup($idShopGroup)
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setIdShopGroup(int $idShopGroup): self
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 18]
```diff
@@ -139,4 +153,44 @@ public function getIdCustomer()
...
+    {
+        $this->idShopGroup = $idShopGroup;
+
+        return $this;
+    }
+
+    /**
+     * @return bool if sharing stock is enable
+     */
+    public function isStockSharingBetweenShopGroupEnabled()
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function isStockSharingBetweenShopGroupEnabled(): bool
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 19]
```diff
@@ -139,4 +153,44 @@ public function getIdCustomer()
...
+    {
+        return $this->stockSharingBetweenShopGroupEnabled;
+    }
+
+    /**
+     * @param bool $stockSharingBetweenShopGroupEnabled
+     *
+     * @return self
+     */
+    public function setStockSharingBetweenShopGroupEnabled($stockSharingBetweenShopGroupEnabled)
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
    public function setStockSharingBetweenShopGroupEnabled(bool $stockSharingBetweenShopGroupEnabled): self
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 20]
```diff
@@ -50,10 +50,24 @@ class ProductSearchContext
...
+    private $stockSharingBetweenShopGroupEnabled = false;
+
     public function __construct(Context $context = null)
     {
         if ($context) {
+            $shopGroup = $context->shop->getGroup();
+
             $this->idShop = $context->shop->id;
+            $this->idShopGroup = $shopGroup->id;
+            $this->stockSharingBetweenShopGroupEnabled = boolval($shopGroup->share_stock);
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
            $this->stockSharingBetweenShopGroupEnabled = (bool) $shopGroup->share_stock;
```

**Review by Progi1984 — COMMENTED** [review]
Small fixes on your PR. You can typehint new method but not old, else it's a BC.

**Comment by Rizzen59** [comment]
That should be ok :)

File: classes/ProductAssembler.php [hunk 21]
```diff
@@ -50,11 +50,14 @@ public function __construct(Context $context)
      * @param array $rawProduct
      *
      * @return array
+     * @throws PrestaShopDatabaseException
```
Comment (Progi1984) [inline classes/ProductAssembler.php:54]:
```suggestion
     *
     * @throws PrestaShopDatabaseException
```

File: src/Core/Product/Search/ProductSearchContext.php [hunk 22]
```diff
@@ -50,10 +50,24 @@ class ProductSearchContext
      */
     private $idCustomer;
 
+    /**
+     * @var int the Shop Group id
+     */
+    private $idShopGroup;
+
+    /**
+     * @var boolean if the sharing stock is enable
```
Comment (Progi1984) [inline src/Core/Product/Search/ProductSearchContext.php]:
```suggestion
     * @var bool if the sharing stock is enable
```

**Review by Progi1984 — COMMENTED** [review]
Two last changes and the CI should be ok. Thanks

**Comment by Rizzen59** [comment]
I cmmited your review

**Review by Progi1984 — DISMISSED** [review]

**Comment by Rizzen59** [comment]
PHP / PHP Coding Standards Fixer (pull_request)  -> there's no more explaination about error ? I have juste Error: Process completed with exit code 8

Do you have any idea ?

**Comment by Progi1984** [comment]
@Rizzen59 Check that error message : https://github.com/PrestaShop/PrestaShop/runs/5985623237?check_suite_focus=true#step:8:14

File: classes/ProductAssembler.php [hunk 23]
```diff
@@ -106,6 +117,7 @@ private function addMissingProductFields(array $rawProduct)
      * @param array $rawProduct
      *
      * @return mixed
+     * @throws PrestaShopDatabaseException
```
Comment (matks) [inline classes/ProductAssembler.php:121]:
```suggestion
     *
     * @throws PrestaShopDatabaseException
```

**Review by matks — DISMISSED** [review]
@Rizzen59 

```
un ./vendor/bin/php-cs-fixer fix --dry-run --diff
Loaded config default from "/home/runner/work/PrestaShop/PrestaShop/.php_cs.dist".
   1) /home/runner/work/PrestaShop/PrestaShop/classes/ProductAssembler.php
      ---------- begin diff ----------
--- Original
+++ New
@@ @@
      * @return mixed
+     *
```

PHP CS fixer wants an empty line between `return` and `throw` 😉

File: classes/ProductAssembler.php (hunk 23 above)
Comment (Rizzen59) [reply classes/ProductAssembler.php:121]: Thnaks it's fixed normally

**Comment by Rizzen59** [comment]
Hi someone can run worfkflow.
Thanks :)

**Review by Progi1984 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @Rizzen59,

Thank you for this PR.
Tested on 1.7.8.x with PHP 7.2 version

1. Enable multistore.
2. Create a product on all shops.
- set quantity to 0 and use default behavior when out of stock (deny orders): on FO, out of stock label is well displayed ✅ 
- choose main shop on the default group
	- keep quantity to 0 and set allow orders when out of stock
	- go to FO on the shop (product page and category page), out of stock label is not displayed ✅ 
- choose the shop on the second group
	- keep quantity to 0 and set allow orders when out of stock
	- go to FO on the shop (product page and category page), out of stock label is not displayed ✅ 

QA approved ✅ 

Thanks

**Comment by Progi1984** [comment]
Thanks @Rizzen59 & @sLorenzini

**Comment by Rizzen59** [comment]
You're welcome. I was very busy last weeks. But il will try to find more time to help on Prestashop

**Comment by Progi1984** [comment]
@Rizzen59 Thanks to you for advance.
