### PR TITLE
Fix ProductCore::getDefaultCategory to return an int consistently

### LINKED ISSUE #31747: Dashboardproducts wrongly uses NULL default Category
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Dashboardproducts native module always uses `NULL` as the default Category for products, because of a silent bug only revealed by PHP warnings.

Within early PrestaShop 1.7
```none
PHP Warning: Illegal string offset 'id_category_default'
```
- After @Progi1984  's Patch https://github.com/PrestaShop/PrestaShop/blame/21aa4c7d00b66aef61ca37494e63403ad6e79f9c/classes/Product.php#L7852
```none
PHP Warning:  Trying to access array offset on value of type int
```

The fallback value after the warnings is always `NULL` and it is used to construct the default `new Category` object in the Dashboardproducts module.

### Expected behavior

`Product->getDefaultCategory` may return either a string, an int or an array with an `id_category_default` key, when SQL value is found \(due to another bug in `ProductCore->getDefaultCategory` which uses `Db::getInstance()->getValue` and proceeds like it would return a result array from PDO or MySQLI.

Due to the upstream core bug in the `Product->getDefaultCategory`, the returned value has to be checked for type and handled accordingly. \(_to maintain backward compatibility with the Core bug and plan forward compatibility for when the Core bug patch PrestaShop/PrestaShop#31752 can be merged_).

### Steps to reproduce

1. Open backoffice Dashboard
2. Open server logs and see the PHP Warning

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

dashproducts

### PR DESCRIPTION
**Pull request by lea-BMS**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | `ProductCore->getDefaultCategory` inconsistently returned an array or an int. <br> This fixes the return value to be always an int.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Check the default Category in Dashboardproducts is correctly pulled in the dashboard.
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#31747
| Related PRs       | Needs PrestaShop/dashproducts#47 to be merged to correctly handle the returned int default_category_id .
| Sponsor company   | BM Services

### CODE REVIEW

File: classes/Product.php [hunk 1]
```diff
@@ -7833,24 +7833,20 @@ public function setAdvancedStockManagement($value)
...
      */
-    public function getDefaultCategory()
+    public function getDefaultCategory(): int
     {
         $default_category = Db::getInstance()->getValue(
             'SELECT product_shop.`id_category_default`
             FROM `' . _DB_PREFIX_ . 'product` p
             ' . Shop::addSqlAssociation('product', 'p') . '
-            WHERE p.`id_product` = ' . (int) $this->id
+            WHERE p.`id_product` = ' . (int)$this->id
```
Comment (kpodemski) [inline classes/Product.php]:
```suggestion
            WHERE p.`id_product` = ' . (int) $this->id
```

File: classes/Product.php [hunk 2]
```diff
@@ -7833,24 +7833,20 @@ public function setAdvancedStockManagement($value)
...
         );
 
-        if (!$default_category) {
-            return ['id_category_default' => Context::getContext()->shop->id_category];
-        } else {
-            return (int) $default_category;
-        }
+        return $default_category ? (int)$default_category : Context::getContext()->shop->id_category;
```
Comment (kpodemski) [inline classes/Product.php]:
```suggestion
        return (int) $defaultCategory ?? Context::getContext()->shop->id_category;
```

File: classes/Product.php [hunk 3]
```diff
@@ -7833,24 +7833,20 @@ public function setAdvancedStockManagement($value)
...
-     * Get the default category according to the shop.
+     * Get the default category id according to the shop.
      *
-     * @return array{id_category_default: int}|int
+     * @return int
      */
-    public function getDefaultCategory()
+    public function getDefaultCategory(): int
     {
         $default_category = Db::getInstance()->getValue(
```
Comment (kpodemski) [inline classes/Product.php]:
```suggestion
        $defaultCategory = Db::getInstance()->getValue(
```

**Review by kpodemski — COMMENTED** [review]
Thanks for contributing @lea-BMS 🎉 

I added a few suggestions.

**Review by FabienPapet — DISMISSED** [review]

File: classes/Product.php [hunk 4]
```diff
@@ -7833,24 +7833,20 @@ public function setAdvancedStockManagement($value)
...
             ' . Shop::addSqlAssociation('product', 'p') . '
             WHERE p.`id_product` = ' . (int) $this->id
         );
 
-        if (!$default_category) {
-            return ['id_category_default' => Context::getContext()->shop->id_category];
-        } else {
-            return (int) $default_category;
-        }
+        return (int) $defaultCategory ?? Context::getContext()->shop->id_category;
```
Comment (0x346e3730) [inline classes/Product.php]:
```suggestion
        return (int) ($defaultCategory ?? Context::getContext()->shop->id_category);
```

Without the brackets the casting to int is applied to `$defaultCategory`. If `$defaultCategory` is null it will return `0` instead of `Context::getContext()->shop->id_category`.
https://3v4l.org/gIpZB

**Review by 0x346e3730 — CHANGES_REQUESTED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
I took the liberty of moving your other PR forward: https://github.com/PrestaShop/dashproducts/pull/47

See my comment other there, you still have a small modification to make for phpstan to be happy.

**Comment by lartist** [comment]
QA dev 🟢

**Comment by lea-BMS** [comment]
> I took the liberty of moving your other PR forward: [PrestaShop/dashproducts#47](https://github.com/PrestaShop/dashproducts/pull/47)
> 
> See my comment other there, you still have a small modification to make for phpstan to be happy.

Thank you for moving it forward. I admit I am short on spare time for this and delayed it.

**Comment by lartist** [comment]
I don't see how to dev test this one so I ran auto tests. If everything is ok I can merge https://github.com/lartist/ga.tests.ui.pr/actions/runs/4562250664

**Review by zuk3975 — APPROVED** [review]

**Comment by zuk3975** [comment]
some automated tests are failing, not sure if they are related, @lartist could you try to restart failing ones?

**Comment by lartist** [comment]
> some automated tests are failing, not sure if they are related, @lartist could you try to restart failing ones?

I've just done it. We'll see.

Anyway I think @Progi1984 add some fix on auto tests. If the rerun doesn't work plz try to rebase on develop @lea-BMS

**Comment by lartist** [comment]
auto test 🟢 thanks @lea-BMS

**Comment by jf-viguier** [comment]
Fixed by https://github.com/PrestaShop/dashproducts/pull/50
