### PR TITLE
Fix "undefined" error when modifying product quantity in FO product quick view 

### LINKED ISSUE #17104: Server error when quickview product quantity changed
### Describe the bug 
Server error when quickview product quantity changed

### Expected behavior
No error message is displayed

1. go to FO
2. click on any product to open the product page
3. scroll down open related product quick view modal
4. increase the product quantity
5. see "undefined" error message

---
1. Open any product page with additional parameters (ie. color):
image
2. Open quickview product in the category products widget:
image
image
3. Close quickview. Now we see an error message under original product`s "add to cart" button.
image
4. Error in the browser console:
image

### Additional infos:

- PS version: 1.7.6.0
- PHP version: 7.1

### PR DESCRIPTION
**Pull request by yanmakouf**
…t found error to throw uncatched error

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Server error when quickview product quantity changed. Do not try to retrieve product attribute if product has no combinations.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes #17104
| Related PRs       |N/A.
| How to test?      | Go to FO > Open any product page > In related products footer 5already seen, or similar > Open a product's Quick View > Modify Quantity/combinations > See NO undefined error.
| Possible impacts? | FO Product Pages/ Cart features

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Looks valid 👍

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -1091,16 +1091,27 @@ function ($elem) use ($attribute) {
...
+                'Product'
+            );
         }
 
-        return (int) Product::getIdProductAttributeByIdAttributes(
-            $this->product->id,
-            $groups,
-            true
-        );
+        return null;
```
Comment (jolelievre) [inline controllers/front/ProductController.php]:
```suggestion
        return 0;
```

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -1091,16 +1091,27 @@ function ($elem) use ($attribute) {
      */
     private function getIdProductAttributeByGroup()
     {
-        $groups = Tools::getValue('group');
-        if (empty($groups)) {
-            return null;
+        try {
```
Comment (jolelievre) [inline controllers/front/ProductController.php:1103]: I remember we discussed about this one and we realized that the whole attribute fetching feature is meaningless for product which have no combinations. Fixing this method is a good thing, but it's a side effect of the initial problem.

In `getIdProductAttributeByGroupOrRequestOrDefault` we should check that product has combinations in the first place, if it doesn't the method should return 0 early.

**Review by jolelievre — COMMENTED** [review]
Thanks @yanmakouf 

Just an improvement suggestion based on what we discussed

**Review by Amoifr — COMMENTED** [review]
nothing to say more than @jolelievre

File: controllers/front/ProductController.php (hunk 2 above)
Comment (yanmakouf) [reply controllers/front/ProductController.php:1103]: Thanks for the review :) Agreed. I forgot that part sorry. I am just nore sure about returning early 0 in `getIdProductAttributeByGroupOrRequestOrDefault ` i'd rather return `null` seing the return result usage a line 546 and 562. Or Maybe it would introduce a BC break ? returning new type 🤔

**Review by yanmakouf — COMMENTED** [review]
@jolelievre @Amoifr PR fixed (I think :) )

File: controllers/front/ProductController.php [hunk 3]
```diff
@@ -985,17 +985,26 @@ private function getIdProductAttributeByRequest()
...
      * or request parameter, or the default attribute as a fallback.
      *
-     * @return int
+     * @return int|null
      *
      * @throws PrestaShopException
      */
     private function getIdProductAttributeByGroupOrRequestOrDefault()
     {
+        // If product has no combinations we early return 0
```
Comment (kpodemski) [inline controllers/front/ProductController.php]:
```suggestion
        // If the product has no combinations, we return early
```

File: controllers/front/ProductController.php (hunk 2 above)
Comment (jolelievre) [reply controllers/front/ProductController.php:1103]: No for standard product in this page I know we usually expect 0 to be set, there may even be some special tests somewhere that tests if `=== 0` so it's safer to keep the int return and return 0

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @yanmakouf

**Review by florine2623 — COMMENTED** [review]
Hello @yanmakouf ,

In any popup in the product page, I can't change de combinations anymore. :x:
In the homepage, or category page, it is OK.

When 1 combination is active:

https://user-images.githubusercontent.com/16019289/188411626-80c7ed3b-cb22-4da0-9e74-efbb4fd63b18.mov

https://user-images.githubusercontent.com/16019289/188412061-839ff969-5d50-4a67-9109-74d8db2bd8be.mov

When multiple combinations are active, it is OK.

Could you check ?
Thanks!

**Comment by yanmakouf** [comment]
Hi @florine2623 thanks for your input. I noticed the same behavior with size combinations when i was working on the fix, thought i fixed it, I will try to test again and fix in the next few day. I'll get back to you :)

**Review by florine2623 — APPROVED** [review]
Hello @yanmakouf ,

Tested again, I couldn't reproduce my previous issue. Probably a cache issue as you said.

Tested the following:
- product quickview in `category page`
- product quickview in `homepage`
- product quickview in `product page` (related product, viewed product, same category, etc)
- product quickview in `brand page`
- product quickview in `Price drop page`
- product quickview in `New products page`
- tested with 1 or more combinations

No alert is shown. It is QA ✅ !
Thanks!

**Comment by jolelievre** [comment]
Thanks @florine2623 and @yanmakouf
