### PR TITLE
Fix: actionCarrierUpdate not triggered on migrated carrier page

### LINKED ISSUE #40067: actionCarrierUpdate not triggered on migrated carrier page
### Describe the bug and add attachments

actionCarrierUpdate is not triggered on migrated carrier page.

### Expected behavior

The hook must be triggered so modules can react on it. Needed for cash on delivery modules for example.

### Steps to reproduce

1. Hook into actionCarrierUpdate via ps_qualityassurance.
2. See that on the old page, the hook triggered.
3. On the migrated page, it doesn't.

### PrestaShop version(s) where the bug happened

9.0.0

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.1.x
| Description?      | This PR adds the call to the actionCarrierUpdate hook for the new carrier page implemented in Symfony.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Enable the new **Carriers** feature in _Advanced Parameters > New & Experimental Features_ <br/> 2. Install the following module: [pr40070.zip](https://github.com/user-attachments/files/25919072/pr40070.zip)<br/> 3. Edit a carrier<br/> 4. After saving, the system should display **Hook hookActionCarrierUpdate executed with id_carrier: CARRIER_ID and new carrier ID: CARRIER_ID** as shown below:<br/> Screenshot 2025-11-21 at 15-00-10 Editing carrier Click and collect mod 2 • Codencode
| UI Tests          | 🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/23542452434
| Fixed issue or discussion?     | Fixes #40067
| Related PRs       | 
| Sponsor company   | Codencode snc

### CODE REVIEW

File: src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php [hunk 1]
```diff
@@ -125,6 +128,15 @@ public function update($id, array $data)
         // Finally we save the tax rules group
         $carrierId = $this->setCarrierTaxRuleGroup($carrierId, $data);
 
+        $this->hookDispatcher->dispatchWithParameters(
+        'actionCarrierUpdate',
+        [
+            'id_carrier' => (int) $id,
+            // BIG NOTE: 
+            // The hook "actionCarrierUpdate" expects the carrier (Carrier object) as a parameter, but we cannot use legacy classes here, so we need to decide how to proceed.
+            'carrier' => new Carrier((int) $carrierId->getValue()),
```
Comment (Codencode) [inline src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: @Hlavtox
Hi Daniel, dyou have any suggestions for solving this problem?

**Comment by Hlavtox** [comment]
@Codencode You can just add this call to ignore list, but maybe we should change approach here?

@kpodemski @jolelievre Guys, how to proceed here, when we use repository instead of object model? Do we just pass the id and call it a day? Do we instantiate the object model?

**Comment by Codencode** [comment]
> @Codencode You can just add this call to ignore list, but maybe we should change approach here?
> 
> @kpodemski @jolelievre Guys, how to proceed here, when we use repository instead of object model? Do we just pass the id and call it a day? Do we instantiate the object model?

@Hlavtox 
I’d rather find a proper solution, also because some time ago I was “told off” in another PR for using legacy classes in the Core namespace, as they shouldn’t be used 😄

**Comment by Codencode** [comment]
As suggested by @Hlavtox and @jolelievre on Slack, I added an exception to avoid errors with PHP Static Analysis.

File: src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php [hunk 2]
```diff
@@ -125,6 +128,14 @@ public function update($id, array $data)
         // Finally we save the tax rules group
         $carrierId = $this->setCarrierTaxRuleGroup($carrierId, $data);
 
+        $this->hookDispatcher->dispatchWithParameters(
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: I'm not sure to understand why this is needed The form data handler should trigger the CQRS command which is still absed on ObjectModel so the generic hooks are triggered Why would we need an extra hook here?

Besides it doesn't really respect the chain of responsibility we have on all other migrated pages, the form data handler is meerly here as the bridge between the form and the CQRS layer

**Review by jolelievre — DISMISSED** [review]

File: src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: Besides this solution is not really optimized because it instanciates a new ObjectModel while we already manipulate one in the CQRS layer 🤔

Comment (Codencode) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: >I'm not sure to understand why this is needed The form data handler should trigger the CQRS command which is still absed on ObjectModel so the generic hooks are triggered Why would we need an extra hook here?

I believe it is necessary because on the legacy page the hook "actionCarrierUpdate" was executed, while on the migrated page the hook is no longer executed.
If we do not execute it, there is currently no way to trigger a hook after the carrier is saved.
cc @Hlavtox

Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: @jolelievre 

It's a special hook that is quite popular in the ecosystem, previously it was part of the controller, that's why I kinda understand why @Codencode decided to do it like this

Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: @jolelievre 

so, realistically speaking, should we keep this hook somewhere in the controller and deprecate it, or do something else?

Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: I commented on the issue https://github.com/PrestaShop/PrestaShop/issues/40067#issuecomment-3728569013

Do you guys know the purpose of this hook? (compared to the generic objectmodel hook) If the need is to have both old and new acrrier object because of the special update/duplicate process on this entity then it makes sense. But as I said in the comment this should be implemented in the update handler instead It's a matter of responsibility, and this way the mechanic will also work for the Admin API

Comment (Hlavtox) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: > Besides this solution is not really optimized because it instanciates a new ObjectModel while we already manipulate one in the CQRS layer 🤔

ObjectModel instances are cached, they are fetched from DB only once.

Comment (Hlavtox) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: > Do you guys know the purpose of this hook? (compared to the generic objectmodel hook) If the need is to have both old and new acrrier object because of the special update/duplicate process on this entity then it makes sense. But as I said in the comment this should be implemented in the update handler instead It's a matter of responsibility, and this way the mechanic will also work for the Admin API

Replied on the issue. :-)

Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: > ObjectModel instances are cached, they are fetched from DB only once.

The DB may be cached but the object itself is still created twice, although it's a minor performance issue the object is not that big in memory Besides there are other reasons why this should be done in the handler:
- respect the responsibility of components
- usage in the Admin API

Comment (Codencode) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: @jolelievre in your opinion how should we handle this?

**Comment by paulnoelcholot** [comment]
@Codencode any news?

**Comment by Codencode** [comment]
@paulnoelcholot I'm waiting for a response from @jolelievre

File: src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php (hunk 2 above)
Comment (Codencode) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: > @jolelievre in your opinion how should we handle this?

Ping @jolelievre

**Review by Hlavtox — DISMISSED** [review]

File: src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: This should be moved inside the CQRS handler, this the hook will also work when it's integrated in the Admin API

So in `EditCarrierHandler`, and to mimic the way it was called in the legacy controller the hook should be called at the same step of the process:
- so after the carrier is updated
- before the log and zones are updated

And you should already have the `$newCarrier` ObjectModel available in the handler so no need to reinstanciate it

Comment (Codencode) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: @jolelievre, great!
You were right, EditCarrierHandler was actually enough, how did I not understand that earlier!

Anyway, I've made the change.
Thanks Jonathan!

Comment (Codencode) [reply src/Core/Form/IdentifiableObject/DataHandler/CarrierFormDataHandler.php]: I also ran the UI tests again and they are ok

**Comment by Progi1984** [comment]
Hello @Codencode 

Thank you for your contribution to PrestaShop!

We would like to inform you that **PrestaShop 9.1 has been officially released**. You can find the full announcement at the following link:
👉 https://build.prestashop-project.org/news/2026/prestashop-9-1-0-available/

Following this release, **9.0.x** is no longer the active development branch. To ensure your changes can be reviewed and merged, please **rebase this pull request onto the `9.1.x` branch**.

> ⚠️ **Important:** the `9.0.x` branch will be **permanently deleted on April 6, 2026**. Please make sure to rebase before that date.

If you have any questions or need assistance with the rebase process, do not hesitate to ask.

Thank you for your understanding and continued support!

**Review by kpodemski — CHANGES_REQUESTED** [review]
It's all good there @Codencode - rebase needed only :)

**Review by kpodemski — APPROVED** [review]

**Comment by Codencode** [comment]
@kpodemski Were the UI tests also rerun?

**Comment by kpodemski** [comment]
@Codencode yes, you've changed the branch and codebase is totally different

**Comment by Codencode** [comment]
ping @Hlavtox @jolelievre for "reapprove"

**Review by Hlavtox — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Codencode, 

Thanks for your PR, i tested it and it's good for me 


https://github.com/user-attachments/assets/f4f8aa18-fb32-43bf-9d50-e630ebed7347

Thank you

**Review by SiraDIOP — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
