### PR TITLE
Fix empty email subject in the translation interface

### LINKED ISSUE #19288: Subject fields appear blank in email translation
#### Describe the bug

Subject's translation is not displayed in the input field when I saved it from the email translation section

#### Steps to Reproduce

1) Install a module which contains email (a mails folder inside the module).
2) To translate the email subjects in any language go to the International > Translations > Email translations like this screenshot https://prnt.sc/sm3ntw
3) Select email body translation
4) Fill subject in input field https://prnt.sc/sm3omn
5) Save and stay
6) Now after saving, there is no content in the input field https://prnt.sc/sm3ntw
The entered subject is not appearing.

**Screenshots**
https://prnt.sc/sm3ntw
https://prnt.sc/sm3omn
If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information
* PrestaShop version: 1.7.7.0
* PHP version: 7.2.0

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Subject's translation is not displayed in the input field when I saved it from the email translation section check this screenshot image
| Type?         | bug fix 
| Category?     | BO
| Fixed ticket? | Fixes #19288 and #15381
| How to test?  | Please install our test module from this link [wktestmodule](https://github.com/Amit-Kumar-Tiwari-Webkul/wktestmodule/blob/master/wktestmodule.zip)<br>and install it and follow the steps as mention in issue #19288

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19289)

### CODE REVIEW

File: controllers/admin/AdminTranslationsController.php [hunk 1]
```diff
@@ -2191,7 +2191,32 @@ public function getListModules($withInstance = false)
 
         return $modules;
     }
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

File: controllers/admin/AdminTranslationsController.php [hunk 2]
```diff
@@ -2191,7 +2191,32 @@ public function getListModules($withInstance = false)
 
         return $modules;
     }
+    
+    /**
+     * @param $directory : name of directory
+     * @return array
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion
     * @param $directory : name of directory
     *
     * @return array
```

File: controllers/admin/AdminTranslationsController.php [hunk 3]
```diff
@@ -2191,7 +2191,32 @@ public function getListModules($withInstance = false)
...
+     */
+    protected function getSubjectMailContent($directory)
+    {
+        $subject_mail_content = array();
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion
        $subject_mail_content = [];
```

File: controllers/admin/AdminTranslationsController.php [hunk 4]
```diff
@@ -2191,7 +2191,32 @@ public function getListModules($withInstance = false)
...
+
+        if (Tools::file_exists_cache($directory.'/lang.php')) {
+            // we need to include this even if already included (no include once)
+            include($directory.'/lang.php');
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion
            include($directory . '/lang.php');
```

File: controllers/admin/AdminTranslationsController.php [hunk 5]
```diff
@@ -2191,7 +2191,32 @@ public function getListModules($withInstance = false)
...
+            foreach ($GLOBALS[$this->translations_informations[$this->type_selected]['var']] as $key => $subject) {
+                $this->total_expression++;
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion
                ++$this->total_expression;
```

File: controllers/admin/AdminTranslationsController.php (hunk 3 above)
Comment (Amit-Kumar-Tiwari-Webkul) [reply controllers/admin/AdminTranslationsController.php]: I have added an array initialization based on your suggestion. But my opinion there was no need

Comment (Progi1984) [reply controllers/admin/AdminTranslationsController.php]: It's a requirement for passing PHPCSFixer check.

File: controllers/admin/AdminTranslationsController.php (hunk 5 above)
Comment (Amit-Kumar-Tiwari-Webkul) [reply controllers/admin/AdminTranslationsController.php]: HI,
Thanks for the suggestion but i don't think that there is any need of pre-increment of $this->total_expression variable

Comment (Amit-Kumar-Tiwari-Webkul) [reply controllers/admin/AdminTranslationsController.php]: HI,
I understand. It is mandatory for PHPCS Fixer

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@Amit-Kumar-Tiwari-Webkul Hi, Could you execute this `./vendor/bin/php-cs-fixer fix --dry-run --diff` and fix errors ? Thanks

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
> @Amit-Kumar-Tiwari-Webkul Hi, Could you execute this `./vendor/bin/php-cs-fixer fix --dry-run --diff` and fix errors ? Thanks
@Progi1984 , Can you help me to resolve this because as per standard it should be shown like this
see screenshot https://prnt.sc/sni69n

File: controllers/admin/AdminTranslationsController.php [hunk 6]
```diff
@@ -2191,7 +2191,7 @@ public function getListModules($withInstance = false)
 
         return $modules;
     }
-
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

File: controllers/admin/AdminTranslationsController.php [hunk 7]
```diff
@@ -3308,4 +3310,32 @@ public function displayAjaxEmailHTML()
...
+    
+    /**
+     * @param $directory : name of directory
+     *
+     * @return array
+     */
+    protected function getSubjectMailContent($directory)
+    {
+        $subject_mail_content = [];
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

File: controllers/admin/AdminTranslationsController.php [hunk 8]
```diff
@@ -3308,4 +3310,32 @@ public function displayAjaxEmailHTML()
             AdminTranslationsController::getEmailHTML($email)
         );
     }
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

File: controllers/admin/AdminTranslationsController.php [hunk 9]
```diff
@@ -3308,4 +3310,32 @@ public function displayAjaxEmailHTML()
...
+     * @return array
+     */
+    protected function getSubjectMailContent($directory)
+    {
+        $subject_mail_content = [];
+        
+        if (Tools::file_exists_cache($directory . '/lang.php')) {
+            // we need to include this even if already included (no include once)
+            include $directory . '/lang.php';
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

**Comment by Progi1984** [comment]
@Amit-Kumar-Tiwari-Webkul Answered ;)

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@Progi1984 hi, I have done all the changes described by you but still, PHP test failed
Any suggestion

File: controllers/admin/AdminTranslationsController.php [hunk 10]
```diff
@@ -3308,4 +3309,29 @@ public function displayAjaxEmailHTML()
...
+    {
+        $subject_mail_content = [];
+        if (Tools::file_exists_cache($directory . '/lang.php')) {
+            // we need to include this even if already included (no include once)
+            include $directory . '/lang.php';
+            foreach ($GLOBALS[$this->translations_informations[$this->type_selected]['var']] as $key => $subject) {
+                ++$this->total_expression;
+                $subject = str_replace('\n', ' ', $subject);
+                $subject = str_replace("\\'", "\'", $subject);
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

File: controllers/admin/AdminTranslationsController.php [hunk 11]
```diff
@@ -3308,4 +3309,29 @@ public function displayAjaxEmailHTML()
...
+                $subject = str_replace('\n', ' ', $subject);
+                $subject = str_replace("\\'", "\'", $subject);
+                
+                $subject_mail_content[$key]['trad'] = htmlentities($subject, ENT_QUOTES, 'UTF-8');
+                $subject_mail_content[$key]['use_sprintf'] = $this->checkIfKeyUseSprintf($key);
+            }
+        } else {
+            $this->errors[] = sprintf($this->l('Email subject translation file not found in "%s".'), $directory);
+        }
+
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]:
```suggestion

```

File: controllers/admin/AdminTranslationsController.php [hunk 12]
```diff
@@ -3308,4 +3309,29 @@ public function displayAjaxEmailHTML()
             AdminTranslationsController::getEmailHTML($email)
         );
     }
+    /**
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php:3314]:
```suggestion

    /**
```

File: controllers/admin/AdminTranslationsController.php [hunk 13]
```diff
@@ -3308,4 +3309,28 @@ public function displayAjaxEmailHTML()
...
+                ++$this->total_expression;
+                $subject = str_replace('\n', ' ', $subject);
+                $subject = str_replace("\\'", "\'", $subject);
+                $subject_mail_content[$key]['trad'] = htmlentities($subject, ENT_QUOTES, 'UTF-8');
+                $subject_mail_content[$key]['use_sprintf'] = $this->checkIfKeyUseSprintf($key);
+            }
+        } else {
+            $this->errors[] = sprintf($this->l('Email subject translation file not found in "%s".'), $directory);
+        }
+        return $subject_mail_content;
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php:3336]:
```suggestion

        return $subject_mail_content;
```

File: controllers/admin/AdminTranslationsController.php [hunk 14]
```diff
@@ -2191,7 +2191,6 @@ public function getListModules($withInstance = false)
 
         return $modules;
     }
-
```
Comment (Progi1984) [inline controllers/admin/AdminTranslationsController.php]: Please add this empty line after the `{`

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@Progi1984 , Hi, now CSFIXER issue fixed.
Please verify it.

**Review by Progi1984 — DISMISSED** [review]

File: controllers/admin/AdminTranslationsController.php [hunk 15]
```diff
@@ -3308,4 +3310,29 @@ public function displayAjaxEmailHTML()
...
+            foreach ($GLOBALS[$this->translations_informations[$this->type_selected]['var']] as $key => $subject) {
+                ++$this->total_expression;
+                $subject = str_replace('\n', ' ', $subject);
+                $subject = str_replace("\\'", "\'", $subject);
+                $subject_mail_content[$key]['trad'] = htmlentities($subject, ENT_QUOTES, 'UTF-8');
+                $subject_mail_content[$key]['use_sprintf'] = $this->checkIfKeyUseSprintf($key);
+            }
+        } else {
+            $this->errors[] = sprintf($this->l('Email subject translation file not found in "%s".'), $directory);
+        }
```
Comment (Junebyun) [inline controllers/admin/AdminTranslationsController.php]: @Progi1984 Can you update the code with the method ‘trans’ instead of "$this->l" please?

**Comment by Junebyun** [comment]
Hello there ! I am bit lost with this PR, why is there the "waiting for wording" label? I don't get where I am need :p

File: controllers/admin/AdminTranslationsController.php (hunk 15 above)
Comment (Amit-Kumar-Tiwari-Webkul) [reply controllers/admin/AdminTranslationsController.php]: @Junebyun , hi I updated this code using trans() method.
please check

File: controllers/admin/AdminTranslationsController.php [hunk 16]
```diff
@@ -3308,4 +3310,29 @@ public function displayAjaxEmailHTML()
...
+            foreach ($GLOBALS[$this->translations_informations[$this->type_selected]['var']] as $key => $subject) {
+                ++$this->total_expression;
+                $subject = str_replace('\n', ' ', $subject);
+                $subject = str_replace("\\'", "\'", $subject);
+                $subject_mail_content[$key]['trad'] = htmlentities($subject, ENT_QUOTES, 'UTF-8');
+                $subject_mail_content[$key]['use_sprintf'] = $this->checkIfKeyUseSprintf($key);
+            }
+        } else {
+            $this->errors[] = $this->trans('Email subject translation file not found in %path%', ['%path%' => $directory], 'Admin.International.Notification');
+        }
```
Comment (Junebyun) [inline controllers/admin/AdminTranslationsController.php:3334]: @Amit-Kumar-Tiwari-Webkul Wording is fine :)

**Review by Junebyun — APPROVED** [review]

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
Hi,
Any Update regarding this PR.

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
Hi @Amit-Kumar-Tiwari-Webkul It seems that the #19288 issue that you declared has not yet been approved or reproduced.
I will try first to test if I can reproduce the issue with the informations you provided before testing your PR.

**Comment by SD1982** [comment]
LGTM issue reproduced and the PR correctly fix it ! Thanks @Amit-Kumar-Tiwari-Webkul !

**Comment by PierreRambaud** [comment]
Thanks @Amit-Kumar-Tiwari-Webkul
