### PR TITLE
Remove id_attribute parameter from product link when it is equal to 0

### LINKED ISSUE #13662: Invalid canonical URL when changing language for products without attributes
**Describe the bug**
The product URL generated by PrestaShop is invalid when you switch languages: the URL is generated with "id_product_attribute=0" which is not valid for a product without atttributes.

**To Reproduce**
1. In the BO, create a product without attributes and activate it
2. In the FO, go to the product page
3. Switch language

**Screenshots**
image

**Additional information**
PrestaShop version: 1.7.6.x
PHP version: 7.2.17

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Keeping `id_attribute = 0` cause extra useless query parameter, so we force it to null to ensure urls are always clean (and match the canonical for product without combinations)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13662
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13664)

### CODE REVIEW

File: classes/Link.php [hunk 1]
```diff
@@ -161,6 +161,10 @@ public function getProductLink(
             $params['id'] = $product->id;
         }
 
+        //Attribute equal to 0 is useless, so we set to null so that it won't be inserted in url parameters
+        if (0 === $ipa) {
```
Comment (PierreRambaud) [inline classes/Link.php]: why not checking for empty, in case someone insert an empty string?

Comment (jolelievre) [reply classes/Link.php]: Good idea!

Comment (jolelievre) [reply classes/Link.php]: @PierreRambaud Done! Thanks

**Review by PierreRambaud — APPROVED** [review]
