### PR TITLE
Fix issue with Product Customizations

### LINKED ISSUE #36286: Problems with Product Customizations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using product customizations with an additional cost, two issues arise. The additional cost for basic customizations in Prestashop cannot be managed directly, but they can be handled through a custom module by utilizing the id_module and price fields in the customized_data table, which Prestashop automatically uses to calculate the product cost.

# Issue 1: (fixed by https://github.com/PrestaShop/PrestaShop/pull/36834)
When purchasing a customized item with an extra charge, the "Total products" column on the order confirmation page is incorrect.
Attached are screenshot **01 - Order create.png** and video **01 - Order create.webm**.

# Issue 2: (fixed by https://github.com/PrestaShop/PrestaShop/pull/36287)
When purchasing the same customized item with two different customizations and two different costs, if I modify the cost of one of the two items in the order, the system updates the cost of both products.
Attached are screenshots **02 - Order edit - 01.png** and **02 - Order edit - 02.png** and video **02 - Order edit.webm**.

Attached is a module that adds 2 customizations to any item added to the cart. Adding the same item twice (with two separate cart additions), the system adds 2 different customizations with 2 different costs.
The module is just an example and with quickly developed code.

**01 - Order create.png**
01 - Order create

**01 - Order create.webm**
[01 - Order create.webm](https://github.com/PrestaShop/PrestaShop/assets/2463965/a44ac956-c171-429b-b49e-afdbd7dfd6e1)

**02 - Order edit - 01.png**
02 - Order edit - 01

**02 - Order edit - 02.png**
02 - Order edit - 02

**02 - Order edit.webm**
[02 - Order edit.webm](https://github.com/PrestaShop/PrestaShop/assets/2463965/55280fda-5fa3-49d9-8e7e-9f9e008975ef)

**Module**
[cnc_prova_configurazionearticolo.zip](https://github.com/user-attachments/files/15520943/cnc_prova_configurazionearticolo.zip)

### Expected behavior

_No response_

### Steps to reproduce

Issue 1:
1. Access the site and add a product to the cart.
2. Add a customization with an additional cost to the product.
3. Proceed to checkout and complete the order.
4. Observe the "Total products" column on the order confirmation page.

Issue 2:
1. Access the site and add the same product to the cart with two different customizations and different costs.
2. Complete the order.
3. Modify the cost of one of the customizations in the order.
4. Observe that the system updates the cost of both customizations.

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Codencode

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | When purchasing the same customized item with two different customizations and two different costs, if I modify the cost of one of the two items in the order, the system updates the cost of both products.
| Type?             | bug fix
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?    |  no
| UI Tests | https://github.com/florine2623/testing_pr/actions/runs/10141414428 ✅ 
| Fixed issue or discussion?     | Fixes #36286 (only issue 2)
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Sorry, but this is a BC break. :-(

**Comment by Codencode** [comment]
> Sorry, but this is a BC break. :-(

Hello @Hlavtox ,
You are right, I hadn't thought about that and I have never encountered such a situation before.
What do you do in these cases?
I have updated the description.
The problem occurs in very specific cases, namely product customizations that involve an additional cost, and this is only feasible in Prestashop through a custom module.
However, this doesn't change the fact that the problem exists.

**Comment by Hlavtox** [comment]
@Codencode Yep, it would be good for it to be fixed. :-)

You have two options:
- Put the $idCustomization parameter to the end of the methods and put a default value to it, so you avoid the BC break.
- You put it to develop branch, which will get (probably) released this year.

**Comment by Codencode** [comment]
> @Codencode Yep, it would be good for it to be fixed. :-)
> 
> You have two options:
> 
> * Put the $idCustomization parameter to the end of the methods and put a default value to it, so you avoid the BC break.
> * You put it to develop branch, which will get (probably) released this year.

The first solution is a great idea! I hadn't thought about it, in fact it doesn't create problems with previous versions!
I will upload the changes.
For now I have had some problems and I have to re-upload the modified files.
Thank you!

**Comment by Codencode** [comment]
@Hlavtox I made the changes as suggested.
Thank you.

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 1]
```diff
@@ -389,15 +389,16 @@ private function updateOrderDetails(Order $order, Cart $cart): void
...
     {
-        $cartProduct = array_reduce($cartProducts, function ($carry, $item) use ($productId, $productAttributeId) {
+        $cartProduct = array_reduce($cartProducts, function ($carry, $item) use ($productId, $productAttributeId, $customizationId) {
             if (null !== $carry) {
                 return $carry;
             }
 
             $productMatch = $item['id_product'] == $productId;
             $combinationMatch = $item['id_product_attribute'] == $productAttributeId;
+            $combinationMatch = $combinationMatch && $item['id_customization'] == $customizationId;
```
Comment (Hlavtox) [inline src/Adapter/Order/OrderAmountUpdater.php]: $customizationMatch

File: src/Adapter/Order/OrderDetailUpdater.php [hunk 2]
```diff
@@ -134,7 +134,8 @@ public function updateOrderDetailsForProduct(
         int $productId,
         int $combinationId,
         DecimalNumber $priceTaxExcluded,
-        DecimalNumber $priceTaxIncluded
+        DecimalNumber $priceTaxIncluded,
+        int $customizationId
```
Comment (Hlavtox) [inline src/Adapter/Order/OrderDetailUpdater.php]: Default value

File: src/Adapter/Order/OrderDetailUpdater.php [hunk 3]
```diff
@@ -314,9 +316,10 @@ private function applyUpdatesForProduct(
         DecimalNumber $priceTaxIncluded,
         int $roundType,
         int $computingPrecision,
-        Address $taxAddress
+        Address $taxAddress,
+        int $customizationId
```
Comment (Hlavtox) [inline src/Adapter/Order/OrderDetailUpdater.php]: Default value

File: src/Adapter/Order/OrderDetailUpdater.php (hunk 2 above)
Comment (Codencode) [reply src/Adapter/Order/OrderDetailUpdater.php]: You're right, it's the rush!

File: src/Adapter/Order/OrderDetailUpdater.php (hunk 3 above)
Comment (Codencode) [reply src/Adapter/Order/OrderDetailUpdater.php]: You're right, it's the rush!

File: classes/Product.php [hunk 4]
```diff
@@ -4057,7 +4057,8 @@ public static function getPriceFromOrder(
         int $combinationId,
         bool $withTaxes,
         bool $useReduction,
-        bool $withEcoTax
+        bool $withEcoTax,
+        int $ustomizationId = 0
```
Comment (PrestaEdit) [inline classes/Product.php]: Missing a "c"

File: classes/Product.php [hunk 5]
```diff
@@ -4067,6 +4068,9 @@ public static function getPriceFromOrder(
         if (Combination::isFeatureActive()) {
             $sql->where('od.`product_attribute_id` = ' . $combinationId);
         }
+        if (Customization::isFeatureActive()) {
+            $sql->where('od.`id_customization` = ' . $ustomizationId);
```
Comment (PrestaEdit) [inline classes/Product.php]: Missing the "c" and (int)

**Review by PrestaEdit — CHANGES_REQUESTED** [review]

File: classes/Product.php (hunk 5 above)
Comment (Codencode) [reply classes/Product.php]: You're right, it's the rush!
Thank you.

File: classes/Product.php (hunk 4 above)
Comment (Codencode) [reply classes/Product.php]: You're right, it's the rush!
Thank you.

File: classes/Product.php (hunk 5 above)
Comment (Codencode) [reply classes/Product.php]: I didn't insert the cast to "int" to maintain the behavior that exists in the other instructions, then there is int as the type in the parameter, so it should be enough.

**Review by Hlavtox — APPROVED** [review]
Code wise it's good!!! :-)

**Comment by Codencode** [comment]
> Code wise it's good!!! :-)

Thank you!

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Codencode ,

Thanks for the PR !

Before:

https://github.com/user-attachments/assets/3f99e3f6-59be-4251-ad9b-ac1ee33d09ac

After: 

https://github.com/user-attachments/assets/f8ed5631-3038-4c0b-87db-59cdfee7b0a3

The prices are only changed when identical products are concerned.
Tested with multiple different/identical products in the same order.

It is QA ✅ 

**Only issue number 2 is fixed** ! Do not close the related issue please.

Thanks!

**Comment by matks** [comment]
Apologies for long time to merge, thank you @Codencode

**Comment by Codencode** [comment]
> Apologies for long time to merge, thank you @Codencode

No problem, thank you @matks

File: src/Core/Cart/CartRow.php [hunk 6]
```diff
@@ -362,7 +362,8 @@ protected function getProductPrice(CartCore $cart, $rowData)
                     (int) $rowData['id_product_attribute'],
                     $computationParameters['withTaxes'],
                     true,
-                    $this->useEcotax
+                    $this->useEcotax,
+                    (int) $rowData['id_customization']
```
Comment (matthieu-rolland) [inline src/Core/Cart/CartRow.php:366]: this is a breaking change fyi

File: src/Adapter/Product/PriceCalculator.php [hunk 7]
```diff
@@ -198,15 +198,17 @@ public function getOrderPrice(
...
         return Product::getPriceFromOrder(
             $orderId,
             $productId,
             $combinationId,
             $withTaxes,
             $useReduction,
-            $withEcoTax
+            $withEcoTax,
+            $customizationId
         );
```
Comment (matthieu-rolland) [inline src/Adapter/Product/PriceCalculator.php:212]: this is a breaking change FYI

File: src/Adapter/Product/PriceCalculator.php [hunk 8]
```diff
@@ -198,15 +198,17 @@ public function getOrderPrice(
...
+        bool $withEcoTax,
+        int $customizationId = 0
     ): ?float {
         return Product::getPriceFromOrder(
             $orderId,
             $productId,
             $combinationId,
             $withTaxes,
             $useReduction,
-            $withEcoTax
```
Comment (matthieu-rolland) [inline src/Adapter/Product/PriceCalculator.php:209]: this is a breaking change fyi (removal of a function parameter)
