### PR TITLE
M/international/locations/countries delete action

### LINKED ISSUE #10604: Migrate "International > Locations > Countries" page
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate listing 
- [ ] Form todo
Capture d’écran 2023-07-06 à 15 52 23

- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] #19372 - Checkboxes for multistore
- [ ] #19324 - Specific settings dropdown for multistore

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### PR DESCRIPTION
**Pull request by margud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Delete action of Countries form 
| Type?             | refacto
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#10604](https://github.com/PrestaShop/PrestaShop/issues/10604)
| Related PRs       | This PR is checkouted from [29591](https://github.com/PrestaShop/PrestaShop/pull/29591) 
| How to test?      |  You can now delete country with new symfony controller.

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 1]
```diff
@@ -106,18 +111,73 @@ public function createAction(Request $request): Response
...
+            $countryFormHandler = $this->get(
+                'prestashop.core.form.identifiable_object.handler.country_form_handler'
+            );
+
+            $countryForm = $countryFormBuilder->getFormFor($countryId);
+            $countryForm->handleRequest($request);
+            $result = $countryFormHandler->handleFor($countryId, $countryForm);
+
+            if ($result->isSubmitted() && $result->isValid()) {
+                $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php:136]:
```suggestion
                $this->addFlash('success', $this->trans('Successful update', 'Admin.Notifications.Success'));
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 2]
```diff
@@ -106,18 +111,73 @@ public function createAction(Request $request): Response
...
+     *
+     * @param int $countryId
+     *
+     * @return RedirectResponse
+     */
+    public function deleteAction(int $countryId): RedirectResponse
+    {
+        try {
+            $this->getCommandBus()->handle(new DeleteCountryCommand($countryId));
+            $this->addFlash('success', $this->trans('Successful deletion', 'Admin.Notifications.Success'));
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php:173]:
```suggestion
            $this->addFlash('success', $this->trans('Successful deletion', 'Admin.Notifications.Success'));
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php (hunk 1 above)
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php:136]:
```suggestion
                $this->addFlash('success', $this->trans('Successful update', 'Admin.Notifications.Success'));
```

**Review by jolelievre — COMMENTED** [review]
Hi @margud

Your PR has a merge commit, maybe you merge develop branch into yours by mistake. This should be fixed, and the branch also should be rebased as it has a conflict

File: src/Adapter/Country/CommandHandler/DeleteCountryHandler.php [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+{
+    /**
+     * {@inheritdoc}
+     *
+     * @throws CountryNotFoundException
+     * @throws DeleteCountryException
+     */
+    public function handle(DeleteCountryCommand $command): void
+    {
+        $country = new Country($command->getCountryId()->getValue());
```
Comment (zuk3975) [inline src/Adapter/Country/CommandHandler/DeleteCountryHandler.php]: inject `PrestaShop\PrestaShop\Adapter\Country\Repository\CountryRepository`
add there a new method (and a new exception class if it doesnt exist) smth like this
```
public function delete(CountryId $countryId): void
{
    $this->deleteObjectModel($this->get($countryId), DeleteCountryException::class, DeleteCountryException::FAILED_DELETE);
}
```

and use it here 
```suggestion
        $country = $this->countryRepository->delete($command->getCountryId());
```

File: src/Adapter/Country/CommandHandler/DeleteCountryHandler.php [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+
+        if (0 >= $country->id) {
+            throw new CountryNotFoundException(sprintf('Unable to find country with id "%d" for deletion', $command->getCountryId()->getValue()));
+        }
+
+        if (!$country->delete()) {
+            throw new DeleteCountryException(sprintf('Cannot delete country with id "%d"', $command->getCountryId()->getValue()), DeleteCountryException::FAILED_DELETE);
+        }
```
Comment (zuk3975) [inline src/Adapter/Country/CommandHandler/DeleteCountryHandler.php]: then these can be removed

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php [hunk 5]
```diff
@@ -220,4 +222,35 @@ private function formatCountryDataIfNeeded(array $data)
...
+     *
+     * @param string $countryReference
+     */
+    public function assertCountryIsDeleted(string $countryReference): void
+    {
+        $countryId = SharedStorage::getStorage()->get($countryReference);
+
+        try {
+            $query = new GetCountryForEditing($countryId);
+            $this->getQueryBus()->handle($query);
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php]:
```suggestion
            $this->getQueryBus()->handle(new GetCountryForEditing($countryId));
```

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php [hunk 6]
```diff
@@ -220,4 +222,35 @@ private function formatCountryDataIfNeeded(array $data)
...
+
+            throw new NoExceptionAlthoughExpectedException(sprintf('Country %s exists, but it was expected to be deleted', $countryReference));
+        } catch (CountryNotFoundException $e) {
+            SharedStorage::getStorage()->clear($countryReference);
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php:252]: not sure if we need to clear the reference, but I guess it doesn't hurt :man_shrugging:

File: src/PrestaShopBundle/Resources/config/services/adapter/country.yml [hunk 7]
```diff
@@ -24,23 +24,26 @@ services:
...
+  PrestaShop\PrestaShop\Adapter\Country\CommandHandler\AddCountryHandler:
     public: true
-    class: 'PrestaShop\PrestaShop\Adapter\Country\CommandHandler\AddCountryHandler'
     autowire: true
     tags:
       - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Country\Command\AddCountryCommand' }
 
-  prestashop.adapter.country.command_handler.edit_country_handler:
+  PrestaShop\PrestaShop\Adapter\Country\CommandHandler\DeleteCountryHandler:
+    public: true
```
Comment (zuk3975) [inline src/PrestaShopBundle/Resources/config/services/adapter/country.yml]:
```suggestion
    public: false
```
unless its used somewhere by $container->get() and is too complicated too do now?

File: src/PrestaShopBundle/Resources/config/services/adapter/country.yml [hunk 8]
```diff
@@ -24,23 +24,26 @@ services:
...
+    autowire: true
+    tags:
+      - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Country\Command\DeleteCountryCommand' }
+
+  PrestaShop\PrestaShop\Adapter\Country\CommandHandler\EditCountryHandler:
     public: true
```
Comment (zuk3975) [inline src/PrestaShopBundle/Resources/config/services/adapter/country.yml]: same as above

File: src/PrestaShopBundle/Resources/config/services/adapter/country.yml [hunk 9]
```diff
@@ -24,23 +24,26 @@ services:
...
-    class: 'PrestaShop\PrestaShop\Adapter\Country\CommandHandler\EditCountryHandler'
     autowire: true
     tags:
       - { name: 'tactician.handler', command: 'PrestaShop\PrestaShop\Core\Domain\Country\Command\EditCountryCommand' }
 
-  prestashop.adapter.country.query_handler.get_country_for_editing_handler:
+  PrestaShop\PrestaShop\Adapter\Country\QueryHandler\GetCountryForEditingHandler:
     public: true
```
Comment (zuk3975) [inline src/PrestaShopBundle/Resources/config/services/adapter/country.yml]: same as above

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 10]
```diff
@@ -201,6 +235,10 @@ protected function getErrorMessages(Exception $e): array
                 'Country contains invalid field values',
                 'Admin.International.Feature'
             ),
+            DeleteCountryException::class => $this->trans(
+                'Country cannot be deleted',
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]:
```suggestion
                'Country cannot be deleted.',
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php [hunk 11]
```diff
@@ -159,6 +164,35 @@ public function editAction(int $countryId, Request $request): Response
...
+     *
+     * @param int $countryId
+     *
+     * @return RedirectResponse
+     */
+    public function deleteAction(int $countryId): RedirectResponse
+    {
+        try {
+            $this->getCommandBus()->handle(new DeleteCountryCommand($countryId));
+            $this->addFlash('success', $this->trans('Successful deletion', 'Admin.Notifications.Success'));
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]:
```suggestion
            $this->addFlash('success', $this->trans('Successful deletion.', 'Admin.Notifications.Success'));
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php (hunk 10 above)
Comment (margud) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]: there are few more error messages, should i add dot on all of them? 
"Country contains invalid field values"
"Failed to update country"
"This country does not exist"

Comment (l-delin) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController.php]: Hello, yes please. All error messages should have a final stop. :-)

**Review by zuk3975 — APPROVED** [review]

**Comment by zuk3975** [comment]
automated tests running here https://github.com/zuk3975/testing_pr/actions/runs/4511258798

File: tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php (hunk 6 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/CountryFeatureContext.php:252]: Yeah, actually it's a good idea! Maybe we should do this more in the future this would automatically keep the tests more consistent We just need to be aware that once a reference is asserted as deleted it's the last time it can be used

**Review by jolelievre — APPROVED** [review]
Thanks @margud 

All good to me since it's a partial feature and the new page is not enabled yet it won't impact the shop or the UI tests So we can merge it.
