### PR TITLE
Skip removed modules on enable theme

### LINKED ISSUE #38835: Unable to install hummingbird (any) theme if blockwishlist is not installed
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

You are unable to activate a theme if one of modules specified in `/themes/themename/config/theme.yml` is not present.

Image

### Expected behavior

User should be able to activate a theme regardless of modules installed or not.
Modules should be hooked ONLY if they are present.

### Steps to reproduce

1. Install 9.0.0
2. Uninstall blockwishlist module and delete it.
3. Upload hummingbird theme zip. [hummingbird (13).zip](https://github.com/user-attachments/files/20566222/hummingbird.13.zip)
4. Try to activate it
5. Cannot install module blockwishlist. The module blockwishlist is invalid and cannot be loaded.

### PrestaShop version(s) where the bug happened

9.0.0 beta

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.1.x
| Description?      | During the enabling of a theme some modules may have been removed, this is no longer blocking but we display a warning to explain the actions that were not performed
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See below
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/21031679856
| Fixed issue or discussion?     | Fixes #38835
| Related PRs       | ~
| Sponsor company   | ~

## How to test

Before testing these these three ways of enabling the theme you need to remove some modules from the disk:
- `ps_distributionapiclient` (or the module are re-installed via API)
- `ps_linklist`
- `blockwishlist`

### Install cli

Run this command (you probably need to adapt the DB settings to your environment:
```
php install-dev/index_cli.php  --language=en  --country=fr  --domain=localhost   --base_uri=/  --db_server=127.0.0.1 --db_user=root --db_name=prestashop --db_create=1 --firstname="John" --lastname="DOE" --name="Prestashop 91" --email=john.doe@prestashop.com --password="prestashop"
```
You should see some messages in the logs:
```
Installing database
Dropping database tables
Installing default data
Truncating database
Creating shop
Installing languages: en, fr
Populating database
Configuring shop
Installing modules on disk
Installing theme hummingbird
# These are the new extra warnings
Module blockwishlist was removed from disk, no need to disable it
Module ps_linklist was removed from disk, impossible to enable it
Module blockwishlist was removed from disk, impossible to reset it
Module ps_linklist was removed from disk, impossible to hook it
# TEnd of extra warnings
Installing fixtures
You can now access your backoffice at http://prestashop.91.localhost/admin-dev.
```

### Install from browser

Perform an install from the browser, a warning block should be displayed after the step that installs the theme, the warning stays visible when the installation succeeded.

Capture d’écran 2026-01-15 à 11 54 23

### Enable from BO

Switch to classic theme by enabling it, then switch back to Hummingbird theme by enabling it you should see a warning:

Capture d’écran 2026-01-15 à 12 05 32

### CODE REVIEW

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Install`
    - [ ] `A warning was triggered during installation`

(Note: this is an automated message, but answering it will reach a real human)

File: install-dev/theme/js/process.js [hunk 1]
```diff
@@ -4,7 +4,8 @@
  *
  * NOTICE OF LICENSE
  *
- * This source file is subject to the Open Software License (OSL 3.0)
+ * This source file is subject to the Open Softwar
+ * e License (OSL 3.0)
```
Comment (boherm) [inline install-dev/theme/js/process.js]: Weird diff here 🤔

File: src/PrestaShopBundle/Install/AbstractInstall.php [hunk 2]
```diff
@@ -75,6 +79,25 @@ public function resetErrors(): void
         $this->errors = [];
     }
 
+    public function setWarning($warnings)
```
Comment (boherm) [inline src/PrestaShopBundle/Install/AbstractInstall.php]: Return is missing here IMHO:

```suggestion
    public function setWarning($warnings): void
```

File: src/PrestaShopBundle/Install/AbstractInstall.php [hunk 3]
```diff
@@ -75,6 +79,25 @@ public function resetErrors(): void
...
+    {
+        if (!is_array($warnings)) {
+            $warnings = [$warnings];
+        }
+
+        $this->warnings = array_merge($this->warnings, $warnings);
+    }
+
+    public function getWarnings()
```
Comment (boherm) [inline src/PrestaShopBundle/Install/AbstractInstall.php]: Here too:
```suggestion
    public function getWarnings(): array
```

**Review by boherm — CHANGES_REQUESTED** [review]

**Comment by Hlavtox** [comment]
@jolelievre Awesome! That will make migrating to hummingbird much easier!

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @jolelievre, 

Thanks for your PR, i tested it and it's good for me 

https://github.com/user-attachments/assets/88c2817d-a358-4c90-95ec-72a91887b83c

Capture d’écran 2026-01-16 à 10 20 33

Thanks

**Review by SiraDIOP — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @jolelievre and @SiraDIOP 🙏🏻
