### PR TITLE
Fix FrontController names in modules hook-exceptions

### LINKED ISSUE #19226: FrontController names in modules hook-exceptions are wrong spelled with a dash
#### Describe the bug

Go to back-office, chose an arbitrary module (ps_emailsubscription for example), and try to make this module disappear from the displayFooterBefore hook in some Core FrontController which have a $php_self thant contain a dash (exeple : 'my-account').

--

#### Expected behavior

you should go to your front-office (after clearing the cache), navigate to the desired Core FrontController (http://something.com/mon-compte in my case) : The module (ps_emailsubscription) should not show up in this page.

#### Steps to Reproduce

When you go to chose an exception from the Core FrontControllers list, you have to notice that this list is generated based on Core FrontController files names :examples :- controllers/front/MyAccountController.php ==> myaccount- controllers/front/ChangeCurrencyController.php ==> changecurrencySo if you select myaccount for example, it will be stored in the DB (${prefix}_hook_module_exceptions table) as it is (myaccount). Then, in the rendering phase (precisely in Hook::excec()), the algorithm was comparing this DB value (myaccount) to current context controller php_self (my-account)(myaccount ?= my-account)==> BUG !

**Screenshots**

https://user-images.githubusercontent.com/39015823/82111516-3c190900-9746-11ea-8eee-8be7b6b7ef40.png

#### Additional information

* PrestaShop version: develop

The user opened a PR there : https://github.com/PrestaShop/PrestaShop/pull/19163

### PR DESCRIPTION
**Pull request by dali-rajab**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Previously, AdminModulesPositionsController used Dispatcher::getControllers(_PS_FRONT_CONTROLLER_DIR_) to suggest hook-exceptions for every module in every Core FrontController, however, this method returns a list of FrontControllers base names (such as myaccount, newproducts, bestsales ...), but in the other side, whenever the the Hook::exec() tries to check the exceptions, it uses the controller_name and php_self (such as my-account, new-products, best-sales ...) to compare, but never uses the base names.<br><br>This new code implements two new public static methods in the Dispatcher class, which work together to extract a list of all php_self property values of each available controller. Thus, AdminModulesPositionsController will suggest hook-exceptions based on php_self, and if php_self don't exist in a controller, then it will suggest the controller base name.
| Type?         | bug fix 
| Category?     | BO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #19226
| How to test?  | **Making the Exception** : Go to back-office, chose an arbitrary module (ps_emailsubscription for example), and try to make this module disappear from the displayFooterBefore hook in some Core FrontController which have a $php_self thant contain a dash (exeple : 'my-account').<br><br> **Testing The exception** : now you should go to your front-office (after clearing the cache), navigate to the desired Core FrontController (http://something.com/mon-compte in my case) : The module (ps_emailsubscription) should not show up in this page. image
|Explanation| When you go to chose an exception from the Core FrontControllers list, you have to notice that this list is generated based on Core FrontController files names : <br>**examples** : <br>- controllers/front/**MyAccount**Controller.php ==> myaccount<br> - controllers/front/**ChangeCurrency**Controller.php ==> changecurrency<br>So if you select **myaccount** for example, it will be stored in the DB (${prefix}_hook_module_exceptions table) as it is (**myaccount**). Then, in the rendering phase (precisely in **Hook::excec()**), the algorithm was comparing this DB value (**myaccount**) to current context controller **php_self** (**my-account**) <br>(**myaccount** ?= **my-account**)==> BUG !
|Solution| Replace the suggestion list filling method by anothoer one based on php_self properties default values.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19163)

### CODE REVIEW

File: classes/Dispatcher.php [hunk 1]
```diff
@@ -1187,4 +1187,52 @@ public static function getControllersInDirectory($dir)
...
     }
+
+    /**
+     * Get the default php_self value of a controller.
+     *
+     * @param string $controller The controller class name
+     *
+     * @return string|null
+     */
+    public static function getControllerPhpself($controller)
```
Comment (PierreRambaud) [inline classes/Dispatcher.php]:
```suggestion
    public static function getControllerPhpself(string $controller)
```

File: classes/Dispatcher.php [hunk 2]
```diff
@@ -1187,4 +1187,52 @@ public static function getControllersInDirectory($dir)
...
+    public static function getControllerPhpself(string $controller)
+    {
+        if (!class_exists($controller)) {
+            return;
+        }
+
+        $reflectionClass = new ReflectionClass($controller);
+        $controllerDefaultProperties = $reflectionClass->getDefaultProperties();
+
+        return isset($controllerDefaultProperties['php_self']) ? $controllerDefaultProperties['php_self'] : null;
```
Comment (PierreRambaud) [inline classes/Dispatcher.php]:
```suggestion
        return $controllerDefaultProperties['php_self'] ?? null;
```

File: classes/Dispatcher.php [hunk 3]
```diff
@@ -1187,4 +1187,52 @@ public static function getControllersInDirectory($dir)
...
+
+    /**
+     * Get list of all php_self property values of each available controller in the specified dir.
+     *
+     * @param string $dir Directory to scan (recursively)
+     * @param bool $base_name_otherwise Return the controller base name if no php_self is found
+     *
+     * @return array
+     */
+    public static function getControllersPhpselfList($dirs, $base_name_otherwise = true)
```
Comment (PierreRambaud) [inline classes/Dispatcher.php]:
```suggestion
    public static function getControllersPhpselfList(string $dirs, bool $base_name_otherwise = true)
```

File: classes/Dispatcher.php [hunk 4]
```diff
@@ -1187,4 +1187,52 @@ public static function getControllersInDirectory($dir)
...
+    {
+        $controllers = Dispatcher::getControllers($dirs);
+
+        $controllersPhpself = [];
+
+        foreach ($controllers as $controllerBaseName => $controllerClassName) {
+            $controllerPhpself = Dispatcher::getControllerPhpself($controllerClassName);
+
+            if ($base_name_otherwise) {
+                $controllerPhpself = $controllerPhpself ? $controllerPhpself : $controllerBaseName;
```
Comment (PierreRambaud) [inline classes/Dispatcher.php]:
```suggestion
                $controllerPhpself = $controllerPhpself ?? $controllerBaseName;
```

File: classes/Dispatcher.php [hunk 5]
```diff
@@ -1187,4 +1187,52 @@ public static function getControllersInDirectory($dir)
...
+     * Get list of all php_self property values of each available controller in the specified dir.
+     *
+     * @param string $dir Directory to scan (recursively)
+     * @param bool $base_name_otherwise Return the controller base name if no php_self is found
+     *
+     * @return array
+     */
+    public static function getControllersPhpselfList(string $dirs, bool $base_name_otherwise = true)
+    {
+        $controllers = Dispatcher::getControllers($dirs);
```
Comment (Progi1984) [inline classes/Dispatcher.php]:
```suggestion
    public static function getControllersPhpselfList(string $dir, bool $base_name_otherwise = true)
    {
        $controllers = Dispatcher::getControllers($dir);
```

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-automation Do you think your tests will be crashed with this PR ?

**Comment by khouloudbelguith** [comment]
Hi @dali-rajab,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1H0kf-mUCidcRbdEvmJxCJF63NkpxE5NA/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @dali-rajab & @khouloudbelguith
