### PR TITLE
Fix revisiting order confirmation and guest to customer conversion in FO

### LINKED ISSUE #14414: Guest account are not converted to a customer account through the FO
**Describe the bug**
Guest account are not converted to a customer account through the FO

**To Reproduce**
1. Complete an order as guest (do not fill password field during checkout)
2. Go to BO and see the customer account is guest
3. After the order, scroll down and fill the fields (firstname, lastname, email & password)
3. Go to BO and see the customer account is still guest instead of customer

**Screenshots**
https://drive.google.com/file/d/1mM1olLM1ygwI1-MnZTAwvUUFxLFxg6Iw/view?usp=sharing

**Additionnal information**
PrestaShop version: All 1.7
PHP version: N/A

### LINKED ISSUE #20388: Re-visiting order confirmation page is not working
#### Description

1. Make an order as a guest.
2. Refresh page.
3. You get redirected to login.

#### Expected behavior

I should be able to see the order confirmation when reloading the page.

#### Cause

In OrderConfirmationController, on line 65, there is a condition:

```
if (!Validate::isLoadedObject($order) || $order->id_customer != $this->context->customer->id || $this->secure_key != $order->secure_key) {
    Tools::redirect($redirectLink);
}
```

If ID of order's customer is not the same as the ID of customer in context, redirect to login page.
My order's customer ID is 1775, but context->customer->id is empty, because it gets cleared after order.

#### PR available
https://github.com/PrestaShop/PrestaShop/pull/25395

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

### LINKED ISSUE #23230: FO - OrderConfirmation for free order doesn't display, display login/history page
#### Describe the bug

When I create a free order, after the payment, I expect to show also the confirmation order page and not redirect to history controller.

#### Steps to Reproduce

1. Create a product
2. Add a Cart Rule or a Specific Price to a product to make it free
3. Add the product to cart
4. Complete the order
5. See the login page or history order and not the confirmation order

#### Additional information
In other order that are not free the confirmation page is show, i see, **but is only a supposition**, that when order is free ps will call the controller with only the param 'free-order=1' and doesn't go to initContent function because the param are null or 0.

* PrestaShop version: 1.7.5.2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | yes
| Fixed ticket?     | Fixes #14414 and #20388 and #23230
| How to test?      | See below
| Possible impacts? | -

## Description
- I rewrote and improved order confirmation controller inner workings. This allowed to fix several things, made things cleaner and more bulletproof.
- ✔️ When you refreshed order confirmation page, you got redirected to login screen or order history. This is now working 100% properly.
- ✔️ When you wanted to convert your account to customer, you had to enter many things and it didn't work at all.
- ✔️ When you enabled catalog mode after making an order, you could no longer access the confirmation screen. This is now working.

## Technical details
- Email on confirmation screen is now taken from the order itself, not from the context. So you can checkout an order in your browser history you made from a different account, and still see the correct information.
- There is a check removed on id_customer, that prevented the revisiting the page, because guests are "logged out" from cookie on first confirm visit. This check is not needed. Mechanism that prevents customer to see other customer's order is the secure_key.
- The PR is prepared for another PR, that will fix ordering as a guest with customer existing - https://github.com/PrestaShop/PrestaShop/pull/25353.
- I removed check on Catalog mode. If you enable catalog mode after customers have been ordering, why they can't view their order confirmation?

## Guest to customer conversion
- The box is shown only to guests and only if a customer account with the same email does not exist.
- They now only need to enter the password (like on guest tracking page), not the name and email again.
- There is a nice error/notification for all cases - empty password, short password, on page refresh, if they already converted him in BO.
- I unified both forms on confirmation page and guest tracking page to a single TPL.
- I added a check for empty password and already converted customer also to guest tracking controller.
- I renamed a variable I added in my previous PR, so it's unified.
Výstřižek

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25395)

### CODE REVIEW

File: controllers/front/OrderConfirmationController.php [hunk 1]
```diff
@@ -45,31 +48,92 @@ public function init()
...
+        // If are coming to this page to finish free order, we need to run additional logic
         if (true === (bool) Tools::getValue('free_order')) {
             $this->checkFreeOrder();
         }
 
-        $this->id_cart = (int) (Tools::getValue('id_cart', 0));
-
-        $redirectLink = 'index.php?controller=history';
-
+        // We get the required data from URL
```
Comment (kpodemski) [inline controllers/front/OrderConfirmationController.php]: > I am pretty rich on coments, if it's not a good practice, I will reduce it, but this way it can be read like a book.

Actually, it should be a code that you read like a book! :) For example in this place, it's obvious that we're getting data from an URL, same for checking password length, etc.

File: controllers/front/OrderConfirmationController.php [hunk 2]
```diff
@@ -79,31 +143,26 @@ public function init()
      */
     public function initContent()
     {
-        if (Configuration::isCatalogMode()) {
```
Comment (kpodemski) [inline controllers/front/OrderConfirmationController.php:93]: I think this check was on point?

File: themes/classic/templates/checkout/order-confirmation.tpl [hunk 3]
```diff
@@ -93,11 +93,31 @@
...
         <div class="card-block">
-          <h4 class="h4">{l s='Save time on your next order, sign up now' d='Shop.Theme.Checkout'}</h4>
-          {render file='customer/_partials/customer-form.tpl' ui=$register_form}
+          <h4 class="h4">{l s='Save time on your next order, sign up now and enjoy:' d='Shop.Theme.Checkout'}</h4>
+          <ul>
+            <li> -{l s='Personalized and secure access' d='Shop.Theme.Customeraccount'}</li>
+            <li> -{l s='Fast and easy checkout' d='Shop.Theme.Customeraccount'}</li>
+            <li> -{l s='Easier merchandise return' d='Shop.Theme.Customeraccount'}</li>
+          </ul>
+          <form method="post">
```
Comment (kpodemski) [inline themes/classic/templates/checkout/order-confirmation.tpl]: I'm not in favor of hardcoding theme forms, it's really good for developer to handle form markup in one place instead of looking for forms all over the place. Consider building this form in the same way like we build login form etc.

File: controllers/front/OrderConfirmationController.php (hunk 2 above)
Comment (Hlavtox) [reply controllers/front/OrderConfirmationController.php:93]: I removed this, because imagine a situation - You have catalog mode disabled and ordering enabled. Somebody makes an order, you enable catalog mode 5 minutes after that. Why would he not be able to re-check his order confirm? :-)

File: themes/classic/templates/checkout/order-confirmation.tpl (hunk 3 above)
Comment (Hlavtox) [reply themes/classic/templates/checkout/order-confirmation.tpl]: @kpodemski It's nearly the same hardcoded form as on guest tracking. I think we could merge it into one TPL and reuse it, at least.

**Comment by Progi1984** [comment]
The linked issue #20388 wait for @PrestaShop/product-team answer :)

File: controllers/front/OrderConfirmationController.php (hunk 1 above)
Comment (matks) [reply controllers/front/OrderConfirmationController.php]: Whether comments are good or not has been a discussion for dozen of years among developers.

Famous quote by Robert C Martin (author of Clean Code):
> A comment is a failure to express yourself in code. If you fail, then write a comment; but try not to fail.

But plenty of people, including others renowned authors have disagreed with him.

I don't have the Ultimate Truth but I think @kpodemski opinion is a good one: comments should bring some informations to the reader that he could not find easily from the code. If you can grasp an information either from the code (getting data from an URL) or from a comment, the comment is not useful. Look at @jolelievre comments in PR https://github.com/PrestaShop/PrestaShop/pull/24991/ they give such information.

However, when you have to choose whether to add a comment or not to add, I think it's always good to add it :) it's better to have a code that is uselessly too obvious rather than an obscure code 😄 

That being said... I'm quite sure some of the other maintainers will disagree with me :trollface:

File: controllers/front/OrderConfirmationController.php [hunk 4]
```diff
@@ -45,31 +48,92 @@ public function init()
...
-
+        // We get the required data from URL
         $this->id_module = (int) (Tools::getValue('id_module', 0));
-        $this->id_order = Order::getIdByCartId((int) ($this->id_cart));
+        $this->id_order = (int) (Tools::getValue('id_order', 0));
         $this->secure_key = Tools::getValue('key', false);
-        $order = new Order((int) ($this->id_order));
+        $this->order = new Order((int) ($this->id_order));
 
+        // We run all the required checks and if something is smelly, we redirect him to order history
```
Comment (matks) [inline controllers/front/OrderConfirmationController.php]: One way to avoid having to write a comment is to use variable names
For example
```
        // We run all the required checks and if something is smelly, we redirect him to order history
```
can transform into
```
$somethingIsSmelly = (!Validate::isLoadedObject($this->order) || $this->secure_key != $this->order->secure_key);
if ($somethingIsSmelly)
```

File: controllers/front/OrderConfirmationController.php [hunk 5]
```diff
@@ -45,31 +48,92 @@ public function init()
...
-
-        $redirectLink = 'index.php?controller=history';
-
+        // We get the required data from URL
         $this->id_module = (int) (Tools::getValue('id_module', 0));
-        $this->id_order = Order::getIdByCartId((int) ($this->id_cart));
+        $this->id_order = (int) (Tools::getValue('id_order', 0));
         $this->secure_key = Tools::getValue('key', false);
-        $order = new Order((int) ($this->id_order));
+        $this->order = new Order((int) ($this->id_order));
```
Comment (matks) [inline controllers/front/OrderConfirmationController.php:69]: I think this change is important. `$order` ⏩  `$this->order` can you explain it ?

File: controllers/front/OrderConfirmationController.php [hunk 6]
```diff
@@ -45,31 +48,92 @@ public function init()
...
+
+            // If no password was entered
+            if (empty($password)) {
+                $this->errors[] = $this->trans(
+                    'To convert your account, you must enter a password.',
+                    [],
+                    'Shop.Forms.Help'
+                );
+
+            // If the password is short
```
Comment (matks) [inline controllers/front/OrderConfirmationController.php]: These comments are not needed, `(strlen($password) < Validate::PASSWORD_LENGTH)` is exactly "verify password is long enough"

File: controllers/front/OrderConfirmationController.php (hunk 5 above)
Comment (Hlavtox) [reply controllers/front/OrderConfirmationController.php:69]: @matks It's because previously, the Order was created twice for nothing - `$order = new Order(Order::getIdByCartId((int) ($this->id_cart)));`. Now I initialize the object only once in init() and save it to the attribute, so we can use it in all other methods.

File: controllers/front/OrderConfirmationController.php (hunk 1 above)
Comment (eternoendless) [reply controllers/front/OrderConfirmationController.php]: I agree that it's preferable to risk having redundant comments rather than lose valuable contextual information. Don't make me reverse engineer code!

File: controllers/front/OrderConfirmationController.php [hunk 7]
```diff
@@ -23,18 +23,21 @@
...
     public $ssl = true;
     public $php_self = 'order-confirmation';
-    public $id_cart;
     public $id_module;
     public $id_order;
-    public $reference;
     public $secure_key;
-    public $order_presenter;
+    public $order;
+    public $customer;
```
Comment (eternoendless) [inline controllers/front/OrderConfirmationController.php]: Consider making these protected

File: controllers/front/OrderConfirmationController.php (hunk 4 above)
Comment (eternoendless) [reply controllers/front/OrderConfirmationController.php]: It's usually better to have dedicated method

```php
if (!$this->verifyOrder($this->order, $this->secure_key)) {
    // error
}
```

**Comment by Hlavtox** [comment]
@matks @eternoendless @kpodemski 
- Ensured compatibility by preserving `id_cart` and `reference` attributes, if anyone is overriding this. New users can use `order` attribute.
- Cleaned unneeded comments and made the two new attributes protected.
- ~~Removed some old historic code `slowvalidation`. It seems it was only used like in 2010 in PayPal module. No trace of it in last years anywhere.~~

File: controllers/front/OrderConfirmationController.php [hunk 8]
```diff
@@ -45,31 +48,86 @@ public function init()
...
+                );
+            // Attempt to convert the customer
+            } elseif ($this->customer->transformToCustomer($this->context->language->id, $password)) {
+                $this->success[] = $this->trans(
+                    'Your guest account has been successfully transformed into a customer account. You can now log in as a registered shopper.',
+                    [],
+                    'Shop.Notifications.Success'
+                );
+            } else {
+                $this->success[] = $this->trans(
```
Comment (Matt75) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
                $this->errors[] = $this->trans(
```

File: controllers/front/OrderConfirmationController.php [hunk 9]
```diff
@@ -45,31 +48,86 @@ public function init()
...
+        $this->reference = (string) $this->order->reference;
+
+        // The confirmation link must contain a unique order secure key matching the key saved in database,
+        // this prevents user to view other customer's order confirmations
         if (!$this->id_order || !$this->id_module || !$this->secure_key || empty($this->secure_key)) {
             Tools::redirect($redirectLink . (Tools::isSubmit('slowvalidation') ? '&slowvalidation' : ''));
         }
-        $this->reference = $order->reference;
-        if (!Validate::isLoadedObject($order) || $order->id_customer != $this->context->customer->id || $this->secure_key != $order->secure_key) {
+        $redirectLink = 'index.php?controller=history';
```
Comment (Matt75) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
        $redirectLink = $this->context->link->getPageLink('history', $this->ssl);
```
Avoid double redirection in case of Url Rewrite enabled

**Comment by Hlavtox** [comment]
@Matt75 Thank you man, all applied! 🚀

**Comment by Matt75** [comment]
There is a problem with using id_order instead of id_cart because after payment a Cart can be split into one or more orders.

Multishipping feature has been partially removed in 1.6.1 and moreover in 1.7.0 but code is still there in PaymentModule class.

And some conditions can currently split a Cart into multiple orders : https://github.com/PrestaShop/prestashop-specs/issues/111

That's why we use id_cart instead of id_order because before 1.7.0 we display all orders created with this Cart.

1.7.0 introduced a regression because only one order is now displayed on confirmation page : https://github.com/PrestaShop/PrestaShop/issues/9594

It's very confusing for a customer to pay for 5 products for example and confirmation page show only 3 products with a different total price... its a real problem

**Comment by ldeprestashop** [comment]
We are looking (not date fix, we must prioritize many features)  for multishipping for future version that's why I agree with @Matt75 last comment.

**Comment by Hlavtox** [comment]
@Matt75 @ldeprestashop 

Hi guys, I didn't know this was possible. I think many modules are not even ready for this, but we can for sure fix it!

However, I checked 1.6.0.X code and I couldn't find anything that would display two orders on confirmation screen, are you sure it was there?

1) Can you provide me with how I can reproduce this multishipping?
2) Do you want me to do it in this PR or we can merge this (I will revert to using id_cart) and do it in another PR?
3) Do you have some specs for this? I would change order attribute to orders -> do what I want with them -> In the template, if there are two orders, I will display message like “We split your cart into multiple orders (ABCDFG and HIJKLMN), so we can work on them independently.” and two product tables.

**Comment by Matt75** [comment]
@Hlavtox

Test scenarios in https://github.com/PrestaShop/prestashop-specs/issues/111 with older versions than PrestaShop 1.7 and you should see all related orders created from cart paid.

1. Multishipping can only be reproduced with PrestaShop 1.5 and carrier modules compliant was rare but others cases bellow can create multiple orders.

For others questions, I let Product Team answer

**Comment by Hlavtox** [comment]
@Matt75 Sorry man, but I don't want to do it in this PR. I will keep the way of getting order from cart id, but let's extend it in another PR. It's too complicated and it would be a mess.

**Comment by Matt75** [comment]
> @Matt75 Sorry man, but I don't want to do it in this PR. I will keep the way of getting order from cart id, but let's extend it in another PR. It's too complicated and it would be a mess.

No worries, my goal was just to explain everyone why id_cart is used and why use id_order instead will cause more problem with current situation.

Moreover we need a decision to choose witch behavior is good

**Comment by marionf** [comment]
Hello @Hlavtox 

Thank you for this really nice PR ! 

I am ok with all the behaviors you described in the PR ✔️  

However, while testing it I ran into the following error when I tried to sign in after the guest account was transformed into a customer through the FO:
Capture d’écran 2021-08-18 à 11 25 29

I also found another issue:
1) I made an order as a guest
2) I transformed the guest into a customer account through the back-office
3) In FO, on the order-confirmation page (I did not refresh it), I tried to enter a password and click on "Create account"
4) It says "Your guest account has been already transformed into a customer account. You can log in as a registered shopper.
"
5) I tried to sign in to my customer account but the password is not working.

I think we should display an error message if the guest was already transformed into a customer account while clicking on "Create account".

Could you fix these issues ?

**Comment by Hlavtox** [comment]
@marionf Hi Marion, the first bug is fixed, I put a variable onto wrong line. Ooops :-)

Regarding the second situation - I changed the message to error and improved the wording. So he knows that the conversion with his password did not went through. It's easy solution not requiring other mods and logic. I think it should be clear now.

Výstřižek

_______

@Matt75 Reverted the logic to getting the data by id_cart so it's prepared for order splitting. 👍

File: controllers/front/OrderConfirmationController.php [hunk 10]
```diff
@@ -45,31 +48,94 @@ public function init()
...
+    public function postProcess()
+    {
+        if (Tools::isSubmit('submitTransformGuestToCustomer')) {
+            // Only variable we need is the password
+            // There is no need to check other variables, because hacker would be kicked out in init(), if he tried to convert another customer
+            $password = Tools::getValue('password');
+
+            if (empty($password)) {
+                $this->errors[] = $this->trans(
+                    'To convert your account, you must enter a password.',
```
Comment (Julievrz) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
                    'Enter a password to transform your guest account into a customer account.',
```

File: controllers/front/OrderConfirmationController.php [hunk 11]
```diff
@@ -45,31 +48,94 @@ public function init()
...
+                    'Your password must be at least %min% characters long.',
+                    ['%min%' => Validate::PASSWORD_LENGTH],
+                    'Shop.Forms.Help'
+                );
+            // Prevent error
+            // A) either on page refresh
+            // B) if we already transformed him in other window or through backoffice
+            } elseif ($this->customer->is_guest == 0) {
+                $this->errors[] = $this->trans(
+                    'We could not transform your guest account, it has already been transformed into a customer account. You can log in as a registered shopper.',
```
Comment (Julievrz) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
                    'A customer account has already been created from this guest account. Please sign in.',
```
If I understand well, this is what you mean here? ☺️

File: themes/classic/templates/checkout/order-confirmation.tpl [hunk 12]
```diff
@@ -93,11 +93,31 @@
   {/block}
 
   {block name='customer_registration_form'}
-    {if $customer.is_guest}
+    {if $order_customer.is_guest && !$registered_customer_exists}
       <div id="registration-form" class="card">
         <div class="card-block">
-          <h4 class="h4">{l s='Save time on your next order, sign up now' d='Shop.Theme.Checkout'}</h4>
-          {render file='customer/_partials/customer-form.tpl' ui=$register_form}
+          <h4 class="h4">{l s='Save time on your next order, sign up now and enjoy:' d='Shop.Theme.Checkout'}</h4>
```
Comment (Julievrz) [inline themes/classic/templates/checkout/order-confirmation.tpl]:
```suggestion
          <h4 class="h4">{l s='Save time on your next order, sign up now' d='Shop.Theme.Checkout'}</h4>
```
"and enjoy:" followed by bullet points is not really easy to translate.

**Comment by Hlavtox** [comment]
@Julievrz Wording updated ;-)

**Comment by Hlavtox** [comment]
@matks @eternoendless Hi guys, I unified the conversions into one file and improved error messages on guest tracking. :-)

File: controllers/front/OrderConfirmationController.php [hunk 13]
```diff
@@ -23,18 +23,21 @@
...
     public $id_module;
     public $id_order;
-    public $reference;
     public $secure_key;
-    public $order_presenter;
+    protected $order;
+    protected $customer;
+    public $reference; // Deprecated
+    public $id_cart; // Deprecated
+    public $order_presenter; // Deprecated
```
Comment (Progi1984) [inline controllers/front/OrderConfirmationController.php]: Could you add PHPDoc for these attributes ?

File: controllers/front/GuestTrackingController.php [hunk 14]
```diff
@@ -129,7 +145,7 @@ public function initContent()
         $this->context->smarty->assign([
             'order' => $presented_order,
             'guest_email' => Tools::getValue('email'),
-            'is_customer' => Customer::customerExists(Tools::getValue('email'), false, true),
```
Comment (kpodemski) [inline controllers/front/GuestTrackingController.php:132]: To avoid a big BC Break I'd leave it as a deprecated variable

File: controllers/front/OrderConfirmationController.php [hunk 15]
```diff
@@ -79,31 +145,26 @@ public function init()
...
-            Tools::redirect('index.php');
-        }
-
-        $order = new Order(Order::getIdByCartId((int) ($this->id_cart)));
-        $presentedOrder = $this->order_presenter->present($order);
-        $register_form = $this
-            ->makeCustomerForm()
-            ->setGuestAllowed(false)
-            ->fillWith(Tools::getAllValues());
+        // Initialize presenters
```
Comment (kpodemski) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
```

File: controllers/front/OrderConfirmationController.php [hunk 16]
```diff
@@ -79,31 +145,26 @@ public function init()
...
+        $order_presenter = new OrderPresenter();
+        $object_presenter = new ObjectPresenter();
 
         parent::initContent();
 
+        // Assign data to output and set template
```
Comment (kpodemski) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
```

File: themes/classic/templates/checkout/order-confirmation.tpl [hunk 17]
```diff
@@ -92,16 +92,15 @@
...
-  {block name='customer_registration_form'}
-    {if $customer.is_guest}
-      <div id="registration-form" class="card">
+  {if !$registered_customer_exists}
+    {block name='conversion_form'}
+      <div class="card">
         <div class="card-block">
-          <h4 class="h4">{l s='Save time on your next order, sign up now' d='Shop.Theme.Checkout'}</h4>
-          {render file='customer/_partials/customer-form.tpl' ui=$register_form}
+          {include file='customer/_partials/conversion-form.tpl'}
```
Comment (kpodemski) [inline themes/classic/templates/checkout/order-confirmation.tpl]: Naming is a bit awkward for me, as conversion has a completely different meaning most of the time. What do you think about `account-transformation-form.tpl`?

File: themes/classic/templates/customer/_partials/conversion-form.tpl [hunk 18]
```diff
@@ -0,0 +1,46 @@
...
+ * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
+ *}
+{block name='conversion_form'}
+    <h4 class="h4">{l s='Save time on your next order, sign up now' d='Shop.Theme.Checkout'}</h4>
+    <ul>
+      <li> - {l s='Personalized and secure access' d='Shop.Theme.Customeraccount'}</li>
+      <li> - {l s='Fast and easy checkout' d='Shop.Theme.Customeraccount'}</li>
+      <li> - {l s='Easier merchandise return' d='Shop.Theme.Customeraccount'}</li>
+    </ul>
+    <form method="post">
```
Comment (kpodemski) [inline themes/classic/templates/customer/_partials/conversion-form.tpl]: you could add a unique id based on the template name

File: controllers/front/OrderConfirmationController.php [hunk 19]
```diff
@@ -45,31 +48,94 @@ public function init()
     {
         parent::init();
 
+        // If are coming to this page to finish free order, we need to run additional logic
```
Comment (Progi1984) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
        // If we are coming to this page to finish free order, we need to run additional logic
```

File: controllers/front/OrderConfirmationController.php [hunk 20]
```diff
@@ -45,31 +48,94 @@ public function init()
...
         if (true === (bool) Tools::getValue('free_order')) {
             $this->checkFreeOrder();
         }
 
+        /*
+         * Because of order splitting scenarios, we must get the data by id_cart parameter (not id_order),
+         * so we can display all orders made fron this cart.
```
Comment (Progi1984) [inline controllers/front/OrderConfirmationController.php]:
```suggestion
         * so we can display all orders made from this cart.
```

File: themes/classic/templates/customer/_partials/conversion-form.tpl [hunk 21]
```diff
@@ -0,0 +1,46 @@
...
+      <div>
```
Comment (Progi1984) [inline themes/classic/templates/customer/_partials/conversion-form.tpl]: Can we remove this `div` ?

**Review by Progi1984 — COMMENTED** [review]
@Hlavtox Thank you for your contribution. I have brought some comments to your PR.

File: themes/classic/templates/customer/_partials/conversion-form.tpl (hunk 18 above)
Comment (Hlavtox) [reply themes/classic/templates/customer/_partials/conversion-form.tpl]: @kpodemski How do you want me to do it?

**Comment by Hlavtox** [comment]
@Progi1984 @kpodemski Thanks for checking guys, all suggestions applied. ;-)

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by Hlavtox** [comment]
Ready for QA?

**Comment by kpodemski** [comment]
@Hlavtox we need wording approval from @Julievrz and then ready for QA 👍🏻

File: controllers/front/GuestTrackingController.php [hunk 22]
```diff
@@ -81,12 +81,28 @@ public function postProcess()
...
                     'Shop.Forms.Help'
                 );
+            // Prevent error
+            // A) either on page refresh
+            // B) if we already transformed him in other window or through backoffice
+            } elseif ($customer->is_guest == 0) {
+                $this->errors[] = $this->trans(
+                    'A customer account has already been created from this guest account. Please sign in.',
+                    [],
+                    'Shop.Notifications.Success'
```
Comment (Julievrz) [inline controllers/front/GuestTrackingController.php]:
```suggestion
                    'Shop.Notifications.Error'
```

Sorry for the delay, I was out of the office last week. I just missed this domain. It's actually an error, not a success. :-)

Comment (Hlavtox) [reply controllers/front/GuestTrackingController.php]: @Julievrz No worries. Good catch, completely forgot to check it :). I also fixed it in confirmation controller. 👍

**Comment by Hlavtox** [comment]
Wording fixed, commits merged into 1 👍

**Review by kpodemski — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by Progi1984** [comment]
@Hlavtox You have some conflicting file. Could you rebase your PR, please ?

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thanks for your PR!
LGTM, QA :heavy_check_mark: 
See the attached screen record below:
https://watch.screencastify.com/v/H56ACdIEzeBCNXM1g3EA

Thanks!

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @Hlavtox

**Comment by Hlavtox** [comment]
@matks Thanks Mathieu! :-)
