### PR TITLE
PHP sessions are not correctly configured

### LINKED ISSUE #22711: Problem with sessions cookies for SameSite issue
#### Describe the bug

As you know, the issue of SameSite in PR #20601 has been resolved. But my concern is that session cookies do not behave in the same way as cookies. PrestaShop uses very few sessions in notifications, admin, and during installation. But many modules may use sessions, especially payment modules. They have set session cookie parameters themselves, otherwise, they will probably have a payment transaction error. My suggestion is to do this next to the cookie params.

I made this PR #22709 for this issue.

#### Expected behavior

I think we expected the behavior of session cookies exactly like normal cookies.

#### Steps to Reproduce

1. remove all cookies from inspect element (Application Tab on chrome)
2. Refresh the page
3. Compare cookie params with sessions.

**Screenshots**

In this screenshot, the first part is related to the current behavior of PrestaShop. The second part of the image is related to the behavior we expect to have.

I made this PR #22709 for this issue.

Video: https://drive.google.com/file/d/1-b9PK1gBZF3MHyQGhFDAUN_vh25pntzq/view

ps-sessions

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Since we add the SameSite attribute in cookies, we have to correctly settle it on PHP sessions depending on the Database configuration in order to allow modules to use $_SESSION when they want
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22711
| How to test?      | Make sure the PHP Session cookie have the same values for SameSite and secure than the PrestaShop Cookie.
| Possible impacts? | Must be tested with & without SSL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22746)

### CODE REVIEW

**Comment by AliShareei** [comment]
Hi @PierreRambaud,

Today I did a technical review for one store that was using PrestaShop 1.7.6.9 and PHP v7.3.25. 
(with CDN -or- Cloud DNS) / LiteSpeed V7.8

I noticed that the `session_set_cookie_params()` method did not work for him at all.
But the old way, I mean `header()` method which is used in old PR #22709 Work well.

What do you think? is there any server restriction for this? 
I found `php_admin_value` which may be related to this.

Edit: There were no restrictions, the problem was with my code, which I explained in later posts.

**Comment by Arman-Hosseini** [comment]
> Hi @PierreRambaud,
> 
> Today I did a technical review for one store that was using PrestaShop 1.7.6.9 and PHP v7.3.25. (with CDN -or- Cloud DNS)
> I noticed that the `session_set_cookie_params()` method did not work for him at all.
> But the old way, I mean `header()` method which is used in old PR #22709 Work well.
> What do you think? is there any server restriction for this?

@AliShareei This PR is not ready for review and use because it is **WIP** and that means work is in progress.
Please wait for the author to complete the work.

**Comment by AliShareei** [comment]
Hi, @Arman-Hosseini Aziz.

Actually, I don't review or use this PR. I fix this problem in our free payment module for months.
so I Just review and fix some small problems with this Issue for our usage.
here I'm trying to share some information that may I think would be helpful for this PR.

another problem I found exactly on this shop I mean PrestaShop 1.7.6.9 and PHP 7.3.25.
is this error: ` (1/1) RuntimeException Failed to start the session: already started by PHP.`

in our code, we start the session carefully. with checking like this `if (session_status() === PHP_SESSION_NONE)`
but in the admin URL, I mean `http://shop.com/admin[x]/` (without extra query) When we first enter, we got this error.

this problem caused by the Symfony package on this path.
`vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage.php`

which code is 

>         if (\PHP_SESSION_ACTIVE === session_status()) {
>             throw new \RuntimeException('Failed to start the session: already started by PHP.');
>         }

I did not make much effort to solve this problem and only exclude the admin for this code because it was not needed for our current use.

I'm not sure if this error exists in this PR as well, I'll just leave this note here for further review.

session-already-start-error

**Comment by AliShareei** [comment]
About `session_set_cookie_params()` I found the problem.
this method must be called on every single page and my code is not running on every request. So that's my fault.

File: classes/Context.php [hunk 1]
```diff
@@ -52,6 +53,9 @@ class ContextCore
     /** @var Cookie */
     public $cookie;
 
+    /** @var SessionInterface */
```
Comment (Progi1984) [inline classes/Context.php]:
```suggestion
    /** @var SessionInterface|null */
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
It would be awesome to cover this topic in documentation (how PHP sessions were handled for PS < 1.7.8 and the change introduced in 1.7.8)

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

It is ok :heavy_check_mark: 

Install in **PHP7.1** with SSL enabled => ok
I checked the PS_COOKIE_SAMESITE have the `Lax` value
**FO**
php7 1_fo_lax
I changed to to `None` value => ok
**FO**
php7 1_fo_non
**BO**
php7 1_bo_non

I Disabled SSL => OK

Install in **PHP7.3** without SSL => OK
**BO**
php7 3_bo_no_ssl
**FO**
image

I enabled SSL => OK
**BO**
image
**FO**
image

Thank you!

**Comment by Progi1984** [comment]
Thanks @PierreRambaud & @khouloudbelguith
