### PR TITLE
Fix combination modal changes detection

### LINKED ISSUE #33965: Product V2 [Combination Tab] - Cannot click on next or previous combination
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In combination tab > edit combination modal the save button is enabled. 
When we click on next combination button, a modal is displayed to discard or cancel changes.

Capture d’écran de 2023-09-18 16-19-34

### Expected behavior

In combination tab > edit combination modal, the save button should be enabled only when we edit the combination.

-> Save button is disabled
Capture d’écran de 2023-09-18 16-13-55

### Steps to reproduce

1- Create product with combination
2- Create combinations
3- Click on edit combination
4- See the error => 
    - Save button is not disabled
    - we cannot go to next or previous page

#### Acceptance Test
Unskip this test : 
* https://github.com/PrestaShop/PrestaShop/blob/dd87f6c3e91c52203869d1354468ad9f4c05cc8f/tests/UI/campaigns/productV2/functional/11_combinationTab.ts#L201-L218

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | The next and previous button in the combination edition modal had a strange behaviour where even if you did not modify any field they would force you to save the current combination as if you changed something. This was due to the fact that some hidden field had eventListener on them that were triggered by an automatic calculation in the final price of the combination. By removing the listeners on the hidden field it fixes the problem.
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | See step to reproduce in #33965 
| UI Tests          | https://github.com/nesrineabdmouleh/testing_pr/actions/runs/6627419084 
| Fixed issue or discussion?     | Fixes #33965
| Sponsor company   | PrestaShop SA

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue [hunk 1]
```diff
@@ -281,17 +281,22 @@
         );
 
         iframeInputs.forEach((input: Element) => {
+          // @ts-ignore
```
Comment (mflasquin) [inline admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue:284]: Why do you need a ts-ignore ?

Comment (raqso) [reply admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue:284]: I think it's because there is already too wide type here:  https://github.com/tleon/PrestaShop/blob/Issue-33965-fix-next-previous-combinations/admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue#L279

This should be changed from 
```
        const iframeInputs = <NodeListOf<Element>>iframeBody.querySelectorAll(
```
to
```
        const iframeInputs = <NodeListOf<HTMLInputElement>>iframeBody.querySelectorAll(
```

Then `// @ts-ignore` and `Element` in line 283 can be removed.
Zrzut ekranu 2023-10-22 o 22 29 09

Then types will not lie and everything should be working without an error.
Zrzut ekranu 2023-10-22 o 22 29 22

Hope it makes sense.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue:284]: We can't force type with HTMLInputElement because the selectors doesn't only catch inputs, and for some reason checking `instanceof HTMLInputElement` was accepted by TypeScript but it didn't work when the code was executed

**Comment by jolelievre** [comment]
Running other campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6624171615

File: admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue (hunk 1 above)
Comment (raqso) [reply admin-dev/themes/new-theme/js/pages/product/combination/combination-modal/CombinationModal.vue:284]: Yes, you're right. I've checked the selector(`'form[name="combination_form"] input, form[name="combination_form"] textarea, form[name="combination_form"] select'` so HTML input or HTML select) and it could be like this:

Zrzut ekranu 2023-10-24 o 13 53 45

**Comment by nesrineabdmouleh** [comment]
UI tests => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/6627419084 :green_circle:

**Review by mflasquin — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @tleon 

Thank you for your PR, I tested it and it seems to works as you can see : 

[Untitled_ Oct 26, 2023 11_58 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/46229c46-200e-4ae1-95d9-15e26368f2fe)

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by nicosomb** [comment]
Thank you @tleon !
