### PR TITLE
Validate password only if not empty, fixing Guest Checkout

### LINKED ISSUE #20517: FO - Cannot create an order as a guest - "Password must be between 5 and 72 characters long" but it is optional
#### Describe the bug

In the FO, when we try to order as a guest, the **Optional field** password cannot be empty

#### Steps to Reproduce

1. Go to FO => Add some products to the cart
2. Proceed to checkout
3. Create an account without a password (as a guest)
4. Click on continue
5. See error

**Screenshots**

image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | PR https://github.com/PrestaShop/PrestaShop/pull/19534/ introduced a better validation of the Customer Form in Checkout, but it removed the ability to have guest checkout (= no password). So I fix it by triggering the validation only if not empty.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20517
| How to test?  | Please see ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20941)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/form/CustomerForm.php [hunk 1]
```diff
@@ -140,7 +140,8 @@ public function validate()
         }
 
         $passwordField = $this->getField('password');
-        if (Validate::isPasswd($passwordField->getValue()) === false) {
+        if (!empty($passwordField->getValue())
+            && Validate::isPasswd($passwordField->getValue()) === false) {
```
Comment (atomiix) [inline classes/form/CustomerForm.php]:
```suggestion
        if ((!empty($passwordField->getValue()) || $this->passwordRequired)
            && Validate::isPasswd($passwordField->getValue()) === false) {
```

Comment (matks) [reply classes/form/CustomerForm.php]: Nice catch ! I did not know about this variable

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matks,

I tried with this PR (fresh install) but the issue not fixed
image
image

Thanks to check and feedback.

**Comment by matks** [comment]
@khouloudbelguith You're right !

I have been betrayed by @atomiix who made me [modify my PR](https://github.com/PrestaShop/PrestaShop/pull/20941/commits/452dd8202d54db39b3bcb9126e1304f1afc9fbba) thus breaking it

**Comment by matks** [comment]
I however found, luckily for @atomiix :trollface: , that the real culprit was [PrestaShop code](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/form/CustomerForm.php) 

```
    public function setGuestAllowed($guest_allowed = true)
    {
        $this->formatter->setPasswordRequired(!$guest_allowed);
        $this->guest_allowed = $guest_allowed;

        return $this;
    }
```
Although "guest allowed" is correctly acknowledged by the CustomerForm, the `password required` part was not acknowledged correctly so I fixed this in [a new commit](https://github.com/PrestaShop/PrestaShop/pull/20941/commits/452dd8202d54db39b3bcb9126e1304f1afc9fbba).

It should be fine now, and we keep @atomiix suggestion that was, after all, a good one

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matks,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1IYZ4mPBWVvZ9fXrqjafasxBi2E3hdTch/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @matks  & @khouloudbelguith
