### PR TITLE
Remove useless ini_set for Windows

### LINKED ISSUE #20206: Options that can't be changed via ini_set()
#### Describe the bug

PHP ini settings: `realpath_cache_size` and `realpath_cache_ttl` can only be changed via `php.ini` file or `httpd.conf` but not via `ini_set()`.
Because these options has mode "PHP_INI_SYSTEM"

[These options in php manual](https://www.php.net/manual/en/ini.core.php#ini.sect.performance)
> **Changeable** PHP_INI_SYSTEM

[More about PHP_INI_SYSTEM](https://www.php.net/manual/en/configuration.changes.modes.php)
> PHP_INI_SYSTEM Entry can be set in php.ini or httpd.conf

#### Expected behavior
N/A
#### Steps to Reproduce

```php
if (ini_set('realpath_cache_size', '1M') === false) {
    echo 'Cannot set "realpath_cache_size" ini option', PHP_EOL;
}
if (ini_set('realpath_cache_ttl', '300') === false) {
    echo 'Cannot set "realpath_cache_ttl" ini option';
}
```

**Screenshots**

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A
* File where bug occured: https://github.com/PrestaShop/PrestaShop/blob/42833c4097071b46f37b76f6c347fb579447e3e1/classes/Windows.php#L35-L36

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | These configuration variables can only be set by php.ini or httpd.conf and have no effect here. I keep the class in case of someone override the Windows class.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20206
| How to test?  | No need QA.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20235)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: classes/Windows.php [hunk 1]
```diff
@@ -32,7 +32,5 @@ class WindowsCore
 {
     public static function improveFilesytemPerformances()
```
Comment (PululuK) [inline classes/Windows.php:35]: Maybe add deprecated in this case

Comment (PierreRambaud) [reply classes/Windows.php:35]: You're right, good idea!

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]
