### PR TITLE
Fix module link in adminsearch

### LINKED ISSUE #28868: [BO - Search] - Old links redirecting to ModuleCatalog appear and redirect to Page not found
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

While searching in BO for Orders (for example), old links redirecting to ModuleCatalog appear and redirect to the Page not found: 

https://user-images.githubusercontent.com/23308427/175934309-7f7b4049-a12f-4a20-a722-2680af5364e3.mp4

### Expected behavior

These old links redirecting to ModuleCatalog shouldn't be displayed

### Steps to reproduce

1. BO > Click on the Search bar
2. Make a search for Orders (for exemple)
3. In the block modules, there are two links displayed
4. Try to click on one of them
5. See error > The page not found is displayed with the error message: `The controller AdminModulesCatalog is missing or invalid.`

### PrestaShop version(s) where the bug happened

8.0.x & develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | This PR fix the link to the module when we search in admin 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28868.
| Related PRs       | 
| How to test?      | See beelow
| Possible impacts? | 

Same PR as https://github.com/PrestaShop/PrestaShop/pull/28785 but in 8.0.x branch 

`cd admin-dev/themes/new-theme/`
`npm run build
`
Search a module in back office top search bar and check the link

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 1]
```diff
@@ -477,6 +478,16 @@ class AdminModuleController {
     let newValue;
     let defaultMax;
 
+    const paramsUrl = (new URL(document.location)).searchParams;
+    const findModule = paramsUrl.get('find');
+
+    if (findModule !== null && self.findModuleUsed !== true) {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]:
```suggestion
    if (findModule && self.findModuleUsed !== true) {
```

Isn't it enough? I barely use `myVar !== null` so it's pretty surprising

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Also findModule could be `undefined` and so it would jump into the condition

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 2]
```diff
@@ -477,6 +478,16 @@ class AdminModuleController {
     let newValue;
     let defaultMax;
 
+    const paramsUrl = (new URL(document.location)).searchParams;
+    const findModule = paramsUrl.get('find');
+
+    if (findModule && self.findModuleUsed !== true) {
+      self.currentTagsList.push(findModule);
+      self.findModuleUsed = true;
+    } else if (findModule !== null) {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]:
```suggestion
    } else if (findModule) {
```

**Review by NeOMakinG — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @okom3pom,

Thank you for this PR.
Tested on 8.0.x, PHP 7.3

Links are well redirected ✅. Here's my screenrecord:

https://user-images.githubusercontent.com/2854834/179954593-bd7633e1-932e-4bd5-86ee-842d5ee575b2.mp4

 QA approved ✅ 
 
 Thanks

**Comment by matthieu-rolland** [comment]
thank you @okom3pom and @sLorenzini !
