### PR TITLE
Prevent from loading old carts

### LINKED ISSUE #17716: Prestashop loads old carts for logged in users
**Describe the bug**
When the option "Re-display cart at login" is turned on, and customer has some old abandoned cart, it will get loaded even if the customer also has some never ordered carts.

The cart should be loaded only if it's the last one from the customer's carts.

>Edit by Khouloud

**Steps to reproduce**
1. In the BO => Shop Parameters => Customer Settings => Disable "Re-display cart at login"
2. Go to the FO => login with your customer
3. Add some products to the cart
4. Sign out ( a new line is added to the BO => Shopping carts page)
5. Go to the FO => login with your customer
6. Add some products to the cart
7. Complete checkout
8. In the BO => Shop Parameters => Customer Settings => Enable "Re-display cart at login" again
9. Go to the FO => login with your customer
10. You will have old products in the cart.

### PR DESCRIPTION
**Pull request by daresh**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When the customer has some old abandoned cart before a more recent valid carts (with orders), that one old cart will get loaded after log in. This change ensures that the cart is loaded only if it's the last cart the customer had.1
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #17716
| How to test?  | See ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17712)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
Hi @daresh , and thank you for the time you gave to this contribution 👍 

Before considering your fix, we need you to validate with the product team that we want this problem to be fixed this way.

Could you please create an issue explaining the bug?

https://github.com/PrestaShop/PrestaShop/issues/new?template=bug_report.md

When it's done you can put the ID of your issue in the PR's description table ("Fixed ticket").
A member of the product will read your issue and from there we will take your PR into consideration.

Thanks !

**Comment by daresh** [comment]
@matthieu-rolland should be done now

**Comment by matthieu-rolland** [comment]
thanx @daresh 👍

**Comment by matks** [comment]
Hi @daresh I am sorry this PR got a bit lost. I see it, I think it makes sense 👍  I approve

**Review by matks — DISMISSED** [review]

File: classes/Cart.php [hunk 1]
```diff
@@ -4008,6 +4008,7 @@ public static function lastNoneOrderedCart($id_customer)
                 WHERE NOT EXISTS (SELECT 1 FROM ' . _DB_PREFIX_ . 'orders o WHERE o.`id_cart` = c.`id_cart`
                                     AND o.`id_customer` = ' . (int) $id_customer . ')
                 AND c.`id_customer` = ' . (int) $id_customer . '
+                AND c.`id_cart` = (SELECT MAX(`id_cart`) FROM `' . _DB_PREFIX_ . 'cart` c2 WHERE c2.`id_customer` = ' . (int) $id_customer . ')
```
Comment (PierreRambaud) [inline classes/Cart.php]:
```suggestion
                AND c.`id_cart` = (SELECT `id_cart` FROM `' . _DB_PREFIX_ . 'cart` c2 WHERE c2.`id_customer` = ' . (int) $id_customer . ' ORDER BY `id_cart` DESC LIMIT 1) 
```
Is maybe faster because  `MAX ` will check for all lines.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
A little comment

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM can be merged if the requested change are OK
@matthieu-rolland have the requested changes been made ?

**Comment by matks** [comment]
> LGTM can be merged if the requested change are OK
> @matthieu-rolland have the requested changes been made ?

Changes have been applied 😊  thanks !

And thank you @daresh
