### PR TITLE
Create Order - Cart details modal - Fix refresh for cart total

### LINKED ISSUE #22105: BO - Order page - Details modal for carts - the Refresh button is not working
#### Describe the bug

In the BO > Orders > Add new Order page > Search a customer > choose it > Open the details for a cart > the refresh button doesn't work.
image

PS 1768 => the refresh button doesn't exist
image

#### Steps to Reproduce

1. Go to FO > Sign in with a customer for example "John Doe", add a product to the cart
2. Don't close the tab window
3. Go to BO > Orders > Add new Order > Search the customer "John Doe" > Choose it
4. Click on the details for the last Cart (the modal is opened)
5. Go back to the FO > Add another product to the cart or just update the quantity
6. In the BO > Orders > Add new Order > Cart details modal > Click on Refresh 
7. See error > Nothing happens

PS: if you close the Modal and open it again => OK

**Screenshots**

https://drive.google.com/file/d/1iwjYEFv70elQ4V_qZu-9guwkKP_CjH_w/view?usp=sharing

#### Additional information

* PrestaShop version: 1770stablebuild1.
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix missing source attribute for the KPIHelper to fix JS error. Do not show the refresh button
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22105 
| How to test?  | In BO > Orders > Add new Order page > Search a customer > choose it > Open the details for a cart > You will see the amount of the cart and no *Refresh* button<br><br>In Orders > Shopping carts > choose a cart and hit View > You will see the total amount of the cart and no *Refresh* button

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22249)

### CODE REVIEW

File: src/Adapter/Kpi/ShoppingCartTotalKpi.php [hunk 1]
```diff
@@ -74,7 +71,7 @@ public function render()
         $helper->title = $translator->trans('Total Cart', [], 'Admin.Orderscustomers.Feature');
         $helper->subtitle = $translator->trans('Cart #%ID%', ['%ID%' => $cart->id], 'Admin.Orderscustomers.Feature');
         $helper->value = $this->locale->formatPrice(
-            $this->getCartTotalPrice($cart),
+            $cart->getCartTotalPrice(),
             Currency::getIsoCodeById((int) $cart->id_currency)
         );
```
Comment (Progi1984) [inline src/Adapter/Kpi/ShoppingCartTotalKpi.php:78]:
```suggestion
        $helper->source = Context::getContext()->link->getAdminLink('AdminStats') . '&ajax=1&action=getKpi&kpi=shopping_cart_total&cartId=' . $cart->id;
```

**Review by Progi1984 — DISMISSED** [review]
DONT MERGE BEFORE 1771 RELEASE

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]
