### PR TITLE
In MultiShop, In new Category, display the top category if there are more one root category

### LINKED ISSUE #23365: BO - The browser is unable to show the error message on an hidden element.
#### Describe the bug

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/22942#issuecomment-781249540
As commented [here](https://github.com/PrestaShop/PrestaShop/pull/22942#issuecomment-781380741) by @NeOMakinG 
An error displayed in the console when creating category,  it's due to radio elements which are inside a `display: none;` property. so the browser is unable to show the error message on an hidden element.

#### Expected behavior

Select the highest parent category automatically .

#### Steps to Reproduce

1. If this [PR](https://github.com/PrestaShop/PrestaShop/pull/22942) is merged
2. Use this PR: https://github.com/PrestaShop/prestashop-ui-kit/pull/137
3. Enable Multistore Context
4. Create a new shop
5. Go to BO > Catalog > Categories page
6. Add a new root category > Save
7. At this step, you are in the Root category list 
image
8. Select only the first shop/second shop
10. Add a new category > the Parent category is not selected
11. Set only the Name & save
12. See the error on the console

image

Previously we have this alert 
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In MultiShop, In new Category, display the top category if there are more one root category<br><br>The bug is only in multi shop mode.<br><br>If in single shop context, you try to create a category in root category which is not the root category of the single shop, you don't have the categories list but only  categories of the root category of the single shop.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23365
| How to test?      | Cf #23365<br><br>Sample case<br>  - In multi shop mode<br>  - Create a shop (which have "Home" as default category)<br>  - Create a root category for this shop<br>  - Go in this root category<br>  - In single shop context (Shop)<br>  - Create a category (**Before:** For parent category , only have "Home" and none are checked/ **After:** For parent category, have top category and the previous root category is checked)

# Related specifications

By [@marion](https://github.com/PrestaShop/PrestaShop/pull/25046#issuecomment-942125508)

> While creating a shop, you have to select a root category through the drop-down.
The categories displayed in the "associated categories" should be the root category selected above + the sub-categories belonging to the root category selected.
I updated the specs: PrestaShop/prestashop-specs#245

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25046)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Short, efficient ^^

**Review by sowbiba — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Enable multistore context and create a new shop
2. In the BO > Catalog > Categories page > Select a shop and create a root category
3. On this page > create a simple category 
image

4. Set name and save => see error
image

I attached a screen record
https://drive.google.com/file/d/1TJ-9g3kHJY4C5Yd8d8o4bXxISMYiaInc/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith You're right. We have discussed with @MatShir : so we have removed the creation of category at the root.

**Review by matthieu-rolland — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi  @Progi1984,

The button is still enabled following these steps:

1. Enable Multistore Context
2. Create a new shop and configure the URL
3. Go to BO > Catalog > Categories page
4. Add a new root category > Save
5. Disable multistore context
6. Go to the BO > Catalog > Categories page > In the root category: the button add new category is displayed 
image

It should be 
image

I attached a screerecord
https://drive.google.com/file/d/1StJyVy5LIRZVwnp4Gl6IMhbtYNsVvytJ/view?usp=sharing
Thanks!

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have a difference between branch 1.7.8.x with and without PR.


1. Go to BO > Shop Parameters > General page and enable multistore
2. Go to BO > Advanced Parameters > Multistore page > Create a new shop
3. Go to BO > Catalog > Catagories page
4. Add a new root category `Home2`
5. Go to BO > Advanced Parameters > Multistore page > Click on `Add new shop`
6. Change the Category root to `Home2`
7. Click on `Expand all`

**With PR**
I have this Tree 
image

It is ok 

**Without PR**
I have this Tree
image

=> NOK

**But**

After the step 7 if we click on **Save**

**With Pr** => I have this warning + red alert
image

**Without PR** => No warning displayed / just red alert 
image


Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith I'm sorry. But I haven't got the problem. Could you retest ?

**Review by sowbiba — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I made a new fresh install of this PR.
I manage to reproduce the same issue.
I attached a screen record
https://drive.google.com/file/d/1RlMIW4e-atlnhvu3Rdbl-xZGHKvU9dH_/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith Ok. I see your problem. I look at specs : https://build.prestashop.com/prestashop-specs/1.7/back-office/advanced-parameters/multistore/multistore.html#shop

> Associated categories: Allow to select the categories that will be associated with the store 

That doesn't talk about shops or the action behind the button.

So I use my @PrestaShop/product-team for having the expected behavior.

**Comment by marionf** [comment]
While creating a shop, you have to select a root category through the drop-down.
The categories displayed in the "associated categories" should be the root category selected above + the sub-categories belonging to the root category selected.
I updated the specs: https://github.com/PrestaShop/prestashop-specs/pull/245

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php [hunk 1]
```diff
@@ -817,16 +819,21 @@ private function getCategoryToolbarButtons(Request $request)
             ];
         }
 
-        $categoryId = $request->attributes->get('categoryId');
+        if (empty($categoryId)) {
```
Comment (tegbessou) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php]: Nice to have.
Here empty is not necessary, you can just use this suggestion. Because of your type-hint in int.
```suggestion
        if ($categoryId === 0) {
```

Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php]: Fixed

Comment (tegbessou) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php]: Thank you

**Comment by tegbessou** [comment]
PR is valid IMO

**Review by tegbessou — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]
Thank you @Progi1984

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
>@khouloudbelguith You're right. We have discussed with @MatShir : so we have removed the creation of category at the root.

First spec => ok 
1. Root category

Multistore disabled
image
Multostore enabled
image
2. Not root category

Multistore disabled 
image

Multistore enabled
image

>While creating a shop, you have to select a root category through the drop-down.
The categories displayed in the "associated categories" should be the root category selected above + the sub-categories belonging to the root category selected.
I updated the specs: PrestaShop/prestashop-specs#245

Second spec => ok
New root category
image
Default category
image

**Without PR** 
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
