### PR TITLE
Cancel/Refunds... adding missing hooks and cancel product refactor

### LINKED ISSUE #20712: actionProductCancel hook not triggered on standard refund
#### Describe the bug
In 1.7.6, the **actionProductCancel** hook was triggered from the BO order page, when clicking on the button "cancel product", "standard refund" or "cancel product". In 1.7.7 it is triggered only when clicking on "cancel product".

#### Expected behavior
The **actionProductCancel** hook should be triggered on all kinds of cancellation / refunds.

#### Steps to Reproduce

Perform a "cancel product", a "standard refund" or a "return product", **actionProductCancel** hook should be triggered.

#### Additional information
* PrestaShop version: 1.7.7

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | The actionProductCancel hook was not being triggered on standard refund or return product, yet it was in 1.7.6, this PR fixes this, and also refactors the CancelOrderProductHandler (it doesn't add code or change the logic, it just makes the code easier to read, and avoids useless duplicate foreach loops)
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20712
| How to test?  | The actionProductCancel hook should be triggered when performing a "Cancel product", "Standard Refund" or "Return product" from the order detail page in BO.

So this PR does 3 things:

1/ Call hooks where it should be called but wasn't 

2/ Small refactor of the `CancelOrderProductHandler` which contains mostly legacy code, here I add no new code, I just changed its organization, made it more readable by moving logical pieces of code in descriptively named private methods, and improved it a little bit performance-wise.

3/ Add a customized product in every `order-cancel-product` behat scenarios.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20693)

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
So this PR does 3 things:

1/ Call hooks where it should be called but wasn't 

2/ Small refactor of the `CancelOrderProductHandler`, no new code, I just changed its organization, made it more readable, and improve it a little bit.

3/ Add a customized product in every `order-cancel-product` behat scenarios.

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 1]
```diff
@@ -91,59 +91,11 @@ public function handle(CancelOrderProductCommand $command)
...
-            $customization_quantities = Customization::retrieveQuantitiesFromIds(array_keys($customizationList));
-            foreach ($customizationList as $id_customization => $id_order_detail) {
-                $qtyCancelProduct = abs($orderDetails['customizedCancelQuantity'][$id_customization]);
-                $customization_quantity = $customization_quantities[$id_customization];
-                if (!$qtyCancelProduct) {
-                    throw new InvalidCancelProductException(InvalidCancelProductException::INVALID_QUANTITY);
-                }
-                $cancellableQuantity = $customization_quantity['quantity'] - ($customization_quantity['quantity_refunded'] + $customization_quantity['quantity_returned']);
+        // check quantity of cancelled products versus cancellable quantities
+        $this->checkProductCancelQuantities($orderDetails, $customizationQuantities);
```
Comment (atomiix) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: Maybe rename this method `assertCancelableProductQuantities()`?

**Review by atomiix — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !! The The actionProductCancel hook seems to be correctly triggered for the "Cancel product", "Standard Refund" or "Return product" actions . Thanks @matthieu-rolland !!

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @SD1982
