### PR TITLE
Do not allow negative amount in order payment block

### LINKED ISSUE #16582: It is possible to add negative Amount for Order Payment from the Back Office
**Describe the bug**
It is possible to add negative Amount for Order Payment from the Back Office. Then message is thrown: An unexpected error occurred. [PrestaShopException code 0]. The actual exception is: Property Order->total_paid_real is not valid.

According to as I understand negative payments should not be saved to the database or at least total sum of payments from the db should not be negative.

**To Reproduce**
1. Go to Front Office and create new order.
2. Go to Back Office and go into that order page
3. Scroll down to Payment section and add new payment with negative amount: -5.548
4. See error: An unexpected error occurred. [PrestaShopException code 0]

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.
Screenshot from 2019-11-28 12-51-45
Screenshot from 2019-11-28 12-52-21

**Additional information**
Have Behat integration 2 failing tests written in file /Order/add_payment.feature on the Github Pull request: https://github.com/PrestaShop/PrestaShop/pull/16525

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Do not allow negative amount in order payment
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16582
| How to test?  | In the migrated order/view page, try to add a payment with a negative amount, an error should be displayed and the payment should not be added

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17241)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 1]
```diff
@@ -803,6 +803,10 @@ public function addPaymentAction(int $orderId, Request $request): RedirectRespon
             } catch (Exception $e) {
                 $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
             }
+        } elseif (!$form->isValid()) {
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```php
       if ($form->isSubmitted()) {
            if (!$form->isValid()) {
                foreach ($form->getErrors(true) as $error) {
                    $this->addFlash('error', $error->getMessage());
                }
            } else {
                $data = $form->getData();

                try {
                    $this->getCommandBus()->handle(
                        new AddPaymentCommand(
                            $orderId,
                            $data['date'],
                            $data['payment_method'],
                            $data['amount'],
                            $data['id_currency'],
                            $data['id_invoice'],
                            $data['transaction_id']
                        )
                    );

                    $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
                } catch (Exception $e) {
                    $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
                }
            }
        }

**Comment by matks** [comment]
Can you turn on the test we disabled until this bug is fixed ? 😄this will help validating the feature

https://github.com/tdavidsonas88/PrestaShop/commit/ea4251123a6c43eaf53b9a1fb13006751b434765

**Review by jolelievre — APPROVED** [review]
Thanks @atomiix

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — CHANGES_REQUESTED** [review]
Sorry I missed the behat test part ^^ Please add:
- a check for negative amount in the handler (or the command via ValueObject maybe easier) which throws an exception
- reactivate the behat test and add a line to check that the appropriate exception has been thrown

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 2]
```diff
@@ -1215,6 +1222,10 @@ private function getErrorMessages(Exception $e)
                 'There are not enough products in stock',
                 'Admin.Notifications.Error'
             ),
+            NegativePaymentAmountException::class => $this->trans(
+                'The amount should be greater than 0.',
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
                'The amount of a payment should be strictly positive.',
```

Suggestion @LouiseBonnard what do you think?

File: tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php [hunk 3]
```diff
@@ -129,15 +130,19 @@ public function addPaymentToOrderWithTheInvalidFollowingProperties(string $order
...
                 )
             );
-        } catch (PrestaShopException $exception) {
-            $msg = $exception->getMessage();
-            $expectedMsg = 'Property Order->total_paid_real is not valid';
-            if ($msg !== 'Property Order->total_paid_real is not valid') {
-                throw new RuntimeException(sprintf('Not expected exception is thrown "%s" but "%s" was expected', $msg, $expectedMsg));
-            }
+        } catch (NegativePaymentAmountException $exception) {
+            $this->lastException = $exception;
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php:134]: Be careful you removed an expected behaviour (with Property Order->total_paid_real is not valid), although the way it was managed was weird
You need to find the related behat test and fix/refacto it By catching the `PrestaShopException` exception and maybe only store it when the message matches so that other use cases correctly fail

**Review by matthieu-rolland — DISMISSED** [review]
@jolelievre 's feedback has been dealt with properly, LGTM for me 👍

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 2 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: It sounds a bit authoritarian, aha! Why changing the wording, isn't it clear enough?

If you want to emphasize the mandatory side of it, I would write _Invalid value: the payment must be a positive amount._, what do you think?

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix ! Could you resolve the conflict on this PR ? Thanks !

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: It's not the mandatory side that I wanted to emphasize, but more having a less "technical" message I just though "positive amount" is maybe more understandable than "greater to 0"

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: I agree, thanks @jolelievre. I still suggest _Invalid value: the payment must be a positive amount._ in this case, it looks clearer.

**Review by jolelievre — APPROVED** [review]
Nice @atomiix

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @atomiix

**Comment by djbuch** [comment]
This is completely wrong... The majority of e-commercant we are helping are typing negative amounts in case of reimbursement... This should be rolled back as soon as possible.

**Comment by matks** [comment]
Hi @djbuch there are 4 possible ways to refund an order:
- cancel a product
- standard refund
- partial refund
- return products

You can see the details in https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/orders/orders/Order%20Page%20View.md#merchandise-return-has-to-be-enabled-if-the-merchant-want-to-use-the-standard-refund-partial-refund-and-return-product-feature

Why not use them rather than typing a negative amount in a "payment" field?

**Comment by djbuch** [comment]
Because those use cases only create the OrderSlip if the Invoice has already been created or cancel a product, but it won't change the payment.

But imagine a workflow were the invoice is created when the Order is already sent out.
Then the seller sees he has not enough of one product, so he cancels the product or lowers the quantity, the order total is so decreased, and he will have an error in the payment section, saying that there was too much paid.

So when he really makes the reimbursement to the buyer with his bank system, he could note this in here with a negative amount to keep track of financial mouvement for this order.

**Comment by matks** [comment]
@djbuch So if I understand correctly, here is a valid scenario

1. I buy 4 boxes of Sugar, each costs 15€ => my order is 60€. I pay 60€. No shipping fees. No VAT, it's B2B.
2. I receive my invoice (it mentions 60€).
3. Merchant finds out OH NO! he has only 3 boxes
4. Merchant wants to modify the order, he modifies the quantity to 3. Order total decreases to 45€.
5. But I already paid 60€ ! So this order is in "overdue" status.
6. What you want to do is "Merchant sends a 15€ check to me, and marks the order as 'paid' (not overdue)" in the Back Office because now the amount I have paid and the amount of my order are equal

Is that a good scenario ?

@MatShir @marionf what do you think about this usecase?

@djbuch I still think that adding negative amount payments is not a good solution 😅  but maybe there is a scenario that is not handled by PrestaShop, indeed. Let's see what Product Team can say.

**Comment by djbuch** [comment]
@matks Yes this is a valide use case.

Maybe the negative could be checked agains total payments no becoming negative. But a reimbursement is indeed a negative payment.

**Comment by matks** [comment]
AFAIK Product team is actually in the process of getting some law compliance people so that they can tell us what can be done or what cannot be done in order to comply with the law.

**Comment by PrestaEdit** [comment]
The main issue there is not that you disallow to add the negative price on the Back Office, but that the model have been change (it's a BC break, as far I know) on a minor version (1.7.7) and you are now not allowed to make a refund with a specific transaction ID and set the negative amount using the ObjectModel related, so.
