### PR TITLE
Fix fatal error in product catalog when short description is too long

### LINKED ISSUE #11887: Error 500 - Disable product with a too long short description
If you limit the short description size and you already have products that exceed the new limit, an Error 500 is thrown when trying to disable the product by clicking in the "tick" icon in product listing.

To Reproduce

1. Save a long Summary description for any product (e.g., a description with 200 characters)
2. Go to "Shop Paramaters > Product Settings" and set "Max size of short description" to a shorter value than the size of the description you've just saved (e.g. 160)
2. Go to "Catalog > Products" and try to disable it directly in the product listing by clicking on the tick icon of the "state" column.

An Error 500 will be thrown.

Additional information
PrestaShop version: 1.7.5.0
PHP version: 7.1.25

### PR DESCRIPTION
**Pull request by rblaurin**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Error 500 - Disable or duplicate product with a too long short description
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | Fixes #11887
| How to test?  | Follow the steps to reproduce the behavior described in the Issue #11887

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12662)

### CODE REVIEW

File: src/Adapter/Product/AdminProductDataUpdater.php [hunk 1]
```diff
@@ -73,7 +73,9 @@ public function activateProductIdList(array $productListId, $activate = true)
         $failedIdList = array();
         foreach ($productListId as $productId) {
             $product = new Product($productId);
-            if (!Validate::isLoadedObject($product)) {
+            if (!Validate::isLoadedObject($product)
+                || (($product->validateFields(false, true)) !== true)
+                || (($product->validateFieldsLang(false, true)) !== true)) {
```
Comment (Quetzacoalt91) [inline src/Adapter/Product/AdminProductDataUpdater.php]:
```suggestion
                || $product->validateFieldsLang(false, true) !== true) {
```

File: src/Adapter/Product/AdminProductDataUpdater.php [hunk 2]
```diff
@@ -73,7 +73,9 @@ public function activateProductIdList(array $productListId, $activate = true)
         $failedIdList = array();
         foreach ($productListId as $productId) {
             $product = new Product($productId);
-            if (!Validate::isLoadedObject($product)) {
+            if (!Validate::isLoadedObject($product)
+                || (($product->validateFields(false, true)) !== true)
```
Comment (Quetzacoalt91) [inline src/Adapter/Product/AdminProductDataUpdater.php]:
```suggestion
                || $product->validateFields(false, true) !== true
```

File: src/Adapter/Product/AdminProductDataUpdater.php [hunk 3]
```diff
@@ -169,6 +171,11 @@ public function duplicateProduct($productId, $namePattern = 'copy of %s')
             throw new \Exception('AdminProductDataUpdater->duplicateProduct() received an unknown ID.', 5005);
         }
 
+        if ((($product->validateFields(false, true)) !== true)
```
Comment (Quetzacoalt91) [inline src/Adapter/Product/AdminProductDataUpdater.php]:
```suggestion
        if ($product->validateFields(false, true) !== true
```

File: src/Adapter/Product/AdminProductDataUpdater.php [hunk 4]
```diff
@@ -169,6 +171,11 @@ public function duplicateProduct($productId, $namePattern = 'copy of %s')
...
+            || (($product->validateFieldsLang(false, true)) !== true)) {
```
Comment (Quetzacoalt91) [inline src/Adapter/Product/AdminProductDataUpdater.php]:
```suggestion
            || $product->validateFieldsLang(false, true) !== true) {
```

File: src/Adapter/Product/AdminProductDataUpdater.php [hunk 5]
```diff
@@ -169,6 +171,11 @@ public function duplicateProduct($productId, $namePattern = 'copy of %s')
...
+            throw new UpdateProductException('Cannot duplicate many requested products', 5004);
```
Comment (Quetzacoalt91) [inline src/Adapter/Product/AdminProductDataUpdater.php]: cc @LouiseBonnard

**Review by Quetzacoalt91 — CHANGES_REQUESTED** [review]
Some changes regarding the parentheses are required

File: src/Adapter/Product/AdminProductDataUpdater.php (hunk 5 above)
Comment (LouiseBonnard) [reply src/Adapter/Product/AdminProductDataUpdater.php]: Should we mention the error is caused by a too long product description?

**Comment by rblaurin** [comment]
> Some changes regarding the parentheses are required

Thanks, commited the suggested changes

File: src/Adapter/Product/AdminProductDataUpdater.php (hunk 5 above)
Comment (rblaurin) [reply src/Adapter/Product/AdminProductDataUpdater.php]: @LouiseBonnard, Do you mean specifically test description_short instead of all fields?
```suggestion
        foreach (Language::getIDs(false) as $id_lang) {
            if ($product->validateField('description_short', $product->description_short[$id_lang], $id_lang) !== true) {
                throw new UpdateProductException(
                    sprintf(
                        'Cannot duplicate this product because the "Summary" field for the language "%s" is too long',
                        Language::getIsoById($id_lang)
                    )
                );                                        
            }
        }
```

Comment (rblaurin) [reply src/Adapter/Product/AdminProductDataUpdater.php]: @LouiseBonnard, do you mean specifically validate the description_short field instead of all fields? Maybe something like: 'Cannot duplicate this product because the "Summary" field for the language "%s" is too long'?

Comment (Quetzacoalt91) [reply src/Adapter/Product/AdminProductDataUpdater.php]: @LouiseBonnard the issue can be a field too long, but something else too.

Il we want to display a reason, we could retrieve the result of `
validateFields` or `
validateFieldsLang` instead.

Comment (LouiseBonnard) [reply src/Adapter/Product/AdminProductDataUpdater.php]: Alright, I thought it was only because of the long description... thanks for the suggestion, @Quetzacoalt91, how could we display this wording?

Comment (Quetzacoalt91) [reply src/Adapter/Product/AdminProductDataUpdater.php]: We could a "global" message saying we cannot duplicate the product (as initially suggested), and concatenate the returned validation message (already translated).

Comment (rblaurin) [reply src/Adapter/Product/AdminProductDataUpdater.php]: @Quetzacoalt91, I have made some changes. Is that what you were talking about?
```suggestion
            throw new UpdateProductException(sprintf('Cannot duplicate this product: %s', $error));
```

**Review by Quetzacoalt91 — APPROVED** [review]
In my opinion that's an efficient way to display the current error. I'm requesting another quick review from @PrestaShop/prestashop-core-developers just in case.

**Note to the merger:** Commits need to be squashed

**Comment by Quetzacoalt91** [comment]
Thank you @rblaurin
