### PR TITLE
Take customizations into account when performing operations on orders

### LINKED ISSUE #23734: BO - Orders page  - Multi-invoice issue - Customized product cannot be added to multi-invoice
#### Describe the bug

In the BO >  Order details page, when we have multi-invoices, adding a customized product is NOK.

#### Steps to Reproduce

1. Create an order from BO/FO with a customized product for example "demo_14"
2. Generate an invoice for this order
3. Go to BO > Orders > last order details page
4. Add the same customized product "demo_14" with creating a new invoice
5. See error: the invoice is created with 0 total, the customized product is not added

**Screenshots**

PS1773build1: https://drive.google.com/file/d/1_w37zZ7nJz5GSbqhNsX83ZwZVYqRTf8H/view?usp=sharing
PS1769 => OK: https://drive.google.com/file/d/1eH--nxu2m9csud9NDhgS3i_BrrImWX3n/view?usp=sharing

#### Additional information

* PrestaShop version: 1770, 1773build1
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Because customizations were not took into account when performing operations on an order, inconsistencies could happen leading to wrong total/quantity. This PR fixes it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23734
| How to test?      | Please see #23734
| Possible impacts? | Adding/modifying/deleting products with/without customization in an order can be impacted.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23902)

### CODE REVIEW

File: src/Adapter/Cart/Comparator/CartProductUpdate.php [hunk 1]
```diff
@@ -56,13 +62,15 @@ class CartProductUpdate
     /**
      * @param int $productId
      * @param int $combinationId
+     * @param int $customizationId
      * @param int $deltaQuantity
      * @param bool $created
      */
-    public function __construct(int $productId, int $combinationId, int $deltaQuantity, bool $created)
+    public function __construct(int $productId, int $combinationId, int $customizationId, int $deltaQuantity, bool $created)
```
Comment (Progi1984) [inline src/Adapter/Cart/Comparator/CartProductUpdate.php]: Bad idea to put it at the middle. Why not put it at the end and set it as optional with null as default value ?

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Not sure about the BC Break. A discussion starts.

File: src/Adapter/Cart/Comparator/CartProductUpdate.php (hunk 1 above)
Comment (atomiix) [reply src/Adapter/Cart/Comparator/CartProductUpdate.php]: I thought about it but as this class is new (introduced in 1.7.7.0), I thought it was cleaner to put this parameter just after `$combinationId`.

Comment (Progi1984) [reply src/Adapter/Cart/Comparator/CartProductUpdate.php]: The problem is the code is already in production. So we must think to users. 

Could you move the parameter ?

Comment (PierreRambaud) [reply src/Adapter/Cart/Comparator/CartProductUpdate.php]: The parameter must be after, otherwise, it's a bc break. If the parameter is mandatory, we can't accept it, but it's still a bc breaks :sweat_smile:

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an issue following these steps:
1. Create a product with customization not required ( minimum one)
I tested with these cases, I manage to reproduce the issue with those cases.
- `Product1` Text not required + File not required 
image
- `Product2` Text not required 
image
- `Product3` Text not required + Text required 
image
2. Go to FO > Produc1 details page
3. Click on "Add to cart" without adding any customization
4. Click on "Continue Shopping"
5. Add a text or File or two customizations and save 
6. Add the product to the cart
7. Continue checkout and place Order
8. Go to BO > Orders > Edit last order created
9. Try to update the base price of a product
10. Click on Save and confirm the action
11. See error 
image

I attached a screen record
https://drive.google.com/file/d/1h19d6ApreK_c0hlyTqPXeUpJ2OgF6NIQ/view?usp=sharing

Thank you!

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I think we should have the Modal when updating the price
image
because the price of all products is updated
Following these steps:
1. Create a product with customization not required ( minimum one)
- `Product2` Text not required 
image
2. Go to FO > Product details page
3. Click on "Add to cart" without adding any customization
4. Click on "Continue Shopping"
5. Add text customization and save 
6. Add the product to the cart
7. Continue checkout and place Order
8. Go to BO > Orders > Edit last order created
9. Try to update the base price of a product
10. Click on Save and confirm the action
11. Refresh the page => the price of the second product is updated too.

https://drive.google.com/file/d/1f-5Bq9jeSTlN7hORtu0WU4ZiQp63Bpeb/view?usp=sharing

What do you think? Thanks!

File: tests/Unit/Adapter/Cart/Comparator/CartProductsComparatorTest.php [hunk 2]
```diff
@@ -229,14 +229,14 @@ public function getExpectedModifiedProducts()
...
+                ['id_product' => 2, 'id_product_attribute' => 0, 'id_customization' => 0, 'cart_quantity' => 2],
             ],
             // New products
             [
-                ['id_product' => 1, 'id_product_attribute' => 0, 'cart_quantity' => 1],
-                ['id_product' => 2, 'id_product_attribute' => 0, 'cart_quantity' => 2],
-                ['id_product' => 3, 'id_product_attribute' => 0, 'cart_quantity' => 2],
+                ['id_product' => 1, 'id_product_attribute' => 0, 'id_customization' => 0, 'cart_quantity' => 1],
+                ['id_product' => 2, 'id_product_attribute' => 0, 'id_customization' => 0, 'cart_quantity' => 2],
+                ['id_product' => 3, 'id_product_attribute' => 0, 'id_customization' => 0, 'cart_quantity' => 2],
```
Comment (sowbiba) [inline tests/Unit/Adapter/Cart/Comparator/CartProductsComparatorTest.php]: Maybe add a test with id_customization !== 0

**Comment by Julievrz** [comment]
> Hi @atomiix,
> 
> I think we should have the Modal when updating the price
> image
> because the price of all products is updated
> Following these steps:
> 
> 1. Create a product with customization not required ( minimum one)
> 
> * `Product2` Text not required
>   image
> 
> 1. Go to FO > Product details page
> 2. Click on "Add to cart" without adding any customization
> 3. Click on "Continue Shopping"
> 4. Add text customization and save
> 5. Add the product to the cart
> 6. Continue checkout and place Order
> 7. Go to BO > Orders > Edit last order created
> 8. Try to update the base price of a product
> 9. Click on Save and confirm the action
> 10. Refresh the page => the price of the second product is updated too.
> 
> https://drive.google.com/file/d/1f-5Bq9jeSTlN7hORtu0WU4ZiQp63Bpeb/view?usp=sharing
> 
> What do you think? Thanks!

Hi @khouloudbelguith. As wording cannot be modified in patch versions, I created an issue to implement a more adapted wording in 1.7.8. Thanks!

**Review by Julievrz — DISMISSED** [review]
Ok to keep this wording even though it is not very clear because wordings cannot be changed in patch versions. But a more adapted wording is suggested here for 1.7.8 => https://github.com/PrestaShop/PrestaShop/issues/24191

**Review by sowbiba — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

I tested :
Automated tests Orders & FO => ok
In Order => Remove all types of products with different types/status of customization => ok
In Order => Add all types of products with different types/status of customization without creating invoice => ok
In Order => Add all types of products with different types/status of customization with creating invoice => ok
In Order => Edit all types of products with different types/status of customization with creating invoice => ok
In Order => Edit all types of products with different types/status of customization with creating invoice => ok
Create an order from the BO/FO with all types of products with different types/status of customization => ok

So it's QA :heavy_check_mark: !

Thanks :)

**Comment by Progi1984** [comment]
##DON'T MERGE BEFORE 1774 RELEASE

**Review by Progi1984 — DISMISSED** [review]
## DON'T MERGE BEFORE 1774 RELEASE

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
1.7.7.4 is released 🎉
