### PR TITLE
No more auto created carts on login

### LINKED ISSUE #9589: [BOOM-5963] Shopping cart is created automatically after login
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5963).

- _**Reporter:**_ Centoasa
- _**Created at:**_ Thu, 12 Jul 2018 14:48:03 +0200

<p>When a customer sign in, an empty cart of 0€ is created</p>

<p>The customer follow-up email being sent also for abandoned cart with 0 amount, so when customer login and ceck own order (status, amount, messages).</p>
    
---
#### Describe the bug
When a customer sign in, an empty cart of 0€ is created.

#### Expected Behavior
The cart should be created only when the customer adds a product.

#### Steps to reproduce

1. BO > SELL > Orders > Shopping Carts > check the list
2. FO > login as client
3. BO > refresh the Shopping Carts list > a new cart with the client name is created

#### Screenshots
image

#### Additional information

- PrestaShop version: 1.7.7.0 & develop
- PHP version: 7.2.34

### PR DESCRIPTION
**Pull request by Prestaworks**
Fix for issue 9589

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This will fix issue reported in 9589, where empty carts are created on login.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9589.
| How to test?      | Follow instructions in issue.
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27803)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
thank you @Prestaworks for your PR 

If I understand well, before this PR a cart would be created for the customer, even before he created any cart by adding a product  ?

Since `updateCustomer` is called at login the idea is to only create the cart if it was already created, right ?

 I'd say your fix looks good to me 👍

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Prestaworks** [comment]
> If I understand well, before this PR a cart would be created for the customer, even before he created any cart by adding a product ?

Yes, a new empty cart was created every time a customer logged in.
> 
> Since `updateCustomer` is called at login the idea is to only create the cart if it was already created, right ?

Yes, attach an existing cart to customer when logging in and also only create new carts when adding a product to the cart.

**Review by matks — DISMISSED** [review]
Hi, the integration tests fail

```
--- Failed steps:

001 Scenario: 1 product in cart, 1 cart rule with too-much amount          # Features/Scenario/Cart/CartToOrder/cart_to_order.feature:162
      Then customer "customer1" should have 1 cart rules that apply to him # Features/Scenario/Cart/CartToOrder/cart_to_order.feature:194
        Expects 1, got 0 instead (RuntimeException)
```

Looks like the change is logic has modified a scenario where a cart rule was expected to be applied

File: classes/Context.php [hunk 1]
```diff
@@ -364,25 +364,30 @@ public function updateCustomer(Customer $customer)
...
-            $this->cart->id_carrier = 0;
-            $this->cart->setDeliveryOption(null);
-            $this->cart->updateAddressId($this->cart->id_address_delivery, (int) Address::getFirstCustomerAddressId((int) ($customer->id)));
-            $this->cart->id_address_delivery = (int) Address::getFirstCustomerAddressId((int) ($customer->id));
-            $this->cart->id_address_invoice = (int) Address::getFirstCustomerAddressId((int) ($customer->id));
+            if (Validate::isLoadedObject($this->cart)) {
+                $idCarrier = (int) $this->cart->id_carrier;
+                $this->cart->secure_key = $customer->secure_key;
+                $this->cart->id_carrier = 0;
+                if ($idCarrier) {
```
Comment (saulaski) [inline classes/Context.php]: Best practice is using strict boolean condition
```suggestion
                if (!empty($idCarrier)) {
```

**Review by saulaski — CHANGES_REQUESTED** [review]
Looks good to me overall, only a minor detail :)

**Review by saulaski — DISMISSED** [review]

**Comment by raphael-jolimoi** [comment]
Hey just  a comment from someone having issues around this cart loading. In my opinion the function Cart::lastNoneOrderedCart shouldn't be used in this case since it restricts to only loading carts that have a guest ID. Shouldn't it load the last non ordered cart regardless of wether or not it is linked to a guest?
In our shop I tried something like this in a Customer class override, the function could be greatly improved it's just a quick dirty fix we also use in some other custom code:
```
public function getLastCart($with_order)
    {
        $id_customer = $this->id;
        $carts = Cart::getCustomerCarts((int)$id_customer, $with_order);
        if (!count($carts)) {
            $cart = new Cart();
            $cart->id_customer = $id_customer;
            $cart->id_currency = (int)Context::getContext()->currency->id;
            $cart->id_lang = (int)Context::getContext()->language->id;
            $cart->save();
            return $cart;
        }
        $cart = array_shift($carts);
        return new Cart((int)$cart['id_cart']);
    }
```

File: classes/controller/FrontController.php [hunk 2]
```diff
@@ -459,10 +459,9 @@ public function init()
             CartRule::autoAddToCart($this->context);
         } else {
             $this->context->cart = $cart;
+            $this->context->cart->checkAndUpdateAddresses();
```
Comment (Hydrog3n) [inline classes/controller/FrontController.php:462]: No sure about that because it's may prevent us some pb we have on cart in joliApp where product are not removable

File: classes/controller/FrontController.php [hunk 3]
```diff
@@ -519,8 +518,14 @@ public function postProcess()
 
     protected function assignGeneralPurposeVariables()
     {
+        if (Validate::isLoadedObject($this->context->cart)) {
+            $cart_presentation = $this->cart_presenter->present($this->context->cart);
+        } else {
+            $cart_presentation = $this->cart_presenter->present(new Cart());
```
Comment (Progi1984) [inline classes/controller/FrontController.php]:
```suggestion
            $presentedCart = $this->cart_presenter->present($this->context->cart);
        } else {
            $presentedCart = $this->cart_presenter->present(new Cart());
```

File: classes/controller/FrontController.php [hunk 4]
```diff
@@ -519,8 +518,14 @@ public function postProcess()
...
+        }
+
         $templateVars = [
-            'cart' => $this->cart_presenter->present($this->context->cart),
+            'cart' => $cart_presentation,
```
Comment (Progi1984) [inline classes/controller/FrontController.php]:
```suggestion
            'cart' => $presentedCart,
```

**Review by Progi1984 — COMMENTED** [review]
A small renamed variable but it's ok for me. Good job.

**Review by Progi1984 — DISMISSED** [review]

File: classes/controller/FrontController.php [hunk 5]
```diff
@@ -519,8 +518,14 @@ public function postProcess()
 
     protected function assignGeneralPurposeVariables()
     {
+        if (Validate::isLoadedObject($this->context->cart)) {
+            $presentedCart = $this->cart_presenter->present($this->context->cart);
+        } else {
+            $presentedCart = $this->cart_presenter->present(new Cart());
+        }
```
Comment (saulaski) [inline classes/controller/FrontController.php]: Just an inspiration for next time, let's factorize duplicated code :)
```suggestion
        if (Validate::isLoadedObject($this->context->cart)) {
            $cart = $this->context->cart;
        } else {
            $cart = new Cart();
        }
        $templateVars = [
            'cart' => $this->cart_presenter->present($cart),
```

**Review by saulaski — DISMISSED** [review]

File: classes/controller/FrontController.php (hunk 5 above)
Comment (Prestaworks) [reply classes/controller/FrontController.php]: I agree, this is better :)

**Review by saulaski — APPROVED** [review]

**Comment by Prestaworks** [comment]
@matks I can't see your change request? only that you "requested changes".

**Comment by matks** [comment]
@Prestaworks it was my review one week ago

https://github.com/PrestaShop/PrestaShop/pull/27803#pullrequestreview-895552237

Looks like GitHub did not remove it although new commits have been added. I remove it now.

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello, 

Issue is still not fixed following the steps bellow:

1. Go to BO> orders> Click on add new order 
2. Choose the customer John DOE > Click on choose
3. Go to the Shopping Carts list > a new cart with the client name is created

https://watch.screencastify.com/v/qm4VuQsaYB6ZiFz8jCft

Coul you please check?

Thanks,

**Comment by Prestaworks** [comment]
> Hello,
> 
> Issue is still not fixed following the steps bellow:
> 
>     1. Go to BO> orders> Click on add new order
> 
>     2. Choose the customer John DOE > Click on choose
> 
>     3. Go to the Shopping Carts list > a new cart with the client name is created
> 
> 
> https://watch.screencastify.com/v/qm4VuQsaYB6ZiFz8jCft
> 
> Coul you please check?
> 
> Thanks,

Seems lika another issue, can you create a separate ticket for the backoffice issue?

**Comment by Progi1984** [comment]
@Prestaworks It seems that the bug #9589 is not fixed. So could you check ? Thanks

**Comment by Prestaworks** [comment]
> @Prestaworks It seems that the bug #9589 is not fixed. So could you check ? Thanks

are you refering to marwachellys issue in BO?

**Comment by Progi1984** [comment]
@Prestaworks Yes, it's exactly the same defined here https://github.com/PrestaShop/PrestaShop/issues/9589#issue-352951958.

**Comment by Prestaworks** [comment]
> 

Hi, sorry I can't see where the comment is on the issue where they mention creating new orders from BO? all comments mention step 2 sign in to FO?

**Comment by salvavidal** [comment]
maked changes in 1.7.7.2.

Now the empty cart is not created when a user login, but last cart is not recovered.

**Comment by Prestaworks** [comment]
> maked changes in 1.7.7.2.
> 
> Now the empty cart is not created when a user login, but last cart is not recovered.

I made a clean install of 1.7.7.2, applied the code and testet to login, the old cart was loaded as expected. (this is also tested in the automatic tests).

**Comment by Prestaworks** [comment]
@Progi1984 and @marwachelly  can you please show me where the issue you mention is reported? I have read all the comments on the ticket and can't see anything about creating orders from BO, all mentions are from customers logging in to FO.

**Comment by kpodemski** [comment]
@marwachelly 

This PR targets the problem in Front Office as described in the Issue. Could you make sure to test it in the Front office instead Back office? This can fix unnecessary data creation on a bigger scale than BO.

**Review by marwachelly — APPROVED** [review]
Hello, 
PR is tested and the issue is fixed when connecting from FO.

https://user-images.githubusercontent.com/89604350/165732630-cbedf316-ce36-4961-b904-aea9b16b44af.mp4

Thanks,

**Review by PululuK — APPROVED** [review]

**Comment by lopezpablodaniel** [comment]
> Hello, PR is tested and the issue is fixed when connecting from FO.
> 
>  Untitled_.Apr.28.2022.11_15.AM.mp4 
> Thanks,

@marwachelly 
Can you test logout and login to check if the product remains in the cart or is lost?
In my case with a new installation, the cart is lost.
Here is the sample: https://www.dropbox.com/s/3s1l4h2nv3so3ec/lost-cart-after-login.gif?dl=0

**Comment by marwachelly** [comment]
> > Hello, PR is tested and the issue is fixed when connecting from FO.
> > Untitled_.Apr.28.2022.11_15.AM.mp4
> > Thanks,
> 
> @marwachelly Can you test logout and login to check if the product remains in the cart or is lost? In my case with a new installation, the cart is lost. Here is the sample: https://www.dropbox.com/s/3s1l4h2nv3so3ec/lost-cart-after-login.gif?dl=0

Hello @lopezpablodaniel,

I didn't reproduce the issue with the PR. Also all UI tests are green.
Could you please try to set the option " Re-display cart at login" to yes (shop parameter > customer settings).

https://user-images.githubusercontent.com/89604350/165913265-478b115d-e074-452a-a0c5-4388714d37f2.mp4

waiting for your feedback,

Thanks,

**Comment by lopezpablodaniel** [comment]
> > > Hello, PR is tested and the issue is fixed when connecting from FO.
> > > Untitled_.Apr.28.2022.11_15.AM.mp4
> > > Thanks,
> > 
> > 
> > @marwachelly Can you test logout and login to check if the product remains in the cart or is lost? In my case with a new installation, the cart is lost. Here is the sample: https://www.dropbox.com/s/3s1l4h2nv3so3ec/lost-cart-after-login.gif?dl=0
> 
> Hello @lopezpablodaniel,
> 
> I didn't reproduce the issue with the PR. Also all UI tests are green. Could you please try to set the option " Re-display cart at login" to yes (shop parameter > customer settings).
> 
>  Untitled_.Apr.29.2022.9_42.AM.mp4 
> waiting for your feedback,
> 
> Thanks,

Hello @marwachelly 
Finally resolved thanks to your advice but that alone didn't resolve it. As an additional, I restarted the statsdata module and activated the first 2 options and now finally, it already maintains the cart after logging out and back in.
Thank you very much!

**Comment by marwachelly** [comment]
> Hello @marwachelly Finally resolved thanks to your advice but that alone didn't resolve it. As an additional, I restarted the statsdata module and activated the first 2 options and now finally, it already maintains the cart after logging out and back in. Thank you very much!

Hello @lopezpablodaniel ,

You are welcome :blush: . So the issue is  QA :heavy_check_mark:.

Thanks,

**Comment by Progi1984** [comment]
Thanks @Prestaworks & @marwachelly

**Comment by marwachelly** [comment]
> @marwachelly
> 
> This PR targets the problem in Front Office as described in the Issue. Could you make sure to test it in the Front office instead Back office? This can fix unnecessary data creation on a bigger scale than BO.

@kpodemski,

An [issue](https://github.com/PrestaShop/PrestaShop/issues/28515) related to the BO problem is created.

Thanks,

**Comment by IlPizza79** [comment]
Hi,  it seems I have the same problem with PS 1.7.8.6.
"Re-display cart at login" is already activated, so what else should I do to prevent empty cart creation at every login?
Thanks!

**Comment by IlPizza79** [comment]
Please, someone let me know if I should open a new issue or I can get help here regarding my issue.
Thanks!

**Comment by kpodemski** [comment]
@IlPizza79 apply the fix from this Pull Request :)

**Comment by IlPizza79** [comment]
Hi @kpodemski you mean I should edit those files?
- classes/Context.php
- classes/controller/FrontController.php
Thanks!

**Comment by lopezpablodaniel** [comment]
> Hi @kpodemski you mean I should edit those files?
> 
> * classes/Context.php
> * classes/controller/FrontController.php
>   Thanks!

Yes, this 2 files: https://github.com/PrestaShop/PrestaShop/pull/27803/files

**Comment by IlPizza79** [comment]
Ok, I've applied the fix from the pull request, and I can see that no more empty cart is created at login.
But the customer cart is still empty after login :-(

Let me try to explain better:
- I login with a sample customer
- I add some product to my cart
- I logout
- I login again with the same customer
- The cart is empty :-(

So, no more empty cart created at login, but the cart is still empty :-(
"Re-display cart at login" is already activated. What else can I try?

Thanks in advance!

**Comment by lopezpablodaniel** [comment]
> Hello @marwachelly Finally resolved thanks to your advice but that alone didn't resolve it. As an additional, I restarted the statsdata module and activated the first 2 options and now finally, it already maintains the cart after logging out and back in. Thank you very much!

@IlPizza79 Check my old answer where I also had to restarted and activate the statsdata module.
With that last change it should work for you.

**Comment by IlPizza79** [comment]
@lopezpablodaniel wow, really thank you for your help, now it's fixed!
But, let me say it's crazy... why does a stat module prevent the normal cart behaviour???
Really, sometimes I'm amazed about things works... 
Anyway, REALLY thank you!

**Comment by lopezpablodaniel** [comment]
@IlPizza79 I normally disable that module because it generates huge tables in the database since they collect all the data of the customers when they visit the sites.
One of the data they store is precisely the id_customer and the id_cart.
With that information retrieves the customer's last active cart.

I'm glad it worked, I've been through the same frustration and there's nothing nicer than giving a problem as "solved".

**Comment by IlPizza79** [comment]
@lopezpablodaniel now statdata module is enabled, but every option is disabled. It seems customer last active card is retrieved even if every option in statdata module is disableb.

But that means I have to keep this module enabled to get customer's last cart?

Anyway, "solved" is one of the nicest words a developer could hear :-D
