### PR TITLE
Fix body classes for content_only and module front controllers

### LINKED ISSUE #29265: Wrong body class is set to module front controller
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you create module front controller, it doesn't use proper body class in the controller. See steps to reproduce.

### Steps to reproduce

1. Install this module [tox_layouttest.zip](https://github.com/PrestaShop/PrestaShop/files/9293465/tox_layouttest.zip)
2. Go to backoffice > **Theme & logo** > bottom of the page **Choose layouts** and check that `category` and `layouttest` pages have both set the same left column layout.
3. Go to any category on your shop, check source code of the page, find `<body>` tag, and see that there is correct `layout-left-column` class on it.
4. Go to `/layouttest` in the front office of your shop, check source code of the page, find `<body>` tag, and see that there is `layout-full-width` instead of `layout-left-column`.

_This is important, because themes use it to style the page. For example to have proper product columns count._

### Cause

See FrontController here:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1677

It tries to get the body class by `php_self`, which is not used by module front controllers and is empty.

It should use `page_name` like in `getLayout` function here:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1299

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

### LINKED ISSUE #29266: Wrong body class is set to when using content_only parameter
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you request content with `?content_only=1`, wrong body class is set. See steps to reproduce.

### Steps to reproduce

1. Get default prestashop installation. It should have CMS pages set with left column.
2. When you inspect source code of any CMS page and check `<body>` tag, it should have `layout-left-column` class.
3. Now add `?content_only=1` to the end of the URL to get only the content. Check source code again.
4. Prestashop will use correct layout `layouts/layout-content-only.tpl`, but the class in body tag will not change and still be `layout-left-column` - wrong :red. It should be `layout-content-only`.

### Cause

See that FrontController applies correct layout TPL file when using content_only here:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1323

But completely ignores it while getting the body class:
https://github.com/PrestaShop/PrestaShop/blob/d1e14ec7b1f959f370915ecb9b34afe28b098e88/classes/controller/FrontController.php#L1677

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Front controller didn't provide correct body classes for styling in case of content_only parameter and custom module front controllers. There are no BC breaks in this PR.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Resolves #29265, resolves #29266
| How to test?      | Test using steps to reproduce in related issues.
| Possible impacts? | no

### Information for devs approving this
There were multiple problems when getting the body class.

Firstly, `$this->context->shop->theme->getLayoutNameForPage` was always called with `$this->php_self` parameter, which is not used in case of module front controllers. We need to use `$this->getPageName()` in that case.

Also, when calling a page with `?content_only=1`, a different layout is used, but this logic was not respected at all when getting the layout for body class purposes.

**Now, there is just one source of truth for the layout name, for any purpose.**

### How to test - module controllers
1. Install this module [tox_layouttest.zip](https://github.com/PrestaShop/PrestaShop/files/9293465/tox_layouttest.zip)
2. Go to backoffice > **Theme & logo** > bottom of the page **Choose layouts** and check that `category` and `layouttest` pages have both set the same left column layout.
3. Go to any category on your shop, check source code of the page, find `<body>` tag, and see that there is correct `layout-left-column` class on it.
4. Go to `/layouttest` in the front office of your shop, check source code of the page, find `<body>` tag, and see that there is `layout-left-column`.
5. Before this PR, there is `layout-full-width` (wrong) instead of `layout-left-column`.

### How to test - content only
1. Get default prestashop installation. It should have CMS pages set with left column.
2. When you inspect source code of any CMS page and check `<body>` tag, it should have `layout-left-column` class.
3. Now add `?content_only=1` to the end of the URL to get only the content. Check source code again.
4. Prestashop will use correct layout `layouts/layout-content-only.tpl`, but the class in body tag will not change and still be `layout-left-column` - wrong :red. It should be `layout-content-only`.
5. Apply this PR, see the issue is gone.

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @PrestaShop/prestashop-maintainers for review

File: src/Core/Addon/Theme/Theme.php [hunk 1]
```diff
@@ -210,9 +217,28 @@ public function getLayoutNameForPage($page)
...
+    }
+
+    /**
+     * Returns full path for provided layout name
+     *
+     * @param string $layout layout name
+     *
+     * @return string layout full path
+     */
+    public function getLayoutRelativePathForLayout($layout)
```
Comment (zuk3975) [inline src/Core/Addon/Theme/Theme.php]: is the naming correct? sounds strange. `Layout{..}ForLayout` :thinking: ?
Also shouldn't it be private or protected?

Comment (Hlavtox) [reply src/Core/Addon/Theme/Theme.php]: I was inspired by `getLayoutRelativePathForPage`, what should I name the function?

Comment (zuk3975) [reply src/Core/Addon/Theme/Theme.php]: looking at what it does, maybe it could be `getLayoutRelativePathByName` or just `getRelativePathForLayout` (this one sounds good for me)? Also maybe the param name could be more precise, like $layoutName. (just suggestions, but you understand better whats hapening here, maybe you could insipre from it and adapt the name accordingly)

File: classes/controller/FrontController.php [hunk 2]
```diff
@@ -1674,7 +1695,7 @@ public function getTemplateVarPage()
             'lang-rtl' => (bool) $this->context->language->is_rtl,
             'country-' . $this->context->country->iso_code => true,
             'currency-' . $this->context->currency->iso_code => true,
-            $this->context->shop->theme->getLayoutNameForPage($this->php_self) => true,
+            $this->getLayoutName() => true,
```
Comment (zuk3975) [inline classes/controller/FrontController.php:1693]: If I understand right, when using `getLayoutNameForPage` it was always providing the default layout, without checking $content_only param, right?

Comment (Hlavtox) [reply classes/controller/FrontController.php:1693]: Yes, exactly.

AND

It was using $this->php_self when calling it, but this parameter is not used for module front controllers.

Comment (kpodemski) [reply classes/controller/FrontController.php:1693]: >It was using $this->php_self when calling it, but this parameter is not used for module front controllers.

https://github.com/prestarocket/morinella/blob/6abd895a45afc0d9383d4012f2a768bc429793e4/modules/leoblog/controllers/front/category.php#L35

Comment (Hlavtox) [reply classes/controller/FrontController.php:1693]: Hmmm, OK, maybe it could be used. But if not, there was no fallback. :-)

File: src/Core/Addon/Theme/Theme.php (hunk 1 above)
Comment (Hlavtox) [reply src/Core/Addon/Theme/Theme.php]: @zuk3975 @kpodemski Naming updated 👍 Ready for review

**Review by zuk3975 — DISMISSED** [review]

File: classes/controller/FrontController.php [hunk 3]
```diff
@@ -1298,15 +1298,31 @@ protected function getThemeDir()
...
+        return $this->context->shop->theme->getLayoutPath($this->getLayoutName());
+    }
+
+    /**
+     * Returns layout name for the current controller.
+     * Modules can override the layout if needed.
+     *
+     * @return string layout name
+     */
+    public function getLayoutName()
```
Comment (jolelievre) [inline classes/controller/FrontController.php]:
```suggestion
    protected function getLayoutName()
```

I do"nt think this needs to be public since it's used internally only, but it can be protected to allow overriding it

File: classes/controller/FrontController.php [hunk 4]
```diff
@@ -1317,11 +1333,15 @@ public function getLayout()
...
+            // Modules can return data with or without the full path
+            // We will strip it if provided
+            $overridden_layout = str_replace(['layouts/', '.tpl'], '', $overridden_layout);
+
             return $overridden_layout;
         }
 
         if ($content_only) {
-            $layout = 'layouts/layout-content-only.tpl';
+            $layout = 'layout-content-only';
```
Comment (jolelievre) [inline classes/controller/FrontController.php:1330]:
```suggestion
            return 'layout-content-only';
```

File: classes/controller/FrontController.php [hunk 5]
```diff
@@ -1317,11 +1333,15 @@ public function getLayout()
                 'content_only' => $content_only,
             ]
         )) {
+            // Modules can return data with or without the full path
+            // We will strip it if provided
+            $overridden_layout = str_replace(['layouts/', '.tpl'], '', $overridden_layout);
```
Comment (jolelievre) [inline classes/controller/FrontController.php]: Since this hook was initially meant to override the layout path, and not the layout name, maybe this should be extracted from this `getLayoutName` and be handled in the `getLayout` method instead These are two different use cases, the hook was never meant to return a layout name

**Review by jolelievre — COMMENTED** [review]
Thanks @Hlavtox 

the modification is legit however you should detail more about the possible impact because it's not as trivial as it seems. Amongst impact I can think of:

- pages previously relied on the class not to change, even if it was a bug it could have impact on some modules or core pages that will need to be fixed after this bugfix is merged
- you changed the module hook override system a bit because you convert the returned value to a layout name, and then convert it again to layout path so there is a convert/unconvert phase that can lead to bugs Also what happens if the module returns a path which is not in the expected `layouts/` folder? This one could be fixed if the hook is kept outside of the `getLayoutName` and remains unchanged as I commented on the file

File: classes/controller/FrontController.php (hunk 5 above)
Comment (Hlavtox) [reply classes/controller/FrontController.php]: @jolelievre Yes, but we will need to get the layout name anyway in this case, so what should we do?

Either just rely on this method of extracting it from path or making another hook for the layout name only - which is a complication.

I think it will be fine, because there are many places in the core that have hardcoded /layouts folder, the structure is solid and won't be changed I think.

**Comment by Hlavtox** [comment]
@jolelievre @atomiix @eternoendless @kpodemski 

Guys, I remade the PR a bit, according to our discussion in weekly meeting. Module now provides only the full path and I use `basename()` function to get the layout name for body class purpose. It will now work correctly even if a module returns completely different path, like `my/custom/layoutsfolder/blabla.tpl`.

Tested, working, fixes both issues in PR description.

**Comment by atomiix** [comment]
Closed/reopened to trigger the CI

**Review by kpodemski — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
It works like a charm with simple shop or multistore :clap: 
Both issues has been fixed with this PR!
LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by kpodemski** [comment]
Thank you @Hlavtox and thank you @hibatallahAouadni for the tests :)
