### PR TITLE
Fixed specific price list in the product editor

### LINKED ISSUE #20021: Catalog Price Rule without condition group doesn't appear in the product editor
#### Describe the bug

When a Catalog Price Rule is created without condition group, this rule is not listed in the Price tab in the product editor.

#### Expected behavior

Display the Catalog Price Rule created.

#### Steps to Reproduce

1. Create a Catalog Price Rule without any condition group
2. Go to the product list and edit some product
3. The Catalog Price Rule created is not listed

**Screenshots**

https://streamable.com/jc22a9

#### Additional information

* PrestaShop version: 1.7.8 / 1.7.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This fix show the hidden specific price created from the Catalog Price Rule when no condition group is applied, and this also fix another error that duplicated the row of the specific price in the database when saving changes to the product.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #20021
| How to test?  | Create a Catalog Price Rule without any condition group. Error video: https://streamable.com/jc22a9

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19968)

### CODE REVIEW

**Comment by Progi1984** [comment]
@Rolige Could you rebase your PR for removing two first commits "Merge" ? Thanks

File: classes/SpecificPriceRule.php [hunk 1]
```diff
@@ -275,14 +275,16 @@ public function getAffectedProducts($products = false)
...
+                if (!SpecificPrice::getByProductId(0, false, false, (int) $this->id)) {
+                    $query = new DbQuery();
+                    $query->select('p.`id_product`')
+                        ->select('NULL as `id_product_attribute`')
+                        ->from('product', 'p')
+                        ->leftJoin('product_shop', 'ps', 'p.`id_product` = ps.`id_product`')
+                        ->where('ps.id_shop = ' . (int) $current_shop_id);
+                    $query->where('p.`id_product` IN (' . implode(', ', array_map('intval', $products)) . ')');
+                    $result = Db::getInstance()->executeS($query);
+                }
```
Comment (Progi1984) [inline classes/SpecificPriceRule.php:287]:
```suggestion
                } else {
                    $result = [['id_product' => 0, 'id_product_attribute' => null]];
                }
```

**Comment by Progi1984** [comment]
@ Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

File: classes/SpecificPriceRule.php (hunk 1 above)
Comment (Rolige) [reply classes/SpecificPriceRule.php:287]: @Progi1984 This is not necessary. The `$products` param is used (according to the method description) to filter the products affected by the `SpecificPriceRule`. So, unless an array(0) is passed as value of the `$products` params, doesn't have sense to return an affected product (id_product => 0) this value is not present on the `$products` params.
Additionally, this method `getAffectedProducts` is only called specifying params on the apply function of the same `SpecificPriceRule` class. It is call previous to creating of specific price to the products list returned. If an specific price is already created with `id_product = 0`, then it is not necessary to create again any other rule for a real product (because an specific price with `id_product = 0` is already affecting all products) or for `id_product = 0` (because is already created). This is the main issue that this PR fixs. In ALL the remaining PrestaShop code, the method `getAffectedProducts` is called without params.

**Comment by Rolige** [comment]
> @Rolige Could you rebase your PR for removing two first commits "Merge" ? Thanks

This is absolutely necessary? Because we are using a unique forked project maintained with upstream. If you have a step by step guide to do this without complications please send us.

**Comment by Rolige** [comment]
> @ Thank you for your contribution. 🤗
> 
> Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
> 
> Thanks 👍

Dona, but I still don't understand why is this necessary, we are repeating the same info.

**Review by matks — DISMISSED** [review]
This PR seems good and the explanations provided by @Rolige are very nice to help.
It's a ✅  for me

File: classes/SpecificPrice.php [hunk 2]
```diff
@@ -188,14 +188,15 @@ public function delete()
         return false;
     }
 
-    public static function getByProductId($id_product, $id_product_attribute = false, $id_cart = false)
+    public static function getByProductId($id_product, $id_product_attribute = false, $id_cart = false, $id_price_rule = false)
```
Comment (PierreRambaud) [inline classes/SpecificPrice.php]:
```suggestion
    public static function getByProductId($id_product, $id_product_attribute = false, $id_cart = false, $id_price_rule = null)
```

File: classes/SpecificPrice.php [hunk 3]
```diff
@@ -188,14 +188,15 @@ public function delete()
...
     {
         return Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
 			SELECT *
 			FROM `' . _DB_PREFIX_ . 'specific_price`
 			WHERE `id_product` = ' . (int) $id_product .
             ($id_product_attribute ? ' AND id_product_attribute = ' . (int) $id_product_attribute : '') . '
-			AND id_cart = ' . (int) $id_cart);
+			AND id_cart = ' . (int) $id_cart .
+            ($id_price_rule ? ' AND id_specific_price_rule = ' . (int) $id_price_rule : ''));
```
Comment (PierreRambaud) [inline classes/SpecificPrice.php]:
```suggestion
            ($id_price_rule !== null ? ' AND id_specific_price_rule = ' . (int) $id_price_rule : ''));
```

File: classes/SpecificPrice.php (hunk 2 above)
Comment (PierreRambaud) [reply classes/SpecificPrice.php]: For a better type hint. Never mix boolean and integer. Prefer a null value instead

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
A little comment about the null value :wink:

**Comment by Rolige** [comment]
> A little comment about the null value 😉

Ok, commit suggestions applied!

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @Rolige !

**Comment by matks** [comment]
Thank you @Rolige ! 6th PR merged 😉  nice record !

**Comment by stickyrst** [comment]
Just pointing out another issues that this solves:
If you have a specific price rule that applies on all products, and then an algorithm calls

SpecificPriceRule::applyAllRules(array((int) $id_product));

Then the algorithm (as it was before) was deleting the line in specific_price with id_product=0 (so it disabled all the reductions on all products, basically, only leaving the reduction on $id_product).

Thanks!
