### PR TITLE
Fix bug related to cache_default_attribute

### LINKED ISSUE #20975: Product price displayed as 0 in category page
#### Describe the bug

The product price is displayed incorrectly on the category page
The original price is **not 0** but the displayed price is 0

#### Expected behavior

The product price should be displayed correctly

Steps to reproduce the issue:
1. Enable multishop context
2. create a new store
3. Create a standard product in all shops
4. select shop1, edit the last product created => generate combinations, 
5. change the combination by default
6. Go to FO > Category page
7. see error

https://drive.google.com/file/d/11FmNrvoC4VHVErmTlyWJlW7SjHqvKbum/view?usp=sharing

1. Enable multishop
2. Add a second shop
3. Switch to second shop
4. Having a product with attributes, delete all its attributes (or make it a "Simple product")
5. Open the product category page, the price will be displayed as 0

**Screenshots**

Expected
localhost_tests_ps_multishop_attribute_en_3-clothes

Actual
localhost_tests_ps_multishop_attribute_second_en_3-clothes

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This solves a bug where 0 is displayed as the product price in the category
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20975
| How to test?  | - Enable multishop and add a new shop<br>- Switch to the new shop<br>- Pick a product with attributes and make it a "Simple product", thus deleting all its attributes for the new shop<br>- Open the product category page, the price is 0 and the image is wrong

More details:
The query is returning `cache_default_attribute` from `product` not from `product_shop`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20964)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
@unlocomqx Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

File: classes/ProductAssembler.php [hunk 1]
```diff
@@ -67,25 +67,29 @@ private function addMissingProductFields(array $rawProduct)
...
                     AND pl.id_lang = $idLang
                 LEFT JOIN {$prefix}stock_available sa
-			        ON sa.id_product = p.id_product 
+			        ON sa.id_product = p.id_product
 			        AND sa.id_shop = $idShop
-			    WHERE p.id_product = $idProduct LIMIT 1";
+                LEFT JOIN {$prefix}product_shop ps
+			        ON ps.id_product = p.id_product
+			        AND ps.id_shop = $idShop
+			    WHERE p.id_product = $idProduct";
```
Comment (Progi1984) [inline classes/ProductAssembler.php]:
```suggestion
			    WHERE p.id_product = $idProduct
			    LIMIT 1";
```

Comment (unlocomqx) [reply classes/ProductAssembler.php:92]: The limit 1 is not needed because it's selecting from ps_product with a specific id_product. I don't think it's necessary

Comment (unlocomqx) [reply classes/ProductAssembler.php]: Done

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello,

This PR is currently blocked by this issue: 
https://github.com/PrestaShop/PrestaShop/issues/9664

Thank you

**Comment by unlocomqx** [comment]
@ngodefroy You can still repro by following these steps, no error 500
https://github.com/PrestaShop/PrestaShop/issues/20975#issuecomment-692067852

**Comment by ngodefroy** [comment]
Hello @unlocomqx ,

Following the test steps:
Enable multishop and add a new shop
- Switch to the new shop
- Pick a product with attributes and make it a "Simple product", thus deleting all its attributes for the new shop
- Open the product category page, the price is 0 and the image is wrong

==> Now the price & image is correct. 
https://drive.google.com/file/d/1PgYF4w6NzTurqF3fvm8v_gyN4OQ-xOMV/view

Thank you

**Comment by unlocomqx** [comment]
@ngodefroy I'm a bit confused. Is it working correctly after applying the fix or without applying the fix?

**Comment by Progi1984** [comment]
Thanks @unlocomqx & @ngodefroy
