### PR TITLE
Order view - Refresh shipping tab when product is added, removed or updated

### LINKED ISSUE #21267: BO - Order page - Recalculate shipping costs option enabled - the Shipping price not instantly updated
#### Describe the bug

When setting the "Recalculate shipping costs after editing the order" option to Yes, the shipping cost are recalculated when editing the order in BO when the price of the order exceeds the carrier's "limit" but not instantly, we need to refresh the page
image

When we **refresh** the page
image

#### Steps to Reproduce

1. Have a carrier set up with a fee below a certain amount, free above it (For example "My Cheap carrier")
image
2. Go to BO > Shop Parameters > Order Settings
3. Set "Recalculate shipping costs after editing the order" to Yes
4. On FO, make an order with this carrier, under the limit amount
5. On BO, edit the order to make it exceed the limit

#### Additional information

* PrestaShop version: 1770rc1
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Refresh shipping tab when product list changed
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21267 
| How to test?  | See description of #21267. Test cases when a product is added, removed or has quantity, price updated. Test cases with cart rules

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22367)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/view/order-shipping-refresher.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+const $ = window.$;
+
+export default class OrderShippingRefresher {
+    constructor() {
+        this.router = new Router();
+    }
+
+    refresh(orderId) {
+        $.ajax(this.router.generate('admin_orders_get_shipping', {orderId}))
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/view/order-shipping-refresher.js]:
```suggestion
        $.getJSON(this.router.generate('admin_orders_get_shipping', {orderId}))
```

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @sowbiba 
Everything looks good to me except for this little point:
With you PR when we edit an order the "payment block" is not correctly updated anymore without a page refresh (it was before the PR)

**screenrecords**
Without PR:
https://drive.google.com/file/d/1RGEqtwpdK9MO-Mz5dxaUr9PGAE5g8XzT/view?usp=sharing
With PR:
https://drive.google.com/file/d/1xza1Zq6EiJm_dK4reWkOfxf7SVDSE7fn/view?usp=sharing

File: admin-dev/themes/new-theme/js/pages/order/view/order-shipping-refresher.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+import Router from '@components/router';
+import OrderViewPageMap from '@pages/order/OrderViewPageMap';
+import InvoiceNoteManager from '../invoice-note-manager';
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/view/order-shipping-refresher.js]:
```suggestion
import InvoiceNoteManager from '@pages/order/invoice-note-manager';
```
Avoid relatives paths

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 3]
```diff
@@ -809,6 +809,24 @@ public function getDocumentsAction(int $orderId)
         ]);
     }
 
+    /**
+     * @AdminSecurity("is_granted(['create', 'update'], request.get('_legacy_controller'))", redirectRoute="admin_orders_index")
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Should be `view` because of `GetOrderForViewing` otherwise, something is confusing

File: admin-dev/themes/new-theme/js/pages/order/view/order-shipping-refresher.js (hunk 2 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-shipping-refresher.js]: Not used anyway. Bad copy/paste. I removed the import ;)

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 3 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: I fix the other 2 actions to use `read`
Nice catch

**Comment by sowbiba** [comment]
> Hi @sowbiba
> Everything looks good to me except for this little point:
> With you PR when we edit an order the "payment block" is not correctly updated anymore without a page refresh (it was before the PR)
> 
> **screenrecords**
> Without PR:
> https://drive.google.com/file/d/1RGEqtwpdK9MO-Mz5dxaUr9PGAE5g8XzT/view?usp=sharing
> With PR:
> https://drive.google.com/file/d/1xza1Zq6EiJm_dK4reWkOfxf7SVDSE7fn/view?usp=sharing

Fixed

It's because I changed $.ajax by $.getJSON

```
$.ajax(
  .then(
     response => {}, //case success
     response => {}, //case error
  )
)
```
$.getJSON doesn't work this way
You have to specify

```
$.getJSON()
.done()
.fail()
```

**Review by atomiix — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
LGTM now !!
Tested :

- initial issue
- add product
- delete product
- edit product quantity
- edit product price
- add discount ( % and amount)
- add free shipping

Thanks @sowbiba !!

**Comment by matks** [comment]
Merge can happen after conflicts are solved 😉  ping @sowbiba

**Comment by sowbiba** [comment]
Rebase done

I changed the milestone too

**Review by Progi1984 — CHANGES_REQUESTED** [review]
## DONT MERGE BEFORE RELEASE 1.7.7.1

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sowbiba & @SD1982
