### PR TITLE
Fix product access in BO when seo redirection related entity is deleted

### LINKED ISSUE #39290: Inaccessible product if redirected to a deleted product
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you redirect a product with the seo settings and then delete the product that you have redirected to, the old product will not be accessible any more.

### Expected behavior

If a product is deleted, products that where redirected to this product should still be accessible.

### Steps to reproduce

1. Go to a product 19 (demo_14) in Backoffice
2. Open SEO tab, set this to redirect to another product (302), select product 18 (demo_10)
3. save changes
4. Go back to product list.
5. Delete product 18 from the shop.
6. open product 19

### PrestaShop version(s) where the bug happened

9.0.0

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

prestaworks

### PR DESCRIPTION
**Pull request by aomaxime**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Fix product access in BO when seo redirection related entity is deleted
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go to product A in BO, add a redirection to product B in seo tab, delete product B, you can access to product A
| Fixed issue or discussion?     | Fixes #39290
| Sponsor company   | Agence Off

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @aomaxime!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by Hlavtox — DISMISSED** [review]

File: classes/Product.php [hunk 1]
```diff
@@ -1297,13 +1297,27 @@ public function delete()
...
     }
 
+    /**
+     * Delete all association to products where this product is indexed.
+     *
+     * @return bool
+     */
+    public function deleteRedirections()
+    {
+        $result1 = Db::getInstance()->update('product', ['redirect_type' => 'default', 'id_type_redirected' => 0], '(redirect_type = "302-product" OR redirect_type = "301-product") AND id_type_redirected = '. (int) $this->id);
```
Comment (FabienPapet) [inline classes/Product.php]: I think you should use some constants instead of hardcoded strings for better maintenance

[PrestaShop\PrestaShop\Core\Domain\Product\ValueObject\RedirectType;](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Product/ValueObject/RedirectType.php)

File: classes/Product.php [hunk 2]
```diff
@@ -1297,13 +1297,27 @@ public function delete()
...
 
         return true;
     }
 
+    /**
+     * Delete all association to products where this product is indexed.
+     *
+     * @return bool
+     */
+    public function deleteRedirections()
```
Comment (FabienPapet) [inline classes/Product.php]:
```suggestion
    public function deleteRedirections(): bool
```

**Review by FabienPapet — CHANGES_REQUESTED** [review]

**Comment by Hlavtox** [comment]
And please target 9.0.x do we can get the fix early

**Comment by aomaxime** [comment]
> And please target 9.0.x do we can get the fix early

Did I do it the right way ?

**Comment by Hlavtox** [comment]
@aomaxime On github, yes, but you must also rebase the PR on that branch.

I can do it for you if needed.

**Comment by aomaxime** [comment]
> @aomaxime On github, yes, but you must also rebase the PR on that branch.
> 
> I can do it for you if needed.

If you can do it, or explain me how to do it and the reason it would be great. I'm relatively new to all this colaboration ecosystem

**Comment by boherm** [comment]
Hi @aomaxime,
You have to rebase your `aomaxime:fix-product-delete-redirection-seo` branch because instead of merge only your commit, we merge other commits that are between our 9.0.x branch and the branch that you use for begin your branch `aomaxime:fix-product-delete-redirection-seo`. And We don't want theses commits to be in 9.0.x branch!

If we merge your PR as is, we merge 625 and not only your work:
Capture d’écran 2025-08-12 à 09 43 12

So yep, you need also to rebase your branch to our 9.0.x branch and maybe also fix some conflicts too 🤔

**Comment by aomaxime** [comment]
@boherm Sorry I think I messed up :(

Maybe the best option for me would be to close this PR, start from scratch on the 9.0.x branch and do another PR without all these old commits.

My work contained only a few lines of code so I can re-do it quick.

Or is still possible to fix my work ?

**Comment by FabienPapet** [comment]
This is possible without closing and reopening the PR with some git interactive rebase. 

Give it a try, you may learn a lot 😊

**Comment by Hlavtox** [comment]
@aomaxime @FabienPapet Should be good now. :-)

**Comment by aomaxime** [comment]
> @aomaxime @FabienPapet Should be good now. :-)

Thank you, what was I missing ? I did a rebase from 9.0.x + fixed all the conflicts but seems it wasn't enought

**Comment by FabienPapet** [comment]
You need to fix formatting and then it's all good

**Review by FabienPapet — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @aomaxime,

I tested your PR and it's good for me!

Thanks!

https://github.com/user-attachments/assets/bb600d11-a6b6-4b8f-ba20-cd6976d51f9f

Automated test : https://github.com/paulnoelcholot/testing_pr/actions/runs/16961941220

**Review by paulnoelcholot — APPROVED** [review]
