### PR TITLE
Fix grid calendar

### LINKED ISSUE #14301: Customer details page is not well displayed - BO
**Describe the bug**
In the BO => customers page, when you try to add or edit a customer, the customer details page is not well displayed.
image

With PS1.7.6.0beta1 => OK

**To Reproduce**
1. Go to BO => Customers page
2. Add/Edit a customer
3. See error

**Additionnal information**
PrestaShop version: branch 1.7.6.x
PHP version: 7.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Remove special case for customers, instead fix overflow on tables and fix calendar cropping properly
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14301 and #14275
| How to test?  | Test customer page on low resolution, the scrollbar is now on the table not the whole page (bootstrap default behavior). Test the calendar, it must display correctly above the grid (even after a resize).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14401)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/app/utils/datepicker.js [hunk 1]
```diff
@@ -33,7 +33,38 @@ const init = function initDatePickers() {
...
-  });
+  })
+  .on('dp.show', replaceDatePicker)
+  .on('dp.hide', function() {
+    $(window).off('resize', replaceDatePicker);
+  })
+  ;
+
+  function replaceDatePicker() {
+    var datepicker = $('body').find('.bootstrap-datetimepicker-widget:last');
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/app/utils/datepicker.js]:
```suggestion
    const datepicker = $('body').find('.bootstrap-datetimepicker-widget:last');
```

File: admin-dev/themes/new-theme/js/app/utils/datepicker.js [hunk 2]
```diff
@@ -33,7 +33,38 @@ const init = function initDatePickers() {
...
+    var position = datepicker.offset(),
+      originalHeight = datepicker.outerHeight(),
+      margin = (datepicker.outerHeight(true) - datepicker.outerHeight()) / 2
+    ;
+
+    // Move datepicker to the exact same place it was but attached to body
+    datepicker.appendTo('body');
+
+    //Height changed because the css from column-filters is not applied any more
+    var top = position.top + originalHeight - margin - datepicker.outerHeight();
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/app/utils/datepicker.js]:
```suggestion
    const top = position.top + originalHeight - margin - datepicker.outerHeight();
```

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @jolelievre
