### PR TITLE
Fix quantity check when there a customization in cart

### LINKED ISSUE #32233: Incorrect count of the quantity of a customized product in the cart.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If an product has 3 available quantities and has a text field for customization (not mandatory), by adding the customized product to the cart, it is also possible to add 3 non-customized ones.
This occurs because the system for calculating the quantity of the item in the cart does not count the customization.
I attach a video

https://user-images.githubusercontent.com/2463965/233431462-45f4394d-ca31-4241-ba3f-2a00e6ff6207.mp4

https://user-images.githubusercontent.com/2463965/233431471-9646ac18-0fea-4a40-8979-f18afcb3687b.mp4

https://user-images.githubusercontent.com/2463965/233431476-9fc0336a-541a-4db2-97ec-9483547c86a3.mp4

### Expected behavior

The system should add a maximum of 3 quantities of the article, thus also verifying the personalized article

### Steps to reproduce

In a fresh installation of Prestashop:
1. Modify article ID 19 by setting quantity 3 and setting the non-mandatory customization field (Options > Customization tab).
2. Go to the product in fronoffice.
3. Fill the personalization field.
4. Save customization.
5. Add the newly customized product to cart.
6. Add 3 quantities of the product (non-customized) to the cart.
7. At this point we have 4 units of item ID 19 in the cart when there are only 4 available.

### PrestaShop version(s) where the bug happened

1.7.x 8.0.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes related to customization quantity checks
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Add a product with customization then another without. The total quantity in cart that is checked against the available stock must be the total of the product and the separate quantities of the customized and the normal product. See #32233
| Fixed ticket?     | Fixes #32233
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/32292
| Sponsor company   | --

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

File: classes/Cart.php [hunk 1]
```diff
@@ -1355,24 +1355,23 @@ public function addCartRule($id_cart_rule, bool $useOrderPrices = false)
...
     {
-        $productIsPack = Pack::isPack($idProduct);
         $defaultPackStockType = Configuration::get('PS_PACK_STOCK_TYPE');
         $packStockTypesAllowed = [
             Pack::STOCK_TYPE_PRODUCTS_ONLY,
             Pack::STOCK_TYPE_PACK_BOTH,
         ];
         $packStockTypesDefaultSupported = (int) in_array($defaultPackStockType, $packStockTypesAllowed);
-        $firstUnionSql = 'SELECT cp.`quantity` as first_level_quantity, 0 as pack_quantity
+        $firstUnionSql = 'SELECT SUM(cp.`quantity`) as first_level_quantity, 0 as pack_quantity
```
Comment (matks) [inline classes/Cart.php:1373]: This is a risky change, I'm very worried 😅 that introducing this SUM() here would modify how items are counted in another scenario.

That being said
- we have QA to explore this
- we have a CI test suite

**Review by matks — DISMISSED** [review]
I am afraid of possible side-effects but I believe it would be catched by more exploration 👍 so let's go forward

File: classes/Cart.php (hunk 1 above)
Comment (unlocomqx) [reply classes/Cart.php:1373]: I should've documented that change because it's tricky. I will add more info. 

The reason is that the query can now return multiple rows when `id_customization` filtering is skipped. It used to only return one row as `id_customization` is unique.

**Review by matks — APPROVED** [review]
Way better ;) thank you

**Review by matks — APPROVED** [review]
Way better ;) thank you

**Review by jolelievre — APPROVED** [review]
Thanks @unlocomqx

**Comment by jolelievre** [comment]
Running whole campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4940581232

**Review by djoelleuch — APPROVED** [review]
Hello @unlocomqx ,

I have checked your PR , the issue is well fixed as you can see : 

[customize.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/63775103-8055-4743-b7e3-2c45a85858c5)


Automated tests --> OK (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4959321552/jobs/8873263857)

It's QA approved :heavy_check_mark:

Thank you !

**Comment by kpodemski** [comment]
thanks @unlocomqx 🎉

**Comment by unlocomqx** [comment]
Thank you @kpodemski, @jolelievre and @djoelleuch 

Glad to contribute
