### PR TITLE
Improve preview and test mail feature, improve and fix a few templates

### LINKED ISSUE #13433: New order_conf email isn't correctly displayed
**Describe the bug**
New order conf email isn't correctly displayed

**To Reproduce**
1. Order a product and change the order status to payment accepted
2. Check the order conf mail received

**Screenshots**

capture d'écran_1405

capture d'écran_1404

capture d'écran_1403

**Before**

capture d'écran_1406

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Product emails had integration issues with the product list (other few templates had bugs). Twig uses condition on template type to adapt html/txt elements. And the preview feature has been improved to allow debugging more easily.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13433 and #13424 and #13582
| How to test?  | Try to order an article and check that the email is correctly integrated. (Try with modern and classic themes). Bonus: also check the `ps_emailalerts` module emails.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13481)

### CODE REVIEW

**Review by tomlev — CHANGES_REQUESTED** [review]
> Reviewed 22 of 24 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13481)* status: all files reviewed, 1 unresolved discussion (waiting on @jolelievre)

___
*[src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php, line 123 at r2](https://reviewable.io/reviews/prestashop/prestashop/13481#-LcpZwlf-Gyrjv-hP1ad:-LcpZwlg-X_Mu5a8_g6G:boys27z) ([raw file](https://github.com/prestashop/prestashop/blob/2d4032eca26229f3d33d14b641b85abb57a83fc6/src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php#L123)):*
> ```PHP
>         $order = new Order($orders[0]['id_order']);
> 
>         if ('order_conf' == $mailLayout->getName()) {
> ```

could you please set these strings (this one and following 'ps_emailalerts', 'new_order' ...) into constants ?

File: src/Core/MailTemplate/Transformation/HTMLCleanTransformation.php [hunk 1]
```diff
@@ -30,6 +30,10 @@
 use Symfony\Component\DomCrawler\Crawler;
 use DOMElement;
 
+/**
+ * Class HTMLCleanTransformation removes element deisgned for txt templates (identified via data-text-only=1)
```
Comment (matks) [inline src/Core/MailTemplate/Transformation/HTMLCleanTransformation.php]: `deisgned` => `designed`

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php [hunk 2]
```diff
@@ -242,6 +249,109 @@ public function previewThemeAction(Request $request, $themeName)
...
+     * @throws InvalidArgumentException
+     */
+    public function sendTestMailAction($theme, $layout, $locale, $module = '')
+    {
+        if ($this->configuration->get('PS_MAIL_THEME') !== $theme) {
+            $this->addFlash(
+                'error',
+                $this->trans(
+                    'Cannot send test email for theme %theme% because it is not your current theme',
+                    'Admin.Notifications.Success',
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: Are we sure of the localization here? I would have put it in _Admin.Notifications.Error_ instead, no?

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php [hunk 3]
```diff
@@ -242,6 +249,109 @@ public function previewThemeAction(Request $request, $themeName)
...
+        /** @var ContextEmployeeProviderInterface $employeeProvider */
+        $employeeProvider = $this->get('prestashop.adapter.data_provider.employee');
+        $employeeData = $employeeProvider->getData();
+
+        /** @var LanguageRepositoryInterface $languageRepository */
+        $languageRepository = $this->get('prestashop.core.admin.lang.repository');
+        /** @var LanguageInterface $language */
+        $language = $languageRepository->getOneByLocaleOrIsoCode($locale);
+        if (null === $language) {
+            throw new InvalidArgumentException(sprintf('Cannot find Language with locale or isoCode %s', $locale));
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php:299]: Is it a translation key? If yes, it needs to be localized. :-)

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php [hunk 4]
```diff
@@ -242,6 +249,109 @@ public function previewThemeAction(Request $request, $themeName)
...
+                        '%email%' => $employeeData['email'],
+                    ]
+                )
+            );
+        } else {
+            $this->addFlash(
+                'error',
+                $this->trans(
+                    'Cannot send test email for layout %layout%',
+                    'Admin.Notifications.Success',
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: Same than previous. ;-)

File: src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig [hunk 5]
```diff
@@ -90,6 +93,10 @@
                               <i class="material-icons">subject</i>
                               {{ 'Text'|trans({}, 'Admin.Design.Feature') }}
                             </a>
+                            <a class="btn tooltip-link dropdown-item" href="{{ mailUrl }}">
+                              <i class="material-icons">email</i>
+                              {{ 'Send a test email'|trans({}, 'Admin.Design.Feature') }}
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig]: It already exists in _Admin.Advparameters.Feature_, let's avoid duplication and use the same key. ;-)

File: tests/Unit/Core/MailTemplate/MailVariablesTransformationTest.php [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+        $transformation = new MailVariablesTransformation(MailTemplateInterface::HTML_TYPE);
+        $layoutVariables = [
+            'templateVars' => [
+                '{firstname}' => 'John',
+                '{lastname}' => 'Doe',
+                'how are you' => 'wasup mate',
+                ],
+        ];
+        $transformedTemplate = $transformation->apply($template, $layoutVariables);
+        $this->assertEquals('Hello John Doe wasup mate?', $transformedTemplate);
```
Comment (LouiseBonnard) [inline tests/Unit/Core/MailTemplate/MailVariablesTransformationTest.php:56]: Ah! Ah! So thug!

File: tests/Unit/Resources/mails/html/clean-account.html [hunk 7]
```diff
@@ -0,0 +1,109 @@
...
+  <td class="space_footer" style="padding: 0;"> </td>
+</tr>
+<tr>
+  <td class="box" style="background-color: #f8f8f8; border: 1px solid #D6D4D4;" bgcolor="#f8f8f8">
+    <table class="table" style="width: 100%;" width="100%">
+      <tr>
+        <td width="10"> </td>
+        <td>
+          <font size="2" face="Open-sans, sans-serif" color="#555454">
+            <p style="margin: 3px 0 7px 0; text-transform: uppercase; font-weight: 500; font-size: 18px; padding-bottom: 10px; border-bottom: 1px solid #D6D4D4;">Important Security Tips:</p>
```
Comment (LouiseBonnard) [inline tests/Unit/Resources/mails/html/clean-account.html]: Same here; if it needs to be translated, the whole paragraph should be localized. Let me know!

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: Nice catch!

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php (hunk 3 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php:299]: This is an exception message not an error message As it's not designed to be displayed it's not useful to translate this one.

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php (hunk 4 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: Right

File: src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig]: Ok, it's juste that it might be weird to mix the domains in the same page no?

File: tests/Unit/Resources/mails/html/clean-account.html (hunk 7 above)
Comment (jolelievre) [reply tests/Unit/Resources/mails/html/clean-account.html]: This is a test file, so not too important But it was removed anyway so everything is fine ^^

File: src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig (hunk 5 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig]: Well, it is often the case actually, and I have always heard that the good practice was to avoid duplicating same translation strings so I guess it is better to use _Admin.Advparameters.Feature_ this time.

**Review by jolelievre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13481)* status: 14 of 74 files reviewed, 8 unresolved discussions (waiting on @LouiseBonnard, @matks, and @tomlev)

___
*[src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php, line 123 at r2](https://reviewable.io/reviews/prestashop/prestashop/13481#-LcpZwlf-Gyrjv-hP1ad:-LdEVS5R7VSo6MELOEv7:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/2d4032eca26229f3d33d14b641b85abb57a83fc6/src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php#L123)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

could you please set these strings (this one and following 'ps_emailalerts', 'new_order' ...) into constants ?
</blockquote></details>

Done.
___
*[src/Core/MailTemplate/Transformation/HTMLCleanTransformation.php, line 34 at r2](https://reviewable.io/reviews/prestashop/prestashop/13481#-LclaDd16r-aTkY1qPVL-r2-34:-LdEVWsGAl-eshJZlUbp:b9ked1p) ([raw file](https://github.com/prestashop/prestashop/blob/2d4032eca26229f3d33d14b641b85abb57a83fc6/src/Core/MailTemplate/Transformation/HTMLCleanTransformation.php#L34)):*
<details><summary><i>Previously, matks (Mathieu Ferment) wrote…</i></summary><blockquote>

`deisgned` => `designed`
</blockquote></details>

The class was removed
___
*[src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig, line 98 at r3](https://reviewable.io/reviews/prestashop/prestashop/13481#-LclaDd2FfFbzUDf0lx0-r3-98:-LdEVliZ1bpns2qK-bRh:bsg88t4) ([raw file](https://github.com/prestashop/prestashop/blob/26e4b56f2abcd334371f5def04f10f83c6422db9/src/PrestaShopBundle/Resources/views/Admin/Improve/Design/MailTheme/Blocks/list_mail_theme_layouts.html.twig#L98)):*
<details><summary><i>Previously, LouiseBonnard wrote…</i></summary><blockquote>

Well, it is often the case actually, and I have always heard that the good practice was to avoid duplicating same translation strings so I guess it is better to use _Admin.Advparameters.Feature_ this time.
</blockquote></details>

Alright, juste wanted to be sure :)
___
*[tests/Unit/Core/MailTemplate/MailVariablesTransformationTest.php, line 56 at r3](https://reviewable.io/reviews/prestashop/prestashop/13481#-LcpV0_32OINYxtgAEX2-r3-56:-LdEW1Cl7mcCIuM_jC30:b-1ba52h) ([raw file](https://github.com/prestashop/prestashop/blob/26e4b56f2abcd334371f5def04f10f83c6422db9/tests/Unit/Core/MailTemplate/MailVariablesTransformationTest.php#L56)):*
<details><summary><i>Previously, LouiseBonnard wrote…</i></summary><blockquote>

Ah! Ah! So thug!
</blockquote></details>

In tests we can :D

File: mails/themes/classic/core/cheque.html.twig [hunk 8]
```diff
@@ -19,9 +19,13 @@
...
-            <p data-html-only="1" style="border-bottom:1px solid #D6D4D4;">
-              {{ 'Order {order_name}'|trans({}, 'Emails.Body', locale) }}&nbsp;-&nbsp;{{ 'Awaiting check payment'|trans({}, 'Emails.Body', locale)|raw }}
-            </p>
+            {% if templateType == 'html' %}
+
+              <p style="border-bottom:1px solid #D6D4D4;">
+                {{ 'Order {order_name}'|trans({}, 'Emails.Body', locale) }}&nbsp;-&nbsp;{{ 'Awaiting check payment'|trans({}, 'Emails.Body', locale)|raw }}
+              </p>
+            
+{% endif %}
```
Comment (PierreRambaud) [inline mails/themes/classic/core/cheque.html.twig:28]: indent

File: mails/themes/classic/core/cheque.html.twig [hunk 9]
```diff
@@ -46,10 +50,16 @@
...
-              {{ 'Here are the bank details for your check:'|trans({}, 'Emails.Body', locale)|raw }}<br />
-              <span><strong>{{ 'Amount:'|trans({}, 'Emails.Body', locale)|raw }}</strong></span> {total_paid}<br />
-              <span><strong>{{ 'Payable to the order of:'|trans({}, 'Emails.Body', locale)|raw }}</strong></span> {check_name}<br />
-              <span><strong>{{ 'Please mail your check to:'|trans({}, 'Emails.Body', locale)|raw }}</strong></span> <html-only>{check_address_html}</html-only> <span data-text-only='1'>{check_address}</span>
+              {{ 'Here are the bank details for your check:'|trans({}, 'Emails.Body', locale)|raw }}<br/>
+              <span><strong>{{ 'Amount:'|trans({}, 'Emails.Body', locale)|raw }}</strong></span> {total_paid}<br/>
+              <span><strong>{{ 'Payable to the order of:'|trans({}, 'Emails.Body', locale)|raw }}</strong></span> {check_name}<br/>
+              <span><strong>{{ 'Please mail your check to:'|trans({}, 'Emails.Body', locale)|raw }}</strong></span>
+              {% if templateType == 'html' %}
+{check_address_html}
```
Comment (PierreRambaud) [inline mails/themes/classic/core/cheque.html.twig:58]: indent

File: mails/themes/classic/core/credit_slip.html.twig [hunk 10]
```diff
@@ -18,9 +18,13 @@
...
-            <p data-html-only="1" style="border-bottom:1px solid #D6D4D4;">
-              {{ 'Order {order_name}'|trans({}, 'Emails.Body', locale) }}&nbsp;-&nbsp;{{ 'Credit slip created'|trans({}, 'Emails.Body', locale)|raw }}
-            </p>
+            {% if templateType == 'html' %}
+
+              <p style="border-bottom:1px solid #D6D4D4;">
+                {{ 'Order {order_name}'|trans({}, 'Emails.Body', locale) }}&nbsp;-&nbsp;{{ 'Credit slip created'|trans({}, 'Emails.Body', locale)|raw }}
+              </p>
+            
+{% endif %}
```
Comment (PierreRambaud) [inline mails/themes/classic/core/credit_slip.html.twig:27]: indent

File: mails/themes/classic/core/download_product.html.twig [hunk 11]
```diff
@@ -19,9 +19,13 @@
...
-            <p data-html-only="1" style="border-bottom:1px solid #D6D4D4;">
-              {{ 'Product(s) now available for download'|trans({}, 'Emails.Body', locale)|raw }}
-            </p>
+            {% if templateType == 'html' %}
+
+              <p style="border-bottom:1px solid #D6D4D4;">
+                {{ 'Product(s) now available for download'|trans({}, 'Emails.Body', locale)|raw }}
+              </p>
+            
+{% endif %}
```
Comment (PierreRambaud) [inline mails/themes/classic/core/download_product.html.twig:28]: indent (check everywhere :p)

File: mails/themes/classic/core/cheque.html.twig (hunk 8 above)
Comment (jolelievre) [reply mails/themes/classic/core/cheque.html.twig:28]: These templates are generated with a tool https://github.com/jolelievre/ps_convert_templates

So manually changing the indentation wold create an offset with the tool's output
And adding a proper indentation management in the tool seems overrated as this theme is the classic one which should not be used much in the future

Comment (PierreRambaud) [reply mails/themes/classic/core/cheque.html.twig:28]: Le fu!

Comment (jolelievre) [reply mails/themes/classic/core/cheque.html.twig:28]: What? "Le fu!" ?

Comment (PierreRambaud) [reply mails/themes/classic/core/cheque.html.twig:28]: https://www.google.fr/search?q=le+fu+meme&source=lnms&tbm=isch&sa=X&ved=0ahUKEwin--e_gfDhAhX2BGMBHXRHAt4Q_AUIDigB&biw=1920&bih=937 😄

**Review by tomlev — COMMENTED** [review]
> Reviewed 10 of 12 files at r3, 45 of 51 files at r4, 7 of 7 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13481)* status: all files reviewed, 11 unresolved discussions (waiting on @jolelievre, @LouiseBonnard, and @matks)

**Review by jolelievre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13481)* status: all files reviewed, 11 unresolved discussions (waiting on @LouiseBonnard, @matks, and @PierreRambaud)

___
*[mails/themes/classic/core/cheque.html.twig, line 28 at r5](https://reviewable.io/reviews/prestashop/prestashop/13481#-LdACWiOHyW1RGNPcVu0-r5-28:-LdidTXaDAG101JBcd3H:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/c673080e7a579bdcc71d01f0dfeb925e1a98b6ff/mails/themes/classic/core/cheque.html.twig#L28)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

https://www.google.fr/search?q=le+fu+meme&source=lnms&tbm=isch&sa=X&ved=0ahUKEwin--e_gfDhAhX2BGMBHXRHAt4Q_AUIDigB&biw=1920&bih=937 😄 
</blockquote></details>

Done.
___
*[mails/themes/classic/core/cheque.html.twig, line 58 at r5](https://reviewable.io/reviews/prestashop/prestashop/13481#-LdACWiOHyW1RGNPcVu0-r5-58:-LdidYPTD_vbNwMExErl:bdm2gga) ([raw file](https://github.com/prestashop/prestashop/blob/c673080e7a579bdcc71d01f0dfeb925e1a98b6ff/mails/themes/classic/core/cheque.html.twig#L58)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

indent
</blockquote></details>

This is generated code, not sure it's worth improving the generator for this.
___
*[mails/themes/classic/core/credit_slip.html.twig, line 27 at r5](https://reviewable.io/reviews/prestashop/prestashop/13481#-LdBtmE5CTB3_-CaspZX-r5-27:-Ldiddfs8n9X-FQHa_Zs:b-pb2q8a) ([raw file](https://github.com/prestashop/prestashop/blob/c673080e7a579bdcc71d01f0dfeb925e1a98b6ff/mails/themes/classic/core/credit_slip.html.twig#L27)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

indent
</blockquote></details>

 This is generated code, not sure it's worth improving the generator for this.
___
*[mails/themes/classic/core/download_product.html.twig, line 28 at r5](https://reviewable.io/reviews/prestashop/prestashop/13481#-LdBtmE6ncpd3kYlwabs-r5-28:-LdidfWx1nPOnMiYsRPU:bdm2gga) ([raw file](https://github.com/prestashop/prestashop/blob/c673080e7a579bdcc71d01f0dfeb925e1a98b6ff/mails/themes/classic/core/download_product.html.twig#L28)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

indent (check everywhere :p)
</blockquote></details>

This is generated code, not sure it's worth improving the generator for this.
___
*[src/Core/MailTemplate/Transformation/HTMLCleanTransformation.php, line 34 at r2](https://reviewable.io/reviews/prestashop/prestashop/13481#-LclaDd16r-aTkY1qPVL-r2-34:-LdidhFe3wKceioWE3Ve:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/2d4032eca26229f3d33d14b641b85abb57a83fc6/src/Core/MailTemplate/Transformation/HTMLCleanTransformation.php#L34)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

The class was removed
</blockquote></details>

Done.
___
*[src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php, line 280 at r3](https://reviewable.io/reviews/prestashop/prestashop/13481#-LclaDd16r-aTkY1qPVO-r3-280:-Ldidixn5c0klirQyl_z:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/26e4b56f2abcd334371f5def04f10f83c6422db9/src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php#L280)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

Nice catch!
</blockquote></details>

Done.
___
*[src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php, line 299 at r3](https://reviewable.io/reviews/prestashop/prestashop/13481#-LclaDd16r-aTkY1qPVO-r3-299:-LdidkK2DKIbMYOyZCoA:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/26e4b56f2abcd334371f5def04f10f83c6422db9/src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php#L299)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

This is an exception message not an error message As it's not designed to be displayed it's not useful to translate this one.
</blockquote></details>

Done.

**Review by tomlev — DISMISSED** [review]
> Reviewed 1 of 51 files at r4.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13481)* status: all files reviewed, 11 unresolved discussions (waiting on @LouiseBonnard, @matks, and @PierreRambaud)

**Comment by sarahdib** [comment]
@jolelievre 

the size and image problem are not solved

Capture d’écran 2019-05-07 à 09 42 08
Capture d’écran 2019-05-07 à 09 42 `17

**Comment by jolelievre** [comment]
@sarahdib The image problem can't be solved if you test on a local shop
If you use Gmail, when displaying an image Google uses a kind of "proxy" url that links to the image, so if it's not online it cant' be displayed

About the size this is weird, which mail is it `order_conf` ? Did you test on a fresh install? If not make sure you have regenerated the templates in `Design > Email Theme` (with "overwrite" option checked to Yes)

You can also try the preview (at the bottom of the page, and then selection `order_conf` preview) or at `/improve/design/mail_theme/preview/en-US/modern/order_conf.html`

**Comment by sarahdib** [comment]
@jolelievre the bank address is not display properly.

Capture d’écran 2019-05-07 à 15 15 45

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @jolelievre
