### PR TITLE
Fix sidebar submenu opening by changing style and adding JS

### LINKED ISSUE #17912: Reduced left menu is not working
#### Describe the bug

Reduced left menu is not working in 1.7.7 : When there is sub-items in an item, it should open a sub-menu, but nothing happens.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO
2. Reduce left menu
3. Try to open an item with sub-items inside (order for example) : Nothing happens.

**Screenshots**

https://drive.google.com/file/d/1ogI4SqnjeJ6FvC5XE8LE7Xt7YpheSVfs/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | We could'nt open submenus when left sidebar was collapsed
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17912.
| How to test?  | Go on BO, collapse menu sidebar, and then try to open submenus by clicking some menus link, it should work on migrated pages and legacy pages

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18102)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/nav_bar.js [hunk 1]
```diff
@@ -44,78 +54,80 @@ export default class NavBar {
...
-              .find('a > i.material-icons.sub-tabs-arrow').text('keyboard_arrow_down');
-            addMobileBodyClickListener();
-          } else {
-            $('nav.nav-bar ul.main-menu > li.-active')
-              .addClass('ul-open open')
-              .find('a > i.material-icons.sub-tabs-arrow').text('keyboard_arrow_up');
-            $('body').off('click.mobile');
-          }
+        const itemOffsetTop = $submenu.position().top;
+        $submenu.find('ul.submenu').css('top', itemOffsetTop);
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/nav_bar.js:100]: Here are some JS modifications

File: admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss [hunk 2]
```diff
@@ -438,7 +438,7 @@
           margin-bottom: 0;
         }
 
-        &.-hover {
+        &.ul-open {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss:441]: css modification

File: admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss [hunk 3]
```diff
@@ -452,7 +452,6 @@
           ul.submenu {
             position: absolute !important;
             display: block !important;
-            top: 34px !important;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/scss/components/layout/_nav_bar.scss:455]: Kicking this out as it's not calculated using JS

File: admin-dev/themes/new-theme/template/components/layout/nav_bar.tpl [hunk 4]
```diff
@@ -28,97 +28,98 @@
...
+                      {if $level2.sub_tabs|@count}
+                        <ul id="collapse-{$level2.id_tab}" class="submenu panel-collapse">
+                          {foreach $level2.sub_tabs as $level3}
+                            {if $level3.active}
+
+                              {$level3Href = $level3.href|escape:'html':'UTF-8'}
+
+                              {$level3Name = $level3.name|escape:'html':'UTF-8'}
+                              {if $level3.name eq ''}
+                                {$level3Name = $level3.class_name|escape:'html':'UTF-8'}
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/template/components/layout/nav_bar.tpl:102]: Added a div to avoid overflow hiding submenus thanks to @PierreRambaud

File: admin-dev/themes/new-theme/js/nav_bar.js [hunk 5]
```diff
@@ -30,10 +30,20 @@ const $ = window.$;
...
+      $('.nav-bar-overflow').on('scroll', () => {
+        const $menuItems = $('.main-menu .link-levelone.has_submenu.ul-open');
+
+        $($menuItems).each((i, e) => {
+          const itemOffsetTop = $(e).position().top;
+          $(e)
+            .find('ul.submenu')
+            .css('top', itemOffsetTop);
+        });
+      });
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/nav_bar.js:46]: Here are some js modifications, did the same on default theme

File: admin-dev/themes/new-theme/js/nav_bar.js [hunk 6]
```diff
@@ -44,78 +54,80 @@ export default class NavBar {
...
-      $('.nav-bar li.link-levelone.has_submenu > a').on(
-        'click',
-        function onNavBarClick(e) {
-          e.preventDefault();
-          e.stopPropagation();
-          const $submenu = $(this).parent();
-          $('.nav-bar li.link-levelone.has_submenu a > i.material-icons.sub-tabs-arrow')
-            .text('keyboard_arrow_down');
-          const onlyClose = $(e.currentTarget).parent().hasClass('ul-open');
+      $('.nav-bar li.link-levelone.has_submenu > a').on('click', function onNavBarClick(e) {
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/nav_bar.js:57]:
```suggestion
      $('.nav-bar li.link-levelone.has_submenu > a').on('click', function(e) {
```

File: admin-dev/themes/new-theme/js/nav_bar.js [hunk 7]
```diff
@@ -44,78 +54,80 @@ export default class NavBar {
...
+        const onlyClose = $(e.currentTarget)
+          .parent()
+          .hasClass('ul-open');
+
+        if ($('body').is('.page-sidebar-closed:not(.mobile)')) {
+          $('.nav-bar li.link-levelone.has_submenu.ul-open').removeClass('ul-open open -hover');
+          $('.nav-bar li.link-levelone.has_submenu.ul-open ul.submenu').removeAttr('style');
+        } else {
+          $('.nav-bar li.link-levelone.has_submenu.ul-open ul.submenu').slideUp({
+            complete: function slideUpIsComplete() {
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/nav_bar.js:71]:
```suggestion
            complete: function() {
```

File: admin-dev/themes/new-theme/js/nav_bar.js [hunk 8]
```diff
@@ -44,78 +54,80 @@ export default class NavBar {
...
+      });
 
-          $.post({
-            url: $(this).data('toggle-url'),
-            cache: false,
-            data: {
-              shouldCollapse: Number($('body').hasClass('page-sidebar-closed')),
-            },
-          });
+      $navBar.on('click', '.menu-collapse', function onNavBarClick() {
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/nav_bar.js:103]:
```suggestion
      $navBar.on('click', '.menu-collapse', function() {
```

File: admin-dev/themes/new-theme/js/nav_bar.js (hunk 6 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/nav_bar.js:57]: Will cause a lint error on merge

File: admin-dev/themes/new-theme/js/nav_bar.js (hunk 7 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/nav_bar.js:71]: Will cause a lint error on merge

File: admin-dev/themes/new-theme/js/nav_bar.js (hunk 8 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/nav_bar.js:103]: Will cause a lint error on merge

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

File: admin-dev/themes/default/template/nav.tpl [hunk 9]
```diff
@@ -4,72 +4,74 @@
...
-							<span>{if $level_1.name eq ''}{$level_1.class_name|escape:'html':'UTF-8'}{else}{$level_1.name|escape:'html':'UTF-8'}{/if}</span>
-						</a>
-					</li>
-				{else}
-					<li class="category-title {if $level_1.current}-active{/if}" id="tab-{$level_1.class_name}" data-submenu="{$level_1.id_tab}">
-						<span class="title">
-							<span>{if $level_1.name eq ''}{$level_1.class_name|escape:'html':'UTF-8'}{else}{$level_1.name|escape:'html':'UTF-8'}{/if}</span>
-						</span>
-					</li>
+  <div class="nav-bar-overflow">
```
Comment (matks) [inline admin-dev/themes/default/template/nav.tpl:7]: @NeOMakinG @PierreRambaud  Sorry for being late on this but I just noticed it while merging `1.7.7.x` into `develop`
Isn't it a BC break ? adding a `<div class="nav-bar-overflow">` on top of the menu ?
This will break any module JS script using selectors ?

Comment (NeOMakinG) [reply admin-dev/themes/default/template/nav.tpl:7]: Depending how it is selected, but even if it's a BC Break, thats a bug which still block the use of the menu while on responsive device, that's pretty huge, it means that you can't use your backoffice on responsive device, that should be fixed even introducing BC

Comment (Progi1984) [reply admin-dev/themes/default/template/nav.tpl:7]: If it's a BC Break, it must defined in changelog ;)
