### PR TITLE
Fix product type error when enabling experimental product page

### LINKED ISSUE #29071: BO - Create a new product - Exception is thrown: Invalid product type. Valid types are: [standard,pack,virtual,combinations] when enabling new product page Feature
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

scrnli_7_13_2022_3-42-48 PM

If I start create a new product with product page V1, then enable product page V2 and reload product page an error 500, see video:

https://user-images.githubusercontent.com/90208051/178752350-bde477d8-7fe1-4b44-88e1-bb9abb0895ed.mp4

### Expected behavior

No errors

### Steps to reproduce

1. Start creates a new product with product page V1
2. Enable product page V2
3. Reload page with new product 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/29071
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29071
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | see in fixed issue https://github.com/PrestaShop/PrestaShop/issues/29071
| Possible impacts? |

### CODE REVIEW

**Comment by zuk3975** [comment]
@jolelievre I feel like the product_type column is redundant, because we cannot trust it 100% :cry: Ideally, we shouldn't allow empty value as type, but I believe its hard to ensure.

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 1]
```diff
@@ -285,25 +285,41 @@ public function get(ProductId $productId): Product
...
+     * @throws ProductConstraintException
+     * @throws ProductNotFoundException
+     */
     public function getProductType(ProductId $productId): ProductType
     {
-        $qb = $this->connection->createQueryBuilder();
-        $qb
-            ->addSelect('p.product_type')
+        $result = $this->connection->createQueryBuilder()
+            ->addSelect('p.product_type, p.cache_is_pack, p.is_virtual, p.cache_default_attribute')
```
Comment (FabienPapet) [inline src/Adapter/Product/Repository/ProductRepository.php]: Colums `p.cache_is_pack, p.is_virtual, p.cache_default_attribute` are added but look not used. Can you please explain why you added them ?

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 2]
```diff
@@ -285,25 +285,41 @@ public function get(ProductId $productId): Product
...
             ->from($this->dbPrefix . 'product', 'p')
             ->where('p.id_product = :productId')
             ->setParameter('productId', $productId->getValue())
+            ->execute()
```
Comment (FabienPapet) [inline src/Adapter/Product/Repository/ProductRepository.php:302]: IMO this change (replacing $qb by $result) is not needed if the selected columns are not modified. Then you can 'just' have the real changes L317 to L322.

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 1 above)
Comment (zuk3975) [reply src/Adapter/Product/Repository/ProductRepository.php]: yes, indeed, I forgot it (I've added them previously, because I tried another approach of fetching the values needed to determine the product type without loading the whole product). But now they are useless, so I'll remove them.

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 2 above)
Comment (zuk3975) [reply src/Adapter/Product/Repository/ProductRepository.php:302]: The $qb variable is redundant, so I just removed the variable.

**Review by marsaldev — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @zuk3975,

It is ok :heavy_check_mark: 
Automatic tests OK.

**Check1**
1. Create a product with API
2. The product is displayed on product page V2
3. Click to edit the product => OK, no exception

**Check2**
1. Create a product with API
2. The product is displayed on product page V2
3. Change the XML object by adding the product type "<product_type>combinations</product_type>"
5. Click to edit the product
6. Click on Save => Ok: no exception

**Check3**
1. Enable the Experimental product page
2. Enable multistore & create a new shop
3. Create a product in all shops with V1
4. Select a shop1 & try to edit the product with V2 => Ok no exception

**Check4**
1. Go to BO > Advanced Parameters > New & Experimental Features page
2. Enable New product page - Single store and save
3. In the Quick access > click on New product => OK no exception

**Check5**
1. Enable the multistore feature
2. Go to BO > Advanced Parameters > New & Experimental Features page
3. Enable New product page - Multi-store and save
4. In the Quick access > click on New product => Ok no exception

**Check6**
1. Create a product with V1 (Standard OR with combinations OR pack OR a vector)
2. BO > CONFIGURE > Advanced Parameters > Enable the New product page
3. Come back to the product page and edit the product (Standard OR with combinations OR pack OR a vector) => OK: no exception


https://user-images.githubusercontent.com/16067358/181789878-6003e9d3-5671-46d2-9e8d-4fe7ff052feb.mp4


PS: I found this issue https://github.com/PrestaShop/PrestaShop/issues/29204 when testing this PR

Thanks!

**Comment by kpodemski** [comment]
Thanks @zuk3975 🎉
