### PR TITLE
Fix stock policy propagation on product combination

### LINKED ISSUE #28958: FO - Proceed to checkout is NOK when the product is allowed when out of stock and Allow ordering of out-of-stock products parameter is disabled with product V2
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Proceed to checkout is NOK when the product is allowed when out of stock and Allow ordering of out-of-stock products parameter is disabled with product V2

https://user-images.githubusercontent.com/92912932/177306715-269046a6-8572-4572-aa4c-e95d480f942f.mp4

### Expected behavior

Proceed to checkout is OK

### Steps to reproduce

1. BO> CONFIGURE > Advanced parameters > New & Experimental Features > Enable the product V2 page 
2. Create a new product V2 with combinations 
3. Generate combinations
4. Select `Allow orders `in `When out of stock `section
5. BO > CONFIGURE > Shop Parameters > Product Settings > Disable `Allow ordering of out-of-stock products` parameter
6. Go to FO > Add the created product to cart
7. Increase the quantity when the error message for quantity is displayed
8. Click on Proceed to checkout 
9. See error > The page still in Shopping cart process and there is no possibility to continue the order
 

### PrestaShop version(s) where the bug happened

8.0.0 

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?      | Product out of stock policy is not propagated in product attributes
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #28958
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.

### CODE REVIEW

File: src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php [hunk 1]
```diff
@@ -91,5 +98,10 @@ public function handle(UpdateProductStockInformationCommand $command): void
             ),
             $command->getShopConstraint()
         );
+
+        dump($command);
```
Comment (marsaldev) [inline src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php]: @FabienPapet 
I see a dump 😊

**Review by marsaldev — CHANGES_REQUESTED** [review]

File: src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php (hunk 1 above)
Comment (FabienPapet) [reply src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php]: ahaha :) fixed

Comment (matks) [reply src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php]: Eye of the tiger!

**Review by marsaldev — DISMISSED** [review]

**Comment by marsaldev** [comment]
Seems ok to me 😉

File: src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php (hunk 1 above)
Comment (marsaldev) [reply src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php]: ahaha :D 

the next thought is, can we include a check for this things in the automated test?

**Comment by marsaldev** [comment]
Uh oh, the tests needs update ^^" 

And I think there is also a BC break here:
https://github.com/PrestaShop/PrestaShop/pull/29132/files#diff-c7671f11a1aa9e93a5db6dcdde0cca09b9a6185af9fb8b2edc3c52fa34903bb7R86

and here (?):
https://github.com/PrestaShop/PrestaShop/pull/29132/files#diff-1d3ebe4c70617961beaa59d7621f5e122b55a8e58e25fdd2aa11345e9af81a77R65

**Comment by FabienPapet** [comment]
Following [this ADR](https://github.com/PrestaShop/ADR/pull/25), changes should be OK with BC premise, can another one confirm ? 

I'll have an look on failing tests

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php [hunk 2]
```diff
@@ -366,4 +368,24 @@ public function getCombinationIdsByAttributes(ProductId $productId, array $attri
...
+    {
+        $qb = $this->connection->createQueryBuilder();
+        $qb
+            ->update(sprintf('%sstock_available', $this->dbPrefix), 'ps')
+            ->set('ps.out_of_stock', (string) $outOfStockType->getValue())
+            ->where('ps.id_product = :productId')
+            ->setParameter('productId', $productId->getValue())
+        ;
+
+        if ($shopConstraint !== null && $shopConstraint->getShopId() !== null) {
```
Comment (zuk3975) [inline src/Adapter/Product/Combination/Repository/CombinationRepository.php]: checking strictly against null doesn't add any value, because arguments are already strictly typed, so i IMO its cleaner to read without `null` checks:

```suggestion
        if ($shopConstraint && $shopConstraint->getShopId()) {
```

Comment (zuk3975) [reply src/Adapter/Product/Combination/Repository/CombinationRepository.php]: Also shouldn't we handle shopGroupId?
Lets say if $shop->constraint is ShopGroupId, then we probably need to check `where id_shop IN (:shopIds)` (shop ids being the shops in group. You should explore more if thats the case, im just saying it without much exploration)? Or if shop group is not supported, then we should throw exception. Because I think in other productRep methods we load the product by shop constraint, which already handles the error case for shopGroup and then its impossible to pass shop constraint for group. (but in this case you can pass any shop constraint, so the ShopGroupId case isn't handled)

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php [hunk 3]
```diff
@@ -366,4 +368,24 @@ public function getCombinationIdsByAttributes(ProductId $productId, array $attri
             return new CombinationId((int) $combination['id_product_attribute']);
         }, $result);
     }
+
+    public function updateCombinationStock(ProductId $productId, OutOfStockType $outOfStockType, ShopConstraint $shopConstraint = null): void
+    {
+        $qb = $this->connection->createQueryBuilder();
+        $qb
+            ->update(sprintf('%sstock_available', $this->dbPrefix), 'ps')
+            ->set('ps.out_of_stock', (string) $outOfStockType->getValue())
```
Comment (kpodemski) [inline src/Adapter/Product/Combination/Repository/CombinationRepository.php:377]:
```suggestion
            ->set('ps.out_of_stock', (string) $outOfStockType->getValue())
```

DB prefix is dynamic :D

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php (hunk 2 above)
Comment (FabienPapet) [reply src/Adapter/Product/Combination/Repository/CombinationRepository.php]: You are right about shopGroupIds, I've aded code to handle them. Considering the 'short if' notation, I prefer keep it that way because I don't like the `if($object)` notation and I prefer testing boolean results.

File: src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php [hunk 4]
```diff
@@ -49,17 +50,23 @@ final class UpdateProductStockInformationHandler implements UpdateProductStockIn
      * @var MovementReasonRepository
      */
     private $movementReasonRepository;
+    /**
```
Comment (zuk3975) [inline src/Adapter/Product/Stock/CommandHandler/UpdateProductStockInformationHandler.php:54]:
```suggestion
    /**
```
Not to block a PR, but in case you have any other feedback, could fix it together.

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php [hunk 5]
```diff
@@ -366,4 +371,17 @@ public function getCombinationIdsByAttributes(ProductId $productId, array $attri
             return new CombinationId((int) $combination['id_product_attribute']);
         }, $result);
     }
+
+    public function updateCombinationStock(ProductId $productId, OutOfStockType $outOfStockType, ShopConstraint $shopConstraint = null): void
+    {
+        $qb = $this->connection->createQueryBuilder();
+        $qb
+            ->update(sprintf('%sstock_available', $this->dbPrefix), 'ps')
```
Comment (zuk3975) [inline src/Adapter/Product/Combination/Repository/CombinationRepository.php:379]:
```suggestion
            ->update(sprintf('%sstock_available', $this->dbPrefix), $this->dbPrefix)
```
Ahh, didn't notice before :( sorry this is critical change, needs to be done :sweat:

File: src/Core/Repository/ShopConstraintTrait.php [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+        string $shopColumnName = 'id_shop',
+        string $shopGroupColumnName = 'id_shop_group'
+    ): QueryBuilder {
+        if (null === $shopConstraint) {
+            return $queryBuilder;
+        }
+
+        if ($shopConstraint->getShopId() !== null) {
+            $queryBuilder
+                ->andWhere($shopColumnName . ' = :shop')
```
Comment (zuk3975) [inline src/Core/Repository/ShopConstraintTrait.php]: I think there is a risk for sql injection :thinking:

File: src/Core/Repository/ShopConstraintTrait.php [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+                ->setParameter('shop', $shopConstraint->getShopId()->getValue())
+            ;
+        }
+
+        if ($shopConstraint->getShopGroupId() !== null) {
+            $queryBuilder
+                ->andWhere($shopGroupColumnName . ' = :shop_group')
```
Comment (zuk3975) [inline src/Core/Repository/ShopConstraintTrait.php]: same here :thinking: 
Guess we should have some kind of a map of allowed table names or am I being too picky?

**Review by zuk3975 — CHANGES_REQUESTED** [review]
Sorry that I didn't see it earlier (and I know this causes PR to drag longer :sweat: ), but it seems there is risk of sql injection in couple places :thinking: (left comments)

File: src/Core/Repository/ShopConstraintTrait.php (hunk 6 above)
Comment (FabienPapet) [reply src/Core/Repository/ShopConstraintTrait.php]: I removed the code as we don't need it yet and it may cause some issues like you mentioned.

Thank you for pointing that out

File: src/Core/Repository/ShopConstraintTrait.php (hunk 7 above)
Comment (FabienPapet) [reply src/Core/Repository/ShopConstraintTrait.php]: I removed the code as we don't need it yet and it may cause some issues like you mentioned.

Thank you for pointing that out

**Comment by FabienPapet** [comment]
Code is now corrected and ready for review

File: src/Core/Repository/ShopConstraintTrait.php [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+        QueryBuilder $queryBuilder,
+        ?ShopConstraint $shopConstraint = null
+    ): QueryBuilder {
+        if (null === $shopConstraint) {
+            return $queryBuilder;
+        }
+
+        if ($shopConstraint->getShopId() !== null) {
+            $queryBuilder
+                ->andWhere('id_shop' . ' = :shop')
```
Comment (zuk3975) [inline src/Core/Repository/ShopConstraintTrait.php]: hehe, now the string concatination is not needed :smile: 
```suggestion
                ->andWhere('id_shop = :shop')
```

File: src/Core/Repository/ShopConstraintTrait.php [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+                ->setParameter('shop', $shopConstraint->getShopId()->getValue())
+            ;
+        }
+
+        if ($shopConstraint->getShopGroupId() !== null) {
+            $queryBuilder
+                ->andWhere('id_shop_group' . ' = :shop_group')
```
Comment (zuk3975) [inline src/Core/Repository/ShopConstraintTrait.php]:
```suggestion
                ->andWhere('id_shop_group = :shop_group')
```

File: src/Core/Repository/ShopConstraintTrait.php (hunk 8 above)
Comment (FabienPapet) [reply src/Core/Repository/ShopConstraintTrait.php]: ;(

**Comment by FabienPapet** [comment]
Fixed

**Review by zuk3975 — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
Legit code to me, but we need to add some behat tests to ensure the data is correctly propagated amongst all the combinations

Since we don't have an endpoint to get the combination out of stock type value (neither in behat nor in one of our CQRS query) you're gonna have to add an endpoint relying on manual DB query or ObjectModel to get back this specific data for combination

This is only temporary because in 8.1 we will change this contract, the combination out_of_stock_type option will be editable combination by combination so we will have a CQRS query to get it at this point. You can leave an `@todo` in this temporary endpoint to make sure we do'nt forget to refacto or clean it in 8.1

**Review by kpodemski — DISMISSED** [review]
I think @jolelievre forgot to put `Request changes` instead of `Comment` :)

**Comment by kpodemski** [comment]
Ping @FabienPapet

**Comment by FabienPapet** [comment]
Updated and ready for review @kpodemski @zuk3975 @jolelievre

File: tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationStockFeatureContext.php [hunk 10]
```diff
@@ -173,4 +173,34 @@ private function fillCommand(UpdateCombinationStockCommand $command, array $data
...
+        $outOfStockInt = $this->convertOutOfStockToInt($outOfStock);
+        Assert::assertSame(
+            $product->getStockInformation()->getOutOfStockType(),
+            $outOfStockInt
+        );
+
+        $combinations = $this->getCombinationsList($reference);
+
+        foreach ($combinations->getCombinations() as $combination) {
+            $stock = new \StockAvailableCore($combination->getCombinationId());
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/UpdateCombinationStockFeatureContext.php]:
```suggestion
            $stock = new StockAvailable($combination->getCombinationId());
```

Please add a `use` statement for this class, we try to never use the FQCDN even for legacy classes that have no namespaces. And we also never use the `*Core` classes but the final ones.

**Review by jolelievre — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Review by margud — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @FabienPapet ,

[Automated tests](https://github.com/florine2623/testing_pr/actions/runs/3427335497) were launched and were successful.

Tested the basic case in PPV2, it is fixed ✅ 
Checkout process is working well.

https://user-images.githubusercontent.com/16019289/200842296-7907e92f-2125-44bb-a24a-e882d00571b2.mov

Also checked for the parameters: ✅ 

- Tested with standard products and combination products
- Disable/enable option `Allow ordering of out-of-stock products`
- In Product Page edition, checked with all the options of `When out of stock`


Also checked with Product Page V1, it is not correct. ❌ 

https://user-images.githubusercontent.com/16019289/200858885-8ce096d7-d1b1-4148-b968-3ffa606db9be.mov

I can always add product to cart + proceed to checkout, with these 2 options:
Screenshot 2022-11-09 at 15 33 59
Screenshot 2022-11-09 at 15 34 17

I should not be able to add my product to my cart when I have `Deny orders` and `Allow ordering of out-of-stock products`.

Could you check?
Thanks!

**Review by florine2623 — APPROVED** [review]
As discussed with @jolelievre ,

This PR is validated for Product Page V2 ✅ 

Another issue has been raised for the Product Page V1 mentioned in the previous comment : https://github.com/PrestaShop/PrestaShop/issues/30312

Thanks all !

**Comment by jolelievre** [comment]
Thanks @FabienPapet and @florine2623
