### PR TITLE
Fixed error message when the order language is different of the employee language

### LINKED ISSUE #26547: BO - Order page - Incorrect alert message when adding a discount or removing it and when updating a carrier
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When the employee language is different from the customer language, in the BO > Orders > Order details page > when we try to add a discount or remove it => the successful alert message is displayed in the language of the customer and not the employee language.

### Expected behavior

If the employee language is English, the successful alert message should be displayed in English

### Steps to reproduce

1. You must have at least two different languages (Install the shop with English country and frensh language)
2. Create an order with the French language
3. The employee language is English
4. Go to BO > Orders > Open the last order created
5. Try to add a valid discount
6. Se error: the message is in French 
image
image
7. Try to remove the discount 
8. Se error: the message is in French
9. Try to update the carrier 
8. Se error: the message is in French

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1build1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed error message when the order language is different of the employee language
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26547
| How to test?      | Cf. #26547

**Description :**
* When you are using the backoffice, you consider that the `translator` is in :fr: 
* When you use (for example) the `AddCartRuleToOrderHandler`, and you go in the `OrderAmountUpdater`
  * The ContextStateManager change the Language of the context in the language of the order so in :gb: in our example
  * When the email send acts, that uses `Context::getContext()->getTranslator()` which changes its `translator` in :gb: 
  * The ContextStateManager restore the language in :fr: 
* At this moment, we have : 
  * `Context::getContext()->language` is in :fr: 
  * `translator` is is :gb: 
  
It's why we need to synchronize the translator with language when we use the ContexteStateManager.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26590)

### CODE REVIEW

File: src/Adapter/Order/CommandHandler/UpdateOrderShippingDetailsHandler.php [hunk 1]
```diff
@@ -68,59 +75,66 @@ public function handle(UpdateOrderShippingDetailsCommand $command)
         $carrierId = $command->getNewCarrierId();
         $oldTrackingNumber = $order->shipping_number;
 
-        $orderCarrier = new OrderCarrier($command->getCurrentOrderCarrierId());
-        if (!Validate::isLoadedObject($orderCarrier)) {
-            throw new OrderException('The order carrier ID is invalid.');
-        }
+        $this->contextStateManager
+            ->setTranslatorLocale((new Language($order->id_lang))->locale);
```
Comment (matks) [inline src/Adapter/Order/CommandHandler/UpdateOrderShippingDetailsHandler.php]: Are we sure that
```
new Language($order->id_lang))
```
will return a valid Language object, so we can fetch `->locale`?

**Review by jolelievre — COMMENTED** [review]
I have a few questions withy this modification:

#### The problem/solution seems upside down 

First, how comes the translator employee's locale has been modified? The modif you are making would make sense if we had a bug that says "Messages in mail rendering are not correctly translated because they use the employee's language", so we would need to state manager to override employee's locale with customer's one.

But the issue here is the opposite, it's the customer's locale that ends up overriding the initial employee's one, it looks like the problem is about something that has not been "unstacked" properly rather than something that was missing being "stacked".

#### What about Context->language ?

I thought that we were already handling the context language in the state manager, then maybe we should switch the translator locale at the same time we change the language? Instead of adding a new locale override (changes are that when we need to override the language we'll need the locale as well)

Also, here it seems you now handle stuff related with the translator, which made me think: maybe the management, if the translator was indeed missing in a way and adding this now, fixes the bug because it resets a value we didn't notice was modified (the translator's locale). But the fix is an after effect of this systematic reset and might be hiding the root cause: who changed the translator's locale in the first place?

File: src/Adapter/ContextStateManager.php [hunk 2]
```diff
@@ -157,6 +157,14 @@ public function setCustomer(?Customer $customer): self
         return $this;
     }
 
+    public function setTranslatorLocale(string $locale): self
```
Comment (jolelievre) [inline src/Adapter/ContextStateManager.php]: As we discussed this probably can be done via the `setLanguage` method, so that it correctly switched the translator when language is overridden

And it also re-switch back the translator's locale correctly when the state is popped

File: src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php [hunk 3]
```diff
@@ -80,6 +81,7 @@ public function handle(AddCartRuleToOrderCommand $command): void
         $this->contextStateManager
             ->setCurrency(new Currency($order->id_currency))
             ->setCustomer(new Customer($order->id_customer))
+            ->setTranslatorLocale((new Language($order->id_lang))->locale)
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php]:
```suggestion
            ->setLanguage((new Language($order->id_lang)))
```

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php]: Once `setLanguage` handles the translator's locale change it becomes easier to use here

**Review by jolelievre — CHANGES_REQUESTED** [review]
Just a suggestion to handle this in `setLanguage`

This way it will automatically be handled in this method as well:
https://github.com/PrestaShop/PrestaShop/blob/62ef09e0f769d0c83eb8a8b49e93b5a7b2e68470/src/Adapter/Order/CommandHandler/AbstractOrderCommandHandler.php#L192

**Review by atomiix — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

This would have deserved some comments here and here but I won't bother you with this 😉

**Comment by HanaRebaiQA** [comment]
Hello @Progi1984 

I have tested this PR. The issue is fixed.
I verified with theses differents cases : 
-Installing shops with different languages and different countries (Shop 1 : English as a language and France as a country, Shop 2 : Italian as a language and Algeria as a country) 
-Import different language
-Verify with multistore. 

See the attached screen-record below : 
https://watch.screencastify.com/v/kFRBPoqcizpuXXqgzzm2
https://watch.screencastify.com/v/yQupft0zfxzYW5XUy6mH
https://watch.screencastify.com/v/hafKtymJylAM2JHAmqkA
https://watch.screencastify.com/v/AeAKXv2xJeQkaZyDwQbV

So, QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @HanaRebaiQA
