### PR TITLE
Use PS cache config as driver.cache

### LINKED ISSUE #22250: The left menu in BO disappeared after upgrade to 1.7.7.0
**Status**: Tech investigation still need to be done

I have encountered an issue with the upgrade of Prestashop 1.7.7 from both 1.7.6.9 and from 1.7.6.5

I have upgraded two of my shops, through 1-click and in both instances the main BO menu has disappeared. 
When I turn the debugger on I get this error:

Notice on line 2083 in file /home/244169.cloudwaysapps.com/zecggmmewd/public_html/classes/controller/AdminController.php
[8] Undefined index: enabled

Please see screenshot attachment

sshot

Server info in sshot2
sshot2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Because APC was used as cache.driver (when available) for doctrine even when the cache setting of PrestaShop was disabled, that led to a cache not being cleared while upgrading and the schema upgrade was then using old Entities.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22250
| How to test?  | With apcu **& [apcu_bc](https://pecl.php.net/package/apcu_bc)**, try to upgrade from 1.7.6.9 to 1.7.7.0. Everything should works and you should still have the left menu in the BO.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22293)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matks** [comment]
We'll need to document this behavior 📖

File: app/config/set_parameters.php [hunk 1]
```diff
@@ -55,7 +55,26 @@
...
+        'CacheMemcached' => ['memcached'],
+        'CacheApc' => ['apcu', 'apc'],
+        'CacheXcache' => ['xcache'],
+    ];
+
+    if (isset($parameters['parameters']['ps_cache_enable'], $parameters['parameters']['ps_caching'])
+        && true === $parameters['parameters']['ps_cache_enable']
+        && isset($cacheType[$parameters['parameters']['ps_caching']])
+    ) {
+        foreach ($cacheType[$parameters['parameters']['ps_caching']] as $type) {
```
Comment (matks) [inline app/config/set_parameters.php:73]: So if memcache and apcu and xcache are available, we decide to use memcache? there's a "ranking"?

Comment (atomiix) [reply app/config/set_parameters.php:73]: @matks We use the parameter key `ps_caching` to know what kind of cache to use

The `foreach` loop is mainly used to check which one of apc/apcu cache is available

File: app/config/set_parameters.php [hunk 2]
```diff
@@ -55,7 +55,26 @@
...
+    $cacheType = [
+        'CacheMemcache' => ['memcache'],
+        'CacheMemcached' => ['memcached'],
+        'CacheApc' => ['apcu', 'apc'],
+        'CacheXcache' => ['xcache'],
+    ];
+
+    if (isset($parameters['parameters']['ps_cache_enable'], $parameters['parameters']['ps_caching'])
+        && true === $parameters['parameters']['ps_cache_enable']
+        && isset($cacheType[$parameters['parameters']['ps_caching']])
```
Comment (Progi1984) [inline app/config/set_parameters.php]: Add this isset in the upside isset.

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by jolelievre** [comment]
I just approved the fix, even with `apcu_bc` installed the upgrade process now runs correctly until the end and the Database and menu are correctly set up.

**Comment by jolelievre** [comment]
Thank you @atomiix
