### PR TITLE
Fix missing DNI Number in BackOffice Order View

### LINKED ISSUE #22979: Missing DNI Number in BO > Order View
#### Describe the bug

In 1.7.7.0 and 1.7.7.1 versions, the Identification number ("DNI") is not displayed in BO > Orders details > Address block. This field is mandatory for some countries, like Spain for example.

The info is also missing in the "Preview" of the order in Orders List.

The DNI is however displayed in the invoice.

#### Expected behavior

Identification number should be displayed in the Shipping Address and Invoice Address, in Customer block in BO > Orders details

#### Steps to Reproduce

0. Add "Spain" as a country in the shop
1. Go to FO, connect with a customer
2. Add an address in Spain, with an Identification Number
3. Make an order
4. Go to BO > Orders > Last order
5. Check Customer block : Address dos not contains the "Identification Number"

**Screenshots**

Address in FO : 
177 regression missing DNI address

Display of order details page in 176 : 
177 regression missing DNI address block 176

Display of order details page in 177 : 
177 regression missing DNI address block 177

Missing info in Preview Order too : 

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A
177 regression missing DNI address block 177 preview

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fixed missing DNI Number in BackOffice Order View
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22979
| How to test?      | Cf. #22979

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23040)

### CODE REVIEW

File: src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php [hunk 1]
```diff
@@ -136,6 +143,7 @@ public function __construct(
         $this->postCode = $postCode;
         $this->phoneNumber = $phone;
         $this->mobilePhoneNumber = $phoneMobile;
+        $this->dni = $dni;
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php:146]: What about doing this? That way getDni could return a string
```suggestion
        $this->dni = (string) $dni;
```

File: src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php [hunk 2]
```diff
@@ -194,6 +202,14 @@ public function getCityName(): string
         return $this->cityName;
     }
 
+    /**
+     * @return string|null
+     */
+    public function getDni(): ?string
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php:210]: Best to avoid mixed types when possible.

```suggestion
     * @return string
     */
    public function getDni(): string
```

File: src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php [hunk 3]
```diff
@@ -93,6 +93,11 @@ class OrderShippingAddressForViewing
      */
     private $mobilePhoneNumber;
 
+    /**
+     * @var string|null
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php:97]:
```suggestion
     * @var string
```

File: src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php [hunk 4]
```diff
@@ -93,6 +93,11 @@ class OrderInvoiceAddressForViewing
      */
     private $mobilePhoneNumber;
 
+    /**
+     * @var string|null
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php:97]:
```suggestion
     * @var string
```

File: src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php [hunk 5]
```diff
@@ -194,6 +202,14 @@ public function getCityName(): string
         return $this->cityName;
     }
 
+    /**
+     * @return string|null
+     */
+    public function getDni(): ?string
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php]:
```suggestion
    /**
     * @return string
     */
    public function getDni(): string
```

File: src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php [hunk 6]
```diff
@@ -136,6 +143,7 @@ public function __construct(
         $this->postCode = $postCode;
         $this->phoneNumber = $phone;
         $this->mobilePhoneNumber = $phoneMobile;
+        $this->dni = $dni;
```
Comment (eternoendless) [inline src/Core/Domain/Order/QueryResult/OrderShippingAddressForViewing.php:146]:
```suggestion
        $this->dni = (string) $dni;
```

File: src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php [hunk 7]
```diff
@@ -121,7 +127,8 @@ public function __construct(
         string $postCode,
         string $phone,
         string $phoneMobile,
-        ?string $vatNumber = null
+        ?string $vatNumber = null,
+        string $dni = ''
```
Comment (atomiix) [inline src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php]: Why not using `null` when dni is not mandatory?

Comment (PierreRambaud) [reply src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php]: I agree the null makes more sense than an empty string :thinking:

Comment (matks) [reply src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php]: Is'nt it against @eternoendless feedback above 😅  ?

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php (hunk 7 above)
Comment (sowbiba) [reply src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php]: I prefer null too. Discussion is not closed yet I suppose

**Review by sowbiba — COMMENTED** [review]
Just null vs empty for DNI to decide but I approve the changes

**Review by sowbiba — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
I see no reason to have an empty DNI when there is no DNI to add.
As example if I'm in France, and creating an invoice, I don't have any DNI, it's not mandatory because it doesn't exists, so the null value makes sense.
` ` `php
if ($object->getDni() === null)
` ` ` 
IMHOIs easier to understand, and it's quite generic with others langages (SQL, Python, etc)

**Comment by Progi1984** [comment]
@PierreRambaud It's a good question : If the value is not mandatory, should it be `null` or an `empty string` ? Ping @eternoendless

**Comment by eternoendless** [comment]
Generally speaking, you shouldn't use nullable types unless null conveys a special meaning (e.g. undefined state in a partially loaded model). The main advantage of using strictly typed values (aka not mixed, not nullable) is that you can safely rely on them for post processing using functions that don't support null or mixed types – no checks or type coercion needed.
If the problem is about optional method parameters, this can easily be fixed by using an empty string as default value instead of null.

Again, there might be some case where NULL is semantically different from empty string, and in that case nullables are valid, but they should be documented.

File: src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php (hunk 7 above)
Comment (Progi1984) [reply src/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewing.php]: Fixed

**Review by sowbiba — DISMISSED** [review]

**Comment by eternoendless** [comment]
So I take it you decided that null has a special meaning. Where can I find documentation about this?

**Comment by Progi1984** [comment]
> So I take it you decided that null has a special meaning. Where can I find documentation about this?

Explained in PHPDoc in constructor and in getter.

**Review by sowbiba — DISMISSED** [review]

File: tests/Unit/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewingTest.php [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+use PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderInvoiceAddressForViewing;
+
+class OrderInvoiceAddressForViewingTest extends TestCase
+{
+    public function testConstruct(): void
+    {
+        $instance = new OrderInvoiceAddressForViewing(1, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k');
+        $this->assertEquals(1, $instance->getAddressId());
+        $this->assertEquals('a b', $instance->getFullName());
+        $this->assertEquals('c', $instance->getCompanyName());
```
Comment (matthieu-rolland) [inline tests/Unit/Core/Domain/Order/QueryResult/OrderInvoiceAddressForViewingTest.php:15]: imho the only method worth checking was `getFullName` :D  Overall, since the class has no error checking or value checking there's not much logic to test...  (same for `OrderShippingAddressForViewingTest.php` )

Your behat test on `GetOrderForViewing` is much more interesting in that aspect

**Review by matthieu-rolland — DISMISSED** [review]
lgtm

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have two issues:

In the BO > Orders > Order list page > Preview Order, the DNI is missing
image
In the Order details page => ok
image


Following these steps:

1. Go to BO > International > Locations > Countries Tab 
2. EDit France country
3. In the Address format, Add dni 
image
5. Save
6. Go to FO > Sign in with John Doe
7. Update `Mon adresse` (France country)
8. Add an `Identification number`
9. Save 
 image
11. Add a product to the cart 
12. Continue checkout
13. In the `ADDRESSES Shipping Address` step > Select `Mon adresse`
14. Place Order
15. G to BO > Orders > Last order created 
16. See the error => the dni is not displayed 

image


Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith For the first bug, it's fixed. But for the second, could you please create a dedicated issue ?

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
this time is the right one !

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I created the new issue: https://github.com/PrestaShop/PrestaShop/issues/23357
I will re-check this PR.

Thank you!

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
1. Order preview page 
image
2. Order details page 
image
3. Invoice 
image
4. Delivery slip 
image
5. Credit slip 
image

Thank you!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
