### PR TITLE
Fix bug keeping user from accessing his profile page in BO

### LINKED ISSUE #19077: BO - No access to employee's profile when not an admin
#### Describe the bug

When an employee has a profile without the following permission : _Advanced Parameters > Team > Employee_ (so when he's not an admin, since no non-admin users should access this page), he cannot access his user profile.

#### Expected behavior

User profile should always be accessible, no matter which permission the user has.

#### Steps to Reproduce

1. With SuperAdmin profile, go to BO > Advanced Parameters > Add new employee
2. Create an employee with a "basic" profile (Logistician, Translator for example)
3. Login with this employee account, try to access his profile => Access denied
4. With SuperAdmin account, change permission to this employee's profile, and give access to Advanced Parameters > Team > Employee
5. With employee account, try to access his profile => OK

But this "solution" in not a good workaround, since it will also give access to the "Advanced Parameters > Team > Employee" page to a standard employee...

**Screenshots**

On this screenrecord, I try to access "Profile" page with a Logistician profile, it does not work. I had the "Advanced Parameters > Team > Employee" permission with a SuperAdmin account, go back to the Logistician profile, now "Profile" page is accessible

https://drive.google.com/open?id=1l29QaaN0AfH-79hTUBfwV-YaM-97Luoe

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | A security rule checked that a user had the 'update' capacity before letting him access his profile page. Every users should access their profile page.
| Type?         | bug fix 
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19077 
| How to test?  | See steps in #19077

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19089)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 1]
```diff
@@ -311,7 +311,6 @@ public function createAction(Request $request)
      * Show Employee edit page.
      *
      * @DemoRestricted(redirectRoute="admin_employees_index")
-     * @AdminSecurity("is_granted('update', request.get('_legacy_controller'))", redirectRoute="admin_employees_index")
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php:314]: I just removed this security rule that was added in 1.7.7, since all users should be able to access their profile edition page in BO.  What do you guys think?

(permission to edit a profile other than one's own is checked in the action method)

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @matthieu-rolland

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland
