### PR TITLE
Restore See More & See less for the Module Manager

### LINKED ISSUE #21054: BO - Modules / No "see less", "see more" links in the modules list
#### Describe the bug

In the module list page there is no "see more", "see less" links

#### Expected behavior

The links should be displayed

#### Steps to Reproduce

1. Go to BO/Improve/Modules/Modules manager
2. Check in the modules listing
4. See error ( no "see more" "see less" links)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
image
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The code pagination has been deleted in #19580, restore it, and add an exclusion for pages that are not Module Manager page. 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21054
| How to test?  | Pagination is still removed on the Alerts and Updates page, but buttons are now present in the Modules section.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21309)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 1]
```diff
@@ -408,6 +424,11 @@ class AdminModuleController {
       }
 
       container.show();
+      if (nbModulesInContainer >= self.DEFAULT_MAX_PER_CATEGORIES) {
+        container.find(`${self.seeMoreSelector}, ${self.seeLessSelector}`).show();
+      } else {
+        container.find(`${self.seeMoreSelector}, ${self.seeLessSelector}`).hide();
+      }
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]:
```suggestion
      container.find(`${self.seeMoreSelector}, ${self.seeLessSelector}`).toggle(nbModulesInContainer >= self.DEFAULT_MAX_PER_CATEGORIES);
```

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 2]
```diff
@@ -416,8 +437,10 @@ class AdminModuleController {
 
     self.updateModuleSorting();
 
-    $(self.recentlyUsedSelector).find('.module-item').remove();
-    $('.modules-list').find('.module-item').remove();
+    if (self.isModulesPage()) {
+      $(self.recentlyUsedSelector).find('.module-item').remove();
+      $('.modules-list').find('.module-item').remove();
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]:
```suggestion
      $(`${self.recentlyUsedSelector}, .modules-list`).find('.module-item').remove();
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

**Comment by Julievrz** [comment]
> This pull request seems to contain new translation strings. I have summarized them below to ease up review:
> 
> * `Admin.Actions`
>   
>   * [x]  [`See less`](https://github.com/PrestaShop/PrestaShop/pull/21309/files#diff-b2dae71856993aa0c728ad7a9cbd07d8R31)
> 
> (Note: this is an automated message, but answering it will reach a real human)

@atomiix This wording is not new I think? I don't know if it is normal that it appears as new here?

**Comment by atomiix** [comment]
> @atomiix This wording is not new I think? I don't know if it is normal that it appears as new here?

@Julievrz, even though this wording is present in the catalogue, as the only place where the wording has been used was removed in the PR #19580, the wording is considered new as it is back in the code now.

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 3]
```diff
@@ -474,6 +497,8 @@ class AdminModuleController {
             if (counter[moduleCategory] >= self.DEFAULT_MAX_RECENTLY_USED) {
               isVisible &= self.currentCategoryDisplay[moduleCategory];
             }
+          } else if (counter[moduleCategory] >= self.DEFAULT_MAX_PER_CATEGORIES) {
+            isVisible &= self.currentCategoryDisplay[moduleCategory];
```
Comment (atomiix) [inline admin-dev/themes/new-theme/js/pages/module/controller.js:499]:
```suggestion
          const defaultMax = (moduleCategory === self.CATEGORY_RECENTLY_USED) ? self.DEFAULT_MAX_RECENTLY_USED : self.DEFAULT_MAX_PER_CATEGORIES;
          if (counter[moduleCategory] >= defaultMax) {
              isVisible &= self.currentCategoryDisplay[moduleCategory];
          }
```

File: admin-dev/themes/new-theme/js/pages/module/controller.js (hunk 1 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/module/controller.js]: Not applied @PierreRambaud

**Review by Progi1984 — COMMENTED** [review]
A small feedback

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 4]
```diff
@@ -399,6 +415,7 @@ class AdminModuleController {
       }
 
       container.show();
+      container.find(`${self.seeMoreSelector}, ${self.seeLessSelector}`).toggle(nbModulesInContainer >= self.DEFAULT_MAX_PER_CATEGORIES);
```
Comment (atomiix) [inline admin-dev/themes/new-theme/js/pages/module/controller.js]:
```suggestion
      container
        .find(`${self.seeMoreSelector}, ${self.seeLessSelector}`)
        .toggle(nbModulesInContainer >= self.DEFAULT_MAX_PER_CATEGORIES);
```

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
No QA : We are waiting Wording Team :)

**Comment by Julievrz** [comment]
I'm sorry for the delay, wording is ok. 😊

**Comment by SD1982** [comment]
LGTM Thanks @PierreRambaud !!

**Comment by Progi1984** [comment]
Thanks @PierreRambaud & @SD1982
