### PR TITLE
Fix notice admin search controller

### LINKED ISSUE #28796: Notice in adminsearch controller
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is  notice when you do a targeted search without results in the search bar.

```
Notice à la ligne 207 du fichier /var/www/html/800/PrestaShop/var/cache/dev/smarty/compile/01/2a/3a/012a3aacf3577da6fea68ba6f9e8fd189e40dca1_0.file.view.tpl.php
[8] Undefined index: searchPanels

Notice à la ligne 207 du fichier /var/www/html/800/PrestaShop/var/cache/dev/smarty/compile/01/2a/3a/012a3aacf3577da6fea68ba6f9e8fd189e40dca1_0.file.view.tpl.php
[8] Trying to get property 'value' of non-object
```

Screenshot (38)

### Expected behavior

No notice :) 

### Steps to reproduce

Go to back office 

In the search bar select invoice and enter XXXX

See the notice 

### PrestaShop version(s) where the bug happened

178x 8.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | There is notice when you do a targeted search without results in the search bar.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28796
| Related PRs       | 
| How to test?      | See issue and check if there is a notice
| Possible impacts? |

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by eternoendless** [comment]
LGTM, what do you think @sowbiba ?

File: controllers/admin/AdminSearchController.php [hunk 1]
```diff
@@ -374,6 +374,8 @@ public function renderView()
         $this->tpl_view_vars['show_toolbar'] = true;
 
         if (count($this->errors)) {
+            $this->getSearchPanels($searchedExpression);
```
Comment (PululuK) [inline controllers/admin/AdminSearchController.php]: Ok for me, just to avoid this kind of oversight, I suggest :
```php

 public function renderView() {

    $searchedExpression = Tools::safeOutput($this->query);

    $this->tpl_view_vars['query'] = $searchedExpression;
    $this->tpl_view_vars['query'] = $searchedExpression;
    $this->tpl_view_vars['show_toolbar'] = true;
    $this->tpl_view_vars['show_toolbar'] = true;

    if (!count($this->errors)) {
        // Old code here
    }

    $this->getSearchPanels($searchedExpression);
    return parent::renderView();
}

**Review by PululuK — DISMISSED** [review]

File: controllers/admin/AdminSearchController.php (hunk 1 above)
Comment (ghost) [reply controllers/admin/AdminSearchController.php]: Thank you for suggestion, it's better

**Review by atomiix — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @okom3pom,

Thank you for this PR.
Tested on 8.0.x and develop branches with PHP 7.2 version.

Tested all list of the search on different pages, no more notice errors. All result of the search are well displayed

QA approved ✅ 

Thanks

**Comment by Progi1984** [comment]
Thanks @okom3pom & @sLorenzini
