### PR TITLE
Do not stripslashes value from _GET & _POST

### LINKED ISSUE #11959: Password with the character \ doesn't work in BO
Hello,
I just notice than password with the character \ doesn't work to connect to the BO.

1. Go to 'Team'
2. Create an account
3. Write the password with \ , for example: 1234\56789
4. Save
5. Notice you can save it without issue.
6. Try to connect with this account and password.
7. See the message "The employee does not exist, or the password provided is incorrect."

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Since magicquote gpc is no more used we can remove this test.<br/>More, only replace the nullbyte with "\0" because it can be written in different ways such as 000, \x00, \z, \u0000...
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11959
| How to test?  | Follow ticket instruction.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11962)

### CODE REVIEW

File: classes/Tools.php [hunk 1]
```diff
@@ -517,7 +517,7 @@ public static function getValue($key, $default_value = false)
         }
 
         if (is_string($value)) {
-            return stripslashes(urldecode(preg_replace('/((\%5C0+)|(\%00+))/i', '', urlencode($value))));
+            return urldecode(preg_replace('/((\%5C0+)|(\%00+))/i', '', urlencode($value)));
```
Comment (eternoendless) [inline classes/Tools.php:535]: It looks like this code replaces `"\0"` and `"\\0"`. Maybe it could be optimized using `str_replace()`?

```suggestion
            return str_replace(["\\0", "\0"], '', $value);
```

Comment (PierreRambaud) [reply classes/Tools.php:535]: Agreed, just didn't want to touch something here, and still don't understand why they used urlencode :/

Comment (eternoendless) [reply classes/Tools.php:535]: Maybe it has something to do with multibyte encoding?

Comment (PierreRambaud) [reply classes/Tools.php:535]: I update the code because "\0" is enough.

Comment (PierreRambaud) [reply classes/Tools.php:535]: ping @eternoendless

**Comment by PierreRambaud** [comment]
ping again @eternoendless

**Review by Quetzacoalt91 — CHANGES_REQUESTED** [review]
These changes requires tests to be added.

For instance, in `test-legacy/Unit/Classes/ToolsCoreTests.php`:

```patch
    public function testGetValueStripsNullCharsFromReturnedStringsExamples()
    {
        return array(
            array("\0", ''),
            array("haxx\0r", 'haxxr'),
            array("haxx\0\0\0r", 'haxxr'),
+            array('1234\56789', '1234\56789'), // <--- Test done in #11959
        );
    }
```

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@PierreRambaud Do we request another round of QA since you changed the PR ?

**Comment by matks** [comment]
Thank @PierreRambaud

File: classes/Tools.php (hunk 1 above)
Comment (eternoendless) [reply classes/Tools.php:535]: You never changed it @PierreRambaud :(
