### PR TITLE
Always request a non cached result in Order::getIdByCartId

### LINKED ISSUE #40007: Order::getIdByCartId in OrderConfirmationControllerCore fails to query order_id when cached
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a payment module redirects to order-confirmation, the `OrderId` is fetched using:
`$this->id_order = Order::getIdByCartId((int) $this->id_cart);` https://github.com/PrestaShop/PrestaShop/blob/1d97fcde1bf31d522cfbcfde904316da1d9088d6/controllers/front/OrderConfirmationController.php#L83

`Order::getIdByCartId` uses `$result = Db::getInstance()->getValue($sql);`, with the default of getValue being to use cache.
Now, in some clustered environments it's possible that the order is created by one node and the confirmation page is server by another; this seems to cause the `Order::getIdByCartId` to return a cached `false`, causing the confirmation page to do an early redirect, exiting early. https://github.com/PrestaShop/PrestaShop/blob/1d97fcde1bf31d522cfbcfde904316da1d9088d6/controllers/front/OrderConfirmationController.php#L95

In my experiments, forcing `Order::getIdByCartId` to query a non cached result solves the issue.

### Expected behavior

_No response_

### Steps to reproduce

1. Pay an order with a PSP that confirms the payment via S2S callbacks.
2. If the conditions align you will sometimes get redirected away from the confirmation page

### PrestaShop version(s) where the bug happened

9.1

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by ilsalvopss**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | This resolves an issue with the order-confirmation controller evident in clustered environments using cache. (see #40007)
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Deploy in a clustered environment with APCu cache enabled.<br/>2. Enable a payment module which receives the payment validation via server-to-server communication from the PSP<br/>3. Place an order, pay and get redirected to confirmation page (before the fix you sometimes will get redirected away from the order confirmation page |
| UI Tests          | https://github.com/ilsalvopss/ga.tests.ui.pr/actions/runs/19537231628
| Fixed issue or discussion?     | Fixes #40007
| Related PRs       |  #40037
| Sponsor company   | N/A

 Same as #40037, targeting 9.0.x

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by Touxten — APPROVED** [review]
Okay with me, but some tests are still red. Can you rerun them?

**Comment by ilsalvopss** [comment]
> Can you rerun them?

Done ;). Updated link to UI tests

File: classes/order/Order.php [hunk 1]
```diff
@@ -1189,7 +1189,8 @@ public static function getIdByCartId($id_cart)
             WHERE `id_cart` = ' . (int) $id_cart .
             Shop::addSqlRestriction();
 
-        $result = Db::getInstance()->getValue($sql);
+        // No cache to avoid getting a wrong result in clustered environments
+        $result = Db::getInstance()->getValue($sql, false);
```
Comment (jolelievre) [inline classes/order/Order.php:1193]: Isn't this a problem from your environment then? 🤔
Probably an infra bug rather than a software one

Comment (ilsalvopss) [reply classes/order/Order.php:1193]: I guess it's a problem in every replicated environment that uses APCu (supported by Prestashop!), including mine.

It's also a problem with a trivial solution and negligible pref. impact: the call to getIdByCartId from the OrderConfirmationController is **always** a miss.

If we're worried that the other few calls are impacted by this: let's then propagate back the $cached with default true so that the default call to getIdByCartId remains cached and the order-confirmation controller can do getIdByCartId($id_cart, $use_cache = false).

PS.. as said in the issue the same kind of query is explicitly non-cached elsewhere:
https://github.com/PrestaShop/PrestaShop/blob/8847730cfa5f39d28b55a72896738538783cb40c/classes/Cart.php#L1904-L1910

Comment (jolelievre) [reply classes/order/Order.php:1193]: Hmm, not super satisfied about this solution But we since there is no advance management of the cache and especially because this request is very small, why not..

**Review by jolelievre — APPROVED** [review]

**Comment by ilsalvopss** [comment]
Can a milestone be added to this or are we waiting some more approvals?

**Comment by ilsalvopss** [comment]
@kpodemski @Touxten @Quetzacoalt91 @jolelievre sorry for the ping, I'm just worried this went in an "uncategorized PR" limbo

**Comment by kpodemski** [comment]
thank you @ilsalvopss 

@PrestaShop/qa-functional this change doesn't require functional tests, CI is 🟢 and UI tests as well
