### PR TITLE
Fix the combination's disappearance from Cart when it's updated by WS

### LINKED ISSUE #23061: Webservice: Combination disappear from carts on update
#### Describe the bug

When you read a combination via webservice and update it without any changes (same dto), if this combination is in any Customer cart, it disappear from cart (always). The combination is updated right. Any error is trigged by webservice. Any message displayed to the customer.

#### Expected behavior

The combination must be remain in the cart (respecting business rules and domain logics)

#### Steps to Reproduce

1) Create a product
2) Create some combinations
3) Insert a combination in the cart on public side
4) Read this combination with web service 
5) Update read combination from web service (same read dto unchanged)
6) This combination left the cart (ALWAYS)

---

1. FO> add the **Hummingbird cushion** with **Black** color in the cart
2. In Postman, choose the **PUT** method
3. For the **request URL**, paste this link http://your_site/api/combinations/27 (need to change your_site by yours)
4. Click on the **Authorization** tab
5. Choose **Basic Auth** and paste the WS key in the **Username** and **password**, Save

image

6. Click on **Body** tab and paste this structure

```
<prestashop>
    <combination>
    	<id>27</id>
        <id_product>11</id_product>
        <quantity>300</quantity>
        <reference>17</reference>
        <quantity>300</quantity>
        <minimal_quantity>1</minimal_quantity>
        <associations>
            <product_option_values nodeType="product_option_value" api="product_option_values">
                <product_option_value>
                    <id>11</id>
                </product_option_value>
            </product_option_values>
        </associations>
    </combination>
</prestashop>
```

image

7. Click on **Send** button
8. Check the FO and refresh
9. See error => the cart has been emptied

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.2.34

### PR DESCRIPTION
**Pull request by fabiovannini**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove combination from cart ONLY on delete. Before ,when web service update the combination, deleteAssociations method was called and that combination left the customer cart.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23061
| How to test?      | Cf. #23061
| Possible impacts? | Check that this does not break the expected relational integrity and business rules.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23081)

### CODE REVIEW

File: classes/Combination.php [hunk 1]
```diff
@@ -276,6 +279,16 @@ public function deleteAssociations()
         return $result;
     }
 
+    /**
+     * Delete product combination from cart.
+     *
+     * @return array Deletion result
```
Comment (Progi1984) [inline classes/Combination.php]:
```suggestion
     * @return bool
```

File: classes/Combination.php [hunk 2]
```diff
@@ -276,6 +279,16 @@ public function deleteAssociations()
...
+     */
+    public function deleteCartProductCombination()
```
Comment (Progi1984) [inline classes/Combination.php]:
```suggestion
    public function deleteCartProductCombination(): bool
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks. Thanks :pray:

**Comment by fabiovannini** [comment]
> Some feedbacks. Thanks 🙏

thank you too!

File: classes/Combination.php [hunk 3]
```diff
@@ -276,6 +279,16 @@ public function deleteAssociations()
         return $result;
     }
 
+    /**
+     * Delete product combination from cart.
+     *
+     * @return bool
+     */
+    public function deleteCartProductCombination(): bool
```
Comment (PierreRambaud) [inline classes/Combination.php]:
```suggestion
    protected function deleteCartProductCombination(): bool
```

I see no reason to have this method public.
Also, you should test if `$this->id` is correctly defined before running an SQL query for nothing.

File: classes/Combination.php [hunk 4]
```diff
@@ -276,6 +279,16 @@ public function deleteAssociations()
...
+    {
+        return Db::getInstance()->delete('cart_product', 'id_product_attribute = ' . (int) $this->id);
```
Comment (PierreRambaud) [inline classes/Combination.php:293]:
```suggestion
        if ((int) $this->id === 0) {
            return false;
        }

        return Db::getInstance()->delete('cart_product', 'id_product_attribute = ' . (int) $this->id);
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Hey, good job, few comments :)

**Comment by fabiovannini** [comment]
> Hey, good job, few comments :)

Thanks Pierre, Icompletely agree with you. I have committed the changes.

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM
**Before PR**
https://www.awesomescreenshot.com/video/2722005?key=cfc3bf2458659b5fcbe92f9e77d82f21
**After PR**
https://www.awesomescreenshot.com/video/2722027?key=227852a406af2155b9321edb60d3b520
Thanks @fabiovannini !!

**Comment by matks** [comment]
Thank you @fabiovannini !
