### PR TITLE
Don't redirect to http from https if it is homepage (Fix Chrome security alert when customer register)

### LINKED ISSUE #22430: Last Chrome browser version display security alert when creating new customer account
#### Describe the bug

Last Chrome browser version display security alert when creating new customer account

#### Expected behavior

There shouldn't be an alert that scares the visitor

#### Steps to Reproduce

1. Install the last version of Google Chrome, install PrestaShop 1.7.7 with HTTPS enabled
2. Go to https://shop_url/connexion?create_account=1
3. Fill the form and submit
4. See error (The information you’re about to submit is not secure)

image

#### Additional information

* PrestaShop version: 1.7.6.8 (and below maybe) to 1.7.7.0 
* PHP version: 7.3
* SSL and SSL everywhere On

### PR DESCRIPTION
**Pull request by ludoc**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | when creating a customer account, after POST on https://<domain>/connexion?create_account=1 server respond with 302 and redirect to http://domain/ which display an alert with the last Chrome browser version
| Type?         | bug fix 
| Category?     |  CO
| BC breaks?    | Unknown
| Deprecations? | no
| Fixed ticket? | Fixes #22430
| How to test?  | 1. Install the last version of Google Chrome, install PrestaShop 1.7.7 with HTTPS enabled<br/>2. Go to https://shop_url/connexion?create_account=1 => you're on HTTPS<br/>3. Fill the form and submit<br/>4. You are redirected to homepage and you're on http

image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22432)

### CODE REVIEW

File: classes/Tools.php [hunk 1]
```diff
@@ -202,10 +202,7 @@ public static function redirect($url, $base_uri = __PS_BASE_URI__, Link $link =
             }
 
             $explode = explode('?', $url);
-            // don't use ssl if url is home page
-            // used when logout for example
-            $use_ssl = !empty($url);
```
Comment (jf-viguier) [inline classes/Tools.php:202]: You should remove this line.

**Review by jf-viguier — COMMENTED** [review]
Thanks @ludoc for this PR. Sounds good to me.
"don't use ssl if url is home page" : why is this rule still there in 2020 ?

**Comment by matks** [comment]
> "don't use ssl if url is home page" : why is this rule still there in 2020 ?

I'll be honest: 2020, 2019 or 2015 I don't understand this rule 😛

**Review by matks — DISMISSED** [review]
Code looks good

I wonder if we could go even further because
```
$explode = explode('?', $url);
$url = $link->getPageLink($explode[0]);
if (isset($explode[1])) {
    $url .= '?' . $explode[1];
}
```
I'm not sure if it's still useful to do the `explode()` and then re-append the `$explode[1]`.

However this is only a suggestion, the PR is valid 👍

**Comment by kpodemski** [comment]
https://github.com/PrestaShop/PrestaShop/commit/792ce71cd4e16ad4940c93b2a82f85ef38f803ea#diff-0175e8ccd89d320e7f91e6333bc749edb922cd119188d0545f51fa3dd838aa2c 🤷

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
It's ok for me but I think we should target `1.7.7.x`

cc @PrestaShop/prestashop-maintainers

**Comment by ghost** [comment]
> 
> 
> Code looks good
> 
> I wonder if we could go even further because
> 
> ```
> $explode = explode('?', $url);
> $url = $link->getPageLink($explode[0]);
> if (isset($explode[1])) {
>     $url .= '?' . $explode[1];
> }
> ```
> 
> I'm not sure if it's still useful to do the `explode()` and then re-append the `$explode[1]`.
> 
> However this is only a suggestion, the PR is valid 👍

I just checked, `$explode[1]` seems used when RewriteEngine is enabled but  `$url = $link->getPageLink($url);` seems ok too.
I'm not sure about this change.

File: classes/Tools.php (hunk 1 above)
Comment (ghost) [reply classes/Tools.php:202]: this line ? : `$explode = explode('?', $url);`

**Comment by matks** [comment]
> > Code looks good
> > I wonder if we could go even further because
> > ```
> > $explode = explode('?', $url);
> > $url = $link->getPageLink($explode[0]);
> > if (isset($explode[1])) {
> >     $url .= '?' . $explode[1];
> > }
> > ```
> > 
> > 
> > I'm not sure if it's still useful to do the `explode()` and then re-append the `$explode[1]`.
> > However this is only a suggestion, the PR is valid 👍
> 
> I just checked, `$explode[1]` seems used when RewriteEngine is enabled but `$url = $link->getPageLink($url);` seems ok too.
> I'm not sure about this change.

Indeed, let's not change this code for now. Too many usecases (RewriteEngine, URL of the Core, module URL, external URL, with or without https...) need to be considered to modify this in a safe way.

Let's keep this PR as it is 👍

**Review by PierreRambaud — DISMISSED** [review]

**Comment by marionf** [comment]
@PrestaShop/prestashop-core-developers I think this PR should rather target 1.7.7.x branch ?

**Comment by ghost** [comment]
are you expecting action from me?

**Comment by matks** [comment]
@ludoc This bug would be nice to be inside PS 1.7.7.1 patch version :) could you please rebase your PR so it targets `1.7.7.x` branch instead of `develop` ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by ghost** [comment]
> @ludoc This bug would be nice to be inside PS 1.7.7.1 patch version :) could you please rebase your PR so it targets `1.7.7.x` branch instead of `develop` ?

it's done 👍

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thanks @ludoc !

**Comment by khouloudbelguith** [comment]
Hi @ludoc,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1dZSZBKQq6yd2RIe49fs1v2BZpbNP_Naw/view?usp=sharing

Thank you!

**Comment by matks** [comment]
Thank you @ludoc and @khouloudbelguith 

CI seems to be broken 🤔
