### PR TITLE
Remove useless legacyContextLoader

### LINKED ISSUE #26503: Autoupgrade - Error during upgrade to develop
#### Describe the bug

There is an error during the autoupgrade to the 8.0.0.

#### Expected behavior

Autoupgrade to develop is possible with no error.

#### Steps to Reproduce

1. Create a release 8.0.0 using (php tools/build/CreateRelease.php) from develop branch
2. Autoupgrade the version 1.7.8.0 to 8.0.0 using local archive 
3. See error.

**Screenshots**
image

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: 7.3
* 1-click upgrade 4.13.0

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | During the upgrade using the autoupgrade module, the database is upgraded with a Symfony command. To be able to execute this command, all commands (services tagged with `console.command`) are added to the Symfony container. As `LegacyContextLoader::LoadGenericContext();` is called in the command's constructor, it resets the context employee even if we don't use the command. The problem is that we need to have a valid employee with enough rights to enable the theme during the upgrade process, just after the db upgrade. This PR Solve the issue by simply removing the `LegacyContextLoader` as it doesn't seem useful.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes partially #26503
| How to test?      | CI Should be green
| Possible impacts? | Can impact command `prestashop:config` & `prestashop:debug` even though I didn't encounter any issue on my side

### BC Break
The first argument of `PrestaShopBundle\Command\ConfigCommand` has been removed (`LegacyContextLoader `)
The last argument of has `PrestaShopBundle\Command\DebugCommand` has been removed (`LegacyContextLoader `)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27276)

### CODE REVIEW

File: src/PrestaShopBundle/Command/DebugCommand.php [hunk 1]
```diff
@@ -61,12 +60,11 @@ class DebugCommand extends Command
      */
     private $debugConfiguration;
 
-    public function __construct(CommandBusInterface $commandBus, DebugMode $debugConfiguration, LegacyContextLoader $legacyContextLoader)
+    public function __construct(CommandBusInterface $commandBus, DebugMode $debugConfiguration)
```
Comment (PululuK) [inline src/PrestaShopBundle/Command/DebugCommand.php:63]: need BC label ?

Comment (atomiix) [reply src/PrestaShopBundle/Command/DebugCommand.php:63]: Right!

**Review by matthieu-rolland — APPROVED** [review]

File: src/PrestaShopBundle/Command/ConfigCommand.php [hunk 2]
```diff
@@ -96,12 +95,10 @@ class ConfigCommand extends Command
     private $idLang;
 
     public function __construct(
-        LegacyContextLoader $legacyContextLoader,
         ShopConfigurationInterface $configuration,
         LanguageDataProvider $languageDataProvider
     ) {
         parent::__construct();
-        $legacyContextLoader->loadGenericContext();
```
Comment (jolelievre) [inline src/PrestaShopBundle/Command/ConfigCommand.php:104]: I don't know if this component is useful indeed, but if it was added I guess there was a reason Maybe @tswfi could tell us more about it?

@atomiix  I thought alternatively maybe `$legacyContextLoader->loadGenericContext()` could be called in the `execute` command instead? this way it's still in use and it should not be called in the constructor as soon as the service is handled by the container

Comment (jolelievre) [reply src/PrestaShopBundle/Command/ConfigCommand.php:104]: By the way, it's weird that the constructor is always called as soon as the service is registered I thought services were only built on demand
Maybe we could define them as lazy as well to avoid this (https://symfony.com/doc/current/service_container/lazy_services.html)

Comment (tswfi) [reply src/PrestaShopBundle/Command/ConfigCommand.php:104]: Cant remember why it was required but I think there was something that was needed from the context by DebugMode..
But if it works correctly without it then I guess it can be removed.

Might even be that it was required for translations which were later removed and context was left behind.

Comment (atomiix) [reply src/PrestaShopBundle/Command/ConfigCommand.php:104]: > I thought alternatively maybe $legacyContextLoader->loadGenericContext() could be called in the execute command instead? 

@jolelievre that's effectively an option I was thinking of but I also wanted to see if it was really required at all and it didn't seem to so I just removed it 😄

>Maybe we could define them as lazy as well to avoid this

This would definitely solve the issue too

Comment (jolelievre) [reply src/PrestaShopBundle/Command/ConfigCommand.php:104]: OK seems there is no use at all then removing it is the best choice indeed

**Review by jolelievre — APPROVED** [review]
Thanks @atomiix

**Comment by jolelievre** [comment]
This PR needs to be tested along with the fix in the autoupgrade https://github.com/PrestaShop/autoupgrade/pull/434

**Review by khouloudbelguith — APPROVED** [review]
Hi @atomiix,

A commented here: https://github.com/PrestaShop/autoupgrade/pull/434#pullrequestreview-884427215
The upgrade to this PR is OK :heavy_check_mark: 
Other bugs found will be fixed in some other PRs.
I tried with a fresh install of this PR => OK
I tried some commands => OK


```
 bin/console prestashop:debug --help
 1970  bin/console prestashop:debug
 1971  bin/console prestashop:debug off
 1972  bin/console prestashop:debug
 1974  bin/console prestashop:debug
 1975  bin/console prestashop:debug on
 1976  bin/console prestashop:debug
 1977  bin/console prestashop:config set PS_MAIL_SERVER --value "my-mailcatcher-container-name"
 1978  bin/console prestashop:config set PS_MAIL_SERVER --value "localhost"
 1979  bin/console prestashop:config set PS_MAIL_SMTP_PORT --value 1025
 1980  bin/console prestashop:config set PS_MAIL_USER --value "demo@prestashop.com"
 1981  bin/console prestashop:config set PS_MAIL_PASSWD --value "123456789"
 1982  bin/console prestashop:config --help
 1984  bin/console prestashop:config get PS_INVOICE_PREFIX --lang en
 1986  bin/console prestashop:config set PS_INVOICE_PREFIX --lang en --value "#ON"
 1987  bin/console prestashop:config get PS_INVOICE_PREFIX --lang en
 1988  bin/console prestashop:config get PS_LANG_DEFAULT
 1989  bin/console prestashop:config remove PS_LANG_DEFAULT
 1990  bin/console prestashop:config get PS_LANG_DEFAULT

```

Thanks!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
