### PR TITLE
Don't check if an invalid address exists over and over again

### LINKED ISSUE #26754: Too many queries to test if address_id exists
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When there is a product in the cart and I'm not logged in, Prestashop is repeating this query 30 times

    SELECT SQL_NO_CACHE `id_address`  FROM ps_address a  WHERE a.`id_address` = 0 LIMIT 1

Additionally the logic is suspect, because the query does not check if the address is marked as deleted or if it is active. This would be necessary, since the addresses are soft-deleted in the address table.

The screenshot are from Profiling mode on a product page. Checking the individual queries in Stopwatch SQL shows that all queries are exactly the same.

### Expected behavior

Never check if address with `id_address = 0` exists. It must never exist.
Check only once if an address exists, remember the answer.
Even better: good execution logic would test only once for the existence of the address saved in the cart.

To-do:

- [x] #28321

- [ ]  Investigate the core of the issue to understand: why we are doing so much queries (related to how we store the adress in the cache of the cart) ?

### Steps to reproduce

1. Enable Profiling mode
3. Add a product to your cart
4. Scroll down to query doubles, you'll notice that there is 30x the same query on the table `address`.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | It's no use checking if an id_address <= 0 exists.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26754 (only when not logged in)
| How to test?      | Enable profiling mode, look for the query described in the issue, see it's not there.
| Possible impacts? | Nothing I can think of

Note: I wanted to add a local cache in the Cart class for the part that verifies if an address exists, but I found a weird thing with tax address during cart calculation. 

- If the shop is configured to use the **invoice address** for tax purposes, then the calculation will try to figure out the invoice address. 
- If the shop is configured to use the **shipping address** for tax, however, it will use whatever is stored as delivery address for each product in the cart (in `ps_cart_product`).

I don't really understand why does the cart hold the shipping address for each product. Is it to support different shipping addresses for the same order? But then, why is this attached to the cart, if it depends on the order?

Also, this is set to zero when you're a guest, and to your default address when you're logged in. So if you add a product to the cart while unlogged, and then you add another product when logged, they will have different shipping addresses stored, so the tax calculation will be different. Is this expected? Shouldn't the tax calculation be homogeneous within an order and therefore only use the shipping/invoice/inferred (if not logged) address? /cc @PrestaShop/product-team 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27406)

### CODE REVIEW

File: classes/Cart.php [hunk 1]
```diff
@@ -761,30 +761,30 @@ public function getProducts($refresh = false, $id_product = false, $id_country =
         $sql->leftJoin('image_shop', 'image_shop', 'image_shop.`id_product` = p.`id_product` AND image_shop.cover=1 AND image_shop.id_shop=' . (int) $this->id_shop);
         $sql->leftJoin('image_lang', 'il', 'il.`id_image` = image_shop.`id_image` AND il.`id_lang` = ' . (int) $this->getAssociatedLanguage()->getId());
 
-        $result = Db::getInstance()->executeS($sql);
+        $products = Db::getInstance()->executeS($sql);
```
Comment (PululuK) [inline classes/Cart.php]: To simplify the review, I think you can do this in another PR, because it not related I think.

Comment (eternoendless) [reply classes/Cart.php]: I moved those commits here: #27416

**Comment by jolelievre** [comment]
@eternoendless I can't be sure but I wonder if this multiple shipping addresses isn't related to the feature that allowed splitting orders It's an old feature that, I believe, isn't managed any more

That allowed you to split a single order into multiple orders (with the same reference though) I can see a few use cases when that was needed:
- in case a product wasn't available but others were thus splitting your delivery into multiple packages 
- when warehouses were handled (advanced stock management) the products could be stored in various warehouses thus forcing them to send multiple packages
 
Now, this is a long shot, but my guess is that different warehouses could have different associated carriers (depending on their location some carriers wouldn't be usable).

And another guess would be that since cart and order could be split into multiple packages each package could have a different shipping address which would explain the need to associate a shipping address to each product independently thus impacting the whole tax association and cart computing

It's a lot of guessing 😅. Bit in a nutshell I think this complexity is related to a lost feature, if it's not split orders or advanced stock it might be another But I don't see a current feature that would require assigning different shipping address to a cart product

**Comment by Matt75** [comment]
> That allowed you to split a single order into multiple orders (with the same reference though) I can see a few use cases when that was needed:
> 
> * in case a product wasn't available but others were thus splitting your delivery into multiple packages
> * when warehouses were handled (advanced stock management) the products could be stored in various warehouses thus forcing them to send multiple packages

* when allowed carriers for products in Cart are not compliant (It's not an old feature, this case is really common and we faced it often on support of PaymentModule, I opened multiple issues about multiple Orders for a Cart)

How to test : a product of Cart is restricted to one Carrier

Should be tested with different tax options, maybe we can reproduce a weird behavior

1. Install a fresh PrestaShop instance
2. Install PrestaShop Checkout module or another Payment module require validation from an API
3. Go to BO > Sell > Catalog > Products
4. Edit Product 1 aka Hummingbird printed t-shirt
5. In Shipping tab > Available carriers > check case of PrestaShop (Pick up in-store)
6. Save product
7. Edit Product 2 aka Hummingbird printed sweater
8. In Shipping tab > Available carriers > check case of My carrier (Delivery next day!)
9. Save product
10. Go to Shop
11. Go to product page of Product 1 aka Hummingbird printed t-shirt
12. Add to cart
13. Go to product page of Product 2 aka Hummingbird printed sweater
14. Add to cart
15. Go to Cart page
16. Go to Proceed to checkout
17. Choose to paid with PrestaShop Checkout
18. Paid
19. See Your order hasn't been validated yet, only created. There can be an issue with your payment or it can be captured later, please contact our customer service to have more details about it.
20. Go to BO > Sell > Orders
21. See 2 Orders created with same reference, only one is with status Payment accepted
22. View this Orders and see Warning €[TOTAL ORDER] paid instead of €[TOTAL CART]. This warning also concerns order [Order reference]

**Comment by jf-viguier** [comment]
>  Shouldn't the tax calculation be homogeneous within an order and therefore only use the shipping/invoice/inferred (if not logged) address?

Yes, there is only one shipping address in the order, tax has to follow this address.
If a product has no vat, it's a tva fraud.

**Review by davidglezz — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]
Code is good to me. Thank you @Matt75 for providing the great usecase. I think QA analysis will be very helpful

**Comment by marwachelly** [comment]
Hello,

I tested the PR and the querry "`SELECT SQL_NO_CACHE `id_address`  FROM ps_address a  WHERE a.`id_address` = 0 LIMIT 1`" doesn't exist any more after adding a product to the cart and when the profiling is active. But I don't have the link between the issue and the steps provided by @Matt75 in [this comment](https://github.com/PrestaShop/PrestaShop/pull/27406#issuecomment-1018298142). So I wasn't able to reproduce the issue.

@Matt75  Could you please updated the issue with more info in the steps to reproduce ?

Many thanks,

**Comment by eternoendless** [comment]
@marwachelly I think there was some mixup, the steps provided by @Matt75 seem to be irrelevant to this change, but related to a side discussion following my footnote.

If you don't see the query being performed again and again, it means that the change is valid.

**Comment by marwachelly** [comment]
> @marwachelly I think there was some mixup, the steps provided by @Matt75 seem to be irrelevant to this change, but related to a side discussion following my footnote.
> 
> If you don't see the query being performed again and again, it means that the change is valid.

The query  doesn't exist when adding product to the cart without logging in. So changes are valid and PR is QA approuved. 

Many thanks,

**Review by marwachelly — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @eternoendless & @marwachelly
