### PR TITLE
Fix free gift product in Order create page

### LINKED ISSUE #18119: [CREATE ORDER] Issues on vouchers adding gift products to the manually created cart
**ISSUE UPDATED**

Several issues related to vouchers with gift products added to the manually created order have appeared. To make it clear what are the expected behaviours, I've updated the [specifications on the create order page](https://github.com/PrestaShop/prestashop-specs/blob/MatShir-create-order/back-office/orders/orders/Create%20new%20order.md) (available in section III - voucher). Please review it and tell me if you have any comments or questions.

ping @matks @zuk3975 @Robin-Fischer-PS @MatShir 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -- - - - - - - - - - - - - - - 

**Current behavior**

Small difference between Legacy and Migrated page.

If I add a voucher with a Gift and another discount (amount, percentage...), if I remove the voucher : 
- Legacy : Voucher AND gift are deleted from the order
- Migrated page : Only the voucher is deleted, the gift stays in the order

For reminder, when adding a voucher only with a Gift, it is not possible to remove it either in Legacy or in Migrated page. The voucher is not displayed in the list.

Screenrecord of Legacy behavior : 
https://drive.google.com/file/d/1ShPcag0h5oNLtV4EpYCokMvtuwu8jEcs/view?usp=sharing

Screenrecord of Migrated behavior : 
https://drive.google.com/file/d/1IO8hy7bJoj9vyY1KYRaMfck_nJdyQSjg/view?usp=sharing

**Expected behavior**

Voucher gifts with or without other cart rules actions should be displayed on the voucher list.
If the voucher is deleted, it deletes the gift from the product list.

_Originally posted by @Robin-Fischer-PS in https://github.com/PrestaShop/PrestaShop/pull/17179#issuecomment-598200694_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Adds following feature to order create page in Back office - Once you add a cart rule with free-product action, the free product appears in products list, marked as a Gift and gift cart rule appears in vouchers list. Once you delete free gift voucher from cart, the gift product also dissapears. :warning: `There is another known issue - cart rule without code cannot be deleted, this pr doesn't fix that`.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #17085 (1st item), #18119
| How to test?  | Create a cart rule with action "send free gift = YES". Add that cart rule in your cart of Order create page in back office. You should see the gift product being added to a list marked as a gift instead of product price.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17179)

Screenshot from 2020-01-15 13-33-11

### CODE REVIEW

**Review by matks — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js [hunk 1]
```diff
@@ -31,6 +31,7 @@ import eventMap from '@pages/order/create/event-map';
 import Router from '@components/router';
 import SummaryRenderer from '@pages/order/create/summary-renderer';
 import ShippingRenderer from '@pages/order/create/shipping-renderer';
+import ProductRenderer from "./product-renderer";
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js]:
```suggestion
import ProductRenderer from './product-renderer';
```

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js [hunk 2]
```diff
@@ -47,10 +47,16 @@ export default class ProductRenderer {
     }
 
     const $productsTableRowTemplate = $($(createOrderMap.productsTableRowTemplate).html());
+    const $productsTableGiftRowTemplate = $($(createOrderMap.productsTableGiftRowTemplate).html());
 
     for (const key in products) {
       const product = products[key];
-      const $template = $productsTableRowTemplate.clone();
+
+      let $template = $productsTableRowTemplate.clone();
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: it's useless to clone twice, consume resource for nothing
```suggestion
      const $template = product.gift === true ? $productsTableGiftRowTemplate.clone() : $productsTableRowTemplate.clone();
```

File: src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php [hunk 3]
```diff
@@ -203,18 +203,13 @@ private function extractProductsFromLegacySummary(Cart $cart, array $legacySumma
...
-                \Tools::ps_round($product['price'], $currency->precision),
-                (int) $product['quantity'],
-                \Tools::ps_round($product['total'], $currency->precision),
-                $this->contextLink->getImageLink($product['link_rewrite'], $product['id_image'], 'small_default'),
-                $this->getProductCustomizedData($cart, $product)
-            );
+            $products[] = $this->buildCartProduct($cart, $currency, $product);
+        }
+
+        if (isset($legacySummary['gift_products'])) {
```
Comment (PierreRambaud) [inline src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php]:
```suggestion
        if (isset($legacySummary['gift_products']) && is_array($legacySummary['gift_products'])) {
```
I'm afraid about legacy data

File: src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php [hunk 4]
```diff
@@ -409,4 +404,21 @@ private function getProductCustomizedFieldsData(array $customizations, array $pr
 
         return $customizationFieldsData;
     }
+
+    private function buildCartProduct(Cart $cart, Currency $currency, array $product, bool $isGift = false): CartProduct
```
Comment (PierreRambaud) [inline src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php]:
```suggestion
    private function buildCartProduct(
        Cart $cart, 
        Currency $currency, 
        array $product, 
        bool $isGift = false
    ): CartProduct
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig [hunk 5]
```diff
@@ -218,6 +218,21 @@
   </tr>
 </script>
 
+<script id="products-table-gift-row-template" type="text/template">
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig:228]: Why not `<template>`? Should we support IE11?

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Question and little refactoring

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig (hunk 5 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig:228]: i guess we should :smile:

**Comment by zuk3975** [comment]
> Question and little refactoring

@PierreRambaud thanks for feedback. Addressed your comments

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig (hunk 5 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig:228]: I hope this kind of template is working everywhere :)

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig (hunk 5 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig:228]: If Im right you offered to use this instead of text/html that i was using before in some other pr :smile:

Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig:228]: You're maybe right :sweat_smile:

**Review by matks — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js [hunk 6]
```diff
@@ -47,10 +47,13 @@ export default class ProductRenderer {
     }
 
     const $productsTableRowTemplate = $($(createOrderMap.productsTableRowTemplate).html());
+    const $productsTableGiftRowTemplate = $($(createOrderMap.productsTableGiftRowTemplate).html());
 
     for (const key in products) {
       const product = products[key];
-      const $template = $productsTableRowTemplate.clone();
+
+      const $template = product.gift === true ? $productsTableGiftRowTemplate.clone() : $productsTableRowTemplate.clone();
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]:
```suggestion
      const $template = product.gift === true ? $(createOrderMap.productsTableGiftRowTemplate).clone() : $(createOrderMap.productsTableRowTemplate).clone();
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback @zuk3975

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js (hunk 6 above)
Comment (matks) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: Why ? Your suggestion is making the line longer 😮 it's harder to read now.
Why clutter this nice statement with meaningful and shortened variable names ?

And why block the PR for such a small thing 😞

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: Because it's a memory optimization : that avoids to recreate a second jquery object for the same element. With this change, we can remove `$productsTableGiftRowTemplate` which become unuseful and memory hungry.

Comment (matks) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: Source: http://www.commitstrip.com/en/2015/07/23/for-a-few-bytes-more/

Comment (matks) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: Also: [Make it work, make it right, make it fast](https://tknilsson.com/2018/05/25/programmer-friday-make-it-work-make-it-right-make-it-fast/)

The "make it fast" should happen **at the end**. Right now a lot of code on PrestaShop does not work, and even more is not right.

Moreover, the provided article clearly states it:
_"When you start to optimize for speed, your codebase often takes on more complexity and becomes harder to understand and work with. A highly optimized loop is harder to read. A cache adds complexity and moving parts._

_Many software systems only need to work, they don’t require any special tuning for performance. Consider the usage scenario, the target audience, and do performance testing to figure out if more performance is necessary."_

I think this optimization is decreasing the code readability and that the memory consumption benefit is insignificant. Moreover you are blocking this PR which is a must-have item for 1.7.7 for such an insignificant part of the PR 😞 . Please think about it, I'm asking you to change your mind 🙏  .

Comment (matthieu-rolland) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: I think both of you are right, on different perspectives. ;) 

It's true that @zuk3975 's proposal makes it easier to read, it's also true that it increases browser's memory consumption, even though it's probably not that bad (given this is BO, not FO).

A third option, that would both keep @Progi1984 's optimization and @zuk3975 's readability, would be to extract the condition in a properly named function, for example **getProductsTemplate**, since the purpose of this condition is to define products's template (maybe you can think of a better name?)

```js
  const $template = this._getProductsTemplate();
```

And the function:

```js
  _getProductsTemplate() {
    return product.gift === true ? $(createOrderMap.productsTableGiftRowTemplate).clone() : $(createOrderMap.productsTableRowTemplate).clone();
  }
```
Extracting hard to read conditions into properly named functions is generally accepted as a good practice (notably in the book **clean code**).

But I really think we are nitpicking over tiny details here 😃 😃

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: Yep @matthieu-rolland proposal seems the cleaner, the code readability is important but jquery objects are quite heavy and shouldn't be created without reason.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: The method name might be something like `cloneProductTemplate(product)` though

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: I approve it ;) Thanks @matthieu-rolland

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig [hunk 7]
```diff
@@ -218,6 +218,21 @@
...
+  <tr>
+    <td><img class="js-product-image" src="" alt=""></td>
+    <td class="js-product-definition-td">
+      <p class="mb-0 js-product-name"></p>
+      <p class="js-product-attr"></p>
+    </td>
+    <td class="js-product-ref"></td>
+    <td>{{ 'Gift'|trans({}, 'Admin.Catalog.Feature') }}</td>
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig]:
```suggestion
    <td>{{ 'Gift'|trans({}, 'Admin.Orderscustomers.Feature') }}</td>
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig [hunk 8]
```diff
@@ -218,6 +218,21 @@
...
+    <td class="js-product-gift-qty"></td>
+    <td class="js-product-total-price">{{ 'Gift'|trans({}, 'Admin.Catalog.Feature') }}</td>
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig]:
```suggestion
    <td class="js-product-total-price">{{ 'Gift'|trans({}, 'Admin.Orderscustomers.Feature') }}</td>
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 9]
```diff
@@ -536,6 +536,10 @@ private function getErrorMessages(Exception $e)
                     'Positive product quantity is required',
                     'Admin.Notifications.Error'
                 ),
+                CartConstraintException::UNCHANGED_QUANTITY => $this->trans(
+                    'Product quantity is already the same as in cart',
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: What action leads to this notification?

Comment (zuk3975) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: Example:

- Product A exists in cart.

- Product A has quantity of 10.

- I search for Product A again and try to add it to cart with quantity of 10.

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 9 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]:
```suggestion
                    'Same product quantity is already in cart',
```

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@zuk3975 Pretty CI is :red_circle: ; Could you fix it ? And fixing this wording change https://github.com/PrestaShop/PrestaShop/pull/17179#discussion_r375861428 ? Thanks
@LouiseBonnard Could you check to wording ? Thanks :)

**Comment by LouiseBonnard** [comment]
@Progi1984, it is all fine for me except this suggestion: https://github.com/PrestaShop/PrestaShop/pull/17179#discussion_r375861428. :-)

**Comment by zuk3975** [comment]
@Progi1984 Fixed.

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 9 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: Fixed in https://github.com/PrestaShop/PrestaShop/pull/17179/commits/07613459013fa55a9b49537973a31f6f427ed252

**Review by Progi1984 — DISMISSED** [review]

**Comment by zuk3975** [comment]
reopen to restart prettyCI

**Comment by zuk3975** [comment]
reopen last try for prettyCI

**Review by matks — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matks — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @zuk3975 !

I have a small difference between Legacy and Migrated page.

If I add a voucher with a Gift and another discount (amount, percentage...), if I remove the voucher : 
- Legacy : Voucher AND gift are deleted from the order
- Migrated page : Only the voucher is deleted, the gift stays in the order

For reminder, when adding a voucher only with a Gift, it is not possible to remove it either in Legacy or in Migrated page.

Screenrecord of Legacy behavior : 
https://drive.google.com/file/d/1ShPcag0h5oNLtV4EpYCokMvtuwu8jEcs/view?usp=sharing

Screenrecord of Migrated behavior : 
https://drive.google.com/file/d/1IO8hy7bJoj9vyY1KYRaMfck_nJdyQSjg/view?usp=sharing

I would like a PM validation for the good behavior, since (in my opinion) both are "a bit strange".

@MatShir , I need you !

**Comment by MatShir** [comment]
Thanks @Robin-Fischer-PS for your report. Indeed, the behaviors are not ideal. It is a bug and a regression. I created a new issue https://github.com/PrestaShop/PrestaShop/issues/18119

**Comment by MatShir** [comment]
@zuk3975 since QA has validated this PR, would you prefer to fix the bug on this one or create a new one?

**Comment by zuk3975** [comment]
> @zuk3975 since QA has validated this PR, would you prefer to fix the bug on this one or create a new one?

@MatShir , Ill stay on this one. Added wip label and referenced the issue already.

File: src/Core/Domain/Cart/QueryResult/CartInformation/CartProduct.php [hunk 10]
```diff
@@ -197,4 +205,12 @@ public function getCustomization(): ?Customization
     {
         return $this->customization;
     }
+
+    /**
+     * @return bool
+     */
+    public function isGift(): bool
```
Comment (jolelievre) [inline src/Core/Domain/Cart/QueryResult/CartInformation/CartProduct.php:212]: I don't see any use off this getter, and I also wonder where in the template or the javascript is this data injected?

File: admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js [hunk 11]
```diff
@@ -90,6 +90,7 @@ export default class CartRuleManager {
     EventEmitter.on(eventMap.cartRuleAdded, (cartInfo) => {
       const cartIsEmpty = cartInfo.products.length === 0;
       this.cartRulesRenderer.renderCartRulesBlock(cartInfo.cartRules, cartIsEmpty);
+      this.productRenderer.renderList(cartInfo.products);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js:93]: Why do you need to update the product list here? Does the cart rule affect the product rendering?

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js:93]: Oh I get it, it's cart rule that adds the gift product right? Hence the products re-rendering

**Review by jolelievre — COMMENTED** [review]
Hi @zuk3975 is this PR still in WIP?

File: admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js (hunk 11 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/order/create/cart-rule-manager.js:93]: yes

**Comment by zuk3975** [comment]
> Hi @zuk3975 is this PR still in WIP?

Yes, Its wip because of the last found bug.

File: src/Core/Domain/Cart/QueryResult/CartInformation/CartProduct.php (hunk 10 above)
Comment (zuk3975) [reply src/Core/Domain/Cart/QueryResult/CartInformation/CartProduct.php:212]: most of this class getters have no usage. I generated all of them i think, its basically a DTO which is used (after converting to json) in javascript.
I think json serializing would fail due to private properties without getters behind the scenes.

**Comment by zuk3975** [comment]
WIP check if classes/Cart::getSummaryDetails changes didn't ruin other pages where its used.
EDIT: removed changes from legacy class. Retrieved gift cart rules in getCartInformationHandler instead.

**Comment by zuk3975** [comment]
Done :heavy_check_mark:

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @zuk3975 !

Four issues with the new behaviour : 

- If I have a paid product, and the same product, but gifted, in my cart, if I delete the paid product, it will also delete the gifted product (the voucher is still displayed). The deletion should only delete the paid product. See screenrecord at the bottom of the comment for this bug (between 01:00 and 01:20).

- If I have a gifted product in my cart (with quantity "1"), and then I try to add the same product, but paid, an error is displayed "Same product quantity is already in cart" and nothing is added.
If I have two gifted products (same product), and then I try to add the same product, but paid, the two gifted product are replaced by only one gifted product (and no paid product). See screenrecord at the bottom of the comment for this bug (between 00:20 and 00:55).

- When adding several vouchers that offers the same product as a gift, there is one line for each gift (like in Legacy, so OK), but the quantity displayed is wrong : The total quantity of this product is displayed, instead of "1".

On my example below, I added the "Best is yet to come Mug" once as a paid item, and four times as a gift (with 4 different vouchers). There is one line for each mug in the cart, with a quantity set to "5" each time, instead of being set to "1" for each. When I create the order, the total quantity for the mug is OK (5 products, and not 25).
pr17179 gift product bad quantity

- When a voucher effect is "Free Gift" + something else (Free shipping, Amount discount or percent discount), the voucher is displayed two times : One with the "gift" discount", and one for the other effect.
pr17179 duplicated vouchers

Screenrecord for these behaviours : 
https://drive.google.com/file/d/1Pz9-0xBO1a1FaKk2qmdFyWSa-c25oLqM/view?usp=sharing

If something is not clear, don't hesitate to ping me, it's quite complex to explain sometimes ^^

**Comment by zuk3975** [comment]
> Four issues with the new behaviour :

Oh my god, here we go again :sob:

**Comment by matks** [comment]
@Robin-Fischer-PS and @MatShir This PR was started on 15th of January. We are once again in the nightmare scenario of endless QA feedbacks. We must do something, else we will continue consuming @zuk3975 motivation and time for weeks and 1.7.7 will never be out.

@Robin-Fischer-PS @MatShir Could you please write a dedicated set of specifications for this bug, and then we implement **exactly** what is described in the document, @Robin-Fischer-PS will test **exactly** what is described in the document and we can merge this ?

Take all the time you need to write this document, it will never be wasted time and it will save all of us lot of time.

**Comment by zuk3975** [comment]
1 bug -WIP: behats passes, but getCartInformation in ajax call is still returning cartrules, which shouldnt exist.

**Comment by zuk3975** [comment]
done :heavy_check_mark:

**Comment by colinegin** [comment]
@zuk3975 did you check all behaviours I wrote in the specifications ? It's not limited to what Mateus had previously written in the issue.

**Comment by zuk3975** [comment]
> @zuk3975 did you check all behaviours I wrote in the specifications ? It's not limited to what Mateus had previously written in the issue.

In progress. Found at least one bug already.

**Review by matks — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: classes/Cart.php [hunk 12]
```diff
@@ -756,7 +756,7 @@ public function getProducts($refresh = false, $id_product = false, $id_country =
             $givenAwayProductsIds = [];
 
             // Do not recalculate in case of refresh
```
Comment (Progi1984) [inline classes/Cart.php]: The comment seems not sync with the `if`

Comment (zuk3975) [reply classes/Cart.php]: yea thanks for noticing. In fact i need an advice here. This if stmt was not making any sense, but it was made on purpose by someone, so idk if i didn't break anything :( . There is only one public action which changes the $splitFiftProductsQuantity to true (cart::getProductsWithSeparatedGifts), but it also forces the $refresh to be true, so the gifts were never recalulated..
So I've decided that was just a mistake and removed the "!" from refresh.
In this case I should also align the comment to absolute opposite (as in the code too.) "Recalculate in case of refresh" Do these changes make sense to you?

**Review by Progi1984 — COMMENTED** [review]
A small feedback

File: classes/Cart.php (hunk 12 above)
Comment (Progi1984) [reply classes/Cart.php]: For me, yes :+1:

**Comment by zuk3975** [comment]
> A small feedback

deleted above mentioned useless comment from code.

**Review by matks — DISMISSED** [review]

File: classes/Cart.php [hunk 13]
```diff
@@ -3838,7 +3837,7 @@ public function getSummaryDetails($id_lang = null, $refresh = false)
 
             if ($cart_rule['gift_product']) {
                 foreach ($products as $key => &$product) {
-                    if (empty($product['gift']) && $product['id_product'] == $cart_rule['gift_product'] && $product['id_product_attribute'] == $cart_rule['gift_product_attribute']) {
+                    if (empty($product['is_gift']) && $product['id_product'] == $cart_rule['gift_product'] && $product['id_product_attribute'] == $cart_rule['gift_product_attribute']) {
```
Comment (jolelievre) [inline classes/Cart.php:3839]: Isn't this a BC break?

Comment (zuk3975) [reply classes/Cart.php:3839]: not 100 % sure, but it seems just a mistake. Everywhere else is "is_gift", thats why this if stmt seems to be impossible to break through.

**Review by matks — DISMISSED** [review]

File: classes/Cart.php [hunk 14]
```diff
@@ -3866,7 +3865,7 @@ public function getSummaryDetails($id_lang = null, $refresh = false)
                         $gift_product['price_wt'] = 0;
                         $gift_product['total_wt'] = 0;
                         $gift_product['total'] = 0;
-                        $gift_product['gift'] = true;
+                        $gift_product['is_gift'] = true;
```
Comment (jolelievre) [inline classes/Cart.php:3868]: To answer your comment https://github.com/PrestaShop/PrestaShop/pull/17179/files#r405261136
The problem is more on this line because `Product::getSummaryDetails` is used elsewhere, so if the array field `gift` becomes `is_gift` it changes the expected data returned by this function no?
Unless this was a bug to use `gift` and the expected result is actually to use `is_gift` ?

Comment (jolelievre) [reply classes/Cart.php:3868]: From what I can see in `Cart::getProducts` it seems like `is_gift` is expected you're right! But then I think there is the same mistake in CartRule https://github.com/PrestaShop/PrestaShop/blob/8415bca965c74ff96e211f987c98b648fa8bd0d8/classes/CartRule.php#L767

**Review by matks — DISMISSED** [review]

File: classes/Cart.php (hunk 14 above)
Comment (Progi1984) [reply classes/Cart.php:3868]: Ping @zuk3975

Comment (zuk3975) [reply classes/Cart.php:3868]: changed that too. ['gift'] to ['is_gift'].

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hello @zuk3975 , thanks for your contribution, would you mind to rebase your pull request and rebuild assets before merging ? Thanks

**Comment by matks** [comment]
@prestashop-issue-bot :trollface: :trollface: :trollface:

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
