### PR TITLE
Fix preview in multilang

### LINKED ISSUE #34191: Preview Disabled Product & Multiples languages
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I duplicate a product in multilingual shop and I preview it in FrontOffice, I can't change the language

### Expected behavior

When I duplicate a product in multilingual shop and I preview it in FrontOffice, I can change the language

### Steps to reproduce

1. Install a shop in English / France
2. Go to BO > Catalog > Products
3. Click on Preview for the first line (for example) : Customizable mug
4. :heavy_check_mark: That go to FrontOffice > Product Page in English
5. Change the language to French 
6.  :heavy_check_mark: That go to FrontOffice > Product Page in French
7. Return to BO
8. Duplicate this product
9. :heavy_check_mark: It's disabled
10. Click on Preview for the first line (for example) : Customizable mug
11.  :heavy_check_mark: That go to FrontOffice > Product Page in English
12. Change the language to French
13. :red_circle: That go to FrontOffice > Categories

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Fixes issue where switching languages on a disabled product preview page redirects to the home page instead of staying on the product preview in the selected language.<br><br>**Root Cause:**<br>When switching languages, `getLanguageLink()` did not preserve preview parameters (`preview`, `id_employee`, `adtoken`), and `canonicalRedirection()` was redirecting preview URLs.<br><br>**Changes made:**<br>1. **`classes/Link.php`**: Modified `getLanguageLink()` to preserve preview parameters when switching languages on product pages<br>2. **`controllers/front/ProductController.php`**: Modified `canonicalRedirection()` to skip redirection when in preview mode
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | **Prerequisites:** Shop with at least 2 languages installed (e.g., English and French)<br><br>**Test Steps:**<br>1. Go to BO > Catalog > Products, duplicate a product (it will be disabled)<br>2. Click "Preview" on the duplicated product<br>3. Switch language using the language switcher in FO<br><br>**Expected:** You remain on the product preview page in the new language (not redirected to home)<br><br>**Regression tests:**<br>- Enabled product preview: language switching should work as before<br>- Regular product page (non-preview): language switching should work as before
| UI Tests          | https://github.com/tleon/ga.tests.ui.pr/actions/runs/20785418501
| Fixed issue or discussion?     | Fixes #34191
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]
Thanks Thomas, I believe it will work correctly.

Just a question - is there a way to move the code with parameters outside the link class? Is it the class responsibility to know something about `preview` params?

**Review by boherm — DISMISSED** [review]

**Review by jolelievre — CHANGES_REQUESTED** [review]
@Hlavtox I agree with you but I don't think we can easily apply this somewhere else The link of the lanague selector are generated by smarty which uses this method
So we're a bit stuck

However @tleon I think we could move this extra code into `Link::getProductLink` instead, it makese sense since the preview exception is only for product AFAIK And this way we get a generic implementation for other links in the page as well

**Comment by jolelievre** [comment]
However, I think we should add a check in getProductLink only add the preview parameter if `$_GET['id_product'] === $product` This way only the url of the current product page is impacted

**Comment by Hlavtox** [comment]
@tleon @jolelievre What about if product controller had it's own `getAlternativeLangsUrl`? It's a common practice that controllers impoement their own behavior, if FrontController is not fitting exactly.

ps_languageselector uses getLanguageLink directly, but it would be easy to release a new version that would use getAlternativeLangsUrl from the current controller. It would also make it much easier for module controllers to provide these links correctly. It's a bad practice anyway for a TPL to call $link->getLanguageLink inside.

**Comment by jolelievre** [comment]
@Hlavtox but from what I found the URLs are not generated by the controller that's the problem it comes from `ps_languageselector.tpl`

```
{foreach from=$languages item=language}
          <li {if $language.id_lang == $current_language.id_lang} class="current" {/if}>
            <a href="{url entity='language' id=$language.id_lang}" class="dropdown-item" data-iso-code="{$language.iso_code}">{$language.name_simple}</a>
          </li>
        {/foreach}
```

Do you have an example of `getAlternativeLangsUrl` that could replace these values?

**Comment by Hlavtox** [comment]
@jolelievre See updated comment

> Do you have an example of getAlternativeLangsUrl that could replace these values?

Not exactly, but canonicalredirection method is a nice example.

**Comment by jolelievre** [comment]
But `getAlternativeLangsUrl` is only used for head tags, it's not adapted for the language selector, or we would need to update the template from both themes as well, which doesn't seem that efficient

**Comment by Hlavtox** [comment]
@jolelievre They should be exactly the same, if I remember correctly. (On my phone now.) We would have single source of truth.

The language selector is only a basic link, it doesnt post anything like a currency switch.

You would just:
- add new method to productcontroller
- In ps_languageselector pass this->context->controller->getAlternateLangsUrl()
- Use the links directly in the switch

**Review by jolelievre — DISMISSED** [review]

**Comment by jolelievre** [comment]
@Hlavtox the current fix is acceptable IMHO (for legacy code)

**Comment by Hlavtox** [comment]
Jo, we are not planning to migrate the front office anytime soon, I think we can do it properly, if it takes about 5 minutes more, right?

**Comment by jolelievre** [comment]
I don't think it's that quick 🤔 What you suggest implies updating two themes, for a feature that didn't exist previously AFAIK, and we just discovered it. If you have a quick fix that takes 5 minutes with only a PR on the core, we're open to suggestions, though

Regarding the FO migration, I don't know when it will start

**Comment by Hlavtox** [comment]
@jolelievre The language block is using the exact same links as `getAlternateLangsUrl`. It's making the links by using the custom `url` smarty method, which is calling a method in `Link` class, which calling `$context->link->getLanguageLink($params['id'])`. Exactly the same as `getAlternateLangsUrl` in `FrontController` does - `$langUrl = $this->context->link->getLanguageLink($lang['id_lang']);`.

So, you just add this to ProductController:

```
    public function getAlternativeLangsUrl()
    {
        $alternateLangsUrl = parent::getAlternativeLangsUrl();

        if ($this->isPreview()) {
            // Append preview and employee params to lang urls
            foreach ($urls as &$url) {
                $url .= (strpos($url, '?') === false ? '?' : '&') 
                    . http_build_query([
                        'preview' => 1,
                        'id_employee' => Tools::getValue('id_employee'),
                        'adtoken' => Tools::getValue('adtoken'),
                    ]);
            }
        }

        return $alternateLangsUrl;
    }
```

And inside `ps_languageselector.php` `getWidgetVariables` add specific urls to the smarty by calling `$this->context->controller->getAlternativeLangsUrl();` and modify the TPL.

No need to mess up Link class, no need to check the current controller, one single source of truth where the language links are coming from.

**Review by nicosomb — DISMISSED** [review]

**Comment by Progi1984** [comment]
@tleon Hi, could you uncomment the line 284 (and remove l.283) in file `tests/UI/campaigns/functional/BO/03_catalog/01_products/22_bulkActionsEnableDisable3DotsButton.ts` ? (And restart your E2E Tests, please)

File: tests/UI/campaigns/functional/BO/03_catalog/01_products/22_bulkActionsEnableDisable3DotsButton.ts [hunk 1]
```diff
@@ -281,7 +281,7 @@ describe('BO - Catalog - Products list : Bulk actions, Enable/Disable, 3-dot but
 
         page = await boProductsPage.clickOnPreviewProductButton(page);
         // @todo : https://github.com/PrestaShop/PrestaShop/issues/34191
```
Comment (Progi1984) [inline tests/UI/campaigns/functional/BO/03_catalog/01_products/22_bulkActionsEnableDisable3DotsButton.ts]:
```suggestion
```

**Review by Progi1984 — COMMENTED** [review]
A small comment

**Review by jolelievre — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]
The code could be simplified, and it's not the cleanest solution - in my opinion, but it's acceptable anyway 👍🏻

Better not to waste more time on such a trivial issue 👍🏻

**Comment by Progi1984** [comment]
@tleon Could you restart your failed E2E Tests, plz ?

**Comment by Hlavtox** [comment]
@jolelievre @kpodemski The issue is there probably for like 10 years, and suddenly we need a half-clean solution quick?

Why are we now accepting hackjobs?

You all know that doing something with current URL parameters inside a getProductLink method is not correct.

**Comment by kpodemski** [comment]
@Hlavtox 

This time, I disagree with you. In my opinion, fixing a preview feature doesn't belong in a `ps_languageselector` module, because if you use `getProductLink` outside this module, it will strip `adtoken` and `preview` params anyway, and we want to avoid that. The problem is inside `Link::getProductLink`, not elsewhere.

This change also works for `getAlternativeLangsUrl` becauase inside it's calling `Link::getLanguageLink` which points to the `getProductLink` 🤷🏻 We keep the scope inside `getProductLink` and **that's ok**, we don't use `adtoken` and preview feature anywhere else in the system.

**Comment by kpodemski** [comment]
@tleon could you restart the failed test?

**Comment by Hlavtox** [comment]
@kpodemski I don't want to fix it in `ps_languageselector` module, I want `ps_languageselector` to use the same source of truth as canonical URLs - controller's `getAlternativeLangsUrl`.

And I want `ProductController` to extend `getAlternativeLangsUrl` with it's own behavior.

**Review by Hlavtox — DISMISSED** [review]
F it, no solution is perfect anyway :D

**Review by SiraDIOP — COMMENTED** [review]
Hello @tleon, 

Could you please restart the automated tests?
https://github.com/tleon/ga.tests.ui.pr/actions/runs/19958574390

Thanks

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -88,6 +88,20 @@ public function canonicalRedirection(string $canonical_url = ''): void
             $this->id_product_attribute = null;
         }
 
+        // Preserve preview parameters if we're in preview mode or if preview parameters are in the URL
+        $extraParams = [];
+        if ($this->isPreview() || (isset($_GET['preview']) && $_GET['preview'] == '1')) {
```
Comment (kpodemski) [inline controllers/front/ProductController.php]:
```suggestion
        if ($this->isPreview()) {
```

I think this check is enough by taking a look at:
```
if ('1' === Tools::getValue('preview')) {
            $adminTokenValidator = $this->getContainer()->get(LegacyAdminTokenValidator::class);
            $isAdminTokenValid = $adminTokenValidator->isTokenValid((int) Tools::getValue('id_employee'), Tools::getValue('adtoken'));
            if ($isAdminTokenValid) {
                $this->setPreviewMode();
            }
        }
```
I'm also not sure why are you forced to add this code again, you added it inside `getProductLink` which is called in the canonical redirection, so you have those checks already there 🤔

Comment (Hlavtox) [reply controllers/front/ProductController.php]: @tleon @kpodemski I think the product canonical URL should not change. If its preview or not, doesnt matter. The URL should be the same.

Comment (kpodemski) [reply controllers/front/ProductController.php]: let's wait for @tleon feedback, I tested his change previously and it worked, I don't see a reason to change the canonical URL

Comment (tleon) [reply controllers/front/ProductController.php]: I was trying something to fix my failing UI test but I will revert it did not help me :/

**Review by kpodemski — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
The last change with product page seems not relevant and not very clean implementation.

File: controllers/front/ProductController.php [hunk 3]
```diff
@@ -194,7 +194,24 @@ public function checkPermissionsToViewProduct(): void
 
         // Now the checks for public
         // If product is disabled or doesn't belong to this shop, we respect the redirection settings
-        if (!$this->product->isAssociatedToShop() || !$this->product->active) {
+        // Also check redirects for active products if a redirect is explicitly configured
+        $shouldCheckRedirect = !$this->product->isAssociatedToShop() || !$this->product->active;
```
Comment (Hlavtox) [inline controllers/front/ProductController.php]: Why did you add this code? There is no redirect for active product. :-)

File: tests/UI/campaigns/functional/BO/03_catalog/01_products/18_seoTab.ts [hunk 4]
```diff
@@ -227,13 +228,29 @@ describe('BO - Catalog - Products : Seo tab', async () => {
...
       // Click on preview button
       page = await boProductsCreatePage.previewProduct(page);
+      // Wait for redirect to complete (product is enabled, so redirect should work)
+      await page.waitForURL('**/*', {waitUntil: 'networkidle'});
+      const currentUrl = await foClassicProductPage.getCurrentURL(page);
+      const newUrl = currentUrl.split('token');
+      await foClassicProductPage.goTo(page, newUrl[0]);
       await foClassicProductPage.changeLanguage(page, 'en');
 
+      // When product is enabled, redirect should work - should redirect to 'Hummingbird printed t-shirt'
```
Comment (Hlavtox) [inline tests/UI/campaigns/functional/BO/03_catalog/01_products/18_seoTab.ts]: No, redirection concerns only disabled products

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Some nonsense code inside

File: controllers/front/ProductController.php [hunk 5]
```diff
@@ -194,7 +194,24 @@ public function checkPermissionsToViewProduct(): void
...
+
+        // For active products, also check redirect if one is explicitly configured
+        if (!$shouldCheckRedirect && $this->product->active) {
```
Comment (jolelievre) [inline controllers/front/ProductController.php]: I'm not sure to understand either, the redirection is only useful for disabled product, so why handle this on active products?

**Review by Hlavtox — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by SiraDIOP** [comment]
Hello @tleon, 

Thanks for your PR, i tested it and it's good for me ^^


https://github.com/user-attachments/assets/e9f70ef8-35da-4be3-b09c-732fd174ba18

https://github.com/user-attachments/assets/9620042b-8230-45e8-bffb-cdfd6837347e

Thanks

**Review by SiraDIOP — DISMISSED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Locked for UI Tests

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]
Approval for E2E Tests
