### PR TITLE
Fix conversion of hex color codes

### LINKED ISSUE #31002: Invalid conversion from 3-char hex-color to 6-char hex color
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Here the formula to convert from 3-char hex-color to 6-char hex color is wrong https://github.com/PrestaShop/PrestaShop/blob/dcdd11673033095fd31b65cca6d9ddb0325464c3/src/Core/Util/ColorBrightnessCalculator.php#L62-L64 

For instance, the color `#0F1` will be converted to `#0F10F1`, which is wrong. `#00FF11` would be correct

### Expected behavior

I expect the conversion from 3-char hex-color to 6-char hex color to give a correct result.

### Steps to reproduce

For devs, not QA-team 😉 
1. Look at this code https://github.com/PrestaShop/PrestaShop/blob/dcdd11673033095fd31b65cca6d9ddb0325464c3/src/Core/Util/ColorBrightnessCalculator.php#L62-L64
2. Imagine what it does and compare to standards

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fix conversion of hex color codes (used for the display of the order state's colors in the BO)
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | The color #0F1 is handled as dark color (#0F10F1), but should be handled as bright (#00FF11). see https://github.com/PrestaShop/PrestaShop/issues/31002#issuecomment-1401527109
| Fixed ticket?     | Fixes #31002
| Related PRs       | Non
| Sponsor company   | Société Biblique de Genève

### CODE REVIEW

**Review by FabienPapet — APPROVED** [review]

**Review by FabienPapet — CHANGES_REQUESTED** [review]
Can you please add a test for this ? 
(\Tests\Unit\Core\Util\ColorBrightnessCalculatorTest::getColors)

**Review by FabienPapet — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: src/Core/Util/ColorBrightnessCalculator.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ private function calculate($hexColor)
         $hexColor = str_replace('#', '', $hexColor);
 
         if (strlen($hexColor) === 3) {
-            $hexColor .= $hexColor;
+            $hexColor = $hexColor[0] . $hexColor[0] . $hexColor[1] . $hexColor[1] . $hexColor[2] . $hexColor[3];
```
Comment (0x346e3730) [inline src/Core/Util/ColorBrightnessCalculator.php]: Shouldn't it be like
```suggestion
            $hexColor = $hexColor[0] . $hexColor[0] . $hexColor[1] . $hexColor[1] . $hexColor[2] . $hexColor[2];
```

?

**Review by 0x346e3730 — CHANGES_REQUESTED** [review]

**Review by mflasquin — CHANGES_REQUESTED** [review]
Please see @0x346e3730 suggestion

**Review by FabienPapet — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

File: src/Core/Util/ColorBrightnessCalculator.php (hunk 1 above)
Comment (lmeyer1) [reply src/Core/Util/ColorBrightnessCalculator.php]: Sorry, I missed that.

**Review by 0x346e3730 — DISMISSED** [review]

File: src/Core/Util/ColorBrightnessCalculator.php (hunk 1 above)
Comment (0x346e3730) [reply src/Core/Util/ColorBrightnessCalculator.php]: No worries it's a small typo it can happen, thank you for your contribution !

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]
@lmeyer1 Lorenz, can you also fix it in Tools::getBrightness? The code is the same, just copy paste. :-)

**Review by FabienPapet — APPROVED** [review]

**Comment by FabienPapet** [comment]
@Hlavtox I did it and rebased

**Review by lartist — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
@PrestaShop/prestashop-maintainers @PrestaShop/prestashop-core-developers the related issue is in the status `TBR` by a developer, so could you please reproduce the issue and validate, then test the PR :pray:

**Review by Hlavtox — APPROVED** [review]
Lets go

**Comment by FabienPapet** [comment]
ping @florine2623 same process for test as I showed you, but instead of text-colors we are using 3 digits hex colors

**Comment by hibatallahAouadni** [comment]
Ping @FabienPapet the author Mr @lmeyer1 made it clear that the issue must be validated by a Dev

image

So, before testing the PR, the related issue should be validated :relaxed: :pray: 

Thanks for your understanding :pray:

**Comment by FabienPapet** [comment]
@hibatallahAouadni 
The problem has been reproduced and is fixed by this PR so the issue is valid.
The fix is good, they are unit tests to assert it. I tested it myself. If this should be tested by a dev, it's already qa ✔️ 
Also, the issue can be tested by @florine2623 because we had a meet and we already talked about this issue and how this can be tested.

Now if you want to discuss further no need to change the labels again, just send a PM to either @florine2623 or me.
If the QA does not need to test it, just put the QA ✔️

**Review by florine2623 — APPROVED** [review]
Hello @lmeyer1 ,

Tested your PR !

I have the correct behavior. The hex color is well calcultaed and the brightness is well adjusted.

Tested with `#890`, I have `#889900` instead of this `#890890` ✅ 
Screenshot 2023-01-27 at 10 12 01

Tested with `#C59`, I have `#CC5599` instead of `#C59C59` ✅ 
Screenshot 2023-01-27 at 10 15 20


It is QA ✅ 
Before merging, would it be possible to get reviews to get this part green ?
Screenshot 2023-01-27 at 10 10 07

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @lmeyer1 🎉
