### PR TITLE
Fix shared smarty compilation ID across shops / themes

### LINKED ISSUE #9763: [BOOM-4673] Shopping cart multi-store
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4673).

- _**Reporter:**_ alexandre@weggs.fr
- _**Created at:**_ Mon, 22 Jan 2018 12:00:45 +0100

<p>Hi !</p>

<p>I have activate multistore with two different themes.</p>

<p>When i add a product in cart in the second shop, the html element .blockcart is well updated but it update also the .blockcart element on the other shop.</p>

<p>If compilation is set on force compilation for each call, it doesn't append. Seems to be a file name cahce problem ?</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by 202-ecommerce**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In all version of PS 1.7, if you have several shops with different theme, they share the same compile ID. Consequently first theme in cache are used for all shops.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9763
| How to test?  | Install two shops with two different theme with cache active and force compile off. Each shop should be load its right theme. You can although try with a child theme and modify for instance only one template (for instance footer.tpl).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13804)

### CODE REVIEW

**Comment by Matt75** [comment]
202 is in da place 🤘

**Review by ewing03 — DISMISSED** [review]

**Comment by matks** [comment]
Looks good 😄 

I have only one thing I'm wondering 🤔 : shall we sanitize the theme name ? I'm not sure Smarty will work good with a `$compile_id` with blank spaces in it, or some exotic characters.

**Comment by 202-ecommerce** [comment]
> Looks good smile
> 
> I have only one thing I'm wondering thinking : shall we sanitize the theme name ? I'm not sure Smarty will work good with a `$compile_id` with blank spaces in it, or some exotic characters.

Smarty compile ID is the prefix of the php file like : 009d1d5ab292ee56d60f8ada9924c91562919f4e.file.footer.tpl.php

The compile ID is a hash (sha1) of the string submitted.

**Comment by matks** [comment]
> > Looks good smile
> > I have only one thing I'm wondering thinking : shall we sanitize the theme name ? I'm not sure Smarty will work good with a `$compile_id` with blank spaces in it, or some exotic characters.
> 
> Smarty compile ID is the prefix of the php file like : 009d1d5ab292ee56d60f8ada9924c91562919f4e.file.footer.tpl.php
> 
> The compile ID is a hash (sha1) of the string submitted.

Then it's fine 👍 thanks ! let's go for QA

**Review by matks — DISMISSED** [review]

**Comment by sarahdib** [comment]
Hello @202-ecommerce 

Thank you for your contribution.

I made some test but the problem is still there, in my first shop using the classic theme this is the preview

Capture d’écran 2019-05-16 à 16 40 33


In the second shop with minimal theme it's ok 

Capture d’écran 2019-05-16 à 16 44 47

**Comment by 202-ecommerce** [comment]
Hi @sarahdib 

I just do the same things as you.

On my first shop : your classic theme
On the second shop : your starter theme

In the frontoffice, each shop have the right theme without cleaning the cache. Fetching template inclunded was solved but not for hooks. So, ok partially solved, sorry for that disappointment !

I propose a second commit to solve this bug. But please not that module need used default Module->fetch method to display a partial template (for instance via an hook) or define its own compile ID when a developper want to call smarty->fetch method included the theme name discriminate each compiled template.

Can you try again with this new commit ?

Thank

**Comment by sarahdib** [comment]
@202-ecommerce Thank you now it's working :)

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@PrestaShop/prestashop-core-developers another review please as I am not 100% confident in my knowledge of Smarty compilation mechanisms 😄

**Comment by 202-ecommerce** [comment]
@matks thank you. 

@PrestaShop/prestashop-core-developers we are available for you to study the best way to fix this bug.

File: classes/module/Module.php [hunk 1]
```diff
@@ -2451,6 +2451,9 @@ public function fetch($templatePath, $cache_id = null, $compile_id = null)
         if ($cache_id !== null) {
             Tools::enableCache();
         }
+        if ($compile_id == null) {
```
Comment (PierreRambaud) [inline classes/module/Module.php]:
```suggestion
        if ($compile_id === null) {
```

File: classes/module/Module.php [hunk 2]
```diff
@@ -2451,6 +2451,9 @@ public function fetch($templatePath, $cache_id = null, $compile_id = null)
...
+            $compile_id = Context::getContext()->shop->theme->getName();
```
Comment (PierreRambaud) [inline classes/module/Module.php:2455]: I think the `compile_id` can be a mix between lang & shop & theme name because of smarty documentation:
>compile_id is an optional parameter. You can also set the $compile_id variable once instead of passing this to each call to this function. It is used in the event that you want to compile different versions of the same template, such as having separate templates compiled for different languages.

wdyt?

File: classes/controller/FrontController.php [hunk 3]
```diff
@@ -675,12 +675,14 @@ protected function smartyOutputContent($content)
 
         $html = '';
 
+        $theme = $this->context->shop->theme->getName();
+
         if (is_array($content)) {
             foreach ($content as $tpl) {
-                $html .= $this->context->smarty->fetch($tpl, null, $this->getLayout());
+                $html .= $this->context->smarty->fetch($tpl, null, $theme . $this->getLayout());
```
Comment (PierreRambaud) [inline classes/controller/FrontController.php:682]: same here, maybe integrate shop id & lang_id in the compile_id parameter?

File: classes/module/Module.php (hunk 2 above)
Comment (202-ecommerce) [reply classes/module/Module.php:2455]: Ok for the if conditions.
We could concatain compileID

$compile_id .= Context::getContext()->shop->theme->getName();

Wdyt ?

I think it’s not necessary and not recommandes to add « dynamic » parameters. Compile ID is not a cache ID. Compilation is done to avoid parsing templates (transforme tpl into php and not tpl into html as cache) but keeping dynamic variables available, conditions, loops. In some case like here, we have the  exact same relative path between two templates that’s explain the bug. We need to specify to smarty that we have several versions of template to compile.
So your suggestion to add id shop works but is not efficient.

If you supply to smarty dynamic parameters as compile Id like shop id, lang id, ... and (why not product id) you will multiply compile templates exponentially regarding numbers of parameters and templates. On our case a Prestashop with 200 shops (yes it is possible) and 2 themes will generate too many unnecessary compiled files.

If a developper want to use cache with smarty to display static html contents, he need to supply obviously all id parameters as cache_id.

So my fix doesn’t change any thing for those who defined on there module a  compile id because of the if null condition and consider they need a specific.

File: classes/controller/FrontController.php (hunk 3 above)
Comment (202-ecommerce) [reply classes/controller/FrontController.php:682]: It’s a compilation id not a cache id. Please consider my previous response.

File: classes/module/Module.php (hunk 2 above)
Comment (PierreRambaud) [reply classes/module/Module.php:2455]: Seems legit, thanks for explanation :+1:

**Comment by PierreRambaud** [comment]
Just a little lint `===` instead of `==` and it's ok for us :)

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
See my comment 😉

**Comment by 202-ecommerce** [comment]
@PierreRambaud @matks 
Thank you ! In the pipes...

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@202-ecommerce Thanks to you for your pull request and explanations :smiley_cat:

**Comment by matks** [comment]
Thank you @202-ecommerce

**Comment by mikirimiki** [comment]
Hello,
I tried this solution, but for me it doesn't work

**Comment by 202-ecommerce** [comment]
@mikirimiki 

The bug about smarty compilation has three origin at this time. Two are already merged on develop branch and included on next minor release 1.7.7. An other is open and wait for QA validation from Prestashop.

Are you sure you have merge all files on your Prestashop ?
If you’ve already verify, I think it will be better to open an new issue with all détails because this thread is closed.

Regards.

**Comment by mikirimiki** [comment]
@202-ecommerce 
Thanks for your replay.
I only changed the files that you had suggested.
I'm sorry I don't know what you mean with "merge all files".

Maybe can I hire a developer here?
Best regards.
