### PR TITLE
Make legacy parameters from routing accessible in migrated pages

### LINKED ISSUE #20934: Following migration, $_GET identifier parameters are missing on "View {..} Page"
#### Describe the bug

Legacy pages "View {..} Page" (View Customer, View Order, View Category, View Attribute ...) usually have a URL that carry the identifier information with a http GET parameter `id_...`.

Example: `admin-dev/index.php?controller=AdminAttributesGroups&viewattribute_group=&id_attribute_group=1`
➡️ the `id_attribute_group` is the identifier

When we migrate a page to Symfony, most often, the new URL does carry the identifier information inside the URL path

Example: `http://localhost:8080/admin-dev/index.php/sell/catalog/categories/3`
➡️ `3` is the identifier

This means that, if a module was hooked on this page previously, retrieving the data using `Tools::getValue('id_{...}')` it will stop working with new migrated page.

#### Expected behavior

We believe we should attempt to provide a backward compatibility mechanism to preserve modules behavior. We might not be able to preserve all GET parameter from legacy page to Symfony page, but at least the "main identifier" should be kept (order ID for "View an Order" page ; customer ID for "View a Customer" page ...).

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In migrated pages the previous query parameters were not accessible any more due to parameters renaming and sometimes the url includes them directly This PR doesn't not solve every problem but at least it allows to access the parameters defined in the routing via `_legacy_parameters` and `_legacy_link` It won't solve every issue for module developers who still need to update their module to be compatible with migrated pages but at least it will help them a little
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20934
| How to test?  | Use the ps_qualityassurance module and register this hook:<br><br>Hook name: `displayAdminOrderTop`<br>Content: `return '<h3>Order id: ' . Tools::getValue('id_order') . '</h3>';`<br><br>Then go to an Order view page, without the PR you should see at the top of the page `Order id:` but no ID, and with the PR you will see `Order id: 5` (if order id is 5 of course)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21025)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/PrestaShopBundle/Routing/Converter/LegacyParametersConverter.php [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+use Symfony\Component\HttpFoundation\Request;
+
+class LegacyParametersConverter
+{
+    /**
+     * @param Request $request
+     *
+     * @return array|null
+     */
+    public function getParametersByRequest(Request $request): ?array
```
Comment (Progi1984) [inline src/PrestaShopBundle/Routing/Converter/LegacyParametersConverter.php]: To remove

**Review by Progi1984 — COMMENTED** [review]
To rebase ;) and One comment

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @jolelievre !!

**Comment by Progi1984** [comment]
Thanks @jolelievre & @SD1982
