### PR TITLE
Correctly displayed precise product weight

### LINKED ISSUE #24687: Precise product weight is not correctly displayed in back-office
#### Describe the bug

Title says it all.

#### Expected behavior

We should see precise weight correctly.

#### Steps to Reproduce

1. Go to Catalog -> Product
2. Edit product
3. Go to 'Shipping' tab
4. Set 'weight' to `0,01731`
5. As you can see, in BO it shows us only `0,017` but in database value is correct

**Screenshots**

https://www.dropbox.com/s/wljgcmiatg9w2d7/Nagranie%20z%20ekranu%202021-05-28%20o%2010.29.32.mov?dl=0

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Weight is not correctly displayed if has more than 3 decimals
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24687
| How to test?      | See #24687 
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24688)

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php [hunk 1]
```diff
@@ -150,6 +150,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'weight',
                 FormType\NumberType::class,
                 [
+                    'scale' => 6,
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]: the fix LGTM, but I think it would be nice to have this value stored in a constant that could be reused for weight precision, instead of potentially hardcoding it at several places, what do you think ?

Comment (kpodemski) [reply src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]: hmmm, you're right, what about place, where you think would be best to put it? `CommonAbstractType`?

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]: As it's relative to this form, put it in the form.

Comment (matks) [reply src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]: Agreed with peers 😄  a constant inside ProductShipping would be great

Comment (kpodemski) [reply src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]: Sorry guys but I added it to `CommonAbstractType` as this const must be used also in `ProductCombination`, I've decided to follow constant added for price precision

Let me know if that's ok or we should have dedicated constant in both forms separately for some reason

File: src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php [hunk 2]
```diff
@@ -159,6 +159,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 ],
             ])
             ->add('attribute_weight', NumberType::class, [
+                'scale' => self::PRESTASHOP_WEIGHT_DECIMALS,
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php]:
```suggestion
                'scale' => static::PRESTASHOP_WEIGHT_DECIMALS,
```

File: src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php [hunk 3]
```diff
@@ -150,6 +150,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'weight',
                 FormType\NumberType::class,
                 [
+                    'scale' => self::PRESTASHOP_WEIGHT_DECIMALS,
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]:
```suggestion
                    'scale' => static::PRESTASHOP_WEIGHT_DECIMALS,
```

Comment (PierreRambaud) [reply src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php]: just a little comment:
```php
<?php

class A
{
    public const B = 'test';

    public function __construct()
    {
        var_dump(self::B);
        var_dump(static::B);
    }
}

class C extends A
{
    public const B = 'here';
}


new C();
```
It will display:
```
/home/got/test.php:9:
string(4) "test"
/home/got/test.php:10:
string(4) "here"
```

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @kpodemski !

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623
