### PR TITLE
Do not put the user as connected if he's not connected

### LINKED ISSUE #9721: [BOOM-4959] Connect to addons in BO
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4959).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Thu, 1 Mar 2018 09:09:10 +0100

<p>If I try to login to addons in the module page with a bad login/passowrd, I have an error message but when I reload the page, it seems I am connected</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | There is no check to defined if the user is properly connected. We must be sure everything is ok when requesting the addons platform.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9721
| How to test?  | Be sure you're not anymore logged in your BO (best way is to clear your cookie) Try with a wrong user like demo@prestashop.com, after a refresh you shouldn't be connected. Then do the same test with a good username and a bad password.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20774)

### CODE REVIEW

File: src/Core/Addon/Login/Exception/LoginErrorException.php [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace PrestaShop\PrestaShop\Core\Addon\Login\Exception;
+
+use PrestaShop\PrestaShop\Core\Exception\CoreException;
+
+class LoginErrorException extends CoreException
```
Comment (PierreRambaud) [inline src/Core/Addon/Login/Exception/LoginErrorException.php:31]: I'm not sure it's the right place and the right name. @matks if you have a suggestion :)

Comment (matks) [reply src/Core/Addon/Login/Exception/LoginErrorException.php:31]: Looks good to me 👍

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by ngodefroy** [comment]
TEST OK:
https://drive.google.com/file/d/1xANiibDhdVvylapjhwLlAogG_PEBM5sG/view

**Comment by Progi1984** [comment]
Thanks @PierreRambaud
