### PR TITLE
Assign product suppliers to combination during combination csv import

### LINKED ISSUE #29350: BO - Supplier block is not displayed in the edit combination page after importing them with csv file
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27353#pullrequestreview-963560433
Supplier block is not displayed on the edit combination page after importing them with csv file

This is new behavior in the 8.0.x, In the Product V1: the supplier block is well updated after importing the combinations

### Expected behavior

_No response_

### Steps to reproduce

1. Create a standard simple product
2. In the options tab > Choose a supplier and save
3. Go to BO > Advanced Parameters > Import page
4. Import combinations
I used this example
```php
Product ID*;Product_Reference;Attribute (Name:Type:Position)*;Value (Value:Position)*
48;reference1;Color:color:0;Blue:0
48;reference2;Color:color:0;Yellow:1
```
5. Go BO > Products page
6. Edit the last product & edit the combination
7. See error > no supplier displayed

I attached a screen record

https://user-images.githubusercontent.com/16067358/166956408-877417a3-68c1-4f08-b836-0bd1e78894e3.mp4

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | refer to https://github.com/PrestaShop/PrestaShop/issues/29350
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/29350
| Related PRs       | 
| How to test?      | refer to https://github.com/PrestaShop/PrestaShop/issues/29350
| Possible impacts? |

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

File: controllers/admin/AdminImportController.php [hunk 1]
```diff
@@ -3010,6 +3010,21 @@ protected function attributeImportOne($info, $default_language, &$groups, &$attr
                     StockAvailable::setQuantity((int) $product->id, $id_product_attribute, (int) $info['quantity'], $this->context->shop->id);
                 }
             }
+
+            // assign combination id to already associated product suppliers
+            $productSuppliers = ProductSupplier::getSupplierCollection($product->id);
```
Comment (jolelievre) [inline controllers/admin/AdminImportController.php:3015]: Be careful I believe this returns ALL the existing ProductSupplier including the ones associated to already existing combinations. So it seems this code works fine for a product without combinations since the only ProductSupplier returned will the one associated to the Product only.

Then cloning this and associating it to the new combinations is fine. But when you perform this import again then the ProductSupplier entities associated to other combinations will also be cloned and associated to the new combination resulting in this new combination having multiple ProductSupplier instances for the same supplier.

I maybe be missing something but I think you should only loop through the ProductSuppliers associated to product only (with `$productSupplier->id_product_attribute === 0`) meaning you will only loop through the list of suppliers associated to the product.

And also the ProductSupplier should only be cloned and associated if the combination doesn't already have an associated ProductSupplier for this supplier. I don't know if I'm clear 😅 but we can discuss this live.

Comment (zuk3975) [reply controllers/admin/AdminImportController.php:3015]: hmm.
Now Im looping through all of them and so I can check if it is already associated or not.
If it is associated, i skip it, this way only creating new ProductSupplier for the ones that are not associated with combination already.

If i would check only with `id_product_attribute === 0` then I won't be able to check if this combination already have the supplier assigned :thinking:

ofc considering performance, I guess if there are alot of combinations, then this will be costly, maybe its worth introducing a separate custom query or so?

**Review by sLorenzini — APPROVED** [review]
hello @zuk3975,

Thank you for this PR.
Automaticated tests are good.
Tested on 8.0.X PHP 7.3.

Suppliers with product page v2 is still assigned to product combinations with CSV import:
 

https://user-images.githubusercontent.com/2854834/192331972-450f10fa-97cf-41bc-8846-0efc9b07d50c.mp4

suppliers-after-csv-import

QA approved ✅ 

Thanks
