### PR TITLE
Stabilize cache clear

### LINKED ISSUE #36446: Logs polluted with a lot of unnecessary data
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PrestaShop 9 Alpha has started to log a lot of - in my opinion - unnecessary information to logs.

Examples:

> Remember me disabled; request does not contain remember me parameter ("{parameter}").

In dev.log:
> [2024-06-28T10:44:27.236145+02:00] app.DEBUG: Remember me disabled; request does not contain remember me parameter ("stay_logged_in"). {"parameter":"stay_logged_in"} []

> Notified event "{event}" to listener "{listener}". - only in the developer mode.

For this one, I have a correct log inside `dev.log` file and it is:
> [2024-06-25T09:44:02.921289+02:00] app.DEBUG: Notified event "Symfony\Component\Security\Http\Event\CheckPassportEvent" to listener "Symfony\Component\Security\Http\EventListener\UserProviderListener::checkPassport". {"event":"Symfony\\Component\\Security\\Http\\Event\\CheckPassportEvent","listener":"Symfony\\Component\\Security\\Http\\EventListener\\UserProviderListener::checkPassport"} []

There is also a lot of logs related to SymfonyCacheClearer:

> SymfonyCacheClearer: Successfully cleared cache for admin env dev

Problem might be related to how we inject class responsible for logging, since we use autowire I feel like we don't inject what we want in some places.

CC @jolelievre 

### Expected behavior

We should not log so much data using `PrestaShopLogger`, they should remain in Symfony's logs.

### Steps to reproduce

Do something in the back office, install a module, uninstall a module, login, re-login and then go to the Logs.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### LINKED ISSUE #38139: Cache clearing doesn't work properly on 9.0.0, doesn't rebuild some things, like a container
### Describe the bug and add attachments

I have been diagnosing some weird issue I found in https://github.com/PrestaShop/PrestaShop/issues/38124.

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: 
You have requested a non-existent service "product_comment_repository".
in /var/www/vhosts/trendo.cz/upgradetest.trendo.cz/vendor/symfony/dependency-injection/Container.php:263 

```
and I found out that the issue disappeared after manually deleting `/var/cache`, even though I clicked **Clear cache** button in backoffice many many times.

So, the true cause is that clearing the cache does not work properly. After clearing the cache, many files stay the same and are not updated, including compiled services.

Image

Ping @jolelievre @tleon

### Steps to reproduce

1. Make sure you are in debug mode.
2. Open `/var/cache/dev`.
3. In backoffice, click clear cache, wait for it to finish.
4. See that some files were not updated, their update time did not change.

### PrestaShop version(s) where the bug happened

9.0.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Stabilize cache clear
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green and UI tests green Also ask some people that have problems to clear cache on their environments to test the PR
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/17302434892
| Fixed issue or discussion?     | Fixes #38139 Fixes #36446
| Related PRs       | https://github.com/PrestaShop/ui-testing-library/pull/669
| Sponsor company   | ~

### Note

The `TranslationCacheClearer` class and service have been removed in favor of the more generic `LegacyCacheClearer`. Strictly speaking it is a breaking change but this service was not considered in the backward compatibility promise and only meant for internal usage, so it's acceptable to remove it in a patch PR.

### CODE REVIEW

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Advparameters.Feature`
    - [ ] `Severity (0-4)`
- `Admin.Advparameters.Help`
    - [ ] `Indicate the minimum log levels that will be saved in database.`
    - [ ] `Debug`

(Note: this is an automated message, but answering it will reach a real human)

File: src/PrestaShopBundle/Cache/LegacyCacheClearer.php [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+use Symfony\Component\Filesystem\Filesystem;
+use Symfony\Component\Finder\Finder;
+use Symfony\Component\HttpKernel\CacheClearer\CacheClearerInterface;
+
+/**
+ * Since PrestaShop 9.0 we have multiple kernels with each their cache folders, the cache are split in this way:
+ *  - var/cache/dev/admin
+ *  - var/cache/dev/admin-api
+ *  - var/cache/dev/front
+ *  - var/cache/front/admin
```
Comment (Hlavtox) [inline src/PrestaShopBundle/Cache/LegacyCacheClearer.php]: There should be `prod` I think

Comment (jolelievre) [reply src/PrestaShopBundle/Cache/LegacyCacheClearer.php]: I can add it, but it's just a comment to explain the structure anyway, there is also the test environement But the comment doesn't need to be exhaustive as long as the behaviour is

Comment (jolelievre) [reply src/PrestaShopBundle/Cache/LegacyCacheClearer.php]: Ah but you're right, I miswrote it, it should be prod instead of front my bad

Comment (Hlavtox) [reply src/PrestaShopBundle/Cache/LegacyCacheClearer.php]: Yeah it's just a comment. :-)

File: tests/UI/package.json [hunk 2]
```diff
@@ -111,7 +111,7 @@
   "homepage": "https://github.com/PrestaShop/PrestaShop/tree/develop/tests/UI#readme",
   "dependencies": {
     "@faker-js/faker": "^9.0.3",
-    "@prestashop-core/ui-testing": "https://github.com/PrestaShop/ui-testing-library#main",
+    "@prestashop-core/ui-testing": "https://github.com/jolelievre/ui-testing-library#logs-database-form",
```
Comment (Quetzacoalt91) [inline tests/UI/package.json]: Denied

File: install-dev/data/xml/configuration.xml [hunk 3]
```diff
@@ -918,5 +918,8 @@ Country</value>
     <configuration id="PS_FEATURE_VALUES_ORDER" name="PS_FEATURE_VALUES_ORDER">
       <value>name</value>
     </configuration>
+    <configuration id="PS_MIN_LOGGER_LEVEL_IN_DB" name="PS_MIN_LOGGER_LEVEL_IN_DB">
+      <value>1</value>
+    </configuration>
```
Comment (M0rgan01) [inline install-dev/data/xml/configuration.xml:923]: There are two different topics on PR I think? cache clear and log? Maybe it's worth separating this into another PR, do you think?

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php [hunk 4]
```diff
@@ -129,6 +133,38 @@ public function saveSettingsAction(
...
+            if (0 === count($saveErrors)) {
+                $this->addFlash('success', $this->trans('Successful update', [], 'Admin.Notifications.Success'));
+
+                return $this->redirectToRoute('admin_logs_index');
+            }
+
+            $this->addFlashErrors($saveErrors);
+        }
+
+        return $this->redirectToRoute('admin_logs_index');
```
Comment (M0rgan01) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php:165]:
```suggestion
       if ($databaseForm->isSubmitted()) {
            $data = $databaseForm->getData();
            $saveErrors = $formHandler->save($data);
            if (0 !== count($saveErrors)) {
                $this->addFlashErrors($saveErrors);
            }
            $this->addFlash('success', $this->trans('Successful update', [], 'Admin.Notifications.Success'));
        }
        return $this->redirectToRoute('admin_logs_index');
```

File: tests/UI/package.json (hunk 2 above)
Comment (jolelievre) [reply tests/UI/package.json]: yep it was temporary, the pR on ui testing has been approved and merged by @Progi1984 so it should be good now

File: install-dev/data/xml/configuration.xml (hunk 3 above)
Comment (jolelievre) [reply install-dev/data/xml/configuration.xml:923]: Ideally, yeah, but I spent 15 hours on this so I don't have the motivation anymore 😅

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php (hunk 4 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php:165]: I copy-pasted the other action without thinking, so it's exactly the same as the previous action in the same controller

I was mainly forced to add this form just to please the UI testing which are a nightmare, IMHO, on this feature The pagination of the grid is based on multiple login in the BO actions, because they generate debug logs in DB, so that then we can check if page 2 works fine...

Since debug logs are not persisted by default I had to add this form just so that we can change the minimum level with playwright so that this crazy pagination testing can work again...

Long story short: I'm tired of this PR, I don't care how pretty the code is on this form as long as the UI tests are green 😅

Comment (M0rgan01) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController.php:165]: I understand, strength and courage dear college

**Comment by ChillCode** [comment]
prod env:

```

Before BO clear cache:

-rw-r--r--  1 www-data www-data  626 Aug 28 07:35 9.0.0en.xml
-rw-r--r--  1 www-data www-data  90K Aug 28 07:35 FrontContainer.php
-rw-r--r--  1 www-data www-data  33K Aug 28 07:35 FrontContainer.php.meta
drwxr-xr-x 13 www-data www-data 4.0K Aug 28 07:35 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:35 appParameters.php
-rw-r--r--  1 www-data www-data 223K Aug 28 07:35 cacert.pem
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:35 circuit_breaker
-rw-r--r--  1 www-data www-data  68K Aug 28 07:35 class_index.php
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:35 distribution-api
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:35 localization
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:35 ps_mainmenu
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:35 smarty
drwxr-xr-x  2 www-data www-data 4.0K Aug 28 07:35 translations
drwxr-xr-x  2 www-data www-data 4.0K Aug 28 07:35 yaml

After BO clear cache:

drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:36 ..
drwxr-xr-x 14 www-data www-data 4.0K Aug 28 07:36 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:36 appParameters.php
-rw-r--r--  1 www-data www-data  68K Aug 28 07:36 class_index.php
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:36 localization
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:36 smarty

After Install Module:

drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:37 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:37 ..
drwxr-xr-x 12 www-data www-data 4.0K Aug 28 07:37 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:37 appParameters.php
-rw-r--r--  1 www-data www-data 223K Aug 28 07:37 cacert.pem
-rw-r--r--  1 www-data www-data  68K Aug 28 07:37 class_index.php

After Uninstall Module:

drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:38 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:38 ..
drwxr-xr-x 12 www-data www-data 4.0K Aug 28 07:38 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:38 appParameters.php
-rw-r--r--  1 www-data www-data 223K Aug 28 07:38 cacert.pem
-rw-r--r--  1 www-data www-data  68K Aug 28 07:38 class_index.php

```

dev env:

```

Before BO clear cache:

drwxr-xr-x  7 www-data www-data 4.0K Aug 28 07:39 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:39 ..
-rw-r--r--  1 www-data www-data  91K Aug 28 07:39 FrontContainer.php
-rw-r--r--  1 www-data www-data  33K Aug 28 07:39 FrontContainer.php.meta
drwxr-xr-x 14 www-data www-data 4.0K Aug 28 07:39 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:39 appParameters.php
-rw-r--r--  1 www-data www-data  68K Aug 28 07:39 class_index.php
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:39 localization
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:39 ps_mainmenu
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:39 smarty
drwxr-xr-x  2 www-data www-data 4.0K Aug 28 07:39 translations

After BO clear cache:

drwxr-xr-x  5 www-data www-data 4.0K Aug 28 07:39 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:39 ..
drwxr-xr-x 14 www-data www-data 4.0K Aug 28 07:39 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:39 appParameters.php
-rw-r--r--  1 www-data www-data  68K Aug 28 07:39 class_index.php
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:39 localization
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:39 smart

After Installing a Module: (no warmup)

drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:41 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:41 ..
drwxr-xr-x 12 www-data www-data 4.0K Aug 28 07:41 admin

```

Then tested using ApplicationKernelCacheClearer and when it tries to clean the pools fails and ExecKernelCacheClearer or FilesystemKernelCacheClearer takes over and clears it, tried both changing priorities.

```

ApplicationKernelCacheClearer: Successfully cleared cache for admin env prod debug off	
ApplicationKernelCacheClearer: Successfully cleared cache for admin env prod debug on 	

SymfonyCacheClearer: Error while clearing cache for admin env prod using PrestaShop\PrestaShop\Adapter\Cache\Clearer\Symfony\ApplicationKernelCacheClearer: Failed opening required '/var/www/prestashop.clean/public_html/var/cache/prod/admin/ContainerBwDuVZm/getConsole_ErrorListenerService.php' (include_path='.:/usr/share/php') 

FilesystemKernelCacheClearer: Cache folder /var/www/prestashop.clean/public_html/var/cache/prod/admin successfully cleared manually
FilesystemKernelCacheClearer: Trying manual removal on trial 1/5 of cache folder /var/www/prestashop.clean/public_html/var/cache/prod/admin 

```

It fails clearing the pools because the APP is already destroyed, a solution is to use cache:pool:clear only when cache:clear fails.

Then tested using FilesystemKernelCacheClearer

```

FilesystemKernelCacheClearer: Trying manual removal on trial 1/5 of cache folder /var/www/prestashop.clean/public_html/var/cache/dev/admin 
FilesystemKernelCacheClearer: Cache folder /var/www/prestashop.clean/public_html/var/cache/dev/admin successfully cleared manually 

Before BO clear cache:

drwxr-xr-x  7 www-data www-data 4.0K Aug 28 07:43 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:42 ..
-rw-r--r--  1 www-data www-data  90K Aug 28 07:42 FrontContainer.php
-rw-r--r--  1 www-data www-data  33K Aug 28 07:42 FrontContainer.php.meta
drwxr-xr-x 13 www-data www-data 4.0K Aug 28 07:42 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:42 appParameters.php
-rw-r--r--  1 www-data www-data 223K Aug 28 07:42 cacert.pem
-rw-r--r--  1 www-data www-data  68K Aug 28 07:42 class_index.php
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:42 localization
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:43 ps_mainmenu
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:43 smarty
drwxr-xr-x  2 www-data www-data 4.0K Aug 28 07:43 translations

After BO clear cache:

drwxr-xr-x  5 www-data www-data 4.0K Aug 28 07:44 .
drwxr-xr-x  4 www-data www-data 4.0K Aug 28 07:43 ..
-rw-r--r--  1 www-data www-data  90K Aug 28 07:44 FrontContainer.php
-rw-r--r--  1 www-data www-data  33K Aug 28 07:44 FrontContainer.php.meta
drwxr-xr-x 13 www-data www-data 4.0K Aug 28 07:44 admin
-rw-r--r--  1 www-data www-data 3.2K Aug 28 07:44 appParameters.php
-rw-r--r--  1 www-data www-data 223K Aug 28 07:44 cacert.pem
-rw-r--r--  1 www-data www-data  68K Aug 28 07:44 class_index.php
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:44 localization
drwxr-xr-x  3 www-data www-data 4.0K Aug 28 07:44 smarty

```

There might be other scenarios, but in these it works.

Clearing cache pools with same params as clear cache is like doing it twice, that's why while using inotify while clearing dev I saw them deleting twice when running ExecKernelCacheClearer, since we run from console we on't get errors since we are not in the current APP:

Command used to track changes in cache folder while clearing.

inotifywait -m -r -e create -e modify -e delete --format '%T %w%f %e' --timefmt '%F %T' var/cache

Absolute overkill with all the clearers and three different methods.

Thanks

**Comment by Codencode** [comment]
Hi @jolelievre,

I did some tests by simulating this issue: https://github.com/PrestaShop/PrestaShop/issues/38124, and it works. So, the front-office cache is cleared properly, both during module installation and when manually clearing it via the button in Admin > Performance.

However, I noticed that during module installation, the admin-side cache might not be cleared. Specifically, I created a module that defines two services: one for the front office and one for the back office. When installing the module, the front-office service is found, but the admin one isn't. However, after clearing the cache manually, everything works fine.
If you want to investigate further, I can share the module I created specifically for this.

Anyway, overall, the change looks fantastic! Great job!


[pr_39442.zip](https://github.com/user-attachments/files/22021046/pr_39442.zip)

**Comment by ChillCode** [comment]
Hi @Codencode 

When installing your module and doing nothing else I get this after CLI `sudo -u www-data bin/console debug:container pr_`:

```

Information for Service "pr_39442.service.admin"
================================================

 ---------------- ------------------------ 
  Option           Value                   
 ---------------- ------------------------ 
  Service ID       pr_39442.service.admin  
  Class            PR39442\Service         
  Tags             -                       
  Public           yes                     
  Synthetic        no                      
  Lazy             no                      
  Shared           yes                     
  Abstract         no                      
  Autowired        no                      
  Autoconfigured   no                      
  Usages           none                    
 ---------------- ------------------------

```

It looks correct, no? can make sure you applied the correct PR.

https://github.com/PrestaShop/PrestaShop/archive/refs/pull/39442/head.zip

[EDIT] And check performance logs, when fails or success there should be an entry now.

**Comment by Codencode** [comment]
Hi @ChillCode,
I'm also getting the same result in the console, so everything seems fine. However, if you try to access the module configuration, you'll see this error:
Screenshot 2025-08-28 at 11-46-57 You have requested a non-existent service pr_39442 service admin   (500 Internal Server Error)

After clearing the cache, the error no longer appears.

But yes, I downloaded the correct PR.

Senza nome-1

**Comment by ChillCode** [comment]
I'm not getting the error, tried in dev and prod, just getting a blank page when I click on Configure button just after installation finishes, as per capture, and since there is no config, is the correct behaviour, don't want to populate the PR and maybe we have different setups, that is the point of testing, so my tests gave me the expected results with all three methods, and even when I made two to fail on purpose the File clearer finished the job at the first try.

image

Try a command like this to test if kernel file is recreated:

inotifywait -m -r -e create -e modify -e delete --format '%T %w%f %e' --timefmt '%F %T' var/cache

[EDIT] As I see you are on an IDE yo can open the kernel file directly from cache folder and check in realtime if it changes during the clearing and adds your service:

`            'pr_39442.service.admin' => 'getPr39442_Service_AdminService',
`

**Comment by Codencode** [comment]
The service is there, but it keeps throwing an error. However, if I clear the cache, it works.

Anyway, considering I'm testing on a Windows environment, which isn't ideal for these kinds of things, let's rely on your tests since you performed them on a Linux environment. So, it's fine by me!

Thanks, @ChillCode! 🙏 

[EDIT]
I pulled the latest commit. I didn't realize there had been a force push, and the issue is gone! So it's working on my end too!

**Review by Codencode — APPROVED** [review]

**Comment by jolelievre** [comment]
@ChillCode yeah I removed the part that clears the pool cache, at some point I had to do this for everything to work correctly, especially for the cache of Admin API scopes and generate Open API doc But I think it was because with the Application method I have to clear multiple times the environment with and without debug, and that fixed everything so I don't need this extra pool clearing any more

**Review by Hlavtox — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @jolelievre,

I tested your PR and it's good for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]
