### PR TITLE
Deprecate cleanNonUnicodeSupport function

### LINKED ISSUE #27362: Remove/Deprecate cleanNonUnicodeSupport function
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The function `Tools::cleanNonUnicodeSupport()`  does nothing because it uses a undefined constant: `PREG_BAD_UTF8_OFFSET`

```php
class CharacterCleaner
{
    /**
     * Delete unicode class from regular expression patterns.
     *
     * @param string $pattern
     *
     * @return string pattern
     */
    public function cleanNonUnicodeSupport($pattern)
    {
        if (!defined('PREG_BAD_UTF8_OFFSET')) {  // <-- ALWAYS TRUE
            return $pattern;
        }

        return preg_replace('/\\\[px]\{[a-z]{1,2}\}|(\/[a-z]*)u([a-z]*)$/i', '$1$2', $pattern);
    }
}
```
Looking at the PHP source code I see that the constant `PREG_BAD_UTF8_OFFSET` does not exist, the most similar is [PREG_BAD_UTF8_OFFSET_ERROR ](https://github.com/php/php-src/blame/2b1f8abd8778d14abeae6a83bc1205989f8bdece/ext/pcre/php_pcre.c#L453) which is always defined (in my case === 5). This hasn't changed in PHP for over 8 years.

Maybe @Progi1984 knows something about it, since he modified it not so long ago in https://github.com/PrestaShop/PrestaShop/pull/14838

Should we remove this wrapper from all validations and deprecate the function?

Additional info:
- I have only found one project that used it and stopped using it:
   - https://github.com/symphonycms/symphonycms/issues/692
   - https://github.com/symphonycms/symphonycms/pull/697/files#diff-bfe72a5ce47c188387989ec3c3e3896fe90fd64f59927fb9a1acf8a4d8867662L611
 - [stackoverflow thread](https://stackoverflow.com/questions/4509576/detect-if-pcre-was-built-without-the-enable-unicode-properties-or-enable-utf) (the only place on the internet where it is mentioned, a comment from someone)

### Expected behavior

Not to have this wrapper

### Steps to reproduce

Not available

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

All

### If your bug is related to a module, specify its name and its version

Core

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Deprecate cleanNonUnicodeSupport() because it does nothing, it always returns $pattern argument without being modified. It uses a undefined constant: PREG_BAD_UTF8_OFFSET so the behavior is always the same.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| Fixed ticket?     | Fixes #27362
| How to test?      | CI green
| Possible impacts? | NO

BC Breaks :
- `CustomerNameValidator` constructor no longer has params.
  - 1º param `CharacterCleaner $characterCleaner` and `private $characterCleaner;` property removed.
- `CustomerNameValidatorFactory` constructor no longer has params.
  - 1º param `CharacterCleaner $characterCleaner` and `private $characterCleaner;` property removed.
- `TypedRegexValidator` constructor no longer has params.
  - 1º param `CharacterCleaner $characterCleaner` and `private $characterCleaner;` property removed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27657)

### CODE REVIEW

File: src/Core/String/CharacterCleaner.php [hunk 1]
```diff
@@ -31,16 +31,16 @@ class CharacterCleaner
...
      * @param string $pattern
      *
      * @return string pattern
      */
     public function cleanNonUnicodeSupport($pattern)
     {
-        if (!defined('PREG_BAD_UTF8_OFFSET')) {
-            return $pattern;
-        }
+        \Tools::displayAsDeprecated('The use of cleanNonUnicodeSupport is not required');
```
Comment (PierreRambaud) [inline src/Core/String/CharacterCleaner.php]: Please do not use this call, follow the coding standard instead:
https://devdocs.prestashop.com/1.7/development/coding-standards/#deprecations

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
One little comment about coding standard

**Comment by davidglezz** [comment]
Done! Thank you @PierreRambaud for your review.

**Review by PierreRambaud — DISMISSED** [review]

File: src/Core/ConstraintValidator/CustomerNameValidator.php [hunk 2]
```diff
@@ -99,8 +83,7 @@ private function isPointSpacedValid($name)
         if (mb_strpos($name, '.') === false && mb_strpos($name, '。') === false) {
             return true;
         }
-        $pattern = $this->characterCleaner->cleanNonUnicodeSupport(self::PATTERN_DOT_SPACED);
 
-        return (bool) preg_match($pattern, $name);
+        return (bool) preg_match(self::PATTERN_DOT_SPACED, $name);
```
Comment (Progi1984) [inline src/Core/ConstraintValidator/CustomerNameValidator.php]:
```suggestion
        return (bool) preg_match(static::PATTERN_DOT_SPACED, $name);
```

File: src/Core/ConstraintValidator/CustomerNameValidator.php [hunk 3]
```diff
@@ -82,9 +68,7 @@ public function validate($value, Constraint $constraint)
      */
     private function isNameValid($name)
     {
-        $pattern = $this->characterCleaner->cleanNonUnicodeSupport(self::PATTERN_NAME);
-
-        return (bool) preg_match($pattern, $name);
+        return (bool) preg_match(self::PATTERN_NAME, $name);
```
Comment (Progi1984) [inline src/Core/ConstraintValidator/CustomerNameValidator.php]:
```suggestion
        return (bool) preg_match(static::PATTERN_NAME, $name);
```

File: src/Core/ConstraintValidator/TypedRegexValidator.php [hunk 4]
```diff
@@ -51,19 +50,6 @@ class TypedRegexValidator extends ConstraintValidator
...
 
-    /**
-     * @var CharacterCleaner
-     */
-    private $characterCleaner;
-
-    /**
-     * @param CharacterCleaner $characterCleaner
-     */
-    public function __construct(CharacterCleaner $characterCleaner)
```
Comment (Progi1984) [inline src/Core/ConstraintValidator/TypedRegexValidator.php:62]: Could you document this BC Break ?

File: src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php [hunk 5]
```diff
@@ -27,35 +27,19 @@
...
-     * @var CharacterCleaner
-     */
-    private $characterCleaner;
-
-    /**
-     * CustomerNameValidatorFactory constructor.
-     *
-     * @param CharacterCleaner $characterCleaner
-     */
-    public function __construct(CharacterCleaner $characterCleaner)
```
Comment (Progi1984) [inline src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php:47]: Could you document this BC Break ?

File: src/Core/ConstraintValidator/CustomerNameValidator.php [hunk 6]
```diff
@@ -40,19 +39,6 @@ class CustomerNameValidator extends ConstraintValidator
...
 
-    /**
-     * @var CharacterCleaner
-     */
-    private $characterCleaner;
-
-    /**
-     * @param CharacterCleaner $characterCleaner
-     */
-    public function __construct(CharacterCleaner $characterCleaner)
```
Comment (Progi1984) [inline src/Core/ConstraintValidator/CustomerNameValidator.php:51]: Could you document this BC Break ?

File: classes/Tools.php [hunk 7]
```diff
@@ -3871,17 +3869,15 @@ public static function arrayUnique($array)
...
-        $context = Context::getContext();
-        $containerFinder = new ContainerFinder($context);
-        try {
-            $container = $containerFinder->getContainer();
-            $characterCleaner = $container->get('prestashop.core.string.character_cleaner');
-        } catch (ContainerNotFoundException $e) {
-            // Used when the container is not generated
-            $characterCleaner = new CharacterCleaner();
-        }
+        @trigger_error(
```
Comment (Progi1984) [inline classes/Tools.php:3872]: Could you document this deprecation ?

**Review by Progi1984 — COMMENTED** [review]
Needs some documentations but it's a really good job

File: classes/Tools.php (hunk 7 above)
Comment (davidglezz) [reply classes/Tools.php:3872]: Is this ok?
```
     * @deprecated Since 8.0.0 and will be removed in the next major.
     * This function always returns $pattern argument without being modified.
     * See more: https://github.com/PrestaShop/PrestaShop/issues/27362
```

File: src/Core/ConstraintValidator/TypedRegexValidator.php (hunk 4 above)
Comment (davidglezz) [reply src/Core/ConstraintValidator/TypedRegexValidator.php:62]: How can I do this? Any suggestion?
I didn't realize that this change makes `BC break`, should I change to `Yes` it in the description table right?

Comment (Progi1984) [reply src/Core/ConstraintValidator/TypedRegexValidator.php:62]: Affirmative for the description table.

For the documentation, check for example the PR of @PrestaEdit : #27531

File: classes/Tools.php (hunk 7 above)
Comment (Progi1984) [reply classes/Tools.php:3872]: Only the first line will be ok.

And document it in the description table.

**Review by Progi1984 — COMMENTED** [review]
Added some docs about deprecations & BC Breaks

File: src/Core/ConstraintValidator/TypedRegexValidator.php (hunk 4 above)
Comment (davidglezz) [reply src/Core/ConstraintValidator/TypedRegexValidator.php:62]: @Progi1984 That PR is a new feature that does not create BC breaks.
Is that PR correct?, I don't see documentation about BC breaks.

**Comment by davidglezz** [comment]
@Progi1984 your comment `Added some docs about deprecations & BC Breaks` suggests to me that you have added a commit, but I don't see it.

File: classes/Tools.php (hunk 7 above)
Comment (davidglezz) [reply classes/Tools.php:3872]: done

File: src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php (hunk 5 above)
Comment (davidglezz) [reply src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php:47]: how can I document it? where?

Comment (Progi1984) [reply src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php:47]: You can document it below the table in your PR. (Check this PR for example #27802)

**Review by Progi1984 — COMMENTED** [review]
Need BC Breaks documentation (Check it #27802).

File: src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php (hunk 5 above)
Comment (davidglezz) [reply src/Core/ConstraintValidator/Factory/CustomerNameValidatorFactory.php:47]: Done

File: src/Core/ConstraintValidator/CustomerNameValidator.php (hunk 6 above)
Comment (davidglezz) [reply src/Core/ConstraintValidator/CustomerNameValidator.php:51]: done

File: src/Core/ConstraintValidator/TypedRegexValidator.php (hunk 4 above)
Comment (davidglezz) [reply src/Core/ConstraintValidator/TypedRegexValidator.php:62]: Done

**Comment by davidglezz** [comment]
- Added BC Breaks docs in description
- [Remove class arguments in constraint_validator.yml](https://github.com/PrestaShop/PrestaShop/pull/27657/commits/e2884023ca00550fa00b432686b2313bd0f654bc)
- Rebased

**Review by kpodemski — APPROVED** [review]

**Comment by davidglezz** [comment]
@kpodemski what do you mean by documentation? more than the one already in the description? can you give me some directions?

**Comment by kpodemski** [comment]
@davidglezz 

We're adding this label to PRs which have something to document inside the devdocs. You did everything correctly there, but we have to make sure these BC Breaks will go to the official documentation too 👍🏻

**Review by Progi1984 — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @davidglezz
