### PR TITLE
Fixed the quantity calculation of packs when containing product variations

### LINKED ISSUE #9671: [BOOM-5312] Pack stock incorrect after order when choosing to decrement both
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5312).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Fri, 13 Apr 2018 15:17:25 +0200

<p>Cas 1: </p>

<p>A a product with a stock of 60<br/>
 B a pack of 10 products A, 6 packs in stock<br/>
 I choose to decrement both (product & pack)</p>

<p>I add 10 products A & 3 packs B in cart, I complete the order.<br/>
 I should have 20 products & 3 packs in stock after the order.<br/>
 But I have 20 products & 2 packs</p>

<p>Cas 2:</p>

<p>A a product with a stock of 60<br/>
 B a pack of 10 products A, 6 packs in stock<br/>
 I choose to decrement both (product & pack)</p>

<p>I add 3 packs B & 17 products A in cart, I complete the order.<br/>
 I should have 13 products & 3 packs in stock after the order.<br/>
 But I have 13 products & 1 pack.</p>
        
* How to reproduce the issue ?

N/A

### LINKED ISSUE #13769: It should not be possible to purchase a pack which requires more quantity of pack item than there is in stock
**Describe the bug**
It should not be possible to purchase a pack which requires more quantity of pack item than there is in stock.

**To Reproduce**

In Admin I have pack product.
In that Pack product I have added a combination product with quantity 100.
The combination product itself has less than 100 quantity availability (for example, 99).
Global setting for packs is to "Decrease both".
My Global Availability preference is "Deny orders" when out of stock.

_Result_:
It is possible to add to cart and purchase the pack.
This results in my combination product having a negative quantity after the purchase. Check screenshot.

_Expected_:
It should not be possible to purchase the pack with this scenario.

**Screenshot:**
Screenshot 2019-05-13 at 15 14 50

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.17

---
> Originally posted by  @theodiablo in #23706

#### Describe the bug

I have a pack of products, which is the same products but with his different variations.
When one of those product variation is out of stock, the pack is still enabled.

#### Expected behavior

The pack should be disabled and display the "Email me when product is back on stock" form I have

#### Steps to Reproduce

Using the basic Prestashop installation

1. Create a product pack containing several variations of the product "Hummingbird printed t-shirt" s-white, s-black, m-white, m-black for instance
2. In Quantities tab, set "Decrement products in the pack only" option
3. Go to your newly created product, it should be displayed correctly and you can add it to the cart (remove the product if added)
4. Set the stock product "Hummingbird printed t-shirt" "S Black" variation to 0
5. Go to the product page, see that it is displayed as if it had items, however it should be disabled
6. Add the product to your cart, an error comes out.

The pack quantity should be 0, but it is 3000.

#### Screenshots

Variations quantities
image

Pack content
image

Pack quantities config (auto calculated wrong)
image

Button enabled, even when one variation has 0 stock
image

Error message after clicking on the "add to cart button"
image

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by theodiablo**
Use the variation product attribute id in the pack quantity calculation.

The issue was that in the pack quantity calculation, it was getting the item quantity in the pack without using the product attribute id, which was getting always the quantities of all variations.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes the quantity calculation of packs when 
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #13769 #9671
| How to test?      | Follow steps in issue description of #13769
| Possible impacts? | It should fix many incoherences with the packs calculations, but I can't tell if some processes were depending on this wrong value previously calculated

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23742)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
seems good to me

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/Pack.php [hunk 1]
```diff
@@ -292,7 +292,7 @@ public static function getQuantity(
             $items = array_values(Pack::getItems($idProduct, Configuration::get('PS_LANG_DEFAULT')));
 
             foreach ($items as $index => $item) {
-                $itemQuantity = Product::getQuantity($item->id, null, null, $cart, $idCustomization);
+                $itemQuantity = Product::getQuantity($item->id, $item->id_pack_product_attribute, null, $cart, $idCustomization);
```
Comment (Progi1984) [inline classes/Pack.php]:
```suggestion
                $itemQuantity = Product::getQuantity($item->id, $item->id_pack_product_attribute ?: null, null, $cart, $idCustomization);
```

**Review by Progi1984 — COMMENTED** [review]
Small feedback for avoiding the case where there is no variation (id_pack_product_attribute = 0)

**Comment by theodiablo** [comment]
I applied the suggestion made by @Progi1984 👍

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
I restarted the failing sanity test

**Review by PierreRambaud — APPROVED** [review]

**Review by theodiablo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23742)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Progi1984)

___
*[classes/Pack.php, line 295 at r1](https://reviewable.io/reviews/prestashop/prestashop/23742#-MWVB5yHF7eB-EYG5ffe-r1-295:-MX2Ut6R9HXIi6fU3yI2:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/e44cb66c6707cb86d647debe006a0a36d66127ce/classes/Pack.php#L295)):*
<details><summary><i>Previously, Progi1984 (Progi1984) wrote…</i></summary><blockquote>

```suggestion
                $itemQuantity = Product::getQuantity($item->id, $item->id_pack_product_attribute ?: null, null, $cart, $idCustomization);
```
</blockquote></details>

Done.

**Comment by aDamelincourt** [comment]
Hello @PrestaShop/product-team 
I need an explanation of how the application behaves in the case of cart rules.
If the pack is part of a cart rule, and there is no more pack, what happens ?

**Comment by theodiablo** [comment]
@aDamelincourt, This PR isn't changing anything related to cart rules, I am not sure this is the right place to ask this question.

**Comment by MatShir** [comment]
@aDamelincourt I don't see the relation with the cart rules also. It is only affect the stocks reserved and the available stocks. The first [issue](https://github.com/PrestaShop/PrestaShop/issues/13769) is about the right stock amount when ordering a pack and product from the pack in the same cart. And #9671 is about to block the pack to be added in a cart if one of product combinations is out of stock.
I'm putting the PR on "Waiting for QA" until further notice :)

**Comment by aDamelincourt** [comment]
Thanks @theodiablo 
✔️  QA approved 
The bug is fixed

**Comment by matks** [comment]
Thank you @aDamelincourt for QA and @theodiablo for the contribution!
