### PR TITLE
Make sure the force ssl is used in Cookie class when we are in admin context

### LINKED ISSUE #12783: BackOffice Cookie does not have the secure flag set when SSL is enforced
**Description**
PROD PrestaShop instances are usually configured to enable SSL on all pages. In that case all Cookie objects should be constructed with "secure" flag in order browsers never send such a cookie over HTTP. Hereby the overall security would be further augmented (regardless of other security controls like the actual Cookie encryption) with very little DEV effort. In addition, security web app scanners will stop reporting "Cookie Vulnerability" and scare some merchants. So, the fix is worth of some small effort.

In https://github.com/PrestaShop/PrestaShop/blob/develop/config/config.inc.php it seems that BackOffice cookie (unlike Front Office one) is constructed always without the secure flag.

//  $force_ssl should be initialized a little bit earlier and applied in the 1st (Admin) Cookie constructor below (the code snippet is taken from mentioned Config.inc.php).
```
if (defined('_PS_ADMIN_DIR_')) {
    $cookie = new Cookie('psAdmin', '', $cookie_lifetime); // BUG
} else {
    $force_ssl = Configuration::get('PS_SSL_ENABLED') && Configuration::get('PS_SSL_ENABLED_EVERYWHERE');
    if ($context->shop->getGroup()->share_order) {
        $cookie = new Cookie('ps-sg'.$context->shop->getGroup()->id, '', $cookie_lifetime, $context->shop->getUrlsSharedCart(), false, $force_ssl);
    } else {
        $domains = null;
        if ($context->shop->domain != $context->shop->domain_ssl) {
            $domains = array($context->shop->domain_ssl, $context->shop->domain);
        }
        $cookie = new Cookie('ps-s'.$context->shop->id, '', $cookie_lifetime, $domains, false, $force_ssl);
    }
}
```
**To Reproduce**
Pre-conditions:
Have a PrestaShop instance that has "Enable SSL" and "Enable SSL on all pages" set to TRUE in the "Shop Parameters -> General" configuration screen

Steps to reproduce:
1. Go to any Admin page / Back Office.
2. Check the PrestaShop-* cookie attributes e.g. in Chrome: Open Dev Tools & Go to Application Tab & Click Storage / Cookies in the left men

Results: PrestaShop-* cookie does not have Secure flag set => Browser would send the Cookie over HTTP too

Expected Behavior: All PrestaShop-* cookies will have Secure flag set

**Additionnal information**
PrestaShop version: Any
PHP version: Any

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Make sure the `Cookie` class receives the `$force_ssl` parameter when running in the admin directory.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12783 
| How to test?  | Install PrestaShop with SSL forced, use SameSite=None in cookie configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21249)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

After Fresh install with forcing SSL => ok
PrestaShop-Installation-Assistant
But I found an issue following these steps:

1. In the BO > Advanced Parameters > Administration >  SameSite=None
2. Go to BO > Shop Parameters > General > Disable SSL and Save
3. Go to BO > Shop Parameters > Traffic & SEO page > Change the Shop domain & SSL domain and Save
4. Go to Dashboard > Redirection to the login page
5. Try to connect => impossible
6. I tried to delete cookies, I use an incognito browser

I attached a screen record

https://drive.google.com/file/d/1issGImseVEIHzkPiHQvym_KdxEKxOasy/view?usp=sharing

1. I tested on the same server 1770rc1build1
2. In the BO > Adavnced Parameters > Administration >  SameSite=None
3. Go to BO > Shop Parameters > General > Disable SSL and Save
4. Go to BO > Shop Parameters > Traffic & SEO page > Change the Shop domain & SSL domain and Save
5. Go to Dashboard > No Redirection to the login page 

https://drive.google.com/file/d/1Q9XXrxJehMiPtQsqSLKJFiHpnSCZJjHj/view?usp=sharing

Thanks!

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud,
> 
> After Fresh install with forcing SSL => ok
> PrestaShop-Installation-Assistant
> But I found an issue following these steps:
> 
> 1. In the BO > Advanced Parameters > Administration >  SameSite=None
> 2. Go to BO > Shop Parameters > General > Disable SSL and Save
> 3. Go to BO > Shop Parameters > Traffic & SEO page > Change the Shop domain & SSL domain and Save
> 4. Go to Dashboard > Redirection to the login page
> 5. Try to connect => impossible
> 6. I tried to delete cookies, I use an incognito browser
> 
> I attached a screen record
> 
> https://drive.google.com/file/d/1issGImseVEIHzkPiHQvym_KdxEKxOasy/view?usp=sharing
> 
> 1. I tested on the same server 1770rc1build1
> 2. In the BO > Adavnced Parameters > Administration >  SameSite=None
> 3. Go to BO > Shop Parameters > General > Disable SSL and Save
> 4. Go to BO > Shop Parameters > Traffic & SEO page > Change the Shop domain & SSL domain and Save
> 5. Go to Dashboard > No Redirection to the login page
> 
> https://drive.google.com/file/d/1Q9XXrxJehMiPtQsqSLKJFiHpnSCZJjHj/view?usp=sharing
> 
> Thanks!

You can't use SameSite=None without SSL, if you disable it after having configured your Cookie SameSite, you should know that something will fail :sweat_smile: 
Otherwise, keep in mind the SSL is the new standard, having a website without SSL will be considered as insecure.
ping @PrestaShop/product-team wdyt?

**Comment by marionf** [comment]
@PierreRambaud 

I am not sure to understand what is SameSite=None
> you should know that something will fail 

Maybe we can inform the user earlier that something will fail with an information message when he/she do this ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud
> 
> I am not sure to understand what is SameSite=None
> 
> > you should know that something will fail
> 
> Maybe we can inform the user earlier that something will fail with an information message when he/she do this ?

There are two things to know right now.

The SameSite will be mandatory in cookie configuration. The default value is Lax, but if you want to use it with `None` you can only do it when your website is running under an SSL configuration.
The second one is, all websites, and especially e-commerce websites must have SSL configured otherwise, they are tagged as `Unsecure`.
So, if you took the time to configure the SameSite to None, then remove the SS, you're pretty sure to have a bad time :sweat_smile: 
But we can add verification to be sure the Cookie `SameSite` value is not settled to `None` when trying to disable the SSL configuration?

**Comment by HartLarsson** [comment]
i would suggest to read this interesting article that explain how things works :)

https://medium.com/swlh/how-the-new-chrome-80-cookie-rule-samesite-none-secure-affects-web-development-c06380220ced

**Comment by PierreRambaud** [comment]
> i would suggest to read this interesting article that explain how things works :)
> 
> https://medium.com/swlh/how-the-new-chrome-80-cookie-rule-samesite-none-secure-affects-web-development-c06380220ced

Yep and more information here #20601

**Comment by marionf** [comment]
> But we can add verification to be sure the Cookie SameSite value is not settled to None when trying to disable the SSL configuration?

Yes, and let the user know with a message why he/she can't disable the SSL

**Review by atomiix — DISMISSED** [review]

File: src/Adapter/Preferences/PreferencesConfiguration.php [hunk 1]
```diff
@@ -70,6 +71,16 @@ public function getConfiguration()
      */
     public function updateConfiguration(array $configuration)
```
Comment (Progi1984) [inline src/Adapter/Preferences/PreferencesConfiguration.php:72]: Please add an unit test

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 2]
```diff
@@ -0,0 +1,216 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace Tests\Unit\Adapter;
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
 */

declare(strict_types=1);

namespace Tests\Unit\Adapter;
```

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 3]
```diff
@@ -0,0 +1,216 @@
...
+                        ['PS_PRICE_ROUND_MODE', null, null, 'test'],
+                        ['PS_ROUND_TYPE', null, null, 'test'],
+                        ['PS_SHOP_ACTIVITY', null, null, 'test'],
+                    ]
+                )
+            );
+
+        $this->mockConfiguration->method('getBoolean')
+            ->will(
+                $this->returnValueMap(
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
            ->willReturnMap(
```

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 4]
```diff
@@ -0,0 +1,216 @@
...
+                        ['PS_SSL_ENABLED_EVERYWHERE', false, true],
+                        ['PS_TOKEN_ENABLE', false, true],
+                        ['PS_ALLOW_HTML_IFRAME', false, true],
+                        ['PS_USE_HTMLPURIFIER', false, true],
+                        ['PS_DISPLAY_SUPPLIERS', false, false],
+                        ['PS_DISPLAY_MANUFACTURERS', false, true],
+                        ['PS_DISPLAY_BEST_SELLERS', false, false],
+                        ['PS_MULTISHOP_FEATURE_ACTIVE', false, true],
+                    ]
+                )
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
```

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 5]
```diff
@@ -0,0 +1,216 @@
...
+        $this->mockConfiguration->method('get')
+            ->will(
+                $this->returnValueMap(
+                    [
+                        ['PS_PRICE_ROUND_MODE', null, null, 'test'],
+                        ['PS_ROUND_TYPE', null, null, 'test'],
+                        ['PS_SHOP_ACTIVITY', null, null, 'test'],
+                    ]
+                )
+            );
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
            ->willReturnMap(
                    [
                        ['PS_PRICE_ROUND_MODE', null, null, 'test'],
                        ['PS_ROUND_TYPE', null, null, 'test'],
                        ['PS_SHOP_ACTIVITY', null, null, 'test'],
                    ]
            );
```

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 6]
```diff
@@ -0,0 +1,216 @@
...
+    public function testUpdateConfiguration()
+    {
+        $this->mockConfiguration->method('get')
+            ->will(
+                $this->returnValueMap(
+                    [
+                        ['PS_COOKIE_SAMESITE', null, null, Cookie::SAMESITE_NONE],
+                    ]
+                )
+            );
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
            ->willReturnMap(
                    [
                        ['PS_COOKIE_SAMESITE', null, null, Cookie::SAMESITE_NONE],
                    ]
            );
```

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 7]
```diff
@@ -0,0 +1,216 @@
...
+        $this->mockConfiguration->method('set')
+            ->will(
+                $this->returnValueMap(
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
            ->willReturnMap(
```

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 8]
```diff
@@ -0,0 +1,216 @@
...
+                        ['PS_USE_HTMLPURIFIER', true],
+                        ['PS_DISPLAY_SUPPLIERS', false],
+                        ['PS_DISPLAY_MANUFACTURERS', true],
+                        ['PS_DISPLAY_BEST_SELLERS', false],
+                        ['PS_MULTISHOP_FEATURE_ACTIVE', true],
+                        ['PS_PRICE_ROUND_MODE', 'test'],
+                        ['PS_ROUND_TYPE', 'test'],
+                        ['PS_SHOP_ACTIVITY', 'test'],
+                    ]
+                )
```
Comment (Progi1984) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
```

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

File: src/Adapter/Preferences/PreferencesConfiguration.php [hunk 9]
```diff
@@ -70,24 +71,59 @@ public function getConfiguration()
...
-            $this->configuration->set('PS_DISPLAY_SUPPLIERS', $configuration['display_suppliers']);
-            $this->configuration->set('PS_DISPLAY_MANUFACTURERS', $configuration['display_manufacturers']);
-            $this->configuration->set('PS_DISPLAY_BEST_SELLERS', $configuration['display_best_sellers']);
-            $this->configuration->set('PS_MULTISHOP_FEATURE_ACTIVE', $configuration['multishop_feature_active']);
-            $this->configuration->set('PS_SHOP_ACTIVITY', $configuration['shop_activity']);
+        if (false === $this->validateConfiguration($configuration)) {
+            return [
+                [
+                    'key' => 'Invalid configuration',
+                    'domain' => 'Admin.Advparameters.Notification',
```
Comment (Julievrz) [inline src/Adapter/Preferences/PreferencesConfiguration.php]: Hi, this string already exists in **Admin.Notifications.Warning**
I think we can keep this one instead of creating a new one.

Comment (PierreRambaud) [inline src/Adapter/Preferences/PreferencesConfiguration.php]:
```suggestion
                    'domain' => 'Admin.Notifications.Warning',
```

**Comment by Julievrz** [comment]
Thanks for the modifications, the wording is ok for me now. ☺️

File: tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php [hunk 10]
```diff
@@ -0,0 +1,213 @@
...
+        );
+    }
+
+    public function testUpdateConfigurationWithInvalidConfiguration()
+    {
+        $this->assertSame(
+            [
+                [
+                    'key' => 'Invalid configuration',
+                    'domain' => 'Admin.Advparameters.Notification',
```
Comment (PierreRambaud) [inline tests/Unit/Adapter/Preferences/PreferencesConfigurationTest.php]:
```suggestion
                    'domain' => 'Admin.Notifications.Warning',
```

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

It is ok :heavy_check_mark: 
1. Fresh install with SSL enabled, the PS_COOKIE_SAMESITE have the `Lax` value
2. Set-Cookie SameSite to None => ok (when SSL enabled or disabled) 
image 
image
3. Disable SSL => ok 
image
4. When SSL enabled / SSL enabled on all page, When I navigate to the BO, In the Dev Tools => Application Tab => Click Storage / Cookies
PrestaShop-* cookie have `Secure` flag set 
image


Thank you!

**Comment by PierreRambaud** [comment]
Thank you @khouloudbelguith
