### PR TITLE
Disable module's hook before upgrading it

### LINKED ISSUE #29542: Upgrade using actionBeforeUpgrade does not execute migrations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Have 2 modules :

First one implementing the hook `actionBeforeUpgrade` which we will call The Updater : As expected on PS 8.0.0, this hook will retrieve the updated module new files, extract them into the modules folder and let the ModuleManager continue the upgrade (migrations, update DB, ...)

A second one which is a classic module implementing an "early hook" : a hook executed before the upgrade, like `actionDispatcherBefore` (this one is called when any request is made on the shop. It detects which controller domain it is front/admin/other and perform authentication checks)

Have an update version available for module 2 and execute the upgrade through The Updater

Observation : The module 1 files are well replaced but the migrations are not executed and the version in DB is wrong
Other observation : the file config_ISO.xml in the root folder of the module 1 contains the old version number

### Expected behavior

_No response_

### Steps to reproduce

1 - have a fresh install of PS 8.0.0

2 - Install [prestashopexamplemodule_1.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/9495809/prestashopexamplemodule_1.0.0.zip) : This module is a classic module implementing `actionDispatcherBefore`. It is in the version 1.0.0 and register a config value in ps_configuration EXAMPLE_MODULE_CONFIG = "VALUE FOR 1.0.0"

3 - Install [prestashopexampleupdatermodule.zip](https://github.com/PrestaShop/PrestaShop/files/9495840/prestashopexampleupdatermodule.zip) : This module is The Updater. It implements `actionBeforeUpgrade`. This hook will extract and install the module prestashopexamplemodule_1.0.1.zip built in it. This new version of module 1 will have the version 1.0.1 and change the config value to EXAMPLE_MODULE_CONFIG = "VALUE FOR 1.0.1"

4 - once the 2 modules are installed. You will see that module 1 have an upgrade available.
Execute that update and observe that files are replaced (v1.0.1 in config.xml and prestashopexamplemodule.php) but the migrations are not executed : You'll have the same value for "EXAMPLE_MODULE_CONFIG" in ps_configuration and the version of module 1 in DB is still 1.0.0
If your shop is in french for example. You'll also have a file config_fr.xml containing version 1.0.0 instead of 1.0.1

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #31098: Error when upgrading module ps_distributionapiclient
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we try to upgrade (or downgrade) ps_distributionapiclient an error shows up. The following steps describe the root of the issue
1. Symfony loads the container with configuration inside ps_distributionapiclient version A
2. The version B is downloaded and the new folder replaces the one from version A
4. Later, from ModuleManager:upgrade we dive deep through several classes until 'actionListModules' hook is executed
5. This hook is catched by ps_distributionapiclient module inside ps_distributionapiclient.php
6. `return $this->getDistributionApi()->getModuleList();` is executed
7. `getDistributionApi()` is a function which try to get DistributionApi service
8. The container try to instantiate it with the constructor of the new version (B) although the configuration from version A was loaded (conf. step 1)
Capture d’écran 2023-01-30 à 15 20 31

### Expected behavior

When I try to upgrade (or downgrade) ps_distributionapiclient, no errors should be dislayed.

### Steps to reproduce

1. Go to the module page.
2. Click on install module button on the top right of the page
3. Drop a new version of ps_distributionapiclient
4. See the error

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

ps_distributionapiclient (the version doesn't matter)

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Disable module's hook before upgrading it: this avoids the crazy situation where a module is being both used and upgrade simultaneously, which causes plenty issues like #31098 and #29542
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | If you try to test a new version of [ps_distributionapiclient](https://github.com/PrestaShop/ps_distributionapiclient/) (use the `dev` branch of ps_distributionapiclient) like [1.0.3](https://github.com/PrestaShop/ps_distributionapiclient/pull/12), it will fail. However if you use this PR, then try to install a new version of ps_distributionapiclient.<br/>This PR is supposed to help us finally unlock [ps_distributionapiclient release 1.0.3](https://github.com/PrestaShop/ps_distributionapiclient/pull/12)! 😄 
| Fixed ticket?     | Resolves #31098, resolves #29542
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

File: src/Core/Module/SourceHandler/RemoteZipSourceHandler.php [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+declare(strict_types=1);
+
+namespace PrestaShop\PrestaShop\Core\Module\SourceHandler;
+
+class RemoteZipSourceHandler implements SourceHandlerInterface
```
Comment (matks) [inline src/Core/Module/SourceHandler/RemoteZipSourceHandler.php:36]: This class can be unit tested 👍

**Review by matks — DISMISSED** [review]
LGTM

File: src/Core/Module/SourceHandler/RemoteZipSourceHandler.php [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        return reset($parts);
+    }
+
+    public function handle(string $source): void
+    {
+        $path = $this->getDownloadDir($this->getModuleName($source));
+        if (!file_exists(dirname($path))) {
+            mkdir(dirname($path), 0777, true);
+        }
+        file_put_contents($path, file_get_contents($source));
```
Comment (FabienPapet) [inline src/Core/Module/SourceHandler/RemoteZipSourceHandler.php]: use Symfony Filesystem to dump and Symfony httpclient to download file.

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php [hunk 3]
```diff
@@ -193,6 +193,7 @@ public function moduleAction(Request $request)
         }
 
         $module = $request->get('module_name');
+        $source = $request->get('source');
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: $request->query->get()

File: src/Core/Module/SourceHandler/RemoteZipSourceHandler.php (hunk 1 above)
Comment (FabienPapet) [reply src/Core/Module/SourceHandler/RemoteZipSourceHandler.php:36]: I don't understand the class name :D

**Review by FabienPapet — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Resources/config/services/core/module.yml [hunk 4]
```diff
@@ -33,10 +33,17 @@ services:
       - '%modules_dir%'
       - '@translator'
 
+  prestashop.module.sourcehandler.remote_zip:
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Resources/config/services/core/module.yml]: private +FQCN

File: src/Core/Module/SourceHandler/RemoteZipSourceHandler.php (hunk 1 above)
Comment (FabienPapet) [reply src/Core/Module/SourceHandler/RemoteZipSourceHandler.php:36]: Interface name and signature is weird, what's its purpose exactly ?

Comment (atomiix) [reply src/Core/Module/SourceHandler/RemoteZipSourceHandler.php:36]: The purpose of this class is to download module (as a Zip file) and extract its content to the `modules/` folder so the upgrade can proceed.

**Review by matks — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

File: src/Core/Module/ModuleManager.php [hunk 5]
```diff
@@ -182,6 +182,8 @@ public function upgrade(string $name, $source = null): bool
             $handler->handle($source);
         }
 
+        $this->hookManager->disableHooksForModule($this->moduleDataProvider->getModuleIdByName($name));
```
Comment (sowbiba) [inline src/Core/Module/ModuleManager.php:185]: Any chance this will cause issues if the module being updated regitered `actionBeforeUpgradeModule` ?

Comment (matks) [reply src/Core/Module/ModuleManager.php:185]: On the contrary, I believe this PR is likely to _avoid_ problems due to `actionBeforeUpgradeModule`.

Today, if a module ABC is plugged on `actionBeforeUpgradeModule` then we enter the crazy situation where
- the ABC module is being updated -> this means change of PHP files, cache cleared, new config loaded (like Symfony services definitions), SQL scripts run...
- the ABC module is also called by hook `actionBeforeUpgradeModule`

It's the serpent eating its own tail 😅 and is causing crazy behaviors.

This PR un-plugs the hooks of module ABC before launching the hook. Then the serpent cannot eat its own tail.

From my point of view, we should never have this situation:
> - the ABC module is being updated -> this means change of PHP files, cache cleared, new config loaded (like Symfony services definitions), SQL scripts run...
- the ABC module is also called by hook `actionBeforeUpgradeModule`

This is not a reliable situation.

However what makes sense is
- module ABC is plugged on `actionBeforeUpgradeModule` hook
- module XYZ is being updated -> hook is triggered and module ABC catches the hook and reacts

**Review by AureRita — APPROVED** [review]
Hi @atomiix 

Thank you for your PR, I tested it and it works, as we can see here :

[Untitled_ Feb 9, 2023 11_37 AM.webm](https://user-images.githubusercontent.com/100699445/217834386-8bee921c-0023-44dc-b9f4-2fa631ac1499.webm)

**Comment by nicosomb** [comment]
Thank you @atomiix and @AureRita !
