### PR TITLE
Fix help sidebar on Experimental Features BO Page

### LINKED ISSUE #23996: BO - Experimental Feature - The help modal cannot be opened
#### Describe the bug

If this PR: https://github.com/PrestaShop/PrestaShop/pull/23703 is merged, a new BO page Experimental Feature is displayed, in this page, the help modal cannot be opened.
As discussed with @matks,` it makes sense! this is a new BO page, so there is no related help page on help.prestashop.com`

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Experimental Feature page
2. Click on 'Help'
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fix help sidebar on Experimental Features BO Page by providing the right help_link.<br/><br/>help.prestashop.com has been deployed to provide the needed content although it is very minimal for now https://help.prestashop.com/en/doc/AdminFeatureFlag?version=1.7.8.0 and https://help.prestashop.com/fr/doc/AdminFeatureFlag?version=1.7.8.0
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/23996
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/23996
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25004)

### CODE REVIEW

File: controllers/admin/AdminLegacyLayoutController.php [hunk 1]
```diff
@@ -38,9 +38,22 @@ class AdminLegacyLayoutControllerCore extends AdminController
...
-    /** @var string */
+    /**
+     * The Help Link is used for the 'Help' button in the top right of Back Office pages
+     *
+     * If $enableSidebar is true, the 'Help' button will download the content available at $helpLink
+     * and inject it into the sidebar window
+     *
+     * If $enableSidebar is false, the 'Help' button is a link that redirects to $helpLink
+     *
+     * @var string
```
Comment (Progi1984) [inline controllers/admin/AdminLegacyLayoutController.php:55]:
```suggestion
     * @var string|null
```

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks for the additional PHPDoc, it makes more sense now ^^

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @matks and @sarahdib
