### PR TITLE
Fix bug on displayed price's calculation in BO order page under specific conditions

### LINKED ISSUE #21708: BO - Order page - Incorrect Total's product line when Round type = "Round on each item"
#### Describe the bug

In the BO > Shop Parameters > General page > Round type = "Round on each item".
When creating an order from the BO > The product's total line is NOK.
image

#### Steps to Reproduce

0. In Shop Parameters > Custom Settings > Groups > Edit Customer "Price display method" => tax included
1. Create a productA with 21% tax, €7.8 tax excluded
2. Go to BO > Order page > Add new order
3. Add the product with quantity =80
4. Create the order
5. see the error: the Total Tax included for the Product detail line is NOK

PS: reproduced when shipping is free or not.
when `Round on each line` or `Round on the total` is applied => ok (no issue)

**Screenshots**
image

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

#### Specs
Round on each item = product unit price rounded
Round on each line = total of the line rounded
https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/price-calculation-rules.md

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | This PR is a bug fix in `OrderForViewing`, when the customer's group price display method is set to "tax inclusive", the shop rounding method is set to "per article", and the tax applied is an odd tax like 21%. Then the total display per order detail is not correct. (only the displayed value for viewing)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21708
| How to test?  | See steps in the issue, it's important to respect all steps, for example you won't reproduce the bug if you don't have an odd tax like 21%.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22126)

### CODE REVIEW

File: tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+
+class PriceDisplayMethodConfigurationFeatureContext extends AbstractConfigurationFeatureContext
+{
+    /**
+     * @Given /^price display method for the group of the customer having email "(.+)" is "(tax included|tax excluded)"$/
+     */
+    public function setPriceDisplayMethodForCustomer(string $customerEmail, string $priceDisplayMethod)
+    {
+        $data = Customer::getCustomersByEmail($customerEmail);
+        $customer = new Customer($data[0]['id_customer']);
```
Comment (Arman-Hosseini) [inline tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php]: Hi dear @matthieu-rolland,

The user has been fetched. Why the new object?

Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php]: hello @Arman-Hosseini ,

`Customer::getCustomersByEmail` returns the result of a sql query, so $data only contains an array of data, not a customer object.  (It's a static method, at this point the customer is not instantiated)

File: classes/Group.php [hunk 2]
```diff
@@ -73,6 +73,9 @@ class GroupCore extends ObjectModel
 
     protected $webserviceParameters = [];
 
+    const PRICE_DISPLAY_METHOD_TAX_INCL = 0;
+    const PRICE_DISPLAY_METHOD_TAX_EXCL = 1;
```
Comment (Progi1984) [inline classes/Group.php]:
```suggestion
    public const PRICE_DISPLAY_METHOD_TAX_INCL = 0;
    public const PRICE_DISPLAY_METHOD_TAX_EXCL = 1;
```

File: tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php (hunk 1 above)
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php]:
```suggestion
        $data = Customer::getCustomersByEmail($customerEmail);
        $data = reset($data);
        if (!isset($data['id_customer'])) {
            throw new Exception('User not found');
        }
        $customer = new Customer($data['id_customer']);
```

File: tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+        $group = new Group($customer->id_default_group);
+        if ($priceDisplayMethod === 'tax included') {
+            $group->price_display_method = Group::PRICE_DISPLAY_METHOD_TAX_INCL;
+        } elseif ($priceDisplayMethod === 'tax excluded') {
+            $group->price_display_method = Group::PRICE_DISPLAY_METHOD_TAX_EXCL;
+        }
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php:54]: else => exception

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 4]
```diff
@@ -1726,4 +1726,40 @@ private function getProductTaxCalculator(int $orderId, int $productId)
 
         return $taxManager->getTaxCalculator();
     }
+
+    /**
+     * @Then the product :productReference in order :orderReference has the following prices for viewing in BO:
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
     * @Then the product :productReference in order :orderReference has following prices:
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 4 above)
Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: I want to keep "for viewing in BO", because it's a calculation that's made for display in BO only (the real price is actually right, it doesn't change what the customer pays in the end)

File: tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+use Customer;
+use Group;
+use RuntimeException;
+
+class PriceDisplayMethodConfigurationFeatureContext extends AbstractConfigurationFeatureContext
+{
+    /**
+     * @Given /^price display method for the group of the customer having email "(.+)" is "(tax included|tax excluded)"$/
+     */
+    public function setPriceDisplayMethodForCustomer(string $customerEmail, string $priceDisplayMethod)
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php]:
```suggestion
    public function setPriceDisplayMethodForCustomer(string $customerEmail, string $priceDisplayMethod): void
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 6]
```diff
@@ -1726,4 +1726,40 @@ private function getProductTaxCalculator(int $orderId, int $productId)
...
         return $taxManager->getTaxCalculator();
     }
+
+    /**
+     * @Then product :productReference in order :orderReference has following prices for viewing in BO:
+     *
+     * @param string $orderReference
+     * @param TableNode $table
+     */
+    public function checkOrderForViewingWithReference(string $productReference, string $orderReference, TableNode $table)
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
    public function checkOrderForViewingWithReference(string $productReference, string $orderReference, TableNode $table): void
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 7]
```diff
@@ -1726,4 +1726,40 @@ private function getProductTaxCalculator(int $orderId, int $productId)
...
+    {
+        $orderId = SharedStorage::getStorage()->get($orderReference);
+        $productId = $this->getProductIdByName($productReference);
+        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing((int) $orderId));
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
        $orderId = (int) SharedStorage::getStorage()->get($orderReference);
        $productId = $this->getProductIdByName($productReference);
        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

**Comment by Progi1984** [comment]
@matthieu-rolland Need a rebase

File: tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+    {
+        $data = Customer::getCustomersByEmail($customerEmail);
+        $data = reset($data);
+        if (!isset($data['id_customer'])) {
```
Comment (Arman-Hosseini) [inline tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php:42]:
```suggestion
        if (false === ($data = reset($data))) {
```

Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/Configuration/PriceDisplayMethodConfigurationFeatureContext.php:42]: Thank you for your review ! 

hm, I think it makes the code less understandable without adding anything... 🤔

**Comment by matthieu-rolland** [comment]
@Progi1984 rebase and feedbacks applied 👍

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @matthieu-rolland !!

**Comment by PululuK** [comment]
Thanks @matthieu-rolland
