### PR TITLE
BO - Customer Page - Allow only positive number for Maximum number of payment days

### LINKED ISSUE #27784: BO - Customers page - An exception is displayed when "Maximum number of payment days" invalid
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Customers > Customers page, when we Add/Edit a customer with invalid "Maximum number of payment days", an exception is displayed
image

### Expected behavior

_No response_

### Steps to reproduce

1. Enable B2B in the BO > Shop Parameters > Customer Settings page
2. Go to BO > Customers > Customers page
2. Add/Edit a customer
3. Add the "Maximum number of payment days" field with a negative number
4. Save
5. See error

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.3

### PHP version(s) where the bug happened

7.3, 7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | BO - Customer Page - Allow only positive number for Maximum number of payment days
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27784
| How to test?      | 1. Enable B2B in the BO > Shop Parameters > Customer Settings page<br>2. Go to BO > Customers > Customers page<br>2. Add/Edit a customer<br>3. Add the "Maximum number of payment days" field with a negative number<br>4. Save<br>5. **BEFORE :** See error<br>5. **AFTER :** A constraint is added if lower than 0.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27793)

### CODE REVIEW

**Review by saulaski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 1]
```diff
@@ -306,6 +307,15 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                     ),
                     'required' => false,
                     'invalid_message' => $this->trans('This field is invalid.', 'Admin.Notifications.Error'),
+                    'constraints' => [
+                        new GreaterThan([
+                            'value' => 0,
+                            'message' => $this->trans(
+                                'Invalid value: the maximum number of payment days must be a positive amount.',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]:
```suggestion
                                '%s is invalid. Please enter an integer greater than or equal to 0.',
```

We could use this existing string. :-)

**Review by Julievrz — COMMENTED** [review]
A wording suggestion

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: Fixed

**Comment by Progi1984** [comment]
@Julievrz Wording applied

@matthieu-rolland @atomiix @saulaski Rebased & Wording applied

**Review by Julievrz — DISMISSED** [review]
Thanks!

**Review by PierreRambaud — APPROVED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 2]
```diff
@@ -306,6 +307,15 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                     ),
                     'required' => false,
                     'invalid_message' => $this->trans('This field is invalid.', 'Admin.Notifications.Error'),
+                    'constraints' => [
+                        new GreaterThan([
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]:
```suggestion
                        new GreaterThanOrEqual([
```

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 3]
```diff
@@ -44,6 +44,7 @@
 use Symfony\Component\OptionsResolver\OptionsResolver;
 use Symfony\Component\Translation\TranslatorInterface;
 use Symfony\Component\Validator\Constraints\Email;
+use Symfony\Component\Validator\Constraints\GreaterThan;
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]:
```suggestion
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Miss click, regarding your message, you should use `GreaterThanOrEqual` instead

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: I agree with Pierre, with the current code you can't enter 0 anymore which is a valid value

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Comment by Progi1984** [comment]
@PierreRambaud & @jolelievre It's good. And rebased :)

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php (hunk 2 above)
Comment (saulaski) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: @PierreRambaud good catch !

**Review by saulaski — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by tegbessou — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
Thanks @Progi1984

**Review by jolelievre — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @Progi1984,

I have an issue following these steps:
1. Enable B2B
2. Go to BO > Customers > Create a new customer
3. Set the filed `Maximum number of payment days` with `758678967867865`
4. Save
5. See error 
image

https://user-images.githubusercontent.com/16067358/156559044-ba537813-896b-4829-8f82-bca0537a2504.mp4

Thanks!

**Comment by Progi1984** [comment]
@jolelievre & @atomiix Added a new constraint for high limit. :)

**Comment by saulaski** [comment]
@khouloudbelguith Good catch ! You love crazy numbers, don't you ? :))

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 4]
```diff
@@ -306,6 +308,22 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                                'Admin.Notifications.Error'
+                            ),
+                        ]),
+                        new LessThan([
+                            'value' => 4294967296,
+                            'message' => $this->trans(
+                                '%s is invalid. Please enter an integer lower than %s.',
+                                'Admin.Notifications.Error'
+                            ),
+                        ]),
```
Comment (saulaski) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: Shorter, faster, easier ?
```suggestion
                        new Range([
                            'min' => 0,
                            'max' => 4294967295,
                            'minMessage' => $this->trans(
                                '%s is invalid. Please enter an integer greater than or equal to 0.',
                                'Admin.Notifications.Error'
                            ),
                            'maxMessage' => $this->trans(
                                '%s is invalid. Please enter an integer lower than %s.',
                                'Admin.Notifications.Error'
                            ),
                        ]),
```

**Review by saulaski — DISMISSED** [review]
Only a suggestion

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php (hunk 4 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: I didn't know it. Thanks

**Review by matthieu-rolland — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 5]
```diff
@@ -306,6 +307,20 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                     ),
                     'required' => false,
                     'invalid_message' => $this->trans('This field is invalid.', 'Admin.Notifications.Error'),
+                    'constraints' => [
+                        new Range([
+                            'min' => 0,
+                            'max' => 4294967295,
```
Comment (atomiix) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: Can you make it a const somewhere? 🙃

Comment (saulaski) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: Very good catch that leads to further thinking...
1. PHP doesn't use unsigned integers, only signed integers. It means the max integer value should be: 2,147,483,647
2. Integers range depends on the platform: 32 bits (2 trillions above) or 64 bits (9E18)
3. There is a native PHP constant, platform dependant, for max value: `PHP_INT_MAX`
4. But what really matters is the max value in database: ps_customer.max_payment_days (unsigned int) => 4,294,967,295
5. It means PHP max value cannot reach MySQL max value on 32 bits platforms
6. On the other hand, such high values don't make any sense from a business point of view. 1 year max (365 days) sounds like a better compromise, or maybe a few years in extreme cases ?

This issue is tricky. I should have thought about it earlier, my apologies :(

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php]: No apologies : it's a pleasure to have feedback.

@atomiix I have done

@saulaski We are a platform. We should limit technically, not for business point of view. Because relative to the business, we can be lower for a specific business and higher for an another one.

File: src/Adapter/Validate.php [hunk 6]
```diff
@@ -33,6 +33,8 @@
  */
 class Validate
 {
+    public const MYSQL_UNSIGNED_INT_MAX = 4294967295;
```
Comment (atomiix) [inline src/Adapter/Validate.php]:
```suggestion
    public const MYSQL_UNSIGNED_INT_MAX = 4294967295; // max 32 bits value: (2^32)-1 
```

Comment (atomiix) [reply src/Adapter/Validate.php]: Just a suggestion so we don't think this number just came out of the blue

Comment (Progi1984) [reply src/Adapter/Validate.php]: Fixed

**Review by atomiix — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

File: src/Adapter/Validate.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Validate.php]: I like the technical solution proposed here I'm just not convinced at all with the location of the const (in an Adapter service class) Especially since this namespace is destined to be moved

I would suggest alternatives:
- put the const in the legacy `ValidateCore` class for now (in the absence of a better solution)
- create a dedicated constraint `UnsignedInt` in the `PrestaShop\PrestaShop\Core\ConstraintValidator\Constraints` namespace (but it's more work)
- put this const in a related VO but the issue is that this notion is quite generic and not related to a specific domain value

So for now my best proposal would be to have this in the `ValidateCore`

Comment (Progi1984) [reply src/Adapter/Validate.php]: Fixed

**Review by PierreRambaud — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @Progi1984,

the alert is incorrect when we enter a number like this `544554654546545`

`544554654546545 is invalid. Please enter an integer lower than 0.`

We should not enter `an integer lower than 0` but `greater than or equal to 0`
image

Thanks!

**Comment by saulaski** [comment]
@Progi1984 @khouloudbelguith 
An idea about what's happening here: the translated error message is incompatible with `Range` constraint.
`'%s is invalid. Please enter an integer lower than %s.'`
Such error message works fine with "simple" constraints like `LowerThan`, because only 2 parameters are used by anonymous placeholders `%s`:
- current value
- max limit

In case of `Range` constraint, a few parameters are set in this order:
1. current value
2. min limit => 0
3. max limit

If the message uses `sprintf` syntax as placeholders, placeholders are replaced in the same order.
Instead we should use a dedicated message with named placeholders:
`'{{value}} is invalid. Please enter an integer lower than {{max}}.'`

**Comment by Progi1984** [comment]
@saulaski I have found a solution where I use placeholders defined in [RangeValidator](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Validator/Constraints/RangeValidator.php#L105-L107) without changing the wording.

File: src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php [hunk 7]
```diff
@@ -306,6 +308,24 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                            'minMessage' => $this->trans(
+                                '%s is invalid. Please enter an integer greater than or equal to 0.',
+                                'Admin.Notifications.Error'
+                            ),
+                            'maxMessage' => $this->trans(
+                                '%s is invalid. Please enter an integer lower than %s.',
+                                'Admin.Notifications.Error',
+                                [
+                                    '{{ value }}',
+                                    '{{ max }}',
```
Comment (saulaski) [inline src/PrestaShopBundle/Form/Admin/Sell/Customer/CustomerType.php:324]: @Progi1984 Nice trick :))

**Review by saulaski — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by khouloudbelguith — DISMISSED** [review]
Hi @Progi1984,

I checked with @Julievrz.
When we enter an invalid integer `576767837867856`.

We have this alert `576767837867856 is invalid. Please enter an integer lower than 4294967295.`

But it should be `576767837867856 is invalid. Please enter an integer lower than or equal to 4294967295.` because we can enter this number `4294967295`.

I attached a screen record

https://user-images.githubusercontent.com/16067358/157457979-c82b0772-4545-4488-b460-52f9d8b5b225.mp4

Thanks!

**Comment by Progi1984** [comment]
@PierreRambaud @saulaski @atomiix Fixed the new wording for @Julievrz & @khouloudbelguith

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @Progi1984,

I checked the Maximum number of payment days
 1. Negatif 
image
2. Negatif too long 
image
3. Positif invalid 
image
4. Positif too long 
image

I checked B2B enabled and disabled:
1. Create a customer from BO / create customer from add a new order 
2. Create a customer via API 
image
3. Import customer
4. Create a customer/guest from FO
5. Sign in & create an order with a guest

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith & @Julievrz
