### PR TITLE
Make Module manager error notifications fixed

### LINKED ISSUE #20700: Make Module manager notifications/flash messages last longer
Make a module return false on install, try to install to get a error notification / flash message.
It works, but it shows for to short amount of time - no time to read if there is important information.

Should be longer, or better lasting forever until you close it with an x.

Screenshot 2020-08-25 at 10 27 15

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix the error notification when an error occured on install / uninstall / enable / disable module
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20700 
| How to test?  | Generate a module with a false return on installation and try to install it. You should have the red error notification which remains fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21121)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/components/module-card.js [hunk 1]
```diff
@@ -347,7 +347,7 @@ export default class ModuleCard {
           self.confirmPrestaTrust(result[moduleTechName]);
         }
 
-        $.growl.error({message: result[moduleTechName].msg});
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/components/module-card.js:350]: This one is aiming errors on install where status == false, but what about others growls ?

Should we put the same behavior on request error or whatever ? wdyt ? @Sinepel

Comment (Sinepel) [reply admin-dev/themes/new-theme/js/components/module-card.js:350]: Maybe for the other `$.growl.error` but not needed for the `$.grow.notice` ? wdyt ?

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/components/module-card.js:350]: I agree that errors needs to be read, while notice can be avoided, but maybe we can increase a bit the time for notice to make it easier to read !

File: admin-dev/themes/new-theme/js/components/module-card.js [hunk 2]
```diff
@@ -347,11 +347,11 @@ export default class ModuleCard {
...
+        $.growl.error({message: result[moduleTechName].msg, fixed: true});
         return;
       }
 
-      $.growl.notice({message: result[moduleTechName].msg});
+      $.growl.notice({message: result[moduleTechName].msg, duration: 15000});
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/components/module-card.js]:
```suggestion
      $.growl.notice({message: result[moduleTechName].msg, duration: 6000});
```

Should be way enough :p

Comment (Sinepel) [reply admin-dev/themes/new-theme/js/components/module-card.js]: You mean I was too greedy?!
I'm OK !

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @Sinepel 
TEST OK, The error notification remains now fixed instead of disappearing after a few seconds.
Capture d’écran 2020-09-29 à 13 58 59

Thank you 💯

**Comment by Progi1984** [comment]
Thanks @Sinepel & @ngodefroy
