### PR TITLE
Don't get info about email exists when reset admin password

### LINKED ISSUE #29568: Don't get info about email exists when reset admin password
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Don't get info about email exists when reset admin password.

### Expected behavior

Display a generic message: "If this email address has been registered in our shop, you will receive a link to reset your password at {...}"

image

### Steps to reproduce

Try to reset admin password and see :  

image

### PrestaShop version(s) where the bug happened

N/A

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Don't get info about email exists when reset admin password.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29568
| Related PRs       | N/A
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/29568
| Possible impacts? | N/A

### CODE REVIEW

File: controllers/admin/AdminLoginController.php [hunk 1]
```diff
@@ -310,7 +310,16 @@ public function processForgot()
         } else {
             $employee = new Employee();
             if (!$employee->getByEmail($email)) {
-                $this->errors[] = $this->trans('This account does not exist.', [], 'Admin.Login.Notification');
+                die(json_encode([
```
Comment (matks) [inline controllers/admin/AdminLoginController.php:313]: I agree that the code is now better.

But `die(json_encode(...))` looks soooooo bad 😢 . Do you think we could at least have a `private function returnJson()` or something in the class to be used instead?

**Comment by atomiix** [comment]
We must check that there's no significative response time difference between an existing and a non-existing email address 😅

**Review by kpodemski — CHANGES_REQUESTED** [review]
Coding standards :-)

File: admin-dev/themes/default/template/controllers/login/content.tpl [hunk 2]
```diff
@@ -142,7 +142,7 @@
 			</div>
 
 			<div class="front forgot_confirm" style="display: none">
-				<h4 id="forgot_confirm_name">{l s='Please, check your mailbox.' d='Admin.Login.Notification'}<br/><br/>{l s='A link to reset your password has been sent to you.' d='Admin.Login.Notification'}</h4>
+				<h4 id="forgot_confirm_name">{l s='Please, check your mailbox.' d='Admin.Login.Notification'}<br/><br/>{l s='If this email address has been registered in our shop, you will receive a link to reset your password.' d='Admin.Login.Notification'}</h4>
```
Comment (l-delin) [inline admin-dev/themes/default/template/controllers/login/content.tpl:145]: Is there any way to know in advance if the email matches an account already or not? To know if the wording needs to be updated (eg. "No account was found with this email address.")

ping @PrestaShop/ux-team

Comment (kpodemski) [reply admin-dev/themes/default/template/controllers/login/content.tpl:145]: @l-delin, the point of this change, is to prevent people from knowing this :) this way it is a bit more secure

File: controllers/admin/AdminLoginController.php [hunk 3]
```diff
@@ -310,7 +310,16 @@ public function processForgot()
...
+                    'hasErrors' => false,
+                    'confirm' => $this->trans(
+                        'If this email address has been registered in our shop, you will receive a link to reset your password at %email%.',
```
Comment (kpodemski) [inline controllers/admin/AdminLoginController.php]:
```suggestion
                        'If this email address has been registered in our shop, you will receive a link to reset your password at %email%.',
```

File: controllers/admin/AdminLoginController.php [hunk 4]
```diff
@@ -310,7 +310,16 @@ public function processForgot()
         } else {
             $employee = new Employee();
             if (!$employee->getByEmail($email)) {
-                $this->errors[] = $this->trans('This account does not exist.', [], 'Admin.Login.Notification');
+                die(json_encode([
+                    'hasErrors' => false,
+                    'confirm' => $this->trans(
+                        'If this email address has been registered in our shop, you will receive a link to reset your password at %email%.', 
+                        [
+                            '%email%' => $email
```
Comment (kpodemski) [inline controllers/admin/AdminLoginController.php]:
```suggestion
                            '%email%' => $email,
```

**Review by kpodemski — DISMISSED** [review]

File: controllers/admin/AdminLoginController.php [hunk 5]
```diff
@@ -310,7 +310,16 @@ public function processForgot()
...
             $employee = new Employee();
             if (!$employee->getByEmail($email)) {
-                $this->errors[] = $this->trans('This account does not exist.', [], 'Admin.Login.Notification');
+                die(json_encode([
+                    'hasErrors' => false,
+                    'confirm' => $this->trans(
+                        'If this email address has been registered in our shop, you will receive a link to reset your password at %email%.',
+                        [
+                            '%email%' => $email,
+                        ],
```
Comment (kpodemski) [inline controllers/admin/AdminLoginController.php]:
```suggestion
                        ],
```

**Review by kpodemski — APPROVED** [review]

File: admin-dev/themes/default/template/controllers/login/content.tpl (hunk 2 above)
Comment (matks) [reply admin-dev/themes/default/template/controllers/login/content.tpl:145]: Agreed with @kpodemski : we must NOT inform the user, because this would an important information for a hacker

File: controllers/admin/AdminLoginController.php (hunk 1 above)
Comment (matks) [reply controllers/admin/AdminLoginController.php:313]: As @kpodemski approved the PR I will not ask for 'more' :) and approve the PR

**Review by matks — APPROVED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @PululuK 

Thanx for your PR ! it's LGTM QA :heavy_check_mark: , the automated tests are also  **OK** 
You can see the attached screen record ! 

[Untitled_ Nov 21, 2022 1_48 PM.webm](https://user-images.githubusercontent.com/31663369/203060338-387dde61-da51-4dd5-8290-9af51a07e205.webm)


Thank you ! :rocket:

**Comment by kpodemski** [comment]
Thank you @PululuK @sallemiines :)

**Comment by atomiix** [comment]
@PululuK thanks for this PR, I think that we still can have the information about an existing admin mail address though. If you look at the response itself when the address exists:
Capture d’écran 2022-11-23 à 10 55 53

Also, if there's an issue while sending the mail (probably a bad smtp configuration), we know the mail exists as we tried to send the mail:
Capture d’écran 2022-11-23 à 10 57 22

I think we should send the same message everytime.

Would you be ok to make the PR to fix this? :)
