### PR TITLE
Nightly : 8.1.x - Multistore (Removed Delete shop url)

### LINKED ISSUE #33291: MultiStore : After defining a shop URL, it's not possible to delete a shop URL
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After the  PR #33255, it's not anymore possible to delete a shop URL.

### Expected behavior

It's possible to delete a shop URL.

### Steps to reproduce

1. Enable Multistore
2. Create a shop
3. Set a virtual URL to the shop
4. After submitting the form, try to remove the shop URL
5. It's not possible

--- 
Execute the following UI test : `TEST_PATH="functional/BO/14*/10*/03*" npm run test:specific:fast-fail`

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Nightly : 8.1.x - Multistore (Removed Delete shop url) 
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5599573723
| Fixed ticket?     | Fixes #33291
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

File: tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.ts [hunk 1]
```diff
@@ -148,18 +148,8 @@ describe('BO - Advanced Parameters - Multistore : Create, Read, Update and Delet
     });
   });
 
-  // 4 : Delete shop URL
-  describe('delete shop URL', async () => {
-    it('should delete the shop URL', async function () {
-      await testContext.addContextItem(this, 'testIdentifier', 'deleteShopURL', baseContext);
-
-      const textResult = await shopUrlPage.deleteShopURL(page, 1);
```
Comment (nesrineabdmouleh) [inline tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.ts:156]: Please fix eslint error => 'shopUrlPage' is defined but never used

Comment (Progi1984) [reply tests/UI/campaigns/functional/BO/14_advancedParameters/10_multistore/03_CRUDShops.ts:156]: Fixed

**Review by boubkerbribri — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
Thank you @Progi1984
