### PR TITLE
Remove images from shop when deleting product from shop

### LINKED ISSUE #30792: UniqueConstraintViolationException when copying product with combinations to shop
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In product v2 when using multistore feature "copy to shop" an error is thrown when trying to copy a product with combination to another shop.
Screenshot 2023-01-10 at 16 30 07

Might be related to recent PR https://github.com/PrestaShop/PrestaShop/pull/30584

### Expected behavior

No error

### Steps to reproduce

1. Turn on multistore, create at least 2 shops, enable product v2 page through experimental features and go to product v2 page.
2. Edit any product with combinations
3. If product is already associated for both shops then use "select shop" and unselect shop2.
4. Again use "select shops" and select shop2 again
5. You should see error complaining about `UniqueConstraintViolation`.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | refer to issue #30792
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30792
| Related PRs       |
| How to test?      | refer to issue
| Possible impacts? |

### CODE REVIEW

File: src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php [hunk 1]
```diff
@@ -211,14 +211,23 @@ public function create(ProductId $productId, ShopConstraint $shopConstraint): Im
...
     /**
-     * @param Image $image
-     * @param ShopId[] $shopsToRemoveImageFrom
+     * @param ImageId $imageId
+     * @param ShopId[] $shopIds
      *
      * @return void
      */
-    public function deleteFromShops(Image $image, array $shopsToRemoveImageFrom)
+    public function deleteFromShops(ImageId $imageId, array $shopIds): void
```
Comment (zuk3975) [inline src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php:219]: these changes wasn't required, I just adjusted it a little so it is more usable and similar to whats done in product repository

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 2]
```diff
@@ -235,7 +236,15 @@ private function copyCarriersToShop(Product $sourceProduct, ShopId $targetShopId
     private function copyImageAssociations(ProductId $productId, ShopId $sourceShopId, ShopId $targetShopId): void
     {
         $imagesFromSourceShop = $this->productImageMultiShopRepository->getImages($productId, ShopConstraint::shop($sourceShopId->getValue()));
+        $targetImageIds = array_map(static function (ImageId $imageId): int {
+            return $imageId->getValue();
+        }, $this->productImageMultiShopRepository->getImagesIds($productId, ShopConstraint::shop($targetShopId->getValue())));
+
         foreach ($imagesFromSourceShop as $image) {
+            // skip image if it is already associated with the target shop
+            if (in_array((int) $image->id, $targetImageIds, true)) {
```
Comment (zuk3975) [inline src/Adapter/Product/Update/ProductShopUpdater.php:245]: these changes are also not mandatory, as the root issue was that the images wasn't being deleted from shops when product was deleted, but I think its still nice to have in case for some reason some images are left, so we don't get the sql UniqueConstraint error.

File: src/Adapter/Product/Shop/CommandHandler/DeleteProductFromShopsHandler.php [hunk 3]
```diff
@@ -76,4 +89,27 @@ public function handle(DeleteProductFromShopsCommand $command): void
...
+                    return $imageId->getValue();
+                }, $this->productImageMultiShopRepository->getImagesIds($productId, ShopConstraint::shop($shopId->getValue())))
+            );
+        }
+
+        // then remove each of those images from all the specified shops
+        foreach ($imageIds as $imageId) {
+            $this->productImageMultiShopRepository->deleteFromShops(new ImageId($imageId), $shopIds);
+        }
+    }
```
Comment (jolelievre) [inline src/Adapter/Product/Shop/CommandHandler/DeleteProductFromShopsHandler.php]: I think you should handle the removal in the same loop shop by shop Because in `deleteFromShops` you check the association between the ImageId and the ShopId But here you merge all the imageIds from all the shops, so you could end up with non existing association and some error will trigger

Comment (jolelievre) [reply src/Adapter/Product/Shop/CommandHandler/DeleteProductFromShopsHandler.php]:
```suggestion
        foreach ($shopIds as $shopId) {
            $imageIds = $this->productImageMultiShopRepository->getImagesIds($productId, ShopConstraint::shop($shopId->getValue()));
            foreach ($imageIds as $imageId) {
                $this->productImageMultiShopRepository->deleteFromShops(new ImageId($imageId), [$shopId]);
            }
        }
    }
```

**Review by jolelievre — COMMENTED** [review]
Thanks @zuk3975 

I noticed this bug and planned to fix along with the last Image integration PR, but you were too fast ^^

One thing to fix in the loop I think, and also you should add some behat tests:
- create a product with images
- copy it to a shop2
- remove it from shop2
- copy it again to shop2

Without your fix this should throw an error (make sure it doesn't by commenting `removeImages` in the handler maybe) with the fix all is green ^^

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature [hunk 4]
```diff
@@ -47,7 +47,7 @@ Feature: Add product image from Back Office (BO)
       | large_default  | 800   | 800    |
       | medium_default | 452   | 452    |
       | small_default  | 98    | 98     |
-    And product "product1" should have no images for shop "shop2"
+    And product "product1" should have no images for shops "shop2"
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature:50]: typo fix - the following step expects array in implementation.

File: tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php [hunk 5]
```diff
@@ -329,7 +329,7 @@ public function assertProductHasNoImages(string $productReference): void
     }
 
     /**
-     * @Then product :productReference should have no images for shop :shops
+     * @Then product :productReference should have no images for shops :shops
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php:332]: typo fix - the following step expects array in implementation.

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature (hunk 4 above)
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/add_multishop_image.feature:50]: same as above

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/delete_multishop_image.feature [hunk 6]
```diff
@@ -63,7 +63,7 @@ Feature: Delete product image from Back Office (BO)
     And product "product1" should have following images for shop "shop2":
       | image reference | is cover | legend[en-US] | position | image url                            | thumbnail url                                      |
       | image3          | true    |                | 2        | http://myshop.com/img/p/{image3}.jpg | http://myshop.com/img/p/{image3}-small_default.jpg |
-    Then product "product1" should have no images for shop "shop3"
+    Then product "product1" should have no images for shops "shop3"
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/delete_multishop_image.feature:66]: same as above

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature [hunk 7]
```diff
@@ -57,13 +58,13 @@ Feature: Copy product from shop to shop.
...
     And default shop for product productWithPrices is shop1
     When I update product "productWithPrices" with following values:
-      | price              | 100.99          |
-      | ecotax             | 0               |
-      | tax rules group    | US-AL Rate (4%) |
-      | on_sale            | true            |
-      | wholesale_price    | 70              |
-      | unit_price         | 10              |
-      | unity              | bag of ten      |
+      | price           | 100.99          |
```
Comment (zuk3975) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature:61]: these changes are not related to the PR, its just some style fixes (removes sume unnecessary spaces) that my IDE applied by autoformatting

File: tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php (hunk 5 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php:332]:
```suggestion
     * @Then product :productReference should have no images for shop(s) :shops
```
Actually you can make the s optional so it can be used with one or several references

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature [hunk 8]
```diff
@@ -616,3 +617,25 @@ Feature: Copy product from shop to shop.
...
+      | image reference | is cover | legend[en-US] | legend[fr-FR] | position | image url                            | thumbnail url                                      |
+      | image1          | true     |               |               | 1        | http://myshop.com/img/p/{image1}.jpg | http://myshop.com/img/p/{image1}-small_default.jpg |
+    When I copy product "product1" from shop "shop1" to shop "shop2"
+    Then product "product1" should have following images for shops "shop1,shop2":
+      | image reference | is cover | legend[en-US] | legend[fr-FR] | position | image url                            | thumbnail url                                      |
+      | image1          | true     |               |               | 1        | http://myshop.com/img/p/{image1}.jpg | http://myshop.com/img/p/{image1}-small_default.jpg |
+    When I delete product "product1" from shops "shop2"
+    Then product "product1" should have no images for shops "shop2"
+    And product "product1" is not associated to shop "shop2"
+    And product "product1" should have following images for shops "shop1":
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature:639]: You need to copy it again that's when the bug was present in our case (some rows left in the tables cause unicity exceptions)

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature [hunk 9]
```diff
@@ -616,3 +617,25 @@ Feature: Copy product from shop to shop.
...
+      | image reference | is cover | legend[en-US] | legend[fr-FR] | position | image url                            | thumbnail url                                      |
+      | image1          | true     |               |               | 1        | http://myshop.com/img/p/{image1}.jpg | http://myshop.com/img/p/{image1}-small_default.jpg |
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature:641]:
```suggestion
      | image1          | true     |               |               | 1        | http://myshop.com/img/p/{image1}.jpg | http://myshop.com/img/p/{image1}-small_default.jpg |
    When I copy product "product1" from shop "shop1" to shop "shop2"
    Then product "product1" should have following images for shops "shop1,shop2":
      | image reference | is cover | legend[en-US] | legend[fr-FR] | position | image url                            | thumbnail url                                      |
      | image1          | true     |               |               | 1        | http://myshop.com/img/p/{image1}.jpg | http://myshop.com/img/p/{image1}-small_default.jpg |
```

File: src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php:219]: Isn't it a BC Break ?

File: tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php (hunk 5 above)
Comment (zuk3975) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php:332]: I didn't think its worth complicating the code for such minor wording "improvement" thing, we (including you 😄 ) used this kind of wording in many places already, why it started bothering you only now? 😄

File: src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Product/Image/Repository/ProductImageMultiShopRepository.php:219]: Nope it's all part of experimental code, no backward policy until the page is finished

File: tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php (hunk 5 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php:332]: That's just a suggestion, I actually don't mind ^^ But the `(s)` is already used in several places and it's convenient because it allows using the two forms easily Not blocking though! But since you were modifying the sentence I just suggested this since it was the occasion

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

File: tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php (hunk 5 above)
Comment (zuk3975) [reply tests/Integration/Behaviour/Features/Context/Domain/Product/ProductImageFeatureContext.php:332]: I think it works for both singular and multiple forms now too, so its just a syntax sugar ✌️

**Review by lartist — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @zuk3975 

Thanx for PR ! 

After installing the PR and Following the existing steps in the [issue#30792](https://github.com/PrestaShop/PrestaShop/issues/30792)  , I noticied that the button **Select Shops** is not exist in the header of the page ! 

Capture-d’écran-du-2023-01-20-12-21-28-png-1902×984-

Could you please check and feedback ! 

**PS**  The button exist in a shop without PR ( I already reproduced the Issue) 

Capture-d’écran-du-2023-01-20-12-31-53-png-1687×683-


Thank you !

**Comment by jolelievre** [comment]
Hi @sallemiines 

from what I see in your first screenshot you were not using the product page V2 (the combination list doesn't look like this anymore, and the image preview is not present in the header). The "Select shop" button and feature can only be used on the product page v2, so it's the only page where it should be tested. It seems like you were not always using the correct page so that probably explains your issue (the second screenshot is ok though).

Also, be careful when you enable the multishop mode it automatically disables the product page v2 so to test this correctly you first need to enable multishop, create your additional shops and only after you can enable the product page v2 (there is a dedicated feature flag for multishop only).

**Comment by sallemiines** [comment]
> Hi @sallemiines
> 
> from what I see in your first screenshot you were not using the product page V2 (the combination list doesn't look like this anymore, and the image preview is not present in the header). The "Select shop" button and feature can only be used on the product page v2, so it's the only page where it should be tested. It seems like you were not always using the correct page so that probably explains your issue (the second screenshot is ok though).
> 
> Also, be careful when you enable the multishop mode it automatically disables the product page v2 so to test this correctly you first need to enable multishop, create your additional shops and only after you can enable the product page v2 (there is a dedicated feature flag for multishop only).

@zuk3975 Thanx for the quick feedback ! yes you are right it's my mistake , i forget to enable the PPV2 in my second shop ! 

The PR LGTM QA :heavy_check_mark: 

https://user-images.githubusercontent.com/31663369/213706015-0fa05636-3fb7-407a-a2e6-0a0fe5eee0bc.mp4




Thank you ! :rocket:
