### PR TITLE
Modifying address from order should duplicate it and soft delete former address

### LINKED ISSUE #17978: Editing an address in the order should create a new address
#### Describe the bug

If you change an address (billing or shipping address) in the order, the new address will be updated in all customer orders.

#### Why 

The order page does not dissociate between modifying an erroneous address and entering a new address.

#### Expected behavior

Editing an address in the order should:
- create a new address 
- it only updates the address of the current order

#### Steps to Reproduce

1. Go to BO > orders > orders > View order
2. Click on edit address
3. Change the address and save
4. The address has been edited and changed for both billing and delivery

**Screenshots**

https://drive.google.com/file/d/1Rx7oDD_8YLr0cMDwLDGm9-qw8aTFfN6Y/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When editing an address from the order view page the edited address data was then impacted on every cart and orders This PR includes two fixes:<br/>1- when an address is edited if it is used in an order (as delivery or invoice address) then the modification are saved into a duplicated address row, and the former one is soft deleted (via a database field)<br/>2- a new controller has been added to edit order's addresses, so the duplication process natively occurs though address editing but then the order (and its cart) must be updated with the new address, and the order shipping cost is updated
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17978
| How to test?  | See issue's problems Basically edit an order delivery address, when going back to the order view only the delivery address must have been updated Any other orders that used this address is unchanged In the Customer's addresses list you should not see more addresses, the former one has been soft deleted and replaced by the new one

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18124)

### CODE REVIEW

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php [hunk 1]
```diff
@@ -57,12 +60,32 @@ public function handle(EditCustomerAddressCommand $command): void
                 throw new AddressConstraintException('Address contains invalid field values');
             }
 
-            if (false === $address->update()) {
+            // The address is used by an order so it is not edited directly, instead a copy is created and
+            if ($address->isUsed()) {
+                // Get a copy of current address
+                $old_address = new Address($address->id);
```
Comment (PierreRambaud) [inline src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]:
```suggestion
                $copyAddress = new Address($address->id);
```

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php [hunk 2]
```diff
@@ -57,12 +60,32 @@ public function handle(EditCustomerAddressCommand $command): void
...
+
+                // Reset ID to force recreating a new address
+                $address->id = $address->id_address = null;
```
Comment (PierreRambaud) [inline src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: I don't understand why we must reset the current address id and not the copied one? :thinking:

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php [hunk 3]
```diff
@@ -57,12 +60,32 @@ public function handle(EditCustomerAddressCommand $command): void
...
+
+                // We consider this address as necessarily NOT deleted, in case you were editing a deleted address
+                // from an order then the newly edited address should not be deleted, so that you can select it
+                $address->deleted = 0;
```
Comment (PierreRambaud) [inline src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: This means, if we edit a deleted address, it's automatically undeleted? should be `if ($address->isUsed() && !$address->deleted)` or something similar?

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php [hunk 4]
```diff
@@ -57,12 +60,32 @@ public function handle(EditCustomerAddressCommand $command): void
...
+                if (false === $address->save()) {
+                    throw new CannotAddAddressException(sprintf('Failed to add new address "%s"', $command->getAddress()));
+                }
+                // Soft delete the former address
+                if (false === $old_address->delete()) {
```
Comment (PierreRambaud) [inline src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: delete $address to be consistent and save the copy instead

File: src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+
+        if (null !== $data['id_state']) {
+            $editAddressCommand->setStateId((int) $data['id_state']);
+        }
+
+        if (null !== $data['phone']) {
+            $editAddressCommand->setHomePhone($data['phone']);
+        }
+
+        if (isset($data['phone_mobile']) && null !== $data['phone_mobile']) {
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php]:
```suggestion
        if (isset($data['phone_mobile'])) {
```
Why doing the same check? :sweat_smile:

File: src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php [hunk 6]
```diff
@@ -0,0 +1,133 @@
...
+     * @throws CountryConstraintException
+     * @throws StateConstraintException
+     * @throws InvalidAddressTypeException
+     * @throws OrderException
+     */
+    public function update($orderId, array $data)
+    {
+        $editAddressCommand = new EditOrderAddressCommand($orderId, $data['address_type']);
+
+        if (null !== $data['alias']) {
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php]: why not using isset instead?

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php [hunk 7]
```diff
@@ -401,6 +404,90 @@ public function editAction(int $addressId, Request $request): Response
...
+
+            // Addres form is built based on address id to fill the data related to this address
+            $addressForm = $addressFormBuilder->getFormFor($addressId, $formData);
+            $addressForm->handleRequest($request);
+
+            // Form is handled based on Order ID because that's the order that needs update
+            $result = $addressFormHandler->handleFor($orderId, $addressForm);
+
+            if ($result->isSubmitted() && $result->isValid()) {
+                $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]:
```suggestion
                $this->addFlash('success', $this->trans('Update successful', 'Admin.Notifications.Success'));
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig [hunk 8]
```diff
@@ -110,14 +110,7 @@
...
-                  'realedit': 1,
-                  'updateaddress': 1,
-                  'address_type': 1,
-                  'id_order': orderForViewing.id,
-                  'id_address': orderForViewing.shippingAddress.addressId,
-                  'back': path('admin_orders_view', {'orderId': orderForViewing.id})
-                }) }}"
+                 href="{{ path('admin_order_addresses_edit', {'orderId': orderForViewing.id, 'addressType': 'delivery'}) }}"
               >
                 {{ 'Edit address'|trans({}, 'Admin.Actions') }}
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig]: It might be related to the changes requested by @colinegin and mentioned [here](https://github.com/PrestaShop/PrestaShop/issues/17993), in the **Admin.Actions** domain: _Edit address_ will be clearer if turned into _Edit existing address_ - as well as _Change address_ into _Select another address_.

FYI @marionf, @MatShir

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig [hunk 9]
```diff
@@ -166,14 +159,7 @@
...
-                  'realedit': 1,
-                  'updateaddress': 1,
-                  'address_type': 2,
-                  'id_order': orderForViewing.id,
-                  'id_address': orderForViewing.invoiceAddress.addressId,
-                  'back': path('admin_orders_view', {'orderId': orderForViewing.id})
-                }) }}"
+                 href="{{ path('admin_order_addresses_edit', {'orderId': orderForViewing.id, 'addressType': 'invoice'}) }}"
               >
                 {{ 'Edit address'|trans({}, 'Admin.Actions') }}
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig]: Same here, I guess.

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php (hunk 2 above)
Comment (matthieu-rolland) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: Here the $address object is the new one, it contains all the data of the address we are creating, so its id must be null so that a new address is created. 

$old_address is what you call the "copied one", this one must keep its id, it's the one that will be soft deleted (without the data modifications)

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: Done

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: Exactly `$address` contains the edited data so this is the one that needs to be inserted in the DB, setting null to the id is kind of a trick but it makes the job

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: Yeh I wasn't 100% sure about this one, but here is the use case: let's you have an order with invoice and delivery address with id 4. You edit the delivery address, so the address with id 4 becomes deleted, and a new address is inserted

Now you also want to edit the invoice address which is still the address with id 4 (deleted), you create a new address by editing it, but since this new address is based on a deleted address the new address is also deleted.

I don't think this is what the user expects, a newly edited and created address should not be deleted I guess. And worst case scenario the new address can always be deleted in the list anyway.

What do you think?

Comment (jolelievre) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: Oh and by the way regarding the condition you proposed, it changes nothing as we are already in a block `if ($address->isUsed())` And i we only set `deleted = 0` when `deleted == 0` then it changes nothing
The real question is indeed should we undelete it by default? as explained in the use case above.

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php (hunk 4 above)
Comment (jolelievre) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php]: As explained above `$address` contains the edited data so it makes more sense to save/insert this one Besides `$address->delete()` sets deleted to true and then performs an update. So it would erase the previous data and save the edited data in the deleted row.

But I understand that the code is not really instinctive.. Maybe if we renamed `$address` into `$editedAddress` it would be easier to understand?

File: src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php (hunk 5 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php]: It is a dumb copy/paste from `AddressFormDataHandler` 😛
I think the isset is necessary because in some cases the field is not present, but then the latter part is useless indeed, I'll remove it

File: src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php (hunk 6 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php]: I guess we can replace with isset everywhere indeed

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php (hunk 7 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: Done

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig (hunk 8 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig]: Ok, I changed these two wordings

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig (hunk 9 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig]: Done as well

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php (hunk 7 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: I only changed them in this controller, but there are many other use of this wrong wording in other controllers I don't want to make all the updates in this PR because it's not related to the issue, but should we change all the present wordings in another PR to be consistent everywhere?

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php [hunk 10]
```diff
@@ -48,21 +51,41 @@ final class EditCustomerAddressHandler extends AbstractAddressHandler implements
...
 
-            if (false === $address->validateFields(false)) {
+            if (false === $editedAddress->validateFields(false)) {
                 throw new AddressConstraintException('Address contains invalid field values');
             }
 
-            if (false === $address->update()) {
-                throw new CannotUpdateAddressException(sprintf('Failed to update address "%s"', $address->id));
+            // The address is used by an order so it is not edited directly, instead a copy is created and
+            if ($editedAddress->isUsed()) {
```
Comment (jolelievre) [inline src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php:64]: @PierreRambaud do you think it's clearer with this naming? Also I thought maybe `$backupAddress` instead of `$copyAddress` would be better?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_customer_address_modal.html.twig [hunk 11]
```diff
@@ -50,7 +50,7 @@
           <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
             {{ 'Cancel'|trans({}, 'Admin.Actions') }}
           </button>
-          
+
           <button type="submit" class="btn btn-primary">
             {{ 'Change'|trans({}, 'Admin.Actions') }}
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_customer_address_modal.html.twig]:
```suggestion
            {{ 'Select'|trans({}, 'Admin.Actions') }}
```

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_customer_address_modal.html.twig]: In order to stay consistent. ;-)

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php (hunk 7 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: Absolutely! I think a part of it has already been done in PR #17819, can you check and let me know if all controllers are changed? If not, I'll create an issue to have it all changed. :-)

File: src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php (hunk 10 above)
Comment (PierreRambaud) [reply src/Adapter/Address/CommandHandler/EditCustomerAddressHandler.php:64]: It's not really a backup but a real copy.
But it's clearer now :)

**Review by PierreRambaud — DISMISSED** [review]

File: src/Adapter/Address/CommandHandler/EditOrderAddressHandler.php [hunk 12]
```diff
@@ -0,0 +1,168 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/Address/CommandHandler/EditOrderAddressHandler.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Address/Command/AbstractEditAddressCommand.php [hunk 13]
```diff
@@ -0,0 +1,414 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Address/Command/AbstractEditAddressCommand.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Address/Command/EditOrderAddressCommand.php [hunk 14]
```diff
@@ -0,0 +1,103 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Address/Command/EditOrderAddressCommand.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Address/CommandHandler/EditOrderAddressHandlerInterface.php [hunk 15]
```diff
@@ -0,0 +1,43 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Address/CommandHandler/EditOrderAddressHandlerInterface.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Address/Exception/CannotUpdateOrderAddressException.php [hunk 16]
```diff
@@ -0,0 +1,34 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Address/Exception/CannotUpdateOrderAddressException.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Cart/Exception/CannotUpdateCartException.php [hunk 17]
```diff
@@ -0,0 +1,34 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Cart/Exception/CannotUpdateCartException.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Order/Exception/CannotUpdateOrderException.php [hunk 18]
```diff
@@ -0,0 +1,34 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Order/Exception/CannotUpdateOrderException.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Order/Exception/InvalidAddressTypeException.php [hunk 19]
```diff
@@ -0,0 +1,34 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Order/Exception/InvalidAddressTypeException.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Domain/Order/OrderAddressType.php [hunk 20]
```diff
@@ -0,0 +1,37 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Domain/Order/OrderAddressType.php:27]: Miss `declare(strict_types=1);`

File: src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php [hunk 21]
```diff
@@ -0,0 +1,133 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Form/IdentifiableObject/DataHandler/OrderAddressFormDataHandler.php:27]: Miss `declare(strict_types=1);`

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php [hunk 22]
```diff
@@ -401,6 +404,90 @@ public function editAction(int $addressId, Request $request): Response
...
+            $addressId = null;
+            switch ($addressType) {
+                case 'delivery':
+                    $addressType = OrderAddressType::DELIVERY_ADDRESS_TYPE;
+                    $addressId = $order->id_address_delivery;
+                    break;
+                case 'invoice':
+                    $addressType = OrderAddressType::INVOICE_ADDRESS_TYPE;
+                    $addressId = $order->id_address_invoice;
+                    break;
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php:434]: default ? An exception ?

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php:434]: The exception is already managed in the command class which checks allowed address types

**Comment by jolelievre** [comment]
Thank you @Progi1984 I addressed all your feedbacks

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@jolelievre You have some errors in Behat tests : https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/299023607#L7674

**Comment by jolelievre** [comment]
@Progi1984 thanks it was related to strict typing, it's ok now

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by SD1982** [comment]
This PR correctly fix #17978 . Thanks @jolelievre
