### PR TITLE
Fixed the display of the dropdown 'No voucher was found'

### LINKED ISSUE #27870: [BO - Add new order] the dropdow "No voucher was found" is not well displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Orders > Add new order page > when we search a cart rule that doesn't exist
The dropdown "No voucher was found" is not well displayed
image

### Expected behavior

image

### Steps to reproduce

1. Create a cart rule with a code
2. Go to BO > Orders > Add new order
3. Choose a customer & add a product to the cart
4. In the voucher block search with a cart rule that doesn't exist
5. See error > the drop-down is not well displayed
6. Remove the input & try to search the valid name
7. See error > is not displayed

https://user-images.githubusercontent.com/16067358/157490279-a66ef9bd-dd67-4bc5-a35e-2bae58bda071.mp4

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed the display of the dropdown 'No voucher was found'
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27870
| How to test?      | Cf. #27870

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27889)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/create/cart-rules-renderer.ts [hunk 1]
```diff
@@ -123,7 +123,7 @@ export default class CartRulesRenderer {
     const $template = $(
       $(createOrderMap.cartRulesNotFoundTemplate).html(),
     ).clone();
-    this.$searchResultBox.replaceWith($template);
+    this.$searchResultBox.append($template);
```
Comment (saulaski) [inline admin-dev/themes/new-theme/js/pages/order/create/cart-rules-renderer.ts]: Cloning the template above is useless since jQuery creates a new DOM Element from HTML content.
Wrapping HTML content in jQuery object is useless as well.
Here we can append HTML content directly: https://api.jquery.com/append/#append-content-content
```suggestion
    this.$searchResultBox.append(
        $(createOrderMap.cartRulesNotFoundTemplate).html()
    );
```

**Review by saulaski — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/create/cart-rules-renderer.ts (hunk 1 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/create/cart-rules-renderer.ts]: Fixed (Ping @NeOMakinG who likes in scred :stuck_out_tongue_closed_eyes:)

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Progi1984, 

I tested it, and it works as we expect 

as you can see on this video : 

the voucher is correctly find 
https://user-images.githubusercontent.com/100699445/158165714-93631ca6-c3ee-4cbb-a90a-89e73e8122db.mp4

**Review by saulaski — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @AureRita
