### PR TITLE
Order Product Search: Limit only if the search phrase length is greater than 2 characters and HTTP Code Error become a 400

### LINKED ISSUE #25360: BO - View an order - Search endpoint returns HTTP 500 when
#### Describe the bug

When Search endpoint `/admin-dev/index.php/sell/orders/products/search?search_phrase=&currency_id=YYY&order_id=ZZZ&_token=AAA` is hit with empty GET parameter `search_phrase` it returns an HTTP response whose status is 500, and the response contains error message "Product search phrase must be a not empty string"

This is a trivial issue with no impact for merchant. It just does not look good.

#### Expected behavior

Search endpoint should return something different than 500, this is not a server error. Maybe a 400.

#### Steps to Reproduce

1. Go to Back Office, open an Order to view it
2. Open Chrome developer tools, open Network tab
3. Click 'Add a product'
4. Start typing something in the product field: you can see in the Network tab that a HTTP query is sent to `/admin-dev/index.php/sell/orders/products/search?search_phrase=XXX&currency_id=YYY&order_id=ZZZ&_token=AAA` and you get a HTTP 200 response
5. Clear the search product field: you can see in the Network tab that a HTTP query is sent to `/admin-dev/index.php/sell/orders/products/search?search_phrase=&currency_id=YYY&order_id=ZZZ&_token=AAA` and you get a HTTP 500 response (`search_phrase` GET parameter is empty)
6. You can also simply browse the URL `/admin-dev/index.php/sell/orders/products/search?search_phrase=&currency_id=YYY&order_id=ZZZ&_token=AAA` and see HTTP status 500, and the response contains error message "Product search phrase must be a not empty string"

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Order Product Search: Limit only if the search phrase length is greather than 2 characters and HTTP Code Error become a 400
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25360
| How to test?      | Cf #25360 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25378)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 1]
```diff
@@ -1763,6 +1764,11 @@ public function searchProductsAction(Request $request): JsonResponse
             return $this->json([
                 'products' => $foundProducts,
             ]);
+        } catch (ProductSearchEmptyPhraseException $e) {
+            return $this->json(
+                [$e, 'message' => $this->getErrorMessageForException($e, [])],
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
                [$e, 'message' => $this->getErrorMessageForException($e, $this->getErrorMessages($e))],
```

Even if it's not handled for now it will allow adding a custom message for this exception (I guess it was forgotten in the other catch block

**Review by jolelievre — COMMENTED** [review]
One small comment, the rest is perfect

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: @jolelievre Fixed

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984

File: admin-dev/themes/new-theme/js/pages/order/create/product-manager.js [hunk 2]
```diff
@@ -201,6 +201,7 @@ export default class ProductManager {
    * @private
    */
   _search(searchPhrase) {
+    // Search only if the search phrase length is greather than 2 characters
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/order/create/product-manager.js]:
```suggestion
    // Search only if the search phrase length is greater than 2 characters
```

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js [hunk 3]
```diff
@@ -54,6 +54,11 @@ export default class OrderProductAutocomplete {
   delaySearch(input) {
     clearTimeout(this.searchTimeoutId);
 
+    // Search only if the search phrase length is greather than 2 characters
```
Comment (matks) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js]:
```suggestion
    // Search only if the search phrase length is greater than 2 characters
```

File: admin-dev/themes/new-theme/js/pages/order/create/product-manager.js (hunk 2 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/create/product-manager.js]: Fixed

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js (hunk 3 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js]: Fixed

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

File: tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/OrderControllerTest.php [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+ */
+
+declare(strict_types=1);
+
+namespace Tests\Integration\PrestaShopBundle\Controller\Admin\Sell\Order;
+
+use PrestaShop\PrestaShop\Adapter\Configuration;
+use Symfony\Bundle\FrameworkBundle\Client;
+use Symfony\Bundle\FrameworkBundle\Routing\Router;
+use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
```
Comment (matks) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Sell/Order/OrderControllerTest.php:34]: As discussed in Slack, I am usually against the use of Symfony TestCase. I think Playwright tests are much more reliable, maintainable and useful although more expensive.

I will not block the PR but I voice my worries that these kind of tests will generate a high maintainance burden and let bugs slip because they craft HTTP requests rather than rely on browser-generated HTTP requests and verify the HTTP response rather than verify the behavior of a browser upon receiving the response.

**Comment by sarahdib** [comment]
@Progi1984 

Instead of error 500 when I clear the search field, I get error 400 with this pr is it wanted ?

Capture d’écran 2021-07-21 à 09 11 18

**Comment by Progi1984** [comment]
@sarahdib Affirmative

**Comment by Progi1984** [comment]
Thanks @sarahdib
