### PR TITLE
Use SF cache pool prune after module action

### LINKED ISSUE #20852: BO - Module / Error when trying to install module
#### Describe the bug

An error message is displayed when trying to install a module from the "module catalog" section and when trying to install a modul from the "upload module" button the install process seems to be stuck in a loop

#### Expected behavior

The module installation should work correctly

#### Steps to Reproduce

**Error from module catalog**
1. Go to BO/Improve/Modules/modules catalog
2. Select one of the free module and click on the install button
3. See error => a error message is displayed in the top right corner

**Error from the "upload module" button**
1. Go to BO/Improve/Modules/modules manager
2. Click on the "upload a module" button and select a zip module to upload
3. See error => the module install process is in a loop

**Screenshots**
**Error from the module catalog section**
https://drive.google.com/file/d/1FOPgIvVTvPTVTMLZmdquYzGrAbXBRNql/view?usp=sharing

**Error from the "upload a module" button**
The process is stuck on this step
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Since PR https://github.com/PrestaShop/PrestaShop/pull/20689/, issues arise after module action (install, upgrade, uninstall) because Symfony Cache Clear timeouts. Using `cache:pool:prune` instead of `cache:clear` seems to solve the issue.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20852
| How to test?  | Please see ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20942)

### CODE REVIEW

**Comment by matks** [comment]
@PierreRambaud This PR reverts partially your PR https://github.com/PrestaShop/PrestaShop/pull/20689/ . I am not sure to fully understand why, but I identified what is wrong nonetheless.

**Comment by PierreRambaud** [comment]
> @PierreRambaud This PR reverts partially your PR #20689 . I am not sure to fully understand why, but I identified what is wrong nonetheless.

The previous behaviour was to remove the whole `/var/cache/env` directory with and `rm -rf`, the problem with cache:pool:clear is, not all caches are removed. :thinking: Clearing a production cache is a long process, should we increase the max execution time for this command? Not sure it's the best idea

**Comment by matks** [comment]
> > @PierreRambaud This PR reverts partially your PR #20689 . I am not sure to fully understand why, but I identified what is wrong nonetheless.
> 
> The previous behaviour was to remove the whole `/var/cache/env` directory with and `rm -rf`, the problem with cache:pool:clear is, not all caches are removed. 🤔 Clearing a production cache is a long process, should we increase the max execution time for this command? Not sure it's the best idea

On the other side, clearing the full `/var/cache/env` directory is a bit overkill 😅 . In an ideal - and far away - world we would be able to locate what cache folders need to be cleared.

**Comment by PierreRambaud** [comment]
> > > @PierreRambaud This PR reverts partially your PR #20689 . I am not sure to fully understand why, but I identified what is wrong nonetheless.
> > 
> > 
> > The previous behaviour was to remove the whole `/var/cache/env` directory with and `rm -rf`, the problem with cache:pool:clear is, not all caches are removed. thinking Clearing a production cache is a long process, should we increase the max execution time for this command? Not sure it's the best idea
> 
> On the other side, clearing the full `/var/cache/env` directory is a bit overkill  . In an ideal - and far away - world we would be able to locate what cache folders need to be cleared.

You preach of the choir!

**Comment by matks** [comment]
On the other hand, right now, QA team is unable to install any module on `develop` which effectively prevents them from testing PRs :/

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by ngodefroy** [comment]
Hello @matks 

I installed successfully 2 modules from my catalog.
Then I uploaded a theme> couldnt make it work.
After I tried installing modules from module catalog but As you can see in the video, One of the module couldnt be installed:
https://drive.google.com/file/d/1dWY04i5HWKZ-YFDasP4E7xIUpNC9BaEV/view

Thank. you

**Comment by matks** [comment]
> Hello @matks
> 
> I installed successfully 2 modules from my catalog.
> Then I uploaded a theme> couldnt make it work.
> After I tried installing modules from module catalog but As you can see in the video, One of the module couldnt be installed:
> https://drive.google.com/file/d/1dWY04i5HWKZ-YFDasP4E7xIUpNC9BaEV/view
> 
> Thank. you

@PrestaShop/qa-functional I tried with a copy of theme Classic but found no issues. Could you please tell me what theme I can use to reproduce the buggy behavior ?

**Comment by ngodefroy** [comment]
Hello @matks  I see its waiting for code owner from @PrestaShop/prestashop-maintainers  review or is it ok to be tested ?
=>I had issue with Bold & Oslo for instance

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php [hunk 1]
```diff
@@ -476,6 +472,10 @@ public function moduleAction(Request $request)
                 ]
             );
 
+            // Get accessed module object
+            $moduleAccessed = $moduleRepository->getModule($module);
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:476]: Could you explain why this change is needed?

Comment (atomiix) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:476]: @PierreRambaud because in the install action, [`getModule` is called]((https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Addon/Module/ModuleManager.php#L310)) after the module has been downloaded, but if you call this method before, the data is cached and the next time you call it, it won't take the fact that the module is now on the disk into account, leading to an error.

**Comment by atomiix** [comment]
@ngodefroy from what I recall, you didn't reproduce the error with those 2 themes the last time you tried. Am I wrong?
Anyway, 2 approves are still needed before QA ;)

**Review by Progi1984 — APPROVED** [review]

**Comment by ngodefroy** [comment]
> @ngodefroy from what I recall, you didn't reproduce the error with those 2 themes the last time you tried. Am I wrong?
> Anyway, 2 approves are still needed before QA ;)

@atomix I didnt reproduce errors uploading the two themes under Design>Theme&logo
But when I try to upload it from module catalog page, I still get the following error w bold and oslo:

Capture d’écran 2020-10-08 à 11 25 33

**Comment by atomiix** [comment]
@ngodefroy I'm not sure to understand 🤔 Are you trying to upload a theme in the module upload modal? If so, I guess this error message makes sense?

**Comment by ngodefroy** [comment]
> @ngodefroy I'm not sure to understand 🤔 Are you trying to upload a theme in the module upload modal? If so, I guess this error message makes sense?

@atomiix yes sorry, my mistake 👎

**Comment by matks** [comment]
Hi, I'm closing the PR 😅 because the QA team believes "if there is a PR then it just needs to pass review and then we can QA it" although the reality is rather "we're trying to turn buttons on and off to see if it solves magically the problem"

This PR staying open sends a wrong message "the issue is solved we are now discussing about details" while the true state is "we are searching for a rock in the desert"

@atomiix if you want to open another PR be my guest 😉

**Comment by ngodefroy** [comment]
Hello @matks 

Tested 
uploading a module
Installing module 
uninstall module

Upload a theme
Change theme
Delete theme

=> TEST OK

Thank you

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @matks & @atomiix & @ngodefroy
