### PR TITLE
Remove gifted quantity from product order quantity

### LINKED ISSUE #21531: BO - Order page - Incorrect quantity added to product when it is added to the same order as a gift also
#### Describe the bug

In the BO > Add new Order page > when we have a product added to the order; as a gift ( a voucher applied) and as a product ordered, the quantity added to the same product NOK
 

#### Steps to Reproduce

1. Create a cart rule "free gift demo_12" without code
2. Go to BO > Order page > Add new order
3. Add demo_12 to the cart (free gift weel added) 
4. Click Add to cart again => see the error
image

**Screenshots**

https://drive.google.com/file/d/1x9WOVyDXy4Gs5BO4QYCwkEupB3VNXGGj/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

### LINKED ISSUE #21592: BO - Order page - The gifted product quantity is not updated
#### Describe the bug

In the BO > Order page > Order detail page > we have already a gifted_product in the order.
When we add a Product with an associated gift, The gifted product quantity is not updated

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Create a cart rule 
1.1. no code
1.2. no condition
1.3. Free gift demo_12 
2. Go to BO > Orders > An old order created
3. add demo_12
4. See error: the quantity of the product added = 1 => it should be 2 (the discount is applied)
image

1.7.6.8 => ok
image

#### Additional information

* PrestaShop version: 1770rc1build2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When a product is gifted in the order and we add the same product in a the order, the gifted product was not removed from "quantity of product in the cart". That leads to weird behaviour when increasing the quantity
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21531 & Fixes #21592
| How to test?  | See the issue.<br>Create a cart rule "free gift demo_12" without code<br>Go to BO > Order page > Add new order<br>Add demo_12 to the cart (free gift will be added)<br>Click Add to cart again => The product quantity must be increase by one<br>You can test with the product gifted twice (2 cart rules)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21781)

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]
One question, very uncommon scenario, what if gift product has minimal quantity? 🤔 Not sure if that's something we should be worried about 🤷

**Comment by sowbiba** [comment]
> One question, very uncommon scenario, what if gift product has minimal quantity?  Not sure if that's something we should be worried about

You can only give one unit of a product as a gift (per cart rule)
If you mean the quantity of the product manually added to the cart, if there is a minimal quantity an exception will be thrown : MinimalQuantityException

**EDIT** : That's what I thought. No exception for minimal quantity. I will ask to @PrestaShop/product-team

File: src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php [hunk 1]
```diff
@@ -86,7 +88,9 @@ public function handle(AddProductToCartCommand $command): void
         $cart = $this->getCart($command->getCartId());
         $product = $cart->getProductQuantity($productIdValue, $combinationId, $customizationId);
 
-        $quantity = $command->getQuantity() + (int) $product['quantity'];
+        $cartQuantity = (int) $product['quantity'] - $this->getProductGiftedQuantity($cart, $productIdValue, $combinationId);
```
Comment (jolelievre) [inline src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: Oh for adding a product But what happens if we update the quantity directly (by clicking on the arrow in the cart product list) Isn't there a weird offset due to this gift product as well?

In which case maybe this substraction should be handled in `UpdateProductQuantityInCartHandler` so that it covers more use cases

I'm surprised this was not handled in the legacy class already, does it mean this can happen on the FO as well?

Comment (kpodemski) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: @jolelievre you mean decrease or increase quantity of gift product?

Comment (jolelievre) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: Yes decrease/increase in the list, or even simply update

**Comment by jolelievre** [comment]
@kpodemski @sowbiba I didn't think about this minimalQuantity for a gift product 😅

Indeed for now a gift product is ALWAYS of quantity `1` you can't edit it in the CartRule and it doesn't check for minimalQuantity, it is hardcoded as 1 for now So maybe we should improve this feature but that's not in the scope of this PR or even this version since it would be a new feature ^^

So this should be discussed with @PrestaShop/product-team to see if the feature should be added However regarding the minimalQuantity I don't think it should be bound to it, gifting a product should have independent constraints from selling the said product

**Comment by MatShir** [comment]
IMO, the minimum product to sell is different than the product quantity to give as a gift.
The behavior is not handled by PS.

In FO, if a cart rule has a gift product with a minimum quantity, the cart rule will be only displayed when the cart will have the required quantity.
If product A has min qt of 5 and it is a gift on a cart rule, the cart will apply the cart rule only if the cart is composed at least of 5 Product A to offer one.  To summarize, the cart will have 6 products. It means that the cart rule with a gift becomes a cart rule with a product constraint and a gift which is not the wanted behavior by the merchant.

I agree with @jolelievre, for now, we should handle the behavior for one quantity for the BO

File: src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php (hunk 1 above)
Comment (sowbiba) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: you cannot increase/decrease quantity of the gift itself (you don't have the quantity input), you can only increase/decrease other products.
The bug I detected in the previous comment https://github.com/PrestaShop/PrestaShop/pull/21781#issuecomment-722551891 is that the other products increase/decrease doesn't respect the minimum quantity : No exception thrown

**Comment by jolelievre** [comment]
@sowbiba I looked into what happened in the FO because I was surprised that there was not bug in FO but there is one in BO

I seems the problem comes from `UpdateProductQuantityInCartHandler::findPreviousQuantityInCart` When you have 3 products plus 1 gift, you want to add the product so the new quantity is logically 5, but `findPreviousQuantityInCart` actually returns 3 (not counting the gift) so the diff is `5 - 3` which is why the product quantity is incremented by 2

**Comment by jolelievre** [comment]
This modification was originally made in this PR https://github.com/PrestaShop/PrestaShop/pull/17179 So we need to be careful if we want to modify this

**Comment by jolelievre** [comment]
I think you are going to have to add behat tests to avoid regression for these two issues #17085 (1st item), #18119

And then fix the `UpdateProductQuantityInCartHandler::findPreviousQuantityInCart` it shouldn't decrement the quantity like that and simply use `$cart->getProducts()` like it used to before the PR

But what works for this issue might be a problem for other issues, hence the necessity of adding behat tests before making any changes

**Review by jolelievre — CHANGES_REQUESTED** [review]
As explained in other comments the bug comes from `UpdateProductQuantityInCartHandler::findPreviousQuantityInCart` So we should fix the origin of the bug instead of adding a patch on our own mistake

**Comment by sowbiba** [comment]
@jolelievre Doing the behat tests you asked, I realize that the behaviour of findPreviousQuantityInCart is correct. When you use UpdateProductQuantityInCartHandler, the quantity in the UpdateProductQuantityInCartCommand is the target quantity for the product, without the gifts

If you have 3 items of a product and 1 gift, if you want to increase the number of overall products to 5, you have to give 4 to the command. And then you will have 4 payed items + 1 gift

And when you are adding an item of the product (AddProductToCartHandler), you will count the items of the product already in the cart without the gifted ones, + the quantity of items you want to add and that's what you'll pass to updateProductQtyInCartHandler

**Comment by jolelievre** [comment]
Mmmm, I see but it's a bit weird then because we don't have the same behaviour in BO and in FO 

In FO the gift present is counted in the total number of products, it's just that we have a discount matching the amount of the product, so there's no problem here What messes with the total here is that in the create an order page we separate these two counts But in order view page we don't separate them

So actually only the Create order page that handles a cart uses this, I just checked the 176 and it matches this behaviour to split the rows, but I really don't think it's a good idea It doesn't represent the actual data in DB, it hides the discount value And it is not consistent with the Front behaviour nor the Order view page behaviour

This needs to be discussed with @PrestaShop/product-team but it would be easier and more stable to modify the behaviour of this page, since it's the only one that behaves this way

**Comment by sowbiba** [comment]
@MatShir WDYT ?

**Comment by MatShir** [comment]
Status update: The behavior won't change on this PR or for the 1.7.7 final release but a small refacto will be done to homogenize the code between order view and add. 

An adjustment will be operated on 1.7.7.1 for the uniformization of the behavior.

File: classes/Cart.php [hunk 2]
```diff
@@ -3790,7 +3790,7 @@ public function checkDiscountValidity($obj, $discounts, $order_total, $products,
      *
      * @return array Cart details
      */
-    public function getSummaryDetails($id_lang = null, $refresh = false)
+    public function getSummaryDetails($id_lang = null, $refresh = false, $splitGift = true)
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
    public function getSummaryDetails($id_lang = null, $refresh = false, bool $splitGift = true)
```

File: src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php [hunk 3]
```diff
@@ -26,6 +26,7 @@
 
 namespace PrestaShop\PrestaShop\Adapter\Cart\CommandHandler;
 
+use Cart;
```
Comment (Progi1984) [inline src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]:
```suggestion
```

File: classes/Cart.php (hunk 2 above)
Comment (sowbiba) [reply classes/Cart.php]: since the other properties are not typed. I didn't want to typehint this one. but why not ?

Comment (Progi1984) [reply classes/Cart.php]: In all cases, it's a BC :)

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 4]
```diff
@@ -620,4 +623,32 @@ private function getErrorCode(Exception $e): int
...
+    /**
+     * This method will be removed in the next patch version. We rely on Cart ObjectModel to simplify the code
+     *
+     * @param int $cartId
+     * @param int $productId
+     * @param int|null $combinationId
+     *
+     * @return int
+     */
+    private function getProductGiftedQuantity(int $cartId, int $productId, ?int $combinationId): int
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: Controllers are not supposed to use directly legacy code 😅  (and this function does seem to belong to controller layer, it's a function that could exist at ObjectModel level because it's useful)

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 5]
```diff
@@ -438,12 +438,15 @@ public function editProductQuantityAction(Request $request, int $cartId, int $pr
     {
         try {
             $newQty = $request->request->getInt('newQty');
+            $combinationId = $request->request->getInt('attributeId');
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]:
```suggestion
            $attributeId = $request->request->getInt('attributeId');
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 6]
```diff
@@ -438,12 +438,15 @@ public function editProductQuantityAction(Request $request, int $cartId, int $pr
...
+
+            $giftedQuantity = $this->getProductGiftedQuantity($cartId, $productId, $combinationId);
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]:
```suggestion
            $giftedQuantity = $this->getProductGiftedQuantity($cartId, $productId, $attributeId);
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 7]
```diff
@@ -438,12 +438,15 @@ public function editProductQuantityAction(Request $request, int $cartId, int $pr
...
 
             $this->getCommandBus()->handle(new UpdateProductQuantityInCartCommand(
                 $cartId,
                 $productId,
-                $newQty,
-                $request->request->getInt('attributeId') ?: null,
+                $newQty + $giftedQuantity,
+                $combinationId ?: null,
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]:
```suggestion
                $attributeId ?: null,
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 8]
```diff
@@ -620,4 +623,32 @@ private function getErrorCode(Exception $e): int
...
+     * @param int $productId
+     * @param int|null $combinationId
+     *
+     * @return int
+     */
+    private function getProductGiftedQuantity(int $cartId, int $productId, ?int $combinationId): int
+    {
+        $giftedQuantity = 0;
+        $cart = new \Cart($cartId);
+        $giftCartRules = $cart->getCartRules(\CartRule::FILTER_ACTION_GIFT, false);
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php:646]: Move to `use` section

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 4 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: that's why I added a comment to explain that it's a code that will be removed in next patch. But ... I did a regular and clean command to get a product cartRules. I stashed it because I thought it's too much :D

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 9]
```diff
@@ -620,4 +623,32 @@ private function getErrorCode(Exception $e): int
...
+        if (count($giftCartRules) > 0) {
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: if count($giftCartRules) <= 0 then return 0;

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 8 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php:646]: same explanation as the question by @matks 
It's temporary code, didn't want to pollute the *use* section

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: No combination matches more with the Combination object and represents more what it actually is, it's a variation of a product which is composed of attributes
Attribute is a characteristic of a product/combination (size, color, ...) In most of the recent command/handlers we used Combination rather than Attribute

If anything it's the parameter which should be renamed rather than the variable here

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 4 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: I'm fifty/fifty on this 😅 
need one more opinion

File: classes/Cart.php [hunk 10]
```diff
@@ -3790,7 +3790,7 @@ public function checkDiscountValidity($obj, $discounts, $order_total, $products,
      *
      * @return array Cart details
      */
-    public function getSummaryDetails($id_lang = null, $refresh = false)
+    public function getSummaryDetails($id_lang = null, $refresh = false, bool $splitGift = true)
```
Comment (jolelievre) [inline classes/Cart.php]: Instead of adding this new parameter and create a BC break you could add a new functions and split this one into two private functions

```php
public function getSummaryDetails($id_lang = null, $refresh = false) {
    $summary = $this->getCartSummaryDetails($id_lang, $refresh);

    return $this->alterCartForDisplay($summary);
}

public function getUnalteredSummaryDetails() {
    return $this->getCartSummaryDetails($id_lang, $refresh);
}

private function getCartSummaryDetails($id_lang = null, $refresh = false) {
    // Get summary without special rules
}

private function alterCartForDisplay(array $summary): array {
    // All the loop part on cart rules (including the free shipping simplification)
}
```

Comment (jolelievre) [reply classes/Cart.php]: Besides `$splitGift` should rather be `$alterForDisplay` and also include the modification of shipping fees, so the whole cart gift loop actually (because it also hides shipping amount when a free_shipping cart rule is applied)

File: src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php [hunk 11]
```diff
@@ -241,14 +249,38 @@ private function extractCartRulesFromLegacySummary(Cart $cart, array $legacySumm
...
+    {
+        $cartRules = [];
+
+        foreach ($legacySummary['discounts'] as $discount) {
+            $cartRuleId = (int) $discount['id_cart_rule'];
+            $cartRules[$cartRuleId] = new CartInformation\CartRule(
+                (int) $discount['id_cart_rule'],
+                $discount['name'],
+                $discount['description'],
+                (new Number((string) $discount['value_tax_exc']))->round($currency->precision)
```
Comment (jolelievre) [inline src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php]:
```suggestion
                new Number((string) $discount['value_tax_exc'], $currency->precision)
```

Comment (jolelievre) [reply src/Adapter/Cart/QueryHandler/GetCartInformationHandler.php]: Same in other methods that use the same round method, the constructor actually already handles this

File: classes/Cart.php [hunk 12]
```diff
@@ -3865,7 +3865,7 @@ public function getSummaryDetails($id_lang = null, $refresh = false)
                 $total_shipping_tax_exc = 0;
             }
 
-            if ($cart_rule['gift_product']) {
+            if ($splitGift && $cart_rule['gift_product']) {
```
Comment (jolelievre) [inline classes/Cart.php]: The `if` statement should be above and include the whole `foreach ($cart_rules as &$cart_rule)` loop (and the one right after which removes cart rules)

File: classes/Cart.php [hunk 13]
```diff
@@ -3786,11 +3786,23 @@ public function checkDiscountValidity($obj, $discounts, $order_total, $products,
...
      */
     public function getSummaryDetails($id_lang = null, $refresh = false)
+    {
+        $summary = $this->getUnalteredSummaryDetails($id_lang, $refresh);
+
+        return $this->alterSummaryForDisplay($summary, $refresh);
+    }
+
+    /**
+     * Returns useful raw informations about the cart.
```
Comment (eternoendless) [inline classes/Cart.php]: Information is an uncountable noun = no plural form

```suggestion
     * Returns useful raw information about the cart.
```

File: classes/Cart.php [hunk 14]
```diff
@@ -3786,11 +3786,23 @@ public function checkDiscountValidity($obj, $discounts, $order_total, $products,
...
+     *
+     * @return array Cart details
+     */
+    public function getUnalteredSummaryDetails($id_lang = null, $refresh = false): array
```
Comment (eternoendless) [inline classes/Cart.php]:
```suggestion
    public function getRawSummaryDetails(?int $id_lang = null, bool $refresh = false): array
```

File: classes/Cart.php (hunk 13 above)
Comment (eternoendless) [reply classes/Cart.php]: Maybe describe the difference a little more in comments?

File: classes/Cart.php (hunk 14 above)
Comment (eternoendless) [reply classes/Cart.php]: Since we're at it, can I suggest making `id_lang` not optional?
```suggestion
    public function getRawSummaryDetails(int $id_lang, $refresh = false): array
```

File: classes/Cart.php [hunk 15]
```diff
@@ -3786,11 +3786,23 @@ public function checkDiscountValidity($obj, $discounts, $order_total, $products,
...
 
     /**
-     * Return useful information about the cart.
+     * Return useful information about the cart for display purpose.
      *
      * @return array Cart details
      */
     public function getSummaryDetails($id_lang = null, $refresh = false)
+    {
+        $summary = $this->getUnalteredSummaryDetails($id_lang, $refresh);
```
Comment (PierreRambaud) [inline classes/Cart.php]:
```suggestion
        $summary = $this->getUnalteredSummaryDetails($id_lang, (bool) $refresh);
```
You can't trust untyped parameter

File: classes/Cart.php [hunk 16]
```diff
@@ -3786,11 +3786,23 @@ public function checkDiscountValidity($obj, $discounts, $order_total, $products,
...
+
+        return $this->alterSummaryForDisplay($summary, $refresh);
```
Comment (PierreRambaud) [inline classes/Cart.php]:
```suggestion
        return $this->alterSummaryForDisplay($summary, (bool) $refresh);
```

File: classes/Cart.php [hunk 17]
```diff
@@ -5113,4 +5050,104 @@ public function getTaxCountry(): Country
 
         return new Country($taxAddress->id_country);
     }
+
+    /**
+     * Alter raw cart details to adapt to display use case.
+     *
+     * @return array
+     */
+    private function alterSummaryForDisplay(array $summary, $refresh = false): array
```
Comment (PierreRambaud) [inline classes/Cart.php]:
```suggestion
    private function alterSummaryForDisplay(array $summary, bool $refresh = false): array
```

File: classes/Cart.php (hunk 14 above)
Comment (sowbiba) [reply classes/Cart.php]: We have some use cases where id_lang is not given to `getSummaryDetails`. In these cases the id_lang is retrieved from the context
Do you suggest we give directly the lang in the context as parameter to the call to `getSummaryDetails` or to get it in this method before calling `getRawSummaryDetails`?

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 18]
```diff
@@ -56,4 +66,44 @@ public function getCartId(): CartId
...
+    {
+        return $this->separateGiftProducts;
+    }
+
+    /**
+     * @param bool $separateGiftProducts
+     *
+     * @return GetCartForOrderCreation
+     */
+    public function setSeparateGiftProducts(bool $separateGiftProducts): GetCartForOrderCreation
```
Comment (eternoendless) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]: This MUST be described in comments

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 19]
```diff
@@ -56,4 +66,44 @@ public function getCartId(): CartId
...
+    public function separateGiftCartRules(): bool
+    {
+        return $this->separateGiftCartRules;
+    }
+
+    /**
+     * @param bool $separateGiftCartRules
+     *
+     * @return GetCartForOrderCreation
+     */
```
Comment (eternoendless) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]: This MUST be described in comments

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 20]
```diff
@@ -110,7 +110,11 @@ public function viewAction(Request $request, $cartId)
     public function getInfoAction(int $cartId)
     {
         try {
-            $cartInfo = $this->getQueryBus()->handle(new GetCartInformation($cartId));
+            $cartInfo = $this->getQueryBus()->handle(
+                (new GetCartForOrderCreation($cartId))
+                    ->setSeparateGiftProducts(false)
+                    ->setSeparateGiftCartRules(false)
```
Comment (eternoendless) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: Don't you mean to use `true` here? Otherwise you don't need to call the setters with default values.

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 21]
```diff
@@ -502,7 +509,11 @@ public function deleteProductAction(Request $request, int $cartId): JsonResponse
      */
     private function getCartInfo(int $cartId): CartInformation
     {
-        return $this->getQueryBus()->handle(new GetCartInformation($cartId));
+        return $this->getQueryBus()->handle(
+            (new GetCartForOrderCreation($cartId))
+                ->setSeparateGiftProducts(false)
+                ->setSeparateGiftCartRules(false)
```
Comment (eternoendless) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: Don't you mean to use `true` here? Otherwise you don't need to call the setters with default values.

File: tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_standard_product.feature [hunk 22]
```diff
@@ -26,7 +26,7 @@ Feature: Add product in cart
     And  I create an empty cart "dummy_cart" for customer "testCustomer"
     And there is a product in the catalog named "product1" with a price of 19.812 and 1000 items in stock
     And the product "product1" minimal quantity is 10
-    When I add 5 products "product1" to the cart "dummy_cart"
+    When I update quantity of product "product1" in the cart "dummy_cart" to 5
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_standard_product.feature]: Why "update quantity"? It makes no sense in natural language. It would if the products were already in the cart.

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php (hunk 20 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php]: Yes. I was testing the front in case the values are FALSE and forgot to revert it

File: tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_standard_product.feature (hunk 22 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Scenario/Cart/Adding/Product/add_standard_product.feature]: Yes. Wrong replacement. There was many cases where it was an update and `add` was used. But not this one ;)

File: classes/Cart.php [hunk 23]
```diff
@@ -3918,17 +3866,17 @@ public function getSummaryDetails($id_lang = null, $refresh = false)
             'invoice_state' => State::getNameById($invoice->id_state),
             'formattedAddresses' => $formatted_addresses,
             'products' => array_values($products),
-            'gift_products' => $gift_products,
-            'discounts' => array_values($cart_rules),
+            'gift_products' => [],
```
Comment (jolelievre) [inline classes/Cart.php]: I don't think we need this field for the raw return, it should only be added in `getSummaryDetails`

File: classes/Cart.php [hunk 24]
```diff
@@ -5113,4 +5061,107 @@ public function getTaxCountry(): Country
...
+     * @param bool $refresh
+     *
+     * @return array
+     */
+    private function alterSummaryForDisplay(array $summary, bool $refresh = false): array
+    {
+        $context = Context::getContext();
+        $currency = new Currency($this->id_currency);
+
+        $products = $this->getProducts($refresh);
```
Comment (jolelievre) [inline classes/Cart.php]:
```suggestion
        $products = $summary['products'];
```
No need to make two queries (especially when `refresh` is true)

File: classes/Cart.php (hunk 14 above)
Comment (eternoendless) [reply classes/Cart.php]: You can keep the fallback in getSummaryDetails to allow a clean interface (i.e. make the parameter required required) for getRawSummaryDetails :)

File: src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php [hunk 25]
```diff
@@ -107,15 +107,15 @@ public function __construct(
...
+     * @param GetCartForOrderCreation $query
      *
      * @return CartInformation
      *
      * @throws CartNotFoundException
      * @throws LocalizationException
      * @throws PrestaShopException
      */
-    public function handle(GetCartInformation $query): CartInformation
+    public function handle(GetCartForOrderCreation $query): CartInformation
```
Comment (jolelievre) [inline src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]:
```suggestion
    public function handle(GetCartForOrderCreation $query): CartForOrderCreation
```

I think the query result class should be renamed as well for consistency

File: src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php [hunk 26]
```diff
@@ -127,15 +127,22 @@ public function handle(GetCartInformation $query): CartInformation
             ->setLanguage($language)
             ->setCustomer(new Customer($cart->id_customer));
 
-        $legacySummary = $cart->getSummaryDetails(null, true);
         $addresses = $this->getAddresses($cart);
 
+        if ($query->separateGiftProducts()) {
```
Comment (jolelievre) [inline src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]: If I recall we mentioned two different options the one for gift splitting and the one for free shipping

However I only see one option here, and in the legacy code it's the same you have either:
- `getRawSummaryDetails` : plain cart summary without modifications
- `getSummaryDetails` legacy function which split gifts AND hides the free shipping

I'm fine with only supporting one option for both feature, although it should be validated by @eternoendless, but then we should find a more appropriate name Following the method from legacy we could introduce `$query->getRawSummary()` which default value would then be `true` (and temporarily used with false here)

Comment (jolelievre) [reply src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]: Oh and from what I see in `extractShippingFromLegacySummary` it seems some modifications are also performed in this handler

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 27]
```diff
@@ -32,13 +32,23 @@
...
 
+    /**
+     * @var bool
+     */
+    private $separateGiftProducts = false;
+
+    /**
+     * @var bool
+     */
+    private $separateGiftCartRules = false;
```
Comment (jolelievre) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]: I think you're mixing things up, separating gift products and separating gift cart rules is the same thing, it's the same feature so no need for two options for the same split
The two options we mentioned were:
- separate gift
- hide/modify free shipping

So at least `separateGiftCartRules` is redundant and should be removed, about free shipping as I said in an earlier comment we could handle it with `separateGift` via a single option but then it should be renamed

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php [hunk 28]
```diff
@@ -438,12 +442,15 @@ public function editProductQuantityAction(Request $request, int $cartId, int $pr
     {
         try {
             $newQty = $request->request->getInt('newQty');
+            $attributeId = $request->request->getInt('attributeId');
+
+            $giftedQuantity = $this->getProductGiftedQuantity($cartId, $productId, $attributeId);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController.php:446]: It can't hurt to add a comment here too

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 29]
```diff
@@ -1167,7 +1167,7 @@ public function duplicateOrderCartAction(int $orderId)
         $cartId = $this->getCommandBus()->handle(new DuplicateOrderCartCommand($orderId))->getValue();
 
         return $this->json(
-            $this->getQueryBus()->handle(new GetCartInformation($cartId))
+            $this->getQueryBus()->handle(new GetCartForOrderCreation($cartId))
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Missing options set to true here

File: tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php [hunk 30]
```diff
@@ -727,6 +757,53 @@ public function assertReductionValueOfCartCartRule(
...
+     * @Then cart :cartReference should contain :quantity products
+     *
+     * @param string $cartReference
+     * @param int $quantity
+     */
+    public function assertCartNumberOfProducts(string $cartReference, int $quantity)
+    {
+        $cartInfo = $this->getCartInformationByReference($cartReference);
+
+        $cartProductsQuantity = \count($cartInfo->getProducts());
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php:768]: I'm surprised `count` needs to be backslashed

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php [hunk 31]
```diff
@@ -85,9 +85,9 @@ public function thereIsDuplicatedCartForCart(string $duplicatedCartReference, st
         $cartId = SharedStorage::getStorage()->get($cartReference);
 
         /** @var CartInformation $cartInformation */
-        $cartInformation = $this->getQueryBus()->handle(new GetCartInformation($cartId));
+        $cartInformation = $this->getQueryBus()->handle(new GetCartForOrderCreation($cartId));
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php]: Maybe it's overkill but I guess we should test the result in both mode (with split gifts, and without split gifts)

File: tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/add_cartrule.feature [hunk 32]
```diff
@@ -113,7 +113,7 @@ Feature: Add cart rule in cart
   Scenario: Add cart rule which provides gift product and free shipping
     Given I create an empty cart "dummy_cart_1" for customer "testCustomer"
     And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart_1"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart_1"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart_1" to 2
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/add_cartrule.feature]: Be careful you replaced every single former use of `I add 2 products` with `I update quantity of product`

So I know that it was incorrect before since it always used the update command to add new product, but since we have both commands available now we should use them appropriately So when it's an empty cart or when it doesn't contain the added product we should use `I add 2 products`  This will allow us to validate its behaviour as well

**Review by jolelievre — CHANGES_REQUESTED** [review]
The two options in the command are not what I remember was discussed

File: classes/Cart.php (hunk 24 above)
Comment (eternoendless) [inline classes/Cart.php]: When calling `getSummaryDetails()`, `$this->getProducts()` will be called twice, and potentially, it will also be refreshed twice if `$refresh` is true.

File: tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php (hunk 30 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php:768]: ow no need. I used to do this for PHP native functions. I will remember the explanation. It's about preprocessing

File: classes/Cart.php (hunk 24 above)
Comment (eternoendless) [reply classes/Cart.php]: Maybe the best solution is to have two complete, independent implementations for getSummaryDetails() and getRawSummaryDetails(). It could be helpful to note exactly what's modified in `getSummaryDetails`.

File: tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/add_cartrule.feature (hunk 32 above)
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Adding/CartRule/add_cartrule.feature]: Same comment, should be "add 2 products" because it's an empty cart

File: tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_cart_rule_from_cart.feature [hunk 33]
```diff
@@ -12,7 +12,7 @@ Feature: Delete cart rule from cart in Back Office (BO)
 
   @bo-delete-cart-rule
   Scenario: Delete cart rule with gift product
-    Given I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    Given I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_cart_rule_from_cart.feature]: This is an add as well

File: tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_cart_rule_from_cart.feature [hunk 34]
```diff
@@ -22,7 +22,7 @@ Feature: Delete cart rule from cart in Back Office (BO)
   @bo-delete-cart-rule
   Scenario: Delete cart rule with gift product when same product as gift already exists in cart
     Given I create an empty cart "dummy_cart_2" for customer "testCustomer"
-    And I add 3 products "Mountain fox notebook" to the cart "dummy_cart_2"
+    And I update quantity of product "Mountain fox notebook" in the cart "dummy_cart_2" to 3
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_cart_rule_from_cart.feature]: Add 3 products

File: tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_product_from_cart.feature [hunk 35]
```diff
@@ -12,15 +12,15 @@ Feature: Delete product from cart in Back Office (BO)
   @bo-delete-product
   Scenario: Delete standard product from cart
     Given I create an empty cart "dummy_cart" for customer "testCustomer"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Cart/Deleting/delete_product_from_cart.feature]: Add here as well

File: tests/Integration/Behaviour/Features/Scenario/Order/duplicate_products.feature [hunk 36]
```diff
@@ -16,7 +16,7 @@ Feature: Order from Back Office (BO)
     And customer "testCustomer" has address in "US" country
     And I create an empty cart "dummy_cart" for customer "testCustomer"
     And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/duplicate_products.feature]: Add 2 products

File: tests/Integration/Behaviour/Features/Scenario/Order/order_add_payment.feature [hunk 37]
```diff
@@ -38,7 +38,7 @@ Feature: Add payment to Order from Back Office (BO)
     And customer "testCustomer" has address in "US" country
     And I create an empty cart "dummy_cart" for customer "testCustomer"
     And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_add_payment.feature]: Add 2 products

File: tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature [hunk 38]
```diff
@@ -17,8 +17,8 @@ Feature: Cancel Order Product from Back Office (BO)
     And customer "testCustomer" has address in "US" country
     And I create an empty cart "dummy_cart" for customer "testCustomer"
     And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"
-    And I add 5 products "Mug The best is yet to come" to the cart "dummy_cart"
-    And I add 3 products "Mug Today is a good day" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 5
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature]: Add 5 products

File: tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature [hunk 39]
```diff
@@ -17,8 +17,8 @@ Feature: Cancel Order Product from Back Office (BO)
...
+    And I update quantity of product "Mug Today is a good day" in the cart "dummy_cart" to 3
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_cancel_product.feature]: This is an add as well

File: tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature [hunk 40]
```diff
@@ -17,7 +17,7 @@ Feature: Order from Back Office (BO)
     And customer "testCustomer" has address in "US" country
     And I create an empty cart "dummy_cart" for customer "testCustomer"
     And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_cart_rules.feature]: Add 2 products

File: tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature [hunk 41]
```diff
@@ -31,7 +31,7 @@ Feature: Multiple currencies for Order in Back Office (BO)
     And I create an empty cart "dummy_cart" for customer "testCustomer"
     And I update the cart "dummy_cart" currency to "currency2"
     And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature]: Add 2 products

File: tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature [hunk 42]
```diff
@@ -25,7 +25,7 @@ Feature: Order from Back Office (BO)
     And customer "testCustomer" has address in "FR" country
     And I create an empty cart "dummy_cart" for customer "testCustomer"
     And I select "FR" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"
-    And I add 2 products "Mug The best is yet to come" to the cart "dummy_cart"
+    And I update quantity of product "Mug The best is yet to come" in the cart "dummy_cart" to 2
```
Comment (eternoendless) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature]: Add 2 products

Comment (eternoendless) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_french_tax.feature]: Please check out the other scenarios as well and revert to the correct wording

File: tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php (hunk 30 above)
Comment (eternoendless) [reply tests/Integration/Behaviour/Features/Context/Domain/CartFeatureContext.php:768]: I don't think it is needed

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 43]
```diff
@@ -56,4 +61,34 @@ public function getCartId(): CartId
...
+    /**
+     * When hideDiscounts is set to TRUE,
+     * Payed products lines are separated to gift products
+     * Price of the gifted products are removed from the overall discounts
+     * Shipping is set to 0 if there is a free_shipping cart rule
+     *
+     * Otherwise,
+     * We will have one line per product and the gifted quantity will be included to the product quantity in the cart.
+     * The shipping will have his original value and a cart_rule with the shipping value will be added
+     * and the gift products price will be included to the discount
```
Comment (eternoendless) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]:
```suggestion
     * When hideDiscounts is set to TRUE,
     * Gifted products are in a separate line from other products which are charged for
     * The price of any gifted products is not included in the overall discounts
     * Shipping is set to 0 if there is a free_shipping cart rule
     *
     * Otherwise,
     * There is one line per product type and the gifted quantity will be included to the product quantity in the cart.
     * Shipping has its original price, and if it's free, the shipping value will be added as a discount
     * Any gifted products' price will be included as a discount
```

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 44]
```diff
@@ -56,4 +61,34 @@ public function getCartId(): CartId
...
+     *
+     * @param bool $hideDiscounts
+     *
+     * @return GetCartForOrderCreation
+     */
+    public function setHideDiscounts(bool $hideDiscounts): GetCartForOrderCreation
```
Comment (eternoendless) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]: You can use `self`
```suggestion
    public function setHideDiscounts(bool $hideDiscounts): self
```

File: src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php [hunk 45]
```diff
@@ -40,26 +40,26 @@
 use PrestaShop\PrestaShop\Adapter\Cart\AbstractCartHandler;
 use PrestaShop\PrestaShop\Adapter\ContextStateManager;
 use PrestaShop\PrestaShop\Core\Domain\Cart\Exception\CartNotFoundException;
-use PrestaShop\PrestaShop\Core\Domain\Cart\Query\GetCartInformation;
-use PrestaShop\PrestaShop\Core\Domain\Cart\QueryHandler\GetCartInformationHandlerInterface;
+use PrestaShop\PrestaShop\Core\Domain\Cart\Query\GetCartForOrderCreation;
+use PrestaShop\PrestaShop\Core\Domain\Cart\QueryHandler\GetCartForOrderCreationHandlerInterface;
 use PrestaShop\PrestaShop\Core\Domain\Cart\QueryResult\CartDeliveryOption;
```
Comment (jolelievre) [inline src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]:
```suggestion
use PrestaShop\PrestaShop\Core\Domain\Cart\QueryResult\CartForOrderCreation\CartDeliveryOption;
```
This one should be moved in the sub namespace as well, it's the only one that is not

File: src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php [hunk 46]
```diff
@@ -201,41 +208,44 @@ private function buildCartAddress(int $addressId, Cart $cart): CartAddress
      * @param Cart $cart
      * @param array $legacySummary
      * @param Currency $currency
+     * @param bool $separateGiftCartRules
      *
-     * @return CartInformation\CartRule[]
+     * @return CartForOrderCreation\CartRule[]
      */
-    private function extractCartRulesFromLegacySummary(Cart $cart, array $legacySummary, Currency $currency): array
+    private function extractCartRulesFromLegacySummary(Cart $cart, array $legacySummary, Currency $currency, bool $separateGiftCartRules = false): array
```
Comment (jolelievre) [inline src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]:
```suggestion
    private function extractCartRulesFromLegacySummary(Cart $cart, array $legacySummary, Currency $currency, bool $hideDiscounts = false): array
```

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 47]
```diff
@@ -56,4 +61,34 @@ public function getCartId(): CartId
...
+     */
+    public function hideDiscounts(): bool
+    {
+        return $this->hideDiscounts;
+    }
+
+    /**
+     * When hideDiscounts is set to TRUE,
+     * Payed products lines are separated to gift products
+     * Price of the gifted products are removed from the overall discounts
```
Comment (jolelievre) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]:
```suggestion
     * Price of the gifted products are removed from the overall discounts, total products and cart total
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php (hunk 31 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php]: Reminder perform two checks here:
- one with `GetCartForOrderCreation::hideDiscounts = false`
- one with `GetCartForOrderCreation::hideDiscounts = true`

File: src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php [hunk 48]
```diff
@@ -278,6 +290,23 @@ private function extractProductsFromLegacySummary(Cart $cart, array $legacySumma
...
+     * @param Cart $cart
+     * @param array $legacySummary
+     * @param Currency $currency
+     *
+     * @return CartProduct[]
+     */
+    private function extractProductsFromLegacySummary(Cart $cart, array $legacySummary, Currency $currency): array
+    {
+        $products = [];
+        foreach ($legacySummary['products'] as &$product) {
```
Comment (eternoendless) [inline src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]: No need to use references here
```suggestion
        foreach ($legacySummary['products'] as $product) {
```

File: src/Core/Domain/Cart/Query/GetCartForOrderCreation.php [hunk 49]
```diff
@@ -56,4 +61,34 @@ public function getCartId(): CartId
...
+    /**
+     * When hideDiscounts is set to TRUE,
+     * Gifted products are in a separate line from other products which are charged for
+     * The price of any gifted products is not included in the overall discounts, total products and cart total
+     * Shipping is set to 0 if there is a free_shipping cart rule
+     *
+     * Otherwise,
+     * There is one line per product type and the gifted quantity will be included to the product quantity in the cart.
+     * Shipping has its original price, and if it's free, the shipping value will be added as a discount
+     * Any gifted products' price will be included as a discount
```
Comment (eternoendless) [inline src/Core/Domain/Cart/Query/GetCartForOrderCreation.php]: Sorry 😁 
```suggestion
     * When hideDiscounts is set to TRUE,
     * Gift products are in a separate line from other products which are charged for
     * The price of any gift products is not included in the overall discounts, total products and cart total
     * Shipping is set to 0 if there is a free_shipping cart rule
     *
     * Otherwise,
     * There is one line per product type, any gift products will be included in the quantity of charged products, but the price of gift products will appear as a discount
     * Shipping has its original price, and if it's free, the shipping value will be added as a discount
```

**Review by eternoendless — APPROVED** [review]
LGTM

**Review by jolelievre — APPROVED** [review]
Nice work @sowbiba

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1HIvYhJ6jEb9EL0iad1ZBqdas7kkc8SpB/view?usp=sharing
Big thanks to @Robin-Fischer-PS and @SD1982 :heart: 


Thank you!
