### PR TITLE
Get quantity_wanted for product only when it is needed

### LINKED ISSUE #21477: Wrong availability message on cart
#### Describe the bug

If you want to display product availability in the cart, and show availability_message, it returns the wrong text. Like it always has the in-stock product, it doesn't show the message for available_later text. (#18225)

If the stock is 2 and quantity in cart is 1 or 2, it displays an "in stock" label instead "Last items in stock".
If the stock is 2 and quantity in cart is 3, it displays an "in stock" label instead "Label when out of stock".

#### Expected behavior

In cart show product availability when **out of stock** or **last items in stock** with the allowed order option.

0. add these lines in `templates/checkout/_partials/cart-detailed-product-line.tpl`
```php
   {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
```
1. Create a product with quantity =2, Allow orders
image
2. In the FO, Add the product to the cart and Go to the cart page
We have different availability label
2.1 Quantity product =2, quantity in the cart =1
2.1.1 Product details page
image
2.1.2 Cart page
image
2.2 Quantity product =2, quantity in the cart =2
2.2.1 Product details page
image
2.2.2 Cart page
image

------------------------------------------------------------------------------------------------
Add product with 2 quantity, select Allow orders.
Set Label when out of stock.
Add
```
{block name='product_availability'}
  <span id="product-availability">
    {if $product.show_availability && $product.availability_message}
      {if $product.availability == 'available'}
        <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
      {elseif $product.availability == 'last_remaining_items'}
        <i class="material-icons product-last-items">&#xE002;</i>
      {else}
        <i class="material-icons product-unavailable">&#xE14B;</i>
      {/if}
      {$product.availability_message}
    {/if}
  </span>
{/block}
```
in `templates/checkout/_partials/cart-detailed-product-line.tpl`

#### Additional information

PrestaShop version: 1.7.6, 1.7.7, develop

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Detailed explanation in linked Issue
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21477.
| How to test?      | Detailed explanation in linked Issue
| Possible impacts? | n/a
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24798)

### CODE REVIEW

File: src/Adapter/Presenter/Product/ProductLazyArray.php [hunk 1]
```diff
@@ -876,7 +876,10 @@ public function addQuantityInformation(
         $show_price = $this->shouldShowPrice($settings, $product);
         $show_availability = $show_price && $settings->stock_management_enabled;
         $this->product['show_availability'] = $show_availability;
-        $product['quantity_wanted'] = $this->getQuantityWanted();
+
+        if (empty($product['quantity_wanted'])) {
```
Comment (PierreRambaud) [inline src/Adapter/Presenter/Product/ProductLazyArray.php]:
```suggestion
        if (!isset($product['quantity_wanted'])) {
```
Otherwise if it's already 0 it will call the method for nothing, no?

Comment (kpodemski) [reply src/Adapter/Presenter/Product/ProductLazyArray.php]: Is there any scenario where someone wants to pass quantity_wanted as 0? :) I don't think of any to be honest

Comment (PierreRambaud) [reply src/Adapter/Presenter/Product/ProductLazyArray.php]: It's a ProductPresenter, maybe it's in order to display products, and for optimization you can directly set the quantity_wanted at 0 to prevent this call.

Comment (kpodemski) [reply src/Adapter/Presenter/Product/ProductLazyArray.php]: @PierreRambaud  let's use `isset`, just to make sure 💪

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

I make a fresh install of this PR.
I cleared cached from PrestaShop & Browser.
But I still have the same issue with PR.
I attached a screen record
https://www.awesomescreenshot.com/video/4149422?key=dd81c6958c482056bd8c66f3100d2780

Thanks to check and feedback.

**Comment by kpodemski** [comment]
Hi @khouloudbelguith 

You're right, I've tested it, fixed, and noticed one important thing:

- sometimes we'll see identical information in both, shopping cart and product page, but **it's not always a case, and this is ok**

Why?

1. Product A: quantity 2
2. Add 2 units to the cart
3. Information on the product page: Out of stock, information in the shopping cart: Last items in-stock

why do I think it's ok?

On the product page we need to check for:

2 (from cart) + 1 (minimum quantity allowed for adding to cart) = 3

Shopping cart:
2 units added

So it makes a lot of sense if at some point information on the shopping cart and product page is different.

**Review by atomiix — DISMISSED** [review]

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 2]
```diff
@@ -693,6 +693,7 @@ protected function getSettings(): ProductPresentationSettings
             $this->settings->stock_management_enabled = Configuration::get('PS_STOCK_MANAGEMENT');
             $this->settings->showPrices = Configuration::showPrices();
             $this->settings->showLabelOOSListingPages = (bool) Configuration::get('PS_SHOW_LABEL_OOS_LISTING_PAGES');
+            $this->settings->lastRemainingItems = Configuration::get('PS_LAST_QTIES');
```
Comment (Progi1984) [inline src/Adapter/Presenter/Cart/CartPresenter.php]: Could you push Configuration to the constructor, please ?

Comment (atomiix) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: Isn't it out of scope of this PR?

Comment (Progi1984) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: As it adds a new line, it should be added following coding standards, so with dependy injection.

Comment (PierreRambaud) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: It's not possible as the CartPresenter is used in standalone.
We can't add dependency injection in this one.

**Review by PierreRambaud — DISMISSED** [review]

File: src/Adapter/Presenter/Cart/CartPresenter.php (hunk 2 above)
Comment (Progi1984) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: @PierreRambaud But ModulePresenter or ProductPresenter are not working as standalone

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

I have an issue following these steps:
1. Fresh install and edit the template `templates/checkout/_partials/cart-detailed-product-line.tpl`
```php
   {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
```
2. Go to BO > Shop Parameters > Product Settings page > Set `Label of in-stock products` and `Label of out-of-stock products with allowed backorders` and save 
image

3. Go to FO > Any product page of the demo product 
image
2. Add the demo product to the cart with quantity =1 or =2
3. In the Shopping cart page, the alert displayed is NOK 
image
4. Increase the quantity to 3 => it will be ok 
image

Thank you!

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-core-developers 

for reviewers: it seems that I've fixed a little bug inside a `ProductLazyArray`, there was a condition to get a real quantity of the product, but later this quantity wasn't used 🙄

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — COMMENTED** [review]
Could you add integration tests in `tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php`, please ?

File: src/Adapter/Presenter/Cart/CartPresenter.php (hunk 2 above)
Comment (matks) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: Agreed with @PierreRambaud and @atomiix

1. It would make no sense to use a `$configuration` instance for this line while the 7 above rely on the singleton. I prefer an homogenous function that rely on legacy way rather than a function that uses 90% legacy way and 10% modern way.

2. `CartPresenter` is built inside `CartController` using `$presenter = new CartPresenter();` . It's not a service retrieved from a service container. I think this is what @PierreRambaud says when referring to "it's used as standalone". So if you start injecting dependencies in the CartController you must modify how it's built. ModulePresenter is different as it's used in the Back-office, not Front-office, where services are mainly used.

Relying on dependency injection for CartPresenter could be interesting, but in another PR, where you would have to solve the question "how do I inject my dependencies": with service container? with a factory, like ProductPresenterFactory? these 2 questions are far from the scope of this PR

**Comment by matks** [comment]
> Could you add integration tests in `tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php`, please ?

That would be indeed a great improvement to the software 👍

**Review by matks — DISMISSED** [review]
Approving the PR content, but as mentioned by @Progi1984 a test would help make sure computations are now good and stay good in the future

**Comment by kpodemski** [comment]
I'll work on the tests 👍

**Comment by kpodemski** [comment]
@Progi1984 @matks tests have been added

**Review by matks — DISMISSED** [review]

File: tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php [hunk 3]
```diff
@@ -92,6 +92,11 @@ class ProductLazyArrayTest extends TestCase
         'out_of_stock' => OutOfStockType::OUT_OF_STOCK_DEFAULT,
     ];
 
+    const PRODUCT_AVAILABLE_NOW = 'This product is available now';
+    const PRODUCT_AVAILABLE_LATER = 'This product is available on backorder';
+    const PRODUCT_NOT_AVAILABLE = 'This product is not available for order';
+    const PRODUCT_ATTRIBUTE_NOT_AVAILABLE = 'Product available with different options';
```
Comment (Progi1984) [inline tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php]:
```suggestion
    private const PRODUCT_AVAILABLE_NOW = 'This product is available now';
    private const PRODUCT_AVAILABLE_LATER = 'This product is available on backorder';
    private const PRODUCT_NOT_AVAILABLE = 'This product is not available for order';
    private const PRODUCT_ATTRIBUTE_NOT_AVAILABLE = 'Product available with different options';
```

**Review by Progi1984 — DISMISSED** [review]
@kpodemski Thank you for your contribution. I approved but I have brought a small fix on scope of constant.

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

I have an issue in the FO > Product details page and quick view pop up.

Steps to reproduce the issue
1. Create a product with quantity = 4 + Deny order + "label in stock" 
image
2. Preview this product
3. In the FO > Product details page
4. Increase the quantity to 5 
5. See error => The availability message is NOK 
image

"Product available with different options" => this product is simple we should have `Out-of-Stock` (In the BO > Shop Parameters > Product Settings)
image

I have the same issue in the FO > Quick view pop up

I attached a screen record
https://watch.screencastify.com/v/PD3sGOXpKmqKtjHxNTmK

Thanks!

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks!
Sorry, but the last issue occurs again,
I checked the commits 
image
Steps to reproduce the behavior
1. Go to BO > Shop Parameters > Product Settings > Set the fields `Label of in-stock products` & `Label of out-of-stock products with allowed backorders`  
image
2. Go to BO > Catalog > Products > Create a product with one combination
3. Set the quantity to 5 
image
4. Go to FO > Product details
5. Increase the quantity to `6`
6. See error: the product availability message displayed is `Product available with different options` 
image


I have a different issue following these steps:
Steps to reproduce the behavior
1. Go to BO > Shop Parameters > Product Settings > Set the fields `Label of in-stock products` & `Label of out-of-stock products with allowed backorders`  
image
2. Go to BO > Catalog > Products > Create a simple product with quantity =4 
image
3. Go to FO > Product details > Increase the quantity o 5
4. The product availability message displayed is `There are not enough products in stock`
image

In the BO > Shop Parameters > Product settings, we have `Label of out-of-stock products with denied backorders = Out-of-Stock`

So it should be displayed `Out-of-Stock`

Thanks!

**Review by matks — DISMISSED** [review]

File: src/Adapter/Presenter/Product/ProductLazyArray.php [hunk 4]
```diff
@@ -917,22 +921,22 @@ public function addQuantityInformation(
                     : ($config[$language->id] ?? null);
                 $this->product['availability_date'] = $product['available_date'];
                 $this->product['availability'] = 'available';
-            } elseif ($product['quantity_wanted'] > 0 && $product['quantity'] > 0) {
+            } elseif ($product['cache_default_attribute'] && !empty($product['quantity_all_versions']) && ($product['quantity_all_versions'] - $product['quantity']) > 0) {
```
Comment (jolelievre) [inline src/Adapter/Presenter/Product/ProductLazyArray.php]: I wonder about the last condition `($product['quantity_all_versions'] - $product['quantity']) > 0`
If I get it right it checks the quantity of all remaining combinations, if some alternative combinations are present it displays the `Product available with different options` message

But shouldn't it use the `$product['quantity_wanted']` in some way? Again if understand correctly, `$product['quantity_wanted']` is supposed to contain the number of products in the cart (so the quantity he the customer is trying to purchase). So we don't need it because it is the quantity of the selected combination and so should be ignored when checking the quantity for others?


Maybe all is good, and I mostly understood the principle, I just want to be sure. I would suggest using some intermediate variables so that the logic is easier to understand here. Like adding on L909

```php
$remainingQuantityOfAlternativeCombinations = 0;
if ($product['cache_default_attribute'] && !empty($product['quantity_all_versions'])) {
    $remainingQuantityOfAlternativeCombinations = $product['quantity_all_versions'] - $product['quantity'];
}
```

This way the condition here becomes:
`elseif ($remainingQuantityOfAlternativeCombinations > 0)`

which makes the code much easier to understand. I do realize this represents an additional early computation that is useless when `$availableQuantity >= 0` But since the data is already present and there is no request to get it I think the delta time of processing is negligible. If we really don't want this extra early computing, it could also be done in a function `private function hasAlternativeCombinationAvailable(array $product): bool`

File: src/Adapter/Presenter/Product/ProductLazyArray.php [hunk 5]
```diff
@@ -917,22 +921,22 @@ public function addQuantityInformation(
...
+                    'Product available with different options',
                     [],
-                    'Shop.Notifications.Error'
+                    'Shop.Theme.Catalog'
                 );
+                $this->product['availability_date'] = $product['available_date'];
                 $this->product['availability'] = 'unavailable';
-                $this->product['availability_date'] = null;
-            } elseif (!empty($product['quantity_all_versions']) && $product['quantity_all_versions'] > 0) {
+            } elseif ($product['quantity_wanted'] > $availableQuantity && $product['quantity'] > 0) {
```
Comment (jolelievre) [inline src/Adapter/Presenter/Product/ProductLazyArray.php]: Mmm, I wonder if this check could not be simplified?

```php
$availableQuantity = $product['quantity'] - $product['quantity_wanted'];
$product['quantity_wanted'] = $availableQuantity - $product['quantity'];

=>
$product['quantity_wanted'] > $availableQuantity
<=>
$availableQuantity - $product['quantity'] > $availableQuantity
<=>
- $product['quantity'] > 0
```

So except for the case when `$availableQuantity = $product['stock_quantity'] - $product['quantity_wanted'];` this first condition seems to be equivalent to the second one. Which kind of makes sense if you consider the first `if ($availableQuantity >= 0)` then it would become equivalent (in a single if) to:

`if ($availableQuantity < 0 && $product['quantity'] > 0)`
=> The product has some quantity left but you try to order too much

**Review by jolelievre — COMMENTED** [review]
Thank you @kpodemski 

I made a few comments, I don't doubt that your modification works, especially since you added uni tests (good call by the way!) But I just made suggestions because the code is hard to understand (and to review as well). So I was thinking of ways to make it more human-readable. The advantage is that since you added some unit tests you can easily check if any modifications breaks the behaviour.

Maybe there is one case missing in the tests when `$prodoct['stock_quantity']` is not available, so we rely on `$product['quantity']` instead

File: src/Adapter/Presenter/Product/ProductLazyArray.php (hunk 4 above)
Comment (kpodemski) [reply src/Adapter/Presenter/Product/ProductLazyArray.php]: That's a good idea.

To be honest, I hate this part of the code, and at some point, I wanted to delete it all and replace it, but it will be easier now with the integration tests 👍 

For the `$product['quantity']` that's a tricky part. Look what the `Product::getQuantity` does, it takes into account value from the cart 🤯 Actually I'll double-check it just to be 100% sure but IMO everything is on point here.

**Comment by kpodemski** [comment]
Thanks, @jolelievre - I improved the codebase a bit, as you suggested. Tests are green.

**Review by Progi1984 — DISMISSED** [review]
I love your tests. Thank you.

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

I have an issue following these steps:
1. Create a product with combinations
2. Edit the first combination => change quantity to 1
3. Availability preferences = `Use default behavior (Deny orders)` 
image
4. In the BO > Shop Parameters > Product Settings page: Label of out-of-stock products with denied backorders = `out-of-stock` 
5. Go TO fo > and preview the last product created
6. change to second/ third combinations => Product availability message = `out-of-stock` => NOK , it should be ` Product available with different options` 
image

This case happens only if we have quantity_of_all_combinations = 1, if quantity_of_all_combinations > = 2 => ok
https://watch.screencastify.com/v/SAe3tZzcSCrfXuUAxAMF

I tried with develop_without_PR
https://watch.screencastify.com/v/iB6Ov8thtwy3CipfKGbi

Thanks!

File: src/Adapter/Presenter/Cart/CartPresenter.php (hunk 2 above)
Comment (PierreRambaud) [inline src/Adapter/Presenter/Cart/CartPresenter.php]:
```suggestion
            $this->settings->lastRemainingItems = (int) Configuration::get('PS_LAST_QTIES');
```
wdyt?

File: tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php [hunk 6]
```diff
@@ -159,6 +165,208 @@ public function testConstructor(): void
...
+    ): void {
+        $language = $this->mockLanguage;
+
+        $this->mockProductPresentationSettings
+            ->method('shouldShowPrice')
+            ->willReturn(true);
+
+        $this->mockConfiguration
+            ->method('get')
+            ->willReturnCallback(function (string $key) use ($language) {
```
Comment (Progi1984) [inline tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php:186]:
```suggestion
            ->willReturnCallback(function (string $key) use (Language $language) {
```

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

It is ok :heavy_check_mark: 
https://watch.screencastify.com/v/zg4KaWWeNtxWQ7xdHnCT

Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @khouloudbelguith
