### PR TITLE
Increase maximum country state name length from 32 to 80 characters

### LINKED ISSUE #27156: BO - Unable to import 'United State' at localization.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When import 'United State' at localization -> getting error 
"The length of property State->name is currently 36 chars. It must be between 0 and 32 chars."

screenshot-smritidwivedi com-2021 12 31-15_43_07

### Expected behavior

State should be import successfully.

### Steps to reproduce

1. Go to International
2. Go to Localization
3. Import State 'United State' -> getting error. 

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.0, 1.7.8.2

### PHP version(s) where the bug happened

_7.3_

### If your bug is related to a module, specify its name and its version

_NA_

### PR DESCRIPTION
**Pull request by rickygzz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixes a bug when importing localization packs, and a State name is greater than 32 characters (e.g. US pack trying to import "United States Minor Outlying Islands"). Alternatively, it allows to set up state names up to 80 characters long.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27156
| How to test?      | Go to BO / Improve / International / Localization / Localization pack you want to import.<br>Select United States.<br>Check States.<br>Click Import.
| Possible impacts? | None that I know of.

image

The database table `ps_stat`e already considers `name` to be up to 64 characters, but `State.php` defines this field as a 32 character size.

Updated for consistency and to avoid errors as the one in #27156 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27162)

### CODE REVIEW

File: classes/State.php [hunk 1]
```diff
@@ -54,7 +54,7 @@ class StateCore extends ObjectModel
             'id_country' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true],
             'id_zone' => ['type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'required' => true],
             'iso_code' => ['type' => self::TYPE_STRING, 'validate' => 'isStateIsoCode', 'required' => true, 'size' => 7],
-            'name' => ['type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'required' => true, 'size' => 32],
+            'name' => ['type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'required' => true, 'size' => 64],
```
Comment (eternoendless) [inline classes/State.php]:
```suggestion
            'name' => ['type' => self::TYPE_STRING, 'validate' => 'isGenericName', 'required' => true, 'size' => 255],
```
I don't see any reason to set it lower than 255

**Comment by eternoendless** [comment]
I'd rebase this into 1.7.8.x, wdyt @PrestaShop/prestashop-core-developers ?

Also, the field size will have to be updated here:
- https://github.com/PrestaShop/autoupgrade/tree/dev/upgrade/sql
- https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/install-dev/data/db_structure.sql#L2052

File: classes/State.php (hunk 1 above)
Comment (rickygzz) [reply classes/State.php]: If so, we should modify the ps_state table structure (modify the .sql file somewhere inside install folder), and I think it may cause conflicts with the current 1.7.x installations

As right now, it is set to 64 chars in the table structure which is large enough (gotta find a state name larger than that)

**Review by matthieu-rolland — DISMISSED** [review]
lgtm

File: classes/State.php (hunk 1 above)
Comment (rickygzz) [reply classes/State.php]: Using an existing States database from all around the world, brings `Southern Nations, Nationalities, and Peoples' Region` from Ethiopia with 52 characters as the longest state name in English language. Finding a state name using 64 characters or more may be possible in other languages, but for convenience in every day use, I believe we will always find an abbreviation shorter than 64 chars.

> The Southern Nations, Nationalities, and Peoples' Region (often abbreviated as SNNPR; Amharic: የደቡብ ብሔር ብሔረሰቦችና ሕዝቦች ክልል, romanized: Yädäbub Bḥer Bḥeräsäbočna Hzboč Kllə) [Wikipedia](https://en.wikipedia.org/wiki/Southern_Nations,_Nationalities,_and_Peoples%27_Region)
>> 6 chars abbreviated, 25 chars in Amharic and 36 chars romanized

image

So bumping it to 255 characters seems a little bit too excessive, will put an additional stress on disk ops and will be a waste of resources on limited or shared hosts, [see discussion in StackExchange](https://dba.stackexchange.com/questions/76469/mysql-varchar-length-and-performance). Also 255 chars will be excessive to show as an option in a form list.

But wdyt?

Comment (matks) [reply classes/State.php]: Initially I was thinking about homogeneity. Most "medium sized text" fields are usually stored as varchar 255. Having one field that does not fit this rule makes it an exception and any exception make the design a little harder to learn/maintainer for new users.

But looking at prestashop database schema I see a lot of different varchar sizes :p so 64 seems OK to me.

**Review by sowbiba — DISMISSED** [review]
Change looks legit. Maybe consider to put it in 1.7.8.x as @eternoendless suggested

**Review by PierreRambaud — DISMISSED** [review]
As @eternoendless said, this PR is not finished, the db_structure needs to be updated, and also, it should target the 1.7.8.x branch :wink:

**Comment by rickygzz** [comment]
I rebased to 1.7.8.x branch, all integration checks passed. I suggest to only update State.php to 64 chars (no need to update db_structure nor upgrade/sql since the field name is already 64 chars). But wdyt @eternoendless @PierreRambaud @sowbiba @matthieu-rolland ?

image

If it is decided to go longer than 64 chars, I guess the maximum will have to be 191 chars since it is a utf8mb4 field (not 255 chars), and I will gladly update the db_structure and upgrade/sql.

### Why I suggest not to update it to 255 chars (or 191 chars since it is utf8mb4)?

As stated in the above resolved conversation

- Longest English state name is e.g. `Southern Nations, Nationalities, and Peoples' Region` (52 chars)
- For everyday use, people will always use a shorter name (or less formal one).
  - e.g. `SNNP` for state name above [see Wikipedia](https://en.wikipedia.org/wiki/Southern_Nations,_Nationalities,_and_Peoples%27_Region)
  - I believe we will always find an abbreviation shorter than 64 chars in any other language. The Southern Nations, Nationalities, and Peoples' Region (often abbreviated as SNNPR; Amharic: የደቡብ ብሔር ብሔረሰቦችና ሕዝቦች ክልል, romanized: Yädäbub Bḥer Bḥeräsäbočna Hzboč Kllə) (6 chars abbreviated, 25 chars in Amharic and 36 chars romanized)
- A standard line is between 60 and 80 chars. More than that seems excessive
  - It will be a waste of resources on limited or shared hosts.
  - A form list with the state name will hardly show more characters.

**Comment by eternoendless** [comment]
> It will be a waste of resources on limited or shared hosts

This is a common misconception. As [described in the MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings), Varchars require as many bytes as the content they hold + 1 or 2 bytes, depending if the content is under or over 256 bytes. 

**There is no reason to limit a varchar field to anything less than 255**, unless you have a business use case that requires this restriction (eg an EAN13 is by definition 13-char long) or [in this specific case with indexes and InnoDB](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-conversion.html):

> InnoDB has a maximum index length of 767 bytes for tables that use COMPACT or REDUNDANT row format, so for utf8mb3 or utf8mb4 columns, you can index a maximum of 255 or 191 characters, respectively. If you currently have utf8mb3 columns with indexes longer than 191 characters, you must index a smaller number of characters.

Artificially limiting the size of a Varchars, as we see in this issue, tends to produce problems in the long run, and provides zero benefits in return.

**Comment by rickygzz** [comment]
I agree @eternoendless to SAVE an utfmb4 VARCHAR on disk it requires ( number of chars * up to 4 bytes per chars ) + 2 bytes. Index are limited to 767 bytes, so there you have the magic number 191 chars. Db will optimize saved disk space according to string length.

But resources problem I refer occurs every time you QUERY that VARCHAR field. It is my understanding that SQL algorithms reserves the maximum field length FOR EVERY ROW no matter the specific string length for a given row. And, for longer saved strings it will involve more disk ops. For 191 chars, it may be an additional 508 bytes per field, for 100 rows it may be around additional 50kb.

Performance wise it may seem to be few milliseconds and kb. But on shared hosts PS already runs awfully slow, even with cached settings on. Now consider the site have hundred visits at a time and the shared hosts receives million visits at a time... everything starts to add up.

191 chars is around 3 lines of standard text. Imagine writing such an address state on a postal card or a shipping sticker. Show a 191 chars in a form list option, browser will limit to show few first chars.

Think about email or pdf invoice templates... 3 lines for state names? soon we will have to limit the number of chars to show per state name.

So for me, 64 chars covers the strange cases where some official state names exceeds the average state length (around 8-12 chars?).

The 2 or 3 times we surpassed the current 32 char limit for an official state name, @eternoendless have found shorter names abbreviations to adjust to such limit. And on everyday use people tend to use shorter names instead of the official larger state names.

**Comment by eternoendless** [comment]
> But resources problem I refer occurs every time you QUERY that VARCHAR field. It is my understanding that SQL algorithms reserves the maximum field length FOR EVERY ROW no matter the specific string length for a given row. And, for longer saved strings it will involve more disk ops. For 191 chars, it may be an additional 508 bytes per field, for 100 rows it may be around additional 50kb.

Interesting insight. However, according to [this StackExchange answer](https://dba.stackexchange.com/a/142823), it seems that this happens only in older versions of MySQL, when the MEMORY table is too big to fit into ram.

From my point of view, self-imposing a convoluted restriction for the sake of a theoretical bottleneck sounds pretty much like the definition of premature optimization. Especially for a table that is unlikely to grow beyond a few hundred records. 

Remember that this data is not hardcoded, but can be modified from the back office. 64 characters might also not be enough for all alphabets. I have to agree though that in this case, 191 is probably too long for practical display reasons. We can settle on 80 as a safer upper limit.

**Comment by rickygzz** [comment]
@eternoendless  fair enough.

I updated commit to 80 chars.

I retargeted to develop because I was thinking it should target version 8.0... but then I re-read the history of this PR and realized Pierre have already told me to target this commit to 1.7.8.x. I guess I still don´t understand when to target to develop and when to 1.7.8.x.

Anyways, it is pointing to 1.7.8.x now.

So, depending on the target, I guess PR https://github.com/PrestaShop/autoupgrade/pull/455 should modify `8.0.0.sql` file OR `1.7.8.4.sql`.

Whatever you tell me, I will do, should be a quick fix.


Please let me know what needs to be done, cheers!

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
All good, thanks

You need to add the changes to 1.7.8.4.sql

**Review by atomiix — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @rickygzz,

I checked the import of the united states => OK (I edited the us.xml file to add this state `United States Minor Outlying Islands`)
I checked the database table `Prefix_state`  => OK
image
But I have an issue following these steps:
1. Go to BO > International > Locations > States Tab
2. Add/Edit a state
3. Check the state name => you cannot add a state more than 32 characters
image

I attached a screen record

https://user-images.githubusercontent.com/16067358/156571123-20945893-7839-45b7-8cb8-4cccb4b645fb.mp4

Thanks!

**Comment by kpodemski** [comment]
Hello @rickygzz 

You have to edit `maxlength` inside `controllers/admin/AdminStatesController.php`

**Comment by rickygzz** [comment]
Thanks @kpodemski , changes were updated as requested by you and @khouloudbelguith 

I rebased to the latest. All checks/tests passed.

I apologize for the delay,

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @rickygzz 

>I apologize for the delay,

Oh, please, don't :) Thank you for your contribution. We really appreciate it.

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @rickygzz,

It is ok :heavy_check_mark: 
**BO**
image
**Database**
image

https://user-images.githubusercontent.com/16067358/162251983-a81f02e8-69fd-4f66-87e4-d043f59db5f7.mp4

I tried to install 
English lanaguage + France country => OK
Anglish language + United states => OK

Thanks!

**Comment by Progi1984** [comment]
Thanks @rickygzz & @khouloudbelguith
