### PR TITLE
Let Symfony handle kernel reboot

### LINKED ISSUE #26924: Cache folders are duplicated
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Few last versions of prestashop has been creating both `prod` and `pro_` folders in _var/cache/_. It seems also `dev` and `de_` are being created. What is that all about?

### Expected behavior

It used to be just `prod` and `dev` folders in _var/cache/_

### Steps to reproduce

1. Move around several pages of backoffice and frontoffice
2. Check _var/cache/_

### PrestaShop version(s) where the bug happened

1.7.7.x, 1.7.8.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Since #21429 has been merged, when the cache gets cleared, a new folder in `var/cache/` is created where the kernel warms up but is never used then. The command `cache:clear` can be used with the option `--no-optional-warmers` that will only reboot the kernel without warming optional cache as `SymfonyCacheClearer` was mean to do.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26924
| How to test?      | Try to install/uninstall `ps_facebook`, no `de_` or `pro_` folder should be present in the `/var/cache/` folder.
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27035)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @atomiix 

Indeed this one works since we clear on the shutdown of the process We'll need to find a way to hot reboot the kernel properly though, later, to handle module's updates so that their services are usable during install

**Comment by atomiix** [comment]
Thanks @sarahdib

File: src/Adapter/Cache/Clearer/SymfonyCacheClearer.php [hunk 1]
```diff
@@ -70,18 +70,13 @@ public function clear()
             // Clear cache
             $input = new ArrayInput([
                 'command' => 'cache:clear',
-                '--no-warmup' => true,
+                '--no-optional-warmers' => true,
```
Comment (mickaelandrieu) [inline src/Adapter/Cache/Clearer/SymfonyCacheClearer.php:73]: This will ignore this specific warmer : https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Cache/CacheWarmer.php

Is it an issue ?
