### PR TITLE
Remove advanced stock management remains

### LINKED ISSUE #33859: Missing AdminWarehouses controller
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After migrating to Prestashop8, the warehouse management seems to be missing. This also happens in a clean installation of Prestashop. 

When searching for "Warehouses" in the search bar, I do get the option "Warehouses" but when I click it I get the error
"The controller AdminWarehouses is missing or invalid."

Screenshot 2023-09-06 at 12 56 53 PM

### Expected behavior

I expect the warehouse functionality to be working

### Steps to reproduce

1. Go to the backoffice
2. search for "Warehouse"
3. click the feature "Warehouses"
4. observe error 

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.22

### If your bug is related to a module, specify its name and its version

AdminWarehouses

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Completely removes code handling deleted functionality of "advanced stock management".
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Do full QA testing. Did a check myself - FO order, BO product edit, BO stock edit, BO order refund, auto tests - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/5530321433.
| Fixed ticket?     | Fixes #33859
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/659
| Sponsor company   |

### Description
- Advanced stock management functionality has been partially removed and deprecated for a whole lifetime of 1.7, but not completely removed.
- This PR removes all the logic from the code along with everything related - supply orders, warehouses, old stock management etc.
- All deprecated things removed right away, the rest was deprecated (object model classes and few methods) and will be removed in v10.
- Unless somebody had manually change a configuration value in the database, it won't have any effect. All methods will return the same data.
- I did not change any used method signature, except changing one required parameter to an optional one.

### BC breaks
- ProductShipping constructor does not use prestashop.adapter.data_provider.warehouse anymore
- AbstractDeleteSupplierHandler does not use prestashop.adapter.supplier.supplier_order_validator anymore

### Deprecated public methods (mostly gutted out, but will return the same data)
- Pack::usesAdvancedStockManagement - returns false
- Pack::allUsesAdvancedStockManagement - returns false
- Product::usesAdvancedStockManagement - returns false
- Product::useAdvancedStockManagement - does not do anything
- Product::setAdvancedStockManagement - does not do anything
- Product::getRealQuantity
- StockManager::isAsmGloballyActivated - returns false
- StockInterface::isAsmGloballyActivated
- Cart::getPackageIdWarehouse - returns 0
- Order::getWarehouseList - returns array with zero
- AdminImportController::supplyOrdersImport - returns 0
- AdminImportController::supplyOrdersDetailsImport - returns 0
- StockAvailable::synchronize - returns true
- Warehouse::resetStockAvailable - returns true

### Deprecated classes to be completely removed in v10
- SupplierOrderValidator
- SupplyOrder
- SupplyOrderDetail
- SupplyOrderHistory
- SupplyorderReceiptHistory
- SupplyOrderState
- Warehouse
- WarehouseProductLocation
- Stock
- Stockmanager
- StockManagerFactory
- StockManagerInterface
- StockManagerModule
- StockMvt
- StockMvtReason
- StockMvtWS

### Deprecated services
- prestashop.adapter.supplier.supplier_order_validator

### Deprecated attributes
- Address::id_warehouse
- OrderDetail::id_warehouse
- Product::advanced_stock_management
- Other ASM attributes were deprecated since 1.7.8

### Removed public methods
- AdminProductWrapper::processDependsOnStock - class to be removed completely in v9
- Product::addStockMvt - deprecated since 1.5
- Product::getStockMvts - deprecated since 1.5
- Product::updateQuantityProductWithAttributeQuantity - deprecated since 1.5

### Removed configuration values
- PS_ADVANCED_STOCK_MANAGEMENT

### Removed routes
- admin_warehouse_refresh_product_warehouse_combination_form - legacy route

### Removed files
- WarehouseDataProvider - deprecated since 8.1
- CannotDeleteWarehouseManagerException
- WarehouseController - deprecated since 8.1
- ProductWarehouseCombination - deprecated since 8.1

### Removed services
- prestashop.adapter.data_provider.warehouse - deprecated

### CODE REVIEW

File: classes/Pack.php [hunk 1]
```diff
@@ -555,22 +550,17 @@ public static function usesAdvancedStockManagement($id_product)
...
-        $products = Pack::getItems($id_product, Configuration::get('PS_LANG_DEFAULT'));
-        foreach ($products as $product) {
-            // if one product uses the advanced stock management
-            if ($product->advanced_stock_management == 0) {
-                return false;
-            }
-        }
-        // not used
-        return true;
+        return false;
```
Comment (matks) [inline classes/Pack.php:563]: This method is confusing 😄

File: classes/Product.php [hunk 2]
```diff
@@ -6720,81 +6640,6 @@ public static function checkAccessStatic($id_product, $id_customer)
...
-     *
-     * @param int $quantity
-     * @param int $id_reason StockMvtReason identifier - useless
-     * @param int|null $id_product_attribute Attribute identifier
-     * @param int|null $id_order Order identifier - DEPRECATED
-     * @param int|null $id_employee Employee identifier - DEPRECATED
-     *
-     * @return bool
-     */
-    public function addStockMvt($quantity, $id_reason, $id_product_attribute = null, $id_order = null, $id_employee = null)
```
Comment (matks) [inline classes/Product.php:6740]: Careful: I know it's deprecated but (unfortunately) it does not mean it's not used anymore... by the core 😞

Comment (matks) [reply classes/Product.php:6740]: I searched and found no usage

File: classes/stock/StockAvailable.php [hunk 3]
```diff
@@ -146,193 +138,17 @@ public static function getStockAvailableIdByProductId($id_product, $id_product_a
      * For a given id_product, synchronizes StockAvailable::quantity with Stock::usable_quantity.
      *
      * @param int $id_product
-     */
-    public static function synchronize($id_product, $order_id_shop = null)
```
Comment (matks) [inline classes/stock/StockAvailable.php:150]: Why did you deprecate other functions but removed this one?

File: classes/stock/StockAvailable.php [hunk 4]
```diff
@@ -146,193 +138,17 @@ public static function getStockAvailableIdByProductId($id_product, $id_product_a
...
-    /**
-     * For a given id_product, sets if stock available depends on stock.
      *
-     * @param int $id_product
-     * @param bool $depends_on_stock Optional : true by default
-     * @param int $id_shop Optional : gets context by default
+     * @deprecated Since 9.0 and will be removed in 10.0
      */
-    public static function setProductDependsOnStock($id_product, $depends_on_stock = true, $id_shop = null, $id_product_attribute = 0)
+    public static function synchronize($id_product, $order_id_shop = null)
```
Comment (matks) [inline classes/stock/StockAvailable.php:144]: Aaaah you did not remove it, it's git which is confused

**Review by matks — DISMISSED** [review]
Looks globally OK

As discussed together on Slack it SHOULD be OK:
- All the modified LIVE code was inside conditions that were never met
- No change of signature of any LIVE function
- Removal of some calls to this dead code

... but it's touching so many files we need to be careful of unexpected side effects ... and simply human error 😄 (you might have modified 1 line not related to ASM by mistake and I might have missed it)

**Comment by matthieu-rolland** [comment]
auto tests: https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/5509263213

File: classes/Product.php [hunk 5]
```diff
@@ -7719,28 +7564,14 @@ public function updateWs($null_values = false)
      *
      * @param int $id_product Product identifier
      * @param int $id_product_attribute Attribute identifier
-     * @param int $id_warehouse Warehouse identifier
+     * @param int $id_warehouse Warehouse identifier - not used anymore
      * @param int|null $id_shop Shop identifier
      *
      * @return int real_quantity
      */
     public static function getRealQuantity($id_product, $id_product_attribute = 0, $id_warehouse = 0, $id_shop = null)
```
Comment (matthieu-rolland) [inline classes/Product.php:7574]: shouldn't we deprecate this method( and trigger a deprecation error)?

or do we consider that this data should still be reachable through object model ?

**Review by matthieu-rolland — COMMENTED** [review]
one small feedback, lgtm otherwise 👍

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/Product.php (hunk 5 above)
Comment (Hlavtox) [reply classes/Product.php:7574]: Well, although not called in the core, the remaining part is a legit call, so I let it live. But we can maybe sometime do a pass and decide what unused methods to remove?

**Comment by Hlavtox** [comment]
@matthieu-rolland @matks @kpodemski Could you approve guys? I fixed a tiny issue with wrong IDs of movement reasons.

New tests run to confirm. (should report only API and translation test error)
https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/5530321433

File: classes/Cart.php
Comment (jolelievre) [inline classes/Cart.php:1]: The modification seems to be equivalent but it's hard to tell exactly considering the number of modifications and the "complexity" of the code So I think for this PR it would be critical to have a good QA to check if there are no regressions, especially regarding the carrier listing/proposal which is quite complex

File: classes/Product.php (hunk 5 above)
Comment (jolelievre) [reply classes/Product.php:7574]: Since it's not used any more I'd vote to deprecated it and remove it in v10

File: classes/Product.php [hunk 6]
```diff
@@ -298,7 +297,7 @@ class ProductCore extends ObjectModel
      *
      * @var bool|null
      */
-    public $depends_on_stock;
+    public $depends_on_stock = false;
```
Comment (jolelievre) [inline classes/Product.php:300]: All good for the other modification for me, but I think you can go one step further and remove this field along with `advanced_stock_management` since they have been deprecated since 1.7.8

We could also use the opportunity to remove these columns from the database

File: classes/order/Order.php [hunk 7]
```diff
@@ -2249,25 +2241,17 @@ public function getOrderInvoiceIdIfHasDelivery()
...
-        foreach ($results as $row) {
-            $warehouse_list[] = $row['id_warehouse'];
-        }
+        @trigger_error(sprintf(
+            '%s is deprecated since 9.0 and will be removed in 10.0.',
+            __METHOD__
+        ), E_USER_DEPRECATED);
 
-        return $warehouse_list;
+        return [0];
```
Comment (jolelievre) [inline classes/order/Order.php:2254]:
```suggestion
        return [];
```

Why not return an empty array instead? It seems like it's the equivalent of no warehouses in the DB

File: classes/order/OrderInvoice.php [hunk 8]
```diff
@@ -196,7 +196,6 @@ public function getProducts($products = false, $selected_products = false, $sele
             }
 
             $this->setProductImageInformations($row);
```
Comment (jolelievre) [inline classes/order/OrderInvoice.php]:
```suggestion
            $product['current_stock'] = '--';
```
Shouldn't it be this for the equivalence? Unless the `current_stock` field is not useful anymore

**Review by jolelievre — COMMENTED** [review]
First review batch (20 out of 117 😅)

File: classes/order/Order.php (hunk 7 above)
Comment (Hlavtox) [reply classes/order/Order.php:2254]: @jolelievre I chose to return zero because if I am correct, every row of order_detail has a id_warehouse of 0, so it would return an array with zero.

File: classes/order/OrderInvoice.php (hunk 8 above)
Comment (Hlavtox) [reply classes/order/OrderInvoice.php]: @jolelievre I will check it, I think I removed it because it wasnt used anywhere.

File: classes/Cart.php
Comment (Hlavtox) [reply classes/Cart.php:1]: You can try to refactor this method and you should end up with the same logic as I did. :-)

- remove `if ($stock_management_active &&` condition and you will end up with `$warehouse_list = [0 => ['id_warehouse' => 0]];`. So you can remove that loop right away.
- remove `if (array_key_exists((int) $id_war, $product['warehouse_list'])) {`, because zero will always exist.
- since there is always only one warehouse inside this address, you can remove this loop - `foreach ($warehouse_count_by_address[$product['id_address_delivery']] as $id_war => $val) {`.
- Then you realize you don't need the first step creating `$warehouse_count_by_address` at all. So you move some things to the second step right away.
- Then just reduce the depth of the array to remove the warehouse `[0]` key level.
- Last step is to add `'warehouse_list' => [0 => 0], 'id_warehouse' => 0,` at the end for backward compatibility. :-)

File: classes/order/OrderInvoice.php (hunk 8 above)
Comment (Hlavtox) [reply classes/order/OrderInvoice.php]: @jolelievre It wasn't used anywhere, but I added the info in my last commit. :-)

File: classes/Product.php (hunk 6 above)
Comment (Hlavtox) [reply classes/Product.php:300]: Done :-)

File: classes/order/Order.php (hunk 7 above)
Comment (Hlavtox) [reply classes/order/Order.php:2254]: Yep, it returned `[0]` before.

File: classes/Product.php (hunk 5 above)
Comment (Hlavtox) [reply classes/Product.php:7574]: Done :-)

**Review by matks — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
looks good to me, as @jolelievre said we'll need some tight QA on this PR

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Tests auto OK.

I checked the following :

BO product edition
BO stock (tab Stock and Movements)
- Employee edition
- Customer order
- Product return

BO order refund
BO product settings > product stock
FO order

LGTM ✅
