### PR TITLE
WS : Handle PATCH requests for attachments

### LINKED ISSUE #28748: [WS] Handle PATCH requests for attachments
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

> Originaly posted by @khouloudbelguith here https://github.com/PrestaShop/autoupgrade/pull/479#pullrequestreview-1004678171

Following the merge of https://github.com/PrestaShop/PrestaShop/pull/27952 it is now possible to use PATCH for API calls.
But when we try to update an attachment (= attached file) with PATCH method, the file is not updated.

PR https://github.com/PrestaShop/PrestaShop/pull/28747 fixes the problem

Attachments are files a user can upload to prestashop.

https://user-images.githubusercontent.com/16067358/173408235-586e989d-3fa5-4ac0-87b4-8456cc030f34.mp4

### Expected behavior

POST and PUT methods work as expected, so when using PATCH http method with the webservice to update an attachment, the file should be correctly updated.

### Steps to reproduce

1. Go to BO > Catalog > Files > Add a new file with type jpeg for example
2. Go to BO > Advanced Parameters > Webservice page & select Patch for the attachment
3. Using postman, I tried to update the attachment with the Patch method
4. See error > the file is not updated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by matks**
This PR continues the work started in #28747 by @nsorosac 

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      |This PR enables the use of PATCH for endpoint /api/attachments/file/{id} . In order to make sure the weird behavior described [here](https://github.com/PrestaShop/PrestaShop/pull/28747#issuecomment-1182203278) is fixed, in the PR I only modify the filename if we use POST (not PUT or PATCH).
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?      | Fixes #28748
| Related PRs       | 
| How to test?      | Please see the Postman calls listed and explained at the bottom of  #28748

### CODE REVIEW

**Comment by matks** [comment]
CI failing for bad reasons https://github.com/PrestaShop/PrestaShop/issues/29641

File: classes/webservice/WebserviceSpecificManagementAttachments.php [hunk 1]
```diff
@@ -332,10 +336,14 @@ public function executeFileAddAndEdit(): void
                 unlink(_PS_DOWNLOAD_DIR_ . $attachment->file);
             }
 
+            $defaultLanguage = Configuration::get('PS_LANG_DEFAULT');
+
             $attachment->file = $file['id'];
             $attachment->file_name = $file['file_name'];
             $attachment->mime = $file['mime_type'];
-            $attachment->name[Configuration::get('PS_LANG_DEFAULT')] = $_POST['name'] ?? $file['file_name'];
+            if ($attachment->name[$defaultLanguage] === null) {
```
Comment (jolelievre) [inline classes/webservice/WebserviceSpecificManagementAttachments.php:344]:
```suggestion
            if (empty($attachment->name[$defaultLanguage]) || !empty($_POST['name'])) {
```

Comment (jolelievre) [reply classes/webservice/WebserviceSpecificManagementAttachments.php:344]: I believe it was your suggestion that we should update the value if `$_POST['name']` is specified in the PATCH request no? And using empty is probably more adapted because an empty string is not a correct name either

**Review by jolelievre — COMMENTED** [review]
Just a small comment, and also while you are fixing something in the webservice could you fix this method https://github.com/PrestaShop/PrestaShop/blob/47cf65b7006fb75a0983172a7f0fc8a9b4f23993/classes/webservice/WebserviceSpecificManagementImages.php#L647

which is supposed to return a boolean.

File: classes/webservice/WebserviceSpecificManagementAttachments.php (hunk 1 above)
Comment (matks) [reply classes/webservice/WebserviceSpecificManagementAttachments.php:344]: To be honest I don't remember what we said ^^ but if we use PATCH then $_POST will be empty.

From the implementation of the class it seems that PUT and PATCH request can only carry a file binary content, that is available in `php://input`, not in $_POST.

See https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceSpecificManagementAttachments.php#L307

When I perform PATCH requests I can only submit a file as binary file content and there is no other body.

**Comment by kpodemski** [comment]
Remember to test it on PHP 8.1 :trollface:

**Review by matthieu-rolland — APPROVED** [review]

File: classes/webservice/WebserviceSpecificManagementAttachments.php (hunk 1 above)
Comment (jolelievre) [reply classes/webservice/WebserviceSpecificManagementAttachments.php:344]: Hmmm, that's not normal A patch method is supposed to allow performing partial update, so you can send only the name or only the file or both if you want
And in a PATCH method in PHP the `$_POST` variable is supposed to be filled the same way as with a POST request

Now it seems like the limitation comes from PHP which fills the `$_FILES` variable ONLY in a POST request, but there are solutions that can be found on internet, the basic workaround is to manually parse the multipart request like in this solution:
https://stackoverflow.com/questions/5483851/manually-parse-raw-multipart-form-data-data-with-php/5488449#5488449

Comment (matks) [reply classes/webservice/WebserviceSpecificManagementAttachments.php:344]: > Hmmm, that's not normal A patch method is supposed to allow performing partial update, so you can send only the name or only the file or both if you want

At the bottom of https://github.com/PrestaShop/PrestaShop/issues/28748 you'll find all endpoints related to this case and how they are used.

Be careful, there is a difference between endpoint `/api/attachments/` and `/api/attachments/file` 

The `/api/attachments/file` focuses only on the attached file on disk. So
- GET fetches the file content (and just the file, not its name, no description, no file extension)
- POST creates the file
- PUT modifies the file
- PATCH also modifies the file
- DELETE deletes the file

This PR aims to enable http requests against `/api/attachments/file` endpoint that contain only file, no filename additional field.

**Review by atomiix — APPROVED** [review]

**Comment by matks** [comment]
@jolelievre 

> Just a small comment, and also while you are fixing something in the webservice could you fix this method

Eyh 😆 if I start fixing stuff in every legacy class I open I will never finish

**Review by khouloudbelguith — APPROVED** [review]
Hello @matks,

Automatic tests => OK :heavy_check_mark: 

I checked THOSE HTTP requests

- GET `http://0.0.0.0:8081/PrestaShop/api/attachments/file/9` 

https://user-images.githubusercontent.com/16067358/190663262-f7c6e40b-3f75-4834-bae0-e87cfabd7de0.mp4

- PUT `http://0.0.0.0:8081/PrestaShop/api/attachments/file/9` 

https://user-images.githubusercontent.com/16067358/190664004-2f468c63-c90c-45d3-a17a-d1d167946060.mp4

I tried to PUT files with different types ( SVG, Gif, pdf, Zip, mp4)

- PATCH `http://0.0.0.0:8081/PrestaShop/api/attachments/file/10`

https://user-images.githubusercontent.com/16067358/190664731-8f23df51-aaaa-4907-922a-90fb611abe32.mp4
I tried to PATCH files with different types (Png, mp4, csv, text)

- POST `http://0.0.0.0:8081/PrestaShop/api/attachments/file`

https://user-images.githubusercontent.com/16067358/190665349-26369aba-3821-456c-b3de-064947a6a663.mp4

I tried with png, pdf, csv

- DELETE `http://0.0.0.0:8081/PrestaShop/api/attachments/13` 

https://user-images.githubusercontent.com/16067358/190666435-1fdfccf5-58d4-43b8-96ad-0233af9cea80.mp4

Also, I checked those HTTP requests

- POST + PATCH product + php7.2
- PATCH Category
- PATCH Order
- PATCH cart rule
- POST Cart rule
- PATCH Supplier
- PATCH Brand

> Remember to test it on PHP 8.1 :trollface:

@kpodemski, I checked PATCH an attachment + PHP 8.1 => OK
but PATCH a product/category => NOK with php8.1 (it is ok with php7.2), but it is not related to this PR.

Thanks!

**Comment by matks** [comment]
Thank you everybody and @khouloudbelguith
