### PR TITLE
Stock field must be empty and still be considered as zero

### LINKED ISSUE #27736: Stock moving quantity editing is taking zero, generating human error
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In version 1.7.7.x when entering Catalog - Stocks, when editing the quantity of a reference, it did not take into account the number zero, if 1 was entered, only one remained. In version 1.7.8.3 the zero must be deleted since by not doing so and typing the 1, the quantity remains with 10 units, this generates human errors.

https://drive.google.com/file/d/11A5QJGVbrBDVGuOB5sAYCkQzVj4o1Z38/view?usp=sharing

### Expected behavior

It should behave as in version 1.7.7.5. when placing any number, it did not take into account the number 0.

### Steps to reproduce

1. Catalog - Stocks
2. Add a one as quantity without deleting the zero.
3. Take as 10 in quantity and not 1 when applying the new quantity.

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fix bug for the empty state in stock delta component, it should be displayed as zero when value is empty But avoid empty to be considered as NaN so that the increment works properly
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27736
| How to test?      | See issue but TLDR; stock delta input is empty by default (no more 0 value in the field) but the incrementation still works as expected
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27776)

### CODE REVIEW

**Comment by jolelievre** [comment]
Hi @NeOMakinG 

can you review this PR please, it fixes a little bug introduced with modification from this PR https://github.com/PrestaShop/PrestaShop/pull/21939 but without losing the initial fix (I hope 😅)

I tested it and it works fine, let me know if I missed something

**Review by matks — COMMENTED** [review]
Re-running CI

**Comment by jolelievre** [comment]
@matks all green now!

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by jolelievre** [comment]
@matks a second approval to switch to QA? :)

**Comment by jolelievre** [comment]
Ah @Progi1984 was too fast :P

File: admin-dev/themes/new-theme/js/app/widgets/ps-number.vue [hunk 1]
```diff
@@ -85,7 +85,7 @@
         this.$emit('blur', $event);
       },
       increment() {
-        const value = parseInt(this.value === '' ? 0 : this.value, 10);
+        const value = parseInt(this.value === '' || isNaN(this.value) ? 0 : this.value, 10);
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/app/widgets/ps-number.vue:88]: Then the vue prop type of `value` should not be `Number` but `String` no? As every inputs values are strings

**Comment by jolelievre** [comment]
You're right @NeOMakinG I updated the type to allow both String and Number (since both types are needed actually)

I need re-approval @Progi1984 @atomiix and @NeOMakinG please

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by ocio87** [comment]
Hello,

I am not from the testing environment but I made the changes in the two files that are indicated in my environment and their behavior is the same, clicking on the box and digitizing a number does not delete the zero.

Greetings,

**Review by jolelievre — COMMENTED** [review]
Hi @ocio87 

did you recompile the assets?
https://devdocs.prestashop.com/1.7/development/compile-assets/

**Comment by ocio87** [comment]
Hello @jolelievre 

Sorry, I haven't compiled. I don't have the ability to perform that procedure. I keep an eye on the testing area and keep an eye out for any help if it's within my reach.

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @jolelievre 

I have tested this PR. The issue is fixed.
Here the checked cases : 
-Check with multistore : OK
-Check with multi-languages : OK
-Check with different product types (Simple, Customizable, with Combinations, Virtaul, Pack) : OK
-Check the increment and decrement of numbers : OK
-Check with mobile : OK
image

https://user-images.githubusercontent.com/92912932/157255731-a4870caa-b477-4e22-96f3-d9fd1af5b875.mp4

https://user-images.githubusercontent.com/92912932/157256770-b2bbb4ed-dd6e-4b98-aee0-fd2ad02f57e7.mp4

But, i just have these behaviors which are also present without PR : 
1. I cannot update with a number equal to **zero**
When i click on `Apply new quantity` by putting a zero in the field ==> An error message is displayed (Bad request)
image
But it's possible to make the final quantity equal to zero by increasing/decreasing the number (like mentionned in the screen-record)
2. It's not possible to put a number in each field with RTL (There is only the possibilty to decrease and increase the number) ==> I think i can create an issue for that

https://user-images.githubusercontent.com/92912932/157258673-a0f8a2f7-630b-4403-ae25-ecd42c3ea9ca.mp4

What do you think ? 

Thanks!

**Comment by jolelievre** [comment]
Hi @HanaRebaiQA 

for the zero value I think it's blocked on purpose, there is no interest to create a stock movement that has no value. Besides if it was already the case before it's not the scope of this PR.

For RTL issues, I didn't get everything but I'd say it's also independent of this PR Did you test without this PR or is it a bug that was introduced with these changes?

**Review by HanaRebaiQA — APPROVED** [review]
Hello @jolelievre 

Thanks for your feedback.
As i mentioned above, the two issues **are present Without this PR**
I wanted to validate with you if we can fix them in this PR or not.

For the zero issue, it's already exists on PS1784 and PS1778 => An old issue

https://user-images.githubusercontent.com/92912932/157452467-69cbd7c3-5ac8-47d0-b302-8f63ed8739bb.mp4


https://user-images.githubusercontent.com/92912932/157452422-8bd814a0-c8c2-4001-a149-1e39a9e56b8d.mp4





For the RTL issue, i checked on PS1784 : NOK, PS1778 : OK and PS1780 : NOK => It's a **regression from the 1780**

https://user-images.githubusercontent.com/92912932/157452530-ca20cbcc-7bd6-4063-af2c-33721428a5c6.mp4

https://user-images.githubusercontent.com/92912932/157452611-f310e940-9671-49a3-8843-5e0df7d966bc.mp4

https://user-images.githubusercontent.com/92912932/157452706-4228178e-e4c7-4150-acf5-7a1d402742d8.mp4



So, for this PR it's QA :heavy_check_mark: 
I will create issues for those I have detected.

Thank you!

**Review by PierreRambaud — APPROVED** [review]
