### PR TITLE
BO - Orders : Fixed amount of order discounts when changing currency

### LINKED ISSUE #16578: Changing currency on an order - Wrong voucher value displayed
**Describe the bug**
When changing currency on an order (From Euro to CHF for example), the discount applied is correct but the default voucher remains in previous currency. Is it normal?

**To Reproduce**
Steps to reproduce the behavior: you should have two currencies or more
1. Modify an order (currently in euro)
2. Click on 'Modify currency' in the payment block (swap currency to CHF)
3. Scroll down at the bottom of the page where the voucher shows up
4. The amount used in the total is correct, but the voucher shows the previous amount

**Screenshots**
image

**Additional information**
PrestaShop version: 1.7.5.1
PHP version: 7.0.33

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | BO - Orders : Fixed amount of order discounts when changing currency
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | :arrow_down: 
| UI Tests          |  https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/19439325539
| Fixed issue or discussion?     | Fixes #16578
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

## How to test ?
1. Go to BO
2. Modify an order (currently in euro)
3. Add a voucher (5€ for example)
4. Click on 'Modify currency' in the payment block (swap currency to CHF or :dollar: )
5. Scroll down at the bottom of the page where the voucher shows up
6. **BEFORE** : The amount used in the total is correct, but the voucher shows the previous amount
7. **AFTER** : The amount used in the total is correct, and the voucher shows the updated amount

### CODE REVIEW

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 1]
```diff
@@ -112,6 +114,26 @@ public function before()
...
+    /**
+     * @Given I change for the order :orderReference the currency :oldCurrency to :newCurrency
+     *
+     * @param string $orderReference
+     * @param string $oldCurrency
+     * @param string $newCurrency
+     */
+    public function changeOrderCurrency(string $orderReference, string $oldCurrency, string $newCurrency): void
+    {
+        $oldCurrencyId = Currency::getIdByIsoCode($oldCurrency, 0, true);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
        $oldCurrencyId = $this->referenceToId($oldCurrencyReference);
```
Currencies' IDs should be retrievable via the shared storage, if you can use this method instead it would be better for the consistency of the context classes

**Comment by Progi1984** [comment]
Ping for review : 
- Internal Committers : @PrestaShop/prestashop-core-developers 
- External Committers : @Codencode / @SharakPL / @Hlavtox / @ShaiMagal / @PululuK / @leemyongpakva / @Touxten

**Review by Hlavtox — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Progi1984, 

Thanks you for your PR, I tested it and it's good for me 

https://github.com/user-attachments/assets/8f49feeb-86b8-40f4-835b-08d59cbdc852

**Review by SiraDIOP — APPROVED** [review]

**Comment by Hlavtox** [comment]
Thank you @Progi1984!
