### PR TITLE
Avoid module sorting function warnings when module data is invalid

### LINKED ISSUE #12478: When I delete a module folder, I get warnings on Permissions BO page
**Describe the bug**
When a module folder is deleted, some php functions related to modules misbehave and generate warnings that can appear in some BO pages.

**To Reproduce**
1. Remove one of your module *by deleting its folder* (example: delete `modules/welcome` module)
2. Go to BO Advanced Parameters > Team > Permissions BO page
3. See warnings

**Screenshots**
capture d ecran 2019-02-07 a 11 46 03

**Additionnal information**
PrestaShop version: `develop` (future 1.7.6)
PHP version: 7.2

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Avoid php warnings when module data is invalid
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/12478
| How to test?  | See fixed ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12479)

### CODE REVIEW

File: controllers/admin/AdminAccessController.php [hunk 1]
```diff
@@ -194,8 +194,18 @@ public function getCurrentProfileId()
...
 
+    /**
+     * @param array $a module data
+     * @param array $b module data
+     *
+     * @return int
+     */
     protected function sortModuleByName($a, $b)
     {
+        if ((!array_key_exists('name', $a)) || (!array_key_exists('name', $b))) {
```
Comment (PierreRambaud) [inline controllers/admin/AdminAccessController.php]: Because strnatcmp can compare null / empty string. 
```php
$aName = isset($a['name']) ? $a['name'] : null;
$bName = isset($b['name']) ? $b['name'] : null;
return strnatcmp($aName, $bName);
```

**Review by PierreRambaud — DISMISSED** [review]
see comment

File: controllers/admin/AdminAccessController.php (hunk 1 above)
Comment (matks) [reply controllers/admin/AdminAccessController.php]: Makes sense 👍

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thanks for the review 😄
