### PR TITLE
Fix BO - The images are not well displayed after adding it in file manager with php8.1

### LINKED ISSUE #29291: BO - The images are not well displayed after adding it in file manager with php8.1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The images are not well displayed after adding it in file manager with php8.1

**8.0.x with php8.1 : NOK** :x: 
image

**8.0.x with php7.3 : OK** :heavy_check_mark: 
image

### Expected behavior

The images are well dispalyed

### Steps to reproduce

1. Check with php8.1
2. Go to BO > Catalog > Categories page OR Products page
3. Edit any Category/Product
4. Insert any type of image (jpeg, png, ..) in the file manager
5. Click on Return to files list to come back to the list of displayed images in the file manager
6. See error >> The images are not well displayed!

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Since php 8.0 gd library has changed
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29291

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @FabienPapet 

That's efficient 😅

**Review by matks — DISMISSED** [review]
So if I understand correctly, the checks performed by prestashop before are now useless because GD does them?

File: admin-dev/filemanager/include/php_image_magician.php [hunk 1]
```diff
@@ -2539,15 +2539,6 @@ public function saveImage($savePath, $imageQuality="100")
   #             * bmp files have no native support for bmp files. We use a
   #       third party class to save as bmp.
     {
-
-    // *** Perform a check or two.
-    if (!is_resource($this->imageResized)) {
```
Comment (atomiix) [inline admin-dev/filemanager/include/php_image_magician.php:2544]: Why not check both? It seems that `$this->imageResized` can be `false` so it would make sense to test it?
```php
if (!is_resource($this->imageResized) && !($this->imageResized instanceof GdImage)) {
```

File: admin-dev/filemanager/include/php_image_magician.php [hunk 2]
```diff
@@ -2644,13 +2635,6 @@ public function displayImage($fileType = 'jpg', $imageQuality="100")
     # Notes:
     #
   {
-      if (!is_resource($this->imageResized)) {
```
Comment (MeKeyCool) [inline admin-dev/filemanager/include/php_image_magician.php:2647]: If I remember what you said, the problem occurred only with php 8.1.
Then what is the change that was done with php 8.1 that you fix removing this code ?

And then why didn't you remove this line for example  : https://github.com/PrestaShop/PrestaShop/blob/94c5f31ad0f1926b58c0fa02f8a4b7ce5db4c688/admin-dev/filemanager/include/php_image_magician.php#L3148 ?
Did you check if this function was called somewhere else ?

File: admin-dev/filemanager/include/php_image_magician.php (hunk 1 above)
Comment (FabienPapet) [reply admin-dev/filemanager/include/php_image_magician.php:2544]: Imo it's useless as this only causes exception, without giving any details. And here the if condition is (IMO) useless since the check is already done before calling the script.

File: admin-dev/filemanager/include/php_image_magician.php (hunk 2 above)
Comment (FabienPapet) [reply admin-dev/filemanager/include/php_image_magician.php:2647]: Yes, in case you want to resize `.bmp` files, I forgot to remove it.

**Comment by FabienPapet** [comment]
> So if I understand correctly, the checks performed by prestashop before are now useless because GD does them?

No, the function signature has changed, and all gd functions are now working with `GdImage` instances and not with  resources anymore.

File: admin-dev/filemanager/include/php_image_magician.php (hunk 1 above)
Comment (atomiix) [reply admin-dev/filemanager/include/php_image_magician.php:2544]: @FabienPapet I don't see where the check is done?

**Review by MeKeyCool — DISMISSED** [review]

File: admin-dev/filemanager/include/php_image_magician.php (hunk 1 above)
Comment (FabienPapet) [reply admin-dev/filemanager/include/php_image_magician.php:2544]: We already check if the file exists in the constructor, but the constructor does not throw any exception if the file does not exist or if the extension is not supported.... 
Anyway, as it can be false, I've reverted and added the condition. 

I really hope we can get rid of this library soon

**Review by atomiix — APPROVED** [review]

**Review by MeKeyCool — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hello @FabienPapet,

Automatic tests are Ok :heavy_check_mark: 
Issue fixed 
image
I tried with those images: webp, jpeg, png, png, gif, and jpg => OK.

https://user-images.githubusercontent.com/16067358/188623596-fdc6dc44-329f-4ced-b966-b936120a2378.mp4


Thanks!

**Review by jolelievre — APPROVED** [review]
