### PR TITLE
Handle route not found in new api

### LINKED ISSUE #31106: API : Request Endpoint `/admin-dev/new-api/` return bad HTTP Code
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I request the endpoint `/admin-dev/new-api/`
I receive a response where the HTTP code is 401

=> Detected by #31102

### Expected behavior

I request the endpoint `/admin-dev/new-api/`
I receive a response where the HTTP code is 404

### Steps to reproduce

1. Request the endpoint `/admin-dev/new-api` with method GET

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #31107: API : Request Endpoint `/admin-dev/new-api/hook-status` return bad HTTP Code
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I request the endpoint `/admin-dev/new-api/hook-status`
I receive a response where the HTTP code is 200 (Redirect to Login Page)

=> Detected by #31102

### Expected behavior

I request the endpoint `/admin-dev/new-api/hook-status`
I receive a response where the HTTP code is 4040

### Steps to reproduce

1. Request the endpoint `/admin-dev/new-api/hook-status` with method GET

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Handle route (endpoints) not found in new api
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31106 and #31107 
| Fixed ticket?     | Fixes #31106 , Fixes #31107 
| Sponsor company   | [@PrestaShopCorp](https://github.com/PrestaShopCorp)

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

File: admin-dev/index.php [hunk 1]
```diff
@@ -76,9 +77,14 @@
 $request = Request::createFromGlobals();
 Request::setTrustedProxies([], Request::HEADER_X_FORWARDED_ALL);
 
+$catch = false;
+if (false !== strpos($request->getRequestUri(), Api::API_BASE_PATH)) {
+    $catch = true;
+}
```
Comment (atomiix) [inline admin-dev/index.php]:
```suggestion
$catch = false !== strpos($request->getRequestUri(), Api::API_BASE_PATH);
```

**Review by FabienPapet — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by paulnoelcholot** [comment]
Hello @mflasquin,

I have tested your PR and it's OK for me :tada: 
Thanks!

**Review by paulnoelcholot — DISMISSED** [review]

**Review by atomiix — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]
