### PR TITLE
Fix exclude discounted products on CartRule

### LINKED ISSUE #10300: Cart rule with "exclude discounted products" do not work as expected
**Describe the bug**
In BO, an option on cart rule is "exclude discounted products". But if I add discounted product in my cart on FO, and the corresponding cart rule, discount will be applied on all cart rows

**To Reproduce**
In BO : Create 2 products, one with a discount. Create a cart rule and check the option "exclude discounted products"
In FO add the 2 products, and the cart rule. Cart total should be calculated with cart rule applying only on the not-discounted product 

comments about that issue here : https://github.com/PrestaShop/PrestaShop/pull/9383

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4
PHP version: N/A

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | CartRules exclude specials from discounts doesn't work when no specific products are selected. Thank you @venditdevs 
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | fixes https://github.com/PrestaShop/PrestaShop/issues/10300
| How to test?  | on BO create cartRule with "exclude discounted product" checked. On a product add a specific price. On FO add the product and the cart rule. Cart calculation should be good. Behat tests added

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13704)

### CODE REVIEW

**Comment by tomlev** [comment]
@venditdevs I made a new PR with your both patches. And added some behat tests.
Thank you !

**Comment by tomlev** [comment]
Patches from @venditdevs 
https://github.com/PrestaShop/PrestaShop/pull/13628
https://github.com/PrestaShop/PrestaShop/pull/13267

File: tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php [hunk 1]
```diff
@@ -154,6 +154,27 @@ public function cartRuleNamedIsRestrictedToCarrierNamed($cartRuleName, $carrierN
         Cache::clear();
     }
 
+    /**
+     * @Given /^cart rule "(.+)" is restricted to cheapest product$/
```
Comment (matks) [inline tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: "cheapest products" is a bit vague 🤔 can we improve it ?

Comment (matks) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: From behat context I see it actually is clear, so maybe it only needs an explanation ?

Comment (tomlev) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: this is a product specification: on cart rule configuration page, you can set the option "Exclude discounted products"

Comment (matks) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: cheapest products is different from discounted products 🤔 😉

Comment (tomlev) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: or 
"Apply a discount to
-Order (without shipping)
-Specific product
-Cheapest product"

Comment (tomlev) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: @matks sorry I pressed "comment" a bit too soon

Comment (matks) [reply tests/Integration/Behaviour/Features/Context/CartRuleFeatureContext.php:158]: OK it makes sense then 👌

**Review by matks — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @tomlev

**Comment by davideapvd** [comment]
would this be ported to 1.7.6.x ?


this a patch that I manually applied to 1.7.6.2 to only introduce the bugfix, maybe helps others.
```

---
 src/Core/Cart/CartRuleCalculator.php | 17 +++++++++++------
 1 file changed, 11 insertions(+), 6 deletions(-)

diff --git a/src/Core/Cart/CartRuleCalculator.php b/src/Core/Cart/CartRuleCalculator.php
index 5ef0c18e..c816b955 100644
--- a/src/Core/Cart/CartRuleCalculator.php
+++ b/src/Core/Cart/CartRuleCalculator.php
@@ -124,8 +124,12 @@ class CartRuleCalculator
         // Discount (%) on the whole order
         if ($cartRule->reduction_percent && $cartRule->reduction_product == 0) {
             foreach ($this->cartRows as $cartRow) {
-                $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
-                $cartRuleData->addDiscountApplied($amount);
+                $product = $cartRow->getRowData();
+                if ((($cartRule->reduction_exclude_special && !$product['reduction_applies'])
+                        || !$cartRule->reduction_exclude_special)) {
+                    $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
+                    $cartRuleData->addDiscountApplied($amount);
+                }
             }
         }
 
@@ -144,9 +148,10 @@ class CartRuleCalculator
             /** @var CartRow|null $cartRowCheapest */
             $cartRowCheapest = null;
             foreach ($this->cartRows as $cartRow) {
-                if ($cartRowCheapest === null
-                    || $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded() > $cartRow->getInitialUnitPrice()
-                                                                                           ->getTaxIncluded()
+                $product = $cartRow->getRowData();
+                if (((($cartRule->reduction_exclude_special && !$product['reduction_applies'])
+                        || !$cartRule->reduction_exclude_special)) && ($cartRowCheapest === null
+                        || $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded() > $cartRow->getInitialUnitPrice()->getTaxIncluded())
                 ) {
                     $cartRowCheapest = $cartRow;
                 }
@@ -155,7 +160,7 @@ class CartRuleCalculator
                 // apply only on one product of the cheapest row
                 $discountTaxIncluded = $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded()
                                        * $cartRule->reduction_percent / 100;
-                $discountTaxExcluded = $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded()
+                $discountTaxExcluded = $cartRowCheapest->getInitialUnitPrice()->getTaxExcluded()
                                        * $cartRule->reduction_percent / 100;
                 $amount = new AmountImmutable($discountTaxIncluded, $discountTaxExcluded);
                 $cartRowCheapest->applyFlatDiscount($amount);
-- 
2.20.1

```

**Comment by JjPrus** [comment]
Can I apply this fix to the 1.7.6.4 or 1.7.6.5 ? Stil the same problem #17489 

edit: I only change CartRulCalculator.php as @davideapvd sugested and it seems to be working with no errors. Both in freshly instaled 17.6.5 and  working shop with custom theme and decimal length quantity applied on 1.7.6.4 so it should be ok.

Why one year old solution wasn't applied to new release? Is it to Prestashop~~French mindset related or smth? Thank @tomlev a lot for a solution!

**Comment by zacariasw** [comment]
> would this be ported to 1.7.6.x ?
> 
> this a patch that I manually applied to 1.7.6.2 to only introduce the bugfix, maybe helps others.
> 
> ```
> 
> ---
>  src/Core/Cart/CartRuleCalculator.php | 17 +++++++++++------
>  1 file changed, 11 insertions(+), 6 deletions(-)
> 
> diff --git a/src/Core/Cart/CartRuleCalculator.php b/src/Core/Cart/CartRuleCalculator.php
> index 5ef0c18e..c816b955 100644
> --- a/src/Core/Cart/CartRuleCalculator.php
> +++ b/src/Core/Cart/CartRuleCalculator.php
> @@ -124,8 +124,12 @@ class CartRuleCalculator
>          // Discount (%) on the whole order
>          if ($cartRule->reduction_percent && $cartRule->reduction_product == 0) {
>              foreach ($this->cartRows as $cartRow) {
> -                $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
> -                $cartRuleData->addDiscountApplied($amount);
> +                $product = $cartRow->getRowData();
> +                if ((($cartRule->reduction_exclude_special && !$product['reduction_applies'])
> +                        || !$cartRule->reduction_exclude_special)) {
> +                    $amount = $cartRow->applyPercentageDiscount($cartRule->reduction_percent);
> +                    $cartRuleData->addDiscountApplied($amount);
> +                }
>              }
>          }
>  
> @@ -144,9 +148,10 @@ class CartRuleCalculator
>              /** @var CartRow|null $cartRowCheapest */
>              $cartRowCheapest = null;
>              foreach ($this->cartRows as $cartRow) {
> -                if ($cartRowCheapest === null
> -                    || $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded() > $cartRow->getInitialUnitPrice()
> -                                                                                           ->getTaxIncluded()
> +                $product = $cartRow->getRowData();
> +                if (((($cartRule->reduction_exclude_special && !$product['reduction_applies'])
> +                        || !$cartRule->reduction_exclude_special)) && ($cartRowCheapest === null
> +                        || $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded() > $cartRow->getInitialUnitPrice()->getTaxIncluded())
>                  ) {
>                      $cartRowCheapest = $cartRow;
>                  }
> @@ -155,7 +160,7 @@ class CartRuleCalculator
>                  // apply only on one product of the cheapest row
>                  $discountTaxIncluded = $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded()
>                                         * $cartRule->reduction_percent / 100;
> -                $discountTaxExcluded = $cartRowCheapest->getInitialUnitPrice()->getTaxIncluded()
> +                $discountTaxExcluded = $cartRowCheapest->getInitialUnitPrice()->getTaxExcluded()
>                                         * $cartRule->reduction_percent / 100;
>                  $amount = new AmountImmutable($discountTaxIncluded, $discountTaxExcluded);
>                  $cartRowCheapest->applyFlatDiscount($amount);
> -- 
> 2.20.1
> ```

I change this lines of code of this post in my prestashop 1.7.6.4, and dont do nothing, anybody have the same problem?? anybody know another solution? Thanks

**Comment by ACTIVA-E** [comment]
Hi, I'm new here.
Applied https://github.com/PrestaShop/PrestaShop/pull/13704#issuecomment-622147277 and worked for me! Thank you zacariasw

**Comment by mircobabini** [comment]
Same here, it works!

**Comment by onklmaps** [comment]
I belive this is merged in at 1.7.7.0.
However, the issue is still reproducible on 1.7.7.4.

**Comment by Fabio11111** [comment]
good morning everyone, sorry, but I can't apply the modification to the CartRuleCalculator.php file, would someone be kind enough to put the complete code of the entire file? Thank you
