### PR TITLE
Handle Product level discount in CQRS

### LINKED ISSUE #38741: Add product level discount
# Context

We must add this new type once all condition options are implemented.

For product-level discounts, the discount applies to each product related to the discount.
This type of discount can only be applied either:
- to one specific product (and its variants)
- to one product segment

The selected products that trigger the discount are also the ones targeted by the discount.

**This is a discount on a product :** 
if I have a flat discount on a product -$2 => if I have 3 products in my cart => -$6
if I have a % discount on  a product -10% => I have -10% on each product

**_This is not the same thing as a cart discount conditioned by a product_**

We also need to check in this issue that : 
* the product segement on the product works when selecting a single product 
* when selecting a group of product

This is going to be 2 PRs : 
- [ ] First PR behat oriented and core logic : related to this task : https://github.com/PrestaShop/PrestaShop/issues/39992

* implement the logic of the discount ( if I have a flat discount on a product -$2 => if I have 3 products in my cart => -$6
* if I have a % discount on  a product -10% => I have -10% on each product ) 
* add behat tests

- [ ] Second PR connect the BO and checks : related to this task : https://github.com/PrestaShop/PrestaShop/issues/39993
* Link the core logic to the BO 
* check that the mockup is respected
* check that the product segment on one product is ok
* implement the product segment on a group of product

# Mockup

Image

Image

# Tests
-  order with X times the same product impacted by the discount => discount is applied X times for each products
- order with X differents products impacted by the discount => discount is applied X times for each product

### LINKED ISSUE #39992: First PR behat oriented and core logic
* implement the logic of the discount ( if I have a flat discount on a product -$2 => if I have 3 products in my cart => -$6
* if I have a % discount on a product -10% => I have -10% on each product )
    add behat tests

### LINKED ISSUE #39993: Second PR connect the BO and checks
* implement the logic of the discount ( if I have a flat discount on a product -$2 => if I have 3 products in my cart => -$6
    if I have a % discount on a product -10% => I have -10% on each product )
* add behat tests
* Link the core logic to the BO
* check that the mockup is respected
* check that the product segment on one product is ok
* implement the product segment on a group of product

### LINKED ISSUE #40283: Customer eligibility
### Description

Add support for customer eligibility restrictions in the Discount API. Customer eligibility allows merchants to restrict discounts to specific customers or customer groups.

**Required Changes:**
- Add customer eligibility fields to the API resource schema:
  - `customer` field (single customer restriction)
  - `customer_groups` field (group restrictions)
- Support reading customer eligibility via GET endpoints
- Support writing customer eligibility via POST/PUT endpoints
- Ensure proper validation and business logic

**Technical Details:**
- Single customer restriction: `cart_rule.id_customer` (0 = no restriction, >0 = specific customer)
- Group restrictions: `cart_rule_group` junction table
- When `id_customer` is set, the discount applies only to that specific customer
- When customer groups are specified, the discount applies to customers in those groups
- Both can be used together (customer must be in specified group AND be the specific customer)

#### Prerequisites
1. Set up a PrestaShop 9 instance with API access configured
2. Create an API client with appropriate permissions
3. Create test customers:
   - Customer A (ID: 1)
   - Customer B (ID: 2)
4. Create customer groups:
   - Group 1: "VIP Customers"
   - Group 2: "Regular Customers"
5. Assign customers to groups

#### Test Case 1: Create Discount with Single Customer Restriction
1. **Create a discount restricted to a specific customer:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Customer-Specific Discount",
     "code": "CUST1ONLY",
     "active": true,
     "conditions": {
       "customer": {
         "id": 1
       }
     },
     "discount": {
       "reduction": {
         "type": "percentage",
         "value": 15
       }
     }
   }
   ```

2. **Verify creation:**
   - Response status should be 201 Created
   - Response should include the customer restriction
   - Verify in Back Office that the discount is restricted to customer ID 1
   - Verify that only customer 1 can use this discount

#### Test Case 2: Create Discount with Customer Group Restriction
1. **Create a discount restricted to customer groups:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "VIP Discount",
     "code": "VIP2025",
     "active": true,
     "conditions": {
       "customer_groups": [1]  // VIP Customers group
     },
     "discount": {
       "reduction": {
         "type": "percentage",
         "value": 20
       }
     }
   }
   ```

2. **Verify creation:**
   - Response status should be 201 Created
   - Response should include the group restrictions
   - Verify in Back Office that the discount is restricted to group 1
   - Verify that only customers in group 1 can use this discount

#### Test Case 3: Read Customer Eligibility via GET
1. **Retrieve a discount with customer restrictions:**
   ```bash
   GET /api/discounts/{discountId}
   Authorization: Bearer {api_token}
   ```

2. **Verify response:**
   - Response should include `conditions.customer.id` if single customer is set
   - Response should include `conditions.customer_groups` array if groups are set
   - All eligibility information should be present and accurate

#### Test Case 4: Update Customer Eligibility
1. **Update an existing discount's customer eligibility:**
   ```bash
   PUT /api/discounts/{discountId}
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "customer": {
         "id": 2
       },
       "customer_groups": [1, 2]
     }
   }
   ```

2. **Verify update:**
   - Response status should be 200 OK
   - Response should reflect the updated customer eligibility
   - Verify in Back Office that restrictions were updated correctly

#### Test Case 5: Remove Customer Restrictions
1. **Remove customer restrictions from a discount:**
   ```bash
   PUT /api/discounts/{discountId}
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "customer": null,
       "customer_groups": []
     }
   }
   ```

2. **Verify removal:**
   - Response status should be 200 OK
   - Discount should now be available to all customers
   - Verify in Back Office that restrictions were removed

#### Test Case 6: Validation - Invalid Customer ID
1. **Attempt to create discount with non-existent customer:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "customer": {
         "id": 99999
       }
     },
     ...
   }
   ```

2. **Verify validation:**
   - Response status should be 400 Bad Request
   - Response should include validation error about invalid customer

#### Test Case 7: Validation - Invalid Group IDs
1. **Attempt to create discount with invalid group IDs:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "customer_groups": [99999, -1]
     },
     ...
   }
   ```

2. **Verify validation:**
   - Response status should be 400 Bad Request
   - Response should include validation errors about invalid groups

#### Test Case 8: Functional Test - Customer Can Use Discount
1. **Create a discount restricted to customer 1**
2. **As customer 1, add items to cart and apply discount:**
   - Should succeed
3. **As customer 2, attempt to use the same discount:**
   - Should fail with appropriate error message
   - Discount should not be applicable

### LINKED ISSUE #40284: Customer usage limit
### Description

Add support for customer usage limits in the Discount API. Customer usage limits allow merchants to restrict how many times a specific customer can use a discount.

**Required Changes:**
- Add `available_per_user` field to the API resource schema
- Support reading usage limits via GET endpoints
- Support writing usage limits via POST/PUT endpoints
- Ensure proper validation (must be positive integer or 0 for unlimited)

**Technical Details:**
- Field: `cart_rule.quantity_per_user`
- Value 0 means unlimited usage per customer
- Value > 0 means the customer can use the discount that many times
- Usage is tracked per customer via orders and cart applications
- The system checks usage when applying discounts to carts

#### Prerequisites
1. Set up a PrestaShop 9 instance with API access configured
2. Create an API client with appropriate permissions
3. Create test customers:
   - Customer A (ID: 1)
   - Customer B (ID: 2)
4. Set up a test product and cart functionality

#### Test Case 1: Create Discount with Usage Limit
1. **Create a discount with usage limit:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Limited Use Discount",
     "code": "LIMIT3",
     "active": true,
     "conditions": {
       "available_per_user": 3
     },
     "discount": {
       "reduction": {
         "type": "percentage",
         "value": 10
       }
     }
   }
   ```

2. **Verify creation:**
   - Response status should be 201 Created
   - Response should include `conditions.available_per_user: 3`
   - Verify in Back Office that the usage limit is set correctly

#### Test Case 2: Read Usage Limit via GET
1. **Retrieve a discount with usage limit:**
   ```bash
   GET /api/discounts/{discountId}
   Authorization: Bearer {api_token}
   ```

2. **Verify response:**
   - Response should include `conditions.available_per_user` field
   - Value should match what was set during creation

#### Test Case 3: Update Usage Limit
1. **Update an existing discount's usage limit:**
   ```bash
   PUT /api/discounts/{discountId}
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "available_per_user": 5
     }
   }
   ```

2. **Verify update:**
   - Response status should be 200 OK
   - Response should reflect the updated usage limit
   - Verify in Back Office that the limit was updated

#### Test Case 4: Set Unlimited Usage (0)
1. **Create or update discount with unlimited usage:**
   ```bash
   PUT /api/discounts/{discountId}
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "available_per_user": 0
     }
   }
   ```

2. **Verify unlimited usage:**
   - Response status should be 200 OK
   - Response should show `available_per_user: 0`
   - Customer should be able to use the discount unlimited times

#### Test Case 5: Validation - Negative Value
1. **Attempt to set negative usage limit:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "available_per_user": -1
     },
     ...
   }
   ```

2. **Verify validation:**
   - Response status should be 400 Bad Request
   - Response should include validation error about invalid value

#### Test Case 6: Validation - Non-Integer Value
1. **Attempt to set non-integer usage limit:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "conditions": {
       "available_per_user": 3.5
     },
     ...
   }
   ```

2. **Verify validation:**
   - Response status should be 400 Bad Request
   - Response should include validation error about integer requirement

#### Test Case 7: Functional Test - Usage Limit Enforcement
1. **Create a discount with usage limit of 2:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Two-Time Use Discount",
     "code": "USE2X",
     "active": true,
     "conditions": {
       "available_per_user": 2
     },
     "discount": {
       "reduction": {
         "type": "percentage",
         "value": 15
       }
     }
   }
   ```

2. **Test usage tracking:**
   - As customer 1, use the discount in cart/order #1: Should succeed
   - As customer 1, use the discount in cart/order #2: Should succeed
   - As customer 1, attempt to use the discount in cart/order #3: Should fail with "usage limit reached" error
   - As customer 2, use the discount: Should succeed (separate limit per customer)

#### Test Case 8: Check Remaining Usage
1. **After creating a discount with usage limit, check remaining usage:**
   ```bash
   GET /api/discounts/{discountId}/usage?customer_id=1
   Authorization: Bearer {api_token}
   ```

2. **Verify response:**
   - Response should include:
     - `total_limit`: 3 (or whatever was set)
     - `used_count`: 1 (or current usage)
     - `remaining`: 2 (or remaining uses)

### LINKED ISSUE #40285: Handle type compatibility in the discounts
### Description

Add proper handling and validation for discount type compatibility in the Discount API. The develop branch introduces discount types as database entities with IDs. Compatibility rules determine which discount types can be used together in the same cart. This issue requires exposing discount types via API and allowing management of compatibility rules between different discount types.

**Required Changes:**
- Create CQRS query and handler to list all discount types with their IDs
  - Query: `GetDiscountTypesQuery`
  - QueryHandler: `GetDiscountTypesHandler`
  - QueryResult: `DiscountTypeList` or similar
- Create API endpoint: `GET /api/discount-types` to retrieve all available discount types
- Add API endpoints to manage compatibility rules for discounts
  - Endpoint to get compatibility for a discount: `GET /api/discounts/{discountId}/compatibility`
  - Endpoint to update compatibility for a discount: `PUT /api/discounts/{discountId}/compatibility`
- Add compatibility field when creating/updating discounts via API
- Add validation to ensure compatibility rules are properly set
- Return clear error messages when incompatible discounts are used together
- Document compatibility rules in API documentation

**Technical Details:**
- **Discount Types:**
  - Stored in `cart_rule_type` table with `id_cart_rule_type` as primary key
  - Available types: `cart_level`, `product_level`, `free_gift`, `free_shipping`, `order_level`
  - Each type has multilingual name and description in `cart_rule_type_lang` table
  - Types have `active` flag to enable/disable them
- **Discount Types List Endpoint:**
  - Endpoint: `GET /api/discount-types`
  - Returns array of discount types with IDs and metadata from database
  - Example response structure:
    ```json
    [
      {
        "id_cart_rule_type": 1,
        "type": "cart_level",
        "name": "On cart amount",
        "description": "Discount applied to cart",
        "is_core": true,
        "active": true
      },
      {
        "id_cart_rule_type": 2,
        "type": "free_shipping",
        "name": "On free shipping",
        "description": "Discount that provides free shipping to the order",
        "is_core": true,
        "active": true
      }
    ]
    ```
  - Requires CQRS implementation (Query + QueryHandler + QueryResult)
- **Compatibility Management:**
  - Compatibility is stored in `cart_rule_compatible_types` junction table
  - Links a discount (`id_cart_rule`) to compatible discount types (`id_cart_rule_type`)
  - When creating/updating a discount, you can specify which other discount types it's compatible with
  - Example: A `cart_level` discount can be marked as compatible with `free_shipping` discounts, meaning they can both be applied to the same cart
  - Compatibility is checked when applying discounts to ensure only compatible discounts are used together
- **Compatibility Endpoints:**
  - `GET /api/discounts/{discountId}/compatibility` - Returns array of compatible discount type IDs
  - `PUT /api/discounts/{discountId}/compatibility` - Updates compatibility rules
  - Request body format (option 1 - array of IDs):
    ```json
    {
      "compatible_type_ids": [1, 2, 3]
    }
    ```
  - Request body format (option 2 - checkbox format matching form structure):
    ```json
    {
      "compatible_type_1": true,
      "compatible_type_2": true,
      "compatible_type_3": true
    }
    ```
  - Both formats should be supported for flexibility

#### Prerequisites
1. Set up a PrestaShop 9 instance with API access configured
2. Create an API client with appropriate permissions
3. Have test products available

#### Test Case 0: List Discount Types (CQRS Required)
1. **Retrieve all available discount types:**
   ```bash
   GET /api/discount-types
   Authorization: Bearer {api_token}
   ```

2. **Verify response:**
   - Response status should be 200 OK
   - Response should be a JSON array of discount types from database
   - Each type should include:
     - `id_cart_rule_type`: Unique database identifier for the type
     - `type`: Type code (e.g., "cart_level", "free_shipping", "product_level", "free_gift", "order_level")
     - `name`: Human-readable name (multilingual)
     - `description`: Description (multilingual)
     - `is_core`: Boolean indicating if it's a core type
     - `active`: Boolean indicating if the type is active
   - Example response structure:
     ```json
     [
       {
         "id_cart_rule_type": 1,
         "type": "cart_level",
         "name": "On cart amount",
         "description": "Discount applied to cart",
         "is_core": true,
         "active": true
       },
       {
         "id_cart_rule_type": 2,
         "type": "free_shipping",
         "name": "On free shipping",
         "description": "Discount that provides free shipping to the order",
         "is_core": true,
         "active": true
       },
       {
         "id_cart_rule_type": 3,
         "type": "product_level",
         "name": "On catalog products",
         "description": "Discount applied to specific products",
         "is_core": true,
         "active": true
       }
     ]
     ```

3. **Verify CQRS implementation:**
   - Query class should be created: `GetDiscountTypesQuery`
   - QueryHandler should be created: `GetDiscountTypesHandler`
   - QueryResult/DTO should be created to represent discount type data
   - QueryHandler should retrieve types from database using `DiscountTypeRepository::getAllActiveTypes()`
   - Response should be consistent and reflect actual database state
   - All active discount types should be included

#### Test Case 1: Create Discount with Compatibility Rules
1. **Get discount type IDs:**
   ```bash
   GET /api/discount-types
   Authorization: Bearer {api_token}
   ```
   - Note IDs for discount types (e.g., `cart_level: 1`, `free_shipping: 2`)

2. **Create a cart_level discount with compatibility rules:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Cart Discount",
     "code": "CART10",
     "active": true,
     "information": {
       "discount_type": "cart_level"
     },
     "value": {
       "reduction": {
         "type": "percentage",
         "value": 10
       }
     },
     "usability": {
       "compatibility": {
         "compatible_type_2": true,
         "compatible_type_3": true
       }
     }
   }
   ```
   - Note: `compatible_type_2` means compatible with discount type ID 2
   - The compatibility is stored in `cart_rule_compatible_types` table
   }
   ```
   - This marks the discount as compatible with discount types 2 and 3 (e.g., free_shipping and product_level)

3. **Verify creation:**
   - Response status should be 201 Created
   - Discount should be created successfully
   - Compatibility rules should be saved in `cart_rule_compatible_types` table
   - Verify in Back Office that compatibility is set correctly

#### Test Case 2: Get Compatibility for a Discount
1. **Create a discount with compatibility rules (as in Test Case 1)**
2. **Retrieve compatibility rules for the discount:**
   ```bash
   GET /api/discounts/{discountId}/compatibility
   Authorization: Bearer {api_token}
   ```

3. **Verify response:**
   - Response status should be 200 OK
   - Response should return array of compatible discount type IDs
   - Example response:
     ```json
     {
       "discount_id": 1,
       "compatible_type_ids": [2, 3]
     }
     ```
   - Or array of full type objects:
     ```json
     {
       "discount_id": 1,
       "compatible_types": [
         {
           "id_cart_rule_type": 2,
           "type": "free_shipping",
           "name": "On free shipping"
         },
         {
           "id_cart_rule_type": 3,
           "type": "product_level",
           "name": "On catalog products"
         }
       ]
     }
     ```

#### Test Case 3: Update Compatibility for a Discount
1. **Create a discount without compatibility rules:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Cart Discount 2",
     "code": "CART20",
     "active": true,
     "information": {
       "discount_type": "cart_level"
     },
     "value": {
       "reduction": {
         "type": "percentage",
         "value": 20
       }
     }
   }
   ```
   - Note the discount ID

2. **Update compatibility rules (using array format):**
   ```bash
   PUT /api/discounts/{discountId}/compatibility
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "compatible_type_ids": [2, 4]
   }
   ```
   
   **Or using checkbox format:**
   ```bash
   PUT /api/discounts/{discountId}/compatibility
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "compatible_type_2": true,
     "compatible_type_4": true
   }
   ```

3. **Verify update:**
   - Response status should be 200 OK
   - Compatibility rules should be updated in `cart_rule_compatible_types` table
   - Verify via GET request that compatibility was updated
   - Old compatibility rules should be removed, new ones added

#### Test Case 4: Remove Compatibility Rules
1. **Create a discount with compatibility rules**
2. **Remove all compatibility rules:**
   ```bash
   PUT /api/discounts/{discountId}/compatibility
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "compatible_type_ids": []
   }
   ```
   - Or send empty object: `{}`

3. **Verify removal:**
   - Response status should be 200 OK
   - All compatibility rules should be removed from database
   - Discount should have no compatibility restrictions

#### Test Case 5: Functional Test - Compatible Discounts Can Be Used Together
1. **Create two discounts:**
   - Discount A: `cart_level` type, compatible with `free_shipping` (type ID 2)
   - Discount B: `free_shipping` type

2. **Test compatibility:**
   - Add Discount A to cart: Should succeed
   - Add Discount B to cart: Should succeed (they are compatible)
   - Both discounts should be applied to the cart

#### Test Case 6: Functional Test - Incompatible Discounts Cannot Be Used Together
1. **Create two discounts:**
   - Discount A: `cart_level` type, NOT compatible with `product_level`
   - Discount B: `product_level` type

2. **Test incompatibility:**
   - Add Discount A to cart: Should succeed
   - Attempt to add Discount B to cart: Should fail with compatibility error
   - Error should indicate that these discount types cannot be used together

#### Test Case 7: Invalid Type IDs in Compatibility
1. **Attempt to set compatibility with invalid type IDs:**
   ```bash
   PUT /api/discounts/{discountId}/compatibility
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "compatible_type_ids": [99999, -1]
   }
   ```

2. **Verify validation:**
   - Response status should be 400 Bad Request
   - Response should include validation errors about invalid type IDs
   - Should suggest using valid type IDs from the list endpoint

#### Test Case 8: Create Discount with Compatibility During Creation
1. **Get discount type IDs:**
   ```bash
   GET /api/discount-types
   Authorization: Bearer {api_token}
   ```

2. **Create discount with compatibility in the same request:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Cart Discount with Compatibility",
     "code": "CARTCOMP",
     "active": true,
     "information": {
       "discount_type": "cart_level"
     },
     "value": {
       "reduction": {
         "type": "percentage",
         "value": 15
       }
     },
     "usability": {
       "compatibility": {
         "compatible_type_2": true,
         "compatible_type_4": true
       }
     }
   }
   ```

3. **Verify creation:**
   - Response status should be 201 Created
   - Discount should be created with compatibility rules
   - Verify via GET request that compatibility is set correctly

#### Test Case 9: Invalid Type IDs in Discount Creation
1. **Attempt to create discount with invalid discount type:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Invalid Discount",
     "information": {
       "discount_type": "invalid_type"
     }
   }
   ```

2. **Verify validation:**
   - Response status should be 400 Bad Request
   - Response should include error about invalid discount type
   - Should suggest using valid types from the list endpoint

#### Test Case 10: API Documentation - Compatibility Rules
1. **Check API documentation:**
   - Documentation should clearly explain compatibility concept
   - Should explain that compatibility is between discount types, not between types and application types
   - Should provide examples of setting compatibility rules
   - Should document the discount-types list endpoint
   - Should document compatibility endpoints

#### Test Case 11: Error Message Clarity
1. **When compatibility validation fails, verify error message:**
   - Error message should clearly state which discount types are incompatible
   - Should reference the discount type IDs
   - Should explain that these discount types cannot be used together in the same cart
   - Should reference the specific discounts causing the issue

#### Test Case 12: Multiple Compatibility Rules
1. **Create a discount compatible with multiple types:**
   ```bash
   POST /api/discounts
   Authorization: Bearer {api_token}
   Content-Type: application/json
   
   {
     "name": "Multi-Compatible Discount",
     "code": "MULTICOMP",
     "active": true,
     "information": {
       "discount_type": "cart_level"
     },
     "value": {
       "reduction": {
         "type": "percentage",
         "value": 10
       }
     },
     "usability": {
       "compatibility": {
         "compatible_type_2": true,
         "compatible_type_3": true,
         "compatible_type_4": true
       }
     }
   }
   ```

2. **Verify multiple compatibility:**
   - Discount should be compatible with all three types
   - Can be used together with discounts of types 2, 3, and 4
   - Verify via GET request that all compatibility rules are set

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.1.x
| Description?      | - Refacto Discount CQRS, merge conditions back into Add/update commands<br>- Handle compatible types in CQRS commands/queries<br>- Improve naming of certain fields<br>- For product level discount handle reduction by amount for cheapest product and product segment<br>- The command no longer exposes the `reduction_product` weird column anymore, instead we have explicite methods like `setCheapestProduct`, `setReductionProductId` not based on weird integer negative values<br>- Partial update works for discount conditions<br>- Improve validation (reduction amoun/percent cannot collide, product level target options cannot collide but at least one is required, all associations entities existence is checked, ...)
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green and UI tests green, discount form compatible types still work
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/20966324424
| Fixed issue or discussion?     | Fixes #38741 Fixes #39992 Fixes #39993 Fixes #40283 Fixes #40285 Fixes #40284
| Related PRs       | https://github.com/PrestaShop/ps_apiresources/pull/131
| Sponsor company   | ~

### CODE REVIEW

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Catalog.Feature`
    - [ ] `Cart conditions`
    - [ ] `Single customer`
    - [ ] `Specifiy discount mode`
    - [ ] `Compatible with discounts`
    - [ ] `Single product`
    - [ ] `Specific products`
- `Admin.Catalog.Help`
    - [ ] `Select which discount types this discount is compatible with.`

(Note: this is an automated message, but answering it will reach a real human)

File: src/Adapter/Discount/Update/DiscountBuilder.php [hunk 1]
```diff
@@ -58,36 +59,36 @@ public function build(AddDiscountCommand $command): CartRule
...
 
         if ($command->getDiscountType()->getValue() === DiscountType::PRODUCT_LEVEL) {
-            if ($command->getPercentDiscount()) {
-                $cartRule->reduction_percent = (float) (string) $command->getPercentDiscount();
-                $cartRule->reduction_amount = 0;
-                $cartRule->reduction_currency = 0;
-                $cartRule->reduction_tax = false;
-            }
-            $cartRule->reduction_product = $command->getReductionProduct();
+            // If cheapest product is enabled we set the specific value, if not we use 0 as the no target value
```
Comment (jolelievre) [inline src/Adapter/Discount/Update/DiscountBuilder.php]:
```php
if ($command->getDiscountType()->getValue() === DiscountType::PRODUCT_LEVEL && $command->getCheapestProduct()) {
     $cartRule->reduction_product = DiscountSettings::CHEAPEST_PRODUCT;
}
```

File: src/Adapter/Discount/Update/DiscountConditionsUpdater.php [hunk 2]
```diff
@@ -129,7 +147,25 @@ private function applyProductConditions(
...
         array $productRuleGroups,
     ): array {
-        $this->cleanDiscountProductRules($discount);
+        // First clear all product rules (meaning if empty array is provided in this method, they are removed and no
+        // new one is created, which is used to remove product conditions)
+        $updatableProperties = $this->cleanDiscountProductRules($discount);
+
+        // Check that the product rules really target products, if not we don't apply them to avoid
+        // creating empty rule groups
+        $containsRules = false;
```
Comment (jolelievre) [inline src/Adapter/Discount/Update/DiscountConditionsUpdater.php]: Use trit here instead

**Review by tleon — APPROVED** [review]

File: src/Adapter/Discount/Trait/ProductConditionsTrait.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+    /**
+     * @param ProductRuleGroup[] $productConditions
+     *
+     * @return bool
+     */
+    public function isSegmentTargeted(array $productConditions): bool
+    {
+        foreach ($productConditions as $productCondition) {
+            if ($productCondition->getQuantity() <= 0) {
+                break;
```
Comment (boherm) [inline src/Adapter/Discount/Trait/ProductConditionsTrait.php:46]: Isn't `continue` instead of `break` here (and same for R50)? 
Maybe I'm totally wrong, but it seems kind of weird here to me with a `break` 🤔

**Review by boherm — APPROVED** [review]
It's looks great! Just one small comment, I'm not totally sure about it 🤔

File: src/Adapter/Discount/Trait/ProductConditionsTrait.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/Discount/Trait/ProductConditionsTrait.php:46]: As we discussed break or continue should have the same behaviour anyway, because of the constraints already present in the command setters
Besides when we check at `CartRule::checkProductRestrictionsFromCart` when one group is invalid (matching no products) then the cartrule is invalid And en empty set of rules makes the group invalid, so the break makes sense

Comment (Hlavtox) [reply src/Adapter/Discount/Trait/ProductConditionsTrait.php:46]: `break` is a bit faster isn't it? If you know that processing the rest is pointless, break ends the loop directly.

**Comment by SiraDIOP** [comment]
Hello @jolelievre, 

Thanks for your PR, i tested it and it's good for me 

Capture d’écran 2026-01-14 à 19 02 29
Capture d’écran 2026-01-14 à 19 02 44

Capture d’écran 2026-01-14 à 17 50 49
Capture d’écran 2026-01-14 à 17 51 05

https://github.com/user-attachments/assets/c6d34213-9aca-4e82-83be-8d9a4bc94877

Thanks

**Review by SiraDIOP — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]
Ok for E2E Tests

**Comment by nicosomb** [comment]
thank you @jolelievre and @SiraDIOP !
