### PR TITLE
Validate image if needed first when adding new brand

### LINKED ISSUE #22737: BO - Brands page - A brand is created despite having an error during the creation
#### Describe the bug

While testing this [PR](https://github.com/PrestaShop/PrestaShop/pull/22474)

In the BO > Catalog > Brands page, A brand is created despite having an error during the creation.

#### Steps to Reproduce

1. Go to BO > Catalog > Brands page
2. Create a new Brand
3. Set all required fields
4. In the Logo field > add an image format not recognized (.svg, .webp)
5. Save
6. An alert is displayed
7. Go to the list brands page without saving
8. See error => the brand is created
9. At this step 6/ `An alert is displayed`, if you add a new image and save => you will have two brands created with same information

image

#### Additional information

* PrestaShop version: PS1769, PS1770, develop branch(1780)
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Image is validated after entity creation, we should validate it first if needed
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22737.
| How to test?      | Follow instructions from #22737 
| Possible impacts? | n/a
| Sponsor company | impSolutions

@PrestaShop/prestashop-core-developers need information if that's a correct way or we should do it differently, same problem exists for other entities 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24823)

📓 BC Breaks:

`src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php` 2nd parameter is now `ManufacturerImageUploader` instead of `ImageUploaderInterface`

### CODE REVIEW

File: src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php [hunk 1]
```diff
@@ -43,17 +43,17 @@ final class ManufacturerFormDataHandler implements FormDataHandlerInterface
      */
     private $bus;
     /**
-     * @var ImageUploaderInterface
```
Comment (matks) [inline src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:46]: Argh 😞 I see why you do this, but it would be better to rely on Interface than implementation to allow people to extend PrestaShop

The best would be to improve ImageUploaderInterface but
- it would be a BC break
- does it make sense to have `ImageUploaderInterface:: checkImageIsAllowedForUpload()` ? does it make sense? it's not the responsibility of an ImageUploader

So I 👍 the chosen solution although I wished we could keep an interface in ManufacturerFormDataHandler

File: src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php [hunk 2]
```diff
@@ -68,6 +68,13 @@ public function create(array $data)
             $data['shop_association'] = [];
         }
 
+        /** @var UploadedFile $uploadedLogo */
+        $uploadedLogo = $data['logo'];
+
+        if ($uploadedLogo instanceof UploadedFile) {
```
Comment (matks) [inline src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:74]: Should we add the validation in `update(array $data)` too?

**Review by matks — APPROVED** [review]
I approve the chosen solution

File: src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php (hunk 2 above)
Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:74]: No need, it's handled inside `ImageUploader::upload`

File: src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php (hunk 1 above)
Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:46]: Good point. We have for example `CategoryMenuThumbnailUploader` where we don't use `AbstractImageUploader` so there's no validation based on `UploadedFile`, I think changing this interface will require a little restructuration of upload in these places.

In the end, this is a bug fix so maybe we could afford to have BC Break here.

File: src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php [hunk 3]
```diff
@@ -43,17 +43,17 @@ final class ManufacturerFormDataHandler implements FormDataHandlerInterface
...
 
     /**
      * @param CommandBusInterface $bus
-     * @param ImageUploaderInterface $imageUploader
+     * @param ManufacturerImageUploader $imageUploader
      */
     public function __construct(
         CommandBusInterface $bus,
-        ImageUploaderInterface $imageUploader
+        ManufacturerImageUploader $imageUploader
```
Comment (Progi1984) [inline src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:56]: BC Break, please document

**Review by Progi1984 — COMMENTED** [review]
Please document the BC Break

File: src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php (hunk 3 above)
Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:56]: Is it a BC Break though?

Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataHandler/ManufacturerFormDataHandler.php:56]: Nevermind, it is ;D

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1fvnhCObjjdw-1psRA86i7VGyhaKF7ffX/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @khouloudbelguith
