### PR TITLE
Handle parallel updates from CartRules when updating a product in Order

### LINKED ISSUE #22004: BO - Order page - An error is displayed when decreasing the gifted product quantity "Could not find the product in cart, meaning Order and Cart are out of sync"
#### Describe the bug

In the BO > Orders page > Order details page > An error is displayed when decreasing the gifted product quantity "Could not find the product in the cart, meaning Order and Cart are out of sync"

#### Steps to Reproduce

1. Create a cart rule "free gift demo_12" without code
image
2. Go to FO
3. Add demo_12 to the cart (free gift well added)
image
4. Continue checkout
5. Place Order
6. Go to BO > Order page >Last order created
image
7. Decrease the quantity of the product from 2 to 1 and save
8. See error
image
9. Refresh the page: The quantity is updated in the product line, so is the price. But the summary is not updated.
10. Change the status of the order to "Payment accepted": The invoice only has the quantity updated, but not the total prices
11. Go to FO > Customer orders > Order details: The quantity is updated, but not the total prices.

PS:1768 => ok 
https://drive.google.com/file/d/1zokwIsVqnDwie65aI_tUcm8E1_5E15Ct/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build4, 177x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | We handled the update of other products when a product was deleted But it turns out it can also happen when a product is edited So we now handle this behaviour as well but to simplify the computation a new `CartProductsComparator` has been introduced
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22004
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22013)

### CODE REVIEW

File: src/Core/Cart/Comparator/CartProductsComparator.php [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+
+namespace PrestaShop\PrestaShop\Core\Cart\Comparator;
+
+use Cart;
+
+/**
+ * This class snapshots a cart when it's created, you can then ask for the difference
+ * that happened on this cart.
+ */
+class CartProductsComparator
```
Comment (jolelievre) [inline src/Core/Cart/Comparator/CartProductsComparator.php]: @PrestaShop/prestashop-core-developers Do you think this should rather be in the `Adapter` namespace?

**Review by jolelievre — COMMENTED** [review]
This is a WIP, missing parts:
- unit tests for CartProductsComparator
- the PR #21994 should be merged first because the status of an empty order should not be `Canceled` in this case, so this PR will need to be rebased

File: src/Core/Cart/Comparator/CartProductsComparator.php (hunk 1 above)
Comment (eternoendless) [reply src/Core/Cart/Comparator/CartProductsComparator.php]: Yes

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Cart/Comparator/CartProductsComparator.php [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+
+    /**
+     * @param array $products
+     * @param array $searchedProduct
+     *
+     * @return array|null
+     */
+    private function getMatchingProduct(array $products, array $searchedProduct): ?array
+    {
+        return array_reduce($products, function ($carry, $item) use ($searchedProduct) {
```
Comment (matks) [inline src/Adapter/Cart/Comparator/CartProductsComparator.php:199]: `array_reduce`? are you a data scientist :trollface: ?

**Review by matks — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

File: classes/Cart.php [hunk 3]
```diff
@@ -1754,15 +1758,17 @@ public function deleteProduct(
...
-            return Db::getInstance()->execute(
-                'UPDATE `' . _DB_PREFIX_ . 'cart_product`
-                SET `quantity` = ' . (int) $preservedGifts[(int) $id_product . '-' . (int) $id_product_attribute] . '
-                WHERE `id_cart` = ' . (int) $this->id . '
-                AND `id_product` = ' . (int) $id_product .
-                ($id_product_attribute != null ? ' AND `id_product_attribute` = ' . (int) $id_product_attribute : '')
-            );
+        if ($preserveGiftsRemoval) {
+            $preservedGifts = $this->getProductsGifts($id_product, $id_product_attribute);
+            if ($preservedGifts[(int) $id_product . '-' . (int) $id_product_attribute] > 0) {
```
Comment (kpodemski) [inline classes/Cart.php]:
```suggestion
            if (isset($preservedGifts[(int) $id_product . '-' . (int) $id_product_attribute]) && $preservedGifts[(int) $id_product . '-' . (int) $id_product_attribute] > 0) {
```

I think @PierreRambaud would appreciate that :)

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 4]
```diff
@@ -152,40 +154,52 @@ public function handle(AddProductToOrderCommand $command)
                 $combination
             );
 
-            $oldProducts = $cart->getProducts(true);
+            $cartComparator = new CartProductsComparator($cart);
             $this->addProductToCart($cart, $product, $combination, $command->getProductQuantity());
-            $newProducts = $cart->getProducts(true);
+            $updatedCartProducts = $cart->getProducts(true);
+
+            // We get all the modification (creation AND updates) and then filter them
```
Comment (kpodemski) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:161]: @jolelievre hmm, you mean:

we get all the modifications (newly added AND updated products from cart)?

File: classes/Cart.php [hunk 5]
```diff
@@ -1331,7 +1332,8 @@ public function updateQty(
         $id_address_delivery = 0,
         Shop $shop = null,
         $auto_add_cart_rule = true,
-        $skipAvailabilityCheckOutOfStock = false
+        $skipAvailabilityCheckOutOfStock = false,
+        $preserveGiftRemoval = true
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
        bool $preserveGiftRemoval = true
```

File: classes/Cart.php [hunk 6]
```diff
@@ -1402,7 +1404,7 @@ public function updateQty(
         Hook::exec('actionCartUpdateQuantityBefore', $data);
 
         if ((int) $quantity <= 0) {
-            return $this->deleteProduct($id_product, $id_product_attribute, (int) $id_customization);
+            return $this->deleteProduct($id_product, $id_product_attribute, (int) $id_customization, (int) $id_address_delivery, (bool) $preserveGiftRemoval);
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
            return $this->deleteProduct($id_product, $id_product_attribute, (int) $id_customization, (int) $id_address_delivery, $preserveGiftRemoval);
```

File: classes/Cart.php [hunk 7]
```diff
@@ -1445,7 +1447,7 @@ public function updateQty(
                 if ($cartFirstLevelProductQuantity['quantity'] <= 1
                     || $cartProductQuantity['quantity'] - $quantity <= 0
                 ) {
-                    return $this->deleteProduct((int) $id_product, (int) $id_product_attribute, (int) $id_customization);
+                    return $this->deleteProduct((int) $id_product, (int) $id_product_attribute, (int) $id_customization, (int) $id_address_delivery, (bool) $preserveGiftRemoval);
```
Comment (Progi1984) [inline classes/Cart.php]:
```suggestion
                    return $this->deleteProduct((int) $id_product, (int) $id_product_attribute, (int) $id_customization, (int) $id_address_delivery, $preserveGiftRemoval);
```

File: classes/Cart.php (hunk 3 above)
Comment (Progi1984) [reply classes/Cart.php:1763]: In this case, i will replace by a `!empty`

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 8]
```diff
@@ -152,40 +154,52 @@ public function handle(AddProductToOrderCommand $command)
...
-                $oldProducts,
-                $newProducts,
-                $product,
-                $combination,
-                $command
-            );
+                // Now we check if the update is about the currently added product This is important for multi invoice orders, in case
+                // the added product was already in previous invoices
+                $cartCombinationId = null !== $cartProductUpdate->getCombinationId() ? $cartProductUpdate->getCombinationId()->getValue() : 0;
+                $combinationId = null !== $combination ? $combination->id : 0;
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]:
```suggestion
                $combinationId = null !== $combination ? (int) $combination->id : 0;
```

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks but very good job

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 4 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:161]: Yes, and then loop through them because even a modification of the product added by the command must be considered as a creation (to add a new OrderDetail)
But the `CartProductsComparator` can't know that, and I didn't find an elegant way to make it manage this, so I prefer to handle this specific case in this specific handler

**Review by Progi1984 — APPROVED** [review]

File: src/Adapter/Cart/Comparator/CartProductsComparator.php [hunk 9]
```diff
@@ -0,0 +1,210 @@
...
+    /**
+     * Returns a list of all products that were updated compared to the creation of this object.
+     *
+     * @param array[] $newProducts
+     *
+     * @return CartProductUpdate[]
+     */
+    private function getAllUpdatedProducts(array $newProducts): array
+    {
+        $updatedProducts = [];
```
Comment (atomiix) [inline src/Adapter/Cart/Comparator/CartProductsComparator.php:141]:
```suggestion
        $updatedProducts = [];
        $deltaQuantity = 0;
```

**Review by matks — APPROVED** [review]

File: src/Adapter/Order/Refund/OrderProductRemover.php [hunk 10]
```diff
@@ -126,7 +126,7 @@ private function updateCart(Cart $cart, OrderDetail $orderDetail): array
             null,
             true,
             false,
-            false // Do not preserve git removal
```
Comment (matthieu-rolland) [inline src/Adapter/Order/Refund/OrderProductRemover.php]: good fix, removing git could be problematic :trollface:

**Review by matthieu-rolland — APPROVED** [review]

File: src/Adapter/Cart/Comparator/CartProductsComparator.php (hunk 9 above)
Comment (jolelievre) [reply src/Adapter/Cart/Comparator/CartProductsComparator.php:141]: Not useful since `$deltaQuantity` is correctly reset in all loop iterations (if/else) No risk to keep a former value

Comment (atomiix) [reply src/Adapter/Cart/Comparator/CartProductsComparator.php:141]: My bad, I read `$deltaQuantity -= (int) $oldProduct['cart_quantity'];` instead of `$deltaQuantity = -(int) $oldProduct['cart_quantity'];` 🤦‍♂️
We're all good then!

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !! The PR seems to correctly fix #22004 
Thanks @jolelievre !!

**Comment by Progi1984** [comment]
Thanks @jolelievre & @SD1982
