### PR TITLE
Increase quantity when adding an already added product when creating order

### LINKED ISSUE #18199: BO - New order page - an exception is displayed when we double click on the "Add to cart" button
#### Describe the bug

In the BO => New order page (migrated), an exception is displayed when we double click on the "Add to cart" button.
image

#### Expected behavior

The quantity of the product must be increased and no exception displayed.
We can click on the "Add to cart" button multiple times.
It is Ok on the legacy page.

#### Steps to Reproduce

1. Go to BO => Order page `shop.com/admin-dev/sell/orders/orders`
2. Click on `Add new order` button
3. Choose a customer
4. Search for a product
5. Click add to cart => OK
6. Click add to cart again
7. see error

**Screenshots**
[Untitled_ Mar 18, 2020 2_22 PM.webm.zip](https://github.com/PrestaShop/PrestaShop/files/4349168/Untitled_.Mar.18.2020.2_22.PM.webm.zip)

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Increase quantity when adding an already added product when creating order
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18199
| How to test?  | 1. Go to BO => Order page shop.com/admin-dev/sell/orders/orders<br>2. Click on Add new order button<br>3. Choose a customer<br>4. Search for a product<br>5. Click add to cart => OK<br>6. Click add to cart again<br>7. Quantity should have been increased without any error message

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18208)

### CODE REVIEW

File: src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php [hunk 1]
```diff
@@ -66,27 +67,31 @@ public function __construct(
      */
     public function handle(AddProductToCartCommand $command): void
     {
-        $quantity = $command->getQuantity();
-        $this->assertQuantityIsPositiveInt($quantity);
-
         $cartIdValue = $command->getCartId()->getValue();
         $productIdValue = $command->getProductId()->getValue();
-        $combinationId = $command->getCombinationId();
+        $combinationId = $command->getCombinationId() ? $command->getCombinationId()->getValue() : null;
```
Comment (Arman-Hosseini) [inline src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]:
```suggestion
        $combinationId = $command->getCombinationId() instanceof CombinationId ? $command->getCombinationId()->getValue() : null;
```

Comment (Progi1984) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: :+1:

**Review by Progi1984 — COMMENTED** [review]
A small change. Thank @Arman-Hosseini for the review ;)

File: src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php (hunk 1 above)
Comment (atomiix) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: @Arman-Hosseini As `getCombinationId()` is returning a `CombinationId` (explicitly said by the method signature) I don't see why I should check for that? I could understand being more strict by checking for `null` though. Am I missing something? 🙂

Comment (PierreRambaud) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: Agree with you @atomiix, but maybe better to be explicit here and check for not `null` 
```suggestion
        $combinationId = $command->getCombinationId() !== null ? $command->getCombinationId()->getValue() : null;
```
From:
```
public function getCombinationId(): ?CombinationId
```

Comment (Arman-Hosseini) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: @atomiix For clarity it's better to compare it with the type that ultimately returns.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
see comment

File: src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php (hunk 1 above)
Comment (atomiix) [reply src/Adapter/Cart/CommandHandler/AddProductToCartHandler.php]: @Arman-Hosseini @PierreRambaud I added a check for `null` like @PierreRambaud suggested.

**Review by PierreRambaud — APPROVED** [review]

**Review by Arman-Hosseini — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
I validate because the bug fix is valid but I think that calling AddProductToOrder when product is already in order is not valid.

**Comment by SD1982** [comment]
This PR correctly fix #18199 . Thanks @atomiix

**Comment by Progi1984** [comment]
Thanks @atomiix
