### PR TITLE
Fix lang table multi-store data issue

### LINKED ISSUE #9606: [BOOM-5828] Categories and products are created for all shops instead of current in multishop configuration
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5828).

- _**Reporter:**_ fortuner
- _**Created at:**_ Tue, 26 Jun 2018 14:19:29 +0200

<p>1. Create Prestashop instance with several shops in multishop group.<br/>
2. Then select certain shop context in shop list dropdown.<br/>
3. Create a category. Check only desired shop association.<br/>
4. Look in database, ps_category and ps_category_lang<br/>
Despite the current shop context and only one desired shop checked in association list, tables have an entry for each shop.<br/>
correct me, if this is expected behavior, but seems to me a bug. And also floods database with unrelated data. I.e. If you have four shops with two languages, data will be copied 8 (!!!) times.</p>
        
* How to reproduce the issue ?

1. Create Prestashop instance with several shops in multishop group.
<br/>
2. Then select certain shop context in shop list dropdown.
<br/>
3. Create a category. Check only desired shop association.
<br/>
4. Look in database, ps_category and ps_category_lang
<br/>
Despite the current shop context and only one desired shop checked in association list, tables have an entry for each shop.
<br/>
correct me, if this is expected behavior, but seems to me a bug. And also floods database with unrelated data. I.e. If you have four shops with two languages, data will be copied 8 (!!!) times.

### PR DESCRIPTION
**Pull request by Dan-Orchard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | With a multi-store set up, adding a product or category to an individual store will put a line for each of the stores into the object_lang table.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9606
| How to test?  | Create a multi-store - Create a category/product in an individual store - only lines with associated stores will be added to object_lang table rather than for all stores.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11876)

### CODE REVIEW

File: classes/ObjectModel.php [hunk 1]
```diff
@@ -542,6 +542,8 @@ public function add($auto_date = true, $null_values = false)
             if (count($this->id_shop_list)) {
                 $id_shop_list = $this->id_shop_list;
             }
+        } else {
+            $id_shop_list = Shop::getCompleteListOfShopsID();
```
Comment (Quetzacoalt91) [inline classes/ObjectModel.php]: You should actually write this affectation before `if (Shop::isTableAssociated($this->def['table'])) {`.

Because if `(count($this->id_shop_list))` is false, you will have an undefined variable.

Comment (Dan-Orchard) [reply classes/ObjectModel.php]: I agree, changed

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @Dan-Orchard
