### PR TITLE
Fix preview mode for combination products

### LINKED ISSUE #37652: [Bug] Product preview returns AJAX error
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When product is disabled and click on preview mode, select another combination different from default and AJAX returns an error.

Tested on a fresh install PS 8.2 with php 8.1

### Expected behavior

Should work accordingly

### Steps to reproduce

1. Disable product
2. Click on preview
3. Select another combination
4. Error undefined appears

### PrestaShop version(s) where the bug happened

8.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Add `adtoken` and `id_employee` to url on switching combination in previewed product.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #37652
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/13048397639
| Fixed issue or discussion?     | Fixes #37652
| Related PRs       | ~
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by mattgoud — DISMISSED** [review]

File: themes/_core/js/product.js [hunk 1]
```diff
@@ -136,6 +136,9 @@ function updateProduct(event, eventType, updateUrl) {
 
   if (preview !== null) {
     preview = `&preview=${preview}`;
```
Comment (Hlavtox) [inline themes/_core/js/product.js]: This line is now extra. :-)

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -544,7 +544,11 @@ public function displayAjaxRefresh()
                 false,
                 false,
                 true,
-                $this->isPreview() ? ['preview' => '1'] : []
+                $this->isPreview() ? [
+                    'preview' => '1',
+                    'id_employee' => Tools::getValue('id_employee'),
+                    'adtoken' => Tools::getValue('adtoken'),
```
Comment (Hlavtox) [inline controllers/front/ProductController.php:550]: Will these variables be in the url all the time? Are there cases when there is only preview=1? (Not sure from memory how it works if the product is active. We need the token only for disabled products that show error page.)

File: themes/_core/js/product.js (hunk 1 above)
Comment (boherm) [reply themes/_core/js/product.js]: Woops, I will recheck that tomorrow. Nice catch!

File: controllers/front/ProductController.php (hunk 2 above)
Comment (boherm) [reply controllers/front/ProductController.php:550]: If the product is active, we don't need these 3 variables on the url. But, for preview of products, we need them all.
Unfortunately, for the use case of combination product and when we switch the combination of the product, we don't send these variables that's cause a rejecting of the ajax query.

Comment (Hlavtox) [reply controllers/front/ProductController.php:550]: Yep, it should work. The pair of three should be there if it's a preview.

**Review by Hlavtox — APPROVED** [review]
Should work correctly. :-)

**Review by jolelievre — APPROVED** [review]

**Review by mattgoud — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @boherm,

I tested your PR but as you see, the problem still seems to be there:

https://github.com/user-attachments/assets/88b7eb90-6619-4908-aeb6-a4c2e34db12f


Can you check that?

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @boherm,

I tested your and it's good for me!

Thanks!

https://github.com/user-attachments/assets/cff2f169-d573-4f42-8fb0-1a57589bbdd2

**Review by paulnoelcholot — APPROVED** [review]
