### PR TITLE
Fix bug with all shops context in WebService

### LINKED ISSUE #12412: With Multistore enabled, API calls are redirected to homepage
I'm on prestashop 1.6.1.14 and I've enabled multistore. When I try to access the api through the url of my B2B shop, nothing happens and it redirects to the homepage. 

For my B2C shop it works but when I go to https://my-shop.com/api/products?id_shop=all it redirects to the homepage with this url https://my-shop.com/?url=products%2F 

The redirect rules in my .htaccess are exactly the same for my two url shops.

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In this PR I introduce a new constant `_PS_API_IN_USE_` to allow PrestaShop to detect calls to webservice in multistore and avoid redirecting them.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #12412
| Related PRs       | 
| How to test?      | Follow instructions in issue report
| Possible impacts? |

### CODE REVIEW

File: classes/shop/Shop.php [hunk 1]
```diff
@@ -396,7 +396,7 @@ public static function initialize()
             Configuration::getMultiShopValues('PS_MEDIA_SERVER_3')
         );
 
-        if ((!$id_shop && defined('_PS_ADMIN_DIR_')) || Tools::isPHPCLI() || in_array($http_host, $all_media)) {
+        if ((!$id_shop && defined('_PS_ADMIN_DIR_')) || ('all' === $id_shop && defined('_PS_API_IN_USE_') && _PS_API_IN_USE_) || Tools::isPHPCLI() || in_array($http_host, $all_media)) {
```
Comment (PululuK) [inline classes/shop/Shop.php]: I suggest to use vars to improve the code readability 
Something like :

```php
$isAllShop = 'all' === $id_shop;
$isApiInUse = defined('_PS_API_IN_USE_') && _PS_API_IN_USE_;
```

Comment (Prestaworks) [reply classes/shop/Shop.php]: I updated the commit with your suggestions.

**Review by matks — APPROVED** [review]
Hello @Prestaworks and thank you for the PR! Apologies for the late review; these last weeks we have been focused on [PrestaShop 8 freeze](https://build.prestashop.com/news/prestashop-feature-freeze-v8/) so we're very late in processing contributions.

I improved a bit the PR description 😉 

For me the code is valid. But I have one question: because of the bug, today nobody can use the webservice in multistore, right? Then if we merge your PR we remove the bug. But do we know if webservices work with multistore ? 😄 I wonder if we have opened a door but behind the door the stuff is broken

**Comment by Prestaworks** [comment]
> 

it's possible to use in multistore, but when creating a size like "Large" for instance, you can't create it for all shops, only for one specific shop at a time. and that will create multiple entries with different IDs.

**Review by matks — COMMENTED** [review]
Thank you for your answer @Prestaworks and my apologies for late answer. I add 'waiting for QA' label so that QA tests this contribution.

**Comment by matks** [comment]
Woups I thought this was the PSWebservice repo (1 approval is enough).

Ping @PrestaShop/committers this PR needs a 2nd approval to move forward :)

**Review by marsaldev — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Prestaworks ,

Tested the following:
- Single store & multistore (with 2 groups)
- Enabling of webservice
- Creation of webservice for a specific store
- Creation of webservice for all store
- Creation of specific product for a specific store
- Switched from single to multistore a few times
- Tested only the GET method.

My shop architecture:
- group default
  - shop1
  - shop2
- second group
  - shop3

Created webservices for all of the shops, no more redirection to `myshop.com/api/products?url=products` when accessing `myshop.com/api/products&id_shop=all`
Each webservice created for each shop has its products.

https://user-images.githubusercontent.com/16019289/196638647-e5ec466e-2c3f-402c-84d2-8a1659845d6c.mov

Well noted for what you said in the comment : 

> you can't create it for all shops, only for one specific shop at a time

For instance, it is QA ✅

**Comment by atomiix** [comment]
Thanks @Prestaworks & @florine2623
