### PR TITLE
Fix combination deletion error

### LINKED ISSUE #24389: BO - Open a combination that has been deleted on product V2
@MatShir @TristanLDD I encountered a problem we didn't think about when trying to access a combination that doesn't exist any more in the modal (because it was deleted in another page). I had a big ugly error, so this is fixed but don't have a regular not found template, so I made one inspired by the 500 one but it's worth some additional love from both of you ^^

Especially regarding:
- the wording
- the error image
- do we keep the same buttons as CTA
- one thing weird (already present in the previous 500 page) The "Enable debug mode" button is always present if if the debug mode is enabled

Here's the look of what I did for now:

Capture d’écran 2021-05-06 à 19 01 18

To avoid blocking this PR too long (and the QA for 178), if it needs a deep reflection I'd suggest merging this for now and improve it in another PR.
## Specs

For me here the best solution would be: 
**IF**

- the user clicks on a combination from the list that doesn't exist anymore

- the user has already the pop in opened, but the combination doesn't exist and saves his edited

- the user goes to the next combination that was deleted before or the user does to the combination selected from the history

**THEN** 

It opens an error modal with an error message and the button 'close and refresh' (on top of the combination modal or close the combination modal first).
## Design 

Hello, here is the link for the modal's mockups: 

https://www.figma.com/file/aCBf2HlypjT0ZxP2XcsT68/Core-Github-issues?node-id=1507%3A11496

I would prefer to avoid overlapping modals, this one should replace the combination modal as it would be confusing to have both modals action buttons in the same time. We can reopen the combination modal after the user closed this one

comb_doesnt_exist

_Originally posted by @jolelievre in https://github.com/PrestaShop/PrestaShop/issues/24076#issuecomment-833691573_

### PR DESCRIPTION
**Pull request by margud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x 
| Description?      | New product page would show not handled error when editing deleted combination. Now we display custom popup and refresh combination list.
| Type?             | bug fix
| Category?         |  BO 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#24389](https://github.com/PrestaShop/PrestaShop/issues/24389)
| How to test?      | Open product with combinations page in 2 different tabs. In one tab delete 1 combination and in another tab try to edit it. Now you should get this popup: image And the combination list has been automatically updated to get more up to date values (which means the removed combination is not present any more), you should test what happens when the combinations have all been removed, the list should switch back to its empty state

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php [hunk 1]
```diff
@@ -27,6 +27,7 @@
 
 namespace PrestaShopBundle\Controller\Admin\Sell\Catalog\Product;
 
+use Combination;
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php]: I'm not sure you need to add this use statement considering the modification you made Even if CSfix doesn't seem to complain the less we change the better

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+            <button type="button" aria-label="Close" class="btn btn-primary" data-dismiss="modal">
+                <span>{{ 'Close and refresh'|trans({}, 'Admin.Catalog.Feature') }}</span>
+            </button>
+        </div>
+    </div>
+{% endblock %}
+
+{% block javascripts %}
+    <script src="{{ asset('themes/new-theme/public/combination_bulk.bundle.js') }}"></script>
+{% endblock %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]: With the limited content of this page I don't think you even need to include some JS here

**Review by jolelievre — COMMENTED** [review]
Thanks @margud 

Just two comments here, however the bigger issue is that you have a merge commit in you PR history which blocks the CI

Maybe try to squash the commits to get rid of this merge commit

**Review by jolelievre — DISMISSED** [review]
Thanks @margud

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * #}
+{% extends '@PrestaShop/base.html.twig' %}
+{% block stylesheets %}
+    <link rel="stylesheet" href="{{ asset('themes/new-theme/public/theme' ~ rtl_suffix ~ '.css') }}" />
+{% endblock %}
+
+{% block body %}
+    <div class="card-block">
+        <div class="row justify-content-center">
```
Comment (zuk3975) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]: all html.twig in prestashop have an indent of 2 spaces (as I see its 4 here). Should keep it consistent

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php [hunk 4]
```diff
@@ -76,9 +76,11 @@ public function editAction(Request $request, int $combinationId): Response
         try {
             $combinationForm = $this->getCombinationFormBuilder()->getFormFor($combinationId);
         } catch (CombinationNotFoundException $e) {
-            return $this->render('@PrestaShop/Admin/Exception/not_found.html.twig', [
-                'errorMessage' => $this->getErrorMessageForException($e, $this->getErrorMessages($e)),
-            ]);
+            return $this->render(
+                '@PrestaShop/Admin/Sell/Catalog/Product/Combination/not_found.html.twig',
+                [],
+                new Response('', 404)
```
Comment (zuk3975) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController.php]:
```suggestion
                new Response('', Response::HTTP_NOT_FOUND)
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+            <img src="{{ asset('themes/new-theme/img/empty_state/missing_combination.png') }}">
+        </div>
+      <div class="row justify-content-center combination-not-found-description">
+        <h2>{{ 'This combination doesn\'t exist anymore'|trans({}, 'Admin.Catalog.Feature') }}</h2>
```
Comment (Julievrz) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]:
```suggestion
        <h2>{{ 'This combination doesn\'t exist anymore'|trans({}, 'Admin.Catalog.Notification') }}</h2>
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+      </div>
+        <div class="row justify-content-center">
+            <button type="button" aria-label="Close" class="btn btn-primary" data-dismiss="modal">
+                <span>{{ 'Close and refresh'|trans({}, 'Admin.Catalog.Feature') }}</span>
```
Comment (Julievrz) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]:
```suggestion
                <span>{{ 'Close and refresh'|trans({}, 'Admin.Actions') }}</span>
```

**Review by zuk3975 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * #}
+{% extends '@PrestaShop/base.html.twig' %}
+{% block stylesheets %}
+  <link rel="stylesheet" href="{{ asset('themes/new-theme/public/theme' ~ rtl_suffix ~ '.css') }}"/>
+{% endblock %}
+
+{% block body %}
+  <div class="card-block">
+    <div class="row justify-content-center">
```
Comment (NeOMakinG) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]:
```suggestion
    <div class="justify-content-center">
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+      <img src="{{ asset('themes/new-theme/img/empty_state/missing_combination.png') }}">
+    </div>
+    <div class="row justify-content-center combination-not-found-description">
```
Comment (NeOMakinG) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]:
```suggestion
    <div class="justify-content-center combination-not-found-description">
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+      <h2>{{ 'This combination doesn\'t exist anymore'|trans({}, 'Admin.Catalog.Notification') }}</h2>
+    </div>
+    <div class="row justify-content-center">
```
Comment (NeOMakinG) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/Combination/not_found.html.twig]:
```suggestion
    <div class="justify-content-center">
```

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
`row` shouldn't be used there as there are no columns as childs

**Review by NeOMakinG — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/product/components/combination-modal/CombinationModal.vue [hunk 10]
```diff
@@ -249,6 +250,19 @@
 
         this.applyIframeStyling();
 
+        // if form is not found it means that combination is missing
+        const editionForm = iframeBody.querySelector<HTMLFormElement>(ProductMap.combinations.editionForm);
```
Comment (yanmakouf) [inline admin-dev/themes/new-theme/js/pages/product/components/combination-modal/CombinationModal.vue:254]: Since it is only used one time, maybe we can skip the const and directly test `if (!iframeBody.querySelector<HTMLFormElement>(ProductMap.combinations.editionForm)`. We can create a const later if for some reason we need a new similar call in the scope.

Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/components/combination-modal/CombinationModal.vue:254]: maybe you are right, but Neo already approved, so I think its not worth blocking PR for this little thing :wink:

**Review by zuk3975 — DISMISSED** [review]

**Review by yanmakouf — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/product/components/combination-modal/CombinationModal.vue (hunk 10 above)
Comment (yanmakouf) [reply admin-dev/themes/new-theme/js/pages/product/components/combination-modal/CombinationModal.vue:254]: Yh sure. free comment ;)

**Review by jolelievre — DISMISSED** [review]

**Review by sLorenzini — COMMENTED** [review]
hello @margud,

Thank you for this PR.
Automaticated tests are good.

Tested on 8.0.x branch with PHP 7.3.

Modal is well displayed on those scenarios:

- the user clicks on a combination from the list that doesn't exist anymore
- the user has already the pop in opened, but the combination doesn't exist and saves his edited
- the user goes to the next combination that was deleted before or the user does to the combination selected from the history 

However, the content is not centered correctly:

modal-error-combinations

Could you check please?
Waiting for your feedbacks.

Thank you

**Comment by margud** [comment]
> hello @margud,
> 
> Thank you for this PR. Automaticated tests are good.
> 
> Tested on 8.0.x branch with PHP 7.3.
> 
> Modal is well displayed on those scenarios:
> 
> * the user clicks on a combination from the list that doesn't exist anymore
> * the user has already the pop in opened, but the combination doesn't exist and saves his edited
> * the user goes to the next combination that was deleted before or the user does to the combination selected from the history
> 
> However, the content is not centered correctly:
> 
> modal-error-combinations
> 
> Could you check please? Waiting for your feedbacks.
> 
> Thank you

not sure why css logic changed, but added fix now. You can try now @sLorenzini

**Comment by Robin-Fischer-PS** [comment]
Hi @margud ,

We just need the dev's code review and we'll test your PR again. Sorry for the long delay in QA :/

Thanks!

**Review by zuk3975 — APPROVED** [review]
Ok for me 🤷‍♂️

**Review by jolelievre — APPROVED** [review]
Thanks @margud

**Review by sLorenzini — APPROVED** [review]
hello @margud 

Thank you for the fix.
Automaticated tests are good.

Tested on 8.0.x branch with PHP 7.3.

Modal is well displayed on those scenarios:

- the user clicks on a combination from the list that doesn't exist anymore
- the user has already the pop in opened, but the combination doesn't exist and saves his edited
- the user goes to the next combination that was deleted before or the user does to the combination selected from the history

[modal-combinations.webm](https://user-images.githubusercontent.com/2854834/196398456-4f28309b-da97-41fe-a97f-106d20dccefd.webm)

QA approved ✅ 

Thanks

**Comment by Progi1984** [comment]
Question before merge to @PrestaShop/prestashop-maintainers : Can we add new strings in patch version ?

**Comment by matks** [comment]
> Question before merge to @PrestaShop/prestashop-maintainers : Can we add new strings in patch version ?

Hi @Julievrz interesting question can you help us?

**Comment by Julievrz** [comment]
> > Question before merge to @PrestaShop/prestashop-maintainers : Can we add new strings in patch version ?
> 
> Hi @Julievrz interesting question can you help us?

Hi :)

We usually don't add new strings to Crowdin in patch versions to avoid translators having to translate new strings too often and to keep them motivated. It would be very discouraging to finally complete a language and have new strings pop up from nowhere.

So I'd say we don't, unless it is a very important string, a huge mistake, or there is no alternative in the existing strings.

**Comment by jolelievre** [comment]
Hi @matks and @Julievrz 

anyway, this PR is about the experimental product page, so I don't think it's such a problem if the new wordings are only handled for 8.1. We could even re-target this PR to develop, as we are doing for most of the pending PRs on product page v2, but since this one is already approved and validated I'd prefer to merge it now in 8.0.x for the next patch

If it's ok with you let's merge the PR now 🙂

**Comment by matks** [comment]
Is it OK for you @Julievrz ? Can we merge this one for the reason indicated above, knowing that anyway these strings are not production-exposed ?

**Comment by jolelievre** [comment]
Anyway we won't update the catalog right now, this wording is only on an experimental page And when we update the catalog for 8.1 it will be merged in the catalog of the 8 they will all be combined So I think we can merge this now it will only be integrated in the next catalog update for 8.1

**Comment by jolelievre** [comment]
Thanks @margud and @sLorenzini
