### PR TITLE
Cast $orderMessage['message'] as string to prevent fatal error.

### LINKED ISSUE #38602: Get order messages can produce a "must be of the type string null given" error due to strict parameter type declaration in OrderMessageForViewing constructor
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

First, I must say I found similar issues, but closed. However, this issue still alive.

View details of some orders can produce a "must be of type string, null given" fatal error.

This is because OrderMessageForViewing class constructor declares $message param as string (strinctly).
But sometimes message from an order it can be null.

### Expected behavior

Show order details page in backoffice.

### Steps to reproduce

This can be a way:

1. Start with a PrestaShop store having a lot of orders, from working several years, prior to 1.7.7.0
2. Upgrade to 1.7.7.0
3. Open orders in backoffice until you find one that trigger the error.

### PrestaShop version(s) where the bug happened

At least from 1.7.7.0 to 8.2.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

José Carlos PHP

### PR DESCRIPTION
**Pull request by josecarlosphp**
Cast $orderMessage['message'] as string, when used as $message parameter to OrderMessageForViewing() constructor, because that parameter is declared as string, but $orderMessage['message'] it can be sometimes not strictly a string.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Prevent "must be of type string" fatal error when viewing order details in BO.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Use your imagination.
| UI Tests          | Not necessary.
| Fixed issue or discussion?     | Fixes #38602
| Related PRs       | No.
| Sponsor company   | José Carlos PHP.

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @josecarlosphp!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by Hlavtox — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 1]
```diff
@@ -711,7 +711,7 @@ private function getOrderMessages(Order $order): OrderMessagesForViewing
 
             $messages[] = new OrderMessageForViewing(
                 (int) $orderMessage['id_customer_message'],
-                $orderMessage['message'],
+                (string) $orderMessage['message'],
```
Comment (Quetzacoalt91) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:714]: Correct me if I'm wrong, but it seems `message` is not supposed to be null, based on the database structure.

https://github.com/PrestaShop/PrestaShop/blob/289b9872802d214f72d72d490c729b213990bae5/install-dev/data/db_structure.sql#L668

Your fix may work, but it is likely hiding another important issue?

Comment (jolelievre) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:714]: @Quetzacoalt91 you're right but the SQL query comes from here https://github.com/PrestaShop/PrestaShop/blob/eff832703974bcef13b7ab7ad168a36c7348a48c/src/Adapter/Customer/CustomerDataProvider.php#L97 There are left joins, so I guess even if `cm.message` can never be null in the table itself, the query result can return a null value if the join doesn't match 🤔

Comment (Quetzacoalt91) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:714]: Fair enough, and no need for further investigation on the Update side.
Thanks

**Review by Quetzacoalt91 — APPROVED** [review]
Confirming my comment is solved.

**Review by AureRita — APPROVED** [review]
Hi @josecarlosphp 

Thank you for your PR, I tested it and it seems to works as you can see : 

https://github.com/user-attachments/assets/c240b38d-6877-4759-a8d5-da189ffc5099


Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you
