### PR TITLE
Grid row delete confirmation modal - Catalog > Monitoring

### LINKED ISSUE #17082: [EPIC] Add a modal to confirm or cancel delete action for one row
**Describe the bug**

Add a modal like on product list to confirm or cancel deletion of a row instead of the browser one

⚠ Add this modal **with the following message** - edited by @LouiseBonnard following https://github.com/PrestaShop/PrestaShop/issues/14462#issuecomment-508394667:

`title` = _Delete selection_ in _Admin.Actions_
`confirm_message` = _Are you sure you want to delete the selected item(s)?_ in _Admin.Global_

`confirm_button_label` = _Delete_ in _Admin.Actions_
`close_button_label` = _Cancel_ in _Admin.Actions_

---

Already migrated pages for which it must be added:
- [x] #17847 - Add a modal to confirm or cancel delete for one row [1/1] 

**Second part to do during the migration of each pages from 1.7.8**
Pages not yet migrated for which it must be added:
- [ ] Orders > Carts
- [ ] Catalog > Attributes
- [ ] Catalog > Features
- [ ] Catalog > Discounts > Cart rules
- [ ] Catalog > Discounts > Catalog price rules
- [ ] Customers > Customer service
- [ ] Design > Image settings
- [ ] Shipping > Carriers
- [ ] International > Locations > Zones
- [ ] International > Locations > Countries
- [ ] International > Locations > States
- [ ] International > Taxes > Tax rules
- [ ] International > Taxes > Tax rules > Edit a tax rule > Countries
- [ ] Shop parameters > Customer settings > Titles
- [x] Shop parameters > Order settings > Statuses : #27606
- [ ] Shop parameters > Contact > Stores
- [x] Shop parameters > Traffic & SEO > Search engines #10589
- [ ] Shop parameters > Traffic & SEO > Referrers
- [ ] Shop parameters > Search > Search
- [ ] Shop parameters > Search > Tags

**Screenshots**

capture d'écran_1723

Remove this one

capture d'écran_1724

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add a confirmation modal when deleting a row from a grid.<br> Catalog > Monitoring
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Partially Fixes #17847
| How to test?  | Go to Catalog > Monitoring in the BO, Try to delete a row, you will have a bootstrap modal to confirm deletion

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18322)

### CODE REVIEW

File: src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php [hunk 1]
```diff
@@ -187,16 +190,19 @@ protected function getRowActions()
...
+                $this->buildDeleteAction(
+                    'admin_product_unit_action',
+                    'id',
+                    'id_product',
+                    ['action' => 'delete'],
+                    [
+                        'confirm_message' => $this->trans(
+                            'Delete selected item?',
+                            [],
+                            'Admin.Advparameters.Feature'
```
Comment (LouiseBonnard) [inline src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php]:
```suggestion
                            'Admin.Notifications.Warning'
```

Comment (LouiseBonnard) [reply src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php]: Is this also a modal?

Comment (sowbiba) [reply src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php]: Yes it's a modal

**Review by Progi1984 — DISMISSED** [review]

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php [hunk 2]
```diff
@@ -36,20 +36,34 @@
...
             ->setIcon('delete')
             ->setOptions([
                 'route' => $deleteRouteName,
                 'route_param_name' => $deleteRouteParamName,
                 'route_param_field' => $deleteRouteParamField,
-                'confirm_message' => $this->trans('Are you sure you want to delete the selected item?', [], 'Admin.Notifications.Warning'),
+                'extra_route_params' => $extraRouteParams,
+                'confirm_message' => array_key_exists('confirm_message', $translations) ?
+                    $translations['confirm_message'] :
+                    $this->trans('Are you sure you want to delete the selected item?', [], 'Admin.Notifications.Warning'),
```
Comment (LouiseBonnard) [inline src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: Should we keep it singular? Issue #17847 talks about bulk action.

Comment (LouiseBonnard) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: @sowbiba, I just have this question, otherwise it's fine for me. :-)

Comment (sowbiba) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: If we can have a generic message for both Bulk and Single deletion, it's fine for me ;)

Comment (sowbiba) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: Something like **Delete selected items?**

Comment (LouiseBonnard) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]:
```suggestion
                    $this->trans('Are you sure you want to delete the selected item(s)?', [], 'Admin.Global'),
```

File: src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php [hunk 3]
```diff
@@ -187,16 +191,20 @@ protected function getRowActions()
...
-                    ])
+                $this->buildDeleteAction(
+                    'admin_product_unit_action',
+                    'id',
+                    'id_product',
+                    Request::METHOD_DELETE,
+                    ['action' => 'delete'],
+                    [
+                        'confirm_message' => $this->trans(
+                            'Delete selected item?',
```
Comment (LouiseBonnard) [inline src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php]: Can you confirm this message is displayed only when a single item is selected?

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php (hunk 2 above)
Comment (LouiseBonnard) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: Let's apply this behavior to every grid, this way it will be more consistent for the users. :-)

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php [hunk 4]
```diff
@@ -36,21 +36,35 @@
...
             ->setOptions([
                 'route' => $deleteRouteName,
                 'route_param_name' => $deleteRouteParamName,
                 'route_param_field' => $deleteRouteParamField,
-                'confirm_message' => $this->trans('Are you sure you want to delete the selected item?', [], 'Admin.Notifications.Warning'),
-                'method' => $method,
+                'extra_route_params' => $extraRouteParams,
+                'confirm_message' => array_key_exists('confirm_message', $translations) ?
+                    $translations['confirm_message'] :
+                    $this->trans('Are you sure you want to delete the selected item(s)?', [], 'Admin.Global'),
```
Comment (LouiseBonnard) [inline src/Core/Grid/Definition/Factory/DeleteActionTrait.php]:
```suggestion
                    $this->trans('Are you sure you want to delete the selected item(s)?', [], 'Admin.Notifications.Warning'),
```

Comment (LouiseBonnard) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: cf. https://github.com/PrestaShop/PrestaShop/issues/17082#issue-547496204

File: src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php (hunk 3 above)
Comment (sowbiba) [reply src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php]: Yes it's only for single deletion

**Review by Progi1984 — DISMISSED** [review]

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php (hunk 4 above)
Comment (sowbiba) [inline src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: @LouiseBonnard The default message is this one
```$this->trans('Are you sure you want to delete the selected item(s)?', [], 'Admin.Global'),```

File: src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php [hunk 5]
```diff
@@ -187,16 +191,20 @@ protected function getRowActions()
...
-                        'confirm_message' => $this->trans('Delete selected item?', [], 'Admin.Notifications.Warning'),
-                    ])
+                $this->buildDeleteAction(
+                    'admin_product_unit_action',
+                    'id',
+                    'id_product',
+                    Request::METHOD_DELETE,
+                    ['action' => 'delete'],
+                    [
+                        'confirm_message' => $this->trans(
```
Comment (sowbiba) [inline src/Core/Grid/Definition/Factory/Monitoring/AbstractProductGridDefinitionFactory.php]: ... And to override the default message, we redefine ```confirm_message``` key

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php (hunk 4 above)
Comment (LouiseBonnard) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]:
```suggestion
                    $this->trans('Are you sure you want to delete the selected item(s)?', [], 'Admin.Notifications.Warning'),
```

**Review by Progi1984 — DISMISSED** [review]

**Review by LouiseBonnard — DISMISSED** [review]

**Review by LouiseBonnard — DISMISSED** [review]

**Review by LouiseBonnard — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig [hunk 6]
```diff
@@ -39,7 +39,7 @@
 {% set extra_route_params = action.options.extra_route_params %}
 
 {% for name, field in extra_route_params %}
-  {% set route_params = route_params|merge({ (name) : (record[field]) }) %}
+  {% set route_params = route_params|merge({ (name) : (record[field] ?? field) }) %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig:42]: It reverts a regression no? Because in 177 there is already this `field` fallback

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php [hunk 7]
```diff
@@ -36,21 +36,35 @@
...
 {
-    protected function buildDeleteAction(string $deleteRouteName, string $deleteRouteParamName, string $deleteRouteParamField, string $method = 'POST'): RowActionInterface
-    {
+    protected function buildDeleteAction(
+        string $deleteRouteName,
+        string $deleteRouteParamName,
+        string $deleteRouteParamField,
+        string $method = 'POST',
+        array $extraRouteParams = [],
+        array $translations = []
```
Comment (jolelievre) [inline src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: I'm not sure it is very useful to add this `$translations` parameter
Because it's not used anywhere, so it adds complexity for no reason Not very SOLID

**Comment by SD1982** [comment]
Hello @sowbiba For this PR the modal is correctly added but Is it normal to be redirected to the product page when you delete a product ? 
https://drive.google.com/file/d/12B4-9Sv0JZWnbyLjSoo9DZOXm8CLQOCW/view?usp=sharing

File: src/Core/Grid/Definition/Factory/DeleteActionTrait.php (hunk 7 above)
Comment (sowbiba) [reply src/Core/Grid/Definition/Factory/DeleteActionTrait.php]: you are right, its no longer relevant since the wording have been made uniform

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig (hunk 6 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig:42]: @sowbiba any update on that?

Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig:42]: @jolelievre we discussed about this. the fallback you're talking about is on link.html.twig file.
Are you ok with that ?

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig (hunk 6 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig:42]: It's useful indeed, but we might have to deal with a conflict someday In case the route parameter name matches a record field name.. Do we accept it for now and think about a fix later or should we anticipate it?
ex:
``````

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig:42]: ex:

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Actions/Row/submit.html.twig:42]: ex:

```php
$record = [
  'id' => 15,
  'name' => 'toto',
  'action' => 'deliver',
];
```

```yaml
route:
   some_route:
       url: /my_route/{action}
```

If we want to specify the route with a specific parameter `action` it will use the record field, not the option from the row action

**Review by LouiseBonnard — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @sowbiba i have a exception while trying to delete an element from any of the monitoring list.
The exception appear after click on the delete button in the cofirmation modal

capture d'écran_46

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM the modal is correctly added and the exception is not displayed anymore . Thanks @sowbiba !

**Comment by Progi1984** [comment]
Thanks @sowbiba
