### PR TITLE
Fix missing AdminSecurity for 8.1.x

### LINKED ISSUE #32575: Fix missing AdminSecurity annotations for 8.1.0
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Release task

This is one of the last steps to do for 8.1.0 Release Candidate.

This ticket is about performing this step from the https://www.prestashop-project.org/maintainers-guide/processes/release/prestashop/preliminary-tasks/ process.

The Command `php bin/console prestashop:linter:security-annotation find-missing` helps us finding controllers that do NOT have the Annotation `@AdminSecurity()` needed to secure them. This is a [system](https://devdocs.prestashop-project.org/8/development/architecture/modern/controller-routing/#how-does-this-work) which uses back-office user privileges to check if user can access a given controller action.

For some controllers that is expected: it is because they are either fully open or are protected using something else than `@AdminSecurity()`.

## What to do

It is necessary, to make sure 8.1.0 Release Candidate is secure, to go through the list below (this is the output of the Command, when run on `8.1.x` branch) and verify for each line:
- is it expected that this Controller has no `@AdminSecurity`; is it because it is an expected exception to the rule
- if not, please add the missing `@Security()` annotation (see example PR https://github.com/PrestaShop/PrestaShop/pull/21190/)

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Before publishing 8.1.0 Release Candidate, I fix some missing `@AdminSecurity` annotations to secure Symfony controllers. See below for details
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Please see below. Also we need CI ✅ & [auto tests](https://github.com/boherm/ga.tests.ui.pr/actions/runs/5002456044) ✅
| Fixed ticket?     | Fixes #32575 
| Related PRs       | 
| Sponsor company   | 

### New API controllers

Controllers
- Configure/AdvancedParameters/AuthorizationServer/ApiAccessController.php
- Configure/AdvancedParameters/AuthorizationServer/ApplicationController.php
were not secured. I fix this. But they are not implemented so it was not a real problem. No need to test, no impact.

### Backoffice translations page

The controller action in charge of rendering the page (other actions are done by ajax endpoints connected to a VueJS application) was not secured. I fix this.

### Backoffice product page v1

Some ProductController actions for the listing were not secured. I fix this.

Multiple ProductImageController.php actions, used to edit & upload images in the backoffice Product Page V1, were not secured. This is because they receive and return JSON, and `AdminSecurity()` does not handle JSON. But leaving these unprotected is worse, so it's better to add the annotation to secure them. Same for VirtualProductController.

### Unfinished Symfony pages

Some Symfony pages not yet completed (= work in progress) were not secured. Annotation was added to them although they have no impact, it's a nice-to-have. Examples: CountryController, CarriersController. No need to test, no impact.

## How to test

Please verify that:

1.  The "translations" backoffice symfony page
- can be accessed by users which are granted correct READ access [through the backoffice Permissions page](https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/advanced-parameters/team/permissions)
- cannot be accessed by users without these rights
2. The backoffice product page v1
- can be accessed by users which are granted correct READ access [through the backoffice Permissions page](https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/advanced-parameters/team/permissions)
- can be used (= create, edit) by users which are granted correct WRITE access through the backoffice Permissions page
- cannot be accessed by users without these rights

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php [hunk 1]
```diff
@@ -157,6 +157,8 @@ public function configureModuleAction($module_name)
     }
 
     /**
+     * @AdminSecurity("is_granted('create', 'ADMINMODULESSF_') || is_granted('update', 'ADMINMODULESSF_') || is_granted('delete', 'ADMINMODULESSF_')")
```
Comment (mflasquin) [inline src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: Are you sure about the "ADMINMODULESSF_" ?

Comment (FabienPapet) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: The name is correct

**Review by FabienPapet — DISMISSED** [review]
LGTM

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php (hunk 1 above)
Comment (boherm) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: Yes, I'm pretty sure of it, and that's why I can't use unfortunately a `request.get('_legacy_controller')` on this controller. 🫤

File: src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php [hunk 2]
```diff
@@ -55,6 +55,29 @@ final class SecurityAnnotationLinterCommand extends Command
      */
     private $securityAnnotationLinter;
 
+    /**
+     * @var array
+     */
+    private const EXCEPTION_ROUTES = [
```
Comment (matks) [inline src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php:61]: Good thing 👍

File: src/PrestaShopBundle/Controller/Admin/CategoryController.php [hunk 3]
```diff
@@ -49,6 +50,8 @@ class CategoryController extends FrameworkBundleAdminController
     /**
      * Process Ajax Form to add a simple category (name and parent category).
      *
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller'))")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/CategoryController.php]: If I am not wrong, this route was used by Product Page V1 to create categories from inside the product page. There is a button "Create a category", it's a shortcut to avoid asking the user to go to "Create a category" backoffice page, it allows user to do it without leaving the product page. As this controller has been deprecated in 8.1 I guess we don't really care if it's 100% OK.

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccessController.php [hunk 4]
```diff
@@ -38,6 +39,9 @@
  */
 class ApiAccessController extends FrameworkBundleAdminController
 {
+    /**
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller'))")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AuthorizationServer/ApiAccessController.php:43]: This route and other must be checked by @mflasquin who worked on these new Symfony pages 😉 .

@mflasquin as you already reviewed I guess it means that's OK for you?

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ShopController.php [hunk 5]
```diff
@@ -42,6 +43,8 @@ class ShopController extends FrameworkBundleAdminController
     /**
      * Search for shops by query.
      *
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller')) || is_granted('delete', request.get('_legacy_controller')) || is_granted('read', request.get('_legacy_controller'))")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ShopController.php]: This route is used by the Multistore header (it was introduced in https://github.com/PrestaShop/PrestaShop/pull/21593). It can be called on any backoffice page, so I think this security is going to break the behavior.

It's a route that can be called by any controller, on any backoffice page so ... I guess it cannot be secured ? :/

File: src/PrestaShopBundle/Controller/Admin/FeatureController.php [hunk 6]
```diff
@@ -38,6 +39,8 @@ class FeatureController extends FrameworkBundleAdminController
     /**
      * Get all values for a given feature.
      *
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller')) || is_granted('read', request.get('_legacy_controller'))")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/FeatureController.php]: Same here: deprecated so OK

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 7]
```diff
@@ -395,6 +395,8 @@ private function getToolbarButtons()
      * Create a new basic product
      * Then return to form action.
      *
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller'))")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php]: This is the product page V1. I am not sure at all :/ that the `_legacy_controller` property will be set correctly in that backoffice page. I think we should not put AdminSecurity on Page Product V1 controllers :/

**Review by matks — COMMENTED** [review]
Hello and thank you for your work!

I think 2 people should validate this PR
- @mflasquin for annotations on backoffice pages related to new backoffice API
- @jolelievre or @zuk3975 for annotations on backoffice pages related to page product v1 and v2

Thank you for performing this tedious work 😉 you have found plenty unsecure endpoints

File: src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php [hunk 8]
```diff
@@ -55,6 +55,29 @@ final class SecurityAnnotationLinterCommand extends Command
...
+        'admin_common_notifications',
+        'admin_common_notifications_ack',
+        'admin_common_pagination',
+        'admin_common_sidebar',
+        'admin_common_reset_search',
+        'admin_common_reset_search_by_filter_id',
+        'admin_security_compromised',
+        'admin_get_ajax_categories',
+        'admin_product_list', // Deprecated products v1
```
Comment (jolelievre) [inline src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php]: These ones are deprecated but still effective in 8.1 since the v2 can be disabled So they should be fixed as well Even though they've been incorrect for a long time since we aim at fixing all required routes they should also be fixed

File: src/PrestaShopBundle/Controller/Admin/CategoryController.php (hunk 3 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/CategoryController.php]: Same comment as above, deprecated is not removed In 9.0 we don't care as it will be removed but in 8.1 it should have as much attention as the other controllers And I wonder if we should we should also add `is_granted('update', request.get('AdminProducts'))` 🤔 But maybe not, permission to edit product doesn't mean you're allowed to edit/create categories

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ShopController.php (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ShopController.php]: Hmmm I guess you're right

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php [hunk 9]
```diff
@@ -115,6 +115,8 @@ public function importAction(Request $request)
     /**
      * Handle import file upload via AJAX, sending authorization errors in JSON.
      *
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller'))")
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php]: From the manual check under it seems like `delete` permission should also be added

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php [hunk 10]
```diff
@@ -223,6 +223,8 @@ public function deleteAction($mailId)
     /**
      * Processes test email sending.
      *
+     * @AdminSecurity("is_granted('create', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller')) || is_granted('read', request.get('_legacy_controller'))", message="Access denied.")
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php]: I think you can remove the manual check in the code now that this annotation is present

File: src/PrestaShopBundle/Controller/Admin/FeatureController.php (hunk 6 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/FeatureController.php]: Same answer as long as it's not removed the deprecated code should respect the same standard, although this one is only used in the product edition page so I guess only update permission could be enough (but `_legacy_controller: AdminProducts` should be used in the routing)

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php [hunk 11]
```diff
@@ -388,6 +388,8 @@ public function refreshExchangeRatesAction()
     /**
      * Handles ajax request which updates live exchange rates.
      *
+     * @AdminSecurity("is_granted('update', request.get('_legacy_controller')) || is_granted('delete', request.get('_legacy_controller'))")
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Here as well you could clean the manual check in the controller

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: I noticed in some places that write the permission manual that they use the controller name instead like `AdminModulesSf` Wouldn't it work as well? Even all the values that we put in `_legacy_controller` don't look like this

Maybe both format can work, but the one matching the controller in camel case feels better no?

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 7 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]: Indeed the `_legacy_controller` attribute is not set everywhere in the routing file, but it seems like they have been added in this PR so it's fine

File: src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/shops.yml [hunk 12]
```diff
@@ -3,5 +3,6 @@ admin_shops_search:
   methods: [ GET ]
   defaults:
     _controller: 'PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\ShopController::searchAction'
+    _legacy_controller: AdminAdvancedParameters
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/config/routing/admin/configure/advanced_parameters/shops.yml]: As @matks said it seems this controller is used across the whole BO for the multi shop headers, it may need to be open to all users And is definitely not related to permissions about advanced parameters

File: src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/features.yml [hunk 13]
```diff
@@ -4,6 +4,7 @@ admin_feature_get_feature_values:
   defaults:
     idFeature: 0
     _controller: PrestaShopBundle\Controller\Admin\FeatureController::getFeatureValuesAction
+    _legacy_controller: AdminFeatures
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/features.yml]:
```suggestion
    _legacy_controller: AdminProducts
```

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/features.yml]: Actually, it's a "sub controller" of Product page, this API is only used in the product edition page (like warehouse and suppliers)

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/features.yml]: By the way, I just noticed that this route is also used in product V2, I marked this controller as deprecated but if we remove it (for v9) the page won't work anymore So we should either:
- remove the deprecation notice from `PrestaShopBundle\Controller\Admin\FeatureController`
- copy this action into the proper controller `PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController` with a new proper route and update the [JS code of product page v2 here](https://github.com/PrestaShop/PrestaShop/blob/8.1.x/admin-dev/themes/new-theme/js/pages/product/edit/manager/feature-values-manager.ts#L145)

**Review by jolelievre — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/features.yml (hunk 13 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/products/features.yml]: (second option is definitely not mandatory for this PR, just removing the deprecated annotation is enough if you prefer)

File: src/PrestaShopBundle/Controller/Admin/CategoryController.php (hunk 3 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/CategoryController.php]: When you browse Product Page V1, you have a small form and a button to allow you to create a category, without having to visit the category BO page. So it's an implicit grant of access.

>  But maybe not, permission to edit product doesn't mean you're allowed to edit/create categories
The Backoffice Product page v1 design obliges us to do this.

File: src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php (hunk 8 above)
Comment (matks) [reply src/PrestaShopBundle/Command/SecurityAnnotationLinterCommand.php]: > since we aim at fixing all required routes they should also be fixed

We aim to fix all required routes, but not in this PR 😉 . This PR must unblock the 8.1.0 release process, not fix every problem in PrestaShop.

I know you'll disagree ^^ but I think we should aim, in this Pull Request, to fix _the new routes introduced in 8.1.0_ and nothing else. Another PR can be done later to fix years-long problems, but I don't want this PR to have a scope too large. Because I know from experience that PRs with too large scopes take weeks to be reviewed, tested and merged.

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php (hunk 10 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController.php]: After checking the code, I think the AdminSecurity was not used there because the response but must be JSON. I think `@AdminSecurity()` works for HTML response only.

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php [hunk 14]
```diff
@@ -315,6 +315,7 @@ public function createAction(Request $request)
      * Show Employee edit page.
      *
      * @DemoRestricted(redirectRoute="admin_employees_index")
+     * @AdminSecurity("is_granted('update', request.get('_legacy_controller'))")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController.php]: Looks like there is a custom rule 🤔 
```
        $formAccessChecker = $this->get('prestashop.adapter.employee.form_access_checker');

        if (!$formAccessChecker->canAccessEditFormFor($employeeId)) {
``` 

So AdminSecurity here will probably not get the job done 😢 this is an exception to the general rule

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php (hunk 9 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController.php]: Same as above: I now understand why AdminSecurity was not used here. Response must be JSON. AdminSecurity does not handle that.

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php (hunk 11 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: No it's another case where message "Access denied" must be in JSON

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php [hunk 15]
```diff
@@ -296,6 +296,8 @@ public function moduleAction(Request $request)
     /**
      * Controller responsible for importing new module from DropFile zone in BO.
      *
+     * @AdminSecurity("is_granted('create', 'ADMINMODULESSF_') || is_granted('delete', 'ADMINMODULESSF_')")
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: Again JSON

**Comment by matks** [comment]
Oooooh now that I dig deeper it seems that _most of the missing AdminSecurity annotations_ were not there because the controller actions do return JSON.

So in order to properly secure these endpoints we strongly need a `AdminSecurityJson()` annotation.

**Comment by matks** [comment]
After more exploration, I found that even EmployeeController actions are meant to be used from any backoffice page. They are used by buttons in the navigation bar, which is displayed in every backoffice page. So it's expected it is not protected against one set of privileges.

**Comment by matks** [comment]
@boherm @jolelievre So reviewing this PR, I had to go through a looooot of old code 😄 

And I found out that `AdminSecurity()` on most of these old controller actions 😞 is not relevant.

1. As mentioned above, `AdminSecurity()` inner system does work well for controller actions that return HTML, not JSON. This is why we have multiple controllers which implement themselves the "check user is granted access" manually, and do not use the annotation. I checked everyone of them and they are secure 👍 so I removed @boherm added annotations. The good way to solve this will be to create a `AdminSecurityJSON()` annotation to be used for these controller actions.
2. Plenty controller actions were actually meant to be used anywhere from the backoffice, because they are used by buttons and actions in the navigation bar. I also removed @boherm annotations on these ones.

## What's left? What did I left untouched?
- AdminSecurity on New API backoffice pages although they are not implemented
- AdminSecurity on symfony pages work in progress
- the first controller used by backoffice translation page
- product page v1 (listing and add/edit) backoffice pages that were not protected by a manual check

**Review by matks — DISMISSED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]
lgtm

**Review by FabienPapet — APPROVED** [review]

**Review by sallemiines — APPROVED** [review]
Hello @boherm 

Thanx for the PR ! LGTM 

[Tests auto](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5043581437)=> OK 
QA :heavy_check_mark: 

Thank you !
