### PR TITLE
Fix undefined INTL_IDNA_VARIANT_UTS46 if intl ICU < 4.6

### LINKED ISSUE #11933: MailboxHeader.php not using the full email-adress of customers, 1.7.5.0
**Describe the bug**
Clean install of 1.7.5.0, migrated old 1.6.1.20 data. MailboxHeader.php doesn't seem to get a correct address - it gets cut after the @-sign.

**To Reproduce**
Good question. Anything related to sending emails to customers generates this problem - them placing an order and getting a confirmation mail, us changing order status (where it's set to mail the customer).

Quite frankly, I'm at a loss to find this. Further logs are available if needed.

**Screenshots**

exeption-log-edited

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2.9

### PR DESCRIPTION
**Pull request by rdy4ever**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | #11579 introduced `INTL_IDNA_VARIANT_UTS46`  in the `idn_to_ascii` function, in order to comply with PHP 7.2 standards.<br>However, this broke e-mail sending for servers running an outdated ICU version (< 4.6). Figures out, there are more shared hostings that run outdated ICU versions with new PHP versions than expected and we should expect to see more and more issues regarding mail sending as more people will upgrade to PS 1.7.5.0. <br>This PR aims to silently fix this issue. If `INTL_IDNA_VARIANT_UTS46` is defined, use it to comply with PHP 7.2 standards. If it's not defined, then use the old `INTL_IDNA_VARIANT_2003` as long as it is [still supported by PHP](https://wiki.php.net/rfc/deprecate-and-remove-intl_idna_variant_2003) (up to the next major release, which will be 8.0.0). In PHP 7.2.0 up to 7.4.0, using `INTL_IDNA_VARIANT_2003` will trigger `E_DEPRECATED` notices while still being the default for the `idn_to_ascii` function and still working. From PHP 7.4.0 up to next major release, the default will be `INTL_IDNA_VARIANT_UTS46` but `INTL_IDNA_VARIANT_2003` will still work with warnings. From PHP 8.0.0, we cannot longer use `INTL_IDNA_VARIANT_2003` so we'll use the current default. If a server will run the outdated ICU <4.6 and PHP >= 8.0.0, an Exception will be triggered, but untill PS will be compatible with PHP 8.0 there is enough time to for most hosts to upgrade their ICU version.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | Does it break backward compatibility?no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #11933, #11949
| How to test?  | Try to send an email from the order page from a server running intl ICU < 4.6. With this fix, it will work. Without, you will get an error 500 both in BO and in FO when customer tries to register, reset password, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11995)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,

thanks for the explanations and for the patch @rdy4ever.

I think the max version of PHP support of PrestaShop 1.7 will be PHP 7, it's already really hard to support 2 major versions of PHP I don't think it will be wise to try to support 3.

Would you mind to apply the linter on your pull request?

```
composer install && ./vendor/bin/php-cs-fixer fix
```

Mickaël

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
ping @eternoendless , we should consider backporting this in 1.7.5.1 of needed

**Comment by rdy4ever** [comment]
hi @mickaelandrieu 
Just linted it.

**Comment by rdy4ever** [comment]
OK, seems I don't know how to properly lint this. PS: I'm on Windows/VS Code

**Comment by mickaelandrieu** [comment]
Me too when I'm playing video games, but I use WSL (Windows Subsystem Linux) with zsh.

capture

We are not really satisfied asking everyone to fix coding styles, we're looking for a more "contributor-friendly" solution while keeping the quality of code high, more to come later :)

Thanks @rdy4ever

**Comment by PierreRambaud** [comment]
Both constants are different and produce a different result :/ (http://www.unicode.org/reports/tr46/#IDNAComparison%3E) 
We need to be sure everything will be ok!

**Comment by rdy4ever** [comment]
Thanks @mickaelandrieu
Do you think we could merge this in 1.7.5.1?
I have a feeling we’ll be seing more bug reports as people upgrade to 1.7.5.0.

File: classes/Mail.php [hunk 1]
```diff
@@ -869,15 +869,26 @@ public static function mimeEncode($string, $charset = 'UTF-8', $newline = "\r\n"
...
      */
     public static function toPunycode($to)
     {
         $address = explode('@', $to);
         if (empty($address[0]) || empty($address[1])) {
             return $to;
         }
-
-        return $address[0] . '@' . idn_to_ascii($address[1], 0, INTL_IDNA_VARIANT_UTS46);
+        if (defined('INTL_IDNA_VARIANT_UTS46')) {
```
Comment (PierreRambaud) [inline classes/Mail.php:881]: Because of return you can do:

```php
        if (defined('INTL_IDNA_VARIANT_UTS46')) {
            return $address[0] . '@' . idn_to_ascii($address[1], 0, INTL_IDNA_VARIANT_UTS46);
        } 

        if (version_compare(phpversion(), '8.0.0', '<')) {
            return $address[0] . '@' . idn_to_ascii($address[1], 0, INTL_IDNA_VARIANT_2003);
        } 

        return $address[0] . '@' . idn_to_ascii($address[1]);
```

**Comment by PierreRambaud** [comment]
I think we need to target 1.7.5.1. @eternoendless This one is important.

File: classes/Mail.php (hunk 1 above)
Comment (rdy4ever) [reply classes/Mail.php:881]: Hi @PierreRambaud
Thanks for the review.
You are right, ‘return’ will stop execution at the first true comparission so I guess elseif is not required.

Comment (PierreRambaud) [reply classes/Mail.php:881]: I did it for you + cs fixer =)
We really appreciate contribution with explanations and php docs :heart:

File: classes/Mail.php [hunk 2]
```diff
@@ -877,7 +884,15 @@ public static function toPunycode($to)
             return $to;
         }
 
-        return $address[0] . '@' . idn_to_ascii($address[1], 0, INTL_IDNA_VARIANT_UTS46);
+        if (defined('INTL_IDNA_VARIANT_UTS46')) {
+            return $address[0] . '@' . idn_to_ascii($address[1], 0, INTL_IDNA_VARIANT_UTS46);
+        }
+
+        if (version_compare(phpversion(), '8.0.0', '<')) {
```
Comment (eternoendless) [inline classes/Mail.php]: If the constant will be removed in a future PHP version, wouldn't it make more sense to check if the constant is defined instead?

File: classes/Mail.php [hunk 3]
```diff
@@ -869,6 +869,13 @@ public static function mimeEncode($string, $charset = 'UTF-8', $newline = "\r\n"
      * @param string $to Email address
      *
      * @return string
+     *
+     * Try to use INTL_IDNA_VARIANT_UTS46 only if defined or PHP version >= 8.0.0
+     * If not, use INTL_IDNA_VARIANT_2003
+     * PHP 7.2.0 up to 8.0.0 will return E_DEPRECATED notices but INTL_IDNA_VARIANT_2003 will still work.
+     * From PHP 8.0.0, we cannot longer use INTL_IDNA_VARIANT_2003 so we'll get an Exception using
+     * default if INTL_IDNA_VARIANT_UTS46 not defined.
+     * See https://wiki.php.net/rfc/deprecate-and-remove-intl_idna_variant_2003
```
Comment (eternoendless) [inline classes/Mail.php]: Please move this block before the `@param` line to comply with Phpdoc syntax.

I think it also could be shortened just to explain that it tries using `INTL_IDNA_VARIANT_UTS46` if defined, then try `INTL_IDNA_VARIANT_2003`.

File: classes/Mail.php (hunk 2 above)
Comment (eternoendless) [reply classes/Mail.php]: We can just add a comment before saying "will be removed in PHP 8, see http://..."

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: classes/Mail.php (hunk 3 above)
Comment (rdy4ever) [reply classes/Mail.php]: @eternoendless I've cut the explanation shorter
@PierreRambaud Thanks!

**Review by eternoendless — DISMISSED** [review]
Looks good to me

**Review by eternoendless — DISMISSED** [review]
Rebased into 1.7.5.x and squashed

**Comment by MathiasReker** [comment]
@rdy4ever to use PHP CS Fixer on Windows:

```
cd repo
git checkout branch
./vendor/friendsofphp/php-cs-fixer/php-cs-fixer
```

**Comment by Quetzacoalt91** [comment]
@rdy4ever / @eternoendless, it seems we need a push to be made on this PR in order to trigger Travis.

**Comment by PierreRambaud** [comment]
Done, waiting for CI :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you all!

**Comment by ghost** [comment]
This bug is very important to fix. None of the payment methods are work in my prestashop 1.7.5.0 installation no matter php 5.6 or 7.0
This also cause an "unexpected error" if pay via PayPal express. 
ICU v4.2.1

**Comment by matks** [comment]
Hi @nataniko this bug has been solved by this PR and will be shipped with patch version 1.7.5.1 which will be released very soon 😄

**Comment by TecnoHands** [comment]
prestashop 1.7.8.6 and I have this error. 
Change the mail.php but prestashop don't send emails only from 1 team account (The registered in all parameters, SMTP, IMAP and store contact mail) 
Per example if you need to respond a client from webmaster and your config is with clientservice@... the mail don't send it, don't transfer to antoher team member.
If you respond from clientservice@.. mails send it and can transfer. 

Message in log
Swift Error: Expected response code 250 but got code \"550\", with message \"550-Your FROM address ( soporte@ , Webmaster\r\n550- ) must match your authenticated email user (\r\n550 atcliente@ ). Treating this as a spoofed email.\r\n\"

With config: /usr/sbin/sendmail emails send it correctly from any account
Problem comes with SMTP configuration
