### PR TITLE
Automatically generate no image thumbnails

### LINKED ISSUE #617: Tags are not displayed on product details page, quick view and product listing page when product has no image
### Describe the bug and add attachments

When a product has no image the tags related to the products are not diplayed/not well displayed.

https://github.com/PrestaShop/hummingbird/assets/16019289/7c91cf14-cb7c-41b5-8ee3-96668d26cebd

### Expected behavior
The tags should be displayed correctly. And an placeholder image should be displayed.

### Steps to reproduce
1. Install dev branch of hummingbird > Apply theme
2. Create a product > Add a title
3. Open the FO
4. See in the homepage the product has the tags (`New` and `Out-of-Stock`) are not correctly displayed :x:
5. Open the quick view : no tags are displayed :x:
6. Click on See details : no tags are displayed

### PrestaShop version(s) where the bug happened
develop

### PHP version(s) where the bug happened
8.1

### LINKED ISSUE #32351: If you delete thumbnails of placeholder images, their thumbnails are not regenerated again.
**Issue**

If you delete thumbnails of placeholder images, their thumbnails are not regenerated again.

Snímek obrazovky 2023-04-21 140353

_Originally posted by @Hlavtox in https://github.com/PrestaShop/PrestaShop/issues/18257#issuecomment-1517720020_

**Expected behavior**

Image 'not found' should be generated 

**PS version**

8.1 rc, develop

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Automatically regenerates default (not found / no image available) images in front office if missing.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See below
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/10615886234
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/32351, Fixes https://github.com/PrestaShop/hummingbird/issues/617
| Related PRs       | 
| Sponsor company   | TRENDO s.r.o.

### How to test
- Make a product with no image
- Go to img/p/ and delete all thumbnails of not found images, keep only the one for your lang - fr.jpg for example.
- Go to FO, refresh, go back to that folder, see that all images are renegerated.
- Now delete even fr.jpg
- Go to FO, refresh, go back to that folder, see that all images are renegerated using a fallback image.

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `description` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#description))
* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `category` should be one of these: `FO`, `BO`, `CO`, `IN`, `WS`, `TE`, `LO`, `ME` or `PM`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `BC breaks` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#bc-breaks))
* The `deprecations` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#deprecations))
* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

File: src/Adapter/Image/ImageRetriever.php [hunk 1]
```diff
@@ -353,22 +353,44 @@ public function getCustomizationImage($imageHash)
...
-        $imageTypes = ImageType::getImagesTypes($type, true);
 
-        if (empty($imageTypes)) {
-            throw new PrestaShopException(sprintf('There is no image type defined for "%s".', $type));
-        }
+        // Get all image types present on shops
+        $imageTypes = ImageType::getImagesTypes();
+
+        // Get path of original image for our current language
+        $originalImagePath = implode(DIRECTORY_SEPARATOR, [
```
Comment (jolelievre) [inline src/Adapter/Image/ImageRetriever.php]: What if `$originalImagePath` doesn't exist? We should check that the file exists no?

Comment (Hlavtox) [reply src/Adapter/Image/ImageRetriever.php]: They are present from the installer for all languages, they must be there.
In `_PS_CAT_IMG_DIR_` `_PS_MANU_IMG_DIR_` `_PS_SUPP_IMG_DIR_` `_PS_PRODUCT_IMG_DIR_` `_PS_STORE_IMG_DIR_`.

In ImageThumbnailsRegenerator that is used in backoffice, there is a following fallback, but it doesn't make much sense. Use `_PS_PRODUCT_IMG_DIR_` if the image is not in `_PS_CAT_IMG_DIR_`?

```php
$file = $dir . $language->getIsoCode() . '.jpg';
                if (!file_exists($file)) {
                    $file = _PS_PRODUCT_IMG_DIR_ . $defaultLang->getIsoCode() . '.jpg';
                }
```

We could introduce one global fallback image for these cases, or when user creates a new completely unknown language. Or just use an icon, this would simplify everything. :-)

Comment (Hlavtox) [reply src/Adapter/Image/ImageRetriever.php]: I introduced a fallback that is used now.

File: src/Adapter/ImageThumbnailsRegenerator.php [hunk 2]
```diff
@@ -275,10 +269,14 @@ public function regenerateNoPictureImages(string $dir, array $type, array $langu
 
         foreach ($type as $image_type) {
             foreach ($languages as $language) {
+                // We get the "no image available" in the folder of the object
                 $file = $dir . $language->getIsoCode() . '.jpg';
+
+                // If it doesn't exist, we use a fallback one in the root of img directory
                 if (!file_exists($file)) {
-                    $file = _PS_PRODUCT_IMG_DIR_ . $defaultLang->getIsoCode() . '.jpg';
+                    $file = _PS_IMG_DIR_ . 'noimageavailable.jpg';
```
Comment (jolelievre) [inline src/Adapter/ImageThumbnailsRegenerator.php]: Here you change the default behaviour, the `noimageavailable` image should only be used as a last resort, if the image with the proper language from default configuration is available then it should be used in priority

It's better to have a localized default image instead of a globally english one

**Review by jolelievre — CHANGES_REQUESTED** [review]

File: src/Adapter/ImageThumbnailsRegenerator.php (hunk 2 above)
Comment (Hlavtox) [reply src/Adapter/ImageThumbnailsRegenerator.php]: Well, the thing is, that for example, for a category, it tries to use _PS_MANU_IMG_DIR_ / fr.jpg

And if it doesn't exist, it uses _PS_PRODUCT_IMG_DIR_ / fr.jpg

Or, for product, it tries to use the same image for fallback. :-)))

Comment (Hlavtox) [reply src/Adapter/ImageThumbnailsRegenerator.php]: Fixed

**Review by jolelievre — APPROVED** [review]
Thanks @Hlavtox

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

It works as expected :) 
The thumbnail displayed when no image is added to a rpduct is the correct one 💪 

https://github.com/user-attachments/assets/d7448bf6-eec7-4f16-8e7f-9fdcc04af952

It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
thanks @Hlavtox !
