### PR TITLE
Fix php7.4 incompability warning

### LINKED ISSUE #23430: [BO] Warning display after creating Store (or view it)
#### Describe the bug

A clear and concise description of what went wrong.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO -> shop parameters -> contact -> Store
2. Click on New Store
3. Fill **all inputs** in form and click on save 
4. Edit the store, see errors

**Screenshots**

image (3)

#### Additional information

* PrestaShop version: develop branch
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Passing the separator after the array in the `implode` method is deprecated, it would trigger several alerts in a big error message
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23430
| How to test?      | See issue #23430
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24479)

### CODE REVIEW

File: controllers/admin/AdminStoresController.php [hunk 1]
```diff
@@ -599,6 +599,6 @@ protected function adaptHoursFormat($value)
     {
         $separator = array_fill(0, count($value), ' | ');
 
-        return array_map('implode', $value, $separator);
+        return array_map('implode', $separator, $value);
```
Comment (matthieu-rolland) [inline controllers/admin/AdminStoresController.php:602]: As of php 7.4, in the implode method, the separator must come before the array:

https://www.php.net/manual/en/function.implode.php

Comment (Progi1984) [inline controllers/admin/AdminStoresController.php:602]: You can't do this as we support PHP 7.1 => 7.4. You must check the version of PHP.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Need changes

File: controllers/admin/AdminStoresController.php (hunk 1 above)
Comment (matks) [reply controllers/admin/AdminStoresController.php:602]: 🤯  what they SWAPPED the argument order in php7.4

Comment (matthieu-rolland) [reply controllers/admin/AdminStoresController.php:602]: https://www.php.net/manual/en/function.implode.php

Before php 7.4, both orders are supported, as of PHP 7.4, only one order is supported (the other order is deprecated)

(Of course, I tested that it still works with an anterior PHP version (7.3))

Comment (matks) [reply controllers/admin/AdminStoresController.php:602]: @matthieu-rolland Do you mean that if you run 1.7.8 with php7.2, php is going to be able to find out "what is glue, what is array" because of the type?

Comment (matthieu-rolland) [reply controllers/admin/AdminStoresController.php:602]: Of course, I tested that it still works with an anterior PHP version (7.3)

Comment (matthieu-rolland) [reply controllers/admin/AdminStoresController.php:602]: yep ! I tested in php 7.3, and it's written in the documentation

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Can be QA by Dev : Please check both PHP 7.4 and PHP 7.2 that it works fine.

Thanks :)

**Comment by PierreRambaud** [comment]
Thank you @matthieu-rolland
