### PR TITLE
Avoid errors display when Emails translations lang.php does not exist

### LINKED ISSUE #23878: Translatations - Error in Email - Body Translations
#### Describe the bug

On 1.7.8, when I modify translations of Email Body, an error is displayed. There was no error in 1.7.7.

Content of the error : "Email subject translation file not found in _[PATH]_/mails/fr/"

#### Expected behavior

No error :smile: 

#### Steps to Reproduce

1. Go to International > Translations
2. In "Modify Translations" select "Email translations", then "Body" and any theme or language, then click the "Modify" button
3. An error is displayed at the top of the page

**Screenshots**

translation error in body translation

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The lang.php is the file where mails template overrides are stored.<br>When you go Go to Admin > International > Translations, In modify translations form, choose Emails, Emails body, choose a language, the modifications made are saved in /mails/LOCALE/lang.php.<br>If no override have been done yet, this file doesn't exist.<br><br>The goal of this PR is to not display errors when lang.php file doesn't exist in the locale mails directory as before 1.7.8.x.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23878 
| How to test?      | Go to Admin > International > Translations, In modify translations form, choose Emails, Emails body, choose a language<br><ul><li>When no lang.php exists in /mails/LOCALE/, no error has to be display </li><li>If you override a module mail subject and refresh the page, the updated subject have to be displayed (see https://github.com/PrestaShop/PrestaShop/issues/19288)</li></ul>
| Possible impacts? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24899)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: controllers/admin/AdminTranslationsController.php [hunk 1]
```diff
@@ -2806,7 +2806,9 @@ public function initFormMails($no_display = false)
 
         foreach ($modules_has_mails as $module_name => $module_path) {
             $module_path = rtrim($module_path, '/');
-            $module_mails[$module_name] = $this->getMailFiles($module_path . '/mails/' . $this->lang_selected->iso_code . '/', 'module_mail');
+            $module_locale_mails_path = $module_path . '/mails/' . $this->lang_selected->iso_code . '/';
+            $module_mails[$module_name] = $this->getMailFiles($module_locale_mails_path, 'module_mail');
+            $module_mails[$module_name]['subject'] = $this->getSubjectMailContent($module_locale_mails_path);
             $module_mails[$module_name]['subject'] = $core_mails['subject'];
```
Comment (matthieu-rolland) [inline controllers/admin/AdminTranslationsController.php]: isn't this overriding the assignation on the line just above?

**Review by matthieu-rolland — COMMENTED** [review]
one feedback

File: controllers/admin/AdminTranslationsController.php (hunk 1 above)
Comment (sowbiba) [reply controllers/admin/AdminTranslationsController.php]: you're right. thanks

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
(waiting for CI before sending in QA)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

I tried to install this [module](https://github.com/Amit-Kumar-Tiwari-Webkul/wktestmodule) and the Stripe module but I manage to reproduce this issue: https://github.com/PrestaShop/PrestaShop/issues/19288 with this PR.
I attached a screen record
https://drive.google.com/file/d/1_FYhUZDUp2uvL4Y6scSgE5zwzX8_HkB3/view?usp=sharing
Without PR => ok
https://drive.google.com/file/d/1yOBfIyrtA42Mkh1e4dvEB6sfNNM2L4PD/view?usp=sharing

Thank you!

**Comment by sowbiba** [comment]
> Hi @sowbiba,
> 
> I tried to install this [module](https://github.com/Amit-Kumar-Tiwari-Webkul/wktestmodule) and the Stripe module but I manage to reproduce this issue: #19288 with this PR.
> I attached a screen record
> https://drive.google.com/file/d/1_FYhUZDUp2uvL4Y6scSgE5zwzX8_HkB3/view?usp=sharing
> Without PR => ok
> https://drive.google.com/file/d/1yOBfIyrtA42Mkh1e4dvEB6sfNNM2L4PD/view?usp=sharing
> 
> Thank you!

The example module https://github.com/Amit-Kumar-Tiwari-Webkul/wktestmodule doesn't have lang.php file

I don't have the stripe module.
We need to find a module which have lang.php. I'm creating one

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

Thank you :slightly_smiling_face:

**Comment by sowbiba** [comment]
Sorry, there is something I misunderstood myself. The description of the PR have been updated. Tell me if it's not clear enough

**Review by matks — COMMENTED** [review]
Hello @sowbiba 

> The goal of this PR is to not display errors when lang.php file doesn't exist in the locale mails directory as before 1.7.8.x.

I am trying to imagine all possible states for this usecase.

## 1. User has not created translation overrides for mail A for locale `localeB`.

So there is no lang.php file in `/mails/localeB/` and that is expected.

Without the PR, we see the error "Email subject translation file not found in /mails/localeB"
With the PR, we see no error ✅ 

## 2. User has created translation overrides for mail A for locale `localeB`.

So there is a lang.php file in `/mails/localeB/` and that is expected.

With and without we see no error ✅ 

## 3. User has not created translation overrides for mail A for locale `localeB`.

BUT for an unexpected reason there is no lang.php file in `/mails/localeB/` . This is a system error, an invalid state.

Without the PR, we see the error "Email subject translation file not found in /mails/localeB" and that is expected: we want the system to warn us about this error
With the PR, my guess would be we see no error. 🟥  I think this is an issue? please tell me

If I am right and there is an issue for usecase 3, we maybe need to put a `if` statement to be able to find out if we are in usecase 1 or 3

**Comment by sowbiba** [comment]
@matks 
You're right about the scenarii and errors state. But the only way to know if user made a modification is the presence of the lang.php

**Comment by matks** [comment]
> @matks
> You're right about the scenarii and errors state. But the only way to know if user made a modification is the presence of the lang.php

Is it possible to do
- we know if this is usecase 1 if directory mails/localeB does not exist
- we know if this is usecase 3 if directory exists but is empty?

**Comment by sowbiba** [comment]
The directory mails/LOCALE always exists, it contains mails templates in html and txt. It's the presence of the lang.php in this directory which says that the user overrides mails subjects or body

**Review by matks — APPROVED** [review]
OK for me then 👍

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1ZQfXmflOdR0whcJW5Chc8cYOPFUNSphn/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @sowbiba & @khouloudbelguith
