### PR TITLE
Mail: add PS_MAIL_SUBJECT_PREFIX to control [Foo] subject prefix

### LINKED ISSUE #24492: Remove square brackets to email subject
#### Describe the bug

It's not really a bug but I consider it a useless thing that any developer goes to remove in its integration because it is useless.

Remove square brackets to email subject.

classes/Mail.php - line 476 (in PrestaShop 1.7.7.4)
Remove this line please.

`$subject = '[' . strip_tags($configuration['PS_SHOP_NAME']) . '] ' . $subject;`
Capture d’écran 2021-05-14 à 09 43 12

#### Expected behavior

Receive an email with the right subject without the shop name in square brackets

#### Steps to Reproduce

Receive an mail

#### Additional information

* PrestaShop version: all - 1.7.7.4
* PHP version: 7.3.28

### PR DESCRIPTION
**Pull request by rmilecki**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Mail::send() was prefixing every e-mail subject with a shop name in<br>square brackets. A lot of shop owners look for a way of disabling that<br>behaviour. Most of them probably find it redundant since there is<br>already a sender in the From field.<br><br>Add PS_MAIL_SUBJECT_PREFIX config option and allow changing it in the<br>Advanced Parameters → E-mail<br><br>Make it enabled by default to avoid changing a long-known behaviour.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24492
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/544
| How to test?      | Disable "Prefix subject with shop name" and verify that outgoing e-mails don't have shop name as subject prefix
| Possible impacts? | Make sure that sending e-mails works

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]
LGTM

**Review by matks — COMMENTED** [review]
Code is OK 👍 please just let me check quickly with @PrestaShop/product-team to confirm behavior is good 😉 (I add the required label)

**Review by marsaldev — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/EmailConfigurationType.php [hunk 1]
```diff
@@ -88,6 +88,9 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'multiple' => false,
                 'choices' => $this->mailMethodChoiceProvider->getChoices(),
             ])
+            ->add('subject_prefix', SwitchType::class, [
+                'label' => $this->trans('Prefix subject with shop name', 'Admin.Advparameters.Feature'),
```
Comment (marsaldev) [inline src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Email/EmailConfigurationType.php]:
```suggestion
                'label' => $this->trans('Enable the shop name as a prefix in the emails subject', 'Admin.Advparameters.Feature'),
```

**Comment by MatShir** [comment]
LGTM 🚀

**Comment by MatShir** [comment]
I have updated some wording. Quick second validation before the QA comes ? @FabienPapet @matks 🙏

**Review by matks — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Review by yanmakouf — APPROVED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Wouldn't the current hook be sufficent? You can do what you want easily. :-)

```php
Hook::exec('actionMailAlterMessageBeforeSend', [
  'message' => &$message,
]);
```
And use it simply by:
```
$subject = $message->getSubject();
// do whatever you want, remove the prefix if wanted, like
$subject = str_replace(
  '[' . strip_tags(Configuration::get('PS_SHOP_NAME')) . '] ', 
  '', 
  $subject);
$message->setSubject($subject);
```

ping @matks @marsaldev

**Comment by kpodemski** [comment]
@Hlavtox we can tell that about many things, but eventually this option is something what merchant are asking about quite often 👍🏻

**Review by FabienPapet — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @rmilecki 

The issue is well fixed and the square brackets are removed :tada: 

image

The automated test are OK :heavy_check_mark: 

Thank you !

**Comment by marsaldev** [comment]
Thanks @rmilecki !

**Comment by rmilecki** [comment]
It's great to have some tiny contribution in this project, thanks for handling my pull request.

**Comment by kpodemski** [comment]
Thank you, Rafał! I hope to see more from you in the future! Keep up the good work :)

**Comment by Hlavtox** [comment]
@rmilecki Hello Rafał, please don't forget to create a PR for autoupgrade https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/8.1.0.sql, or it will change default behavior for upgrading users. 👍
