### PR TITLE
Search Tab with case sensitive matching

### LINKED ISSUE #37962: Case sensitive tab mismatch
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PrestaShop V9, if your tab controller matches another tab with different case it results in an error `Undefined array index` in `TabRepository::getIdByClassName` because the passed argument (for ex: `Home`) can match with a tab that shouldn't match (for example `HOME`), since the query is case insensitive by default the tab will be matched, but the cached value won't be the same (`HOME` is used as the array key, and `Home` won't match).

This results in an array exception where the request should have failed and trigger a `NoResultException` which is correctly handled otherwise.

Image

### Expected behavior

If two tabs have controllers matching not strictly (case sensitive) but almost (case insensitive) the correct tab should be found, we want to avoid an incorrect matching that would result in improper index fetching

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Add BINARY function in Doctrine queries to allow a case sensitive request when searching for matching Tab
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | UI tests and CI green
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/13659421160
| Fixed issue or discussion?     | Fixes #37962
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by mattgoud — APPROVED** [review]

File: src/PrestaShopBundle/Entity/Repository/TabRepository.php [hunk 1]
```diff
@@ -137,7 +137,8 @@ public function getIdByClassName(string $className): int
         if (!isset($this->cachedTabIds[$className])) {
             $result = $this->createQueryBuilder('t')
                 ->select('t.id, t.className')
-                ->where('t.className = :className')
+                // Use binary to force a case-sensitive comparison (HOME and Home are different)
```
Comment (kpodemski) [inline src/PrestaShopBundle/Entity/Repository/TabRepository.php:140]: It solves the problem for this one scenario and part of the core, but why would anyone call their tab "Home" and not something more specific like ModuleNameHome? 🤔

**Review by kpodemski — APPROVED** [review]

File: src/PrestaShopBundle/Entity/Repository/TabRepository.php (hunk 1 above)
Comment (kpodemski) [reply src/PrestaShopBundle/Entity/Repository/TabRepository.php:140]: I think the lack of specificity in the naming may lead to more issues in other places of the core 🤔

Comment (jolelievre) [reply src/PrestaShopBundle/Entity/Repository/TabRepository.php:140]: Yeah I agree it's an edge case, we stumble upon it with the shipping module that has a routing with a legacy controller mapping `HomeController` (already advised them to add a prefix for the module) and another sub-entry in the menu added by PS Classic edition, a first level parent element with controller `HOME`

The two are colliding very weirdly because we remove the suffix `Controller` when we search for a matching tab (already done in legacy) so `HOME` is returned in the result and added in the cached array, but the `Home` is not accessible and it raises an exception 🤪

So very unlikely edge case, but still I prefer to handle this part a bit better

**Comment by nicosomb** [comment]
@jolelievre can you detail the "how to test" section please? 
I had a custom tab on 9.0.x and on your branch. And I found it in both versions, with uppercase or lowercase.
I didn't see any difference between your branch and the 9.x one.

**Comment by nicosomb** [comment]
@jolelievre It's OK for me ✅

**Comment by nicosomb** [comment]
@jolelievre but you have a failing test in UI tests.
