### PR TITLE
Wrong redirection when using the quick search for a category

### LINKED ISSUE #17908: BO - Quick search - redirect to the Categories list page
#### Describe the bug

In the BO, When we search a category with the quick search, we are always redirected to the Categories list page instead of the Edit category page

#### Expected behavior
Redirection to the Categories list page
**Explain what you expected to happen instead.**
Redirection to the Edit category page

#### Steps to Reproduce

1. Go to BO
2. Search with the "Women" category for example in the top of the page
image

3. Click on the "Edit" button
image

3. Redirection to the Categories list page  instead of the Edit category page

It is ok with PS1.7.5.2
https://drive.google.com/file/d/1yZ9d7uD_NwqDhRP5irBRR-cVIgTlTZz3/view

#### Additional information

* PrestaShop version: 1.7.6.0, PS1.7.6.3, Branch 1.7.6.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | In the BO, When we search a category with the quick search, we are always redirected to the Categories list page instead of the Edit category page. `Tools::getPath` Became obsolete after migrating the category page. You must update the URLs to the new symfony controller.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17908.
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/17908 by @khouloudbelguith .

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17920)

### CODE REVIEW

File: classes/Tools.php [hunk 1]
```diff
@@ -4264,10 +4264,11 @@ public static function getPath($url_base, $id_category, $path = '', $highlight =
                 $n = 1;
                 $n_categories = (int) count($categories);
                 foreach ($categories as $category) {
-                    $link = Context::getContext()->link->getAdminLink('AdminCategories');
-                    $edit = '<a href="' . Tools::safeOutput($link . '&id_category=' . (int) $category['id_category'] . '&' . (($category['id_category'] == 1 || $home) ? 'viewcategory' : 'updatecategory')) . '" title="' . ($category['id_category'] == Category::getRootCategory()->id_category ? 'Home' : 'Modify') . '"><i class="icon-' . (($category['id_category'] == Category::getRootCategory()->id_category || $home) ? 'home' : 'pencil') . '"></i></a> ';
+                    $action = (($category['id_category'] == (int) Configuration::get('PS_HOME_CATEGORY') || $home) ? 'admin_categories_index' : 'admin_categories_edit');
```
Comment (jolelievre) [inline classes/Tools.php]: Nice work @PululuK Although in this case you can take advantage of the `_legacy_link` feature https://devdocs.prestashop.com/1.7/development/architecture/migration-guide/controller-routing/#the-legacy-link-property

Which is able to automatically convert a legacy link into a symfony route, provided you correctly use the arguments and not copy paste them by hand. So you could use the actions `index` and `updatecategory` in place of (respectively) the routes `admin_categories_index` and `admin_categories_edit`

This feature also manages an automatic redirection even with urls formatted like legacy, however in this case it doesn't work because the mapping of the `id_category` is missing for the `admin_categories_index` route (probably because the parameter was managed after the initial creation).

Anyway I believe you could fix this whole bug just fixing the routing configuration in `src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml`

```yaml
admin_categories_index:
    path: /{categoryId}
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:index
        _legacy_controller: AdminCategories
        _legacy_link: AdminCategories
        _legacy_parameters:
            id_category: categoryId
        categoryId: null
    requirements:
        categoryId: '\d+'
```
Only by adding the missing `_legacy_parameters` part

**Review by jolelievre — COMMENTED** [review]
Thanks @PululuK 
Nice handling of the `Link::getAdminLink` feature ^^
I have a suggestion for a fix that might be a bit simpler though

**Comment by PululuK** [comment]
> Thanks @PululuK
> Nice handling of the `Link::getAdminLink` feature ^^
> I have a suggestion for a fix that might be a bit simpler though

File: classes/Tools.php (hunk 1 above)
Comment (PululuK) [reply classes/Tools.php]: Hi @jolelievre 
Thank for you feedback ....


Very interesting your proposal ... Effectively is missing the `_legacy_parameters` (in `src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml::admin_categories_index`), adding this will prevent the redirection from always being on the category home, but this will not solve this problem for editing (which is the case with this issue : https://github.com/PrestaShop/PrestaShop/issues/17908).

Just with that :

```yml
admin_categories_edit:
    path: /{categoryId}/edit
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:edit
        _legacy_controller: AdminCategories
        _legacy_link: AdminCategories:updatecategory
        _legacy_parameters:
            id_category: categoryId
    requirements:
        categoryId: \d+
```

`index.php/sell/catalog/categories?_token=xxxx&id_category=xxx&updatecategory` should redirect here `/index.php/sell/catalog/categories/xxx/edit?_token=xxxxx`, But this is not the case ... see https://github.com/PrestaShop/PrestaShop/issues/17908

I think in this case the problem is much more complex then ...

Comment (jolelievre) [reply classes/Tools.php]: Oh you're right!! That's because the initial call to `getAdminLink` doesn't have the action parameter So it converts it to the index route (which makes sense), and then append the additional parameter

This would work well if the parameters were inject completely in `getAdminLink` So I guess the solution is a mix between what you did and fixing the routing

Once the routing is fixed, then you can really use the parameter `action` instead of `route` so you would need to replace:

```php
$action = (($category['id_category'] == (int) Configuration::get('PS_HOME_CATEGORY') || $home) ? 'index' : 'updatecategory');
```

and 

```php
$link = Context::getContext()->link->getAdminLink('AdminCategories',true, array('action'=> $action,'categoryId'=> (int) $category['id_category']));
```

Comment (PululuK) [reply classes/Tools.php]: It also works, I just tested! Could you tell me how it is faster than injecting symfony parameters directly? Because it seems more logical to directly inject the parameters for the new controller instead of legacy. See https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/classes/Link.php#L705

Comment (PululuK) [reply classes/Tools.php]: Done !

Comment (jolelievre) [reply classes/Tools.php]: The sf route params were initially introduced to allow creating symfony url through the `Link::getAdminLink` function (at the time the `_legacy_link` feature didn't exist)

Whereas the `_legacy_link` feature along with the `LegacyUrlConverter` service was specifically designed from a migration point of view. It has two main advantages:
- once the `_legacy_link` is correctly set the legacy urls are automatically redirected (when they find a matching route), so that even hard coded urls are correctly redirected to the new migrated page
- for modules developer you can use the getAdminLink in any version, if the controller has been migrated it will output the symfony url, if not it will output the legacy controller one

The only drawback (as you could see), is when parameters are concatenated after the getAdminLink call, because they are concatenated after the symfony url. We have no solution for this problem today, except correctly using the function parameters (which is sadly not possible in some early 1.7 versions).


As for this special case, since it's inside the core you are right: it doesn't bring much values It might be slightly less performant because it needs to find the matching route, but some cache policy has been implemented so the matching process is not that long

You might wonder, what is the advantage because this small performance drawback then? If I could inject the appropriate route directly. I would see two side advantages:
- if the symfony route is modified somehow (its name, parameters, ...) the modification would be automatically updated via this call
- for people using the previous versions it also gives them a valid example of how they should use the getAdminLink correctly and how they could integrate it (wether in the core or in their module)

Also, but this one is personal, I don't think mixing symfony routes inside the legacy classes is a good thing to do if we can avoid it.

Comment (PululuK) [reply classes/Tools.php]: Thank you @jolelievre  ! 
I agree on some points!
Done

File: classes/Tools.php [hunk 2]
```diff
@@ -4264,10 +4264,11 @@ public static function getPath($url_base, $id_category, $path = '', $highlight =
...
+                    $link = Context::getContext()->link->getAdminLink('AdminCategories',true, array('route'=>$action,'categoryId'=>(int) $category['id_category']));
```
Comment (jolelievre) [inline classes/Tools.php]: Sorry I missed this one, last modif you should use the legacy parameter `id_category` and let the converter rename it into `categoryId` for symfony routing

This is one of the advantages I mentioned, you can always inject the legacy parameter and if we, someday, change the parameter name in the routing it will still work.

Comment (PululuK) [reply classes/Tools.php]: Done !
Thank you @jolelievre

Comment (jolelievre) [reply classes/Tools.php]: Thank YOU! I just approved the PR!

**Review by jolelievre — DISMISSED** [review]
Thank you @PululuK

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Indentation is broken, please use php-cs-fixer

File: src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml [hunk 3]
```diff
@@ -5,6 +5,8 @@ admin_categories_index:
         _controller: PrestaShopBundle:Admin\Sell\Catalog\Category:index
         _legacy_controller: AdminCategories
         _legacy_link: AdminCategories
+        _legacy_parameters:
+            id_category: categoryId
```
Comment (matks) [inline src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml:9]: @jolelievre this parameter will not become mandatory for other URL generation statements ?

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml:9]: Good question! But I don't think so the converter only uses them to try and rename the parameters in their routing equivalent:
https://github.com/PrestaShop/PrestaShop/blob/7633be8294d90148d2bdfe3fd1c2d403e72ec91b/src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php#L151

Nothing special happens if they are not present, or if any additional parameter is used. At worst they will be appended to the generated url

Comment (matks) [reply src/PrestaShopBundle/Resources/config/routing/admin/sell/catalog/categories.yml:9]: Ok 👍 good to me then

**Comment by PululuK** [comment]
> Indentation is broken, please use php-cs-fixer

Hi @PierreRambaud 
Can you tell me where? In php file or yml ?

**Comment by jolelievre** [comment]
@PululuK We recently disabled PrettyCI because it had some issues, and it will soon stop to work (bu the end of the year)
But we haven't reintroduced the Github action that validates code style on the 176 branch, so @PierreRambaud detects them with his super eyes!! ^^

Anyway to fix it you can just run `php ./vendor/bin/php-cs-fixer fix` from the root folder

**Comment by PululuK** [comment]
> @PululuK We recently disabled PrettyCI because it had some issues, and it will soon stop to work (bu the end of the year)


Yes I am aware, I received their email! We must quickly find a tool to replace, even if I sincerely believe that the eyes of @PierreRambaud  are more effective

**Comment by PululuK** [comment]
Done @PierreRambaud (AKA PrettyCI-Man)  @jolelievre  !

**Review by jolelievre — DISMISSED** [review]

File: classes/Tools.php [hunk 4]
```diff
@@ -4264,10 +4264,11 @@ public static function getPath($url_base, $id_category, $path = '', $highlight =
                 $n = 1;
                 $n_categories = (int) count($categories);
                 foreach ($categories as $category) {
-                    $link = Context::getContext()->link->getAdminLink('AdminCategories');
-                    $edit = '<a href="' . Tools::safeOutput($link . '&id_category=' . (int) $category['id_category'] . '&' . (($category['id_category'] == 1 || $home) ? 'viewcategory' : 'updatecategory')) . '" title="' . ($category['id_category'] == Category::getRootCategory()->id_category ? 'Home' : 'Modify') . '"><i class="icon-' . (($category['id_category'] == Category::getRootCategory()->id_category || $home) ? 'home' : 'pencil') . '"></i></a> ';
+                    $action = (($category['id_category'] == (int) Configuration::get('PS_HOME_CATEGORY') || $home) ? 'index' : 'updatecategory');
+                    $link = Context::getContext()->link->getAdminLink('AdminCategories',true, array('action'=> $action,'id_category'=> (int) $category['id_category']));
```
Comment (Progi1984) [inline classes/Tools.php]:
```suggestion
                    $link = Context::getContext()->link->getAdminLink('AdminCategories', true, ['action'=> $action,'id_category'=> (int) $category['id_category']]);
```

File: classes/Tools.php [hunk 5]
```diff
@@ -4264,10 +4264,11 @@ public static function getPath($url_base, $id_category, $path = '', $highlight =
...
+                    $edit = '<a href="' . Tools::safeOutput($link).'" title="' . ($category['id_category'] == Category::getRootCategory()->id_category ? 'Home' : 'Modify') . '"><i class="icon-' . (($category['id_category'] == Category::getRootCategory()->id_category || $home) ? 'home' : 'pencil') . '"></i></a> ';
```
Comment (Progi1984) [inline classes/Tools.php]:
```suggestion
                    $edit = '<a href="' . Tools::safeOutput($link) . '" title="' . ($category['id_category'] == Category::getRootCategory()->id_category ? 'Home' : 'Modify') . '"><i class="icon-' . (($category['id_category'] == Category::getRootCategory()->id_category || $home) ? 'home' : 'pencil') . '"></i></a> ';
```

**Review by Progi1984 — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Can you please  target the 1.7.7.x branch instead of 1.7.6.x?

**Comment by PululuK** [comment]
> Can you please target the 1.7.7.x branch instead of 1.7.6.x?

hi @PierreRambaud 
Why and how should I do that please?

**Comment by PierreRambaud** [comment]
@PululuK Because this one is not major and we will release a 1.7.7.0 really soon :wink:

**Comment by PululuK** [comment]
> @PululuK Because this one is not major and we will release a 1.7.7.0 really soon

Ok ... I updated the tag to 1.7.7.X.

**Comment by jolelievre** [comment]
@PululuK you also need to change the target branch (actually that's the most important)
You can do it by editing the PR and changing the base, although ideally you should rebase because there might be some conflict If it's too complicated you can recreate a branch from 1.7.7.x branch and cherry pick the commit
I can do it for you if you want?

**Comment by PululuK** [comment]
> @PululuK you also need to change the target branch (actually that's the most important)
> You can do it by editing the PR and changing the base, although ideally you should rebase because there might be some conflict If it's too complicated you can recreate a branch from 1.7.7.x branch and cherry pick the commit
> I can do it for you if you want?

Yes you can do it ! thank you so much @jolelievre

**Comment by jolelievre** [comment]
Ok @PululuK , the PR is rebased and the target is 1.7.7.x

**Comment by Progi1984** [comment]
Please fix PHPCSFixer issues.

**Comment by PululuK** [comment]
> Please fix PHPCSFixer issues.

Hi @Progi1984 
Sorry! but your test tool is not verbose enough, I have no information on the lines concerned ... I miss PrettyCi 😔

**Comment by PululuK** [comment]
> Please fix PHPCSFixer issues.

Done !

**Review by Progi1984 — DISMISSED** [review]

**Comment by jolelievre** [comment]
Hello @PululuK 
So it's been decided that there will be a 1.7.6.5 version in the end 😅
So this PR can go back to the 1.7.6.x branch, I'm gonna make the rebase to avoid bothering you 😉

**Review by jolelievre — DISMISSED** [review]
Thank you @PululuK 
The PR is back on track for 1.7.6!

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PululuK** [comment]
Hi @PierreRambaud 

Is it normal that travisCI is blocked? I have to do something ?

**Comment by PierreRambaud** [comment]
@PululuK It's not normal, it happens sometimes :sob:

**Comment by SD1982** [comment]
Hi @PululuK It seems that there is an issue with Travis can you check this please ?

**Comment by PululuK** [comment]
> @PululuK It's not normal, it happens sometimes sob

Hi @PierreRambaud 
Can you relaunch Travis please? It was green before rebase to 1.7.6.x

**Comment by jolelievre** [comment]
Actually the problem is not from the rebase nor this PR but some fixtures in the tests suites which are not valid any more
Here is the PR that fixes it https://github.com/PrestaShop/PrestaShop/pull/18309

**Comment by jolelievre** [comment]
@PululuK  I'll rebase this PR as soon as the other one is merged 😉

**Comment by PululuK** [comment]
> Actually the problem is not from the rebase nor this PR but some fixtures in the tests suites which are not valid any more
Here is the PR that fixes it #18309

You are in the future ! 
Thanks @jolelievre  @PierreRambaud

**Comment by jolelievre** [comment]
Rebased! should be good this time

**Review by jolelievre — APPROVED** [review]

**Comment by PululuK** [comment]
> Hi @PululuK It seems that there is an issue with Travis can you check this please ?


Hi @SD1982 
It is Done .. Big thanks guys @jolelievre @PierreRambaud !

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
This PR correctly fix #17908 ! Thanks @PululuK !

**Comment by Progi1984** [comment]
Thanks @PululuK

**Comment by Gipielle** [comment]
Hello, this fix works but is not complete,

if you click in the category link now it goes always in modify both (pencil right) and also category name (wrong) category name should go into the cateogoty so you can see list of subcategory.

**Comment by PululuK** [comment]
> Hello, this fix works but is not complete,
> 
> if you click in the category link now it goes always in modify both (pencil right) and also category name (wrong) category name should go into the cateogoty so you can see list of subcategory.

Hi @Gipielle ,

Could you open a new issue dedicated to this? Do not hesitate to tag me please!

Thank you !

**Comment by Gipielle** [comment]
@PululuK done here #18732
Thanks
