### PR TITLE
Fix image configuration

### LINKED ISSUE #34055: BO-PHP version generates an exception when saving Image settings
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After editing some Image settings,when you try to save there is an exception displayed in the BO and it seems related to PHP version since the problem is not reproduced in all PHP versions:

**- PHP v 8.0 & 8.1 & 8.2** :x:

See attached scereenrecord :

https://github.com/PrestaShop/PrestaShop/assets/92626242/c451bce8-9d38-456d-af88-62b05bf780f8

image

**- PHP v 7.4** :heavy_check_mark: 

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/42eaa5c9-4502-4efa-bcf9-0e1929b52d90

### Expected behavior

The exception should not be displayed when Saving the image settings

### Steps to reproduce

1. Make sure you are using in your shop BO php version  8.1
2. Design > Image Settings >  Images generation options section
3. Image format : select Use JPEG
4. Click Save button
5. See Error

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.0 & 8.1 & 8.2

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixes image configuration with new image system NOT enabled. We were doing some things with a field that was not in the form.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Make sure "multiple image formats" feature flag is disabled. Go to BO > Image settings. Save the form. Will work.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #34055
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

File: controllers/admin/AdminImagesController.php [hunk 1]
```diff
@@ -98,7 +98,7 @@ public function init()
 
         $this->canGenerateAvif = $this->get('PrestaShop\PrestaShop\Core\Image\AvifExtensionChecker')->isAvailable();
         $this->isMultipleImageFormatFeatureEnabled = $this->get(FeatureFlagRepository::class)->isEnabled(FeatureFlagSettings::FEATURE_FLAG_MULTIPLE_IMAGE_FORMAT);
-        $this->imageFormatConfiguration = $this->get(ImageFormatConfiguration::class);
+        $this->imageFormatConfiguration = $this->get('PrestaShop\PrestaShop\Core\Image\ImageFormatConfiguration');
```
Comment (jolelievre) [inline controllers/admin/AdminImagesController.php]: Why not keeping this one?
```suggestion
        $this->imageFormatConfiguration = $this->get(ImageFormatConfiguration::class);
```

File: controllers/admin/AdminImagesController.php [hunk 2]
```diff
@@ -680,10 +686,15 @@ protected function _regenerateNewImages($dir, $type, $productsImages = false)
...
+         * In new image system, it's multiple formats. In case of legacy, it's only .jpg.
          *
          * In case of .jpg images, the actual format inside is decided by ImageManager.
          */
-        $configuredImageFormats = $this->imageFormatConfiguration->getGenerationFormats();
+        if ($this->isMultipleImageFormatFeatureEnabled) {
+            $configuredImageFormats = $this->imageFormatConfiguration->getGenerationFormats();
+        } else {
+            $configuredImageFormats = ['jpg'];
+        }
```
Comment (jolelievre) [inline controllers/admin/AdminImagesController.php]: This check is not supposed to be needed `ImageFormatConfiguration` already handles it internally and returns `['jpg']` automatically when the feature flag is disabled, that's what you handled in your previous PR

I think just the modif in `beforeUpdateOptions` should be enough no?

File: controllers/admin/AdminImagesController.php [hunk 3]
```diff
@@ -831,10 +842,15 @@ protected function _regenerateNoPictureImages($dir, $type, $languages)
...
```
Comment (jolelievre) [inline controllers/admin/AdminImagesController.php]:
```suggestion
        $configuredImageFormats = $this->imageFormatConfiguration->getGenerationFormats();
```

File: controllers/admin/AdminImagesController.php (hunk 2 above)
Comment (jolelievre) [reply controllers/admin/AdminImagesController.php]:
```suggestion
        $configuredImageFormats = $this->imageFormatConfiguration->getGenerationFormats();
```

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Hlavtox

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
The auto tests are green :heavy_check_mark: https://github.com/hibatallahAouadni/testing_pr/actions/runs/6313658038
LGTM, QA :heavy_check_mark: 

[pr_34060.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/eef5078f-44d6-4a5b-8751-dce8e777f00a)

Thanks!
