### PR TITLE
Fix permissions for read-only user

### LINKED ISSUE #29001: BO > Permissions - Can't access certains pages with Profile with only View Permission
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After creating a new Profile for an Employee with **ONLY** View permissions, there are some pages that I cannot access.
The pages reloads to Dashboard.

https://user-images.githubusercontent.com/16019289/177819614-3502c825-c954-49e5-8dc2-522b21bd5b68.mov

### Expected behavior

I should be able to access the pages like in version 1.7.8.6.
This is a regression.

### Steps to reproduce

1. Go to BO > Team > Profile
2. Create a new profile "stagiaire"
3. Go to Permissions > Choose "stagiaire" > click on "View" for everything
4. Go to Employees > Create new employee with profile "stagiaire"
5. Log out from your current account and Log Into your "stagiaire" account
6. Go to the following pages, see that only the Dashboard is displayed ❌ 
- orders > delivery slip
- catalog > Products
- Catalog > Categories
- Design > Positions

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Before Symfony 4.4, voters with many attributes acted as a `OR` condition, and when it was migrated in ff96226eae149d58b34ca6c5228b846595d05914 has been replaced by an `AND` condition. Solution was to migrate back to the `OR` condition
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29001 
| How to test?      | See #29001 .

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php [hunk 1]
```diff
@@ -93,7 +93,7 @@ class ProductController extends FrameworkBundleAdminController
     /**
      * Shows products listing.
      *
-     * @AdminSecurity("is_granted(['read'], request.get('_legacy_controller'))")
+     * @AdminSecurity("is_granted('create', 'ADMINPRODUCTS_') || is_granted('update', 'ADMINPRODUCTS_') || is_granted('read', 'ADMINPRODUCTS_')")
```
Comment (atomiix) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]: Why not using `request.get('_legacy_controller')` here?
```suggestion
     * @AdminSecurity("is_granted('create', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller')) || is_granted('read', request.get('_legacy_controller'))")
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php [hunk 2]
```diff
@@ -44,7 +44,7 @@ class DeliveryController extends FrameworkBundleAdminController
      *
      * @Template("@PrestaShop/Admin/Sell/Order/Delivery/slip.html.twig")
      * @AdminSecurity(
-     *     "is_granted('read', request.get('_legacy_controller')) && is_granted('update', request.get('_legacy_controller')) && is_granted('create', request.get('_legacy_controller')) && is_granted('delete', request.get('_legacy_controller'))",
+     *     "is_granted('read', request.get('_legacy_controller')) || is_granted('update', request.get('_legacy_controller')) || is_granted('create', request.get('_legacy_controller')) || is_granted('delete', request.get('_legacy_controller'))",
```
Comment (atomiix) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php:47]: I think you can do the same for the action [`generatePdfAction`](https://github.com/PrestaShop/PrestaShop/blob/8.0.x/src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController.php#L92)?

**Review by atomiix — COMMENTED** [review]
Shame on me for using `&&` instead of `||` 😅
Just a question and probably another place where we should use `||` instead of `&&`

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 3]
```diff
@@ -99,6 +99,7 @@ class ProductController extends FrameworkBundleAdminController
      *
      * URL example: /product/catalog/40/20/id_product/asc
      *
+     * @AdminSecurity("is_granted('create', 'ADMINPRODUCTS_') || is_granted('update', 'ADMINPRODUCTS_') || is_granted('read', 'ADMINPRODUCTS_')")
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php]: As @atomiix suggested on another file you can use `request.get('_legacy_controller')` instead of the hard-coded `'ADMINPRODUCTS_'`

Comment (FabienPapet) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]: Done

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php (hunk 1 above)
Comment (FabienPapet) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]: Done

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @FabienPapet ,

Thanks for your PR !

I have now access to all my pages and their tabs as a read-only employee 👍 

It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
Thank you @FabienPapet well done 👏 

Thanks for the tests @florine2623 :)
