### PR TITLE
Avoid setting height to 0 if height isn't defined on product dropzone

### LINKED ISSUE #24809: The element height which contains Product images is not calculated when you access to product edit by clicking on price or qty in the Products list
#### Describe the bug

When I access the details of a product by clicking on the **product quantity** or **product price** in the product list, I arrive to the quantity or price tab. Going then to the **Basic Settings** tab, the element height is not calculated. I need to refresh the page.

#### Expected behavior

The element height should be calculated

image

#### Steps to Reproduce

1. Go to admin > Catalogue > Products
2. Click on a product quantity in the list
3. From the tab where you arrive in the product page, go to the essential tab
4. See error > the height is not calculated)

**Screenshots**
https://www.awesomescreenshot.com/video/4016852?key=845385fb30ee981e0928c692b6ec31ab

image

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The height was wrong if the element doesn't exist on the page or is hidden, it should be avoided if the current height === 0px
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24809.
| How to test?      | Go on product page, go on price tab, refresh the page and go on basic tab, the height should be fine
| Possible impacts? | Product page v1 dropzone

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24848)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
@NeOMakinG As seen on Slack, a small issue that can be fixed on this PR : 

When the upload fails (for example : image too large), an horizontal line is displayed and enlarge my screen on the right, causing the display of the scrollbar. This happens with and without the PR.

See screenshot : 

image

**Comment by NeOMakinG** [comment]
@Robin-Fischer-PS should be fine now

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 1]
```diff
@@ -1335,9 +1335,13 @@ window.imagesProduct = (function () {
       dropZoneElem.css('height', '');
       const closedHeight = dropZoneElem.outerHeight();
       const realHeight = dropZoneElem[0].scrollHeight;
-      dropZoneElem.css('height', oldHeight);
 
-      return (realHeight > closedHeight);
+      console.log(realHeight, closedHeight);
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/bundle/product/form.js]: :thinking:

Comment (NeOMakinG) [reply admin-dev/themes/default/js/bundle/product/form.js]: Oof

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 2]
```diff
@@ -1335,9 +1335,12 @@ window.imagesProduct = (function () {
...
       const closedHeight = dropZoneElem.outerHeight();
       const realHeight = dropZoneElem[0].scrollHeight;
-      dropZoneElem.css('height', oldHeight);
 
-      return (realHeight > closedHeight);
+      if (oldHeight !== '0px') {
+        dropZoneElem.css('height', oldHeight);
+      }
+
+      return (realHeight > closedHeight) && dropZoneElem.find('.dz-preview:not(.openfilemanager)').length;
```
Comment (matks) [inline admin-dev/themes/default/js/bundle/product/form.js:1343]: If `dropZoneElem.find('.dz-preview:not(.openfilemanager)')` cannot be found, is it OK to call `.length()` on it?

Comment (NeOMakinG) [reply admin-dev/themes/default/js/bundle/product/form.js:1343]: Yep because JQuery returns an array of elements, the array length will be 0 with a previousElement key

Comment (Progi1984) [reply admin-dev/themes/default/js/bundle/product/form.js:1343]: Could you move the selector to a selector map ?

**Review by Progi1984 — COMMENTED** [review]
A small feedback and it's ok

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 2 above)
Comment (NeOMakinG) [reply admin-dev/themes/default/js/bundle/product/form.js:1343]: @Progi1984 nop, it's from legacy folder, I won't create a map for this, it's out of the scope of the PR and inside a folder that should be deprecated in the future

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @NeOMakinG !

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @florine2623
