### PR TITLE
Fixed Recalculate Shipping when the carrier of an order is changed

### LINKED ISSUE #25565: 1.7.7.6 - ps_order_recalculate_shipping set to NO - Not working correctely
#### Describe the bug

ps_order_recalculate_shipping set to NO - Not working correctely

#### Expected behavior

When the configuration "Recalculate shipping costs after editing the order" is defined to "No" and the user edits the carrier of an order, the shipping cost of the order remains the same. The order total and invoice are not impacted.
Specs: https://github.com/PrestaShop/prestashop-specs/pull/258

#### Steps to Reproduce

0 - Set "Recalculate shipping costs after editing the order" to "NO".
1 - Make an order with a free shipping carrier and pay with bankwire for instance;
2 - Go to the backoffice set the order as "Processing in progress";
3 - Change the carrier to a paid one and introduce a tracking number;
4 - Set the order as "Shipped";

After you change the order status to "Shipped" it will show an additional payment that will match the shipping price of the carrier selected at step 3.

#### Additional information

* PrestaShop version: 1.7.7.6
* PHP version: 7.2

**Server info:**

- Server information Linux 160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64
- Server software version: Apache
- Memory limit: 1024M
- Max execution time: 600
- Upload Max File size: 128M
- PHP version: 7.2.24-0ubuntu0.18.04.8

**Database information**

- MySQL version: 5.7.35-0ubuntu0.18.04.1
- MySQL server: 127.0.0.1
- Tables prefix: ps_
- MySQL engine: InnoDB
- MySQL driver: DbPDO

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed Recalculate Shipping when the carrier of an order is changed
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25565 
| How to test?      | Cf. #25565 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26481)

## Specs

https://github.com/PrestaShop/prestashop-specs/pull/258

we can test this issue https://github.com/PrestaShop/PrestaShop/issues/24598 when testing this PR

### CODE REVIEW

File: classes/order/OrderHistory.php [hunk 1]
```diff
@@ -388,26 +388,22 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
                     $payment->order_reference = Tools::substr($order->reference, 0, 9);
                     $payment->id_currency = $order->id_currency;
                     $payment->amount = $rest_paid;
-
-                    if ($order->total_paid != 0) {
-                        $payment->payment_method = $payment_method->displayName;
-                    } else {
-                        $payment->payment_method = null;
-                    }
+                    $payment->payment_method = $order->total_paid != 0 ? $payment_method->displayName : null;
```
Comment (jolelievre) [inline classes/order/OrderHistory.php]: I don't understand why you need to change this method? Since the bug is related to carrier change and shipping cost, not the payment method nor the order state changes? 🤔

File: classes/order/OrderHistory.php [hunk 2]
```diff
@@ -388,26 +388,22 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
...
+                    $payment->conversion_rate = $order->conversion_rate;
+                    $payment->save();
 
                     // Update total_paid_real value for backward compatibility reasons
-                    if ($payment->id_currency == $order->id_currency) {
-                        $order->total_paid_real += $payment->amount;
-                    } else {
-                        $order->total_paid_real += Tools::ps_round(Tools::convertPrice($payment->amount, $payment->id_currency, false), Context::getContext()->getComputingPrecision());
-                    }
+                    $order->total_paid_real += $rest_paid;
```
Comment (jolelievre) [inline classes/order/OrderHistory.php:396]: Why do you remove the currency conversion? Do you assume payment and order will necessarily have the same currency?
If the use case was handled I guess it's because it can happen.

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 3]
```diff
@@ -565,15 +565,13 @@ private function updateOrderInvoices(Order $order, Cart $cart, int $computingPre
                 if ($freeShipping) {
                     $invoice->total_discount_tax_excl = $invoice->total_discount_tax_excl - $invoice->total_shipping_tax_excl + $totalShippingTaxExcluded;
                     $invoice->total_discount_tax_incl = $invoice->total_discount_tax_incl - $invoice->total_shipping_tax_incl + $totalShippingTaxIncluded;
+                } else {
```
Comment (jolelievre) [inline src/Adapter/Order/OrderAmountUpdater.php:568]: This fixes the invoice total update, but wasn't there an issue on Order total as well (based on the issue)

I checked and the order total is computed the same way as here so it's logical but the issue seemed to indicate that there were some problems on Order total as well

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature [hunk 4]
```diff
@@ -19,11 +19,12 @@ Feature: Order from Back Office (BO)
     And a carrier "default_carrier" with name "My carrier" exists
     And a carrier "price_carrier" with name "My cheap carrier" exists
     And a carrier "weight_carrier" with name "My light carrier" exists
+    And I enable carrier "weight_carrier"
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature]: Be careful I'm not sure you should enable the weight carrier in the Background
Because there is a system in the cart that automatically selects the cheapest carrier by default, so it could impact some shipping costs unexpectedly

It is safer to enable it only in the scenario in which you are going to use it

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature [hunk 5]
```diff
@@ -54,17 +55,81 @@ Feature: Order from Back Office (BO)
     And order "bo_order1" should have following details:
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature:54]: So it seems `weight_carrier` was associated even though it was not enabled 🤔
This is weird indeed, it shouldn't be possible I guess we have no checks that ensure the carrier is enabled, we should add some

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature [hunk 6]
```diff
@@ -54,17 +55,81 @@ Feature: Order from Back Office (BO)
...
+      | total_discounts_tax_incl | 0.0    |
+      | total_paid_tax_excl      | 43.800 |
+      | total_paid_tax_incl      | 46.430 |
+      | total_paid               | 46.430 |
+      | total_paid_real          | 46.430 |
+      | total_shipping_tax_excl  | 5.0    |
+      | total_shipping_tax_incl  | 5.30   |
+    When I update order "bo_order1" Tracking number to "TEST1234" and Carrier to "default_carrier"
+    Then order "bo_order1" should have "default_carrier" as a carrier
+    ## Shipping equals to 0 as 2 products in cart have no weight
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature]: This comment is not adapted at all to the situation 😅

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature [hunk 7]
```diff
@@ -54,17 +55,81 @@ Feature: Order from Back Office (BO)
...
+      | total_paid_real          | 46.430 |
+      | total_shipping_tax_excl  | 7.0    |
+      | total_shipping_tax_incl  | 7.42   |
+    Then order "bo_order1" has 1 payments
+    And order "bo_order1" payment in first position should have the following details:
+      | paymentMethod  | Dummy payment   |
+      | transactionId  |                 |
+      | amount         | $46.43          |
+      | invoiceNumber  | #IN000001       |
+    ## Change to paid order status
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature:115]: Wow, this is a really weird behaviour... The order was already considered paid (vie the `Processing in progress` state). But the order was modified so a payment was missing

And now you change the status again and it considers again that the rest has been paid, this is a very dangerous behaviour that could lead merchant to lose a lot of money... I don't think we can assume a payment has been made simply because the order has been shipped

The automatic payment should only happen once IMHO, but anyway it's a big behaviour change that needs to be discussed with @PrestaShop/product-team

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature [hunk 8]
```diff
@@ -92,11 +157,89 @@ Feature: Order from Back Office (BO)
...
+      | total_discounts_tax_incl | 0.0    |
+      | total_paid_tax_excl      | 43.800 |
+      | total_paid_tax_incl      | 46.430 |
+      | total_paid               | 46.430 |
+      | total_paid_real          | 46.430 |
+      | total_shipping_tax_excl  | 5.0    |
+      | total_shipping_tax_incl  | 5.30   |
+    When I update order "bo_order1" Tracking number to "TEST1234" and Carrier to "default_carrier"
+    Then order "bo_order1" should have "default_carrier" as a carrier
+    ## Shipping equals to 0 as 2 products in cart have no weight
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature]: Again the comment is not adapted

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @Progi1984 Nice improvements in the behat tests
However there are some changes in the code that really worry me 🤔

File: classes/order/OrderHistory.php (hunk 1 above)
Comment (Progi1984) [reply classes/order/OrderHistory.php]: I improve just the code in using it. Boy Scout rule.

File: classes/order/OrderHistory.php (hunk 2 above)
Comment (Progi1984) [reply classes/order/OrderHistory.php:396]: Check the new line 392. :)

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature (hunk 4 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature (hunk 8 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature (hunk 7 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature:115]: :warning: I don't change this behavior. 

It's done in `classes/order/OrderHistory` (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/OrderHistory.php#L373-L410),
* When you change the status of an order, 
* When the new order status is "Paid"
* When there are already invoices
* When there is a "rest to be paid",
* Then a new order payment is added 

This behavior exists since (nearly) 10 years (1.5.5.0) => https://github.com/PrestaShop/PrestaShop/commit/ccb07311262bf06b9b06180a7f10f9dd9d82cc69#diff-32c0a9dbcd2665ee1a3e6258057b294d4653a6f84a4453cc32c4886ee2e9f2d7.

**Review by Progi1984 — COMMENTED** [review]
...

File: tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature (hunk 7 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_shipping_recalculate.feature:115]: Ok, my bad ^^

**Review by jolelievre — APPROVED** [review]
Nice bro!

File: classes/order/OrderHistory.php [hunk 9]
```diff
@@ -375,11 +375,11 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
...
         if ($new_os->paid == 1) {
-            $invoices = $order->getInvoicesCollection();
             if ($order->total_paid != 0) {
                 $payment_method = Module::getInstanceByName($order->module);
             }
 
+            $invoices = $order->getInvoicesCollection();
             foreach ($invoices as $invoice) {
                 /** @var OrderInvoice $invoice */
                 $rest_paid = $invoice->getRestPaid();
```
Comment (sowbiba) [inline classes/order/OrderHistory.php:385]: A question : what is RestPaid ? Is it the amount left to pay or the amount paid for the invoice ?

**Review by sowbiba — APPROVED** [review]
Just a question. Looks good for me

File: classes/order/OrderHistory.php (hunk 9 above)
Comment (Progi1984) [reply classes/order/OrderHistory.php:385]: I don't know. I think it is the amount left to pay

**Review by PierreRambaud — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello,

The issue of this PR is fixed. 
See screen-record below : 
https://watch.screencastify.com/v/xguKbWqLM2YauSlcMb2B

I verified also theses issues related to it : #24598, #25418, #21267, #20744 + an exploratory tests + run of automated tests related to Orders + multistore

LGTM, QA :heavy_check_mark: 
Good job.

Thanks,

**Comment by Progi1984** [comment]
Thanks @HanaRebaiQA
