### PR TITLE
Handle bad theme error nicely

### LINKED ISSUE #14326: Command EnableThemeHandler
**Describe the bug**

Using a string in the php reset function.

**To Reproduce**
1. Duplicate the classic theme to create a new theme
2. Arrange for the new theme to install normally.
3. Use the classic theme.
4. Remove in the new theme theme.css (in new_theme/assets/css/theme.css).
5. Define "_PS_MODE_DEV_" on true
6. Enable the new theme.

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: 7.1
bug_1

Value of $errors :

image

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | If Theme Install fails and return a string error message, displays it nicely
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14326
| How to test?  | See ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14331)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php [hunk 1]
```diff
@@ -509,7 +509,7 @@ private function handleEnableThemeException(ThemeException $e)
                     'Admin.Modules.Notification',
                     [
                         '%action%' => strtolower($this->trans('Install', 'Admin.Actions')),
-                        '%module%' => $e->getModuleName(),
+                        '%module%' => ($e instanceof FailedToEnableThemeModuleException) ? $e->getModuleName() : '',
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: Additionnal bugfix (found while working on this PR) :
If `$e` was an instance of something else than `FailedToEnableThemeModuleException` (example: `CannotEnableThemeException`) this code would fail

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: Why do we not add unit tests to prevent this kind of situation?

Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: Because it's a Controller, so I think E2E tests are a better solution to test it, don't you think ?

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: I was talking about `EnableThemeHandler.php` sorry ^^

Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: All right 😄
Unfortunately, we only were able to build a proper setup / method of using Behat at the end of 1.7.6 development phase . For each new page we'll migrate in 1.7.7, we'll have every Command (and most Queries) tested with Behat.
For the pages migrated before, we'll use pauses time windows (such as waiting for code review) to complete the coverage.

However this one will probably be a nightmare to test 🤔as a Theme installation involves the database, the filesystem, file uploads...

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: If it's unit tests we don't care what we are using (db, fs, etc).

Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: We use Behat here because any Handler is actually part of the Adapter layer which uses extensively legacy classes a.k.a "static classes paradise" and is a nightmare to unit test 😢so our Behat tests are basically "black box testing" as isolation is veeeeery hard to achieve

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: Not sure file like `src/Core/Domain/Theme/CommandHandler/EnableThemeHandler.php` are hard to unit test :thinking:

Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/ThemeController.php:512]: Oh 😶you're right. Usually all Handlers are in Adapter context but not this one (probably because we could get rid of all legacy logic) 😄

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PierreRambaud for review and @sarahdib for QA
