### PR TITLE
Fix BO - New currency page 

### LINKED ISSUE #18882: BO - New currency page issues
#### Describe the bug

The migration of the admin currency page to symfony does not seem to be finished.

#### Expected behavior

Finish migration and make the currency page great again.

#### Steps to Reproduce

1. Go to currency page in BO
2. Id column is missing
3. Bulk action is missing (delete, disable, enable)
4. Show SQL query is missing
5. Export to SQL Manager is missing
6. We cannot filter by currency name
7. We cannot filter by cyrrency symbol

**Screenshots**

currency

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | The migration of the admin currency page to symfony does not seem to be finished.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18882.
| How to test?  | See #18882 

## How to test ?

- [x] Go to currency page in BO
- [x] Test SQL action : Show SQL query, Export to SQL Manager is missing and List refresh
- [x]  Test filters : Id, currency name symbol, etc etc
- [x] Test Bulk action delete, disable, enable.  NOTE : You cant delete or disable the default shop currency.

imporve_currency (1)

### 👷🏽 don't forget to build assets !
See https://devdocs.prestashop.com/1.7/development/compile-assets/#build-all-assets-at-once

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18883)

### CODE REVIEW

File: src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: Don't forget `declare(strict_types=1);` on new files.

File: src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+    /**
+     * @var bool
+     */
+    private $expectedStatus;
+
+    /**
+     * @param int[] $currencyIds
+     * @param bool $expectedStatus
+     */
+    public function __construct(array $currencyIds, $expectedStatus)
```
Comment (Progi1984) [inline src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php]:
```suggestion
    public function __construct(array $currencyIds, bool $expectedStatus)
```

File: src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+    {
+        $this->assertStatusIsBool($expectedStatus);
```
Comment (Progi1984) [inline src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php]:
```suggestion
```

File: src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php (hunk 1 above)
Comment (PululuK) [reply src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: Big thanks man !
But ... is it really useful in my case  🤔 ?

Comment (Progi1984) [reply src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: It's a good practice we apply for all new files.

Comment (PululuK) [reply src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: Thanks @Progi1984 ... where can I find that in the PS Doc please ?

Comment (jolelievre) [reply src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: 😂 He got you @Progi1984 Seems like you're up for updating the doc 😛

Comment (eternoendless) [reply src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: Done here: https://github.com/PrestaShop/docs/pull/518

Comment (PululuK) [reply src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:26]: Thanks a lot @eternoendless  !

File: src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+            if (0 >= $entity->id) {
+                throw new CurrencyNotFoundException(sprintf('Currency object with id "%s" has not been found for deletion.', $currencyId->getValue()));
+            }
+
+            $this->assertDefaultCurrencyIsNotBeingRemoved($currencyId->getValue());
+            $this->assertDefaultCurrencyIsNotBeingRemovedFromAnyShop($entity);
+
+            try {
+                if (false === $entity->delete()) {
```
Comment (jolelievre) [inline src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php:84]: You should store the ids of failed deletion, and throw a dedicated exception that will contain an array of failed ids
If not, one falsy deletion will prevent all the remaining ones

There are a few handlers that do the same like `BulkDeleteAttachmentsHandler` (although some don't implement this, but they should) The you should manage the exception error message with something similar to https://github.com/PrestaShop/PrestaShop/blob/a9616c5549e04cb0982c17976a1e15d56548e1b2/src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttachmentController.php#L320

File: src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php [hunk 5]
```diff
@@ -0,0 +1,129 @@
...
+                throw new CurrencyNotFoundException(sprintf('Currency object with id "%s" has not been found for toggling.', $currency->getValue()));
+            }
+
+            if ($entity->active) {
+                $this->assertDefaultCurrencyIsNotBeingDisabled($entity);
+                $this->assertDefaultCurrencyIsNotBeingDisabledFromAnyShop($entity);
+            }
+
+            try {
+                if (false === $entity->toggleStatus()) {
```
Comment (jolelievre) [inline src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php:89]: You should not use the `toggleStatus` function but rather use `$command->getStatus()` So that the command can enable OR disable but not do both depending on the entity status, the status applied will not be consistent on all the entities
Using `$command->getStatus()` will match the expected behaviour of the grid actions for `Enable selection` `Disable selection`

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+{
+    /**
+     * @var int
+     */
+    private $defaultCurrencyId;
+
+    /**
+     * @param int $defaultCurrencyId
+     */
+    public function __construct($defaultCurrencyId)
```
Comment (PierreRambaud) [inline src/Adapter/Currency/CommandHandler/BulkDeleteCurrenciesHandler.php]:
```suggestion
    public function __construct(int $defaultCurrencyId)
```

File: src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+{
+    /**
+     * @var int
+     */
+    private $defaultCurrencyId;
+
+    /**
+     * @param int $defaultCurrencyId
+     */
+    public function __construct($defaultCurrencyId)
```
Comment (PierreRambaud) [inline src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php:52]:
```suggestion
    public function __construct(int $defaultCurrencyId)
```

File: src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php [hunk 8]
```diff
@@ -0,0 +1,131 @@
...
+            throw new CannotDisableDefaultCurrencyException(sprintf('Currency with id "%s" is the default currency and cannot be disabled.', $currency->id));
+        }
+    }
+
+    /**
+     * @param Currency $currency
+     *
+     * @throws DefaultCurrencyInMultiShopException
+     */
+    private function assertDefaultCurrencyIsNotBeingDisabledFromAnyShop(Currency $currency)
```
Comment (PierreRambaud) [inline src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php]: it's a duplicate from BulkDeleteCurrenciesHandler, maybe use an abstract method :thinking:

File: src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml [hunk 9]
```diff
@@ -80,3 +80,21 @@ admin_currencies_get_reference_data:
     _controller: 'PrestaShopBundle:Admin\Improve\International\Currency:getReferenceData'
     _legacy_controller: AdminCurrencies
     _legacy_link: AdminCurrencies:getReferenceData
+
+admin_currencies_bulk_delete:
+  path: /bulk-delete
+  methods: [POST]
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml]:
```suggestion
  methods: [DELETE]
```
or POST and DELETE for the moment? :thinking:

Comment (Progi1984) [reply src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml]: It's a BC to remove method ;)

Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml]: It's a new path, can't be a BC break :thinking:

Comment (Progi1984) [reply src/PrestaShopBundle/Resources/config/routing/admin/improve/international/currencies.yml]: Oops for me, in this case.

File: src/Core/Domain/Currency/Exception/CurrencyConstraintException.php [hunk 10]
```diff
@@ -72,10 +72,21 @@ class CurrencyConstraintException extends CurrencyException
...
+     */
+    const ISO_CODES_MISMATCH = 8;
+
     /**
      * Code used when an invalid precision is used (positive integer expected)
      *
      * @see Precision
      */
-    const INVALID_PRECISION = 8;
+    const INVALID_PRECISION = 9;
```
Comment (Progi1984) [inline src/Core/Domain/Currency/Exception/CurrencyConstraintException.php]: @PululuK Please don't change value for constant.

Comment (PululuK) [reply src/Core/Domain/Currency/Exception/CurrencyConstraintException.php]: See https://github.com/jolelievre/PrestaShop/blob/currency-edition/src/Core/Domain/Currency/Exception/CurrencyConstraintException.php#L86 
Merged here : https://github.com/PrestaShop/PrestaShop/pull/14972

Comment (Progi1984) [reply src/Core/Domain/Currency/Exception/CurrencyConstraintException.php]: :ok_hand:

**Review by Progi1984 — DISMISSED** [review]

File: src/Core/Domain/Currency/Exception/CurrencyConstraintException.php (hunk 10 above)
Comment (PululuK) [reply src/Core/Domain/Currency/Exception/CurrencyConstraintException.php]: By cons it is very strange, because I do not have that on the develop branch https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Currency/Exception/CurrencyConstraintException.php#L80, while it  https://github.com/jolelievre/PrestaShop/blob/currency-edition/src/Core/Domain/Currency/Exception/CurrencyConstraintException.php#L86 was merged  here #14972

ping @jolelievre @PierreRambaud

Comment (Progi1984) [reply src/Core/Domain/Currency/Exception/CurrencyConstraintException.php]: Correct, I checked ;) Removed here : https://github.com/PrestaShop/PrestaShop/commit/ca475439c846940fe9e42254bf0dd04204a11a6e#diff-f5c3c83f1af68a05ac6ab2068e1b9c6d

Could you adapt your code ?

Comment (PululuK) [reply src/Core/Domain/Currency/Exception/CurrencyConstraintException.php]: Done !

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

File: src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php [hunk 11]
```diff
@@ -0,0 +1,88 @@
...
+        return $this->expectedStatus;
+    }
+
+    /**
+     * @param int[] $currencyIds
+     */
+    private function setCurrencies(array $currencyIds)
+    {
+        if (empty($currencyIds)) {
+            throw new CurrencyConstraintException('Currencies must be provided in order to toggle their status');
```
Comment (jolelievre) [inline src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php]: You should have an exception code here like you did with `CurrencyConstraintException::EMPTY_BULK_DELETE` This way you can display an appropriate error message in the controller by matching the exception class and code (by the way this part is missing for now).

I think a common code could be enough `CurrencyConstraintException::EMPTY_BULK_ACTION` for both bulk delete and bulk toggle since the error message can also be common, something like `Please select at least one currency for bulk action.`

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php [hunk 12]
```diff
@@ -462,6 +464,67 @@ private function getSettingsFormHandler()
...
+                $currenciesIds,
+                $expectedStatus
+            ));
+
+            $this->addFlash(
+                'success',
+                $this->trans('The status has been successfully updated.', 'Admin.Notifications.Success')
+            );
+        } catch (CurrencyException $e) {
+            $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php:496]: You should update `getErrorMessageForException` to manage the new exception code you added

**Review by jolelievre — COMMENTED** [review]
@PululuK Sorry I know this one has already been double-approved

I had started a review but forgot to post it, so I don't block the PR but those improvement would be nice, they can be done in a separate PR but if you have time to to do it in this one it will gain some QA time ^^

File: src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php (hunk 5 above)
Comment (PululuK) [reply src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php:89]: @jolelievre See https://github.com/PululuK/PrestaShop/blob/patch-4/src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php#L69
The status is updated only when necessary.

**Comment by PululuK** [comment]
I am not sure of some translations in the exception messages. We will need your help @LouiseBonnard please !

File: src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php (hunk 5 above)
Comment (jolelievre) [reply src/Adapter/Currency/CommandHandler/BulkToggleCurrenciesStatusHandler.php:89]: My bad! I didn't noticed it 😅

File: src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Domain/Currency/Command/BulkToggleCurrenciesStatusCommand.php]: As @Progi1984 suggested, why not using strict type `bool` here? It would avoid checking it manually with `assertStatusIsBool`

File: src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php [hunk 13]
```diff
@@ -74,10 +79,23 @@ protected function getName()
...
+                    ])
+            )
+            ->add(
+                (new DataColumn('id_currency'))
+                    ->setName($this->trans('ID', [], 'Admin.Global'))
+                    ->setOptions([
+                        'field' => 'id_currency',
+                    ])
+            )
+            ->add((new DataColumn('name'))
```
Comment (jolelievre) [inline src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php:95]: Be careful since you changed the column here, this will remove a behaviour from https://github.com/PrestaShop/PrestaShop/blob/3112ecde59959ab42fa6ee9ea23fcdd9278258c2/src/Core/Currency/CurrencyGridDataFactory.php#L93

It is supposed to add `Edited` when a currency has been edited (different data than CLDR repository), and it adds an icon for unofficial currencies. It's not the cleanest implementation I admit (especially the hard coded HTML for icon), a better way to do this would be to create a custom column twig but I struggled with it I don't remember why.. 🤔

Anyway you can just fix this by changing the `CurrencyGridDataFactory` and update the `name` field instead of `currency` in the records data.

**Review by jolelievre — COMMENTED** [review]
Thanks for the modifications @PululuK 

Two last comments, and then it's perfect for me 😉

File: src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php (hunk 13 above)
Comment (PululuK) [reply src/Core/Grid/Definition/Factory/CurrencyGridDefinitionFactory.php:95]: Nice catch @jolelievre  ! Thank you so much man.

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php [hunk 14]
```diff
@@ -500,6 +565,14 @@ private function getErrorMessages(Exception $e)
                     'This currency already exists.',
                     'Admin.International.Notification'
                 ),
+                CurrencyConstraintException::EMPTY_BULK_TOGGLE => $this->trans(
+                    'Currencies must be provided in order to toggle their status',
+                    'Admin.International.Notification'
+                ),
+                CurrencyConstraintException::EMPTY_BULK_DELETE => $this->trans(
+                    'At least one currency must be provided for deleting',
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Can you please explain in which context do those exceptions appear? Is it when a user is performing an action but without having selected a currency?

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: > Is it when a user is performing an action but without having selected a currency?

Exactly ! For bulk actions only, delete et toggle status actions.

**Review by jolelievre — DISMISSED** [review]
Great work @PululuK 
Thanks

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php (hunk 14 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Noted, thanks! Symfony pages don't allow bulk actions (delete or enable/disable) when no item is selected, see screenshot below.

Capture d’écran 2020-05-26 à 18 22 37

On the Legacy pages, the error notification is _You must select at least one element to delete._. So I suggest keeping the Symfony behavior. :-)

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Okay ! It's good for me then ... Thanks @LouiseBonnard

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: @LouiseBonnard it is indeed blocked on the front side, so this error shouldn't happen But it's better to manage it in case the template is overridden or modified by a module It's better to have a safeguard on the server side as well
So as you said the appropriate wording would be the same as in legacy `You must select at least one element to delete.` in `Admin.Notifications.Error` domain?
What about the the toggle bulk action, I couldn't find a wording for this one, and since we don't know if the action was enable or disable maybe we could have a generic wording like `You need to select at least one element to use the bulk action.` (in `Admin.Notifications.Error` as well)

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Well, it's a bit inconsistent to talk about 'bulk action' and make it works for a single item... but I've checked and it happens for all grids in the software so let's keep on being consistent in our inconsistency, aha! So okay for:

1. _You must select at least one element to delete._ in _Admin.Notifications.Error_
1. _You must select at least one element to perform a bulk action._ in _Admin.Notifications.Error_

Many thanks, @jolelievre & @PululuK. :-)

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Thanks @LouiseBonnard, But ... we need two messages, one when no item is selected during mass deletion and the other when changing status. Otherwise, a single common message for the two cases.

> 1. You must select at least one element to delete. in Admin.Notifications.Error

It is ok for : bulk delete action

> 2. You must select at least one element to perform a bulk action. in Admin.Notifications.Error

Are you sure you want to use this for status? Why not common between the two cases?

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: _You must select at least one element to perform a bulk action._ works for both cases: bulk delete action and bulk disable/enable action. What do you think?

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: LGTM  thanks @LouiseBonnard !  @jolelievre WDYF ?

Comment (Junebyun) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: @LouiseBonnard 'Can't find the domain of these 2 strings.
The rest of the wording is ok!

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: See https://github.com/PrestaShop/PrestaShop/pull/18883#discussion_r431121110 please

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: I'm waiting for confirmation from @jolelievre (or someone else). After that I will update my PR

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: These are new wording, that's why you can't find them The question is/are do they need modification? Or are there existing wording that can be used? (I couldn't find some)
And, lastly, what domain should they be in?

Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: @jolelievre  See https://github.com/PrestaShop/PrestaShop/pull/18883#discussion_r431121110 please !

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: I didn't see Louise's response But I think we can go for `You must select at least one element to perform a bulk action.` (only one new wording this way, and reusable in many cases)
It only leaves us with the domain `Admin.International.Notification` or `Admin.Notifications.Error` Since it's a generic one maybe the second one is better

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: Yep sorry @PululuK I saw it 30sec after ^^ I think you can make the modification with `You must select at least one element to perform a bulk action.` and `Admin.Notifications.Error`
As it has high chances to be validated, and we will just have to wait for wording validation

Thanks again for your commitment and patience ;)

**Review by LouiseBonnard — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php (hunk 14 above)
Comment (PululuK) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: > Thanks again for your commitment and patience ;)

Don't worry @jolelievre  I am a poet... not a web developer 😉

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by Junebyun — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM thanks @PululuK !!

**Comment by PululuK** [comment]
> LGTM thanks @PululuK !!

Thank you @SD1982 
But as seen with @matks see https://github.com/PrestaShop/PrestaShop/issues/18882#issuecomment-635821168 , this is an improvement proposal and not a bug fix. So we need product team validation
Thank you all for your time and patience.

ping @MatShir @LouiseBonnard @colinegin

**Comment by MatShir** [comment]
Go, Go, Go ! Already approved and approved a second time :+1:

**Comment by Progi1984** [comment]
Thanks @PululuK

**Comment by SimonGrn** [comment]
This broke our automated tests when you changed a class name in the markup :sob: 
We'll fix it, no worries.

Could you please remember to ping the QA team when you touch the markup ? Thanks a lot !

**Comment by PululuK** [comment]
> This broke our automated tests when you changed a class name in the markup sob
> We'll fix it, no worries.
> 
> Could you please remember to ping the QA team when you touch the markup ? Thanks a lot !

Hi @SimonGrn, 
I'm sorry, but I don't know what you're talking about, could you add that to the contribution guide please ? https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/

Let me know if I need to do something
Thank you

**Comment by SimonGrn** [comment]
> Hi @SimonGrn,
> I'm sorry, but I don't know what you're talking about, could you add that to the contribution guide please ? https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/
> 
> Let me know if I need to do something
> Thank you

If I'm not mistaken, [this change](https://github.com/PrestaShop/PrestaShop/pull/18883/files#diff-42325e7abaac7e50a35ade88214eaaeaR93) modified the final markup.
We use the HTML markup to drive our automated tests (you can see in the [last `develop` run](https://nightly.prestashop.com/report/383) what broke) to verify currency pages are working normally.
When we know it in advance we can adapt our tests but we didn't notice this one in time.

I'll add it in the devdocs !
