### PR TITLE
Do not use virtual cart for saving quantity in stock

### LINKED ISSUE #16840: OrderDetail->product_quantity_in_stock is wrong
**Describe the bug**
This commit screwed up the logic of computing items-in-stock quantity.
https://github.com/PrestaShop/PrestaShop/commit/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9#diff-706c99b0aadf150c801cec8a83a90cc1

Wrong line (1.7.6.2):
`$product_quantity = (int)Product::getQuantity($this->product_id, $this->product_attribute_id, null, $cart);`

Correctly functioning (from 1.6.1.23):
`$product_quantity = (int)Product::getQuantity($this->product_id, $this->product_attribute_id);`

**To Reproduce**
1. Make a product, set quantity to 1.
2. Check ps_stock_available, search the id_product, should be like this: quantity: 1, physical_quantity: 1, reserved_quantity: 0.
3. Order 1 piece of the product.
4. Go to order detail in BO, you will see a warning that the product you ordered was not/is not in stock. You also won't see the blue circle under the products quantity in the product list.
5. Check ps_order_detail, search the id_product and id_order, you will find **product_quantity: 1, product_quantity_in_stock: 0**.  But it should be **product_quantity: 1, product_quantity_in_stock: 1**.
6. Now, try it in older Prestashop or try it with the mentioned line change in classes/order/OrderDetail.php. It will work fine.

I do not want to make a PR, I don't know why this change was introduced, but on my side, I reverted it and I don't see any abnormalities.

**Additional information**
PrestaShop version: 1.7.6.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | **product_quantity_in_stock** in OrderDetail table should save data about how many pieces of the product were in stock at the time of ordering. This behavior was broken (by accident) in non-related PR on 27 Feb 2018. We should not use virtual cart in this case.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #16840
| How to test?      | See below
| Possible impacts? | -

**How to test:**
- Make Product A with quantity 0, Product B with quantity 1, Product C with quantity 2.
- Order all of them.
- Go to **ps_order_detail** in database and see that **product_quantity** contains amount of ordered products and **product_quantity_in_stock** properly contains the quantity of items in stock, at the time of your order.
- It will be the same behavior as till 1.7.2.

Výstřižek

**PR that broke the behavior:**
https://github.com/PrestaShop/PrestaShop/commit/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9 - OrderDetail.php

**Changes:**
- I do not use virtual cart (that subtracts items in cart from the amount) for this purpose. We need real amount in stock.
- I renamed a variables and added comments.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26075)

### CODE REVIEW

File: classes/order/OrderDetail.php [hunk 1]
```diff
@@ -752,7 +752,7 @@ protected function create(Order $order, Cart $cart, $product, $id_order_state, $
         $this->product_weight = $product['id_product_attribute'] ? (float) $product['weight_attribute'] : (float) $product['weight'];
         $this->id_warehouse = $id_warehouse;
 
-        $product_quantity = (int) Product::getQuantity($this->product_id, $this->product_attribute_id, null, $cart);
+        $product_quantity = (int) Product::getQuantity($this->product_id, $this->product_attribute_id);
         $this->product_quantity_in_stock = ($product_quantity - (int) $product['cart_quantity'] < 0) ?
```
Comment (jf-viguier) [inline classes/order/OrderDetail.php]: Why is this if for ? 
```suggestion
        $this->product_quantity_in_stock = $product_quantity - (int) $product['cart_quantity'];
```

Comment (Hlavtox) [reply classes/order/OrderDetail.php]: @jf-viguier
Výstřižek

**Review by matks — APPROVED** [review]
Argh 😅  it's always so hard, because "what's the quantity of my product" is always a complex question in ecommerce.

Is it
- how much I have in warehouse
- how much I have in warehouse minus what has been ordered
- how much I have in warehouse minus what has been ordered and what has been put in my cart

And there is probably more cases. 

Logic seems good @Hlavtox but such PRs are always scary to review because sometimes we fix 1 bug for 1 situation and we unfortunately [introduce 3 bugs in another situation](https://twitter.com/Nick_Craver/status/1391385254167031812?s=19) because we did not understand it well.

So we need to ask ourselves: how can we merge safely this PR, knowing we fixed 1 bug and did not introduce any other?

I may have an idea: we could ask @marionf who did the QA of the PR https://github.com/PrestaShop/PrestaShop/pull/8607 (the PR which introduced the bug you mention) and we could map all the QA scenarii used at this time. So we'll have "the usecases the PR https://github.com/PrestaShop/PrestaShop/pull/8607 was supposed to fix" and we'll be able to check them against this PR.

If we validate that your PR fixes bug https://github.com/PrestaShop/PrestaShop/issues/16840 AND does not break usecases mentioned in https://github.com/PrestaShop/PrestaShop/pull/8607 then it's OK for me.

Wdyt ?

**Comment by Hlavtox** [comment]
@matks Go for it! 

- Install 1.6 and see it works like in my PR
- Install 1.7.2 and see it works like in my PR
- This value is only used here in PrestaShop - https://github.com/PrestaShop/PrestaShop/blob/8e0818f0143cdba8e3d5e2a44130ada12eb81586/classes/PaymentModule.php#L568 so unless I broke it (will test tommorow), it should have no effect. 
- I plan to open a issue and PR to display this backoffice. The merchant needs to know if the product was in stock **when the customer ordered it**, so he knows what customer has priority if multiple people ordered the product.

**Comment by marionf** [comment]
@matks 

Here are the scenarios used to test the PR https://github.com/PrestaShop/PrestaShop/pull/8607

**Scenario n°1 : Try to add the standard product to the cart first, then the pack**
1) In Shop parameters > Product settings, choose "decrement both" for "Default pack stock management "
2) In Shop parameters > Product settings, put "Allow ordering of out-of-stock products" on "No".
3) Create a standard product "A" with a stock of 50 and make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
4) Create a pack of product "B" with a stock of 5, this pack contains 10 products "A", make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences and make sure that "Decrement both" is selected as "Pack quantities".
5) In the FO, try to add 50 products "A" to the cart -> It should be ok
6) In the FO, try to add 5 products "B" to the cart -> You shouldn't be able to do it: the message "Out-of-Stock" should be displayed on the product page and the "add to cart" button should be disabled.

**Scenario n°2: Try to add the pack to the cart first, then the standard product**
1) In Shop parameters > Product settings, choose "decrement both" for "Default pack stock management "
2) In Shop parameters > Product settings, put "Allow ordering of out-of-stock products" on "No".
3) Create a standard product "A" with a stock of 50 and make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
4) Create a pack of product "B" with a stock of 5, this pack contains 10 products "A". Make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences, and make sure that "Decrement both" is selected as "Pack quantities".
5) In the FO, try to add 5 products "B" to the cart -> It should be ok
6) In the FO, try to add 50 products "A" to the cart -> You shouldn't be able to do it: the message "Out-of-Stock" should be displayed on the product page and the "add to cart" button should be disabled.

**Scenario n°3: Product without combinations and with negative stock**
1) Create a standard product with -3 as quantity and make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
2) In the FO, try to add this product to the cart -> You shouldn't be able to do it: the message "Out-of-Stock" should be displayed on the product page and the "add to cart" button should be disabled.

**Scenario n°4: Product without combinations and with stock = 0**
1) Create a standard product with 0 as quantity and make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
2) In the FO, try to add this product to the cart -> You shouldn't be able to do it: the message "Out-of-Stock" should be displayed on the product page and the "add to cart" button should be disabled.

**Scenario n°5: Product with 2 combinations, one of which has a negative stock**
1) Create a standard product with 2 combinations: blue & red
2) The first combination "blue" has a stock of -3 
3) The second combination "red" has a stock of 10 
4) Make sure that in the "combination" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
5) In the FO, select the combination "red" and add 1 piece to the cart -> It should work
6) In the FO, select the combination "blue" and try to add 1 piece to the cart -> You shouldn't be able to do it: the message "Product available with different options" should be displayed on the product page and the "add to cart" button should be disabled.

**Scenario n°6: Product with 2 combinations, one of which has a stock = 0**
1) Create a standard product with 2 combinations: blue & red
2) The first combination "blue" has a stock of 0 
3) The second combination "red" has a stock of 10 
4) Make sure that in the "combination" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
5) In the FO, select the combination "red" and add 1 piece to the cart -> It should work
6) In the FO, select the combination "blue" and try to add 1 piece to the cart -> You shouldn't be able to do it: the message "Product available with different options" should be displayed on the product page and the "add to cart" button should be disabled.

File: classes/order/OrderDetail.php [hunk 2]
```diff
@@ -752,9 +752,13 @@ protected function create(Order $order, Cart $cart, $product, $id_order_state, $
...
 
-        $product_quantity = (int) Product::getQuantity($this->product_id, $this->product_attribute_id, null, $cart);
-        $this->product_quantity_in_stock = ($product_quantity - (int) $product['cart_quantity'] < 0) ?
-            $product_quantity : (int) $product['cart_quantity'];
+        // We get the real quantity of the product in stock and save how much of the ordered quantity was in stock
+        $product_quantity_in_stock = (int) Product::getQuantity($this->product_id, $this->product_attribute_id);
+
+        // Ordered 3 pcs, in stock 10 pcs, result is 3
+        // Ordered 3 pcs, in stock 1 pcs, result is 1
+        $this->product_quantity_in_stock = ($product_quantity_in_stock - (int) $product['cart_quantity'] < 0) ?
```
Comment (jolelievre) [inline classes/order/OrderDetail.php:760]: Just to be sure I understand this field, it contains the quantity that was in stock at the moment the OrderDetail is created. So it's the physical quantity right?

It means depending on you product configuration, if you allowed the product to be ordered out of stock The `OrderDetail::product_quantity` can be different from this right?

You could have:
- product_quantity = 10
- product_quantity_in_stock = 5

As long as you allow out of stock orders?

Comment (jolelievre) [reply classes/order/OrderDetail.php:760]: I searched for uses of this field in the core but found very few matches, I guess this is mostly used by modules?

**Review by jolelievre — COMMENTED** [review]
Hi @Hlavtox 

I commented a bit to make sure I get the problem right. If I understood right the modification seems legit 😅

However regarding everything that touches the order modification, I tend to be very wary modifications and it would be great if we could add some behat tests for this, to avoid someone from reverting this fix later.

File: classes/order/OrderDetail.php (hunk 2 above)
Comment (Hlavtox) [reply classes/order/OrderDetail.php:760]: @jolelievre 
> Just to be sure I understand this field, it contains the quantity that was in stock at the moment the OrderDetail is created. So it's the physical quantity right?

Exactly. :-)

> It means depending on you product configuration, if you allowed the product to be ordered out of stock The OrderDetail::product_quantity can be different from this right?

Yes, if not all pieces in stock, it will be different.

> I searched for uses of this field in the core but found very few matches, I guess this is mostly used by modules?

In Prestashop core and native modules, the only single place where this is used is here. I will check if I didn't break it.
https://github.com/PrestaShop/PrestaShop/blob/e0d2a408fde3e6e374ff787e8a5a5536a7fa1197/classes/PaymentModule.php#L567

However, this information is extremely valuable for employees. I display it in order administration, I added it to mailalerts and other places. When customer argues with you that the item was in stock, you currently have no evidence. But if you can do `if (product_quantity == product_quantity_in_stock)`, you immediately know what you need. Once this is merged, I want to implement this.

**Review by jolelievre — APPROVED** [review]
@Hlavtox Ok for me, but as I said it would be really great if some behat tests could be added

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

**Scenario n°2: Try to add the pack to the cart first, then the standard product**
I have an issue following these steps:

1. In Shop parameters > Product settings, choose "decrement both" for "Default pack stock management "
2. In Shop parameters > Product settings, put "Allow ordering of out-of-stock products" on "No".
3. Create a standard product "A" with a stock of 50 and make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
4. Create a pack of product "B" with a stock of 5, this pack contains **5** products "A". Make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences, and make sure that "Decrement both" is selected as "Pack quantities".
5. In the FO, try to add 5 products "B" to the cart 
6. I the Shopping cart page => you can increase the quantity of the pack to **10** with no alert 
image
7. Click on Proceed to checkout
8. See error 
image

I attached a screen record
https://watch.screencastify.com/v/d1ZSwwid4jQFc2MxMM4d

**Other steps to reproduce the issue**
1. In Shop parameters > Product settings, choose "decrement both" for "Default pack stock management "
2. In Shop parameters > Product settings, put "Allow ordering of out-of-stock products" on "No".
3. Create a standard product "A" with a stock of 50 and make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences.
4. Create a pack of product "B" with a stock of 5, this pack contains **5** products "A". Make sure that in the "quantity" tab, "Use default behavior (Deny orders)" is selected as Availability preferences, and make sure that "Decrement both" is selected as "Pack quantities".
5. In the FO > Product B details page
6. Click Add to cart > then click on Continue Shopping 
7. This action can be done 10 times => NOK, we have Product B with quantity = 5 and not 10

I attached a screen record
https://watch.screencastify.com/v/gv3WZK0TK7GkR25Bd94e

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Are you sure that it's not happening in develop? It's impossible, that variable is only used in one place in Prestashop.

**Comment by khouloudbelguith** [comment]
@Hlavtox, thanks for your feedback.
I created an issue https://github.com/PrestaShop/PrestaShop/issues/26728
@marionf do you think that this issue is blocking the test of the PR.
It is related to the **sceanrio1** and **scenario2**.

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith 
The issue https://github.com/PrestaShop/PrestaShop/issues/26728 is not related to this PR and happens also on the develop branch, so we shouldn't block this PR because of this issue

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

It is ok :heavy_check_mark: 
I checked the 6 scenarios => ok :heavy_check_mark: 
I checked a product out of stock allowed / I checked also a product out of stock not allowed
I created order from FO / BO with different types of products
image


Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Yaaaaaay 🎉🎉🎉

**Comment by Progi1984** [comment]
Thanks @Hlavtox & @khouloudbelguith
