### PR TITLE
Possibility to check if we're in product quick view mode

### LINKED ISSUE #21359: Regression related to quick view and hookDisplayProductAdditionalInfo
#### Describe the bug

Because of this PR:
https://github.com/PrestaShop/PrestaShop/pull/15297

Module developers are unable to determine if product is refreshed in quick view context or not.

#### Expected behavior

We should be able to check wether module is displayed in quick view or not, previously it was possible.

#### Steps to Reproduce

Steps to reproduce the "good" behavior from 1.7.6:

1. Make sure you have `ps_sharebuttons` module installed and enabled
2. Edit `/themes/classic/modules/ps_sharebuttons/views/templates/hook/ps_sharebuttons.tpl`
3. Put at the beginning of the block: `<pre>{$smarty.post|@print_r}</pre>`
4. Go to homepage
5. Enable quick view on some product with attributes
6. See that there's an array:

```
[action] => quickview
[id_product] => 1
[id_product_attribute] => 1
```

7. change attribute, see that we still have an access to `[action] => quickview`

Of course this is wrong that `id_product_attribute` is not updated etc. and at the end #15297 is helping with that **but**, let's check this on 1.7.7 now:

1. Make sure you have `ps_sharebuttons` module installed and enabled
2. Edit `/themes/classic/modules/ps_sharebuttons/views/templates/hook/ps_sharebuttons.tpl`
3. Put at the beginning of the block: `<pre>{$smarty.post|@print_r}</pre>`
4. Go to homepage
5. Enable quick view on some product with attributes
6. See that there's an array:

```
 [action] => quickview
 [id_product] => 1
 [id_product_attribute] => 1
```

7. **Now the important part**, change attribute, new array:

```
[ajax] => 1
[action] => refresh
[quantity_wanted] => 1
```

As you can see `action` is different than in 1.7.6, because of this I can't as a module developer check from `.tpl` if module is in quick view or not, because of this some of modules I work with doesn't work.

PR to follow.

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Follow #21359 
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21359 
| How to test?  | Edit ps_sharebutton module and try to check if you're in quick view mode using code below
| Sponsor company | impSolutions

#### In module .tpl (worth checking of we're 

```
{if $page.page_name == 'product' && Context::getContext()->controller->isQuickView()}
  we're in quick view mode for {$product.id_product} and attribute {$product.id_product_attribute}
{/if}
```

### In module .php files

```
if ($this->context->controller instanceof ProductController && $this->context->controller->isQuickView()) {
echo 'yep';
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21362)

### CODE REVIEW

File: themes/_core/js/product.js [hunk 1]
```diff
@@ -154,6 +154,7 @@ function updateProduct(event, eventType, updateUrl) {
       url: updateUrl + ((updateUrl.indexOf('?') === -1) ? '?' : '&') + formSerialized + preview,
       method: 'POST',
       data: {
+        quickview: parseInt($('.modal.quickview.in').length),
```
Comment (matks) [inline themes/_core/js/product.js]: Suggestion: if we're going to introduce a `quickview` boolean both in PHP and in JS, maybe we can make it 100% unambiguous ?

This statement basically says "OK, if selector `'.modal.quickview.in'` does exist, then I know that I am in a quickview" so it's trying to find out whether or not it's a quickview using the HTML markup.

What about making it 100% clear ? I'm suggesting to put somewhere in the HTML markup a data attribute `is-quickview`. So the code would become

```suggestion
        quickview: $('my-div-with-my-informations').data('is-quickview')
```

**Review by matks — DISMISSED** [review]

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -1312,4 +1323,22 @@ protected function isValidCombination($productAttributeId, $productId)
 
         return false;
     }
+
+    /**
+     * Return information whether we are or not in quick view mode.
+     *
+     * @return bool
+     */
+    public function isQuickView()
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php]:
```suggestion
    public function isQuickView(): bool
```

File: controllers/front/ProductController.php [hunk 3]
```diff
@@ -1312,4 +1323,22 @@ protected function isValidCombination($productAttributeId, $productId)
...
+    {
+        return $this->isQuickView;
+    }
+
+    /**
+     * Set quick view mode.
+     */
+    public function setQuickViewMode($enabled = true)
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php]:
```suggestion
    public function setQuickViewMode(bool $enabled = true)
```

File: controllers/front/ProductController.php [hunk 4]
```diff
@@ -1312,4 +1323,22 @@ protected function isValidCombination($productAttributeId, $productId)
...
+     *
+     * @return bool
+     */
+    public function isQuickView()
+    {
+        return $this->isQuickView;
+    }
+
+    /**
+     * Set quick view mode.
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:1341]:
```suggestion
     * Set quick view mode.
     *
     * @param bool $enabled
```

File: themes/_core/js/product.js (hunk 1 above)
Comment (PierreRambaud) [inline themes/_core/js/product.js]:
```suggestion
        quickview: $('.modal.quickview.in').length,
```
parseInt is useless here

Comment (kpodemski) [reply themes/_core/js/product.js]: Hey, once again thanks for the suggestion, but as I said on Slack, I don't think that we would ever had different element with this kind of class in our shop, and thanks to checking it like this theme developers don't need to do anything to make them compatible with my solution

**Comment by kpodemski** [comment]
Thanks @PierreRambaud

**Review by Sinepel — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: controllers/front/ProductController.php [hunk 5]
```diff
@@ -52,6 +52,8 @@ class ProductControllerCore extends ProductPresentingFrontControllerCore
     protected $quantity_discounts;
     protected $adminNotifications = [];
 
+    protected $isQuickView = false;
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:58]:
```suggestion
    /**
     * @var bool
     */
    protected $isQuickView = false;
```

File: themes/_core/js/product.js [hunk 6]
```diff
@@ -154,6 +154,7 @@ function updateProduct(event, eventType, updateUrl) {
       url: updateUrl + ((updateUrl.indexOf('?') === -1) ? '?' : '&') + formSerialized + preview,
       method: 'POST',
       data: {
+        quickview: $('.modal.quickview.in').length,
```
Comment (PierreRambaud) [inline themes/_core/js/product.js:157]: Has @matks said earlier, is there a quick way to put the `is_quick_view` smarty variable into the template to retrieve the data instead of hoping the theme is using the same modal? :)

Comment (kpodemski) [reply themes/_core/js/product.js:157]: Probably, but as it is regression and because of related PR changes my module doesn't work (and probably some other modules), I thought that it would be better to do it without it, because this would require theme authors to make proper changes too, and it's way harder to update theme than a module 🤷🏼‍♂️

Also, it would not be smart to use this set of classes in place different than this specific modal and what's more important some code in JS is related to .quickview class too :)

Comment (PierreRambaud) [reply themes/_core/js/product.js:157]: Oh, reviewing too much pull request didn't notice the 1.7.7.x branch :sweat_smile: 
Let's improve this for the develop branch :)

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

After a fresh install of this PR, The **action** is still refresh
I attached a screen record
https://drive.google.com/file/d/1_wa8MdEw-JbmtzqOWV5cI92TJ5rFXIoY/view?usp=sharing
image

Thanks to check it.

**Comment by kpodemski** [comment]
Hello @khouloudbelguith 

Sorry, I wasn't precise enough, the point is to have quickview=1 and it's OK. We can't have same array before and after, module developers needs to change their code from action=quickview to new one for checking if we are, or not, in quickview mode.

Point of this PR was to have this possibility at all, because without it, we couldn't check for this state from module tpl or php after changing attributes.

QA is ok if:
- you can open quick view
- quickview = 1 is in modal
- you don't have quickview=1 on regular product page

If you need more informations let me know.

**Comment by khouloudbelguith** [comment]
Hi @kpodemski,

Thanks for the feedback.
It is ok :heavy_check_mark: 
https://www.awesomescreenshot.com/video/1332722?key=3b55dcbb4e75458dc096bdd10640c15e

Thanks!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @khouloudbelguith
