### PR TITLE
Duplicate product in order invoices

### LINKED ISSUE #18721: BO - ORDER - INVOICE - Impossible to reassign a product to another invoice
#### Describe the bug

In BO order if we have multiple invoice in an order when trying to reassign a product to another invoice the save button have no effect.

#### Expected behavior
The invoice reassignment should work

#### Steps to Reproduce

1. Go to BO => order => order => select an order
2. Add a product with a new generated invoice to the order
3. Try to edit the invoice of one of the product
4. Click on save 
5. See error the invoice is not updated

**Screenshots**

https://drive.google.com/file/d/1sgSxXBvW5ROAtxGZqv6nje-7i6soiaz6/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### LINKED ISSUE #20612: Improve error message when adding product in existing invoice
#### Describe the bug

In BO, in order view page, when I add a product that already exists in an order I get this error:
`This product is already in your order, please edit the quantity instead.`

This is fine, but when I have multi invoice and I add the product to an invoice that already contains the product I get the same error message, whereas I should get this error message:
`This product is already in the invoice #number, please edit the quantity instead.`

#### Expected behavior

When I add existing product in an invoice I get a more precise error message.

#### Steps to Reproduce

1. Go to an Order view page
2. Go in the document tab and generate invoice if no one exists
3. This will enable the multi-invoice features on the page
4. Add a product to any invoice
5. Add this same product to the same invoice you just added it to
6. You should see an error message (this is expected, this action is not authorize) with the appropriate content

**Screenshots**

image

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | This PR is a subset of the initially too big https://github.com/PrestaShop/PrestaShop/pull/20776 It focuses on fixing product change of invoice, along with testing if by doing so duplicate products are NOT inserted in invoices It also improves the error message when such scenario occurs (both on addition and edition)<br />Lastly it integrates lots of behat tests regarding the multi invoices, most of them have been commented because they are not fixed yet but this allows to have the tools to test multi invoices as well as the list of expected values and behaviours (to be fixed in future PRs)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18721 and #20612
| How to test?  | Create an order with multiple invoices (you will need 3 with different products)<br />Try to add a product to an invoice that already contains this product<br />The error message `This product is already in the invoice #number, please edit the quantity instead.` is displayed<br />Add the product to an invoice that does not contain it<br />It works fine<br />Now try to edit the product by changing its invoice to one that already contains it<br />The error message `This product is already in the invoice #number, please edit the quantity instead.` is displayed<br />Edit it again but with an invoice that doesn't contain it<br />It works fine and the new invoice is correctly assigned to the edited product

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20906)

### CODE REVIEW

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 1]
```diff
@@ -349,7 +350,7 @@ private function createNewOrEditExistingInvoice(
         if ($order->hasInvoice()) {
             return $command->getOrderInvoiceId() ?
                 $this->updateExistingInvoice($command->getOrderInvoiceId(), $cart, $products) :
-                $this->createNewInvoice($order, $cart, $command->isFreeShipping(), $products);
+                $this->createNewInvoice($order, $cart, $command->withFreeShipping(), $products);
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]:
```suggestion
                $this->createNewInvoice($order, $cart, $command->hasFreeShipping(), $products);
```

Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: (For boolean, `is` or `has`)

File: src/Core/Domain/Order/Exception/DuplicateProductInOrderInvoiceException.php [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+     */
+    private $orderInvoiceNumber;
+
+    /**
+     * @param string $orderInvoiceId
+     * @param string $message
+     * @param int $code
+     * @param Throwable|null $previous
+     */
+    public function __construct(string $orderInvoiceId, $message = '', $code = 0, Throwable $previous = null)
```
Comment (Progi1984) [inline src/Core/Domain/Order/Exception/DuplicateProductInOrderInvoiceException.php:49]:
```suggestion
    public function __construct(string $orderInvoiceId, string $message = '', int $code = 0, Throwable $previous = null)
```

File: src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php [hunk 3]
```diff
@@ -78,7 +78,7 @@ class AddProductToOrderCommand
     /**
      * @var bool|null bool if product is being added using new invoice
```
Comment (Progi1984) [inline src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php:79]: Bad comment

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 4]
```diff
@@ -286,6 +292,35 @@ public function addProductsToOrderWithExistingInvoiceAndTheFollowingDetails(stri
...
+    /**
+     * @Then :invoicePosition invoice from order :orderReference should have following details:
+     *
+     * @param string $invoicePosition
+     * @param string $orderReference
+     * @param TableNode $table
+     */
+    public function checkInvoiceDetails(string $invoicePosition, string $orderReference, TableNode $table)
+    {
+        $orderId = SharedStorage::getStorage()->get($orderReference);
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:304]:
```suggestion
        $orderId = (int) SharedStorage::getStorage()->get($orderReference);
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 5]
```diff
@@ -432,6 +467,24 @@ public function editProductsToOrderWithFollowingDetails(string $productName, str
...
+    /**
+     * @When I edit product :productName in :invoicePosition invoice from order :orderReference with following products details:
+     *
+     * @param string $productName
+     * @param string $orderReference
+     * @param TableNode $table
+     */
+    public function editProductsFromInvoiceWithFollowingDetails(string $productName, string $orderReference, string $invoicePosition, TableNode $table)
+    {
+        $orderId = SharedStorage::getStorage()->get($orderReference);
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:479]:
```suggestion
        $orderId = (int) SharedStorage::getStorage()->get($orderReference);
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 6]
```diff
@@ -449,6 +502,31 @@ public function editCombinationToOrderWithFollowingDetails(string $combinationNa
...
+
+        $invoiceIndexes = [
+            'first' => 0,
+            'second' => 1,
+            'third' => 2,
+            'fourth' => 3,
+            'last' => $invoicesCollection->count() - 1,
+        ];
+        if (!isset($invoiceIndexes[$invoicePosition])) {
+            throw new RuntimeException(sprintf('Can not interpret this invoice position %s', $invoicePosition));
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
            throw new RuntimeException(sprintf('Cannot interpret this invoice position %s', $invoicePosition));
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 7]
```diff
@@ -458,20 +536,31 @@ public function editCombinationToOrderWithFollowingDetails(string $combinationNa
      */
     private function updateProductInOrder(int $orderId, array $productOrderDetail, array $data)
     {
+        $invoiceId = null;
+        if (isset($data['invoice'])) {
+            $order = new Order($orderId);
+            $invoice = $this->getInvoiceFromOrder($order, $data['invoice']);
+            $invoiceId = $invoice->id;
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
            $invoiceId = (int) $invoice->id;
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature [hunk 8]
```diff
@@ -0,0 +1,698 @@
...
+@clear-cache-before-feature
+Feature: Order from Back Office (BO)
+  In order to manage orders for FO customers
+  As a BO user
+  I need to be able to customize orders from the BO
+
+  Background:
+    Given email sending is disabled
+    And the current currency is "USD"
+    And country "US" is enabled
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature:13]:
```suggestion
    And the country "US" is enabled
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 9]
```diff
@@ -286,6 +292,35 @@ public function addProductsToOrderWithExistingInvoiceAndTheFollowingDetails(stri
         }
     }
 
+    /**
+     * @Then :invoicePosition invoice from order :orderReference should have following details:
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
     * @Then the :invoicePosition invoice from order :orderReference should have following details:
```

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 10]
```diff
@@ -708,6 +797,33 @@ public function duplicateOrder($orderReference, $duplicatedCartReference)
      * @param string|null $combinationName
      */
     public function orderContainsProductWithReference(string $orderReference, int $quantity, string $productName, ?string $combinationName = null)
+    {
+        $this->assertProductCounts($orderReference, $quantity, $productName, $combinationName);
+    }
+
+    /**
+     * @Then :invoicePosition invoice from order :orderReference should contain :quantity product(s) :productName
+     * @Then :invoicePosition invoice from order :orderReference should contain :quantity combination(s) :combinationName of product :productName
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
     * @Then the :invoicePosition invoice from order :orderReference should contain :quantity product(s) :productName
     * @Then the :invoicePosition invoice from order :orderReference should contain :quantity combination(s) :combinationName of product :productName
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature [hunk 11]
```diff
@@ -0,0 +1,698 @@
...
+    And second invoice from order "bo_order1" should contain 1 products "Test Product B"
+    And second invoice from order "bo_order1" should have following details:
+      | total_products          | 40.000 |
+      | total_products_wt       | 42.400 |
+      | total_discount_tax_excl | 0.0    |
+      | total_discount_tax_incl | 0.0    |
+#      | total_paid_tax_excl     | 47.00  |
+#      | total_paid_tax_incl     | 49.82  |
+#      | total_shipping_tax_excl | 7.0    |
+#      | total_shipping_tax_incl | 7.42   |
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature:78]: Why is this commented ?

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature [hunk 12]
```diff
@@ -0,0 +1,698 @@
...
+#      | total_shipping_tax_excl  | 21.0   |
+#      | total_shipping_tax_incl  | 22.26  |
+    And order "bo_order1" carrier should have following details:
+      | weight                 | 0.600 |
+#      | shipping_cost_tax_excl | 21.00 |
+#      | shipping_cost_tax_incl | 22.26 |
+
+  Scenario: I add products in two different invoices and apply a discount on only one
+    When I generate invoice for "bo_order1" order
+    Then order "bo_order1" should have 1 invoices
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature]:
```suggestion
    Then order "bo_order1" should have 1 invoice
```

**Review by Progi1984 — COMMENTED** [review]
@jolelievre Some comments

File: src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php (hunk 3 above)
Comment (jolelievre) [reply src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php:79]: Why?

File: src/Core/Domain/Order/Exception/DuplicateProductInOrderInvoiceException.php (hunk 2 above)
Comment (jolelievre) [reply src/Core/Domain/Order/Exception/DuplicateProductInOrderInvoiceException.php:49]: The native `Exception` doesn't have strict type so I prefer to keep the same signature

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 4 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:304]: Not needed because the stored order id is always a strict int

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature (hunk 11 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature:78]: This big behat feature comes from a bigger PR (see description) where everything was fixed But the PR is too big and the technical solution to fix shipping calculations and discount on invoices has not been validated by Pablo

So the idea of this PR is to integrate all the expected scenarios as a reference but some are commented because they are not fixed yet in this one, they will be uncommented in future PR that fix the bugs

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature (hunk 8 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature:13]: I fixed the other suggestion for behat sentences, but this one is quite old, used in many different features with unrelated domains So I prefer not to fix it here to avoid making the PR too big and having potential conflicts with other pending PRs

File: src/Core/Domain/Order/Exception/DuplicateProductInOrderInvoiceException.php (hunk 2 above)
Comment (Progi1984) [reply src/Core/Domain/Order/Exception/DuplicateProductInOrderInvoiceException.php:49]: :ok:

File: src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php [hunk 13]
```diff
@@ -251,9 +251,9 @@ public function getOrderInvoiceId()
     /**
      * @return bool|null
      */
-    public function isFreeShipping()
+    public function hasFreeShipping()
```
Comment (Progi1984) [inline src/Core/Domain/Order/Product/Command/AddProductToOrderCommand.php]:
```suggestion
    public function hasFreeShipping(): ?bool
```

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature (hunk 8 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_multi_invoices.feature:13]: npb

**Review by Progi1984 — DISMISSED** [review]
A small comment. But I approve :+1:

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 14]
```diff
@@ -86,6 +88,7 @@ public function handle(UpdateProductInOrderCommand $command)
 
             // Check fields validity
             $this->assertProductCanBeUpdated($command, $orderDetail, $order, $orderInvoice);
+            $this->assertProductDuplicate($order, $orderDetail, $orderInvoice);
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: I think method name 'assetProductNotDuplicated' is more correct. wdyt ?

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Indeed! I also renamed it in `AddProductToOrderHandler`

**Review by sowbiba — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I have an exception following these steps:
1. Add a product1 to cart and proceed checkout
2. Go to BO => Orders => Edit the last order created
3. Generate an invoice
4. Add a new product2 with creating a new invoice

=> see error => an exception is displayed in the console
image

Thanks to check and feedback.

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 

indeed I have the same bug, sorry I didn't know this method was not available and didn't test this use case in the BO. This is fixed now 😉

**Review by Progi1984 — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1wgid6SB92w0wANPXyIPp3DOeirHqrdBR/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @jolelievre & @khouloudbelguith
