### PR TITLE
Email subject doesn't support html entities

### LINKED ISSUE #16847: If the shop name contains special chars => the email subject will be incorrect
**Describe the bug**
If the shop name contains special chars => the email subject will be incorrect.
For example if the shop name is äöüß ) => subject email => `[&auml;&ouml;&uuml;&szlig;]`
https://github.com/PrestaShop/PrestaShop/pull/16500#commitcomment-36445923
Thanks @JBWModules

**To Reproduce**
1. Go to BO => Shop Parameters => Contact
2. change Shop name `äöüß`
3. Check emails (Order confirmation email for example)
image

With PS1.7.6.1, as you can see in this ticket: https://github.com/PrestaShop/PrestaShop/issues/16499#issuecomment-557434129
the `Shop name` defined in the multistore page
If we change it in the multistore page => Ok
image
With PS1.7.5.2 => OK

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Tools::safeOutput html entities encode subject that produce a buggy subject with special characters.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16847
| How to test?  | Add a special character in Shop name and send an email.

Initial Work from @jf-viguier in #17073

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17608)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

File: classes/Mail.php [hunk 1]
```diff
@@ -465,7 +465,7 @@ function ($carry, $item) {
             );
 
             /* Create mail and attach differents parts */
-            $subject = '[' . Tools::safeOutput($configuration['PS_SHOP_NAME']) . '] ' . $subject;
+            $subject = '[' . strip_tags($configuration['PS_SHOP_NAME']) . '] ' . $subject;
```
Comment (Ydalb) [inline classes/Mail.php:468]: Why do you need to strip tags in an email subject ? 

(btw, yo @Progi1984  🕺 )

Comment (jf-viguier) [reply classes/Mail.php:468]: It's a security. Someone could put an html tag in shop name.

**Comment by Ydalb** [comment]
Hm, it’s not the problem of the sender, i.e. PrestaShop, but of the client
mail ?

**Comment by jf-viguier** [comment]
Sorry @Ydalb I don't understand. It's about the subject, not the sender.
Anyway, my pr has been approved by core team and checked by QA.

**Comment by Ydalb** [comment]
> Sorry @Ydalb I don't understand. It's about the subject, not the sender.
> Anyway, my pr has been approved by core team and checked by QA.

My point is: you don't need to protect a subject's email by stripping HTML tags. It is the responsability of the client mail (the person who receive the email) to display the subject with encoded entities.

Just a simple test: try to send you an email (for example, using Gmail) with HTML tags in the subject.

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
the pull request seems to correctly fix the described issue ; Thanks @Progi1984

**Comment by PierreRambaud** [comment]
Thanks @Progi1984

**Comment by jf-viguier** [comment]
Thanks @Progi1984 to have so nicely backported my pr ;-)
