### PR TITLE
Webservice: honor maximum image upload size

### LINKED ISSUE #28157: WebService image upload size is hardcoded instead of being loaded from settings
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Uploading product image through WebService uses limit of 3MB hardcoded in WebserviceSpecificManagementImages.php Line 68.
Temporary fix in WebserviceSpecificManagementImages.php:
```$imgMaxUploadSize = 3000000;``` to desired size.

### Expected behavior

Should be loaded from config PS_LIMIT_UPLOAD_IMAGE_VALUE or from php config:
```
ini_get('upload_max_filesize');
ini_get('post_max_size');
```

Whichever is smaller.

### Steps to reproduce

1. Send upload product image request through webservice

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by balejk**
- webservice: honor maximum image upload size

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The webservice does not respect the image upload size limit set in back-office. This pull request addresses that.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | `imgMaxUploadSize` property removed from `classes/webservice/WebserviceSpecificManagementImages.php`
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28157
| Related PRs       | no
| How to test?      | Upload a image through the webservice, compare its size with the maximum image upload size configured in back-office.
| Possible impacts? | no

### CODE REVIEW

**Comment by zuk3975** [comment]
Hi, Thanks for your contribution! 

Are there any related bug issues? If yes, please attach them. If no, create one and wait for QA to reproduce it please :v: 

About the wording `KB -> kB` - I personally don't see a point in that. If you google it, there are many uses of KB
Screenshot from 2022-07-25 12-15-07
.

**Comment by balejk** [comment]
I have been able to find an issue (#28157) describing exactly this, but it's been closed due to author's inactivity - is it OK or should I open a fresh one?

Regarding the `k` prefix, my understanding is that `K` is a often refers to a multiple of 1024 (although I consider `KiB` less ambiguous), while `k` as a prefix used by SI signifies a multiple of 1000. Since here we deal with thousands of bytes, I believe little `k` is more precise, even if the difference is often not too significant.

But it was just that I have noticed it while changing the size limit and so I included it, I would not change it on it's own. Also, I have not checked it anywhere else, only in these two files, so it's not thorough and might be inconsistent with the rest of PrestaShop (although I think the use of 1000/1024 multiples is inconsistent across PS already). Please let me know if I should remove this commit.

**Comment by zuk3975** [comment]
Im not sure about changing 1024 to 1000. I don't think prestashop has defined it anywhere whether it should use decimal or binary SI (1000 vs 1024) for such calculations. And there is currently probably a mix of those in code.
Because of that I would say we should target this PR to only fix the hardcoded value issue and not change the wording, neither the 1024 -> 1000 (this way the max upload size won't be affected either which will result in less potential problems).

By the way, we will still need to wait for QA to reproduce the issue first (I reopened the one you mentioned, feel free to participate there if you have anything to add).
wdyt @PrestaShop/committers?

**Comment by ghost** [comment]
I agree with @zuk3975 

Changing kB to KB or vice versa is not too important.
The important thing is not to use a hard-coded variable anymore.
In another time we could open a new issue to harmonize 1000 or 1024 in all PrestaShop

**Comment by ghost** [comment]
I think the best way is open a new issue with all the step to reproduce.
You will have more chance for the QA validate it because I don't know the proccess when we reopen an issue

**Comment by balejk** [comment]
Actually, my motivation for changing it was also that the limit for both attachments and images is set in the same window in BO, but in the webservice code, attachments limit was assumed to be scaled by 1024, whilst images limit was scaled by 1000. I think the issue isn't that both 1000 and 1024 are used across PS, but rather that the same prefixes are used for both.

I have removed the latter two commits.

File: classes/webservice/WebserviceSpecificManagementImages.php [hunk 1]
```diff
@@ -1032,11 +1027,13 @@ protected function writeImageOnDisk($base_path, $new_path, $dest_width = null, $
      */
     protected function writePostedImageOnDisk($reception_path, $dest_width = null, $dest_height = null, $image_types = null, $parent_path = null)
     {
+
+        $imgMaxUploadSize = ((int)Configuration::get('PS_LIMIT_UPLOAD_IMAGE_VALUE')) * 1000 * 1000;
```
Comment (zuk3975) [inline classes/webservice/WebserviceSpecificManagementImages.php:1031]:
```suggestion
        $imgMaxUploadSize = ((int) Configuration::get('PS_LIMIT_UPLOAD_IMAGE_VALUE')) * 1000 * 1000;
```

**Comment by ghost** [comment]
You have to run : 

`./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix classes/webservice/WebserviceSpecificManagementImages.php`

File: classes/webservice/WebserviceSpecificManagementImages.php [hunk 2]
```diff
@@ -62,11 +62,6 @@ class WebserviceSpecificManagementImagesCore implements WebserviceSpecificManage
      */
     protected $imageType = null;
 
-    /**
-     * @var int The maximum size supported when uploading images, in bytes
-     */
-    protected $imgMaxUploadSize = 3000000;
```
Comment (zuk3975) [inline classes/webservice/WebserviceSpecificManagementImages.php:68]: hmm also this is probably a BC break. I think its acceptable, but should be defined in PR description

**Comment by kpodemski** [comment]
Hello @balejk 

Could you help our QA team validate the issue? It has been reported already but QA team didn't receive any response from the author

**Comment by balejk** [comment]
@kpodemski With pleasure. What is required of me?

**Comment by zuk3975** [comment]
> @kpodemski With pleasure. What is required of me?
 
 @balejk 
Just A detailed information with steps of how to reproduce the issue, so QA can reproduce and acknowledge it. (There is an issue already, but it was raised by someone else, so maybe you could improve it or just add your use case example, because the author of the issue is not active anymore)

**Comment by kpodemski** [comment]
Thanks @balejk ❤️

**Review by kpodemski — APPROVED** [review]

**Comment by ghost** [comment]
@PrestaShop/prestashop-maintainers 

What are we doing for this BC?
Should we depreciate the property or can we delete it directly?

File: classes/webservice/WebserviceSpecificManagementImages.php [hunk 3]
```diff
@@ -1032,11 +1027,12 @@ protected function writeImageOnDisk($base_path, $new_path, $dest_width = null, $
      */
     protected function writePostedImageOnDisk($reception_path, $dest_width = null, $dest_height = null, $image_types = null, $parent_path = null)
     {
+        $imgMaxUploadSize = ((int) Configuration::get('PS_LIMIT_UPLOAD_IMAGE_VALUE')) * 1000 * 1000;
```
Comment (jolelievre) [inline classes/webservice/WebserviceSpecificManagementImages.php:1030]: Seems ok to me, just one thing I'm a bit wary of, are we sure that the dropzone JS component computes the max size this way? Because it could be:

```suggestion
        $imgMaxUploadSize = ((int) Configuration::get('PS_LIMIT_UPLOAD_IMAGE_VALUE')) * 1024 * 1024;
```

which would result in slightly different behavior. But it's not blocking anyway the difference is minor. However, this makes me realize I'm not sure this limit has been implemented on the product page v2.

@NeOMakinG do you know if the component used for v2 has such a feature? We should also probably handle this in the PHP API side internally.

**Review by jolelievre — APPROVED** [review]
Thanks @balejk 

Just a small question, although it's not blocking so I still approve the PR.

File: classes/webservice/WebserviceSpecificManagementImages.php (hunk 3 above)
Comment (NeOMakinG) [reply classes/webservice/WebserviceSpecificManagementImages.php:1030]: https://docs.dropzone.dev/configuration/basics/configuration-options

`maxFilesize` is 256 bytes by default

**Review by khouloudbelguith — APPROVED** [review]
Hi @balejk,

It is ok :heavy_check_mark: 
I checked those endpoints

- http://localhost/PrestaShop/api/images/categories/12
- http://localhost/PrestaShop/api/images/products/2
- http://localhost/PrestaShop/api/images/manufacturers/4
- http://localhost/PrestaShop/api/images/suppliers/1
- http://localhost/PrestaShop/api/images/stores/6

https://user-images.githubusercontent.com/16067358/198346562-a459ed03-6e17-48c5-b976-2b3c0b46aac6.mp4

Thanks!

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @balejk and @khouloudbelguith

**Comment by Ratnadeep-Dasgupta** [comment]
Hi @khouloudbelguith @prestonBot ,

I am facing the below error while uploading the image for the product.
Can anyone let me know what is the actual issue regarding this or provide us the XML feed ?
Screenshot 2023-03-20 104733

**Comment by Ratnadeep-Dasgupta** [comment]
Hi @balejk @prestonBot @zuk3975 @okom3pom @kpodemski ,

Can anyone help me with the above issue that I am facing?
