### PR TITLE
Client API - Help card is not displayed in sidebar as it should

### LINKED ISSUE #36570: Client API - Help card is not displayed in sidebar as it should
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Help card is not displayed in the sidebar as it should and it won't close if cross is clicked.

https://github.com/user-attachments/assets/6bd2581e-7ec6-4b8f-8ece-601d06e6d3f4

### Expected behavior

Should open in sidebar and should close if cross is clicked

### Steps to reproduce

1. Go to BO > Advanced parameters > Admin API
2. Click on Help card

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by seiwan**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Fix enable sidebar in the back office of the advanced parameters / Admin API page
| Type?             | bug fix 
| Category?         |  BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go to the back office, on the advanced parameters / Admin API page page and click on the Help button.  Help should open in a sidebar
| UI Tests          | https://github.com/seiwan/ga.tests.ui.pr/actions/runs/15904194557.
| Fixed issue or discussion?     | Fixes #36570
| Related PRs       | None
| Sponsor company   | PrestaShop

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @seiwan!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by seiwan** [comment]
@LaurieReinette
@Clap404
@sarahdib 
@maxencenoel-prestashop
@JeanBaptisteAvot

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdminAPIController.php [hunk 1]
```diff
@@ -1,4 +1,5 @@
 <?php
+
```
Comment (nicosomb) [inline src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdminAPIController.php]: useless line

Comment (seiwan) [reply src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdminAPIController.php]: Done

**Review by ga-devfront — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @seiwan, 

Thank you for your PR, i tested this PR and it's OK for me ^^

https://github.com/user-attachments/assets/549aa7a5-66b4-4d13-9c7d-317134eb74d3

Thank you ^^

**Review by SiraDIOP — APPROVED** [review]

**Comment by matks** [comment]
Thank you @seiwan
