### PR TITLE
Increase max size of reference, meta_title, meta_description email, password, firstname, lastname and company.

### LINKED ISSUE #9717: [BOOM-4983] If the meta description is more than 255 characters in product, the changes are not saved.
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4983).

- _**Reporter:**_ JuanjoSC
- _**Created at:**_ Fri, 2 Mar 2018 19:49:40 +0100

<p>The current size of the meta description is 320 characters (according to google), prestashop lets us put more than 160 but if we exceed 255, it does not save any changes in the product and does not give an error.</p>
        
* How to reproduce the issue ?

Creating a product with a meta description of more than 255 characters

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | After reading this PR https://github.com/PrestaShop/PrestaShop/pull/10438, I think we need to increase max size of reference, meta_title, meta_describtion, email, password, firstname, lastname and company to prevent issues.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9717 #9942
| How to test?  | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10446)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
What do you think  @colinegin ?

File: classes/CMSCategory.php [hunk 1]
```diff
@@ -89,7 +89,11 @@ class CMSCategoryCore extends ObjectModel
             'link_rewrite' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isLinkRewrite', 'required' => true, 'size' => 64),
             'description' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isCleanHtml'),
             'meta_title' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255),
+<<<<<<< HEAD
```
Comment (PierreRambaud) [inline classes/CMSCategory.php]: Hum you commit some conflicts :)

File: classes/Category.php [hunk 2]
```diff
@@ -116,7 +116,11 @@ class CategoryCore extends ObjectModel
             'link_rewrite' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isLinkRewrite', 'required' => true, 'size' => 128),
             'description' => array('type' => self::TYPE_HTML, 'lang' => true, 'validate' => 'isCleanHtml'),
             'meta_title' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255),
+<<<<<<< HEAD
```
Comment (PierreRambaud) [inline classes/Category.php]: Hum you commit some conflicts :)

File: classes/Manufacturer.php [hunk 3]
```diff
@@ -81,7 +81,11 @@ class ManufacturerCore extends ObjectModel
             'description' => array('type' => self::TYPE_HTML, 'lang' => true, 'validate' => 'isCleanHtml'),
             'short_description' => array('type' => self::TYPE_HTML, 'lang' => true, 'validate' => 'isCleanHtml'),
             'meta_title' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255),
+<<<<<<< HEAD
```
Comment (PierreRambaud) [inline classes/Manufacturer.php]: Hum you commit some conflicts :)

File: classes/CMSCategory.php (hunk 1 above)
Comment (MathiasReker) [reply classes/CMSCategory.php]: I am solveing it now

File: classes/Manufacturer.php (hunk 3 above)
Comment (MathiasReker) [reply classes/Manufacturer.php]: Fixed :)

File: classes/Category.php (hunk 2 above)
Comment (MathiasReker) [reply classes/Category.php]: Fixed :)

Comment (Mreker) [reply classes/Category.php]: Fixed :)

File: classes/CMSCategory.php (hunk 1 above)
Comment (MathiasReker) [reply classes/CMSCategory.php]: Fixed :)

**Comment by MathiasReker** [comment]
@PierreRambaud wdyt?

**Comment by PierreRambaud** [comment]
Thanks @Mreker , I'm agree with what you did, but need a feedback from @eternoendless and other members of the team :)

**Comment by MathiasReker** [comment]
This PR can be reviewed, it is not more in progress :)

**Comment by MathiasReker** [comment]
What is status on this? :)

**Comment by colinegin** [comment]
Hello @Mreker , sorry for the delay, we have discussed about it with @PierreRambaud but I did not have time to write you earlier.

It's a great idea, but I think it would also be helpful for merchants to make recommendations for SEO (metatitle and meta description) according to Google standards so that they don't think that they should add as much content as possible. 

For example, in the product page, it is written below the metatitle / metadescription field : X of 70/160 characters used (recommended) (X being changed dynamically according to the number of letters added in the field). There is not such information in category and SEO & URL pages.

What do you think of this idea @LouiseBonnard ?

I guess this is not something you could add with your PR @Mreker, but the idea is to keep it in mind for a future improvement !

**Comment by MathiasReker** [comment]
@colinegin @PierreRambaud I see your point of improvement by the count of characters. I can look into this and see if I can solve this. But I will do it in another PR.

Can you merge this for now? This PR is safe to merge, as this can not break anything, it only solves a lot of issues with eg. name, email and company length. I also saw someone ask for bigger size of reference, what this PR solves.

wdyt?
meta-descr 2 verzia-fb
?

**Comment by colinegin** [comment]
Currently we recommend 160 characters in the product sheet if I'm correct, I think we should leave it this way (checked with our SEO team).

**Comment by MathiasReker** [comment]
I can change it back to 255 if you want?

**Comment by MathiasReker** [comment]
I don't see any negative effects with this PR :-) Can it be merged? Let me know, if I have to solve any part of this PR :-)

**Comment by colinegin** [comment]
Hi @Mreker, sorry for the misunderstanding, I think you were talking about the recommendation text !
Regarding the max, let's keep it with what you have originally done.

Thanks !

**Comment by MathiasReker** [comment]
Then everything is OK? I think this should be merged asap. This PR will get a lot of conflicts over time, because I fixed a lot of code standard errors.

**Review by PierreRambaud — DISMISSED** [review]

File: install-dev/upgrade/sql/1.7.5.0.sql [hunk 4]
```diff
@@ -7,3 +7,117 @@ SET NAMES 'utf8';
...
+  CHANGE `meta_description` `meta_description` VARCHAR(512) DEFAULT NULL; 
+
+ALTER TABLE `PREFIX_customer`
+  CHANGE `passwd` `passwd` varchar(2048) NOT NULL;
+
+ALTER TABLE `PREFIX_employee`
+  CHANGE `passwd` `passwd` varchar(2048) NOT NULL;
+
+ALTER TABLE `PREFIX_customer`
+  CHANGE `passwd` `passwd` varchar(2048) NOT NULL;
```
Comment (Quetzacoalt91) [inline install-dev/upgrade/sql/1.7.5.0.sql]: I see many duplicates in this file, the column has been already updated a few lines before. Please remove the wrong update.

**Review by Quetzacoalt91 — DISMISSED** [review]

File: install-dev/upgrade/sql/1.7.5.0.sql (hunk 4 above)
Comment (MathiasReker) [reply install-dev/upgrade/sql/1.7.5.0.sql]: You are right, sorry for that. I just fixed it and made it more readable.

**Comment by Mreker** [comment]
Everything should be OK now 😊

**Review by PierreRambaud — DISMISSED** [review]

**Comment by MathiasReker** [comment]
@Quetzacoalt91 ok now? :-)

File: install-dev/data/db_structure.sql [hunk 5]
```diff
@@ -2500,7 +2500,7 @@ CREATE TABLE `PREFIX_stock_available` (
     `id_shop`, 
     `id_shop_group`
   )
-) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8 COLLATION;
+) ENGINE = ENGINE_TYPE DEFAULT CHARSET = utf8 COLLATION;
```
Comment (PierreRambaud) [inline install-dev/data/db_structure.sql]: why do you add space here when it's easier to export structure from mysqldump command and it doesn't add its :/

Comment (MathiasReker) [reply install-dev/data/db_structure.sql]: I thought that spaces around operators was the right format in sql. (https://solutioncenter.apexsql.com/rules-of-sql-formatting-commas-and-spacing-in-t-sql/)

But I can change it back for all places, if you want?

Comment (MathiasReker) [reply install-dev/data/db_structure.sql]: Fixed

**Comment by MathiasReker** [comment]
@Quetzacoalt91 @PierreRambaud wdyt?

**Comment by MathiasReker** [comment]
I really hope this can be merged to 1.7.5, since it fix many issues.

File: install-dev/data/db_structure.sql [hunk 6]
```diff
@@ -1,2630 +1,2821 @@
...
-  PRIMARY KEY (`id_employee`),
-  KEY `employee_login` (`email`,`passwd`),
-  KEY `id_employee_passwd` (`id_employee`,`passwd`),
+  `id_employee` int(10) unsigned NOT NULL auto_increment, 
+  `id_profile` int(10) unsigned NOT NULL, 
+  `id_lang` int(10) unsigned NOT NULL DEFAULT '0', 
+  `lastname` varchar(255) NOT NULL, 
+  `firstname` varchar(255) NOT NULL, 
+  `email` varchar(255) NOT NULL, 
+  `passwd` varchar(2048) NOT NULL,
```
Comment (Quetzacoalt91) [inline install-dev/data/db_structure.sql]: This column type does not fit the `Employee` class

File: install-dev/data/db_structure.sql [hunk 7]
```diff
@@ -1,2630 +1,2821 @@
...
-  `id_operating_system` int(10) unsigned DEFAULT NULL,
-  `id_web_browser` int(10) unsigned DEFAULT NULL,
-  `id_customer` int(10) unsigned DEFAULT NULL,
-  `javascript` tinyint(1) DEFAULT '0',
-  `screen_resolution_x` smallint(5) unsigned DEFAULT NULL,
-  `screen_resolution_y` smallint(5) unsigned DEFAULT NULL,
-  `screen_color` tinyint(3) unsigned DEFAULT NULL,
-  `sun_java` tinyint(1) DEFAULT NULL,
-  `adobe_flash` tinyint(1) DEFAULT NULL,
-  `adobe_dire
```
Comment (Quetzacoalt91) [inline install-dev/data/db_structure.sql:1809]: This column does not match the definition in `Product.php`

Comment (Quetzacoalt91) [inline install-dev/data/db_structure.sql]: This column does not match the class `Referrer.php`

File: install-dev/upgrade/sql/1.7.5.0.sql [hunk 8]
```diff
@@ -1,12 +1,83 @@
...
+  CHANGE `meta_description` `meta_description` VARCHAR(512) DEFAULT NULL,
+  CHANGE `meta_title` `meta_title` VARCHAR(255) DEFAULT NULL;
+
+ALTER TABLE `PREFIX_order_detail`
+  CHANGE `product_reference` `product_reference` varchar(64) DEFAULT NULL;
+
+ALTER TABLE `PREFIX_product`
+  CHANGE `reference` `supplier_reference` varchar(64) DEFAULT NULL,
+  CHANGE `supplier_reference` `supplier_reference` varchar(64) DEFAULT NULL;
+
```
Comment (Quetzacoalt91) [inline install-dev/upgrade/sql/1.7.5.0.sql:69]: It seems the product_lang schema is not updated

**Comment by Quetzacoalt91** [comment]
Hi @MathiasReker,

We can't promise to make this PR available on 1.7.5.0, a beta build is closed to be published and we have not validated your PR yet. The only thing we are currently sure about is to have it for 1.7.6.0.

**Comment by MathiasReker** [comment]
I am solving your comments right now 🐇

File: install-dev/data/db_structure.sql (hunk 6 above)
Comment (MathiasReker) [reply install-dev/data/db_structure.sql]: Fixed

File: install-dev/data/db_structure.sql (hunk 7 above)
Comment (MathiasReker) [reply install-dev/data/db_structure.sql]: Fixed

File: install-dev/upgrade/sql/1.7.5.0.sql (hunk 8 above)
Comment (MathiasReker) [reply install-dev/upgrade/sql/1.7.5.0.sql:69]: Fixed

File: install-dev/data/db_structure.sql (hunk 7 above)
Comment (MathiasReker) [reply install-dev/data/db_structure.sql:1809]: I did not change anything related to this in my PR :-)

Comment (MathiasReker) [reply install-dev/data/db_structure.sql]: I did not change anything related to this in my PR :-)

Comment (MathiasReker) [reply install-dev/data/db_structure.sql:1809]: If there is an issue, can this be fixed in an other PR?

**Comment by MathiasReker** [comment]
@Quetzacoalt91 Should be OK now.

File: install-dev/data/db_structure.sql (hunk 7 above)
Comment (MathiasReker) [reply install-dev/data/db_structure.sql]: If there is an issue, can this be fixed in an other PR?

Comment (Quetzacoalt91) [reply install-dev/data/db_structure.sql:1809]: You actually did :)

https://github.com/PrestaShop/PrestaShop/pull/10446/files#diff-0a7a17e9ff155e6890d7a5b01eea713cR391

In `Product.php`, `meta_title` is now a varchar(255).

Comment (MathiasReker) [reply install-dev/data/db_structure.sql:1809]: I just updated meta_title in this commit: https://github.com/PrestaShop/PrestaShop/pull/10446/commits/b1486074c8a22985e2f0135235816bb3dada3cd8 :) But I did not change anything related to `adobe_dire` ?

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @MathiasReker 

We have a problem, if I create a CMS page witth a meta title = 255 chars, the display is broken

capture d ecran_521

For categories, meta title is limited to 70 and meta description to 160

capture d ecran_522

If I create a customer with an email = 255 chars, the display is broken

capture d ecran_523

In FO the customer's email is blocked to 128

capture d ecran_524

For employees, the table is also broken

capture d ecran_525

**Comment by MathiasReker** [comment]
@marionf I will look into this now

**Comment by marionf** [comment]
thank you @MathiasReker

**Comment by MathiasReker** [comment]
WIP

**Comment by MathiasReker** [comment]
Everything should be fixed now! :-) Please have a look @marionf

**Comment by marionf** [comment]
Thank you @MathiasReker for your fixes

1) If I edit a category and add all chars for meta title and meta description and save:

capture d ecran_531

When I edit the category, it looks like all chars have not been saved

capture d ecran_533

2) If I try to create a customer in FO with the email aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac@prestashop.com
(247 chars)
I have an exception

capture d ecran_534

**Comment by MathiasReker** [comment]
`If I edit a category and add all chars for meta title and meta description and save:` I can not reproduce, it works on my end.

**Comment by MathiasReker** [comment]
`If I try to create a customer in FO with the email` I am looking into this now

**Comment by MathiasReker** [comment]
@marionf I can't reproduce your first issue. The second is fixed.

**Comment by MathiasReker** [comment]
show 1
@marion

**Comment by MathiasReker** [comment]
I checked again, I really can't reproduce your first issue. Can you check your database, if the fields are updated?

**Comment by MathiasReker** [comment]
@Quetzacoalt91 Sorry, I had to solve some issues, so your review is now not valid anymore. Can you approve again?

File: classes/Mail.php [hunk 9]
```diff
@@ -58,7 +58,7 @@ class MailCore extends ObjectModel
                 'validate' => 'isEmail',
                 'copy_post' => false,
                 'required' => true,
-                'size' => 126,
+                'size' => 255,
```
Comment (Quetzacoalt91) [inline classes/Mail.php:61]: When you apply changes to the model, make sure you update `db_structure.sql` & the equivalent upgrade file or it will remain invalid.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by marionf** [comment]
It's ok @MathiasReker 

The table had not been updated 

capture d ecran_535

File: classes/Mail.php (hunk 9 above)
Comment (MathiasReker) [reply classes/Mail.php:61]: I already did. The reason why I had to change this file now, is that the email validator was not updated and that caused an exception. There were several places to update the size without in the database files, and this place was missing. :)

**Comment by MathiasReker** [comment]
> 
> 
> It's ok @MathiasReker
> 
> The table had not been updated
> 
> capture d ecran_535

Weird, did your run the database update script?

**Comment by MathiasReker** [comment]
@marionf btw, everyting is OK now? :)

**Comment by marionf** [comment]
Humm, I still have the exception in FO

**Comment by MathiasReker** [comment]
solved 1
@marionf It is working for me. Try to clear your cache.

**Comment by MathiasReker** [comment]
I removed %mail% from the error msg. Check my last gif to see why.

**Comment by marionf** [comment]
If you add a product to your cart and click on Continue without complete the "Password" field it works.
The exception is showing if you complete the password field during checkout.
You can also see it if you try to create a new account without cart/order

https://drive.google.com/file/d/1N7gdZq2Zt_kMrAMNziulXH35O9G_tXXP/view?usp=sharing

**Comment by MathiasReker** [comment]
Thank for clarifying, its fixed now :)

**Comment by marionf** [comment]
All good, thank you very much @MathiasReker

**Review by jolelievre — DISMISSED** [review]
nice job @MathiasReker

**Comment by Quetzacoalt91** [comment]
Requesting @LouiseBonnard review about the catalog update :)

File: app/Resources/translations/default/ShopNotificationsError.xlf [hunk 10]
```diff
@@ -527,8 +527,8 @@ File: classes/stock/SupplyOrderDetail.php:339</note>
 File: classes/form/CustomerForm.php:178</note>
       </trans-unit>
       <trans-unit id="b99c284c2a24cf024e5811c89706bf79">
-        <source>The email "%mail%" is already used, please choose another one or sign in</source>
-        <target>The email "%mail%" is already used, please choose another one or sign in</target>
+        <source>The email is already used, please choose another one or sign in</source>
```
Comment (LouiseBonnard) [inline app/Resources/translations/default/ShopNotificationsError.xlf:530]: Why removing the mention of the mail?

Comment (jolelievre) [reply app/Resources/translations/default/ShopNotificationsError.xlf:530]: I think it's because of this issue 
jonathan-22

Comment (MathiasReker) [reply app/Resources/translations/default/ShopNotificationsError.xlf:530]: 47718673-426d9000-dc49-11e8-94b5-e854c02fe06a

Because the message box is too small for many email addresses and the email address is obvious, it is written in the field above :) You can see on the gif what I mean.

Comment (MathiasReker) [reply app/Resources/translations/default/ShopNotificationsError.xlf:530]: @jolelievre you were 30 sec faster than me 😆

**Comment by MathiasReker** [comment]
@jolelievre can you review last commits? I had to prevent design issues if name were too long. Also I fixed a bug with filterkey.

**Comment by jolelievre** [comment]
@MathiasReker it's good for me, if it's ok for @LouiseBonnard and @Quetzacoalt91 the we can push it towards a last QA

**Comment by Quetzacoalt91** [comment]
@MathiasReker you should stick to the database update, especially when the changes duplicate other PRs like https://github.com/PrestaShop/PrestaShop/pull/11179.

Everytime you add changes we must make another review, ask the QA to check again, and this prevent the PR to be merged. If we want to make it available for 1.7.5.0, we must now avoid adding other fixes not related to the original topic. ;)

**Comment by MathiasReker** [comment]
> 
> 
> @MathiasReker you should stick to the database update, especially when the changes duplicate other PRs like #11179.
> 
> Everytime you add changes we must make another review, ask the QA to check again, and this prevent the PR to be merged. If we want to make it available for 1.7.5.0, we must now avoid adding other fixes not related to the original topic. ;)

I reverted missing filterkey.

**Comment by MathiasReker** [comment]
@Quetzacoalt91 the other commit is still important for this issue, because the design can be broken if use of too long names.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by MathiasReker** [comment]
thank you @Quetzacoalt91 :)

**Comment by MathiasReker** [comment]
Sorry @Quetzacoalt91, I had to solve some lint issues because travis ci was failing. :/

**Comment by MathiasReker** [comment]
Everything should be OK now.

**Comment by marionf** [comment]
@MathiasReker 

I have an exception if I try to send a message through the contact form with an email address > 255 chars

capture d ecran_543

Also the table on the Contact page is broken

capture d ecran_544

**Comment by MathiasReker** [comment]
WIP

**Comment by MathiasReker** [comment]
@marionf @Quetzacoalt91 I did not introduce this exception. I can reproduce the issue here as well: http://fo.demo.prestashop.com/en/contact-us. As far as I see the contact module is missing a check for email length. I solved the issue (please correct me if I solved it wrong), but to get it work, you need to merge both this PR and this: https://github.com/PrestaShop/contactform/pull/30/files

**Comment by MathiasReker** [comment]
The design issue is fixed too.

**Comment by MathiasReker** [comment]
The test are no more parsing since I replaced tabs with spaces for some other code in files that I was working in:
classes/Product.php
classes/Contact.php

**Comment by MathiasReker** [comment]
Sorry, I don't see exactly why the tests are failing. Can you help me?

**Comment by Quetzacoalt91** [comment]
All PRs and build are currently failing (https://travis-ci.org/PrestaShop/PrestaShop/pull_requests) and we need to investigate. You can only fix the lint builds on your side.

**Comment by MathiasReker** [comment]
@Quetzacoalt91 I don't think there is an issue then, I ran cs fixer.

**Comment by Quetzacoalt91** [comment]
PR rewritten to squash commits when possible and to rebase over `1.7.5.x`

**Comment by Quetzacoalt91** [comment]
Thank you @MathiasReker
