### PR TITLE
Remove notice on field value on webservice

### LINKED ISSUE #12056: [PHP Notice #8] Undefined index: value (classes/webservice/WebserviceOutputXML.php, line 128)
**Describe the bug**
On Prestashop webservice from 1.6.1.x to 1.7.5.x, when I'm requesting URL "/api/customers/2", I have the following warning:

>  [PHP Notice #8] Undefined index: value (classes/webservice/WebserviceOutputXML.php, line 128) 

Customer n°01 (default "John DOE" customer) is queryable successfully, but not others.

I'm not on a fresh install of Prestashop and I overrided some tables and classes, so I think you can't reproduce this error but, anyway, it's important to test if a variable exists before use it. 

**To Reproduce**
1. Request "shop-url.com/api/customers/2"
2. See error "[PHP Notice #8] Undefined index: value (classes/webservice/WebserviceOutputXML.php, line 128)"

**Screenshots**
Screenshot of error + relative source code 
errror_webserviceoutputxml

**To Resolve**
Replace line 128:
`            if ($field['value'] != '') {`
By:
`            if (isset($field['value']) && $field['value'] != '') {`

**Additionnal information**
PrestaShop version: 1.6.1.23 (but same until 1.7.5.x)
PHP version: 5.6

### PR DESCRIPTION
**Pull request by Klemart3D**
Update for https://github.com/PrestaShop/PrestaShop/pull/12213
To fix #12056

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check if $field['value'] is set before display it
| Type?         | bug fix
| Category?     | WS
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12056 
| How to test?  | Check API with NULL values in place of empty values into database. eg: try api/customers/1 URL with a "website" or "company" value set to NULL into DB in place of empty field.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12213)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

File: classes/webservice/WebserviceOutputXML.php [hunk 1]
```diff
@@ -135,7 +135,7 @@ public function renderField($field)
                 $ret .= ' read_only="true"';
             }
 
-            if ($field['value'] !== '') {
+            if (!empty($field['value'])) {
```
Comment (PierreRambaud) [inline classes/webservice/WebserviceOutputXML.php]:
```suggestion
            if (array_key_exists('value', $field)) {
```

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Do not use empty, the value can be false, 0, null

**Comment by Klemart3D** [comment]
> Do not use empty, the value can be false, 0, null

@PierreRambaud It was your suggestion:
https://github.com/PrestaShop/PrestaShop/pull/12213/files/2e87ccdc94a1228acdf9042c843b33a36f377343#r249060236

**Comment by PierreRambaud** [comment]
> > Do not use empty, the value can be false, 0, null
> 
> @PierreRambaud It was your suggestion:
> https://github.com/PrestaShop/PrestaShop/pull/12213/files/2e87ccdc94a1228acdf9042c843b33a36f377343#r249060236

Lol :sweat_smile: I read it too fast last time and don't check the original behaviour. My bad :/

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Klemart3D,

Your PR is OK :heavy_check_mark: 
But, in the develop branch, I can't reproduce the issue.

Ping @PrestaShop/prestashop-core-developers can we accept this PR? 

Thanks!

**Comment by PierreRambaud** [comment]
@khouloudbelguith Yes, only to be consistent with the whole method content :)

**Comment by matks** [comment]
Thank you @Klemart3D
