### PR TITLE
FO - Validate field values when creating customer account

### LINKED ISSUE #24464: FO - Create Account / Checkout page - Order as a guest / Adresses step - Exception displayed when Firstname, Lastname or City are invalid
#### Describe the bug

In the FO > Checkout page > Order as a guest part, when we set the firstname & lastname with invalid data, an exception is displayed
Also, when we create an address in the checkout page with invalid firstname & lastname & City => an exception is displayed.

Edit by @Robin-Fischer-PS : In FO > Create an account, an exception is also displayed when the firstname and/or lastname fields contain invalid characters.

#### Expected behavior

We should have an alert as in PS1774
image
image

#### Steps to Reproduce

1. Go to FO
2. Add a product to the cart and proceed to checkout
3. In the Checkout page > Create a customer or a guest with invalid firstname & lastname
4. Set other required fields and click continue
5. See error
6. In the addresses step: create a new address with invalid firstname & lastname & city
7. Click continue
8. See error

Other steps : 

1. Go to FO > Create an account
2. Fill in the fields, with invalid character in "firstname" or "lastname" fields (for example "lastname1"
3. Save : An exception is displayed.

**Screenshots**
1. lastname
FO_guest_lastname
2. Firstname
FO_guest_firsname
3. City
FO_address_city
4. address firstname & lastname
FO_address_lastname
FO_address_firstname

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.2 & 7.4

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Restore validation on customer account creation form. Pre-validate values before trying to save customer or address to avoid exception raise
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24464 
| How to test?      | See the well described issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24599)

### CODE REVIEW

File: classes/form/CustomerForm.php [hunk 1]
```diff
@@ -275,4 +277,46 @@ private function validateByModules()
...
+     * Performs validation on field values.
+     * Adds error to the field object if value is not as expected.
+     */
+    private function validateFieldsValues(): void
+    {
+        $this->validateFirstname();
+        $this->validateLastname();
+    }
+
+    private function validateFirstname(): void
```
Comment (matks) [inline classes/form/CustomerForm.php]: This function seems almost identical to `validateLastname()` - only field name changes. Maybe we could have a `validateFiedIsCustomerName($fieldName);` unique function for both?

File: classes/form/CustomerAddressForm.php [hunk 2]
```diff
@@ -217,4 +203,111 @@ function (FormField $item) {
...
+
+                    return false;
+                }
+            }
+        }
+
+        return true;
+    }
+
+    private function validateCity(): bool
```
Comment (matks) [inline classes/form/CustomerAddressForm.php]: Seems very close to `CustomerForm::validateLastname()`
- fieldname change
- there is some checks on `$field->isRequired()`
- `isCityName()` is used instead of `isCustomerName()`

So we could use a unique function for both usecases?
```
public function validateField(string $fieldName, $mustBeRequired = true, $validationFunction)

...

$isValid &= $this->validateField('city', true, 'isCityName');
```

**Review by matks — COMMENTED** [review]
> Pre-validate values before trying to save customer or address to avoid exception raise

So your plan is "let's catch errors in the fields early, so that invalid data is not sent to ObjectModel which would throw exceptions" ?

But if tomorrow we modify a bit ObjectModel validation, and we do not update this form validation, we will have again exception usecases 🤔  ?

May I suggest to _also_ add a try/catch statement at the right place, so that when ObjectModel fails to validate the data we would avoid displaying an exception page to merchant? It would be better to have a generic error message. I'm not sure, tell me wdyt 😉

File: classes/form/CustomerAddressForm.php (hunk 2 above)
Comment (sowbiba) [reply classes/form/CustomerAddressForm.php]: I thought exactly the same but making it over generic will make it hard to understand and if we want to add a specific case for one of the fields, we will have to break the generic
But why not? I can apply your suggestion ;)

File: classes/form/CustomerForm.php (hunk 1 above)
Comment (sowbiba) [reply classes/form/CustomerForm.php]: :+1:

File: classes/form/CustomerAddressForm.php (hunk 2 above)
Comment (matks) [reply classes/form/CustomerAddressForm.php]: @sowbiba If you are thinking "ok today I can do X, but maybe in future X will not be good if some changes require to be done"... then I answer [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) 😉 

> "You aren't gonna need it" is a principle of extreme programming (XP) that states a programmer should not add functionality until deemed necessary. XP co-founder Ron Jeffries has written: "Always implement things when you actually need them, never when you just foresee that you need them." Other forms of the phrase include "You aren't going to need it" and "You ain't gonna need it".

Comment (sowbiba) [reply classes/form/CustomerAddressForm.php]: 👍🏾 And that is a principle of agility : do what you need today
There is another difference between 'city' and the names : The error message
I can give it as parameter too :D

**Review by Julievrz — DISMISSED** [review]
Wording ✔️ 
Thank you

File: classes/form/CustomerAddressForm.php [hunk 3]
```diff
@@ -154,10 +140,16 @@ public function submit()
...
-            $address,
-            $this->getValue('token')
-        );
+        try {
+            return $this->getPersister()->save(
+                $address,
+                $this->getValue('token')
+            );
+        } catch (PrestaShopException $e) {
+            $this->errors[''][] = $this->translator->trans('Could not update your information, please check your data.', [], 'Shop.Notifications.Error');
```
Comment (sowbiba) [inline classes/form/CustomerAddressForm.php:149]: @Julievrz 
I found this generic message to say that there is something wrong in the form and we can't save it
Maybe you can suggest another one :) Thanks

Comment (Julievrz) [reply classes/form/CustomerAddressForm.php:149]: I tried, but I couldn't find better wording. I think this one is ok as it has a pretty logical domain.

File: classes/form/CustomerForm.php [hunk 4]
```diff
@@ -275,4 +282,30 @@ private function validateByModules()
...
+     * Performs validation on field values.
+     * Adds error to the field object if value is not as expected.
+     */
+    private function validateFieldsValues(): void
+    {
+        $this->validateFieldIsCustomerName('firstname');
+        $this->validateFieldIsCustomerName('lastname');
+    }
+
+    private function validateFieldIsCustomerName($fieldName): void
```
Comment (Progi1984) [inline classes/form/CustomerForm.php]:
```suggestion
    private function validateFieldIsCustomerName(string $fieldName): void
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/form/CustomerAddressForm.php [hunk 5]
```diff
@@ -217,4 +209,73 @@ function (FormField $item) {
...
+
+                    return false;
+                }
+            }
+        }
+
+        return true;
+    }
+
+    private function validateField(string $fieldName, string $validationFunction, string $validationFailMessage): bool
```
Comment (matks) [inline classes/form/CustomerAddressForm.php:272]: PHPDoc might be useful for developers using an IDE that does not support type hinting

File: classes/form/CustomerForm.php [hunk 6]
```diff
@@ -275,4 +282,35 @@ private function validateByModules()
...
+        $this->validateFieldIsCustomerName('firstname');
+        $this->validateFieldIsCustomerName('lastname');
+    }
+
+    /**
+     * Checks whether a field's value is a valid customer(person) name.
+     *
+     * @param string $fieldName
+     */
+    private function validateFieldIsCustomerName(string $fieldName): void
```
Comment (matks) [inline classes/form/CustomerForm.php:301]: It would be great to be able to validate the behavior using tests. But it seems CustomerForm class rely heavily on static calls and singleton instances, so isolating it might be a very hard task?

**Review by matks — DISMISSED** [review]
Code is good for me. Added some suggestions but not blocking

**Review by matks — DISMISSED** [review]
I approve the code 👍  

Did you check if it's possible to test this scenario ? 😉

File: classes/form/CustomerAddressForm.php [hunk 7]
```diff
@@ -217,4 +209,83 @@ function (FormField $item) {
...
+     * Returns true if all field values are correct, false otherwise.
+     *
+     * @return bool
+     */
+    private function validateFieldsValues(): bool
+    {
+        $isValid = true;
+
+        $isValid &= $this->validatePostcode();
+        $isValid &= $this->validateField('firstname', 'isName', $this->translator->trans(
```
Comment (kpodemski) [inline classes/form/CustomerAddressForm.php:224]: @sowbiba why `Address->firstname` is not validated the same way as `Customer->firstname`? with `isCustomerName`?

Comment (sowbiba) [reply classes/form/CustomerAddressForm.php:224]: It's the way it was done in the objectModels
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Address.php#L129
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Customer.php#L181 

But  isCustomer seems to be more restrictive about authorized characters so maybe better. But ... I will then modify the behaviour

**Comment by sowbiba** [comment]
> I approve the code 
> 
> Did you check if it's possible to test this scenario ?

I can instantiate the form (with mocked dependencies), fill data and call validate. I'll give a try ;)

**Comment by sowbiba** [comment]
> > I approve the code
> > Did you check if it's possible to test this scenario ?
> 
> I can instantiate the form (with mocked dependencies), fill data and call validate. I'll give a try ;)

Checked. Too many requests done to DB. I mocked a lot of things and finally was stopped by a query done in the middle of the *validate* method to check if the customer exists. So I was not able to test the validation with that state of the implementation

**Review by kpodemski — DISMISSED** [review]

**Review by Progi1984 — COMMENTED** [review]
Please add unit tests

**Comment by matks** [comment]
> Please add unit tests

@sowbiba did an analyzis to find out how this class could be tested, but it seems there is way too much coupling in the class, making attempts to test it a bad spaghetti soup 🍝

**Review by Progi1984 — DISMISSED** [review]

File: classes/form/CustomerAddressForm.php (hunk 3 above)
Comment (PierreRambaud) [inline classes/form/CustomerAddressForm.php:149]:
```suggestion
            $this->errors[] = [
                $this->translator->trans(
                    'Could not update your information, please check your data.', 
                    [], 
                    'Shop.Notifications.Error'
                )
            ];
```

File: classes/form/CustomerAddressForm.php [hunk 8]
```diff
@@ -217,4 +209,83 @@ function (FormField $item) {
...
+                        ['%zipcode%' => $country->zip_code_format],
+                        'Shop.Forms.Errors'
+                    ));
+
+                    return false;
+                }
+            }
+        }
+
+        return true;
```
Comment (PierreRambaud) [inline classes/form/CustomerAddressForm.php]:
```suggestion
        $postcode = $this->getField('postcode');
        
        if ($postcode && $postcode->isRequired()) {
            $country = $this->formatter->getCountry();
            if (!$country->checkZipCode($postcode->getValue())) {
                $postcode->addError($this->translator->trans(
                    'Invalid postcode - should look like "%zipcode%"',
                    ['%zipcode%' => $country->zip_code_format],
                    'Shop.Forms.Errors'
                ));

                return false;
            }
        }

        return true;
```

File: classes/form/CustomerForm.php [hunk 9]
```diff
@@ -211,12 +213,17 @@ public function submit()
...
-            );
+            try {
+                $ok = $this->customerPersister->save(
+                    $this->getCustomer(),
+                    $clearTextPassword,
+                    $newPassword,
+                    $this->passwordRequired
+                );
+            } catch (PrestaShopException $e) {
+                $this->errors[''][] = $this->translator->trans('Could not update your information, please check your data.', [], 'Shop.Notifications.Error');
```
Comment (PierreRambaud) [inline classes/form/CustomerForm.php:224]:
```suggestion
                $this->errors[] = [
                    $this->translator->trans(
                        'Could not update your information, please check your data.', 
                        [], 
                        'Shop.Notifications.Error'
                    )
                ];
```

**Comment by SD1982** [comment]
LGTM !!
Thanks @sowbiba !!

**Comment by Progi1984** [comment]
@sowbiba Could you fix coding style for @PierreRambaud before merging your PR ? (No impact on behavior)

**Comment by PierreRambaud** [comment]
> @sowbiba Could you fix coding style for @PierreRambaud before merging your PR ? (No impact on behavior)

It's also because we shouldn't use `$this->errors[''][]` it's never used like that. :thinking:

File: classes/form/CustomerAddressForm.php (hunk 3 above)
Comment (Progi1984) [reply classes/form/CustomerAddressForm.php:149]:
```suggestion
            $this->errors[] = $this->translator->trans('Could not update your information, please check your data.', [], 'Shop.Notifications.Error');
```

**Review by Progi1984 — COMMENTED** [review]
A last one @sowbiba

File: classes/form/CustomerAddressForm.php (hunk 3 above)
Comment (Progi1984) [reply classes/form/CustomerAddressForm.php:149]: Ping @sowbiba

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Ping @PierreRambaud

File: classes/form/CustomerForm.php [hunk 10]
```diff
@@ -275,4 +282,35 @@ private function validateByModules()
...
+     */
+    private function validateFieldIsCustomerName(string $fieldName): void
+    {
+        $field = $this->getField($fieldName);
+        if (null === $field) {
+            return;
+        }
+        $value = $field->getValue();
+        if (!empty($value) && false === (bool) Validate::isCustomerName($value)) {
+            $field->AddError($this->translator->trans(
```
Comment (PierreRambaud) [inline classes/form/CustomerForm.php]:
```suggestion
            $field->addError($this->translator->trans(
```

Just notice the method name is not the right one.

File: classes/form/CustomerAddressForm.php [hunk 11]
```diff
@@ -217,4 +209,82 @@ function (FormField $item) {
...
+        $field = $this->getField($fieldName);
+        if (null === $field) {
+            return true;
+        }
+        $value = $field->getValue();
+        if ($field->isRequired() && empty($value)) {
+            return false;
+        }
+        if (!empty($value) && false === (bool) Validate::$validationFunction($value)) {
+            $field->AddError($validationFailMessage);
```
Comment (PierreRambaud) [inline classes/form/CustomerAddressForm.php]:
```suggestion
            $field->addError($validationFailMessage);
```
Just notice the method name is not the right one.

File: classes/form/CustomerForm.php [hunk 12]
```diff
@@ -211,12 +213,17 @@ public function submit()
...
-            );
+            try {
+                $ok = $this->customerPersister->save(
+                    $this->getCustomer(),
+                    $clearTextPassword,
+                    $newPassword,
+                    $this->passwordRequired
+                );
+            } catch (PrestaShopException $e) {
+                $this->errors[] = $this->translator->trans('Could not update your information, please check your data.', [], 'Shop.Notifications.Error');
```
Comment (PierreRambaud) [inline classes/form/CustomerForm.php]: In Form context, errors are in format `array<int, array>` I'm not sure it's  `array<int, string>`

Comment (sowbiba) [reply classes/form/CustomerForm.php]: After manual testing

The errors array key needs to be a string and its value an array with the error msg as string

if the key is a field name, it will be displayed in front of the field. if it's empty string it's a global error

That explains why it's instantiated like https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/form/AbstractForm.php#L41

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

File: classes/form/CustomerForm.php (hunk 12 above)
Comment (PierreRambaud) [reply classes/form/CustomerForm.php]: It's clearly a weird syntax, but anyway :sweat_smile:

**Review by PierreRambaud — APPROVED** [review]

**Comment by sowbiba** [comment]
@SD1982 Do you want to re-check ?

**Comment by sowbiba** [comment]
Spoke with @SD1982 . Go merge
