### PR TITLE
Handle fallback when currency has empty display names

### LINKED ISSUE #27921: BO - An exception is displayed when editing a currency with a custom lanaguage
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed when editing a currency with a custom language.
This issue is reproduced only with PHP7.4
image

I checked S1784 + php7.3 => ok
I checked develop + php7.3 => OK

I checked 1784 + php7.4 => NOK
I checked 1780 + php7.4 => NOK
I checked develop + php7.4 => NOK

Prestashop 1778 is not compatible with PHP7.4

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > International > Localization > Languages page
2. Create a new language like this 
image
3. Change the employee language to this one created
4. Go to BO > International > Localization > currencies page
5. Edit a currency 
6. See error 

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.4, develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Avoid bug when display names of a currency are empty which happens which custom languages, in this case we use the iso code as a fallback
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27921
| Related PRs       | This fix was originally fixed in this PR https://github.com/PrestaShop/PrestaShop/pull/28081 which has been closed
| How to test?      | Follow ticket instruction.
| Possible impacts? | ~

### CODE REVIEW

**Comment by jolelievre** [comment]
Hi @marwachelly 

this PR fixes the initial bug and also the one you discovered here https://github.com/PrestaShop/PrestaShop/pull/28081#pullrequestreview-933499129

**Review by ghost — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Core/Localization/CLDR/Currency.php [hunk 1]
```diff
@@ -140,6 +140,10 @@ public function getDecimalDigits()
      */
     public function getDisplayName($countContext = CurrencyInterface::DISPLAY_NAME_COUNT_DEFAULT)
     {
+        if (empty($this->displayNames)) {
+            return $this->isoCode;
```
Comment (Progi1984) [inline src/Core/Localization/CLDR/Currency.php]: Could you add an Unit Test in `tests/Unit/Core/Localization/CLDR/CurrencyTest.php` ?

**Review by Progi1984 — DISMISSED** [review]
A small feedback but I approve.

File: src/Core/Localization/CLDR/Currency.php (hunk 1 above)
Comment (jolelievre) [reply src/Core/Localization/CLDR/Currency.php]: Yep good call!

Comment (Progi1984) [reply src/Core/Localization/CLDR/Currency.php]: Ping me after that and I will approve a new time :heart_eyes_cat:

**Comment by jolelievre** [comment]
@Progi1984 unit tests added 😉

**Comment by jolelievre** [comment]
Also will need re-approval from @matthieu-rolland or @okom3pom

**Review by Progi1984 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @jolelievre ,

Thanks for the PR

Tested the following with PHP 7.3 and 7.4:

- Created a new language and edited it
- Edited currency (edit symbol/format + reset)
- Restored default settings
- Created a new currency (tested with an existing currency + a manually created one)
- Deletion of a currency and the new language OK
- In FO, configuration of language and currency is well saved

No more exception is displayed ✅ 

It is QA ✅

**Comment by Progi1984** [comment]
Thanks @jolelievre & @florine2623
