### PR TITLE
Don't trim arrays in AdminStoresController::postProcess : they delete it

### LINKED ISSUE #21624: Extra post array are deleted in AdminStoresController::postProcess
#### Describe the bug

Any array extra post vars are deleted on save by AdminStoresController::postProcess

#### Steps to Reproduce

1. Create a module or an override
2. Add a new HelperForm field in AdminStoreController, by example a select with 'multiple' => true
3. Try to save or dump this field : it's always empty

* PrestaShop version: 1.7.6
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jf-viguier**
Extra post array are deleted in AdminStoresController::postProcess because if this trim on array

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | check that POST var is a string before trim it
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21624
| How to test?  | see in the issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21625)

### CODE REVIEW

File: controllers/admin/AdminStoresController.php [hunk 1]
```diff
@@ -333,7 +333,7 @@ public function postProcess()
             $langs = Language::getLanguages(false);
             /* Cleaning fields */
             foreach ($_POST as $kp => $vp) {
-                if (!in_array($kp, ['checkBoxShopGroupAsso_store', 'checkBoxShopAsso_store', 'hours'])) {
```
Comment (matks) [inline controllers/admin/AdminStoresController.php:336]: @jf-viguier If you do this, then you also disable trim capabilities on not-string fields such as numeric inputs.

I'm not sure whether that's an issue 🤔  do the numeric inputs in the Stores BO page (ZIP code, longitude, latitude) behave OK ? I guess yes because they are passed as strings from $_POST.

What else can we get from $_POST ? Only strings and arrays ?

Comment (jf-viguier) [reply controllers/admin/AdminStoresController.php:336]: @matks $_POST values are always strings or array of strings I guess. Integer casting is done after the trim.
By the way there are number_format for lat/long, (int) casting for ids. Postcode is a string (think about Corsica)

Comment (matks) [reply controllers/admin/AdminStoresController.php:336]: This change seems OK then.

But I have another one 😁 : previous implementation was NOT trimming if `$kp` was one of 'checkBoxShopGroupAsso_store', 'checkBoxShopAsso_store' or 'hours'.

If I am not wrong, with your new implementation you DO trim these 3 values.

So in order to keep the "dont trim these 3" we need to do keep the "exclusion list" but _add_ the string type check:
```
if (!in_array($kp, ['checkBoxShopGroupAsso_store', 'checkBoxShopAsso_store', 'hours']) && is_string($kp)) {
```

Comment (jf-viguier) [reply controllers/admin/AdminStoresController.php:336]: No, these 3 ones are arrays

Comment (matks) [reply controllers/admin/AdminStoresController.php:336]: Haha 😄  so it works

Thanks for answering, I approve the PR

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@jf-viguier I'm afraid you need to rebase to make CI pass. Because of this weekend release of Composer v2 [our CI pipeline was broken](https://github.com/PrestaShop/PrestaShop/issues/21621). It's fixed now but all PRs failing need to be rebased.

**Comment by jf-viguier** [comment]
@matks I've done a rebase on my branch patch-6, please check

**Comment by jf-viguier** [comment]
@matks all checks have passed now, you can ask for another review ?

**Comment by matks** [comment]
> @matks all checks have passed now, you can ask for another review ?

I'm sure the review machines @Progi1984 and @PierreRambaud will come here soon 👀

File: controllers/admin/AdminStoresController.php [hunk 2]
```diff
@@ -333,7 +333,7 @@ public function postProcess()
...
+                if (is_string($kp)) {
```
Comment (PululuK) [inline controllers/admin/AdminStoresController.php]:
```suggestion
                if (is_string($vp)) {
```

**Review by PululuK — COMMENTED** [review]
In this case, you need to check the value and not the key.

File: controllers/admin/AdminStoresController.php (hunk 2 above)
Comment (matks) [reply controllers/admin/AdminStoresController.php]: @PululuK Oooooh you're right 😮  I did not see that.

One good reason to avoid short variable names like this 😅

**Comment by jf-viguier** [comment]
Thanks @PululuK You're right

**Review by PululuK — APPROVED** [review]

**Comment by jf-viguier** [comment]
What's wrong with travis here ? @PululuK ? @matks ?

**Comment by jf-viguier** [comment]
Can I have a validation for hacktoberfest ?

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
> What's wrong with travis here ? @PululuK ? @matks ?

We're just busy fine-tuning the 1.7.7.0 RC1 over and over 😞 it's so hard to release something flawless

- I approved your PR so it should be acknowledged for Hacktoberfest
- I restarted the failing Travis build as I think it failed for wrong reasons

**Comment by jf-viguier** [comment]
Thanks @PululuK @matks everything seems ok now and good luck for RC1

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I added this code line
```php
                [
                    'type' => 'select',
                    'label' => $this->trans('multiple select', array(), 'Admin.Global'),
                    'name' => 'multiple_select',
                    'required' => true,
                    'multiple' => true,
                    'default_value' => (int) $this->context->country->id,
                    'options' => array(
                        'query' => Country::getCountries($this->context->language->id),
                        'id' => 'id_country',
                        'name' => 'name',
                    ),
                ],
```
after this line [controllers/admin/AdminStoresController.php](https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminStoresController.php#L221).
But, when I try to Create a new store with selecting multiple data, it is still not saved.
image
I attached a screen record
https://drive.google.com/file/d/1Tu-UEfPTobzbLkzn79bjBMoYr3W9GOk-/view?usp=sharing

Thanks to check and feedback.

**Comment by PululuK** [comment]
Hi @khouloudbelguith, 

Yes, because you did not manage the persistence of this data, so it is not related to this PR.

I think you should test this way : 

Put this code here : https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminStoresController.php#L349
```php 
var_dump($_POST['multiple_select']); exit;
```
- **Before this PR**  :  must return empty
- **After this PR**  :  must return data selected

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

Thank you, it help's :slightly_smiling_face: 

@jf-viguier, it is ok :heavy_check_mark: 
**Without PR**
image

**With PR**
image

Thank you!

**Comment by jf-viguier** [comment]
Thanks @PululuK, you rocks

**Comment by kpodemski** [comment]
Thank you @jf-viguier @PululuK and @khouloudbelguith 👍
