### PR TITLE
Reset quantity value to min value after adding to cart

### LINKED ISSUE #9743: [BOOM-4776] Problem display of discount in product page after click on Continue shopping
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4776).

- _**Reporter:**_ khouloud.belguith
- _**Created at:**_ Thu, 8 Feb 2018 18:17:36 +0100

<p>Hi,</p>

<p>There is a bug in the discount display and the price on the Product page, after adding the product to cart, when this discount is set in the CATALOG PRICE RULES.<br/>
In my case, the product is set for a unit discount of 18%, and for more than 48 units, the discount goes to 25%.<br/>
As you can see on the video record, the discount for 48 units remains at 18% ( and the price is 26,56€ instead of 24.29€) in the Product page after adding this product to the cart unless the quantity is not updated in the input text.</p>

<p>Best regards, Khouloud</p>
        
* How to reproduce the issue ?

1-Create the first catalog price rules with a discount 18% from 1 quantity
<br/>
2-Create the second catalog price rules with a discount 25% from 48 quantity
<br/>
3-Check the product page in FO
<br/>
4-Put more than 48 in the quantity
<br/>
5-Add the product to the cart
<br/>
6-Click on CONTINUE SHOPPING
<br/>
7-The quantity is not updated in the input text, it is still 48 but the price and the discount are not correct: the discount should be 25 % and with the correct price

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Reset quantity value to min value after adding to cart
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9743
| How to test?  | Add a product to your cart after changing the quantity, preferably one which has a min quantity superior to 1, and at the best with some discount depending on the quantity. After the product is added to the cart the quantity field is automatically updated to "min value" and the promotion is no longer visible.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11661)

### CODE REVIEW

File: themes/_core/js/product.js [hunk 1]
```diff
@@ -324,4 +324,14 @@ $(document).ready(() => {
             args.product_url
         );
     });
+
+    prestashop.on('updateCart', (event) => {
+        if (!event || !event.reason || event.reason.linkAction != 'add-to-cart' ) {
```
Comment (mickaelandrieu) [inline themes/_core/js/product.js]:
```diff
- != 'add-to-cart'
+ !== 'add-to-cart'
```

**Review by mickaelandrieu — CHANGES_REQUESTED** [review]

File: themes/_core/js/product.js (hunk 1 above)
Comment (jolelievre) [reply themes/_core/js/product.js]: Thanks, done!

File: themes/_core/js/product.js [hunk 2]
```diff
@@ -324,4 +324,14 @@ $(document).ready(() => {
...
+          return;
+        }
+        const $productActions = $('.product-actions');
+        const $quantityWantedInput = $productActions.find('#quantity_wanted:first');
```
Comment (PierreRambaud) [inline themes/_core/js/product.js]: `#quantity_wanted:first` it's an idea, you don't need to add `:first` and select it from `.product-actions`, you need to fix the duplicate id :/

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Wrong selectors

File: themes/_core/js/product.js (hunk 2 above)
Comment (jolelievre) [reply themes/_core/js/product.js]: I actually simply copied the existing code, but indeed the `:first` is useless since there is only one element with this id. I corrected it in other places as well.

**Review by PierreRambaud — DISMISSED** [review]
:heart:

**Comment by marionf** [comment]
@jolelievre I see changes requested but the issue is in to be tested column, is it ready for QA or you need to make changes ?

**Comment by jolelievre** [comment]
Yes, changes have been merged in the meantime. I think it's safer if I rebase it before testing.

**Review by mickaelandrieu — APPROVED** [review]
