### PR TITLE
Return integer instead of bool into checkModulesNames()

### LINKED ISSUE #27086: [BO] An unknown error in Stats page at Debug mode
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I want to open Stats page, an error will be displayed in debug mode.

Screenshot from 2021-12-24 13-30-21
 

### Expected behavior

_No response_

### Steps to reproduce

1. Enable debug mode
2. Go to BO > Stats

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When you visits the stats tab, you have an error due to the use of uasort with a method that return a bool. As it's deprecated into newer PHP version, it show an error.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #27086.
| How to test?      | Visit the Stats tab, see that you have an error and the listing of menus displayed in ascendant order. Use this PR and see that you still have the right order but without the error.
| Possible impacts? | n/d.

# BC Break

`AdminStatsTabController::checkModulesNames` now returns an int instead of a boolean

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27091)

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Someone could tell me why the CS fixer failed ? It's because the : int use ?

File: controllers/admin/AdminStatsTabController.php [hunk 1]
```diff
@@ -167,9 +167,12 @@ public function displayMenu()
         return $tpl->fetch();
     }
 
-    public function checkModulesNames($a, $b)
+    public function checkModulesNames($a, $b): int
     {
-        return (bool) ($a['displayName'] > $b['displayName']);
+        if ($a['displayName'] == $b['displayName']) {
```
Comment (sowbiba) [inline controllers/admin/AdminStatsTabController.php]: Not the purpose of this PR but I can see only one usage of this method, it's in this controller itself. It should be private

Why don't you we use `strcasecmp` https://www.php.net/manual/en/function.strcasecmp.php

If it's only for sorting, it'll be enough and the `checkModulesNames` method can be deleted

`uasort($modules, 'strcasecmp');`

**Comment by PierreRambaud** [comment]
> Someone could tell me why the CS fixer failed ? It's because the : int use ?

Everything will be shown if you click on the "Details" link:
image

**Comment by PrestaEdit** [comment]
Of course, I've check but don't see why or understand (or maybe I don't check the good things on the details, if you could point me the real point, it will be usefull here :D)

**Comment by PierreRambaud** [comment]
> Of course, I've check but don't see why or understand (or maybe I don't check the good things on the details, if you could point me the real point, it will be usefull here :D)

https://github.com/PrestaShop/PrestaShop/runs/4627036966?check_suite_focus=true#step:9:11
This is where you have to edit your code, I recommend you to run php-cs-fixer on your computer.

File: controllers/admin/AdminStatsTabController.php (hunk 1 above)
Comment (PrestaEdit) [reply controllers/admin/AdminStatsTabController.php]: `strcasecmp(): Argument #1 ($string1) must be of type string, array given`

File: controllers/admin/AdminStatsTabController.php [hunk 2]
```diff
@@ -167,9 +167,12 @@ public function displayMenu()
...
+            return 0;
+        }
+        return ($a['displayName'] < $b['displayName']) ? -1 : 1;
```
Comment (PierreRambaud) [inline controllers/admin/AdminStatsTabController.php]:
```suggestion
        return strcasecmp($a['displayName'], $b['displayName']);
```

Should be enough

File: controllers/admin/AdminStatsTabController.php (hunk 1 above)
Comment (PierreRambaud) [reply controllers/admin/AdminStatsTabController.php]: You can't do `uasort($modules, 'strcasecmp');` as `$modules` is an array of array, it works only when the content of the array is a string.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Please fix cs fixer and maybe use strcasecmp instead

**Review by PierreRambaud — APPROVED** [review]
I also document the BC break for you

**Review by kpodemski — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PrestaEdit,

It is ok :heavy_check_mark: 
I checked with PHP7.3 => ok
I checked with PHP7.2 => ok
I checked with PHP8.0 => ok
https://watch.screencastify.com/v/j2Xw2zDzHw6AAmYCwhDX

Thanks!

**Review by sowbiba — APPROVED** [review]
