### PR TITLE
Respect configuration of product summary max length

### LINKED ISSUE #28363: Products page V2 - Summary description characters limit does not work
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27892#pullrequestreview-951989134

The characters limit number does not work on products page V2 in summary description.

In Products page V1, limit is 20.
Also tested in 178X branch for this page and it's ok

Capture d’écran 2022-04-28 à 11 48 11

In Products page V2, limit is 800, the default characters limit

characters-limit-summary-pp-v2

Set the summary to more than 20 characters and save

characters-limit-summary-pp-v2-saved

### Expected behavior

See the old page Product V1:

image

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings page
2. Change the Max size of short description to 20 > save
3. Go to Catalog > Products V2 > Edit a product
4. See error > in the summary section, the max size is not updated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2.21

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | refer #28363
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Closes #28363
| Related PRs       | 
| How to test?      | refer to #28363
| Possible impacts? |

### CODE REVIEW

**Comment by zuk3975** [comment]
Found another related issue.
This summary field has html tags hidden, so tinyMCE lenght counter shows different values than symfony length validator is validating. (see screenshots - allowed chars 4, entered 4, but still error, because behidn the scenes there are <p> tags around the text which are also considered by default Length validator)

Screenshot from 2022-09-01 17-51-17
Screenshot from 2022-09-01 17-53-31


So for that to work I should probably implement custom Length validator to strip the html tags before checking length (cosidering that we don't care about database length because the field is TEXT with a limit of 65.5k symbols)

**EDIT** - fixed using already existing TinyMceLength constraint

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php [hunk 1]
```diff
@@ -93,18 +105,18 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
                 'options' => [
-                    'limit' => ProductSettings::MAX_DESCRIPTION_SHORT_LENGTH,
+                    'limit' => $shortDescriptionLimit,
                     'attr' => [
                         'class' => 'serp-default-description',
                     ],
                     'constraints' => [
                         new Length([
-                            'max' => ProductSettings::MAX_DESCRIPTION_SHORT_LENGTH,
+                            'max' => $shortDescriptionLimit,
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php]: You should use `TinyMceMaxLength` instead of `Length` here, this should fix the bug you mentioned in your comment (and for description field as well)

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php]: Actually I'm not even sure the Length constraint is required since `FormattedTextareaType` seems to automatically add the `TinyMceMaxLength` as long as `limit` is correctly set (to be tested)

Comment (zuk3975) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php]: aha, it didn't work. I fixed it with recent commits using the normalizer in options resolver to set default "constraints" value. Feedback appreciated

Comment (zuk3975) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Description/DescriptionType.php]: also constraint was setin view->vars. It didn't seemed to be used, im not sure if I didn't miss anything, but I removed that part.

**Review by Julievrz — APPROVED** [review]
Wording ✔️

**Review by jolelievre — APPROVED** [review]
Seems perfect!

Thanks @zuk3975

**Review by yanmakouf — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @zuk3975 ,

Tested on develop. PHP 7.4.

Tested with product page V2 with multiple languages.
Description length superior to, inferior to, equal to 800.
Error message is correct, no more Exception is displayed.
Screenshot 2022-09-26 at 15 08 18

It is QA ✅ 
Thanks!
