### PR TITLE
Cart: replace this->getAssociatedLanguage()->getId() by equivalent th…

### LINKED ISSUE #26787: Unefficient retreival of $this->id_lang in class Cart
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I discovered this bug in Profiling mode, see screenshot :

The class *Cart* instantiates 40x an object model *Language*, always the current language. Not only one time would suffice, but looking at the code, each time it is the code `$this->getAssociatedLanguage()->getId()` that is implicated.
`ObjectModel::getAssociatedLanguage` loads the Language object model referenced in `$this->id_lang` (see https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ObjectModel.php#L379), but we only use the id of that model.

The bug consist of using `$this->getAssociatedLanguage()->getId()` instead of the straight forward `$this->id_lang`.

### Expected behavior

I expect that when an object property is directly accessible, like `$this->id_lang`, we use it, instead of going for a convoluted, ressource intensive solution.

### Steps to reproduce

1. Enable Profiling mode
2. Display a FO page while having an article in the cart
3. Scroll down to Profiling section *ObjectModel instances*
4. Notice the number of times a language object model is instantiated (43x in my case, of which 40x in `classes/Cart.php`)

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
…is->id_lang

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Inefficient access of $this->id_lang. using inefficient $this->getAssociatedLanguage()->getId() instead of straight forward member access.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26787.
| How to test?      | In Profiling mode, compare number of instances of ObjectModel Language (edit by @jolelievre make sure this doesn't impact the initial fox for https://github.com/PrestaShop/PrestaShop/issues/22611 but it's already covered by a Behat test so it should be fine)
| Possible impacts? | There is no impact possible. The method getAssociatedLanguage() uses default language, when $this->id_lang is not a valid language. But this test is already performed in the constructor [getAssociatedLanguage()](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Cart.php#L203)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26788)

### CODE REVIEW

**Comment by lmeyer1** [comment]
@jolelievre recommends over at slack to test if $this->id_lang is a valid language in the constructor of Cart. That's the point of the next commit.

**Review by jolelievre — COMMENTED** [review]
The modification is legitimate

I would suggest going a bit further and optimizing the `getAssociatedLanguage` function so that it stores the language in a protected field to avoid creating multiple instances

@atomiix I believe you were the one who introduced this function, I remember we discussed about this solution Id' like your opinion as well on this modification please

**Comment by lmeyer1** [comment]
@jolelievre 
> I would suggest going a bit further and optimizing the getAssociatedLanguage function so that it stores the language in a protected field to avoid creating multiple instances

I let you do that. For me it is much more appropriate to remove those useless function calls, rather that fix the function. Checking the language on `__construct` is enough.

**Comment by jolelievre** [comment]
@lmeyer1 at first I though that we could remove the function as well But then I looked ai its usage and there are lots of places in the code that use it and expect a `Language` object returned not just the ID, so it's still useful I think

**Comment by lmeyer1** [comment]
@jolelievre
Thinking about it:
- Changing ObjectModel::getAssociatedLanguange would affect all object models
- Let’s consider a Language as immutable
- There are only few languages in an installation, often only one.
- Each object model should have a property that points to Language instance. For the current language it would be the same as Context::getContext()->language. For the other languages a cached Language instance.

If we could not consider a Language instance as immutable, we have to manage that on update in the object model.

**Review by matks — DISMISSED** [review]
Current changes are OK for me 👍

**Comment by atomiix** [comment]
The problem by doing so is that if you then save the cart, you'll lose the information of the language the order was made with. I think that we should keep this info while being able to display the order in another language in case the original one has been deleted.

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Approved it too fast, I think @atomiix is right, we should investigate a little bit more

**Comment by lmeyer1** [comment]
> The problem by doing so is that if you then save the cart, you'll lose the information of the language the order was made with. I think that we should keep this info while being able to display the order in another language in case the original one has been deleted.

The function `getAssociatedLanguage()` returns the language defined by `self::$id_lang` unless `self::$id_lang` is not a referencing a valid language, in which case it returns the default language.
If the cart is created with a specific `$id_lang`, that `$id_lang` will never be changed in https://github.com/PrestaShop/PrestaShop/pull/26788/files#diff-a1349548e1b4f0f9e9bda744305bba472b6cb9d887572fa1bcb9498f401e5fb7R205.

The only case I could imagine that the language changes is: the cart was created in a language, that was subsequently uninstalled from the environment. In such an exceptional case, it would not make any sense to keep the cart bound to that inexistent language.

@atomiix, @PierreRambaud, did I overlook something? If so could you explain how it could be possible to loose the information of the language the order was made from?

**Review by kpodemski — CHANGES_REQUESTED** [review]
I'm blocking this PR so we can investigate this further.

**Review by MeKeyCool — DISMISSED** [review]
> The problem by doing so is that if you then save the cart, you'll lose the information of the language the order was made with. I think that we should keep this info while being able to display the order in another language in case the original one has been deleted.

I am not sure I understand well :thinking: 

@atomiix, do you mean that we have two different languages ? One associated to Cart (given by `$this->getAssociatedLanguage()`) and another given by constructor (`$idLang`) ?

In `ObjectModelCore` abstract class, I found that code :
```php
    /**
     * Returns the language related to the object or the default one if it doesn't exists
     *
     * @return Language
     *
     * @throws PrestaShopDatabaseException
     * @throws PrestaShopException
     */
    public function getAssociatedLanguage(): Language
    {
        $language = new Language($this->id_lang);
        if (null === $language->id) {
            $language = new Language((int) Configuration::get('PS_LANG_DEFAULT'));
        }

        return $language;
    }
```

Then it looks that `$id_lang` is overriden in `CartCore` class and take the value given by constructor.

IMO, the refacto proposed by @lmeyer1 is consistent but maybe @atomiix you know a specific bug about orders language that already exists ? Could you link or create the corresponding issue ? If we need to dissociate Cart language and its constructor's one, maybe we could create another attribute to avoid multiple db calls ?

**Comment by lmeyer1** [comment]
@atomiix @kpodemski
Hello, I agree with @MeKeyCool, in my opinion, there is no reason the current language could be different from the cart language.
I'd really like that either:
- you describe a scenario where there is actually a problem with my PR because of this assumption about language ids
- or you unblock this PR, so that we can advance with the work.

Thank you

**Comment by atomiix** [comment]
@lmeyer1 @MeKeyCool 
>The only case I could imagine that the language changes is: the cart was created in a language, that was subsequently uninstalled from the environment. In such an exceptional case, it would not make any sense to keep the cart bound to that inexistent language.

This is exactly what I was thinking of, but I'm not sure it does not make sense to keep the cart bound to that inexistent language.
There's maybe something to at least use a static cache to retrieve the associated language without using the DB every time.

**Comment by lmeyer1** [comment]
@atomiix 
> but I'm not sure it does not make sense to keep the cart bound to that inexistent language

Can you please elaborate? What is the language of the cart used for anyway? **If on a bilingual shop, I add an article to my cart in language 1, then I switch to language 2, what will be the effect of having a cart in language 1 displayed on a shop in language 2?** I didn't test, but it seems logical to me, that the cart's language will adapt to the language of the shop.

It would not even make sense to keep the cart in language 1, if the customer changed language to language 2. Even less, if in the meantime language 1 does no longer exist.

**Comment by atomiix** [comment]
@lmeyer1 I see your point and it make sense actually when the cart is "in use", but once the order has been made, the cart still exists and the language has no reason to change IMO.

**Comment by lmeyer1** [comment]
@atomiix I understand your use case. I adapted my code to account for it.
@kpodemski Please review, and release the blocking if it's OK.

**Review by kpodemski — DISMISSED** [review]
@lmeyer1 

It makes sense, but could you please indicate how QA can really test your changes? it's not only about number of queries but also about certain behavior underneath

**Comment by lmeyer1** [comment]
@kpodemski 
To test I really only can imagine what is written above
> In Profiling mode, compare number of instances of ObjectModel Language

IMHO, there cannot be any change in behavior now, after that I have adapted according to the request of @atomiix .

**Comment by kpodemski** [comment]
Hi @lmeyer1 

If I recall correctly, this fix with `getAssociatedLanguge` was related to deleting the language for the previously created cart. You're placing an order in Deutsh and then deleting the language.

File: classes/Cart.php [hunk 1]
```diff
@@ -61,6 +61,12 @@ class CartCore extends ObjectModel
     /** @var int Language ID */
     public $id_lang;
 
+    /** @var int Language ID
+     * This is the same as $id_lang except in the following case:
+     * If $id_lang is invalid (e.g. due to a removed language) $id_lang_associated is the default language
+     */
+    protected $id_lang_associated;
```
Comment (jolelievre) [inline classes/Cart.php]: This should be handled in ObjectModel this way all the classes will profit from the improvement

File: classes/Cart.php [hunk 2]
```diff
@@ -202,6 +208,7 @@ public function __construct($id = null, $idLang = null)
         if (null !== $idLang) {
             $this->id_lang = (int) (Language::getLanguage($idLang) !== false) ? $idLang : Configuration::get('PS_LANG_DEFAULT');
         }
+        $this->id_lang_associated = $this->getAssociatedLanguage()->getId();
```
Comment (jolelievre) [inline classes/Cart.php]: This shouldn't be done in the constructor, but instead in the `getAssociatedLanguage` function itself, this way you only request the Language when it's needed. So instead of storing the `id_lang_associated` you should have an `$associated_language` field to store the object itself

Also as most cache strategies this could result in unexpected bugs, so we need a way to clear this cache or at least a parameter to force refreshing it So I suggest adding a `$forcerefresh` optional boolean parameter in the `getAssociatedLanguage(bool $forceRefresh = false)` function

**Review by jolelievre — CHANGES_REQUESTED** [review]
Hi @lmeyer1 

it's a good thing to optimize this method indeed, but it can be done in a more generic way I think.
Also, I'd like @atomiix opinion on this one, do you think it can result in unexpected bugs if we keep this data in cache during the process time? Although it's only cached on the instance level so maybe it's fine.

File: classes/Cart.php (hunk 2 above)
Comment (lmeyer1) [reply classes/Cart.php]: @jolelievre 
> Also as most cache strategies this could result in unexpected bugs

Can you really imagine when this could give a bug ? There is no way to change the language of a cart anyway (or where and when would this be done?

**Comment by lmeyer1** [comment]
@jolelievre 
> it's a good thing to optimize this method indeed, but it can be done in a more generic way I think.

What do you mean? If it is about optimizing the whole cart thing, I don't think it is a option for me. When you think about just the language property, can you tell me what exactly you think about ?

File: classes/Cart.php (hunk 2 above)
Comment (lmeyer1) [reply classes/Cart.php]: I really get exasperated about this review. It's now more than half a year and this PR (major for optimization and minor in extent) is still not getting merged, all because of a hypothetical use case, where a cart would continue to exist in a language that was uninstalled from Prestashop.
😭 😠

Comment (kpodemski) [reply classes/Cart.php]: @lmeyer1 but `getAssociatedLanguage` was introduced exactly to prevent errors after deleting a language, it's not a hypothetical use case, it was reported before :)

Comment (lmeyer1) [reply classes/Cart.php]: @kpodemski @atomiix Do you have the link to the issue? This might be a starting point to a reliable test procedure.

Comment (jolelievre) [reply classes/Cart.php]: Hi @lmeyer1 this is the original PR that introduced this method https://github.com/PrestaShop/PrestaShop/pull/22677

As @kpodemski this was not made just for fun but to fix an actual bug, you can get frustrated I understand but it doesn't mean we'll approve this faster ^^

Also when I meant it can be done more generic I meant that instead of modifying the Cart class you can handle your optimization in ObjectModel where the function is implemented instead (you'll see more details in my previous comments), so it's just about this language method but in the parent class.

Also, we try to anticipate the unexpected side effects, but as you said it should be fine as long as we are in the same process where there are few chances that the language is deleted in the meantime. I also thought this could impact the behat test that ensures this use case because they are all executed in the same process, but it seems to be fine, probably because each action (CQRS commands/queries) actually instantiates another Cart instance. As long as the tests are green it seems to be fine.

Comment (lmeyer1) [reply classes/Cart.php]: @jolelievre Thanks for your explanations.

> you can get frustrated I understand but it doesn't mean we'll approve this faster ^^

At least I understand now what that pickyness is all about...

File: classes/Cart.php (hunk 1 above)
Comment (atomiix) [reply classes/Cart.php]: I had a pending review that said exactly that 😅

**Review by atomiix — COMMENTED** [review]
@jolelievre I think it's okay to have this instance cache 👍
@lmeyer1 I think that what @jolelievre said is that you can implement this caching system directly in the `getAssociatedLanguage()` method so every objectModel using this method can benefit from it

**Comment by lmeyer1** [comment]
@jolelievre @atomiix
I think I understood your comments, and changed everything accordingly. Please have a look.

File: classes/ObjectModel.php [hunk 3]
```diff
@@ -59,6 +59,12 @@ abstract class ObjectModelCore implements \PrestaShop\PrestaShop\Core\Foundation
     /** @var int|null Language ID */
     protected $id_lang = null;
 
+    /** @var int Language ID
+     * This is the same as $id_lang except in the following case:
+     * If $id_lang is invalid (e.g. due to a removed language) $id_lang_associated is the default language
+     */
+    protected $id_lang_associated;
```
Comment (MeKeyCool) [inline classes/ObjectModel.php]: It looks like this attribute isn't use anywhere.

File: classes/ObjectModel.php [hunk 4]
```diff
@@ -385,6 +391,10 @@ public function getFieldsLang()
      */
     public function getAssociatedLanguage(): Language
     {
+        static $language = null;
```
Comment (MeKeyCool) [inline classes/ObjectModel.php]: I am not convinced by this static usage, from what I understood, shouldn't you use some Cache and/or lazy loading system ?

**Review by MeKeyCool — CHANGES_REQUESTED** [review]
Maybe I missed something or you got mixed up with commits but I don't think the final code change is satisfying.

Won't a simple lazy loading system would be enough for this case ?

File: classes/ObjectModel.php (hunk 4 above)
Comment (lmeyer1) [reply classes/ObjectModel.php]: You're right. The unused attribute was intended for this.

File: classes/ObjectModel.php [hunk 5]
```diff
@@ -385,12 +391,15 @@ public function getFieldsLang()
      */
     public function getAssociatedLanguage(): Language
     {
-        $language = new Language($this->id_lang);
-        if (null === $language->id) {
-            $language = new Language((int) Configuration::get('PS_LANG_DEFAULT'));
+        if (!is_null($this->lang_associated)) {
```
Comment (MeKeyCool) [inline classes/ObjectModel.php]: I would prefer `if ($this->lang_associated instanceof Language)` test :yum:

**Review by MeKeyCool — DISMISSED** [review]
One non blocking comment ^^

Good job ( we see the end of the tunnel :smile: )

**Review by jolelievre — DISMISSED** [review]
Thanks @lmeyer1

File: classes/ObjectModel.php (hunk 5 above)
Comment (atomiix) [inline classes/ObjectModel.php]: Just to be peaky 😅:
```suggestion
        if (null !== $this->lang_associated) {
```

Comment (lmeyer1) [reply classes/ObjectModel.php]: @atomiix Yoda style or another reason?

Comment (atomiix) [reply classes/ObjectModel.php]: using `===` instead of the function `is_null()`. Mainly because that's what you also did just after so it's coherent (but it's also a micro optimization as using `is_null()` is slightly slower).

Comment (lmeyer1) [reply classes/ObjectModel.php]: @atomiix Done.

Comment (lmeyer1) [reply classes/ObjectModel.php]: I followed @atomiix's advice

**Review by MeKeyCool — APPROVED** [review]
Thanks for your contribution ^^

File: classes/ObjectModel.php [hunk 6]
```diff
@@ -385,12 +391,15 @@ public function getFieldsLang()
...
     public function getAssociatedLanguage(): Language
     {
-        $language = new Language($this->id_lang);
-        if (null === $language->id) {
-            $language = new Language((int) Configuration::get('PS_LANG_DEFAULT'));
+        if (null !== $this->lang_associated) {
+            return $this->lang_associated;
+        }
+        $this->lang_associated = new Language($this->id_lang);
+        if (null === $this->lang_associated->id) {
```
Comment (jolelievre) [inline classes/ObjectModel.php:398]:
```suggestion
        if (!Validate::isLoadedObject($this->lang_associated)) {
```

Comment (jolelievre) [reply classes/ObjectModel.php:398]: Just a suggestion as I often see this kind of code to check an object is correctly loaded, but not a mandatory modif 😉

**Review by jolelievre — APPROVED** [review]
Thanks @lmeyer1 

Just a suggestion but the PR is already legit to me

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your PR :rocket: LGTM, QA :heavy_check_mark: 
The Cart is empty or not, the number of times a language object model is instantiated is always 4 :clap: 

image

Thanks!

**Review by hibatallahAouadni — APPROVED** [review]
Hello @lmeyer1 

Thanks for your PR :rocket: LGTM, QA :heavy_check_mark: 
The Cart is empty or not, the number of times a language object model is instantiated is always 4 :clap: 

image

Thanks!

**Comment by jolelievre** [comment]
Thanks @lmeyer1 and @hibatallahAouadni
