### PR TITLE
BO : Add Product on Order : Use previous cart rather than creating a new one

### LINKED ISSUE #13880: Bug in displayed discount when adding product (linked to a coupon) to an existing order from BO
**Describe the bug**

**To Reproduce**

1. Create a coupon rule with: empty code + product restriction + discount amount
1. try to add this product above (linked to the coupon) to any existing order
1. you will see that the discount is duplicated
1. also if you delete the discount from the order, the discount displayed ins incorrect

**Screenshots**
1!UNITO-UNDERSCORE!part1
1!UNITO-UNDERSCORE!part2
1!UNITO-UNDERSCORE!part3
2!UNITO-UNDERSCORE!part1
2!UNITO-UNDERSCORE!part2

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When you add a product (which add a discount), the discount block is not added
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Partially fix #13880
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/13880#issuecomment-595189713 from @khouloudbelguith

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18205)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
..

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 1]
```diff
@@ -131,12 +131,12 @@ public function handle(AddProductToOrderCommand $command)
...
         // @todo: use https://github.com/PrestaShop/decimal for prices computations
-        $order->total_products += (float) $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS);
-        $order->total_products_wt += (float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
+        $order->total_products = (float) $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS);
+        $order->total_products_wt = (float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
 
-        $order->total_paid += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
-        $order->total_paid_tax_excl += Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $order->total_paid_tax_incl += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+        $order->total_paid = Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
```
Comment (matthieu-rolland) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]:
```suggestion
        $order->total_paid = Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), Cart::ONLY_DISCOUNTS);
```

And same for other hardcoded 2 values ;)

**Review by matthieu-rolland — CHANGES_REQUESTED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: @matthieu-rolland The 2 value is for the `Tools::ps_round`, not the `$cart->getOrderTotal`

Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: ah damn, I badly read, my mistake .... in this case we need to use the proper computing precision:


```
        $computingPrecision = new ComputingPrecision();
        $precision = $computingPrecision->getPrecision($currency->precision);
```
Then replace 2 with $precision ...  (we're supposed to get rid of hardcoded precision everywhere)

Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: But I'm not blocking the PR for this since you didn't introduce this, I can do it in another PR 👍

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: @matthieu-rolland I do the move now ;)

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 2]
```diff
@@ -131,12 +131,21 @@ public function handle(AddProductToOrderCommand $command)
...
-        $order->total_products_wt += (float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
+        $order->total_products = (float) $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS);
+        $order->total_products_wt = (float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
 
-        $order->total_paid += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
-        $order->total_paid_tax_excl += Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $order->total_paid_tax_incl += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+        $order->total_paid = Tools::ps_round(
+            (float) $cart->getOrderTotal(true, $totalMethod),
+            $this->context->getComputingPrecision()
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: I don't think you should use the precision rom context It will use the context's currency which might be different from the order one Rather use a dedicated ComputingPrecision object along with the precision o the currency in the order

**Review by jolelievre — CHANGES_REQUESTED** [review]
In the same spirit as the comment I let, we shouldn't rely on context values What you changed or the cart is even more true!
In this handler we use cart rules from the cart present in the context, shouldn't we use the cart associated to the order like you did to get the real total?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 2 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Thanks. I applied your review ;) (Thanks a lot dude ;))

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 3]
```diff
@@ -505,15 +529,16 @@ private function createNewInvoice(Order $order, Cart $cart, $isFreeShipping)
      */
     private function updateExistingInvoice($orderInvoiceId, Cart $cart)
     {
+        $precision = $this->getPrecisionFromCart($cart);
         $invoice = new OrderInvoice($orderInvoiceId);
 
         $invoice->total_paid_tax_excl += Tools::ps_round(
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:635]: Something feels off For the order you replaced the `+=` part with a simple `=` I guess it's because previously the cart only contained the new product but now it contains all o them
So it should be the same thing when you update the invoice right?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 4]
```diff
@@ -462,8 +479,15 @@ private function createNewInvoice(Order $order, Cart $cart, $isFreeShipping)
         $taxCalculator = $carrier->getTaxCalculator($invoice_address);
 
         // @todo: use https://github.com/PrestaShop/decimal to compute prices and taxes
-        $invoice->total_paid_tax_excl = Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $invoice->total_paid_tax_incl = Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+        $precision = $this->getPrecisionFromCart($cart);
+        $invoice->total_paid_tax_excl = Tools::ps_round(
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:591]: Same here i you create a new invoice with a cart containing ALL the products the total won't be correct

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 3 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:635]: Correct. I fixed it.

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 4 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:591]: Changed the behavior.

File: classes/order/OrderDetail.php [hunk 5]
```diff
@@ -755,7 +755,7 @@ public function createList(Order $order, Cart $cart, $id_order_state, $product_l
 
         unset(
             $this->vat_address,
-            $products, $this->customer
```
Comment (matks) [inline classes/order/OrderDetail.php:758]: I see that `OrderDetail::createList()` is used in PaymentModule.
Modifying its unspecified behavior is highly dangerous.
May I suggest some other ideas ?
- create a new function instead of using/modifying `createList()`
- add a flag (yes I know 😱) to modify this one

I am very scared of this change

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 6]
```diff
@@ -117,40 +119,60 @@ public function handle(AddProductToOrderCommand $command)
...
-        $order->total_products_wt += (float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
-
-        $order->total_paid += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
-        $order->total_paid_tax_excl += Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $order->total_paid_tax_incl += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+        $orderProducts = $order->getCartProducts();
+        $order->total_products = (float) $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS, $orderProducts);
+        $order->total_products_wt = (float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS, $orderProducts);
+
+        $precision = $this->getPrecisionFromCart($cart);
```
Comment (matks) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Suggestion, but not mandatory: use Decimal instead of `ps_round()`

File: classes/order/OrderDetail.php (hunk 5 above)
Comment (Progi1984) [reply classes/order/OrderDetail.php:758]: Please check again... The variable isn't used in  the method and it's the alone reference. :wink:

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 7]
```diff
@@ -349,6 +396,59 @@ private function createSpecificPriceIfNeeded(
         return null;
     }
 
+    /**
+     * @param Cart $cart
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:418]: Add comment, something like: `This function extracts the newly added product from the cart and reformat the data in order to create a dedicated OrderDetail with the appropriate amounts`
And maybe rename into `getNewCartProduct` or `getNewCartProductData`

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 8]
```diff
@@ -465,8 +567,15 @@ private function createNewInvoice(Order $order, Cart $cart, $isFreeShipping)
         $taxCalculator = $carrier->getTaxCalculator($invoice_address);
 
         // @todo: use https://github.com/PrestaShop/decimal to compute prices and taxes
-        $invoice->total_paid_tax_excl = Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $invoice->total_paid_tax_incl = Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+        $precision = $this->getPrecisionFromCart($cart);
+        $invoice->total_paid_tax_excl = Tools::ps_round(
+            (float) $cart->getOrderTotal(false, $totalMethod),
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Be careful I think here you need to use the new products as well
The new invoice can be created after one already existed, in which case you don't want the newly created invoice to contain the total of the previous invoice

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 9]
```diff
@@ -503,23 +603,25 @@ private function createNewInvoice(Order $order, Cart $cart, $isFreeShipping)
     /**
      * @param int $orderInvoiceId
      * @param Cart $cart
+     * @param Product $product
      *
      * @return OrderInvoice
      */
-    private function updateExistingInvoice($orderInvoiceId, Cart $cart)
+    private function updateExistingInvoice($orderInvoiceId, Cart $cart, array $products)
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]:
```suggestion
    private function updateExistingInvoice($orderInvoiceId, Cart $cart, array $newProducts)
```

for better understanding

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 10]
```diff
@@ -503,23 +603,25 @@ private function createNewInvoice(Order $order, Cart $cart, $isFreeShipping)
     /**
      * @param int $orderInvoiceId
      * @param Cart $cart
+     * @param Product $product
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: this param doesn't match the new argument

**Review by jolelievre — CHANGES_REQUESTED** [review]
Some small fix left, but congrats on this fix!!

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 10 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Fixed

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 9 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Fixed

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 8 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Thanks. I check it ;)

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 7 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:418]: Fixed

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 11]
```diff
@@ -102,7 +105,7 @@ public function handle(AddProductToOrderCommand $command)
 
         $this->checkProductInStock($command->getProductId()->getValue(), $command->getCombinationId(), $command->getProductQuantity());
 
-        $cart = $this->createNewCart($order);
+        $cart = $this->createNewOrEditExistingCart($order);
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Maybe you could move this here: `$oldCartRules = $cart->getCartRules();`
Instead of L95, this would seem more logical and I think it will ease the merge with @sowbiba 's PR: https://github.com/PrestaShop/PrestaShop/pull/17927

Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: :+1:

File: classes/order/OrderDetail.php (hunk 5 above)
Comment (matks) [reply classes/order/OrderDetail.php:758]: You're right, I was confused by this stupid code 😓

**Review by matks — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 12]
```diff
@@ -199,22 +216,33 @@ public function handle(AddProductToOrderCommand $command)
...
+            (float) $cart->getOrderTotal(true, $totalMethod, $orderProducts),
+            $precision
+        );
+        $order->total_discounts = (float) abs($cart->getOrderTotal(true, Cart::ONLY_DISCOUNTS, $orderProducts));
+        $order->total_discounts_tax_excl = (float) abs($cart->getOrderTotal(false, Cart::ONLY_DISCOUNTS, $orderProducts));
+        $order->total_discounts_tax_incl = (float) abs($cart->getOrderTotal(true, Cart::ONLY_DISCOUNTS, $orderProducts));
+
         $order->update();
+
+        $this->contextStateManager->restoreContext();
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:250]: Consider restore the context if there is an exception between the moment it has been modified and the moment it is restored

try {} catch{ restore context }

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 13]
```diff
@@ -114,46 +124,52 @@ public function handle(AddProductToOrderCommand $command)
 
         $this->addProductToCart($cart, $product, $combination, $command->getProductQuantity());
 
+        // Fetch Cart Product
+        $productCart = $this->getCartProductData($cart, $product, $command->getProductQuantity());
+
         $invoice = $this->createNewOrEditExistingInvoice(
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: I maybe dont get it. We have 1 invoice per product ?

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 14]
```diff
@@ -523,21 +581,39 @@ public function duplicateOrder($orderReference, $duplicatedCartReference)
...
+            }
         }
 
-        throw new RuntimeException(sprintf('Order was expected to have "%d" products "%s" in it. Instead got "%s"', $quantity, $productName, $productQuantities['quantity']));
+        if ($productQuantity == $quantity) {
+            return;
+        }
+        throw new RuntimeException(
+            sprintf(
+                'Order was expected to have "%d" products "%s" in it. Instead got "%s"',
```
Comment (sowbiba) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: [Minor] we can use %d for the last placeholder

Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Fixed

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 12 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:250]: Done

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 13 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: No it's depending of the input ;)

**Review by sowbiba — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 15]
```diff
@@ -89,132 +99,155 @@ public function handle(AddProductToOrderCommand $command)
...
+            ->setCurrency(new Currency($order->id_currency))
+            ->setCustomer(new Customer($order->id_customer));
 
-        $product = $this->getProductObject($command->getProductId(), (int) $order->id_lang);
-        $combination = $this->getCombination($command->getCombinationId());
+        try {
+            $this->assertOrderWasNotShipped($order);
 
-        $this->checkProductInStock($command->getProductId()->getValue(), $command->getCombinationId(), $command->getProductQuantity());
+            $oldCartRules = (new Cart($order->id_cart))->getCartRules();
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Only a suggestion if you feel like it, this could be done right after the call to `createNewOrEditExistingCart` L116:
`$oldCartRules = $cart->getCartRules();`

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 16]
```diff
@@ -89,132 +99,155 @@ public function handle(AddProductToOrderCommand $command)
...
+            }
 
-        $order = $order->refreshShippingCost();
+            $order = $order->refreshShippingCost();
 
-        Hook::exec('actionOrderEdited', ['order' => $order]);
+            Hook::exec('actionOrderEdited', ['order' => $order]);
 
-        $newCartRules = $this->context->cart->getCartRules();
+            $newCartRules = $this->context->cart->getCartRules();
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Seems like `$this->context->cart = $cart;` (L327)
So actually `$this->context->cart === $cart` So maybe we could remove all direct references to `$this->context` ?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 17]
```diff
@@ -89,132 +99,155 @@ public function handle(AddProductToOrderCommand $command)
...
-        if ($this->context->cart !== null) {
-            $oldCartRules = $this->context->cart->getCartRules();
-        } else {
-            $oldCartRules = [];
-        }
-
-        $this->assertOrderWasNotShipped($order);
+        $this->contextStateManager
+            ->setCurrency(new Currency($order->id_currency))
+            ->setCustomer(new Customer($order->id_customer));
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:104]: Thanks to this I think `$this->context->customer = new Customer($order->id_customer);` L328 is now useless

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 18]
```diff
@@ -89,132 +99,155 @@ public function handle(AddProductToOrderCommand $command)
...
 
-        Hook::exec('actionOrderEdited', ['order' => $order]);
+            Hook::exec('actionOrderEdited', ['order' => $order]);
 
-        $newCartRules = $this->context->cart->getCartRules();
+            $newCartRules = $this->context->cart->getCartRules();
 
-        sort($oldCartRules);
-        sort($newCartRules);
+            sort($oldCartRules);
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:200]: Since old and new cart rules now come from the same cart instance, `$newCartRules` are only the ones added from the product, maybe this could be fetched more easily

**Review by matks — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 19]
```diff
@@ -503,23 +624,33 @@ private function createNewInvoice(Order $order, Cart $cart, $isFreeShipping)
...
+        );
+        $invoice->total_products += (float) $cart->getOrderTotal(
+            false,
+            Cart::ONLY_PRODUCTS,
+            $newProducts
+        );
+        $invoice->total_products_wt += (float) $cart->getOrderTotal(
+            true,
+            Cart::ONLY_PRODUCTS,
+            $newProducts
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:651]: No need to update `$invoice->total_wrapping` like in `createInvoice` here?

**Review by jolelievre — DISMISSED** [review]
Great improvement @Progi1984 

I only added some comments because we are a few lines away from getting completely rid of `$this->context`

Only thing I'm worried is the comment about wrapping in `updateExistingInvoice `

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 16 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: :+1:

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 15 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: :+1:

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 17 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:104]: :+1:

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 19 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php:651]: I don't know... but not the cas in legacy :tongue:

**Review by jolelievre — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

I have two errors with your PR : 

- I cannot delete the product which is linked to the discount : When I click on delete and confirm, nothing happens. After refresh, the product is still in the cart.
- When I try to delete the voucher, there is an error

See the errors in this screenrecord : 
https://drive.google.com/file/d/1yXPaN5rDVTXcLychf1ft3e_3RbblR3QT/view?usp=sharing

Thanks !

**Comment by Progi1984** [comment]
@Robin-Fischer-PS
> I cannot delete the product which is linked to the discount : When I click on delete and confirm, nothing happens. After refresh, the product is still in the cart.

Will be fixed in PR #18204 

> When I try to delete the voucher, there is an error

A new issue has been created : #18379

**Comment by Robin-Fischer-PS** [comment]
Alright, then it's OK for me ! :heavy_check_mark: 

Thanks @Progi1984  :)

**Comment by Progi1984** [comment]
Thanks @Robin-Fischer-PS
