### PR TITLE
Handle empty states for category grids

### LINKED ISSUE #17597: Remove search fields when listing are empty
**Describe the bug**
Remove search fields, search button, labels and bulk checkbox when listing are empty

Already migrated pages:
- [x] Catalog > categories
- [x] Catalog > monitoring
- [x] Catalog > brands
- [x] Catalog > suppliers
- [x] Catalog > files
- [x] Customers > customers
- [x] Customers > addresses
- [x] Customer service > order messages
- [x] Design > pages (categories & pages)
- [x] International > localization > Languages
- [x] International > localization > Currencies
- [x] International > taxes > taxes
- [x] Shop parameters > order settings > statuses
- [x] Shop parameters > customer settings > groups
- [x] Shop parameters > contact > contacts
- [x] Shop parameters > traffic & SEO > SEO & URLs
- [x] Advanced parameters > E-mail 
- [x] Advanced parameters > Team > Employees 
- [x] Advanced parameters > Team > Profiles 
- [x] Advanced parameters > Database > SQL manager 
- [x] Advanced parameters > Database > DB backup
- [x] Advanced parameters > Logs
- [x] Advanced parameters > Webservice

Not yet migrated pages:
- [ ] Catalog > products
- [ ] Catalog > attributes
- [ ] Catalog > features
- [ ] Catalog > cart rules
- [ ] Catalog > catalog price rules
- [ ] Customer service > customer service
- [ ] Customer service > merchandise returns
- [ ] Design > image settings
- [ ] Shipping > carriers
- [ ] International > locations > Zones
- [ ] International > locations > Countries
- [ ] International > locations > States
- [ ] International > taxes > taxes rules
- [ ] Shop parameters > customer settings > titles
- [ ] Shop parameters > contact > stores
- [ ] Shop parameters > traffic & SEO > Search engines
- [ ] Shop parameters > traffic & SEO > Referrers
- [ ] Shop parameters > Search > Search
- [ ] Shop parameters > Search > Tags
- [ ] Advanced parameters > Multistore > Admin shop group
- [ ] Advanced parameters > Multistore > Admin shop
- [ ] Advanced parameters > Multistore > Admin shop url

**Screenshots**
Pages without empty state
capture d'écran_2306

Pages with empty state
capture d'écran_2305

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When table with no data and no filter selected was displayed, the filter form was still shown. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17597
| How to test?  | With a clean install of PrestaShop (without fixtures), check all pages listed in #17597, you should not see the filter form if the table is empty.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19703)

### CODE REVIEW

File: src/Core/Grid/Presenter/GridPresenter.php [hunk 1]
```diff
@@ -40,6 +42,10 @@
  */
 final class GridPresenter implements GridPresenterInterface
 {
+    private const CATEGORY_GRID_IDS = [
```
Comment (matks) [inline src/Core/Grid/Presenter/GridPresenter.php]: Hardcoded grid IDs 🤔 it breaks the O of SOLID

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig [hunk 2]
```diff
@@ -23,7 +23,7 @@
  * International Registered Trademark & Property of PrestaShop SA
  *#}
 
-<tr class="column-filters {% if 0 == grid.data.records_total and grid.filters is empty and grid.actions.bulk|length < 0 %}d-none{% endif %}">
+<tr class="column-filters{% if grid.attributes.is_empty_state %} d-none{% endif %}">
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig:26]: This template is used by all grids, not only categories. You are modifying a global logic for only 2 usecases 😅 don't do that !

**Review by matks — CHANGES_REQUESTED** [review]
I don't think this logic is good neither the implementation 😞 sorry

See comments

**Comment by matks** [comment]
Rerunning Travis

**Comment by matks** [comment]
Warning: I tried to fix this issue once and failed. See my mistake and be careful about not doing it again => https://github.com/PrestaShop/PrestaShop/pull/19606#issuecomment-639535728

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig (hunk 2 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig:26]: @matks except for `and grid.actions.bulk|length < 0` which was also removed in the @Progi1984's [PR](https://github.com/PrestaShop/PrestaShop/pull/19606/files#diff-d3df3c524df921323ec17cedfe38888bL26) for the same reason, it's the exact same condition in twig that [the condition defining if `is_empty_state` is true or not](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Presenter/GridPresenter.php#L89) and it's already used for [tables header row](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/headers_row.html.twig#L26)

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig (hunk 2 above)
Comment (matks) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig:26]: OK I understand it better. I was initially confused by "empty state" because I thought it was about these images that appear instead of an empty listing.

So it's something different here. If I track correctly your train of thoughts, "a grid is in an empty state when 1. it has no records 2. there is no registered filter 3. this is not a search result"

The implementation seems valid however what I am wary of in this PR is that `search_request` parameter is being used in GridPresenter (= so it's used by ALL grids) but is only being used into CMS Pages grid. So we have a global parameter, a global property that can be used for all the grids (twenty ? thirty ?) into PrestaShop ... but is only being used for CMS Pages Grid. And then only CMS Pages Grid benefits from this (undocumented) feature.

It would be different if we were able to make sure that `is_search_request` filter is computed automatically, for any grid. That would be awesome then 😄 

Wdyt ?

Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig:26]: No no, your were right, it's about the placeholder images when the list is empty.

Actually, it was firstly used by the Categories page and I just reused this method but you're right, it would be better to have it automatically computed and available everywhere :)

File: src/Core/Grid/Presenter/GridPresenter.php [hunk 3]
```diff
@@ -94,6 +94,12 @@ public function present(GridInterface $grid)
             $presentedGrid['form_prefix'] = $searchCriteria->getFilterId();
         }
 
+        if (isset($searchCriteria->getFilters()['is_search_request'])
+            && false === $searchCriteria->getFilters()['is_search_request']
+            && 0 === $data->getRecordsTotal()) {
+            $presentedGrid['attributes']['is_empty_state'] = true;
+        }
```
Comment (PierreRambaud) [inline src/Core/Grid/Presenter/GridPresenter.php]:
```suggestion
        $presentedGrid['attributes']['is_empty_state'] = isset($searchCriteria->getFilters()['is_search_request'])
            && false === $searchCriteria->getFilters()['is_search_request']
            && 0 === $data->getRecordsTotal();
```
?

File: src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig (hunk 2 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/Table/filters_row.html.twig:26]: @matks I've finally managed to do it differently. Seems cleaner to me but lmk what you think 🙂

**Review by matks — COMMENTED** [review]
@atomiix So if I get it correctly, from `isEmptyState()` function implementation:

"A grid is in an empty state ?

- if there is no filter AND no records it's YES
- however, if there are filters, we look for all filters and if one of these filters matches the filters of the GridDefinition, it's a NO
- else if there are no records it's a YES
- else if there are records it's a NO"

Is that right ?

Mmmm ... 🤔 we need to make sure this covers all cases.

For example, pagination is a filter isn't it ? So if I ask for a bad page number, there are no records found however since pagination is not a filter inside grid definition, then it'll be empty ?

**Comment by atomiix** [comment]
@matks you got it right! I think I tried a lot of possibilities and that's pretty much what we get in 1.7.7 already. The only difference is the check of the grid definition filters to handle pages with default "filters" added to get the default parent category id.

For the case you're pointing out, even with a bad page number `grid->getData()->getRecordsTotal()` will be `> 0` and so `isEmptyState` will return `false`.

**Review by matks — DISMISSED** [review]
I'm OK with how this PR is now 👍 approving the request

File: src/Core/Grid/Presenter/GridPresenter.php [hunk 4]
```diff
@@ -166,4 +166,26 @@ private function getColumnFilters(GridDefinitionInterface $definition)
...
+
+        $definitionFiltersKeys = array_keys($grid->getDefinition()->getFilters()->all());
+        foreach ($filterFormData as $key => $value) {
+            if (in_array($key, $definitionFiltersKeys, true)) {
+                return false;
+            }
+        }
+
+        return 0 === $grid->getData()->getRecordsTotal();
```
Comment (Progi1984) [inline src/Core/Grid/Presenter/GridPresenter.php]:
```suggestion
        $filterFormData = $grid->getFilterForm()->getData();
        $dataRecordsTotal = $grid->getData()->getRecordsTotal();
        if (empty($filterFormData) && 0 === $dataRecordsTotal) {
            return true;
        }

        $definitionFiltersKeys = array_keys($grid->getDefinition()->getFilters()->all());
        foreach ($filterFormData as $key => $value) {
            if (in_array($key, $definitionFiltersKeys, true)) {
                return false;
            }
        }

        return 0 === $dataRecordsTotal;
```

**Review by Progi1984 — COMMENTED** [review]
A small change

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by ngodefroy** [comment]
TESTED "Remove search fields, search button, labels and bulk checkbox when listing are empty"
In following pages, I added in bold my comments

- [x]  Catalog > categories
- [x]  Catalog > monitoring
- [x]  Catalog > brands
- [x]  Catalog > suppliers
- [x]  Catalog > files
- [ ]  Customers > customers
- [ ]  Customers > addresses
- [ ]  Customer service > order messages
- [ ]  Design > pages (categories & pages)
- [ ]  International > localization > Languages ==>**get the following error: "you cannot change the status of the default language"**
- [ ]  International > localization > Currencies ==> "**an error occurred while deleting this selection: euro" (only currency there)** 
- [ ]  International > taxes > taxes
- [ ]  Shop parameters > order settings > statuses ==>**No delete button found**
- [ ]  Shop parameters > customer settings > groups ==>**No delete button found**
- [ ]  Shop parameters > contact > contacts
- [ ]  Shop parameters > traffic & SEO > SEO & URLs
- [ ]  Advanced parameters > E-mail
- [ ]  Advanced parameters > Team > Employees
- [ ]  Advanced parameters > Team > Profiles
- [ ]  Advanced parameters > Database > SQL manager
- [ ]  Advanced parameters > Database > DB backup
- [ ]  Advanced parameters > Logs
- [ ]  Advanced parameters > Webservice
- [ ] Not yet migrated pages:
- [ ] 
- [ ]  Catalog > products
- [ ]  Catalog > attributes
- [ ]  Catalog > features
- [ ]  Catalog > cart rules
- [ ]  Catalog > catalog price rules
- [ ]  Customer service > customer service
- [ ]  Customer service > merchandise returns
- [ ]  Design > image settings
- [ ]  Shipping > carriers
- [ ]  International > locations > Zones
- [ ]  International > locations > Countries
- [ ]  International > locations > States => **Got an error: Can't delete Florida, but the all the others states are OK**
- [ ]  International > taxes > taxes rules
- [ ]  Shop parameters > customer settings > titles
- [ ]  Shop parameters > contact > stores ==> **index.php?controller=AdminStores&conf=2&token=5a064959886ebbec0dc33282f5c47015:2112 Uncaught TypeError: Cannot read property 'defaults' of undefined
    at index.php?**controller=AdminStores&conf=2&token=5a064959886ebbec0dc33282f5c47015:2112 
- [ ]  Shop parameters > traffic & SEO > Search engines
- [ ]  Shop parameters > traffic & SEO > Referrers
- [ ]  Shop parameters > Search > Search ==> error in console **Uncaught TypeError: Cannot read property 'defaults' of undefined
    at index.php?controller=AdminSearchConf&conf=2&token=3bc4c2349aaf8c6384538e7d87917640:1661** (this issue seems randoms, on some pages) 
- [ ]  Shop parameters > Search > Tags
- [ ]  Advanced parameters > Multistore > Admin shop group 

- [ ]  Advanced parameters > Multistore > Admin shop
- [ ]  Advanced parameters > Multistore > Admin shop url

Thank you @atomiix 
@PrestaShop/product-team could you confirm me the places where I cannot find the delete button is correct and shouldnt be implemented ?

**Comment by marionf** [comment]
@ngodefroy 

To see the delete button you should create new order status, new order return status and new customer group

**Comment by ngodefroy** [comment]
> @ngodefroy
> 
> To see the delete button you should create new order status, new order return status and new customer group

Ok, thank you, then I can only delete the one I created and not the ones by default, is that correct? 

@atomiix, also I had an issue on this PR (could not reproduce on develop branch):
When I bulk deleted the "add new order return status" under Shop parameters > order settings > statuses, It wasnt deleted. See the video: Shop parameters > https://drive.google.com/file/d/1ypEiea4M6qAcd_ImtDDUARMl3z3i9Qyg/view

Note: The undefined found randomly were not linked to this PR.

**Comment by marionf** [comment]
> Ok, thank you, then I can only delete the one I created and not the ones by default, is that correct?

Yes, this is the wanted behavior

**Comment by Progi1984** [comment]
Ping @atomiix : @marionf has answered.

**Comment by ngodefroy** [comment]
Test OK, the issue: issue on this PR (could not reproduce on develop branch):
When I bulk deleted the "add new order return status" under Shop parameters > order settings > statuses, It wasnt deleted. was appearing bc I hadnt the last PR version: **https://drive.google.com/file/d/1fUF58tskFXbaWw8x10uyOb2kWBV2LiDB/view**

- [x] All good 

Thank you @atomiix

**Comment by atomiix** [comment]
Thanks @ngodefroy !
