### PR TITLE
Install theme before modules

### LINKED ISSUE #28242: ps_emailalerts modules are not hooked at all on fresh install
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

ps_emailalerts module is not hooked at all on the develop branch.

On 1.7.8x branch, tested with 2.3.3 version of the module and is hooked on "displayCustomerAccount", "displayMyAccountBlock", "displayProductAdditionalInfo" hooks, all is ok:

https://user-images.githubusercontent.com/2854834/162991327-2a4686cc-48b7-4fbb-a52c-ceca45904b96.mp4

In FO, on product page we have the block:

178x-product-psemailalertsOK png

Also on my account page the block is displayed:

178x-account-psemailalertsOK png

On develop branch, tested with 2.3.3 version of the module and it's not hooked at all:

https://user-images.githubusercontent.com/2854834/162992481-4565c935-60e0-46fa-8b4f-d90c4e6c241f.mp4

In FO, on product page the block is not displayed:

develop-product-psemailalertsNOK

Also on my account page, the block is not displayed:

develop-account-psemailalertsNOK png

Tested 2.3.4 version of the module on develop branch and again not hooked

### Expected behavior

ps_emailalerts module must be hooked automatically after the installation on: 

- "displayCustomerAccount" hook, 
- "displayMyAccountBlock" hook, 
- "displayProductAdditionalInfo" hook

### Steps to reproduce

1. Go to BO -> Install ps_emailalerts module
2. Click on configure button of the module
3. Click on "Manage hooks" button on top right of the screen
4. List of hook is displayed for the module but in this case the list is empty

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

ps_emailalerts v2.3.3/v.2.3.4

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When the theme is installed, it uses the `theme.yml` file to know which modules are required for the theme and to which hooks they must be attached to. Once the install process has this info, it will unhook every modules that are hooked to hooks listed in the `theme.yml` so only theme-related modules are hooked on those hooks. By installing the modules not already installed by the theme **after** the theme, this limitation goes away.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28242
| Related PRs       | 
| How to test?      | Please see #28242
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28258)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

File: install-dev/controllers/http/process.php [hunk 1]
```diff
@@ -100,11 +100,11 @@ public function process(): void
                     ->setProcessFOThemes(['classic'])
                     ->process();
                 $this->processConfigureShop();
-            } elseif (Tools::getValue('installModules') && (!empty($this->session->process_validated['configureShop']) || !$validateFixturesInstallation)) {
-                $this->processInstallModules();
-            } elseif (Tools::getValue('installTheme') && !empty($this->session->process_validated['installModules'])) {
+            } elseif (Tools::getValue('installTheme') && !empty($this->session->process_validated['configureShop'])) {
```
Comment (jolelievre) [inline install-dev/controllers/http/process.php:103]: Not sure it's necessary to invert those two, since they are independent use cases based on the request parameters their order shouldn't matter here The important is the order of the steps that you changed downer

**Review by jolelievre — DISMISSED** [review]
Thanks @atomiix 

Just one comment but it's more a suggestion, not blocking anyway

File: install-dev/controllers/http/process.php (hunk 1 above)
Comment (atomiix) [reply install-dev/controllers/http/process.php:103]: Yes it is because we check `$this->session->process_validated['configureShop']` before calling `installTheme`, then we check `installTheme` before calling `installModules`, etc.. 🙂

File: src/PrestaShopBundle/Install/Install.php [hunk 2]
```diff
@@ -1026,6 +1026,10 @@ protected function executeAction(array $modules, string $action, string $errorMe
         foreach ($modules as $module_name) {
             $moduleException = null;
 
+            if ($moduleManager->isInstalled($module_name)) {
```
Comment (Progi1984) [inline src/PrestaShopBundle/Install/Install.php]: If the `action` is `postInstall`, then the action will not be executed;

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@atomiix Thank you for your contribution. I have found an edge case in `src/PrestaShopBundle/Install/Install.php`.

File: src/PrestaShopBundle/Install/Install.php (hunk 2 above)
Comment (atomiix) [reply src/PrestaShopBundle/Install/Install.php]: Nice catch!

File: install-dev/controllers/http/process.php (hunk 1 above)
Comment (jolelievre) [reply install-dev/controllers/http/process.php:103]: Oh right! I didn't notice you updated the step that is supposed to be executed right before I get it now!

**Review by jolelievre — APPROVED** [review]
Thanks @atomiix

**Review by Progi1984 — APPROVED** [review]

**Review by marwachelly — APPROVED** [review]
Hello @atomiix,

Thank you for your PR. It's  tested and the issue is well fixed.

https://user-images.githubusercontent.com/89604350/165110429-0c58215b-6bce-4d2f-a84b-b9ad3833a246.mp4

Thanks,

**Comment by Progi1984** [comment]
Thanks @atomiix & @marwachelly
