### PR TITLE
Check that $session is set before using it

### LINKED ISSUE #24781: cookie.php getSession not checking that $session is defined before using it
#### Describe the bug

In Cookie.php $session is used before checking if it is defined or not. This leads to crash if for example logout is called without checking if the session is alive.

https://github.com/PrestaShop/PrestaShop/blob/5f7367fc84c09dfee1306de149737b0316362bc5/classes/Cookie.php#L584

```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in ..../classes/Cookie.php:548
```

#### Expected behavior

No crash when calling logout without session.

#### Steps to Reproduce

call logout twice..

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

That method is added here: https://github.com/PrestaShop/PrestaShop/commit/3ef3b64d27b7d248bbd2f92289f11369b3dbbafa#diff-98d8ae92e3bdf87d1bd72ab244ca1619cb90f3fa8d0ed9a4c462ce1b929092b4R540

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Check that $session is set before calling its methods
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24781
| How to test?      | Call getSession without proper session
| Possible impacts? | Session handling gets more robust with small defensive coding..

Special thanks for the slack discussions on this: @PierreRambaud @cdcvince

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24782)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

File: classes/Cookie.php [hunk 1]
```diff
@@ -589,7 +589,7 @@ public function getSession($sessionId)
             $session = new CustomerSession($sessionId);
         }
 
-        if (!empty($session->getId())) {
+        if ($session && !empty($session->getId())) {
```
Comment (Quetzacoalt91) [inline classes/Cookie.php]: In the error you got, it was like PHP put a default value on this variable. It seems that it could remain undefined in some cases, I wonder if 

```suggestion
        if (isset($session) && !empty($session->getId())) {
```

wouldn't be even better.

**Review by PierreRambaud — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

File: classes/Cookie.php [hunk 2]
```diff
@@ -589,7 +589,7 @@ public function getSession($sessionId)
             $session = new CustomerSession($sessionId);
         }
 
-        if (!empty($session->getId())) {
+        if (isset($session) && !empty($session->getId())) {
```
Comment (PululuK) [inline classes/Cookie.php]:
```suggestion
        if (Validate::isLoadedObject($session)) {
```

**Comment by Robin-Fischer-PS** [comment]
Hi,

No need for QA on this PR. If a maintainer can check the PR before merge it would be nice.

Thanks :)

File: classes/Cookie.php (hunk 2 above)
Comment (PierreRambaud) [reply classes/Cookie.php]: haha always forget this one :+1:

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

File: classes/Cookie.php [hunk 3]
```diff
@@ -589,7 +589,7 @@ public function getSession($sessionId)
             $session = new CustomerSession($sessionId);
         }
 
-        if (!empty($session->getId())) {
+        if (Validate::isLoadedObject($session)) {
```
Comment (tswfi) [inline classes/Cookie.php]: @PululuK Are you sure this works? Wouldn't this still throw "undefined variable" ?

Comment (tswfi) [reply classes/Cookie.php]: yup, just tested and I can still replicate the problem in a shop with just the validate change

image

```suggestion
        if ($session && Validate::isLoadedObject($session)) {
```

Comment (PierreRambaud) [reply classes/Cookie.php]: PR rebased and squash ;)

**Review by Progi1984 — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

File: classes/Cookie.php (hunk 3 above)
Comment (PululuK) [reply classes/Cookie.php]: Thanks guys !

**Comment by PierreRambaud** [comment]
Thank you @tswfi
