### PR TITLE
Fix Multistore dropdown in current group context

### LINKED ISSUE #24334: Multistore dropdown - In Group Context, display only the shops of the group
#### Describe the bug

In Multistore, when we have several group with shops inside, if I'm in a Group Context in a page where the multistore dropdown can be displayed, I want the dropdown to display only the shops inside the group, not all the shops.

#### Expected behavior

Display only the shops inside the group in Multistore Dropdown

#### Steps to Reproduce

0. Have Multistore ON, have at least 2 groups with 2 shops in each (shops A & B in Group 1, shops C & D in Group 2)
1. Go to Shop Parameters > General > Maintenance
2. Set a specific parameter in shop A (shop in Group 1), and a specific parameter in shop C (shop in group 2)
3. Change context to "Group 2"
4. Open the Multistore dropdown : All the shops are displayed, only the one inside the group 2 should be displayed.

**Screenshots**

multistore dropdown group ocntext

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x 
| Description?      | When in a group context, multistore dropdowns should only display the state of fields for the current group, not other groups.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24334
| How to test?      | Detailed steps are available in issue #24334
| Possible impacts? | Multistore dropdown as a whole

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24355)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matthieu-rolland !

I have an issue with your PR : 

In all shops context, the list of the groups with the shops "stops" when there is a group customized, or a group in which a shop is customized. See the following screenshots, it will be clearer : 

Here, a shop in the first displayed group ("default") is customized, the list stop at this group : 
pr24355 missing all shops

Here, only the last group is customized so all the groups and shops are displayed : 
pr24355 missing all shops group customized 3

Here, the second group is customized, but not the first one, so only the first 2 groups are displayed : 
pr24355 missing all shops group customized

Hope this is clear ^^

File: src/PrestaShopBundle/Controller/Admin/MultistoreController.php [hunk 1]
```diff
@@ -115,20 +115,21 @@ public function header(bool $lockedToAllShopContext): Response
...
 
-        foreach ($groupList as $key => $group) {
-            if (count($group->getShops()) === 0) {
-                unset($groupList[$key]);
+        foreach ($shopGroups as $key => $group) {
+            if ($this->shouldIncludeGroupShop($group)) {
+                $groupList[] = $group;
             }
-            if ($this->multistoreContext->isAllShopContext() || $group->getId() === $this->multistoreContext->getContextShopGroup()->id) {
+            if ($this->multistoreContext->isAllShopContext() || $group->getId() === $this->multistoreContext->getContextShopGroup()->id && !$shouldDisplayDropdown) {
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/MultistoreController.php]: Hello @matthieu-rolland . I understand that what you are doing in function `configurationDropdown()` is

1. Gather multishop data
2. Do some computing and filtering to build $groupList
3. Return the dropdown, with the right data to be displayed

The step 2 is being run when the shop context is all shops, group shop and single shop. The 3 usecases run the same code which is why you have some conditional statement "if I am in shop group", "if I am in single shop"...

I may be out of scope, but I was wondering if the code could be easier to navigate if we handle the 3 usecases very differently?

I imagine something like this:

```
    public function configurationDropdown(ShopConfigurationInterface $configuration, string $configurationKey): Response
    {
        switch ($contextType)
            case self::CONTEXT_ALL_SHOPS:
                return $this->build AllShopsDropdown();
            case self::CONTEXT_GROUP_SHOPS:
                return $this->build GroupShopsDropdown();
            case self::CONTEXT_SINGLE_SHOP:
                return $this->build SingleShopDropdown();
    }
```

Then all the conditional logic "should I include group shop? yes? no?" would not be needed. For the 3 functions you would know exactly what to do.

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Controller/Admin/MultistoreController.php]: Actually there is only two cases: all shop or group shop (we never display this dropdown in single shop context, so this method is not even called).

I just separated the data gathering into two methods, one for all shop, and one for group shop, there is a little bit of repetition, but it's easier to read. 

If you guys think it was better before, I can still remove this last commit 👍  https://github.com/PrestaShop/PrestaShop/pull/24355/commits/66671d4ff30675934a6950f14e72f0e6750e2df0

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/MultistoreController.php [hunk 2]
```diff
@@ -115,35 +116,124 @@ public function header(bool $lockedToAllShopContext): Response
...
+     * @param array $shopGroups
+     * @param string $configurationKey
+     *
+     * @return array
+     */
+    private function allShopDropdown(CustomizedConfigurationChecker $shopCustomizationChecker, array $shopGroups, string $configurationKey): array
+    {
+        $groupList = [];
+        $shouldDisplayDropdown = false;
+        foreach ($shopGroups as $key => $group) {
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/MultistoreController.php:191]: Seems very similar as above :thinking: 
Maybe refactor it?

File: src/PrestaShopBundle/Controller/Admin/MultistoreController.php [hunk 3]
```diff
@@ -115,35 +116,124 @@ public function header(bool $lockedToAllShopContext): Response
...
+                || (
+                    $this->multistoreContext->isGroupShopContext()
+                    && $group->getId() === $this->multistoreContext->getContextShopGroup()->id
+                )
+            )
+        ) {
+            return true;
+        }
+
+        return false;
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/MultistoreController.php:237]:
```suggestion
        return count($group->getShops()) > 0
            && (
                $this->multistoreContext->isAllShopContext()
                || (
                    $this->multistoreContext->isGroupShopContext()
                    && $group->getId() === $this->multistoreContext->getContextShopGroup()->id
                )
            )
        );
```

**Comment by atomiix** [comment]
Thanks @matthieu-rolland & @Robin-Fischer-PS !
