### PR TITLE
Initialize dispatcher early and fix all $_FILES issues

### LINKED ISSUE #40022: move_uploaded_file causing error 500 in BO
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

PrestaShop is trying to handle upload itself independently.
Error 500 appears, because it's trying to work with "uploaded file" which already disappeared because move_uploaded_file
Tested for 1.7.x.x + 8.x.x, where it's working without troubles.
Problem is only for 9.x.x

TEST MODULE:
[shaim_move_uploaded_file.zip](https://github.com/user-attachments/files/23589245/shaim_move_uploaded_file.zip)

Screenshot with error 500 detailed:
[screencapture-ps80-openservis-cz-admin1869zbxwkyk6vnes5y8-improve-modules-manage-action-configure-shaim-move-uploaded-file-2025-11-17-18_56_31.pdf](https://github.com/user-attachments/files/23589200/screencapture-ps80-openservis-cz-admin1869zbxwkyk6vnes5y8-improve-modules-manage-action-configure-shaim-move-uploaded-file-2025-11-17-18_56_31.pdf)

### Expected behavior

No error 500

### Steps to reproduce

1. install my small module created for this purpose
2. try to upload file, any will see error 500
3. change "move_uploaded_file" to "copy" and there is not error 500, because file will persist, so no error 500 will be appeared, but copy is not correct usage for uploaded files! Only correct usage is "move_uploaded_file"

### PrestaShop version(s) where the bug happened

9.0.1

### How you installed PrestaShop

github

### PHP version(s) where the bug happened

8.3

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Dispatcher can be initialized too late and call request builder with malformed data. This makes sure it's done at the beginning of the request.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See the related issue.
| UI Tests          | https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/19618799004
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/40022
| Related PRs       | 
| Sponsor company   | TRENDO s.r.o.

### CODE REVIEW

**Review by Codencode — DISMISSED** [review]

**Comment by kpodemski** [comment]
@Hlavtox cs fixer `-Dispatcher` in category controller

File: admin-api/index.php [hunk 1]
```diff
@@ -70,6 +70,15 @@
...
 //Request::enableHttpMethodParameterOverride();
 $request = Request::createFromGlobals();
+
+/*
+ * Initialize legacy dispatcher at the initial stage of the request. If we don't do it now,
+ * the dispatcher could be created later by legacy classes. But, at that point, the request
+ * could already be modified, for examply by move_uploaded_file. That would cause createFromGlobals
+ * to crash.
+ */
+Dispatcher::getInstance($request);
```
Comment (kpodemski) [inline admin-api/index.php]: @Hlavtox I'm not sure if we need to do it here.

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php [hunk 2]
```diff
@@ -307,11 +306,6 @@ public function editAction(
 
         $defaultGroups = $defaultGroupsProvider->getGroups();
 
-        // If we don't create the dispatcher instance with the current request,
```
Comment (kpodemski) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController.php:310]: Lol. That was a nice hack.

File: admin-api/index.php (hunk 1 above)
Comment (Hlavtox) [reply admin-api/index.php]: Me neither, but hey, better be safe?

Comment (kpodemski) [reply admin-api/index.php]: I don't think there will be a situation where we use `move_uploaded_file` in the API context.

@jolelievre ?

Comment (jolelievre) [reply admin-api/index.php]: Yes there is, because some CQRS commands use it so the API will be based on it

Comment (jolelievre) [inline admin-api/index.php]: I think we should create another static method `setRequest` so that the `Dispatcher` class stores it without creating the Dispatcher singleton itself This way when the DIspatcher is not needed it will not be built, but when it becomes needed it can use the stored request

This way calling `Dispatcher::setRequest` is impactless when not needed, and protective when we need it Do you see the idea?

**Review by jolelievre — CHANGES_REQUESTED** [review]
The principle is great, just a suggestion to reduce the impact when the DIspatcher is not needed

File: admin-api/index.php (hunk 1 above)
Comment (Codencode) [reply admin-api/index.php]: If I've understood correctly, we should do something like this:

```php
    public static function getInstance(?SymfonyRequest $request = null)
    {
        if (!self::$instance) {
            if ($request === null || !self::$request) {
                if ($request === null) {
                    self::$request = $request;
                } else {
                    self::$request = SymfonyRequest::createFromGlobals();
                }
            }
            self::$instance = new Dispatcher(self::$request);
        }

        return self::$instance;
    }

    public static function setRequest(?SymfonyRequest $request = null)
    {
        if (!$request) {
            $request = SymfonyRequest::createFromGlobals();
        }

        return self::$request = $request;
    }
```

Right?
Excellent idea!!!

**Comment by Hlavtox** [comment]
@jolelievre @kpodemski @Codencode Guys check it now.

Now it only sets the request for future purposes, but does not start the dispatcher, load routes etc.

I was remaking it and then I see that you suggested exactly the same thing :D

File: admin-api/index.php (hunk 1 above)
Comment (jolelievre) [reply admin-api/index.php]: Almost but yeah that's the idea

```php
    public static function getInstance(?SymfonyRequest $request = null)
    {
        if (!self::$instance) {
            if ($request !== null) {
                self::$request = $request;
            } elseif (self::$request === null) {
                self::$request = SymfonyRequest::createFromGlobals();
            }
            self::$instance = new Dispatcher(self::$request);
        }

        return self::$instance;
    }

    public static function setSymfonyRequest(SymfonyRequest $request)
    {
        return self::$request = $request;
    }
```

File: classes/Dispatcher.php [hunk 3]
```diff
@@ -187,10 +197,22 @@ class DispatcherCore
...
+             * 2. If not set, we can use the request provided as parameter to getInstance() method.
+             * 3. Finally, if no request was provided, we create it from globals. However, this could be sometimes
+             *    dangerous and provide unexpected results, when a request data was already modified by the application.
+             */
+            if (self::$request == null) {
+                if (null !== $request) {
+                    self::$request = $request;
+                } else {
+                    self::$request = SymfonyRequest::createFromGlobals();
+                }
```
Comment (jolelievre) [inline classes/Dispatcher.php:213]: Ah I commented before I saw your modif, seems perfect this way!

**Review by jolelievre — DISMISSED** [review]

File: admin-api/index.php (hunk 1 above)
Comment (Codencode) [reply admin-api/index.php]: @jolelievre 
Of course you are the master!!! 😄

**Review by Codencode — DISMISSED** [review]

**Comment by Codencode** [comment]
@Hlavtox Perfect!
You just need to check the CS Fixer.

**Comment by Hlavtox** [comment]
@jolelievre @Codencode @kpodemski So NOW it's ready

**Review by Codencode — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Hlavtox

**Review by tleon — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @Hlavtox, 

Thanks for your PR, i tested it and it's good for me ^^ i'm waiting automated tests to approve the PR.

https://github.com/user-attachments/assets/4a2d1cce-1bb3-4e69-a972-5f414f0a845c

Thanks

**Comment by Hlavtox** [comment]
@SiraDIOP All green now. :-) merging

**Comment by SiraDIOP** [comment]
Automated tests are OK 
https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/19618799004
