### PR TITLE
Fix BO - Order - Wrong declination reference displayed on pack composition

### LINKED ISSUE #18370: BO - Order - Wrong declination reference displayed on pack composition
#### Describe the bug

In the BO => Order page => when a pack is ordered => the combination reference is not displayed, product reference is displayed instead.

#### Steps to Reproduce

1. Go to a declination detail 'T-shirt imprimé colibri Taille - S, Couleur - Blanc
2. Add a reference: demo_1_S_BLANC
3. Create a pack product
4. Add the declination to the pack: the declination reference is displayed. i.e. `demo_1_S_BLANC`
5. Save
6. Go t the FO => add the pack created to the cart and process to checkout
7. Go to the BO => Orders page => View the last Order created
8. Click on the link "View pack content" 
9. The product reference `demo_1` is displayed instead of declination reference `demo_1_S_BLANC`
image
image

#### Additional information

* PrestaShop version: 1.7.5.2, PS1.7.6.4, develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | In the BO => Order page => when a pack is ordered => the combination reference is not displayed, product reference is displayed instead.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/18370
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/18370 by @khouloudbelguith 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18374)

### CODE REVIEW

File: classes/Pack.php [hunk 1]
```diff
@@ -367,6 +367,13 @@ public static function getItemTable($id_product, $id_lang, $full = false)
                 if (isset($attr_name[0]['id_product_attribute_image']) && $attr_name[0]['id_product_attribute_image']) {
                     $line['id_image'] = $attr_name[0]['id_product_attribute_image'];
                 }
+
+                if (isset($attr_name[0]['attribute_reference'])) {
+                    $line['reference'] = $attr_name[0]['attribute_reference'];
+                } else {
+                    $line['reference'] = '';
+                }
```
Comment (Progi1984) [inline classes/Pack.php]:
```suggestion
                $line['reference'] = $attr_name[0]['attribute_reference'] ?? '';
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback

File: classes/Pack.php (hunk 1 above)
Comment (PululuK) [reply classes/Pack.php]: Hi @Progi1984,
Thanks man ... but this is a PHP 7 feature https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce
and PS 1.7.5 ~ 1.7.6 still support PHP 5.2 for example https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

We may be worried about servers in PHP 5.2 🤔 ?

Comment (Progi1984) [reply classes/Pack.php]: Hi @PululuK, 177 version support PHP 7.1 as minimal version. For 178, it's in discussion.

Comment (PululuK) [reply classes/Pack.php]: I may have misspoke myself ... this PR must work for PS 1.7.5.2 and 1.7.6.4 too, and these versions still support PHP => 5.2.
Suppose I am in a RunTime with a PS 1.7.5.2 and a PHP 5.2 ... Will your suggestion work ?

Comment (Progi1984) [reply classes/Pack.php]: This PR is targeted to `develop` branch, so the future 178 version. Actually, while the issue is not in 176x (patch version) ou 177x (actually in feature freeze) kanban, it can be integrated to previous versions.

Comment (PululuK) [reply classes/Pack.php]: I'm really sorry ... but how can I tag multiple branches ? Do I have to create a PR for each branch mentioned in the [issue](https://github.com/PrestaShop/PrestaShop/issues/18370)?

Comment (Progi1984) [reply classes/Pack.php]: See on issue with PM. But actually no new issues are integrated to these versions (else major or critical issues)

Comment (PululuK) [reply classes/Pack.php]: Ok thanks man !

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

It is OK
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @PululuK
