### PR TITLE
Wrong get and set data for employee options configuration

### LINKED ISSUE #24615: BO -  Employee options are NOK
#### Describe the bug

In the BO > Advanced Parameters > Team > Employees page, Try to change `Password regeneration` to 5 min, enable `Memorize the language used in Admin panel forms` and click on save, a green alert is displayed but no update saved

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Team > Employees page
2. Try to change `Password regeneration` to 5 min, enable `Memorize the language used in Admin panel forms`
3. Save
4. See error: no data saved
5. try to Sign out from the BO 
6. Click `I forget my password` and reset it
7. Try to reset it again => See error
image

It should be` You can reset your password every 5 minute(s) only. Please try again later.`

#### Additional information

* PrestaShop version: 178x
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Do not retrieve data from a custom array, it was the old behavior.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24615
| How to test?      | 1. Go to BO > Advanced Parameters > Team > Employees page<br>2. Try to change `Password regeneration` to 5 min, enable `Memorize the language used in Admin panel forms`<br>3. Save<br>4. See error: no data saved<br>5. try to Sign out from the BO <br>6. Click `I forget my password` and reset it<br>7. Try to reset it again => See error.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24632)

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsFormDataProvider.php [hunk 1]
```diff
@@ -52,16 +52,14 @@ public function __construct(DataConfigurationInterface $employeeOptionsConfigura
      */
     public function getData()
     {
-        return [
-            'options' => $this->employeeOptionsConfiguration->getConfiguration(),
-        ];
+        return $this->employeeOptionsConfiguration->getConfiguration();
```
Comment (PululuK) [inline src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsFormDataProvider.php:55]: BC, rigth ?

Comment (PierreRambaud) [reply src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsFormDataProvider.php:55]: Nope, it's a bug, not a bc breaks as the behavior is not the right one.

Comment (PululuK) [reply src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsFormDataProvider.php:55]: Removing **options** key in return, will break where it is expected right?

Comment (PierreRambaud) [reply src/PrestaShopBundle/Form/Admin/Configure/AdvancedParameters/Employee/EmployeeOptionsFormDataProvider.php:55]: > Removing **options** key in return, will break where it is expected right?

No, it's a missing change from an old PR, it's currently just a bug and shouldn't returns the options parameter ^^

**Review by PululuK — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1JtO94jmRz571EqHNvmHDJodSX0RfO0wG/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @PierreRambaud & @khouloudbelguith
