### PR TITLE
Fix to keep the main product category after importing a product update

### LINKED ISSUE #22336: Product Import - Main category deleted after the import
#### Describe the bug

Hello,

We have an issue on our prestashop (1.7.6.1) : when we import a product with only columns ID & Name, the main category of the product is deleted.

#### Expected behavior

The import should only change the data that are in the csv imported, no other information on the product.

#### Steps to Reproduce

1. Prepare a CSV to import a product : 
image

2. Check in the back office the main category of the product you want to import before doing the import (here it is "jumelles" : 
image

3. Go in the import part & import your CSV : 

image

image

image

image

4. Go back to the product page to see the change in the title (which is normal) and to see that the main category was deleted and moved to 'all products':
image

#### Additional information

* PrestaShop version: 1.7.6.1
* PHP version: N/A

### PR DESCRIPTION
**Pull request by SergioQuinonez**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | An error occurs when importing an "update" of products, the main category is changed randomly.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22336.
| How to test?      | 1. Take a reference product and watch its "Categories" section, [like this](https://user-images.githubusercontent.com/82282541/120587667-08615d80-c3f3-11eb-87f8-0b29427822da.png), focus in the main category<br>2. Create a simple product import file with 2 columns, `id_product` and `stock`<br>3. In the column of `id_product` put the product id used as a reference (from point 1)<br>4. In the the column of `stock` specify a valid integer amount<br>5. Go to "Advanced Parameters > Import" and choose your created import file<br>6. IMPORTANT: turn on the option "Force all ID numbers"<br>7. Continue, associate the corresponding column and import it!<br>8. Now go back to the reference product and check its "Categories" section, the main category must have changed
| Possible impacts? | Products import.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24780)

### CODE REVIEW

File: controllers/admin/AdminImportController.php [hunk 1]
```diff
@@ -1939,13 +1939,15 @@ protected function productImportOne($info, $default_language_id, $id_lang, $forc
         }
 
         // Category default now takes the value of the first new category during import
-        if (isset($product->id_category[0])) {
-            $product->id_category_default = (int) $product->id_category[0];
-        } else {
-            if (!isset($product->id_category_default) || !$product->id_category_default) {
+        if (!isset($product->id_category_default) || !$product->id_category_default) {
```
Comment (PierreRambaud) [inline controllers/admin/AdminImportController.php]: Isn't bit a little weird, as I understand this means we can import product data and update the default category if it already has one :thinking: ?

Comment (prestaalba) [reply controllers/admin/AdminImportController.php]: In fact, what this mean is: we cannot assign a new default category to a product that already has a defined default category and no default category modification has been requested on the CSV import. Only if an specific default category update is requested the change will be made (on the fillInfo method, previous to this code) and if default category is not present on id_category property, then it will be added.

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by marwachelly** [comment]
Hello,
When installing the shop I faced the attached error:
image
Could you please check.

**Comment by SergioQuinonez** [comment]
> Hello, When installing the shop I faced the attached error: image Could you please check.

Hi,
I don't know which version or commit you used for your installation, but I have created a fresh installation from the develop branch (commit: 8da483c06dcfb3dec0c7f4eaa12945c4784a4610) applying this patch and it goes perfectly.

image
image

**Comment by marwachelly** [comment]
> > Hello, When installing the shop I faced the attached error: image Could you please check.
> 
> Hi, I don't know which version or commit you used for your installation, but I have created a fresh installation from the develop branch (commit: [8da483c](https://github.com/PrestaShop/PrestaShop/commit/8da483c06dcfb3dec0c7f4eaa12945c4784a4610)) applying this patch and it goes perfectly.
> 
> image image

Hello @SergioQuinonez ,
Thank you for your feedback. It could be a cache issue. I Cloned again the project and now the installation works fine. PR will be tested.

**Comment by marwachelly** [comment]
Hello;
I tested the PR, the  issue was fixed but I found a regression related to the PR with another scenario:
when the main category is Home then I want to change the category to Art with an import: 
In the branch develop without PR the main category change to Art.  But when I tested with the PR after the import of the file to change the category from Home to Art I,  the category home is still defined as main category .
Test on the branch develop without PR 
https://www.awesomescreenshot.com/video/5597081?key=674eea887de3edcd62446ae7b57921dd
Test on develop with PR
https://www.awesomescreenshot.com/video/5596930?key=fcca1ded002793273c35ec88e76202bf
Could you please check.
Thanks,

**Comment by prestaalba** [comment]
> Hello; I tested the PR, the issue was fixed but I found a regression related to the PR with another scenario: when the main category is Home then I want to change the category to Art with an import: In the branch develop without PR the main category change to Art. But when I tested with the PR after the import of the file to change the category from Home to Art I, the category home is still defined as main category . Test on the branch develop without PR https://www.awesomescreenshot.com/video/5597081?key=674eea887de3edcd62446ae7b57921dd Test on develop with PR https://www.awesomescreenshot.com/video/5596930?key=fcca1ded002793273c35ec88e76202bf Could you please check. Thanks,

Hello. I fixed the code to take into account the scenario that you report as a regression. Please, let me know if everything is OK when you test it again.

**Review by atomiix — DISMISSED** [review]

File: controllers/admin/AdminImportController.php [hunk 2]
```diff
@@ -1940,7 +1940,9 @@ protected function productImportOne($info, $default_language_id, $id_lang, $forc
 
         // Category default now takes the value of the first new category during import
         if (isset($product->id_category[0])) {
-            $product->id_category_default = (int) $product->id_category[0];
+            if (!isset($product->id_category_default) || !$product->id_category_default || !in_array($product->id_category_default, $product->id_category)) {
```
Comment (Progi1984) [inline controllers/admin/AdminImportController.php]:
```suggestion
            if (!empty($product->id_category_default) || !in_array($product->id_category_default, $product->id_category)) {
```

**Review by Progi1984 — COMMENTED** [review]
@SergioQuinonez Thank you for your contribution. I have brought a small optimization of your code.

**Comment by SergioQuinonez** [comment]
> @SergioQuinonez Thank you for your contribution. I have brought a small optimization of your code.

Ok, I commited your code proposal, thanks!

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by marwachelly** [comment]
Hello, 

1. Import product without changing the main category (The main category entered is different from Home)=> The main category is changed to Home => issue still not fixed

https://www.awesomescreenshot.com/video/5808523?key=ba6947b9fb8356acf8397dce3b3f9f75

2. Import product with changing the main category (The main category entered is Home)=> The main category is changed as mentioned in the file imported => issue fixed 

https://www.awesomescreenshot.com/video/5808143?key=4cd440804f6a4e69c353843073724d6c

Could you please check ?

Many thanks,

**Comment by prestaalba** [comment]
> Hello,
> 
> 1. Import product without changing the main category (The main category entered is different from Home)=> The main category is changed to Home => issue still not fixed
> 
> https://www.awesomescreenshot.com/video/5808523?key=ba6947b9fb8356acf8397dce3b3f9f75
> 
> 1. Import product with changing the main category (The main category entered is Home)=> The main category is changed as mentioned in the file imported => issue fixed
> 
> https://www.awesomescreenshot.com/video/5808143?key=4cd440804f6a4e69c353843073724d6c
> 
> Could you please check ?
> 
> Many thanks,

Sorry @marwachelly. There was an small error on the Code optimization commit proposed by @Progi1984. Already fixed on the new commit. Regards.

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@SergioQuinonez Sorry I can't send your PR in QA as the issue #22336 is waiting for @PrestaShop/product-team

**Review by matthieu-rolland — APPROVED** [review]

**Comment by MatShir** [comment]
Go go go ! Thanks for the contribution. LGTM 👍

**Comment by PierreRambaud** [comment]
Thank you @SergioQuinonez

**Comment by hibatallahAouadni** [comment]
Hello @SergioQuinonez 

Thanks for your PR :clap: 
LGTM, QA :heavy_check_mark: 

Thanks!
