### PR TITLE
BO - Create Order page - Defined the order status relative to payment

### LINKED ISSUE #18831: BO - When creating an order, the status selected by default in the drop-down is canceled
**EDIT:**
#### Describe the bug

When the user chooses a payment method, the create order page assigns an automatic status defined by a hard-coded list in the code. When the payment module was not associated with a status in the create order page, the status "payment accepted" is assigned by default.

#### Expected behaviour

To remove the hard-coded list associating the status and payment method.
The default value of the payment method in the droplist is "Choose a payment method" or empty value (wording still to be defined). When the user selects a payment method, it does not affect the list. 
The default value of the status droplist is "Choose a status" or empty value (wording still to be defined). 
So to create the order, the user has to select an order status. An error message is thrown if the user has not chosen a status or payment method.

#### Steps to Reproduce

Steps to reproduce the behaviour:

1. Go to BO->Order
2. Click on Create order
3. Add a product
4. Scroll down to the bottom of the page
5. See the status selected by default

**Screenshots**
Legacy 
Capture d’écran 2020-04-27 à 10 36 30

Migrated
Capture d’écran 2020-04-27 à 10 37 08

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | BO - Create Order page - Defined the order status relative to payment module
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18831
| How to test?  | 0. Build assets<br>1. Go to BO > Order<br>2. Click on Create order<br>3. Add a product<br>4. Scroll down to the bottom of the page<br>5. See the status selected by default.<br>6. Change the status<br>7. Change the payment<br>8. The status must be change to the default 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18875)

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 1]
```diff
@@ -48,16 +54,37 @@ class CartSummaryType extends AbstractType
...
-        FormChoiceProviderInterface $paymentModulesChoiceProvider
+        FormChoiceProviderInterface $paymentModulesChoiceProvider,
+        Configuration $configuration
     ) {
+        $this->configuration = $configuration;
         $this->orderStatesChoiceProvider = $orderStatesChoiceProvider;
         $this->paymentModulesChoiceProvider = $paymentModulesChoiceProvider;
+        $this->defaultOrderState = (int) $this->configuration->get('PS_OS_PAYMENT');
+        $this->paymentOrderStates = [
+            'ps_checkpayment' => (int) $this->configuration->get('PS_OS_CHEQUE'),
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: These are hardcoded modules ? 😮

Can you explain why you need these informations ?

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: It's the default order state relative to payment module.

Legacy : https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminOrdersController.php#L245

**Review by NeOMakinG — DISMISSED** [review]
Front end part looks fine for me

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 1 above)
Comment (matks) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: Waho 😅 

Question: is it OK that in legacy it was named `$defaults_order_state` but you named it `paymentOrderStates` (and used `defaultOrderState` for another thing).

Suggestion, not mandatory: add a comment to explain this, because it's not obvious and if I was surprised by it, I think other people will be surprised (and have the same question) too. So the comment will carry the answer.

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 1 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: Renamed variable ;)

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: This should be dynamic based on order_state and modules..
In `ps_order_state` you have a `module_name` column that will allow you to match the module, and the waiting status seems to be the one whose template is `payment` in the `ps_order_state_lang`

So you could add add the `FormChoiceAttributeProviderInterface` to `prestashop.adapter.form.choice_provider.installed_payment_modules` which would return a dynamic array `['module_name' => pending_order_state_id]`

File: admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js [hunk 2]
```diff
@@ -186,6 +187,10 @@ export default class CreateOrderPage {
     });
   }
 
+  initSummaryOrderStatus() {
+    $(createOrderMap.summaryPaymentModule).trigger('change');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js]: You use the trigger to launch your change listener, but isn't it cleaner to init it manually using the first select option?
With
```
this.summaryManager.setOrderState($(`${createOrderMap.summaryPaymentModule} option:selected`).data('order-state'))
```

**Review by jolelievre — CHANGES_REQUESTED** [review]
Sorry, I know the legacy behavior includes those hard coded values per module But we can't integrate this as sis, it's too ugly
- if a new module is integrated it won't be managed correctly (#ps_checkout)
- developing a proper dynamic solution is not that complex with the tools and interfaces we already have (see my comment)

File: admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js (hunk 2 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/create/create-order-page.js]: Fixed

**Review by atomiix — DISMISSED** [review]

File: src/Adapter/Form/ChoiceProvider/InstalledPaymentModulesChoiceProvider.php [hunk 3]
```diff
@@ -53,4 +76,24 @@ public function getChoices(): array
...
+
+    /**
+     * {@inheritdoc}
+     */
+    public function getChoicesAttributes()
+    {
+        $attr = [];
+        $orderStates = $this->orderStateDataProvider->getOrderStates($this->contextLangId);
+        foreach (array_keys($this->getChoices()) as $moduleName) {
+            $attr[$moduleName] = array_reduce($orderStates, function ($carry, $item) use ($moduleName) {
```
Comment (jolelievre) [inline src/Adapter/Form/ChoiceProvider/InstalledPaymentModulesChoiceProvider.php]: Correct me if I'm wrong, this gives you the state assigned to a module, but it doesn't ensure that it's a "waiting payment" state, because a module can have several states assigned to it

From what I see, this information is in `order_state_lang.template` which needs to be `payment` because it's the email sent to require payment from the customer, but another criteria might be to check for the state flags and search for one that as `paid = 0`

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 4]
```diff
@@ -79,8 +88,8 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('order_state', ChoiceType::class, [
                 'choices' => $this->orderStatesChoiceProvider->getChoices(),
-                'required' => false,
-                'placeholder' => false,
+                'required' => true,
+                'placeholder' => $this->translator->trans('Choose a feature', [], 'Admin.Catalog.Feature'),
```
Comment (Progi1984) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: @MatShir Need wording

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 5]
```diff
@@ -1524,6 +1524,10 @@ private function getErrorMessages(Exception $e)
                     'Invalid action: this order has not been paid.',
                     'Admin.Notifications.Error'
                 ),
+                InvalidOrderStateException::NOT_FOUND => $this->trans(
+                    'Invalid order state id.',
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: @MatShir Need wording

File: src/Core/Domain/Order/Exception/InvalidOrderStateException.php [hunk 6]
```diff
@@ -51,6 +51,10 @@ class InvalidOrderStateException extends OrderException
      * Used when the order has been delivered (and it shouldn't have)
      */
     const UNEXPECTED_DELIVERY = 4;
+    /**
+     * Used when the order state is not found
+     */
+    const NOT_FOUND = 5;
```
Comment (jolelievre) [inline src/Core/Domain/Order/Exception/InvalidOrderStateException.php]:
```suggestion

    /**
     * Used when the order state is not found
     */
    const NOT_FOUND = 5;
```

File: src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php [hunk 7]
```diff
@@ -139,7 +140,10 @@ private function assertIsModuleName($moduleName)
     private function assertOrderStateIsPositiveInt($orderStateId)
     {
         if (!is_int($orderStateId) || 0 >= $orderStateId) {
-            throw new OrderException('Invalid order state id');
+            throw new InvalidOrderStateException(
+                InvalidOrderStateException::NOT_FOUND,
```
Comment (jolelievre) [inline src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php]:
```suggestion
                InvalidOrderStateException::INVALID_ID,
```

`NOT_FOUND` would be more adapted for a valid ID that doesn't match any row in the database

I hesitate between `INVALID_ID` because it is redundant with the class name, I thought about `MISSING` at first 🤔

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 4 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]:
```suggestion
                'placeholder' => $this->translator->trans('Choose an order status', [], 'Admin.Orderscustomers.Feature'),
```

This one already exists and seems fitting

**Comment by MatShir** [comment]
EDIT2:
FYI: https://github.com/PrestaShop/prestashop-specs/pull/101/files#diff-c1e0379db435994768883dec603a3e0e
@sarahdib 

#### Describe the bug

When the user chooses a payment method, the create order page assigns an automatic status defined by a hard-coded list in the code. When the payment module was not associated with a status in the create order page, the status "payment accepted" is assigned by default.

#### Expected behaviour

To remove the hard-coded list associating the status and payment method.
The default value of the payment method in the droplist is "Choose a payment method" or empty value (wording still to be defined). When the user selects a payment method, it does not affect the list. 
The default value of the status droplist is "Choose a status" or empty value (wording still to be defined). 
So to create the order, the user has to select an order status. An error message is thrown if the user has not chosen a status or payment method.

File: src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php (hunk 7 above)
Comment (Progi1984) [reply src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php]: Good idea for `MISSING` but empty is not missing. I prefer `INVALID_ID` ;)

Comment (Progi1984) [reply src/Core/Domain/Order/Command/AddOrderFromBackOfficeCommand.php]: Fixed

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 4 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: Corrigé ;)

**Comment by MatShir** [comment]
Hi @Progi1984 
@LouiseBonnard had a nice suggestion. Do you think we could disable the validation button until the merchant select both of inputs? It will avoid unnecessary error messages. 

If not @LouiseBonnard will bring the required wording for the error message and the default wording in the dropdowns.

**Comment by Progi1984** [comment]
@MatShir The submit button can't be click while the input has been filled. Thanks HTML5 Required.

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 8]
```diff
@@ -74,13 +83,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('payment_module', ChoiceType::class, [
                 'choices' => $this->getPaymentModuleChoices(),
-                'required' => false,
-                'placeholder' => false,
+                'required' => true,
+                'placeholder' => $this->translator->trans(
+                    'Choose a payment type',
```
Comment (Progi1984) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: Ping @LouiseBonnard

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 9]
```diff
@@ -74,13 +83,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+                    'Admin.Catalog.Feature'
+                ),
             ])
             ->add('order_state', ChoiceType::class, [
                 'choices' => $this->orderStatesChoiceProvider->getChoices(),
-                'required' => false,
-                'placeholder' => false,
+                'required' => true,
+                'placeholder' => $this->translator->trans(
+                    'Choose an order status',
```
Comment (Progi1984) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]: Ping @LouiseBonnard

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 5 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Ping @LouiseBonnard

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 10]
```diff
@@ -1499,6 +1500,10 @@ private function getErrorMessages(Exception $e)
                     'Admin.Orderscustomers.Notification'
                 ),
             ],
+            InvalidModuleException::class => $this->trans(
+                'Payment module name is invalid',
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Ping @LouiseBonnard

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 8 above)
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]:
```suggestion
                    '-- Choose --',
```

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 11]
```diff
@@ -74,13 +83,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('payment_module', ChoiceType::class, [
                 'choices' => $this->getPaymentModuleChoices(),
-                'required' => false,
-                'placeholder' => false,
+                'required' => true,
+                'placeholder' => $this->translator->trans(
+                    'Choose a payment type',
+                    [],
+                    'Admin.Catalog.Feature'
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]:
```suggestion
                    'Admin.Actions'
```

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 9 above)
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]:
```suggestion
                    '-- Choose --',
```

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 12]
```diff
@@ -74,13 +83,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
             ])
             ->add('order_state', ChoiceType::class, [
                 'choices' => $this->orderStatesChoiceProvider->getChoices(),
-                'required' => false,
-                'placeholder' => false,
+                'required' => true,
+                'placeholder' => $this->translator->trans(
+                    'Choose an order status',
+                    [],
+                    'Admin.Orderscustomers.Feature'
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php]:
```suggestion
                    'Admin.Actions'
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 13]
```diff
@@ -1499,6 +1500,10 @@ private function getErrorMessages(Exception $e)
...
+                'Admin.Catalog.Notification'
+            ),
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Do we need this error notification? It is a dropdown selector, right?

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 5 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Same here. :-)

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 13 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: It's an error in an alert box if the form is submitted and payment module is not right filled.

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 5 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: It's an error in an alert box if the form is submitted and order state is not right filled.

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 13 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: If we want to stay consistent, we should use _Please fill in all the required fields._ - an error notification that already exists on this page. But it looks like all fields are required on this page and therefore there is no red asterisk to let the user know which fields are required. It might be confusing for the users. So I suggest _You must choose a payment module to create the order._ in _Admin.Orderscustomers.Notification_.

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 5 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Order state or order status? I suggest _You must choose an order status to create the order._ in _Admin.Orderscustomers.Notification_.

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php [hunk 14]
```diff
@@ -74,13 +83,21 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('payment_module', ChoiceType::class, [
                 'choices' => $this->getPaymentModuleChoices(),
-                'required' => false,
-                'placeholder' => false,
+                'required' => true,
+                'placeholder' => $this->translator->trans(
+                    '-- Choose --',
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php:88]: So we keep a generic placeholder? Not a specific one like `Choose a payment module` and `Choose an order state` ?
@LouiseBonnard

**Review by jolelievre — APPROVED** [review]
Seems good to me, just one question regarding the wording

Also no changes needed on the javascript side? The part that automatically selected a value has already been removed?
Do the selector need to be repositioned on the first empty choice on update?

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php (hunk 14 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php:88]: It's @LouiseBonnard which have decided. It's not me.

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php:88]: I've browsed the software this morning and this part is messy... there are currently many ways of selecting an item in a dropdown list: 

1. the first line can be just empty, 
2. or can have the first option preselected by default (pretty risky in this case),
3. or have a specified first line ('Choose a feature', or 'Please choose a MySQL table', etc.),
4. or have a generic first line ('-- Choose --', like in the cart rule restrictions part).

My recommendation goes to the two last points for a more user-friendly experience. According to the decision we will make, we will have to specify it in the UI kit right after so that it can be taken into account in later developments - and then harmonized throughout PrestaShop.

Having a generic first line like '-- Choose --' for all dropdown selectors seems to be the easiest way. I don't mind having a specified first line, even if it multiplies the strings, but my point is that it will have to be documented in the UI kit anyway.

FYI @Junebyun, @MatShir, @prestascott, and @TristanLDD

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php:88]: OK fine for me with the generic message, besides the label already explains what we are selecting Maybe we should document this decision indeed (once it's settled) for future similar behaviour

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Form/Admin/Sell/Order/CartSummaryType.php:88]: Again, I totally agree with you, @jolelievre!
😄

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks  @Progi1984  !

**Comment by PierreRambaud** [comment]
Thanks @Progi1984
