### PR TITLE
Disallow birth year in two digits

### LINKED ISSUE #17341: birthday date to 'xx-xx-0000' erreur 500
**Describe the bug**
if a customer create one account and change the birthday date to 'xx-xx-0000', th account is validate but when he want go to "account> informations " he have a error "500 Server Error" and he can't do an order (he can't go to url :/commande => "500 Server Error" )

if a customer change his birthday date in the account>information page with this value ('xx-xx-0000') he have the same probleme.

**Screenshots**
Image 2

**Additional information**
Version de PrestaShop : 1.7.6.3
Version de PHP : 7.2.26-1+ubuntu16.04.1+deb.sury.org+1

AND

Version de PrestaShop : 1.7.5.1
Version de PHP : 7.0.33-1~dotdeb+8.1

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | To avoid year in two digits ob bug with xx-xx-0000 date, disallow date < 200 years ago
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/17341 & https://github.com/PrestaShop/PrestaShop/issues/17507
| How to test?  |  In customer creation/modification, fill in a bith date like xx-xx-85 or xx-xx-0000 : no more year date like 0085 or error 500 for xx-xx-0000

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17664)

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you add tests in ValidateCoreTest.php please? There is already an `isBirthDateProvider` you can improve :)

File: classes/Validate.php [hunk 1]
```diff
@@ -638,8 +638,9 @@ public static function isBirthDate($date, $format = 'Y-m-d')
         if (!empty(DateTime::getLastErrors()['warning_count']) || false === $d) {
             return false;
         }
+        $twoHundredYearsAgo = time() - (200 * 365 * 24 * 60 * 60);
```
Comment (Progi1984) [inline classes/Validate.php]:
```suggestion
        $twoHundredYearsAgo = new Datetime();
        $twoHundredYearsAgo->sub(new DateInterval('P200Y'));
```

File: classes/Validate.php [hunk 2]
```diff
@@ -638,8 +638,9 @@ public static function isBirthDate($date, $format = 'Y-m-d')
...
 
-        return $d->setTime(0, 0, 0)->getTimestamp() <= time();
+        return $d->setTime(0, 0, 0)->getTimestamp() <= time() && $d->setTime(0, 0, 0)->getTimestamp() >= $twoHundredYearsAgo;
```
Comment (Progi1984) [inline classes/Validate.php]:
```suggestion
        return $d->setTime(0, 0, 0)->getTimestamp() <= time() && $d->setTime(0, 0, 0) >= $twoHundredYearsAgo;
```

File: classes/Validate.php (hunk 1 above)
Comment (PierreRambaud) [reply classes/Validate.php]: If you prefer use Datetime here, you need to update the whole method to be consistent :)

File: classes/Validate.php (hunk 2 above)
Comment (PierreRambaud) [inline classes/Validate.php]:
```suggestion
        return $d->setTime(0, 0, 0) <= new Datetime() && $d->setTime(0, 0, 0) >= $twoHundredYearsAgo;
```

File: classes/Validate.php (hunk 1 above)
Comment (jf-viguier) [reply classes/Validate.php]: done

File: classes/Validate.php (hunk 2 above)
Comment (jf-viguier) [reply classes/Validate.php]: done

Comment (jf-viguier) [reply classes/Validate.php]: done

**Comment by jf-viguier** [comment]
tests added in ValidateCoreTest.php

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
This pull request correctly fix the issue thanks @jf-viguier

**Comment by matks** [comment]
Thank you @jf-viguier and congratulations on your 17th PR !
