### PR TITLE
In BO Product page, use ecotax excl. tax instead of tax incl.

### LINKED ISSUE #10026: [BOOM-1506] In BO Product page, ecotax tax excl is used instead of ecotax tax incl
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-1506).

- _**Reporter:**_ vincentbz
- _**Created at:**_ Tue, 20 Sep 2016 17:39:49 +0200

1) I enable ecotax in international > VAT
2) I define a tax for my ecotax of 20%
Capture du 2018-03-15 16-05-05

3) I set ecotax = 1€ tax incl
The price tax excl is not well recalculated (issue https://github.com/PrestaShop/PrestaShop/issues/9855)
Sans titre2

4) I save my product, reload the page ==> the ecotax = amount Tax Excl. The VAT on the ecotax has disappear in the nature. And the product price tax incl is also wrong (should be 12€)
Capture du 2018-03-15 16-40-38

### LINKED ISSUE #18550: Ecotax value is reduced each time a product is saved
#### Describe the bug

Ecotax value is reduced each time a product is saved.

1. Be sure to have ecotax enabled and set to a specific tax rule (20% in France, for example)
- go to International > Taxes page and enable ecotax
- then refresh page add tax ON ecotax
Capture d’écran 2020-04-10 à 16 54 31
2. Create a new product and set price without tax to 100, click "save" then refresh the page.
3. Set ecotax value to 10, save, refresh the page. You should see that ecotax amount is 8.3 because 20% tax has been applied.
4. ecotax value is now 8,3333 (=> 10/1,20)
5. do not touch anything, **save again**, refresh the page
6. ecotax value is now 6,944444 (8,333/1,20)
7. and so on....

#### Additional information

* PrestaShop version: 1.7.6 and probably lower versions too
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Ecotax is stored with tax included but form uses the tax excluded value. However BO Product page would load the form with tax. incl. value, leading to the crazy scenario described in https://github.com/PrestaShop/PrestaShop/issues/18550. I fix that.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/18550 and number 4 of https://github.com/PrestaShop/PrestaShop/issues/10026
| How to test?  | Please test the scenario described in https://github.com/PrestaShop/PrestaShop/issues/18550 . It should not happen anymore. Please check the ecotax amount is correctly being stored and computed for both "with ecotax tax and "without ecotax tax". By this I mean: you can add tax on ecotax 😄See below screenshot. Everything is explained in https://github.com/PrestaShop/PrestaShop/issues/18550

Screenshot

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18580)

### CODE REVIEW

**Comment by matks** [comment]
This is a `Topwatchers` bug and a `Major` bug fixed by only 2 lines of code. I think it could be backported to `1.7.6.x` branch to provide ecotax working field in 1.7.6

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php [hunk 1]
```diff
@@ -532,9 +532,12 @@ function ($p) {
      */
     private function mapStep2FormData(Product $product)
     {
+        // ecotax is stored with tax included but form uses the tax excluded value
+        $ecotax = \Tools::ps_round($product->ecotax * (1 + \Tax::getProductEcotaxRate() / 100), 2);
```
Comment (Progi1984) [inline src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Please declare `Tools` and `Tax`.

Comment (Progi1984) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: But it seems magic !

Comment (jolelievre) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Nice fix! Once it's merged in 176 I think we should adapt it with `ComputingPrecision` for 177
Same as @Progi1984 As soon as the `use` statement I approve right away 😉

**Review by matthieu-rolland — DISMISSED** [review]

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php (hunk 1 above)
Comment (matks) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: PR updated. I found that in this class adapter classes were available so I used already declared adapter classes instead.

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php [hunk 2]
```diff
@@ -532,9 +532,15 @@ function ($p) {
      */
     private function mapStep2FormData(Product $product)
     {
+        // ecotax is stored with tax included but form uses the tax excluded value
+        $ecotax = $this->tools->round(
+            $product->ecotax * (1 + $this->taxRuleDataProvider->getProductEcotaxRate() / 100),
+            2
```
Comment (hadjedjvincent) [inline src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: You should use more decimals here, 6 decimals maybe ? as the database `ecotax` column allow 6 decimals.

Comment (PierreRambaud) [inline src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Could you use a constant instead? or explain why you use 2 in a code comment.

Comment (matks) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Initially I was copying the behavior of `AdminProductsController::_applyTaxToEcotax()` but I see that indeed I should rather pick the same precision that is being used in the function that computes "tax excl." from "tax. incl." price, which is `AdminProductsController::_removeTaxFromEcotax()`

So, as `AdminProductsController::_removeTaxFromEcotax()` uses 6 precision digits, I will use 6 too.

Comment (matks) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Initially I was copying the behavior of `AdminProductsController::_applyTaxToEcotax()` but I see that indeed I should rather pick the same precision that is being used in the function that computes "tax excl." from "tax. incl." price, which is `AdminProductsController::_removeTaxFromEcotax()`

So, as `AdminProductsController::_removeTaxFromEcotax()` uses 6 precision digits, I will use 6 too.

Comment (matks) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Fixed in https://github.com/PrestaShop/PrestaShop/pull/18580/commits/f3b1d0e650165f0b4b61959deda23a999c346c21

Comment (matks) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Fixed in https://github.com/PrestaShop/PrestaShop/pull/18580/commits/f3b1d0e650165f0b4b61959deda23a999c346c21

**Review by Progi1984 — APPROVED** [review]

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php [hunk 3]
```diff
@@ -532,9 +532,17 @@ function ($p) {
      */
     private function mapStep2FormData(Product $product)
     {
+        // ecotax is stored with tax included but form uses the tax excluded value
+        // using a precision of 6 digits as `AdminProductsController::_removeTaxFromEcotax()`
+        // which does the opposite uses 6 digits too
+        $ecotax = $this->tools->round(
+            $product->ecotax * (1 + $this->taxRuleDataProvider->getProductEcotaxRate() / 100),
+            6
```
Comment (sowbiba) [inline src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:540]: can we put it in a constant ?

**Review by sowbiba — APPROVED** [review]

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php (hunk 3 above)
Comment (matks) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:540]: We could, but it would only be useful if all the places using this value use the constant as well.
I know https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminProductsController.php#L2209 uses it as this function reverts the logic there, and there might be more.

Could it be considered an improvement and I'll do it in another PR ?
I'm afraid of changing other parts of the code and introducing crazy bugs 😅which would then be reported by QA and that would block this PR

Comment (sowbiba) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:540]: Ok with that

**Comment by SD1982** [comment]
LGTM Thanks @matks !

**Comment by Progi1984** [comment]
Thanks @matks
