### PR TITLE
Fix compiled legacy container

### LINKED ISSUE #25112: Services in front container are not available once the container is cached
#### Describe the bug

If you try to access one of the following service:
- `configuration`
- `context`
- `db`
- `shop`
- `employee`
from the front container when the cache is empty, the first time you try to access it, it will work, but not the second time when the cache is created.

#### Expected behavior

Services should be always available

#### Steps to Reproduce

1. Clear the cache `rm -rf var/cache/*`
2. Open `controllers/front/IndexController.php` and add the following lines in the `initContent()` function:
```php
$container = ContainerBuilder::getContainer('front', true);
$entityManager = $container->get('shop');
```
3. Open your browser and try to access the front office of your shop
4. No error
5. Refresh
6. See error

#### Additional information

* PrestaShop version: 1.7.6.9, 1.7.7.x, 1.7.8.x, develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The way the front container is build makes services unavailable once the container is cached. This PR fixes it.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25112
| How to test?      | See below
| Possible impacts? | 

### How to test

In a front controller (`IndexController.php` for instance), try to get one of the following services: 
- `configuration`
- `context`
- `db`
- `shop`
- `employee`

```php
$container = ContainerBuilder::getContainer('front', true);
$entityManager = $container->get('shop');
```

With the cache cleared (`rm -rf var/cache/*`), you shouldn't have an exception, if you refresh the page, you shouldn't have an exception either.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25111)

### CODE REVIEW

File: classes/container/LegacyCompilerPass.php [hunk 1]
```diff
@@ -37,27 +37,32 @@ class LegacyCompilerPass implements CompilerPassInterface
...
 
-        $container->set('context', $context);
-        $container->set('configuration', new Configuration());
-        $container->set('db', Db::getInstance());
-        $container->set('shop', $context->shop);
-        $container->set('employee', $context->employee);
+        $this->buildSyntheticDefinitions(['shop' => Shop::class, 'employee' => Employee::class], $container);
+    }
+
+    private function buildDefinitions(array $keys, ContainerBuilder $container)
```
Comment (Progi1984) [inline classes/container/LegacyCompilerPass.php]:
```suggestion
    private function buildDefinitions(array $keys, ContainerBuilder $container): void
```

File: classes/container/LegacyCompilerPass.php [hunk 2]
```diff
@@ -37,27 +37,32 @@ class LegacyCompilerPass implements CompilerPassInterface
...
+                $definition = new Definition($class[0]);
+                $definition->setFactory($class);
+            } else {
+                $definition = new Definition($class);
+            }
+            $container->setDefinition($key, $definition);
+        }
     }
 
     private function buildSyntheticDefinitions(array $keys, ContainerBuilder $container)
```
Comment (Progi1984) [inline classes/container/LegacyCompilerPass.php]:
```suggestion
    private function buildSyntheticDefinitions(array $keys, ContainerBuilder $container): void
```

**Review by Progi1984 — DISMISSED** [review]
Small feedbacks but it's ok :)

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by atomiix** [comment]
This can be validated by a dev

**Comment by PierreRambaud** [comment]
Thank you @atomiix  and  @jolelievre
