### PR TITLE
Carrier selection improvement in BO product page

### LINKED ISSUE #30121: Carriers new ui in the product page v2
**US:**
As a merchant, I want to manage my carriers easily 
The old ui was not intuitive, none of the carrier has to be selected if you want all your carriers to be used for this product

**Specs:**

By default, 'all carriers' is selected.
When a carrier is selected in the drop list then the carriers are displayed below the drop list as a label.
Only the carriers selected can use to deliver the product.
 

Image

If all the carriers are unselected, then All carriers is selected in the drop list

### LINKED ISSUE #31417: PPV2 - The number of filter is not well displayed when filtering more than one in a product with combinations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The number of filters is not well displayed when filtering more than one in a product with combinations 

**PS8.1.0_beta_build1 : NOK** :x: 

image

**PS8.1.0_beta_build2 : NOK** :x: 

image

https://user-images.githubusercontent.com/92912932/219618605-947c58c0-701e-4202-93e0-d58e25d27897.mp4

**PS8.0.1 : OK** :heavy_check_mark: 

image

https://user-images.githubusercontent.com/92912932/219619437-e880c75a-a1ca-47c1-b738-f3ac73338342.mp4

So, it's a regression on **8.1.0_beta**!

### Expected behavior

The number of filters is well displayed

### Steps to reproduce

1. Use the 8.1.0_beta
2. Go to BO > Advanced parameters > New & Experimental features > Enable New product page
3. Go to BO > Catalog > Products V2 > Create a product with combinations
4. Add new combinations (eg: more than 2 combinations) for the product 
5. Click on Save
6. On the `Manage product combinations` section > Use Filter by > Choose the first filter
7. Click on the second filter 
8. See error >> The filter number is not well displayed
9. Click on the third/fourth.. filter 
8. See error >> The filter number is not well displayed

### PrestaShop version(s) where the bug happened

8.1.0_beta

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #31424: PPV2 : The filter number is not displayed at all with a product with a combination when filtering from Right to left
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The filter number is not displayed at all with a product with a combination when filtering from Right to left. 
Only **Clear filter** is displayed.

**PS8.1.0_beta_build1 : NOK** :x: 
image

**PS8.1.0_beta_build2 : NOK** :x: 
image

https://user-images.githubusercontent.com/92912932/219678934-747b4bc8-bd65-4bdb-bc74-d3c04c643ce1.mp4

**PS8.0.1 : OK** :heavy_check_mark: 

image

https://user-images.githubusercontent.com/92912932/219678868-ec119ed5-e837-491d-9309-68c7ee30fe38.mp4

So, it's a regression on **8.1.0_beta**!

### Expected behavior

The number of filtered cases is displayed!

### Steps to reproduce

1. Use the 8.1.0_beta
2. Go to BO > Advanced parameters > New & Experimental features > Enable New product page
3. Go to BO > Catalog > Products V2 > Create a product with combinations
4. Add new combinations (eg: more than 2 combinations) for the product
5. Click on Save
6. On the Manage product combinations section > Use Filter by > Choose the last filter **from right to left**
7. Click on the next filter
8. See error >> Only Clear filter is displayed and the number is not displayed

### PrestaShop version(s) where the bug happened

8.1.0_beta

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixes two issues (by refactoring common component in vue js): https://github.com/PrestaShop/PrestaShop/issues/30121, https://github.com/PrestaShop/PrestaShop/issues/31424
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30121, Fixes #31424, Fixes #31417
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/30121, https://github.com/PrestaShop/PrestaShop/issues/31424. Make sure carriers and combination filters works as expected (because they are using the same vue js component that was refactored)
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
Screenshot 2023-02-01 at 12 28 54
Screenshot 2023-02-01 at 12 29 03
Screenshot 2023-02-01 at 12 30 35

### CODE REVIEW

**Comment by zuk3975** [comment]
the idea was to reuse existing vue component that was used in combination filters. It almost works (needs to replace the new component checkboxes-dropdown usage in combinations and adjust backend.)
But this PR is now on hold as there are doubts if it is really an "improvement" or it makes the usage worse.

**Comment by NeOMakinG** [comment]
> the idea was to reuse existing vue component that was used in combination filters. It almost works (needs to replace the new component checkboxes-dropdown usage in combinations and adjust backend.) But this PR is now on hold as there are doubts if it is really an "improvement" or it makes the usage worse.

This UI may be over complicated, while we could have just 2 radios or a dropdown "All carriers, specific carriers" and new checkboxes appearing below in case "Specific carriers" is selected

File: admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue [hunk 1]
```diff
@@ -72,65 +73,74 @@
...
       },
+      disabled: {
+        type: Boolean,
+        default: false,
+      },
     },
     mounted() {
-      this.eventEmitter.on(CombinationEvents.clearAllCombinationFilters, this.clear);
+      this.selectedItems = this.items.filter((item) => this.initialItemIds.includes(item.id));
+      this.eventEmitter.on(eventClearAllSelections, () => this.clear());
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: You can't use EventEmitter anymore for a component which is shared and can be used multiple times in the page. The event emitter dispatches event that are global on the whole page so it will create a bug that, for example, clearing the combination filters will clear the carriers as well.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: We already saw this with Valentin when he refactored the component for Vue3 but at the time it as ok since the component was only used for combination generation and used an event only used in this scope. Now that the component needs to be generic this approach is not valid anymore.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: But for the solution, you can't use event in this component anymore I think. The `clear` method basically forces `this.selectedItems = []` So it's the parent which needs to do this operation when it needs to, via changing the injected props like `items` or `initialItemIds` (I'm not sure how they work..)

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+      removeCarrier(carrier: Carrier): void {
+        this.selectedCarrierIds = this.selectedCarrierIds.filter(
+          (id: number) => carrier.id !== id,
+        );
+      },
+      getLabel(): string {
+        return this.selectedCarrierIds.length > 0
+          ? this.$t('selectedCarriers.label')
+          : this.$t('allCarriers.label');
+      },
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue]: I believe this should be in the computed method if you want the value to automatically update when `selectedCarrierIds` values change

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php [hunk 3]
```diff
@@ -110,18 +116,35 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'default_empty_data' => 0.0,
                 'modify_all_shops' => true,
             ])
-            ->add('carriers', ChoiceType::class, [
-                'choices' => $this->carrierChoiceProvider->getChoices(),
+            // related all shops checkbox is rendered in javascript side, but it is still needed here to be correctly filled with data
+            ->add($modifyAllShopsInputName, HiddenType::class)
+        ;
+
+        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($modifyAllShopsInputName) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php]: I think you made this a bit too complicated, sorry I didn't understand the need when we discussed it.
All the data attributes you add here can be added without the an event form since most of them are not based on the data anyway.

The only which is related to the data is `data-selected-carrier-ids` but you don't need it, in your JS function `initCarrierSelector` you use it to get the selected carriers, but you can get them by getting the initial select values no need for JSON here, you can use a querySelector with the pseudo attribute `:checked` to retrieve this list.

Same thing for the whole `carrierChoices` list you can fetch it from all the available options in the select.

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php [hunk 4]
```diff
@@ -110,18 +116,35 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
+            $carrierChoices = $this->carrierChoiceProvider->getChoices();
+            $form = $event->getForm();
+            // Vue js CarrierSelector component mounts on this one instead of rendering default bootstrap choices list
+            $form->add('carriers', ChoiceType::class, [
+                'choices' => $carrierChoices,
+                'attr' => [
+                    'data-modify-all-shops-name' => sprintf('product[shipping][%s]', $modifyAllShopsInputName),
+                    'data-choice-input-name' => 'product[shipping][carriers][]',
```
Comment (jolelievre) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php]: These data attributes are not needed as well, you should get the name of the select field instead this way it's really dynamic and will adapt if it's renamed or moved

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php]: The modify for all is more a special case indeed, but I don't understand why the regular way doesn't work here? Seems like it could be completely out of the Vue component no?

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @zuk3975 

but a few things don't seem correct, or over-complicated we can discuss them if you want.

File: admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue (hunk 1 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue:115]: i tried it from parent and couldn't get it working, not sure why though 😭

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue (hunk 2 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue]: it works, but ok It is probably better practice to use computed 🤷‍♂️

File: admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue (hunk 1 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: I added a dynamic event name that can be passed to child component to clear all the filters, I don't know if there is another option. I can't mutate properties from parent in child without using events I think.

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php (hunk 3 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php]: yep thanks, I had this feeling it is getting too complicated 😄 . Now its much better 👍

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php (hunk 4 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php]: using the regular input (by form option modify_all_shops = true) when you click on the button which supposed to expand carriers selection, instead of expanding it and it kind of works strange then. Btw it for some reason renders above the component (though I guess that wouldn't be hard to fix)

https://user-images.githubusercontent.com/31609858/216284316-544a1e42-a59d-4ba5-b9d5-0e67f35adc9e.mov

Comment (zuk3975) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Shipping/ShippingType.php]: altough with custom one, the multishop checkbox always stays visible, but I made that way intentionally, so in case you just want to apply current shop carrier to all shops without modifying anything (so it appears on click, and never disapears 😄 )

**Comment by zuk3975** [comment]
Also it wasn't in specs but I added a button to clear selections quickly (it seemed nice to have, to avoid unselecting all carriers one by one)
Screenshot 2023-02-02 at 13 57 06

**Comment by zuk3975** [comment]
Ui tests fails for importing typescript interface, I also reproduced it once locally when building js files, but it seems to be random. I don't know how to fix that 😓

File: admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue [hunk 5]
```diff
@@ -72,65 +73,80 @@
...
+      },
+      disabled: {
+        type: Boolean,
+        default: false,
+      },
     },
     mounted() {
-      this.eventEmitter.on(CombinationEvents.clearAllCombinationFilters, this.clear);
+      this.selectedItems = this.items.filter((item) => this.initialItemIds.includes(item.id));
+      if (this.clearSelectedItemsEvent) {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: I think we could get rid of this event thing, the idea is to be able to clear the selected items from the parent. Now your `selectedItems` is a local data so it can't be edited by the parent, however it's built on mount based on `initialItemIds` And this one is a prop that can be edited by the parent. SO hat is possible is:

1. turn `selectedItems` into a computed field, based on `this.initialItemIds`
```ts
selectedItems(): array {
  this.items.filter((item) => this.initialItemIds.includes(item.id))
}
```

Now it will automatically update when the prop is updated, so in the parent you can do `mycomponent.initialItemIds = []` and it should clear it (it should also work ith automatic binding if the prop is linked to another variable).

Maybe you'll have to update also the `toggleSelection` method, basically instead of updating `selectedItems` (which is now a computed field without a setter) you do the same operations on `initialItemIds` and it will automatically update `selectedItems`

And finally maybe `initialItemIds` can be renamed into `selectedItemIds` which would match more with the way it will work (easier to understand from the parent point of view).

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: With this you should be able to remove the whole event emitter thing which would make the component more stable and more reusable

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: Oh and with this maybe you also won't need to use the `removeItem` and `addItem` event, but a `change` event so that the parent can use `selectedItemIds` directly as v-model

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/index.ts [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+      name: labelText,
+      label: labelText,
+    });
+
+    if (choiceInputName === '') {
+      // get the name of choice input which is important so that in backend side it is correctly filled in form when handling request
+      choiceInputName = input.name;
+    }
+  });
+
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/carriers/index.ts]: I'm wondering if all this could not be done in the mount of the component instead 🤔 I think on mount you have the reference of the container so you can get all its initial content in theory

**Review by jolelievre — COMMENTED** [review]
Thanks @zuk3975 

I have a few suggestions of improvement for the Vue component, if it's complex don't hesitate to tell me. I can either help you or try to implement it and see if my idea would work.

File: admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue (hunk 5 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: all of it sounds great in theory, but you cannot edit props. All props that are passed from parent are kind of immutable as I understand.
Screenshot 2023-02-03 at 14 54 12

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/index.ts (hunk 6 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/components/carriers/index.ts]: can be done, didn't think it would make sense as it would pollute the component by requesting indirect data. Like instead of choices list it will have to require input/label selectors which sounds a bit crappy 🤷‍♂️

File: admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue (hunk 5 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/app/components/CheckboxesDropdown.vue]: oh I was wrong all the time about this (I was confused and chased wrong idea from beginning 😄 ), since I passed the selected ids from parent, then child doesn't need to update them anymore. Fixed in latest commits.

File: admin-dev/themes/new-theme/js/app/widgets/ps-select.vue [hunk 7]
```diff
@@ -51,7 +51,7 @@
 
   export default defineComponent({
     props: {
-      items: {
+      choices: {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/app/widgets/ps-select.vue]: Hmm be careful this widget is old and used in other apps, so you can't change the name of the prop here or it will create side effects The naming is better in the new component but for this one we must keep this less good
Unless we can have an "alias" feature that allows using both props names (and deprecate the `items` one maybe until we replace it everywhere)

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue [hunk 8]
```diff
@@ -0,0 +1,159 @@
...
+  import CheckboxesDropdown from '@app/components/checkboxes-dropdown/CheckboxesDropdown.vue';
+  import {defineComponent, PropType} from 'vue';
+  import ProductEventMap from '@pages/product/product-event-map';
+  import {Choice} from '@app/components/checkboxes-dropdown/types';
+
+  export default defineComponent({
+    name: 'CarrierSelector',
+    data(): {
+      selectedCarrierIds: number[],
+      clearSelectedCarriersEvent: string,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue]: This one can now be removed 🎉

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+      choiceInputName: {
+        type: String,
+        required: true,
+      },
+    },
+    components: {
+      CheckboxesDropdown,
+    },
+    mounted() {
+      this.selectedCarrierIds = this.initialCarrierIds;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue]: Hehe I though about this one 😅
Nice trick, it should work fine because we don't update the prop on this component anyway, although if it one day needs to be used in another Vue app and to make this prop correctly responsive a watch maybe be needed in case the prop is modified
But not needed for now

File: admin-dev/themes/new-theme/js/app/widgets/ps-select.vue (hunk 7 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/app/widgets/ps-select.vue]: Or at least we should fix the only other usage I could find https://github.com/PrestaShop/PrestaShop/blob/794e8bd29d107dd46df21f95d7a53d987b4d61d3/admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters.vue#L64

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/index.ts [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+  const vueApp = createApp(CarrierSelector, {
+    i18n,
+    carrierChoices,
+    initialCarrierIds,
+    modifyAllShopsName: <string>container.dataset.modifyAllShopsName,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/carriers/index.ts]:
```suggestion
```
I think this one can be removed, it's not used anymore

File: admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue [hunk 11]
```diff
@@ -57,17 +56,22 @@
...
+  import ProductEventMap from '@pages/product/product-event-map';
 
   const CombinationEvents = ProductEventMap.combinations;
 
   export default defineComponent({
     name: 'Filters',
-    data(): {selectedFilters: Record<string, any>} {
+    data(): {
+      selectedFilters: Record<string, any>,
+      clearSelectedFiltersEvent: string,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue]: This one can be removed it's not used anymore

File: admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue [hunk 12]
```diff
@@ -126,7 +130,6 @@
       },
       clearAll(): void {
         this.selectedFilters = [];
-        this.$emit('clearAll');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue]: You can also clear `this.eventEmitter.emit(CombinationEvents.clearAllCombinationFilters);` No one listens to this event anymore

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue [hunk 13]
```diff
@@ -308,7 +308,7 @@
         );
 
         this.sortableContainer.sortable({
-          items: DropzoneMap.sortableItems,
+          choices: DropzoneMap.sortableItems,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue]: Hmm, are you sure it's related? 🤔 Or is it an automatic change by your IDE maybe?
I don't see the connection with modified components

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue (hunk 8 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue]:
```suggestion
```

File: admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue [hunk 14]
```diff
@@ -0,0 +1,159 @@
...
+
+  export default defineComponent({
+    name: 'CarrierSelector',
+    data(): {
+      selectedCarrierIds: number[],
+      clearSelectedCarriersEvent: string,
+    } {
+      return {
+        selectedCarrierIds: [],
+        clearSelectedCarriersEvent: ProductEventMap.shipping.clearSelectedCarriers,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/carriers/CarrierSelector.vue]:
```suggestion
```
And you can also clean `clearSelectedCarriers` from the event map

File: admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue [hunk 15]
```diff
@@ -57,17 +56,22 @@
...
     name: 'Filters',
-    data(): {selectedFilters: Record<string, any>} {
+    data(): {
+      selectedFilters: Record<string, any>,
+      clearSelectedFiltersEvent: string,
+    } {
       return {
-        selectedFilters: {},
+        selectedFilters: [],
+        clearSelectedFiltersEvent: CombinationEvents.clearAllCombinationFilters,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue]:
```suggestion
```

File: admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue (hunk 12 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/components/filters/Filters.vue]: So you should also be able to clean `clearAllCombinationFilters` from the event map

File: admin-dev/themes/new-theme/js/pages/product/product-event-map.ts [hunk 16]
```diff
@@ -67,4 +67,7 @@ export default {
     listUpdated: 'specificPricesListUpdated',
   },
   cancelProductShops: 'cancelProductShops',
+  shipping: {
+    clearSelectedCarriers: 'clearSelectedCarriers',
+  },
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/product-event-map.ts]:
```suggestion
```

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/product-event-map.ts]: Along with `clearAllCombinationFilters` which should be useless now

**Review by jolelievre — COMMENTED** [review]
Thanks @zuk3975 

Nice you made it!! Not so simple to clean this Vue component.
Just a few comments about some stuff to clean but all good regardless

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue (hunk 13 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue:311]: stupid IDE changed too much things

File: admin-dev/themes/new-theme/js/app/widgets/ps-select.vue (hunk 7 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/app/widgets/ps-select.vue]: "too smart" IDE changed too much

File: admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue (hunk 13 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/components/dropzone/Dropzone.vue]: Thanks for noticing this! Again, IDE was too "smart" did too much :D Ill revert this, I was only intending to change in CheckboxesDropdown

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Comment by zuk3975** [comment]
@jolelievre tested it and said it works fine, but I still find it buggy. Sometimes its impossible to click on the checkbox because the component dropdown is "jumping around" :smile: 
Also I noticed, that "clear all" button doesn't trigger the change of form save button, I tried adding custom event for it but again some very strange behavior happens, the "save" button starts to flicker like if there is some infinite loop :sweat: 
Not sure what to do with this component, it sucks.

**Comment by zuk3975** [comment]
Added back custom all shops button, also type fixes and some other stuff, seems to work well now, but needs review again.

**Comment by zuk3975** [comment]
Rebased and noticed that all shops checkbox is always submitted with empty value, so it doesn't work the way it is now :sweat:

File: admin-dev/themes/new-theme/js/app/components/checkboxes-dropdown/CheckboxesDropdown.vue [hunk 17]
```diff
@@ -72,66 +71,52 @@
...
-    data(): {selectedFilters: Array<Record<string, any>>} {
-      return {
-        selectedFilters: [],
-      };
-    },
     props: {
       parentId: {
         type: Number,
-        required: true,
+        default: 1,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/app/components/checkboxes-dropdown/CheckboxesDropdown.vue:81]: If it's now an optional prop maybe it's default value should be falsy (0, null or false I don't know)

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue [hunk 18]
```diff
@@ -0,0 +1,186 @@
...
+    <div>
+      <div
+        v-if="modifyAllShopsVisible"
+        class="form-check form-check-radio form-checkbox"
+      >
+        <div
+          class="md-checkbox md-checkbox-inline"
+        >
+          <label class="required">
+            <input
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue]: We should discuss this, I still don't understand why it has to be inside this component In a previous state of your PR it was handled like any other field and it worked fine for me locally 🤔

File: admin-dev/themes/new-theme/js/pages/product/carrier/index.ts [hunk 19]
```diff
@@ -0,0 +1,88 @@
...
+      id: Number(input.value),
+      name: <string> input.name,
+      label: <string> label.textContent,
+    });
+
+    if (choiceInputName === '') {
+      // get the name of choice input which is important so that in backend side it is correctly filled in form when handling request
+      choiceInputName = input.name;
+    }
+  });
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/index.ts:74]: I'm almost sure all this part could be moved into the `mount` method of the Vue component, it would divide responsibilities a bit cleaner Optional though, but it would be a nice improvement, and a nice example for other Vue components, as much as possible I think the "init methods" should have as few intelligence as possible

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/carrier/index.ts:74]: From the Vue doc, seems like there are a few hooks/lifecyle events that could be used:
- setup
- beforeMount
- beforeCreate

These ones are, in theory, called before the initial element is replaced with the Vue base element So all the select options should still be unchanged and you could parse their info to set the data I guess

But again it's optional, no need to block this PR for this

File: admin-dev/themes/new-theme/js/pages/product/combination/filters/Filters.vue [hunk 20]
```diff
@@ -57,81 +57,109 @@
...
+  import CheckboxesDropdown from '@app/components/checkboxes-dropdown/CheckboxesDropdown.vue';
+  import EventEmitter from '@components/event-emitter';
+  import ProductEventMap from '@pages/product/product-event-map';
+  import ProductMap from '@pages/product/product-map';
+  import {Attribute, AttributeGroup} from '@pages/product/combination/types';
+  import {Choice} from '@app/components/checkboxes-dropdown/types';
 
   const CombinationEvents = ProductEventMap.combinations;
 
+  interface Filter {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/combination/filters/Filters.vue:70]: I wonder if this interface should be in `@app/components/checkboxes-dropdown/types` as well? Since it's kind of used to "drive" the dropdown component it maybe useful for other future usages as well?

**Review by jolelievre — COMMENTED** [review]
Just a few comments

File: admin-dev/themes/new-theme/js/pages/product/combination/filters/Filters.vue (hunk 20 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/combination/filters/Filters.vue:70]: hmm no, I see it as another implementation of dropdown component. So now we have the reusable dropdown component, which is implemented in 2 places - 1. carriers checkboxes dropdown and 2. combination filters dropdonws.

File: admin-dev/themes/new-theme/js/pages/product/carrier/index.ts (hunk 19 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/pages/product/carrier/index.ts:74]: I tried it just now, couldn't make it work. CarrierChoiceLabelElements are missing in all hooks (and in some of them like "setup" I also wasn't able to set data properties as they were not yet initialized probably) :man_shrugging:

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue [hunk 21]
```diff
@@ -0,0 +1,164 @@
...
+        this.selectedCarrierIds = this.selectedCarrierIds.filter(
+          (id: number) => carrier.id !== id,
+        );
+      },
+      clearAllSelected(): void {
+        this.selectedCarrierIds = [];
+        this.eventEmitter.emit(ProductEventMap.shipping.clearAllCarriers);
+        const carrierSelector = <HTMLDivElement> document.querySelector(ProductMap.shipping.carrierSelectorContainer);
+        // this event will allow modify_all_shops checkbox to stay visible after clearing all carriers
+        carrierSelector.dispatchEvent(new Event('change'));
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue]: I think this change event should be triggered by the select input, not the container div
And if this works maybe the `clearAllCarriers` will then become useless as we discussed

File: admin-dev/themes/new-theme/js/pages/product/carrier/index.ts (hunk 19 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/carrier/index.ts:74]: Ok no problem, it was worth testing ^^

**Review by jolelievre — COMMENTED** [review]
Thanks @zuk3975 

only one comment left about the way change event is triggered

File: admin-dev/themes/new-theme/js/app/components/checkboxes-dropdown/CheckboxesDropdown.vue (hunk 17 above)
Comment (zuk3975) [reply admin-dev/themes/new-theme/js/app/components/checkboxes-dropdown/CheckboxesDropdown.vue:81]: There is still some logic using elements based on parentId, so I didn't think its worth complicating things by changing this value and risking to break combination filters.

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue [hunk 22]
```diff
@@ -0,0 +1,170 @@
...
+    </div>
+  </div>
+</template>
+
+<script lang="ts">
+  import CheckboxesDropdown from '@app/components/checkboxes-dropdown/CheckboxesDropdown.vue';
+  import {defineComponent, PropType} from 'vue';
+  import {Choice} from '@app/components/checkboxes-dropdown/types';
+  import EventEmitter from '@components/event-emitter';
+  import ProductEventMap from '@pages/product/product-event-map';
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue]: You're gonna need to remove those two imports for ESlint

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue [hunk 23]
```diff
@@ -0,0 +1,170 @@
...
+  <div class="carrier-selector">
+    <div
+      class="form-check form-check-radio form-radio"
+    >
+      <div
+        class="carrier-selector-line"
+        v-if="carrierChoices.length"
+      >
+        <checkboxes-dropdown
+          :choices="carrierChoices"
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue:36]:
```suggestion
          id="carrierCheckboxesDropdown"
          :choices="carrierChoices"
```

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue [hunk 24]
```diff
@@ -0,0 +1,170 @@
...
+        this.selectedCarrierIds = this.selectedCarrierIds.filter(
+          (id: number) => carrier.id !== id,
+        );
+      },
+      clearAllSelected(): void {
+        const previouslySelectedCarrierIds = this.selectedCarrierIds;
+        this.selectedCarrierIds = [];
+        previouslySelectedCarrierIds.forEach((id: number) => {
+          const checkbox = <HTMLInputElement> document.querySelector(
+            `.carrier-selector .dropdown-item input[type="checkbox"][value="${id}"]`,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue]:
```suggestion
            `#carrierCheckboxesDropdown input[type="checkbox"][value="${id}"]`,
```

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue (hunk 23 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue:36]: or
```suggestion
          id="carrier-checkboxes-dropdown"
          :choices="carrierChoices"
```

File: admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.ts [hunk 25]
```diff
@@ -108,7 +108,11 @@ export default class ProductPartialUpdater {
     this.initialData = this.getFormDataAsObject();
     this.$productForm.submit(() => this.updatePartialForm());
     // 'dp.change' event allows tracking datepicker input changes
-    this.$productForm.on('keyup change dp.change', ':input', () => this.updateFooterButtonStates());
+    this.$productForm.on('keyup change dp.change',
+      // listen for all inputs except combination filters
+      `:input[name!="${ProductMap.combinations.list.attributeFilterInputName}"]`,
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-partial-updater.ts:113]: Hmm, this is weird though 🤔 Does it also mean the input from combination list trigger the product footer update?

File: admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue [hunk 26]
```diff
@@ -0,0 +1,173 @@
...
+    computed: {
+      selectedCarriers(): Choice[] {
+        return this.carrierChoices.filter((carrier: Choice) => this.selectedCarrierIds.includes(carrier.id));
+      },
+      getLabel(): string {
+        return this.selectedCarrierIds.length > 0
+          ? this.$t('selectedCarriers.label')
+          : this.$t('allCarriers.label');
+      },
+      checkboxesDropdownId(): string {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/product/carrier/CarrierSelector.vue:122]: Oh nice idea to use a computed for this!

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Review by mflasquin — DISMISSED** [review]
Seems ok, what a big job @zuk3975 :smile: 
Just one question, wouldn't it be a BC break to change some classes on elements ?
For example :

image

**Comment by zuk3975** [comment]
> Seems ok, what a big job @zuk3975 smile Just one question, wouldn't it be a BC break to change some classes on elements ? For example :
> 
> image

hmm I don't know actually (maybe :smile: ), but in any case, this was only introduced in experimental product page (for combinations filtering), so it doesn't count as BC break I think

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @zuk3975 

I have checked your PR. Here is my feedback : 

- Issue #31424 is fixed :heavy_check_mark: 


image

- Issue #31417 is fixed :heavy_check_mark: 


image

- Issue #30121 is OK but there is an empty space that is not displayed in the template


**With PR :** 
image

**Template :** 
image


- But the new Available carriers section is well added 

image

- Check with multistore : OK :heavy_check_mark: 

- Also, the automated tests  failed in product V2 tests.

https://github.com/HanaRebaiQA/testing_pr/actions/runs/4424648222

I have launched the failed job many times. ping @PrestaShop/qa-automation What do you think? is it related to this PR ?

Could you please check and give me your feedback ?


Thank You!

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by zuk3975** [comment]
fixed selected carriers padding (aligned with the all-shops checkbox).
image

**Review by jolelievre — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
UI tests => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/4435417846

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @zuk3975 , 
LGTM , the issue is well fixed :heavy_check_mark:  

[Untitled_ Mar 22, 2023 12_04 PM.webm](https://user-images.githubusercontent.com/115152460/226885694-7381cd5d-33f0-42c5-8a7d-bdb7e75287f4.webm)

image

It's QA approved  :rocket: 
thank you !

**Comment by jolelievre** [comment]
Thanks @zuk3975 and @djoelleuch
