### PR TITLE
Fix images for objects without name or rewrite

### LINKED ISSUE #27757: All images on shop stop working due to missing rewrites
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If your products do not have link rewrite and a name, all product images stop working and their URL looks like this: `http://example.com/33-home_default/.jpg`.

### Expected behavior

There should be a fallback if there is no rewrite.

Steps to reproduce the issue 
Install Ps with English language & France country 

1. Create a product > upload an image & enable it
2. Don't click on the preview button & don't click on save again
3. Go to FO > Search this product & select french language 
4. See an error 
5. Same issue in the list page 

I attached a screen record

https://user-images.githubusercontent.com/16067358/155131003-f649f167-149d-4c28-be8b-098e611cfe0b.mp4

---------------------------------------------------------------------------------------

**UDPATE: I cannot reproduce it this way for a second time. :(**

1. Install Prestashop.
2. Add new language, enable it.
3. Go to front office and switch to this language.
4. See no images.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #30058: Unnamed images for other languages
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

For some reason, 

When creating a new product in BO:
the productimages only appear for the default language (dutch), most of the time for the English, Deutsch and Spanish language. Sometimes only in Dutch.
When uploading images by CSV images, images for all languages work just fine.
All migrated products (from Prestashop 1.6, using Migration Pro module) only have in Dutch and English the images (that languages were already on our old shop). The new languages doesn't have the images.

It is only frontoffice. Backoffice no problems.
For example: 

I already searched in the database, but all looks fine. I don't see any differences between the languages.

### Expected behavior

the productimages should all have the same name, as they are using the same image.

### Steps to reproduce

1. create product
2. save product
3. check on front end.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | If a product does not have `link _rewrite` or a `name`, it didn't work because of wrong URL. I use image ID as a fallback. Also, changed `isset` to `!empty` and renamed some variables to make it more understandable.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Resolves #27757, Resolves #30058
| How to test?      | Make a product, set name and link_rewrite in ps_product_lang to empty strings, check in FO that no images for that product are working. I managed to somehow reproduce a scenario where language addition failed and there was no data for single language, and whole shop was without images.
| Possible impacts? | No

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27758)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

File: src/Adapter/Image/ImageRetriever.php [hunk 1]
```diff
@@ -203,7 +203,7 @@ public function getImage($object, $id_image)
             }
 
             $url = $this->link->$getImageURL(
-                isset($object->link_rewrite) ? $object->link_rewrite : $object->name,
+                !empty($object->link_rewrite) ? $object->link_rewrite : (!empty($object->name) ? $object->name : $id_image),
```
Comment (saulaski) [inline src/Adapter/Image/ImageRetriever.php]: Nothing really wrong here, just a bit overcomplicated to chain ternary operators this way.
Functional cases are usually better suited in a good old `if` structure.

**Review by saulaski — APPROVED** [review]

File: src/Adapter/Image/ImageRetriever.php (hunk 1 above)
Comment (Progi1984) [reply src/Adapter/Image/ImageRetriever.php]:
```suggestion
                $object->link_rewrite ?: $object->name ?: $id_image,
```

**Review by Progi1984 — COMMENTED** [review]
I have a small suggestion with the elvis operator :man_singer:

**Review by matthieu-rolland — COMMENTED** [review]
waiting for @Progi1984 's feedback to be applied, LGTM otherwise 👍

File: src/Adapter/Image/ImageRetriever.php (hunk 1 above)
Comment (saulaski) [reply src/Adapter/Image/ImageRetriever.php]: @Progi1984 Unfortunately chained ternary operators can't handle undefined properties and might crash. Did you mean this ?
```suggestion
                $object->link_rewrite ?? $object->name ?? $id_image
```
This last suggestion can't handle tricky cases either, like empty strings.
IMHO there is no way to replace empty tests with chained operators, because `empty()` can handle both undefined and falsey values.
That's why I suggested if/else structure to handle each functional case only to improve readibility.

Comment (Progi1984) [reply src/Adapter/Image/ImageRetriever.php]: Oh yeah ! I don't think.

@Hlavtox Use @saulaski solution ;)

**Review by matks — CHANGES_REQUESTED** [review]
I agree with @saulaski too 👍

**Comment by Hlavtox** [comment]
@matks @saulaski @Progi1984 I don't understand which solution you want me to implement. :-)

But I guess my original one did work properly?

File: src/Adapter/Image/ImageRetriever.php (hunk 1 above)
Comment (saulaski) [reply src/Adapter/Image/ImageRetriever.php]: @Hlavtox We mean the code should be easier to read, no fancy syntax required :)
Something like this:
```suggestion
            if (!empty($object->link_rewrite)) {
                $imageName = $object->link_rewrite;
            } elseif (!empty($object->name) {
                $imageName = $object->name;
            } else {
                $imageName = $id_image;
            }
            $url = $this->link->$getImageURL(
                $imageName,
```

**Review by saulaski — CHANGES_REQUESTED** [review]

**Comment by kpodemski** [comment]
Hey @Hlavtox 

@saulaski had a great suggestion to make this code more readable. What do you think? let's try to unblock this PR as it is pretty straightforward to test and merge 👍

**Comment by matks** [comment]
> Hey @Hlavtox
> 
> @saulaski had a great suggestion to make this code more readable. What do you think? let's try to unblock this PR as it is pretty straightforward to test and merge 👍

Friendly reminder @Hlavtox 😄

**Comment by Hlavtox** [comment]
Hello @saulaski, @matks, @Progi1984, @kpodemski

I implemented the simplier solution as you requested, added some comments and renamed some small things to make it more clear. Ready for review 👍

**Comment by Progi1984** [comment]
@Hlavtox Please ping @PrestaShop/prestashop-maintainers

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Hlavtox** [comment]
@hibatallahAouadni @sallemiines Ping for QA please, it has been more than 40 days 😐

**Comment by sallemiines** [comment]
Hello @Hlavtox !

The issue is solved :+1: 

https://user-images.githubusercontent.com/31663369/199719645-0c478d38-49e9-40a2-a6f5-2ed648bf999b.mp4

Thank you ! :rocket:

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @Hlavtox and @sallemiines
