### PR TITLE
Install module CQRS command

### LINKED ISSUE #36975: Admin API - Install module

### LINKED ISSUE #37253: Modules Page is not up to date after disabling/enabling a module with API
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

* I enable / disable a module with API
* The BO is not synced with modules states

### Expected behavior

* I enable / disable a module with API
* The BO is synced with modules states

### Steps to reproduce

1. Go to BO
2. Go to Modules
3. Check that `blockwishlist` is enabled
4. Create a API key (scope : `module_write`) 
5. Request an access_token
6. Request the endpoint for disabling the module (Response 🆗 )
Image
Image

7. Refresh the BO
8. The module `blockwishlist` is always enabled

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by sullivan-monteiro**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Install module CQRS command
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/11708705964
| Fixed issue or discussion?     | Fixes #36975 and Fixes #37253
| Related PRs       | https://github.com/PrestaShop/ps_apiresources/pull/37
| Sponsor company   | ~

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hello @sullivan-monteiro!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

File: src/Adapter/Module/CommandHandler/InstallModuleHandler.php [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+        protected ModuleManager $moduleManager,
+        protected ModuleRepository $moduleRepository,
+    ) {
+    }
+
+    public function handle(InstallModuleCommand $command): void
+    {
+        $technical_name = $command->getTechnicalName()->getValue();
+
+        $result = $this->moduleManager->install($technical_name);
```
Comment (jolelievre) [inline src/Adapter/Module/CommandHandler/InstallModuleHandler.php]: I don't think we need a tmp variable, the data is already accessible from the command it could only use additional memory for no advantage
```suggestion
        $result = $this->moduleManager->install($command->getTechnicalName()->getValue());
```

File: src/Adapter/Module/CommandHandler/InstallModuleHandler.php [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+{
+    public function __construct(
+        protected ModuleManager $moduleManager,
+        protected ModuleRepository $moduleRepository,
+    ) {
+    }
+
+    public function handle(InstallModuleCommand $command): void
+    {
+        $technical_name = $command->getTechnicalName()->getValue();
```
Comment (jolelievre) [inline src/Adapter/Module/CommandHandler/InstallModuleHandler.php]: Before installing the module you should get the module from the repository (not using getPresentModule or it could trigger a not found exception), and check if it is already installed, you shouldn't install a module that is already installed
```php
        $module = $this->moduleRepository->get($command->getTechnicalName()->getValue());
        if ($module->isInstalled()) {
            throw new CannotInstallModuleException('Cannot install a module already installed', CannotInstallModuleException::ALREADY_INSTALLED);
        }
```

If the module is installed but its DB version doesn't match the disk version then the action to perform should be Update not Install (in update command handler we'll have to remember checking that the update action makes sense as well)

File: src/Adapter/Module/CommandHandler/UploadModuleHandler.php [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+    ) {
+    }
+
+    public function handle(UploadModuleCommand $command): void
+    {
+        try {
+            $technical_name = $command->getTechnicalName()->getValue();
+            $source = $command->getSource();
+
+            $this->moduleManager->upload($technical_name, $source);
```
Comment (jolelievre) [inline src/Adapter/Module/CommandHandler/UploadModuleHandler.php]:
```suggestion
            $this->moduleManager->upload($command->getTechnicalName()->getValue(), $command->getSource());
```

File: src/Adapter/Module/QueryHandler/GetModuleInfosHandler.php [hunk 4]
```diff
@@ -51,7 +51,7 @@ public function handle(GetModuleInfos $query): ModuleInfos
             $module->get('name'),
             $module->get('version'),
             $module->isActive(),
-            $module->isInstalled(),
+            $module->IsInstalled(),
```
Comment (jolelievre) [inline src/Adapter/Module/QueryHandler/GetModuleInfosHandler.php]:
```suggestion
            $module->isInstalled(),
```

File: src/Adapter/Module/CommandHandler/UploadModuleHandler.php [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+        protected ModuleRepository $moduleRepository,
+    ) {
+    }
+
+    public function handle(UploadModuleCommand $command): void
+    {
+        try {
+            $technical_name = $command->getTechnicalName()->getValue();
+            $source = $command->getSource();
+
```
Comment (jolelievre) [inline src/Adapter/Module/CommandHandler/UploadModuleHandler.php]:
```suggestion
```

File: src/Adapter/Module/CommandHandler/InstallModuleHandler.php [hunk 6]
```diff
@@ -0,0 +1,55 @@
...
+
+        $result = $this->moduleManager->install($technical_name);
+
+        if (!$result) {
+            throw new CannotInstallModuleException('Technical error occurred while installing module.');
```
Comment (jolelievre) [inline src/Adapter/Module/CommandHandler/InstallModuleHandler.php:56]: We're gonna need exception codes to identify the different errors that can happen, or we can decide to create individual dedicated exception classes as you prefer
```suggestion
            throw new CannotInstallModuleException('Technical error occurred while installing module.', CannotInstallModuleException::TECHNICAL_ERROR);
```

File: src/Adapter/Module/CommandHandler/InstallModuleHandler.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/Module/CommandHandler/InstallModuleHandler.php]: Ah you already introduced a dedicated `AlreadyInstalledModuleException` (which is triggered nowhere btw), you can use this one if you prefer that instead of using code

File: src/Core/Module/ModuleManager.php [hunk 7]
```diff
@@ -90,6 +90,22 @@ public function __construct(
         $this->hookManager = $hookManager;
     }
 
+    public function upload(string $name, string $source): void
+    {
+        if (!$this->adminModuleDataProvider->isAllowedAccess(__FUNCTION__)) {
```
Comment (jolelievre) [inline src/Core/Module/ModuleManager.php:95]: Ok to use this, but then you need to update the `PrestaShop\PrestaShop\Adapter\Module\AdminModuleDataProvider` to handle this fully The `isAllowedAccess` logic is based on the passed parameter which represents the action, here it would be `upload`

So far it didn't know the upload action, but it seems logical that it behaves the same as the action to install and upgrade so you should update this line:
https://github.com/PrestaShop/PrestaShop/blob/eff832703974bcef13b7ab7ad168a36c7348a48c/src/Adapter/Module/AdminModuleDataProvider.php#L172-L174

File: src/Core/Module/ModuleManager.php [hunk 8]
```diff
@@ -90,6 +90,22 @@ public function __construct(
         $this->hookManager = $hookManager;
     }
 
+    public function upload(string $name, string $source): void
```
Comment (jolelievre) [inline src/Core/Module/ModuleManager.php]: I believe we discussed this but it seems the `$name` is not useful here, so if it's not used at all it should be removed (and also in the CQRS command)

Unless we decide to use it for module validation as we discussed quickly?

File: tests/Integration/Behaviour/Features/Scenario/Module/module.feature [hunk 9]
```diff
@@ -104,6 +104,33 @@ Feature: Module
     When I uninstall module "ps_featuredproducts" with deleteFile false
     Then I should have an exception that module is not installed
 
+  Scenario: Install module
+    When I install module "ps_featuredproducts"
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Module/module.feature]:
```suggestion
    Given module ps_featuredproducts has following infos:
      | technical_name | ps_featuredproducts |
      | version        | 1.0.0               |
      | enabled        | false                |
      | installed      | false               |
    When I install module "ps_featuredproducts"
```
This is a bit redundant because the module was uninstalled in the previous scenario, it means scenarios in this feature are co-dependent We try to avoid this to keep scenarios as independent as possible but I'd say in this case we can make an exception and it makes sense That said it doesn't hurt to emphasize what is the expected beginning status of the module before we use the install action

File: tests/Integration/Behaviour/Features/Scenario/Module/module.feature [hunk 10]
```diff
@@ -104,6 +104,33 @@ Feature: Module
...
+    Then module ps_featuredproducts has following infos:
+      | technical_name | ps_featuredproducts  |
+      | version        | 1.0.0                |
+      | enabled        | true                 |
+      | installed      | true                 |
+
+  Scenario: Upload module with zip file on disk
+    When I upload module "test_install_cqrs_command" from "zip" "test_install_cqrs_command.zip"
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Module/module.feature]: I guess you are using a module that doesn't exist yet right? If so please check that the module is not present before uploading the file You can do so by using the "module has following infos" step and assert that it triggers a ModuleNotFoundException

Once this is asserted you can upload the zip, by the way since I guess you created the zip manually can you make it so it doesn't have a `1.0.0` version, just to make sure it reads the new version correctly from the extracted archive and not as a default value

Then before the module is installed you should check that it is now present (you don't get a ModuleNotFoundException) but is not installed

File: tests/Integration/Behaviour/Features/Scenario/Module/module.feature [hunk 11]
```diff
@@ -104,6 +104,33 @@ Feature: Module
...
+      | enabled        | true                      |
+      | installed      | true                      |
+
+  Scenario: Upload module with zip file on remote
+    When I uninstall module "ps_featuredproducts" with deleteFile true
+    And I upload module "ps_featuredproducts" from "url" "https://github.com/PrestaShop/ps_featuredproducts/releases/download/v2.1.4/ps_featuredproducts.zip"
+    And I install module "ps_featuredproducts"
+    Then module ps_featuredproducts has following infos:
+      | technical_name | ps_featuredproducts |
+      | version        | 1.0.0               |
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Module/module.feature]:
```suggestion
      | version        | 2.1.4               |
```
If you download the zip for 2.1.4 then it should be the expected version after installation

File: tests/Integration/Behaviour/Features/Scenario/Module/module.feature (hunk 10 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Module/module.feature]: I'm thinking this PR could be the proper moment to enrich the `GetModuleInfos` command so we return additional versions, for now I can only think about:
- database version (the version in DB representing the last installed version)
- disk version (the version in the files representing the last uploaded zip)

File: src/Adapter/Module/CommandHandler/InstallModuleHandler.php [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+        protected ModuleManager $moduleManager,
+        protected ModuleRepository $moduleRepository,
+    ) {
+    }
+
+    public function handle(InstallModuleCommand $command): void
+    {
+        $module = $this->moduleRepository->getModule($command->getTechnicalName()->getValue());
+        if ($module->isInstalled()) {
+            throw new AlreadyInstalledModuleException('Cannot install a module already installed', CannotInstallModuleException::ALREADY_INSTALLED);
```
Comment (jolelievre) [inline src/Adapter/Module/CommandHandler/InstallModuleHandler.php]: It's easier we use a code to specify the error more accurately or we use dedicated exception for each error Here you are mixing both, when an exception relies on specific const for code values these const must be in the Exception itself because they only make sense for this specific exception

Comment (jolelievre) [reply src/Adapter/Module/CommandHandler/InstallModuleHandler.php]:
```suggestion
            throw new AlreadyInstalledModuleException('Cannot install a module already installed');
```
or
```suggestion
            throw new CannotInstallModuleException('Cannot install a module already installed', CannotInstallModuleException::ALREADY_INSTALLED);
```

File: src/Core/Domain/Module/Command/UploadModuleCommand.php [hunk 13]
```diff
@@ -0,0 +1,73 @@
...
+    /**
+     * @var string|null
+     */
+    private $source;
+
+    /**
+     * @param string $technicalName Technical name for module
+     * @param string $source source for module
+     */
+    public function __construct(string $technicalName, ?string $source = null)
```
Comment (jolelievre) [inline src/Core/Domain/Module/Command/UploadModuleCommand.php]:
```suggestion
    public function __construct(string $technicalName, string $source)
```
Are you sure the source is optional? How can we upload an empty source?

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Modules.Notification`
    - [ ] `You are not allowed to upload modules.`

(Note: this is an automated message, but answering it will reach a real human)

File: src/Adapter/Module/CommandHandler/InstallModuleHandler.php (hunk 12 above)
Comment (sullivan-monteiro) [reply src/Adapter/Module/CommandHandler/InstallModuleHandler.php]: I use the first one

File: src/Core/Domain/Module/Command/UploadModuleCommand.php (hunk 13 above)
Comment (sullivan-monteiro) [reply src/Core/Domain/Module/Command/UploadModuleCommand.php]: i remove the optional property of the parameter

File: tests/Integration/Behaviour/Features/Scenario/Module/module.feature (hunk 11 above)
Comment (sullivan-monteiro) [reply tests/Integration/Behaviour/Features/Scenario/Module/module.feature]: We have a problem in this part. When we launch the test, we have 1.0.0 on the information but, with the API, we have the correct 2.1.4

**Review by jolelievre — DISMISSED** [review]
Thanks @sullivan-monteiro

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]
Ok for UI Tests
