### PR TITLE
BO > Customers > Addresses - Required fields are not used in back office

### LINKED ISSUE #28848: BO > Customers > Addresses - Required fields are not used in back office
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When applying required fields for addresses they are not used in the BO

### Expected behavior

Use the required fields like : 

https://user-images.githubusercontent.com/5064590/175557925-ebfe5aa9-09ac-4232-affd-0765cf7f4a7e.mp4

### Steps to reproduce

1 ) Set required fields in back office for address
2 ) Edit an address from back office and see you can add or adit an adresse without required field

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | BO > Customers > Addresses - Required fields are not used in back office, an employe can add address with missing field
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28848.
| Related PRs       | 
| How to test?      | See issue
| Possible impacts? | 

https://user-images.githubusercontent.com/5064590/175557925-ebfe5aa9-09ac-4232-affd-0765cf7f4a7e.mp4

### CODE REVIEW

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+    {
+        $this->queryBus = $queryBus;
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    public function getOptions(int $id, array $data): array
+    {
+        return ['requiredFields' => $this->queryBus->handle(new GetRequiredFieldsForAddress())];
```
Comment (kpodemski) [inline src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: @okom3pom you can move it to the new property

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 2]
```diff
@@ -138,7 +139,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'The national ID card number of this person, or a unique tax identification number.',
                 'Admin.Orderscustomers.Feature'
             ),
-            'required' => false,
+            'required' => in_array('dni', $requiredFields) ? true : false,
```
Comment (kpodemski) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
            'required' => in_array('dni', $requiredFields),
```

should be enough because `in_array` returns boolean

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php (hunk 1 above)
Comment (ghost) [reply src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: @kpodemski I'm not sure I understand. Can you explain it to me? Thank you in advance

Comment (matthieu-rolland) [reply src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: @kpodemski did you mean doing `$this->queryBus->handle(new GetRequiredFieldsForAddress())]` in the constructor and setting the result in a class property ?

**Review by matthieu-rolland — COMMENTED** [review]
Looks good to me, waiting for precisions about Krystian's comment before approving 👍

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php (hunk 1 above)
Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: @matthieu-rolland yes

Comment (zuk3975) [inline src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: I think its worth reusing single private method in both public methods
```suggestion
        return $this->getRequiredFields();
```
And add new method
```
    private function getRequiredFields(): array
    {
        return ['requiredFields' => $this->queryBus->handle(new GetRequiredFieldsForAddress())];
    }
```

**Comment by zuk3975** [comment]
Maybe we could use this occasion to unit test the CustomerAddressFormOptionsProvider? It will require mocking query handler, but shouldn't be a problem.

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php [hunk 3]
```diff
@@ -43,27 +43,33 @@ class CustomerAddressFormOptionsProvider implements FormOptionsProviderInterface
...
+     */
+    private $requiredFields;
+
     /**
      * @param CommandBusInterface $queryBus
      */
     public function __construct(CommandBusInterface $queryBus)
     {
         $this->queryBus = $queryBus;
+        $this->requiredFields = $this->queryBus->handle(new GetRequiredFieldsForAddress());
```
Comment (zuk3975) [inline src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: thats not what I meant.
Just create a private method so you can reuse the whole line (including the 'requiredFields' array key). So like this:
```
    private function getRequiredFieldsOption(): array
    {
        return ['requiredFields' => $this->queryBus->handle(new GetRequiredFieldsForAddress())];
    }
```

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php [hunk 4]
```diff
@@ -43,27 +43,33 @@ class CustomerAddressFormOptionsProvider implements FormOptionsProviderInterface
...
     }
 
     /**
      * {@inheritDoc}
      */
     public function getOptions(int $id, array $data): array
     {
-        return ['requiredFields' => $this->queryBus->handle(new GetRequiredFieldsForAddress())];
+        return ['requiredFields' => $this->requiredFields];
```
Comment (zuk3975) [inline src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: and then just use that here
```
return $this->getRequiredFieldsOption();
```

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php [hunk 5]
```diff
@@ -43,27 +43,33 @@ class CustomerAddressFormOptionsProvider implements FormOptionsProviderInterface
...
     }
 
     /**
      * {@inheritDoc}
      */
     public function getDefaultOptions(array $data): array
     {
-        return ['requiredFields' => $this->queryBus->handle(new GetRequiredFieldsForAddress())];
+        return ['requiredFields' => $this->requiredFields];
```
Comment (zuk3975) [inline src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: and here
```
return $this->getRequiredFieldsOption();
```

File: src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php (hunk 3 above)
Comment (ghost) [reply src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: Hi @zuk3975 I understand what you mean but @kpodemski  asks me for this way. 

I don't know which one is better?

https://github.com/PrestaShop/PrestaShop/pull/29114#discussion_r925974517

Thank for your time

Comment (zuk3975) [reply src/Core/Form/IdentifiableObject/OptionProvider/CustomerAddressFormOptionsProvider.php]: @kpodemski could you elaborate why you would want to do that? I don't think its the right way :thinking:

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 6]
```diff
@@ -138,7 +139,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 'The national ID card number of this person, or a unique tax identification number.',
                 'Admin.Orderscustomers.Feature'
             ),
-            'required' => false,
+            'required' => in_array('dni', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
            'required' => in_array('dni', $requiredFields, true),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 7]
```diff
@@ -236,7 +237,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ->add('company', TextType::class, [
                 'label' => $this->trans('Company', 'Admin.Global'),
                 'help' => $genericInvalidCharsMessage,
-                'required' => false,
+                'required' => in_array('company', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
                'required' => in_array('company', $requiredFields, true),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 8]
```diff
@@ -255,7 +256,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('vat_number', TextType::class, [
                 'label' => $this->trans('VAT number', 'Admin.Orderscustomers.Feature'),
-                'required' => false,
+                'required' => in_array('vat_number', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
                'required' => in_array('vat_number', $requiredFields, true),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 9]
```diff
@@ -297,7 +298,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('address2', TextType::class, [
                 'label' => $this->trans('Address (2)', 'Admin.Global'),
-                'required' => false,
+                'required' => in_array('address2', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
                'required' => in_array('address2', $requiredFields, true),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 10]
```diff
@@ -396,7 +397,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 ],
             ])->add('phone', TextType::class, [
                 'label' => $this->trans('Phone', 'Admin.Global'),
-                'required' => false,
+                'required' => in_array('phone', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
                'required' => in_array('phone', $requiredFields, true),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 11]
```diff
@@ -415,7 +416,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             ])
             ->add('phone_mobile', TextType::class, [
                 'label' => $this->trans('Mobile phone', 'Admin.Global'),
-                'required' => false,
+                'required' => in_array('phone_mobile', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
                'required' => in_array('phone_mobile', $requiredFields, true),
```

File: src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php [hunk 12]
```diff
@@ -432,7 +433,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                 ],
             ])
             ->add('other', TextareaType::class, [
-                'required' => false,
+                'required' => in_array('other', $requiredFields),
```
Comment (FabienPapet) [inline src/PrestaShopBundle/Form/Admin/Sell/Address/CustomerAddressType.php]:
```suggestion
                'required' => in_array('other', $requiredFields, true),
```

**Comment by FabienPapet** [comment]
Some minor changes needed IMO to enable strictness comparaison in [in_array()](https://www.php.net/manual/en/function.in-array.php)

**Comment by zuk3975** [comment]
by the way (sorry I might just be missing something) isn't this PR missing changes in address controller?
As I see address controller also calls the handler to get the fields :thinking: (maybe thats what you meant @kpodemski when referring multiple queries to get required fields?)

**Nevermind**, its all good. The options I mentioned are passed in controller, because its for the form in index page (the requried fields form). And that one doesn't have a form builder so all of those options are retrieved and passed in controller.

**Review by FabienPapet — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by zuk3975 — APPROVED** [review]

**Comment by ghost** [comment]
Thank you @zuk3975

**Review by kpodemski — APPROVED** [review]

**Review by marwachelly — APPROVED** [review]
Hello @okom3pom,

PR is tested and the issue is well fixed. The automatic tests are OK 

https://user-images.githubusercontent.com/89604350/183879931-fbd56068-7285-4202-9bf2-3dcc111d094a.mp4

PR is QA approved :heavy_check_mark: 

Thanks,

**Review by FabienPapet — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @marwachelly and @okom3pom
