### PR TITLE
Fix free shipping cart rule should not be recalculate when PS_ORDER_RECALCULATE_SHIPPING is false

### LINKED ISSUE #24598: BO - Orders -Prices are not well calculated when Recalculate shipping costs option is set to NO
#### Describe the bug

When setting the "Recalculate shipping costs after editing the order" option to No, the shipping cost are not recalculated when editing the order in BO when the price of the order exceeds the carrier's "limit", but the discount free shipping is recalculated  

#### Steps to Reproduce

1. Have a carrier set up with a fee below a certain amount/weight, free above it (in my case, I used `My cheap carrier)`
2. Create a cart rule Free shipping
3. Go to BO > Shop Parameters > Order Settings
4. Set "Recalculate shipping costs after editing the order" to No
5. On FO, make an order with this carrier, under the limit amount (50€)
6. Select My cheap carrier as a shipping method
7. Go to BO > Orders > Last Order created > generate an ivoice
8. EDit the quantity of the product to `2`
9. See error: `An unexpected error occurred. [Symfony\Component\Debug\Exception\ContextErrorException code 0]: Notice: Undefined property: OrderInvoice::$total_paid`, 
10. Refresh the page =>  discount is updated => it shouldn't: the total is NOK, invoice NOK

**Screenshots**
177x(1775): https://drive.google.com/file/d/1X_sx3j52QflnmnsCIdooilhbX490dWUN/view?usp=sharing
1769 => ok: https://drive.google.com/file/d/1PpYOxC8o-O11akUTSb3DWCZ_E432PTyH/view?usp=sharing

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2, 7.4

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | When a modification is done on the order, cart rules are recalculate but the option PS_ORDER_RECALCULATE_SHIPPING was not take into account when doing so. This PR fixes it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24598
| How to test?      | Please see #24598
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24679)

### CODE REVIEW

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 1]
```diff
@@ -309,16 +309,31 @@ private function updateOrderTotals(Order $order, Cart $cart, int $computingPreci
...
         if (!$this->getOrderConfiguration('PS_ORDER_RECALCULATE_SHIPPING', $order)) {
-            $shippingDiffTaxIncluded = $order->total_shipping_tax_incl - $totalShippingTaxIncluded;
-            $shippingDiffTaxExcluded = $order->total_shipping_tax_excl - $totalShippingTaxExcluded;
+            $freeShipping = false;
+            foreach ($order->getCartRules() as $cartRule) {
+                if ($cartRule['free_shipping']) {
+                    $freeShipping = true;
+                    break;
+                }
+            }
```
Comment (PierreRambaud) [inline src/Adapter/Order/OrderAmountUpdater.php]:
```suggestion
            $freeShipping = $this->isFreeShipping($order);
```

You can create a method
```php
    protected function isFreeShipping(Order $order): bool
    {
        foreach ($order->getCartRules() as $cartRule) {
            if ($cartRule['free_shipping']) {
                return true;
            }
        }

        return false;
    }
```

to prevent, duplicate

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 2]
```diff
@@ -567,6 +588,22 @@ private function updateOrderInvoices(Order $order, Cart $cart, int $computingPre
         }
     }
 
+    /**
+     * @param Order $order
+     *
+     * @return bool
+     */
+    protected function isFreeShipping(Order $order)
```
Comment (Progi1984) [inline src/Adapter/Order/OrderAmountUpdater.php]:
```suggestion
    protected function isFreeShipping(Order $order): bool
```

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 3]
```diff
@@ -549,16 +564,22 @@ private function updateOrderInvoices(Order $order, Cart $cart, int $computingPre
...
                 $invoice->total_shipping_tax_excl = $totalShippingTaxExcluded;
 
-                $invoice->total_paid -= $shippingDiffTaxIncluded;
-                $invoice->total_paid_tax_incl -= $shippingDiffTaxIncluded;
-                $invoice->total_paid_tax_excl -= $shippingDiffTaxExcluded;
+                if (!$freeShipping) {
+                    $shippingDiffTaxIncluded = $invoice->total_shipping_tax_incl - $totalShippingTaxIncluded;
+                    $shippingDiffTaxExcluded = $invoice->total_shipping_tax_excl - $totalShippingTaxExcluded;
+                    $invoice->total_paid_tax_incl -= $shippingDiffTaxIncluded;
+                    $invoice->total_paid_tax_excl -= $shippingDiffTaxExcluded;
```
Comment (Progi1984) [inline src/Adapter/Order/OrderAmountUpdater.php]:
```suggestion
                    $invoice->total_paid_tax_incl -= ($invoice->total_shipping_tax_incl - $totalShippingTaxIncluded);
                    $invoice->total_paid_tax_excl -= ($invoice->total_shipping_tax_excl - $totalShippingTaxExcluded);
```

**Review by Progi1984 — COMMENTED** [review]
Small feedbacks

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an issue following these steps:

1. Have a carrier set up with a fee below a certain amount/weight, free above it (in my case, I used My cheap carrier)
2. Create a cart rule Free shipping
3. Go to BO > Shop Parameters > Order Settings
4. Set "Recalculate shipping costs after editing the order" to No
5. On FO, make an order with this carrier, under the limit amount (50€) with John Doe
6. Select My cheap carrier as a shipping method
7. Go to BO > Orders > Last Order created
8. Try to change the Shipping Address and select `My Adress (United States)`
9. See an error
10. The discount value is NOK
image
11. Try to change the product quantity to 10
12. See error: the discount value is updated
image
13. Generate an invoice
14. See error, the discount block is NOK
image

Thank you!

**Review by jolelievre — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
I check these tests:
Recalculate shipping costs option **enabled**:
1. Update quantity product
2. Change Address
3. Change carrier
4. Add/Remove product
5. Change Currency

Recalculate shipping costs option **disabled**:
1. Update quantity product
2. Change Address /Edit Adress
3. Change carrier
4. Add/Remove product
5. Change currency

https://drive.google.com/file/d/1M13_pna0EIKOo43g-pEdaBiF71AorTPs/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
