### PR TITLE
Fix: Error when creating an attribute for a group in “All shops” context with multiple shops

### LINKED ISSUE #40705: Error when creating an attribute for a group in “All shops” context with multiple shops
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using a multi-shop setup with two shops, an error occurs when creating an attribute for a group while the shop context is set to **All shops**.

The attribute creation fails and the operation cannot be completed in this context. Switching to a single shop context allows the attribute to be created correctly.

An attached video is provided to show the issue.

https://github.com/user-attachments/assets/484fc264-f7e8-4547-b78f-a22e0fa23a73

### Expected behavior

_No response_

### Steps to reproduce

1. Create 2 shops
2. Go to **Attributes & Features > Attributes**
3. Select an attribute group
4. Select the **All stores** context
5. Try to add a new attribute

### PrestaShop version(s) where the bug happened

9.0.2

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

_No response_

### Your company or customer's name goes here (if applicable).

Codencode snc

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | This PR fixes an issue in AttributeGroupChoiceProvider where the service could receive a `null` shop ID in valid contexts (e.g. _All shops_ or back office initialization).<br/><br/>The service definition now resolves the shop ID by:<br/>- using the modern shop context when available<br/>- falling back to the legacy context when the shop context is `null`<br/>This prevents type errors and ensures consistent behavior across all shop contexts.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Create 2 shops<br/>2. Go to **Attributes & Features > Attributes**<br/>3. Select an attribute group<br/>4. Select the **All stores** context<br/>5. You must be able to add the attribute without errors.
| UI Tests          |  🟢 https://github.com/Codencode/ga.tests.ui.pr/actions/runs/21871395698
| Fixed issue or discussion?     | Fixes #40705
| Related PRs       | 
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by Codencode** [comment]
@jolelievre 
I created a new PR so I could rename the branch as you suggested.

I created the `findByLangForAllShops` method and passed the entire `Context`.

What do you think? Is it okay?

File: src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php [hunk 1]
```diff
@@ -54,12 +55,12 @@ final class AttributeGroupChoiceProvider implements FormChoiceProviderInterface,
...
      * @param AttributeGroupRepository $attributeGroupRepository
      * @param int $langId
-     * @param int $shopId
+     * @param context $context
      */
     public function __construct(
         private readonly AttributeGroupRepository $attributeGroupRepository,
         private readonly int $langId,
-        private readonly int $shopId,
+        private Context $context,
```
Comment (jolelievre) [inline src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: Sorry, I wasn't clear enough, this context is an old implementation (that we should deprecate one day probably)

I was talking about the recent new context services so `PrestaShop\PrestaShop\Core\Context\ShopContext`

Comment (Codencode) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: @jolelievre done.

File: src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php [hunk 2]
```diff
@@ -96,7 +97,14 @@ private function setAttributeGroups(): void
     {
         if (null === $this->attributeGroupsChoicesAttributes || null === $this->attributeGroupsChoices) {
             if (null === $this->attributeGroups) {
-                $this->attributeGroups = $this->attributeGroupRepository->findByLangAndShop($this->langId, $this->shopId);
+                if ($this->shopContext->isSingleShopContext()) {
+                    $this->attributeGroups = $this->attributeGroupRepository->findByLangAndShop(
+                        $this->langId,
+                        $this->shopContext->getShopConstraint()->getShopId()->getValue()
+                    );
+                } else {
```
Comment (jolelievre) [inline src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: No need to handle group context in your opinion?

Comment (Codencode) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: You're right!!!
How would you do it?
I could handle everything in the else like this:
```
$this->attributeGroups = $this->attributeGroupRepository->findByLangForMoreShops(
    $this->langId,
    $this->shopContext->getAssociatedShopIds()
);
```
so instead of the `findByLangForAllShops` method I would have `findByLangForMoreShops` that uses an array of id_shop?

Maybe if you have a suggestion for a name instead of `findByLangForMoreShops` 😄

Comment (jolelievre) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: Hmm, interesting idea!! I forgot about this `getAssociatedShopIds` That should do it!

Comment (jolelievre) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: I would use `findByLangForShops` simply though, and I guess it could be used for both a single shop and a shop group

Comment (Codencode) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: In fact yes, we can always use the new `findByLangForShops` method without having to check the context.
However, I’ll keep the `findByLangAndShop` method — I don’t want to introduce a breaking change.

Comment (jolelievre) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: Yes for retro-compatibility we have to keep it

Comment (Codencode) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php]: @jolelievre done!

**Review by Hlavtox — DISMISSED** [review]

File: src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php [hunk 3]
```diff
@@ -54,12 +55,12 @@ final class AttributeGroupChoiceProvider implements FormChoiceProviderInterface,
...
      * @param AttributeGroupRepository $attributeGroupRepository
      * @param int $langId
-     * @param int $shopId
+     * @param ShopContext $shopContext
      */
     public function __construct(
         private readonly AttributeGroupRepository $attributeGroupRepository,
         private readonly int $langId,
-        private readonly int $shopId,
+        private ShopContext $shopContext,
```
Comment (jolelievre) [inline src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php:64]: You could also replace `$langId` with the `LanguageContext` but it's optional

**Review by jolelievre — DISMISSED** [review]

File: src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php (hunk 3 above)
Comment (Codencode) [reply src/Core/Form/ChoiceProvider/AttributeGroupChoiceProvider.php:64]: @jolelievre done!

**Review by jolelievre — APPROVED** [review]
Perfect! Thanks @Codencode

**Review by paulnoelcholot — APPROVED** [review]
Hello @Codencode,

I tested your PR and it's good for me! 🎉 

Thanks!

https://github.com/user-attachments/assets/b6e3fab6-9a1e-4bca-8111-08126be410ff

**Comment by Codencode** [comment]
@paulnoelcholot, I think the PR would need a second approval before QA.

I'm asking before merging.
Maybe the "Waiting for QA" label had been added, but the PR was modified.
@PrestaShop/committers what should we do?

Unless @paulnoelcholot's own approval still counts

**Review by kpodemski — APPROVED** [review]
