### PR TITLE
Fix tab modules list

### LINKED ISSUE #21220: BO - Welcome module - Th pop up onboarding is not displayed in the step4/6 "step2" - mbo installed
#### Describe the bug

When the ps_mbo module is installed, the popup onboarding is not displayed at the step 4/6 "Get your shop ready for Payment" step2
image

#### Expected behavior

image

#### Steps to Reproduce

1. Install 1770rc1
2. Go to BO 
3. Follow the welcome instructions
4. See error at step 4/6 "Get your shop ready for Payment" step2

#### Additional information

* PrestaShop version: 1770rc1
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix method which get the list of modules that belong to a tab
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21220
| How to test?  | With Module MBO installed and activated, Go to BO > Payment > Payment methods. The list of Active payment modules must not be empty

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21232)

### CODE REVIEW

File: classes/Tab.php [hunk 1]
```diff
@@ -682,15 +682,44 @@ public static function getClassNameById($idTab)
...
+     * @param string $file_to_refresh
+     * @param string $external_file
+     *
+     * @return bool
+     */
+    private static function refresh($file_to_refresh, $external_file)
+    {
+        $content = Tools::file_get_contents($external_file);
+
+        return $content ? (bool) file_put_contents(_PS_ROOT_DIR_ . $file_to_refresh, $content) : false;
```
Comment (PierreRambaud) [inline classes/Tab.php]:
```suggestion
        return $content ? (bool) file_put_contents(_PS_ROOT_DIR_ . $file_to_refresh, $content) : false;
```
file_put_contents should not be cast in bool, inserting 0 bytes will return false whereas everything is ok :thinking: 

Otherwise you can use `Tools::copy` which is doing the same thing

File: classes/Tab.php [hunk 2]
```diff
@@ -682,15 +682,44 @@ public static function getClassNameById($idTab)
...
+
     public static function getTabModulesList($idTab)
     {
         $modulesList = ['default_list' => [], 'slider_list' => []];
-        $xmlTabModulesList = false;
 
-        if (file_exists(_PS_ROOT_DIR_ . Module::CACHE_FILE_TAB_MODULES_LIST)) {
-            $xmlTabModulesList = @simplexml_load_file(_PS_ROOT_DIR_ . Module::CACHE_FILE_TAB_MODULES_LIST);
+        if (!self::isFresh(Module::CACHE_FILE_TAB_MODULES_LIST, 604800)) {
+            self::refresh(Module::CACHE_FILE_TAB_MODULES_LIST, _PS_TAB_MODULE_LIST_URL_);
```
Comment (PierreRambaud) [inline classes/Tab.php]:
```suggestion
        if (!static::isFresh(Module::CACHE_FILE_TAB_MODULES_LIST)) {
            static::refresh(Module::CACHE_FILE_TAB_MODULES_LIST, _PS_TAB_MODULE_LIST_URL_);
```

I'm not sure about having these methods in the Tab class :thinking:

File: classes/Tools.php [hunk 3]
```diff
@@ -4352,6 +4352,32 @@ public static function setFallbackParameters(array $fallbackParameters): void
...
+
+    /**
+     * @param string $file
+     * @param int $timeout
+     *
+     * @return bool
+     */
+    public static function isFileFresh($file, $timeout = 604800)
+    {
+        if (($time = @filemtime(_PS_ROOT_DIR_ . $file)) && filesize(_PS_ROOT_DIR_ . $file) > 0) {
```
Comment (jolelievre) [inline classes/Tools.php:4376]: No error on `filesize` if the file doesn't exist? Maybe you should use `@filesize` as a protetction?
Unless `@filemtime` already fails on a nonexistent file?

**Review by jolelievre — DISMISSED** [review]
Except the comment I left, it seems ok to me

File: classes/Tab.php [hunk 4]
```diff
@@ -685,12 +685,13 @@ public static function getClassNameById($idTab)
     public static function getTabModulesList($idTab)
     {
         $modulesList = ['default_list' => [], 'slider_list' => []];
-        $xmlTabModulesList = false;
 
-        if (file_exists(_PS_ROOT_DIR_ . Module::CACHE_FILE_TAB_MODULES_LIST)) {
-            $xmlTabModulesList = @simplexml_load_file(_PS_ROOT_DIR_ . Module::CACHE_FILE_TAB_MODULES_LIST);
+        if (!Tools::isFileFresh(Module::CACHE_FILE_TAB_MODULES_LIST, 604800)) {
```
Comment (Progi1984) [inline classes/Tab.php]: No constant for `604800` ?

File: classes/Tools.php [hunk 5]
```diff
@@ -4352,6 +4352,32 @@ public static function setFallbackParameters(array $fallbackParameters): void
...
         static::$fallbackParameters = $fallbackParameters;
     }
+
+    /**
+     * @param string $file_to_refresh
+     * @param string $external_file
+     *
+     * @return bool
+     */
+    public static function refreshFile($file_to_refresh, $external_file)
```
Comment (Progi1984) [inline classes/Tools.php]:
```suggestion
    public static function refreshFile(string $file_to_refresh, string $external_file): bool
```

File: classes/Tools.php [hunk 6]
```diff
@@ -4352,6 +4352,32 @@ public static function setFallbackParameters(array $fallbackParameters): void
...
+        return (bool) static::copy($external_file, _PS_ROOT_DIR_ . $file_to_refresh);
+    }
+
+    /**
+     * @param string $file
+     * @param int $timeout
+     *
+     * @return bool
+     */
+    public static function isFileFresh($file, $timeout = 604800)
```
Comment (Progi1984) [inline classes/Tools.php]:
```suggestion
    public static function isFileFresh(string $file, int $timeout = 604800): bool
```

File: classes/Tools.php (hunk 3 above)
Comment (sowbiba) [reply classes/Tools.php:4376]: filemtime returns false if file doesnt exist

File: classes/Tab.php (hunk 4 above)
Comment (Progi1984) [inline classes/Tab.php]:
```suggestion
        if (!Tools::isFileFresh(Module::CACHE_FILE_TAB_MODULES_LIST, Tools::CACHE_LIFETIME_SECONDS)) {
```

File: classes/Tools.php [hunk 7]
```diff
@@ -40,6 +40,7 @@ class ToolsCore
 {
     const CACERT_LOCATION = 'https://curl.haxx.se/ca/cacert.pem';
     const SERVICE_LOCALE_REPOSITORY = 'prestashop.core.localization.locale.repository';
+    const CACHE_LIFETIME_SECONDS = 604800;
```
Comment (Progi1984) [inline classes/Tools.php]:
```suggestion
    public const CACHE_LIFETIME_SECONDS = 604800;
```

**Review by Progi1984 — DISMISSED** [review]

File: classes/Tools.php [hunk 8]
```diff
@@ -4352,6 +4353,32 @@ public static function setFallbackParameters(array $fallbackParameters): void
...
+        return (bool) static::copy($external_file, _PS_ROOT_DIR_ . $file_to_refresh);
+    }
+
+    /**
+     * @param string $file
+     * @param int $timeout
+     *
+     * @return bool
+     */
+    public static function isFileFresh(string $file, int $timeout = self::CACHE_LIFETIME_SECONDS): bool
```
Comment (PierreRambaud) [inline classes/Tools.php:4374]:
```suggestion
    public static function isFileFresh(string $file, int $timeout = static::CACHE_LIFETIME_SECONDS): bool
```

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM 
**Before PR**
image

**After PR**
image

Thanks @sowbiba !! :+1:

**Comment by Progi1984** [comment]
Thanks @sowbiba & @SD1982
