### PR TITLE
Fix BO page Module permission checks

### LINKED ISSUE #19989: It is not possible to disable a module from BO page
#### Describe the bug

It is not possible to disable a module from BO page, no matter whether you are SuperAdmin or have the rights to modify Module page.

Spotted by @atomiix and @jolelievre 

#### Steps to Reproduce

1. Go to Module BO page
2. Try to "disable" a module

#### Additional information

* PrestaShop version: 1.7.6.x
* PHP version: 7.1

This bug might be related to the following PHPUnit failing:
```
> @php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit-admin.xml

PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
.............................F.................................  63 / 149 ( 42%)
............................................................... 126 / 149 ( 84%)
.......................                                         149 / 149 (100%)

Current report of phpErrorsHandler:
Errors: 0 / Warnings: 417 / Notices: 20 / Deprecations: 470
Time: 38.25 seconds, Memory: 356.74MB

There was 1 failure:
1) LegacyTests\Integration\PrestaShopBundle\Controller\Admin\ModuleControllerTest::testModuleAction
Failed asserting that an array has the key 'test-module'.
/home/travis/build/PrestaShop/PrestaShop/tests-legacy/Integration/PrestaShopBundle/Controller/Admin/ModuleControllerTest.php:58
FAILURES!

Tests: 149, Assertions: 265, Failures: 1.

Script @php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit-admin.xml handling the phpunit-admin event returned with error code 1
```

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Controller permissions are ordered by level, so when you check a minimum permission you need to use the higher ones for the comparison to behave as expected .<br/>Else the level returned `PageVoter::LEVEL_DELETE` doesn't allow to perform `PageVoter::LEVEL_UPDATE` <br/>See [FrameworkBundleAdminController::authorizationLevel](https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/src/PrestaShopBundle/Controller/Admin/FrameworkBundleAdminController.php#L245) for more details<br/>Update: to keep a more precise permission checking, the fix was actually improved to use `isGranted` instead of `authorizationLevel` this allows to check very specific roles
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19989
| How to test?  | Connect to the BO and try to perform enable/disable/install/uninstall actions on modules<br/>With the super admin of course everything must work Ideally if you can also test with a specific Employee Profile And toggling the different autorizations to check that it matches the expected rules (See below the role for each action)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19990)

```
            case ModuleAdapter::ACTION_UPGRADE:
            case ModuleAdapter::ACTION_RESET:
            case ModuleAdapter::ACTION_ENABLE:
            case ModuleAdapter::ACTION_DISABLE:
            case ModuleAdapter::ACTION_ENABLE_MOBILE:
            case ModuleAdapter::ACTION_DISABLE_MOBILE:
                Role UPDATE is required for these actions

            case ModuleAdapter::ACTION_INSTALL:
                Role CREATE is required for these actions

            case ModuleAdapter::ACTION_UNINSTALL:
                Role DELETE is required for these actions
```

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php [hunk 1]
```diff
@@ -803,6 +791,23 @@ private function checkPermissions(array $pageVoter)
         }
     }
 
+    /**
+     * @param string $pageVoter
+     *
+     * @return JsonResponse
+     */
+    private function checkPermission(string $pageVoter)
```
Comment (eternoendless) [inline src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: This won't work in PHP 5.x
```suggestion
    private function checkPermission($pageVoter)
```

**Review by eternoendless — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php (hunk 1 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: It's strange that it was not found by PHP syntax checker 🤔 or is that a check we added from 1.7.7 ?

Comment (eternoendless) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: It's a Github action I think?

**Review by matks — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php (hunk 1 above)
Comment (Quetzacoalt91) [reply src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php]: That's not a syntax but a runtime error, that's why it wasn't found by `php -l`

**Review by atomiix — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi there !

I tested the PR with the different permissions (Menu and Modules permissions), with bulk action and actions on only one module, it matches the rules, so it's QA :heavy_check_mark: .

Thanks @jolelievre @matks !

**Comment by matks** [comment]
Thank you @jolelievre, @atomiix, @Robin-Fischer-PS and @eternoendless
