### PR TITLE
Database update command - Wrong SQL Query generated

### LINKED ISSUE #24423: Error during database upgrade with decimal columns
#### Describe the bug

An error occured during database upgrade from Prestashop 1.7.7.3 to 1.7.7.4.
The error is located in `src/PrestaShopBundle/Command/UpdateSchemaCommand.php`
I attach my [log.txt](https://github.com/PrestaShop/PrestaShop/files/6450987/log.txt) file to the issue.

#### Steps to Reproduce

1. Create a module that use Doctrine and a table that have a DECIMAL field
2. Install the module
3. Go to 1-Click Upgrade
4. Click on "Upgrade Prestashop Now!'

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.27
* 1-Click upgrade version: 4.12.0

### PR DESCRIPTION
**Pull request by RomsC**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When a SQL table have a decimal field, the prestashop:schema:update-without-foreign failed. It generate a wrong SQL query.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24423 
| How to test?      | See issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24584)

### CODE REVIEW

File: src/PrestaShopBundle/Command/UpdateSchemaCommand.php [hunk 1]
```diff
@@ -154,14 +154,18 @@ protected function execute(InputInterface $input, OutputInterface $output)
             if (preg_match('/ALTER TABLE (.+?) /', $sql, $matches)) {
                 $tableName = $matches[1];
                 $matches = [];
-                if (preg_match_all('/([^\s,]*?) CHANGE (.+?) (.+?)(,|$)/', $sql, $matches)) {
-                    foreach ($matches[2] as $matchKey => $fieldName) {
+
+                $findChange = strpos($sql, 'CHANGE');
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Command/UpdateSchemaCommand.php]: It's not a good idea.
It will be true if the SQL request contains the word CHANGE, so
`ALTER TABLE nom_table RENAME COLUMN previous_name TO CHANGED_NAME`

You have to fix the regex instead

Comment (RomsC) [reply src/PrestaShopBundle/Command/UpdateSchemaCommand.php]: I have change the way to make it work

**Review by matks — COMMENTED** [review]
Hello @RomsC and thank you for your contribution.

I had no idea how UpdateSchemaCommand was built so when I reviewed your PR I discovered it. Whao 😅   it's scary! All this tricky logic dealing with SQL queries to manipulate them and obtain the right stuff...

Unfortunately, the code is how it is today. We cannot change that. But in order to be able to modify it and feel safe about the changes, we need some safety measures. Moreover this is being used in the upgrade process which is already quite complex and has a reputation of failing often so let's try to make sure we don't make it worse ^^ .

The very best way to be sure that we break nothing if we merge this Pull Request would be a validation that it works before AND it works after the merge, minus the bug. That can be brought by tests.

This is a CLI Symfony Command. Good news: that can be tested quite well. https://symfony.com/doc/current/console.html#testing-commands The complex part will be to setup a SQL database with a configuration A, then run the Command, then validate the database B is as expected. Maybe using sqlite?

If we have a set of tests that
1. load a given database structure
2. run `prestashop:schema:update-without-foreign`
3. validate new database structure is as expected

Then we could safely merge your Pull Request knowing the behavior has been preserved

**Comment by matks** [comment]
Hello @RomsC did you read my answer 😊  ? How do you feel about it?

**Comment by RomsC** [comment]
Hello @matks, I have read your comment and I understand your point of view.
I am not famyliar with tests and currently I have not time to take a look.
I'll try to find some time to do it, but not right away.

I had a discussion with @PierreRambaud about this PR and he could take a look at it and set up the tests when he has a bit more time.

**Comment by PierreRambaud** [comment]
> Hello @matks, I have read your comment and I understand your point of view.
> I am not famyliar with tests and currently I have not time to take a look.
> I'll try to find some time to do it, but not right away.
> 
> I had a discussion with @PierreRambaud about this PR and he could take a look at it and set up the tests when he has a bit more time.

It's on my TODO list, I started it this morning ^^

**Comment by PierreRambaud** [comment]
Hi  @RomsC I send you a message on slack, I'm looking for a data set examples for my unit tests.
Could you send us examples of SQL queries you get before by adding a simple `var_export($updateSchemaSql);` in `UpdateSchemaCommand` just after building this var?

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hello @RomsC, thanks for your contribution, would you mind to rebase your pull request? Thanks

Reference : https://anavarre.net/how-to-rebase-a-github-pull-request/

**Review by atomiix — DISMISSED** [review]

File: src/PrestaShopBundle/Command/UpdateSchemaCommand.php [hunk 2]
```diff
@@ -67,165 +66,271 @@ protected function configure()
...
+    public function execute(InputInterface $input, OutputInterface $output)
     {
-        $conn = $this->em->getConnection();
-        $conn->beginTransaction();
+        $connection = $this->em->getConnection();
+        $connection->beginTransaction();
 
         $output->writeln('Updating database schema...');
-        $sqls = 0;
+        $affectedRows = 0;
```
Comment (Progi1984) [inline src/PrestaShopBundle/Command/UpdateSchemaCommand.php]:
```suggestion
```

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — COMMENTED** [review]
A small feedback

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @RomsC,

FYI, QA cannot test it right now, we have an issue on autoupgrade that prevents us from testing it : #25276

Sorry for the delay :)

**Comment by PierreRambaud** [comment]
> Hi @RomsC,
> 
> FYI, QA cannot test it right now, we have an issue on autoupgrade that prevents us from testing it : #25276
> 
> Sorry for the delay :)

Is there still an issue?

**Comment by PierreRambaud** [comment]
ping @khouloudbelguith

**Comment by marwachelly** [comment]
Hello,

This PR cannot be tested now. It is blocked by the autoupgrade issue https://github.com/PrestaShop/PrestaShop/issues/26503
image

Thanks,

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello, 

The autoupgrade issue https://github.com/PrestaShop/PrestaShop/issues/26503 is fixed. I tested the PR. Following the steps bellow:

1. Create a release from 8.0.0 with PR
2. Install the module provided in https://github.com/RomsC/upgradewithdecimalfield in the shop 1.7.7.3
3. Go to 1-Click Upgrade to the version  8.0.0 with PR
4. Click on "Upgrade Prestashop Now!'
5. I had the attached error

image

6. The rollback wasn't possible as shown in the screen record bellow
https://watch.screencastify.com/v/aAdNTSuFqQw6X1yV6PeH


PS: I cannot install the module provided in https://github.com/RomsC/upgradewithdecimalfield in the shop 1.7.8.3. So I cannot test the PR with upgrade from 1.7.8.3 to 8.0.0 

image

Could you please check?

Thanks,

**Comment by Progi1984** [comment]
@marwachelly I don't think the error in the upgrade is relative to this PR. It was fixed by @jolelievre in PrestaShop/autoupgrade/pull/434 (v4.15.0 which is not released).

**Review by marwachelly — APPROVED** [review]
Hello,

I tested the PR using the autoupgrade module from the dev branch and following the steps bellow:

1. Create a release from 8.0.0 with PR
2. Install the module provided in https://github.com/RomsC/upgradewithdecimalfield in the shop 1.7.7.3/1.7.8.3
3. Go to 1-Click Upgrade to the version 8.0.0 with PR
4. Click on "Upgrade Prestashop Now!'
The upgrade was successful. 
image

Thanks,

**Comment by Progi1984** [comment]
Thanks @RomsC & @marwachelly
