### PR TITLE
Wrong usage of shopId property during installation process

### LINKED ISSUE #24508: FO - Several pages URL and names are not translated
#### Describe the bug

When I have several languages available on FO, the names and URL of some pages (user account pages, links in footer...) are not translated and are in English whatever the language selected.

In Shop Parameters > Traffic & SEO, the URL are indeed not translated (they were translated in 1.7.7.x), if I modify the URL or the name, it's indeed modified in FO.

#### Expected behavior

URL and pages name should be translated.

#### Steps to Reproduce

1. Install PS in English, with country France.
2. Add "Austria" Localisation Pack
3. Go to FO, login, select "French" as a language
4. Go to the user account : The URL and the name are in English ("My account" and "my-account") instead of French ("Mon compte and "mon-compte" in 1.7.7.x)
5. Check in German : Same issue.

**Screenshots**

my account

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The property is never filled, use the method parameter instead.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24508
| How to test?      | Install PrestaShop in french, make sure ps_meta_lang is properly translated.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24525)

### CODE REVIEW

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 1]
```diff
@@ -62,11 +62,6 @@ class EntityTranslator implements EntityTranslatorInterface
      */
     protected $tableName;
 
-    /**
-     * @var int
-     */
-    protected $shopId;
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/EntityTranslator.php:68]: Please describe the BC Break

**Review by Progi1984 — COMMENTED** [review]
A feedback for the BC Break

File: src/Adapter/EntityTranslation/EntityTranslator.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Adapter/EntityTranslation/EntityTranslator.php:68]: It's not a BC, it has been introduced in 1.7.8.x

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @PierreRambaud 

LGTM, QA :heavy_check_mark: 

https://drive.google.com/file/d/19_wIAQaXgBFXir5usGtkVLXhdgqOzK8j/view

Thanks!

**Comment by Progi1984** [comment]
Thanks @PierreRambaud & @hibatallahAouadni
