### PR TITLE
Do not go to the latest step when you change a previous step state in checkout

### LINKED ISSUE #12456: Checkout proceeds automatically from carrier selection to payment selection
I'm developing a shipment module. My plan is to use the displayCarrierExtraContent -hook to display additional info and input fields when a customer selects a particular carrier by clicking its radio button during checkout. This has worked fine with PS 1.7.2 - 1.7.4 and my earlier shipping modules.

But lately I've been using PS 1.7.5.0 to develop my latest shipping module. To my great surprise I noticed that when during checkcout I selected a carrier, the checkout process automatically proceeded to payment method selection without me clicking the continue-button. I didn't have a chance to read additional carrier info or use my module's additional input fields. Neither did I have a chance to type order comment or make selections about recycled packaging or gift wrap.

I have two languages (id 1 English, id 2 Finnish) in my 1.7.5.0 test installation. English is the default language. When I first notices the problem, I had been using Finnish the whole time during my development project.

While I was trying to figure out what could cause this behavior, I changed FO UI language from Finnish to English and immediately noticed that checkout functioned as I hoped it would function, ie. checkout did not automatically proceed from carrier selection to payment method selection.

I changed back to Finnish, and now it too functions as I had hoped! AFAIK I hadn't done anything else than changed the UI language using PrestaShop's language selector.

To further test the problem I have changed language back and forth, logged in and out, reopened browser and used wholly different browser, but I can't reproduce the problematic behavior anymore. Ie. now the checkout process works as I wish it would but I have no idea how.

Because I can't reproduce the "bug", this isn't exactly a bug report. But hopefully my report will benefit someone if this problem arises somewhere else. I'm not the only one who has noticed this behavior:
https://stackoverflow.com/questions/54255061/disable-automatic-continue-to-the-payment-step

Thank you.

PrestaShop: 1.7.5.0
Theme: classic
PHP Version 7.1.26
WWW-server: Apache 2.4.29
Firefox 65.0 (used during the initial finding and during further tests)
Google Chrome 72.0 (used during further tests)

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Do not go to the latest step when you change a previous step state. <br>Use accessors instead of method properties.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12456 #9620 
| How to test?  | You must be able to switch between step without loosing data, but you always need to click to continue to go to the next order step.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13106)

### CODE REVIEW

File: classes/checkout/CheckoutAddressesStep.php [hunk 1]
```diff
@@ -67,7 +67,7 @@ public function handleRequest(array $requestParams = array())
         if (array_key_exists('use_same_address', $requestParams)) {
             $this->use_same_address = (bool) $requestParams['use_same_address'];
             if (!$this->use_same_address) {
-                $this->step_is_current = true;
+                $this->setComplete(true);
```
Comment (jolelievre) [inline classes/checkout/CheckoutAddressesStep.php]: Is this normal this is the only `setComplete` in the method, and it doesn't match the previous code `$this->step_is_current = true;` not `$this->step_is_complete = true`

**Review by jolelievre — COMMENTED** [review]
This doesn't look like the easy code to modify ^^
I thought the issue required to remove some links in the tabs (that's what I remember from the sprint planning)

**Comment by jolelievre** [comment]
I'm surprised you didn't need any changes to the front part, I thought the problem was linked to this modification: https://github.com/PrestaShop/PrestaShop/pull/11015/files
Which automatically refreshes the page and prevent from fill the whole form.

File: classes/checkout/CheckoutAddressesStep.php (hunk 1 above)
Comment (PierreRambaud) [reply classes/checkout/CheckoutAddressesStep.php]: Thanks, you're right!

**Comment by PierreRambaud** [comment]
@jolelievre This page needs to be reload each time with suppliers.
The problem is the way the current step is determined. In fact when we set step as complete we need to say "Hey, the next step will be the current step" instead of checking for "which step is the latest complete".

**Review by eternoendless — COMMENTED** [review]
Looks good to me

**Review by eternoendless — APPROVED** [review]

**Comment by eduvega16** [comment]
Thanks for the solution!!!
