### PR TITLE
Display validation when Enable/Disable webservice keys by bulk actions

### LINKED ISSUE #21745: Validation message not displayed when Enable/Disable webservice keys by bulk actions
#### Describe the bug

There is no validation message when Enable/Disable webservice keys by bulk actions

#### Expected behavior

Validation message should be displayed after enabling or disabling a webservice key

#### Steps to Reproduce

1. Go to 'Advanced parameters>Webservice'
2. Click on 'Add new webservice key'
3. Select the created webservice key  
4. Click on 'Bulk actions button> Enable or Disable'
5. There is no validation message

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8.0 -  1.7.6.8
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Display validation when Enable/Disable webservice keys by bulk actions
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21745
| How to test?      | Cf. #21745

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25301)

### CODE REVIEW

**Review by Julievrz — DISMISSED** [review]
Wording ✅

File: tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php [hunk 1]
```diff
@@ -0,0 +1,167 @@
...
+        $all = $this->session->getFlashBag()->all();
+        $this->assertArrayHasKey('success', $all);
+        $this->assertSame('The status has been successfully updated.', $all['success'][0]);
+
+        // Check status
+        $webserviceKey = new WebserviceKey($this->webserviceKey->id);
+        $this->assertTrue((bool) $webserviceKey->active);
+    }
+
+    public function dataProviderBulkEnable(): array
```
Comment (PierreRambaud) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php]: Since you have only a boolean behaviour, you can use the same data provider.

File: tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+
+namespace Tests\Integration\PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters;
+
+use Symfony\Bundle\FrameworkBundle\KernelBrowser;
+use Symfony\Bundle\FrameworkBundle\Routing\Router;
+use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
+use Symfony\Component\HttpFoundation\Session\Session;
+use WebserviceKey;
+
+class WebserviceControllerTest extends WebTestCase
```
Comment (matks) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php:37]: I think a playwright test would be better. Checking that session contains the right flash message seems over-engineered to me. If we want to verify that we use correctly the session from the browser, let's setup a real browser and verify how it works with the code.

[Quoting Matthias Noback](https://matthiasnoback.nl/2021/03/testing-controllers-when-you-have-a-decoupled-core/):
> And controllers shouldn't be unit tested, because:

> Those unit tests tend to be a one-to-one copy of the controller code itself. There is no healthy distance between the test and the implementation.
Controllers need some form of integrated testing, because by zooming in on the class-level, you don't know if the controller will behave well when the application is actually used. Is the routing configuration correct? Can the framework resolve all of the controller's arguments? Will dependencies be injected properly? And so on.

File: tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php (hunk 1 above)
Comment (Progi1984) [reply tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php]: Fixed

File: tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+    protected $session;
+    /**
+     * @var WebserviceKey
+     */
+    protected $webserviceKey;
+
+    public function setUp(): void
+    {
+        parent::setUp();
+
```
Comment (PierreRambaud) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php:59]:
```suggestion
```

File: tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+        $this->webserviceKey->key = 'DFS51LTKBBMBAF5QQRG523JMQYEHA4X7';
+        $this->webserviceKey->description = 'Description WS Key';
+        $this->webserviceKey->active = true;
+        $this->webserviceKey->add();
+    }
+
+    public function tearDown(): void
+    {
+        parent::tearDown();
+
```
Comment (PierreRambaud) [inline tests/Integration/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceControllerTest.php:76]:
```suggestion
```

**Review by PierreRambaud — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]
LGTM

**Review by jolelievre — APPROVED** [review]

**Comment by matks** [comment]
Thank you @Progi1984
