### PR TITLE
Fix cart voucher values in cart summary and checkout summary

### LINKED ISSUE #16842: FO - The promo value is not correct in the cart summary & checkout summary
**Describe the bug**
The promo value is not correct in the cart summary & checkout summary

**To Reproduce**
1. Go to the BO => Catalog => Discounts => Create a new cart rule
1.1 has no code
1.2 there is no condition
1.3 As an acrtion=> Apply a discount Percent = 100% => Apply a discount to:"Cheapest product"
image

2. Go to the FO => Add to the cart demo_11 & demo_6
3. The cart rule will be applied to the demo_11
4. Go to the cart page
5. See error
image

With PS1.7.6.2 was ok
image

**Additional information**
PrestaShop version: develop
PHP version: 7.1

Edit:
**Specs:**
The discount should display **the value of the discount** and nor the percentage.
And if the value can't be retrieved for a technical reason, it should display the percentage.

### PR DESCRIPTION
**Pull request by arouiadib**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x 
| Description?  | This PR fixes the issues of the amounts of promo codes in cart summary and checkout summary.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |  Fixes #16842 
| How to test?  | Check the amount of reduction of each cart voucher, now it depends of the actions of the cart voucher and is not equal to all products total.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17502)

### CODE REVIEW

**Comment by MatShir** [comment]
@arouiadib: "the PR I created is a "white-flag" PR for me, because I have spend hours trying to create a cleaner and better solution to no avail. My one-line PR uses an existing method getContextualValue in CartRule.php. Does it go against migration principles? Better not to use methods from that class? Am I right? Additionally, the processing in that mothod almost exists in CartRuleCalculator also, but not easy to re-use ( as I see it addresses another purpose IMO, and re-factoring should be done carefully).

Another possible solution is use quantity from product list in Presenter, but it would be a second duplication for that processing, and maybe is not the role of cartPresenter?!

I think for a cleaner solution is to make a re-factoring in CartRuleCalculator. But more experienced people from the community will suggest me the right direction."

@PrestaShop/prestashop-core-developers What do you think ?

**Comment by marionf** [comment]
For @PrestaShop/prestashop-qa 
Could you verify if this PR brings no regressions with a free shipping cart rule (https://github.com/PrestaShop/PrestaShop/issues/9702) ?

File: src/Adapter/Presenter/Cart/CartPresenter.php [hunk 1]
```diff
@@ -640,6 +637,16 @@ private function cartVoucherHasAmountReduction($cartVoucher)
...
     }
 
+    /**
+     * @param array $cartVoucher
+     *
+     * @return bool
+     */
+    private function cartVoucherHasGiftProductReduction($cartVoucher)
+    {
+        return array_key_exists('gift_product', $cartVoucher) && $cartVoucher['gift_product'];
```
Comment (PierreRambaud) [inline src/Adapter/Presenter/Cart/CartPresenter.php]:
```suggestion
        return !empty($cartVoucher['gift_product']);
```

Is it really needed to add a method only for this check?

Comment (arouiadib) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: Not really needed, but just to follow suit with current code.

Comment (arouiadib) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: I see what you mean now. Well, the only reason is to make the `if` statement more self-explanatory  ( the naming `cartVoucherHasGiftProductReduction` inside `if` emphasizes the fact that we need the 3 conditions that have "similar" weight). But you know, I am still learning the codebase so I can't tell which one is more suitable until you directly tell me ;-)

**Comment by Progi1984** [comment]
@arouiadib Hi Could you fix the PHPCSFixer ? Thanks

**Comment by arouiadib** [comment]
@Progi1984 , I tried today to no avail. I will retry ASAP. Thank you very much for your time.

**Comment by arouiadib** [comment]
Hi @Progi1984 , I finally managed to fix code styles issue.  Messed up the branch a little bit :baby:  
Thank you very much for your time.

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

File: src/Adapter/Presenter/Cart/CartPresenter.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: In fact, this is the same thing.
```
!empty($cartVoucher['gift_product']); // => Not false, 0, '', null, []
array_key_exists('gift_product', $cartVoucher) && $cartVoucher['gift_product'] // => Check if the key exists in the table and is not null, false, 0, '', etc
```

This is the same check, but it's faster due to only one call

Comment (arouiadib) [reply src/Adapter/Presenter/Cart/CartPresenter.php]: Thank you very much :). 
If I understand well (because I really have a slow brain these days), we can we go further by adding [one another commit](https://github.com/PrestaShop/PrestaShop/pull/17502/commits/099a863b16a8a3405af20d28269b483ccb015cb0).

**Comment by SD1982** [comment]
hi @arouiadib  Can you please resolve the conflict ?

**Comment by Progi1984** [comment]
Hello @arouiadib, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by arouiadib** [comment]
Hello @SD1982 @Progi1984 , I think this PR is no longer taking the direction that the code source is taking. I will be rethinking things to bring a more appropriate change. Thank you very much guys for all your time.

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
@arouiadib you're almost done, one last conflict to fix ;)

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by jolelievre** [comment]
Hi @PrestaShop/prestashop-qa 

In addition to what @marionf said about checking no regression regarding the issue #9702 about free shipping cart rule

You should also check this issue https://github.com/PrestaShop/PrestaShop/issues/18065 since lots of the code that fixed this in https://github.com/PrestaShop/PrestaShop/pull/18144 has been replaced

So it would seem all this calculation was useless because it is present in `$cartVoucher` which would be great! @Progi1984 since you approved this PR and coded the previous one i guess it's ok but since we don't have much automated test on this code better safe than sorry ^^

**Comment by SD1982** [comment]
LGTM I have also checked for #9702 and #18065 as suggested by @jolelievre and i haven't notified any unwanted behaviour or regression ! Thanks @arouiadib !

**Comment by Progi1984** [comment]
Thanks @arouiadib

**Comment by arouiadib** [comment]
Thank you all guys.

**Comment by ComonSoft** [comment]
Hi, this fix the issue #16842 but the reduction summury is still false in cart summury see screenshot
image

**Comment by MatShir** [comment]
Hi @ComonSoft,
Could you create a new issue with the detailed steps to helps us reproduce it?
We will be happy to test and check it out.

**Comment by ComonSoft** [comment]
@MatShir this is the same issue as describre in ticket #19090 The solution proposed here only solve the amount of each voucher in cart summury but not the sum of all voucher. 1rst circle in my screen shot.

**Comment by MatShir** [comment]
Okay thanks for your feedbacks @ComonSoft, the bug is placed on the Roadmap 1.7.8 ;-)
