### PR TITLE
Fix module translations

### LINKED ISSUE #29236: Translations with special characters are not displayed properly
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

1.7.8:
image

8.0.0:
image

### Expected behavior

Quotations marks should be properly displayed.

### Steps to reproduce

1. Install the example module.
2. Go to the configuration page.

Example module:
[kphelperformtranslations.zip](https://github.com/PrestaShop/PrestaShop/files/9250305/kphelperformtranslations.zip)

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | See #29236 and comments below
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29236.
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/24401
| How to test?      | See #29236 
| Possible impacts? | All module translations. :point_up: I updated ModuleFrontController as well but I think it is not well tested by original given module.

It looks that legacy `Controller` child classes that used `l(...)` function haven't been well updated during the migration process.
That induced some weird behavior with inheritance.

I reinforced deprecation notifications and checked all legacy controller `l(...)` functions definitions.

### CODE REVIEW

**Comment by kpodemski** [comment]
I'll check this today, but I'm afraid this fix won't work properly with legacy translations.

**Review by jolelievre — COMMENTED** [review]
Thanks @MeKeyCool 

Since our Symfony translator seems to handle the fallback here:
https://github.com/PrestaShop/PrestaShop/blob/8204abff432f7d8c5d27f6f3b337f432e21ae80a/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php#L64-L66

I'd say this is legit, at least in BO which has the Symfony environment available. I don't know if this works fine on the front as well. I'd like @eternoendless or @atomiix opinion on this one before I approve it.

**Comment by MeKeyCool** [comment]
> Thanks @MeKeyCool
> 
> Since our Symfony translator seems to handle the fallback here:
> 
> https://github.com/PrestaShop/PrestaShop/blob/8204abff432f7d8c5d27f6f3b337f432e21ae80a/src/PrestaShopBundle/Translation/PrestaShopTranslatorTrait.php#L64-L66
> 
> I'd say this is legit, at least in BO which has the Symfony environment available. I don't know if this works fine on the front as well. I'd like @eternoendless or @atomiix opinion on this one before I approve it.

Yep, I didn't tested front controller so it would be nice to have more approvals on this fix

**Comment by MeKeyCool** [comment]
> I'll check this today, but I'm afraid this fix won't work properly with legacy translations.

If you have any module with more translation use cases to help me to test I would enjoy the help ;)

**Comment by kpodemski** [comment]
For the `ModuleFrontController` the syntax is:

`$this->l('String', 'ClassName')` which you haven't implemented in the `$this->trans` method, but let me get back to you later today 👍

File: classes/controller/ModuleAdminController.php [hunk 1]
```diff
@@ -103,22 +103,8 @@ protected function getTemplateLookupPaths()
...
-
-            $translated = Translate::getModuleTranslation($this->module->name, $string, $class, null, $addslashes);
-        }
-
-        if ($htmlentities) {
-            $translated = htmlspecialchars($translated, ENT_QUOTES, 'utf-8');
-        }
-
-        return $translated;
+        return $this->trans($string);
```
Comment (eternoendless) [inline classes/controller/ModuleAdminController.php]: This won't work with legacy dictionaries. You need to go through `Translate::getModuleTranslation()` because legacy dictionaries require the module name and the class name where the method is called.

I'd rather investigate about where the double escape is being performed

File: classes/controller/ModuleFrontController.php [hunk 2]
```diff
@@ -94,6 +94,8 @@ public function initContent()
      */
     protected function l($string, $specific = false, $class = null, $addslashes = false, $htmlentities = true)
     {
-        return $this->module->l($string, $specific);
+        @trigger_error(__FUNCTION__ . 'is deprecated. Use ModuleFrontController::trans instead.', E_USER_DEPRECATED);
+
+        return $this->trans($string);
```
Comment (eternoendless) [inline classes/controller/ModuleFrontController.php]: You need to use `l()` for the same reasons explained above.

**Review by eternoendless — DISMISSED** [review]

File: classes/controller/ModuleAdminController.php (hunk 1 above)
Comment (MeKeyCool) [reply classes/controller/ModuleAdminController.php]: In fact `Translate::getModuleTranslation` didn't translate well then I'll search there why it doesn't work.

Comment (kpodemski) [reply classes/controller/ModuleAdminController.php]: @MeKeyCool FYI, before your change, every translation was working as expected, and the only issue was the double escape.

**Comment by MeKeyCool** [comment]
@eternoendless , with my testing case, it looks that changing  `Translate::getModuleTranslation` arguments ensure the job.

What do you think ? Is there any case where escaping special characters is expected ? :thinking:

File: classes/controller/ModuleAdminController.php [hunk 3]
```diff
@@ -112,7 +112,9 @@ protected function l($string, $class = null, $addslashes = false, $htmlentities
                 $class = get_class($this);
             }
 
-            $translated = Translate::getModuleTranslation($this->module->name, $string, $class, null, $addslashes);
+            $fallback = false; // new translation system has already been tested
+            $escape = false; // don't convert special chars to html entities
```
Comment (atomiix) [inline classes/controller/ModuleAdminController.php]: Maybe the `$escape` should be using the `$htmlentities` value?

Comment (MeKeyCool) [reply classes/controller/ModuleAdminController.php]: :thinking: I am not sure to understand your comment, do you mean that I should change variable name ?

Comment (atomiix) [reply classes/controller/ModuleAdminController.php]: No, I mean that maybe `$escape` should be dependent of the value of `$htmlentities`.
```php
$translated = Translate::getModuleTranslation($this->module->name, $string, $class, null, $addslashes, null, $fallback, $htmlentities);
```

Comment (MeKeyCool) [reply classes/controller/ModuleAdminController.php]: So scatterbrained xD
I even didn't notice that argument ... I'll check in our specific case but it's default value at true looks a problem ^^'

Thanks for the double check ^^'

Comment (MeKeyCool) [reply classes/controller/ModuleAdminController.php]: I got the problem.

In fact, `$htmlentities` option is applied twice.
I'll review the workflow. Maybe it is better to remove it from `ModuleAdminControllerCore::l(...)` function.

**Comment by MeKeyCool** [comment]
Then in fact 
```php
if ($htmlentities) {
    $translated = htmlspecialchars($translated, ENT_QUOTES, 'utf-8');
}
```
was a way to fix that `$htmlentities` wasn't applied properly in `parent::l(...)` and `Translate::getModuleTranslation(...)`

**Comment by Julievrz** [comment]
I don't see any new wordings so I'm removing the label but feel free to ping me back if needed.

**Review by jolelievre — APPROVED** [review]
Thanks @MeKeyCool 

The fix seems legit with the minimum and clean changes, nice job.

**Review by kpodemski — APPROVED** [review]
Great, I've tested it and it works as expected 👍 

Thanks @MeKeyCool

**Review by atomiix — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @MeKeyCool,

Thank you for this PR.

Tested on 8.0.x branch with PHP 7.3.

All auto tests are ok ✅.
The quote are well displayed with your PR ✅:

https://user-images.githubusercontent.com/2854834/189317870-81f65e48-e33c-43e5-8923-96079dbfcc76.mp4

QA approved ✅ 

Thanks

**Comment by matks** [comment]
Thank you @MeKeyCool and @sLorenzini
