### PR TITLE
Fix discount detail in cart when a product has en ecotax with applied tax

### LINKED ISSUE #29331: FO - Discounts - The discount detail is NOK when we the product selected has an ecotax
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-974372319
In the FO > Shopping cart page and checkout page, when we apply a cart rule "percent discount on a selected product that has an ecotax, the discount line s NOK.

Reproduced with PS1787 and 8.0.x

It is ok with PS1770

### Expected behavior

Display 6 Euro in the discount details in the step to reproduce. 

### Steps to reproduce

1. Go to BO > International > Taxes & Enable Ecotax & tax ecotax = 20%
2. Create a product with ecotax, in my case   
image
3. Go to BO > Catalog > Cart rules page and create a cart rule:
3.1 Product Selection: select the ecotax product 
image
3.2 a percent discount, in my case 50% & Apply a discount to Selected Products 
image
4. Go to FO > Add the last product created to the cart
5. Apply the discount
6. See error: the discount line = 5.80 => NOK, it should be 6
image

### PrestaShop version(s) where the bug happened

1.7.8.7, 8.0.x

### PHP version(s) where the bug happened

7.2, 8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In the FO > Shopping cart page and checkout page, when we apply a cart rule "percent discount on a selected product that has an ecotax, the discount line s NOK.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29331
| Related PRs       | 
| How to test?      | See #29331
| Possible impacts? |

### CODE REVIEW

**Comment by matks** [comment]
> Hello @mflasquin!
> 
> This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

@mflasquin when your first PR is merged, you won't see this message anymore

**Review by matks — APPROVED** [review]
Looks good but only QA team will be able to tell us if this is right 😄

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @mflasquin ,

Tested the following:

- Basic case from issue:
Screenshot 2022-10-28 at 16 18 14
Screenshot 2022-10-28 at 16 17 57
Screenshot 2022-10-28 at 16 17 29


- Case with Ecotax, no tax: ✅ 
Screenshot 2022-10-28 at 16 40 45
Screenshot 2022-10-28 at 16 40 32
Screenshot 2022-10-28 at 16 42 29


- Case without Ecotax all together: ✅ 


- Tested with Discount amount - Tax excluded (instead of Discount Percentage): ❌ 
NOK, but out-of-scope and already on GitHub: 
https://github.com/PrestaShop/PrestaShop/issues/25389

Check result in FO page product, FO cart, FO checkout process, BO orders, BO invoice pdf and automated tests ✅ 

LGTM, it is QA ✅ 
Thanks @mflasquin !

**Comment by jolelievre** [comment]
Thanks @mflasquin and @florine2623

File: classes/CartRule.php [hunk 1]
```diff
@@ -1328,12 +1328,7 @@ public function getContextualValue($use_tax, Context $context = null, $filter =
                             && (($this->reduction_exclude_special && !$product['reduction_applies']) || !$this->reduction_exclude_special)) {
                             $price = $product['price'];
                             if ($use_tax) {
-                                $infos = Product::getTaxesInformations($product, $context);
-                                $tax_rate = $infos['rate'] / 100;
-                                // As the price is tax excluded but ecotax included, we need to substract the ecotax before getting the price tax included
-                                $price -= $product['ecotax'];
-                                $price *= (1 + $tax_rate);
-                                $price += $product['ecotax'];
+                                $price = $product['price_without_reduction'];
```
Comment (DelecroixQuentin) [inline classes/CartRule.php:1331]: Hi @mflasquin @jolelievre @matks,
A bit late but why use `$product['price_without_reduction']` here ?

`$product['price']` is the current price without tax and with reduction apply.
So, in this case, we want to use the current price with tax AND with reduction apply (ie `$product['price_with_reduction']` variable)
With the use of `$product['price_without_reduction']`, it means that we use the current price with tax but without reduction, so it's ok for all product without reduction but if we have a product with a specific price apply, the cart rule amount is wrongly computed.

Product with specific price in cart : 
image

Add cart rule on this cart : 
image
The cart rule amount computed is set to - 139.9 instead of - 79.9.
By the way, the discount line is correct.

**Comment by RosaBenouamer** [comment]
Hello @DelecroixQuentin 
Thank you for your proposition.
Is it possible for you to submit a PR please ?
Indeed this one is already merged :-)
