### PR TITLE
Fix filter not being taken into account in grid export

### LINKED ISSUE #10293: Issues in search / export feature in migrated pages
**Describe the bug**
Currently, the export action in Crud pages doesn't take in account the results filtered by the User.

**To Reproduce**
1. Go to one listing page migrated on SF (Categories or Customers)
2. Filter the Grid using Search form.
3. Click on the Wheel, then "Export" action
4. The generated file contains all categories.

**Additionnal information**
PrestaShop version: 1.7.6.0
PHP version: whatever

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix grid filters not being taken into account
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | Fixes #10293
| How to test?  | Filter customer, and export as csv, your filter should be taken into account. Same for category listing.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16158)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 1]
```diff
@@ -110,6 +111,27 @@ public function indexAction(Request $request, CustomerFilters $filters)
...
+        $responseBuilder = $this->get('prestashop.bundle.grid.response_builder');
+
+        return $responseBuilder->buildSearchResponse(
+            $this->get('prestashop.core.grid.definition.factory.customer'),
+            $request,
+            CustomerGridDefinitionFactory::GRID_ID,
+            'admin_customers_index'
+        );
+    }
+
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: I'm thinking about factoring this, it looks a lot like the searchGridAction in the CategoryController

File: src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php [hunk 2]
```diff
@@ -233,6 +235,11 @@ protected function getFilters()
                         'data-url' => $this->resetActionUrl,
                         'data-redirect' => $this->redirectActionUrl,
                     ],
+                    'reset_route' => 'admin_common_reset_search_by_filter_id',
+                    'reset_route_params' => [
+                        'filterId' => self::GRID_ID,
```
Comment (PierreRambaud) [inline src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php]:
```suggestion
                        'filterId' => static::GRID_ID,
```

**Review by PierreRambaud — DISMISSED** [review]

File: src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php [hunk 3]
```diff
@@ -233,6 +235,11 @@ protected function getFilters()
                         'data-url' => $this->resetActionUrl,
                         'data-redirect' => $this->redirectActionUrl,
                     ],
+                    'reset_route' => 'admin_common_reset_search_by_filter_id',
```
Comment (jolelievre) [inline src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php:234]: Mmmm, I think you should remove the `attr` part

**Review by jolelievre — COMMENTED** [review]
You can clean the Category definition

File: src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php (hunk 3 above)
Comment (matthieu-rolland) [reply src/Core/Grid/Definition/Factory/CategoryGridDefinitionFactory.php:234]: done

**Review by jolelievre — APPROVED** [review]
Nice @matthieu-rolland
