### PR TITLE
Module translations no longer take translations from another lang if its default one.

### LINKED ISSUE #27351: Module Description gives "missing" Translation issue
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Module description text: "Get notified directly on your browser tab each time you get a new order, customer or message." , see screenshot, is not appearing anywhere for translation to other languages, but is probably referred as "missing" translation in International>Translation>installed modules translation section, even in English, see screenshot.
This also gives error in Symphony, see another screenshot
Снимок экрана 2022-01-13 в 23 26 40
Снимок экрана 2022-01-13 в 23 29 36
Снимок экрана 2022-01-13 в 23 32 31

### Expected behavior

text is translatable and no translation error in Symphony

1. Enable Debug mode
1. Go to BO > International > Translations page 
2. Choose a module 'Order Notifications on the Favicon' to translate
3. Search for this expression: `Get notified directly on your browser tab each time you get a new order, customer or message.` => No expression
4. In the Path `/PrestaShop/Modules/Ps_faviconnotificationbo.php` => it is well displayed

That's why we have a warning
https://user-images.githubusercontent.com/16067358/149479984-3329c17a-e66c-4e0d-8840-3576535d1e59.mp4

---------------------------------------------

1. Debug mode
2. Translation errors in Symphony
3. International>Translation>installed modules translation of English: cannot find any missing string, while it is shown that there is one
(see screenshots above)

### PrestaShop version(s) where the bug happened

1.7.6.5

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

Order Notifications on the Favicon v2.1.1 / ModulesFaviconnotificationboAdmin

### LINKED ISSUE #30085: Module translations with different languages
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If module has few different languages translated it will auto-fill missing fields with default language.
For example if default BO lang is set to NL and we try to translate the LT one, the missing LT fields will be filled with the filled NL fields. As I understand it should stay empty, because its hard to find missing fields for LT lang if the missing ones are filled with other lang.
image

### Expected behavior

If the translations are missing for the selected lang it should stay missing and not filled with default BO lang translations

### Steps to reproduce

1. Select any module that you want to test
2. Translated selected language, for example Netherlands.
3. Change BO language to Netherlands (profile->language)
4. Try to translate same module in Lithuanian language (can use any other language)
5. If the translation doesn't exist in Lithuanian but exists in Netherlands it will be filled with Netherlands translations

### PrestaShop version(s) where the bug happened

1.7+

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by margud**
… from default lang and not leave them empty

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | When translating module, if default lang is not English the other languages gets filled with default lang translations. For example if my module has FR translations but doesn't have LT translations and BO default lang is FR. When translating module for LT it will fill with FR translations when it should leave it empty. This PR fixes this issue.
| Type?             | bug fix 
| Category?         |  BO 
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Translate module in one lang and in Bo user profile make language of the translated lang. Then when translating it for another lang it should no longer fill fields with another lang.
| Fixes issue | Resolves #30085 & resolves #27351

### CODE REVIEW

**Comment by kpodemski** [comment]
Hello @margud 

Just to make sure. Are you talking about a situation where your translations are done like this:

`$this->l('Something in English')`

or `$this->l('Something in French by default')`?

**Comment by margud** [comment]
> Hello @margud
> 
> Just to make sure. Are you talking about a situation where your translations are done like this:
> 
> `$this->l('Something in English')`
> 
> or `$this->l('Something in French by default')`?

Its when $this->l('Something in English')

For example if the text is $this->l('Something in English')
BO default shop is FR and it has it translated to 'Something in FR'
Then if i go to LT translation where it is not translated i expect it to be blank but it adds 'Something in FR'
By adding this change this doesn't happen anymore.

**Comment by kpodemski** [comment]
Thanks, @margud. I'm asking because this code that you've modified is there for ages, and I'm worried about possible side-effects.

**Comment by margud** [comment]
> Thanks, @margud. I'm asking because this code that you've modified is there for ages, and I'm worried about possible side-effects.

I was also afraid to change it but couldn't fine any side effects. Maybe we need more testing, i m not sure but I couldn't find anything that it could effect.

File: controllers/admin/AdminTranslationsController.php [hunk 1]
```diff
@@ -271,11 +271,7 @@ protected function getModuleTranslations()
         if (!isset($_MODULE) && !isset($GLOBALS[$name_var])) {
             $GLOBALS[$name_var] = [];
         } elseif (isset($_MODULE)) {
-            if (is_array($GLOBALS[$name_var]) && is_array($_MODULE)) {
```
Comment (jolelievre) [inline controllers/admin/AdminTranslationsController.php:274]: This is a bit weird because the method so far did exactly what it stated in its description (for once we have a description on legacy code 😅) I'm a bit worried this could have unexpected side effects

Comment (margud) [reply controllers/admin/AdminTranslationsController.php:274]: Yeah but its only used to fill translations in translation page. And it fills with default lang when it should leave it empty. So should i just close this pr and leave it like it is?

**Comment by matks** [comment]
@jolelievre @kpodemski we have amazing people to help us finding about side effects: the QA team

So I suggest if the code seems OK but we are afraid of side effects we ask the help of QA team.

**Review by matks — APPROVED** [review]

**Comment by jolelievre** [comment]
@margud did you create an issue for this one? We may need some insight from the product team at first, and then we can focus a bit more on this code change because I'm really worried about the possible side effects here 🤔

**Comment by margud** [comment]
> @margud did you create an issue for this one? We may need some insight from the product team at first, and then we can focus a bit more on this code change because I'm really worried about the possible side effects here thinking

Created and added in description.

**Review by jolelievre — COMMENTED** [review]
Thanks @margud

**Review by jolelievre — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
The issue related to this PR is invalid and closed.
So, This PR cannot be tested.

Thank you !

**Comment by jolelievre** [comment]
I believe the issue was closed by mistake but it as recently reopened (and assigned to another issue that was older in the meantime). So this PR should be tested again I guess

**Review by MhiriFaten — APPROVED** [review]
Hello @margud ,

I have checked your PR and the issue is well fixed !
The automated tests are OK.

So it is QA approved :heavy_check_mark: 
Thank you !

**Comment by FabienPapet** [comment]
Thank you @margud
