### PR TITLE
Open EntitySearchInput to public components in backoffice

### LINKED ISSUE #34667: Product Page v2 does not work with all input types.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

following the instructions on how to add fields to product page v2
https://devdocs.prestashop-project.org/8/modules/sample-modules/extend-product-page/

adding a EntitySearchInputType to the options tab
https://devdocs.prestashop-project.org/8/development/components/form/types-reference/entity-search-input-type/

ends up in rendering a dead input that does not work to search in, also the delete buttons for attached items does nothing.

Seems to be related to the search for related products is initiated with hard coded id's in https://github.com/PrestaShop/PrestaShop/blob/a85f47c37b3e3b52a4eddbdcb33baf851d0dd691/admin-dev/themes/new-theme/js/pages/product/product-map.ts

```
 relatedProducts: {
    searchInput: '#product_description_related_products',
  },
```

rebuilding this file with a class selector does make the input search, but the two widgets will then overlap and adding a new item will be added to both inputs. So there seems to be more issues with this.

### Expected behavior

I expect inputTypes to work.

### Steps to reproduce

1. install a module to the shop that extends the product page with a EntitySearchInputType 
2. select product page v2
3. go to a product
4. type a search into the new field.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

7.4.9

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by thomasDelaporte**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Enables the “EntitySearchType” component to be used outside the sources of the new administration theme (mainly for module developers). The solution isn't perfect for the user's (prestawork) needs, but it's within the Prestashop standards.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Modifications that may have an impact on use are made to the component initialization for the “Related product” field (Product V2) to demonstrate its use.
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/9398790012
| Fixed issue or discussion?     | Fixes #34667

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @thomasDelaporte!

This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

**Review by nicosomb — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]
LGMT, thanks for your contribution ;)

File: admin-dev/themes/new-theme/js/app/utils/init-components.ts [hunk 1]
```diff
@@ -158,6 +159,7 @@ const initPrestashopComponents = (): void => {
     TinyMCEEditor,
     TranslatableField,
     TranslatableInput,
+    EntitySearchInput
```
Comment (kpodemski) [inline admin-dev/themes/new-theme/js/app/utils/init-components.ts]:
```suggestion
    EntitySearchInput,
```

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @thomasDelaporte 

Good idea!

**Comment by florine2623** [comment]
@PrestaShop/tech-council can this be QAed by dev ?

**Comment by kpodemski** [comment]
@florine2623 yes, it should be tested by dev

**Comment by jolelievre** [comment]
Tested and validated by QA by dev
