### PR TITLE
Fix robots.txt and generate new one when action on languages

### LINKED ISSUE #14836: robots.txt is wrong
**Describe the bug**
Robots.txt file is generated for wrong dirs.

**To Reproduce**
0. Install Danish language on a clean install (no second language). Try to install PrestaShop in a folder instead of in the root (I did not test in the root).
1. Go to configure -> shop -> seo & url -> generate robots.txt
2. See robots.txt Should be similair to below:
**Please note that there is generated some URLs with language code `/da/` but I do only have one language installed, so I don't have a language code in my URL.**

```
# robots.txt automatically generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# http://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
Allow: */modules/*.png
Allow: */modules/*.jpg
Allow: /js/jquery/*
# Private pages
Disallow: /*?order=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&order=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories for localhost
Disallow: /prestashop_WH/app/
Disallow: /prestashop_WH/cache/
Disallow: /prestashop_WH/classes/
Disallow: /prestashop_WH/config/
Disallow: /prestashop_WH/controllers/
Disallow: /prestashop_WH/download/
Disallow: /prestashop_WH/js/
Disallow: /prestashop_WH/localization/
Disallow: /prestashop_WH/log/
Disallow: /prestashop_WH/mails/
Disallow: /prestashop_WH/modules/
Disallow: /prestashop_WH/override/
Disallow: /prestashop_WH/pdf/
Disallow: /prestashop_WH/src/
Disallow: /prestashop_WH/tools/
Disallow: /prestashop_WH/translations/
Disallow: /prestashop_WH/upload/
Disallow: /prestashop_WH/var/
Disallow: /prestashop_WH/vendor/
Disallow: /prestashop_WH/webservice/
Disallow: /da/app/
Disallow: /da/cache/
Disallow: /da/classes/
Disallow: /da/config/
Disallow: /da/controllers/
Disallow: /da/download/
Disallow: /da/js/
Disallow: /da/localization/
Disallow: /da/log/
Disallow: /da/mails/
Disallow: /da/modules/
Disallow: /da/override/
Disallow: /da/pdf/
Disallow: /da/src/
Disallow: /da/tools/
Disallow: /da/translations/
Disallow: /da/upload/
Disallow: /da/var/
Disallow: /da/vendor/
Disallow: /da/webservice/
# Files
Disallow: /*da/gendan-adgangskode
Disallow: /*da/adresse
Disallow: /*da/adresser
Disallow: /*da/log-ind
Disallow: /*da/kurv
Disallow: /*da/rabat
Disallow: /*da/ordrehistorik
Disallow: /*da/mine-oplysninger
Disallow: /*da/min-konto
Disallow: /*da/foelg-din-bestilling
Disallow: /*da/kreditnota
Disallow: /*da/ordre
Disallow: /*da/soeg
Disallow: /*da/Gaestesporing
Disallow: /*da/ordrebekraeftelse

```

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.x
screen

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Currently the robots.txt is not good when there is only one language. I've added an improvement to generate the robots.txt when you change a language. I also add svg and gif
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/14836
| How to test?      | See below
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company   | @Touxten 

**How to test :** 

- Generate robots.txt with one language and the url is http://127.0.0.1/  and check the robots.txt
- Generate robots.txt with two languages and the url is http://127.0.0.1/ and check the robots.txt
- Generate robots.txt with one language and the url is http://127.0.0.1/myfolder/  and check the robots.txt
- Generate robots.txt with two languages and and the url is http://127.0.0.1/myfolder/  and check the robots.txt
- Enable multishop and creates two shops with differents directory and check the robots.txt
- Put an online website and check if the crawler dont acces to the page with this tools (https://fr.ryte.com/free-tools/robots-txt/) or another tools

The new content without /fr/ or /*fr/ for a website with one language and in the folder `/dev-monoshop/PrestaShop/`

```
# robots.txt automatically generated by PrestaShop e-commerce open-source solution
# https://www.prestashop.com - https://www.prestashop.com/forums
# This file is to prevent the crawling and indexing of certain parts
# of your site by web crawlers and spiders run by sites like Yahoo!
# and Google. By telling these "robots" where not to go on your site,
# you save bandwidth and server resources.
# For more information about the robots.txt standard, see:
# https://www.robotstxt.org/robotstxt.html
User-agent: *
# Allow Directives
Allow: */modules/*.css
Allow: */modules/*.js
Allow: */modules/*.png
Allow: */modules/*.jpg
Allow: */modules/*.gif
Allow: */modules/*.svg
Allow: /js/jquery/*
# Private pages
Disallow: /*?order=
Disallow: /*?tag=
Disallow: /*?id_currency=
Disallow: /*?search_query=
Disallow: /*?back=
Disallow: /*?n=
Disallow: /*&order=
Disallow: /*&tag=
Disallow: /*&id_currency=
Disallow: /*&search_query=
Disallow: /*&back=
Disallow: /*&n=
Disallow: /*controller=addresses
Disallow: /*controller=address
Disallow: /*controller=authentication
Disallow: /*controller=cart
Disallow: /*controller=discount
Disallow: /*controller=footer
Disallow: /*controller=get-file
Disallow: /*controller=header
Disallow: /*controller=history
Disallow: /*controller=identity
Disallow: /*controller=images.inc
Disallow: /*controller=init
Disallow: /*controller=my-account
Disallow: /*controller=order
Disallow: /*controller=order-slip
Disallow: /*controller=order-detail
Disallow: /*controller=order-follow
Disallow: /*controller=order-return
Disallow: /*controller=order-confirmation
Disallow: /*controller=pagination
Disallow: /*controller=password
Disallow: /*controller=pdf-invoice
Disallow: /*controller=pdf-order-return
Disallow: /*controller=pdf-order-slip
Disallow: /*controller=product-sort
Disallow: /*controller=search
Disallow: /*controller=statistics
Disallow: /*controller=attachment
Disallow: /*controller=guest-tracking
# Directories for 127.0.0.1
Disallow: /dev-monoshop/PrestaShop/app/
Disallow: /dev-monoshop/PrestaShop/cache/
Disallow: /dev-monoshop/PrestaShop/classes/
Disallow: /dev-monoshop/PrestaShop/config/
Disallow: /dev-monoshop/PrestaShop/controllers/
Disallow: /dev-monoshop/PrestaShop/download/
Disallow: /dev-monoshop/PrestaShop/js/
Disallow: /dev-monoshop/PrestaShop/localization/
Disallow: /dev-monoshop/PrestaShop/log/
Disallow: /dev-monoshop/PrestaShop/mails/
Disallow: /dev-monoshop/PrestaShop/modules/
Disallow: /dev-monoshop/PrestaShop/override/
Disallow: /dev-monoshop/PrestaShop/pdf/
Disallow: /dev-monoshop/PrestaShop/src/
Disallow: /dev-monoshop/PrestaShop/tools/
Disallow: /dev-monoshop/PrestaShop/translations/
Disallow: /dev-monoshop/PrestaShop/upload/
Disallow: /dev-monoshop/PrestaShop/var/
Disallow: /dev-monoshop/PrestaShop/vendor/
Disallow: /dev-monoshop/PrestaShop/webservice/
# Files
Disallow: /dev-monoshop/PrestaShop/recuperation-mot-de-passe
Disallow: /dev-monoshop/PrestaShop/adresse
Disallow: /dev-monoshop/PrestaShop/adresses
Disallow: /dev-monoshop/PrestaShop/connexion
Disallow: /dev-monoshop/PrestaShop/panier
Disallow: /dev-monoshop/PrestaShop/reduction
Disallow: /dev-monoshop/PrestaShop/historique-commandes
Disallow: /dev-monoshop/PrestaShop/identite
Disallow: /dev-monoshop/PrestaShop/mon-compte
Disallow: /dev-monoshop/PrestaShop/suivi-commande
Disallow: /dev-monoshop/PrestaShop/avoirs
Disallow: /dev-monoshop/PrestaShop/commande
Disallow: /dev-monoshop/PrestaShop/recherche
Disallow: /dev-monoshop/PrestaShop/suivi-commande-invite
Disallow: /dev-monoshop/PrestaShop/confirmation-commande
```

This PR close : https://github.com/PrestaShop/PrestaShop/pull/26133

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26133)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php [hunk 1]
```diff
@@ -432,4 +444,16 @@ private function getBulkLanguagesFromRequest(Request $request)
 
         return $languageIds;
     }
+
+    /**
+     * Generates the robots.txt file.
+     *
+     * @return bool
+     */
+    private function generateRobotsTxt()
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php]: This does not only generate the robots.txt file. If there is already a file, it replaces the old file, right ?

The naming of the function should represent this. Suggestions:
- `regenerateRobotsTxt()`
- `recreateRobotsTxt()`

File: classes/Tools.php [hunk 2]
```diff
@@ -2881,13 +2881,14 @@ public static function generateRobotsFile($executeHook = false)
                 }
 
                 // Disallow multilang directories
-                if (!empty($languagesIsoIds)) {
+                if (!empty($languagesIsoIds) && count($languagesIsoIds) > 1) {
```
Comment (PierreRambaud) [inline classes/Tools.php]:
```suggestion
                if (is_array($languagesIsoIds) && count($languagesIsoIds) > 1) {
```
The return of `getIsoIds` can be false, so the count will fail. This check can also be done above instead of redo it on each loop.

```php
$containsIsoIds = is_array($languagesIsoIds) && count($languagesIsoIds) > 1;
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php [hunk 3]
```diff
@@ -307,6 +317,8 @@ public function bulkToggleStatusAction(Request $request, $status)
                 $expectedStatus
             ));
 
+            $this->generateRobotsTxt();
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php]: This should not be done in the controller but in the BulkToggleStatusHandler. Same for all other calls. The controller should contain as little as possible logic, following the [Skin controller, fat model](https://www.slideshare.net/syedhamin/thin-controllers-fat-models-how-to-write-better-code) practice.

**Review by matks — DISMISSED** [review]
Hello @okom3pom thank you for the PR!

The robots.txt generation seems OK but there is some changes to bring. 😉

File: src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php (hunk 3 above)
Comment (ghost) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController.php]: I hope i use the good way

File: classes/Tools.php [hunk 4]
```diff
@@ -2878,36 +2878,35 @@ public static function generateRobotsFile($executeHook = false)
...
-                            fwrite(
-                                $write_fd,
-                                sprintf(
-                                    'Disallow: /%s/%s%s',
-                                    $language['iso_code'],
-                                    $dir,
-                                    PHP_EOL
-                                )
-                            );
+                    // Disallow multilang directories
```
Comment (tegbessou) [inline classes/Tools.php:2887]: Hi @okom3pom, I don't understand why you move this and the next if condition in the previous `foreach` could you explain me, please?

File: classes/Tools.php [hunk 5]
```diff
@@ -2878,36 +2878,35 @@ public static function generateRobotsFile($executeHook = false)
...
+                    if (is_array($languagesIsoIds) && count($languagesIsoIds) > 1) {
```
Comment (tegbessou) [inline classes/Tools.php:2888]: In this if condition instead of `count($languageIsoIds) > 1`, you can use `!empty($languageIsoIds)`. I think it's more understandable :)

Comment (ghost) [reply classes/Tools.php:2888]: Hello @tegbessou.

This is the problem with robots.txt

When there is only one language it adds /en/ but these addresses do not exist with /en/ when there is only one language.

If count > 1 we add /fr/ and /en/ 

More informations and bad robot.txt in the issue https://github.com/PrestaShop/PrestaShop/issues/14836

File: classes/Tools.php (hunk 4 above)
Comment (ghost) [reply classes/Tools.php:2887]: It is when you have many shops with different directories that we need this.

Comment (ghost) [reply classes/Tools.php:2887]: I will add the "multishop" section for "How to test".

File: classes/Tools.php (hunk 5 above)
Comment (tegbessou) [reply classes/Tools.php:2888]: Yes, I understand the problem! Thank you!

File: classes/Tools.php (hunk 4 above)
Comment (tegbessou) [reply classes/Tools.php:2887]: Okay, thank you for the explanation! Yes, please add this in `How to test`!

**Review by matks — COMMENTED** [review]
Hello @okom3pom and thank you for the improvements! The PR is a lot better now :)

Do you think we can go to the next level? Your code will become even better if...we can test it.
- it would be awesome to have tests verify the output of Tools::generateRobotsFile()
- it would be awesome to have tests verify the four handlers correctly execute the file re-computing

**Review by sowbiba — COMMENTED** [review]
Improvements seems good to me. Waiting for tests asked by @matks to make it better. Thanks @okom3pom

**Comment by PierreRambaud** [comment]
Hi @okom3pom ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @okom3pom ,

Thanks for the PR !

Generate robots.txt with one language and the url is http://127.0.0.1/ and check the robots.txt ✅ 
[robots_1.txt](https://github.com/PrestaShop/PrestaShop/files/8023010/robots_1.txt)

Generate robots.txt with two languages and the url is http://127.0.0.1/ and check the robots.txt ✅ 
[robots_2.txt](https://github.com/PrestaShop/PrestaShop/files/8023011/robots_2.txt)

Generate robots.txt with one language and the url is http://127.0.0.1/myfolder/ and check the robots.txt ✅ 
[robots_folder_1.txt](https://github.com/PrestaShop/PrestaShop/files/8022960/robots_folder_1.txt)

Generate robots.txt with two languages and and the url is http://127.0.0.1/myfolder/ and check the robots.txt ✅ 
[robots_folder_2.txt](https://github.com/PrestaShop/PrestaShop/files/8022962/robots_folder_2.txt)

With multishop, 2 shops 2 languages ✅ 
[robots.txt](https://github.com/PrestaShop/PrestaShop/files/8023064/robots.txt)


It is QA ✅ !

**Comment by Progi1984** [comment]
Thanks @okom3pom & @florine2623
