### PR TITLE
Fix category create in product page

### LINKED ISSUE #22144: BO - Can't create category on product page
#### Describe the bug

In the BO > Catalog > Products page > Create a new Product, when we try to create a new category, we have an exception in the console.
image

#### Expected behavior

In the 177x => OK

#### Steps to Reproduce

1. Go to BO > Catalog > Product page
2. Add a new product
3. Scroll down to create a new category

#### Additional information

* PrestaShop version: develop (1780)
* PHP version: 7.2

### LINKED ISSUE #25081: Product page category creation fails
#### Describe the bug

Strict types were declared in old code recently (probably mistaken, that command was introduced in experimental page) and now category creation fails in product page.

#### Expected behavior

Category should be created successfully

#### Steps to Reproduce

1. Go to Product page (old)
2. Add category
3. Nothing happens (see error in profiler)

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
Screenshot from 2021-06-22 16-06-55
Screenshot from 2021-06-22 16-07-05

#### Additional information

* PrestaShop version: 1.7.8, develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | See issue ticket. Issues comes from 2 things: 1) a type mismatch and 2) a `declare(strict_types=1);` added to a 1.7.7 file (=> BC break). The PR fixes the type mismatch and remove the `declare(strict_types=1);`
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25081 & Fixes #22144
| How to test?      | see issue ticket.
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25082)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

File: src/Core/Domain/Product/Command/AssignProductToCategoryCommand.php [hunk 1]
```diff
@@ -24,8 +24,6 @@
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  */
 
-declare(strict_types=1);
```
Comment (matks) [inline src/Core/Domain/Product/Command/AssignProductToCategoryCommand.php:27]: For reviewers: adding this `declare(strict_types=1);` was a BC break because file existed without `declare(strict_types=1);` in 1.7.7

**Comment by Robin-Fischer-PS** [comment]
Thanks @zuk3975 for this quick fix !

It's QA :heavy_check_mark: :)

**Comment by matks** [comment]
Thanks @zuk3975 and @Robin-Fischer-PS
