### PR TITLE
Manage backward compatibility of legacy links

### LINKED ISSUE #10811: Can't transplant a module
**Describe the bug**
Can't transplant a module

**To Reproduce**
1. Go to Design > Position
2. Click on Transplant a module
3. You are still on the same page

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Manage backward compatibility of legacy links, see https://github.com/PrestaShop/PrestaShop/issues/10745 for more detail
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10811 #10745 #10804 #10817 
| How to test?  | To test this new feature you need to select this PR branch of course. Then the easiest way to test it is to use this module https://github.com/jolelievre/testlegacyurl<br />It displays all the migrated links and allows you to see if they have been correctly converted<br />You can also click on the legacy links to check if the redirection is correctly done<br />If you don't want to clone the module repository you can download it here [testlegacyurl.zip](https://github.com/PrestaShop/PrestaShop/files/2447813/testlegacyurl.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10868)

### CODE REVIEW

File: classes/Link.php [hunk 1]
```diff
@@ -803,55 +805,34 @@ public function getAdminLink($controller, $withToken = true, $sfRouteParams = ar
...
-        if (isset($sfRouter)) {
-            if (empty($routeName)) {
-                $routeName = $this->searchRouteFromRouter($sfRouter, $controller);
+        if (empty($routeName) && null !== $legacyUrlConverter) {
+            try {
+                $conversionParameters = array_merge(['controller' => $controller], $sfRouteParams, $params);
+                unset($conversionParameters['token']);
+
+                return $legacyUrlConverter->convertByParameters($conversionParameters);
+            } catch (CoreException $e) {
```
Comment (PierreRambaud) [inline classes/Link.php:800]: Add a comment to say you don't care if an exception occurred here.

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php [hunk 2]
```diff
@@ -0,0 +1,268 @@
...
+     *
+     * @return array
+     */
+    private function breakLegacyLink(Route $route)
+    {
+        $routeDefaults = $route->getDefaults();
+        $legacyLink = $routeDefaults['_legacy_link'];
+        $linkParts = explode(':', $legacyLink);
+        $legacyController = $linkParts[0];
+        $legacyAction = count($linkParts) > 1 ? $linkParts[1] : null;
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Routing/LegacyUrlConverter.php]: `isset($linkParts[1])` is maybe faster than count?

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php [hunk 3]
```diff
@@ -0,0 +1,268 @@
...
+            foreach ($routeDefaults['_legacy_parameters'] as $legacyParameter => $parameter) {
+                if (isset($parameters[$legacyParameter])) {
+                    $parameters[$parameter] = $parameters[$legacyParameter];
+                    unset($parameters[$legacyParameter]);
+                }
+            }
+        }
+
+        $legacyAction = $this->getActionFromParameters($parameters);
+        unset($parameters['controller']);
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Routing/LegacyUrlConverter.php:154]: make sure key exist before unset?

Comment (Quetzacoalt91) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php:154]: That's not needed, it won't throw any notice.

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php [hunk 4]
```diff
@@ -0,0 +1,268 @@
...
+     */
+    public function __construct(RouterInterface $router)
+    {
+        $this->router = $router;
+        $this->legacyRoutes = [];
+        $this->controllersActions = [];
+        /** @var Route $route */
+        foreach ($this->router->getRouteCollection() as $routeName => $route) {
+            $this->addRoute($routeName, $route);
+        }
```
Comment (Quetzacoalt91) [inline src/PrestaShopBundle/Routing/LegacyUrlConverter.php]: How long does it take to run this loop?

If the time needed is noticeable. It could be better to run it at the first real use of this class.

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php [hunk 5]
```diff
@@ -0,0 +1,268 @@
...
+     * @param array $parameters
+     * @param string $routeName
+     *
+     * @return array
+     */
+    private function convertParametersForRoute(array $parameters, $routeName)
+    {
+        $route = $this->legacyRoutes[$routeName];
+        $routeDefaults = $route->getDefaults();
+        if (!empty($routeDefaults['_legacy_parameters']) && is_array($routeDefaults['_legacy_parameters'])) {
```
Comment (Quetzacoalt91) [inline src/PrestaShopBundle/Routing/LegacyUrlConverter.php:144]: `if (is_array($routeDefaults['_legacy_parameters'])) {` could be enough. If the array is empty, the `foreach` will exit immediately.

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php]: good question, I can change it anyway and even use empty to be sure
But regarding the performance.. do you know which one is faster?

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php (hunk 3 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php:154]: yep, unset the world! don't give a sh**

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php (hunk 4 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php]: I don't think it is that long since it only creates a few arrays, but I can delay this creation via getters sure, it's probable for the best
Although since this service is called pretty early in the Listener it will have to perform it anyways, so I think the gain will be small

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php:144]: actually if the key doesn't exist (which is mostly the case for this parameter) then is_array will fail because of unexisting index
`empty` here is used as an `isset` purpose more than to check the size of the array

Comment (Quetzacoalt91) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php:144]: That's a clear explanation.

File: src/PrestaShopBundle/Routing/LegacyUrlConverter.php (hunk 2 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Routing/LegacyUrlConverter.php]: From what I read, isset is maybe one of the fastest function of php. it doesn't need loop or anything.

File: src/Core/Exception/CoreException.php [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
+namespace PrestaShop\PrestaShop\Core\Exception;
+
+/**
+ * Class CoreException, this is the default base class of every
+ * Exception classes from prestaShop.
+ */
+class CoreException extends \Exception
```
Comment (matks) [inline src/Core/Exception/CoreException.php:33]: We have https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Exception/PrestaShopCoreException.php
Either one of these 2 must extend the other or we must delete one of them.

File: src/Core/Exception/ErrorMessageException.php [hunk 7]
```diff
@@ -29,9 +29,9 @@
 use Throwable;
 
 /**
- * Class PrestaShopCoreException.
+ * Class ErrorMessageException.
  */
-class PrestaShopCoreException extends \Exception
+class ErrorMessageException extends CoreException
```
Comment (matks) [inline src/Core/Exception/ErrorMessageException.php]: Isn't it rather a `TranslationAwareException` as suggested by @sarjon in https://github.com/PrestaShop/PrestaShop/pull/10865#issuecomment-427034772 ?

File: src/PrestaShopBundle/Resources/config/services/bundle/routing.yml [hunk 8]
```diff
@@ -4,3 +4,8 @@ services:
         arguments:
           - '@=service("prestashop.module_kernel.repository").getActiveModulesPaths()'
         tags: [routing.loader]
+
+    prestashop.bundle.routing.legacy_url_converter:
+        class: 'PrestaShopBundle\Routing\LegacyUrlConverter'
+        arguments:
+            $router: '@router'
```
Comment (matks) [inline src/PrestaShopBundle/Resources/config/services/bundle/routing.yml:11]: 😮 I did not know this syntax for SF services
👍

File: src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2018 PrestaShop SA
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
+namespace PrestaShopBundle\Routing\Exception;
+
+use PrestaShop\PrestaShop\Core\Exception\ErrorMessageException;
+use Throwable;
```
Comment (matks) [inline src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php]: As found by sarjon in https://github.com/PrestaShop/PrestaShop/pull/10865 : careful with `Throwable` we still have to be php5.6-compatible

File: src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+     *
+     * @param string $key
+     * @param array $parameters
+     * @param null $domain
+     * @param int $code
+     * @param Throwable|null $previous
+     */
+    public function __construct($key, array $parameters = [], $domain = null, $code = 0, Throwable $previous = null)
+    {
+        parent::__construct($key, $domain, $parameters, $code, $previous);
```
Comment (matks) [inline src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php]: Why do you override the `__construct` if you copy the parent behavior ?

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php (hunk 10 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php]: it change $parameters and $domain order, but don't know why :/

**Comment by PierreRambaud** [comment]
Woot, what a work :+1:

File: src/Core/Exception/CoreException.php (hunk 6 above)
Comment (jolelievre) [reply src/Core/Exception/CoreException.php:33]: that's actually what I did in this PR, introducing a very basic `CoreException`

File: src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php (hunk 10 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php]: be cause I didn't have a domain for this exception, but it is a bad idea to leave it empty, and this kind of exception is not displayed as an error message or notification
So I changed it to a more common CoreException

File: src/Core/Exception/ErrorMessageException.php (hunk 7 above)
Comment (jolelievre) [reply src/Core/Exception/ErrorMessageException.php]: yep good idea, although I don't like `TranslationAwareException` because it gives the feeling that the Exception is capable of translating itself, as if it contained the translator service
I prefered `TranslatableCoreException` which seems more correct to me

File: src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php (hunk 9 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php]: ok, I integrated the modif but can you check if it is good `TranslatableCoreException`
Especially the `use` part, is it ok to have `use Throwable` in php 5.6 or should I use `\Throwable` and `\Exception` instead?

File: src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml [hunk 11]
```diff
@@ -41,6 +44,17 @@ admin_module_manage:
         keyword:
         _controller: PrestaShopBundle:Admin/Improve/Module:manage
         _legacy_controller: AdminModulesManage
+        _legacy_link: AdminModulesManage
+
+admin_module_manage_alias:
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml]: make `_legacy_link` a possible array for aliases will be better, no?
```yml
_legacy_link:
  - AdminModuleManager
  - AdminModulesSf
```

File: src/PrestaShopBundle/Resources/config/services/bundle/routing.yml (hunk 8 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/config/services/bundle/routing.yml:11]: FYI: https://symfony.com/blog/new-in-symfony-3-4-local-service-binding
Can be useful :)

File: src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml (hunk 11 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml]: yeah, I'm gonna add this feature

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml]: done!

File: classes/Link.php (hunk 1 above)
Comment (jolelievre) [reply classes/Link.php:800]: done

File: src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml [hunk 12]
```diff
@@ -44,17 +44,9 @@ admin_module_manage:
...
-admin_module_manage_alias:
-    path:     /manage/{category}/{keyword}
-    methods:  [GET]
-    defaults:
-        category:
-        keyword:
-        _controller: PrestaShopBundle:Admin/Improve/Module:manage
-        _legacy_controller: AdminModulesManage
-        _legacy_link: AdminModulesSf
+        _legacy_link:
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/config/routing/admin/improve/modules/_modules.yml:47]: :+1:

**Review by PierreRambaud — DISMISSED** [review]
Nice work again!

File: tests/Integration/PrestaShopBundle/Routing/LegacyUrlConverterTest.php [hunk 13]
```diff
@@ -32,12 +32,15 @@
 use Link;
 use ReflectionClass;
 
+/**
+ * @group demo
```
Comment (sarjon) [inline tests/Integration/PrestaShopBundle/Routing/LegacyUrlConverterTest.php:36]: offtopic question, but how do you know which group it belongs to? :thinking: is there any docs regarding it?

Comment (jolelievre) [reply tests/Integration/PrestaShopBundle/Routing/LegacyUrlConverterTest.php:36]: well.. I just found out about these groups 😄
so I used one of those defined in phpunit-admin.xml because it was the only way to make my tests work.. (not very proud of this 🤫)

Comment (sarjon) [reply tests/Integration/PrestaShopBundle/Routing/LegacyUrlConverterTest.php:36]: @matks we could improve it. :)

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php (hunk 9 above)
Comment (matks) [reply src/PrestaShopBundle/Routing/Exception/RouteNotFoundException.php]: I tried, it seems the `use` is not a issue for php5.6

**Review by matks — DISMISSED** [review]

File: tests/Integration/PrestaShopBundle/Routing/LegacyUrlConverterTest.php (hunk 13 above)
Comment (matks) [reply tests/Integration/PrestaShopBundle/Routing/LegacyUrlConverterTest.php:36]: Yes we can !

**Comment by marionf** [comment]
@jolelievre 

I have an exception when I click on Design > Theme & logo > Theme custo

capture d ecran_421

When I click on Shop parameters > Traffic & SEO > Add new page or edit, I have this:

capture d ecran_422

I have also these exceptions when I click on some links in your module, but maybe it's normal ?

capture d ecran_423

capture d ecran_424

capture d ecran_425

**Comment by PierreRambaud** [comment]
@marionf I fix issues and it's normal for these links. (Allow only in POST / DELETE)

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @jolelievre
