### PR TITLE
Use core translations sources for themes in addition to the translations of the theme itself

### LINKED ISSUE #26549: Exported translations are not working properly
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you export translations for the custom theme, and the language different than English, in International -> Translations translations are exported with mixed English and custom language. This is because of some core translations like Shop.Theme.Global, etc., are being exported in English, and only custom translations are in Polish.

### Expected behavior

When we export, let's say, French translations for a custom theme, all translations should be in French. Default ones (from the default catalog that were not modified) and custom ones.

The translations to export should be loaded and overridden in this order (the last one being the one that "wins" if it exists):

1. default catalogue (untranslated)
2. core xlf (translated)
3. database translation (no theme)
4. theme xlf (translated)
5. database translation (theme)

### Steps to reproduce

1. You need to have at least two languages.
2. You need to have a custom theme installed. It could even be a duplicate of the classic with a different name.
3. Now export translations for your theme and for the language different than English
4. Open the downloaded package, and see that in the package, you have `.xlf` files with English translations instead of translations in your exported language.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #27410: BO: Themes translation are empty in BO
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Themes translations are empty in the BO:
Screenshot_1
Screenshot_2
But all tested themes by me fully translated to French and the translations appear in Front office:
Screenshot_3
Screenshot_4
Screenshot_5
But these translations are empty in BO:
Screenshot_6
Screenshot_7
This problem occur since the PrestaShop 1.7.8.0. 
There are not this problem in previous PrestaShop versions.

### Expected behavior

I expect to see all translations filled in BO because all phrases were translated in tested themes.

### Steps to reproduce

1. Install any custom theme (except "Classic".) that was translated to other languages.
2. Go to Translations:
Screenshot_1

3. And see that most of translations are empty
Screenshot_2
:

### PrestaShop version(s) where the bug happened

1.7.8.0 - 1.7.8.2

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Since #23296, one of the path given to `PrestaShop\PrestaShop\Core\Translation\Provider\CatalogueProviderFactory` was wrong, this PR fixes it. Also, core translations where not take into account when translating a theme (other than classic) that uses core wordings. This PR fixes it by loading core translations first, then overwrite them with theme translations (if present).
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #27410 & #26549
| How to test?      | Please see #27410 & #26549
| Possible impacts? | 

#### Deprecation
The constructor of `PrestaShop\PrestaShop\Core\Translation\Storage\Provider\ThemeCatalogueLayersProvider` takes now a `PrestaShop\PrestaShop\Core\Translation\Storage\Provider\ModuleCatalogueProviderFactory` as first argument

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27422)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @atomiix,

I tried with different themes

**With PR**
image
**Without PR**
image


But I have an issue following these steps:
1. Go to BO > International > Translations page
2. Choose `Type of translation` = `Front office Translations` / `Select your theme = Core` / choose a language for example French and click on Modify
3. Search the expression `PERSONAL INFORMATION`, change it and save 
image
4. Go to FO & check that the translation is well changed 
5. Go to BO > Design > Theme & Logo > Upload a new theme & Use it
6. Go to BO > International > Translations page
7. Choose `Type of translation` = `Front office Translations` / `Select your theme = Your new theme` / choose a language = French and click on Modify
8. Search the expression `PERSONAL INFORMATION`, change it and save 
image
9. Go to FO & check that the translation is not saved & the first translation is displayed of the core theme
image

Thanks!

**Comment by atomiix** [comment]
@khouloudbelguith you're not modifying the same string. The first one is `Personal Information` in `Shop.Theme.Checkout`, the second is `Your personal information` in `Shop.Theme.Customeraccount`.

The first one (`Personal Information`) is not available when selecting a theme because the string is not in the templates but [in the core](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutPersonalInformationStep.php#L95).

However, you can try with the second one (`Your personal information`) that will be showed in `Home > Your account > Information`

**Review by khouloudbelguith — COMMENTED** [review]
Hi

I checked this PR with @atomiix in private because we are using some themes that cannot be published.
1. Install this PR using English language & France country
2. Upload the `pinkwep` theme (or another specific theme cannot be published here)
[pinkwep.zip](https://github.com/PrestaShop/PrestaShop/files/8002731/pinkwep.zip)
3. Use it
4. Go to BO > International > Translations > `Type of translation = Front office translations` + Pinkwep + **English**
5. Click on Modify
6. See error => There are `254 missing` 
image

If we try these steps with PS1778 using **English** language only => OK 
image

But when we use PS1778 + **French** language => NOK
image
image

Ping @PrestaShop/product-team what do you think?

Thanks!

**Comment by SharakPL** [comment]
That's why this whole translation system of PS 1.7 is so messed up from the beginnig. Old one was so much better even despite high `max_input_vars` requirements. The only good feature here is that you can translate only specific module instead of all at once.

From what I've heard on the forums and FB groups, the problem here is some translations have to be changed inside Classic theme, even when you use different theme.

File: src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php [hunk 1]
```diff
@@ -137,12 +137,23 @@ public function getDefaultCatalogue(
...
+        $coreCatalogue = $this->coreFrontProvider->getFileTranslatedCatalogue($locale);
+
+        // load core user-translated catalogue
+        $coreUserTranslatedCalalogue = (new UserTranslatedCatalogueFinder(
+            $this->databaseTranslationLoader,
+            ['*']
+        ))
+            ->getCatalogue($locale);
+
+        $coreCatalogue->addCatalogue($coreUserTranslatedCalalogue);
```
Comment (SharakPL) [inline src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php]:
```suggestion
        $coreUserTranslatedCatalogue = (new UserTranslatedCatalogueFinder(
            $this->databaseTranslationLoader,
            ['*']
        ))
            ->getCatalogue($locale);

        $coreCatalogue->addCatalogue($coreUserTranslatedCatalogue);
```

**Review by SharakPL — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/config/services/bundle/translation.yml [hunk 2]
```diff
@@ -164,11 +164,6 @@ services:
             - "@prestashop.core.admin.lang.repository"
             - "@prestashop.core.admin.translation.repository"
 
-    prestashop.translation.sql_loader:
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Resources/config/services/bundle/translation.yml:167]: You should deprecate it instead of removing it :thinking:

**Review by PierreRambaud — DISMISSED** [review]
Just one comment which is not mandatory

File: src/PrestaShopBundle/Resources/config/services/bundle/translation.yml (hunk 2 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/config/services/bundle/translation.yml:167]: You're right, I can even keep it completely, this class is used in legacy, I can just remove the `tags` part 👍

File: src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php [hunk 3]
```diff
@@ -137,12 +137,23 @@ public function getDefaultCatalogue(
      *
      * @return MessageCatalogue
      *
-     * @throws TranslationFilesNotFoundException
+     * The **file** translated catalogue for a theme other than classic corresponds
+     * to the core files, overwrite by the user-translated core wordings (if any), overwrite
+     * by the theme files (if any)
```
Comment (jolelievre) [inline src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php]:
```suggestion
     * The **file** translated catalogue for a theme other than classic corresponds
     * to the core files, overwritten by the user-translated core wordings (if any), overwritten
     * by the theme files (if any)
```

Comment (jolelievre) [reply src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php]: Suggestion onlly

File: src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php [hunk 4]
```diff
@@ -137,12 +137,23 @@ public function getDefaultCatalogue(
...
      */
     public function getFileTranslatedCatalogue(string $locale): MessageCatalogue
     {
         // load front office catalogue
-        $catalogue = $this->coreFrontProvider->getFileTranslatedCatalogue($locale);
+        $coreCatalogue = $this->coreFrontProvider->getFileTranslatedCatalogue($locale);
+
+        // load core user-translated catalogue
+        $coreUserTranslatedCatalogue = (new UserTranslatedCatalogueFinder(
```
Comment (jolelievre) [inline src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php]: Shouldn't `UserTranslatedCatalogueFinder` be injected instead?

Comment (jolelievre) [reply src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php]: Or at least use:

```suggestion
        $coreUserTranslatedCatalogue = $this->getUserTranslatedCatalogue($locale);
```

Which has the exact same code (this doesn't mean it can't be injected and used in the method)

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php [hunk 5]
```diff
@@ -92,20 +92,43 @@ public function loadLanguage(TranslatorInterface $translator, $locale, $withDB =
...
+            }
+        }
 
-        foreach ($finder as $file) {
-            list($domain, $locale, $format) = explode('.', $file->getBasename(), 3);
-            $translator->addResource($format, $file, $locale, $domain);
-            if ($withDB) {
-                $translator->addResource('db', $domain . '.' . $locale . '.db', $locale, $domain);
+        // Load theme user-translated wordings for core + theme wordings
+        if (!$this->isAdminContext) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php:129]: Why isn't this included in the loop before? Is it important that those domains are added after the user translated resources? What is the difference with what you do on L122? `$translator->addResource('db', $domain . '.' . $locale . '.db', $locale, $domain);`

Seems like it's the same code except for the resource name

Comment (jolelievre) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php:129]: Oh it's the resource format actually so I guess it makes the whole difference, it's related to a special loader I guess

**Review by jolelievre — COMMENTED** [review]
Thanks @atomiix 

I don't understand everything 😅
But it seems ok, I just had a few suggestions

Waiting for your answers and/or modif then I approve

File: src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php (hunk 4 above)
Comment (atomiix) [reply src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php]: It's not the **exact** same code, in the `getUserTranslatedCatalogue()` method, we add the theme name, not here 🙃

File: src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php (hunk 5 above)
Comment (atomiix) [reply src/PrestaShopBundle/Translation/TranslatorLanguageLoader.php:129]: Exactly, there is one "core" db loader and one "theme" db loader, and indeed, order matters!

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by khouloudbelguith — DISMISSED** [review]
Hello @atomiix,

I found a difference between this PR and PS1778.
1. Install this PR using English language & France country
2. Upload the custom theme provided in the private discussion
3. Use it
4. Go to BO > International > Translations > `Type of translation = Front office translations` + theme + **English**
5. Click on Modify
6. See the  error 
image

I tried the same steps with PS1778 => OK

image

I tried another theme
1. Install this PR using English language & France country
2. Upload the `pinkwep` theme (or another specific theme cannot be published here)
[pinkwep.zip](https://github.com/PrestaShop/PrestaShop/files/8002731/pinkwep.zip)
3. Use it
4. Go to BO > International > Translations > `Type of translation = Front office translations` + Pinkwep + **English**
5. Click on Modify 
image

I checked PS1778 => OK
image

Thanks!

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/config/services/bundle/translation.yml [hunk 6]
```diff
@@ -57,7 +57,7 @@ services:
             - '@prestashop.translation.extractor.theme'
             - '@prestashop.core.addon.theme.repository'
             - '@filesystem'
-            - '%themes_translations_dir%'
```
Comment (lmeyer1) [inline src/PrestaShopBundle/Resources/config/services/bundle/translation.yml:60]: @atomiix Is there a reason why you fixed here, but you didn't fix also on line 108 https://github.com/PrestaShop/PrestaShop/blob/6e4a76d183753fcef267eb565710600a439dc8d2/src/PrestaShopBundle/Resources/config/services/bundle/translation.yml#L108

I didn't find what `$this->resourceDirectory` in `Translation/Provider/ThemeProvider.php` is used for, but I'm sure it is pointing to the wrong place too.

**Review by lmeyer1 — CHANGES_REQUESTED** [review]

File: src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php [hunk 7]
```diff
@@ -152,13 +163,12 @@ public function getFileTranslatedCatalogue(string $locale): MessageCatalogue
                 ->getCatalogue($locale);
 
             // overwrite with the theme's own catalogue
-            $catalogue->addCatalogue($fileTranslatedCatalogue);
+            $coreCatalogue->addCatalogue($fileTranslatedCatalogue);
         } catch (TranslationFilesNotFoundException $e) {
-            // there are no translation files, ignore them
-            return new MessageCatalogue($locale);
+            // No translation file was found in the theme, we keep using those from the core
```
Comment (lmeyer1) [inline src/Core/Translation/Storage/Provider/ThemeCatalogueLayersProvider.php:178]: Good catch ! 👍  I found this one too.

**Comment by lmeyer1** [comment]
@atomiix You address only the problem with the theme translations of the `Shop` domain, but not for the `Modules` domain.
Is it planned to fix it for the `Modules` domain too ?

Capture d’écran 2022-03-18 172418 modifié

File: src/PrestaShopBundle/Resources/config/services/bundle/translation.yml (hunk 6 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/config/services/bundle/translation.yml:60]: You're right! But from what I found, `ThemeProvider` is used when you try to export a theme. There's maybe an issue because of this probably wrong path but I think it's out of the scope of this PR and may need a dedicated issue.

**Comment by atomiix** [comment]
@lmeyer1, I think both are fixed in this PR. I'm loading the full core translations files as default values.

**Comment by lmeyer1** [comment]
@atomiix 
I tested this PR by merging it locally in my dev env, it didn't seem to work. But maybe the tests were just too quickly done. 

So no problem, I wait for it to be merged hopefully in the next release.

**Review by matks — DISMISSED** [review]

**Review by khouloudbelguith — DISMISSED** [review]
Hi @atomiix,

I have an issue following these steps:
1. Install this PR with the English language and France country
2. Go to BO > Design > Theme & Logo page
3. Add this theme or the other theme provided in private
[pinkwep.zip](https://github.com/PrestaShop/PrestaShop/files/8372918/pinkwep.zip)
4. Go to BO > International > Translations page T`ype of translation = Front office translations` + theme + `French`
5. Click on Modify
6. See the error
image

I tried with the English language => OK
image

Also, I have an issue following these steps:
1. Install this PR with the French language & France country
2. Upload this theme: https://github.com/prestarocket-agence/classic-rocket
3. Use this theme
4. Go to FO > Add a comment and approve it from BO
5. Now check the product again 
image
4. Go to BO > International > Translations page Type of translation = Front office translations` + theme + `French`
5. Click on Modify
6. Search for the expression 
7. See error, it is empty but in the FO => OK
image

I checked other expressions:
**FO** => OK
image
**BO** => NOK
image

Thanks!

**Comment by rodriciru** [comment]
In PS 1.7.8.5 wont work for me. But it fixed the issue of my theme .xlf files not begin in BO Translation manager.
Now i can see theme xlf in BO and export them. 
Previously, as the Translation manager wont show the theme xlf files, it only exports strings in english unless i manually override and saved in DB

**Comment by atomiix** [comment]
@khouloudbelguith for the 1st issue, it's the expected behavior: there is no translations for these wordings (neither in french nor english) but in english we can "fallback" on the source wording, that's why it's not missing in english.

For the second issue, I updated my PR and it should be ok now.

**Review by lmeyer1 — DISMISSED** [review]
Thanks @atomiix

**Comment by atomiix** [comment]
You're welcome @lmeyer1, you were right about the `Modules*` domain indeed!

**Review by jolelievre — DISMISSED** [review]
Thanks @atomiix

**Review by kpodemski — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hi @atomiix,

I found those issues:

**First issue**
1. Install this PR with English language & France country
2. Add this theme https://github.com/prestarocket-agence/classic-rocket and use it as a theme
3. Go to BO > International > Translations page `Type of translation = Front office translations` + `theme` + `French`
4. Check the section of the module GDPR 
image
5. Try to translate any expression and save for example 
image
6. Go to FO > Sing in > Your account > GDPR - Personal data (fr/module/psgdpr/gdpr): check the data is not translated
image

PS: I checked PS1785 and PS1778 => same behavior
What do you think, is it out of the scope of this PR?

---------------------------------------------------------

**Second issue**
1. Install this PR with English language & France country
2. Add this theme https://github.com/prestarocket-agence/classic-rocket and use it as a theme
3. Go to BO > International > Translations page `Type of translation = Front office translations` + `theme` + `French`
4. Search this expression `Your personal information`, change it, and save 
image
5. Go to FO > Checkout page > See error: no translation saved 
image
6. Go to BO > International > Translations page `Type of translation = Front office translations` + `Core` + `French`
7. Search this expression `Your personal information`, change it, and save 
image
8. Go to FO > Checkout page > See error: the new expression is well displayed but was are using the classic-rocket theme
image


PS: I checked PS1785 and PS1778 => same behavior
What do you think, is it out of the scope of this PR?


-----------------------------------

**Third issue**
1. Install this PR with English language & France country
2. Add this theme https://github.com/prestarocket-agence/classic-rocket and use it as a theme
3. Go to BO > International > Translations page `Type of translation = Installed modules translations` + `Official GDPR compliance` + `French`
4. In the Section `customerPersonalData` try to change the data, save and stay 
image
5. Go to FO > Sing in > Your account > GDPR - Personal data (fr/module/psgdpr/gdpr): check the data is not translated 
image
6. Go to BO > International > Translations page `Type of translation = Front office translations` + `theme` + `French`
7. Check the section of the module GDPR => NOK, but in the FO is well displayed in French 
image

I attached a screen record

https://user-images.githubusercontent.com/16067358/163808567-1304e6f4-94e2-40d6-8b1c-34ce750bf9f8.mp4

Thanks!

File: config/smartyfront.config.inc.php [hunk 8]
```diff
@@ -171,8 +173,20 @@ function smartyTranslate($params, $smarty)
     if (!isset($params['sprintf'])) {
         $params['sprintf'] = array();
     }
+
+    // fix inheritance template filename in case of includes from different cross sources between theme, modules, ...
+    $filename = $smarty->template_resource;
+    if (!isset($smarty->inheritance->sourceStack[0]) || $filename === $smarty->inheritance->sourceStack[0]->resource) {
```
Comment (Progi1984) [inline config/smartyfront.config.inc.php:179]: You chould check the type of `sourceStack[0]` or if `resource` exists.

File: config/smartyfront.config.inc.php [hunk 9]
```diff
@@ -171,8 +173,20 @@ function smartyTranslate($params, $smarty)
...
+    }
+    $basename = basename($filename, '.tpl');
+
     if (!isset($params['d'])) {
-        $params['d'] = null;
+        if ($params['mod']) {
+            $params['d'] = DomainHelper::buildModuleDomainFromLegacySource($params['mod'], $basename);
+        } else {
+            $params['d'] = null;
+        }
```
Comment (Progi1984) [inline config/smartyfront.config.inc.php]:
```suggestion
        $params['d'] = $params['mod'] ? DomainHelper::buildModuleDomainFromLegacySource($params['mod'], $basename) : null;
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback

File: config/smartyfront.config.inc.php (hunk 8 above)
Comment (atomiix) [reply config/smartyfront.config.inc.php:179]: if `$smarty->inheritance->sourceStack[0]` exists, `$smarty->inheritance->sourceStack[0]->resource` necessarily exists too.
Here you can see that what's pushed to `sourceStack`:
https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_runtime_inheritance.php#L246

It's a `Smarty_Template_Source`:
https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_internal_template.php#L71

and `Smarty_Template_Source` contains `$resource`:
https://github.com/smarty-php/smarty/blob/master/libs/sysplugins/smarty_template_source.php#L25

**Comment by atomiix** [comment]
@khouloudbelguith issue 1 & 3 should be fixed now.

For the second issue though, it's the "normal" behavior. The first expression you're translating (`Your personal information`) is not the one displayed in the checkout page. You can't find the "real" `Personal information` when you translate the classic-rocket theme because the theme itself doesn't use this expression, it is used directly inside a core Controller.
That's why you can find it when translating the core.

**Review by matks — APPROVED** [review]

File: config/smartyfront.config.inc.php (hunk 8 above)
Comment (Progi1984) [reply config/smartyfront.config.inc.php:179]: But like it's public properties, we can define any types so we should check the type of sourceStack[0]

**Review by Progi1984 — COMMENTED** [review]
A last comment

**Comment by atomiix** [comment]
@Progi1984 I can't see your last comment 🤔

File: config/smartyfront.config.inc.php (hunk 8 above)
Comment (Progi1984) [reply config/smartyfront.config.inc.php:179]: Ping @atomiix

**Review by kpodemski — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hello @atomiix, @kpodemski,

The review of @kpodemski was removed by mistake.

Sorry :slightly_smiling_face:

**Review by khouloudbelguith — COMMENTED** [review]
Hello @atomiix,

I tried the first issue, I stll manage to reproduce the issue.
Steps to reproduce the issue:
1. Install this PR with English language & France country
2. Add this theme https://github.com/prestarocket-agence/classic-rocket and use it as a theme
3. Go to BO > International > Translations page `Type of translation = Front office translations` + `theme` + `French`
4. Check the section of the module GDPR 
5. Try to translate any expression and save for example 
6. Go to FO > Sing in > Your account > GDPR - Personal data (fr/module/psgdpr/gdpr): check the data is not translated

PS: I tried with Fensh & italian
I attached a screen record

https://user-images.githubusercontent.com/16067358/174597377-03372e00-c8bb-48f4-bfec-b33897816c0e.mp4

------------------------------------------------------------

I tried the third issue, the Step 7 is still reproduced
Steps to reproduce the issue:
1. Install this PR with English language & France country
2. Add this theme https://github.com/prestarocket-agence/classic-rocket and use it as a theme
3. Go to BO > International > Translations page `Type of translation = Installed modules translations` + `Official GDPR compliance` + `French`
4. In the Section `customerPersonalData` try to change the data, save 
5. Go to FO > Sing in > Your account > GDPR - Personal data (fr/module/psgdpr/gdpr): check the data is **translated**  (issue **fixed)**
6. Go to BO > International > Translations page `Type of translation = Front office translations` + `theme` + `French`
7. Check the section of the module GDPR => NOK, but in the FO is well displayed in French 

I attached a screen record

https://user-images.githubusercontent.com/16067358/174597853-213ebfc3-e7f2-4586-8dfb-603e2465acd6.mp4

Thanks!

**Comment by atomiix** [comment]
@khouloudbelguith It looks like the issue comes from the theme. It tries to override the file `customerPersonalData17.tpl` of the module psgdpr but this file doesn't exist anymore. If you rename `themes/classic-rocket/modules/psgdpr/views/templates/front/customerPersonalData17.tpl` to `themes/classic-rocket/modules/psgdpr/views/templates/front/customerPersonalData.tpl` though, everything should be working.

**Review by khouloudbelguith — APPROVED** [review]
Hi @atomiix,

It is ok :heavy_check_mark: 
Automatic test => OK
[Mochawesome Report.pdf](https://github.com/PrestaShop/PrestaShop/files/9235928/Mochawesome.Report.pdf)

About this issue: https://github.com/PrestaShop/PrestaShop/issues/27410
I tried with 4 different themes & a child theme => ok, I tried with French & Italian

https://user-images.githubusercontent.com/16067358/182208196-73226650-d728-4054-8928-200b25bfd869.mp4

I checked this issue https://github.com/PrestaShop/PrestaShop/issues/26549 => OK

https://user-images.githubusercontent.com/16067358/182208853-54a55742-59ec-4ae5-b13f-0d846c61e1d9.mp4

Export in the specific language 
image
image

Also, I tried to translate all types with English language:
- Back office 
- Front Office Core
- Email Subject
- Email Core
- Module Newsletter
- Other

Thanks!

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @atomiix & @khouloudbelguith 🎉
