### PR TITLE
Fix lang on currency install

### LINKED ISSUE #13249: Create currency has no names nor symbols
**Describe the bug**
I go to "International > Localization > Currencies" page in the Back office.
I try to create a new currency, select it and set a rate, then click save
The currency is added I can see it in the back office and in the database
However is localized info (in `currency_lang`) are empty (name and symbol)
The numeric_iso_code is also missing (and I'm not sure about the precision but 0 seems suspect)

**Screenshots**
Capture d’écran 2019-04-09 à 10 25 16

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | fix a bug on currency install, resulting in unexisting rows for currency_lang
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | fixes #13249 #13247 #13271
| How to test?  | install with lang=en, country=fr, both languages should work on frontoffice. Please check if it resolves the second issue @jolelievre is talking about in the comments of this issue #13249

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13261)

### CODE REVIEW

File: classes/LocalizationPack.php [hunk 1]
```diff
@@ -352,7 +352,20 @@ protected function _installCurrencies($xml, $install_mode = false)
...
+                    // Following is required when installing new currency on existing languages:
+                    // we want to properly update the symbol in each language
+                    $languages = Language::getLanguages();
+                    $context = Context::getContext();
+                    $container = isset($context->controller) ? $context->controller->getContainer() : null;
+                    if (null === $container) {
+                        $container = SymfonyContainer::getInstance();
+                    }
+                    /** @var LocaleRepository $localeRepoCLDR */
+                    $localeRepoCLDR = $container->get('prestashop.core.localization.cldr.locale_repository');
```
Comment (Quetzacoalt91) [inline classes/LocalizationPack.php]: You already have this code in the file. Can you please refacto in a common method?

**Review by Quetzacoalt91 — DISMISSED** [review]

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php [hunk 2]
```diff
@@ -88,4 +93,23 @@ private function assertCurrencyWithIsoCodeDoesNotExist($isoCode)
...
+     * @param string $isoCode
+     *
+     * @throws CurrencyConstraintException
+     */
+    private function refreshLocalizedCurrencyData(Currency $currency)
+    {
+        // Following is required when installing new currency on existing languages:
+        // we want to properly update the symbol in each language
+        $context = Context::getContext();
+        $container = isset($context->controller) ? $context->controller->getContainer() : null;
```
Comment (matks) [inline src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: Please do not load the container this way 😉 . Inject the required service in the constructor:
```
    /**
     * @param int $localeRepoCLDR
     */
    public function __construct($localeRepoCLDR)
    {
        $this->localeRepoCLDR = $localeRepoCLDR;
    }
```
and configure this service dependency injection accordingly in https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/adapter/currency.yml#L21:
```
    prestashop.adapter.currency.command_handler.create_currency:
        class: 'PrestaShop\PrestaShop\Adapter\Currency\CommandHandler\AddCurrencyHandler'
        arguments:
          - '@prestashop.core.localization.cldr.locale_repository'
```

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php [hunk 3]
```diff
@@ -26,13 +26,17 @@
 
 namespace PrestaShop\PrestaShop\Adapter\Currency\CommandHandler;
 
+use Context;
 use Currency;
+use Language;
+use PrestaShop\PrestaShop\Adapter\SymfonyContainer;
```
Comment (matks) [inline src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: Unneeded (see below)

File: classes/Currency.php [hunk 4]
```diff
@@ -758,4 +761,40 @@ public static function isMultiCurrencyActivated($idShop = null)
...
+     * @throws PrestaShopException
+     * @throws \PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException
+     */
+    public function refreshLocalizedCurrencyData(array $languages, LocaleRepository $localeRepoCLDR)
+    {
+        $symbolsByLang = $namesByLang = [];
+        foreach ($languages as $languageData) {
+            $language = new Language($languageData['id_lang']);
+            if ($language->locale === '') {
+                // Language doesn't have locale we can't install this language
```
Comment (jolelievre) [inline classes/Currency.php:781]: Did you see any case where this happened? During install maybe when language are not saved yet?
I'm wondering if this would require an exception/error rather than ignoring it (same old question with legacy code..)

File: classes/Currency.php [hunk 5]
```diff
@@ -758,4 +761,40 @@ public static function isMultiCurrencyActivated($idShop = null)
...
+                continue;
+            }
+
+            $cldrLocale = $localeRepoCLDR->getLocale($language->locale);
```
Comment (jolelievre) [inline classes/Currency.php:786]: Could you add some PHPDoc please so that we know which type of objects we're dealing with, to avoid confusion
(Maybe a fully qualified PHPDoc to avoid a use statement and "coupling" the two classes?)

File: classes/LocalizationPack.php [hunk 6]
```diff
@@ -352,7 +352,13 @@ protected function _installCurrencies($xml, $install_mode = false)
                         return false;
                     }
                     Cache::clear();
+                    // set default data from CLDR
                     $this->setCurrencyCldrData($currency, $defaultLang);
+
+                    // Following is required when installing new currency on existing languages:
+                    // we want to properly update the symbol in each language
+                    $localeRepoCLDR = $this->getCldrLocaleRepository();
+                    $currency->refreshLocalizedCurrencyData(Language::getLanguages(), $localeRepoCLDR);
```
Comment (jolelievre) [inline classes/LocalizationPack.php:361]: It's sad that we add this public method for this.. Even though it's a good thing to perform this modif in a single place, though you need to inject the repo in it Maybe it should be a service which makes this update rather than the `Currency` itself

File: install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php [hunk 7]
```diff
@@ -37,4 +41,18 @@ function ps_1760_copy_data_from_currency_to_currency_lang()
             "
         );
     }
+    /** @var Currency[] $currencies */
```
Comment (jolelievre) [inline install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php:44]: Right it's a good thing to perform it on upgrade as well. I'm wondering though, is the SQL query still useful with this new code?

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: Unneeded because unused you mean? Shouldn't the CSFixer remove this?

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php [hunk 8]
```diff
@@ -57,6 +75,7 @@ public function handle(AddCurrencyCommand $command)
             $entity->iso_code = $command->getIsoCode()->getValue();
             $entity->active = $command->isEnabled();
             $entity->conversion_rate = $command->getExchangeRate()->getValue();
+            $entity->refreshLocalizedCurrencyData(Language::getLanguages(), $this->localeRepoCLDR);
```
Comment (jolelievre) [inline src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php:75]: I know this is an adapter handler and we will still have some Legacy code (starting with ObjectModel), but we should limit their use as much as we can So maybe you could use `LanguageRepositoryInterface` instead, and add it a `getLanguages` method (this interface is new we won't be able to change it in later versions so we might as well do it while we can)

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @tomlev, a few improvements suggested, but I can't wait for this one to be merged.

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php (hunk 3 above)
Comment (tomlev) [reply src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: it should.
it didn't.
I do.

File: classes/Currency.php (hunk 4 above)
Comment (tomlev) [reply classes/Currency.php:781]: honestly (and unfortunately) I do not remember the reason of this test.

File: install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php (hunk 7 above)
Comment (tomlev) [reply install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php:44]: I think it is not required, but if any change is made to refreshLocalizedCurrencyData method, it could not update _lang table anymore.
That's why I did not delete the SQL query.

File: classes/LocalizationPack.php (hunk 6 above)
Comment (tomlev) [reply classes/LocalizationPack.php:361]: I think it could be done in next step for CLDR (currency/language cutomization)
this method is a best effort to properly update currency data from CLDR.

Comment (tomlev) [reply classes/LocalizationPack.php:361]: more precisely : in this version the method override currency_lang data
in next version with customization it will not, we will have to find a better way to update data

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: That's weird, so the CSFixer has issues? Or you just forgot it?

File: classes/Currency.php (hunk 4 above)
Comment (jolelievre) [reply classes/Currency.php:781]: ok met's leave it then

File: classes/LocalizationPack.php (hunk 6 above)
Comment (jolelievre) [reply classes/LocalizationPack.php:361]: well in the next version it will still update the data if they are not present right?
but ok for an improvement in next version

File: install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php (hunk 7 above)
Comment (jolelievre) [reply install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php:44]: So you're saying the two actually do the same things?

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php (hunk 3 above)
Comment (tomlev) [reply src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: I forgot it, but it used to bloc travis test, wasn't it ?

File: classes/Currency.php [hunk 9]
```diff
@@ -782,7 +782,9 @@ public function refreshLocalizedCurrencyData(array $languages, LocaleRepository
                 continue;
             }
 
+            // CLDR locale give us the CLDR reference specification
```
Comment (jolelievre) [inline classes/Currency.php:785]: I was actually thinking about something more technical and straight forward like:
```php
/** @var \PrestaShop\PrestaShop\Core\Localization\CLDR\Locale $cldrLocale */
```

File: src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/Currency/CommandHandler/AddCurrencyHandler.php]: Yes but now the lint is out of the travis tests, and performed by github actions
But we need to check our workflow as the checks are not performed on PRs nor do they block the merge..

File: install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php (hunk 7 above)
Comment (tomlev) [reply install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php:44]: not exactly:
SQL query insert rows in currency_lang
php updates localized data.
if php script does not have any data to update, it will not create the rows

File: classes/Currency.php (hunk 9 above)
Comment (tomlev) [reply classes/Currency.php:785]: hum it is already correctly typehinted by my IDE

Comment (jolelievre) [reply classes/Currency.php:785]: think about people using emacs 😇
or who are simply reading the code on github

File: install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php (hunk 7 above)
Comment (jolelievre) [reply install-dev/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php:44]: alright

**Review by jolelievre — APPROVED** [review]
