### PR TITLE
Hide product quantity in Order view page when stock management is disabled

### LINKED ISSUE #21767: When stock management is disabled, the available quantity in order detail is displayed
#### Describe the bug

When stock management is disabled, the available quantity in order detail is displayed

#### Expected behavior

When stock management is disabled, the available quantity in order detail shouldn't be displayed

#### Steps to Reproduce

1. Go to Shop parameters > Product settings
2. Disable stock management
3. Go to Orders > Orders > View an order
4. The "available" quantity is displayed while it shouldn't

**Screenshots**

**1.7.7**
capture d'écran_2851

**1.7.6**
capture d'écran_2852

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Hide product quantity in Order view page when PS_STOCK_MANAGEMENT is disabled
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21767
| How to test?  | In Shop Parameters > product settings disable `Enable stock management` option The order view page shouldn't display product stock available quantities any more

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22082)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 1]
```diff
@@ -528,6 +528,7 @@ public function viewAction(int $orderId, Request $request): Response
             'nextOrderId' => $orderSiblingProvider->getNextOrderId($orderId),
             'paginationNum' => $paginationNum,
             'paginationNumOptions' => $paginationNumOptions,
+            'isAvailableQuantityDisplayed' => (bool) $this->configuration->get('PS_STOCK_MANAGEMENT'),
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
            'isAvailableQuantityDisplayed' => $this->configuration->getBoolean('PS_STOCK_MANAGEMENT'),
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 2]
```diff
@@ -727,6 +728,7 @@ public function addProductAction(int $orderId, Request $request): Response
                 'product' => $newProduct,
                 'isColumnLocationDisplayed' => $newProduct->getLocation() !== '',
                 'isColumnRefundedDisplayed' => $newProduct->getQuantityRefunded() > 0,
+                'isAvailableQuantityDisplayed' => (bool) $this->configuration->get('PS_STOCK_MANAGEMENT'),
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
                'isAvailableQuantityDisplayed' => $this->configuration->getBoolean('PS_STOCK_MANAGEMENT'),
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 3]
```diff
@@ -967,6 +969,7 @@ public function updateProductAction(int $orderId, int $orderDetailId, Request $r
             'cancelProductForm' => $cancelProductForm->createView(),
             'isColumnLocationDisplayed' => $product->getLocation() !== '',
             'isColumnRefundedDisplayed' => $product->getQuantityRefunded() > 0,
+            'isAvailableQuantityDisplayed' => (bool) $this->configuration->get('PS_STOCK_MANAGEMENT'),
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
            'isAvailableQuantityDisplayed' => $this->configuration->getBoolean('PS_STOCK_MANAGEMENT'),
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: No because configuration is supposed to be a `ConfigurationInterface` which only contains get/set methods

`getBoolean` is a side effect of the Adapter implementation of this interface which only exists because it extends `ParameterBag` When we explicitely use the Adapter service or in service definition I don't mind using `getBoolean` but in this case it's not correct

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @jolelievre The available quantity is still displayed 
image

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM now 
image
Thanks @jolelievre !!

**Comment by Progi1984** [comment]
Thanks @jolelievre & @SD1982
