### PR TITLE
Avoid crash because of image timeout

### LINKED ISSUE #18115: "Modify module positions" BO page fails if an image from Addons is too long to load
#### Describe the bug

I was working on "Modify module positions" BO page and my page crashed because a module image failed to load fast enough: see screenshot

URL http://localhost/admin-dev/index.php?controller=AdminModulesPositions&addToHook=&show_modules=69&token=XXXX

#### Expected behavior

A BO page should never crash because of a slow image load 😅 

**Screenshots**

Capture d’écran 2020-03-12 à 11 54 35

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve `Module::copyModAddonsImg()` to avoid crashes if timeout
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/18115
| How to test?  | I dont know 😓 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18116)

### CODE REVIEW

File: classes/module/Module.php [hunk 1]
```diff
@@ -1603,16 +1603,35 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
+     * @param \StdClass $modaddons Addons Module object, provided by XML stream
+     *
+     * @return string|null
+     */
     public static function copyModAddonsImg($modaddons)
     {
         if (!Validate::isLoadedObject($modaddons)) {
-            return;
+            return null;
         }
```
Comment (PululuK) [inline classes/module/Module.php:1615]: Returning null is too silent ... 
Rather check if it is a module instance instead of isLoadedObject and throw an exception.

something like that :
```php
         if (!($modaddons instanceof Module)) {
            throw new InvalidModuleException('Invalud module ... etc etc');
        }
```

Comment (matks) [reply classes/module/Module.php:1615]: I'm afraid of modifying the code of such an old class used so deeper 😅

This part of the code is very tangled and buried deep inside layers of layers of code. I'm afraid of breaking something.

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/module/Module.php [hunk 2]
```diff
@@ -1603,16 +1603,35 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
+            }
+
+            if ($remoteDownloadWasASuccess && !file_put_contents($filepath, $remoteImage)) {
+                copy(_PS_IMG_DIR_ . '404.gif', $filepath);
+            }
         }
-        if (file_exists(_PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg')) {
+
+        if (file_exists($filepath)) {
             return '../img/tmp/' . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg';
```
Comment (PierreRambaud) [inline classes/module/Module.php]: Don't do `md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg'` twice please :sweat_smile:

File: classes/module/Module.php [hunk 3]
```diff
@@ -1603,16 +1603,35 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
+
+        $filepath = _PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg';
+        $fileDoesNotExist = !file_exists($filepath);
+
+        if ($fileDoesNotExist) {
+            $remoteDownloadWasASuccess = false;
+            try {
+                $remoteImage = Tools::file_get_contents($modaddons->img);
+                $remoteDownloadWasASuccess = true;
+            } catch (\Exception $e) {
```
Comment (PululuK) [inline classes/module/Module.php]: Please add a use Exception; instead of the \ notation

File: classes/module/Module.php [hunk 4]
```diff
@@ -1603,16 +1603,35 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
         if (!Validate::isLoadedObject($modaddons)) {
-            return;
+            return null;
         }
-        if (!file_exists(_PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg') &&
-        !file_put_contents(_PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg', Tools::file_get_contents($modaddons->img))) {
-            copy(_PS_IMG_DIR_ . '404.gif', _PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg');
+
+        $filepath = _PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg';
+        $fileDoesNotExist = !file_exists($filepath);
```
Comment (PululuK) [inline classes/module/Module.php]: some optimizations

**Review by PululuK — CHANGES_REQUESTED** [review]
@see : https://github.com/matks/PrestaShop/pull/4/files

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
See comments

File: classes/module/Module.php (hunk 2 above)
Comment (matks) [reply classes/module/Module.php]: This is 2020 ! Hardware is cheap ! 😄

Comment (matks) [reply classes/module/Module.php]: (the code, before my changes, did it 3 or 4 times)

Anyway @PululuK fixed my code and addresses your feedback

**Comment by matks** [comment]
Big thanks to @PululuK for not only reviewing this PR but also submitting a PR to my fork with valid (and better) changes / suggestions

@PierreRambaud your word, now 😄

File: classes/module/Module.php [hunk 5]
```diff
@@ -1603,17 +1604,37 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
+            }
+
+            if ($remoteDownloadWasASuccess && !file_put_contents($filepath, $remoteImage)) {
+                copy(_PS_IMG_DIR_ . '404.gif', $filepath);
+            }
         }
-        if (file_exists(_PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg')) {
-            return '../img/tmp/' . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg';
+
+        if ($fileExist) {
```
Comment (PierreRambaud) [inline classes/module/Module.php]:
```suggestion
        if (file_exists($filepath)) {
```
You need to do it one more time, otherwise it just keep the result before trying to copy

Comment (matks) [reply classes/module/Module.php]: @PierreRambaud Done. But now I guess we should add a `else()` right ? Else function returns void

File: classes/module/Module.php [hunk 6]
```diff
@@ -1603,17 +1604,37 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
+            if ($remoteDownloadWasASuccess && !file_put_contents($filepath, $remoteImage)) {
+                copy(_PS_IMG_DIR_ . '404.gif', $filepath);
+            }
         }
-        if (file_exists(_PS_TMP_IMG_DIR_ . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg')) {
-            return '../img/tmp/' . md5((int) $modaddons->id . '-' . $modaddons->name) . '.jpg';
+
+        if (file_exists($filepath)) {
+            return '../img/tmp/' . $filename;
         }
```
Comment (Progi1984) [inline classes/module/Module.php]:
```suggestion
        if ($fileExist) {
            return '../img/tmp/' . $filename;
        }
```

File: classes/module/Module.php [hunk 7]
```diff
@@ -1603,17 +1604,37 @@ public static function getModulesOnDisk($use_config = false, $logged_on_addons =
...
+            try {
+                $remoteImage = Tools::file_get_contents($modaddons->img);
+                $remoteDownloadWasASuccess = true;
+            } catch (Exception $e) {
+                copy(_PS_IMG_DIR_ . '404.gif', $filepath);
+            }
+
+            if ($remoteDownloadWasASuccess && !file_put_contents($filepath, $remoteImage)) {
+                copy(_PS_IMG_DIR_ . '404.gif', $filepath);
+            }
```
Comment (Progi1984) [inline classes/module/Module.php]:
```suggestion
            }
            $fileExist = file_exists($filepath);
```

**Review by Progi1984 — DISMISSED** [review]

File: classes/module/Module.php (hunk 5 above)
Comment (PierreRambaud) [reply classes/module/Module.php]: The function was already returning void :thinking:

**Review by PierreRambaud — DISMISSED** [review]

File: classes/module/Module.php [hunk 8]
```diff
@@ -23,6 +23,7 @@
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  * International Registered Trademark & Property of PrestaShop SA
  */
+use Exception;
```
Comment (Progi1984) [inline classes/module/Module.php]: To remove ;)

Comment (matks) [reply classes/module/Module.php]: I have no opinion on this (use `use` for native php classes) but I think @PierreRambaud asked me to do the opposite a long time ago 🤔

Comment (Progi1984) [reply classes/module/Module.php]: It's just for fixing Travis ;)

Comment (PierreRambaud) [reply classes/module/Module.php]: I asked to use namespace object when it's needed (in Symfony pages for example) :sweat_smile: 
It's not mandatory to remove the use here, it can help to see which Exception are thrown in this class.

Comment (matks) [reply classes/module/Module.php]: My bad, sorry @Progi1984

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
I deleted the branch by mistake. Restoring it and reopening PR

**Review by PululuK — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @matks !

**Comment by Progi1984** [comment]
Thanks @matks
