### PR TITLE
Fix FO Exception after category add on multilang shop

### LINKED ISSUE #18711: Exception on all FO pages when adding a language and a category in menu
We have a bug appearing when a new category is added to the menu in fo, and a new language is added in BO.

## How to reproduce:
1- Go to BO add a language
2- Add a category in BO
3- In the menu module, add the new category to the menu
4- go to FO, change language

see error:
Capture d’écran 2020-04-20 à 11 39 28

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Handle multilang parameters when building routes
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18711
| How to test?  | 1- Go to BO add a language<br>2- Add a category in BO<br>3- In the menu module, add the new category to the menu<br>4- go to FO, change language<br>5- You wont see any exception

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18743)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/Dispatcher.php [hunk 1]
```diff
@@ -936,7 +936,16 @@ public function createUrl(
...
-                        $replace = $route['keywords'][$key]['prepend'] . $params[$key] . $route['keywords'][$key]['append'];
+                        $parameter = $params[$key];
+                        if (is_array($params[$key])) {
+                            if (array_key_exists($id_lang, $params[$key])) {
+                                $parameter = $params[$key][$id_lang];
+                            } else {
+                                // made the choice to return the first element of the array
+                                $parameter = reset($params[$key]);
+                            }
+                        }
```
Comment (Progi1984) [inline classes/Dispatcher.php]:
```suggestion
                        if (is_array($parameter)) {
                            if (array_key_exists($id_lang, $parameter)) {
                                $parameter = $parameter[$id_lang];
                            } else {
                                // made the choice to return the first element of the array
                                $parameter = reset($parameter);
                            }
                        }
```

Comment (Progi1984) [reply classes/Dispatcher.php]: What do you think about this ?

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sowbiba
