### PR TITLE
Fix installation of en-GB during install, improve installation error report

### LINKED ISSUE #38878: Fails to Install when Region set to United Kingdom (UK)
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

During install of 9.0.0-1.0 basic (the default package from PS Download site), the installation fails at 23% repeatedly.

This happens with PHP 8.1,2,3,4.

While writing this, something crossed my mind, and it appears that it WILL install with Country as US, but NOT as UK. (I need it UK).

Interestingly, the % Completion is different too, in US, creating the DB is at 10%, while for UK, this is 12% of the installation!

The install fails at Create default shop and languages

### Expected behavior

An installation that doesn't fail with UK Selected!

### Steps to reproduce

Download the PS 9 package from Prestashop downloads
Upload to directory and unzip
start the installer by heading to the url of the package
fill in details USING UNITED KINGDOM as the country.
Watch it fail at 23%

NOTE: IT DOES WORK WITH UNITED STATES.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1, 8.2, 8.3, 8.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Fix installation of en-GB during install: since the language is not present in available languages from `install-dev/langs` folder some additional `downloadAndInstallLanguagePack` method was called before the default language is initialized Also improve installation error report to get more accurate feedback
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green UI tests green Test manually (see issue)
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/16314613094
| Fixed issue or discussion?     | Fixes #38878
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by Codencode — DISMISSED** [review]

File: classes/Language.php [hunk 1]
```diff
@@ -1653,16 +1653,24 @@ public static function updateMultilangFromClass($table, $className, $lang)
...
-        self::loadAdminTranslatorLocale($shopDefaultLanguage->locale, false);
+        // The provided locale should always be loaded though
         self::loadAdminTranslatorLocale($lang->locale, false);
 
         $sfContainer = SymfonyContainer::getInstance();
-        $translator = $sfContainer->get(TranslatorInterface::class);
-        (new EntityTranslatorFactory($translator))
-            ->build($classObject)
-            ->translate($lang->id, $shop->id);
+        if ($sfContainer->has('language')) {
```
Comment (Quetzacoalt91) [inline classes/Language.php]: Shall we allow this case to be happening in the installation process only, and throw an exception otherwise?
I we don't do this, we may end with a method that nothing because finding the service `language` was failing silently.

Comment (jolelievre) [reply classes/Language.php]: Actually it's completely wrong I wanted to test if the translator is available not `language` Maybe that's why I have errors in the test (hopefully)

Regarding the exception or the silent fail I agree that an exception would be cleaner, but if we do that it would break the installation process And handling an exception only during installation could be an alternative but I'm not sure we have a way to detect if we are in the installation process 🤔

Comment (Quetzacoalt91) [reply classes/Language.php]: > I'm not sure we have a way to detect if we are in the installation process 🤔

If that helps, from the modules we rely on a constant: `defined('PS_INSTALLATION_IN_PROGRESS')`

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @jolelievre, 

Thank you for your PR, I tested it and it's good for me ^^
Capture d’écran 2025-07-17 à 10 03 23

**Review by SiraDIOP — APPROVED** [review]
