### PR TITLE
Fix wrong multishop detection in AdminInvoiceController

### LINKED ISSUE #26137: BO invoice counters are wrongly displayed in "All shops" context
( Note: I am opening this issue as requested by @PierreRambaud - A fix for this had already been made in my PR #24120 )

#### Describe the bug
Backoffice invoices counters are displayed only for one shop when using multishop in "All shops" context

#### Expected behavior

I would expect to see counters considering invoices from all shops. 

#### Steps to Reproduce

1. Enable multishop with two shops (shop1 / shop2)
2. Complete two orders, one in shop1 - one in shop2 and change their order status to "Payment accepted" to trigger invoice generation
3. Switch to "All shops" context and go to Orders > Invoice
4. See only "1" invoice is displayed in "payment accepted" instead of 2 - PDF export routine is correctly export both invoices , though

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7.8
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by gennaris**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The actual wrong bindValue of shopIds to imploded string was causing  SQL "IN ()" clause to be always threated as string and not integer array - resulting in wrong invoices listed in backoffice in multiple shop selected / all shops context.
| Type?             | bug fix
| Category?         |  BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26137
| How to test?      |  Check "invoices" BO page in "All shops" mode with multiple shops before / after the fix and compare results.

See the actual query below :

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24120)

### CODE REVIEW

File: src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php [hunk 1]
```diff
@@ -61,18 +61,15 @@ public function __construct(Connection $connection, $tablePrefix)
...
+        $sql = 'SELECT COUNT(o.id_order) AS nbOrders, o.current_state as id_order_state
+            FROM `{table_prefix}order_invoice` oi
+            LEFT JOIN `{table_prefix}orders` o ON oi.id_order = o.id_order
+            WHERE o.id_shop IN('.implode(',', array_map('intval', $shopIds)).')
+            AND oi.number > 0
+            GROUP BY o.current_state';
         $sql = str_replace('{table_prefix}', $this->tablePrefix, $sql);
 
         $statement = $this->connection->prepare($sql);
-        $statement->bindValue('shopIds', implode(',', array_map('intval', $shopIds)));
```
Comment (matks) [inline src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php:75]: Hello, I think we can keep the `bindValue()` which has benefits by passing the right parameter type `Connection::PARAM_STR_ARRAY`

It should look like :
```
$statement->bindValue('shopIds', $shopIds, Connection::PARAM_STR_ARRAY);
```
can you try and explore this?

Comment (gennaris) [reply src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php:75]: Already tried with PARAM_INT_ARRAY and PARAM_STR_ARRAY but we'll end up with an exeception in both ways :

```
An exception occurred while executing 'SELECT COUNT(o.id_order) AS nbOrders, o.current_state as id_order_state
FROM `ps_order_invoice` oi
LEFT JOIN `ps_orders` o ON oi.id_order = o.id_order
WHERE o.id_shop IN(:shopIds)
AND oi.number > 0
GROUP BY o.current_state' with params [{"2":2,"1":1}]:

Notice: Array to string conversion
```

Looks like PDO / DBAL bindValue() is not array friendly - In order to work , query should be rewritten with QueryBuilder but my patch would work aswell...

**Review by sowbiba — DISMISSED** [review]
LGTM

File: src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php [hunk 2]
```diff
@@ -61,18 +61,15 @@ public function __construct(Connection $connection, $tablePrefix)
...
-SELECT COUNT(o.id_order) AS nbOrders, o.current_state as id_order_state
-FROM `{table_prefix}order_invoice` oi
-LEFT JOIN `{table_prefix}orders` o ON oi.id_order = o.id_order
-WHERE o.id_shop IN(:shopIds)
-AND oi.number > 0
-GROUP BY o.current_state
-SQL;
+        $sql = 'SELECT COUNT(o.id_order) AS nbOrders, o.current_state as id_order_state
+            FROM `{table_prefix}order_invoice` oi
+            LEFT JOIN `{table_prefix}orders` o ON oi.id_order = o.id_order
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php]:
```suggestion
            INNER JOIN `{table_prefix}orders` o ON oi.id_order = o.id_order
```

Comment (Progi1984) [reply src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php]: That changes the behavior of the query. Isn't it ?

Comment (Progi1984) [reply src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php]: Ping @PierreRambaud

Comment (matthieu-rolland) [reply src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php]: since the selection is made on the joined table only, I believe it should not change the result of this function

Comment (PierreRambaud) [reply src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php]: It's because of `o.id_shop` in the WHERE condition, so the `o` alias is mandatory, and because it's mandatory, you have to use INNER for better performance.

Comment (Progi1984) [reply src/PrestaShopBundle/Entity/Repository/OrderInvoiceRepository.php]: Thanks for explanation @PierreRambaud . I approve the request of @PierreRambaud

**Comment by matks** [comment]
I applied @PierreRambaud code suggestion to the submitted PR. Now we should try to reproduce the issue and submit a bug report before validating the PR, so that QA team can track and confirm the bug solving.

**Comment by PierreRambaud** [comment]
Hi @gennaris 
Are you able to create an issue?

**Comment by gennaris** [comment]
@PierreRambaud - Sure, I will shortly

**Comment by PierreRambaud** [comment]
Hi @gennaris 
Seems tests are failing :/

**Comment by matks** [comment]
Re-running CI to be sure this is not a false positive

**Comment by PierreRambaud** [comment]
> Re-running CI to be sure this is not a false positive

When it concerns cs fixer, it's not a false positive ^^
I rebase the PR and also apply cs fixer

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @gennaris 

Thanks for your PR. The issue is fixed.
I checked the behavior using theses cases : 

- Create and Update order for two shops from BO
- Generate invoice for status which do not have invoice and check 
- Create orders for twos shops from FO and Update status from BO

See an example of a scenario in the screen-record below : 
https://watch.screencastify.com/v/5ixcbyqSpE0lfd1NJchq

So, QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @gennaris & @HanaRebaiQA
