### PR TITLE
Use getSemVersion instead of getVersion to have the correct version

### LINKED ISSUE #26756: BO - Translations page - an exception is displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the develop branch, in the BO > International > Translations page, an exception is displayed
image
It is detected by nightly
https://nightly.prestashop.com/report/3037
Version 1.8.0.0 is not correct.

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > International > Translations page 
2. See error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #26760: BO - the version of PrestaShop in the toolbar symfony is not correct
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Migrated page, when the debug mode is enabled.
The version of PrestaShop in the toolbar is incorrect.
image
This issue is reported by @boubkerbribri 

### Expected behavior

It should be 8.0.0

### Steps to reproduce

1. Enable debug mode
2. Go to BO > Any migrated page
3. In the toolbar Symfony
4. check the version PrestaShop

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Using getVersion will return the wrong version number for non legacy (not 4 digits) versions. To fix this, we replace getVersion calls by getSemVersion where it's relevant
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26756 and #26760 
| How to test?      | Follow descriptions in the issues linked
| Possible impacts? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26934)

### CODE REVIEW

**Comment by sowbiba** [comment]
This PR is needed to test #26669 #25236 and #25176

File: src/Adapter/Language/LanguagePackInstaller.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function __construct(TranslatorInterface $translator, Version $version)
     public function downloadAndInstallLanguagePack($iso)
     {
         $freshInstall = empty(Language::getIdByIso($iso));
-        $result = Language::downloadAndInstallLanguagePack($iso, $this->version->getVersion(), null, $freshInstall);
+        $result = Language::downloadAndInstallLanguagePack($iso, $this->version->getSemVersion(), null, $freshInstall);
```
Comment (sowbiba) [inline src/Adapter/Language/LanguagePackInstaller.php:67]: the $version param is not used at all. We maybe have to consider removing it

**Comment by sowbiba** [comment]
There is another usage of getVersion in the module ps_mbo

https://github.com/PrestaShopCorp/ps_mbo/blob/master/src/AddonsSelectionLinkProvider.php#L80
used in
https://github.com/PrestaShopCorp/ps_mbo/blob/master/src/Controller/Admin/ModuleSelectionController.php#L80

but I cannot find how to call this URL through the BO

**Review by eternoendless — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

This PR is ok :heavy_check_mark: 
I checked the translations page => ok
I checked all sections => ok
image

Automatic tests => ok 
[Mochawesome Report_translations.pdf](https://github.com/PrestaShop/PrestaShop/files/7687363/Mochawesome.Report_translations.pdf)

I just have one issue
In the footer > on the toolbar Symfony, => if we click on this link `Read PrestaShop 8.0.0 Docs` => redirection 404 not found
image

This issue should be fixed in this PR?
If not, I will create another issue and we can merge this PR.

Thank you!

File: src/PrestaShopBundle/Resources/views/Admin/WebProfiler/config.html.twig [hunk 2]
```diff
@@ -100,7 +100,7 @@
             <div class="sf-toolbar-info-piece">
                 <b>Resources</b>
                 <span>
-                    {% set appVersion = collector.applicationversion|join()[:3] %}
+                    {% set appVersion = collector.applicationversion|join()[:1] %}
```
Comment (sowbiba) [inline src/PrestaShopBundle/Resources/views/Admin/WebProfiler/config.html.twig:103]: Because devdocs link is now https://devdocs.prestashop.com/8/ instead of https://devdocs.prestashop.com/8.0/

**Review by jolelievre — APPROVED** [review]
Thanks @sowbiba

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

It is ok :heavy_check_mark: 
https://watch.screencastify.com/v/ZRdLDBjkt0hLImJyDNF0
image
image

Automatic tests => ok
[Mochawesome Report_tran1.pdf](https://github.com/PrestaShop/PrestaShop/files/7694490/Mochawesome.Report_tran1.pdf)

Thanks!
