### PR TITLE
Dynamic import for zxcvbn library

### LINKED ISSUE #30088: New password policy fix causes core.js to be gigantic
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

With the new password policy (which is a good thing) using the [zxcvbn](https://github.com/dropbox/zxcvbn) library, I recently noticed that the final `core.js` filesize when from `~45kb` to `~443kb`, which is almost 10 times larger than before.

**Update:** I was looking in the network tab. Looking at the _actual_ filesize it goes from `~138kb` to `~936kb`. Still almost 7 times larger.

A big part of it seems to be the **gigantic** list of normal (I guess "bad"?) passwords. See attached screen recording:

https://www.loom.com/share/70d0b00132b0424b8ebf2b241eb14401

It seems to have been added in this [PR](https://github.com/PrestaShop/PrestaShop/pull/28127).

### Expected behavior

This is not really my area of expertise but I'm guessing the proper way would to compare the wanted/entered password, against this list with AJAX in order so save filesize and possibly script execution time.

### Steps to reproduce

1. Compare `core.js` filesize between 1.7.x and latest 8.0.0 beta

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Oksydan**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x-rc 
| Description?      | `zxcvbn` library is rly huge and shouldn't be loaded in core.js. We are providing new filed to `prestashop` global variable `core_js_public_path`. It is being used for webpack `publicPath` on the fly to avoid problem when ruing prestashop inside catalog (`domain.com/directory/`). For now `prestashop.checkPasswordScore` is asynchronous and it's returning a promise. `zxcvbn` library is being loaded dynamically on calling `prestashop.checkPasswordScore` function. I will provide `PR` to classic and hummingbird.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | Yes and no. Since prestashop 8.0.0 isn't released yet but it will be if we don't implement it now.
| Deprecations?     | no
| Fixed ticket?     | Fixes #30088
| How to test?      | 1. Build core.js assets (there should new file with suffix `-chunk.js`. <br> 2. If testing with classic-theme https://github.com/PrestaShop/classic-theme/pull/67 apply changes from this PR.<br> 3. Go to FO register page. <br> 4. Type inside password field, (you can open network tab in browser, there should be js file loaded on password check). <br> 5. Password policy should be working as before.
| Possible impacts? | Check if it's working for prestashop installation with different `physicial_uri` 

Before:
core.js size: `940kB`

After:
core.js size: `144kB`

### CODE REVIEW

**Comment by yanmakouf** [comment]
@NeOMakinG 🦸‍♂️ 🚀  🔎

**Comment by Hlavtox** [comment]
Remember that we want to load core js optionally - https://github.com/PrestaShop/PrestaShop/pull/29995 😎

**Review by NeOMakinG — APPROVED** [review]
We definitely need this inside the 8.0 release or it will be a big blocker for the adoption

@Oksydan you're a monster btw

**Review by yanmakouf — APPROVED** [review]

File: themes/_core/js/theme.js [hunk 1]
```diff
@@ -22,6 +22,8 @@
  * @copyright Since 2007 PrestaShop SA and Contributors
  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
  */
+__webpack_public_path__ = window.prestashop.core_js_public_path;
```
Comment (jolelievre) [inline themes/_core/js/theme.js:25]: Not sure I get the purpose of this one? It allows using `const zxcvbn = (await import('zxcvbn')).default;` and import from chunks right?

**Review by jolelievre — APPROVED** [review]

File: themes/_core/js/theme.js (hunk 1 above)
Comment (Oksydan) [reply themes/_core/js/theme.js:25]: Hi @jolelievre,
Webpack need `publicPath` to be set so it can find files that have to be fetched example `publicPath = "/themes/"` - `domain.com/themes/chunkfilename`.
We can set `publicPath` in webpack configuration to just `/themes/` and that should work in 99% but if store `physical_uri` is different than `/` for example `/store/` (`domain.com/store/`) `publicPath` will be `/store/themes/`. That's why we need that variable to be set on the fly.

**Review by khouloudbelguith — COMMENTED** [review]
Hello @nicosomb,

I checked those cases
**Case1** 
image
`Physical_uri === /Presta+Shop/` => OK

- Install > Information step
- FO > Create an account
- FO > Edit information
- FO > Create an account for a guest
- FO > Checkout > Create an account

**Case2**
image
`Physical_uri === /PrestaShop/`  => OK

- Install > Information step  => OK
- FO > Create an account  => OK
- FO > Edit information  => OK
- FO > Create an account for a guest  => OK
- FO > Checkout > Create an account  => OK

**Case3** 
image
`Physical_uri === /` => OK

- Install > Information step  => OK
- FO > Create an account  => OK
- FO > Edit information  => OK
- FO > Create an account for a guest  => OK
- FO > Checkout > Create an account  => OK

I attached screen records

https://user-images.githubusercontent.com/16067358/197586971-2a5c04b2-a28f-4fb6-9378-24129c1183ba.mp4


**Case4**
image
`Physical_uri === /test/80x/` => **NOK**
Install > Information step: OK
BO > Create a customer => OK
BO > Edit an employee password => OK
FO > Create an account => **NOK**
FO > Edit information => **NOK**
FO > Checkout > Create an account => **NOK**

The info messages are not displayed when typing the password
I attached a screen record

https://user-images.githubusercontent.com/16067358/197587303-99f0696c-a230-4f71-a0ea-d7acdfa1eb95.mp4

I tried with 8.0.0RC1 => OK

https://user-images.githubusercontent.com/16067358/197588820-bda848d0-3845-4ac9-b847-eb1761ea76b1.mp4


Thanks!

**Comment by Oksydan** [comment]
Hi @khouloudbelguith,
In not working case your network tab is showing that file has been fetched properly. There is a js error in your console ever time you type in password field. Did you apply changes to classic when you were testing that case 4? Are you able to show me that console with errors? 
Thanks

**Review by khouloudbelguith — APPROVED** [review]
Hi @Oksydan,

Thanks for your feedback.
After some rechecks, it is ok :heavy_check_mark: 
I checked with this 
image

Also, automatic tests => OK :heavy_check_mark: 
I checked when multistore enabled / I checked friendly URL enabled & disabled => OK :heavy_check_mark: 

https://user-images.githubusercontent.com/16067358/197747186-afc8aad6-2b53-4fa4-acb0-db846e33c48d.mp4

Also, I checked the size of core.js => ok
image

Before, it was Nok
image

Thanks!

**Comment by kpodemski** [comment]
Thank you @Oksydan @khouloudbelguith

**Comment by Oksydan** [comment]
@khouloudbelguith good job. Thank you.
