### PR TITLE
Fix(carrier): handle page redirection on fields that are on error

### LINKED ISSUE #36759: New page carriers - bugs
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Bug 1 
I edit an old carrier, if I want to add a new zone but I do not enter the cost, the name of the zone disappears.

Bug 2
I create a new carrier, if I want to add a new zone, I cannot enter a cost.

Bug3
If I want to put a logo greater than 8 Mb, I have an error 500

Bug 4
If I configure my carrier with maximum authorized order dimensions of 1cm x 1cm x 1cm. I can order an order greater than these dimensions if the weight of the order is less than the maximum authorized weight.

Bug 5 
If the shipping costs are free, I cannot choose a delivery zone.

Bug 6
I can't save a carrier if all the required fields are not filled in. If I don't fill them in, I don't get an error message to tell me.

### Expected behavior

_No response_

### Steps to reproduce

Bug 1 :
https://www.loom.com/share/c1ba7893e5174e9591dd4397f4f2d1f7

Bug 2 : 
https://www.loom.com/share/d42a86ca6d074792a49035b8d3a034db

Bug 3 : 
https://www.loom.com/share/a3f932975bbb4a1db1e712d5f3eaeac2

Bug 4 : 
image
image

Bug 5 : 
image

Bug 6
https://www.loom.com/share/581a1052cdc14effb8a4a8f3a5582d68

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Nakahiru**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This pull request solve the issue mentioned in the issue #36759 regarding the bug 6. Before the pull request, when submitting the form, if there was an error in a field that was in another tab, nothing happen. The user cannot see any errors and don't know what to do. Now, if there is an error anywhere in the form, Independent from the tab, the user will be redirected to the first field that is in error.
| Type?             |  improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See description in the issue #36759
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/10936613034
| Fixed issue or discussion?     | Fixes #36759
| Related PRs       | none
| Sponsor company   | PrestaShop

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/carrier/form/carrier-form-manager.ts [hunk 1]
```diff
@@ -82,6 +86,35 @@ export default class CarrierFormManager {
     this.$shippingMethodInput.on('change', () => this.refreshCurrentShippingSymbol());
     $(CarrierFormMap.zonesContainer).on('click', CarrierFormMap.deleteZoneButton, (e:Event) => this.onDeleteZone(e));
     this.eventEmitter.on(CarrierFormEventMap.rangesUpdated, (ranges: Range[]) => this.onChangeRanges(ranges));
+
+    this.initErrorListener();
+  }
+
+  private initErrorListener(): void {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/carrier/form/carrier-form-manager.ts]: Could you integrate this in the `NavbarHandler` component instead, because we'll need to reuse this behaviour in other pages probably Maybe you can add an optional second parameter with the selector of the form?

File: admin-dev/themes/new-theme/js/pages/carrier/form/carrier-form-manager.ts [hunk 2]
```diff
@@ -82,6 +86,35 @@ export default class CarrierFormManager {
...
+    const carrierForm = document.querySelector(CarrierFormMap.form);
+    const requiredFields = carrierForm?.querySelectorAll('[required]');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/carrier/form/carrier-form-manager.ts]: Do we need do filter only inputs that are required? There may be other inputs with min/max value or other stuff that are enforced natively in HTML. So we could check every inputs and listen to their invalid event?

**Review by tleon — COMMENTED** [review]
Could you run the UI test ?

File: admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+  constructor(options: NavbarFormErrorHandlerType) {
+    this.navbarHandler = options.navbarHandler;
+    this.form = options.form;
+
+    this.initListener();
+    this.resetInvalidField();
+  }
+
+  private findRequiredFieldsFromForm(): NodeListOf<HTMLElement> {
+    return this.form.querySelectorAll('[required]');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts]: I already made a similar suggestion previously, but are we sure we only want to check at `required` inputs?

That's the type of constraint that is bothering us for carrier page but there could be other use cases like `min/max` values, so to avoid having to update this component sometime soon why not checking all the inputs in the form instead?

File: admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+  }
+
+  private initListener(): void {
+    this.findRequiredFieldsFromForm().forEach((field) => {
+      field.addEventListener('invalid', () => {
+        if (!this.firstInvalidField) {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts]: Why do you need to persist this invalid field? Is it in case two inputs are invalid when you click submit?

File: admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts (hunk 3 above)
Comment (Nakahiru) [reply admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts]: Yes, my bad 🙏🏻 I forgot to handle this one. Now, all fields in the form are selected in order to handle fields like the min/max attribute 🙂

File: admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts (hunk 4 above)
Comment (Nakahiru) [reply admin-dev/themes/new-theme/js/components/navbar-form-error-handler.ts]: I make some improvements on the logic in order to make it easier. It has been removed from class attribute, it is now scoped to the method. It allows to redirect to the first field in error if there is more than one error in the form.

**Review by jolelievre — APPROVED** [review]
Thanks @Nakahiru

**Review by boherm — APPROVED** [review]

**Review by tleon — APPROVED** [review]
