### PR TITLE
Fix number of DL & expiration date being displayed in the download virtual product mail

### LINKED ISSUE #10915: Display issue in virtual product email
**Describe the bug**
Some html tags are displayed in email when you order virutal product

**To Reproduce**
1. Go to advanced parameters > Email and choose Send email in text format
2. Make sure you receive email (test it)
3. Go to Catalog > Product
4. Create a new virual product with a file
4. Order this product
5. Put the order in "payment accepted" status
6. See the txt email sent 

**Screenshots**

46542475-cb99dd00-c8be-11e8-932e-13fb208dacc0

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This fixes #16014 that was merged to soon
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10915
| How to test?  | Order a virtual product with a file and see the text mail sent

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16049)

### CODE REVIEW

File: src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php [hunk 1]
```diff
@@ -351,6 +375,28 @@ private function getProductList(Order $order)
...
+     */
+    private function getFakeVirtualProductList()
+    {
+        $products = Product::getProducts($this->context->language->getId(), 0, 2, 'id_product', 'ASC');
+        $results = [];
+
+        foreach ($products as $product) {
+            $p = new Product($product['id_product']);
+            $results[] = [
+                'text' => Product::getProductName($product['id_product']),
```
Comment (jolelievre) [inline src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php]: Can't you get the product name since you instanciated in `$p`? `$p->name` ?
And you could rename this variable, either `$productEntity` or you can change your initial `$product` array to `$productData`

File: src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php [hunk 2]
```diff
@@ -119,6 +121,19 @@ public function buildTemplateVariables(LayoutInterface $mailLayout)
...
+     * @param $id
+     * @param array $parameters
+     * @param null $domain
+     * @param null $local
+     *
+     * @return string
+     */
+    protected function trans($id, $parameters = [], $domain = null, $local = null)
+    {
+        return $this->context->getTranslator()->trans($id, $parameters, $domain, $local);
```
Comment (jolelievre) [inline src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php]: If you need the translator it's better to directly inject `@translator` in the constructor

**Review by jolelievre — COMMENTED** [review]
Nice, this class is getting bigger and bigger One day this will need to be refactored ^^

File: src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php (hunk 1 above)
Comment (atomiix) [reply src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php]: Yes, `$p` was a temporary variable name, forgot to rename it...
I did try to use `$p->name` but it's an array with all the names for the different translations. Do you think I still should use it?

Comment (jolelievre) [reply src/Adapter/MailTemplate/MailPreviewVariablesBuilder.php]: Oh yes because it contains the localized name in an array No I think it's fine with what you did Just rename the variable it will be enough

File: mails/_partials/download_product_virtual_products.tpl [hunk 3]
```diff
@@ -24,6 +24,6 @@
  *}
 <ul>
 {foreach $list as $product}
-  <li><a href="{$product.url}">{$product.text}</a></li>
+  <li><a href="{$product.url}">{$product.text}</a>{$product.complementary_text}</li>
```
Comment (Progi1984) [inline mails/_partials/download_product_virtual_products.tpl]: It should be better to add a trim for removing space at start.

Comment (atomiix) [reply mails/_partials/download_product_virtual_products.tpl]: I'm not sure because the space is added on purpose :

`$complementaryText .= ' ' . $this->trans('expires on %s.', array($product['deadline']), `

File: classes/order/OrderHistory.php [hunk 4]
```diff
@@ -136,16 +136,17 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
                 $customer = new Customer((int) $order->id_customer);
                 $links = array();
                 foreach ($assign as $product) {
-                    $text = Tools::htmlentitiesUTF8($product['name']);
+                    $complementaryText = '';
```
Comment (PierreRambaud) [inline classes/order/OrderHistory.php]:
```suggestion
                    $complementaryText = [];
```

File: classes/order/OrderHistory.php [hunk 5]
```diff
@@ -136,16 +136,17 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
...
                     if (isset($product['deadline'])) {
-                        $text .= '&nbsp;' . $this->trans('expires on %s.', array($product['deadline']), 'Admin.Orderscustomers.Notification');
+                        $complementaryText .= ' ' . $this->trans('expires on %s.', array($product['deadline']), 'Admin.Orderscustomers.Notification');
```
Comment (PierreRambaud) [inline classes/order/OrderHistory.php]:
```suggestion
                        $complementaryText[] = $this->trans('expires on %s.', array($product['deadline']), 'Admin.Orderscustomers.Notification');
```

File: classes/order/OrderHistory.php [hunk 6]
```diff
@@ -136,16 +136,17 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
...
                     }
                     if (isset($product['downloadable'])) {
-                        $text .= '&nbsp;' . $this->trans('downloadable %d time(s)', array((int) $product['downloadable']), 'Admin.Orderscustomers.Notification');
+                        $complementaryText .= ' ' . $this->trans('downloadable %d time(s)', array((int) $product['downloadable']), 'Admin.Orderscustomers.Notification');
```
Comment (PierreRambaud) [inline classes/order/OrderHistory.php]:
```suggestion
                        $complementaryText[] = $this->trans('downloadable %d time(s)', array((int) $product['downloadable']), 'Admin.Orderscustomers.Notification');
```

File: classes/order/OrderHistory.php [hunk 7]
```diff
@@ -136,16 +136,17 @@ public function changeIdOrderState($new_order_state, $id_order, $use_existing_pa
...
                     }
                     $links[] = array(
-                        'text' => $text,
+                        'text' => Tools::htmlentitiesUTF8($product['name']),
                         'url' => $product['link'],
+                        'complementary_text' => $complementaryText,
```
Comment (PierreRambaud) [inline classes/order/OrderHistory.php]:
```suggestion
                        'complementary_text' => implode(' ', $complementaryText),
```

And no more spaces :)

Comment (PierreRambaud) [reply classes/order/OrderHistory.php]: Or I missed something about @Progi1984 's comment :sweat_smile:

File: mails/_partials/download_product_virtual_products.tpl (hunk 3 above)
Comment (Progi1984) [reply mails/_partials/download_product_virtual_products.tpl]: Ok; Sorry.

File: classes/order/OrderHistory.php (hunk 7 above)
Comment (atomiix) [reply classes/order/OrderHistory.php]: I'm pretty sure a space should be put at the begining too otherwise the link will be showed as : [Hummingbird printed sweater]()expires on 2019-10-24. downloadable 10 time(s)
instead of
[Hummingbird printed sweater]() expires on 2019-10-24. downloadable 10 time(s)

Comment (PierreRambaud) [reply classes/order/OrderHistory.php]: Maybe this one should be add in the template.

**Review by PierreRambaud — APPROVED** [review]
