### PR TITLE
Fix sorting by Relevance in search results

### LINKED ISSUE #34174: Product Search Relevance Option is Reversed When Manually Selected
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using the search products are displayed ordered by "Relevance" but the "Sort by:" drop-down shows "Choose". If "Relevance" is selected from options the products are listed in reverse order. i.e. the lease relevant first. 

### Expected behavior

The "Relevance" option should be selected by default and list products with the most relevant first.

### Steps to reproduce

Do a search in the front end.
Check the sort order displayed on the results page and make note of the product order.
Use the on page drop-down to select "Relevance" sort order.
Check the order of the displayed products.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mrkalchemy**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | suggested fix for issue #34174 (https://github.com/PrestaShop/PrestaShop/issues/34174).
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Search option defaults to "Relevance" and selecting 'Relevance' displays in correct match order.
| UI Tests          | https://github.com/mrkalchemy/ga.tests.ui.pr/actions/runs/6824831854.
| Fixed issue or discussion?     | Fixes #34174 
| Related PRs       | #34598  (version for develop)
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

File: classes/Search.php [hunk 1]
```diff
@@ -349,7 +349,7 @@ public static function find(
         $sqlScore = '';
         if (!empty($scoreArray) && is_array($scoreArray)) {
             $sqlScore = ',( ' .
-                'SELECT SUM(weight) ' .
```
Comment (matthieu-rolland) [inline classes/Search.php:352]: could you please explain this fix ? here you'll get a negative value instead of a positive one, right ? if yes, why is that ?

**Review by matthieu-rolland — COMMENTED** [review]
Thank you for your contribution @mrkalchemy !

I have a question for you

File: classes/Search.php [hunk 2]
```diff
@@ -349,7 +349,7 @@ public static function find(
...
+                'SELECT 0 - SUM(weight) ' .
```
Comment (matthieu-rolland) [inline classes/Search.php]: could you please explain this fix ? here you'll get a negative value instead of a positive one, right ? if yes, why is that ?

Comment (mrkalchemy) [reply classes/Search.php]: You are correct the idea is to switch the order so that the most relevant matches have a lower number not a higher one. This is needed because the "Relevance" sort by option on the search page uses ascending ordering.

The search score uses the alias `position` and other product lists assume that lower numbers come first. By modifying the behaviour to be the same as other product lists the problem can be fixed with minimal changes. It also works on the 8.1 and dev branches.

Hope that helps.

**Comment by Hlavtox** [comment]
Although feels a bit like a hackjob, we are relocating a problem to a good place and we will remove the reversed mess from Controllers. :-)

File: classes/Search.php (hunk 2 above)
Comment (matthieu-rolland) [reply classes/Search.php]: thank you for the explanation 👍

**Review by matthieu-rolland — COMMENTED** [review]
Thank you @mrkalchemy 

We can't validate the PR yet, not until the QA team has validated the issue (that's the process) 👍

**Comment by mrkalchemy** [comment]
Thanks @matthieu-rolland 

Should I be chasing up anyone in the QA team or do I just need to be patient.  😀

**Comment by kpodemski** [comment]
@mrkalchemy we'll review it soon :D be patient 👍🏻 :D

**Comment by Hlavtox** [comment]
It must be thinked through, because with this, we will break all module search providers, which will become reversed.

Maybe create a new sort order called `search_relevance`?

**Comment by mrkalchemy** [comment]
Okay I think I have a solution that shouldn't break anything. It involves changing the available sort orders in the SearchProductSearchProvider adapter class. This is probably the route I should have taken initially but never mind.

**Comment by mrkalchemy** [comment]
I've pushed the changes for you to have a look at. I don't think this should break anything as it's just changing the displayed sort options for the product search page. It's a lot cleaner than the original version. 🤞 

I've tested this on a clean install of 8.1.2 and it works great.

The fix for the **develop branch** is even more simple as the 'Relevance' option was moved from the SortOrdersCollection class and placed in the SearchProductSearchProvider adapter class (Pull #31074) so it's just a case of changing the 'asc' to 'desc'.

change this ...

            // We use default set of sort orders + option to sort by position (relevance), which makes sense only here and on category page
            $result->setAvailableSortOrders(
                array_merge(
                [
                    (new SortOrder('product', 'position', 'asc'))->setLabel(
                        $this->translator->trans('Relevance', [], 'Shop.Theme.Catalog')
                    ),
                ],
                $this->sortOrdersCollection->getDefaults())
            );

... to this ...

            // We use default set of sort orders + option to sort by position (relevance), which makes sense only here and on category page
            $result->setAvailableSortOrders(
                array_merge(
                [
                    (new SortOrder('product', 'position', 'desc'))->setLabel(
                        $this->translator->trans('Relevance', [], 'Shop.Theme.Catalog')
                    ),
                ],
                $this->sortOrdersCollection->getDefaults())
            );

If it would be helpful I can raise a separate PR for the **develop branch** fix as it is quite different.

**Comment by mrkalchemy** [comment]
I made a pull request with my suggested changes for the develop branch ( https://github.com/PrestaShop/PrestaShop/pull/34598 ).

**Comment by mrkalchemy** [comment]
Some of the automated "PHP Static Analysis" workflows were not happy with the changes. So I just pushed some updates to the PR branch that should hopefully fix all of the issues. 🤞

**Review by boherm — APPROVED** [review]
Hi @mrkalchemy, thanks for your contribution!

**Review by Hlavtox — APPROVED** [review]
Guys, just remember not to backport it into develop, it's done a better way and @mrkalchemy already did a separate pr for develop. :-)

**Review by florine2623 — APPROVED** [review]
Hello @mrkalchemy ,

LGTM
Screenshot 2023-11-20 at 16 55 36
Screenshot 2023-11-20 at 16 55 41

QA ✅

**Comment by matks** [comment]
Thank you @mrkalchemy
