### PR TITLE
Customer is able to see order detail page via link even order share is disabled in multishop

### LINKED ISSUE #26953: Customer is able to see order detail page via link even order share is disabled in multishop
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

- Multishop is enabled, Suppose, there are two shops Shop A and Shop B with the same shop group SG-A
- Share customer enabled for shop group SG-A and order share is disabled.
- Now if a customer places an order from Shop A and login into Shop B then no order is visible because order share is disabled.
- But if customer open that order via the link then it is visible
- Order must not be visible on another shop if order share is disabled.
### Shop A
Orders page: https://nimb.ws/hPLHgV
Order Detail page https://nimb.ws/U9JVd6  (URL: http://localhost/ps1780/ShopA/en/index.php?controller=order-detail&id_order=20)
### Shop B
Orders page: https://nimb.ws/j85mZ6
Order Detail page https://nimb.ws/nSmuBp  (URL: http://localhost/ps1780/ShopB/en/index.php?controller=order-detail&id_order=20)
- Hence on ShopB Customer must not be able to see details.

### Expected behavior

_No response_

### Steps to reproduce

- Multishop is enabled, Suppose, there are two shops Shop A and Shop B with the same shop group SG-A
- Share customer enabled for shop group SG-A and order share is disabled.
- Now if a customer places an order from Shop A and login into Shop B then no order is visible because order share is disabled.
- But if customer open that order via the link then it is visible
- Order must not be visible on another shop if order share is disabled.
### Shop A
Orders page: https://nimb.ws/hPLHgV
Order Detail page https://nimb.ws/U9JVd6  (URL: http://localhost/ps1780/ShopA/en/index.php?controller=order-detail&id_order=20)
### Shop B
Orders page: https://nimb.ws/j85mZ6
Order Detail page https://nimb.ws/nSmuBp  (URL: http://localhost/ps1780/ShopB/en/index.php?controller=order-detail&id_order=20)
- Hence on ShopB Customer must not be able to see details.

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Customer is able to see order detail page via link even order share is disabled in multishop
| Type?             | bug fix
| Category?         | FO
| Fixed ticket?     | Fixes #26953 
| How to test?      | See the description:
- Multishop is enabled, Suppose, there are two shops Shop A and Shop B with the same shop group SG-A
- Share customer enabled for shop group SG-A and order share is disabled.
- Now if a customer places an order from Shop A and login into Shop B then no order is visible because order share is disabled.
- But if customer open that order via the link then it is visible
- Order must not be visible on another shop if order share is disabled.
### Shop A
Orders page: https://nimb.ws/hPLHgV
Order Detail page https://nimb.ws/U9JVd6  (URL: http://localhost/ps1780/ShopA/en/index.php?controller=order-detail&id_order=20)
### Shop B
Orders page: https://nimb.ws/j85mZ6
Order Detail page https://nimb.ws/nSmuBp  (URL: http://localhost/ps1780/ShopB/en/index.php?controller=order-detail&id_order=20)
- Hence on ShopB Customer must not be able to see details.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26954)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Dear @Amit-Kumar-Tiwari-Webkul As I wrote in https://github.com/PrestaShop/PrestaShop/issues/26953 I think we should first check what the "order share" feature is supposed to do. There might be a reason why the current behavior, that you want to block, was implemented.

So I label this PR "Waiting for PM" so that Product Team can tell us if this behavior is expected or if it's a bug that needs to be fixed.

**Review by atomiix — DISMISSED** [review]

**Comment by marionf** [comment]
The option "share orders" allows customers who are logged in to any shop from this group to be able to see their order history for all the shops in the group. Also, the customer's cart will be shared by all shops in this group. This way, any purchase started in one shop will be able to be completed in another shop from the same group.

I agree with @Amit-Kumar-Tiwari-Webkul if the option "Share orders" is disabled, then the orders and the carts created in a shop shouldn't be visible once the customer is logged in to the other shops.

By the way, I updated the spec to make them clearer: https://github.com/PrestaShop/prestashop-specs/pull/281

File: controllers/front/OrderDetailController.php [hunk 1]
```diff
@@ -183,15 +183,29 @@ public function initContent()
...
-                $this->order_to_display = (new OrderPresenter())->present($order);
+                $viewAccess = true;
+                if ($order->id_shop != $this->context->shop->id) {
+                    if ($this->context->customer->id_shop_group == $this->context->shop->id_shop_group) {
+                        $shopGroup = new ShopGroup($this->context->customer->id_shop_group);
+                        if (!$shopGroup->share_order) {
+                            $viewAccess = false;
+                        }
+                    }
+                }
```
Comment (Progi1984) [inline controllers/front/OrderDetailController.php]:
```suggestion
                if ($order->id_shop != $this->context->shop->id && $this->context->customer->id_shop_group == $this->context->shop->id_shop_group) {
                    $shopGroup = new ShopGroup($this->context->customer->id_shop_group);
                    if (!$shopGroup->share_order) {
                        $viewAccess = false;
                    }
                }
```

**Review by Progi1984 — COMMENTED** [review]
@Amit-Kumar-Tiwari-Webkul A small suggestion and it's an approval for me.

File: controllers/front/OrderDetailController.php [hunk 2]
```diff
@@ -183,15 +183,27 @@ public function initContent()
 
             $order = new Order($id_order);
             if (Validate::isLoadedObject($order) && $order->id_customer == $this->context->customer->id) {
-                $this->order_to_display = (new OrderPresenter())->present($order);
+                $viewAccess = true;
```
Comment (sowbiba) [inline controllers/front/OrderDetailController.php]: I see someone who will say "Deny first, and then allow when granted"
Ping @PierreRambaud

**Review by matks — COMMENTED** [review]
OK for me
Waiting for @PierreRambaud opinion on the item identified by @sowbiba

File: controllers/front/OrderDetailController.php (hunk 2 above)
Comment (PierreRambaud) [reply controllers/front/OrderDetailController.php]: I'm more in favor of failing fast.
Instead of having $viewAccess = false; I would prefer to directly redirect when it's possible.
Instead of having encapsulation

**Review by PierreRambaud — COMMENTED** [review]
The whole code can be simpler:
image

```
            $order = new Order($id_order);
            if (!Validate::isLoadedObject($order) || $order->id_customer != $this->context->customer->id) {
                $this->redirect_after = '404';
                $this->redirect();
            }

            if ($order->id_shop != $this->context->shop->id && $this->context->customer->id_shop_group == $this->context->shop->id_shop_group) {
                $shopGroup = new ShopGroup($this->context->customer->id_shop_group);
                if (!$shopGroup->share_order) {
                    $this->redirect_after = '404';
                    $this->redirect();
                }
            }

            if (Tools::getIsset('errorQuantity')) {
                $this->errors[] = $this->trans('You do not have enough products to request an additional merchandise return.', [], 'Shop.Notifications.Error');
            } elseif (Tools::getIsset('errorMsg')) {
                $this->errors[] = $this->trans('Please provide an explanation for your RMA.', [], 'Shop.Notifications.Error');
            } elseif (Tools::getIsset('errorDetail1')) {
                $this->errors[] = $this->trans('Please check at least one product you would like to return.', [], 'Shop.Notifications.Error');
            } elseif (Tools::getIsset('errorDetail2')) {
                $this->errors[] = $this->trans('For each product you wish to add, please specify the desired quantity.', [], 'Shop.Notifications.Error');
            } elseif (Tools::getIsset('errorNotReturnable')) {
                $this->errors[] = $this->trans('This order cannot be returned', [], 'Shop.Notifications.Error');
            } elseif (Tools::getIsset('messagesent')) {
                $this->success[] = $this->trans('Message successfully sent', [], 'Shop.Notifications.Success');
            }

            $this->order_to_display = (new OrderPresenter())->present($order);

            $this->reference = $order->reference;

            $this->context->smarty->assign([
                'order' => $this->order_to_display,
                'orderIsVirtual' => $order->isVirtual(),
                'HOOK_DISPLAYORDERDETAIL' => Hook::exec('displayOrderDetail', ['order' => $order]),
            ]);

            unset($order);
        }
```
No need to have $viewAccess to only use the redirect() method :thinking:

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
> **[PierreRambaud](/PierreRambaud) ** l

I have updated.
$viewAccess variable was useless

**Review by PierreRambaud — APPROVED** [review]
It's easier to read :+1:

**Review by sowbiba — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @Amit-Kumar-Tiwari-Webkul 

Thanks for your PR. The issue is fixed.
So, its QA :heavy_check_mark: 

image

Here the tested cases : 
-Check with Share Customers enabled & Share orders disabled
-Check with Share Customers enabled & Share orders enabled
-Check with 2 Shops of the same Shop group
-Check with 2 Shops of different Shop group and different customers
-Check when create order from FO & BO
-Check following the order confirmation, in order history list, in the order details
-Check with Firefox browser
-Check on mobile
image

https://watch.screencastify.com/v/r4v5e77Ttr8dYPIScH0j
https://watch.screencastify.com/v/OQO6fkKRU5moCn0bKm9J
https://watch.screencastify.com/v/lUnOAPXt4euSewYy4QbC
https://watch.screencastify.com/v/oiNLqFQkkeSmerziFh9f
https://watch.screencastify.com/v/C0XJfvcqW8sNPNFcqjqc

Thanks!

**Comment by Progi1984** [comment]
Thanks @Amit-Kumar-Tiwari-Webkul & @HanaRebaiQA
