### PR TITLE
Fix bug when changing addresses on virtual product command

### LINKED ISSUE #12442: Major bug with Virtual Products command !
**Describe the bug**
Hi,
If we want to change the billing address for a virtual product order, 
an error is displayed, see below:

**To Reproduce**

1. Go to BO order
1. Click on command virtual product
1. change the billing address
1. See error

**Screenshots**
adresse-virtual-product-bug

2nd error
If you want to change only the billing address of the customer, big bug!
In addition, the address we wanted to edit is cloned by itself when we save or cancel the change!

changement-adresse-vitual-p

See video:

screencapture!UNITO-UNDERSCORE!05-02-2019!UNITO-UNDERSCORE!22!UNITO-UNDERSCORE!03!UNITO-UNDERSCORE!43

I have the error on 1.7.3.3, 1.7.4.4 and 1.7.5.x

**Additionnal information**
PrestaShop version: 1.7.3.x - 1.7.4.x, 1.7.5.x
PHP version: 7.1

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When changing the address of an order having only a virtual product, there is an error message, because the order carrier is not found.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12442 
| How to test?  | - Create a virtual product (don't forget to fill its quantity)<br>- create an order with the virtual product you created<br>- Try to change the invoice address, it should work.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17804)

### CODE REVIEW

File: classes/order/Order.php [hunk 1]
```diff
@@ -2688,10 +2688,13 @@ public function refreshShippingCost()
         $this->update();
 
         // save order_carrier prices, we'll save order right after this in update() method
-        $order_carrier = new OrderCarrier((int) $this->getIdOrderCarrier());
-        $order_carrier->shipping_cost_tax_excl = $this->total_shipping_tax_excl;
-        $order_carrier->shipping_cost_tax_incl = $this->total_shipping_tax_incl;
-        $order_carrier->update();
+        $orderCarrierId = (int) $this->getIdOrderCarrier();
```
Comment (matks) [inline classes/order/Order.php:2691]: It's fun that this method is capable of returning zero and look right in your eyes "Eyh, here's the order ID you asked for, nothing weird here, sir !" 😆

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by arouiadib — APPROVED** [review]
