### PR TITLE
Fixed pagination in Customer - View Page

### LINKED ISSUE #25588: BO - Customer View page - Pagination of the block voucher is NOK
#### Describe the bug

In the BO > Customers > Customers view page, if we have more than 10 vouchers, the pagination is not working.

#### Steps to Reproduce

1. Create more than 10 vouchers for a customer `John DOE`
2. Go to BO > Customers page
3. View the customer `John DOE`
4. In the Voucher block, try to change the item of pagination => NOK
5. try to change the number of pages => NOK

image

With PS1769 & PS1776 => we don't have pagination
image

#### Additional information

* PrestaShop version: 1780rc1build2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed pagination in Customer - View Page
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #25588
| How to test?      | 1. Create more than 10 vouchers for a customer `John DOE`<br>2. Create more than 10 addresses for a customer `John DOE`<br>3. Go to BO > Customers page<br>4. View the customer `John DOE`<br><br>**BEFORE :**<br>5. In the Voucher block, Change the the item of pagination => NOK<br>6. In the Voucher block, Change the number of pages => NOK<br>7. In the Addresses block, Change the the item of pagination => NOK<br>8. In the Addresses block, Change the number of pages => NOK<br><br>**AFTER :**<br>5. In the Voucher block, Change the the item of pagination => OK<br>6. In the Voucher block, Change the number of pages => OK<br>7. In the Addresses block, Change the the item of pagination => OK<br>8. In the Addresses block, Change the number of pages => OK<br>

**:notebook: BC Breaks :**
* In `src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php`, for the method `viewAction`, 2 new parameters added : `CustomerDiscountFilters $customerDiscountFilters` & `CustomerAddressFilters $customerAddressFilters`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25822)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by kpodemski** [comment]
Hey @Progi1984 

Have you tested it? 🤔 

I had to modify the grid and pass offset and limit to the Grid. Take a look:
https://github.com/PrestaShop/PrestaShop/pull/24797

Btw. this controller needs to be refactored. We're getting the data with `GetCustomerForViewing`, and then we're getting them again inside the Grids 🙄

**Comment by Progi1984** [comment]
@kpodemski It was tested in local and it's the technic for all controllers.

**Comment by kpodemski** [comment]
@Progi1984 weird, for me, it doesn't work:

https://www.dropbox.com/s/uyo6lfypfewwvr0/Zrzut%20ekranu%202021-09-13%20o%2014.37.43.png?dl=0

and it makes sense because here:
https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php#L66

there are no limits

**Comment by Progi1984** [comment]
@kpodemski I check a new time ;)

**Comment by Progi1984** [comment]
@kpodemski Thanks. I didn't understand my initial test. :( It's now fixed.

File: src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php [hunk 1]
```diff
@@ -72,11 +72,19 @@ public function getData(SearchCriteriaInterface $searchCriteria)
             false
         );
 
+        $numDiscounts = count($discounts);
+
+        $discounts = array_slice(
```
Comment (PierreRambaud) [inline src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: This is something that must be done in `getCustomerCartRules` logic instead here :thinking: 
If we have thousands of customer cart rules, we will load them all, then we do an array_slice, it's really reall ybad for performance :(

Comment (Progi1984) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: I understand but I think it's not the place to refactor the `getCustomerCartRules` logic which is really complex.

Comment (kpodemski) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: @PierreRambaud maybe let's accept it now, and we can improve it later, I think we need a better way of getting CartRule because there's a lot of method doing almost the same thing, maybe we could introduce some `CartRuleFinder`

The entire Customer view page needs a lot of work to optimize it, right now it's a mess

Comment (PierreRambaud) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: ping @matks and @jolelievre need your feedback here.
Personally, I'm not in favor of merging at is :/

**Review by sowbiba — COMMENTED** [review]
Looks good as it is but waiting for the decision to slice the cart rules in getCustomerCartRules or in CustomerDiscountGridDataFactory

My opinion : filtering in getCustomerCartRules would be cleaner but in this method, the request to retrieve all cart rules is done first before filtering depending on the method parameters. The result will be the same in term of performance. This need to be thought more to filter cart rules in the SQL query. Doing it too fast can introduce regressions

File: src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php (hunk 1 above)
Comment (matks) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: @PierreRambaud actually the unnecessary loading of all cart rules is already happening. In 1.7.8.x it's already happening. So this PR does not make performance worse, it keeps the performance 'as bad as it was before'.

So for me it's OK 👍  because the pagination logic is needed.

One step at a time :) I suggest we merge this PR as it makes the code a little better, and I agree we could make it even better by working on `getCustomerCartRules()`. But for another PR.

**Review by matks — APPROVED** [review]

File: src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php (hunk 1 above)
Comment (jolelievre) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: I agree with @PierreRambaud this false pagination is useless, it gives a false feeling that you can paginate and optimize But actually, you only hide part of the content so that what? There is less place used on the page?

So I would suggest two possibilities:
- improve the `getCustomerCartRules` function to include pagination in the query (with new optional parameters)
- remove the false pagination completely if it's not functional, this way if it's a problem for users they will give us honest feedback about a true missing feature, not one that was hidden under the carpet 😅

(I'm saying this because I know, as you do 😛 , when we say "let's do this later" we forget it anyway ^^)

Comment (kpodemski) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: > remove the false pagination completely if it's not functional, this way if it's a problem for users they will give us honest feedback about a true missing feature, not one that was hidden under the carpet 😅

In that case, we would have a long list of discounts after recent changes in the specs. I've tried to talk with PMs about changing them but without success. 

> (I'm saying this because I know, as you do 😛 , when we say "let's do this later" we forget it anyway ^^)

That's true, and given that we have specs for this section, maybe it would be good to rework it now.

I have a very similar PR: https://github.com/PrestaShop/PrestaShop/pull/24797. So these two have to be combined IMHO.

Comment (jolelievre) [reply src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php:77]: @kpodemski I agree both PR look similar in their goal, I guess they could be merged indeed And since in your PR you introduce a new function I think it should be possible to integrate pagination in the request without risking any side effects somewhere else since the function will only be used here

But the changes will need to target 1.7.8.1

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue, I don't know if it is a bug or a normal behavior
Steps to reproduce the issue:

1. Create 11 addresses ( or 11 vouchers)
2. Go to BO > Customers > View customer page
3. In the Addresses block (Vouchers block) => change number of of item to 10 => you have two pages
4. Go to the second page
5. delete the last item
6. we have `No records found`, is it ok?
image

or we should have the first list?
I attached a screen record
https://watch.screencastify.com/v/lSF8dvpdJoGtSNs6e8Qa

If it is normal behavior, the PR is good for me :slightly_smiling_face: 
Thanks!

**Comment by kpodemski** [comment]
Hello all,

What do you think about using code from this PR:
https://github.com/PrestaShop/PrestaShop/pull/24797

In @Progi1984 work? I think we could merge these two.

**Comment by Progi1984** [comment]
@khouloudbelguith Sorry. It seems that it's a bug inherented to grids. All grids are in the same case. Could you create a specific issue for this, please ? (Thanks @jolelievre for the help).

**Review by jolelievre — APPROVED** [review]
Good enough for a quick patch ^^

**Comment by khouloudbelguith** [comment]
Thanks, @Progi1984 and @jolelievre!
I created a separate issue: https://github.com/PrestaShop/PrestaShop/issues/26218

This PR is QA :heavy_check_mark: 

Thanks!

**Comment by PierreRambaud** [comment]
Thank you @Progi1984
