### PR TITLE
PrestashopLogger should save object type, even if object id is not set.

### LINKED ISSUE #24706: PrestashopLogger should save object type, even if object id is not set.
#### Describe the bug

Swiftmailer has thrown an exception, but `Prestashoplogger` did not save the `object_type` 'Swift_Message'.

#### Expected behavior

I expected that the exception waould be logged to `ps_log` with all it's attributes.

#### Steps to Reproduce

1. Go to *Configure - Advanced Parameters - E-mail*
2. Select *Set my own SMTP parameters (for advanced users ONLY)*, and define email parameters for SMTP
3. Enter an invalid *SMTP password*
4. Send a email from the FO (e.g. a reset password request)
5. The e-mail will fail to send (obviously)
6. Open phpmyadmin and look at the latest entry in the table `ps_log`. You will notice that it does not have an `object_type`, event though in `Mail::send()` `PrestaShopLogger::addLog()` was called with a parameter of `$object_type = 'Swift_Message'`

#### Additional information

* PrestaShop version: 1.7.7.4, develop
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | PrestashopLogger should save object type, even if object id is not set.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24706.
| How to test?      | Follow the steps indicated in #24706 and notice that the object_type is logged now.
| Possible impacts? | None

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24707)

### CODE REVIEW

File: classes/PrestaShopLogger.php [hunk 1]
```diff
@@ -158,9 +158,12 @@ public static function addLog($message, $severity = 1, $errorCode = null, $objec
...
 
-        if (!empty($objectType) && !empty($objectId)) {
-            $log->object_type = pSQL($objectType);
-            $log->object_id = (int) $objectId;
+        if (!empty($object_type)) {
+            $log->object_type = pSQL($object_type);
+        }
+
+        if (!empty($object_id)) {
+            $log->object_id = (int)$object_id;
```
Comment (PierreRambaud) [inline classes/PrestaShopLogger.php]:
```suggestion
            $log->object_id = (int) $object_id;
```

Comment (lmeyer1) [reply classes/PrestaShopLogger.php]: Sorry, I missed this typo

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by lmeyer1** [comment]
The objectType of `'Swift_Message'` used in `classes/Mail.php` is not valid. The field is defined in `PrestaShopLogger.php` with `isName`.

    'object_type' => ['type' => self::TYPE_STRING, 'validate' => 'isName'],

I push a new commit to correct this secondary issue.

This also explains the observation of @hibatallahAouadni that she didn't receive the error (see https://github.com/PrestaShop/PrestaShop/issues/24706#issuecomment-851392686)

>Hello @lmeyer1
>In my ps_log, the whole line doesn't exist like I didn't send the test mail and didn't receive the error.
>But when I try to change an Order status, then I reproduce the issue, (...)

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

File: classes/PrestaShopLogger.php [hunk 2]
```diff
@@ -158,9 +158,12 @@ public static function addLog($message, $severity = 1, $errorCode = null, $objec
             $log->id_employee = (int) $idEmployee;
         }
 
-        if (!empty($objectType) && !empty($objectId)) {
-            $log->object_type = pSQL($objectType);
-            $log->object_id = (int) $objectId;
+        if (!empty($object_type)) {
+            $log->object_type = pSQL($object_type);
```
Comment (eternoendless) [inline classes/PrestaShopLogger.php]: This will never work, the variable names are incorrect vs the method's parameters:
```suggestion
        if (!empty($objectType)) {
            $log->object_type = pSQL($objectType);
```

File: classes/PrestaShopLogger.php [hunk 3]
```diff
@@ -158,9 +158,12 @@ public static function addLog($message, $severity = 1, $errorCode = null, $objec
...
+        }
+
+        if (!empty($object_id)) {
+            $log->object_id = (int) $object_id;
```
Comment (eternoendless) [inline classes/PrestaShopLogger.php]: Same here:
```suggestion
        if (!empty($objectId)) {
            $log->object_id = (int) $objectId;
```

**Review by eternoendless — CHANGES_REQUESTED** [review]

File: classes/PrestaShopLogger.php (hunk 3 above)
Comment (eternoendless) [reply classes/PrestaShopLogger.php]: This part only makes sense if an objectType has been defined

File: classes/Mail.php [hunk 4]
```diff
@@ -656,7 +656,7 @@ function ($carry, $item) {
                 'Swift Error: ' . $e->getMessage(),
                 3,
                 null,
-                'Swift_Message'
+                'SwiftMessage'
```
Comment (eternoendless) [inline classes/Mail.php:659]: Why did you change this?

File: classes/PrestaShopLogger.php (hunk 2 above)
Comment (lmeyer1) [reply classes/PrestaShopLogger.php]: Sorry, I missed that.

File: classes/Mail.php (hunk 4 above)
Comment (lmeyer1) [reply classes/Mail.php:659]: I changed it, because all other `$objectType`s are in camelcase.

But since I didn't change the occurrence of `Swift_Message` in `PrestashopLogger`, it's bad.

File: classes/PrestaShopLogger.php (hunk 2 above)
Comment (lmeyer1) [reply classes/PrestaShopLogger.php]: I think, we should not escape with `pSQL()` here, nor in `$log->message = pSQL($message);` above.
This leads to double escaping.

**Comment by lmeyer1** [comment]
@eternoendless UI tests are failing at `Order a product and check order confirmation
    1) should Pay by back wire and confirm order`.
Should I try later ? There seems to be no relation to the change. 
Or is it because my fork from `develop` branch is too old ?

File: classes/Mail.php (hunk 4 above)
Comment (lmeyer1) [reply classes/Mail.php:659]: In fact, I commented before on the reason why I changed this:
https://github.com/PrestaShop/PrestaShop/pull/24707#issuecomment-857672010

`Swift_Message` does not validate with the `isName` rule, but it has to.
The right correction is to change `Swift_Message` to  `SwiftMessage` everywhere.

Comment (eternoendless) [reply classes/Mail.php:659]: OK I get it. I'm not thrilled about it as the original object isn't written like that, but looks harmless otherwise.

**Review by eternoendless — APPROVED** [review]
Looks good to me

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,
The issue is fixed. The the object_type 'Swift_Message' is added.
https://www.awesomescreenshot.com/video/5813614?key=7bf7bb5cf1c47bb632ed58f5e39423da
Thanks,

**Comment by Progi1984** [comment]
Thanks @lmeyer1 & @marwachelly
