### PR TITLE
Better handle aliases with space in search

### LINKED ISSUE #22444: [FO] Make a search with Alias composed with two words doesn't show any results
#### Describe the bug

After creating a new alias composed with two words (**tee shirt => sweater**), I tried to make a search in **FO** by the newly created alias (**tee shirt**), but there's no product displayed.

With **PS1.7.6.9**, it works perfectly (see the attached screen record below)

#### Expected behavior

Display the product contain the search term (**sweater**)

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Shop Parameters** > **Search**
2. Click on **Add new** alias button
3. Write **"tee shirt"** in **Alias** input and **"sweater"** (or **"t-shirt"**) in **Result** input, then **Save**
4. **FO** > make a search by **"tee shirt"**, there's no result

**Screenshots**

**PS1.7.6.9:**
https://drive.google.com/file/d/1Oa2a5H9NGHCWcY-Zbv2CAtaY8SbCRTCY/view

**PS1.7.7.0:**
https://drive.google.com/file/d/1xMsFjeVDWsXaCbvarI_pyD9ompaMZ6jI/view

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

_This bug is originally reported by @MatShir_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Since the fuzzy search has been implemented, aliases with space weren't take into account as well as before. This PR aims to fix this.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22444
| How to test?      | Please See #22444
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22528)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

File: classes/Search.php [hunk 1]
```diff
@@ -182,15 +182,17 @@ public static function sanitize($string, $id_lang, $indexation = false, $iso_cod
...
-                $alias = new Alias(null, $word);
-                if (Validate::isLoadedObject($alias)) {
-                    $processed_words[] = $alias->search;
-                } else {
-                    $processed_words[] = $word;
-                }
+            $aliases = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS('
+				SELECT a.alias, a.search
+				FROM `' . _DB_PREFIX_ . 'alias` a
+				WHERE \'' . pSQL($string) . '\' LIKE CONCAT(\'%\', alias, \'%\') AND `active` = 1');
```
Comment (PierreRambaud) [inline classes/Search.php]:
```suggestion
				WHERE \'' . pSQL($string) . '\' REGEXP CONCAT(\'(^|[[:space:]])\', alias, \'([[:space:]]|$)\') AND `active` = 1');
```

Because if you have a lot of words, the search is not looking for boundaries.
Example:
You have this:
image

With LIKE and CONCAT:
image


With word boundaries (compatible MySQL 5.6 :sob: )
image

With word boundaries and more checks:
image

**Review by PierreRambaud — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by Roomsmaniia** [comment]
Hi @atomiix,
It doesn't work when i write 2 words in alias
ex : tee shirt : dont work
teeshirt : work

Thanks

**Comment by atomiix** [comment]
@RomainBocheux I'm maybe missing something but when I have no alias and I search "tee shirt" I have no result:
Capture d’écran 2020-12-23 à 10 44 08

But when I create an alias "tee shirt" with "t-shirt" as search value and then I search "tee shirt" again, I have a result:
Capture d’écran 2020-12-23 à 10 43 38

**Comment by Roomsmaniia** [comment]
@atomiix I asked @khouloudbelguith to try and she has the same problem
https://drive.google.com/file/d/1ztNuKGCNetH4u0FPrtOOsRGK0NZ6pTBp/view

**Comment by Robin-Fischer-PS** [comment]
PR needs review before QA :)

File: classes/Search.php [hunk 2]
```diff
@@ -182,15 +182,31 @@ public static function sanitize($string, $id_lang, $indexation = false, $iso_cod
...
-                    $processed_words[] = $word;
-                }
+            $query = '
+				SELECT a.alias, a.search
+				FROM `' . _DB_PREFIX_ . 'alias` a
+				WHERE \'' . pSQL($string) . '\' %s AND `active` = 1
+            ';
+
+            // check if we can we use '\b' (faster)
+            $useICU = (bool) Db::getInstance(_PS_USE_SQL_SLAVE_)->getValue(
```
Comment (Progi1984) [inline classes/Search.php]:
```suggestion
            $useICU = (bool) Db::getInstance((bool) _PS_USE_SQL_SLAVE_)->getValue(
```

File: classes/Search.php [hunk 3]
```diff
@@ -182,15 +182,31 @@ public static function sanitize($string, $id_lang, $indexation = false, $iso_cod
...
+                'SELECT 1 FROM DUAL WHERE \'icu regex\' REGEXP \'\\\\bregex\''
+            );
+            $aliases = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS(
```
Comment (Progi1984) [inline classes/Search.php]:
```suggestion
            $aliases = Db::getInstance((bool) _PS_USE_SQL_SLAVE_)->executeS(
```

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1_-xr1szBVs8UsxreHfElrSaHE1XyCcj1/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
