### PR TITLE
Fix missing translations on meta pages

### LINKED ISSUE #28944: Missing translations on meta pages
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On clean install of PrestaShop, several translations are missing on meta pages.

- "Brands" on `manufacturers` page title
- "Brands list" on `manufacturers` page description
- "brands" on `manufacturers` page url rewrite
- "Our special products" on `prices-drop` page description

### Expected behavior

No missing translations.

### Steps to reproduce

1. Make a clean install of PrestaShop in another language than English (e.g. French)
2. Go to `Paramètres de la boutique > Trafic et SEO`
3. See missing translations on `manufacturers` and `prices-drop` pages

### PrestaShop version(s) where the bug happened

1.7.x.x

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fixes missing translations on `manufacturers` and `prices-drop` pages.<br><br>Translation strings must match those used here: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/en/data/meta.xml.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28944.
| Related PRs       | -
| How to test?      | See issue description.
| Possible impacts? | -
| Sponsor company | @Creabilis

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by micka-fdz** [comment]
Hi @Julievrz, translations already exists here. We just need to change source on CrowdIn if possible (or create new ones?).

- "Manufacturers" is now "Brands"
- "Brand list" is now "Brands list"
- "On-sale products" is now "Our special products"
- "manufacturers" is now "brands"
- "supplier" is now "suppliers"

**Comment by okom3pom** [comment]
@Julievrz i am not sure it's news wording, it's to match with h`ttps://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/en/data/meta.xml.`

File: classes/lang/KeysReference/MetaLang.php [hunk 1]
```diff
@@ -56,26 +56,26 @@
 
 trans('Shop powered by PrestaShop', 'Shop.Navigation');
 
-trans('Brand list', 'Shop.Navigation');
```
Comment (Julievrz) [inline classes/lang/KeysReference/MetaLang.php:59]: Maybe we could use the existing string "List of all brands" in Shop.Theme.Global to avoid creating a new string.

File: classes/lang/KeysReference/MetaLang.php [hunk 2]
```diff
@@ -26,7 +26,7 @@
 trans('404 error', 'Shop.Navigation');
 trans('Best sales', 'Shop.Navigation');
 trans('Contact us', 'Shop.Navigation');
-trans('Manufacturers', 'Shop.Navigation');
+trans('Brands', 'Shop.Navigation');
```
Comment (Julievrz) [inline classes/lang/KeysReference/MetaLang.php:29]:
```suggestion
trans('Brands', 'Shop.Theme.Global');
```

Let's use the existing string.

File: classes/lang/KeysReference/MetaLang.php [hunk 3]
```diff
@@ -56,26 +56,26 @@
...
+trans('Our special products', 'Shop.Navigation');
 
 trans('Lost ? Find what your are looking for', 'Shop.Navigation');
 
 trans('Suppliers list', 'Shop.Navigation');
 trans('page-not-found', 'Shop.Navigation');
 trans('best-sales', 'Shop.Navigation');
 trans('contact-us', 'Shop.Navigation');
-trans('manufacturers', 'Shop.Navigation');
+trans('brands', 'Shop.Navigation');
```
Comment (Julievrz) [inline classes/lang/KeysReference/MetaLang.php:73]:
```suggestion
trans('brands', 'Shop.Theme.Catalog');
```
The string already exists in Shop.Theme.Catalog

**Comment by micka-fdz** [comment]
Hi @Julievrz,

For consistency, I think we need to keep same translation domain in entire file.
Moreover, these translations are not related at all to theme (`Shop.Theme.x`).

Wdyt ?

**Comment by kpodemski** [comment]
I'm removing "Waiting for QA" and adding "Waiting for author" to address @Julievrz feedback

**Comment by Julievrz** [comment]
> Hi @Julievrz,
> 
> For consistency, I think we need to keep same translation domain in entire file. Moreover, these translations are not related at all to theme (`Shop.Theme.x`).
> 
> Wdyt ?

I understand your point but if the string already exists I think it's better to use it instead of creating a new one. Otherwise, translators will have to translate the same string over and over again. 😅 The strings are attached to the classic default theme, right?

**Review by Julievrz — APPROVED** [review]
After discussing with @micka-fdz I approve the wording of this PR. Thanks for the clarification. :-)

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @micka-fdz ,

I did the install in French, check SEO & URL, the translation is still missing on Brands, . I dont have what you said [here](https://github.com/PrestaShop/PrestaShop/issues/28944#issuecomment-1173995123).

Without PR and with PR, it is the same result.
Manufacturer:
Screenshot 2022-07-19 at 11 56 18
Prices drop:
Screenshot 2022-07-19 at 11 56 23
Suppliers:
Screenshot 2022-07-19 at 12 11 23

What do you think ?

**Comment by Julievrz** [comment]
> Hello @micka-fdz ,
> 
> I did the install in French, check SEO & URL, the translation is still missing on Brands, . I dont have what you said [here](https://github.com/PrestaShop/PrestaShop/issues/28944#issuecomment-1173995123).
> 
> Without PR and with PR, it is the same result. Manufacturer: Screenshot 2022-07-19 at 11 56 18 Prices drop: Screenshot 2022-07-19 at 11 56 23 Suppliers: Screenshot 2022-07-19 at 12 11 23
> 
> What do you think ?

I think it's because the strings have not been pushed to Crowdin yet, and so they are not yet translated.

**Comment by micka-fdz** [comment]
Hi @florine2623,

I think @Julievrz is right. However, we can see new wordings on your screenshots so it's ok.

**Comment by micka-fdz** [comment]
@Julievrz when do new translations appear on Crowdin? Once the PR is merged?

**Comment by Julievrz** [comment]
> @Julievrz when do new translations appear on Crowdin? Once the PR is merged?

Usually a few weeks before the release of a major or minor version.

**Comment by micka-fdz** [comment]
> Usually a few weeks before the release of a major or minor version.

Ok thanks 👍

**Review by florine2623 — APPROVED** [review]
Hello @Julievrz & @micka-fdz ,

Thanks for the details ^^

It is QA ✅

**Comment by matthieu-rolland** [comment]
thank you @micka-fdz and @florine2623 👍

**Comment by SharakPL** [comment]
Are you sure changing MetaLang.php is enough for this? What about default translations? That's what gets translated on Crowdin, right? It still uses old phrases:

https://github.com/PrestaShop/PrestaShop/blob/3f93469a87a7f1fc2ce25f13e5af293936faef41/translations/default/ShopNavigation.xlf#L20-L24

https://github.com/PrestaShop/PrestaShop/blob/3f93469a87a7f1fc2ce25f13e5af293936faef41/translations/default/ShopNavigation.xlf#L150-L154

https://github.com/PrestaShop/PrestaShop/blob/3f93469a87a7f1fc2ce25f13e5af293936faef41/translations/default/ShopNavigation.xlf#L165-L169

https://github.com/PrestaShop/PrestaShop/blob/3f93469a87a7f1fc2ce25f13e5af293936faef41/translations/default/ShopNavigation.xlf#L195-L199

https://github.com/PrestaShop/PrestaShop/blob/3f93469a87a7f1fc2ce25f13e5af293936faef41/translations/default/ShopNavigation.xlf#L220-L224

ref. #30620
