### PR TITLE
Product duplication in table ps_product_supplier

### LINKED ISSUE #19574: Duplicate combination product results in 500 error page (product is still duplicated)
**Describe the bug**
When duplicating a product in some situations a 500 error page is shown. This happens in a multistore installation and only with products that have features and/or combinations. When I duplicate a simple product without features/combinations no error is shown.

When the error is shown the product is still created, but there are no features and images in the created product.

**Expected behavior**
Just like a simple product a product with features/combinations should also be nicely duplicated

**Steps to Reproduce**

- Activate multistore, All Shops environment in BO
- Have Suppliers ready
- Go to Products list
- Try to duplicate a product with combinations -> OK
- Edit that product > in tab Option, choose a Supplier > Save
- Go back to your product list
- Duplicate the newly edited product -> NOK 500 error
- After refreshing the page, product has been duplicated

**Error shown with debug mode :**
Capture d’écran 2020-06-05 à 17 44 51
So I guess it's a combination of having a supplier selected and have a combination in the product. 

Error looks similar to this old issue: https://web.archive.org/web/20180318141337/http://forge.prestashop.com/browse/PSCSX-9828

### PR DESCRIPTION
**Pull request by levyn**
Excessive product duplication in table ps_product_supplier

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When duplicating a product in a multistore installation and only with products that have features and/or combinations a 500 error page is shown.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | yes / no
| Deprecations? | no
| Fixed ticket? | Fixes #19574 
| How to test?  | Activate multistore<br>All Shops environment in BO<br>Have Suppliers ready<br>Go to Products list<br>Edit that product > in tab Option, choose a Supplier > Save<br>Go back to your product list<br>Duplicate the newly edited product -> NOK 500 error

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20153)

### CODE REVIEW

File: classes/Product.php [hunk 1]
```diff
@@ -4799,6 +4800,14 @@ public static function duplicateAttributes($id_product_old, $id_product_new)
...
 
             foreach ($result3 as $row3) {
+                $current_supplier_key = $id_product_new . '_' . $id_product_attribute_new . '_' . $row3['id_supplier'];
+
+                if (in_array($current_supplier_key, $product_supplier_keys)) {
+                    continue;
+                } else {
+                    $product_supplier_keys[] = $current_supplier_key;
+                }
+
```
Comment (PierreRambaud) [inline classes/Product.php]:
```suggestion
                if (in_array($current_supplier_key, $product_supplier_keys)) {
                    continue;
                }

                $product_supplier_keys[] = $current_supplier_key;

```

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @levyn,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/13I_ZtWOyrqRsX8sbo0PXBtwMMikQM-ow/view?usp=sharing
Thanks!!

**Comment by Progi1984** [comment]
Thanks @levyn & @khouloudbelguith
