### PR TITLE
Use AsyncToggleColumnExtension for Customers list

### LINKED ISSUE #25114: When using toggle in Customers listing, whole page is refreshed although only row could be refreshed
#### Describe the bug

When using toggle in Customers listing (3 fields can be toggled: "enabled", "newsletter" and "partner offers"), whole page is refreshed. We could refresh only the row being updated, this makes the user experience better and saves computing resources.

#### Expected behavior

When using toggle in Customers listing (3 fields can be toggled: "enabled", "newsletter" and "partner offers", only the modified row is modified.

This is the behavior implemented on Category listing.

#### Steps to Reproduce

1. Go to BO Customers list
2. Click on one of the fields that can be toggled (see screenshot below)
3. See that after the action has been done, the whole page is refreshed
4. You can compare with BO Category list: go to Category list, click on the field that can be toggled, no full page refresh

**Screenshots**

Capture d’écran 2021-06-24 à 10 46 40

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/25114
| How to test?      | See ticket steps https://github.com/PrestaShop/PrestaShop/issues/25114
| Possible impacts? | I only modify the JS behavior of Customers list, for the Toggle action, and the controllers responsible for the action behavior.

# Description

As explained in https://github.com/PrestaShop/PrestaShop/issues/25114, when we use "toggle action" on the Customers grid, the whole page Customers listing page is refreshed.

I replace `ColumnTogglingExtension` by `AsyncToggleColumnExtension` to improve this. Thanks to the replacement, only the clicked row is updated, not the whole page. So when user toggles one of the togglable field (newsletter, enabled, partner offers), the page does not reload. The user experience is better then.

This also requires to modify the controllers response. With `ColumnTogglingExtension` they return a redirect response, with `AsyncToggleColumnExtension` we need a JSON response to the ajax query being performed. The backend logic remains unmodified.

# BC Breaks

As requested by @PierreRambaud and @jolelievre I modified the return type of controller actions from HttpResponse to JSONResponse.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25115)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/customer/index.js [hunk 1]
```diff
@@ -59,10 +59,11 @@ $(() => {
   customerGrid.addExtension(new SubmitBulkExtension());
   customerGrid.addExtension(new SubmitGridExtension());
   customerGrid.addExtension(new LinkRowActionExtension());
-  customerGrid.addExtension(new ColumnTogglingExtension());
   customerGrid.addExtension(new DeleteCustomersBulkActionExtension());
   customerGrid.addExtension(new DeleteCustomerRowActionExtension());
   customerGrid.addExtension(new FiltersSubmitButtonEnablerExtension());
+  customerGrid.addExtension(new AsyncToggleColumnExtension());
+
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/customer/index.js]:
```suggestion
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 2]
```diff
@@ -516,15 +516,18 @@ public function toggleStatusAction($customerId)
...
         } catch (CustomerException $e) {
-            $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
+            $response = [
+                'status' => false,
+                'message' => $this->getErrorMessageForException($e, $this->getErrorMessages($e)),
+            ];
         }
 
-        return $this->redirectToRoute('admin_customers_index');
+        return $this->json($response);
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php:530]: Please update PHPDoc : it's not anymore a `RedirectResponse`

**Review by Progi1984 — COMMENTED** [review]
A feedback... and a question : isn't it a BC Break as we change return type ?

**Comment by matks** [comment]
> A feedback... and a question : isn't it a BC Break as we change return type ?

Very good question: are our controllers part of our public API?

I can depreciate current controller actions and create new ones to work around it, but it would be good to know if, in general, controller actions are part of the public API and must be protected against BC breaks.

**Comment by Progi1984** [comment]
@matks If it was typed, with semver, it would be a BC Break. But like it's not typed... it shouldn't be a BC Break.

(:heart: typehint)

**Comment by matks** [comment]
> @matks If it was typed, with semver, it would be a BC Break. But like it's not typed... it shouldn't be a BC Break.
> 
> (❤️ typehint)

Even though it's not typed, I completely modify the response. It used to be a Redirect, now it's a JSON. If a module is using this route it's 100% it'll break its behavior. So even if we don't call it a "BC break" it's a "something Break".

**Comment by sowbiba** [comment]
> > @matks If it was typed, with semver, it would be a BC Break. But like it's not typed... it shouldn't be a BC Break.
> > (heart typehint)
> 
> Even though it's not typed, I completely modify the response. It used to be a Redirect, now it's a JSON. If a module is using this route it's 100% it'll break its behavior. So even if we don't call it a "BC break" it's a "something Break".

I would write another action returning JSON and deprecate the current action, and maybe add in private method the common behaviour to ease future drop. For the same reason you explained : If someone is using it elsewhere, it will break his expectations

we are open for theme creation, even in BO, so someone is probably using it in his theme and plug a lot of stuff depending on the result :D :D

**Review by matthieu-rolland — COMMENTED** [review]
phpstan is not happy about receiving a JsonResponse instead of a RedirectResponse, otherwise LGTM 👍

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php:530]: And it's a BC break since you change the contract and behaviour of the "API", no more redirection but JSON formatted response

**Review by jolelievre — DISMISSED** [review]

**Comment by matks** [comment]
Hello @Progi1984 @sowbiba @jolelievre I have applied @sowbiba suggestion in https://github.com/PrestaShop/PrestaShop/pull/25115/commits/4a29c851fbd2c313aea645fe1f6f810ff46a2cbd

> I would write another action returning JSON and deprecate the current action, and maybe add in private method the common behaviour to ease future drop. For the same reason you explained : If someone is using it elsewhere, it will break his expectations

I also did something maybe a bit crazy 😛 with `performActionThenReturnJsonResponse` that uses a string that is a function name we call (I wanted to use a callable but it seems I cannot use `$this`). Please tell me what you think about it 😄 it was fun to write but maybe the logic is a bit over the head

**Comment by kpodemski** [comment]
@matks interesting, maybe this method should be available globally for all controllers?

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 3]
```diff
@@ -527,6 +534,25 @@ public function toggleStatusAction($customerId)
...
+     *     "is_granted('update', request.get('_legacy_controller'))",
+     *     redirectRoute="admin_customers_index",
+     *     message="You do not have permission to edit this."
+     * )
+     *
+     * @param int $customerId
+     *
+     * @return JsonResponse
+     */
+    public function toggleStatusThenReturnJsonAction($customerId)
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    public function toggleStatusThenReturnJsonAction(int $customerId)
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 4]
```diff
@@ -527,6 +534,25 @@ public function toggleStatusAction($customerId)
...
+    {
+        return $this->performActionThenReturnJsonResponse(
+            'toggleCustomerStatus',
+            (int) $customerId
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
            $customerId
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 5]
```diff
@@ -564,6 +593,25 @@ public function toggleNewsletterSubscriptionAction($customerId)
...
+     * @return JsonResponse
+     */
+    public function toggleNewsletterSubscriptionThenReturnJsonAction($customerId)
+    {
+        return $this->performActionThenReturnJsonResponse(
+            'toggleCustomerNewsletterSubscription',
+            (int) $customerId
+        );
+    }
+
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    public function toggleNewsletterSubscriptionThenReturnJsonAction(int $customerId)
    {
        return $this->performActionThenReturnJsonResponse(
            'toggleCustomerNewsletterSubscription',
            $customerId
        );
    }

```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 6]
```diff
@@ -599,6 +652,25 @@ public function togglePartnerOfferSubscriptionAction($customerId)
...
+     * @return JsonResponse
+     */
+    public function togglePartnerOfferSubscriptionThenReturnJsonAction($customerId)
+    {
+        return $this->performActionThenReturnJsonResponse(
+            'toggleCustomerPartnerOfferSubscription',
+            (int) $customerId
+        );
+    }
+
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    public function togglePartnerOfferSubscriptionThenReturnJsonAction(int $customerId)
    {
        return $this->performActionThenReturnJsonResponse(
            'toggleCustomerPartnerOfferSubscription',
            $customerId
        );
    }

```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 3 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    public function toggleStatusThenReturnJsonAction(int $customerId): JsonResponse
```

Better ;)

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 7]
```diff
@@ -564,6 +593,25 @@ public function toggleNewsletterSubscriptionAction($customerId)
...
+     *     "is_granted('update', request.get('_legacy_controller'))",
+     *     redirectRoute="admin_customers_index",
+     *     message="You do not have permission to edit this."
+     * )
+     *
+     * @param int $customerId
+     *
+     * @return JsonResponse
+     */
+    public function toggleNewsletterSubscriptionThenReturnJsonAction(int $customerId)
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    public function toggleNewsletterSubscriptionThenReturnJsonAction(int $customerId): JsonResponse
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 8]
```diff
@@ -599,6 +652,25 @@ public function togglePartnerOfferSubscriptionAction($customerId)
...
+     *     "is_granted('update', request.get('_legacy_controller'))",
+     *     redirectRoute="admin_customers_index",
+     *     message="You do not have permission to edit this."
+     * )
+     *
+     * @param int $customerId
+     *
+     * @return JsonResponse
+     */
+    public function togglePartnerOfferSubscriptionThenReturnJsonAction(int $customerId)
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    public function togglePartnerOfferSubscriptionThenReturnJsonAction(int $customerId): JsonResponse
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 9]
```diff
@@ -849,6 +921,81 @@ public function getOrdersAction(int $customerId)
...
+        // toggle newsletter subscription
+        $editCustomerCommand->setNewsletterSubscribed(!$editableCustomer->isNewsletterSubscribed());
+
+        $this->getCommandBus()->handle($editCustomerCommand);
+    }
+
+    /**
+     * @param int $customerId
+     */
+    protected function toggleCustomerPartnerOfferSubscription(int $customerId)
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    protected function toggleCustomerPartnerOfferSubscription(int $customerId): void
```

**Review by Progi1984 — COMMENTED** [review]
@matks Thank you for your contribution. I have added some typing to your PR. Could you add it before approve ?

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 6 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Fixed in https://github.com/PrestaShop/PrestaShop/pull/25115/commits/5aabb5bb639e79844a62601873be667ab4bb33ab

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 5 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Fixed in https://github.com/PrestaShop/PrestaShop/pull/25115/commits/5aabb5bb639e79844a62601873be667ab4bb33ab

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 4 above)
Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Fixed in https://github.com/PrestaShop/PrestaShop/pull/25115/commits/5aabb5bb639e79844a62601873be667ab4bb33ab

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@matks Sorry for disturbing you again. Could you rebase your PR for fixing conflicting file ?

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
I really, really, really dislike adding `ThenReturnJson` in the action name. It's really ugly and has nothing to do in the action. :thinking:

**Comment by matks** [comment]
> I really, really, really dislike adding `ThenReturnJson` in the action name. It's really ugly and has nothing to do in the action. 🤔

I will gladly use any new name you like 😄  I just need something different from current actions.

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 10]
```diff
@@ -849,6 +920,81 @@ public function getOrdersAction(int $customerId)
         ]);
     }
 
+    /**
+     * @param string $callable that will be called before JSON response is built and returned
+     * @param int $customerId that will be passed to callable
+     *
+     * @return JsonResponse
+     */
+    protected function performActionThenReturnJsonResponse(string $callable, int $customerId): JsonResponse
```
Comment (eternoendless) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
    protected function performActionThenReturnJsonResponse(callable $callable, int $customerId): JsonResponse
```

Comment (eternoendless) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: Then you send callables instead of just strings

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 11]
```diff
@@ -849,6 +920,81 @@ public function getOrdersAction(int $customerId)
...
+    {
+        if (!method_exists($this, $callable)) {
```
Comment (eternoendless) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
        if (!is_callable($callable)) {
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 12]
```diff
@@ -849,6 +920,81 @@ public function getOrdersAction(int $customerId)
...
+            throw new RuntimeException(sprintf('Cannot call %s on %s',
+                $callable,
+                get_class($this)));
+        }
+
+        try {
+            $this->$callable($customerId);
```
Comment (eternoendless) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]:
```suggestion
            call_user_func($callable, $customerId);
```

**Comment by PierreRambaud** [comment]
> > I really, really, really dislike adding `ThenReturnJson` in the action name. It's really ugly and has nothing to do in the action. thinking
> 
> I will gladly use any new name you like  I just need something different from current actions.

I'm more in favor of keeping the current name and if you want to keep the old behavior create dedicated action for that.
I see no reason to create a new name for a new method, unrelated to what we use in other controllers. We should accept BC breaks here

**Comment by matks** [comment]
> > > I really, really, really dislike adding `ThenReturnJson` in the action name. It's really ugly and has nothing to do in the action. thinking
> > 
> > 
> > I will gladly use any new name you like  I just need something different from current actions.
> 
> I'm more in favor of keeping the current name and if you want to keep the old behavior create dedicated action for that.
> I see no reason to create a new name for a new method, unrelated to what we use in other controllers. We should accept BC breaks here

Applied in commit https://github.com/matks/PrestaShop/commit/884f621d3c2899c2e1814992495261349f475248

Now the diff is a lot simpler. I enable the JavaScript Grid extension and transform existing controller actions so that they return JSON instead of HTTP redirect.

**Review by jolelievre — APPROVED** [review]
I approve this, however this is regarded as a BC break the API contract is completely modified You should notate the PR as a BC break, and add a small paragraph in the description

**Review by eternoendless — APPROVED** [review]
Looks good

**Comment by matks** [comment]
> You should notate the PR as a BC break, and add a small paragraph in the description

Done

**Review by kpodemski — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @matks & @sarahdib
