### PR TITLE
Use language_code when locale is empty to get CLDR data

### LINKED ISSUE #21891: Adding incorrect language causes exception in Edit Currency page.
#### Describe the bug
Adding incorrect language causes "Cache key length must be greater than zero." error when trying to edit currency. Now I don't know if PrestaShop should implement safeguards against incorrect language or how often and why user would add an incorrect language. But in this case error was rather confusing and I thought something wrong with my cache. 

In this case function LocaleRepository->getLocale receives empty $localeCode(i guess at some point PrestaShop fails to find localeCode for incorrect language and simply sends empty localeCode to this function). I would suggest to thorw an Exception here in case localeCode is empty, since exception will be thrown anyway once PrestaShop tries to find empty localeCode in locale cache. 

#### Expected behavior

Incorrect language either shouldn't impact PrestaShop in anyway or Exception should be very clear with what went wrong.

#### Steps to Reproduce

1) Add incorrect language for example ISO Code = aa Language Code = en-TS
2) Try to edit currency, receive error "Cache key length must be greater than zero."

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop(1.7.8).
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Because on custom languages, the key `locale` of the `ps_lang` table is empty, when trying to access the cache data, an exception is thown because the key is empty. This PR fixes it by using the key `language_code` when `locale` is empty.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21891
| How to test?  | Please see #21891

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21912)

### CODE REVIEW

File: classes/Currency.php [hunk 1]
```diff
@@ -1134,13 +1134,13 @@ public function refreshLocalizedCurrencyData(array $languages, LocaleRepository
         $symbolsByLang = $namesByLang = [];
         foreach ($languages as $languageData) {
             $language = new Language($languageData['id_lang']);
+            $localeString = $language->locale;
             if (empty($language->locale)) {
```
Comment (PierreRambaud) [inline classes/Currency.php]:
```suggestion
           $localeString = empty($language->locale) ? $language->getLanguageCode() : $language->locale;
```

File: classes/Language.php [hunk 2]
```diff
@@ -793,6 +793,28 @@ public static function getIdByLocale($locale, $noCache = false)
...
 
+    /**
+     * Returns language id from language code
+     *
+     * @param string $code Locale IETF language tag
+     * @param bool $noCache
+     *
+     * @return int|false|null
+     */
+    public static function getIdByCode($code, $noCache = false)
```
Comment (PierreRambaud) [inline classes/Language.php]:
```suggestion
    public static function getIdByCode(string $code, bool $noCache = false)
```

File: src/Adapter/Currency/CurrencyDataProvider.php [hunk 3]
```diff
@@ -109,7 +109,12 @@ public function getCurrencyByIsoCode($isoCode, $idLang = null)
      */
     public function getCurrencyByIsoCodeAndLocale($isoCode, $locale)
     {
+        // Language available from the CLDR
         $idLang = Language::getIdByLocale($locale, true);
+        if (false === $idLang) {
```
Comment (PierreRambaud) [inline src/Adapter/Currency/CurrencyDataProvider.php]: What about null value?

File: src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php [hunk 4]
```diff
@@ -116,7 +116,12 @@ protected function doRead($currencyDataId)
         $currencyData->setNames([$localeCode => $currencyEntity->name]);
         $currencyData->setSymbols([$localeCode => $currencyEntity->symbol]);
 
+        // Language available from the CLDR
         $idLang = Language::getIdByLocale($localeCode, true);
+        if (false === $idLang) {
```
Comment (PierreRambaud) [inline src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php]: Same about the null value

Comment (jolelievre) [inline src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php]:
```suggestion
        if (empty($idLang)) {
```

File: src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php [hunk 5]
```diff
@@ -214,8 +214,12 @@ private function getLanguagesData(string $currencyIsoCode)
         $languagesData = [];
         /** @var LanguageInterface $language */
         foreach ($languages as $language) {
-            $locale = $localeRepository->getLocale($language->getLocale());
-            $cldrLocale = $cldrLocaleRepository->getLocale($language->getLocale());
+            $localeString = $language->getLocale();
+            if ('' === $localeString) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]:
```suggestion
            if (empty($localeString)) {
```

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php]: It will cover more error cases (like null or false) just to be sure

File: classes/Currency.php (hunk 1 above)
Comment (Progi1984) [reply classes/Currency.php]: Approved !

File: src/Adapter/Currency/CurrencyDataProvider.php (hunk 3 above)
Comment (Progi1984) [reply src/Adapter/Currency/CurrencyDataProvider.php]:
```suggestion
        if (empty($idLang)) {
```

File: src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php (hunk 4 above)
Comment (Progi1984) [reply src/Core/Localization/Currency/DataLayer/CurrencyDatabase.php]:
```suggestion
        if (empty($idLang)) {
```

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an issue following these steps:

1. Go to BO > International > Localization > Currencies page
2. Click "add new currency"
3. Select a currency
4. See the error "the Modal is still loading"

image

=> An error 500 in the console

image

Thanks!

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I have an exception following these steps:

1. Go to BO > International > Localization > Languages Tab
2. Add incorrect language for example ISO Code = aa Language Code = en-TS
 image
3. In the BO > International > Localization > change the Default language with the last language created
4. Go to BO > International > Localization > Currencies
5. Add new currency
6. Select for example "Algerian Dinar (DZD)"
7. Save
8. Delete it
9. Go to BO > International > Localization Tab
10. Select `Algeria`  and click import
11. See an error

image
https://drive.google.com/file/d/12LcXmjsB4RG8-ZajIg4kCtm_u0uOX4tE/view?usp=sharing

Thanks!

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/LocalizationPack.php [hunk 6]
```diff
@@ -617,4 +618,16 @@ public function getErrors()
     {
         return $this->_errors;
     }
+
+    private function getSoftDeletedByIsoCodeOrCreate(string $isoCode)
```
Comment (PierreRambaud) [inline classes/LocalizationPack.php]:
```suggestion
    private function getSoftDeletedByIsoCodeOrCreate(string $isoCode): Currency
```

And add docblock

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
This fix seem more stable than the initial one However it's a bit disturbing that it changes the behaviour of `getLocale` meaning you can't stricly get its value..
Maybe an alternate getter which manages this fallback would be cleaner

Alternatively since the issue seem to be the lack of locale_code from manually created languages why not fixing the creation process instead so that it's not empty Either copy `language_code` into `locale` on creation (since it seems that it's absent from the form) Or add this field into the form?

**Comment by atomiix** [comment]
@jolelievre actually I wonder if it shouldn't had to be made before but was forget because in `Language.php`, that implements the same interface, [you can see](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/classes/Language.php#L1588-L1596) that this "fallback" has been made.

Maybe a distinct method should be use instead but that would either not be declared in the `LanguageInterface` interface or it will be a BC Break.

I've thought about copying `language_code` into `locale` but that's kind of the only way to know that it's a custom language, so I think it should stay empty.

File: classes/LocalizationPack.php [hunk 7]
```diff
@@ -617,4 +618,26 @@ public function getErrors()
...
+     * Return a currency (that can be soft deleted) if presents in the DB
+     * or a new one if not.
+     *
+     * @param string $isoCode
+     *
+     * @return Currency
+     *
+     * @throws PrestaShopDatabaseException
+     */
+    private function getSoftDeletedByIsoCodeOrCreate(string $isoCode): Currency
```
Comment (sowbiba) [inline classes/LocalizationPack.php]: looking at the method name, I would think that it will return an object only if it's soft-deleted or create a new one

**Review by sowbiba — DISMISSED** [review]

File: classes/LocalizationPack.php (hunk 7 above)
Comment (atomiix) [reply classes/LocalizationPack.php]: You're right, I'm gonna change that name 👍

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
In the end the whole PR became much simpler with the fix in Lang 😅

**Comment by khouloudbelguith** [comment]
Hi @atomiix,


It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1kSQTdz9e50_wbOZTCgjveDJH149OoTvy/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
