### PR TITLE
Specific Price Form : Changing currency change the symbol

### LINKED ISSUE #26482: [BO] Product page, Specific prices - Change currency don't change Symbol
## Describe the bug

When we change the currency condition for specific price, the default currency doesn't change by the currency symbol selected.

Capture d’écran 2021-10-29 à 19 15 14

## Expected behavior

When we change the currency condition for a specific price, the default currency should change by the currency symbol selected. Add Form + Modal Form + Initialization Modal Form

Capture d’écran 2021-10-29 à 19 16 32

Capture d’écran 2021-10-29 à 19 17 42

## Steps to Reproduce

1. Configure more than 1 currency for the shop, for example USD and EUR
2. Go to Product Page
3. Click on 'Add specific price' or Edit one specific price
4. Select specific currency
5. The symbol after the field "Product price (tax excl.)" is still the default currency of shop
6. The symbol in select option between "amount" en "percentage" is still the default currency of shop

## Additional information

Maybe related to #19673 "Default currency symbol" 

* PrestaShop version: 1.7.6.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Specific Price Form : Changing currency change the symbol
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26482
| How to test?      | Cf. #26482 (Only on the Product Page v2) <br><br>Check the same behavior on the page `sell/catalog/catalog-price-rules/new` (Migrated but not totally)

**:notebook: BC Breaks**
* Parameter 4 of the class `PrestaShopBundle\Form\Admin\Sell\Product\Pricing\SpecificPriceType` has changed from  `FormChoiceProviderInterface $currencyByIdChoiceProvider` to `$currencyByIdChoiceProvider`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28068)

### CODE REVIEW

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php [hunk 1]
```diff
@@ -143,12 +144,15 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
             throw new SpecificPriceException('product_id is required to add/edit specific price.');
         }
 
+        dump($this->currencyByIdChoiceProvider->getChoices());
```
Comment (matthieu-rolland) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php]:
```suggestion
```

Comment (Progi1984) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/SpecificPriceType.php]: Fixed

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts [hunk 2]
```diff
@@ -33,9 +35,12 @@ export default class IncludeTaxFieldToggle {
 
   $taxInclusionInputs: JQuery;
 
-  constructor(reductionTypeSelector: string, taxInclusionInputs: string) {
+  reductionTypeAmountSymbol: string;
+
+  constructor(reductionTypeSelector: string, taxInclusionInputs: string, reductionTypeAmountSymbol:string = '') {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts]:
```suggestion
  constructor(reductionTypeSelector: string, taxInclusionInputs: string, reductionTypeAmountSymbolSelector:string) {
```

File: admin-dev/themes/new-theme/js/pages/specific-price/form/currency-symbol-updater.ts [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+/**
+ * Change symbol when the currency select is changed
+ */
+export default class CurrencySymbolUpdater {
+  public constructor() {
+    this.init();
+  }
+
+  private init(): void {
+    const selectCurrency = document.querySelector(SpecificPriceMap.currencyId) as HTMLSelectElement;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/specific-price/form/currency-symbol-updater.ts]: Be careful the `IncludeTaxFieldToggle` component is also used in the catalog price rule form This fix should improve both forms I think But it means the selector ID you use here might be different in the other form so it would need to be configurable via the constructor parameters

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts (hunk 2 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts]: We need to understand that it's a selector or it's confusing with the `const reductionTypeAmountSymbol` which is the HTML element in the handle function

I don't think the parameter should be optional It's a new component in v8 so no BC here

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts [hunk 4]
```diff
@@ -33,9 +35,12 @@ export default class IncludeTaxFieldToggle {
 
   $taxInclusionInputs: JQuery;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts:34]: It's not the scope of this PR but I think this component naming could be improved into `ReductionTaxFieldToggle`

File: src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php [hunk 5]
```diff
@@ -63,4 +64,21 @@ public function getChoices()
...
         return $choices;
     }
+
+    public function getChoicesAttributes()
+    {
+        $currencies = $this->getCurrencies();
+        $choicesAttributes = [];
+
+        foreach ($currencies as $currency) {
+            $choicesAttributes[sprintf('%s (%s)', $currency['name'], $currency['iso_code'])]['symbol'] = $currency['symbol'];
```
Comment (jolelievre) [inline src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php]: This code is a bit hard to read I suggest splitting in two lines:

```suggestion
            $currencyLabel = sprintf('%s (%s)', $currency['name'], $currency['iso_code']);
            $choicesAttributes[$currencyLabel]['symbol'] = $currency['symbol'];
```

**Review by jolelievre — COMMENTED** [review]
Thanks @Progi1984 
A few feedback

**Review by matthieu-rolland — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts (hunk 4 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts:34]: Even if you try ignoring me by resolving the conversation I still think the naming could be improved into `ReductionTaxFieldToggle` 😅

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts [hunk 6]
```diff
@@ -33,9 +33,20 @@ export default class IncludeTaxFieldToggle {
...
 
-  constructor(reductionTypeSelector: string, taxInclusionInputs: string) {
+  currencySymbolSelect: string;
+
+  reductionTypeAmountSymbolSelector: string;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts]:
```suggestion
  reductionAmountSymbolSelector: string;
```

The input with the symbol is only containing the amount not the type, so I think the naming could be simplified (same for the other variables and component mappers) This would make it more understandable and shorter for a bit less code

File: admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts [hunk 7]
```diff
@@ -24,19 +24,40 @@
...
 import IncludeTaxFieldToggle from '@components/form/include-tax-field-toggle';
+import CurrencySymbolUpdater from '@components/form/currency-symbol-updater';
 import PriceFieldAvailabilityHandler from './price-field-availability-handler';
 
 import CatalogPriceRuleFormMap from './catalog-price-rule-form-map';
 
 const {$} = window;
 
 $(() => {
+  new CurrencySymbolUpdater(
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts:35]: Why not include this component directly inside the `IncludeTaxFieldToggle` instead of duplicating the initialization for both use cases? This would make `IncludeTaxFieldToggle` much easier to use

**Review by jolelievre — COMMENTED** [review]
Thanks @Progi1984, almost all good for me except for some naming suggestions and maybe the `CurrencySymbolUpdater` that could be integrated in the `IncludeTaxFieldToggle`


However on a side note we noticed with @matthieu-rolland that the final mock-up doesn't match this fix exactly (see screenshot):
Capture d’écran 2022-03-31 à 16 14 56

The currency and percent symbols would be used in a selector (instead of current explicit selector Amount/Percent), so we wouldn't use a MoneyType anymore meaning the symbol doesn't need to be updated anymore as well

So we need decision from @MatShir and @TristanLDD about which UX they prefer, sorry.
However the good news is that regardless of the decision your fix should be applicable on the Catalog Price Rule form at least (unless of course it is decided to use the new UX on this one as well 😅)

**Comment by jolelievre** [comment]
OOOohhh but wait! I misunderstood the issue completely, the purpose was to update the amount sybol based on which Currency has been selected in the currency selector my bad!

So I thought that this field was only used as a criteria to filter which specific price to use. It turns out this field is also use to define which currency is used to associate with the value of the amount. This changes all, so good news @Progi1984 this PR is gully legit then. Although we'll have to test some use cases because when I see the code the currency seems to be correctly converted for SpecificPrice with values, but those with reductions I'm not so sure!

But anyway @MatShir and @TristanLDD I think we should update the place of this currency input in the form because it's not very intuitive that it impacts the amount values.

Finally @Progi1984 with all this in mind I think there is a field that you don't update since there are two inputs related to a price amount:
Capture d’écran 2022-03-31 à 16 27 47

I believe only the reduction field is updated for now.

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts (hunk 6 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts]: Fixed

File: admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts (hunk 4 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/components/form/include-tax-field-toggle.ts:34]: Fixed

File: admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts (hunk 7 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts:35]: Because it's not the scope of the `ReductionTaxFieldToggle` to update the currency symbol.

**Comment by Progi1984** [comment]
@jolelievre 

> I believe only the reduction field is updated for now.

Two fields are updated : https://github.com/PrestaShop/PrestaShop/pull/28068/files#diff-cda5dd92c407c29436b400b08e9174d9c7da475dc13502df40b394949cceacdeR42-R52

File: admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts [hunk 8]
```diff
@@ -44,10 +55,27 @@ export default class IncludeTaxFieldToggle {
...
+    const isPercentage = this.$reductionTypeSelector.val() === 'percentage';
+
+    if (isPercentage) {
       this.$taxInclusionInputs.fadeOut();
     } else {
       this.$taxInclusionInputs.fadeIn();
     }
+
+    if (this.reductionAmountSymbolSelector !== '') {
+      const reductionTypeAmountSymbol = document.querySelector(this.reductionAmountSymbolSelector) as HTMLInputElement;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts]:
```suggestion
      const reductionTypeAmountSymbol = document.querySelector<HTMLInputElement>(this.reductionAmountSymbolSelector);
```

File: admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts [hunk 9]
```diff
@@ -44,10 +55,27 @@ export default class IncludeTaxFieldToggle {
...
+      reductionTypeAmountSymbol.innerHTML = isPercentage ? '%' : this.getSymbol(reductionTypeAmountSymbol.innerHTML);
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts]: And then verify if it exists before executing this

File: admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts [hunk 10]
```diff
@@ -44,10 +55,27 @@ export default class IncludeTaxFieldToggle {
...
+    }
+  }
+
+  private getSymbol(defaultValue: string): string {
+    const select = document.querySelector(this.currencySymbolSelect) as HTMLSelectElement;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/components/form/reduction-tax-field-toggle.ts]:
```suggestion
    const select = document.querySelector<HTMLSelectElement>(this.currencySymbolSelect);
```

File: admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts [hunk 11]
```diff
@@ -23,20 +23,41 @@
...
+    CatalogPriceRuleFormMap.currencyId,
+    ((symbol: string): void => {
+      if (symbol === '') {
+        return;
+      }
+
+      // Reduction Amount
+      const reductionTypeSelect = document.querySelector(CatalogPriceRuleFormMap.reductionTypeSelect) as HTMLSelectElement;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts]:
```suggestion
      const reductionTypeSelect = document.querySelector<HTMLSelectElement>(CatalogPriceRuleFormMap.reductionTypeSelect);
```

File: admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts [hunk 12]
```diff
@@ -23,20 +23,41 @@
...
+
+      if (reductionTypeSelect.options[reductionTypeSelect.selectedIndex].value === 'amount') {
+        const reductionTypeAmountSymbol = document.querySelector(
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts]: Again, prefer using the generic

File: admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts [hunk 13]
```diff
@@ -24,14 +24,40 @@
...
-  new IncludeTaxFieldToggle(SpecificPriceMap.reductionTypeSelect, SpecificPriceMap.includeTaxInputContainer);
+  new CurrencySymbolUpdater(
+    SpecificPriceMap.currencyId,
+    ((symbol: string): void => {
+      if (symbol === '') {
+        return;
+      }
+
+      // Specific Price
+      const priceSymbol = document.querySelector(SpecificPriceMap.priceSymbol) as HTMLInputElement;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts]: Again use the generic

File: admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts [hunk 14]
```diff
@@ -24,14 +24,40 @@
...
+      priceSymbol.innerHTML = symbol;
+
+      // Reduction Amount
+      const reductionTypeSelect = document.querySelector(SpecificPriceMap.reductionTypeSelect) as HTMLSelectElement;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts]: Generic

File: admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts [hunk 15]
```diff
@@ -24,14 +24,40 @@
...
+
+      if (reductionTypeSelect.options[reductionTypeSelect.selectedIndex].value === 'amount') {
+        const reductionTypeAmountSymbol = document.querySelector(SpecificPriceMap.reductionTypeAmountSymbol) as HTMLInputElement;
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts]: Generic

**Comment by NeOMakinG** [comment]
Think about using the `generics` and verify if the return of `querySelector` is defined

File: admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts [hunk 16]
```diff
@@ -23,20 +23,44 @@
...
+    CatalogPriceRuleFormMap.currencyId,
+    ((symbol: string): void => {
+      if (symbol === '') {
+        return;
+      }
+
+      // Reduction Amount
+      const reductionTypeSelect = document.querySelector<HTMLSelectElement>(CatalogPriceRuleFormMap.reductionTypeSelect);
+
+      if (reductionTypeSelect && reductionTypeSelect.options[reductionTypeSelect.selectedIndex].value === 'amount') {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts]:
```suggestion
      if (reductionTypeSelect?.options[reductionTypeSelect.selectedIndex].value === 'amount') {
```

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/index.ts]: Can you test if this is possible? Not sure as it's inside a compare

File: admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts [hunk 17]
```diff
@@ -24,14 +24,46 @@
...
+      const priceSymbol = document.querySelector<HTMLInputElement>(SpecificPriceMap.priceSymbol);
+
+      if (priceSymbol) {
+        priceSymbol.innerHTML = symbol;
+      }
+
+      // Reduction Amount
+      const reductionTypeSelect = document.querySelector<HTMLSelectElement>(SpecificPriceMap.reductionTypeSelect);
+
+      if (reductionTypeSelect && reductionTypeSelect.options[reductionTypeSelect.selectedIndex].value === 'amount') {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/specific-price/form/index.ts]:
```suggestion
      if (reductionTypeSelect?.options[reductionTypeSelect.selectedIndex].value === 'amount') {
```

**Review by NeOMakinG — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Progi1984 

I have checked this PR. The issue is not fixed.

- Edit or add a new product V2 (The same with product V1)
- Configure more than one currency in the shop,
- Add a new specific price OR Edit a new specific price
==> The symbol still the default currency of shop and not updated when change the new currency.

Example : 
When add a specific price
image
After save
image

https://user-images.githubusercontent.com/92912932/162946819-1fd0f039-9c17-4c91-9e72-1a390d54b3cf.mp4

Could you please check ?

Thanks!

**Comment by Progi1984** [comment]
@HanaRebaiQA Have you rebuild assets ?

**Review by PierreRambaud — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_prices_listing.feature [hunk 18]
```diff
@@ -67,7 +67,7 @@ Feature: List specific prices for product in Back Office (BO)
...
-      | price2       |                         | amount         | 12.56           | true         | 45.78       | 1             | test_shop | USD      | United States | Visitor | John DOE | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
-      | price3       | Size - S, Color - White | percentage     | 30              | false        | 0           | 1             |           |          |               |         |          | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
+      | id reference | combination             | reduction type | reduction value | includes tax | fixed price | from quantity | shop      | currency | currencyISOCode | country       | group   | customer | from                | to                  |
+      | price1       |                         | amount         | 111.50          | true         | 400         | 1             |           |          |                 |               |         |          | 0000-00-00 00:00:00 | 0000-00-00 00:00:00 |
```
Comment (matks) [inline tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_prices_listing.feature:71]: Ha 😄 this starts to become a bit long to scroll 😅

File: src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php [hunk 19]
```diff
@@ -27,12 +27,13 @@
...
 
 use PrestaShop\PrestaShop\Adapter\Currency\CurrencyDataProvider;
+use PrestaShop\PrestaShop\Core\Form\FormChoiceAttributeProviderInterface;
 use PrestaShop\PrestaShop\Core\Form\FormChoiceProviderInterface;
 
 /**
  * Class CurrencyByIdChoiceProvider provides currency choices with ID values.
  */
-final class CurrencyByIdChoiceProvider implements FormChoiceProviderInterface
+final class CurrencyByIdChoiceProvider implements FormChoiceProviderInterface, FormChoiceAttributeProviderInterface
```
Comment (matks) [inline src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php:36]: I guess adding an interface on a final class is not a Breaking Change

**Review by matks — DISMISSED** [review]

File: src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php (hunk 19 above)
Comment (Progi1984) [reply src/Core/Form/ChoiceProvider/CurrencyByIdChoiceProvider.php:36]: Modifying a final class is not a BC because it's not extendable.

File: tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_prices_listing.feature (hunk 18 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Product/SpecificPrice/specific_prices_listing.feature:71]: :rofl:

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Progi1984 

I have checked again this PR. The issue is not fixed when add OR edit a specific price.
image
image

https://user-images.githubusercontent.com/92912932/163784008-264f1026-a0d0-4699-bbfb-e42daacd762b.mp4

Could you please check again ?

Thanks!

**Comment by Progi1984** [comment]
@PierreRambaud & @matks I have fixed feedbacks from @HanaRebaiQA

File: admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/catalog-price-rule-form-map.ts [hunk 20]
```diff
@@ -30,6 +30,10 @@ export default {
   // mapping for price-field-availability-handler
   initialPrice: '#catalog_price_rule_leave_initial_price',
   price: '#catalog_price_rule_price',
+  currencyId: '#catalog_price_rule_id_currency',
+  reductionTypeSelect: '#catalog_price_rule_reduction_type',
+  reductionTypeAmountSymbol: '.js-reduction-row .input-group .input-group-append .input-group-text, '
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/catalog-price-rule/form/catalog-price-rule-form-map.ts:35]: Oh that one is tricky 😅

File: admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts [hunk 21]
```diff
@@ -24,9 +24,14 @@
  */
 
 export default {
+  currencyId: '#specific_price_currency_id',
   customerSearchContainer: '#specific_price_customer',
   priceInput: '#specific_price_fixed_price',
+  priceSymbol: '.js-fixed_price-row .input-group.money-type .input-group-append .input-group-text, '
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts:30]: I guess you need to target both prepend and append classes because the MoneyType form field changes its display based on the language? Maybe it could be simplified by updating the form theme and adding a single class that would be common to both use cases? (just a suggestion though)

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController.php [hunk 22]
```diff
@@ -182,8 +182,15 @@ private function formatSpecificPricesList(SpecificPriceList $specificPriceListFo
                 'country' => $specificPrice->getCountryName() ?? $this->trans('All countries', 'Admin.Global'),
                 'group' => $specificPrice->getGroupName() ?? $this->trans('All groups', 'Admin.Global'),
                 'customer' => $specificPrice->getCustomerName() ?? $this->trans('All customers', 'Admin.Global'),
-                'price' => $this->formatPrice($specificPrice->getFixedPrice()),
-                'impact' => $this->formatImpact($specificPrice->getReductionType(), $specificPrice->getReductionValue()),
+                'price' => $this->formatPrice(
+                    $specificPrice->getFixedPrice(),
+                    $specificPrice->getCurrencyISOCode() ?: $this->getContextCurrencyIso()
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController.php:187]: Oh tricky as well! This originally "simple" PR keeps getting harder and harder 😅

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984 

I have a few questions but it's for my curiosity Great work!

File: admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts (hunk 21 above)
Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts:30]: I think it can be done in the future. Isn't it ?

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController.php (hunk 22 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController.php:187]: I confirm. But isn't it our daily job ?

**Review by NeOMakinG — APPROVED** [review]

File: admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts (hunk 21 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/specific-price/specific-price-map.ts:30]: Yeah absolutely

**Review by HanaRebaiQA — APPROVED** [review]
Hello @Progi1984 

Thanks for the fixed issues.

I have testes again this PR. Here my tested cases : 
-Check with different product types : OK
-Check when add and edit a specific prices : OK
-Check with different currencies (When add pack localization, when create a custom currecy) : OK
-Check with different languages : OK
-Check with multistore : OK
-Check when add product with API : OK
-Check when import products : OK

image

So, it's QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @HanaRebaiQA
