### PR TITLE
Fix wrong tab selected after changing a product combination on the FO

### LINKED ISSUE #24800: Wrong tab showed after changing combination on product page in the FO
#### Describe the bug

When you change combination, add product to cart etc. tabs below are not properly reloaded

#### Expected behavior

Reload tabs properly

#### Steps to Reproduce

1. Go to the FO
2. Go to Product with combinations page
3. Switch to second tab, probably "Product details"
4. Change combination
5. See error, "Product details" is now with product description

Unfortunately this is regression as we don't have such an issue on 1.7.7.x

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.8 and develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In #23056, `js-*` selectors have been added but some of them were not updated when the active state of a tab change. This PR fixes it.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24800
| How to test?      | Please see #24800
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24849)

### CODE REVIEW

File: themes/classic/_dev/js/product.js [hunk 1]
```diff
@@ -158,4 +159,18 @@ $(document).ready(() => {
       }
     });
   }
+
+  function addJsProductTabActiveSelector() {
+    const nav = $(prestashop.themeSelectors.product.tabs);
+    nav.on('show.bs.tab', (e) => {
+      const target = $(e.target);
+      target.addClass('js-product-nav-active');
+      $(target.attr('href')).addClass('js-product-tab-active');
```
Comment (kpodemski) [inline themes/classic/_dev/js/product.js]: maybe a bit overkill but probably should go to the selectors map 🤷

Comment (NeOMakinG) [reply themes/classic/_dev/js/product.js]: @Progi1984 get out of his body please !

File: themes/classic/_dev/js/selectors.js [hunk 2]
```diff
@@ -54,7 +56,7 @@ prestashop.themeSelectors = {
     returnForm: '#order-return-form, .js-order-return-form',
   },
   arrowDown: '.arrow-down, .js-arrow-down',
-  arrowUp: '.arrow-up, .js-arrow-down',
+  arrowUp: '.arrow-up, .js-arrow-up',
```
Comment (kpodemski) [inline themes/classic/_dev/js/selectors.js:59]: nice catch

**Review by kpodemski — APPROVED** [review]

File: themes/classic/_dev/js/selectors.js [hunk 3]
```diff
@@ -53,7 +56,7 @@ prestashop.themeSelectors = {
...
```
Comment (atomiix) [inline themes/classic/_dev/js/selectors.js:59]: Not in the scope of this PR but I noticed it so I fixed it 😅

**Review by Progi1984 — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @atomiix !

**Comment by Progi1984** [comment]
Thanks @atomiix & @florine2623
