### PR TITLE
Don't search all word for customer search when we create an order

### LINKED ISSUE #22652: BO ORDER CREATE - Customer search field shows results for all words
#### Describe the bug

When you go to create a new order from BO and you search for customer, it shows results for all words you enter.
You search for John Doe and instead of one or few John Does, it finds all Johns and all Doe. There are billion of results... 

#### Expected behavior

It should search only for the phrase as a whole.

#### Steps to reproduce

1. **BO**>**SELL**>**Customer**
2. Create two customers: "John Smith" and "Sam Doe"
3. **BO**>**SELL**>**Orders**
4. Create Order
5. make a search with "John Doe"
6. See error > there's 3 customers diplayed

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When you go to create a new order from BO and you search for customer, it shows results for all words you enter. You search for John Doe and instead of one or few John Does, it finds all Johns and all Do
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/22652
| How to test?      | Make a search with OR and Without OR 
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

Capture d’écran de 2021-10-05 08-49-22

Capture d’écran de 2022-01-24 10-56-31

This PR replace : https://github.com/PrestaShop/PrestaShop/pull/26109

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26109)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
I like the idea of allowing multiple searches by using OR and not relying on it else. It's not ambiguous, it's straightforward 👍

**Comment by mparvazi** [comment]
@okom3pom 

Can we use something like this:
Screenshot 2022-01-26 at 13-09-48 Product • develop

Or as like as Google:
If there is no results for `"Thomas Doe"` then try to search `"Thomas" OR "Doe"` .
```
Showing results for "Thomas" OR "Doe"
Search instead for "Thomas Doe"
```

Btw `SearchController` currently is not smart, and should be add some hacks to work as like as search engines.

- Use quotes: `"John Doe"`
- Use a hyphen to exclude words: `John -Doe`
- Use the asterisk wildcard `John * Doe`
- Search for multiple words at once `John OR Doe`

`john -doe`

Screenshot 2022-01-26 at 13-39-18 Product • develop

`john +doe`

Screenshot 2022-01-26 at 13-39-49 Product • develop

`john phone:641-451-2923`

Screenshot 2022-01-26 at 13-45-07 Product • develop

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php [hunk 1]
```diff
@@ -441,7 +441,7 @@ public function setRequiredFieldsAction(Request $request)
     public function searchAction(Request $request)
     {
         $query = $request->query->get('customer_search');
-        $phrases = explode(' ', $query);
+        $phrases = explode('OR', $query);
```
Comment (saulaski) [inline src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: @okom3pom Thank you for this great proposal.

Perhaps the implementation requires further testing to avoid unexpected results:
1. The OR separator might need space characters around `' OR '`, in order to handle some tricky cases like `"SPECTOR Warren"`.
2. Beyond this first splitting, if I'm not wrong, `Customer::searchByName()` will also split each individual search query with space separator: https://github.com/PrestaShop/PrestaShop/blob/cf54f94ec6440e573a1f7b1549ee29ce31e619c3/classes/Customer.php#L875

**Review by saulaski — CHANGES_REQUESTED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php (hunk 1 above)
Comment (ghost) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: @saulaski 
 _The OR separator might need space characters around ' OR ', in order to handle some tricky cases like "SPECTOR Warren"._
 
 Nice catch I didn't think of that, for the second point i need to check

Comment (ghost) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: For the second point is for this.

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Customer/QueryHandler/SearchCustomersHandler.php#L83

`$search_items = explode(' ', $query);` it's for search **Thomas Roux** in firstname and lastname

Comment (saulaski) [reply src/PrestaShopBundle/Controller/Admin/Sell/Customer/CustomerController.php]: @okom3pom Thank you for this quick validation

**Comment by ghost** [comment]
@mparvazi 

I agree with you.

However this search is to find a customer to create an order I am not sure of the relevance of all these options.

Currently the PR fixes the issue, it should open an improvement issue

**Comment by mparvazi** [comment]
> @mparvazi
> 
> I agree with you.
> 
> However this search is to find a customer to create an order I am not sure of the relevance of all these options.
> 
> Currently the PR fixes the issue, it should open an improvement issue

Yes, you right!

I think I should create new issue for advanced search options.

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/customer.html.twig [hunk 2]
```diff
@@ -37,6 +37,7 @@
         >
         <small class="form-text">
           {{ 'Search for an existing customer by typing the first letters of his/her name.'|trans({}, 'Admin.Orderscustomers.Help') }}
+          {{ 'You can use " OR " for a multiple search.'|trans({}, 'Admin.Orderscustomers.Help') }}
```
Comment (Julievrz) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/customer.html.twig]:
```suggestion
          {{ 'Use OR to broaden your search'|trans({}, 'Admin.Orderscustomers.Help') }}
```

If I understand well, if a user enters "John Doe", only the results containing both John AND Doe will appear. But the user can use OR if he/she wants to display results containing either John or Doe for example, John Sims and Nicolas Doe?

**Comment by ghost** [comment]
@Julievrz I've updated the wording

Regards

**Review by saulaski — APPROVED** [review]

**Comment by Julievrz** [comment]
> @Julievrz I've updated the wording
> 
> Regards

Thanks, it's wording ✔️

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
@okom3pom is on fire lately 🔥 

LGTM

**Review by hibatallahAouadni — APPROVED** [review]
Hello @okom3pom 

Thanks for your PR :clap: 
LGTM, QA :heavy_check_mark: 

https://user-images.githubusercontent.com/23308427/152962906-d2b5a806-b433-48d1-bffe-fbcb0bd3cf15.mp4

Using one sentence, two sentence with OR, two sentence without OR, all works :rocket: 

image

image

image

Thanks!

**Comment by Progi1984** [comment]
Thanks @okom3pom & @hibatallahAouadni
