### PR TITLE
Refresh documents tab when adding product in order view page

### LINKED ISSUE #17977: New invoice not displayed in documents tab before reloading the page
#### Describe the bug

If you add a new product and choose to create a new invoice, the invoice is not displayed in documents tab before reloading the page

#### Expected behavior

The invoice should be displayed in the documents tab without reloading the page

#### Steps to Reproduce

1. Go to BO > orders > orders > View order
2. Click on add a product
3. Select a product and select "Create a new invoice"
4. Click on add
5. The new invoice isn't displayed in the documents tab, you have to reload the page to see it

#### Additional information

https://drive.google.com/file/d/1S4yKh_4l7ddrWvyHmBIonMx4_kyydWRP/view?usp=sharing

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When adding a product and choosing to create a new invoice, the "Documents" tab wasn't updated with the new invoice. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17977
| How to test?  | See below

## How to test

Please rebuild assets before testing.

1. Go to BO > orders > orders > View order<br>2. Click on add a product<br>3. Select a product and select "Create a new invoice"<br>4. Click on add<br>5. The new invoice should be displayed in the documents tab, the number of documents should be updated as well.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18196)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    this.invoiceNoteManager = new InvoiceNoteManager();
+  }
+
+  refresh(orderId) {
+    $.ajax(this.router.generate('admin_orders_get_documents', {orderId}))
+      .then((response) => {
+        $(OrderViewPageMap.orderDocumentsTabCount).text(response.total);
+        $(OrderViewPageMap.orderDocumentsTabContentTable).html(response.html);
+        this.invoiceNoteManager.setupListeners();
+      });
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js]: No error handling necessary?

Comment (atomiix) [reply admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js]: @NeOMakinG I don't think so, there is no "action", it's only fetching data to refresh a part of the page. And even if it fails, if you refresh the page you'll be up-to-date. But maybe I'm wrong. WDYT?

**Comment by matthieu-rolland** [comment]
is it normal that you build so many assets ? :D

**Review by matthieu-rolland — DISMISSED** [review]
LGTM for me, even though it would nice to build only necessary assets (I don't block the PR for this)

**Review by PierreRambaud — DISMISSED** [review]
Approuve event if there are some eslint problems. Will be fixed when merging to develop branch

File: admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js (hunk 1 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js]: But what tell you to refresh the page if you see nothing telling you ? If thats the normal behavior/workflow, let's doing this, or maybe just create an alert, @PrestaShop/prestashop-core-developers what's the normal workflow for error handling on JS side of PS?

Comment (atomiix) [reply admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js]: @NeOMakinG If you don't see your new invoice in the document tab, you'll may think to reload the page?
Anyway, if we decide to handle errors here, we should add error handling in the [price refresher](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js#L38) as well

Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/pages/order/view/order-documents-refresher.js]: That would be a bug tbh, even if peoples refresh, they'll want to create an issue to fix that

Yes of course, we need to handle errors everywhere :/

But as everyone looks to approve the PR, maybe that's something to do in another issue/pr

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @atomiix the PR correctly create and add the new invoice without refreshing the page but I have noticed that if we create a new invoice for only one product and next we delete that product from the cart the new invoice still exist and is empty .

capture d'écran_9

Is that the correct and desired behaviour ? Or should I have to create a new issue for this ? What do you think @PrestaShop/prestashop-product-team

**Comment by LouiseBonnard** [comment]
✅ **UPDATE** 

@SD1982, we keep it as is for now so consider it wanted. :-)

---

I've tested different scenarios and it happens that when an item is deleted from an order, its product line is removed from the invoice. So here is my recommendation:

If the payment has not been processed yet and the user deletes the only product(s) attached to an invoice = **invoice is deleted** from the _Documents_ tab

💡 It might be nice to add a notification (a kind of form, see example below) to remind the user that, in this case, this action will delete the invoice as well. Something like _Deleting this product will also delete the related invoice. Are you sure you want to continue?_ in _Admin.Orderscustomers.Notification_.

Capture d’écran 2020-03-25 à 14 49 34

---

It raises another issue regarding the invoice: what should happen when the payment is validated and the user deletes the product(s) attached to an invoice?

Either the **invoice remains available** in the _Documents_ tab and still mentions the deleted products (and highlights them as deleted?), or **new invoice is generated** in the _Documents_ tab? In comparison, when a discount is applied to an already paid order, the invoice is updated and the discount is mentioned.

Anyway, nothing special to do for this pull request but, FYI, I'm in touch with the legal team about the last point. Invoices are supposed to be inalterable in France & EU so we must be sure of the behavior - display or not the deleted product line in the invoice, especially for paid orders. According to what they'll say, I will open an issue to specify it for a future version.

**Review by matks — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 2]
```diff
@@ -686,6 +686,24 @@ public function getInvoicesAction(int $orderId)
...
+     * @param int $orderId
+     */
+    public function getDocumentsAction(int $orderId)
+    {
+        /** @var OrderForViewing $orderForViewing */
+        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
+
+        return $this->json([
+            'total' => count($orderForViewing->getDocuments()->getDocuments()),
+            'html' => $this->render('@PrestaShop/Admin/Sell/Order/Order/Blocks/View/documents.html.twig', [
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:705]: Is it not possible to ouput json rather than html ?

Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:705]: You mean output `orderForViewing` as raw JSON data and handle the rendering on javascript side ?
This would be a very big change in the scope of the PR

Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:705]: Affirmative. We need to do it before beta, because we can't change it after this release.

Comment (matks) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:705]: I'm against it, just like I said for https://github.com/PrestaShop/PrestaShop/pull/18204/files#r402206127 😉but I see you saw it too
I started the discussion on slack 😄

Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:705]: After discussion, it's :ok_hand: for me.

**Review by Progi1984 — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix ! We need some review before testing.

Thanks :)

**Review by Progi1984 — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
@atomiix there are some conflict that needs to be fixed before review 😃

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SD1982** [comment]
Hello @atomiix The PR correctly add the second invoice and display it without having to refresh the page but I noticed a few things:

1 - If we add a product to an order that does not yet have an invoice 2 buttons "generate an invoice" are visible and if we delete the product that we just added the two buttons are always visible and the amount of the order is incorrect
https://drive.google.com/file/d/1YC79ZGj2knvfbreamHeFMWH3sp1LE3m-/view?usp=sharing

2 - If we add a new product and generate a new invoice the new invoice is correctly generated but if we delete the previously added product the new generated invoice still exist and is empty 
https://drive.google.com/file/d/1kUC60DUKp6FgSxNHt9k0JrPL_UZOJZMb/view?usp=sharing

3 - If we add a new product with a new invoice if we try to edit any product of the order => in the invoice column => all the invoice are displayed 
https://drive.google.com/file/d/1KVnoOGhz_N23rWdTc_mdv8_HKFoHcwf6/view?usp=sharing
but this behaviour seems to disappear if some payment have been made
capture d'écran_27

4 - If we don't have the problem n°3 in the product edit we have the possibility to reassign the product to another invoice but it has no effect ( this behaviour is also present without the PR )
https://drive.google.com/file/d/1AzFtIUXdFJOUMtIHM9m5fxEHj7LJ7vfV/view?usp=sharing

**Comment by atomiix** [comment]
Hi @SD1982,

I'll fix the first issue.

For the second one,  except if i'm missing something, you already reported it and we decided to [let it like that](https://github.com/PrestaShop/PrestaShop/pull/18196#issuecomment-603866785)

And finally, 3rd & 4th issues seem to be out of scope to me as it's not related to the document tab not being refresh after a product has been added. Can you open new issues for them?

Thanks!  🙂

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @atomiix 

For the number 2 yes i have already reported it ( I hadn't seen @LouiseBonnard  update )
and as she said 

> we keep it as is for now so consider it wanted.

But even if we don't delete the invoice when we delete the only product related to this invoice the total amount of the order must be correctly recalculated. 

For N°3 it seems that it's related to your PR because this behaviour is not reproduced if the PR is not applied 

And for N°4 I agree it is out of scope because as I said it was already present before the application of PR and i will create the issue :+1:

**Comment by atomiix** [comment]
@SD1982 I'm pretty sure that the total amount is not correctly updated because it's an order created by the fixtures. If you create an order manually it should work.

For N°3, I can reproduce it without my PR.  Are you up to date on 1.7.7.x when trying to reproduce it without the PR?

N°4 : 👌

**Comment by SD1982** [comment]
@atomiix When the reviews are done I will retest all this in detail :+1:

**Review by jolelievre — DISMISSED** [review]

**Comment by SD1982** [comment]
Hello @atomiix as you said i also can reproduce the error n°3 without applying your PR and i have also find some new issues while testing your PR but not in the scope and not related with your PR. Your PR correctly fix #17977 ! Thanks @atomiix !

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @atomiix
