### PR TITLE
No unit of value for the txt files attached to a product

### LINKED ISSUE #22123: No unit of value for the txt files attached to a product
#### Describe the bug

The file attached to a product has no unit of value

#### Expected behavior

The file attached to a product has a unit of value

#### Steps to Reproduce

1. Go to BO > catalog > Products 
2. Click on a product > go to option > Attached files
3. Attach a **txt** file `(*.txt)` to the product
4. Preview product
5. Click on attachments
6. See error

**Screenshots**

image

#### Additional information

* PrestaShop version: 1.7.7, develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | The file attached to a product has no unit of value.
| Type?         |  improvement 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/22123
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/22123 by @RomainBocheux 

## Before

Capture du 2020-11-28 23-57-43

## After

image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22152)

### CODE REVIEW

File: classes/Tools.php [hunk 1]
```diff
@@ -4127,9 +4127,10 @@ public static function formatBytes($size, $precision = 2)
             return '0';
         }
         $base = log($size) / log(1024);
+        $baseUnity = Context::getContext()->getTranslator()->trans('Bytes', [], 'Shop.Theme.Catalog');
         $suffixes = ['', 'k', 'M', 'G', 'T'];
```
Comment (PierreRambaud) [inline classes/Tools.php]:
```suggestion
        $suffixes = ['o', 'ko', 'Mo', 'Go', 'To'];
```
Should be enough

File: classes/Tools.php [hunk 2]
```diff
@@ -4127,9 +4127,10 @@ public static function formatBytes($size, $precision = 2)
...
 
-        return round(1024 ** ($base - floor($base)), $precision) . $suffixes[floor($base)];
+        return round(1024 ** ($base - floor($base)), $precision) . $suffixes[floor($base)] . $baseUnity;
```
Comment (PierreRambaud) [inline classes/Tools.php]:
```suggestion
        return round(1024 ** ($base - floor($base)), $precision) . Context::getContext()->getTranslator()->trans($suffixes[floor($base)], [], 'Shop.Theme.Catalog');
```

File: classes/Tools.php (hunk 1 above)
Comment (PululuK) [reply classes/Tools.php]: @PierreRambaud  why ?

Comment (PierreRambaud) [reply classes/Tools.php]: Because it's not needed to add a translation for a unit.
kBytes is not the right way to write it :sweat_smile: it's `KByte(s)`, imho the short usage is the common one. People are often talking about ko/Mo than KBytes/MBytes

Comment (PululuK) [reply classes/Tools.php]: But `Mo = Mega octets`, its french right ?

Comment (PierreRambaud) [reply classes/Tools.php]: afaik no, https://en.wikipedia.org/wiki/Octet_(computing) but it's more used in France, or Canada because byte is ambiguous (1 byte/1 octet = 8 bits) :sweat_smile: 


```suggestion
        $suffixes = ['Byte(s)', 'KByte(s)', 'MBytes(s)', 'GByte(s)', 'TByte(s)'];
```
wdyt about this one?

Comment (PululuK) [reply classes/Tools.php]: @PierreRambaud  That's fine with me, but I think it should still be translatable.

Comment (PierreRambaud) [reply classes/Tools.php]: I update my second command to be sure it's correctly translated

Comment (PululuK) [reply classes/Tools.php]: Done ! Thanks @PierreRambaud

**Comment by Julievrz** [comment]
Hi @PululuK, just a quick wording question: isn't it more common to write "B,MB,KB,TB, ... ?

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PululuK** [comment]
> Hi @PululuK, just a quick wording question: isn't it more common to write "B,MB,KB,TB, ... ?

Hi @Julievrz 
Sorry for the delay
It is ok to me too ... What do you prefer ?

**Comment by Julievrz** [comment]
> > Hi @PululuK, just a quick wording question: isn't it more common to write "B,MB,KB,TB, ... ?
> 
> Hi @Julievrz
> Sorry for the delay
> It is ok to me too ... What do you prefer ?

After a little research, it looks like it is more common for "bytes" to be spelled out but "MB", "KB", "GB", "TB" can be written in their contracted form. I am not a specialist of units though, so if anyone disagrees please feel free to tell me. 😊

**Comment by marionf** [comment]
Hello @PululuK 

Following the feedback of @Julievrz could you replace "bytes", "KByte" ... by "MB", "KB", "GB", "TB" ?

**Comment by PululuK** [comment]
> Hello @PululuK
> 
> Following the feedback of @Julievrz could you replace "bytes", "KByte" ... by "MB", "KB", "GB", "TB" ?

Hi @marionf @Julievrz 

- KByte(s) => KB
- MByte(s) => MB
- GByte(s) => GB
- TByte(s) => TB
- Byte(s) =>  ??

**Comment by marionf** [comment]
I think we can keep Byte(s) as there is no abbreviation for it
Is it ok for you @Julievrz ?

**Comment by atomiix** [comment]
@marionf @Julievrz you can use `B` for byte! ([Byte on wikipedia, last paragraph](https://en.wikipedia.org/wiki/Byte))

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Julievrz** [comment]
> @marionf @Julievrz you can use `B` for byte! ([Byte on wikipedia, last paragraph](https://en.wikipedia.org/wiki/Byte))

Thanks for your feedback @atomiix!

**Comment by aDamelincourt** [comment]
Thanks @PululuK 
✔️  check by QA
It's OK for several files types(including txt)
image

**Comment by Progi1984** [comment]
Thanks @PululuK & @aDamelincourt
