### PR TITLE
Fix issue with null values on stores from import

### LINKED ISSUE #34974: Store contact import can insert bad data in DB
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When Importing Store Contacts with the import tool, the fields hours is not required. However, if this field is not included in the csv file, then the db get a bad value stored and when trying to edit the store contact you get the error 
"count(): Argument #1 ($value) must be of type Countable|array, null given"

### Expected behavior

When importing store contacts I expect to be able to edit them.

### Steps to reproduce

1. Go to Import feature and select to import store contacts
2. upload the attached file and match the fields
[storecontacts.csv](https://github.com/PrestaShop/PrestaShop/files/13831504/storecontacts.csv)
3. complete the import-
4. Go to Store Contacts, you should now have a new store contact named Test
5. Edit the store contact Test

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Prestaworks AB

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | When importing store contacts and a store is missing opening hours, that store will not be possible to access from the BO due to null values from the DB not being allowed in conversion.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| UI tests     | https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/18500948427
| How to test?      | Follow instructions in issue.
| Fixed issue or discussion?     | Fixes #34974
| Sponsor company   | Prestaworks AB

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

File: controllers/admin/AdminStoresController.php [hunk 1]
```diff
@@ -608,6 +608,9 @@ public function updateOptionPsShopStateId($value)
      */
     protected function adaptHoursFormat(array $value)
```
Comment (kpodemski) [inline controllers/admin/AdminStoresController.php]:
```suggestion
    protected function adaptHoursFormat(?array $value)
```

**Comment by kpodemski** [comment]
@Prestaworks 

have you checked whether the input to this method is `null` or an empty array?

if it's `null` then my change is legit, if it's an empty array then the check should be different

or, the check whether there's null should be earlier somewhere in the import

**Comment by Prestaworks** [comment]
> @Prestaworks
> 
> have you checked whether the input to this method is `null` or an empty array?
> 
> if it's `null` then my change is legit, if it's an empty array then the check should be different
> 
> or, the check whether there's null should be earlier somewhere in the import

The DB has a empty string, 
the value sent is null (In PS 8 where I fixed this, there is no type array so it accepts any input for ps 9 your change is good).

**Review by kpodemski — APPROVED** [review]

**Review by Codencode — APPROVED** [review]

**Review by SiraDIOP — COMMENTED** [review]
Hello @Prestaworks,

Thanks for your PR, 
I tested it and i have some problem (see video):
I tried to import the CSV file ,
[storecontacts.csv](https://github.com/user-attachments/files/22950981/storecontacts.csv)
 but I got an error during import, and the imported contact is not in Contacts.

https://github.com/user-attachments/assets/f78b333b-ed6e-4474-866e-f336d4fda490

Did i miss something??

Thanks

**Comment by Prestaworks** [comment]
> c

Seems to be failing due to country missing. You can change "Sweden" in the file to a country that is active in your shop.

**Review by SiraDIOP — COMMENTED** [review]
Hello @Prestaworks ,

I change the country but i have an error when i do the import 
Capture d’écran 2025-10-16 à 16 18 03

Did i miss something??

Thanks

**Comment by Prestaworks** [comment]
> Hello @Prestaworks ,
> 
> I change the country but i have an error when i do the import Capture d’écran 2025-10-16 à 16 18 03
> 
> Did i miss something??
> 
> Thanks

You seem to have uploaded the wrong file? or maybe broken it somehow?

**Review by SiraDIOP — COMMENTED** [review]
@Prestaworks  No, I used the file you provided us. Is it possible to provide us with another file with the country change, please?

Thanks

**Comment by Prestaworks** [comment]
My guess is that you opened the file and then saved it as some other format than CSV.

You can tell me what Country you want and I can change it for you.

**Review by SiraDIOP — COMMENTED** [review]
@Prestaworks, United states for example

Thanks

**Comment by Prestaworks** [comment]
here we go
[storecontacts_us.csv](https://github.com/user-attachments/files/23020093/storecontacts_us.csv)

**Comment by SiraDIOP** [comment]
Hello @Prestaworks 

Thank you, that's fine with me. I tested it and it works.


https://github.com/user-attachments/assets/93300fe9-7146-468f-9dac-cf9957d5b9c5


Thank you very much for your help.

**Review by SiraDIOP — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you @Prestaworks !
