### PR TITLE
Fix parameters list in product lookup

### LINKED ISSUE #13421: Can't create a pack
**Describe the bug**
Can't create a pack

**To Reproduce**
1. Go to Catalog > Products > New product
2. Select pack of product
3. Search an existing product
4. Nothing is found

**Screenshots**
capture d'écran_1399

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | When replacing a method call, the parameter list was different but wasn't updated
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | Fixes #13421
| How to test?  | When creating a pack, looking for modules works again.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13431)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

File: src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php [hunk 1]
```diff
@@ -143,7 +143,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
             'required' => true,
         ])
             ->add('inputPackItems', TypeaheadProductPackCollectionType::class, [
-                'remote_url' => $this->context->getLegacyAdminLink('AdminProducts', true, [], ['ajax' => 1, 'action' => 'productsList', 'forceJson' => 1, 'excludeVirtuals' => 1, 'limit' => 20]) . '&q=%QUERY',
+                'remote_url' => $this->context->getLegacyAdminLink('AdminProducts', true, ['ajax' => 1, 'action' => 'productsList', 'forceJson' => 1, 'excludeVirtuals' => 1, 'limit' => 20]) . '&q=%QUERY',
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:146]: Do you know why `'&q=%QUERY'` is not in query parameters?

Comment (Quetzacoalt91) [reply src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php:146]: Because it would be sanitized, preventing the existing js to replace the placeholder with an actual parameter
