### PR TITLE
Fix displayAdminProductsExtra hook content display in V1.7.5.0 beta

### LINKED ISSUE #11582: DisplayAdminProductsExtra hook form not display in product edit module page for PS1.7.5.0 beta
**Describe the bug**
DisplayAdminProductsExtra hook return form not display in catalog product edit module tag configure button click

**To Reproduce**
1. Create a module which use 'DisplayAdminProductsExtra' hook and return a form
2. Go to Catalog -> Products, and edit a product
3. Click on 'Modules' tab and then click on Module 'Configure' button
4. Form not display

**Screenshots**
download 15

**Fixed**
Change this line:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Twig/HookExtension.php#L137

From: 
```
- 'content' => array_values($hookRender)[0],
+ 'content' => $hookRender,
```

**Testing**
This change works if multiple module use this hook.

**Additionnal information**
PrestaShop version: 1.7.5.0 beta
PHP version: 7

### PR DESCRIPTION
**Pull request by dheerajwebkul**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | displayAdminProductsExtra form content not display in catalog product edit module page
| Type?         | bug fix 
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11582
| How to test?  | If we use DisplayAdminProductsExtra hook and return a form content it will display in catalog -> product Module tab 'Configure' button click

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11584)

### CODE REVIEW

File: src/PrestaShopBundle/Twig/HookExtension.php [hunk 1]
```diff
@@ -134,7 +134,7 @@ public function renderHooksArray($hookName, $hookParameters = array())
             $render[] = [
                 'id' => $module,
                 'name' => $this->moduleDataProvider->getModuleName($module),
-                'content' => array_values($hookRender)[0],
+                'content' => $hookRender,
```
Comment (mickaelandrieu) [inline src/PrestaShopBundle/Twig/HookExtension.php:137]: it will break another bug fixed here => https://github.com/PrestaShop/PrestaShop/pull/10038

Revert some update introduced is never a good idea, you need to be more precise and/or add a specific test.

Maybe we receive 2 different types here: array or a string depending on the context, but the solution is not to revert or the previous bug will be back: what happens if you try to add data with another hook of display in this page?

What happens if you try to add data with a hook of display in the performance page for instance?

**Review by mickaelandrieu — DISMISSED** [review]
:-1: if not completed by specific tests

**Comment by jolelievre** [comment]
hello @dheerajwebkul 
I looked at your PR and the modifications @mickaelandrieu talked about, I thin you are right for this modification
I will test it a bit further as I noticed some mistakes in related classes as well

**Comment by dheerajwebkul** [comment]
thanks @jolelievre

File: src/PrestaShopBundle/Twig/HookExtension.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Twig/HookExtension.php:137]: hi again @dheerajwebkul 
so after some additional tests we validate your changes, however could you change your PR and target the 1.7.5.x branch instead (the change will be merged back in develop later)
I also would like you to integrate one small fix in https://github.com/PrestaShop/PrestaShop/blob/e078125d0700056c0579f28b0e4c1a0aaf4ab66a/src/PrestaShopBundle/Service/Hook/RenderingHookEvent.php#L84

and change

```php
    $this->currentContent = '';
```

with

```php
    $this->currentContent = [];
```

**Review by jolelievre — CHANGES_REQUESTED** [review]

**Comment by dheerajwebkul** [comment]
Hello @jolelievre 
I just changed the branch but it looks like many changed there.
what I need to do now, Do I need to create new PR on branch V1.7.5.x branch?

Please advice.

**Comment by jolelievre** [comment]
yes because you made your initial changes from the develop branch which already has a lot of changes
Nevermind, you can set back your PR with develop as a target, and I will take care of cherry-picking your modification back in the 1.7.5.x branch

**Comment by dheerajwebkul** [comment]
yes, thanks @jolelievre 

I just backed to the develop branch.

**Comment by jolelievre** [comment]
thank you, also can you please make the little modification on `RenderingHookEvent` ?

**Comment by jolelievre** [comment]
Hello again @dheerajwebkul if you don't mind I created another PR to update the 1.7.5.x branch https://github.com/PrestaShop/PrestaShop/pull/11638

**Comment by dheerajwebkul** [comment]
yes sure @jolelievre, let you know

**Comment by dheerajwebkul** [comment]
Hello @jolelievre 

I have done your changes.

You have created new PR, but I think it's not needed because many discussions involved here to keep us updated and also the issue is very clear to users.
I request you to please continue with this PR.

Thanks,

**Review by jolelievre — DISMISSED** [review]

**Comment by jolelievre** [comment]
Don't worry @dheerajwebkul I didn't intend to close this PR.
I created the other one https://github.com/PrestaShop/PrestaShop/pull/11638 mainly because it was easier to bring these changes in 1.7.5.x branch, and it is easier for our QA team if they need to validate it on the 1.7.5.x version.
But I think we can merge both PR on their respective branch.

**Comment by dheerajwebkul** [comment]
Thanks @jolelievre

**Comment by jolelievre** [comment]
@dheerajwebkul actually I had help from @Quetzacoalt91 to rebase your PR, so now the target is 1.7.5.x which is even better!
I'm gonna close the one I created

**Comment by Quetzacoalt91** [comment]
Hi,

I rebased the PR for the branch `1.7.5.x`. By doing so, we keep @dheerajwebkul contribution and make the future merge on `develop` easier by keeping the same sha1. :)

**Review by jolelievre — APPROVED** [review]
nice job @dheerajwebkul

**Comment by Quetzacoalt91** [comment]
Hi,

I rebased the PR for the branch `1.7.5.x`. By doing so, we keep @dheerajwebkul contribution and make the future merge on `develop` easier by keeping the same sha1. :)

**Comment by Quetzacoalt91** [comment]
Thank you @dheerajwebkul

**Comment by dheerajwebkul** [comment]
Very thanks @jolelievre @Quetzacoalt91 
Great :+1:
