### PR TITLE
Fix delivery time for multishop

### LINKED ISSUE #28998: [Multistore] Combination product - Can't set up a specific delivery time on the Shipping tab with All Shops tab
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you're on multishop, on "all shop" tab, when you want to turn up the specific delivery time with a combination product, it doesn't change anything, it let the default delivery time, you can see it on this video : 

https://user-images.githubusercontent.com/100699445/177803549-a5f13317-bd13-4d8b-9b4a-5b3eb070603b.mp4

### Expected behavior

I expect that I can change the specific delivery time with a combination product with all my shop at the same time 

### Steps to reproduce

1. Go to BO > Shop Parameters > General
2. Scroll down to enable Multistore 
3. Go to Advanced Parameters > Multistore
4. Clic on Add new shop 
5. Set up your new shop 
6. Set up its url
7. Go to Catalog > Product
8. Select a product with combination on it 
9. Go to Combinations tab 
10. Scroll Down, Clic on Allow orders
11. Set up the text of "Label when in stock" and "Label when out of stock (and back order allowed)"
12. Go to Shipping tab 
13. Clic on Specific delivery time to this product
14. set up the text of "Delivery time of in-stock products" and "Delivery time of out-of-stock products with allowed orders"
15. Save the product
16. Reload the current webpage 
17. See the error, Default delivery time is still selected

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | See https://github.com/PrestaShop/PrestaShop/issues/28998 comments.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28998 .
| Related PRs       | [#25913](https://github.com/PrestaShop/PrestaShop/pull/25913) and especially this commit : https://github.com/PrestaShop/PrestaShop/commit/66a6843bfca2d056896858c5b11a91c85eb16b7f
| How to test?      | See below
| Possible impacts? | As I changed `ObjectModel` all basic CRUDs may be impacted. 

:point_up: I observed another problem, when changing shop, page isn't refreshed and shop selection form stay stuck on the top of the page. I should investigate if an issue already created about this problem.

## Steps to reproduce
1. Enable multistore : Configure > Shop Parameters > General > Enable Multistore : Yes 
2. Configure multistore :
   - Advanced Parameters > Multistore > Add a new shop > Shop name / Color > Save
   - Add an url to your new shop > save
3. Go to a product shipping configuration : Sell > Catalog > Products > select a product > Shipping
4. Edit `Delivery Time` and `Shipping fees` fields for one shop > refresh (without cache)
   - You can see that `Delivery Time` is changed for all shops and `Shipping fees` is well updated for given shop.
   - :question: Is it expected behavior as `Delivery Time` isn't a multishop field ? Maybe it can wait product v2 page.
5. Edit `Delivery Time` and `Shipping fees` fields for "all shops" > refresh (without cache)
   - You can see that none of the fields are up to date

### CODE REVIEW

**Review by yanmakouf — APPROVED** [review]
🚀

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php [hunk 1]
```diff
@@ -119,6 +119,8 @@ class AdminModelAdapter extends \PrestaShopBundle\Model\AdminModelAdapter
         'low_stock_alert',
         'available_date',
         'ecotax',
+        'additional_shipping_cost',
```
Comment (jolelievre) [inline src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:122]: It's that simple? 😅
Why wasn't it needed before the fix in ObjectModel?

Comment (jolelievre) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:122]: Is it because partial update didn't really work before so everything was saved and now that it works as expected we realize that some fields had been forgotten in this weird multishop feature? 😛

Comment (MeKeyCool) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:122]: Yep, you can follow my investigations in comments of initial issue.
If I well understood different refactoring stages, 
1. Initially, `multishop_check` fields were given in old templating system by a `products.js` script. This script already didn't manage our two fields.
2. When multishop was designed, this code : https://github.com/PrestaShop/PrestaShop/blob/8.0.x/controllers/admin/AdminProductsController.php#L1883-L1885 was used in controller to get fields to update under multishop context but the function you fixed here : https://github.com/PrestaShop/PrestaShop/commit/66a6843bfca2d056896858c5b11a91c85eb16b7f was bugged and in fact our fields went threw this check and were always updated even if not passed by front-end request.
3. Then the templating system has been updated and the adapter class was created. The developer in charge probably used elements he found in script.
4. You fixed the issue of the bugged function and then revealed the initial bug ^^'

1 week of investigations xD

Comment (jolelievre) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php:122]: Haha nice speleology work 😅

**Review by jolelievre — APPROVED** [review]
Thanks @MeKeyCool

**Review by atomiix — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
Hello @MeKeyCool,

Thank you for this PR.

Tested on 8.0.x with PHP 7.3 version. 

The delivery time is correctly saved on all stores. See my screenrecord:

https://user-images.githubusercontent.com/2854834/187950539-436e7e8c-2aa7-41f1-bfd5-35c64dd46405.mp4

QA approved ✅ 

Thank you
