### PR TITLE
Fixed swagger property filter system for mapped properties

### LINKED ISSUE #39827: Endpoint `POST /admin-api/attributes/attribute` : Unusable endpoint
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I request the endpoint with expected data (check ⬇️) : 

Image

The HTTP Code for the response is 500.

I have this output : 
```js
{
  type: 'https://tools.ietf.org/html/rfc2616#section-10',
  title: 'An error occurred',
  status: 500,
  detail: 'Expected argument of type "array", "null" given',
  class: 'Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException',
  trace: [
    {
      namespace: '',
      short_class: '',
      class: '',
      type: '',
      function: '',
      file: '/home/flefevre/projects/prestashop/src/Core/ConstraintValidator/DefaultLanguageValidator.php',
      line: 62,
      args: []
    },
    {
      namespace: 'PrestaShop\\PrestaShop\\Core\\ConstraintValidator',
      short_class: 'DefaultLanguageValidator',
      class: 'PrestaShop\\PrestaShop\\Core\\ConstraintValidator\\DefaultLanguageValidator',
      type: '->',
      function: 'validate',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/RecursiveContextualValidator.php',
      line: 752,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'RecursiveContextualValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator',
      type: '->',
      function: 'validateInGroup',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/RecursiveContextualValidator.php',
      line: 597,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'RecursiveContextualValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator',
      type: '->',
      function: 'validateGenericNode',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/RecursiveContextualValidator.php',
      line: 511,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'RecursiveContextualValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator',
      type: '->',
      function: 'validateClassNode',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/RecursiveContextualValidator.php',
      line: 302,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'RecursiveContextualValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator',
      type: '->',
      function: 'validateObject',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/RecursiveContextualValidator.php',
      line: 136,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'RecursiveContextualValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\RecursiveContextualValidator',
      type: '->',
      function: 'validate',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/RecursiveValidator.php',
      line: 87,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'RecursiveValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\RecursiveValidator',
      type: '->',
      function: 'validate',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/validator/Validator/TraceableValidator.php',
      line: 61,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Validator\\Validator',
      short_class: 'TraceableValidator',
      class: 'Symfony\\Component\\Validator\\Validator\\TraceableValidator',
      type: '->',
      function: 'validate',
      file: '/home/flefevre/projects/prestashop/vendor/api-platform/core/src/Symfony/Validator/Validator.php',
      line: 59,
      args: []
    },
    {
      namespace: 'ApiPlatform\\Symfony\\Validator',
      short_class: 'Validator',
      class: 'ApiPlatform\\Symfony\\Validator\\Validator',
      type: '->',
      function: 'validate',
      file: '/home/flefevre/projects/prestashop/src/PrestaShopBundle/ApiPlatform/Validator/CQRSApiValidator.php',
      line: 63,
      args: []
    },
    {
      namespace: 'PrestaShopBundle\\ApiPlatform\\Validator',
      short_class: 'CQRSApiValidator',
      class: 'PrestaShopBundle\\ApiPlatform\\Validator\\CQRSApiValidator',
      type: '->',
      function: 'validate',
      file: '/home/flefevre/projects/prestashop/src/PrestaShopBundle/ApiPlatform/Normalizer/CQRSApiNormalizer.php',
      line: 92,
      args: []
    },
    {
      namespace: 'PrestaShopBundle\\ApiPlatform\\Normalizer',
      short_class: 'CQRSApiNormalizer',
      class: 'PrestaShopBundle\\ApiPlatform\\Normalizer\\CQRSApiNormalizer',
      type: '->',
      function: 'denormalize',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/serializer/Serializer.php',
      line: 249,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\Serializer',
      short_class: 'Serializer',
      class: 'Symfony\\Component\\Serializer\\Serializer',
      type: '->',
      function: 'denormalize',
      file: '/home/flefevre/projects/prestashop/src/PrestaShopBundle/ApiPlatform/Serializer/CQRSApiSerializer.php',
      line: 112,
      args: []
    },
    {
      namespace: 'PrestaShopBundle\\ApiPlatform\\Serializer',
      short_class: 'CQRSApiSerializer',
      class: 'PrestaShopBundle\\ApiPlatform\\Serializer\\CQRSApiSerializer',
      type: '->',
      function: 'denormalize',
      file: '/home/flefevre/projects/prestashop/src/PrestaShopBundle/ApiPlatform/Serializer/CQRSApiSerializer.php',
      line: 149,
      args: []
    },
    {
      namespace: 'PrestaShopBundle\\ApiPlatform\\Serializer',
      short_class: 'CQRSApiSerializer',
      class: 'PrestaShopBundle\\ApiPlatform\\Serializer\\CQRSApiSerializer',
      type: '->',
      function: 'deserialize',
      file: '/home/flefevre/projects/prestashop/vendor/api-platform/core/src/State/Provider/DeserializeProvider.php',
      line: 93,
      args: []
    },
    {
      namespace: 'ApiPlatform\\State\\Provider',
      short_class: 'DeserializeProvider',
      class: 'ApiPlatform\\State\\Provider\\DeserializeProvider',
      type: '->',
      function: 'provide',
      file: '/home/flefevre/projects/prestashop/vendor/api-platform/core/src/Symfony/Security/State/AccessCheckerProvider.php',
      line: 62,
      args: []
    },
    {
      namespace: 'ApiPlatform\\Symfony\\Security\\State',
      short_class: 'AccessCheckerProvider',
      class: 'ApiPlatform\\Symfony\\Security\\State\\AccessCheckerProvider',
      type: '->',
      function: 'provide',
      file: '/home/flefevre/projects/prestashop/src/PrestaShopBundle/ApiPlatform/Provider/EmptyBodyDeserializerProvider.php',
      line: 61,
      args: []
    },
    {
      namespace: 'PrestaShopBundle\\ApiPlatform\\Provider',
      short_class: 'EmptyBodyDeserializerProvider',
      class: 'PrestaShopBundle\\ApiPlatform\\Provider\\EmptyBodyDeserializerProvider',
      type: '->',
      function: 'provide',
      file: '/home/flefevre/projects/prestashop/vendor/api-platform/core/src/Symfony/EventListener/DeserializeListener.php',
      line: 111,
      args: []
    },
    {
      namespace: 'ApiPlatform\\Symfony\\EventListener',
      short_class: 'DeserializeListener',
      class: 'ApiPlatform\\Symfony\\EventListener\\DeserializeListener',
      type: '->',
      function: 'onKernelRequest',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/event-dispatcher/Debug/WrappedListener.php',
      line: 116,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\EventDispatcher\\Debug',
      short_class: 'WrappedListener',
      class: 'Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener',
      type: '->',
      function: '__invoke',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/event-dispatcher/EventDispatcher.php',
      line: 220,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\EventDispatcher',
      short_class: 'EventDispatcher',
      class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
      type: '->',
      function: 'callListeners',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/event-dispatcher/EventDispatcher.php',
      line: 56,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\EventDispatcher',
      short_class: 'EventDispatcher',
      class: 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
      type: '->',
      function: 'dispatch',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php',
      line: 139,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\EventDispatcher\\Debug',
      short_class: 'TraceableEventDispatcher',
      class: 'Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher',
      type: '->',
      function: 'dispatch',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/http-kernel/HttpKernel.php',
      line: 157,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\HttpKernel',
      short_class: 'HttpKernel',
      class: 'Symfony\\Component\\HttpKernel\\HttpKernel',
      type: '->',
      function: 'handleRaw',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/http-kernel/HttpKernel.php',
      line: 76,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\HttpKernel',
      short_class: 'HttpKernel',
      class: 'Symfony\\Component\\HttpKernel\\HttpKernel',
      type: '->',
      function: 'handle',
      file: '/home/flefevre/projects/prestashop/vendor/symfony/http-kernel/Kernel.php',
      line: 197,
      args: []
    },
    {
      namespace: 'Symfony\\Component\\HttpKernel',
      short_class: 'Kernel',
      class: 'Symfony\\Component\\HttpKernel\\Kernel',
      type: '->',
      function: 'handle',
      file: '/home/flefevre/projects/prestashop/admin-api/index.php',
      line: 75,
      args: []
    }
  ]
}
```

### Expected behavior

The HTTP Code for the response is 201.

Image

### Steps to reproduce

1. Fetch an access token (scope `attribute_write`)
2. Request an endpoint
  * Method : POST
  * URI : `/admin-api/attributes/attribute`
  * Data : 
    ```js
    {
      attributeGroupId: 4,
      color: '#bcddb2',
      shopIds: [ 1 ]
    }
    ```

### PrestaShop version(s) where the bug happened

9.0.x

### How you installed PrestaShop

_No response_

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Fixes Swagger documentation for `POST /admin-api/attributes/attribute` endpoint.<br><br>**Issues:**<br>- `names` field was missing or incorrectly shown as `string` instead of `object`<br>- `names` was not marked as required<br>- Auto-generated fields (`attributeId`, `position`) appeared in POST request body<br><br>**Changes:**<br>- Added `Assert\NotBlank` and `openapiContext` to `names` property in `Attribute.php`<br> Enhanced `CQRSOpenApiFactory` to properly handle localized values and filter non-writable properties<br><br>**Result:** Swagger now correctly shows `names` as required object with locale keys, and excludes read-only fields from POST requests.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Open `/admin-api/docs` and check `POST /admin-api/attributes/attribute` endpoint<br>2. Verify `names` appears as required `object` type with locale keys example (`{"en-US": "Value name", "fr-FR": "Nom de la valeur"}`)<br>3. Verify `attributeId` do NOT appear in POST request body<br>4. Verify `attributeId`  appear in GET response<br>5. Test creating an attribute with the documented format to ensure it works correctly
| UI Tests          | https://github.com/tleon/ga.tests.ui.pr/actions/runs/19040956972
| Fixed issue or discussion?     | Fixes #39827
| Related PRs       | https://github.com/PrestaShop/ps_apiresources/pull/100
| Sponsor company   | PrestaShop SA

payload to test the endpoint with should be the same kind as the doc example : 

``` 
{
  "attributeGroupId": 4,
  "names": {
    "en-US": "Green",
    "fr-FR": "Vert"
  },
  "color": "#bcddb2",
  "shopIds": [1]
}
```

### CODE REVIEW

**Comment by Progi1984** [comment]
@tleon You can remove the `skip` in file `tests/UI/campaigns/functional/API/02_endpoints/02_attribute/04_postAttributesAttribute.ts` at line 68

**Comment by tleon** [comment]
I don't think I can since the tests sends this data : 

```   const apiResponse = await apiContext.post('attributes/attribute', {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
        data: {
          attributeGroupId: createAttributeValue.attributeID,
          color: createAttributeValue.color,
          shopIds: [1],
        },
      });```

**Comment by Progi1984** [comment]
@tleon Correct. I will fix it just after the merge of this one.

**Review by boherm — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

File: src/Core/Domain/AttributeGroup/Attribute/Command/AddAttributeCommand.php [hunk 1]
```diff
@@ -62,25 +62,20 @@ class AddAttributeCommand
...
-     * @param int $attributeGroupId
-     * @param array $localizedValue
-     * @param string $color
+     * @param array $localizedNames
      * @param int[] $associatedShopIds
      *
      * @throws AttributeConstraintException
      */
-    public function __construct(int $attributeGroupId, array $localizedValue, string $color, array $associatedShopIds = [])
+    public function __construct(int $attributeGroupId, array $localizedNames, string $color, array $associatedShopIds = [])
```
Comment (jolelievre) [inline src/Core/Domain/AttributeGroup/Attribute/Command/AddAttributeCommand.php:70]: I don't think you need to change this, you can configure the mapping on the module side via `CQRSCommandMapping`

Comment (tleon) [reply src/Core/Domain/AttributeGroup/Attribute/Command/AddAttributeCommand.php:70]: It was for harmonizing. It seems everywhere we use localizedNamed and here we use localizedValue

Comment (jolelievre) [reply src/Core/Domain/AttributeGroup/Attribute/Command/AddAttributeCommand.php:70]: Ok fair enough

**Review by boherm — DISMISSED** [review]

File: tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php [hunk 2]
```diff
@@ -710,4 +721,64 @@ public function getExpectedTags(): iterable
             ['ApiClient'],
         ];
     }
+
+    public function testMultiParameterSettersTransformedToSubObjects(): void
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php]: I think this one can be removed, since the expected data for the `Product` schema have been updated above this one becomes redundant

File: tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php [hunk 3]
```diff
@@ -710,4 +721,64 @@ public function getExpectedTags(): iterable
...
+        $updateProductCommandSchema = $schemas['Product.UpdateProductCommand'];
+        /** @var ArrayObject $addProductCommandSchema */
+        $addProductCommandSchema = $schemas['Product.AddProductCommand'];
+
+        $this->assertArrayHasKey('productId', $productReadSchema['properties']);
+        $this->assertArrayHasKey('productId', $updateProductCommandSchema['properties']);
+        $this->assertArrayNotHasKey('productId', $addProductCommandSchema['properties']);
+    }
+
+    public function testApiPropertyOpenApiContextApplied(): void
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php:755]: Nice!

File: src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/DatePropertyAdapter.php [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+                        $propertyType = $parameters[0]->getType()->getName();
+                    }
+                }
+            }
+
+            $isDateProperty = false;
+            if ($propertyType !== null) {
+                if ($propertyType === DateImmutable::class || (class_exists($propertyType) && is_subclass_of($propertyType, DateImmutable::class))) {
+                    $isDateProperty = true;
+                } elseif ($propertyType === DateTimeInterface::class || (class_exists($propertyType) && in_array(DateTimeInterface::class, class_implements($propertyType) ?: []))) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/DatePropertyAdapter.php]: Hmm, I don't think we need this one no? Because only fields that explicitely use `DateImmutable` should have this special modification

Since `DateTimeInterface` is common to all the date fields this risks to force a `date` format on an expected `datetime` no?

I'd remove this `elseif` case as the previous one seems enough, but maybe I'm missing a use case?

File: src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/DatePropertyAdapter.php [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+                        $isDateProperty = true;
+                    }
+                }
+            }
+
+            if ($isDateProperty) {
+                $definition['properties'][$propertyName]['format'] = 'date';
+
+                $example = $definition['properties'][$propertyName]['example'] ?? null;
+                if (is_string($example)) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/DatePropertyAdapter.php]: Couldn't this be simplified as well? Usually we keep API resources as simple as possible, and using the `DateImmutable` type should be the go-to solution to have proper documentation, so there shouldn't be additional APIProperty

But let's say there is, then it must be for a good reason and we can keep the explicitely set example as is no?

So I think we could simplify this by:

```php
if (empty($example)) {
    $definition['properties'][$propertyName]['example'] = '2025-11-05';
}
```

File: src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/MultiParameterSetterAdapter.php [hunk 6]
```diff
@@ -0,0 +1,168 @@
...
+
+                if ($this->isDateTime($methodParameter->getType())) {
+                    $parameterTypeName = $methodParameter->getType()->getName();
+                    $isDateImmutable = ($parameterTypeName === DateImmutable::class || is_subclass_of($parameterTypeName, DateImmutable::class));
+                    $format = $isDateImmutable ? 'date' : 'date-time';
+                    $methodParameterSchema = new ArrayObject([
+                        'format' => $format,
+                        'type' => 'string',
+                    ]);
+                    if ($isDateImmutable) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/MultiParameterSetterAdapter.php:96]: Maybe we could add an example for regular datetime?

File: src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/SchemaSynchronizer.php [hunk 7]
```diff
@@ -0,0 +1,254 @@
...
+use ReflectionMethod;
+use ReflectionProperty;
+use Symfony\Component\PropertyInfo\PropertyInfoExtractorInterface;
+use Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface;
+use Throwable;
+
+/**
+ * Synchronizes the OpenAPI schema with the actual properties available in the resource.
+ * This removes fields that are documented but don't exist in the actual resource,
+ * and ensures properties from the resource are present in the schema.
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/SchemaSynchronizer.php]: Adding an example here would be perfect to remember the context later (example ean13 no?)

File: src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/SchemaSynchronizer.php [hunk 8]
```diff
@@ -0,0 +1,254 @@
...
+    {
+        if (!class_exists($class)) {
+            return;
+        }
+
+        if (empty($definition['properties'])) {
+            $definition['properties'] = new ArrayObject();
+        }
+
+        if (!$operation) {
```
Comment (jolelievre) [inline src/PrestaShopBundle/ApiPlatform/OpenApi/Adapter/SchemaSynchronizer.php]: I understand the needed for the second part of this adapter: "if a property is set on the command but not on the API resource we remove it from the doc"

But in this case there is no operation, so no CQRS command, so I guess the class used is the API resource itself no? Then it's only for read operations

So my question is, do we need to check if the properties match the API resource properties in this case? Because my understanding is that that's already what is done by API platform, so the properties should already be synced no?

File: tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php [hunk 9]
```diff
@@ -710,4 +721,64 @@ public function getExpectedTags(): iterable
...
+        $this->assertEquals('object', $redirectOptionSchema['type']);
+        $this->assertArrayHasKey('redirectType', $redirectOptionSchema['properties']);
+        $this->assertArrayHasKey('redirectTarget', $redirectOptionSchema['properties']);
+        $this->assertEquals('string', $redirectOptionSchema['properties']['redirectType']['type']);
+        $this->assertEquals('integer', $redirectOptionSchema['properties']['redirectTarget']['type']);
+        $this->assertArrayNotHasKey('redirectType', $properties);
+        $this->assertArrayNotHasKey('redirectTarget', $properties);
+    }
+
+    public function testNonWritablePropertiesFilteredFromWriteOperations(): void
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php]: I'm not sure I understood this one 🤔

File: tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php [hunk 10]
```diff
@@ -425,7 +425,7 @@ public static function provideJsonSchemaFactoryCases(): iterable
                             'fr-FR' => 'valeur',
                         ],
                     ]),
-                    // Nullable DateTime
+                    // Nullable DateImmutable (format is 'date' not 'date-time')
```
Comment (jolelievre) [inline tests/Integration/PrestaShopBundle/ApiPlatform/CQRSOpenApiFactoryTest.php:428]: Currently, the test only checks the format for `date`

We need another example with a `datetime` to make sure both works and that `date` is not forced on all date fields

**Review by jolelievre — APPROVED** [review]
Thanks @tleon

**Review by boherm — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @tleon,

I tested your PR and it's good for me! :tada: 

Thanks!

image


image
