### PR TITLE
Create Order - Cart details modal - Fix refresh for cart total

### LINKED ISSUE #22105: BO - Order page - Details modal for carts - the Refresh button is not working
#### Describe the bug

In the BO > Orders > Add new Order page > Search a customer > choose it > Open the details for a cart > the refresh button doesn't work.
image

PS 1768 => the refresh button doesn't exist
image

#### Steps to Reproduce

1. Go to FO > Sign in with a customer for example "John Doe", add a product to the cart
2. Don't close the tab window
3. Go to BO > Orders > Add new Order > Search the customer "John Doe" > Choose it
4. Click on the details for the last Cart (the modal is opened)
5. Go back to the FO > Add another product to the cart or just update the quantity
6. In the BO > Orders > Add new Order > Cart details modal > Click on Refresh 
7. See error > Nothing happens

PS: if you close the Modal and open it again => OK

**Screenshots**

https://drive.google.com/file/d/1iwjYEFv70elQ4V_qZu-9guwkKP_CjH_w/view?usp=sharing

#### Additional information

* PrestaShop version: 1770stablebuild1.
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
> ### Reverted in 1.7.7.1
> ### **New PR :** https://github.com/PrestaShop/PrestaShop/pull/22685
> 
<br><br>

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix missing source attribute for the KPIHelper to fix JS error. Do not show the refresh button
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22105 
| How to test?  | In BO > Orders > Add new Order page > Search a customer > choose it > Open the details for a cart > You will see the amount of the cart and no *Refresh* button<br><br>In Orders > Shopping carts > choose a cart and hit View > You will see the total amount of the cart and no *Refresh* button

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22249)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Comment by sowbiba** [comment]
Something I don't like here is that we call it KPI but it's not one. It's not reused to make stats. The value is not saved anyway
WDYT @PrestaShop/product-team @PrestaShop/prestashop-maintainers ?

**Review by atomiix — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by sowbiba** [comment]
As discussed with @PrestaShop/product-team , we hide the refresh button because it refreshed the cart total but not the products list. That can be confusing for the user

**Review by atomiix — DISMISSED** [review]

File: controllers/admin/AdminStatsController.php [hunk 1]
```diff
@@ -1025,6 +1025,17 @@ public function displayAjaxGetKpi()
 
                 break;
 
+            case 'shopping_cart_total':
+                $cartId = Tools::getValue('cartId');
+                $cart = new Cart((int) $cartId);
+                if ($cart) {
```
Comment (jolelievre) [inline controllers/admin/AdminStatsController.php]: This will always be true, so the `if` is useless

Comment (jolelievre) [reply controllers/admin/AdminStatsController.php]: Maybe `Validate::isLoadedObject` ? Or remove the if completely

**Review by jolelievre — DISMISSED** [review]
One comment but not blocking (PHPStan might not be happy when we merge ^^)

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Roomsmaniia** [comment]
LGTM,

Thanks @sowbiba

**Comment by matks** [comment]
Thank you @sowbiba

**Comment by Progi1984** [comment]
@sowbiba Could you push a new time your PR to 1.7.7.x ? It will be merged in 1772.

**Comment by sowbiba** [comment]
Reverted in 1.7.7.1
New PR : #22685
