### PR TITLE
Load combination choices depending on shop selection in SpecificPrice form

### LINKED ISSUE #30798: Product v2 specific price combination choices doesn't consider shop constraint
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When adding/editin specific price for product in product page v2 we have selection of shops and selection of combinations. 
These two options are now not dependant on each other.

### Expected behavior

Shop and combination selections should depend on each other. When shop selection changes, combinations list must be reloaded dynamically - 
1. when ALL SHOPS is selected, then combinations from all shops should be shown in choices list
2. when certain shop is selected, then combinations only from that shop should be shown in choices list

### Steps to reproduce

1. Go to product v2 (when multistore is enabled and product v2 page is enabled) and open any product with combination for editing.
2. In Pricing tab press Add specific price
3. Play around with shop selection and combination seleciton inputs and you will see that these always shows same combination no matter if single or all shops is selected (and it will cause issues when there are different combinations between shops)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | refer to #https://github.com/PrestaShop/PrestaShop/issues/30798 (tbd more later)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |  no
| How to test?      | refer to https://github.com/PrestaShop/PrestaShop/issues/30798. ⚠️ note to QA - when testing the PR don't trust combinations list in new product page, because the combinations generation is not yet fixed. So it is now possible to generate combinations for attributes which are not associated to the shop actually therefore the list can be confusing. So for example if in list you see size combinations for shop1, but is not associated to shop1 (in attribute edition page), then in the combination choices list in specific price you shouldn't see those combinations and that is a good sign, it means searching works as expected and it doesn't show attributes that are not associated to the shop.
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/30798
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by zuk3975** [comment]
PR done, but pausing it for a while as one issue was found during it (need to discuss how we proceed).
The issue is related to multishop combinations - so we have combinations copied from shop to shop when copying product, but they doesn't seem to care about the attributes shop association. 

E.g. in shop1 we have color attribute, while in shop2 we have only size:
1. Lets say we create a product and generate color combinations in shop1,
2. then we copy product from shop1 to shop2
3. Result - we have product with color combinations in shop2 (so we end up with logical problem, because actually there is no color attribute associated to shop2)

I added couple behat test cases with a TODO to adjust them after we decide how this all suppose to work. (like when copying product from shop to shop we should also associate related attributes if some of them doesn't exist? should generating combination for all shops throw error or also create the attributes if they are misssing in certain shops etc..) 

ping @MatShir the issue I mentioned in standup.

**Comment by kpodemski** [comment]
@zuk3975 

~Nice catch! IMHO to save the work for merchants, it would be better to associate missing attributes to the target store automatically.~

Edit: that was a **bad** idea :)

**Comment by zuk3975** [comment]
ok so this PR can be merged independently. 
he mentioned [problem](https://github.com/PrestaShop/PrestaShop/pull/30881#issuecomment-1385322067) will have a dedicated issue created and will be solved in dedicated PR.

**Comment by MatShir** [comment]
-> issue created https://github.com/PrestaShop/PrestaShop/issues/30969

File: src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/SpecificPriceCombinationListener.php [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+        $this->combinationRepository = $combinationRepository;
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    public static function getSubscribedEvents(): array
+    {
+        return [
+            //            FormEvents::PRE_SET_DATA => 'updateCombinationChoices',
```
Comment (SharakPL) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/SpecificPriceCombinationListener.php]:
```suggestion
            // FormEvents::PRE_SET_DATA => 'updateCombinationChoices',
```
forgot to remove it?

**Review by SharakPL — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/SpecificPriceCombinationListener.php (hunk 1 above)
Comment (zuk3975) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/SpecificPriceCombinationListener.php]: oh yes, thanks 👍

**Review by SharakPL — DISMISSED** [review]

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php [hunk 2]
```diff
@@ -690,4 +721,129 @@ private function getShopIdsByConstraint(CombinationId $combinationId, ShopConstr
...
+     */
+    private function searchCombinationIdsByAttributes(
+        ProductId $productId,
+        LanguageId $languageId,
+        ShopConstraint $shopConstraint,
+        string $searchPhrase,
+        ?int $limit
+    ): array {
+        if ($shopConstraint->getShopGroupId()) {
+            throw new CombinationException('Group shop constraint not supported');
```
Comment (jolelievre) [inline src/Adapter/Product/Combination/Repository/CombinationRepository.php]:
```suggestion
            throw new InvalidShopConstraintException('Group shop constraint not supported');
```

File: src/Adapter/Product/Combination/Repository/CombinationRepository.php [hunk 3]
```diff
@@ -690,4 +721,129 @@ private function getShopIdsByConstraint(CombinationId $combinationId, ShopConstr
...
+     * @param LanguageId $languageId
+     * @param ShopConstraint $shopConstraint
+     * @param string $searchPhrase
+     *
+     * @return int[]
+     */
+    private function searchAttributes(LanguageId $languageId, ShopConstraint $shopConstraint, string $searchPhrase): array
+    {
+        if ($shopConstraint->getShopGroupId()) {
+            throw new CombinationException('Shop group constraint is not supported');
```
Comment (jolelievre) [inline src/Adapter/Product/Combination/Repository/CombinationRepository.php]:
```suggestion
            throw new InvalidShopConstraintException('Shop group constraint is not supported');
```

File: src/Core/Domain/Product/Combination/QueryResult/ProductCombinationsResult.php [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+declare(strict_types=1);
+
+namespace PrestaShop\PrestaShop\Core\Domain\Product\Combination\QueryResult;
+
+class ProductCombinationsResult
```
Comment (jolelievre) [inline src/Core/Domain/Product/Combination/QueryResult/ProductCombinationsResult.php]:
```suggestion
class ProductCombinationsCollection
```

File: src/PrestaShopBundle/Resources/config/services/core/product.yml [hunk 5]
```diff
@@ -24,3 +25,7 @@ services:
       - '@=service("prestashop.adapter.legacy.configuration").get("PS_ATTRIBUTE_ANCHOR_SEPARATOR")'
 
   PrestaShop\PrestaShop\Core\Product\Combination\NameBuilder\CombinationNameBuilderInterface: '@PrestaShop\PrestaShop\Core\Product\Combination\NameBuilder\CombinationNameBuilder'
+
+  prestashop.core.product.combination.name_builder.combination_name_builder:
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/config/services/core/product.yml]: Why re-introduce this old service name if it's not used anymore? Seems like it wasn't used in 8.0 either so no need to add an already deprecated not used service

File: tests/Integration/Behaviour/Features/Context/Domain/AttributeFeatureContext.php [hunk 6]
```diff
@@ -64,4 +64,56 @@ public function assertNamedAttributeExists(string $attributeReference, string $n
...
+
+    /**
+     * @Given I associate attribute ":attributeReference" with shops ":shopReferences"
+     *
+     * @param string $attributeReference
+     * @param string $shopReferences
+     *
+     * @return void
+     */
+    public function associateAttributeWithShops(string $attributeReference, string $shopReferences): void
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/AttributeFeatureContext.php:77]: Since these steps are based purely on legacy code and no CQRS commands, they should be in the upper namespace `tests/Integration/Behaviour/Features/Context/AttributeFeatureContext.php` (same for the `assertAttributeIsNotAssociatedToShops` end point)

File: tests/Integration/Behaviour/Features/Context/Domain/AttributeGroupFeatureContext.php [hunk 7]
```diff
@@ -70,6 +70,58 @@ public function assertNamedAttributeGroupExists(string $attributeGroupReference,
...
 
+    /**
+     * @Given I associate attribute group ":attributeGroupReference" with shops ":shopReferences"
+     *
+     * @param string $attributeGroupReference
+     * @param string $shopReferences
+     *
+     * @return void
+     */
+    public function associateAttributeGroupWithShops(string $attributeGroupReference, string $shopReferences): void
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/AttributeGroupFeatureContext.php]: Same suggestion as the previous context, these two methods should be placed in the upper namespace

**Comment by jolelievre** [comment]
Woups, there's also a conflict for the routing file now

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

File: tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+     * @param string $productReference
+     * @param string $searchPhrase
+     * @param string $langIso
+     * @param string $shopReference
+     * @param int $limit
+     * @param ProductCombinationsCollection $expectedResults
+     *
+     * @return void
+     *
+     *@see transformProductCombinationsResult for $expectedResults type transformation
```
Comment (SharakPL) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php:52]:
```suggestion
     * @see transformProductCombinationsResult for $expectedResults type transformation
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+     *
+     * @param string $productReference
+     * @param string $searchPhrase
+     * @param string $langIso
+     * @param int $limit
+     * @param ProductCombinationsCollection $expectedResults
+     *
+     * @return void
+     *
+     *@see transformProductCombinationsResult for $expectedResults type transformation
```
Comment (SharakPL) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php:83]:
```suggestion
     * @see transformProductCombinationsResult for $expectedResults type transformation
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php [hunk 10]
```diff
@@ -0,0 +1,153 @@
...
+     * @param string $productReference
+     * @param string $searchPhrase
+     * @param string $langIso
+     * @param ShopConstraint $shopConstraint
+     * @param int $limit
+     * @param ProductCombinationsCollection $expectedResults
+     *
+     * @return void
+     *
+     *@see transformProductCombinationsResult for $expectedResults type transformation
```
Comment (SharakPL) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/Combination/SearchProductCombinationFeatureContext.php:132]:
```suggestion
     * @see transformProductCombinationsResult for $expectedResults type transformation
```

**Review by SharakPL — APPROVED** [review]
Just a tiny docblock issues, but nothing blocking the PR.

**Comment by paulnoelcholot** [comment]
Hello @zuk3975,

I have tested your PR and it's OK for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @zuk3975 :)
