### PR TITLE
Removed use of service parameter in controller

### LINKED ISSUE #25711: [BO] - Generate Emails throws an exception missing `parameter_bag`
#### Describe the bug

When I click on Generate Emails, an exception will be thrown

#### Expected behavior

no error, a success message will be displayed (like 1780)

image

#### Steps to Reproduce

1. BO > IMPROVE > Design > Email Theme
2. In **Generate emails**, choose **classic** for **Select your email theme**
3. Choose **English** for **Select your language**
4. Choose **classic** for **Select the theme you want to overwrite**
5. Select **No** for **Overwrite templates**
6. Click on **Generate emails** button
7. See error

**Screenshots**

image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed use of service parameter in controller
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25711
| How to test?      | Cf. #25711

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25776)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Hi @Progi1984,

that is not really the same, you may use [ParameterBagInterface](https://symfony.com/blog/new-in-symfony-4-1-getting-container-parameters-as-a-service) as direct dependency of the controller instead or parameter binding.

Also, as this parameter is now part of the Request : does it means that someone evil can alter the value ?

WDYT ?

File: src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php [hunk 1]
```diff
@@ -117,7 +118,7 @@ public function generateMailsAction(Request $request)
                 $modulesMailFolder = '';
                 //Overwrite theme folder if selected
                 if (!empty($data['theme'])) {
-                    $themeFolder = $this->getParameter('themes_dir') . '/' . $data['theme'];
+                    $themeFolder = $themes_dir . '/' . $data['theme'];
```
Comment (matks) [inline src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: I might be wrong but it sounds like the original intent was
```suggestion
                    $themeFolder = $this->container->getParameter('themes_dir') . '/' . $data['theme'];
```

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: It was but it seems it doesn't work anymore, because the `parameter_bag` is not accessible in the container anymore. See the error thrown here: https://github.com/symfony/symfony/blob/2ea14ffc32bc46319bff29ab6ccaeea5ba5aa9f0/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L68

So maybe there is more simple, the controller would need to be registered as a service or maybe we need to configure the `parameter_bag` in our container, either way, this might be doable via configuration in the framework instead of modifying the code.

Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController.php]: Is it really needed to register a parameterBag for the container for this method which is only requires something already defined in service? It will use memory for nothing, seems a little bit overkill imho

**Review by jolelievre — DISMISSED** [review]
Nice, thanks @Progi1984

File: src/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProvider.php [hunk 2]
```diff
@@ -61,7 +67,7 @@ public function getChoices()
             $coreMailsFolder = $theme->getDirectory() . '/mails';
             $modulesMailFolder = $theme->getDirectory() . '/modules';
             if (is_dir($coreMailsFolder) || is_dir($modulesMailFolder)) {
-                $themeChoices[$theme->getName()] = $theme->getName();
+                $themeChoices[$theme->getName()] = realpath($this->themesDirectory . '/' . $theme->getName());
```
Comment (jolelievre) [inline src/Core/Form/ChoiceProvider/ThemeByNameWithEmailsChoiceProvider.php]: I just realized something, I wonder if we even need to inject `themesDirectory` Since the Theme class already contains this folder maybe you could simply do:

```suggestion
                $themeChoices[$theme->getName()] = $theme->getDirectory();
```

**Review by jolelievre — APPROVED** [review]
The third implementation is the right one 😅

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by mickaelandrieu — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,
The basic scenario was tested and it is Ok as shown in the recording bellow 
https://www.awesomescreenshot.com/video/5390592?key=5ebe7321b34b6003b60f0a1ccca58d58
Also I changed the language to Arabic and the theme to classic and I made sure that the emails are changed to classic when the client chooses the Arabic as language.
=> PR validated and can be merged

**Comment by Progi1984** [comment]
Thanks @marwachelly
