### PR TITLE
Refresh order products when a product is added or deleted

### LINKED ISSUE #21500: BO - Order page - Ajax issue - The gift Product is not removed when removing a product ordered
#### Describe the bug

Related to this [PR](https://github.com/PrestaShop/PrestaShop/pull/21447)
In the FO, when we add product A to the cart then checkout, the Order must contain Product A and Product B
In the BO > Order detail page => when we remove the Product A from the order, the cart rule is removed and Product B is not removed, we need to reload the page

#### Expected behavior

The ProductB should be removed

**SPECS**:

When a product is successfully added to the order, a notification of success is displayed: "The item was successfully added." in Admin.Notifications.Success.
Then the product list is reloaded behind the loading spinner to check if any new products could be added through automatics carts rules. The user is redirected to the first page of the product list.

When a product is removed from the order, a notification is displayed: "The item was successfully removed." in Admin.Notifications.Error.
Then the product list is refreshed behind the loading spinner to check if any gift product has to be removed as well. The user is redirected to the page where the user removed the product. If the removed product was on the last page, the user is redirected to the second-last page.

FYI: specs are updated

#### Steps to Reproduce

1. Go to BO > Catalog > Discounts page
2. Create a cart rule "free gift "demo_6 60*90"
3. Go to FO > Add any other product to cart
4. Apply the discount
5. Continue checkout
6. in the BO > Order detail page > remove the product Ordered
7. See the error "The gift Product is not removed"
8. if you reload the page => OK

**Screenshots**

https://drive.google.com/file/d/1N06UU3WrfwgVwgeiTDnB26R_3PEOtc3v/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When an order's product is added or deleted, the list of products is entirely retreived from the back. This list is now sorted by orderDetailId, so the last product added is on the top
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21500 
| How to test?  | Edit an order, the list must be ordered by orderDetailId DESC.<br>When an product is added, you will see a loading spin and few seconds after the list w/o the product added. It will be on the top of the list<br>Delete a product from the list, you will see a loading spin and few seconds after the list w/o the product deleted<br>After each action on this list, the pagination must be correct

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21692)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 1]
```diff
@@ -709,10 +712,15 @@ public function addProductAction(int $orderId, Request $request): Response
...
+            $updatedProducts[$orderProductForViewing->getOrderDetailId()] = $orderProductForViewing;
+        }
         $newProducts = [];
-        for ($i = count($previousProducts); $i < count($updatedProducts); ++$i) {
-            $newProducts[] = $updatedProducts[$i];
+        foreach (array_keys($updatedProducts) as $productKey) {
+            if (!in_array($productKey, array_keys($previousProducts), true)) {
+                $newProducts[] = $updatedProducts[$productKey];
+            }
         }
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
        $newProducts = array_diff(array_keys($updatedProducts), array_keys($previousProducts));
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 2]
```diff
@@ -1446,6 +1454,48 @@ public function getPricesAction(int $orderId): JsonResponse
...
+        $this->dispatchHook(
+            'actionGetAdminOrderButtons', [
+            'controller' => $this,
+            'id_order' => $orderId,
+            'actions_bar_buttons_collection' => $backOfficeOrderButtons,
+        ]);
+
+        $cancelProductForm = $formBuilder->getFormFor($orderId);
+
+        $paginationNum = (int) $this->configuration->get('PS_ORDER_PRODUCTS_NB_PER_PAGE', self::DEFAULT_PRODUCTS_NUMBER);
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
        $paginationNum = $this->configuration->getInt('PS_ORDER_PRODUCTS_NB_PER_PAGE', self::DEFAULT_PRODUCTS_NUMBER);
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php (hunk 1 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Thanks Franck. I will only get the keys if I do this. And after that I can put the objects into $newProducts

Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Correct.

```suggestion
        $newProducts = array_diff_assoc($updatedProducts, $previousProducts);
```

Comment (sowbiba) [reply src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: array_diff_assoc works only if values can be converted to string

I'm trying https://www.php.net/manual/fr/function.array-diff-key.php

**Review by Progi1984 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 3]
```diff
@@ -337,4 +317,42 @@ export default class OrderViewPage {
...
     return $(OrderViewPageMap.productsTablePagination).find('.active span').get(0);
   }
+
+  refreshProductsList(orderId) {
+    const $loadingSpinner = $(OrderViewPageMap.productsPanel).find('.spinner-order-products-container#orderProductsLoading');
+    $loadingSpinner.show();
+
+    const $tablePagination = $(OrderViewPageMap.productsTablePagination);
+    const numRowsPerPage = $tablePagination.data('numPerPage');
+    const initialNumProducts = parseInt($(OrderViewPageMap.productsCount).html(), 10);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]:
```suggestion
    const initialNumProducts = $(OrderViewPageMap.productsTableRows).length;
```
I didn't make this change last time I modified this, but it's probably more stable this way 😉

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig [hunk 4]
```diff
@@ -115,3 +118,9 @@
 
   <script src="{{ asset('themes/new-theme/public/order_view.bundle.js') }}"></script>
 {% endblock %}
+
+{% set js_translatable = {
+  "Items successfully added": '[1] item[2] was succesfully added.'|trans({}, 'Admin.Notifications.Success'),
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: In the plural form it won't be correct it will say `2 items was successfully added.` instead of `2 items were successfully added.`

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: In more advanced translation framework you can define singular/plural forms But in this case I think it's two basic So you have two solutions either have 4 wordings (two for singular and two for plural) Or rephrase the sentence in another way like:
`Successfully added [1] item(s).` (this kind of wording is already used)

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js [hunk 5]
```diff
@@ -38,7 +38,7 @@ export default class OrderProductRenderer {
     if ($productRow.length > 0) {
       $productRow.html($(newRow).html());
     } else {
-      $(OrderViewPageMap.productAddRow).before($(newRow).hide().fadeIn());
+      $(OrderViewPageMap.productsTableRows).first().before($(newRow).hide().fadeIn());
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js]: Are you sure you still need this method since the whole list is refreshed? Maybe it can be removed?

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 6]
```diff
@@ -126,39 +118,18 @@ export default class OrderViewPage {
...
-      const newPagesNum = Math.ceil(newNumProducts / numRowsPerPage);
-
-      // Update pagination
-      if (newPagesNum > initialPagesNum) {
-        this.orderProductRenderer.paginationAddPage(newPagesNum);
-      }
-
-      this.orderProductRenderer.updateNumProducts(newNumProducts);
       this.orderProductRenderer.resetAddRow();
       this.orderPricesRefresher.refreshProductPrices(event.orderId);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js:115]: I think that `this.orderPricesRefresher.refreshProductPrices` is now useless since the whole list is refreshed You should remove it everywhere The API endpoint for backward compatibility can be kept but maybe add a comment that is not used any more (for now at least) So that we deprecate it sometime later if we really don't use it at all

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 7]
```diff
@@ -126,39 +118,18 @@ export default class OrderViewPage {
...
       this.orderDiscountsRefresher.refresh(event.orderId);
       this.orderInvoicesRefresher.refresh(event.orderId);
       this.orderDocumentsRefresher.refresh(event.orderId);
       this.orderProductRenderer.moveProductPanelToOriginalPosition();
 
-      // Move to last page to see the added product
+      // Move to first page to see the added product
       EventEmitter.emit(OrderViewEventMap.productListPaginated, {
-        numPage: newPagesNum
+        numPage: 1
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: The switch to page 1 should be performed in `refreshProductsList` There is no interest of moving to page 1 until the list is refreshed and pagination reset

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: Or at least you should do this in a callback, or maybe have a second parameter to indicate which page you are targeting after the refresh Because when a product is deleted I'm not sure the first page is the best choice it should be the current page (former deleted product's page)

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 8]
```diff
@@ -337,4 +308,68 @@ export default class OrderViewPage {
...
+            this._fadeAlert($alertBlock);
+          }
+
+          // Bind actions on products
+          this.listenForProductDelete();
+          this.listenForProductEdit();
+          this.resetToolTips();
+        })
+        .fail(errors => {
+          location.reload();
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: Boum!! 😅

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 9]
```diff
@@ -337,4 +308,68 @@ export default class OrderViewPage {
...
     return $(OrderViewPageMap.productsTablePagination).find('.active span').get(0);
   }
+
+  refreshProductsList(orderId) {
+    const $loadingSpinner = $(OrderViewPageMap.productsPanel).find('.spinner-order-products-container#orderProductsLoading');
+    $loadingSpinner.show();
+
+    const $tablePagination = $(OrderViewPageMap.productsTablePagination);
+    const numRowsPerPage = $tablePagination.data('numPerPage');
+    const initialNumProducts = $(OrderViewPageMap.productsTableRows).length;
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js:306]: Be careful I recently noticed this but actually this is not the number of products strictly speaking It's the number of rows So you shouldn't rely on this for your alert because if the gift was already present there will be no new rows (but there is a second new product)

And I actually wonder if it's correct to use this for the label that displays the number of products 🤔  (the one used by `this.orderProductRenderer.updateNumProducts`) Shouldn't it indicates the total number of products instead? (like the sum of each rows) @MatShir this is a question for you 🙂

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 10]
```diff
@@ -337,4 +308,68 @@ export default class OrderViewPage {
...
+
+          const newNumProducts = $(OrderViewPageMap.productsTableRows).length;
+          const initialPagesNum = Math.max(Math.ceil(initialNumProducts / numRowsPerPage), 1);
+          const newPagesNum = Math.ceil(newNumProducts / numRowsPerPage);
+
+          this.orderProductRenderer.updateNumProducts(newNumProducts);
+
+          // Update pagination
+          if (newPagesNum > initialPagesNum) {
+            this.orderProductRenderer.paginationAddPage(newPagesNum);
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: Be careful this won't work when you remove a product if the number of pages decreased It would be easier to actually just set the number of pages with a new method and get rid of these unstable addPage/removePage methods
All this should be handled by a single initPagination method that is used on page loading as well

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 11]
```diff
@@ -709,12 +712,13 @@ public function addProductAction(int $orderId, Request $request): Response
...
-        $updatedProducts = $orderForViewing->getProducts()->getProducts();
-        $newProducts = [];
-        for ($i = count($previousProducts); $i < count($updatedProducts); ++$i) {
-            $newProducts[] = $updatedProducts[$i];
+        $updatedProducts = [];
+        foreach ($orderForViewing->getProducts()->getProducts() as $orderProductForViewing) {
+            $updatedProducts[$orderProductForViewing->getOrderDetailId()] = $orderProductForViewing;
         }
 
+        $newProducts = array_diff_key($updatedProducts, $previousProducts);
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:729]: Nice catch, even though it shouldn't be useful any more since you refresh the whole list

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product_list.html.twig [hunk 12]
```diff
@@ -0,0 +1,20 @@
...
+
+{% for product in orderForViewing.products.products %}
+    {% include '@PrestaShop/Admin/Sell/Order/Order/Blocks/View/product.html.twig' with {
+        'product': product,
+        'productIndex': loop.index,
+        'paginationNum': paginationNum,
+        'isColumnLocationDisplayed': isColumnLocationDisplayed,
+        'isColumnRefundedDisplayed': isColumnRefundedDisplayed
+    } %}
+{% endfor %}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product_list.html.twig]: Missing EOL

File: src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php [hunk 13]
```diff
@@ -169,7 +169,8 @@ public function handle(GetOrderProductsForViewing $query): OrderProductsForViewi
 
         unset($product);
 
-        ksort($products);
+        // reorder products by order_detail_id DESC
+        krsort($products);
```
Comment (jolelievre) [inline src/Adapter/Order/QueryHandler/GetOrderProductsForViewingHandler.php]: I think this should be related to a parameter to indicate the expected order, optional parameter that you can set in the OrderController

This would prevent modifying the test that need to reorder the result to get the expected results I wouldn't go as far as classifying this as a BC break (to change the order) but at least it should be choosable (and the default behaviour should be the original one)

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 14]
```diff
@@ -337,4 +308,68 @@ export default class OrderViewPage {
...
+            $alertBlock.find('.alert-text').html(
+                window.translate_javascripts['Items successfully added']
+                    .replace('[1]', (newNumProducts-initialNumProducts))
+                    .replace('[2]', (newNumProducts-initialNumProducts) > 1 ? 's' : '')
+            );
+            this._fadeAlert($alertBlock);
+          }
+
+          // Bind actions on products
+          this.listenForProductDelete();
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: As @eternoendless said you should modify the listeners so that they are registered on the parent but with sub selectors This will allow you to only listen once and then no need to re-register the listeners With jquery it's quite easy, it's called delegated selectors, instead of doing:

```js
$(OrderViewPageMap.productDeleteBtn)
      .off('click')
      .on('click', (event) => this.orderProductManager.handleDeleteProductEvent(event));
```

you can do

```js
$(OrderViewPageMap.productsTable).on(
    'click',
    OrderViewPageMap.productDeleteBtn,
    (event) => this.orderProductManager.handleDeleteProductEvent(event)
);
```

The idea is that `OrderViewPageMap.productsTable` which is the element that will not be removed is the one that listens the `click` event even when it bubbles from a child, and it only triggers the handler when the original target of the even is `OrderViewPageMap.productDeleteBtn`

So you register only **once** and then no matter how many elements you add or remove the click is already registered

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 9 above)
Comment (MatShir) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js:306]: Legacy only counts the line :cry:. I will update the specs

Comment (MatShir) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js:306]: I guess this PR is not the place to fix this

**Comment by MatShir** [comment]
**SPECS**:

When a product is successfully added to the order, a notification of success is displayed: "The item was successfully added." in Admin.Notifications.Success.
Then the product list is reloaded behind the loading spinner to check if any new products could be added through automatics carts rules. The user is redirected to the first page of the product list.

When a product is removed from the order, a notification is displayed: "The item was successfully removed." in Admin.Notifications.Error.
Then the product list is refreshed behind the loading spinner to check if any gift product has to be removed as well. The user is redirected to the page where the user removed the product. If the removed product was on the last page, the user is redirected to the second-last page.

FYI: specs are updated

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js (hunk 5 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js]: The else can be removed. The IF clause is still useful when editing a row https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js#L106

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 6 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js:115]: Still used in productUpdated event aswell
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js#L112

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 8 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: :joy: Yes, if something wrong with the API request, I don't know what to do so ... I refresh

File: src/Core/Domain/ValueObject/QuerySorting.php [hunk 15]
```diff
@@ -0,0 +1,75 @@
...
+    }
+
+    /**
+     * @param string $sorting
+     *
+     * @throws InvalidSortingException
+     */
+    private function assertSortingSupported(string $sorting): void
+    {
+        if (!in_array($sorting, [self::ASC, self::DESC], true)) {
```
Comment (jolelievre) [inline src/Core/Domain/ValueObject/QuerySorting.php:73]: Maybe we should check `strtoupper($sorting)` Just to be a bit less strict and allow `desc` or `asc` as input
The stored value must be in upper case though, so we would just need to do `$sorting = strtoupper($sorting);` in the constructor

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js [hunk 16]
```diff
@@ -268,4 +221,27 @@ export default class OrderProductRenderer {
     }
     $(target).toggleClass('d-none', !isColumnDisplayed);
   }
+
+  initPagination() {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js]:
```suggestion
  updatePaginationControls() {
```

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 17]
```diff
@@ -337,4 +285,62 @@ export default class OrderViewPage {
...
+
+          // Display alert
+          if (initialNumProducts > newNumProducts) { // product deleted
+            $.growl.notice({
+              title: '',
+              message: window.translate_javascripts['Items successfully removed']
+                  .replace('[1]', (initialNumProducts-newNumProducts))
+            });
+            // Move to page of the deleted item
+            EventEmitter.emit(OrderViewEventMap.productListPaginated, {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: This should be performed outside of this `if/elseif` block because in case `initialNumProducts == newNumProducts` (for an unknown weird reason) the event is never triggered

So you can init `let numPage = 1` before the id, only change its value when `initialNumProducts > newNumProducts` and then always trigger the event after the growl So that we are sure to be in a consistent state

File: src/Core/Domain/ValueObject/QuerySorting.php [hunk 18]
```diff
@@ -0,0 +1,75 @@
...
+    {
+        $this->assertSortingSupported($sorting);
+
+        $this->sorting = $sorting;
+    }
+
+    /**
+     * @return string
+     */
+    public function getValue()
```
Comment (jolelievre) [inline src/Core/Domain/ValueObject/QuerySorting.php]:
```suggestion
    public function getValue(): string
```

File: src/Core/Domain/ValueObject/QuerySorting.php [hunk 19]
```diff
@@ -0,0 +1,75 @@
...
+ *
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
```
Comment (jolelievre) [inline src/Core/Domain/ValueObject/QuerySorting.php:27]: missing declare strict type

File: src/Core/Domain/Exception/InvalidSortingException.php [hunk 20]
```diff
@@ -0,0 +1,36 @@
...
+ *
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
```
Comment (jolelievre) [inline src/Core/Domain/Exception/InvalidSortingException.php:27]: missing declare strict type

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 21]
```diff
@@ -666,11 +667,6 @@ private function handleOutOfStockProduct(OrderForViewing $orderForViewing)
      */
     public function addProductAction(int $orderId, Request $request): Response
     {
-        /** @var OrderForViewing $orderForViewing */
-        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php:674]: I know we don't need this any more since we don't rely on the response content, but it is still a BC break
I suggest we wait until the RC1 is validated (or not) If an RC2 is required then we can remove this code, if not let's leave it with a comment explaining that it's not used any more and should be removed in a major version

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 22]
```diff
@@ -1446,6 +1415,48 @@ public function getPricesAction(int $orderId): JsonResponse
...
+    public function getProductsListAction(int $orderId): Response
+    {
+        /** @var OrderForViewing $orderForViewing */
+        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId, QuerySorting::DESC));
+
+        $currencyDataProvider = $this->container->get('prestashop.adapter.data_provider.currency');
+        $orderCurrency = $currencyDataProvider->getCurrencyById($orderForViewing->getCurrencyId());
+
+        $formBuilder = $this->get('prestashop.core.form.identifiable_object.builder.cancel_product_form_builder');
+        $backOfficeOrderButtons = new ActionsBarButtonsCollection();
```
Comment (jolelievre) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: This is not useful for product list These buttons are used in the top layer of the product page

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 23]
```diff
@@ -337,4 +285,62 @@ export default class OrderViewPage {
   getActivePage() {
     return $(OrderViewPageMap.productsTablePagination).find('.active span').get(0);
   }
+
+  refreshProductsList(orderId) {
+    const $loadingSpinner = $(OrderViewPageMap.productsPanel).find('.spinner-order-products-container#orderProductsLoading');
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: You need to add this in `OrderViewPageMap`

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig [hunk 24]
```diff
@@ -115,3 +115,9 @@
 
   <script src="{{ asset('themes/new-theme/public/order_view.bundle.js') }}"></script>
 {% endblock %}
+
+{% set js_translatable = {
+  "Items successfully added": 'Succesfully added [1] item(s).'|trans({}, 'Admin.Notifications.Success'),
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: Wording question for @Julievrz or @LouiseBonnard First foes this kind of wording seem ok to you? Regarding the way to handle plural
Second, should we use a generic wording (using "items") or a specific one for this page (using "products")

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 25]
```diff
@@ -235,7 +235,7 @@ public function removeProductsFromOrder(string $productReference, string $orderR
         $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
         /** @var OrderProductForViewing[] $products */
         $products = $orderForViewing->getProducts()->getProducts();
-        foreach ($products as $product) {
+        foreach (array_reverse($products) as $product) {
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Since the default order is no `ASC` you don't need to reverse the array If you want to be sure you can force the parameter in GetOrderForViewing though
I think this might be related with the errors in the behat tests of specific prices

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 8 above)
Comment (atomiix) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: Why not notifying it with a growl notification?

File: src/Core/Domain/ValueObject/QuerySorting.php [hunk 26]
```diff
@@ -0,0 +1,77 @@
...
+use PrestaShop\PrestaShop\Core\Domain\Exception\InvalidSortingException;
+
+/**
+ * Class QuerySorting is responsible for providing valid sorting parameter.
+ */
+class QuerySorting
+{
+    const ASC = 'ASC';
+    const DESC = 'DESC';
```
Comment (atomiix) [inline src/Core/Domain/ValueObject/QuerySorting.php]:
```suggestion
    public const ASC = 'ASC';
    public const DESC = 'DESC';
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 27]
```diff
@@ -667,9 +668,12 @@ private function handleOutOfStockProduct(OrderForViewing $orderForViewing)
     public function addProductAction(int $orderId, Request $request): Response
     {
         /** @var OrderForViewing $orderForViewing */
-        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
+        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId, 'DESC'));
```
Comment (atomiix) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId, QuerySorting::DESC));
```

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 28]
```diff
@@ -706,15 +710,20 @@ public function addProductAction(int $orderId, Request $request): Response
             );
         }
 
+        /**
+         * Returning the products list view is not required since we reload the whole list
+         * We keep it for now to avoid Breaking Change
+         */
         /** @var OrderForViewing $orderForViewing */
-        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId));
+        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId, 'DESC'));
```
Comment (atomiix) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
        $orderForViewing = $this->getQueryBus()->handle(new GetOrderForViewing($orderId, QuerySorting::DESC));
```

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig (hunk 24 above)
Comment (Julievrz) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: @jolelievre I am not a fan of this way to handle the plural form because it can be very difficult to translate for languages who have a completely different word for plural form (e.g.: Polish). 

I think the best solution would be to have 2 strings. One in singular "The product was successfully added/removed."  and one in plural for bulk actions ("Products were successfully added/removed") 

If you can do this, that would be perfect!

If we are talking about products only here then you are right, using the word "product" makes more sense, thank you for noticing it. 😊

Comment (Julievrz) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig]: @sowbiba Do you think it would be possible to have 2 different wordings as explained above? 😊

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 29]
```diff
@@ -337,4 +285,73 @@ export default class OrderViewPage {
...
+                    .replace('[1]', (newNumProducts-initialNumProducts))
+            ;
+
+            // Move to first page to see the added product
+            numPage = 1;
+          }
+
+          $.growl.notice({
+            title: '',
+            message: message,
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: if message is empty, what is the behavior ?

**Review by Progi1984 — COMMENTED** [review]
Small feedback

**Comment by Julievrz** [comment]
Thank you @sowbiba for adapted the wording! All good for me ☺️

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 29 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: an empty growl is displayed. I updated the code to test if message is empty

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@sowbiba Travis is :red_circle:

File: tests/UI/pages/BO/orders/view.js [hunk 30]
```diff
@@ -55,6 +55,9 @@ class Order extends BOBasePage {
       page.click(this.UpdateProductButton),
       this.waitForVisibleSelector(page, this.editProductQuantityInput),
     ]);
+    await Promise.all([
+      this.waitForVisibleSelector(page, this.productQuantitySpan(row)),
+    ]);
```
Comment (boubkerbribri) [inline tests/UI/pages/BO/orders/view.js]:
```suggestion
    await this.waitForVisibleSelector(page, this.productQuantitySpan(row));
```

No need for `Promise.all`

**Review by atomiix — DISMISSED** [review]

**Review by boubkerbribri — DISMISSED** [review]
LGTM for UI tests

**Review by Progi1984 — DISMISSED** [review]

**Review by boubkerbribri — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product_list.html.twig [hunk 31]
```diff
@@ -0,0 +1,20 @@
+{% set isColumnLocationDisplayed = false %}
+{% set isColumnRefundedDisplayed = false %}
+{% for product in orderForViewing.products.products|slice(0, paginationNum) %}
+    {% if product.location is not empty %}
+        {% set isColumnLocationDisplayed = true %}
+    {% endif %}
+    {% if product.quantityRefunded > 0 %}
+        {% set isColumnRefundedDisplayed = true %}
+    {% endif %}
+{% endfor %}
```
Comment (atomiix) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product_list.html.twig]: I think you can remove [those lines](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/products.html.twig#L26-L35) then

Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/product_list.html.twig]: They are set in products.html.twig so no need to re-set them.

I did the same in the controller to pass the variables to the template for the Ajax action

**Review by atomiix — DISMISSED** [review]

**Review by boubkerbribri — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js [hunk 32]
```diff
@@ -135,40 +127,19 @@ export default class OrderViewPage {
...
       this.orderPricesRefresher.refresh(event.orderId);
+      this.refreshProductsList(event.orderId);
       this.orderPaymentsRefresher.refresh(event.orderId);
       this.orderDiscountsRefresher.refresh(event.orderId);
       this.orderInvoicesRefresher.refresh(event.orderId);
       this.orderDocumentsRefresher.refresh(event.orderId);
       this.orderProductRenderer.moveProductPanelToOriginalPosition();
 
-      // Move to last page to see the added product
+      // Move to first page to see the added product
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: This event is fired while the list is being refreshed (since there is an ajax request and no `await` behaviour) So it's triggered too soon and is either useless or at the wrong place Either it should be triggered automatically in the `refreshProductsList` or it should be called in a success calback after `refreshProductsList` (which would need a callback parameter in this case)

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js [hunk 33]
```diff
@@ -197,47 +197,8 @@ export default class OrderProductRenderer {
...
-  }
-
-  paginationAddPage(numPage) {
-    const $tablePagination = $(OrderViewPageMap.productsTablePagination);
-    $tablePagination.data('numPages', numPage);
-    const $linkPagination = $(OrderViewPageMap.productsTablePaginationTemplate).clone();
-    $linkPagination.find('span').attr('data-page', numPage);
-    $linkPagination.find('span').html(numPage);
-    $(OrderViewPageMap.productsTablePaginationTemplate).before($linkPagination.removeClass('d-none'));
-    this.togglePaginationControls();
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-renderer.js:232]: Are you sure `togglePaginationControls` is still called correctly when necessary? The controls should not be visible when there is only one page So when adding/removing products or when the number of elements per page is changed the controls may need to be hidden/shown

File: admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js (hunk 32 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-view-page.js]: You're right. This call is not necessary
We already move to the first page when a product is added and to the relevant page if a product is deleted
https://github.com/PrestaShop/PrestaShop/pull/21692/files#diff-a6fbb1713c4a3ada62793c614ff8b1b56b4da7804338dedc16402c89bc6de0d2R378

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM If travis is :+1: it's ok for QA !!
Thanks @sowbiba !!

**Comment by Progi1984** [comment]
Thanks @sowbiba & @SD1982
