### PR TITLE
Fix object model partial update

### LINKED ISSUE #13007: Function setFieldsToUpdate() does not work for single database table
**Describe the bug**
While you want to simply one field while update an ObjectModel, you could use the setFieldsToUpdate() method. But this one need to have a _shop table associated, to work.

Instead, the ObjectModel is whole saved.

**To Reproduce**
1. Instanciate an ObjectModel (which have no _shop table associated !)
2. Change somes properties
3. Apply the setFieldsToUpdate() method for one of theses modified changes
4. Update the ObjectModel
5. See that the ObjectModel is whole saved, instead of the only field to update.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fixes the management of partial updates, along the way the feature became buggy and didn't work anymore. This PR fixes the behaviour for classic fields, multi lang fields and multishop fields.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #13007
| How to test?      | This is a technical modification, which is hard to test by QA That is why some integration tests were added to validate the fix The tests were added before the fix to highlight the behaviours that didn't work (see this build https://github.com/jolelievre/PrestaShop/runs/3623175580) Then the fix was cherry-picked from this PR #25464 where it was initially fixed So no QA is needed only CI green
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25913)

### Description

This modification is important because it appears the whole "partial update of an ObjectModel" feature has been buggy for quite a while now. I went through the history of this code and found these consecutive modifications:

https://github.com/PrestaShop/PrestaShop/commit/009e190263a2b4d904d084b0bea5a02a2c235fdb
https://github.com/PrestaShop/PrestaShop/commit/84d1e57ad968bb6fd81ba22ac6e4ef40d5efbeee
https://github.com/PrestaShop/PrestaShop/commit/07c3ee5dd1ddc1b091fc0700249d5d5def6ca7cd (https://github.com/PrestaShop/PrestaShop/pull/2452)

I think the code got harder and harder to understand and some features were lost along the way, the initial purpose of `update_fields` is to filter the fields that need to be updated, so basically if the `update_fields` is defined and the field is not inside the array we skip it so it's not updated

Although there are a few complex use cases:

For multilang values, the `updated_fields` must be check based on the `$id_lang` of course

For multishop values:

- any multishop value should only be updated in the `_shop` table not in the original one
- in the Product case this check was not correctly done, since most fields are duplicated it resulted in updating the column in both the `product` table AND the `product_shop` table
- there is an exception though when the multishop field is defined with `'shop' => 'both'` then the value must be updated in both tables (this is only used for `Combination` and `Image`)

But the way the `both` feature was handled broke the feature because the condition `!empty($data['shop']) && $data['shop'] != 'both'` is not correct, the purpose is to detect when `'shop' => true` but since `'both'` is considered truthy the condition is never met even when `'shop' => true` That's why a strict non equality is required here.

### CODE REVIEW

File: tests/Integration/Classes/ObjectModelTest.php [hunk 1]
```diff
@@ -0,0 +1,691 @@
...
+        }
+        if (isset($value[self::SECOND_LANGUAGE_PLACEHOLDER])) {
+            $localizedValue[$this->secondLanguageId] = $value[self::SECOND_LANGUAGE_PLACEHOLDER];
+        }
+
+        return $localizedValue;
+    }
+}
+
+class TestableObjectModel extends ObjectModel
```
Comment (PierreRambaud) [inline tests/Integration/Classes/ObjectModelTest.php]: Should be outside this file, maybe in a fixture namespace?

File: tests/Integration/Classes/ObjectModelTest.php [hunk 2]
```diff
@@ -0,0 +1,691 @@
...
+     * @param array $updatedProperties
+     */
+    private function applyModifications(TestableObjectModel $object, array $updatedProperties): void
+    {
+        foreach ($updatedProperties as $field => $value) {
+            if (is_array($value)) {
+                $object->{$field} = $this->convertLocalizedValue($value);
+            } else {
+                $object->{$field} = $value;
+            }
```
Comment (PierreRambaud) [inline tests/Integration/Classes/ObjectModelTest.php]:
```suggestion
            $object->{$field} = is_array($value) ? $this->convertLocalizedValue($value) : $value;
```

File: classes/ObjectModel.php [hunk 3]
```diff
@@ -406,12 +406,16 @@ protected function formatFields($type, $id_lang = null)
...
             if (($type == self::FORMAT_LANG && empty($data['lang']))
                 || ($type == self::FORMAT_SHOP && empty($data['shop']))
-                || ($type == self::FORMAT_COMMON && ((!empty($data['shop']) && $data['shop'] != 'both') || !empty($data['lang'])))) {
+                || ($type == self::FORMAT_COMMON && ((!empty($data['shop']) && $data['shop'] !== 'both') || !empty($data['lang'])))) {
                 continue;
             }
 
             if (is_array($this->update_fields)) {
-                if ((!empty($data['lang']) || (!empty($data['shop']) && $data['shop'] != 'both')) && (empty($this->update_fields[$field]) || ($type == self::FORMAT_LANG && empty($this->update_fields[$field][$id_lang])))) {
+                if (!empty($data['lang']) && $type == self::FORMAT_LANG && empty($this->update_fields[$field][$id_lang])) {
```
Comment (PierreRambaud) [inline classes/ObjectModel.php]: :+1:

File: tests/Integration/Classes/ObjectModelTest.php (hunk 1 above)
Comment (jolelievre) [reply tests/Integration/Classes/ObjectModelTest.php]: Since it's only used in this test (and not meant to be used somewhere else) I like the fact that's it's in the same file

File: tests/Integration/Classes/ObjectModelTest.php [hunk 4]
```diff
@@ -0,0 +1,691 @@
...
+    }
+
+    private function installTestableObjectTables(): void
+    {
+        $testableObjectSqlFile = dirname(__DIR__, 2) . '/Resources/sql/install_testable_object.sql';
+        $sqlRequest = file_get_contents($testableObjectSqlFile);
+        $sqlRequest = preg_replace('/PREFIX_/', _DB_PREFIX_, $sqlRequest);
+
+        $dbCollation = Db::getInstance()->getValue('SELECT @@collation_database');
+        $allowedCollations = ['utf8mb4_general_ci', 'utf8mb4_unicode_ci'];
```
Comment (PierreRambaud) [inline tests/Integration/Classes/ObjectModelTest.php]: I think you can avoid these preg_replace and directly put the desired behavior in the sql file :)

File: tests/Integration/Classes/ObjectModelTest.php (hunk 1 above)
Comment (PierreRambaud) [reply tests/Integration/Classes/ObjectModelTest.php]: Afaik, PSR-4 will also trigger warning because of having two classes in the same file

Comment (jolelievre) [reply tests/Integration/Classes/ObjectModelTest.php]: I don't think so, I already did it in other tests classes But just because I like you I will move it 😘

File: tests/Integration/Classes/ObjectModelTest.php (hunk 4 above)
Comment (jolelievre) [reply tests/Integration/Classes/ObjectModelTest.php]: Probably, but I prefer tests to remain a bit dynamic just in case, it's not that complicated nor performance taxing anyway

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

File: classes/ObjectModel.php [hunk 5]
```diff
@@ -406,12 +406,16 @@ protected function formatFields($type, $id_lang = null)
             // E.g. if only lang fields are filtered, ignore fields without lang => true
             if (($type == self::FORMAT_LANG && empty($data['lang']))
                 || ($type == self::FORMAT_SHOP && empty($data['shop']))
-                || ($type == self::FORMAT_COMMON && ((!empty($data['shop']) && $data['shop'] != 'both') || !empty($data['lang'])))) {
+                || ($type == self::FORMAT_COMMON && ((!empty($data['shop']) && $data['shop'] !== 'both') || !empty($data['lang'])))) {
```
Comment (eternoendless) [inline classes/ObjectModel.php:414]: Isn't this related to this bug? https://github.com/PrestaShop/PrestaShop/issues/25346#issuecomment-892599529

Comment (jolelievre) [reply classes/ObjectModel.php:414]: Mmm, yes and no The part I fixed is only about partial update

I noticed the same problem mentioned in the other issue, regardless of how you defined the multishop field I had to have it in both the origin table and the multishop table, so I guess there is still a bug about this Should it be fixed in the same PR?

File: classes/ObjectModel.php [hunk 6]
```diff
@@ -406,12 +406,16 @@ protected function formatFields($type, $id_lang = null)
...
                 continue;
             }
 
             if (is_array($this->update_fields)) {
-                if ((!empty($data['lang']) || (!empty($data['shop']) && $data['shop'] != 'both')) && (empty($this->update_fields[$field]) || ($type == self::FORMAT_LANG && empty($this->update_fields[$field][$id_lang])))) {
+                if (!empty($data['lang']) && $type == self::FORMAT_LANG && empty($this->update_fields[$field][$id_lang])) {
+                    continue;
+                } elseif (!empty($data['shop']) && $type == self::FORMAT_SHOP && $data['shop'] !== 'both' && empty($this->update_fields[$field])) {
+                    continue;
+                } elseif ($type == self::FORMAT_COMMON && empty($this->update_fields[$field])) {
```
Comment (eternoendless) [inline classes/ObjectModel.php]: Consider adding comments to explain the cases

File: classes/ObjectModel.php [hunk 7]
```diff
@@ -755,34 +759,35 @@ public function update($null_values = false)
             $this->id_shop_default = (in_array(Configuration::get('PS_SHOP_DEFAULT'), $id_shop_list) == true) ? Configuration::get('PS_SHOP_DEFAULT') : min($id_shop_list);
         }
         // Database update
-        if (!$result = Db::getInstance()->update($this->def['table'], $this->getFields(), '`' . pSQL($this->def['primary']) . '` = ' . (int) $this->id, 0, $null_values)) {
+        $updatedFields = $this->getFields();
```
Comment (eternoendless) [inline classes/ObjectModel.php]: I think this should be either "fieldsToUpdate" (fields being the ones in the database) or "updatedProperties" (properties being the ones in ObjectModel)

File: src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php [hunk 8]
```diff
@@ -107,6 +107,7 @@ private function fillUpdatableProperties(Combination $combination, UpdateCombina
 
         if (null !== $command->getWeight()) {
             $combination->weight = (float) (string) $command->getWeight();
+            $updatableProperties[] = 'weight';
```
Comment (eternoendless) [inline src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php:110]: Is this change related?

File: tests/Integration/Classes/ObjectModelTest.php [hunk 9]
```diff
@@ -0,0 +1,678 @@
...
+     * @var int
+     */
+    private $defaultShopId;
+
+    /**
+     * @var int
+     */
+    private $secondShopId;
+
+    protected function setUp(): void
```
Comment (eternoendless) [inline tests/Integration/Classes/ObjectModelTest.php:66]: Shouldn't there be a teardown to remove what was inserted?

Consider doing the setup/teardown using setupBeforeClass and teardownBeforeClass to avoid doing this once per test case.

File: tests/Integration/Classes/ObjectModelTest.php [hunk 10]
```diff
@@ -0,0 +1,678 @@
...
+        $multiLangObject->enabled = true;
+        $multiLangObject->name = $localizedNames;
+        $this->assertTrue((bool) $multiLangObject->update());
+
+        $defaultLangObject = new TestableObjectModel($createdId, $this->defaultLanguageId);
+        $this->assertEquals($localizedNames[$this->defaultLanguageId], $defaultLangObject->name);
+
+        $secondLangObject = new TestableObjectModel($createdId, $this->secondLanguageId);
+        $this->assertEquals($localizedNames[$this->secondLanguageId], $secondLangObject->name);
+    }
```
Comment (eternoendless) [inline tests/Integration/Classes/ObjectModelTest.php]: These are actually three or four separate tests, see [Test dependencies](https://phpunit.readthedocs.io/en/9.5/writing-tests-for-phpunit.html#test-dependencies)

File: src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/Product/Combination/CommandHandler/UpdateCombinationDetailsHandler.php:110]: Yes and no, since the partial update didn't work we couldn't detect that this behat test was failing because everything was saved anyway So now that partial update works correctly the CI is falling here and prevents the merge
I could create yet another PR to fix this separately but it feels a bit overkill IMHO

File: tests/Integration/Classes/ObjectModelTest.php (hunk 9 above)
Comment (jolelievre) [reply tests/Integration/Classes/ObjectModelTest.php:66]: I wanted to rely on setupBeforeClass/teardownBeforeClass But the problem is that this Intergation test environment uses `processIsolation=true` which seems to make `setupBeforeClass` called on EACH tests.. Basically setupBeforeClass acts almost like a regular setUp

This is really bothersome, because of this I wasn't able to make a proper independent initialization (which is why I need to always check if the data is present or not) nor can I do a cleaning because I can't detect which test is the last one

But I tried to clean as much as possible, so I still drop the content of `testable_object` table on each init, I could also drop them on tearDown and remove the extra shop and language, but it will result in creating/dropping each content on each test call which will make the whole test longer

File: tests/Integration/Classes/ObjectModelTest.php (hunk 10 above)
Comment (jolelievre) [reply tests/Integration/Classes/ObjectModelTest.php]: I know but because of this process isolation it's really hard to create such dependencies because the content will be re-initialized between each test and I will lose the previously created entities in DB

This whole processIsolation really is a pain!!

File: classes/ObjectModel.php (hunk 7 above)
Comment (jolelievre) [reply classes/ObjectModel.php]: Ok I'll go with `fieldsToUpdate` here, so that it makes more sense with the `getFields` Mixing fields and properties would make the code more complex to read/understand

File: classes/ObjectModel.php (hunk 5 above)
Comment (jolelievre) [reply classes/ObjectModel.php:414]: I researched a bit more the other bug, so it is indeed partly related to this code but also (mainly) because of this part https://github.com/PrestaShop/PrestaShop/blob/62206a604f2557d5e067d6b8d81f68528e254d47/classes/ObjectModel.php#L296

Which merges multi shop fields with regular fields no matter what, seems like it was for retro compatibility I guess we could get rid of this in v8 so that multishop fields are no longer duplicated in their associated table? (in another PR maybe as it represents quite a big change)

Comment (matks) [reply classes/ObjectModel.php:414]: > I guess we could get rid of this in v8

I think we might fix a bug and introduce another if we do that.

Too many things are coupled, mixed, blended in this ObjectModel, I think if we really want to modify the internal behavior we need a full exploration of everything that's supposed to happen. Understand every bit of logic, including the ones added for backward compatibility, test the whole thing... and then we could start doing such changes. But unless we 100% understand this part (no guess, rather certainties) I suggest we pause a bit 😅

File: tests/Integration/Classes/ObjectModelTest.php (hunk 10 above)
Comment (matks) [reply tests/Integration/Classes/ObjectModelTest.php]: Make it work, make it right, make it fast.

I think @jolelievre did the 1st step and that is already a great achievement 😉  . I suggest we keep it like this for now, and iterate later if we really want to make ObjectModel tests a thing. Testing this part of the code is already a massive challenge by itself.

**Review by matks — DISMISSED** [review]
Code is good enough for me. I think we should merge it. If we want to improve it more, we should iterate following the agile mindset.

File: classes/ObjectModel.php (hunk 5 above)
Comment (jolelievre) [reply classes/ObjectModel.php:414]: Yep, the intent was not to do it in this PR anyway

But aside from that, if we wait for certainties to ùake changes I think we will never make them, the code is 7 years old, nothing was documented, all the old devs are gone I don't see how we can have certainties on what was expected at the time, we will always move forward making guesses

The best we could do is make a survey to the community to get feedback on these features and how they were used 5 or 6 years ago, but I'm not sure we'll be able to get many answers on this

Comment (matks) [reply classes/ObjectModel.php:414]: > But aside from that, if we wait for certainties to make changes I think we will never make them, the code is 7 years old, nothing was documented, all the old devs are gone I don't see how we can have certainties on what was expected at the time, we will always move forward making guesses

If we spend one or two weeks deciphering the ObjectModel behavior, carefully building test cases one by one to make sure we understand 100% the goal of each statement, we could have certainties.

However it needs a lot of time 😞

**Review by eternoendless — DISMISSED** [review]
LGTM

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]
