### PR TITLE
Avoid using _PS_PRICE_COMPUTE_PRECISION_

### LINKED ISSUE #26553: Problem with orders with amounts without decimals
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When Prestashop is configured so that it does not use decimals, when validating the order with the 'validateOrder' method, the order is marked with payment error (PS_OS_ERROR)

on line 323 the error is thrown
```php
if ($order_status->logable && number_format($cart_total_paid, Context::getContext()->getComputingPrecision()) != number_format($amount_paid, _PS_PRICE_COMPUTE_PRECISION_)) {
    $id_order_state = Configuration::get('PS_OS_ERROR');
}
```

In the if, the amount is validated with the constant _PS_PRICE_COMPUTE_PRECISION_ and the configuration of the currency is not checked. In this case the variable **_$cart_total_paid_** always has a difference with the amount paid (**_number_format($amount_paid, _PS_PRICE_COMPUTE_PRECISION_)_**).

image

### Expected behavior

The order is marked with the correct status

### Steps to reproduce

1. Install clean Prestashop versión >= 1.7.8.0.
2. Create currency without decimal and set as default.
3. Install the `Payment by check` and enable it or use a payment method that set the status of payment in `payment accepted (ps_order_state id 2)` or `Processing in progress (ps_order_state id 3)`.
3. Create an publish product with price lower than $1000.
4. Create and publish product with price higher than $1000.
5. Buy a product with the `Payment by check` payment method or the one configured with a price less than $ 1000. It should work fine.
6. Purchase product with the `Payment by check` payment method or the one configured with price higher than $1000. This will fail and set order to Payment Error state.

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #26671: Payment error with currency without two decimal places 1.7.8.1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

It is identified that with the Colombian currency (Peso COP) it throws a payment error when there are no configured decimals or with a configured decimal.
When the two decimal places are configured in the COP currency, the order is created correctly with the Order status "Pending payment".
For the COP currency it is not necessary to have decimals. Is it possible to omit these decimals?

https://drive.google.com/file/d/17DRKRMeU3J3z1gHuOWOjODePW28Bxo8s/view

### Expected behavior

It must allow the correct generation of the order with decimals equal to zero in the mode configuration as is currently the case with version 1.7.7.x

### Steps to reproduce

1. Go to International - Location - Currency
2. Change Decimals to Zero

image

3. From the front office place an order.
4. It generates an error in the payment.

---

1. Install 1781 / 1780
2. Install the module COD
3. add the currency DZD or Colombian currency ( units of thousands)
4. Change precision of the currency to 0
5. Create an order from FO with COD
6. In the BO > Order > the status of the order is payment error

I manage to reproduce the issue with PS1780 / PS1781 using COD only
It is ok with PS1778 and 1769 => it's a **regression** on **1.7.8.0**

### PrestaShop version(s) where the bug happened

1.7.8.1

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_wirepayment

### PR DESCRIPTION
**Pull request by mpaolino**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | PaymentModule::validateOrder is using the deprecated config constant<br>`_PS_PRICE_COMPUTE_PRECISION_` to generate a string representation of the total amount paid with a payment module and comparing that to the cart total string representation calculated with `Context::getContext()->getComputingPrecision()`. This check will always fail when a currency with a decimal precision is different than the present `_PS_PRICE_COMPUTE_PRECISION_ = 2` constant, hence the order will be placed in a payment error status and no log or further details will be displayed. This happens for example while using MercadoPago payment module v4.8.0 (official partner). Apparently _PS_PRICE_COMPUTE_PRECISION_ was deprecated in 1.7.7.x but this core class still uses it. The proposed change substitutes the constant with the precision value obtained from the context, just like it is used in the rest of the source code. Also a log is added to register this error situation. 
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26553
| How to test?      | Create a currency with decimal values different than "2", make a purchase in the FO, order is created with status Configuration::get('PS_OS_ERROR') instead of a valid one. Full details in bug report. 
| Possible impacts? | This is a core PaymentModule change so impact might be big, I'd check for all and any regressions regarding payments. There is still another place that `_PS_PRICE_COMPUTE_PRECISION_` [is in use in PaymentModule](https://github.com/PrestaShop/PrestaShop/blob/586dbdbb3c60899f9f07b1eb41864b9e4333175a/classes/PaymentModule.php#L1148), this should be probably addressed in a different issue. 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26824)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Thanks for the PR ! As I said in https://github.com/PrestaShop/PrestaShop/issues/26553 the PR seems good but we really need a list of clear steps to reproduce the bug, else QA team wont be able to reproduce the issue and verify it's now solved.

**Comment by mpaolino** [comment]
Actually there is more than one bug in that single conditional line.

The problem why QA could not reproduce it was probably they didn't use a localization that has the comma (",") as decimal separator.

The rationale behind that comparison is they are trying to avoid round errors, but:

1) They are comparing with different number of decimals precision (`number_format` rounds the values).
2) They are using the inequality operator to do the comparison, which will evaluate to 0 (true) in cases like "100.00" == "100", but would fail in case of "100,00" == "100". The original reporter and mi use localizations that use commas as separators.

BTW, this is how PHP prior to 8.0 does the comparison on number strings: https://www.php.net/manual/en/language.operators.comparison.php

There are a number of ways of doing this right but probably PHPs strcmp will work correctly, I will update this if I have the time.

**Comment by mpaolino** [comment]
Actually there is more than one bug in that single conditional line.The problem why QA could not reproduce it was probably they didn't made a purchase that was higher or equals to $1000.

The rationale behind that comparison is they are trying to avoid rounding errors, but:

1) They are comparing with different number of decimal precision (number_format rounds the values).

2) They are using the inequality operator to do the comparison, which will actually convert strings to numbers, and it will round numbers and incorrectly process commas in thousands separators. This achieves the complete opposite of what was intended.
Notably, this situation yields wrong results if the purchase exceeds 1000, or if the purchase is lower than 1000 but the paid amount has any decimals.

```php
php > var_dump(number_format(1000, 2));
string(8) "1,000.00"

php > var_dump(number_format(1000, 0));
string(5) "1,000"

php > var_dump(number_format(100, 2));
string(6) "100.00"

php > var_dump(number_format(100, 0));
string(3) "100"
```

This is how PHP prior to 8.0 does the comparison on number strings: https://www.php.net/manual/en/language.operators.comparison.php

So for example:

```php
php > var_dump(number_format(1000, 2) != number_format(1000, 0));
bool(true)

php > var_dump(number_format(100, 2) != number_format(100, 0));
bool(false)

php > var_dump(number_format(100, 2) != number_format(100.10, 0));
bool(false)

```

There are a number of ways of doing this right but probably PHPs strcmp will work correctly independently of all combinations, I will update this if I have the time.

**Comment by mpaolino** [comment]
Steps to reproduce the bug:

1. - Install clean Prestashop
1.1 - Configure Prestashop tu use a single currency with decimals value "0".

2. - Install [MercadoPago 4.8.0 module ](https://addons.prestashop.com/es/pago-tarjeta-carteras-digitales/23962-mercado-pago.html)
2.1 - Configure MercadoPago plugin with:
2.1.1 - Country: Uruguay
2.1.2 - Public Key: TEST-f9ea27ea-8d3b-4ebe-b614-648e7c85656d
2.1.3 - Access token: TEST-3885957295412805-120315-3cc32a81f07c5cbfa0d122dbe4f04547-19099354
2.2 - Select Visa and Master as valid card payment options under "CHECKOUT PRO" tab.
Screenshot from 2021-12-06 16-32-16
Screenshot from 2021-12-06 16-32-08
Screenshot from 2021-12-06 16-31-41
2.3 - Under Advanced Configuration (Configuracion Avanzada in Spanish) select all options as per screenshot.

3. Create an publish product with price lower than $1000
4. Create and publish product with price higher than $1000
5. Purchase product with price lower than $1000. Should work ok.
6. Purchase product with price higher than $1000. **This should fail.**

**Comment by mpaolino** [comment]
@matks done. Steps to reproduce in bug report.

**Comment by ocio87** [comment]
Hello, I just tested the change in the PaymentModule.php file and it no longer throws a payment error with the bank transfer module in Colombia currency without decimals.

https://drive.google.com/file/d/1-6ESV_2R6voEnkq3kv4fIg5MkkT6kCRF/view?usp=sharing

image

Thanks,

**Review by sowbiba — DISMISSED** [review]
Fix seems good. Can you rebase 1.7.8.x and change the PR target ?

I can help if you need it

File: classes/PaymentModule.php [hunk 1]
```diff
@@ -315,8 +315,10 @@ public function validateOrder(
             // Amount paid by customer is not the right one -> Status = payment error
             // We don't use the following condition to avoid the float precision issues : http://www.php.net/manual/en/language.types.float.php
             // if ($order->total_paid != $order->total_paid_real)
-            // We use number_format in order to compare two string
-            if ($order_status->logable && number_format($cart_total_paid, Context::getContext()->getComputingPrecision()) != number_format($amount_paid, _PS_PRICE_COMPUTE_PRECISION_)) {
+            // We use number_format to convert the numbers to strings and strcmp to compare them to avoid auto reconversions to numbers in PHP < 8.0
+            $comp_precision = Context::getContext()->getComputingPrecision();
+            if ($order_status->logable && (strcmp(number_format($cart_total_paid, $comp_precision), number_format($amount_paid, $comp_precision)) != 0)) {
```
Comment (jolelievre) [inline classes/PaymentModule.php]:
```suggestion
            if ($order_status->logable && (number_format($cart_total_paid, $comp_precision) !== number_format($amount_paid, $comp_precision))) {
```

Comment (jolelievre) [reply classes/PaymentModule.php]: I think you can use strict equality to avoid auto reconversion

Comment (jolelievre) [reply classes/PaymentModule.php]: And as @sowbiba suggested, this should target the 1.7.8.x branch

**Review by jolelievre — COMMENTED** [review]
Thanks @mpaolino

File: classes/PaymentModule.php (hunk 1 above)
Comment (mpaolino) [reply classes/PaymentModule.php]: I'll take care of targeting 1.7.8.x no problem. Regarding the code suggestion, since this is your code base and you guys maintain it, I think honoring your preference is the right thing to do. I like the shorter version but I though the longer version was justified to avoid hiding what is actually being done in this specific case that PHP behaves so awkwardly (and to be fair the return value evaluation should have being `!== 0`). Putting a `!==` in there would make that more easy to change it back, while strcmp will at least require a little more effort to understand why it has being done that way and there is no practical performance impact.

Anyways, you have a deal.

**Comment by mpaolino** [comment]
> Fix seems good. Can you rebase 1.7.8.x and change the PR target ?
> 
> I can help if you need it

SOW, sorry, shit hit the fan. A rebase is not really possible as develop and `1.7.8.x` differ too much. I'll try to revert it here for historical purposes, not sure how Github its gonna handle this. I think a new PR targeting `1.7.8.x` will be a better alternative. You guys can later merge/cheery pick changes to whatever branch you'd like.

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Still waiting for https://github.com/PrestaShop/PrestaShop/issues/26553 to be verified by QA 😊  but I'm positive we'll succeed!

**Review by jolelievre — APPROVED** [review]

**Comment by mastudillot** [comment]
When will the pull request merge?

**Comment by matks** [comment]
Hello everyone _we cannot merge this PR until a QA analyst has validated it_. And QA analyst needs the bug report https://github.com/PrestaShop/PrestaShop/issues/26553 to be verified. QA analyst will use the verified scenario to then poke around, change some settings and verify everything is good not only for the situation described but also in related scenarii.

If you wish this PR to move forward please help making https://github.com/PrestaShop/PrestaShop/issues/26553 being verified ;) there's still confusion

**Comment by mpaolino** [comment]
> Hello everyone _we cannot merge this PR until a QA analyst has validated it_. And QA analyst needs the bug report #26553 to be verified. QA analyst will use the verified scenario to then poke around, change some settings and verify everything is good not only for the situation described but also in related scenarii.
> 
> If you wish this PR to move forward please help making #26553 being verified ;) there's still confusion

OK, let me explain then:

* A very detailed bug report was given by @mastudillot along a very clear set of instructions to reproduce it.
* QA decided to not follow those instructions, instead decided to test whatever they wanted, determined they could not reproduce it and closed the issue marking it as `Invalid`.
* I provided this PR to fix this issue
* I provided a new, separate set of instructions in the same bug report with an official plugin in an attempt to make them actually test it
* I mentioned the QA team member to try to reopen the issue
* QA reopened the bug and left it in "needs spec" on 6th Dec 2021 and abandoned it.
* I provided an additional step to @mastudillot's instructions to try to match the scenario QA actually used (but did not shared). They used the check payment plugin when no one told them to, so I provided the extra instruction to trigger the bug with that plugin. For some reason QA wont use a third party plugins to reproduce issues, completely ignoring the fact plugins can use faulty core functionality. I wonder what happens when you have a core bug that is only triggered by a third party plugin.

As you can see, all the confusion is a direct result of how the information is being handled, the information provided is not honored and it gets buried in threads, confusion derived from scenarios not provided by the contributors and overall very bad handling. 
As another example of this status quo, your last message in the bug report 25 days ago made it look like your team had everything to test it and nothing else was needed from contributors, unfortunately it seems that now there's still confusion.
This is not an isolated thing, same happened in another PR I made, they closed it for no reason, not even tested it, I had to spend more time trying to get it open again and tested.

As you can see, in none of these cases we actually need to provide additional information for the bugs to be reproduced, we're just struggling with the team to correctly do the triaging and testing.

Having said all that, I will once again provide a new set of instructions in an attempt that the team actually test it *as provided*, unfortunately I believe this is the last time I will be contributing PRs to this project as you well said but might not be aware, we are **all** buried in work and I can't afford to keep compensating for the shortcomings of this development process.

**Comment by ocio87** [comment]
Hello,

Adding what is indicated by @mpaolino.

Please remember that there is also evidence of the bug https://github.com/PrestaShop/PrestaShop/issues/26671 reported with the bank transfer module where multiple users have reported the same decimal problem.

Thanks,

**Comment by Guisardo** [comment]
Hi @mpaolino , please notice that that the same constant is being used in another place of the same file:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L1160

Could you change that one too to avoid another PR?

**Comment by mpaolino** [comment]
> Hi @mpaolino , please notice that that the same constant is being used in another place of the same file:
> https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L1160
> 
> Could you change that one too to avoid another PR?

Hi.

I already pointed that out in the initial PR report. This is a bug fix for a single reported bug, what your are asking here is that I complete the refactor of PaymentModule to completely remove the constant. Although I recognize there must  be another underlying bug there, this is out of scope for this PR and I don't have the time to hunt for the triggering use cases. Feel free to provide the PR as it will require a  different set of test instructions.

**Review by sowbiba — APPROVED** [review]

**Comment by mpaolino** [comment]
@sowbiba I assume there is something required from me since the issue is in "Waiting for author". Can you comment on that?

**Comment by mastudillot** [comment]
Any news to be able to mix the PR?

**Review by PierreRambaud — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
Hello @mpaolino 
Tested on 1.7.8.x branch.
PHP 7.2.21 version

Tested on cases below:

- created order from BO with product > 1000 + < 1000 
- created order from FO with product > 1000 + < 1000 
- tested with custom currencies with decimal/without decimal
- tested with custom currencies with modified exchange rate
- tested with multiple payment modules
- modified order statuses options

QA approved ✅

**Comment by Progi1984** [comment]
Thanks @mpaolino

**Comment by mastudillot** [comment]
Thanks to everyone
