### PR TITLE
Orders View : Display right price depending configuration

### LINKED ISSUE #23957: BO - Order page - The total price excluding taxes is displayed instead of the total price including taxes
#### Describe the bug

In the BO, within an order, the total price shown in the title row and in the order total block, is shown without taxes instead of the price with taxes, this happens when selecting "show prices: taxes excluded" for a group of clients.

#### Expected behavior

Here are two parts:

1. When you enter in 
the order, the total price of the title and the info block are shown excluding taxes instead of taxes included. (it should be 2.56 Euro)

2. When you click on modify the product, under the column "Total taxes excluded", the price is shown including taxes. When you leave the edition the price returns to being tax excluded

#### Steps to Reproduce

Customer X is in the default group of Customers.

1. Create a product A with a price without taxes of € 2,116 (2.56 with taxes).

2. Go to Store parameters> Customer settings> Groups and modify the Customers group

3. In the section Price display method, change to Tax excluded.

4. In the FO, Customer X places an order with product A and checks that the prices with taxes excluded (€ 2.12) and taxes included (€ 2.56) are displayed in the cart.

5. In the BO, go to Orders> Orders and see the order with Product A. Here the employee sees the total price with taxes included of the order placed (€ 2.56).

6. Enter within the order

7. The employee sees the total price taxes excluded wrongly.

https://user-images.githubusercontent.com/82192606/114123658-07c8b100-98f3-11eb-9999-8e770b8a93f8.mp4

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.7.3
* PHP version: 7.3.27

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Orders View : Display right price depending configuration
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23957
| How to test?      | 1. Create a product A with a price without taxes of € 2,116 (2.56 with taxes).<br>2. Go to Store parameters> Customer settings> Groups and modify the Customers group<br>3. In the section Price display method, change to Tax excluded.<br>4. In the FO, Customer X places an order with product A and checks that the prices with taxes excluded (€ 2.12) and taxes included (€ 2.56) are displayed in the cart.<br>5. In the BO, go to Orders> Orders and see the order with Product A. Here the employee sees the total price with taxes included of the order placed (€ 2.56).<br>6. In the Orders List, in the preview of the order, the price is in tax excluded (like the configuration of Customer Group)<br>7. Enter within the order<br>8. The employee sees the total price taxes excluded wrongly.<br>9. In product lists, the total price for the row of the product is tax excluded (like the configuration of Customer Group)<br>10. In product lists, in summary, the total price is tax included<br>11. In product lists, in edition of row, the last column of total is tax excluded (like the configuration of Customer Group)<br>
 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24324)

### CODE REVIEW

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php [hunk 1]
```diff
@@ -709,15 +709,14 @@ private function getOrderPrices(Order $order): OrderPricesForViewing
...
-            $totalAmount = (float) $order->total_paid_tax_excl;
         } else {
             $productsPrice = (float) $order->total_products_wt;
             $discountsAmount = (float) $order->total_discounts_tax_incl;
             $wrappingPrice = (float) $order->total_wrapping_tax_incl;
             $shippingPrice = (float) $order->total_shipping_tax_incl;
             $shippingRefundable = max(0, $shipping_refundable_tax_incl);
-            $totalAmount = (float) $order->total_paid_tax_incl;
         }
+        $totalAmount = (float) $order->total_paid_tax_incl;
```
Comment (matks) [inline src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:727]: Hi @Progi1984 I suppose the PR is in WIP but this seems to be something that needs to be explained 😅  why always return total_paid_tax_incl ?

Comment (Progi1984) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:727]: I will link tomorrow if @MatShir  has done improvements on specs

**Review by matthieu-rolland — DISMISSED** [review]

File: src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php:727]: I also don't understand this, we're supposed to switch the display with/without taxes but you always use the amount with tax 🤔

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Create a product A with a price without taxes of € 2,116 (2.56 with taxes).
2. Go to Store parameters> Customer settings> Groups and modify the Customers group
3. In the section Price display method, change to Tax excluded.
4. In the FO, Customer X places an order with product A and checks that the prices with taxes excluded (€ 2.12) and taxes included (€ 2.56) are displayed in the cart.
5. Go to BO > orders > Shopping cart page
6. View last order
7. see the error: the total is displayed with tax excluded 

image


Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith Could you create an issue ? It's not in the scope of the PR (Orders View).

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Thanks, I created another issue: https://github.com/PrestaShop/PrestaShop/issues/24484
But some other issues about this: `In product lists, in edition of row, the last column of total is tax excluded (like the configuration of Customer Group)`

1. Create a product A with a price without taxes of € 2,116 (2.5392 with taxes).
2. Go to Store parameters> Customer settings> Groups and modify the Customers group
3. In the section Price display method, change to Tax excluded.
4. In the FO, Customer X places an order with product A and checks that the prices with taxes excluded (€ 2.12) and taxes included (€ 2.54) are displayed in the cart.
5. Go to BO > orders > Last Order created
6. Edit the product
7. Try to change the quantity (Increase the decrease it again)
8. See error => The total is tax included 
image
9. Also try to change the product price 
image
10. Try to add the same product (or another product)
11. See error, the total displayed is tax included instead of tax excluded 
image

Thank you!

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

Sorry but the last issue is still displayed
I followed these steps:
1.
```
cd admin-dev/themes/new-theme
rm -rf node_modules
npm i --verbose
npm install
npm run build
```
2. `rm -R PrestaShop/var/cache/dev`
3. Fresh install with English language & France country with incognito browser
4. Create a product A with a price without taxes of € 2,116 (2.5392 with taxes) >  Go to Store parameters> Customer settings> Groups and modify the Customers group > In the section Price display method, change to Tax excluded.
5. In the FO, Customer X places an order with product A and checks that the prices with taxes excluded (€ 2.12) and taxes included (€ 2.54) are displayed in the cart.
6. Go to BO > orders > Last Order created > Try to **add** the same product (or another product)
7. See an error, the total displayed is tax included instead of tax excluded
image
8. If you change quantity in the block **Add** => NOK (it should be displayed with tax excluded)
image
9. If you change the price in the block **Add** => NOK  (it should be displayed with tax excluded)
image

Thank you!

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
1. ` In the BO, go to Orders> Orders and see the order with Product A. Here the employee sees the total price with taxes included of the order placed (€ 2.56).` => ok 
image
2. `In the Orders List, in the preview of the order, the price is in tax excluded (like the configuration of Customer Group)` => ok
image
3. `In product lists, the total price for the row of the product is tax excluded (like the configuration of Customer Group)` => ok
image
4. `In product lists, in summary, the total price is tax included` => ok
image
5.` In product lists, in edition of row, the last column of total is tax excluded (like the configuration of Customer Group)` => ok (I checked with Edit and Add)
image
image

1. I checked with Group tax excluded (customer) and Group tax included (Guest) => ok
2. I checked when a guest is transformed to customer
3. I created order from BO and FO


Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
