### PR TITLE
Load module translation catalogues for all present modules

### LINKED ISSUE #30241: Unable to translate module's tabs using XLF
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

To translate module's added menus (tabs); we are supposed to use colums of the ps_tab table named `wording` (to store the wording) and `wording_domain` (to store the translation domain).
The menus are supposed to be translated when they are stored in ps_tab_lang

https://devdocs.prestashop-project.org/1.7/modules/concepts/controllers/admin-controllers/tabs/#since-prestashop-178

But this doesn't work

### Expected behavior

_No response_

### Steps to reproduce

Have a module with 
- translations with xlf
- an added tab using wording and wording_domain

Install it

See that the tabs are not translated

Here is an example module 
[prestashopexamplemodule.zip](https://github.com/PrestaShop/PrestaShop/files/9963234/prestashopexamplemodule.zip)

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | During the installation of a module the translation catalog is loaded so it's available (among other things) for the multi lang tab creation
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~
| UI Tests          | https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/13806182696
| Fixed issue or discussion?     | Fixes #30241
| Related PRs       | https://github.com/PrestaShopCorp/ps_classic_edition/pull/53
| Sponsor company   | ~

### How to test

Install this module  [ps_classic_edition.zip](https://github.com/user-attachments/files/19167003/ps_classic_edition.zip) that modifies the menu on the left in the BO. Without this PR the tab `Welcome` and `Home` are not correctly translated, with the PR both tabs are correctly translated in French (optionally also in Spanish and Italian)

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop`, `9.0.x` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `description` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#description))
* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `category` should be one of these: `FO`, `BO`, `CO`, `IN`, `WS`, `TE`, `LO`, `ME` or `PM`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `BC breaks` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#bc-breaks))
* The `deprecations` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#deprecations))
* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Hlavtox** [comment]
@jolelievre Looking at the description, this is going to fix non-translated modules before they are installed, right?

File: src/Adapter/Module/Repository/ModuleRepository.php [hunk 1]
```diff
@@ -128,6 +133,30 @@ public function getActiveModules(): array
...
 
+    /**
+     * Return present modules (even if those not installed in DB).
+     *
+     * @return array
+     */
+    public function getPresentModules(): array
+    {
+        if (!defined('_DB_PREFIX_')) {
+            return []; // getActiveModules() can be called during install BEFORE the database configuration has been defined
```
Comment (nicosomb) [inline src/Adapter/Module/Repository/ModuleRepository.php]:
```suggestion
            return []; // getPresentModules() can't be called during install BEFORE the database configuration has been defined
```

File: src/Adapter/Module/Repository/ModuleRepository.php [hunk 2]
```diff
@@ -128,6 +133,30 @@ public function getActiveModules(): array
...
+        }
+
+        $presentModules = [];
+        try {
+            foreach ($this->getModulesFromFolder() as $moduleName => $modulePath) {
+                $presentModules[] = $moduleName;
+            }
+        } catch (Exception) {
+            // DO nothing. getPresentModules() can be called during install BEFORE the database configuration has been defined
```
Comment (nicosomb) [inline src/Adapter/Module/Repository/ModuleRepository.php]:
```suggestion
            // DO nothing. getPresentModules() can't be called during install BEFORE the database configuration has been defined
```

File: src/Adapter/Module/Repository/ModuleRepository.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Module/Repository/ModuleRepository.php]: Nope, that's the reason why there is a fallback because it can happen and it would fail
But the method name is wrong indeed

File: src/Adapter/Module/Repository/ModuleRepository.php (hunk 2 above)
Comment (jolelievre) [reply src/Adapter/Module/Repository/ModuleRepository.php]: Same

File: src/Adapter/Module/Repository/ModuleRepository.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/Module/Repository/ModuleRepository.php]: Oh but it made me realize this method makes no call to the DB, so I should remove this check

**Comment by jolelievre** [comment]
@Hlavtox I'm not sure about which problem you mention, but that's the idea yes During the `Module::install` process the module's catalogues were not loaded so no translations were available

The PR includes two improvements:
- the catalogues of modules present in the modules folder are always loaded even if they are not installed, so they are always available
- during the installation the catalogues from module being installed is dynamically loaded right before its install process is launched, this is needed in addition to the previous point for the module uploaded by zip (since they are not in the module folder when the process begins)

**Comment by Hlavtox** [comment]
@jolelievre I don't know if there is an issue open about this.

If you unzip a module using new translation system to modules directory and go to BO > Module manager, you will see that the module name and description is in English, even if you have backoffice in other language and there are XLF files for it. After installing the module, the translations appear.

Your PR should fix this. :-)

**Comment by Hlavtox** [comment]
@jolelievre I don't know if there is an issue open about this.

If you unzip a module using new translation system to modules directory and go to BO > Module manager, you will see that the module name and description is in English, even if you have backoffice in other language and there are XLF files for it. After installing the module, the translations appear.

Your PR should fix this. :-)

**Comment by jolelievre** [comment]
@Hlavtox I just tested it and yes it works thanks to the first bugfix (load catalogue for all present modules)

**Review by nicosomb — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@jolelievre awesome

**Review by boherm — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @jolelievre, 
Before installing the PR, when I install the module and change the language to Spanish on the home page, for example, I get this: There is no translation for this module 
Capture d’écran 2025-03-12 à 12 04 11

When I install the PR and module I get the same module that is not translated, is this normal?

Capture d’écran 2025-03-12 à 12 33 57

**Comment by jolelievre** [comment]
Hi @SiraDIOP just to give context for other contributors, as we discussed the block you are showing is handled by the Classic Edition module, it's a bug on the module level not related to the scope of this PR 😉

**Comment by SiraDIOP** [comment]
Hello @jolelievre , 
Thanks you ^^. 

All done the PR is OK for me ^^ .

**Review by SiraDIOP — APPROVED** [review]
