### PR TITLE
Don't reassign global vars in front controller

### LINKED ISSUE #28067: Don't reassign cart global vars in front controller
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Don't reassign cart global vars in front controller.

### Expected behavior

_No response_

### Steps to reproduce

Remove (smarty assign) cart presented in order or cart  front controller and see that it does not change anything in FO you can always access cart presented object in smarty. Because it has already been assigned in the front controller parent class

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Don't reassign global vars in front controller. This change fixes minor code issues I found while working on another bug. Already assigned in `FrontControllerCore::assignGeneralPurposeVariables()`
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28067
| How to test?      | Make cart and order controller work fine :)
| Possible impacts? | Make cart and order controller work fine :)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27227)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
@PululuK so the `$cart` and `$static_token` vars already exist, is that right? and they are the same object?

File: controllers/front/CartController.php [hunk 1]
```diff
@@ -105,15 +105,8 @@ public function initContent()
         if (!Tools::getValue('ajax')) {
             $this->checkCartProductsMinimalQuantities();
         }
-        $presenter = new CartPresenter();
-        $presented_cart = $presenter->present($this->context->cart, $shouldSeparateGifts = true);
```
Comment (kpodemski) [inline controllers/front/CartController.php:112]: By default it's:

`public function present($cart, $shouldSeparateGifts = false)`

And in the `FrontController`:
`'cart' => $this->cart_presenter->present($this->context->cart),`

**Review by kpodemski — CHANGES_REQUESTED** [review]
I think you've changed the behavior because the second argument has a different value now.

File: controllers/front/CartController.php (hunk 1 above)
Comment (Hlavtox) [reply controllers/front/CartController.php:112]: @kpodemski Keep it off, gift separation is not working and results in wrong totals - https://github.com/PrestaShop/PrestaShop/issues/20564.

That's why the gifts are turned off in FrontController.

**Comment by Hlavtox** [comment]
@kpodemski It was ignored and overriden by `'cart' => $this->cart_presenter->present($this->context->cart)`, his solution is correct and retains the original behavior.

**Before**
default

**After**
after

**Comment by Hlavtox** [comment]
@PululuK Do you think you could also fix it in ps_shoppingcart? It also presents the cart, while it was already once presented in FrontController.
https://github.com/PrestaShop/ps_shoppingcart/blob/5ecb9ae77bf58ab2e3254ebda76404425d2ac643/ps_shoppingcart.php#L96

**This would further improve performance**
level 2

**Comment by kpodemski** [comment]
Thanks for the detailed feedback @Hlavtox

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
LGTM, @Hlavtox 's suggestion does make sense, what do you think @PululuK ?

**Comment by PululuK** [comment]
> LGTM, @Hlavtox 's suggestion does make sense, what do you think @PululuK ?

This can be done in another PR.

**Comment by PululuK** [comment]
@matks @kpodemski  in reality these variables have never been used. See `FrontControllerCore::assignGeneralPurposeVariables()` called in `FrontControllerCore::initContent()`.

these vars they are overwritten when we load at this level in the child classes. Ex.:

```php

class CartControllerCore extends FrontController
{
   /**
     * @see FrontController::initContent()
     */
    public function initContent()
    {
        parent::initContent(); // will overwrite the vars.
    }

}

**Comment by Hlavtox** [comment]
I don't think so @PululuK, because:

For example tha $cart variable and gift parameter when calling present. In cart controller, gifts were enabled, in frontcontroller, gifts were disabled. The result was - disabled.

I know that, because when you enabled gifts in frontcontroller, they popped up.

**Comment by PululuK** [comment]
> I don't think so @PululuK, because:
> 
> For example tha $cart variable and gift parameter when calling present. In cart controller, gifts were enabled, in frontcontroller, gifts were disabled. The result was - disabled.
> 
> I know that, because when you enabled gifts in frontcontroller, they popped up.

have you encountered any unexpected behavior with this PR?

**Comment by Hlavtox** [comment]
No, because you left the original behavior in Frontcontroller. :) I think, we just misunderstood man and we mean the same thing. 😄

Anyway, it works perfectly, good job!

**Review by atomiix — DISMISSED** [review]

**Comment by marwachelly** [comment]
Hello, 

The issue is missing. As discussed with @Robin-Fischer-PS  It seems that it is a technical issue. we think it can be tested by a dev.

Thanks,

**Comment by PululuK** [comment]
Hi guys,

The news ?

**Comment by Hlavtox** [comment]
@PululuK Just make the related issue, or it will wait another month for QA

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Needs a rebase

**Comment by PululuK** [comment]
> Needs a rebase

@Progi1984  done !

**Review by kpodemski — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hello !

 @PrestaShop/prestashop-core-developers Could you please validate the related issue : https://github.com/PrestaShop/PrestaShop/issues/28067

And then do a QA by dev on this PR ?

Thanks ;)

**Comment by kpodemski** [comment]
@Robin-Fischer-PS 

It's a refacto. We spoke recently with @matks that refacto doesn't require adding an Issue but providing "How to test" and "Possible impacts" is always good. 

This change aims to simplify code, but it might impact the default behavior of Cart and Ordering features.

**Comment by matks** [comment]
@Robin-Fischer-PS Issue approved, so PR can be tested by dev? I add "Waiting for dev" and "Waiting for QA"

**Comment by Robin-Fischer-PS** [comment]
@matks  OK for QA by dev :)

**Review by MeKeyCool — COMMENTED** [review]
I don't understand why you don't replace  
```php
$cartPresenter = new CartPresenter();
$presentedCart = $cartPresenter->present($this->context->cart);
```
by
```php
$this->context->cart
```
at lines 137 and 548.

:thinking: Maybe your PR concerns only a weird behavior with `$this->context->smarty->assign(...` ?

**Comment by Hlavtox** [comment]
@MeKeyCool Context doesn't contain the presented cart, but the basic Cart object.

**Comment by MeKeyCool** [comment]
> @MeKeyCool Context doesn't contain the presented cart, but the basic Cart object

Then when you replace 
```php
if (count($presented_cart['products']) > 0) {
```
by
```php
if ($this->context->cart->hasProducts()) {
```
It is not refacto only, is it ? :thinking:
Why do you change behavior ? Are you fixing a bug ?

**Comment by kpodemski** [comment]
@MeKeyCool 

it's not a change of behavior. The idea is not to use the Presenter when it's not needed

Presenters are wrappers around objects to properly sanitize the data for the view, etc. It wasn't needed to use the Presenter in both of these places.

I'd highly suggest you checking Presenters in the core and how they work, it will allow you to understand the change better here.

**Comment by MeKeyCool** [comment]
> @MeKeyCool
> 
> it's not a change of behavior. The idea is not to use the Presenter when it's not needed
> 
> Presenters are wrappers around objects to properly sanitize the data for the view, etc. It wasn't needed to use the Presenter in both of these places.
> 
> I'd highly suggest you checking Presenters in the core and how they work, it will allow you to understand the change better here.

Thanks a lot for explanations @kpodemski ^^ I note that I have to update my knowledge about Presenters ^^

So If I understand well, at lines 137 and 548 we need to sanitize data but not in the code updated by @Hlavtox  ?
Did I get the point this time ? ^^'

**Comment by kpodemski** [comment]
@MeKeyCool 

If you want to run a method to check if the Cart has any product, you don't need to have the output formatted by the Presenter. `$this->context->cart` gives you access to the `Cart` class instance, `Presenter` gives you `view-ready` Cart class instance

**Comment by Hlavtox** [comment]
@MeKeyCool I dont know what I have to do with this PR bro 😁

The point of this PR is not to present (enrich) the cart object twice, it already makes the shop a turtle, no need to do it three times. :-)))

**Review by matks — APPROVED** [review]
Code is valid ✅ and behavior seems OK as far as I can see ✅

**Comment by matks** [comment]
Thank you @PululuK
