### PR TITLE
Fix exception during profil edition if invalid field given with avatar

### LINKED ISSUE #28253: BO > Profile - Exception is displayed when adding invalid field and choosing avatar
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When I edit my Profile with an invalid last name and an avatar, I get an exception `An exception has been thrown during the rendering of a template`.

https://user-images.githubusercontent.com/16019289/163202458-698882e4-da2e-484b-8d13-27429b9a55c8.mov

Screenshot 2022-04-13 at 16 25 42

Tested in local and prod env.

Only reproduced on develop branch. PS 1.7.8.x is OK

### Expected behavior

An exception shouldn't be displayed.
Only the message alert `The "Last name" field is invalid.`

### Steps to reproduce

1. edit last name with invalid string
2. add a profile picture
3. save
4. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | A weird 500 error occurred during profile edition if an avatar and an invalid field was given.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28253.
| Related PRs       | /
| How to test?      | cf. #28253 
| Possible impacts? | Really low risk.

I am not satisfied by this bug fix but I added a full comment to explain the problem. I think solving `$_FILES` consistency with `AbstractImageUploader` and `FormBuilder` behavior would induce too much work for this simple bug.
Maybe I don't know some easy trick so feel free to suggest any better solution :blush:. 

After some exchange with maintainers, I created this issue : #28664 . Let's think about it and prioritize it.

### CODE REVIEW

**Comment by kpodemski** [comment]
I think this error is similar to the one I fixed some time ago
https://github.com/PrestaShop/PrestaShop/pull/24823

I remember there was idea to improve this behavior for every controller that handles images

**Comment by MeKeyCool** [comment]
> I think this error is similar to the one I fixed some time ago #24823
> 
> I remember there was idea to improve this behavior for every controller that handles images

Thanks for the link @kpodemski , do you know if a discussion is shared somewhere about this refactoring ?
Shouldn't it be integrated with https://github.com/PrestaShop/PrestaShop/issues/27318 ?

File: src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php [hunk 1]
```diff
@@ -160,6 +171,12 @@ public function update($id, array $data)
             ->setHasEnabledGravatar((bool) $data['has_enabled_gravatar'])
         ;
 
+        /** @var UploadedFile $uploadedAvatar */
+        $uploadedAvatar = $data['avatarUrl'];
+        if ($uploadedAvatar instanceof UploadedFile) {
+            $this->imageUploader->upload($id, $uploadedAvatar);
+        }
+
```
Comment (jolelievre) [inline src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php]: I think you could even move this even lower after the `$this->bus->handle($command);` no?
To make sure the command has been executed correctly before trying to handle the image upload.

Unless some validation midway prevents you from doing it?

Comment (MeKeyCool) [reply src/Core/Form/IdentifiableObject/DataHandler/EmployeeFormDataHandler.php]: Yep I was focused on my problem and didn't think about the rest of the function...
Thanks for advice ^^

**Review by jolelievre — DISMISSED** [review]
Thanks @MeKeyCool

**Review by Amoifr — COMMENTED** [review]
Except the yaml shaping error noticed .... It seems to be going on right way

**Review by jolelievre — APPROVED** [review]
Thanks @MeKeyCool

**Review by matthieu-rolland — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @MeKeyCool 

I have checked this PR. The issue is fixed.

-Check with different languages (RTL and no RTL) : OK
-Check with multistore : OK
-Check with different browsers (Chrome & Firefox) : OK

https://user-images.githubusercontent.com/92912932/179740253-21a8d2a5-61e0-4810-8345-9485736699a6.mp4

image


So, it's QA :heavy_check_mark: 

Thanks!

**Comment by matthieu-rolland** [comment]
thank you @MeKeyCool and @HanaRebaiQA 👍
