### PR TITLE
Ignore attribute_quantity if stock management disabled

### LINKED ISSUE #30179: BO - Unable to update settings for products with combinations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

error-1

Tested in fresh installation of PS 8.0.0.

When Stock management is disabled, the products having combinations is showing error while saving any of its data. I tested it with default (demo) products as well as new products.
Simple products are working fine.

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > Shop Parameters > Product Settings. Disable the Stock management option.
2. Go to BO > Catalog > Products. Edit any product which has combinations.
3. Click on "Combinations" tab, edit price impact field or any data in the combination and click "Save".
4. Error showing "Unable to update settings" as in above screenshot.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3.21

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by bibips**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When stock management is disabled, it's impossible to create a product with combinations.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Disable stock management, create a product with declinaison and save
| Fixed ticket?     | Fixes #30179

### CODE REVIEW

**Comment by bibips** [comment]
Static Analysis failed on code doesn't write by myself `ConfigurationLegacy`. Is it normal ?
Does a documentation exist to manage the configuration with a Symfony service ?

```
//force virtual product feature
ConfigurationLegacy::updateGlobalValue('PS_VIRTUAL_PROD_FEATURE_ACTIVE', '1');
```

**Comment by 0x346e3730** [comment]
Hello @bibips and thank you for your contribution !
It is indeed not related to your PR, ping @FabienPapet is it a miss in the baseline of PHPStan or is it a usecase that has been missed ? PHPStan configuration is like this for those errors:
```
disallowIn:
    - src/PrestaShopBundle/*
    - src/Core/*
allowIn:
    - src/Adapter/*
    - src/PrestaShopBundle/Install/*
```

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php [hunk 1]
```diff
@@ -370,7 +370,9 @@ public function getModelData($form_data, $isMultiShopContext = false)
             $form_data['combinations'][$k]['attribute_unity'] = abs(
                 $this->floatParser->fromString($combination['attribute_unity'])
             );
-            $form_data['combinations'][$k]['attribute_quantity'] = $this->floatParser->fromString($combination['attribute_quantity']);
+            if (ConfigurationLegacy::get('PS_STOCK_MANAGEMENT')) {
```
Comment (0x346e3730) [inline src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Hey @bibips, thank you for your contribution !
This is now forbidden. It already exists in the file twice and is tolerated but you're adding a new one that triggers PHPStan as you can read more easily in the [action logs](https://github.com/PrestaShop/PrestaShop/actions/runs/4186592753/jobs/7255291051#step:7:59). I am not sure what is the new way to do so tho, I've pinged other developers to come and take a look

**Review by 0x346e3730 — CHANGES_REQUESTED** [review]

**Review by 0x346e3730 — DISMISSED** [review]
lgtm 👍

File: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php (hunk 1 above)
Comment (bibips) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: I did a refactor based on the Symfony service `prestashop.adapter.legacy.configuration` (see https://devdocs.prestashop-project.org/8/development/multistore/shops-configuration/#usage).

`ConfigurationLegacy` is not used in this classe anymore 👍

Comment (0x346e3730) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: Awesome ! Can you then remove in `phpstan-baseline.neon` the lines 1707 to 1711 ?
```

		-
			message: "#^Namespace Configuration is forbidden, No legacy calls inside the prestashop bundle\\. Please create an interface and an adapter if you need to\\.$#"
			count: 2
			path: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
```
No longer needed as you refacto'd the whole file

Comment (bibips) [reply src/PrestaShopBundle/Model/Product/AdminModelAdapter.php]: It's done, thanks for your help

**Review by matthieu-rolland — COMMENTED** [review]
rebase needed 👍

File: phpstan-baseline.neon [hunk 2]
```diff
@@ -1705,11 +1705,6 @@ parameters:
 			count: 2
 			path: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
 
-		-
-			message: "#^Namespace Configuration is forbidden, No legacy calls inside the prestashop bundle\\. Please create an interface and an adapter if you need to\\.$#"
-			count: 2
-			path: src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
-
```
Comment (zuk3975) [inline phpstan-baseline.neon]: this one was introduced here for a reason, you can't just delete it when you don't know what it means or how to fix it :smile:
Instead of deleting this rule, use ShopConfigurationInterface inside AdminModelAdapter, that should solve the problem.

**Review by jolelievre — DISMISSED** [review]
Hi @bibips 

the product page V1 is gonna be deleted in v9, we just didn't take the time to clean those files yet. But fixing this with `develop` as a target will only end up working for nothing.

So the PR is not useful for v9, but I don't know if this kind of fix could be integrated in the coming v8.1 (so you'd have to change the target branch and rebase your PR) which will be the last version using this page. This should be decided by @PrestaShop/product-team (@MatShir maybe you have an opinion on this topic?)

In any case as it is this modification can't be merged, sorry

**Comment by kpodemski** [comment]
@MatShir, I think we should agree on having this fixed in 8.0 or 8.1. Look at the description. Why something like this is considered a Minor issue?

**Comment by bibips** [comment]
I agree with you @kpodemski, this bug does not seem minor to me. Can you tell me the target branch for the rebase ?

**Comment by kpodemski** [comment]
Hi @bibips 

You can rebase your change to the 8.1.x branch. If there will be version 8.0.4, we will cherry-pick your change.

**Comment by MatShir** [comment]
Hi @bibips, 
We are planning a small patch for the 8.0.4. Do you think you could provide the changes for the end of this week or beginning of next week to the 8.0.x? Otherwise, it will have to be on the 8.1.x branch

**Comment by bibips** [comment]
@MatShir @jolelievre rebase on 8.0.x done

**Review by zuk3975 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by boubkerbribri — COMMENTED** [review]
No need for UI tests maintainers approval.

**Review by djoelleuch — APPROVED** [review]
Hello @bibips 
I have tested your PR and it's well fixed !

image

It's QA approved :heavy_check_mark: 
thank you !

**Comment by kpodemski** [comment]
thank you, @bibips - well done 👏🏻 🎉
