### PR TITLE
Fix configure warning when module is disabled or uninstalled

### LINKED ISSUE #28919: BO - Module manager - The module to configure is not removed from the alerts tab after uninstalling it
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After fresh install > In the BO > Modules > Module Manager page > Alerts tab,
Try to uninstall the module `ps_checkpayment` without removing the folder
The alert  `Uninstall action on module ps_checkpayment succeeded.` is well displayed, but the module is not removed from the alerts tab
image
It should be removed as in the PS1786

https://user-images.githubusercontent.com/16067358/176652308-0cad0c82-099a-42fa-a52a-088e5a244f56.mp4

### Expected behavior

As discussed with @MatShir and @atomiix, the module should be removed from the alerts tab

### Steps to reproduce

1. Go to BO > Modules > Module manager > Alerts tab
2. Uninstall the module  `ps_checkpayment` without removing the folder
3. See error > The module is not removed from the alerts tab

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fix configure warning when module is disabled or uninstalled
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28919.
| Related PRs       | 
| How to test?      | See issue
| Possible impacts? |

### CODE REVIEW

File: tests/Unit/Core/Module/ModuleRepositoryTest.php [hunk 1]
```diff
@@ -50,8 +50,17 @@ class ModuleRepositoryTest extends TestCase
         'demo',
     ];
 
+    private const ACTIVED_MODULES = [
```
Comment (matthieu-rolland) [inline tests/Unit/Core/Module/ModuleRepositoryTest.php]:
```suggestion
    private const ACTIVE_MODULES = [
```

I think `actived` doesn't make much sense here, it would be `active` or `activated` ;)

File: tests/Unit/Core/Module/ModuleRepositoryTest.php [hunk 2]
```diff
@@ -110,6 +119,7 @@ public function getModuleMock(string $moduleName): Module
 
         $module->method('getInstance')->willReturn($moduleInstance);
         $module->method('isInstalled')->willReturn(in_array($moduleName, self::INSTALLED_MODULES));
+        $module->method('isActive')->willReturn(in_array($moduleName, self::ACTIVED_MODULES));
```
Comment (matthieu-rolland) [inline tests/Unit/Core/Module/ModuleRepositoryTest.php]: same here

**Review by matthieu-rolland — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @okom3pom 

Thank you for your PR, I tested it and it seems to not correct the issue, as we can see here :

https://user-images.githubusercontent.com/100699445/177583120-9203a07a-7f50-4958-8207-b369f8f341c5.mp4

**Comment by ghost** [comment]
Hello @AureRita 

Regression is when you change the page.

Video 8.0.0 with PR and without

https://user-images.githubusercontent.com/5064590/177721728-35e81fa0-d7d8-4cca-a997-a61b9178b137.mp4

Video 1.7.8

https://user-images.githubusercontent.com/5064590/177723052-cab57222-0e31-460e-98b1-de5f6a865e16.mp4

And it's only with cheque module

I will try to made an other PR in the dev branch, this PR fix only the regression.

**Review by AureRita — APPROVED** [review]
Hi @okom3pom, 

Sorry for my misunderstanding, I think this pr will hide the display of module directly ( without reloading the page), so currently your PR works, as we can see : 

https://user-images.githubusercontent.com/100699445/177729162-f5e63508-fc65-4293-93e2-b961c2341cbc.mp4

**Comment by matks** [comment]
Thank you @okom3pom
