### PR TITLE
Fix dispatched hook on the Grid presenter: action<GridDefinitionId>GridFilterFormModifier

### LINKED ISSUE #13579: Grid presenter hook doesn't respects the documentation
**Describe the bug**
While defining a hook to customize the Grid presentation, the dispatched hook is wrong.

It's not formatted like the other ones, making the use of this hook impossible while using lowercased grid identifiers.

See https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/Presenter/GridPresenter.php#L96 while for others one the Grid identifier is formatted https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/GridFactory.php#L92.

Can we fix this for 1.7.6?

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The dispatched hook doesn't fit what is documented and specified
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no (the hook is not available right now)
| Deprecations? | no
| Fixed ticket? | Fixes #13579
| How to test?  | No need, but you can create a module that hooks to the Logs Grid presenter

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13609)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

File: src/Core/Grid/Presenter/GridPresenter.php [hunk 1]
```diff
@@ -30,6 +30,7 @@
 use PrestaShop\PrestaShop\Core\Grid\Column\Type\Common\PositionColumn;
 use PrestaShop\PrestaShop\Core\Grid\Definition\GridDefinitionInterface;
 use PrestaShop\PrestaShop\Core\Grid\Filter\FilterInterface;
+use Symfony\Component\DependencyInjection\Container;
```
Comment (jolelievre) [inline src/Core/Grid/Presenter/GridPresenter.php:33]: Too bad we don't have another class to use to camelize?

Comment (PierreRambaud) [reply src/Core/Grid/Presenter/GridPresenter.php:33]: Nope, and this is what we are already using https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Grid/GridFactory.php#L92

Comment (jolelievre) [reply src/Core/Grid/Presenter/GridPresenter.php:33]: yes I know, it's just that we were completely framework agnostic until we use this class
not really a problem since it's integrated in the core anyway, but still my heart cries a little.. 🥺

Comment (PierreRambaud) [reply src/Core/Grid/Presenter/GridPresenter.php:33]: :broken_heart:

Comment (mickaelandrieu) [reply src/Core/Grid/Presenter/GridPresenter.php:33]: > yes I know, it's just that we were completely framework agnostic until we use this class
not really a problem since it's integrated into the core anyway, but still my heart cries a little..

Me too, but it's not me but @sarjon who introduced it with the approval of @matks xD

In 1.7.7, we may improve that but for now, we need to provide consistent behavior, isn't it?

**Comment by mickaelandrieu** [comment]
Thanks for the review, this doesn't needs QA approval as it's a cherry pick 👍

File: src/Core/Grid/Presenter/GridPresenter.php (hunk 1 above)
Comment (sarjon) [reply src/Core/Grid/Presenter/GridPresenter.php:33]: > Too bad we don't have another class to use to camelize?

There is option to use `\Doctrine\Common\Inflector\Inflector::camelize()`, but it won't change much right?

> just that we were completely framework agnostic

We were not. :/ Grid already depends on Symfony Form component and Doctrine. In fact, `Core` is not framework agnostic at all. :disappointed: 

> Me too, but it's not me but @sarjon who introduced it with the approval of @matks

I don't think it's worth copy/paste 3rd party lib inside PS, what benefits would that bring? :thinking:

Comment (matks) [reply src/Core/Grid/Presenter/GridPresenter.php:33]: > yes I know, it's just that we were completely framework agnostic until we use this class
> not really a problem since it's integrated in the core anyway, but still my heart cries a little.. 

We are framework agnostic. But we are not component agnostic.
In the Core code written for migration, you'll never find a class using `Symfony\Bundle`. But you'll find `Symfony\Component`. This means that if we want, we can ditch Symfony framework and replace it with Laravel framework. But we still rely on Symfony components (as does Laravel !).

I think this is a fair compromise between coupling matters and code simplicity matters. But if this becomes an issue, we can aim for a full 3rd-party independant Core and rely on interfaces being implemented by external libs, using hexagonal architecture.

I think it's too early to do it 😉 but I'm listening to feedbacks ;) .
