### PR TITLE
Fix group reduction when specific price is set

### LINKED ISSUE #22096: Multicurrencies - BO - Order page - Incorrect Product's total when it is in a category discount for the customer Group
#### Describe the bug

This issue occurs only with a different currency than the default one.
A customer Group has a discount category for example 50% for the Art category
image
In the BO > Orders > Order page > when we Update a product(which is in the category discount) => the product's price is NOK.
If we generate the invoice => total incorrect

#### Steps to Reproduce

1. Go to BO > International > Localization page
2. Import the United States pack
3. Go to the currencies page
4. Edit the $ currency with exchange = 10 (only to visualize the issue)
5. Go shop Parameters > Customer Settings > Groups Tab
6. Edit the customer Group, Add a discount 50% for the Art category
image
7. Go to FO > Art category > Select `$` currency > Add the product `demo_18`to the cart
8. Continue checkout
9. Go to BO > Orders > Open last Order created
image
10. EDit the quantity of the product ordered ( from 1 to 2 form example)
11. Save
12. See error => the product's total is NOK
image
13. Change the status of the Order to Payment accepted
14. Download the invoice
15. See the error
image

1770finalbuild => NOK: https://drive.google.com/file/d/1IYCHdcMkUTZ_G_1K7QsWMywcziDSSc-x/view?usp=sharing

PS:1769 => ok: https://drive.google.com/file/d/1dojva4t7oLJDFw1ZLxiV7RbfzmRCIZUy/view?usp=sharing

#### Additional information

* PrestaShop version: 1770finalbuild1
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Group reduction was applied twice when quantity of a product in an order is updated. To fix it we don't apply category discount if specific price is defined
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22096
| How to test?  | See issue https://github.com/PrestaShop/PrestaShop/issues/22096

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22161)

### CODE REVIEW

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 1]
```diff
@@ -55,6 +58,37 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
         Cache::clean('product_id_tax_rules_group_*');
     }
 
+    /**
+     * @Then The category of product :productName has reduction of :reductionPercent% for the customer :customerReference
+     */
+    public function theCategoryOfProductHasReductionOfForCustomer($productName, $reductionPercent, $customerReference)
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]:
```suggestion
    public function theCategoryOfProductHasReductionOfForCustomer(string $productName, float $reductionPercent, string $customerReference)
```

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 2]
```diff
@@ -55,6 +58,37 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
...
+        $customerId = SharedStorage::getStorage()->get($customerReference);
+        $customer = new Customer((int) $customerId);
+        if (!$customer) {
+            throw new RuntimeException('The customer doesn\'t exist');
+        }
+
+        $groupReduction = new GroupReduction();
+        $groupReduction->id_category = $category->id;
+        $groupReduction->id_group = $customer->id_default_group;
+        $groupReduction->reduction = (float) $reductionPercent / 100;
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]:
```suggestion
        $groupReduction->reduction = $reductionPercent / 100;
```

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature [hunk 3]
```diff
@@ -215,6 +215,54 @@ Feature: Multiple currencies for Order in Back Office (BO)
...
+      | total_products_wt        | 63.60 |
+      | total_discounts_tax_excl | 0.00   |
+      | total_discounts_tax_incl | 0.00   |
+      | total_paid_tax_excl      | 130.00 |
+      | total_paid_tax_incl      | 137.80 |
+      | total_paid               | 137.80 |
+      | total_paid_real          | 0.0    |
+      | total_shipping_tax_excl  | 70.00  |
+      | total_shipping_tax_incl  | 74.20  |
+    And the category of product "Mug The best is yet to come" has no reduction
```
Comment (atomiix) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature]: Maybe add this line as a "Given" in the next Scenario to avoid take that line for a "check" as it's more like a "reset" if I got it right?

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 4]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
         Cache::clean('product_id_tax_rules_group_*');
     }
 
+    /**
+     * @Then The category of product :productName has reduction of :reductionPercent% for the customer :customerReference
+     */
+    public function theCategoryOfProductHasReductionOfForCustomer(string $productName, float $reductionPercent, string $customerReference)
```
Comment (NeOMakinG) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]: The function name looks a bit strange, I can't find what it really does by reading it, and it looks like it's not really doing what the description/function name say

**Review by NeOMakinG — COMMENTED** [review]
I won't block because I'm not really a PHP developer, but added a comment

**Comment by khouloudbelguith** [comment]
Hi @sowbiba,

I have an issue following these steps:

1. Go to BO > International > Localization page
2. Import the United States pack
3. Go to the currencies page
4. Edit the $ currency with exchange = 10 (only to visualize the issue)
5. Go shop Parameters > Customer Settings > Groups Tab
6. Edit the customer Group, Add a discount 50% for the Art category
7. Go to FO > Art category > Select $ currency > Add the product `demo_18` to the cart
8. Continue checkout
9. On the Personnel information page "order as a **guest**"
10. At this step: try to navigate to "Guest Order Tracking" using this URL: shop.com/en/guest-tracking
11. Set the Order Reference: of the last order
12. Set the Email: of the last guest added
13. Click Send
14. Scroll down
15. Transform your guest account into a customer account: Set a password and send 
image
16. Go to BO > Orders > Open last Order created
17. Add `demo_19` to the order
18. See error => the product's total is changed

 
I attached a screen record
https://drive.google.com/file/d/1WKztTVBm93SVulwG1SVdbsATbPmceQAr/view?usp=sharing

PS: there is a difference between updating the same product and adding a product.
If we update the quantity of the product => the price is not changed.

I think, after transforming the gust account to customer => prices should be changed when reloading the page / or do not accept to change the price at first.

Ping @PrestaShop/product-team what do you think?

Thanks!

File: tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature (hunk 3 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature]: to avoid dependencies between scenarii, I can add it in the *Background*

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php (hunk 4 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]: renamed ;)

File: tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature (hunk 3 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_currency.feature]: Done

**Comment by sowbiba** [comment]
> Hi @sowbiba,
> 
> I have an issue following these steps:
> 
> 1. Go to BO > International > Localization page
> 2. Import the United States pack
> 3. Go to the currencies page
> 4. Edit the $ currency with exchange = 10 (only to visualize the issue)
> 5. Go shop Parameters > Customer Settings > Groups Tab
> 6. Edit the customer Group, Add a discount 50% for the Art category
> 7. Go to FO > Art category > Select $ currency > Add the product `demo_18` to the cart
> 8. Continue checkout
> 9. On the Personnel information page "order as a **guest**"
> 10. At this step: try to navigate to "Guest Order Tracking" using this URL: shop.com/en/guest-tracking
> 11. Set the Order Reference: of the last order
> 12. Set the Email: of the last guest added
> 13. Click Send
> 14. Scroll down
> 15. Transform your guest account into a customer account: Set a password and send
>     image
> 16. Go to BO > Orders > Open last Order created
> 17. Add `demo_19` to the order
> 18. See error => the product's total is changed
> 
> I attached a screen record
> https://drive.google.com/file/d/1WKztTVBm93SVulwG1SVdbsATbPmceQAr/view?usp=sharing
> 
> PS: there is a difference between updating the same product and adding a product.
> If we update the quantity of the product => the price is not changed.
> 
> I think, after transforming the gust account to customer => prices should be changed when reloading the page / or do not accept to change the price at first.
> 
> Ping @PrestaShop/product-team what do you think?
> 
> Thanks!



EDIT : the bug happens because the customer group changed. The guest is now a regular customer, he doesn't belong to "Guest" group anymore so the category discount is not applied for the 2nd line. For the orderDetail which quantity is updated, the price in the form field is considered as specific price. The question is "Can the prices be changed after the order is validated?"

**Comment by MatShir** [comment]
The issue shown by @khouloudbelguith happens because the page introduces new behavior. The product price is updated when the cart is updated so if the product has a new price and we change the quantity then the price of the product is updated. 
IMO, this issue is out of PR scoop and might be an excepted behavior (still need to be studied)

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 5]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
...
+    /**
+     * @Then The category of product :productName has reduction of :reductionPercent% for the customer :customerReference
+     */
+    public function addReductionOnProductCategoryForCustomerGroup(string $productName, float $reductionPercent, string $customerReference)
+    {
+        $productId = $this->getProductIdByName($productName);
+
+        $product = new Product($productId);
+        $category = new Category($product->id_category_default);
+        if (!$category) {
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]: Wrong way : `$category` will be an object !

**Review by Progi1984 — DISMISSED** [review]
Need a fix in `tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php`

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php (hunk 5 above)
Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]: Fixed : I use Category::categoryExists instead

Comment (sowbiba) [reply tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]: And I did the same fix for customer existence check

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 6]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
         Cache::clean('product_id_tax_rules_group_*');
     }
 
+    /**
+     * @Then The category of product :productName has reduction of :reductionPercent% for the customer :customerReference
```
Comment (atomiix) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]:
```suggestion
     * @Given The category of product :productName has reduction of :reductionPercent% for the customer :customerReference
```

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 7]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
...
+
+        if (!$groupReduction->add()) {
+            throw new RuntimeException('Cannot add group reduction to database');
+        }
+
+        GroupReduction::resetStaticCache();
+    }
+
+    /**
+     * @Then The category of product :productName has no reduction
```
Comment (atomiix) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]:
```suggestion
     * @Given The category of product :productName has no reduction
```

File: src/Adapter/Order/AbstractOrderHandler.php [hunk 8]
```diff
@@ -325,7 +326,10 @@ protected function getProductRegularPrice(
             false,
             $order->id_customer, // We still use the customer ID in case this customer has some special prices
             null, // But we keep the cart null as we don't want this order overridden price
-            $order->{Configuration::get('PS_TAX_ADDRESS_TYPE', null, null, $order->id_shop)}
+            $order->{Configuration::get('PS_TAX_ADDRESS_TYPE', null, null, $order->id_shop)},
+            $specificPriceOutput,
```
Comment (jolelievre) [inline src/Adapter/Order/AbstractOrderHandler.php]: Since you don't use the output you can use `null` here

File: src/Adapter/Order/AbstractOrderHandler.php [hunk 9]
```diff
@@ -325,7 +326,10 @@ protected function getProductRegularPrice(
...
+            true,
+            false
```
Comment (jolelievre) [inline src/Adapter/Order/AbstractOrderHandler.php]: Maybe add a comment to indicate we explicitly ask for the price without group reduction?

Although I'm worried about this one because if we want to add a product that has a group reduction then we can't do it by default, or we can but it would be considered as a specific price

**Review by jolelievre — COMMENTED** [review]
A few comments, also as I said in another comment this might be partially fixed by https://github.com/PrestaShop/PrestaShop/pull/22299

At least it will have some impact since we don't really on SpecificPrice any more, so it might be worth waiting for the other PR to be merged first and rebase to check if the modifications from this PR are still necessary

If the bug is fixed we will still need the behat tests from this PR anyway

File: src/Adapter/Order/AbstractOrderHandler.php (hunk 8 above)
Comment (sowbiba) [reply src/Adapter/Order/AbstractOrderHandler.php]: the parameter is passed by reference, I can only use a variable, even if it's null

File: src/Adapter/Order/AbstractOrderHandler.php (hunk 9 above)
Comment (sowbiba) [reply src/Adapter/Order/AbstractOrderHandler.php]: This method `getProductRegularPrice` is only used in `updateSpecificPrice` which is called in `AddProductToOrderHandler` and `UpdateProductInOrderHandler`
When we add or update a product in order, the prices are given in parameter, and they are taken as they are, so if the product has group reduction, it has to be included in the price given

You are right, it will be in all cases saved as a specific price

Comment (sowbiba) [reply src/Adapter/Order/AbstractOrderHandler.php]: For the product add for example, if the interface is used, the user will hit SearchProductHandler::getProductPriceForOrder to get the product details he wants. This method will return the effective product price, group reduction included

**Comment by sowbiba** [comment]
After discussions, we better wait for https://github.com/PrestaShop/PrestaShop/pull/22299 by @jolelievre 
I'll re-test the issue and if needed rework this PR. Anyway, we will keep the behat to validate the behaviour

**Comment by jolelievre** [comment]
Hi @sowbiba 

PR https://github.com/PrestaShop/PrestaShop/pull/22299 vas validated and merged, it seems it fixes your issue #22096 so good news ^^
However your PR is still interesting because you integrated behat tests in it that are not in the branch, so could you rebase your branch and clean your modifications?

File: classes/GroupReduction.php [hunk 10]
```diff
@@ -285,4 +285,12 @@ public static function deleteCategory($id_category)
 
         return true;
     }
+
+    /**
+     * Reset static cache (mainly for test environment)
+     */
+    public static function resetStaticCache()
+    {
+        GroupReduction::$reduction_cache = [];
```
Comment (jolelievre) [inline classes/GroupReduction.php]:
```suggestion
        static::$reduction_cache = [];
```

Comment (jolelievre) [reply classes/GroupReduction.php]: Could you also add this `GroupReduction::resetStaticCache()` in `CommonFeatureContext::clearCache`

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 11]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
         Cache::clean('product_id_tax_rules_group_*');
     }
 
+    /**
+     * @Given The category of product :productName has reduction of :reductionPercent% for the customer :customerReference
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]:
```suggestion
     * @Given The default category of product :productName has a group reduction of :reductionPercent% for the customer :customerReference
```

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 12]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
...
+
+        if (!$groupReduction->add()) {
+            throw new RuntimeException('Cannot add group reduction to database');
+        }
+
+        GroupReduction::resetStaticCache();
+    }
+
+    /**
+     * @Given The category of product :productName has no reduction
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php]:
```suggestion
     * @Given The default category of product :productName has no group reduction
```

**Comment by sowbiba** [comment]
I confirm the bug is resolved by your PR @jolelievre 
I removed the modifications and keep only the behat test.

File: classes/GroupReduction.php (hunk 10 above)
Comment (sowbiba) [reply classes/GroupReduction.php]: already done

**Review by jolelievre — APPROVED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php [hunk 13]
```diff
@@ -55,6 +58,53 @@ public function setProductTaxRulesGroup(string $taxRulesGroupReference, string $
...
+        if (!Customer::customerIdExistsStatic($customerId)) {
+            throw new RuntimeException('The customer doesn\'t exist');
+        }
+
+        $customer = new Customer((int) $customerId);
+
+        $groupReduction = new GroupReduction();
+        $groupReduction->id_category = $product->id_category_default;
+        $groupReduction->id_group = $customer->id_default_group;
+        $groupReduction->reduction = $reductionPercent / 100;
```
Comment (PierreRambaud) [inline tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php:83]: It's already a percent in the Given sentence :thinking:

Comment (PierreRambaud) [reply tests/Integration/Behaviour/Features/Context/Domain/ProductFeatureContext.php:83]: Ok, I get it, it's how it's used in the Core :sweat_smile:

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
No need QA, the PR from @jolelievre already fix the issue, only behat tests were edited
