### PR TITLE
Product multishop prices

### LINKED ISSUE #13007: Function setFieldsToUpdate() does not work for single database table
**Describe the bug**
While you want to simply one field while update an ObjectModel, you could use the setFieldsToUpdate() method. But this one need to have a _shop table associated, to work.

Instead, the ObjectModel is whole saved.

**To Reproduce**
1. Instanciate an ObjectModel (which have no _shop table associated !)
2. Change somes properties
3. Apply the setFieldsToUpdate() method for one of theses modified changes
4. Update the ObjectModel
5. See that the ObjectModel is whole saved, instead of the only field to update.

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: N/A

### LINKED ISSUE #18919: Customization parameters lost on product with multistore
#### Describe the bug

When creating a shop in multistore, if importing Product Data from another shop, the customizable products are not working well anymore : 
- On the newly created shop, the customizable products are created, but without the customization parameters
- If editing the customization parameters on the newly created shop, it will erase these parameters from the "original" shop (and vice versa, if editing the original product, it will erare the customization parameters from the new shop)

#### Expected behavior

- When creating a shop with import of products, the customization parameters must be maintained.
- When editing a customizable product which is shared between several shops, with a "one shop" context, the new customization parameters should be saved on this shop only. All others parameters on others shops should not be erased or modified.

#### Steps to Reproduce

1. Create a product with customization parameters (text and/or file)
2. Enable Multistore
3. Create a new shop, importing product data from actual shop
4. Go to the newly created shop context, to the customizable product : The parameters are not present
5. Add new customization parameters (on this shop context) : It's OK
6. Go to original shop context : Customization parameters are erased.

**Screenshots**

https://drive.google.com/file/d/1J0GYXEx-qKXqjrIC4FNY5ARwcU2eufxT/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.6.5, 1.7.7 at least
* PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR introduces the multistore feature into the new product page, for now it only handles the fields related to prices but it brings a few core architectural elements to handle other multistore fields:<br>- a form extension to configure and add automatically a checkbox to handle override for all shops<br>- `AbstractObjectModelRepository` can now get and update an entity with its value for a specific shop<br>- `GetProductForEditing` now returns data for a specific shop (the `ShopId` parameter is mandatory regardless of the shop configuration or the context)<br>- new `CopyProductToShop` allows to copy values between several shops (the feature is not completely finished, only direct product fields are handled for now The feature will need to be enriched to handle the product's associations in future PRs (combinations, images, suppliers, ...)<br>- `UpdateProductPricesHandler` is the first handler to handle multi shop command<br>- `PricesCommandsBuilder` is the first builder to handle multishop, it is also the first one to use the new `CommandAccessor` component which simplifies building CQRS commands (for single shop and/or multishop)<br>- the multishop header was improved to allow hiding it by clinking outside of it
| Type?             | new feature
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #18919 and #13007
| How to test?      | Create two shops, then in the new product page edit a product and change the price for each shop (with different values) the price should be different If you click on the override checkbox every shop associated to the product is updated You might encounter some issues related with the stock, especially if you have a shop group which shares its stock (more details here https://github.com/PrestaShop/PrestaShop/issues/26738) This is not related to the scope of this PR, it won't be fixed now but when we deal with multishop for Product's stock The popup validation for multishop is not implemented yet, it will be added in another PR On creation we automatically assign the created product to the shop from context You cannot edit the shop associations yet
| Possible impacts? | The modifications change a few architecture but are mostly focused on the pricing tab so it shouldn't impact the others

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25464)

### Partial update fix

This PR includes a fix in `ObjectModel` a historical bug (several years old) was messing with the partial update feature, more info in this comment https://github.com/PrestaShop/PrestaShop/pull/25464/files#r701331675

### Wholesale price

There was also a bug related to wholesale price, when the product had assigned suppliers it could not be modified in the Pricing tab because it was overridden by the default supplier's price. So now the CQRS commands keep both fields in sync, and in the page the input fields are also synced when modified by the user.
(This new behaviour needs to be validated by the @PrestaShop/product-team )

## New multistore management in product page

In the new product page the design and the way the multishop feature is handled in the product page has been rethought, because the previous page was confusing (at best) and buggy in some ways, this resulted in merchant doing modifications without realizing the consequences of their actions sometimes.

To simplify the multishop feature here are the most important changes.

### No more All shops mode

The page is no longer accessible in the "All shops" context, the reason behind this is to avoid merchants modifying all their shops at once without realizing it, and more importantly, We can't really know which data is supposed to be displayed as the default one.

Note that this was true when we first thought about the new page because we didn't know about the `id_shop_default`, this could now serve as a base in the All shops mode But regardless in v8.0 the all shops mode won't be handled because it requires more reflection about how it would be improved to avoid any confusion.

Besides there is nowhere a feature that allows choosing which shop should be considered the default one for a product (only assigned on the creation and that's it) And there is not a viable system of inheritance or override in the way Product handles multishop (basically the data is duplicated and copied for each shop individually).

For all those reasons, and more, the "All shops" context edition will then be disabled in the new product page but to compensate the single shop mode has been improved.

### Single shop mode

So now a product can only be edited in single shop mode, but it would troublesome if you had to go through all of your shops when you wish to edit one data with the same value everywhere. This is why from now on each multishop field (not all the product's fields are multishop) will have an assigned checkbox that allows you to "Apply changes to all stores" by checking this you will update all the stores for **this field only**.

Capture d’écran 2021-09-10 à 12 13 47

We decided on this feature because the previous "All shops" mode modified the whole product for all the shops, but it didn't allow you to fine-tune which part you wished to update. With this new single shop page, you can now decide more precisely if your modification is "local" (only the shop in the context) or "global" (applied to all the associated shops of this product). So even if the "All shops" mode is not accessible anymore, you can now make "bulk edition" from the single shop mode with more control and more knowledge of what you are actually modifying.

### Shop association management

Additionally, something that was not possible previously, you will now be able to easily manage which shops are associated to a product. And you also will be able to transfer/copy data from one shop to another, as well as remove the association between a product and a shop. This isn't handled in this PR yet but you can see a preview of what it will look like:

Capture d’écran 2021-09-10 à 12 48 01

As a result, if a product is not associated with a shop you won't be able to access its edit page when the said shop is selected. You will need to associate/transfer it previously. Previously you could access the product in any shop regardless of it being associated or not, but it resulted in most of the fields being empty which is confusing and can lead to many mistakes.

### Popup validation

Additionally, on form submit a popup will now be displayed to summarize what was modified and which shops will be affected by the changes. Though this popup is not completely specified and not implemented in this PR so I won't give more details for now.

### CODE REVIEW

File: src/Adapter/AbstractObjectModelRepository.php [hunk 1]
```diff
@@ -95,6 +116,43 @@ protected function getObjectModel(int $id, string $objectModelClass, string $exc
...
+        $primaryColumn = $modelDefinition['primary'];
+
+        $query = new DbQuery();
+        $query
+            ->select('e.`' . $primaryColumn . '` as id')
+            ->from($objectTable . '_shop', 'e')
+            ->where('e.`' . $primaryColumn . '` = ' . $id)
+            ->where('e.`id_shop` = ' . $shopId->getValue())
+        ;
+        $sql = $query->build();
```
Comment (Progi1984) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
```

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+@reset-database-before-feature
+@product-multi-shop
+@update-multi-shop-management
+Feature: Copy product from shop to shop.
+  As a BO user I want to be able to copy product from shop to shop.
+
+  Background:
+    Given shop "shop1" with name "test_shop" exists
+    And shop group "default_shop_group" with name "Default" exists
+    And I add a shop "shop2" with name "default_shop_group" and color "red" for the group "default_shop_group"
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature]: the shop name is the same as the shop group name ?

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+      | tax rules group    | US-AL Rate (4%) |
+      | on_sale            | true            |
+      | wholesale_price    | 70              |
+      | unit_price         | 10              |
+      | unity              | bag of ten      |
+      | unit_price_ratio   | 10.099          |
+    And product product1 is not associated to shop shop3
+    And product product1 is not associated to shop shop4
+    # Now modify and copy the values but this time the shop is already associated so it is an update
+    When I update product "product1" prices with following information:
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature:66]: How can we know that the current shop is `shop1` ?

**Review by Progi1984 — COMMENTED** [review]
Some feedbacks

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php [hunk 4]
```diff
@@ -46,30 +57,77 @@ public function buildCommands(ProductId $productId, array $formData): array
...
         if (isset($priceData['retail_price']['price_tax_excluded'])) {
-            $command->setPrice((string) $priceData['retail_price']['price_tax_excluded']);
+            if (!empty($priceData['retail_price']['multistore_override_all_price_tax_excluded'])) {
+                $this->getAllShopsCommand($productId)->setPrice((string) $priceData['retail_price']['price_tax_excluded']);
+            } else {
+                $this->getSingleCommand($productId)->setPrice((string) $priceData['retail_price']['price_tax_excluded']);
+            }
         }
         if (isset($priceData['retail_price']['ecotax'])) {
-            $command->setEcotax((string) $priceData['retail_price']['ecotax']);
```
Comment (matks) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php:55]: If we do
```
$command = $this->getSingleCommand($productId);
```
then we can keep current line

File: src/PrestaShopBundle/Form/Admin/Extension/MultistoreOverridableExtension.php [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+use Symfony\Component\Form\AbstractTypeExtension;
+use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
+use Symfony\Component\Form\Extension\Core\Type\FormType;
+use Symfony\Component\Form\FormBuilderInterface;
+use Symfony\Component\Form\FormInterface;
+use Symfony\Component\Form\FormView;
+use Symfony\Component\OptionsResolver\OptionsResolver;
+use Symfony\Contracts\Translation\TranslatorInterface;
+
+class MultistoreOverridableExtension extends AbstractTypeExtension
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Extension/MultistoreOverridableExtension.php]: We need to describe the goal of this class.

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 6]
```diff
@@ -0,0 +1,306 @@
...
+        $qb
+            ->update($this->dbPrefix . 'product_shop')
+            ->where('id_shop = :id_shop')
+            ->where('id_product = :id_product')
+            ->setParameter('id_shop', $targetShopId->getValue())
+            ->setParameter('id_product', $productId->getValue())
+        ;
+
+        $queryValues = $this->formatQueryValues($fields);
+        foreach ($queryValues as $column => $value) {
```
Comment (matks) [inline src/Adapter/Product/Update/ProductShopUpdater.php]: So we fully avoid the use of ObjectModel here? That is a bold move 😄

Comment (matks) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: I'm not against it, I just hope it'll work without issues 👀

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php [hunk 7]
```diff
@@ -30,12 +30,23 @@
...
 /**
  * Builder used to build UpdateProductPricesCommand
  */
-class PricesCommandsBuilder implements ProductCommandsBuilderInterface
+class PricesCommandsBuilder extends MultistoreCommandsBuilder implements ProductCommandsBuilderInterface
 {
+    /**
+     * @var UpdateProductPricesCommand
+     */
+    private $singleShopCommand;
```
Comment (matks) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php]: Why keep the two separate? We will never have a part of the form submitted for single shop and another part submitted for all shops?

**Review by matks — COMMENTED** [review]
Overall review: I'm OK with the concept. Added a question about MultistoreCommandsBuilder to be sure I understand the strategy.

The only thing I'm afraid of is the mechanisms used to add checkboxes. We did it in an abstract a-little-bit-of-magic way and it could make it harder to debug than plain simple

```
if ($multistoreIsEnabled} { 
  $this->addCheckboxes();
}
```
But at this point it's too early to know whether this is over-engineered or just fine.

File: src/Adapter/AbstractObjectModelRepository.php [hunk 8]
```diff
@@ -66,15 +72,30 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
      * @param string $objectModelClass
      * @param string $exceptionClass
+     * @param ShopId|null $shopId
      *
      * @return ObjectModel
      *
      * @throws CoreException
      */
-    protected function getObjectModel(int $id, string $objectModelClass, string $exceptionClass): ObjectModel
+    protected function getObjectModel(int $id, string $objectModelClass, string $exceptionClass, ?ShopId $shopId = null): ObjectModel
```
Comment (eternoendless) [inline src/Adapter/AbstractObjectModelRepository.php]: IMO this calls for a `NoShopId` class and this method issuing a deprecated soft error when passed null.

Comment (eternoendless) [reply src/Adapter/AbstractObjectModelRepository.php]: Now that I think of it, I can't find a scenario where you wouldn't need the shop id, if you pass null then you're just leaving it up to Context, so you can leave it nullable for backward compatibility but you must issue a deprecation error when null.

File: src/Adapter/AbstractObjectModelRepository.php [hunk 9]
```diff
@@ -66,15 +72,30 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+            if (null !== $shopId) {
+                $this->checkShopAssociation($id, $objectModelClass, $shopId);
+            }
+
+            // Special case for Product because it has an additional full parameter
+            if ($objectModelClass === Product::class) {
+                $objectModel = new Product($id, false, null, $shopId ? $shopId->getValue() : null);
+            } else {
+                $objectModel = new $objectModelClass($id, null, $shopId ? $shopId->getValue() : null);
+            }
```
Comment (eternoendless) [inline src/Adapter/AbstractObjectModelRepository.php]: You can extract this into a `constructObject(int $id, ShopId $shopId): ObjectModel` method, then leave it to the concrete class to override it for Product

File: src/Adapter/AbstractObjectModelRepository.php [hunk 10]
```diff
@@ -66,15 +72,30 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
      * @return ObjectModel
      *
      * @throws CoreException
      */
-    protected function getObjectModel(int $id, string $objectModelClass, string $exceptionClass): ObjectModel
+    protected function getObjectModel(int $id, string $objectModelClass, string $exceptionClass, ?ShopId $shopId = null): ObjectModel
     {
         try {
-            $objectModel = new $objectModelClass($id);
+            if (null !== $shopId) {
```
Comment (eternoendless) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
            if ($shopId instanceof ShopId) {
```

File: src/Adapter/AbstractObjectModelRepository.php [hunk 11]
```diff
@@ -66,15 +72,30 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+
+            // Special case for Product because it has an additional full parameter
+            if ($objectModelClass === Product::class) {
+                $objectModel = new Product($id, false, null, $shopId ? $shopId->getValue() : null);
+            } else {
+                $objectModel = new $objectModelClass($id, null, $shopId ? $shopId->getValue() : null);
+            }
+
+            // Force id_shop_list right away so that DB modification use the appropriate shop and not the one from context
+            if (null !== $shopId) {
```
Comment (eternoendless) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
            if ($shopId instanceof ShopId) {
```

File: src/Adapter/AbstractObjectModelRepository.php [hunk 12]
```diff
@@ -95,6 +116,43 @@ protected function getObjectModel(int $id, string $objectModelClass, string $exc
         return $objectModel;
     }
 
+    /**
+     * @param int $id
+     * @param string $objectModelClass
```
Comment (eternoendless) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
     * @param class-name<ObjectModel> $objectModelClass
```

see https://phpstan.org/writing-php-code/phpdoc-types#class-string

Comment (eternoendless) [reply src/Adapter/AbstractObjectModelRepository.php]: The parameter should probably be renamed to `$objectModelClassName`

File: src/Adapter/AbstractObjectModelRepository.php [hunk 13]
```diff
@@ -95,6 +116,43 @@ protected function getObjectModel(int $id, string $objectModelClass, string $exc
...
+     * @param ShopId $shopId
+     *
+     * @throws ShopAssociationNotFound
+     */
+    protected function checkShopAssociation(int $id, string $objectModelClass, ShopId $shopId): void
```
Comment (eternoendless) [inline src/Adapter/AbstractObjectModelRepository.php]: Isn't this done by ObjectModel already?

File: src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php [hunk 14]
```diff
@@ -68,7 +69,26 @@ public function __construct(
...
     {
-        $product = $this->productRepository->get($command->getProductId());
+        // @todo: this part will very likely be very similar in other multistore handlers, maybe we can share this via an abstract class later
+        if (null === $command->getShopConstraint()) {
+            $this->updatePriceByShop($command);
+        } elseif ($command->getShopConstraint()->forAllShops()) {
+            $shops = $this->productRepository->getAssociatedShopIds($command->getProductId());
+            foreach ($shops as $shopId) {
+                $this->updatePriceByShop($command, $shopId);
+            }
```
Comment (eternoendless) [inline src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: Hum, this looks like a future performance issue. The way I see it, an update for a single shop is an update performed with a constraint (eg. `WHERE shop_id = %`) and an update for multiple shops is an update without constraint (eg. `WHERE 1`). Therefore the shop constraint should naturally go all the way to `$this->productRepository->partialUpdate()` so that the repository can perform an optimized batch update query instead of a bunch of single updates.

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 15]
```diff
@@ -357,4 +362,49 @@ public function bulkDelete(array $productIds): void
...
+     *
+     * @return bool
+     */
+    public function isAssociatedToShop(ProductId $productId, ShopId $shopId): bool
+    {
+        try {
+            $this->checkShopAssociation($productId->getValue(), Product::class, $shopId);
+        } catch (ShopAssociationNotFound $e) {
+            return false;
+        }
```
Comment (eternoendless) [inline src/Adapter/Product/Repository/ProductRepository.php]: You shouldn't use exceptions as a messaging protocol

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 16]
```diff
@@ -0,0 +1,306 @@
...
+    /**
+     * @param Product $product
+     *
+     * @return array
+     */
+    private function getAssociationFields(Product $product): array
+    {
+        $associationFields = [];
+        $associationFields['id_category_default'] = (int) $product->id_category_default;
+        $associationFields['cache_default_attribute'] = (int) $product->cache_default_attribute;
```
Comment (eternoendless) [inline src/Adapter/Product/Update/ProductShopUpdater.php]: If you are going this way, you can do it with less noise:
```suggestion
        $associationFields = [
        	'id_category_default' => (int) $product->id_category_default,
        	'cache_default_attribute' => (int) $product->cache_default_attribute,
      	];
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 17]
```diff
@@ -0,0 +1,306 @@
...
+        $fields = [];
+        // The fields are fetched separately for more clarity, and it could also allow to configure which parts are copied
+        // (e.g copy only prices but not stock)
+        $fields = $fields + $this->getAssociationFields($sourceProduct);
+        $fields = $fields + $this->getPricesFields($sourceProduct);
+        $fields = $fields + $this->getStockFields($sourceProduct);
+        $fields = $fields + $this->getSEOFields($sourceProduct);
+        $fields = $fields + $this->getOptionsFields($sourceProduct);
+        $fields = $fields + $this->getCustomizationFields($sourceProduct);
+        $fields = $fields + $this->getDateFields($sourceProduct);
```
Comment (eternoendless) [inline src/Adapter/Product/Update/ProductShopUpdater.php]: IMO this will be easier to read (and less risky) if you use a single array_merge operation
```suggestion
        // The fields are fetched separately for more clarity, and it could also allow to configure which parts are copied
        // (e.g copy only prices but not stock)
        $fields = array_merge(
            $this->getAssociationFields($sourceProduct),
            $this->getPricesFields($sourceProduct),
            $this->getStockFields($sourceProduct),
            $this->getSEOFields($sourceProduct),
            $this->getOptionsFields($sourceProduct),
            $this->getCustomizationFields($sourceProduct),
            $this->getDateFields($sourceProduct)
        );
```

File: src/Adapter/AbstractObjectModelRepository.php (hunk 9 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: I'm not sure to understand this, I don't mind creating a `constructObject` function, however I will still need to handle a special case for product constructor because it has an extra parameter compared to all other legacy objects constructors

File: src/Adapter/AbstractObjectModelRepository.php (hunk 13 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: Maybe there's a function already existing in ObjecModel that I don't know of Do you know which one?

I actually inspired this from this PR https://github.com/PrestaShop/PrestaShop/pull/21227 which improves `ObjectModel::existsInDatabase` which was buggy for some objects (like Order because its ID doesn't follow the usual convention)

However this method only checks for the entity ID not the association, but if you know of such existing method I'm interested!

File: src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php (hunk 14 above)
Comment (jolelievre) [reply src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: That makes sense, but for now the repositories are based on using the ObjectModel save/update methods which are performed on one entity It's not a new dedicated SQL query that is built, so we can't make such optimizations for now

We would need a "true" repository that is able to build the query itself instead of relying on the ObjectModel to do so, but that's not the path we chose for now So I'd say it's a refacto and optimization that would need to be done separately

Unless we decide to perform this refacto right now but it will significantly increase the PR size and development time

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 15 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php]: I don't understand, which exception are you referring to here?

File: src/Adapter/AbstractObjectModelRepository.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: These repositories are only used in the experimental product page for now, so if we go that way it's probably better to introduce a BC break and completely force the parameter I don't think it's worth maintaining backward compatibility for experimental code

However before I do this I need to analyze the impact of such change, because it means a lot of modification in a lot of places, maybe it will have to be done in a separate PR

File: src/Adapter/AbstractObjectModelRepository.php (hunk 12 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: I didn't know this one, nice!

Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: However I have two warnings in my IDE, it doesn't seem to bother CS-fixer nor PHPStan though

Capture d’écran 2021-08-26 à 13 55 55

Capture d’écran 2021-08-26 à 13 56 51

Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: Actually, PHPStan does not appreciate it.. that's weird Maybe we don't have a recent enough version?

Capture d’écran 2021-08-26 à 13 58 06

File: src/Adapter/AbstractObjectModelRepository.php (hunk 1 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: Right, it was for debug Thanks

Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: I'm surprised we have no warnings or errors from PHPStan with unused variables like this 🤔

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: Yeah, I think it can only be more performant and it gives us more control over what we're doing There is still a lot of unknown magic regarding ObjectModel and how it handles multishop
Besides all this is tested with Behat

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php (hunk 7 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php]: Well actually we do, because the single shop page now adds for each multishop field a checkbox "Apply for all shops"

So we have to split this into two commands, one for the current single shop And one to force the value to all the shops

The implementation here is quite naive yet though, I need to think of a better and reusable system to handle this, however, the principle of relying on two distinct commands still seems the best approach to me for now

I'm opened to alternatives though!

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php (hunk 4 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php:55]: Well actually we will need the same thing as the above line later, it's just that for now I only handle the `price_tax_excluded` fields

File: src/PrestaShopBundle/Form/Admin/Extension/MultistoreOverridableExtension.php (hunk 5 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Extension/MultistoreOverridableExtension.php]: Yep I agree, but it's not definitive at all This is the part I need to improve most as I'm not satisfied with it yet I don't know if I can rely on a single extension or if I'll need two Once the code is more mature I'll add appropriate descriptions

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature (hunk 2 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature]: Nope, it's a mistake Thanks

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature (hunk 3 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature:66]: Because `And single shop context is loaded` (L15) forces the single shop context with default shop which is the shop1

But maybe it's not explicit enough? Or maybe we should never rely on the context shop at all and always provide a specific shop? That would imply forcing a shopConstraint in every single command that have already been implemented But it might be the safer solution

File: src/Adapter/AbstractObjectModelRepository.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: On second thought I wonder if this parameter should not be mandatory because not all the ObjectModel handle multishop (actually the majority of them don't..)

So it would force a useless parameter to be provided in most of the case, alternatively maybe we should instead have two methods `get` and `getForShop`? The later would have a mandatory `ShopId` parameter

File: src/Adapter/AbstractObjectModelRepository.php (hunk 9 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: Ok I got it!! 😅

File: tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature (hunk 3 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Product/Shop/shop_management.feature:66]: This changed, now the shopConstraint parameter is mandatory for this command, though I kept the old behat endpoint (to keep the regular single shop scenarios simpler), but what it does behind the scene is get the default shop from the configuration

File: admin-dev/themes/new-theme/js/components/multistore-header.ts [hunk 18]
```diff
@@ -71,12 +72,46 @@ const initMultistoreHeader = () => {
 
   new AutoCompleteSearch($searchInput, dataSetConfig);
 
-  if (headerButton && modalMultishop) {
+  function toggleModal() {
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/components/multistore-header.ts]: Please define the return value.

File: admin-dev/themes/new-theme/js/components/multistore-header.ts [hunk 19]
```diff
@@ -71,12 +72,46 @@ const initMultistoreHeader = () => {
...
+        toggleModal();
+      }
+    }, false);
   }
+
+  /**
+   * Header multishop links don't handle anchors which might be useful for tab navigation for example
+   * so we synchronize them via javascript
+   */
+  function updateLinksAnchor() {
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/components/multistore-header.ts]: Please define the return value.

File: tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php [hunk 20]
```diff
@@ -0,0 +1,336 @@
...
+        ];
+    }
+
+    /**
+     * @dataProvider getExpectedCommandsMultistore
+     *
+     * @param array $formData
+     * @param array $expectedCommands
+     */
+    public function testBuildCommandMultistore(array $formData, array $expectedCommands)
```
Comment (Progi1984) [inline tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php]:
```suggestion
    public function testBuildCommandMultistore(array $formData, array $expectedCommands): void
```

File: tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php [hunk 21]
```diff
@@ -0,0 +1,336 @@
...
+     * @param array $expectedCommands
+     */
+    public function testBuildCommand(array $formData, array $expectedCommands)
+    {
+        $builder = new PricesCommandsBuilder(self::MULTI_SHOP_PREFIX);
+        $builtCommands = $builder->buildCommands($this->getProductId(), $formData, $this->shopId);
+        $this->assertEquals($expectedCommands, $builtCommands);
+    }
+
+    public function getExpectedCommands()
```
Comment (Progi1984) [inline tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php]:
```suggestion
    public function getExpectedCommands(): iterable
```

File: tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php [hunk 22]
```diff
@@ -0,0 +1,336 @@
...
+{
+    private const MULTI_SHOP_PREFIX = 'prices_multishop';
+
+    /**
+     * @dataProvider getExpectedCommands
+     *
+     * @param array $formData
+     * @param array $expectedCommands
+     */
+    public function testBuildCommand(array $formData, array $expectedCommands)
```
Comment (Progi1984) [inline tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilderTest.php]:
```suggestion
    public function testBuildCommand(array $formData, array $expectedCommands): void
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php [hunk 23]
```diff
@@ -116,14 +177,25 @@ public function assertPriceFields(string $productReference, TableNode $tableNode
...
 
+        $this->assertPricesInfos($pricesInfo, $data);
+    }
+
+    /**
+     * @param $pricesInfo
+     * @param array $data
+     * @param string|null $shopReference
+     */
+    private function assertPricesInfos($pricesInfo, array $data, string $shopReference = null): void
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php]:
```suggestion
    private function assertPricesInfos(ProductPricesInformation $pricesInfo, array $data, string $shopReference = null): void
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php [hunk 24]
```diff
@@ -116,14 +177,25 @@ public function assertPriceFields(string $productReference, TableNode $tableNode
         $data = $tableNode->getRowsHash();
         $pricesInfo = $this->getProductForEditing($productReference)->getPricesInformation();
 
+        $this->assertPricesInfos($pricesInfo, $data);
+    }
+
+    /**
+     * @param $pricesInfo
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php]:
```suggestion
     * @param ProductPricesInformation $pricesInfo
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php [hunk 25]
```diff
@@ -36,23 +36,61 @@
...
 use Tests\Integration\Behaviour\Features\Context\Domain\TaxRulesGroupFeatureContext;
 use Tests\Integration\Behaviour\Features\Context\Util\PrimitiveUtils;
 
 class UpdatePricesFeatureContext extends AbstractProductFeatureContext
 {
+    /**
+     * @When I update product :productReference prices for shop :shopReference with following information:
+     *
+     * @param string $productReference
+     * @param string $shopReference
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php:51]:
```suggestion
     * @param string $shopReference
     * @param TableNode $table
```

File: tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php [hunk 26]
```diff
@@ -36,23 +36,61 @@
...
+    {
+        $shop = $this->getSharedStorage()->get(trim($shopReference));
+        $shopConstraint = ShopConstraint::shop((int) $shop->id);
+        $this->updatePrices($productReference, $table, $shopConstraint);
+    }
+
+    /**
+     * @When I update product :productReference prices for all shops with following information:
+     *
+     * @param string $productReference
```
Comment (Progi1984) [inline tests/Integration/Behaviour/Features/Context/Domain/Product/UpdatePricesFeatureContext.php:64]:
```suggestion
     * @param string $productReference
     * @param TableNode $table
```

File: src/PrestaShopBundle/Form/Admin/Extension/ModifyAllStoresExtension.php [hunk 27]
```diff
@@ -0,0 +1,160 @@
...
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        if (!$this->multistoreContextChecker->isSingleShopContext()) {
+            return;
+        }
+
+        $isOverridden = $builder->getOption('modify_all_stores');
+        if ($isOverridden) {
+            $label = $this->getCheckboxLabel();
+            $builder->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event) use ($label) {
```
Comment (Progi1984) [inline src/PrestaShopBundle/Form/Admin/Extension/ModifyAllStoresExtension.php:106]:
```suggestion
            $builder->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event) use ($label) {
```

File: src/Core/Domain/Product/Query/GetProductForEditing.php [hunk 28]
```diff
@@ -55,4 +65,12 @@ public function getProductId(): ProductId
     {
         return $this->productId;
     }
+
+    /**
+     * @return ShopId|null
```
Comment (Progi1984) [inline src/Core/Domain/Product/Query/GetProductForEditing.php]:
```suggestion
     * @return ShopId
```

File: src/Core/Domain/Product/Query/GetProductForEditing.php [hunk 29]
```diff
@@ -55,4 +65,12 @@ public function getProductId(): ProductId
...
+     */
+    public function getShopId(): ?ShopId
```
Comment (Progi1984) [inline src/Core/Domain/Product/Query/GetProductForEditing.php]:
```suggestion
    public function getShopId(): ShopId
```

File: src/Core/Domain/Product/Query/GetProductForEditing.php [hunk 30]
```diff
@@ -39,13 +40,22 @@ class GetProductForEditing
     private $productId;
 
     /**
-     * GetEditableProduct constructor.
+     * @var ShopId|null
```
Comment (Progi1984) [inline src/Core/Domain/Product/Query/GetProductForEditing.php]:
```suggestion
     * @var ShopId
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 31]
```diff
@@ -0,0 +1,302 @@
...
+            'text_fields' => (int) $product->text_fields,
+        ];
+    }
+
+    /**
+     * Date fields are all mandatory.
+     *
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, string>
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 32]
```diff
@@ -0,0 +1,302 @@
...
+            'active' => (int) $product->active,
+            'available_for_order' => (int) $product->available_for_order,
+            'indexed' => (int) $product->indexed,
+        ];
+    }
+
+    /**
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, int>
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 33]
```diff
@@ -0,0 +1,302 @@
...
+        return [
+            'redirect_type' => $product->redirect_type,
+            'id_type_redirected' => (int) $product->id_type_redirected,
+        ];
+    }
+
+    /**
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, int>
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 34]
```diff
@@ -0,0 +1,302 @@
...
+            'low_stock_alert' => (int) $product->low_stock_alert,
+            'advanced_stock_management' => $product->advanced_stock_management,
+            'pack_stock_type' => (int) $product->pack_stock_type,
+        ];
+    }
+
+    /**
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, int>
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 35]
```diff
@@ -0,0 +1,302 @@
...
+            'unit_price_ratio' => $product->unit_price_ratio,
+            'unity' => $product->unity,
+            'additional_shipping_cost' => $product->additional_shipping_cost,
+        ];
+    }
+
+    /**
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, int>
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 36]
```diff
@@ -0,0 +1,302 @@
...
+        return [
+            'id_category_default' => (int) $product->id_category_default,
+            'cache_default_attribute' => $product->cache_default_attribute,
+        ];
+    }
+
+    /**
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, mixed>
```

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 37]
```diff
@@ -0,0 +1,302 @@
...
+            $qb->set($column, $value);
+        }
+
+        return $qb;
+    }
+
+    /**
+     * @param Product $product
+     *
+     * @return array
```
Comment (Progi1984) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
     * @return array<string, int>
```

**Review by Progi1984 — COMMENTED** [review]
@jolelievre Thank you for your contribution. I have brought some comments.

File: classes/ObjectModel.php [hunk 38]
```diff
@@ -406,12 +406,16 @@ protected function formatFields($type, $id_lang = null)
...
             if (($type == self::FORMAT_LANG && empty($data['lang']))
                 || ($type == self::FORMAT_SHOP && empty($data['shop']))
-                || ($type == self::FORMAT_COMMON && ((!empty($data['shop']) && $data['shop'] != 'both') || !empty($data['lang'])))) {
+                || ($type == self::FORMAT_COMMON && ((!empty($data['shop']) && $data['shop'] !== 'both') || !empty($data['lang'])))) {
                 continue;
             }
 
             if (is_array($this->update_fields)) {
-                if ((!empty($data['lang']) || (!empty($data['shop']) && $data['shop'] != 'both')) && (empty($this->update_fields[$field]) || ($type == self::FORMAT_LANG && empty($this->update_fields[$field][$id_lang])))) {
+                if (!empty($data['lang']) && $type == self::FORMAT_LANG && empty($this->update_fields[$field][$id_lang])) {
```
Comment (jolelievre) [inline classes/ObjectModel.php]: This modification is important because it appears the whole "partial update of an ObjectModel" feature  has been buggy for quite a while now. I went through the history of this code and found these consecutive modifications:

https://github.com/PrestaShop/PrestaShop/commit/009e190263a2b4d904d084b0bea5a02a2c235fdb
https://github.com/PrestaShop/PrestaShop/commit/84d1e57ad968bb6fd81ba22ac6e4ef40d5efbeee
https://github.com/PrestaShop/PrestaShop/commit/07c3ee5dd1ddc1b091fc0700249d5d5def6ca7cd (https://github.com/PrestaShop/PrestaShop/pull/2452)

I think the code got harder and harder to understand and some features were lost along the way, the initial purpose of `update_fields` is to filter the fields that need to be updated, so basically if the `update_fields` is defined and the field is not inside the array we skip it so it's not updated

Although there are a few complex use cases:

For multilang values, the `updated_fields` must be check based on the `$id_lang` of course

For multishop values:

- any multishop value should only be updated in the `_shop` table not in the original one
- in the Product case this check was not correctly done, since most fields are duplicated it resulted in updating the column in both the `product` table AND the `product_shop` table
- there is an exception though when the multishop field is defined with `'shop' => 'both'` then the value must be updated in both tables (this is only used for `Combination` and `Image`)

But the way the `both` feature was handled broke the feature because the condition `!empty($data['shop']) && $data['shop'] != 'both'` is not correct, the purpose is to detect when `'shop' => true` but since `'both'` is considered truthy the condition is never met even when `'shop' => true` That's why a strict non equality is required here.

Comment (jolelievre) [reply classes/ObjectModel.php:414]: So this fixes some buggy behaviour, however this could raise some breaking change especially regarding the Product class, because now that the filtering is correctly handled the multishop fields are updated ONLY in the `product_shop` table.

They will remain unchanged forever in the `product` table, and I'm not sure this behaviour is expected or correctly understood by everyone...

Comment (jolelievre) [reply classes/ObjectModel.php:414]: One possibility to force the update in both table is to set `'shop' => 'both'` in every Product's fields (instead of simply true) This way we keep the double update behaviour but it is done correctly this time

File: admin-dev/themes/new-theme/js/components/navbar-handler.ts [hunk 39]
```diff
@@ -70,13 +70,8 @@ export default class NavbarHandler {
   }
 
   updateBrowserHash(target: string): void {
-    const hashName = target.replace('#', `#${this.tabPrefix}`);
-
-    if (window.history.pushState) {
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/components/navbar-handler.ts:75]: ping @NeOMakinG can you have a look please

File: src/Adapter/AbstractObjectModelRepository.php [hunk 40]
```diff
@@ -66,35 +72,76 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+     */
+    protected function checkShopAssociation(int $id, string $objectModelClassName, ShopId $shopId): void
+    {
+        $modelDefinition = $objectModelClassName::$definition;
+        $objectTable = $modelDefinition['table'];
+        $primaryColumn = $modelDefinition['primary'];
+
+        $query = new DbQuery();
+        $query
+            ->select('e.`' . $primaryColumn . '` as id')
```
Comment (PierreRambaud) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
            ->select('e.`' . bqSQL($primaryColumn) . '` as id')
```

File: src/Adapter/AbstractObjectModelRepository.php [hunk 41]
```diff
@@ -66,35 +72,76 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+            ->from($objectTable . '_shop', 'e')
```
Comment (PierreRambaud) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
            ->from(bqSQL($objectTable) . '_shop', 'e')
```

File: src/Adapter/AbstractObjectModelRepository.php [hunk 42]
```diff
@@ -66,35 +72,76 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+            ->where('e.`id_shop` = ' . $shopId->getValue())
+        ;
+
+        try {
+            $row = Db::getInstance()->getRow($query, false);
+        } catch (PrestaShopDatabaseException $e) {
+            $row = false;
+        }
+
+        if (!isset($row['id'])) {
```
Comment (PierreRambaud) [inline src/Adapter/AbstractObjectModelRepository.php]:
```suggestion
        if (empty($row['id'])) {
```
Should we really need to find zero values?

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 43]
```diff
@@ -0,0 +1,302 @@
...
+        $this->shopRepository->assertShopExists($targetShopId);
+
+        /** @var Product $sourceProduct */
+        $sourceProduct = $this->productRepository->getForShop($productId, $sourceShopId);
+
+        // @todo: for now only fields from product_shop table ar handed, we still need to handle multilang, stock_available, and probably other things (in another PR)
+        // @todo: do not forget to copy customization_field_lang, this part was not handled in the legacy import (fixed in this PR)
+        // The fields are fetched separately for more clarity, and it could also allow to configure which parts are copied
+        // (e.g copy only prices but not stock)
+        $fields = array_merge(
```
Comment (PierreRambaud) [inline src/Adapter/Product/Update/ProductShopUpdater.php]: In case of arrays are in multidimensional mode: https://www.php.net/manual/en/function.array-merge-recursive.php

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 44]
```diff
@@ -0,0 +1,302 @@
...
+    /**
+     * @param Product $product
+     *
+     * @return array<string, int>
+     */
+    private function getAssociationFields(Product $product): array
+    {
+        return [
+            'id_category_default' => (int) $product->id_category_default,
+            'cache_default_attribute' => $product->cache_default_attribute,
```
Comment (PierreRambaud) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
            'cache_default_attribute' => (int) $product->cache_default_attribute,
```

Regarding the returns definition, it should be an int :thinking:

File: admin-dev/themes/new-theme/js/components/navbar-handler.ts (hunk 39 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/js/components/navbar-handler.ts:75]: @jolelievre did you test this? And using the previous and next func of the browser? We had an issue on this on FO where using window.location is erasing the history, but as it's only aiming the hash part, maybe not on this case

**Comment by NeOMakinG** [comment]
Front logic looks fine to me, except a small question about testing something

Also, I don't mind about these JS files instead of TS files, because I'm still currently migrating them

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Product/Update/ProductShopUpdater.php [hunk 45]
```diff
@@ -0,0 +1,302 @@
...
+    /**
+     * @param array $fields
+     *
+     * @return array
+     */
+    private function formatQueryValues(array $fields): array
+    {
+        $values = [];
+        foreach (array_keys($fields) as $column) {
+            $values[sprintf('`%s`', $column)] = sprintf(':%s', $column);
```
Comment (PierreRambaud) [inline src/Adapter/Product/Update/ProductShopUpdater.php]:
```suggestion
            $values[sprintf('`%s`', bqSQL($column))] = sprintf(':%s', $column);
```
?

File: admin-dev/themes/new-theme/js/pages/product/edit/product-suppliers-manager.js [hunk 46]
```diff
@@ -86,6 +88,53 @@ export default class ProductSuppliersManager {
...
+   * @param {string} newPrice
+   */
+  updateDefaultProductSupplierPrice(newPrice) {
+    const defaultProductSupplierId = this.getDefaultProductSupplierId();
+
+    if (defaultProductSupplierId) {
+      // Update default price value and trigger change so that memorizeCurrentSuppliers is triggered (along with other
+      // potential listeners)
+      const rowMap = this.suppliersMap.productSupplierRow;
+      $(rowMap.priceInput(defaultProductSupplierId)).val(newPrice).trigger('change');
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-suppliers-manager.js]: Shouldn't be a blur event?

File: src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php [hunk 47]
```diff
@@ -51,27 +55,62 @@ final class UpdateProductPricesHandler implements UpdateProductPricesHandlerInte
...
     /**
      * {@inheritdoc}
      */
     public function handle(UpdateProductPricesCommand $command): void
     {
-        $product = $this->productRepository->get($command->getProductId());
+        if ($command->getShopConstraint()->forAllShops()) {
+            $product = $this->productRepository->get($command->getProductId());
+        } else {
+            $product = $this->productRepository->getForShop($command->getProductId(), $command->getShopConstraint()->getShopId());
```
Comment (PierreRambaud) [inline src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: We have a `partialUpdateForShopConstraint` method, why we don't have a `getForShopConstraint` 
```php
$this->productRepository->get($command->getProductId(), $command->getShopConstraint());
```
?

File: src/Core/Domain/Product/Query/GetProductForEditing.php [hunk 48]
```diff
@@ -39,13 +40,22 @@ class GetProductForEditing
...
+     * @param ShopId $shopId
      */
-    public function __construct(int $productId)
-    {
+    public function __construct(
+        int $productId,
+        ShopId $shopId
+    ) {
         $this->productId = new ProductId($productId);
+        $this->shopId = $shopId;
```
Comment (PierreRambaud) [inline src/Core/Domain/Product/Query/GetProductForEditing.php]: what about shop group id? are we planning to handle this use case? or is it not needed?

File: admin-dev/themes/new-theme/js/components/navbar-handler.ts (hunk 39 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/navbar-handler.ts:75]: This was only used to change the hashtag indeed, but I don't think history can handle this anyway 🤔

Even if it could losing history between the page's tabs is not that much a problem IMHO, compared to the previous issue, when the form shop context was saved you were always redirected to the first tab Which is really annoying when you want to compare the prices between the shops (for example)

I wanted to keep the `pushState` but there is no event related to it, unlike when using `window.location.hash` where a `hashchange` event is triggered. So it allows keeping track on the current hash and to update the URLs in the multishop header.

I tried to find something similar for `pushState` but since no event exists the only workaround I found actually overrides the function in the window object to integrate a custom event when the method is called. Which seemed overkill to me, and not really a clean solution.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/navbar-handler.ts:75]: BTW I tried using the prev/next buttons in the browser, and I'm quite surprised but it works 😅

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 43 above)
Comment (jolelievre) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: For now only the "simple" fields directly related to Product are handled, so they are only single dimension arrays, it's fine with the current code

The more advanced fields (like relationships) will be handled in a different PR, and probably in a different function (well another private function at least)

File: src/Core/Domain/Product/Query/GetProductForEditing.php (hunk 48 above)
Comment (jolelievre) [reply src/Core/Domain/Product/Query/GetProductForEditing.php]: No the group shop context is not handled by the product page (nor the Product object for that matter)

File: tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php [hunk 49]
```diff
@@ -1138,6 +1171,35 @@ private function createBasic(array $product): ProductBasicInformation
         );
     }
 
+    /**
+     * @param int $expectedShopId
+     *
+     * @return MockObject|CommandBusInterface
+     */
+    private function createQueryBusCheckingShopMock(int $expectedShopId)
```
Comment (Progi1984) [inline tests/Unit/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProviderTest.php]:
```suggestion
    private function createQueryBusCheckingShopMock(int $expectedShopId): CommandBusInterface
```

**Review by Progi1984 — DISMISSED** [review]
I approve but I have brought you a small comment in test.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php [hunk 50]
```diff
@@ -0,0 +1,165 @@
...
+
+    /**
+     * @var PropertyAccessorInterface
+     */
+    private $propertyAccessor;
+
+    public function __construct(CommandAccessorConfig $config)
+    {
+        $this->config = $config;
+        $this->propertyAccessor = PropertyAccess::createPropertyAccessorBuilder()
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php:90]: Isn't something we can inject?

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php [hunk 51]
```diff
@@ -0,0 +1,165 @@
...
+     *
+     * @param array $data
+     * @param mixed $singleStoreCommand
+     * @param mixed|null $allStoresCommand
+     *
+     * @return array Returns modified commands (if no field was detected an empty array is returned)
+     */
+    public function buildCommands(
+        array $data,
+        $singleStoreCommand,
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: Isn't an array or null?
Can by ?array no?
I said that because of the in_array function

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php [hunk 52]
```diff
@@ -0,0 +1,165 @@
...
+    /**
+     * If only single store command is provided then only this one will be prefilled, however if a command for all
+     * stores is also provided then this component will check in the data (for each field) if the modification targets
+     * all the stores, or not, and prefill the appropriate command accordingly.
+     *
+     * @param array $data
+     * @param mixed $singleStoreCommand
+     * @param mixed|null $allStoresCommand
+     *
+     * @return array Returns modified commands (if no field was detected an empty array is returned)
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: What kind of array is it? does it return strings? Objects?

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php [hunk 53]
```diff
@@ -0,0 +1,165 @@
...
+     * @param CommandField $commandField
+     * @param mixed $singleStoreCommand
+     * @param mixed|null $allStoresCommand
+     *
+     * @return mixed
+     */
+    private function getAppropriateCommand(
+        array $data,
+        CommandField $commandField,
+        $singleStoreCommand,
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: same as previous, can be typed I think

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php [hunk 54]
```diff
@@ -0,0 +1,120 @@
...
+    /**
+     * @return string
+     */
+    public function getModifyAllNamePrefix(): string
+    {
+        return $this->modifyAllNamePrefix;
+    }
+
+    /**
+     * @return CommandField[]
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php]:
```suggestion
     * @return array<int, CommandField>
```

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php [hunk 55]
```diff
@@ -0,0 +1,165 @@
...
+     */
+    private function castValue($value, string $type)
+    {
+        switch ($type) {
+            case CommandField::TYPE_STRING:
+                return (string) $value;
+            case CommandField::TYPE_BOOL:
+                return (bool) $value;
+            case CommandField::TYPE_INT:
+                return (int) $value;
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: What about the TYPE_ARRAY?

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php [hunk 56]
```diff
@@ -0,0 +1,120 @@
...
+
+namespace PrestaShop\PrestaShop\Core\Form\IdentifiableObject\CommandBuilder\Accessor;
+
+/**
+ * Config that gives information to the CommandAccessor component to correctly check the data and prefill the command
+ * object, each data property is associated to a setter in the command and its appropriate type for casting. Example:
+ *
+ * $config = new CommandAccessorConfig('modify_all_');
+ * $config
+ *     ->addField('[name]', 'setName', CommandField::TYPE_STRING)
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php:37]: Isn't more obvious to add a field like that 
```suggestion
 *     ->addField('name', 'setName', CommandField::TYPE_STRING)
```
or
```suggestion
 *     ->addField('parent[children]', 'setChildren', CommandField::TYPE_STRING)
```

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php [hunk 57]
```diff
@@ -54,11 +55,16 @@ public function __construct(iterable $commandBuilders)
      *
      * @return array
      */
-    public function buildCommands(ProductId $productId, array $formData): array
+    public function buildCommands(ProductId $productId, array $formData, ShopId $shopId): array
     {
         $commandCollection = [];
         foreach ($this->commandBuilders as $commandBuilder) {
-            $commands = $commandBuilder->buildCommands($productId, $formData);
+            if ($commandBuilder instanceof MultistoreProductCommandsBuilderInterface) {
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php]: $shopId could be an optional parameter to prevent this kind of condition, wdyt?

File: src/Core/Form/IdentifiableObject/DataHandler/ProductFormDataHandler.php [hunk 58]
```diff
@@ -48,16 +49,26 @@ class ProductFormDataHandler implements FormDataHandlerInterface
...
     public function __construct(
         CommandBusInterface $bus,
-        ProductCommandsBuilder $commandsBuilder
+        ProductCommandsBuilder $commandsBuilder,
+        int $defaultShopId,
+        ?int $contextShopId
     ) {
         $this->bus = $bus;
         $this->commandsBuilder = $commandsBuilder;
+        $this->shopId = null !== $contextShopId ? new ShopId($contextShopId) : new ShopId($defaultShopId);
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/DataHandler/ProductFormDataHandler.php]:
```suggestion
        $this->shopId = new ShopId($contextShopId ?: $defaultShopId);
```

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php [hunk 59]
```diff
@@ -70,22 +71,31 @@ final class ProductFormDataProvider implements FormDataProviderInterface
...
-        int $defaultCategoryId
+        int $defaultCategoryId,
+        int $defaultShopId,
+        ?int $shopId
     ) {
         $this->queryBus = $queryBus;
         $this->defaultProductActivation = $defaultProductActivation;
         $this->mostUsedTaxRulesGroupId = $mostUsedTaxRulesGroupId;
         $this->defaultCategoryId = $defaultCategoryId;
+        $this->shopId = null !== $shopId ? new ShopId($shopId) : new ShopId($defaultShopId);
```
Comment (PierreRambaud) [inline src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: same as previous about the ternary

File: src/Core/Util/DateTime/DateTime.php [hunk 60]
```diff
@@ -65,4 +66,28 @@ public function __construct()
     {
         throw new RuntimeException(sprintf('This class purpose is to define constants only. You might have mistaken it with "%s"', \DateTime::class));
```
Comment (PierreRambaud) [inline src/Core/Util/DateTime/DateTime.php]: NativeDateTime?

File: admin-dev/themes/new-theme/js/pages/product/edit/product-suppliers-manager.js (hunk 46 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/edit/product-suppliers-manager.js]: No, the registered event in `ProductPartialUpdater` and in `FormObjectMapper` are both `change` events

File: src/Adapter/AbstractObjectModelRepository.php (hunk 40 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: I wanted to use doctrine query, but I forgot that this abstract class doesn't have a `Connection` field, since not all the repositories use doctrine for their request

This will have to be improved later ^^ I'm gonna keep using legacy Db with your improvements

File: src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php (hunk 47 above)
Comment (jolelievre) [reply src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: Well in the abstract class I added two methods:
- `getObjectModelForShop` (which use a single shop ID)
- `partiallyUpdateObjectModelForShops` (which uses a list of shop ids)

The get is based on only one shop because the override is only related to a single shop (at least for Product, maybe in the future we'll need to add the same thing for ShopGroup). So getting a Product value only makes sense for one shop.

By the way the "regular" `get` without the provided ShopId actually relies on the legacy behaviour and gets the shop ID from context, this part I'm not particularly a fan because it kind of hides some things, but since the constraint for all shops doesn't contain the context shop ID I don't know how to handle this better. One solution could be to rely on the product's default shop ID though. Maybe I should add this in the `get` method.

Comment (jolelievre) [reply src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: Regarding the partial update method, the method in the abstract class is more generic (it is based on a list of ShopIds) but in the case of the product repository I added a method which relies on ShopConstraint because we have only two use cases:
- Single shopId, then I call `partiallyUpdateObjectModelForShops` with an array of one ShopId
- All shop context, in this case we need to get the list of all associated shop IDs and then call `partiallyUpdateObjectModelForShops` with the appropriate array

So it felt more convenient to use `ShopConstraint` as a parameter since it is accessible in the commands directly, this way the part that gets the list of associated shops is handled internally in the Repository instead of duplicating it in all the handlers.

Comment (jolelievre) [reply src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: TLDR; 
- updating values by shop constraint makes sense because in the case of AllShop context we can update a bunch of shop at the same time
- but we can't `get` a Product with data for AllShop, nor ShopGroup (it would be possible if our structure of multishop for product was better handled but that's not the case right now) so since it is only possible for single shop context it felt more simple to rely on ShopID directly rather than ShopConstraint

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 44 above)
Comment (jolelievre) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: Yep, nice catch!

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 45 above)
Comment (jolelievre) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: In this case I'm not sure it's required because this time it is based on a Doctrine query

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 52 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: It is an array of Command objects, but I can't detail the type more precisely because all command objects are independent and they don't share a common class nor interface

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 50 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php:90]: I don't think so, the `PropertyAccess` is a component but it doesn't exist as a service as far as I know https://symfony.com/doc/4.4/components/property_access.html

Besides, it is used internally in this class (which should also be seen as a component), but it's not really a dependency that could be adapted by different external implementation, so creating it internally makes sens to me

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 51 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: No these objects are CQRS commands, like `UpdateProductPricesCommand` for example The `in_array` in this function is used with the command as the needle (`mixed`), not the haystack array

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 53 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: I can't type this because it needs to work with any CQRS command, `UpdateProductPricesCommand`, `UpdateProductBasicInformationCommand`, ...

They share no common class nor interface so I can't type it, `mixed` can't be used as a strong type either and I don't belive there is a generic `Object` in PHP

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 55 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: If the value is an array I don't think we have to cast it 🤔. Is it possible to do this `return (array) $value` ? I thought that like a mixed type it should simply be returned as is.

But to be honest, I didn't need to use the type array for now so I'm not 100% sure, I added it because I thought it could be useful later. But maybe it would be better not to handle it at all for now until we encounter a use case where it is needed.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php (hunk 56 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php:37]: No, I thought so as well, but that's not how the `PropertyAccessor` works. When you want to access an array field you need those brackets. The notation without brackets seems to be reserved for Objects like in `object.myChildren`

I tested the notation `parent[children]` and I get an exception `Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Cannot read property "parent" from an array. Maybe you intended to write the property path as "[parent]" instead.`

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php (hunk 54 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php]: I don't see the interest of this notation for such simple arrays, it gives the feeling that the indexes could be associative (like not consecutive using int IDs as keys)

But I'll change regardless, we should definitely document this new notation as mandatory somewhere and integrate a PHPStan rule for this

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php (hunk 57 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php]: Well the idea here is to be really explicit about which builder handles multistore and which one doesn't (since not all the fields in Product are multishop not all Commands are multishop).

But when one command is indeed multishop I want the ShopId to be forced and not optional, this forces us to really provide a shopId, and really think about which one. This will avoid the magic relying on the shop context behind the scene.

That's why I introduced the `MultistoreProductCommandsBuilderInterface`, for now the only "real" builder that implements it is the `PricesCommandsBuilder` (since it's the focus of this POC). The `ProductCommandsBuilder` though (which I don't consider as a "real" builder) is the class that orchestrates all other builders, so it can handle both multishop and singleshop builders, which is why it needs to check their type.

However since it contains some multishop handler, the orchestrator is itself a multishop handler that's why it also implements the `MultistoreProductCommandsBuilderInterface` because it needs to be called with the ShopId parameter so that it can transmit it to its internal builders.

File: src/Core/Form/IdentifiableObject/DataHandler/ProductFormDataHandler.php (hunk 58 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataHandler/ProductFormDataHandler.php]: Oh! Smart 😅

File: src/Core/Util/DateTime/DateTime.php (hunk 60 above)
Comment (jolelievre) [reply src/Core/Util/DateTime/DateTime.php]: You're right! I didn't see this one

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php (hunk 56 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php:37]: Actually I think it would work if you had this kind of object:
```php
class MyObject {
    public $parent = [
        'children' => 'anything',
    ];
}
```

It mixed both object and array so that would match your example. But since this component will mainly be used in command builders which are based on flat array data from the form (no objects), I prefer to keep the examples matching the most common use cases.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 51 above)
Comment (PierreRambaud) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: Funny that we don't have a default CQRS command interface :thinking:

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php (hunk 54 above)
Comment (PierreRambaud) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php]: I agree, it's a demand from @eternoendless :roll_eyes:

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 55 above)
Comment (PierreRambaud) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: We can cast things into array it works ^^
```
(array) 1; => [1]

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php (hunk 56 above)
Comment (PierreRambaud) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php:37]: sad story :(

Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php:37]: I thought so too at first, but in a way it makes sense that they chose to use a different syntax to access arrays and objects

File: src/Adapter/AbstractObjectModelRepository.php (hunk 8 above)
Comment (matks) [reply src/Adapter/AbstractObjectModelRepository.php]: > On second thought I wonder if this parameter should not be mandatory because not all the ObjectModel handle multishop (actually the majority of them don't..)

Every ObjectModel is supposed to be able to be multistore, but enabling or disabling this feature is done for each case. Just like any field can be translatable but it's enabled or not for each field.

So it's OK for me to consider that the standard usecase is "handle ObjectModel for different Shop context" and that "when option is disabled" is a specific case.

File: src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php (hunk 47 above)
Comment (matks) [reply src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: > but we can't get a Product with data for AllShop, nor ShopGroup (it would be possible if our structure of multishop for product was better handled but that's not the case right now) so since it is only possible for single shop context it felt more simple to rely on ShopID directly rather than ShopConstraint

If we want, in the future, to harmonize how we get ObjectModel, we could do the following:
```
public function getForShop(int $productId, ShopConstraint $constraint)
{
    if (!$constraint->isSingleShopConstraint()) {
        throw new RuntimeException('Cannot use ShopConstraint All shops or group shops with product entity');
```

This allows someone motivated to provide another implementation - that handles shop groups and all shops so we accept all kind of constraints in the signature, but in the Core implementation we fail if not given the right constraint.

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 15 above)
Comment (matks) [reply src/Adapter/Product/Repository/ProductRepository.php]: I suppose @eternoendless says that you use the throw of ShopAssociationNotFound to fetch the data "there is no shop association" and return false. I suppose @eternoendless would prefer

```
if (!$this->isThereAShopAssociation(...) {
    return false;
}

$check = $this->checkShopAssociation(...);

return true;
```

Don't rely on "this code will throw exception B if it meets usecase A, so I will on purpose trigger the situation for usecase A and listen for exception B to know whether or not I am in usecase A". Exceptions should only be throwed when we go on a path we DONT want to go.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 51 above)
Comment (matks) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: > Funny that we don't have a default CQRS command interface 🤔

Because it would have nothing in it, it would be an empty interface. A Command is... almost a DTO. Almost a StdClass.

Maybe however we could cast `$singleStoreCommand` into a CommandCollection object if @PierreRambaud does not want arrays.

**Review by matks — COMMENTED** [review]
Reviewed almost half of the PR. I will finish tomorrow.

Big work there 😄  but needs an extensive focus to follow it all.

File: src/Adapter/AbstractObjectModelRepository.php (hunk 8 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: Mmm, actually the ObjectModel does handle multishop internally, but not all the Entities use this feature, that's what I meant when I said that not all types of ObjectModel are multishop

And the thing is I believe there are more entities that don't use it than the opposite, that's why I think it's preferable that the abstract repository has dedicated base methods for both use cases This way you can use the appropriate one depending on the type of ObjectModel you are using

File: src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php (hunk 47 above)
Comment (jolelievre) [reply src/Adapter/Product/CommandHandler/UpdateProductPricesHandler.php]: Mmm, I get it what you both say makes sense! Then what I'm gonna do is implement `public function getForShop(int $productId, ShopConstraint $constraint)` in the `ProductRepository` (this will make the handler cleaner and the code easier to reuse)

However I will handle this only in the ProductRepository, I don't think we can make it generic in the abstract class (each type of ObjectModel may have different ways of handling the multishop). Instead the asbtract class offer simpler methods (based on shopId or list of shopIds) so that the concrete Repository (here ProdctRepository) can rely on them but it's the concrete class which has the responsibility to interpret the `ShopConstraint`

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php (hunk 57 above)
Comment (PierreRambaud) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php]: As far as I know, @eternoendless had in mind for the future that having a single store is a "Multistore with only one store". Meaning we could have a `ProductCommandsBuilderInterface` and if the shop constraint is defined, it means it does not affect all stores.
wdyt @eternoendless @matks ? I'm afraid of adding complexity everywhere with "If mutlistore, use this command, elseif  this one else another one", shouldn't be a single command to handle stores cases?

Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php]: I see your point and that's what I had in mind, which is why I prefer to force the ShopId (or ShopConstraint) parameter where it is needed rather than relying on an optional one.

But that doesn't mean we should have a shop parameter everywhere when it has no sense at all, even if we consider we are always in multishop some Entities and/or some part of the Product scope are not multishop at all so in those cases using a useless shop constraint seems confusing and illogical.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 50 above)
Comment (matks) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php:90]: I confirm, it's a util class that has IMO no advantages to be injected. Like json_encode

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 55 above)
Comment (matks) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: For record ^^https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Behaviour/Features/Context/Util/PrimitiveUtils.php

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php (hunk 56 above)
Comment (matks) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessorConfig.php:37]: I encountered the same situation in https://github.com/PrestaShop/PrestaShop/pull/25611. I agree it feels strange at first.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php [hunk 61]
```diff
@@ -30,46 +30,55 @@
...
         }
 
         $priceData = $formData['pricing'];
-        $command = new UpdateProductPricesCommand($productId->getValue());
+        $config = new CommandAccessorConfig($this->modifyAllNamePrefix);
+        $config
+            ->addMultiStoreField('[retail_price][price_tax_excluded]', 'setPrice', CommandField::TYPE_STRING)
+            ->addMultiStoreField('[retail_price][ecotax]', 'setEcotax', CommandField::TYPE_STRING)
+            ->addMultiStoreField('[tax_rules_group_id]', 'setTaxRulesGroupId', CommandField::TYPE_STRING)
+            ->addMultiStoreField('[on_sale]', 'setOnSale', CommandField::TYPE_STRING)
```
Comment (matks) [inline src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php]: `onSale` is a string, not a boolean?

File: tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandFieldTest.php [hunk 62]
```diff
@@ -0,0 +1,121 @@
...
+     */
+    public function testInvalidConstructors(string $dataPath, string $commandSetter, string $type, bool $isMultistoreField, string $expectedException): void
+    {
+        $this->expectException($expectedException);
+        new CommandField($dataPath, $commandSetter, $type, $isMultistoreField);
+    }
+
+    public function getInvalidParameters(): iterable
+    {
+        yield [
```
Comment (matks) [inline tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandFieldTest.php]: What is the difference between a PHPUnit dataProvider that returns an array and another that returns an iterable?

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php (hunk 61 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/PricesCommandsBuilder.php]: Yep, you're right! What is weird is that it was still working, which makes me think the `PropertyAccess` component probably handles casting internally

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 51 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: But again `$singleStoreCommand` and `$allStoresCommand` are NOT arrays, they are objects. But the returns of this method is an array of commands (even if it can contain one, two or no commands sometimes).

And I need two internal arrays, the second one is used to make sure the commands are always returned in the same order.

File: src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php (hunk 55 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandAccessor.php]: Ok I'll add the cast for array then

File: tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandFieldTest.php (hunk 62 above)
Comment (jolelievre) [reply tests/Unit/Core/Form/IdentifiableObject/CommandBuilder/Accessor/CommandFieldTest.php]: There's not much difference, it will have the same behaviour basically as far as I know 🤔
But I like the yield syntax better because it's clearer to me

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 63]
```diff
@@ -357,4 +405,139 @@ public function bulkDelete(array $productIds): void
...
+    }
+
+    /**
+     * @param ProductId $productId
+     *
+     * @return ShopId[]
+     */
+    public function getAssociatedShopIds(ProductId $productId): array
+    {
+        $qb = $this->connection->createQueryBuilder();
```
Comment (kpodemski) [inline src/Adapter/Product/Repository/ProductRepository.php]: If this is a part of the Adapter, wouldn't be better to just use `ObjectModel::getAssociatedShops`?

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 64]
```diff
@@ -357,4 +405,139 @@ public function bulkDelete(array $productIds): void
...
+     * @param Product $product
+     *
+     * @return Product
+     *
+     * @throws CoreException
+     */
+    private function loadProduct(Product $product): Product
+    {
+        try {
+            $product->loadStockData();
```
Comment (kpodemski) [inline src/Adapter/Product/Repository/ProductRepository.php:461]: loadProduct = loadStockData? What's going on there?

Maybe would be better to have it as "loadRelatedData" or something like this?

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 6 above)
Comment (kpodemski) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: @jolelievre - this is a big PR, so forgive me if that's somewhere in the code, but does it mean that dynamic hooks from the ObjectModel don't work anymore?

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php [hunk 65]
```diff
@@ -75,25 +76,36 @@ final class ProductFormDataProvider implements FormDataProviderInterface
...
     ) {
         $this->queryBus = $queryBus;
         $this->defaultProductActivation = $defaultProductActivation;
         $this->mostUsedTaxRulesGroupId = $mostUsedTaxRulesGroupId;
-        $this->defaultCategoryId = $defaultCategoryId;
         $this->contextLangId = $contextLangId;
+        $this->defaultCategoryId = $defaultCategoryId;
+
+        // Usually context shop ID is null when multistore feature is disabled, in this case we use the default shop as fallback
+        $this->shopId = $contextShopId ?: $defaultShopId;
```
Comment (kpodemski) [inline src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: IMHO context should always return the default shopId even if multi-store is disabled. I like to think that multi-store is always there, but we may or may not use it. WDYT?

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php [hunk 66]
```diff
@@ -83,6 +83,7 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                     new Type(['type' => 'float']),
                 ],
                 'default_empty_data' => 0.0,
+                'modify_all_stores' => true,
```
Comment (kpodemski) [inline src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: if I didn't know what this is about, I would think that this field would be populated to all of the stores, no matter what

File: src/Adapter/AbstractObjectModelRepository.php [hunk 67]
```diff
@@ -73,28 +79,82 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+    /**
+     * @param int $id
+     * @param string $objectModelClassName
+     * @param ShopId $shopId
+     *
+     * @return bool
+     *
+     * @throws ShopAssociationNotFound
+     */
+    protected function hasShopAssociation(int $id, string $objectModelClassName, ShopId $shopId): bool
```
Comment (kpodemski) [inline src/Adapter/AbstractObjectModelRepository.php]: ObjectModel::isAssociatedToShop?

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 63 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php]: I didn't know these methods existed in the ObjectModel, thanks I'll refacto the abstract class a bit to rely on them!

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 64 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php:461]: Yep, if you prefer I don't mind it's true that loadProduct is a bit confusing

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php (hunk 65 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: Well actually it's because of how the shop context service behaves:
https://github.com/PrestaShop/PrestaShop/blob/824691139ee1ee220fc1a2f3b9d7b4fed5cd33f0/src/Adapter/Shop/Context.php#L60

And more precisely how the legacy Shop also behaves:

https://github.com/PrestaShop/PrestaShop/blob/7fb9828bec07e3de4bef4f0f949ceec2b765cc4c/classes/shop/Shop.php#L1025-L1031

In the service definition I rely on this method:
https://github.com/PrestaShop/PrestaShop/blob/7bd9e1810a7a870d62786927ecb3bbd82dcb0281/src/PrestaShopBundle/Resources/config/services/core/form/form_data_provider.yml#L152-L161

So what happens when you are in context ALL_SHOP is that `Shop::$context_id_shop` and `Shop::$context_id_shop_group` are both null (which makes sense in a way, we are not in single shop mode so we can't know what sop is selected in the context). So in this case I need to decide on which shop to fallback on, and my main was actually that in tests environment the value was null as well and caused bugs so the CI was broken

But while I answer this I actually think I have a better idea here, I introduced a special shop constraint for product and can use `ProductShopConstraint::defaultProductShop()` it means it uses the shop that has been assign as default to the product (in DB it's `product.id_shop_default` basically, from what I understood, this field is filled with either:
- the shop in context when the product is created/imported in a single shop context
- the default shop otherwise (multishop disabled or all shop context)

Anyway this product's default shop is "dynamic" as it can be different from one product to another, so I think it would be the best candidate for fallback in this case.

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php (hunk 66 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: The way the page works in multishop mode now has changed, but you're right this PR lacked description about this new feature especially since it's the first one and it only deals with the prices related fields. Other PRs will follow for other parts after this initial POC is validated.

I updated the PR description with more details about what to expect with new page regarding multishop, you should read it (I didn't want a too long comment here, that might be lost along the review and rebase ^^)

Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: TLDR; not every product's field are multishop, only those defined as such in the Product's definition (present in the product_shop table) actually handle the multishop override, the other ones will share the same value regardless of the shop context. This new option is basically used to identify which fields are handled by the multishop system, so they need to be "enabled" one by one the the form types.

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php (hunk 65 above)
Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: > Anyway this product's default shop is "dynamic" as it can be different from one product to another, so I think it would be the best candidate for fallback in this case.

Yes, good idea 👍

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: Hi @kpodemski by dynamic hooks do you mean the ones triggered by the ObjectModel in save/add/update methods?

If you refer to these then they are still triggered when you edit the form don't worry, but indeed not in this peculiar case. However this feature didn't exist in the previous page, the idea here is that if you have a product assigned to a single shop (and not all the shops) you had no way to assign it to another one.

Now we will add a new feature that allows to assign the product to another by copying the data of a source shop. This is the purpose of this service, such feature didn't exist previously as far as I know.

I inspired most of it from the `ShopController` and how it handles the duplication of the products (and other entities) when you create a new shop, which relies mostly on this method:

https://github.com/PrestaShop/PrestaShop/blob/ca46aade5238ce31de77223217951180ce0cce2d/classes/shop/Shop.php#L1179

As you can see it uses direct SQL queries and does not rely on ObjectModels in this case (as it would cost too much performance I think with too many objects being created). So the ObjectModel related hooks are not lost here, because the feature is new and even in copy shop data they were not called.

But correct me if I'm wonrg on this maybe I missed some things regarding the product's hooks. Just by answering you in this comment I realized that I actually could/should integrate a hook in this service. Either a new one or maybe the one that is already present in the Shop method:

https://github.com/PrestaShop/PrestaShop/blob/ca46aade5238ce31de77223217951180ce0cce2d/classes/shop/Shop.php#L1271

The problem is that this hook is generic to the shop copy, not the product only so I guess a new hook would be better.

What do you think of all this?

File: src/Adapter/AbstractObjectModelRepository.php (hunk 67 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: I didn't know of that one either, I will refacto to use it Thanks

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php (hunk 65 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: I think I'll do the same in `ProductFormDataHandler` (and so in the command builders as well) It's better to rely on a shop constraint indicating the product's default rather than on a shopId which would fall back to the global default shop.

Because nothing guarantees that the global default shop is the same as the product's default shop.

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 6 above)
Comment (kpodemski) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: Legacy behavior is that if you save the product, even for the new store, the `$object->update` is being executed.

My experience is that most of the developers don't use `actionShopDataDuplication`. It's barely available in the modules I've seen. Devs rely on the `actionObjectProductAdd`, `actionObjectProductUpdate`, etc.

Unfortunately, I think that if we are copying a product from one store to another, we need to fire the dynamic hooks from the `ObjectModel`, because they are related to many modules such as featured products, etc.

IMHO the most important thing is that cache needs to be cleared, but of course, we can't just clear the entire cache of the store because it's precarious. 

I need to investigate this further, @Matt75 who works in the extension team, might be helpful on this one.

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 64 above)
Comment (kpodemski) [reply src/Adapter/Product/Repository/ProductRepository.php:461]: It's almost like hydrating an object with additional data. Let's try to find a better naming 💪 

cc @PrestaShop/prestashop-maintainers

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php (hunk 66 above)
Comment (kpodemski) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: @jolelievre 

> This new option is basically used to identify which fields are handled by the multishop system, so they need to be "enabled" one by one the the form types.

I was at the meeting with y'all about the multi-store, and I think I remember that we talked about this, naming is a bit not on point for me. Because if this is only about the field being multi-store compatible, and checkbox saying "if you want to update this field in the context of all stores" let's not name it in a way where we can expect that this field is always updated in the context of all stores, what do you think? Right now, when I don't look at the front, but only read a code, I'm seeing that this field will be updated in the context of all stores, and that is not true, unless you check input.

 few ideas:

`'multistore_global_update_checkbox' => true`
`'multistore_checkbox' => true`
`'multistore_applicable' => true`
`'multistore_association' => true`
`'multistore_populate_checkbox' => true`

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php (hunk 65 above)
Comment (kpodemski) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: yes, totally! it should be possible to delete the product from a single context, so if one has:

Default shop: A

Product in the Shop A
Product in the Shop B

and deletes Product in the Shop B

and we have a problem

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 64 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php:461]: But no need to overthink this one It is specific to Product, it's in a private method and it just loads the stock data (by default the Product object model doesn't). Maybe `loadProductStock` is enough?

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php (hunk 65 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: Mmm, I think there is more a problem when you delete product from Shop A (which is the default one)

Indeed, but I'll handle this use case in a later PR, when I will introduce the command `RemoveProductFromShop` (naming not decided yet), in which case we will handle the automatic redefinition of the product's default shop, to make sure the data stays consistent This command will be handled in the multishop header new component that helps with the association with other shops

As for the listing, I don't know yet how we will handle the removal. One possibility would that we rely on this `RemoveProductFromShop` command, and when it detects that no shops are associated to the product then it removes it for good (either soft delete or hard delete depending on the product's associations)

File: src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php (hunk 66 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Sell/Product/Pricing/RetailPriceType.php]: Just to make sure we're on the same page, what this option does:
- when `modify_all_stores` is true a checkbox is associated to the field
  - if the checkbox is checked then the modification is applied to all the associated shops
  - if not the modification is applied to the shop selected in the current context only

Regardless of this option, there is no more "All shop context" in the product page.

So if I understand your comment, the option name makes it sound like no matter what the modification will ALWAYS be applied to all shops, so it doesn't emphasize enough on the fact that it is linked to a toggable feature related to a checkbox right?

Then maybe we could rename it `is_modifiable_for_all_stores` ?

File: src/Adapter/AbstractObjectModelRepository.php (hunk 67 above)
Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: So after checking I can't use `ObjectModel::isAssociatedToShop` in this situation, it only works on an instanciated object, like `$product->isAssociatedToShop($shopId)`

But here it is not the exact same use case, I need to check the existence based on IDs and object type alone to avoid relying on a instance of ObjectModel, that's why I think it's better to keep it that way here

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 63 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php]: For the same reason as your comment related to `isAssociatedToShop` using `getAssociatedShops` required the legacy object to be instanciated to be used.

Form now I admit that this method is only used in `partialUpdateForShopConstraint` which uses an instance of `Product` but this method will likely be useful in other uses cases where we need to get the list of associated shops for a product for example. 

I admit this new kind of repositories are a bit confusing because they mix doctrine queries and use of ObjectModel, also not all of them use the Doctrine connection, so I can't even integrate the connection and dbPrefix in the abstract class.

I think it would be worth thinking of a way to distinct and combine these two kinds of repositories for cleaner implementation, but that would be the purpose of another PR.

File: src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php (hunk 65 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/DataProvider/ProductFormDataProvider.php]: Done! As we said the now the provider uses the product's own default shop as a fallback when no context shop is selected Same for update commands (along all the command builder chain).

I just kept the global default shop ID for the CreateProductCommand, since the product can't have its own default shop when being created, the global default shop seems like a good candidate for fallback.

File: src/Adapter/Product/Update/ProductShopUpdater.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Product/Update/ProductShopUpdater.php]: @kpodemski indeed that makes sense, even though this feature is new I understand that it will be simpler for modules to integrate with it we keep on relying on the dynamic hooks

Good news is I was able to refacto this method quite quickly, by relying on the existing methods that were introduced in this PR, the copy method basically does:
- get product with shop constraint on source shop
- update product with shop constraint on target shop

For now it seems to work fine, at least all the behat tests regarding prices are still green, we'll probably need to look into more details for other scopes (by adding relevant behat tests), and especially regarding the associations but it's for another PR.

So now when a product is copied into another one the hooks `actionObjectUpdateBefore` (and after, and for product) will be triggered, even when the product was not previously associated to the shop.

Do you think it's ok this way, or should I make it so that the create hook is triggered instead? I think the update one is more suited but I prefer to be sure.

File: admin-dev/themes/new-theme/js/components/modify-all-stores-checkbox/index.ts [hunk 68]
```diff
@@ -0,0 +1,93 @@
...
+
+  /**
+   * @param {string} modifyAllNamePrefix
+   */
+  constructor(modifyAllNamePrefix = '') {
+    if (!modifyAllNamePrefix) {
+      this.modifyAllNamePrefix = 'modify_all_stores_';
+    } else {
+      this.modifyAllNamePrefix = modifyAllNamePrefix;
+    }
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/components/modify-all-stores-checkbox/index.ts]:
```suggestion
    this.modifyAllNamePrefix = (!modifyAllNamePrefix) ? 'modify_all_stores_' : modifyAllNamePrefix;
```

File: classes/ObjectModel.php (hunk 38 above)
Comment (jolelievre) [reply classes/ObjectModel.php]: This fix has been extracted into a dedicated PR https://github.com/PrestaShop/PrestaShop/pull/25913

File: src/Adapter/AbstractObjectModelRepository.php (hunk 12 above)
Comment (PierreRambaud) [reply src/Adapter/AbstractObjectModelRepository.php]: It should be `class-string<ObjectModel>` and not `class-name` :thinking:

**Review by matks — COMMENTED** [review]
Sorry but... it's needed to rebase.

As soon as it's rebases, ping me, I'll do the review again.

File: src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig [hunk 69]
```diff
@@ -99,6 +99,7 @@
 
     {{- form_widget(form) -}}
     {{- form_errors(form) -}}
+    {{- block('form_modify_all_stores') -}}
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig]: Add comment to explain this (on the block as well)

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig]: Document in Dev doc

File: src/Adapter/AbstractObjectModelRepository.php [hunk 70]
```diff
@@ -74,28 +80,82 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
+    /**
+     * @param int $id
+     * @param string $objectModelClass
+     * @param string $exceptionClass
+     *
+     * @return ObjectModel
+     *
+     * @throws CoreException
+     */
+    protected function getObjectModelForShop(int $id, string $objectModelClass, string $exceptionClass, ShopId $shopId): ObjectModel
```
Comment (jolelievre) [inline src/Adapter/AbstractObjectModelRepository.php]: Split the multishop functions and move them into a dedicated multishop abstract
The ProductRepository will have to extend this new abstract, temporarily we will have two product repositories one multishop one "classic" the aim is to replace the classic one with the multishop one piece by piece and finally only keep the multishop one (which will be renamed into ProductRepository at that final point)

File: src/Adapter/AbstractObjectModelRepository.php [hunk 71]
```diff
@@ -74,28 +80,82 @@ protected function assertObjectModelExists(int $id, string $objectTableName, str
...
     }
 
+    /**
+     * @param int $id
+     * @param string $objectModelClassName
+     * @param ShopId $shopId
+     *
+     * @return bool
+     *
+     * @throws ShopAssociationNotFound
```
Comment (jolelievre) [inline src/Adapter/AbstractObjectModelRepository.php]: Remove this

File: src/Adapter/AbstractObjectModelRepository.php [hunk 72]
```diff
@@ -127,6 +187,32 @@ protected function addObjectModel(ObjectModel $objectModel, string $exceptionCla
...
+     * @param string $exceptionClass
+     * @param int $errorCode
+     *
+     * @return int
+     */
+    protected function addObjectModelToShop(ObjectModel $objectModel, int $shopId, string $exceptionClass, int $errorCode = 0): int
+    {
+        // Store object's list of shop ID to reset it appropriately after the update
+        $savedShopIds = $objectModel->id_shop_list;
+        $objectModel->id_shop_list = [$shopId];
```
Comment (jolelievre) [inline src/Adapter/AbstractObjectModelRepository.php]: Comment this better (and in the ObjectModel as well)

Comment (jolelievre) [reply src/Adapter/AbstractObjectModelRepository.php]: Be careful this might change the `id_shop_default` check that we don't mess with it

File: src/Adapter/AbstractObjectModelRepository.php [hunk 73]
```diff
@@ -127,6 +187,32 @@ protected function addObjectModel(ObjectModel $objectModel, string $exceptionCla
...
+
+        try {
+            $object = $this->addObjectModel($objectModel, $exceptionClass, $errorCode);
+        } catch (Exception $e) {
+            // Even if an error occurs we reset the initial object's inner data, but without blocking the exception
+            $objectModel->id_shop_list = $savedShopIds;
+            throw $e;
+        }
+
+        $objectModel->id_shop_list = $savedShopIds;
```
Comment (jolelievre) [inline src/Adapter/AbstractObjectModelRepository.php]: Simplify this, no need to reset this

File: src/Core/Domain/Product/ValueObject/ProductShopConstraint.php [hunk 74]
```diff
@@ -0,0 +1,91 @@
...
+     * @var bool
+     */
+    protected $defaultProductShop;
+
+    /**
+     * Constraint to get product values for its default shop.
+     *
+     * @return static
+     */
+    public static function defaultProductShop(): self
```
Comment (jolelievre) [inline src/Core/Domain/Product/ValueObject/ProductShopConstraint.php]: Remove this extra shop constraint along with the class itself
The product default shop can be fetched in advance nad used as a regular ShopId constraint

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 75]
```diff
@@ -410,4 +465,151 @@ public function searchProducts(string $searchPhrase, LanguageId $languageId, Sho
...
+        ;
+
+        $result = $qb->execute()->fetchAll();
+        if (empty($result)) {
+            return [];
+        }
+
+        $shops = [];
+        foreach ($result as $shop) {
+            $shops[] = new ShopId((int) $shop['id_shop']);
```
Comment (jolelievre) [inline src/Adapter/Product/Repository/ProductRepository.php]: Cache this result using a CacheAdapter
Add methods to clear the cache when a write action is performed (typically associate or un associate a shop), but also allow to clear manually

File: src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php (hunk 57 above)
Comment (jolelievre) [reply src/Core/Form/IdentifiableObject/CommandBuilder/Product/ProductCommandsBuilder.php]: This is a temporary interface, when we migrate everything we will remove it all builders will have a mandatory ShopConstraint (ad a @todo in the code not to forget this)

**Comment by Progi1984** [comment]
@jolelievre Needs a rebase

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 75 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php]: @eternoendless on second thought since this method is not used very much for now I'm not sure it deserves to be cached The only moment when it's called is when a product is updated, it's a critical moment where we want to be sure we have up-to-date data

I'm not against adding some caching in this repository at some point, but it might be a bit early for that Since right now we only have one use case for now when we know we need to clear the cache: `CopyProductToShop` command

So I'd leave this one for later

File: .gitignore [hunk 76]
```diff
@@ -118,6 +118,8 @@ tests/Resources/img/c/*
 !tests/Resources/img/c/.gitkeep
 tests/Resources/img/tmp/*
 tests/Resources/img/tmp/.gitkeep
+tests/Resources/img/m/*
+!tests/Resources/img/m/.gitkeep
```
Comment (PierreRambaud) [inline .gitignore]: Images are automatically created in `tests/Resources/img` maybe ignore the whole directory instead

Comment (jolelievre) [reply .gitignore]: Well that's what the `*` rule does, it ignores the whole content, but we still have a `.gitkeep` file in the folder that is on the repository so it shouldn't be ignored (even if it's already added so it doesn't change much) All our empty folders are usually handled this way in gitignore

**Comment by tswfi** [comment]
Does this handle different tax settings per shop also?

**Comment by jolelievre** [comment]
Hi @tswfi what do you mean exactly by that?

If it's about setting a different tax rule per shop then yes it's handled with this PR.

If it's about proposing only the taxes associated to the current shop in the selector then I admit I'm not sure it was not the purpose of this PR, or at least I didn't think about it. But it could be handled in a different issue/PR.

**Comment by jolelievre** [comment]
@tswfi about the second question I had.

I just tested it, it turns out the tax list is already filtered based on shop context.

So when you will edit your product in signal shop context:
- the tax list only contains tax rules associated with the shop
- and of course, you can define a different tax rule for each shop
-

File: admin-dev/themes/new-theme/js/components/modify-all-shops-checkbox/index.ts [hunk 77]
```diff
@@ -0,0 +1,98 @@
...
+
+import MultiShopModifyAllMap from './component-map';
+
+const {$} = window;
+
+/**
+ * Enables multi shop modify all checkboxes on the page. The checkboxes are hidden by default,
+ * they appear on input focus and stay visible when the value changed.
+ */
+export default class ModifyAllShopsCheckbox {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/components/modify-all-shops-checkbox/index.ts:34]: The name looks really too generic, I'm unable to find what this component is doing even with the description and it looks not adapted to a class, what about something like `AllShopContextCheckbox` or if you have a better idea..

**Review by NeOMakinG — COMMENTED** [review]
Just a little comment because of a naming overwise everything looks fine to me

File: src/Adapter/Product/Repository/ProductMultiShopRepository.php [hunk 78]
```diff
@@ -0,0 +1,389 @@
...
+use PrestaShop\PrestaShop\Core\Repository\AbstractMultiShopObjectModelRepository;
+use PrestaShopException;
+use Product;
+
+/**
+ * @todo: This class has been added while we progressively migrate each domain to multishop It contains the new
+ *        dedicated function bound with multishop When everything has been migrated they will be moved back to
+ *        the initial ProductRepository and single shop methods should be removed But since this will be done
+ *        in several PRs for now it's easier to separate them into two services
+ *        This is why a lot of code is duplicated between the two classes but don't worry this one is only temporary
```
Comment (matks) [inline src/Adapter/Product/Repository/ProductMultiShopRepository.php:63]: 👀

File: src/Adapter/Product/Repository/ProductRepository.php [hunk 79]
```diff
@@ -96,27 +92,28 @@ class ProductRepository extends AbstractObjectModelRepository
...
         $this->connection = $connection;
         $this->dbPrefix = $dbPrefix;
         $this->productValidator = $productValidator;
-        $this->defaultCategoryId = $defaultCategoryId;
         $this->taxRulesGroupRepository = $taxRulesGroupRepository;
         $this->manufacturerRepository = $manufacturerRepository;
     }
 
     /**
+     * @todo: Not sure this should be in the repository as it gives a false feeling the the repository can duplicate a
```
Comment (matks) [inline src/Adapter/Product/Repository/ProductRepository.php:113]: What about we remove it then? Or throw an exception?

File: src/Core/Domain/Shop/Exception/ShopAssociationNotFound.php [hunk 80]
```diff
@@ -0,0 +1,36 @@
+<?php
```
Comment (matks) [inline src/Core/Domain/Shop/Exception/ShopAssociationNotFound.php:1]: github syntax color does not apply to this file. any idea? wrong warning?

File: src/Core/Repository/AbstractMultiShopObjectModelRepository.php [hunk 81]
```diff
@@ -0,0 +1,176 @@
...
+     * @param string $objectModelClassName
+     * @param ShopId $shopId
+     *
+     * @return bool
+     */
+    protected function hasShopAssociation(int $id, string $objectModelClassName, ShopId $shopId): bool
+    {
+        $modelDefinition = $objectModelClassName::$definition;
+        $objectTable = $modelDefinition['table'];
+        $primaryColumn = $modelDefinition['primary'];
```
Comment (matks) [inline src/Core/Repository/AbstractMultiShopObjectModelRepository.php:139]: Should we create some helper functions `getPrimaryColumn()` on ObjectModel to make it reusable? we could force the `bqSQL()` inside

File: src/Core/Repository/AbstractMultiShopObjectModelRepository.php [hunk 82]
```diff
@@ -0,0 +1,176 @@
...
+            ->where('e.`id_shop` = ' . $shopId->getValue())
+        ;
+
+        try {
+            $row = Db::getInstance()->getRow($query, false);
+        } catch (PrestaShopDatabaseException $e) {
+            $row = false;
+        }
+
+        return !empty($row['id']);
```
Comment (matks) [inline src/Core/Repository/AbstractMultiShopObjectModelRepository.php:155]: `isset` or `empty`?

File: src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php [hunk 83]
```diff
@@ -0,0 +1,160 @@
...
+    public function buildForm(FormBuilderInterface $builder, array $options)
+    {
+        if (!$this->multistoreContextChecker->isSingleShopContext()) {
+            return;
+        }
+
+        $isOverridden = $builder->getOption('modify_all_shops');
+        if ($isOverridden) {
+            $label = $this->getCheckboxLabel();
+            $builder->addEventListener(FormEvents::PRE_SET_DATA, static function (FormEvent $event) use ($label) {
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php]: Why static?

File: src/Core/Domain/Shop/Exception/ShopAssociationNotFound.php (hunk 80 above)
Comment (jolelievre) [reply src/Core/Domain/Shop/Exception/ShopAssociationNotFound.php:1]: Don't know it happens sometimes, but I don't know the reason why

File: src/Adapter/Product/Repository/ProductRepository.php (hunk 79 above)
Comment (jolelievre) [reply src/Adapter/Product/Repository/ProductRepository.php:113]: Because it's not the scope of this PR at all, it's just to avoid forgetting this refacto is required

File: src/Core/Repository/AbstractMultiShopObjectModelRepository.php (hunk 81 above)
Comment (jolelievre) [reply src/Core/Repository/AbstractMultiShopObjectModelRepository.php:139]: I can add a static method in ObjectModel for that indeed However I don't think the `bqSQL` must be included inside, in case the method is used for another purpose than creating an SQL request

`bqSQL` should only be used when build the request

File: src/Core/Repository/AbstractMultiShopObjectModelRepository.php (hunk 82 above)
Comment (jolelievre) [reply src/Core/Repository/AbstractMultiShopObjectModelRepository.php:155]: empty, in case it returns 0

File: src/Core/Repository/AbstractMultiShopObjectModelRepository.php (hunk 81 above)
Comment (jolelievre) [reply src/Core/Repository/AbstractMultiShopObjectModelRepository.php:139]: Actually, it's counterproductive, since I also need to get the table from the definition it's actually more efficient to get the whole definition and pick the necessary fields

I could create two static methods (one for table and one for primary column), but it seems like it becomes a bit overkill

File: src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php (hunk 83 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Extension/ModifyAllShopsExtension.php]: No reason! I just copied it from `MultistoreConfigurationTypeExtension` and I didn't notice I fixed both code

**Review by matks — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]
Awesome PR 👍

**Comment by matthieu-rolland** [comment]
I sent this PR in QA despite the `waiting for wording` label since it's blocking many subjects, wording can still be changed later

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php [hunk 84]
```diff
@@ -488,7 +513,7 @@ private function renderDisableMultistorePage(int $productId = null): Response
     {
         return $this->render('@PrestaShop/Admin/Sell/Catalog/Product/disabled.html.twig', [
             'errorMessage' => $this->trans(
-                'This page is not yet compatible with the multistore feature. To access the page, please [1]disable the multistore feature[/1].',
+                'This page is only compatible with the single store context. To access the page, please select a store or [1]disable the multistore feature[/1].',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]:
```suggestion
                'This page is only compatible in a single store context. To access the page, please select a store or [1]disable the multistore feature[/1].',
```

**Review by Julievrz — COMMENTED** [review]
It would be nice if you could make this wording change before merging. It would avoid creating another PR.

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php [hunk 85]
```diff
@@ -479,6 +484,26 @@ private function addFlashMessageProductV2IsDisabled(): void
...
+     * @param int $productId
+     *
+     * @return Response
+     */
+    private function renderMissingAssociation(int $productId): Response
+    {
+        //@todo this error message should be improved to indicate which shop can/should be used for this product and/or how to associate it to the current context
+        return $this->render('@PrestaShop/Admin/Sell/Catalog/Product/disabled.html.twig', [
+            'errorMessage' => $this->trans(
+                'This product is not associated to the store selected in the current context, please select another one.',
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]:
```suggestion
                'This product is not associated with the store selected in the multistore header, please select another one.',
```
I just have a doubt about "multistore header" as it's not available on all pages. In any case, we should replace "associated to" with "associated with". :-)

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I have some issues:

**First issue**
1. Go to BO > Advanced Parameters > Experimental Features page & Enable Experimental product page
2. Multistore context is disabled & we have only one shop
3. Go to BO > Catalog > Products > Edit a product V2
4. In the Pricing Tab, if we modify all fields => the checkbox "Apply changes to all stores" is displayed, but we don't have any shops

I think it shouldn't be displayed 
image

Also, I have a similar problem in another case following these steps:
1. We have already two shops: ShopA & ShopB
2. We have a productA available only in the ShopA
3. If we edit this productA, in the pricing tab => if we modify all fields => the checkbox "Apply changes to all stores" is displayed, but this product is only compatible with shopA

**Second issue**

1. Go to BO > Advanced Parameters > Experimental Features page & Enable Experimental product page
2. Go to BO > Catalog > Products > Edit a product V2
3. In the pricing tab,> Click on the field `Retail price (tax excl.)`, then click on the field `Retail price (tax incl.)`, then click on the `Tax rule`
4. See error 

image

I attached a screen record

https://user-images.githubusercontent.com/16067358/150323081-72c34878-3609-44fc-8e4a-1e57ce18e54c.mp4

**Third issue**
1. Go to BO > Advanced Parameters > Experimental Features page & Enable Experimental product page
2. Enable multistore context and create a new shop > we have two shops: shopA & shopB
3. Create a product in all shops & set the `Retail price (tax excl.)` & `Retail price (tax incl.)` & `Tax rule` & `Retail price per unit (tax excl.)` different from 0
4. ShopA is selected, edit this product V2
5. Change the tax rule and click on the checkbox of `Retail price (tax incl.)` => `Retail price (tax excl.)` will be automatically clicked
6. Click also on the checkbox of `Retail price per unit (tax incl.)` => `Retail price per unit (tax excl.)` will be automatically clicked
7. Save
8. Select shopB
9. In the Pricing tab, you can check that `Retail price (tax incl.)` & `Retail price per unit (tax incl.)` are not changed
10. Is it a normal behavior?

I attached a screen record


https://user-images.githubusercontent.com/16067358/150326078-edb0a7cc-8fac-48fb-b741-dbe958450168.mp4


Thanks!

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 

I tested the bugs you found:

### First issue
Indeed the checkboxes were always added (though they were hidden at first in my case). I fixed this so that they are not added when the multishop is disabled or if there is only one shop created.

For your second question, it is not planned to hide the checkbox in case the product is only associated in one shop. It can be an improvement (although I'm not sure how to deal with it technically 😅 ) But it's not the scope of this PR. @MatShir This was not specified yet, as far as I know, do you think this should be handled in an issue as an improvement?

### Second issue

I'm not sure to understand this one, is it when multishop is active or not? And what is the bug exactly? Is it the extra offset under the tax selector panel?

If it was only when multishop is disabled then maybe it's fixed thanks to the first fix. If it's about the panel which has an offset I can't reproduce it.

### Third issue

This is the expected behaviour. The input price tax excluded and tax included are actually only one field, only the price tax excluded is saved. The price tax included is here to help edit and it automatically computes the value of price tax excluded. So when one checkbox is clicked it is synced with the other. Same principle for unit price tax excl and tax incl.

And regarding the video you made where it doesn't update the included value it's also related. The only persisted value is the tax excluded which is correctly applied everywhere (the value is 10 in all shops) However the tax rule is different depending on the shop (because you didn't check the multishop checkbox so it makes sense) which explains why the value tax included is different.

File: src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php (hunk 85 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController.php]: It is available on this page when multishop is active so it seems all good

**Comment by jolelievre** [comment]
@Julievrz I updated the wording as you sggested

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @jolelievre,

It is Ok :heavy_check_mark: 
I tried these cases:
1. Multishop context disabled
2. Multishop context enabled + 1 shop created
3. Two shops with the same group
4. 4 shops from different groups
5. I tried to create 4 types of products (Simple + product with combinations + Vector + pack)
6. I tried to make an order for each shop with the same product but prices are different from each shop


https://user-images.githubusercontent.com/16067358/151393136-90b6668c-8cdf-4d7d-886a-289b18b2409b.mp4

Also, I checked this [issue](https://github.com/PrestaShop/PrestaShop/issues/18919) => fixed

https://user-images.githubusercontent.com/16067358/151395948-69c04cde-8d04-4c48-998c-d509094ef7da.mp4

PS: I found some other issues related to the multishop but not the scope of this PR.

About this bug, We will create a sperate issue
**Second issue**

```
1. Go to BO > Advanced Parameters > Experimental Features page & Enable Experimental product page
2. Go to BO > Catalog > Products > Edit a product V2
3. In the pricing tab,> Click on the field `Retail price (tax excl.)`, then click on the field `Retail price (tax incl.)`, then click on the `Tax rule`
4. See error 
```



Thanks!

**Comment by PierreRambaud** [comment]
Thank you @jolelievre great job (as usual)

**Comment by Robin-Fischer-PS** [comment]
And thanks @khouloudbelguith for your great test (as usual too :D ) !

**Comment by jolelievre** [comment]
Here is the issue for the remaining UX bug https://github.com/PrestaShop/PrestaShop/issues/27497

**Comment by matks** [comment]
Bravo bravo bravo 🎉
