### PR TITLE
Get page title respecting dedicated meta title and combination information

### LINKED ISSUE #21391: FO - The product meta-title is incorrect after changing a combination
#### Describe the bug

the automatic page reload on product detail pages causes the meta title to get replaced with the product name

Issue is this line:
https://github.com/PrestaShop/PrestaShop/blob/b70d51837420275c5ad8c717162ddddb169e00d1/controllers/front/ProductController.php#L458

it needs to use $product['meta_title'] instead of $product['title']

#### Expected behavior

meta title should stay as it is

#### Steps to Reproduce

1. Have a product with a meta title != its name
2. Go to that product's front page
3. Either wait for the initial reload or change a combination or the quantity to cause one

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This is follow up for https://github.com/PrestaShop/PrestaShop/issues/21391
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21391 
| How to test?  | Detailed instruction below.
| Sponsor company | impSolutions

Previous version fixed an issue with not correctly displayed `meta_title` after changing combination, but it was not working properly with setting from Shop Parameters -> Traffic & SEO -> Display attributes in the product meta title  -> YES

## How to test?

0. Set "Display attributes in the product meta title" to "YES"
1. Edit product ID 1
2. Set meta title to: Dedicated meta title
3. Go to product page, see that the current title is:
> Dedicated meta title Size S Color White
4. Now change combination, see that title is:
> Dedicated meta title

NOK

Point 4 should change meta title to:
> Dedicated meta title Size S Color Black

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21783)

### CODE REVIEW

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -469,7 +469,9 @@ public function displayAjaxRefresh()
             'product_has_combinations' => !empty($this->combinations),
             'id_product_attribute' => $product['id_product_attribute'],
             // We use the meta_title key because product_title is used for the title of the page
-            'product_title' => $product['meta_title'],
+            'product_title' => $this->getProductPageTitle(
+                $this->getTemplateVarPage()['meta'] ?? []
+            ),
```
Comment (PululuK) [inline controllers/front/ProductController.php:473]: Remove comment above too.

**Review by PululuK — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM the meta title is correctly set and updated
image
Thanks @kpodemski !!

**Comment by PululuK** [comment]
Thanks @kpodemski
