### PR TITLE
Fetch and set logo image size inside template

### LINKED ISSUE #25853: Width and Height values are fixed for Header shop logo
#### Describe the bug

In prestashop 1.7.8 with recent changes to fix CLS, fixed values for width and heigh has been added to template. That causing problem when someone is adding images with different ratio than has been assumed.

#### Expected behavior

Header template - [this lines](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.0-build/themes/classic/templates/_partials/header.tpl#L65), value shouldn't be fixed.
In FrontController.php we could replace that 'logo' field in `$shop` array with new structure:
```
'logo' => [
  'src' => $logoSrc,
  'width' => $logoWidth,
  'height' => $logoWidth
]
```
Values could be fetched with getimagesize function.
Don't forget about `themes/classic/templates/checkout/_partials/header.tpl` where logo is also used. 

#### Steps to Reproduce

1. In BO go to Design->Theme & Logo.
2. Replace shop logo with this [image](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Prestashop.svg/1024px-Prestashop.svg.png)
3. Go to FO, and inspect shop logo in browser.
4. Images width and height values will be `width="100" height="28"` even if images ratio is different. 

#### Additional information

* PrestaShop version: 1.7.8
* PHP version: N/A

### PR DESCRIPTION
**Pull request by Oksydan**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Instead of setting width and height fixed for shop logo, we are fetching it size and set proper width and height values. It required to adjust json-ld where logo was fetched from `$shop.logo`. <br>  We are changing `$shop.logo` variable from `string` to `array` and it is breaking change. Themes and module that are using `$shop.logo` as src logo will have to change it to `$shop.logo.src`. 
| Type?             | bug fix
| Category?         | FO
| BC breaks?        |  yes
| Deprecations?     |  no
| Fixed ticket?     | Fixes #25853
| How to test?      | Follow instruction inside issue.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25857)

### CODE REVIEW

File: classes/controller/FrontController.php [hunk 1]
```diff
@@ -1622,6 +1622,26 @@ public function getTemplateVarCustomer($customer = null)
...
+            $logoFileDir = $logoDir . $logoFileName;
+            $logoSizes = getimagesize($logoFileDir);
+
+            $logoData['src'] = $psImageUrl . $logoFileName;
+            $logoData['width'] = $logoSizes[0];
+            $logoData['height'] = $logoSizes[1];
+        }
+
+        return $logoData;
+    }
```
Comment (kpodemski) [inline classes/controller/FrontController.php]:
```suggestion
    /**
     * Get the shop logo with its dimensions
     *
     * @return array
     */
    public function getShopLogo(): array
    {
        if (!Configuration::hasKey('PS_LOGO')) {
            return [];
        }
        
        $logoFileName = Configuration::get('PS_LOGO');
        list($logoWidth, $logoHeight) = getimagesize(_PS_IMG_DIR_ . $logoFileName);
        
        return [
            'src' => ($this->getTemplateVarUrls()['img_ps_url'] ?? _PS_IMG_) . $logoFileName,
            'width' => $logoWidth,
            'height' => $logoHeight
        ];
    }
```

@Oksydan WDYT? :D

Comment (Oksydan) [reply classes/controller/FrontController.php]: @kpodemski You just made me feel like I know nothing about PHP 😂

**Comment by Oksydan** [comment]
@kpodemski thank you.
I just copied and pasted your stuff. Now I feel small 😄

File: classes/controller/FrontController.php (hunk 1 above)
Comment (kpodemski) [reply classes/controller/FrontController.php]: @Oksydan no, no, it's just a little optimization, you don't need to set variables if you use them once, return early if no need to continue, etc. 👍

**Review by kpodemski — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
@Oksydan please document the BC break inside the description of the PR :)

File: classes/controller/FrontController.php [hunk 2]
```diff
@@ -1622,6 +1622,27 @@ public function getTemplateVarCustomer($customer = null)
         return $cust;
     }
 
+    /**
+     * Get the shop logo with its dimensions
+     *
+     * @return array
```
Comment (Progi1984) [inline classes/controller/FrontController.php]:
```suggestion
     * @return array<string, string|int>
```

**Review by Progi1984 — DISMISSED** [review]

File: classes/controller/FrontController.php [hunk 3]
```diff
@@ -1622,6 +1622,27 @@ public function getTemplateVarCustomer($customer = null)
...
+     */
+    public function getShopLogo(): array
+    {
+        if (!Configuration::hasKey('PS_LOGO')) {
+            return [];
+        }
+
+        $logoFileName = Configuration::get('PS_LOGO');
+        list($logoWidth, $logoHeight) = getimagesize(_PS_IMG_DIR_ . $logoFileName);
```
Comment (PierreRambaud) [inline classes/controller/FrontController.php]: Could you check if the file exists before using getimagesize?

**Comment by Oksydan** [comment]
@NeOMakinG information added.
@PierreRambaud @Progi1984 thank you for your reviews.
All suggestions applied.

**Review by NeOMakinG — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Progi1984** [comment]
@Oksydan Could you target `1.7.8.x` branch for fixing the bug in the next patch release ?

**Comment by Oksydan** [comment]
@Progi1984 branch rebased with 1.7.8.x, target changed.

File: themes/classic/templates/_partials/header.tpl [hunk 4]
```diff
@@ -54,22 +54,32 @@
...
     <div class="container">
        <div class="row">
         <div class="col-md-2 hidden-sm-down" id="_desktop_logo">
+          {if $shop.logo}
             {if $page.page_name == 'index'}
               <h1>
-                <a href="{$urls.pages.index}">
-                  <img class="logo img-responsive" src="{$shop.logo}" alt="{$shop.name}" loading="lazy" width="100" height="28">
-                </a>
+                {renderLogo}
```
Comment (NeOMakinG) [inline themes/classic/templates/_partials/header.tpl:77]: This thing looks so weird to me (not related to the PR), I think we should add a title somewhere else that surrounding the logo, right?

**Review by NeOMakinG — APPROVED** [review]

File: themes/classic/templates/_partials/header.tpl (hunk 4 above)
Comment (Oksydan) [reply themes/classic/templates/_partials/header.tpl:77]: @NeOMakinG yea it is weird it was introduced in https://github.com/PrestaShop/PrestaShop/commit/57269252d42c26b6e50974db6a7890ece837dd95#diff-8ada98d9b9b82420991362832e15678cdd981b2eaef44cc880074a98271dbb9c 
I am not SEO expert so I have no idea why it is here.

Comment (NeOMakinG) [reply themes/classic/templates/_partials/header.tpl:77]: Usually in my past jobs, we were adding an h1 inside the topbar, so the h1 is always a text on top level, and it was working pretty fine respecting SEO standards, I think we need to change this in the future (maybe in the new theme?)

**Review by kpodemski — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Oksydan ,

Thanks for the PR !
All good to me :
Screenshot 2021-10-04 at 18 00 00

**Comment by PierreRambaud** [comment]
Thank you @Oksydan

**Comment by PrestaEdit** [comment]
Hi @everyone here !

Could you explain me why we introduce a BC break as this one that will affect every theme on 1.7.8 inside this minor version ? 🤔

**Comment by kpodemski** [comment]
Hi @PrestaEdit 

We discussed it internally, and maybe the solution would be to leave the old variable and introduce a new one. What do you think?

**Comment by PrestaEdit** [comment]
That a BC break could not be added into a .1 version as it, for sure.
At least to a 1.7.9 if you want, but not there.

Like 90% of theme will be broken with this update, for sure. A change that they can handle fast, but not sure that it's a normal thing.

**Comment by kpodemski** [comment]
Of course, I understand. I'm asking what do you think about the proposed solution 😎 

We leave `$shop.logo`
We add `$shop.logo_with_dimensions` or whatever

**Comment by PrestaEdit** [comment]
As you know, I dislike having this kind of extra vars, even if I have no other solution really.

Or having simply an entry in the logo array as "logo_sizes" ?

**Comment by kpodemski** [comment]
@PrestaEdit, that's what I was thinking. I meant `$shop.logo`, not `$shop` 👍

**Comment by Oksydan** [comment]
@kpodemski @PrestaEdit 
You are right i didn't think about backwards compatibility with it.
We can add `$shop.logo_with_dimension` and leave `$shop.logo` as it was before.

File: themes/classic/templates/_partials/header.tpl [hunk 5]
```diff
@@ -54,22 +54,32 @@
   </nav>
 {/block}
 
+{function renderLogo}
+  <a href="{$urls.pages.index}">
+    <img
+      class="logo img-fluid"
+      src="{$shop.logo.src}"
+      alt="{$shop.name}"
+      loading="lazy"
```
Comment (SharakPL) [inline themes/classic/templates/_partials/header.tpl:63]: Main place for logo is the header, very top of the page on all devices so almost always in the viewport on page load.
That's [not the best place for using lazy loading](https://web.dev/browser-level-image-lazy-loading/#avoid-lazy-loading-images-that-are-in-the-first-visible-viewport)

Comment (NeOMakinG) [reply themes/classic/templates/_partials/header.tpl:63]: Is it really changing something anyway?

Comment (SharakPL) [reply themes/classic/templates/_partials/header.tpl:63]: >Images that are eagerly loaded can be fetched right away, while images which are loaded lazily the browser currently needs to wait until it knows where the image is positioned on the page, which relies on the IntersectionObserver to be available.

Basically it slows down loading, because it needs to calculate its position first and that's useless for header's logo. It's all about best practices :)

Comment (SharakPL) [reply themes/classic/templates/_partials/header.tpl:63]: https://github.com/PrestaShop/PrestaShop/blob/f8210fbaeaf373ee23d125fd4d9e8c6e947668b5/themes/classic/modules/ps_imageslider/views/templates/hook/slider.tpl#L38
First slide of ps_imageslider should also be without `loading="lazy"` as it's almost always visible right away, even on mobile when it's enabled.

Comment (Oksydan) [reply themes/classic/templates/_partials/header.tpl:63]: @SharakPL it isn't slowing anything THB, it might not be a necessary but it doesn't change anything. It is native lazyloading not js base lazyloading for images. It don't have to wait in execution stack to be executed after other scripts.

Comment (SharakPL) [reply themes/classic/templates/_partials/header.tpl:63]: Well, I guess that's pointless anyway. In 2021 it should be possible to use SVG as logo in Prestashop.

Comment (Oksydan) [reply themes/classic/templates/_partials/header.tpl:63]: @SharakPL yes, you are right it is pointless here and you are right about allowing us to use svg logo for shop. If you are interested in, I can create module that will allow you to upload svg logo for your shop.

Comment (SharakPL) [reply themes/classic/templates/_partials/header.tpl:63]: Thanks but I managed that myself. The point is to have that option by default in Design -> Themes
