### PR TITLE
Fix BO Units on inputs

### LINKED ISSUE #28892: BO - Product V1 - Shipping & Pricing tab - Units are not well displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Product V1 > Shipping tab, the units are not displayed
image

In the BO > Catalog > Product V1 > Pricing tab > Add new specific price >  the units are not displayed 
image

### Expected behavior

PS1786 => ok
image
PS1786 => ok
image

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Add/Edit a product
3. In the Shipping tab > See error: the units are not well displayed
4. In the Pricing tab > Add a specific  price > See error: the units are not well displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Description?    | Since commit 1ac33da1254044268a2c0f8a8e9d4907947bba4a, form types have a new 'unit' option that customize input block. This PR fixes some UI issues by adding that property. 
| Branch?           | 8.0.x 
| Type?             | bug fix 
| Category?         |  BO
| BC breaks?        | yes 
| Deprecations?     |  no
| Fixed ticket?     | Fixes #28892.
| How to test?      | See issue

Breaking changes: 

- Added two string parameters on `PrestaShopBundle\Form\Admin\Product\ProductShipping`

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Code is OK

It contains BC breaks but on 8.0.x it's OK it's a major

Please describe the BC breaks in the PR body ;)

File: src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php [hunk 1]
```diff
@@ -76,7 +78,7 @@ class ProductShipping extends CommonAbstractType
      * @param WarehouseDataProvider $warehouseDataProvider
      * @param CarrierDataProvider $carrierDataProvider
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php:85]: PHPDoc is outdated: missing the 2 new parameters

File: src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php [hunk 2]
```diff
@@ -67,6 +67,8 @@ class ProductShipping extends CommonAbstractType
      * @var array
      */
     private $warehouses;
+    private $dimensionUnit;
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php:73]: Some PHPDoc would be cool 😄

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

File: src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml [hunk 3]
```diff
@@ -168,6 +168,8 @@ services:
       - "@prestashop.adapter.legacy.context"
       - "@prestashop.adapter.data_provider.warehouse"
       - "@prestashop.adapter.data_provider.carrier"
+      - "@=service('prestashop.adapter.legacy.configuration').get('PS_DIMENSION_UNIT')"
+      - "@=service('prestashop.adapter.legacy.configuration').get('PS_WEIGHT_UNIT')"
```
Comment (PululuK) [inline src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml:172]: I suggest to use configuration service as a param instead of config value, because : 

- if later we need a new configuration value, we will no longer need to change the constructor of the class.

Comment (matks) [reply src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml:172]: But then you inject a big object instead of a small property 😮 isn't it a waste of memory?

The [work in progress](https://github.com/PrestaShop/ADR/pull/25) ADR for BC breaks states that Symfony service don't have to preserve backward compatibility for their constructors so we will be able to modify the constructor without BC break blocker.

Comment (kpodemski) [reply src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml:172]: @matks IMHO it's not only about BC Breaks. When's the limit where it's better to use the service instead of values? Four constructor arguments? Ten arguments? How many construct arguments is too many? :D I see using a service directly as a future-proof solution and having a lot of arguments smells like a constructor over-injection. **On the other hand** with that approach we don't need to worry about the configuration key name and if it does not produce a BC Break... =)

**Review by ghost — COMMENTED** [review]
Same issue when editng a combination.

Screenshot (79)

I don't now if we need a new PR and a new issue or we fix in this PR ?

**Comment by FabienPapet** [comment]
Actually, this code already exists in another service definition, I just copied it from this one : 

```yaml 
  form.type.sell.product.shipping.dimensions_type:
    class: 'PrestaShopBundle\Form\Admin\Sell\Product\Shipping\DimensionsType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      - "@=service('prestashop.adapter.legacy.configuration').get('PS_DIMENSION_UNIT')"
      - "@=service('prestashop.adapter.legacy.configuration').get('PS_WEIGHT_UNIT')"
    tags:
      - { name: form.type }
```

**Comment by PululuK** [comment]
> Actually, this code already exists in another service definition, I just copied it from this one :
> 
> ```yaml
>   form.type.sell.product.shipping.dimensions_type:
>     class: 'PrestaShopBundle\Form\Admin\Sell\Product\Shipping\DimensionsType'
>     parent: 'form.type.translatable.aware'
>     public: true
>     arguments:
>       - "@=service('prestashop.adapter.legacy.configuration').get('PS_DIMENSION_UNIT')"
>       - "@=service('prestashop.adapter.legacy.configuration').get('PS_WEIGHT_UNIT')"
>     tags:
>       - { name: form.type }
> ```

See [The Boy Scouts principle](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)

**Comment by FabienPapet** [comment]
Both look good to me, I prefer injecting values through configuration rather than an object config file, to allow reusability of the form types and avoid unnecessary coupling.

@PululuK I agree about leaving cleaner than I found the code, but IMO a change like this should be done in another MR as this MR is only bug fixing.

File: src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml (hunk 3 above)
Comment (PululuK) [reply src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml:172]: > But then you inject a big object instead of a small property :open_mouth: isn't it a waste of memory?

@matks are you sure that `PrestaShop\PrestaShop\Adapter\Configuration::get` is "a small property" ?

Comment (matks) [reply src/PrestaShopBundle/Resources/config/services/bundle/form/form_type.yml:172]: I am sure what will be returned is a small property, yes. I think you want to mean something, feel free to make it explicit 😄

**Comment by jolelievre** [comment]
I agree with @FabienPapet point of view both solutions are valid, each one has its pros and cons but anyway it doesn't deserve blocking the PR for those preferences IMHO

**Comment by matks** [comment]
I waited a bit to see if discussion would continue but as nothing changed since 5 days I'll go ahead: I share @jolelievre opinion that this topic is interesting but it should not block the PR. Even if the PR moves forward we can improve the code later, when we reach a consensus 👍

**Review by matks — APPROVED** [review]

**Comment by ghost** [comment]
I will open a new issue for editing a combination

**Review by HanaRebaiQA — APPROVED** [review]
Hello @FabienPapet 

Thanks for your PR. The issue is fixed. 

Here is my checked list : 

-Check with product V1 and product V2 : OK
-Check with different product types (Standard, pack, virtual, with combinations) : OK
-Check with multistore enabled and disabled : OK
-Check the automated tests : OK
-Check with different languages (RTL and no RTL) : OK
-Check with different browsers (Chrome and Firefox) : OK

image

image

For the edit combination issue, @okom3pom : Here is a dedicated issue that should be resolved [#29165 ](https://github.com/PrestaShop/PrestaShop/issues/29165)

So, it's QA :heavy_check_mark: 

Thank You!

**Comment by kpodemski** [comment]
Thanks @FabienPapet and @HanaRebaiQA
