### PR TITLE
Redirect to product list with warning message instead of raising an exception when we try to access a product which doesn't exist

### LINKED ISSUE #29913: BO - Products - An exception is displayed after deleting a product created with V1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Products page, an exception is displayed after deleting a product 
image

### Expected behavior

An warning message saying: "The product %name% has been deleted". 

### Steps to reproduce

1. Install 8.0.0 Rc or Use 8.0.0 from an upgrade
2. Enable debug mode
3. Create a Product (with Product V1 or V2)
4. Create an order with this product
5. Go to BO > Catalog > Product & delete the last product created
6. A. Go to BO > Orders > Preview for the previous order created
6. B. Go to BO > Orders > Order detail 
8. Click on the product
9. See exception

https://user-images.githubusercontent.com/16067358/194298724-778580be-b0b2-46d6-98ea-ee871ffcdc22.mp4

PS: I tried with PS1.7.8.7, but we cannot click on the product, this is a new feature on PS8.0.0 
image

### PrestaShop version(s) where the bug happened

8.0.0RC

### PHP version(s) where the bug happened

7.4, 8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Redirect to product list with warning message instead of raising an exception when we try to access a product which doesn't exist
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/29913
| Fixed ticket?     | Fixes #29913
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 1]
```diff
@@ -455,9 +456,18 @@ public function formAction($id, Request $request)
         }
 
         $productAdapter = $this->get('prestashop.adapter.data_provider.product');
-        $product = $productAdapter->getProduct($id);
+        try {
+            $product = $productAdapter->getProduct($id);
+        } catch (LogicException $e) {
```
Comment (mflasquin) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php:461]: It seems LogicException is raised only if we don't provide a product id, but if we cant to call this route we have to give a product id, no ?

File: src/PrestaShopBundle/Controller/Admin/ProductController.php [hunk 2]
```diff
@@ -455,9 +456,18 @@ public function formAction($id, Request $request)
...
+            $product = null;
+        }
 
         if (!$product || empty($product->id)) {
+            $this->addFlash(
+                'warning',
+                $this->trans('The product you are trying to access doesn\'t exist', 'AdminLoginNotification')
```
Comment (l-delin) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php]:
```suggestion
                $this->trans('The product you are trying to access doesn\'t exist.', 'Admin.Catalog.Notification')
```

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 1 above)
Comment (lartist) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:461]: @mflasquin sorry I don't understand your question

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 2 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]:
```suggestion
                $this->trans('The product you are trying to access doesn\'t exist', 'Admin.Catalog.Notification')
```
Hi @l-delin if the namespace is wrong then this one seems more adapted no? `Orderscustomers` has no relationship with the product page in theory

**Review by jolelievre — COMMENTED** [review]
hi @lartist 

this one is still in progress? because I don't see the fix on the Order details link

**Comment by lartist** [comment]
> hi @lartist
> 
> this one is still in progress? because I don't see the fix on the Order details link

Yes I realized it and I talked to you about that this morning. Today I'm a little bit busy. But I'll do it tomorow morning.

**Comment by lartist** [comment]
> hi @lartist
> 
> this one is still in progress? because I don't see the fix on the Order details link

@jolelievre done

**Comment by lartist** [comment]
@l-delin what about @jo suggestion for the domain 'Admin.Catalog.Notification' instead of 'Admin.Orderscustomers.Notification'.
I also added a commit with a new wording, please tell me if there is something to change.
https://github.com/PrestaShop/PrestaShop/pull/30957/files#diff-4714f44cd02ae297f3e42bbdc205bdb518491e6a7d127b63bf2be26acb300c9cR146

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig [hunk 3]
```diff
@@ -139,7 +139,13 @@
           <tbody>
           {% for productDetail in orderPreview.productDetails %}
             <tr class="{% if loop.index > productsPreviewLimit %}js-product-preview-more d-none{% endif %}">
-              <td class="p-1"><a class="px-0 external-link" href="{{ path('admin_product_form', {'id': productDetail.id}) }}" target="_blank">{{ productDetail.name }}</a></td>
+              <td class="p-1">
+                {% if productDetail.id %}
+                  <a class="px-0 external-link" href="{{ path('admin_product_form', {'id': productDetail.id}) }}" target="_blank">{{ productDetail.name }}</a>
+                {% else %}
+                  {{ productDetail.name }} ({{ 'Product deleted'|trans({}, 'Admin.Global') }})
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig]:
```suggestion
                  {{ productDetail.name }} ({{ 'Product deleted'|trans({}, 'Admin.Catalog.Feature') }})
```

**Review by jolelievre — COMMENTED** [review]
Thanks @lartist 

@l-delin we'd need your feedback regarding the wording namespaces please

**Review by 0x346e3730 — DISMISSED** [review]

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 2 above)
Comment (l-delin) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php]: Hello @jolelievre Yes, you're right - my bad. 😄 I edited my suggestion

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig (hunk 3 above)
Comment (l-delin) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig]: Hello @lartist / @jolelievre , where does this string appear? I'm not sure I understand what 'product deleted' means (whether it's a notification or just a text somewhere)

Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig]: Hi @lartist 

this one is not a notification it's displayed in the Order details when a product from the order has been removed:
Capture d’écran 2023-02-03 à 20 09 08

Comment (lartist) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/preview.html.twig]: > Hi @lartist
> 
> this one is not a notification it's displayed in the Order details when a product from the order has been removed: Capture d’écran 2023-02-03 à 20 09 08

Sorry I'm lost, which catalog do I have to change finally? :)

**Review by zuk3975 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @lartist 

Thanks for your PR!
With Product V1: all goods :heavy_check_mark: 
image

image

With Product V2: NOT OK :x: 
There's a problem! the product is not displayed in the product list page, see the attached screen record below: 

[pr_30957.webm](https://user-images.githubusercontent.com/23308427/217891514-12c12038-4ab8-4b8a-8626-4106d8b14c4d.webm)

Please check and feedback.

Thanks!

**Comment by lartist** [comment]
> Hello @lartist
> 
> Thanks for your PR! With Product V1: all goods ✔️ image
> 
> image
> 
> With Product V2: NOT OK ❌ There's a problem! the product is not displayed in the product list page, see the attached screen record below:
> 
> Please check and feedback.
> 
> Thanks!

Hi @hibatallahAouadni, 

Sorry for the delay, I was focusing on the release.
Regarding the exception thrown at the end of your screen record. I've just handle it in my last commit.
Regarding the fact that the product doesn't appear in the product list v2. I think it's out of scope. We should create an issue for this.

Thanks

**Comment by HanaRebaiQA** [comment]
Hello @lartist 

Thanks for your feedback. But, I deleted the Waiting for QA label until we have the new reviewers' approval and the CI will be green.

**Review by zuk3975 — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/ProductController.php (hunk 1 above)
Comment (FabienPapet) [inline src/PrestaShopBundle/Controller/Admin/ProductController.php:461]: Looks weird to catch a LogicException instead of a ProductNotFoundException

Comment (zuk3975) [reply src/PrestaShopBundle/Controller/Admin/ProductController.php:461]: getProduct method throws that exception (don't ask why - legacy stuff.. :smile:), to avoid introducing BC breaks or other unexpected behavior (modules may depend on that exception) we suggested not to change the legacy part and just catch that one.

**Review by matks — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello !

I have checked your PR and here is my checklist : 

**Checked with product V1** :heavy_check_mark: 

> Standard product
Combination product
Virtual Product
Parck

**Checked with product V2** :heavy_check_mark: 
> Standard product
Combination product
Virtual Product
Parck


The exception is no more displayed and it is OK.
But the automated tests are failed in the catalog part which is directly linked to the PR :warning: 
https://github.com/MhiriFaten/testing_pr/actions/runs/4290619785

Ping @PrestaShop/qa-automation  could you check it please ?

Thank you!

**Comment by Progi1984** [comment]
@MhiriFaten Could you restart failed jobs ?

**Comment by MhiriFaten** [comment]
@Progi1984 I still find the same result 
https://github.com/MhiriFaten/testing_pr/actions/runs/4351713423

image

**Comment by nesrineabdmouleh** [comment]
> @Progi1984 I still find the same result https://github.com/MhiriFaten/testing_pr/actions/runs/4351713423
> 
> image

@MhiriFaten you should rebase your fork :)

**Comment by jolelievre** [comment]
Thanks @lartist
