### PR TITLE
Prefix parameter in CLI is not interpreted if it's empty

### LINKED ISSUE #19201: DB_PREFIX is ignored in docker container
**Describe the bug**
DB_PREFIX is completly ignored if set to `''` (empty string) or `null` or `~` and always fallsback to `ps_`

**To Reproduce**
1. Add  `DB_PREFIX: ''` to docker-compose.yaml
2. docker-compose up -d
3. Check prestashop DB, all tables should be without `ps_` prefix

**Screenshots**
image

**Additional information**
PrestaShop version: 1.7.7.2
PHP version: 7.2

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When using `--prefix=""` with `index_cli.php` the database prefix fallbacks to `ps_` contrary to the classic installer.
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19201
| How to test?  | Run `./install-dev/index_cli.php --prefix=""` or in `docker-compose.yml` add in `environment` this line: `DB_PREFIX: ''`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19213)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

File: install-dev/classes/datas.php [hunk 1]
```diff
@@ -206,6 +206,8 @@ public function getAndCheckArgs($argv)
 
             if ($res[1] == 'license' && !isset($res[2])) {
                 $res[2] = 1;
+            } elseif ($res[1] == 'prefix' && !isset($res[2])) {
```
Comment (PierreRambaud) [inline install-dev/classes/datas.php]:
```suggestion
            } elseif ($res[1] == 'prefix' && empty($res[2])) {
```

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @PierreRambaud
