### PR TITLE
Refactor cancel product and bug fix

### LINKED ISSUE #18432: Refactor DeleteProductFromOrderHandler
- [x] #18564 : Refactor two handlers : 
- src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
- src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php

because updateOrder are nearly the same.

- [ ] Refactor handler src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php for using src/Adapter/Order/Refund/OrderProductRemover.php as service.

### LINKED ISSUE #19717: Wrong order total when cancelling a product on an order having cart rules
#### Describe the bug
There is a bug when canceling a product from an order having cart rules, order total is wrong.

Also this block should not be displayed when canceling a product:
Capture d’écran 2020-06-11 à 15 20 18

And the reduction values table is not updated.

#### Expected behavior
Canceling a product (quantity: one) should have the same impact as deleting it. Cart rules reduction values should be updated and the order total to be paid should be the same.

#### Steps to Reproduce

1. In FO, create an order with 2 products (quantity one for each product), go through completion of the order
2. In FO, create a second order, the exact same order: with the 2 same products and quantity of one for each product.
3. In BO, go the order detail page of the first order you created, and delete one product.
4. In BO, go to the second order you created and cancel one product.

**There are 3 problems:**
- The two orders end up with two different total order values.
- In both cases, the reduction amount table is not updated
- When canceling a product, this block appears (it should only appear for refunds)
Capture d’écran 2020-06-11 à 15 20 18

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Refactor Cancel Product feature to use the OrderProductQuantityUpdater, it also fixes the three bugs described in this PR: #19717
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19717
| How to test?  | See issue #19717

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19981)

### CODE REVIEW

**Review by atomiix — COMMENTED** [review]
I'm not sure about the file `package-lock.json` being changed 🤔

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 1]
```diff
@@ -114,29 +110,17 @@ public function handle(CancelOrderProductCommand $command)
...
-                    if ($order_carrier->update()) {
-                        $order->weight = sprintf('%.3f ' . Configuration::get('PS_WEIGHT_UNIT'), $order_carrier->weight);
-                    }
-                }
-
-                if (Configuration::get('PS_ADVANCED_STOCK_MANAGEMENT') && StockAvailable::dependsOnStock($orderDetail->product_id)) {
-                    StockAvailable::synchronize($orderDetail->product_id);
-                }
+                $newQuantity = (int) $orderDetail->product_quantity - (int) $qty_cancel_product;
+                $this->orderProductQuantityUpdater->update($order, $orderDetail, $newQuantity, null);
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: You use null as the last parameter, but the OrderDetail can have an invoice associated

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 2]
```diff
@@ -114,29 +110,17 @@ public function handle(CancelOrderProductCommand $command)
...
                 Hook::exec('actionProductCancel', ['order' => $order, 'id_order_detail' => (int) $orderDetail->id_order_detail], null, false, true, false, $order->id_shop);
             }
         }
         if (!empty($orderDetails['customizedProductsOrderDetail'])) {
             foreach ($orderDetails['customizedProductsOrderDetail'] as $orderDetail) {
                 $qtyCancelProduct = abs($orderDetails['customizedCancelQuantity'][$orderDetail->id_customization]);
-                $this->orderProductRemover->deleteProductFromOrder($order, $orderDetail, $qtyCancelProduct);
+                $newQuantity = (int) $orderDetail->product_quantity - (int) $qtyCancelProduct;
+
+                $this->orderProductQuantityUpdater->update($order, $orderDetail, $newQuantity, null);
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: Same here, you should provide the invoice if present (it can be generated manually even if the order has not been paid)

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php (hunk 1 above)
Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: If the order has an invoice then the user should not be able to perform a "cancel product", this case should never happen.

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php (hunk 2 above)
Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: same as above

File: admin-dev/themes/new-theme/package-lock.json [hunk 3]
```diff
@@ -4161,8 +4161,7 @@
                 "ansi-regex": {
```
Comment (matthieu-rolland) [inline admin-dev/themes/new-theme/package-lock.json:4161]: @NeOMakinG when I did my npm install, "optional: true" was added in many places in the package-lock.json, do you think it's ok ?

(thanks @atomiix )

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 4]
```diff
@@ -114,31 +130,23 @@ public function handle(CancelOrderProductCommand $command)
...
-                    $order_carrier->weight = (float) $order->getTotalWeight();
-                    if ($order_carrier->update()) {
-                        $order->weight = sprintf('%.3f ' . Configuration::get('PS_WEIGHT_UNIT'), $order_carrier->weight);
-                    }
-                }
-
-                if (Configuration::get('PS_ADVANCED_STOCK_MANAGEMENT') && StockAvailable::dependsOnStock($orderDetail->product_id)) {
-                    StockAvailable::synchronize($orderDetail->product_id);
-                }
+                $newQuantity = (int) $orderDetail->product_quantity - (int) $qty_cancel_product;
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: Even tough it is checked in OrderProductRemover it might be safer to set a `max(,0)` here as well, to be sure the quantity is never negative

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 5]
```diff
@@ -114,31 +130,23 @@ public function handle(CancelOrderProductCommand $command)
...
+                $orderInvoice = $orderDetail->id_order_invoice != 0 ? new OrderInvoice($orderDetail->id_order_invoice) : null;
+                $this->orderProductQuantityUpdater->update($order, $orderDetail, $newQuantity, $orderInvoice);
                 Hook::exec('actionProductCancel', ['order' => $order, 'id_order_detail' => (int) $orderDetail->id_order_detail], null, false, true, false, $order->id_shop);
             }
         }
         if (!empty($orderDetails['customizedProductsOrderDetail'])) {
             foreach ($orderDetails['customizedProductsOrderDetail'] as $orderDetail) {
                 $qtyCancelProduct = abs($orderDetails['customizedCancelQuantity'][$orderDetail->id_customization]);
-                $this->orderProductRemover->deleteProductFromOrder($order, $orderDetail, $qtyCancelProduct);
+                $newQuantity = (int) $orderDetail->product_quantity - (int) $qtyCancelProduct;
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php]: Same here `max(,0)`

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 6]
```diff
@@ -31,35 +31,51 @@
...
      *
-     * @param OrderProductRemover $orderProductRemover
+     * @param OrderProductQuantityUpdater $orderProductQuantityUpdater
+     * @param LoggerInterface $logger
+     * @param TranslatorInterface $translator
      */
     public function __construct(
-        OrderProductRemover $orderProductRemover
+        OrderProductQuantityUpdater $orderProductQuantityUpdater,
+        LoggerInterface $logger,
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:73]: It's a BC with you add new parameters to the construct

**Review by Progi1984 — COMMENTED** [review]
:warning: It's a BC.

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php (hunk 6 above)
Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:73]: But this handler doesn't exist in previous versions :D

File: admin-dev/themes/new-theme/package-lock.json (hunk 3 above)
Comment (NeOMakinG) [reply admin-dev/themes/new-theme/package-lock.json:4161]: It should not do anything dangerous, I think it's not a problem at all

Comment (matthieu-rolland) [reply admin-dev/themes/new-theme/package-lock.json:4161]: thanks for the deedback :)

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:73]: In the adapter namescape BC are usually accepted although they need to be documented
But in this case indeed it's a new class for 177 so no BC here

**Review by jolelievre — APPROVED** [review]

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php (hunk 6 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:73]: Ok. Bad one for me. Sorry.

**Review by Progi1984 — APPROVED** [review]

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php [hunk 7]
```diff
@@ -191,4 +199,24 @@ private function checkOrderState(Order $order)
...
+    private function cancelOrder(Order $order)
+    {
+        $history = new OrderHistory();
+        $history->id_order = (int) $order->id;
+        $history->changeIdOrderState(Configuration::get('PS_OS_CANCELED'), $order);
+        if (!$history->addWithemail()) {
+            // email failure must not block order update process
+            $this->logger->warning(
+                $this->translator->trans(
+                    'Order history email could not be sent, test your email configuration in the Advanced Parameters > E-mail section of your back office.',
```
Comment (LouiseBonnard) [inline src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:215]: Hi there, should the 'Advanced Parameters > E-mail' part use placeholders instead? Like we did with issue #18809 with @jolelievre, what do you think?

Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:215]: @LouiseBonnard 
Actually I didn't add a new message, I used the same message that was used in the `OrderProductRemover.php` file.

@SD1982  is currently testing this PR so I can't push code right now, but if you want I can change the message in another PR once this one is merged 👍

Comment (LouiseBonnard) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:215]: Okay, no worries, it can be done later with, perhaps, other wordings of that kind, it was more a question to Jonathan. But please keep in mind that QA is not supposed to test pull requests when the _waiting for wording_ label is still visible or else it complicates the wording review. :-)

**Comment by PierreRambaud** [comment]
I mark the PR a BC breaks

**Comment by PierreRambaud** [comment]
Woot, just notices the class is final. Did it to fast. @Progi1984 the class is final, this is not a BC breaks :)

**Comment by SD1982** [comment]
LGTM Thanks @matthieu-rolland !!

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @SD1982

File: src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php (hunk 7 above)
Comment (matthieu-rolland) [reply src/Adapter/Order/CommandHandler/CancelOrderProductHandler.php:215]: yep, I removed the label thinking that since I was moving existing code the wording didn't need to be checked again, I'll keep the waiting for wording label to be sure next time 👍
