### PR TITLE
Force disabled discounts (CartRules) to show if needed

### LINKED ISSUE #21556: Disabled voucher not displayed on customer panel in BO
#### Describe the bug

On BO > Customers > Customer View, the "Vouchers" block is set to display all vouchers limited to this customer. But only the enabled vouchers ("Status" to "Yes") are displayed.

The vouchers which are disabled are not displayed.

Edit : To reproduce it, you must have no other active cart rules. As soon as you have another active cart rules, the bug is not present anymore (even on 1.7.7.x). (Thanks @atomiix for the investigation)

#### Expected behavior

All vouchers limited to a customer should be displayed on the customer page, even if they are disabled.

#### Steps to Reproduce

0. Have no discount on BO
1. Go to BO > Catalog > Discount
2. Create a discount with Status at "Yes", and limited to Customer A
3. Go to BO > Customers > Customer A details page
4. Check Vouchers block : The voucher is displayed
5. Click on "Edit" the voucher, set Status to "No" and Save
6. Customer A details page is shown again, the voucher is not longer displayed even if it still exist and is still limited to this customer

**Screenshots**

https://drive.google.com/file/d/1ZpKfl5cOO2iJ6YUKUsVqn0OQPGQdtkAj/view?usp=sharing

#### Additional information

* PrestaShop version: presta1770rc1build2
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Follow instructions from well described issue
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21556.
| How to test?      | Follow instructions from well described issue
| Possible impacts? | n/a
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24797)

### CODE REVIEW

File: classes/CartRule.php [hunk 1]
```diff
@@ -408,9 +408,7 @@ public static function getCustomerCartRules(
         $free_shipping_only = false,
         $highlight_only = false
     ) {
-        if (!CartRule::isFeatureActive()
-            || !CartRule::haveCartRuleToday($id_customer)
-        ) {
+        if ($active && (!CartRule::isFeatureActive() || !CartRule::haveCartRuleToday($id_customer))) {
```
Comment (PierreRambaud) [inline classes/CartRule.php]: So, if we don't want vouchers only and CartRule is disabled, we run everything? :thinking:

Comment (kpodemski) [reply classes/CartRule.php]: thing is that if we have only one voucher (as described in Issue), and disable it, `CartRule` feature is treated as non active, so we need to omit this check

I was thinking about adding a new param like `$forceDisplay = false` but not sure if that's a good idea

Comment (PierreRambaud) [reply classes/CartRule.php]: I'm also not sure it's a good idea to display things if CartRule feature is not active :thinking:

Comment (kpodemski) [reply classes/CartRule.php]: It's tricky because we shouldn't care if the feature is active or not, we need to display all customer vouchers regardless of feature activity, especially if the feature state is not really our decision but... state and number of vouchers

Comment (PierreRambaud) [reply classes/CartRule.php]: It's weird :thinking: So the CartRule::isFeatureActive should be useless. Maybe we have to ping @PrestaShop/product-team and  @Robin-Fischer-PS

Comment (PierreRambaud) [reply classes/CartRule.php]: We also can't retrieve cart rules that are not active :thinking:

Comment (kpodemski) [reply classes/CartRule.php]: It's not that useless because this check is helpful in front-office

> We also can't retrieve cart rules that are not active 🤔

yes, and that's the point, we need to retrieve whatever we want to solve this issue, I could separate this query and create a dedicated method just to get what we need w/o checks, and left checks inside this old method, but naming  this new one would be challenging :D

Comment (PierreRambaud) [reply classes/CartRule.php]: Maybe it's a better solution, having a method for one usecase, and not one method for all usecases :p

**Review by atomiix — DISMISSED** [review]

File: tests/Integration/Classes/CartRuleTest.php [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+        $this->dummyCartRule = $this->createDummyCartRule(false, (int) $this->dummyCustomer->id);
+
+        $customerCartRules = CartRule::getAllCustomerCartRules(
+            (int) $this->dummyCustomer->id
+        );
+
+        $this->assertEquals(1, count($customerCartRules));
+    }
+
+    public function testGetAllCartRulesForCustomerWithDedicatedMethodBothEnabledAndDisabled()
```
Comment (Progi1984) [inline tests/Integration/Classes/CartRuleTest.php]:
```suggestion
    public function testGetAllCartRulesForCustomerWithDedicatedMethodBothEnabledAndDisabled(): void
```

File: tests/Integration/Classes/CartRuleTest.php [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+        $this->createDummyCartRule(true, (int) $this->dummyCustomer->id);
+
+        $customerCartRules = CartRule::getAllCustomerCartRules(
+            (int) $this->dummyCustomer->id
+        );
+
+        $this->assertEquals(3, count($customerCartRules));
+    }
+
+    public function testGetAllCartRulesForCustomerWithDedicatedMethodBothEnabledAndDisabledWithOtherCustomerCartRulesAvailable()
```
Comment (Progi1984) [inline tests/Integration/Classes/CartRuleTest.php]:
```suggestion
    public function testGetAllCartRulesForCustomerWithDedicatedMethodBothEnabledAndDisabledWithOtherCustomerCartRulesAvailable(): void
```
Magic Name... Do you like Java ?

File: tests/Integration/Classes/CartRuleTest.php [hunk 4]
```diff
@@ -0,0 +1,200 @@
...
+    /**
+     * @param bool $active
+     * @param int $customerId
+     *
+     * @return CartRule
+     */
+    public function createDummyCartRule(
+        bool $active = true,
+        int $customerId
+    ) {
```
Comment (Progi1984) [inline tests/Integration/Classes/CartRuleTest.php]:
```suggestion
    ): CartRule {
```

File: tests/Integration/Classes/CartRuleTest.php [hunk 5]
```diff
@@ -0,0 +1,200 @@
...
+    }
+
+    /**
+     * @param bool $active
+     * @param int $customerId
+     *
+     * @return CartRule
+     */
+    public function createDummyCartRule(
+        bool $active = true,
```
Comment (Progi1984) [inline tests/Integration/Classes/CartRuleTest.php]:
```suggestion
        bool $active,
```

File: tests/Integration/Classes/CartRuleTest.php [hunk 6]
```diff
@@ -0,0 +1,200 @@
...
+        int $customerId
+    ) {
+        $randomNumber = rand(999, 9999);
+        $cart_rule = new CartRule();
+        $cart_rule->code = 'TEST_CART_RULE_' . $randomNumber;
+        $cart_rule->name = [
+            $this->configuration->get('PS_LANG_DEFAULT') => 'Test Cart Rule #' . $randomNumber,
+        ];
+        $cart_rule->id_customer = (int) $customerId;
```
Comment (Progi1984) [inline tests/Integration/Classes/CartRuleTest.php]:
```suggestion
        $cart_rule->id_customer = $customerId;
```

**Review by Progi1984 — COMMENTED** [review]
Good job :) (and <3 tests)

File: tests/Integration/Classes/CartRuleTest.php (hunk 3 above)
Comment (kpodemski) [reply tests/Integration/Classes/CartRuleTest.php]: 😅 I like to read code you know, 

normally I'd go with:

`test_if_this_is_working_or_not` instead of camel case but hey! we still can read it in camelCase :D

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @kpodemski 
With your PR applied the cart rule is not displayed even if he is enabled but the discount count is ok 
image

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

File: classes/CartRule.php [hunk 7]
```diff
@@ -537,6 +535,40 @@ public static function getCustomerCartRules(
...
+
+        $result = Db::getInstance()->executeS($query);
+
+        if (!$result) {
+            return [];
+        }
+
+        foreach ($result as &$cart_rule) {
+            if ($cart_rule['quantity_per_user']) {
+                $quantity_used = Order::getDiscountsCustomer((int) $customerId, (int) $cart_rule['id_cart_rule']);
```
Comment (arouiadib) [inline classes/CartRule.php]: is this variable always holding integers?

File: src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php [hunk 8]
```diff
@@ -65,11 +65,8 @@ public function __construct(
      */
     public function getData(SearchCriteriaInterface $searchCriteria)
     {
-        $discounts = CartRule::getCustomerCartRules(
-            $this->contextLangId,
-            $this->customer->id,
-            false,
-            false
+        $discounts = CartRule::getAllCustomerCartRules(
```
Comment (arouiadib) [inline src/Core/Grid/Data/Factory/CustomerDiscountGridDataFactory.php]: could be a one-liner?

File: tests/Integration/Classes/CartRuleTest.php [hunk 9]
```diff
@@ -0,0 +1,200 @@
...
+        );
+
+        $this->assertEquals(1, count($customerCartRules));
+    }
+
+    public function testGetAllCartRulesForCustomerWithDedicatedMethodEvenDisabled(): void
+    {
+        $this->dummyCartRule = $this->createDummyCartRule(false, (int) $this->dummyCustomer->id);
+
+        $customerCartRules = CartRule::getAllCustomerCartRules(
```
Comment (arouiadib) [inline tests/Integration/Classes/CartRuleTest.php:119]: maybe also this could be a one-line ?

File: tests/Integration/Classes/CartRuleTest.php [hunk 10]
```diff
@@ -0,0 +1,200 @@
...
+        $this->assertEquals(1, count($customerCartRules));
+    }
+
+    public function testGetAllCartRulesForCustomerWithDedicatedMethodBothEnabledAndDisabled(): void
+    {
+        $this->createDummyCartRule(false, (int) $this->dummyCustomer->id);
+        $this->createDummyCartRule(true, (int) $this->dummyCustomer->id);
+        $this->createDummyCartRule(true, (int) $this->dummyCustomer->id);
+
+        $customerCartRules = CartRule::getAllCustomerCartRules(
```
Comment (arouiadib) [inline tests/Integration/Classes/CartRuleTest.php:132]: same as before (maybe)

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

- When you create a **disabled** voucher **limited to one customer**, the voucher is well displayed on the customer details page 
=> OK :heavy_check_mark: 
- When you create a **disabled/enabled** voucher **not limited to one customer** and **without code**, the voucher is not displayed in the customer details pages 
=> NOK :x: 

=> Cause, without PR, an **enabled** voucher **not limited to one customer** and **without cod**e is displayed in the customer details page.

https://drive.google.com/file/d/16LUCrvOt1Fg0_zRN49T863LyWaHpwfDH/view

Please check and feedback.
Thanks!

**Comment by kpodemski** [comment]
@hibatallahAouadni I think this one should be validated by @PrestaShop/product-team 

What's the point of showing vouchers not related to the customer on his page?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/product-team wdyt?
### Without PR: 

- an **enabled** voucher **not limited to one customer** and **without code** is displayed in the customer details page.

### With PR: 

- an **enabled** voucher **not limited to one customer** and **without code** is **NOT** displayed in the customer details page.

And @kpodemski think that:
> What's the point of showing vouchers not related to the customer on his page?

So, wdyt?

**Comment by marionf** [comment]
> What's the point of showing vouchers not related to the customer on his page?

I think we should display on the customer view page all the cart rules that can be used by the customer, this way the merchant can see all the cart rules that can be used by this customer.

**Comment by kpodemski** [comment]
@marionf 

I'm really not sure if that's a good idea because this page is strictly related to this customer, and if the merchant has a lot of "global" vouchers, this list will be quite big, with no easy way to distinct vouchers related to the customer we're viewing.

Anyway, I've changed code to meet your suggestion 👍

**Comment by MatShir** [comment]
Maybe, we could display first the cart rule available and assigned to the customer especially on the top of the list then display all the cart rule that could be use by the customer ? 🤷 (and adding a pagination if needed also)

File: classes/CartRule.php [hunk 11]
```diff
@@ -537,6 +535,40 @@ public static function getCustomerCartRules(
...
+     *
+     * @return array
+     */
+    public static function getAllCustomerCartRules(
+        int $customerId
+    ): array {
+        $query = new DbQuery();
+        $query->select('cr.*, crl.name');
+        $query->from('cart_rule', 'cr');
+        $query->where('cr.id_customer = ' . (int) $customerId . ' OR (cr.`id_customer` = 0 AND (cr.`highlight` = 1 OR cr.`code` = ""))');
```
Comment (Progi1984) [inline classes/CartRule.php]:
```suggestion
        $query->where('cr.id_customer = ' . $customerId . ' OR (cr.`id_customer` = 0 AND (cr.`highlight` = 1 OR cr.`code` = ""))');
```

It's already an integer.

**Review by Progi1984 — COMMENTED** [review]
@kpodemski Thank you for your contribution. I have commented a last time and it will be a approve.

File: classes/CartRule.php (hunk 7 above)
Comment (PierreRambaud) [reply classes/CartRule.php]: If you're talking about the customerId yes it is because of method signature

**Comment by kpodemski** [comment]
@Progi1984 thx, done

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thanks again!

Here's all the use cases:

- an **enabled** voucher **limited to one customer** & **without code** => **displayed**
- an **enabled** voucher **limited to one customer** & **with code** and **Highlight** enabled => **displayed**
- an **enabled** voucher **limited to one customer** & **with code** and **Highlight** disabled => **displayed**
- a **disabled** voucher **limited to one customer** & **without code** => **displayed**
- a **disabled** voucher **limited to one customer** & **with code** and **Highlight** enabled => **displayed**
- a **disabled** voucher **limited to one customer** & **with code** and **Highlight** disabled => **displayed**
- an **enabled** voucher **not limited to one customer** & **without code** => **displayed**
- an **enabled** voucher **not limited to one customer** & **with code** and **Highlight** enabled => **displayed**
- an **enabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed**
- a **disabled** voucher **not limited to one customer** & **without code** => **displayed**
- a **disabled** voucher **not limited to one customer** & **with code** and **Highlight** enabled => **displayed**
- a **disabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed**

https://drive.google.com/file/d/1IntbgzEhoVbCHtQ26rKAd48XMxrOAlLL/view
Ping @PrestaShop/product-team if this is the expected behavior, then QA :heavy_check_mark: please verify these two use cases:
- an **enabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed**
- a **disabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed**

Waiting for your feedback!
Thanks!

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Could you please resolve your conflicting files :pray: 
> Ping @PrestaShop/product-team if this is the expected behavior, then QA :heavy_check_mark: please verify these two use cases:
1 - an **enabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed**
2 - a **disabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed**

About the first not displayed condition (1), I check the [specs](https://github.com/PrestaShop/prestashop-specs/pull/189/files?short_path=48191b5) and as you can see below:

image

In FO, if the voucher with code and the highlight is disabled, so the voucher is not available in FO (not displayed).
So, IMHO I think it should be the same behavior in BO:
a **disbaled/enabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled => **NOT displayed** :heavy_check_mark: 

In BO, the pagination works like charm, thanks @kpodemski :clap: 

image

In FO, with all conditions mentioned in my previous comment, only these are displayed => :heavy_check_mark: 

image

Please rebase your PR, then I will add the QA :heavy_check_mark: 

Thanks :pray:

**Comment by kpodemski** [comment]
Thanks for the tests @hibatallahAouadni 👍 I rebased a PR.

**Comment by MatShir** [comment]
Sorry for the late response, I suggest displaying all the cart rule without regarding the different parameter. I don't want a merchant to guess why some carts are not displayed. Questions @kpodemski : what do you think to first filter by enabled, then by to display first the one linked to the user?

**Comment by hibatallahAouadni** [comment]
Ping @PrestaShop/prestashop-core-developers review please :pray:

**Comment by matks** [comment]
> Ping @PrestaShop/prestashop-core-developers review please 🙏

We wait for @kpodemski answer, following @MatShir question.

**Comment by hibatallahAouadni** [comment]
Ping @kpodemski could you please answer @MatShir question :pray:

File: tests/Integration/Classes/CartRuleTest.php [hunk 12]
```diff
@@ -0,0 +1,259 @@
...
+{
+    /**
+     * @var Customer
+     */
+    public $dummyCustomer;
+
+    /**
+     * @var CartRule
+     */
+    public $dummyCartRule;
```
Comment (sowbiba) [inline tests/Integration/Classes/CartRuleTest.php]: I don't see the necessity to make it an property. You always create a new one and do not reuse it

**Review by sowbiba — COMMENTED** [review]
1 comment. Otherwise it's all good

**Review by sowbiba — DISMISSED** [review]

File: tests/Integration/Classes/CartRuleTest.php [hunk 13]
```diff
@@ -0,0 +1,259 @@
...
+
+    /**
+     * @var Configuration
+     */
+    public $configuration;
+
+    /**
+     * @var int
+     */
+    public $defaultLanguageId;
```
Comment (PierreRambaud) [inline tests/Integration/Classes/CartRuleTest.php]:
```suggestion
    /**
     * @var Customer
     */
    protected $dummyCustomer;

    /**
     * @var Configuration
     */
    protected $configuration;

    /**
     * @var int
     */
    protected $defaultLanguageId;
```

Clearly no need to put test properties in public :thinking:

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Just one comment about visibility, there is no need to put properties in public, use protected or private instead

**Review by PierreRambaud — APPROVED** [review]

File: tests/Integration/Classes/CartRuleTest.php [hunk 14]
```diff
@@ -0,0 +1,259 @@
...
+
+    /**
+     * @return Customer
+     */
+    public function createDummyCustomer(): Customer
+    {
+        $customer = new Customer();
+        $customer->firstname = 'Jenna';
+        $customer->lastname = 'Doe';
+        $customer->email = 'pub+jenna+' . rand(0, 99) . '@prestashop.com';
```
Comment (atomiix) [inline tests/Integration/Classes/CartRuleTest.php]: I know there is very little chance that it happens, but this doesn't garanti the uniqueness of the email 😅

Comment (PierreRambaud) [reply tests/Integration/Classes/CartRuleTest.php]: Woot, I missed this one :scream:

**Review by PierreRambaud — DISMISSED** [review]
Agree with @atomiix 
The `rand` is useless in the `createDummyCustomer`

**Comment by kpodemski** [comment]
@atomiix @PierreRambaud yeah, well, the chances were very little but I've just changed `rand` to `uniqid`. Better safe than sorry ;-)

**Review by atomiix — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by kpodemski** [comment]
ping @PierreRambaud 

Could you take a look? you've requested changes

**Comment by PierreRambaud** [comment]
> ping @PierreRambaud
> 
> Could you take a look? you've requested changes

FYI, anyone can dismiss a review.
image

File: tests/Integration/Classes/CartRuleTest.php [hunk 15]
```diff
@@ -0,0 +1,259 @@
...
+
+    /**
+     * @return Customer
+     */
+    public function createDummyCustomer(): Customer
+    {
+        $customer = new Customer();
+        $customer->firstname = 'Jenna';
+        $customer->lastname = 'Doe';
+        $customer->email = 'pub+' . uniqid() . '@prestashop.com';
```
Comment (PierreRambaud) [inline tests/Integration/Classes/CartRuleTest.php:253]: Why you always create random customer? 
Why not clearing the database on tearDown instead?

Comment (kpodemski) [reply tests/Integration/Classes/CartRuleTest.php:253]: Because I wanted to have a possibility to create a couple of vouchers for a couple of customers.

**Comment by hibatallahAouadni** [comment]
I cannot test this PR because it is blocked by this issue #27119 :disappointed:

**Comment by kpodemski** [comment]
Hello @hibatallahAouadni 

Maybe you can simply turn off the blockwishlist module before testing these changes? 🙂

**Comment by hibatallahAouadni** [comment]
@kpodemski ok I will try :wink:

**Review by hibatallahAouadni — CHANGES_REQUESTED** [review]
Hello @kpodemski 

Thanks for the tip, now I can test the PR :wink: 
Well, it seems you didn't apply the requested changes by @MatShir 
> Sorry for the late response, I suggest **displaying all the cart rule without regarding the different parameter**. I don't want a merchant to guess why some carts are not displayed.

Means that: 
a **disbaled/enabled** voucher **not limited to one customer** & **with code** and **Highlight disabled** 
   => it **should be displayed** in **BO** for the **merchant**

These two cases are missing (it should be 12 cart rules not 10):
- an **enabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled
- a **disabled** voucher **not limited to one customer** & **with code** and **Highlight** disabled

image

I notice that the Id column is too tight, to a point where an id (composed of two digits like 10) will be split.

> Questions @kpodemski : what do you think to first filter by enabled, then by to display first the one linked to the user?

Nice work :clap: the whole list is well filtred.
For the FO, LGTM :heavy_check_mark: 

image

Waiting for your changes :rocket: 
Thanks!

**Comment by kpodemski** [comment]
Hello @hibatallahAouadni 

> Means that:
a disabled/enabled voucher not limited to one customer & with code and Highlight disabled
=> it should be displayed in BO for the merchant

That would mean that you'd see there every single voucher added to the store. On this list, all cart rules should be usable for this customer, and if not, we need to get those highlighted. The point of this section is to get not all vouchers but those available for the customer through the dedicated code or through highlighting them in the shopping cart.

> I notice that the Id column is too tight, to a point where an id (composed of two digits like 10) will be split.

I think it's not related to this PR, it's a global style.

cc @MatShir

**Comment by MatShir** [comment]
After reading @kpodemski comment's, you made a point. We should avoid displaying vouchers that are not customer related and not highlighted. 

Sorry for the back and forth, I didn't realize the impact it could have on the list.

**Comment by hibatallahAouadni** [comment]
Hello @kpodemski 

Thanks @MatShir for your confirmation :pray: 
Then all LGTM except this one:

> > I notice that the Id column is too tight, to a point where an id (composed of two digits like 10) will be split.
> 
> I think it's not related to this PR, it's a global style.

No, it's not! cause on develop without PR, I didn't encounter the issue:

image

Please check and feedback.
Thanks!

**Comment by Progi1984** [comment]
@kpodemski Are you still on this PR or can we close this one ?

**Comment by hibatallahAouadni** [comment]
@kpodemski @MatShir I think we can accept this PR as it's and open a new issue (regression) for the ID issue, wdyt?

**Comment by MatShir** [comment]
@hibatallahAouadni sounds good to me. WDYT @kpodemski ?

**Comment by hibatallahAouadni** [comment]
Hello,

We have the PM approval and @kpodemski 's.
So, finally it's QA :heavy_check_mark: 

After merging this PR, I will create a new issue-regression for the bad display of IDs.

Thanks everyone :pray:

**Review by hibatallahAouadni — APPROVED** [review]
Hello,

We have the PM approval and @kpodemski 's.
So, finally it's QA :heavy_check_mark: 

After merging this PR, I will create a new issue-regression for the bad display of IDs.

Thanks everyone :pray:

**Comment by atomiix** [comment]
Thanks @kpodemski & @hibatallahAouadni !
