### PR TITLE
Filter variations by qty at FO

### LINKED ISSUE #9948: [BOOM-3420] FO: Unable to select product combination, because you need to go via a combination that is out of stock.
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3420).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Thu, 6 Jul 2017 17:20:32 +0200

**Steps to reproduce the issue:**
1-Create a product with combinations. Put stock in some combination but not in all.
2- Disable the option "Allow to buy products out of stock."
3-Disable the option "Display unavailable product attributes on the product page" in the Product Settings page
4-In FO, combinations out of stock can not be selected

https://drive.google.com/file/d/1YoTsG5tSydgnhtQAYhWWXiMhbWOTXTd_/view
<p>Dans Paramètres > Produits, je met Afficher les attributs indisponibles sur la fiche produit sur Non.<br/>
Ceci fonctionne si il y a qu'un seul attribut 

Cependant, ça ne fonctionne plus quand il y a plusieurs attributs 

https://drive.google.com/file/d/1GYgWfsCiLa_YAZkShBhzxFf7TixHLdiN/view?usp=sharing

### PR DESCRIPTION
**Pull request by Guisardo**
If enable, only show variations with quantities at FO. Also, if the variation is not available when the user change an attribute, look for something similar instead of always going back to the default.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  |  The current implementation is not handling well the product combination changes at FO. The ProductController tries to match the exact variation when the user change an attribute. But, when combinations have more than one attribute and the user only is able to change one attribute per action, the ProductController may not find the combination available and fallback into the default one, even if it is totally different and the FO then has to resets the user selection completely. Also, the FO is currently showing variations with no quantity available. When the user selects an attribute with no quantity, the FO fallback SILENTLY into the default combination provoking incorrect orders.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Didn't find the ticket but many people complain about this at the forums. Per example: https://www.prestashop.com/forums/topic/308751-hide-unavailable-combinations/ // Think is related to https://github.com/PrestaShop/PrestaShop/issues/9948
| How to test?  | To test this, you need to have a product with multiple combinations. The stock of those combinations should variate and some should have 0 elements. The change includes the conditions to offer out of stock if it is configured so that must be tested too. If this works and the product only allows order when in stock, the FO should only display what is available and the user should be able to change the attributes successfully switching to other combinations that has stock available.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20565)

### CODE REVIEW

**Comment by Guisardo** [comment]
Hi there,
Not sure why the linter complains. I'd only push the changes that affect what is reported at the description of the PR, maybe the rest of the file needs linting or something. Let me know how else can I help or feel free to touch the code yourself.

**Comment by matthieu-rolland** [comment]
> Hi there,
> Not sure why the linter complains. I'd only push the changes that affect what is reported at the description of the PR, maybe the rest of the file needs linting or something. Let me know how else can I help or feel free to touch the code yourself.

Hi @Guisardo , thank you for your contribution !

If there is no issue, then you should create one, we need this to track what is being done, for the product team, the QA team, and project management as a whole, once the issue is created, then you can put the link in your PR's description. It would be perfect if you can describe precisely each step leading to your issue, so that people can reproduce it faster.

You can create your issue here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

 

For the liting issue, just do this command from the root of your project, and commit/push the modified file:

`./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix controllers/front/ProductController.php`

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -985,6 +990,43 @@ function ($elem) use ($checkedIdProductAttribute) {
...
+
+                        if (count($alternativeProductAttribute)) {
+                            usort($alternativeProductAttribute, function ($a, $b) {
+                                $aValue = $a['quantity'];
+                                $bValue = $b['quantity'];
+                                if ($a == $b) {
+                                    return 0;
+                                }
+
+                                return ($a > $b) ? -1 : 1;
```
Comment (Progi1984) [inline controllers/front/ProductController.php]:
```suggestion
                                if ($a['quantity'] == $b['quantity']) {
                                    return 0;
                                }

                                return ($a['quantity'] > $b['quantity']) ? -1 : 1;
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

**Comment by Progi1984** [comment]
@Guisardo Could you fix errors on PHPCSFixer ?

**Review by Progi1984 — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @Guisardo 

Could you verify if your PR is fixing this issue: https://github.com/PrestaShop/PrestaShop/issues/9948 ?
If it's not the case, could you please create a new issue with the steps to reproduce the bug ?
This will help to test your PR and quickly better understand what is the problem

Than you very much :)

**Comment by Guisardo** [comment]
> Hello @Guisardo
> 
> Could you verify if your PR is fixing this issue: #9948 ?
> If it's not the case, could you please create a new issue with the steps to reproduce the bug ?
> This will help to test your PR and quickly better understand what is the problem
> 
> Than you very much :)

Hi @marionf,
Yes, that seems to be the case, although the #9948 is quite old and part of the report is in french so it is hard to confirm, but by google translate and by the related issues it all indicates that this PR will fix that issue.
Best,

File: controllers/front/ProductController.php [hunk 2]
```diff
@@ -985,6 +990,41 @@ function ($elem) use ($checkedIdProductAttribute) {
             );
 
             if (empty($availableProductAttribute) && count($availableProductAttributes)) {
+                if (!Product::isAvailableWhenOutOfStock($this->product->out_of_stock)) {
```
Comment (sowbiba) [inline controllers/front/ProductController.php:996]: It would be great to add some comments to explain what is done here

**Review by sowbiba — DISMISSED** [review]

File: controllers/front/ProductController.php (hunk 2 above)
Comment (Guisardo) [reply controllers/front/ProductController.php:996]: comments added @sowbiba

**Comment by ngodefroy** [comment]
Hello @Guisardo 
What I tested:
In FO went to Shop param>Producgt settings and switched to No "Display unavailable product attributes on the product page"
Create a product
Add combinations with elements and stock/out of stock products
Modify combination
Check FO that the products out of stock doesnt appears => TEST OK

As you mentioned "_The change includes the conditions to offer out of stock if it is configured so that must be tested too_"
Then, When I click on "allow orders" I get the undefined below (which was also present on the actual version):
Capture d’écran 2020-10-08 à 09 43 42

Did you also wanted to fix this in your PR?

Thank you !

**Comment by Guisardo** [comment]
> Hello @Guisardo
> What I tested:
> In FO went to Shop param>Producgt settings and switched to No "Display unavailable product attributes on the product page"
> Create a product
> Add combinations with elements and stock/out of stock products
> Modify combination
> Check FO that the products out of stock doesnt appears => TEST OK
> 
> As you mentioned "_The change includes the conditions to offer out of stock if it is configured so that must be tested too_"
> Then, When I click on "allow orders" I get the undefined below (which was also present on the actual version):
> Capture d’écran 2020-10-08 à 09 43 42
> 
> Did you also wanted to fix this in your PR?
> 
> Thank you !

Hi @ngodefroy , thanks for the tests!
That message is a "Notice", it will only show when a high level of debugging is enabled at the environment. That is probably why it hasn't been reported at the current version.
Nevertheless, I'd added the condition to prevent that notice.
Best,

**Comment by Guisardo** [comment]
Hi @Progi1984 | @sowbiba , could you move the label back to "waiting for QA" so this doesn't get stuck?

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

File: controllers/front/ProductController.php [hunk 3]
```diff
@@ -985,6 +992,45 @@ function ($elem) use ($checkedIdProductAttribute) {
...
+                        foreach ($checkProductAttribute as $key => $attribute) {
+                            $alternativeAttribute = array_filter(
+                                $availableProductAttributes,
+                                function ($elem) use ($attribute) {
+                                    return $elem['id_attribute'] == $attribute['id_attribute'] && !$elem['is_color_group'];
+                                }
+                            );
+                            foreach ($alternativeAttribute as $key => $value) {
+                                $alternativeProductAttribute[$key] = $value;
+                            }
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:1016]: Use array_merge instead :thinking:

File: controllers/front/ProductController.php [hunk 4]
```diff
@@ -985,6 +992,45 @@ function ($elem) use ($checkedIdProductAttribute) {
             );
 
             if (empty($availableProductAttribute) && count($availableProductAttributes)) {
+                // if selected combination is NOT available ($availableProductAttribute) but they are other alternatives ($availableProductAttributes), then we'll try to get the closest.
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:995]: I think the best way to understand is to split this code into small methods. :thinking:

File: controllers/front/ProductController.php [hunk 5]
```diff
@@ -676,9 +676,13 @@ protected function assignAttributesGroups($product_for_template = null)
...
-                    $id_attributes = Db::getInstance()->executeS('SELECT `id_attribute` FROM `' . _DB_PREFIX_ . 'product_attribute_combination` pac2
-                        WHERE `id_product_attribute` IN (' . implode(',', array_map('intval', $id_product_attributes)) . ')
-                        AND id_attribute NOT IN (' . implode(',', array_map('intval', $current_selected_attributes)) . ')');
+                    $id_attributes = Db::getInstance()->executeS('SELECT pac2.`id_attribute` FROM `' . _DB_PREFIX_ . 'product_attribute_combination` pac2' .
+                        ((!Product::isAvailableWhenOutOfStock($this->product->out_of_stock) && 0 == Configuration::get('PS_DISP_UNAVAILABLE_ATTR')) ?
+                        ' INNER JOIN `' . _DB_PREFIX_ . 'stock_available` pa ON pa.id_product_attribute = pac2.id_product_attribute
+                        WHERE pa.quantity > 0 AND ' :
+                        ' WHERE ') .
+                        'pac2.`id_product_attribute` IN (' . implode(',', array_map('intval', $id_product_attributes)) . ')
+                        AND pac2.id_attribute NOT IN (' . implode(',', array_map('intval', $current_selected_attributes)) . ')');
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:685]:
```suggestion
                    $notAvailable = !Product::isAvailableWhenOutOfStock($this->product->out_of_stock) && 0 == Configuration::get('PS_DISP_UNAVAILABLE_ATTR');
                    $id_attributes = Db::getInstance()->executeS(
                        'SELECT pac2.`id_attribute` FROM `' . _DB_PREFIX_ . 'product_attribute_combination` pac2' .
                        (
                            $notAvailable
                            ? ' INNER JOIN `' . _DB_PREFIX_ . 'stock_available` pa ON pa.id_product_attribute = pac2.id_product_attribute WHERE pa.quantity > 0 AND '
                            :' WHERE '
                        ) .
                        'pac2.`id_product_attribute` IN (' . implode(',', array_map('intval', $id_product_attributes)) . ') ' .
                        'AND pac2.id_attribute NOT IN (' . implode(',', array_map('intval', $current_selected_attributes)) . ')'
                    );
```

make it a little more readable (make sure it's ok with names :) )

File: controllers/front/ProductController.php [hunk 6]
```diff
@@ -985,6 +992,45 @@ function ($elem) use ($checkedIdProductAttribute) {
...
+                            );
+                            foreach ($alternativeAttribute as $key => $value) {
+                                $alternativeProductAttribute[$key] = $value;
+                            }
+                        }
+
+                        if (count($alternativeProductAttribute)) {
+                            // if alternative combination is found, order the list by quantity to use the one with more stock.
+                            usort($alternativeProductAttribute, function ($a, $b) {
+                                if ($a['quantity'] == $b['quantity']) {
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:1022]: Use a method instead of an anonymous function for the sort.

**Comment by SD1982** [comment]
LGTM this PR seems to correctly fix #9948 :+1: 
Thanks @Guisardo !!

**Comment by PululuK** [comment]
Thanks @Guisardo

**Comment by zenerry** [comment]
Hi everyone!
 those are great news!
Is there any way to apply this solution to PS 1.7.5.2 (can't update to newer PS versions for external technical reasons) ?

Thanks!

**Comment by Guisardo** [comment]
Hi @PierreRambaud , thanks for the feedback! I tried to patch the bug with the minimal code changes so it wont break anything else, but I agree that, with a little more time, the code could be more elegant and maintainable. 
Should I open a new PR for those improvements or should I post them here too?
