### PR TITLE
CO: improvement : Performance String Modifier

### LINKED ISSUE #34453: FO: Slow loading of product page with many combinations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we have many variants, like 500 or more, the site loading is pretty slow.

### Expected behavior

The site speed should not be affected massively

### Steps to reproduce

1. Create a product with 4 different attribute groups and a certain amount of attributes and create > 500 variants
2. Create a product with only few combinations
3. Go to front office and load both products and compare times in profiler. Compare the initContent method times.

Those will be dramatically different

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Shoprunners**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This improvements makes reuse of the StringModifier. Why is this an issue? I.e. if a product has many combinations, for each combination a new StringModifier with the whole tail will be created in the initContent method of the frontend ProductController, which costs a good time. There is no need for it and we can just reuse it.
| Type?             |  improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Profile a product with 2000 combinations and look at the initContent time.
| UI Tests          | https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6747522063
| Fixed issue or discussion?     | Fixes #34453
| Sponsor company   | Shoprunners

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]
Nice improvement

**Comment by M0rgan01** [comment]
@Shoprunners Nice work, only one fix is ​​missing on CS Fixer, and it is approved

**Comment by Shoprunners** [comment]
> @Shoprunners Nice work, only one fix is ​​missing on CS Fixer, and it is approved

Thanks,
but I don't see the error, I can't find any spaces or missing brackets etc.. Any idea? The error message is not very usefull.

File: classes/Tools.php [hunk 1]
```diff
@@ -1223,7 +1224,21 @@ public static function str2url($str)
...
     {
-        return (new StringModifier())->replaceAccentedChars($str);
+        return (self::getStringModifier())->replaceAccentedChars($str);
+    }
+
+    /**
+    * Reuse the StringModifier for performance reasons.
+    *
+    * @return StringModifier
+    */
```
Comment (kpodemski) [inline classes/Tools.php]:
```suggestion
    * Reuse the StringModifier for performance reasons.
     *
     * @return StringModifier
     */
```

Comment (kpodemski) [reply classes/Tools.php]: cs fixer, you can also run it locally :)

**Review by FabienPapet — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by MatShir** [comment]
We could cherry-pick for the 8.1.x or change the branch. what do you think @Shoprunners ?

**Comment by Shoprunners** [comment]
> We could cherry-pick for the 8.1.x or change the branch. what do you think @Shoprunners ?

Sure, I don't see any reason why not. But I am not good in rebasing etc.

**Comment by M0rgan01** [comment]
@Shoprunners I can do it if you want, but I need publishing rights to your fork

Otherwise, create a new branch (patch-16v2) starting from 8.1.x, cherry-pick the commits from the patch-16 branch and force-push targeting the patch-16 branch. It would then be necessary to change the destination branch of the PR to 8.1.x

**Comment by MatShir** [comment]
@Shoprunners up !! You have the checkbox on the bottom right to allow maintainer to edit ;)

**Comment by Shoprunners** [comment]
> @Shoprunners I can do it if you want, but I need publishing rights to your fork
> 
> Otherwise, create a new branch (patch-16v2) starting from 8.1.x, cherry-pick the commits from the patch-16 branch and force-push targeting the patch-16 branch. It would then be necessary to change the destination branch of the PR to 8.1.x

I added you as collaborateur to the fork. Hope that is what you needed?

**Comment by M0rgan01** [comment]
@Shoprunners @MatShir  it's all good

**Review by M0rgan01 — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by M0rgan01** [comment]
thanks @Shoprunners
