### PR TITLE
Fix empty data by < in invoice note

### LINKED ISSUE #24893: BO - Orders - invoice note with invalid data
**Describe the bug**
In the BO > Orders > Order details page > when we add an  invoice note with invalid data, an Update successful alert is displayed by the note is empty.

**Expected behavior**
The user should be able to save any value.

**Steps to Reproduce**

1. Go to BO > Orders > Orders list page
2. View any order
3. In the invoice Tab, add a note with < hello > and save
4. See error: the invoice  note is still empty

#### Additional information

- PrestaShop version: 178x
- PHP version: 7.3

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In the BO > Orders > Order details page > when we add an invoice note with invalid data, an Update successful alert is displayed by the note is empty.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24893
| How to test?      | See issue 
| Possible impacts? | No

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24895)

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
Hi @okom3pom , unfortunately there is already an issue and a pull request that has been merged for this :/ 

https://github.com/PrestaShop/PrestaShop/pull/24867

**Comment by ghost** [comment]
Mine it's invoice notes you can check ?

**Comment by matthieu-rolland** [comment]
> Mine it's invoice note you can check ?

oh damn, excuse me, my mistake 👍

**Comment by matthieu-rolland** [comment]
could you create an issue for this? So that the product team can track this ? 
Meanwhile I approve your PR 👍

**Review by matthieu-rolland — COMMENTED** [review]
LGTM

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/issues/24893

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 1]
```diff
@@ -956,12 +957,15 @@ public function removeCartRuleAction(int $orderId, int $orderCartRuleId): Redire
...
-
-        $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
+        try {
+            $this->getCommandBus()->handle(new UpdateInvoiceNoteCommand(
+                $orderInvoiceId,
+                $request->request->get('invoice_note')
+            ));
+            $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
+        } catch (InvoiceException $e) {
+            $this->addFlash('error', $this->trans('Invalid characters:', 'Admin.Notifications.Info'));
```
Comment (Progi1984) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]: Invalid characters missing. Isn't it ?

**Review by Progi1984 — COMMENTED** [review]
A small comment

**Review by Progi1984 — COMMENTED** [review]
A last one :

- Could you add in `getErrorMessages` an `InvoiceException`, like  `OrderException::class`OrderException::class ?

After that, it should be ok for me.

File: src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php [hunk 2]
```diff
@@ -956,12 +957,18 @@ public function removeCartRuleAction(int $orderId, int $orderCartRuleId): Redire
...
-            $request->request->get('invoice_note')
-        ));
-
-        $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
+        try {
+            $this->getCommandBus()->handle(new UpdateInvoiceNoteCommand(
+                $orderInvoiceId,
+                $request->request->get('invoice_note')
+            ));
+            $this->addFlash('success', $this->trans('Successful update.', 'Admin.Notifications.Success'));
```
Comment (Julievrz) [inline src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php]:
```suggestion
            $this->addFlash('success', $this->trans('Update successful', 'Admin.Notifications.Success'));
```

**Review by Julievrz — DISMISSED** [review]
Wording ✔️ Thanks!

**Review by PierreRambaud — DISMISSED** [review]

File: classes/order/OrderInvoice.php [hunk 3]
```diff
@@ -112,7 +112,7 @@ class OrderInvoiceCore extends ObjectModel
             'total_wrapping_tax_excl' => ['type' => self::TYPE_FLOAT],
             'total_wrapping_tax_incl' => ['type' => self::TYPE_FLOAT],
             'shop_address' => ['type' => self::TYPE_HTML, 'validate' => 'isCleanHtml', 'size' => 1000],
-            'note' => ['type' => self::TYPE_STRING, 'validate' => 'isCleanHtml', 'size' => 65000],
+            'note' => ['type' => self::TYPE_HTML],
```
Comment (matks) [inline classes/order/OrderInvoice.php:115]: If I am not wrong, this change has huge impacts? Modify a column of objectmodel OrderInvoice?

From what I see in class ObjectModel, it will modify how `formatValue()`,  `getHtmlFields()` are processed when called on an object that is an instance of OrderInvoice (also for child classes)

Also if someone is analyzing the fields of an `$order_invoice` objectmodel and he is using
```
        if (array_key_exists('fields', $this->def)) {
            foreach ($this->def['fields'] as $name => $field) {
                if (is_array($field) && array_key_exists('type', $field) && self::TYPE_STRING === $field['type']) {
                    // do something
                }
            }
        }
```
it will not work anymore

So it looks like a BC break to me 🤔  .

Also if we remove `'validate' => 'isCleanHtml', 'size' => 65000` what are the default values for this field now?

**Review by Progi1984 — APPROVED** [review]

File: classes/order/OrderInvoice.php (hunk 3 above)
Comment (Progi1984) [reply classes/order/OrderInvoice.php:115]: It's not a BC Break as we don't define that field type of objectmodel are parts of our API.

**Review by Julievrz — APPROVED** [review]
Wording ✔️ Thanks

File: classes/order/OrderInvoice.php (hunk 3 above)
Comment (atomiix) [reply classes/order/OrderInvoice.php:115]: I'm not sure it's a BC either but I would keep `'size' => 65000` though 🤔

**Review by PierreRambaud — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for your PR!
I think that you're going to fix the Order note too, but it seems it's not the case :sweat_smile: 
Well, LGTM expect on mobile version: 

image

It will be good if we could improve the display of these buttons (like this):

image

@NeOMakinG wdyt? should @okom3pom fix it in this PR or should I open a new issue to fix it?

Thanks!

**Comment by NeOMakinG** [comment]
@hibatallahAouadni we can create another issue for this :)

**Comment by ghost** [comment]
Thanks @NeOMakinG , alignments is not my cup of tea :)

**Comment by hibatallahAouadni** [comment]
Well then, all LGTM (I will open a new issue about that issue).
So QA :heavy_check_mark: 

Thanks @okom3pom !

**Comment by PierreRambaud** [comment]
Thank you @okom3pom
