### PR TITLE
Make BO menu translatable

### LINKED ISSUE #9762: [BOOM-4692] Menu translation
## Log
24/03/2021 - remaining - Fix the lastest bug from the PR

## Description

> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4692).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Thu, 25 Jan 2018 09:25:29 +0100

### Steps to reproduce
1. Install shop in French. 
2. Import EN language 
3. Set your account on it 
4. See error > some menu texts are not translated correctly ("Order Settings" instead of "Orders").

### Additional infos

- PS version: 1.7.7.0
- PHP version: 7.2

### LINKED ISSUE #9816: [BOOM-4258] On BO orders menu I have item 'discount' instead of 'credit slips'
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4258).

- _**Reporter:**_ ldifaz
- _**Created at:**_ Tue, 7 Nov 2017 15:36:19 +0100

<p>With prestashop 1.7.2 in the BO main menu is show 'discount' (italian 'buoni sconto') in menu Orders instead of 'credit slips' (italian 'note di credito'). The traslation is correct (in the language module), and the form show the right content but also the first box show the wrong label 'discount' (italian 'buoni sconto') see the image attached.<br/>
Now my version is 1.7.2.4 and the problem is still there!<br/>
There is anyone can help me?</p>

<p>Thanks in advance. </p>
        
* How to reproduce the issue ?

N/A

### LINKED ISSUE #9893: [BOOM-3832] "Stock" menu cannot be translated
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3832).

- _**Reporter:**_ alexeven
- _**Created at:**_ Wed, 13 Sep 2017 11:53:21 +0200

<p>Hello, </p>

<p>The labels "Stocks" in the menu isn't translated.</p>

<p>A few things things:</p>

<p>1/ It should be "Stock" and not "Stocks"<br/>
2/ We have translations for "Stock" and Link using the domain Admin.Navigation.Menu.<br/>

<p>Please make sure this is translated + translatable, like the other labels from the menu.</p>

<p>Thanks,</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Make the BO menu translatable through the translation interface and get rid of translation problems when installing other languages.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9762 & Fixes #9893
| How to test?  | See below.

## About this change

This PR introduces several changes to the way automatic database content translation works.

### Understanding multi language entities, the menu, installer fixtures and automatic translation

Multi language entities in PrestaShop manage translated content by means of a second table, called `{entity_name}_lang`, where a copy of each one of the entity's multilingual fields are stored, translated to each of the installed languages.

Elements from the back office menu are stored in database and are managed by an entity called Tab. In order to have elements from the tab menu translated, the wordings from those "tabs" are multilingual.

On install, PrestaShop uses "data fixtures" (XML files containing predefined data) to populate certain tables, like shop configuration and elements of the BO menu, with default data. As a side note, this system is used for demo products as well.

During this process, wordings for multilingual entities are inserted on the database in the language chosen during install, or in English if translated fixtures for said data are not available (this is the case for Tab, which only has fixtures in English).

But as you have probably noticed, elements in the menu appear translated after you finish the translation in another language, like French. How does this happen?

PrestaShop has an _"automagic translation"_ feature for most multilingual entities. `Language::updateMultilangFromClass()` will loop through all tables finishing in `_lang`, and will try to translate their content using the appropriate class for that entity that extends `DataLang` (like `TabLang`, `ConfigurationLang`, `OrderStateLang`, and so forth) and is located in `classes/lang/`. 

Content is translated by performing a technique accurately described by @tomlev as _"untranslating and re-translating"_. It consists in taking the already translated content in the `lang` table, finding the original translation key by performing a reverse lookup in the translator component's dictionary, then using that key to translate the content into another language. 

This process is triggered during the install and whenever a new language is installed.

During install, Tab content is initially in English, regardless of your language of choice, because of fixtures. If you are installing in, say, French, the translator will contain a dictionary with pairs like `"Some Wording" => "Le wording en français"`. When the install process triggers this translation, it will find wordings like _"Some Wording"_ and will try to untranslate them. Since it won't find them, it will fall back to the original key. Then, it will perform a translation, resulting in _"Le wording en français"_, which is the value it will save.

If later on you install another language, like Spanish, then your dictionary will have pairs like `"Some Wording" => "El wording en español"`. Since content is saved in French, it will find values like _"Le wording en français"_ which results in _"Some Wording"_ when performing a reverse translation using the French dictionary. Using that key, we can translate the wording again using the Spanish dictionary, and we get _"El wording en español"_, which is saved in database.

### The problems

This sounds like a clever hack, and in most cases it works fine. However, in some cases two different wordings translate to the same phrase in a particular language. In those cases, a reverse translation could yield the wrong key, resulting in an erroneous translation to the target language.

The second problem appears in the specific case of the menu. Default menu entries are  supposed to be translatable via the translation interface in the Back Office (wordings are placed in the `Admin.Navigation.Menu` translation domain). However, translations modified through this interface are not reflected in the menu. This is because the automatic translation is not triggered after editing a translation, but even if it was, it would never work: the dictionary we're using to _"untranslate and retranslate"_ is the same we're updating. If the dictionary was updated before retranslation process, then the reverse lookup wouldn't work (because the menu name stored in database would be different from the one in the dictionary and therefore never found), and if the dictionary was updated after the retranslation process, then the previous value would be inserted in database, resulting in no change.

### The solutions

In my view, multilanguage data should be classified in two distinct groups. In the first one, wordings are stored as translation key and translation domain pairs, and are translated on the fly, exclusively via the translator component. In the second one, content is translated exclusively by the user via form (like, for example, a product's description). Mixing the two by performing untranslation and retranslation is an absurdity that results in too much complexity, which is at best unreliable.

This means that content which is not directly user-editable, like menu names, should always be translated using the translator, and never stored translated.

Ideally, this could be solved simply by adding a "wording" and "wording_domain" to each element in `tab`, and getting rid of `tab_lang` altogether. After that, it would be up to the presentation layer to get these properties and translate them on the fly using the translator. However, this would introduce a breaking change, since modules rely on the "name" property being stored translated. Therefore, this required a more complex solution.

In this change, I introduced the aforementioned columns, but kept the automatic translation feature so that the `name` column is still stored translated in `tab_lang` just as before. However, I added a specific behavior for Tab so that when the automatic translation is triggered, instead of performing a reverse translation lookup, it uses the provided wording and wording domain as basis for the retranslation. In order to provide zero-effort retrocompatibility, Tabs with no `wording` and `wording_domain` are translated using reverse lookup, just like before.

In addition, I refactored the retranslation feature a little so that I could trigger it on a single entity. This allows me to trigger a retranslation of Tabs whenever wordings from the menu domain (`Admin.Navigation.Menu`) are updated in the translation interface. 

Modules can also benefit from this system: they just need to fill out the `wording` and `wording_domain` fields on the tabs they create. If the wording exists in the catalogue, it will be translated. However, translating it from the back office interface won't trigger a retranslation unless it's attached to the `Admin.Navigation.Menu` domain. A future improvement could add a hook so that modules can add elements to the list of domains that trigger this.

**Updates on November 9, 2020:**

- Reworked how language packs are set up during the install 
  ⚠️ **WARNING:** This also includes that language packs are no longer downloaded again during install if already present in the `/translations` folder
- Removed a reference to "safe mode" during install, which no longer exists

**As noted on [April 8, 2021](https://github.com/PrestaShop/PrestaShop/pull/18082#issuecomment-815829907):**

Modules [need to be updated](https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/tabs/#since-prestashop-178) to allow their tabs to be translated automatically when installing a new language.

## How to test

1. Install PrestaShop in French. Menu and other auto translatable things like order states should be in French.
2. Install PrestaShop in English, then add French. Menu and other auto translatable things like order states should be in French or English depending on your choice of language.
3. Edit a menu item in the BO translation page. After refreshing the page, the menu item should appear as translated.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18082)

### CODE REVIEW

**Comment by Progi1984** [comment]
@eternoendless Your PR put Travis in the :red_circle: zone !

File: classes/Language.php [hunk 1]
```diff
@@ -1342,75 +1345,70 @@ public static function getLanguagePackListContent($iso, $tar)
...
      *
-     * @param $iso_code
+     * @param string $iso_code 2-letter language code
      *
      * @return bool
      */
     public static function updateMultilangTable($iso_code)
     {
-        $useLang = Db::getInstance()->getRow('SELECT * FROM `' . _DB_PREFIX_ . 'lang` WHERE `iso_code` = "' . pSQL($iso_code) . '" ', true, false);
+        $langId = Language::getIdByIso($iso_code);
```
Comment (PierreRambaud) [inline classes/Language.php]:
```suggestion
        $langId = static::getIdByIso($iso_code);
```

File: classes/Language.php [hunk 2]
```diff
@@ -1342,75 +1345,70 @@ public static function getLanguagePackListContent($iso, $tar)
...
 
-        if (!empty($useLang)) {
-            $lang = new Language($useLang['id_lang']);
+        if (!empty($langId)) {
+            $lang = new Language($langId);
```
Comment (PierreRambaud) [inline classes/Language.php]:
```suggestion
            $lang = new static($langId);
```

File: classes/Language.php [hunk 3]
```diff
@@ -1342,75 +1345,70 @@ public static function getLanguagePackListContent($iso, $tar)
...
+    public static function updateMultilangTables(Language $language, array $tablesToUpdate)
+    {
+        $translator = SymfonyContainer::getInstance()->get('translator');
+
+        foreach ($tablesToUpdate as $tableName) {
+            $className = (new DataLangFactory(_DB_PREFIX_, $translator))
+                ->getClassNameFromTable($tableName);
+
+            if (_DB_PREFIX_ . 'country_lang' === $tableName) {
+                self::updateMultilangFromCldr($language);
```
Comment (PierreRambaud) [inline classes/Language.php]:
```suggestion
                static::updateMultilangFromCldr($language);
```

File: classes/Language.php [hunk 4]
```diff
@@ -1342,75 +1345,70 @@ public static function getLanguagePackListContent($iso, $tar)
...
+            } else {
+                self::updateMultilangFromClass($tableName, $className, $language);
```
Comment (PierreRambaud) [inline classes/Language.php]:
```suggestion
                static::updateMultilangFromClass($tableName, $className, $language);
```

File: classes/Language.php [hunk 5]
```diff
@@ -1342,75 +1345,70 @@ public static function getLanguagePackListContent($iso, $tar)
...
+            }
+        }
+
+        Hook::exec('actionUpdateLangAfter', ['lang' => $language]);
```
Comment (PierreRambaud) [inline classes/Language.php]: Maybe add a 
`Hook::exec('actionUpdateLangBefore', ['lang' => $language]);` ?

File: classes/Language.php [hunk 6]
```diff
@@ -1447,43 +1445,43 @@ public static function updateMultilangFromCldr($lang)
      *
      * @param string $table
      * @param string $className
-     * @param string $lang
+     * @param Language $lang
```
Comment (PierreRambaud) [inline classes/Language.php]:
```suggestion
     * @param static $lang
```
?

File: classes/Tab.php [hunk 7]
```diff
@@ -77,6 +83,8 @@ class TabCore extends ObjectModel
             'enabled' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
             'hide_host_mode' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
             'icon' => ['type' => self::TYPE_STRING, 'size' => 64],
+            'wording' => ['type' => self::TYPE_STRING, 'validate' => 'isString', 'size' => 194],
```
Comment (PierreRambaud) [inline classes/Tab.php]: No need to put `194` if you don't add index on it :thinking:

File: classes/lang/TabLang.php [hunk 8]
```diff
@@ -23,12 +23,30 @@
...
+    public function getFieldValue($field, $value)
+    {
+        $domain = '';
+        if (is_array($value)) {
+            list($message, $domain) = $value;
+        } else {
+            $message = $value;
+        }
+
+        return $this->translator->trans($message, [], (!empty($domain)) ? $domain : $this->domain, $this->locale);
```
Comment (PierreRambaud) [inline classes/lang/TabLang.php]:
```suggestion
        return $this->translator->trans($message, [], (!empty($domain) ? $domain : $this->domain), $this->locale);
```
For a better readability

File: composer.json [hunk 9]
```diff
@@ -12,6 +12,7 @@
         "ext-json": "*",
         "ext-gd": "*",
         "ext-dom": "*",
+        "ext-simplexml": "*",
```
Comment (PierreRambaud) [inline composer.json]: composer.lock needs to be updated

File: install-dev/data/xml/tab.xml [hunk 10]
```diff
@@ -5,450 +5,697 @@
...
 
         <tab id="Dashboard" id_parent="" active="1" enabled="1" hide_host_mode="0" icon="trending_up">
             <class_name>AdminDashboard</class_name>
+            <wording>Dashboard</wording>
+            <wording_domain>Admin.Navigation.Menu</wording_domain>
         </tab>
 
         <!--SELL-->
         <tab id="SELL" id_parent="" active="1" enabled="1" hide_host_mode="0" icon="">
             <class_name>SELL</class_name>
```
Comment (PierreRambaud) [inline install-dev/data/xml/tab.xml:21]: Is these  `class_name` and `id` are ok? :thinking: 
```suggestion
        <tab id="Sell" id_parent="" active="1" enabled="1" hide_host_mode="0" icon="">
            <class_name>Sell</class_name>
```

File: install-dev/data/xml/tab.xml [hunk 11]
```diff
@@ -5,450 +5,697 @@
...
+                    <wording_domain>Admin.Navigation.Menu</wording_domain>
                 </tab>
 
-                    <tab id="Stock_Management" id_parent="Stock_Management" active="1" enabled="1" hide_host_mode="0" icon="">
+                    <tab id="Stock_Management" id_parent="Stock_Management_Parent" active="1" enabled="1" hide_host_mode="0" icon="">
                         <class_name>AdminStockManagement</class_name>
+                        <wording>Stock Management</wording>
+                        <wording_domain>Admin.Navigation.Menu</wording_domain>
                     </tab>
                     <tab id="Stock_Movement" id_parent="Stock_Management" active="1" enabled="1" hide_host_mode="0" icon="">
```
Comment (PierreRambaud) [inline install-dev/data/xml/tab.xml:218]:
```suggestion
                    <tab id="Stock_Movement" id_parent="Stock_Management_Parent" active="1" enabled="1" hide_host_mode="0" icon="">
```
?

Comment (PierreRambaud) [reply install-dev/data/xml/tab.xml:218]: And for others

File: install-dev/data/xml/tab.xml [hunk 12]
```diff
@@ -5,450 +5,697 @@
...
                 </tab>
                 <tab id="Configuration" id_parent="Advanced_stock_management" active="1" enabled="1" hide_host_mode="0" icon="">
                     <class_name>AdminStockConfiguration</class_name>
+                    <wording>Configuration</wording>
+                    <wording_domain>Admin.Navigation.Menu</wording_domain>
                 </tab>
 
 
         <!--IMPROVE-->
         <tab id="IMPROVE" id_parent="" active="1" enabled="1" hide_host_mode="0" icon="">
```
Comment (PierreRambaud) [inline install-dev/data/xml/tab.xml:247]: Again, an uppercase id :thinking:

File: install-dev/data/xml/tab.xml [hunk 13]
```diff
@@ -5,450 +5,697 @@
...
+                    <wording_domain>Admin.Navigation.Menu</wording_domain>
                 </tab>
                 <tab id="Mail_Theme_Parent" id_parent="Look_feel" active="1" enabled="1" hide_host_mode="0" icon="">
-                  <class_name>AdminParentMailTheme</class_name>
+                    <class_name>AdminParentMailTheme</class_name>
+                    <wording>Email Theme</wording>
+                    <wording_domain>Admin.Navigation.Menu</wording_domain>
                 </tab>
                     <tab id="Mail_Theme" id_parent="Mail_Theme_Parent" active="1" enabled="1" hide_host_mode="0" icon="">
-                      <class_name>AdminMailTheme</class_name>
```
Comment (PierreRambaud) [inline install-dev/data/xml/tab.xml:211]: Indentation in the whole file is totally broken :sweat_smile:

File: install-dev/upgrade/sql/1.7.8.0.sql [hunk 14]
```diff
@@ -9,3 +9,6 @@ INSERT IGNORE INTO `PREFIX_hook` (`id_hook`, `name`, `title`, `description`, `po
   (NULL, 'actionPresentProduct', 'Product Presenter', 'This hook is called before a product is presented', '1')
   (NULL, 'displayBanner', 'Display Banner', 'Use this hook for banners on top of every pages', '1')
 ;
+
+ALTER TABLE `PREFIX_tab` ADD `wording` VARCHAR(196) DEFAULT NULL AFTER `icon`;
```
Comment (PierreRambaud) [inline install-dev/upgrade/sql/1.7.8.0.sql]:
```suggestion
ALTER TABLE `PREFIX_tab` ADD `wording` VARCHAR(256) DEFAULT NULL AFTER `icon`;
```

File: install-dev/upgrade/sql/1.7.8.0.sql [hunk 15]
```diff
@@ -9,3 +9,6 @@ INSERT IGNORE INTO `PREFIX_hook` (`id_hook`, `name`, `title`, `description`, `po
...
+ALTER TABLE `PREFIX_tab` ADD `wording_domain` VARCHAR(196) DEFAULT NULL AFTER `wording`;
```
Comment (PierreRambaud) [inline install-dev/upgrade/sql/1.7.8.0.sql]:
```suggestion
ALTER TABLE `PREFIX_tab` ADD `wording_domain` VARCHAR(256) DEFAULT NULL AFTER `wording`;
```

File: src/Adapter/EntityTranslation/DataLangClassNameNotFoundException.php [hunk 16]
```diff
@@ -0,0 +1,32 @@
...
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to http://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
+namespace PrestaShop\PrestaShop\Adapter\EntityTranslation;
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/DataLangClassNameNotFoundException.php]:
```suggestion
namespace PrestaShop\PrestaShop\Adapter\EntityTranslation\Exception;
```

Could it be in a separated directory?

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 17]
```diff
@@ -0,0 +1,223 @@
...
+
+        $shopFieldExists = $this->shopFieldExists($tableNameSql);
+
+        // get table data
+        $sql = "SELECT * FROM `$tableNameSql` WHERE `id_lang` = $languageId"
+            . ($shopFieldExists ? sprintf(' AND `id_shop` = %d', $this->shopId) : '');
+
+        $tableData = $this->db->executeS($sql, true, false);
+
+        if (!empty($tableData)) {
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php]:
```suggestion
        if (empty($tableData)) {
            return;
        }
```

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 18]
```diff
@@ -0,0 +1,223 @@
...
+                        $updateField[] = '`' . bqSQL($fieldName) . '` = "' . pSQL($translatedField) . '"';
+                    }
+                }
+
+                // Update table
+                if (!empty($updateWhere) && !empty($updateField)) {
+                    $updateWhere = implode(' AND ', $updateWhere);
+                    $updateField = implode(', ', $updateField);
+
+                    $sql = "UPDATE `$tableNameSql` SET $updateField
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php]: Prepare the string outside the loop, and use sprintf instead. 
The `$shopFieldExists` shouldn't be executed on each loop.

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 19]
```diff
@@ -0,0 +1,223 @@
...
+     * Retrieves the original wording via reverse dictionary search (aka "untranslation")
+     *
+     * @param array $data
+     * @param string $fieldName
+     *
+     * @return string
+     */
+    protected function getSourceString(array $data, string $fieldName): string
+    {
+        return $this->translator->getSourceString($data[$fieldName], $this->dataLang->getDomain());
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php:211]: Make sure `$data[$fieldName]` exists?

File: src/PrestaShopBundle/Entity/Tab.php [hunk 20]
```diff
@@ -108,6 +108,20 @@ class Tab
      */
     private $icon;
 
+    /**
+     * @var string
+     *
+     * @ORM\Column(name="wording", type="string", length=194, nullable=true)
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Entity/Tab.php]:
```suggestion
     * @ORM\Column(name="wording", type="string", length=256, nullable=true)
```

File: src/PrestaShopBundle/Entity/Tab.php [hunk 21]
```diff
@@ -108,6 +108,20 @@ class Tab
...
+     */
+    private $wording;
+
+    /**
+     * @var string
+     *
+     * @ORM\Column(name="wording_domain", type="string", length=194, nullable=true)
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Entity/Tab.php]:
```suggestion
     * @ORM\Column(name="wording_domain", type="string", length=256, nullable=true)
```

File: src/PrestaShopBundle/Install/EntityLoader/FileLoader.php [hunk 22]
```diff
@@ -0,0 +1,143 @@
...
+     *
+     * @return string
+     */
+    private function getFallBackToDefaultEntityLanguage($iso, $entity)
+    {
+        if ($this->getFallbackToDefaultLanguage($iso) === self::FALLBACK_LANGUAGE_CODE) {
+            return self::FALLBACK_LANGUAGE_CODE;
+        }
+
+        return file_exists($this->langPath . $this->getFallbackToDefaultLanguage($iso) . '/data/' . $entity . '.xml') ? $iso :
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Install/EntityLoader/FileLoader.php]: You did thee times `file_exists` here. Why not checking only:
```suggestion
        return file_exists($this->langPath . $iso . '/data/' . $entity . '.xml') ? $iso : self::FALLBACK_LANGUAGE_CODE;
```

And you can remove `getFallbackToDefaultLanguage` method, and the previous check :thinking:

**Comment by marionf** [comment]
@eternoendless Does this PR will fix also #9816 and #9893 ?

**Comment by eternoendless** [comment]
@marionf I think it should. However the "Link widget" may need an update in the module

File: classes/Language.php (hunk 5 above)
Comment (eternoendless) [reply classes/Language.php]: What for?

File: install-dev/data/xml/tab.xml (hunk 10 above)
Comment (eternoendless) [reply install-dev/data/xml/tab.xml:21]: I don't remember what I found out about these but since it's unrelated I'd prefer to leave it as is for now. Be aware that this tab exists as it is since 1.7.0.

File: install-dev/data/xml/tab.xml (hunk 11 above)
Comment (eternoendless) [reply install-dev/data/xml/tab.xml:218]: Again, this is shadowy terrain that should definitely be explored, but not in this PR!

File: install-dev/data/xml/tab.xml (hunk 13 above)
Comment (eternoendless) [reply install-dev/data/xml/tab.xml:211]: Yes because the structure makes no sense. This indentation is meant to reflect the menu structure which doesn't follow the xml structure (or is it the other way around? 🤪) 

Anyway I spent some hours trying to fix it and I found myself falling through the "refactor ALL the things!" rabbit hole, so I backtracked and decided to focus on the original intent.

File: src/Adapter/EntityTranslation/EntityTranslator.php (hunk 18 above)
Comment (eternoendless) [reply src/Adapter/EntityTranslation/EntityTranslator.php]: I'm refactoring the $shopFieldExists but leaving the string interpolation. AFAIK `sprintf` won't add anything and replacing named tokens with `%s` will decrease readability.

File: src/Adapter/EntityTranslation/EntityTranslator.php (hunk 19 above)
Comment (eternoendless) [reply src/Adapter/EntityTranslation/EntityTranslator.php:211]: Okay

File: src/PrestaShopBundle/Install/EntityLoader/FileLoader.php (hunk 22 above)
Comment (eternoendless) [reply src/PrestaShopBundle/Install/EntityLoader/FileLoader.php]: Okay, but if for any reason this stops working you'll fix it 😛

**Comment by eternoendless** [comment]
@PierreRambaud rebased and changes applied.

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 23]
```diff
@@ -0,0 +1,238 @@
...
+     * Builds the table name using the DataLang class as source
+     *
+     * @param DataLangCore $dataLang
+     *
+     * @return string The table name, including prefix
+     */
+    private function buildTableNameFromDataLang(DataLangCore $dataLang): string
+    {
+        $tableName = Inflector::tableize(get_class($dataLang));
+        if (substr($tableName, 0, strlen(_DB_PREFIX_)) !== _DB_PREFIX_) {
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php]: Use `construct` parameter for `dbprefix` like in `DataLangFactory`

Comment (eternoendless) [reply src/Adapter/EntityTranslation/EntityTranslator.php]: Done!

**Review by PierreRambaud — DISMISSED** [review]

File: install-dev/data/xml/tab.xml [hunk 24]
```diff
@@ -5,450 +5,697 @@
...
                     </tab>
                     <tab id="Marketing_tools" id_parent="Module_Catalog" active="1" enabled="1" hide_host_mode="0" icon="">
                         <class_name>AdminAddonsCatalog</class_name>
+                        <wording>Module Selections</wording>
+                        <wording_domain>Admin.Navigation.Menu</wording_domain>
                     </tab>
                 <tab id="Module_Page_old" id_parent="Modules" active="0" enabled="1" hide_host_mode="0" icon="">
                     <class_name>AdminModules</class_name>
+                    <wording/>
+                    <wording_domain/>
```
Comment (Progi1984) [inline install-dev/data/xml/tab.xml:297]: Normal ?

File: src/Adapter/EntityTranslation/DataLangFactory.php [hunk 25]
```diff
@@ -0,0 +1,142 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to http://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/DataLangFactory.php:28]:
```suggestion
declare(strict_types=1);
```

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 26]
```diff
@@ -0,0 +1,246 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to http://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/EntityTranslator.php:28]:
```suggestion
declare(strict_types=1);

```

File: src/Adapter/EntityTranslation/EntityTranslatorFactory.php [hunk 27]
```diff
@@ -0,0 +1,107 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/EntityTranslatorFactory.php:28]:
```suggestion
declare(strict_types=1);

```

File: src/Adapter/EntityTranslation/Exception/DataLangClassNameNotFoundException.php [hunk 28]
```diff
@@ -0,0 +1,32 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to http://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/Exception/DataLangClassNameNotFoundException.php:28]:
```suggestion
declare(strict_types=1);

```

File: src/Adapter/EntityTranslation/TabTranslator.php [hunk 29]
```diff
@@ -0,0 +1,84 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to http://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/TabTranslator.php:28]:
```suggestion
declare(strict_types=1);

```

File: src/Core/Translation/EntityTranslatorInterface.php [hunk 30]
```diff
@@ -0,0 +1,41 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/Core/Translation/EntityTranslatorInterface.php:27]:
```suggestion
declare(strict_types=1);

```

File: src/PrestaShopBundle/Install/EntityLoader/FileLoader.php [hunk 31]
```diff
@@ -0,0 +1,164 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to http://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/PrestaShopBundle/Install/EntityLoader/FileLoader.php:28]:
```suggestion
declare(strict_types=1);

```

File: src/PrestaShopBundle/Translation/TranslatorInterface.php [hunk 32]
```diff
@@ -0,0 +1,59 @@
...
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
+namespace PrestaShopBundle\Translation;
+
```
Comment (Progi1984) [inline src/PrestaShopBundle/Translation/TranslatorInterface.php:29]:
```suggestion

use Symfony\Component\Translation\TranslatorInterface as SymfonyTranslatorInterface;
```

File: src/PrestaShopBundle/Translation/TranslatorInterface.php [hunk 33]
```diff
@@ -0,0 +1,59 @@
...
+/**
+ * Interface for PrestaShop translators
+ */
+interface TranslatorInterface extends \Symfony\Component\Translation\TranslatorInterface
```
Comment (Progi1984) [inline src/PrestaShopBundle/Translation/TranslatorInterface.php]:
```suggestion
interface TranslatorInterface extends SymfonyTranslatorInterface
```

File: src/PrestaShopBundle/Translation/TranslatorInterface.php [hunk 34]
```diff
@@ -0,0 +1,59 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline src/PrestaShopBundle/Translation/TranslatorInterface.php:27]:
```suggestion
declare(strict_types=1);

```

File: tests/Unit/Adapter/Translations/DataLangFactoryTest.php [hunk 35]
```diff
@@ -0,0 +1,59 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
```
Comment (Progi1984) [inline tests/Unit/Adapter/Translations/DataLangFactoryTest.php:27]:
```suggestion
declare(strict_types=1);

```

**Review by Progi1984 — COMMENTED** [review]
Some changes

**Review by matthieu-rolland — DISMISSED** [review]

File: install-dev/data/xml/tab.xml (hunk 24 above)
Comment (eternoendless) [reply install-dev/data/xml/tab.xml:297]: Yes, this tab was never translated. I don't really know why it's here, notice it's `active="0"`.

Comment (Progi1984) [reply install-dev/data/xml/tab.xml:297]: Ok for me ;)

File: src/PrestaShopBundle/Translation/TranslatorInterface.php [hunk 36]
```diff
@@ -0,0 +1,61 @@
...
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2020 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+declare(strict_types=1);
+
+namespace PrestaShopBundle\Translation;
+
+use Symfony\Component\Translation\TranslatorInterface as SymfonyTranslatorInterface;
```
Comment (Progi1984) [inline src/PrestaShopBundle/Translation/TranslatorInterface.php:30]:
```suggestion
use Symfony\Component\Translation\TranslatorInterface as SymfonyTranslatorInterface;

```

**Comment by Progi1984** [comment]
@eternoendless Some PHPCS fix errors ;) and Travis is now :green_circle:

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SD1982** [comment]
> ## How to test
> 1. Install PrestaShop in French. Menu and other auto translatable things like order states should be in French.
> 2. Install PrestaShop in English, then add French. Menu and other auto translatable things like order states should be in French or English depending on your choice of language.
> 3. Edit a menu item in the BO translation page. After refreshing the page, the menu item should appear as translated.

Hi @eternoendless If I reproduce step 2 everything is ok but if I do it in reverse i mean install in French => add English it doesn't seem to work properly the menu stays in french
https://drive.google.com/file/d/1U49TDB1kaQChUUp-7wR9p1DA-0kLeGy4/view?usp=sharing

I also have an exception when trying to update a langage : 
https://drive.google.com/file/d/1AO7eV7S_dqvPEZFsSEp0_JlRDXMXnfZl/view?usp=sharing

File: src/PrestaShopBundle/Translation/DataCollectorTranslator.php [hunk 37]
```diff
@@ -29,7 +29,23 @@
...
+    {
+        return $this->__call('isLanguageLoaded', [$locale]);
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function clearLanguage($locale)
+    {
+        return  $this->__call('clearLanguage', [$locale]);
```
Comment (Pierstoval) [inline src/PrestaShopBundle/Translation/DataCollectorTranslator.php]: I'm not sure about these two methods. They seem to use the [base translator's __call() method](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/DataCollectorTranslator.php#L113-L116) but it needs a decorated translator.

Why don't you call `$this->translator->clearLanguage($locale)`, since the decorated translator should anyway be an instance of Prestashop's one?
You could even type-hint this in the class with `/** @​property PrestashopTranslator $translator */` (of course you would need to import the namespace for auto-completion in IDEs).

Comment (eternoendless) [reply src/PrestaShopBundle/Translation/DataCollectorTranslator.php]: I had forgotten about this, the answer is pretty simple: the translator property is private on the original DataCollectorTranslator, so I can't access it 😢 

That said I think I could have used `parent::isLanguageLoaded()` and it would have been routed automagically all the same. But I don't know if it would have been clearer that way either anyway 😁

Comment (Pierstoval) [reply src/PrestaShopBundle/Translation/DataCollectorTranslator.php]: Calling `parent::isLanguageLoaded()` is definitely the way to go. Relying on magic methods is almost never a good option. Especially when the base method is reachable through `parent::` 🙂  (and especially in this case where it's more a hack than a true feature/pattern usage)

**Comment by eternoendless** [comment]
Rebased and bugs fixed.

- Reworked how language packs are set up during the install 
  ⚠️ **WARNING:** This also includes that language packs are no longer downloaded again during install if already present in the `/translations` folder
- Removed a reference to "safe mode" during install, which no longer exists
- Shuffled code around in Language class

### It works on my computer!

- Tested install in French, adding English, switching to that language, changing menu translations, installing more languages, uninstalling languages and reinstalling them again...
- Also verified that mail templates are in the correct language, as well as currencies
- Note: I installed English through localization pack, for all other languages I used _International > Translations > Add / update a language_

File: classes/Language.php [hunk 38]
```diff
@@ -39,12 +42,23 @@ class LanguageCore extends ObjectModel implements LanguageInterface
     const ALL_LANGUAGES_FILE = '/app/Resources/all_languages.json';
     const SF_LANGUAGE_PACK_URL = 'https://i18n.prestashop.com/translations/%version%/%locale%/%locale%.zip';
     const EMAILS_LANGUAGE_PACK_URL = 'https://i18n.prestashop.com/mails/%version%/%locale%/%locale%.zip';
+    const PACK_TYPE_EMAILS = 'emails';
+    const PACK_TYPE_SYMFONY = 'sf';
```
Comment (Progi1984) [inline classes/Language.php]:
```suggestion
    public const PACK_TYPE_EMAILS = 'emails';
    public const PACK_TYPE_SYMFONY = 'sf';
```

File: src/PrestaShopBundle/Translation/DataCollectorTranslator.php (hunk 37 above)
Comment (eternoendless) [reply src/PrestaShopBundle/Translation/DataCollectorTranslator.php]: I had to revert to this because PHPStan doesn't support calls to `parent` if the method is not declared  in the parent and routed with `__call()` ☹️ 

See https://github.com/PrestaShop/PrestaShop/pull/18082/checks?check_run_id=1375456805

File: classes/Language.php [hunk 39]
```diff
@@ -1256,31 +1335,87 @@ public static function installEmailsLanguagePack($lang_pack, &$errors = [])
...
+     * @param string $iso Language ISO code
+     * @param array $params Optional parameters for self::checkAndAddLanguage
+     * @param array $errors
+     *
+     * @return bool
+     *
+     * @throws PrestaShopDatabaseException
+     * @throws PrestaShopException
+     */
+    public static function installFirstLanguagePack(string $iso, array $params = [], &$errors = []): bool
```
Comment (Progi1984) [inline classes/Language.php]:
```suggestion
    public static function installFirstLanguagePack(string $iso, array $params = [], array &$errors = []): bool
```

File: classes/lang/DataLang.php [hunk 40]
```diff
@@ -36,26 +38,33 @@
...
-    /** @var string */
+    /** @var string Default translation domain */
     protected $domain;
 
-    public function __construct($locale)
+    /**
+     * @param string $locale
+     * @param TranslatorInterface|null $translator If defined, use this translator
+     */
+    public function __construct($locale, $translator = null)
```
Comment (Progi1984) [inline classes/lang/DataLang.php]:
```suggestion
    public function __construct($locale, ?TranslatorInterface $translator = null)
```

File: classes/Tab.php [hunk 41]
```diff
@@ -80,6 +86,8 @@ class TabCore extends ObjectModel
             'enabled' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
             'hide_host_mode' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
             'icon' => ['type' => self::TYPE_STRING, 'size' => 64],
+            'wording' => ['type' => self::TYPE_STRING, 'validate' => 'isString', 'size' => 255],
+            'wording_domain' => ['type' => self::TYPE_STRING, 'validate' => 'isString', 'size' => 255],
```
Comment (Progi1984) [inline classes/Tab.php]:
```suggestion
            'wording' => ['type' => self::TYPE_STRING, 'validate' => 'isString', 'allow_null' => true, 'size' => 255],
            'wording_domain' => ['type' => self::TYPE_STRING, 'validate' => 'isString', 'allow_null' => true, 'size' => 255],
```

File: classes/Tab.php [hunk 42]
```diff
@@ -58,6 +58,12 @@ class TabCore extends ObjectModel
     /** @var string Icon font */
     public $icon;
 
+    /** @var string Wording to use for the display name */
+    public $wording;
+
+    /** @var string Wording domain to use for the display name */
+    public $wording_domain;
```
Comment (Progi1984) [inline classes/Tab.php]:
```suggestion
    /** @var string|null Wording to use for the display name */
    public $wording;

    /** @var string|null Wording domain to use for the display name */
    public $wording_domain;
```

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 43]
```diff
@@ -0,0 +1,246 @@
...
+     * @param TranslatorInterface $translator
+     * @param DataLangCore $dataLang
+     */
+    public function __construct(
+        Db $db,
+        string $dbPrefix,
+        TranslatorInterface $translator,
+        DataLangCore $dataLang
+    ) {
+        //$this->translatorLanguageLoader = new TranslatorLanguageLoader(true);
```
Comment (Progi1984) [inline src/Adapter/EntityTranslation/EntityTranslator.php]:
```suggestion
```

File: src/PrestaShopBundle/Entity/Tab.php [hunk 44]
```diff
@@ -108,6 +108,20 @@ class Tab
      */
     private $icon;
 
+    /**
+     * @var string
```
Comment (Progi1984) [inline src/PrestaShopBundle/Entity/Tab.php]:
```suggestion
     * @var string|null
```

File: src/PrestaShopBundle/Entity/Tab.php [hunk 45]
```diff
@@ -108,6 +108,20 @@ class Tab
...
+     *
+     * @ORM\Column(name="wording", type="string", length=255, nullable=true)
+     */
+    private $wording;
+
+    /**
+     * @var string
```
Comment (Progi1984) [inline src/PrestaShopBundle/Entity/Tab.php]:
```suggestion
     * @var string|null
```

File: src/PrestaShopBundle/Entity/Tab.php [hunk 46]
```diff
@@ -158,6 +172,22 @@ public function getTabLangs()
         return $this->tabLangs;
     }
 
+    /**
+     * @return string|null
+     */
+    public function getWording()
```
Comment (Progi1984) [inline src/PrestaShopBundle/Entity/Tab.php]:
```suggestion
    public function getWording(): ?string
```

File: src/PrestaShopBundle/Entity/Tab.php [hunk 47]
```diff
@@ -158,6 +172,22 @@ public function getTabLangs()
...
+    {
+        return $this->wording;
+    }
+
+    /**
+     * @return string|null
+     */
+    public function getWordingDomain()
```
Comment (Progi1984) [inline src/PrestaShopBundle/Entity/Tab.php]:
```suggestion
    public function getWordingDomain(): ?string
```

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Translation/DataCollectorTranslator.php (hunk 37 above)
Comment (Pierstoval) [reply src/PrestaShopBundle/Translation/DataCollectorTranslator.php]: @eternoendless PHPStan is not a true god that you have to follow! If you're certain that you have the right class at the right moment, and you tested the feature, then it works, and you can add an exception to PHPStan. If you do so, remember to add a small comment to explain why there's an exception :)

**Comment by Julievrz** [comment]
Hi @eternoendless, the wordling looks good to me but I only spotted 2 strings. Is there something else that I might be missing? Thanks

**Comment by eternoendless** [comment]
Don't worry @Julievrz I didn't change any of the existing wordings (nor did I add any new one).

**Comment by eternoendless** [comment]
Rebased again

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 48]
```diff
@@ -0,0 +1,245 @@
...
+            // Update table
+            if (!empty($updateWhere) && !empty($updateFields)) {
+                $updateWhere = implode(' AND ', $updateWhere);
+                $updateFields = implode(', ', $updateFields);
+
+                $sql = "UPDATE `$tableNameSql`
+                    SET $updateFields
+                    WHERE $updateWhere AND `id_lang` = $languageId"
+                    . $shopWhere
+                    . ' LIMIT 1';
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php:161]:
```suggestion
                $sql = 'UPDATE `' . $tableNameSql . '` '
                    'SET $updateFields ' .
                    'WHERE ' . $updateWhere . ' AND `id_lang` = ' . $languageId . ' ' .
                    . $shopWhere
                    . ' LIMIT 1';
```

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 49]
```diff
@@ -0,0 +1,245 @@
...
+     * @param string $tableNameSql
+     *
+     * @return bool
+     *
+     * @throws \PrestaShopDatabaseException
+     */
+    protected function shopFieldExists(string $tableNameSql): bool
+    {
+        $columns = $this->db->executeS(
+            sprintf('SHOW COLUMNS FROM `%s`', $tableNameSql)
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php]:
```suggestion
            sprintf('SHOW COLUMNS FROM `%s`', bqSQL($tableNameSql))
```

File: src/Adapter/EntityTranslation/EntityTranslator.php [hunk 50]
```diff
@@ -0,0 +1,245 @@
...
+        );
+
+        foreach ($columns as $column) {
+            if ($column['Field'] == 'id_shop') {
```
Comment (PierreRambaud) [inline src/Adapter/EntityTranslation/EntityTranslator.php]:
```suggestion
            if ($column['Field'] === 'id_shop') {
```

File: src/PrestaShopBundle/Install/EntityLoader/FileLoader.php [hunk 51]
```diff
@@ -0,0 +1,165 @@
...
+     * Returns the lookup paths for the provided entity / iso.
+     *
+     * @param string $entity Entity name
+     * @param string|null $iso [default=null] 2-letter language code
+     *
+     * @return string[] List of lookup paths
+     */
+    private function getLookupPaths(string $entity, ?string $iso = null): array
+    {
+        $fileName = "$entity.xml";
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Install/EntityLoader/FileLoader.php:144]:
```suggestion
        $fileName = $entity . '.xml';
```

Comment (eternoendless) [reply src/PrestaShopBundle/Install/EntityLoader/FileLoader.php:144]: I don't get this obsession with single quotes. I find interpolation much more readable.

File: src/Adapter/EntityTranslation/EntityTranslator.php (hunk 48 above)
Comment (eternoendless) [reply src/Adapter/EntityTranslation/EntityTranslator.php:161]: There is an error in your suggestion. IMO I find the original more readable.

Comment (PierreRambaud) [reply src/Adapter/EntityTranslation/EntityTranslator.php:161]: I just don't like mixing ways to concatenate variables in strings :roll_eyes:

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@eternoendless Please rebase (PHPStan is :red_circle: & composer has conflicts).

File: src/PrestaShopBundle/Install/EntityLoader/FileLoader.php (hunk 51 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Install/EntityLoader/FileLoader.php:144]: Just a habit, make sure the code is always written in the same way

**Comment by eternoendless** [comment]
Rebased once again

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Translation/TranslatorInterface.php [hunk 52]
```diff
@@ -0,0 +1,62 @@
...
+
+/**
+ * Interface for PrestaShop translators
+ */
+interface TranslatorInterface extends SymfonyTranslatorInterface
+{
+    /**
+     * Performs a reverse search in the catalogue and returns the translation key if found.
+     * AVOID USING THIS, IT PROVIDES APPROXIMATE RESULTS.
```
Comment (sowbiba) [inline src/PrestaShopBundle/Translation/TranslatorInterface.php:39]: ???

**Review by sowbiba — DISMISSED** [review]
Rebase needed

**Comment by eternoendless** [comment]
I'm not rebasing this again until it's been validated by QA

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

This issue https://github.com/PrestaShop/PrestaShop/issues/9893 is not fixed with this PR
I cannot translate the `Stock` menu because it doesn't exist 

This issue: https://github.com/PrestaShop/PrestaShop/issues/9816 is not fixed with this PR
image

But I can change the translation successfully 
image

Also, I found an error

1. Install shop with French language & France country
2. Go to BO > International > Localization page
3. Upload United states pack
4. Change employee language to English
5. The menu Design > Themes Catalog is still displayed in French Catalogue de thèmes
6. I tried to translate it but I found 
image

I tried to change the translation of this expression in French, I found two similar expressions of `Catalogue de thèmes`
image

Thank you!

**Comment by eternoendless** [comment]
I Rebased the PR and added two commits:
- 15ede64 - which fixes the Stock wording
- 6c594e5 - which adds support for registering wording and wording domain in module tabs

@khouloudbelguith please test my PR again.

> This issue #9893 is not fixed with this PR
> I cannot translate the `Stock` menu because it doesn't exist

* The `Stock` wording is now fixed in this PR. 
* The other problem is fixed by in the Link Widget module: https://github.com/PrestaShop/ps_linklist/pull/116 (which requires this PR to work).

Regarding the "Theme Catalog" not being translated - this is actually due to the same problem that I fixed in Link Widget, but in this case it must be fixed in MBO. In fact, every module that adds a menu item will display the same problem and need to be fixed individually (ie. the module must register the Tab adding `wording` and `wording_domain`). The problem itself is unrelated to the PR, but this PR makes it possible to fix it!

File: composer.lock [hunk 53]
```diff
@@ -58,6 +58,9 @@
                 "doctrine",
                 "orm"
             ],
+            "support": {
```
Comment (Progi1984) [inline composer.lock]: Please remove modifications on composer.lock

**Review by Progi1984 — COMMENTED** [review]
A small feedback

File: composer.lock (hunk 53 above)
Comment (eternoendless) [reply composer.lock]: These are added automatically by composer when you run `composer update nothing`
If I change it then composer.lock will become out of sync with composer.json

**Review by Progi1984 — DISMISSED** [review]

File: composer.lock (hunk 53 above)
Comment (Progi1984) [reply composer.lock]: composer.lock is again out of sync

Comment (eternoendless) [reply composer.lock]: I will update it again once QA has validated it

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

It is ok :heavy_check_mark: 
I make these tests:
1. Install Shop with Arabic language + Saudi Arabia country
2. Add some language via Translation page & pack via Localization page
3. Translate some menus
4. Install Shop with English language + France country
5. Install Shop with French language + France country
6. #9762 => fixed / #9893 (Stock menu) => fixed
7. Add Japan language via Translations page (translate some menus)
8. Import Algeria pack
10. Update all Core Menu 
image

PS: https://github.com/PrestaShop/PrestaShop/issues/9816 still exists
https://github.com/PrestaShop/PrestaShop/issues/23156#issuecomment-774157511 still exists

Thank you!

**Comment by eternoendless** [comment]
Rebased

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by eternoendless** [comment]
Re rebased. Hopefully tests will pass now?

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by eternoendless** [comment]
After rebase, a new Tab had been introduced in fixtures, breaking the install.

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by eternoendless** [comment]
Thanks everyone! 🎉
