### PR TITLE
Fix bulk module actions

### LINKED ISSUE #12011: The bulk actions to uninstall modules does not work on 1.7.5.0
Hi
the bulk actions to unistall modules does not work on 1.7.5.0
if I do manually it is ok but one by one

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Bulk actions didn't work any more because cache was clear during parallel calls. So a request parameter was added to allow perform actions on a module without clearing cache. Then javascript was updated for bulk actions, so that all actions are performed without clearing the cache except for the last one which clears the cache at the end. The same bug happened when using the button "Upgrade all", it now uses the same process.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12011 & #12044
| How to test?  | Try to perform bulk actions on modules (one or more). Also try to update all possible modules with the "Update all" button.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12205)

### CODE REVIEW

File: src/Core/Addon/Module/ModuleManager.php [hunk 1]
```diff
@@ -615,7 +627,9 @@ public function enableMobile($name)
             );
         }
 
-        $this->clearCache();
+        if ($result && $this->actionParams->get('cacheClearEnabled', true)) {
```
Comment (PierreRambaud) [inline src/Core/Addon/Module/ModuleManager.php]: This could be a function to remove duplicate.

```php
function checkForCacheAndClearYouKnowItBro($result) {
  if ($result && $this->actionParams->get('cacheClearEnabled', true)) {
    $this->clearCache();
  }
} 
```

Comment (jolelievre) [reply src/Core/Addon/Module/ModuleManager.php]: yep,  good idea

Comment (jolelievre) [reply src/Core/Addon/Module/ModuleManager.php]: done

**Review by PierreRambaud — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/components/module-card.js [hunk 2]
```diff
@@ -222,7 +222,7 @@ export default class ModuleCard {
     return (event.result !== false); // explicit false must be set from handlers to stop propagation of the click event.
   };
 
-  _requestToController(action, element, forceDeletion) {
+  _requestToController(action, element, forceDeletion, disableCacheClear, requestCallback) {
```
Comment (Quetzacoalt91) [inline admin-dev/themes/new-theme/js/components/module-card.js]: `callback` is commonly used.

File: admin-dev/themes/new-theme/js/pages/module/controller.js [hunk 3]
```diff
@@ -1028,7 +1065,26 @@ class AdminModuleController {
...
-      $(self.upgradeAllTargets).click();
+
+      if ($(self.upgradeAllTargets).length <= 0) {
+        console.warn(window.translate_javascripts['Upgrade All Action - One module minimum']);
+        return false;
+      }
+
+      const modulesActions = [];
+      let moduleTechName;
+      $(self.upgradeAllTargets).each(function bulkActionSelector() {
```
Comment (Quetzacoalt91) [inline admin-dev/themes/new-theme/js/pages/module/controller.js:1091]: Looks like this method already exist l.956, a refacto could be done here.

Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/module/controller.js:1091]: Well that's what I initially tried to do, but it's not exactly the same
The clicked elements and HTML structure is a bit different so each case needs to build this array itself

**Comment by mbadrani** [comment]
@jolelievre tricky scenario, if you make an action (bulk actions) twice, you enter into an infinite loop
image
for my example I've disabled 3 modules on bulk actions (best suppliers, best vouchers and best-selling products) and disable another time (it appears on the list of bulk actions), best suppliers and best vouchers return an error pop-up (normal behavior), but the third one stay with his spinner for infinite time

**Comment by PierreRambaud** [comment]
@mbadrani Is it QA approved? You said there is an infinite loop :open_mouth:

**Comment by jolelievre** [comment]
No it's not approved there is a bug when some of the bulk actions fail, the last one remains pending and the spinner is still visible.

**Comment by mbadrani** [comment]
If we consider only the aim of the PR it's fine for me but my last comment was just an observation in a particular tricky scenarii, tell me if this PR is good enough and if we will create in a second time something to fix this behavior

**Comment by PierreRambaud** [comment]
I remove the "QA :heavy_check_mark:" since there is still a bug.

**Comment by jolelievre** [comment]
It shouldn't be long to fix so we'd better fix it now

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by mbadrani** [comment]
well done @jolelievre
