### PR TITLE
Do not allow the selection of any subcategories

### LINKED ISSUE #14100: You shouldn't be able to move a parent category in a sub category
**Describe the bug**
You shouldn't be able to move a parent category in a sub category

**To Reproduce**
1. Go to Catalog > Categories
2. Click on edit for Clothes
3. Select Women as parent category
4. See error with max execution time
5. Return to the category list, the category edited disappeared

**Screenshots**
capture d'écran_1642

On 1.7.5.2 it was not possible to move a parent category in the sub category, they was disabled

capture d'écran_1643

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | See #14100 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14100 
| How to test?  | See #14100 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14107)

### CODE REVIEW

File: src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php [hunk 1]
```diff
@@ -71,6 +73,25 @@ public function handle(GetCategoryForEditing $query)
             );
         }
 
+        /**
+         * Select recursivly the subcategories in one SQL request
+         *
+         * @see https://dev.mysql.com/doc/refman/8.0/en/with.html
```
Comment (matks) [inline src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php]: Is it a mysql 8 only feature ? If yes, I'm afraid we cant use it 😢

Comment (PierreRambaud) [reply src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php]: Oh my gad, I checked only for this
image
And thinking everything was ok :sob: :sob:

Comment (PierreRambaud) [reply src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler.php]: Done! Thanks a lot

**Review by matks — DISMISSED** [review]

**Review by matks — APPROVED** [review]
