### PR TITLE
Do not proceed setCurrentState if order already has the right state

### LINKED ISSUE #20623: setCurrentState to the same id_order_state
#### Describe the bug

It happens at every webservice PUT request for updating any order field. The order_state is reprocessed without checking if the order already has the state, sending the state's email and triggering all related hooks.

#### Expected behavior

If the order already has the requested state, avoid to execute the setCurrentState's body

#### Steps to Reproduce

Create an order state with the email sending option set to on, put an order to this state and then, send again the same put request using the WS. You will receive two emails because the order has changed twice to the same state.

#### Additional information

Fix related: https://github.com/PrestaShop/PrestaShop/pull/20622

### PR DESCRIPTION
**Pull request by bertoferrero**
This fix avoids executing the setCurrentState body if the order already has that id_order_state

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | It happens at every webservice PUT request for updating any order field. The order_state is reprocessed without checking if the order already has the state, sending the state's email and triggering all related hooks.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20623
| How to test?  | Create an order state with the email sending option set to on, put an order to this state and then, send again the same put request using the WS. You will receive two emails because the order has changed twice to the same state.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20622)

### CODE REVIEW

File: classes/order/Order.php [hunk 1]
```diff
@@ -1673,9 +1673,12 @@ public function getWsOrderRows()
      */
     public function setCurrentState($id_order_state, $id_employee = 0)
     {
-        if (empty($id_order_state)) {
+        if (empty($id_order_state) || $id_order_state == $this->current_state) {
             return false;
         }
+        if ($id_order_state == $this->current_state) {
```
Comment (PululuK) [inline classes/order/Order.php]: unnecessary 🤔 ?
Already checked just before

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Duplicated condition as @PululuK said :)

File: classes/order/Order.php (hunk 1 above)
Comment (bertoferrero) [reply classes/order/Order.php]: Yes, you are right, a mistake pasting the code, let me fix it.

**Comment by bertoferrero** [comment]
> 
> 
> Duplicated condition as @PululuK said :)

Fixed, sorry

File: classes/order/Order.php [hunk 2]
```diff
@@ -1673,7 +1673,7 @@ public function getWsOrderRows()
      */
     public function setCurrentState($id_order_state, $id_employee = 0)
     {
-        if (empty($id_order_state)) {
+        if (empty($id_order_state) || $id_order_state == $this->current_state) {
```
Comment (PierreRambaud) [inline classes/order/Order.php]:
```suggestion
        if (empty($id_order_state) || (int) $id_order_state === (int) $this->current_state) {
```
Let's have a strict comparison :)

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Nice catch :) thanks, moving to QA now

**Comment by khouloudbelguith** [comment]
Hi @prestaquality,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1sfGY4HXpt18g-mULlMmKcLcpAXXfjJcO/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @prestaquality & @khouloudbelguith
