### PR TITLE
Fixed Update Quantity in an order in multishop context

### LINKED ISSUE #21987: [Multistore] - BO - Order page - An alert "Error! There are not enough products in stock." is displayed when updating the product quantity
#### Describe the bug

"Share available quantities to sell" option is enabled, "All shops" is selected, in the BO > Orders > Order page > when we try to update the product quantity => an alert "Error! There are not enough products in stock." but the Available quantity > 0

#### Steps to Reproduce

1. Enable Multishop Context.
2. Go to BO > Advanced Parameters > Multistore page
3. Create a new Group _`GroupA`_
image
4. Create a new shop _`ShopA`_ related to the _`GroupA`_
image
5. Create a `productA` in all shops 
6. Quantity of the `productA` in the shopA = 12
7. ShopA => create an order from the FO with the last product created (quantity ordered = 1)
8. Go to BO > Advanced Parameters > Multistore page
9. Edit the Group by default _`Default`_
10. Enable "Share available quantities to sell"
image
11. Go Back to the Order => last order created => All shops selected
12. Try to increase the quantity => you have an alert 
```php
"Error!
There are not enough products in stock."
```
But the **Available quantity > 0**
image

If you select the shopA => ok

PS: 1768: https://drive.google.com/file/d/1Q7ScfJ51BsYZWb8cMJA8pIuPeiN5H4si/view?usp=sharing => ok 

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixed UpdateProductInOrder in MultiShop
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Fixes #21987
| How to test?  | Cf. #21987

**:notebook: BC Break** : 
* `classes/module/Module.php` : the static property was in `private` : it's now in `protected`
* `src/Adapter/ContextStateManager.php` : the parameter is not a `Context` but a `PrestaShop\PrestaShop\Adapter\LegacyContext`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22228)

### CODE REVIEW

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 1]
```diff
@@ -83,6 +92,9 @@ public function handle(UpdateProductInOrderCommand $command)
                 $orderInvoice = new OrderInvoice($command->getOrderInvoiceId());
             }
 
+            // Set Context Shop
+            $this->contextStateManager->setShop(new Shop($orderDetail->id_shop));
+
```
Comment (PululuK) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Add `use Shop`

Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Fixed

**Review by PululuK — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
The fix seems fine to me, but it would definitely need some behat tests imho 👍 

You'll find multistore related feature context methods in:
 `tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php`

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 2]
```diff
@@ -172,9 +187,16 @@ private function assertProductCanBeUpdated(
...
 //        }
 
-        //check if product is available in stock
-        if (!Product::isAvailableWhenOutOfStock(StockAvailable::outOfStock($orderDetail->product_id))) {
-            $availableQuantity = StockAvailable::getQuantityAvailableByProduct($orderDetail->product_id, $orderDetail->product_attribute_id);
+        // Check if product is available in stock
+        if (!Product::isAvailableWhenOutOfStock(StockAvailable::outOfStock(
+            $orderDetail->product_id,
+            $orderDetail->id_shop
+        ))) {
```
Comment (PierreRambaud) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]:
```suggestion
        if (
            !Product::isAvailableWhenOutOfStock(
                StockAvailable::outOfStock(
                    $orderDetail->product_id,
                    $orderDetail->id_shop
                )
            )
        ) {
```

Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Thanks

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php [hunk 3]
```diff
@@ -49,19 +53,138 @@ public function shopWithNameExists(string $reference, string $shopName)
...
+    {
+        $shopGroup = new ShopGroup();
+        $shopGroup->name = $groupName;
+        $shopGroup->active = true;
+        if (!$shopGroup->add()) {
+            throw new RuntimeException(sprintf('Could not create shop group: %s', Db::getInstance()->getMsgError()));
+        }
+
+        SharedStorage::getStorage()->set($reference, $shopGroup);
+    }
```
Comment (matthieu-rolland) [inline tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:72]: I added exactly the same method in this PR [#21593](https://github.com/PrestaShop/PrestaShop/pull/21593/files#diff-f9b7ec88e6015597b47efa96260d27707f7d1cb64e95e1101c8c519939884122R88-R106) , but with color too.

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php [hunk 4]
```diff
@@ -49,19 +53,138 @@ public function shopWithNameExists(string $reference, string $shopName)
...
+
+    /**
+     * @Given /I add a shop "(.+)" with name "(.+)" for the group "(.+)"$/
+     *
+     * @param string $reference
+     * @param string $shopName
+     * @param string $shopGroupName
+     */
+    public function addShop(string $reference, string $shopName, string $shopGroupName): void
```
Comment (matthieu-rolland) [inline tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:81]: Same here, I added exactly the same method in [#21593](https://github.com/PrestaShop/PrestaShop/pull/21593/files#diff-f9b7ec88e6015597b47efa96260d27707f7d1cb64e95e1101c8c519939884122R108-R130) but with color..

I'm not sure how to deal with this situation 🤔   Maybe the last who's merged can take the other's modifications into account ? I see that you add the country, I didn't.

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 5]
```diff
@@ -83,6 +93,9 @@ public function handle(UpdateProductInOrderCommand $command)
                 $orderInvoice = new OrderInvoice($command->getOrderInvoiceId());
             }
 
+            // Set Context Shop
+            $this->contextStateManager->setShop(new Shop($orderDetail->id_shop));
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: There is something weird here, this handler didn't have the state manager because it is actually handled internally by `OrderProductQuantityUpdater` which already overrides the Shop context based on the info from `$cart->id_shop`

So there are two weird things:
- the shop should be overridden when `$this->orderProductQuantityUpdater->update` is called so it will erase the previous override from this class, therefore it should be useless here
- if there is a bug and the wrong shop was used then does it means that `$orderDetail->id_shop` is different from `$cart->id_shop` ?! this is quite worrying 😅

In the end if your fix works then I guess the override was also necessary in the previous calls before `orderProductQuantityUpdater` is used like in `updateSpecificPrice` that would explain why it fixes it

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Finally if the override shop is needed earlier then there are chances that other context entities also need it (Country, Currency, ...) I recently added some helpers in this PR https://github.com/PrestaShop/PrestaShop/pull/22246 to help doing this, you can use one of these two methods which are quite convenient:

- `AbstractOrderCommandHandler::setCartContext`
- `AbstractOrderCommandHandler::setOrderContext`

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 6]
```diff
@@ -172,9 +187,20 @@ private function assertProductCanBeUpdated(
...
 
-        //check if product is available in stock
-        if (!Product::isAvailableWhenOutOfStock(StockAvailable::outOfStock($orderDetail->product_id))) {
-            $availableQuantity = StockAvailable::getQuantityAvailableByProduct($orderDetail->product_id, $orderDetail->product_attribute_id);
+        // Check if product is available in stock
+        if (
+            !Product::isAvailableWhenOutOfStock(
+                StockAvailable::outOfStock(
+                    $orderDetail->product_id,
+                    $orderDetail->id_shop
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Oh I guess the main/real fix is here no?

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: The same check is performed in `AddProductToOrderHandler` so it should probably be fixed as well

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 7]
```diff
@@ -563,8 +563,23 @@ public function checkOrderInvoicesCount(string $orderReference, int $expectedCou
     public function editProductsToOrderWithFollowingDetails(string $productName, string $orderReference, TableNode $table)
     {
         $orderId = SharedStorage::getStorage()->get($orderReference);
-        $productOrderDetail = $this->getOrderDetailFromOrder($productName, $orderReference);
         $data = $table->getRowsHash();
+        //if (!$data['price_tax_incl']) {
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Why the commented code? It should be removed?

Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Why not using `getOrderDetailFromOrder` like before? Especially since you improved it?

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 8]
```diff
@@ -674,6 +689,14 @@ private function updateProductInOrder(int $orderId, array $productOrderDetail, a
         }
     }
 
+    /**
+     * @Then I should get no order error
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: This could probably be useful in the CommonContext no? (without the order part)

File: tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php [hunk 9]
```diff
@@ -83,13 +85,39 @@ public function before(BeforeScenarioScope $scope)
...
     /**
-     * @param $productName
+     * @param string $productName
      *
      * @return Product
      */
-    public function getProductWithName($productName)
+    public function getProduct(string $productName)
+    {
+        $idShop = (int) Context::getContext()->shop->id !== (int) Configuration::get('PS_SHOP_DEFAULT') ?
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php:94]: Mmmm, stateful tests to validate stateful crappy code ^^
What are the chances this goes wrong someday? :trollface: 

(I don't have a better/faster alternative though ^^)

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 4 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:81]: I think this one will have priority anyway since its target is 177x and yours is develop

File: tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php [hunk 10]
```diff
@@ -83,13 +85,39 @@ public function before(BeforeScenarioScope $scope)
     /* PRODUCTS */
 
     /**
-     * @param $productName
+     * @param string $productName
      *
      * @return Product
      */
-    public function getProductWithName($productName)
+    public function getProduct(string $productName)
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php]: Was it really necessary to rename this one? I'm just anticipating the potential conflicts and missing functions that may come after this one is merged, and the change of name doesn't seem to bring much value except reduce the code size in this class

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature [hunk 11]
```diff
@@ -2,6 +2,7 @@
 @reset-database-before-feature
 @clear-cache-before-feature
 @order-multi-shop
+
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature]: Is it necessary? Are the tags still correctly attached to the feature with this?

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature [hunk 12]
```diff
@@ -288,3 +289,62 @@ Feature: Order from Back Office (BO)
...
+    Then the remaining available stock for product "Product A" should be 98
+    ## 100 - 2 (in cart)
+    When I add order "order_product_a" with the following details:
+      | cart                | cart_product_A             |
+      | message             | test                       |
+      | payment module name | dummy_payment              |
+      | status              | Awaiting bank wire payment |
+    Then the remaining available stock for product "Product A" should be 96
+    And order "order_product_a" should contain 2 products "Product A"
+    ## 100 - 2 (in cart) - 2 (in order)
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature]: There's something wrong here, the 2 products in the cart are the same as the 2 products in the Order since it's the same order/cart So only 2 products should be taken out of the stock not 4

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature [hunk 13]
```diff
@@ -288,3 +289,62 @@ Feature: Order from Back Office (BO)
...
+      | State            | Alabama                            |
+      | Postal code      | 12345                              |
+    Then customer "testCustomerShop2" has address in "US" country
+    # Create Order
+    # Context : Shop 2
+    When I create an empty cart "cart_product_A" for customer "testCustomerShop2"
+    And I select "US" address as delivery and invoice address for customer "testCustomerShop2" in cart "cart_product_A"
+    And I add 2 products "Product A" to the cart "cart_product_A"
+    Then the remaining available stock for product "Product A" should be 98
+    ## 100 - 2 (in cart)
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature]: Actually as long as the cart is not ordered the stock shouldn't be updated, what you are getting back here is the "virtual stock" which uses the cart as an argument I'm not sure it's the appropriate way to test the stock here especially since you are testing order features So you shouldn't rely on the "current cart" which can be modified as soon as you create a new cart (it's adapted, or at least convenient, when testing the cart but here I don't think it's ideal)

It would be more accurate to test the real stock which is independent from the cart you'd better use this step instead:
`Then the available stock for product "Test Duplicate Product" should be 100` (from `ProductFeatureContext::actualQuantityOfProductNamedShouldBe`)

File: tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature [hunk 14]
```diff
@@ -11,6 +12,12 @@ Feature: Order from Back Office (BO)
     Given email sending is disabled
     And the current currency is "USD"
     And country "FR" is enabled
+    And the module "dummy_payment" is installed
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature]: Why did you move this? Careful I don't remember exactly why but I believe the order of these creations was very specific and all was placed in a specific order for some good reason 😅

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 4 above)
Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:81]: it makes sense 😭

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 3 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:72]: I know. I copy it for easily merge it in 178. ;)

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 4 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:81]: @matthieu-rolland Don't worry. I will rebase your PR ;)

Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:81]: ah it's ok, I'll do it 👍  i'll have to do some modifications anyway

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 3 above)
Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:72]: ah nice 👍 one problem less

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 5 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Fixed

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 8 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Fixed

File: tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php (hunk 10 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature (hunk 11 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature (hunk 13 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature]: Fixed

File: tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature (hunk 12 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_multi_shop.feature]: Fixed

File: tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php (hunk 9 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php:94]: <3

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 7 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Yes, I should remove it.

Because `getOrderDetailFromOrder` use `getProductByName` which use `SearchProductsHandler` which change the `contextStateManager->setShop`. While `OrderController::updateProductAction` push directly the information.

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 15]
```diff
@@ -58,54 +60,65 @@ final class UpdateProductInOrderHandler extends AbstractOrderHandler implements
...
     /**
      * UpdateProductInOrderHandler constructor.
      *
      * @param OrderProductQuantityUpdater $orderProductQuantityUpdater
+     * @param ContextStateManager $contextStateManager
      */
     public function __construct(
-        OrderProductQuantityUpdater $orderProductQuantityUpdater
+        OrderProductQuantityUpdater $orderProductQuantityUpdater,
+        ContextStateManager $contextStateManager
```
Comment (matks) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php:81]: Isn't this a BC break ?
We can avoid it by allowing nullable argument 😉

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php [hunk 16]
```diff
@@ -49,19 +53,138 @@ public function shopWithNameExists(string $reference, string $shopName)
...
+    {
+        $shop = new Shop();
+        $shop->active = true;
+        $shop->id_shop_group = ShopGroup::getIdByName($shopGroupName);
+        $shop->id_category = 2;
```
Comment (matks) [inline tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:87]: Could we explain this magic number? (either a constant or a comment)

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php [hunk 17]
```diff
@@ -49,19 +53,138 @@ public function shopWithNameExists(string $reference, string $shopName)
...
+     *
+     * @throws \PrestaShopException
+     */
+    private function setShopContext(int $context, int $shopId): void
+    {
+        Shop::setContext($context, $shopId);
+        Context::getContext()->shop = new Shop($shopId);
+        // Clean cache
+        Cache::clean('Shop::getCompleteListOfShopsID');
+        Cache::clean('StockAvailable::*');
```
Comment (matks) [inline tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:189]: I see so many functions dedicated to Cache, should we group them all together in some "Util class" ? We can use helper classes in Behat tests.

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 18]
```diff
@@ -1425,12 +1437,20 @@ private function getSpecificPriceId(int $productId, int $combinationId, int $ord
 
     /**
      * @param string $productName
+     * @param Order|null $order
      *
-     * @return int
+     * @return FoundProduct
      */
-    private function getProductByName(string $productName)
+    private function getProductByName(string $productName, Order $order = null)
```
Comment (matks) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]:
```suggestion
    private function getProductByNameAndOrder(string $productName, Order $order = null)
```
Would it be possible to highlight in function name the fact it's filtered by order too?
Or maybe 2 functions (`getProductByName()` and `getProductInOrderByName()`) would be better?

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 15 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php:81]: Fixed.

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 18 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Fixed

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 17 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:189]: It's not in the PR scope.

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 19]
```diff
@@ -58,54 +61,65 @@ final class UpdateProductInOrderHandler extends AbstractOrderHandler implements
...
      * @param OrderProductQuantityUpdater $orderProductQuantityUpdater
+     * @param ContextStateManager|null $contextStateManager
      */
     public function __construct(
-        OrderProductQuantityUpdater $orderProductQuantityUpdater
+        OrderProductQuantityUpdater $orderProductQuantityUpdater,
+        ContextStateManager $contextStateManager = null
     ) {
         $this->orderProductQuantityUpdater = $orderProductQuantityUpdater;
+        $this->contextStateManager = $contextStateManager ?: new ContextStateManager(Context::getContext());
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: Not a fan of manually creating this, I understand that it's to avoid a BC break but it's an an adapter class for a handler which is not at all dedicated to be extended It's even `final` so in this case (imho) the BC break is not only acceptable but recommended
@matks what do you think?

Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: But it's a recommendation from @matks :sob:

Comment (matks) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: I actually suggested this solution 😅  I thought it was an easy and inoffensive way to avoid the BC

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 20]
```diff
@@ -58,54 +61,65 @@ final class UpdateProductInOrderHandler extends AbstractOrderHandler implements
...
+        $this->assertProductNotDuplicate($order, $orderDetail, $orderInvoice);
 
-            // Update specific price if needed
-            $product = $this->getProduct(new ProductId((int) $orderDetail->product_id), (int) $order->id_lang);
-            $combination = $this->getCombination((int) $orderDetail->product_attribute_id);
+        // Update specific price if needed
+        $product = $this->getProduct(new ProductId((int) $orderDetail->product_id), (int) $order->id_lang);
+        $combination = $this->getCombination((int) $orderDetail->product_attribute_id);
 
+        $this->contextStateManager->setShop(new Shop($order->id_shop));
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]:
```suggestion
        $this->setOrderContext($contextStateManager, $order);
```

This is a recent helper added, it's safer as it overrides most of the part in the context that can go wrong (Shop, Cart, Country, Currency, ...) It is safer to override them all to avoid potential other bugs related to invalid data from context

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: As I said you should fix `AddProductToOrderHandler` while you're at it It was built with the exact same code so there are high chances that it will have the exact same bug No need to wait for QA or community to find the bug and open an issue

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php [hunk 21]
```diff
@@ -157,6 +159,39 @@ public static function cleanDatabaseHardPrepareFeature()
         require_once _PS_ROOT_DIR_ . '/config/config.inc.php';
     }
 
+    /**
+     * This hook can be used to flag a feature for database hard reset
+     *
+     * @BeforeFeature @reset-context-before-feature
+     */
+    public static function resetContextBeforeFeature()
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]: There is already a mechanism for this which is automatic in `ContextFeatureContext::resetContext()` It relies on the `ContextMocker` class I think it would be more useful to improve this class with what you need This will benefice the whole tests rather than just this specific use case

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 22]
```diff
@@ -563,9 +563,21 @@ public function checkOrderInvoicesCount(string $orderReference, int $expectedCou
     public function editProductsToOrderWithFollowingDetails(string $productName, string $orderReference, TableNode $table)
     {
         $orderId = SharedStorage::getStorage()->get($orderReference);
-        $productOrderDetail = $this->getOrderDetailFromOrder($productName, $orderReference);
         $data = $table->getRowsHash();
 
+        $order = new Order($orderId);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: What was the problem with `getOrderDetailFromOrder`? It's been used for a long time now and seemed to serve its purpose

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 23]
```diff
@@ -1561,10 +1595,11 @@ private function getOrderDetailFromOrder(
         ?string $combinationName = null,
         ?int $orderInvoiceId = null
     ): array {
-        $product = $this->getProductByName($productName);
+        $order = new Order(SharedStorage::getStorage()->get($orderReference));
+        $product = $this->getProductByNameAndOrder($productName, $order);
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: That's a good idea to use this one with the search restricted for Order it allows to validate the Search query indirectly However I don't understand why you improved this method here, but decided not to rely on it in `editProductsToOrderWithFollowingDetails`

File: tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php (hunk 16 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:87]: Fixed

Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/ShopFeatureContext.php:87]: I believe you can use `Configuration::get('PS_HOME_CATEGORY')` to be a bit more dynamic

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 19 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: @Progi1984 I know I read the history That's why I pinged him ^^ I agree that the optional parameter + manual building is sometimes useful especially for Services that are used in legacy classes, or that can be extended or used by modules

But this one just can't because of the `final` so complexifying the constructor for a potential extension use case that can't happen seems overkill and counter productive

Note: the `final` here is a good argument, but I think even some handlers that don't have it - because we forgot it - should be modifiable in the same way or else we can never fix them properly because we are afraid of BC because of a dependency that is always injected via the service DI anyway. Besides in this case manual building is easy but it's not always the case

Finally, and maybe most important, the ContextStateManager has a principle of stacking the overrides when consecutive calls are made one after another, but if another instance is used in different parts of the code they don't share this stack thus the whole stack behaviour can't work and it can cause unexpected behaviours..

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: I know you didn't have the time to work on this one again, but as I read it this modification seems even riskier to me so I prefer to block the PR for now, I'm open to discussion of course But you'll have to convince me that this has no chance of breaking the override stack mechanism from ContextStateManager ^^ (as explained in the previous comment)

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php (hunk 20 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: For more safety you should call `$this->contextStateManager->saveCurrentContext()` before setting new context overrides This is what allows the stack mechanism to work properly and avoids to mess everything up when multiple calls of `restorePreviousContext` are made.

This made me realize that `saveCurrentContext` is not called in `AbstractOrderCommandHandler::setCartContext` which is a mistake from my side!! My bad, this should be fixed to avoid any unexpected bug related to context overriding

Even though it's not strictly mandatory (it's much more important to call it in independent services like `OrderAmountUpdater`, `OrderProductQuantityUpdater`, ...) it would still be safer to use it in this method as well so that the handler classes also "protect" their overrides

**Review by jolelievre — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php [hunk 24]
```diff
@@ -83,13 +85,39 @@ public function before(BeforeScenarioScope $scope)
...
+
+        return $this->products[$productName . $idShop];
+    }
+
+    /**
+     * @param Product $product
+     */
+    private function addProduct(Product $product): void
+    {
+        $idShop = (int) Context::getContext()->shop->id !== (int) Configuration::get('PS_SHOP_DEFAULT') ?
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/ProductFeatureContext.php:105]: Maybe you should put this into a private function `getShopId()`

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php (hunk 21 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]: This improvement is still valid, it would improve the `ContextMocker` for all existing and future tests

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php [hunk 25]
```diff
@@ -195,6 +197,14 @@ public static function clearCacheAfterFeature()
         self::clearCache();
     }
 
+    /**
+     * @BeforeScenario @reset-context-before-feature
+     */
+    public static function resetContextBeforeFeature()
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]: I don't think this is necessary Since this is already handled in `ContextFeatureContext` before each scenario

But the `ContextFeatureContext` is not associated to every suite for now, only the cart one And you're dealing with the `order` suite Besides resetting context on each scenario makes sense for cart tests but not necessarily for Order

So I guess it can be useful to be able to enable this behaviour on demande thanks to a tag, however I think the current implementation misses the point compared to `ContextFeatureContext` In the original context the `ContextMocker` is initialized on `@BeforeScenario` and then reset on `@AfterScenario` Here you only setup the mocker but never reset it

So you would need to endpoints here that are related to the same tag:
- one `@BeforeScenario @reset-context-before-feature` which does the same thing as `ContextFeatureContext::mockContext`
- one `@AfterScenario @reset-context-before-feature` which resets it to avoid messing with the following tests

However you are setting the tag on the Feature level, but use a `@BeforeScenario` directive meaning the context will be reset on EACH scenario in the feature file, if you only want to mock and rest your context once per feature then you should use these instead:
- `@BeforeFeature @reset-context-before-feature`
- `@AfterFeature @reset-context-before-feature`

File: tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature [hunk 26]
```diff
@@ -1,5 +1,6 @@
 # ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s order --tags order-odd-tax
 @reset-database-before-feature
+@reset-context-before-feature
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature]: Another detail you set the tag here `@reset-context-before-feature` I guess because the context was messed up by the previous feature `order_multi_shop.feature` (I assume so because this is where you create shops and all)

Then I think it's the `order_multi_shop.feature` which should have a tag and clean after it's done This way it avoids breaking other features, and if one day we introduce a new feature that is executed between `order_multi_shop.feature` and `order_odd_tax.feature` It won't need to be added this cleaning tag

**Review by jolelievre — COMMENTED** [review]
Nice! I just added some comments about the behaviour of the cleaning tag which can be improved I think

File: tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature (hunk 26 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_odd_tax.feature]: Fixed.

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php (hunk 25 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]: Fixed.

File: src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php [hunk 27]
```diff
@@ -71,6 +71,7 @@ public function handle(UpdateCartCarrierCommand $command)
             ->setCustomer(new Customer($cart->id_customer))
             ->setShop(new Shop($cart->id_shop))
         ;
+        $this->contextStateManager->saveCurrentContext();
```
Comment (jolelievre) [inline src/Adapter/Cart/CommandHandler/UpdateCartCarrierHandler.php]: You should probably use the helper function `setCartContext` It's probably not in this `AbstractCartHandler` but it's worth adding it in the abstract I think

File: src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php [hunk 28]
```diff
@@ -92,6 +92,7 @@ public function handle(AddOrderFromBackOfficeCommand $command)
             ->setCountry($this->getTaxCountry($cart))
             ->setShop(new Shop($cart->id_shop))
         ;
+        $this->contextStateManager->saveCurrentContext();
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php]: Here you can probably use `setCartContext` or `setOrderContext`

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php [hunk 29]
```diff
@@ -195,6 +202,34 @@ public static function clearCacheAfterFeature()
         self::clearCache();
     }
 
+    /**
+     * @BeforeScenario @reset-context-before-scenario
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]:
```suggestion
     * @BeforeScenario @reset-context-after-scenario
```
This name would be more adapted I guess

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php [hunk 30]
```diff
@@ -195,6 +202,34 @@ public static function clearCacheAfterFeature()
...
+     */
+    public static function resetContextBeforeScenario()
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]:
```suggestion
    public static function mockContextBeforeScenario()
```
Same naming as in `ContextFeatureContext` which represents better what it actually does

File: tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php [hunk 31]
```diff
@@ -195,6 +202,34 @@ public static function clearCacheAfterFeature()
...
+         * the shop context thus overriding the expected value
+         */
+        $legacyContext->getContext();
+
+        self::$contextMocker = new ContextMocker();
+        self::$contextMocker->mockContext();
+    }
+
+    /**
+     * @AfterScenario @reset-context-before-scenario
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php]:
```suggestion
     * @AfterScenario @reset-context-after-scenario
```

File: src/Adapter/Cart/AbstractCartHandler.php [hunk 32]
```diff
@@ -61,4 +69,38 @@ protected function getCart(CartId $cartId)
...
+    {
+        $contextStateManager
+            ->setCart($cart)
+            ->setCustomer(new Customer($cart->id_customer))
+            ->setCurrency(new Currency($cart->id_currency))
+            ->setLanguage(new Language($cart->id_lang))
+            ->setCountry($this->getCartTaxCountry($cart))
+            ->setShop(new Shop($cart->id_shop))
+        ;
+        $contextStateManager->saveCurrentContext();
```
Comment (jolelievre) [inline src/Adapter/Cart/AbstractCartHandler.php]: `saveCurrentContext` must be called first, then use the setters

Comment (jolelievre) [reply src/Adapter/Cart/AbstractCartHandler.php]: it's a good idea to integrate the `saveCurrentContext` inside this helper function I thought it was already the case in `AbstractOrderCommandHandler` but it appears not
It would be much safer, do you think you can try adding it into `AbstractOrderCommandHandler` as well, I think it would be safer If all tests are still green If it breaks tests then nevermind it is out of scope but it's worth a try

File: src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php [hunk 33]
```diff
@@ -84,14 +79,8 @@ public function handle(AddOrderFromBackOfficeCommand $command)
...
-        $this->contextStateManager
-            ->setCart($cart)
-            ->setCurrency(new Currency($cart->id_currency))
-            ->setCustomer(new Customer($cart->id_customer))
-            ->setLanguage(new Language($cart->id_lang))
-            ->setCountry($this->getTaxCountry($cart))
-            ->setShop(new Shop($cart->id_shop))
-        ;
+        $this->setCartContext($this->contextStateManager, $cart);
+        $this->contextStateManager->saveCurrentContext();
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php]: Same here `saveCurrentContext` must be called first You can use the `OrderAmountUpdater` as an example

**Review by jolelievre — COMMENTED** [review]
I just pushed the fix for all behat tests It should be good now

**Review by matthieu-rolland — DISMISSED** [review]

File: classes/module/Module.php [hunk 34]
```diff
@@ -221,6 +221,14 @@ abstract class ModuleCore implements ModuleInterface
 
     public static $hosted_modules_blacklist = ['autoupgrade'];
 
+    public static function setContextInstanceForTesting(Context $context)
+    {
+        /** @var Module $module */
+        foreach (self::$_INSTANCE as $module) {
```
Comment (PierreRambaud) [inline classes/module/Module.php]:
```suggestion
        foreach (static::$_INSTANCE as $module) {
```

File: src/Adapter/Cart/AbstractCartHandler.php [hunk 35]
```diff
@@ -61,4 +69,38 @@ protected function getCart(CartId $cartId)
...
+     *
+     * @return Country
+     *
+     * @throws \PrestaShopDatabaseException
+     * @throws \PrestaShopException
+     */
+    protected function getCartTaxCountry(Cart $cart): Country
+    {
+        $taxAddressType = Configuration::get('PS_TAX_ADDRESS_TYPE');
+        $taxAddressId = property_exists($cart, $taxAddressType) ? $cart->{$taxAddressType} : $cart->id_address_delivery;
```
Comment (PierreRambaud) [inline src/Adapter/Cart/AbstractCartHandler.php]: Watch out with `property_exists` it doesn't check if the property is accessible.
```suggestion
        $taxAddressId = $cart->{$taxAddressType} ?? $cart->id_address_delivery;
```

File: src/Adapter/LegacyContext.php [hunk 36]
```diff
@@ -75,19 +78,18 @@ public function __construct(
      */
     public function getContext()
     {
-        static $legacyContext = null;
-
-        if (null === $legacyContext) {
+        if (null === self::$instance) {
```
Comment (PierreRambaud) [inline src/Adapter/LegacyContext.php]:
```suggestion
        if (null === static::$instance) {
```

File: src/Adapter/LegacyContext.php [hunk 37]
```diff
@@ -75,19 +78,18 @@ public function __construct(
...
             $legacyContext = Context::getContext();
 
             if ($legacyContext && !empty($legacyContext->shop) && !isset($legacyContext->controller) && isset($legacyContext->employee)) {
                 //init real legacy shop context
                 $adminController = new AdminController();
                 $adminController->initShopContext();
             }
+            self::$instance = $legacyContext;
```
Comment (PierreRambaud) [inline src/Adapter/LegacyContext.php]:
```suggestion
            static::$instance = $legacyContext;
```

File: src/Adapter/LegacyContext.php [hunk 38]
```diff
@@ -75,19 +78,18 @@ public function __construct(
...
         }
 
-        return $legacyContext;
+        return self::$instance;
```
Comment (PierreRambaud) [inline src/Adapter/LegacyContext.php]:
```suggestion
        return static::$instance;
```

File: src/Adapter/LegacyContext.php [hunk 39]
```diff
@@ -343,4 +345,13 @@ public function getAvailableLanguages()
...
         return $this->getLanguages(false);
     }
+
+    /**
+     * @param Context $testInstance
+     *                              Unit testing purpose only
+     */
+    public static function setInstanceForTesting(Context $testInstance)
+    {
+        self::$instance = $testInstance;
```
Comment (PierreRambaud) [inline src/Adapter/LegacyContext.php]:
```suggestion
        static::$instance = $testInstance;
```

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
Travis fail and I already ran it twice.

```
There were 8 errors:
1) LegacyTests\Integration\PrestaShopBundle\Controller\Admin\Improve\Design\PositionsControllerTest::testUnhooksListAction
Error: Cannot access  property Module::$cachedModuleNames
/home/travis/build/PrestaShop/PrestaShop/classes/module/Module.php:1207
/home/travis/build/PrestaShop/PrestaShop/tests-legacy/Integration/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsControllerTest.php:47
2) LegacyTests\Integration\PrestaShopBundle\Controller\Admin\Improve\Design\PositionsControllerTest::testUnhooksWithQueryAction
Error: Cannot access  property Module::$cachedModuleNames
/home/travis/build/PrestaShop/PrestaShop/classes/module/Module.php:1207
/home/travis/build/PrestaShop/PrestaShop/tests-legacy/Integration/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsControllerTest.php:47
3) LegacyTests\Integration\PrestaShopBundle\Controller\Admin\SurvivalTest::testPagesAreAvailable with data set "admin_modules_positions" ('Positions', 'admin_modules_positions')
Error: Cannot access  property Module::$cachedModuleNames
```

File: src/Adapter/LegacyContext.php [hunk 40]
```diff
@@ -343,4 +345,13 @@ public function getAvailableLanguages()
     {
         return $this->getLanguages(false);
     }
+
+    /**
+     * @param Context $testInstance
+     *                              Unit testing purpose only
+     */
+    public static function setInstanceForTesting(Context $testInstance)
```
Comment (sowbiba) [inline src/Adapter/LegacyContext.php:353]: ???? Having a method only for testing purpose is not common at all

Comment (PierreRambaud) [reply src/Adapter/LegacyContext.php:353]: He's right, setInstance should be enough. If you need it in your test, you probably did something wrong, or make it available for everyone :)

```suggestion
    public static function setInstance(Context $testInstance)
```

File: src/Adapter/ContextStateManager.php [hunk 41]
```diff
@@ -215,21 +220,29 @@ public function saveCurrentContext(): self
         return $this;
     }
 
+    /**
+     * @return array|null
```
Comment (eternoendless) [inline src/Adapter/ContextStateManager.php:227]: What does it mean when contextFieldsStack is null compared to empty array? Don't make me read the source code to understand the interface, this is what Phpdoc is for!

File: src/Adapter/ContextStateManager.php [hunk 42]
```diff
@@ -241,17 +254,30 @@ private function saveContextField(string $fieldName)
...
             if ('shop' === $fieldName) {
                 $this->restoreShopContext($currentStashIndex);
             }
-            $this->context->$fieldName = $this->contextFieldsStack[$currentStashIndex][$fieldName];
+            $this->getContext()->$fieldName = $this->contextFieldsStack[$currentStashIndex][$fieldName];
             unset($this->contextFieldsStack[$currentStashIndex][$fieldName]);
         }
     }
 
+    /**
```
Comment (eternoendless) [inline src/Adapter/ContextStateManager.php:271]: Needs description

File: src/Adapter/ContextStateManager.php [hunk 43]
```diff
@@ -57,29 +57,29 @@ final class ContextStateManager
...
      */
-    private $contextFieldsStack = [[]];
+    private $contextFieldsStack = null;
 
     /**
-     * @param Context $context
+     * @param LegacyContext $legacyContext
      */
-    public function __construct(Context $context)
+    public function __construct(LegacyContext $legacyContext)
```
Comment (eternoendless) [inline src/Adapter/ContextStateManager.php:72]: Isn't this a breaking change?

File: src/Adapter/LegacyContext.php (hunk 40 above)
Comment (Progi1984) [reply src/Adapter/LegacyContext.php:353]: That permits to keep consistance between another classes

image

File: src/Adapter/ContextStateManager.php (hunk 43 above)
Comment (Progi1984) [reply src/Adapter/ContextStateManager.php:72]: Documented.

File: src/Adapter/ContextStateManager.php (hunk 41 above)
Comment (Progi1984) [reply src/Adapter/ContextStateManager.php:227]: Documented

File: src/Adapter/ContextStateManager.php (hunk 42 above)
Comment (Progi1984) [reply src/Adapter/ContextStateManager.php:271]: Done

File: src/Adapter/LegacyContext.php (hunk 40 above)
Comment (kpodemski) [reply src/Adapter/LegacyContext.php:353]: Question is, shall we move in direction when we code to meet wrong standards, or fix them when we have possibility?

File: src/Adapter/Cart/AbstractCartHandler.php [hunk 44]
```diff
@@ -61,4 +69,38 @@ protected function getCart(CartId $cartId)
...
+
+    /**
+     * @param Cart $cart
+     *
+     * @return Country
+     *
+     * @throws \PrestaShopDatabaseException
+     * @throws \PrestaShopException
+     */
+    protected function getCartTaxCountry(Cart $cart): Country
```
Comment (kpodemski) [inline src/Adapter/Cart/AbstractCartHandler.php]: @Progi1984 

in `Cart` class there's a method doing exactly same thing, `Cart->getTaxCountry`

is there any specific reason to not use it?

File: src/Adapter/ContextStateManager.php [hunk 45]
```diff
@@ -182,7 +182,7 @@ public function setShop(Shop $shop): self
      */
     public function restorePreviousContext(): self
     {
-        $currentStashIndex = array_key_last($this->contextFieldsStack);
+        $currentStashIndex = $this->getCurrentStashIndex();
         foreach (array_keys($this->contextFieldsStack[$currentStashIndex]) as $fieldName) {
```
Comment (kpodemski) [inline src/Adapter/ContextStateManager.php]:
```suggestion
        foreach (array_keys($this->contextFieldsStack[$this->getCurrentStashIndex()]) as $fieldName) {
```

File: src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php [hunk 46]
```diff
@@ -84,14 +79,8 @@ public function handle(AddOrderFromBackOfficeCommand $command)
...
         //Context country, language and currency is used in PaymentModule::validateOrder (it should rely on cart address country instead)
-        $this->contextStateManager
-            ->setCart($cart)
-            ->setCurrency(new Currency($cart->id_currency))
-            ->setCustomer(new Customer($cart->id_customer))
-            ->setLanguage(new Language($cart->id_lang))
-            ->setCountry($this->getTaxCountry($cart))
-            ->setShop(new Shop($cart->id_shop))
-        ;
+        $this->setCartContext($this->contextStateManager, $cart);
```
Comment (kpodemski) [inline src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php:84]: `setCartContext` is triggering `saveCurrentContext()` at the beginning just to have:
`$this->contextStateManager->saveCurrentContext();`

right after it? 🤔 is this for purpose?

**Review by kpodemski — COMMENTED** [review]
few questions, overall everything seems to be done very well and behat tests are on point 💪

File: src/Adapter/Cart/AbstractCartHandler.php (hunk 44 above)
Comment (jolelievre) [reply src/Adapter/Cart/AbstractCartHandler.php]: Indeed, I think we can use `Cart::getTaxCountry`

File: src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php (hunk 46 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php:84]: You're right, there is an extra `saveCurrentContext` in this class that should be removed, `saveCurrentContext` should always be called BEFORE you override the context, so its rightful place is in the `setCartContext` function

File: src/Adapter/Cart/AbstractCartHandler.php (hunk 44 above)
Comment (Progi1984) [reply src/Adapter/Cart/AbstractCartHandler.php]: Fixed

File: src/Adapter/ContextStateManager.php (hunk 45 above)
Comment (Progi1984) [reply src/Adapter/ContextStateManager.php]: Fixed

File: src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php (hunk 46 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php:84]: Fixed

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have the same alert following these steps:
1. Enable Multishop Context.
2. Go to BO > Advanced Parameters > Multistore page
3. Create a new Group _`GroupA`_
image
4. Create a new shop _`ShopA`_ related to the _`GroupA`_
image
5. Create a `productA` in all shops 
6. Quantity of the `productA` in the shopA = 12
7. ShopA => create an order from the FO with the last product created (quantity ordered = 1)
8. Go to BO > Advanced Parameters > Multistore page
9. Edit the Group by default _`Default`_
10. Enable "Share available quantities to sell"
image
11. Go to BO > Shop Parameters > Product Settings > All shops selected > Enable `Allow ordering of out-of-stock products` 
12. Go Back to the Order => last order created => All shops selected
12. Try to increase the quantity => you have an alert 
image

Thank you!

**Review by jolelievre — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found a new issue following these steps:
1. Enable Multishop Context.
2. Go to BO > Advanced Parameters > Multistore page
3. Create a new Group _`GroupA`_
image
4. Create a new shop _`ShopA`_ related to the _`GroupA`_
image
5. Create a `productA` in all shops 
6. Create a `productB` in all shops 
6. Quantity of the `productA` in the shopA = 12 > 0
7. Quantity of the `productB` in the shopA = 12 > 0
7. ShopA => create an order from the FO with the last product created (quantity ordered = 1)
8. Go to BO > Advanced Parameters > Multistore page
9. Edit the Group by default _`Default`_
10. Enable "Share available quantities to sell"
image
11. Go Back to the Order => last order created => All shops selected
12. Try to add `productB` => you have an alert 
 ```php
"Error!
There are not enough products in stock."
```
But the **Available quantity > 0**
image


Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith It's a new bug as you add a product to an order. In the initial bug, it's an update.  So it's a new bug.

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/14W2Asr6sdO5rW_zST-wbIVe4GzfoRgnl/view?usp=sharing

Other issues created here:
1. https://github.com/PrestaShop/PrestaShop/issues/23823
2. https://github.com/PrestaShop/PrestaShop/issues/23824

Thank you!

**Review by jolelievre — CHANGES_REQUESTED** [review]
Blocked for @Progi1984 Waiting for travis to unlock

**Review by jolelievre — APPROVED** [review]
