### PR TITLE
Remove special case of Product::toggleStatus

### LINKED ISSUE #21929: When I toggle product status from search page it overrides previously set redirection options
#### Describe the bug

When I toggle product status from search page it overrides previously set redirection options, wether you enable or disable the product it uses `Product::toggleStatus`
https://github.com/PrestaShop/PrestaShop/blob/59f2ca0e1ec873195be0a3d879415c273b7d126a/classes/Product.php#L1129

This method forces the reset of the redirection options, so any configuration previously set in the product page will be erased/overridden. When you toggle the status from the product page, or from the product list it doesn't happen, it keeps the configuration set in product page just as expected?

#### Expected behavior

When I toggle the status from search list the redirect options are not modified.

#### Steps to Reproduce

1. Go to a product page edition in the BO
2. Go in the SEO tab and change its redirection options from the default ones (for example redirect to a product and select a product)
3. In the FO go to the product page which should be correctly displayed
4. Disable the product from the BO product page
5. You should copy the FO product page link as it will be useful for further tests
6. Refresh the FO product page you should be redirect to the other selected product
7. Go the the BO product list, enable the product and the disable it again
8. Check on the FO the product page is still correctly redirected to the selected product
9. Enable the product again so it is accessible in the FO
10. Now in the BO make a search in the top bar for the modified product, you should see a list which allows you to toggle the product status
11. Disable the product
12. Go to the FO and try to access the product page, you are redirect to a category page (default redirect options) which is not the expected configured behaviour
13a. Alternatively you can check in the BO product page that the redirection configuration has been modified
13b. Alternatively you can check in the database that the fields `redirect_type` and `id_type_redirected` have been modified

**Screenshots**

Configuration:

Capture d’écran 2020-11-16 à 11 38 51

#### Additional information

* PrestaShop version: develop (at least)
* PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove special case of Product::toggleStatus as it should not override the configured behaviour You will find more details in the issue, but basically the redirect options are set independently of the Product status and should not be modified when its status is changed The FO controller handles all this correctly so the problem only comes from the `Product::toggleStatus` which is only used in search list for now (and a not used yet CQRS handler)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21929
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21931)

### CODE REVIEW

File: classes/Product.php [hunk 1]
```diff
@@ -1123,26 +1123,6 @@ public function validateField($field, $value, $id_lang = null, $skip = [], $huma
         return parent::validateField($field, $value, $id_lang, $skip, $human_errors);
     }
 
-    /**
```
Comment (jolelievre) [inline classes/Product.php:1126]: I hesitate to flag this as a BC break, my guess is this was once required because the FO didn't handle the redirection independently or correctly But it is absolutely not required/useful today and it prevents from correctly setting the expected redirection behaviour

So it's definitely a bug, should we flag it as a BC in case some some developers expect this method to update those fields?

**Comment by jolelievre** [comment]
This PR is required for this migration PR https://github.com/PrestaShop/PrestaShop/pull/21550

File: classes/Product.php (hunk 1 above)
Comment (PululuK) [reply classes/Product.php:1126]: It will break https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminSearchController.php#L75 right ?

Introduced here : https://github.com/PrestaShop/PrestaShop/pull/19080/files

Comment (jolelievre) [reply classes/Product.php:1126]: No because `toggleStatus` already exist in ObjectModel, so removing this function reverts it back to the initial purpose: toggling status ^^
It doesn't modify other fields any more

**Review by Progi1984 — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

File: classes/Product.php (hunk 1 above)
Comment (matks) [reply classes/Product.php:1126]: @jolelievre I would not call this "a BC break" but rather "a notable change".
We could add a little not in "1.7.8.0 notable changes: toggling the status of product does not modify its redirection settings, this has to be done somewhere else in the code"

File: classes/Product.php [hunk 2]
```diff
@@ -1123,26 +1123,6 @@ public function validateField($field, $value, $id_lang = null, $skip = [], $huma
...
-     * {@inheritdoc}
-     */
-    public function toggleStatus()
```
Comment (zuk3975) [inline classes/Product.php:1129]: this method is used by UpdateProductStatusHandler, shouldn't you adapt its implementation?

**Comment by Robin-Fischer-PS** [comment]
Thanks @jolelievre , it's QA :heavy_check_mark: :)

**Comment by PululuK** [comment]
Thanks @jolelievre
