### PR TITLE
Fix performance issue linked to HookModuleFilter PR

### LINKED ISSUE #37913: Performance issue on BackOffice with HookModuleFilter
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

#### Initial issue

The issue lies in the method `HookCore::getHookModuleFilter()` introduced int PR https://github.com/PrestaShop/PrestaShop/pull/37125, where the system attempts to retrieve the service `PrestaShop\PrestaShop\Core\Hook\HookModuleFilter` using the following instruction:

```php
try {
    $hookModuleFilter = $serviceContainer->get(HookModuleFilter::class);
} catch (Exception $e) {
    return null;
}
```

However, in the back office, the system fails to retrieve it and throws the following exception (handled via try/catch, so it’s not visible):

```php
throw new ServiceNotFoundException($id, null, null, [], sprintf('The "%s" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.', $id));
```

#### Core issue

The `HookModuleFilter` service is not public in BackOficce (in the Symfony container), as such it cannot be retrieved via `container::get` since it's private, and we cannot inject it properly in this case since the service is inside deep inside some legacy code handling hook execution.

So besides the performance cost of this unreachable service called hundreds of times (for each hook), the other problem is that the feature of hook filtering cannot work in the BackOffice because of this (initial tests were mainly centered on the FrontOffice)

### Expected behavior

The service must be made public, the try/catch can then be simplified, if the service is not found in the future an exception should be triggered to identify the problem right away.

### Steps to reproduce

The bug was not seeable by functional QA, so manual tests should validate that the initial behaviour from https://github.com/PrestaShop/PrestaShop/discussions/37060 still works as expected.

A complementary QA by dev can be made by adding break points in the `HookCore::getHookModuleFilter` to make sure no `ServiceNotFound` exception is triggered anymore, although it there was it would be seen now since the exception is no longer caught and hidden.

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | The `HookModuleFilter` service was private, which would trigger an exception when the BO tried to reach it. (thank you @Codencode for catching this !)
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | - [Download test module](https://github.com/user-attachments/files/17958166/demodoctrine.zip)<br> - Unzip in the modules folder, install via the module manager page in back office<br>- In FO, check that the module ps_linklist doesn't display its links in the footer.<br>- (don't mind the name of the module, I took an existing example module as a basis)
| UI Tests          | https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/13012266734
| Fixed issue or discussion?     | Fixes #37913
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/37125
| Sponsor company   | PrestaShop

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @matthieu-rolland

**Review by tleon — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
cc @Codencode :)

File: classes/Hook.php [hunk 1]
```diff
@@ -1129,13 +1129,7 @@ private static function getHookModuleFilter()
...
         }
 
-        try {
-            $hookModuleFilter = $serviceContainer->get(HookModuleFilter::class);
-        } catch (Exception $e) {
-            return null;
-        }
-
-        return $hookModuleFilter;
+        return $serviceContainer->get(HookModuleFilter::class);
```
Comment (PululuK) [inline classes/Hook.php:1131]: Hello @matthieu-rolland 
This method no longer returns null, can you please update the PhpDocs in this case ? Also add `@throws ServiceNotFoundException`

**Review by PululuK — DISMISSED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @matthieu-rolland,

I tested your PR and it's good for me! :tada: 

Waiting to automated test now.

Thanks!


image

**Review by paulnoelcholot — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you everyone 🎉
