### PR TITLE
Sanitize product sort order

### LINKED ISSUE #21312: Product sort order not sanitized
#### Describe the bug

In category page, sort order can be changed in the url for an unexpected value : this generate a php notice in debug mode et an 500 error without.
Sort order has to be sanitized, it's not secure like this.

#### Expected behavior

Sort order in the url has to be sanitized.

#### Steps to Reproduce

by example, expected value in category page : 
/3-vetements?order=product.position.asc

Just remove .asc : 
/3-vetements?order=product.position.asc

You will see the php notice.

#### Additional information

* PrestaShop version: develop, 1.7.6, 1.7.7
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In category page, sort order can be changed in the url for an unexpected value : this generate a php notice in debug mode et an 500 error without. Sort order has to be sanitized, it's not secure like this.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21312.
| How to test?  | Just remove .asc in order var in category page : /3-vetements?order=product.position

Hello to Hacktoberfest

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21313)

### CODE REVIEW

File: src/Core/Product/Search/SortOrder.php [hunk 1]
```diff
@@ -120,6 +120,9 @@ public function toString()
      */
     public static function newFromString($sortOrderConfiguration)
     {
+        if (count(explode('.', $sortOrderConfiguration)) !== 3) {
+            return new static('', '', 'asc');
+        }
```
Comment (PululuK) [inline src/Core/Product/Search/SortOrder.php]:
```php
 public static function newFromString($sortOrderConfiguration)
 {
       $sortParams =  explode('.', $sortOrderConfiguration);

       if (count($sortParams) < 3) {
            return static::random();
        }

        list($entity, $field, $direction) = $sortParams;

        return new static($entity, $field, $direction);
  }
```

OR 🤔 ?

```php
public static function newFromString($sortOrderConfiguration)
{
        $sortParams = explode('.', $sortOrderConfiguration);
        return new static(
              $sortParams[0] ?? '', 
              $sortParams[1] ?? '', 
              $sortParams[2] ?? 'random'
       );
 }
```

**Review by PululuK — COMMENTED** [review]
Nice catch @jf-viguier  !
Some suggestions :

- return `random` instead of `asc` (because this case is generic ... It can happen if you remove the sort `desc` or `asc`)
- simplify the code

Something like :

File: src/Core/Product/Search/SortOrder.php (hunk 1 above)
Comment (Progi1984) [reply src/Core/Product/Search/SortOrder.php]: I prefer the first solution. It's more readable.

**Review by Progi1984 — COMMENTED** [review]
Good review @PululuK

File: src/Core/Product/Search/SortOrder.php (hunk 1 above)
Comment (jf-viguier) [reply src/Core/Product/Search/SortOrder.php]: @PululuK why returning random ? Is it the default sort order ?

Comment (jf-viguier) [reply src/Core/Product/Search/SortOrder.php]: @PululuK @Progi1984 I've commited your suggestion. Please add hacktoberfest label.

**Comment by NeOMakinG** [comment]
Travis was 🔴

**Comment by jf-viguier** [comment]
@NeOMakinG how to fix travis stuff ?

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/product-team OK with this behavior ?
> In category page, sort order can be changed in the url for an unexpected value
> If we remove .asc in order var in category page : /3-vetements?order=product.position, the sort is random.

**Comment by jf-viguier** [comment]
@Progi1984 I guess it's more a security issue than a real world issue : if someone remove one on the 3 sort order elements, it's certainly a hack attempt, WDYT ?

**Comment by LouiseBonnard** [comment]
Hi @jf-viguier, thanks for your contribution! I can understand the security part, thanks @Progi1984, I only have two questions:

1. Does this fix **only apply to category pages**? I think about the other product listings (for example, by default, the _New Products_ or the _Best Sales_ pages) that display sorting options.

2. Does it **apply to any sorting option** as long as it contains `.asc` or `.desc` in the URL?

**Comment by jf-viguier** [comment]
> Does this fix only apply to category pages? I think about the other product listings (for example, by default, the New Products or the Best Sales pages) that display sorting options.

It's for all pages : search, new products, ...

> Does it apply to any sorting option as long as it contains .asc or .desc in the URL?

No, it apply only if you remove manually .asc ou .desc in the url : this should not be done by a regular user, only by a hacker or a pen test tool.

**Comment by LouiseBonnard** [comment]
Nice, thank you for the reply, @jf-viguier!

> No, it apply only if you remove manually .asc ou .desc in the url : this should not be done by a regular user, only by a hacker or a pen test tool.

No matter what sorting option it is: product.price, product.name, product.date, product.position, etc.?

**Comment by NeOMakinG** [comment]
> @NeOMakinG how to fix travis stuff ?

I just closed and opened again, it makes travis run again (as it was not linked to your PR at all)

**Comment by jf-viguier** [comment]
> No matter what sorting option it is: product.price, product.name, product.date, product.position, etc.?

no. If sort order doesn't have the 3 required components in the url, default is used with random. It should never happen with regular user.

**Comment by jf-viguier** [comment]
@@NeOMakinG @PululuK it's ok now for travis, I just need an approve.

File: src/Core/Product/Search/SortOrder.php (hunk 1 above)
Comment (PierreRambaud) [reply src/Core/Product/Search/SortOrder.php]: The hacktoberfest label doesn't need to be added, we already tagged our repositories :wink:

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I don't understand why we should return a random SortOrder when the `$sortOrderConfiguraiton` is malformed.
Why not throw an exception like InvalidArgumentException?

**Comment by PierreRambaud** [comment]
> > No matter what sorting option it is: product.price, product.name, product.date, product.position, etc.?
> 
> no. If sort order doesn't have the 3 required components in the url, default is used with random. It should never happen with regular user.

Regarding the ProductListingFrontController and how SortOrder class is used.
The default is not random but asc: https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Product/Search/SortOrder.php#L62
and it's used here: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/ProductListingFrontController.php#L285

I don't see any "default random sorting" :thinking:

**Comment by kpodemski** [comment]
Maybe @PierreRambaud is right? maybe we shouldn't hide a real issue here, and just throw an Exception instead? This is not normal to change params in URL manually and it might look like attempt to hack default mechanisms

File: src/Core/Product/Search/SortOrder.php (hunk 1 above)
Comment (LouiseBonnard) [reply src/Core/Product/Search/SortOrder.php]: @PierreRambaud, it is what has been asked in the Build post [here](https://build.prestashop.com/news/hacktoberfest-2020-is-coming). Goal is to get an estimated number of the pull requests submitted in the context of this challenge, there is no way to have KPI on it today, cf. https://github.com/PrestaShop/prestashop-retro/issues/80.

**Comment by jf-viguier** [comment]
I've followed @PierreRambaud way and throw a PrestaShopException

**Comment by jf-viguier** [comment]
I can't understand phpstan error, please help

**Comment by matks** [comment]
> I can't understand phpstan error, please help

It seems not related to your PR 🤔

**Comment by jf-viguier** [comment]
@matks how to restart travis stuff ?

File: src/Core/Product/Search/SortOrder.php [hunk 2]
```diff
@@ -120,7 +120,13 @@ public function toString()
      */
     public static function newFromString($sortOrderConfiguration)
     {
-        list($entity, $field, $direction) = explode('.', $sortOrderConfiguration);
+        $sortParams = explode('.', $sortOrderConfiguration);
+
+        if (count($sortParams) < 3) {
+            throw new \PrestaShopException('Invalid argument');
```
Comment (PierreRambaud) [inline src/Core/Product/Search/SortOrder.php]: It should be an InvalidArgumentException or a CoreException. PrestaShopException is too generic.

Comment (jf-viguier) [reply src/Core/Product/Search/SortOrder.php]: Done with a CoreException

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @jf-viguier 

I still reproduced the issue after deleting manually the "asc" or even "desc"

Capture d’écran 2020-10-12 à 16 35 26

Thank you

**Comment by jf-viguier** [comment]
hello @ngodefroy you mean with my PR ?
What's your prestashop version ? Show me the exact url please.

**Comment by ngodefroy** [comment]
> hello @ngodefroy you mean with my PR ?
> What's your prestashop version ? Show me the exact url please.

@jf-viguier version 1.7.8.0 
Capture d’écran 2020-10-12 à 17 11 38

**Comment by jf-viguier** [comment]
@ngodefroy in my pr at line 123, there is just a {, nothing to generate the notice, it seems that you don't have my pr installed
see it here : https://github.com/PrestaShop/PrestaShop/blob/f21a3aa3534bddc0ee483e5aec1a5f043346c9b6/src/Core/Product/Search/SortOrder.php#L123

**Comment by ngodefroy** [comment]
> @ngodefroy in my pr at line 123, there is just a {, nothing to generate the notice, it seems that you don't have my pr installed
> see it here :
> 
> https://github.com/PrestaShop/PrestaShop/blob/f21a3aa3534bddc0ee483e5aec1a5f043346c9b6/src/Core/Product/Search/SortOrder.php#L123
@jf-viguier I reinstalled the PR, cleared cache and I have this now, you can't reproduce ?
Capture d’écran 2020-10-12 à 17 42 40
Thank you

**Comment by jf-viguier** [comment]
@ngodefroy it ok now, the "Invalid argument" exception is the expected behavior as suggested by @PierreRambaud

**Comment by matks** [comment]
Thank you @jf-viguier and everyone involved
