### PR TITLE
Fix compare function of dashboard's calendar

### LINKED ISSUE #22973: Dashboard stats error 1.7.7.0
Hi,

When we try to compare a date period in the dashboard stats, it's not possible to open the dropdown list to choose what we want to compare it with.

We then get the error message "The selected period is not valid".

Thanks

Screen Shot 2021-01-18 at 16 37 26
Screen Shot 2021-01-18 at 16 37 34

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | We couldn't compare periods on the dashboard because the checkbox wasn't working
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22973.
| How to test?      | Go on the dashboard and try to compare periods, you should be able to do it
| Possible impacts? | The dashboard's calendar

image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22997)

### CODE REVIEW

File: admin-dev/themes/default/js/calendar.js [hunk 1]
```diff
@@ -380,7 +380,7 @@ $( document ).ready(function() {
 	});
 
 	$('#datepicker-compare').click(function() {
-		if ($(this).attr("checked")) {
+    if ($(this).is(":checked")) {
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/calendar.js]:
```suggestion
    if ($(this).prop('checked')) {
```
Should be better, no?

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 

**Without PR**
image

**With PR**
image
https://drive.google.com/file/d/19KHLf0-5MGKZh2oke1rClUzag3CDG1F9/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @khouloudbelguith
