### PR TITLE
Fix showing price of customized products in Order Confirmation page

### LINKED ISSUE #10912: Wrong total and total_wt on order-confirmation with customization
**Describe the bug**
in the confirmation page, the total and the total_wt is wrong when we add a customization in the cart
image

**Additionnal information**
PrestaShop version: 1.7.4.2
PHP version: 7.1

In classes\Product.php
image
$product_update['total_wt'] = 13,34  * (1 - 1); -> 0
$product_update['total'] = 13,9  * (1 - 1); -> 0

In templates\checkout\_partials\order-confirmation-table.tpl
image

### PR DESCRIPTION
**Pull request by artemevsin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix showing zero price of customized product in Order Confirmation page. The bug is there for a long time. At lease since OrderLazyArray has been introduced. 
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #10912
| Related PRs       | 
| How to test?      | Add customized product to a cart (Customized mug in fresh installation) and finish the order. On Order Confirmation page there will be zero price next to customized product.
| Possible impacts? |

### CODE REVIEW

**Comment by Hlavtox** [comment]
QA team and @artemevsin - be sure to test all situations that can happen.
- Customized and non-customized product in the same cart
- One product customized with A, one product customized with B in the same cart

I don't have any bug on 1.7.6, I will test it tommorow. 🤔

**Review by Progi1984 — DISMISSED** [review]

**Comment by artemevsin** [comment]
@Hlavtox yes, I already tried situations you've described.
Product - Customizable Mug with two custom text fields - customization A (not required) and customization B (not required)
1. Order contains mug with customization A and without customization >> on Order Confirmation page mug without customization has price while mug with customization does not have price
2. Order contains mug with custom text "AAA", mug with custom text "BBB" (same customization) and mug without customization >> on Order Confirmation page mug without customization has price, but mugs with customizations (both) do not have prices
3. Order contains mug with custom text "AAA" (customization A), mug with custom text "CCC" (customization B - another text field) and mug without customization >> on Order Confirmation page mug without customization has price while two mugs with customization do not have prices

File: src/Adapter/Presenter/Order/OrderLazyArray.php [hunk 1]
```diff
@@ -179,6 +179,9 @@ public function getProducts()
 
             $productPrice = $includeTaxes ? 'product_price_wt' : 'product_price';
             $totalPrice = $includeTaxes ? 'total_wt' : 'total_price';
```
Comment (MeKeyCool) [inline src/Adapter/Presenter/Order/OrderLazyArray.php]:
```suggestion
            if (is_array($orderProduct['customizedDatas']) && count($orderProduct['customizedDatas'])) {
                $totalPrice = $includeTaxes ? 'total_customization_wt' : 'total_customization';
            } else {
                $totalPrice = $includeTaxes ? 'total_wt' : 'total_price';
            }
```

:thinking:  Don't you think it would be clearer to have if/else statement instead of default value overridden in some cases ?

Just a suggestion ^^

**Review by MeKeyCool — DISMISSED** [review]

File: src/Adapter/Presenter/Order/OrderLazyArray.php (hunk 1 above)
Comment (artemevsin) [reply src/Adapter/Presenter/Order/OrderLazyArray.php]: Yes, I see it. In this case it's definitely more clearer. Thanks :+1:

**Review by MeKeyCool — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @artemevsin 

Thanks for your PR. But, there is another [PR](https://github.com/PrestaShop/PrestaShop/pull/12422) that may fixes the same issue in our backlog  
Also, i think it should be two PRs to test in the same time, one in the `PrestaShop/Core` and another in `classic-theme` to can resolve the issue (Like introduced in the description of this PR https://github.com/PrestaShop/PrestaShop/pull/12422 )

ping @PrestaShop/prestashop-core-developers What do yout think ? 

Thank You!

**Comment by kpodemski** [comment]
Hello @HanaRebaiQA 

The PR you mention cannot get to the core before PrestaShop 9.0. Let's not block this one.

**Review by djoelleuch — APPROVED** [review]
Hello @artemevsin  ,

It's QA approved :heavy_check_mark:  
The issue is well fixed !
Automated tests --> OK 

iss2

iss21

Thank you for your PR :rocket:

**Comment by kpodemski** [comment]
Thank you, @artemevsin ! well done 👏🏻
