### PR TITLE
Override : Create directory if not exists

### LINKED ISSUE #14948: Issues with override when dir doesnt exist or when using USE statements
**Describe the bug**
If a module have overrides of controllers/front/listing these are not copies on install and not removed on uninstall.

**To Reproduce**
1. Install a module with a listing override.
2. Look in the overrides folder of Prestashop

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2.x

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Override : Create directory if not exists
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #14948
| How to test?      | * Try to install this module [dummymodule.zip](https://github.com/PrestaShop/PrestaShop/files/7122543/dummymodule.zip)<br><br>**BEFORE :** Error displayed<br>**AFTER :** The override is well added and the module is installed.<br><br>* Remove the `override/controllers/front/listing/SearchController.php` or any override installed by a module<br>* Reset the module<br><br>**BEFORE :** Errors displayed<br>**AFTER :** The reset is done and the override is well added<br /><br />* Remove the module<br>**AFTER :** The file is removed if the class is empty<br>**AFTER :** The tree of the overriden file is removed if the tree only contains `index.php` files.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25805)

### CODE REVIEW

**Comment by micka-fdz** [comment]
Hi @Progi1984, it seems folder creation doesn't work on module reset. Is it normal behaviour?

**Comment by micka-fdz** [comment]
Moreover, if we follow [this discussion](https://github.com/PrestaShop/PrestaShop/pull/25774), I think we can also remove all empty subfolders of `override/` now that folder creation is working properly. @matks @PierreRambaud do you agree with this?

Is there an issue about missing `index.php` files on these newly created folders?

File: classes/module/Module.php [hunk 1]
```diff
@@ -3161,7 +3161,8 @@ public function addOverride($classname)
             $override_dest = _PS_ROOT_DIR_ . DIRECTORY_SEPARATOR . 'override' . DIRECTORY_SEPARATOR . $path;
             $dir_name = dirname($override_dest);
 
-            if (!$orig_path && !is_dir($dir_name)) {
+            // Create directory if not exists
+            if (!is_dir($dir_name)) {
                 @mkdir($dir_name, FileSystem::DEFAULT_MODE_FOLDER);
```
Comment (PierreRambaud) [inline classes/module/Module.php]:
```suggestion
                @mkdir($dir_name, FileSystem::DEFAULT_MODE_FOLDER, true);
```

You have to allow recursion otherwise it will not work as expected :)

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Recursion is mandatory, and I agree, we can clear the override directory and remove all useless folders

**Comment by Progi1984** [comment]
@PierreRambaud @micka-fdz I have managed recursive creation, fixed when we try to reset a module and improved the test scenario.

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
@atomiix I think I have forgot to remove all useless folders... and may be add a check for `index.php` files

File: classes/Meta.php [hunk 2]
```diff
@@ -73,8 +73,13 @@ public static function getPages($excludeFilled = false, $addPage = false)
             die(Tools::displayError(Context::getContext()->getTranslator()->trans('Cannot scan root directory', [], 'Admin.Notifications.Error')));
         }
 
-        if (!$overrideFiles = Tools::scandir(_PS_CORE_DIR_ . DIRECTORY_SEPARATOR . 'override' . DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR . 'front' . DIRECTORY_SEPARATOR, 'php', '', true)) {
-            die(Tools::displayError(Context::getContext()->getTranslator()->trans('Cannot scan "override" directory', [], 'Admin.Notifications.Error')));
+        $overrideDir = _PS_CORE_DIR_ . DIRECTORY_SEPARATOR . 'override' . DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR . 'front' . DIRECTORY_SEPARATOR;
+        if (!is_dir($overrideDir)) {
+            $overrideFiles = [];
+        } else {
+            if (!$overrideFiles = Tools::scandir($overrideDir, 'php', '', true)) {
```
Comment (PierreRambaud) [inline classes/Meta.php]: Elseif maybe ? :roll_eyes:

Comment (Progi1984) [reply classes/Meta.php]: You're right

Comment (Progi1984) [reply classes/Meta.php]: Fixed

**Comment by micka-fdz** [comment]
Nice job @Progi1984 👍

File: classes/module/Module.php [hunk 3]
```diff
@@ -3224,6 +3231,22 @@ public function addOverride($classname)
         return true;
     }
 
+    private function createOverrideDirectory(string $directoryPath): void
+    {
+        // Create directory (with recurrence)
+        @mkdir($directoryPath, FileSystem::DEFAULT_MODE_FOLDER, true);
+
+        // Copy index.php to each directory
+        $directoryOverride = _PS_ROOT_DIR_ . DIRECTORY_SEPARATOR . 'override' . DIRECTORY_SEPARATOR;
```
Comment (PierreRambaud) [inline classes/module/Module.php]: duplicate from line 3167, can be something you refactor .

You're also able to use SplFileInfo object through Symfony FS, in order to be able to properly handle parent directories, it also has a better way to copy: https://github.com/symfony/filesystem/blob/4.4/Filesystem.php#L41

Comment (Progi1984) [reply classes/module/Module.php]: Fixed

**Review by PierreRambaud — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]
LGTM

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Install the dummymodule
2. check that the override is well added => ok
3. Uninstall the module 
4. The override file `SearchController.php` still exist in the path `PrestaShop/override/controllers/front/listing/` => it should be deleted I think, I tried with some other modules => ok (the override is well removed)


PS: I checked this issue: https://github.com/PrestaShop/PrestaShop/issues/11516 => fixed with this PR
I checked this issue: https://github.com/PrestaShop/PrestaShop/issues/20377 not fixed with this PR.

Thanks!

**Comment by PierreRambaud** [comment]
> Hi @Progi1984,
> 
> I have an issue following these steps:
> 
> 1. Install the dummymodule
> 2. check that the override is well added => ok
> 3. Uninstall the module
> 4. The override file `SearchController.php` still exist in the path `PrestaShop/override/controllers/front/listing/` => it should be deleted I think, I tried with some other modules => ok (the override is well removed)
> 
> PS: I checked this issue: #11516 => fixed with this PR I checked this issue: #20377 not fixed with this PR.
> 
> Thanks!

This PR should fixes #14948 only :thinking:

**Comment by khouloudbelguith** [comment]
> This PR should fixes #14948 only

@PierreRambaud yes, it is fixed but only I have an issue as described before

- Install the dummymodule
- check that the override is well added => ok
- Uninstall the module
- The override file SearchController.php still exist in the path PrestaShop/override/controllers/front/listing/ => it should be deleted I think, I tried with some other modules => ok (the override is well removed)

Thanks!

File: classes/module/Module.php [hunk 4]
```diff
@@ -3128,6 +3134,38 @@ public function addOverride($classname)
         return true;
     }
 
+    /**
+     * Create override directory and add index.php in all tree
+     *
+     * @param string $directoryOverride
+     * @param string $directoryPath
```
Comment (jolelievre) [inline classes/module/Module.php]: Maybe indicate that these parameters expect an absolute path

File: classes/module/Module.php [hunk 5]
```diff
@@ -3297,10 +3334,39 @@ public function removeOverride($classname)
             }
 
             $to_delete = preg_match('/<\?(?:php)?\s+(?:abstract|interface)?\s*?class\s+' . $classname . '\s+extends\s+' . $classname . 'Core\s*?[{]\s*?[}]/ism', $code);
+
+            if (!$to_delete) {
+                // Check if override class has remaining code
+                eval(
```
Comment (jolelievre) [inline classes/module/Module.php:3165]: Can you add some explanation on this complicated thing! 😅

```
To detect if the class has remaining code we dynamically create an class which contains the remaining code, the we use ReflectionClass to analyze what this code actually contains If no valuable code remains then we can delete it
```

Comment (jolelievre) [reply classes/module/Module.php:3165]: It would have been nice to have this kind of feature externalized in a dedicated class but it might be out of this PR's scope!

Comment (jolelievre) [reply classes/module/Module.php:3165]: Congratulations on this idea however, it's a bit ugly but yet it's smart 😅

**Review by jolelievre — COMMENTED** [review]
Thanks @Progi1984 Nice work
I just made suggestions to add comments because some part of the code are hard to understand but the code itself is fine

**Review by jolelievre — DISMISSED** [review]
Perfect @Progi1984

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Install the module dummmodule decribed in the "How to test" section
2. I checked the file `prestashop/override/controllers/front/listing/SearchController.php` is well created
3. I removed the folder `prestashop/override/controllers` manually
4. I added the access with this command `chmod 777 -R prestashop/override/`
5. In the BO > Module Manager, I tried to rest the module dummymodule
6. I have this error 
image
7. I checked the folder `prestashop/override/controllers/front/listing/` is well created but the file `SearchController.php` not created
8. I tried to rest the module for the second time => ok 

https://watch.screencastify.com/v/YajmOQGm2txhYv5Gcf7d

Thanks!

**Comment by Progi1984** [comment]
@jolelievre & @atomiix I have fixed the problem of @khouloudbelguith. Can i have a little review ?

**Review by atomiix — DISMISSED** [review]

File: classes/module/Module.php (hunk 5 above)
Comment (matks) [reply classes/module/Module.php:3165]: Agreed with @jolelievre : you made this already huge class a little bit more large 😅 

Nice-to-have: put this logic somewhere else

File: classes/module/Module.php [hunk 6]
```diff
@@ -3311,6 +3381,45 @@ public function removeOverride($classname)
         return true;
     }
 
+    /**
+     * Create override directory and add index.php in all tree
```
Comment (matks) [inline classes/module/Module.php]: Remove, not create 😛

File: classes/module/Module.php [hunk 7]
```diff
@@ -3297,10 +3335,42 @@ public function removeOverride($classname)
...
+                        [
+                            ' ',
+                            'class ' . $classname . 'OverrideOriginal_check' . $uniq . ' extends \stdClass',
+                        ],
+                        $code
+                    )
+                );
+
+                // Then we use ReflectionClass to analyze what this code actually contains
+                $override_class = new ReflectionClass($classname . 'OverrideOriginal_check' . $uniq);
```
Comment (matks) [inline classes/module/Module.php:3180]: I'm a little bit afraid of performance if we install many modules in a short amount of time... like the install process 🤔 

Would like @PierreRambaud opinion on this one

**Review by matks — COMMENTED** [review]
Please see my review I voice some worries.

Also do you think we could test the new folder movements logic you provided?

File: classes/module/Module.php (hunk 7 above)
Comment (PierreRambaud) [reply classes/module/Module.php:3180]: This one is executed only during the removal, so if we have no other choice than using the reflection that's ok

**Review by matks — COMMENTED** [review]
Do you think we could test the new folder movements logic you provided?

**Comment by Progi1984** [comment]
@matks I have tried during a complete afternoon but if was a fail. It was not really possible to test this part.

**Review by jolelievre — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Install module dummymodule1 
[dummymodule1.zip](https://github.com/PrestaShop/PrestaShop/files/7710031/dummymodule1.zip) => check on override is created in `/override/classes/Cart.php`
2. Install module dummymodule2 
[dummymodule2.zip](https://github.com/PrestaShop/PrestaShop/files/7710039/dummymodule2.zip) => check the same override `/override/classes/Cart.php`
3. See error: the overide of the first module is removed

**With PR**
https://watch.screencastify.com/v/W65GC4v9sbInrPapXwDX
**Without PR**
https://watch.screencastify.com/v/a1AxOLjBFCCjfDDpamkL

Thanks!

**Review by jolelievre — COMMENTED** [review]
Legit changes however CI is failing because of CS fixer

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by PierreRambaud — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an issue following these steps:
1. Install this module 
[dummymodule_err.zip](https://github.com/PrestaShop/PrestaShop/files/8016038/dummymodule_err.zip)
2. In the folder `/PrestaShop/override/classes/` delete the folder `webservice`
3. Reset module 
4. See error => is not possible

We should remove the folder `classes` into `PrestaShop/override/` path

https://user-images.githubusercontent.com/16067358/152811979-6102db0c-73c7-404b-ad2d-3a2784602c85.mp4

--------------------------------------------------------------------------------

1. Install this module 
[dummymodule_err.zip](https://github.com/PrestaShop/PrestaShop/files/8016038/dummymodule_err.zip)
2. Go to BO > Module manager page
3. Try to disable the module => see error

https://user-images.githubusercontent.com/16067358/152813155-4eda5706-b7bd-4416-95a3-c6ef2db89754.mp4

**Without PR** => ok

https://user-images.githubusercontent.com/16067358/152814321-a68f95db-6e72-4734-9288-bd9512782767.mp4

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith For the first issue, it is also on `develop`. It's because the attribute of the class is in multiline. The same for the second issue (same problem). So these issues are out of the scope of the PR.

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @Progi1984,

I'm sorry, but I found another behavior following these steps:
1. Install the `dummymodule` => ok
[dummymodule.zip](https://github.com/PrestaShop/PrestaShop/files/8040580/dummymodule.zip)
2. Check that the override `controllers/front/listing/SearchController.php` is well created
3. Go to BO > Advanced Parameters > Performance page
4. Enable "Disable all overrides" and save 
image
5. Go to BO > Modules > Module Manager > Search the `dummymodule`
6. Click on Disable => OK "Disable action on module dummymodule succeeded." alert well displayed
7. Check that the override `controllers/front/listing/SearchController.php` still exist
8. Go to BO > Modules > Module Manager > Enable `dummymodule`
9. See error 
image
10. Click on enable again = > OK

Same behavior if I tried to uninstall this module at the `step6` & install the  module at `step8`
I attached a screen record

https://user-images.githubusercontent.com/16067358/153403495-b41c8190-83a1-4e26-ab5c-661f0caf2942.mp4

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith Sorry, I checked but I have the same problem on `develop` branch. It's not relative to this PR.

**Review by khouloudbelguith — APPROVED** [review]
Hi @Progi1984,

Thanks a lot for your feedback.
It is ok :heavy_check_mark: 

https://user-images.githubusercontent.com/16067358/153430849-5cd0b6d3-6e3f-40e3-8922-f460c5c3c13f.mp4

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith

**Comment by alisamie97** [comment]
Hi every one. I just tried with prestashop 1.7.8.6 and failed to override a listing controller. I had to create `listing` directory in `override/controllers/front` manually and the do the override with a module. https://github.com/PrestaShop/PrestaShop/issues/14948#issuecomment-1187024709

**Comment by Adekonl** [comment]
I think these commits removed all our overrides when using the oneclickupgrade. The dirs are empty in the downloaded new version and not excluded in the delete, so override/classes/, override/modules/ override/controllers are deleted.

Relevant logs:
[2023-07-05 10:18:33] /modules/welcome ignored
[2023-07-05 10:18:33] removed dir /override/classes.
[2023-07-05 10:18:33] removed dir /override/controllers.
[2023-07-05 10:18:33] removed dir /override/modules.
