### PR TITLE
No alert displayed when changing the status with bulk action in legacy controllers

### LINKED ISSUE #21571: BO - Shipping - Carriers - No alert displayed when changing the Free shipping status or changing the status's carrier with bulk action
#### Describe the bug

In the BO > Carriers page, No alert displayed when changing the Free shipping status or changing the status's carrier with bulk action

#### Steps to Reproduce

1. Go to BO > Carriers page 
2. Try to Enable/Disable Carriers with bulk action
4. See error: No alert displayed
4. Try to Enable/disable Free Shipping => No alert displayed

**Screenshots**

https://drive.google.com/file/d/1oNNDJd8iDgY-gmjWxf8ONJEIDexpRSJp/view?usp=sharing

#### Additional information

* PrestaShop version: 1770rc1build2, 1768
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | No alert displayed when changing the status with bulk action in legacy controllers.
| Type?         | bug fix
| Category?     | BO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21571
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/21571 by @khouloudbelguith .

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21576)

### CODE REVIEW

File: classes/controller/AdminController.php [hunk 1]
```diff
@@ -4166,8 +4166,21 @@ protected function processBulkStatusSelection($status)
                 /** @var ObjectModel $object */
                 $object = new $this->className((int) $id);
                 $object->active = (int) $status;
-                $result &= $object->update();
+                $update_ok = $object->update();
+                $result &= $update_ok;
+
+                if (!$update_ok) {
```
Comment (Progi1984) [inline classes/controller/AdminController.php]:
```suggestion
                $isUpdated = $object->update();
                $result &= $isUpdated;

                if (!$isUpdated) {
```

File: classes/controller/AdminController.php [hunk 2]
```diff
@@ -4166,8 +4166,21 @@ protected function processBulkStatusSelection($status)
...
+                    $this->errors[] = $this->trans('Can\'t update #%id% status', ['%id%' => (int) $id], 'Admin.Notifications.Error');
+                }
             }
+
+            if ($result) {
+                $this->redirect_after = self::$currentIndex . '&conf=5&token=' . $this->token;
+            }
+
+            $this->errors[] = $this->trans('An error occurred while updating the status.', [], 'Admin.Notifications.Error');
```
Comment (Progi1984) [inline classes/controller/AdminController.php]: If it's good, we have this error ?

File: classes/controller/AdminController.php [hunk 3]
```diff
@@ -4166,8 +4166,21 @@ protected function processBulkStatusSelection($status)
                 /** @var ObjectModel $object */
                 $object = new $this->className((int) $id);
                 $object->active = (int) $status;
-                $result &= $object->update();
+                $update_ok = $object->update();
```
Comment (PierreRambaud) [inline classes/controller/AdminController.php]:
```suggestion
                $update_ok = (bool) $object->update();
```

It currently returns an integer :(

File: classes/controller/AdminController.php (hunk 2 above)
Comment (PululuK) [reply classes/controller/AdminController.php]: Hi @Progi1984  I found it here : https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController.php#L642

Ping @LouiseBonnard

File: classes/controller/AdminController.php (hunk 1 above)
Comment (PululuK) [reply classes/controller/AdminController.php]: Thanks ! done

File: classes/controller/AdminController.php (hunk 3 above)
Comment (PululuK) [reply classes/controller/AdminController.php]: Yep ! thanks

File: classes/controller/AdminController.php (hunk 2 above)
Comment (LouiseBonnard) [reply classes/controller/AdminController.php]: Yep, it exists!

Comment (PululuK) [reply classes/controller/AdminController.php]: Thank you @LouiseBonnard  ! you can validate the wording now please

Comment (LouiseBonnard) [reply classes/controller/AdminController.php]: @Julievrz is now in charge of the wording reviews, she will check it as soon as she can. :-)

Comment (PululuK) [reply classes/controller/AdminController.php]: Oh Sorry @LouiseBonnard

Comment (Progi1984) [reply classes/controller/AdminController.php]: No. I talk about the behavior ! I would add error in `else` for the `if $result`.

File: classes/controller/AdminController.php [hunk 4]
```diff
@@ -4166,8 +4166,21 @@ protected function processBulkStatusSelection($status)
...
+                }
             }
+
+            if ($result) {
+                $this->redirect_after = self::$currentIndex . '&conf=5&token=' . $this->token;
+            }
+
+            $this->errors[] = $this->trans('An error occurred while updating the status.', [], 'Admin.Notifications.Error');
+        } else {
+            $this->errors[] = $this->trans('You must select at least one element to perform a bulk action.', [], 'Admin.Notifications.Error');
```
Comment (Julievrz) [inline classes/controller/AdminController.php]:
```suggestion
            $this->errors[] = $this->trans('You need to select at least one item to use the bulk action.', [], 'Admin.Notifications.Error');
```

I changed the wording to try to stay consistent with the existing one. :)

File: classes/controller/AdminController.php [hunk 5]
```diff
@@ -4166,8 +4166,21 @@ protected function processBulkStatusSelection($status)
                 /** @var ObjectModel $object */
                 $object = new $this->className((int) $id);
                 $object->active = (int) $status;
-                $result &= $object->update();
+                $isUpdated = (bool) $object->update();
+                $result &= $isUpdated;
+
+                if (!$isUpdated) {
+                    $this->errors[] = $this->trans('Can\'t update #%id% status', ['%id%' => (int) $id], 'Admin.Notifications.Error');
```
Comment (Julievrz) [inline classes/controller/AdminController.php:4183]:
```suggestion
                    $this->errors[] = $this->trans('#%id% status cannot be updated.' => (int) $id], 'Admin.Notifications.Error');
```

It would be better to tell the user why it can't be updated and how to solve the issue. Could you tell me more about it so I can come up with a new wording?

File: classes/controller/AdminController.php (hunk 2 above)
Comment (PululuK) [reply classes/controller/AdminController.php]: Well seen! Thank you @Progi1984

File: classes/controller/AdminController.php (hunk 4 above)
Comment (PululuK) [reply classes/controller/AdminController.php]: Done ! Thanks @Julievrz

File: classes/controller/AdminController.php (hunk 5 above)
Comment (PululuK) [reply classes/controller/AdminController.php:4183]: Hi @Julievrz  This message is sent when the reason is unknown ... When the reason is known the message is managed in another place.
Here is an example when I try to change the status of an invalid carrier:
image

Comment (Julievrz) [reply classes/controller/AdminController.php:4183]: Thank you @PululuK 

@LouiseBonnard What should we do in that case? Should we keep "#%id% status cannot be updated." ?

Comment (LouiseBonnard) [reply classes/controller/AdminController.php:4183]: It suits me fine!

**Comment by sowbiba** [comment]
I have a doubt about the meaning of the issue. Reading it, I understood that @khouloudbelguith ask for a confirm modal. No ?

EDIT : Whatever the answer your modification is good :smiley:

**Comment by PululuK** [comment]
> I have a doubt about the meaning of the issue. Reading it, I understood that @khouloudbelguith ask for a confirm modal. No ?
> 
> EDIT : Whatever the answer your modification is good smiley

Hello @sowbiba 

@khouloudbelguith  talks about legacy alerts

image


Thanks

File: classes/controller/AdminController.php (hunk 5 above)
Comment (PululuK) [reply classes/controller/AdminController.php:4183]: @Julievrz  if it is ok for you you can remove `waiting for wording` label please ? Thanks !

**Review by sowbiba — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
Seems good to me, let's wait for the wording review :+1:

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @PululuK 

As the issue fixed by your PR isn't a regression of the 1.7.7, could you please rebase your PR on develop branch ?

**Comment by PululuK** [comment]
> Hello @PululuK
> 
> As the issue fixed by your PR isn't a regression of the 1.7.7, could you please rebase your PR on develop branch ?

Done !

**Comment by PululuK** [comment]
ping @Progi1984 @matthieu-rolland

**Comment by jolelievre** [comment]
Hi @PululuK thanks for changing the target branch, but you also need to rebase your PR based on develop
So that you get the latests modifs (including the new CI features)

**Comment by PululuK** [comment]
> Hi @PululuK thanks for changing the target branch, but you also need to rebase your PR based on develop
> So that you get the latests modifs (including the new CI features)

Hi @jolelievre, yep ! Done

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Roomsmaniia** [comment]
hi @PululuK,
I still have the error on #21847, when i want to enable or disable an user, i see no changing
image

**Comment by PululuK** [comment]
> hi @PululuK,
> I still have the error on #21847, when i want to enable or disable an user, i see no changing
> image



Hi @RomainBocheux 

I was wrong, this PR fix only https://github.com/PrestaShop/PrestaShop/issues/21571
I will open another PR to fix https://github.com/PrestaShop/PrestaShop/issues/21847

Thanks

**Comment by Roomsmaniia** [comment]
LGTM,

Thanks @PululuK

**Comment by PululuK** [comment]
Thanks @PululuK
