### PR TITLE
Fix exception when deleting address from customer view

### LINKED ISSUE #18748: BO - Customer View page - An exception is displayed when deleting an address
#### Describe the bug

In the BO => Customers => Customer view page, when we try to delete an address, an exception is displayed.

#### Expected behavior

It should delete the address successfully.

#### Steps to Reproduce

1. Go to BO => Customers => Customer view page or example "John DOE"
2. Try to delete an address
3. See error

**Screenshots**

image

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fix exception displayed when an address is deleted from customer view
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18748
| How to test?  | 1. Go to BO => Customers => Customer view page or example "John DOE"<br>2. Try to delete an address<br>3. You don't see any error but the delete success alert

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18764)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

File: admin-dev/themes/new-theme/js/components/form-submit-button.js [hunk 1]
```diff
@@ -60,11 +60,32 @@ export default class FormSubmitButton {
         return;
       }
 
+      let method = 'POST';
+      let addInput = null;
+
+      if ($btn.data('method')) {
+        const btnMethod = $btn.data('method');
+        const isGetOrPostMethod = ['GET', 'POST'].includes(btnMethod);
+        method = isGetOrPostMethod ? method : 'POST';
```
Comment (matthieu-rolland) [inline admin-dev/themes/new-theme/js/components/form-submit-button.js:69]: It seems like the value of the **method** variable can only be 'POST'. Or is there something I don't get ?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig [hunk 2]
```diff
@@ -92,12 +92,15 @@
                     ></a>
 
                     <div class="dropdown-menu dropdown-menu-right">
-                      <a class="btn tooltip-link dropdown-item"
-                         href="{{ getAdminLink('AdminAddresses', true, {'id_address': address.addressId, 'deleteaddress': 1, 'back': app.request.uri}) }}"
+                      <button type="button"
+                              class="btn tooltip-link dropdown-item js-form-submit-btn"
+                              data-form-confirm-message="{{ 'Are you sure you want to delete the selected item(s)?'|trans({}, 'Admin.Global') }}"
+                              data-form-submit-url="{{ getAdminLink('AdminAddresses', true, {'id_address': address.addressId, 'deleteaddress': 1, 'back': app.request.uri}) }}"
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: You can use the symfony route on this one now `admin_addresses_delete`

File: admin-dev/themes/new-theme/js/components/form-submit-button.js (hunk 1 above)
Comment (matthieu-rolland) [inline admin-dev/themes/new-theme/js/components/form-submit-button.js]: It seems like the value of the **method** variable can only be 'POST'. Or is there something I don't get ?
Maybe you wanted to write:
```suggestion
        method = isGetOrPostMethod ? btnMethod : 'POST';
```

**Review by matthieu-rolland — COMMENTED** [review]
Just one feedback..

File: admin-dev/themes/new-theme/js/components/form-submit-button.js [hunk 3]
```diff
@@ -60,11 +60,32 @@ export default class FormSubmitButton {
         return;
       }
 
+      let method = 'POST';
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/components/form-submit-button.js:65]: Great addition to this component!! Can you update the JSDoc on the class and add the new `data-method` parameter please?

File: admin-dev/themes/new-theme/js/components/form-submit-button.js (hunk 1 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/components/form-submit-button.js]: No it can be GET or POST, and for other methods (HEAD, DELETE) an hidden input is added and the http method used is POST

Comment (matthieu-rolland) [reply admin-dev/themes/new-theme/js/components/form-submit-button.js]: yes but the **method** variable is set to 'POST' and never changed after...  I think he meant to use the value of **btnMethod** instead. 🤔

Comment (sowbiba) [reply admin-dev/themes/new-theme/js/components/form-submit-button.js]: If the method is something else than GET or POST, POST will be set as verb and the hidden input will do the job to make the request with the correct verb

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig [hunk 4]
```diff
@@ -92,12 +92,15 @@
                     ></a>
 
                     <div class="dropdown-menu dropdown-menu-right">
-                      <a class="btn tooltip-link dropdown-item"
-                         href="{{ getAdminLink('AdminAddresses', true, {'id_address': address.addressId, 'deleteaddress': 1, 'back': app.request.uri}) }}"
+                      <button type="button"
+                              class="btn tooltip-link dropdown-item js-form-submit-btn"
+                              data-form-confirm-message="{{ 'Are you sure you want to delete the selected item(s)?'|trans({}, 'Admin.Global') }}"
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: Currently, there are two exceptions on this page: one when deleting one row (_Delete selected item?_) and another when deleting in bulk (_Delete selected items?_). Which exception does this PR fix? Or is it a 2-in-1 exception that would work for both cases?

Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: this confirm message I updated is for single row deletion

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: Okay, thanks @sowbiba! In this case, I'd keep it consistent with the other exception (the bulk action exception) and write _Delete selected item?_, localized in _Admin.Notifications.Warning_. It is not a deletion modal because the page has not been migrated in Symfony yet, right?

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php [hunk 5]
```diff
@@ -144,6 +144,11 @@ public function deleteAction(int $addressId): RedirectResponse
             $this->addFlash('error', $this->getErrorMessageForException($e, $this->getErrorMessages($e)));
         }
 
+        $redirectUrl = $request->query->get('redirectUrl');
```
Comment (sowbiba) [inline src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: Maybe I can do it like 

```return $request->query->has('redirectUrl') ? $this->redirect($request->query->get('redirectUrl')) : $this->redirectToRoute('admin_addresses_index');```

WDYT ?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig (hunk 4 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: didn't want to introduice this subject :joy:  but yes, this should be a modal, not a simple confirm box

Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: And in the other modals for deletion we did, the confirm message was "{{ 'Are you sure you want to delete the selected item(s)?'|trans({}, 'Admin.Global') }}"
That's why I choosed this wording

Comment (LouiseBonnard) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: I know, and you're right about it. But since the bug is about a confirm box, we should keep the behavior iso, at least for now, and turn these two confirm boxes into one modal when the page will be migrated.

File: src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php (hunk 5 above)
Comment (matthieu-rolland) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: It seems fine to me.

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: I don't see any problem with that

Comment (Progi1984) [reply src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController.php]: And me

**Review by matthieu-rolland — APPROVED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig (hunk 4 above)
Comment (LouiseBonnard) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: Actually, the page is migrated for 1.7.7 and I've just come across this PR, https://github.com/PrestaShop/PrestaShop/pull/18464, so I guess it should definitely be a modal here. It looks like @marionf is the owner of this topic, can you confirm?

**Review by Progi1984 — APPROVED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig (hunk 4 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: The PR #18464 is for bulk action

https://github.com/PrestaShop/PrestaShop/issues/17847 :thinking:

**Review by matks — APPROVED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig (hunk 4 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: We keep the classic confirm for this PR. The modal will be done in another PR, for 1.7.8

**Review by LouiseBonnard — APPROVED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig (hunk 4 above)
Comment (Progi1984) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/View/addresses.html.twig]: :+1:
