### PR TITLE
Fix upgrade from ps < 1.7.0.0

### LINKED ISSUE #22237: Upgrade 1.6.1.24 => 1.7.7.0 fails ; XmlLoader Call to a member function trans() on null
#### Describe the bug

Bug found by @SD1982 

```
[INTERNAL] /var/www/html/builds/1.6.1.24/src/PrestaShopBundle/Install/XmlLoader.php line 467 - Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function trans() on null #0 /var/www/html/builds/1.6.1.24/src/PrestaShopBundle/Install/XmlLoader.php(347): PrestaShopBundle\Install\XmlLoader->flushDelayedInserts() 
#1 /var/www/html/builds/1.6.1.24/src/PrestaShopBundle/Install/Install.php(476): PrestaShopBundle\Install\XmlLoader->populateEntity('tab') 
#2 /var/www/html/builds/1.6.1.24/admin8932wiobg/autoupgrade/latest/install/upgrade/php/migrate_tabs_17.php(63): PrestaShopBundle\Install\Install->populateDatabase('tab') 
#3 [internal function]: migrate_tabs_17() 
#4 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(395): call_user_func_array('migrate_tabs_17', Array) 
#5 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(360): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.0.0', '/* PHP:migrate_...') 
#6 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(284): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.0.0', '/* PHP:migrate_...') 
#7 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(55): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.6.1.24') 
#8 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(101): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.6.1.24') 
#9 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#10 /var/www/html/builds/1.6.1.24/admin8932wiobg/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#11 {main}
```

#### Expected behavior

Upgrade should work flawlessly

#### Steps to Reproduce

1. Install PS 1.6.1.24 and module autoupgrade
2. Run upgrade to PS 1.7.7.0
3. See error

* PHP version: 7.1

### LINKED ISSUE #22294: In autoupgrade process, Doctrine schema update process is performed after scripts which create inconsistent behavior
#### Describe the bug

Module autoupgrade [CoreUpgrader17:: upgradeDb()](https://github.com/PrestaShop/autoupgrade/blob/v4.11.0/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php#L53)
```
    protected function upgradeDb($oldversion)
    {
        parent::upgradeDb($oldversion);

        $commandResult = $this->container->getSymfonyAdapter()->runSchemaUpgradeCommand();
        if (0 !== $commandResult['exitCode']) {
            throw (new UpgradeException($this->container->getTranslator()->trans('Error upgrading Doctrine schema', array(), 'Modules.Autoupgrade.Admin')))
                ->setQuickInfos(explode("\n", $commandResult['output']));
        }
    }
```

`runSchemaUpgradeCommand()` relies on Doctrine `prestashop:schema:update` (which is a very bad idea).

## An issue about which is first

If we wait for `runSchemaUpgradeCommand()` to create some columns, __these columns cannot be modified by scripts run in__ `parent::upgradeDb($oldversion);`! **Any column that is being managed by Doctrine cannot be modified in our scripts!**

## It fails for < 1.7.5 to 1.7.7

When I run autoupgrade CLI from PS 1.7.5 to PS 1.7.7 I have this
```
WARNING - 
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.7.0
            1054 in UPDATE `ps_admin_filter` SET `filter_id` = SUBSTRING(`filter_id`, 1, 191): Unknown column 'filter_id' in 'field list'</div>

WARNING - 
            <div class="upgradeDbError">
            [WARNING] SQL 1.7.7.0
            1054 in ALTER TABLE `ps_admin_filter` CHANGE `filter_id` `filter_id` VARCHAR(191) NOT NULL: Unknown column 'filter_id' in 'ps_admin_filter'</div>
```

This is because column `filter_id` is created by Doctrine so it cannot be modified by the SQL scripts before.

#### Steps to Reproduce

1. Install PS 1.7.5
2. Run CLI autoupgrade
3. See warnings like https://travis-ci.com/github/matks/autoupgrade/jobs/451118636

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Because the table `ps_tab` has been changed on 1.7.7.x, when executing the 1.7.0.0 upgrade script, tabs weren't properly updated. The other issue was that because of a previous upgrade script, the `Language` class had cache that wasn't up-to-date with the new database structure leading to an SQL update error. This PR fixes both bugs.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22237 #22294
| How to test?  | Try to upgrade a shop from PrestaShop < 1.7.0.0 (1.6.1.24) to 1.7.7.0, the upgrade process should finish without any error.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22274)

### CODE REVIEW

**Comment by matks** [comment]
@atomiix Could it also fix https://github.com/PrestaShop/PrestaShop/issues/22250 ?

**Comment by atomiix** [comment]
@matks I don't think so as #22250 happens from 1.7.6.9 while I'm doing some changes for version < 1.7.0.0

**Comment by matks** [comment]
If I understand correctly,

For PS 1.6 => PS 1.7.6 we have a different structure for tabs (between PS 1.6 and PS 1.7) and the script correctly migrates it
But for PS 1.6 => PS 1.7.7, the file structure is "immediately" migrated to 177 version so the script fails because it expects the old structure

So we have a different script for ps1.6 => ps1.7.6 and ps1.6 => ps1.7.7 ?

**Comment by atomiix** [comment]
That's the opposite, when upgrading from PS 1.6 to PS 1.7.7, the upgrade script uses core files that expect the new DB structure.

File: install-dev/upgrade/php/migrate_tabs_17.php [hunk 1]
```diff
@@ -59,12 +60,46 @@ function migrate_tabs_17()
...
+    }
+
+    $xml_loader = new \XmlLoader1700();
+    $xml_loader->setTranslator(Context::getContext()->getTranslator());
+    $xml_loader->setLanguages($languages);
+
+    try {
+        $xml_loader->populateEntity('tab');
+    } catch (PrestashopInstallerException $e) {
+        return false;
```
Comment (matks) [inline install-dev/upgrade/php/migrate_tabs_17.php:92]: Should we "silence" this error or should we make it crash the process loudly?

**Review by matks — DISMISSED** [review]
Code seems OK for me. QA team can validate 1.6 => 1.7 upgrade and [automated tests](https://github.com/PrestaShop/autoupgrade/pull/373) can validate the other paths

File: install-dev/upgrade/php/migrate_tabs_17.php (hunk 1 above)
Comment (atomiix) [reply install-dev/upgrade/php/migrate_tabs_17.php:92]: The way it is now, it will return an error in the logs (it wasn't the case before). I don't think we need to do more 😄

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @atomiix The original error is not displayed but I have this error now 
I don't know if it's related with your PR because I can really test without 
image

`[INTERNAL] /var/www/html/builds/1.6.1.24/app/AppKernel.php line 39 - ParseError: syntax error, unexpected ';' #0 /var/www/html/builds/1.6.1.24/modules/autoupgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/b...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('AppKernel') #2 /var/www/html/builds/1.6.1.24/config/autoload.php(28): spl_autoload_call('AppKernel') #3 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/UpgradeContainer.php(545): require_once('/var/www/html/b...') #4 /var/www/html/builds/1.6.1.24/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(73): PrestaShop\Module\AutoUpgrade\UpgradeContainer->initPrestaShopAutoloader() #5 /var/www/html/builds/1.6.1.24/admin762k5hk9q/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->init() #6 {main}`

Tested on php7.1 and mysql 5.7

File: install-dev/upgrade/php/migrate_tabs_17.php [hunk 2]
```diff
@@ -59,12 +60,46 @@ function migrate_tabs_17()
...
+    }
+
+    return true;
+}
+
+class XmlLoader1700 extends XmlLoader
+{
+    public function createEntityTab($identifier, array $data, array $data_lang): void
```
Comment (Progi1984) [inline install-dev/upgrade/php/migrate_tabs_17.php:100]:
```suggestion
    public function createEntityTab($identifier, array $data, array $data_lang)
```

**Comment by SD1982** [comment]
Hi @atomiix As we have seen together there is now this error which is displayed:
image

`SQL 1.7.7.0 1146 in UPDATE `ps_admin_filter` SET `filter_id` = SUBSTRING(`filter_id`, 1, 191): Table 'prestashop-161.ps_admin_filter' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_admin_filter` CHANGE `filter_id` `filter_id` VARCHAR(191) NOT NULL: Table 'prestashop-161.ps_admin_filter' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_admin_filter` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'prestashop-161.ps_admin_filter' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_link_block` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'prestashop-161.ps_link_block' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_link_block_lang` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'prestashop-161.ps_link_block_lang' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_link_block_shop` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'prestashop-161.ps_link_block_shop' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_module_history` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'prestashop-161.ps_module_history' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_translation` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'prestashop-161.ps_translation' doesn't exist`

File: install-dev/upgrade/php/migrate_tabs_17.php (hunk 2 above)
Comment (atomiix) [reply install-dev/upgrade/php/migrate_tabs_17.php:100]: That's an override, not sure we should change the signature here.

File: install-dev/upgrade/php/ps_1770_update_charset.php [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+function ps_1770_update_charset()
+{
+    $adminFilterTableExists = false;
+    $adminFilterFilterIdExists = false;
+    $moduleHistoryTableExists = false;
+    $translationTableExists = false;
```
Comment (Progi1984) [inline install-dev/upgrade/php/ps_1770_update_charset.php]:
```suggestion
    $adminFilterTableExists = $adminFilterFilterIdExists = $moduleHistoryTableExists = $translationTableExists = false;
```

File: install-dev/upgrade/php/ps_1770_update_charset.php [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+            $adminFilterFilterIdExists = Db::getInstance()->executeS(
+                'SELECT count(filter_id) FROM ' . _DB_PREFIX_ . 'admin_filter'
+            );
+        }
+        $moduleHistoryTableExists = Db::getInstance()->executeS(
+            'SELECT count(*) FROM ' . _DB_PREFIX_ . 'module_history'
+        );
+        $translationTableExists = Db::getInstance()->executeS(
+            'SELECT count(*) FROM ' . _DB_PREFIX_ . 'translation'
+        );
```
Comment (Progi1984) [inline install-dev/upgrade/php/ps_1770_update_charset.php]:
```suggestion
        $adminFilterTableExists = (bool) Db::getInstance()->executeS(
            'SELECT count(*) FROM ' . _DB_PREFIX_ . 'admin_filter'
        );
        if ($adminFilterTableExists) {
            $adminFilterFilterIdExists = (bool) Db::getInstance()->executeS(
                'SELECT count(filter_id) FROM ' . _DB_PREFIX_ . 'admin_filter'
            );
        }
        $moduleHistoryTableExists = (bool) Db::getInstance()->executeS(
            'SELECT count(*) FROM ' . _DB_PREFIX_ . 'module_history'
        );
        $translationTableExists = (bool) Db::getInstance()->executeS(
            'SELECT count(*) FROM ' . _DB_PREFIX_ . 'translation'
        );
```

File: install-dev/upgrade/php/ps_1770_update_charset.php [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+    }
+
+
+    if ($translationTableExists) {
+        $result &= Db::getInstance()->execute(
+            'ALTER TABLE `PREFIX_translation` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci'
+        );
+    }
+
+    return $result;
```
Comment (Progi1984) [inline install-dev/upgrade/php/ps_1770_update_charset.php]:
```suggestion
    return (bool) $result;
```

**Review by Progi1984 — COMMENTED** [review]
Some feedback

**Review by Progi1984 — DISMISSED** [review]

File: install-dev/upgrade/php/migrate_tabs_17.php [hunk 6]
```diff
@@ -59,12 +60,46 @@ function migrate_tabs_17()
...
         Db::getInstance()->execute('UPDATE '._DB_PREFIX_.'tab SET id_parent='.(int)$idTab.' WHERE id_parent='.(int)$idParent);
     }
+
+    return true;
+}
+
+function populateTab()
+{
+    $languages = [];
+    foreach (Language::getLanguages() as $lang) {
```
Comment (PierreRambaud) [inline install-dev/upgrade/php/migrate_tabs_17.php:79]: You should use LanguageCore instead like on line 61

File: install-dev/upgrade/php/add_new_status_stock.php [hunk 7]
```diff
@@ -26,6 +26,7 @@
 
 function add_new_status_stock()
 {
+    Language::resetCache();
```
Comment (PierreRambaud) [inline install-dev/upgrade/php/add_new_status_stock.php:29]: You should use LanguageCore instead like in migrate_tabs_17.php

File: install-dev/upgrade/php/migrate_tabs_17.php (hunk 6 above)
Comment (PierreRambaud) [inline install-dev/upgrade/php/migrate_tabs_17.php:79]: I don't know why they used LanguageCore, and sometimes Language :sweat_smile:

File: install-dev/upgrade/php/migrate_tabs_17.php (hunk 2 above)
Comment (jolelievre) [reply install-dev/upgrade/php/migrate_tabs_17.php:100]: Agreed!

File: install-dev/upgrade/php/ps_1770_update_charset.php [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+    try {
+        $adminFilterTableExists = (bool) Db::getInstance()->executeS(
+            'SELECT count(*) FROM ' . _DB_PREFIX_ . 'admin_filter'
+        );
+        if ($adminFilterTableExists) {
+            $adminFilterFilterIdExists = (bool) Db::getInstance()->executeS(
+                'SELECT count(filter_id) FROM ' . _DB_PREFIX_ . 'admin_filter'
+            );
+        }
+        $moduleHistoryTableExists = (bool) Db::getInstance()->executeS(
```
Comment (jolelievre) [inline install-dev/upgrade/php/ps_1770_update_charset.php:45]: The checks on each table should be performed separately (different try/catch blocks) because let's say the first check on `admin_filter` fails because the table doesn't exist Then the following checks won't be performed and `module_history` and `translation` will be considered non existent

File: install-dev/upgrade/php/migrate_tabs_17.php [hunk 9]
```diff
@@ -59,12 +60,46 @@ function migrate_tabs_17()
...
+        $languages[$lang['id_lang']] = $lang['iso_code'];
+    }
+
+    $xml_loader = new \XmlLoader1700();
```
Comment (jolelievre) [inline install-dev/upgrade/php/migrate_tabs_17.php:85]: A little comment explaining why you needed a custom XmlLoader that overrides the initial one here would be nice

**Review by Progi1984 — APPROVED** [review]

File: install-dev/upgrade/php/ps_1770_update_charset.php [hunk 10]
```diff
@@ -0,0 +1,91 @@
...
+            $adminFilterFilterIdExists = (bool) Db::getInstance()->executeS(
+                'SELECT count(filter_id) FROM ' . _DB_PREFIX_ . 'admin_filter'
+            );
+        }
+    } catch (Exception $e) {
+
+    }
+
+    try {
+        $moduleHistoryTableExists = (bool) Db::getInstance()->executeS(
```
Comment (jolelievre) [inline install-dev/upgrade/php/ps_1770_update_charset.php:45]: I'm not sure but what if the code fail? is it possible that the `$moduleHistoryTableExists` variable will not be initialized? The the following code could fail because of an undefined variable

So maybe in the next code you should check `if (isset($moduleHistoryTableExists) && $moduleHistoryTableExists)` Or define the variable `$moduleHistoryTableExists = false;` before the try/catch block?

**Review by jolelievre — APPROVED** [review]
Not sure about the last comment so I still approve I let you judge if the modif is required or not

File: install-dev/upgrade/php/ps_1770_update_charset.php (hunk 10 above)
Comment (atomiix) [reply install-dev/upgrade/php/ps_1770_update_charset.php:45]: It's defined before: https://github.com/PrestaShop/PrestaShop/pull/22274/files#diff-e02480de244d3b5fdbd2e8354f049d52b6602b5ec711b7608d2e0dbf4bea0929R29

**Comment by SD1982** [comment]
LGTM now !! No errors displayed during the upgrade process !!
upgraded from 1.6.1.24 
php 7.1
mysql 5.7
Thanks @atomiix !!

**Comment by gyan111** [comment]
When will this available on autoupgrade?

**Comment by matks** [comment]
@gyan111 This PR has been milestoned for PS 1.7.7.1 which is scheduled for [mid January 2021](https://github.com/PrestaShop/PrestaShop/issues/22306) or late January 2021.

**Comment by mbautista** [comment]
Hello,
I try to upgrade from PS 1.6.0.11 to PS 1.7.8.5 and I have this error :
```
# /usr/bin/php7.1 install/upgrade/upgrade.php
PHP Warning:  Invalid argument supplied for foreach() in /***/classes/Profile.php on line 251
PHP Fatal error:  Uncaught PrestaShopObjectNotFoundException: The hook id #0 does not exist in database in /***/classes/Hook.php:242
Stack trace:
#0 /***/classes/Hook.php(677): HookCore::getNameById(0)
#1 /***/classes/module/Module.php(1029): HookCore::unregisterHook(Object(BlockSearch), 0, NULL)
#2 /***/classes/module/Module.php(733): ModuleCore->unregisterHook(0)
#3 /***/src/Adapter/Module/Module.php(269): ModuleCore->uninstall()
#4 /***/src/PrestaShopBundle/Install/Upgrade.php(565): PrestaShop\PrestaShop\Adapter\Module\Module->onUninstall()
#5 /***/src/PrestaShopBundle/Install/Upgrade.php(820): PrestaShopBundle\Install\Upgrade->disableIncompatibleModules()
#6 /***/install/upgrade/upgrade.php(93): PrestaShopBundle\Install\Upgrade->run()
#7 {main}
  thrown in /***/classes/Hook.php on line 242
  ```
  Is there any solution for this ?
  Thank you very much :)

EDIT : I found a simple hack : juste add the following line in classes/Hook.php before line 234 (beginning of the getNameById function) :
`if ($hook_id == 0) return null;`
I had another problem with the paypal module, I renamed the folder and the upgrade script could complete without any further error.
