### PR TITLE
Fix first attribute generation when not choosing first attribute

### LINKED ISSUE #12393: Generate combination issue when the attribute name contains a symbol
**Describe the bug**
In the product page, when we try to generate a combination and the attribute's name has a symbol for example `red/black` or `green yellow`, an error occurs

**To Reproduce**
Steps to reproduce the behavior: (Mode debug is enabled)
1. Go to BO => Catalog => Attributes => Color attribute page
2. Create new value for example `red/black` or `green yellow`
3. Go to BO => Products
4. Create a new Product with a combination
5. Select the attribute created  `green yellow`
6. Click on generate
7. See error

**Screenshots**
https://drive.google.com/file/d/175dA5DozFO15A_QFAFmpPJW0ci11YwJG/view
image

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | There was a problem when creating a new combination (first one). The process which was setting the default combination tried to access a false index in an array (the array was associated by position, not starting at 0)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12393
| How to test?  | Go to a product, remove all its combinations. Try to add a new attribute (do not use the first of the list).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12402)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/Admin/AttributeController.php [hunk 1]
```diff
@@ -174,8 +174,20 @@ public function ensureProductHasDefaultCombination(Product $product, array $comb
...
+                 * Combinations indexed by position, then attribute id
+                 * ex: $combinations = [
+                 *  3 => [ //4th position attribute
+                 *      45 => [ //product_attribute id
+                 *      ]
+                 *  ]
+                 * ]
+                 */
+                $firstPosition = array_keys($combinations)[0];
+                if (isset($combinations[$firstPosition]) && count($combinations[$firstPosition])) {
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/Admin/AttributeController.php]: `!empty($combinations[$firstPosition])` will do the isset and count at the same time but faster :D

Comment (jolelievre) [reply src/PrestaShopBundle/Controller/Admin/AttributeController.php]: Thanks, I always forget about this one!

**Review by PierreRambaud — APPROVED** [review]

File: src/PrestaShopBundle/Controller/Admin/AttributeController.php (hunk 1 above)
Comment (PierreRambaud) [reply src/PrestaShopBundle/Controller/Admin/AttributeController.php]: You're welcome :wink:
