### PR TITLE
Fix edit bulk quantity for stock page

### LINKED ISSUE #30634: Not possible to modify the Bulk edit quantity by clicking on the arrows
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On Stock Management, develop, it's not possible to modify the Bulk edit quantity by clicking on the arrows. On 8.0.x,it's possible.

image

### Expected behavior

It should be possible to modify the Bulk edit quantity by clicking on the arrows

### Steps to reproduce

1. On catalog > Stock
2. Click on the checkbox of a product
3. Click on arrows of Bulk edit quantity
4. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix some things on this component:<br>* Fix modify value by arrows<br>* Fix isFocused behaviour<br>* Improve input when we haven't check the bulk action.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | **Be carefull to correctly rebuild the assets of the admin-new-theme before testing!**<br>See #30634 
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/6458602927 ✅
| Fixed issue or discussion?     | Fixes #30634 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matks** [comment]
Sanity tests are failing but I know it's not related to this PR

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by AureRita** [comment]
Hi @boherm 

Thank you for your PR ! I tested it and it works well about the arrow, unfortunatelly, now we can't add number by a scroll with your mouse as you can see : 

[Untitled_ Oct 5, 2023 11_36 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/af13963a-d94b-4d35-8f2f-e2a3baadde7d)

Waiting for your feedback 

Thank you

**Comment by boherm** [comment]
Thanks for your tests @AureRita, I can't check that today! (I don't have a mouse with a wheel with me today... 😅)

File: admin-dev/themes/new-theme/js/app/widgets/ps-number.vue [hunk 1]
```diff
@@ -78,25 +78,30 @@
       },
     },
     methods: {
+      getValue(): number {
+        const value = Number.isNaN(this.value) ? 0 : Number.parseInt(<string> this.value, 10);
+
+        return Number.isNaN(value) ? 0 : value;
```
Comment (tleon) [inline admin-dev/themes/new-theme/js/app/widgets/ps-number.vue:84]: I don't understand this. Is it necessary to double check the same thing ? Couldn't we not just return the expression instead of going through a const  ?

**Review by jolelievre — APPROVED** [review]
Thanks @boherm

File: admin-dev/themes/new-theme/js/app/widgets/ps-number.vue (hunk 1 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/app/widgets/ps-number.vue:84]: I guess it's in case the value is not a number like if `aaa` is forced by the user, then `parseInt` would return `NaN`?

Comment (tleon) [reply admin-dev/themes/new-theme/js/app/widgets/ps-number.vue:84]: Wouldn't the first check `Number.isNaN(this.value)` catch it already ?

**Review by tleon — APPROVED** [review]
My comment is not blocking tho.

File: admin-dev/themes/new-theme/js/app/widgets/ps-number.vue (hunk 1 above)
Comment (boherm) [reply admin-dev/themes/new-theme/js/app/widgets/ps-number.vue:84]: Exactly @jolelievre! In a dark case, we must have an ultimate isNaN to check and set value correctly.

**Review by florine2623 — APPROVED** [review]
Hello @boherm ,

LGTM

https://github.com/PrestaShop/PrestaShop/assets/16019289/cac0105f-59c2-487d-bd7f-0048e8db49ee




It is QA ✅
