### PR TITLE
Prevent using period, comma keys inside quantity input

### LINKED ISSUE #9616: [BOOM-5790] Stock page - No alert message when editing quantity product with decimals
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5790).

- _**Reporter:**_ khouloud.belguith
- _**Created at:**_ Wed, 20 Jun 2018 10:34:16 +0200

---

#### Steps to reproduce 
1. In BO => Stock page => Select a product
2. edit quantity with decimals for example "2,1"
3. click "Apply new quantity"
4. See error => There is no alert displayed and 2 is added to the Available & Physical quantity successfully
5. But, if we try to add this quantity "2,1" with the "Check" button
6. See error => An alert displayed & this alert is displayed in frensh which is wrong

**Screenshots**
image

#### Additional infos

- PS version: 1.7.3.3
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | It's probably better to prevent using  these keys instead of forcing browser to validate fields
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9616.
| How to test?      | Details in the issue. You shouldn't be able to use `,` or `.` inside qty field anymore
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Logic is OK but ESlint complains

**Review by Progi1984 — CHANGES_REQUESTED** [review]
I don't think we should only take `,` & `.`. We should use CLDR because there exists many decimal separators : https://en.wikipedia.org/wiki/Decimal_separator.

**Comment by kpodemski** [comment]
@Progi1984 I don't think you can use something else than a digit, `.` and `,` + `e` (which doesn't cause issues) inside `type="number"`

**Comment by Progi1984** [comment]
@kpodemski Mozilla & Google are based on WhatWG which defines it : 

> As described above, a user agent might support numeric input in the user's local format, converting it to the format required for submission as described above. This might include handling grouping separators (as in "872,000,000,000") and various decimal separators (such as "3,99" vs "3.99") or using local digits (such as those in Arabic, Devanagari, Persian, and Thai).

Source : https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)

**Comment by kpodemski** [comment]
@Progi1984 

Sorry, I don't get your point. We want to prevent people from typing `1,23` `1.45`. That's it. CLDR could be useful for formatting output. In this scenario, what would you want me to do? Remember that we don't want to validate decimal values, we want to prevent typing decimal values.

**Comment by Hlavtox** [comment]
@kpodemski Try to think about if we maybe want to allow decimal quantities at some point in future.

**Comment by kpodemski** [comment]
@Hlavtox having this check there is the smallest problem we'd have 😜

**Comment by kpodemski** [comment]
@NeOMakinG could you take a look? :>

File: admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue [hunk 1]
```diff
@@ -97,6 +98,11 @@
         this.value = '';
         this.product.qty = null;
       },
+      onKeydown(event: KeyboardEvent): void {
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/app/pages/stock/components/overview/spinner.vue:102]: Can you add a comment there to explain why you added this? It will be clearer if we need to change it in the future

**Review by NeOMakinG — COMMENTED** [review]
Added a small comment taking @Progi1984 feedback into consideration, it looks fine to me as we want to avoid floats there, not need to overengineer it

**Review by MeKeyCool — DISMISSED** [review]

**Comment by MeKeyCool** [comment]
@kpodemski and @Progi1984 , I think you don't really speak about the same thing.

@kpodemski is simply fixing the #9616 issue as it is described while @Progi1984 you are trying to define a better specification for the component. I think you both have some good points to bring to project but to avoid frustrations and misunderstanding we should separate approaches. With a good agile process it is not a problem to make a small enhancement based on simple specifications waiting for better specs.

So the question is, where should we enhance specifications you brought @Progi1984 ? And what is the process to discuss about them ?

**Review by matks — DISMISSED** [review]
In my opinion that fix is valid. We can always do more but that is not a reason to reject bug fixes that fit current situation

@kpodemski check @NeOMakinG feedback ;)

**Review by matks — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @kpodemski 

Thank you for your PR, I tested it and it works, as we can see here :

https://user-images.githubusercontent.com/100699445/178497713-57770d33-92c0-4b40-95b3-bcbfc39985ea.mp4

(currently, when I pressed the "," or the ".", they aren't write on the field)

**Comment by atomiix** [comment]
Thanks @kpodemski & @AureRita
