### PR TITLE
Use relative urls for Quick Access menu

### LINKED ISSUE #29763: Quick Access links contain the domain: as a result, they potentially log out the user
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I the BO, the Quick Access links contain the domain. As a consequence, in a multishop environment, on gets potentially logged out when using Quick Access, because the domain of the BO changes unexpectedly. This is quite annoying.

### Expected behavior

No link in the BO must log me out. All the links must be relative to the domain and not include the domain.

### Steps to reproduce

Prerequisite:
- Set up a multishop installations with two shops
- Shop A on domain https://shop-a.com
- Shop B on domain https://shop-b.com
- A employee account that has access to the two shops.

Reproduce:
1. As employee log into the BO using https://shop-a.com
2. In the shop selection dropdown list select shop B
3. On the Quick Access menu, inspect the links, they all are like `<a href="https://shop-b.com...`
4. Follow a Quick access link
5. You are logged out and asked to log into shop B on https://shop-b.com

### PrestaShop version(s) where the bug happened

1.7.8.7 (1.6.1.1 does not have this erroneous behavior)

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Change the Quick Access links to use relative URLs. This assures that the employee does not get logged out when using a Quick access link in multishop environment
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29763
| Related PRs       | None
| How to test?      | Check #29763. Bug should not be reproducible after merging
| Possible impacts? | Is there a use case, when a Quick Access link should use an absolute URL? The only one I can imagine is a link to the FO, and this case is already addressed in the preexisting if-then-clause.

### CODE REVIEW

**Comment by kpodemski** [comment]
@lmeyer1, what about a scenario where you have your store in the subfolder? ;-)

**Comment by lmeyer1** [comment]
@kpodemski 
In a shop-in-subfolder scenario, there is the same basic problem: in order to be able to share a link between shops, the url should be valid in all shops. I have a test site where the shops are in a subfolder. I must test there to get aware of all the gotchas.

**Comment by lmeyer1** [comment]
@kpodemski
There are two cases of subfolder: physical_uri and virtual_uri.
- We must take into account `physical_uri` (and this IS ALWAYS the same for all shops)
- We do not need to take into account the `virtual_uri`, because the session is tied to a cookie that sits at the domain level. The user does not get logged out when he logged in using `domain.com/virtual/admin-dev` and is redirected to `domain.com/admin-dev`

With this the last commit everything works. EDIT: No, it doesn't. 😞

File: classes/QuickAccess.php [hunk 1]
```diff
@@ -104,7 +104,7 @@ public static function getQuickAccessesWithToken($idLang, $idEmployee)
 
                     $tokenString = $admin_tab[1] . (int) Tab::getIdFromClassName($admin_tab[1]) . $idEmployee;
                 }
-                $quickAccess[$index]['link'] = '/' . basename(_PS_ADMIN_DIR_) . '/' . $quick['link'];
+                $quickAccess[$index]['link'] = Context::getContext()->shop->physical_uri . basename(_PS_ADMIN_DIR_) . '/' . $quick['link'];
```
Comment (lmeyer1) [inline classes/QuickAccess.php]: No, this won't work. 
/!\  $context->shop is not related to the URL used to access the admin area.
As $shop->physical_uri is identical for all shops on the same installation, this might work most of the time.
This does not work: shop 1 @ example.com, shop2 @ example.org/shop. Here the two domains are different, and the virtual-uri also.

**Comment by lmeyer1** [comment]
@kpodemski 
>What about a scenario where you have your store in the subfolder?

The problem is fixed. It will work now in any case.

Force-push after rebase.

**Review by kpodemski — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @lmeyer1 ,

I have checked your PR,
The employee does not get logged out when using a Quick access link in multishop environment.

- The issue is well fixed. 
- The automated tests are OK.

So it is QA  approved :heavy_check_mark: 

Thank you.

**Comment by kpodemski** [comment]
Thank you, @lmeyer1 🎉
