### PR TITLE
Multistore: fix configuration value not saved for current context

### LINKED ISSUE #26967: BO - Multistore - Save settings for a specific shop is not working correctly in maintenance page.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Save settings for a specific shop is not working correctly in maintenance page.
https://watch.screencastify.com/v/5E5iLUNfKXapZgdyUNha

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO enable multistore and create a new shop
2. Go to Shop parameters > general > Maintenance
3. Select  All Shop, and fill "ip de maintenance" with the field "all-shop-value" 
4. select the new shop , check the box  ip de maintenance and fill it with the field "single-shop-value" 
5. Uncheck the box  ip de maintenance , save , the default value  "all-shop-value" will be restored
6. check all boxes and save 
7. the settings are not saved for Maintenance IP and Custom maintenance text

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Configuration values were not saved for current multistore context when the value was the same as the parent value
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26967
| How to test?      | See issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26994)

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
this is wip, tests coming

File: classes/Configuration.php [hunk 1]
```diff
@@ -469,7 +469,7 @@ public static function updateValue($key, $values, $html = false, $idShopGroup =
         foreach ($values as $lang => $value) {
             $storedValue = Configuration::get($key, $lang, $idShopGroup, $idShop);
             // if there isn't a $stored_value, we must insert $value
-            if ((!is_numeric($value) && $value === $storedValue) || (is_numeric($value) && $value == $storedValue && Configuration::hasKey($key, $lang))) {
+            if ((!is_numeric($value) && $value === $storedValue && Configuration::hasKey($key, $lang, $idShopGroup, $idShop)) || (is_numeric($value) && $value == $storedValue && Configuration::hasKey($key, $lang, $idShopGroup, $idShop))) {
```
Comment (matks) [inline classes/Configuration.php]: That's a really long line 😄  should we pass it into multiline?

**Review by matks — DISMISSED** [review]
Approved, submitted 1 nice to have

File: classes/Configuration.php (hunk 1 above)
Comment (Progi1984) [inline classes/Configuration.php]:
```suggestion
            if (
              ((!is_numeric($value) && $value === $storedValue) || (is_numeric($value) && $value == $storedValue))
               && Configuration::hasKey($key, $lang, $idShopGroup, $idShop)
            ) {
```

**Review by Progi1984 — COMMENTED** [review]
A small feedback

**Review by sowbiba — COMMENTED** [review]
Nothing to add to @Progi1984 suggestion
Wait for it to approve

**Review by sowbiba — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,

PR is tested and the issue is fixed.
https://watch.screencastify.com/v/LxqDmhyDe9lMQAc6ARYb

Thanks,
