### PR TITLE
Order page in BO > partial refund block, bad displaying of products “Quantity” field

### LINKED ISSUE #29050: Order page in BO > partial refund block, bad displaying of products “Quantity” field
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Screenshot from 2022-07-12 12-03-20

### Expected behavior

As in previous versions
Screenshot from 2022-07-12 14-10-49

### Steps to reproduce

1. Open some order page in BO
2. Click on "Partial refund" button
3. Check “Quantity” field 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Order page in BO > partial refund block, bad displaying of products “Quantity” field
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29050.
| Related PRs       | 
| How to test?      | See issue
| Possible impacts? |

### CODE REVIEW

**Review by marsaldev — APPROVED** [review]

File: src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php [hunk 1]
```diff
@@ -62,6 +62,7 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
                     'required' => false,
                     'data' => 0,
                     'scale' => 0,
+                    'unit' => '/ ' . $product->getQuantity(),
```
Comment (MeKeyCool) [inline src/PrestaShopBundle/Form/Admin/Sell/Order/CancelProductType.php:65]: I think it is very tricky for developer to understand that `unit` represents the number of available values.

Is it documented anywhere ? Maybe a comment or a reference to the documentation would be great :thinking: ...

**Review by MeKeyCool — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @okom3pom,

Thank you for this PR.
Tested on 8.0.x branch and PHP 7.3 version.

All auto tests are ok ✅ 
The field is well displayed on partial refund block ✅:

Capture d’écran 2022-09-09 à 14 28 59


QA approved ✅ 

Thanks

**Comment by matthieu-rolland** [comment]
thank you @okom3pom and @sLorenzini !
