### PR TITLE
Front side validation problem on the number of characters in a password

### LINKED ISSUE #19505: FO Account creation - Browser-side validation problem on the number of characters in a password
#### Describe the bug

There is only a HTML validation of the password when creating an account. This is problematic if a theme does not add this check because it is impossible for the user to connect later.

#### Expected behavior

In case there is no HTML validation in the theme, perform a validation from the server before registration.

#### Steps to Reproduce

1. Delete the validation from the template `form-fields.tpl`
form-fields

2. Go on the registration form
3. Create an account with a password under 5 characters long
form

5. Log out and try to log in
loginform
erorr

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by florian-202**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | There is only a HTML validation of the password when creating an account. This is problematic if a theme does not add this check because it is impossible for the user to connect later, see also #19505 
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19505.
| How to test?  | - Delete the validation from the template form-fields.tpl <br> - Go on the registration form <br> - Create an account with a password under 5 characters long <br> - Log out and try to log in

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19534)

### CODE REVIEW

File: classes/form/CustomerForm.php [hunk 1]
```diff
@@ -138,6 +138,15 @@ public function validate()
             );
             $birthdayField->setValue($dateBuilt->format('Y-m-d'));
         }
+
+        $passwordField = $this->getField('password');
+        if(!Validate::isPasswd($passwordField->getValue())) {
```
Comment (clotairer) [inline classes/form/CustomerForm.php]:
```suggestion
        if(Validate::isPasswd($passwordField->getValue()) === false) {
```

File: classes/form/CustomerForm.php [hunk 2]
```diff
@@ -138,6 +138,15 @@ public function validate()
...
+            $passwordField->AddError($this->translator->trans(
+                'The password should be at least 5 characters long',
+                [],
+                'Shop.Notifications.Error'
+            ));
+        }
```
Comment (PululuK) [inline classes/form/CustomerForm.php]: The error message will be incorrect if the password contains more than 72 characters
https://github.com/202ecommerce/PrestaShop/blob/fix-password-validation/classes/Validate.php#L541

**Suggestion :** 

Return a new common error message for both cases (<5 and > 72)  :  
Example :  `Password must be between 5 and 72 characters long` or something like that

Comment (florian-202) [reply classes/form/CustomerForm.php]: I hadn't thought about it, I'll fix it

Comment (PululuK) [reply classes/form/CustomerForm.php]: ping @LouiseBonnard @Junebyun if you need help with this!

Thank you @florian-202

**Review by clotairer — APPROVED** [review]

File: classes/form/CustomerForm.php [hunk 3]
```diff
@@ -138,6 +138,15 @@ public function validate()
             );
             $birthdayField->setValue($dateBuilt->format('Y-m-d'));
         }
+
+        $passwordField = $this->getField('password');
+        if (Validate::isPasswd($passwordField->getValue()) === false) {
+            $passwordField->AddError($this->translator->trans(
+                'Password must be between 5 and 72 characters long',
+                [],
+                'Shop.Notifications.Error'
```
Comment (Junebyun) [inline classes/form/CustomerForm.php:147]:
```suggestion
                'Password must be between 5 and 72 characters',
                [],
                'Shop.Notifications.Error'
```

Comment (Junebyun) [inline classes/form/CustomerForm.php:147]:
```suggestion
                'Password must be between 5 and 72 characters.',
                [],
                'Shop.Notifications.Error'
```

**Review by Junebyun — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM The validation is correctly added . Thanks @florian-202 !

**Comment by Progi1984** [comment]
Thanks @florian-202 & @SD1982

**Review by jolelievre — APPROVED** [review]
