### PR TITLE
Fixed cart rule on selected product with product with ecotax

### LINKED ISSUE #24788: FO - Discounts - The discount detail is NOK when we the product selected has an ecotax
#### Describe the bug

In the FO > Shopping cart page and checkout page, when we apply a cart rule "percent discount on a selected product that has an ecotax, the discount line s NOK.

#### Steps to Reproduce

1. Go to BO > International > Taxes & Enable Ecotax
2. Create a product with ecotax, in my case  image
3. Go to BO > Catalog > Cart rules page and create a cart rule:
3.1 Product Selection: select the ecotax product 
image
3.2 a percent discount, in my case 50% & Apply a discount to Selected Products 
image
4. Go to FO > Add the last product created to the cart
5. Apply the discount
6. See error: the discount line = 6.2 => NOK, it should be 6
image

If we place the order => the discount is ok on the Order details page
image

In the PS1769, we have this
image

#### Additional information

* PrestaShop version: 1775build1, 1774
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fixed cart rule on selected product with product with ecotax : the price with taxes is calculated from tax rate but the price contains ecotax. It must be removed before calculation.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24788
| How to test?      | Cf #24788

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24868)

### CODE REVIEW

File: classes/CartRule.php [hunk 1]
```diff
@@ -1274,7 +1274,9 @@ public function getContextualValue($use_tax, Context $context = null, $filter =
                             if ($use_tax) {
                                 $infos = Product::getTaxesInformations($product, $context);
                                 $tax_rate = $infos['rate'] / 100;
+                                $price -= $product['ecotax'];
```
Comment (PierreRambaud) [inline classes/CartRule.php:1278]: Add a comment explaining why it's like that please

Comment (Progi1984) [reply classes/CartRule.php:1278]: Explained in description

Comment (PierreRambaud) [reply classes/CartRule.php:1278]: Not sure people are going to read the PR description when reading the code :thinking:

Comment (Progi1984) [reply classes/CartRule.php:1278]: Fixed

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

Could you check the conflict ?

Thanks!

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @Progi1984 !

**Comment by Progi1984** [comment]
Thanks @florine2623
