### PR TITLE
Prevent adding out of stock products in Create order page

### LINKED ISSUE #22109: BO > Create Order : No limitation on quantity when out of stock
#### Describe the bug

In BO > Orders > Add new order : For a product with a "Deny out of stock order" behavior, it is possible to add more product than available (only by editing quantity). The total are however OK : Only the available quantity is counted for Total, Discount, Shipping...

There is also an error message displayed.

Once the order is created, only the available quantity is in the order, so it's only a trivial bug.

In 176x, it was not possible to add more than the available quantity.

#### Expected behavior

Label in stock is displayed in the product list.

If the product quantity selected by the user is higher than the stock available and the stock behavior when out of stock is deny orders 
Then
Keep the stock selected by the user in the input and the error message but the button create order is disabled. 

(Not ISO)
#### Steps to Reproduce

1. Have a Product A with quantity = 2, and "Deny out of stock order"
2. Go to BO > Create Order > Add new order, choose a customer
3. Add product A, try to add more than available quantity : It is not possible.
4. Once Product A is added, try to edit quantity over the available quantity : It is possible (but a warning is displayed and the totals are not updated)

**Screenshots**

Screenrecord : 
https://drive.google.com/file/d/1WMHUAq1EkjMSZ2XW2T8ICU78Y-WvTwO1/view?usp=sharing

screencapture-localhost-prestabeta17702-admin9418pfie6-index-php-sell-orders-orders-new-2020-11-25-16_31_21

#### Additional information

* PrestaShop version: presta1770stable1
* PHP version: N/A

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Prevent adding out of stock products in Create order page
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #22109
| How to test?      | Cf #22109

**:notebook: BC Breaks :**
* In `src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php`, the constructor has two new parameters in 11th `int $stock` and 12th `bool $availableOutOfStock`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22920)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found two issues:

**First issue**

1. Create a product A with combinations 
image

2. Go to BO > Create Order > Add new order, choose a customer
3. Add product A 
4. See error: the in stock is incorrect 
image
5. Try to change a combination
6. See an error in the console

**second issue**

1. In the BO > Orders > Add new Order
2. Choose a customer
3. Add any product to the cart
4. See the alignment issue 
image

**Without PR**
image

Thanks!

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Progi1984** [comment]
(Ping @NeOMakinG for the second issue)

File: src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php [hunk 1]
```diff
@@ -206,6 +222,22 @@ public function getCustomization(): ?Customization
         return $this->customization;
     }
 
+    /**
+     * @return int
+     */
+    public function getStock(): int
```
Comment (eternoendless) [inline src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php]: This should be `getStockAvailable` for consistency

Comment (eternoendless) [reply src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php]: What does this return when stock management is disabled?

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js [hunk 2]
```diff
@@ -160,24 +166,31 @@ export default class ProductRenderer {
...
+    );
     this._renderCombinations(product.combinations);
     this._renderCustomizations(product.customizationFields);
   }
 
   /**
    * Updates stock text helper value
    *
+   * @param {object} inputStockCounter
+   * @param {object} inputQuantity
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: Please document what these parameters are

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js [hunk 3]
```diff
@@ -160,24 +166,31 @@ export default class ProductRenderer {
...
    * @param {number} stock
    * @param {boolean} infinitMax
```
Comment (eternoendless) [inline admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js]: I don't know what these are either

File: src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php [hunk 4]
```diff
@@ -553,6 +553,8 @@ private function buildCartProduct(
             \Tools::ps_round($product['total'], $currency->precision),
             $this->contextLink->getImageLink($product['link_rewrite'], $product['id_image'], 'small_default'),
             $this->getProductCustomizedData($cart, $product),
+            Product::getQuantity((int) $product['id_product']),
+            (bool) Product::isAvailableWhenOutOfStock($product['out_of_stock']),
```
Comment (PierreRambaud) [inline src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]: The funny thing, this method returns an int :exploding_head:

Comment (Progi1984) [reply src/Adapter/Cart/QueryHandler/GetCartForOrderCreationHandler.php]: Fixed

File: src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php (hunk 1 above)
Comment (Progi1984) [reply src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php]: Renamed for the variable name.

Comment (Progi1984) [reply src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php]: For the second, I think it's a complete regression.

Comment (Progi1984) [reply src/Core/Domain/Cart/QueryResult/CartForOrderCreation/CartProduct.php]: And it doesn't seem a regression
So it's a bug : https://github.com/PrestaShop/PrestaShop/issues/23216

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I found an issue following these steps: 

1. The product `demo_1` has 8 combinations for each combination quantity = 300 
image
2. Go to BO > Orders > Add new Order page > Choose a customer
3. Search for the product `Hummingbird printed t-shirt` (demo_1)
4. Add it to the cart
5. See the error, the quantity is NOK 
image
**Without PR**
image
6. **With PR** we can edit quantity over the available quantity= 300: It is possible to increase it to 2400 = quantities of all combinations
Ping @PrestaShop/product-team @Progi1984 what do you think?

Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith I have fixed the bug for "See the error, the quantity is NOK". I just took the product (and not the combination if it was specified) :facepalm: .

File: admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js [hunk 5]
```diff
@@ -73,6 +73,12 @@ export default class ProductRenderer {
         $template.find(createOrderMap.listedProductQtyInput).data('attribute-id', product.attributeId);
         $template.find(createOrderMap.listedProductQtyInput).data('customization-id', customizationId);
         $template.find(createOrderMap.listedProductQtyInput).data('prev-qty', product.quantity);
+        this.renderStock(
+          $template.find(createOrderMap.listedProductQtyStock),
+          $template.find(createOrderMap.listedProductQtyInput),
+          product.availableStock,
+          product.availableOutOfStock || (product.availableStock <= 0)
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js:80]: This check is weird, I know it's not new from your PR but how does it make sense?
If the stock is negative or zero then we consider it infinite?

Comment (Progi1984) [reply admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js:80]: Yes

**Review by matthieu-rolland — APPROVED** [review]
I reviewed your last modifications given khouloud's feedback, looks good to me 👍

**Comment by sowbiba** [comment]
The protection added is all about create order interface (App)
Is there a control made when creating the Order ?

**Review by sowbiba — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/187NkGpPCGRrREjDZ9KImYmydI_SlcII4/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
## WAIT FOR 1772 RELEASE

**Comment by PierreRambaud** [comment]
Thank you @Progi1984
