### PR TITLE
Fix: Unable to configure a module that utilizes a modern controller

### LINKED ISSUE #38045: Unable to configure a module that utilizes a modern controller
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There’s an issue with the configuration page of modules using modern (Symfony) controllers. It simply redirects to the 404 page.

### Expected behavior

It should open the configuration page of the module.

### Steps to reproduce

1. Install PS 9.0.0 Beta
2. Navigate to any module that utilizes a modern controller, such as the `blockwishlist` module
3. Observe multiple redirections that are finally landing on 404 page error

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Promokit

### PR DESCRIPTION
**Pull request by Codencode**
In case of installation in a subfolder, "physical_uri" is added twice.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | When PrestaShop is installed in a subfolder, the "physical_uri" field is added twice in the configuration URL of a module that uses the modern configuration page.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/38045
| UI Tests          |  https://github.com/paulnoelcholot/testing_pr/actions/runs/15156649630
| Fixed issue or discussion?     | Fixes #38045
| Related PRs       | 
| Sponsor company   | @Codencode

### CODE REVIEW

File: classes/Tools.php [hunk 1]
```diff
@@ -204,6 +204,13 @@ public static function sanitizeAdminUrl(string $url): string
         $link = Context::getContext()->link;
         if (!preg_match('@^https?://@i', $url) && $link) {
             $baseUrl = rtrim($link->getAdminBaseLink(), '/');
+
+            $physicalUri = Context::getContext()->shop->physical_uri;
```
Comment (nicosomb) [inline classes/Tools.php:210]: could you please a one-line comment to explain your change?

Comment (Codencode) [reply classes/Tools.php:210]: > could you please a one-line comment to explain your change?

Done, is it clear enough?

**Review by nicosomb — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@Codencode Brother, aren't we fixing a symptom instead of a root cause here? **I did not check how it works**, but string replacing something in an URL seems like a too much magic here, shouldn't we get the clean URL from somewhere ready to go? 🤔

**Comment by Codencode** [comment]
@Hlavtox,
the issue is that in the case of an installation in a subfolder, we end up with the value of `physical_uri `both in `$baseUrl` and in `$url`.

For example, considering PrestaShop installed locally at the URL "localhost/shop", we would have:

- $url = /shop/admin-dev/modules/blockwishlist/configuration?_token=xxxx
- $baseUrl = http://localhost/shop

As a result, we would get:
$url = http://localhost/shop/shop/admin-dev/modules/blockwishlist/configuration?_token=xxxx

We should either remove the prefix in `Link::getAdminBaseLink()` or remove it from the input, but that seems tricky.

What do you think?

**Comment by Hlavtox** [comment]
@Codencode From what I see, `sanitizeAdminUrl` was added to 9.x.x for some reason, it didn't exist before.

In 8.2, `redirectAdmin` just uses the URL directly - `header('Location: ' . $url);`.

So, I think that `sanitizeAdminUrl` should not exist at all and the code that calls `redirectAdmin` should make sure it passes a proper link in the first place. It has getAdminLink and/or symfony router for that purpose.

**Comment by Codencode** [comment]
@Hlavtox Yes, I noticed that sanitizeAdminUrl was introduced in 9.x.x.

So, would you remove this method?

**Comment by Hlavtox** [comment]
I will ping @jolelievre as he was the one who introduced the method in https://github.com/PrestaShop/PrestaShop/commit/0c37633675b87790ce2d275837470405dc6e1ece

You can see in the test in the commit what this code does, it standardizes the URL. 

But, I think, if it wasn't required before in all the symfony code and we could route just fine, is it really needed?

**Comment by jolelievre** [comment]
The `sanitizeAdminUrl` thing was added to maintain backward compatibility in module configuration

I don't remember all the details but mostly the problem was that previously configuration pages were rendered under an address that looked like `http://myshop.com/admin-dev/index.php?controller=AdminModules&action=configure&module=module_name` but the migrated page has an address that looks like `/admin-dev/improve/modules/manage/action/configure/{module_name}` so many URLs in the form configuration action tag were not correct anymore because they were expecting being displayed at the root of the admin URL. And many of them in the native modules are built manually by appending pieces of URLs in the template or in the `FormHelper` configuration.

I believe this resulted in incorrect redirection after the form was submitted. Long story short the extra method was definitely added or a reason but maybe there's a better solution, the main issue comes from the manually built URLs but I expect many tier modules to use the same bad practice so we need a generic solution that maximizes the backward compatibility.

**Comment by Codencode** [comment]
I’m definitely stating the obvious here.
If we consider the blockwishlist module, the URL generated here:
https://github.com/PrestaShop/blockwishlist/blob/04578362768800a1a680c86ce5a64cc35785fff6/blockwishlist.php#L111-L116

is identical between PrestaShop version 8 and version 9.

In light of this, if the `sanitizeAdminUrl` method was introduced for the reasons mentioned by @jolelievre, I believe we should modify it to prevent the `physical_uri` value from being repeated twice.

If you have any suggestions, I can run some tests.

**Comment by Codencode** [comment]
An alternative solution could be this:

```php
    public static function sanitizeAdminUrl(string $url): string
    {
        $link = Context::getContext()->link;
        if (!preg_match('@^https?://@i', $url) && $link) {
            if (str_contains($url, Context::getContext()->shop->physical_uri)) {
                $baseUrl = self::getShopDomainSsl(true);
            } else {
                $baseUrl = rtrim($link->getAdminBaseLink(), '/');
            }

            if (!str_contains($url, basename(_PS_ADMIN_DIR_))) {
                $baseUrl .= '/' . basename(_PS_ADMIN_DIR_);
            }

            $url = $baseUrl . '/' . trim($url, '/');
        }

        return $url;
    }
```

This way, if the input URL contains `physical_uri`, we build `$baseUrl` with just the protocol and domain (e.g., https://localhost/).
Otherwise, if `physical_uri `is not present in the URL, we construct `$baseUrl` using `$link->getAdminBaseLink()`.

File: classes/Tools.php [hunk 2]
```diff
@@ -204,6 +204,14 @@ public static function sanitizeAdminUrl(string $url): string
         $link = Context::getContext()->link;
         if (!preg_match('@^https?://@i', $url) && $link) {
             $baseUrl = rtrim($link->getAdminBaseLink(), '/');
+
+            // Removes physical_uri from baseUrl to avoid duplicate admin path
+            $physicalUri = Context::getContext()->shop->physical_uri;
+            if (substr($physicalUri, -1) === '/') {
+                $physicalUri = rtrim($physicalUri, '/');
+            }
+            $baseUrl = str_replace($physicalUri, '', $baseUrl);
```
Comment (jolelievre) [inline classes/Tools.php]: This global str_replace worries me a bit because in case the folder is in the middle of the url it could be replaced when not intented to Maybe we should check if the folder is present at the beginning of the url only something like:

```php
$url = trim($url, '/');
if (str_starts_with(, $physicalUri)) {
   $url = substr($url, strlen($physicalUri))
}
$url = trim($url, '/');
```

The code is not optimised too many trims here and there that should be mutualized but that's the idea

Comment (jolelievre) [reply classes/Tools.php]: Also this `sanitizeAdminUrl` is far from ideal and not super stable potentially, but I couldn't find a cleaner solution But because of its potential instability it's important to test it accurately, which is why you should update the related tests https://github.com/PrestaShop/PrestaShop/blob/0c37633675b87790ce2d275837470405dc6e1ece/tests/Integration/Classes/ToolsTest.php#L33

and add some use cases with this extra shop folder

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @Codencode 

The basic solution is here indeed, but it can still be improved a little to prevent some unexpected side effects

File: classes/Tools.php (hunk 2 above)
Comment (jolelievre) [reply classes/Tools.php]: I just thought that the `str_starts_with` condition could maybe be even stricter and include the `index.php` since this problem will likely only happens on legacy urls so instead of checking that the url starts with `/sub_folder` maybe we should check that it starts with `/sub_folder/index.php`

Comment (jolelievre) [reply classes/Tools.php]: I just noticed I implemented my suggestion wrongly, instead of modifying the `$url` we should adapt the `$baseUrl`

**Comment by Codencode** [comment]
@jolelievre,
could it be like this?

```php
    public static function sanitizeAdminUrl(string $url): string
    {
        $link = Context::getContext()->link;
        if (!preg_match('@^https?://@i', $url) && $link) {
            $baseUrl = rtrim($link->getAdminBaseLink(), '/');

            // Removes physical_uri from baseUrl to avoid duplicate admin path
            $physicalUri = Context::getContext()->shop->physical_uri;
            if (str_starts_with($url, $physicalUri)) {
                $url = substr($url, strlen($physicalUri));
            }

            if (!str_contains($url, basename(_PS_ADMIN_DIR_))) {
                $baseUrl .= '/' . basename(_PS_ADMIN_DIR_);
            }

            $url = $baseUrl . '/' . trim($url, '/');
        }

        return $url;
    }
```

Regarding the tests, I don't have much knowledge on the matter, but if we can define a solution to solve the problem, I can work on it to figure out how to proceed.

Thank you!

**Comment by jolelievre** [comment]
@Codencode yep it seems ok, you can propose this change I'll look into the tests if you want

I anticipate they can be tricky because they are integration tests, so they are based on the shop config meaning we'd have to define a shop path during the test process but only for some use cases...

**Comment by Codencode** [comment]
@jolelievre I've updated the code in the PR.
If the change looks good, as soon as I have some time, I'll focus on the tests to see if I can implement them. Of course, any suggestions you have are more than welcome :).
Thanks!

**Comment by jolelievre** [comment]
Thanks @Codencode 
Seems ok to me, I'm gonna look into the tests to improve them

**Review by jolelievre — APPROVED** [review]
Thanks @Codencode 

I added the new tests, nothing fancy but it validates a few potential use cases with physical URI, your code handled them all correctly nice job

And at least we have these tests to keep us safe when we'll need to further evolve this method (which is likely to happen 😅)

**Comment by Codencode** [comment]
> Thanks @Codencode
> 
> I added the new tests, nothing fancy but it validates a few potential use cases with physical URI, your code handled them all correctly nice job
> 
> And at least we have these tests to keep us safe when we'll need to further evolve this method (which is likely to happen 😅)

@jolelievre,
I noticed that you handled various scenarios, including the configuration URL of a module (in the "blockwishlist" test). This is an excellent approach for future considerations, as you rightly pointed out yourself 😄.

Great job!

Thank you so much!

**Review by kpodemski — APPROVED** [review]

**Comment by Codencode** [comment]
Hi @PrestaShop/qa-functional,
Could you check this PR when you have time? Let me know if there are any blockers or if you need anything from my side.

Thanks in advance! 🙏

**Review by paulnoelcholot — COMMENTED** [review]
Hello @Codencode,

I tester your PR but the issue seems still here :/


https://github.com/user-attachments/assets/b41bf595-3d40-4961-88f5-793afa2faf17

Did I miss something?

Thanks for your feedback!

**Comment by Codencode** [comment]
Hello @paulnoelcholot,

I tested the change again, and it works.
Could you please verify that the PR modification has been set up correctly?

You need to check this file:
https://github.com/PrestaShop/PrestaShop/pull/38048/files#diff-0175e8ccd89d320e7f91e6333bc749edb922cd119188d0545f51fa3dd838aa2c

Thanks!

[screen-capture.webm](https://github.com/user-attachments/assets/f78e1139-b7ba-46c8-9983-3ae56f44ecf5)

**Comment by paulnoelcholot** [comment]
Hello @Codencode,

My apologies! Yes it was a problem during the PR installation as you had sensed.

So now it's good for me! :tada: 

Thanks!


https://github.com/user-attachments/assets/ba5e966b-d6d6-4ed3-b20d-1f5b7301a078

Automated test : https://github.com/paulnoelcholot/testing_pr/actions/runs/15156649630

**Review by paulnoelcholot — APPROVED** [review]

**Comment by Codencode** [comment]
Hello @paulnoelcholot,
Perfect!
Thank you!
