### PR TITLE
Deleting extra parameter

### LINKED ISSUE #26212: Wrong number of parameters in method getSimpleAddresses from class Customer in class CheckoutSession
#### Describe the bug

In method `getCustomerAddressesCount` of class `CheckoutSession`, the call of method `getSimpleAddresses` from class `Customer` has a wrong number of parameters

For info, I met this issue because for a specific need, I had to override method `getSimpleAddresses` in class `Customer` and i had to add an argument to it but it didn't work due to this wrong call

#### Expected behavior

Both methods need to have same number of parameters

#### Steps to Reproduce

1. Check the method `getSimpleAddresses` in class [Customer ](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/Customer.php#L677) -> Only one argument
2. Compare with its call in method `getCustomerAddressesCount` of class [CheckoutSession](https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/classes/checkout/CheckoutSession.php#L72) -> Two arguments
3. See error > not same number of parameters

**Screenshots**

image

image

#### Additional information

* PrestaShop version: At least 1.7
* PHP version: All

### PR DESCRIPTION
**Pull request by christophe-rouille**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |  In method getCustomerAddressesCount of class CheckoutSession, the call of method getSimpleAddresses from class Customer has a wrong number of parameters
| Type?             |  refacto 
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26212
| How to test?      | Check the method getSimpleAddresses in class Customer -> Only one argument<br>Compare with its call in method getCustomerAddressesCount of class CheckoutSession -> 
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26268)

### CODE REVIEW

**Review by PrestaEdit — APPROVED** [review]

File: classes/checkout/CheckoutSession.php [hunk 1]
```diff
@@ -70,8 +70,7 @@ public function getCart()
     public function getCustomerAddressesCount()
     {
         return count($this->getCustomer()->getSimpleAddresses(
-            $this->context->language->id,
-            true // no cache
+            $this->context->language->id
```
Comment (PululuK) [inline classes/checkout/CheckoutSession.php:73]: Hi @christophe-rouille,
Thanks for your contribution !
I'm trying to understand the intention of the developer who made this implementation. 
I think he wanted to use this parameter to cache the SQL request generated by `Customer::getSimpleAddressSql`. See https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Customer.php#L694-L695

So in my opinion, we should instead improve `Customer::getSimpleAddresses` method and add this parameter and use it when executing the request. Something like :

```php
 public function getSimpleAddresses($idLang = null, ?bool $useCache = false)
    {
        ...
        ...
        $sql = $this->getSimpleAddressSql(null, $idLang);
        $result = Db::getInstance(_PS_USE_SQL_SLAVE_)->executeS($sql, true, $useCache);
        ....
        ....
    }
```
But it can be done in another PR!
So, it is Ok for me.

**Review by PululuK — APPROVED** [review]

**Comment by tegbessou** [comment]
PR is valid IMO

**Review by matthieu-rolland — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Can this PR be tested by a dev ? Thanks :)

**Comment by atomiix** [comment]
Actually, there is no need for QA for this one, merging it!

**Comment by atomiix** [comment]
Thanks @christophe-rouille!
