### PR TITLE
Keep order detail from being updated in BO > Order detail page, when product doesn't exist anymore

### LINKED ISSUE #20818: [1.7.7 beta 2] Order view - Product ID is invalid error message
#### Steps to Reproduce

1. Install 1.7.7 beta 2.
2. Delete all products.
3. Go edit KHWLILZLL.
4. Change price of the product.
5. Price will change, but error message will be displayed that the product ID is invalid.

#### Additional information

* PrestaShop version: 1.7.7 beta 2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In BO > Order detail, when updating the price of a deleted product, we would have a bad error message and the order detail would still be updated. This PR improves the error message and do not update the price.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20818
| How to test?  | See steps described in #20818

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20902)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

File: src/Core/Domain/Order/Exception/CannotUpdateProductInOrder.php [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+declare(strict_types=1);
+
+namespace PrestaShop\PrestaShop\Core\Domain\Order\Exception;
+
+/**
+ * Thrown on failure to update product in an order
+ */
+class CannotUpdateProductInOrderException extends OrderException
```
Comment (jolelievre) [inline src/Core/Domain/Order/Exception/CannotUpdateProductInOrder.php]: The filename is incorrect -> `CannotUpdateProductInOrderException.php`

File: src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php [hunk 2]
```diff
@@ -145,6 +146,12 @@ private function assertProductCanBeUpdated(
         Order $order,
         OrderInvoice $orderInvoice = null
     ) {
+        // assert product exists
+        $product = new Product($orderDetail->product_id);
+        if ($product->id !== (int) $orderDetail->product_id) {
+            throw new CannotUpdateProductInOrderException('You cannot edit the price of a product that no longer exists in your catalog.');
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php]: The exception name seems too generic as there are many reasons why the product can not be updated (see all the rest of the function). This exception should reflect this particular reason, something like `ProductInOrderNotFoundException` `CannotFindProductInOrderException` or similar

**Review by jolelievre — CHANGES_REQUESTED** [review]
The name and especially filename of the exception need to be improved Also could you add a behat test for this use case please? 🙂

File: src/Core/Domain/Order/Exception/CannotUpdateProductInOrder.php (hunk 1 above)
Comment (matthieu-rolland) [reply src/Core/Domain/Order/Exception/CannotUpdateProductInOrder.php]: damn yes, I broke my branch and reproduced this code on a new one, and didn't name this file right 🤦

**Review by jolelievre — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 3]
```diff
@@ -1494,4 +1495,67 @@ private function getOrderDiscountByName(int $orderId, string $cartRuleName): ?Or
...
+        $product->delete();
+    }
+
+    /**
+     * @When I update deleted product :productReference in order :orderReference
+     *
+     * @param string $productReference
+     * @param string $orderReference
+     */
+    public function tryUpdatingProductDeletedFromCatalogue(string $productReference, string $orderReference)
```
Comment (atomiix) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:1519]: Why not updating `updateProductInOrder()` directly?

Comment (matthieu-rolland) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:1519]: Indeed ! So I called `updateProductInOrder()` in this method, thanx for the catch. 

This method is still necessary, we are in a special case: updating a product that was deleted from the catalogue, going through `editProductsToOrderWithFollowingDetails()` method would trigger errors at several points before updating because the product doesn't exist anymore.

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 4]
```diff
@@ -1494,4 +1497,54 @@ private function getOrderDiscountByName(int $orderId, string $cartRuleName): ?Or
 
         return null;
     }
+
+    /**
+     * @When I delete product :productReference from catalogue
+     *
+     * @param string $productReference
+     */
+    public function removeProductFromCatalogue(string $productReference)
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php:1506]: This should be in `ProductFeatureContext`

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
