### PR TITLE
Fix obvious bugs in product page

### LINKED ISSUE #24258: [Experimental product page] Fix raw bugs
### Describe the bug

The QA team explored the experimental product page and reported many raw bugs. We need to fix them.

#### In Edit a Product experimental BO page

When saving the form in product not virtual an error related to virtual_product_file_id always popped
When switching to combination type and error related to missing stock form always popped
When switching types to combination an error indicating that extra fields were present prevented from validating the form and really save the modification

#### In Create a Product experimental BO page

All fields should ne correctly prefilled so the only error you should have when creating a new product is the missing default name (if absent of course)
When you switch the type in creation you should have a modal to force you to submit the form to confirm this modification (unlike the edition page no extra warning is displayed as it's not useful for an empty/new product)

#### Additional information

* PrestaShop version: `1.7.8.x`

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR aims to fix the first obvious and really blocking bugs in the new product page that prevent QA team from correctly testing it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/24258
| How to test?      | See description
| Possible impacts? | See description

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24168)

### In edition:
- When saving the form in product not virtual an error related to `virtual_product_file_id` always popped
- When switching to combination type and error related to missing stock form always popped
- When switching types to combination an error indicating that extra fields were present prevented from validating the form and really save the modification

### In creation:
- All fields are correctly prefilled so the only error you should have when creating a new product is the missing default name (if absent of course)
- Now when you switch the type in creation you get a modal to forces you to submit the form to confirm this modification (unlike the edition page no extra warning is displayed as it's not useful for an empty/new product)

### Possible impacts
A new extension manages the empty state of some fields, you should check that these fields have correct behaviour even (especially) when left empty or unmodified with zero values:
- Low stock threshold in product and combination form
-`price_tax_excluded` in Supplier form, when a new product supplier is dynamically added with js action it must be prefilled with `0.0` not empty value

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

File: src/PrestaShopBundle/Form/Admin/Extension/DefaultEmptyDataExtension.php [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+
+use PrestaShopBundle\Form\DataTransformer\DefaultEmptyDataTransformer;
+use stdClass;
+use Symfony\Component\Form\AbstractTypeExtension;
+use Symfony\Component\Form\Extension\Core\Type\FormType;
+use Symfony\Component\Form\FormBuilderInterface;
+use Symfony\Component\OptionsResolver\OptionsResolver;
+
+/**
+ * Class DefaultEmptyDataExtension extends every form type with additional default_empty_data option.
```
Comment (matks) [inline src/PrestaShopBundle/Form/Admin/Extension/DefaultEmptyDataExtension.php:39]: I see this class has a connection with DefaultEmptyDataTransformer but I fail to understand exactly the usecase it solves. I am sorry 😅  .

Could it be possible to explain it in the PR body and/or in PHPDoc?

**Review by matks — DISMISSED** [review]
Syntax and logic seems OK but I do not understand DefaultEmptyDataExtension purpose fully (although I understand the raw goal)

File: src/PrestaShopBundle/Form/Admin/Extension/DefaultEmptyDataExtension.php (hunk 1 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Form/Admin/Extension/DefaultEmptyDataExtension.php:39]: The use case is actually explained in details in the `DefaultEmptyDataTransformer` PHPDoc description that was previously added to the branch This extension is only a "shortcut" to use it more easily via the new options that can be used directly in the field definitions

See description of the transformer here https://github.com/PrestaShop/PrestaShop/blob/e4f7c9d0e1afd68dbf3ecc118713b3e88a869a2a/src/PrestaShopBundle/Form/DataTransformer/DefaultEmptyDataTransformer.php#L33 It brings feature that is not available with the existing options from Symfony (empty_data does not behave as we could expect ^^)

Do you think it's still worth describing it all in this PR's description?

Comment (matks) [reply src/PrestaShopBundle/Form/Admin/Extension/DefaultEmptyDataExtension.php:39]: Now I understand, but DefaultEmptyDataTransformer is still hard to grasp when you dont know the context.

It's not because DefaultEmptyDataTransformer phpDoc is not good, it's because the topic is complex ;)

No need to modify the PR body

**Comment by sarahdib** [comment]
@jolelievre 
When I switch from product with combinaison to another type there is an error
Capture d’écran 2021-04-30 à 18 38 49

If I select the type of product before adding the product name there is an error message (maybe is wanted) : (https://drive.google.com/file/d/19fA_PsaG7fUfEti2MSiyO1U1TtVHAfR5/view

**Comment by jolelievre** [comment]
Hi @sarahdib about the error message with missing name it is on purpose indeed Regardless of the product type the minimum info for a product is always to have at least a name (in default language)

About the other bug you mentioned can you give me more details, please? I thought I had already fixed this bug and I can't reproduce it: https://drive.google.com/file/d/1Hl1YWog0p0FnmrR7kM62yao1l_GiRaHF/view

**Comment by sarahdib** [comment]
@jolelievre I can't reproduce this bug anymore but there is a new one : https://drive.google.com/file/d/1dZ_fDO0aA6aRVcGafiG8DjA99QJKlTDP/view 
If you change the product type, confirm and click on the save button the change is not applied

**Comment by jolelievre** [comment]
@sarahdib I fixed the last bug by disabling the save button when we validate the type change

File: admin-dev/themes/new-theme/js/pages/product/edit/product-type-manager.js [hunk 2]
```diff
@@ -51,22 +52,25 @@ export default class ProductTypeManager {
...
+        case ProductMap.productType.PACK:
+          confirmWarning = this.$typeSelector.data('pack-warning');
+          break;
+        case ProductMap.productType.VIRTUAL:
+          confirmWarning = this.$typeSelector.data('virtual-warning');
+          break;
+        case ProductMap.productType.STANDARD:
+        default:
+          confirmWarning = '';
+          break;
```
Comment (Progi1984) [inline admin-dev/themes/new-theme/js/pages/product/edit/product-type-manager.js:72]:
```suggestion
```

**Review by Progi1984 — COMMENTED** [review]
A small request

**Review by Progi1984 — APPROVED** [review]

File: admin-dev/themes/new-theme/js/pages/product/edit/product-type-manager.js (hunk 2 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/pages/product/edit/product-type-manager.js:72]: ESLint doesn't accept it, already tried 🤷‍♂️

**Review by matks — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @jolelievre & @sarahdib
