### PR TITLE
Fix gift added/removed when editing order (product quantity/shipping address)

### LINKED ISSUE #22917: BO - Order page - An error is displayed when changing the addresses for the second time
#### Describe the bug

During testing this PR: https://github.com/PrestaShop/PrestaShop/pull/22909
An exception is displayed when changing the Shipping address the second time.
`Could not find the product in cart, meaning Order and Cart are out of sync`

#### Expected behavior

Remove all the gifts (and the cart rules) that do not match the shipping country and the cart rule country restriction.

#### Steps to Reproduce

0. Upload the United states pack
1. Go to BO => Catalog => Discounts page
2. Create a cart rule with a country selection "The United States" with an action "Free gift" 
3. Go to FO > sign in with John DOE, add any product **different from the gift**
4. Continue checkout > in the Address step: select "My address" (United states country) > Place Order
5. In the BO > Orders > Last order Created
6. Try to change the Shipping address to "Mon addresse" (France country) => ok
7. Try to change again the Shipping address to "Mu address" (United States country) => NOK
8. See error
image

1769=> ok: https://drive.google.com/file/d/1olnhZoBnSexUERFT_z4muLwlO7rtY1VF/view?usp=sharing

#### Additional information

* PrestaShop version: 1770, 1771
* PHP version: 7.1

### LINKED ISSUE #23266: BO - Order page - Ajax issue - The Discount Block is not automatically updated when updating / adding a product
#### Describe the bug

In the BO > Orders page > Order details page > when we update the quantity of the product => the discount value is not automatically updated 
We should refresh the page to be ok

#### Steps to Reproduce

1. Create a cart rule with free shipping
2. In the BO > Shipping > Carriers page > Enable `My cheap carrier`
3. Go to FO > Add `demo_5` (The adventure begins Framed poster) to the cart 
4. Apply the discount
4. Continue checkout
5. In the Shipping method step > select `My cheap carrier` > Place Order
6. Go to BO > Orders > Last order created 
7. Increase the quantity of the product to `2`
8. Save
9. See the error: the discount value is not updated => it is `-€6` instead of `-€3.60`
10. If you refresh the page => ok
**Screenshots**

PS1771 => ok https://drive.google.com/file/d/18Dh8cqrEjl62GOJM-6VOr2niJPdp-dDw/view?usp=sharing
PS1772build1 => NOK https://drive.google.com/file/d/1p9RJjiPty8Z1mD0XASM-gEdrivrn08mo/view?usp=sharing 

#### Additional information

* PrestaShop version: 1772build1
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | When editing the shipping address of an order or changing the quantity of a product in an order, cart rules are recalculated and the cart related to the order was updated but not the order leading to an out of sync error when free gifts were added/deleted from the cart. This PR aims to fix it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #22917 & #23266
| How to test?      | See #22917 for shipping address related gift and try also the following:<br>1. Create a cart rule that offers a free gift after a certain amount is reached<br>2. In the FO, add a product (different from the gift) to the cart, update its quantity to reach the cart rule threshold and have the free gift in the cart<br>3. Finish the order<br>4. In the BO, edit that order by decreasing the quantity of the product added to 1<br>5. The free gift should have been removed from the order<br>6. Try incrementing the quantity back to reach the threshold<br>7. The free gift should be back in the order
| Possible impacts? | /

📓 BC Break :

- The constructor of the file `src/Adapter/Order/OrderAmountUpdater.php` has a new parameter (the 4th): `PrestaShop\PrestaShop\Adapter\Order\Refund\OrderProductRemover $orderProductRemover`

- `CartProductsComparator::getUpdatedProducts()`, `CartProductsComparator::getAdditionalProducts()` & `CartProductsComparator::getModifiedProducts()` don't take any parameter anymore. You should use `CartProductsComparator::setKnownUpdates()` instead.
- The constructor of the file `src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php` has 2 new parameters (3rd & 4th): `PrestaShop\PrestaShop\Adapter\ContextStateManager $contextStateManager ` & `PrestaShop\PrestaShop\Adapter\Order\OrderProductQuantityUpdater $orderProductQuantityUpdater`
- `OrderProductRemover::deleteProductFromOrder()` now returns a `CartProductsComparator` instead of an `array`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23138)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/view/order-discounts-refresher.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export default class OrderDiscountsRefresher {
   }
 
   refresh(orderId) {
-    $.getJSON(this.router.generate('admin_orders_get_discounts', {orderId}))
+    $.ajax(this.router.generate('admin_orders_get_discounts', {orderId}))
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/pages/order/view/order-discounts-refresher.js:37]: What is the reason behind this. The result is no more a json? :thinking:

Comment (atomiix) [reply admin-dev/themes/new-theme/js/pages/order/view/order-discounts-refresher.js:37]: @PierreRambaud it never was actually! If you check [2 lines further](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/admin-dev/themes/new-theme/js/pages/order/view/order-discounts-refresher.js#L39), you can see that we are using `replaceWith(response)` directly.

Comment (PierreRambaud) [reply admin-dev/themes/new-theme/js/pages/order/view/order-discounts-refresher.js:37]: trololololo

**Review by PierreRambaud — DISMISSED** [review]

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 2]
```diff
@@ -149,6 +165,92 @@ public function update(
...
+     *
+     * @param CartProductUpdate[] $modifiedProducts
+     * @param Cart $cart
+     * @param Order $order
+     *
+     * @throws OrderException
+     * @throws PrestaShopDatabaseException
+     * @throws PrestaShopException
+     */
+    private function updateOrderModifiedProducts(array $modifiedProducts, Cart $cart, Order $order)
```
Comment (Progi1984) [inline src/Adapter/Order/OrderAmountUpdater.php]:
```suggestion
    private function updateOrderModifiedProducts(array $modifiedProducts, Cart $cart, Order $order): void
```

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 3]
```diff
@@ -129,9 +140,14 @@ public function update(
             // Update order details (if quantity or product price have been modified)
             $this->updateOrderDetails($order, $cart);
 
+            $productsComparator = new CartProductsComparator($cart);
             // Recalculate cart rules and Fix differences between cart's cartRules and order's cartRules
             $this->updateOrderCartRules($order, $cart, $computingPrecision, $orderInvoiceId);
 
+            // synchronize modified products with the order
```
Comment (Progi1984) [inline src/Adapter/Order/OrderAmountUpdater.php]:
```suggestion
            // Synchronize modified products with the order
```

**Review by Progi1984 — COMMENTED** [review]
Small feedback but good job

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Order/OrderProductQuantityUpdater.php [hunk 4]
```diff
@@ -223,8 +224,26 @@ private function applyOtherProductUpdates(
...
+                foreach ($cart->getProducts() as $product) {
+                    if ((int) $product['id_product'] === $updatedProduct->getProductId()->getValue()
+                        && (int) $product['id_product_attribute'] === $updatedCombinationId) {
+                        $productsToAdd[] = $product;
+                        break;
+                    }
+                }
             }
         }
+        if (count($productsToAdd) > 0) {
```
Comment (matthieu-rolland) [inline src/Adapter/Order/OrderProductQuantityUpdater.php:256]: maybe adding a comment here about why this is needed would be helpful for future developers stumbling on this code 👍

**Comment by eternoendless** [comment]
Don't forget to label PRs that include BC breaks (a feature to add to Prestonbot BTW)

**Review by matks — DISMISSED** [review]
Code is good enough for me. I see @matthieu-rolland provided a not-blocking comment also 😉

**Comment by Progi1984** [comment]
> Don't forget to label PRs that include BC breaks (a feature to add to Prestonbot BTW)

It seems :heavy_check_mark:  : https://github.com/PrestaShop/prestonbot/issues/108 (ping @atomiix )

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

I found some issues following these steps:

1. Create a cart rule "free gift" after a certain amount is reached
1.1 Minimum amount = 50 Euro Tax included Shipping included 
image
1.2 Free gift demo_12 
image
2. Go to FO > Sign in with John Doe 
3. Add demo_6 to the cart = 34.80 euro tax included
4. Add demo_18 to the cart = 10.80 euro tax inluded
5. Go to checkout 
6. In the Shipping method => select "My carrier"  = 8.40 euro
7. Place the order
8. Go to BO > Orders > Last order created
9. Delete the gifted product 
image
10. Try to edit the carrier 
image
11. Select another carrier or update the tracking number
12. see the error 
image

Also, I found that the cart rule that offers a free gift after a certain amount is reached,  In the BO, edit that order by updating the "`price`" of the ordered products => NOK

1. Create a cart rule "free gift" after a certain amount is reached
1.1 Minimum amount = 50 Euro Tax included Shipping included 
image
1.2 Free gift demo_12 
image
2. Go to FO > Sign in with John Doe 
3. Add demo_6 to the cart = 34.80 euro tax included with quantity = 2
4. Go to checkout 
6. In the Shipping method => select free carrier
7. Place the order
8. Go to BO > Orders > Last order created 
image
9. Edit the price of the ordered product to 17.40 euro 
image
10. Save 
11. See error > the gift is not removed

=> This issue should be fixed with this PR?

Thank you!

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 5]
```diff
@@ -129,9 +140,14 @@ public function update(
             // Update order details (if quantity or product price have been modified)
             $this->updateOrderDetails($order, $cart);
 
+            $productsComparator = new CartProductsComparator($cart);
```
Comment (Progi1984) [inline src/Adapter/Order/OrderAmountUpdater.php:142]: Could you add it to constructor please ?

**Review by Progi1984 — COMMENTED** [review]
Two feedbacks : one from me & one from @matthieu-rolland

File: src/Adapter/Order/OrderAmountUpdater.php (hunk 5 above)
Comment (atomiix) [reply src/Adapter/Order/OrderAmountUpdater.php:142]: I don't think I can, I need to call this with the `$cart` state as is it at that time.

File: src/Adapter/Order/OrderProductQuantityUpdater.php (hunk 4 above)
Comment (atomiix) [reply src/Adapter/Order/OrderProductQuantityUpdater.php:256]: @matthieu-rolland I thought that comments [here](https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/Adapter/Order/OrderProductQuantityUpdater.php#L201-L202) were enough

File: src/Adapter/Order/OrderAmountUpdater.php (hunk 5 above)
Comment (PierreRambaud) [reply src/Adapter/Order/OrderAmountUpdater.php:142]: Not a good idea because it depends on the Cart, and this one is a method parameter :)

File: src/Adapter/Order/OrderProductQuantityUpdater.php [hunk 6]
```diff
@@ -177,15 +178,52 @@ private function updateOrderDetail(
...
     }
 
+    /**
+     * @param Cart $cart
+     * @param OrderDetail $orderDetail
+     *
+     * @throws \PrestaShopDatabaseException
+     * @throws \PrestaShopException
+     */
+    private function setSpecificPriceIfNeeded(Cart $cart, OrderDetail $orderDetail)
```
Comment (jolelievre) [inline src/Adapter/Order/OrderProductQuantityUpdater.php]: We don't use specific price any more to customize the order detail prices Instead you should only rely on OrderDetail, you can use the `OrderDetailUpdater` service, if needed, to help you with that

File: src/Adapter/Order/OrderProductQuantityUpdater.php [hunk 7]
```diff
@@ -177,15 +178,52 @@ private function updateOrderDetail(
 
             // Update quantity on the cart and stock
             if ($updateCart) {
-                $updatedProducts = $this->updateProductQuantity($cart, $orderDetail, $oldQuantity, $newQuantity);
-                $this->applyOtherProductUpdates($order, $cart, $orderInvoice, $updatedProducts);
+                $this->setSpecificPriceIfNeeded($cart, $orderDetail);
```
Comment (jolelievre) [inline src/Adapter/Order/OrderProductQuantityUpdater.php]: Why does the price need to be updated in this case? If the price was changed it's supposed to be reflected in the OrderDetail

File: src/Adapter/Order/OrderProductQuantityUpdater.php [hunk 8]
```diff
@@ -223,8 +262,26 @@ private function applyOtherProductUpdates(
                     $orderInvoice,
                     false
                 );
+            } else {
+                foreach ($cart->getProducts() as $product) {
```
Comment (jolelievre) [inline src/Adapter/Order/OrderProductQuantityUpdater.php]: I think you can simplify here and use `$updatedProduct->isCreated()` to no if it's a creation straight away, rather than searching an OrderDetail which, logically, cannot be present

File: src/Adapter/Order/OrderProductQuantityUpdater.php [hunk 9]
```diff
@@ -177,15 +178,52 @@ private function updateOrderDetail(
 
             // Update quantity on the cart and stock
             if ($updateCart) {
-                $updatedProducts = $this->updateProductQuantity($cart, $orderDetail, $oldQuantity, $newQuantity);
-                $this->applyOtherProductUpdates($order, $cart, $orderInvoice, $updatedProducts);
+                $this->setSpecificPriceIfNeeded($cart, $orderDetail);
+                $modifiedProducts = $this->updateProductQuantity($cart, $orderDetail, $oldQuantity, $newQuantity);
```
Comment (jolelievre) [inline src/Adapter/Order/OrderProductQuantityUpdater.php]: An alternative here since you need to handle both updates and creation could be for the function `updateProductQuantity` to return the cart comparator itself.

This way you can then call `$this->applyOtherProductUpdates($cartComparator->getUpdatedProducts())` and another `$this->applyOrderProductCreations($cartComparator->getAdditionalProducts())` this allows to cleanly split both actions (it was the purpose of these the cart comparator splitting functions).

Comment (jolelievre) [reply src/Adapter/Order/OrderProductQuantityUpdater.php]: Same thing should be done for the OrderProductRemover as well (although I don't understand how removing a product can create another, but anything is possible with CartRules 😅 )

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php [hunk 10]
```diff
@@ -125,6 +125,9 @@ public function addOrderWithTheFollowingDetails($orderReference, TableNode $tabl
         );
 
         SharedStorage::getStorage()->set($orderReference, $orderId->getValue());
+
+        // Once the order is created, the cart in the context should be null
+        Context::getContext()->cart = null;
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: Be careful with this, it can reeeaaally mess with:
- `ContextStateManager` which is used in several handlers
- `ContextMocker` which is used in some behat tests especially for multi shop tests

I don't think the behat features should mess with the context directly

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature [hunk 11]
```diff
@@ -1169,3 +1169,154 @@ Feature: Order from Back Office (BO)
...
+      | Last name        | testLastName                 |
+      | Address          | 36 Avenue des Champs Elysees |
+      | City             | Paris                        |
+      | Country          | France                       |
+      | Postal code      | 75008                        |
+    And I change order "bo_order1" shipping address to "test-customer-france-address"
+    Then order "bo_order1" should have 1 products in total
+    And order "bo_order1" should have 0 invoice
+    And order "bo_order1" should have 0 cart rule
+    And order "bo_order1" should have following details:
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1234]: Maybe add a comment here to explain that Tax is not applied in France

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature [hunk 12]
```diff
@@ -1169,3 +1169,154 @@ Feature: Order from Back Office (BO)
...
+    And I add order "bo_order1" with the following details:
+      | cart                | dummy_cart                 |
+      | message             | test                       |
+      | payment module name | dummy_payment              |
+      | status              | Awaiting bank wire payment |
+    Then order "bo_order1" should have 4 products in total
+    And order "bo_order1" should have 0 invoice
+    And order "bo_order1" should have 1 cart rule
+    And order "bo_order1" should have following details:
+      | total_products           | 49.00 |
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1316]: How comes there is no more tax applied in this scenario, is it because of the french address that was created in the previous one?

If yes, it might be a little problem because then the two scenarios are dependent and can't be launched independently, so maybe the address should be removed at the end of the previous scenario (or you can just reload the DB by adding a `@reset-database-before-scenario` tag on this scenario but it's gonna be longer, and it won't fix potential future scenarios added after)

**Review by jolelievre — CHANGES_REQUESTED** [review]
Some comments on how to make the product updates/creations more logical by using the other methods allowed by the CartComparator

But my main concern is the come back of SpecificPrice 😅  This one brang us nothing but pain and inconsistent behaviour and we struggled to get rid of it in favor of OrderDetail which is supposed to handle this job of price edition (see this PR https://github.com/PrestaShop/PrestaShop/pull/22299)

If you wan to discuss it feel free to "bother" me ^^

File: src/Adapter/Order/OrderProductQuantityUpdater.php (hunk 7 above)
Comment (atomiix) [reply src/Adapter/Order/OrderProductQuantityUpdater.php]: Yep, it is, but not in the cart!

File: src/Adapter/Order/OrderProductQuantityUpdater.php (hunk 6 above)
Comment (atomiix) [reply src/Adapter/Order/OrderProductQuantityUpdater.php]: I'm using specific price to keep the `$cart` in sync because cart rules are calculated from the cart

File: tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php (hunk 10 above)
Comment (atomiix) [reply tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php]: I know, but without that, this PR's tests wouldn't pass. And it make sense because in the real usage, when you make an order, the cart is reset. Do you see another (cleaner) way to do it?

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature (hunk 12 above)
Comment (atomiix) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1316]: It's only because I didn't choose "US" as delivery and invoice address so it should be using a French address instead (not the one created before though)

**Review by NeOMakinG — DISMISSED** [review]
Front-end LGTM

File: src/Adapter/Order/OrderProductQuantityUpdater.php (hunk 6 above)
Comment (jolelievre) [reply src/Adapter/Order/OrderProductQuantityUpdater.php]: If you need to use SpecificPrice then it means something is missing along the workflow because OrderDetail should (and must) be enough That's why in https://github.com/PrestaShop/PrestaShop/pull/22299 an new parameter `$keepOrderPrices` was added, the principal behind this parameter is to get the list of product but their prices are fetched from OrderDetail (if the cart is associated to an order of course)

The parameter was added to several functions as there are many possible use cases:
- `getProducts`
- `getOrderTotal`
- `newCalculator`
- `getPackageShippingCost`
- `applyProductCalculations` (protected)

So relying on OrderDetail and this parameter should be enough, however it's more than possible that:
- it has not been used everywhere it should in the Order handlers/services
- it is still missing in some other Cart methods used during computation

Sorry for being picky about this subject but we struggled so long with SpecificPrices that I don't want them to come back in the game 😅  Although it may seem like a good idea at first it results in way too many buggy behaviour (you can see the number of issues associated to the #222999 PR, and it's only the tip of the iceberg), so it's really worth the effort of not using them.

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature (hunk 12 above)
Comment (jolelievre) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1316]: Oh right there is not this statement `And I select "US" address as delivery and invoice address for customer "testCustomer" in cart "dummy_cart"` in this case

Well unless you really need french address or not taxes for this use case I'd suggest to use the US address as well, because it will use taxed values which ensures that they are correctly computed We've had some bugs related to taxe computing in the past that were not noticed simply because the behat tests didn't handle any tax at all so they remain invisble

File: src/Adapter/Order/OrderProductQuantityUpdater.php (hunk 4 above)
Comment (matthieu-rolland) [reply src/Adapter/Order/OrderProductQuantityUpdater.php:256]: edit: ah yes saw it 👍

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature (hunk 12 above)
Comment (Progi1984) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1316]: Ping @atomiix

Comment (atomiix) [reply tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1316]: It has been done: https://github.com/PrestaShop/PrestaShop/pull/23138/files#diff-c1467f8fb57dcdfe67430f18f463329d2402e127598d9abf04e205feff105165R1270

**Comment by Progi1984** [comment]
@atomiix Could you rebase your PR :( ?

File: src/Adapter/Cart/Comparator/CartProductsComparator.php [hunk 13]
```diff
@@ -55,52 +60,54 @@ public function __construct(Cart $cart)
         $this->savedProducts = $cart->getProducts(true);
     }
 
+    /**
+     * @param array $knownUpdates
+     */
+    public function setKnownUpdates(array $knownUpdates): void
+    {
+        $this->knownUpdates = $knownUpdates;
```
Comment (Progi1984) [inline src/Adapter/Cart/Comparator/CartProductsComparator.php]:
```suggestion
    public function setKnownUpdates(array $knownUpdates): self
    {
        $this->knownUpdates = $knownUpdates;
        
        return $this;
```

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

1. Select (Shipping & Invoice) addresses multiple times => ok
2. Edit existing addresses => ok
3. Edit carrier => ok
4. Edit product quantity => ok
5. Adding a product => ok
6. Removing a product => ok

But updating the product price => NOK

Steps to reproduce the issue:
1. Create a cart rule "free gift" after a certain amount is reached
1.1 Minimum amount = 50 Euro Tax included Shipping included 
image
1.2 Free gift demo_12 
image
2. Go to FO > Sign in with John Doe
3. Add demo_6 to the cart = 34.80 euro tax included with quantity = 2
4. Go to checkout
5. In the Shipping method => select free carrier
6. Place the order
7. Go to BO > Orders > Last order created
8. Edit the price of the ordered product to 17.40 euro 
image
9. Save & refresh the page 
10. See error > the gift is not removed 
image

Thank you!

File: admin-dev/themes/new-theme/js/pages/order/order-shipping-manager.js [hunk 14]
```diff
@@ -27,11 +27,7 @@ import OrderViewPageMap from './OrderViewPageMap';
 const $ = window.$;
 
 export default class OrderShippingManager {
-  constructor() {
-    this._initOrderShippingUpdateEventHandler();
-  }
-
-  _initOrderShippingUpdateEventHandler() {
+  initOrderShippingUpdateEventHandler() {
```
Comment (jolelievre) [inline admin-dev/themes/new-theme/js/pages/order/order-shipping-manager.js]: This could be performed in a constructor only once by using deferred events from jQuery, but it's just a suggestion

```suggestion
  $(OrderViewPageMap.mainDiv).on('click', OrderViewPageMap.showOrderShippingUpdateModalBtn, (event) => {
```

This allows not to init the event each time the DOM is updated

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php [hunk 15]
```diff
@@ -77,14 +103,96 @@ public function handle(ChangeOrderDeliveryAddressCommand $command)
             throw new OrderException('New delivery address is not valid');
         }
 
+        $this->contextStateManager
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php]: Maybe consider using `AbstractOrderCommandHandler::setCartContext` by changing the parent class

Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php]: This whole block must be wrapped in a `try/finally` block So that the context is correctly reset even in case of error Sorry but this one is a must have

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php [hunk 16]
```diff
@@ -51,16 +61,32 @@ final class ChangeOrderDeliveryAddressHandler extends AbstractOrderHandler imple
...
+
+    /**
+     * @var OrderProductQuantityUpdater
+     */
+    private $orderProductQuantityUpdater;
+
     /**
      * @param OrderAmountUpdater $orderAmountUpdater
      * @param OrderDetailUpdater $orderDetailTaxUpdater
+     * @param ContextStateManager $contextStateManager
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php:73]: I know the use case in the issue is only about Delivery address since the cart rule is related to delivery address only But should we have the same thing for `ChangeOrderInvoiceAddressHandler` just to be sure?

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 17]
```diff
@@ -148,6 +164,92 @@ public function update(
...
+    /**
+     * @param CartProductUpdate $productUpdate
+     * @param Cart $cart
+     *
+     * @return array|null
+     */
+    private function findProductInCart(CartProductUpdate $productUpdate, Cart $cart): ?array
+    {
+        foreach ($cart->getProducts() as $product) {
+            $combinationId = null === $productUpdate->getCombinationId()
```
Comment (jolelievre) [inline src/Adapter/Order/OrderAmountUpdater.php]: This should be done outside of the loop

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 18]
```diff
@@ -148,6 +164,92 @@ public function update(
...
+    /**
+     * @param CartProductUpdate $productUpdate
+     * @param Order $order
+     *
+     * @return array|null
+     */
+    private function findProductInOrder(CartProductUpdate $productUpdate, Order $order): ?array
+    {
+        foreach ($order->getProducts() as $product) {
+            $combinationId = null === $productUpdate->getCombinationId()
```
Comment (jolelievre) [inline src/Adapter/Order/OrderAmountUpdater.php]: SAme here this can be done right before the loop

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature [hunk 19]
```diff
@@ -1169,3 +1169,156 @@ Feature: Order from Back Office (BO)
...
+    And I add 1 products "Product 12345" to the cart "dummy_cart"
+    And I add order "bo_order1" with the following details:
+      | cart                | dummy_cart                 |
+      | message             | test                       |
+      | payment module name | dummy_payment              |
+      | status              | Awaiting bank wire payment |
+    Then order "bo_order1" should have 2 products in total
+    And order "bo_order1" should have 0 invoice
+    And order "bo_order1" should have 1 cart rule
+    And order "bo_order1" should have following details:
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1197]: More often than not, sadly 😅 , the order totals are correct but not the OrderDetails So since this use case is quite complex it might be interesting to add two steps to validate each Order product's details

File: tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature [hunk 20]
```diff
@@ -1169,3 +1169,156 @@ Feature: Order from Back Office (BO)
...
+    And I add 3 products "Product 12345" to the cart "dummy_cart"
+    And I add order "bo_order1" with the following details:
+      | cart                | dummy_cart                 |
+      | message             | test                       |
+      | payment module name | dummy_payment              |
+      | status              | Awaiting bank wire payment |
+    Then order "bo_order1" should have 4 products in total
+    And order "bo_order1" should have 0 invoice
+    And order "bo_order1" should have 1 cart rule
+    And order "bo_order1" should have following details:
```
Comment (jolelievre) [inline tests/Integration/Behaviour/Features/Scenario/Order/order_gift_cart_rule.feature:1315]: Same comment for this one it might be interesting checking the details of OrderDetails

**Review by jolelievre — COMMENTED** [review]
Most of the comments are suggestion

However at least one is mandatory add a try/catch/finally block when using the context state manager in the address handler

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php (hunk 16 above)
Comment (atomiix) [reply src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php:73]: I don't think we should do the same thing for `ChangeOrderInvoiceAddressHandler` as we do not recalculate cart rules when changing the invoice address

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php:73]: We do recompute the cart rules amounts in case the address changes its country and tax are related to the invoice address But it shouldn't impact the gifts indeed And the context state manager is already handled internally by `orderAmountUpdater` and `orderDetailTaxUpdater`
So you're right it should be good

**Review by jolelievre — DISMISSED** [review]
Great work!

**Comment by jolelievre** [comment]
Ok, so in fact as we discussed changing the tax country could have an impact. Here is the use case:

- Gift cart rule when price TTC > 50€
- tax country is based on invoice address
- change the invoice address which impacts the price TTC which becomes the same as HT
- the cart total is no longer > 50
- the gift is removed

But I'd say it's worth handling it in another issue and PR.

File: src/Adapter/Order/Refund/OrderProductRemover.php [hunk 21]
```diff
@@ -95,18 +98,19 @@ public function deleteProductFromOrder(Order $order, OrderDetail $orderDetail, b
...
-     * @return CartProductUpdate[]
+     * @param CartProductsComparator $cartComparator
      */
-    private function updateCart(Cart $cart, OrderDetail $orderDetail): array
-    {
-        $cartComparator = new CartProductsComparator($cart);
+    private function updateCart(
+        Cart $cart,
+        OrderDetail $orderDetail,
+        CartProductsComparator &$cartComparator
```
Comment (Progi1984) [inline src/Adapter/Order/Refund/OrderProductRemover.php]: Really need a reference ? Why not define a property in class ?

**Review by Progi1984 — COMMENTED** [review]
A small comment

File: src/Adapter/Order/Refund/OrderProductRemover.php [hunk 22]
```diff
@@ -95,18 +103,18 @@ public function deleteProductFromOrder(Order $order, OrderDetail $orderDetail, b
...
-        return $updatedProducts;
+        return $this->cartProductComparator;
     }
 
     /**
      * @param Cart $cart
      * @param OrderDetail $orderDetail
-     *
-     * @return CartProductUpdate[]
+     * @param CartProductsComparator $cartComparator
```
Comment (Progi1984) [inline src/Adapter/Order/Refund/OrderProductRemover.php]:
```suggestion
```

**Review by Progi1984 — COMMENTED** [review]
A last comment

**Review by Progi1984 — DISMISSED** [review]

File: src/Adapter/Order/Refund/OrderProductRemover.php (hunk 21 above)
Comment (PierreRambaud) [reply src/Adapter/Order/Refund/OrderProductRemover.php]: In fact, all objects are passed by references in PHP, you don't have to use object property nor `&` :wink:

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

1. https://github.com/PrestaShop/PrestaShop/issues/23266 + https://github.com/PrestaShop/PrestaShop/issues/22917 => ok
2. https://drive.google.com/file/d/1wK4gRwnIC9dKPKNyOguwxNT2saQ606n_/view?usp=sharing
3. Select (Shipping & Invoice) addresses multiple times => ok
4. Edit existing addresses => ok
5. Edit carrier => ok
6. Edit product quantity => ok
7. Adding a product without updating price => ok
8. Removing a product => ok
9. Updating the product price to remove the discount => Ok
10. Updating the product price to add the discount => NOk
```
Steps to reproduce the issue:

- Create a cart rule "free gift" after a certain amount is reached
- 1.1 Minimum amount = 50 Euro Tax included Shipping included
- 1.2 Free gift demo_12
- Go to FO > Sign in with John Doe
- Add demo_6 to the cart = 34.80 euro tax included with quantity = 1
- Go to checkout
- In the Shipping method => select free carrier
- Place the order
- Go to BO > Orders > Last order created
- Edit the price of the ordered product to 100 euro
- Save & refresh the page
- See error > the gift is not added
```
https://drive.google.com/file/d/14s2WfEI60ovsd4Gj1BlzRIXeF2_pdrKm/view?usp=sharing
11. Add a product while updating the price => NOK
```
Steps to reproduce the issue:

- Create a cart rule "free gift" after a certain amount is reached
- 1.1 Minimum amount = 50 Euro Tax included Shipping included
- 1.2 Free gift demo_12
- Go to FO > Sign in with John Doe
- Add demo_6 to the cart = 34.80 euro tax included with quantity = 1
- Go to checkout
- In the Shipping method => select free carrier
- Place the order
- Go to BO > Orders > Last order created
- Add `demo_19` with updating the price to 100 euro
- Click on "Add" & refresh the page
- See error > the gift is not added
```
https://drive.google.com/file/d/1xnnBvQIXc3P1czMi3BnCpcjrfSk6P9Lt/view?usp=sharing

Ping @atomiix @jolelievre, about this issue: https://github.com/PrestaShop/PrestaShop/pull/23138#issuecomment-823365166
I manage to reproduce with PS1769 and 177x(it is not a regression)


Thank you!

**Review by PierreRambaud — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php [hunk 23]
```diff
@@ -77,14 +99,91 @@ public function handle(ChangeOrderDeliveryAddressCommand $command)
...
+     * @param Order $order
+     * @param Cart $cart
+     * @param CartProductsComparator $productsComparator
+     */
+    private function synchronizeOrderWithCart(
+        Order $order,
+        Cart $cart,
+        CartProductsComparator $productsComparator
+    ): void {
+        $modified = $productsComparator->getModifiedProducts();
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php:134]: don't need a varibale. Not blocking

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php [hunk 24]
```diff
@@ -77,14 +99,91 @@ public function handle(ChangeOrderDeliveryAddressCommand $command)
...
+     * @param CartProductUpdate $productUpdate
+     * @param Order $order
+     * @param Cart $cart
+     *
+     * @return OrderDetail|null
+     */
+    private function getOrderDetail(CartProductUpdate $productUpdate, Order $order, Cart $cart): ?OrderDetail
+    {
+        foreach ($order->getProducts() as $product) {
+            $combinationId = $productUpdate->getCombinationId() ? $productUpdate->getCombinationId()->getValue() : 0;
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php]: combinationId can be get just once, out of the "foreaches"

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php [hunk 25]
```diff
@@ -77,14 +99,91 @@ public function handle(ChangeOrderDeliveryAddressCommand $command)
...
+            }
+        }
+
+        foreach ($cart->getProducts() as $product) {
+            $combinationId = $productUpdate->getCombinationId() ? $productUpdate->getCombinationId()->getValue() : 0;
+            if (
+                (int) $product['id_product'] === $productUpdate->getProductId()->getValue()
+                && (int) $product['id_product_attribute'] === $combinationId
+            ) {
+                $orderDetail = new OrderDetail();
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php:179]: Maybe I'm wrong. But here you create an orderDetail for the product without checking if it already exists

File: src/Adapter/Order/OrderAmountUpdater.php [hunk 26]
```diff
@@ -148,6 +164,92 @@ public function update(
...
+     *
+     * @throws OrderException
+     * @throws PrestaShopDatabaseException
+     * @throws PrestaShopException
+     */
+    private function updateOrderModifiedProducts(array $modifiedProducts, Cart $cart, Order $order): void
+    {
+        $productsToAddToOrder = [];
+        foreach ($modifiedProducts as $modifiedProduct) {
+            if (null === $this->findProductInCart($modifiedProduct, $cart)) {
```
Comment (sowbiba) [inline src/Adapter/Order/OrderAmountUpdater.php]: In this foreach, probably you will call `findProductInCart` and `findProductInOrder` multiple times. Why not calling them just once and set them into variables?

**Review by sowbiba — COMMENTED** [review]
Good job !! Some suggestions

File: src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php (hunk 25 above)
Comment (atomiix) [reply src/Adapter/Order/CommandHandler/ChangeOrderDeliveryAddressHandler.php:179]: If it was existing it would have been returned in the first `foreach` of this function ;)

File: classes/CartRule.php [hunk 27]
```diff
@@ -625,10 +625,12 @@ public function getProductRules($id_product_rule_group)
      * @param Context $context Context instance
      * @param bool $alreadyInCart Check if the voucher is already on the cart
      * @param bool $display_error Display error
+     * @param bool $check_carrier
+     * @param bool $useOrderPrices
      *
      * @return bool|mixed|string
      */
-    public function checkValidity(Context $context, $alreadyInCart = false, $display_error = true, $check_carrier = true)
+    public function checkValidity(Context $context, $alreadyInCart = false, $display_error = true, $check_carrier = true, $useOrderPrices = false)
```
Comment (Progi1984) [inline classes/CartRule.php:633]:
```suggestion
    public function checkValidity(Context $context, $alreadyInCart = false, $display_error = true, $check_carrier = true, bool $useOrderPrices = false)
```

File: classes/Cart.php [hunk 28]
```diff
@@ -472,10 +472,11 @@ public function getAverageProductsTaxRate(&$cartAmountTaxExcluded = null, &$cart
      *                    - FILTER_ACTION_GIFT
      *                    - FILTER_ACTION_ALL_NOCAP
      * @param bool $autoAdd automaticaly adds cart ruls without code to cart
+     * @param bool $useOrderPrices
      *
      * @return array|false|mysqli_result|PDOStatement|resource|null Database result
      */
-    public function getCartRules($filter = CartRule::FILTER_ACTION_ALL, $autoAdd = true)
+    public function getCartRules($filter = CartRule::FILTER_ACTION_ALL, $autoAdd = true, $useOrderPrices = false)
```
Comment (Progi1984) [inline classes/Cart.php:479]:
```suggestion
    public function getCartRules($filter = CartRule::FILTER_ACTION_ALL, $autoAdd = true, bool $useOrderPrices = false)
```

**Review by sowbiba — COMMENTED** [review]
LGTM ! Waiting for the feedbacks from @Progi1984 ;)

**Review by Progi1984 — COMMENTED** [review]
Two small feedbacks and it's good

**Review by sowbiba — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

There are some Conflicting files.

Thank you!

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix 

It is ok :heavy_check_mark: 

1. #23266 => ok
2. #22917 => ok (Shipping + Invoice: Select Another address + Edit address multiple times)
3. Edit carrier => ok
4. Edit product quantity => ok
5. Adding a product without updating price => ok
6. Removing a product => ok
7. Updating the product price to remove the discount => Ok
8. Updating the product price to add the discount => Ok
9. Add a product while updating the price => OK

https://drive.google.com/file/d/12z_M85ONjuOKuoTNPHT8VeuIA64jWa9Z/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @atomiix & @khouloudbelguith
