### PR TITLE
Wrong prices in edit order with secondary currency

### LINKED ISSUE #12521: Error total count in order edit PS 1.7.5
I have store with USD default currency, but many orders are made by customers in UAH. If you try to edit the price / add / remove goods in the admin panel, you get absolutely incorrect sum total.

1. Create store with at least two currencies
2. Place your order in a non-default currency
3. Try admin panel to add product to order.

>Edit by Khouloud: https://github.com/PrestaShop/PrestaShop/issues/16937

If you change status of the order to "Payment accepted", consult the invoice: The sums in the invoice are wrong too (but currency sign is OK)

**Screenshots**
https://prnt.sc/minwqu

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 5.5

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixes total price error when adding a product to an order with secondary currency (not default one)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12521
| How to test?  | <ul><li>Add a secondary currency to the shop</li><li>Create an order using this secondary currency</li><li>Go to admin and add a product to the order</li><li>Result : The total price is incorrect</li></ul>

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17927)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@sowbiba You are fixing the legacy controller that we are going to delete soon 😄

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 1]
```diff
@@ -87,130 +96,142 @@ public function handle(AddProductToOrderCommand $command)
...
-        } else {
-            $oldCartRules = [];
-        }
+        $this->contextStateManager
+            ->setCurrency(new Currency($order->id_currency))
+        ;
 
-        $this->assertOrderWasNotShipped($order);
+        try {
+            if ($this->context->cart !== null) {
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: I feels weird to use the context cart, I guess it comes from the legacy controller

Isn't it possible to get the cart from the order instead? And it could be overridden in the context like the Currency is with the `contextStateManager`

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 2]
```diff
@@ -87,130 +96,142 @@ public function handle(AddProductToOrderCommand $command)
     {
         $order = $this->getOrderObject($command->getOrderId());
 
-        if ($this->context->cart !== null) {
-            $oldCartRules = $this->context->cart->getCartRules();
-        } else {
-            $oldCartRules = [];
-        }
+        $this->contextStateManager
+            ->setCurrency(new Currency($order->id_currency))
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: It might be safer to override the customer as well Some operation rely on it, like getting the customer address which in turn allows to get the tax included/excluded parameter

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig [hunk 3]
```diff
@@ -28,7 +28,7 @@
     {{ form_row(addProductRowForm.product_id) }}
     {{ form_row(addProductRowForm.tax_rate) }}
     {{ form_label(addProductRowForm.search) }}
-    {{ form_widget(addProductRowForm.search) }}
+    {{ form_widget(addProductRowForm.search, { 'attr': {'data-currency': orderForViewing.currencyId }}) }}
```
Comment (PululuK) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: Hi @sowbiba 

Thank you ... !

You should inject this data in the controller when creating the form rather than in the template (`in PrestaShopBundle\Controller\Admin\Sell\Order::viewAction`)
See : https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php#L412

We talked about it with @jolelievre  a few weeks ago, I don't know if this case is concerned. The idea is to keep consistency.

WDYF @jolelievre  ?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 4]
```diff
@@ -87,130 +96,142 @@ public function handle(AddProductToOrderCommand $command)
...
+                $order->total_discounts += $orderCartRule->value;
+                $order->total_discounts_tax_incl += $orderCartRule->value;
+                $order->total_discounts_tax_excl += $orderCartRule->value_tax_excl;
+                $order->total_paid -= $orderCartRule->value;
+                $order->total_paid_tax_incl -= $orderCartRule->value;
+                $order->total_paid_tax_excl -= $orderCartRule->value_tax_excl;
+            }
+
+            $order->update();
+        } catch (\Exception $e) {
```
Comment (jolelievre) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Please add a `use Exception;` instead of the `\` notation

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig (hunk 3 above)
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: Could you add this in the `AddProductRowType` instead?
In the next version (and a little in this one) we are trying to fully fill the form types in order to simplify the twig template with a simple `from_widget(addProductRowForm)` but this requires to correctly create the form beforehand

In `OrderController::viewAction` when the form is created you can inject the currency id as an option, which will then allow you to add this field on the `search` form field Of course what you did works and we may improve it later, but if it's not too long to do it now it will save us a bit of time later

**Review by jolelievre — COMMENTED** [review]
Nice @sowbiba It's reassuring to see it works ^^
I have a few feedback, and I was wondering if there are any behat tests for this feature?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig (hunk 3 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: I actually made the same feedback in my review ^^

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 5]
```diff
@@ -87,130 +97,143 @@ public function handle(AddProductToOrderCommand $command)
...
+                !empty($invoice->id) ? $invoice->id : 0
+            );
 
-        $order->total_paid += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
-        $order->total_paid_tax_excl += Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $order->total_paid_tax_incl += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+            // update totals amount of order
+            // @todo: use https://github.com/PrestaShop/decimal for prices computations
+            $order->total_products += (float) $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS);
+            $order->total_products_wt += Tools::ps_round((float) $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS), 2);
```
Comment (sowbiba) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Fixes #17976

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig (hunk 3 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: Fixed. Thanks @PululuK and @jolelievre

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 1 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Done

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 2 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Done

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 4 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Done

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig (hunk 3 above)
Comment (sowbiba) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/add_product_row.html.twig]: Done

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 1 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Done

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 6]
```diff
@@ -87,130 +97,139 @@ public function handle(AddProductToOrderCommand $command)
...
+            ->setCustomer(new Customer($order->id_customer))
+        ;
 
-        $this->assertOrderWasNotShipped($order);
+        try {
+            $oldCartRules = (new Cart($order->id_cart))->getCartRules();
 
-        $product = $this->getProductObject($command->getProductId(), (int) $order->id_lang);
-        $combination = $this->getCombination($command->getCombinationId());
+            $this->assertOrderWasNotShipped($order);
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: May be you can up this before $oldCartRules.

That permit to not assign value to variables if order was not shipped.

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 7]
```diff
@@ -87,130 +97,139 @@ public function handle(AddProductToOrderCommand $command)
...
+                $cart->getProducts(),
+                !empty($invoice->id) ? $invoice->id : 0
+            );
 
-        $order->total_paid += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
-        $order->total_paid_tax_excl += Tools::ps_round((float) $cart->getOrderTotal(false, $totalMethod), 2);
-        $order->total_paid_tax_incl += Tools::ps_round((float) $cart->getOrderTotal(true, $totalMethod), 2);
+            // update totals amount of order
+            // @todo: use https://github.com/PrestaShop/decimal for prices computations
+            $order->total_products += (float) $cart->getOrderTotal(false, Cart::ONLY_PRODUCTS);
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Why not round `total_products` ?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 8]
```diff
@@ -87,130 +97,139 @@ public function handle(AddProductToOrderCommand $command)
...
-        if (!empty($newCartRules) && !empty($oldCartRules)) {
-            $result = array_diff($newCartRules, $oldCartRules);
-        } else {
-            $result = [];
-        }
+            if (!empty($newCartRules) && !empty($oldCartRules)) {
+                $result = array_diff($newCartRules, $oldCartRules);
+            } else {
+                $result = [];
+            }
```
Comment (Progi1984) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]:
```suggestion
            $result = (!empty($newCartRules) && !empty($oldCartRules)) ? array_diff($newCartRules, $oldCartRules) : [];
```

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 7 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: For the `total_products_wt` I noticed a bug #17976 but there are some other prices that are not rounded. I don't want to round them all and introduce myself a bug

Maybe an advice from @eternoendless @matks @jolelievre ... @PrestaShop/prestashop-core-developers  ?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 6 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: done

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 8 above)
Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: done

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js [hunk 9]
```diff
@@ -44,12 +44,17 @@ export default class OrderProductAutocomplete {
       event.stopImmediatePropagation();
       this.updateResults(this.results);
     });
-    this.input.on('keyup', event => this.search(event.target.value));
+    this.input.on('keyup', event => this.search(event.target.value, $(event.target).data('currency')));
```
Comment (atomiix) [inline admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js]: Shouldn't we be using `$(event.currentTarget)` instead of `$(event.target)` ?

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 7 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: This is very weird, and seems like a quick fix that blow up later.. Why round only with taxes? This may work with the values you tried but t doesn't it'll work in every cases
I know it's a very difficult topic, and I'd say it needs to be dealt with in a dedicated PR, and in a transversal way in all handlers Not just this one, and just on this value..

Comment (sowbiba) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: If I understand well, you mean that fixing that may pop other bugs in other cases ?

And we need to refactor the rounding process everywhere at once ?

File: admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js (hunk 9 above)
Comment (sowbiba) [reply admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js]: done ;)

**Review by Progi1984 — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]
JS Looks fine for me

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 7 above)
Comment (Progi1984) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: @jolelievre Ping

**Review by jolelievre — DISMISSED** [review]
Thanks @sowbiba

**Review by Progi1984 — DISMISSED** [review]

**Comment by boubkerbribri** [comment]
@sowbiba please resolve conflicts

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@sowbiba Travis is :red_circle:

File: controllers/admin/AdminOrdersController.php [hunk 10]
```diff
@@ -178,6 +178,7 @@ public function __construct()
             $order = new Order((int) Tools::getValue('id_order'));
             $this->context->cart = new Cart($order->id_cart);
             $this->context->customer = new Customer($order->id_customer);
+            $this->context->currency = new Currency($order->id_currency);
```
Comment (matks) [inline controllers/admin/AdminOrdersController.php:181]: This line modifies the legacy Orders controller. Does this mean you fixed the issue in both legacy and migrated pages ?

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 11]
```diff
@@ -89,132 +99,137 @@ public function handle(AddProductToOrderCommand $command)
...
-            $orderCartRule->add();
-
-            // @todo: use https://github.com/PrestaShop/decimal
-            $order->total_discounts += $orderCartRule->value;
-            $order->total_discounts_tax_incl += $orderCartRule->value;
-            $order->total_discounts_tax_excl += $orderCartRule->value_tax_excl;
-            $order->total_paid -= $orderCartRule->value;
-            $order->total_paid_tax_incl -= $orderCartRule->value;
-            $order->total_paid_tax_excl -= $orderCartRule->value_tax_excl;
+            throw $e;
```
Comment (matks) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Oh, nice indeed. @jolelievre I guess we should do this in all handlers using ContextStateeManager ?

File: controllers/admin/AdminOrdersController.php (hunk 10 above)
Comment (sowbiba) [reply controllers/admin/AdminOrdersController.php:181]: Yes the fix is done for both controllers

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php [hunk 12]
```diff
@@ -89,132 +99,137 @@ public function handle(AddProductToOrderCommand $command)
...
+                $order->total_paid_tax_excl -= $orderCartRule->value_tax_excl;
+            }
 
-        if (!empty($newCartRules) && !empty($oldCartRules)) {
-            $result = array_diff($newCartRules, $oldCartRules);
-        } else {
-            $result = [];
-        }
+            $order->update();
+        } catch (Exception $e) {
```
Comment (PierreRambaud) [inline src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: The exception is too generic :thinking:

Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Not in that case, the idea is just to:
- catch the exception
- restore the context
- rethrow the exception

So it is voluntary that it's the most generic one

File: src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php (hunk 11 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php]: Yep that's the idea! But we might have missed it in some of them

File: controllers/admin/AdminOrdersController.php (hunk 10 above)
Comment (jolelievre) [reply controllers/admin/AdminOrdersController.php:181]: Even though it will be removed in 177 ^^
But it can be useful for people who would need to patch the legacy controller

**Comment by jolelievre** [comment]
Hi @sowbiba I think this PR is gonna have a lot of conflict with this one https://github.com/PrestaShop/PrestaShop/pull/18205
Because of the modification in `AddProductToOrderHandler` The 18205 already includes some of your modifications but since there are more complex changes I think it's better to wait or it to be merged, so that you can rebase and add your changes after
What do you think?

**Comment by sowbiba** [comment]
> Hi @sowbiba I think this PR is gonna have a lot of conflict with this one #18205
> Because of the modification in `AddProductToOrderHandler` The 18205 already includes some of your modifications but since there are more complex changes I think it's better to wait or it to be merged, so that you can rebase and add your changes after
> What do you think?

I agree. I will wait for that PR to be merged as it is already in QA ;)

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @sowbiba !

I have one question and one remark :

- I cannot reproduce the bug in https://github.com/PrestaShop/PrestaShop/issues/12521 without your PR, so either I'm not doing it well, either I don't know how to test your PR.

How can I reproduce the bug that should be fixed by your PR ?

The remark : Thanks to your PR, I found a new critical bug ! See issue : https://github.com/PrestaShop/PrestaShop/issues/18433

Thanks ! Do not hesitate to ping me if you need more info.

**Comment by sowbiba** [comment]
> Hi @sowbiba !
> 
> I have one question and one remark :
> 
> * I cannot reproduce the bug in #12521 without your PR, so either I'm not doing it well, either I don't know how to test your PR.
> 
> How can I reproduce the bug that should be fixed by your PR ?
> 
> The remark : Thanks to your PR, I found a new critical bug ! See issue : #18433
> 
> Thanks ! Do not hesitate to ping me if you need more info.

The bug was not about the total but the search result. The prices are not converted to secondary currency

https://drive.google.com/file/d/1_a7rHXzjNWiJ4cR5tPCyREuF8vsWx5sr/view

**Comment by Progi1984** [comment]
Thanks @sowbiba

**Comment by ejfarsta** [comment]
I'm not quite sure how to implement the changes as in 1.7.6.8 I don't have most of those files avaliable in FTP ... 
admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
admin-dev/themes/new-theme/public/order_view.bundle.js 
src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php 
src/PrestaShopBundle/Form/Admin/Sell/Order/AddProductRowType.php
What am I missing???

**Comment by PululuK** [comment]
> I'm not quite sure how to implement the changes as in 1.7.6.8 I don't have most of those files avaliable in FTP ...
> admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
> admin-dev/themes/new-theme/public/order_view.bundle.js
> src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
> src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
> src/PrestaShopBundle/Form/Admin/Sell/Order/AddProductRowType.php
> What am I missing???

Hi @ejfarsta 
Maybe it is missing : `controllers/admin/AdminOrdersController.php` ?

**Comment by kpodemski** [comment]
@ejfarsta 

1.7.6.8 and 1.7.7 are completely different when it comes to order management, I'm pretty sure that you need to wait for an upgrade

**Comment by ejfarsta** [comment]
@PululuK actually this is the only file that I have from all the list... I implemented change in this file but it didn't silve the problem, so I believe that I also have to change all others files...but I don't have them ...

**Comment by PululuK** [comment]
Oh, sorry ... In this case see please https://github.com/PrestaShop/PrestaShop/pull/17927#issuecomment-713112081

**Comment by ejfarsta** [comment]
@kpodemski 
> 1.7.6.8 and 1.7.7 are completely different when it comes to order management, I'm pretty sure that you need to wait for an upgrade

I believe so but somehow this pull request merged and marked in all other issues regarding PS 1.7.5 and 1.7.6 as a fix for them ...

**Comment by kpodemski** [comment]
@ejfarsta 

no, no, it's not working like that, it means that this bug has been reproduced on those versions, but it's fixed in 1.7.7

**Comment by ejfarsta** [comment]
Hmmm all of other issues are closed and marked as fix with link to this pull request. But okay... So does it means that I have to upgrade to 1.7.7 to fix the issue ? :/

**Comment by kpodemski** [comment]
Yes, I believe so, and I highly encourage you to do that, there's a lot of good in 1.7.7, really, I think that we need couple weeks more to finish it but it's worth waiting!

> Hmmm all of other issues are closed and marked as fix with link to this pull request

It's just FYI that "hey, we fixed it! you can update software and problem should be gone" 👍

**Comment by ejfarsta** [comment]
> Yes, I believe so, and I highly encourage you to do that, there's a lot of good in 1.7.7, really, I think that we need couple weeks more to finish it but it's worth waiting!

I'm always crying inside a little when I need to upgrade ... it's like walking in mine field ;) 

However, thank you for explaning everything step by step!
