### PR TITLE
Modify test data generation to handle price with taxes

### LINKED ISSUE #12174: Wrong tax in order slip when product tax has changed
**Describe the bug**
When an order slip is created, the current tax rule from the product is used instead of the saved one in the order detail. So when the tax rule has changed since the order was created, a wrong tax is applied to the order slip detail and this also leads to wrong totals in the order slip.

**To Reproduce**

1. Order a product so that you have a valid order with an invoice
1. Change the tax rule of this product in the product admin page so that it has a different tax percentage
1. Refund the product from the order and create an order slip
1. See that tax included values are wrong compared to those in the orginal invoice from this order

**Additionnal information**
PrestaShop version: checked in 1.7.2.1, should also be present in current version

**Fix**
see pull request

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | The test data generated via some fixtures didn't have prices with tax included (they were equal to tax excluded) This was because all products had a tax rule group different rom the customer therefor tax rate was always 0
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Also fixes #12174
| How to test?  | Once all test values are updated to match the tax values all tests must be green The PR was initially only dedicated to improving automatic tests but it ended up also fixing an issue So I guess the issue needs to be validated by QA team

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18023)

### CODE REVIEW

File: install-dev/fixtures/fashion/install.php [hunk 1]
```diff
@@ -60,4 +69,18 @@ public function populateFromXmlFiles()
...
+        $stateId = $this->retrieveId('state', $state);
+        $countryId = $this->retrieveId('country', $country);
+
+        return Db::getInstance()->getValue(
+            '
+		SELECT id_tax_rules_group
+		FROM ' . _DB_PREFIX_ . 'tax_rule
+		WHERE
+			id_country=' . (int) $countryId . ' AND id_state=' . (int) $stateId
+        );
```
Comment (PierreRambaud) [inline install-dev/fixtures/fashion/install.php]:
```suggestion
            'SELECT id_tax_rules_group
            FROM ' . _DB_PREFIX_ . 'tax_rule
            WHERE
            id_country=' . (int) $countryId . ' AND id_state=' . (int) $stateId
        );
```

File: src/Adapter/Order/Refund/OrderRefundCalculator.php [hunk 2]
```diff
@@ -246,7 +247,7 @@ private function isTaxIncludedInOrder(Order $order): bool
      *
      * @throws PrestaShopException
      */
-    private function getOrderTaxCalculator(Order $order): TaxCalculator
+    private function getCarrierTaxCalculator(Order $order): TaxCalculator
```
Comment (PierreRambaud) [inline src/Adapter/Order/Refund/OrderRefundCalculator.php]:
```suggestion
    private function getCarrierTaxCalculatorFromOrder(Order $order): TaxCalculator
```
wdyt?

File: tests/puppeteer/pages/BO/catalog/products/index.js [hunk 3]
```diff
@@ -141,6 +143,17 @@ module.exports = class Product extends BOBasePage {
...
+   * Get Product Price TTC
+   * @param row
+   * @return Float
+   */
+  async getProductPriceTTCFromList(row) {
+    const text = await this.getTextContent(this.productsListTableColumnPriceTTC.replace('%ROW', row));
+    const price = /\d+(\.\d+)?/g.exec(text).toString();
+    return parseFloat(price);
+  }
+
```
Comment (PierreRambaud) [inline tests/puppeteer/pages/BO/catalog/products/index.js]:
```suggestion
  async getProductPriceFromList(row, ttc) {
    const selector = ttc ? this.productsListTableColumnPriceTTC : this.productsListTableColumnPrice;
    const text = await this.getTextContent(selector.replace('%ROW', row));
    const price = /\d+(\.\d+)?/g.exec(text).toString();
    return parseFloat(price);
  }

```
Do not duplicate `getProductPriceFromList` method. Add a parameter to do that

File: tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js [hunk 4]
```diff
@@ -115,6 +115,27 @@ describe('Create, read, update and delete Standard product in BO', async () => {
     ]);
   });
 
+  it('should go to Products page', async function () {
+    await testContext.addContextItem(this, 'testIdentifier', 'goToProductsPage', baseContext);
```
Comment (boubkerbribri) [inline tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js]:
```suggestion
    await testContext.addContextItem(this, 'testIdentifier', 'goToProductsPageToCheckPrices', baseContext);
```

File: tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js [hunk 5]
```diff
@@ -115,6 +115,27 @@ describe('Create, read, update and delete Standard product in BO', async () => {
...
+    await this.pageObjects.boBasePage.goToSubMenu(
+      this.pageObjects.boBasePage.catalogParentLink,
+      this.pageObjects.boBasePage.productsLink,
+    );
+    await this.pageObjects.boBasePage.closeSfToolBar();
```
Comment (boubkerbribri) [inline tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js]:
```suggestion
```

No need for this here

File: tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js [hunk 6]
```diff
@@ -115,6 +115,27 @@ describe('Create, read, update and delete Standard product in BO', async () => {
...
+    const pageTitle = await this.pageObjects.productsPage.getPageTitle();
+    await expect(pageTitle).to.contains(this.pageObjects.productsPage.pageTitle);
+  });
+
+  it('should filter list by reference, check prices and go to edit page', async function () {
+    await testContext.addContextItem(this, 'filterReference', 'filterBy_reference', baseContext);
```
Comment (boubkerbribri) [inline tests/puppeteer/campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js]:
```suggestion
    await testContext.addContextItem(this, 'testIdentifier', 'checkProductsPrices', baseContext);
```

File: tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js [hunk 7]
```diff
@@ -58,6 +58,15 @@ describe('Filter in Products Page', async () => {
...
     numberOfProducts = await this.pageObjects.productsPage.resetAndGetNumberOfLines();
     await expect(numberOfProducts).to.be.above(0);
+
+    // Do not loop more than the products displayed via the pagination
+    const numberOfProductsOnPage = await this.pageObjects.productsPage.getNumberOfProductsOnPage();
+    // Check that prices have correct tax values
+    for (let i = 1; i <= numberOfProducts && i <= numberOfProductsOnPage; i++) {
+      const productPrice = await this.pageObjects.productsPage.getProductPriceFromList(i);
+      const productPriceTTC = await this.pageObjects.productsPage.getProductPriceTTCFromList(i);
+      await expect(parseFloat(productPrice)).to.equal(parseFloat((productPriceTTC / 1.2).toFixed(2)));
```
Comment (Progi1984) [inline tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js]: Why 1.2 ?

**Comment by jolelievre** [comment]
@PierreRambaud @boubkerbribri I addressed all your feedback Thanks

File: tests/puppeteer/pages/BO/catalog/products/index.js [hunk 8]
```diff
@@ -133,10 +135,12 @@ module.exports = class Product extends BOBasePage {
   /**
    * Get Product Price
    * @param row
+   * @param ttc
    * @return Float
    */
-  async getProductPriceFromList(row) {
-    const text = await this.getTextContent(this.productsListTableColumnPrice.replace('%ROW', row));
+  async getProductPriceFromList(row, ttc) {
```
Comment (Progi1984) [inline tests/puppeteer/pages/BO/catalog/products/index.js]:
```suggestion
  async getProductPriceFromList(row, isTTC) {
```

File: tests/puppeteer/pages/BO/catalog/products/index.js [hunk 9]
```diff
@@ -133,10 +135,12 @@ module.exports = class Product extends BOBasePage {
   /**
    * Get Product Price
    * @param row
+   * @param ttc
```
Comment (Progi1984) [inline tests/puppeteer/pages/BO/catalog/products/index.js]:
```suggestion
   * @param boolean ttc
```

File: tests/puppeteer/pages/BO/catalog/products/index.js (hunk 8 above)
Comment (jolelievre) [reply tests/puppeteer/pages/BO/catalog/products/index.js]: Rather `withTaxes` then

File: tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js (hunk 7 above)
Comment (jolelievre) [reply tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js]: Because in this context we use french TVA of 20%, I hard coded it because it never changes But if one day we need to change it it will need to be more dynamic I thought for now it's enough

**Comment by jolelievre** [comment]
@Progi1984 I adressed you feedback as well ^^

**Review by Progi1984 — DISMISSED** [review]

**Review by boubkerbribri — DISMISSED** [review]

File: tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js (hunk 7 above)
Comment (PierreRambaud) [reply tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js]: It's better to add a const / page variable because you also use it in 02_CRUDStandardProductInBO.js

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi,

The fix for https://github.com/PrestaShop/PrestaShop/issues/12174 does not seem to work.

See invoice : 
[IN000001 (14).pdf](https://github.com/PrestaShop/PrestaShop/files/4348188/IN000001.14.pdf)

And credit slip after changing tax : 
[000001 (6).pdf](https://github.com/PrestaShop/PrestaShop/files/4348190/000001.6.pdf)

Tax should be identical.

Thanks

**Comment by Robin-Fischer-PS** [comment]
And note that there is a conflict on a puppeteer file :)

**Review by boubkerbribri — DISMISSED** [review]

File: tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js (hunk 7 above)
Comment (Progi1984) [reply tests/puppeteer/campaigns/sanity/02_productsBO/01_filterProducts.js]: :+1: with @PierreRambaud comment ;)

**Review by Progi1984 — COMMENTED** [review]
Remain 1 comment (this one from @PierreRambaud) before approve

**Comment by jolelievre** [comment]
Oh yeah I missed that comment, I fix it right away

**Review by Progi1984 — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
The fix is OK now, thanks @jolelievre !

Initial invoice : 
[IN000001 (16).pdf](https://github.com/PrestaShop/PrestaShop/files/4355675/IN000001.16.pdf)

Credit slip after changing product and shipping VAT : 
[000001 (7).pdf](https://github.com/PrestaShop/PrestaShop/files/4355677/000001.7.pdf)
