### PR TITLE
Don't encode quotes in column name filter value

### LINKED ISSUE #26550: [BO] Product listing - Unable to search for a product with an apostrophe (if using the apostrophe)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If my product name has an apostrophe, I cannot search for it using the apostrophe in the search. It does not return any results.
Example: "L'arbre".

I have to search without the apostrophe. In some cases, this is not practical

### Expected behavior

Be able to search with an apostrophe

### Steps to reproduce

1. Create a product with an apostrophe
2. Search for the product on the BO

### PrestaShop version(s) where the bug happened

1.7.7.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by yo7hli**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?   | Currently, single quotes in column name grid filtering get escaped to the corresponding html code, interfering with search results. Resolved by not escaping single quotes in filter value. Safe, because the sql query string gets escaped further down in the sql query itself
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | nothing i can think of
| Deprecations?     |  no
| Fixed ticket?     | Fixes #26550 
| How to test?      | See issue description
| Possible impacts? | none i can think of

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26561)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
If what you say 'Safe, because the sql query string gets escaped further down in the sql query itself' is true, then this PR is valid 👍  could you help me and show me where exactly the SQL escape happens?

**Comment by yo7hli** [comment]
@matks 
after returning the unencoded filter value, the filter is persisted as is (json encoded, I dont think we need to escape anything here), then when the sql is prepared the filter values get escaped: https://github.com/PrestaShop/PrestaShop/blob/c5ac7baaec3b913ed2ff64195938ef05bd21169c/src/Adapter/Product/AdminProductDataProvider.php#L333-L338
then the escape function deals with quotes and double quotes:
 https://github.com/PrestaShop/PrestaShop/blob/c5ac7baaec3b913ed2ff64195938ef05bd21169c/classes/db/DbPDO.php#L283-L289

**Review by matks — DISMISSED** [review]
Thank you @yo7hli I approve the PR 😄

**Review by Progi1984 — COMMENTED** [review]
@yo7hli Great contribution. Could you add some unit tests, please ?

**Comment by yo7hli** [comment]
@Progi1984 
ok so here's an attempt at testing this scenario, now since I dont have much experience in writing tests, suggestions are welcome :)

File: tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+            ->getProductCatalogFilter();
+
+        $this->assertSame($expected, $setFilter['filter_column_name']);
+    }
+
+    public function productFilterProviderByName(): array
+    {
+        return [
+            'quote_in_name' => [['filter_column_name' => 't\'est'], 't\'est'],
+            'double_quote_in_name' => [['filter_column_name' => 't\"est'], 't\"est'],
```
Comment (PierreRambaud) [inline tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php]:
```suggestion
            'double_quote_in_name' => [['filter_column_name' => 't"est'], 't"est'],
            'lot_of_double_quote' => [['filter_column_name' => 't""e""s""t""""'], 't""e""s""t""""'],
            'lot_of_quote' => [['filter_column_name' => "t'''e''s't''"], "t'''e''s't''"],
```

The backslash is not needed.

Comment (yo7hli) [reply tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php]: agreed

File: tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+ * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://devdocs.prestashop.com/ for more information.
+ *
+ * @author    PrestaShop SA and Contributors <contact@prestashop.com>
+ * @copyright Since 2007 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ */
+
+namespace Tests\Unit\PrestaShopBundle\Entity;
```
Comment (Progi1984) [inline tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php]:
```suggestion
 */

declare(strict_types=1);

namespace Tests\Unit\PrestaShopBundle\Entity;
```

File: tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+
+use PHPUnit\Framework\TestCase;
+use PrestaShopBundle\Entity\AdminFilter;
+
+class AdminFilterTest extends TestCase
+{
+    private $emptyFilter;
```
Comment (Progi1984) [inline tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php:36]:
```suggestion
    /**
     * @var array
     */
    private $emptyFilter;
```

File: tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+
+    protected function setUp(): void
+    {
+        $this->emptyFilter = AdminFilter::getProductCatalogEmptyFilter();
+    }
+
+    public function testGetProductCatalogEmptyFilter()
```
Comment (Progi1984) [inline tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php]:
```suggestion
    public function testGetProductCatalogEmptyFilter(): void
```

File: tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+        $this->assertEmpty($this->emptyFilter['filter_column_reference']);
+        $this->assertEmpty($this->emptyFilter['filter_column_price']);
+        $this->assertEmpty($this->emptyFilter['filter_column_sav_quantity']);
+        $this->assertEmpty($this->emptyFilter['filter_column_active']);
+    }
+
+    /**
+     * @dataProvider productFilterProviderByName
+     */
+    public function testSetProductCatalogFilterByName(array $filter, $expected)
```
Comment (Progi1984) [inline tests/Unit/PrestaShopBundle/Entity/AdminFilterTest.php]:
```suggestion
    public function testSetProductCatalogFilterByName(array $filter, string $expected): void
```

**Review by Progi1984 — COMMENTED** [review]
@yo7hli Some feedbacks and it's an approval

**Comment by yo7hli** [comment]
@Progi1984 
looking good

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,
PR is tested with different languages and the issue is fixed :
image
Thanks,

**Comment by Progi1984** [comment]
Thanks @yo7hli & @marwachelly
