### PR TITLE
Fix Broken Authentication and Session Management

### LINKED ISSUE #12040: Broken Authentication and Session Management
**Describe the bug**
All previous passwords resettled by links should automatically expire once a user changes his email address or his password.
Thanks hami hax & Jhon Ken

**To Reproduce**
With email:
1. Create an (prestashop) account having an email address "a@x.com".
2. Now Logout and ask for a password reset link. Don't use the password reset link.
3. Log in using the same password back and update your email address to "b@x.com" and verify the same.
4. Now log out and use the password reset link which was mailed to "a@x.com" in step 2.
5. Password will be changed.

With password change:
1. login From two browser at a time [ From Chrome browser and From Mozilla
Firefox ]
2. Change password in setting from chrome browser
3. Now Check Mozilla FireFox
4. Your Session Got Updated in place of expiration

### PR DESCRIPTION
**Pull request by arnaudschaeffer**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | All previous passwords resettled by links should automatically expire once a user changes his email address or his password.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12040 
| How to test?  | See issue #12040

I started working on this before realising that this issue was marked for the version 1.7.6. I created the PR anyway, it will be possible to use it later.

I'm pretty sure that I fix the first problem describe in the issue. But I'm not as confident about the second problem (clear all sessions after an user change his password, except the one he used to change it). I worked for me but let me know if you wanted to do it in another way.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12391)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
I will try to have a look on tomorrow and see why tests are broken.

File: classes/Customer.php [hunk 1]
```diff
@@ -747,6 +747,14 @@ public static function checkPassword($idCustomer, $passwordHash)
         if (!Validate::isUnsignedId($idCustomer)) {
             die(Tools::displayError());
         }
+
+        // Check that customers password hasn't changed since last login
+        $context = Context::getContext();
+        if ($passwordHash != $context->cookie->__get('passwd')) {
+            $context->customer->logout();
```
Comment (Quetzacoalt91) [inline classes/Customer.php]: It seems this line in not needed, as the AdminController is already able to logout the employee if invalid.

**Comment by PierreRambaud** [comment]
Really sorry for the delay, we're a little bit busy :smile_cat: 
Your pull request seems to fix more than the original issue. If you change your title, firstname, lastname, birthdate or password you'll be disconnect from others devices.
I also rebase your PR from latest develop changes.

@colinegin If it's ok for you, I'll be glad to merge this PR.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @arnaudschaeffer
