### PR TITLE
Fix deleted customer's order preview/details

### LINKED ISSUE #17311: Error while trying to preview or view an order of a deleted customer
**Describe the bug**
Error while trying to preview or view an order of a deleted customer

**To Reproduce**
1. Go to BO > Customers > Customers
2. Delete John Doe
3. Go on the migrated order list
4. Try to click on the preview, nothing is happening
5. Try to view the order 
6. See errors

**Screenshots**
**Error in the console after clicking on the preview**
capture d'écran_2301

**Error after clicking on view**
capture d'écran_2299

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When a customer was hard deleted, you couldn't see his orders preview and details. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17311
| How to test?  | 1. Go to BO > Customers > Customers<br>2. Delete John Doe<br>3. Go on the migrated order list<br>4. See this [issue comment](https://github.com/PrestaShop/PrestaShop/issues/17311#issuecomment-581481515) to see what should be displayed on the list and on the order details.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17535)

### CODE REVIEW

File: src/Core/Grid/Column/Type/DisableableLinkColumn.php [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+
+        return $this;
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function getOptions()
+    {
+        return array_merge($this->linkColumn->getOptions(), parent::getOptions());
```
Comment (Progi1984) [inline src/Core/Grid/Column/Type/DisableableLinkColumn.php:90]:
```suggestion
        return array_merge(parent::getOptions(), $this->linkColumn->getOptions());
```

**Review by Progi1984 — COMMENTED** [review]
Feedback

File: src/Core/Grid/Column/Type/DisableableLinkColumn.php (hunk 1 above)
Comment (Progi1984) [reply src/Core/Grid/Column/Type/DisableableLinkColumn.php:90]: Cancelled

**Review by Progi1984 — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_all_messages_modal.html.twig [hunk 2]
```diff
@@ -30,7 +30,12 @@
         <div class="row">
           <div class="col">
             <h3 class="card-header-title">
-              {{ 'Message history with %name%'|trans({'%name%': orderForViewing.customer.firstName ~ ' ' ~ orderForViewing.customer.lastName}, 'Admin.Global') }} ({{ orderForViewing.messages.messages|length }})
+              {% if orderForViewing.customer is not null %}
+                {{ 'Message history with %name%'|trans({'%name%': orderForViewing.customer.firstName ~ ' ' ~ orderForViewing.customer.lastName}, 'Admin.Global') }}
```
Comment (LouiseBonnard) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_all_messages_modal.html.twig:34]: Is this string necessary? What will %name% indicate? We are talking about a deleted customer, we are not supposed to have its name anymore.

File: src/Core/Grid/Column/Type/DisableableLinkColumn.php [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+
+declare(strict_types=1);
+
+namespace PrestaShop\PrestaShop\Core\Grid\Column\Type;
+
+use PrestaShop\PrestaShop\Core\Grid\Column\AbstractColumn;
+use PrestaShop\PrestaShop\Core\Grid\Column\Type\Common\LinkColumn;
+use Symfony\Component\OptionsResolver\OptionsResolver;
+
+final class DisableableLinkColumn extends AbstractColumn
```
Comment (matks) [inline src/Core/Grid/Column/Type/DisableableLinkColumn.php:35]: It's not necessarily an issue but ... did you consider modifying LinkColumn to add an option, rather than creating a new class ? If yes, what are the reasoning behind this choice ? Just curious

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_all_messages_modal.html.twig (hunk 2 above)
Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_all_messages_modal.html.twig:34]: Actually, "Message history with %name%" is the sentence when the customer is not deleted. %name% will "firstname lastname". When the customer is deleted, the sentence will be "Message history" as you can see just below. 🙂

File: src/Core/Grid/Column/Type/DisableableLinkColumn.php (hunk 3 above)
Comment (atomiix) [reply src/Core/Grid/Column/Type/DisableableLinkColumn.php:35]: @matks The main purpose was to keep the `LinkColumn` as simple as possible knowing that `DisableableLinkColumn` is only used once (for now at least...). But your suggestion seems good to me too. WDYT?

File: src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig [hunk 4]
```diff
@@ -49,8 +50,14 @@
             {{ 'View full details'|trans({}, 'Admin.Actions') }}
           </a>
         </div>
+        {% else %}
+        <div class="col">
+          <h2 class="mb-0">{{ 'Deleted customer'|trans({}, 'Admin.Global') }}</h2>
```
Comment (NeOMakinG) [inline src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:55]: Could we think about a better workflow when we've to disable margin-bottom ? Using class like mb-0 is against the CSS principle :/

Comment (NeOMakinG) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:55]: I would prefer something like customer-title-delete and adding a margin-bottom: 0; somewhere in the css, or disable margin-bottom on h2 inside a certain class...

What do you think @PierreRambaud

Comment (PierreRambaud) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:55]: Agree with @NeOMakinG It's also easier for someone to do something more specific with a custom class than a class like `mb-0`

Comment (atomiix) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:55]: @PierreRambaud @NeOMakinG Maybe we can open another issue for that because all that page is build like that and I was just reusing a part to adapt it when the customer doesn't exist. WDYT?

Comment (NeOMakinG) [reply src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/customer.html.twig:55]: Ok, but I think we should talk about it with the team before next migrations

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by SD1982** [comment]
The pull request correctly fix #17311  : 

**Order list after deleting a customer :** 

Fix deleted customer's order preview details #17535 after PR1

**Order view after deleting a customer :** 

Fix deleted customer's order preview details #17535 after PR2
