### PR TITLE
Fix grid sorting by

### LINKED ISSUE #44: Grid issue: re-order asc/desc on columns doesn't works
A plugin has been used but sounds broken.

You can test it here => http://localhost/admin-dev/index.php/configure/advanced/logs/

### PR DESCRIPTION
**Pull request by matks**
Fix grid sorting by enabling SearchParametersResolver to resolve 'sort column' request as well

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop |
| Description?  | Fix BO grid 'sort column' feature |
| Type?         | bug fix |
| Category?     | BO |
| BC breaks?    | no |
| Deprecations? | no |
| Fixed ticket? | 
| How to test?  | Login in BackOffice, visit URL http://localhost/admin-dev/index.php/configure/advanced/logs/ (this is the SF version of this page), then click on arrows on the top of columns. Expected behavior is: this should sort the table data by using the column as a reference, and another click will toggle the order. Example: click on "Date" once to see the table data rows being sorted in ascending order using the dates of the rows. Click another time on "Date" to see the table data rows being sorted in descending order this time. |

Should fix https://github.com/PrestaShop/prestafony-project/issues/44

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9300)

### CODE REVIEW

File: src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php [hunk 1]
```diff
@@ -102,9 +102,11 @@ public function resolve(Request $request, ArgumentMetadata $argument)
     {
         $filtersClass = $argument->getType();
         list($controller, $action) = ControllerAction::fromString($request->get('_controller'));
-        // is the url contains filters?
+
         $query = $request->query;
-        if ($query->has('filters') || $query->has('limit')) {
+        $doesTheUrlContainsFilters = ($query->has('filters') || $query->has('limit') || $query->has('sortOrder'));
```
Comment (PierreRambaud) [inline src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php:107]: No need to add this in variable, can be used in condition =)

Comment (matks) [reply src/PrestaShopBundle/Controller/ArgumentResolver/SearchParametersResolver.php:107]: The variable name is a hint to help developers to understand the meaning of this line of code. It replaces the [deleted comment](https://github.com/PrestaShop/PrestaShop/pull/9300/files#diff-307533e1154f5cf404d67226aa79ef8eL105).

**Comment by mickaelandrieu** [comment]
Works as expected for me

works_as_expected

**Comment by mickaelandrieu** [comment]
And LGTM, thanks @matks and @marionf for the review

**Review by mickaelandrieu — APPROVED** [review]
