### PR TITLE
Prevent deleting main URL of a store

### LINKED ISSUE #32864: BO - Multistore - Store crashes when deleting main URL
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In multistore mode, when you assign for the main shop two main URLs, you can see that after adding the second URL, the first one become not main anymore.

In fact you can observe that the first URL assigned to the shop have no delete option, only Edit button; in the other side the second URL even it became a main URL we have the option to delete it.

See attached screenshots :
image

If I delete the second URL which became the main URL all the store crashes and you can’t even go back to previous menu.

See attached screenrecord for store crash :

https://github.com/PrestaShop/PrestaShop/assets/92626242/0729cf3e-367d-4af4-990e-56347be74884

Related to #11477

### Expected behavior

I think that the system should prevent us from deleting a main URL if there is only one available, or if there is two URLs it should automatically switch to the second one so the store won’t crash .

### Steps to reproduce

1. BO > Configure > General > Enable Multistore > click on `Save` button
2. Advanced Parameters > Multistore > click on `Add a new shop` button> click on `Save` button
3. In Multistore tree select the first shop > click on the URL below
4. Click on `Add a new URL` button
5. In URL options section : In Shop field choose your first shop in the drop-down list and enable the button `Is it the main URL for this shop?`
6. IN Shop URL section > add Virtual URL name
7. Get back to  URL options and click on `Save `button
8. Go to Multistore tree section > click on `Default` to show stores URLs
9. Go to the second URL assigned for the store(URL that you've just created in step 4 & 5) > click on `Edit `button 
10. Go to Shop URL section > click on Save button
11. Go to Multistore tree section > click on `Default` to show stores URLs
12. Go to the second URL (URL that you've just created in step 4 & 5) > click on the arrow from `Edit` button > click on `Delete` and confirm
13. See error > See attached video record :

https://github.com/PrestaShop/PrestaShop/assets/92626242/da9c8927-47f3-44ba-a25c-f964f1f14159

### PrestaShop version(s) where the bug happened

1.7.8.9 & 8.0.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | In shop URL controller, there was a first row hardcoded, that should not be deleted. This is not correct, we must prevent deleting the real main URLs of stores. Got inspired in group and statuses controller and got the IDs with a query.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Main URL of a store is not deletable anymore.
| Fixed ticket?     | Fixes #32864
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @Hlavtox 

Thank you for your PR, it solved the mentioned problem ,LGTM :heavy_check_mark: 

See attached videorecod:

https://github.com/PrestaShop/PrestaShop/assets/92626242/2ed52a10-cc9b-4cde-b616-210f8d600616

Thanks!

**Comment by nicosomb** [comment]
Thank you @Hlavtox !

File: controllers/admin/AdminShopUrlController.php [hunk 1]
```diff
@@ -122,6 +123,19 @@ public function renderList()
         return parent::renderList();
     }
 
+    /**
+     * Returns a list of URLs that are selected as main ones for some store.
+     *
+     * @return array of URLs that are selected as main
+     */
+    protected function getUnremovableUrls()
```
Comment (FabienPapet) [inline controllers/admin/AdminShopUrlController.php:131]: can you make it private so it is not BC compliant ?
