### PR TITLE
Fixed unclear error message during api/products/image requests with improper input data

### LINKED ISSUE #22313: Better error message on invalid image upload request
When there is an invalid request during Image upload, prestashop returns only general error code 500 / 66: Unable to save this image, response should be bit more detailed

### PR DESCRIPTION
**Pull request by KminekMatej**
Add new throw clause for better debug, when input data are not specified correctly

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improper input data during api/products/image requests leads to unclear error message. I added a bit more detailed error message.
| Type?         | improvement
| Category         | WS
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22313 .
| How to test?  | Send request with malformed image property - instead of displaying error code 500 / 66: Unable to save this image, response should be 400 / 67: Missing tmp_file property. Check supplied input data.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22309)

### CODE REVIEW

**Comment by KminekMatej** [comment]
Fixes #22313

File: classes/webservice/WebserviceSpecificManagementImages.php [hunk 1]
```diff
@@ -1221,6 +1221,7 @@ protected function writePostedImageOnDisk($reception_path, $dest_width = null, $
                     return true;
                 }
             }
+            throw new WebserviceException('Missing tmp_file property. Check supplied input data.', [67, 400]);
```
Comment (atomiix) [inline classes/webservice/WebserviceSpecificManagementImages.php]: @KminekMatej I think you'd rather reuse what had been done here : https://github.com/PrestaShop/PrestaShop/blob/develop/classes/webservice/WebserviceSpecificManagementImages.php#L1111-L1113

Comment (KminekMatej) [reply classes/webservice/WebserviceSpecificManagementImages.php]: You, sir, are absolutely right. I will update that

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional OK for a QA dev ?

**Comment by Robin-Fischer-PS** [comment]
@Progi1984 Yes, OK for QA by dev. Thanks :)

**Comment by atomiix** [comment]
Before the PR:
Capture d’écran 2021-03-31 à 16 06 52

After the PR:
Capture d’écran 2021-03-31 à 16 07 20

This PR is QA ✔️

**Comment by Progi1984** [comment]
Thanks @KminekMatej & @atomiix
