### PR TITLE
Fix: bug: Legacy form sends GET request instead of POST as it should

### LINKED ISSUE #37687: Bug: Legacy form sends GET request instead of POST as it should
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Forms in PrestaShop using the POST method are incorrectly submitting data as GET, resulting in form values being appended to the URL. This behavior is unexpected and may cause security issues, as sensitive data may become visible in the URL.

### Expected behavior

Forms using the POST method should not append data to the URL. All submitted data should be sent in the request body as per the HTTP specification.

### Steps to reproduce

- Navigate to any module configuration page that is using legacy form. In my case it was `ps_brandlist`
- Just click Save button
- Observe the URL after submission. Form values appear in the URL as if the form was submitted using the GET method.

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

ps_brandlist (or any other that is using legacy form)

The link to Slack discussion https://prestashop.slack.com/archives/CTKHSPWPM/p1734385117647459

### Your company or customer's name goes here (if applicable).

Valerii

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | see #37687 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see #37687 + To make sure this doesn't break anything all the native modules configuration pages should be tested
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/12954942359
| Fixed issue or discussion?     | Fixes #37687 
| Related PRs       | 
| Sponsor company   | @Codencode

### CODE REVIEW

File: src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php [hunk 1]
```diff
@@ -125,9 +125,7 @@ public function convertByRequest(Request $request)
         $this->router->getContext()->fromRequest($request);
         $this->checkAlreadyMatchingRoute($request->getRequestUri());
 
-        $parameters = array_merge($request->query->all(), $request->request->all());
-
-        return $this->convertByParameters($parameters);
+        return $this->convertByParameters($request->query->all());
```
Comment (jolelievre) [inline src/PrestaShopBundle/Routing/Converter/LegacyUrlConverter.php]: Yeah when the legacy url converter was introduced along with the LegacuUrlListener we used a simple redirection which lost the initial method, so the workaround was to merge all data to make sure they are not lost
Now that the listener has been improved and is based on a 308 redirection (which keeps the method and body content) this becomes useless

**Review by jolelievre — DISMISSED** [review]
Thanks @Codencode

**Review by Hlavtox — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@Codencode `Tests\Integration\PrestaShopBundle\Routing\Converter\LegacyUrlConverterTest::testPostParameters` must be updated - probably it expects the (wrong) post parameters to be in the result.

**Comment by Codencode** [comment]
@Hlavtox,
from what I understand, the problem is that the action simulated by the test (submitAddToHook) triggers the redirect, but the test expects that no redirect occurs. Should the following instruction be removed?"
```php
$this->assertFalse($response->isRedirection());
```

https://github.com/PrestaShop/PrestaShop/blob/61c7c4b5247789eb1a68291a955aea29a3167635/tests/Integration/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php#L450C1-L457C6

What am I missing?

**Comment by Hlavtox** [comment]
No idea, I will ping @jolelievre and @boherm. :-)

**Comment by jolelievre** [comment]
Yep I noticed this one I plan on testing this locally to understand the problem, it's on my todo list

**Comment by Codencode** [comment]
> Yep I noticed this one I plan on testing this locally to understand the problem, it's on my todo list

Perfect, thank you!

**Comment by jolelievre** [comment]
Hi @Codencode 

it took me a while to understand the goal behind this test 😅 I developed this a long time ago and there were no comments to explain it. So actually the test was here to make sure if the action is posted (and not in the URL) then it is correctly taken into account for route matching.

Your modification had a side effect in this case, only the query parameters were used, so the action was considered as empty which is synonym for `index` action, and this action matched with the `admin_modules_positions` hence the unwanted redirection.

So I improved the method a bit, it cannot simply rely on `convertByParameters` we need to split the work:
- matching is based on GET + POST parameters
- URL generation is based only on GET parameters

I improved the test use case so that it validates both these use cases (matching action via POST, no matching action via POST) with better explanation this time 😉

**Comment by Codencode** [comment]
@jolelievre, perfect! thanks again!

**Review by jolelievre — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by SiraDIOP** [comment]
Hello @Codencode ,

I tested your PR and it's good for me! 🎉

I'm waiting the automated test for approve the PR.

Thanks!

https://github.com/user-attachments/assets/914deec9-54d1-4e9c-92a0-b9b9a5d4da7b

**Comment by Codencode** [comment]
@SiraDIOP thank you!

**Comment by SiraDIOP** [comment]
Hello @Codencode ,
All automated tests are ok, so everything is Ok.
Thanks
https://github.com/SiraDIOP/ga.tests.ui.pr/actions/runs/12990872384

**Review by SiraDIOP — APPROVED** [review]

**Comment by Hlavtox** [comment]
@jolelievre @boherm I don't really see if it works from @SiraDIOP video, should I merge it? :-)))

**Comment by jolelievre** [comment]
@Hlavtox yep I also tested it and it works, there are still some unwanted variables in the URL after post, but that's because the `action` parameter in the form itself adds many GET parameters in the URL

Some are automatically remove (mostly the action parameter than can have different formats), but there is still a legacy tab_module that is obsolete now I think We could either fix all the modules to remove this when they generate the form, or improve the `LegacyUrlConverter` to remove this legacy parameter (although it's kind of twisting its responsibility a bit)

TLDR; the post variables are fixed and are only present in post data now so we're good

**Comment by Hlavtox** [comment]
@jolelievre OK, I think that it's not the responsibility of the converter. If we find that the parameter should not be there, it will be resolved in a different place anyway. :-)
