### PR TITLE
Fix combination ecotax display and edition

### LINKED ISSUE #9967: [BOOM-3282] Ecotax on combinations not displayed in FO
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3282).

- _**Reporter:**_ stkado
- _**Created at:**_ Tue, 20 Jun 2017 08:57:29 +0200

<p>On the product page if my combination doesn't have the same ecotax as the parent when i switch combination the ecotax isn't updated / displayed</p>
        
capture-for-jira-screenshot-20160920-173156-945

capture-for-jira-screenshot-20160920-173023-827
Edit from this issue: https://github.com/PrestaShop/PrestaShop/issues/16462

                    Ecotax is unavailable for combinations

By displaying the variable `$product` in the loop of the file `/themes/classic/templates/checkout/_partials/order-confirmation-table.tpl` (order confirmation page), the `ecotax` is `"0.000000"` for the combination.

`ecotax` seems to refer to the ecotax of the product and therefore seems to override the one of the combination.

The same problem occurs on the product page, where `ecotax` is also `0` (and so the ecotax is not displayed).

I want to show that the problem is bigger: the data would be correctly displayed if it went up correctly.

**To Reproduce**
1. Enable ecotax
2. Create a product with combinations and ecotax in combinations
3. Display `$product` variable on the product page and on the order confirmation page

### LINKED ISSUE #24529: BO - Orders - Problems on product price changing in database
#### Describe the bug

If I change the price on a product in an order via the administration, the values of `product_price` and `original_product_price` are different or same between the method used for update.

#### Expected behavior

The same behavior on differents methods

##### Create a first order:

1. Go to admin > order settings > order settings
2. Click on **add new order**
3. Choose a customer
4. Search a product and add to cart. Mug The Adventure Begins for example at 11.90
5. Change the price to 8.00
6. Choose the payment method & status and create the order
7. In your database check the `product_price`, `original_product_price` and `unit_price_tax_excl` in the `order_detail` table.

product_price = 11.90
original_product_price = 11.90
unit_price_tax_excl = 8.00

##### Create a second order:

Do the same steps but don't change the price at step 5. Create the order.

1. On the order view edit the price of the product at 8.00 
2. Save the line and confirm
3. In your database check the `product_price`, `original_product_price` and `unit_price_tax_excl` in the `order_detail` table.

product_price = 8.00
original_product_price = 11.90
unit_price_tax_excl = 8.00

##### Conclusion:

There is a difference between the two methods, I don't know which method is in error.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.2.34
* MariaDB: 10.5.9

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | `OrderDetail::product_price` is actually a deprecated field and is synonym to `OrderDetail::unit_price_tax_excl` This PR fixes some issues in the creation of OrderDetail so that the two values are always in sync It was already handled in `Order::getProducts` (see link below) but now the database is also correctly synced<br>Also this PR includes a fix in the ecotax computation of combination price which caused `OrderDetail::original_product_price` to be incorrect (ecotax was absent)<br><br>This modification originates from this PR https://github.com/PrestaShop/PrestaShop/pull/24675 Where a small fix was added related to combination ecotax in Order computing But this fix also impacts the FO because the ecotax combination's value was never used Now that this is fixed it raises some questions regarding the BO which was inconsistent So this PR aims to add the necessary changes (to avoid making the previous PR too big and avoid noise) Basically it fixes a few things regarding the combination ecotax:<br>- save the value in tax excluded (but display tax included)<br>- display the correct ecotax value in FO when it has been overridden<br>- in BO handle automatic updates on impact prices when ecotax is changed, the goal is to keep the final price unchanged while editing the ecotax
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9967 #24529
| How to test?      | Unlike what was stated in the original issue OrderDetail::product_price shouldn't be equal to OrderDetail::original_product_price but rather to OrderDetail::unit_price_tax_excl<br><br>Edit ecotax in a product with combinations, it now overrides the product's value and is correctly displayed in FO
| Possible impacts? | This PR might fix some bugs related to ecotax and combinations, although most of the time the computation seemed to be correct (based on existing behat tests) so it's probably computed differently for regular prices but a mistake was still present in the computation of original_product_price

Here is the code that ensures `OrderDetail::original_product_price` and `OrderDetail::unit_price_tax_excl` are equal when getting order products, so the database should be equal as well
https://github.com/PrestaShop/PrestaShop/blob/948ecce8461176c507512c977633731bc3550a24/classes/order/Order.php#L607

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24991)

### CODE REVIEW

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 1]
```diff
@@ -1771,19 +1789,29 @@ var priceCalculation = (function() {
...
+      this.updateImpactTI(impactPriceTE, obj);
+    },
+
+    /**
+     * Computes the impact price tax included and update the related input
+     * @param {Number} impactPriceTE
+     * @param {jQuery} obj
+     */
+    updateImpactTI: function(impactPriceTE, obj) {
+      var impactPriceTI = 0;
```
Comment (Progi1984) [inline admin-dev/themes/default/js/bundle/product/form.js]:
```suggestion
      var impactPriceTI = 0;
      var displayPrecision = 6;
```

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 2]
```diff
@@ -1771,19 +1789,29 @@ var priceCalculation = (function() {
...
+      if (!isNaN(impactPriceTE)) {
         var rates = this.getRates();
         var computation_method = taxElem.find('option:selected').attr('data-computation-method');
-        newPrice = ps_round(addTaxes(price, rates, computation_method), 6);
-        newPrice = truncateDecimals(newPrice, 6);
+        impactPriceTI = ps_round(addTaxes(impactPriceTE, rates, computation_method), 6);
+        impactPriceTI = truncateDecimals(impactPriceTI, 6);
```
Comment (Progi1984) [inline admin-dev/themes/default/js/bundle/product/form.js]:
```suggestion
        impactPriceTI = ps_round(addTaxes(impactPriceTE, rates, computation_method), displayPrecision);
        impactPriceTI = truncateDecimals(impactPriceTI, displayPrecision);
```

File: admin-dev/themes/default/js/bundle/product/product-combinations.js [hunk 3]
```diff
@@ -137,12 +139,41 @@ var combinations = (function() {
...
+          // when typing a new ecotax on the form, update it on the final price data attribute
+          'keyup': function () {
+            var attributeId = $(this).closest('.combination-form').attr('data');
+            var finalPriceLabel = getCombinationRow(attributeId).find('.attribute-finalprice span');
+            var combinationEcotax = priceCalculation.getCombinationEcotaxTaxExcluded($(this));
+            if (combinationEcotax <= 0) {
+              combinationEcotax = priceCalculation.getProductEcotaxTaxExcluded();
+            }
+
+            finalPriceLabel.data('productEcotax', combinationEcotax);
```
Comment (Progi1984) [inline admin-dev/themes/default/js/bundle/product/product-combinations.js]: Could you factorize this code ?

File: classes/Product.php [hunk 4]
```diff
@@ -3406,6 +3414,7 @@ public static function priceCalculation(
                         'price' => $row['price'],
                         'ecotax' => $row['ecotax'],
                         'attribute_price' => (isset($row['attribute_price']) ? $row['attribute_price'] : null),
+                        'attribute_ecotax' => (isset($row['attribute_ecotax']) ? $row['attribute_ecotax'] : null),
```
Comment (Progi1984) [inline classes/Product.php]:
```suggestion
                        'attribute_ecotax' => $row['attribute_ecotax'] ?: null,
```

File: controllers/front/ProductController.php [hunk 5]
```diff
@@ -1032,7 +1032,9 @@ public function getTemplateVarProduct()
         $product['minimal_quantity'] = $this->getProductMinimalQuantity($product);
         $product['quantity_wanted'] = $this->getRequiredQuantity($product);
         $product['extraContent'] = $extraContentFinder->addParams(['product' => $this->product])->present();
-        $product['ecotax'] = Tools::convertPrice((float) $product['ecotax'], $this->context->currency, true, $this->context);
+
+        $productEcotax = $this->getProductEcotax($product);
+        $product['ecotax'] = Tools::convertPrice($productEcotax, $this->context->currency, true, $this->context);
```
Comment (Progi1984) [inline controllers/front/ProductController.php]:
```suggestion
        $product['ecotax'] = Tools::convertPrice($this->getProductEcotax($product), $this->context->currency, true, $this->context);
```

File: controllers/front/ProductController.php [hunk 6]
```diff
@@ -1096,6 +1098,25 @@ protected function getProductMinimalQuantity($product)
         return $minimal_quantity;
     }
 
+    /**
+     * @param $product
+     *
+     * @return float
+     */
+    protected function getProductEcotax($product): float
```
Comment (Progi1984) [inline controllers/front/ProductController.php]:
```suggestion
    protected function getProductEcotax(array $product): float
```

File: controllers/front/ProductController.php [hunk 7]
```diff
@@ -1096,6 +1098,25 @@ protected function getProductMinimalQuantity($product)
         return $minimal_quantity;
     }
 
+    /**
+     * @param $product
```
Comment (Progi1984) [inline controllers/front/ProductController.php]:
```suggestion
     * @param array $product
```

**Review by Progi1984 — COMMENTED** [review]
Small feedbacks but it's a good job

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 1 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js]: Actually I now use the scope variable `displayPricePrecision` which is fetched from data attribute Much better

File: admin-dev/themes/default/js/bundle/product/product-combinations.js (hunk 3 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/product-combinations.js]: It was removed mostly after a bug fix ^^ better get the data from the input JIT rather than maintaining data attributes on the whole page

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 8]
```diff
@@ -1622,17 +1624,32 @@ var priceCalculation = (function() {
...
-    return Tools.parseFloatFromString(ecoTaxElem.val()) / (1 + ecoTaxRate);
+    var ecoTax = Tools.parseFloatFromString(ecoTaxElem.val());
+
+    if (isNaN(ecoTax)) {
+      ecoTax = 0;
+    }
+
+    if (ecoTax === 0) {
+      return ecoTax;
+    }
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/bundle/product/form.js]:
```suggestion
    if (isNaN(ecoTax) || ecoTax === 0) {
      return ecoTax;
    }
```

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 9]
```diff
@@ -1547,7 +1547,11 @@ var priceCalculation = (function() {
   var taxElem = $('#form_step2_id_tax_rules_group');
   var reTaxElem = $('#step2_id_tax_rules_group_rendered');
   var displayPricePrecision = priceHTElem.attr('data-display-price-precision');
-  var ecoTaxRate = ecoTaxElem.attr('data-eco-tax-rate');
+  var ecoTaxRate = Number(ecoTaxElem.attr('data-eco-tax-rate'));
+  if (isNaN(ecoTaxRate)) {
+    ecoTaxRate = 0;
+  }
+  ecoTaxRate = ecoTaxRate / 100;
```
Comment (PierreRambaud) [inline admin-dev/themes/default/js/bundle/product/form.js]:
```suggestion
  if (isNaN(ecoTaxRate)) {
    ecoTaxRate = 0;
  } else {
    ecoTaxRate = ecoTaxRate / 100;
  }
```

No need to divide if it's 0

File: admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js [hunk 10]
```diff
@@ -171,17 +176,24 @@ export default function() {
...
-        var jQueryFinalPriceEl = jQueryRow.find(finalPriceSelector);
-        var impactOnPriceEl = jQueryRow.find(impactOnPriceSelector);
-        var impactOnPrice = impactOnPriceEl.val();
-
-        jQueryFinalPriceEl.data('price', newPrice);
-        // calculate new price
-        var newFinalPrice = new Number(newPrice) + new Number(impactOnPrice);
-        jQueryFinalPriceEl.text(ps_round(newFinalPrice, 6));
+        var tableRow = $('#'+item.id);
+        var attributeId = tableRow.attr('data');
```
Comment (PierreRambaud) [inline admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js:182]:
```suggestion
        var attributeId = tableRow.data();
```

Shouldn't be this?

**Review by Julievrz — DISMISSED** [review]

File: classes/Product.php [hunk 11]
```diff
@@ -2396,6 +2396,10 @@ public function getAttributesResume($id_lang, $attribute_value_separator = ' - '
             } else {
                 $combinations[$key]['quantity'] = Cache::retrieve($cache_key);
             }
+
+            $ecotax = (float) $combinations[$key]['ecotax'] ?? 0;
+            $combinations[$key]['ecotax_tax_excluded'] = $ecotax;
+            $combinations[$key]['ecotax_tax_included'] = Tools::ps_round($ecotax * (1 + Tax::getProductEcotaxRate() / 100), 6);
```
Comment (atomiix) [inline classes/Product.php]: Shouldn't the `6` be a const or took from a configuration?

**Review by Progi1984 — DISMISSED** [review]

File: classes/Product.php (hunk 11 above)
Comment (jolelievre) [reply classes/Product.php]: Yes, you're right!!

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jolelievre, @MatShir,

>Edit ecotax in a product with combinations, it now overrides the product's value and is correctly displayed in FO

I need some specs to follow because I find some differences.
Steps to reproduce the issue:
1. Go to BO > International > Taxes page > Enable ecotax
2. Go to BO > Catalog > Products page > Add new product with combinations
3. In the Pricing Tab
Price tax excluded = €6 / Price (tax incl.) = €12 / Tax rule = 20% / ecotax = 4.8 tax included
image
4. Edit the combination > set impact on price (tax excluded) = 10 / Impact on price tax included = 12 / Ecotax (tax incl.) = **0** or Ecotax (tax incl.) = 4.8 => I have same result
5. See the final price of the combination = 20.8 
5.1. **Ecotax (tax incl.) = 4.8** 
image
image
5.2 **Ecotax (tax incl.) = 0**
image
image

6. In the FO > I have same result also
image

To conclude, I have three cases in the Edit combination page
1. If Ecotax impact = 0 or Ecotax of original product( in my case =4.8) => same result
image

2. If 0 < Ecotax impact < 4.8 =>  Impact on price of the combination is increased 
image

3. If Ecotax impact > 4.8 =>  Impact on price of the combination is descresed
image


Thank you!

**Comment by MatShir** [comment]
Hi @khouloudbelguith,
All the behaviors you listed are good. Here is the specification -> https://github.com/PrestaShop/prestashop-specs/pull/236.
Can you tell me if they are clear enough and answer all your questions? :)

**Comment by jolelievre** [comment]
Hi @khouloudbelguith 
does the 👍. on mateus' comment mean you will look into it? or does it mean it's ok and we can merge this one? ^^
(I know you're focused on testing the RC1 build so I guess it will wait for next week?)

**Comment by khouloudbelguith** [comment]
Hello @jolelievre, @MatShir,

I will look into it as a priority after the test of the release 178rc1.

Thank you!

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I have a behavior, I don't know exactly if it is ok or not.
I need your confirmation @jolelievre @MatShir 
**Spec**:
```
IF a product with combination has an ecotax equal to 0 and the user adds a new ecotax price to the combination
THEN
The impact on the price of the combination is subtracted from the ecotax, so the final retail price is not impacted.
```
Steps to reproduce the issue:
1. Go to BO > International > Taxes > Enable Ecotax with No tax 
image
2. Create a product with combinations: price price = 0 / tax rule = 20% / ecotax = 0
image
3. Edit the first combination:
Impact on price tax excluded = 20 / Impact on price (tax incl.) = 24 / Final retail price (tax excl.) will be20 €
image
4. Set the ecotax of the combination to 10
4.1. The impact on the price of the combination is subtracted from the ecotax => **ok**
4.2. the final retail price is not impacted => **ok** 
image
5. Go to FO > Product details page
The product price = **22** = 12 +10 = Impact on price (tax incl.) + Ecotax = (Impact on price (tax excluded.) +20%) + ecotax => Is this correct ?
image

In the specs, we have **the final retail price is not impacted** = 20 tax excluded => so the product price tax included = 20 +20% = 24 and not 22 
What do you think? Thanks!

**Spec**
```
IF a product with combination has an ecotax set and the user adds a new ecotax price to the combination lower than the ecotax of the product
THEN
The impact on the price of the combination is increased from the ecotax combination, so the final retail price is not impacted.
```

1. Create a product with combinations: 
Price tax included = 12 / tax rule = 20% / Ecotax = 2
image
2. Edit combination
Impact on price tax excluded = 20 / Impact on price (tax incl.) = 24 / Final retail price (tax excl.) will be30.3333 €
image
3. Set the ecotax of the combination to 1 lower than the ecotax of the product
3.1. The impact on the price of the combination is increased from the ecotax combination => ok
3.2. so the final retail price is not impacted => ok 
image
4. Go to FO > Product details page
The product price = 36.2 = price product tax included + impact on price tax included  - ecotax of the combination = 12 + 25.2 -1 => is that correct ? 
image

**Specs**
```
IF a product with combination has an ecotax set and the user adds a new ecotax price to the combination superior than the ecotax of the product
THEN
The impact on the price of the combination is subtracted from the ecotax.
The final retail price is not impacted and the ecotax from the combination is displayed in the front office
```

1. Create a product with combinations: 
Price tax included = 12 / tax rule = 20% / Ecotax = 2
image
2. Edit combination
Impact on price tax excluded = 20 / Impact on price (tax incl.) = 24 / Final retail price (tax excl.) will be30.3333 €
image
3. Set the ecotax of the combination to 10 superior than the ecotax of the product
3.1. The impact on the price of the combination is subtracted from the ecotax => NOK, impact on price tax excluded = 12 = original impact (=20) - Ecotax of the combination (=10) + Ecotax product ( =2) = 20 - 10 +2 = 12 => Is that correct? 
3.2. The final retail price is not impacted 
image

4. Go to Fo > product details page
Product price = 34.40 = product price tax included (=12) + Impact on price (tax incl.) (=14.4) + ecotax combination ( =10) - ecotax product (=2) = 12 + 14.40 + (10 - 2)  = 34.40

=> Is that correct? if yes, I think in the FO **Including €10.00 for ecotax** should be **Including €8.00 (10-2) for ecotax** 
image


Thank you!
Sorry again!

Thank you!

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 12]
```diff
@@ -1692,15 +1707,22 @@ var priceCalculation = (function() {
...
       });
 
-      /** combinations : update TTC price field on change */
+      /** combinations : update TTC price field on HT change */
       $(document).on('keyup', '.combination-form .attribute_priceTE', function() {
         priceCalculation.impactTaxInclude($(this));
         priceCalculation.impactFinalPrice($(this));
       });
-      /** combinations : update HT price field on change */
+      /** combinations : update HT price field on TTC change */
```
Comment (matks) [inline admin-dev/themes/default/js/bundle/product/form.js:1715]: TTC is French if I am not wrong?

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 13]
```diff
@@ -1692,15 +1707,22 @@ var priceCalculation = (function() {
         priceCalculation.taxExclude();
       });
 
-      /** combinations : update TTC price field on change */
+      /** combinations : update TTC price field on HT change */
```
Comment (matks) [inline admin-dev/themes/default/js/bundle/product/form.js:1710]: HT is French if I am not wrong

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 14]
```diff
@@ -1771,57 +1793,296 @@ var priceCalculation = (function() {
...
+      var productPrice = priceCalculation.getProductBasePrice();
+      var productPriceTI = this.computePriceTaxIncluded(productPrice);
+      var ecotaxTI = this.getCombinationEcotaxTaxIncluded(obj);
+      // If no ecotax for combination use the product's one
+      if (ecotaxTI <= 0) {
+        ecotaxTI = getEcotaxTaxIncluded();
+      }
+
+      // Compute impact price tax excluded then update the price tax included
+      var impactPriceTI = currentFinalPriceTI - ecotaxTI - productPriceTI;
```
Comment (matks) [inline admin-dev/themes/default/js/bundle/product/form.js:1978]: I'm soooo afraid of mathematical inaccurate operations 😨  in this statement

File: admin-dev/themes/default/js/bundle/product/form.js [hunk 15]
```diff
@@ -1771,57 +1793,296 @@ var priceCalculation = (function() {
...
+      impactPriceTI = ps_round(impactPriceTI, displayPricePrecision);
+      impactPriceTI = truncateDecimals(impactPriceTI, displayPricePrecision);
```
Comment (matks) [inline admin-dev/themes/default/js/bundle/product/form.js:1980]: So we truncate after round. I guess there will be some usecases where this will give us inaccurate computations 😞

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig [hunk 16]
```diff
@@ -35,7 +35,19 @@
         </div>
     </td>
     <td class="attribute-finalprice text-sm-right">
-      <span data-price="{{ form.vars.value.final_price }}" data-uniqid="{{ form.vars.value.id_product_attribute }}">{{ form.vars.value.final_price }}</span> {{ default_currency }}
+      <div>
+        <span class="final-price" data-price="{{ form.vars.value.final_price }}" data-uniqid="{{ form.vars.value.id_product_attribute }}">{{ form.vars.value.final_price }}</span> {{ default_currency }}
+      </div>
+      {% if 'PS_USE_ECOTAX'|configuration != 0 %}
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig:41]: I did not know we could do that 😄

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig [hunk 17]
```diff
@@ -35,7 +35,19 @@
...
+        {% set attributeEcotax = form.vars.value.attribute_ecotax %}
+        {% if attributeEcotax == 0 %}
```
Comment (matks) [inline src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig:43]: This could be done in php, not in the view?

**Review by matks — APPROVED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 12 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js:1715]: Yep, but I used the same wording that was already present 🤷‍♂️

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 14 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js:1978]: You mean just like every computing we have so far in all the BO? 😅
(Except ONE use case in new product page)

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 15 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js:1980]: Honestly, I'm not sure the truncate is really useful, since we already round with the precision before.. But I copied some existing code from the current product page to remain consistent

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig (hunk 16 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig:41]: Yep, me neither! That's quite useful actually!

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig (hunk 17 above)
Comment (jolelievre) [reply src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig:43]: Maybe indeed, but it would mean adding some "parsing" of the form data all the time just for this.. it might be more complex for not much more value Besides this part is only used for display and as a reminder

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 14 above)
Comment (matks) [reply admin-dev/themes/default/js/bundle/product/form.js:1978]: Yes 😛  but making the list bigger is no good

Out of the scope of this PR I agree 👍 

By the way, on Product Page V2, do we have something for accurate JS mathematical operations?

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 15 above)
Comment (matks) [reply admin-dev/themes/default/js/bundle/product/form.js:1980]: I understand 👍

**Review by matks — DISMISSED** [review]

File: admin-dev/themes/default/js/bundle/product/form.js (hunk 14 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/form.js:1978]: Yep now we do we introduced `bignumber.js` That's the ONE use case I mentioned, it's only implemented for product price computing for now, but it should be used everywhere in this page

That's why I don't mind adding some additional float computing since the page is being migrated anyway, and the idea is not to rework the whole legacy page for a bug fix

**Review by PierreRambaud — DISMISSED** [review]

File: src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig [hunk 18]
```diff
@@ -161,7 +173,8 @@
                         </fieldset>
                     </div>
                     <div class="col-md-3">
-                      <small class="form-control-label vcenter">{{ "Final retail price (tax excl.) will be"|trans({}, 'Admin.Catalog.Feature') }} <span class="final-price" data-price="{{ form.vars.value.final_price }}" data-uniqid="{{ form.vars.value.id_product_attribute }}">{{ form.vars.value.final_price }}</span> {{ default_currency }}</small>
+                      <div class="form-control-label vcenter">{{ "Final retail price (tax excl.) will be"|trans({}, 'Admin.Catalog.Feature') }} <span class="final-price" data-price="{{ form.vars.value.final_price }}" data-uniqid="{{ form.vars.value.id_product_attribute }}">{{ form.vars.value.final_price }}</span> {{ default_currency }}</div>
+                      <div class="form-control-label vcenter">{{ "Final retail price (tax incl.) will be"|trans({}, 'Admin.Catalog.Feature') }} <span class="final-price-tax-included" data-price="{{ form.vars.value.final_price_tax_included }}" data-uniqid="{{ form.vars.value.id_product_attribute }}">{{ form.vars.value.final_price_tax_included }}</span> {{ default_currency }}</div>
```
Comment (jolelievre) [inline src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_combination.html.twig:177]: @Julievrz I believe this is the only new wording, I just copied and adapted it from the existing `Final retail price (tax excl.) will be"`
Is it ok for you?

File: admin-dev/themes/default/js/bundle/product/product-combinations.js [hunk 19]
```diff
@@ -54,16 +55,24 @@ var combinations = (function() {
       if (!tableRow.is('tr')) {
           throw new Error('Structure of table has changed, this function needs to be updated.');
       }
-      var priceImpactInput = tableRow.find('.attribute_priceTE').first();
-      var finalPriceLabel = tableRow.find('.attribute-finalprice span');
 
-      var impactOnPrice = Tools.parseFloatFromString(priceImpactInput.val());
-      var previousImpactOnPrice = Tools.parseFloatFromString(priceImpactInput.attr('value'));
+    // We need this because there is a specific data="smthg" attribute so we can't use data() function
```
Comment (Progi1984) [inline admin-dev/themes/default/js/bundle/product/product-combinations.js]:
```suggestion
      // We need this because there is a specific data="smthg" attribute so we can't use data() function
```

**Review by Progi1984 — DISMISSED** [review]

File: admin-dev/themes/default/js/bundle/product/product-combinations.js [hunk 20]
```diff
@@ -54,16 +55,24 @@ var combinations = (function() {
...
+      finalPriceLabel.html(finalPrice);
 
-      finalPriceLabel.html(Number(ps_round(finalPrice, 6)).toFixed(6));
+      // Update ecotax preview (tax included)
+      var combinationEcotaxTI = priceCalculation.getCombinationEcotaxTaxIncludedById(attributeId);
+      if (combinationEcotaxTI === 0) {
+        combinationEcotaxTI = priceCalculation.getProductEcotaxTaxIncluded();
+      }
+      var ecoTaxLabel = tableRow.find('.attribute-finalprice span.attribute-ecotax');
+      ecoTaxLabel.html(Number(ps_round(combinationEcotaxTI, 2)).toFixed(2)); // 2 digits for short
```
Comment (atomiix) [inline admin-dev/themes/default/js/bundle/product/product-combinations.js:73]: Can't we use the priceDisplayPrecision here instead of the hardcoded `2`?

File: admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js [hunk 21]
```diff
@@ -171,17 +176,25 @@ export default function() {
...
+        var finalPriceLabel = tableRow.find('.attribute-finalprice span.final-price');
+        finalPriceLabel.html(finalPrice);
+
+        // Update ecotax preview (tax included)
+        var combinationEcotaxTI = priceCalculation.getCombinationEcotaxTaxIncludedById(attributeId);
+        if (combinationEcotaxTI === 0) {
+          combinationEcotaxTI = priceCalculation.getProductEcotaxTaxIncluded();
+        }
+        var ecoTaxLabel = tableRow.find('.attribute-finalprice span.attribute-ecotax');
+        ecoTaxLabel.html(Number(ps_round(combinationEcotaxTI, 2)).toFixed(2)); // 2 digits for short
```
Comment (atomiix) [inline admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js:195]: Same here

File: admin-dev/themes/default/js/bundle/product/product-combinations.js (hunk 20 above)
Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/product-combinations.js:73]: No in this case the 2 is on purpose, this is displayed in the Combination list and using 6 decimals was kind of ugly (it's just a reminder in the list, when you edit the combination you get the full price with 6 decimals)

Capture d’écran 2021-07-27 à 12 44 32
(here because of the `Ecotax` label it would take two lines and it's really not ideal.. and this value is only for display)

Capture d’écran 2021-07-27 à 12 44 39
(In the edition though we have more precision)

File: admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js (hunk 21 above)
Comment (jolelievre) [reply admin-dev/themes/new-theme/js/product-page/product-bulk-combinations.js:195]: Same reason as above, in the list the space is limited which is why I chose to only display two digits

File: admin-dev/themes/default/js/bundle/product/product-combinations.js (hunk 20 above)
Comment (atomiix) [reply admin-dev/themes/default/js/bundle/product/product-combinations.js:73]: I think the priceDisplayPrecision is 2 by default though, 6 is for compute precision I think

Comment (jolelievre) [reply admin-dev/themes/default/js/bundle/product/product-combinations.js:73]: Indeed, but actually, the display precision value used here is a hardcoded value of 6 that comes from:
https://github.com/PrestaShop/PrestaShop/blob/3d06748975e00c548e940bf82862d9d211ae94d4/src/PrestaShopBundle/Form/Admin/Type/CommonAbstractType.php#L37

I just fixed a bug related to this precision, I thought I could rely on computing precision but we reverted the changes and it's always 2, so it turns out in some cases the display precision is better (6) And in this case we absolutely need an accurate precision

So it's really badly done but I admit but I don't plan on fixing all the legacy inconsistencies related to precision in this PR... I already banged my head enough this morning because it made no sense.. Now it works that's all I care about for now 😅

**Review by atomiix — APPROVED** [review]

File: classes/order/OrderDetail.php [hunk 22]
```diff
@@ -64,7 +64,11 @@ class OrderDetailCore extends ObjectModel
     /** @var int */
     public $product_quantity_reinjected;
 
-    /** @var float Without taxes, includes ecotax */
+    /**
+     * @deprecated since 1.5 Use unit_price_tax_excl instead
```
Comment (matks) [inline classes/order/OrderDetail.php:68]: Deprecated since 1.5 ? 🤔

**Review by matks — APPROVED** [review]
I approve this PR. I understand this is a compromise between the need to fix the bug in a patch version and the needed changes to fix it properly.

I only ask for one thing, which does not require to modify this PR 😄 : create an issue in https://github.com/PrestaShop/docs/  that would be "Explain in 1.7 the different order and order details database fields, which are rounded, which are not, which are tax excl. (when it's not obvious), which are tax incl., which are considered when shipping is modified, tax is modified ... basically all the crazy stuff you had to dig up from the legacy code (so it would be similar to https://github.com/PrestaShop/docs/issues/601 but for order, not for cart). This would be the starting point for someone who wants to fix the order and cart database schema in order to fix for good those issues.

I am 99% sure with a better database schema, such fixes would be easier.

File: src/Adapter/Product/AdminProductWrapper.php [hunk 23]
```diff
@@ -137,8 +139,19 @@ public function processProductAttribute($product, $combinationValues)
         if (!isset($combinationValues['attribute_weight_impact'])) {
             $combinationValues['attribute_weight_impact'] = 0;
         }
+
+        // This is VERY UGLY, but since ti ComputingPrecision can never return enough decimals for now we have no
```
Comment (matks) [inline src/Adapter/Product/AdminProductWrapper.php:143]:
```suggestion
        // This is VERY UGLY, but since the ComputingPrecision can never return enough decimals for now we have no
```

File: classes/order/OrderDetail.php (hunk 22 above)
Comment (jolelievre) [reply classes/order/OrderDetail.php:68]: As far as I could find yes, deprecated since unit_price_tax_excl was introduced

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

It is ok :heavy_check_mark: 
I checked the three cases of spec with display = tax excluded / = tax included
1. `IF a product with combination has an ecotax equal to 0 and the user adds a new ecotax price to the combination
THEN
The impact on the price of the combination is subtracted from the ecotax, so the final retail price is not impacted.` => ok with ecotax tax = 0 / 10% / 20%
2. `IF a product with combination has an ecotax set and the user adds a new ecotax price to the combination lower than the ecotax of the product
THEN
The impact on the price of the combination is increased from the ecotax combination, so the final retail price is not impacted.` => ok with ecotax tax = 0 / 10% / 20%
3. `IF a product with combination has an ecotax set and the user adds a new ecotax price to the combination superior than the ecotax of the product
THEN
The impact on the price of the combination is subtracted from the ecotax.
The final retail price is not impacted and the ecotax from the combination is displayed in the front office` => ok with ecotax tax = 0 / 10% / 20%

Create order from BO / FO with guest & customer
Check invoice (ecotax = 0 => new detail in the tax detail / combination with ecotax => well displayed
Edit order (product price & quantity)
I checked ecotax tax = 0 / 10% / 20%
Issue https://github.com/PrestaShop/PrestaShop/issues/24529 => fixed: I checked from the BO > Add new Order page & from BO > Orders > View Order page

Thanks!

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
THe wording has not changed. So I apply the wording :heavy_check_mark:, @Julievrz ;)

**Comment by Progi1984** [comment]
Thanks @jolelievre @Julievrz & @khouloudbelguith
