### PR TITLE
Use _DB_PREFIX_ constant instead of ps_ in SQL queries

### LINKED ISSUE #25617: FO - Using a limited cart rule crashes checkout at shipping step if the database prefix is not ps_
#### Describe the bug

The 'Total available for each user' in cart rule not considered if the customer is signed in from the checkout page.

#### Steps to Reproduce

1. Install PS 1.7.7.6, choose a prefix different from `ps_` from database

Capture d’écran 2021-08-16 à 17 11 56

2. This creates your shop and all your SQL tables use this prefix

Capture d’écran 2021-08-16 à 17 03 35

3. Create a cart rule. Choose a name, a description and generate a code.

Then use the following settings:
- Condition - Total available = 10
- **Condition - Total available for each user =1**
- Action - Discount = 1 euro
4. Save cart rule
5. Go to FO > add a product to cart, go to checkout, create a FO account
6. Add the created cart rule to your cart
7. Try to place the order. When you click "continue" after 'choose delivery method' it should crash
Capture d’écran 2021-08-16 à 17 10 16

#### Additional information

* PrestaShop version: 177x(PS1776), 178_rc1
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by idnovate**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | _DB_PREFIX_ is not used, so it throws an error with installations not using 'ps_' as database prefix
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Ticket | Fixes https://github.com/PrestaShop/PrestaShop/issues/25617
| Deprecations?     | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25567)

### CODE REVIEW

File: classes/CartRule.php [hunk 1]
```diff
@@ -715,9 +715,9 @@ public function checkValidity(Context $context, $alreadyInCart = false, $display
 
                 $quantityUsed += (int) Db::getInstance()->getValue('
                     SELECT count(*)
-                    FROM ps_cart_cart_rule ccr
-                    INNER JOIN ps_cart c ON c.id_cart = ccr.id_cart
-                    LEFT JOIN ps_orders o ON o.id_cart = c.id_cart
+                    FROM ' . _DB_PREFIX_ . 'cart_cart_rule ccr
+                    INNER JOIN ' . _DB_PREFIX_ . 'cart c ON c.id_cart = ccr.id_cart
+                    LEFT JOIN ' . _DB_PREFIX_ . 'orders o ON o.id_cart = c.id_cart
```
Comment (PululuK) [inline classes/CartRule.php]:
```suggestion
                    FROM `' . _DB_PREFIX_ . 'cart_cart_rule` ccr
                    INNER JOIN `' . _DB_PREFIX_ . 'cart` c ON c.id_cart = ccr.id_cart
                    LEFT JOIN `' . _DB_PREFIX_ . 'orders` o ON o.id_cart = c.id_cart
```

**Review by PululuK — DISMISSED** [review]
😱😱

Thanks @idnovate

**Review by Progi1984 — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
I approve, but it has to be backported in 1.7.7.x branch and 1.7.8.x branch

**Comment by khouloudbelguith** [comment]
Hi @idnovate,

It is ok :heavy_check_mark: 

I checked with PHP7.2 + custom database prefix => ok
1. create cart rule with code Highlight enabled & disabled / without code 
2. Create orders with new customers / old customer / guest
3. Apply cart rules
I checked with PHP7.4 + custom database prefix => ok

I checked with PHP7.4 + prefix by default => ok

https://drive.google.com/file/d/1Tn9X3X1CH8TX_U_SDSr2Hw6PJl_BaEVJ/view?usp=sharing
Thanks!

**Review by sowbiba — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @idnovate
