### PR TITLE
Handle Shop context override in order editing

### LINKED ISSUE #21706: Edit quantity and deletion in order in BO in Multishop context : Totals are not updated
#### Describe the bug

In a multishop context : 
If a merchant edit the quantity of a product in an order in BO, in "All shops" context, an error is displayed and nothing is changed immediately.
After refresh, the quantity is updated, but not the "Summary" part of the product block, with the totals : "Products", "Taxes" and "Total".

When adding a product : It's OK.

On 176 : Adding or editing a product : OK.

Edit : The error is "An unexpected error occurred. [PrestaShopBundle\Exception\NotImplementedException code 0]: Shop context types other than "single shop" are not supported"

Edit 2 : 
When deleting a product, the same behaviour is happening, excepted there is no error displayed. But the deletion appears at first not to be working (nothing is changed), but after refresh, the product is indeed deleted, but the totals are not updated.

#### Expected behavior

 As a user, when I am in "all shop" I can edit an order.

#### Steps to Reproduce

0. Have an install with Multishop enabled and at least two active shops
1. Go to BO > Orders > Order details
2. Edit the quantity of a product in the order : An error message is displayed and the edition is not validated
3. Refresh the page : The quantity is updated in the product line, so is the price. But the summary is not updated.
4. Change the status of the order to "Payment accepted" : The invoice only has the quantity updated, but not the total prices
5. Go to FO > Customer orders > Order details : The quantity is updated, but not the total prices.

**Screenshots**

Screenrecord : 
https://drive.google.com/file/d/1H_Y-5-eZ1zGotXcmEdz_wEFMtpqoyjz4/view?usp=sharing

Resulting invoice : 
edit quantity multishop invoice

Order on the customer account in FO : 
edit quantity multishop customer view

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Some errors happened when stock movement needed to be added, because `StockManagementRepository` constructor checks that we are in single shop context So the ContextStateManager is now able to override the shop context which allows to perform any modif even when you are in All shops context (it forces the order's shop in the context just the time to make the changes)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21706
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21721)

### CODE REVIEW

File: classes/order/Order.php [hunk 1]
```diff
@@ -2681,6 +2681,30 @@ public function getOrderDetailTaxes()
         );
     }
 
+    /**
+     * @param int $productId
+     * @param int $productAttributeId
+     *
+     * @return int|null
+     */
+    public function getProductSpecificPriceId(int $productId, int $productAttributeId): ?int
```
Comment (jolelievre) [inline classes/order/Order.php:2690]: I added this method because the `AbstractOrderHandler` and `OrderFeatureContext` didn't fetch the SpecificPrice ID the exact same way and it created errors and false positive/negative in the behat suite

So now they both use this method which ensures they both use the correct values, if this needs to be modified we won't have to update both classes now

File: classes/order/OrderDetail.php [hunk 2]
```diff
@@ -537,7 +537,7 @@ protected function checkProductStock($product, $id_order_state)
         if ($id_order_state != Configuration::get('PS_OS_CANCELED') && $id_order_state != Configuration::get('PS_OS_ERROR')) {
             $update_quantity = true;
             if (!StockAvailable::dependsOnStock($product['id_product'])) {
-                $update_quantity = StockAvailable::updateQuantity($product['id_product'], $product['id_product_attribute'], -(int) $product['cart_quantity']);
+                $update_quantity = StockAvailable::updateQuantity($product['id_product'], $product['id_product_attribute'], -(int) $product['cart_quantity'], $product['id_shop'], true);
```
Comment (jolelievre) [inline classes/order/OrderDetail.php:540]: Turns out the only moment when Stock movement were not updated was when they were added

File: src/Adapter/ContextStateManager.php [hunk 3]
```diff
@@ -154,6 +157,25 @@ public function setCustomer(?Customer $customer): self
...
+     *
+     * @return $this
+     *
+     * @throws \PrestaShopException
+     */
+    public function setShop(?Shop $shop, int $shopContextType = Shop::CONTEXT_SHOP): self
+    {
+        $this->saveContextField('shop');
+        $this->context->shop = $shop;
+        Shop::setContext(Shop::CONTEXT_SHOP, null !== $shop ? $shop->id : null);
```
Comment (jolelievre) [inline src/Adapter/ContextStateManager.php]: I hesitate to force the ALL_SHOP shop context when `$shop` is null?

Comment (matks) [reply src/Adapter/ContextStateManager.php]: I hesitate too 😛 I am not 100% sure that `$shop === null` is equivalent to ALL_SHOP ... 😅 for example what about CLI context and Webservice context

File: src/Adapter/ContextStateManager.php [hunk 4]
```diff
@@ -218,6 +245,18 @@ private function restoreContextField(string $fieldName): void
         $currentStashIndex = array_key_last($this->contextFieldsStack);
         // NOTE: array_key_exists important here, isset cannot be used because it would not detect if null is stored
         if (array_key_exists($fieldName, $this->contextFieldsStack[$currentStashIndex])) {
+            if ('shop' === $fieldName) {
```
Comment (matks) [inline src/Adapter/ContextStateManager.php:247]: So much logic, makes it tempting to even address it in a dedicated function `restoreShopContext()` ?

File: src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php [hunk 5]
```diff
@@ -101,10 +103,6 @@ public function handle(AddCartRuleToOrderCommand $command): void
      */
     private function addCartRuleAndUpdateOrder(AddCartRuleToOrderCommand $command, Order $order): void
     {
-        $computingPrecision = new ComputingPrecision();
```
Comment (matks) [inline src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php:104]: I dont see why these 3 lines are removed 🤔

File: src/Adapter/ContextStateManager.php (hunk 3 above)
Comment (jolelievre) [reply src/Adapter/ContextStateManager.php]: Yep that's why for now I thought it may be less risky to force single shop context when this setter is used but not assume any other behaviour when null is used 🤷‍♂️
Or maybe we should even not accept null and it would solve the problem

File: src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php (hunk 5 above)
Comment (jolelievre) [reply src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php:104]: Because they are actually useless 😅. 
At first I only removed `$precision` which was not used, then it highlighted the fact that the other two were also useless

File: src/Adapter/ContextStateManager.php (hunk 4 above)
Comment (jolelievre) [reply src/Adapter/ContextStateManager.php:247]: Yeah I also hesitated, I'm gonna add this one

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by kpodemski** [comment]
Hey @jolelievre 

Like I said on Slack, those all smarty functions related to back-office such a `displayPrice` were kept separaterly to force people to not use them in new theme architecture, and to keep back-office backward compatible, for example if you want to format price, do it on controller level and higher, not in view. Having them back will be confusing as functions like `{addJsDef}` might not work properly.

I'd use additional checking inside this file to load only required functions on front-office, not all of them.

**Comment by jolelievre** [comment]
@kpodemski 

thanks for the heads up Actually I think the problem that happens from time to time in the Travis tests comes from the PDF constructor: https://github.com/PrestaShop/PrestaShop/blob/b403594c7bc47474f3c61d2698e1d57ed390fbd1/classes/pdf/PDF.php#L100

It register these former smarty functions because the PDF templates were not updated and still rely on these So I guess in weird cases the `smarty` cloning of function registering doesn't happen correctly and it ends not registering these methods therefore they are unusable Maybe we should put some love in these PDFs and refacto them so that they don't need these methods any more.

Anyway that's not the purpose of this PR and travis tests are all green now ^^

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

I have an issue following these steps:

1. Enable Multishop Context.
2. Go to BO > Advanced Parameters > Multistore page
3. Create a new Group _`GroupA`_
image
4. Create a new shop _`ShopA`_ related to the _`GroupA`_
image
5. Create a `productA` in all shops 
6. Quantity of the `productA` in the shopA = 12
7. ShopA => create an order from the FO with the last product created (quantity ordered = 1)
8. Go to BO > Advanced Parameters > Multistore page
9. Edit the Group by default _`Default`_
10. Enable "Share available quantities to sell"
image
11. Go Back to the Order => last order created => All shops selected
12. Try to increase the quantity => you have an alert 
```php
"Error!
There are not enough products in stock."
```
But the **Available quantity > 0**
image

If you select the shopA => ok

I think, this issue should be specified by the @PrestaShop/product-team ?

I found this [spec](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/orders/orders/Order%20Page%20View.md#viii-multistore)

>_An order made from a specific shop can be edited from any shops. Even if the shop where the order is edited isn't in the same group as the shop where the order was made._

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @jolelievre,

It is ok :heavy_check_mark: 
Thanks to @Robin-Fischer-PS also :slightly_smiling_face: 
As discussed with @MatShir about this [issue](https://github.com/PrestaShop/PrestaShop/pull/21721#issuecomment-726107000), we will create another ticket.

Thank you all!

**Comment by PululuK** [comment]
Thanks @jolelievre

**Review by eternoendless — CHANGES_REQUESTED** [review]
Wait for 1.7.7.1

**Comment by eternoendless** [comment]
Dammit, I got here too late!

Let's just hope we don't need to revert this one 😅

**Comment by PululuK** [comment]
> Wait for 1.7.7.1

But I see the milestone is 1.7.7.0 ?
