### PR TITLE
Fix SQL syntax error in upgrade file to PS 1.7.6

### LINKED ISSUE #13068: Invalid mysql syntax during upgrade to 1.7.6
**Describe the bug**
Database upgrade file contains invalid sql syntax, which will cause an error during prestashop upgrade to 1.7.6

**To Reproduce**
It would occur during prestashop upgrade from 1.7.5 to 1.7.6, but we cannot test that easily while 1.7.6 is not released.

**Screenshots**
Problematic code: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.6.0.sql#L21
`IF EXISTS` cannot be used with `DROP INDEX` in mysql.
Error screenshot with mysql 5.7: 
Screenshot from 2019-03-27 12-31-05

**Additionnal information**
PrestaShop version: 1.7.6
PHP version: N/A

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix a SQL syntax error while upgrading to 1.7.6.0
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | Fixes #13068
| How to test?  | Run an upgrade, which must success on this request.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13223)

### CODE REVIEW

File: install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+ * versions in the future. If you wish to customize PrestaShop for your
+ * needs please refer to https://www.prestashop.com for more information.
+ *
+ * @author    PrestaShop SA <contact@prestashop.com>
+ * @copyright 2007-2019 PrestaShop SA and Contributors
+ * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
+ * International Registered Trademark & Property of PrestaShop SA
+ */
+
+function ps_1760_replace_index_of_admin_filter()
```
Comment (jolelievre) [inline install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php:29]: maybe we should create functions because this kind of scenario might happen again in the future, so having a `remove_table_index($table, $indexName)` and `add_table_index($table, $indexName)` might be useful

File: install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+    if ($key_exists) {
+      $res &= Db::getInstance()->execute('ALTER TABLE
+        `' . _DB_PREFIX_ . 'admin_filter`
+        DROP KEY `' . $index . '`');
+    }
+  }
+  $res &= Db::getInstance()->execute('ALTER TABLE
+    `' . _DB_PREFIX_ . 'admin_filter`
+    ADD UNIQUE INDEX `admin_filter_search_id_idx` (`employee`, `shop`, `controller`, `action`, `filter_id`)');
```
Comment (jolelievre) [inline install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php:41]: also when adding an index maybe you should perform a check first? especially for a unique index
sometimes upgrade script are launched multiple times (for test purposes for example), so it's safer to check if the index is already here (in a dedicated function as suggested in the first comment)

Comment (Quetzacoalt91) [reply install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php]: You're right, like we did for tab management.

File: install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php (hunk 1 above)
Comment (Quetzacoalt91) [reply install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php:29]: You're right, like we did for tab management.

Comment (jolelievre) [reply install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php:29]: yep that's the idea

Comment (Quetzacoalt91) [reply install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php:29]: I actually did not create a method for index creation, as their signature will always be different. Only the deletion has been included in the last commit.

File: install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php (hunk 2 above)
Comment (Quetzacoalt91) [reply install-dev/upgrade/php/ps_1760_replace_index_of_admin_filter.php:41]: Well, for this time let's delete it before recreate it.

**Review by jolelievre — APPROVED** [review]
Nice job @Quetzacoalt91

**Comment by jolelievre** [comment]
Thanks @Quetzacoalt91

**Comment by jolelievre** [comment]
Thanks @Quetzacoalt91
