### PR TITLE
Correct product meta-title after changing variant

### LINKED ISSUE #21391: FO - The product meta-title is incorrect after changing a combination
#### Describe the bug

the automatic page reload on product detail pages causes the meta title to get replaced with the product name

Issue is this line:
https://github.com/PrestaShop/PrestaShop/blob/b70d51837420275c5ad8c717162ddddb169e00d1/controllers/front/ProductController.php#L458

it needs to use $product['meta_title'] instead of $product['title']

#### Expected behavior

meta title should stay as it is

#### Steps to Reproduce

1. Have a product with a meta title != its name
2. Go to that product's front page
3. Either wait for the initial reload or change a combination or the quantity to cause one

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Follow #21391
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21391 
| How to test?  | Instruction below
| Sponsor company | impSolutions

Follow these steps before, and after change:

1. Edit product with combinations, set custom meta title.
2. Visit product, see if meta title is OK
3. Change variant, meta title NOK
4. To confirm that it's only bugged in ajax request refresh page, meta title OK

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21394)

### CODE REVIEW

File: controllers/front/ProductController.php [hunk 1]
```diff
@@ -455,7 +455,7 @@ public function displayAjaxRefresh()
             'product_minimal_quantity' => $minimalProductQuantity,
             'product_has_combinations' => !empty($this->combinations),
             'id_product_attribute' => $product['id_product_attribute'],
-            'product_title' => $product['title'],
+            'product_title' => $product['meta_title'],
```
Comment (PierreRambaud) [inline controllers/front/ProductController.php:459]:
```suggestion
            // We use the meta_title key because product_title is used for the title of the page
            'product_title' => $product['meta_title'],
```

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @kpodemski 

Following the scenario:
Edit product with combinations, set custom meta title.
Visit product, see if meta title is OK
Change variant, meta title NOK
To confirm that it's only bugged in ajax request refresh page, meta title OK
Capture d’écran 2020-10-12 à 14 19 57

==> TEST OK

Thank you

**Comment by NeOMakinG** [comment]
Damn, it looks like the issue aim to fix this bug on 1.7.7.x, what do we do there?

**Comment by kpodemski** [comment]
@NeOMakinG not really, it's not regression so I've decided to put it on `develop`, it's not critical etc.
