### PR TITLE
When refreshing an order, display shipping price if needed

### LINKED ISSUE #22071: BO - Order details - In the info block - The shipping is not refreshed after adding a product
#### Describe the bug

In the BO > Orders > Order detail page > when adding a product to an empty order, the Shipping is not updated in the info block
image
When we refresh the page => ok
image

#### Steps to Reproduce

1. Create order from the FO with only one product
2. In the Shipping steps " choose a carrier with fees (not free)"
3. Delete the product and refresh: The order is empty
4. Add a product to the order => NOK
image
5. Refresh => ok
image

ps1.7.6.9 => OK
https://drive.google.com/file/d/1FURxcTRChiD9l5LLCChmaDD1vaha1oPq/view?usp=sharing

#### Additional information

* PrestaShop version: 1770Build1
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | When refreshing an order, display shipping price if needed
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #22071
| How to test?  | Build assets & Cf. #22071

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22171)

### CODE REVIEW

File: admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js [hunk 1]
```diff
@@ -35,11 +35,15 @@ export default class OrderPricesRefresher {
 
   refresh(orderId) {
     $.ajax(this.router.generate('admin_orders_get_prices', {orderId})).then(response => {
+      console.log(response);
+      console.log(OrderViewPageMap.orderShippingTotalContainer);
+      console.log($(OrderViewPageMap.orderShippingTotalContainer));
```
Comment (NeOMakinG) [inline admin-dev/themes/new-theme/js/pages/order/view/order-prices-refresher.js]:
```suggestion
```

**Review by NeOMakinG — CHANGES_REQUESTED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
Apparently, it's breaking a sanity test...

**Comment by NeOMakinG** [comment]
> Apparently, it's breaking a sanity test...

Looks unrelated

**Review by atomiix — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an error following these steps:

1. Create an order from the FO with two different products
2. In the Shipping steps " choose a carrier with fees (not free)"
3. In BO > Orders > last order created page
4. Delete a product
5. see the error
6. The shipping is not displayed(it is removed)
image
7. Reload the page => ok
image


I have an issue also following these steps:

1. Create an order from the FO with only one product (not a virtual product)
2. In the Shipping steps " choose a carrier with fees (not free)"
3. In BO > Orders > last order created page > Delete the product and refresh: The order is empty
4. Add a new virtual product (`demo_19`) to the order
5. See error => the Shipping is displayed (price => ok)
image
6. Reload the page => ok
image


Thanks!

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1bIPWZLMr7iY_C89ewzocZd0RY-10Ecpo/view?usp=sharing
PS: I found this [regression](https://github.com/PrestaShop/PrestaShop/issues/22424) during testing this PR, but it is reproduced without PR also.
Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith
